### ISSUE TITLE
Provide feedback on Microsoft 365 Defender

### ISSUE THREAD

**Issue by s3c1t2** [MicrosoftDocs/microsoft-365-docs#10003]
For several months and on a regular bases I've submit feedback pertaining to Microsoft 365 Defender placement of the "Feedback" button.  

Case in point; take a look at  https://learn.microsoft.com/en-us/microsoft-365/security/defender/feedback?view=o365-worldwide - specifically under "Check out this video to see how easy it is to provide feedback." - no need to play the video.  Just look at the still image, bottom right hand corner displays the "Feedback" button.   When performing an investigation every minute loss is critical; not being able to view or scroll due to the "Feedback" pop-out button is time that will never be recovered.   

What is the rational for placing a "Feedback" button over the page content or scroll bar?

**Comment by msbemba** [comment]
@s3c1t2 Thank you for your feedback. A change in the placement of feedback button needs to be provided to the Product group. I'd recommend you providing the same on our main feedback portal (https://feedbackportal.microsoft.com/ ) so that our prodcut/dev engineer can work on it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @s3c1t2 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by s3c1t2** [comment]
Ping

**Comment by s3c1t2** [comment]
@msbemba & @yogkumgit Thank You for your suggestion and response.
