### ISSUE TITLE
Missing OS version

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#10001]
Below **Requirements for Microsoft Defender Antivirus to run in passive mode** OS versions are listed, but Server 2012R2 and Server 2016 are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61024433-366d-5ea3-4a3f-0cdd5cdcd900
* Version Independent ID: 348d3fc9-0937-b3a6-897e-09d1236d7019
* Content: [Microsoft Defender Antivirus compatibility with other security products](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@andrePKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10012

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andrePKI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
