### ISSUE TITLE
MacOS Network Protection release ring command incorrect

### ISSUE THREAD

**Issue by NoahTaylorMonet** [MicrosoftDocs/microsoft-365-docs#10004]
MDE documentation on MacOS Network Protection looks to be no longer accurate:

Under the Prerequisites section it has this command to change the release ring on MacOS so that Network Protection can be enabled.

defaults write com.microsoft.autoupdate2 ChannelName -string InsiderSlow

I confirmed on mine that instead of InsiderSlow, it needs to be set to External to get the InsiderSlow ring and be able to make use of Network Protection.

defaults write com.microsoft.autoupdate2 ChannelName -string External

Can this be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 415606ab-27e9-e125-d868-1e4636771d36
* Version Independent ID: 415606ab-27e9-e125-d868-1e4636771d36
* Content: [Use network protection to help prevent macOS connections to bad sites](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection-macos?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection-macos.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection-macos.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@NoahTaylorMonet Thank you for your feedback. The cmdlets have been updated to defaults write com.microsoft.autoupdate2 ChannelName -string External and no longer shows insiderslow

![image](https://user-images.githubusercontent.com/45987684/197456709-0f2eb419-54ce-43c7-8f4e-298984045377.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @NoahTaylorMonet Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
