### ISSUE TITLE
Describe the Audit Log Entries

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/microsoft-365-docs#10013]
The article mentions 

> Notifications and responses are tracked in the audit log.

but doesn't describe the audit log entries. Could we document at which steps audit log entries are written and the activity name for each entry?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Version Independent ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Content: [Manage ownerless Microsoft 365 groups and teams - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/ownerless-groups-teams?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/ownerless-groups-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/ownerless-groups-teams.md)
* Service: **microsoft-365-business**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please help us in resolving this issue. Thanks

**Comment by schumatt-msft** [comment]
> @schumatt-msft the audit log is covered in [Search the audit log in the compliance portal](https://learn.microsoft.com/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance). 

@MikePlumleyMSFT Makes sense. Great article, but unfortunately it doesn't look like it describes any of the ownerless group audit log entries (or anything for the M365 Group heading):

![image](https://user-images.githubusercontent.com/52325421/198032218-df62b10f-6360-4d17-9f0f-14bf80f7e63d.png)

Could some additional details be added there?

**Comment by MikePlumleyMSFT** [comment]
@schumatt-msft please open an issue on that article and the author will take a look.

**Comment by msbemba** [comment]
@MikePlumleyMSFT  I have added the article as a related topic to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10096

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @schumatt-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
