### ISSUE TITLE
Typo in the screenshot

### ISSUE THREAD

**Issue by MubDubs** [MicrosoftDocs/microsoft-365-docs#10016]
![2022-10-20 13_49_26-What is Microsoft 365 Defender_ _ Microsoft Learn — Mozilla Firefox](https://user-images.githubusercontent.com/75283373/197021735-7df2f0ca-889f-48cd-8cbc-11ef5e6f2759.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bed9a314-00dd-bffd-69fa-8f93228044b6
* Version Independent ID: 4cece1bf-38f8-e293-5178-4ac5ee70bddc
* Content: [What is Microsoft 365 Defender?](https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-defender?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-365-defender.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-defender.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MubDubs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10040

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MubDubs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
