### ISSUE TITLE
TYPO - PLD instead of DPL

### ISSUE THREAD

**Issue by serafing** [MicrosoftDocs/microsoft-365-docs#10015]
Change the line:
Exchange Online automatically relocates the user's mailbox if the PLD changes
to 
Exchange Online automatically relocates the user's mailbox if the PDL changes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6c94c2-33d6-12a4-ae18-c8448e8cc386
* Version Independent ID: a320a3b3-0301-10d7-e3fb-d3794ca248f1
* Content: [Microsoft 365 Multi-Geo tenant configuration - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-tenant-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/multi-geo-tenant-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/multi-geo-tenant-configuration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@serafing Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10039

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @serafing Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
