### ISSUE TITLE
Is custom SITs supported in Content Explorer

### ISSUE THREAD

**Issue by testad** [MicrosoftDocs/microsoft-365-docs#10023]
I recently created a custom SIT and was hoping to see the crawled results in Content Explorer. However, I see no details about if this is supported on this page, nor on the custom SIT documentation. 

Would appreciate to have that clarified.

Many thanks!

**Comment by yogkumgit** [comment]
@testad Please indicate which document you are referring to. Thanks

**Comment by testad** [comment]
Sorry for this. I used the submit feedback for "This Page" in the footer but it appears like it logged in the wrong place. I was referring to this page: https://learn.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer

I suspect that custom SITs will show up but that there is no entry in content explorer until the crawl has happened.

**Comment by testad** [comment]
Update: the custom SIT has now showed up in Content Explore after the schedule crawl happened. I found information about the crawl on the custom SIT docs and assumed this would impact visibility in the Content Explorer. You might want to add a note on the Content Explorer page about custom SIT delay due to crawl. It is no major, but as it takes a couple of days it might be helpful for people like myself.

**Comment by msbemba** [comment]
@testad Thank you for your feedback. We have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10056

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@testad closing as author has not approved the changes. Thanks
