### ISSUE TITLE
Protected Users are limited to 301, not 350.

### ISSUE THREAD

**Issue by workkirk** [MicrosoftDocs/microsoft-365-docs#10028]
Hello,

Via PS script I attempted to programmatically add 340 users to TargetedUsersToProtect. The operation completed without error.

Upon checking the policy in the Defender GUI, page reads that 301/350 are protected. Looking at the individuals on the list, I can easily identify where everything cut off.

Further attempts to manually or programmatically add entries to the list fail without error.

Thanks
Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70ea08aa-4520-8f48-93e2-0ce74cd43298
* Version Independent ID: 7be23d3d-f72b-abd3-e2c4-96ff3998a59b
* Content: [Configure anti-phishing policies in Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@workkirk Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10041

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chrisda** [comment]
@workkirk, I updated the 3 topics that said 350 to 301.

you should open a support ticket about this so the UI will get updated or the problem will get fixed so you really can enter 350 users.

Thanks for the feedback.

Closing
