### ISSUE TITLE
list specific features that require a shared mailbox to be licensed

### ISSUE THREAD

**Issue by GHSandy** [MicrosoftDocs/microsoft-365-docs#10029]
[Enter feedback here] Could the article be updated to list all advanced features that require a shared mailbox be licensed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 289f2440-9c44-7d93-20e3-baa9e9892cd9
* Version Independent ID: abc4e209-a071-d28a-cb01-aa72bbaee7c0
* Content: [About shared mailboxes - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/about-shared-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/about-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/about-shared-mailboxes.md)
* Service: **microsoft-365-business**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@GHSandy Thank you for your feedback. We have added a note on what features will be available when licensed

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GHSandy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
