### ISSUE TITLE
The steps for checking Storage Account Resource ID should be updated

### ISSUE THREAD

**Issue by morrow233** [MicrosoftDocs/microsoft-365-docs#10024]
[Enter feedback here]
Enable raw data streaming
https://learn.microsoft.com/en-us/microsoft-365/security/defender/streaming-api-storage?view=o365-worldwide#enable-raw-data-streaming

According to the description, Resource ID is displayed on text under Storage Account Resource ID.

======
In the Storage Account Resource ID box that appears, type your Storage Account Resource ID. To get your Storage Account Resource ID, open the Azure portal at https://portal.azure.com/, click Storage accounts > go to the properties tab > copy the text under Storage Account Resource ID.
======

But design might be changed as now it's not desplayed.
To know the resourse ID, it has to be checked by JSON View so please consider to update MDE docs.

Get storage account configuration information
https://learn.microsoft.com/en-us/azure/storage/common/storage-account-get-info?tabs=portal

======
To display the Azure Resource Manager resource ID for a storage account in the Azure portal, follow these steps:

Navigate to your storage account in the Azure portal.

On the Overview page, in the Essentials section, select the JSON View link.

The resource ID for the storage account is displayed at the top of the page.
======

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2c4ce0a-ea31-d97f-776e-237959a0c8b0
* Version Independent ID: c5be1cc5-404e-e6ee-336a-5bbe59b90d66
* Content: [Stream Microsoft 365 Defender events to your Storage account](https://learn.microsoft.com/en-us/microsoft-365/security/defender/streaming-api-storage?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/streaming-api-storage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/streaming-api-storage.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@morrow233 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10055

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @morrow233 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
