### ISSUE TITLE
Innacurate mapping of "Scoped deployment and privacy"

### ISSUE THREAD

**Issue by doug-msft** [MicrosoftDocs/microsoft-365-docs#10031]
Hi David, great job on this doc!
One minor correction. 
The "Scoped deployment and privacy" section went to "Settings-> Cloud apps -> System -> Scoped deployment and privacy"
![image](https://user-images.githubusercontent.com/116388443/197280243-c4000407-b6b5-4faa-82d0-fbca2de68aca.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c29e05f2-5a90-3457-220f-af7c4ad3c9f2
* Version Independent ID: c29e05f2-5a90-3457-220f-af7c4ad3c9f2
* Content: [Microsoft Defender for Cloud Apps in Microsoft 365 Defender (Preview)](https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
@doug-msft  - Thanks for pointing this out. We're working on the correction, should be out soon.
