### ISSUE TITLE
MDE AIR results definitions of “remediated, mitigated, resolved, and blocked??????

### ISSUE THREAD

**Issue by johnB007** [MicrosoftDocs/microsoft-365-docs#10030]
[Enter feedback here]
Posted in MSFT MDE DL and no one can answer - "Does anyone have a document or reference for the MDE AIR results definitions of “remediated, mitigated, resolved, and blocked”?  I have a CX requesting the definitions.  "

Does anyone have a document or reference for the MDE AIR results definitions of “remediated, mitigated, resolved, and blocked”?  I have a CX requesting the definitions.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e66cb3d-b771-af2b-860f-5355b2178db0
* Version Independent ID: 7ce9307c-ca00-cb47-6978-b9b09c139978
* Content: [Automated investigation and response in Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-air?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/office-365-air.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-air.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@johnB007 Thank you for your feedback. This document does not mention the status of remediated, mitigated, or resolved as this is AIR for Defender for 365, you can find the status here -https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/air-view-investigation-results?view=o365-worldwide#investigation-status

For MDE AIR. You can find more information about the investigation status here -https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/autoir-investigation-results?view=o365-worldwide#investigation-states


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @johnB007 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
