### ISSUE TITLE
Microsoft Defender Endpoint for Android supported profiles

### ISSUE THREAD

**Issue by PMLIO** [MicrosoftDocs/microsoft-365-docs#10037]
Please clarify this sentence "Corporate-owned, personally enabled" - such profile don't exist. Do you mean "Corporate-owned devices with work profile"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b355e15-45e5-e953-4089-fd4b6932dde3
* Version Independent ID: 092fbd46-65e6-8122-3a8b-404006d20aab
* Content: [Microsoft Defender for Endpoint on Android](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-android?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-android.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-android.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@PMLIO Thank you for your feedback. Corporate Owned, Personally Enabled (COPE) is a business model in which an organization provides its employees with mobile computing devices and allows the employees to use them as if they were personally-owned. 

If you continue to not see the profile, I'd recommend opening a support ticket with Microsoft via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Please reply.

**Comment by msbemba** [comment]
@PMLIO We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10057

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PMLIO Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
