### ISSUE TITLE
About mdatp_managed.json setting

### ISSUE THREAD

**Issue by mh-mnc11** [MicrosoftDocs/microsoft-365-docs#10038]
[Enter feedback here]
It is not possible to control all MDE communication only with proxy setting in this json. Please add notes or consider deleting it if it cannot be used normally.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04ef0d15-6735-bb94-0d86-d57ffbaa05f7
* Version Independent ID: 52e516b5-b365-4950-334a-c4797333093d
* Content: [Set preferences for Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-preferences?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-preferences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-preferences.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@mh-mnc11 Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10079

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mh-mnc11 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
