### ISSUE TITLE
Clarification on returning audit log events.

### ISSUE THREAD

**Issue by MrOCanada** [MicrosoftDocs/microsoft-365-docs#1004]
This document is well written. I have two questions for clarification:

It starts out with this statement. I will capitalize the main words for my question:
"Starting in January 2019, Microsoft is TURNING ON MAILBOX AUDIT LOGGING BY DEFAULT for all Office 365 organizations. This means that certain actions performed by mailbox owners, delegates, and admins are automatically logged, and the corresponding mailbox audit records will be available when you search for them in the mailbox audit log. Before mailbox auditing was turned on by default, you had to manually enable it for every user mailbox in your organization."

Under the More Information section:
"Only users with E5 licenses OR MAILBOXES WHERE MAILBOX AUDIT LOGGING WAS MANUALLY ENABLED BY AN ADMIN will return mailbox audit log events in audit log searches in the Security & Compliance Center or via the Office 365 Management Activity API."

Question 1: If Microsoft is "turning on mailbox audit logging by default" is it the same as if "mailbox audit logging was manually enabled by an admin"? I may be splitting hairs but just confirming.

Question 2: By "turning on mailbox audit logging by default" is this equal Microsoft setting the AuditDisabled value to false for the Set-OrganizationConfig Powershell command,  OR is it equal to Microsoft touching every existing mailbox and setting the AuditEnabled value to true for the Set-Mailbox Powershell command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing#feedback)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MrOCanada:

Answer to Question 1: Yes, 'on by default' and 'off by default but manually turned on for each individual mailbox' are effectively the same thing. Custom audited events vs. default audited events come into play, so be sure to understand default audited actions vs. customized audited actions as described in: https://docs.microsoft.com/microsoft-365/compliance/enable-mailbox-auditing#change-or-restore-mailbox-actions-logged-by-default.

Answer to Question 2: 'On by default' is: `Set-OrganizationConfig -AuditDisabled $false`, and the *AuditEnabled* value on the mailbox is ignored (even mailboxes where the value is `$false` still get audited for the default audited events).

**Comment by MrOCanada** [comment]
Thank you.
