### ISSUE TITLE
link not working - O365 Exit Planning Considerations

### ISSUE THREAD

**Issue by SebastianPiendl** [MicrosoftDocs/microsoft-365-docs#10046]
The following link is not working:

[O365 Exit Planning Considerations](https://servicetrust.microsoft.com/ViewPage/TrustDocuments?command=Download&downloadType=Document&downloadId=77ea7ebf-ce1b-4a5f-9972-d2d81a951d99&docTab=6d000410-c9e9-11e7-9a91-892aae8839ad_FAQ_and_White_Papers)

**Comment by denisebmsft** [comment]
Hello Sebastian! Can you please tell us which article has the broken link? Thank you

**Comment by SebastianPiendl** [comment]
Hi Denise, sorry! For creating the issue in the wrong feedback repo.
Following article has the broken link:
https://learn.microsoft.com/en-us/microsoft-365/compliance/customer-key-manage?view=o365-worldwide

**Comment by yogkumgit** [comment]
@SebastianPiendl Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
