### ISSUE TITLE
Latest Labkit21h2 and 11 fails to completely install all VMs

### ISSUE THREAD

**Issue by theobor** [MicrosoftDocs/microsoft-365-docs#10044]
As the title says I have tried numerus times to install the latest Microsoft365DeviceLabKit and Win10_21H2_lab on a 1TB HD and 32GB of Ram with a i7 CPU, not it is an older device.  It only seems to install parts of the server VM's and none of the client ones.  

Would these Labkit's require most up to date hardware that supports the latest TMP technology, as we know that win11 requires it unless you disable the option?

**Comment by denisebmsft** [comment]
Hello @theobor. Can you please tell us to which article(s) your feedback applies? Thank you

**Comment by theobor** [comment]
New to this and not sure what you mean but it is not referring to any article but to the actual installation of the Labkit's. Just a update I have tested this on a device that has the TPM 2 chip and it installed all the VM's. The problem is that the creation of the Client VM's are for more up to date hardware,

**Comment by yogkumgit** [comment]
@theobor Thank you very much for raising the issue. Considering the nature of the issue please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
