### ISSUE TITLE
Feedback "No Match" for custom SIT or Custom Trainable classifier: in the prompt from Microsoft, who is the admin for custom SITs?

### ISSUE THREAD

**Issue by sergioandreslq** [MicrosoftDocs/microsoft-365-docs#10053]
Hello Team, 
Topic: Content Explorer 

Question:
I created a custom SIT, the files are showed in Content Explorer. 
there are 2 buttons "No Match" and Match.

If I choose "not match": appear the message:
"Your feedback has been saved and will be reviewed by an **_### admin_** who manages classifiers"

If this is a custom SIT, who will receive the notification for this classifier?

![image](https://user-images.githubusercontent.com/75001072/197784665-c5154818-e182-45cb-b806-a9d48a894dc4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe2de60a-f10c-4991-350b-c29eec9bb54e
* Version Independent ID: fe2de60a-f10c-4991-350b-c29eec9bb54e
* Content: [Increase Classifier Accuracy - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/data-classification-increase-accuracy?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-increase-accuracy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-increase-accuracy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@sergioandreslq Thank you for your feedback. The feedback is usually submitted to the product team and you should hear back from them. If not, you can also contact the support team via the need help section in the admin center so that a support engineer can file a bug with the dev/product team to fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sergioandreslq Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
