### ISSUE TITLE
Message Center email alerts headers

### ISSUE THREAD

**Issue by fbarbier63** [MicrosoftDocs/microsoft-365-docs#10064]
A consideration for potential email tagging for main alerts posted on Message Center, could you all provide any type of tagging or email headers used for critical alerts such as Data Privacy as some alerts send emails with the MC number of some other ones such as Data Privacy only recommend to go consult the original message on the Message Center.
Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29f3771a-247c-4f85-992a-e671285c70bd
* Version Independent ID: f3c2890a-2470-9349-ff77-924cf8566365
* Content: [Message center in the Microsoft 365 admin center - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/message-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/message-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/message-center.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@fbarbier63 Thank you for your feedback. Since this is a technical question, I'd recommend you leave a feedback on our main feedback portal (https://feedbackportal.microsoft.com/ )  One of our Dev/Product team members will be able to help you out.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @fbarbier63 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
