### ISSUE TITLE
Bookings with Me looks to have been released to GA but multiple places with "Preview" indication

### ISSUE THREAD

**Issue by lbeamish** [MicrosoftDocs/microsoft-365-docs#10063]
Based on Road map this has gone to General Availability but seeing the Preview in the following places:
1) Outlook on the web 
![Outlookonweb](https://user-images.githubusercontent.com/61236578/197848707-9149075c-7e83-4558-a17e-0a68d1be68cc.png)
2) Bookings with Me FAQ:
Why is Bookings with me in preview?
Bookings with me is in preview for all enterprise users worldwide. We're collecting feedback and making improvement while it is being integrated into scheduling experiences in Bookings and Outlook.
https://learn.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide#why-is-bookings-with-me-in-preview

Can this be fixed? 
Laurie
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adb53eb7-85a1-6aa0-dfd1-e2b54586008a
* Version Independent ID: 5532470a-a47d-e3bd-4e74-02b2c822cae1
* Content: [Microsoft Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-overview.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@lbeamish Thank you for your feedback. I will work with the author and fix this with the help of Product owner. 

Thanks
Sri

**Comment by lauriebeamish** [comment]
Any word on when this will be fixed?  We are withholding our rollout of bookings with me until we see the "Preview" come off the web page.

**Comment by tiburd** [comment]
The "Preview" indication is no longer in the article. Closing this issue.
