### ISSUE TITLE
connect

### ISSUE THREAD

**Issue by 711712** [MicrosoftDocs/microsoft-365-docs#10068]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12f55a68-599b-2e28-7f74-ce0484d15afc
* Version Independent ID: 9936a89f-1118-061b-4382-e0b6b219febd
* Content: [Migrate email and contacts to Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/migrate-email-and-contacts-admin?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/migrate-email-and-contacts-admin.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/migrate-email-and-contacts-admin.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@711712 Thank you for your feedback. I'm not sure if your question is about connecting with admin credentials, if yes, that is correct. You will need to connect using the admin credentials in order to bulk import email, contacts, and calendars to Microsoft 365.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @711712 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
