### ISSUE TITLE
Operations not Documented

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/microsoft-365-docs#10067]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here
The below operations can be seen in the audit logs, however they are not documented:

CrmDefaultActivity has RecordType 21 - Member Name: CRM Description: Dynamics 365 events. Workload: CRM

AdminMailAccess  has RecordType 38 - Member Name: DataGovernance Description: Events related to retention policies and retention labels in the Security & Compliance Center. Workload: SecurityComplianceCenter

This is also missing a definition on the management api schema https://review.learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema?branch=main however issues can't be opened on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://review.learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide&branch=main#search-the-audit-log)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@asdcristi - thanks for the feedback. As an internal MS contact, I'll send you an internal email with the link to the content request form so you can submit this request there. Submitting internally is easier for me and the PG team to review, confirm, and approve.
