### ISSUE TITLE
Missing rate limits for /api/deviceavinfo 

### ISSUE THREAD

**Issue by yowsa** [MicrosoftDocs/microsoft-365-docs#10071]
Can you please update the rate limit for the "1 Export health reporting (JSON response)" option, it currently only lists example rate limits and I urgently need this.

thank you!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 881f771d-1eb6-96ac-5652-53ba7183d9e0
* Version Independent ID: 881f771d-1eb6-96ac-5652-53ba7183d9e0
* Content: [Microsoft Defender Antivirus Device Health export device antivirus health reporting](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@yowsa Thank you for your feedback. The  Rate limitations for this API are (**_example_** 30 calls per minute and 1000 calls per hour.)

Document update via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10097

**Comment by yowsa** [comment]
Thanks for the quick reply, however the text still references this as an example rate not the actual rate limit. Is this the actual limit or just an example still? :) 

> @yowsa Thank you for your feedback. The  Rate limitations for this API are (**_example_** 30 calls per minute and 1000 calls per hour.)
> 
> 
> 
> Document update via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10097
> 
> 
> 
> Thanks
> 
> Sri

**Comment by msbemba** [comment]
@yowsa That is correct. it is not an example. It is the actual limitation. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10097 to reflect the same.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @yowsa Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
