### ISSUE TITLE
MDE: Limited periodic scanning

### ISSUE THREAD

**Issue by theonlybrand** [MicrosoftDocs/microsoft-365-docs#10076]
Currently the docs state that Defender Antivirus is able to do limited-periodic scanning (LPS) when disabled or uninstalled, but states it is not available when in passive mode. I think it should be the other way around, I double checked with a few of my test machines by the following:
1. Confirm 3rd party AV is installed on machine
2. Get-MpComputerStatus in elevated PowerShell states AMRunningMode: "SxS Passive Mode" 
3. Defender is able to do LPS in the UI.

Also if you set the "DisableAntiSpyware" to 1 in HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender
the enabled LPS option switches back to "Off".

**Comment by yogkumgit** [comment]
@theonlybrand Please indicate which document you are referring to. Thanks

**Comment by theonlybrand** [comment]
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide#how-microsoft-defender-antivirus-affects-defender-for-endpoint-functionality

**Comment by msbemba** [comment]
@theonlybrand Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10098

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @theonlybrand Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
