### ISSUE TITLE
Missing descriptions of Microsoft 365 Groups activities

### ISSUE THREAD

**Issue by schumatt-msft** [MicrosoftDocs/microsoft-365-docs#10070]
There are some newer activities logged for Microsoft 365 Groups that aren't described in this article:

![Screenshot from audit log search of Microsoft 365 Groups activities: IB assistant removed group member, Identified as IB non-compliant group, Notified ownerless group, Responded to ownerless group notification, Unattended ownerless group](https://user-images.githubusercontent.com/52325421/198034102-ae8cf6a9-e534-416b-ae28-635f13c07b31.png)

Could these be added?  Opening this issue based on discussion in #10013 for same topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@schumatt-msft - thanks for the feedback. As an internal MS contact, I'll send you an internal email with the link to the content request form so you can submit this request there. Submitting internally is easier for me and the PG team to review, confirm, and approve.
