### ISSUE TITLE
maximum page size 200000 now?  how do i use this?  is it live?

### ISSUE THREAD

**Issue by maxst33l** [MicrosoftDocs/microsoft-365-docs#10072]
It now states for option #1:
maximum page size is 200,000
whereas a few weeks ago this was 10,000
which is awesome!

However, it appears that it's still capped at 10,000 and we still need to use odata next to get more than 10,000.

If the max page size is now 200,000 how to I set this??  
For rest ingestion into other tools, pagination really complicates things and I'd like to be able to grab all in one swoop.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 881f771d-1eb6-96ac-5652-53ba7183d9e0
* Version Independent ID: 881f771d-1eb6-96ac-5652-53ba7183d9e0
* Content: [Microsoft Defender Antivirus Device Health export device antivirus health reporting](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api?view=o365-worldwide#1-export-health-reporting-json-response)
* Content Source: [microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by maxst33l** [comment]
interesting, even though my old script that has a while loop for odata next  loops 3 times to get all 23,000k records, it appears it's no longer necessary.  I removed the loop and it looks like the base url:
"https://api.securitycenter.microsoft.com/api/deviceavinfo"
can grab all 23000 in one now without any parameters needed.

is this correct?

**Comment by msbemba** [comment]
@maxst33l Thank you for your feedback. The base URl can grab up to 200,000 in one go without any extra parameters.

Hope this helps!

Thanks
Sri

**Comment by maxst33l** [comment]
Yes, that is a most welcomed update.  I will adjust my script to no longer call odata next.  Thank you for the verification.
