### ISSUE TITLE
Confusing part about 'Sydney, NSW'

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1007]
This paragraph is confusing as a customer because it's unclear if this is meant seriously or if the reason for this is known but not part of this guide as it would be irrelevant:

> Interestingly, if “Sydney, NSW” has a comma, the DLP policy is not triggered. I have no idea why a comma makes any difference here, nor why other cities and states in Australia aren't included in the keywords for the Australian driver's license information type, but there you go. So, what can we do about it? There's a couple of options.

If the reason is unknown, this should be investigated with the product team. Same with why no other cities and states are included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36344d-67bf-68cb-5004-9ac6f27ebf51
* Version Independent ID: 89a7d7e7-c643-eb06-d844-b97b80633b68
* Content: [Create, test, and tune a DLP policy - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy#feedback)
* Content Source: [microsoft-365/compliance/create-test-tune-dlp-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@GiantCrocodile  - Thank you for your comment. I have removed this text from this topic.

**Comment by GiantCrocodile** [comment]
So has this issue been fixed @chrfox or is it still live in the product?
