### ISSUE TITLE
Incorrect statement regarding who can reset Global Admin passwords

### ISSUE THREAD

**Issue by andyrobbins** [MicrosoftDocs/microsoft-365-docs#10088]
Hello there,

In this [markdown file](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md) and subsequently [rendered page](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide), this statement is made:

> Because only another global admin can reset a global admin's password, we recommend that you have at least 2 global admins in your organization in case of account lockout.

However, according to our tests and to [this table](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#who-can-reset-passwords), Global Admin principals are not the only principals that can reset the password for other Global Admin principals. Any principal with the Privileged Authentication Admin role can also reset the password of a Global Admin principal.

Given the context of the "About admin roles in the Microsoft 365 admin center" page, I would recommend re-writing the full statement from this:

> Because only another global admin can reset a global admin's password, we recommend that you have at least 2 global admins in your organization in case of account lockout. But the global admin has almost unlimited access to your org's settings and most of the data, so we also recommend that you don't have more than 4 global admins because that's a security threat.

To this:

> Global Admins have almost unlimited access to your organization's settings and most of its data. We recommend you limit the number of Global Admins as much as possible. A Global Admin may inadvertently lock their account and require a password reset. Either another Global Admin or a Privileged Authentication Admin can reset a Global Admin's password. Therefore, we recommend you have at least either one more Global Admin or a Privileged Authentication Admin in the event a Global Admin locks their account.

Andy

**Comment by msbemba** [comment]
@andyrobbins Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10100

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andyrobbins Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
