### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by andysgit007** [MicrosoftDocs/microsoft-365-docs#10086]
[Course MS-500T02-A: Implementing Microsoft 365 Threat Protection](https://learn.microsoft.com/en-us/training/certifications/courses/ms-500t02).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16e75870-345e-f35b-87e2-e5e4f2707391
* Version Independent ID: 16e75870-345e-f35b-87e2-e5e4f2707391
* Content: [Microsoft 365 Defender portal](https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-365-defender-portal.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-defender-portal.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@andysgit007 Thank you for your feedback. The old Course page is no longer available, we have updated the document with another course via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10099

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andysgit007 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
