### ISSUE TITLE
label deletes items but not folders, post retention period ends

### ISSUE THREAD

**Issue by sometimes56** [MicrosoftDocs/microsoft-365-docs#10080]
[Enter feedback here]

Item deletion is supported with keepAndDelete or Delete label but not folder deletion. This info to the public docs will help in reducing such escalations where Cx will understand that folders will not be deleted, and they need to untag the folder if the label is applied then try to delete during their cleanup exercise.

~ Omkar N S.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b58a7e8c-acc0-df60-1563-8ac667096826
* Version Independent ID: 770a3929-18b7-3655-be8d-5c3eb7462df2
* Content: [Flowchart to determine when an item is retained or deleted - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-flowchart?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-flowchart.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-flowchart.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@sometimes56  Yes, we have this clearly documented that Microsoft 365 retention supports items and not organizing structures, but this page isn't the place for this information that focuses on the principles of retention to explain conflict resolution for policies and labels. 

For example, for SharePoint, in "Learn about retention for SharePoint and OneDrive" (https://learn.microsoft.com/microsoft-365/compliance/retention-policies-sharepoint) we list exactly what items are impacted by retention and deletion actions, and "Retention settings from both retention policies and retention labels do not apply to organizing structures that include libraries, lists, and folders."
