### ISSUE TITLE
eDiscovery search of sharepoint site subfolder returns entire site

### ISSUE THREAD

**Issue by bluestarcs** [MicrosoftDocs/microsoft-365-docs#10094]
Hi,
I am trying to place a hold/search only a sub-folder of a SharePoint site in the eDiscovery center. I have successfully done this in multiple tenants however, in a certain tenant, when I specify the subfolder in "Locations" I am able to add the subfolder however once the search has completed, it has searched the entire site and not just the subfolder. For example, my site url is: https://myorg.sharepoint.com/sites/Mysitename which let's say has 14TBs of data, I search for the folder I would like to place on hold, i.e.: https://myorg.sharepoint.com/sites/Mysitename/Documents/FolderOne/Subfolder1/* , which has only 63GBs of data. I type the url into the location search in an eDiscovery search and hit enter. My subfolder appears, I check the checkbox and click add. It says I have 1 site included in my search and I click done. When the search has completed, I check the search summary and under status, it shows the entire site contents (14TBs) instead of just the subfolder's contents (63TBs).  This is an urgent issue and any help would be greatly appreciated!

**Comment by denisebmsft** [comment]
Hello @bluestarcs and thank you for posting your question here. We need a little bit more information. To which article(s) does this apply? This information will help us route the issue to the correct writer/team.

**Comment by yogkumgit** [comment]
@bluestarcs We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
