### ISSUE TITLE
Tag availability compared between doc article and portal not the same

### ISSUE THREAD

**Issue by kathodion** [MicrosoftDocs/microsoft-365-docs#10090]
[Enter feedback here]
_If there is no security update available, the CVE will have the tag '**No updates available**'. There will be no option to go to the related security recommendation as software that doesn't have a security update available is excluded from the Security recommendations page._

I refer to the part above in the documentation and the tag in bold. This tag is not available in the portal, see picture 1.
![image](https://user-images.githubusercontent.com/10939437/198526613-19c9a0c3-3bae-43c2-bfad-ea5a7620b655.png)

Can you clarify if the doc article is incorrect or if the tag should be present in the portal please.

best regards
Pascal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1f0aa86-a1bc-be77-2d19-2538b674755b
* Version Independent ID: b1f0aa86-a1bc-be77-2d19-2538b674755b
* Content: [Vulnerabilities in my organization](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/tvm-weaknesses?view=o365-worldwide#gain-vulnerability-insights)
* Content Source: [microsoft-365/security/defender-vulnerability-management/tvm-weaknesses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/tvm-weaknesses.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
Hi @kathodion, 

Looks like that article is incorrect! I will update this now and the changes will be reflected later today! 

Thanks for sending this through.

Sinead

**Comment by msbemba** [comment]
@kathodion Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10106

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kathodion Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
