### ISSUE TITLE
Azure AzCopy - version?

### ISSUE THREAD

**Issue by andrewbettany** [MicrosoftDocs/microsoft-365-docs#1009]
The version of Azure AzCopy in this article which is downloaded from within the Security & Compliance Center is a 32bit version that is part of the Microsoft SDK, which is not fully supported.
Should we be able to use the latest released version of Azure AzCopy?
The commands shown in this article are incompatible with the the Azure AzCopy v10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?source=docs)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@andrewbettany The short answer is no. Only the version of  AzCopy that can be loaded in the network upload wizard supports the command syntax in this topic. That's version v8.1. AzCopy v10 isn't supported. Please see similar GitHub issue: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1015
