### ISSUE TITLE
Update information related eDiscovery decryption for files protected on-premises

### ISSUE THREAD

**Issue by sergioandreslq** [MicrosoftDocs/microsoft-365-docs#10095]
Hello team, 

Please help us updating the article associated to the paragraf:
"Important

Decryption isn't supported for files that are locally encrypted and then uploaded to SharePoint or OneDrive. For example, local files that are encrypted by the Azure Information Protection (AIP) client and then uploaded to Microsoft 365 aren't supported. Only files that are encrypted in the SharePoint or OneDrive service are supported for decryption."

This note is not correct as eDiscovery can unencrypt data that was protected on-premise after the AIP UL client was released.

I did the test and eDiscovery can decrypt data that was protected on-premise and execute the eDiscovery. I was able to see the content of the protected file.

Please help us to update the article as this NOTE is generated a lot of confusion for FEs and SMEs which are warning the customer if data is protected on-premises the eDiscovery can't decrypt it for investigation.

Video of the lab
https://microsoft-my.sharepoint.com/:v:/p/v-slondono/EU65lDeNMLtFmnV1oxrUTVUBPOpz2jcTN2Kk9mvU5EIvAQ?e=BVM6da

![image](https://user-images.githubusercontent.com/75001072/198734251-958529eb-01bd-49d2-90cd-3ef3c7bfc5af.png)
![image](https://user-images.githubusercontent.com/75001072/198734277-d537e456-db41-40a7-93d2-d8ffab0c8259.png)
![image](https://user-images.githubusercontent.com/75001072/198734292-3bbdd3b9-23a0-4939-b71f-25d5a095bd38.png)
![image](https://user-images.githubusercontent.com/75001072/198734310-fd786625-62db-4a39-a708-bc55b5aab885.png)
![image](https://user-images.githubusercontent.com/75001072/198734324-eb8b22c6-e496-4814-b1cb-655cd2888c34.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e38718be-6244-3988-7851-7c8c5625dd9f
* Version Independent ID: 4581a9e4-b838-c1a9-93a8-d52630128195
* Content: [Decryption in Microsoft Purview eDiscovery tools - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-decryption?view=o365-worldwide#decryption-limitations-with-sensitivity-labels-in-sharepoint-and-onedrive)
* Content Source: [microsoft-365/compliance/ediscovery-decryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-decryption.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@sergioandreslq Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10133

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@sergioandreslq Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
