### ISSUE TITLE
Confusing version references

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/microsoft-365-docs#1010]
Why "Creators Update" in six places? That was three years ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d66a7a3-2230-d907-5ff3-b3f7ed8c166a
* Version Independent ID: e437b87d-0845-bb6f-3b0b-8d9fd2b3013a
* Content: [Upgrade Windows devices to Windows Pro Creators Update - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/upgrade-to-windows-pro-creators-update)
* Content Source: [microsoft-365/business/upgrade-to-windows-pro-creators-update.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/upgrade-to-windows-pro-creators-update.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
I updated the topic - hopefully more consistent now.

**Comment by BR77BE** [comment]
It still says "Creators Update" in three places (including index).
