### ISSUE TITLE
Export device list through files

### ISSUE THREAD

**Issue by skowronp1** [MicrosoftDocs/microsoft-365-docs#10101]
Hi I do remember it was available some time ago and described. Is it still supported way of getting the list of devices in case the org possess 100k+ devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07828149-8c9b-2b6f-b5f6-9558cfcfa650
* Version Independent ID: 2101b098-7da1-86ca-6a31-fddfa7a5cb62
* Content: [List machines API](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-machines.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @skowronp1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
