### ISSUE TITLE
All Credentials DLP Policy triggers on Zoom Calendar Invites

### ISSUE THREAD

**Issue by adrwh** [MicrosoftDocs/microsoft-365-docs#10116]
Hi, after turning creating a DLP policy using the "All Credentials" template, it triggers with every meeting invite due to Zoom and Google sending meeting passwords in the invitation email.

How can i exclude sender addresses from the policy when the sending address is external?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28be949f-8589-8f7c-8e08-c029389a1f6e
* Version Independent ID: f5928319-0360-41fa-dda0-5473b4e1a5b2
* Content: [DLP policy conditions, exceptions, and actions - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-conditions-and-exceptions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-conditions-and-exceptions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-conditions-and-exceptions.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@adrwh Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
