### ISSUE TITLE
Incorrect Japanese translation

### ISSUE THREAD

**Issue by VigneshMitsume** [MicrosoftDocs/microsoft-365-docs#10119]
This page and the child pages for eDiscovery has lot of incorrect/inconsistent Japanese translation for custodian management.
Japanese customers cannot understand correctly about the product. Especially "non-custodial" is translated into 6 patterns as far as I found. Each of those translated word has totally different meaning For ex. custodian: "カストディアン" "保管担当者" 
custodial: "保管" 
non-custodial: "非 親権" "非カストディアル" "非カストディアン" "非保管" "非親権" "非管理"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 562b6b1d-b0fd-0d65-9db8-37df67bd7035
* Version Independent ID: 92c4403b-0d6b-88aa-74f4-ba3b7640ad00
* Content: [Microsoft Purview eDiscovery solutions - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@tiburd Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [240347](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/240347)

I'm closing this issue because the Global Services team will handle it from here.

cc: @yogkumgit
