### ISSUE TITLE
In the image [govern-your-data] the word management is misspelled as "managment"

### ISSUE THREAD

**Issue by koffnox** [MicrosoftDocs/microsoft-365-docs#10112]
[Enter feedback here]

In the image [govern-your-data] the word management is misspelled as "managment"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c187df5e-7b20-def8-6649-dd218c1a960f
* Version Independent ID: c187df5e-7b20-def8-6649-dd218c1a960f
* Content: [Microsoft Purview Data Lifecycle Management & Microsoft Purview Records Management - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/manage-data-governance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/manage-data-governance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/manage-data-governance.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@koffnox  Thanks for flagging his typo - not sure how we all missed it, before!  I'll put it on the list of things to fix.
