### ISSUE TITLE
Default page size for user related devices

### ISSUE THREAD

**Issue by yowsa** [MicrosoftDocs/microsoft-365-docs#10123]
What are the default page size for this endpoint? And what is the max page size we can request for?

Thank you 🙏🏻

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9849a2ea-ad01-d8ab-f03a-6f8b256c22bb
* Version Independent ID: 9849a2ea-ad01-d8ab-f03a-6f8b256c22bb
* Content: [Microsoft Defender Antivirus export device antivirus health details API methods and properties](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-health-api-methods-properties?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-health-api-methods-properties.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-health-api-methods-properties.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@yowsa Thank you for your feedback. The maximum page size is  200,000. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10139

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @yowsa Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
