### ISSUE TITLE
Antivirus export via files

### ISSUE THREAD

**Issue by yowsa** [MicrosoftDocs/microsoft-365-docs#10122]
Is there any information on when "1.3 Export device antivirus health details API properties (via files)" will be officially released? 

Also curious is there is a way to get the associated user when requesting device health?

Thank you!! 🙏🏻

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9849a2ea-ad01-d8ab-f03a-6f8b256c22bb
* Version Independent ID: 9849a2ea-ad01-d8ab-f03a-6f8b256c22bb
* Content: [Microsoft Defender Antivirus export device antivirus health details API methods and properties](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-health-api-methods-properties?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-health-api-methods-properties.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-health-api-methods-properties.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@yowsa Thank you for your feedback. The release date is not available yet. However, you can enter this feedback on our main feedback portal ( https://feedbackportal.microsoft.com/ ) so that a dev/product engineer can provide more information on when this will be live.

Hope this helps!

Thanks
Sri
