### ISSUE TITLE
Are rate limits application level or application+tenant?

### ISSUE THREAD

**Issue by yowsa** [MicrosoftDocs/microsoft-365-docs#10124]
Are the rate limits for the Defender Endpoint APIs per combination of **application+tenant_id** or per **application** only? Haven't been able to find details on this in the docs. 

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 881f771d-1eb6-96ac-5652-53ba7183d9e0
* Version Independent ID: 881f771d-1eb6-96ac-5652-53ba7183d9e0
* Content: [Microsoft Defender Antivirus Device Health export device antivirus health reporting](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-health-export-antivirus-health-report-api.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@yowsa Thank you for your feedback. The rate limitations are always on the combination of application+tenant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @yowsa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
