### ISSUE TITLE
URI Not Working

### ISSUE THREAD

**Issue by lovetherager** [MicrosoftDocs/microsoft-365-docs#10129]
The URI "https://webhook.ingestion.office.com/api/signals" that is used in the powershell script and the powerautomate does not work. When attempting to access. A 401 or a 403 error is served. Can you please update the document with a functioning URI?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6b68cfa-058a-8536-fb6a-b54e8fffa626
* Version Independent ID: dbcba365-2858-8cff-4f30-8a8a0068ac71
* Content: [Set up a connector to import HR data - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/import-hr-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/import-hr-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-hr-data.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@lovetherager Thank you for your feedback. I'll check with the author and update the latest URL shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@lovetherager Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
