### ISSUE TITLE
Observation in data doesn't match the retention period END date time for Delete policy.

### ISSUE THREAD

**Issue by VincentXu2021** [MicrosoftDocs/microsoft-365-docs#10142]
In this example, it says "typically 1-7 days after the start of the retention period on day 2"
https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide#example-3-delete-only-after-1-day
from above document, my understanding in "1-day delete policy" is like this:
Message sent: 2022-11-01T02:30:00 (UTC)
Retention period start: 2022-11-02T00:00:00(UTC)
Retention period end: 2022-11-03T00:00:00(UTC) 

However, my observation in data doesn't match above understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide#example-3-delete-only-after-1-day)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@VincentXu2021 I don't see how this is actionable for the documentation as a GitHub Issue, but I can share that the explanation and example went through careful review and signoff by the engineering team that owns the code. If your observations don't match the documentation, you can open a support ticket for investigation.  They can contact us if they think any changes are needed.
