### ISSUE TITLE
Required version of Office needs correcting

### ISSUE THREAD

**Issue by maccaoz** [MicrosoftDocs/microsoft-365-docs#10149]
Docs currently state:

"A supported version of Microsoft Office is installed"

This is leading customers to erroneously believe Perpetual Office is supported.   Consider changing to "A supported version of Microsoft 365 Apps is installed", or perhaps adding a note to indicate that Perpetual is not supported.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a89deeb-d0ed-47a1-b79c-01aa2cbfcadf
* Version Independent ID: 5a89deeb-d0ed-47a1-b79c-01aa2cbfcadf
* Content: [Onboard Windows 10 or Windows 11 devices into Microsoft 365 overview - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/device-onboarding-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/device-onboarding-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@maccaoz Thank you for your feedback. WE have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10168

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @maccaoz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
