### ISSUE TITLE
Not Updated for New Commerce Experience

### ISSUE THREAD

**Issue by WhiskeyTFox** [MicrosoftDocs/microsoft-365-docs#10140]
[Enter feedback here]
This page and the instructions do not seem to apply to the "new commerce experience". The options to manage "add-ons" in a parent subscription is no longer available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add more SharePoint storage to your subscription](https://learn.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by 22f-cy** [comment]
> 
> [Enter feedback here]
> This page and the instructions do not seem to apply to the "new commerce experience". The options to manage "add-ons" in a parent subscription is no longer available. 
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
> * Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
> * Content: [Add more SharePoint storage to your subscription](https://learn.microsoft.com/en-us/microsoft-365/commerce/add-stor~~e?view=o365-worldwide)
> * Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
> * Service: **microsoft-365-business**
> * GitHub Login: @cmcatee-MSFT
> * Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@WhiskeyTFox Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10185

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@WhiskeyTFox Closing as per author's Input. Thanks
