### ISSUE TITLE
Indicator Import requires PascalCase for Category strings.

### ISSUE THREAD

**Issue by vxSpctr** [MicrosoftDocs/microsoft-365-docs#10146]
Attempting to import Indicators with specific categories requires the string to be written on Pascal Case convention and only accepts the category list available at the portal:

![image](https://user-images.githubusercontent.com/92767117/199828282-5b0e500c-a86f-4336-a9fe-cf60c32af5ac.png)

If you try "Suspicious Activity" with or without quotes will pop up an error while importing, however, "SuspiciousActivity" with no quotes at the Category column will succeed. If the second word does not have the uppercase in the first character, will fail as well.

The documentation has no reference to this, and the note at the end just confirms the categories are aligned with the MITRE conventions which does not specify the Pascal Case usage for the import. Document: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-manage?view=o365-worldwide

**Comment by msbemba** [comment]
@vxSpctr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10183

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @vxSpctr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
