### ISSUE TITLE
Order of operations for block/allow

### ISSUE THREAD

**Issue by obsoletenewyork** [MicrosoftDocs/microsoft-365-docs#10143]
Can you add documentation here that specifies the order of operations for the block/allow actions? 

Example: 
An admin creates a manual block entry for a URL. Later on, that same URL is submitted via the submissions portal to create an allow entry. Does the block always take precedence?

**Comment by yogkumgit** [comment]
@obsoletenewyork Can you please tell us to which article(s) your question applies? This will help us route this issue to the correct writer/team.

**Comment by obsoletenewyork** [comment]
@yogkumgit 

Article is here - thank you:
https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-tenant-allow-block-list?view=o365-worldwide

**Comment by chrisda** [comment]
@obsoletenewyork, I added the following note:

> [!NOTE]
> In the Tenant Allow/Block List, block entries take precedence over allow entries.

OK?

**Comment by yogkumgit** [comment]
@obsoletenewyork Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
