### ISSUE TITLE
typo: fourthcoffeecorp.onmicrsoft.com

### ISSUE THREAD

**Issue by paulaustin-automutatio** [MicrosoftDocs/microsoft-365-docs#10158]
[Enter feedback here]
typo in the following domain

fourthcoffeecorp.onmicrsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains Frequently Asked Questions](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.yml)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@paulaustin-automutatio Thank you for your feedback. The changes have been made by @DMoenks via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10159

Once the author approves, the changes will be live.

Thanks
Sri
