### ISSUE TITLE
Debugging mdatp_managed.json

### ISSUE THREAD

**Issue by ChrisRitson** [MicrosoftDocs/microsoft-365-docs#10151]
I've just spent too long debugging a rookie error in /etc/opt/microsoft/mdatp/managed/mdatp_managed.json.

My error was specifying a path for an excludedFileName when I should have specified a name. Two things would have made this a lot easier. Either:

- A tool to output the current state or exclusions which had been entered on the command line as a .json file for use elsewhere; or
- An error or warning that a required value had been omitted and an unwanted one ignored in a log or validation command.

I realise this is a product change request, but I wonder just how many collective hours have been wasted on a trivial error like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6bcf39-9a8c-7fa3-803a-508e7b74cc9b
* Version Independent ID: 9fd6d652-df16-7f4b-d253-6aee2362f836
* Content: [Configure and validate exclusions for Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-exclusions?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-exclusions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-exclusions.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ChrisRitson Thank you for your feedback. You are right, this is product feedback and should be routed to the dev/product group. I'd recommend you post this directly on our main feedback protal - https://feedbackportal.microsoft.com/  so that a dev/product engineer can review and respond.

Hope this helps!

Thanks
Sri
