### ISSUE TITLE
Edits and date/time issues

### ISSUE THREAD

**Issue by njpl3** [MicrosoftDocs/microsoft-365-docs#10152]
I was just figuring out how to configure this and I found this page. Thank you for the detailed information. I have just a couple of edits and questions/clarifications...

**Under "schedule a quick scan", change**
2. Save the file as com.microsoft.wdav.schedquickscan.plist.
to
2. Save the file as com.microsoft.wdav.schedquickscan.plist to the /Library/LaunchDaemons directory

**Under "schedule a full scan", change**
2. Save the file as com.microsoft.wdav.schedfullscan.plist.
to
2. Save the file as com.microsoft.wdav.schedfullscan.plist to the /Library/LaunchDaemons directory

**Under "Load your file", change**
p-list to plist

**Under commands, consider adding**
chown root:wheel /Library/LaunchDaemons/com.microsoft.wdav.sched*
chmod 644 /Library/LaunchDaemons/com.microsoft.wdav.sched*
xattr -c /Library/LaunchDaemons/com.microsoft.wdav.sched*

**Under commands, change**
launchctl load /Library/LaunchDaemons/<your file name.plist>
launchctl start <your file name>
to
launchctl load -w /Library/LaunchDaemons/<your file name.plist>

Note: Without the -w, the loaded LaunchDaemon will only run until the next restart, the w stands for "persistent" (I have no idea who came up with that one!). The start subcommand is traditionally only used for testing (i.e. start/stop)

Question about the Day/Weekday portion of the plist
        <key>Day</key>
        <integer>3</integer>
        <key>Hour</key>
        <integer>2</integer>
        <key>Minute</key>
        <integer>50</integer>
        <key>Weekday</key>
        <integer>5</integer>

Does that mean that the scheduled scan will run on the third day of the month as well as every Friday @ 02:50? Looking at it from a cron perspective, day and weekday are usually competing schedule items and are generally not used in conjunction with each other when calling a process (unless you explicitly meant to call out separate day and weekday in the schedule listed above).

Needed clarifications
"The Weekday value of StartCalendarInterval uses an integer to indicate the fifth day of the week, or Friday. The range is between 0 and 7 with 7 representing Sunday"
##Something is off with that math. 0-7 is eight days unless 0 and 7 both represent Sunday

"The Hour value of StartCalendarInterval uses an integer to indicate the second hour of the day. The range is between 0 and 24."
##While, 00:00-59 and 24:00-59 are the same thing, it is more common to not use 24:00 (i.e. 00:00 to 23:59). Does Defender Endpoint evaluate both 00:00-59 and 24:00-59 nomenclatures as the same?
"The Minute value of StartCalendarInterval uses an integer to indicate fifty minutes of the hour. The range is between 0 and 59."
##fifty should be sixty

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae1c59b1-e4aa-6a18-7c34-720d0eb83c5d
* Version Independent ID: f5a3fc3c-bec2-3d7a-1d61-e23a0c1f8d4f
* Content: [How to schedule scans with Microsoft Defender for Endpoint on macOS](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-schedule-scan?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-schedule-scan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-schedule-scan.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @njpl3 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
