### ISSUE TITLE
No more free trials?

### ISSUE THREAD

**Issue by joholmes123** [MicrosoftDocs/microsoft-365-docs#10153]
Making people enter credit card information and then needing to cancel in order to not be billed is really not cool. 

As a consultant, I frequently have people start a trial to get practice and introduced to the application and this is going to leave a bad taste in people's mouths.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9487dd6d-c534-ee70-0f59-00fcd20c0c93
* Version Independent ID: 69908dd8-ae60-0697-0b1c-0934f2ad2568
* Content: [Try or buy a Microsoft 365 for business subscription](https://learn.microsoft.com/en-us/microsoft-365/commerce/try-or-buy-microsoft-365?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/try-or-buy-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/try-or-buy-microsoft-365.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@joholmes123 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
