### ISSUE TITLE
Mas7894

### ISSUE THREAD

**Issue by Masonta1976** [MicrosoftDocs/microsoft-365-docs#10155]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Version Independent ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Content: [Microsoft 365 admin center - Overview - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide#who-has-admin-permissions-in-my-business)
* Content Source: [microsoft-365/admin/admin-overview/admin-center-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-center-overview.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@Masonta1976 Thank you for your feedback. I'm not sure if your entire feedback was entered. Could you please provide us with more information on the question or changes you need on this document?

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.
