### ISSUE TITLE
AzCopy v10 Arguments update

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/microsoft-365-docs#1015]
Verify if the arguments shown in step 2 are still valid. Example the /Y mentioned in the article may no longer be accurate in the latest AzCopy version. See https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-copy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files#step-4-create-the-pst-import-mapping-file)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@CHDAFNI-MSFT The AzCopy command syntax in this topic only supports the version of AzCopy that is downloaded when clicking the "Download Azure AzCopy" link in the network upload wizard. In this case, this is version 8.1. AzCopy v10 isn't supported for PST import.

There is a note about this in the topic, which may need to be updated from "not recommended" to "not supported by the command syntax in this topic."
