### ISSUE TITLE
API Limits are incorrect

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#10162]
[Enter feedback here]
I believe the limits are incorrect -- for the API, we should return 100k results, not 10k.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53a61a50-f7f2-f09a-a008-759c3afba97b
* Version Independent ID: 872c0e23-c626-3e22-efea-d4ef4ad7f32b
* Content: [Advanced Hunting API](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-api?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-advanced-query-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-advanced-query-api.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jrhi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10197

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jrhi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
