### ISSUE TITLE
Add domains up to 900 OR up to 5,000? 

### ISSUE THREAD

**Issue by coleefy** [MicrosoftDocs/microsoft-365-docs#10163]
[Enter feedback here]

What is the correct number of domains we can add on an M365 tenant?

ON THIS PAGE: It says

`Typically, you can add up to 900 domains to your Microsoft 365 subscription.`

BUT on other MS Learn pages, it says "up to 5,000":

- https://learn.microsoft.com/en-us/microsoft-365/admin/m365-feature-descriptions?view=o365-worldwide&tabs=Domains
- https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/exchange-online-protection-limits

Please confirm on the page. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains Frequently Asked Questions](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.yml)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@coleefy Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10198

Once the author approves, the changes will be live.

Thanks
Sri
