### ISSUE TITLE
Update to reflect Defender Vulnerability Management with Defender for Servers P2

### ISSUE THREAD

**Issue by jbrysonMSFT** [MicrosoftDocs/microsoft-365-docs#10165]
A linked Azure subscription with Defender for Servers Plan 2 will grant the full Defender for Vulnerability Management

![image](https://user-images.githubusercontent.com/54324805/200376981-c672d12c-bbbb-468f-8f0a-b71558a8f6cd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa2cb7af-a9ea-41cf-60ec-b33ff122b058
* Version Independent ID: fa2cb7af-a9ea-41cf-60ec-b33ff122b058
* Content: [Microsoft Defender Vulnerability Management public preview](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
Hi @jbrysonMSFT 

Just so I'm clear - are you requesting to update this page:
 https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management?view=o365-worldwide

with the information that if you sign up for Defender for Servers Plan 2 you'll get Microsoft Defender Vulnerability Management? 

If so, I might just send an email to give the product team visibility into this as I think there are ongoing discussions around the licensing and bundling of MDVM,

Thanks,
Sinead

**Comment by siosulli** [comment]
Hi @jbrysonMSFT  - can you confirm what needs to be done here so we close this ticket? 

Thanks,
Sinead

**Comment by jbrysonMSFT** [comment]
In this page we now state that Defender Vulnerability Managment (full add-on) is supported in Defender for Servers P2.  
https://learn.microsoft.com/en-us/azure/defender-for-cloud/plan-defender-for-servers-select-plan

This page should also reflect that you can get Defender Vulnerability management as an add-on to Defender for Endpoint P2, standalone, or as part of Defender for Servers P2. 
https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management?view=o365-worldwide

**Comment by siosulli** [comment]
@jbrysonMSFT - we have added a new table in the MDVM docs about its availability in DfS:

https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities?view=o365-worldwide#vulnerability-management-capabilities-for-servers

**Comment by siosulli** [comment]
Closing this issue and the documentation now covers MDVM support in DfS
