### ISSUE TITLE
Guest Web-Only Access

### ISSUE THREAD

**Issue by nickbrownapollo** [MicrosoftDocs/microsoft-365-docs#10161]
I think that the section "Set up web-only access for guests" is slightly misleading.

I believe that the intention of this rule is to effectively force guests to use a Web Browser by denying access using all other clients. The most logical approach would have been to use a "Block" grant control, but I understand this can cause unintended side effects, so this isn't the approach taken.

Instead, the defined rule appears to be blocking dependent on the compliance state of the device. This seems to be making the assumption that guest = non-compliant device. Whilst this is often likely to be the case, it's also possible that guests may authenticate from compliant devices, (particularly if inbound organisational trust settings have been configured to support compliant devices), so this rule would not be effective for those guests. I think this needs to be spelled out more clearly.
 
A more accurate description of what is configured with this rule is:
"Deny access to guests from non-compliant devices using non-browser client applications"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a more secure guest sharing environment](https://learn.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@nickbrownapollo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10196

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nickbrownapollo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
