### ISSUE TITLE
Typo on "Note"

### ISSUE THREAD

**Issue by catarinamarto** [MicrosoftDocs/microsoft-365-docs#10178]
[I would suggest to change this typo "If you have a billing profile, you **con** only change the billing frequency when you buy or upgrade a subscription. To find out if you have a billing" to "you **can**"]
Thanks
Catarina

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49d66f21-cff3-bb96-df38-6f67d95eb6cf
* Version Independent ID: 00256bad-f01c-02a6-9554-a0be1ce933ea
* Content: [Change your billing frequency](https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-payment-frequency?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-payment-frequency.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-payment-frequency.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@catarinamarto Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10203

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @catarinamarto Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
