### ISSUE TITLE
Output missing for Defender for Antivirus mode via sc query windefend

### ISSUE THREAD

**Issue by gh-andrem** [MicrosoftDocs/microsoft-365-docs#10179]
Looking at the documentation on how to check if MDAV is in passive mode I've noticed that it is not described what the expected output of [[Method | Command Prompt]](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-mde-phase-3?view=o365-worldwide#confirm-that-microsoft-defender-antivirus-is-in-passive-mode-on-your-endpoints) should look like.

I've ran the command on a device where MDAV is in active (normal) and passive mode and the only difference is that the **windefend** service is **STOPPABLE** (in passive mode) and **NOT_STOPPABLE** (in active mode).
If that is correct, could this information be included in the documentation?

**Device with MDAV in passive mode**

```
SERVICE_NAME: windefend
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

**Device with MDAV in active mode**
```
SERVICE_NAME: windefend
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (NOT_STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f43ff24-610d-5bd7-cc54-14a418b7d494
* Version Independent ID: 3a677b3a-712c-dd35-e31c-dfcc18808c43
* Content: [Switch to Microsoft Defender for Endpoint - Onboard](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-mde-phase-3?view=o365-worldwide#confirm-that-microsoft-defender-antivirus-is-in-passive-mode-on-your-endpoints)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-mde-phase-3.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@gh-andrem Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10204

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gh-andrem Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
