### ISSUE TITLE
Windows 10 lab download is corrupted

### ISSUE THREAD

**Issue by MrMozbe** [MicrosoftDocs/microsoft-365-docs#10175]
[Enter feedback here]

the Windows 10 lab download is corrupted
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @cdmm12
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@MrMozbe Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10200

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by msbemba** [comment]
@yogkumgit 
The Lab environment link is fixed.

The issue can be closed
