### ISSUE TITLE
'Link to 'Get access to and back up a former user's data' is incorrect.

### ISSUE THREAD

**Issue by ChrisAt2at** [MicrosoftDocs/microsoft-365-docs#10177]
Page https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/delete-a-user?view=o365-worldwide is referring to '[Get access to and back up a former user's data](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide).', but the link goes to https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-4?view=o365-worldwide.
It should be step 5: https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-5?view=o365-worldwide

**Comment by msbemba** [comment]
@ChrisAt2at Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10202

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChrisAt2at Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
