### ISSUE TITLE
TLS 1.1/1.0 expiration info is out-of-date

### ISSUE THREAD

**Issue by manderson97** [MicrosoftDocs/microsoft-365-docs#10188]
The page still states "We began disabling TLS 1.0 and 1.1 for Worldwide and GCC environments beginning on **October 15, 2020** and will continue with roll-out **over the next weeks and months**."

Is the rollout complete?  If so, we should make it clear that we've removed TLS 1.0 and 1.1...

If the rollout _isn't yet_ complete, we should provide an update on when we expect it to be done...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14a729bb-ad0e-27bf-b119-beb99f1df9f4
* Version Independent ID: bc005f28-aa37-f52d-c328-ff547c1eb7b3
* Content: [Technical reference details about encryption - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/technical-reference-details-about-encryption?view=o365-worldwide#support-for-tls-10-and-11-deprecation)
* Content Source: [microsoft-365/compliance/technical-reference-details-about-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/technical-reference-details-about-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@manderson97 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10207

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@manderson97 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
