### ISSUE TITLE
Syntex Setup Process Doesn't Ask for Environment

### ISSUE THREAD

**Issue by slgsperry** [MicrosoftDocs/microsoft-365-docs#10186]
I went through the setup process in my tenant today. It never asked me what environment to use, it set it to the Default environment.

The doc is incorrect, it should also include steps on how to change the environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Service: **microsoft-syntex**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@slgsperry Thank you for your feedback. If you have multiple environments configured, you can choose which one to configure.  This option will not appear if you only have one environment. 

Hope this helps!

Thanks
Sri

**Comment by slgsperry** [comment]
I have 20 environments. Option still did not appear.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@slgsperry I'm testing this currently and will update the steps shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@slgsperry Yes, I'll do that.

**Comment by msbemba** [comment]
@slgsperry Thank you for your feedback. This seems to be working in the test tenant. I'd recommend you open a ticket via the need help section on the admin center so that the support engineer can file a bug and escalate it to the concerned team. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @slgsperry Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
