### ISSUE TITLE
Defender for endpoint bandwidth

### ISSUE THREAD

**Issue by ShawnHag** [MicrosoftDocs/microsoft-365-docs#10193]
Hi,
On this page it says that the Defender for endpoint sensor can use a daily average bandwidth of 5 MB to communicate with the Defender for Endpoint cloud service.

Is there any chance of this bandwidth to significantly increase? (ex: when a device is compromised by a malware)
If there is, in what kind of situation and approximately how much will the bandwidth increase?

I would like to know about how much bandwidth should be expected when we use the full capapbilities of Defender for endpoint,
or when an attack has been seen on a device.

Thank you 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in this document and can be closed.

Thanks
Sri
