### ISSUE TITLE
Forming PS Script to find SITs stored in SPO Sites

### ISSUE THREAD

**Issue by hibbyskuss** [MicrosoftDocs/microsoft-365-docs#10195]
Hi team, I am currently working on a project in which I try to create a PS script that allows me to create a new compliance search (which I did), but in this search, I would like to include which Sensitive Information Type the search is supposed to look for. So, I have defined the location etc., but the operator that I struggle with including is basically the ones mentioned [here](https://learn.microsoft.com/en-us/microsoft-365/compliance/form-a-query-to-find-sensitive-data-stored-on-sites?view=o365-worldwide).

The following is my current script, nothing too complex and I removed the actual values to keep it simple, but is there a way to insert a property for the SITs or DLP Policy templates (including the SITs) that I am trying to filter out of the site I am searching? 

```
Import-Module ExchangeOnlineManagement
Set-Location XX
Connect-IPPSSession -UserPrincipalName 
New-ComplianceSearch -Name "XX" -SharepointLocation "SITEURL"
Set-ComplianceSearch -Identity "XX" 
```

If more clarification is needed, please let me know. Thanks so much in advance, any help or tip is appreciated! 👻

**Comment by msbemba** [comment]
@hibbyskuss Thank you for your feedback. Since this is a technical query and needs assistance with PowerShell scripting, I'd recommend you contact Microsoft support via the need help section on the admin center so that the support engineer can assist you with the above query.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hibbyskuss Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by hibbyskuss** [comment]
Hi @msbemba & @yogkumgit, thanks for your kind responses, I appreciate it. I will let you know if there's anything that might need an update as soon as I have resolved the issue from my end! :) 

Thanks and all best,
Nadya
