### ISSUE TITLE
October 2022 - DLP Links

### ISSUE THREAD

**Issue by iftikhariqbal** [MicrosoftDocs/microsoft-365-docs#10192]
The links mentioned under the October 2022 update of Data Loss Prevention are not working 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89486ebd-f4fa-9d07-ee93-d04fd8d41027
* Version Independent ID: 667019d9-aac6-f466-1605-651a800fc212
* Content: [What's new in Microsoft Purview risk and compliance solutions - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@iftikhariqbal Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10209

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @iftikhariqbal Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
