### ISSUE TITLE
Update on TLS 1.0/1.1 retirement?

### ISSUE THREAD

**Issue by manderson97** [MicrosoftDocs/microsoft-365-docs#10190]
The "latest" update states: "We have already disabled TLS 1.0 and 1.1 for most Microsoft 365 services in the world wide environment. **Rollout will continue over the following weeks and months.**"

But there is no context for "when this started" or _more importantly_, when it is expected to be completed...

A different page https://learn.microsoft.com/en-us/microsoft-365/compliance/technical-reference-details-about-encryption?view=o365-worldwide#support-for-tls-10-and-11-deprecation states  "We began disabling TLS 1.0 and 1.1 for Worldwide and GCC environments **beginning on October 15, 2020** and will **continue with roll-out over the next weeks and months**."

But it's been 25 months now... 

It would be useful for this information to be current, and if this _isn't complete yet_, be clear about when its expected to be complete for the remaining environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec089a7-8f7b-d4d9-a763-e8abd73fb2c9
* Version Independent ID: 41ba8999-f0ea-5847-afad-8620dd83492a
* Content: [Disabling TLS 1.0 and 1.1 for Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @WorkShay
* Microsoft Alias: **fasqiu**

**Comment by msbemba** [comment]
@manderson97 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10208

Once the author approves, the changes will be live.

Thanks
Sri
