### ISSUE TITLE
Special Characters Excluded

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/microsoft-365-docs#1020]
The list of special characters appears to be incomplete. For example, square and curly braces are ignored in the search as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions#feedback)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@terrogin Thanks for the heads up. We'll look into this and update doc accordingly.

**Comment by markjjo** [comment]
@terrogin FYI that we added square and curly brackets to list of special characters that are ignored in search query. We also added open/closed parenthesis. We also move this content to a dedicated section for improved discoverability. Thanks again for calling this out.

https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions#special-characters
