### ISSUE TITLE
Update See Also section

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#10211]
Under "See Also" section, please link to another article in this series, on how to detect and remediate illicit consent grants. Thanks.

https://learn.microsoft.com/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 073882cd-36d0-b95a-77b2-aadd06fa34a5
* Version Independent ID: 463f2f77-3fb0-8078-5b49-878747f2842b
* Content: [Responding to a Compromised Email Account - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. Done.

Thanks for the feedback.

Closing
