### ISSUE TITLE
This page needs to be updated for GCC Functionality.

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/microsoft-365-docs#10212]
GCC cusotmers are not allowed to submit via the process described in this page.  if they do they get the following pop up.  for appropriate content PG should provide context for GCC and for that matter DOJ tenants where it relates to sumissions.

![GovSubmissionError](https://user-images.githubusercontent.com/47158090/200909478-02a74b45-87ea-4830-a26a-c5a391352f44.png)

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a21caf6-05ad-6226-59ea-5e4151d784b8
* Version Independent ID: 9cb6935a-184f-b18a-184c-7d4faf6256b6
* Content: [Report spam, non-spam, phishing, suspicious emails and files to Microsoft - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
@sinnamingrrl, does that error appear when _admins_ or _end-users_ attempt to submit messages to Microsoft for analysis? And using which method on that page (there are 5 rows in that table...).

**Comment by sinnamingrrl** [comment]
Looks good Chris!

**Comment by chrisda** [comment]
OK.

Thanks for the feedback.

Closing
