### ISSUE TITLE
> I exported a vcard from contacts.google.com (see picture).

### ISSUE THREAD

**Issue by Chadwell89** [MicrosoftDocs/microsoft-365-docs#10217]
> I exported a vcard from contacts.google.com (see picture).
> 
> ![all](https://user-images.githubusercontent.com/701648/45147118-85206800-b1c4-11e8-92b3-502af302b51d.png)
> 
> ![tel label other](https://user-images.githubusercontent.com/701648/45147202-b1d47f80-b1c4-11e8-92a0-6c185659b906.png)
> 
> 
> ![tel label work](https://user-images.githubusercontent.com/701648/45147183-a84b1780-b1c4-11e8-8844-198e479b6167.png)
> 
> 
> ![tel no label](https://user-images.githubusercontent.com/701648/45147167-9c5f5580-b1c4-11e8-9aef-8d4273422fe5.png)
> 
> ![all 3](https://user-images.githubusercontent.com/701648/45147148-923d5700-b1c4-11e8-95a0-f19afd0d23d5.png)
> 
> In the vcard, I created 4 types of contacts:
> 1. a contact with phone and label WORK
> 1. a contact with phone and no label
> 1. a contact with phone and label OTHER
> 1. a contact with all above
> 
> The vcard source is (I added a blank line to make it easier to read):
> ```
> BEGIN:VCARD
> VERSION:3.0
> FN:Tel Label Other
> N:Label Other;Tel;;;
> TEL:1019181716
> item1.ADR:;;;;;;
> item1.X-ABLabel:
> END:VCARD
> 
> BEGIN:VCARD
> VERSION:3.0
> FN:Tel Label Work
> N:Label Work;Tel;;;
> TEL;TYPE=WORK:0987654321
> item1.ADR:;;;;;;
> item1.X-ABLabel:
> END:VCARD
> 
> BEGIN:VCARD
> VERSION:3.0
> FN:Tel No Label
> N:No Label;Tel;;;
> item1.TEL:0123456789
> item1.X-ABLabel:
> item2.ADR:;;;;;;
> item2.X-ABLabel:
> END:VCARD
> 
> BEGIN:VCARD
> VERSION:3.0
> FN:Tels One Label One Other One Not
> N:One Label One Other One Not;Tels;;;
> item1.TEL:0102030405
> item1.X-ABLabel:
> TEL;TYPE=WORK:0908070605
> TEL:19181717
> item2.ADR:;;;;;;
> item2.X-ABLabel:
> END:VCARD
> ```
> 
> The result json does not contain the phone number for the label OTHER:
> 
> ```json
> [
>   {
>     "datapoints": [{ "name": "adr", "value": ["", "", "", "", "", "", ""] }],
>     "fn": "Tel Label Other",
>     "n": "Label Other;Tel;;;"
>   },
>   {
>     "datapoints": [
>       { "name": "adr", "type": "work", "value": ["", "", "", "", "", "", ""] }
>     ],
>     "fn": "Tel Label Work",
>     "n": "Label Work;Tel;;;"
>   },
>   {
>     "datapoints": [
>       { "name": "tel", "value": "0123456789" },
>       { "name": "adr", "value": ["", "", "", "", "", "", ""] }
>     ],
>     "fn": "Tel No Label",
>     "n": "No Label;Tel;;;"
>   },
>   {
>     "datapoints": [
>       { "name": "tel", "value": "0102030405" },
>       { "name": "tel", "type": "work", "value": "0908070605" },
>       { "name": "adr", "value": ["", "", "", "", "", "", ""] }
>     ],
>     "fn": "Tels One Label One Other One Not",
>     "n": "One Label One Other One Not;Tels;;;"
>   }
> ]
> ```

_Originally posted by @Chadwell89 in https://github.com/cozy/cozy-vcard/issues/28#issuecomment-1280042871_```
- []()****
```

**Comment by msbemba** [comment]
@Chadwell89 Thank you for your feedback. Could you please provide us with the Microsoft document you follow to do this export from Google? Also, this could be a bug, I'll recommend you contact the support team, via the need help section on the admin center so that they can help you fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Chadwell89 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
