### ISSUE TITLE
Assign any M365 license to a User with Disabled plan not working

### ISSUE THREAD

**Issue by NiteshSharma2K19** [MicrosoftDocs/microsoft-365-docs#10229]
Hi Author,

I tried to assign an M365 E5 license to a user in my tenant and the script failed (https://learn.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide#assigning-licenses-to-user-accounts). This account has some other existing subscriptions with a few disabled services. 

The script you have above works fine but only if other subscriptions are not assigned or they don't have disabled services. I need an example script where we can set another subscription (e.g. M365 E5) with disabled services (e.g. Sway) and the user had some other subscription assigned with some disabled services.

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 073b885d-191e-8c00-fa59-ad83ba79ec10
* Version Independent ID: 4bd5799d-9baf-90b6-634d-398fbea6b66f
* Content: [Assign Microsoft 365 licenses to user accounts with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@NiteshSharma2K19 Thank you for your feedback. We shall update and add a new script to the document for this scenario if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@NiteshSharma2K19 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10314

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @NiteshSharma2K19 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
