### ISSUE TITLE
Add link to improve clarity - Intune manage ATP vulnerability

### ISSUE THREAD

**Issue by azvise** [MicrosoftDocs/microsoft-365-docs#10227]
I think 'd be helpful to link the following article under "**Remediation request steps**" **point 5**. for better clarity (Notify your IT Administrator about the new request and have them log into Intune to approve or reject the request and start a package deployment.): 

https://learn.microsoft.com/en-us/mem/intune/protect/atp-manage-vulnerabilities

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e838a1d-9b5d-ce39-11a7-c6f64a42dcf0
* Version Independent ID: 4e838a1d-9b5d-ce39-11a7-c6f64a42dcf0
* Content: [Remediate vulnerabilities](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/tvm-remediation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/tvm-remediation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/tvm-remediation.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @azvise Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
