### ISSUE TITLE
Microsoft Purview solutions trial

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#10228]
Hello,

I see that in almost every document here and there is added text with info about "getting trial for 90 days, etc",
But what if a customer has currently Microsoft 365 E3, they still have included and created services like:
Azure Information Protection Plan 1;
Manual, default, and mandatory sensitivity labeling in Office 365;
Manual labeling with the AIP app and plugin;
Sensitivity labeling for containers in Office 365;
Data Loss Prevention (DLP) for emails & files;
Basic Message Encryption;

And in the portal as Microsoft 365 E3 customer, we already see the "[Microsoft Purview]", so we will lose those benefits and will be locked down to access Microsoft Purview after 90 days? Where we can find information for Microsoft 365 E3 license?

Why and how this applies:
"Microsoft 365 E3 and Office 365 E3 customers who don't already have a Microsoft E5 license package are eligible for the Purview solutions trial. The trial isn't available for Microsoft 365 Government customers."

Can you please share a document explaining the situation for Microsoft 365 E3 customers and services included:
Azure Information Protection Plan 1;
Manual, default, and mandatory sensitivity labeling in Office 365;
Manual labeling with the AIP app and plugin;
Sensitivity labeling for containers in Office 365;
Data Loss Prevention (DLP) for emails & files;
Basic Message Encryption;

Or add something to this document maybe?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20cac351-694d-9907-5fa4-b51292c7a3ba
* Version Independent ID: 71eaaf1f-7bfd-3eca-b742-691fd702268c
* Content: [About the Microsoft Purview solutions trial - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/compliance-easy-trials?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-easy-trials.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-easy-trials.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by yogkumgit** [comment]
@chvukosw Please help us in resolving this issue. Thanks

**Comment by chvukosw** [comment]
Will look into this and get back to you, thanks.

**Comment by chvukosw** [comment]
Hello - the the trial will enable customers to see E5 features in addition to their existing services. Once the trial ends, they go back to what they had prior to the trial; nothing will change for them. Thanks.
