### ISSUE TITLE
Section 6 - ping-pong option for desktop app

### ISSUE THREAD

**Issue by btl512** [MicrosoftDocs/microsoft-365-docs#10232]
Is the ping-pong behavior of Outlook on the web on the roadmap for the Outlook desktop app? If so, any projection on availability?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide#sending-email-from-the-proxy-address-easily)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@btl512 Thank you for your feedback. It is not available in the roadmap yet, however you can post the feedback on main feedback portal( https://feedbackportal.microsoft.com/ ), so that our dev/product engineers will be able to review and respond with accurate information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@btl512 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
