### ISSUE TITLE
Do record versions in the Preservation Hold Library undergo disposition review?

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10237]
Documentation indicates a timer job looks after any 'versions' of records tracked within the Preservation Hold Library (PHL) and progresses them to the 2nd stage Recycle Bin at the end of their retention period as per the documented logic/process. 

Question - If using a record label configured to require disposition review - do any versions stored in the PHL route through the defined disposition review process of the label prior to being moved to recycle bin, or are these directly moved? For that matter - do any 'versions' from the Preservation Hold Library undergo disposition review prior to being moved to recycle bins, or does disposition always center around the original file/record in the Doc Lib based on the applied label and its retention settings?

[How retention works for SharePoint and OneDrive](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-retention-works-for-sharepoint-and-onedrive)

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Investigating

**Comment by cabailey** [comment]
I have some useful updates from an authoritative source & making corresponding edits to the docs.  They should be live tomorrow but, in the meantime, sharing here: 

Any item that's configured for disposition review is exempt from the timer's cleanup process.  Effectively, they behave as "retain forever" until disposition is approved, and then they go straight to the 2nd stage recycle bin.  As the documentation for disposition review mentions, they will be permanently deleted within 15 days of disposition approval. 

Each version has its own file in the Preservation Hold library, stored in the Records folder as documented here: https://learn.microsoft.com/en-us/microsoft-365/compliance/record-versioning  Each version can expire independently so yes, each version will undergo disposition review if that's been configured for the label.

**Comment by kstat** [comment]
@cabailey - Thank you for these notes, and updates to the documentation. 

Just to clarify the last part of my original question - does disposition always center around the tagged document in the original library, or does/could it center around tagged versions of documents in the preservation hold library as well? Trying to understand if the 2nd paragraph in your response above means that a disposition reviewer might see a version of a file from the PHL in the Disposition tab in the Compliance Center after it expires then? Also curious as to what happens to these PHL versions then if the label on the original file gets changed at some point?

In the broader scheme of things - this 'issue' relates to us trying to understand if we can develop a 'Superseded or Obsolete' use-case upon the record versioning capabilities - e.g., if disposition review is always required by an Org prior to purging any records, could we simply tag records with record labels and rely on versioning so that older (superseded) versions go through disposition review before these are disposed?

**Comment by cabailey** [comment]
Yes, disposition review can happen for tagged versions in the PHL before the current version has expired.  Think of the previous versions as separate files to the current version - because this is what they are in the PHL, and how they can have their own end of retention date.  So yes, older versions can expire before the current version that the user sees, but won't be permanently deleted if marked for disposition review until disposition is approved.

What happens if the label is changed on the current version is an interesting question - I'll ask about this, but I assume an unusual occurrence since allowed by only a site admin, not standard users.

**Comment by kstat** [comment]
Thanks, @cabailey. I'm a little stumped on trying to tie together the notes above with the Compliance Center Disposition experience. I don't actually see a version history indication in the Disposition tab when something comes up for disposition review. The 'Location' attribute of the document that's pending disposition in the Disposition tab appears to point to the physical location of the original tagged document itself (and not a previous version of it from the PHL). Based on the above, I was expecting a different type of URL or a reference to a version of the record file, or maybe I've misunderstood the details above?

For reference, I've tried to create multiple record versions in the PHL by locking/unlocking a tagged document on different days this past week for the same document tagged with a 'Based on: Last Modified' record label with a 1-day retention period. I do see the document come up for disposition review, however only a single item is listed for review (which is the original tagged document itself).

**Comment by cabailey** [comment]
Have you tried the "When labeled" to start the retention period as recommended for record versions?  That resets the start of the retention period (unlike Last Modified).

**Comment by kstat** [comment]
Unfortunately, no difference when using the 'When labeled' label. I see only a single document reference in the Disposition tab for what's eligible for disposition, even though multiple versions had been created last week and label is set to expire these after 1-day. For the only document in the tab, there is no indication of version within the UI, just the link that takes me directly to the original tagged document residing within the library.

**Comment by kstat** [comment]
Just circling back on this one to close the loop. I was finally able to see 'versions' of records from the PHL show up for disposition review under the 'Disposition' tab in the Compliance center. The URLs listed for these versions in the Disposition tab have the path to the Perservation Hold Library stored within them (e.g., '.../sites/SiteX/PreservationHoldLibrary/Records/Filename.docx'). 

The timeline however does not make sense to me. I had initially anticipated these to show up for review in up to 7-days after the versions were established in the PHL. When these did not appear, I then assumed it might be up to 37-days after establishing the versions in the PHL (in case the timer job needed these to sit in the PHL for at-least 30 days). In my case, it seems the versions appeared for disposition review almost 7 weeks after these were established in the PHL by unlocking the locked labeled items. This part doesn't make sense to me, but it falls outside of the concern of the documentation and this issue.
