### ISSUE TITLE
How is retention period for record versions determined for record labels that are configured to start retention based on 'When Item was Labeled' or  'When an Event Occurs'?

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10236]
Link does not detail how this works for labels configured to start retention based on when 'Items are labeled' or 'Based on Event' (i.e., only speaks to 'When item was Created', or 'When item was Last Modified').

[How retention works with document versions
](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-retention-works-with-document-versions)

**Comment by cabailey** [comment]
The behavior for these is the same as "when created"- now added.

**Comment by kstat** [comment]
Sorry, @cabailey - doesn't the 'when labeled' definition based on this revision above conflict with what the 'tip' on this page below suggests? If the 'tip' is accurate, then presumably the 'when labeled' works similarly to how 'last modified' worked before July 2022?

https://learn.microsoft.com/en-us/microsoft-365/compliance/record-versioning?view=o365-worldwide

**Comment by kstat** [comment]
@cabailey Since the issue is marked closed, not sure if the comment above might have fallen by the wayside, or if you've received a notification re: it? Assuming this gets through, let me know if you need me to create a separate issue for this. 

Much appreciated! Thanks!!

**Comment by cabailey** [comment]
Although the issue is closed I still get notified and agree we seem to have introduced a contradiction, here. I'm investigating & will update this thread (no need to open a new one) and the documentation as needed, but most people are out this week for US Thanksgiving holiday.

**Comment by cabailey** [comment]
This technology is full of exceptions (and variations) - and this is a good example where both statements are true but missing the glue to explain how. The new single file behavior doesn't apply to record versions.  These remain independent files, which can therefore expire independently of each other.  I'll be making updates to clarify this as well - good catch!
