### ISSUE TITLE
How many records labels can you have in a single tenant?

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10235]
The maximum # of retention labels per tenant is 1000 as per the link below. Is this specific to just the 'retention labels' (i.e., which do not mark a document as a record), or applies to any kind of label (i.e., inclusive of Record or Regulatory Record)?

[Maximum number of retention labels per tenant
](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-limits?view=o365-worldwide#maximum-number-of-retention-labels-per-tenant)

**Comment by msbemba** [comment]
@kstat Thank you for your feedback. Great question, it is specific to just the retention labels and does not include any other records.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kstat Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
