### ISSUE TITLE
Is it possible to back date when a retention label was applied to a document in SPO?

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10238]
Apologies if this is not the right forum to ask this question - please direct me to the correct forum in case it is not.

When applying a retention label to a document in SharePoint Online through the UI, Compliance specific properties are automatically assigned, one of which includes 'Retention label Applied', or internally known as 'ComplianceTagWrittenTime'. 

Is it possible to overwrite this value through API? There appears to be a CSOM method that likely allows something of this nature, though there is no documentation explaining what it does, what parameter values it accepts, or if it supports this operation.

[ListItem.SetComplianceTagWithExplicitMetasUpdate Method
](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.client.listitem.setcompliancetagwithexplicitmetasupdate?view=sharepoint-csom)

**Comment by msbemba** [comment]
@kstat Thank you for your feedback. Looks like the document in question does not have a feedback option. However, you can post this feedback on our main sharepoint feedback portal[SharePoint · Community (microsoft.com)](https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472) and our dev/product engineer will be able to answer your query.

Hope this helps!

Thanks
Sri

**Comment by kstat** [comment]
Thank you. I've posted the question there as suggested.
