### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by woiim** [MicrosoftDocs/microsoft-365-docs#10245]
This change to TLS instruction is too technical for the average home user of Office 365.
Please advise if Office 365 updates automatically changes your TLS

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec089a7-8f7b-d4d9-a763-e8abd73fb2c9
* Version Independent ID: 41ba8999-f0ea-5847-afad-8620dd83492a
* Content: [Disabling TLS 1.0 and 1.1 for Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-au/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365?view=o365-worldwide&ocid=cmmvcsuhj3z)
* Content Source: [microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @WorkShay
* Microsoft Alias: **fasqiu**

**Comment by msbemba** [comment]
@woiim Thank you for your feedback. The effect on end-users is minimal. the change is basically to deprecate the protocol and start using the latest version. In case, if you have issues connecting to Exchange or any of the Microsoft services using applications like outlook, teams, etc, feel free to open a support case via the need help section in the M365 admin center and the support team will be able to assist you.

Hope this helps!

Thanks
Sri
