### ISSUE TITLE
At a loss

### ISSUE THREAD

**Issue by curious-condor** [MicrosoftDocs/microsoft-365-docs#10241]
Have no idea what any of this means.  Update my client?  What is or who is that?  I have an old email that I still use and there is some kind of problem with it on Dec1.  That's what I got. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec089a7-8f7b-d4d9-a763-e8abd73fb2c9
* Version Independent ID: 41ba8999-f0ea-5847-afad-8620dd83492a
* Content: [Disabling TLS 1.0 and 1.1 for Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365?view=o365-worldwide&ocid=cmmvcsuhj3z)
* Content Source: [microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @WorkShay
* Microsoft Alias: **fasqiu**

**Comment by msbemba** [comment]
@curious-condor Thank you for your feedback. The effect on end-users is minimal. the change is basically to deprecate the protocol and start using the latest version. In case, if you have issues connecting to Exchange or any of the Microsoft services using applications like outlook, teams, etc, feel free to open a support case with our technical support team and the support engineerwill be able to assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @curious-condor Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
