### ISSUE TITLE
TLS Changes to Office 365 Home

### ISSUE THREAD

**Issue by woiim** [MicrosoftDocs/microsoft-365-docs#10246]
This change to TLS instruction is too technical for the average home user of Office 365.
Please advise if Office 365 updates automatically changes your TLS

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec089a7-8f7b-d4d9-a763-e8abd73fb2c9
* Version Independent ID: 41ba8999-f0ea-5847-afad-8620dd83492a
* Content: [Disabling TLS 1.0 and 1.1 for Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-au/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365?view=o365-worldwide&ocid=cmmvcsuhj3z)
* Content Source: [microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @WorkShay
* Microsoft Alias: **fasqiu**

**Comment by RAJU2529** [comment]
@yogkumgit , close this issue #10246 because this is duplicate
