### ISSUE TITLE
Manage discovery for private teams

### ISSUE THREAD

**Issue by mcantin** [MicrosoftDocs/microsoft-365-docs#10249]
[Manage discovery of private teams in Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams)

At the top of the page there is a link to 'Manage discovery of private teams'. This link URL is 'https://learn.microsoft.com/en-us/microsoftteams/manage-discovery-of-private-teams', but the URL resolves to 'https://learn.microsoft.com/en-us/microsoftteams/teams-overview' possibly because the discovery of private teams was rescinded or deprecated according to https://techcommunity.microsoft.com/t5/microsoft-teams/workaround-to-find-private-teams-for-employees-to-request-access/m-p/3067423

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c9e89b4-e660-da7c-f9d3-b27faacbe85a
* Version Independent ID: 8541efa3-47eb-fe52-4e80-e018b6e412dd
* Content: [Governing access in Microsoft 365 groups, Teams, and SharePoint](https://learn.microsoft.com/en-us/microsoft-365/solutions/groups-teams-access-governance?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/groups-teams-access-governance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/groups-teams-access-governance.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@mcantin Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10260

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mcantin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
