### ISSUE TITLE
Container definition seems inaccurate

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10240]
Per table footnote in referenced article below - Records shouldn't be allowed to cross a Document Library boundary if it has been unlocked at-least once. In our tests, records were able to be moved to other libraries within the same site after they had already been unlocked (and then left in that state, or re-locked again). We tested using record retention labels. 

Should the container definition be a 'Site' instead?

[Compare restrictions for what actions are allowed or blocked
](https://learn.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide#compare-restrictions-for-what-actions-are-allowed-or-blocked)

**Comment by msbemba** [comment]
@kstat Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10268

Once the author approves, the changes will be live.

Thanks
Sri
