### ISSUE TITLE
Very Helpful - request for more

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#10248]
This is very helpful and a nice, concise discussion. Please create similar documentation for all of the Defender products

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e32e2ed-5ae3-d1c6-6a5b-25b225647dbf
* Version Independent ID: 3f5d0ae5-a9b0-f755-c2f6-c38c75e3e485
* Content: [Step-by-step threat protection stack in Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
Good idea. But not directly actionable as an item to track in a GitHub issue.

**Comment by yogkumgit** [comment]
@DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
