### ISSUE TITLE
Screensize change for F plans not changed to 10.9"

### ISSUE THREAD

**Issue by basbax** [MicrosoftDocs/microsoft-365-docs#10254]
Screensize hasn't been changed to 10.9" for F plans on this site.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a66e2933-c8de-0ae5-c6a4-bb83d7152b56
* Version Independent ID: a66e2933-c8de-0ae5-c6a4-bb83d7152b56
* Content: [Changing from a Microsoft 365 E plan to a Microsoft 365 F plan - Microsoft 365 for frontline workers](https://learn.microsoft.com/en-us/microsoft-365/frontline/switch-from-enterprise-to-frontline?view=o365-worldwide)
* Content Source: [microsoft-365/frontline/switch-from-enterprise-to-frontline.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/frontline/switch-from-enterprise-to-frontline.md)
* Service: **microsoft-365-frontline**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by msbemba** [comment]
@basbax Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10267

Once the author approves, the changes will be live.

Thanks
Sri
