### ISSUE TITLE
Please add Valimail offering for Office 365

### ISSUE THREAD

**Issue by ilantz** [MicrosoftDocs/microsoft-365-docs#1025]
The doc mentions Agari as a 3rd party DMARC monitoring service for Microsoft.com

We should also mention that Valimail offers free DMARC monitoring services for Office 365. As announced here https://www.microsoft.com/security/blog/2019/06/03/secure-cloud-free-dmarc-monitoring-office-365/

Please add this under the as a note in the implementation steps so that admins are aware they can use this https://go.valimail.com/microsoft.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email#what-is-a-dmarc-txt-record)
* Content Source: [microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@ilantz -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/939c7105722164bb3f90929527063fd97bcfeef0. 


Thank you for your contribution to make the docs better! Much appreciated!
