### ISSUE TITLE
Cross Tenant Feature is not Enabled (OneDrive)

### ISSUE THREAD

**Issue by dvbnl** [MicrosoftDocs/microsoft-365-docs#10255]
I've tested the Mailbox Cross Tenant migration (preview) and everything works fine. While testing the OneDrive cross tenant migration I'm getting the following error:

`Set-SPOCrossTenantRelationship : The Cross-Tenant content move feature is not enabled for this tenant.`

The prerequisites say:
Turn off service encryption with Customer Key enabled. Confirm that the source OneDrive tenant doesn't have Service encryption with Microsoft Purview Customer Key enabled. If enabled on Source tenant, the migration will fail. [Learn more on Service encryption with Microsoft Purview Customer Key](https://learn.microsoft.com/en-us/microsoft-365/compliance/customer-key-overview)

Is Customer Key required to make this work (without encryption)?

**Comment by tolive-csti** [comment]
Following this issue :
Same issue when trying to get CrossTenant URL when running Get-SPOCrossTenantHostURL :

`Set-SPOCrossTenantRelationship : The Cross-Tenant content move feature is not enabled for this tenant.`

**Comment by dvbnl** [comment]
> Following this issue : Same issue when trying to get CrossTenant URL when running Get-SPOCrossTenantHostURL :
> 
> `Set-SPOCrossTenantRelationship : The Cross-Tenant content move feature is not enabled for this tenant.`

The Get-SPOCrossTenantHostURL is working for me. My error occurs at the next command:

`Set-SPOCrossTenantRelationship -Scenario MnA -PartnerRole Target -PartnerCrossTenantHostUrl $url`

I've also made a ticket at Microsoft. All prerequisites and licenses are correct.

**Comment by msbemba** [comment]
@dvbnl Thank you for your feedback. You need to disable Service encryption with Microsoft Purview Customer Key. If that is already complete and you meet the prerequisites, I recommend you continue working with the support engineer you are currently working with to resolve the issue.

Hope this helps!

Thanks
Sri

**Comment by dvbnl** [comment]
> @dvbnl Thank you for your feedback. You need to disable Service encryption with Microsoft Purview Customer Key. If that is already complete and you meet the prerequisites, I recommend you continue working with the support engineer you are currently working with to resolve the issue.
> 
> 
> 
> Hope this helps!
> 
> 
> 
> Thanks
> 
> Sri

Hi Sri,

Thanks for your answer! Customer Key is disabled in both tenants right now so I'll request and configure it first.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @dvbnl Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Phurba2123** [comment]
> @dvbnl Thank you for your feedback. You need to disable Service encryption with Microsoft Purview Customer Key. If that is already complete and you meet the prerequisites, I recommend you continue working with the support engineer you are currently working with to resolve the issue.
> 
> Hope this helps!
> 
> Thanks Sri

Hi @yogkumgit ,

How can we disable Service encryption with Microsoft Purview Customer Key? I could not get how to disable it?
Please let me know. It will be very helpfull.

**Comment by dvbnl** [comment]
> > @dvbnl Thank you for your feedback. You need to disable Service encryption with Microsoft Purview Customer Key. If that is already complete and you meet the prerequisites, I recommend you continue working with the support engineer you are currently working with to resolve the issue.
> 
> > 
> 
> > Hope this helps!
> 
> > 
> 
> > Thanks Sri
> 
> 
> 
> Hi @yogkumgit , @msbemba 
> 
> 
> 
> How can we disable Service encryption with Microsoft Purview Customer Key? I could not get how to disable it?
> 
> Please let me know. It will be very helpful.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/67428946/203977017-3d469947-7b1c-4482-820f-851bfa714fc5.png)
> 
> 

I still experience the same issue.. MS support told me to use mover.io which will be retired next year in January.

They told me that there will be an alternative before that date. They call me when it's up

**Comment by SamanthaSt** [comment]
@dvbnl  did you get a Feedback from Microsoft? 
I wanted to test the OneDrive migration Today and ran into the same problem in both my tenants.

**Comment by dvbnl** [comment]
> @dvbnl  did you get a Feedback from Microsoft? 
> 
> I wanted to test the OneDrive migration Today and ran into the same problem in both my tenants. 

Unfortunately not, it's almost the 31th ALs Mover.IO is coming to it's end. There should be an alternative for that one in the 365 migration center.

But to be honest I'd prefer the SPO move feature..

**Comment by SamanthaSt** [comment]
> Unfortunately not, it's almost the 31th so Mover.IO is coming to it's end. There should be an alternative for that one in the 365 migration center.

Thanks for the reply. I looked at the O365 Migration Center but I didn´t see a One Dirve Cross Tenant Migration option so far. 
Hope you find a solution ;)

**Comment by dvbnl** [comment]
@SamanthaSt will let you know. Working on some tenant migration projects so I'm on it on a daily basis.

**Comment by rlacko-sygic** [comment]
> @dvbnl did you get a Feedback from Microsoft? I wanted to test the OneDrive migration Today and ran into the same problem in both my tenants.

Same here. I first started the configuration of the tenants with older version of Sharepoint Management Shell and was able to set organization relationships, verify the relationship,  but was not able to upload identity mapping file because some of the cmdlets were missing. Then updated the management shell and after that the game was over. Event the Verify-SPOCrossTenantRelationship cmdlet which was working before is throwing  "The Cross-Tenant content move feature is not enabled for this tenant." error now.

**Comment by beezneezy** [comment]
@dvbnl Just checking in myself here. I doubt there is any additional word but I am curious if anything has changed.

**Comment by dvbnl** [comment]
> @dvbnl Just checking in myself here. I doubt there is any additional word but I am curious if anything has changed.

Unfortunately not! Still working on it, will post an update here asap I hope..

**Comment by drkmccy** [comment]
I've tried this on three different tenants and getting the same issue

**Comment by dvbnl** [comment]
I've got more information on this case, almost wrapping this up and I'll share my work around soon

**Comment by eixgit** [comment]
Hi @dvbnl - what was the workaround? I have a migration deadline approaching and I haven't gotten any help from Microsoft so far.

**Comment by drkmccy** [comment]
@dvbnl please do, I have raised a ticket with Microsoft who are clueless. They told me to raise with FastTrack who said its not their remit, then they told me to use Mover.io. Clearly their desk doesn't have a grasp of the situation. 

@eixgit I just did a migration using a trial of Sharegate. I was hoping the tool was as quick, easy and simple as Mover.io given how slick their website is but unfortunately it was slower, more complex, and it downloads everything locally before re-uploading to the new tenant. I did do a free trial of Avepoint Fly (only migrates 3 users) which was really impressive - easier and simpler than Mover.io (really!) so we might give them a call to get pricing.

**Comment by dvbnl** [comment]
The 'bug' is known and is on purpose. The SPOrelationship between tenants can be established with cross-tenant synchronization. It's currently in preview but soon it will go into production.

If you use the cross-tenant synchronization to create the trusts you can basically skip this part and continue with the migration. 
At the moment I'm using the following code to extract the identities from the source tenant and create the CSV to migrate the users to the destination tenant

`### SOURCE TENANT ATTRIBUTE EXTRACT ###
Write-Host "========================================================================" -ForegroundColor Magenta
Write-Host "CSV SPO USERS GENEREREN" -BackgroundColor White -ForegroundColor Black
Write-Host "========================================================================" -ForegroundColor Magenta
timeout /t 20

    ## CONNECT TENANT + CUSTOM VARIABLES
    Write-Host "Connecting > source tenant......." -BackgroundColor White -ForegroundColor Black
    Start-Sleep -Seconds 5
    Connect-AzureAD | Out-Null
    $TargetUPN = Read-Host "Vul de target tenant domein in (bijv: testtenant.onmicrosoft.com)"
    $TenantID = Read-Host "Vul de target tenant id in"

    ## IMPORT USERS
    $AllUsers = Import-Csv -Delimiter ';' -Path $CSV
    $UserList = @()

    Foreach ($User in $AllUsers)
        {       
            ## GET USER ATTRIBUTES
            $Object = Get-AzureADUser -SearchString $User.UserPrincipalName
            Start-Sleep -Milliseconds 10

            ## VARIABLES
            $SourceUPN = $Object.UserPrincipalName
            $UserType = $Object.UserType
            $Alias = $Object.MailNickName

            # NOTIFY PROGRESS
            Write-Host "User $Alias is processed"

            ## UPDATE USERLIST
            $UserList = $UserList + [PSCustomObject]@{User = $Alias; SourceTenantCompanyID = $TenantID; SourceUserUpn = $SourceUPN; TargetUserUpn = ($Alias +"@$TargetUPN"); TargetUserEmail = ($Alias +"@$TargetUPN"); UserType = $UserType}
        }

    ## RESULT SOURCE TENANT
    Write-Host "========================================================================" -ForegroundColor Magenta
    Write-Host "PROCESSING......." -BackgroundColor White -ForegroundColor Black
    Write-Host "========================================================================" -ForegroundColor Magenta

    ## EXPORT TO CSV
    $UserList | Export-Csv -Path ".\SPO-Users.csv" -NoTypeInformation

    ## SLEEP + NOTIFY
    Start-Sleep -Seconds 5
    Write-Host "Attributes zijn exported naar CSV" -ForegroundColor White
    Start-Sleep -Seconds 5`

**Comment by dvbnl** [comment]
https://learn.microsoft.com/en-us/azure/active-directory/multi-tenant-organizations/cross-tenant-synchronization-configure

**Comment by staticset** [comment]
Hi @dvbnl 
I created the trusts between tennant use link that you provided, but get same error. Any ideas?

**Comment by wilkinet** [comment]
Hi @dvbnl 
Up to what section of the Cross-Tenant Synchronization guide must you go before reverting back to the OneDrive Cross-Tenant Migration guide? I obviously do not want to follow the entire Cross Tenant Synchronization method. I assume the trust verification confirmation commands will never succeed in this Known issue scenario and I would just have to move on to the part of creating the mapping file portion of the guide? Running other verification checks also indicates that the feature is only supported in Multi-Geo tenants. I however have no location configuration available in my Sharepoint Admin portal.

**Comment by dvbnl** [comment]
> Hi @dvbnl 
> 
> Up to what section of the Cross-Tenant Synchronization guide must you go before reverting back to the OneDrive Cross-Tenant Migration guide? I obviously do not want to follow the entire Cross Tenant Synchronization method. I assume the trust verification confirmation commands will never succeed in this Known issue scenario and I would just have to move on to the part of creating the mapping file portion of the guide? Running other verification checks also indicates that the feature is only supported in Multi-Geo tenants. I however have no location configuration available in my Sharepoint Admin portal.
> 
> 
> 
> 

Indeed, it's all about the trust. After that the mapping is the next step!

**Comment by dvbnl** [comment]
> Hi @dvbnl 
> 
> I created the trusts between tennant use link that you provided, but get same error. Any ideas?

Check the last 2 comments here. It's all about the trust part indeed!

**Comment by itsHenry35** [comment]
> The 'bug' is known and is on purpose. The SPOrelationship between tenants can be established with cross-tenant synchronization. It's currently in preview but soon it will go into production.
> 
> If you use the cross-tenant synchronization to create the trusts you can basically skip this part and continue with the migration. At the moment I'm using the following code to extract the identities from the source tenant and create the CSV to migrate the users to the destination tenant
> 
> ```
> ## CONNECT TENANT + CUSTOM VARIABLES
> Write-Host "Connecting > source tenant......." -BackgroundColor White -ForegroundColor Black
> Start-Sleep -Seconds 5
> Connect-AzureAD | Out-Null
> $TargetUPN = Read-Host "Vul de target tenant domein in (bijv: testtenant.onmicrosoft.com)"
> $TenantID = Read-Host "Vul de target tenant id in"
> 
> ## IMPORT USERS
> $AllUsers = Import-Csv -Delimiter ';' -Path $CSV
> $UserList = @()
> 
> Foreach ($User in $AllUsers)
>     {       
>         ## GET USER ATTRIBUTES
>         $Object = Get-AzureADUser -SearchString $User.UserPrincipalName
>         Start-Sleep -Milliseconds 10
> 
>         ## VARIABLES
>         $SourceUPN = $Object.UserPrincipalName
>         $UserType = $Object.UserType
>         $Alias = $Object.MailNickName
> 
>         # NOTIFY PROGRESS
>         Write-Host "User $Alias is processed"
> 
>         ## UPDATE USERLIST
>         $UserList = $UserList + [PSCustomObject]@{User = $Alias; SourceTenantCompanyID = $TenantID; SourceUserUpn = $SourceUPN; TargetUserUpn = ($Alias +"@$TargetUPN"); TargetUserEmail = ($Alias +"@$TargetUPN"); UserType = $UserType}
>     }
> 
> ## RESULT SOURCE TENANT
> Write-Host "========================================================================" -ForegroundColor Magenta
> Write-Host "PROCESSING......." -BackgroundColor White -ForegroundColor Black
> Write-Host "========================================================================" -ForegroundColor Magenta
> 
> ## EXPORT TO CSV
> $UserList | Export-Csv -Path ".\SPO-Users.csv" -NoTypeInformation
> 
> ## SLEEP + NOTIFY
> Start-Sleep -Seconds 5
> Write-Host "Attributes zijn exported naar CSV" -ForegroundColor White
> Start-Sleep -Seconds 5`
> ```

![image](https://user-images.githubusercontent.com/58730749/236658953-6a4d109f-c8e4-4a30-8a4a-8a2200bc9819.png)
Why's that?

**Comment by dvbnl** [comment]
> > The 'bug' is known and is on purpose. The SPOrelationship between tenants can be established with cross-tenant synchronization. It's currently in preview but soon it will go into production.
> 
> > 
> 
> > If you use the cross-tenant synchronization to create the trusts you can basically skip this part and continue with the migration. At the moment I'm using the following code to extract the identities from the source tenant and create the CSV to migrate the users to the destination tenant
> 
> > 
> 
> > ```
> 
> > ## CONNECT TENANT + CUSTOM VARIABLES
> 
> > Write-Host "Connecting > source tenant......." -BackgroundColor White -ForegroundColor Black
> 
> > Start-Sleep -Seconds 5
> 
> > Connect-AzureAD | Out-Null
> 
> > $TargetUPN = Read-Host "Vul de target tenant domein in (bijv: testtenant.onmicrosoft.com)"
> 
> > $TenantID = Read-Host "Vul de target tenant id in"
> 
> > 
> 
> > ## IMPORT USERS
> 
> > $AllUsers = Import-Csv -Delimiter ';' -Path $CSV
> 
> > $UserList = @()
> 
> > 
> 
> > Foreach ($User in $AllUsers)
> 
> >     {       
> 
> >         ## GET USER ATTRIBUTES
> 
> >         $Object = Get-AzureADUser -SearchString $User.UserPrincipalName
> 
> >         Start-Sleep -Milliseconds 10
> 
> > 
> 
> >         ## VARIABLES
> 
> >         $SourceUPN = $Object.UserPrincipalName
> 
> >         $UserType = $Object.UserType
> 
> >         $Alias = $Object.MailNickName
> 
> > 
> 
> >         # NOTIFY PROGRESS
> 
> >         Write-Host "User $Alias is processed"
> 
> > 
> 
> >         ## UPDATE USERLIST
> 
> >         $UserList = $UserList + [PSCustomObject]@{User = $Alias; SourceTenantCompanyID = $TenantID; SourceUserUpn = $SourceUPN; TargetUserUpn = ($Alias +"@$TargetUPN"); TargetUserEmail = ($Alias +"@$TargetUPN"); UserType = $UserType}
> 
> >     }
> 
> > 
> 
> > ## RESULT SOURCE TENANT
> 
> > Write-Host "========================================================================" -ForegroundColor Magenta
> 
> > Write-Host "PROCESSING......." -BackgroundColor White -ForegroundColor Black
> 
> > Write-Host "========================================================================" -ForegroundColor Magenta
> 
> > 
> 
> > ## EXPORT TO CSV
> 
> > $UserList | Export-Csv -Path ".\SPO-Users.csv" -NoTypeInformation
> 
> > 
> 
> > ## SLEEP + NOTIFY
> 
> > Start-Sleep -Seconds 5
> 
> > Write-Host "Attributes zijn exported naar CSV" -ForegroundColor White
> 
> > Start-Sleep -Seconds 5`
> 
> > ```
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/58730749/236658953-6a4d109f-c8e4-4a30-8a4a-8a2200bc9819.png)
> 
> Why's that?
> 
> 

Because of the system language. Let me take a look at it tomorrow!

At the moment I'm working on a migration tool with GUI based on all available API's and modules from Microsoft to do tenant-to-tenant migrations.
