### ISSUE TITLE
Clarify Record Retention statement

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10272]
Please clarify what is meant by: Only when the Record status property is set to Locked is a new version of the record retained.

The word 'retained' is ambiguous or the definition is overloaded or unclear in this context? Does it imply 'prevent edits' or does it relate to how the retention period for the version is determined?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b41860d-88f5-a81d-435b-de6e8b5ef0cc
* Version Independent ID: c092d603-411d-09bb-1626-464f104325f3
* Content: [Use record versioning in SharePoint or OneDrive - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/record-versioning?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/record-versioning.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/record-versioning.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@kstat Thank you for your feedback. When the file is locked, the latest version of the document is a record. When the file is unlocked, a reference to this version (preserved as a record) is added to the version history. 

Subsequent edits to the document, when it is unlocked, create versions that are not declared as a record. To declare the latest version, you will need to lock the file, which will declare the latest version as record in SharePoint online.

Hope this help!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kstat Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kstat** [comment]
Sorry, just wanting to seek additional clarification re: the comments above @msbemba. Is it the case that 'retained' here implies that the retention clock on a tagged document (assuming label is configured to mark item as a record) would not start until the document is in a locked state?
