### ISSUE TITLE
prerequisite endpoints

### ISSUE THREAD

**Issue by crankyroadkill** [MicrosoftDocs/microsoft-365-docs#10273]
This page lists only the following endpoints as required:

enterpriseregistration.windows.net - For Azure AD registration.
login.microsoftonline.com - For Azure AD registration.
*.dm.microsoft.com - The use of a wildcard supports the cloud-service endpoints that are used for enrollment, check-in, and reporting, and which can change as the service scales.

What about all the other endpoints required by the "Microsoft Defender for Endpoint URL list for commercial customers" (spreadsheet)?

Please clarify any and all endpoint URL requirements.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e93f9bbd-5752-e28a-f32d-a01d81964c8f
* Version Independent ID: e93f9bbd-5752-e28a-f32d-a01d81964c8f
* Content: [Manage Microsoft Defender for Endpoint configuration settings on devices with Microsoft Endpoint Manager](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/security-config-management?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/security-config-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/security-config-management.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Pls contact support.
