### ISSUE TITLE
Link to old Video

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#10275]
the link to the video points to something that is no longer accurate because the UI has changed, this is confusing. Please remove the link or update the video. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b680bb5-de3b-ee83-3764-91695bab77ed
* Version Independent ID: 9c770adf-a66e-ed32-25aa-ffbc46eaef82
* Content: [Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/defender-for-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10310

Once the author approves, the old video will be removed.

Thanks
Sri

**Comment by Ratulch** [comment]
Merged https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10310.
