### ISSUE TITLE
New search does not have the possibility to Filter for Set-Mailbox

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#10286]
You mention:

> Activity column header, type Set-Mailbox so that only audit records related to the Set-Mailbox cmdlet are displayed

However, it's not possible to filter on **Set-Mailbox** in the Filter.

![image](https://user-images.githubusercontent.com/32098920/202188042-3603bd87-5e66-4a60-b5bd-32aa6891c453.png)

I think this might be related to the implementation of **New Search** but it's not even available in **Classic search**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51490fff-e4b6-24fe-d203-cec12a0db3a2
* Version Independent ID: 83caa7b3-3a93-a0e3-7d0a-74cacee4407a
* Content: [Search the audit log to troubleshoot common scenarios - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/auditing-troubleshooting-scenarios?view=o365-worldwide#determine-who-set-up-email-forwarding-for-a-mailbox)
* Content Source: [microsoft-365/compliance/auditing-troubleshooting-scenarios.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/auditing-troubleshooting-scenarios.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@JonesMikael Thank you for your feedback. The Activities section should be blank so that the search returns audit records for all activities. Once the results are available, you can filter with the set-mailbox cmdlet to see if audit records are related to the Set-Mailbox.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JonesMikael Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
