### ISSUE TITLE
Incorrect steps for OneDrive "Create and run a search"

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/microsoft-365-docs#10287]
[Enter feedback here]

Documentation states for OneDrive that you use an account to search, see below:

SharePoint sites: Set the toggle to On and then select Choose sites to specify SharePoint sites **and OneDrive accounts to search**. Enter the URL for each site that you want to search. You can also add the URL for the SharePoint site for a Microsoft Team, Microsoft 365 Group, or Yammer Group.

However, when performing a Content Search (https://compliance.microsoft.com/contentsearchv2?viewid=search) you don't have options to add a OneDrive account, rather you need to search for the personal site "https://tenant-my.sharepoint.com/personal/" that is the only option for OneDrive.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04e514aa-9f04-5cc9-93f6-9f5f2f614c2a
* Version Independent ID: dea1ab15-bc09-05c1-b48b-1a06c0b53b50
* Content: [Create and run a Content search in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@ddaanniieell9 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10308

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@ddaanniieell9 closing it as per author's comment in PR. Thanks
