### ISSUE TITLE
Docs For "Scenario: Left wildcard subdomain and right wildcard suffix" Do Not Explicitly Detail Multiple Sub-Directories For Tilde

### ISSUE THREAD

**Issue by cskujawa** [MicrosoftDocs/microsoft-365-docs#10289]
In the docs located at the link below it is not explicitly mentioned whether a left and right tilde would match or not match multiple sub-directories as in the example cases below. These examples are included for the left and right wildcard. 

- abc.xyz.contoso.com/a/b/c
- contoso.com/b/a/c

https://learn.microsoft.com/microsoft-365/security/office-365-security/allow-block-urls#url-syntax-for-the-tenant-allowblock-list
![image](https://user-images.githubusercontent.com/62387276/202237531-2b8bfe8d-4c4b-4860-b551-627648f60158.png)

.md where these are documented:

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/3c6e4d5d04cd0816bd9397bb321057ff0a85a39a/microsoft-365/security/office-365-security/tenant-allow-block-list.md#scenario-left-wildcard-subdomain-and-right-wildcard-suffix

**Comment by chrisda** [comment]
@cskujawa is this the same 'missing www' problem from your [other issue](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10288)? If so, I added the www entries back per the same related PR.

**Comment by cskujawa** [comment]
Hello Chris, thanks for taking a look into this, in regards to this one I just noticed it hadn't mentioned a few examples of cases where entries with a ~ would be matched, but they were mentioned in the wildcard examples. Specifically multiple directories in the file path.

So it doesn't say that with an entry for ~contoso.com~ these would also match:

- abc.xyz.contoso.com/a/b/c
- contoso.com/b/a/c

That being said, these examples were also affected by the other issue which looks good now, thank you!

**Comment by chrisda** [comment]
@cskujawa, I would encourage you to make any changes you like directly in the topics themselves. It's super-easy. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md). Just @ include me in the comments, and I'll review your pull request and publish.

**Comment by cskujawa** [comment]
Done, thank you for your assistance @chrisda, closing this out.

There's also an erroneous newline at 416, didn't catch it until looking at the side by side, unfortunately I can't edit the commit to fix it.
