### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by tarrzan33** [MicrosoftDocs/microsoft-365-docs#10280]
Your links to the json on github are broken and return page not found. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d10d24d-490f-f943-f8f0-4c3817812d59
* Version Independent ID: 91ae55bd-0673-f709-336b-7825ce9b9027
* Content: [Step 2. Use Microsoft Teams to create your contract management channel - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/contentunderstanding/solution-manage-contracts-step2)
* Content Source: [microsoft-365/contentunderstanding/solution-manage-contracts-step2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/solution-manage-contracts-step2.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@tarrzan33 -- Thank you so much for letting us know about the broken link. We are looking into it and trying to see what needs to be done to fix it. Again, thank you.

**Comment by chuckedmonson** [comment]
@tarrzan33 -- This issue has been resolved. Thanks again for letting us know.
