### ISSUE TITLE
URL Rendering Issue In "Allow or block URLs using the Tenant Allow/Block List" Article

### ISSUE THREAD

**Issue by cskujawa** [MicrosoftDocs/microsoft-365-docs#10288]
The document located at the link below appears to be auto-formatting URLs with the "www" subdomain. This poses a potential issue as the subdomains may not be blocked or allowed and some examples conflict with each other. In cases where the URL contoso.com and www.contoso.com have the same functionality they appear as duplicates.

https://learn.microsoft.com/microsoft-365/security/office-365-security/allow-block-urls#url-syntax-for-the-tenant-allowblock-list 

For instance on the docs page, the scenario for "No Wildcards" says an entry for contoso.com will be matched and not matched for allows. For blocks contoso.com appears twice on the list.

![image](https://user-images.githubusercontent.com/62387276/202232113-d9fdd652-ab78-426f-818f-37b73b40531d.png)

In the .md linked below they appear as written.

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/3c6e4d5d04cd0816bd9397bb321057ff0a85a39a/microsoft-365/security/office-365-security/tenant-allow-block-list.md

![image](https://user-images.githubusercontent.com/62387276/202233063-0830b645-6be4-4f39-91a8-a453351fd2a7.png)

**Comment by chrisda** [comment]
@cskujawa, I don't think there's any auto-formatting going on. Someone must have literally removed the www from those entries. I added them back throughout.

Thanks for the feedback.

Closing
