### ISSUE TITLE
MEM is missing along the valid values for ServiceAreas parameter in Endpoints web method

### ISSUE THREAD

**Issue by taikuli** [MicrosoftDocs/microsoft-365-docs#10283]
Good Morning!

According to https://learn.microsoft.com/en-us/mem/intune/fundamentals/intune-endpoints there seems to be another valid value for the parameter **ServiceAreas** in the endpoints web method: **MEM**

Please add it here and double check for other changes to the webservice that might require changes to this documentation.

Thanks

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd333ae2-34f6-4afd-cdb1-db72303a5736
* Version Independent ID: 5fc52fe8-dade-b8b7-7126-c4e7dd902e62
* Content: [Office 365 IP Address and URL web service - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-ip-web-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-ip-web-service.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
@taikuli, thanks for reaching out. I spoke with the endpoints web service PM and this value is part of an ongoing development effort to update the web service. Use of the **MEM** value for the _ServiceAreas_ parameter may therefore have unpredictable results until this work is complete. I'm working with the owner of the Intune topic to pull related guidance until development work has been completed and we can publish a complete set up updates to all related guidance. -Kelley
