### ISSUE TITLE
Missing informations about Released/Published date in mac-whatsnew page.

### ISSUE THREAD

**Issue by kash1064** [MicrosoftDocs/microsoft-365-docs#10284]
Hello Experts.

Could you add Release/Publish date informations to each build on this page?

I found these informations is lack after "Aug-2022 (Build: 101.75.90 | Release version: 20.122071.17590.0)".

These are important informations especially for many users.
It can very help us to maintain environments.

So please add Release/Publish date informations to each build on this page.
Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00948177-b26b-c26c-8ff3-7ad66f388623
* Version Independent ID: f370db23-e9ec-93c1-9ce2-957e111dcfce
* Content: [What's new in Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-whatsnew?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-whatsnew.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-whatsnew.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@kash1064 Thank you for your feedback. We have updated dates for Nov and Oct via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10313c

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kash1064 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
