### ISSUE TITLE
Any details on MC467231?

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#10281]
How is BCL SCORING changing?  Or is this also being kept secretive?  Seeing a LOT more UCE type emails that pass Sender Auth, aren't spam, but are getting through at MULTIPLE customer tenants despite any BCL settings (said another way they are scoring a 0 today)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5942c743-89c5-43c8-330a-dafbbb2dde37
* Version Independent ID: 025fd91b-9ddf-fc72-16e4-2f19ab860ed7
* Content: [What's the difference between junk email and bulk email? - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email?view=o365-worldwide#how-to-tune-bulk-email)
* Content Source: [microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
I'm not sure that BCL scoring is changing. You should open a support ticket and ask.

**Comment by chrislehr** [comment]
The message center says this:

"We are rolling out several changes in how we allocate BCL scores to messages to provide more accurate scoring and coverage for bulk messages."  MC467231

Ill open a ticket shortly.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chrislehr** [comment]
‎33878442‎ opened in my tenant.
