### ISSUE TITLE
Adding Superuser without adding as Staff automap parameter

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [MicrosoftDocs/microsoft-365-docs#10282]
The Add-MailboxPermission command does not include "-AutoMapping:$false", causing the Booking mailbox to show in the user's Outlook. This is undesirable for us, so we've included the parameter, but unsure if other use cases need the mailbox mapped to Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fcbd22b-e14b-fe97-7b7f-eb672e84d382
* Version Independent ID: f9a024d7-6600-4922-02b5-2c8ceeae13ab
* Content: [Add staff to Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/add-staff?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/add-staff.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/add-staff.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@FMCUSystemAdmins Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10309

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by FMCUSystemAdmins** [comment]
> 

Thank you

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @FMCUSystemAdmins Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
