### ISSUE TITLE
What license includes this feature?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#10294]
I'm looking for a comprehensive list of licenses that will enable the Attack simulation training feature. Finding that list involved clicking multiple links and scanning multiple pages before I found the information. One or no clicks and zero scanning is preferred. 

I've shared the entire experience at the bottom to help explain where the suggestions are coming from. Because my journey started on this page and then lead to another doc, which led to another doc, I have feedback for multiple docs in this ticket. Let me know if I should submit separate issues to each doc.

1) Update the service description page [Microsoft Defender for Office 365 Licensing Terms](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#licensing-terms) and make the plans that contain Microsoft Defender for Office a section that is linkable, instead of a note. Make the section easy to read by switching to bulleted lists.

    Before
    > **Note:** Office 365 E5, Microsoft 365 E5 Security, and Microsoft 365 E5 include Microsoft Defender for Office P2 licenses, and Microsoft 365 Business Premium includes Microsoft Defender for Office 365 P1 licenses.

    After
    > ### Microsoft Defender for Office Plans
    > #### Microsoft Defender for Office P1
    > * Microsoft 365 Business Premium
    > #### Microsoft Defender for Office P2
    > * Office 365 E5
    > * Microsoft 365 E5 Security (add-on)
    > * Microsoft 365 E5

2) Update the [Threat Investigation and Response capabilities](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-ti?view=o365-worldwide) "learn more" link to the section from suggestion 1.
3) Remove the license talk, you have a learn more link that takes you to the license requirements.
4) Update the [Get started using Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide) by adding something along the lines of "To learn more about license requirements..." and link to the section from suggestion 1.
5) remove the license talk, you have a learn more link that takes you to the license requirements.
6) alternatively, include all the licenses as a note and include a link to an authoritative document in case the license requirements change. I like this approach more, but it's more maintenance :).
7) Fix the TOC links on [Where to get Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide#where-to-get-microsoft-defender-for-office-365), they both goto top of the page, probably because the entry does not exist.
    > * [Microsoft Defender for Office 365 availability](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#office-365-advanced-threat-protection-atp-availability) for a list of subscriptions that include Defender for Office 365 plans.
    > * [Feature availability across Microsoft Defender for Office 365 plans](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans) for a list of features included in Plan 1 and 2.

---
# My journey

In this article, according to the sentence below, the Attack simulation training feature requires Microsoft 365 E5 or Microsoft Defender for Office 365 Plan 2. Ultimately, we need the Threat investigation and response feature included with Defender for Office 365 Plan 2. 
>If your organization has Microsoft 365 E5 or Microsoft Defender for Office 365 Plan 2, which includes [Threat Investigation and Response capabilities](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-ti?view=o365-worldwide)

License requirement:
* Microsoft 365 E5
* Microsoft Defender for Office 365 Plan 2
* _Threat investigation and response capabilities_

Not a comprehensive list, so I continue to search

Following the [Threat Investigation and Response capabilities](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-ti?view=o365-worldwide) link I find this,
>Microsoft 365 threat investigation and response capabilities are included in Microsoft Defender for Office 365 Plan 2, which is included in Enterprise E5 or as an add-on to certain subscriptions. To learn more, see [Defender for Office 365 Plan 1 and Plan 2](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide#whats-the-difference-between-microsoft-defender-for-office-365-plan-1-and-plan-2).

License requirement:
* Microsoft Defender for Office 365 Plan 2
* Enterprise E5
* _an add-on to certain subscriptions_

Not a comprehensive list, also different from the first list, the search continues!

Following the [Defender for Office 365 Plan 1 and Plan 2](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide#whats-the-difference-between-microsoft-defender-for-office-365-plan-1-and-plan-2) link I find this,
>Microsoft Defender for Office 365 is included in certain subscriptions, such as Microsoft 365 E5, Office 365 E5, Office 365 A5, and Microsoft 365 Business Premium.
>
> If your subscription doesn't include Defender for Office 365, you can get Defender for Office 365 Plan 1 or Plan 2 as an add-on to certain subscriptions. To learn more, take a look at the following resources:
> * [Microsoft Defender for Office 365 availability](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#office-365-advanced-threat-protection-atp-availability) for a list of subscriptions that include Defender for Office 365 plans.
> * [Feature availability across Microsoft Defender for Office 365 plans](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans) for a list of features included in Plan 1 and 2.
> * [Get the right Microsoft Defender for Office 365](https://products.office.com/exchange/advance-threat-protection#pmg-allup-content) to compare plans and purchase Defender for Office 365.

Nope, still trying to determine what licenses are required for attack simulation training... :)

[Microsoft Defender for Office 365 availability](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#office-365-advanced-threat-protection-atp-availability) is using the bookmark "#office-365-advanced-threat-protection-atp-availability" which does not exist and I'm taken to the top of the page.
[Feature availability across Microsoft Defender for Office 365 plans](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans) is using the bookmark of "#feature-availability-across-advanced-threat-protection-atp-plans" which also does not exist back to the top of the same page...

Okay lets look at the page, [Microsoft Defender for Office 365 Licensing Terms](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#licensing-terms) has the following **NOTE**. (Notes are probably not the most reliable source.., p.s. same page as the first two links)
>Note
> Office 365 E5, Microsoft 365 E5 Security, and Microsoft 365 E5 include Microsoft Defender for Office P2 licenses, and Microsoft 365 Business Premium includes Microsoft Defender for Office 365 P1 licenses.

License requirement:
* Office 365 E5
* Microsoft E5 Security _(add-on)_
* Microsoft 365 E5
* Microsoft Defender for Office P2

Despite being a "note" which is typically not a core piece of information the article is trying to share, this is the most comprehensive list.

The last link is a product page for Defender for Office, doesn't tell me what licenses include either version of the product so not helpful.

As a comparison, here is the article for [Exchange Online Archiving service description](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
> Cloud-based archive and in-place hold as an add-on for the following plans
> -list of plans-

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59c87455-77af-093a-6fb6-286049aad15a
* Version Independent ID: b2690e98-781d-4a27-a9bc-bd621964feb0
* Content: [Get started using Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-get-started.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Any plan that includes "Microsoft Defender for Office 365 (Plan 2)" includes attack simulation training. You can search in the following topic:

<https://learn.microsoft.com/azure/active-directory/enterprise-users/licensing-service-plan-reference>

**Comment by yogkumgit** [comment]
@jonwbstr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
