### ISSUE TITLE
Remove "Dynamic Delivery" as prefered option

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/microsoft-365-docs#1029]
"Dynamic Delivery" is no longer preferred option. Could you please remove it from this statement: "In the response section, choose the Dynamic Delivery option. (Learn more about Dynamic Delivery and previewing with ATP Safe Attachments.)"
and recommend "Block" mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be929ba-8bef-b75c-0475-041bb6ec441a
* Version Independent ID: 358f9e1a-1900-7c8c-814a-b878a9a22f9e
* Content: [Set up Office 365 ATP Safe Attachments policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello @pawp81 ,
It says "Example: To set up a policy called "no delays" that delivers everyone's messages immediately and then reattaches attachments after they're scanned, you might specify the following settings:" 

So the option is need to be set in the described scenario, it is not stated that it is a preferred option.
Thank you

**Comment by mypil** [comment]
@pawp81 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
