### ISSUE TITLE
Clear as Mud

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/microsoft-365-docs#10293]
The statement "Defender Vulnerability Management add-on Additional capabilities for Defender for Endpoint Plan 2"  in the top table.Doesn't make sense. When you click on all of the links under that section then all of those components are included in of DFE Plan 2. What is the difference? Would be good to have a simple table that has the tick and cross per component starting with DFE P2 then map out want is added when you purchase the additional SKU. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4383e31-f80e-65de-3a90-9bb53b6845d2
* Version Independent ID: d4383e31-f80e-65de-3a90-9bb53b6845d2
* Content: [Compare Microsoft Defender Vulnerability Management offerings](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
@Jlouden9 Thank you for your feedback. For the features listed in the section:  

Defender Vulnerability Management add-on
_Additional capabilities for Defender for Endpoint Plan 2_

They are only available if you install the Defender Vulnerability Management add-on on top of MDE P2. They are not in Defender for Endpoint Plan 2. 

This table focuses on Defender Vulnerability Management capabilities. 

Details on the Defender for Endpoint Plan can be found here: 
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide#compare-microsoft-endpoint-security-plans-1

I will track your feedback that table with ticks would be useful and look into it.

Thanks.
