### ISSUE TITLE
Broken link on group limitations

### ISSUE THREAD

**Issue by eketo-msft** [MicrosoftDocs/microsoft-365-docs#10291]
The link "See AAD service limits and restrictions" on https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide is broken.  The link should go to https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/directory-service-limits-restrictions.

**Comment by msbemba** [comment]
@eketo-msft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10307

Once the author approves, the changes will be live.

Thanks
Sri
