### ISSUE TITLE
Apply the above selection if malware scanning for attachments times out or error occurs. 

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/microsoft-365-docs#1030]
Description of "Apply the above selection if malware scanning for attachments times out or error occurs. " setting in ATP Safe Attachments policy is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be929ba-8bef-b75c-0475-041bb6ec441a
* Version Independent ID: 358f9e1a-1900-7c8c-814a-b878a9a22f9e
* Content: [Set up Office 365 ATP Safe Attachments policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello @pawp81,
which article does this issue related to? I do not see the mentioned option in [Set up Office 365 ATP Safe Attachments policies - Office 365](https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies)
Are you talking about [Configure your Office 365 tenant for increased security](https://docs.microsoft.com/microsoft-365/security/office-365-security/tenant-wide-setup-for-increased-security)?

Thank you

**Comment by pawp81** [comment]
In this article: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies we are not documenting "Apply the above selection if malware scanning for attachments times out or error occurs." setting which is one of the ATP Safe Attachment policy settings.

**Comment by mypil** [comment]
@pawp81 -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/7f36b6e8fd1da7dcdf1fde7caedd3fb6629520a6. 


Thank you for your contribution to make the docs better! Much appreciated!
