### ISSUE TITLE
Missing Technical Support for Partners Plan

### ISSUE THREAD

**Issue by mrbelchior** [MicrosoftDocs/microsoft-365-docs#10301]
In the "Support, help and training" tab, the technical partner support plans are missing. Where it says "Partner" below "Elevated support options" and "Additional Support Services", there should be something mentioning these. Example:

"Partners: You can select a Microsoft partner and delegate administrative functions, including creating service request tickets. For more information, see the [Partners](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/partners) service description and [Add, change, or delete a subscription advisor partner](https://learn.microsoft.com/en-us/office365/admin/misc/add-partner)."

Technical support for partners: If you're a partner and need information about specific partner support plans, see the following table. For more information, see [compare partner support plans](https://partner.microsoft.com/support/partnersupport)

-- | --
Premier Support for Partners (PSfP) | Fee-based. Use for all products.
Advanced Support for Partners (ASfP) | Fee-based. Use for cloud products only.
Signature Cloud Support | Included with Microsoft Cloud Partner Program benefits for Gold or Silver competencies.Use for cloud products only. See Technical Benefits
Product Support Incidents | Included with Microsoft Cloud Partner Program benefits for Gold, Silver, or Microsoft Action Pack partners.Use for recent, on-premises products only. See Technical Benefits

(Info from https://learn.microsoft.com/en-gb/partner-center/customer-support#escalating-to-microsoft)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 136a78ac-adc0-dcff-3d09-00b6cb5e45b4
* Version Independent ID: 136a78ac-adc0-dcff-3d09-00b6cb5e45b4
* Content: [Microsoft 365 feature descriptions - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/m365-feature-descriptions?redirectedfrom=MSDN&view=o365-worldwide&tabs=Support)
* Content Source: [microsoft-365/admin/m365-feature-descriptions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/m365-feature-descriptions.md)
* Service: **microsoft-365-business**
* GitHub Login: @pebaum
* Microsoft Alias: **office365servicedesc**

**Comment by msbemba** [comment]
@mrbelchior Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10312

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mrbelchior Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
