### ISSUE TITLE
Must clarify about roadmap 101515 (Junk/Phishing reporting actions integrated with Microsoft Defender for Office 365)

### ISSUE THREAD

**Issue by dnetoa** [MicrosoftDocs/microsoft-365-docs#10305]
Hi,

I hope docs must to clarify what is the recommendation of MSFT since now we have a Built-in button for report junk and phishing on Outlook Web. They're reporting as same way to admin and be controlled by choices of admin?

[Roadmap 101515](https://www.microsoft.com/en-us/microsoft-365/RoadmapFeatureRSS/101515)

**Comment by msbemba** [comment]
@dnetoa Thank you for your feedback. This feature that you are reporting is under development and most probably released soon. Once it is Launched and available to the general audience, the author and the PM will be able to update the documents. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dnetoa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
