### ISSUE TITLE
Incorrect statement about regulatory record?

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10303]
In the next to last paragraph, it suggests you can auto-apply retention labels for regulatory records, which I believe is un-true? The restictions around auto-label for regulatory record is clarified further below in the Important note in the blue background.

[Records](https://learn.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide#records)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Records management for documents and emails in Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide#records)
* Content Source: [microsoft-365/compliance/records-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records-management.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@kstat Yes, thanks for flagging this.  The statement is half right - you can auto-apply labels for records, but not regulatory records.  I'll make a tweak to the wording for accuracy.

**Comment by cabailey** [comment]
Fixed now, closing
