### ISSUE TITLE
Things to keep in mind

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#10318]
Maybe is it good to add a point that this applies to the OS and Server roles only, and that additional Software (like SQLServer) is not subject to Automatic exclusions - to date it was not clear to me.... (I just assumed this list was not listing _all_ Automatic exclusions and that other lists could exist for e.g. SQLServer)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1664d524-cf0b-a4d4-695a-114f5df1d33e
* Version Independent ID: 31bff983-8c0c-915c-6f88-f5a0a719987c
* Content: [Configure Microsoft Defender Antivirus exclusions on Windows Server](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andrePKI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
