### ISSUE TITLE
Security Administrator

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#1031]
Security Administrator permissions alone does not give enough permissions to implement the ATP safe Attachment / Safe Links policies:
The object 'contoso.onmicrosoft.com\Safe Attachment' must be within the read scope before and after it's modified.
Can't perform the save operation.
    + CategoryInfo          : NotSpecified: (:) [New-SafeAttachmentPolicy], ADScopeException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be929ba-8bef-b75c-0475-041bb6ec441a
* Version Independent ID: 358f9e1a-1900-7c8c-814a-b878a9a22f9e
* Content: [Set up Office 365 ATP Safe Attachments policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies?source=docs#step-1-review-the-prerequisites)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello @JeroenDronkers,
yes, you are correct. To create safe attachment policy you need to have Organization management role or Security Administrator + Hygiene Management roles.
Thank you

**Comment by JeroenDronkers** [comment]
Hello Marat,

Thanks but the article doesn’t mention that additionally to the Security Administrator role you need to add Hygiene Management roles and therefore multiple customers have opened support cases because they can’t manage ATP with the Security Administrator role.

If Hygiene Management roles need to be added then the article should mention this.


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>
[Microsoft Logo]
Backup | Alisdair Douglas (Alisdair Douglas (aldoug@microsoft.com)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

**Comment by MaratMussabekov** [comment]
Hello, I've added it in #1138

**Comment by mypil** [comment]
@JeroenDronkers - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/23adab350274d524d2ef404678e737e551789aac. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by JeroenDronkers** [comment]
Hello All,

According to the response I got from Marat the issue with the article is not understood:


Hello @JeroenDronkers<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeroenDronkers&data=02%7C01%7Cjedronke%40microsoft.com%7C1d38973f91fb4aaed90108d7a2eefa21%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637157019591747179&sdata=YA7xMGrQkF9PrCQu3VSrki7UFjyQVFYD3iom2OvfMqI%3D&reserved=0>,
yes, you are correct. To create safe attachment policy you need to have Organization management role or Security Administrator + Hygiene Management roles.
Thank you

The article mentioned only “Security Administrator” role is needed to enable or adjust ATP policies but Security Admin role doesn’t come with the additional Hygiene management roles. Hence we are receiving cases from customers not being able to create ATP policies.

The article is still incorrect as long as Security Administrator doesn’t automatically include the Hygiene management roles or as long as it doesn’t mention that these roles need to be added to the Security Admin role.



Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>
[Microsoft Logo]
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539
