### ISSUE TITLE
add info that Auto Update channel names have changed from "External" to "Preview"

### ISSUE THREAD

**Issue by mcteufelms** [MicrosoftDocs/microsoft-365-docs#10315]
[Enter feedback here]
Hello,

in our command that shows the customer how to get access to preview features of MDE we mention the channel name "External":

"defaults write com.microsoft.autoupdate2 ChannelName -string External"

However, according to this article, the channel name has been changed from "External" to "Preview" in recent versions of MS Auto-Update:

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-updates?view=o365-worldwide#set-the-channel-name

We should at least mention this in the MDE MacOS network protection set-up guidance. (i.e. that there are two possible commands depending on the version of MS Auto-Update). Got some customers being confused.

Best regards,
Michaela

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 415606ab-27e9-e125-d868-1e4636771d36
* Version Independent ID: 415606ab-27e9-e125-d868-1e4636771d36
* Content: [Use network protection to help prevent macOS connections to bad sites](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection-macos?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection-macos.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection-macos.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@mcteufelms Thank your for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10339

Once the author approves, the changes will be live.

Thanks
Sri
