### ISSUE TITLE
Remark about Automatic exclusions not clear

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#10316]
Under "Important" in the section "Recommendations for defining exclusions" it is stated  "includes many automatic exclusions based on known operating system behaviors and typical management files, such as those used in enterprise management, database management, and other enterprise scenarios and situations."
This I interpreted that not only the Windows OS and additional server roles are covered by that statement, but also things like SQLServer and perhaps Configuration Manager and so on. I assumed Microsoft knows the Microsoft products. But it seems that that is not the case, so maybe the "Important" can be made a bit clearer about this? Maybe refer to the full list of Automatic  exclusions? (I believe that is [here](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus?view=o365-worldwide))

edit: removed WSUS as I see that is a role and does have some Automatic exclusions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d5d462d-4c3a-f363-f1d7-611e3c71fbb4
* Version Independent ID: e496259f-7012-e898-12c3-88115d55d5e0
* Content: [Set up exclusions for Microsoft Defender Antivirus scans](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus?view=o365-worldwide#recommendations-for-defining-exclusions)
* Content Source: [microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@andrePKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10351

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andrePKI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
