### ISSUE TITLE
Why can't I pay by a method other than credit card?

### ISSUE THREAD

**Issue by GraemeNZ** [MicrosoftDocs/microsoft-365-docs#10326]
My credit card has been hacked and has been blocked by my bank. They are issuing me a new credit card, which may take up to 2 weeks to arrive. Coincidentally, the day that my card was blocked, was the day my 365 bill fell due. I have money to pay, I just can't use a credit card. Why can't I pay by bank deposit? It seems you don't want your money...?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14e33d-0d3e-45f4-fefe-dec3ae7d351f
* Version Independent ID: aeb53e2c-d35c-73fe-26f2-4f101bfeeea7
* Content: [Manage payment methods](https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-payment-methods?view=o365-worldwide#add-a-payment-method)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-payment-methods.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-payment-methods.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@GraemeNZ Thank you for your feedback. The availability of payment options depends on the country your tenant is hosted. I'd recommend you contact the support team via the need help section on the admin center so that our billing team can assist you with this query.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GraemeNZ Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GraemeNZ** [comment]
Hi

Actually I do see a need for a documentation change. These instructions:

 Sriraman M S Wednesday, 23 November, 1:18 am
"contact the support team via the need help section on the admin center so that our billing team can assist you with this query."

Clicking on the need help section on the admin center took me to GitHub, where you've told me to click on the help section ion the admin center ...

Regards, Graeme

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@GraemeNZ  Thank you for your feedback. 

The link to the admin center is https://admin.microsoft.com/Adminportal/Home?source=applauncher#/homepage

You can see the Help and support option in the right corner, Click on that to open a support ticket.

![image](https://user-images.githubusercontent.com/45987684/204447782-bea7ac3d-e143-4994-8544-56a482c5f14b.png)

Hope this helps!

Thanks
Sri
