### ISSUE TITLE
Incorrect Page Title

### ISSUE THREAD

**Issue by mbressman** [MicrosoftDocs/microsoft-365-docs#10325]
https://support.microsoft.com/en-us/office/set-up-an-outlook-account-in-the-ios-mail-app-b2de2161-cc1d-49ef-9ef9-81acd1c8e234

This support article is clearly about the iOS Outlook app, and yet the page title, URL link title portion, and header in the page are incorrect and this causes confusion.  I've reported this multiple times to Microsoft via support ticket and feedback on that page (over many months) and it has yet to be changed.

**Comment by denisebmsft** [comment]
Hello @mbressman and thank you for the feedback. Issues logged here are technically for content published on learn.microsoft.com, and the article in question is actually published to support.microsoft.com. No worries, though. I'm contacting the article's owner to ask them to fix it. Thank you for helping us improve our documentation by letting us know about things like this!! Have a great day!

**Comment by denisebmsft** [comment]
I wrote the article owners and asked them to look into this issue. Thanks again!
