### ISSUE TITLE
Which object types are protected by Defender for Office?

### ISSUE THREAD

**Issue by DMoenks** [MicrosoftDocs/microsoft-365-docs#10327]
In conjunction with [OfficeDocs-O365ServiceDescriptions/#764](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/764) I'm currently wondering if users actually need to be Exchange Online recipients to be protected by Defender for Office.

For example, if a user is only licensed for _Microsoft 365 Apps_ and _SharePoint Online_, but not _Exchange Online_, to solely be able to work with Office files stored on OneDrive and SharePoint, they're only a **user** in regards of Exchange, they're no **recipient**. As such, they can be neither included in nor excluded from Safe Links policies when configuring those in the browser, as the "users" lists just allow to select recipients, not users. This matches the current [documentation](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-safe-links-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-create-safe-links-policies), which only refers to "mailboxes, mail users, or mail contacts".
Interestingly, when configuring policies by using PowerShell, also users and not just recipients can be included or excluded by stating their full **UserPrincipalName**, but that doesn't necessarily mean they're protected eventually.

Although the licensing parts of documentation always speak of users, all the configuration parts almost exclusively speak of recipients, which would be two different things in the end, at least from a technical perspective.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide#safe-links-settings-for-microsoft-teams)
* Content Source: [microsoft-365/security/office-365-security/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
@DMoenks, Safe Links or Safe Attachments protection requires a Microsoft Defender for Office 365 Plan 1 or Plan 2 license.

So what exactly is the ask here for this topic?

**Comment by DMoenks** [comment]
The question is not regarding licensing for Defender for Office, as the license need for that product would rather be the topic of the other issue I linked above. The question is, if users need to be Exchange Online **recipients** to actually be protected by Defender for Office from a technical perspective or if it's sufficient if they're Exchange Online **users**.

The example I provided above (licensed for _Microsoft 365 Apps_ and _SharePoint Online_, but not for _Exchange Online_), would end up in the affected user account to be an Exchange Online **user**, not a **recipient**. So, even if that user account was licensed for _Defender for Office_ by any means, would it actually be protected by _Defender for Office_ or not?

As the documentation mentions **recipients** over and over, I would suspect the answer to be No, but I couldn't such an answer anywhere in the documentation. If the answer would be No, there might be customers having user accounts they deem protected, which aren't actually protected at all...

**Comment by chrisda** [comment]
You should open a support ticket and ask. Report back here with any improvements to the documentation (the Safe Links or Safe Attachments topics, not the Service Description).

**Comment by yogkumgit** [comment]
@DMoenks Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
