### ISSUE TITLE
Alignment of events time + correction of table reference

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/microsoft-365-docs#10329]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

In the FAQ section, the below is detailed:

Most auditing data is available within 30 minutes but it may take up to 24 hours after an event occurs for the corresponding audit log entry to be displayed in the search results. See the table in the [Before you search the audit log](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-search-the-audit-log) section of this article that shows the time it takes for events in the different services to be available.

In the before you search the audit log, the table has been removed and the below is detailed:

Microsoft doesn't guarantee a specific time after an event occurs for the corresponding audit record to be returned in the results of an audit log search. **For core services (such as Exchange, SharePoint, OneDrive, and Teams), audit record availability is typically 60 to 90 minutes after an event occurs**. For other services, audit record availability may be longer. However, some issues that are unavoidable (such as a server outage) may occur outside of the audit service that delays the availability of audit records. For this reason, Microsoft doesn't commit to a specific time.

2 issues here:

1. Either auditing data is available within 30 minutes, either between 60-90 minutes and this should be aligned in the two paragraphs.
2. In the FAQ section, we're referencing and old table which was removed, instead we should only write:

 See the [Before you search the audit log](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-search-the-audit-log) section of this article that shows the time it takes for events in the different services to be available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://review.learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide&branch=main#before-you-search-the-audit-log)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@asdcristi Closing it as per author's comment in PR. Thanks
