### ISSUE TITLE
Typo in screenshots

### ISSUE THREAD

**Issue by klennan** [MicrosoftDocs/microsoft-365-docs#1032]
"Reveiw set 1" is the set title in the screenshots in this page. I believe the intention was "Review set 1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2a0e3d-d36e-7559-c3f7-66b5c24dc811
* Version Independent ID: 605cc901-1def-ade1-ce0d-5e970caa148c
* Content: [Query the data in a review set - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/review-set-search)
* Content Source: [microsoft-365/compliance/review-set-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/review-set-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@klennan Thanks for the heads up.
