### ISSUE TITLE
Wrong wait time for user remove

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/microsoft-365-docs#10323]
The wait time needs to be changed from 1 hour to 24 hours.  One user has waited over 6 hours now.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c17e50d-aa8f-bd30-66af-ef4d63f02402
* Version Independent ID: 92cbda3f-c3a9-ed20-2038-7e966f491934
* Content: [Remove blocked users from the Restricted users portal - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@fixx-er Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10340

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fixx-er Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by puneethmeister** [comment]
@chrisda This needs to be changed to 1 hour. It's not 24 hours. Sometimes due some technical issues user might be blocked for more than 1 hour but in most cases the user will be unblocked in 1 hour

**Comment by fixx-er** [comment]
I have had many customers complain waiting 6+ hours.  Many partners are describing to customers a 24 hour wait.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by puneethmeister** [comment]
Can you share the customer details, NDRs for investigation or ask the customer to raise a support ticket with the details? This will help us figure out any bugs in the system. Thanks

**Comment by fixx-er** [comment]
Yes, next time this occurs. There are no active cases now to my knowledge.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
