### ISSUE TITLE
Supported group types not documented

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/microsoft-365-docs#10328]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

In the Target Users section, the below is specified however there is no description of which groups we're accepting:

"Include only specific users and groups: Choose one of the following options:

Add users icon. Add users: In the Add users flyout that appears, you can find users and groups based on the following criteria:

Search for users or groups: In box, you can type part of the Name or Email address of the user or group and then press Enter. You can select some or all of the results. When you're finished, click Add x users."

As confirmed by PG, Dynamic Distribution Groups cannot be used in this case. We would need to either:

1. Detail that only groups found in Azure AD can be used, or
2. Detail which are the compatible ones, or
3. Detail which ones are not compatible

Thank you,
Cristian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c312fd69-72cd-bc86-4fe1-993b60b97bc6
* Version Independent ID: b7887ba6-4775-39f0-e368-68f140ce233d
* Content: [Simulate a phishing attack with Attack simulation training - Office 365](https://review.learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@asdcristi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10341

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chrisda** [comment]
Related pull request merged, so closing issue.

Thanks for the feedback.
