### ISSUE TITLE
Update Docs with new Intune Endpoint Security > Attack Surface Reduction > Device Control UX

### ISSUE THREAD

**Issue by davi-cruz** [MicrosoftDocs/microsoft-365-docs#10321]
I have noticed that Device Control UI has changed recently in Intune, to include settings described in this article which is great!
An update of this article, keeping this for customers that eventually might use a third-party MDM provider would be beneficial, simplifying their journey on Device Control while using Microsoft Defender for Endpoint.

Associated resources to this change like [Reusable Settings](https://learn.microsoft.com/en-us/mem/intune/protect/reusable-settings-groups) refers to this article, which may cause confusion during testing or adoption.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19b5fda8-c875-aac3-385d-43c88feed731
* Version Independent ID: 19b5fda8-c875-aac3-385d-43c88feed731
* Content: [Deploy and manage Removable Storage Access Control using Intune](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by omahivade** [comment]
Mene payment Kiya 550 fir bhi app open nahi huaa

**Comment by msbemba** [comment]
@davi-cruz Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10350

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @davi-cruz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ittp1337** [comment]
Is it possible to update the screenshots reflecting the actual cases ? :)
Would be very helpfull, in my option its a bit confusing...
