### ISSUE TITLE
Worst 2015 passwords broken link

### ISSUE THREAD

**Issue by phenixita** [MicrosoftDocs/microsoft-365-docs#10330]
Hi team,
at the bottom of the page the link to the 2015 worst passwords [is broken](https://go.microsoft.com/fwlink/p/?linkid=861020)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@phenixita Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10342

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @phenixita Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
