### ISSUE TITLE
Menu options have changed

### ISSUE THREAD

**Issue by dabutlermsft** [MicrosoftDocs/microsoft-365-docs#1033]
The menu options & doc locations have changed - this page needs to be updated to reflect the current design of the Service Trust Portal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a6cff6-f960-bab8-10b0-731d1e78e8ec
* Version Independent ID: a60eb908-022a-4d90-23a4-b4e765f232e9
* Content: [Get started with the Microsoft Service Trust Portal - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-service-trust-portal#feedback)
* Content Source: [microsoft-365/compliance/get-started-with-service-trust-portal.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-with-service-trust-portal.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@dabutlermsft Thanks for the heads up. You could also submit a pull request with these fixes.

**Comment by markjjo** [comment]
@dabutlermsft Heads up that I have updated this topic as per your feedback. The latest version will be on the live site later this afternoon.
