### ISSUE TITLE
Behavior of edit new menu function is different from what is documented

### ISSUE THREAD

**Issue by RobAaldijk** [MicrosoftDocs/microsoft-365-docs#10338]
If I open the Edit new menu function, The edit published or draft template menu is not displayed, instead, if I choose Edit from the context menu on a template, the contenttype associated with the template is displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d958029d-52d6-41e7-9054-9500f2e02e48
* Version Independent ID: d958029d-52d6-41e7-9054-9500f2e02e48
* Content: [Edit a modern template in Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/contentunderstanding/content-assembly-edit-template)
* Content Source: [microsoft-365/contentunderstanding/content-assembly-edit-template.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/content-assembly-edit-template.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@chuckedmonson Please help us in resolving this issue, Thanks

**Comment by chuckedmonson** [comment]
Hello, @anrasto -- Can you please advise what needs to be changed in the "Edit a modern template" to address the customer's issue? Thank you.

**Comment by chuckedmonson** [comment]
In progress.

**Comment by chuckedmonson** [comment]
@RobAaldijk-- Our apologies, we're having a hard time replicating your issue. Would you mind providing more information around specifically what you are describing please? Thank you.

**Comment by RobAaldijk** [comment]
I am currently trying to replicate it in a different environment – once that has happened will have a ticket created with support and also share with you an extensive report. Meanwhile, it is still showing this behavior in our current tenant – initially, templates are created but after a page refresh they disappear from the menu. I can still see them created as hidden templates in the site (see screenshot attached), but they can no longer be accessed. At creation time, also the attached error is shown.

**Comment by yogkumgit** [comment]
@chuckedmonson

**Comment by chuckedmonson** [comment]
@RobAaldijk-- Thank you for the follow up, appreciate it.

**Comment by RobAaldijk** [comment]
Thanks for your patience 😊
