### ISSUE TITLE
Missing video link

### ISSUE THREAD

**Issue by khbafl** [MicrosoftDocs/microsoft-365-docs#10337]
This documentation page mentions a video without including the link : 

"This article and the deployment video use Azure as the deployment destination for the DKE service. If you're deploying to another location, you'll need to provide your own values."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@khbafl Thank you for your feedback. We have added the video link to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10401

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@khbafl Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
