### ISSUE TITLE
 Forwarded message Option in Threat explorer 

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/microsoft-365-docs#10344]
Under the Threat explorer -> Advanced filter, we have an option "Forwarded Message" .There are many queries from  customer on what type of forwarding information can be seen there. Hence need to include the below information to provide more clarity.

The "Forwarded message" Option in Threat explorer covers only external forwarding on below scenarios..                                                                                                                                             

1) Mailbox forwarding via "Forwardingaddress" to external address
2) Mailbox forwarding via "ForwardingSMTPAddress" to External address
3) Inbox rule  forwarding To External address
4) Transport rule redirection (redirect message to) to External address

 The ones it doesn't cover.

1) Any forwarding to internal address or to Onpremise mailbox
2) Mail user forwarding to external address
3) Manual forwarding from Mailbox
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89aaa2af-ba47-4e6f-60f3-1b0b95df35f9
* Version Independent ID: 8495bb4c-045a-5085-64d9-1b9ae788cfdb
* Content: [Views in Threat Explorer and real-time detections - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer-views?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer-views.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer-views.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help.

**Comment by Ratulch** [comment]
Looking into this.

**Comment by Ratulch** [comment]
This is the answer I received -- "The “Forwarded message” filter gives results if there is any email sent/received as part of SMTP email forwarding rule configuration. Manual email forwards are not listed as part of this filter. Also, the advanced filter option is going to be deprecated soon with the new version of Threat Explorer."

@MithunRathinam Does that answer your question?

**Comment by yogkumgit** [comment]
@MithunRathinam Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
