### ISSUE TITLE
Case Action - Turn off pseudonymize

### ISSUE THREAD

**Issue by paulohanlon** [MicrosoftDocs/microsoft-365-docs#10359]
Under Case Actions there's no mention of the option to "Manage pseudonymize" which gives IRM Investigators the ability to turn off for the case, if enabled at the tenant level.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44c1982d-931d-e5d9-6f54-8b63050932d5
* Version Independent ID: 30c21178-f013-4649-59ae-4b9f75e13ccc
* Content: [Insider risk management cases - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-cases?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@paulohanlon Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10408

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@paulohanlon Closing it as per author's comment in PR. Thanks
