### ISSUE TITLE
Missing details related to Web Protection

### ISSUE THREAD

**Issue by MasterBlaster4** [MicrosoftDocs/microsoft-365-docs#10355]
There is an undocumented but relevant difference on Web Protection behavior between supervised vs. unsupervised devices that should be on the public documentation:

1.	On Supervised devices with the configuration profile (control filter profile), Defender can access the full URL. If the full URL is phishing, then it will be blocked.
2.	On an Unsupervised device, Defender has access to the domain name only, and if the domain is not a phishing URL it won't be blocked. Refer Safari browser unsupervised column. All the domain names in the SmartScreen demo URLs are not phishing. Eg: [https://nav.smartscreen.msft.net/phishingdemo.html](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnav.smartscreen.msft.net%2Fphishingdemo.html&data=05%7C01%7Cgoliveira%40microsoft.com%7C8c9b7c8e57db4211540e08dab7071b96%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638023538526631888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8w4Ih3lX42AqljqThqPkrB5QOt8ZXp1tz16ikyoRBhU%3D&reserved=0) Full URL is phishing, but the domain name is not phishing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28f5c122-c802-18db-caa3-1aa12f3670ac
* Version Independent ID: 7ba4e9f5-37aa-9842-c6b1-ee41afc892e1
* Content: [Microsoft Defender for Endpoint on iOS](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-ios?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-ios.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-ios.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MasterBlaster4 Thank you for your feedback. We have a different document that details about web protection and I have added this information to it - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-configure-features

This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10407

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MasterBlaster4 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
