### ISSUE TITLE
Spelling  or Grammar Error ...took "effect" not "a fact"

### ISSUE THREAD

**Issue by Redbaron13** [MicrosoftDocs/microsoft-365-docs#10356]
Add your Google Workspace domain to Microsoft 365
Article
10/26/2022
2 minutes to read 

...6. Open the record type drop-down, choose TXT, paste the TXT value you copied then select Add. The update usually takes **~~a fact~~**`effect` within a few minutes but may take up to 48 hours.
7. Return to the admin center, select Verify,and then Close.

**Comment by yogkumgit** [comment]
@Redbaron13 Please indicate which document you are referring to. Thanks

**Comment by deFRAGerNZ** [comment]
@yogkumgit  answering for @Redbaron13 - Probably this one: https://learn.microsoft.com/en-us/microsoft-365/admin/moveto-microsoft-365/add-google-domain?view=o365-worldwide

**Comment by msbemba** [comment]
@deFRAGerNZ and @Redbaron13  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10402

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by Redbaron13** [comment]
@msbemba you're welcome. @deFRAGerNZ  @yogkumgit thanks for the help  @denisebmsft - Thank you all for the help in updating this webpage.

All, I must admit this was my first time using GitHub, so I apologize if I did not reference the specific webpage or proposed my change correctly. I still learning. - Any advice on what I should do next time to improve my proposed correction/change in the future or just general GitHub etiquette is always welcome and appreciated.

Thanks again, 

Kevin    / /
        |___|

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Redbaron13 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
