### ISSUE TITLE
Definition of "Conflict" is not clear

### ISSUE THREAD

**Issue by Interface007** [MicrosoftDocs/microsoft-365-docs#10357]
The documentation here is "When two or more policies have conflicting settings, the conflicting settings are not added to the combined policy, while settings that don't conflict are added to the superset policy that applies to a device.". To me it's not clear whether two settings with the same effect are a conflict.
Example:
Policy 1: Attack surface reduction policies "Block all Office applications from creating child processes = Block"
Policy 2: Devices | Configuration profiles "Office apps launching child processes = Block"

Both settings should have the exact same effect: blocking Office applications from creating child processes. Is it seen as a conflict if both settings are applied through two policies that target the same user and machine?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@Interface007 Thank you for your feedback. Great question, If both the policies are set to block then it would not become a conflict. However  below settings will be a conflict

Policy 1: Attack surface reduction policies "Block all Office applications from creating child processes = Allow"
Policy 2: Devices | Configuration profiles "Office apps launching child processes = Block"

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.
