### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by PMLIO** [MicrosoftDocs/microsoft-365-docs#10358]
Hi, the Printer, Removable Storage and Network share groups are missing in my EndPoint DLP Settings (M365 E5). Are these preview features where we need to opt-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f25ec8-d5a8-4a9d-ca72-bd61eacd9dbc
* Version Independent ID: 34f25ec8-d5a8-4a9d-ca72-bd61eacd9dbc
* Content: [Configure endpoint DLP settings - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-configure-endpoint-settings?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-configure-endpoint-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-configure-endpoint-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@PMLIO Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
