### ISSUE TITLE
Contrdicting information

### ISSUE THREAD

**Issue by terryhugill** [MicrosoftDocs/microsoft-365-docs#10368]
These contradictory statements are in this document. If the differences are for different policy types, this could be made clearer. 

![image](https://user-images.githubusercontent.com/24670663/203828812-bd08eae0-1672-4e12-ab38-fdef50064eeb.png)

![image](https://user-images.githubusercontent.com/24670663/203828912-28a8aa72-2fb0-4774-98a9-6504c286b9b4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18f9ed93-1f7c-c9d9-2c2f-494b46cc5757
* Version Independent ID: 3c954243-4c6d-3791-bf42-be61e88eac7f
* Content: [Create and manage communication compliance policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@terryhugill Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10403

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by terryhugill** [comment]
Thank you.

**Comment by yogkumgit** [comment]
@terryhugill Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
