### ISSUE TITLE
Add "Don't exclude the URL *.blob.core.windows.net from any kind of network inspection"

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#10369]
This page is recommending to customers that they should exclude from HTTPS inspection all of the FQDNs in the spreadsheet. That spreadsheet includes entries with *.blob.core.windows.net, which is Azure Blob Storage. 

It's a bad idea to exclude Azure Blob Storage from network inspection. Attackers have in the past used Azure Blob Storage to host malware. This has been an effective tactic because some organizations have over-broad exceptions from network inspection for Microsoft-hosted sites.

Another Microsoft Docs Defender page (linked below) includes a specific recommendation to **not** exclude *.blob.core.windows.net from HTTPS inspection. No reason is given on that page, but I the contributors to that page probably recognized that doing so would present an unnecessary security risk.

The advice on that page is: "Don't exclude the URL *.blob.core.windows.net from any kind of network inspection."
This is the link: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus?view=o365-worldwide#allow-connections-to-the-microsoft-defender-antivirus-cloud-service

That advice should be replicated on this page. Customers should not be excluding Azure Blob Storage from https inspection.

Example of a past attack where an attacker used Azure Blob Storage to host malware:
https://www.bleepingcomputer.com/news/security/phishing-attack-uses-azure-blob-storage-to-impersonate-microsoft/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide#enable-access-to-microsoft-defender-for-endpoint-service-urls-in-the-proxy-server)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@robmacf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10404

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @robmacf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
