### ISSUE TITLE
List All Policy Indicators

### ISSUE THREAD

**Issue by paulohanlon** [MicrosoftDocs/microsoft-365-docs#10360]
Customers often ask for a list of all available policy indicators. Today the only way to see this list is to open the IRM Settings within the portal. We should document the full list either on this page or another which is linked to from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Insider risk management settings - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@paulohanlon - thanks for the feedback. As an internal MS contact, I'll send you an internal email with the link to the content request form so you can submit this request there. Submitting internally is easier for me and the PG team to review, confirm, and approve.
