### ISSUE TITLE
Removal or migration of page into existing configure-server-endpoints.md

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/microsoft-365-docs#10365]
The majority of the info on this page is a repetition of the information on the page configure-server-endpoints.md (titled "Onboard Windows servers to the Microsoft Defender for Endpoint service").
It seems it would be better to migrate the little content that's unique on this page, into the above mentioned, to simplify the content. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Version Independent ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Content: [Defender for Endpoint onboarding Windows Server](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-server?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-server.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
Hi @baardhermansen and @yogkumgit 

As there is a plan to refresh the onboarding content in the near future this is really helpful information. 

I will make sure this included as part of the documentation refresh.

Thanks,
Sinead

**Comment by yogkumgit** [comment]
@siosulli Thank you very much for sharing this information. @baardhermansen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
