### ISSUE TITLE
Bad idea to hide support inside something that could be the problem.

### ISSUE THREAD

**Issue by jsclary** [MicrosoftDocs/microsoft-365-docs#10375]
[Enter feedback here]
If you are having technical issues with Microsoft 365, logging in to the admin console may be part of the problem so putting the support options there is a terrible idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Version Independent ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Content: [Get support - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&culture=en-us&country=us)
* Content Source: [microsoft-365/admin/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-support.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@jsclary Thank you for your feedback. The option to create a support ticket via the need help section is one of the ways to contact  Microsoft support and users can always use the other support option if they have trouble getting into the admin center. 
It is not always that a technical issue stops admins from accessing the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jsclary Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
