### ISSUE TITLE
The table does not make sense under roles and permissions

### ISSUE THREAD

**Issue by yepitsausername** [MicrosoftDocs/microsoft-365-docs#10370]
You have 4 columns advising "One of the following roles are required... " for each defender. But it is not clear what each row references to. 

![image](https://user-images.githubusercontent.com/119018808/203877139-7eeaa8c8-8801-41fe-86e0-25ee8e37113b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6a41905-15a0-c141-4465-a7cd344be59b
* Version Independent ID: 10c9daa9-c186-b2bf-1e8e-8d76b88cc7fb
* Content: [Custom roles for role-based access control](https://learn.microsoft.com/en-us/microsoft-365/security/defender/custom-roles?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/custom-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/custom-roles.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@yepitsausername Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10406

Once the author approves, the changes will be live.

Thanks
Sri
