### ISSUE TITLE
Invalid values in field

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/microsoft-365-docs#10384]
Hi,

This document describes the "action" field as an enum with values:

`The action that will be taken if the indicator will be discovered in the organization. Possible values are: "Alert", "AlertAndBlock", and "Allowed"`

AlertAndBlock is not valid, if you try to use it you will get this error:

`Failed to parse CSV file. Invalid line: 2, Reason: Error in parsing field Action, value: AlertAndBlock. Possible values: Allowed,Audit,BlockAndRemediate,Warn,Block`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f03d3a25-4ee0-0c3a-4fde-c6f9ef7a3773
* Version Independent ID: b08640a7-7e66-2653-bf3f-727fbb90709d
* Content: [Manage indicators](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-manage?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/indicator-manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/indicator-manage.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@technion Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10405

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @technion Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
