### ISSUE TITLE
Minor grammar check

### ISSUE THREAD

**Issue by binUmmer** [MicrosoftDocs/microsoft-365-docs#10386]
[Enter feedback here]
I think the notes sections on top needs a minor update

Trusted ARC sealers is an admin-created list of intermediary domains who have implemented ARC sealing. When an email is routed to Office 365 through and ARC trusted intermediary of the Office 365 tenant, Microsoft validates the ARC signature, and, based on the ARC results, can honor authentication details provided.

it should be according to me, "through an ARC trusted intermediary..." not "through and..."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36f9293f-c337-7af6-e994-336531d62f35
* Version Independent ID: 36f9293f-c337-7af6-e994-336531d62f35
* Content: [Use Trusted ARC senders for legitimate devices and services between the sender and receiver - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@binUmmer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10434

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @binUmmer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
