### ISSUE TITLE
Global Quarantine notification settings documentation outdated

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/microsoft-365-docs#10388]
Hello,

the documentation for the Quarantine notification settings is outdated.
There are two new settings which are not documented here yet:
"Specify sender address" 
and "Subject".
Could you please update your documentation to keep up with the product?
best regards
joerg

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faf5c5df-c3ab-8448-aef0-af05977db9b9
* Version Independent ID: adade895-f42b-1029-9948-5ddb5b038257
* Content: [Quarantine policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. Fixed. Updates should be visible ~11:00AM M 11/28 PST (GMT-7)

**Comment by joergrenn** [comment]
> Use Specify sender address to select an existing recipient to use as the sender of quarantine notifications. This sender email address does not need to be unique for each language.

I don't think that's correct. Could you ask engineering to provide the correct information and confirm?
I think it just needs to be an address from an organization domain. A mailbox does not need to exist for that address.
Also I think the email address cannot be different for different languages, i can only be one sender for all.

**Comment by chrisda** [comment]
It does need to be an existing recipient (I never said 'mailbox'), but it appears to prefer mailboxes. Mail contacts, distribution groups, dynamic distribution groups, mail-enabled security groups, or Microsoft 365 Groups are not available in the pick list. Mail users, room mailboxes, and equipment mailboxes are available in the pick list

Apparently, you can *select* a different sender for each language, but you're correct in that only the last sender selected is used for any/all languages.

I'll clarify the point about 'same sender for all languages'.
