### ISSUE TITLE
Explorer does not exist

### ISSUE THREAD

**Issue by unknowndpi** [MicrosoftDocs/microsoft-365-docs#10387]
https://learn.microsoft.com/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365

Discusses links to 'Explorer' which no longer exist

**Comment by unknowndpi** [comment]
Not only does 'Explorer' not exist (probably now called Real-Time detections), none of the remediation options are available as per the screenshots/documentation.

**Comment by msbemba** [comment]
@unknowndpi  Thank you for your feedback. I was able to test in a couple of tenants and the explorer feature is still available

![image](https://user-images.githubusercontent.com/45987684/205575028-1643a184-0dab-4c8b-8b77-0826bb921902.png)

If you  are still not able to find the feature, I'd request you to contact support via the help and support option in the admin center.
Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @unknowndpi Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
