### ISSUE TITLE
Text page points to himself

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/microsoft-365-docs#10382]
the paragraph:
"This capability is similar to [advanced hunting in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-overview) and supports queries that check a broader data set coming from"
point to himself page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39e09aba-ad5e-3d3d-5838-5db2390d8ecf
* Version Independent ID: 0bd43dda-c3f7-8502-0b61-ee61118fa762
* Content: [Overview - Advanced hunting](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-overview.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
Addressed in this PR. Thank you so much for the catch. https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/17767

**Comment by yogkumgit** [comment]
@schmurky PR link does not work. Kindly check.

**Comment by schmurky** [comment]
The PR has been published, public doc now reflects the change: https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-overview?view=o365-worldwide

![image](https://user-images.githubusercontent.com/66350491/204517506-16cef1d2-e786-489e-b88a-fe4f0dccba59.png)
