### ISSUE TITLE
TrackUserClicks Incorrect

### ISSUE THREAD

**Issue by deFRAGerNZ** [MicrosoftDocs/microsoft-365-docs#10385]
Command for tracking user clicks in the documentation is incorrect - Documentation is 'TrackUserClicks', while command in New/Set/Get-SafeLinksPolicy is 'TrackClicks', without the 'User'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Fixed.

Thanks for the feedback.

Closing
