### ISSUE TITLE
Where are the tables?

### ISSUE THREAD

**Issue by groove200** [MicrosoftDocs/microsoft-365-docs#10389]
No tables or error codes listed ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 102c5c34-0c04-cc14-8e9c-74ff42e1fdc2
* Version Independent ID: 6a06016e-6ac1-ab00-5a33-1d1226e2e45d
* Content: [Microsoft Defender Antivirus event IDs and error codes](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide#windows-defender-av-ids)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hi @groove200. Are you not seeing information like this in the article?

![image](https://user-images.githubusercontent.com/18405051/204357475-687f0a1a-084f-4b4d-9d1f-3600baa8d37d.png)

I'm seeing all the content rendering correctly. Can you check again?

**Comment by yogkumgit** [comment]
@denisebmsft Thank you very much for the contribution and sharing this explanation. @groove200 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
