### ISSUE TITLE
MS Bookings: I’d like to customize the Subject Line in Confirmation Email

### ISSUE THREAD

**Issue by Franky-74** [MicrosoftDocs/microsoft-365-docs#10381]
Is it possible to customize the automated email that is sent when a booking is made online? I see that I can add text to the email that is generated but I need to remove the CONFIRMED part as our appointments must be accepted before they are truly confirmed. I would like to make it more like "Your Appointment Request has Been Submitted"?

**Comment by msbemba** [comment]
@Franky-74 Thank you for your feedback. This sounds like a technical question and needs to be routed to our Microsoft support team. You can create a support ticket via the help and support option on the Admin center so that a support engineer will be able to assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Franky-74 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
