### ISSUE TITLE
Check if user has an archive mailbox

### ISSUE THREAD

**Issue by ElfNeedsFood** [MicrosoftDocs/microsoft-365-docs#10395]
[Enter feedback here]
Section on "if user is not on legal hold", the first check should be if the user has an archive mailbox.

Also, the solution to use New-ComplianceSearchAction is unfeasible since that command is limited to removing 10 messages per run and anyone in this situation is going to have too many messages to purge for that to be viable.  Either fix New-ComplianceSearchAction to allow an override or come up with a better answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e391a3b9-fc52-bedf-353a-3564752240dd
* Version Independent ID: 89376ace-9c00-7c45-3771-a9a913f81bed
* Content: [Search for and delete email messages in your organization - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@ElfNeedsFood Thank you for your feedback. Earlier, we had the feature to search-mailbox and delete more than 10 messages per run, however, with the New-ComplianceSearchAction it is not feasible. I'd recommend you raise this feedback directly on our main feedback portal (https://feedbackportal.microsoft.com/ ) so that the product or dev team and provide you with an update.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@ElfNeedsFood Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
