### ISSUE TITLE
Wording in article - supported OS's.

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#10393]
In the section entitled "what is controlled folder access?" - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide#what-is-controlled-folder-access

the text states

"Supported on Windows Server 2019, Windows Server 2022, Windows 10, and Windows 11 clients"

In the "Why controlled folder access is important" section - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide#why-controlled-folder-access-is-important

the text states

"Controlled folder access is supported on the following versions of Windows:

Windows 10, version 1709 and later
Windows 11
Windows 2012 R2
Windows 2016
Windows Server 2019
Windows Server 2022"

Either the text in the first section I mentioned needs amending to add support for 2012 R2 and Server 2016, or the second section I mentioned needs amending to remove 2012 R2 and Server 2016 if they are not supported.

Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14fb0d02-ceff-61d8-3041-13df9513769a
* Version Independent ID: 7c98a316-de58-520a-a6ad-06ddaf0d71b3
* Content: [Protect important folders from ransomware from encrypting your files with controlled folder access](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/controlled-folders.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@pjrcdf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10435

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pjrcdf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
