### ISSUE TITLE
Possible typo in the article

### ISSUE THREAD

**Issue by MatiLag** [MicrosoftDocs/microsoft-365-docs#10419]
[Enter feedback here]
At the end of the article under Auto-expanding archiving and other compliance features->Import service
It says: "Import service: You can use the Office 365 Import service to import PST files to a user's auto-expanded archive. You can import up to 100 GB of data from PST files to the user's archive mailbox"

I believe the right sentence should be:
"Import service: You **can't** use the Office 365 Import service to import PST files to a user's auto-expanded archive. You can import up to 100 GB of data from PST files to the user's archive mailbox"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54a21b69-2f7c-d54d-d8a1-5512b810b4bf
* Version Independent ID: 19126a83-c4af-bd0c-6a20-76e27db675c9
* Content: [Learn about auto-expanding archiving - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/autoexpanding-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/autoexpanding-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by MatiLag** [comment]
Hello @msbemba. Thank you for replying, however I don't believe this is correct. This because the import allows you to import only to primary archive mailbox 
https://learn.microsoft.com/en-us/microsoft-365/troubleshoot/pst-import-service/issues-with-pst-import-job#import-job-fails-with-mapiexceptionshutoffquotaexceeded-error

![image](https://user-images.githubusercontent.com/113982925/205478961-ce6d1892-4ca2-40c2-a88e-1dccd3e07b21.png)

**Comment by msbemba** [comment]
@MatiLag  Thank you for the reference. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10452

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by cabailey** [comment]
@msbemba  What leads you to believe that this page is incorrect rather than the troubleshooting page?   Have you checked this with engineering?  The troubleshooting page refers to "Overview of unlimited archiving" - which is an old name for this feature (and doesn't reflect the current page tile) that's now officially called "auto-expanding archiving".

**Comment by msbemba** [comment]
@cabailey Sorry about that.  I'm still confused about whether PST import is possible on a mailbox with auto-expanding archiving enabled. If it is, then there are no changes needed in the document.

Thanks
Sri

**Comment by cabailey** [comment]
@msbemba Please don't open PRs to change support statements without confirmation from an authoritative source.

I work with the engineering team that owns archiving and auto-expansion for mailboxes, but not the engineering team that owns the PST import service.  My understanding is that import is possible with limited support after an archive mailbox has been enabled for auto-expansion.  The import service doesn't understand the auxiliary storage that gets automatically created, and which happens after 100 GB - hence the statement "You can use the Office 365 Import service to import PST files to a user's auto-expanded archive. You can import up to 100 GB".  However, I believe there are some corner cases where auxiliary storage can be created before 100 GB, and then import will fail.  I don't have confirmation from the engineering team that owns the import service that these exceptions occur frequently enough to change the existing support statement.  In their docs (https://learn.microsoft.com/microsoft-365/compliance/importing-pst-files-to-office-365#why-import-email-data-to-microsoft-365) they specifically reference auto-expanding archiving so I take that to mean the feature is supported in some fashion.

When I asked a support engineer about the contradicting statement in the troubleshooting article ("the auto-expansion feature doesn't support PST import"), her interpretation was that it meant when the mailbox was in the process of auto-expanding (which will happen after importing 100 GB), import isn't supported/won't work.  If that's the case, I think it was written backwards and should more accurately be "the PST import feature doesn't support the auto-expansion process". But I'm not convinced most people would see the subtle difference between that statement and import isn't supported after auto-expansion is enabled.

The dependency here is on the import service, not the auto-expanding archive feature. The engineering team that owns the import service should own the support statement so I'm removing it from this page for it be documented with the PST import documentation.  I've flagged this to the relevant writer but feel free to open a GitHub Issue on their page, asking to clarify their support after an archive mailbox has been enabled for auto-expansion. Or, you can open a support ticket to be directed to the relevant team to get an authoritative answer.
