### ISSUE TITLE
This helped me diagnose an immediate problem

### ISSUE THREAD

**Issue by Velochic** [MicrosoftDocs/microsoft-365-docs#10423]
Regarding how OneDrive is managed, and how much space it should be taking up within an enterprise user's account. 
Short version - if you have multiple users on one computer, all using OneDrive for all their files, local storage is consumed very, very quickly!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9ad983-1df9-1123-222b-5c867894ff21
* Version Independent ID: 3e9ad983-1df9-1123-222b-5c867894ff21
* Content: [Move your files to OneDrive - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/files-to-onedrive?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/files-to-onedrive.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/files-to-onedrive.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@Velochic Thank you for your feedback. We have added it as a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10453

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Velochic Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
