### ISSUE TITLE
What's new

### ISSUE THREAD

**Issue by kgoldman** [MicrosoftDocs/microsoft-365-docs#10420]
The title is 'what's new', but it just has a set of version numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38276f58-2d15-9f05-cd4a-87646ec11b27
* Version Independent ID: 12f1b3df-123f-7005-9f68-38ab20df09cd
* Content: [What's new in Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-whatsnew?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-whatsnew.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-whatsnew.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@kgoldman Thank you for your feedback. Once you expand the version number, information on what's new will be available.

![image](https://user-images.githubusercontent.com/45987684/205298188-c1c2ea33-041d-4abc-a028-5bf0363171b3.png)

Hope this helps!

Thanks
Sri
