### ISSUE TITLE
Issues on https://learn.microsoft.com/en-us/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold

### ISSUE THREAD

**Issue by TadaoMachida** [MicrosoftDocs/microsoft-365-docs#10431]
In the topic https://learn.microsoft.com/en-us/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold
Tip section under Step 1: Create a custom retention tag for the Recoverable Items folder has 2 issues.

1. The link "Change the deleted item retention period for a mailbox in Exchange Online" is broken, it jumps to the top page of www.microsoft.com
2.  'defined by the AgeLimitForRetention parameter' is probably not accurate, parameter could be 'RetainDeletedItemsFor' instead of 'AgeLimitForRetension'. Please verify and update.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2e247ee-12d5-add4-756c-b8a8d4ebb7a3
* Version Independent ID: 889ce47a-58f5-7bc1-2343-64dcd4bdac2a
* Content: [Increase the Recoverable Items quota for mailboxes on hold - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@TadaoMachida Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10473

Once the author approves, the changes will be live.

For 2. the Statement seems to be accurate, MS recommends that the AgeLimitForRetention value matches the value set for RetainDeletedItemsFor parameter of the mailbox.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@TadaoMachida Closing it as per author's comment in PR. Thanks
