### ISSUE TITLE
MOERA domain limit five in Microsoft 365 docs - 30 in Azure Portal

### ISSUE THREAD

**Issue by NestoriSyynimaa** [MicrosoftDocs/microsoft-365-docs#10433]
[Add and replace your onmicrosoft.com fallback domain in Microsoft 365](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/7a37ad4efaceab76a1d1fa21981a303ab2c0c9bf/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain.md) documentation states: 
*You are limited a total of five onmicrosoft.com domains in your Microsoft 365 environment. Once they are added, they cannot be removed.*

However, when adding a new MOERA domain in [Azure AD Portal](https://aad.portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/Domains) it says: 
*This domain can't be removed after it's added. Make sure the spelling is correct before you add the domain, as you can only have 30 total onmicrosoft.com domains.*

I was able to add more than five MOERA domains via Azure Portal, but Microsoft 365 admin center only allows adding five. However, I can change the fallback (i.e. "active" MOERA) domain normally in Microsoft 365 admin center regardless of the number of MOERA domains.

**Comment by msbemba** [comment]
@NestoriSyynimaa Thank you for your feedback. I shall test this and update the document if need be.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@NestoriSyynimaa I have checked with the author and engineering team on this one. The limit on the M365 portal is 5 and on the Azure AD portal is 30. There was a similar issue(https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10480#issuecomment-1357607908) raised a few days back and the author has passed on the feedback to the Product group.

CC : @efrene 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @NestoriSyynimaa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
