### ISSUE TITLE
Inconsistency in the text

### ISSUE THREAD

**Issue by KvR1991** [MicrosoftDocs/microsoft-365-docs#10432]
The link provided on the page (this one https://www.microsoft.com/research/wp-content/uploads/2016/06/Microsoft_Password_Guidance-1.pdf) is not in par with the text on this page (minimum length 14 char).
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@KvR1991 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10474

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@KvR1991 I have received an update from the author. According to the security PMs, I’ve been working with the new guidance is 14-character length. 

Hope this helps!

@yogkumgit  There are no changes required in this document. 
Thanks
Sri
