### ISSUE TITLE
Add license requirement under the - What do you need to know before you begin section.

### ISSUE THREAD

**Issue by JamesTran-MSFT** [MicrosoftDocs/microsoft-365-docs#10430]
Add the requirement for a Microsoft 365 E5 or Microsoft Defender for Office 365 Plan 2 license within the [What do you need to know before you begin](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide#what-do-you-need-to-know-before-you-begin) section.

This is [mentioned at the beginning of the article](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide) but could easily be missed by users. For more info - https://learn.microsoft.com/en-us/answers/questions/1111420/index.html

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59c87455-77af-093a-6fb6-286049aad15a
* Version Independent ID: b2690e98-781d-4a27-a9bc-bd621964feb0
* Content: [Get started using Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-get-started.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JamesTran-MSFT, it might be faster if you did this yourself where you want it. It's super-easy; instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md). Just @ include in the comments of your pull request.
