### ISSUE TITLE
Incorrect Graph API endpoints, no clear expectations set on message deletion time

### ISSUE THREAD

**Issue by DmitryVorobyov** [MicrosoftDocs/microsoft-365-docs#10441]
1. Based on my testing, Graph API endpoints for eDiscovery are currently under ".,./compliance/...", not ".../security/..."
2. There needs to be an expected deletion time specified (ideally an SLA). Deletion process is not immediate, and it is currently unclear what can be expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 327f05ec-cc23-3241-eb82-12d89ea0bfc8
* Version Independent ID: 327f05ec-cc23-3241-eb82-12d89ea0bfc8
* Content: [Search for and delete chat messages in Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-and-delete-teams-chat-messages?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-and-delete-Teams-chat-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-and-delete-Teams-chat-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@DmitryVorobyov Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10476

Once the author approves, the changes will be live.

I tested purging data and I see that as soon as I run the POST request to purge chat messages, these messages are removed from the Teams client. I have added @robmazz  to confirm if this is the right behavior or if this needs to be reported to PG.

Thanks
Sri
