### ISSUE TITLE
How to assign the Microsoft Defender for Business servers license ? 

### ISSUE THREAD

**Issue by KevMcCordStewartMuseum** [MicrosoftDocs/microsoft-365-docs#10449]
Hello,

I followed the process to enroll Windows Server to Microsoft Defender successfully ...
•	I assigned the Microsoft Defender for Business to the admin account used to enroll the Windows Servers
•	I bought one Microsoft Defender for Business servers
•	I enroll one Windows Server successfully
•	The console still show the Microsoft Defender for Business servers license as NOT assigned.
 
So, my question is, how to assign that license to the server that I just enrolled ?
I understand that I am supposed to have one Microsoft Defender for Business servers per server that I will enroll
I just don’t understand how to assign these licenses to the servers . 
The Microsoft 365 shows the license Microsoft Defender for Business servers as not used, I am not sure if this is a normal situatin or not :-D

Thanks !

Kev

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0bd9d5a-a0ff-fd44-8eb4-3938ffb307a9
* Version Independent ID: d0bd9d5a-a0ff-fd44-8eb4-3938ffb307a9
* Content: [Get Microsoft Defender for Business servers](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/get-defender-business-servers?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/get-defender-business-servers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/get-defender-business-servers.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @KevMcCordStewartMuseum. Thank you for posting your question here. I'll check on this and will respond as soon as I can.

**Comment by denisebmsft** [comment]
Hello @KevMcCordStewartMuseum. I'm following up on your very good question about assigning the Microsoft Defender for Business servers license. Although you need one license per server, you do not have to assign it to any users or devices. As you experienced, even if you do assign it to a user, such as an admin account, it will still show as unassigned. This is a known issue at this time. I'm updating the article to hopefully make it more clear. Please let us know if you have any other questions.

**Comment by KevMcCordStewartMuseum** [comment]
Hello @denisebmsft  , Thank you for the explanation. That's what I thought but just wanted to make sure it was the way to go !

**Comment by Ntworkadmin** [comment]
Hello @denisebmsft, we bought Microsoft Defender for Business servers, and we onboarded successfully but is still showing as unassigned license do we know when this issue will be address? also, some policies not applying from itune to 2016-2022 server any information about what support what platform?
