### ISSUE TITLE
Incorrect directions to turn on auditing

### ISSUE THREAD

**Issue by b-col** [MicrosoftDocs/microsoft-365-docs#1044]
"You have to first turn on audit logging before you can run an audit log search. If the Start recording user and admin activity link is displayed, click it to turn on auditing."

The link simply says "Turn it on", rather than "Start recording user and admin activity". This is shown correctly in the below article:
https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#step-1-run-an-audit-log-search)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@b-col Thanks for the heads up. Will you please take a screenshot of the UI where the "turn it on" string appeared and attached to this thread? And the navigation instructions for how you got to that UI? Thanks.

**Comment by markjjo** [comment]
@b-col Nevermind. I found the string in the UI. I will update topic accordingly.

![image](https://user-images.githubusercontent.com/36746813/72175696-9b7a9d00-3391-11ea-91b6-04b66c7f5554.png)
