### ISSUE TITLE
Does not work as expected.

### ISSUE THREAD

**Issue by engorgedWOLF** [MicrosoftDocs/microsoft-365-docs#10459]
I think the links with the /security/ do not work. The old compliance ones do... sometimes... 
The purge does not work as expected. if I want to purge chats between 2 dates, it deletes some and others in between are not deleted. 
Other times it does not purge anything at all. 
Why is that so?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 327f05ec-cc23-3241-eb82-12d89ea0bfc8
* Version Independent ID: 327f05ec-cc23-3241-eb82-12d89ea0bfc8
* Content: [Search for and delete chat messages in Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-and-delete-teams-chat-messages?view=o365-worldwide&branch=markjjo-teamssearchandpurge)
* Content Source: [microsoft-365/compliance/search-and-delete-Teams-chat-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-and-delete-Teams-chat-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@engorgedWOLF Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
