### ISSUE TITLE
M365 Ownerless group Policy - not working

### ISSUE THREAD

**Issue by mgmjtech** [MicrosoftDocs/microsoft-365-docs#10469]
I have enabled the M365 Ownerless group policy for 3 weeks now and none of the users are getting email notifications for it.

Ownerless group = 6500 groups/teams
Policy
Sender
xxxx@xxxxxx.onmicrosoft.com
Weekly notification options
Notify most active members: Weekly for ‎4‎ weeks
Number of active members to notify: ‎10‎
Specify who can receive ownership notifications: Block only certain active members
Groups
All groups

I have also used audit logs (compliance portal) to search for the ownerless group activities with no results. I have also gone thru the Q&A ownerless article. 

Please advise on how do i troubleshooting this and find the root cause as to why email notification is not sent to active users.

https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/ownerless-groups-teams?view=o365-worldwide
https://learn.microsoft.com/en-us/exchange/troubleshoot/groups-and-distribution-lists/ownerless-group-policy
https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-search?view=o365-worldwide

**Comment by msbemba** [comment]
@mgmjtech Thank you for your feedback. Since this is a technical query and could very well be a bug, I'd recommend you contact Microsoft support via the need help section on the admin center. So that a support engineer can work with you to resolve the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mgmjtech Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
