### ISSUE TITLE
Conflict between this doc and domain management in admin portal

### ISSUE THREAD

**Issue by tommoser** [MicrosoftDocs/microsoft-365-docs#10460]
When setting up a domain for GCCH in the admin portal, the docs indicate to use the office365.us endpoints. However, the domain management interface lists the commercial endpoints under Outlook.com in the admin portal.

Which set is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1a8b9e7-32c2-9e42-5f9d-8824bd15ab8e
* Version Independent ID: 4e4ba710-bb50-569d-34a6-8ef122d57aa6
* Content: [DNS records for Office 365 GCC High - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/dns-records-for-office-365-gcc-high?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/dns-records-for-office-365-gcc-high.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/dns-records-for-office-365-gcc-high.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @dzazzo
* Microsoft Alias: **dzazzo**

**Comment by dzazzo** [comment]
Hi Tom - the *.office365.us endpoints are the correct ones to use. We’ll log a bug for the portal team to update those endpoints in the admin center.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Tom Moser ***@***.***>
Sent: Monday, December 5, 2022 5:00:01 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: David Zazzo ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/microsoft-365-docs] Conflict between this doc and domain management in admin portal (Issue #10460)


When setting up a domain for GCCH in the admin portal, the docs indicate to use the office365.us endpoints. However, the domain management interface lists the commercial endpoints under Outlook.com in the admin portal.

Which set is correct?

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: b1a8b9e7-32c2-9e42-5f9d-8824bd15ab8e
  *   Version Independent ID: 4e4ba710-bb50-569d-34a6-8ef122d57aa6
  *   Content: DNS records for Office 365 GCC High - Microsoft 365 Enterprise<https://learn.microsoft.com/en-us/microsoft-365/enterprise/dns-records-for-office-365-gcc-high?view=o365-worldwide>
  *   Content Source: microsoft-365/enterprise/dns-records-for-office-365-gcc-high.md<https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/dns-records-for-office-365-gcc-high.md>
  *   Service: microsoft-365-enterprise
  *   GitHub Login: @dzazzo<https://github.com/dzazzo>
  *   Microsoft Alias: dzazzo
