### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ruscoe888** [MicrosoftDocs/microsoft-365-docs#10465]
The licensing section needs work - no idea on cost or how to obtain a license - going to the tenant and trying to purchase, I'm unable to find anything...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78fbba03-39f0-9d11-12b0-b57830942db8
* Version Independent ID: f14feef7-7041-5e60-c193-8eb480097511
* Content: [Microsoft 365 tenant-to-tenant migrations - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@ruscoe888 Thank you for your feedback. This document is created to understand different architectural models available for tenant-to-tenant migration. For purchasing licenses, you can check https://learn.microsoft.com/en-us/microsoft-365/commerce/licenses/buy-licenses?view=o365-worldwide 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ruscoe888 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
