### ISSUE TITLE
Minimum software requirement for specific page section info is self-contradictory

### ISSUE THREAD

**Issue by filippossemere** [MicrosoftDocs/microsoft-365-docs#10461]
[Either official documentation is misstated or the pre-requirements for Windows 11 for Microsoft Defender Application Guard for Office is thoroughly incorrect.]

This page refers to the part whereas "(Windows 10 only)" is stated under the minimum software requirement says above that all Windows 11 versions are supported. This makes absolutely no sense.

https://learn.microsoft.com/microsoft-365/security/office-365-security/install-app-guard#minimum-software-requirements

Self contradictory:

https://learn.microsoft.com/microsoft-365/security/office-365-security/install-app-guard#deploy-application-guard-for-office

--------------------------------------------------
I'm running Win11 with HCVI (UEFI lock), AMD-VT and VBS activated, yet am unable to run Microsoft Defender Application Guard for Office via virtual machine running on Dell switchless hyper-visor. I even installed the Microsoft Defender Application Guard Companion from the Microsoft Store and still not working. I have installed Microsoft Defender Application Guard for Office via **Programs and Features** > **Turn Windows features on or off**, confirmed installed. I have no logs to go after and seemingly no error messages appearing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8cc5310-e03b-d538-e741-09be5f32ab13
* Version Independent ID: 6f56df92-3eb1-56ff-efc9-a4d269efd7aa
* Content: [Application Guard for Office for admins - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/install-app-guard?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/install-app-guard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/install-app-guard.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@schmurky Please help us in resolving this issue. Thanks

**Comment by filippossemere** [comment]
> @schmurky Please help us in resolving this issue. Thanks

The pre-requirements for Microsoft Defender Application Guard for Office are supposedly fulfilled yet the functionality is still not actively turned on.

Where are the log location for Microsoft Defender Application Guard for Office? Otherwise I cannot help you fix this issue.

**Comment by Ratulch** [comment]
Looking into this.

**Comment by jotaylo** [comment]
It looks like the comment about the contradiction is specifically referring to step 1 - the wording is supposed to indicate that step 1 needs to be followed for those running Windows 10 only. All subsequent steps are relevant to Windows 10 and 11.

@filippossemere you mentioned enabling the Windows Feature, did you also enable the policy as described in step 3?

**Comment by Ratulch** [comment]
This issue has been addressed: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/18624. The updated topic will be published later today.
