### ISSUE TITLE
Modern Auth section still necessary?

### ISSUE THREAD

**Issue by MicrosoftGuyJFlo** [MicrosoftDocs/microsoft-365-docs#10467]
Is the section "Turn on Modern authentication for your organization" really needed anymore? Now that basic auth has been or is being disabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multifactor authentication for users - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@MicrosoftGuyJFlo Thank you for your feedback since Basic auth is still available till Dec 31st, 2022. The content team will update the document after the protocol has been completely disabled on all Microsoft tenants.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MicrosoftGuyJFlo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
