### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mramnet** [MicrosoftDocs/microsoft-365-docs#1046]
"Ofifce"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bbddb6-0c20-233e-6cee-12a7733f9acf
* Version Independent ID: 6155ec87-8d4b-edc9-3595-f1747d569363
* Content: [Upgrade to Microsoft 365 Business from Office 365 Business Premium - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/migrate-to-microsoft-365-business)
* Content Source: [microsoft-365/business/migrate-to-microsoft-365-business.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/migrate-to-microsoft-365-business.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@mramnet - Thank you for pointing this out.

PR #1049 has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!

**Comment by Sirkkuw** [comment]
merged. thank you for finding the issue!
