### ISSUE TITLE
How do I remove target spam messages in my organization?

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/microsoft-365-docs#1047]
Hi,

I was just targeted by a spam email to 14 users in my organization, I assume based on the 14 one of our clients address books were hacked. The email was sent from a gcocable.ca domain.

How can I remove these 14 messages immediately from my users mailboxes? It seems once its delivered I can only let the users know or grab a message ID and send it to O365 techs for analysis. How Can I take immediate action as an admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feec6b-ad9f-0592-70f0-295f8dbe7cfd
* Version Independent ID: 4434e0fa-efb0-d1fd-57e2-a43b83774dd0
* Content: [Anti-spam protection FAQ - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-protection-faq)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-protection-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-protection-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@eschrader - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
