### ISSUE TITLE
Block Office applications from injecting code into other processes

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/microsoft-365-docs#10478]
Block Office applications from injecting code into other processes

"This rule applies to Word, Excel, and PowerPoint."

This rule seems to apply to OneNote as well.  I see a few hits for it on our ASR Audit Reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Version Independent ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Content: [Attack surface reduction rules reference](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@mattsmacblog Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10495

Once the author approves, the changes will be live.

Thanks
Sri
