### ISSUE TITLE
uninstall steps by JAMF

### ISSUE THREAD

**Issue by morrow233** [MicrosoftDocs/microsoft-365-docs#10470]
[Enter feedback here]

My customer requesting us to provide actual steps needed for uninstall MDE on Mac by JAMF.
Please consider adding steps about uninstallation.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9240d179-335e-1031-d077-6bc0dbc8d5a7
* Version Independent ID: b3a7140b-d37e-e27f-d973-2cf6f10a4af8
* Content: [Resources for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-resources?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-resources.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@morrow233 Thank you for your feedback. centrally managed to uninstall is available on JAMF (https://docs.jamf.com/10.24.1/jamf-pro/administrator-guide/Uninstalling_Packages.html), but it is not yet available for Microsoft Intune. Since the steps require one to uninstall MDE on Mac by JAMF, it has not been added to the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @morrow233 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
