### ISSUE TITLE
Embedded video clips shows wrong captions and it should be fixed.

### ISSUE THREAD

**Issue by mutsun1** [MicrosoftDocs/microsoft-365-docs#10475]
video clip that is embedded on this page shows incorrect caption and it looks like for PowerAutomate but is not Microsoft 365 Defender portal.
This page is for explanations what M365 Defender is and the captions of this video should be fixed.

Here is the screen shot of the video clips on this page.

![image](https://user-images.githubusercontent.com/22488411/206183027-d99cecf1-f6b8-49ae-8813-c82478505937.png)

![image](https://user-images.githubusercontent.com/22488411/206183211-08654062-4939-4b71-80fd-50c4bf2d4df4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16e75870-345e-f35b-87e2-e5e4f2707391
* Version Independent ID: 16e75870-345e-f35b-87e2-e5e4f2707391
* Content: [Microsoft 365 Defender portal](https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-defender-portal?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-365-defender-portal.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-defender-portal.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Will add task item to backlog.
