### ISSUE TITLE
Step 6 needs instructions on how to verify deletion without accessing Teams app

### ISSUE THREAD

**Issue by DmitryVorobyov** [MicrosoftDocs/microsoft-365-docs#10482]
Users with eDiscovery roles, who are tasked with purging the messages, may not have the option to reach out to the users whose chat messages have been purged and ask them to verify that the purge has been successful. 

_For example, Teams messages being purged can belong to a C-level executive - in this case the eDiscovery admin doing the purge won't be able to approach the executive and ask them to check their Teams._ 

Therefore, there needs to be a way to check for successful deletion of messages "from the back-end" (e.g., by refreshing collection results). 

There also needs to be clear information on how long does it take for purge results to be reflected on the number of items in the eDiscovery collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 327f05ec-cc23-3241-eb82-12d89ea0bfc8
* Version Independent ID: 327f05ec-cc23-3241-eb82-12d89ea0bfc8
* Content: [Search for and delete chat messages in Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-and-delete-teams-chat-messages?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-and-delete-Teams-chat-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-and-delete-Teams-chat-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@DmitryVorobyov - thanks for the feedback. As an internal MS contact, I'll send you an internal email with the link to the content request form so you can submit this request there. Submitting internally is easier for me and the PG team to review, confirm, and approve.
