### ISSUE TITLE
The /v: switch for verbose status messages into a log file gives an error as written.

### ISSUE THREAD

**Issue by shawntr** [MicrosoftDocs/microsoft-365-docs#1048]
The command for /v: switch above will give an error unless the .log extension is removed.

The article has the switch as "/V:"c:\Users\Admin\Desktop\Uploadlog.log""

It should be "/V:"c:\Users\Admin\Desktop\Uploadlog"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@shawntr Thanks for the info. What is the error if you include the .log extension?

**Comment by markjjo** [comment]
Closing this issue. Can't repro. Azcopy outputs a log file to, for example. upload.log. I did receive an error if the log file specified by /V: parameter was open when I ran azcopy, but .log extension doesn't return an error.
