### ISSUE TITLE
Five attributes in Azure AD?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#10488]
The article says,
> Currently, we provide capabilities for five attributes in Azure AD
> * Company
> * Department
> * Country
> * State and Country
> * City, State, and Country

This is strange wording. I was originally looking for an attribute in AD named "State and Country" and another attribute named "City, State, and Country" but then realized that is probably not what the author intended.

I believe this is the intended meaning:

> The five attributes in AD that need to be populated are:
> * Company
> * Department
> * Country
> * State
> * City

The group level analytics aren't working for me yet, so I'm not sure if they can be grouped / filtered in the five ways described or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70d902a1-c74f-91b1-0ef4-39682c2174d3
* Version Independent ID: 70d902a1-c74f-91b1-0ef4-39682c2174d3
* Content: [Group Level Aggregates in Adoption Score - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/adoption/group-level-aggregates?view=o365-worldwide)
* Content Source: [microsoft-365/admin/adoption/group-level-aggregates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/adoption/group-level-aggregates.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@jonwbstr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10499

Once the author approves, the changes will be live.

Thanks
Sri
