### ISSUE TITLE
Information on deleting domains incorrect?

### ISSUE THREAD

**Issue by a-goo** [MicrosoftDocs/microsoft-365-docs#10480]
Is the Note at point 4 in this section **"Add a new onmicrosoft.com domain"** https://learn.microsoft.com/en-us/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain?view=o365-worldwide&source=docs#add-a-new-onmicrosoftcom-domain 
correct?
![image](https://user-images.githubusercontent.com/105272899/206451572-8a91b17a-b302-4e89-9aec-cea558dabfdb.png)

From what I can see in the Azure portal deletion of _onmicrosoft.com_ domains is possible:

![image](https://user-images.githubusercontent.com/105272899/206452051-6c51fcc8-ad97-48bb-83bf-b4e948950d9d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a66bd91-6de1-5128-0f77-df1573b7f800
* Version Independent ID: 0a66bd91-6de1-5128-0f77-df1573b7f800
* Content: [Add and replace your onmicrosoft.com fallback domain in Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
I followed up with engineering on this.  They verified that although you will see the Delete button in the Azure portal, if you attempt to continue with deleting the verified onmicrosoft.com domain, it will fail with an error.

**Comment by a-goo** [comment]
> I followed up with engineering on this. They verified that although you will see the Delete button in the Azure portal, if you attempt to continue with deleting the verified onmicrosoft.com domain, it will fail with an error.

@efrene - please provide the following feedback to the engineering team:

As a general principle, if something is not possible to be done, then 
a) clear information should be provided in the GUI regarding what is possible/not possible, and 
b) options (menus, buttons etc) to manage a resource should be consistent with what is possible - i.e. no delete button or menu item should be available or should be deactivated.

In this instance, 
o	Options to delete the domain are clearly visible
o	All the processes to prepare for deletion of this domain are available 
o	When reaching the final step for deletion, the error message does not provide correct/clear information

All of this is contrary to what is apparently actually possible. No information is provided anywhere regarding that this domain cannot be deleted.
This is a **very poor user experience** and a waste of my time, my customer’s time, and Microsoft support resources time.
Not only is it a waste of time it is extremely frustrating for me and my customer. Microsoft needs to continually pay attention to and ensure good usability at all times.

**Comment by efrene** [comment]
@a-goo, I agree that this is not a good user experience and is the first time I have seen it. I will make sure to pass your complete feedback on to them, and am sorry for the inconvenience it has caused you and the customer.
