### ISSUE TITLE
Attachment format when manually reporting emails.

### ISSUE THREAD

**Issue by glr0221** [MicrosoftDocs/microsoft-365-docs#10481]
Hello Microsoft,

You mentioned the following in the message submission format : 

_The user reported message is unmodified and is included as an attachment._

I would just like to inquire what type of attachment does your 'report' system support?
Do we need to use eml or msg format?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User reported message settings - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-user-reported-messages-files-custom-mailbox?view=o365-worldwide#message-submission-format)
* Content Source: [microsoft-365/security/office-365-security/submissions-user-reported-messages-files-custom-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-user-reported-messages-files-custom-mailbox.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@glr0221, in the [Options for third-party reporting tools]{https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-user-reported-messages-files-custom-mailbox#options-for-third-party-reporting-tools) section, we say:

> A messages sent to the reporting mailbox must include the original user reported message as an uncompressed .EML or .MSG attachment. Don't forward the original user reported message to the reporting mailbox.

So, I would say we support both formats.

**Comment by yogkumgit** [comment]
@glr0221 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by glr0221** [comment]
Thanks @yogkumgit @chrisda. Let us close this item.
