### ISSUE TITLE
Why does Pay-per-incident URL redirect to M365 Support?

### ISSUE THREAD

**Issue by AmazonGrace** [MicrosoftDocs/microsoft-365-docs#10484]
I had this URL bookmarked https://support.microsoft.com/en-us/topic/support-for-business-1f4c4d09-9047-28ac-bb3b-618757e3bffd which was a great reference that broke down comparisons between support plans. Now it redirects to this M365 page which makes no sense at all. https://learn.microsoft.com/en-US/microsoft-365/admin/get-help-support?view=o365-worldwide

If you search Bing for Microsoft pay per incident, the above URL is the first search return - and then the user gets sent to a product-specific page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Version Independent ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Content: [Get support - Microsoft 365 admin](https://learn.microsoft.com/en-US/microsoft-365/admin/get-help-support?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-support.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us in resolving this issue. Thanks

**Comment by cmcatee-MSFT** [comment]
@yogkumgit My team doesn't own the content on support.microsoft.com and isn't responsible for redirects from articles there. I've reached out to the team that owns SMC content to help resolve this.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please suggest , who can be assigned as contact person. Thanks

**Comment by cmcatee-MSFT** [comment]
@yogkumgit The URL now redirects to this page: [Small business help & learning](https://support.microsoft.com/en-US/smallbusiness). The old page was retired, and, to my knowledge, there is no comparable page for it now.
