### ISSUE TITLE
GCC / GCCH documentation issue

### ISSUE THREAD

**Issue by dacmcbibs** [MicrosoftDocs/microsoft-365-docs#10483]
[Enter feedback here]
The GCC High section of the documentation for adding the Report Message or Phishing add-ins is not correct

- The URL for the Microsoft 365 admin center does not redirect to the GCCH admin center.
- The steps are to go to "Settings > Add-ins" but in in the tenant its actually "Organizations < Add-ins"
- The link to the Report Phishing Manifest file is broken ( https://ipagave.azurewebsites.net/ReportMessageManifest/ReportPhishingAzure.xml)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@dacmcbibs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10498

Once the author approves, the changes will be live.

The URL seems to be temporarily down, I'm copying the author to check this internally

CC : @Dansimp 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dacmcbibs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dacmcbibs** [comment]
Just an FYI the link to the manifest for report phishing is still broken : 
 https://ipagave.azurewebsites.net/ReportMessageManifest/ReportPhishingAzure.xml

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@dacmcbibs The URLs have been updated and the Manifest is working now.

@yogkumgit  This can be closed.

Thanks
Sri

**Comment by jkurlanski** [comment]
It appears to be broken again

**Comment by yogkumgit** [comment]
@msbemba Kindly look into it. Thanks

**Comment by Ratulch** [comment]
The link is working again https://ipagave.azurewebsites.net/ReportPhishingManifest/ReportPhishingAzure.xml. 
Looks like this is a server issue and not really a documentation issue.

**Comment by jkurlanski** [comment]
Confirmed!

Joe Kurlanski CISSP(r) HCISPP(r)
President
Monarch Information Security Consulting, Inc

Phone: (207) 808-0472 | Mobile: (207) 232-2511
www.MonarchISC.com<https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fmonarchisc.com%2F&data=05%7C01%7Cjoe%40monarchisc.com%7C1680d9787ea246d88ac208dabda1e866%7C27e7fb1386844114a8141d3ce26950c4%7C0%7C0%7C638030800384939777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BubYPpeFJTG23WGV5h6Ka6l0zfuYZH59wylnqabqjjE%3D&reserved=0> | Let's Connect  <https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fjoe-kurlanski-0a432b6b%2F&data=05%7C01%7Cjoe%40monarchisc.com%7C1680d9787ea246d88ac208dabda1e866%7C27e7fb1386844114a8141d3ce26950c4%7C0%7C0%7C638030800384939777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KIkVak5xn3HuwBzgdLnA36ICxfHPizwVlAVAb9nSoKI%3D&reserved=0>

*Links are active. Mouse-over before clicking to ensure they are legitimate
