### ISSUE TITLE
doc: please correct "routing guide" 404 error

### ISSUE THREAD

**Issue by michaelspinks** [MicrosoftDocs/microsoft-365-docs#10492]
In the article in the section [here](https://learn.microsoft.com/en-us/microsoft-365/enterprise/azure-expressroute?view=o365-worldwide#implementing-expressroute-for-microsoft-365) the "routing guide" link is returning a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1f4de16-6600-515c-138e-0d43f330a7b0
* Version Independent ID: 547b7ad4-1722-bd71-4818-95abbaa475ad
* Content: [Azure ExpressRoute for Microsoft 365 - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/azure-expressroute?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/azure-expressroute.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/azure-expressroute.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I've resolved the issue and the revision will be published later today. -Kelley
