### ISSUE TITLE
Attack simulation email has incomplete headers

### ISSUE THREAD

**Issue by glr0221** [MicrosoftDocs/microsoft-365-docs#10497]
Hello Microsoft,

I would like to inquire about the headers of the email sent out when running an attack simulation. The headers of these attack simulation emails seems to be composed of four lines only as shown in the image below : 

<img width="738" alt="MissingHeaders" src="https://user-images.githubusercontent.com/3444844/206993940-30d08b27-125e-4598-9136-2205b750e5db.png">

The other issue I have is that when this attack simulation email is downloaded, some of the headers are auto-generated? From the 4 headers show, the 'From', 'To', 'Subject', Thread-topic and other headers are auto-generated. 

<img width="757" alt="Screen Shot 2022-12-12 at 4 16 00 PM" src="https://user-images.githubusercontent.com/3444844/206995662-4dac2291-64db-4451-ae46-07569c30b01d.png">

I guess the bottomline here is the inconsistency of the available data/headers. The first image attached is also the result when using the EWS / GRAPH / REST APIs to query the headers. How can we use the GRAPH/REST/EWS APIs to get the same set of headers as that of the second image?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59c87455-77af-093a-6fb6-286049aad15a
* Version Independent ID: b2690e98-781d-4a27-a9bc-bd621964feb0
* Content: [Get started using Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-get-started.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@glr0221, you should open a support ticket and ask.

**Comment by glr0221** [comment]
Hello @chrisda, support ticket for M365? for the Defender feature? Thanks.

**Comment by chrisda** [comment]
@glr0221, you can't open support tickets here in GitHub. All we do here is fix documentation.

 From any page in security.microsoft.com, click the need help button:

![image](https://user-images.githubusercontent.com/33166947/207409798-e1ca1104-1444-4f35-983f-42a3c381e05e.png)

**Comment by glr0221** [comment]
Thank you. We can close this item for now.

**Comment by chrisda** [comment]
@glr0221, opening a support ticket will (eventually) get your question in front of the people who can answer your questions.
