### ISSUE TITLE
The GPO Path referenced to schedule protection updates is wrong

### ISSUE THREAD

**Issue by jongross4** [MicrosoftDocs/microsoft-365-docs#10505]
[Enter feedback here]
Step 4 under GPO references Windows components > Microsoft Defender Antivirus > Signature Updates when it should reference Windows components > Microsoft Defender Antivirus > Security Intelligence Updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4e26a44-834c-bcd3-5fec-b9aa9bb8cde1
* Version Independent ID: 1d3e40d3-8d86-147d-f509-2f59adbceee0
* Content: [Schedule Microsoft Defender Antivirus protection updates](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@jongross4 We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10533

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jongross4 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
