### ISSUE TITLE
Remove 'Use Intune to tune on cloud protection'

### ISSUE THREAD

**Issue by ruphuss** [MicrosoftDocs/microsoft-365-docs#10500]
The section *Use Intune to tune on cloud protection* should be removed as the recommended approach is to use Endpoint Security to configure Defender Antivirus.

*Intune* and *Microsoft Endpoint Manager* are the **same** product so having both of these sections doesn't make sense. Anything security related (antivirus, firewall, encryption) should be configured under Endpoint Security and not as a Device Configuration Profile. That was the old method for configuring security.

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus?view=o365-worldwide&source=docs#use-intune-to-turn-on-cloud-protection

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcfc10-a6b2-04a9-180e-7e0ffa230c36
* Version Independent ID: 8ed5bf92-9816-fb44-ca16-8d6fd8b1e37f
* Content: [Turn on cloud protection in Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus?view=o365-worldwide&source=docs#use-intune-to-turn-on-cloud-protection)
* Content Source: [microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@ruphuss Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10530

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ruphuss Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
