### ISSUE TITLE
Update the process for turning on cloud protection with MEM

### ISSUE THREAD

**Issue by ruphuss** [MicrosoftDocs/microsoft-365-docs#10501]
1. In step 3, the link to create a new profile opens a link to creating a device restriction policy. We shouldn't recommend using this template to try and create an antivirus policy. I couldn't find the correct article which steps an administrator through the process of creating an Antivirus policy under Endpoint Security so maybe consider removing the link or creating the article and updating the link. Either would be better than directing an admin to an article that is not related to creating an antivirus policy.
2. The process for turning on Cloud Protection with MEM is incorrect. Step 5 of the process details how to configure *Cloud Block Level*. Configuring this setting without enable Cloud protection won't do anything.
3. There is a link to an article on how to create antimalware policies with Microsoft Endpoint Configuration Manager. This is not really related with creating policies with MEM/Intune so again, should probably be removed.

If you did want to include links to articles related to actual subject matter, try these:
https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-antivirus-policy
https://learn.microsoft.com/en-us/mem/intune/protect/antivirus-microsoft-defender-settings-windows#cloud-protection
https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-policy#manage-conflicts

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus?view=o365-worldwide#use-microsoft-endpoint-manager-to-turn-on-cloud-protection

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcfc10-a6b2-04a9-180e-7e0ffa230c36
* Version Independent ID: 8ed5bf92-9816-fb44-ca16-8d6fd8b1e37f
* Content: [Turn on cloud protection in Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus?view=o365-worldwide#use-intune-to-turn-on-cloud-protection)
* Content Source: [microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
@ruphuss thank you so much for your feedback. I have updated the article to make it more accurate. I appreciate your input. Thanks for helping us improve the quality of our documentation. You should see the doc updates live a little later today.
