### ISSUE TITLE
Attack Simulator - please confirm "applies to" eligibility.

### ISSUE THREAD

**Issue by Sizzl** [MicrosoftDocs/microsoft-365-docs#10509]
Could we please confirm the intention of the "Applies to" table? Attack simulator isn't available in P1-only environments.

If the intention is for it to be there because anyone can sign up for a P2 trial to use it, then perhaps further clarification would be warranted? It's a little misleading currently, and not consistent with docs for other attack simulation tooling (e.g., with Defender for Office, documentation clearly states that it only applies to P2).

Otherwise, this doc may have been incorrectly updated to include the "Applies to" section with the rest of the bulk updates in October 2021 (commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/0091839969f4bb4b58868b7d6a8a5cfc47244eb1).

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e038c807-ffc4-5594-06c9-20f8edec48c2
* Version Independent ID: e501e36c-36a2-c6ee-cf09-12a4e62c069e
* Content: [Experience Microsoft Defender for Endpoint through simulated attacks](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-simulations?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-simulations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-simulations.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@Sizzl Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10543

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Sizzl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
