### ISSUE TITLE
Write-Host missing on line 77

### ISSUE THREAD

**Issue by Spence10873** [MicrosoftDocs/microsoft-365-docs#10504]
Line 77 of the provided PowerShell script to output a report is missing the cmdlet Write-Host. The script fails to execute until Write-Host is added before "No hold policies found in case:"...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 170c3a0d-4a77-211f-8ef4-21da97042c1e
* Version Independent ID: b121eb8f-2438-f0cf-41b9-0cfe3ca34925
* Content: [Use a script to create an eDiscovery holds report - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Spence10873 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10532

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@Spence10873 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
