### ISSUE TITLE
Bookings with Me looks to have been released to GA but multiple places with "Preview" indication

### ISSUE THREAD

**Issue by lauriebeamish** [MicrosoftDocs/microsoft-365-docs#10510]
Based on Road map this has gone to General Availability but seeing the Preview in the following places:
**Outlookonweb**
![image](https://user-images.githubusercontent.com/86493942/207391985-9be32163-e08d-43a1-8c8c-e9dffb52c8b5.png)

**Bookings with Me FAQ:**
Why is Bookings with me in preview?
Bookings with me is in preview for all enterprise users worldwide. We're collecting feedback and making improvement while it is being integrated into scheduling experiences in Bookings and Outlook.

**Learning**
https://learn.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide#why-is-bookings-with-me-in-preview
Can this be fixed?
Our management is hesitate to deploy Bookings with Me through out firm if it still has the "Preview" label

Laurie

**Comment by msbemba** [comment]
@lauriebeamish Thank you for your feedback. I'm currently checking with the Author/PM and will update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit author is currently working with the PM internally on this.

Thanks
Sri

**Comment by msbemba** [comment]
Author is currently checking with the PM's to get this fixed.

**Comment by msbemba** [comment]
@lauriebeamish The Preview banner has been removed.

@yogkumgit  This can be closed.
