### ISSUE TITLE
Microsoft 365 Compliance & Azure Compliance - out of sync

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/microsoft-365-docs#1051]
M365 compliance page - https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-home.md
is out of sync with the Azure compliance page - https://azure.microsoft.com/en-us/overview/trusted-cloud/compliance/

Unknown which is a more accurate representation of a source of truth but as an example, M365 compliance offering "TruSight" is listed as an 'Industry' compliance offering whereas the Azure compliance page lists it as a region/country specific offering

Same example can be said with "FDA CFR Title 21 Part 11"

**Comment by robmazz** [comment]
@CHDAFNI-MSFT - thanks for the feedback, the Microsoft 365 page is authoritative. The Azure compliance page points to the topics on the Microsoft 365 page and content set. The differences in the grouping of the topics will be updated so that they match. Thanks again!
