### ISSUE TITLE
Add notification for impact on existing guests

### ISSUE THREAD

**Issue by laminblake** [MicrosoftDocs/microsoft-365-docs#10516]
While the changes implemented in this article are obvious to some, others might not realize that this change will block access for existing guests whose domains are not added to cross-tenant access organizational settings. Probably best to add a warning on this page for that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d78edc3b-1cd8-4654-b5c3-4c5268ac5903
* Version Independent ID: d78edc3b-1cd8-4654-b5c3-4c5268ac5903
* Content: [Limit guest sharing to specific organizations](https://learn.microsoft.com/en-us/microsoft-365/solutions/limit-guest-sharing-to-specific-organization?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/limit-guest-sharing-to-specific-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/limit-guest-sharing-to-specific-organization.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by laminblake** [comment]
Also applying these changes will block all communication inbound via teams with any domain not configured in the organization settings, including personal accounts.

**Comment by msbemba** [comment]
@laminblake Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10542

Once the author approves, the changes will be live.

Thanks
Sri
