### ISSUE TITLE
Certification Validation errors for globaldisco.crm.dynamics.com

### ISSUE THREAD

**Issue by PrasadMadhavan** [MicrosoftDocs/microsoft-365-docs#10519]
We have a SharePoint 2013, Dynamics 365 integration where  a user uploads a file in SharePoint library. This triggers a SharePoint event receiver, which sends a request to Dynamics 365 to create a document link.  It has been working fine since last 3 years, but recently it fails sporadically and we notice the error on event logs as shown below. 

An operation failed because the following certificate has validation errors:
 
Subject Name: CN=globaldisco.crm.dynamics.com, O=Microsoft Corporation, L=Redmond, S=WA, C=US
Issuer Name: CN=Microsoft Azure TLS Issuing CA 02, O=Microsoft Corporation, C=US
Thumbprint: 80B7F9A5A22C6936F5F50569480A146B1220879A
Errors:
NotTimeValid: A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.

While searching for a resolution for this, we found below article online, While this issue may not be directly related to this article, we do wish to know more about the certificate "Microsoft Azure TLS Issuing CA 02" and why we receive certification validation errors as above. 
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md

Can you please help? 

Regards
Prasad

**Comment by msbemba** [comment]
@PrasadMadhavan Thank you for your feedback. Since this is a technical issue, I'd recommend you contact support via the need help button on the admin center. So that a support engineer can fix the issue or escalate if it is a bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PrasadMadhavan Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
