### ISSUE TITLE
Need more direction

### ISSUE THREAD

**Issue by thatbeingsaid3** [MicrosoftDocs/microsoft-365-docs#10517]
Regarding the comment "This user is synchronized with your local Active Directory. Some details can be edited only through your local Active Directory".  I had this issue.  The problem is that the on-prem DC does not have any Exchange options for me to add primary or alias emails.  If you can add a bit more instructions on how to do that using on-prem AD, that would be great,

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@thatbeingsaid3 Thank you for your feedback. This document pertains only to adding information on the M365 admin center. 

There are multiple ways to add an alias to a user in AD. https://learn.microsoft.com/en-us/answers/questions/260810/how-i-can-add-mail-alias-second-address-for-o365-a.html

IF you still cannot add an alias, Please create a support ticket via the need help section on the admin center so that a support engineer can assist you.

Hope this helps!


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @thatbeingsaid3 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
