### ISSUE TITLE
Include the "Surface Hub‎ and ‎Microsoft Teams‎ Rooms setup guide" under the "Guides for collaboration section"

### ISSUE THREAD

**Issue by jagonzal01** [MicrosoftDocs/microsoft-365-docs#10522]
Hi team,

We are missing the "Surface Hub‎ and ‎Microsoft Teams‎ Rooms setup guide" under the "Guides for collaboration" section. This is the URL for the guide:
https://admin.microsoft.com/#/modernonboarding/surfacehubsetupguide

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e0e0337-ad80-74c2-07df-1164a0641feb
* Version Independent ID: 7f19f87a-79cf-33b6-c64f-4449b1add0d9
* Content: [Setup guides for Microsoft 365 and Office 365 services - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/setup-guides-for-microsoft-365?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/setup-guides-for-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/setup-guides-for-microsoft-365.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@jagonzal01 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10541

Once the author approves, the change will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This has been updated. Issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jagonzal01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
