### ISSUE TITLE
Dispose Review Comment

### ISSUE THREAD

**Issue by IstvanYbema** [MicrosoftDocs/microsoft-365-docs#1052]
Could you please add instructions on where to get the comments that were added tot the dispose review? 
In the Dispose Review windows the reviewer can add comments on the actions: Dispose, Extend and Relabel. These actions and the comments should be available somewhere.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: d552f987-1606-01f7-d600-5887968ae60c
* Version Independent ID: 8c5f88de-93e7-862e-0550-fb9ac012be35
* Content: [Overview of disposition reviews - Microsoft 365 Compliance](https://docs.microsoft.com/nl-nl/microsoft-365/compliance/disposition-reviews#feedback)
* Content Source: [microsoft-365/compliance/disposition-reviews.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@IstvanYbema  I learned from engineering that they can be seen in the "Disposed" tab when the item is disposed, but this feature hasn't yet completed rollout for SharePoint Online items - so for these, you might have to wait another month or so.  I'll look at adding this clarification to the page when the feature is fully rolled out.
