### ISSUE TITLE
14 character not possible in O365

### ISSUE THREAD

**Issue by guitman444** [MicrosoftDocs/microsoft-365-docs#10521]
This page recommends a 14 character minimum password. But, Azure AD does not allow enforcement of this. Azure AD passwords are "A minimum of 8 characters and a maximum of 256 characters.", and this cannot be changed:

https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-sspr-policy#password-policies-that-only-apply-to-cloud-user-accounts

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit  I'm currently checking with the author and PM. Will update the document if need be.

**Comment by yogkumgit** [comment]
Author confirmed that issue has been fixed. closing. Thanks
