### ISSUE TITLE
Confusing text

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#10539]
There is a sentence that begins with "the following table...." and there is not a table after the paragraph, the next paragraph begins with "The following roles..." 

This is confusing, Please add the table or rewrite the first paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Roles and role groups in Microsoft Defender for Office 365 and Microsoft Purview compliance - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/scc-permissions?toc=%2Fmicrosoft-365%2Fcompliance%2Ftoc.json&bc=%2Fmicrosoft-365%2Fbreadcrumb%2Ftoc.json&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/scc-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/scc-permissions.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DeanGross, OK fixed.

Thanks for the feedback.

Closing.
