### ISSUE TITLE
Search-Mailbox -DeleteContent parameter orphans

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/microsoft-365-docs#1053]
Hi guys,

I have a script to delete content from some shared mailbox with the "Search-Mailbox -DeleteContent" cmdlet. With this retirement, what should I do to prepare myself? Does exist any other way to achieve my goal?

Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b8bac8-ffc4-8c4c-2d59-f27a96dbd414
* Version Independent ID: b78fa02e-9ae3-fa72-e23a-f70cf96d2e0f
* Content: [Retirement of legacy eDiscovery tools - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement?source=docs)
* Content Source: [microsoft-365/compliance/legacy-ediscovery-retirement.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/legacy-ediscovery-retirement.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ingd This section descriptions using ComplianceSearch and ComplianceSearchAction cmdlets as a replacement: https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement?source=docs#search-mailbox-cmdlet

This topic has more instructions: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization
