### ISSUE TITLE
Specific to Outlook

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/microsoft-365-docs#10545]
["If somebody forwards a meeting invite from an email client other than Outlook, although any applied encryption persists, the sensitivity label is dropped."

Please add the definition of being dropped here. Simply not visible I assume? Thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7476556-f95b-5e2f-2301-46cc3d52b71c
* Version Independent ID: b7476556-f95b-5e2f-2301-46cc3d52b71c
* Content: [Use sensitivity labels to protect calendar items, Teams meetings, and chat - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-meetings?view=o365-worldwide#prevent-copying-chat-to-the-clipboard-label-setting)
* Content Source: [microsoft-365/compliance/sensitivity-labels-meetings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-meetings.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ChristianJBergstrom An email client other than Outlook wouldn't display the sensitivity label in the first place, so my understanding of "dropped" was more literal - removed from the email headers (metadata).  It then wouldn't be displayed on any email client that was the recipient of a forward, including Outlook in the same tenant.  But I'll double-check this before updating the documentation with a clarification.

**Comment by cabailey** [comment]
@ChristianJBergstrom Yes, confirmed with a reword on its way to be published.  I learned that this behavior isn't specific to calendar items though, and wondering if it even needs to be included here.  Some more info:

There is no email standard requirement to keep any email header (other than the most basic ones) on any email/calendar reply/fwd.  When an email client drafts a reply/fwd, it only copies the content of the body and not much else. that's why the msip_header is not retained.

**Comment by ChristianJBergstrom** [comment]
> @ChristianJBergstrom Yes, confirmed with a reword on its way to be published. I learned that this behavior isn't specific to calendar items though, and wondering if it even needs to be included here. Some more info:
> 
> There is no email standard requirement to keep any email header (other than the most basic ones) on any email/calendar reply/fwd. When an email client drafts a reply/fwd, it only copies the content of the body and not much else. that's why the msip_header is not retained.

@cabailey That's some handy additional info, thanks.
