### ISSUE TITLE
Prevent copying chat to the clipboard label setting

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/microsoft-365-docs#10544]
["Currently, this setting isn't supported for users outside your organization, which includes anonymous users and external users."

But supported for guest users with a guest account?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7476556-f95b-5e2f-2301-46cc3d52b71c
* Version Independent ID: b7476556-f95b-5e2f-2301-46cc3d52b71c
* Content: [Use sensitivity labels to protect calendar items, Teams meetings, and chat - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-meetings?view=o365-worldwide#prevent-copying-chat-to-the-clipboard-label-setting)
* Content Source: [microsoft-365/compliance/sensitivity-labels-meetings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-meetings.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ChristianJBergstrom  Yes. Clarified in the documentation now.
