### ISSUE TITLE
Delegated permission

### ISSUE THREAD

**Issue by MWestermark** [MicrosoftDocs/microsoft-365-docs#10546]
_For billing accounts created inside of Microsoft 365 sign-up, new Global, Billing and Global Reader Administrators are automatically granted distinct levels of access. You can manage this access from the Billing > Billing accounts page by explicitly removing those users from the role assignment section at the bottom of the page._ 

This is very unclear. Does "Global, Billing and Global Reader Administrators" refer to granting delegated Global Administrator permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6755527d-53c9-a8b1-c2af-6446a9862783
* Version Independent ID: 8ba1ba1b-45c0-a51a-703e-da4c9dcb16b8
* Content: [Understand billing accounts](https://learn.microsoft.com/en-us/microsoft-365/commerce/manage-billing-accounts?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/manage-billing-accounts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/manage-billing-accounts.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@MWestermark Thank you for your feedback. Yes, it refers to Delegated administrator Permissions. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MWestermark Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
