### ISSUE TITLE
whitelist size?

### ISSUE THREAD

**Issue by satyenshah** [MicrosoftDocs/microsoft-365-docs#1054]
Is there a length limit to an organization's "do not rewrite" list?  I heard last year that there was a relative small (like 140 byte) limit to the total length of the list.  I was wondering if that is still the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac84f75-b6d9-9495-873a-8f87b90b8034
* Version Independent ID: 18369495-0e0f-e3e1-6945-0200790fd107
* Content: [Set up a custom do-not-rewrite URLs list using Office 365 ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Abdul8383** [comment]
I confirm there is no length.

**Comment by mypil** [comment]
@satyenshah - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by Abdul8383 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
