### ISSUE TITLE
Add RSS feed to this site

### ISSUE THREAD

**Issue by kk-koji** [MicrosoftDocs/microsoft-365-docs#10540]
[Enter feedback here]
Several users have requested that add RSS feed to this site.
Is it possible to add RSS feed as like following site?

https://learn.microsoft.com/en-us/defender-for-identity/whats-new
![image](https://user-images.githubusercontent.com/59611341/208586459-36155a10-53ff-46ad-ac76-ce2d55678688.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89486ebd-f4fa-9d07-ee93-d04fd8d41027
* Version Independent ID: 667019d9-aac6-f466-1605-651a800fc212
* Content: [What's new in Microsoft Purview risk and compliance solutions - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by kk-koji** [comment]
Hello, any update for this issue?

**Comment by yogkumgit** [comment]
@kk-koji Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
