### ISSUE TITLE
Bookings is not included with F3

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/microsoft-365-docs#10548]
This page indicates F3 licenses entitle the user to Bookings but we recently confirmed this is not the case. We also opened a support ticket with Microsoft who confirmed F3 does not entitle a user to Bookings.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7484dd4-5d94-dd6c-0dbe-551c852677c1
* Version Independent ID: 257d60e2-9313-e08b-dccf-120cb4b30f5b
* Content: [Microsoft Bookings Frequently Asked Questions](https://learn.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-faq.yml)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@pagejustin Thank you for your feedback. The product page for both o365 and M365 F3 shows that it contains MS Bookings.

https://www.microsoft.com/en-us/microsoft-365/enterprise/office-365-f3?activetab=pivot:overviewtab

I'd recommend you open a support ticket and share this information with them.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @pagejustin Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
