### ISSUE TITLE
Outdated rreference

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/microsoft-365-docs#10549]
"Use the Content search tool in the Microsoft Purview compliance portal to quickly find email in Exchange mailboxes, documents in SharePoint sites and OneDrive locations, and instant messaging conversations in Skype for Business"

Skype for Business online has been discontinued for some time now ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43805ced-b8ff-10a2-fdeb-27164b7a60c2
* Version Independent ID: 2950235b-9c80-c617-631a-faacced47b49
* Content: [Search for content - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-for-content?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-for-content.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-content.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@TheITguy666 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10558

Once the author approves, the changes will be live.

Thanks
Sri
