### ISSUE TITLE
Update Parameter: "Resource" to "Scope"

### ISSUE THREAD

**Issue by HPS-RobRice** [MicrosoftDocs/microsoft-365-docs#10554]
This page incorrectly states that `"resource": "https://api.securitycenter.microsoft.com"` needs to be provded in the POST body when authenticating (getting an access token). The correct value appears to be `"scope": "https://api.securitycenter.microsoft.com/.default"`. I suspect other pages that reference the `resource` parameter need to be updated too, such as [this](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-sample-python?view=o365-worldwide#get-token).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a700a4e-82ff-29ce-1b68-247de33652db
* Version Independent ID: bff8c6c3-eb28-1846-c711-36a7c67167aa
* Content: [Create an app to access Microsoft Defender for Endpoint without a user](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-create-app-webapp?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/exposed-apis-create-app-webapp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/exposed-apis-create-app-webapp.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@HPS-RobRice Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10617

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @HPS-RobRice Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
