### ISSUE TITLE
You seriously link to bing.com from https://aka.ms/o365cdns ?

### ISSUE THREAD

**Issue by fss23** [MicrosoftDocs/microsoft-365-docs#10552]
Aloha,
The very last link in the article: https://aka.ms/o365cdns links to a blank Bing.com search page.
please fix the redirect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3e4d9f-5c87-71ae-24c3-1d2490812632
* Version Independent ID: 12818354-d3c6-9058-78a5-495ad511fb6d
* Content: [Content delivery networks - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/content-delivery-networks?view=o365-worldwide#is-my-data-safe)
* Content Source: [microsoft-365/enterprise/content-delivery-networks.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/content-delivery-networks.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@fss23 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10593

The link is no longer active and has been removed. Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The PR has been merged. The issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fss23 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
