### ISSUE TITLE
SharePoint Online Migration?

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/microsoft-365-docs#10555]
Hi!
Is this tool only for Cross-tenant OneDrive migration or does it also migrate SharePoint Online sites?

Thanks!
Fernando

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c59d15b-a5d1-400a-aa12-8d768817f8f6
* Version Independent ID: 3c59d15b-a5d1-400a-aa12-8d768817f8f6
* Content: [Cross-tenant OneDrive migration overview - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-onedrive-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-onedrive-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-onedrive-migration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by msbemba** [comment]
@FernandoGualano Thank you for your feedback. This tool is specific to one drive and does not support SharePoint online sites.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @FernandoGualano Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Mike-Crowley** [comment]
FYI, the SharePoint version of this concept is in preview and discussed here: https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-sharepoint-migration?view=o365-worldwide
