### ISSUE TITLE
"Priority Accounts" does not exist on the "Active users" nor "Setup" page

### ISSUE THREAD

**Issue by g24swint** [MicrosoftDocs/microsoft-365-docs#10550]
The Active Users nor the Setup page have any "priority accounts" management function available. Seems like this documentation is well out of date.

I did look under the "three dots" menu under active users and still did not see the item

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 134a0b6c-728a-d952-2f1c-a6fd868db10c
* Version Independent ID: 640bb6ef-2003-c604-9d25-380b774cbbc0
* Content: [Manage and monitor priority accounts - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/priority-accounts?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/priority-accounts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/priority-accounts.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@g24swint Thank you for your feedback. I'll test this feature and update the documentation if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@g24swint Thank you for your feedback. I was able to find this under both options. 

![image](https://user-images.githubusercontent.com/45987684/211038235-a788f9e0-da0b-44a1-ad33-a49fd3b59a15.png)


If you still do not see this option, I'd recommend you contact Microsoft support via the need help section on the admin center so that the support engineer can assist you in fixing this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @g24swint Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
