### ISSUE TITLE
Failed RMS templates

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/microsoft-365-docs#10557]
Under section 4. you have 4 commands that its implied you need to run through AIP but only the first two run correctly the 3 and 4 do not run command not recognised as they are exchange commands.
still didn't fix my issue and the documentation around those missing RMS templates is just all over the show if someone could actually test these commands and ensure they work that would be nice. :)
Although I appreciate that might be hard given how unstable the platform is at the moment with all the "changes" currently happening.

Best Regards
Dave Webster

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe08d5e-4870-331e-b5f2-92848b5211b0
* Version Independent ID: 60ed3095-a42c-1bcb-f2fa-8325cfcd03f6
* Content: [Set up Microsoft Purview Message Encryption - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/set-up-new-message-encryption-capabilities?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-new-message-encryption-capabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-new-message-encryption-capabilities.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@webstaff Thank you for your feedback. The document suggests connecting to Exchange online PS earlier in the steps and we cannot to AIP just before executing these cmdlets. So, a single instance of PS will be sufficient to run both EXO and AIP cmdlets. Something like - https://learn.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @webstaff Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
