### ISSUE TITLE
Ongoing issue with Web Protection for Supervised iOS devices without local VPN

### ISSUE THREAD

**Issue by AFjolle** [MicrosoftDocs/microsoft-365-docs#10551]
Ongoing issue with Web Protection for Supervised iOS devices without local VPN

After a recent update of the Microsoft Defender iOS app, the app is not reacting to the {{issupervised}} configuration attribute, even though an active Zero Touch Control Filter and App Configuration Policy is present and working. 
This means that even with Zero Touch control filter enabled and working, the flow hangs on the "Allow Microsoft Defender to set up a VPN connection" page when launching the app.

Note:
- Zero Touch Content Filter is working and present in the iOS settings - skips login and terms without issues
- App Configuration Policy is working for every other attribute than {{issupervised}}
- Same result using the non-zerotouch control filter

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [App-based deployment for Microsoft Defender for Endpoint on iOS](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by FrodeBj** [comment]
Same here!

**Comment by msbemba** [comment]
@AFjolle Thank you for your feedback. This sounds more like a bug and needs to be reported to our Engineering team. I'd recommend you contact support via the need help section on the admin center, so that a Support engineer can collect more information and escalate if need be.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AFjolle Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mjcaparas** [comment]
Thanks for the report! We’ve connected with our friends on the Defender for Endpoint team and confirmed that Apple has acknowledged a bug in iOS 16.1: https://developer.apple.com/forums/thread/721101 

We do not have shareable target dates for when the next iOS update will be available and would encourage affected customers to install any new OTA updates as soon as they become available. Should you have any further issues once iOS 16.X is released and installed on your device, please reach back out to our support team for further review and investigation. Thanks!

**Comment by FrodeBj** [comment]
Just installed iOS 16.3 (preview from Apple Beta program). Same problem there with  {{issupervised}} not working.

**Comment by AFjolle** [comment]
@FrodeBj 
According to the Great Eskimo™ from the developer forum, it should be fixed in Beta 2, that has been seeding since January 11th.
Can you confirm that you are on Beta 2 or newer?

**Comment by BarbieAction** [comment]
May I ask if web protection would still work even if this bug is present.
I have the same issue where the Defender App would still ask for setting up loopback VPN. 
When I test SmartScreenUrlWarning it is not triggered unless I actually setup a loopback VPN.
I did the ZeroTouch config setup and all configs are applied.

**Comment by FrodeBj** [comment]
@AFjolle @BarbieAction I am on iOS 16.3 Release Candidate (20D47). After further investigations it seems like content filter is actually working when testing on smartscreentestratings2.net. I get the banner from Defender saying it has blocked the web connection. BUT the Defender app still says web protection is disabled, and if I try to reinstall Defender I am being asked for vpn setup.

**Comment by FrodeBj** [comment]
Well, I tried a workaround here. I added WebProtection = false config on the Defender app configuration in addition to the issupervised. It now seems like the Defender banner still appears if I go to the test page smartscreentestratings2.net. This way users don't get the vpn message when setting up Defender for the first time.

**Comment by AFjolle** [comment]
@FrodeBj @BarbieAction The workaround with disabling WebProtection is of course a temporary "solution", but not something i like at all, from a user experience point of view. And it dosn't work in iOS 16.2, so they have "fixed" something in 16.3 RC then.

@mjcaparas My questions is now as follows: Since it only works with WebProtection disabled, has apple only fixed it partially, or do we need MS to update their app accordingly to work with the "fix"?

**Comment by AFjolle** [comment]
@FrodeBj I can confirm the same behavior as you are expieriencing. Running 16.3 GA. Filtering is working, however the Defender App still prompts for VPN setup. So a little improvement from 16.2. 

@mjcaparas Rest of these problems must be MS or a bug that prevents the app from understanding the {issupervised} parameter.

**Comment by AFjolle** [comment]
I can now confirm that everything is working as it should after MS Defender 1.1.38xx update.

**Comment by BarbieAction** [comment]
@AFjolle I'm still having the following issue.
Everything is working, no loopback VPN is created etc, but the end-user still needs to open the Defender App and select Yes to agreement, then it restarts and starts working, but the end-user still needs to open the app once for web protection to work.

**Comment by AFjolle** [comment]
@BarbieAction We're running iOS 16.3.0, and newest version of MS Defender without issues and it skips the VPN creation in favor of using content filtering. The app is not required to be opened for it to work in our case. I haven't had time to test 16.3.1 however.
I would check if the ZeroTouch configuration policy is still in place, and i would also check if the {{issupervised}} parameter is set. I would also confirm that your devices are supervised and not just managed.

**Comment by BarbieAction** [comment]
@AFjolle Thank you for responding.

iOS 16.3.1
Device is managed & supervised
Config Policy - issupervised string {{issupervised}}
Device Config Profile - Custom with ControlFilterZeroTouch.mobileconfig

All policys are assigned correctly according to EMM.
**But how can i verify if the {{issupervised}} is set on the device?**

If i go to the device Settings - General - VPN & Device Management
I can see Content Filter Running: Microsoft Defender for Endpoint, however when i go to the smartscreen test site nothing is triggered.

Now if I open the Defender app, I'm asked to sign in, and then i need to agree to the terms of Use., then asked if MS defender should be allowed to send notification.

Everything is On and everything is working withou VPN but I have to open the app.

**Comment by AFjolle** [comment]
@BarbieAction
Since i have not tested iOS 16.3.1 yet, i get worried wether or not that could pose any issues.

Try to confirm that the issupervised App Config Policy is targeted at "All Devices" or a similar appropiate Dynamic Device Group (not all users). I have found no way of checking wether or not it has been deployed correctly to the devices.

Also try to confirm that the ZeroTouch Control Filter Device Config Profile is targeted at "All Devices" or a similar appropiate Dynamic Device Group (not all users). My understanding is that the function of this profile is to parse "True" to the issupervised variable set by App Config Policy together with setting a variable of SilentOnboard. Also make sure you are using the correct Control Filter policy with ZeroTouch silent onboarding, and not the normal one.

**Comment by BarbieAction** [comment]
@AFjolle Again thank you for answering me.
This is the Control Filter im using: https://aka.ms/mdeiosprofilesupervisedzerotouch

The app conifguration policy is assigned to all devices and I can see it being applied correctly accoridng to the report.
Device Configuration where I have the control filter I have pointed this to a dynamic device group, as I'm testing it.

Both are applied according to reports. 
The web protection says running but not working until I open the Defender App and then the user has to sign in and accept agreement.

**Comment by AFjolle** [comment]
@BarbieAction 
I will try to update one of our test devices til iOS 16.3.1, to see if i am encountering similar problems.
Will let you know in a bit.

**Comment by AFjolle** [comment]
@BarbieAction 
I can confirm it’s working for me after the iOS 16.3.1 update - it’s only asking for notification permission, and it is also working before giving the permission. So no changes here. I am unsure what is happening in your case :s

**Comment by BarbieAction** [comment]
@AFjolle Then I'm not sure what I'm doing wrong. And thank you so much for testing.
I'm I missing something?

I'm using the correct profile, and I only need to configure the two parts I mentioned?
So when you test smartscreentestrating2 site you get it blocked before opening the Defender App?

**Comment by BarbieAction** [comment]
@AFjolle Thank you so much, not sure how I can pm you on github, but would love it if you could help me check this over teams when you have time.

**Comment by AFjolle** [comment]
@BarbieAction 
You should be able to grab my email from my Github profile now :-)

**Comment by ThwinAg** [comment]
I got the same issue. Right  Control Filter and config profile for supervised are applied to my test device  but I still need to login for ms defender to work . Does anyone get it working as we expect. if so , can you provide me the process to set up Supervised iOS Zero-Touch Defender Deployment?
