### ISSUE TITLE
Sensitivity Labels - US Government Community (GCC) Availability

### ISSUE THREAD

**Issue by UserX12345** [MicrosoftDocs/microsoft-365-docs#1056]
When will this feature be available to US Government Community (GCC) tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Overview of sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@UserX12345 We can't provide dates here, but I am looking into where you can monitor the status of this release.

**Comment by cabailey** [comment]
@UserX12345 I've reached out to our marketing team who owns the M365 roadmap but in the meantime, I also found this UserVoice entry where I encourage you to vote on it and you can also monitor for updates: https://msip.uservoice.com/forums/600097-azure-information-protection/suggestions/39408979-unified-sensitivity-labels-in-the-government-cloud
