### ISSUE TITLE
Does this format collapsed?

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/microsoft-365-docs#10566]
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide

----------------
Important

Defender for Endpoint Plan 1 includes only the following manual response actions:

- Run antivirus scan
- Isolate device
- Stop and quarantine a file
- _**Add an indicator to block or allow a file Microsoft Defender for Business does not include the "Stop and quarantine a file" action at this time. Your subscription must include Defender for Endpoint Plan 2 to have all of the response actions described in this article.**_
----------------

Is the following correct?

----------------
Important

Defender for Endpoint Plan 1 includes only the following manual response actions:

- Run antivirus scan
- Isolate device
- Stop and quarantine a file
- _**Add an indicator to block or allow a file.
Microsoft Defender for Business does not include the "Stop and quarantine a file" action at this time.
Your subscription must include Defender for Endpoint Plan 2 to have all of the response actions described in this article.**_
----------------

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb7742-1171-00f4-ab40-6bcc479078ca
* Version Independent ID: 9a79f573-5f20-0e4c-822e-8af4ebf65422
* Content: [Take response actions on a device in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/respond-machine-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/respond-machine-alerts.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@takeakitake Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10609

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @takeakitake Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
