### ISSUE TITLE
GitHub Website Feedback/Suggestions

### ISSUE THREAD

**Issue by BillyAlbornoz1** [MicrosoftDocs/microsoft-365-docs#10561]
Since there weren't any forms of video-tutorials that would all have all been able to explain as specifically as possible about the ways that this type of site, GitHub, itself in particular actually works, then there should all always be any forms of media and visual demonstrations shown posted all on up on this type of site, GitHub, itself in particular that would all always be able to explain as specifically as possible about the reasons for why it is all always as important as ever nowadays, today in general that all of these forms of media and visual demonstrations all always make sure to explain the very best that they all ever could about all always making sure that there are all always any forms of video-tutorials that would all always be able to talk about the complete history of this type of site and the complete history of the type of company that actually created it, GitHub, itself in particular as well as the ways that both of these types of industries have all actually been looking and working nowadays, today in general in comparison to the ways that they all had all been looking and working way back then during the times of when they all had all first originated and so on and so forth. All of these types of things should all also all always make sure to go for showing any forms of video-tutorials about the ways that this type of company, GitHub, itself in particular actually works as well as the ways that the type of site that it created actually works right smack alongside with the ways that any types of users in general and all types of users in general could all always be able to learn and understand about the ways of actually being able to understand how to navigate through a site like this type itself in particular in just as short and simple of processes as possible no matter what types of new types of features are all ever added to it in order to make it work in the very best darn ways that it all ever could in general and all. Lastly, all of the forms of media and visual demonstrations mentioned way earlier in the beginning as well as all of the forms of video-tutorials mentioned right smack in the middle of all of this feedback should all always be translated into as many different types of worldwide foreign languages as possible and everything.

**Comment by yogkumgit** [comment]
@tiburd Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
@BillyAlbornoz1 
Although we appreciate your time and effort in providing suggestions for general improvements, this feedback system is designed for feedback about specific documentation. 
Thanks!
