### ISSUE TITLE
I can't change from "month to month" billing to annual billing for my subscription

### ISSUE THREAD

**Issue by djmrky** [MicrosoftDocs/microsoft-365-docs#10569]
Hi, I wanted to change the billing frequency, but 
**Edit billing frequency" option is grayed out.**

How can I do this?

I have the
"Microsoft 365 Business Basic (Month to Month)"
subscription

Thanks in advance

![image](https://user-images.githubusercontent.com/29006279/209667764-38325e91-5723-49e3-a616-146611ff50e1.png)

**Comment by msbemba** [comment]
@djmrky Thank you for your feedback. This could be due to a billing issue and I'd recommend you contact the billing team via the need help section on the admin center so that they can assist you.

Hope this helps!

Thanks
Sri
