### ISSUE TITLE
Microsoft Myanmar

### ISSUE THREAD

**Issue by BreakerZoeBurma** [MicrosoftDocs/microsoft-365-docs#10571]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 293f9fb8-bc6a-47ee-dbbe-ec60d9c6cb75
* Version Independent ID: a7b41845-3da9-4c3e-8222-d47109e9a746
* Content: [Find Microsoft 365 for business support phone numbers by country or region - Microsoft 365 admin](https://learn.microsoft.com/en-gb/microsoft-365/admin/support-contact-info?view=o365-worldwide&source=docs#myanmar)
* Content Source: [microsoft-365/admin/support-contact-info.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support-contact-info.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by denisebmsft** [comment]
Hello @BreakerZoeBurma. Do you have any feedback or questions for us?
