### ISSUE TITLE
Enable the troubleshooting mode steps no 4 screenshot inconsistency

### ISSUE THREAD

**Issue by AndNovian** [MicrosoftDocs/microsoft-365-docs#10578]
Steps no 4 is showing "The device page shows the **device is now in troubleshooting mode**.", however screenshot is showing **Troubleshooting mode is pending**, inconsistent information + screenshot

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Version Independent ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Content: [Get started with troubleshooting mode in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by AndNovian** [comment]
![image](https://user-images.githubusercontent.com/114455998/209902058-f956b34a-bf81-47a2-baab-0fe1aebf3260.png)

**Comment by msbemba** [comment]
@AndNovian Thank you for your feedback. I'll change the screenshot and update the document shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@AndNovian Thank you for your feedback. We have changed the screenshot via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10761

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AndNovian Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
