### ISSUE TITLE
Incorrect information about versions getting copied to Preservation Hold Library

### ISSUE THREAD

**Issue by Jvasil** [MicrosoftDocs/microsoft-365-docs#1057]
The following statement under the  "How a retention policy works with document versions in a site collection" section of this article is incorrect.. 
"Each time a document subject to a hold or retain policy is edited, a version is copied to the Preservation Hold library. "

Item and document versions are actually retained within the version history of the items and documents themselves (within the list and libraries). 
Versions do "not" get copied to the Preservation Hold Library when an item or document is edited. 
Versions only get copied to the Preservation Hold Library when an item is deleted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Jvasil  Thanks for your feedback that was sent to the engineering team.  They have now updated this page for the corrections so I'll close this issue, but please reopen it if you think your comments are not addressed.
