### ISSUE TITLE
Questions on M365 F1 plan Teams meeting capabilities

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/microsoft-365-docs#10570]
Our customer would like to know Microsoft Teams meeting capactity of M365 F1 plan, specifically for the below:

Participant capacity
Maximum group meeting duration
Maximum one-on-one meeting duration

Any guidance would be of great help!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3d7b845-c6f9-0d61-d1de-34996a06df72
* Version Independent ID: d3d7b845-c6f9-0d61-d1de-34996a06df72
* Content: [Understand frontline worker user types and licensing - Microsoft 365 for frontline workers](https://learn.microsoft.com/en-us/microsoft-365/frontline/flw-licensing-options?view=o365-worldwide)
* Content Source: [microsoft-365/frontline/flw-licensing-options.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/frontline/flw-licensing-options.md)
* Service: **microsoft-365-frontline**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by Balamurugan-dot** [comment]
Hi Team, Any further update please?

**Comment by msbemba** [comment]
@Balamurugan-dot Thank you for your feedback. The limitations/ capacity for F1 licenses remain the same

https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams talks about this in detail. I have also added this as a related topic to this document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10614

Thanks
Sri

**Comment by Balamurugan-dot** [comment]
Hi Sriman,

Thank you for the answers.

With regard to the below asks, I assume it remains same as mentioned here<https://www.microsoft.com/en-us/microsoft-teams/compare-microsoft-teams-options?activetab=pivot:primaryr1> and per the below screenshot. Could you please confirm this one too?

Maximum group meeting duration
Maximum one-on-one meeting duration

                                                                        [Graphical user interface, application  Description automatically generated]
***@***.***
Regards,
B.G

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Balamurugan-dot That is correct. It remains the same for the Maximum group meeting duration and Maximum one-on-one meeting duration as well.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Balamurugan-dot Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
