### ISSUE TITLE
please note expected wait time for secure score to update after policy change

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#10577]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75a2c77d-f8c2-b663-57a1-1b1ec8565e89
* Version Independent ID: 69cc2b0f-d0d0-d4b1-8cb9-13c246d67e70
* Content: [Assess your security posture through Microsoft Secure Score](https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score-improvement-actions?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-secure-score-improvement-actions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-secure-score-improvement-actions.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@gkens Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10613

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gkens Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
