### ISSUE TITLE
ASR Exclusion pr rule documentation missing.

### ISSUE THREAD

**Issue by thomasforde** [MicrosoftDocs/microsoft-365-docs#10588]
_"You can specify individual files or folders (using folder paths or fully qualified resource names), **but you can't specify which rules the exclusions apply to.** "_

Information about the ASR Exclusioin pr rule is missing. No information about how it works, and if it works at all. Search blognet and techcommunity reveals little to no information about this new rule...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by yogkumgit** [comment]
@jweston-1 Please help us in resolving this issue. Thanks

**Comment by bweston-8** [comment]
Fixed as follows:
Removed outdated statement. Added link to location where per-rule exclusions are documented, as follows:

REMOVED:
{ but you can't specify which rules the exclusions apply to }

ADDED:
{ For information about per-rule exclusions, see: [Configure ASR rules per-rule exclusions](attack-surface-reduction-rules-deployment-test#configure-asr-rules-per-rule-exclusions). }

Changes should be live by about 10:30 PST tomorrow morning.
