### ISSUE TITLE
Mailbox retention reduced from 183 dya to 30 days

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#10582]
The following section needs updating because Microsoft changed the retention period for inactive mailboxes from 183 days to 30 days in August 2022. message Center change MC411428 (August 8, 2022).

> Delete an inactive mailbox
> If you no longer need to retain the contents of an inactive mailbox, you can permanently delete the inactive mailbox by removing the hold applied to the inactive mailbox. The mailbox will be retained for 183 days after you remove the hold or retention policy and be recoverable during that time. After 183 days, the mailbox will be marked for permanent deletion, and the mailbox will become non-recoverable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7108464d-597a-c79d-cac8-94e35d9dd3d0
* Version Independent ID: ba0d3744-707d-c506-47f4-83519022d4cb
* Content: [Create and manage inactive mailboxes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-and-manage-inactive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@nikki-c  Thanks for flagging!  Yes, the reduction in the number of days got updated in a couple of places (https://learn.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365 and https://learn.microsoft.com/en-us/microsoft-365/compliance/delete-an-inactive-mailbox) but missed this further reference.  Good example of the dangers of having technical details in multiple places. and now removed from this page.
