### ISSUE TITLE
Escalation Process

### ISSUE THREAD

**Issue by twilight-moon** [MicrosoftDocs/microsoft-365-docs#10584]
Please add instructions on how to contact someone to speed up the process. I've been waiting a week. If you need a registration/ssn please give a number to call or a form to fill out and I can provide that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4e2ac78-e08b-d7c8-5eec-baf9e9c13b62
* Version Independent ID: 66014f69-00c9-0e9b-fe0a-d0e10f2ca5eb
* Content: [About registration numbers and under-review notifications](https://learn.microsoft.com/en-US/microsoft-365/commerce/about-registration-numbers?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/commerce/about-registration-numbers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/about-registration-numbers.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@twilight-moon Thank you for your feedback. The usual process does not take a week. However, if you would like to escalate you can do so by creating a support ticket via the need help section on the admin center so that an engineer can resolve or escalate the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @twilight-moon Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
