### ISSUE TITLE
Use 'matches these text patterns' or 'include any of these words' under 'Use mail flow rules'

### ISSUE THREAD

**Issue by Borgquite** [MicrosoftDocs/microsoft-365-docs#10599]
Under **Use mail flow rules** the documentation states to create a condition as follows:

> Mail flow rule condition: A message header > **includes any of these words** > Header name: Authentication-Results > Header value: dmarc=pass or dmarc=bestguesspass.

However the screenshot shown under action 4 shows the rule created with 'header matches' instead of 'header includes' which is the outcome when selecting a different mail flow rule condition:

> Mail flow rule condition: A message header > **matches these text patterns** > Header name: Authentication-Results > Header value: dmarc=pass or dmarc=bestguesspass.

Please can the documentation be consistent, so that it either advises 'includes any of these words' and 'header includes' in the screenshot, _or_ 'matches these text patterns' and 'header matches' in the screenshot, depending on what the best option to use is (possibly 'matches these text patterns' and 'header matches')?

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Borgquite, the screenshot was old, using the classic EAC. I updated the screenshot to match the text in the new EAC.

Any condition or exception that has 'text patterns' in the name means regular expressions (RegEx). There isn't much difference between 'includes any of these words' and 'matches these text patterns' when you use plain text letters and numbers. But even a rather benign character like a period means something in RegEx, so you would need to account for that.

Use 'includes any of these words' if you're going to use discreet text values and use 'matches these text patterns' if you're going to use a RegEx expression.

Does that help?

**Comment by Borgquite** [comment]
@chrisda Thanks for this & the clarification - appreciated :)
