### ISSUE TITLE
Change domain instructions in Microsoft Support Documentation could be improved

### ISSUE THREAD

**Issue by ThomasThatcher** [MicrosoftDocs/microsoft-365-docs#10592]
Instructions under "Change your email address to use your custom domain using the Microsoft 365 admin center
" title may confuse users.

https://learn.microsoft.com/en-us/microsoft-365/admin/email/change-email-address?view=o365-worldwide

Step 1 and 2 explain that one must navigate to https://admin.microsoft.com, click Setup, and then they can add a domain name.

There is a setup button on that page. However, there is no option to set up a new domain name unless you click on "View all on the Setup page". The option to set up a domain name is also no longer under Domains, it's under "Sign-in and security", and it's called "Get your custom domain set up"

The steps _could_ be amended like so, to make the process clearer.

1. Navigate to https://admin.microsoft.com/
2. Click on the drawer ("Hamburger") icon next to your organisation's name at the top left of the page
3. Click Setup
4. Click "Get your custom domain set up" under "Sign-in and security"
5. ...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1394eba-4e78-2fd6-84f3-4ee64aedab51
* Version Independent ID: 0ba9ff8c-20a8-58a9-dce7-a3bb0627c134
* Content: [Change your email address to use your custom domain - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/change-email-address?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/change-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/change-email-address.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**
![2023_01_04_13_20_03_Home_Microsoft_365_admin_center](https://user-images.githubusercontent.com/5836427/210473385-d7b34598-a73c-4359-9605-de79db6bfc56.png)
![2023_01_04_13_20_32_Home_Microsoft_365_admin_center](https://user-images.githubusercontent.com/5836427/210473395-d6b785f9-a30a-42da-813b-e9f2b8af3bf5.png)

**Comment by msbemba** [comment]
@ThomasThatcher Thank you for your feedback. I was able to navigate via Settings-->Domains

We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10615

Once the author approves, the changes will be live.

Thanks
Sri
