### ISSUE TITLE
Template not there

### ISSUE THREAD

**Issue by GTAdoum** [MicrosoftDocs/microsoft-365-docs#10590]
[Enter feedback here]
On the Active Users in O365 admin panel, there are no Templates link anywhere to click on.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0a03342-9a4b-cf1d-9a3b-7bdee0fe6b09
* Version Independent ID: 260c8359-f319-0647-ab77-a594ec872b2b
* Content: [Create and use a template to add users - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/create-and-use-a-template-to-add-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/create-and-use-a-template-to-add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/create-and-use-a-template-to-add-users.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@GTAdoum Thank you for your feedback. I was able to find the option under users-->active users

![image](https://user-images.githubusercontent.com/45987684/211024483-5d608c0d-9e1c-496a-956a-50970e85203c.png)


If you continue to have this problem, I'd recommend you contact Microsoft support via the need help link so that a support engineer can assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GTAdoum Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GTAdoum** [comment]
I discovered that it depends on the user, the access that have been defined for it.  My admin user did not have access to templates, I had to use another admin user that had all the access.
