### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by TeamTerry** [MicrosoftDocs/microsoft-365-docs#106]
The link for - Cloud platform roadmap - does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac3a55f-8896-66f4-9f61-3b03abad73ca
* Version Independent ID: 2983f37d-44e7-d5fe-b2b1-acac599f26a3
* Content: [Microsoft 365 Enterprise overview](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-overview)
* Content Source: [microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/microsoft-365-overview.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@TeamTerry, I removed the link. Thanks for letting us know.

**Comment by robmazz** [comment]
Closing this as resolved.
