### ISSUE TITLE
The provided urls don't work while old versions are working fine.

### ISSUE THREAD

**Issue by VincentXu2021** [MicrosoftDocs/microsoft-365-docs#10603]
https://graph.microsoft.com/v1.0/security/ediscovery/cases, this doesn't work for me. It gets 400 bad request error.
However, this is working fine: https://graph.microsoft.com/beta/compliance/ediscovery/cases.

I checked, url with "v1.0/security" doesn't work.
Instead,  url with "beta/compliance" is working fine.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc20a329-2484-3a90-1843-143dc24a8959
* Version Independent ID: dc20a329-2484-3a90-1843-143dc24a8959
* Content: [Search for and delete chat messages in Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-search-and-delete-teams-chat-messages?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-search-and-delete-teams-chat-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-search-and-delete-teams-chat-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@VincentXu2021 Thank you for your feedback. I shall test both the GET requests and update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@VincentXu2021 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10703

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @VincentXu2021 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
