### ISSUE TITLE
Excel spreadsheet download, extra details requested.

### ISSUE THREAD

**Issue by nicolasblank** [MicrosoftDocs/microsoft-365-docs#1060]
[Hi folks, The Excel document supplied is lovely with lots of detail, however, it is positioned to "track progress with stakeholders and teams". Looking at the tools released by MS aka.ms/CAF, aka.ms/adopt, several guided scenarios are suggested as to how to engage with teams and what to track. May I suggest two changes, 1. extra columns for "Percent Complete", "Team(s)", "Owner" or whatever columns would most suit the authors in terms of their experience with working with customers, 2. another sheet with some examples of items that are tracked. 
I'm suggesting these changes as a customer-facing consultant so that the spreadsheet is ready to go from download  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 734ff6a2-959a-b862-a691-54410031cb71
* Version Independent ID: 04f70373-d24c-5c48-5c13-1dfa5e2ddd4d
* Content: [Microsoft 365 Security for Business Decision Makers (BDMs)](https://docs.microsoft.com/en-us/microsoft-365/security/microsoft-365-security-for-bdm#feedback)
* Content Source: [microsoft-365/security/Microsoft-365-security-for-bdm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/Microsoft-365-security-for-bdm.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@nicolasblank - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
