### ISSUE TITLE
Reference to appropriate Defender for Cloud in schema reference missing.

### ISSUE THREAD

**Issue by davi-cruz** [MicrosoftDocs/microsoft-365-docs#10619]
Both `IdentityLogonEvents` and `DeviceLogonEvents` articles in this documentation refers to a Defender for Cloud schema reference, in order to get more information about events types as Tip below:

> For detailed information about the events types (`ActionType` values) supported by a table, use the built-in schema reference available in the Defender for Cloud.

The problem is that, besides the documents lacks the link for easier reference, I couldn't find any article in Defender for Cloud nor any other Defender and/or Sentinel product that could help answering this question.

- DeviceLogonEvents Content: [DeviceLogonEvents table in the advanced hunting schema](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-devicelogonevents-table?view=o365-worldwide)

Any guidance would be very appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ee4abdf-2875-e47e-9f96-ea3ae4b5a864
* Version Independent ID: 556d368a-3ca3-7f64-7cc2-4d8332ea8fd2
* Content: [IdentityLogonEvents table in the advanced hunting schema](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-identitylogonevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-identitylogonevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-identitylogonevents-table.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@schmurky Please hep us in resolving this issue. Thanks

**Comment by schmurky** [comment]
I will fix this. This should be Microsoft 365 Defender.

**Comment by schmurky** [comment]
Corrected in this PR: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/18553, if you can't view kindly wait for the updates tomorrow.
