### ISSUE TITLE
No information to correct incorrectly flagged malware messages (all EPUB attachments in our case)

### ISSUE THREAD

**Issue by developer-controls** [MicrosoftDocs/microsoft-365-docs#10618]
I am trying to find the information to correct overzealous flagging of legit messages as malware. In our case, Exchange is quarantining all emails with EPUB attachments as malware. The same messages do go through to @outlook.com (and other competing mail service) email addresses, so the problem must be specific to our tenant or Quarantine rules. Ultimately, our reason is to send EPUB files through Exchange using the API, but currently we see they're being blocked regardless of the source. 

Please update this page to include information or a link to information to address quarantine malware settings to fix improper quarantining.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e13e522a-93c8-fb88-3833-8660d8bbc71d
* Version Independent ID: 06300772-2c8c-9e1e-f777-f8adb61af136
* Content: [Quarantined email messages - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@developer-controls, the topic you referenced did contain the following statement:

 - Admins and users can report false positives to Microsoft in quarantine.

I beefed that up a bit with the following changes:

- Admins can report false positives to Microsoft from quarantine. For more information, see [Take action on quarantined email](https://learn.microsoft.com/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files#take-action-on-quarantined-email) and [Take action on quarantined files](https://learn.microsoft.com/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files#take-action-on-quarantined-files).

- Depending on the [user reported message settings](https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-user-reported-messages-files-custom-mailbox) in the organization (specifically, the **Let your organization report messages from quarantine** setting), users can report false positives to Microsoft from quarantine.

Malware is one of those things that you have some control over (i.e., you can tighten the screws by rejecting files based solely on specific extensions), but there's no skip filtering list for malware (too dangerous). I can find nothing about automatic rejection of ePub files by the service.

Does this help?

**Comment by developer-controls** [comment]
Thanks. That's interesting and does help. I have not been able to find a current Microsoft-provided list of file types that are considered unsafe (if there is a page with those extensions, including a link to it here would be even better). For some reason, the default settings for malware are treating all EPUB attachments to our messages as malware. But that's apparently an anomaly and not the intent. MS Support is investigating why this is happening in our tenant. So far, it remains a mystery.

**Comment by chrisda** [comment]
@developer-controls, I don't think anti-malware filtering rejects files based solely on type instead of the results from message/attachment scanning (heuristics, history, and/or AI results), but I could be wrong.

Where you can reject files solely based on extension is with [common attachments filtering in anti-malware policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/anti-malware-protection-about#anti-malware-policies). The filetypes that are blocked by default are the examples of filetypes that are considered unsafe (very few good reasons to send such files in email):

> ace, apk, app, appx, ani, arj, bat, cab, cmd, com, deb, dex, dll, docm, elf, exe, hta, img, iso, jar, jnlp, kext, lha, lib, library, lnk, lzh, macho, msc, msi, msix, msp, mst, pif, ppa, ppam, reg, rev, scf, scr, sct, sys, uif, vb, vbe, vbs, vxd, wsc, wsf, wsh, xll, xz, z

As you can see, they're virtually all some form of executable.

**Comment by developer-controls** [comment]
Microsoft Support has confirmed and reproduced the problem (not clear if this is specific to our tenant or many) where turning on that very anti-malware policy (the default that's on for every new tenant) causes it to reject EPUB files. Because this is not the intended behavior, this should probably not be added to this page. Now that I know it's a problem MS intends to fix, I don't feel so strongly that this needs to be better documented on these pages. 

That said, if it's not already on the page, I do suggest including that link in your last comment to the "common attachments filtering in anti-malware policies." I had been looking for that and not been able to find that list before your post here in the comments (could just be my own stupidity). A link on the page about quarantined emails to the list of extensions that will automatically be quarantined with standard filtering on would be helpful.

**Comment by developer-controls** [comment]
Maybe it's the gzip in that list -- those are no more malicious than a regular zip or 7z file, should not be blocked, and could be the same kind of container used to hold an EPUB.

**Comment by chrisda** [comment]
@developer-controls, OK. I added the following text to the Comments column for malware in the table near the bottom:

> If you turn on common attachments filtering in anti-malware policies (in the default policy or in custom policies), file attachments in email messages to the affected recipients are treated as malware based solely on the file extension. A predefined list of mostly executable file types is used by default, but you can customize the list. For more information, see [Anti-malware policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/anti-malware-protection-about#anti-malware-policies).

**Comment by developer-controls** [comment]
Thanks for the attention and edits. I do think the page is much stronger and more helpful as a result of your efforts.
