### ISSUE TITLE
BDM Definition in Opening Paragraph

### ISSUE THREAD

**Issue by nicolasblank** [MicrosoftDocs/microsoft-365-docs#1061]
The article title positions the article towards BDMs, however in reading the opening paragraph, I don't see the positioning towards the BDM, i.e. the "why" of why this article is written towards a BDM explicitly (as per the title). The article content may be followed by an Engineer, CISO, consultant, IT Manager or a BDM due to its prescriptive nature, It is not clear in the opening paragraph, why this content is specifically geared towards a BDM.
Are there choices or a decision tree which requires the strategic decision making power of a BDM?

The headings in the article suggest that they are - for the right kind of educate BDM that is, I doubt that a CFO would care about "assuming breach" - within reason that is.

**Comment by mypil** [comment]
@nicolasblank - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by nicolasblank** [comment]
Yes of course, I apologies if I’ve commented incorrectly in error, it refers to
https://docs.microsoft.com/en-us/microsoft-365/security/microsoft-365-security-for-bdm

**Comment by mypil** [comment]
@nicolasblank - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
