### ISSUE TITLE
Pages below Manage eDiscovery seem to be standalone rather than part of a tree of pages

### ISSUE THREAD

**Issue by paulohanlon** [MicrosoftDocs/microsoft-365-docs#10628]
The article links under "Manage eDiscovery" seem to be broken. When clicking a page, the page opens, but you lose the section of that page on the left hand menu. It's like the pages don't belong to the Manage eDiscovery tree but are standalone pages? To repro, expand Manage eDiscovery - eDiscovery (Premium) - Overview. The correct page opens but the left side menu resets

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe406b2-11c1-30d1-ca6f-671a1623e73e
* Version Independent ID: 2fe406b2-11c1-30d1-ca6f-671a1623e73e
* Content: [Overview of the eDiscovery (Premium) solution in Microsoft Purview - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-overview?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/ediscovery-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@paulohanlon - thanks for the feedback, this issue has been resolved.
