### ISSUE TITLE
Missing license information about Microsoft 365 Business Premium

### ISSUE THREAD

**Issue by bedo1976** [MicrosoftDocs/microsoft-365-docs#10624]
[Enter feedback here]

Hello

In the Link https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide the licences [Microsoft Defender for Office 365 plan 1 and plan 2] are mentioned.

But we are using the business premium subscription, where "Microsoft Defender for Office 365" is included:

https://www.microsoft.com/de-at/microsoft-365/business/compare-all-microsoft-365-business-products-b?ef_id=a24f3d015c08117120175eb860263ad1:G:s&OCID=AIDcmmwf9kwzdj_SEM_a24f3d015c08117120175eb860263ad1:G:s&lnkd=Bing_O365SMB_Brand&msclkid=a24f3d015c08117120175eb860263ad1

In this article it is not clear how to proceed with business premium. How can this be used? For example look at this picture, where only trial appears and we don't know if this is part of the business premium subscription or not. And how should we proceed to use Microsoft Defender for Office 365 with business premium licence?

![image](https://user-images.githubusercontent.com/46280077/211144494-f410c61e-347e-477b-a894-33e58ab3ae4e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3369738b-f096-6c2e-22d4-ee79057997c7
* Version Independent ID: d3fce773-a1e8-193a-b4fa-7f71b9ac3ea4
* Content: [Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/defender-for-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @bedo1976 and thank you for posting this issue. Take a look at these resources:

- https://learn.microsoft.com/en-us/microsoft-365/business-premium/?view=o365-worldwide
- https://learn.microsoft.com/en-us/microsoft-365/business-premium/m365bp-increase-protection?view=o365-worldwide

Microsoft 365 Business Premium includes Defender for Office 365 Plan 1 and Defender for Business. The two links I've shared above give you an overview of setting up and configuring everything, and the second link in particular focuses on Defender for Office 365 capabilities. 

If you still have questions, please let us know. Thanks again!

**Comment by denisebmsft** [comment]
Hi again @bedo1976. I thought about this issue some more last night and had a thought. Could you go to your admin center (https://admin.microsoft.com) and check what subscriptions you have? If you have an enterprise subscription alongside your Microsoft 365 Business Premium subscription, the enterprise experience would override your whole experience. Also, I'm not seeing "Endpoints" in the navigation bar, which actually should be there (considering Microsoft 365 Business Premium includes Defender for Business).

**Comment by bedo1976** [comment]
Hi Denise

 

Thanks for your Feedback. May Admin center shows from my point of view no enterprise subscription:

 



 

I only use Business Premium license:

 



 

I see here in  <https://security.microsoft.com/> https://security.microsoft.com/ Email & collaboration / Investigations only expired trial. And I thought, that I could access this feature with Office 365 Plan 1 or Business Premium:

 



 

I’ll check the other links you sent to me on the weekend.

 

Have a nice day.

Thank you.

 

Von: Denise Vangel-MSFT ***@***.***> 
Gesendet: Mittwoch, 11. Jänner 2023 18:09
An: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: bedo1976 ***@***.***>; Mention ***@***.***>
Betreff: Re: [MicrosoftDocs/microsoft-365-docs] Missing license information about Microsoft 365 Business Premium (Issue #10624)

 

Hi again @bedo1976 <https://github.com/bedo1976> . I thought about this issue some more last night and had a thought. Could you go to your admin center (https://admin.microsoft.com) and check what subscriptions you have? If you have an enterprise subscription alongside your Microsoft 365 Business Premium subscription, the enterprise experience would override your whole experience. Also, I'm not seeing "Endpoints" in the navigation bar, which actually should be there (considering Microsoft 365 Business Premium includes Defender for Business).
