### ISSUE TITLE
Issues with Ms Defender on linux.

### ISSUE THREAD

**Issue by Yebni-Sekawke** [MicrosoftDocs/microsoft-365-docs#10626]
1. observed on RedHat 6.x, init script for service has "sudo" - it is not needed

# grep -i kill /etc/init.d/mdatp
    pgrep $SERVICENAME | xargs sudo kill -9  # In case, some wdavdaemon process is not killed yet

after restart/stop of service this error appears, it cannot kill all related processes and occupies a lot of system resources (swap)

# service mdatp stop
Stopping daemon: mdatp stop/waiting
Sorry, user root is not allowed to execute '/bin/kill -9 1545 4916 5787 7357 9636 10859 14992 16673 23836 25254 28091 28309' as root on XXXXXXXX

2. file /opt/microsoft/mdatp/conf/mdatp.conf 

if I set "active = yes" to "active = no", this setting will be reverted back (to "= yes") after each reinstallation/upgrade

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bc22dbc-1c50-f45c-be48-887339dbcabc
* Version Independent ID: c4533eec-6b64-17b4-c5cd-b3d123f6169f
* Content: [Provide feedback on Microsoft 365 Defender](https://learn.microsoft.com/en-gb/microsoft-365/security/defender/feedback?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/feedback.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/feedback.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Pease help us in resolving this issue. Thanks

**Comment by Yebni-Sekawke** [comment]
well, guys, I will just close this one
:/
