### ISSUE TITLE
Duplicate sections on page

### ISSUE THREAD

**Issue by ScottWakemanRBS** [MicrosoftDocs/microsoft-365-docs#10630]
Just letting the page owners know that paragraphs 1 & 2 are nearly the same as 3 & 4. Looks like maybe an accidental copy & paste. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b3bda19-af86-20e8-92c4-ccb0caee7cd2
* Version Independent ID: cc93f793-d8bf-e508-d1c1-ddada942623d
* Content: [Share calendars with external users - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/share-calendars-with-external-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/share-calendars-with-external-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/share-calendars-with-external-users.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ScottWakemanRBS Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10702

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ScottWakemanRBS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
