### ISSUE TITLE
use of 'personal' is confusing

### ISSUE THREAD

**Issue by simonburbery** [MicrosoftDocs/microsoft-365-docs#10631]
When I think 'personal' I'm thinking Intune where it's my device and data, not the company's. I realise the intention is personal as in credit card numbers etc... almost more privacy realated?  Just suggesting that replacing 'personal' with 'sensitive' in the title and first few paragraphs would save some confusion. It does start to say 'sensitive' further down.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 479256a1-2220-1f5e-810e-363be327ccf8
* Version Independent ID: 34707182-f237-616a-eb09-572d37192473
* Content: [Monitor for leaks of personal data - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/monitor-for-leaks-of-personal-data?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/monitor-for-leaks-of-personal-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/monitor-for-leaks-of-personal-data.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by yogkumgit** [comment]
@BrendaCarter Please help us in resolving this issue. Thanks

**Comment by DMoenks** [comment]
Given that some well-known laws, such as Europe's GDPR and California's CCPA, use the term _personal data_ when referring to information such as names, email addresses and phone numbers, the term seems to fit here quite well. I agree that the switch from using _personal data_ to _sensitive data_ in the documentation seems misleading though, but this might be due to the fact that the described tools can be used to work on other sensitive information as well, such as product names, patent IDs or similar things.

**Comment by BrendaCarter** [comment]
This article can be retired. It's out of date.

**Comment by simonburbery** [comment]
Appreciate the comment. I see it is out of date now. We switched a client
to defender for office from dark trace. Previous product had a data loss
report they liked (although I've advised that data loss involves much more
than email) so was investigating MS options. We'll match it as closely as
we can with a custom power bi report.

**Comment by BrendaCarter** [comment]
@cabailey -- What is the best option for simonburbery to report on data loss for his customer? 

@simonburbery -- the current data protection content is located within these content sets:

https://learn.microsoft.com/microsoft-365/compliance/information-protection-solution
https://learn.microsoft.com/microsoft-365/solutions/data-privacy-protection

For non-Microsoft SaaS apps, you can use Microsoft Defender for Cloud to gain visibility into data loss.
https://learn.microsoft.com/security/zero-trust/integrate-saas-apps
