### ISSUE TITLE
AVG Test Virus?

### ISSUE THREAD

**Issue by JLBrocx** [MicrosoftDocs/microsoft-365-docs#10637]
Run a malware detection test on an Android device: Install any test virus app from the Google play store and verify that it gets detected by Microsoft Defender for Endpoint. Here is an example app that can be used for this test: [Test virus](https://play.google.com/store/apps/details?id=com.antivirus&hl=en_US&gl=US). Note that on Android Enterprise with a work profile, only the work profile is supported.

Is this the correct app used as a 'test virus'? I have tested installing this app on multiple Android devices using MDE and all of them installed successfully with Defender stating "no threats found in AVG AntiVirus" at time of installation.

![MicrosoftTeams-image (78)](https://user-images.githubusercontent.com/11243032/211468557-084498f8-dea7-476a-9425-e8aba117b177.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f1a5514-0ea6-abe7-8fe2-586bc31d07a5
* Version Independent ID: 1f1a5514-0ea6-abe7-8fe2-586bc31d07a5
* Content: [Microsoft Defender for Endpoint - Mobile Threat Defense](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mtd?view=o365-worldwide#pilot-evaluation)
* Content Source: [microsoft-365/security/defender-endpoint/mtd.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mtd.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @sunasing
* Microsoft Alias: **sunasing**

**Comment by msbemba** [comment]
@JLBrocx Thank you for your feedback. Yes, this is the correct app used as a 'test virus', If this is still a problem and I'd recommend you contact Microsoft support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JLBrocx Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
