### ISSUE TITLE
Compliance checklist: Denmark - link broken

### ISSUE THREAD

**Issue by karl-henrik** [MicrosoftDocs/microsoft-365-docs#1063]
Trying to access Compliance checklist: Denmark gives me the error message "Dokumentet kan ikke findes på retsinformation.dk"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 827c60d3-427d-3868-a1f7-5bcc5f34af08
* Version Independent ID: 8484bbcf-1af6-9136-2ff3-07e555dfb913
* Content: [Financial Supervisory Authority (FSA) Denmark - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-fsa-denmark)
* Content Source: [microsoft-365/compliance/offering-FSA-Denmark.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-FSA-Denmark.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@karl-henrik - thanks for the feedback, I'll investigate and update with a working link.

**Comment by robmazz** [comment]
@karl-henrik - I've updated the topic and please use this link (https://servicetrust.microsoft.com/ViewPage/TrustDocumentsV3?command=Download&downloadType=Document&downloadId=524cc66f-b292-49e9-aa14-04560401baa0&tab=7f51cb60-3d6c-11e9-b2af-7bb9f5d2d913&docTab=7f51cb60-3d6c-11e9-b2af-7bb9f5d2d913_Compliance_Guides). Thanks again for your feedback!
