### ISSUE TITLE
Prepare the target tenant by creating the Exchange Online migration endpoint and organization relationship

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#10645]
Step 2 of this section, where you run the PowerShell to create the endpoint, you may want to consider changing:

New-MigrationEndpoint -RemoteServer outlook.office.com -RemoteTenant "contoso.onmicrosoft.com" -Credentials $Credential -ExchangeRemoteMove:$true -Name "[the name of your migration endpoint]" -ApplicationId $AppId

-remotetenant to be something other than "contoso.onmicrosoft.com" which is the target tenant in the example as that generates the error: "Write-ErrorMessage : ASSERT: The resource tenant and the accessing tenant cannot be equal."  I think this needs to be the name of the source tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. As per the document the source tenant is Contoso.onmicrosoft.com and You will need to replace contoso.onmicrosoft.com in the above example with your source tenants' correct onmicrosoft.com name.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dkotars Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by CJDUWrk** [comment]
> @msbemba Thank you very much for the contribution and sharing this explanation. @dkotars Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

I do think the documentation should be updated to specifiy that the -RemoteTenant paremter should be the SOURCE tenant. This thread was helpful in figuring that out after days of searching for an answer.
