### ISSUE TITLE
Oversight on Having Owners change via Powershell impacts Last Activity Date on SharePoint Sites

### ISSUE THREAD

**Issue by zakarm1** [MicrosoftDocs/microsoft-365-docs#10643]
Everyone except external users is turned off by default on our tenant.  We don't want people using this account.  However, there are times that we need to add this account to specific site collections.  We have generated a powershell script that opens up EEEU(Everyone except external users) and creating a group, adding the EEEUaccount to the group, reassigning the group to a different owner and then closing up the EEEU again. 
In order to do all of this via powershell, we have to make the service account an admin or owner of the site collection.  We have found that updating the site collection admin/owner, it changes the **Last Activity Date** of the SharePoint site.

This will also happen when admins need to report on SharePoint Sites and in order to find what they are looking for, we have to update the site collection administrator to the account we are using to run the powershell until we get the data we are trying to report on.

We need  functionality in the UI or Power Automate that will allow us to report on SPO site collections (outside of what the admin center reports on) or not change the **Last Activity Date**  if powershell is touching the sites.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5a67cc-bf49-d25c-f89b-60dd30948f6d
* Version Independent ID: 56a98096-97f9-67d4-d2ed-befc800b6771
* Content: [Microsoft 365 admin center SharePoint site usage reports - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/sharepoint-site-usage-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@zakarm1 Thank you for your feedback. I tested and Could see that it changes the Last Activity Date of the SharePoint site. What you are requesting for is a design change, So I'd recommend leaving the feedback on our main feedback portal (https://feedbackportal.microsoft.com/) so that our product/Dev engineers can help you with this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@zakarm1 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by zakarm1** [comment]
Thank you!  I submitted feedback for this issue.  https://feedbackportal.microsoft.com/feedback/idea/6d8ec42a-8e96-ed11-a81b-6045bdaf6a9e
I was guided by the Microsoft Tech to submit in this location. My apologies if its not the correct process.
Thank you! :)
