### ISSUE TITLE
Virtual Appointments - basic features

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/microsoft-365-docs#10655]
Page states

With any Microsoft 365 license, you can use basic Virtual Appointments capabilities that make it easy to schedule and join business-to-customer meetings.

This does not appear to be correct.  Basic Virtual Appointments seems to require Bookings which is not available at A1/E1 level. 

![image](https://user-images.githubusercontent.com/55286035/211803235-0bb60922-05f7-4a6c-92e3-b4a6434e07c5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f450f2d-441b-ed2c-b1c3-2187e1da3556
* Version Independent ID: 6f450f2d-441b-ed2c-b1c3-2187e1da3556
* Content: [Virtual Appointments with Microsoft Teams - Microsoft 365 for frontline workers](https://learn.microsoft.com/en-us/microsoft-365/frontline/virtual-appointments?view=o365-worldwide)
* Content Source: [microsoft-365/frontline/virtual-appointments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/frontline/virtual-appointments.md)
* Service: **microsoft-365-frontline**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by msbemba** [comment]
@thewrabbit Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10676

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing it as per the comment in PR. Thanks
