### ISSUE TITLE
Script contains error

### ISSUE THREAD

**Issue by todd-tiffany** [MicrosoftDocs/microsoft-365-docs#10658]
The Powershell script on this page contains an error.  Both the currentStart and currentEnd variables are set to $start.  

#Start script
[DateTime]$currentStart = $start
[DateTime]$currentEnd = $start

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec0b4030-1bf8-c9ee-2710-b6fd3a38a381
* Version Independent ID: 96da3f55-b072-d222-b0a9-ebdf84a87a0f
* Content: [Use a PowerShell script to search the audit log - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-search-script?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-search-script.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-search-script.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@todd-tiffany Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10675

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @todd-tiffany Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
