### ISSUE TITLE
Text correction required

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/microsoft-365-docs#10650]
Undo user reported messages

Once a user reports a suspicious message that's delivered to the reporting mailbox, the user and admins **don't** can't undo the reported message. The user can recover the messages from their Deleted Items or Junk Email folders.

Please remove 'don't' as 'can't' is already written. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Manage submissions - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-admin?view=o365-worldwide#undo-user-reported-messages)
* Content Source: [microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-admin.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
@kumaarrahul, fixed. In the future, you too can make changes like this yourself without opening an issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing.

**Comment by kumaarrahul** [comment]
@chrisda Thanks for sharing the guide. This helps.
