### ISSUE TITLE
Groups in Identity Access Policies

### ISSUE THREAD

**Issue by SebastianAzure** [MicrosoftDocs/microsoft-365-docs#10657]
Groups
All Azure AD groups used as part of these recommendations must be created as a Microsoft 365 group not a Security group. This requirement is important for the deployment of sensitivity labels when securing documents in Microsoft Teams and SharePoint later on. For more information, see the article [Learn about groups and access rights in Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/concept-learn-about-groups#group-types)

Which Azure AD groups are we talking about here? Further explanation when they need to be M365 groups would be good. 
We wouldn't use M365 groups to include or exclude users from conditional access policies for example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b77aedd2-47a9-fcf5-3cc3-b46fe8548314
* Version Independent ID: 6942764e-b1c3-a1a1-007f-e34d44c5c696
* Content: [Common Zero Trust identity and device access policies - Microsoft 365 for enterprise - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/identity-access-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/identity-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/identity-access-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by yogkumgit** [comment]
@MicrosoftGuyJFlo Please help us in resolving this issue. Thanks

**Comment by MicrosoftGuyJFlo** [comment]
The groups are those that are mentioned in the assigning policies section that follows under include or exclude. They get reused in other articles in the guidance. #please-close
