### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by devan10** [MicrosoftDocs/microsoft-365-docs#10665]
With regards to the note: The standalone versions of Defender for Endpoint Plan 1 and Plan 2, even when they are included as part of other Microsoft 365 plans, do not include server licenses. To onboard servers to those plans, you'll need Defender for Servers Plan 1 or Plan 2 as part of the Defender for Cloud offering.

Does this mean that customers can no longer purchase Microsoft Defender for Endpoint Server SKU and have to do all provisioning through Azure Arc and Microsoft Defender for Cloud?  If so, does this make all of the documentation here irrelevant: 
 https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-ansible?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
Hello @devan10. Good catch! Thank you so much for posting this issue. I have updated our docs to reflect that either Defender for Endpoint for Servers or Defender for Servers is required. You'll see the updates live later today (at around 4 p.m. Pacific Time). Thank you for helping us improve our documentation!
