### ISSUE TITLE
I cannot sign into my Authenticator app on my phone. It asks me to retrieve the code from the app while I am on the app???

### ISSUE THREAD

**Issue by Berichicko** [MicrosoftDocs/microsoft-365-docs#10663]
[Enter feedback here]

Hello! Please help, I have used all the options https://answers.microsoft.com/en-us/msoffice/forum/all/i-cannot-sign-into-my-authenticator-app-on-my/52f7be1f-20a3-4ba4-9d90-195af75f811b?page=1  and I can't access my account

![image](https://user-images.githubusercontent.com/104761482/211886039-f6f75019-8f86-4915-827f-1c1eb0736887.png)

However, if you don't have the third option and cannot receive verification code by text message, we are very sorry for the inconvenience caused at your end. In this situation, you need to contact your Microsoft 365 admin to help you [disable Multi-factor authentication for your account](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#turn-off-legacy-per-user-mfa). Then re-enable Multi-factor authentication for your account.

You may need to reinstall the Authenticator app and then [set up the Microsoft Authenticator app again](https://support.microsoft.com/en-us/topic/use-microsoft-authenticator-with-microsoft-365-1412611f-ad8d-43ab-807c-7965e5155411#ID0EBBH=_Step_1).

For your reference: [How do I find my Microsoft 365 admin?](https://support.microsoft.com/en-us/office/how-do-i-find-my-microsoft-365-admin-59b8e361-dbb6-407f-8ac3-a30889e7b99b)

**Please,  disable Multi-factor authentication for my account:**   aliaksandr@testpro.io

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Version Independent ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Content: [Microsoft 365 admin center - Overview - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide#who-has-admin-permissions-in-my-business)
* Content Source: [microsoft-365/admin/admin-overview/admin-center-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-center-overview.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@Berichicko Thank you for your feedback. I wish I could help you out, however, since this is a technical query it needs to be routed to the support team. I'd request you contact Microsoft support over the phone to resolve the issue. https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide#phone-support 

Hope this helps!

Thanks
Sri

**Comment by Berichicko** [comment]
> @Berichicko Thank you for your feedback. I wish I could help you out, however, since this is a technical query it needs to be routed to the support team. I'd request you contact Microsoft support over the phone to resolve the issue. https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide#phone-support
> 
> Hope this helps!
> 
> Thanks Sri

Thanks, problem is resolved!
