### ISSUE TITLE
Shared Mailboxes

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#1066]
Could do with a section on covering shared mailboxes with ATP

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f4d9231-3dae-4719-7728-c212b6f72fec
* Version Independent ID: fb84d1b6-b388-553f-c707-baa06c78e072
* Content: [Office 365 ATP Safe Links - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/atp-safe-links)
* Content Source: [microsoft-365/security/office-365-security/atp-safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-safe-links.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@aldoug Thank you for your feedback. This document pertains only to Office 365 ATP Safe Links. We have the service description link in this document So people know the licensing requirements for using safe links.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@aldoug  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
