### ISSUE TITLE
more details

### ISSUE THREAD

**Issue by hsantan** [MicrosoftDocs/microsoft-365-docs#10661]
please submit more details what's the itens is covered by User Activities report. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f635544-505f-fdfa-9a4a-64eb2ea5c4f6
* Version Independent ID: 2f635544-505f-fdfa-9a4a-64eb2ea5c4f6
* Content: [Microsoft 365 admin center Viva Learning activity reports - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/viva-learning-activity?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/viva-learning-activity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/viva-learning-activity.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@hsantan Thank you for your feedback. I'll update the document with more details.

Thanks
Sri

**Comment by msbemba** [comment]
@hsantan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10759

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @hsantan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
