### ISSUE TITLE
Edit billing frequency is grayed out so I cannot change it

### ISSUE THREAD

**Issue by rivettp** [MicrosoftDocs/microsoft-365-docs#10671]
I'm trying to save money by switching to annual billing from monthly for my single user Microsoft 3655 Basic. 
It's already wasted 15 minutes of my time, which, at my hourly rate, is pretty close to the amount I'd save, so about to give up. 
I cannot believe you make something so basic so hard: please think of the small business owner like me. You're doing all this sophisticated AI stuff but cannot even let me change my billing frequency!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49d66f21-cff3-bb96-df38-6f67d95eb6cf
* Version Independent ID: 00256bad-f01c-02a6-9554-a0be1ce933ea
* Content: [Change your billing frequency](https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-payment-frequency?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-payment-frequency.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-payment-frequency.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@rivettp Thank you for your feedback. The Edit billing frequency should not be grayed out. If it is grayed out, then there is a good chance the permissions granted to your account are not enough. I'd recommend you contact the billing team via the need help section on the admin center so that the support engineer can assist you in fixing and changing the frequency.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rivettp Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
