### ISSUE TITLE
What is EFV:NLI?

### ISSUE THREAD

**Issue by freakynl** [MicrosoftDocs/microsoft-365-docs#1067]
What is EFV:NLI?

And NO, it has NOT been answered here: https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/211

Closing something w/o an answer does NOT equate to an answer.

If you're wondering about how awesome you are with regards to anti-spam, please check here: https://github.com/mailcow/mailcow-dockerized/issues/2851

That should say enough...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers#feedback)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by Lewis2z** [comment]
I would also like to know the answer to this issue! Everything in my email (that I can see) is passing the necessary spam filter checks, yet it is still ending up in Spam. Other email providers are correctly allowing the email through into inbox.

How can Microsoft not even know the answer to this?!

**Comment by TekBear** [comment]
This note "Other fields in this header are used exclusively by the Microsoft anti-spam team for diagnostic purposes." is too easy to miss. If a code *EFV:NLI* is exposed to the end user it needs to be in you main you list of codes so it can quickly find it through a search engine. It is extremely time wasting to go hunting for codes not listed. Being told the foot note says all other codes not listed are Microsoft internal diagnostics is not acceptable. When searching for codes you need to find the right document; skim the code table. Reading document footnotes is not the way to present this information effectively - I have . I wasted significant time reading several docs on how spam detection process works I am still unclear, and then reading Github issues asking about "EFV:NLI" which is the only place the code is mentioned, trying to find an answer. Why make diagnosing so difficult - for example: put an item in your code table "EFV:* or other values:    Microsoft anti-spam team diagnostic code not indicator of why the item was flagged as spam". Would that be accurate because I am still unclear about it?  An entry like that at the end of table  is the kind of information that would really be useful and EASY TO FIND because that is the place you expect to find it. There is a finite (??) number of codes that should be clearly defined somewhere (that includes the MS Microsoft anti-spam team diagnostic codes). Why is that not a better solution?

**Comment by TekBear** [comment]
My suggested amendment to the document:
Put an item at END of the code table "EFV:NFI or other values:    Microsoft anti-spam team diagnostic code internal use AND not indicator to the end user of why the item was flagged as spam". 

Would that be accurate because I am still unclear if your anti-spam team diagnostic code categorically are to be ignored by the end user trying to establish the reason for email being sent to the spam folder. An entry like that at the end of table is the kind of information that would really be useful and EASY TO FIND, because that is the place you expect to find it. There is a finite (??) number of codes that should be clearly defined somewhere (that includes the MS anti-spam team diagnostic codes). 

Why is that not a better solution?

This note "Other fields in this header are used exclusively by the Microsoft anti-spam team for diagnostic purposes." in your document is too easy to miss. If a code *EFV:NLI* is exposed to the end user it needs to be in the main table of codes so it can be quickly found through a search engine looking for the code value. It is extremely time wasting to go hunting for codes not listed. When your looking at document first time it starts by skimming the code table and working back from there. All information about codes (and exception cases) belongs in the code table. Reading Github issues asking about "EFV:NLI" was the only place the code is mentioned in trying to find an answer. 


(I have I wasted significant time reading several docs on how spam detection process works I am still unclear what I need to check to stop certain mail items incorrectly going to the spam folder. The reason I am reading these docs is to try and determine why my mail is going into spam. I find this is not clearly defined.)

**Comment by securityvoid** [comment]
As a suggestion; it would be great if Microsoft created a tool that would decipher why a message failed and give more details.

It could work a number of different ways:
1) You cut and paste the X-Forefront-Antispam-Report into a website and some tool would parse it and list the reasons why the message failed.

2) You could forward the failed message as an attachment to a special email address and it could give back a report as to why it failed.

3) Outlook could have a feature that would read the header of a message in Junk and give a detailed output / report as to why the message failed.

The above would likely be much easier to keep up-to-date than with the documentation for the individual fields. I feel like every time I've checked this header in the last three years its had one new field or something that changed. That gives a moving target from a Doc standpoint.

**Comment by mypil** [comment]
Related to issues: #486 #810

**Comment by oost1971** [comment]
TODAY/This morning:
X-Forefront-Antispam-Report
EFV:NLI;
X-MS-Exchange-Organization-AuthSource
VE1EUR01FT045.eop-EUR01.prod.protection.outlook.com
X-Microsoft-Antispam-Mailbox-Delivery
abwl:0;wl:0;pcwl:0;kl:0;iwl:0;dwl:0;dkl:0;rwl:0;ucf:0;jmr:0;ex:0;auth:1;dest:J;OFR:SpamFilterAuthJ;ENG:(5062000261)(5061607266)(5061608174)(4900115)(4920090)(6350004)(4950130)(4990090)(9140004);RF:JunkEmail;

**Comment by TekBear** [comment]
@securityvoid I note that https://outlook.live.com in browser offers "Message Header Analyzer" add-in function. The option needs to be on context menu of mail item listing but is only reachable by opening the mail item and select 3-dot menu.  It does provide "more details" part of your suggestion but has not helped me solve why safe listed email address, and in my contact list still end up in junk folder. It is a baby step towards your suggestion.  
[Image: Message Header Analyzer](https://imgur.com/TcUc6g7)

**Comment by freedompower** [comment]
All the emails comming from our new serveur get set to spam on Outlook, it's been like that for 5 weeks... _still no explanation_ for "**EFV:NLI**", and Microsoft is not doing anything about it. We have tried everything. What the hell Microsoft??? We are not on any blacklist, we have dmarc, dkim, spf1, all that! Such a bad company, I hope MSFT crashes.

**Comment by securityvoid** [comment]
> Message Header Analyzer

Its apparently available in Outlook as well if you search "Get Plugins", and also has [a website here](https://mha.azurewebsites.net/).

It at least makes it faster / easier to read the headers; though it doesn't look like the anti-spam tab really goes into most of the headers.

Its something though, thanks!

**Comment by securityvoid** [comment]
@freedompower 
> _still no explanation_ for "**EFV:NLI**"

I do not know what that means, but I do not think it matters for spam. I can at least tell you that messages that aren't flagged as spam in my mailbox have "EFV" set to "NLI".

If you can post your full X-Forefront-Antispam-Report header we might be able to help you figure it out.

**Comment by freedompower** [comment]
`1	MIME-Version	1.0
2	Received	from DB8P191MB1110.EURP191.PROD.OUTLOOK.COM (2603:10a6:800:7d::17) by VI1P191MB0477.EURP191.PROD.OUTLOOK.COM with HTTPS via VI1PR0801CA0073.EURPRD08.PROD.OUTLOOK.COM; Wed, 12 Feb 2020 13:34:53 +0000
3	Received	from AM6P191CA0023.EURP191.PROD.OUTLOOK.COM (2603:10a6:209:8b::36) by DB8P191MB1110.EURP191.PROD.OUTLOOK.COM (2603:10a6:10:16c::10) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.2707.21; Wed, 12 Feb 2020 13:34:52 +0000
4	Received	from HE1EUR02FT028.eop-EUR02.prod.protection.outlook.com (2a01:111:f400:7e05::209) by AM6P191CA0023.outlook.office365.com (2603:10a6:209:8b::36) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.2707.23 via Frontend Transport; Wed, 12 Feb 2020 13:34:52 +0000
5	Authentication-Results	spf=pass (sender IP is 51.79.72.138) smtp.mailfrom=saintarnould.com; glockeasymail.com; dkim=pass (signature was verified) header.d=saintarnould.com;glockeasymail.com; dmarc=pass action=none header.from=saintarnould.com;compauth=pass reason=100
6	Received-SPF	Pass (protection.outlook.com: domain of saintarnould.com designates 51.79.72.138 as permitted sender) receiver=protection.outlook.com; client-ip=51.79.72.138; helo=odedi83569.mywhc.ca;
7	Received	from odedi83569.mywhc.ca (51.79.72.138) by HE1EUR02FT028.mail.protection.outlook.com (10.152.10.102) with Microsoft SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.2729.22 via Frontend Transport; Wed, 12 Feb 2020 13:34:51 +0000
8	DKIM-Signature	v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=saintarnould.com; s=default; h=To:Date:Message-ID:From:Subject:Mime-Version :Content-Type:Sender:Reply-To:Cc:Content-Transfer-Encoding:Content-ID: Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc :Resent-Message-ID:In-Reply-To:References:List-Id:List-Help:List-Unsubscribe: List-Subscribe:List-Post:List-Owner:List-Archive; bh=06zcWXlCpO584EsyjJRhsN2t4CkMJUXmMmOF/4lqLA4=; b=rddza/4TDSQBk1dr41VmDf474q y3lDI2P7iUaCdki+oLKU69M4Xi9kXNBOvD/bIlXn9doFE80akA6YDBGBrCIsCxU+m+nNLhsjZiGCM U6r1mkxRgvef7QngTYr1wx7gGfFOgwQmjEEneTOWD6ICvANxi1wigoGNHHj4SMiR7H2G1sumse3DA OhK2QQYXO29Kok8YEEIWU1sIaepV8PV3G4z7Yq9+LyEuiE9QREAfSwDd2cDNTK0djW7gI/8ZXJI5S ECRr9szKEwja2dj6nQI5siRwEZL3car0p5Cc8e31VB+xpw/ztKBZy3Y4f4otRD7whs07XkLzLULlG OBo67yqg==;
9	Received	from mail.glockapps.com ([52.4.163.16]:61320 helo=WIN-2OPIRHUK7SP) by odedi83569.mywhc.ca with esmtpsa (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128) (Exim 4.92) (envelope-from <**REDACTED**@saintarnould.com>) id 1j1sA9-007xeJ-F5 for exosf@glockeasymail.com; Wed, 12 Feb 2020 08:34:50 -0500
10	Content-Type	multipart/alternative; boundary="Apple-Mail=_A0F836B3-E0D3-4E2B-B0AA-9376B9EC5786"
11	Subject	What is up
12	From	Erod <**REDACTED**@saintarnould.com>
13	X-API-Campaign-id	2020-02-12-13:34:03:154t
14	Message-ID	<9e10a446483c0ea949425eccb7526cf0.20200212133440224@saintarnould.com>
15	Date	Wed, 12 Feb 2020 13:34:40 GMT
16	To	exosf@glockeasymail.com
17	X-OutGoing-Spam-Status	No, score=-1.0
18	X-AntiAbuse	This header was added to track abuse, please include it with any abuse report
19	X-AntiAbuse	Primary Hostname - odedi83569.mywhc.ca
20	X-AntiAbuse	Original Domain - glockeasymail.com
21	X-AntiAbuse	Originator/Caller UID/GID - [47 12] / [47 12]
22	X-AntiAbuse	Sender Address Domain - saintarnould.com
23	X-Get-Message-Sender-Via	odedi83569.mywhc.ca: authenticated_id: **REDACTED**@saintarnould.com
24	X-Authenticated-Sender	odedi83569.mywhc.ca: **REDACTED**@saintarnould.com
25	Return-Path	**REDACTED**@saintarnould.com
26	X-MS-Exchange-Organization-ExpirationStartTime	12 Feb 2020 13:34:52.0190 (UTC)
27	X-MS-Exchange-Organization-ExpirationStartTimeReason	OriginalSubmit
28	X-MS-Exchange-Organization-ExpirationInterval	1:00:00:00.0000000
29	X-MS-Exchange-Organization-ExpirationIntervalReason	OriginalSubmit
30	X-MS-Exchange-Organization-Network-Message-Id	92c2a8fa-b2cc-47bf-8efd-08d7afc056bf
31	X-EOPAttributedMessage	0
32	X-EOPTenantAttributedMessage	4afcf95c-f67c-41d3-b723-1ecad6b02a2d:0
33	X-MS-Exchange-Organization-MessageDirectionality	Incoming
34	X-Forefront-Antispam-Report	CIP:51.79.72.138;IPV:;CTRY:CA;EFV:NLI;SFV:SPM;SFS:(199004)(189003)(86362001)(7596002)(356004)(6666004)(19273905006)(26005)(6966003)(8676002)(9786002)(36906005)(1096003)(246002)(7636002)(7116003)(36756003)(336012)(33964004)(6916009)(45080400002)(5660300002)(2616005)(956004)(3480700007)(44180200015);DIR:INB;SFP:;SCL:5;SRVR:DB8P191MB1110;H:odedi83569.mywhc.ca;FPR:;SPF:Pass;LANG:fr;PTR:odedi83569.mywhc.ca;A:1;MX:1;CAT:SPM;
35	X-MS-Exchange-Organization-AuthSource	HE1EUR02FT028.eop-EUR02.prod.protection.outlook.com
36	X-MS-Exchange-Organization-AuthAs	Anonymous
37	X-MS-PublicTrafficType	Email
38	X-MS-Office365-Filtering-Correlation-Id	92c2a8fa-b2cc-47bf-8efd-08d7afc056bf
39	X-MS-TrafficTypeDiagnostic	DB8P191MB1110:
40	X-MS-Oob-TLC-OOBClassifiers	OLM:773;
41	X-MS-Exchange-Organization-SCL	6
42	X-Microsoft-Antispam	BCL:0;
43	X-MS-Exchange-CrossTenant-OriginalArrivalTime	12 Feb 2020 13:34:51.7356 (UTC)
44	X-MS-Exchange-CrossTenant-Network-Message-Id	92c2a8fa-b2cc-47bf-8efd-08d7afc056bf
45	X-MS-Exchange-CrossTenant-Id	4afcf95c-f67c-41d3-b723-1ecad6b02a2d
46	X-MS-Exchange-CrossTenant-FromEntityHeader	Internet
47	X-MS-Exchange-Transport-CrossTenantHeadersStamped	DB8P191MB1110
48	X-MS-Exchange-Transport-EndToEndLatency	00:00:01.6690359
49	X-MS-Exchange-Processed-By-BccFoldering	15.20.2707.030
50	X-Microsoft-Antispam-Mailbox-Delivery	ucf:0;jmr:1;ex:0;auth:0;dest:J;ENG:(20160513016)(750127)(520011016)(944506383)(944626516);
51	X-Microsoft-Antispam-Message-Info	Q4jQuW4vGjMqvcfQH1dy+Zf3Qez5Kxefx0ogKBPY6JkLpchctkSKivR3DoaXEQkeX/E2q7+lMcYPnQ2UdZtxAsKi6KpXANqZzNeXI1XjMZzmJWG6EFMZXBHsMcgZMlnGWym9NKh12uJLr2yHk2LdHa37gtOTAYUJVPa0pIY90xpL5VZbbYQpl0y5mc4pHJa6MTGnj4l1DWXggH/TGAj/yaD68ORPxmfkMN3FMaNuczyG5MpQfh7W0whp4fzdWilZUXX2i5Xf+AOYnSHvYl8diYJHO+095JshLkLEJ5ZN6twI6WxWzKlmYKbwxvsJ1XX7C9hxDPY04ExAuzmkwKmTkmO2Ezs/N85nv78j5/fI5jGpvQawHMqav9mRmrcH3nQXWpN+UH4penTVjGTXNvQ+3DUG7Ad0XO7Ao4971KQf5gp2ChGwsOVk/3Ivg30wSA3N0sN/uOKh0MtSnm+nlpf7t3mm6HyZr3ikUiFaEfVTj4sYq6MXH6Xm5bY0+1AT3pj80wfuRJh/39CUbqgpIW/ptZpHfEXhFYACaq/Dz8NqwVeKO+FuZhz7KvQibCFfPzGl3M8IgEmoFgptnoNDv5FL3qNCnLJI+G+nENiIjXISGGJtsM6SFLFHbNwXX3s9PXKqvXqVtTtGEGrjBzWGMrBuTJFtWoZvV55t/WgaAhuElth6UEI6aLKN3Nvsdtf09Ccmae8/ufKNOkcqGTVXdq7wdK8qs0+eVCf0HkfWeaTetl7sJVdxv/kDt/wAbRPvNoRkvlLMviQDZ7He6ClfWI6y4xYNG+7s8e0r5+urC8Pj5qZ6ThGWuJPm0ldXnlPIQxcLQypSyt+60YBUwYk3r9Nn+pGR7x6bHHqXlDTlnZt3H7plZ4MfhfdlwW7AhZtCiGMYYlqBh9EygBPk4x8ahTdIGIlPcQ6jhEXe9lcMvIcLMoZVr7dBtO3siEMejZsswd5gRn5z10ssuPq2ugrU8VKw/R+7sgaNm5sA9Ymi8Yy3rjla7mEDU47dWhvwkrbI1TFJegUnJk1cifWhPKn4oCsi36Q60kyr+rujpV4XlIR4AddRWlAXJgxYrsHUyt23XazRwP+cmkUiQ7dG42cWmRktc2ddbFpfcTlhIXRV2dmvz6R/BCnNARGcv6wEr1axo2Nspt5CZj3x5IPc0d14mTUJsgmQlcvuBkLBDuNJhK5qELHZ1r9g3iZjAHUFKDtRh2Kumn6O/vnmDlf7bxyiIDemap00c4MxMgH92EebwyqYMZ76KPPQVLsS+AJF5WgpZ4oSMQoJsOYhvnaS9tVQoSvA6hwUtjHuyvZr4m0UxkWwlBcyPtHsCwWg5BVl9sucv3pi32BcsbvSAFoc2fd5yWh1TQKtRjX+q2yrB7iSt7uk6hGxmn/KtU9awn/gt0PdQekEAl543QXULRxgHFy5Ev2wP8ZUywbhhnUOmWbZgS1ZUUNOnqP1g8qU1BjaQbWj1jKBRmqnx8EQSHkTKH+KmFJ1YDgSSUGOGwaAkRDy600zcjFGKA4dl/Ocj0nUTZiW2IuKc8X6VmdTtZCMBvWDqGWhuA==`

**Comment by securityvoid** [comment]
> X-Forefront-Antispam-Report CIP:51.79.72.138;IPV:;CTRY:CA;EFV:NLI;SFV:SPM;SFS:(199004)(189003)(86362001)(7596002)(356004)(6666004)(19273905006)(26005)(6966003)(8676002)(9786002)(36906005)(1096003)(246002)(7636002)(7116003)(36756003)(336012)(33964004)(6916009)(45080400002)(5660300002)(2616005)(956004)(3480700007)(44180200015);DIR:INB;SFP:;SCL:5;SRVR:DB8P191MB1110;H:odedi83569.mywhc.ca;FPR:;SPF:Pass;LANG:fr;PTR:odedi83569.mywhc.ca;A:1;MX:1;CAT:SPM;


@freedompower 

SFV:SPM - This header indicates that its the content of the message that is resulting in the message being flagged as spam. [(See this page)](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers)

I believe the SFS list indicates which content filters it failed; but I have not seen those documented.

**Comment by securityvoid** [comment]
Also, SCL states the confidence level of it being Spam. I forget where I saw this documented; but I think you need to be below a 3 for it to not flag it / block it. You're at 5; which usually goes in the junk folder with a default config.

**Comment by TekBear** [comment]
@securityvoid here is another [email header set](https://pastebin.com/tNT42ium). Is there anyway I can stop this going to junk folder? (It is a from a job posting site mailing list subscription.)

Does anyone know of a guide that help decode why an email items get flagged as junk?

**Comment by oost1971** [comment]
can someone explain this more clearly ;

X-Microsoft-Antispam-Mailbox-Delivery | abwl:0;wl:0;pcwl:0;kl:0;iwl:0;dwl:0;dkl:0;rwl:0;ucf:0;jmr:0;ex:0;auth:1;dest:J;OFR:SpamFilterAuthJ;ENG:(5062000261)(5061607266)(5061608174)(4900115)(4920090)(6350004)(4950130)(4990090)(9140004);RF:JunkEmail;
-- | --

Thanks in advance, mail was dropped in unwanted folder of outlook (LIVE)
Some extra info about date/time and subject below;
4 | From | ODMH – Team HR <noreply@odmh.nl>
-- | -- | --
5 | Date | Tue, 11 Feb 2020 07:25:04 +0100
6 | Subject | Jouw sollicitatie bij de ODMH

**Comment by 851597064** [comment]
In another thread about this topic I read someone's theory that free-tier Outlook and Hotmail addresses might be 'more affected' by this problem, and I now have evidence in support of this theory: I sent two emails, both through a python script that uses Mailgun as a service provider. Earlier today I had a 10/10 from mail-tester.com using that script, btw. The first email went to a free hotmail address of mine, the second to my paid, corporate E3 Exchange Online account.

Lo and behold: the free account dumped it in Junkmail, with X-Forefront-Antispam-Report: EFV:NLI;
and the corporate account placed it in Inbox with X-Forefront-Antispam-Report:
 CIP:69.72.42.5;IPV:;CTRY:US;EFV:NLI;SFV:NSPM;SFS:(10001)(286005)(199004)

Look closely, the mysterious EFV:NLI is there in both headers with different effect. So based on this small sample I conclude:
- EFV:NLI is truly internal diagnostic and does not effect spam
- paid accounts get closer and more accurate spam detection whereas free-tier accounts do not and Microsoft errs on the side of caution by dropping them into Junk more easily.

**Comment by jasonpfraser** [comment]
I had a similar problem, trying to understand why an email was marked as SPAM. Based on my little bit of research I think the header categories are as follows.
EFV:NLI; = "Not listed on Bad IP reputation lists (refer to IPV:NFI)"
DIR:INB; = "Direction of email being filtered, in this case Inbound"
A:1; = "Which A record was used?"
MX:1; = "Which MX record was used?"
FPR:; = "Have not been able to figure this one out yet"
SFP:; = "Used by Microsoft to define if email has been sent by their High risk Delivery Pool of email servers as they thought it was outgoing spam (value if true =1501), (it is possible that this is historical?)"

The one that actually defines why the email was blocked is the "SFS:" tag, this will likely have a lot of numbers in it and they are the individual spam filtering rules. In my case I think one of them is probably triggering on use of a nickname in the subject that does not match the receiver email name (obviously these rules would be different between free and enterprise, an I am on enterprise where accounts are usually natural names). 

My "SFS:" tag read as follows "SFS:(10001)(4636009)(199004)(189003)(8676002)(33656002)(7696005)(5660300002)(9326002)(1096003)(6506007)(86362001)(496002)(52536014)(9686003)(336012)(7636002)(356004)(6916009)(26005)(246002)(8636004)(55016002)(15974865002)(1780200001);"

I am led to believe that Internal MS support teams have access to the list of rules and may be able to help you with the right support contract in place but I have not tried this. I can understand the rule descriptions are probably very messy so MS would not want them public, there is also some justification for not giving away their rules as that may help spammers (though I am personally convinced of this argument).

However I cant see any reason to obfuscate the rest of them as they are not exactly valuable IP and I think the reason provided of internal diagnostics is rubbish, anything communicating over public internet should IMHO be using approved, published, and documented protocols and headers. While originally stated for crypto, I think Kerckhoffs's principle and Shannon's maxim are valid here. Essentially, design your systems in such a way that others having knowledge of them does not give them the ability to misuse/break them.

Anyhow sorry for the long response. Basically it is unlikely that "EFV:NFI" is the cause of your issue and actually if I am correct, it should show up on all emails detected as content spam. Trying the support call path is probably your only chance but will only address the specific email as different rules will be triggered based on content. Hope that helps someone.

**Comment by mypil** [comment]
@freakynl @Lewis2z @TekBear @oost1971 @securityvoid @jasonpfraser @851597064 @freedompower - Thank you for engaging with the community here for the docs.

Please see this https://github.com/MicrosoftDocs/microsoft-365-docs/issues/486#issuecomment-540828898 from one of the authors - "Any headers not documented here are internal and used exclusively by the Microsoft anti-spam team for diagnostic purposes."

If you have some suggestions on how to make Microsoft 365 better, it would be great if you could add your voice in **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)**. I know the product teams are keeping a close tab on user feedback and feature requests that would help improve Microsoft 365.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by jas8522** [comment]
Any updates here? That UserVoice was apparently shut down. I've now seen numerous cases of Microsoft servers filtering legit messages to spam/junk without any known cause and because of the reasons identified above, we have no recourse.
