### ISSUE TITLE
Custom view, paste text into XML file, import error: "The specified custom view is not valid"

### ISSUE THREAD

**Issue by TBSJordanNash** [MicrosoftDocs/microsoft-365-docs#10689]
I followed the instructions by creating four TXT files, renamed them as specified including the XML extension. I pasted the provided XML content into each. I started Event Viewer (right-clicking on the Start button is more efficient than typing "event viewer" by the way) and clicked Action > Import Custom View.

After selecting a file, and accepting the defaults, Event Viewer returns an error "The specified custom view is not valid."

![image](https://user-images.githubusercontent.com/103598158/212335492-cee33107-7c16-4454-898b-5b072ba02bf4.png)

![image](https://user-images.githubusercontent.com/103598158/212335546-d5cecaab-a4fb-411a-9f1b-ecb9b03fe126.png)

![image](https://user-images.githubusercontent.com/103598158/212335372-0d33262e-a1e3-4cf6-8cb8-6be7cc85f889.png)

![image](https://user-images.githubusercontent.com/103598158/212335414-9d90ef06-c949-4dd3-8fc9-4d2c5943a961.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41ce74f1-3ef4-8755-21a1-ac93ba2f81d2
* Version Independent ID: 2a1e5cea-33b7-e231-878c-8bc38c51f0be
* Content: [Understand and use attack surface reduction (ASR)](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/overview-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/overview-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/overview-attack-surface-reduction.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @TBSJordanNash Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
