### ISSUE TITLE
What does it mean "Microsoft 365 Apps or Microsoft 365 Business Premium"?

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/microsoft-365-docs#10686]
What does it mean "Microsoft 365 Apps or Microsoft 365 Business Premium" in "Safe Links settings for Office apps" section?

https://learn.microsoft.com/microsoft-365/security/office-365-security/safe-links-about#safe-links-settings-for-office-apps

Microsoft 365 Apps "for enterprise" or Microsoft 365 Business Premium only? (Exclude Microsoft 365 Apps for business standalone plan?)
Microsoft 365 Apps for enterprise/business and all suite plan that include Office like Office 365 E3/Microsoft 365 Business Premium?

Please explain clearly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Version Independent ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@takeakitake, it appears that "Microsoft 365 Apps" could be changed to "Microsoft 365 Apps for enterprise" if that helps, although [this article](https://learn.microsoft.com/deployoffice/about-microsoft-365-apps) and other locations use just "Microsoft 365 Apps".

[Microsoft 365 Business Premium](https://www.microsoft.com/microsoft-365/business/microsoft-365-business-premium) is the correct term.

Those references are the licenses/products that you buy to get Office (or that are included in other licensing plans like "Microsoft 365 A5 for students"), and those versions of Office (either one) support Safe Links. For more information and to find these license values, see [Product names and service plan identifiers for licensing](https://learn.microsoft.com/azure/active-directory/enterprise-users/licensing-service-plan-reference). That big table is too wide, so use the left and right arrow keys to scroll horizontally.

I'll take suggestions for how to clarify.

**Comment by yogkumgit** [comment]
@takeakitake Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
