### ISSUE TITLE
MicrosoftTeams Module: Get-MultiGeoRegion failed to communicate over non standard port

### ISSUE THREAD

**Issue by thekamilpro** [MicrosoftDocs/microsoft-365-docs#10691]
Hello,

I've been trying to the command to check Multi-Geo status:
Get-MultiGeoRegion -EntityType user -EntityId fred.bloggs@company.com

And it errors out with "one or more errors", when running with -verbose parameter, it seems it tries to connect to migrationsvc.teams.microsoft.com over port 8653

VERBOSE: Making API call for URI: https://migrationsvc.teams.microsoft.com:8653/api/v1.0/users/fred.bloggs@company.com/region

I tried to find any sort of documentation on these command and domain however I couldn't find any. Can you please:

1. Point me out to any documentation mentioning the required domain and ports
2. Confirm whether this is in fact correct addresses

It makes it hard to justify opening firewall for the given network address and port if there's no official documentation.

I'm running module version 4.9.1

**Comment by yogkumgit** [comment]
@thekamilpro Can you please tell us to which article(s) your question applies? This will help us route this issue to the correct writer/team. Thanks

**Comment by thekamilpro** [comment]
It's this one: https://learn.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-teams-in-microsoft-365?view=o365-worldwide

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please help us in resolving this issue. Thanks

**Comment by MikePlumleyMSFT** [comment]
@thekamilpro I recommend opening a support ticket for this issue. @yogkumgit do you have the process for that?

**Comment by thekamilpro** [comment]
@MikePlumleyMSFT by the issue, do mean the actual URLs and ports used by the module?

**Comment by MikePlumleyMSFT** [comment]
@thekamilpro, I'm not aware of any documentation that I can point you to for ports and URLs. Support should be able to help you debug the error.

**Comment by thekamilpro** [comment]
@MikePlumleyMSFT how can I contact support for MicrosoftTeams module?

**Comment by MikePlumleyMSFT** [comment]
@yogkumgit do you info on how to contact support?

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Thank you very much for sharing this explanation. @thekamilpro Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Petri-X** [comment]
@thekamilpro same issue on here.
Did you found any solution for this? The main question is not actually opening the port, but if the whole PS module can work with proxy, why suddenly one CMDLet doesn't?
