### ISSUE TITLE
How often is the 'When retention period expires' event triggered per labeled item? 

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#10696]
Under the **When the flow is triggered** section, could you please clarify if the trigger is only initiated once per labeled item, or does it trigger on a recurring basis for the same item for as long as the original conditions of the trigger are still met (i.e., item is still labeled and is past the end of its retention)? E.g.  if a flow has already been triggered once and has sent an email to someone about the item, would the flow be re-triggered again later if the document is still present in the original location and is still tagged with the same label and is still past its expiry date? 

_NOTE - Labeled item above indicates an item is tagged with a retention label that is configured to retain an item and then initiate a Power Automate flow at the end of its retention period._ 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43c8da6b-a034-f4fc-db7e-e341f8adf4d5
* Version Independent ID: 43c8da6b-a034-f4fc-db7e-e341f8adf4d5
* Content: [Customize what happens at the end of the retention period - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-label-flow?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-label-flow.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-label-flow.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Yes, just like the other actions that get triggered at the end of the retention actions, running a Power Automate flow is a single occurrence with the caveat that there are built-in checks to retry if needed:

"Both the flow itself and the Microsoft 365 compliance actions in the flow are queued so that if there are any network or service delays, the flow and actions are automatically retried."

**Comment by yogkumgit** [comment]
@kstat Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
