### ISSUE TITLE
Update clarification around MC200232

### ISSUE THREAD

**Issue by Ganym3de** [MicrosoftDocs/microsoft-365-docs#1069]
The update states "If you do not want end-users to be able to access phishing email within Quarantine, then you can set a different action other than Quarantine message for phishing email in the spam filter policy." but this is a cause for concern for security especially if an organization does not have MFA setup for end users.  Suspected phishing email regardless if not high confidence should still be reviewed by an admin. Using the policy to "Send to another address" isn't the most resourceful solution as it creates another audit point for admins. Will there be a way to toggle the behaviour? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e13e522a-93c8-fb88-3833-8660d8bbc71d
* Version Independent ID: 06300772-2c8c-9e1e-f777-f8adb61af136
* Content: [Quarantine email messages in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-email-messages#feedback)
* Content Source: [microsoft-365/security/office-365-security/quarantine-email-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-email-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Ganym3de Thank you for the feedback. The update is not published on the document yet, I'll check with the author and get back to you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@Ganym3de Thank you for feedback. Looks like the update says

High confidence phishing email = no user access in quarantine (admin only); 
‘Regular’ phishing email = user access in quarantine UNLESS you configure a different action in anti-spam policies (Delete message is probably best).

![image](https://user-images.githubusercontent.com/45987684/74340147-6798fa00-4dcb-11ea-92b5-d3a1d8db1c4d.png)

Meanwhile, we are working on the document(https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-your-spam-filter-policies)  to show the new options and Change in the UI. This should soon be updated.

Hope this helps!
Thanks
Sri

**Comment by mypil** [comment]
@Ganym3de - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
