### ISSUE TITLE
Link does not work under Health Services

### ISSUE THREAD

**Issue by TeamTerry** [MicrosoftDocs/microsoft-365-docs#107]
How customers use Microsoft 365 Enterprise
-
https://www.microsoft.com/en-au/microsoft-365/blog/2018/07/16/lilly-strives-to-speed-innovation-with-help-from-microsoft-365-enterprise/?ms.o365url=lilly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 863db1df-d804-e38c-a90c-fae6a0244653
* Version Independent ID: 7d9d48a4-27a0-5bfc-a98f-8a94015dbde4
* Content: [Deploy Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/deploy-microsoft-365-enterprise)
* Content Source: [microsoft-365/enterprise/deploy-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/deploy-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
This resource is not available in your locale (en-au in the URL). I updated the link for the U.S version and should now work for you. Thanks for letting us know.

**Comment by robmazz** [comment]
@TeamTerry - Thanks for your feedback, I'll get this over to the Enterprise writing team for clarification/correction.

**Comment by robmazz** [comment]
@TeamTerry - Ignore above, I see that Joe has already commented. Closing this issue.
