### ISSUE TITLE
page size correction

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#10704]
there are references to pages of 17 x 17 (which is not a standard size of paper), and then it states Legal size, which is actually 8.5 x14. I think that the 17 x17 may be a typo and it should be 11x17 (which is typically referred to as Tabloid size), please review and correct if necessary. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1aa4-860c-6480-502f-08f610f0b9b2
* Version Independent ID: a4be1aa4-860c-6480-502f-08f610f0b9b2
* Content: [Requirements and limitations for models in Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/requirements-and-limitations?view=o365-worldwide#unstructured-document-processing)
* Content Source: [microsoft-365/syntex/requirements-and-limitations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/requirements-and-limitations.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10711

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chuckedmonson** [comment]
@DeanGross, @msbemba -- Thank you for catching and fixing. Merged these changes as part of PR #18485. Updates will be live 1/17/23 after 3:30 PM PT. Thanks again.
