### ISSUE TITLE
Request rephrasing under Prerequisites

### ISSUE THREAD

**Issue by benpaul4u** [MicrosoftDocs/microsoft-365-docs#10706]
Requesting rephrasing under Prerequisites:

Instead of "Microsoft Endpoint Configuration Manager (MECM) older than 2207. ", recommend to have something like "Microsoft Endpoint Configuration Manager (MECM) _version to be higher than_ 2207." , as "older than" seems to be confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db7a8efc-83e0-d8cf-7385-c323d3793327
* Version Independent ID: db7a8efc-83e0-d8cf-7385-c323d3793327
* Content: [Migrating servers from Microsoft Monitoring Agent to the unified solution](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/application-deployment-via-mecm?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/application-deployment-via-mecm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/application-deployment-via-mecm.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @alekyaj
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@benpaul4u thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10712

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as duplicate PR is merged. Thanks
