### ISSUE TITLE
Can you confirm step 6. under onboard instructions. The defender for endpoint has a different method as it says to use Defender ATP policy, whereas this article says to deploy it as a package

### ISSUE THREAD

**Issue by mohanra1** [MicrosoftDocs/microsoft-365-docs#10717]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d0bace4-46dc-8b93-8731-71ad5e98e298
* Version Independent ID: 1d0bace4-46dc-8b93-8731-71ad5e98e298
* Content: [Onboard Windows 10 and Windows 11 devices using Configuration Manager - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-sccm?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/device-onboarding-sccm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/device-onboarding-sccm.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by robertsteinBH** [comment]
This article still needs a thorough update. The references to SCCM 2012 are extremely out of date as this product is EOL (as referenced here (https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9228). 
The relevant MDE onboarding documentation for Configuration Manager is here: 
https://learn.microsoft.com/en-us/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection
Even if not using the built-in tools for MDE onboarding, the correct document for creating a package (to deploy a script) is here: 
https://learn.microsoft.com/en-us/mem/configmgr/apps/deploy-use/packages-and-programs

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue, Thanks

**Comment by yogkumgit** [comment]
@mohanra1 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
