### ISSUE TITLE
Script errors out - The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by TheDeuceYouSay** [MicrosoftDocs/microsoft-365-docs#10719]
Uninstalled AzureAD module, installed 2.0.2.149 AzureADPreview module and am getting this error when I run the script:

Get-AzureADDirectorySetting : The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.

as well as for:

Get-AzureADDirectorySettingTemplate
New-AzureADDirectorySetting

 $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  963

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://learn.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@TheDeuceYouSay Thank you for your feedback. I was able to test this and it works fine.

![image](https://user-images.githubusercontent.com/45987684/213712630-600ccc80-8310-4047-932c-de8d30b91dd1.png)


If you continue to have an issue, I'd recommend opening a support ticket via the need help section on the admin center.

Hope this helps!

Thanks
Sri
