### ISSUE TITLE
The Video is showing Old UI in public document..

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/microsoft-365-docs#10714]
The video under this section **"How to secure and restore email function to a suspected compromised Microsoft 365 account and mailbox**"  is showing old UI. Can you please update it or pull it completely until then? . Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 073882cd-36d0-b95a-77b2-aadd06fa34a5
* Version Independent ID: 463f2f77-3fb0-8078-5b49-878747f2842b
* Content: [Responding to a Compromised Email Account - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MithunRathinam, OK, Video link removed.

Thanks for the feedback.

Closing
