### ISSUE TITLE
The local script downloaded from purview portal still says onboarding to Microsoft defender for endpoint when it is run

### ISSUE THREAD

**Issue by mohanra1** [MicrosoftDocs/microsoft-365-docs#10718]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 453efbb0-2428-1f98-0449-bb8490620489
* Version Independent ID: 453efbb0-2428-1f98-0449-bb8490620489
* Content: [Onboard Windows 10 and Windows 11 devices using a local script - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-script?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/device-onboarding-script.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/device-onboarding-script.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mohanra1** [comment]
ALso please verify the file names in point no.9

**Comment by msbemba** [comment]
@mohanra1 Thank you for your feedback. We have fixed the file name via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10760

Once the author approves, the changes will be live.

I'm also checking the other issue and will update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mohanra1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
