### ISSUE TITLE
Conflicting information on custom domains in anti-phishing policies.

### ISSUE THREAD

**Issue by mkesler80** [MicrosoftDocs/microsoft-365-docs#10716]
There is conflicting information in this article and a second article relating to the maximum number of custom domains in the Enable Domains to Protect policy.

In the article titled "Configure anti-phishing policies in Microsoft Defender for Office 365" we have the following

     Note

     You can have a maximum of 50 domains in all anti-phishing policies.

Which seems to imply that there can only be a maximum of 50 domains across all anti-phishing policies.

In the article titled [Anti-phishing policies in Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-policies-about?view=o365-worldwide) it states:

     Note

     You can specify a maximum of 50 custom domains in each anti-phishing policy.

I'm not 100% certain which is correct, but I believe it is the second note.  Need to have that clarified and the incorrect note needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70ea08aa-4520-8f48-93e2-0ce74cd43298
* Version Independent ID: 7be23d3d-f72b-abd3-e2c4-96ff3998a59b
* Content: [Configure anti-phishing policies in Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-policies-mdo-configure?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-policies-mdo-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-policies-mdo-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mkesler80, I just tested it: the maximum is 50 domains per policy. As soon as you try to add 51, you get an error, but you can add more domains (including the same domains) to a different policy while the first policy has 50 domains.

I replaced the wrong sentence with the correct sentence so both articles now say the same thing.

**Comment by yogkumgit** [comment]
@mkesler80 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
