### ISSUE TITLE
Is setting up Azure resources/billing for the pay-as-you-go "preview" now a REQUIREMENT for Microsoft Syntex?

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#10720]
Logged in as a Global Admin attempting to setup Syntex but it seems impossible without first setting up all the Azure stuff for the pay-as-you-go preview:
![image](https://user-images.githubusercontent.com/9206808/212985500-d4293311-85fe-4502-a5f6-15ba86670815.png)

Our customer does not want to participate in this preview and doesn't really plan on using the pay-as-you-go licensing model. However, based on the message in the screenshot it seems like that's not an option.

Can someone clarify, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a699347-c700-9679-2498-f3d78e421089
* Version Independent ID: 1a699347-c700-9679-2498-f3d78e421089
* Content: [Set up Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/set-up-content-understanding?view=o365-worldwide)
* Content Source: [microsoft-365/syntex/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/set-up-content-understanding.md)
* Service: **microsoft-syntex**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@sparkitect if you have [Microsoft Syntex licenses](https://www.microsoft.com/en-us/microsoft-365/enterprise/microsoft-syntex-plan) assigned, it should not require you to enter an Azure subscription. If you have the licenses but the setup button is grayed out, then I recommend opening a support ticket.

**Comment by yogkumgit** [comment]
@sparkitect Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
