### ISSUE TITLE
Inaccurate reference

### ISSUE THREAD

**Issue by ExchRanger** [MicrosoftDocs/microsoft-365-docs#10728]
In this article there is a section titled "Reset business passwords in bulk" It references this article: https://o365info.com/manage-office-365-users-password-using/ - there is nothing in this article about resetting user's passwords in bulk. 

Reset business passwords in bulk
Use PowerShell! Check out this post by Eyal Doron: [Managing passwords with PowerShell](https://go.microsoft.com/fwlink/?linkid=853696).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa4f7db9-4faf-03f9-516c-7bb1f6dbac92
* Version Independent ID: 0a2f9a24-76e7-b889-3a75-3e2bbb5aba96
* Content: [Reset passwords - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/reset-passwords?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/reset-passwords.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/reset-passwords.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ExchRanger Thank you for your feedback. The document referenced talks about managing passwords using PowerShell and there is a section which talks about setting passwords in bulk using Powershell

![image](https://user-images.githubusercontent.com/45987684/213714868-b4b966a8-6297-403b-9d0c-0f16b7909214.png)

Hope this helps!

Thanks
Sri

**Comment by ExchRanger** [comment]
I did see that, thanks. I feel like there should be some way to reset user passwords using group membership where you can run a reset password command against users via group membership without having to do all users in the environment or resort to a .csv file. I guess that is my idea of bulk reset. Thanks for the reply. I have found a workable solution.
