### ISSUE TITLE
clarification around label application

### ISSUE THREAD

**Issue by adelaidecopland** [MicrosoftDocs/microsoft-365-docs#1072]
This is more just a request for info thing, while I understand that only one retention label can be applied at a time to an item I've read conflicting reports about whether it's possible to apply both a retention label and a sensitivity label to an item. I don't have access to an environment at the moment to test, so am hoping to get some clarification to help inform our config decisions.

**Comment by mypil** [comment]
@adelaidecopland - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@adelaidecopland - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.
