### ISSUE TITLE
Add additional "Site Collection Owners" to a personal OneDrive MS Directions Fail as written

### ISSUE THREAD

**Issue by GuidanceImp** [MicrosoftDocs/microsoft-365-docs#10732]
[Enter feedback here]

The directions specified do not work as intended.
When going to O365 Admin > SharePoint Admin Center > User Profiles > Manage User Profiles 
The intent is to select the user account right click and select "Manage Site Collection Owners".  However all attempts to add and remove access from this portal fail.

However - If your right click on the profile select "Manage Personal Site" > Select "Site Collection Administrators"  and add the user from this menu the process works.

This appears to be an issue with the portal menu and not the permissions themselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34c90550-34c3-c6de-81d4-6d85a8bc3f90
* Version Independent ID: 151fb754-7bea-f489-5115-e3551db0f303
* Content: [Step 5 - Give another employee access to OneDrive and Outlook data - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-5?view=o365-worldwide#access-a-former-users-onedrive-documents)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-5.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-5.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@GuidanceImp Thank you for your feedback. I was able to test and add and remove access works as expected. If you still have trouble making this change, please raise a support ticket via the need help section on the admin center, so that a support engineer can fix this for you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GuidanceImp Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
