### ISSUE TITLE
lastSeen API ≠ lastSeen GUI

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/microsoft-365-docs#10747]
Hi,

maybe you could add a note that:
lastSeen API ≠ lastSeen GUI

I was struggeling using the API as it didn´t match the UI and got the answer that:
lastSeen API = Last Device Update

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71010864-b3f8-23e1-33fe-496f136bf2b7
* Version Independent ID: e4c58cda-d42f-4445-3a03-6f4c8c1e6460
* Content: [Machine resource type](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Will add note.
