### ISSUE TITLE
Cross Tenant User Data Migration Licensing

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/microsoft-365-docs#10742]
The official docs (https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide) says “Cross Tenant User Data Migration is available as an add-on to the following Microsoft 365 subscription plans for **Enterprise Agreement customers**. User licenses are per migration (onetime fee). Please contact your Microsoft account team for details”.

Is this license required to migrate a customer who does not have an Enterprise Agreement?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@FernandoGualano Thank you for your feedback. This License is only available for Enterprise Agreement (EA) customers. Talk to your EA representative to get the valid price for the license.

Non-EA Customers currently do not qualify for this type of migration.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @FernandoGualano Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bnulti** [comment]
Is there a specific SKU for this license as I cannot find it across multiple CSP's?
