### ISSUE TITLE
MSCommerce completely fails to follow standard PowerShell patterns

### ISSUE THREAD

**Issue by alexbuzzbee** [MicrosoftDocs/microsoft-365-docs#1074]
I am aware that this is probably not the appropriate place to file this issue. However, I cannot find the correct location. If appropriate, I am willing to re-file this elsewhere.

The `MSCommerce` module does not follow several standard PowerShell design patterns, including the appropriate use of verbs, the singularity of nouns, and pipelining.

The cmdlet `Update-MSCommerceProductPolicy` has the wrong verb. It should be `Set-MSCommerceProductPolicy`. An alias of the old name could be used for backwards-compatibility.

The cmdlet `Get-MSCommerceProductPolicies` has a plural noun. It should be combined with `Get-MSCommerceProductPolicy` such that providing no `ProductId` returns all products. An alias of the separate cmdlet could be used for backwards-compatibility.

The cmdlet `Update-MSCommerceProductPolicy`/`Set-MSCommerceProductPolicy` does not take input from the pipeline. It should set `ValueFromPipelineByProperty` on `ProductId` so that one can pipe from `Get-MSCommerceProductPolicy` to `Set-MSCommerceProductPolicy`, and should also ensure that it has the correct split between `BeginProcessing`, `EndProcessing`, and `ProcessRecord` such that multiple objects can be piped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@alexbuzzbee Thanks. I have forwarded this feedback to the product team.
