### ISSUE TITLE
Suggestion: ansible facts instead of [distro] and [version] placeholders

### ISSUE THREAD

**Issue by jmacdone** [MicrosoftDocs/microsoft-365-docs#10741]
Perhaps use ansible facts instead of manually replacing static placeholders?  Or include it as an additional example?

```
baseurl: https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/prod/ 

repo: deb [arch=arm64,armhf,amd64] https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/prod {{ ansible_distribution_release }} main
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5b7c531-90a1-7f6b-4c1d-0a126cdea398
* Version Independent ID: 5a10f1bb-6407-d706-0b79-bf448a8eda9d
* Content: [Deploy Microsoft Defender for Endpoint on Linux with Ansible](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-ansible?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-with-ansible.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jmacdone Thank you for your feedback. We have mentioned " replace [distro] and [version] with the information you've identified."  in the document. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jmacdone Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jmacdone** [comment]
@msbemba I'm glad this helped.  I was going to take a look at the update, but it looks like the latest commit for this doc is [436291f](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/436291f3aaf3d04d3a19324885ba05db33267551) from Sept 29, 2022.   I see you opened a few pull requests today, but I don't see one for this doc. Where should I be looking?
