### ISSUE TITLE
Mistake in the "Prerequisites" table

### ISSUE THREAD

**Issue by Kentaro0kada** [MicrosoftDocs/microsoft-365-docs#10757]
[Enter feedback here]
In the "Prerequisites" table, the correct KB for Windows 10 21H2 is "KB5019275", not "KB5011563".
Could you please fix this part of the mistake?
Also, could you please add Windows 10 22H2 as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Version Independent ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Content: [Get started with troubleshooting mode in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode?view=o365-worldwide&source=docs#prerequisites)
* Content Source: [microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Kentaro0kada Thank you for your feedback. We have made changes to the KB article via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10802

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Kentaro0kada Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
