### ISSUE TITLE
Unsupported version of .NET Core 3.1 reference

### ISSUE THREAD

**Issue by calbertolazaro** [MicrosoftDocs/microsoft-365-docs#10754]
The page makes reference to deprecated version of .NET Core 3.1. 
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

The supported versions are .NET 6 and .NET 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide#build-the-project)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@calbertolazaro Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10801

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @calbertolazaro Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
