### ISSUE TITLE
French drivers license number missing?

### ISSUE THREAD

**Issue by SeanK1191** [MicrosoftDocs/microsoft-365-docs#1075]
Looks like there is suppose to be a section for French driving license number where the Finland passport number section is.

**Comment by mypil** [comment]
@SeanK1191 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by SeanK1191** [comment]
Sorry, my bad. 

It is the what 'what-the-sensitive-information-types-look-for' located [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md) although this seems to have a valid entry for French Drivers License.

I was using [this](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for#finland-passport-number) page when I noticed the issue, looks like the French Drivers License isn't formatted correctly and doesn't show up as it's own section.

**Comment by chrfox** [comment]
Hi @SeanK1191 
The documentation reflects what is in the code of the product. I am forwarding this to the product group, If there is a code fix, then the documentation will be updated.

**Comment by mypil** [comment]
@SeanK1191 -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by chrfox so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
