### ISSUE TITLE
microsoft learn for sc-200 module, wrong word correction

### ISSUE THREAD

**Issue by abdulNagaria** [MicrosoftDocs/microsoft-365-docs#10750]
![image](https://user-images.githubusercontent.com/112937671/213445396-d12ff487-d61e-4e81-b5a3-948434036f7e.png)

in the above image in the table you can see for the description of "Threat Analytics" the description is given as "When new Threat Analytic reports _area_ created" where **"area"** should just be **"are"**.

its a small issue could not find the doc to make the change , so opening a pull issue 👍

**Comment by abdulNagaria** [comment]
@yogkumgit , I was unable to find the page within the repository but this is the [link](https://learn.microsoft.com/en-us/training/modules/mitigate-incidents-microsoft-365-defender/13-configure-microsoft-365-defender-portal) for the page which contains the error

**Comment by msbemba** [comment]
@yogkumgit This falls under the training repo and not M365. Can we route this to the right team?

https://learn.microsoft.com/en-us/training/modules/mitigate-incidents-microsoft-365-defender/13-configure-microsoft-365-defender-portal

**Comment by yogkumgit** [comment]
@tiburd Please help. Thanks

**Comment by tiburd** [comment]
@abdulNagaria 
Hello, Abdul,

Thank you for reporting this typo. Unfortunately, our team doesn't have access to the training repos.

May I suggest that you please report the typo using the "reporting an issue" link at the bottom of the page that has the typo?
<img width="554" alt="image" src="https://user-images.githubusercontent.com/54688693/213732502-a79ce622-1128-447d-8d8d-9d70cd401725.png">

Thank you!

cc: @yogkumgit @msbemba
