### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by webfort** [MicrosoftDocs/microsoft-365-docs#10752]
Connect-AzureAD -AzureEnvironmentName AzureGermanyCloud throws the following exception
`Connect-AzureAD : One or more errors occurred.: Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-AzureAD -AzureEnvironmentName AzureGermanyCloud
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD
 
Connect-AzureAD : One or more errors occurred.
At line:1 char:1
+ Connect-AzureAD -AzureEnvironmentName AzureGermanyCloud
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AggregateException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD
 
Connect-AzureAD : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-AzureAD -AzureEnvironmentName AzureGermanyCloud
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], NullReferenceException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD
 
Connect-AzureAD : One or more errors occurred.: Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-AzureAD -AzureEnvironmentName AzureGermanyCloud
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-AzureAD], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Open.Azure.AD.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55574af9-0105-dcd1-7eb0-77513df4e54f
* Version Independent ID: 5fe2849b-d39a-4d75-a5ce-e8f577c9a161
* Content: [Connect to Microsoft 365 with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@webfort Thank you for your feedback. This seems more of a technical issue as it is failing due to an authentication error. I'd recommend you contact Support via the need help section on the admin center so that an engineer will be able to help you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @webfort Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
