### ISSUE TITLE
Steps out of date, inaccurate and vague.

### ISSUE THREAD

**Issue by agoldenlife** [MicrosoftDocs/microsoft-365-docs#1076]
Not sure if our tenant is newer, but I can't perform any of these steps.  Below I will point  out the issues I see.  If we can lets clear this up as a recent rash of new malware is aiming for this specific vector to gain persistent data access.  I have tried these instructions using the old and new admin center layout.  The problems are not related to that.

Specifically this section: Steps for finding signs of this attack
1: Security and Compliance does not exist in my tenant.  I have a Security option and a Compliance option under "Admin centers" in my left bar on the page "Microsoft 365 admin center".
2: If I click compliance or security I do not have a "Search and Investigation" option/choice.  I also don't understand you use of the word "node".  That word should be removed.  However, if I click the "Security option", then choose "More Options", then I will see a "Office 365 security and compliance center".  In that Center I have an option/choice for "Search", but still no "Search and Investigation".  Under "Search", when I expand it, I see an option for "Audit log search". Please bold "Audit log search" in your statement as that is the complete name.  You just have "Audit log" in bold and not the word search.
3: You do not "create" a search.  You are searching.  Please remove that word.  First you leave the default options, Activities to "Show results for all activities".  Next you leave the "Users" field blank so it will search for all users.  You may want to point out they should adjust the date as by default it goes back 8 days.  Click the "Search" button now we see results on right.  You state to filter it... OK.  Which fields am I filtering on.  First step is I have to click the "Filter" button to see the fields come up.  Then where do I put your filter parameters?  I would assume in "Activity", "Item" or "Detail".  Also put in quotes what you want me to type.  do you want "add" in there?  Are the parameters you put correct.  I approved a new app and did a search for those two settings but the results were blank.
4: How do you "Examine the extended properties"?  I assume you mean click and entry and the details window opens from the right.  Then expand the "More Information" section to look for that field.

Finally you state at the top this should be looked at weekly?  How about creating a "New alert policy".  Also if we are to check it weekly, probably need good instructions so that we can.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66854a7-7556-9b2a-0a33-886e3d881047
* Version Independent ID: 7ce3d8d5-cece-0b6f-68d5-143e12a3fff8
* Content: [Detect and Remediate Illicit Consent Grants in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants#feedback)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @agoldenlife, thanks for your comments, the topic has been updated and will be live soon

**Comment by agoldenlife** [comment]
I am not sure how this issue was closed.  The instructions are wholly inaccurate.  What was even changed.  I point out at least 4 items none of which were changes!  If you have some other instructions that you can point to, but these instructions are useless!

**Comment by mypil** [comment]
@agoldenlife - The content has been updated to add the changes that you requested for based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/ff3b2d4fcaaff2d615cbb4a4f2a62676f9920abe but it may take a few days for the merged content to appear in the doc. 

We value your contribution towards the improvement of our docs. Please feel free to open a new issue if there is a specific area in the docs that we can make better. Thank you!
