### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by ledeczi** [MicrosoftDocs/microsoft-365-docs#10766]
[The filter keeps catching important email. There is no information on how to remove an address from spam filtering. Even if I release the email, it still catches email from the same sender later on. Where is a Safe Sender List? How can I add addresses to it? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfc15d1-833b-3139-6bc0-1acb97d507c8
* Version Independent ID: 31e24618-c2e6-4fe4-9651-04d6007548a4
* Content: [Find and release quarantined messages as a user - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-end-user?redirectSourcePath=%252farticle%252fEFFF08EC-68FF-4099-89B7-266E3C4817BE&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-end-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-end-user.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@ledeczi Thank you for your feedback. Messages that are identified as malware or high-confidence phishing are always quarantined, regardless of the safe sender list option that you use. For more information, see [Secure by default in Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-by-default?view=o365-worldwide).

If it is not malware of high confidence phish, it respects the safe sender lists created in EOP. Refer -https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ledeczi Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
