### ISSUE TITLE
Brooken link

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/microsoft-365-docs#10779]
[Link for "see the Product Terms(https://www.microsoft.com/licensing/terms/productoffering/MicrosoftDefenderforEndpointServer/all) is broken]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Version Independent ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Content: [Defender for Endpoint onboarding Windows Server](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-server?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-server.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@gb5757870 Thank you for your feedback. We have removed the product terms in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10803

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by tiburd** [comment]
PR merged. Closing issue.
