### ISSUE TITLE
Clarify if Microsoft Defender for Business support Sentinel integration

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/microsoft-365-docs#10771]
Hello Microsoft Documentation Team,

## Suggestion with regards to Sentinel
It will help Microsoft Customers and Partners if you clearly define on the comparison page if Defender for Business has all the required API to integrate with Microsoft Sentinel. I can see multiple customers looking for this answer online without a clear answer.
Sentinel compatibility is not mentioned in this initial Microsoft blog here
https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/introducing-microsoft-defender-for-business/ba-p/2898701

## Suggestion with regards to tables
Also in the document, you have two comparison tables:
* Vertical comparison table comparing "Defender for Business (standalone)" vs "Microsoft 365 Business Premium"
* Horizontal comparison table comparing "Defender for Business (standalone)"  "Defender for Endpoint Plan 1 (for enterprise customers)" and "Defender for Endpoint Plan 2 (for enterprise customers)"

Two tables of two layouts are making little sense and are impossible to follow and compare. One shared table comparing all four would make much more sense. Besides, there is no "Defender for Business (standalone)" in the official sheet here - https://aka.ms/M365BusinessPlans 

Best regards,
Serg

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 587ea70a-04b9-bdc8-f774-419607a07c47
* Version Independent ID: 587ea70a-04b9-bdc8-f774-419607a07c47
* Content: [Compare security features in Microsoft 365 plans for small and medium-sized businesses](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/compare-mdb-m365-plans?view=o365-worldwide#compare-microsoft-defender-for-business-to-microsoft-defender-for-endpoint-plans-1-and-2)
* Content Source: [microsoft-365/security/defender-business/compare-mdb-m365-plans.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/compare-mdb-m365-plans.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @SergGu and thank you so much for the feedback. I've reached out to the product team for clarification on which APIs are supported. In general, Defender for Business uses the Defender for Endpoint APIs but not necessarily all of them. I'm getting clarification on that. And I'll take a gander at updating the two tables to make things more clear. Thank you for posting your excellent question and for the helpful feedback. Watch for an update here soon.

**Comment by denisebmsft** [comment]
Just checking in. I am still waiting on details to update the docs.

**Comment by chritea** [comment]
Hi @denisebmsft , do you have any update? This would really help as the documentation is unclear at the moment. Thank you!

**Comment by SeegersInVegas** [comment]
Hi @denisebmsft, do you have any news on this issue? I´m working with a client, which tries to ingest their MDB-Data into Sentinel via EventHubs, since there´s no clear documentation available about whats possible and what is not. Thank you !

**Comment by denisebmsft** [comment]
Hello @SeegersInVegas @chritea -- just checking in. I am working on this. My apologies for taking longer to get the required information. Doc updates are in progress. I will post another update here soon.

**Comment by denisebmsft** [comment]
Hello again @SeegersInVegas @chritea. You can use the Event Streaming API with Defender for Business to stream information about device events. I've updated the documentation and the changes will be live sometime tomorrow. Additional how-to information is planned but that's not ready yet. In the meantime, here are some links that might be helpful:

- https://learn.microsoft.com/en-us/microsoft-365/security/defender/streaming-api?view=o365-worldwide
- https://learn.microsoft.com/en-us/microsoft-365/security/defender/supported-event-types?view=o365-worldwide
