### ISSUE TITLE
"The HIPAA Business Associate Agreement is available via the Online Services Terms" - where in the OST?

### ISSUE THREAD

**Issue by laurarob** [MicrosoftDocs/microsoft-365-docs#1077]
Where in the OST is the BAA even mentioned? I have the current doc and it's not mentioned at all. How are customers supposed to find the OST -&gt; BAA terms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545aa0d-ba68-3113-413b-0c0b176b08bd
* Version Independent ID: bb2ce8e1-7f40-e5ed-60c4-f8bb0912661d
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-hipaa-hitech#feedback)
* Content Source: [microsoft-365/compliance/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@laurarob - thanks for the feedback, let me investigate and find some details for the BAA and OST.

**Comment by robmazz** [comment]
@laurarob - Are you referring to this statement in the FAQ: "For Microsoft cloud services: The HIPAA Business Associate Agreement is available via the Online Services Terms by default to all customers who are covered entities or business associates under HIPAA." The link here in the topic opens this site that has the current HIPAA BAA terms - https://www.microsoftvolumelicensing.com/DocumentSearch.aspx?Mode=3&DocumentTypeId=52&Language=1. Can you see if this answers your question? Please let me know, thanks!

**Comment by robmazz** [comment]
Closing as resolved - no confirmation from customer.
