### ISSUE TITLE
Storage Quota for SharePoint online

### ISSUE THREAD

**Issue by Jakke2440** [MicrosoftDocs/microsoft-365-docs#10781]
is there any impact on the Storage Quota for SharePoint online? I could not find any info about that

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6c9e87a-f0ca-b98a-96de-1ede59d58c21
* Version Independent ID: d6c9e87a-f0ca-b98a-96de-1ede59d58c21
* Content: [Use Office 365 Content Delivery Network (CDN) with SharePoint Online - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Jakke2440 Thank you for your feedback. There is no impact on the storage quota, which is why there is no reference to it on the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Jakke2440 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
