### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by pctsltd** [MicrosoftDocs/microsoft-365-docs#1078]
You note "The Advanced Spam filter settings of the Anti-spam policy are currently being deprecated. Our recommended settings for these are to turn them OFF. The functions that were available in the Advanced Spam filter is being incorporated into other parts of the filtering stack."

Can you let us know if some of these have been integrated elsewhere already and if so where we can find them?

If not - can you give us 
(I) any timeframe when they will be deprecated or 
(ii) any timeframe when the integration elsewhere might happen or 
(iii) an indication of where should we look to find out when certain settings from this page are integrated elsewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2cc102-c50a-ec38-c90c-aafd97fda6f4
* Version Independent ID: 45ea7aa3-c198-ab40-dd4f-a008e191e178
* Content: [Advanced spam filtering options - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/advanced-spam-filtering-asf-options#feedback)
* Content Source: [microsoft-365/security/office-365-security/advanced-spam-filtering-asf-options.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/advanced-spam-filtering-asf-options.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by joinimran** [comment]
@pctsltd - Thank you for your query. @MSFTTracyP Can you please share your input on this? If there is anything that needs to be added, please let me know so that I can create PR for the same.

@mypil FYI Please

**Comment by n1x0d** [comment]
So it is recommended to set those options to off for the obscure reason that they are being incorporated some place else. This leaves more questions than answers. 

Why should we turn them off exactly? What happens we I don't turn them off?
What has been incorporated somewhere else exactly? All features? Some of them? If we turn them off now, will we lose something? If not.. why?

Kindly give us some details please. Thanks!

**Comment by chrisda** [comment]
I've heavily updated the topic to mathc current UI. As described, any announcements will occur outside of this topic (likely in a Message Center and/or blog post).

If the settings are currently working for you now, I would see no reason to change them, but be prepared for the day when they will disappear from ASF settings. The guidance seems to be more for new customers who never configured anti-spam policies; they're all turned off by default, and we recommend that you leave them off.

Closing.

**Comment by andrewpEntag** [comment]
Hi @chrisda, I was just wondering if this is still the recommended action in 2022? I don't see any notes now indicating that these will be depreciated and there is now no explicit guidance to turn them off (or on for that matter). 

Thanks,
Andrew

**Comment by chrisda** [comment]
@andrewpEntag, you are correct. I toned down the language in the topic some time ago. Standard and Strict preset security policies don't turn any of the ASF settings on, and the note that's always been in the topic is still accurate:

 > [!NOTE]
> Enabling one or more of the ASF settings is an aggressive approach to spam filtering. You can't report messages that are filtered by ASF as false positives. You can identify messages that were filtered by ASF by:
>
> - Periodic quarantine notifications from spam and high confidence spam filter verdicts.
> - The presence of filtered messages in quarantine.
> - The specific `X-CustomSpam:` X-header fields that are added to messages as described in this article.

About as strongly worded as I'm prepared to go today is: "our recommended value for these settings is off".
