### ISSUE TITLE
Incomplete Instructions on Case creation 

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/microsoft-365-docs#10785]
The current workflow of case creation requires setting up Team Members and other search criteria. That isn't shown in the directions. For example there is no Save button but rather a submit button.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0bbad5-4e3f-c65e-1abf-821ec4be481a
* Version Independent ID: 3f0bbad5-4e3f-c65e-1abf-821ec4be481a
* Content: [Teams workflow in eDiscovery (Premium) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-teams-workflow?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/ediscovery-teams-workflow.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-teams-workflow.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@hoyty76 Thank you for your feedback. We will review and make changes to the document shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@hoyty76 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11106

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@hoyty76 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
