### ISSUE TITLE
Confusing Example

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1079]
In the "Using a label as a condition in a DLP policy" section, the Retention Label example uses "Confidential" as a label name, since this word is more typically associated with Sensitivity labels, I would like to suggest that a different example be used to decrease the chance for confusion.  Retention and Sensitivity are 2 very different, but related, concepts and we need to keep them separated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies#more-information)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @DeanGross 
Thanks for letting me know. I am working on a wide update of all the DLP content and will address this and many other issues in that work
thanks
Chris
