### ISSUE TITLE
Poor writing style - please correct

### ISSUE THREAD

**Issue by victortimothyshulist** [MicrosoftDocs/microsoft-365-docs#10806]
[ Please correct the very poor writing style.   You have a fine product, do not lower your standards by writing poorly.  For example, the line that states:  "Checking for the license state and whether it got properly provisioned...."   -- Please correct this to be professionally written - please correct to  "Checking for the license state and whether it WAS properly provisioned...".   We have a word in English, it is "was".   The word "got" does NOT mean "was".  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b25b8545-b7f0-e035-ca6e-26b1530feddb
* Version Independent ID: 93b5152a-2ba2-1239-ded7-42896cacc074
* Content: [Set up Microsoft Defender for Endpoint deployment](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/production-deployment?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/production-deployment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/production-deployment.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@victortimothyshulist Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10847

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by victortimothyshulist** [comment]
Thank you So much for upholding the quality of language and knowledge.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @victortimothyshulist Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
