### ISSUE TITLE
Clarify that messages classified as Phishing aren't viewable in end user quarantine

### ISSUE THREAD

**Issue by mikenri** [MicrosoftDocs/microsoft-365-docs#1080]
This documentation is worded such where it seems end users should be able to see messages classified as Phishing and only high confidence Phishing are held in administrative quarantine. 

Support has advised that currently both Phishing and High Confidence Phishing are held in administrative quarantine. 

End user access to Phishing isn't being rolled out until starting in Feb. 2020 per MC20032:
https://admin.microsoft.com/Adminportal/Home#/MessageCenter?id=MC200232

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e13e522a-93c8-fb88-3833-8660d8bbc71d
* Version Independent ID: 06300772-2c8c-9e1e-f777-f8adb61af136
* Content: [Quarantine email messages in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-email-messages#feedback)
* Content Source: [microsoft-365/security/office-365-security/quarantine-email-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-email-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@mikenri - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/e38307caad32a9634a45fe1a2c71a67f16f09808. 


Thank you for your contribution to make the docs better! Much appreciated!
