### ISSUE TITLE
Subtitle change request

### ISSUE THREAD

**Issue by kuroyuko** [MicrosoftDocs/microsoft-365-docs#10800]
Now We can't get the information for the CNAME record to connect AAD from the admin center domain setup wizard.
I think the subtitle should be modified as follows;

"Add CNAME records to connect other services (Teams, Exchange Online, AAD, MDM)"
↓
"Add CNAME records to connect other services (Teams, Exchange Online, MDM)"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f2e4e45-6ad7-eb79-aecb-0d7a89b06a03
* Version Independent ID: 1059223e-5759-b130-41ac-5ea98cb5367e
* Content: [Add DNS records to connect your domain - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by msbemba** [comment]
@kuroyuko Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10846

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kuroyuko Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
