### ISSUE TITLE
Cannot search for MSCommers PS module on PowerShell Module Browser

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/microsoft-365-docs#1081]
I am a user of PowerShell Module Browser (PSMB).
https://docs.microsoft.com/en-us/powershell/module/

I really heavlly rely on this web service to find Microsoft PowerShell modules.
But, I noticed the MSCommerce module (https://www.powershellgallery.com/packages/MSCommerce/1.2) has not been searchable on PSMB.

Could you add the MSCommerce module to the module lists?
If it is not intentionally listed, could you tell me the reason?

Thanks

**Comment by mypil** [comment]
@kefujino - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by kefujino** [comment]
@mypil 

https://docs.microsoft.com/en-us/teamblog/announcing-unified-powershell-experience
https://docs.microsoft.com/en-us/powershell/module/?term=MSCommers

These articles are for PowerShell Module Browser.
They describe to **"search all Microsoft PowerShell modules and cmdlets"**, but actually MSCommers PS module isn't searchable.

![image](https://user-images.githubusercontent.com/13634805/72692087-57e01a00-3b6d-11ea-9a8b-dfd87d7e5038.png)

![image](https://user-images.githubusercontent.com/13634805/72692041-12235180-3b6d-11ea-8317-4c5599dc4009.png)

**Comment by mypil** [comment]
@kefujino - This repo is intended for feedback on the Microsoft 365 docset. The doc link you provided is for the below doc:

* Content: [Announcing the PowerShell Module Browser](https://docs.microsoft.com/en-us/teamblog/announcing-unified-powershell-experience)
* Content Source: [teamblog/announcing-unified-powershell-experience.md](https://github.com/MicrosoftDocs/blog/blob/live/teamblog/announcing-unified-powershell-experience.md)
* Product: **team-blog**


Please submit your feedback and open a new issue by clicking on the Feedback section on that specific Microsoft doc which is found at the bottom of the page.


Thank you for your contribution to make the docs better! Much appreciated!
