### ISSUE TITLE
Unexpected Safe Links Functionality for entire tenant

### ISSUE THREAD

**Issue by lmarianko** [MicrosoftDocs/microsoft-365-docs#10818]
A customer could be taken off guard if they never had an MDO defender license in the past and then added it later.  We had a customer who never had a defender license in the tenant and then added it for a small group of people (not for entire tenant).  They had not applied any custom policies. All of sudden everyone in the entire tenant got safe links and they had no idea why.  Also in order to be license compliant they would have to exclude everyone from the built in policy that they did not buy the license for.  I think this needs to be in one of those blue or pink boxes as an  important change or warning.  Before this change no one in the tenant got safe links or attachments unless you set up a policy..thats a big change.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
Checking.

**Comment by chrisda** [comment]
@lmarianko, although the topic already contains the following text:

> Until you assign the policies to users, the **Standard** and **Strict** preset security policies are assigned to no one. In contrast, the **Built-in protection** preset security policy is assigned to all recipients by default, but you can configure exceptions.

I'll admit that doesn't exactly stand out., so I added the following text nearby:

> [!IMPORTANT]
> Unless you configure exceptions to **Built-in protection**, everyone in the organization will receive Safe Links and Safe Attachments protection.

OK?

**Comment by lmarianko** [comment]
That's part of it but I think something should be mentioned about licenses specifically.  Does the built in protection now give you safe links and safe attachments even if you don't have a defender license?  Is it now part of EOP basic protection?  This is where the confusion comes in.

Do you have to add exceptions for those users that don't have a defender license or you won't be in license compliance?

Thanks.

Leslie

Leslie Marianko
Sr Cloud Solutions Architect
State and Local Government
Modern Work
  Office: +1 (646) 225-5061
  Mobile: +1 (908) 342-5433
  ***@***.******@***.***>
[Microsoft]

**Comment by lmarianko** [comment]
So are we saying its not out of license compliance if everyone has built in protection and does not have a defender license?


Leslie Marianko
Sr Cloud Solutions Architect
State and Local Government
Modern Work
  Office: +1 (646) 225-5061
  Mobile: +1 (908) 342-5433
  ***@***.******@***.***>
[Microsoft]

**Comment by chrisda** [comment]
Switching to email.
