### ISSUE TITLE
Need to update this Document with Proper Graphic

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/microsoft-365-docs#10825]
Hello Team,
Can you update this article with proper graphic? The one we have is from 5 years ago. ( https://learn.microsoft.com/microsoft-365/security/office-365-security/email-authentication-about)

Regards,
Mithun Rathinam
Exchange Beta engineer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd1ebad6-d8d1-8973-7595-71cb8a50b833
* Version Independent ID: d1d565cb-2f31-c847-860e-513dcaefa123
* Content: [Email authentication in Microsoft 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/email-authentication-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/email-authentication-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
Checking to see if modern statistics are available. Otherwise, I'm going to remove the graphic and edit the words.

**Comment by chrisda** [comment]
Removed out-of-date 2018 text and graphics.

Thanks for the feedback.

Closing
