### ISSUE TITLE
Retention Labels used as Sensitivity Labels

### ISSUE THREAD

**Issue by gruering** [MicrosoftDocs/microsoft-365-docs#1082]
It looks like retention labels are misused as sensitivity labels in this example. This is very confusing and I assume it has to do with the current limitations of DLP policies for sensitivity labels. Retention labels shouldn't be used to classify content based on sensitivty as shown in this example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d15f061-ae97-6eab-12a4-1e0344a01fa0
* Version Independent ID: fa58e7e0-d50b-8629-2d5a-d4827e03f644
* Content: [Protect SharePoint Online files with retention labels and DLP - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp#feedback)
* Content Source: [microsoft-365/compliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by Duncan-Cooper** [comment]
Microsoft, please do clear this up. Imagine a company using retention labelling for sensitivity actions and then later actually wanting to introduce retention policies using retention labelling too. If people implement this way their document management system will be broken. Unless I missed something...

**Comment by Duncan-Cooper** [comment]
> Microsoft, please do clear this up. Imagine a company using retention labelling for sensitivity actions and then later actually wanting to introduce retention policies using retention labelling too. If people implement this way their document management system will be broken. Unless I missed something...

Just found this - which may explain why the article exists (as a workaround?).
"Support for sensitivity labels is coming
You can currently use only a retention label as a condition, not a sensitivity label. We're currently working on support for using a sensitivity label in this condition."

https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies#support-for-sensitivity-labels-is-coming

**Comment by msbemba** [comment]
@gruering  and @Duncan-Cooper  Thank you for the feedback. As @Duncan-Cooper  Suggested You can currently use only a retention label as a condition, not a sensitivity label. We're currently working on support for using a sensitivity label in this condition.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@gruering - Thank you for submitting feedback.

From our understanding, the issue has been answered by msbemba so we will close this issue.

Thank you for engaging with the community here for the docs.

**Comment by stevelee101** [comment]
@mypil - in the meantime can we clarify and add msbemba's details because it continues to cause confusion with customers.

**Comment by msbemba** [comment]
@stevelee101 Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1938

Thanks
Sri
