### ISSUE TITLE
Scanning Frequencies

### ISSUE THREAD

**Issue by SeniorConsulting** [MicrosoftDocs/microsoft-365-docs#10824]
Greetings, this page does not supply any information around the scanning or reporting frequencies of Sensitive Information Types. Some examples:

- After creating a new custom SIT, how long should you expect results/matches to appear in the compliance portal?
- What is the window between creating an item which has an SIT in it and it showing up in the compliance portal?
   - How long after uploading an item to SharePoint? Note - there is some reference that [SharePoint will need to be recrawled](https://learn.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type?view=o365-worldwide#create-a-custom-sensitive-information-type), but not any of the crawling timeframes) 
   - How long after receiving an email in Exchange Online?

If this abides by another documented process, providing a link to this process would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1edffc-5d5e-8ed8-a7d1-7467fb14b3d1
* Version Independent ID: 13a701b4-3dfa-2b1b-2ff2-445183a1f1eb
* Content: [Learn about sensitive information types - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-learn-about?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitive-information-type-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitive-information-type-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by SeniorConsulting** [comment]
Hi team, it's been a few months - is there any update to this feedback?

**Comment by yogkumgit** [comment]
@SeniorConsulting Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
