### ISSUE TITLE
Suggested edit to https://learn.microsoft.com/en-us/microsoft-365/admin/manage/use-qr-code-download-outlook?view=o365-worldwide

### ISSUE THREAD

**Issue by sfellmanMS** [MicrosoftDocs/microsoft-365-docs#10838]
We need to add a disclaimer to this article since the feature is paused; suggest the following:

As of August 2021, this experience has been put on HOLD indefinitely on commercial/enterprise users due to the lack of controls on it for Tenants. The works to provide these controls is extensive and the Identity team continues working on them. We rolled back this experience on commercial/enterprise users since we want to provide more security and customization for all the different cases they managed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 749a8389-eda6-3059-b713-5d0b3755fe9c
* Version Independent ID: 53000b70-b561-ec33-0b94-f0c26650548b
* Content: [Use a QR code to sign-in to the Outlook mobile apps - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/use-qr-code-download-outlook?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/manage/use-qr-code-download-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/use-qr-code-download-outlook.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@sfellmanMS Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10850

Once the author approves, the changes will be live.

Thanks
Sri
