### ISSUE TITLE
How do I block the damn thing?

### ISSUE THREAD

**Issue by jarrett-b** [MicrosoftDocs/microsoft-365-docs#10856]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Ratulch** [comment]
Hi @jarrett-b -- Could you please provide more details on the issue you're facing? Thank you.

**Comment by jarrett-b** [comment]
I opened ticket and discovered the on/off switch is in Microsoft Defender, not Exchange. Please stop pushing features without the administrator's permission, this caused me a big headache at my company.
