### ISSUE TITLE
Updates to section on Locking and unlocking a record

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#10854]
In the section locking and unlocking a record. I would add that when a record is locked a padlock appears next to the file name indicating the file cannot be edited. When the file is unlocked, the padlock is removed as the file can be edited. 

![image](https://user-images.githubusercontent.com/69439002/215848506-6fff2218-8e3c-4dea-8a48-d5348fbc8c65.png)

I would also add that Retention Events only selected locked records.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b41860d-88f5-a81d-435b-de6e8b5ef0cc
* Version Independent ID: c092d603-411d-09bb-1626-464f104325f3
* Content: [Use record versioning in SharePoint or OneDrive - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/record-versioning?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/record-versioning.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/record-versioning.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@nikki-c   Thank you for the suggestion about the padlock.  I don't have confirmation at the moment that the padlock always appears for all scenarios and that using the Details pane is the most reliable method, but I'll continue to investigate.

Can you explain more about "Retention Events only selected locked records."  I'm having problems understanding what you mean by this.

**Comment by cabailey** [comment]
I've added a reference to the padlock but still waiting for clarification about the "Retention Events only selected locked records." additional comment.  Closing this issue but you can always open a new one with that clarification. One issue per GitHub Issue is easier to track and manage.
