### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/microsoft-365-docs#10859]
I would like clarification on what licensing is required for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59c87455-77af-093a-6fb6-286049aad15a
* Version Independent ID: b2690e98-781d-4a27-a9bc-bd621964feb0
* Content: [Get started using Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-get-started.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mattdreher Microsoft Defender for Office 365 Plan 2, either as an add-on subscription or as part of something else (Microsoft 365 E5).

**Comment by chrisda** [comment]
Thanks for the feedback.

Closing
