### ISSUE TITLE
Add limitation.  

### ISSUE THREAD

**Issue by contributor-luis** [MicrosoftDocs/microsoft-365-docs#10857]
[Enter feedback here]

Hi Team, 

I worked with PG about SharePoint and OneDrive can't process encrypted files when the label that applied the encryption has any of the following [configurations for encryption] limitations and we found another scenario that we need to add here. 

![image](https://user-images.githubusercontent.com/105931677/215856641-c123d21c-59cf-45d7-875f-bcea84a7994a.png)

Here is the limitation found: When you enable encryption on the parent label and the child label does not have encryption enabled, these labels will not display in Office Web by design. 

Regards, 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide#limitations)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Closing - we have an ongoing internal discussion how to document this, so no need to duplicate.

**Comment by contributor-luis** [comment]
Thanks Carol,

Best regards,

Luis Elias
Support Escalation Engineer, Security & Purview | Microsoft Team | Fairfax
Empowering, Helping, and Advising Customers

Customer Service & Support
Phone: +1 469 775 0736
Email: ***@***.******@***.***>

Need help outside my working hours?
Manager: Benjamin Krauter, ***@***.******@***.***>
Working Hours: Mon-Fri 9:00 AM - 6:00 PM EST

[Image result for microsoft logo]

"Empower every person and every organization on the planet to achieve more.
