### ISSUE TITLE
Rules examples are screenshots, without a plaintext copy of the code to copy\paste

### ISSUE THREAD

**Issue by PaulHarfield** [MicrosoftDocs/microsoft-365-docs#10865]
Rules examples are screenshots, without a plaintext copy of the code to copy\paste. Would be handy to have usable samples
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63a192be-1169-e91d-9dc7-9a01908ace40
* Version Independent ID: 63a192be-1169-e91d-9dc7-9a01908ace40
* Content: [Operationalize attack surface reduction (ASR) rules](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-operationalize?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-operationalize.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-operationalize.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@PaulHarfield Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10966

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@jweston-1 please merge this PR. thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PaulHarfield Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
