### ISSUE TITLE
Channel information is different from acctual name

### ISSUE THREAD

**Issue by morrow233** [MicrosoftDocs/microsoft-365-docs#10866]
[Enter feedback here]

There is a description about channel name change.
=========
Prior to Microsoft AutoUpdate version 4.29, channels had different names:
	• Beta was named InsiderFast (Insider Fast)
	• Preview was named External (Insider Slow)
	• Current was named Production
=========

But those are little bit different from actual names thus, customer is confused.
![image](https://user-images.githubusercontent.com/87346322/216005273-2ca34a84-91ed-4ecc-8056-51bdeebb092f.png)

Please consider updating the description like below.

=========
Prior to Microsoft AutoUpdate version 4.29, channels had different names:
	• Beta Channel was named InsiderFast (Insider Fast)
	• Current Channel (Preview) was named External (Insider Slow)
	• Current Channel was named Production
=========

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 092ef512-a100-4be8-8f63-1caaeb9e9559
* Version Independent ID: 5245c257-ea7e-57b9-03d9-bf2b63b3306c
* Content: [Deploy updates for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-updates?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-updates.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@morrow233 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10912

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @morrow233 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
