### ISSUE TITLE
feedback on Teams chat and channel messages of Location

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/microsoft-365-docs#1086]
Hi Team,
If we enabled 'status' of Teams chat and channel messages in Location, it works when sending message in teams chat and channel messages. However, this option does not work if we share a file in Channel. Because of file sent in channel will be saved in SharePoint site, and we have to enable SharePoint sites in Location. This confused the customer on DLP configuration for teams. Can we have more details of step or statement to guide our customer on this configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaab3f7-d1d4-c649-efe8-f24913da4f3e
* Version Independent ID: c5710ebf-0ca5-ab46-c490-64ebc308defe
* Content: [Data loss prevention and Microsoft Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams)
* Content Source: [microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-microsoft-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
HI @XixiHuang333 
Can you please describe in more detail the scenario that your customer got confused on. What was it that they were trying to accomplish and where did they get confused in the content?
thanks
Chris

**Comment by mypil** [comment]
@XixiHuang333 - We would like to follow up. Can you please respond to the query of chrfox?

Thank you.

**Comment by mypil** [comment]
@XixiHuang333 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
