### ISSUE TITLE
Suggest a correction on this page

### ISSUE THREAD

**Issue by micmaher** [MicrosoftDocs/microsoft-365-docs#10869]
There is a bulleted list which looks out of place, otherwise this is one of the best MS articles I have read in a long time

Please refer to 

https://learn.microsoft.com/microsoft-365/security/office-365-security/migrate-to-defender-for-office-365-prepare#define-spam-and-bulk-user-experiences

It's a repeat of the bullet points from a prior section at https://learn.microsoft.com/microsoft-365/security/office-365-security/migrate-to-defender-for-office-365-prepare#move-features-that-modify-messages-into-microsoft-365

* Domain Keys Identified Mail (DKIM) will break.
* Spoof intelligence will not work properly.
* You'll probably get a high number of false positives (good mail marked as bad).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce7455d-8c2d-e20a-567e-0873e0a4f533
* Version Independent ID: 4ce7455d-8c2d-e20a-567e-0873e0a4f533
* Content: [Migrate to Microsoft Defender for Office 365 Phase 1: Prepare - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/migrate-to-defender-for-office-365-prepare?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/migrate-to-defender-for-office-365-prepare.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/migrate-to-defender-for-office-365-prepare.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@micmaher, thanks. That appears to be some kind of weird copy/paste error. I fixed it.

Thanks for the feedback.

Closing
