### ISSUE TITLE
Permissions for DLP reports

### ISSUE THREAD

**Issue by neozhu-msft** [MicrosoftDocs/microsoft-365-docs#1087]
{"Message":"You don\u0027t have access to DLP Incident Data.","DiagnosticContext":"{Version:17.00.4058.005,Environment:WUSPROD,DeploymentId:e3e080d08f264cb48f670c1d113d21cc,InstanceId:WebRole_IN_2,SID:a3d2fb77-6e5c-44c0-922b-bdc1acda1aef,CID:57032f72-5f58-485d-98eb-5ad91b54b112}","Time":"2020-01-16T00:22:24.4522979Z","ExceptionType":"Microsoft.Exchange.PswsClient.PswsException"}

assigned the mentioned permission where still received the server 500 error. The correct permission should be 

1. Compliance Management role in Exchange EAC 
2. Security Reader role in Security & Compliance Center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec12506-ca29-0a03-3b01-699cb22b7ab7
* Version Independent ID: 6dc6083d-fcde-3622-5653-61c5be4bb5db
* Content: [View the reports for data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/view-the-dlp-reports)
* Content Source: [microsoft-365/compliance/view-the-dlp-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-the-dlp-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
HI neozhu-msft
thanks for your comments. I'll verify the permissions and update the content as needed.

**Comment by chrfox** [comment]
Hi @neozhu-msft 
Since you are a Microsft FTE, we can continue this discussion internally.
