### ISSUE TITLE
Please correct the description of "Scan files on the network"

### ISSUE THREAD

**Issue by narkuroki** [MicrosoftDocs/microsoft-365-docs#10878]
[Enter feedback here]
Please correct the description of "Scan files on the network"

Please correct the following statements.
━━━━━━━━━━━━━━━━━━━━
Policy items and locations:
Scan files on the network
Scan > Scan network files

Default setting (if not configured):
Disabled
━━━━━━━━━━━━━━━━━━━━

Please correct as follows.

Current statement:
Default setting (if not configured): Disabled

Correct:
Default setting (if not configured) Enabled

Why it needs to be fixed:
I've checked the spec internally and confirmed that it will be enabled if I don't configure it.
A customer requested a fix. Please correct it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 292d5bf4-ff14-4cbe-eab1-3fe35cb5c1c9
* Version Independent ID: 782db2b2-0a15-941c-24ff-345ecfe694f3
* Content: [Configure scanning options for Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-advanced-scan-types-microsoft-defender-antivirus?view=o365-worldwide#settings-and-locations)
* Content Source: [microsoft-365/security/defender-endpoint/configure-advanced-scan-types-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-advanced-scan-types-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@narkuroki Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10914

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The PR is merged and can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @narkuroki Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
