### ISSUE TITLE
Skype for Business CNAME record values are incorrect

### ISSUE THREAD

**Issue by aaronswainonset** [MicrosoftDocs/microsoft-365-docs#10879]
Regarding the section "Add the two required CNAME records for Skype for Business" - https://learn.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide#add-the-two-required-cname-records-for-skype-for-business

The table in step 5 says the two CNAME values must end in a period, however the values generated in Microsoft 365 Admin Center do not end in a period. Is the documentation incorrect, or does M365 AC generate the wrong values?

This also appears to affect other sections of the documentation (https://learn.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide#add-the-two-required-cname-records-for-skype-for-business).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6107c99-df0b-8a33-f291-086ea6fd5034
* Version Independent ID: 0ba87689-7a57-c3f8-af4b-3267c81b933d
* Content: [Connect your DNS records at Cloudflare to Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-cloudflare.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by msbemba** [comment]
@aaronswainonset Thank you for your feedback. The document is correct, the CNAME records for Skype for Business should end with a period. I'll work with the team to fix this internally.

Hope this helps!

Thanks
Sri

**Comment by aaronswainonset** [comment]
Hi @msbemba .

I think I'm misunderstanding something. Microsoft 365 Admin Center generates the CNAMEs without a trailing period, and the M365 AC validates that they're found in my DNS. But the documentation says the CNAMEs should have a trailing period.

Is M365 AC generating incorrect CNAMEs and incorrectly validating them, or is the documentation incorrect?

**Comment by aaronswainonset** [comment]
Hi @msbemba .

The trailing period is not required. These instructions are for Cloudflare and Cloudflare doesn't accept the trailing period.

When adding the CNAME to Cloudflare, including the trailing period as per MS documentation:
![image](https://user-images.githubusercontent.com/63683488/217137758-ec11b5cf-d295-441c-ae96-20b1d5acdeda.png)

After adding the CNAME to Cloudflare, note that Cloudflare removes the trailing period automatically:
![image](https://user-images.githubusercontent.com/63683488/217137597-ddac84e8-6ff5-4c28-a61b-d747320cabcb.png)

**Comment by msbemba** [comment]
@aaronswainonset Thank you for your response, I shall check with the PM, test, and update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@aaronswainonset Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11004

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by Cee3097** [comment]
Now that scares the shit out of me and mine

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @aaronswainonset Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
