### ISSUE TITLE
Bulk Add Users to "Manage senders for impersonation protection"

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#10881]
I do not see anything listed in the documentation to bulk add users to "Manage senders for impersonation protection". Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-policies-about?view=o365-worldwide#impersonation-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-policies-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-policies-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@HarrisburgUSysAdmin, you're in the "about" topic. The "how to" topic contains PowerShell instructions to [create](https://learn.microsoft.com/microsoft-365/security/office-365-security/anti-phishing-policies-mdo-configure#step-1-use-powershell-to-create-an-anti-phish-policy) and [modify\(https://learn.microsoft.com/microsoft-365/security/office-365-security/anti-phishing-policies-mdo-configure#use-powershell-to-modify-anti-phish-policies) anti-phishing policies.

Those instructions don't specifically contain information about adding multiple users for impersonation protection, but they do link off to the corresponding [New-AntiPhishPolicy](https://learn.microsoft.com/powershell/module/exchange/New-AntiPhishPolicy) and [Set-Anti-PhishPolicy](https://learn.microsoft.com/powershell/module/exchange/New-AntiPhishPolicy), where the _TargetedUsersToProtect_ parameter is identified as "MultiValuedProperty" and the rather complex syntax for it is explained.

So, to add multiple users for user impersonation protection to an existing anti-phishing policy, use the following syntax:

```powershell
Set-AntiPhishPolicy -Identity "<Policy Name>" -TargetedUsersToProtect "DisplayName1;EmailAddress1","DisplayName2;EmailAddress2",..."DisplayNameN;EmailAddressN"
```

OK?

**Comment by chrisda** [comment]
Sorry, I should have also included the _EnableTargetedUserProtection_ parameter in the previous command:

```powershell
Set-AntiPhishPolicy -Identity "<Policy Name>" -EnableTargetedUserProtection $true -TargetedUsersToProtect "DisplayName1;EmailAddress1","DisplayName2;EmailAddress2",..."DisplayNameN;EmailAddressN"
```

**Comment by chrisda** [comment]
Thanks for the feedback.

Closing
