### ISSUE TITLE
Change in https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9974 for this article is not reflecting. Still has old information.

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#10880]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf5df26b-9563-4810-f5b8-6997c9baa27c
* Version Independent ID: 006f5550-36b6-1de7-d3a5-63b85241df03
* Content: [Microsoft Defender for Endpoint Device Control Device Installation](https://review.learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-device-control-device-installation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by PremMS-MDE** [comment]
@msbemba Requested change was under the topic: Prevent Installation of Removable devices.

**Comment by PremMS-MDE** [comment]
@msbemba kindly requesting to check the above info

**Comment by msbemba** [comment]
@PremMS-MDE We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11003 and it will be live once the author approves.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PremMS-MDE Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
