### ISSUE TITLE
URL not valid: https://github.com/microsoft/shell-intune-samples/tree/master/Misc/MDATP

### ISSUE THREAD

**Issue by tomrys** [MicrosoftDocs/microsoft-365-docs#10882]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae1c59b1-e4aa-6a18-7c34-720d0eb83c5d
* Version Independent ID: f5a3fc3c-bec2-3d7a-1d61-e23a0c1f8d4f
* Content: [How to schedule scans with Microsoft Defender for Endpoint on macOS](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-schedule-scan?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-schedule-scan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-schedule-scan.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@tomrys Thank you for your feedback. I do not see the URL in this Document and also notice that the URL does not exist anymore. Are you referring to a different document which points this out?

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.
