### ISSUE TITLE
Incorrectly states "Intune: Not available" for Block persistence through WMI event subscripton rule

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#10896]
[Enter feedback here]
section for Block persistence through WMI event subscription says Intune name: Not available however this is configurable in the Intune ASR policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Version Independent ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Content: [Attack surface reduction rules reference](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#block-persistence-through-wmi-event-subscription)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jrhi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10954

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jrhi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bweston-8** [comment]
This was fixed as part of: https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10954
