### ISSUE TITLE
Doc needs to be update to reflect Purview

### ISSUE THREAD

**Issue by mossywell** [MicrosoftDocs/microsoft-365-docs#10891]
Step 2 "Expand the Compliance center section and select Roles." need to be updated as there is no "Compliance centre section".
I think it needs to say "Microsoft Purview solutions"?

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 468343fc-2808-0f78-f1a7-9d34b8fa8e16
* Version Independent ID: e3b7630f-75a9-d236-6c8b-7ebd27a7e9c0
* Content: [Permissions in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-gb/microsoft-365/compliance/microsoft-365-compliance-center-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/microsoft-365-compliance-center-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-compliance-center-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@mossywell Thank you for your feedback. The document has been updated now with Microsoft Purview solutions.

Hope this helps!

Thanks
Sri
