### ISSUE TITLE
How to programatically set new sesnsitivity labels?

### ISSUE THREAD

**Issue by ashavibapat** [MicrosoftDocs/microsoft-365-docs#1089]
https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#relabel-office-365-groups-with-new-sensitivity-labels

Is there a graph api I can use?
Would the older pnp core extension method for         public static void UpdateSiteClassificationsSettings(string accessToken, SiteClassificationsSettings siteClassificationsSettings)
 still work?

**Comment by mypil** [comment]
@ashavibapat - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
