### ISSUE TITLE
Removing Devices from Eval Lab

### ISSUE THREAD

**Issue by gatesry** [MicrosoftDocs/microsoft-365-docs#10897]
Hello, under the **Request for more devices** it references `..When all existing devices are used and deleted, you can request for more devices.` The current documentation doesn't precisely specify how to delete devices. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 302ee74c-812a-51b2-13e5-7b5daaa411f7
* Version Independent ID: 37fca1db-b257-588f-db65-4d5c6d7fd53f
* Content: [Microsoft Defender for Endpoint evaluation lab](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluation-lab?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/evaluation-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/evaluation-lab.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by Darktortue** [comment]
Any updates on this issue ?

**Comment by mjcaparas** [comment]
Devices are deleted when they expire.
