### ISSUE TITLE
Defender for Endpoint tenant license name

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/microsoft-365-docs#10906]
Wondering if "Defender for Endpoint tenant" is new limited license, or part of Defender for Endpoint Plan 1 or Plan 2? 

Thanks for a short update.

Best regards
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 415606ab-27e9-e125-d868-1e4636771d36
* Version Independent ID: 415606ab-27e9-e125-d868-1e4636771d36
* Content: [Use network protection to help prevent macOS connections to bad sites](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection-macos?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection-macos.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection-macos.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@TobiasAT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10965

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by TobiasAT** [comment]
@msbemba  Thanks for the clarification and update.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TobiasAT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
