### ISSUE TITLE
Am I missing something - why is there no column for "recipient" in the admin quarantine?

### ISSUE THREAD

**Issue by pctsltd** [MicrosoftDocs/microsoft-365-docs#1090]
It leaves it very time consuming to identify who the emails are aimed at, as you have to go into each email in the quarantine  - to see the recipient. Am I missing something here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an administrator in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@pctsltd - Thank you for submitting feedback.

Please refer to this section in the doc- **[To filter results and find quarantined messages and files
](https://docs.microsoft.com/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files#to-filter-results-and-find-quarantined-messages-and-files)** where you will see the instructions on how you can filter by the Recipient email address. Please also see below screen shot for the same info.

![image](https://user-images.githubusercontent.com/47188252/72813961-a6a7b580-3c3a-11ea-8101-2680a1702bb2.png)


We hope this helps to answer your query.

**Comment by pctsltd** [comment]
Thanks for that but why does it not appear as a column that can be turned on for the main display like the sender email address can be selected?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mypil** [comment]
@pctsltd - I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so technical support can answer your technical queries. Based on outcome, let us know if it is something that can be called out in the docs. Thank you!
