### ISSUE TITLE
Microsoft Defender for Endpoint for Servers Licensing No Longer Available for Purchase

### ISSUE THREAD

**Issue by hh-trj** [MicrosoftDocs/microsoft-365-docs#10901]
Under the section "Options for onboarding servers", one of the options listed is "Microsoft Defender for Endpoint for Servers".

Our CDW account manager and their internal Microsoft resource are saying that this license was discontinued by Microsoft in September 2022. If this is correct, it should be removed from the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec57328d-4b17-abe6-001e-c5ecb2f00746
* Version Independent ID: be98599a-b690-a3e6-c610-8da71fd80d76
* Content: [Compare Microsoft endpoint security plans](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide#options-for-onboarding-servers)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @hh-trj and thank you for the feedback. I've updated the article and the changes should be live later today. https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/18848
