### ISSUE TITLE
Encryption for emails but not for documents

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/microsoft-365-docs#1091]
Is this possible that we can configure a single label to encrypt emails and the same label should also be available to classify documents without encryption? for e.g. in case of "Let users assign permissions when they apply the label"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Restrict access to content by using encryption in sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@prashant1380  What you're asking for isn't supported - per app configuration for a label. You're welcome to create a UserVoice suggestion for this and you might find it useful to check here first: https://msip.uservoice.com/forums/600097-azure-information-protection?category_id=320548
