### ISSUE TITLE
MS Def 4Cloud to 365 Def Portal

### ISSUE THREAD

**Issue by blackishpanther** [MicrosoftDocs/microsoft-365-docs#10919]
Yea but where lol, you say it's moving there and provide a link the Defender but when you get there you fail to show where exactly you've hidden MS Defender for Identity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0cb96f5d-6738-30e2-de75-cc6fa0b2d940
* Version Independent ID: 0cb96f5d-6738-30e2-de75-cc6fa0b2d940
* Content: [Redirecting accounts from Microsoft Defender for Identity to Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-mdi-redirection?view=o365-worldwide&branch=pr-en-us-18255)
* Content Source: [microsoft-365/security/defender/microsoft-365-security-mdi-redirection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-security-mdi-redirection.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by blackishpanther** [comment]
No one able to find it?

**Comment by msbemba** [comment]
@blackishpanther Thank you for your feedback. Here is a quick reference on where you can find Defender for identity in M365 Defender page - https://learn.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-center-mdi?view=o365-worldwide#quick-reference

Hope this helps!

Thanks
Sri

**Comment by blackishpanther** [comment]
I dont see anything that looks like MS Def for Identity, what path am I
supposed to be following as far as that little matrix you sent? What are
the steps there or are they all stand-alone separate things?

**Comment by Cee3097** [comment]
They don't stand alone. md has been initiated since 2020

**Comment by Cee3097** [comment]
U have to go to braille, don't use def

**Comment by blackishpanther** [comment]
Sorry not familiar with that

**Comment by blackishpanther** [comment]
Why do that? Do you feel better?

**Comment by Cee3097** [comment]
Receese's cup

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@blackishpanther There is a new release for Defender for Identity release 2.198which was released on Feb 15. More information can be found on the below link and it explains the changes and how to access resources in M365 defender

https://learn.microsoft.com/en-us/defender-for-identity/whats-new#defender-for-identity-release-2198

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @blackishpanther Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
