### ISSUE TITLE
confusing explanation

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/microsoft-365-docs#10923]
Is it just me, or the text in 'Policy conflict handling follows the order below' is confusing?
(https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-ip-domain?view=o365-worldwide#policy-conflict-handling-follows-the-order-below)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0362931f-fb4c-ca1f-801e-b58a18613eae
* Version Independent ID: ed70b560-7c32-81b4-f138-6f58af9ef696
* Content: [Create indicators for IPs and URLs/domains](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-ip-domain?view=o365-worldwide#policy-conflict-handling-follows-the-order-below)
* Content Source: [microsoft-365/security/defender-endpoint/indicator-ip-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/indicator-ip-domain.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@TheITguy666 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10995

Once the author reviews and approves, the changes will be live.

Thanks
Sri

**Comment by Cee3097** [comment]
Read

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TheITguy666 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
