### ISSUE TITLE
M365 Anti-Spam block lists

### ISSUE THREAD

**Issue by shtau1** [MicrosoftDocs/microsoft-365-docs#1092]
In the area with the descprition: 
Always mark email from the following senders or domains as spam
The Block Lists doesn't provide any information about wildcards, positive or negative. Can they be used? If so, what is their format? If I block a domain, is it's sub-domains blocked? How do I do that? I can't find any language on this. You can do this on Barracuda and other Spam filtering appliances, it would make sense if you could do so in this. Even if there is no ability for wildcards, it should be stated as such and there should be information about whether there is intent to have wildcards or not. 

(https://protection.office.com/antispam) under "edit policy"

**Comment by mypil** [comment]
@shtau1 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by shtau1** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies Sorry, giving feedback in Github is new to me. I hope this helps. Also, my feedback relates to any Microsoft Docs page that relates to the above mentioned spam filter policies.

**Comment by msbemba** [comment]
@shtau1 Thank you for your feedback, unfortunately, there is no option use to wild cards in the policy section. I have added a note for clarity via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1177


Thanks
Sri

**Comment by mypil** [comment]
@shtau1 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/357aaf30b411c979bb7517ab4770d4f46c40d59c. 


Thank you for your contribution to make the docs better! Much appreciated!
