### ISSUE TITLE
User reported message settings has moved

### ISSUE THREAD

**Issue by sadayori** [MicrosoftDocs/microsoft-365-docs#10938]
"User reported message settings" has moved

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1541fb66-1414-579d-344c-fc1e25ba4ea0
* Version Independent ID: 1541fb66-1414-579d-344c-fc1e25ba4ea0
* Content: [How-to deploy and configure the report message add-in - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTBen
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@sadayori Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10992

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by Ratulch** [comment]
PR#10992 is merged. Closing this issue.
