### ISSUE TITLE
EDM Upload Agent

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/microsoft-365-docs#1093]
Is there a list of commands somewhere for the agent? Currently it seems there is no way to remove a data store, but if you would like to make changes to the columns in the data store it will not allow you to refresh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification#feedback)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by GiantCrocodile** [comment]
I ran the tool with an invalid argument and got this returned:

```
EdmUploadAgent.exe /?
Command failed.
Error Type: System.ArgumentException
Error Message: Unknown command. Command: ?.
Parametername: ?

 EdmUploadAgent Tool.

 Usage: EdmUploadAgent.exe Command Parameters

 Examples:
     EdmUploadAgent.exe /Authorize
     EdmUploadAgent.exe /CreateHash /DataFile [data file] /HashLocation [hash file location]
     EdmUploadAgent.exe /UploadHash /DataStoreName [DS Name] /HashFile [hash file]
     EdmUploadAgent.exe /UploadData /DataStoreName [DS Name] /DataFile [data file] /HashLocation [hash file location]
     EdmUploadAgent.exe /GetDataStore
     EdmUploadAgent.exe /GetSession /DataStoreName [DS Name]
     EdmUploadAgent.exe /CancelSession /DataStoreName [DS Name] /SessionId [Session Id]
     EdmUploadAgent.exe /ResumeSession /DataStoreName [DS Name] /SessionId [Session Id] /HashFile [hash file]
```

**Comment by chrfox** [comment]
Hi, @Mark7even - Thank you for your comment. I don't know if there is a list of commands for the EDM Upload agent.  I will ask the product group owner.

**Comment by chrfox** [comment]
@Mark7even - I have added a tip to the document that tells you how to get a list out of the supported command parameters.  Thanks for your suggestion.

**Comment by Mark7even** [comment]
Is that a comprehensive list? It seems incomplete.
