### ISSUE TITLE
Update wording from "MAU checks daily for updates" to "MAU checks updates periodically"

### ISSUE THREAD

**Issue by YongRhee-MSFT** [MicrosoftDocs/microsoft-365-docs#10947]
[Enter feedback here]
Can we change the wording from:
MAU checks daily for updates, and automatically downloads and installs them.
to
MAU checks updates periodically, and automatically downloads and installs them.

Thanks in advance,
Yong Rhee
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 092ef512-a100-4be8-8f63-1caaeb9e9559
* Version Independent ID: 5245c257-ea7e-57b9-03d9-bf2b63b3306c
* Content: [Deploy updates for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-updates?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/mac-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-updates.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@YongRhee-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10993

Once the author approves, the changes will be live.

Thanks
Sri
