### ISSUE TITLE
Details on how campaigns are made or how to make my own is missing

### ISSUE THREAD

**Issue by davidfox2** [MicrosoftDocs/microsoft-365-docs#10952]
On the threat explorer page it mentions that "Note: Campaigns include a specific subset of messages. [Learn more](https://go.microsoft.com/fwlink/?linkid=2153688)" however coming to this page I still don't really understand what subset of messages are included?! The page does a good job explaining what a campaign is and how to filter and use existing ones but I don't understand what actually triggers the creation of a campaign or how to make my own for attacks that have been persistent and large in scope for my organization. Additionally it appears there are some campaign queries under advanced hunting which is completely not mentioned on this page and I don't understand how they are related.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6c6c12e-33b7-8086-c4eb-4f5fbc751901
* Version Independent ID: 3b098f74-d3cc-c720-bd93-2fc5310cfe57
* Content: [Campaigns in Microsoft Defender for Office 365 Plan - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/campaigns?view=o365-worldwide#attitional-actions)
* Content Source: [microsoft-365/security/office-365-security/campaigns.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/campaigns.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
@davidfox2, from the Campaigns topic:

A campaign is a coordinated email attack against one or many organizations. Email attacks that steal credentials and company data are a large and lucrative industry. As technologies increase in an effort to stop attacks, attackers modify their methods in an effort to ensure continued success.

> Microsoft leverages the vast amounts of anti-phishing, anti-spam, and anti-malware data across the entire service to help identify campaigns. We analyze and classify the attack information according to several factors. For example:
>
> - **Attack source**: The source IP addresses and sender email domains.
> - **Message properties**: The content, style, and tone of the messages.
> - **Message recipients**: How recipients are related. For example, recipient domains, recipient job functions (admins, executives, etc.), company types (large, small, public, private, etc.), and industries.
> - **Attack payload**: Malicious links, attachments, or other payloads in the messages.

As you can probably infer, there's no way we can go into great detail about when/why malicious messages are identified as a campaign. There are lots of factors involved, and to describe them all would allow attackers to game the system.

Regarding campaigns in advanced hunting vs. campaigns on the Campaigns page, I don't think they're related. Campaigns in advanced hunting appear to be well known attacks where everyone uses the same name for them (and they're old; some from 2021). Campaigns on the Campaigns page are identified by Microsoft as part of a large or small coordinated attack by the same entity, and they might not be recognized industry-wide.

Does this make sense?

**Comment by davidfox2** [comment]
@chrisda, That does make sense, thank you for explanation. 

I had hopes to leverage the capability inside my own organization, for ongoing persistent phishing attacks that I would have loved to tie together with a campaign, but that isn't how they really work. I think some of the confusion occurred because of the wording that they help "Efficiently investigate and respond" when it seems like it is moreso about reducing InfoSec offices workload and not an new investigation tool. 


Could we start this page off with something like "Campaigns are managed by Microsoft"

And then put in a request for the threat explorer (somehow) to change the text "specific types of messages" to "are managed by Microsoft"

**Comment by chrisda** [comment]
@davidfox2, I changed the introduction of the campaigns topic to say:

> Campaigns in the Microsoft 365 Defender portal identifies and categorizes coordinated email attacks, including phishing and malware. Microsoft's management of email attacks into discreet campaigns will help you to:

Regarding the second thing, can you provide a screenshot? Sorry, Threat Explorer isn't my thing.

**Comment by davidfox2** [comment]
![image](https://user-images.githubusercontent.com/4884032/220831297-63538d81-04df-4a87-964f-42d7a94ccaf3.png)

Sorry the page I am referring to is the campaigns page in defender located here https://security.microsoft.com/campaignsv3

**Comment by yogkumgit** [comment]
@chrisda

**Comment by chrisda** [comment]
I updated the Campaigns page last month for correctness with the current UI, so I think I got everything.

Thanks for the feedback.

Closing
