### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by davidfox2** [MicrosoftDocs/microsoft-365-docs#10950]
https://learn.microsoft.com/microsoft-365/security/office-365-security/campaigns#attitional-actions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6c6c12e-33b7-8086-c4eb-4f5fbc751901
* Version Independent ID: 3b098f74-d3cc-c720-bd93-2fc5310cfe57
* Content: [Campaigns in Microsoft Defender for Office 365 Plan - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/campaigns?view=o365-worldwide#attitional-actions)
* Content Source: [microsoft-365/security/office-365-security/campaigns.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/campaigns.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@davidfox2, fixed.

In the future, you too can make updates like this yourself without opening a GitHub Issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
