### ISSUE TITLE
 Software evidence not exist 

### ISSUE THREAD

**Issue by KONIKPK** [MicrosoftDocs/microsoft-365-docs#10951]
[Enter feedback here]

This is not up to date this 
Software evidence not exist in menu. Update this doc. Many things are different. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 985384b1-44b5-e852-22ab-06936c4903b7
* Version Independent ID: 985384b1-44b5-e852-22ab-06936c4903b7
* Content: [Software inventory in Defender Vulnerability Management](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/tvm-software-inventory?view=o365-worldwide#software-evidence)
* Content Source: [microsoft-365/security/defender-vulnerability-management/tvm-software-inventory.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/tvm-software-inventory.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@KONIKPK Thank you for your feedback. I could see the software evidence in the menu

![image](https://user-images.githubusercontent.com/45987684/218488710-ec117a10-c592-4f4e-b775-d08af2c06dd3.png)

If you continue to not see this option in the Menu, There is a chance it could be a bug in your tenant. In that case, I'd recommend you contact support via the need help section on the admin center to raise a ticket with Microsoft Support.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @KONIKPK Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
