### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by LaPhi** [MicrosoftDocs/microsoft-365-docs#1095]
https://docs.microsoft.com/de-de/microsoft-365/compliance/controlling-your-data-using-customer-key?source=docs

Translation Error

"Diese werden als Trinkgeld und wichtigbezeichnet. "

The Translation is using "Trinkgeld". In German this means "Tip" (Restaurant)
"wichtigbezeichnet" --> "WICHTIG bezeichnet"

Corrrect:
These are called out as TIP and IMPORTANT. --> Diese werden als TIPP und WICHTIG bezeichnet.

**Comment by GiantCrocodile** [comment]
Yep, I can approve this; definitely wrong.

**Comment by KCCross** [comment]
Sending this over to the loc crew. Thanks for the headsup!

**Comment by TinaMcN** [comment]
@LaPhi thanks for the feedback.  I sent the article to be human translated.  @OfficeGlobal can you please make sure it is fixed during human translation and let us know when it's done.

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@LaPhi , @TinaMcN  the article has been HumanTranslated and published live

![image](https://user-images.githubusercontent.com/47977325/73261031-8b552100-41cb-11ea-99ae-5c237743317a.png)

**Comment by mypil** [comment]
@LaPhi - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
