### ISSUE TITLE
ManagedByFilter doesn't appear to be changeable.

### ISSUE THREAD

**Issue by tokitamo-ms** [MicrosoftDocs/microsoft-365-docs#10964]
[Enter feedback here]
This document describes how to modify EnabledEmailAddressTemplates and ManagedByFilter, but the sample appears to be incorrect.
Also, Set-EmailAddressPolicy does not have the -ManagedByFilter option.

Sample
Set-EmailAddressPolicy -Name StudentsGroups -EnabledEmailAddressTemplates "SMTP:@students.groups.contoso.com","smtp:@groups.contoso.com", "smtp:@students.contoso.com" ManagedByFilter {Department -eq 'Students'} -Priority 2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54783558-94f0-24ad-0fa3-1461a608fd10
* Version Independent ID: 53ebf483-a8ef-e242-9a2c-c285bbce65da
* Content: [Choose the domain to use when creating Microsoft 365 groups](https://learn.microsoft.com/en-us/microsoft-365/solutions/choose-domain-to-create-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/choose-domain-to-create-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/choose-domain-to-create-groups.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@tokitamo-ms Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10971

Once the author approves, the changes will be live.
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tokitamo-ms Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by tokitamo-ms** [comment]
@yogkumgit @msbemba Thank you for your work.
