### ISSUE TITLE
fix error in FAQ related to m365 apps for business support teams

### ISSUE THREAD

**Issue by iovex** [MicrosoftDocs/microsoft-365-docs#10963]
https://www.microsoft.com/en-us/microsoft-365/business/compare-all-microsoft-365-business-products

In above link,  I saw below FAQ, as I know , Microsoft 365 apps for business does not provide teams benefit, why it said that Microsoft apps for business can host meeting and video call ?
and made me confused.

`With Microsoft 365 Business Basic, Microsoft 365 Business Standard, Microsoft 365 Business Premium, and Microsoft Apps for Business plans, you can host online meetings and video calls for up to 300 people using Microsoft Teams.`

please correct this issue in time

**Comment by msbemba** [comment]
@iovex Thank you for your feedback. I notice that a change is required, however, we have access only to(https://learn.microsoft.com/) documents. We will internally try to forward this to the concerned team and let them know.

Hope this helps!

Thanks
Sri
