### ISSUE TITLE
Office 365 ATP Evaluation Mode documentation missing

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/microsoft-365-docs#1096]
When I go to the Office 365 Security & Compliance portal -&gt; Threat Management -&gt; Policy I now see a "new" option called ATP Evaluation mode. Opening the solution gives the following text: "Turn on Office 365 ATP easily and risk-free in evaluation mode to see how your protection can improve. Learn more about evaluation mode"

The learn more is a hyperlink referring to this page, but no info on what evaluation mode is and does to be found here - please include

/Kenneth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a177ba2-5cff-b0a0-6afa-717689db2884
* Version Independent ID: 802f6c49-9a14-e76f-6cf3-67862b40f18d
* Content: [Office 365 Advanced Threat Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp)
* Content Source: [microsoft-365/security/office-365-security/office-365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@kennethvs Thank you for your feedback. I'm checking this with the author and will get back to you shortly.

Thanks
Sri

**Comment by MSFTTracyP** [comment]
Though this is taking a very long time, I'm writing to say I'm aware of it and looking into this.

**Comment by SLeuthold** [comment]
Looping in @ryancairnes for visibility

**Comment by MSFTTracyP** [comment]
This has taken a long time, but documentation is beginning to appear such as https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-evaluation?view=o365-worldwide. Please keep an eye on future developments re. evaluating / trying out the product!
