### ISSUE TITLE
Did you mean Threat "Exporter" in the last section name?

### ISSUE THREAD

**Issue by ShaXam-King** [MicrosoftDocs/microsoft-365-docs#1097]
The last section name is "Some differences between Threat Exporter and real-time detections". I realize the feature is about exporting items for further analysis but this looks like a product name being that it is capitalized. I just thought it might need another look.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and real-time detections, new to Threat Explorer, changes to Threat Explorer, new to Office 365, Security, Cloud Security, new to Security in ATP, new ATP features - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer#feedback)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @ShaXam-King, great catch! No, we did not mean for it to be "exporter," and we appreciate you noticing this.
