### ISSUE TITLE
Wrong example url given

### ISSUE THREAD

**Issue by imnota** [MicrosoftDocs/microsoft-365-docs#10979]
The URL referenced in 1.6.1 is:
GET https://api.securitycenter.microsoft.com/api/machines/BaselineComplianceAssessmentByMachine

This does not appear to be correct url for certificate assessment.

Perhaps should be https://api.securitycenter.microsoft.com/api/machines/CertificateAssessmentByMachine based on the given response in 1.6.2?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29ca9c58-1c3f-6da6-ad14-464e98553f3a
* Version Independent ID: 29ca9c58-1c3f-6da6-ad14-464e98553f3a
* Content: [Certificate assessment methods and properties per device](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/export-certificate-inventory-assessment?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/export-certificate-inventory-assessment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/export-certificate-inventory-assessment.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
Thanks @imnota for finding this! 

@yogkumgit @imnota is correct and this should be updates to:

https://api.securitycenter.microsoft.com/api/machines/CertificateAssessmentByMachine 

Thanks,
Sinead

**Comment by msbemba** [comment]
@imnota Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11024

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by tiburd** [comment]
PR with change has been merged. Closing issue.
