### ISSUE TITLE
Page gives incorrect instructions

### ISSUE THREAD

**Issue by pvolve** [MicrosoftDocs/microsoft-365-docs#10973]
[Enter feedback here]

Clicking on the Domains link to go to the domains tab takes me to a page where I can select the domain. After that, nothing matches

"On the Domains page, select your domain, then select Start setup. You'll go back to the domains setup wizard to see the specific value you need to add."

There is no Start setup shown for the domain. After that, none of the steps apply

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 854cbadf-a802-0782-5a3a-b839995ff7fd
* Version Independent ID: b511466a-2505-4e90-548c-3fa5b6f2aedc
* Content: [Gather the information you need to create DNS records - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/information-for-dns-records?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/information-for-dns-records.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by msbemba** [comment]
@pvolve Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11023

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pvolve Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
