### ISSUE TITLE
Photo collection

### ISSUE THREAD

**Issue by Andreahn41** [MicrosoftDocs/microsoft-365-docs#10984]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3369738b-f096-6c2e-22d4-ee79057997c7
* Version Independent ID: d3fce773-a1e8-193a-b4fa-7f71b9ac3ea4
* Content: [Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-gb/microsoft-365/security/office-365-security/defender-for-office-365?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-Advanced-Threat-Protection-e100fe7c-f2a1-4b7d-9e08-622330b83653&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/defender-for-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Andreahn41 Thank you for your feedback. Ms defender for Office 365 does not have a photo collection. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Andreahn41 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
