### ISSUE TITLE
Commands for Prepare target user objects for migration

### ISSUE THREAD

**Issue by jackchuong** [MicrosoftDocs/microsoft-365-docs#10983]
I have a question about this part:
Prepare target user objects for migration

Users migrating must be present in the target tenant and Exchange Online system (as MailUsers) marked with specific attributes to enable the cross-tenant moves. The system will fail moves for users that aren't properly set up in the target tenant. The following section details the MailUser object requirements for the target tenant.

--> So I have to use New-MailUser and Set-MailUser to create and set attributes for users migrating to enable the cross-tenant moves ?
If I use New-ADUser and Set-ADUser to create and set attributes for users migrating , mailbox migrations will not work ?
Because target tenant is hybrid, I want to control User objects at AD on premise .

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@jackchuong Thank you for your feedback. Yes, it will work as long as the object is synced to Exchange Online as a Mail user.

In hybrid environments, you will need to set the appropriate attributes on the target ADUser.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jackchuong Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jackchuong** [comment]
I apologize for the unclear question, my question is :
I use New-ADUser and Set-ADUser to create and set attributes for users migrating on my AD on premise , these users are synced to my Microsoft 365 tenant through ADCONNECT . How can I transfer these users to MailUser ?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@jackchuong Thank you for your feedback. Ideally, when you create a new-aduser if the target address is something else and not the domain in Cloud(onmicrosoft.com or mail.onmicrosoft.com) it creates these users as mail users in the cloud. Unfortunately, adding that information to this document would only create ambiguity. 

If you still have trouble creating mail users in Exchange online, I'd recommend you create a support ticket via the need help section on the admin center, so that a support engineer can assist you.

Hope this helps!

Thanks
Sri
