### ISSUE TITLE
Mailbox permissions blank for HelpDesk on MS 365 Admin Center

### ISSUE THREAD

**Issue by Mela-SAG** [MicrosoftDocs/microsoft-365-docs#10989]
[
Hi, 
since a coupple of Weeks my "Azure Helpdesk" User can't adit the "Mailbox permissions" , it is just empty... They have "Mail recipient" Role in EAC and also through the EAC work, but till a couple of Weeks this also work through the MS 365 Admin Center.... do I miss some Access?   

Best Regards and Thanks for the Help
Mela

]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b9d613a-f990-4045-f0d3-273ecc827db7
* Version Independent ID: ef031919-5994-8d21-1f62-ee0db6f235b0
* Content: [Give mailbox permissions to another user - Admin Help - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Mela-SAG Thank you for your feedback. This sounds like a technical issue with your tenant. I'd recommend you to contact Microsoft support via the need help section so that a support engineer can help you out.

Hope this helps!

Thanks
Sri

**Comment by Mela-SAG** [comment]
Thanks, I will do it.

**Comment by Mela-SAG** [comment]
@msbemba 
I get a Answerd by Microsoft:
_"This is to inform you that it is by design behavior from Microsoft that Exchange recipient admin role only has access to manage users from Exchange admin center. "_

I dont know, but I was prety sure this was also working from the MS 365 Admin console ...  is this true?

**Comment by msbemba** [comment]
Looks like that is correct. I can see that the Mail recipient role can only do the below 

![image](https://user-images.githubusercontent.com/45987684/220641694-920b2fdb-557a-427d-89b8-8a6fe78d15b9.png)

Which does not include Granting mailbox permissions.

Hope this helps!

Thanks
Sri
