### ISSUE TITLE
The “Document name matches patterns” menu is missing

### ISSUE THREAD

**Issue by AiHirano** [MicrosoftDocs/microsoft-365-docs#10980]
The following document says that “Document name matches patterns” is supported for Conditions SharePoint and Conditions OneDrive accounts, but it does not actually appear in the operation menu. Is this a correct description?”

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-policy-reference.md

**Comment by mocca1103** [comment]
In my settings menu,  “Document name matches patterns” also does not appear  for Conditions SharePoint and Conditions OneDrive accounts. Only for Conditions Exchange. I appreciate if you cloud give us an answer.

**Comment by msbemba** [comment]
@AiHirano Thank you for your feedback. I could not find the option as well. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11025

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AiHirano Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
