### ISSUE TITLE
Add reference to "SharePoint Online"

### ISSUE THREAD

**Issue by paulbellacera** [MicrosoftDocs/microsoft-365-docs#1098]
The "Client communication with the server" section only mentions OneDrive for Business, but should include SharePoint Online to save any confusion. See addition in square brackets below for clarification.

Client communication with the server - Communication to [SharePoint Online and] OneDrive for Business across the Internet uses SSL/TLS connections. All SSL connections are established using 2048-bit keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd33fd3f-2ee9-139e-5cb3-afc28acaadcf
* Version Independent ID: cbc94676-e994-137b-6ff6-f2dee2940393
* Content: [Office 365 Encryption for Skype, OneDrive, SharePoint, and Exchange - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange#encryption-of-data-in-transit)
* Content Source: [microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@paulbellacera Thank you for the feedback. I have submitted a PR # https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1175 to modify the document.

Thanks
Sri

**Comment by mypil** [comment]
@paulbellacera - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/c730d15a21926028692c0604ac352106a8c2887e. 


Thank you for your contribution to make the docs better! Much appreciated!
