### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jt980** [MicrosoftDocs/microsoft-365-docs#1099]
When I click on the link titled "Start using the Azure HIPAA/HITRUST Blueprint" I get an "Operation Failed" error.  The actual link is "https://aka.ms/healthblueprint"  Then, the page goes blank.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545aa0d-ba68-3113-413b-0c0b176b08bd
* Version Independent ID: bb2ce8e1-7f40-e5ed-60c4-f8bb0912661d
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-hipaa-hitech)
* Content Source: [microsoft-365/compliance/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@jt980 - thanks for the feedback, this link doesn't work for me either - investigating with the website owners.

**Comment by robmazz** [comment]
@jt980 - here's the correct blueprint link (https://docs.microsoft.com/azure/governance/blueprints/samples/hipaa-hitrust/), updating the topic now. Thanks again for your feedback!
