### ISSUE TITLE
Prohibited Apps

### ISSUE THREAD

**Issue by mohamedmall** [MicrosoftDocs/microsoft-365-docs#110]
Need to add third Party Browsers to the list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9a87cc-07f9-22e5-ad76-c07e975dc1d1
* Version Independent ID: 65c2c9cf-f576-9059-5dac-bf94ba01cf0e
* Content: [Microsoft Managed Desktop app requirements](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/mmd-app-requirements)
* Content Source: [microsoft-365/managed-desktop/get-started/mmd-app-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/managed-desktop/get-started/mmd-app-requirements.md)
* Service: **m365-md**
* GitHub Login: @TrudyHa

**Comment by jdeckerms** [comment]
@mohamedmall Browsers are restricted by the portion of the article that states "Act as an app store or have built-in extension manager".
