### ISSUE TITLE
Helpful page

### ISSUE THREAD

**Issue by IhuanHarian** [MicrosoftDocs/microsoft-365-docs#11005]
[This page is helpful and clearly stated. However, finding this setting in the first placehad been very hard, until I eventually came across this page. On the contrary, the send as delegation is configured by default in shared mailboxes and it makes things so much easier.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b725ac58-0fa5-9f7d-84fa-a8541477fe0e
* Version Independent ID: f2acd0d0-60b8-0744-e241-06fb753aa5d1
* Content: [Allow members to send as or send on behalf of a group](https://learn.microsoft.com/en-us/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@IhuanHarian Thank you for your feedback. If you would like to see any changes, feel free to mention them in your feedback as well.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  There are no changes needed in the document and the issue can be closed.

Thanks
Sri
