### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/microsoft-365-docs#11009]
Broken link for General --> Configure Email Notifications
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-email-notifications?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81812335-239a-b679-b94d-4edc51881fc9
* Version Independent ID: ff002d4e-5cf0-258f-cb80-1d5e09ff394a
* Content: [Configure general Defender for Endpoint settings](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/preferences-setup?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/preferences-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/preferences-setup.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@gb5757870 Thank you for your feedback. Configuration of vulnerability email notifications can be found at https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-vulnerability-email-notifications?view=o365-worldwide

There are no changes required in the said document

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @gb5757870 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by gb5757870** [comment]
Issue is not fixed. 
On this page: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/preferences-setup?view=o365-worldwide

General --> "Configure Alert Notifications" link takes to a page with 404 errors
![Snip20230217_49](https://user-images.githubusercontent.com/5389878/219471033-5a23402d-1230-4832-84b1-c70280264149.png)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@gb5757870 I don't see General --> "Configure Alert Notifications" link on this page https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/preferences-setup?view=o365-worldwide

Could you share a screenshot of the page with that option?

Thanks
Sri

**Comment by gb5757870** [comment]
Hi, here is the screenshot
[image: image.png]

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@gb5757870 I see the 404 error, but how did you get to the broken link? Is the link mentioned anywhere on this or any other page page - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/preferences-setup?view=o365-worldwide ?

Thanks
Sri

**Comment by gb5757870** [comment]
@msbemba See the highlighted place which takes me to the broken link.
![Broken link](https://user-images.githubusercontent.com/5389878/220835385-ba0f1e69-1eda-477e-802d-01a556b1e5c3.png)

**Comment by msbemba** [comment]
@gb5757870 Thank you for your feedback. We have emailed the author to fix the broken link.

@yogkumgit  Email sent 2.24.2023

Thanks
Sri

**Comment by mjcaparas** [comment]
Fixes checked in. Updates should be reflected soon.
