### ISSUE TITLE
Update inbox hunting query for additional operation

### ISSUE THREAD

**Issue by tvjust** [MicrosoftDocs/microsoft-365-docs#11013]
https://learn.microsoft.com/en-us/microsoft-365/security/defender/alert-grading-playbook-inbox-manipulation-rules?view=o365-worldwide#advanced-hunting-queries
The first Kusto query could probably be enhanced and include the **UpdateInboxRules** Operation to include rules created via outlook desktop client as it can also be used to create inbox rules. 

https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/updateinboxrules-operation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3a5719-43f6-1ac0-9210-68954fb56800
* Version Independent ID: 3b3a5719-43f6-1ac0-9210-68954fb56800
* Content: [Alert grading for suspicious inbox manipulation rules](https://learn.microsoft.com/en-us/microsoft-365/security/defender/alert-grading-playbook-inbox-manipulation-rules?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/alert-grading-playbook-inbox-manipulation-rules.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/alert-grading-playbook-inbox-manipulation-rules.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@tvjust Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11046

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tvjust Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
