### ISSUE TITLE
Inactive users

### ISSUE THREAD

**Issue by roaima** [MicrosoftDocs/microsoft-365-docs#11011]
A recent email from Microsoft regarding Non Profit licence usage, "Action required: We need your help! Help us serve more nonprofits" has this page linked as "Identifying inactive users" to the target https://emails.azure.microsoft.com/redirect/?destination=https%3A%2F%2Faka.ms%2FIdentifyingInactiveusers&p=bT1kN2IzNTRmYy0wMzI1LTQwZTEtYjRiZi03YmY0NDdmNDNkZWQmdT1hZW8mbD1JZGVudGlmeWluZ0luYWN0aXZldXNlcnM%3D

Unfortunately there is nothing obvious on this page that addresses the link. Presumably the email author knows something that we (or I?) don't, as otherwise they wouldn't have linked this page. So, how do we use any of these reports to identify inactive users?

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1eaa6e98-66e9-aad3-2d67-543c22f4ce4b
* Version Independent ID: 26bddf9e-f338-329f-76e5-302a1343f7f1
* Content: [Microsoft 365 admin center activity reports - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/activity-reports.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@roaima Thank you for your feedback. It is not practically easy to manage inactive users using the reports. However, To manage inactive users, the below document can help

https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-manage-inactive-user-accounts

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @roaima Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
