### ISSUE TITLE
Security menu option missing

### ISSUE THREAD

**Issue by chrisbues** [MicrosoftDocs/microsoft-365-docs#1101]
"To turn the Microsoft Threat Protection service on, go to Settings &gt; Microsoft Threat Protection &gt; Opt-in / Opt-out in the Microsoft 365 security center."

"Settings" isn't shown in the first screenshot, nor in our actual tenant with E5 licenses. Is there additional detail needed on this page for this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7f625c-f3ef-882d-231f-6fef18e14137
* Version Independent ID: 3f335d54-6d65-d49a-e517-2c3a9a95e44d
* Content: [Turn on Microsoft Threat Protection in the Microsoft 365 security center - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-enable#feedback)
* Content Source: [microsoft-365/security/mtp/mtp-enable.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/mtp-enable.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by lomayor** [comment]
Checking. @chrisbues, can you confirm if you're a global administrator or a security administrator in your tenant?

**Comment by psk-uloba** [comment]
We have the same issue, and yes I have GA rights on the tenant.

**Comment by chrisbues** [comment]
@lomayor Yup, GA on the tenant. Just checked today again - Settings is still missing.
![image](https://user-images.githubusercontent.com/30657552/73081137-131df100-3e95-11ea-8f65-bfd4cf290666.png)

**Comment by m-xen** [comment]
We have the same issue

**Comment by chrisbues** [comment]
Settings isn't in the Gear menu either, so it's really not on the page at all, at least for us.

**Comment by lomayor** [comment]
Thanks for clarifying. Waiting on guidance from engineering. 

Can you also confirm that you have [the required E5 license](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/prerequisites#licensing-requirements)?

This might be a bug.

**Comment by lomayor** [comment]
Thanks for clarifying, @chrisbues. I'm waiting for guidance from engineering.

Can you also confirm that you have the [required E5 licenses](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/prerequisites#licensing-requirements)?

**Comment by lomayor** [comment]
@chrisbues, please also try accessing the settings page directly:

https://security.microsoft.com/settings

**Comment by chrisbues** [comment]
Settings just shows an empty list:
![image](https://user-images.githubusercontent.com/30657552/73098025-87b55780-3eb6-11ea-9c20-4b3b31106002.png)

**Comment by chrisbues** [comment]
We have Office 365 A5 and Office 365 E5, Enterprise Mobility + Security E5, and Windows E5

**Comment by lomayor** [comment]
Thanks again. It might take a while before I get a response from engineering. Meanwhile, please don't hesitate to contact support for assistance.

![image](https://user-images.githubusercontent.com/24801435/73102894-ad873000-3ea7-11ea-8b3a-f4aaf7b3ee2d.png)

**Comment by mugshots311** [comment]
We are having the same problem

**Comment by lomayor** [comment]
@chrisbues, everyone -- engineering needs more information from you to really look into this, specifically your tenant IDs. Please file corresponding support cases through the portal, mentioning "Microsoft Threat Protection" and providing screenshots whenever possible.

Based on our initial investigation, this only occurs on tenants that don't have the required licenses. I understand that some orgs will have atypical license combinations or have licenses spread across multiple tenants. We'll need to check individual tenants to understand what's going on.

**Comment by lomayor** [comment]
Closing docs issue until further updates from Support & Engineering.

**Comment by DeanGross** [comment]
Please reopen this, the problem still exists.

**Comment by zlDev** [comment]
2 months later this problem still exists.

**Comment by zlDev** [comment]
@chrisbues were you able to resolve this issue?

**Comment by ConsistentTheory** [comment]
Havint the same problem. I'm GA and I have Enterprise Mobility + Security E5.
![image](https://user-images.githubusercontent.com/26940111/76530782-8515be00-6474-11ea-828e-1d3e522683b3.png)
This is my menu and Settings is missing, if I go directly to the link the page is blank.

**Comment by lomayor** [comment]
Just want to leave a note here that this has been confirmed to be a licensing issue by zlDev in another thread. For everyone who encounters the same issue, kindly check the eligibility requirements here:

https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-enable
