### ISSUE TITLE
Custom Notes for 1:1 Bookings fixed?

### ISSUE THREAD

**Issue by samadane** [MicrosoftDocs/microsoft-365-docs#11016]
Has this been fixed?

https://learn.microsoft.com/en-us/microsoft-365/bookings/power-automate-integration?view=o365-worldwide#known-issues-and-limitations

"Some Bookings parameters are not populated. Cancel Reason and Custom Notes for 1:1 Bookings are not populated. The fix for this will be rolled out soon."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 503b7737-253c-3d94-6ca2-816dc9754b4d
* Version Independent ID: 503b7737-253c-3d94-6ca2-816dc9754b4d
* Content: [Use Power Automate connectors to build Bookings workflows](https://learn.microsoft.com/en-us/microsoft-365/bookings/power-automate-integration?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/power-automate-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/power-automate-integration.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @samadane Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by samadane** [comment]
@msbemba thank you. It seemed like custom notes were populating in flow last week.
