### ISSUE TITLE
Add or edit custom DNS records section

### ISSUE THREAD

**Issue by resinizar** [MicrosoftDocs/microsoft-365-docs#11015]
When I click domain (step 3) there is nothing that says DNS settings or custom records (step 4). 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0012093-49ca-c2f6-a3f3-4e4252fca609
* Version Independent ID: 22784dda-ff03-971b-4d6e-5b0152f62942
* Content: [Add a domain to Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide#add-or-edit-custom-dns-records)
* Content Source: [microsoft-365/admin/setup/add-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-domain.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by msbemba** [comment]
@resinizar Thank you for your feedback. I was able to locate DNS records once you click the domain that you would like to add a custom record. I have made changes accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11043

![image](https://user-images.githubusercontent.com/45987684/219699025-f4613b9b-81f6-46c2-9380-cf32a09945ec.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @resinizar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
