### ISSUE TITLE
Sha sum for client analyzer is incorrect

### ISSUE THREAD

**Issue by maximvelichko** [MicrosoftDocs/microsoft-365-docs#11019]
Sha sum for client analyzer is not correct. I suggest removing it from the page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95ba8ed0-8234-d514-f06e-3ce69e60bfec
* Version Independent ID: 51d6d3ae-6100-7acb-af46-e8ec6b9fe84f
* Content: [Run the client analyzer on macOS or Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
It has been updated.
