### ISSUE TITLE
Article needs updated licensing information added.

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/microsoft-365-docs#11029]
This SMS feature requires Teams Premium license

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a4e2dea-de84-ec37-adee-776f2b4eea92
* Version Independent ID: 3ca1c4a4-b32f-ea7b-ebfb-d4057d82938d
* Content: [Configure SMS text notifications and reminders in Microsoft Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/bookings-sms?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/bookings/bookings-sms.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-sms.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@NickElniff Thank you for your feedback. We'll be providing unlimited SMS notifications through March 1, 2023, for customers with Bookings licenses. Closer to the date, the document will be updated by the author on what the new licensing requirements would be.

The same has been added as a note to the document. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @NickElniff Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
