### ISSUE TITLE
Confirm all actions are logged?

### ISSUE THREAD

**Issue by alexp12344** [MicrosoftDocs/microsoft-365-docs#1102]
This article states
"When Microsoft releases a new mailbox action (particularly actions that help protect your organization and help with forensic investigations), the action is automatically added to the list of mailbox actions that are audited by default. This means you don't need to monitor add new actions on mailboxes."
This is something previously we enabled via script.

But this article suggests that there are some actions that aren't included in the default logging config - is that correct?
https://o365reports.com/2020/01/21/enable-mailbox-auditing-in-office-365-powershell/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing#feedback)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@alexp12344, that's correct. Not all available mailbox actions are audited by default as described in the tables in this section: https://docs.microsoft.com/microsoft-365/compliance/enable-mailbox-auditing#logon-types-and-mailbox-actions.

If you manually select what's audited, you can potentially select everything. But, if a new audited action becomes available, you'll need to a) discover it, and b) manually add it yourself.

Ultimately, it's a balance. The default audited actions should be sufficient for most organizations. But, if you determine they aren't, you'll need to go manual for some or all of your mailboxes.

**Comment by chrisda** [comment]
@alexp12344, a clarification and related update to the topic:

'On by default' is on for everyone: Office/Microsoft E3, E5, etc., but audit log searches in the Office 365 Security & Compliance Center or via the Office 365 Management Activity API **only return results for users (mailboxes) with E5 licenses**.

To return results for mailboxes with any other licenses types, you need to use the **Search-MailboxAuditLog** or **New-MailboxAuditLogSearch** cmdlets in Exchange Online PowerShell or the two available Exchange admin center (EAC) reports: **Export mailbox audit logs** or **Run a non-owner mailbox access report**.

Thanks for the feedback, and sorry for my initial confusion.
