### ISSUE TITLE
Wrong text and link to the Billing section

### ISSUE THREAD

**Issue by Lightpeek** [MicrosoftDocs/microsoft-365-docs#11022]
Hello

In the section [View who has licenses for a purchase or trial subscription](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins?view=o365-worldwide#view-who-has-licenses-for-a-purchase-or-trial-subscription) there is a link to the **Licenses** page. However, it is not on the **Licenses** page you have the filter, it is on the **Your products** page. So the text in bullet #1 should be as follows:

1. In the admin center, go to the Billing > [Your products](https://admin.microsoft.com/Adminportal/Home#/subscriptions) page.

Kind regards
Roger Lysnes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e05e10b-691c-2357-25f5-1a9e810c662d
* Version Independent ID: 0d789543-2033-d759-1fe9-69f24e458c13
* Content: [Manage self-service purchases and trials (for admins)](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Lightpeek Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11044

Once the author approves, the changes will be live.

Thanks
Sri
