### ISSUE TITLE
DMARC - 'No' outputs missing

### ISSUE THREAD

**Issue by DarthMuppet54** [MicrosoftDocs/microsoft-365-docs#11021]
The two outer small purple decision boxes, 'is z a subdomain of x' and 'is y a subdomain of z', are both missing the 'NO' output.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email, setup steps - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-dmarc-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/email-authentication-dmarc-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/email-authentication-dmarc-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us in resolving this issue. Thanks

**Comment by DMoenks** [comment]
That's something a colleague and I also wondered more than once and we just guessed it might result in a DMARC failure. Would be great to actually see this clarified in the process schematic though 😃

**Comment by tiburd** [comment]
@chrisda 
Thanks for fixing!
Closing this issue.
