### ISSUE TITLE
Access content public sharepoint CDN with img tag html 

### ISSUE THREAD

**Issue by ariefarfiansyah** [MicrosoftDocs/microsoft-365-docs#11026]
Dear Team, 

Is it possible if we show some picture using tag html image from sharepoint using public cdn ?

for example like this : 

`"<img src="$publiccdnlink">"`

I ask this because for now if we want to show the image from publiccdn we should add Header : 
Referer : our tenant sharepoint.

Thanks.

**Comment by denisebmsft** [comment]
Hello @ariefarfiansyah! Can you please tell us to which article(s) your feedback applies?

**Comment by ariefarfiansyah** [comment]
Hi @denisebmsft thanks for the reply. 

I follow this article and it works, but i cannot apply the file (image) with image tag html. 

https://www.wictorwilen.se/blog/sharepoint-online-cdn-features-announced-in-preview/

Thanks.

**Comment by msbemba** [comment]
@ariefarfiansyah Thank you for your feedback. We work on Microsoft documents and in case you have suggestions or modifications on an existing document, we will be more than happy to help you. In your case, it looks like a technical question/issue, so I'd recommend you open a support ticket via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ariefarfiansyah Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
