### ISSUE TITLE
Power Apps missing in time table

### ISSUE THREAD

**Issue by RebekkaAalbers** [MicrosoftDocs/microsoft-365-docs#1103]
Power Apps is missing in the time table how long it takes for message to service in audit log search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#search-the-audit-log)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@RebekkaAalbers Thanks for question. I will try to get answer from engineering, but what is your experience? In your organization, are Power Apps events showing up after 30 minutes or 24 hours?

**Comment by RebekkaAalbers** [comment]
30 minutes

**Comment by markjjo** [comment]
@RebekkaAalbers Thanks for following up.

**Comment by markjjo** [comment]
@RebekkaAalbers The table has been updated: PowerApps = 30 minutes
