### ISSUE TITLE
This page references a UX that is not present in the workflow

### ISSUE THREAD

**Issue by pvolve** [MicrosoftDocs/microsoft-365-docs#11035]
This page says: From the How you'll sign in page on the Microsoft 365 Business Standard sign up, choose Create a new business email account (advanced).

There is no such option in signing up for Microsoft 365 Business Standard

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc903dd4-94b0-1461-d9a4-5b457d5ac3b6
* Version Independent ID: 7a8eff98-2ba7-81f7-2a3d-71bdd7e1994a
* Content: [Set up Microsoft 365 Business Standard with a new or existing domain - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/setup-business-standard?view=o365-worldwide&source=docs#set-up-microsoft-365-for-business)
* Content Source: [microsoft-365/admin/setup/setup-business-standard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/setup-business-standard.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @pvolve Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
