### ISSUE TITLE
Microsoft Lighthouse deployment plan issues

### ISSUE THREAD

**Issue by SFMextrico** [MicrosoftDocs/microsoft-365-docs#11040]
Hello,

We've long been wanting to use Lighthouse, but it's full of issues.
At the moment the most impactful for us is that we simply cannot use the Deployment Plan deploy at all. No matter partner tenant permissions or customer tenant permissions, both for our DAP and GDAP customers.

We're simply receiving an "An error has occured while generating validation data. Please try again." when trying to deploy any task via Lighthouse.

Most of the time we're also receiving errors for the perimeters like includ/exclude users with "There was an error with this setting"

We cannot see any error logs, or anything of the like - is it a specific role, maybe even a custom role, we need in partner or customer tenant that needs to be given before we can use it?
Can we get any sort of data from anywhere with regards to our issues, so that we can troubleshoot it ourselves, or do we simply need to accept that Lighthouse is a broken / unfinished product?

It seems like Lighthouse have been put in GA way to soon

**Comment by msbemba** [comment]
@SFMextrico Thank you for your feedback. Sorry to hear that, I'd recommend you contact our support team via the need help section on the admin center so that a support engineer can assist you with the technical issues.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SFMextrico Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by simonburbery** [comment]
Unfortunately, I am reporting we have the same problem 9 months later.  I will log a support request.
