### ISSUE TITLE
Reference to ‘Clutter’ need revising 

### ISSUE THREAD

**Issue by Mal-G** [MicrosoftDocs/microsoft-365-docs#1104]
‘Clutter’ is no more, document needs updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459b0779-5ac5-c20d-d01d-403276c84745
* Version Independent ID: 5a502f35-ec76-5902-923c-4e4cdbbf334b
* Content: [Report junk email and phishing scams in Outlook on the web  - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop#feedback)
* Content Source: [microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Mal-G  Thank you for the feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1176

Thanks
Sri

**Comment by chrisda** [comment]
PR merged live. Closing
