### ISSUE TITLE
Documentation out of data - "Device Management" panel no longer there

### ISSUE THREAD

**Issue by truekonrads** [MicrosoftDocs/microsoft-365-docs#11054]
Hello,

This is how the "Endpoints" section looks like. It does not have "Devices" element:

![image](https://user-images.githubusercontent.com/1421150/219829717-efcfcdad-76f8-4338-b7a0-4758d996d29b.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f044e756-d5d8-5db6-edbb-f042b1b22b3c
* Version Independent ID: 5d016fa2-3407-e757-1595-118728158c46
* Content: [Onboard Windows devices using a local script](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-script?view=o365-worldwide#offboard-devices-using-a-local-script)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-script.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-script.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@truekonrads Thank you for your feedback. I have checked and it is under **Settings**-->Endpoints, 

![image](https://user-images.githubusercontent.com/45987684/221007798-738ff519-f64f-4759-8b22-4cc31c204a73.png)

if you unable to view the option, I'd recommend reaching out to support to fix the problem.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @truekonrads Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by truekonrads** [comment]
Best update the documentation to reflect the actual path

**Comment by msbemba** [comment]
@truekonrads Thank you for the response. The document has been updated with the actual path--> In the navigation pane, select Settings > Endpoints > Device management > Onboarding.

Hope this helps!

Thanks
Sri
