### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by asaburrows** [MicrosoftDocs/microsoft-365-docs#11055]
I changed my nameservers to point to microsoft but the domain wizzard in office 365 still thinks they are pointing to my old provider and does not give me the option to add DNS records. Frustrating.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3db0d1ba-e79a-77ab-fced-a8a80f5b07b3
* Version Independent ID: 30dda152-9ad2-24c3-caf6-e00f3443b173
* Content: [Change nameservers to set up Microsoft 365 with any domain registrar - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by msbemba** [comment]
@asaburrows Thank you for your feedback. This sounds more like a technical issue, I'd recommend you contact Microsoft support via the need help section on the admin cetner.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @asaburrows Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
