### ISSUE TITLE
4.18.2301.6 Breaks the ability of 2022 VMs to Boot

### ISSUE THREAD

**Issue by rinaldym** [MicrosoftDocs/microsoft-365-docs#11056]
4.18.2301.6 Microsoft Defender update breaks the ability of my 2022 VMware hosted VMs to boot up when SecureBoot is enabled

**Comment by yogkumgit** [comment]
@rinaldym Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
