### ISSUE TITLE
Australia?

### ISSUE THREAD

**Issue by sadayori** [MicrosoftDocs/microsoft-365-docs#11062]
hi folks,
i noticed this product was available for our new zealand cousins. Are there plans for this product be available for Australia?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1868d9e3-d5d4-6978-69dd-820a6f53e507
* Version Independent ID: b185508c-951f-4684-9f4d-ae6eea02df74
* Content: [Get Microsoft 365 for Campaigns - Microsoft 365 Business Premium](https://learn.microsoft.com/en-us/microsoft-365/business-premium/get-microsoft-365-campaigns?view=o365-worldwide)
* Content Source: [microsoft-365/business-premium/get-microsoft-365-campaigns.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-premium/get-microsoft-365-campaigns.md)
* Service: **microsoft-365-security**
* Sub-service: **m365bp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@sadayori Thank you for your feedback. At present- No, it is not available in Australia. If you would like to know more information, you can leave feedback on our main feedback portal - https://feedbackportal.microsoft.com/ so that a developer or a product will review and provide more information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@sadayori Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
