### ISSUE TITLE
Is it security- and privacy-wise safe to test Sensitive info types with real data?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1106]
Due to #870 we were asked to upload real world data to test a sensitive info type provided by Microsoft. Is it safe to do so? Like what are the security and privacy-wise aspects of uploading test data to the sensitive info types test function?

Is it the same level of privacy as if the function/feature would test data on e. g. a SharePoint Online? Does Microsoft uses this uploaded test data by their own for improving their own services/tests?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb7953e-5257-2578-4607-2d93940d6845
* Version Independent ID: 8e59d041-619e-d54f-f28e-faac2bc18ef2
* Content: [Create a custom sensitive information type in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type#feedback)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by GiantCrocodile** [comment]
Metadata missing due to some browser issue on my side. I refer to this document: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type#test-custom-sensitive-information-types-in-the-security--compliance-center

**Comment by mypil** [comment]
@GiantCrocodile - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@chrfox - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by chrfox** [comment]
@GiantCrocodile - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP.
