### ISSUE TITLE
Need clarification on Licensing Requirements on Microsoft 365 Security

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#11069]
Need clarification to the l**icensing requirements** section. Today:

> licensed through Microsoft Defender for Endpoint (per user), Windows Enterprise E5, Microsoft 365 Security, or Microsoft 365 E5, or have the VM licensed through Microsoft Defender for Cloud

There is no license called only **Microsoft 365 Security**. I assume that it should say **Microsoft 365 E5 Security**, or **Microsoft 365 F5 Security**? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb9a6dfb-2853-20fc-bd6c-2f636945b328
* Version Independent ID: 60586381-2d76-32bc-8e44-342ee36ada1c
* Content: [Onboard Windows devices in Azure Virtual Desktop](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@JonesMikael Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11092

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JonesMikael Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
