### ISSUE TITLE
Make it clear if the features mentioned requires E5 license, or provide a link to a comparision table/list

### ISSUE THREAD

**Issue by ken-chy** [MicrosoftDocs/microsoft-365-docs#11067]
Hi,

I noticed there is a "Tip" on this page (and also some other pages):

> If you're not an E5 customer, you can try all the premium features in Microsoft Purview for free.

However, it says nothing about which feature requires E5. I'm confused when I see this prompt. Does it mean all the features on the page requires E5 or not? It does not answer questions like "I have Office 365 E3, can I use this?"

If possible, please add a note under the title of the premium features, for example, "Require E5 license." Otherwise, adding a link to a feature comparison table/list or related documentation should reduce confusion.

Thank you.

Ken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 Groups, and SharePoint sites - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#enable-this-preview-and-synchronize-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Assigning to @chvukosw (not specific to this page & I don't own the text)

**Comment by cabailey** [comment]
Since I don't own this text, removing myself as assigned

**Comment by chvukosw** [comment]
Will take your comments into consideration as we make updates to the About the Purview solutions trail, which is linked to from the tip.
