### ISSUE TITLE
Error 400 on Get-MSCommerceProductPolicies -PolicyId AllowSelfServicePurchase

### ISSUE THREAD

**Issue by scursio-uefa** [MicrosoftDocs/microsoft-365-docs#11065]
Error when running the below:

PS C:\WINDOWS\system32> Get-MSCommerceProductPolicies -PolicyId AllowSelfServicePurchase
HandleError : Failed to retrieve product policy with PolicyId 'AllowSelfServicePurchase', ErrorMessage - The remote
server returned an error: (400) Bad Request. ErrorDetails - {"errorCode":"BadRequest","reason":"Invalid scope."}
At C:\Program Files\WindowsPowerShell\Modules\MSCommerce\1.7\MSCommerce.psm1:239 char:5
+     HandleError -ErrorContext $_ -CustomErrorMessage "Failed to retri ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,HandleError

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by JMMora** [comment]
Getting the same issue

**Comment by TobiasAT** [comment]
Same here, and the same issue as #4408 from March 2021.

**Comment by kainar** [comment]
Same Issue for me on our tenant.

**Comment by solon2099** [comment]
Same issue on our PROD and DEV tenant.

**Comment by db1066** [comment]
Same here, is there an alternate method to block app purchases in the meantime?

**Comment by db1066** [comment]
> 



> Same here, is there an alternate method to block app purchases in the meantime?

FYI

Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId CFQ7TTC0KP0N -Value "Disabled"

Still works, list of ID's are here [https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide](url)

**Comment by msbemba** [comment]
@scursio-uefa Thank you for your feedback. I was able to reproduce the issue. I'll check internally and update the document. 

Thanks
Sri

**Comment by JMMora** [comment]
I have a Microsoft open on this, but no answers since 2 days ago.

**Comment by Kees-v-D** [comment]
Also have a Microsoft case open for this, since Monday (issue first appeared to us last week on Friday). Last response from Microsoft (today) was that the backend team was working on a fix.

**Comment by TobiasAT** [comment]
Seems they fixed the issue, it's working again
