### ISSUE TITLE
Permission requirements incorrect

### ISSUE THREAD

**Issue by imnota** [MicrosoftDocs/microsoft-365-docs#11064]
The permissions requirements for applications are listed in 1.2 and 2.2 as "Software.Read.All", however, based on my testing these should be "Vulnerability.Read.All"

I would assume that the same would apply to delegated which should be "Vulnerability.Read"

Thanks

Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29ca9c58-1c3f-6da6-ad14-464e98553f3a
* Version Independent ID: 29ca9c58-1c3f-6da6-ad14-464e98553f3a
* Content: [Certificate assessment methods and properties per device](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/export-certificate-inventory-assessment?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/export-certificate-inventory-assessment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/export-certificate-inventory-assessment.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by imnota** [comment]
I've tested and confirmed that delegated requires "Vulnerability.Read"

**Comment by msbemba** [comment]
@imnota Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11127

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @imnota Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
