### ISSUE TITLE
Sample CSV file is no longer accurate.

### ISSUE THREAD

**Issue by roeben124** [MicrosoftDocs/microsoft-365-docs#11071]
[Enter feedback here]
The sample CSV provided is no longer accurate.  When using M365 admin center, the (attached) sample CSV provided has now 16 columns and added the "Alternate email address" column after the Fax column.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99474cca-d2bc-d602-71ba-5c20e894429a
* Version Independent ID: 5aa17d74-a77f-82ed-48db-ff10413784bb
* Content: [Add several users at the same time to Microsoft 365 - Admin Help - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/add-several-users-at-the-same-time?redirectSourcePath=%252fen-us%252farticle%252fAdd-several-users-at-the-same-time-to-Office-365-Admin-Help-1f5767ed-e717-4f24-969c-6ea9d412ca88&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/add-several-users-at-the-same-time.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/add-several-users-at-the-same-time.md)
* Service: **microsoft-365-enterprise**
[Import_User_Sample.csv](https://github.com/MicrosoftDocs/microsoft-365-docs/files/10793035/Import_User_Sample.csv)

* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@roeben124 Thank you for your feedback. I was able to test with the sample CSV file and it works. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11130

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @roeben124 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
