### ISSUE TITLE
PreferStaticProxyForHttpRequest required for offline servers

### ISSUE THREAD

**Issue by niarme-MSFT** [MicrosoftDocs/microsoft-365-docs#11085]
In the purple box for completely offline servers, it is _recommended_ that the PreferStaticProxyForHttpRequest value be modified to 1.  It has been found that this value is **required** in a scenario of offboarding a server from one tenant and onboarding to another tenant.  Documentation may need to be updated to reflect this as a required value.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/77701346/220476353-32da4acc-09b1-446d-8424-d0967b71a21f.png">

**Comment by yogkumgit** [comment]
@niarme-MSFT Please indicate which document you are referring to. Thanks

**Comment by niarme-MSFT** [comment]
@yogkumgit, the documentation is listed here: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide

**Comment by msbemba** [comment]
@niarme-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11148

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @niarme-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
