### ISSUE TITLE
Incorrect reference to -Trustee in instructions

### ISSUE THREAD

**Issue by jesslyn-omm** [MicrosoftDocs/microsoft-365-docs#11086]
Step 2  states:
Add-MailboxPermission -Identity <bookingmailbox@emailaddress> -User <adminusers@emailaddress> -AccessRights FullAccess -Deny:$false -AutoMapping:$false

Then Step 3 in the next section states
Add-RecipientPermission -Identity "daycare@contoso.com" -Trustee "Allie Bellew" -AccessRights SendAs -Confirm:$false

both return -Trustee errors in PowerShell
Add-MailboxPermission : A parameter cannot be found that matches parameter name 'Trustee'.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fcbd22b-e14b-fe97-7b7f-eb672e84d382
* Version Independent ID: f9a024d7-6600-4922-02b5-2c8ceeae13ab
* Content: [Add staff to Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/add-staff?view=o365-worldwide#make-a-bookings-user-a-super-user-without-adding-them-as-staff-in-bookings)
* Content Source: [microsoft-365/bookings/add-staff.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/add-staff.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jesslyn-omm Thank you for your feedback. While granting Mailbox permissions, you would not use the Trustee parameter, instead use it only when granting Recipient permissions. I was able to run the cmdlets without any issues.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jesslyn-omm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
