### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/microsoft-365-docs#11083]
The document doesn't include information on the Export functionality and the export limits (how many rows).
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3d3633-893d-9354-9402-c47ed7dec790
* Version Independent ID: fc12340b-403f-b531-04be-91f00a8f0af6
* Content: [Get started with Activity explorer - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-activity-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-activity-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@itishnitsa Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
