### ISSUE TITLE
Please correct the description of "Randomize scheduled task times"

### ISSUE THREAD

**Issue by narkuroki** [MicrosoftDocs/microsoft-365-docs#11089]
[Enter feedback here]
Please correct the description of "Randomize scheduled task times"

Please correct the following statements.
━━━━━━━━━━━━━━━━━━━━
In Microsoft Defender Antivirus, randomize the start time of the scan to any interval from 0 to 23 hours.
In SCEP, randomize scans to any interval plus or minus 30 minutes. This can be useful in virtual machines or VDI deployments.
━━━━━━━━━━━━━━━━━━━━

Please correct as follows.

Current statement:
In Microsoft Defender Antivirus, randomize the start time of the scan to any interval from 0 to 23 hours.

Correct:
In Microsoft Defender Antivirus, randomize the start time of the scan to any interval from 0 to 23 hours.
By default, scheduled tasks will begin at a random time within 4 hours after the time specified in Task Scheduler.

Why it needs to be fixed:
Applying the latest WindowsDefender.admx and checking the description of "Randomize scheduled task times" shows the following:
A customer requested that the same information be included in the documentation.

・WindowsDefender.admx

 
    This policy setting allows you to configure the scheduled scan, and the scheduled security intelligence update, start time window in hours.
     If you disable or do not configure this setting, scheduled tasks will begin at a random time within 4 hours after the time specified in Task Scheduler.
     If you enable this setting, you can widen, or narrow, this randomization period. Specify a randomization window of between 1 and 23 hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8195657b-949f-869c-b499-1e4390d39f9a
* Version Independent ID: 8308cec0-964e-a4f2-df7c-bdc1a671a2aa
* Content: [Schedule antivirus scans using Group Policy](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@narkuroki Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11147

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @narkuroki Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by narkuroki** [comment]
@msbemba 
@yogkumgit 

Looking at the content reviewed in https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11147, there is the following statement.

━━━━━━━━━━━━━━━━━━━━
In Microsoft Defender Antivirus, randomize the start time of the scan to any interval from 0 to 23 hours. By default, scheduled tasks will begin at a random time within four hours of the time specified in Task Scheduler.
━━━━━━━━━━━━━━━━━━━━

This statement is incorrect.
The correct information is within 4 hours, not around 30 minutes.
This is also written in WindowsDefender.admx.
Could you please fix it again?

・WindowsDefender.admx
━━━━━━━━━━━━━━━━━━━━
This policy setting allows you to configure the scheduled scan, and the scheduled security intelligence update, start time window in hours.
 If you disable or do not configure this setting, scheduled tasks will begin at a random time within 4 hours after the time specified in Task Scheduler.
 If you enable this setting, you can widen, or narrow, this randomization period. Specify a randomization window of between 1 and 23 hours.
━━━━━━━━━━━━━━━━━━━━

**Comment by narkuroki** [comment]
@msbemba 
@yogkumgit 
Thank you for your correction.
"Content Source: [microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy.md)" reflects the fix,
"Content: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy?view=o365-worldwide" doesn't seem to reflect the fix yet.
When will the fix be reflected?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@denisebmsft I can ee the PR was merged, however, the document doesn't reflect the changes yet. Could you please check this?

Thanks
Sri
