### ISSUE TITLE
Tool fails to install

### ISSUE THREAD

**Issue by it-cairnmillar** [MicrosoftDocs/microsoft-365-docs#1108]
I have the latest version of Edge installed. Still get the "Deployment and application do not have matching security zones" error. I tried everything in this page and several others. Don't see why I need to run 2 browsers. Microsoft, get your act together!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7e8e46-96fd-2679-908f-65862428d018
* Version Independent ID: b40db2b9-6918-9f89-ae5b-73b5760439fa
* Content: [Use the Office 365 eDiscovery Export Tool in Microsoft Edge - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/configure-edge-to-export-search-results#feedback)
* Content Source: [microsoft-365/compliance/configure-edge-to-export-search-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/configure-edge-to-export-search-results.md)
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@it-cairnmillar Please open a ticket with Microsoft Support so they can analyze and troubleshoot your issue, and help us update the documentation accordingly. Apologies for the hassle and agreed that having to use different browsers is a pain.
