### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by paulohanlon** [MicrosoftDocs/microsoft-365-docs#11098]
Some of the templates listed no longer exist in the Purview portal (e.g. GDPR) and the ones that do exist don't contain the correct SITS (e.g. Enhanced GDPR makes no mentions of any of the named entities it includes such as Addresses and Full Names. This particular template also only shows 2 rules, when there's now 4). Probably needs a complete review based on recently updates to DLP templates

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b969281-83ff-1ec9-e59f-deee4f0dc49e
* Version Independent ID: 2665e941-08ff-5a30-ed06-3a3b716b54e1
* Content: [What DLP policy templates include - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/what-the-dlp-policy-templates-include?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/what-the-dlp-policy-templates-include.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-dlp-policy-templates-include.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks
