### ISSUE TITLE
Wrong HTTP method in (HTTP request) description

### ISSUE THREAD

**Issue by PhilippEisenmann** [MicrosoftDocs/microsoft-365-docs#11095]
Paragraph: https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/add-or-remove-machine-tags.md#http-request

The method must not be POST but PATCH.

See same API documentation: https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/update-machine-method.md

BR
Philipp
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45e02871-e257-cb19-c0e4-cee106705368
* Version Independent ID: b3a038cf-d812-d3f9-05b3-ed6a803311d5
* Content: [Add or Remove Machine Tags API](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/add-or-remove-machine-tags?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/add-or-remove-machine-tags.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/add-or-remove-machine-tags.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@PhilippEisenmann Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11146

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PhilippEisenmann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
