### ISSUE TITLE
Inconsistent information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#11094]
This page states "we are currently unable to support indirect providers", but this page https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-requirements?view=o365-worldwide states that indirect billers are supported. Which is correct? please resolve these inconsistencies

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 761e3863-9d08-e5a4-c9d2-9ed09a8acf24
* Version Independent ID: 55b46499-7fad-3dc9-cc0c-d4290f3755d4
* Content: [Microsoft 365 Lighthouse frequently asked questions (FAQs)](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-faq?view=o365-worldwide)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-faq.yml)
* Service: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@yogkumgit  - I'll go ahead and fix this one myself. Thanks!

**Comment by SKjerland** [comment]
@DeanGross - Thanks for bringing this to our attention! Indirect providers ARE supported--the requirements article is correct and the FAQ article is incorrect. I updated the FAQ article and the updated article should be live later this afternoon.
