### ISSUE TITLE
Settings vs. Files

### ISSUE THREAD

**Issue by ruairidhlc** [MicrosoftDocs/microsoft-365-docs#1109]
"Other settings, such as encryption and content marking, aren't applied to all content within the team, group, or site."

As I understand it, sensitivity labels applied to SPO sites only change the settings for the site, such as controlling access on non-compliant devices and sharing settings.  It is completely removed from the files hosted in that site and its document libraries.  What is advised as the best practise to protect (encrypt) those files to only site members - is it still IRM via document library settings and if so, are there any plans for unified labeling to apply to SPO files automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **krowley**

**Comment by cabailey** [comment]
@ruairidhlc Yes, applying sensitivity labels automatically to files in SharePoint is around the corner, currently in private preview.  I can't provide an ETA, but watch this space!  It might be too late to join this private preview, but if you're interested in this or other private previews for sensitivity labels, here's a sign-up link: https://aka.ms/mip-preview
