### ISSUE TITLE
Blocked time on calendar is not syncing with Bookings

### ISSUE THREAD

**Issue by lucentraenna** [MicrosoftDocs/microsoft-365-docs#11100]
There are appointments that already exist on Outlook. I have the staff set so that blocked time prevents booking over it. I have the time zone set correctly. Why are appointments being allowed during the blocked time?

**Comment by msbemba** [comment]
@lucentraenna Thank you for your feedback. This looks more like a technical issue and I'd recommend you contact the Microsoft support team via the need help option on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lucentraenna Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
