### ISSUE TITLE
Desired delimiter for the .csv file

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1110]
Which delimiter should be used for the .csv file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification#feedback)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by MaratMussabekov** [comment]
Hello, CSV stands for "Comma separated values", so desired delimiter is comma.
Thank you

**Comment by GiantCrocodile** [comment]
Well, that's not that much of an argument @MaratMussabekov: There are other common delimiters beside the classical comma. https://tools.ietf.org/html/rfc4180#section-2 supports this.

**Comment by GiantCrocodile** [comment]
I just found this https://answers.microsoft.com/en-us/msoffice/forum/all/excel-to-csv-brings-in-semi-colon-instead-of-comma/a3a732ec-d991-4de1-a8b1-6c293c8b82a1 and verified it on my OS: List separator for my Windows 10 with German language is `;` so Microsoft didn't use a `,` themselves.

**Comment by chrfox** [comment]
@MaratMussabekov - Thank you for your response, you are correct.
