### ISSUE TITLE
Change step referenced

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/microsoft-365-docs#11103]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

The below section points to Step 3, however the correct step is 2.

The logging of audit records for MailItemsAccessed and Send will begin within 24 hours. You have to perform Step 3 to start logging of two other Audit (Premium) events: SearchQueryInitiatedExchange and SearchQueryInitiatedSharePoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d420e29-9348-48e6-673f-141212bf4de6
* Version Independent ID: d7e79a0d-39bf-abe1-3a2e-b9ba0f099934
* Content: [Set up Audit (Premium) in Microsoft 365 - Microsoft Purview (compliance)](https://review.learn.microsoft.com/en-us/microsoft-365/compliance/audit-premium-setup?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-premium-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-premium-setup.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@asdcristi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11143

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by robmazz** [comment]
Closing - asked MS contact to follow the requested process to open an internal ADO request for content updates.
