### ISSUE TITLE
How to make MacOS device isolation by REST API ? 

### ISSUE THREAD

**Issue by eric-jenouvrier** [MicrosoftDocs/microsoft-365-docs#11102]
Within Microsoft Documentation, 
* the following page https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#isolate-devices-from-the-network is saying 

"Isolating devices from the network is not currently supported for devices running macOS. For macOS, use live response to run the action. For more information on live response, see [Investigate entities on devices using live response](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response?view=o365-worldwide)."

* on https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response?view=o365-worldwide, the documentation is well done, we have information on all "command" a human can do into a "Live Response Session"
* on Live Response Session REST API : https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-live-response?view=o365-worldwide, there is only 3 command available (PutFile, RunScript, GetFile), no command for MacOS device Isolation.

At the very end : 
* Are we able to make MacOS Device Isolation by Human Operator : yes (live response action + command)
* Are we able to make MacOS Device Isolation by REST API / Programmatically : no (no REST API available or not well documented on how do do it for MacOS)

The text block

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3e5349-9b67-18ff-6c1c-d123b1f21a72
* Version Independent ID: fe100af9-381b-8b0f-cd7b-94ac62b6b313
* Content: [Run live response commands on a device](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-live-response?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-live-response.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-live-response.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks
