### ISSUE TITLE
Bring Back Tech Support - This is WAY too Complicated

### ISSUE THREAD

**Issue by KingRayBoss** [MicrosoftDocs/microsoft-365-docs#11116]
This is far too complicated and Microsoft continues to hide behind all this insanity. I do NOT want to start programming again just to use a product and alert them to things going on with it. I'm paying for this & their salaries, not the other way around. I'm getting threatened by phishers/scammers who end up getting around the crummy Outlook junk mail filter. and into my inbox. All coming from Google Mail. They're getting smarter in hiding who they are using my email address as a domain. REALLY, MS? You need to take accountability for these things. Not turn us into unpaid developers. I'm retired & disabled. Bring back direct technical support!! You're paying those folks, so where are they?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba3c2328-105e-de82-a999-98662924b81c
* Version Independent ID: c353e1b6-4409-bcb6-67b6-943d43ea8f23
* Content: [Configure anti-phishing policies in EOP - Office 365](https://learn.microsoft.com/en-gb/microsoft-365/security/office-365-security/anti-phishing-policies-eop-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-policies-eop-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-policies-eop-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@KingRayBoss, there's nothing more frustrating than being dumped into admin content when you aren't an admin.

Out of curiosity, were you directed to the anti-phishing policies article by a link in Outlook?

**Comment by KingRayBoss** [comment]
I'm the admin of my machine, but it's wild how I ended up here. Since I can't find a tech support phone number, I clicked on Feedback and saw all this stuff about programming Outlook. SMH

Yes, I saw the anti-phishing policies, but am tired of reading through tons of things like that when I've been an Outlook user since the 1990's. Shouldn't be this hard and my eyes are old. LOL

**Comment by KingRayBoss** [comment]
Your response made me laugh @LordReydrX. I've been a computer professional since 1978. That's why I knew what to say. Businesses putting a crap load of text in lieu of lousy policies about junk mail is rather unacceptable to me. I've been an operator, tech support rep, software developer, and software consultant. I would've never gotten away with hiding from end-users like they get away with now. NOT GOOD! 

Sure, I would appreciate the information if I was trying to write code for my products, but I am not. I'm a busy guy and started steaming when I saw the email threatening to do things to my machine if I didn't send them Bitcoins. Are you kidding me? LOL

**Comment by KingRayBoss** [comment]
Wait, you want screen shots of that threatening email that wound up in my inbox, @LordReydrX? Oh, how about the one who threatened to take over $400 from my PayPal account? They're too long for that and exposes my real email address. I thought it was legitimate until I looked into it further. It was exactly the amount of some yard care I scheduled and I sent a crazy email to the vendor telling them it was supposed to be deducted quarterly, not all at once. I apologized quickly and still got a discount cuz she likes me ... hahahaha. I told her it was my fault for not looking more closely at that email with a PDF attachment. Sure is wasting my time & nerves, I tell you that!

**Comment by KingRayBoss** [comment]
Huh? What are you stammering about @LordReydrX? I didn't insult you. Perhaps it's you who needs to be on meds, not me. LOL ... Ummmmmm

**Comment by KingRayBoss** [comment]
I have a whole lot going on in my life, mostly good things, but I can only get to these responses when I can get to them. No, I haven't found a solution to letting Microsoft know they need to do something about their filter again. That was the nature of my feedback. That somehow Google email addresses slip past the junk mail filter and end up in my inbox. Blocking them only happens when I think it's not a legitimate email, and there are times when I'm bombarded with them. 

THAT is why I was so confused that I ended up here instead of giving feedback directly to Microsoft. I don't know how that happened. So, @LordReydrX, whatever you got out of things I said, I wasn't talking to you or about you. And, your rude response, to whatever, is the reason I hate coming into Forums. That much we can agree on both sides of the spectrum. I'm not stupid, nor am I any kind of newbie, just new to this Forum. I've been in computers since 1978, and you're rather ridiculous to assume anything about me.

Have a nice day after you get those meds you projected onto me. LOL ... SMH

**Comment by chrisda** [comment]
OK. Then. It looks like this thread has run it's course.

Thanks for the feedback.

Closing.
