### ISSUE TITLE
HTML exposed and url is dead

### ISSUE THREAD

**Issue by LordReydrX** [MicrosoftDocs/microsoft-365-docs#11115]
[![image](https://user-images.githubusercontent.com/75751669/220820991-a8994f00-4e16-4ddd-81fd-613b44db3bc3.jpeg)]()

**Comment by msbemba** [comment]
@LordReydrX Thank you for your feedback. Could you please provide us the URL of the document that you are referring to? so that this can be corrected?

Thanks
Sri

**Comment by yogkumgit** [comment]
@LordReydrX We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
