### ISSUE TITLE
Link to real-time data

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/microsoft-365-docs#11123]
There is a Note section saying, "This is a protection trend report, meaning data represents trends in a larger dataset" which begs the question of 'so where DO you go to find real-time data?'  Could a sentence with a link be added that points folks to Threat Explorer for detailed real-time information? 

https://learn.microsoft.com/microsoft-365/security/office-365-security/threat-explorer-about#view-phishing-url-and-click-verdict-data

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f202d70-f6d7-faba-ac20-16e4d41e0179
* Version Independent ID: 1f202d70-f6d7-faba-ac20-16e4d41e0179
* Content: [View Defender for Office 365 reports - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/reports-defender-for-office-365?view=o365-worldwide#url-protection-report)
* Content Source: [microsoft-365/security/office-365-security/reports-defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/reports-defender-for-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@npherson, done.

In the future, you too can make changes like this yourself without opening a GitHub issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
