### ISSUE TITLE
Unclear wording

### ISSUE THREAD

**Issue by hapklaar** [MicrosoftDocs/microsoft-365-docs#11121]
The phrase "(a role is assigned only to the Organization Management role group)" should be "(this role is assigned only to the Organization Management role group by default)"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 468343fc-2808-0f78-f1a7-9d34b8fa8e16
* Version Independent ID: e3b7630f-75a9-d236-6c8b-7ebd27a7e9c0
* Content: [Permissions in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/microsoft-365-compliance-center-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-compliance-center-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@hapklaar Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11144

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@hapklaar Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
