### ISSUE TITLE
Unable to turn on Audit Logging

### ISSUE THREAD

**Issue by tomkodet** [MicrosoftDocs/microsoft-365-docs#1112]
Hello,

We are only using SharePoint Online at this point and would still like to enable Audit Logging. Currently, I am unable to turn on Audit Logging because we do not have any users with Exchange Online accounts or licenses. Why is the Audit Log option restricted to only those with Exchange enabled? I think this should be allowed for all O365 products.

Thanks,

Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn Office 365 audit log search on or off - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@tomkodet Thanks for the question. The unified auditing infrastructure is based/dependent on Exchange. Audit records are ingested/stored in a system mailbox in EXO; you run an EXO PowerShell cmdlet to enable auditing for your org; searching the audit log runs an EXO PowerShell cmdlet in the background to search for records in the system mailbox. SPO does provide some auditing at a site collection level. See https://support.office.com/en-us/article/configure-audit-data-for-a-site-collection-a9920c97-38c0-44f2-8bcb-4cf1e2ae22d2?ui=en-US&rs=en-US&ad=US#ID0EAADAAA=SharePoint_Online

**Comment by tomkodet** [comment]
@markjjo Thanks for the reply. It still seems confusing to me that O365 UnifiedAuditLogs would require an organization to also purchase Exchange Online in order to get access to the logs for every other product. For us, our mail is hosted by our parent company and we are using a separate O365 tenant to provide SharePoint Online only. I've tried to enable the logs and get the error message below stating I am not allowed to use the cmdlet.

The following error occurred during validation in agent 'Substrate Only Agent': 'Organization is not licensed for Exchange email functionality. Cmdlet usage is restricted.'

Client Error

The following error occurred during validation in agent 'Substrate Only Agent': 'Organization "domainname.onmicrosoft.com" is not licensed for Exchange email functionality. Cmdlet usage is restricted.'

Request: /api/adminauditlogconfig/EnableUnifiedAuditLogIngestion
Status code: 500
Exception: Microsoft.Exchange.PswsClient.PswsException
Diagnostic information: {Version:17.00.4092.006,Environment:EUSPROD,DeploymentId:834xxxxxxxxxxxxxxxxxxxx,InstanceId:WebRole_IN_3,SID:xxxxxxxx-xxxx-xxxxxxxx,CID:xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}
Time: 2020-01-23T22:46:19.4153623Z

**Comment by markjjo** [comment]
@tomkodet Please see my previous response about auditing pipeline based on Exchange infrastructure. The error above confirms that you need an EXO org. Pretty sure that you'll need at least one EXO/O365 license for your org. You could assign that to yourself so that a mailbox is provisioned for you. You don't have to send mail from it, etc.  You can open a ticket with MS support for more info.
