### ISSUE TITLE
Check for labels enabled in SPO/OD4B - bad command parameter

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/microsoft-365-docs#11133]
The instruction in the Requirements section - 2nd bullet for "You've enabled sensitivity labels for Office files in SharePoint and OneDrive." is incorrect -- -EnableAIPIntegration is not a valid parameter.
Instead I used   (Get-SPOTenant).EnableAIPIntegration   successfully to obain the parameter value.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a96bf9a2-9de2-8366-24f5-d014b72fd380
* Version Independent ID: a96bf9a2-9de2-8366-24f5-d014b72fd380
* Content: [Configure a default sensitivity label for a SharePoint document library - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-default-label?view=o365-21vianet&branch=pr-en-us-12593)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-default-label.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-default-label.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@bholzmmc Thank you for your feedback. The document now states that 

You've [enabled sensitivity labels for Office files in SharePoint and OneDrive](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-21vianet). To check this status, you can run (Get-SPOTenant).EnableAIPIntegration from the [SharePoint Online Management Shell](https://learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online) to confirm the value is set to True.

Hope this helps!

Thanks
Sri

**Comment by cabailey** [comment]
@bholzmmc Yes, thanks for flagging this!  Confirmed and fixed yesterday, I just didn't have time to reply.
