### ISSUE TITLE
This documentation is wrong. 

### ISSUE THREAD

**Issue by robert5150** [MicrosoftDocs/microsoft-365-docs#11132]
The options to enable IRM for SharePoint or SharePoint lists and libraries is wrong. The options simply don't exist in the site settings. 

https://learn.microsoft.com/en-us/microsoft-365/compliance/apply-irm-to-a-list-or-library?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0704afe-d1a4-c553-38ed-b7ee6a95e416
* Version Independent ID: 3d83f05b-965d-1b9a-4773-a8a77bd89473
* Content: [Apply IRM to a list or library - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/apply-irm-to-a-list-or-library?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-irm-to-a-list-or-library.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-irm-to-a-list-or-library.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@robert5150 Thank you for your feedback. I'm verifying the document and will update the steps shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@robert5150 Thank you for your feedback. I'm able to view the settings

![image](https://user-images.githubusercontent.com/45987684/222742350-6e295aa6-9094-44ba-acc2-1ffebf4acf2c.png)

![image](https://user-images.githubusercontent.com/45987684/222742547-2dd452ea-4387-4090-b209-6cb886b06183.png)

If you continue to see this issue, I recommend you contact the support team via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @robert5150 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
