### ISSUE TITLE
Unable to locate this mdatp on ubuntu

### ISSUE THREAD

**Issue by Vincentssssssss** [MicrosoftDocs/microsoft-365-docs#11138]
root@ubuntu:~# uname -a
Linux ubuntu 5.15.0-1033-azure #40~20.04.1-Ubuntu SMP Tue Jan 24 16:06:28 UTC 20                                                                          23 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# sudo apt-get install mdatp
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package mdatp

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Vincentssssssss Thank you for your feedback. This sounds like a technical issue, I'd recommend you contact Microsoft support via the need help section on the admin center so that a support engineer can assist you to fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Vincentssssssss Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
