### ISSUE TITLE
Id Property Not Returned as Documented

### ISSUE THREAD

**Issue by NomadicSquirrel** [MicrosoftDocs/microsoft-365-docs#11141]
The Id is not returned in this API, as stated in the documentation (Section 1.5).  1.6.2 goes on to also show an example response that does not include an Id property.

Id | string | Unique identifier for the record. | 123ABG55_573AG&mnp!
-- | -- | -- | --

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7cb493c-e225-0e6b-5b9b-aaa97953be82
* Version Independent ID: eabcfb9e-1873-2b0c-3a0e-1144801df621
* Content: [Export software inventory assessment per device](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-assessment-software-inventory?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-assessment-software-inventory.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-assessment-software-inventory.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@NomadicSquirrel Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11180

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @NomadicSquirrel Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
