### ISSUE TITLE
Step 8 of the "Onboarding blob" section's screenshot is incorrect, it is a duplicate of step 3. 

### ISSUE THREAD

**Issue by NickConnon** [MicrosoftDocs/microsoft-365-docs#11149]
The screenshot in step 8 should have the image from step 10, instead of duplicating step 3's image, and step 10 should have a screenshot of the configuration profiles list.

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#onboarding-blob

<img width="590" alt="image" src="https://user-images.githubusercontent.com/83462832/221219362-14d813e8-5ee9-408c-918c-a8337211b735.png">
is the same as 
<img width="554" alt="image" src="https://user-images.githubusercontent.com/83462832/221219414-46b5137e-2475-4af8-ae38-315f246efbbb.png">
which should be this instead with a new screenshot uploaded for step 10
<img width="574" alt="image" src="https://user-images.githubusercontent.com/83462832/221219488-238a2a24-42a8-4c05-b0d7-f64730987ad1.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd66a255-36e5-29dc-7610-d50ef8bca3f3
* Version Independent ID: 17375473-bc07-f8e5-a85f-d732bbba3d71
* Content: [Intune-based deployment for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#create-system-configuration-profiles)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-with-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-with-intune.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@NickConnon Thank you for your feedback. We have update the screenshot in the document shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@NickConnon Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11220

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @NickConnon Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
