### ISSUE TITLE
unclear statement about anonymous or unauthenticated proxy traffic

### ISSUE THREAD

**Issue by DonPick** [MicrosoftDocs/microsoft-365-docs#11155]
Hi folks,

for page: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide

this sentence/paragraph , seems incomplete and unclear?
If a proxy or firewall is blocking anonymous traffic as Defender for Endpoint sensor, and it's connecting from system context to make sure anonymous traffic is permitted in the previously listed URLs.

should it instead be like this?:
If a proxy or firewall is blocking anonymous traffic _from the_ Defender for Endpoint sensor, and it's connecting from system context , _it's important_ to make sure anonymous traffic is permitted _in your proxy or firewall for_ the previously listed URLs.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DonPick Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
