### ISSUE TITLE
Email activity Report and Licensed Shared Mailboxes

### ISSUE THREAD

**Issue by cristinitu** [MicrosoftDocs/microsoft-365-docs#11151]
[Enter feedback here]
The article mentions that "The Email activity report is only available for mailboxes that are associated with users who have licenses.". What about licensed shared mailboxes?

In case "Sand as" is used to send an email, and both the user and the delegate are licensed, who will have this email in "Send actions"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be45e626-ed67-3f48-1a80-5d69f938638b
* Version Independent ID: de7bbfaa-17fb-01eb-fd74-a854d615dc23
* Content: [Microsoft 365 admin center email activity reports - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/email-activity-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/email-activity-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/email-activity-ww.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@cristinitu Thank you for your feedback.  It works on a shared mailbox if the mailbox is licensed, Also If the option 'Copy items sent as this mailbox' is selected it will be available on both the mailbox and for the delegate.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cristinitu Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
