### ISSUE TITLE
Misleading example in document

### ISSUE THREAD

**Issue by Ant1120** [MicrosoftDocs/microsoft-365-docs#11152]
Please double-check if following statement on the page is still valid. In my implmentation on Feb-22-2023, neither "Site_Path" nor "SiteContent_Path" was actually functional in the later e-discovery content search (returning 0 item). If I switch to "Site_DocumentLink" in the filter applied, the e-discovery content search worked as expected honoring the filter.

https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-permissions-filtering-for-content-search?view=o365-worldwide#filters
`These two filters are interchangeable. For example, "Site_Path -like 'https://contoso.sharepoint.com/sites/doctors'" and "SiteContent_Path -like 'https://contoso.sharepoint.com/sites/doctors'"
`
Plus, in the next sentence of the same paragraph, there is another document provided for "a list of searchable site properties". In that article, neither "Site_Path" nor "SiteContent_Path" is listed.

`For a list of searchable site properties, see [Keyword queries and search conditions for eDiscovery](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-keyword-queries-and-search-conditions?view=o365-worldwide#searchable-site-properties)`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9237f497-7a2d-060e-348b-8cba3ae25f63
* Version Independent ID: 9237f497-7a2d-060e-348b-8cba3ae25f63
* Content: [Configure permissions filtering for eDiscovery - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-permissions-filtering-for-content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-permissions-filtering-for-content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-permissions-filtering-for-content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Ant1120 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11219

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@Ant1120 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
