### ISSUE TITLE
Major flaw in MDO P2 evaluation

### ISSUE THREAD

**Issue by davebirr** [MicrosoftDocs/microsoft-365-docs#11157]
We already had MDO P1 (Via M365 BP) and tried the MDO P2 evaluation. After it expired, all MDO P1 functionality in the admin center is completely broken. All of the MDO admin pages redirect to the trialHorizontalHub and are completely non-functional.

You need a way to offboard paying P1 customers from the P2 evaluation after it's done.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d08fef08-2fa6-79c4-4adf-e1e194a33a0d
* Version Independent ID: 6c962f09-1e5d-bcac-c58f-ecaf58bc9774
* Content: [Try and evaluate Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/try-microsoft-defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/try-microsoft-defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/try-microsoft-defender-for-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@davebirr, you should open a support ticket about this. The trial should not affect anything that's common to P1 and P2. Per the article in question for M365 BP customers:

> Organizations with Defender for Office 365 Plan 1 (for example Microsoft 365 Business Premium or add-on subscriptions) have exactly the same policies as organizations with Defender for Office 365 Plan 2 (impersonation protection in anti-phishing policies, Safe Attachments policies, and Safe Links policies). The security policies from allow mode (Standard preset security policy) or blocking mode (evaluation policies) don't expire or stop working after 90 days. What ends after 90 days for these organizations are the [automation, investigation, remediation, and education capabilities](https://learn.microsoft.com/microsoft-365/security/office-365-security/defender-for-office-365#whats-the-difference-between-microsoft-defender-for-office-365-plan-1-and-plan-2) of Plan 2 that aren't present in Plan 1.
