### ISSUE TITLE
How to enable "Report a Concern" feature in Teams for those that don't have it enabled

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/microsoft-365-docs#11158]
The article doesn't really go into detail about how to enable the "Report a Concern" feature for Teams. My Teams Admin portal does not show any option for turning this on/off. I have Communication Compliance enabled too. 

This is a part of what the article says:

"_The Report a concern option for Teams personal and group chat messages is enabled by default and can be controlled via Teams messaging policies in the [Teams admin center](https://learn.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal)_"

In my case, it's not enabled by default.

I navigated around the Team admin portal and the messaging policy but no option is found:
![image](https://user-images.githubusercontent.com/5460795/221424949-b0b48608-c77c-410d-875c-17a5ff6eec5a.png)

![image](https://user-images.githubusercontent.com/5460795/221424905-fafc4e0d-0742-4aa6-81b4-c3f34f79a546.png)

![image](https://user-images.githubusercontent.com/5460795/221424915-82c45ec0-5bd7-4aad-9fa3-18bc98fe41e6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18f9ed93-1f7c-c9d9-2c2f-494b46cc5757
* Version Independent ID: 3c954243-4c6d-3791-bf42-be61e88eac7f
* Content: [Create and manage communication compliance policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-policies?view=o365-worldwide#user-reported-messages-policy)
* Content Source: [microsoft-365/compliance/communication-compliance-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Rykimaruh Thank you for your feedback. This sounds more like a permission issue or a bug, I'd recommend you contacting Support via the need help option on the M365 admin center, so that the Support engineer can help you fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Rykimaruh Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
