### ISSUE TITLE
No description of Simulation Automation is given. 

### ISSUE THREAD

**Issue by VathekVan** [MicrosoftDocs/microsoft-365-docs#11167]
No description of Simulation Automation is given. It just goes right into how to set one up.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6be692e7-40f2-87ae-56b6-680a32f1024f
* Version Independent ID: 6be692e7-40f2-87ae-56b6-680a32f1024f
* Content: [Simulation automations for Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-simulation-automations?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-simulation-automations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-simulation-automations.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@VathekVan, I added this information as an introduction:

> In Attack simulation training in Microsoft 365 E5 or Microsoft Defender for Office 365 Plan 2, simulation automations allow you to run multiple benign cyberattack simulations in your organization. Simulation automations can contain multiple payloads and start on an automated schedule. Creating a simulation automation is very similar to [creating an individual simulation](https://learn.microsoft.com/microsoft-365/security/office-365-security/attack-simulation-training-simulations), except you also select the payloads and the automation schedule.

Feel free to update it if you like. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
