### ISSUE TITLE
No Steps Provided to Activate rights management in the admin center

### ISSUE THREAD

**Issue by mkroeff-fcx** [MicrosoftDocs/microsoft-365-docs#11165]
The name of this page is  "Activate rights management in the admin center" yet it provides zero steps on how to actually activate it............

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d20fbb5-c482-7944-b726-63b2b3e1ddbe
* Version Independent ID: 0a98d497-e6fa-3aa3-23ba-7939f5fb7a1e
* Content: [Activate rights management in the admin center - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/activate-rms-in-microsoft-365?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/activate-rms-in-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/activate-rms-in-microsoft-365.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@mkroeff-fcx Thank you for your feedback. This page is just an overview about the product, however you have links in the document which takes you to the page to activate rights management

![image](https://user-images.githubusercontent.com/45987684/222759855-64042701-3cf5-4f2c-bd27-a45792d40978.png)


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mkroeff-fcx Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
