### ISSUE TITLE
Private Teams Chat Retention

### ISSUE THREAD

**Issue by michael-hare** [MicrosoftDocs/microsoft-365-docs#11168]
This article is referenced on the Data Lifecycle configuration page and hotlinked under "Teams private channel messages
Messages from Teams private channels. [More details](https://go.microsoft.com/fwlink/?linkid=2220113)"

Presumably, from Exchanges perspective these private channel chat messages are part of the group mailbox or similar, but it is very unclear the correct configuration except that private channel chat messages have to be configured separately. This is not explained in anyway on the Docs page so should be included in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide#whats-included-for-retention-and-deletion)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@michael-hare Thank you for flagging this - private channels use the UserMailbox attribute (now added to this page), which explains why a separate retention policy is needed for private channels, as documented here https://learn.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide&tabs=teams-retention#create-and-configure-a-retention-policy
