### ISSUE TITLE
Where can I find the tile "Devices with sensor issues"?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#11162]
The article just dives in, but does not tell where to find the tile from the portal. It is not on my home page, and I cannot add any more cards "You already have all the cards on your home page". I don't seem to able to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca0b53f6-8f88-42e7-e1b2-ee3f68889379
* Version Independent ID: eacbb573-2072-b835-e3b4-bb62d9df1e70
* Content: [Check the health state of the sensor at Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/check-sensor-status?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/check-sensor-status.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/check-sensor-status.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Content outdated. Will fix.
