### ISSUE TITLE
Poorly written docs - improvement required

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#11178]
I am writing to request that this page is rewritten to provide further clarity around the impact Tamper Protection has on valid configuration mechanisms such as SCCM/Intune/GPO etc.

I recently had to raise a support case as some settings we had enabled in SCCM werent taking effect as expected. After many hours of troubleshooting it transpired these settings were TP protected and therefore will not change from the defaults regardless of the settings in SCCM.

The existing documentation states clearly that  "With tamper protection, malicious apps are prevented from taking actions"

This statement should also clarify that non malicious management solution apps such as SCCM and Intune will also be prevented from making changes! There is a blue highlighted box beneath the overview section that does state the impact TP has on  Intune settings - why does this not include other management mechanisms that are also impacted?

It also states that in order to obtain the list of TP protected settings we should contact support. This should not be the case at all, as a full list of tamper protected settings should be clearly published.

To further add to the lack of cohesion in the existing docs, the section entitled "How Tamper Protection Works" (which is immediately below the blue box that states the impact to Intune pushed settings) states:

_Tamper protection essentially locks Microsoft Defender Antivirus to its secure, default values, and prevents your security settings from being changed through apps and methods such as:_

- Configuring settings in Registry Editor on your Windows device
- Changing settings through PowerShell cmdlets on your device
 
Again, there is no mention of the impact TP has on settings pushed from management platforms such as Intune or SCCM!

Had the docs been better written and more cohesive, the support ticket I had to raise and many hours of lost time could have been avoided.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f31e7b39-b7c3-188a-0b2a-02ff10a5be6d
* Version Independent ID: 44940a13-0a2d-e281-560b-cb4d8a5d1ccf
* Content: [Protect security settings with tamper protection](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @pjrcdf and thank you for your feedback. This issue appears to be a lot like #11179. I am looking into this and will get the docs updated accordingly. My apologies for the inconvenience. Thank you so much for filing this issue so we can fix it.

**Comment by denisebmsft** [comment]
Hello @pjrcdf.  I wanted to let you know that the tamper protection docs have been updated and the changes went live this afternoon. Doc updates include changes to provide more clarity around what happens when tamper protection is enabled. Please let me know if you have any other questions or feedback. Thank you again for posting this issue and helping me improve our documentation.
