### ISSUE TITLE
Confusing differentiation between Annual and Monthly Subscription

### ISSUE THREAD

**Issue by krei68** [MicrosoftDocs/microsoft-365-docs#11176]
[Enter feedback here]
At the top of the page, there is differentation between Annual and Monthly subscriptions - however the Annual part refers to "not renewing", and the monthly part refers to "cancelling". These are 2 different things - so the obvious questions come up: What happens if you decide to cancel an annual subscription - and what happens if you let a monthly subscription not renew?

Thanks,

Christian

Annual subscriptions. If you **turn off recurring billing** on an annual subscription, it goes through the same stages as an expired subscription. The first stage starts on the anniversary of the annual subscription, not the date that you turned off the subscription's recurring billing setting.
Monthly subscriptions. If you **cancel** a monthly subscription, it immediately moves to the Disabled stage on the date you cancel it. This means that your users immediately lose access to the Microsoft 365 assets, and only admins have access to the data for the next 90 days.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@krei68 Thank you for your feedback.

When an annual subscription is canceled it is canceled only on the date of anniversary. So it is not pro-rated like the monthly subscription.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @krei68 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
