### ISSUE TITLE
Version of AZcopy

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#11174]
From the Purview Admin center page upload non-Office 365 data page the link goes to AZCopy v8.1 https://learn.microsoft.com/en-gb/previous-versions/azure/storage/storage-use-azcopy
![image](https://user-images.githubusercontent.com/69439002/221827195-6c012fdc-633b-41a0-bd62-34a55b718785.png)
This works OK.

The Microsoft Learn documentation states that AzCopy V10 is needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 305ff999-68dc-aebf-9e80-ecc51a370664
* Version Independent ID: 305ff999-68dc-aebf-9e80-ecc51a370664
* Content: [Load non-Microsoft 365 data into a review set - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-load-non-office-365-data-into-a-review-set?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-load-non-office-365-data-into-a-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-load-non-office-365-data-into-a-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11191

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@nikki-c Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
