### ISSUE TITLE
Clarification on download limits

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#11175]
Can you update the document to confirm the download limits and whether this is based on the number of files selected or whether it is based on the total file size. 

If you try to download too many files, you see the following error, which either asks you to reduce number of files or to use the export feature 
![image](https://user-images.githubusercontent.com/69439002/221850603-f16b8f6c-ae6c-45ac-a65f-95b6cbf5d727.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3b8233-7dce-deaa-7ddb-ec34efc21b7e
* Version Independent ID: 5a3b8233-7dce-deaa-7ddb-ec34efc21b7e
* Content: [Download documents from a review set - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-download-documents-from-review-set?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-download-documents-from-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-download-documents-from-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11192

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@nikki-c Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
