### ISSUE TITLE
MailUser objects are also covered by the Compliance retention policy

### ISSUE THREAD

**Issue by riohedfield** [MicrosoftDocs/microsoft-365-docs#11173]
Hello,

MailUsers objects (without mailboxes) are also covered and retained by the retention policy and yet there is nothing about that in the official documentations.
So, whenever a compliance retention policy is created with "All Mailboxes", MailUsers are being held as softdeleted users and can only be deleted after running set-mailuser <GUID> -ExcludeFromAllOrgHolds.

Could you please update the documentation to reflect the above.

Thank you
BR

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1c2e44-357c-8096-5bdf-40e205778ded
* Version Independent ID: 19c7b5d9-1e0c-501b-7b70-df5aab48b36e
* Content: [Learn about retention for Exchange - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-exchange?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-exchange.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Investigating

**Comment by cabailey** [comment]
Although closed, I wanted to note that this request is acknowledged and on the backlog but no new documentation to share at this point.
