### ISSUE TITLE
For detailed syntax and parameter information, see Test-DlpPolicies. : the link doesn't work

### ISSUE THREAD

**Issue by FadJee** [MicrosoftDocs/microsoft-365-docs#11177]
Hello, 
When I click on [Test-DlpPolicies](https://learn.microsoft.com/en-us/powershell/module/exchange/test-dlppolicies) : the link gives a 404 error page. 
Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c4f97c0-0783-56bb-7872-eae1439f1647
* Version Independent ID: 0c4f97c0-0783-56bb-7872-eae1439f1647
* Content: [Test your DLP policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-test-dlp-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-test-dlp-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-test-dlp-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks
