### ISSUE TITLE
Azure Defender Software API response Inconsistenct

### ISSUE THREAD

**Issue by Algoss** [MicrosoftDocs/microsoft-365-docs#11186]
**Distributions by software_id** return distribution list for a software id but for same software_id in list software API response distributions are empty list.

**List Software API** - With one software_id there are two items in the API response list and both responses have different values for other fields.

I cannot give the software api response data here due to privacy terms as it is from my Org. I am working with LinkedIn Org. It would be helpful if I can proper support on this.  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aabaf97f-4313-dc71-8fdb-69349dd08ed1
* Version Independent ID: c17beb7f-e5df-fce8-0e03-dcd2a0a8d6c3
* Content: [List software](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-software?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-software.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-software.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@Algoss Thank you for your feedback. Since this is a technical issue, I'd recommend you opening a support ticket via the need help section on the admin center, so that a support engineer can review and help you with a fix.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Algoss Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
