### ISSUE TITLE
but Defender for Endpoint is set to Allow, should be updated in order to clarify the comment.

### ISSUE THREAD

**Issue by YongRhee-MSFT** [MicrosoftDocs/microsoft-365-docs#11183]
[Enter feedback here]

Dear Sir or Madam,

We need clarification in the comment below...

Change from:
/*
In situations when Microsoft Defender Antivirus is set to Block, but Defender for Endpoint is set to Allow, the policy will default to Allow.
*/
to:
/*
In situations when Microsoft Defender Antivirus is set to Block, but Defender for Endpoint - Indicators - File hash or Certificate is set to Allow, the policy will default to Allow.
*/

Thanks,
Yong

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef58bda-c0ee-ad76-20e8-b226af0cadb6
* Version Independent ID: c8580dd2-6ff9-550c-0b0e-6be69523b5f2
* Content: [Create indicators for files](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-file?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/indicator-file.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/indicator-file.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Fixed.
