### ISSUE TITLE
Request to update

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1118]
Please update the supporting documentation to reflect the Dec 26, 2019 International Traffic in Arms regulations; Activities That Are Not Exports, Reexports, Retransfers, or Temporary Imports; Storage and Transmission of Encrypted Data - - DDTC Public Announcements announcement impact on Azure/Office 365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cade86bc-56c3-ebc0-7a47-f5f835777b8c
* Version Independent ID: 3cdf7eb2-1653-f339-0685-cac32030dd82
* Content: [International Traffic in Arms Regulations (ITAR) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-itar?source=docs)
* Content Source: [microsoft-365/compliance/offering-ITAR.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-ITAR.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@DeanGross - Thanks for the feedback. The interim rule represents some opportunity to loosen the controls in our compliance programming, and we are assessing the potential along with waiting for further clarification from the regulator.  Thus, until that assessment is completed, our compliance remains consistent with the more conservative prior rule.
