### ISSUE TITLE
NDR change to 5.7.703

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#11190]
Please fix the line 

5.7.1 Your message can't be delivered because one or more recipients are blocked by your organization's tenant allow/block list policy.

to state 

5.7.703 Your message can't be delivered because one or more recipients are blocked by your organization's tenant allow/block list policy.

That NDR has changed. As per https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure and https://learn.microsoft.com/exchange/troubleshoot/email-delivery/ndr/fix-error-code-5-7-700-through-5-7-750. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c79bb5c3-e92a-583b-337a-1a038e50f064
* Version Independent ID: 253ccf77-2d74-dd95-2686-a8fcdc424c7a
* Content: [Create blocked sender lists - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hudish, fixed.

In the future, you too can make changes like this yourself. No need to open an issue about it first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
