### ISSUE TITLE
Please correct the description of "Randomize scheduled task times"

### ISSUE THREAD

**Issue by narkuroki** [MicrosoftDocs/microsoft-365-docs#11199]
[Enter feedback here]
Please correct the description of "Randomize scheduled task times"

Please correct the following statements.
━━━━━━━━━━━━━━━━━━━━
In Microsoft Defender Antivirus, randomize the start time of the scan to any interval from 0 to 23 hours. By default, scheduled tasks will begin at a random time within four hours of the time specified in Task Scheduler.

In SCEP, randomize scans to any interval plus or minus 30 minutes. This can be useful in virtual machines or VDI deployments.
━━━━━━━━━━━━━━━━━━━━

Please correct as follows.

Current statement:
In SCEP, randomize scans to any interval plus or minus 30 minutes. This can be useful in virtual machines or VDI deployments.

Correct:
Please delete the description

Why it needs to be fixed:
This page is for public information about Microsoft Defender Antivirus (MDAV), but it is confusing for customers that it mentions System Center Endpoint Protection (SCEP).
Can you delete the description?

If you can't remove the description, the "SCEP" link will show the public information for Simple Certificate Enrollment Protocol instead of System Center Endpoint Protection.
Please remove the link as Simple Certificate Enrollment Protocol is not an antivirus product and the link is inappropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8195657b-949f-869c-b499-1e4390d39f9a
* Version Independent ID: 8308cec0-964e-a4f2-df7c-bdc1a671a2aa
* Content: [Schedule antivirus scans using Group Policy](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@narkuroki Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11238

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @narkuroki Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
