### ISSUE TITLE
Group Mailbox is not avaiable in Cache mode but works only in Online Mode

### ISSUE THREAD

**Issue by Inderjeetsinghjaggi** [MicrosoftDocs/microsoft-365-docs#11209]
[Enter feedback here]
Group Mailbox is not avaiable in Cache mode but works only in Online Mode
We confirmed this with MS ticket ([External] [Case #:35149437] - GroupMailbox AutoMapping - 960337) and we do not have any documentation on internet for same. Suggest you to add this as note on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79d897cc-0be6-a995-fc23-e0259c0c47ba
* Version Independent ID: 79d897cc-0be6-a995-fc23-e0259c0c47ba
* Content: [Microsoft 365 Group mailbox size management - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/group-mailbox-size-management?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/group-mailbox-size-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/group-mailbox-size-management.md)
* Service: **microsoft-365-business**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by yogkumgit** [comment]
Closing as per the author's comment in PR. Thanks
