### ISSUE TITLE
Why is auditing data not encrypted?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1120]
The docs state:
> Is auditing data encrypted? Auditing data is stored in Exchange mailboxes (data at rest) in the same region where the auditing pipeline is deployed. This data is not encrypted. However, data in transit is always encrypted.

Why is auditing data at rest not encrypted, only in transit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@GiantCrocodile This FAQ is just stating the normal behavior in Exchange. Like any other Exchange items in the transport pipeline (in transit), audit records are encrypted (by Exchange). And like any other item at rest in a mailbox, they are not encrypted (by Exchange). There is service level encryption, where Exchange servers in the datacenter are encrypted via BitLocker.

If you think the FAQ needs to be clarified, please submit a PR.
