### ISSUE TITLE
Sharepoint Dev Tenant Account - Can't connect to catalog error under Admin Managed seen in MAC 

### ISSUE THREAD

**Issue by gelicas** [MicrosoftDocs/microsoft-365-docs#11204]
I setup a sharepoint dev tenant and added an addin for excel to test out. I then added user accounts my team in the addin so they can test this out, just recently a user has mentioned that when they try to login in their test account in MAC they see a "Can't connect to catalog error" under admin managed but when they try to login in PC excel all works as expected. 

We only see this issue when we try to login and access the addin in MAC excel, we have tried deleting cache, uninstalling and reinstalling office but the issue is still there. 

Can you help us resolve this? Thanks !

**Comment by yogkumgit** [comment]
@gelicas Please indicate which document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@gelicas We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by gelicas** [comment]
Hey @yogkumgit,

Apologies for the late response, was handling another project and was not able to update this ticket earlier. 

We deployed an addin in sharepoint dev tenant through uploading a manifest file.

The issue 'Cannot Connect to Catalog' occurs when we try to access the addin we added in Sharepoint under Admin Managed in Excel application.

We noticed this behavior in M1/M2 MAC devices, we also tried deploying a general addin to test out if this will also happen however we still see the error message under admin managed.


Please let us know how can we configure this.

Thank you!

**Comment by yogkumgit** [comment]
@gelicas Here, we are limited to documentation fixes and improvements. I request please open a service ticket in your tenant and follow with them for the resolution. Thanks
