### ISSUE TITLE
Not Allowing Me to Update Payment Method

### ISSUE THREAD

**Issue by Silvrbckw** [MicrosoftDocs/microsoft-365-docs#11216]
I have been trying to pay this bill. It does not recognize any of my email addresses

**Comment by yogkumgit** [comment]
@Silvrbckw which document you are referring to. Thanks

**Comment by Silvrbckw** [comment]
> @Silvrbckw which document you are referring to. Thanks

Microsoft 365. I'm trying to change format on Microsoft Excel. I also trying to pay a past due bill on. My Microsoft. I keep getting error code.

My Microsoft ONE cloud keeps disconnecting. 

Excel Document or Google Sheet must be saved in format xts
to submit to Google for my business page can go live.

**Comment by yogkumgit** [comment]
@Silvrbckw Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
