### ISSUE TITLE
phishing emails REAPPEAR after 30 min to inbox

### ISSUE THREAD

**Issue by Rmatey** [MicrosoftDocs/microsoft-365-docs#1122]
I report emails as phishing and they REAPPEAR about 30 min later in my inbox. Seems like they should never come back to my inbox. What is up with that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459b0779-5ac5-c20d-d01d-403276c84745
* Version Independent ID: 5a502f35-ec76-5902-923c-4e4cdbbf334b
* Content: [Report junk email and phishing scams in Outlook on the web  - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop#feedback)
* Content Source: [microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@Rmatey - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
