### ISSUE TITLE
Confusing licensing statements at odds with each other.

### ISSUE THREAD

**Issue by cimares** [MicrosoftDocs/microsoft-365-docs#11222]
The licensing statement in the callout panel is at odds with the licensing document linked at the top of the page.

The callout states that once this feature leaves preview, it will require the Microsoft Syntex Advanced add-on, however the Security & Compliance document states that Automatic application of a Sensitivity license requires an E5 license.  The call-out at the bottom of the document also states that an E5 premium license is required and an E5 trial can be used.

This needs clarification from the product group please.

From the licensing guide:
**For both client and service-side automatic sensitivity labeling, the following licenses provide user rights:**

Microsoft 365 E5/A5/G5
E5 Compliance
Microsoft 365 E5/A5/G5 Information Protection and Governance
Office 365 E5/A5/G5

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a96bf9a2-9de2-8366-24f5-d014b72fd380
* Version Independent ID: a96bf9a2-9de2-8366-24f5-d014b72fd380
* Content: [Configure a default sensitivity label for a SharePoint document library - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-default-label?view=o365-worldwide&source=docs#how-to-configure-a-default-sensitivity-label-for-a-sharepoint-document-library)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-default-label.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-default-label.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@cimares I understand the confusion. I don't make licensing decisions, but I have been in communication with those that do, so I can throw some light on this that might help. While this feature remains in preview, E5/A5/G5 compliance customers can try it. But the callout is to warn customers that at GA, they will require a Microsoft Syntex Advanced add-on.  I agree the main licensing page should be updated to clarify that this specific type of automatic labeling isn't included in E5/A5/G5 and requires a different license. I'm told they don't update that page until GA, when licensing is finalized. But I do encourage you to leave a GitHub Issue on that page asking for clarification.

Even when the feature goes GA , I'll leave the licensing link at the top of the page that will hopefully have this clarification by then. But it's also relevant for the feature's prerequisites - creating and publishing sensitivity labels, and enabling sensitivity labels for SharePoint.
