### ISSUE TITLE
But where are stored Universal annotations of Microsoft Syntex ! ?

### ISSUE THREAD

**Issue by eajclement** [MicrosoftDocs/microsoft-365-docs#11227]
[Enter feedback here]
The question is in the title and I've nothing to add 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faf8168a-116f-1111-0a1a-4f9870b86363
* Version Independent ID: faf8168a-116f-1111-0a1a-4f9870b86363
* Content: [Comment and collaborate using annotations in Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/annotations)
* Content Source: [microsoft-365/syntex/annotations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/annotations.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@eajclement-- Annotations are stored as comments in the comments table. Thanks.
