### ISSUE TITLE
Process exclusion addition

### ISSUE THREAD

**Issue by BlakeMsft** [MicrosoftDocs/microsoft-365-docs#11221]
I think we should add more processes to the process list on this page:

cmd.exe
cscript.exe
wscript.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 864c454f-e0d9-fb1d-6090-5982eb733eb0
* Version Independent ID: ca1abacc-22e4-688d-370b-e34d827fde76
* Content: [Common mistakes to avoid when defining exclusions](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@BlakeMsft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11241

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BlakeMsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by BlakeMsft** [comment]
My suggestions have not been added, so how is this closed?

Common mistakes to avoid when defining exclusions | Microsoft Learn<https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus?view=o365-worldwide>

Thank you,
Blake

**Comment by msbemba** [comment]
@BlakeMsft The Pr has been merged. The document will be updated in the next 24 hours.

Thanks
Sri

**Comment by BlakeMsft** [comment]
Thank you!
