### ISSUE TITLE
Advanced functionality not defined

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/microsoft-365-docs#11234]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

In the article, Advanced functionality is mentioned, requiring additional licensing however we don't see an explanation on what this means, what makes an alert policy contain advanced functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Microsoft 365 alert policies - Microsoft Purview (compliance)](https://review.learn.microsoft.com/en-us/microsoft-365/compliance/alert-policies?branch=main&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@tiburd kindly point internal MS contributors to the ADO form link and close the issue. Thanks

**Comment by tiburd** [comment]
@asdcristi 
Hi, Cristian-Alexandru,

Thanks for the feedback. 

As a Microsoft submitter, I'll send you an internal email with the link to the content request form so you can submit this request there. Submitting internally is easier for the compliance content team and the PG team to review, confirm, and approve.

Thanks!

cc: @yogkumgit
