### ISSUE TITLE
Renaming user account - what about device profile?

### ISSUE THREAD

**Issue by the-epoch** [MicrosoftDocs/microsoft-365-docs#11232]
It seems after renaming the user account, the device profile doesn't update. Even renaming the user's profile folder (C:\Users\%username%) to add .OLD or .TEMP at the end of their profile folder name to force creation of a new profile folder doesn't appear to fix the issue.

egj If renamaing a user account called "John Doe" to "Jane Doe", the user's profile still shows John Doe, even though the user logs in with Jane Doe.
Also, the user account picture and Start menu profile, still shows John Doe.

This needs to be fixed for a variety of very important reasons (separation from domestic violence, transition gender etc)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f42a1bfc-8920-c16d-f4c9-d29b401b7f6c
* Version Independent ID: 979b71da-fdff-238d-41fb-472f1591e51e
* Content: [Change a user name and email address - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/change-a-user-name-and-email-address?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/change-a-user-name-and-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/change-a-user-name-and-email-address.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@the-epoch Thank you for your feedback. This sounds more like a technical issue and might need involvement from the windows team as well. I'd recommend you contact support via the need help section on the admin center so that our support engineer can fix the issue or report a bug to the product team.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @the-epoch Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
