### ISSUE TITLE
Update Step 2: Upload a list of attorneys (optional) section

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#11231]
Update Step 2: Upload a list of attorneys (optional) section to include a note to state that once the attorney CSV file has been uploaded, there is no way to view the attorney list or to download the attorney list. Therefore it is recommended to keep the CSV file for reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02cdf9a2-095e-cfd9-7be0-b746cdbc200d
* Version Independent ID: 02cdf9a2-095e-cfd9-7be0-b746cdbc200d
* Content: [Set up attorney-client privilege detection in eDiscovery (Premium) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-attorney-privilege-detection?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-attorney-privilege-detection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-attorney-privilege-detection.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11242

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@nikki-c Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
