### ISSUE TITLE
E5 license clarification

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/microsoft-365-docs#11244]
Does the first chart with the column header "Defender Vulnerability Management Add-on
for Defender for Endpoint Plan 2 and E5" mean that these Add-on features are included in the E5 license or that the Add-on features are elligable for purchase at an added cost for E5 license holders?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4383e31-f80e-65de-3a90-9bb53b6845d2
* Version Independent ID: d4383e31-f80e-65de-3a90-9bb53b6845d2
* Content: [Compare Microsoft Defender Vulnerability Management plans and capabilities](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
HI @cchambers-cap 

It means that E5 customers are eligible to purchase the add-on.

I will look at updating this page to make this clearer. Thanks for your feedback.
