### ISSUE TITLE
Confusing statement

### ISSUE THREAD

**Issue by Houti** [MicrosoftDocs/microsoft-365-docs#1125]
The following doesn't make sense or is stated improperly. Why would an SP content that wasn't deleted or changed by the user when the policy expires get moved to the first-stage Recycle-Bin? it will only make sense if the admin chose to delete after retention. If they chose to do nothing, the content should stay where it was. Can you provide some clarity on this:
Content in OneDrive accounts and SharePoint sites
2. If the content is not modified or deleted during the retention period, it's moved to the first-stage Recycle Bin at the end of the retention period. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Houti  Thanks for your feedback - I'm investigating this with engineering.

**Comment by cabailey** [comment]
@Houti  Confirmed.  The docs currently describe the paths for retain and then delete (probably the most common, and the most complex).  For completeness, they need updating for retain-only, and delete-only.  This doc update is now in progress and I'll update this issue when it's published.

**Comment by cabailey** [comment]
Page now updated for retain-only and delete-only retention policies, for both SharePoint and Exchange.
