### ISSUE TITLE
Role groups that support AUs?

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/microsoft-365-docs#11254]
Can you please clarify which Role Groups support administrative units? The below is rather vague:

> Use any of the role groups from the Microsoft Purview compliance solutions that support administrative units to assign administrative units to members.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 468343fc-2808-0f78-f1a7-9d34b8fa8e16
* Version Independent ID: e3b7630f-75a9-d236-6c8b-7ebd27a7e9c0
* Content: [Permissions in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center-permissions?view=o365-worldwide#administrative-units-preview)
* Content Source: [microsoft-365/compliance/microsoft-365-compliance-center-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-compliance-center-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks
