### ISSUE TITLE
Typo in Properties Table

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#11253]
Hi,

In the Properties table - under the entry for "type" you list possible values.

The value for "Live Response" currently contains a space and is incorrect.

It should be "LiveResponse"

Thanks

Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b878866-1f3c-cdca-08c2-caab294b3815
* Version Independent ID: a6054c77-7c3f-adeb-dfea-651f7b399da5
* Content: [machineAction resource type](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machineaction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machineaction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machineaction.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@pjrcdf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11312

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pjrcdf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
