### ISSUE TITLE
Clarify whether email address of former employee can be used as an alias on another mailbox (while inactive mailbox on hold exists)

### ISSUE THREAD

**Issue by OneUser1** [MicrosoftDocs/microsoft-365-docs#11272]
Hi all,

for mail forwarding or converting to a shared mailbox to work, we are not allowed to delete the user account connected to the mailbox. We may be forced to delete the account after x days by internal compliance policies... so how do we ensure that email for the former employee's email address can still be received by another mailbox AND ensure that the content of the old mailbox is on hold using M365 Retention Policies for x years?
The problem with this is that when the email address is still present on the inactive mailbox (on hold) we are not able to set it as an alias on another mailbox.. is there a supported way to achive our scenario? If so, pls document the steps here.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Step 4 - Forward a former employee's email to another employee or convert to a shared mailbox - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-4?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-4.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-4.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@OneUser1 Thank you for your feedback. This is not a supported scenario, Only one account in the tenant can have the alias as they are unique. Workaround would be to edit the inactive mailbox email address, You can contact support via the need help section on the admin center for assistance on this.

Hope this helps!

Thanks
Sri

**Comment by OneUser1** [comment]
Thank you, @msbemba !

Can you add this as a short notice in the article? I am sure this is a question that some of us customers think about when introducing EXO and new processes for it👍🏻 thank you very much!

**Comment by msbemba** [comment]
@OneUser1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11345

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by OneUser1** [comment]
Thank you!
