### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#11273]
Step 1 states that "If you don't want to use an existing insider risk management policy (selected in Step 2), you must create a new insider risk management policy" this implies that we would have already selected a policy, but since we are in step 1 that does not make sense. Please rewrite to eliminate this ambiguity

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fce93136-62ca-b3bd-fd4b-d33a951edf81
* Version Independent ID: fce93136-62ca-b3bd-fd4b-d33a951edf81
* Content: [Help dynamically mitigate risks with Adaptive Protection (preview) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-adaptive-protection?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-adaptive-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-adaptive-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have removed that ambiguous statement as it has been rewritten in step 2. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11314

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@DeanGross Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
