### ISSUE TITLE
Suggestion to Improve the Retention Schema (when settings are to Retain and Delete)

### ISSUE THREAD

**Issue by anaritaroque** [MicrosoftDocs/microsoft-365-docs#11270]
I would like to contribute to this article, to improve in the retention schema there is available when the retention settings are to retain and delete. 
Our customers often what to understand better the the entire process/picture how retention settings works for EXO from the moment they delete an item subject to retention until when the retention copy is created and how they can reach the recoverable items subfolders. 

![image](https://user-images.githubusercontent.com/127306856/223703900-c7808e56-9ce1-4e68-affe-5dc1ee482913.png)

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1c2e44-357c-8096-5bdf-40e205778ded
* Version Independent ID: 19c7b5d9-1e0c-501b-7b70-df5aab48b36e
* Content: [Learn about retention for Exchange - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-exchange?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-exchange.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@anaritaroque  Thank you for this contribution - that's a very complex diagram that we might not be able to accommodate in our docs because of accessibility and localization requirements. However, I'll add it to a future sprint and discuss it with the team.

**Comment by anaritaroque** [comment]
Hello @cabailey, thank you for your feedback on this.

Please note, that this schema came from the fact, that on this Microsoft documentation/schema is not reflected that within the Recoverable Items folder, the retention copies actually goes to the Recoverable Items subfolders, which are not visible to any user (not even a user with Global Admin role). And that the location of the Recoverable Items subfolders is within the Exchange Admin center. - none of this is explained in the documentation. 

Therefore, from the actual schema in the documentation, which is the only one available to show to our customers, is easy to wrongly assume that the retention copies are just visible within the Recoverable Items/Deletions which is visible to any outlook user. Which is not. So, this is why I believe is important to have somehow this information also explained in the documentation.

Thank you for your attention here.

**Comment by cabailey** [comment]
@anaritaroque  Thank you for your additional notes. From the parent article that gets referenced at the top of this page, we do document that retained copies go into the Recoverable Items folder (https://learn.microsoft.com/microsoft-365/compliance/retention#how-retention-settings-work-with-content-in-place) and also for your comment "... easy to wrongly assume that the retention copies are just visible within the Recoverable Items/Deletions which is visible to any outlook user " we have:

"These secure locations and the retained content aren't visible to most people. In most cases, people don't even need to know that their content is subject to retention settings."

Then in the "How retention works for Exchange" section on this page: "Both a mailbox and a public folder use the Recoverable Items folder to retain items. Only people who have been assigned eDiscovery permissions can view items in another user's Recoverable Items folder."

What would an admin do differently with the information you highlighted?  For compliance outcomes (the business purpose behind retention of deleted messages), eDiscovery tools would search these subfolders automatically.  I wasn't aware that the Recoverable Items subfolders could be searched and traversed interactively in the Exchange Admin center, but in that case, I would expect that information (and when it's appropriate to do this) to be in the Exchange admin center documentation. It's not a requirement for compliance.

**Comment by anaritaroque** [comment]
@cabailey Thank you once again for your reply!

Can just make one last observation: in which scenario the the retention copies goes to Recoverable Items/DiscoveryHolds? 

I know that the documentation says: (https://learn.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/recoverable-items-folder) - "If In-Place Hold is enabled or if a Microsoft 365 or Office 365 retention policy is assigned to the mailbox, this subfolder contains all items that meet the hold query parameters and are hard deleted."

Does the Recoverable Items/DiscoveryHolds subfolder - is only applicable for retention policies copies and not retention labels ones? Because in any scenario tested with our Microsoft product, using just retention labels the copies never went to this subfolder. So, I just wanted confirm this understanding. 

Thank you once again.
