### ISSUE TITLE
Clarify whether emails can still be received while AAD account is only disabled, not deleted

### ISSUE THREAD

**Issue by OneUser1** [MicrosoftDocs/microsoft-365-docs#11271]
Hi all,

it is not clear from this docs (and the seven steps below) whether emails sent to a mailbox of a user that has been disabled are still received or not. Assume that the license is still in place. With the AAD account disabled it appears to me that mail flow should still be possible as it is the exact same scenario as with shared mailboxes..

Pls clarify in which scenarios and how long mails are still received and from when on mails will be rejected by Exchange Online (license removed, AAD account and mailbox deleted etc.?).

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@OneUser1 Thank you for your feedback. As long as the license is assigned, Blocking the user in the AAD or M365 Admin center does not impact mail flow. It works the same way as any other mailbox. 

The emails will be rejected by Exchange online, only when the user account is deleted from AAD.

Even in that case, you have a 30-day window to restore the account and mailbox. 

Hope this helps!

Thanks
Sri

**Comment by OneUser1** [comment]
Thank you, @msbemba!

Can you include this in the article so that it is clear? This would be great. We assumed it is like that and a short notice would help a lot. Thank you! :)

**Comment by OneUser1** [comment]
Thanks!
