### ISSUE TITLE
Please provide better RBAC guidance

### ISSUE THREAD

**Issue by HoCGeek** [MicrosoftDocs/microsoft-365-docs#11275]
This article states "You must be an admin for a business subscription to use these support methods.".  Please define what an "admin for a business subscription" is.  No such role exists, as far as I can tell, in Azure AD or O365 roles and permissions.  In AAD it looks like I might need "Billing Admin" or "Service Support Admin" to manage our support requests, but I'm not sure if that is the same list as I can see in the MS Services Hub or in the Azure "Help & Support" portal.  

Frankly, all of these support requests should be centralized and visible through a single portal.  

Also, Microsoft's own documentation recommends "Assign the least permissive role" but an awful lot of your documentation - like this article - say things like "you must be a business admin" or "sign in with your admin account" or, worse, "sign in with your global admin account" without actually defining anywhere what actual permissions are required.

Please tell me specifically what role I need to assign to my director so that he can see the list of all of our open support tickets - especially for his monthly meeting with our CSAM!

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Version Independent ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Content: [Get support - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-support.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us in resolving this issue. Thanks

**Comment by cmcatee-MSFT** [comment]
@HoCGeek You can assign someone the Service Support admin role so that they can open and manage support requests. There's a list of the admin roles available in the Microsoft 365 admin center here: [Commonly used Microsoft 365 admin center roles](https://learn.microsoft.com/microsoft-365/admin/add-users/about-admin-roles#commonly-used-microsoft-365-admin-center-roles). I'll update the article to include a link to that list.
