### ISSUE TITLE
Time to update this page.

### ISSUE THREAD

**Issue by bhirsch13** [MicrosoftDocs/microsoft-365-docs#11297]
This page is out of date. It instructs you to go to a place that has either moved or no longer exists

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34027c3c-c961-a4a6-9ef0-bb5cdcefdef1
* Version Independent ID: ae8613d1-8aad-a993-9168-6a21bf26c9e2
* Content: [Configure Conditional Access in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-conditional-access?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-conditional-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-conditional-access.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@bhirsch13 Thank you for your feedback. We will review and update the document accordingly.

Thanks
Sri

**Comment by msbemba** [comment]
@bhirsch13 Thank you for your feedback. I was able to locate the settings as described in the document. 

![image](https://user-images.githubusercontent.com/45987684/226646380-4d15b20e-938f-4ccc-96be-848d835d8e7e.png)


In case, you are not able to view the options, I'd recommend reaching out to support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bhirsch13 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
