### ISSUE TITLE
MS Graph

### ISSUE THREAD

**Issue by JimC-TX** [MicrosoftDocs/microsoft-365-docs#11307]
Why would you depreciate PowerShell for AzureAD.
Many of us have a large investment in time here and all I really need is to have to relearn something that already works just fine.
Graph is an unnecessary addition to our tool box. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d22d23da-eb81-b2e5-9655-748f77b25f80
* Version Independent ID: d8b557bc-d9c4-a58e-5ece-c4c6ffbadad0
* Content: [Remove Microsoft 365 licenses from user accounts with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/remove-licenses-from-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/remove-licenses-from-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/remove-licenses-from-user-accounts-with-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@JimC-TX Thank you for your feedback. I'd defer this to the developers and the Product team as they will be able to provide accurate information. You can leave feedback on our main feedback portal (https://feedbackportal.microsoft.com/ ), So that a dev/Product engineer could provide you with an answer.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@JimC-TX Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
