### ISSUE TITLE
Missing subnets

### ISSUE THREAD

**Issue by USCloud-EricWilborn** [MicrosoftDocs/microsoft-365-docs#11305]
The OneDrive client on MacOS is reaching out to hosts in the subnets: 40.64.0.0/13 and 51.0.0.0/8 but those subnets are not listed in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by USCloud-EricWilborn** [comment]
@kelleyvice-msft @yogkumgit Any updates?
