### ISSUE TITLE
Update the government section to include support for DOD customers.

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/microsoft-365-docs#11308]
Hi Team - based on a recent RFC escalation to the team that owns reporting/submission, it was noted that these addIns are indeed supported for DOD customers.  Today, the document only addresses GCC/GCCHigh.  Please can the documentation be updated accordingly along with any caveats those tenants may encounter (such as limitation that reports only go to an internal reporting mailbox due to the FEDRAMP requirements, etc?)  Thanks, and please feel free to reach out for internal bug references.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. thanks

**Comment by chrisda** [comment]
@drdenson, the topic was updated last week for GCC/GCC High organizations to download the add-ins: [Get the Report Message or the Report Phishing add-ins for your Microsoft 365 GCC or GCC High organization](https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure#get-the-report-message-or-the-report-phishing-add-ins-for-your-microsoft-365-gcc-or-gcc-high-organization).

I also added the following line to the Note in that section:

> In U.S. Government organizations (Microsoft 365 GCC, GCC High, and DoD), reported messages are not sent to Microsoft for analysis. They are sent only to the reporting mailbox that you identify. For more information, see [User reported settings](https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox).

OK?

And always remember, you are free to add anything you like to topics; no need to open issues first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

**Comment by drdenson** [comment]
Looks great, thanks!  Otherwise, I'll discuss direct contribution with my team/leadership - I think the concern here is that we, as support, do not feel comfortable speaking for engineering/PM as to how features are supposed to work (we receive lots of feedback around how the PG doesn't want certain limitations, etc exposed in public facing documentation, etc).  The intent of these issue requests are to advise the PG/PMs of the products/feature problems we are seeing, what customer's are complaining about, and to square what we're being told in engineering bugs against what said engineering teams want exposed publicly.  That said, point taken!

Regards,
Dean

**Comment by chrisda** [comment]
Cool. And just remember, history and precedent in this and other content says it's OK to talk about what's different in GCC, GCC High, or DoD vs. regular WW. There are call-outs everywhere.
