### ISSUE TITLE
fix the PL version ("departed" is translated wrong)

### ISSUE THREAD

**Issue by piokuj** [MicrosoftDocs/microsoft-365-docs#11303]
Hello team,
I do realize the Polish version of the page  has been done partially or fully by machine-translation but you may want to fix the translation of "departed" because it looks funny and unprofessional.

Currently "departed" is being translated to "zmarły" which means "dead/deceased" so you get the point :)
Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e422ac12-4a97-3561-d450-d2e08b9dddaf
* Version Independent ID: f0d35b02-19a2-d0b9-53a0-b395915f4bec
* Content: [Restore an inactive mailbox - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/restore-an-inactive-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/restore-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/restore-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@piokuj Thank you for this feedback. I'm replacing this word in English to be "former" and hope this helps with the translation. Can you report back when you see it live?

**Comment by piokuj** [comment]
Hi @cabailey , wow as this is a super quick response and yes, this has fixed the issue. 
Now the translation says "były" which is close to "ex-" and works well in Polish.
Cheers!

**Comment by cabailey** [comment]
@piokuj Thank you for letting me know! Closing this issue.
