### ISSUE TITLE
There is a typo in Outlook on iOS version number 

### ISSUE THREAD

**Issue by olamer** [MicrosoftDocs/microsoft-365-docs#1131]
There is a typo in Outlook on iOS about required version number for Sensitivity label capabilities in Outlook. It says 4.71+ where it should be 4.7.1+ (which was released on Oct, 16 2019). Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@olamer Yes, confirmed - thanks for the heads-up!  Fixing it now.

**Comment by cabailey** [comment]
Fix on live site now. closing.
