### ISSUE TITLE
AST - Training Campaigns - Instructions don't align with portal

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#11316]
The instructions to create a new Training Campaign - don't align with what you see in the portal

Im logged is as a Global Administrator, on a tenant with MDO-P2 licenses, and I cannot see a 'TRAINING' tab, when I follow these instructions

**_Create Training campaigns**
To create a Training campaign, do the following steps:

- In the Microsoft 365 Defender portal at https://security.microsoft.com/, go to 
-- Email & collaboration > Attack simulation training > Training tab. 
- Or, to go directly to the Training tab, use https://security.microsoft.com/attacksimulator?viewid=trainingcampaign.
-- On the Training tab, select Create new.

The new Training campaign wizard opens. The rest of this section describes the pages and the settings they contain._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e368fd8c-e40c-7999-a151-36bbb13ba52d
* Version Independent ID: e368fd8c-e40c-7999-a151-36bbb13ba52d
* Content: [Training campaigns in Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
Checking. I don't see it my M365 E5 tenant, either. The feature might be in Preview or still rolling out.

**Comment by chrisda** [comment]
@gbms311, notice the alert at the top of the article:

> [!NOTE]
> This article describes features that are in Public Preview, aren't available in all organizations, and are subject to change.

I was going to add that statement, but it was already there.

OK?

**Comment by yogkumgit** [comment]
@gbms311 Thank you very much for your kind feedback. Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
