### ISSUE TITLE
Safe Links supportability in Office 2016

### ISSUE THREAD

**Issue by gesmyrli** [MicrosoftDocs/microsoft-365-docs#11328]
Inside the "Safe Links settings for Office apps" section at the first bullet point you mention that the client requirements for Safe Links are Microsoft 365 Apps or Microsoft 365 Business Premium. However, on the second bullet point "Office apps are configured to use modern authentication" you also mention Office 2013, 2016 and 2019 which after testing it is proven that they are not working! Can you please clearly verify whether Safe Link policies are only supported in Microsoft 365 Apps, and they are not supported in other Office versions (e.g. 2016)? 

Thank you,
George

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Version Independent ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about?view=o365-worldwide#safe-links-settings-for-office-apps)
* Content Source: [microsoft-365/security/office-365-security/safe-links-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by gesmyrli** [comment]
Hello @chrisda. Thank you for your reply. Still the narrative is a little bit confusing. In my opinion it should be written in a way that it clearly says that the only supported clients for Safe Links to work are Microsoft 365 Apps or Microsoft 365 Business Premium and that at the same time Modern Authentication must be enabled in Exchange Online. Finally, just put a note or attention box that will remind everyone that with modern auth enabled the following supported versions of Office are supported or need to be configured in certain way.

**Comment by gesmyrli** [comment]
Hello @chrisda. Thank you for your reply. Still the narrative is a little bit confusing. In my opinion it should be written in a way that it clearly says that the only supported clients for Safe Links to work are Microsoft 365 Apps or Microsoft 365 Business Premium and that at the same time Modern Authentication must be enabled in Exchange Online. Finally, just put a note or attention box that will remind everyone that with modern auth enabled the following versions of Office are supported or need to be configured in certain way to work.

**Comment by chrisda** [comment]
@gesmyrli, I rewrote it to say this (changes in bold):

> Safe Links protection for Office apps has the following client requirements:
>
> - Microsoft 365 Apps or Microsoft 365 Business Premium:
>   - Current versions of Word, Excel, and PowerPoint on Windows, Mac, or in a web browser.
>   - Office apps on iOS or Android devices.
>   - Visio on Windows.
>   - OneNote in a web browser.
>   - Outlook for Windows when opening saved EML or MSG files.
>
> - **Supported** Office apps **and Microsoft 365 services** are configured to use modern authentication. For more information, see **[How modern authentication works for Office client apps](https://learn.microsoft.com/microsoft-365/enterprise/modern-auth-for-office-2013-and-2016)**.

OK?
