### ISSUE TITLE
How does a Partner set this up on their tenant??

### ISSUE THREAD

**Issue by Cloud-Monkey5000** [MicrosoftDocs/microsoft-365-docs#11321]
The article shows the feature _exists_ and how to use it, but NO Steps/Links/etc on How to _Set it up._
What needs to be done in Azure/on client's tenant, etc?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b378de4-ca71-a16b-6669-369e3e3ff9d4
* Version Independent ID: 1a1a6ec6-8c04-2172-7afa-49d268191687
* Content: [Manage multiple tenants - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/multi-tenant/manage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/multi-tenant/manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/multi-tenant/manage.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Cloud-Monkey5000 Thank you for your feedback.  If you're a partner who has a delegated admin role and manages multiple tenants, this would automatically set up. 

To gain delegated admin role, You can check - https://learn.microsoft.com/en-us/partner-center/dap-faq

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Cloud-Monkey5000 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
