### ISSUE TITLE
Please add a description of the design of the iOS indicator.

### ISSUE THREAD

**Issue by YUKAYAMAMOT** [MicrosoftDocs/microsoft-365-docs#11338]
[Enter feedback here]
I have confirmed that it is a specification that the iOS indicator does not generate alerts.
Therefore, I would appreciate it if you could add the following text.

━━━━━━━━━━━━━━━━━━━━
 Note
Defender for Endpoint on iOS supports creating custom indicators only for IP addresses and URLs/domains.
For iOS, no alerts are generated on Microsoft 365 Defender when the URL or IP set in the indicator is accessed.
━━━━━━━━━━━━━━━━━━━━

Current statement:
 Note
Defender for Endpoint on iOS supports creating custom indicators only for IP addresses and URLs/domains.

Correct:
 Note
Defender for Endpoint on iOS supports creating custom indicators only for IP addresses and URLs/domains.
For iOS, no alerts are generated on Microsoft 365 Defender when the URL or IP set in the indicator is accessed.

Why it needs to be fixed:
At this time, we have confirmed that the design does not generate alerts on Microsoft 365 Defender when connecting to the URL or IP address set in the indicator.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4eae37-e4cf-2642-d2cf-c648f90d2cc6
* Version Independent ID: 7cb88605-ddc9-5a1a-67f4-a28da1819227
* Content: [Configure Microsoft Defender for Endpoint on iOS features](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-configure-features?view=o365-worldwide#configure-custom-indicators)
* Content Source: [microsoft-365/security/defender-endpoint/ios-configure-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-configure-features.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@YUKAYAMAMOT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11343

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @YUKAYAMAMOT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
