### ISSUE TITLE
"Windows10, Windows 11, Windows Server" should be selected on "Platform"

### ISSUE THREAD

**Issue by morrow233** [MicrosoftDocs/microsoft-365-docs#11339]
[Enter feedback here]
Configuration steps on this document should be updated.

Configure ASR rules using Intune
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test?view=o365-worldwide#configure-asr-rules-using-intune

On the step 4, it says "select Windows 10 and later".
====
4. In Platform, select Windows 10 and later, and in Profile, select Attack surface reduction rules.
====

When "Windows 10 and later" is selected in Platform, "Attack surface reduction rules" cannot be selected under "Profile".
"Windows10, Windows 11, Windows Server" should be selected in Platform.

Screenshot also needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 498a23d9-d5b0-2c98-edfa-d9871675f5ae
* Version Independent ID: 498a23d9-d5b0-2c98-edfa-d9871675f5ae
* Content: [Test attack surface reduction (ASR) rules](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@morrow233 Thank you for your feedback. We have made changes to the screenshot via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11609

Once the author approves, the changes will be live.

Thanks
Sri
