### ISSUE TITLE
Include report type limits

### ISSUE THREAD

**Issue by v-fate** [MicrosoftDocs/microsoft-365-docs#1133]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc#choose-report-type

	Report Type	Access	Limit
	Summary report	Instant online access	20,000
	Enhanced summary report	Downloadable CSV file only	50,000
	Extended report	Downloadable CSV file only	1,000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58f8e2c-428a-4d8e-e8b7-a0342a0038db
* Version Independent ID: 6e7fab1b-1e24-9e36-176d-c3fb14f233a7
* Content: [Message trace in the Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc#feedback)
* Content Source: [microsoft-365/security/office-365-security/message-trace-scc.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/message-trace-scc.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@v-fate, Done.

Thanks for the feedback.
