### ISSUE TITLE
To delete more than 10 items, you can use the Search-Mailbox -DeleteContent command in Exchange Online PowerShell.

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/microsoft-365-docs#1134]
**Problem Location:** 
In the section "Before you Begin" https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization#before-you-begin

**Problem Description:**
The third bullet point, last sentence is no longer correct as Microsoft seems to have removed that command.

**Solution Requested:**
We need to know the new solution for deleting mail en-masse.

**Reasoning:**
Our specific use case is migration related (Below) but there could be plenty of use cases for this.
Example 1. Somehow spam makes it into the email system and all users have hundreds or thousands of messages.
Example 2. We are migrating from On-Premise 2013 and some users have more than 300gb of mail and are still on-premise.
The O365 100GB Inbox+100GB Archive is not large enough to migrate. 
The AutoExpand feature does not seem to function until the primary inbox is migrated to Exchange Online.

So we are stuck deleting mail. Ok, no problem.
But where we used to just be able to run a PowerShell command to do so without much effort.
Microsoft is introducing much more effort, in that now we must somehow mount the mailbox elsewhere and run this stuff manually. And with this large amount of mail, that is an extremely slow process, that takes a lot of IT time, and the users time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 464a4f5f-8740-79aa-3647-a9b5e351656c
* Version Independent ID: a51103db-92b2-d225-d493-81d624e6fc6b
* Content: [Search for and delete email messages in your Office 365 organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization#feedback)
* Content Source: [microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Krytical13 Thanks for the thoughtful feedback. I would suggest you copy and paste a snippet of this feedback to https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=139404

A few comments:

- Search-Mailbox cmdlet is being retired only in EXO/O365 - It will still be available in on-premises server versions, so you can still use in Ex. 2?
- Search-Mailbox cmdlet will be available in EXO until April 1, 2020
- You could script New-ComplianceSearchAction -Purge command and loop it to make multiple passes to address the 10-item limit per search action.
- After mail is migrated, [Threat Protection](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/microsoft-threat-protection) functionality in O365 can help reduce spam
- More info about the [retirement of legacy eDiscovery tools](https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement)
