### ISSUE TITLE
Where are templates stored?

### ISSUE THREAD

**Issue by DLPAAU** [MicrosoftDocs/microsoft-365-docs#11357]
I have created my first GDAP template, how do I now access that template to assign to other tennants?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8902c43-bbb2-e567-a712-d2ce1c40ce35
* Version Independent ID: c8902c43-bbb2-e567-a712-d2ce1c40ce35
* Content: [Set up GDAP for your customers - Microsoft 365 Lighthouse](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-setup-gdap?view=o365-worldwide#related-content)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-setup-gdap.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-setup-gdap.md)
* Service: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@DLPAAU - Once you've created and saved a GDAP template, you can assign it to other customer tenants by re-running GDAP Setup from the GDAP Setup card on the Home page of Lighthouse. When you open GDAP Setup, proceed to the **Assign customer tenants** step and select additional tenants to assign the template to.

**Comment by DLPAAU** [comment]
Thanks you Shari

However when I go back to Template Setup all of the security have been removed, I cannot jump directly to Assign customer tenants.

***@***.***

Deb Landon

Support email: ***@***.******@***.***>
Support portal: https://my.pa.com.au
W www.pa.com.au<http://www.pa.com.au>
T 1300 658 608<tel:1300658608>
Our clients regularly give us positive feedback on our informative events; you can register for them on our events page<https://www.pa.com.au/events>.
***@***.******@***.******@***.******@***.******@***.******@***.***<https://blog.pa.com.au/>

**Comment by SKjerland** [comment]
@DLPAAU - I'm sorry to hear you're having a problem with it. Since this appears to be a problem that you're having with the product, you'll need to reach out to Support to troubleshoot. They'll know if this is a known issue, or if it's something they need to walk you through to get it working. Thanks!
