### ISSUE TITLE
Items with this label

### ISSUE THREAD

**Issue by pmcgrath66** [MicrosoftDocs/microsoft-365-docs#1135]
When I go to "Explore Items" for a Retention Label, click "Items with this label", select SharePoint, and them my site collection, I see nothing. I not only have labels being used I have received disposition emails for them.

Any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35afb875-bb47-fc7d-7e95-36cbde2b671b
* Version Independent ID: 3a2ad411-cae1-efa2-f089-97ed2df52fb4
* Content: [View label usage with label analytics - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/label-analytics#feedback)
* Content Source: [microsoft-365/compliance/label-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/label-analytics.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@pmcgrath66 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by pmcgrath66** [comment]
Thank you. I will update the board when I have an answers from Microsoft.

Patrick McGrath
SharePoint Administrator
[Open Dealer Exchange]
31440 Northwestern Hwy.  |  Suite 250  |  Farmington Hills, MI 48334
Office: 313.349.0052  |  Cell: 734.644.4635  |  Fax: 313.749.0990
pmcgrath@opendealerexchange.com<mailto:pmcgrath@opendealerexchange.com>
www.opendealerexchange.com
Follow Us: LinkedIn<http://www.linkedin.com/company/open-dealer-exchange-llc>
