### ISSUE TITLE
IP ranges up to date?

### ISSUE THREAD

**Issue by p-graves** [MicrosoftDocs/microsoft-365-docs#11352]
My server is trying to reach address:

23.1.33.207

23.1.33.197

23.1.33.200

23.1.33.204

22.1.33.208

21.1.33.215

21.1.33.213

However, the only address range listed that's close to those is  23.103.160.0/20, but that range doesn't include the attempted IPs.

And it's like that for a few ranges.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by p-graves** [comment]
Was this fixed?

**Comment by tiburd** [comment]
We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).
