### ISSUE TITLE
M365 Usage Report

### ISSUE THREAD

**Issue by MSPFE2019** [MicrosoftDocs/microsoft-365-docs#11363]
How can I modify the report to retrieve data from multiple tenants? Our goal is to generate a single report that consolidates data from all six or more tenants.

**Comment by msbemba** [comment]
@MSPFE2019 Thank you for your feedback. Currently, the feature is not available via the admin center, However, You can still get the data using Power BI usage analytics- 
https://learn.microsoft.com/en-us/microsoft-365/admin/usage-analytics/customize-reports?view=o365-worldwide#customizing-the-reports-in-power-bi-desktop

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MSPFE2019 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
