### ISSUE TITLE
Defender upgrades generate CodeSignSummary*.md file in 

### ISSUE THREAD

**Issue by bootrec** [MicrosoftDocs/microsoft-365-docs#11368]
All my Apple computers have been getting a CodeSignSummary*.md file appearing in Applications, caused by Defender upgrades. This seems abnormal, didn't use to do this before, seems like something changed with your ATP processes recently. 

<img width="1044" alt="Screenshot 2023-03-15 at 14 12 49" src="https://user-images.githubusercontent.com/65039324/225729050-30a5c436-8f30-4f37-8da3-8328e3e5c2f0.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3a947a2-093c-0f4e-7053-c30112d1cee1
* Version Independent ID: 12fbc5ca-2b24-6717-ac98-331f0bba5278
* Content: [Set up the Microsoft Defender for Endpoint on macOS policies in Jamf Pro](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@bootrec Thank you for your feedback. Sorry to hear that, looks like a technical issue or bug to me. I'd recommend you contact support via the need help section on the admin center, so an engineer can work with you and fix or escalate the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bootrec Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
