### ISSUE TITLE
RHEL and variants (CentOS, Fedora, Oracle Linux and Amazon Linux 2) - inaccurate desciption

### ISSUE THREAD

**Issue by PiotrWadolowski** [MicrosoftDocs/microsoft-365-docs#11362]
In table there is versioning: "For RHEL/Centos/Oracle 8.0-8.5" should be "For RHEL/Centos/Oracle 8.0-8.7" as 8.6 and 8.7 are supported as well

**Comment by denisebmsft** [comment]
Hello @PiotrWadolowski. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by PiotrWadolowski** [comment]
Hi Denise,

Deploy Microsoft Defender for Endpoint on Linux manually | Microsoft Learn<https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide#rhel-and-variants-centos-fedora-oracle-linux-and-amazon-linux-2>

Kind regards,
Piotr Wądołowski
Support Escalation Engineer
Microsoft Cybersecurity - Endpoint Protection
Office: +48 (22) 5941543
Mon-Fri 9am-5pm GMT+1
***@***.******@***.***>

[Microsoft Logo]

We are always interested to hear your feedback. Please feel free to reach me or my manager regarding the level of service you have received at ***@***.******@***.***>

**Comment by msbemba** [comment]
@PiotrWadolowski Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11406

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PiotrWadolowski Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
