### ISSUE TITLE
Question on section 2.5 Properties (via files)

### ISSUE THREAD

**Issue by PaulFeaser** [MicrosoftDocs/microsoft-365-docs#11365]
Section 2.5 Properties doesn't list out the fields as 1.6 for Json does.  Does this comment "Some additional columns might be returned in the response. These columns are temporary and might be removed. Only use the documented columns" indicate that the documented columns are what is in 1.6?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5086764e-b412-9ea7-1a69-16ebca004e27
* Version Independent ID: 5086764e-b412-9ea7-1a69-16ebca004e27
* Content: [Security baseline assessment methods and properties per device](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/export-security-baseline-assessment?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/export-security-baseline-assessment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/export-security-baseline-assessment.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@PaulFeaser Thank you for your feedback. You are correct, the JSON response might return additional columns, however, they are temporary and will be removed.

Hope this helps!

Thanks
Sri

**Comment by PaulFeaser** [comment]
Thank you!  Working through the various pages as we are using the Bulk Exports and trying to reconcile what fields we should be getting for each.

**Comment by msbemba** [comment]
Thank you for understanding.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PaulFeaser Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
