### ISSUE TITLE
Requirements to use M365 Lighthouse

### ISSUE THREAD

**Issue by ShawnHag** [MicrosoftDocs/microsoft-365-docs#11372]
Is it possible for an ordinary company to use Microsoft 365 Lighthouse to manage their multiple tenants?
Or is this service only for MSSPs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4b28125-703d-234a-b52f-2a46de32ffa6
* Version Independent ID: 55d48817-9185-2fd9-55cf-cea275666fbe
* Content: [Requirements for Microsoft 365 Lighthouse - Microsoft 365 Lighthouse](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-requirements.md)
* Service: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@ShawnHag Thank you for your feedback. Currently, it is only available for  Managed Service Providers (MSPs). Note that even 
MSPs must be enrolled in the Cloud Solution Provider (CSP) program as an Indirect Reseller or Direct Bill partner to use Lighthouse.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ShawnHag Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
