### ISSUE TITLE
Claritiy  on invoice pay 

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/microsoft-365-docs#11381]
The documentation on invoice pay is not clear or user friendly.  Lot of users are not understanding the limit for  invoice pay eligibility. 
The certain amount with location should be listed so that it is clear and concise  to customer. 

Lot of customer who is not able to chose invoice pay is questioning the reason and not sure about the amount to be selected.  MS says it USD  6000  however is it same across the service location ?

Be an established customer for at least six months and have no outstanding balances
**Have a subscription cost that exceeds a certain amount (this amount varies by service location)**
Pass a credit check

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82583c48-08e6-9acb-657b-ce1fe44e76a5
* Version Independent ID: cbdcf652-3a68-4fa3-9f3b-92c518e0b710
* Content: [Payment options for your Microsoft business subscription](https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @robinpoulose1 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by robinpoulose1** [comment]
as per support agent its $6000 / month. Is the cap same for other coutries as well ?
