### ISSUE TITLE
ronis/menof.ibm

### ISSUE THREAD

**Issue by vortex-maze** [MicrosoftDocs/microsoft-365-docs#11388]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by vortex-maze** [comment]
continue

**Comment by msbemba** [comment]
@vortex-maze Thank you for your feedback. Is ronis/menof.ibm  a mailbox? If this is a technical question or help needed during troubleshooting, I'd recommend you contact support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by vortex-maze** [comment]
continue
