### ISSUE TITLE
Toggle switch to left?

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/microsoft-365-docs#11393]
Shouldn't you toggle the switch to the **_left_** to disable the services under **Manage settings for email apps** ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 073882cd-36d0-b95a-77b2-aadd06fa34a5
* Version Independent ID: 463f2f77-3fb0-8078-5b49-878747f2842b
* Content: [Responding to a Compromised Email Account - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@LijuV-MSFT, fixed.

Thanks for the feedback.

Closing
