### ISSUE TITLE
EDM licensing information missing

### ISSUE THREAD

**Issue by iftikhariqbal** [MicrosoftDocs/microsoft-365-docs#11391]
[Enter feedback here]

The link "See the [data loss prevention service description] for complete licensing information" does not mention anything regarding license rights for EDM.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5c5906d-c5e2-dbee-7e57-9f00510bac48
* Version Independent ID: e5c5906d-c5e2-dbee-7e57-9f00510bac48
* Content: [Get started with exact data match based sensitive information types - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sit-get-started-exact-data-match-based-sits-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sit-get-started-exact-data-match-based-sits-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sit-get-started-exact-data-match-based-sits-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks
