### ISSUE TITLE
Confusing if doc applies only to MDE or also M365D

### ISSUE THREAD

**Issue by khbafl** [MicrosoftDocs/microsoft-365-docs#11408]
Hello, 

The mention "Applies to Microsoft 365 Defender" on top of this page is a bit confusing, please make it more clear if this documention applies only to MDE. 

Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55901976-4431-c470-88cb-af7430bb7339
* Version Independent ID: 0e80c507-335d-bd5e-7315-b8fe30aec0ff
* Content: [Grant access to managed security service provider (MSSP)](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/grant-mssp-access?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/grant-mssp-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/grant-mssp-access.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@khbafl thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11442

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @khbafl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
