### ISSUE TITLE
Clarification on Valid Users

### ISSUE THREAD

**Issue by MSFT-SeanG** [MicrosoftDocs/microsoft-365-docs#11412]
In the section around "Simulation messages not delivered to all targeted users" - what constitutes a "valid" or "invalid" recipient email address? Can this be clarified within this section?

Is Attack Simulation expected to count On-Premises users as "invalid"? There is nothing in these docs stating (or not stating) that On-Premises mailboxes are supported.

https://learn.microsoft.com/microsoft-365/security/office-365-security/attack-simulation-training-faq#simulation-messages-not-delivered-to-all-targeted-users

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b480c7ad-d444-b167-6c3c-80a8e8fb714d
* Version Independent ID: a17b1117-7d8a-54b1-fa72-6cc7b644a254
* Content: [Attack simulation training deployment considerations and FAQ - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-faq?view=o365-worldwide#simulation-messages-not-delivered-to-all-targeted-users)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-faq.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@MSFT-SeanG Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
