### ISSUE TITLE
Link to keyword list chapter/section

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1141]
Hello,

it would be nice if you could add a link to the keyword list chapter/section within this sentence:

'Although you can create keyword lists in sensitive information types, keyword lists are limited in size and require modifying XML to create or edit them.'

I would like to read more about keyword lists to understand them better but I wasn't able to find the documentation of them via the Microsoft's site search nor via Google.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 196b87de-20ff-37ea-79b8-beb37a1361e0
* Version Independent ID: d3aa9f91-0cec-b9df-6fc7-415242393e3f
* Content: [Create a keyword dictionary - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-keyword-dictionary#feedback)
* Content Source: [microsoft-365/compliance/create-a-keyword-dictionary.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-keyword-dictionary.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @GiantCrocodile, 
Thanks for your suggestion. The section you suggest adding a link to immediately follows the sentence where you suggest the link be added.

**Comment by GiantCrocodile** [comment]
I think this is a misunderstanding @chrfox: I mean a link to an article where it's explained how to create and edit the XML:

`Although you can create keyword lists in sensitive information types, keyword lists are limited in size and require modifying XML to create or edit them.`
