### ISSUE TITLE
Tables aren't usable making it really hard to navigate the info.

### ISSUE THREAD

**Issue by OzmeisterO** [MicrosoftDocs/microsoft-365-docs#11414]
I love the Standard vs. Strict preset policy page as it gives me all the information I need when people ask how the preset policies are configured.  Unfortunately, several of the tables are unusable because they are too wide to show all the columns, and you can't easily scroll across as the horizontal scroll bar is several pages down at the bottom of the table.  This is the case for several tables, with the one in the 'EOP anti-spam policy settings' section (https://learn.microsoft.com/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365#eop-anti-spam-policy-settings) being the worst.

Is it possible to make the tables wider so they show all the columns (and I can scroll the whole page if I need to)?  This would be far better than the current experience.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@OzmeisterO, tables are definitely a weakness of markdown as there's zero ability to control column widths.

The only true solution would be to convert the markdown tables to HTML, but HTML tables are a royal pain to modify and keep up-to-date.

The only trick I can offer is to click in the table and use the right and left cursor keys on your keyboard to scroll horizontally so you don't have to go all the way down to the bottom of the table to use the horizontal scroll bar.

**Comment by yogkumgit** [comment]
@OzmeisterO Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
