### ISSUE TITLE
ASR rule "Block Office communication application from creating child processes" not available on Endpoint Configuration Manager

### ISSUE THREAD

**Issue by morcha134** [MicrosoftDocs/microsoft-365-docs#11418]
In the table "ASR rules supported configuration management systems" next to the rule "Block Office communication application from creating child processes" it is written that it is supported by Microsoft Endpoint Configuration Manager starting from CB 1710. I am running CB 2111 and this ASR is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Version Independent ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Content: [Attack surface reduction rules reference](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @morcha134 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
