### ISSUE TITLE
DLM - Information on document libraries in scope and possible limitations regarding classig SharePoint sites/templates

### ISSUE THREAD

**Issue by janvonr** [MicrosoftDocs/microsoft-365-docs#11419]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

The following topics/questions are not completely answered in the documentation and customers are often asking for a clear feedback regarding them, as this could have a big impact on the retention/deletion implementation.

1. Which SharePoint/OneDrive libraries are in scope of a deletion policy? The documentation says "All files in document libraries", but what is the exact definition behind it, so that customer can identify the libraries that would be impacted? Do we use the contentclass:STS_List_DocumentLibrary property?
2. For retention/deletion policies are there any known limitations regarding classic SharePoint sites/templates?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft Purview (compliance)](https://review.learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide&branch=main#whats-included-for-retention-and-deletion)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Hi @janvonr I'm told that the content class that starts with "STS_ListItem" and is not a folder will identify eligible items for a retention policy but there currently isn't a way via the UI to see/confirm the exact items.

For your second question, I'm not aware of any known limitations regarding M365 retention for classic SharePoint sites/templates but will let you know if I hear of any after further investigations with the engineering team. If you are experiencing problems, I encourage you to use the standard support channels.
