### ISSUE TITLE
Domain and subdomain

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/microsoft-365-docs#1142]
*.contoso.com/* is said to behave as such: "Allows recipients to visit a domain, subdomains, and paths, such as https://www.contoso.com, https://www.contoso.com, https://maps.contoso.com, or https://www.contoso.com/a."

But URLs like https://contoso.com/a/b, which to me sounds like a domain, are being re-written.

Sites that use both https://contoso.com/a/b and https://www.contoso.com/a/b need to have two entries to a custom Do Not Rewrite URL list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac84f75-b6d9-9495-873a-8f87b90b8034
* Version Independent ID: 18369495-0e0f-e3e1-6945-0200790fd107
* Content: [Set up a custom do-not-rewrite URLs list using Office 365 ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by joinimran** [comment]
@kevintaber - Thank you for sharing your feedback. Please note the following:

(.contoso.com/ is said to behave as such: "Allows recipients to visit a domain, subdomains, and paths, such as https://www.contoso.com, https://www.contoso.com, https://maps.contoso.com, or https://www.contoso.com/a) - This is only applicable when you are using wildcards, .contoso.com/ will not allow to visit subdomains or domain paths but using wildcard * will help to achieve the required goals.

https://contoso.com/a/b is the same as https://contoso.com/a/b as www is not a subdomain like maps.contoso.com so adding one URL is sufficient. 

Thanks.

**Comment by mypil** [comment]
@kevintaber  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by joinimran so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by DGG-IT** [comment]
I don't think this is sufficiently answered. Can you clarify?  If I have a record *.contoso.com/* will https://contoso.com/a/ be re-written? https://contoso.com does not seem to match the *.domain.com pattern.

If *.contoso.com/* does NOT match https://contoso.com/a/ then the documentation should be updated to remove the word "domain" from 'Allows recipients to visit a domain, subdomains, and paths,'

If *.contoso.com/* DOES match https://contoso.com/a/ then the documentation should be updated to add an example like https://contoso.com/a/

**Comment by DGG-IT** [comment]
The comment tool also seems to interpret asterisks (*) as markdown for italics. 

I don't think this is sufficiently answered. Can you clarify? If I have a record (star).contoso.com/(star) will https://contoso.com/a/ be re-written? https://contoso.com does not seem to match the *.domain.com pattern.

If (star).contoso.com/(star) does NOT match https://contoso.com/a/ then the documentation should be updated to remove the word "domain" from 'Allows recipients to visit a domain, subdomains, and paths,'

If (star).contoso.com/(star) DOES match https://contoso.com/a/ then the documentation should be updated to add an example like https://contoso.com/a/
