### ISSUE TITLE
DLM - Automatic deletion of inactive mailboxes with items that need to be retained

### ISSUE THREAD

**Issue by janvonr** [MicrosoftDocs/microsoft-365-docs#11423]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]

In the documentation we're saying that inactive mailboxes cannot be deleted when an hold is applied and that for inactive mailboxes with one or more retention labels configured to retain items the hold cannot be removed, which makes sense.

But what happens if the retention period for the retained items is over? Will the inactive mailbox be deleted automatically or is it necessary to do this manually? 

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c129f4e-664c-971f-e438-18ae3eb87f17
* Version Independent ID: e63b5be8-3c3c-2592-72bf-3f00cca0e525
* Content: [Delete an inactive mailbox - Microsoft Purview (compliance)](https://review.learn.microsoft.com/en-us/microsoft-365/compliance/delete-an-inactive-mailbox?view=o365-worldwide&branch=main)
* Content Source: [microsoft-365/compliance/delete-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Hi @janvonr At this time we don't scan to identify if any items that were marked for retention have expired all retention periods, so inactive mailboxes are not automatically deleted. However, all data will expire as needed and there's no need to manually delete that mailbox if all your policies were correctly in place at the time of account deletion.

It looks like you're a Microsoft employee - in which case there's no need to file a GitHub Issue for M365 retention docs. You can contact me direct.
