### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by TerryJ123** [MicrosoftDocs/microsoft-365-docs#11422]
[Enter feedback here]
Under this section - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboarding-endpoint-manager?view=o365-worldwide#confirm-attack-surface-reduction---attack-surface-reduction-rules
There is a typo in step 1. 
Before applying the policy on a test device, pen a PowerShell Window and type Get-MpPreference.

It should read:
Before applying the policy on a test device, OPEN a PowerShell Window and type Get-MpPreference.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25e228a0-6a2c-2ae2-655b-ada8b6f313bc
* Version Independent ID: fe0dcf35-c7f7-8dce-f829-9bc03827a40a
* Content: [Onboarding using Microsoft Intune](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboarding-endpoint-manager?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboarding-endpoint-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboarding-endpoint-manager.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@TerryJ123 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11445

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TerryJ123 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
