### ISSUE TITLE
How do we tune rules to make them easier or harder to match?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#11428]
There once was an article that discussed this topic. The page cannot be found and I am having trouble locating another page that discusses this topic. Please advise
https://learn.microsoft.com/en-us/microsoft-365/compliance/microsoft-365/compliance/dlp-learn-about-dlp?view=o365-worldwide#tuning-rules-to-make-them-easier-or-harder-to-match

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b58684f5-131c-2815-c670-ffed84c37df0
* Version Independent ID: b58684f5-131c-2815-c670-ffed84c37df0
* Content: [Design a Data loss prevention policy - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-design?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-policy-design.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-policy-design.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@jonwbstr Thank you for your feedback. Are you referring to the below section?
https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-learn-about-dlp?view=o365-worldwide#monitor-outcomes-and-fine-tune-the-policy

Thanks
Sri

**Comment by jonwbstr** [comment]
Doesn't look like it

A rule is creating too many false positives. How do I get fewer false
positives?

A rule is creating too missing legitimate matches. How do I get it to catch
more legitimate matches?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
Email sent to author 27 March 2023

**Comment by yogkumgit** [comment]
@jonwbstr Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
