### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#11430]
The term 'get-mgsubscribedsku' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e0c0537-bbc1-02c8-7ae2-78646b2a2e98
* Version Independent ID: a9becd2e-5989-da88-8b6c-0e51476a21c7
* Content: [Disable access to Microsoft 365 services with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. I was able to test and the cmdlet works as usual

![image](https://user-images.githubusercontent.com/45987684/227247711-817d139e-0743-4cf0-a729-1dcb1cc7716a.png)


If you continue to have issues, I'd recommend reaching out to the support team via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dkotars Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
