### ISSUE TITLE
Record Type 50 and 51

### ISSUE THREAD

**Issue by MurtazK** [MicrosoftDocs/microsoft-365-docs#1143]
Where can I find details about Record Type 50 and 51 online? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d18ff7-80de-a4d1-41a3-3601f09d3442
* Version Independent ID: dc3327c1-5c78-53ee-6ecb-18b274ddcdbd
* Content: [Detailed properties in the Office 365 audit log - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log#feedback)
* Content Source: [microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@MurtazK Thanks for query. Currently, these record types aren't documented, but will look into getting these documented. RecordType = 51 are message hygiene events probably related to anti-spam and anti-malware protection via policies in the O365 security and compliance center. RecordType = 50 are aggregated Exchange item events (aggregation of multiple similar operations on Exchange items). Please open a ticket with Microsoft Support for help, more info.
