### ISSUE TITLE
Missing information on role/privileges required to view device information

### ISSUE THREAD

**Issue by dpshutts** [MicrosoftDocs/microsoft-365-docs#11439]
I was hoping to find guidance on how to provide access to the device inventory to part of our team but that's not currently listed on the page. I have a colleague able to access security.microsoft.com but that same colleague cannot see the Device Inventory - nor can I see a role that has the prefix 'Device' 

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d401bb34-5a2e-7f66-8fcd-28a395c62a99
* Version Independent ID: 1022827b-273c-7351-ee5d-189e6caa5fee
* Content: [Device inventory](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machines-view-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machines-view-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machines-view-overview.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
See https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/rbac?view=o365-worldwide
