### ISSUE TITLE
Is SSL offloading supported in hybrid exchange environments?

### ISSUE THREAD

**Issue by horsi3** [MicrosoftDocs/microsoft-365-docs#11437]
Hi are you please able to clarify something for me:

The way the page reads to me now, it's clear that SSL offloading is **not** supported for on-prem only environments.
The very next section talks about on-prem hybrid 365 environments and has no mention of SSL offloading. Does this mean that in that scenario, SSL offloading is supported?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6967c48-088b-9648-a84e-24717f592389
* Version Independent ID: bff5a2db-aa33-ec7d-fd39-070bf0d77a36
* Content: [Hybrid Modern Authentication overview and prerequisites for use with on-premises Skype for Business and Exchange servers - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/hybrid-modern-auth-overview?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/hybrid-modern-auth-overview.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@horsi3 Thank you for your feedback. Yes, SSL Offloading is supported in Hybrid and no Supported in On-prem only environments.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @horsi3 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
