### ISSUE TITLE
Cloud Protection Level GPO Confusion

### ISSUE THREAD

**Issue by MichaelNell** [MicrosoftDocs/microsoft-365-docs#11446]
Hi Team, 

Could we please add a note to this page to avoid customer confusion when setting Cloud Protection level settings using GPO. 

From my understanding GPO state has three options
Not Configured -> No value found
Disabled -> A value of 0 in the setting
Enabled -> A value of 1 or more

The issue with setting Cloud protection level to default it sets a registry value as 0. What happens in RSOP or GPMC the state shows as Disabled.

![image](https://user-images.githubusercontent.com/128721281/227247190-f3b2b895-60f6-44a4-a859-3dba6f5be2c3.png)

We have confirmed the setting to be working as expected, it is RSOP and GPMC that is causing doubt with customers.

The RSOP results from an enabled configuration with the default blocking level

![image](https://user-images.githubusercontent.com/128721281/227248404-7d00f640-1c10-4fee-aa55-10b5283ea9ec.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: babd7f5d-94d7-dd5a-bc57-420f5fe36ab0
* Version Independent ID: 144573e2-f4a6-6961-4302-750e64ec41b6
* Content: [Specify the cloud protection level for Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/specify-cloud-protection-level-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/specify-cloud-protection-level-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/specify-cloud-protection-level-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hi @MichaelNell. Thank you so much for your feedback. I have opened this pull request to add a note. Please let me know if you have any other questions. https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/19715

**Comment by denisebmsft** [comment]
Doc updated! Thank you so much @MichaelNell for your help!
