### ISSUE TITLE
Please make this feature available for everyone, not only MS partners.

### ISSUE THREAD

**Issue by PDM314** [MicrosoftDocs/microsoft-365-docs#11440]
Please make this feature available for everyone, not only MS partners.

**Comment by denisebmsft** [comment]
Hello @PDM314. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by yogkumgit** [comment]
@PDM314 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
