### ISSUE TITLE
Safelinks url issue in Outlook email

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftDocs/microsoft-365-docs#11441]
We are currently doing some tests and receiving emails in our Outlook but some reason, one of the emails is coming up with an issue. 

When the mouse is hovered on top of either a **button** or a **picture** in the email, no **url** is being displayed where as the other email is fine and we can see the URLs.

I've already added both the URLs in the SafeLinks option _(**Do not rewrite the following URLs in email**)_ but still the same issue.

Not sure where to check further or if there is a bug.

Kindly help me out.

Awaiting for your reply,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Version Independent ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Closing due to lack of response.

Thanks for the feedback.
