### ISSUE TITLE
Configuration steps by Intune

### ISSUE THREAD

**Issue by morrow233** [MicrosoftDocs/microsoft-365-docs#11457]
[Enter feedback here]
The description of the configuration steps are only by GPO.

Configure remediation options
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus?view=o365-worldwide#configure-remediation-options

Same config can be controled by Intune.
Please consider to add configuration steps by Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c974b4-7004-d52c-0ffe-c6f3729477f9
* Version Independent ID: 7162a35d-fc78-54ac-531a-02ec8c07a8ff
* Content: [Configure remediation for Microsoft Defender Antivirus detections](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Hello @morrow233 @yogkumgit and thank you for the feedback. I've updated the article, and you'll see the changes live later today (like around 4 p.m. Pacific Time). Thanks again for posting this issue and for helping us to improve our documentation.
