### ISSUE TITLE
How to check if a link was scanned and approved?

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/microsoft-365-docs#11452]
We received a phishing email (high-confidence) that does not appear to have been processed by SafeLink.  

How can I check (audit?) logs to determine if the link was scanned by SafeLink.  I've Binged/searched/ChatGPT'd and cannot find how to determine if a link in an email was scanned or why it was not, if it wasn't.  

I know Microsoft used to provide a section "How to tell if it works", I would love to see this information provided.
I understand that you will know it's working if you see the wrapper, but in this case, there is no safelink wrapper in the URL - and I want to know why.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Version Independent ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mntorq, your best way forward is to open a support ticket about this. Report back here with any findings that can help improve the documentation.

**Comment by chrisda** [comment]
@mntorq, are you saying that the message was detected by anti-spam filtering as high confidence phishing? The table in [this article](https://learn.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined) needs to be updated for Safe Links and Safe Attachments, but I bet it's as simple as Safe Links scanning is lower in the stack, so Safe Links never got to it.

The **URL detonation** category that's shown in the [Threat protection status report](https://learn.microsoft.com/microsoft-365/security/office-365-security/reports-email-security#threat-protection-status-report) shows detections by Safe Links.

Thanks for the feedback.

Closing
