### ISSUE TITLE
Circular link

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/microsoft-365-docs#11461]
"For information how to update or install the platform update, see [Update for Windows Defender antimalware platform](https://support.microsoft.com/help/4052623/update-for-windows-defender-antimalware-platform)."

This link leads to THIS page.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61d65c37-bbb6-5c7a-8405-5994badd0b23
* Version Independent ID: 61d65c37-bbb6-5c7a-8405-5994badd0b23
* Content: [Microsoft Defender Antivirus security intelligence and product updates](https://learn.microsoft.com/en-GB/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @BR77BE. Oh my goodness -- thank you so much for catching this! My apologies! I've updated the article and the changes will be live later today.
