### ISSUE TITLE
Question about scope of "Select the domain to use for email from Microsoft 365 products"

### ISSUE THREAD

**Issue by cclayton18** [MicrosoftDocs/microsoft-365-docs#11472]
It isn't clear from the [documentation ](https://learn.microsoft.com/en-us/microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products?view=o365-worldwide) whether the email from Microsoft services uses our domain only if was generated by activity of one of our own tenant users, or if it would also change for someone outside our org (in another tenant) sharing content with us.  If the former, that really helps us with external email tagging and other security.  If the latter, there's little point in opting in.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eda44995-3561-2f08-e776-5359b0aaf37c
* Version Independent ID: eda44995-3561-2f08-e776-5359b0aaf37c
* Content: [Select the domain to use for email from Microsoft 365 products - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@cclayton18 Thank you for your feedback. Microsoft services use your domain only if was generated by the activity of one of our own tenant users.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cclayton18 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
