### ISSUE TITLE
Add clarification about email submissions from GCC tenants.

### ISSUE THREAD

**Issue by ScyberSocii** [MicrosoftDocs/microsoft-365-docs#11471]
It would also be helpful if this page noted that admins in GCC tenants must open a case to submit email to Microsoft for analysis. The 'Import' box on this page is what I'm referring to: https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-admin?view=o365-worldwide. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b36a6f3e-632a-bf8e-4293-7eae6bd6e68f
* Version Independent ID: b36a6f3e-632a-bf8e-4293-7eae6bd6e68f
* Content: [(False Positives) How to handle legitimate emails getting blocked from delivery using Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/step-by-step-guides/how-to-handle-false-positives-in-microsoft-defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/step-by-step-guides/how-to-handle-false-positives-in-microsoft-defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/step-by-step-guides/how-to-handle-false-positives-in-microsoft-defender-for-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@ScyberSocii Thank you for your feedback. We have added an important note to the document which states "In U.S. Government organizations (Microsoft 365 GCC, GCC High, and DoD), admins can't use the Submissions page in the Microsoft 365 Defender portal to submit messages to Microsoft. Instead, admins in those organizations need to open a support case to submit messages."

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ScyberSocii Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
