### ISSUE TITLE
How do I know this worked?

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#11477]
In Safe Documents, there are three files you can use.  

In SafeLinks, there USED to be a URL (www.safelinks.contoso.com) that would trigger a safelinks response. 

Can we have that back?  We have eicar for AM, GTube for AS, Test docs for SD, but nothing for safelinks.

Please empower us to show customers the tool works more!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a27041e-26ec-eaf9-83e3-a7a926a50d33
* Version Independent ID: 3a27041e-26ec-eaf9-83e3-a7a926a50d33
* Content: [Set up Safe Links policies in Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-policies-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links-policies-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-policies-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@chrislehr, I added the following item to the [How do you know these procedures worked?](https://learn.microsoft.com/microsoft-365/security/office-365-security/safe-links-policies-global-settings-configure#how-do-you-know-these-procedures-worked) section:

> - Use the URL <http://spamlink.contoso.com> to test Safe Links protection. This URL is similar to the GTUBE text string for testing anti-spam solutions. This URL is not harmful, but it will trigger Safe Links protection.

OK?

**Comment by chrislehr** [comment]
Most excellent.  And works!

[cid:a4055892-c088-4696-ae08-c6e4efd63be2]

Thanks!!!!!
________________________________

**Comment by chrislehr** [comment]
Chris - the second part of the new section references how to check the block URLs, which is from the SafeLinks Global Settings in the UI, which is now deprecated.   The Pshell to access blockurls works, but to set there you would mislead - this should instead reference the TABL

Example:
[cid:27100f6c-cad6-468f-b058-2dbddc011326]

This should now reference:
Get-TenantAllowBlockListItems -ListType url

Chris
________________________________

**Comment by chrisda** [comment]
@chrislehr, you screenshot didn't come through, so I can't see what you're referencing.

The [Configure global settings for Safe Links in Microsoft Defender for Office 365](https://learn.microsoft.com/microsoft-365/security/office-365-security/safe-links-policies-global-settings-configure) article has this big note at the top:

> The **Global settings** menu and the **Block the following URLs** list for Safe Links are in the process of being deprecated. Use block entries for URLs in the [Tenant Allow/Block List](https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-urls-configure#use-the-microsoft-365-defender-portal-to-create-block-entries-for-urls-in-the-tenant-allowblock-list) instead.

So, when the **Global Settings** option goes away in the Microsoft 365 Defender portal everywhere (it's still visible to me in my plain M365 E5 tenant), that whole article will go away (likely redirected to the TABL URL article). The big note at the top is going to have to suffice for now.

**Comment by chrisda** [comment]
@chrislehr, all references to "Block the following URLs" for Safe Links in the Defender portal and in PowerShell were removed everywhere, first in the late May/early June timeframe, including the removal of the aforementioned "Configure global settings for Safe Links" article, which now redirects to URL entries in the Tenant Allow/Block List.

So, I'm closing this issue as complete.

Thanks for the feedback.
