### ISSUE TITLE
Is this expected behaviour? If an org adds your tenant ID for external shared channels you don't get asked for approval

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/microsoft-365-docs#11483]
Hi, I noticed during a test that the following is possible.

You can look up other org's IDs via something like https://www.whatismytenantid.com/ and if they haven't set their Teams policies correctly you could potentially invite their users to an external shared channel without an admin being aware. The user is aware because of the Teams notification it generates.

If another org adds your tenant ID for the purposes of using External Teams shared channels should someone in your org be notified or asked for approval i.e a global admin?

Thanks, Darrel

**Comment by denisebmsft** [comment]
Hi @Darrelo365. To which article does your feedback apply? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by Darrelo365** [comment]
Hi, this is the page I thought I'd contributed feedback to. Apologies if I've misunderstood. 

https://learn.microsoft.com/en-US/microsoft-365/solutions/collaborate-teams-direct-connect?WT.mc_id=TeamsAdminCenterCSH&view=o365-worldwide#enable-shared-channels-in-teams

**Comment by msbemba** [comment]
@Darrelo365 Thank you for your feedback. No, It does not ask for approval. But only an Admin can set the inbound and outbound settings in Azure AD for this to work.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Darrelo365 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
