### ISSUE TITLE
Could you review the hyperlink URLs?

### ISSUE THREAD

**Issue by KENJISHIRAKI** [MicrosoftDocs/microsoft-365-docs#11487]
[Enter feedback here]
Hello there,

The hyperlink "Configure Microsoft Defender for Endpoint and MS AutoUpdate (MAU) notifications" links to the following URL, but is this not correct?
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-updates?view=o365-worldwide

I want to check the settings related to notifications, but the XML presented in the link has nothing to do with notifications. The XML I saw was for MAU configuration.

I think the correct link is below.Therefore, could you please review the hyperlink?
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#notifications

Best regards,
Kenji Shiraki

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd66a255-36e5-29dc-7610-d50ef8bca3f3
* Version Independent ID: 17375473-bc07-f8e5-a85f-d732bbba3d71
* Content: [Intune-based deployment for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#overview)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-with-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-with-intune.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@KENJISHIRAKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11558

Once the author approves, the changes will be live.

Thanks
Sri
