### ISSUE TITLE
Redirect URI for Canvas Developer Key

### ISSUE THREAD

**Issue by ptart** [MicrosoftDocs/microsoft-365-docs#11484]
Where can I find the required Redirect URI for the OneDrive LTI in Canvas when creating the Developer Key?
Thanks,
Patrick Tart

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fee0615-eb33-e945-c1ee-efad095ead11
* Version Independent ID: 2a7089da-e35a-8f39-3df1-98ee29710cb6
* Content: [Integrate Microsoft OneDrive LTI with Canvas](https://learn.microsoft.com/en-us/microsoft-365/lti/onedrive-lti?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/lti/onedrive-lti.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lti/onedrive-lti.md)
* Service: **microsoft-365-business**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@ptart 

For the OneDrive/Canvas integration, you should only have to copy the JSON text from the Microsoft LTI registration portal and paste it to Canvas and copy the Client ID from Canvas and paste it the Microsoft LTI registration portal. There shouldn't be a need for the Redirect URI like some of the other LMS providers.

If you're seeing a different experience than indicated in the document, I'd suggest submitting a support ticket: https://learn.microsoft.com/en-us/microsoft-365/lti/manage-microsoft-one-lti?view=o365-worldwide#report-problems-with-lti-registration-portal.

**Comment by ptart** [comment]
Thanks for confirming. Copying/pasting the JSON to a different application added some extra spaces. I cleaned it up and everything‘s working as expected. Thanks for your help again! You can close this ticket.


Regards,

Patrick Tart

Technology Services

Wake County Public School System

________________________________
