### ISSUE TITLE
1.5 Properties:  ComplianceLevel doesn't match Examples

### ISSUE THREAD

**Issue by PaulFeaser** [MicrosoftDocs/microsoft-365-docs#11498]
In pulling down this data, the 'complianceLevel' field in section 1.5 Properties doesn't match 1.6 Examples where it has an 's' on the end.  I'm using the field complianceLevels with the 's' so hopefully you just update section 1.5.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fac6a9e-cd46-de91-7808-d2a7a2916e26
* Version Independent ID: 3fac6a9e-cd46-de91-7808-d2a7a2916e26
* Content: [Security baselines assessment configurations](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-security-baselines-assessment-configurations?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-security-baselines-assessment-configurations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-security-baselines-assessment-configurations.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@PaulFeaser Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11559

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by PaulFeaser** [comment]
@msbemba Thank you!
