### ISSUE TITLE
Clarifications required : cloud only user vs hybrid (synced from AD)

### ISSUE THREAD

**Issue by GitHubGuillaumeMS** [MicrosoftDocs/microsoft-365-docs#11490]
I was asked by a customer to provide best practices and guidance around how to remove an employee following a departure, and only this document appears to provide clear and defined steps to follow.  

After presenting the process, my entreprise customer remained under the impression the documentation was not applicable to his situation because of the and wording and different links & reference around _Small Business_ 

A document linked in the first step  (Prevent a former employee from logging in and block access to Microsoft 365 services) points to [the recommendations around revoking access in a hybrid environment](https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/users-revoke-access?source=recommendations#revoke-access-for-a-user-in-the-hybrid-environment), but I believe it could be beneficial to make a clearer and louder mention of the fact that the steps outlined apply to user in both cloud only and hybrid environments (and perhaps outline the particularities associated with each).

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by GitHubGuillaumeMS** [comment]
Hi Sri,

The first step 1 from the main doc (Step 1 - Prevent a former employee from logging in and block access to Microsoft 365 services) points to https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-1?view=o365-worldwide

In that referenced article, mention is made of the https://learn.microsoft.com/en-us/powershell/module/azuread/revoke-azureaduserallrefreshtoken article (see screenshot) and this is the only place where there are specific and defined steps for hybrid / cloud only. Marking that difference should be made clearer / louder.

Hope this helps clarify

________________________________

**Comment by GitHubGuillaumeMS** [comment]
The steps are not even detailed in the second article from my previous email, It's the suggested links at the end of the article that guide us to https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/users-revoke-access?source=recommendations#revoke-access-for-a-user-in-the-hybrid-environment in which steps are described for a hybrid environment.

Apology for the confusion, hope this makes things clearer.
________________________________

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@GitHubGuillaumeMS Got it. The recommended or suggested articles are based on AI and are usually articles that users follow after viewing this document. We would not be able to edit that. 

Hope this helps!

Thanks
Sri

**Comment by GitHubGuillaumeMS** [comment]
@msbemba : My coment was not about the suggested articles.  I was simply making mention because the documentation does not make any explictly state if the steps are only mean to be used in cloud only environment or if they are also valid for scenarios in which a customer synced their identities to AAD (hybrid)é

I was originally referring to [this article](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide ), in which steps are detailled to remove a former employee.

The steps appear to only be valid for cloud-only environments, while they should also be valid for hybrid environments. 

The purpose of my comment was to suggest including indications that the steps in the article apply to both types of environment, and perhaps link some of the articles that are specifically intended for customers that sync identities (hybrid).

Hope this makes things clearer.

Thanks !

**Comment by GitHubGuillaumeMS** [comment]
Hi @msbemba ,

Was any additional clarification required ?  

Thanks again for your assistance !

**Comment by msbemba** [comment]
@GitHubGuillaumeMS Thank you for the response. Step7 in this document does state that this is only for Cloud only environments and how to achieve this in case of a hybrid situation -https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-7?view=o365-worldwide#does-your-organization-use-active-directory

Hope this helps!

Thanks
Sri

**Comment by GitHubGuillaumeMS** [comment]
Hi @msbemba ,

Despite some implicit reference like the one you made mention of, nothing in the main indicates if these steps to remove a former employee (https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee) apply to cloud only or to hybrid environment.  Furthermore, the tip in the green box mentions "If you need help with the steps in this topic, consider [working with a Microsoft small business specialist](https://go.microsoft.com/fwlink/?linkid=2186871)" which creates further confusion to customers as this seems to suggest there would be other steps to follow in an entreprise context (as opposed to SMB only like this is suggesting).

My recommendation is to modify the article to make clear indications of the fact that the steps apply to both Cloud only & hybrid identities, and add direct & explicit references to documentation that only apply to one or the other.

Hope this is clearer.  Thanks !

**Comment by msbemba** [comment]
Thank you  @GitHubGuillaumeMS, I have made some changes including the steps of deleting account via AD. This can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11762

Once the author approves, the changes will be live.

Thanks
Sri
