### ISSUE TITLE
UI and Steps do not align with Current version

### ISSUE THREAD

**Issue by Cassia-Rob** [MicrosoftDocs/microsoft-365-docs#11504]
THe UI in the video and steps listed below it no longer macth up to what is seen in the application.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Cassia-Rob Thank you for your feedback. I see the documented UI in the application.

![image](https://user-images.githubusercontent.com/45987684/229432592-3a37fa4b-8c5f-4d7d-941c-099171b21dbc.png)

If there are different options shown, could you please provide us a snip?

Thanks
Sri

**Comment by Cassia-Rob** [comment]
In the video it says:
1. Click on the user
2. Click on the delete user
3. The page that is displayed show the same one you provide above.

However, when I follow the same steps in step 3 the page that is actually displayed is:

![image](https://user-images.githubusercontent.com/94903274/229534564-0ebf8aa9-34e9-4120-96d1-8ac8264c9194.png)

Which does not display the check boxes that your image (or the video) has.

Thanks!

Rob

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Cassia-Rob Thank you for your response and the screenshot. Looks like you are deleting an unlicensed user. If you try to remove a licensed user, you will be able to see the options that are described in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Cassia-Rob Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Cassia-Rob** [comment]
Thanks @msbemba  and @yogkumgit!

Cheers!

Rob
