### ISSUE TITLE
Information may not accurate in "Note"

### ISSUE THREAD

**Issue by Yorkwu1** [MicrosoftDocs/microsoft-365-docs#1150]
Based on the article: https://docs.microsoft.com/en-us/microsoft-365/compliance/records#using-retention-labels-to-declare-records, we can see the statement: "Declaring an item as a record using retention labels requires an Office 365 Enterprise E5 license or equivalent for each user who has permissions to edit content in this location. Users who have read-only access don't require a license.". 

However based on our test, they should be following behaviors:
        1. No matter users have or don't have E5/E3 licenses, if they have Edit permission, they can declare an item as a record.
        2. When users don't have edit permission (we test via read-only permission), no matter users have or don't have license, they are unable to declare an item as a record.

There are inconsistency between article and our practice.

**Comment by mypil** [comment]
@Yorkwu1 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by Yorkwu1** [comment]
Hi Joyce,

Would you please check the document listed below? I am a Microsoft support engineer. My customer mentioned a mistake in the document listed below.
https://docs.microsoft.com/en-us/microsoft-365/compliance/records#using-retention-labels-to-declare-records


York Wu
Support Engineer
AH-GC-CH- S+S Exchange
Customer Service and Support
Office: +862152637937
wuyue@microsoft.com<mailto:wuyue@microsoft.com>
[Microsoft]
﻿  TechLead | Steven Yu (stevenyu@microsoft.com<mailto:stevenyu@microsoft.com>)
  Team Manager | Kirin Xue (lin.xue@microsoft.com<mailto:lin.xue@microsoft.com>)
  If you have any feedback about my work, please let either me or my manager Kirin Xue know at lin.xue@microsoft.com<mailto:lin.xue@microsoft.com>

**Comment by Yorkwu1** [comment]
Add @ChoonHeng Lee<mailto:Choonheng.Lee@microsoft.com> into the mail thread.


York Wu
Support Engineer
AH-GC-CH- S+S Exchange
Customer Service and Support
Office: +862152637937
wuyue@microsoft.com<mailto:wuyue@microsoft.com>
[Microsoft]
﻿  TechLead | Steven Yu (stevenyu@microsoft.com<mailto:stevenyu@microsoft.com>)
  Team Manager | Kirin Xue (lin.xue@microsoft.com<mailto:lin.xue@microsoft.com>)
  If you have any feedback about my work, please let either me or my manager Kirin Xue know at lin.xue@microsoft.com<mailto:lin.xue@microsoft.com>

From: York Wu
Sent: Thursday, January 30, 2020 11:43 AM
To: MicrosoftDocs/microsoft-365-docs <reply@reply.github.com>; MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Information may not accurate in "Note" (#1150)

Hi Joyce,

Would you please check the document listed below? I am a Microsoft support engineer. My customer mentioned a mistake in the document listed below.
https://docs.microsoft.com/en-us/microsoft-365/compliance/records#using-retention-labels-to-declare-records


York Wu
Support Engineer
AH-GC-CH- S+S Exchange
Customer Service and Support
Office: +862152637937
wuyue@microsoft.com<mailto:wuyue@microsoft.com>
[Microsoft]
﻿  TechLead | Steven Yu (stevenyu@microsoft.com<mailto:stevenyu@microsoft.com>)
  Team Manager | Kirin Xue (lin.xue@microsoft.com<mailto:lin.xue@microsoft.com>)
  If you have any feedback about my work, please let either me or my manager Kirin Xue know at lin.xue@microsoft.com<mailto:lin.xue@microsoft.com>

**Comment by joinimran** [comment]
@Yorkwu1 Thanks for sharing this, I have gone through the document and feels like removing the note can surely be helpful in the document as this note is making contradicting statements. 

Additionally can you please confirm if the user has Microsoft 365 license and maybe that component is overwriting the Office365 restriction. 

Thanks.

**Comment by mypil** [comment]
@Yorkwu1 - Can you please respond to the query of joinimran?

Thank you.

**Comment by mypil** [comment]
@Yorkwu1 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
