### ISSUE TITLE
365 Retention Policy: unclear what happens after delete action in Exchange Online 

### ISSUE THREAD

**Issue by kevinblumenfeld** [MicrosoftDocs/microsoft-365-docs#1151]
The statement seems confusing: 

> If the item is not modified or deleted during the retention period,
> the same process runs periodically on all folders in the mailbox and
> identifies items whose retention period has expired, and these items
> are permanently deleted **within** 14 days of the end of the retention
> period.

Example scenario: 
 - User has 365 Retention Policy applied to their mailbox 
 - Retention Period: Keep content, and delete it if it's older than 2 years
 - The default of 14 days is found when running: Get-Mailbox | Select-Object RetainDeletedItemsFor

The day the user's 2-year-old data is deleted by the 365 Retention Policy, do they not have a full 14-days to recover those items from the Recoverable Items Folder?  Why is the word **within** used?  Would that not denote a window **between** the end of the retention period and 14 days?  

Would a better phrasing include 
"...delete **after** the 14 days?"

https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies

**Comment by chvukosw** [comment]
Thanks for bringing this to our attention. I am researching this with the PM and will verify. I believe it is correct, and that to prevent a permanent deletion one needs to select the option, at the time a retention label is created, to trigger a disposition review if they want the chance to recover. Will verify and if that is the case, will update the page to clarify .

**Comment by chvukosw** [comment]
Hello, I have confirmed with engineering that the language on the page is correct--content is deleted within 14 days, not at the end of 14 days. If a user wants to be able to review content before permanent deletion, they need to use retention labels, not apply a retention policy, so that they can set up a disposition review to review content before a final deletion. Clarifying language to this effect has been added to the top section of this page. Thank you.

**Comment by kevinblumenfeld** [comment]
Thank you @chvukosw  

May I ask, what process takes "up to 14 days" to delete said content?  

That to me is the ambiguous part of the documentation - specifically the "up to" part.  

Is the process the Managed Folder Assistant (MFA)? or is this referring to the Recoverable Items Retention found here

`Get-Mailbox user | Select RetainDeletedItems`

this defaults to 14 days but can be as long as 30 days. Or something else?

Thanks again!
Kevin
