### ISSUE TITLE
There is not an Integrated Apps under Settings in M365 Admin Center

### ISSUE THREAD

**Issue by greenchevy65** [MicrosoftDocs/microsoft-365-docs#11511]
We do not have an Integrated Apps option under Settings.  Add-ins is directly under Settings in the Microsoft 365 admin center.  This line on the page seems to be incorrect.

1. In the admin center, go to the Settings > Integrated apps > Add-ins page.

Thank you,
Dana White
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e62dfa25-e420-38e4-ff47-05cca62d14ec
* Version Independent ID: 5ea03ce0-38b9-e005-a430-e98442e2ec83
* Content: [Deploy add-ins in the admin center - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-deployment-of-add-ins.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@greenchevy65 Thank you for your feedback. I was able to find the option under settings in M365 admin center.

![image](https://user-images.githubusercontent.com/45987684/229433787-739328c4-f933-4452-9018-bca37e002539.png)


If you continue to have this problem, I'd recommend you open a support ticket via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @greenchevy65 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
