### ISSUE TITLE
Why we do not have Bookings or Virtual Appointments in the list

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/microsoft-365-docs#11525]
Why we do not have Bookings or Virtual Appointments in the list. Customers would like to know where is bookings 
data stored.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dipinn26592 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
