### ISSUE TITLE
conflicting articles

### ISSUE THREAD

**Issue by riohedfield** [MicrosoftDocs/microsoft-365-docs#11523]
Hello, 

In the following article: https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-create-a-litigation-hold?view=o365-worldwide#assign-an-exchange-online-plan-2-license

We have Litigation hold is supported in Office 365 A1 subscriptions

![image](https://user-images.githubusercontent.com/59142439/228848768-8300088d-771c-4883-9322-b677d230c9c8.png)

In the following article Office 365 A1 doesn't support Litigation Hold: 

https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#exchange-online-features

![image](https://user-images.githubusercontent.com/59142439/228849802-807b7fea-323d-47df-bf11-543f65ba645a.png)

1. Could you please adjust the article with the wrong info.
2. In addition does Office 365 A3 support litigation hold?

BR
Ribo

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7007724c-a3ad-9453-c637-4f6f7f7728fe
* Version Independent ID: 7007724c-a3ad-9453-c637-4f6f7f7728fe
* Content: [Create a Litigation hold - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-create-a-litigation-hold?view=o365-worldwide#assign-an-exchange-online-plan-2-license)
* Content Source: [microsoft-365/compliance/ediscovery-create-a-litigation-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-create-a-litigation-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@riohedfield Thank you for your feedback. Yes, Litigation hold is available in O365 A1 and A3. I'll work with the author to fix 
https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#exchange-online-features

Thanks
Sri

**Comment by riohedfield** [comment]
Thanks @msbemba
