### ISSUE TITLE
Password Expiration Policy Configuration through MS365 Admin Center vs PowerShell

### ISSUE THREAD

**Issue by Shaleed** [MicrosoftDocs/microsoft-365-docs#11524]
Hello, I've tried the following case that includes the one in this issue. The result is not what I expected from what msbemba said in another issued related to the same check.

1. Original situation:
   a. “Set passwords to never expire” enabled (by default)

2. What I changed:
   a. I disabled the “Set passwords to never expire” flag (to set the expiration to 90 days for all users);
   b. I set no expiration password through PowerShell to only 5 users (PasswordNeverExpires = True).
   c. Using the Get-AzureADUser command to get all users and related Password Expiration Policy status correctly gives all "PasswordNeverExpires = false" except for those 5 users.

3. What I tested:
   a. After all this is turned back on the “Set passwords to never expire” flag;
   b. And then I used the Get-AzureADUser command to get all users and related Password Expiration Policy status;
   c. The result was the same as step 2c.

I expected all PasswordNeverExpires to be set to true instead. So how does this work?

**Comment by denisebmsft** [comment]
Hello @Shaleed. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by Shaleed** [comment]
Hello, this is the Version Independent ID: "a139620d-3330-a687-709a-35bb270101e4" 

Thank you so much!

**Comment by msbemba** [comment]
@Shaleed Thank you for your feedback. This sounds like a bug to me and needs to be reported to the Product group. I'd recommend you create a support ticket via the need help section on the admin center and share the results with the Engineer so that this can be escalated and fixed. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Shaleed Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
