### ISSUE TITLE
How long does Analytics take?

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/microsoft-365-docs#11526]
The compliance.microsoft.com has a note it takes 24 hours to start seeing data, but this article says 48 hours.  Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Get started with insider risk management settings - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide#analytics)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@cablechewer Thank you for your feedback. It usually takes 24 -48 hours to start seeing the data. We wanted to document the maximum amount of time it takes to show up the data.

Hope this helps!

Thanks
Sri
