### ISSUE TITLE
Documentation For Each License Entitlement

### ISSUE THREAD

**Issue by haydanbarry** [MicrosoftDocs/microsoft-365-docs#1152]
With Microsoft EMS plans, it seems the latest documentation now caters specifically to E5/ATP users. There is very little documentation that highlights the options available to E3 users. The documentation needs to be outlined to specifically show which features and options are available to each license respectively. Essentially this document says that E3 users don't have any options to tune anti-Phishing policy other than turn it off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e78b5a4-f24e-7830-489b-89b86aa7e53c
* Version Independent ID: 2ee17e64-35cb-3994-8cee-959009bce720
* Content: [Tune anti-phishing protection in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tuning-anti-phishing#feedback)
* Content Source: [microsoft-365/security/office-365-security/tuning-anti-phishing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tuning-anti-phishing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by joinimran** [comment]
@haydanbarry - Thank you for your feedback. Specific to this document these features are controlled by ATP which is by default part of E5 license. Please see more details at https://www.microsoft.com/en-us/licensing/product-licensing/microsoft-365-enterprise

Thanks.

**Comment by mypil** [comment]
@haydanbarry - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by joinimran so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
