### ISSUE TITLE
link broken to "how to connect to exchange online"

### ISSUE THREAD

**Issue by LouisMastelinck** [MicrosoftDocs/microsoft-365-docs#11528]
The url in this part [https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/mdo-support-teams-about?view=o365-worldwide#enable-microsoft-defender-for-teams

"After you [**connect to Exchange Online PowerShell]**(https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell.md), run the following command to join the Teams preview:"

Is not a valid url. 
Could be this url: https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba876c7-24a2-a4b0-1b50-af42d33b00f1
* Version Independent ID: 2ba876c7-24a2-a4b0-1b50-af42d33b00f1
* Content: [Microsoft Defender for Office 365 support for Microsoft Teams (Preview) - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/mdo-support-teams-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/mdo-support-teams-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mdo-support-teams-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@LouisMastelinck Thank you for your feedback. The link has been fixed and we are able to access the link via https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LouisMastelinck Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by v-ratulach** [comment]
Updated topic with correct link.
