### ISSUE TITLE
Disabling Tamper Protection doesn't work on Windows Server 2019

### ISSUE THREAD

**Issue by az-mikhail** [MicrosoftDocs/microsoft-365-docs#11530]
It seems that disabling the Tamper Protection setting doesn't work with SCCM 2207 and Defender for Endpoint on Windows Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c747a2e-85ad-103f-02de-a52879aefd89
* Version Independent ID: 2c747a2e-85ad-103f-02de-a52879aefd89
* Content: [Manage tamper protection using tenant attach with Configuration Manager, version 2006](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-tamper-protection-configuration-manager?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-tamper-protection-configuration-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-tamper-protection-configuration-manager.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by az-mikhail** [comment]
Hello @denisebmsft ,
Thank you for your reply. 
We managed to enable the Tamper protection using Intune policy but now when we are trying to disable it using the same policy it doesn't work.

Regarding the note, does that mean that if I enable the Tamper protection I won't be able to change the tamper-protected settings even using Intune/SCCM?

**Comment by denisebmsft** [comment]
Hi again @az-mikhail. Please open a support ticket on this. It's the fastest way to raise awareness to your issue, and it'll help our teams sort out whether there's a software issue or if the docs need to be updated. Thank you, and please let me know how it goes.
