### ISSUE TITLE
Out-of-date instructions using Classic Exchange admin center

### ISSUE THREAD

**Issue by mjf-ans** [MicrosoftDocs/microsoft-365-docs#11538]
"Step 4: Unblock the existing email server (optional)" has instructions to use the Exchange admin center, but the section being used (Protection > Connection filter) was on the Classic Exchange admin center, and has now moved to Microsoft 365 Defender.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 738692b6-47ec-2a49-e576-bb6ff0cd3471
* Version Independent ID: c9d7a0ad-2db4-dda1-6021-831e5bb38098
* Content: [Pilot Microsoft 365 from my custom domain - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/pilot-microsoft-365-from-my-custom-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/pilot-microsoft-365-from-my-custom-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/pilot-microsoft-365-from-my-custom-domain.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by msbemba** [comment]
@mjf-ans Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11569

Once the author approves, the changes will be live.

Thanks
Sri
