### ISSUE TITLE
Clarification on where in Exchange Online are pronouns stored?

### ISSUE THREAD

**Issue by IADflyer** [MicrosoftDocs/microsoft-365-docs#11536]
This article mentions that pronouns are stored in Exchange Online, but does not mention where in Exchange Online they are stored.  For example, is it an attribute that can be viewed with the Get-Mailbox Exchange Online cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9673b777-a479-8c08-88cf-50c1dfea76cd
* Version Independent ID: 9673b777-a479-8c08-88cf-50c1dfea76cd
* Content: [Turn pronouns on or off for your organization in the Microsoft 365 admin center - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/turn-pronouns-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/turn-pronouns-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/turn-pronouns-on-or-off.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@IADflyer Thank you for your feedback. Currently, the details are not visible via any cmdlet. However, they are stored in the exchange mailbox and the details are hidden. I'd recommend you post this feedback on our main feedback portal(https://feedbackportal.microsoft.com/ ) so that our dev or product engineers can help you with more details.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@IADflyer Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
