### ISSUE TITLE
Just a typo, Heaver instead of Header.

### ISSUE THREAD

**Issue by LuxsonicAdmin** [MicrosoftDocs/microsoft-365-docs#11545]
In the section on using Mail Flow Rules, in point 4-b:
"
Modify the message properties > set a message header:

    Header name: For example, X-ETR.
    **Heaver** value: For example, Bypass spam filtering for authenticated sender 'contoso.com'.
"
Heaver should be Header.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@LuxsonicAdmin, fixed.

In the future, you too can make updates like this yourself without opening a GitHub issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
