### ISSUE TITLE
Server OS in Lab are expired

### ISSUE THREAD

**Issue by MrMozbe** [MicrosoftDocs/microsoft-365-docs#11551]
The Evaluation versions of the servers OS in labs are all expired in when Windows 10 lab

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @cdmm12
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@MrMozbe Thank you for your feedback. We will test and update the document shortly.

Thanks
Sri
