### ISSUE TITLE
Security 

### ISSUE THREAD

**Issue by tkms212** [MicrosoftDocs/microsoft-365-docs#1155]
Many customer cares how to protect raw data. Could you please add the description how to encrypt data and protect data?

Ex: EDM only upload hashed data so customer doesn't need to upload sensitive information to Microsoft Cloud. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification#feedback)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @tkms212 - I'll contact you internally to get more details on this issue.
