### ISSUE TITLE
ATP audited activities

### ISSUE THREAD

**Issue by inmamede** [MicrosoftDocs/microsoft-365-docs#1156]
Hello, I noticed we include Advanced Threat Protection and Threat Intelligence as one of the services that is audited in O365. Indeed I do see some audit logs for malware detected by ATP safe attachments, for example. Would it be possible to reference in this doc which are the activities audited for ATP or is this information already referenced elsewhere? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#audited-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@inmamede Thanks for the inquiry. You can find more information Advanced Threat Protection and Threat Intelligence auditing events in the topic about the Office 365 Management Activity API schema: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#office-365-advanced-threat-protection-and-threat-investigation-and-response-schema
