### ISSUE TITLE
add -IncludeSoftDeletedRecipients in the line 33 of the script.

### ISSUE THREAD

**Issue by mhunecke** [MicrosoftDocs/microsoft-365-docs#11566]
[Enter feedback here]

How about to add the parameter "-IncludeSoftDeletedRecipients" on the script.
So our customer will be able to search also on the deleted users.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 136c161f-13b8-fb62-01de-53b1219b5290
* Version Independent ID: f1843c14-29da-d831-c7ce-9e3f624a01ed
* Content: [Use Content search for targeted collections - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/use-content-search-for-targeted-collections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-content-search-for-targeted-collections.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@mhunecke Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11572

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@mhunecke Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
