### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by davecober** [MicrosoftDocs/microsoft-365-docs#1157]
On this page it says:

"Do you have Microsoft 365 E5 or Microsoft 365 E3 together with Identity & Threat Protection? Consider trying Microsoft Threat Protection."

But on the MTP prerequisites page it says:

"Microsoft 365 security requires one of the following licenses:

Microsoft 365 E5
Office 365 E5, Enterprise Mobility + Security E5, and Windows E5"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a177ba2-5cff-b0a0-6afa-717689db2884
* Version Independent ID: 802f6c49-9a14-e76f-6cf3-67862b40f18d
* Content: [Office 365 Advanced Threat Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp#feedback)
* Content Source: [microsoft-365/security/office-365-security/office-365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello, Microsoft 365 E3 + Identity & Threat Protection licenses are enough to use MTP. Source: [Introducing new advanced security and compliance offerings for Microsoft 365](https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/02/introducing-new-advanced-security-and-compliance-offerings-for-microsoft-365/)
Looks like Microsoft Threat Protection prerequisites page is outdated.
Thank you

**Comment by denisebmsft** [comment]
Greetings! Thank you for catching this. The article has been updated and changes will render live shortly.
