### ISSUE TITLE
Turning off Per-user MFA before enabling CAP

### ISSUE THREAD

**Issue by larasawalha90** [MicrosoftDocs/microsoft-365-docs#11581]
Hello, 

We have some concern regarding the note add which request to turn off both Per-user MFA and security defaults before you enable conditional access policy
![image](https://user-images.githubusercontent.com/110615808/230028256-feba3c03-b16b-4f79-9758-195f3312eb67.png)

We understand that a customer should not be using both Per-user MFA and conditional access policy that requires MFA at the same time since this will cause a conflict and will contradict with the purpose of using CAP. However, we need to understand why Per-user MFA should be turned off before enabling CAP since some customer are concerned that if Per-user MFA has been disabled before enabling CAP there will be a short gap that will allow users to sign-in without MFA prompt which will raise security risks

Our request is either to remove "Per-user MFA" from the note or add more clarification to the customer so they understand why and what is expected if Per-user MFA was still enabled when CAP is enabled and what risks will this impose 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multifactor authentication for users - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#use-conditional-access-policies)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by larasawalha90** [comment]
Thank you @msbemba for the explanation.

Is it possible to add a note on the conflict for Per-user MFA with conditional access and why we recommend turning it off to give more clarity to customers?

Or maybe add a reference for the Per-user MFA article so customers can click on the URL and understand more about Per-user MFA? Like this article https://learn.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-userstates

**Comment by larasawalha90** [comment]
Hello @msbemba, please find the below suggestions.

**ORIGINAL**

Turn off both per-user MFA and Security defaults before you enable Conditional Access policies.

**SUGGESTED CHANGE**

Do not forget to disable per-user MFA after you have enabled Conditional Access policies. This is important as it will result in inconsistent user experience.
-------------------------------------------------------------------
In reality, we require customers to disable Security Defaults before enabling conditional access policies. However, we are not blocking the customer from using CAP if they have per user MFA enabled.  

Therefore, we can point out the importance of disabling this, but it is not a requirement to allow the configuration of CAP.  I believe if we add it this way, we are eliminating the small window (when the users will not be required to perform MFA) when the org will migrate the users from per-user MFA to CAP

**Comment by yogkumgit** [comment]
@msbemba Please update.

**Comment by larasawalha90** [comment]
@msbemba Thank you very much :)
