### ISSUE TITLE
Security baselines assessment doc need new note

### ISSUE THREAD

**Issue by PiotrWadolowski** [MicrosoftDocs/microsoft-365-docs#11584]
on Security baselines assessment (https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/tvm-security-baselines?view=o365-worldwide)

we're missing important note information on public docs.. We have this documented internally but it looks like it was missed on public ones. 

"The benchmark currently only supports GPO configurations and not MEM (Intune)"

discussed on PG/EEE/EE weekly meeting and agreed that it would be good to add this.

**Comment by msbemba** [comment]
@PiotrWadolowski Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11644

Once the author approves, the changes will be live.

Thanks
Sri
