### ISSUE TITLE
When was the reference to the "Decide whether to test or run your policy" page added to this article? 

### ISSUE THREAD

**Issue by tgrahampen** [MicrosoftDocs/microsoft-365-docs#11586]
I'm trying to do some sleuthing to figure out when the actual page was added to the Purview UI. The addition of that page to the UI broke our existing auto-apply policies. They stopped working. New auto-apply policies with same exact config work, but the old ones don't. 

Maybe if I find out exactly when this article was updated with that bit of information and pass that date along to Microsoft Support (as an update to an existing ticket regarding the broken policies), maybe then they can tell me when the UI was changed and whether the new change was announced. 

https://learn.microsoft.com/en-us/microsoft-365/compliance/auto-apply-retention-labels-scenario?view=o365-worldwide

**Comment by msbemba** [comment]
@tgrahampen Thank you for your feedback. The change was announced on Mar 23, 2023.

Hope this helps you fix the issue with support.

Thanks
Sri

**Comment by tgrahampen** [comment]
Thanks, Sri! Do you know what Microsoft service I can sign up for that would notify me regarding upcoming changes to the Purview UI? Is service health the only portal for that?

Tyler Graham
Corporate Records Analyst
Penumbra, Inc. • One Penumbra Place, Alameda, CA 94502
📞+1 510-995-9703 • ***@***.******@***.***> • www.penumbrainc.com<http://www.penumbrainc.com/>

From: Sriraman M S ***@***.***>
Sent: Tuesday, April 11, 2023 11:08 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Tyler Graham ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [MicrosoftDocs/microsoft-365-docs] When was the reference to the "Decide whether to test or run your policy" page added to this article? (Issue #11586)

CAUTION: This email originated from outside of Penumbra. Do not click links, open attachments or forward unless you recognize the sender and know the content is safe.


@tgrahampen<https://github.com/tgrahampen> Thank you for your feedback. The change was announced on Mar 23, 2023.

Hope this helps you fix the issue with support.

Thanks
Sri

**Comment by msbemba** [comment]
@tgrahampen That is correct. Currently, it is available in the service health and message center (Under Health in M365 admin center)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tgrahampen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
