### ISSUE TITLE
Get-TeamsSecurityPreview not available.

### ISSUE THREAD

**Issue by sholland-bamboohealth** [MicrosoftDocs/microsoft-365-docs#11587]
I'm connecting with and admin account using connect-Exchangeonline using exchangeonlinemanagement version 3.1.0
but the Get-TeamsSecurityPreview is not recognized as the name of a cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba876c7-24a2-a4b0-1b50-af42d33b00f1
* Version Independent ID: 2ba876c7-24a2-a4b0-1b50-af42d33b00f1
* Content: [Microsoft Defender for Office 365 support for Microsoft Teams (Preview) - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/mdo-support-teams-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/mdo-support-teams-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mdo-support-teams-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by v-ratulach** [comment]
Looking into this.

**Comment by v-ratulach** [comment]
@sholland-bamboohealth - Can you please share the tenant ID?

**Comment by sholland-bamboohealth** [comment]
turns out it was a problem with the powershell module.

**Comment by sholland-bamboohealth** [comment]
turns out it was a problem with the powershell module.
