### ISSUE TITLE
Error Running in Cross Tenant Migration Script

### ISSUE THREAD

**Issue by Nishit92inn** [MicrosoftDocs/microsoft-365-docs#11588]
When Running either script the following error is displayed, is there a prerequisite that was missed as neither the New-OrganizationRelationship or the Set-OrganizationRelationship commands appear to have this parameter. If I edit and replace with MailboxMoveDirection then a similar error relating to the OAuthApplicationId parameter is shown on the Resource side.

A parameter cannot be found that matches parameter name 'MailboxMoveCapability'.
+ CategoryInfo : InvalidArgument: (:) [New-OrganizationRelationship], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,New-OrganizationRelationship
+ PSComputerName : outlook.office365.com

**Comment by msbemba** [comment]
@Nishit92inn Thank you for your feedback. I was able to test and it works. It is available only in the cloud-based service. If you still have an issue, I'd recommend you contacting support via the need help section so that they can fix or raise a bug.

https://learn.microsoft.com/en-us/powershell/module/exchange/new-organizationrelationship?view=exchange-ps

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Nishit92inn Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Nishit92inn** [comment]
Hello Thank You everyone for quick help, i have raised a ticket with Support.
