### ISSUE TITLE
Set-PolicyConfig -InformationBarrierMode 'MultiSegment' - Unrecognized mode

### ISSUE THREAD

**Issue by Purple-Tentacle** [MicrosoftDocs/microsoft-365-docs#11597]
I have a completely new demo tenant, Information barriers are not configured.
InformationBarrierMode is SingleSegment.

I am running this command to enable multi-segment mode:

`Set-PolicyConfig -InformationBarrierMode 'MultiSegment'`

But I receive this error:

`
Information Barrier config is not updated successfully. Error: {"error":{"code":"40005","message":"Unrecognized mode, source mode and 
destination mode should be 'Single' or 'MultiAllow'"}}.
    + CategoryInfo          : NotSpecified: (:) [Set-PolicyConfig], IBConfigUpdateFailureException
    + FullyQualifiedErrorId : [Server=MW2NAM10WS013,RequestId=4ec525ad-3294-4163-ae0c-c603cd2fbb68,TimeStamp=06.04.2023 08:50:11] [Failu 
   reCategory=Cmdlet-IBConfigUpdateFailureException] DF42E1F2,Microsoft.Office.CompliancePolicy.Tasks.SetPolicyConfig
    + PSComputerName        : nam10b.ps.compliance.protection.outlook.com
`

I already installed the preview 2 of ExchangeOnlineManagement  3.2.0.

Are there additional steps necessary, which are not documented yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de406555-1a6d-896b-ff10-f873f96c36aa
* Version Independent ID: de406555-1a6d-896b-ff10-f873f96c36aa
* Content: [Use multi-segment support in information barriers - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/information-barriers-multi-segment?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers-multi-segment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-multi-segment.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by DLPTest-rt** [comment]
any updates on this. I am also getting the same error.

**Comment by Purple-Tentacle** [comment]
> any updates on this. I am also getting the same error.

Not from me, unfortunately.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Purple-Tentacle Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Purple-Tentacle** [comment]
According to Microsoft support you should run

Connect-IPPSSession
connect-exchangeonline
Get-OrganizationConfig | FL *information*

and NOT Get-PolicyConfig.

Get-OrganizationConfig | FL *information* shows Legacy, which explains the error I am receiving.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Purple-Tentacle Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11975

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@Purple-Tentacle Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
