### ISSUE TITLE
Change Cloud Protection to High as for best practise 

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/microsoft-365-docs#11599]
Hello, here is advised  to set the value to not configured: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide#cloud-delivered-protection

here is advised to set the value to high:

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-block-at-first-sight-microsoft-defender-antivirus?view=o365-worldwide#create-a-device-configuration-profile

In my opinion this document should be updated to advise to set high

here again the advice is to set to high https://learn.microsoft.com/en-us/mem/intune/protect/security-baseline-settings-defender-atp?pivots=atp-december-2020

We should make consistence advice when we come to security . Thanks

**Comment by denisebmsft** [comment]
Hello @dbona75. Great catch! Thank you so much for your helpful feedback. I have updated the article and you'll see the revised version live later today (at around 4 p.m. Pacific Time). Thank you for helping us to improve our documentation!
