### ISSUE TITLE
Link to Schema is Incorrect

### ISSUE THREAD

**Issue by mitchsilberstein** [MicrosoftDocs/microsoft-365-docs#11598]
Under step 2 with the link labeled "MDE Preferences schema" is goes to "https://github.com/microsoft/mdatp-xplat/blob/master/macOS/schema/schema.json".

The correct URL should be "https://github.com/microsoft/mdatp-xplat/blob/master/macos/schema/schema.json". It does not like the capital letters for OS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12b60492-956e-9681-f3b6-cc8731f4eb59
* Version Independent ID: 1c3e9a4d-10d6-cceb-807e-2bb0a99d73c2
* Content: [Deploy and manage device control using JAMF](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-device-control-jamf?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-device-control-jamf.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-device-control-jamf.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@mitchsilberstein Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11645

Once the author approves, the changes will be live.

Thanks
Sri
