### ISSUE TITLE
Guidance around Chain of Custody does not work for Office documents?

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#11600]
Upon trying the steps / guidance provided in the **Validating migrated records** section for supporting Chain of Custody requirements, we're observing that certain office file formats (such as docx, xlsx, pptx, etc.) result in mismatched values between source and target.

We're migrating files from SharePoint 2013 to SharePoint Online using a 3rd party migration tool. We've used the QuickXORHash and Base64 code snippets as per the references in the article, and are retrieving the `vti_writevalidationtoken` value of the destination files through CSOM. 

For Office formats as described above, the base64-encoded QuickXORHash of the original Office files from SharePoint 2013 does not match the `vti_writevalidationtoken` values of these files once migrated to SPO.

Hoping to get some clarification around what 'records' means in the context of this article? Is it specifically referring to a 'declared record file' that might reside for instance within a Record Center site in SharePoint 2013 (e.g., if using the out-of-place legacy records management solution from SharePoint Server on-premises), or is it a conceptual reference to anything that an organization might consider as being a record?

We've assumed it's the latter - in which case, perhaps we may be missing some steps in our implementation, or have configured something incorrectly.  Is there any additional guidance available around establishing chain of custody during migration for Office documents?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Records management for documents and emails in Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide#validating-migrated-records)
* Content Source: [microsoft-365/compliance/records-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records-management.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@kstat   Thank you for flagging this, currently investigating.  And yes, records in this context means items that your organization needs to manage as records rather than any specific technical implementation.

**Comment by cabailey** [comment]
@kstat  Docs are updated to clarify what we mean by "records" but for this procedure not working for you, I've been advised this needs a support ticket to the SharePoint team (they own the property, not the Records Management team) for investigation.

**Comment by kstat** [comment]
Appreciate the update - thank you @cabailey.
