### ISSUE TITLE
Incorrect configuration guidance for guest/external users CA policy

### ISSUE THREAD

**Issue by nathanmcnulty** [MicrosoftDocs/microsoft-365-docs#11601]
The directions in the table to Require MFA always for guests and external users is incorrect:

Create this new policy and configure:
For Assignments > Users and groups > Include, choose Select users and groups, and then select All guest and external users.
For Assignments > Conditions > Sign-in, leave all options unchecked to always enforce multi-factor authentication (MFA).

First, there is no Conditions > Sign-in, it should be Conditions > Sign-in risk.
Second, I believe we need to select all risk levels.

As you can see below, you can't save if we leave all options unchecked ;)

![image](https://user-images.githubusercontent.com/6653432/230448962-e631ccb1-cdb2-4e90-8964-8ad684bed7f1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4806dd-a0d0-966c-8130-e752676090a5
* Version Independent ID: 6403c614-26bc-f037-262a-1ec33fc7d385
* Content: [Identity and device access policies for allowing guest and external user B2B access - Microsoft 365 for enterprise - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/identity-access-policies-guest-access?view=o365-worldwide#updating-the-common-policies-to-allow-and-protect-guests-and-external-user-access)
* Content Source: [microsoft-365/security/office-365-security/identity-access-policies-guest-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/identity-access-policies-guest-access.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by nathanmcnulty** [comment]
Hey @msbemba, I saw the edits go live. Thanks for fixing the "Sign-in risk" part, but do be aware that the docs are still incorrect. We can't save the policy unless we select an option. If we want it to apply every time, we must select all options. I tried to give a heads up on the PR: https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11647#issuecomment-1503970342

**Comment by msbemba** [comment]
@nathanmcnulty The edits have not gone live as the author has not reviewed them yet. I have made some slight changes which is up for authors review.

Thanks
Sri

**Comment by nathanmcnulty** [comment]
@msbemba Thanks Sri, I see the latest updates, and it looks better. We still need to specify to select ALL of the checkboxes to enforce MFA on every sign-in. That was the stated goal of the document. If it helps, I can wait until all changes are live and do a PR :)
