### ISSUE TITLE
Support for GCC customers?

### ISSUE THREAD

**Issue by JeffMichelmore** [MicrosoftDocs/microsoft-365-docs#11604]
Is this table supported in GCC environments? If not, can this document be updated to reflect that please? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0096bb8f-89d1-f968-4f1e-19e82b162ca5
* Version Independent ID: 0096bb8f-89d1-f968-4f1e-19e82b162ca5
* Content: [UrlClickEvents table in the advanced hunting schema](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-urlclickevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-urlclickevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-urlclickevents-table.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
That info is here: https://learn.microsoft.com/en-us/microsoft-365/security/defender/supported-event-types?view=o365-worldwide

**Comment by msbemba** [comment]
@JeffMichelmore Thank you for your feedback. As @schmurky mentioned UrlClickEvents is currently in public preview for Microsoft 365 Commercial customers and not available yet for GCC, GCC High or DoD.

We have added this information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11646

Once the author approves, the changes will be live.

Thanks
Sri
