### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by AlexVernon** [MicrosoftDocs/microsoft-365-docs#11614]
The following link reports a 404 error.

[Sensitivity labels for Teams meetings](https://support.microsoft.com/office/sensitivity-labels-for-teams-meetings-abd9f361-6a18-4256-ae46-5d429bc16ba6)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb0e73fa-705d-d5bb-07e5-39253e04a0ea
* Version Independent ID: 3c43a2e7-fcfd-cdae-fd18-f87de6eb7945
* Content: [Get started with sensitivity labels - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/get-started-with-sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/get-started-with-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-with-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@AlexVernon Thank you for your feedback. I can see it is working now.

https://support.microsoft.com/en-us/office/sensitivity-labels-for-teams-meetings-2b244d1d-72d0-471e-8e58-c41079e190fb

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AlexVernon Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
