### ISSUE TITLE
Automate self-healing with Microsoft 365 Defender Training link broken

### ISSUE THREAD

**Issue by teerich** [MicrosoftDocs/microsoft-365-docs#11617]
Automate self-healing with Microsoft 365 Defender Training link at the bottom of the article broken. It just reloads the page. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a03b3bdc-3b33-d1cb-cfd7-45c36f0b45a5
* Version Independent ID: a0a76115-7b17-d197-c3e4-d8e506d0ea96
* Content: [Automated investigation and response in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/m365d-autoir?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/m365d-autoir.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/m365d-autoir.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @teerich and thank you so much for letting us know about this issue. I've updated the article accordingly. Thank you for helping us improve the quality of our documentation. 

https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11628
