### ISSUE TITLE
Clarify audit defaults for M365 Business

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/microsoft-365-docs#11619]
It says "Audit logging is turned on by default for Microsoft 365 and Office 365 enterprise organizations"
Does this means orgs with M365 Business Basic/Standard/Premium don't have it enabled by default?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn auditing on or off - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-enable-disable?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-enable-disable.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-enable-disable.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by JMCA2** [comment]
It should also be clarified on https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-standard-setup?view=o365-worldwide where it says "Audit (Standard) is enabled by default for most Microsoft 365 and Office 365 organizations"

**Comment by msbemba** [comment]
@JMCA2 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11642

It is enabled by default for all organizations.

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@JMCA2 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
