### ISSUE TITLE
Clarify eDiscovery (Standard) licensing for M365 Business Premium

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/microsoft-365-docs#11626]
On this page it says "To access eDiscovery (Standard) in the Microsoft Purview compliance portal and use the hold and export features, your organization must have an Exchange online Plan 2 or Microsoft 365 E3 or Office 365 E3 subscription or higher. Microsoft 365 Frontline organizations must have an F5 subscription."

However, on https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-ediscovery it lists Microsoft 365 Business Premium as a valid license.

Also, on this link above it says "Exchange Only" but I have tested myself on a Business Premium tenant that search in SharePoint and Teams are also available for eDiscovery Standard cases.

@pamelaar
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1a79bc-c504-7b0d-2a76-b1151fdd2ec2
* Version Independent ID: 1d1a79bc-c504-7b0d-2a76-b1151fdd2ec2
* Content: [Get started with eDiscovery (Standard) cases in Microsoft Purview - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-standard-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-standard-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-standard-get-started.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@JMCA2 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
