### ISSUE TITLE
How to quickly test the built-in information types?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#1162]
For some reason, only the first 100 default information types enumerate in the UI. This means we cannot easily test information types like "IP Address", etc. What is the recommended way to test these? I understand we can get the XML using  Get-DlpSensitiveInformationTypeRulePackage and extract the regex manually, but is this the only approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb7953e-5257-2578-4607-2d93940d6845
* Version Independent ID: 8e59d041-619e-d54f-f28e-faac2bc18ef2
* Content: [Create a custom sensitive information type in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type#test-custom-sensitive-information-types-in-the-security--compliance-center)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@mypil - This should go to support.

**Comment by chrfox** [comment]
Hi @Mike-Crowley 
I think the best way forward is if you can open a [service ticket ](https://docs.microsoft.com/office365/admin/contact-support-for-business-products) in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
