### ISSUE TITLE
I have been having issues with my PC for three days. I need help. Microsoft/Lenovo instructed me to lock down my PC and wait for an Email to start it back up. I have yet to get an email. I can't work or study without the use of my computer. Will you please fix it. It's stuck in Safe Mode but won't connect to Internet. I have sent several tickets to Microsoft attempting to fix issues. I'm available to fix today. 

### ISSUE THREAD

**Issue by Silvrbckw** [MicrosoftDocs/microsoft-365-docs#11620]

**Comment by NoahTheTechNerd** [comment]
Hi there Silvrbckw, please contact Microsoft directly to get your issue fixed.

I hope this helped :)

**Comment by yogkumgit** [comment]
@Silvrbckw Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
