### ISSUE TITLE
Missing license information for mailbox archival instructions

### ISSUE THREAD

**Issue by bandtank** [MicrosoftDocs/microsoft-365-docs#11638]
This page does not specify which license is needed to enable archiving. In my tenant, I do not see the option for any of my users. Licenses are either Microsoft Business Standard or Office 365 E3. If an E5 license is required, that needs to be stated somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes for Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
At the top of the page, and every other page for managing mailboxes, is a link to our authoritative licensing statements.  If the information you are looking for isn't there, please leave a GitHub Issue for that page so the relevant people can see it and take action on it.

You'll find the licensing info for mailbox archiving by searching on that page for "archiving" but here's a direct link to the section: https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#email-archiving
