### ISSUE TITLE
Why are functions used sometimes and regex other times?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#1163]
Why is SSN a function and not regex? This is a simple regex, isn't it? What is the reason some things are regex patterns and not functions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ebaf450-d84e-c333-125c-b0e6d4662bad
* Version Independent ID: efcb8b51-f2fe-765b-221d-75890b4a2d64
* Content: [What the DLP functions look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-dlp-functions-look-for)
* Content Source: [microsoft-365/compliance/what-the-dlp-functions-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-dlp-functions-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @Mike-Crowley  - 
Thank you for your question, since this pertains to how the product is coded, I think that the best way to get closure on this issue would be to post on [Office365.uservoice.com](https://office365.uservoice.com/forums/289138-office-365-security-compliance).
