### ISSUE TITLE
Out of date instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#11631]
the instructions don't accurately describe recent changes to the M365 Defender portal, please update the images and text

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55901976-4431-c470-88cb-af7430bb7339
* Version Independent ID: 0e80c507-335d-bd5e-7315-b8fe30aec0ff
* Content: [Grant access to managed security service provider (MSSP)](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/grant-mssp-access?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/grant-mssp-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/grant-mssp-access.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Will update
