### ISSUE TITLE
Should Remove be "Stop scoring activity for users"?

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/microsoft-365-docs#11639]
The article states in Step 3 "Select Remove users" however there is no such option presented on the page. What is present is a little garbage can with the text "Stop Scoring activity for Users".  My assumption is that this is the Remove option, but that the text does not say Remove.

My customer has found this confusing, and refused to use the Stop button until we document whether it is really the remove function.  If they are the same, we need to update either this article or the GUI on compliance.microsoft.com.

Prior to this I had given the customer another method of removing people in bulk from policies.  That method was to create a CSV file that could be imported by the HR connector.  In that file state the LastWorkingDate as being in the past.  I believe that should accomplish the goal as well.  I don't know if it would be appropriate to document that in this article.

Thanks

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 937c3899-9a77-3dd5-81d3-bb407cfd887b
* Version Independent ID: 592ca560-8133-7c4f-b4c7-09df187d5b38
* Content: [Manage the workflow with the insider risk management users dashboard - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-users.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@cablechewer Thank you for your feedback. Since you are internal Microsoft submitter, we request you submit the request via https://aka.ms/RequestComplianceDocs

Thanks again for your feedback.

Regards
Sri
