### ISSUE TITLE
Create New Folder or Document Missing options

### ISSUE THREAD

**Issue by ejbulaong** [MicrosoftDocs/microsoft-365-docs#1164]
After I enabled IRM in my Documents Library, the option for Word, Excel, etc. in the +New button are gone and the Edit New Menu button is not doing anything. I disabled the IRM and the options are back and the Edit New Menu button is working again. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0704afe-d1a4-c553-38ed-b7ee6a95e416
* Version Independent ID: 3d83f05b-965d-1b9a-4773-a8a77bd89473
* Content: [Apply Information Rights Management (IRM) to a list or library - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-irm-to-a-list-or-library)
* Content Source: [microsoft-365/compliance/apply-irm-to-a-list-or-library.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-irm-to-a-list-or-library.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@ejbulaong - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
