### ISSUE TITLE
Autopilot and pre-provisioning by admin/service provider blocks self-service M365 App installation

### ISSUE THREAD

**Issue by domcote** [MicrosoftDocs/microsoft-365-docs#11664]
The instructions for users to install M365 Apps themselves assume they have local administrative privileges.
The only time that seems realistic is when they go through OoBE themselves.

Any other reasonable scenario won't allow it:
1. Autopilot (key reason to use Autopilot is to NOT make users admins)
2. Any sort of pre-provisioning by a service provider or local admin (including Autopilot)

IMHO this needs to be reflected, not just here but all over M365 BP documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9478bdea-fc84-7014-f85f-6a8581207df4
* Version Independent ID: 9478bdea-fc84-7014-f85f-6a8581207df4
* Content: [Install Microsoft 365 apps on all devices in Microsoft 365 Business Premium - Microsoft 365 Business Premium](https://learn.microsoft.com/en-us/microsoft-365/business-premium/m365bp-install-office-apps?view=o365-worldwide&tabs=iPhone)
* Content Source: [microsoft-365/business-premium/m365bp-install-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-premium/m365bp-install-office-apps.md)
* Service: **microsoft-365-security**
* Sub-service: **m365bp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @domcote. Thank you so much for your helpful feedback. I will look into this and get the docs updated.

**Comment by domcote** [comment]
Happy to help.

As a rough outline I can suggest this alternate approach to deploy M365 Apps on M365 BP tenants, which is much more “enterprise”-style:

1.	Optionally: Use Autopilot. Not so much for initial deployment (SMBs don’t deploy new devices all the time), but with these benefits:
- Self-Onboarding users are local users on their devices, not local admins. A huge security benefit.
- If a device starts mis-behaving support folks can just remotely wipe/reset the device and Autopilot will always guide non-technical (potentially remote) users back on board, restoring original functionality again. Through the Company Portal App, users can do the same.
- It is theft-protection “light”. As long as it runs Windows Pro, that device can’t be “hijacked” and used solely for personal purposes.
2.	Configure an M365 App deployment policy in Intune to auto-deploy using a “required” assignment. However, this MUST be done using an XML profile, not a config designer profile as only the former allows specifying the <Product ID="O365BusinessRetail"> parameter. Without it, all sorts of strange effects occur.
This’ll work regardless of user rights and how the device was deployed.
3.	Since no ordinary folks know how to create an Office xml config file by hand, I used [Office Customization Tool - Microsoft 365 Apps admin center](https://config.office.com/deploymentsettings) which is an easy GUI to do the Job.

**Comment by denisebmsft** [comment]
Hello @domcote. Thank you again for your helpful feedback. I have made some revisions (more will follow) to the Microsoft 365 Business Premium content. One addition is a new article that explains managed vs unmanaged devices in the context of this content set. I'm still reviewing your suggestions and will be making more revisions soon.

https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/20010
https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/20016
https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/20017
