### ISSUE TITLE
Powershell Example

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/microsoft-365-docs#11667]
[Enter feedback here]

In the example PowerShell for Get-OwaMailboxPolicy and Set-OwaMailboxPolicy I believe the <> operators should be omitted.  Generates an error that the '<' operator is reserved for future use.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8af6036-e59d-10ef-6563-5cdbcef9104b
* Version Independent ID: d8af6036-e59d-10ef-6563-5cdbcef9104b
* Content: [Custom domain support in Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/custom-domain-support?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/custom-domain-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/custom-domain-support.md)
* Service: **bookings**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@FC-EricWeller Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11719

Once the author approves, the changes will be lvie.

Thanks
Sri
