### ISSUE TITLE
"Convert a shared mailbox back to a user's (private) mailbox" instructions are outdated

### ISSUE THREAD

**Issue by Xpyder** [MicrosoftDocs/microsoft-365-docs#11669]
The instructions under "Convert a shared mailbox back to a user's (private) mailbox" are outdated, there's no Shared under Recipients in the Exchange Admin Center

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13b3fbbe-fde3-fd52-f9cd-d8fca56a1494
* Version Independent ID: 73d71ee8-579d-78b5-a8cd-48d7ec51ebb8
* Content: [Convert a user mailbox to a shared mailbox - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **microsoft-365-business**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@Xpyder Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11721

Once the author approves, the changes will be live.

Thanks
Sri
