### ISSUE TITLE
Retention Label - Version History

### ISSUE THREAD

**Issue by i-dodd** [MicrosoftDocs/microsoft-365-docs#11665]
In the section - How retention works with document versions (https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-retention-works-with-document-versions), it states for document versions _“That's not the case for retention labels when the content isn't subject to a retention policy (or an eDiscovery hold). Instead, the versioning limits are honored so that older versions are automatically deleted to accommodate new versions, but users are still prevented from deleting versions.”_

What we are seeing is when an item has a retention label the version limit is completely ignored and all versions are retained. If you then remove the label then all versions beyond the limit are deleted. What I take from the wording from the page is that the versions beyond the limit should be deleted even when the file has a retention label. Is this wording correct or is it expected behaviour version history limit is ignored when content has a retention label?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-retention-works-with-document-versions)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@i-dodd After checking with engineering, please open a support ticket for investigation.  The expectation is as documented.

**Comment by i-dodd** [comment]
Ok thanks I have raised a support ticket. Another thing I have noticed is the first line in the same section states: "Versioning is a feature of all document lists and libraries in SharePoint and OneDrive. By default, versioning retains a minimum of 500 major versions, although you can increase this limit."

You can decrease the limit as well as increase it though can't you?

**Comment by cabailey** [comment]
@i-dodd  Yes, the referenced links explains how you can increase or decrease the limit. Revised the word to "change" to avoid any misinterpretation.
