### ISSUE TITLE
Inaccurate instructions for getting to the message trace

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/microsoft-365-docs#1166]
Since Security and Compliance are separated, these instructions are no longer accurate: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc#open-message-trace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58f8e2c-428a-4d8e-e8b7-a0342a0038db
* Version Independent ID: 6e7fab1b-1e24-9e36-176d-c3fb14f233a7
* Content: [Message trace in the Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc#open-message-trace)
* Content Source: [microsoft-365/security/office-365-security/message-trace-scc.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/message-trace-scc.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@franklesniak, for the foreseeable future, there will be the original Security & Compliance Center, the new Compliance Center, and the new Security Center. I updated the topic with instructions that are more accurate in the current landscape.

Thanks for the feedback.

**Comment by farces** [comment]
@chrisda is there any plan to add the security & compliance center link back to 'all admin centers' in the portal? At the moment there are the two individual portals listed only, and to get to the old portal you either have to bookmark the original protection URL or go to exchange admin center->mail flow->message trace->"go to new portal".

**Comment by chrisda** [comment]
@farces. in my E5 tenant, from the main M365 admin page at <admin.microsoft.com>, if I click **Show all**, Security & Compliance is there:
![image](https://user-images.githubusercontent.com/33166947/74961429-eccf7080-53c2-11ea-9ee4-af38f7ed9408.png)
As you describe, it isn't available under **All admin centers**, but neither is the new Compliance Center or the new Security Center, so whatever is going on there is probably in flux.
