### ISSUE TITLE
No documentation on how to actually setup the azure storage account and container

### ISSUE THREAD

**Issue by joshammons** [MicrosoftDocs/microsoft-365-docs#11677]
This article explains how to export to an azure storage account but does not give any details on HOW that azure storage account should be setup. What settings does the azure storage and container need for this to work? I have setup an azure storage account and tried multiple settings and have followed what instructions are here but continue to get 404 errors from the MS Premium eDisco client.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bbdb9ae-bbde-ae26-f608-479e529fb6d9
* Version Independent ID: b3bab9c7-3802-9fd5-b438-969195817cc5
* Content: [Export documents to an organization Azure Storage account - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/download-export-jobs?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/download-export-jobs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/download-export-jobs.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by joshammons** [comment]
Besides documentation on recommendations for setting up the azure storage account and container, this page also needs to explicitly call out that when you paste the SAS token from the container you must add a question mark "?" prior to pasting it into the SAS Token field in the review set export settings. Otherwise, you will get http 404 errors if you only paste the SAS token without the question mark "?".

**Comment by joshammons** [comment]
Another thing that I found that isn't called out in the documentation is that the SAS token you create for the azure storage monitor needs to have all permissions, otherwise it will return a 403 forbidden error. This should either be included in the documentation or it's a bug in the MS Premium eDisco tool that should be fixed. It does not seem logical that "read", "delete", "immutable storage", and some of the other permissions would be needed to write data to the container from MS Premium eDisco client.

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@joshammons Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
