### ISSUE TITLE
Activate Rights Management in admin center

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/microsoft-365-docs#11673]
The title says "Activate rights management in the admin center" but it doesn't actually say how to activate them in the admin center.

Is it possible? Or is only possible to enable RM with PowerShell?

If it is indeed possible, instructions should be added on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d20fbb5-c482-7944-b726-63b2b3e1ddbe
* Version Independent ID: 0a98d497-e6fa-3aa3-23ba-7939f5fb7a1e
* Content: [Activate rights management in the admin center - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/activate-rms-in-microsoft-365?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/activate-rms-in-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/activate-rms-in-microsoft-365.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by JMCA2** [comment]
@alejaraz

**Comment by msbemba** [comment]
@JMCA2 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11722

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per author's comment in PR. Thanks
