### ISSUE TITLE
Update antimalware Security intelligence section - The AUOptions registry key - is GPO option 7 relevant too?

### ISSUE THREAD

**Issue by ilgs** [MicrosoftDocs/microsoft-365-docs#11679]
Configure Automatic Updates GPO has "new" option related to servers only: 7 – Auto Download, Notify to install, Notify to Restart. (Windows Server only). According to its description it also downloads all updates including Defender definitions. So, will this also allow automatic definition installation for Defender on Servers? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff9a2869-614c-e077-8d71-351448810897
* Version Independent ID: 09369dc3-f8d1-9b19-0043-47fa733a3b81
* Content: [Microsoft Defender Antivirus on Windows Server](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server?view=o365-worldwide&source=docs#update-antimalware-security-intelligence)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@ilgs Thank you for your feedback. Yes, it does  install  automatic definition.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ilgs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ilgs** [comment]
@msbemba Thanks for update.
@yogkumgit Thanks as well for taking care. I think, that yes, documentation update is required, since "Option 7" is not listed in it, but only 3 and 4, as in attached screenshot.
![image](https://user-images.githubusercontent.com/130704653/234762081-4e652b13-64f1-4323-bb14-e60347a051f6.png)
