### ISSUE TITLE
Update with info on Spoof Intelligence Insight

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#1167]
This article is really about addressing false positive emails in Office 365, and the single biggest cause of false positives that I've observed is O365's anti-spoofing detection. Microsoft is enforcing anti-spoofing tech (SPF, DKIM and DMARC) when most bulk email senders have not yet implemented these anti-spoofing technologies. 

Luckily Microsoft has also provided a feature, Spoof Intelligence Insight, to allow organizations to intelligently whitelist domain pairs that fit this case. There's a whole walkthrough here: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight. IMO, using this feature should be the first measure to deal with false positives before the other whitelisting measures mentioned in this article are considered. This is a much safer method than whitelisting an address or a domain because it whitelists the domain only for a particular sending infrastructure, not just messages "from" the domain coming from anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello @robmacf ,
Spoof Intelligence Insight allows to send unauthenticated emails, it doesn’t allow to bypass other antispam checks. I don’t think that this feature should be described here, as this page is in “Anti-spam and anti-malware protection” section, not in the “Anti-spoofing protection in Office 365”. 

**biggest cause of false positives that I've observed is O365's anti-spoofing detection** - Sure it is a major cause, I believe the link you've provided should be added to the article, I will create the PR for it.

Thank you

**Comment by chrisda** [comment]
PR merged. Closing
