### ISSUE TITLE
Network Protection cannot start due to unsupported release ring

### ISSUE THREAD

**Issue by staze** [MicrosoftDocs/microsoft-365-docs#11680]
Just trying to figure out documentation. The base documentation says to set MAU to Current for Release Channel. 
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide#step-5-configure-microsoft-autoupdate-mau

But a mention here says set it to "External". https://github.com/MicrosoftDocs/microsoft-365-docs/issues/10004 (mention of this is no where in the documentation). 

Set to "Current", mdatp health reports "Network Protection cannot start due to unsupported release ring" and release ring is "Custom". We are using the manifest produced by pbowden built into Jamf, which has Defender set to Current.

**Comment by staze** [comment]
May be that it's a bad error message due to the fact edr isn't fully rolled out yet? https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection-macos?view=o365-worldwide

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by staze** [comment]
Speaking to Max Velitchko, this is expected behavior. Network protection is still in preview, so update channel has to match. This can be closed.
