### ISSUE TITLE
Changes to this page

### ISSUE THREAD

**Issue by BlakeMsft** [MicrosoftDocs/microsoft-365-docs#11685]
I recommend moving the Requirements section to the top.
I recommend adding an additional OS to the Reqirements section - "Windows 2012 R2 with the Modern Unified Solution".
I recommend removing the following section as it's already mentioned in the Requirements section:

Supported OS versions:
Windows Version 10 and later.
Note
This feature is available starting with platform version 4.18.2108.X and later.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e075325-c8a9-4152-352f-6399e036c896
* Version Independent ID: 03ff8166-3867-23f1-5dc3-75f603cfe919
* Content: [Performance analyzer for Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@BlakeMsft We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11725

Once the author approves, the changes will be live.

Thanks
Sri
