### ISSUE TITLE
want to change

### ISSUE THREAD

**Issue by ERIC-ZHAO-3366** [MicrosoftDocs/microsoft-365-docs#11689]
I prefer "Connect-SPOService -URL https://contoso-admin.sharepoint.com -credential admin@contoso.com" to change 'Connect-SPOService -url https://<TenantName>-admin.sharepoint.com'. Because when I use 'Connect-SPOService -url https://<TenantName>-admin.sharepoint.com', it will say unsupported browser

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 942901e0-cdff-92c2-d986-6675efd2eca5
* Version Independent ID: 942901e0-cdff-92c2-d986-6675efd2eca5
* Content: [OneDrive Cross-tenant OneDrive migration Step 1 - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-onedrive-migration-step1?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-onedrive-migration-step1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-onedrive-migration-step1.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ERIC-ZHAO-3366 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
