### ISSUE TITLE
Automated Investigation is no longer available in the security portal

### ISSUE THREAD

**Issue by jigyasugulati90** [MicrosoftDocs/microsoft-365-docs#11696]
Automated Investigation is no longer available in the security portal. Refer attached image.
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-features?view=o365-worldwide#automated-investigation 
<img width="1299" alt="Screenshot 2023-04-17 at 1 56 36 PM" src="https://user-images.githubusercontent.com/77526024/232428881-340cd0cf-0230-4899-9942-915befb33451.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3c074f5-bd58-6b72-d891-3d9fe0118767
* Version Independent ID: 2eea3a11-be82-49bc-6056-f4fba30bd638
* Content: [Configure advanced features in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-features?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/advanced-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/advanced-features.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jigyasugulati90 Thank you for your feedback. We have removed automated investigation from the document as it is no longer available 

Thank you for highlighting the same.

Hoep this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jigyasugulati90 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
