### ISSUE TITLE
Incomplete info re: Scheduled Scans in Passive/EDR Block Mode

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#11699]
I recently had to raise a support case as we were seeing full scans completing on endpoints that were in EDR Block Mode and couldnt understand why as the documentation in the section linked here - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide#how-microsoft-defender-antivirus-affects-defender-for-endpoint-functionality

states that _"(5) When Microsoft Defender Antivirus is in passive mode, scans aren't scheduled. Note that scan tasks that are enabled in Windows Task Scheduler will continue to run according to their schedule. If you have such scheduled tasks, you can remove these if preferred."_

Whilst this is technically correct, what it should also state is that if scans are scheduled in your configuration at all, the schedule will be ignored but unless catchup scans are disabled, then catchup scans will still occur.

In my scenario I had created a scan policy in SCCM that included scheduled scan and catchup scan settings that I thought (based on the documentation) would apply when Defender was in Active Mode.

Had the detail about catchup scans behaviour applying regardless (if scheduled scans are configured) been documented, then this would have prevented me from needing to raise a support ticket to understand why full scans were running on devices in EDR Block mode.

Thanks

Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61024433-366d-5ea3-4a3f-0cdd5cdcd900
* Version Independent ID: 348d3fc9-0937-b3a6-897e-09d1236d7019
* Content: [Microsoft Defender Antivirus compatibility with other security products](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @pjrcdf for letting us know about this issue. I'll look into it.

**Comment by denisebmsft** [comment]
Hello @pjrcdf. Thank you again for your helpful feedback. The article has been updated and you'll see the changes go live a little later today.
