### ISSUE TITLE
need clarification on network protection pki

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/microsoft-365-docs#11690]
In the MDE android setup for network protection it is also necessary to setup trusted root certificates in the configuration keys, please clarify if this is needed for iOS as well.

Thanks
Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4eae37-e4cf-2642-d2cf-c648f90d2cc6
* Version Independent ID: 7cb88605-ddc9-5a1a-67f4-a28da1819227
* Content: [Configure Microsoft Defender for Endpoint on iOS features](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-configure-features?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-configure-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-configure-features.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Pls contact support.
