### ISSUE TITLE
When is the renewal for April 2023?

### ISSUE THREAD

**Issue by KENJISHIRAKI** [MicrosoftDocs/microsoft-365-docs#11693]
[Enter feedback here]
This page is updated almost monthly, but not yet for April 2023. When will the page be updated?
The reason I am asking this question is because the following public information states that new features were added to MDE by KB5025229, but I do not know the details.
https://support.microsoft.com/en-us/topic/april-11-2023-kb5025229-os-build-17763-4252-e8ead788-2cd3-4c9b-8c77-d677e2d8744f
>New! This update adds many new features and improvements to Microsoft Defender for Endpoint. For more information

Please update this page to confirm what features were added.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c5eb6e9-4010-6077-4746-ec9f93148f9e
* Version Independent ID: 8c5eb6e9-4010-6077-4746-ec9f93148f9e
* Content: [What's new in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-endpoint?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-endpoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-endpoint.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by KENJISHIRAKI** [comment]
Hello @mjcaparas -san, @yogkumgit -san,
Any progress on the update of this article here?
Best regards,

**Comment by mjcaparas** [comment]
maybe see: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/windows-whatsnew?view=o365-worldwide
