### ISSUE TITLE
The screenshot of the CSV in section Import retention labels into your file plan is incorrect

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#11706]
The screenshot of the File Plan import CSV in section Import retention labels into your file plan is incorrect
The column IsRecordLabel shows values of Yes and No. This is incorrect. The correct values are TRUE and FALSE. This is detailed in the table in the section Information about the label properties for import 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Use file plan to manage retention labels - Microsoft Purview (compliance)](https://learn.microsoft.com/en-gb/microsoft-365/compliance/file-plan-manager?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@nikki-c  Thanks for flagging this minor discrepancy in the screenshot we missed!  Noted for a future revision.
