### ISSUE TITLE
The table Information about the label properties for import is not complete

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#11707]
The table Information about the label properties for import is not complete

I have found out through trial and error that some properties have character limits. For  example the Categories property has a maximum length of 64. When you upload you file Plan and a property exceeds the character limits you get an error message. 

![image](https://user-images.githubusercontent.com/69439002/232778111-41066011-0705-4088-9131-8de4eaa8f422.png)

I have come across character limitations in the following three properties LabelName, DepartmentName and Categories but this list may  not be exhaustive.
Can you update the table to show the character limits for the columns to make it clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Use file plan to manage retention labels - Microsoft Purview (compliance)](https://learn.microsoft.com/en-gb/microsoft-365/compliance/file-plan-manager?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@nikki-c  I am waiting on engineering to investigate this. Some time ago, a change was made to remove the length limitation of 64 characters for all but the ones listed in the documentation (LabelName, Comment, and Notes) and that's the by-design implementation. But we've been hearing that some customers run into fields that have the old length limitation, as you have done, and the error message is sufficient to unblock them. LabelName is documented as 64 characters (before the table).
