### ISSUE TITLE
clarification needed on cases when users won't get signed out

### ISSUE THREAD

**Issue by JohnInAtlanta** [MicrosoftDocs/microsoft-365-docs#11702]
On the bullet point "Users won't get signed out in these cases", the third item is ambiguous. "if they're on a managed device (one that is compliant or joined to a domain) and using a supported browser like Microsoft Edge or Google Chrome (with the Windows Accounts extension.)

it isn't clear if "(with the Windows Accounts extension)" applies **only** to Google Chrome, or if it applies to **both** Microsoft Edge and Google Chrome.

**Comment by msbemba** [comment]
@JohnInAtlanta Thank you for your feedback. It applies to Microsoft edge irrespective of the extension. However,for google chrome it applies only with the [Windows Accounts extension](https://chrome.google.com/webstore/detail/windows-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JohnInAtlanta Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
