### ISSUE TITLE
attachmentnames property not searching for only extension name

### ISSUE THREAD

**Issue by GregNelsonatPeters** [MicrosoftDocs/microsoft-365-docs#1170]
The documentation https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions states
"The third example returns all attachments with the pptx file extension."  With 3rd example being attachmentnames:.pptx

In Office 365 I have attempted to use this in the Keywords area.  It is pulling any attachment with the phrase PPTX  so the file name could be THISPPTX.DOC and it will still be pulled as a result.  This seems to be a technical issue or an issue with the documentation.

**Comment by markjjo** [comment]
@GregNelsonatPeters Thanks for reaching out. But I can't repro this. Using attachmentnames:.pptx returns only attachments with .pptx file extension. It did not return the attachment named PPTXTest.docx. Is this is an issue for you, I would suggest you open a support ticket with Microsoft Support.

![image](https://user-images.githubusercontent.com/36746813/73573280-d7040680-4427-11ea-857f-49d13b778970.png)
