### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by marjoriemaddison** [MicrosoftDocs/microsoft-365-docs#1171]
The page security and compliance does not exist as per instructions in Open message trace.  Only security OR compliance, separate sights in which message trace is not included in either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58f8e2c-428a-4d8e-e8b7-a0342a0038db
* Version Independent ID: 6e7fab1b-1e24-9e36-176d-c3fb14f233a7
* Content: [Message trace in the Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc#feedback)
* Content Source: [microsoft-365/security/office-365-security/message-trace-scc.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/message-trace-scc.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by wendyhelson5469** [comment]
DO NOT LINK

**Comment by GiantCrocodile** [comment]
See this @marjoriemaddison: https://protection.office.com/messagetrace

I was able to find it as described in the docs:

![grafik](https://user-images.githubusercontent.com/6271057/73597852-f5095e00-4530-11ea-9c79-e9a280036506.png)

**Comment by chrisda** [comment]
Closing as duplicate of #1166. I updated the instructions.

Thanks for the feedback
