### ISSUE TITLE
'Retention period expired' trigger behavior and Power Automate action-limits

### ISSUE THREAD

**Issue by kstat** [MicrosoftDocs/microsoft-365-docs#11723]
Are there any details around how the 'retention period expired' trigger gets fired if there are multiple records (e.g., thousands) that expire within a given day/time-period? Since event-based retention may start the retention clock on multiple documents at/around the same time (as per any ComplianceAssetID conditions), there could be many documents expiring together at the same time. How does this volume interact with any Power Automate flow [limits](https://learn.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations#licensed-user-request-limits)?

E.g. - if the flow is complex and has multiple actions within it, is there a risk of the flow(s) being throttled when there are multiple records expiring at the same time? This information would be helpful from a capacity planning POV for a custom flow-based disposition solution. 

There is [documentation ](https://learn.microsoft.com/en-us/connectors/microsoft365compliance/#limits) on the Compliance Connector page that speaks to throttling limits for calls coming back into Purview from Power Automate. This question is about the reverse - if there are any specific non-functional behavior patterns or details of the limits of the trigger from Purview when it tries to call in to any Flow(s)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43c8da6b-a034-f4fc-db7e-e341f8adf4d5
* Version Independent ID: 43c8da6b-a034-f4fc-db7e-e341f8adf4d5
* Content: [Customize what happens at the end of the retention period - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-label-flow?view=o365-worldwide#when-the-flow-is-triggered)
* Content Source: [microsoft-365/compliance/retention-label-flow.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-label-flow.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@kstat I'm told nothing special here for this scenario beyond the standard flow limits.
