### ISSUE TITLE
Is the size limit 2TB or 2GB the text here is unclear.

### ISSUE THREAD

**Issue by JonathanWrigley** [MicrosoftDocs/microsoft-365-docs#11720]
OneDrive account size limits
Each OneDrive account can have a maximum of **2 TB** of content or 1 million items.

Important
If you attempt to migrate any OneDrive site that exceeds the **2GB** quota, the transfer will fail.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c59d15b-a5d1-400a-aa12-8d768817f8f6
* Version Independent ID: 3c59d15b-a5d1-400a-aa12-8d768817f8f6
* Content: [Cross-tenant OneDrive migration overview - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-onedrive-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-onedrive-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-onedrive-migration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by msbemba** [comment]
@JonathanWrigley Thank you for your feedback. The size limit is indeed 2TB. However, If you attempt to migrate any OneDrive site that exceeds the 2GB quota, the transfer will fail.

We hope to increase those limits in the future to ensure larger OneDrive accounts can be migrated via the process. 

Hope this helps!

Thanks
Sri

**Comment by JonathanWrigley** [comment]
This is still unclear. So if a one drive is bigger than 2GB is won’t
migrate?  It seems like there is a mistake with the use of GB and TB in the
documentation.  Is it max drive size for a successful migration 2tb or 2Gb?

Thanks

Jonathan

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@JonathanWrigley 

The maximum size a onedrive account can hold - 2 TB

The maximum size for a single onedrive migration is 2 GB.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JonathanWrigley Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
