### ISSUE TITLE
Misleading Information.

### ISSUE THREAD

**Issue by iamvishals** [MicrosoftDocs/microsoft-365-docs#1172]
Please add details that the fingerprinting is limited to Exchange online only and would not cover any other workloads in the M365 Suite. Also, please correct the MCAS documentation as it suggests that you can use fingerprinting in MCAS policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 327f1fbb-ffb4-4d3a-53db-d43ad239ef0c
* Version Independent ID: f23ccb3e-b493-8eaf-d87d-61ae6acc3919
* Content: [Document Fingerprinting - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/document-fingerprinting#feedback)
* Content Source: [microsoft-365/compliance/document-fingerprinting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/document-fingerprinting.md)
* Service: **exchange-online**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @iamvishals 
Thank you for your comment,  I am investigating this and will update the content as appropriate.

**Comment by chrfox** [comment]
@iamvishals 
confirmed with PG that the documentation is correct, document fingerprinting can be used in MCAS file policies.
