### ISSUE TITLE
Unable to create new scans via API with authentication type community string

### ISSUE THREAD

**Issue by bcrpntr** [MicrosoftDocs/microsoft-365-docs#11732]
I am attempting to bulk create scans, but am not able to create a scan for SNMP community strings.
Documentation example only gives type AuthPriv; https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/add-a-new-scan-definition
Pulling from the endpoint, all existing show null for scanAuthenticationParams.
Is there something I'm missing here, or is this not a possibility currently?

**Comment by bcrpntr** [comment]
I was able to do some testing on this, and found that the type needed to be set to "CommunityString".

I also had to change the format to this for any requests to work, the default template resulted in an incorrect format error;
`{
  "scanType": "Network", 
  "scanName": "Test Network scan", 
  "isActive": true, 
  "target": "127.0.0.1", 
  "intervalInHours": 1, 
  "targetType": "Ip",
  "scannerAgent": {
      "machineId": "eb663a27678ik2f61bc268a79eeasdf450f77",
      "machineName": "DESKTOP-TEST"
  },
  "scanAuthenticationParams": {
    "@odata.type": "#microsoft.windowsDefenderATP.api.SnmpAuthParams", 
        "type": "CommunityString",
        "communityString": "community-string" 
  }
}`

**Comment by yogkumgit** [comment]
@siosulli Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@siosulli Thank you very much for the contribution and sharing this explanation. @bcrpntr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
