### ISSUE TITLE
Limits to custom tile to the app launcher

### ISSUE THREAD

**Issue by MichaelJZurawski** [MicrosoftDocs/microsoft-365-docs#11731]
Are there limits to the custom tile to the app launcher?  We have hundreds now and are seeing delays with icons and searches working.   Knowing the limits on this page would be helpful. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9488caf7-b791-3002-8749-7fdc4b2ec8b3
* Version Independent ID: 08e61eb0-7bcd-f449-46ef-17e209138a8e
* Content: [Add custom tiles to the app launcher - Microsoft 365 admin](https://learn.microsoft.com/en-US/microsoft-365/admin/manage/customize-the-app-launcher?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/customize-the-app-launcher.md)
* Service: **microsoft-365-business**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@MichaelJZurawski Thank you for your feedback. Currently, there are no limits for the custom tile to the app launcher. If there is a delay in icons and searches, I'd recommend you contact support via the need help section on the admin center, so that they can fix the problem or bug.

Hope this helps!

Thanks
Sri

**Comment by MichaelJZurawski** [comment]
Great, thank you.  You may close the ticket.



Thank you,

Michael J. Zurawski | EUC Engineering | Collaboration
Health Care Service Corporation (HCSC)
***@***.******@***.***>
M: (847) 366-9388
