### ISSUE TITLE
Windows 11 client missing

### ISSUE THREAD

**Issue by jppistoia** [MicrosoftDocs/microsoft-365-docs#11766]
[Enter feedback here]

When is defining OS supported should be say windows 10/11 ?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec57328d-4b17-abe6-001e-c5ecb2f00746
* Version Independent ID: be98599a-b690-a3e6-c610-8da71fd80d76
* Content: [Compare Microsoft endpoint security plans](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@jppistoia Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11865

Once the author approves, the changes will be live.

Thanks
Sri
