### ISSUE TITLE
Page is Out  of date.

### ISSUE THREAD

**Issue by Scarkal** [MicrosoftDocs/microsoft-365-docs#11767]
You have made changes and added a new interface for AAD. Please update this article with the new screen shots of where Secuirty and Properties can be found to get to the AAD properties.  4-19-23

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 965d1d2f-81dd-8057-5a13-4f75cfe0c1f7
* Version Independent ID: 7bd2fc7a-93dd-9081-6d98-3e28fdebe342
* Content: [Turn on MFA with security defaults or Conditional Access - Microsoft 365 Business Premium](https://learn.microsoft.com/en-us/microsoft-365/business-premium/m365bp-conditional-access?view=o365-worldwide&tabs=secdefaults)
* Content Source: [microsoft-365/business-premium/m365bp-conditional-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-premium/m365bp-conditional-access.md)
* Service: **microsoft-365-security**
* Sub-service: **m365bp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@Scarkal Thank you for your feedback. We will update the screenshots in the document shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@Scarkal Thank you for your feedback. I see the navigation and the properties page to be the same as mentioned in the document

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/3d17013d-0c06-4fc4-aa1e-63840dfafdb0)


Thanks
Sri
