### ISSUE TITLE
Set-PolicyConfig -InformationBarrierMode 'MultiSegment' Does Not Work

### ISSUE THREAD

**Issue by l2g2h** [MicrosoftDocs/microsoft-365-docs#11773]
Hello,

 I have attempted this with multiple tenants it does not work. I have tried via powershell 5 or terminal powershell 7. I have tried latest EXO 2.x and 3.x.
 
 This is a Microsoft issue not an issue to redirect to customer support it's obviously reoccurring in various licenses & tenant types as well as for various others. 

This contradicts documentation provided by Microsoft making the product look as if it'll work for a scenario when it doesn't.

> 
>  Set-PolicyConfig -InformationBarrierMode 'MultiSegment'
> Information Barrier config is not updated successfully. Error: {"error":{"code":"40005","message":"Unrecognized mode, source mode
> and destination mode should be 'Single' or 'MultiAllow'"}}.
>     + CategoryInfo          : NotSpecified: (:) [Set-PolicyConfig], IBConfigUpdateFailureException
>     + FullyQualifiedErrorId : [Server=MW2NAM12WS020,RequestId=365ec443-3d37-42ff-b60f-0d9c9f56bf2f,TimeStamp=4/19/2023 10:47:35 PM]
>     [FailureCategory=Cmdlet-IBConfigUpdateFailureException] DD30B15B,Microsoft.Office.CompliancePolicy.Tasks.SetPolicyConfig
>     + PSComputerName        : nam12b.ps.compliance.protection.outlook.com

**Comment by Purple-Tentacle** [comment]
According to Microsoft support you should run 

`Connect-IPPSSession`
`connect-exchangeonline`
`Get-OrganizationConfig | FL *information*`

and NOT `Get-PolicyConfig`.

`Get-OrganizationConfig | FL *information*` shows Legacy, which explains the error I am receiving.

**Comment by msbemba** [comment]
@l2g2h Thank you for your feedback. Are you referring to the below document? https://learn.microsoft.com/en-us/microsoft-365/compliance/information-barriers-edit-segments-policies?view=o365-worldwide

Thanks
Sri

**Comment by Purple-Tentacle** [comment]
I am not the one who was asked, but I was referring to this:
https://learn.microsoft.com/en-us/microsoft-365/compliance/information-barriers-multi-segment?view=o365-worldwide#check-the-ib-mode-for-your-organization

**Comment by yogkumgit** [comment]
Closing as per #11597

**Comment by Purple-Tentacle** [comment]
Why is this closed? The documentation is still wrong.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Purple-Tentacle @l2g2h Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11975

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@l2g2h Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
