### ISSUE TITLE
Missleading information 

### ISSUE THREAD

**Issue by adcferr** [MicrosoftDocs/microsoft-365-docs#11777]
Hello,

In the Microsoft Workplace Analytics activities, the Note mentions this is possible to check in AAD sign in logs.
Is it possible to access sign out logs in AAD?
Could you please clarify this?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2acaa1df-0b13-a511-b3ef-af5bc8f0acfa
* Version Independent ID: 2acaa1df-0b13-a511-b3ef-af5bc8f0acfa
* Content: [Audit log activities - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-activities?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-activities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-activities.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by adcferr** [comment]
Reference to:  https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-activities?view=o365-worldwide#microsoft-workplace-analytics-activities

"Note

*These are Azure Active Directory sign in and sign off activities. These activities are logged even if you don't have Workplace Analytics turned on in your organization. For more information about user sign in activities, see [Sign-in logs in Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-sign-ins)."

In the table above this note there is a log regarding user log off logs.

Let me know once there is an update or action plan regarding this please.

**Comment by adcferr** [comment]
any update regarding this?

**Comment by yogkumgit** [comment]
@adcferr Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
