### ISSUE TITLE
Explicitly cover the upgrade from Windows 11 Home to Windows 11 Pro

### ISSUE THREAD

**Issue by agiliant** [MicrosoftDocs/microsoft-365-docs#11776]
This page does not make it clear whether the M365 Business Premium licence allows a user to upgrade from Windows 11 Home to Windows 11 Pro. My assumption is it does not but it would be very helpful if that scenario can be explicitly addressed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0eef3514-c5f5-66e4-98d1-4dbc7b2af260
* Version Independent ID: 0eef3514-c5f5-66e4-98d1-4dbc7b2af260
* Content: [Upgrade Windows devices to Windows 10 or 11 Pro - Microsoft 365 Business Premium](https://learn.microsoft.com/en-us/microsoft-365/business-premium/m365bp-upgrade-windows-10-pro?view=o365-worldwide#purchase-windows-10-or-11-pro-to-upgrade-from-windows-10-home)
* Content Source: [microsoft-365/business-premium/m365bp-upgrade-windows-10-pro.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-premium/m365bp-upgrade-windows-10-pro.md)
* Service: **microsoft-365-security**
* Sub-service: **m365bp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @agiliant and thank you for posting your question here. Microsoft 365 Business Premium does not include free upgrades from Home versions of Windows to Pro. Upgrades from previous versions of Windows Pro, such as Windows 7 or 8.1 Pro to Windows 10 Pro are included, but not upgrades from Windows 11 Home to Windows 11 Pro. I hope this helps! I have updated the article and the changes will be live later today (like at around 4 p.m. Pacific Time). Thank you again for your feedback!
