### ISSUE TITLE
'Windows and Office deployment and management lab kit.' Installation Failure

### ISSUE THREAD

**Issue by Alexdd65** [MicrosoftDocs/microsoft-365-docs#1178]
I had a similar issue with version 1903 already, but since the new version would arrive any moment, I waited for this one..
Freshly downloaded yesterday..
Cleared my Test Environment to start from scratch (Dual core i7 server with 32GB RAM, 450GB disk using Server 2012R2 Hyper-V. C-drive = 450GB + D-drive = DVD)

Running the setup works fine for all the servers.
Looks like it is then preparing all the clients where I found the vhd files for Client 5 & 6..
During creation of the Win7 client, it's failing.
![image](https://user-images.githubusercontent.com/56219878/73639383-8b8e6a00-466c-11ea-9cb2-47db93d52e5e.png)

I did notice that it had setup a drive F (boot drive) & G (system), where it's pointing to the wrong drive which is causing the failure.

Hyper-V doesn't include any of the Clients..
![image](https://user-images.githubusercontent.com/56219878/73639424-a4971b00-466c-11ea-83be-70b72d660902.png)

both installation logs have been attached as well..

[moagd55y.xhu.Log](https://github.com/MicrosoftDocs/microsoft-365-docs/files/4146993/moagd55y.xhu.Log)
[tmp2ABD.tmp.log](https://github.com/MicrosoftDocs/microsoft-365-docs/files/4146994/tmp2ABD.tmp.log)

**Comment by mypil** [comment]
@Alexdd65 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by Alexdd65** [comment]
This starts from:
https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab

Where you find the entire download for the Lab environment installation.
https://www.microsoft.com/en-us/evalcenter/evaluate-lab-kit

Once downloaded, you get the installation and documentation..

It is that INSTALL which is failing..

**Comment by mypil** [comment]
@Alexdd65 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products
