### ISSUE TITLE
Steps do not work as described

### ISSUE THREAD

**Issue by 1024-Kibibytes** [MicrosoftDocs/microsoft-365-docs#11781]
Under Step 2, I ran Connect-MsolService. PowerShell 7.3.0 returned "The term 'Connect-MsolService' is not recognized."

I had to run Import-Module MSOnline first in order to get Connect-MsolService to run at all.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55574af9-0105-dcd1-7eb0-77513df4e54f
* Version Independent ID: 5fe2849b-d39a-4d75-a5ce-e8f577c9a161
* Content: [Connect to Microsoft 365 with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide#connect-with-the-azure-active-directory-powershell-for-graph-module)
* Content Source: [microsoft-365/enterprise/connect-to-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@1024-Kibibytes Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11864

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by temanteleary** [comment]
@msbemba I am going to approve the changes made to the document as I am filling in for the author, Kelley, who is on leave.  I am just seeing this open PR as part of our new monthly content freshness review.

**Comment by temanteleary** [comment]
Closing this PR and approving/merging PR #11864.
