### ISSUE TITLE
Incorrect description of onboarding file

### ISSUE THREAD

**Issue by ALMSLabs** [MicrosoftDocs/microsoft-365-docs#11788]
[For MDE onboarding with SCCM, the file name and extension listed on the page does not match the file name in the downloaded ZIP file -  DeviceComplianceOnboardingScript.cmd vs DeviceCompliance.onboarding]
Please clarify/make necessary updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d0bace4-46dc-8b93-8731-71ad5e98e298
* Version Independent ID: 1d0bace4-46dc-8b93-8731-71ad5e98e298
* Content: [Onboard Windows 10 and Windows 11 devices using Configuration Manager - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-sccm?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/device-onboarding-sccm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/device-onboarding-sccm.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@ALMSLabs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11866

Once the author approves, the changes will be live.

Thanks
Sri
