### ISSUE TITLE
Dutch BSN filter triggers Dutch Chamber of Commerce number

### ISSUE THREAD

**Issue by jwmpap** [MicrosoftDocs/microsoft-365-docs#1179]
Business email needs to contain a 8 digit KvK (Dutch Chamber of Commerce) number.

Commonly used formatting of CoC-number in email signature is "KvK 012345678" or "KvK: 012345678" (without quotes).

This CoC-number triggers "Netherlands Citizen's Service (BSN) Number" filter, please adjust regex.

Email warning shows:
Your email message conflicts with a policy in your organization. Issues:
•	Message is sent to people outside your organization.
•	Message contains the following sensitive information: EU National Identification Number

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [What the sensitive information types look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for#feedback)
* Content Source: [microsoft-365/compliance/what-the-sensitive-information-types-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by jwmpap** [comment]
Maybe add this digit check to the BSN:
The Dutch Social Security Number or Personal Number (Burger Service Nummer, BSN) uses the modulo 11 algorithm (normally 9 characters, if 8 chars start add a 0 at the front): https://nl.wikipedia.org/wiki/Elfproef

**Comment by chrfox** [comment]
@jwmpap - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.
