### ISSUE TITLE
Graph API Access

### ISSUE THREAD

**Issue by davegreyuk** [MicrosoftDocs/microsoft-365-docs#11799]
Hi, are there any plans to allow this report data to be downloaded via Graph API's as per the other admin reports? This and Visio are currently missing but would be useful to have. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88b68222-3eac-0447-de7f-9b7ba70f1794
* Version Independent ID: 88b68222-3eac-0447-de7f-9b7ba70f1794
* Content: [Microsoft 365 admin center Project activity  - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/project-activity?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/project-activity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/project-activity.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@davegreyuk Thank you for your feedback. Currently, we do not have updates on when this will be available. However, you contact to leave your feedback on the main feedback page at https://feedbackportal.microsoft.com/- So that our dev or product engineers will be able to respond.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @davegreyuk Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
