### ISSUE TITLE
How retention works with OneNote content

### ISSUE THREAD

**Issue by kathleenlgo** [MicrosoftDocs/microsoft-365-docs#11796]
Hi,

Can you help to confirm the text below that is highlighted in yellow please?  When I tested on my machine, I see that only sections (not pages) are represented as individual files.

Also, please clarify if text that is highlighted in blue is correct or if it should be replaced by "each section within a notebook"?

<img width="433" alt="image" src="https://user-images.githubusercontent.com/22525477/233760363-cdd89962-d7ff-44c6-8fd1-f176f87e31ce.png">

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-retention-works-with-onenote-content)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Investigating

**Comment by cabailey** [comment]
@kathleenlgo  Yes, confirmed - it's sections only, not pages (confusing architecture!).  Thanks for flagging this, text now fixed.

**Comment by edmundhenley-mo** [comment]
Hi @cabailey - thanks for your text update - helpful to understand that sections act like files.
Could you consider a further text update for the paranoid please?
This to clarify whether or not adding/modifying a child page will update the modified date on the parent section.
I'd assume so - letting users apply a simple "sections are files" mental model.
But great to clarify given:
* the architecture already a little confusing, as you say!
* sections may be long-lived, so this apparent implementation detail may matter

**Comment by cabailey** [comment]
Yes, we're looking into adding a graphic to show the file relationship in OneNote if they haven't already published this.
