### ISSUE TITLE
Does this feature require an E5 license, or will this work with E3?

### ISSUE THREAD

**Issue by michaelblumenthal** [MicrosoftDocs/microsoft-365-docs#1180]
Does this feature require an E5 license, or will this work with E3?  Please indicate which licenses are required in order to use advanced eDiscovery reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 537e7055-af69-4127-7b3b-1d76796c6f40
* Version Independent ID: b2827f5d-bf44-474e-442e-22bc101e7681
* Content: [Advanced eDiscovery reports - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-ediscovery-reports)
* Content Source: [microsoft-365/compliance/advanced-ediscovery-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/advanced-ediscovery-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@michaelblumenthal All feature/functionality in Advanced eDiscovery requires E5 or E3 + Advanced Compliance add-on. Please see: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-tenantlevel-services-licensing-guidance#office-365-advanced-ediscovery or https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

**Comment by markjjo** [comment]
Re-posting the second URL from above as the URL changed since initial posting: 

https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#office-365-advanced-ediscovery
