### ISSUE TITLE
Clarity needed on Powershell version

### ISSUE THREAD

**Issue by therealtadda** [MicrosoftDocs/microsoft-365-docs#11804]
Please note clearly that while CAMP will install and run as a module under Powershell 7.3.4, that it cannot interoperate with ExchangeOnlineManagement 3.1.x in Powershell 7.3.4 (and one assumes all powershell 7.x versions)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ffc6641-5a0f-3b5b-49c4-50ee9c205f80
* Version Independent ID: 1a8feee1-b328-fbb9-6962-920e890f3ab7
* Content: [Configuration Analyzer for Microsoft Purview - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-mcca?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-manager-mcca.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-mcca.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by yogkumgit** [comment]
@chvukosw Please help us in resolving this issue. Thanks

**Comment by chvukosw** [comment]
This tool is no longer supported; article has been retired.
