### ISSUE TITLE
wrong role groups names

### ISSUE THREAD

**Issue by mhunecke** [MicrosoftDocs/microsoft-365-docs#11814]
****
Wrong name   --> Correct name
Attack Simulator Administrators --> Attack Simulation Administrators
Attack Simulator Payload Authors --> Attack Payload Authors

All the best.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Roles and role groups in Microsoft Defender for Office 365 and Microsoft Purview compliance - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/scc-permissions?view=o365-worldwide#relationship-of-members-roles-and-role-groups)
* Content Source: [microsoft-365/security/office-365-security/scc-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/scc-permissions.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mhunecke, fixed.

Thanks for the feedback.

Closing

**Comment by mhunecke** [comment]
Thank you.


Marcelo Hunecke
***@***.******@***.***>

[Microsoft Logo]

Você já conhece o M365 Apps Copilot? - Introducing Microsoft 365 Copilot - your copilot for work - The Official Microsoft Blog<https://blogs.microsoft.com/blog/2023/03/16/introducing-microsoft-365-copilot-your-copilot-for-work/>
