### ISSUE TITLE
This page is sending me round in circles. What I need is a big button that says "Press here". [WindowsServer2012R2]

### ISSUE THREAD

**Issue by iamthefaker** [MicrosoftDocs/microsoft-365-docs#11815]
[Enter feedback here]
This page is sending me round in circles.
What I need is a big button that says "Press here"
[WindowsServer2012R2]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#update-packages-for-microsoft-defender-for-endpoint-on-windows-server-2012-r2-and-2016)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@iamthefaker Thank you for your feedback. Looks like you may need technical assistance, I'd recommend you contact support via the need help section on the admin center so that our support engineer can assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @iamthefaker Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
