### ISSUE TITLE
Create rules notifications URL Broke

### ISSUE THREAD

**Issue by cybernerd2014** [MicrosoftDocs/microsoft-365-docs#11811]
URL "Create rules notifications " Link on this page is broke.
(https://github.com/MicrosoftDocs/microsoft-365-docs/tree/public/microsoft-365/security/defender-endpoint)/configure-mssp-notifications.md

**Comment by msbemba** [comment]
@cybernerd2014 Thank you for your feedback. There seems to be an extra  ")" in the URL. I'm able to open the document without the same - https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-mssp-notifications.md

Could you also provide the actual link of the page which contains this broken link?

Thanks
Sri
