### ISSUE TITLE
Customer Key Subscription placement in Enterprise Scale

### ISSUE THREAD

**Issue by SebastianPiendl** [MicrosoftDocs/microsoft-365-docs#11812]
Could you please add in which Management Group should the customer key subscriptions be placed?
https://github.com/Azure/Enterprise-Scale

**Comment by yogkumgit** [comment]
@SebastianPiendl Please indicate which document you are referring to and what is your feedback. Thanks

**Comment by SebastianPiendl** [comment]
@yogkumgit Here you can find the Customer Key documentation https://learn.microsoft.com/en-us/microsoft-365/compliance/customer-key-overview?view=o365-worldwide

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@SebastianPiendl Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
