### ISSUE TITLE
Precedence scenario clarification: broad destruction policy vs. default library label?

### ISSUE THREAD

**Issue by dsnyder99** [MicrosoftDocs/microsoft-365-docs#1181]
Would a destruction policy applied to all SharePoint sites and a default destruction label applied to a document library be considered equally "implicit", with the shorter destruction period winning? Or would the default destruction label be considered more explicit and thus win before the question of length of destruction was asked? This is a common scenario in my experience (looking to "except" a particular document library from a destruction policy by extending the destruction period) and I think it should be included in the examples. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels#feedback)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by chvukosw** [comment]
Thanks for your comment - this will be brought up with the engineering team.

**Comment by chvukosw** [comment]
Hello - Shorter time period doesn't necessarily "win." Your scenario is a common one that you can do if you want to create an exception to a wider retention policy by setting a further-out retention date for certain libraries with retention labels or record labels. The labels that you apply will then take precedence. Thanks for noting this; we will add more common use scenarios to our documentation in future updates.
