### ISSUE TITLE
Typo on page, "Sstructured"

### ISSUE THREAD

**Issue by storyid** [MicrosoftDocs/microsoft-365-docs#11828]
See title, there's a typo on the page, search for "Sstructured" and you'll find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8634c11c-7366-8fc6-9a62-4118e7408506
* Version Independent ID: 8634c11c-7366-8fc6-9a62-4118e7408506
* Content: [Run a trial of Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/trial-syntex?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/syntex/trial-syntex.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/trial-syntex.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@storyid -- Good catch, thank you! It's been fixed and is in the queue for republishing. Thanks so much.
