### ISSUE TITLE
DMARC Handling and Roadmap Item 117533

### ISSUE THREAD

**Issue by dataCollegechurch** [MicrosoftDocs/microsoft-365-docs#11826]
How is this section changing "How Microsoft 365 handles outbound email that fails DMARC" now that this item on the roadmap is being implemented: `https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=1&searchterms=117533&filters=&searchterms=117533`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email, setup steps - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-dmarc-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/email-authentication-dmarc-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/email-authentication-dmarc-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@dataCollegechurch Thank you for your feedback. Currently, we do not have more information on what is changing on Roadmap Item 117533. However, Once it is closer to going live,  the PM team will update the document if need be.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dataCollegechurch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kundan254** [comment]
Is this still being rolled out, as i do not see any changes to my tenant.
