### ISSUE TITLE
Files shared with Anyone sometimes prompt users to login 

### ISSUE THREAD

**Issue by Jarajesh** [MicrosoftDocs/microsoft-365-docs#11825]
I regularly share files using the "share with anyone, doesn't require sign-in"  option.

If I share to 10 users 3 of them get back to me saying its asking to sign in.

I have followed the methods mentioned in this page.

Not sure if this is a bug  or this page needs updating.

There is thread opened in 2019 with the same issue still not fixed so hopefully a onedrive issue.
https://techcommunity.microsoft.com/t5/onedrive-for-business/files-shared-with-anyone-sometimes-prompt-users-to-request/m-p/308153/page/3
https://www.reddit.com/r/sysadmin/comments/9spgsj/external_sharing_with_onedrive/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1b12dd3-e62d-a7ff-c597-9588cf6f1a23
* Version Independent ID: 231efccb-cfad-cf42-bd45-48bbcb2958d9
* Content: [Best practices for unauthenticated sharing](https://learn.microsoft.com/en-us/microsoft-365/solutions/best-practices-anonymous-sharing?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/best-practices-anonymous-sharing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/best-practices-anonymous-sharing.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Jarajesh Thank you for your feedback. This looks like a bug in the tenant, I'd recommend you contacting support via the need help section on the admin center, so that the support engineer can fix this or raise a bug with the concerned team to fix it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Jarajesh Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
