### ISSUE TITLE
Ambiguity on the information provided. Or a Typo

### ISSUE THREAD

**Issue by alisalih1** [MicrosoftDocs/microsoft-365-docs#11827]
Ambiguity in the documentation. This might be due to a Typo. Under the size limit, there is a 2TB content max, but in the "Important" section, it says 2GB. 

Page: https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-onedrive-migration?view=o365-worldwide#onedrive-account-size-limits

Thanks.

**Comment by msbemba** [comment]
@alisalih1 Thank you for your feedback. The size limit is indeed 2TB. However, If you attempt to migrate any OneDrive site that exceeds the 2GB quota, the transfer will fail.

We hope to increase those limits in the future to ensure larger OneDrive accounts can be migrated via the process.

Hope this helps!

Thanks
Sri

**Comment by alisalih1** [comment]
> @alisalih1 Thank you for your feedback. The size limit is indeed 2TB. However, If you attempt to migrate any OneDrive site that exceeds the 2GB quota, the transfer will fail.
> 
> We hope to increase those limits in the future to ensure larger OneDrive accounts can be migrated via the process.
> 
> Hope this helps!
> 
> Thanks Sri

May be additional information like you explained should be added to clarify that. I appreciate the explanation. Thanks Sri.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@alisalih1 Looks like the limit to migration is 2TB. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11874

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by alisalih1** [comment]
Fantastic! Thank you! Closing this Issue then.
