### ISSUE TITLE
I am trying to alert MS of possible phishing spam but Do Not have any MS products.  How To?

### ISSUE THREAD

**Issue by user211120** [MicrosoftDocs/microsoft-365-docs#11838]
I am trying to alert MS of possible phishing spam but Do Not Have any MS products.  How To? Txn, Jim (I'm new at this)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc4f577-32e6-7164-6b97-ac4aede3a9af
* Version Independent ID: 6dc4f577-32e6-7164-6b97-ac4aede3a9af
* Content: [Report spam, non-spam, phishing, suspicious emails and files to Microsoft - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by v-ratulach** [comment]
Hello @user211120 : Can you please provide some specific information? You said you don't have any MS products, does that mean you don't have Outlook? Are you asking as an admin or as an end user?

**Comment by msbemba** [comment]
@user211120  Thank you for your feedback. You can report Spam by choosing one of the ways mentioned in the link.

https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/phishing?view=o365-worldwide#reporting-spam

Hope this helps!

Thanks
Sri

**Comment by user211120** [comment]
Thank you, Jim

------------------------------------------------------------------------
*From:* Sriraman M S ***@***.***
*Sent:* Thursday, May 4, 2023 at 7:21 AM
*To:* MicrosoftDocs/microsoft-365-docs
*Cc:* user211120; Mention
*Subject:* [MicrosoftDocs/microsoft-365-docs] I am trying to alert MS of 
possible phishing spam but Do Not have any MS products. How To? (Issue 
#11838)

**Comment by v-ratulach** [comment]
Closing this issue as there's no need for any documentation update.
