### ISSUE TITLE
Training Reminder notification received even after completion of training

### ISSUE THREAD

**Issue by v0lck3r** [MicrosoftDocs/microsoft-365-docs#11843]
Hello Team,

While launching a simulation compaign, some users completed all the assigned trainings however they still receive the training reminder. I didn't find an option to control this behavior in attack simulator. Is this expected ?
Please advise

**Comment by denisebmsft** [comment]
Hello @v0lck3r. Can you please tell us to which article your feedback applies? This information will help us route the issue to the appropriate writer/team.

**Comment by v0lck3r** [comment]
Hello @denisebmsft, my question is related to Microsoft Attack Simulator https://security.microsoft.com/attacksimulator

**Comment by chrisda** [comment]
Checking

**Comment by richa-b23** [comment]
Hi @v0lck3r Thank you for raising the issue. This issue has been fixed. 
cc: @chrisda
