### ISSUE TITLE
Process does not take into consideration SSRP

### ISSUE THREAD

**Issue by troyradtke** [MicrosoftDocs/microsoft-365-docs#11849]
An employee that is scoped into SSPR can simply reset the password using standard recovery methods for a forgotten password.  The current MFA setup needs to be removed to prevent recovery after the password is changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @troyradtke Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
