### ISSUE TITLE
Feedback signatures

### ISSUE THREAD

**Issue by WardenHub** [MicrosoftDocs/microsoft-365-docs#11846]
Absurd that default signature cannot be set (as signature is setup by user) but instead you have to use an appending rule to e-mails.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a984a46-1f7b-6ef1-71f3-c5df6c142c01
* Version Independent ID: 4fab7da3-c9ae-0136-c693-ae99c1090f40
* Content: [Create organization-wide signatures and disclaimers - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/create-signatures-and-disclaimers?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/create-signatures-and-disclaimers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/create-signatures-and-disclaimers.md)
* Service: **microsoft-365-business**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@WardenHub Thank you for your feedback. Since this is a feature request, I'd recommend you post the feedback on our main feedback portal ( https://feedbackportal.microsoft.com/) so that our dec or product engineer will be able to respond.


Hope this helps!

Thanks
Sri
