### ISSUE TITLE
Unclear which "methods" are separate methods in "Post installation configuration"

### ISSUE THREAD

**Issue by birdmn** [MicrosoftDocs/microsoft-365-docs#11847]
[Enter feedback here]
Section "Post installation configuration" states the following:
"After installation, configure Defender for Endpoint with static proxy **using one of the following methods**:"
but it is hard to distinguish the different methods from each other. Clear listing "Method 1., Method 2." or bullets would make it clear which method is which.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd891b7a-0d7d-db48-fb16-9b48fe755fb9
* Version Independent ID: e868eeaf-780d-f64d-6ba9-73fca8ca03d9
* Content: [Microsoft Defender for Endpoint on Linux static proxy discovery](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-static-proxy-configuration.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@birdmn Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11901

Once the author approves, the changes will be live.

Thanks
Sri
