### ISSUE TITLE
"BULK" is being flagged on emails sent to a single recipient

### ISSUE THREAD

**Issue by FluidNets-DamianS** [MicrosoftDocs/microsoft-365-docs#11840]
Similar to issue: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7546

 I can understand actual bulk email "email with more than x recipients" being flagged as bulk. However, this new algorithm now defaults "bulk" when a user sends a single email to another email. a single email should never be flagged as "bulk". Bulk should never be applied below 15 recipients.
 
 This is impacting me as well as my clients ability to communicate with clients on legitimate business transactions.

**Comment by FluidNets-DamianS** [comment]
I just got off the phone with support who has stated this is a "known issue" and affecting thousands of users.  I was told they have reported this to product development but have not heard back yet.  This is a legal issue as Microsoft is preventing paying customers from doing business due to a glitch and there seems know way to get anyone from Microsoft to actually respond.  I am advising all of my clients to contact legal counsel since there appears to be no other way to resolve.

**Comment by msbemba** [comment]
@FluidNets-DamianS Thank you for your feedback. You have done the right thing by contacting support. That is the only way to be able to report a product bug. We at the documentation team do not have access to report bugs. 

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.
