### ISSUE TITLE
Win Server 2022 docs isn't up to date on download package

### ISSUE THREAD

**Issue by skjensen** [MicrosoftDocs/microsoft-365-docs#11850]
The description for how to onboard Windows Server 2022 documentation isn't up to date on this page: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#windows-server-semi-annual-enterprise-channel-sac-windows-server-2019-and-windows-server-2022

From the page: 
**Download package**
1. In Microsoft 365 Defender, go to Settings > Device Management > Onboarding.
2. Select Windows Server 1803 and 2019.
3. Select Download package. Save it as WindowsDefenderATPOnboardingPackage.zip.
4. Follow the steps provided in the [Complete the onboarding steps](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#step-3-complete-the-onboarding-steps) section.

On https://security.microsoft.com/ You can go to Settings, but you see the options in the attached screenshot, not the option to select "Device Management" as stated in the documentation. Clicking Endpoint brings you to a new page, where a section in the menu is called Device Management, and it got the menu item Onboarding, from where you can download the onboarding package. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@skjensen Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11902

Once the author approves, the changes will be live.

Thanks
Sri
