### ISSUE TITLE
Consider moving to the SharePoint content set

### ISSUE THREAD

**Issue by tomresing** [MicrosoftDocs/microsoft-365-docs#1185]
This article's intent is fairly well scoped to SharePoint. And, there doesn't seem to be an article in the SharePoint admin set covering this intent. Consider moving it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b270c9f7-c829-a6ac-0390-59d43d87a2e8
* Version Independent ID: 8a03f50c-78c4-75cf-7117-b27fbda09d3f
* Content: [Create and apply information management policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-info-mgmt-policies#feedback)
* Content Source: [microsoft-365/compliance/create-info-mgmt-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-info-mgmt-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@tomresing - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by MSFTTracyP** [comment]
@tomresing Compliance articles cover a wide variety of technologies, SharePoint among them. Please feel free to surface a link in the SharePoint TOC to this document in the meantime. But for more information, please come to me directly. I'm happy to work with you!
