### ISSUE TITLE
Directions are out of date

### ISSUE THREAD

**Issue by RGrizzzz** [MicrosoftDocs/microsoft-365-docs#11851]
Customer feedback is telling they're dissatisfied with this article, as .NET core 3.1 has been out of support for nearly 6 months. Please update with supported versions of API, and any relevant changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@RGrizzzz Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
