### ISSUE TITLE
Impact of changing the tenant name is understated.  Can you explain it more completely?

### ISSUE THREAD

**Issue by michaelblumenthal** [MicrosoftDocs/microsoft-365-docs#11856]
I've spent parts of the last several months looking at where the tenant display name is used. 
You don't mention that the tenant name shows up in Microsoft Authenticator and in the File Open & File save dialogs in Word, Excel, and PowerPoint desktop apps and in some screens in all the M365 mobile apps. 
Only Teams updates automatically, all the other client experiences do not.  There is a script available to trigger the update in some of the M365 desktop apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ecea09f5-957a-4674-0449-def4a1de21a4
* Version Independent ID: 53c2bbeb-daf8-56cd-f821-aa6e7e2fee92
* Content: [Change your organization's address, technical contact, and more - Microsoft 365 admin](https://learn.microsoft.com/en-US/microsoft-365/admin/manage/change-address-contact-and-more?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/change-address-contact-and-more.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/change-address-contact-and-more.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by DMoenks** [comment]
I second this request. A more complete and detailed overview of affected locations and possible end-user impacts when changing organization details would be desirable, especially when it comes to the organization name.

When migrating to Microsoft cloud services some years ago, we specified our HQ company's name as the display name for the tenant, which doesn't really represent the current situation after numerous subsidiaries joined in and the commonly used names now more and more refer to the company group as a whole.
If changing the display name would just leave existing users stuck with the previous name until they switch to new devices over the next few years, we'd be totally fine with that. We just want to make sure it doesn't break anything from a technical perspective.

Updating the documentation with more detailed up- and downsides of changing those settings would allow customers to better decide for or against doing so.

**Comment by michaelblumenthal** [comment]
I have a PowerPoint deck which I've been using internally at my employer to document and communicate about all the places affected by changing the tenant name.  I will try to clean it up and share it in the next few days.  I can also be reached on LinkedIn (http://bit.ly/MBB-LI) for a discussion of this issue or if I need to be reminded to share the deck.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us in resolving this issue. Thanks

**Comment by michaelblumenthal** [comment]
The PPTX deck I wanted to share has a lot of corporate branding on it, so I don't want to share it publicly. 
However, here are some key points:
Both employees and vendors/partners/customers/AAD Guests see the company name in various experiences. These can include:
Microsoft Authenticator prompts
Office desktop apps File Open and File Save dialogs.
Power Automate workspace names
OneNote default notebook for a new user
Mobile apps including OneDrive, Teams, and the M365 App, as well as error messages about sign-in to AAD on mobile devices.
OneDrive Sync's Blue Office Building sync in Windows File Explorer is going away eventually (in favor of adding links to SPO folders so SPO folder sync happens under OneDrive's Blue Cloud icon instead), However, for those orgs that have SPO sync users today, the tenant rename experience is bad - users don't pick up the update until they sync a new folder and then they end up with two different Blue Office Buildings for the same org. Remediating that at scale is very challenging at best.

**Comment by cmcatee-MSFT** [comment]
@michaelblumenthal Thanks for the feedback! Would you be able to suggest the changes directly in the article and submit a PR to me? That would be the quickest way to get updates made to this article.

**Comment by michaelblumenthal** [comment]
@cmcatee-MSFT , do you have time to teach me how to do a PR?  Although I used to be a SharePoint developer, I've been in M365 service admin roles (aka IT Pro roles) for the last 6+ years and no longer know my way around Visual Studio nor how to do anything in GitHub other than open an issue.

**Comment by yogkumgit** [comment]
@michaelblumenthal Please check - https://www.microsoft.com/videoplayer/embed/RE1XQTG

**Comment by michaelblumenthal** [comment]
@yogkumgit shouldn't you wait until I actually submit my edits before you close this issue?

@yogkumgit , @cmcatee-MSFT is there a style guide I should be mindful of as I make my edits?

**Comment by cimares** [comment]
@michaelblumenthal - It's also very visible in places like the Defender for Cloud Apps.. I did some testing for another client that had a legal requirement to remove all instances of their old owner and they ended up building a new tenant and migrating in the end. I'll see fi I can find the docs I wrote and share them with you.

**Comment by michaelblumenthal** [comment]
I've been making edits in my forked repository once a week over the last few weeks. I am getting closer to being ready to make the pull request.

**Comment by michaelblumenthal** [comment]
I created PR 12392.

**Comment by michaelblumenthal** [comment]
@cimares once my PR gets merged, please fork it and add your content about Defender for cloud apps.

**Comment by yogkumgit** [comment]
#12392
