### ISSUE TITLE
Adding NetRange for MSFT | 20.33.0.0 - 20.128.255.255

### ISSUE THREAD

**Issue by enigmanet** [MicrosoftDocs/microsoft-365-docs#11852]
I noticed that the IP address 20.96.219.x is missing from the list  This IP address belongs to MSFT and is part of their network.
Could you please add the following NetRange and CIDR to the list IP ranges please.

NetRange: 20.96.0.0 - 20.111.255.255
CIDR: 20.96.0.0/11

NetRange:       20.33.0.0 - 20.128.255.255
CIDR:           20.33.0.0/16, 20.128.0.0/16, 20.64.0.0/10, 20.40.0.0/13, 20.36.0.0/14, 20.48.0.0/12, 20.34.0.0/15
NetName:        MSFT
NetHandle:      NET-20-33-0-0-1
Parent:         NET20 (NET-20-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       
Organization:   Microsoft Corporation (MSFT)
RegDate:        2017-10-18
Updated:        2021-12-14
Ref:            https://rdap.arin.net/registry/ip/20.33.0.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks
