### ISSUE TITLE
The link to "Download SharePoint Online Management Shell from Official Microsoft Download Center" is 404

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/microsoft-365-docs#11867]
Trying to use the instructions here to migrate from tenant to tenant but the link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f025da8-8287-f98b-2167-5af04cabb254
* Version Independent ID: 7f025da8-8287-f98b-2167-5af04cabb254
* Content: [Cross-tenant SharePoint site migration overview (preview) - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-sharepoint-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-sharepoint-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-sharepoint-migration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by msbemba** [comment]
@Ofer-Gal Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11903

Once the author approves, the changes will be live.

Thanks
Sri
