### ISSUE TITLE
This page needs update

### ISSUE THREAD

**Issue by Tosue** [MicrosoftDocs/microsoft-365-docs#1186]
There are new attack types available not discussed in this page, and it also lacks information about results of attacks, reports, post-attack tasks, and user experience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbdcbd5-7bd2-6b55-b72c-cbedfdea776c
* Version Independent ID: 1e6198f8-6ef1-6227-c9e8-f31944a5d1db
* Content: [Attack Simulator in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator#feedback)
* Content Source: [microsoft-365/security/office-365-security/attack-simulator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by joinimran** [comment]
@Tosue Thank you for your feedback. If there is any information you have that needs to be added it the document please do share so that we can update the document with more relevant and updated information. 

Thanks.
Imran.

**Comment by mypil** [comment]
@Tosue   - Can you please respond to the query of joinimran?

Thank you.

**Comment by Tosue** [comment]
Sorry I see attacks are covered, but there is no information on the results of attacks, reports, post-attack tasks, and user experience

**Comment by chrisda** [comment]
Massive updates were made to this topic. They're under review now.

**Comment by chrisda** [comment]
Updated topic is live.

Closing
