### ISSUE TITLE
Instructions broken from step 1

### ISSUE THREAD

**Issue by rharrison-MAC** [MicrosoftDocs/microsoft-365-docs#11876]
From step 1, these instructions did not work for me.  I was not allowed to choose a calendar, but assigned directly to my own calendar.  In step 3, there was no left navigation pane to click anything in.  I do not see any publish options.  Either one needs admin privileges to do this kind of customization on a booking page, or there is a disconnect between this page and the current product.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93b5cf44-bd31-017e-c70f-62cc26ae42ea
* Version Independent ID: 26f5a25f-c80b-0d09-f6c3-6cfc97b31988
* Content: [Customize and publish your booking page](https://learn.microsoft.com/en-us/microsoft-365/bookings/customize-booking-page?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/customize-booking-page.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/customize-booking-page.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@rharrison-MAC Thank you for your feedback. I tested it now and looks like it works as described in the product page

![image](https://user-images.githubusercontent.com/45987684/236390721-36dd390a-bf42-4642-b964-2f1e556ba22c.png)


If you continue to have issues, I'd recommend you contact support via the need help section on the admin center, so that our support engineer can fix this for you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rharrison-MAC Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
