### ISSUE TITLE
Removing messages from OME

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#1188]
Hi! How can we remove messages from OME-hosting servers, for example if customer request us to stop processing their data? Is there any way to delete messages so they are no longer available from the browser?

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Office 365 Message Encryption FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/pl-pl/microsoft-365/compliance/ome-faq#what-subscriptions-do-i-need-to-use-the-new-ome-capabilities)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by MaratMussabekov** [comment]
Hello, it is possible for [Advanced Message Encryption](https://docs.microsoft.com/en-us/microsoft-365/compliance/revoke-ome-encrypted-mail) only
Thank you

**Comment by mypil** [comment]
@Larryngolog - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov  so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
