### ISSUE TITLE
Incorrect Statement Regarding F SKUs and Phone System

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/microsoft-365-docs#11883]
This line regarding Phone System (and the associated table) appears to be incorrect:

"However, they won't be able to create live events and webinars or use Teams Phone capabilities."

You can add the Phone System add-on to F SKUs.  If the intent is to imply that it's not included but available as an add-on, then the table column labeled "E3/E5" is inaccurate as only E5 includes Phone System.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a66e2933-c8de-0ae5-c6a4-bb83d7152b56
* Version Independent ID: a66e2933-c8de-0ae5-c6a4-bb83d7152b56
* Content: [Changing from a Microsoft 365 E plan to a Microsoft 365 F plan - Microsoft 365 for frontline workers](https://learn.microsoft.com/en-us/microsoft-365/frontline/switch-from-enterprise-to-frontline?view=o365-worldwide#teams)
* Content Source: [microsoft-365/frontline/switch-from-enterprise-to-frontline.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/frontline/switch-from-enterprise-to-frontline.md)
* Service: **microsoft-365-frontline**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by samanro** [comment]
Thanks for bringing this to our attention. I am updating the line to say "However, they won't be able to create live events and webinars or use Teams Phone capabilities without the purchase of additional add-ons."

**Comment by samanro** [comment]
Article has been updated: https://learn.microsoft.com/en-us/microsoft-365/frontline/switch-from-enterprise-to-frontline?view=o365-worldwide
