### ISSUE TITLE
Corn instead of Cron

### ISSUE THREAD

**Issue by jeremy-hagan** [MicrosoftDocs/microsoft-365-docs#11890]
[Enter feedback here]

Search for Corn. You'll find it.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c88857c-131f-ca74-10db-29835c2e486c
* Version Independent ID: 5c88857c-131f-ca74-10db-29835c2e486c
* Content: [How to schedule an antivirus scan using Anacron in Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/schedule-antivirus-scan-in-mde?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/schedule-antivirus-scan-in-mde.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/schedule-antivirus-scan-in-mde.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jeremy-hagan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11920

Once the author approves, the changes will be live.

Thanks
Sri
