### ISSUE TITLE
Microsoft quaranting Planner emails

### ISSUE THREAD

**Issue by emilylait** [MicrosoftDocs/microsoft-365-docs#11899]
Hi there, recently had a customer support ticket around Planner emails being quarantined by Microsoft systems (i.e. Microsoft stopping Microsoft). The fix was to add the Microsoft Planner emails to the trusted sender list. Customer asked this feedback to be provided - and perhaps have the documentation updated to show that even some Microsoft apps might need to be added (would have thought they would have always been considered safe as it's from Microsoft). Can any comments be added to doco about adding Microsoft services to trusted senders or something alike?
Thank you
Em

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-policies-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-policies-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-policies-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by emilylait** [comment]
Hi Chris

Sure - have some details from customer below in regards to the questions (highlighted below):

*            What are the messages being detected as? Impersonation? Spoof? I would guess impersonation.
Impersonation - the CIO is on the user impersonation protection list
*            What mail address (es) are we talking about?
***@***.******@***.***>
The following article contains as similar call-out about internal Microsoft messages tripping impersonation protection:
https://learn.microsoft.com/microsoft-365/security/office-365-security/anti-phishing-policies-mdo-configure#use-the-microsoft-365-defender-portal-to-create-anti-phishing-policies
[!TIP]
If Microsoft 365 system messages from the following senders are identified as impersonation attempts, you can add the senders to the trusted senders list:
*            ***@***.******@***.***>
*            ***@***.******@***.***>
*            ***@***.******@***.***>
Good callout - I would suggest they add ***@***.******@***.***>... Or just apply the logic to do that internally if they know it would cause the issue?

Thank you
Em

Emily Lait (she/her)
Account Technology Strategist
Higher Education, Microsoft
Level 28, 400 George Street
Brisbane QLD 4000 Australia
Phone:  +61 7 3291 6417
Mobile:  +61 408 253 049
***@***.******@***.***>
Visit Microsoft Higher Education<https://www.microsoft.com/en-au/education/higher-education>

***@***.***


We work flexibly at Microsoft. If you receive an email from me outside normal business hours, I am sending it at a time
that is convenient for me. I'm not expecting you to read or reply until your normal business hours.

Our mission is to empower every person and every organization on the planet to achieve more.


Upcoming leave: 22nd May  - 16th June 2023

**Comment by chrisda** [comment]
@emilylait, check out your response: all of the email addresses were asterisk-ed out.

You are more than welcome to add the required email address in the topic at that content location I suggested. It's super-easy and is described [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md). Just @ include me in the comments so I'll see it.

**Comment by emilylait** [comment]
Hi Chris

I have done that change by adding the planner email address 😊.

Apologies I just realised I forgot to add a comment to you, wasn’t too sure how to do that haha.

Thank you heaps
Em

Emily Lait (she/her)
Account Technology Strategist
Higher Education, Microsoft
Level 28, 400 George Street
Brisbane QLD 4000 Australia
Phone:  +61 7 3291 6417
Mobile:  +61 408 253 049
***@***.******@***.***>
Visit Microsoft Higher Education<https://www.microsoft.com/en-au/education/higher-education>

***@***.***


We work flexibly at Microsoft. If you receive an email from me outside normal business hours, I am sending it at a time
that is convenient for me. I’m not expecting you to read or reply until your normal business hours.

Our mission is to empower every person and every organization on the planet to achieve more.


Upcoming leave: 22nd May  – 16th June 2023
