### ISSUE TITLE
Quoting typo

### ISSUE THREAD

**Issue by bdanjoux** [MicrosoftDocs/microsoft-365-docs#11891]
In the Permissions section, there are some inconsistent quotes:

`<html><body>

Application | Machine.Read.All | ''Read all machine profiles''
Application | "Machine.ReadWrite.All | 'Read and write all machine information'
Delegated (work or school account) | Machine.LiveResponse | Run live response on a specific machine

</body>
</html>`

Should be

`<html><body>

Application | Machine.Read.All | Read all machine profiles
Application | Machine.ReadWrite.All | Read and write all machine information
Delegated (work or school account) | Machine.LiveResponse | Run live response on a specific machine

</body>
</html>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd8827-66cd-625d-a992-d42ec38ce0d6
* Version Independent ID: 67e04899-ef6e-20d3-8aec-d1765349bc32
* Content: [Get live response results](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-live-response-result?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-live-response-result.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-live-response-result.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@bdanjoux Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11921

Once the author approves, the changes will be live.

Thanks
Sri
