### ISSUE TITLE
Storage and retention limits for messages hosted in OME portal

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#1189]
What is the storage limit for messages hosted in OME portal and served to users through the browser? 
Is there a retention period after which messages hosted in OME portal are not available anymore?

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Office 365 Message Encryption FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/pl-pl/microsoft-365/compliance/ome-faq#what-subscriptions-do-i-need-to-use-the-new-ome-capabilities)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by MaratMussabekov** [comment]
Hello @Larryngolog,
there is no limits for storage, as for retention periods - could be configured only for external recipients, more details [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-advanced-expiration)
You can use New-OMEConfiguration/Set-OMEConfiguration commands to set it using PowerShell
Thank you

**Comment by Larryngolog** [comment]
Hello @MaratMussabekov thanks for answer.  Regarding the retention period this setting is for AME which requires E5. What about customers who only have E3 and only use OME?

**Comment by MaratMussabekov** [comment]
Hello @Larryngolog,
for OME there is no retention limit.  Messages are not stored on the portal, they are stored in recipient's mailbox, portal only allows to decrypt the message.
Thank you

**Comment by Larryngolog** [comment]
Correct me if I'm wrong, but since the OME portal is decrypting and displaying the message it need to have access to the message. And since recipient is an external person it cannot use their mailbox as a store for the message. My customers have experienced expiration of the messages in OME portal after about 2 months, but I have not seen it documented anywhere.

**Comment by MaratMussabekov** [comment]
Not sure this is correct. 
As far as I know, it uses Azure RMS for encryption, and it uses portal only for decrypting (portal authorizes the recipient), as it described [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome) and [here](https://support.office.com/en-us/article/how-do-i-open-a-protected-message-1157a286-8ecc-4b1e-ac43-2a608fbf3098?ui=en-US&rs=en-US&ad=US)
Thank you

**Comment by Larryngolog** [comment]
Ok, but for the users not using Outlook.com or Office 365 and Outlook app the portal not only authorizes them with the one time password but it also renders the mail on site https://outlook.office365.com/Encryption. It has to get the contents from somewhere and it's definitelly not recipients mailbox as it's completely out of Office 365 reach.

**Comment by MaratMussabekov** [comment]
Yes, I am not sure I am correct, as I have access only to publicly-accessible documentation (which doesn't contain any info about retention). However, a lot of people in the Internet talking about 60 days limit.
Dear @KCCross, could you please assist? Clarification about OME retention limits is required.
Thank you

**Comment by KCCross** [comment]
Forwarding to Samson - I believe the retention limit changed. Getting final #s.

**Comment by samschan-ms** [comment]
There is no retention limit for E3 or E5 customers.  the mail content are stored inside the sending organization's mailbox.

The E5 feature allows to set access expiration through the OME portal.  The mail is still resides in the organization after expiration.

**Comment by MaratMussabekov** [comment]
Hello,
as there are not retention limits, I believe no change is required for the article and the issue could be closed.
Dear @Larryngolog , what do you think?
Thank you

**Comment by yogkumgit** [comment]
@MaratMussabekov Thank you very much for the contribution and sharing this explanation. @Larryngolog Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
