### ISSUE TITLE
tampering ending troubleshooting mode?

### ISSUE THREAD

**Issue by BrechtMo** [MicrosoftDocs/microsoft-365-docs#11900]
It's not clear to me if I can completely disable tamper protection. It first hints at disabling tamper protection but later mentions that a tampering event will end troubleshooting mode altogether. Please elaborate.

During troubleshooting mode, you can use the PowerShell command Set-MPPreference -DisableTamperProtection $true or, on client operating systems, the Security Center app **to temporarily disable tamper protection** on your device and make your necessary configuration changes.

    Use troubleshooting mode to disable/change the tamper protection setting to perform:
        Microsoft Defender Antivirus functional troubleshooting /application compatibility (false positive application blocks).
        Microsoft Defender Antivirus performance troubleshooting by using the troubleshooting mode and manipulating tamper protection and other antivirus settings.

    **If a tampering event occurs** (for example, the MpPreference snapshot is altered or deleted), **troubleshooting mode will end** and tamper protection will be enabled on the device.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Version Independent ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Content: [Get started with troubleshooting mode in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@BrechtMo Thank you for your feedback. We have made changes to the document and removed the ambiguous statement via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11923

Once the author approves, the changes will be live.

Thanks
Sri
