### ISSUE TITLE
The Teams admin center usage report links are incorrectly redirecting to M365 admin center specific usage reports 

### ISSUE THREAD

**Issue by ivlists** [MicrosoftDocs/microsoft-365-docs#11908]
The links for Teams admin center specific usage reports are pointing to usage reports in M365 admin center. 

![image](https://user-images.githubusercontent.com/479153/236285530-9ceff814-3281-4659-ba88-31fc7ac4f1da.png)

For example, The link for Teams user activity report is pointing to M365 admin center specific Teams user activity report - https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft-teams-user-activity-preview?bc=%2Fmicrosoftteams%2Fbreadcrumb%2Ftoc.json&toc=%2Fmicrosoftteams%2Ftoc.json&view=o365-worldwide 

It should ideally point to Teams admin center specific Teams user activity report which is a separate MD file.

**Comment by msbemba** [comment]
@ivlists Thank you for your feedback. I don't see another MD file for the Teams admin center-specific Teams user activity report. This document does explain the team's user activity, etc.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ivlists Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
