### ISSUE TITLE
Missing '-' on InformationBarriersMode Set-SPOSite commands

### ISSUE THREAD

**Issue by tsalata** [MicrosoftDocs/microsoft-365-docs#11906]
There are two 'Set-SPOSite' commands on the page that are missing the '-' sign.

Issue 1:
`Set-SPOSite -Identity <siteurl> InformationBarriersMode OwnerModerated`
Should be:
`Set-SPOSite -Identity <siteurl> -InformationBarriersMode OwnerModerated`

Issue 2:
`Set-SPOSite -Identity <siteurl> InformationBarriersMode Mixed`
Should be:
`Set-SPOSite -Identity <siteurl> -InformationBarriersMode Mixed`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9e60884-b6b0-e11c-c1c2-e2a3eb5a580a
* Version Independent ID: c9e60884-b6b0-e11c-c1c2-e2a3eb5a580a
* Content: [Use information barriers with OneDrive - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/information-barriers-onedrive?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers-onedrive.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-onedrive.md)
* Service: **one-drive**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@tsalata Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11924

Once the author approves, the changes will be live.

Thanks
Sri
