### ISSUE TITLE
Mistake in Policy Conflict section

### ISSUE THREAD

**Issue by JustinCredible-** [MicrosoftDocs/microsoft-365-docs#11913]
Policy Conflict section step 2
Devices > Configuration policy >
should be Devices > Configuration profiles >

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide#intune)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@JustinCredible- Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11925
