### ISSUE TITLE
What is the Upper limit for Unlimited Archiving ?

### ISSUE THREAD

**Issue by Mohkam** [MicrosoftDocs/microsoft-365-docs#1191]
I guess in september 2019, “The unlimited archiving feature in Office 365 (called auto-expanding archiving) provides up to 1 TB of storage in archive mailboxes in Exchange Online.” as it still shows in https://docs.microsoft.com/zh-tw/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description#unlimited-archive-storage-quota

Is the upper limit still the same (1 TB) or its changed ?

**Comment by markjjo** [comment]
@Mohkam We've removed the reference to the 1 TB limit in the service descriptions. For example, here is the en-us version: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description#unlimited-archive-storage-quota
