### ISSUE TITLE
specific license is not called out for impersonation protection

### ISSUE THREAD

**Issue by Juhaugen** [MicrosoftDocs/microsoft-365-docs#11912]
[there is no specification which anti phishing features are a part of MDO p1 and MDO p2, only MDO and EOP.  could you please correct this or let me know if the impersonation protection is a part of p1 and p2 or just p2?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-policies-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-policies-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-policies-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Juhaugen, there are no differences between anti-phishing policies in Defender for Office 365 Plan 1 or Plan 2. The features are the same. Impersonation protection is available in anti-phishing policies in Plan 1 and Plan 2.

**Comment by Juhaugen** [comment]
Thank you Chris, it appears the blog I saw this in was updated when I was oof, thank you for confirming!

All the best,

***@***.***
***@***.***

Justin Haugen
Technical Specialist

Microsoft Fargo Campus
One Lone Tree Road | Fargo, ND 58104
Office 365 welcome kit please click here<https://onedrive.live.com/redir?resid=5A070F54C78D525C%21118998&authkey=%21AHfFxINh36VsM4I&page=View&wd=target%28Office%20365%2FO365.one%7Ca627888a-7146-4df4-abea-302b9f77e3d9%2FOffice%20365%7C679e4589-f17a-4f3a-a5f2-9b16e82e8e94%2F%29>
Microsoft Privacy Statement<http://go.microsoft.com/fwlink/?LinkId=81184>.

**Comment by chrisda** [comment]
@Juhaugen, thanks for the feedback.

Closing
