### ISSUE TITLE
Pointing out that default alerts are configured to have mail sent to tenantadmins group

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#11929]
I wonder if there is an opportunity to point out in tis article that default alerts are automatically sent to Tenantadmins and who that implies (Global Admins).

Have had feedback from customers that this isn't really clear and has caused some confusion. Many  global admin roles do not have email and default alerts can be missed.

Is this documented anywhere else if not in this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Microsoft 365 alert policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide#default-alert-policies)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11962

Once the author approves, the changes will be live.

Thanks
Sri
