### ISSUE TITLE
IPV6 Support

### ISSUE THREAD

**Issue by klikevil** [MicrosoftDocs/microsoft-365-docs#11933]
Is IPV6 supported for this?  The examples don't appear to include ipv6 addresses and when I was attempting to write an allow rule it kept throwing syntax errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9b787f-def1-bbc5-48ca-42180f9560d2
* Version Independent ID: 3d9b787f-def1-bbc5-48ca-42180f9560d2
* Content: [Allow or block email using the Tenant Allow/Block List - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@klikevil, I would say based on your experience that no, IPV6 addresses aren't supported.

**Comment by chrisda** [comment]
Closing due to lack of response.

Thanks for the feedback.
