### ISSUE TITLE
incorrect instructions

### ISSUE THREAD

**Issue by Jont-K** [MicrosoftDocs/microsoft-365-docs#1193]
To assign third-party apps

step 4 in the section " Assign Licenses " is incorrect. 
"Under Settings & actions, select the link to Manage in publisher’s portal."  no link called "Manage in PUblishers portal".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7cf7a2d-2bf1-c605-f3c6-299cb55efa89
* Version Independent ID: 550ec250-27de-0553-324e-f30efa48f034
* Content: [Manage software-as-a-service apps for your organization](https://docs.microsoft.com/en-us/microsoft-365/commerce/manage-saas-apps)
* Content Source: [microsoft-365/commerce/manage-saas-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/manage-saas-apps.md)
* Product: ****
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by MaratMussabekov** [comment]
Dear @TrudyHa,
could you please assist? I cannot check it myself, as third-party apps are not available in my region.
Also, could you please check #1292, it contains some fixes related to the same instructions.
Thank you

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @Jont-K Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
