### ISSUE TITLE
Duplicated content

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#11930]
There are 2 paragraphs with "Because Microsoft 365 Defender technologies span various functions" which are very similar. One of them should be removed or rewritten to eliminate redundant information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b92d260-ca15-0bdf-0d36-66ea6189f516
* Version Independent ID: 9c436392-f1b5-a66e-74a8-7a8b85347738
* Content: [Step 3. Plan for Microsoft 365 Defender integration with your SOC catalog of services](https://learn.microsoft.com/en-us/microsoft-365/security/defender/integrate-microsoft-365-defender-secops-services?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/integrate-microsoft-365-defender-secops-services.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/integrate-microsoft-365-defender-secops-services.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11963
