### ISSUE TITLE
PDF reader list is outdated - missing Adobe

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#11943]
This page does not list Adobe Acrobat Reader, as a compatible MIP encrypted PDF reader

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7da662e1-5ae5-7760-1321-26cd2bab997a
* Version Independent ID: 60319761-1406-6c06-1620-e1a484468879
* Content: [SharePoint-compatible PDF readers that support IRM services - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@gbms311 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11965

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@gbms311 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
