### ISSUE TITLE
"No address book policies" paragraph clarification

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#1194]
I am referring to article https://docs.microsoft.com/cs-cz/microsoft-365/compliance/information-barriers-policies#prerequisites.

Please clarify with Engineering if ABPs can be recreated after Information Barriers have been implemented or not. 

The message we are sending is not very clear because we are not saying that ABPs are not supported in conjunction with IBPs. We just say that they should be removed if they exist prior of implementing IBPs.

Going through some internal Engineering requests, I've seen that there is a long term plan to replace ABPs with IBPs in Exchange, and that there is also a conflict between the two, which explains the existence of the paragraph in question, in the article.

**Comment by chrfox** [comment]
Hi @Alex-Catalin 
No, you cannot have Exchange address book polices and Information Barrier policies implemented simultaneously.  Exchange ABP + Information Barrier polices = are not supported.
