### ISSUE TITLE
When deploying the add-ins centrally in O365, an App Registration in Azure is automatically created

### ISSUE THREAD

**Issue by ramonabadea** [MicrosoftDocs/microsoft-365-docs#11947]
Dear Microsoft, 

FYI: There is no point on the documentation about the fact that deploying the add-ins centrally in O365 will **automatically deploy an app registration in Azure.** 
If admins are not aware that the two are interdependent, we might delete the Azure app registration and the add-in will be deleted too.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
@ramonabadea, I added the following item to the existing Note in the [Admin instructions](https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure?view=o365-worldwide#admin-instructions) section:

> When you follow these instructions to centrally deploy the add-ins, a corresponding app registration is also deployed in Azure. If you delete the app registration for the add-in in Azure, the add-in is also deleted from the organization.

Feel free to improve it if you like. It's very easy and instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).
