### ISSUE TITLE
Please add the information of Viva Learning on [View a list of self-service purchase products and their status] 

### ISSUE THREAD

**Issue by M365SupportJapan** [MicrosoftDocs/microsoft-365-docs#11944]
[Enter feedback here]
Please add the information of Viva Learning on [View a list of self-service purchase products and their status] list.

Product: Viva Learning
ProductId: CFQ7TTC0HVZG

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**
![imagefor change](https://user-images.githubusercontent.com/42572415/236727563-1154fac3-50ed-4b4c-be39-53959abfecc8.png)

**Comment by msbemba** [comment]
@M365SupportJapan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11966

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by M365SupportJapan** [comment]
[like]  Mizuho Takahashi reacted to your message:
________________________________

**Comment by cmcatee-MSFT** [comment]
I spoke with the product team, and they don't want Viva Learning added to the list at this time.
