### ISSUE TITLE
What about the other Defender products?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#11957]
This article only provides guidance for working with MDE, what about MDO, MDI and MDCA? how should MSSPs work with alerts from those products in the M365 Security portal? please update this article to include guidance for providing complete coverage of the Defender suite

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a41826a-edba-15b1-5a4f-3bfc6676e52c
* Version Independent ID: 54c1d95d-7430-5bf5-8a88-40396298cbfd
* Content: [Provide managed security service provider (MSSP) access](https://learn.microsoft.com/en-us/microsoft-365/security/defender/mssp-access?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/mssp-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/mssp-access.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
See: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/access-mssp-portal?view=o365-worldwide
