### ISSUE TITLE
Retention - Stop/Disable

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#11956]
Hello,

It could be good if in document explained how to stop the retention policy, what is impact, and what is expected when the policy is stoped/the user is excluded or the policy is deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef663fdc-1776-3c73-7743-332796c284e6
* Version Independent ID: ceb29788-39be-8c30-b92a-7a22243ebe83
* Content: [Automatically retain or delete content by using retention policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide&tabs=teams-retention)
* Content Source: [microsoft-365/compliance/create-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @lightupdifire, yes, there's quite a bit to this so it's covered where we explain the other concepts about Microsoft 365 retention: https://learn.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#releasing-a-policy-for-retention
