### ISSUE TITLE
Azure B2B Option

### ISSUE THREAD

**Issue by iviikel1** [MicrosoftDocs/microsoft-365-docs#11953]
There are Microsoft posted videos from back in late October 2020 about this feature being in the works for Azure B2B guest accounts rather than just Microsoft Partners. Is that still in the works and is there an ETA for the feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b378de4-ca71-a16b-6669-369e3e3ff9d4
* Version Independent ID: 1a1a6ec6-8c04-2172-7afa-49d268191687
* Content: [Manage multiple tenants - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/multi-tenant/manage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/multi-tenant/manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/multi-tenant/manage.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@iviikel1 Thank you for your feedback. Unfortunately, it is not available yet. You can post your feedback on our main feedback (https://feedbackportal.microsoft.com/), so that our dev/engineering team can respond.

Hope this helps!

Thanks
Sri
