### ISSUE TITLE
The training link doesn't seem to bring to trainings page, instead redirects to Defender documentation top page

### ISSUE THREAD

**Issue by kuzmeech** [MicrosoftDocs/microsoft-365-docs#11951]
On page https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint?view=o365-worldwide the section "Training for security analysts" link initially leads to https://learn.microsoft.com/en-us/training/paths/defender-endpoint-fundamentals/ and then redirects to https://learn.microsoft.com/en-us/microsoft-365/security/defender/?view=o365-worldwide , not leading to the actual training.

**Comment by msbemba** [comment]
@kuzmeech Thank you for your feedback. The training module has been removed as it is no longer available, PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11967 has been created for the same

If you are looking at other training modules, you can find them here- https://learn.microsoft.com/en-us/users/collinschedler-0717/collections/3nrwbj15ggyjq5

Thanks
Sri
