### ISSUE TITLE
Clarify the assigned permissions required

### ISSUE THREAD

**Issue by AzureGuineaPig** [MicrosoftDocs/microsoft-365-docs#11952]
Within bullet-point 3 in the "What do you need to know before you begin?" section, please clarify the assigned permission requirements for the Azure AD RBAC section - which roles provide for Read only access to quarantined messages for all users and roles that provide ability to take action on quarantined messages for all users.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an admin - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files?view=o365-worldwide#what-do-you-need-to-know-before-you-begin)
* Content Source: [microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@AzureGuineaPig, anything with "Reader" in the role name gives read-only access (Global Reader/Security Reader). The other roles allow action (Global Administrator/Security Administrator).

Are you saying that's not clear, and the information needs to be split out like the explanation in the Exchange Online RBAC bullet?

**Comment by chrisda** [comment]
No response, so I clarified.

Thanks for the feedback.

Closing
