### ISSUE TITLE
Error on page https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-tags?view=o365-worldwide#add-device-tags-by-creating-a-custom-profile-in-microsoft-intune

### ISSUE THREAD

**Issue by amazing-mr-ed** [MicrosoftDocs/microsoft-365-docs#11955]
[Enter feedback here]
The paragraph:

For Windows 10 or later, in the [OMA-IRU settings](https://learn.microsoft.com/en-us/mem/intune/configuration/custom-settings-windows-10) section, for Data type, choose String. For Value, type (or paste) ./Device/Vendor/MSFT/WindowsAdvancedThreatProtection/DeviceTagging/Group.

Should read:

For Windows 10 or later, in the [OMA-IRU settings](https://learn.microsoft.com/en-us/mem/intune/configuration/custom-settings-windows-10) section, for Data type, choose String. For OMA-URI, type (or paste) ./Device/Vendor/MSFT/WindowsAdvancedThreatProtection/DeviceTagging/Group.

The Value should be the tag that you want to apply.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51c29286-b601-4dad-0e65-227c8d045ee4
* Version Independent ID: 2af4acf9-4089-5dff-d628-16b8425e0a57
* Content: [Create and manage device tags](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-tags?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine-tags.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine-tags.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@amazing-mr-ed Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11968

Once the author approves, the changes will be live.

Thanks
Sri
