### ISSUE TITLE
Fix your documentation to match changes made in your portal

### ISSUE THREAD

**Issue by jpsebasti** [MicrosoftDocs/microsoft-365-docs#11969]
Why can't you keep your documentation updated to changes made in the O365 Portal.
The info on how to turn on/off auditing talks about the Permissions page in the Exchange Admin.  If I go there the permissions page forces me back to the Admin Roles page.  

The documentation is wrong and should be updated correctly by a documentation specialist, not a software developer and it should be correct before the feature is released. 

Please don't send me another communication to request that the documentation be updated.  I expect that this feedback is sufficient to request that.  My time is important and I'm not going to make an additional request where I have to spend more of my time re-describing the issue again in some other form request.

I don't understand why the user experience always seems to be an afterthought to Microsoft.
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn auditing on or off - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-enable-disable?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-enable-disable.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-enable-disable.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@jpsebasti Thank you for your feedback. Sorry to hear that you are having trouble enabling Auditing. I followed the instructions in the document and was able to turn on Audtiting as decribed here

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/6e58fefb-f76b-49e3-89db-57f68c69e6fd)

Could you please elaborate on which link takes you to the permissions page in the Exchange admin center?

Hope this helps!

Thanks
Sri
