### ISSUE TITLE
Does EOP actually perform DKIM signing for on-prem mail servers

### ISSUE THREAD

**Issue by billvolt** [MicrosoftDocs/microsoft-365-docs#11972]
This page notes, "Applies to ... Exchange Online Protection."  EOP provides services for outbound mail sent from on-prem servers, including Exchange and others.

In my testing using the procedure documented here my outbound mail passed through EOP without having a DKIM signature added.

When I contacted Microsoft Support I was advised that EOP would not do this and I must apply DKIM signatures in my on-prem mail environment.  If this is an intended and supported function of Exchange Online Protection, please advise how best to escalate my open ticket.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-dkim-configure?view=o365-worldwide#on-premises-exchange-environments.)
* Content Source: [microsoft-365/security/office-365-security/email-authentication-dkim-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/email-authentication-dkim-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@billvolt Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11983

Once the author approves, the changes will be live.

Thanks
Sri
