### ISSUE TITLE
Outdated licensing information?

### ISSUE THREAD

**Issue by jhic** [MicrosoftDocs/microsoft-365-docs#11971]
This doc states that:

"The standalone versions of [Defender for Endpoint Plan 1 and Plan 2](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide), even when they're included as part of other Microsoft 365 plans, don't include server licenses. To onboard servers to those plans, you need either **Microsoft Defender for Endpoint for Servers** or Defender for Servers Plan 1 or Plan 2 as part of the [Defender for Cloud](https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-cloud-introduction) offering. To learn more, see [Defender for Endpoint onboarding Windows Server](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-server?view=o365-worldwide)."

I do not believe that Microsoft Defender for Endpoint for Servers is purchasable any longer. I believe the two options for Defender for Servers is only Defender for Cloud or Defender for Business servers. If anything, you may want to make a note that those MDE for Servers licenses are legacy only, even though they will continue to work. If I am not understanding something please let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide#licensing-requirements)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jhic Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/11984

Once the author approves, the changes will be live.

Thanks
Sri
