### ISSUE TITLE
defender service is failing to start, locale not supported

### ISSUE THREAD

**Issue by fierg** [MicrosoftDocs/microsoft-365-docs#11978]
Since today the defender service is failing to start:

```
Mai 11 08:26:36 user systemd[1]: Failed to start mdatp.service - Microsoft Defender.
Mai 11 08:26:36 user systemd[1]: mdatp.service: Failed with result 'core-dump'.
Mai 11 08:26:36 user systemd[1]: mdatp.service: Start request repeated too quickly.
Mai 11 08:26:36 user systemd[1]: Stopped mdatp.service - Microsoft Defender.
Mai 11 08:26:36 user systemd[1]: mdatp.service: Scheduled restart job, restart counter is at 3.
Mai 11 08:26:36 user systemd[1]: mdatp.service: Failed with result 'core-dump'.
Mai 11 08:26:34 user systemd[1]: mdatp.service: Main process exited, code=dumped, status=6/ABRT
Mai 11 08:26:33 user wdavdaemon[3760]: terminating with uncaught exception of type std::runtime_error: locale not supported
Mai 11 08:26:33 user wdavdaemon[3804]: avc:  could not determine enforcing mode: No such file or directory
Mai 11 08:26:33 user systemd[1]: Started mdatp.service - Microsoft Defender.
Mai 11 08:26:33 user systemd[1]: Stopped mdatp.service - Microsoft Defender.
Mai 11 08:26:33 user systemd[1]: mdatp.service: Scheduled restart job, restart counter is at 2.
Mai 11 08:26:33 user systemd[1]: mdatp.service: Failed with result 'core-dump'.
Mai 11 08:26:31 user wdavdaemon[2735]: avc:  could not determine enforcing mode: No such file or directory
Mai 11 08:26:28 user systemd[1]: mdatp.service: Main process exited, code=dumped, status=6/ABRT
Mai 11 08:26:26 user wdavdaemon[2692]: terminating with uncaught exception of type std::runtime_error: locale not supported
Mai 11 08:26:22 user systemd[1]: Started mdatp.service - Microsoft Defender.
Mai 11 08:26:22 user systemd[1]: Stopped mdatp.service - Microsoft Defender.
Mai 11 08:26:22 user systemd[1]: mdatp.service: Scheduled restart job, restart counter is at 1.
Mai 11 08:26:22 user systemd[1]: mdatp.service: Failed with result 'core-dump'.
```

my locale is set to `en_US.UTF-8`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@fierg Thank you for your feedback. This looks like a technical issue, I'd recommend you contacting support via the need help section on the admin center, so that our support engineer can work with you to fix this.

Hope this helps!

Thanks
Sri
