### ISSUE TITLE
Patch and Post differences

### ISSUE THREAD

**Issue by tonylanglet** [MicrosoftDocs/microsoft-365-docs#11999]
The HTTP request details is set to use PATCH as the web request method but in the example POST is being used. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45e02871-e257-cb19-c0e4-cee106705368
* Version Independent ID: b3a038cf-d812-d3f9-05b3-ed6a803311d5
* Content: [Add or remove a tag for a machine](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/add-or-remove-machine-tags?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/add-or-remove-machine-tags.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/add-or-remove-machine-tags.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@tonylanglet Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12015

Once the author approves, the changes will be live.

Thanks
Sri
