### ISSUE TITLE
So, this is not applicable to tenants that do not have an EA with MS? If you are a small tenant with commercial terms licenses without an EA or on a CSP with layers of middle people without an EA?

### ISSUE THREAD

**Issue by spahbedsuren** [MicrosoftDocs/microsoft-365-docs#11997]
So, this is not applicable to tenants that do not have an EA with MS? If you are a small tenant with commercial terms licenses without an EA or on a CSP with layers of middle people without an EA?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@spahbedsuren Thank you for your feedback. Yes, as of now, it is available only for EA customers and will be available for the commercial licenses soon.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @spahbedsuren Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
