### ISSUE TITLE
Guests users are not allowed to join this Unified Group due to policy setting while adding Guest users to AAD M365 group

### ISSUE THREAD

**Issue by ilantom** [MicrosoftDocs/microsoft-365-docs#11991]
I created M365 group in Microsoft tenant. 

I'm able to add a Guest user to this group manually via Azure Portal

On adding Guest users to this group using batch programmatically, I see this error:

```
Response - StatusCode:Forbidden - Content:{
"error": {
"code": "Authorization_RequestDenied",
"message": "Guests users are not allowed to join this Unified Group due to policy setting. paramName: Members, paramValue: , objectType: Microsoft.Online.DirectoryServices.Group",
}
}
```

Why is it behaving differently while using Graph API v/s via Azure Portal? What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e00be85-c1bd-bfd9-e09b-78fea811f864
* Version Independent ID: bdfb2aad-6aa8-76a8-46cf-1603f8255df4
* Content: [Prevent guests from being added to a specific group](https://learn.microsoft.com/en-us/microsoft-365/solutions/per-group-guest-access?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/per-group-guest-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/per-group-guest-access.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@ilantom Thank you for your feedback. This sounds like a bug and needs to be reported to the PM or PG, I'd recommend you raise a support ticket via the need help or contact the team internally to raise a product bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@ilantom Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
