### ISSUE TITLE
Activity Explorer - Clarify how the Office 365 Management Audit can be used

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/microsoft-365-docs#12002]
There are two issues:

I (and most users will) need to export more than 10k entries from the Purview Data Loss Prevention Activity Explorer. The message in the Activity Explorer is to use the Office 365 Management Activity API to perform the export. However, when exporting from the API a number of fields shown in the Activity Explorer are not available from the API e.g. Removable media device model is available in the Activity Explorer but seemingly not in the Office 365 Management Activity API. (It is definitely not in Record Type 63 for DLP activities) Where in the API are the missing fields? What is missing from the documentation is the 'how to construct the same data set' using the Office 365 Management Activity API. 

The other issue (which something for the page owner of https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference#list-available-content ) is that the date range filters are not working with the List Available Content API call (https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference#list-available-content ). The call is only returning data for the current day no matter how the filters are constructed. This means consumers cannot actually access the audit data say for the last 30-days or recreate the Activity Explorer data.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3d3633-893d-9354-9402-c47ed7dec790
* Version Independent ID: fc12340b-403f-b531-04be-91f00a8f0af6
* Content: [Get started with Activity explorer - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-activity-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-activity-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by buildbod** [comment]
Fixing the filtering issue (see (https://github.com/MicrosoftDocs/office-365-management-api/issues/367) ) has revealed that created on removable media is in the API (and part of DLPEndpoint)  However it is not in the Audit Search filter.

**Comment by buildbod** [comment]
![missing filter](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/13903544/f3e3d824-7e52-493a-8389-52be0c7b3943)

As a result you have to export all of the DLPEndpoint items and filter them outside of the audit. This is a significant undertaking when DLP is enabled as it results in very large exports...

**Comment by kmkoenen** [comment]
Investigating

**Comment by yogkumgit** [comment]
@buildbod Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
