### ISSUE TITLE
Avatars for Microsoft Teams URL ranges are not included in this document

### ISSUE THREAD

**Issue by akrupennikov** [MicrosoftDocs/microsoft-365-docs#12008]
Hello!

I got some customer feedback regarding the issue with Avatar feature funcitioning. According to this document (https://learn.microsoft.com/en-us/microsoftteams/meeting-avatars), Avatars require additional set of URLs to work properly. The customer allowed only what is included in Office 365 URLs and IP address ranges and was confused to find that it is not the only source of knowledge for O365-family products.

Would it be possible to enhance this document with Avatar URLs? It will bring a lot of clarity for this feature.
Thank you!

Best regards,
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@akrupennikov Thank you for your feedback. Please be aware that the [Office 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide) topic is autogenerated by an internal tool that engineering teams use to aggregate and validate endpoint data. It cannot be manually updated by writers. 
 Any updates or changes to the information have to be initiated by support through the M365 engineering teams and then pushed through that internal process & tool.

So if you feel the IPs and URLs are not updated, have the support engineer to escalate it to the engineering team.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @akrupennikov Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
