### ISSUE TITLE
Roles are not working

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/microsoft-365-docs#1200]
I have given a mail user the security reader role and the following roles in exchange:
Audit Logs
Mail Recipients
Mailbox Import Export
Mailbox Search
Message Tracking
Security Admin
User Options
View-Only Configuration
View-Only Recipients

under security & compliance -&gt; threat management -&gt; they only see review and policy why is explorer not showing up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and real-time detections, new to Threat Explorer, changes to Threat Explorer, new to Office 365, Security, Cloud Security, new to Security in ATP, new ATP features - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by mypil** [comment]
@SquirrelAssassin - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by SquirrelAssassin** [comment]
Something is not right, I had to give the use security administrator which is way to much permissions.  The end user had both security reader and view only recipients that met two of the requirements and from the documentation it only needs one.  There is something broken in permissions.    

To view and use Explorer or real-time detections, you must have appropriate permissions, such as those granted to a security administrator or security reader.

    For the Security & Compliance Center, you must have one of the following roles assigned:
        Organization Management
        Security Administrator (this can be assigned in the Azure Active Directory admin center (https://aad.portal.azure.com))
        Security Reader

    For Exchange Online, you must have one of the following roles assigned in either the Exchange admin center (https://outlook.office365.com/ecp) or with PowerShell cmdlets (See Exchange Online PowerShell):
        Organization Management
        View-only Organization Management
        View-Only Recipients role
        Compliance Management
