### ISSUE TITLE
Incorrect directions. 

### ISSUE THREAD

**Issue by ThompsonSolutions** [MicrosoftDocs/microsoft-365-docs#12004]
The following steps in the article do not follow the current layout of MS portal:
In the admin center, go to the Settings > Org Settings > Services page.

Select Reports.

Uncheck the statement Display concealed user, group, and site names in all reports, and then save your changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1eaa6e98-66e9-aad3-2d67-543c22f4ce4b
* Version Independent ID: 26bddf9e-f338-329f-76e5-302a1343f7f1
* Content: [Microsoft 365 admin center activity reports - Microsoft 365 admin](https://learn.microsoft.com/en-US/microsoft-365/admin/activity-reports/activity-reports?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide#show-user-details-in-the-reports)
* Content Source: [microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/activity-reports.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@ThompsonSolutions  Thank you for your feedback. the steps seem to be accurate

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/0ef0a68d-f3d1-4fce-aa0d-73fbb5e5bb9d)

Hope this helps!

Thanks
Sri
