### ISSUE TITLE
Vague documentation on licensing

### ISSUE THREAD

**Issue by benstegink** [MicrosoftDocs/microsoft-365-docs#12003]
The Documentation says "In organizations with Microsoft Defender for Office 365 Plan 2 (add-on licenses or included in subscriptions like Microsoft 365 E5), you can use Attack simulation training in the Microsoft 365 Defender portal..."

Does "you can use Attack simulation" mean that the person setting up and "using" the attack simulation services in Defender needs to have E5, but users that the phishing simulation attack is sent to can have any licenses? i.e. I can still send a simulated email to someone with a simple Exchange Plan 1 or Plan 2 license. Or does that mean that every user I send a simulated attack email to needs to have Plan 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59c87455-77af-093a-6fb6-286049aad15a
* Version Independent ID: b2690e98-781d-4a27-a9bc-bd621964feb0
* Content: [Get started using Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-get-started.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@benstegink, my guess is that from a technical standpoint, all you need is one Defender for Office 365 Plan 2 license in the entire organization (likely, for the admin setting it up as you described).

From a compliance/licensing perspective, anyone/everyone involved should be licensed for Defender for Office 365 Plan 2.

There are a few different Defender for Office 365 features that work that way.

**Comment by DMoenks** [comment]
According to the [licensing terms](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#licensing-terms), if one user is licensed for _Defender for Office 365 Plan 2_, **every** user must be licensed for it, which would somehow answer the initial question with "this scenario is non-compliant"

**Comment by benstegink** [comment]
@DMoenks, thanks that's the info I was looking for that explanation on this page where it talks about licensing might be nice as well.  "To use attack simulation, every user and shared mailbox must have a Microsoft Defender for Office 365 Plan 2". 

Because it also looks like not only every user, but every shared mailbox as well?! So if I have 100 shared mailbox and add a Defender for Office 365 Plan 2, I need to pay an extra $500/month for those shared mailboxes? Or having to keep track of short term shared mailboxes when a user leaves a company. I can under how this works for user, but also having to licenses shared mailboxes that were previously free as the fluidity that shared mailboxes can have in some companies...

**Comment by chrisda** [comment]
@benstegink, shared mailboxes don't require user licenses, so they shouldn't require licenses for MDO. It's more about the licensing of the users who use those shared mailboxes.

**Comment by benstegink** [comment]
@chrisda, that's always been my thought as well. I was just looking at the licensing terms @DMoenks referenced above and it has the below. Again, going back to the original issue of that it might be good to put some clarification into this. i.e. if all users need to be licensed, the bullet about Shared Mailboxes is just confusing b/c if it's that's user accessing the shared mailboxes need the license, and all users need a license, by default all the licenses will be there and putting shared mailboxes as a bullet just adds confusion imho.

"For Microsoft Defender for Office 365 Plan 2 tenants, licenses must be acquired for users or mailboxes falling under one or more of the following scenarios:

- All Exchange Online users on the tenant. This is because Plan 2 features and capabilities protect all users in the tenant.
- All shared mailboxes on the tenant.
- If Safe Attachments protection for SharePoint, OneDrive for Business, or Teams is turned on, all users that access SharePoint, OneDrive for Business, or Teams.
- Any user that uses Microsoft 365 Apps or Teams when Safe Links protections are enabled."

**Comment by chrisda** [comment]
@benstegink, apparently, the Service Description is correct. I'll add a link to it in the What do you need to know before you begin? section.

**Comment by benstegink** [comment]
@chrisda, sounds good to me. That was what I was looking for in the "What you need to do" is which specific users/mailboxes/etc. need to be licensed with that P2 license in order to run an attack simulation. Thanks again!

**Comment by benstegink** [comment]
So a followup question then if Shared Mailboxes need to be licensed, does this also mean you need a license for each Microsoft 365 Group and Teams team as these also have shared mailboxes associated with each of them? The whole thing of having to license shared mailboxes when all of the users using the Shared Mailboxes is baffling, not to mention the administrative overhead of licensing all these mailboxes seems nearly impossible.

**Comment by DMoenks** [comment]
I'll just link [OfficeDocs-O365ServiceDescriptions/#764](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/764) here for reference, mostly being in the same state regarding licensing clarification

**Comment by chrisda** [comment]
@benstegink, I would say: go by what the Service Description says.

**Comment by chrisda** [comment]
Nothing new to report here, so closing.

Thanks for the feedback.
