### ISSUE TITLE
Storage in Archives not considered in Mailbox Usage report?

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/microsoft-365-docs#12009]
Hello,
in the section there is the sentence: "Storage Chart doesn't include archive mailboxes"
Does this really mean, that the storage consumend by emails in archive mailboxes is not shown in the mailbox usage report?
If so, how can the storage in archive mailboxes be reportet?
Also this is important information that should be mentioned more prominently I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e612a4e4-d051-27a7-e54a-bb1ac3fe0849
* Version Independent ID: 653be32f-e4e8-8a72-98b3-a629238ecbd5
* Content: [Microsoft 365 admin center mailbox usage reports - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/mailbox-usage?redirectSourcePath=%252fclient%252fMailbox-usage-beffbe01-ce2d-4614-9ae5-7898868e2729&view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/mailbox-usage.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@joergrenn Thank you for your feedback. No,  the storage consumed by emails in archive mailboxes is shown in the mailbox usage report. however, only the storage chart doesn't include archive mailboxes.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @joergrenn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by joergrenn** [comment]
Hello @msbemba ,
thanks for the reply, but I am still at the end of my rope here.
What ist the "usage report"?
Is this the table below the three Charts where each individual mailbox is listed with Username, Last activity, Item count, Storage used, Quota status?
So the Storage used for a mailbox in that table includes the archive storage?

I am interested in course of the overall storage used by all mailboxes in the tenant. I would export the data from the storage chart for that.
But neither in the chart nor in the exported csv is the data of archive mailboxes included?
Is there another way to get the overall storage consumed by all mailboxes including archives?
