### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by inspektor99** [MicrosoftDocs/microsoft-365-docs#1201]
Every time I try and export a particular review set, I get the all document IDs in the summary.txt.  However, the actual documents do not export, there are zero exported documents.  I have tried exporting all documents, selecting all and exporting selected documents, every combination of export options, still no documents.

results of the Summary.txt
  Native files: true
  Extracted text files: false
  Load file: true
  Include tag: false
  Parsed selection expansion columns: ConversationFamilyId
  Parsed file replacement rules: conversationPdfTime|conversations/{WORKINGSET_ID}/convertedpdf/[ConversationFamilyId].pdf=&gt;{EXPORT_ID}/NativeFiles/[ConversationFamilyId]_conversation.pdf|Noop|Noop|Noop|Noop

Load file
  [Load file] total documents: 0
  [Load file] without processing error: 0
  [Load file] with processing error: 0
  [Load file] native documents: 0
  [Load file] converted documents: 0
  [Load file] redacted documents: 0
  [Load file] text documents: 0
  [Load file] redacted text documents: 0
Native files
  [Native files] total documents: 0
  [Native files] native documents: 0
  [Native files] converted documents: 0
  [Native files] redacted documents: 0
Extracted text files
  [Extracted text] total documents: 0
  [Extracted text] text documents: 0
  [Extracted text] redacted text documents: 0

Native files size
  Size(Bytes): 0
  Size(MB): 0
  Size(GB): 0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2290d327-7e3c-bc52-ca1a-2e6b60d502c0
* Version Independent ID: 4b775396-e48c-717a-fccf-61705776f2ba
* Content: [Export documents from a review set - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-documents-from-review-set#feedback)
* Content Source: [microsoft-365/compliance/export-documents-from-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-documents-from-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@inspektor99 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
