### ISSUE TITLE
content update

### ISSUE THREAD

**Issue by nitbhatt0** [MicrosoftDocs/microsoft-365-docs#12011]
[
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-controlled-folders?view=o365-worldwide#microsoft-intune
Step#5. 
the option is not 'Enable Folder Protection'
Rather its now called - ' Enable Controlled Folder Access'

Likewise.
Step#6 | List of additional folders >> is called >> 'Controlled Folder Access Protected Folders'
Step#7 | List of apps that have access >> is now >> 'Controlled Folder Access Allowed Applications'

]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25faafb3-297a-dbb1-651b-dcf18081e95b
* Version Independent ID: 61a3c7ca-8094-5219-7f7c-688124bab07c
* Content: [Enable controlled folder access](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-controlled-folders?view=o365-worldwide#microsoft-intune)
* Content Source: [microsoft-365/security/defender-endpoint/enable-controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-controlled-folders.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@nitbhatt0 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12039

Once the author approves, the changes will be live.

Thanks
Sri
