### ISSUE TITLE
Missing categories

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#1202]
CAT:GIMP and CAT:AMP missing. Please confirm with engineering and update.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4194fdd-c5de-d424-319a-5e83774b36c2
* Version Independent ID: 83997ad4-a9bd-146e-5da0-8022458cf3ea
* Content: [How policies and protections are combined when mail is red-flagged - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined)
* Content Source: [microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by 4rtorias** [comment]
CAT:HPHISH is also missing.

**Comment by mypil** [comment]
Related to issue #707

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights on this issue?


Thank you.

**Comment by 4rtorias** [comment]
We really need an update on the HPHISH category and whether or not it can be managed. Premier Support has been unable to help us resolve High Confidence Phish false positives for 2 weeks. Releasing Quarantine messages by hand is taking a significant amount of our time.

**Comment by MSFTTracyP** [comment]
This document isn't meant to be the sole source of truth, and is for the purpose of education, chiefly. As a result, these documents may not be kept current to product reality. Examination of headers is handled through _**Threat Explorer**_, which parses and renders based on data just like these. It would be a much more worthwhile practice to work in Threat Explorer, and Realtime detections to look at email headers. There you can preview email headers and download email bodies. Likewise, Premier is better served working through this tool and giving feedback up through the chain to improve these features. Please let me know if there are problems working with Threat Explorer, and let's get that feedback chain going.

**Comment by chrisbues** [comment]
> This document isn't meant to be the sole source of truth, and is for the purpose of education, chiefly. 
> As a result, these documents may not be kept current to product reality.

So you're effectively saying the **official documentation is not going to be correct or up to date**. I have a hard time believing that's Microsoft's official position on what docs.microsoft.com is intended to be. As a customer with significant investment in Microsoft technologies, I have a reasonable expectation that the documentation will be correct, period.

**Comment by mypil** [comment]
@aldoug @4rtorias @chrisbues - Thank you for engaging with the community here for the docs.

From our understanding, the issue you raised has been answered by the author MSFTTracyP so we will close this issue.

If you have some suggestions on how to make Microsoft 365 better, it would be great if you could add your voice in **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)**. I know the product teams are keeping a close tab on user feedback and feature requests that would help improve Microsoft 365.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
