### ISSUE TITLE
Licence clarification

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/microsoft-365-docs#12025]
[Enter feedback here]
https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide#dlp-licensing-for-microsoft-teams
In the above section, Does F5 Information Protection & Governance include Teams DLP? If yes, can you please update this page?

The below article clearly says F5 IP&G includes Teams DLP
https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-data-loss-prevention-data-loss-prevention-dlp-for-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebaab3f7-d1d4-c649-efe8-f24913da4f3e
* Version Independent ID: c5710ebf-0ca5-ab46-c490-64ebc308defe
* Content: [Data loss prevention and Microsoft Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide#dlp-licensing-for-microsoft-teams)
* Content Source: [microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-microsoft-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@bubhat Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12041

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@bubhat Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
