### ISSUE TITLE
OneDriveAccess

### ISSUE THREAD

**Issue by DMcCollumn** [MicrosoftDocs/microsoft-365-docs#12024]
Instructions listed here for OneDrive access do no work. Folder just keeps coming up as Empty when admins are assigned. GA's can open OneDrive through admin panel and see plenty of files. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34c90550-34c3-c6de-81d4-6d85a8bc3f90
* Version Independent ID: 151fb754-7bea-f489-5115-e3551db0f303
* Content: [Step 5 - Give another employee access to OneDrive and Outlook data - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-5?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-5.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-5.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@DMcCollumn Thank you for your feedback. We will review and update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@DMcCollumn Thank you for your feedback. I was able to follow the steps and find the files intact. If you continue to face issues, I'd recommend raising a support ticket via the need help section on the admin center, so that our support engineers can assist you fix this bug.

Hope this helps!

Thanks
Sri
