### ISSUE TITLE
Settings > Endpoints > Roles (under Permissions) is missing

### ISSUE THREAD

**Issue by SirHenryIII** [MicrosoftDocs/microsoft-365-docs#12036]
The documentantion describe below Create, Edit or Delete roles to go to:

> Settings > Endpoints > Roles (under Permissions).

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/15123392/3ad8e195-c54a-4cc0-938b-bd3c75c11d05)

But this isn't available anymore. I have tested it from different tenants with different Licences with the same result. Actually I didn't find a way to create custom roles for the defender.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 796818f1-67d6-9a20-9498-94baf03276d6
* Version Independent ID: a9293050-acc0-7710-52cf-5cf64689d719
* Content: [Create and manage roles for role-based access control](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/user-roles?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/user-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/user-roles.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@SirHenryIII Thank you for your feedback. I was able to find the option as described in the document.

![Uploading image.png…]()
