### ISSUE TITLE
Link Missing

### ISSUE THREAD

**Issue by MartinMurdy** [MicrosoftDocs/microsoft-365-docs#1203]
Metadata file
This can be considered your “load file” that contains metadata associated with the files you exported. For a list of fields available in the metadata file, see [link]. This file can typically be ingested by 3rd party tools downstream.

see [link] ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2290d327-7e3c-bc52-ca1a-2e6b60d502c0
* Version Independent ID: 4b775396-e48c-717a-fccf-61705776f2ba
* Content: [Export documents from a review set - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-documents-from-review-set#feedback)
* Content Source: [microsoft-365/compliance/export-documents-from-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-documents-from-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@MartinMurdy Thanks for the heads up. I'll fix this link. The link will point to this file: https://docs.microsoft.com/en-us/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery

See fields in the "Exported field name" column.
