### ISSUE TITLE
requesting to add more details on the modern unified solution

### ISSUE THREAD

**Issue by nitbhatt0** [MicrosoftDocs/microsoft-365-docs#12035]
[Hi Team,
Can you please include some details about what exactly is the - modern unified solution. 

if its AMA then please mention it clearly in the docs and include screenshots
If its not AMA, and something else, then please include some screenshots on how can we verify that the modern unified solution is successfully installed.

I searched online and couldn't find any details on this.
so it'd be great if you share clear information on ms docs.

]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#new-windows-server-2012-r2-and-2016-functionality-in-the-modern-unified-solution)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
More info on modern unified solution: https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/defending-windows-server-2012-r2-and-2016/ba-p/2783292 

To verify - run the detection test.
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-detection-test?view=o365-worldwide
