### ISSUE TITLE
Typo in title of Document

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#12050]
The title if this page has a typo - Service is spelt "Sevice" 

It currently reads "Check sevice health at Microsoft Defender for Endpoint"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca0b53f6-8f88-42e7-e1b2-ee3f68889379
* Version Independent ID: eacbb573-2072-b835-e3b4-bb62d9df1e70
* Content: [Check the device health at Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/check-sensor-status?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/check-sensor-status.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/check-sensor-status.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
Hello @pjrcdf. Thank you so much for letting us know about this issue. It's fixed and the updates will be live later today. Really appreciate your calling this to our attention. Thanks again!
