### ISSUE TITLE
I am searching for a wallet

### ISSUE THREAD

**Issue by Johannie803** [MicrosoftDocs/microsoft-365-docs#1205]
Why cant you give me a wallet without comment of any kind.

**Comment by mypil** [comment]
@Johannie803 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@Johannie803 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.

**Comment by Johannie803** [comment]
Your people must be crazy with sending such large pass word for reset the same there is over 100 letters for reseting my password is it not possible to use a shorter one.

________________________________
Fra: Joyce Y. <notifications@github.com>
Sendt: 12. februar 2020 03:41
Til: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Johnnie Sigaard. <mckinnysigaard@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [MicrosoftDocs/microsoft-365-docs] I am searching for a wallet (#1205)


Closed #1205<https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1205>.
