### ISSUE TITLE
Always audit file activity for devices section confusing and misleading

### ISSUE THREAD

**Issue by AndNovian** [MicrosoftDocs/microsoft-365-docs#12059]
Always audit file activity for devices
By default, when devices are onboarded, activity for Office, PDF, and CSV files is automatically audited and available for review in activity explorer. Turn off this feature if you want this activity to be audited only when onboarded devices are included in an active policy.

**File activity will always be audited for onboarded devices, regardless of whether they're included in an active policy.** 

// _Above section in bold is problematic and confusing. I suspected the explanation is only copy paste from the actual DLP policy and this doesnt help with clear explanation to the option at all._

Below is actual screenshot frm my demo tenant
When this option is enabled
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/114455998/81cf2167-3755-4358-82bd-eac2032774ff)

When option is disabled
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/114455998/7eb9076e-e6a5-4f9c-8e43-3d8ea4c2ce0a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f25ec8-d5a8-4a9d-ca72-bd61eacd9dbc
* Version Independent ID: 34f25ec8-d5a8-4a9d-ca72-bd61eacd9dbc
* Content: [Configure endpoint DLP settings - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-configure-endpoint-settings?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-configure-endpoint-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-configure-endpoint-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@AndNovian Thank you for your feedback. We have removed the ambiguous statement from the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12128

If the option is turned ON -File activity will always be audited for onboarded devices, regardless of whether they're included in an active policy.

If the option is turned OFF- File activity will always be audited for onboarded devices only when they're included in an active policy.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@AndNovian Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
