### ISSUE TITLE
Incorrect caveat regarding Submissions page for GCC/GCCH/DoD tenants

### ISSUE THREAD

**Issue by lonstev** [MicrosoftDocs/microsoft-365-docs#12052]
Documentation note indicates: "In U.S. Government organizations (Microsoft 365 GCC, GCC High, and DoD), admins can't use the Submissions page in the Microsoft 365 Defender portal to submit messages to Microsoft. Instead, admins in those organizations need to open a support case to submit messages."

At least in GCC High, admins are able to utilize the Submissions page to submit messages to Microsoft.  I confirmed this is available in our test tenant.  If that is new behavior, we should update the documentation and modify the note appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Manage submissions - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-admin?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-admin.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by v-ratulach** [comment]
Looking into this.

**Comment by v-ratulach** [comment]
@lonstev   The topic has been updated: https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-admin?view=o365-worldwide
