### ISSUE TITLE
Please show images or screenshots

### ISSUE THREAD

**Issue by MrVP** [MicrosoftDocs/microsoft-365-docs#12051]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e62dfa25-e420-38e4-ff47-05cca62d14ec
* Version Independent ID: 5ea03ce0-38b9-e005-a430-e98442e2ec83
* Content: [Deploy add-ins in the admin center - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-deployment-of-add-ins.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@MrVP Thank you for your feedback. We will add the screenshots to the document shortly. 

Thanks
Sri

**Comment by msbemba** [comment]
@MrVP Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12350

Once the author approves, the changes will be live.

Thanks
Sri
