### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by mmtenez** [MicrosoftDocs/microsoft-365-docs#12067]
[ Sisestage tagasiside siia]

---
#### Dokumendi üksikasjad

⚠ *Ärge seda jaotist redigeerige. See on vajalik learn.microsoft.com-i ➟ GitHubi probleemide linkimiseks.*

* ID: 9487dd6d-c534-ee70-0f59-00fcd20c0c93
* Version Independent ID: 69908dd8-ae60-0697-0b1c-0934f2ad2568
* Content: [Try or buy a Microsoft 365 for business subscription](https://learn.microsoft.com/et-EE/microsoft-365/commerce/try-or-buy-microsoft-365?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/try-or-buy-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/try-or-buy-microsoft-365.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@mmtenez Thank you for your feedback. This document pertains only to the M365 subscription and is not related to any apple products. 

@yogkumgit  There are no changes needed on this document and can be closed.

Thanks
Sri
