### ISSUE TITLE
No KQL Example in Section

### ISSUE THREAD

**Issue by kylerguldenfpg** [MicrosoftDocs/microsoft-365-docs#12062]
https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-keyword-queries-and-search-conditions?view=o365-worldwide

There should be an example provided in KQL in the "Finding content in Exchange Online" section, as well as the "Finding content in SharePoint and OneDrive" section. An example is given in English, but not in KQL -- which is the subject of the overall document.

This change would make KQL more accessible to beginners and show a correct example of the described syntax in a "real world" scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f712951e-e492-0f7b-71a7-06942ef9f72b
* Version Independent ID: f712951e-e492-0f7b-71a7-06942ef9f72b
* Content: [Keyword queries and search conditions for eDiscovery - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@kylerguldenfpg Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
