### ISSUE TITLE
Lab Kit Corrupt

### ISSUE THREAD

**Issue by Syn3rgi3** [MicrosoftDocs/microsoft-365-docs#1206]
The lab kit zip file is corrupt, can you please investigate and repackage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office Deployment Lab Kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?source=docs#feedback)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by mypil** [comment]
@Syn3rgi3 - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Syn3rgi3 - Are you getting an error when you download and install the zip file? 
Can you please share more details by sending us a screenshot of the error? Please attach it here in the comment section.

Thank you.

**Comment by JGruszczyk** [comment]
@Syn3rgi3 can you please upload and provide us the error you're seeing? I was able to download the package without any issues

**Comment by JGruszczyk** [comment]
I was again able to download this without error. @Syn3rgi3 please provide us some details on the error and we can reopen this issue
