### ISSUE TITLE
Content should be updated to allow access for device management

### ISSUE THREAD

**Issue by ksagala** [MicrosoftDocs/microsoft-365-docs#12068]
"Device management is part of the Security & Compliance Center so you'll need to go there to kick off Basic Mobility and Security setup." It's not true anymore. Device management for Basic Mobility and Security is now available in admin.microsoft.com portal via hidden link. Companies without Intune (or MDE) licenses are confused.
Configuration steps 3 and 4 also describing not existing configuration option.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67847a65-598f-f3ff-0864-92a39dfdd86d
* Version Independent ID: e47b69f4-1964-e18b-e81e-31edc2e6798f
* Content: [Set up Basic Mobility and Security - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/basic-mobility-security/set-up?view=o365-worldwide)
* Content Source: [microsoft-365/admin/basic-mobility-security/set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/basic-mobility-security/set-up.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ksagala Thank you for your feedback. We will review the navigation changes and update the document accordingly.

Thanks
Sri

**Comment by msbemba** [comment]
@ksagala Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12157

Once the author approves, the changes will be live.

Thanks
Sri
