### ISSUE TITLE
Azure Static Web App plan (MTA-STS)

### ISSUE THREAD

**Issue by Matt-C22** [MicrosoftDocs/microsoft-365-docs#12076]
Could you explain in detail the reasoning for using the Standard plan as opposed to the Free one for this deployment?

[On the 4th step](https://learn.microsoft.com/en-us/microsoft-365/compliance/enhancing-mail-flow-with-mta-sts?view=o365-worldwide#option-1-recommended-azure-static-web-app), the following is stated: 
4. Create a new Azure Static Web App with the following configuration:

Name: MTA-STS-StaticWebApp
**Plan type: Standard**
Deployment Details: Azure DevOps
Organization: ContosoCorporation
Project: MTA-STS_Project
Repository: MTA-STS_Project
Branch: master
Build Presets: Angular
App Location: /home

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d79cb8a-81c1-1edb-c13c-cb7f14225149
* Version Independent ID: 7d79cb8a-81c1-1edb-c13c-cb7f14225149
* Content: [Enhancing mail flow with MTA-STS  - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/enhancing-mail-flow-with-mta-sts?view=o365-worldwide#option-1-recommended-azure-static-web-app)
* Content Source: [microsoft-365/compliance/enhancing-mail-flow-with-mta-sts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enhancing-mail-flow-with-mta-sts.md)
* Service: **o365-seccomp**
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by msbemba** [comment]
@Matt-C22 Thank you for your feedback. The Free option is generally used for Hobby or personal projects. Since we are trying to help Microsoft Exchange Online customers host their MTA-STS policy using Azure resources, this should be the standard plan.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Matt-C22 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
