### ISSUE TITLE
The Cross-Tenant content move feature is not enabled for this tenant

### ISSUE THREAD

**Issue by joaopavan** [MicrosoftDocs/microsoft-365-docs#12073]
Hi,

I am unable to establish trust between the source and target tenants. When I try to use the cmdlet "Set-SPOCrossTenantRelationship" I receive the error "The Cross-Tenant content move feature is not enabled for this tenant".

How Can I enable this feature?

The "cross-tenant mailbox migration" worked fine to me in the same tenant. 

Thank you.

**Comment by joaopavan** [comment]
Hello,
Yes. It is correct.

Em seg., 22 de mai. de 2023 às 13:45, Denise Vangel-MSFT <
***@***.***> escreveu:

**Comment by msbemba** [comment]
@joaopavan Thank you for your feedback. This looks more like a technical problem or a bug, I'd recommend you contact support via the need help section on the admin center, so that the support engineer can assist you in fixing the issue.

Hope this helps!

Thanks
Sri
