### ISSUE TITLE
Select the domain to use for email from Microsoft 365 products: Scope again and guests ?

### ISSUE THREAD

**Issue by ElricX0X** [MicrosoftDocs/microsoft-365-docs#12077]
Hello,

If we opt in, what would be the sender for an email going to an external guest account ?
For example if you add some external  guest to a team what will the sender be  for the "You have been added to a team in Microsoft Teams" email ?

Best regards,
Elric
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eda44995-3561-2f08-e776-5359b0aaf37c
* Version Independent ID: eda44995-3561-2f08-e776-5359b0aaf37c
* Content: [Select the domain to use for email from Microsoft 365 products - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@ElricX0X Thank you for your feedback. Once this is configured all M365 products do not use the default Microsoft email address, instead, start using the custom send from the domain address. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ElricX0X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
