### ISSUE TITLE
Broken link in supported language section

### ISSUE THREAD

**Issue by airdalle** [MicrosoftDocs/microsoft-365-docs#12074]
The section "what languages are supported" of [https://learn.microsoft.com/en-us/microsoft-365/compliance/ocr-learn-about](https://learn.microsoft.com/en-us/microsoft-365/compliance/ocr-learn-about) provides a broken link.

Current provided URL is [https://azure.microsoft.com/cognitive-services/computer-vision/language-support](https://azure.microsoft.com/cognitive-services/computer-vision/language-support), and seems it should target to [https://learn.microsoft.com/en-us/azure/cognitive-services/language-support](https://learn.microsoft.com/en-us/azure/cognitive-services/language-support) instead ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdf1850-fdb8-c210-1d45-13cd55d733b3
* Version Independent ID: 6fdf1850-fdb8-c210-1d45-13cd55d733b3
* Content: [Learn about optical character recognition in Microsoft Purview (preview) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ocr-learn-about?view=o365-worldwide#workflow-at-a-glance)
* Content Source: [microsoft-365/compliance/ocr-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ocr-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @kmkoenen
* Microsoft Alias: **v-katykoenen**

**Comment by msbemba** [comment]
@airdalle Thank you for your feedback. The Link has been pointed to https://learn.microsoft.com/en-us/azure/cognitive-services/language-support now.


Thanks
Sri
