### ISSUE TITLE
Device Onboarding Python script obsolete?

### ISSUE THREAD

**Issue by QMUL-JayHay** [MicrosoftDocs/microsoft-365-docs#12084]
Hi, all

I cannot see the Python script for download from the support portal. Is this a deprecated/obsolete method now?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7ba4860-989a-9424-1de5-37691678aa84
* Version Independent ID: a7ba4860-989a-9424-1de5-37691678aa84
* Content: [Use network protection to help prevent Linux connections to bad sites](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection-linux.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@QMUL-JayHay Thank you for your feedback. It is available under Microsoft 365 Defender -> Settings -> Device Management -> Onboarding.

If you continue to not see the script, I'd recommend you contact support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by QMUL-JayHay** [comment]
Thank you for the info. I understand the layout now. 

For posterity, the Python script only covers small deployments (1-10 devices). It is not used for the Puppet, Ansible, ... method at all.
