### ISSUE TITLE
Query regarding impact on guest accounts

### ISSUE THREAD

**Issue by hittensa** [MicrosoftDocs/microsoft-365-docs#12086]
Please can you confirm what happens to guest account access when a custom domain is removed.

E.g: Your users have been granted access to multiple third party tenancies using their M365 accounts. Your users have the domain @constoso.com associated with their accounts. You remove the @contoso.com domain to another M365 tenancy during an acquisition or merger.  Your users revert back to @onmicrosoft.com during the domain removal.

What happens in this instance? I'm assuming that the @onmicrosoft.com accounts continue to have access and the users will need to reach out to the orgs to have them re-invite them in their new tenancy?

**Comment by yogkumgit** [comment]
@hittensa Please indicate which document you are referring to . Thanks

**Comment by hittensa** [comment]
The article is: https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/remove-a-domain?view=o365-worldwide

**Comment by msbemba** [comment]
@hittensa Thank you for your feedback. You are correct, the respective onmicrosoft.com accounts get access and they suers will need to reach out to the organization to have them re-invite them in their new tenancy.

Hope this helps!

Thanks
Sri
