### ISSUE TITLE
Teams Tenant Switching

### ISSUE THREAD

**Issue by fanuelushindi** [MicrosoftDocs/microsoft-365-docs#12085]
Will users still switch tenants on Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f0db07-fbeb-7a8e-aa94-297b5f808216
* Version Independent ID: 0fec134e-c8a3-50ec-7094-31ca70cb42ba
* Content: [Microsoft 365 inter-tenant collaboration - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-inter-tenant-collaboration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-inter-tenant-collaboration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-inter-tenant-collaboration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@fanuelushindi Thank you for your feedback. Yes, users will still switch tenants on teams on the top right corner.

Hope this helps!

Thanks
Sri
