### ISSUE TITLE
Pls make the videos downloadable 

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/microsoft-365-docs#1208]
hi, Could you please make the videos available for offline usage. Will help to review /replay the content offline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88d48ed-b84b-3571-6c6e-e12ed8811c11
* Version Independent ID: a1aefdd8-25ed-f181-a167-c5d5f7a4efa3
* Content: [Chief Information Security Officer (CISO) Workshop, Module 1: Microsoft Cybersecurity Briefing - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/ciso-workshop-module-1)
* Content Source: [microsoft-365/security/office-365-security/ciso-workshop-module-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/ciso-workshop-module-1.md)
* Service: **o365-seccomp**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@knssub - Thank you for submitting feedback. 

I will get this request over to the Microsoft 365 writing team for their consideration.

**Comment by mypil** [comment]
@Dansimp - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by denisebmsft** [comment]
Greetings! It looks like the videos are actually downloadable. Start a video, and look for the down arrow, which is a download button. Please let us know if you have any other questions.

**Comment by knssub** [comment]
the videos are not downloadable, please try it. It only downloads the transcripts, not the video.

**Comment by knssub** [comment]
Can you pls open this, this request is closed without verification
