### ISSUE TITLE
Some more information about disabling PowerShell connectivity

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/microsoft-365-docs#1209]
One of the Miscellaneous/non-policy settings is to disable PowerShell connectivity. Can we have some more information about what is meant here, is that PowerShell connectivity for all, or just for mailboxes ?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4f6b67-85ac-ef6e-5260-6ae160cfd6d8
* Version Independent ID: b4ae42b8-dd36-9f18-092b-af0b55b3c0fb
* Content: [Best practices for configuring EOP and Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/best-practices-for-configuring-eop)
* Content Source: [microsoft-365/security/office-365-security/best-practices-for-configuring-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/best-practices-for-configuring-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@kennethvs, I updated the topic with a link to the 'how to' procedure and some notes.

In the cloud, you enable/disable PowerShell access via the Set-User cmdlet, so recipient objects that are returned by the Get-User cmdlet are viable. Basically, you're talking about mailboxes with associated user accounts, and also mail users (mail-enabled users).

Thanks for the feedback.
