### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by danielclasson** [MicrosoftDocs/microsoft-365-docs#121]
"If are not currently using Azure Active Directory"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d56e8900-d44a-b87c-a19d-8523810b4308
* Version Independent ID: 598e8f77-17af-6ade-318f-ea7775db080d
* Content: [Step 2 - Directory and Network Readiness](https://docs.microsoft.com/en-us/microsoft-365/enterprise/step-2-directory-and-network-readiness)
* Content Source: [microsoft-365/enterprise/step-2-directory-and-network-readiness.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/step-2-directory-and-network-readiness.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by adrianyong3** [comment]
Created a PR for this issue https://github.com/MicrosoftDocs/microsoft-365-docs/pull/126

**Comment by JGruszczyk** [comment]
Corrected spelling
