### ISSUE TITLE
Update Schema Table documentation

### ISSUE THREAD

**Issue by 0fflineDocs** [MicrosoftDocs/microsoft-365-docs#12102]
[Enter feedback here]

 On this page: https://learn.microsoft.com/en-gb/microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide#learn-the-schema-tables

The schema tables needs an additional update, there are more tables in M365 Defender (Hunting/Advanced Hunting/Schema Reference) under Schema Reference than are listed here. Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc9f0472-a1fe-8d1e-f081-fd3c97bbfc92
* Version Independent ID: ddc56801-5d2f-cef2-c6fe-3360368088fa
* Content: [Data tables in the Microsoft 365 Defender advanced hunting schema](https://learn.microsoft.com/en-gb/microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-schema-tables.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-schema-tables.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
Thank you, I will update the tables and this

**Comment by schmurky** [comment]
This PR addresses this. https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/20731

**Comment by schmurky** [comment]
Hi @yogkumgit! this has been addressed.
