### ISSUE TITLE
Request update the "Friendly name" in Teams activities

### ISSUE THREAD

**Issue by contributor-luis** [MicrosoftDocs/microsoft-365-docs#12104]
[Enter feedback here]

We have 4 Friendly names in the Teams activities table that needed an update. 

Appear in doc as: "Applied sensitivity label" --- Appear in Activity Audit as: "Applied sensitivity label to meeting"
Appear in doc as: "Changed sensitivity label" --- Appear in Activity Audit as: "Changed sensitivity label for meeting"
Appear in doc as: "Removed sensitivity label" --- Appear in Activity Audit as: "Removed sensitivity label from meeting"
Appear in doc as: "Responded to invitee response to shared channel" --- Appear in Activity Audit as: "Responded to invitee response to shared channel invitation"

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/105931677/fb6cde8c-e5de-40a5-b39c-2ad06862f182)
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/105931677/90c03b71-dafb-4ea6-8e2f-b3a240bb74b2)
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/105931677/5c65b6ce-4c8f-458c-ba2a-237bbc4b2027)
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/105931677/defe44b0-370a-4ed9-825f-554cbf7ebbf9)

Regards, 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 508fc30b-d9da-181a-a015-b7888c0b825b
* Version Independent ID: 508fc30b-d9da-181a-a015-b7888c0b825b
* Content: [Search the audit log for events in Microsoft Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-teams-audit-log-events?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-teams-audit-log-events.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-teams-audit-log-events.md)
* Service: **msteams**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@contributor-luis Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12112

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@contributor-luis Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
