### ISSUE TITLE
Include note for Cross Cloud Anonymous Join for the Teams endpoint section

### ISSUE THREAD

**Issue by bradbrill** [MicrosoftDocs/microsoft-365-docs#12100]
Teams in DoD supports Cross-Cloud Anonymous Join, which means a DoD Teams user/client can join WW or GCCH hosted meetings. This has caused some confusion/lead to customers raising cases because they have whitelisted for DoD, but not for the other clouds. It is currently only implied that if they want to be able to connect to GCCH/WW meetings, that they have to whitelist for those endpoints.

Could we please include a warning/notification under the Teams subsection that for Cross-Cloud Join to properly work, they must whitelist the endpoints for the cloud of the target meeting? Also add links to the other cloud endpoint pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13e07b8c-58ce-5d96-14cd-535b6d9c542c
* Version Independent ID: 13e07b8c-58ce-5d96-14cd-535b6d9c542c
* Content: [Office 365 US Government DOD endpoints - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@bradbrill Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12131

Once the author approves, the changes will be live.

Thanks
Sri
