### ISSUE TITLE
How to find out which document is detected as unprotected, sensitive content?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1210]
The `Unprotected sensitive info` widget is shown in the tenant and it states that 1 document is unprotected.

> Some docs in your org contain one or more of DLP's most common types of sensitive info but aren't being protected by a DLP policy. Learn about our policy recommendations

How to find out which document is detected as unprotected, sensitive content? As a customer, we would like to know if a file is detected as in this case it's most likely a false positive but as a customer we want to verify this.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09548665-6562-b523-40da-a1a3dbb59fdd
* Version Independent ID: a9902aec-7ba7-2618-6c62-69d0ccdf774b
* Content: [Get started with DLP policy recommendations - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-dlp-policy-recommendations#feedback)
* Content Source: [microsoft-365/compliance/get-started-with-dlp-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-with-dlp-policy-recommendations.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @GiantCrocodile 
- Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

**Comment by GiantCrocodile** [comment]
I opened a service ticket and will keep you updated if the docs need clarification @chrfox. Thank you!

**Comment by GiantCrocodile** [comment]
This did help @chrfox:

1. becoming an eDiscovery Administrator (https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions#assign-ediscovery-permissions-in-the-security--compliance-center)
2. start a keyword search at https://protection.office.com/contentsearchbeta?ContentOnly=1 and e. g. search for string `SensitiveType:"Credit Card Number"` if you want to find documents which contain credit card numbers. (https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide#searchable-sensitive-data-types)

Maybe this should be properly referenced.
