### ISSUE TITLE
Wrong description to parameters of "ResetPlatform" and "RevertPlatform".

### ISSUE THREAD

**Issue by sparkf1** [MicrosoftDocs/microsoft-365-docs#12116]
The description of parameters of -ResetPlatform and -RevertPlatform are opposite.

The -ResetPlatform should be used to "reset platform binaries back to %ProgramFiles%\Windows Defender".

and the -RevertPlatform should be used to "Revert platform binaries back to the previous installed version of the Defender platform".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd851389-130d-f800-f73d-b7561ccff612
* Version Independent ID: 58ee1cc9-d047-da22-0f56-865643d10d7c
* Content: [Use the command line to manage Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/command-line-arguments-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/command-line-arguments-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/command-line-arguments-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@sparkf1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12151

Once the author approves, the changes will be live.

Thanks
Sri
