### ISSUE TITLE
DirSync

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#12111]
Should update the old references to DirSync. It isn't called that anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1313c6f6-7fb6-4487-5a6a-495eb4d77ac9
* Version Independent ID: f17ee402-dc00-c939-abfe-3afe2a3bee3a
* Content: [Step 7 - Delete a former employee's user account - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-7?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-7.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-7.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12150

Once the author approves, the changes will be live.

Thanks
Sri
