### ISSUE TITLE
How to onboard to TVM standalone

### ISSUE THREAD

**Issue by bleek00** [MicrosoftDocs/microsoft-365-docs#12115]
In this link it only say how to activate TVM standalone service but it doesn't day how to onboard devices to the TVM, w/o it how will it discover recommendations?
https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management?view=o365-worldwide#try-defender-vulnerability-management-standalone

Or should I onboard devices as same as I would do when licensed with MDE P1/P2?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa2cb7af-a9ea-41cf-60ec-b33ff122b058
* Version Independent ID: fa2cb7af-a9ea-41cf-60ec-b33ff122b058
* Content: [Sign up for Microsoft Defender Vulnerability Management](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management?view=o365-worldwide#try-defender-vulnerability-management-standalone)
* Content Source: [microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
@yogkumgit just an FYI that I have sent a message to the product team on this.

**Comment by siosulli** [comment]
Hi @bleek00

Thanks for raising this question! 

As it stands, MDVM doesn't have an independent/separate onboarding process, so yes, you should onboard devices as you would for MDE. 

I have attached image of the Device management\Onboarding page you'll see in the MDVM standalone portal. 

It references Defender for Endpoint but is also applies MDVM.

Improved guidance around this process for standalone is planned in the near future! 

Thanks,
Sinead

![MicrosoftTeams-image (28)](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/64898442/75bc5107-147f-4903-bdff-404015b85d69)
