### ISSUE TITLE
SE Labs test result missing (2023)

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#12121]
Can we add "Microsoft Defender for Office 365 named Best Email Security Service of 2023 by SE Labs" https://www.microsoft.com/en-us/security/blog/2023/02/21/microsoft-defender-for-office-365-named-best-email-security-service-of-2023-by-se-labs/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0665c47f-53f5-bd90-bb22-c99650f2c0ff
* Version Independent ID: a832271a-63b1-71fe-043e-0e3910bb61e0
* Content: [Top scoring in industry tests - Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/top-scoring-industry-tests?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/top-scoring-industry-tests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/top-scoring-industry-tests.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@gbms311 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12152

Once the author approves, the changes will be live.

Thanks
Sri
