### ISSUE TITLE
Reports page in compliance portal

### ISSUE THREAD

**Issue by riswinto** [MicrosoftDocs/microsoft-365-docs#12122]
The **Reports** page is gone in the compliance portal. It looks like reports are now accessible through Data loss prevention > Activity explorer or via PS scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bec12506-ca29-0a03-3b01-699cb22b7ab7
* Version Independent ID: 6dc6083d-fcde-3622-5653-61c5be4bb5db
* Content: [View the reports for data loss prevention - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/view-the-dlp-reports?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/view-the-dlp-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-the-dlp-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@riswinto Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
