### ISSUE TITLE
Non Compliance of Sign ins.

### ISSUE THREAD

**Issue by OMEGA-AUSTRALIA** [MicrosoftDocs/microsoft-365-docs#12123]
Good Afternoon Tam GitHub.

With the highest level of respect, I seek your teams urgent and professional assistance to address 5 years of day in and day out sign on failures into Office 365.

As the Managing Director of the business, I am seek your assistance including compensation to remedy this situation once and for all.

We are dealt with no forms of explanation, other than constant harrowing harassment demanding us to submit pass codes…Furthermore, there are instances like today, where our signatures have  failed to be recognized. 

Your urgent assistance will be greatly appreciated.

Thanks and regards,
Michael Nakhel.
 [Omega Logistics Australasia]
Michael@omegalogistics.com.au
+61 401 100 636

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 562cb0f3-faa7-d798-bf68-7f8d5b1ac5d1
* Version Independent ID: 562cb0f3-faa7-d798-bf68-7f8d5b1ac5d1
* Content: [Microsoft Purview solutions trial user guide - Microsoft Purview (compliance)](https://learn.microsoft.com/en-au/microsoft-365/compliance/compliance-easy-trials-compliance-playbook?view=o365-worldwide#communication-compliance)
* Content Source: [microsoft-365/compliance/compliance-easy-trials-compliance-playbook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-easy-trials-compliance-playbook.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by OMEGA-AUSTRALIA** [comment]
Good Morning from Sydney Australia,

Just to report, overnight system failed to recognise our signatures or passwords. 

Could one of your Senior Staff Members kindly advise what action I should take to address this ongoing matter,

Thank you & I look forward to your reply.

Kind regards,
Michael

**Comment by msbemba** [comment]
@OMEGA-AUSTRALIA Thank you for your feedback. Since this is a technical issue, I'd recommend you contact our Support team via the need help section on the M365 admin center. 

Hope this helps!

Thanks
Sri
