### ISSUE TITLE
Search And Purge role - Where is it?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/microsoft-365-docs#12132]
In the Get the case ID section it says "sign in to the Graph Explorer with an account that's assigned the Search And Purge role in the Microsoft Purview compliance portal." The problem is the role called Search and Purge is a role within a role group, There isn't a way to assign a specific role (at least that I can find). Can you please link to directions on how to find and assign this role such as what role group it is in?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc20a329-2484-3a90-1843-143dc24a8959
* Version Independent ID: dc20a329-2484-3a90-1843-143dc24a8959
* Content: [Search for and delete chat messages in Teams - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-search-and-delete-teams-chat-messages?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/ediscovery-search-and-delete-teams-chat-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-search-and-delete-teams-chat-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@hoyty76 Thank you for your feedback. Search and Purge is a role - https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/scc-permissions?toc=%2Fmicrosoft-365%2Fcompliance%2Ftoc.json&bc=%2Fmicrosoft-365%2Fbreadcrumb%2Ftoc.json&view=o365-worldwide that is assigned to Data Investigator and Organization Management by default.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hoyty76 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
