### ISSUE TITLE
OME, IRM, Azure RMS, Purview Message Encryption - terms become confusing to follow 

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#12138]
This page, and the next page are using a lot of terms that becomes confusing to follow. On one hand we talk about 'Microsoft Purview Message Encryption', when we start by saying we support (1) '**Microsoft Purview Message Encryption**' (2) Secure/Multipurpose & Internet Mail Extensions (S/MIME), and (3) Information Rights Management (IRM).
then we switch immediately below in the comparison table and talk about **OME**, IRM and S/MIME
and then we talk about "**Azure RMS**" ...  including both IRM capabilities and Microsoft Purview Message Encryption

Can we explain the link Purview has to OME, IRM and Azure RMS , ie which one Purview uses ?

I think the next page covers it*, but it would be good / helpful to clear it up on this page as it comes first in the reading order. 
*"Microsoft Purview Message Encryption is an online service that's built on Microsoft Azure Rights Management (Azure RMS) which is part of Azure Information Protection"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21613e57-8909-5adc-26ea-14e0a4771d3b
* Version Independent ID: dcd08c8d-4786-abbd-bd9d-47ad6d2117e6
* Content: [Email encryption in Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/email-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/email-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/email-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks
