### ISSUE TITLE
Can we ensure consistency and refence comparison tables of Message Encryption?

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#12139]
Can we make sure this comparison table on this page - aligns with the comparison and language of: https://learn.microsoft.com/en-us/microsoft-365/compliance/ome-version-comparison?view=o365-worldwide
(and also references it)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21613e57-8909-5adc-26ea-14e0a4771d3b
* Version Independent ID: dcd08c8d-4786-abbd-bd9d-47ad6d2117e6
* Content: [Email encryption in Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/email-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/email-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/email-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@gbms311 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
