### ISSUE TITLE
Correct the Dates

### ISSUE THREAD

**Issue by bradbrill** [MicrosoftDocs/microsoft-365-docs#12147]
There's a statement that the migration will begin in January 2022 and continue through October 2022. I believe that's meant to be October 2023.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c23df2b9-0e0e-1a54-2f42-effb9387459a
* Version Independent ID: c23df2b9-0e0e-1a54-2f42-effb9387459a
* Content: [Office TLS certificate changes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-tls-certificates-changes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md)
* Service: **o365-seccomp**
* GitHub Login: @pshelton-skype
* Microsoft Alias: **pshelton**

**Comment by pshelton-skype** [comment]
October 2022 is correct. With a incredibly small number of exceptions, migration to the new root certificates completed in 2022.

**Comment by bradbrill** [comment]
This sentence doesn't make sense. "Services began transitioning to the new Root CAs in January 2022 and will continue through October 2022." How can it begin at a point later than it will continue through?

**Comment by pshelton-skype** [comment]
January is the first month of 2022 and October is the tenth month of 2022. The start date came before the end date and both dates are now in the past.

**Comment by bradbrill** [comment]
I just had a brain fart. I assumed it was still in progress because Digicert G2 isn't supported in GCCH Teams yet.

**Comment by pshelton-skype** [comment]
No worries, @bradbrill. This has taken long enough in the GCCH that it's probably worth re-posting an announcement and refreshing dates in the documentation when the top-most wildcard certs are to be rotated there. Thanks for the reminder.

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.
