### ISSUE TITLE
Unclear limitation descriptions

### ISSUE THREAD

**Issue by PorLosTacos** [MicrosoftDocs/microsoft-365-docs#12146]
This page appears to list the possibilities per group type, which leads the reader to believe that anything not listed is not allowed, which is not the case. I suggest listing limitations for each group. For example:

The article lists the following:

"Microsoft 365 groups support nesting through [dynamic groups in Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-dynamic-rule-member-of)."

Is this bit mentioning a cool feature of Dynamic Groups in Azure AD? What are there other ways to methods to nest groups into MSFT 365 groups? What groups types can you nest into MSFT 365 groups? Etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **microsoft-365-business**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@PorLosTacos Thank you for your feedback. Microsoft 365 Groups don't support nesting with other Microsoft 365 Groups or with distribution or security groups. It only supports nesting through dynamic groups in Azure Active Directory.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PorLosTacos Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
