### ISSUE TITLE
AST: Update number of builtin payloads and Training modules

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#12149]
I know this may feel like a never ending task, but recently we made a big investment in new content, so it would be good to publicly state the new higher numbers, Im currently responding to a RFI, and need to cite the references to my claims (ie the number of Payloads included, and the number of training modules we have)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b480c7ad-d444-b167-6c3c-80a8e8fb714d
* Version Independent ID: a17b1117-7d8a-54b1-fa72-6cc7b644a254
* Content: [Attack simulation training deployment considerations and FAQ](https://learn.microsoft.com/en-gb/microsoft-365/security/office-365-security/attack-simulation-training-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-faq.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by gbms311** [comment]
Hi. 

Logging into the security.microsoft.com portal, you get 100+ payloads, across 10 categories, and 12+ languages. Additionally there are 85+ training videos to choose from within the Training Content Library. 


Here are some blogs: 
https://techcommunity.microsoft.com/t5/microsoft-defender-for-office/training-only-campaign-is-now-available-with-an-expanded/ba-p/3795237. 

and

https://techcommunity.microsoft.com/t5/security-compliance-and-identity/customize-login-pages-in-attack-simulation-training/ba-p/3447477

**Comment by chrisda** [comment]
@gbms311, your initial request sounds like an ask to *update* existing numbers published in existing articles that are too low.

I found a couple of references to 12+ languages, but the only other firm number I could find is here:

[Q: Does Microsoft provide payloads in other languages?](https://learn.microsoft.com/microsoft-365/security/office-365-security/attack-simulation-training-faq#q-does-microsoft-provide-payloads-in-other-languages)

> A: Currently, there are 40+ localized payloads available in 29+ languages: English, Spanish, German, ...

Which might still be accurate.

If we had existing number that were too low, it would definitely be important to update them. But, by adding numbers now, we guaranteeing ourselves a bit of a maintenance issue (for example, what happens when the number of categories goes from 10 to 15)? Is there a perception that AST doesn't have enough payloads/categories?

**Comment by gbms311** [comment]
Hi . It more about the increased content videos, ie 100+ payloads, across 10 categories, and 85+ training videos to choose from within the Training Content Library.
So maybe the amendment of the question "Q: Does Microsoft provide payloads in other languages?" 
and the addition of a question "Q: How many training videos are available?" - the answer being something along the lines of " Currently there are over 85 training modules within the content library"

Yes this seems like an ever moving target, but there have been a few milestone announcements since this FAQ was written, and it is very dated currently. (incl SANS https://techcommunity.microsoft.com/t5/microsoft-defender-for-office/sans-training-content-now-available-within-attack-simulation/ba-p/3827366) 

I am requesting that we can at least change when big strides are made. 
Yes there is a perception that we have a low amount of content - we are often loosing in compete situations with dedicated providers like KnowB4

**Comment by chrisda** [comment]
@gbms311, OK Done.

> ### Q: How many training videos are available?
>
> A: Currently, there are more than 85 training modules available in the content library. 

You too can add stuff like this directly without opening a GitHub issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md). Just @ include me in the pull request so I can review and approve.

Thanks for the feedback.

Closing
