### ISSUE TITLE
Simple Typo - Chrome reference in firefox instructions

### ISSUE THREAD

**Issue by LiamAlexanderDPC** [MicrosoftDocs/microsoft-365-docs#12141]
Chrome is referenced here, should be Firefox -> https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-firefox-extension-get-started?view=o365-worldwide#adding-the-chrome-extension-to-the-forceinstall-list

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 799a9147-05f7-5a71-fb04-ddf7c2e59236
* Version Independent ID: 799a9147-05f7-5a71-fb04-ddf7c2e59236
* Content: [Get started with the Microsoft Purview Firefox Extension - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-firefox-extension-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-firefox-extension-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-firefox-extension-get-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@LiamAlexanderDPC Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12155

Once the author approves, the changes will be live.

Thanks
Sri
