### ISSUE TITLE
More examples on how to block entire TLD domains.

### ISSUE THREAD

**Issue by ivandretvic** [MicrosoftDocs/microsoft-365-docs#12142]
We need guidance on how to block top level domains entirely. For example, how do we block the newly enabled .ZIP TLD that google just launched? The platform validation checks do not recognise this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f078ade-1f5b-ca3f-190a-8182a4f3d155
* Version Independent ID: 2556b079-c975-79f7-bad0-44ba3fc18ed5
* Content: [Allow or block URLs using the Tenant Allow/Block List](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list-urls-configure?view=o365-worldwide#url-syntax-for-the-tenant-allowblock-list)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list-urls-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list-urls-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **chrisda**

**Comment by v-ratulach** [comment]
Looking into this.

**Comment by v-ratulach** [comment]
Per the PM, we are working on this updating this feature. Stay tuned for documentation updates a few weeks later.
