### ISSUE TITLE
Missing command in Step 2 under "Register Azure subscriptions to use a mandatory retention period"

### ISSUE THREAD

**Issue by andypituch** [MicrosoftDocs/microsoft-365-docs#1214]
Step 2 mentions to "Run the Register-AzProviderFeature cmdlet to register your subscriptions to use a mandatory retention period. Perform this action for each subscription." but the code sample doesn't show the "Register-AzProviderFeature" cmdlet being run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key for Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up#register-azure-subscriptions-to-use-a-mandatory-retention-period)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
That's terrible. Verifying which is correct - the instruction or the example. Thanks for finding this.

**Comment by andywahr** [comment]
The code sample was added but was incorrect for Registering the mandatoryRetentionPeriodEnabled feature:

`-ProviderNamespace Microsoft.KeyVault`   should be  `-ProviderNamespace Microsoft.Resources`
