### ISSUE TITLE
Incorrect Content

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#12140]
This page is very wrong for o365 in China. Links are for the global cloud, instructions are wrong. Capability doesn't even exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29f9f87e-6f96-9663-114a-f6bd74a7a7f4
* Version Independent ID: b3ba56e3-0c78-f286-1c01-12375bf00f62
* Content: [Learn about importing organization PST files - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-21vianet)
* Content Source: [microsoft-365/compliance/importing-pst-files-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/importing-pst-files-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@danmyhre Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
