### ISSUE TITLE
Clarification on roles and validate roles

### ISSUE THREAD

**Issue by SeniorConsulting** [MicrosoftDocs/microsoft-365-docs#12148]
Hi Team,

I've recently struggled with assigning roles to provide access to Settings > Information Protection Scanner.

Firstly, can you please confirm (and correspondingly update the documentation), that these roles need to be assigned in Azure AD, and _**not**_ in the Purview compliance portal.

> Sign in to the [Microsoft Purview compliance portal](https://compliance.microsoft.com/) with one of the following roles:
> 
>    - Global administrator
>    - Compliance administrator
>    - Compliance data administrator
>    - Security administrator
>    - Security operator
>    - Security reader
>    - Global reader
> 
> Then, navigate to the Settings pane.
>Within the Settings pane, select Information protection scanner.

Secondly, can you please validate whether the last three options will allow you to make changes to the Information Protection Scanner settings? i.e. Security operator, Security reader, Global reader. I don't believe they will - if I am correct, can you please update the documentation accordingly.

I've tried with security operator, which shows the Information Protection Scanner blade, but fails to load any content.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e41928f2-a56f-775f-6486-7a8c6b303763
* Version Independent ID: e41928f2-a56f-775f-6486-7a8c6b303763
* Content: [Install and configure the Microsoft Purview Information Protection scanner - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/deploy-scanner-configure-install?view=o365-worldwide&tabs=azure-portal-only#configure-the-scanner-settings)
* Content Source: [microsoft-365/compliance/deploy-scanner-configure-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/deploy-scanner-configure-install.md)
* Service: **o365-seccomp**
* GitHub Login: @libarson
* Microsoft Alias: **libarson**

**Comment by yogkumgit** [comment]
@libarson Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@SeniorConsulting Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
