### ISSUE TITLE
Publish an estimated time before changes are active

### ISSUE THREAD

**Issue by Jono007** [MicrosoftDocs/microsoft-365-docs#12143]
Can you please include an estimate on the time it takes for changes to become active. For example, if I make a change to a Safe Links policy by adding an affected group of users, how long before the policy starts to affect the new group/users?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a27041e-26ec-eaf9-83e3-a7a926a50d33
* Version Independent ID: 3a27041e-26ec-eaf9-83e3-a7a926a50d33
* Content: [Set up Safe Links policies in Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-policies-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links-policies-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-policies-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Jono007, according to the "What do you need to know before you begin?" section of the article you referenced:

> Allow up to 6 hours for a new or updated policy to be applied.

**Comment by Jono007** [comment]
Thank you Chris. Sorry I missed that!

**Comment by chrisda** [comment]
@Jono007, no problem.

Thanks for the feedback.

Closing.
