### ISSUE TITLE
Deprecated add-ins

### ISSUE THREAD

**Issue by jschadow** [MicrosoftDocs/microsoft-365-docs#12156]
Isn't the Report Message and Report Phish add-ins being deprecated?

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/37567392/cfd4094e-18bd-4e16-910d-c991583ec127)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1541fb66-1414-579d-344c-fc1e25ba4ea0
* Version Independent ID: 1541fb66-1414-579d-344c-fc1e25ba4ea0
* Content: [How-to deploy and configure the report message add-in](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTBen
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jschadow Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
