### ISSUE TITLE
typo near ConversationTopic

### ISSUE THREAD

**Issue by salakhani** [MicrosoftDocs/microsoft-365-docs#1216]
't' is missing near 
ConversationTopic - his

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf6db6db-e01a-846e-7ae2-3e94e037e23a
* Version Independent ID: 42a662f4-fea6-8913-dd8c-c7bc0dafad74
* Content: [De-duplication in eDiscovery search results - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/de-duplication-in-ediscovery-search-results#feedback)
* Content Source: [microsoft-365/compliance/de-duplication-in-ediscovery-search-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/de-duplication-in-ediscovery-search-results.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@salakhani Thanks for the heads up. Will fix.
