### ISSUE TITLE
Unable to use those plugins on assigned mailboxes with Full Access permissions. 

### ISSUE THREAD

**Issue by WalterMccan** [MicrosoftDocs/microsoft-365-docs#12160]
This page does not provide the explanation that users assigned Full Access to other mailboxes may not be able to report messages within those mailboxes unless they are directly logged into them. Consider scenario where a PA is working CEOs emails and is unable to report the phishing ones... The expected functionality here would be that if user has full access (or read and manage) mailbox permissions, they should be able to report emails within that mailbox. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-users-report-message-add-in-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by v-ratulach** [comment]
Looking into this.

**Comment by dhairyya** [comment]
@WalterMccan could you please explain what the exact error is you are seeing here and how can I reproduce it?

**Comment by WalterMccan** [comment]
@dhairyya There is no error. Outlook simply doesn't allow the user with full permissions to use the report add-in. The add-in is not showing at all and there is no ability to add it. 

To reproduce:
1. Create 2 mailboxes. Assign full permissions of the first mailbox to another mailbox user. 
2. Wait for Outlook to show the first mailbox for the second user and navigate to it. 
3. Attempt to report a message within the second mailbox.

**Comment by dhairyya** [comment]
@WalterMccan if you are trying to report a message from shared and delegate mailbox please read the following MC post https://admin.microsoft.com/AdminPortal/Home?ref=MessageCenter/:/messages/MC553274

Let me know if you have any questions or doubt

**Comment by WalterMccan** [comment]
@dhairyya Thank you for this informative post. It seems like the feature is only available for the OWA which is unfortunate as majority of people use the desktop version. Additionally this feature is not supported by Report Message add-in. I don't think it will work for us so we may look at some third party solutions or invest time in developing own add-in. Thank you for the information :)
