### ISSUE TITLE
EDR Exclusion information is not complete

### ISSUE THREAD

**Issue by AndNovian** [MicrosoftDocs/microsoft-365-docs#12168]
The note about Defender Exclusion not applying to EDR Exclusion is useful, however from Customer perspective, it is confusing because there are no reference to EDR Exclusion, on how to do that? Currently the only method to do it is by Contacting Customer support. Please add this information so customer could directly refer to us when they need EDR exclusion.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/114455998/9fa6642f-9a5e-4596-ab2b-fe9a339057ee)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6bcf39-9a8c-7fa3-803a-508e7b74cc9b
* Version Independent ID: 9fd6d652-df16-7f4b-d253-6aee2362f836
* Content: [Configure and validate exclusions for Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-exclusions?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-exclusions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-exclusions.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@AndNovian Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12199

Once the author approves, the changes will be live.

Thanks
Sri
