### ISSUE TITLE
Share your business files with Teams, SharePoint, and OneDrive infographic PowerPoint link broken

### ISSUE THREAD

**Issue by kevhoyt** [MicrosoftDocs/microsoft-365-docs#12162]
The link for the 'Share your business files with Teams, SharePoint, and OneDrive' infographic to PowerPoint does not work. Just takes you to a generic PowerPoint infographics page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 236bd376-94b8-97b1-a46f-8d340c8ad05d
* Version Independent ID: bd8d12f6-40f4-b9bd-e97b-84dc8a77e705
* Content: [Microsoft 365 infographics for users](https://learn.microsoft.com/en-us/microsoft-365/solutions/infographics-for-users?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/infographics-for-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/infographics-for-users.md)
* Service: **o365-solutions**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by msbemba** [comment]
@kevhoyt Thank you for your feedback. It is not broken anymore and currently takes it to https://learn.microsoft.com/en-us/microsoft-365/solutions/infographics-for-users?view=o365-worldwide#share-your-business-files-with-teams-sharepoint-and-onedrive

Hope this helps!

Thanks
Sri

**Comment by kevhoyt** [comment]
Sorry, but I don't see this as fixed. When I click on the link for the PDF it takes me to a generic Infographic design templates page. Not to a PDF with the document loaded. The only one that works now is the one for Microsoft 365 security tips infographic. All the others go to a generic page and the Power Point for the infographic cannot be found.

cc: @yogkumgit

**Comment by yogkumgit** [comment]
@msbemba Please comment.

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder.

**Comment by msbemba** [comment]
@kevhoyt thank you for your feedback. Looks like the FW links are redirecting to a different page. I'll work with the author and update the links.

Thanks
Sri

**Comment by msbemba** [comment]
Email sent 29 JUn 2023

**Comment by samanro** [comment]
Hi all - I have republished these to the download center instead of the templates site and updated the fwlinks. Might take a minute for the links to start working again, but they should be fixed.

**Comment by yogkumgit** [comment]
Thanks. Closing.
