### ISSUE TITLE
update the "Deploy and manage Removable Storage Access Control using Intune"

### ISSUE THREAD

**Issue by PiotrWadolowski** [MicrosoftDocs/microsoft-365-docs#12172]
The public docs https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-intune?view=o365-worldwide require more clarification ofr customers.

On OMA-URI as ./Vendor/MSFT/Defender/Configuration/DeviceControl/PolicyGroups/%7b**[GroupId]**%7d/GroupData

Add information (note) what specific part need to be replaced in customer environment " **[GroupId]** ".

**Comment by msbemba** [comment]
@PiotrWadolowski Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12197

Once the author approves, the changes will be live.

Thanks
Sri
