### ISSUE TITLE
Web content filter for 3rd party browsers isn't working after upgraded to 4.18.23050.3.

### ISSUE THREAD

**Issue by sparkf1** [MicrosoftDocs/microsoft-365-docs#12176]
Web content filter for 3rd party browsers isn't working after upgraded to 4.18.23050.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61d65c37-bbb6-5c7a-8405-5994badd0b23
* Version Independent ID: 61d65c37-bbb6-5c7a-8405-5994badd0b23
* Content: [Microsoft Defender Antivirus security intelligence and product updates](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates?view=o365-worldwide#security-intelligence-updates)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@sparkf1 Thank you for your feedback. Sorry to hear that you have a technical issue. I'd recommend you contacting Support via the need help section on the admin center, so that a support engineer can fix or raise a bug with the Product group to fix this.

Hope this helps!

Thanks
Sri
