### ISSUE TITLE
Companion app has been retired

### ISSUE THREAD

**Issue by Spence10873** [MicrosoftDocs/microsoft-365-docs#12173]
We state in this doc that a companion app is available in iOS an Android. As of December 2022, it was retired. I would also like to add that the UX in the mobile web page for managing bookings is basically unusable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7484dd4-5d94-dd6c-0dbe-551c852677c1
* Version Independent ID: 257d60e2-9313-e08b-dccf-120cb4b30f5b
* Content: [Microsoft Bookings Frequently Asked Questions](https://learn.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-faq.yml)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Spence10873 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12193

Once the auhtor approves, the changes will be live.

Thanks
Sri
