### ISSUE TITLE
PDF paper size

### ISSUE THREAD

**Issue by intention-it** [MicrosoftDocs/microsoft-365-docs#12171]
These instructions contain a PDF designed for a USA paper size, and advice to "print it on letter, legal, or tabloid (11 x 17) size paper". Note that in most of the world we would use ISO paper sizes e.g. A4, and/or measure in mm. At least specify inches if we are sent searching for 11x17.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78fbba03-39f0-9d11-12b0-b57830942db8
* Version Independent ID: f14feef7-7041-5e60-c193-8eb480097511
* Content: [Microsoft 365 tenant-to-tenant migrations - Microsoft 365 Enterprise](https://learn.microsoft.com/en-gb/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by temanteleary** [comment]
@yogkumgit I am updating the document to specify "inches" for the 11 x 17 paper size referenced in the document as the comment suggested.  Going to close this issue.
