### ISSUE TITLE
Contradicting information regarding Quarantine data retention timeframe in Microsoft defender

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/microsoft-365-docs#12179]
This is the exact text from Group policy setting in Windows 11 22631.1830

>  If you disable or do not configure this setting, items will be kept in the quarantine folder indefinitely and will not be automatically removed.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/118815227/02fd353d-8cd5-4076-a361-75ce4c280712)

But [this web page](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus) says Quarantined items will be deleted after 90 days by default.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/118815227/92014f43-d629-4f60-8473-769413ad70e7)

I'm not using Defender for Endpoint, I use the normal Microsoft Defender for consumer, and the page says it also applies to Microsoft Defender.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/118815227/c5c13a86-d1a6-4906-8c76-c460f471855a)

So I'm reporting this contradicting info to be reviewed and fixed, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c974b4-7004-d52c-0ffe-c6f3729477f9
* Version Independent ID: 7162a35d-fc78-54ac-531a-02ec8c07a8ff
* Content: [Configure remediation for Microsoft Defender Antivirus detections](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@HotCakeX Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12195

Once the author approves, the changes will be live.

Thanks
Sri
