### ISSUE TITLE
Requirements for using Microsoft 365  Lighthouse

### ISSUE THREAD

**Issue by ShawnHag** [MicrosoftDocs/microsoft-365-docs#12183]
On this page, it says that "Only MSPs are required to enroll in the CSP program; the customers they manage do not need to enroll in the CSP program"

But on the Frquently asked page (the URL below)
https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-faq?view=o365-worldwide#how-much-does-microsoft-365-lighthouse-cost
it also says that "who have a Cloud Solution Provider (CSP) relationship with their customers. Note that indirect providers aren't currently supported by Lighthouse. "

My question is, 
when a MSP tries to use Microsoft 365 Lighthouse with few customers, does the customers Microsoft 365 related licenses have to be provided by CSP program? Or will it be fine if licenses are supplied through EA program?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4b28125-703d-234a-b52f-2a46de32ffa6
* Version Independent ID: 55d48817-9185-2fd9-55cf-cea275666fbe
* Content: [Requirements for Microsoft 365 Lighthouse - Microsoft 365 Lighthouse](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-requirements.md)
* Service: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4b28125-703d-234a-b52f-2a46de32ffa6
* Version Independent ID: 55d48817-9185-2fd9-55cf-cea275666fbe
* Content: [Requirements for Microsoft 365 Lighthouse - Microsoft 365 Lighthouse](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-requirements.md)
* Service: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@ShawnHag Thank you for your feedback. The licenses can be a part of the EA or CSP as long as you have a Cloud Solution Provider (CSP) relationship with the customer.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ShawnHag Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
