### ISSUE TITLE
Windows and Office 365 deployment lab kit download links

### ISSUE THREAD

**Issue by mmtechconsulting** [MicrosoftDocs/microsoft-365-docs#12182]
The link to download the lab usually redirects to an old version of the lab. Once downloaded and installed it seems not to be functional because everything has expired.

Can you post the correct download link for Windows 11 please?

**Comment by yogkumgit** [comment]
@mmtechconsulting Please indicate which document you are referring to. Thanks

**Comment by msbemba** [comment]
@mmtechconsulting Thank you for your feedback. Are you referring to https://learn.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide ? The Windows and Office 365 deployment lab kit seems to be updated recently.

Hope this helps!

Thanks
Sri
