### ISSUE TITLE
Timelines for deletion of data

### ISSUE THREAD

**Issue by Richard-Barr3tt** [MicrosoftDocs/microsoft-365-docs#1218]
In the section titled 'Revoke your keys and start the data purge process' in section 5 for Exchange and section 3 for SharePoint there is no mention of timescales. Is it possible to add some reference in for timescales for this process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bbe84f4-e076-750f-62b7-842c9cd03736
* Version Independent ID: 3380a064-f592-a639-fc4f-35ec021438a3
* Content: [Manage Customer Key for Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-manage#feedback)
* Content Source: [microsoft-365/compliance/customer-key-manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-manage.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by MaratMussabekov** [comment]
Hello @Richard-Barr3tt,
timelines depend on data to be deleted.
Microsoft usually refers to [Exit Planning](https://servicetrust.microsoft.com/ViewPage/TrustDocuments?command=Download&downloadType=Document&downloadId=77ea7ebf-ce1b-4a5f-9972-d2d81a951d99&docTab=6d000410-c9e9-11e7-9a91-892aae8839ad_FAQ_and_White_Papers) document in this case (the link to the document is in the article too).
Thank you

**Comment by mypil** [comment]
@Richard-Barr3tt  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
