### ISSUE TITLE
Slight correction on verbiage

### ISSUE THREAD

**Issue by lonstev** [MicrosoftDocs/microsoft-365-docs#12187]
The references to the 'Organization profile' are "Organizational Settings profile" and "On the Org settings page, select Organizational profile.
On the Organizational profile page,"

This should be 'Organization profile', not 'Organizational profile' or 'Organizational Settings profile'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eda44995-3561-2f08-e776-5359b0aaf37c
* Version Independent ID: eda44995-3561-2f08-e776-5359b0aaf37c
* Content: [Select the domain to use for email from Microsoft 365 products - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/select-domain-to-use-for-email-from-microsoft-365-products.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@lonstev Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12191

Once the author approves, the changes will be live.

Thanks
Sri
