### ISSUE TITLE
Attack Simulation appears pretty flakey for the past month - doesn't always send out a simulation

### ISSUE THREAD

**Issue by DeePelleCANdo** [MicrosoftDocs/microsoft-365-docs#12196]
Have been trying to send out a simulation for over six weeks that actually works
all the way through.
I typically will have it sent to myself and if it is satisfactory, then I send it out to others.
The first bunch will not even display correctly once I click on the link to test going to any 
of the landing pages.
Moved to another payload and that one won't even send out.  (I am not new to this ...
have sent out many in the past.)

Put in a support ticket a few weeks ago and that just sits.  Rock and a hard place at
the moment.  Anyone else going through the same issues right now?

**Comment by msbemba** [comment]
@DeePelleCANdo Thank you for your feedback. This looks like a technical issue and you have done the right thing by opening a support ticket. I'd suggest you follow up with the support engineer to resolve this issue.

Hope this helps!

Thanks
Sri
