### ISSUE TITLE
Email Notifications and Policy Tips are both required

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/microsoft-365-docs#1219]
The article should note that when configuring User Notifications in a DLP Rule in the Security and Compliance Center, both Email Notifications and Policy Tips are required. One cannot be configured without the other. The way the article is written makes it sound like these two option are independent. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@terrogin 
issue addressed in content and published
