### ISSUE TITLE
"Submit files for analysis" link leads to 404

### ISSUE THREAD

**Issue by jschwager** [MicrosoftDocs/microsoft-365-docs#12205]
The "[Submit files for analysis](https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/submission-guide.md)" link under the "Submitting files for analysis" section results in a 404 error. It appears that the ".md" at the end of the hyperlink should be removed to resolve this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc98cb60-e7c8-72d1-4422-305f9266af5f
* Version Independent ID: fc98cb60-e7c8-72d1-4422-305f9266af5f
* Content: [Manage exclusions for Microsoft Defender for Endpoint and Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-antivirus-exclusions?view=o365-worldwide#submissions-suppressions-and-exclusions)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-antivirus-exclusions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-antivirus-exclusions.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@jschwager Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12220

Once the author approves, the changes will be live.

Thanks
Sri
