### ISSUE TITLE
License Hyperlink to the 10 year Add-On license.

### ISSUE THREAD

**Issue by SARSAX** [MicrosoftDocs/microsoft-365-docs#12206]
[Enter feedback here]
https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide

Please do add the hyperlink to buy the 10 year Add-On license.

Thank You.
![auditlogretentiondashboardpriority](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/135763609/6cbc7142-d9ae-4a05-a926-33a7471d0fda)
![ediscovery-create-new-audit-retention-policy](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/135763609/aeb4199b-cea5-4570-9343-5485be3fa30f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@SARSAX Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12221

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by SARSAX** [comment]
Thank You!

Regards,
Sarthak Saxena

**Comment by yogkumgit** [comment]
@SARSAX Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
