### ISSUE TITLE
Email sent by the delist portal are not DMARC compliant and thus blocked as spam... rather ironically one might add...

### ISSUE THREAD

**Issue by rednoah** [MicrosoftDocs/microsoft-365-docs#1220]
5.7.26 Unauthenticated email from microsoft.com is not accepted due to 5.7.26 domain's DMARC policy. Please contact the administrator of 5.7.26 microsoft.com domain if this was a legitimate mail. Please visit 5.7.26 https://support.google.com/mail/answer/2451690 to learn about the 5.7.26 DMARC initiative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Use the delist portal to remove yourself from the Office 365 blocked senders list - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis#feedback)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
@rednoah My thanks for the error message you dropped here. I'm looking at delist issues again. I appreciate the information!

**Comment by yogkumgit** [comment]
@MSFTTracyP  Kindly answer and help us in resolving this issue. Thanks.

**Comment by MSFTTracyP** [comment]
@yogkumgit Hi Yogesh. I've elevated this issue more than once and am looking at a means to be more effective in this effort. Thanks for staying on it.

**Comment by MSFTTracyP** [comment]
@rednoah, I realize this happened quite some time back, but are you or others still experiencing this issue? Where are you seeing it precisely, and would you happen to have a sample of the non-compliance, such as Header info? If you do, please let me know. This is certainly something you've probably headed to Support with some time ago, and if so, please feel free to let us know if a solution was reached by your Support person and yourself.

**Comment by rednoah** [comment]
Sorry, I forgot the details. I think it was in the context of `*.hotmail.com` email addresses not accepting email from me, and me filling out some online form to say I'm not a spammer. I did switch service provider / outgoing IP though since then, and things have resolved itself. No issues right now.
