### ISSUE TITLE
Data Security

### ISSUE THREAD

**Issue by jarednealeigh** [MicrosoftDocs/microsoft-365-docs#1221]
Hey my org is very concerned with maintaining the integrity of our data, I ran a wireshark capture of a test upload to the EDM cloud and it appears the application data is encrypted w/ TLS1.2 over 443, but I was looking for more concrete details from MSFT and if this encryption is end-to-end?

**Comment by mypil** [comment]
@jarednealeigh - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@jarednealeigh - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.
