### ISSUE TITLE
Defender for Identity Integration

### ISSUE THREAD

**Issue by Wallace4444** [MicrosoftDocs/microsoft-365-docs#12211]
The document states that the integration with Defender for Identity is configured via https://portal.atp.azure.com. Ignoring the fact that portal is going to be removed from June 30, most tenancy's redirect to security.microsoft.com.

I couldn't locate any settings within MDE or MDI to enable integration between the two anymore.

Is there any way to configure this integration now, or is it enabled by default as it's all under the M365 Defender umbrella?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3c074f5-bd58-6b72-d891-3d9fe0118767
* Version Independent ID: 2eea3a11-be82-49bc-6056-f4fba30bd638
* Content: [Configure advanced features in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-features?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/advanced-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/advanced-features.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Wallace4444 Thank you for your feedback. You are right, it is enabled by default as it's all under the M365 Defender umbrella.

We will make changes to the document post the June 30 cut-off date. 

Hope this helps!

Thanks
Sri
