### ISSUE TITLE
No Message encryption report in the Microsoft Purview compliance portal

### ISSUE THREAD

**Issue by zagee1** [MicrosoftDocs/microsoft-365-docs#12217]
In the Microsoft Purview compliance portal there is no "Message encryption report"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10cd0b42-9f8f-265f-1f4b-f5b73f811cfc
* Version Independent ID: f400b434-c016-7ee5-ef38-b57b90dcab95
* Content: [Revoke email encrypted by Advanced Message Encryption - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/revoke-ome-encrypted-mail?view=o365-worldwide#encrypted-emails-that-you-can-revoke)
* Content Source: [microsoft-365/compliance/revoke-ome-encrypted-mail.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/revoke-ome-encrypted-mail.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@zagee1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12244

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@zagee1 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
