### ISSUE TITLE
Article does not mention that actions are required

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/microsoft-365-docs#1222]
According to MS support, the default behavior of a DLP policy when no alert is configured, is to not alert or trigger. This isn't specified in the article. Testing verifies this is true with default information types. However, Custom Information Types do alert when there is no action defined in the policy. 

The article should include a note about the requirement for an action to be defined, and that this is only true with default information types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by joinimran** [comment]
@terrogin  Thanks for sharing this information. Can you please share your conversation happened with MS Support. This can better help me to understand this and to update the document.

**Comment by mypil** [comment]
@terrogin   - Can you please respond to the query of joinimran?

Thank you.

**Comment by terrogin** [comment]
> @terrogin Thanks for sharing this information. Can you please share your conversation happened with MS Support. This can better help me to understand this and to update the document.

Yes, would you like the entire email chain here, or is there somewhere better I can send it?

**Comment by joinimran** [comment]
@terrogin - Can you please share the entire email chain that will surely help to extract the required information.

**Comment by chrfox** [comment]
HI @terrogin 
If you can, and it doesn't violate any of your orgs privacy rules or laws, please update this thread with the relevant context, problem and resolution of your support issue.

**Comment by terrogin** [comment]
I will, yes, but need a little time to clear identifying information. As a side note, I've performed additional testing that appears to confirm support's response on the matter.

Sent from Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by terrogin** [comment]
Here is the conversation. I've removed the ticket # and other information:



-------------------------------------------------------------------------------------
Support Personnel (Microsoft) 
	Monday, October 21, 2019 5:12 PM GMT
	The expectation for reporting is that you do need at least one action configured or there's no need for reporting.  The behavior you have with the custom SI and TEAMS is curious.  

Thanks
Support Personnel

-------------------------------------------------------------------------------------
User@company.com

	Monday, October 21, 2019 4:01 PM GMT
	Thanks, so at this point are we saying that this is all expected behavior?

-------------------------------------------------------------------------------------
Support Personnel (Microsoft) 
	Monday, October 21, 2019 2:22 PM GMT
	Hi User
Sorry for the delayed response.  I reviewed the documentation and this isn't outlined regarding the reporting.  I can make a request to the content writers to add something about it though.  

Support Personnel

 
-------------------------------------------------------------------------------------
User@company.com 

	Friday, October 11, 2019 6:45 PM GMT
	Well, I know the custom SITs detect without actions. So far it appears only the built in SITs don’t detect without actions, and Teams (whether custom or built in). 
I certainly understand why customization is typically out of scope, but I'm trying to understand more about the inconsistent behavior. 
Is there any documentation about this? It seems like it was known that built-in SITs shouldn’t detect without actions, but I haven't seen any articles about that, myself

-------------------------------------------------------------------------------------
Support Personnel (Microsoft) 
	Friday, October 11, 2019 6:18 PM GMT
	That would indicate the issue likely with the custom SI.  Just to confirm you might want to create another policy and add just one of the custom regex and test. 
In addition, if you can send me the custom rule package with custom SI I can review - customization is outside the scope for support but it might be simple enough to spot an issue. 

Support Personnel

-------------------------------------------------------------------------------------
User@company.com 

	Thursday, October 10, 2019 2:49 PM GMT
	Hi Support Personnel, 
 
I added a new policy and rules yesterday looking for the built-in SIT for US SSN. I sent an email full of SSN’s that tested successfully when I tested the SIT. This morning there are no detections. What happens if you create a custom SIT on your end and apply a rule with no action? Does that one get detected?
 
 -------------------------------------------------------------------------------------
Support Personnel (Microsoft) 
	Wednesday, October 9, 2019 3:31 PM GMT
	Quick question but it looked like the SI in the rules are custom regex? If that's right, can you test using one of the built-in SI to see if the behavior changes?  The DLP should report when there's an action (no need to report if there's no action to take) But since you have reports on rules without actions, that's unexpected so am wondering if a possible explanation is in the SI you have being detected?

**Comment by terrogin** [comment]
Here is the email chain. I've removed the ticket number and other identifying information. The email chain is a follow-up to a phone conversation where we noticed that default information types were not triggering DLP alerts while custom information types were. Each policy was configured without an action.


-------------------------------------------------------------------------------------
Support Personnel (Microsoft) 
Monday, October 21, 2019 5:12 PM GMT
The expectation for reporting is that you do need at least one action configured or there's no need for reporting.  The behavior you have with the custom SI and TEAMS is curious.  

Thanks
Support Personnel

-------------------------------------------------------------------------------------
User@company.com

Monday, October 21, 2019 4:01 PM GMT
Thanks, so at this point are we saying that this is all expected behavior?

-------------------------------------------------------------------------------------
Support Personnel (Microsoft) 
Monday, October 21, 2019 2:22 PM GMT
Hi User
Sorry for the delayed response.  I reviewed the documentation and this isn't outlined regarding the reporting.  I can make a request to the content writers to add something about it though.  

Support Personnel

 
-------------------------------------------------------------------------------------
User@company.com 

Friday, October 11, 2019 6:45 PM GMT
Well, I know the custom SITs detect without actions. So far it appears only the built in SITs don’t detect without actions, and Teams (whether custom or built in). 
I certainly understand why customization is typically out of scope, but I'm trying to understand more about the inconsistent behavior. 
Is there any documentation about this? It seems like it was known that built-in SITs shouldn’t detect without actions, but I haven't seen any articles about that, myself

-------------------------------------------------------------------------------------
Support Personnel (Microsoft) 
Friday, October 11, 2019 6:18 PM GMT
That would indicate the issue likely with the custom SI.  Just to confirm you might want to create another policy and add just one of the custom regex and test. 
In addition, if you can send me the custom rule package with custom SI I can review - customization is outside the scope for support but it might be simple enough to spot an issue. 

Support Personnel

-------------------------------------------------------------------------------------
User@company.com 

Thursday, October 10, 2019 2:49 PM GMT
Hi Support Personnel, 
 
I added a new policy and rules yesterday looking for the built-in SIT for US SSN. I sent an email full of SSN’s that tested successfully when I tested the SIT. This morning there are no detections. What happens if you create a custom SIT on your end and apply a rule with no action? Does that one get detected?
 
 -------------------------------------------------------------------------------------
Support Personnel (Microsoft) 
Wednesday, October 9, 2019 3:31 PM GMT
Quick question but it looked like the SI in the rules are custom regex? If that's right, can you test using one of the built-in SI to see if the behavior changes?  The DLP should report when there's an action (no need to report if there's no action to take) But since you have reports on rules without actions, that's unexpected so am wondering if a possible explanation is in the SI you have being detected?

**Comment by chrfox** [comment]
note added to topic and published
