### ISSUE TITLE
Data state column contains incorrect information for Devices under location link

### ISSUE THREAD

**Issue by maccaoz** [MicrosoftDocs/microsoft-365-docs#12227]
### 
[Enter feedback here]
Link:  https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-reference?view=o365-worldwide#locations

In the devices section, we state that Data at Rest is scanned on Endpoints.  This is incorrect and needs to be removed.  Currently we only support data in use and data in motion.

Data is classified and scanned on creation and modification.  Pre existing files are not crawled at rest on the device.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77dd99ae-2687-1e3f-341e-04a8e3d4acc2
* Version Independent ID: 1948ad4b-3bc1-4f49-fded-9582a854cbbd
* Content: [Data Loss Prevention policy reference - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-reference?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-policy-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-policy-reference.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
@maccaoz - With JIT enabled, all files are protected from egress by default by the candidate policy until a scan is completed.
