### ISSUE TITLE
Need to call out that eDiscovery/Content Search is not an email backup tool

### ISSUE THREAD

**Issue by LoGlenn** [MicrosoftDocs/microsoft-365-docs#12222]
[Can we please have a statement on this page stating that eDiscovery/Content Search are not email backup tools. Customers keep opening cases believing that they can just import the data into the mailbox. The data exported contains folders that have hidden folder structures inside of Outlook, but they are there. So, the data has to be edited for an import. 

We do not provide documentation or anything saying how this can be done. We normally state once a case is opened that the customer has to do this manually with an editing tool or use a 3rd party tool of their choosing. 

- If we can state up front that this is not designed to do this, then we can try to avoid issues.  
- If we can state it would have these additional folder structures by design. That may also help.

**Down below is where in this article that the confusion comes from.**

https://learn.microsoft.com/en-us/microsoft-365/compliance/restore-an-inactive-mailbox?view=o365-worldwide#:~:text=Note,content%20search%20results

Note

You can't recover or restore an inactive mailbox that's configured with an auto-expanding archive. If you need to recover data from an inactive mailbox with an auto-expanding archive, use content search to export the data from the mailbox and then import to another mailbox. For instructions, see following articles:

[Content search](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-content-search?view=o365-worldwide)
[Export content search results](https://learn.microsoft.com/en-us/microsoft-365/compliance/export-search-results?view=o365-worldwide)]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e422ac12-4a97-3561-d450-d2e08b9dddaf
* Version Independent ID: f0d35b02-19a2-d0b9-53a0-b395915f4bec
* Content: [Restore an inactive mailbox - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/restore-an-inactive-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/restore-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/restore-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
@LoGlenn  Yes, absolutely fair feedback & will address today.  Thanks for flagging this!

**Comment by cabailey** [comment]
Update live now, closing.
