### ISSUE TITLE
No information on finishing date

### ISSUE THREAD

**Issue by probichaux** [MicrosoftDocs/microsoft-365-docs#12226]
The doc says that for commercial customers "deprecation of TLS 1.0 and 1.1 will begin October 15, 2020 and rollout will continue over the following weeks and months." That was a long time ago :) Is the deprecation complete? If so, please say so. If not, say that too. The current text is ambiguous.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f7e4139-a562-6b81-6584-277efc4f6103
* Version Independent ID: e812b33a-f183-8b6a-bab0-447ddab2f26f
* Content: [Preparing for TLS 1.2 in Office 365 and Office 365 GCC - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/prepare-tls-1.2-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prepare-tls-1.2-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **shmehta**

**Comment by yogkumgit** [comment]
@probichaux Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
