### ISSUE TITLE
Invoice Charges while i have a student free account 

### ISSUE THREAD

**Issue by mahamohyeldin** [MicrosoftDocs/microsoft-365-docs#12233]
I have a student free account on azure, and now i received an unexpected invoice with a total 65.15 USD, below two screenshots indicating the invoice details. Why Microsoft withdrawn the charges from my bank card?!
![credit1](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/34853660/3b3d47f2-091e-496f-8dbe-8cdc54525d99)
![credit](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/34853660/d884fd01-536b-452b-8144-2fa9bef717d6)

**Comment by HotCakeX** [comment]
There is this text above the invoice number, letting you know the card will be charged within 2 days.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/118815227/e4c64293-86b7-4d7e-8489-7114e99c61ef)

Azure support: https://azure.microsoft.com/en-us/support/

**Comment by yogkumgit** [comment]
@mahamohyeldin Considering the nature of the issue please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
