### ISSUE TITLE
Outdated suspense dates

### ISSUE THREAD

**Issue by probichaux** [MicrosoftDocs/microsoft-365-docs#12234]
This page says: "Services began transitioning to the new Root CAs in January 2022 and will continue through October 2022." It's now June 2023, and the page should be updated to indicate the current state of the rollout. Is it done? Is it still ongoing? The world wonders.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c23df2b9-0e0e-1a54-2f42-effb9387459a
* Version Independent ID: c23df2b9-0e0e-1a54-2f42-effb9387459a
* Content: [Office TLS certificate changes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-tls-certificates-changes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md)
* Service: **o365-seccomp**
* GitHub Login: @pshelton-skype
* Microsoft Alias: **pshelton**

**Comment by msbemba** [comment]
@probichaux Thank you for your feedback. I have removed the end date as the transition is still in progress (PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12245) and the existing CA Common Names and/or thumbprints will be required through at least October 2023 based on the lifetime of existing certificates.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@probichaux Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
