### ISSUE TITLE
Groups has changed to Teams & groups

### ISSUE THREAD

**Issue by cwsmith-160** [MicrosoftDocs/microsoft-365-docs#12232]
It took me a minute longer to find "Shared mailboxes" than it should have if the bold "Group" text had been labeled as it appears currently in the admin center as "Teams & groups".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 198eb002-1d99-5a13-05d4-34d1cbb8d9d9
* Version Independent ID: 6218b3c9-f0a2-ed0e-ef0a-c99c3c280030
* Content: [Configure shared mailbox settings - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/configure-a-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-a-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-a-shared-mailbox.md)
* Service: **microsoft-365-business**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@cwsmith-160 - Thanks for providing this feedback. We updated those references to reflect the current UI. The updated help article should go live later this afternoon.
