### ISSUE TITLE
What is the use of $Rule Var in step 5

### ISSUE THREAD

**Issue by FindsTheLost** [MicrosoftDocs/microsoft-365-docs#1223]
In step 5 
$rule = New-CaseHoldRule -Name $search.Name -Policy $policy.Identity
You are setting a $rule variable that is never used. why is this needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b602a57-ddf2-74b2-f9f3-082966d29fef
* Version Independent ID: 7fed9668-05f9-bff4-fd5e-6486e541b54e
* Content: [Migrate legacy eDiscovery searches and holds to the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/migrate-legacy-ediscovery-searches-and-holds#feedback)
* Content Source: [microsoft-365/compliance/migrate-legacy-eDiscovery-searches-and-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/migrate-legacy-eDiscovery-searches-and-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@FindsTheLost Thanks for the heads up/catch. I'm checking with PM, but I think you're right that saving to variable isn't correct. When you create a hold policy you have to create a correspond hold rule. So I think this command should probably be changed to 

New-CaseHoldRule -Name $search.Name -Policy $policy.Identity

Also, if the in-place hold that you're migrating is a query-based hold, then you'd have to add the -ContentMatchQuery parameter to the above command. So using the example in step 3 in this topic, the command would be:

New-CaseHoldRule -Name $search.Name -Policy $policy.Identity -ContentMatchQuery "Smoking gun"

I'll follow up to this issue to confirm and then update the topic accordingly.

**Comment by markjjo** [comment]
@FindsTheLost $Rule variable in step 5 does create the rule. Apologies for my mindfart of implying that rule doesn't get created. Original thinking of using the variable was in case you needed the rule properties to run another cmdlet. I'm going to remove the variable and also fix a typo in the Powershell connection instructions (Import-PSSession **$sccSession** -DisableNameChecking). These changes should be live tomorrow. Thanks again the heads up.
