### ISSUE TITLE
Training Classifiers not available in Business Premium

### ISSUE THREAD

**Issue by beachgrootbreadalto** [MicrosoftDocs/microsoft-365-docs#12235]
Please correct your documentation to reflect the fact that training classifiers are not available in BP licensed tenants, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c11defbb-77c3-c56c-41f2-65e3a4dfafc5
* Version Independent ID: bde5b77f-712d-f811-2315-d775d66fc8a6
* Content: [Get started with the default DLP policy - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/get-started-with-the-default-dlp-policy?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/get-started-with-the-default-dlp-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-with-the-default-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@beachgrootbreadalto Thank you for your feedback. Classifiers are a Microsoft 365 E5, or E5 Compliance feature. You must have one of these subscriptions to make use of them. This is available in the prerequisites section of trainable classifiers -https://learn.microsoft.com/en-us/microsoft-365/compliance/classifier-get-started-with?view=o365-worldwide#licensing-requirements

Hope this helps!

Thanks
Sri

**Comment by beachgrootbreadalto** [comment]
Good morning. Confusion stems from the fact that the Default DLP Policy can exist without the mentioned classifiers (for example with a Business Premium tenant) without mention that the classifier policies will only appear in licensed up tenants. Thanks!

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@beachgrootbreadalto Thank you for your feedback. I have added that requirement as a note in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12268

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@beachgrootbreadalto Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
