### ISSUE TITLE
request for clarification and Applying Sensitivity Labels

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1224]
There are 3 ways to classify: manual, automatic and trainable, but the Important note above states that "both types of classifiers" this is unclear, please rewrite to explicitly identify which types can be used for conditions.

Also what about applying a Sensitivity Label based on a condition, is this not possible? is it on the roadmap? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3c5c98-9f47-9512-b932-2f72822796d2
* Version Independent ID: fd477cf9-4ee0-544f-10c6-f3dfccb10186
* Content: [Getting started with trainable classifiers (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-getting-started-with)
* Content Source: [microsoft-365/compliance/classifier-getting-started-with.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-getting-started-with.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by MaratMussabekov** [comment]
Dear @DeanGross ,
**There are 3 ways to classify: manual, automatic and trainable, but the Important note above states that "both types of classifiers" this is unclear, please rewrite to explicitly identify which types can be used for conditions.** - PR to fix that created

**Also what about applying a Sensitivity Label based on a condition, is this not possible? is it on the roadmap?** - it is possible, more details - [Apply a sensitivity label to content automatically](https://docs.microsoft.com/microsoft-365/compliance/apply-sensitivity-label-automatically)

Thank you

**Comment by chrfox** [comment]
HI @DeanGross 
Both types of classifiers refers to built-in and trainable, fixed, sorry for the confusion
