### ISSUE TITLE
Could you please add Best practice or Hints of customizing SIT?

### ISSUE THREAD

**Issue by kash1064** [MicrosoftDocs/microsoft-365-docs#12248]
[Enter feedback here]
Hello team.

The settings of SIT seems to be tradeoffs with performance. 
I know a lot of SIT settings and also generic keywords, or ambiguous regex will cause of performance issue in MDE onboarded device.

Could you add Best practice or Hints of customizing SIT in this Docs to avoid these performance issues?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1391cf1-588f-a4a9-8692-8c07cf1e459a
* Version Independent ID: d57337a5-d0f3-de26-2259-6b7fa7613d05
* Content: [Customize a built-in sensitive information type - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/customize-a-built-in-sensitive-information-type?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customize-a-built-in-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customize-a-built-in-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@kash1064 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
