### ISSUE TITLE
The storage chart is calculated based on what exactly?

### ISSUE THREAD

**Issue by riohedfield** [MicrosoftDocs/microsoft-365-docs#12249]
Hello, 

Question about the documentation that is not precise and which I wish that you adjust for the public for better understanding of the charts:
The Mailbox Usage > Storage chart is calculated based on TotalItemSize or (TotalItemSize + TotalDeletedItemSize) in Get-MailboxStatistics? are the Recoverable Items included?
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/59142439/f603c056-1f02-4c7b-b852-be0b500b5a0c)

It will be really helpful to know what is really included there.

Thank you in advance.
Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e612a4e4-d051-27a7-e54a-bb1ac3fe0849
* Version Independent ID: 653be32f-e4e8-8a72-98b3-a629238ecbd5
* Content: [Microsoft 365 admin center mailbox usage reports - Microsoft 365 admin](https://learn.microsoft.com/en-US/microsoft-365/admin/activity-reports/mailbox-usage?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/mailbox-usage.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@riohedfield Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12285

Once the author approves, the changes will be live.

Thanks
Sri
