### ISSUE TITLE
Indicate Role needed to see devices 

### ISSUE THREAD

**Issue by marcio-PBS** [MicrosoftDocs/microsoft-365-docs#12253]
Please indicate which role is required to see "Devices" under Assets. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1737f-574e-4751-66e8-6c9bd441ff9d
* Version Independent ID: dbb1737f-574e-4751-66e8-6c9bd441ff9d
* Content: [Manage devices in Microsoft Defender for Business](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-manage-devices?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-manage-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-manage-devices.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @marcio-PBS and thank you so much for your feedback. Users must have one of the following roles assigned to view the list of onboarded devices: Global Administrator, Security Administrator, or Security Reader. Only those who have the Global Administrator role can do setup and configuration tasks, including onboarding devices, but users with one of those three roles can view the device inventory (Microsoft 365 Defender portal > Assets > Devices). 

I have updated the article and you should see the changes go live at around 4 p.m. Pacific Time.
