### ISSUE TITLE
Typo in article: int-phishing

### ISSUE THREAD

**Issue by jprknight** [MicrosoftDocs/microsoft-365-docs#12254]
In ant-phishing policies,

TYPO int-phishing => inti-phishing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-policies-about?view=o365-worldwide#spoof-protection-and-sender-dmarc-policies)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-policies-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-policies-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jprknight, I can't see what you're calling out. Can you modify the article directly as explained [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md)? Just @ include me in the Comments section so I'll see it.
