### ISSUE TITLE
Confusion re: labels

### ISSUE THREAD

**Issue by CreelMike** [MicrosoftDocs/microsoft-365-docs#1226]
This article uses retention labels in a manner more commonly served by sensitivity labels...  In fact, the retention labels listed nearly line up with the default sensitivity labels described in the article linked to above.  Using retention labels in this fashion seriously limits the capability to use these labels for disposition scenarios.  Please review to determine if recommendation should be modified to make use of sensitivity labels as the fundamental labeling control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e992a02b-9be0-8ae1-5078-56435edff356
* Version Independent ID: 96d3d112-27c7-c781-ebbf-23ca7eeb316e
* Content: [Secure files in Microsoft Teams - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-files-in-teams)
* Content Source: [microsoft-365/security/office-365-security/secure-files-in-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-files-in-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@CreelMike  - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by CreelMike** [comment]
Thanks, Joyce, but I’m afraid that perhaps my feedback wasn’t clear…  I’m well versed in uservoice, but I wasn’t asking for a change in the product -- I believe the documentation is wrong…  Could you please review again?  I’d be glad to discuss if that helps…

**Comment by mypil** [comment]
@CreelMike - We value collaboration and appreciate your efforts to clarify the docs.
Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also [create a Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.
