### ISSUE TITLE
Need this page updated like the other one to avoid issues.

### ISSUE THREAD

**Issue by LoGlenn** [MicrosoftDocs/microsoft-365-docs#12263]
[Enter feedback here]
We have this article still stating what the other one we had corrected used to say. We get customers mad at support trying to use eDiscovery/Content Search as an email backup tool. It is for finding data often for legal purposes. It is not an email restore tool and this is by design. 

**Current problem version:**
https://learn.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-auto-expanding-archives:~:text=eDiscovery%20holds.-,Inactive%20mailboxes%20and%20auto%2Dexpanding%20archives,to%20search%20an%20inactive%20mailbox%20and%20export%20the%20search%20results%2C%20see%3A,-Content%20search

**Fixed version from similar article:**
https://learn.microsoft.com/en-us/microsoft-365/compliance/restore-an-inactive-mailbox?view=o365-worldwide#:~:text=Note,see%20following%20articles%3A

Copy of screen shot of previous one in case it helps.
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/104854134/4d5f0343-fd58-4ec0-a3cc-c96ba844e053)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Learn about inactive mailboxes - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-auto-expanding-archives)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Thank you for flagging this second reference.  Fixing today.

**Comment by LoGlenn** [comment]
Not sure if its too late, can you do this one as well - https://learn.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-auto-expanding-archives.

**Comment by cabailey** [comment]
Wasn't that the original link in this issue, now fixed?  Currently says:

"If, for compliance reasons, you need to recover data from an inactive mailbox with an auto-expanding archive, use content search to export the data from the mailbox. This action is supported for eDiscovery purposes only, and can't be used as a backup solution."

Did you mean to paste a different link?

**Comment by LoGlenn** [comment]
Hello Cabailey,

You are right, wrong link (Face palm). Here is hopefully the 3rd and final one that should be updated. It is for Recovering, not that restore and learn about inactive is handled.

https://learn.microsoft.com/en-us/microsoft-365/compliance/recover-an-inactive-mailbox?view=o365-worldwide#:~:text=You%20can%27t%20recover,see%20following%20articles%3A

I appreciate the help on this.

**Comment by cabailey** [comment]
OK, updating now.  Good example of why I always aim for publishing a technical statement once rather than repeating it over multiple articles and then have problems later chasing down all the references when it needs updating.  Not a strategy my predecessor subscribed to, apparently :)
