### ISSUE TITLE
CAT:HPHISH missing

### ISSUE THREAD

**Issue by partlycloudyGE** [MicrosoftDocs/microsoft-365-docs#1227]
Please add CAT:HPHISH! High Confidence Phish is launched in ATP Antispam Policy but not documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers#feedback)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@partlycloudyGE - Thank you for submitting feedback.

Please see this https://github.com/MicrosoftDocs/microsoft-365-docs/issues/486#issuecomment-540828898 from one of the authors - "Any headers not documented here are internal and used exclusively by the Microsoft anti-spam team for diagnostic purposes."
