### ISSUE TITLE
Mailbox Audit

### ISSUE THREAD

**Issue by Daiannec** [MicrosoftDocs/microsoft-365-docs#12273]
The **MailboxLogin** option is not available for auditing. As I recall, authoring of logins is done directly from AzureAd (new Entra). Documentation needs to be updated.

![audit2](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/104602080/4928476a-baa7-4db1-a39a-b83155c69557)
![audit](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/104602080/c0363c1b-9dfb-4e5d-bd68-eafadea22ab5)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Daiannec, I did some testing.

MailboxLogin is an acceptable value for AuditOwner only in E3 and E5, just like it's documented in the table, but I realize that might not mean anything.

So, it looks like I need to add a description to the effect of "available but doesn't work" the MailboxLogin description?

And is [this](https://learn.microsoft.com/azure/active-directory/reports-monitoring/concept-sign-ins) the Azure equivalent that we should direct people to instead?

Also, testing revealed an undocumented acceptable value UpdateComplianceTag that I'll add to the table.

**Comment by DMoenks** [comment]
From my point of view, the first screenshot simply shows that _MailboxLogin_ isn't enabled for the specified mailbox, which matches the documentation, as _MailboxLogin_ isn't part of the default audit events, probably for privacy reasons. In all honesty, I've never enabled and used that event for auditing, so I can't tell if it works or not, but as of now that screenshot solely confirms what can be found in the documentation

**Comment by yogkumgit** [comment]
@Daiannec Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
