### ISSUE TITLE
Missing detail on DMARC value

### ISSUE THREAD

**Issue by Steltek** [MicrosoftDocs/microsoft-365-docs#12272]
"Add your specific DMARC value." is not very descriptive. Where do I find that? How to I generate/build that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 521a61f4-edfa-5aff-598e-6a63480e4a6e
* Version Independent ID: 521a61f4-edfa-5aff-598e-6a63480e4a6e
* Content: [How to enable DMARC Reporting for Microsoft Online Email Routing Address (MOERA) and parked Domains](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/step-by-step-guides/how-to-enable-dmarc-reporting-for-microsoft-online-email-routing-address-moera-and-parked-domains?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/step-by-step-guides/how-to-enable-dmarc-reporting-for-microsoft-online-email-routing-address-moera-and-parked-domains.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/step-by-step-guides/how-to-enable-dmarc-reporting-for-microsoft-online-email-routing-address-moera-and-parked-domains.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Steltek Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12286

Once the author approves, the changes will be live.

Thanks
Sri
