### ISSUE TITLE
ICANN verification of contact information

### ISSUE THREAD

**Issue by samsonmobisa** [MicrosoftDocs/microsoft-365-docs#12274]
![8bf27c08-510c-4d49-b152-8d047d038f1f](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/92422271/dffae1e8-0481-4b8b-860b-c9b3ac94b599)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 840fd195-aec1-bb94-7d7e-12b80345701b
* Version Independent ID: 875f23b9-b3e4-c1a2-5f78-de963d6f0ce9
* Content: [ICANN verification of contact information - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/icann-verification-of-contact-information?redirectSourcePath=%252farticle%252f%2525200413dcce-26be-4b8c-b3fa-73ac1ac4fb35&view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/icann-verification-of-contact-information.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/icann-verification-of-contact-information.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by samsonmobisa** [comment]
The office 365 support link isn't working. The link doesn't seem to be active

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@samsonmobisa  This looks like a technical issue/bug, you will need to report it to the support team via the need help section on the admin center. So that a technical support engineer can fix this.

Hope this helps!

Thanks
Sri

**Comment by samsonmobisa** [comment]
Tried to use a link in a certain article but didn't seem to work. Can you
please share with me a link to support team

**Comment by msbemba** [comment]
@samsonmobisa  https://support.microsoft.com/en-us/topic/contact-microsoft-office-support-fd6bb40e-75b7-6f43-d6f9-c13d10850e77#:~:text=Sign%20in%20to%20Microsoft%20365,%2Dfree%2C%20US%20only). 

This is the link to contact support

Hope this helps!

Thanks
Sri
