### ISSUE TITLE
Message Center > Preferences > Major Updates

### ISSUE THREAD

**Issue by jd1984** [MicrosoftDocs/microsoft-365-docs#12278]
Hello, in regards to:

> Each admin can:
Set email preferences to receive a weekly digest of all messages, _**emails for major updates only**_, and emails for data privacy messages.

We have a long running support case open, where emails for major updates is turned on, but have only been receiving them intermittently. The issue is definitely on the sending side. Most new major updates do arrive fine, however some never turn up at all, and posts which are subsequently updated with new information, rarely appear to get sent back out.

For example: Basic Authentication Deprecation in Exchange Online, we were aware of the high level timeline, but did not receive the specific 7 day warning / deadline for our particular tenant. Only after logging into the portal when it suddenly stopped working, did we find this out, as we had been expecting to receive this via email.

After many months of back and forth with support, and numerous examples provided, we have now been advised:

> We have got an update from engineering team, they confirmed that they do not send individual emails when the post is updated. They also mentioned that not for every MC post update, will have email notification sent to you and its by design behavior. If you want to see or receive all post that been published over email, one way would be to subscribe to "Weekly Digest", so each week you will get a weekly digest email with all MC posts that been published in the past week. Moreover, if you subscribe to the Weekly Digest email, you will see it noted there.

I see the weekly update is turned on by default, however it is not clear that turning this off means potentially missing major updates.
This effectively means people have to keep the weekly digest turned on, or manually check the portal each day.
It does not appear possible to receive  **_emails for major updates only_** in the way it is currently documented.

Please can this be verified and made clearer?

Thank You
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29f3771a-247c-4f85-992a-e671285c70bd
* Version Independent ID: f3c2890a-2470-9349-ff77-924cf8566365
* Content: [Message center in the Microsoft 365 admin center - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/message-center?view=o365-worldwide#preferences)
* Content Source: [microsoft-365/admin/manage/message-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/message-center.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jd1984 Thank you for your feedback. I'm verifying/testing this internally and will provide an update shortly.

Thanks
Sri

**Comment by jd1984** [comment]
Thank you, please find a few recent examples attached
![example](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/43063718/6eb53fab-2458-433c-8fc1-68d1e1a184f1)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@jd1984 Thank you for your feedback. I can confirm with multiple tenants that I received all the MC updates(Major). This sounds like an issue with the Admin center as you should receive an email for all major updates(Email for major updates only) if you are subscribed for it. I'd recommend you contact the support team again and see if this can be escalated to the product group to fix the bug.

Hope this helps!

Thanks
Sri
