### ISSUE TITLE
The recommended config file for Intune has formatting issue

### ISSUE THREAD

**Issue by bubaji1** [MicrosoftDocs/microsoft-365-docs#12284]
On line 76, the close tag should be </string>, and not </key>. I got an error when trying to upload to Intune, and then plutil on mac pointed me in the right direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2dc758cd-0668-546f-5132-c3b5d2bf2b8e
* Version Independent ID: afa7ca04-3825-e73a-bd6e-4cf55010bd60
* Content: [Set preferences for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-preferences?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-preferences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-preferences.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@bubaji1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12303

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by bubaji1** [comment]
Perfect - thanks for the prompt action.
