### ISSUE TITLE
Update Steps

### ISSUE THREAD

**Issue by rf-bcit** [MicrosoftDocs/microsoft-365-docs#12289]
Wipe Data and Block are now Wipe company data and Block access

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2bdb60-b559-ddf3-0eec-be4943fc94fd
* Version Independent ID: 5b176c0f-6c35-a187-2ccb-53a23e154978
* Content: [Step 3 - Wipe and block a former employee's mobile device - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-3?view=o365-worldwide#wipe-mobile-device-using-the-exchange-admin-center)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-3.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@rf-bcit Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12304

Once the author approves, the changes will be live.

Thanks
Sri
