### ISSUE TITLE
DiagTrack is no longer used starting with RS5 or newer

### ISSUE THREAD

**Issue by cstanciumsft** [MicrosoftDocs/microsoft-365-docs#12282]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]
DiagTrack is no longer used by the MDE sensor starting with Windows RS5 or newer, as per the Product Engineering Team. Sense hosts its own mechanism to send CyberData and no longer relies on DiagTrack, starting with RS5.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76a978b2-de1e-d59d-016d-023cb2ff4851
* Version Independent ID: d2891133-a976-edbf-2aad-d6971182dbbf
* Content: [Fix unhealthy sensors in Microsoft Defender for Endpoint](https://review.learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/fix-unhealthy-sensors?view=o365-worldwide&branch=main)
* Content Source: [microsoft-365/security/defender-endpoint/fix-unhealthy-sensors.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/fix-unhealthy-sensors.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks
