### ISSUE TITLE
DiagTrack is no longer used starting with RS5 or newer

### ISSUE THREAD

**Issue by cstanciumsft** [MicrosoftDocs/microsoft-365-docs#12281]
DiagTrack is no longer used by the MDE sensor starting with Windows RS5 or newer, as per the Product Engineering Team. Sense hosts its own version of Telib to send CyberData and no longer relies on DiagTrack.
The document is confusing customers and they think DiagTrack is required for MDE.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7326a1bb-dad2-0770-5df2-fb79d960cce0
* Version Independent ID: 44412965-a543-3e52-bfea-acf535d49ce5
* Content: [Troubleshoot Microsoft Defender for Endpoint onboarding issues](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-onboarding?view=o365-worldwide#ensure-the-diagnostics-service-is-enabled)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-onboarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-onboarding.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks
