### ISSUE TITLE
Request to add Shifts data location

### ISSUE THREAD

**Issue by nicolasbroisin** [MicrosoftDocs/microsoft-365-docs#12283]
[Can Shifts be added to this page please ? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@nicolasbroisin Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12302

Once the author approves, the changes will be live.

Thanks
Sri
