### ISSUE TITLE
Additional MDE pre req data required

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#12292]
It would be better if you could list the Pre reqs in Defender for Endpoint required for this capability in this article too.

For example I believe Network Protection has to be enabled in block mode in MDE for device isolation to work and I am sure there are other features that need to be enabled in order for all of this capability to function.

These need to be listed more explicitly in this document to avoid customer believing they are protected when they are not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8c235b3-4549-fd60-718b-f73bb3ae4c5e
* Version Independent ID: b8c235b3-4549-fd60-718b-f73bb3ae4c5e
* Content: [Configure automatic attack disruption capabilities in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/configure-attack-disruption?view=o365-worldwide#prerequisites-for-automatic-attack-disruption-in-microsoft-365-defender)
* Content Source: [microsoft-365/security/defender/configure-attack-disruption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/configure-attack-disruption.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @diannegali
* Microsoft Alias: **diannegali**

**Comment by diannegali** [comment]
@pjrcdf thanks for pointing this out. However, there are no prerequisites required for this capability other than what is stated in the configuration page per the designers. We will update the document should this change in the future.
