### ISSUE TITLE
GLobal Admin & access

### ISSUE THREAD

**Issue by BruHop1** [MicrosoftDocs/microsoft-365-docs#12297]
Kia ora,
I am the founder & owner of my company. I get messages telling me I need the global administrator to do certain things in my Office 365 account. I use it for my business & one of my 2 desktop computers now requires me to sign in every time I want to use word or excel etc. I have used that desktop comp for several years without problems. I get asked which account I want to sign in with & I cannot figure out how to rationalise the set up so I only have one account. 
I think I have an existing old free account that was not for my business.
I would liove to have someone guide me through how to make sure my account is uncluttered & I can operate efficiently from either of my desktops & my laptop. I run iMacs & an apple laptop.
ngā mihi
Bruce Hopkins
ActionActors Ltd

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a57c0a2-0a6c-4499-f31e-18016d006549
* Version Independent ID: 5587ca01-e40f-478d-1796-b7b4dc41cbf0
* Content: [Microsoft Secure Score](https://learn.microsoft.com/en-gb/microsoft-365/security/defender/microsoft-secure-score?view=o365-worldwide#required-permissions)
* Content Source: [microsoft-365/security/defender/microsoft-secure-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-secure-score.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@BruHop1 Thank you for your feedback. Looks like you need technical assistance and I'd suggest you to contact support via the need help section on the admin center, so that our support engineer can assist you.

Hope this helps!

Thanks
Sri
