### ISSUE TITLE
What setting if device group policies is empty/left default?

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#12291]
Can you please add the information that if you don't create any device groups and specify the Automation level, what is default for all endpoints?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8c235b3-4549-fd60-718b-f73bb3ae4c5e
* Version Independent ID: b8c235b3-4549-fd60-718b-f73bb3ae4c5e
* Content: [Configure automatic attack disruption capabilities in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/configure-attack-disruption?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/configure-attack-disruption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/configure-attack-disruption.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @diannegali
* Microsoft Alias: **diannegali**

**Comment by diannegali** [comment]
@JonesMikael the default setting is "Full - remediate threats automatically". Thanks for this question. We will add this bit in the documentation.
