### ISSUE TITLE
"AuditData" Column not present after export

### ISSUE THREAD

**Issue by AMureika** [MicrosoftDocs/microsoft-365-docs#1229]
I believe the download log function has changed as the 'AuditData" column is not present after I export a user for review.

I did note that you can switch between CSV and JSON formats on the download screen now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 932eaab9-9438-a378-1ac1-e59477ed1f51
* Version Independent ID: 8a0ce802-0320-16bf-bea9-1c166940d4c9
* Content: [Export, configure, and view audit log records - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-view-audit-log-records#feedback)
* Content Source: [microsoft-365/compliance/export-view-audit-log-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-view-audit-log-records.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@AMureika Thanks for pointing this out. However, I can't repro this in a production tenant. Can you please send screenshots or the keystrokes to reproduce this?

**Comment by AMureika** [comment]
@markjjo -  I'm not sure what changed, but I tried the same steps today and the AuditData column is now there when I try to do the transform.  I'm chalking it up to a "blip in time"  ;-)
I think we can close this off.

**Comment by markjjo** [comment]
@AMureika Thanks for following up. Glad AuditData column is displayed.
