### ISSUE TITLE
Blah Blah Blah - Where's the meat?

### ISSUE THREAD

**Issue by glassm** [MicrosoftDocs/microsoft-365-docs#12294]
I still don't know, after reading this page (Configure and validate exclusions for Microsoft Defender Antivirus scans) how to configure exclusions. Please start with How to use the app to make it happen rather than a general discussion about the subject and related theories -- thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d5d462d-4c3a-f363-f1d7-611e3c71fbb4
* Version Independent ID: e496259f-7012-e898-12c3-88115d55d5e0
* Content: [Set up exclusions for Microsoft Defender Antivirus scans](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-exclusions-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @glassm. Thank you very much for your feedback. I have been working on the documentation for Microsoft Defender Antivirus exclusions and did update this article today. The updates should be live at around 4 p.m. Pacific Time. Thanks again for posting your feedback here. 

https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/21509
