### ISSUE TITLE
Remove Expired Certificate information

### ISSUE THREAD

**Issue by mshahane** [MicrosoftDocs/microsoft-365-docs#12298]
https://learn.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-certificate-chains?view=o365-worldwide

On this Page there are expired certificates information. Could you remove those and add new/changed certificates information?

E.g.,
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/83323280/6bf869c8-b3b6-4012-bf28-f17ffb704831)

**Comment by yogkumgit** [comment]
@mshahane Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
