### ISSUE TITLE
Request for Information Responses - Detail Tenant Info Request - Who I can contact?

### ISSUE THREAD

**Issue by mpellizzon** [MicrosoftDocs/microsoft-365-docs#12293]
Hello,

I have to provide a report stating the physical access to my tenant´s datacenter in the last 90 days.

I read the Standard Response to Requests for Information for Microsoft Professional Services, specifically item 2.4 Physical and Operational Security, but there is no instruction to contact someone to provide a report that could show that except for the Microsoft and 3rd party personnel which had phisical access to my tenant´s resources, no other person had access to them.

Is there someone I could contact?

Thanks

Mirella

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6a6cff6-f960-bab8-10b0-731d1e78e8ec
* Version Independent ID: a60eb908-022a-4d90-23a4-b4e765f232e9
* Content: [Get started with the Microsoft Service Trust Portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/get-started-with-service-trust-portal?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/get-started-with-service-trust-portal.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-with-service-trust-portal.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by yogkumgit** [comment]
@mpellizzon Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
