### ISSUE TITLE
 API for User Reported Messages

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/microsoft-365-docs#12299]
We need an API for User Reported Messages, could you please suggest.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53a61a50-f7f2-f09a-a008-759c3afba97b
* Version Independent ID: 872c0e23-c626-3e22-efea-d4ef4ad7f32b
* Content: [Advanced Hunting API](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-api?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-advanced-query-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-advanced-query-api.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@ghost Thank you for your feedback. Looks like you have a technical question and I'd recommend contacting support via the need help section on the admin center, so that our support engineer can help you out.

Hope this helps!

Thanks
Sri
