### ISSUE TITLE
Phone Number Format on Bookings Self-Service Page

### ISSUE THREAD

**Issue by mshiccups** [MicrosoftDocs/microsoft-365-docs#12307]
The graphic in the MS documentation shows that a phone number can be set to a standard format depending on the country of origin on the MS Bookings self-service page. We have not experienced this on our end. The field is required on our page but does not require any type of country code or area code, etc. There is not dropdown to select a country. How do we adjust this?

Here is the link: https://learn.microsoft.com/en-us/microsoft-365/bookings/customize-booking-page?view=o365-worldwide

**Comment by msbemba** [comment]
@mshiccups Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12332

Once the author approves, the changes will be live.

Thanks
Sri
