### ISSUE TITLE
Why not in Security Center

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1230]
Why is this new functionality getting added to the old SCC center at protection.microsoft.com instead of new center at security.microsoft.com. According to https://docs.microsoft.com/en-us/microsoft-365/security/mtp/overview-security-center the new site is supposed to be the home for this functionality

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DeanGross, new may be a relative term, as in when this feature was originally conceived vs. when it was actually implemented. Naturally, it makes sense for all things in the Security & Compliance Center to eventually migrate to the Security Center and the Compliance Center.

Thanks for the feedback.
