### ISSUE TITLE
View or edit role assignments: incorrect procedure

### ISSUE THREAD

**Issue by starbuck3000** [MicrosoftDocs/microsoft-365-docs#12301]
Hello, 

The proposed procedure contains some errors:
1. Go to the Microsoft 365 Defender portal (https://security.microsoft.com/) and sign in.
--> OK
2. In the navigation pane, choose Permissions & roles, and then under Azure AD, select Roles.
--> NOK: menu entry not shown. If "Permissions" is selected, then all further instructions are a mismatch, too.

Wouldn't the central administration console path be more accurate (i.e., https://admin.microsoft.com/, then "Roles", then "Role assignments", then select role, then assign through the side tab)? 

Kind regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4edd8a-e4ce-8916-7f8f-533fe5bf5d8a
* Version Independent ID: 5c4edd8a-e4ce-8916-7f8f-533fe5bf5d8a
* Content: [Assign security roles and permissions in Microsoft Defender for Business](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-roles-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-roles-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-roles-permissions.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @starbuck3000 and thank you so much for the feedback. I will look into this!

**Comment by denisebmsft** [comment]
Content updated! Please let me know if you have any other questions. Thank you again for your helpful feedback!
