### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by kaileyb** [MicrosoftDocs/microsoft-365-docs#1231]
Link 'conformance reports' to https://cloudblogs.microsoft.com/industry-blog/industry/government/accessibility-conformance-reports/ produces "Not Found" error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784b1052-9ed9-3adb-7d38-3241529c8ec2
* Version Independent ID: 6e6effbb-bb80-4bae-8644-b5bf44101c0c
* Content: [U.S. Section 508 - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-section-508-vpats#microsoft-accessibility-conformance-reports)
* Content Source: [microsoft-365/compliance/offering-Section-508-VPATS.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-Section-508-VPATS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@kaileyb - thanks for the feedback, I'm updating the topic with the correct link (https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/) now.
