### ISSUE TITLE
Attack Simulation Training - Bug

### ISSUE THREAD

**Issue by jasons1987** [MicrosoftDocs/microsoft-365-docs#12314]
User A receives an attack sim training email with a malicious link
User A **does not** click the link 
User A forwards the email to User B
User B opens the email and clicks the malicious link
User B gets web page saying "oops that was a risk click User A" 

Back in the reporting, User A is reported as clicking being compromised
No record of User B clicking the link.

**Comment by denisebmsft** [comment]
Hello @jasons1987. Thank you for the feedback. Can you please tell us to which article this applies? This information will help us route the issue to the correct writer or team. Thank you!

**Comment by jasons1987** [comment]
https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide

**Comment by chrisda** [comment]
@jasons1987, you should open a support ticket about this. It sounds like expected behavior, but they can tell you for sure, and we likely need to update our documentation.

Honestly, I never thought about what happens when someone who is outside the simulation clicks on a link from the simulation.
