### ISSUE TITLE
Feedback policy Note is Wrong

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/microsoft-365-docs#12317]
Feedback policy will change from off to on on July 21, 2023. Regarding the note describing this, the ja-jp page states that it will be turned off.
Wrong translation.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/41832013/690a3125-3e68-42f5-9018-474495ee33ba)

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/41832013/457121f7-104f-4b75-b087-eef715e1cb11)
NG: 2023 年 7 月 21 日からオフに変わります。
OK: 2023 年 7 月 21 日以降、オフからオンに変わります。
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8d2ba49-5e22-3373-5034-bb2fde743762
* Version Independent ID: 3a02dcf2-1310-561d-4106-d495eaec63b7
* Content: [Manage Microsoft feedback for your organization - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-feedback-ms-org?WT.mc_id=M365-MVP-5002496&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-feedback-ms-org.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-feedback-ms-org.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@tiburd Please help.

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [#337993](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/337993)

I'm closing this issue because the Global Services team will handle it from here.
