### ISSUE TITLE
TermStore expansion - skos:collection equivalent

### ISSUE THREAD

**Issue by KellyVance** [MicrosoftDocs/microsoft-365-docs#12312]
TermStore would benefit from an additional native function (rather than custom field) to serve an equivalent purpose to skos:collections such as a sharepoint-taxonomy:TermUse

i.e. A subset of terms within a TermSet specific to a particular use case or logical grouping that is not part of the logical taxonomic structure of the TermSet and where terms could exist in multiple use cases. Where the individual terms selected are included independent of their parent or child terms. And subsequently able to select collections as picklist options or export/query those collections.

e.g. 
**TermSet:** _Units of Measure_
Metres
Feet
Grams 
Pounds
Seconds
Minutes

**TermUse:** _Units of Measure\Mass_
Grams

**TermUse:** _Units of Measure\Distance_
Feet
Metres

**TermUse:** _Units of Measure\Time_
Seconds
Minutes

Also an equivalent to skos:notation e.g. sharepoint-taxonomy:notation.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 063dc29a-8947-e966-fb3c-ead51eea1244
* Version Independent ID: 063dc29a-8947-e966-fb3c-ead51eea1244
* Content: [SKOS format reference for SharePoint taxonomy - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/skos-format-reference)
* Content Source: [microsoft-365/syntex/skos-format-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/skos-format-reference.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by msbemba** [comment]
@KellyVance Thank you for your feedback. This will need to route to our Product team and I'd recommend you post this in our [SharePoint · Community (microsoft.com)](https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472) so that our Product engineers can look into it and respond.

Hope this helps!

Thanks
Sri
