### ISSUE TITLE
Microsoft 365 Multi-Geo

### ISSUE THREAD

**Issue by pinguin0422** [MicrosoftDocs/microsoft-365-docs#12328]
Hello,

What does “eDiscovery data location coming soon” mean? Is the datacenter still in planning and how will I know when it is introduced?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32b41c7e-29cd-eb5b-36b2-738b3babd08f
* Version Independent ID: 22eda3f7-1c04-b3b0-95fd-3474b3f991b2
* Content: [Microsoft 365 Multi-Geo - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-multi-geo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-multi-geo.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@pinguin0422 Thank you for your feedback. Yes, the data center is in planning status and we will update the document and update customers via the message center once it is available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @pinguin0422 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
