### ISSUE TITLE
what if you don't have ms 365?

### ISSUE THREAD

**Issue by mhead110** [MicrosoftDocs/microsoft-365-docs#12320]
I want to forward a suspicious email--  no way to do that unless I subscribe to stuff I don't want?   MS trying to sell something every 4 minutes.   The tech I talked to couldn't even tell me whether it was from MS or not!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc4f577-32e6-7164-6b97-ac4aede3a9af
* Version Independent ID: 6dc4f577-32e6-7164-6b97-ac4aede3a9af
* Content: [Report spam, non-spam, phishing, suspicious emails and files to Microsoft](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-report-messages-files-to-microsoft.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
@mhead110, if you don't have Microsoft 365, do you have Outlook.com?

I'm curious why/how you landed in Microsoft 365 documentation.

**Comment by yogkumgit** [comment]
@mhead110 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
