### ISSUE TITLE
Activation Time?

### ISSUE THREAD

**Issue by fhvasco** [MicrosoftDocs/microsoft-365-docs#1232]
Scenario: Office 365 retention policy exist for all Exchange Online mailboxes to keep data for X number of years.  How long before the Office 365 retention policy is applied to a new mailbox?

For example, If an unlicensed shared mailbox exists but was recently assigned an Exchange Online Plan 2 license, how long before the contents are under the control of the retention policy?

**Comment by mypil** [comment]
Closing this issue as it is a Duplicate to #1233
