### ISSUE TITLE
Instructions of Syntex and Power automate are not clear

### ISSUE THREAD

**Issue by bekem07** [MicrosoftDocs/microsoft-365-docs#12327]
I am baffled at step 2 of the processing power automate. At the update item, it told could not find the item, and I have also not found the "Contracts" list in the previous (in Step 2 in the article), I think it's Contracts Library not List. By the way, I changed the Update item to Create Item, it try only for me.

There is so much confusion in the entire article. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3c6e304-7dcb-c299-fd85-2f8f3248864e
* Version Independent ID: b3c6e304-7dcb-c299-fd85-2f8f3248864e
* Content: [Step 3. Use Power Automate to create the flow to process your contracts - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/solution-manage-contracts-step3)
* Content Source: [microsoft-365/syntex/solution-manage-contracts-step3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/solution-manage-contracts-step3.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**
```[tasklist]
### Tasks
```

**Comment by yogkumgit** [comment]
@chuckedmonson Please help us in resolving this issue. Thanks

**Comment by chuckedmonson** [comment]
@bekem07 -- Thank you for your feedback. We're sorry about your experience.
From the information you provided, we're not able to identify your specific issues. Would it be possible to provide more precise information about the specific issue you're having with the article? Again, thank you for your help.
