### ISSUE TITLE
Removal of IP address in row 24

### ISSUE THREAD

**Issue by PaulCollinge** [MicrosoftDocs/microsoft-365-docs#12326]
Please remove IP address from row 24 as it's no longer valid. The row should just show the FQDN  www.msftconnecttest.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Other endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by PaulCollinge** [comment]
Hi @msbemba , the page in question is manually maintained and is not linked to the M365 endpoints web service.

**Comment by msbemba** [comment]
@kelleyvice-msft  Could you please confirm if this can be edited? As I don't see an option to make changes.

Thanks
Sri

**Comment by yogkumgit** [comment]
@PaulCollinge kindly coordinate with @kelleyvice-msft . Thanks
