### ISSUE TITLE
Service and URL's section contains only port 443 to be excluded however for go.microsoft.com and *.download.windowsupdate.com port 80 is required. is it possible to edit the document and make the necessary change?

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#12322]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1575e3-b233-ffd2-95c1-fd34fd242651
* Version Independent ID: 02b44885-5bff-1580-0974-f9050bee639c
* Content: [Configure and validate Microsoft Defender Antivirus network connections](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus?view=o365-worldwide#services-and-urls)
* Content Source: [microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @PremMS-MDE I will get the article updated.

**Comment by denisebmsft** [comment]
https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/21167

**Comment by denisebmsft** [comment]
Article updated! And live!
