### ISSUE TITLE
Options for Microsoft reporting tools - Bug or inconsistency

### ISSUE THREAD

**Issue by BiggsSkeedR** [MicrosoftDocs/microsoft-365-docs#12336]
Not sure if this is a bug or documentation inconsistency, but the section [Options for Microsoft reporting tools](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox?view=o365-worldwide#options-for-microsoft-reporting-tools) states that when the setting **Send the reported messages to** is set to **My reporting mailbox only** the messages should still appear in the Submissions page. However, having tried this, I have confirmed that they do not.

When set to **Microsoft and my reporting mailbox** the reported messages show up in the Submissions page.

Trying to raise this via support ticket TrackingID#2306230050001109

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User reported settings](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BiggsSkeedR, it's good that you opened a support ticket, because this sounds like a bug.

If users report messages using the Report button in Outlook on the web and/or the Report Message or Report Phishing add-ins in virtually all Outlook platforms, user reported messages should appear on the **User reported** tab on the **Submissions** page (Microsoft only, reporting mailbox only, or both).
