### ISSUE TITLE
Instructions for setting up Web Content Filters is out of date.

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/microsoft-365-docs#12337]
On step 1 for setting up a web filter.  After going to security.microsoft.com, I have to go to settings, endpoints, and then Web content filtering under Rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3afb40ff-f167-1d49-443f-a971611a6340
* Version Independent ID: 3afb40ff-f167-1d49-443f-a971611a6340
* Content: [Set up web content filtering in Microsoft Defender for Business](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-web-content-filtering?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-web-content-filtering.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hi @rconiv. Good catch! Thank you for letting me know about this. I've updated the article and the changes will be live later today.   Appreciate your feedback!
