### ISSUE TITLE
Activation Time?

### ISSUE THREAD

**Issue by fhvasco** [MicrosoftDocs/microsoft-365-docs#1233]
Scenario: Office 365 retention policy exist for all Exchange Online mailboxes to keep data for X number of years. How long before the Office 365 retention policy is applied to a new mailbox?

For example, If an unlicensed shared mailbox exists but was recently assigned an Exchange Online Plan 2 license, how long before the contents are under the control of the retention policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by chvukosw** [comment]
Hello, can you please elaborate on your question or clarify? Does your question have more to do with the license of the mailbox at issue? Thank you.

**Comment by msbemba** [comment]
@fhvasco Thank you for feedback. The retention policy is applied as soon as the mailbox is assigned that policy, In case of a new mailbox, it takes immediate effect.  The retention policy can be assigned even for shared mailboxes,  If the mailbox already exists and you change the retention policy then you can use a PS cmd mentioned in the document. (https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/start-managedfolderassistant?view=exchange-ps).

I don't believe there are any changes required in this document. Thank you for your time in providing feedback.

Thanks
Sri

**Comment by mypil** [comment]
@fhvasco - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
