### ISSUE TITLE
Missing information regarding interval for updating the activity log

### ISSUE THREAD

**Issue by a-goo** [MicrosoftDocs/microsoft-365-docs#12347]
There is no information provided regarding how often the activity log is updated. 
It clearly isn't instantly, since during testing we have waited up to 30 minutes and still cannot see a tagged document in the Activity Explorer. Refresh does not appear to activate any crawl to find new data. 

How often is the data in the Activity Explorer updated? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3d3633-893d-9354-9402-c47ed7dec790
* Version Independent ID: fc12340b-403f-b531-04be-91f00a8f0af6
* Content: [Get started with Activity explorer - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-activity-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-activity-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by a-goo** [comment]
It also seems that newly created sites in SharePoint have an additional delay before data is registered in the Activity Explorer. 
How long is this delay? Why is there even a delay?

**Comment by yogkumgit** [comment]
@a-goo Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
