### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#12341]
Add details on priority order. It isn't written clearly as to if 0 is the highest priority or if the largest number is the highest priority. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77dd99ae-2687-1e3f-341e-04a8e3d4acc2
* Version Independent ID: 1948ad4b-3bc1-4f49-fded-9582a854cbbd
* Content: [Data Loss Prevention policy reference - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-reference?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-policy-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-policy-reference.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@danmyhre Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
