### ISSUE TITLE
Is this project still valid?

### ISSUE THREAD

**Issue by SukrittaH** [MicrosoftDocs/microsoft-365-docs#12353]
[Enter feedback here]
I can't run this project completely. found this error when launch the app locally {"ClassName":"System.ArgumentException","Message":"Key DKETestKey not found","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.InformationProtection.Web.Models.TestKeyStore.GetActiveKey(String keyName) in C:\\Users\\SukrittaHanucharoenk\\Documents\\DoubleKeyEncryptionService\\src\\customer-key-store\\Models\\TestStore.cs:line 115\r\n   at Microsoft.InformationProtection.Web.Models.KeyManager.GetPublicKey(Uri requestUri, String keyName) in C:\\Users\\SukrittaHanucharoenk\\Documents\\DoubleKeyEncryptionService\\src\\customer-key-store\\Models\\KeyManager.cs:line 24\r\n   at Microsoft.InformationProtection.Web.Controllers.KeysController.GetKey(String keyName) in C:\\Users\\SukrittaHanucharoenk\\Documents\\DoubleKeyEncryptionService\\src\\customer-key-store\\Controllers\\KeysController.cs:line 26","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147024809,"Source":"customerkeystore","WatsonBuckets":null,"ParamName":null}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide#system-and-licensing-requirements-for-dke)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@SukrittaH Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
