### ISSUE TITLE
XML Error

### ISSUE THREAD

**Issue by zach-wilson** [MicrosoftDocs/microsoft-365-docs#12358]
I'm no expert, but I believe there is an error in the XML on this page. I had to change it in order to get Jamf to accept it without an error.

I believe the following line (which is repeated multiple times) is the issue:

<string>block</key>

It should be: 

<string>block</string>

Cheers,
Zach

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2dc758cd-0668-546f-5132-c3b5d2bf2b8e
* Version Independent ID: afa7ca04-3825-e73a-bd6e-4cf55010bd60
* Content: [Set preferences for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-preferences?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-preferences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-preferences.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@zach-wilson Thank you for your feedback. Could you please elaborate on which line the word block has been repeated multiple times?

Thanks
Sri

**Comment by yogkumgit** [comment]
@zach-wilson Please reply to the query. Thanks.

**Comment by yogkumgit** [comment]
@zach-wilson We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
