### ISSUE TITLE
Joker34international

### ISSUE THREAD

**Issue by wonghongyang** [MicrosoftDocs/microsoft-365-docs#12359]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d29992b-3923-dee5-80ce-d2f6d742a22d
* Version Independent ID: 69b84bff-490f-7e75-51fd-b1f0e77dc247
* Content: [Assign admin roles the Microsoft 365 admin center - Microsoft 365 admin](https://learn.microsoft.com/en-MY/microsoft-365/admin/add-users/assign-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/assign-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/assign-admin-roles.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@wonghongyang Thank you for your feedback. I dont see any description of your feedback here, You can reply back here with more information.

Thanks
Sri
