### ISSUE TITLE
about setting value "Scan packed executables" 

### ISSUE THREAD

**Issue by hnakamoto** [MicrosoftDocs/microsoft-365-docs#12354]
[Enter feedback here]
"Scan packed executables" has been removed from the following Windows 11 templates

Administrative Templates (.admx) for Windows 11 2022 Update (22H2)
Administrative Templates (.admx) for Windows 11 October 2021 Update (21H2)

Could you please remove it from this site as well or add a comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 292d5bf4-ff14-4cbe-eab1-3fe35cb5c1c9
* Version Independent ID: 782db2b2-0a15-941c-24ff-345ecfe694f3
* Content: [Configure scanning options for Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-advanced-scan-types-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-advanced-scan-types-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-advanced-scan-types-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@hnakamoto Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12387

Once the author approves, the changes will be live.

Thanks
Sri
