### ISSUE TITLE
Missing reference for roadmap Feature ID

### ISSUE THREAD

**Issue by a-goo** [MicrosoftDocs/microsoft-365-docs#12355]
"**Now rolling out in preview:** For SharePoint, users can also see and apply sensitivity labels from the details pane. This method is also available from the Files tab in Teams."

Please specify the Feature ID in the roadmap. Searching there for "sensitivity labels sharepoint" yields no relevant results.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
The technical documentation doesn't link to roadmap entries and in this case, there isn't one because I'm told it wasn't considered a big enough change
