### ISSUE TITLE
Microsoft defender smartScreen blocking a simulation website

### ISSUE THREAD

**Issue by preeeeemo** [MicrosoftDocs/microsoft-365-docs#12362]
Hello!

The sub-domain for https://www.bankmenia.org/ is getting blocked by the Edge Browser (Microsoft Defender SmartScreen).

For instance, the following gets blocked on Edge:

https://www.bankmenia.org/*
https://www.bankmenia.org/abcdefg

Disabling "Microsoft Defender SmartScreen" on the browser settings fixes this, but we do not want to do that for our entire fleet. The rest of the 129 websites (at the time of writing) work fine, including any sub-domains. 

Thanks,

Preeeeemo

**Comment by msbemba** [comment]
@preeeeemo Thank you for your feedback. This looks like a technical issue or a bug, I recommend you contact support via the need help section on the admin center so that our support engineer can assist.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @preeeeemo Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by preeeeemo** [comment]
Thanks Gents, I have opened a ticket and will update you accordingly.
