### ISSUE TITLE
Instructions for Changing End Date of Campaign

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#12368]
Please provide instructions for changing the Training Completion date for a campaign, this does not seem possible, but I may be missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e368fd8c-e40c-7999-a151-36bbb13ba52d
* Version Independent ID: e368fd8c-e40c-7999-a151-36bbb13ba52d
* Content: [Training campaigns in Attack simulation training](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by yogkumgit** [comment]
@DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
