### ISSUE TITLE
Missing information around Smart Alerts

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/microsoft-365-docs#12363]
Hi,

Since the deployment of Smart alerts, a number of smart  alerts have appeared however there is no documentation around them or how they are generated. Or how to disable them. Just wondering if this article could be updated to include information about smart alerts.

Regards
John

Roadmap announcement below
https://www.microsoft.com/en-au/microsoft-365/roadmap?filters=&searchterms=117491

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c22bc78f-4f09-7bd5-4ee1-7cbbd4f42335
* Version Independent ID: c22bc78f-4f09-7bd5-4ee1-7cbbd4f42335
* Content: [Microsoft Purview Compliance Manager alerts and alert policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-alert-policies?view=o365-worldwide#viewing-and-managing-alerts)
* Content Source: [microsoft-365/compliance/compliance-manager-alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by yogkumgit** [comment]
@Jlouden9 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
