### ISSUE TITLE
Incorrect statement in the "Office 365 Video transition to Microsoft Stream details" document

### ISSUE THREAD

**Issue by Jvasil** [MicrosoftDocs/microsoft-365-docs#1236]
There is a NOTE in the Embedding Experience section for the "Office 365 Video transition to Microsoft Stream details" document that needs to be updated. The document and Embed section is here 
https://docs.microsoft.com/en-us/stream/migration-experience#embedding-experience

The last note in the Embedded Experience section current states 
"NOTE: There is no action required from you to update the emded codes, redirection is automatic after going live. Also, there are no plans to stop this redirection any time in the future."

The last sentence in that note is not longer accurate and needs to be updated to reflex recent announcements documented here 
https://docs.microsoft.com/en-us/stream/migrate-from-office-365
that states on " March 1, 2022 - Redirection for links and embed codes from Office 365 Video to Stream will no longer be maintained"

So that last sentence needs to updated to state 
"After March 1, 2022, redirection for links and embed codes from Office 365 Video to Stream will no longer be maintained"

**Comment by mypil** [comment]
@Jvasil - Thank you for submitting feedback.

This repository is intended for feedback on docs specific to Microsoft 365 topics and the issue you opened is for MS Stream. However, I went ahead and reached out to some of my contacts to get ahold of the author of that doc. The author has fixed the issue on the Stream help docs. 

Thank you for your contribution to make the docs better!
