### ISSUE TITLE
Can we add A5 license under prerequisites, since A5 is included as a part of P2 license?

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#12364]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fbaaa90e-6975-ee29-335a-545cb6a55986
* Version Independent ID: 75c93c17-4952-a13f-ed60-d2baefd0337e
* Content: [Web content filtering](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-content-filtering?view=o365-worldwide#prerequisites)
* Content Source: [microsoft-365/security/defender-endpoint/web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-content-filtering.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@PremMS-MDE Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12386

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by PremMS-MDE** [comment]
Thank you @msbemba
