### ISSUE TITLE
Why not distinguish between Forwarding and Relay??

### ISSUE THREAD

**Issue by GlosJohn** [MicrosoftDocs/microsoft-365-docs#12370]
Why on earth would you put Forwarding and Relay in the same pool??

This is causing a lot of issues for a lot of companies.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2dee626-2897-aa19-46c9-8cbafa54035d
* Version Independent ID: e69c5a66-6591-d1b8-9fcc-ad303b86b415
* Content: [Outbound delivery pools](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/outbound-spam-high-risk-delivery-pool-about?view=o365-worldwide#relay-pool)
* Content Source: [microsoft-365/security/office-365-security/outbound-spam-high-risk-delivery-pool-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/outbound-spam-high-risk-delivery-pool-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
@GlosJohn, your only way forward for a question like that is to open a support ticket.
