### ISSUE TITLE
Would you add "Office 365 E3 subscription + the Microsoft 365 E5/A5/F5/G5 Insider Risk Management add-on" in "Subscriptions and licensing" section?

### ISSUE THREAD

**Issue by kuroyuko** [MicrosoftDocs/microsoft-365-docs#12375]
Would you add "Office 365 E3 subscription + the Microsoft 365 E5/A5/F5/G5 Insider Risk Management add-on" in "Subscriptions and licensing" section?

・"Subscriptions and licensing" section
--
To access and use insider risk management, your organization must have one of the following subscriptions or add-ons:

Microsoft 365 E5/A5/F5/G5 subscription (paid or trial version)
Microsoft 365 E3/A3/F3/G3 subscription + the Microsoft 365 E5/A5/F5/G5 Compliance add-on
Microsoft 365 E3/A3/F3/G3 subscription + the Microsoft 365 E5/A5/F5/G5 Insider Risk Management add-on
Office 365 E3 subscription + Enterprise Mobility and Security E3 + the Microsoft 365 E5 Compliance add-on
--

I check the below table and Docs, "Office 365 E3 subscription + the Microsoft 365 E5/A5/F5/G5 Insider Risk Management add-on" seems to meet the license condition to access and use insider risk management.

https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-22
---
Which licenses provide the rights for a user to benefit from the service?
Microsoft 365 E5/A5/G5, Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance, and Microsoft 365 E5/A5/F5/G5 Insider Risk Management provide the rights for a user to benefit from Insider Risk Management.
---

https://go.microsoft.com/fwlink/?linkid=2139145

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/65701242/fbd0a762-a996-48f6-a055-c6f4436668af)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb98e0ff-d34c-75bc-0ade-7dc70fc7f4bd
* Version Independent ID: 5172471f-e514-bcde-16e0-d8d8090a892a
* Content: [Get started with insider risk management - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-configure?view=o365-worldwide#subscriptions-and-licensing)
* Content Source: [microsoft-365/compliance/insider-risk-management-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-configure.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@kuroyuko Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
