### ISSUE TITLE
Missing reference to Microsoft 365 Defender

### ISSUE THREAD

**Issue by Amjad202020** [MicrosoftDocs/microsoft-365-docs#12377]
Hi,

As this is part of the Microsoft 365 Defender console, it would be useful to state that in the article, mentioning that it is one of the components within the main MS 365 Defender portal.

Cheers
Amjad

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07d225fa-722b-4608-a695-b935d4b820e1
* Version Independent ID: 07d225fa-722b-4608-a695-b935d4b820e1
* Content: [Microsoft Defender Vulnerability Management](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@Amjad202020 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12427

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per author's comment. Thanks
