### ISSUE TITLE
changes to alert location.

### ISSUE THREAD

**Issue by thomasjsweet** [MicrosoftDocs/microsoft-365-docs#12374]
[Enter feedback here]

I think these steps are no longer current based on changes to the UI or I am just misunderstanding.

existing....
1. Go to [compliance portal](https://go.microsoft.com/fwlink/p/?linkid=2077149).
3. Sign in using your work or school account.
5. On the Activity alerts page, click Add icon. New.

Consider
1. Go to [compliance portal](https://go.microsoft.com/fwlink/p/?linkid=2077149).
3. Sign in using your work or school account.
5. Go to Policies in the left navigation
6. Click on Alert Policies located under the alert menu
7. On the Alert policies page, click Add Alert Policy. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84e63e43-1556-04aa-7771-59e47a4931b0
* Version Independent ID: cf9673ed-2dee-eb23-826d-3a5ba2c9d89a
* Content: [Create activity alerts - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/create-activity-alerts?view=o365-worldwide#more-information)
* Content Source: [microsoft-365/compliance/create-activity-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-activity-alerts.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@thomasjsweet Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
