### ISSUE TITLE
Type of Groups that are eligible

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#12372]
Please specify what type of Groups can be assigned to a training campaign, I am not seeing Security Groups, so it appears that only M365 Groups are eligible. It would be helpful to explicitly state this . 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e368fd8c-e40c-7999-a151-36bbb13ba52d
* Version Independent ID: e368fd8c-e40c-7999-a151-36bbb13ba52d
* Content: [Training campaigns in Attack simulation training](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-training-campaigns.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12384

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chrisda** [comment]
OK Fixed.
