### ISSUE TITLE
Article doesn't explain the most important topic - How to manually reattempt delivery

### ISSUE THREAD

**Issue by ronnessim** [MicrosoftDocs/microsoft-365-docs#12373]
When trying to fix a problem, users need a way to force attempt redelivery to see if the problem is fixed or not. The article doesn't touch on this topic at all. It should state whether or not it's possible and if it's possible how to do it. Right now it just says "the messages will be randomly requeued at whatever time Microsoft thinks is good". We'd like something more definitive in terms of whether or not we can choose a test message (without creating a new one for certain scenarios) and manually force delivery to be attempted again.

**Comment by denisebmsft** [comment]
Hello @ronnessim. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by ronnessim** [comment]
This refers to:

https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/mail-flow-delivery-faq?view=o365-worldwide

I assumed that because I was taken to the github page from the feedback link that the article in question was implied in the issue – if not they should fix that (most other feedback hubs work this way).

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
@ronnessim, it's not possible to manually force redelivery of queued messages. If you would like a definitive answer, you should open a support ticket and ask.
