### ISSUE TITLE
What is the required Office 365 ProPlus version on client side for this feature?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/microsoft-365-docs#1239]
Would help a lot in testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by kshi-docs** [comment]
Office 365 ProPlus Version 2002 (12527.20092)

**Comment by chrisda** [comment]
Done per PR #1260.

Closing.

Thanks for the feedback.
