### ISSUE TITLE
[Scenario 2: Allow specific approved USB printers using Intune] Example is incorrect.

### ISSUE THREAD

**Issue by komatsuyuta1** [MicrosoftDocs/microsoft-365-docs#12394]
[Enter feedback here]
The following example is incorrect.
Please correct it immediately.

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/printer-protection?view=o365-worldwide#scenario-2-allow-specific-approved-usb-printers-using-intune

-incorrect
 example `<enabled><data id="ApprovedUsbPrintDevices_List" value="03F0/0853,`

-correct
 example `<enabled/><data id="ApprovedUsbPrintDevices_List" value="03F0/0853,`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0131f7d-e811-d9bc-c372-c56b19b4a091
* Version Independent ID: 0fc6d8db-b125-3985-b9d7-c97587d4ebd2
* Content: [Microsoft Defender for Endpoint Device Control Printer Protection](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/printer-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/printer-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/printer-protection.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Lovina-Saldanha
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@komatsuyuta1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12430

Once the author approves, the changes will be live.

Thanks
Sri
