### ISSUE TITLE
Bypass malware filter

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/microsoft-365-docs#1240]
The answer is missing a *not* if I'm correct. Otherwise the Answer *No* doesn't make any sense.

Q. I am not able to receive a specific attachment because it is being falsely filtered by the malware filters. Can I allow this attachment through via mail flow rules?

A. No. You can ***not*** use Exchange mail flow rules to bypass the malware filters. If you would like this attachment to bypass the malware filters, send the attachment to the intended recipient within a password protected .zip file. Any password protected file is bypassed by malware filtering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 180de890-8454-96ba-3a68-53d1a9a0b319
* Version Independent ID: a702d0cf-c426-f3d7-ed50-144e4f26d4d7
* Content: [Anti-malware protection FAQ  - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-malware-protection-faq-eop#q-i-am-not-able-to-receive-a-specific-attachment-because-it-is-being-falsely-filtered-by-the-malware-filters-can-i-allow-this-attachment-through-via-mail-flow-rules)
* Content Source: [microsoft-365/security/office-365-security/anti-malware-protection-faq-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-malware-protection-faq-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Weishaupt, fixed. In the future, you, too, can make simple fixes like this [directly](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md) without opening a GitHub Issue first.

Thanks for the feedback.
