### ISSUE TITLE
Support for macOS MS Defender device tag via Intune

### ISSUE THREAD

**Issue by jhlau-paloit** [MicrosoftDocs/microsoft-365-docs#12405]
Is macOS really supported for adding device tags via Intune? There are steps for Windows but missing the steps for macOS. The redirect link is only a general guidance on setting up a custom config in Intune for macOS and it's not useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51c29286-b601-4dad-0e65-227c8d045ee4
* Version Independent ID: 2af4acf9-4089-5dff-d628-16b8425e0a57
* Content: [Create and manage device tags](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-tags?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine-tags.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine-tags.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Please open comment on the Intune page.
