### ISSUE TITLE
"Advanced option: Microsoft Teams" section is confusing as referencing Skype in the middle of process

### ISSUE THREAD

**Issue by Lderib** [MicrosoftDocs/microsoft-365-docs#12409]
[The "Advanced option: Microsoft Teams" section is confusing as it mentions 4 entry needed for Teams and after describing the 2 first entries the process switches and is referencing Skype for the 2 remainingentries.
Is it a typo and one should read Teams?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5a6649-19ba-86b0-bd19-2250c9b66968
* Version Independent ID: 17867a08-ec7c-f5bb-7a03-94e9027ff0f8
* Content: [Connect your DNS records at Namecheap to Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-gb/microsoft-365/admin/dns/create-dns-records-at-namecheap?view=o365-worldwide#advanced-option-microsoft-teams)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-namecheap.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-namecheap.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by neshvig10** [comment]
can I fix this one
