### ISSUE TITLE
Non-visible payment methods

### ISSUE THREAD

**Issue by redmeades-ud** [MicrosoftDocs/microsoft-365-docs#12403]
There needs to be a section addressing what to do if I cannot see a payment method.

I see a notification indicating this, but I want to do something about it - I cannot delete it, nor change billing to use a newly added card.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14e33d-0d3e-45f4-fefe-dec3ae7d351f
* Version Independent ID: aeb53e2c-d35c-73fe-26f2-4f101bfeeea7
* Content: [Manage payment methods](https://learn.microsoft.com/en-au/microsoft-365/commerce/billing-and-payments/manage-payment-methods?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-payment-methods.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-payment-methods.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@redmeades-ud Thank you for your feedback. Ideally, if you don't see the payment method, we recommend contacting support.  We have added that information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12431


Once the author approves, the changes will be live.

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@redmeades-ud Are you the admin who added the payment method you're trying to change/replace? What is the exact notification you see?

**Comment by cmcatee-MSFT** [comment]
Closing since there's been no response from the customer on this.
