### ISSUE TITLE
"Known issues" says "None" for platform 4.18.23050.5 

### ISSUE THREAD

**Issue by omegagx** [MicrosoftDocs/microsoft-365-docs#12401]
Platform: 4.18.23050.5 has a serious performance issue where it slows down 3rd party browsers significantly. There is even a service health advisory DZ615064 stating that but this webpage still says "None" under "Known issues" - please update that.

The issue started on May 30th, 2023 which is more than enough time to update "Known issues" on this documentation page.
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/19207488/9865b32f-0df0-4e24-990c-d9bdaaacd03e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61d65c37-bbb6-5c7a-8405-5994badd0b23
* Version Independent ID: 61d65c37-bbb6-5c7a-8405-5994badd0b23
* Content: [Microsoft Defender Antivirus security intelligence and product updates](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-updates.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you for letting me know about this, @omegagx. Looking into it.

**Comment by denisebmsft** [comment]
Hello @omegagx. Thank you again for raising this issue. I've added an item to the "Known issues" for the May 2023 Update. Please let me know if you have any other questions.

**Comment by omegagx** [comment]
> Hello @omegagx. Thank you again for raising this issue. I've added an item to the "Known issues" for the May 2023 Update. Please let me know if you have any other questions.
Thanks a lot for your help.
Also, can you please make sure the process to post known issues for the Defender platform exists and is followed in some kind of an automated fashion? This issue has been happening since May 30th and I asked support many times to update it over the last 3 weeks - we even opened a support ticket and we were told it would be done but until I made you aware of it, no one has contacted the documentation team, so it appears the process is broken somehow. @denisebmsft
