### ISSUE TITLE
Weekday and Day of month values?

### ISSUE THREAD

**Issue by marckerr** [MicrosoftDocs/microsoft-365-docs#12416]
[Enter feedback here]
The Weekday and Day values for the .plist are a little confusing. If you set the Day of the month value to 1 and the Weekday to 1. Does that mean the scan would only run on the 1st of the month if that is also the first day of the week? Or does it run on the 1st day of the month as well as every 1st day of the week?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae1c59b1-e4aa-6a18-7c34-720d0eb83c5d
* Version Independent ID: f5a3fc3c-bec2-3d7a-1d61-e23a0c1f8d4f
* Content: [How to schedule scans with Microsoft Defender for Endpoint on macOS](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-schedule-scan?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-schedule-scan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-schedule-scan.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@marckerr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12453

Day and weekday are usually competing schedule items and are generally not used in conjunction with each other when calling a process.

Once the author approves, the changes will be live.

Thanks
Sri
