### ISSUE TITLE
Inadequate information provided

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/microsoft-365-docs#12418]
This page is overly simplistic and not that useful in its present state. If administrators will be enabling auditing for their users, they will almost certainly be enabling it for every user in the organization. Why do you not provide powershell commands to check whether users have Microsoft 365 Advanced Auditing enabled on their account? Or which users don't? Or (most usefully) to enable it for every user in an org? Why not provide information about whether this is the default condition when an E5 license is applied, or whether admins will need to enable it on a per user basis going forward?

In Step 2, you give a command to enable two Audit (Premium) events. How about including the powershell commands to check whether users have auditing enabled for these events already? How about (most usefully) including the appropriate commands to enable it for every user in an org? Again, if an E5 license is applied, will these events still need to be enabled for each individual user going forward, and thus incorporated into the new user setup routine? 

When writing documentation that is obviously geared toward the enterprise, please make your focus creating documentation that is useful in an enterprise scenario for a large number of users, and anticipate the typical admins' questions in implementing the feature on an ongoing basis rather than just supplying the absolute minimum information necessary. Security is an important concern for organizations, and your documentation should reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d420e29-9348-48e6-673f-141212bf4de6
* Version Independent ID: d7e79a0d-39bf-abe1-3a2e-b9ba0f099934
* Content: [Set up Audit (Premium) in Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-premium-setup?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-premium-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-premium-setup.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@ianc911 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
