### ISSUE TITLE
Please update "Use Group Policy to disable local list merging" section in this Docs.

### ISSUE THREAD

**Issue by KENJISHIRAKI** [MicrosoftDocs/microsoft-365-docs#12419]
[Enter feedback here]
This section suggests setting "Configure local administrator merge behavior for lists" to "Disable" to disable the local administrator merge behavior. In this case, the DisableLocalAdminMerge registry is set to "0".
However, this is for older group policy templates.
If you use the latest administrative template for Windows 11, setting "Configure local administrator merge behavior for lists" to Disable will enable the local administrator merge behavior, DisableLocalAdminMerge is set to "1".
This is due to a change in the Group Policy specification in Windows 11.

The following Docs "Administrative Templates (.admx) for Windows 11 2022 Update (22H2)" and "Administrative Templates (.admx) for Windows 10 November 2021 Update (21H2)" templates, compare the description of "Configure local administrator merge behavior for lists". You will see that the specification has changed.
https://learn.microsoft.com/en-us/troubleshoot/windows-client/group-policy/create-and-manage-central-store#links-to-download-the-administrative-templates-files-based-on-the-operating-system-version

So, could you please add that "Configure local administrator merge behavior for lists" needs to be set to Enable if you want to disable the local administrator merge behavior in the latest template?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8b1f64a-e4fd-574c-06b2-55aef958516d
* Version Independent ID: 3bee5906-0a2a-d2f3-08b8-efbc4b3de739
* Content: [Configure local overrides for Microsoft Defender Antivirus settings](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-local-policy-overrides-microsoft-defender-antivirus?view=o365-worldwide#use-group-policy-to-disable-local-list-merging)
* Content Source: [microsoft-365/security/defender-endpoint/configure-local-policy-overrides-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-local-policy-overrides-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@KENJISHIRAKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12454

Once the author approves, the changes will be live.

Thanks
Sri
