### ISSUE TITLE
Managing user consent for apps article doesn't show in TOC

### ISSUE THREAD

**Issue by ashishguptaiitb** [MicrosoftDocs/microsoft-365-docs#12422]
The page at /microsoft-365/admin/misc/user-consent does not show up in the TOC -- when the page is opened, the TOC doesn't expand to show its location in the TOC. Is this an orphaned page that needs a redirect OR is it a bug on learn.microsoft that TOC doesn't expand upon opening the article? I attempted to search for the title in the TOC search field and it still didn't show. Please investigate and fix. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b13e4c14-5b0a-a4f6-1e65-7c79e49a0f10
* Version Independent ID: ec4223f2-8127-7605-07a0-306c4d412fed
* Content: [Managing user consent to apps in Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/misc/user-consent?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/user-consent.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/user-consent.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by ashishguptaiitb** [comment]
@kwekuako , I see this as the TOC entry now. Seems like the above is addressed. Thoughts?

<img width="251" alt="image" src="https://github.com/MicrosoftDocs/microsoft-365-docs/assets/49870256/37d15998-2a94-4570-ae6f-cddd216f8bc7">

**Comment by yogkumgit** [comment]
@ashishguptaiitb Thanks.
