### ISSUE TITLE
Wrong ResourceAppIdUri and Query URL

### ISSUE THREAD

**Issue by TestagonEins** [MicrosoftDocs/microsoft-365-docs#12426]
It took me awhile to figure out what's wrong, but I finally managed to find the cause.
When the script is executed as described in the article, the user will face the following error:
_**"Unauthorized","message":"Unauthorized request - reason of failure: Account mode is inactive"**_
It is because 
`$resourceAppIdUri = 'https://api.securitycenter.microsoft.com'`
should be changed to
`$resourceAppIdUri = 'https://api.security.microsoft.com'`
After changing that, the user will encounter another error:
_**"code":"Forbidden","message":"Missing application roles. API required roles: AdvancedQuery.Read.All, application roles"**_
It is because 
`$url = "https://api.securitycenter.microsoft.com/api/advancedqueries/run"`
should be changed to
`$url = "https://api.security.microsoft.com/api/advancedhunting/run"`
After those changes the script runs flawlessly. Of course you need to have AdvancedHunting.Read.All permission assigned to the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7cd6dd-8a34-95e4-655e-f4c6c0edb439
* Version Independent ID: 84b357ce-c1f7-89a5-a971-4656e79c6abf
* Content: [Advanced Hunting with PowerShell API Basics](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-sample-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-advanced-query-sample-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-advanced-query-sample-powershell.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@TestagonEins Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12455

Once the author approves, the changes will be live.

Thanks
Sri
