### ISSUE TITLE
Retention policy licence requirement seem wrong, F5 also have right to change the settings

### ISSUE THREAD

**Issue by adrienmaugard** [MicrosoftDocs/microsoft-365-docs#12425]
Hello

I have a question about this part of the documentation:
To retain an audit log for longer than 90 days (and up to 1 year), the user who generates the audit log (by performing an audited activity) must be assigned an Office 365 E5 or Microsoft 365 E5 license or have a Microsoft 365 E5 Compliance or E5 eDiscovery and Audit add-on license. To retain audit logs for 10 years, the user who generates the audit log must also be assigned a 10-year audit log retention add-on license in addition to an E5 license.

Audit (Premium) can be obtained via other licences than E5 and E5 add-on.
The retention policy can also be upgraded up to 1 year retention if you have for example and F5 Compliance and Security

Is the quoted sentence is true that ONLY E5 have this feature, or all bundle with Audit (Premium) have this?
(the 10 years retention licence is only available for E5 and not for F5, but this seem overkill when you need only 1 years retention)

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@adrienmaugard Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
