### ISSUE TITLE
What happens exactly when a Litigation hold is removed?

### ISSUE THREAD

**Issue by ContreBombarde** [MicrosoftDocs/microsoft-365-docs#12421]
_Based on previous experiences here, please do not close this by recommending reaching out to Support. This is a documentation question regarding https://learn.microsoft.com/en-US/microsoft-365/compliance/ediscovery-create-a-litigation-hold?view=o365-worldwide (it's unclear to me why going to the View all page feedback link and clicking New issue doesn't include a reference to the page in question... forgive me if this is a GitHub noob question, but I've been asked previously to include a reference to the original page, so maybe it's not just me?)._

On the page in question, it details what happens when a Litigation hold is applied. However, as with much documentation, it does not describe exactly what happens when the setting is undone/removed (when the Litigation hold is removed in this case). Could this info be added to the page?

Thank you for your help! The documentation is continually improving.

**Comment by yogkumgit** [comment]
@ContreBombarde Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
