### ISSUE TITLE
Cancel

### ISSUE THREAD

**Issue by hstandley** [MicrosoftDocs/microsoft-365-docs#12438]
I find it interesting that you have links for many things but none that make canceling easy to do. That is what I want to do.

**Comment by yogkumgit** [comment]
@tiburd Please help.

**Comment by msbemba** [comment]
@hstandley Thank you for your feedback. I'm not sure which document you are reviewing currently, however We have a topic on how to cancel: [Cancel your Microsoft business subscription | Microsoft Learn](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hstandley Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
