### ISSUE TITLE
(preview) should be removed from Restricted app groups (preview).

### ISSUE THREAD

**Issue by YoshihiroIchinose** [MicrosoftDocs/microsoft-365-docs#12439]
We see still "preview" in Endpoint DLP page for "Restricted app groups (preview)". This feature has been GA since mid of 2022. So, "(preview)" should be removed from Restricted app groups (preview).
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f25ec8-d5a8-4a9d-ca72-bd61eacd9dbc
* Version Independent ID: 34f25ec8-d5a8-4a9d-ca72-bd61eacd9dbc
* Content: [Configure endpoint DLP settings - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-configure-endpoint-settings?source=recommendations&view=o365-worldwide#restricted-app-groups-preview)
* Content Source: [microsoft-365/compliance/dlp-configure-endpoint-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-configure-endpoint-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@YoshihiroIchinose Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
