### ISSUE TITLE
Needs a note to distinguish GCC from GCCH as this is not supported in the latter.

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/microsoft-365-docs#12435]
Hi Team - this is not currently a supported feature in GCCH, the article is a bit ambiguous and it would be helpful to call out that this is for GCCModerate, and not GCCH/DOD.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6be7caf9-523d-2e84-fb17-14b1606aa97a
* Version Independent ID: 34a7cb37-5f79-c1d3-f40f-8afb91f48862
* Content: [Connect to Microsoft 365 Government Community Cloud (GCC) data with Usage Analytics - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/usage-analytics/connect-to-gcc-data-with-usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/connect-to-gcc-data-with-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/connect-to-gcc-data-with-usage-analytics.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@drdenson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12458

Once the author approves, the changes will be live.

Thanks
Sri
