### ISSUE TITLE
G-Cloud certifications

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/microsoft-365-docs#1243]
The links for G-Cloud certifications don't seem to link to the evidence for certification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 325c4ef5-eba1-1c1c-fac0-e4005d5022f6
* Version Independent ID: 94abd524-48b9-0786-dde3-ff9a94134b69
* Content: [United Kingdom Government-Cloud (G-Cloud) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-g-cloud-uk)
* Content Source: [microsoft-365/compliance/offering-G-Cloud-UK.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-G-Cloud-UK.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@Air-Git - thanks for the feedback, what specifically are you looking for? The listed links primarily point to documentation on the Service Trust Portal that is specific to each service.

**Comment by Air-Git** [comment]
The link to Office 365 UK G cloud Risk Environment is to a general list of assessment reports not specifically UK and not specifically Office 365: https://aka.ms/Office365UKGCloudRiskEnvironment

**Comment by robmazz** [comment]
@Air-Git - thanks for the clarification. Yes, it looks like that link should point to this location, will update the topic and republish. Thanks!

https://servicetrust.microsoft.com/ViewPage/UKComplianceResourcesV3?command=Download&downloadType=Document&downloadId=89df60d3-b96f-4c08-a5dc-6f5db86b8800&tab=626aa9e0-3d7b-11e9-9157-b7b7eba45f26&docTab=626aa9e0-3d7b-11e9-9157-b7b7eba45f26_GRC_Assessment_R
