### ISSUE TITLE
Unspecific wording in terms of auto remediation

### ISSUE THREAD

**Issue by mikerobyn** [MicrosoftDocs/microsoft-365-docs#12434]
Hi,

if the following part of the page is meant to say that the stated actions are the only ones that are supported in automated remediation, then the text should be changed to "Whether taken automatically or upon approval, an automated investigation **and remediation** can result in in one ore more of the remediation actions".

Current text:
Whether taken automatically or upon approval, an automated investigation can result in one or more of the remediation actions:

Quarantine a file
Remove a registry key
Kill a process
Stop a service
Disable a driver
Remove a scheduled task

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f9e011b-c50f-3549-286a-0810ad2cb8c9
* Version Independent ID: e31b4231-10c3-fed2-651a-3f0e4685f3b8
* Content: [Review remediation actions following automated investigations](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-auto-investigation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-auto-investigation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-auto-investigation.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@mikerobyn Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12457

Once the author approves, the changes will be live.

Thanks
Sri
