### ISSUE TITLE
Product Names Wrong

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#12444]
This article states at the beginning

"To create your own custom gradual rollout process for Defender updates, you can use Group Policy, Microsoft Configuration Manager, and PowerShell."

Then it lists 3 sections - Group Policy, Intune and PowerShell

Note - Microsoft Configuration Manager is referred to in the opening paragraph, but in the sections below this is replaced with Intune

Please correct and stick to common product names rather than using different names interchangeably  to prevent confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f65bc58-aab1-16bb-4a4b-30a21491ca99
* Version Independent ID: ee076a7a-4abb-6664-3c78-735ffaf3fd54
* Content: [Create a custom gradual rollout process for Microsoft Defender updates](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-updates?view=o365-worldwide&source=recommendations)
* Content Source: [microsoft-365/security/defender-endpoint/configure-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-updates.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@pjrcdf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12461

Once the author approves, the changes will be live.

Thanks
Sri
