### ISSUE TITLE
What about E5 users

### ISSUE THREAD

**Issue by AJ-Gov** [MicrosoftDocs/microsoft-365-docs#12443]
Hi,

On this page you talk about the Defender for Endpoint Plan 2 and E3, what about customers who have MS 365 E5 license?

Thanks
Amjad

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa2cb7af-a9ea-41cf-60ec-b33ff122b058
* Version Independent ID: fa2cb7af-a9ea-41cf-60ec-b33ff122b058
* Content: [Sign up for Microsoft Defender Vulnerability Management](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/get-defender-vulnerability-management.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@AJ-Gov Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12460

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba
