### ISSUE TITLE
The information about the "Bill to" address part is wrong. We need to update the "Bill to" address also under the products subscription page

### ISSUE THREAD

**Issue by ieokkokwong** [MicrosoftDocs/microsoft-365-docs#12440]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50536931-a7c8-620a-aae0-9c4baec51f74
* Version Independent ID: 27ce5737-2b34-cb55-07b0-c8450c0e5d62
* Content: [Change your billing addresses](https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@ieokkokwong Thank you for your feedback. I was able to test this by going into the Billing > Payment methods section.

I was not able to make this change from the products subscription page, so the document seems to be correct.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ieokkokwong Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ieokkokwong** [comment]
As I reported at the beginning, the information in this documentation is wrong. Otherwise, why would I even bother providing information to you. If you feel that you want to keep information wrong, then I have no choice. Let's more customers complain then.
As I am an actual paying customer, here is an evidence that the "Payment method" page according to the documentation is actually empty.
![Screenshot 2023-07-15 002324](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/74746504/fd2c8737-5f49-4bb0-876f-8268b36865c2)

However, the payment method is actually under the actual product subscription.
![Screenshot 2023-07-15 002448](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/74746504/13152723-d98f-4d53-a846-229ffa10996e)
