### ISSUE TITLE
Update article as per new exchange admin center . There is change in navigation options

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/microsoft-365-docs#12446]
Please update the article as per new exchange admin center.  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe0e7a9a-356a-724b-77ab-41a3c456154b
* Version Independent ID: 78ce0ee4-bd8f-4cfa-cea4-170af5d21aff
* Content: [Define mail flow rules to encrypt email messages - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@robinpoulose1 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
