### ISSUE TITLE
NPS Feedback 

### ISSUE THREAD

**Issue by oneillliam** [MicrosoftDocs/microsoft-365-docs#12447]
[Enter feedback here]
Hi

Just looking to understand please the definitions for Promoters, Passives and Detractors in terms of the 5 point scale ?

Presuming that a 5 is a Promoter but what about 4 etc?

Thanks very much

Liam

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc81f41c-573b-fa50-f2a2-e6a929127e20
* Version Independent ID: b02ba4fe-163e-b8fb-db67-750f15de2af3
* Content: [Microsoft product NPS feedback and insights for your organization - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-feedback-product-insights?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-feedback-product-insights.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-feedback-product-insights.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
@oneillliam 
Hi Liam,

Thank you for submitting your feedback. The documentation team reports that the topic has been updated to include examples.

Best wishes!
