### ISSUE TITLE
Office 365 URL and IP address article inaccurate

### ISSUE THREAD

**Issue by dingovvarrior** [MicrosoftDocs/microsoft-365-docs#12441]
I spent 8 hours troubleshooting why mail wasn’t being received last night. The IP ranges listed for SMTP from 365 is incomplete. This caused us major stress as we could see IP addresses in logs but not allowed.

we had to look at this JSON file for Exchange Online protection subnets, to get the complete list. Further, your document doesn’t make mention of Subnets or IP addresses to allow for the Remote Connectivity Validator (which frankly is useless now and there is no way to get back to the old reliable one that made sense).

you need to make mention of this json file in the knowledge base article, as 8 hours troubleshooting for an incomplete article is a nightmare.

further, you need to update the firewall rules tables to say whether the traffic is inbound, or outbound, or both. Our firewall people couldn’t make sense of it. The use of the word ‘client’ is not clear enough.

please follow your own article in a test environment, with constraints on allowing traffic in and out of on premise exchange and where you have a problem, fix the article. Please also include the test ip addresses used by Microsoft for the remote connectivity analyser and others.

If you can create a PowerShell script that we can schedule, to import the subnets to the receive connector from the JSON file for Exchange mail protection IP addresses, this would greatly help too.

you also need to clarify the *.mail.protection.outlook.com which is listed in the table, because Exchange 2016 does not allow the use of domains on receive connectors and it is not clear if that DNS wildcard includes other Ip addresses or not.

the hybrid configuration wizard is also broken, with the latest build and CU of Exchange 2016. It does not create the receive connectors and there is no clear article on manually setting one up.

Our migration has been a nightmare because of these issues. Please fix it asap.

I am very frustrated, but have tried to keep my feedback clear as it is so difficult to get clear answers. When you update a document or article, someone needs to test it from beginning to end, before publishing.

https://www.microsoft.com/en-us/download/details.aspx?id=56519

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@dingovvarrior Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data.
We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.

Thanks
Sri
