### ISSUE TITLE
Clarify Reissuance Notice Trigger

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#1245]
Could you please update the Re-Issuance notification section to clarify that you have to edit the portal content to trigger the re-issuance notice? It is not clear that this is what triggers the notice. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4faa207-c5ae-c300-144e-3b7e59ea6ef6
* Version Independent ID: cbdb3efa-5a3f-27f7-8da2-c4dea01aae8b
* Content: [Create a legal hold notice - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-hold-notification#re-issuance-notification)
* Content Source: [microsoft-365/compliance/create-hold-notification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-hold-notification.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@EricaToelle Thanks for the heads up. This topic has been updated to address this. We also added a section on what triggers the sending of the different notifications.

https://docs.microsoft.com/en-us/microsoft-365/compliance/create-hold-notification?view=o365-worldwide#events-that-trigger-notifications
