### ISSUE TITLE
Bookings Calendar is now Bookings Page

### ISSUE THREAD

**Issue by MSUMOLL** [MicrosoftDocs/microsoft-365-docs#12450]
Microsoft has changed terminology. what used to be called a booking calendar is now called a booking page. the only thing still referred to as a booking calendar is the actual calendar in the bookings application. Changing references to booking calendar to booking page is advisable everywhere. 

If anyone knows how to get ahold of folks at microsoft. The confirmation email that is sent out when a booking page is created is still using the outdated booking calendar terminology, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db93982a-4d08-b3be-4f3d-33ff5b9d20b2
* Version Independent ID: 30541004-90bb-b9fc-02a6-a04e7a921b13
* Content: [Enter your Bookings business information](https://learn.microsoft.com/en-us/microsoft-365/bookings/enter-business-information?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/enter-business-information.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/enter-business-information.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@MSUMOLL Thank you for your feedback. We have fixed this document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12456

We have also informed the PM's on the confirmation email as it is still referred to as the Bookings calendar.

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by MSUMOLL** [comment]
Thank _you_!
