### ISSUE TITLE
Search And Purge role missing in Data Investigator

### ISSUE THREAD

**Issue by kmsrajan** [MicrosoftDocs/microsoft-365-docs#1246]
Data investigator contains 9 roles in first table whereas in the second table it is missing "Search And Purge"

**Comment by mypil** [comment]
@kmsrajan - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by markjjo** [comment]
@kmsrajan I assume that your issue applies to the topic on RBAC permissions for the security and compliance center: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center

If so, thanks for the heads up. The Data Investigator role *should not* be in the second table, as the second is a list of roles (and the role groups they're assigned to by default). I think this is a cut and paste error. I'll go ahead and just delete the Data Investigator from the second table.

Please respond if my assumption is incorrect.
