### ISSUE TITLE
Incorrect Trigger for Data Theft by Leavers

### ISSUE THREAD

**Issue by paulohanlon** [MicrosoftDocs/microsoft-365-docs#12466]
In section "Policy template prerequisites and triggering events" there is a table which states the triggering event for "Data Theft by departing users" is "Resignation or termination date indicator from HR connector" but I don't believe this is true. This policy is triggered when the user is imported via the HR Connector and lasts until the termination date. Neither the resignation date nor the termination date are "triggers" I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3dbafdce-9c36-3989-5671-97b02cf6b468
* Version Independent ID: 3dbafdce-9c36-3989-5671-97b02cf6b468
* Content: [Learn about insider risk management policy templates - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-policy-templates?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-policy-templates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-policy-templates.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@paulohanlon Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
