### ISSUE TITLE
"Please refer to Azure Active Directory Data Locations" Power BI Report Broken

### ISSUE THREAD

**Issue by adamfowlerit** [MicrosoftDocs/microsoft-365-docs#12474]
The link [Please refer to [Azure Active Directory Data Locations](https://aka.ms/aaddatamap).](https://aka.ms/aaddatamap) loads a Power BI report, but when you click the drop down menu to 'Select your company geo' an error comes up saying 'can't display this visual'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b59be58-a0a1-08a0-bfed-d8958ba58e56
* Version Independent ID: 4b59be58-a0a1-08a0-bfed-d8958ba58e56
* Content: [Data Residency for Other Microsoft 365 Services - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/m365-dr-workload-other?view=o365-worldwide#azure-active-directory-aad)
* Content Source: [microsoft-365/enterprise/m365-dr-workload-other.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/m365-dr-workload-other.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by adamfowlerit** [comment]
Someone's updated the page :) It did go to a Power Bi report, now it just loops to the same page - why would https://aka.ms/aaddatamap mentioned on this page with an external page link, now link back to this page?

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @adamfowlerit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
