### ISSUE TITLE
not helpful

### ISSUE THREAD

**Issue by haddenmart** [MicrosoftDocs/microsoft-365-docs#12472]
outlook goes and marks email as junk that is 3 days old and I have approved them. It also marks as junk email from senders that I routinely communicate with. The safe sender list is not capable of handling all the senders that are being mistakenly marked as junk. my settings for junk is No Automatic Filtering. Only senders in the blocked list should go to junk but that is not happening. 

Outlook 365 version 2308 (Build 16708.20004 Click to Run)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b36a6f3e-632a-bf8e-4293-7eae6bd6e68f
* Version Independent ID: b36a6f3e-632a-bf8e-4293-7eae6bd6e68f
* Content: [(False Positives) How to handle legitimate emails getting blocked from delivery using Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/step-by-step-guides/how-to-handle-false-positives-in-microsoft-defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/step-by-step-guides/how-to-handle-false-positives-in-microsoft-defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/step-by-step-guides/how-to-handle-false-positives-in-microsoft-defender-for-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@haddenmart, you're asking in an area that deals with admin features as part of Office 365/Microsoft 365. For example, admins handle false positives (good marked bad) and false negatives (bad let through) in the [Tenant Allow/Block List](https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-about).

But it sounds like that's not available to you as you're just using Outlook.

**Comment by haddenmart** [comment]
I have admin rights and did use them and not just outlook

**Comment by msbemba** [comment]
@haddenmart Thank you for your feedback. This sounds more like a technical issue and I'd recommend you contacting support via the need help section on the admin center, so that our engineers can analyze and fix or escalate depending on the issue.

Hope this helps!

Thanks
Sri

**Comment by haddenmart** [comment]
It is not a technical issue. It is the fact that I had to go through 8 captchas to get in. I am a human but it told me I was not the first time.
