### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by Phantom-Physics** [MicrosoftDocs/microsoft-365-docs#12470]
Under FAQ
Q: What happens to my data after the trial expires?
A: After your trial expires, **yo** have access to your trial data (data from features in Defender for Office 365 that you didn't have previously) for 30 days. After this 30 day period, all policies and data that were associated with the Defender for Office 365 trial are deleted.

Should read "you'll"
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d08fef08-2fa6-79c4-4adf-e1e194a33a0d
* Version Independent ID: 6c962f09-1e5d-bcac-c58f-ecaf58bc9774
* Content: [Try and evaluate Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/try-microsoft-defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/try-microsoft-defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/try-microsoft-defender-for-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Phantom-Physics, fixed.

In the future, you too can make changes like this yourself without opening a GitHub issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing

**Comment by Phantom-Physics** [comment]
Cool!! Good to know. Thank you
