### ISSUE TITLE
*.contoso.com/* does not work for URL: https://www.contoso.com

### ISSUE THREAD

**Issue by baswijdenes** [MicrosoftDocs/microsoft-365-docs#1247]
***.contoso.com/***
Allows recipients to visit a domain, subdomains, and paths, such as https://www.contoso.com, https://www.contoso.com, https://maps.contoso.com, or https://www.contoso.com/a.This entry is inherently better than *contoso.com*, because it doesn't include potentially fraudulent sites, like https://www.falsecontoso.com or https://www.false.contoso.completelyfalse.com
-- | --

The example is incorrect, with a / will only search for URLs including a / at the end. 

If we use domain.com with the / in the signature it will still be rewritten.

**Comment by mypil** [comment]
@baswijdenes - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@baswijdenes - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
