### ISSUE TITLE
All learn pages videos are not optimized for tablet / touchscreens experience 

### ISSUE THREAD

**Issue by peterwww** [MicrosoftDocs/microsoft-365-docs#12473]
Just try to get controls for the video while opening videos in full screen mode And you will see what I mean. Pulling up controls behavior is very inconsistent they sometimes show up but it's random there is no single gesture which would actually bring up the controls especially since swipe down from the screen activates windows taskbar so this takes control over the screen instead of video controls

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8690a332-f672-8db8-1552-5ee16e78746f
* Version Independent ID: 3df5b553-4e29-da25-c0e4-10686c5fed20
* Content: [Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by peterwww** [comment]
to give you bit more context, when I watch learn video in full screen accessing controls is always hit an miss as there seems to be no single gesture or interaction that brings them up, they sometimes show up and sometimes I can just press with 2 fingers to get play pause if remember correctly but that won't get you out of Fullscreen mode or allow scrollbar to move through material ... Maybe it's just me but then again if there was an easy self explanatory way to do this I'm quite sure I'd find it as I do on any other product with good UX, so I would expect other users have same issue.

Best

PW
________________________________

**Comment by mjcaparas** [comment]
Limitations
