### ISSUE TITLE
Typo on learn document.

### ISSUE THREAD

**Issue by MyISPisSlow** [MicrosoftDocs/microsoft-365-docs#12485]
There is a grammer issue in the Review Set section.

"You can also <Missing a word here> tagging to determine which documents to export."
Replace with: also use tagging or also utilize tagging

https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-create-and-manage-cases?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 343654ec-23bf-c946-141f-3b43ad8b170b
* Version Independent ID: 343654ec-23bf-c946-141f-3b43ad8b170b
* Content: [Create and manage an eDiscovery (Premium) case - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-create-and-manage-cases?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-create-and-manage-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-create-and-manage-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@MyISPisSlow Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
