### ISSUE TITLE
Phase 2: Create and configure the isolated team site

### ISSUE THREAD

**Issue by kkazala** [MicrosoftDocs/microsoft-365-docs#1248]
Creating SPO Team site using procedure described above will result in a group-connected team site. 
Which means that an O365 Group is created automatically. 
That is correct that using the steps in "Next, from the new SharePoint Online team site, configure permissions.", permissions are assigned to the Security groups without using the Office 365Group, and the &lt;site name&gt; Owners  are not group Owners. 
But... wouldn't it be better to create a team site without a O365Group (STS#3)?

The part "First, create the SharePoint Online team site with these steps." doesn't refer to the Group owner field, which is mandatory. In this case it's important that end users (someone from &lt;site name&gt; Owners ) is NOT defined here. Otherwise they would be able to add members to the O365Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 724a18a5-5ab0-9459-c17f-e26abcda1829
* Version Independent ID: 5536e4e8-6094-db8f-f9b8-a44e79692bcb
* Content: [Deploy an isolated SharePoint Online team site - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/deploy-an-isolated-sharepoint-online-team-site#feedback)
* Content Source: [microsoft-365/security/office-365-security/deploy-an-isolated-sharepoint-online-team-site.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/deploy-an-isolated-sharepoint-online-team-site.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by MikePlumleyMSFT** [comment]
@kkazala thanks for catching that - yes, in this case a team site with no group is a better way to go. I've submitted a PR to update the procedure. Should be on the live site in the next day or so.

**Comment by mypil** [comment]
@kkazala - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/e4151a6ea6. 


Thank you for your contribution to make the docs better! Much appreciated!
