### ISSUE TITLE
Suggestion to also add local command using Powershell to adjust UILockdown 

### ISSUE THREAD

**Issue by AndNovian** [MicrosoftDocs/microsoft-365-docs#12490]
I am working with a customer having UILockdown issue, where they checked GPO and found no policy on the UILockdown. However, when we checked Get-MpPreference we can see local device setting is set to true. 

I think it will be super helpful to others having similar issue where UILockdown is for some reason enabled locally from the device and they need to change them. We can use the following command:

**Set-MpPreference -UILockdown 0**

And use **Get-MpPreference t**o check the value of UILockdown
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/114455998/c02c2be1-00e3-49a4-8f86-6cc470b9106f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9870c42b-eede-b869-3d4d-cd2c53be82ed
* Version Independent ID: 8ae67d57-bb69-1e7c-92df-2960e2a2f152
* Content: [Hide the Microsoft Defender Antivirus interface](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-end-user-interaction-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-end-user-interaction-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-end-user-interaction-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@AndNovian Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12525

Once the author approves, the changes will be live.

Thanks
Sri
