### ISSUE TITLE
Sentence confusing, or worded incorrectly. 

### ISSUE THREAD

**Issue by T-Avery** [MicrosoftDocs/microsoft-365-docs#1249]
This sentence on this page, "If you use a retention policy to make an inactive mailbox, Office 365 continues to process the retention policy on the inactive mailbox" is confusing.  Does the retention policy make a mailbox inactive?  Is the mailbox already inactive and the retention policy is applied to it?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Overview of inactive mailboxes in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365#feedback)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@T-Avery Thanks for the feedback. As per the topic, a mailbox is made inactive by placing a hold/retention policy on it and then deleting the corresponding user account in AAD. You have to do those two things. There are many instances in this topic of "use a <lit hold or retention policy> to make a mailbox inactive..." which is a kind of short-hand for " place a <lit hold or retention policy> on the mailbox and then delete the corresponding user account to make it an inactive mailbox." The point of the sentence that you cite is that we will continue to process the retention policy on inactive mailboxes, which means that items in inactive mailboxes will be expired when the retention period is reached and items will be retained or deleted based on the retention action defined by the retention policy.

Let me know if you have any suggestions to make this clearer.
