### ISSUE TITLE
Why this option is gone

### ISSUE THREAD

**Issue by Malli88** [MicrosoftDocs/microsoft-365-docs#12491]
Hello,

Bookings is something we want to implement in our organization.
Could someone explain why we do not have this option and why there are so many people requesting it?
The Preschedule and decompression time is pretty much not usable, if I can't share the meeting with others attendees.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1a5147c-954b-7e29-bb95-f9c58f9413d0
* Version Independent ID: e1a5147c-954b-7e29-bb95-f9c58f9413d0
* Content: [Manage group attendees in Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/manage-attendees-bookings?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/manage-attendees-bookings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/manage-attendees-bookings.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Malli88 Thank you for your feedback. We recommend you post this in our main feedback portal https://feedbackportal.microsoft.com/ so that our Product engineering team can look at this and contact or update you on the status of this feature.

Hope this helps!

Thanks
Sri

**Comment by Malli88** [comment]
Hello @msbemba 
thank you for the response. Do you have a reference or a direct link for me?
Cheers
Stephan

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder.
