### ISSUE TITLE
Is GCC limitation still true?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#12501]
The section on Regulatory overview states that GCC tenants cannot use Universal templates. I have a client with a GCC tenant and the universal templates are available. Please update the documentation to reflect this availability. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef09c14-cd8a-91c4-b156-9ad03d6886a0
* Version Independent ID: a0411e7e-3ccc-f60e-f871-2d38637f45f7
* Content: [Learn about regulations in Microsoft Purview Compliance Manager - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-templates?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-manager-templates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-templates.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by yogkumgit** [comment]
@DeanGross Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
