### ISSUE TITLE
Both Android (portableDevice) and iOS (appleDevice)  are not GA now.

### ISSUE THREAD

**Issue by m-kikushima** [MicrosoftDocs/microsoft-365-docs#12500]
[Enter feedback here]
Both Android (portableDevice) and iOS (appleDevice)  are not GA now.
Is it possible to add above?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1045c931-5e47-95f1-1851-4710cf59325e
* Version Independent ID: 811f41b4-b663-06db-9737-d871767065fb
* Content: [Device control for macOS](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-device-control-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-device-control-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-device-control-overview.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@m-kikushima Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12517

Once the author approves, the changes will be live.

Thanks
Sri
