### ISSUE TITLE
Support page describes information not found

### ISSUE THREAD

**Issue by MetalGreg** [MicrosoftDocs/microsoft-365-docs#12503]
The support page (update April, 2023) reads

How to get to the Office activations report
1 In the admin center, go to the Reports > Usage page.

Yet on the home page of the Office 365 admin center, I find no link named "Reports"

There are three separate tiles with links containing the word "report"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9262b85d-883b-2b04-07ee-d4120dc7669f
* Version Independent ID: 7244aa48-52b4-1bc3-7c94-f87061869e41
* Content: [Microsoft 365 admin center Office activations reports - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft-office-activations-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/microsoft-office-activations-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft-office-activations-ww.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@MetalGreg Thank you for your feedback. I was able to locate the reports-->usage in the admin center

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/90f19e25-677d-4f95-b655-14a2300f2d95)


In case you still don't see this option, I'd recommend contacting support via the need help section on the admin center, so that our support engineer can fix it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MetalGreg Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MetalGreg** [comment]
Gentle reminder. Some people still use PCs and access the web the "old fashioned" way.



Sent via the Samsung Galaxy S23 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
