### ISSUE TITLE
Unable to download eDiscovery files on macos

### ISSUE THREAD

**Issue by katharos49** [MicrosoftDocs/microsoft-365-docs#12506]
Hello - referencing a related question #2825 - I need to download eDiscovery files from my Content Search in Purview and I am using macos 13.3.1(a).
I attempted to follow the instructions on this [KBA](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-configure-edge-to-export-search-results?view=o365-worldwide) but there is no ClickOnce option appearing on the edge://flags/ screen.

Without the ability to enable ClickOnce how can I successfully export reports and also PST files from Microsoft Purview?

Edge version Version 114.0.1823.82 (official build)
OS: macos 13.3.1(a) on Apple Silicone M1

**Comment by yogkumgit** [comment]
@katharos49 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
