### ISSUE TITLE
content filter does not work with AOVPN

### ISSUE THREAD

**Issue by NaserQujaq** [MicrosoftDocs/microsoft-365-docs#12508]
Please add a clear statement mentioning that customers can run MDE for iOS without the loopback VPN using content filter, however, this filter does not if customer is using AOVPN but works with other types of VPN. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [Deploy Microsoft Defender for Endpoint on iOS with Microsoft Intune](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@NaserQujaq Thank you for your feedback. We have a statement in the document which states the same

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide#device-configuration-profile-control-filter

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @NaserQujaq Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
