### ISSUE TITLE
Mismatching file type and OCR documentation for prebuild models

### ISSUE THREAD

**Issue by ChristianGalla** [MicrosoftDocs/microsoft-365-docs#12513]
According to this page, prebuild models are only supporting .bmp, .jpeg, .pdf, .png, and .tiff files, but regarding to their OCR description, office files are truncated at 64k characters.

Are for example docx files missing in the supported file list or has the truncation information already been added for further extension of the supported file types?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4be1aa4-860c-6480-502f-08f610f0b9b2
* Version Independent ID: a4be1aa4-860c-6480-502f-08f610f0b9b2
* Content: [Requirements and limitations for models in Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/requirements-and-limitations#structured-document-processing)
* Content Source: [microsoft-365/syntex/requirements-and-limitations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/requirements-and-limitations.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@seansquires -- Can you please clarify the supported file types for prebuilt models? Thank you.

**Comment by chuckedmonson** [comment]
@ChristianGalla -- Thank you for taking the time to ask about this. You're right, sorry for the confusion. Office file types aren't yet available for prebuilt models. The article will be updated accordingly. Thank you again for the feedback.
