### ISSUE TITLE
Error in assigning sensitivity Labels to excel files in Sharepoint online and Onedrive

### ISSUE THREAD

**Issue by bihagacharya** [MicrosoftDocs/microsoft-365-docs#1251]
Enabled the public preview feature, created a label and published. I can see the label under Sensitivity tab, but getting below error when I try to apply it.

We couldn't apply your label at this time. Please try again later.

**Comment by mypil** [comment]
@bihagacharya - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bihagacharya** [comment]
Using the below link.

https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files

**Comment by mypil** [comment]
@bihagacharya - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
