### ISSUE TITLE
What about Customer Lockbox for non-Microsoft employees like other CSPs?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1252]
Hello,

please provide information if Customer Lockbox does protect customer data not only from Microsoft employees but also other CSPs.

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Office 365 Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests#customer-lockbox-workflow)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@GiantCrocodile  Thank you for the feedback. Customer Lockbox ensures that Microsoft cannot access your content to perform a service operation without your explicit approval.  CSP's never have that option to perform a service operation. 

CSP can manage your tenant as an admin if you have added them as delegated administrators.

Hope this helps!

Thanks
Sri

**Comment by GiantCrocodile** [comment]
Thank you for your reply @msbemba! So Customer Lockbox won't help with delegated administrators. Is there something else to limit/to approve actions of delegated administrators beside seeing their past activity in the audit log?

**Comment by msbemba** [comment]
@GiantCrocodile There is no option to approve or decline the actions. However, the best you can do is to assign the roles/ There are two security groups, Admin Agents and Helpdesk Agents, more information can be found below.

https://docs.microsoft.com/en-us/partner-center/customers_revoke_admin_privileges#delegated-admin-privileges-in-azure-ad

**Comment by GiantCrocodile** [comment]
I will check this out in the next days and come back to you to confirm this did help or to ask for further details. Thank you!

**Comment by mypil** [comment]
@GiantCrocodile - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
