### ISSUE TITLE
O365 TI Connection Licensing clarification

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#12520]
the text states that we need to have o365 E5, what about M365 E5/G5, will these provide the necessary functionality? if so please clarify. 

What role is required to enable this feature? Please add this to the table

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4352228-5f34-5590-9721-a1d7cab2ac38
* Version Independent ID: 2a484437-5f3c-ab9f-b10e-67cd71f111a4
* Content: [Threat investigation & response capabilities in Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-ti?view=o365-worldwide&redirectSourcePath=%252fen-us%252farticle%252fOffice-365-Threat-Intelligence-overview-32405DA5-BEE1-4A4B-82E5-8399DF94C512)
* Content Source: [microsoft-365/security/office-365-security/office-365-ti.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-ti.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12547

Once the author approves, the changes will be live.

Thanks
Sri
