### ISSUE TITLE
Azure is now Entra

### ISSUE THREAD

**Issue by Uuinner** [MicrosoftDocs/microsoft-365-docs#12527]
I can't access Azure portal anymore and new Entra portal looks different. Needs to be updated for Entra

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9f839f-892b-57c3-97f0-76dd0095384d
* Version Independent ID: 3e9f839f-892b-57c3-97f0-76dd0095384d
* Content: [Add users and assign licenses in Microsoft Defender for Business](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-add-users?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-add-users.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@Uuinner Thank you for your feedback. While the name change is true, it is not yet reflected for customers and we expect it to start appearing in Microsoft product experiences In August 2023. We will update the document once this is official.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Uuinner Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
