### ISSUE TITLE
Timeout for pending actions

### ISSUE THREAD

**Issue by KENJISHIRAKI** [MicrosoftDocs/microsoft-365-docs#12522]
[Enter feedback here]
Regarding semi - require approval, I have confirmed that pending actions will time out after 7 days.
Could you please note in the Docs that leaving an action in a pending status will cause it to time out, and that if it times out, the behavior is the same as if the action had been rejected?
Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f996ba8e-6b9c-ee65-e401-310a8de48d15
* Version Independent ID: 07d04803-7552-399b-fb24-01c05e2e0a7b
* Content: [Automation levels in automated investigation and remediation](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/automation-levels?view=o365-worldwide#levels-of-automation)
* Content Source: [microsoft-365/security/defender-endpoint/automation-levels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/automation-levels.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@KENJISHIRAKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12545

Once the author approves, the changes will be live.

Thanks
Sri
