### ISSUE TITLE
Hyperlink about Compliance Portal Setting references to 404

### ISSUE THREAD

**Issue by aexlz** [MicrosoftDocs/microsoft-365-docs#12530]
If you click the hyperlink in the following section, you will be lead to a 404:

> If [reporting for Microsoft Purview Communication Compliance is turned off](https://learn.microsoft.com/en-us/microsoftteams/communication-compliance#report-a-concern-in-microsoft-teams), users might not have the dropdown list to select Security risk - Spam, phishing, malicious content. Instead, they're shown a confirmation pop-up.

**Comment by yogkumgit** [comment]
@aexlz Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
