### ISSUE TITLE
low-quality screenshots

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1253]
Some of the screenshots are of low-quality. They should be replaced with images with higher resolution.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Overview of file plan manager - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/file-plan-manager#feedback)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by chvukosw** [comment]
Hello, thanks for you feedback. Yes, these screenshots will be updated and improved for better readability in future updates to the topic.

**Comment by GiantCrocodile** [comment]
Is there any ETA for the next update of this topic @chvukosw? Is there something else wrong with this chapter?

**Comment by chvukosw** [comment]
Hi there- nope, nothing wrong. Just regular tweaks we do to optimize readability.

**Comment by sriharibabu9** [comment]
Hi, thanks for the explanation. The screenshots in this topic still blurred.
