### ISSUE TITLE
Data location for Dynamics 365

### ISSUE THREAD

**Issue by cwaddzz** [MicrosoftDocs/microsoft-365-docs#12534]
I was hoping for guidance on where my Dynamics 365 data is stored geographically. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://learn.microsoft.com/en-gb/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide&WT.mc_id=365AdminCSH_inproduct)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@cwaddzz Thank you for your feedback.  The PDF -https://aka.ms/dynamics_365_international_availability_deck has information about the following:

Product availability
Data location
Language
Localization

The Microsoft document for the same is - https://learn.microsoft.com/en-us/dynamics365/get-started/availability

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cwaddzz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
