### ISSUE TITLE
Update on "recommended" users count.

### ISSUE THREAD

**Issue by MrSchnappauf** [MicrosoftDocs/microsoft-365-docs#12532]
Thank you very much for your detailed doc page! 

But there is a small part which we think could be more clarified:

_"Too many users: When there are too many designated users concurrently accessing a shared mailbox (**no more than 25 is recommended**), they may intermittently fail to connect to this mailbox or have inconsistencies like messages being duplicated in the outbox."_

We had in on multiple occasions in the past that the Microsoft support rejected our tickets because there have been more than 25 users with FullAccess rights on the shared mailbox that had an issue. While there is no known technical limit to how much user I can give permissions to a mailbox, the supporter have said that more then 25 delegates is not supported. Microsoft basically forced us to reduce the number of  FullAccess users before continuing with the ticket.

Your article states that no more than 25 are recommended. A change in the wording from "recommended" to "not supported" would help us greatly since then we got a hard cap on an official Microsoft doc which can be communicated to our users. "Not recommended" sounds like "not nice but still ok" which always opens up new discussions with our management.

Thank you for your time and consideration!

Best regards,

@MrSchnappauf

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 289f2440-9c44-7d93-20e3-baa9e9892cd9
* Version Independent ID: abc4e209-a071-d28a-cb01-aa72bbaee7c0
* Content: [About shared mailboxes - Microsoft 365 admin](https://learn.microsoft.com/en-us/Microsoft-365/admin/email/about-shared-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/about-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/about-shared-mailboxes.md)
* Service: **microsoft-365-business**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@MrSchnappauf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12550

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by MrSchnappauf** [comment]
@msbemba 

Thank you for your time!
