### ISSUE TITLE
Did not apply - none of the PowerShell commands not recognized

### ISSUE THREAD

**Issue by mtnmann9** [MicrosoftDocs/microsoft-365-docs#12533]
Powershell responded to every query with: [command] is not recognized as the name of a cmdlet, function,
script file, or operable program.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc0555a1-2410-5679-03f3-e5768a1dc9cd
* Version Independent ID: e3d2444e-22f6-f697-03a4-9edb8226b72e
* Content: [View Microsoft 365 licenses and services with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@mtnmann9 Thank you for your feedback. I'm able to test all the commands without any issues. Hope you are connecting to module before running the cmdlet. If you continue to have problems, I'd recommend you contacting support via the need help section on the admin center, so that our support engineer can help you out.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mtnmann9 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
