### ISSUE TITLE
Clarify language in Teams User Activity Report

### ISSUE THREAD

**Issue by mcm223** [MicrosoftDocs/microsoft-365-docs#12540]
In the Teams User Activity report, there are separate fields for "Total organized meetings" and "Total participated meetings" so my expectation would be that the field "Total meetings" would include all meetings the user either organized or participated in. But the description for "Total meetings" says the following:

> The number of online meetings that the user **participated in** during the specified time period.

If that is the case, it's not clear what the difference is between "Total participated meetings" and "Total meetings," or whether organized calls are included in "Total meetings."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8bbc80-90d7-5bb5-520d-87db92c10c16
* Version Independent ID: b69c7d34-18ed-b3a3-fc4e-7ed2ab86d5c5
* Content: [Microsoft 365 admin center Teams user activity reports - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft-teams-user-activity-preview?view=o365-worldwide&bc=%2Fmicrosoftteams%2Fbreadcrumb%2Ftoc.json&toc=%2Fmicrosoftteams%2Ftoc.json)
* Content Source: [microsoft-365/admin/activity-reports/microsoft-teams-user-activity-preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft-teams-user-activity-preview.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@mcm223 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12551

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mcm223 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
