### ISSUE TITLE
Broken link for setup instructions

### ISSUE THREAD

**Issue by davebirr** [MicrosoftDocs/microsoft-365-docs#12543]
The reference in this link no longer exists:

Use those instructions to create CNAME records described in [Simplify Windows enrollment without Azure AD Premium](https://learn.microsoft.com/en-us/mem/intune/enrollment/windows-enroll#simplify-windows-enrollment-without-azure-ad-premium).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67847a65-598f-f3ff-0864-92a39dfdd86d
* Version Independent ID: e47b69f4-1964-e18b-e81e-31edc2e6798f
* Content: [Set up Basic Mobility and Security - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/basic-mobility-security/set-up?view=o365-worldwide)
* Content Source: [microsoft-365/admin/basic-mobility-security/set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/basic-mobility-security/set-up.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@davebirr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12553

Once the author approves, the changes will be live.

Thanks
Sri
