### ISSUE TITLE
Update Intune Deployment section to the latest interface 

### ISSUE THREAD

**Issue by AndNovian** [MicrosoftDocs/microsoft-365-docs#12541]
Please update Intune deployment part to match the current Intune Set up name
Devices > Configuration Profiles > Create Profile > macOS > Templates > Custom
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/114455998/a62200dd-b3e8-41a6-9e54-9874474d605b)

Current Docs is a little bit different:
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/114455998/2448d3b7-67f8-49d3-ba02-5b799196880b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2dc758cd-0668-546f-5132-c3b5d2bf2b8e
* Version Independent ID: afa7ca04-3825-e73a-bd6e-4cf55010bd60
* Content: [Set preferences for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-preferences?view=o365-worldwide#intune-full-profile)
* Content Source: [microsoft-365/security/defender-endpoint/mac-preferences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-preferences.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@AndNovian Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12552

Once the author approves, the changes will be live.

Thanks
Sri
