### ISSUE TITLE
Microsoft Ignite link broken

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1254]
The link to the video is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aea55d3-0ff7-e90d-41ce-63e8a67c44b8
* Version Independent ID: f64d3864-65b2-ca06-6c05-2543ad46d0e6
* Content: [Microsoft 365 ISO 27001 action plan — Top priorities for your first 30 days, 90 days, and beyond - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/iso-action-plan)
* Content Source: [microsoft-365/compliance/iso-action-plan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/iso-action-plan.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@GiantCrocodile - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/5c3d54d2a4712fd777e9e1e7e313fb60cc22e6b9. 


Thank you for your contribution to make the docs better! Much appreciated!
