### ISSUE TITLE
Discrepancy between Unified Audit log and Azure Sign In report for login events

### ISSUE THREAD

**Issue by Izauer** [MicrosoftDocs/microsoft-365-docs#1255]
I seeing that some of the Azure Active Directory events (user login events) are appearing in the Azure Sign In logs but in the unified logs (Azure Sign Ins referece: https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-audit-logs).
What is the difference between these two audit logs of login events?
Why some of the events appearing in one audit log but in the other one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Izauer A subset of Azure user login events are ingested to the unified audit log. Would suggest monitoring login events in the Azure portal, which has more detailed and robust reporting and formatting of information in the audit record. The schemas for the Azure auditing events that are ingested to the unified audit log are described here: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#azure-active-directory-base-schema

**Comment by Izauer** [comment]
@markjjo Thanks for your answer.
Regarding your statement - 'A subset of Azure user login events are ingested to the unified audit log' - where can I find reference to it in the documentation? 

In addition, I also had few times that login events appeared in the unified audit log but not in Azure Sign-ins log. Any idea why? 
I can provide examples if needed.
