### ISSUE TITLE
1

### ISSUE THREAD

**Issue by RengarLearnToCode** [MicrosoftDocs/microsoft-365-docs#12566]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 258b2648-c412-8f1a-6909-bd2fed576d46
* Version Independent ID: 258b2648-c412-8f1a-6909-bd2fed576d46
* Content: [Microsoft Defender Threat Intelligence in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/defender-threat-intelligence?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/defender-threat-intelligence.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/defender-threat-intelligence.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@RengarLearnToCode What is your feedback. Please share.
