### ISSUE TITLE
Microsoft Privacy & online safety page URL and Sign in URL not working.

### ISSUE THREAD

**Issue by ThatSatsuma889** [MicrosoftDocs/microsoft-365-docs#12563]
I wanted to change my settings for Privacy & online safety, but after I click on that category I get hit with this message. "We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available." I also tried signing in on the Xbox settings page where the Privacy & online safety category is, but I get hit with the same message.
![2023-07-30 12_30_52-Window](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/89546818/10bb3803-3ce6-4296-b957-8050b6a6309c)
![2023-07-30 12_30_52-Window](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/89546818/66b36122-59ae-4a50-ae8e-61bbaf3d0ddb)
![2023-07-30 12_31_17-Window](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/89546818/44a4e3d8-bfcd-468f-b037-7d59fb5fab91)
Can anyone help?

**Comment by ThatSatsuma889** [comment]
(I posted the same image by mistake, my bad.)

**Comment by yogkumgit** [comment]
@ThatSatsuma889 Please indicate which document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@ThatSatsuma889 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
