### ISSUE TITLE
Line#10 Exchange Online Protection hyper link is dead (404)

### ISSUE THREAD

**Issue by Amartya-Karan** [MicrosoftDocs/microsoft-365-docs#1256]
Line#10 Exchange Online Protection hyperlink is dead (404) . Please correct the hyperlink 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad38c0e5-d4fa-e34f-fd58-b3a4a07e5276
* Version Independent ID: e55c6ee7-87f4-7ce4-6e25-655a0a36ce44
* Content: [Set up your EOP service - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-your-eop-service#what-do-you-need-to-know-before-you-begin)
* Content Source: [microsoft-365/security/office-365-security/set-up-your-eop-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-your-eop-service.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by joinimran** [comment]
@Amartya-Karan Can you please check at your end. All of the links mention in the document are working fine.  There is no broken link on the page. 

Thanks.

**Comment by Amartya-Karan** [comment]
Now the link is working, That time it was coming with 404 . Thanks for fixing
