### ISSUE TITLE
MSERT.EXE - Shows infected files but does not provide for cleaning once scan completed

### ISSUE THREAD

**Issue by LJFLAT** [MicrosoftDocs/microsoft-365-docs#12565]
I have ran the MSERT.EXE tool twice over the weekend and now this morning. It is coming up with infected files but when it completes, says there were no infected files found.

Is this right?

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/28922631/a2335eb7-744e-496e-b031-f3216bcf0126)

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/28922631/7acec3dd-5f05-455a-bd1c-b1b23a4f97fa)

**Comment by denisebmsft** [comment]
Hello @LJFLAT. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team.

**Comment by LJFLAT** [comment]
Sorry about that... Here is the link

https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/safety-scanner-download?view=o365-worldwide

Cheers

**Comment by msbemba** [comment]
@LJFLAT Thank you for your feedback. This does not sound right and looks like a technical issue or bug, I'd recommend reaching our to the support team via the need help section on the admin center, so that our support engineers can assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LJFLAT Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
