### ISSUE TITLE
wrong object type specified in Shared mailbox description

### ISSUE THREAD

**Issue by john-r-hobbs** [MicrosoftDocs/microsoft-365-docs#12571]
Under "Shared Mailbox" it says, "Users with permissions to the **group mailbox** can send as or send on behalf of the mailbox email address, if the administrator has given that user permissions to do that."
 
"Group mailbox" in this sentence should say "Shared Mailbox"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare types of groups in Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **microsoft-365-business**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@john-r-hobbs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12590

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @john-r-hobbs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
