### ISSUE TITLE
There is no product called: Microsoft Defender for Office 365 E5

### ISSUE THREAD

**Issue by scottyv** [MicrosoftDocs/microsoft-365-docs#12574]
The licensing requirements listed is very confusing.  There is no product called: Microsoft Defender for Office 365 E5.  It should say: Microsoft Office 365 E5.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge in Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge?view=o365-worldwide#zero-hour-auto-purge-zap-in-microsoft-teams)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@scottyv, fixed per linked pull request.

Thanks for the feedback.

Closing.
