### ISSUE TITLE
Page claims you can use the MSAL.PS PowerShell module to get an MDE API token, but this is not true.

### ISSUE THREAD

**Issue by Chris1WK** [MicrosoftDocs/microsoft-365-docs#12573]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb191c54-e48e-c031-5310-e2fd584dc412
* Version Independent ID: 201b65d3-a983-8746-3e02-631e5c77a792
* Content: [Create an app to access Microsoft 365 Defender APIs on behalf of a user](https://learn.microsoft.com/en-us/microsoft-365/security/defender/api-create-app-user-context?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/api-create-app-user-context.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/api-create-app-user-context.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by Chris1WK** [comment]
I posted a similar question to the MSAL.PS github page and found that you CAN do this, but you need to specify the full scope, IE "https://api.securitycenter.windows.com/AdvancedQuery.Read".  The example shows a call to get an MSGraph token.

**Comment by msbemba** [comment]
@Chris1WK Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12593

Once the author approves, the changes will be live.

Thanks
Sri
