### ISSUE TITLE
Get-AzureADDirectorySettingTemplate -Id 62375ab9-6b52-47ed-826b-58e47e0e304b Errors

### ISSUE THREAD

**Issue by bloodytourists** [MicrosoftDocs/microsoft-365-docs#1257]
I have had to change the above query as it no longer recognises -Id as a parameter. The command I used to overcome this is:

$template = Get-AzureADDirectorySettingTemplate | where -Property Id -Value "62375ab9-6b52-47ed-826b-58e47e0e304b" -EQ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **krowley**

**Comment by cabailey** [comment]
@bloodytourists  Thanks for letting us know about this.  We're in the process of revising this article to remove Azure AD instructions and instead point to the Azure AD documentation where they will know about their changes.

**Comment by mypil** [comment]
@bloodytourists - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author cabailey so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by cabailey** [comment]
@bloodytourists This article is now republished without the Azure AD instructions, and instead, link off to the Aure AD documentation where they have updated the syntax.
