### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by jgre333** [MicrosoftDocs/microsoft-365-docs#12577]
You have a typo under how to use for targeted release. It says "Selece Settings" instead of "Select Settings"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a1d99c0b-11d7-7375-79c3-c18b320d3fc3
* Version Independent ID: 79a0f634-d6c1-b3b1-9594-89710359e146
* Content: [Stay on top of changes - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/stay-on-top-of-updates?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/stay-on-top-of-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/stay-on-top-of-updates.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jgre333 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12595

Once the author approves, the changes will be live.

Thanks
Sri
