### ISSUE TITLE
role clarification

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/microsoft-365-docs#12575]
[Enter feedback here]
Can you clarify if Service Support admin includes Message center privacy reader and/or Message center reader, given Service Support includes "View and share message center posts". Is a Message center post the same thing as a notification? Thank you,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@giterdn Thank you for your feedback. No, it is not the same as notification, however, they can Set email preferences to receive a weekly digest of all messages, emails for major updates only, and emails for data privacy messages etc.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @giterdn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
