### ISSUE TITLE
Configure inbound and outbound settings sections say the same thing

### ISSUE THREAD

**Issue by mikevasiloff** [MicrosoftDocs/microsoft-365-docs#12588]
The "Configure outbound settings for the organization" section currently says the same thing as the "inbound settings" section:
`Use the outbound settings to specify which users or groups from the external organization can access resources in your organization.`

I think it should instead say something like this:
`Use the outbound settings to specify which users or groups from **your organization** can access resources in **the external** organization.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2341de0-ff6d-99fe-d7f5-19e70be3efef
* Version Independent ID: c2341de0-ff6d-99fe-d7f5-19e70be3efef
* Content: [Collaborate with guests from other Microsoft 365 cloud environments (Preview)](https://learn.microsoft.com/en-us/microsoft-365/solutions/collaborate-guests-cross-cloud?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-guests-cross-cloud.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-guests-cross-cloud.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Submitted a fix.
