### ISSUE TITLE
Security Adminsitrator role group definition 

### ISSUE THREAD

**Issue by tolarianNZ** [MicrosoftDocs/microsoft-365-docs#12586]
It appears this role group may be missing the fact it includes the ability to manage the Information Protection Scanner.  Official scanner docs refer to other roles, however this role permits it too.

I am unable to post equal feedback on this page <https://learn.microsoft.com/purview/deploy-scanner-configure-install?tabs=azure-portal-only#configure-the-scanner-settings> but there is no Feedback button.

It does not include Security Administrator as a role that can manage Information Protection Scanner, I began this journey because the 3 Compliance/Org mgmt roles specified in the URL above are very permissive, and have realised Security Admin allows it.  

Can you please tag the right group to update that could update that, in lieu of a Feedback button that page too?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Roles and role groups in Microsoft Defender for Office 365 and Microsoft Purview compliance](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/scc-permissions?view=o365-worldwide&toc=%2Fmicrosoft-365%2Fcompliance%2Ftoc.json&bc=%2Fmicrosoft-365%2Fbreadcrumb%2Ftoc.json)
* Content Source: [microsoft-365/security/office-365-security/scc-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/scc-permissions.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@tolarianNZ, I confirmed that the Security Administrator role group in Defender for Office 365 (security and Purview compliance (compliance) contains the following roles:

- Audit Logs
- Compliance Manager Administration
- Device Management
- DLP Compliance Management
- IB Compliance Management
- Manage Alerts
- Quarantine
- Security Administrator
- Sensitivity Label Administrator
- Tag Contributor
- Tag Manager
- Tag Reader
- View-Only Audit Logs
- View-Only Device Management
- View-Only DLP Compliance Management
- View-Only IB Compliance Management
- View-Only Manage Alerts

The only role that was missing from the article was Tag Contributor, which I added.

I requested an update to the Purview article you mentioned to add Security Administrator to that bulleted list of role groups. I have no power to approve/merge pull requests in that repo.

OK?

**Comment by tolarianNZ** [comment]
Hi, appreciate the response Chris.

None of the roles in that list you provide grant access to the Purview
Information Protection Scanner - I feel like like the Security
Administrator role group contains a role that is still missing from the
list, that grants access to the Scanner.

I don't believe a Role Group should grant rights *outside of *the roles
defined within a Role Group, unless I am mistaken there and apologies if so
no further action required.


Regards,
Ryan

**Comment by chrisda** [comment]
@tolarianNZ, if we're talking about Security Administrator in Security/Compliance, the roles listed should be the Security/Compliance roles that are assigned.

If we're talking about the Azure AD role named Security Administrator, there likely are many other roles/permissions assigned.

Thanks for the feedback.

Closing
