### ISSUE TITLE
Need to add Power BI/Fabric to in scope service

### ISSUE THREAD

**Issue by sergeigms** [MicrosoftDocs/microsoft-365-docs#12580]
[Enter feedback here]
Power BI should be in scope for ABT. Can we please confirm and update the doc? It is important compliance feature in HSL and a requirements for most FSIs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Version Independent ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Content: [Idle session timeout for Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/idle-session-timeout-web-apps?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/idle-session-timeout-web-apps.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by ByBrianGoodman** [comment]
@sergeigms  - Microsoft Fabric has been added to document. Will be live after PR is approved.

**Comment by msbemba** [comment]
PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12584

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sergeigms Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
