### ISSUE TITLE
30 minutes to 24 hours is no longer accurate (time for records to show up in logs)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#1258]
I officially have spotted at least 1 audited activity which took ~53 hours to show up in the log.  It was for the operation Set-InboxRule (workload = Exchange) which we use for O365 Alerts.  Is the information on this page out of date / inaccurate or would that be considered an issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#frequently-asked-questions)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@JeremyTBradshaw Nothing has changed in terms of the 30-minute SLA for when Exchange activities are searchable in the unified audit log. So this sounds like an issue. Would suggest you contact Microsoft Support if this continues.
