### ISSUE TITLE
Unclarity in configuration

### ISSUE THREAD

**Issue by heggholmen** [MicrosoftDocs/microsoft-365-docs#12598]
In the section "Configure Supervised Mode via Microsoft Intune / App configuration policy / 3. In the next screen, select Use configuration designer as the format. Specify the following properties:" there is some unclarity.

In the text it stats; "Configuration Value: true" but in the screenshot it shows "Configuration Value:{{issupervised}}"
The screenshot is the correct setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [Deploy Microsoft Defender for Endpoint on iOS with Microsoft Intune](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@heggholmen Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12620

Once the author approves, the changes will be live.

Thanks
Sri
