### ISSUE TITLE
The code sample was added but was incorrect for Registering the mandatoryRetentionPeriodEnabled feature:

### ISSUE THREAD

**Issue by andypituch** [MicrosoftDocs/microsoft-365-docs#1259]
The code sample was added but was incorrect for Registering the mandatoryRetentionPeriodEnabled feature:

`-ProviderNamespace Microsoft.KeyVault`   should be  `-ProviderNamespace Microsoft.Resources`

I don't know if i should open a new issue or just have this re-updated

_Originally posted by @andywahr in https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1214#issuecomment-587155268_

**Comment by robmazz** [comment]
@andypituch - thanks for the feedback, can you clarify which topic you are referring to with this request?

**Comment by andypituch** [comment]
See https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1214#issuecomment-587155268 for details.

Doc with issue is Step #2: https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up#register-azure-subscriptions-to-use-a-mandatory-retention-period

**Comment by msbemba** [comment]
@andypituch Thank you for your feedback. We have made the changes via PR # https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2212

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andypituch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
