### ISSUE TITLE
Missing RSS feed for "What's new in Microsoft Defender for Office 365"

### ISSUE THREAD

**Issue by itsgaryk** [MicrosoftDocs/microsoft-365-docs#12608]
I'm unable to find an RSS feed of the following page:
https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/defender-for-office-365-whats-new?view=o365-worldwide
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/defender-for-office-365-whats-new.md

Done the following triage:
- The page does not contain a link
- No "rss" in page source
- Previous versions of the pages on Github do not have the link
- Tried to manually create the RSS URL by copying the format of others e.g. https://aka.ms/mdo/rss
- Used RSS checker websites

Please can Microsoft investigate and resolve. Thank you

**Comment by chrisda** [comment]
@itsgaryk, I don't think that article ever had an RSS feed.
