### ISSUE TITLE
portal.rooms.microsoft.com is not included in this page or the JSON file

### ISSUE THREAD

**Issue by cypheredout** [MicrosoftDocs/microsoft-365-docs#12609]
Doing a dig on portal.rooms.microsoft.com points to mmrprodglobfeweb.azurewebsites.net which points to the response of 40.112.243.2 --> it is part of this network subnet 40.112.128.0/17 which is documented in the Azure Datacenter IP's (https://www.microsoft.com/en-us/download/details.aspx?id=56519) doc.  We need it added to the Json and also to the page that is a optional requirement.

; <<>> DiG 9.18.17 <<>> portal.rooms.microsoft.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51350
;; flags: qr rd ad; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

 

;; QUESTION SECTION:
;portal.rooms.microsoft.com.    IN      A

 

;; ANSWER SECTION:
portal.rooms.microsoft.com. 0   IN      CNAME   mmrprodglobfeweb.azurewebsites.net.
mmrprodglobfeweb.azurewebsites.net. 0 IN CNAME  waws-prod-bay-129.sip.azurewebsites.windows.net.
waws-prod-bay-129.sip.azurewebsites.windows.net. 0 IN CNAME waws-prod-bay-129.westus.cloudapp.azure.com.
waws-prod-bay-129.westus.cloudapp.azure.com. 0 IN A 40.112.243.2

 

 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by tiburd** [comment]
We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).
