### ISSUE TITLE
Support for AlmaLinux (CentOS is reaching EoL)

### ISSUE THREAD

**Issue by sebanism** [MicrosoftDocs/microsoft-365-docs#12617]
CentOS 7 and 8 are reaching end of life, AlmaLinux is one of just a few notable drop-in replacements, however it is not yet supported by MDE, nor does there appear to be a timeline. We have already begun migrating our servers from CentOS, as have a number of clients. MDE is the only agent we use that has not yet caught up and started supporting AlmaLinux.

**Comment by denisebmsft** [comment]
Hello @sebanism. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team.

**Comment by yogkumgit** [comment]
@sebanism We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
