### ISSUE TITLE
Link to Group Owner instructions, group owner action is a required followup to this page

### ISSUE THREAD

**Issue by e5z8652** [MicrosoftDocs/microsoft-365-docs#12613]
"Once this is enabled, Group owners can provide group members with the ability to create folders, rename folders, copy, move and delete messages. Group level member permission is handled by Group owners."

A documentation link for group owners would be great, as the process for granting user permissions is not immediately apparent within the web UI, and many of our group owners are non-technical.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62ab7809-9202-5fce-7b0a-ff090a920ce5
* Version Independent ID: 62ab7809-9202-5fce-7b0a-ff090a920ce5
* Content: [Manage Folders and Rules feature in Microsoft 365 Groups - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/manage-folders-and-rules-feature?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/manage-folders-and-rules-feature.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-folders-and-rules-feature.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@e5z8652 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12619

Once the author approves, the changes will be live.

Thanks
Sri
