### ISSUE TITLE
Automatically free up licenses

### ISSUE THREAD

**Issue by INC02203** [MicrosoftDocs/microsoft-365-docs#12629]
[Manage auto-claim policies ](https://learn.microsoft.com/en-us/microsoft-365/commerce/licenses/manage-auto-claim-policies?view=o365-worldwide): 
If a user who claimed license under auto claim policy has not accessed application for a certain period, will the license be released back to the pool of licenses? If yes, what is the time period and is it configurable?

**Comment by yogkumgit** [comment]
Hello @INC02203 . Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team.

**Comment by msbemba** [comment]
@INC02203 Thank you for your feedback. In the case if a user who claimed a license under auto claim policy has not accessed the application for a certain period or for any amount of time, the licenses do not get released.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @INC02203 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
