### ISSUE TITLE
No mention of what happens when the time is up

### ISSUE THREAD

**Issue by Paplewska** [MicrosoftDocs/microsoft-365-docs#12621]
[Enter feedback here]

The document tells you how to approve or reject investigations, but investigations have a timeframe for approval. What happens if it is not approved in time? Do they get rejected?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75038ca4-5640-5792-4dd9-0baeedb9ad29
* Version Independent ID: f87ee7c8-1869-295a-6d65-079681545baf
* Content: [Review and manage remediation actions in Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Paplewska Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12646

Once the author approves, the changes will be live.

Thanks
Sri
