### ISSUE TITLE
Configure Supervised Mode has wrong setting in text

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/microsoft-365-docs#12622]
In Configure Supervised Mode via Intune, step 3 has an incorrect setting.

In the next screen, select Use configuration designer as the format. Specify the following properties:

Configuration Key: issupervised
Value type: String
Configuration Value: true

The Configuration Value should be {{issupervised}} according to the image of the setting below the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [Deploy Microsoft Defender for Endpoint on iOS with Microsoft Intune](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MarcLaf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12648

Once the author approves, the changes will be live.

Thanks
Sri
