### ISSUE TITLE
550 5.7.703 Your message can't be delivered

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#12627]
The following line of the article is incorrect: "The entire message is blocked for all internal and external recipients of the message, even if only one recipient email address or domain is defined in a block entry."
This is not the case. Only external recipients are blocked while any other internal recipients that were in the to or cc fields will receive the email. Please update the article or verify what the expected behaviour should be. Thanks!
https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-about#block-entries-in-the-tenant-allowblock-list

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbb3daf4-fa28-88d9-4543-89d8ff5ead5d
* Version Independent ID: bbb3daf4-fa28-88d9-4543-89d8ff5ead5d
* Content: [Manage allows and blocks in the Tenant Allow/Block List](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list-about?view=o365-worldwide#block-entries-in-the-tenant-allowblock-list)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@JeroenDronkers, I'm told the fixes that will make that incorrect statement correct will be rolled out soon.

**Comment by JeroenDronkers** [comment]
Thanks Chris!


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
***@***.******@***.***>

[abc]
﻿
Team Manager | Frances Early ***@***.******@***.***>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center

**Comment by chrisda** [comment]
OK. Thanks for the feedback.

Closing
