### ISSUE TITLE
Syntex Site Templates Not Available for pay-as-you-go Billing

### ISSUE THREAD

**Issue by gcwedc** [MicrosoftDocs/microsoft-365-docs#12634]
The documentation references available SharePoint site templates , but notes: 

"Note: You must be a licensed Syntex user to view and apply this site template. " 

[https://support.microsoft.com/en-us/office/use-the-contracts-management-team-site-template-powered-by-microsoft-syntex-80820115-c700-4a62-bb59-69b33c8e3b4f](url)

However, per-user licensing is not available after July 1st, : 

Note

As of July 1, 2023, per-user licenses are no longer available for purchase. You will need to [set up pay-as-you-go billing](https://learn.microsoft.com/en-us/microsoft-365/syntex/syntex-azure-billing).

Per-user licenses purchased before July 1 can still be assigned to new users. After existing per-user licenses expire, you will need to opt-in to Syntex [pay-as-you-go billing](https://learn.microsoft.com/en-us/microsoft-365/syntex/syntex-azure-billing).

[https://learn.microsoft.com/en-us/microsoft-365/syntex/set-up-content-understanding](url)

So, we are not able to create Microsoft Syntex site templates. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2800df8-5dc8-19b2-e168-01e3621e1e38
* Version Independent ID: c2800df8-5dc8-19b2-e168-01e3621e1e38
* Content: [Accelerate your solution using site templates for Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/site-templates)
* Content Source: [microsoft-365/syntex/site-templates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/site-templates.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@gcwedc -- Thank you for calling this out. Let me look into it and get back to you. Thanks again for the feedback.
