### ISSUE TITLE
Offboard Machine API Hasn't Removed Device

### ISSUE THREAD

**Issue by nathanielhoh** [MicrosoftDocs/microsoft-365-docs#12638]
We recently became aware of a random device enrolled in our of clients tenant M365 Defender, the device in question is not managed by us and the client cannot identify the device.

As we have no way to connect to the device we could not run the offboarding script.

We have attempted to use the [Machine Offboard API](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/offboard-machine-api?view=o365-worldwide) to remove the device. Instead of receiving the expected Status 200 we received Status 201 Created with the below response:

> {
>     "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#MachineActions/$entity",
>     "id": "cd46c651-f570-4e32-abdb-a02a9e022a92",
>     "type": "Offboard",
>     "title": null,
>     "requestor": "Customer App",
>     "requestorComment": "Offboard machine by postman",
>     "status": "Pending",
>     "machineId": "d95f8b657a36ced22147cb7b54802152caa29247",
>     "computerDnsName": "desktop-5o2hkn5",
>     "creationDateTimeUtc": "2023-08-08T01:34:32.1341831Z",
>     "lastUpdateDateTimeUtc": "2023-08-08T01:34:32.1341838Z",
>     "cancellationRequestor": null,
>     "cancellationComment": null,
>     "cancellationDateTimeUtc": null,
>     "errorHResult": 0,
>     "scope": null,
>     "externalId": null,
>     "requestSource": "PublicApi",
>     "relatedFileInfo": null,
>     "commands": [],
>     "troubleshootInfo": null
> }

Since then in Security Center the device activity has not updated, and the monitor status is now inactive, however the device still shows as being onboarded and has not been removed:
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/139199171/a2d0b161-6aa8-46f1-9336-a10e748e6a26)

Does anyone know how we can force this device to be fully removed?

**Comment by msbemba** [comment]
@nathanielhoh Thank you for your feedback. This looks like a technical issue and I'd recommend contacting support via the need help section on the admin center so that our Support engineers can help you fix this.

Hope this helps!

Thanks
Sri

**Comment by nathanielhoh** [comment]
Hi Sri will do, given the fact that I didn't receive the expected status code as per the current documentation for the Machine Offboard API, is the current documentation correct as it lists this as the expected response:
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/139199171/e97ab98b-d43c-4845-acd3-a49c0708137a)
Or is the response I had received fine?

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @nathanielhoh Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by nathanielhoh** [comment]
Hi All just an update in case anyone else runs into this: 

I've done some digging and found that this appears to be expected behavior when a device is offboarded.

Once a device is offboarded it may take up to 7 days for the device to be set as inactive, at this point the device will remain in the Device List until the Retention Period expires https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/offboard-machines?view=o365-worldwide

From what I can tell the retention period is 180 days as per https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/data-storage-privacy?view=o365-worldwide#how-long-will-microsoft-store-my-data-what-is-microsofts-data-retention-policy)

Would be good if the Offboard machine API page was updated with this information.
