### ISSUE TITLE
Prerequisites to properly access Data Classification Preview

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#1263]
Please make sure that you update the documentation properly and include the following details:

- specific license required to be assigned on the user accessing the Data Classification (Preview) - should be Enterprise E5

- specific admin roles required for the user - should be one of the following: Global Administrator, Compliance Administrator or Compliance Data Administrator; the last 2 should be assigned on protection.office.com under Permissions area and also on Azure AD, on the user assigned roles (most likely this should be in sync and should require assignment only in 1 place, either in AAD or in protection.office.com)

- clarify exactly what "M365 Administrator" means, as it can be any type of admin here, but this doesn't necessarily mean that it is the correct type of admin needed to access the feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37494e01-d673-2fcb-4a86-baecb716120e
* Version Independent ID: 1f46b90e-3691-5b81-9f9e-ce3c94f18a1d
* Content: [Get started with data classification (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-overview#feedback)
* Content Source: [microsoft-365/compliance/data-classification-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Alex-Catalin  Thank you for the feedback, We have added the prerequisites to the document via PR #https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1314

Thanks
Sri
