### ISSUE TITLE
Why are they including Members in a Guest Setup

### ISSUE THREAD

**Issue by vpmih** [MicrosoftDocs/microsoft-365-docs#12647]
If this page is to create a secure GUEST environment, why is it including MEMBERS in the setup?

6. "In the dropdown, select B2B collaboration guest users and B2B collaboration member users."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a more secure guest sharing environment](https://learn.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@vpmih it's possible to [change a guest's user type to member](https://learn.microsoft.com/azure/active-directory/external-identities/user-properties#can-azure-ad-b2b-users-be-added-as-members-instead-of-guests). This covers that scenario. You can just select B2B collaboration guest users if your guests all have a user type of guest.

**Comment by yogkumgit** [comment]
@vpmih Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
