### ISSUE TITLE
Prerequisites to properly access Data Classification Preview

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#1264]
Please make sure that you update the documentation properly and include the following details:

- specific license required to be assigned on the user accessing the Data Classification (Preview) - should be Enterprise E5

- specific admin roles required for the user - should be one of the following: Global Administrator, Compliance Administrator or Compliance Data Administrator; the last 2 should be assigned on protection.office.com under Permissions area and also on Azure AD, on the user assigned roles (most likely this should be in sync and should require assignment only in 1 place, either in AAD or in protection.office.com)

- aside from the above requirements, "Content Explorer List viewer" and/or "Content Explorer Content viewer" roles are required additionally to access the features described on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334e743d-c929-c74a-c996-2b8e0b68a46b
* Version Independent ID: 91c4563c-72c1-4655-72f7-d467b6098540
* Content: [Using data classification content explorer (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer)
* Content Source: [microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-content-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Alex-Catalin  Thank you for your feedback. We have added the prerequisites to this document via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1313

Meanwhile, we have added the Content Explorer List viewer and Content Explorer Content viewer permissions to the document and necessary admin roles.

Thanks
Sri

**Comment by lmarianko** [comment]
Does this work in GCC tenants?  I don't see the permission you mention nor the content explorer view.  Tx.

**Comment by msbemba** [comment]
@lmarianko Commercial Office 365 tenants should see this preview functionality, but there's no news when it might be available for GCC tenants.

Thanks
Sri
