### ISSUE TITLE
 Windows Defender Antivirus

### ISSUE THREAD

**Issue by DJILALI02HADI** [MicrosoftDocs/microsoft-365-docs#12654]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30fc8e9f-ad24-1453-d0c8-85ff73910c79
* Version Independent ID: 7a6d0aae-8a3e-b6fc-cb13-e0a30b7b76df
* Content: [Microsoft Defender Antivirus in the Windows Security app](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @DJILALI02HADI. Do you have feedback or a question for us? It didn't come through. Please let us know if there's an issue with documentation. Thank you!
