### ISSUE TITLE
About Debian 12 support

### ISSUE THREAD

**Issue by narkuroki** [MicrosoftDocs/microsoft-365-docs#12659]
[Enter feedback here]
Please correct the description of "System requirements"
Please correct the following statements.

━━━━━━━━━━━━━━━━━━━━
Debian 9 or higher
━━━━━━━━━━━━━━━━━━━━

Please correct as follows.

Current statement:
Debian 9 or higher

Correct:
Debian 9-11

Why it needs to be fixed:
I have confirmed in the Microsoft Defender for Endpoint Discussion (msde@microsoft.com) that the mdatp package for Debian 12 is unreleased.
The current description reads that Debian 12 also supports MDE on Linux, but in fact it does not because the mdatp package has not been released.
Here is the thread for reference:

Re: MDATP binaries missing for Debian 12
==========
We have a tracking item for this - Deliverable 45712965: MDATP support for Debian-12
Supporting MDE on Debian-12  is on our roadmap. The MDE bits under Debian-12  will be available from September
==========

RE: Error in installing MDE on Debian 12
==========
Take a look at this ICM: https://portal.microsofticm.com/imp/v3/incidents/incident/413442694/summary
MDATP is not released in Debian 12 yet, this is planned to be delivered in the august release which can be expected to reach customer around mid of September.
==========

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide#system-requirements)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by narkuroki** [comment]
@yogkumgit 
Any progress on this matter?

**Comment by msbemba** [comment]
@narkuroki Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12696

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by narkuroki** [comment]
@msbemba 
The documentation doesn't seem to reflect the fix yet.
It looks like it's been approved already, when will the fix go into effect?

**Comment by msbemba** [comment]
@narkuroki Yes, we are waiting for the author to merge the PR. This will happen shortly.

Thanks
Sri

**Comment by narkuroki** [comment]
@msbemba 
The document has not been modified yet.
When will this change?

**Comment by msbemba** [comment]
We are waiting for the author to approve and merge. Please standby.

Thanks
Sri
