### ISSUE TITLE
Instructions do not match user experience

### ISSUE THREAD

**Issue by vemaloy** [MicrosoftDocs/microsoft-365-docs#12658]
The instructions on this page claims that information can be exported from Bookings in an xls format, yet the platform only is allowing a TSV export.  Please update either the instructions or (better) the platform so they match!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d6baff0-3819-e2b2-ea6d-b18c9bbdff1c
* Version Independent ID: 6a3e2522-a4a1-e2d5-61fb-f07d1b60cb00
* Content: [View Bookings calendar information](https://learn.microsoft.com/en-us/microsoft-365/bookings/reporting-info?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/reporting-info.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/reporting-info.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@vemaloy authors says - once you download the tsv file and open it, you can save it to xls format. Thanks.
