### ISSUE TITLE
Device Groups not present in Security Portal

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/microsoft-365-docs#12664]
In step 5 Set up your device groups, device collections, and organizational units, the second sub step says to navigate to **Settings > Endpoints > Permissions > Device groups.**

However in the Security Portal this location does not exist. I am unable to locate Device Groups anywhere. I am unable to determine whether this is the result of the portal changing or lacking the appropriate licenses (we have Business Premium).

The only place I can see that mentions Auto Remediation is under **Settings > Endpoints > Auto Remediation** however page does not give any options to create settings or groups.

Even the page at https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-groups?view=o365-worldwide mentions creating groups at the same location.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a0f4a32-b5d6-82b6-f42a-9664d9be8f5a
* Version Independent ID: e64468af-9eda-5fad-9d39-f837e70c1123
* Content: [Create and manage device groups in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-groups?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine-groups.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MarcLaf Thank you for your feedback. This looks like an issue with your tenant. 

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/adb4ae5a-0900-461c-bd84-2d93a16bd642)

I'd recommend contacting the support team via the need help section on the admin center, so that the support can assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MarcLaf Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MarcLaf** [comment]
I received a reply from MS Support. Even though Defender for Business includes features of Defender P1 and P2, the Device Group functionality discussed in the article is NOT included. Defender for Business Device Groups are managed in a separate place. The documentation that is pertinent to DfB is https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-create-edit-device-groups?view=o365-worldwide. Perhaps a note in this page could indicate that if you are on Defender for Business then to go to the other page for information on it?

**Comment by yogkumgit** [comment]
@MarcLaf Thanks

**Comment by yogkumgit** [comment]
@msbemba Please review and comment. Thanks

**Comment by msbemba** [comment]
@MarcLaf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12780

Once the author approves, the changes will be live.

Thanks
Sri
