### ISSUE TITLE
Please add a note to mention that EXO Plan 1 from Business Plans does not qualify for the multi-geo add-on

### ISSUE THREAD

**Issue by gabsto-ms** [MicrosoftDocs/microsoft-365-docs#12661]
[Hello, The licensing requirements are creating confusion for some customers. Specifically, the mention that Exchange Online Plan 1 qualifies for the multi-geo add-on has led some customers to believe incorrectly that Exchange Online Plan 1 included in Business Plans qualifies as well. We had a few cases on this subject and the customers' experience was impacted. It would help to avoid confusion and prevent such future cases if we added a note to clarify this. Please mention specifically that Exchange Online Plan 1 from the Business Plans does not qualify. Thank you.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32b41c7e-29cd-eb5b-36b2-738b3babd08f
* Version Independent ID: 22eda3f7-1c04-b3b0-95fd-3474b3f991b2
* Content: [Microsoft 365 Multi-Geo - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-multi-geo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-multi-geo.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@AnupamFrancis can you take a look?

**Comment by AnupamFrancis** [comment]
@briandaymsft Would you be able to help with this feedback on how Exchange Online Plans should be mentioned?

**Comment by gabsto-ms** [comment]
Hello @briandaymsft 
Sorry for disturbing you, I just wanted to check if this suggestion is being taken into consideration.
Thank you.

**Comment by briandaymsft** [comment]
@gabsto-ms , we're going to update the language to note SMB products are excluded but are working through the actual language.

**Comment by yogkumgit** [comment]
@briandaymsft Thank you very much for sharing this explanation. @gabsto-ms Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
