### ISSUE TITLE
What license is this available in?

### ISSUE THREAD

**Issue by devwheel** [MicrosoftDocs/microsoft-365-docs#1266]
E3 or E5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48819587-775e-ec94-d18b-cd68162b6ef3
* Version Independent ID: 1cb0dd4b-1ec4-fc4b-138a-c3d001281fcc
* Content: [Manage GDPR data subject requests with the DSR case tool in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/manage-gdpr-data-subject-requests-with-the-dsr-case-tool)
* Content Source: [microsoft-365/compliance/manage-gdpr-data-subject-requests-with-the-dsr-case-tool.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/manage-gdpr-data-subject-requests-with-the-dsr-case-tool.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@devwheel Both E3 and E5.
