### ISSUE TITLE
On Debian 12, the "Configure the Linux software repository" step gives an error.

### ISSUE THREAD

**Issue by narkuroki** [MicrosoftDocs/microsoft-365-docs#12660]
[Enter feedback here]
Areas that need fixing:
The following command for "Ubuntu and Debian systems" in "Configure the Linux software repository"

・Update the repository metadata:
   sudo apt-get update
  

Reasons to fix:
In Debian 12, apt-key is deprecated (obsolete), so public key authentication is not possible with the current documentation procedures.
As per the documentation, when I run the "sudo apt-get update" command, I get the following error:
━━━━━━━━━━━━━━━━━━━━
W: GPG error: https://packages.microsoft.com/debian/12/prod bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'https://packages.microsoft.com/debian/12/prod bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
━━━━━━━━━━━━━━━━━━━━

To avoid the above error, the Microsoft GPG public key "microsoft.gpg" installed with the following command must be placed as "/usr/share/keyrings/microsoft-prod.gpg".
By doing this, the "sudo apt-get update" command on Debian 12 will succeed.

Command:
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

Please add to the documentation that Debian 12 requires special work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by narkuroki** [comment]
@yogkumgit 
Any progress on this matter?

**Comment by narkuroki** [comment]
@msbemba 
The documentation doesn't seem to reflect the fix yet.
It looks like it's been approved already, when will the fix go into effect?

**Comment by narkuroki** [comment]
@msbemba 
I Checked https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12695.
Unfortunately, the command you're trying to fix fails on Debian 11 and below.
What I wanted in this request was to write instructions for both pre-Debian 11 and he for Debian 12.
It seems that my request was not conveyed correctly.
Could you please fix it again as below?

・Contents currently published in the document
━━━━━━━━━━━━━━━━━━━━
・Install the Microsoft GPG public key:
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
━━━━━━━━━━━━━━━━━━━━

・What you are currently trying to modify with "https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12695"
━━━━━━━━━━━━━━━━━━━━
・Install the Microsoft GPG public key:
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg  > /dev/null
━━━━━━━━━━━━━━━━━━━━

・Real content that you want to correct
━━━━━━━━━━━━━━━━━━━━
・Install the Microsoft GPG public key:

For Debian 11 and below, run the following command.
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

For Debian 12 and above, run the following command.
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg  > /dev/null
━━━━━━━━━━━━━━━━━━━━

**Comment by narkuroki** [comment]
@msbemba 
Could you please confirm this?

**Comment by narkuroki** [comment]
@msbemba 
A customer has requested an urgent fix for this issue.
Could you please confirm.

**Comment by msbemba** [comment]
@narkuroki  We are waiting for author to approve the changes. Will be live one the author approves.

**Comment by outdoorsman** [comment]
I was FINNNALLY able to get this working in Debian 12 via my Dockerfile. The last piece of the puzzle for me was using the path `/usr/share/keyrings/microsoft-prod.gpg` for Debian 12 and obviously no using `apt-key` since it's deprecated. Here's what I have now...

```
# MSSQL ODBC Driver
RUN mkdir -p /etc/apt/keyrings \
    # Add Microsoft key to keyring
    && curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft-prod.gpg \
    # Download appropriate package for the OS version (currently Debian 12)
    && curl -sSL https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    # Install ODBC Driver 18 for SQL Server (does not include SQLCMD)
    && apt-get install -y --no-install-recommends msodbcsql18 \
    # Optional 1: for bcp and sqlcmd
    && apt-get install -y --no-install-recommends mssql-tools18 \
    # Optional 1: export the connection string to set up the SQLCMD environment variable
    && echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc \
    # Optional 2: for unixODBC development headers
    && apt-get install -y unixodbc-dev \
    # Optional 2: kerberos library for debian-slim distributions
    && apt-get install -y libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt
```
