### ISSUE TITLE
Verbose page related to billing should answer the simplest case first.

### ISSUE THREAD

**Issue by sakoht** [MicrosoftDocs/microsoft-365-docs#12669]
This page answers 1000 questions, it seems.

But I came here b/c on the page that shows my invoices and payment methods, it was not obvious how to pay.

I don't want to read pages of documentation to send money for a bill.  I want a "Pay" button.  And I want it to take my money from the card I already put in, and pay the invoices shown.  I don't want to get a Ph.D. in your billing details.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82583c48-08e6-9acb-657b-ce1fe44e76a5
* Version Independent ID: cbdcf652-3a68-4fa3-9f3b-92c518e0b710
* Content: [Payment options for your Microsoft business subscription](https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription?view=o365-worldwide#pay-by-invoice-check-or-eft)
* Content Source: [microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@sakoht Thank you for your feedback. That is covered in this section https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription?view=o365-worldwide#what-if-i-have-an-outstanding-balance

If you personally added the payment method that has a past due amount, you can use Settle balance to make a payment.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sakoht Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
