### ISSUE TITLE
DNS TXT verification records 

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/microsoft-365-docs#12662]
Ummm do we just keep this record out there forever to show the rest of the world were using d365 for them to hack us?  Or can we remove this after verification?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9c6bbf8-c699-5317-5751-339dd499f8d7
* Version Independent ID: 20b3d64a-ef3e-da1f-a0b1-7bcb54acfeb2
* Content: [Connect your DNS records at Network Solutions to Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-network-solutions?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-network-solutions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-network-solutions.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by msbemba** [comment]
@SquirrelAssassin Thank you for your feedback. If you are referring to the TXT record, This record is used only to verify that you own your domain; it doesn't affect anything else. You can delete it later if you like.

The other records should not be deleted.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SquirrelAssassin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
