### ISSUE TITLE
On-premise should be on-premises

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/microsoft-365-docs#12665]
In Step 1, the architecture chart lists **On-Premise** as a type. This should be **On-premises**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e457d022-6b68-137b-5723-098c6d301af6
* Version Independent ID: df9dc070-ee8b-3cc5-8ea7-68dc2d5abb56
* Content: [Identify Defender for Endpoint architecture and deployment method](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deployment-strategy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/deployment-strategy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deployment-strategy.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@MarcLaf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12694

Once the author approves, the changes will be live.

Thanks
Sri
