### ISSUE TITLE
Purpose of offboarding process

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#12666]
I don't see the purpose of running the offboarding process.  If you have devices that are not to be used again, they will still show inactive after 7 days even if you don't run the offboarding process.  Data is still retained for the retention period as well and the device still shows up in the portal for 30 days no matter if you do offboarding or not.  In addition, if you reimage the device for redeployment, you'll still get a duplicate entry for the same workstation name in the portal (assuming you redeploy with same host name).  

So what, exactly, is the advantage/purpose of running the offboarding process?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bdead68-23ab-5e20-5f29-a356aea830be
* Version Independent ID: 4bdead68-23ab-5e20-5f29-a356aea830be
* Content: [Offboard a device from Microsoft Defender for Business](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-offboard-devices?view=o365-worldwide&tabs=Windows1011)
* Content Source: [microsoft-365/security/defender-business/mdb-offboard-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-offboard-devices.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @Canis-Lupis and thank you for posting your question here. I've thought about this and did a little research. Some companies prefer to offboard devices as part of good housekeeping practices or in cases where devices will be used again. In your scenario, where you're talking about devices you won't use again, you can choose to just let them go into an inactive state. Now once a device goes into an inactive state, it can be more difficult (if not impossible) to offboard it. I hope this helps!

**Comment by Canis-Lupis** [comment]
No, I'm referring to devices that will be used again.  Even with those, there doesn't appear to be any advantage to offboarding as the results are the same if you offboard or not; both show inactive after 7 days, both still create a new object in the database when the host is reimaged, and both still retain data for 30 days.  Offboarding doesn't actually do anything.
________________________________
