### ISSUE TITLE
Page should be top link in setup guide

### ISSUE THREAD

**Issue by Doune9** [MicrosoftDocs/microsoft-365-docs#12677]
I've finally found this page several months too late having worked it all out for myself. It would have saved a lot of grief if it had been front and centre of the setup guidance in the Admin Centre.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 854cbadf-a802-0782-5a3a-b839995ff7fd
* Version Independent ID: b511466a-2505-4e90-548c-3fa5b6f2aedc
* Content: [Gather the information you need to create DNS records - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/information-for-dns-records?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/information-for-dns-records.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by msbemba** [comment]
@Doune9 Thank you for your feedback. The change you are requesting is on the Admin center and that needs to be passed on directly to our Product team. You can do so by providing your feedback directly on our main feedback portal (https://feedbackportal.microsoft.com/)

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.
