### ISSUE TITLE
Powershell authentication incorrect

### ISSUE THREAD

**Issue by jishua9** [MicrosoftDocs/microsoft-365-docs#12679]
The example for powershell authentication has the incorrection parameters in the authentication body $authBody

Is says "source = "$sourceAppIdUri"
However it will not work with "source", this should be "scope" for it to work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a700a4e-82ff-29ce-1b68-247de33652db
* Version Independent ID: bff8c6c3-eb28-1846-c711-36a7c67167aa
* Content: [Create an app to access Microsoft Defender for Endpoint without a user](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-create-app-webapp?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/exposed-apis-create-app-webapp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/exposed-apis-create-app-webapp.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jishua9 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12744

Once the author approves, the changes will be live.

Thanks
Sri
