### ISSUE TITLE
Tamper Protection enabled through the security portal (Security.microsoft.com) requires MAPs connections to be working on endpoint in order for Tamper protection settings to reach the endpoint from the portal.

### ISSUE THREAD

**Issue by Wzobac** [MicrosoftDocs/microsoft-365-docs#12676]
Tamper Protection enabled through the security portal (Security.microsoft.com) requires MAPs connections to be working on endpoint in order for Tamper protection settings to reach the endpoint from the portal.

Please add this to the FAQ.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7e4fb05-0172-f24b-9b47-ca6e85db2001
* Version Independent ID: b7e4fb05-0172-f24b-9b47-ca6e85db2001
* Content: [Frequently asked questions (FAQs) on tamper protection](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/faqs-on-tamper-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/faqs-on-tamper-protection.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/faqs-on-tamper-protection.yml)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Confirming with product team and when I get their OK I will add it.

**Comment by denisebmsft** [comment]
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/faqs-on-tamper-protection?view=o365-worldwide#what-s-required-for-tamper-protection-to-reach-devices-when-it-s-enabled-in-the-microsoft-365-defender-portal-
