### ISSUE TITLE
Customer Story link points to a page that does not exist

### ISSUE THREAD

**Issue by amback00** [MicrosoftDocs/microsoft-365-docs#1267]
The link provided under the "Microsoft and HIPAA and the HITECH Act" section points to a page that does not exist. Here is the text from the paragraph: "Learn about the benefits of HIPAA and the HITECH on the Microsoft Cloud: Read the Zwanger — Pesiri Radiology Customer Story"

Here is the link that is incorrect: https://customers.microsoft.com/story/radiology-clinics-ease-compliance-drive-innovation-with-cloud-based-data-network

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545aa0d-ba68-3113-413b-0c0b176b08bd
* Version Independent ID: bb2ce8e1-7f40-e5ed-60c4-f8bb0912661d
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-hipaa-hitech#feedback)
* Content Source: [microsoft-365/compliance/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@amback00 - thanks for the feedback, the link has been updated and now points to the main Microsoft Customer Stories (https://customers.microsoft.com) website. Please filter by HIPAA or HITECH for applicable stories. Thanks!
