### ISSUE TITLE
Quarantine is available in Microsoft 365 operated by 21Vianet.

### ISSUE THREAD

**Issue by jinhan2023** [MicrosoftDocs/microsoft-365-docs#12684]
In the Quarantined messages FAQ document, 
https://learn.microsoft.com/microsoft-365/security/office-365-security/quarantine-faq
it says "Quarantine isn't available in Microsoft 365 operated by 21Vianet." which is wrong. Please remove it.

**Comment by chrisda** [comment]
@jinhan2023, it said that in several different places. I removed that statement everywhere.

Thanks for the feedback.

Closing
