### ISSUE TITLE
Defining Credit Card format as 16 digits is incorrect

### ISSUE THREAD

**Issue by AveryBaker** [MicrosoftDocs/microsoft-365-docs#1268]
This sentence is misleading because Credit Card Numbers are not always 16 digits.

"16 digits which can be formatted or unformatted (dddddddddddddddd) and must pass the Luhn test."

This may make people think DLP cannot detect credit card numbers that are not 16 digits long, however I validated with testing 14 and 15 digit card numbers those scenarios are covered as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [What the sensitive information types look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for)
* Content Source: [microsoft-365/compliance/what-the-sensitive-information-types-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@AveryBaker Thank you for your feedback. We have made the changes to the doc via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1300

Thanks
Sri

**Comment by chrfox** [comment]
Hi @AveryBaker 
Thanks for your comment, it has been addressed in the document and published
