### ISSUE TITLE
Old eciar link

### ISSUE THREAD

**Issue by BlakeMsft** [MicrosoftDocs/microsoft-365-docs#12691]
Links need to be updated

**OLD**
curl -o test.txt https://www.eicar.org/download/eicar.com.txt

**NEW**
curl -o test.txt https://secure.eicar.org/eicar.com.txt

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6bcf39-9a8c-7fa3-803a-508e7b74cc9b
* Version Independent ID: 9fd6d652-df16-7f4b-d253-6aee2362f836
* Content: [Configure and validate exclusions for Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-exclusions?view=o365-worldwide#validate-exclusions-lists-with-the-eicar-test-file)
* Content Source: [microsoft-365/security/defender-endpoint/linux-exclusions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-exclusions.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Thank you @BlakeMsft. We have a work item in the queue for this.

**Comment by denisebmsft** [comment]
Resolved! https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/22052
