### ISSUE TITLE
GCC Roadmap?

### ISSUE THREAD

**Issue by chassold75** [MicrosoftDocs/microsoft-365-docs#1269]
We implemented this awhile back as a GCC, trained users, and it was working but functionality was removed without any notification.  It sounds like it was a compliance reason, which is fine but is this on the roadmap for GCC?  How do we know when it is turned back on? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in#feedback)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@chassold75 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback [[and feature requests]] on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
