### ISSUE TITLE
What happens to email that is sent during the period between license being disabled and renewed?

### ISSUE THREAD

**Issue by Meppyman** [MicrosoftDocs/microsoft-365-docs#12692]
I have this issue every year where my E3 licences expire within days of action pack renewal being available. It makes it very hard to time it to not have an outage.

It would be good if this page explained what happens to email sent to the mailboxes that have recently expired licences. Are they queued and eventually delivered? Do they bounce? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Meppyman Thank you for your feedback. Once your subscription expires, users have normal access to the Microsoft 365 portal, Microsoft 365 apps, and services such as email and SharePoint Online. This is the expired state and this lasts for 30 days. The bounce-back starts to happen in the disabled stage o.e after 30 days of subscription expiration.

Hope this helps!

Thanks
Sri

**Comment by Meppyman** [comment]
My emails started bouncing immediately, there was no 30 day period.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Meppyman Thank you for the response. This still looks like a billing issue and only the billing team can clarify what happened in your tenant. I'd recommend you contact support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Meppyman Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
