### ISSUE TITLE
Receiving "Access to the resource is forbidden"

### ISSUE THREAD

**Issue by msekkappan** [MicrosoftDocs/microsoft-365-docs#12706]
I have global and security administrator, however I am getting the error "Access to the resource is forbidden".  Could you add a pointer to the page addressing how to handle this error?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7da91eaf-b220-a7f2-18a6-25539ca6fea3
* Version Independent ID: b7b9cac7-469c-606d-905c-8a87a0eba401
* Content: [Microsoft Defender for Endpoint APIs connection to Power BI](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api-power-bi?view=o365-worldwide#sample-reports)
* Content Source: [microsoft-365/security/defender-endpoint/api-power-bi.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/api-power-bi.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@msekkappan Thank you for your feedback. This is either an issue with the permissions or a bug, I'd recommend you reach out to the support team via the need help section on the admin center so that this can be escalated internally for a fix.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @msekkappan Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
