### ISSUE TITLE
Clarifying language in Advanced phishing thresholds

### ISSUE THREAD

**Issue by edfishermsft** [MicrosoftDocs/microsoft-365-docs#1270]
In the section Advanced phishing thresholds, it references "the standard way" and "the same way" but it is not clear whether those are the same, and to what they actually refer. Assuming they are the same, and refer to the "Choose Actions" setting detailed above, could we make this more clear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?source=docs#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@edfishermsft - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/f5f93baac010a3261dc4aea307dd0a526eebc0ca. 


Thank you for your contribution to make the docs better! Much appreciated!
