### ISSUE TITLE
GCC High settings page missing.

### ISSUE THREAD

**Issue by iviryz** [MicrosoftDocs/microsoft-365-docs#12707]
GCC High instructions missing, blade is missing from the security & privacy (org settings) tab.  This is for idle timeout settings which is GA, but missing from the GUI.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Version Independent ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Content: [Idle session timeout for Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/idle-session-timeout-web-apps?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/idle-session-timeout-web-apps.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@iviryz Thank you for your feedback. The settings page is GA, I'd recommend you contact support via the need help section on the admin center, so that the support team can fix this for you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @iviryz Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by iviryz** [comment]
It is that way in all GCC high tenants we manage, i've even asked other admins in other GCC High tenants to check as well, it is absolutely not there in any tenant.  Would recommend that be added to the learn page that it is not located there in GCC High.
