### ISSUE TITLE
Links to endpoint URL list result in "404 - File or directory not found."

### ISSUE THREAD

**Issue by PMKMSFT** [MicrosoftDocs/microsoft-365-docs#12705]
Step 1. Allow URLs for the Microsoft Defender for Endpoint traffic result in 404 error.
```
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

```
This section : https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/comprehensive-guidance-on-linux-deployment?view=o365-worldwide&source=docs#step-1-allow-urls-for-the-microsoft-defender-for-endpoint-traffic

`Download [Microsoft Defender for Endpoint URL list for commercial customers](https://download.microsoft.com/download/8/a/5/8a51eee5-cd02-431c-9d78-a58b7f77c070/mde-urls.xlsx) or [Microsoft Defender for Endpoint URL list for Gov/GCC/DoD](https://download.microsoft.com/download/8/a/5/8a51eee5-cd02-431c-9d78-a58b7f77c070/mde-urls.xlsx) that lists the services and their associated URLs that your network must be able to connect.
`

**Comment by msbemba** [comment]
@PMKMSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12732

Once the author approves, the changes will be live.

Thanks
Sri
