### ISSUE TITLE
id used for this API seems inconsistent with other security API:s ?

### ISSUE THREAD

**Issue by JimBjorklund** [MicrosoftDocs/microsoft-365-docs#12717]
https://api.securitycenter.microsoft.com/api/machines returns an id that cannot be used by this api.
That is, https://api.securitycenter.microsoft.com/api/machines/{id} will not work when replacing the {id} with the id returned for a machine by the other api. It works when the "Device id" visible in Defender (https://security.microsoft.com/machines/v2/...) for a device is used.

Is this by design or a mistake? If it's by design, how can we get the correct id that is needed by the api?

I have also commented on this on Stackoverflow: https://stackoverflow.com/questions/71229238/microsoft-security-center-api-filter-not-working/77013073

When experimenting further I can see that for some machines I get more than one match by matching on DNS, 3 in one case, and one of these have an id (that is the name of the property in the returned json) that matches "Device id". I clearly need to examine this further.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0bd7b7cf-2e09-891e-c89e-a6aef8c94f4d
* Version Independent ID: 4be5364b-1fda-6f54-c27c-2a2544a204d0
* Content: [Get machine by ID API](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machine-by-id?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-machine-by-id.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-machine-by-id.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by JimBjorklund** [comment]
Hi, after further investigation it seems more than likely that this only affected some devices which may have been registered more than once due to being cloned (we use SCCM). I do not thing this needs to be investigated further.

**Comment by yogkumgit** [comment]
@JimBjorklund Thanks
