### ISSUE TITLE
Recover mails deleted from Quarantine

### ISSUE THREAD

**Issue by sgfurgi** [MicrosoftDocs/microsoft-365-docs#12713]
Hello
I don´t see here or anywhere in the MS documentation or forums, how do you recover a message deleted from the quarantine. First, it's not crystal clear for me if when a message gets into the quarantine, it uses a centralized storage for all the quarantined messages or it use the mailbox storage of each mailbox. I think it's the second one. Besides where is stored, where are the deleted messages from the quarantine if you delete them and you don't check the option for permanent deletion? I think if you have an option to soft delete, you have a way to recover too.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an admin](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@sgfurgi, currently, admins can't recover any messages that were deleted from quarantine.

A quarantined message either never reaches the mailbox (intercepted during mail flow) or is removed from the mailbox after delivery via ZAP, so you can think of it as centralized storage.

Yes, [delete a quarantined message](https://learn.microsoft.com/microsoft-365/security/office-365-security/quarantine-admin-manage-messages-files#delete-email-from-quarantine) includes a selection to **Permanently delete** or **Delete**. 

- **Permanently delete**: No recovery possible by anyone, not even Microsoft support.
- **Delete**: Currently, no way for admins to recover the message themselves.

Does this make sense?

**Comment by sgfurgi** [comment]
Hi Chris, thanks for the answer. Yes, makes sense partially. So, if the tenant admin can't recover the mail, who can? Microsoft support by opening a ticket?

Thanks again

**Comment by chrisda** [comment]
@sgfurgi, not to shout it from the mountaintops, but yes, if you selected **Delete** and not **Permanently Delete**.

**Comment by sgfurgi** [comment]
Thanks Chris
