### ISSUE TITLE
I can't cancel meetings in my calendar in Office 365 by Remove-CalendarEvents!

### ISSUE THREAD

**Issue by FunkEinstein** [MicrosoftDocs/microsoft-365-docs#1271]
Today I found that my scripts which cancels calendar events stopped working. Now I can cancel meetings only by using Set-MailboxAutoReplyConfiguration with DeclineEventsForScheduledOOF and DeclineAllEventsForScheduledOOF flags! What did you do? My code didn't change several month!

**Comment by whh5599** [comment]
我无法通过Remove-CalendarEvents在Office 365中取消日历中的会议！ 9 hours ago

**Comment by FunkEinstein** [comment]
I found that a problem was in calendar event, it hasn't attendees and command can't cancel it.
