### ISSUE TITLE
Incorrect timezone instructions

### ISSUE THREAD

**Issue by 25004** [MicrosoftDocs/microsoft-365-docs#12721]
This page has the wrong instructions for how to set your timezone. It says:

>To set the time zone for these features, go to Settings > Microsoft 365 Defender > Time zone.

However, the setting is actually under:

>Settings > Security center > Time zone

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/4212061/a3cbdf69-7ac0-49c5-a7ee-43a54dcb2f7e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96430923-3fc2-48df-fe6a-ddc3b62a908c
* Version Independent ID: 61ce1cd0-8dce-f926-4272-b6e579bb426a
* Content: [Set the time zone for Microsoft 365 Defender features](https://learn.microsoft.com/en-us/microsoft-365/security/defender/m365d-time-zone?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/m365d-time-zone.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/m365d-time-zone.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @diannegali
* Microsoft Alias: **diannegali**

**Comment by msbemba** [comment]
@25004 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12742

Once the author approves, the changes will be live.

Thanks
Sri
