### ISSUE TITLE
DMARC is a fiction in Microsoft as you allow all email to go through

### ISSUE THREAD

**Issue by slawekdejneka** [MicrosoftDocs/microsoft-365-docs#12723]
Guys,

You are so proud that you have implemented DMARC for all incoming emails, however it doesn't work as your Policy and Action are both set to NONE.

 smtp.mailfrom=hotmail.com; dmarc=pass (p=none sp=none pct=100) action=none

Your security settings are useless...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email, setup steps](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-dmarc-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/email-authentication-dmarc-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/email-authentication-dmarc-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@slawekdejneka Thank you for your feedback. Since you have a technical issue, I'd recommend you contact support via the need help section in the admin center, so that our support team can fix this issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @slawekdejneka Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
