### ISSUE TITLE
I m working on antiphishing  looking for microsoft staticstic on phishing and data set for 2023

### ISSUE THREAD

**Issue by ashvinigjadhav** [MicrosoftDocs/microsoft-365-docs#12728]
Phishing Attack Techniques and Trends:

    Kumar, S., & Bhatia, S. (2012) - "Phishing Attacks and Countermeasures: the Increasing Threat of Electronic Crimes." [Citation: Ref No 1]
    Nazario, J. (2006) - "Spear Phishing: A New Wave of Attacks." [Citation: Ref No 3]
    Kang, B. G., Kim, S. H., & Kim, S. (2013) - "Voice Phishing Attacks." [Citation: Ref No 4]
    Ramzan, Z. (2007) - "Pharming: A New Type of Cyber Attack." [Citation: Ref No 6]
    Gurbani, V. K., Ko, R. K., & Ong, C. S. (2007) - "Vishing: Measuring the Vulnerability of VoIP Users to VoIP Phishing." [Citation: Ref No 13]
    Fu, X., & Liu, L. (2009) - "A Survey of Mobile Phishing Attacks and Defence Techniques." [Citation: Ref No 14]
[Enter feedback here]
<html><body>
<br / id="docs-internal-guid-51bce893-7fff-2517-9fb6-c69538d1b063"><h3 dir="ltr" style="line-height:1.38;text-align: justify;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:10pt;font-family:'Times New Roman',serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">III. Phishing Overview</span></h3><div dir="ltr" style="margin-left:0pt;" align="left">

Ref No | Paper Title | Author(s) | Publication Year | Summary | Key Technologies Discussed
-- | -- | -- | -- | -- | --
1 | Phishing Attacks and Countermeasures: the Increasing Threat of Electronic Crimes | Kumar, S., & Bhatia, S. | 2012 | Discusses common phishing attack methods and explores countermeasures. | Email Phishing
2 | The Art of Deception: Training the Insider Threat | Hadnagy, C. | 2011 | Explores social engineering techniques used in phishing attacks. | Social Engineering
3 | Spear Phishing: A New Wave of Attacks | Nazario, J. | 2006 | Focuses on targeted spear phishing attacks and their implications. | Spear Phishing
4 | Voice Phishing Attacks | Kang, B. G., Kim, S. H., & Kim, S. | 2013 | Investigates voice-based phishing (vishing) attacks and suggests preventive measures. | Vishing
5 | Mobile-based Smishing in the Wild | De Decker, B., & Christiaens, M. | 2016 | Examines SMS-based phishing (smishing) attacks on mobile devices. | Smishing
6 | Pharming: A New Type of Cyber Attack | Ramzan, Z. | 2007 | Provides insights into pharming attacks and their mechanisms. | Pharming
7 | Email Clone Detection and Characterization | Li, Q., et al. | 2019 | Focuses on clone phishing, proposing techniques for the detection and characterization of cloned emails. | Clone Phishing
8 | Detecting Malicious URLs in Emails | Gupta, P., Sahoo, D., & Thomas, C. | 2019 | Discusses methods to identify malicious URLs in emails, emphasizing URL analysis and feature extraction. | Deceptive URLs
9 | Detecting Malicious Attachments in Emails | Alzahrani, A., & Jiang, X. | 2020 | Presents techniques for detecting malicious email attachments, with a focus on machine learning-based approaches. | Malicious Attachments
10 | Detecting Email Impersonation Attacks: A Comprehensive Review | Nguyen, H. A., et al. | 2020 | Provides a comprehensive review of techniques to detect email impersonation attacks, emphasizing sender verification and behavioral analysis. | Impersonation
Research Gaps:
Limited Coverage of Emerging Techniques: Most of the research papers focus on well-known phishing techniques, such as email phishing, spear phishing, vishing, and smishing. However, there is limited coverage of emerging and novel phishing techniques. Research should explore and analyze the latest tactics employed by cybercriminals.
Incomplete Understanding of Pharming: While some papers touch on pharming attacks, there is a gap in having a comprehensive understanding of pharming techniques and their countermeasures. Further research could delve deeper into this area.
Insufficient Coverage of Clone Phishing: The research on clone phishing is limited to clone detection methods. There is a research gap in exploring the evolution of clone phishing techniques and how to effectively counteract them.
Lack of Multidisciplinary Approaches: The presented papers primarily approach phishing attacks from a technical standpoint. There is a research gap in integrating multidisciplinary approaches, such as psychology and user behavior analysis, to better understand and mitigate phishing threats.
Limited Attention to Real-time Detection: While some papers discuss detection techniques, there is a research gap in developing and evaluating real-time detection mechanisms for various phishing tactics. Real-time detection is crucial for preventing successful attacks.
User-Centric Education: Although some papers touch upon user awareness, there is a gap in research that focuses on innovative and effective user-centric education and training strategies to reduce the susceptibility of individuals to phishing attacks.
Evaluation in Diverse Environments: Many papers evaluate their proposed solutions in controlled environments. There is a need for research that evaluates anti-phishing measures in diverse real-world settings to ensure their effectiveness across different scenarios.
Holistic Approaches: The research papers often address specific phishing tactics in isolation. A research gap exists in developing holistic anti-phishing approaches that can handle multiple tactics simultaneously and adapt to evolving attack strategies.

</div>
</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70a146b0-2b14-817e-a6c0-fe1b94f6d169
* Version Independent ID: 70a146b0-2b14-817e-a6c0-fe1b94f6d169
* Content: [Phishing trends and techniques](https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/phishing-trends?view=o365-worldwide)
* Content Source: [microsoft-365/security/intelligence/phishing-trends.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/intelligence/phishing-trends.md)
* Service: **microsoft-365-security**
* Sub-service: **intelligence**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ashvinigjadhav Thank you for your feedback. You will need to contact support via the need help section on the admin center, so that the support team can help you get the details.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ashvinigjadhav Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
