### ISSUE TITLE
Incorrect Information

### ISSUE THREAD

**Issue by elyas-farhani-db** [MicrosoftDocs/microsoft-365-docs#12722]
[Settings > Security Center > Time zone is a correct location]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96430923-3fc2-48df-fe6a-ddc3b62a908c
* Version Independent ID: 61ce1cd0-8dce-f926-4272-b6e579bb426a
* Content: [Set the time zone for Microsoft 365 Defender features](https://learn.microsoft.com/en-us/microsoft-365/security/defender/m365d-time-zone?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/m365d-time-zone.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/m365d-time-zone.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @diannegali
* Microsoft Alias: **diannegali**

**Comment by msbemba** [comment]
@elyas-farhani-db Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12742

Once the author approves, the changes will be live.

Thanks
Sri
