### ISSUE TITLE
Some Links are not valid anymore...

### ISSUE THREAD

**Issue by abunzel** [MicrosoftDocs/microsoft-365-docs#1273]
error message "The requested page was not found."
Please update the links to the BSI websites (www.bsi.bund.de)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bc6b13-6706-19be-d5f7-f455610c448e
* Version Independent ID: ac511ee9-67fc-b378-9c13-4b23b46d74cf
* Content: [Cloud Computing Compliance Controls Catalog (C5) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-c5-germany#feedback)
* Content Source: [microsoft-365/compliance/offering-C5-Germany.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-C5-Germany.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@abunzel - thanks for the feedback, I've updated the links in the topic to point to the new locations.
