### ISSUE TITLE
3 or 4 hours?

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/microsoft-365-docs#12734]
As the document states the Troubleshooting mode lasts for 3 hours and the portal during enablement tells 4 hours - which information is true?

If 4 is true, please also update the Advanced Hunting Code to 4

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Version Independent ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Content: [Get started with troubleshooting mode in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@myfope Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12743

Once the author approves, the changes will be live.

Thanks
Sri
