### ISSUE TITLE
Groups Administrator is also allowed to create Microsoft 365 groups

### ISSUE THREAD

**Issue by Borgquite** [MicrosoftDocs/microsoft-365-docs#12749]
In the list
'Other roles can create Microsoft 365 Groups via limited means, listed below.'

The 'Groups Administrator' role should also appear (with whatever means it is able to create Microsoft 365 Groups also shown)

https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#groups-administrator

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://learn.microsoft.com/en-gb/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Borgquite Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12762

Once the author approves, the changes will be live.

Thanks
Sri
