### ISSUE TITLE
Missing or outdated

### ISSUE THREAD

**Issue by stu68** [MicrosoftDocs/microsoft-365-docs#12740]
On step 7 there is nowhere to enter the user's name. That page is just a list of properties for the user profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34c90550-34c3-c6de-81d4-6d85a8bc3f90
* Version Independent ID: 151fb754-7bea-f489-5115-e3551db0f303
* Content: [Step 5 - Give another employee access to OneDrive and Outlook data - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-5?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-5.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-5.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@stu68 Thank you for your feedback. I'm able to locate the box to enter username 

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/f9a3bf7f-ae52-4eaa-bd8a-51dfeb2dea83)


If you continue to have problem, please contact support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @stu68 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
