### ISSUE TITLE
XML tag mismatch/typo in examples

### ISSUE THREAD

**Issue by JamesDickson108** [MicrosoftDocs/microsoft-365-docs#12741]
In the JAMF Recommended Configuration Profile, the JAMF Full Configuration Profile, and the Intune Full Configuration Profile examples there is a tag type mismatch on the block line under tamperProtection-->EnforcementLevel-->block. The current line is:
`<string>block</key>`

the correct tag should be:
`<string>block</string>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2dc758cd-0668-546f-5132-c3b5d2bf2b8e
* Version Independent ID: afa7ca04-3825-e73a-bd6e-4cf55010bd60
* Content: [Set preferences for Microsoft Defender for Endpoint on Mac](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-preferences?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-preferences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-preferences.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@JamesDickson108 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12774

Once the author approves, the changes will be live.

Thanks
Sri
