### ISSUE TITLE
User in Security Administrator role was unable to perform task of managing device roles, UI was greyed out.

### ISSUE THREAD

**Issue by dave-007** [MicrosoftDocs/microsoft-365-docs#12748]
User in Security Administrator role was unable to perform task of managing device roles, UI was greyed out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 796818f1-67d6-9a20-9498-94baf03276d6
* Version Independent ID: a9293050-acc0-7710-52cf-5cf64689d719
* Content: [Create and manage roles for role-based access control](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/user-roles?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/user-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/user-roles.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@dave-007 Thank you for your feedback. Looks like a technical issue as the UI should be editable. I'd recommend contacting support via the need help section on the admin center for technical assistance.

Hope thia helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dave-007 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
