### ISSUE TITLE
Reviewer Email Issues

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/microsoft-365-docs#1274]
The reviewer email section of the importer tool states: 

>When this property is populated, a  disposition review will be triggered when the retention duration  expires. This property specifies the email address of a reviewer for Delete and KeepAndDelete  retention actions. You can include the email address of individual  users, distribution or security groups, or Office 365 groups. You can  specify multiple email addresses separated by commas.

When trying to add an Office 365 group I am getting an error that the ReviewerEmail {O365 Group Email} is not supported. 

Additionally, multiple emails need to be separated by a semicolon, when trying with a comma you will get an error when importing the document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Overview of file plan manager - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/file-plan-manager)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by chvukosw** [comment]
Hello, we are looking into this issue, thank you for your patience.

**Comment by msbemba** [comment]
@Mlavieri Thank you for your feedback. We have made changes to the doc via PR #https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1312

Thanks
Sri

**Comment by chvukosw** [comment]
PR merged, thank you.
