### ISSUE TITLE
The document is mistakenly stating Microsoft Defender runs in passive mode when Smart App Control is on

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/microsoft-365-docs#12747]
Smart App Control being turned on does not make the Microsoft Defender run in passive mode, only 3rd party AVs do that. [This part](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide#microsoft-defender-antivirus-and-non-microsoft-antivirusantimalware-solutions) of the document needs to be corrected,

<br>

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/118815227/fbac8078-288a-4084-b3f5-87df789f4f23)

<br>

### This is the status of AMRunningMode showing normal when Smart App Control is turned on.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/118815227/067098d3-adcf-4c54-abe0-bf0939fc8b2f)

<br>

### This is the status of AMRunningMode showing normal when a 3rd party AV is installed

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/118815227/3256c41f-f329-4fb2-87fb-108660fbf965)

**Smart App Control never sets it to passive mode like the document states.**

<br>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61024433-366d-5ea3-4a3f-0cdd5cdcd900
* Version Independent ID: 348d3fc9-0937-b3a6-897e-09d1236d7019
* Content: [Microsoft Defender Antivirus compatibility with other security products](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide#use-windows-powershell-to-confirm-that-microsoft-defender-antivirus-is-running)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @HotCakeX and thank you for the feedback. I'm looking into this.

**Comment by HotCakeX** [comment]
> Hello @HotCakeX and thank you for the feedback. I'm looking into this.

Hi, Thank you!

**Comment by denisebmsft** [comment]
Hi again @HotCakeX. I updated the article and you'll see the changes live later today (like at around 4 p.m. Pacific Time). Thank you so much for letting us know about this.

**Comment by HotCakeX** [comment]
> Hi again @HotCakeX. I updated the article and you'll see the changes live later today (like at around 4 p.m. Pacific Time). Thank you so much for letting us know about this.

That is really good to know!
Anytime and thank you very much for quick response 🙂
