### ISSUE TITLE
"Office 365 URLs and IP address ranges" page should include change log 

### ISSUE THREAD

**Issue by bodowney1** [MicrosoftDocs/microsoft-365-docs#12757]
When customers subscribe to the RSS feed for changes, they will get a notification similar to the one below:

-----------------------------------------------------------------------------------
<lastBuildDate>Tue, 29 Aug 2023 23:51:24 Z</lastBuildDate>
    <item>
      <guid isPermaLink="false">2023082900</guid>
      <link>https://endpoints.office.com/changes/Worldwide/2023082900?singleVersion=true&amp;clientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7</link>
      <title>2023082900 - Worldwide</title>
      <description>Version 2023082900 includes 5 changes. IPs: 4 added and 4 removed. URLs: 0 added and 1 removed. 7 other attributes changed.</description>
      <pubDate>Tue, 29 Aug 2023 23:51:24 Z</pubDate>
    </item>
----------------------------------------------------------------------------------

My customer reached out to me and wanted to know if there is a way to find out what were the changes?  In this example above, what 4 IP addresses were added, and which ones were removed.    Outside of finding an old version of the o365 URL/IP addresses page and comparing the two, was unable to find anything.   

Is this something that could be added in the near future?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@bodowney1 We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).

**Comment by bodowney1** [comment]
Thanks for the quick response, Yogesh..  Howwever, what my customer is looking are the changes as well.   For example, what was removed, and what was added..     If this page is generated from a DB then there has to be  way to publish a page showing just the changes..     Is this something that could be added?

Thanks



Sent from Outlook<http://aka.ms/weboutlook>
