### ISSUE TITLE
Lots of good info, but where in the GUI do you go to set this up?

### ISSUE THREAD

**Issue by linx-collin** [MicrosoftDocs/microsoft-365-docs#12754]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed62cce4-7497-d557-8ee9-1e9d65dfc408
* Version Independent ID: 58739750-4fee-52d1-be71-9d379f59ee91
* Content: [Set up SPF to help prevent spoofing](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/email-authentication-spf-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/email-authentication-spf-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/email-authentication-spf-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@linx-collin, you set up the SPF TXT record at your DNS registrar or your separate DNS hosting service if the registrar doesn't also host the DNS records for your domain. There isn't anything for you to do in the Microsoft 365 admin center or the Microsoft 365 Defender portal related to SPF records.

**Comment by yogkumgit** [comment]
@MSFTTracyP

**Comment by linx-collin** [comment]
Apologies, I'm closing this out as it was just a note aout the web page and I couldn't find anything about the spf stopping public folder emails from working. Also, we setup spf recordds on our domains and we still get email that fail spf coming through. So I thought there was a page in the admin console to enable the blocking of records that fail spf. But it's mute now since I discovered that it breaks mail enabled public folders.
