### ISSUE TITLE
Known issues using "All Cloud Apps"

### ISSUE THREAD

**Issue by clajes** [MicrosoftDocs/microsoft-365-docs#1275]
[Enter feedback here]
Hi 

I suggest that we include more details for each protection level about our guidance for targeting apps. Zero Trust Architecture calls for customers to target "All Cloud Apps" and require known/compliant device and known user. However if they do that, there are some important scenarios that breaks, like using device code flow, Intune ESP with WSfB, CMD, Teams tabs i.e. Below I attach a ppt table with some of the scenarios that I have stumbled into.  Some are client related and some are related to the backend. I am happy to elaborate on this. Potentially you can look at our internal Ready session, where I walk through some of the challenges, MWST319TT.
[Doc1.docx](https://github.com/MicrosoftDocs/microsoft-365-docs/files/4239461/Doc1.docx)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0edb16f-03bd-e6f8-87e1-7fc713db726d
* Version Independent ID: 34252c76-c635-0fe0-e0fc-283d0e87d3b7
* Content: [Common identity and device access policies - Microsoft 365 Enterprise - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/identity-access-policies)
* Content Source: [microsoft-365/enterprise/identity-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/identity-access-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by martincoetzer** [comment]
Thank you for this feedback. We are constantly looking at improving this content and will certainly consider your suggestions in our next round. A Zero Trust approach is important and this article can form part of an organization's bigger Zero Trust strategy. Check out our Zero Trust center for more information: https://www.microsoft.com/en-us/security/business/zero-trust

**Comment by martincoetzer** [comment]
#please-close
