### ISSUE TITLE
Some critical guidance on "domain targeting" is needed on all policy articles

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#12753]
So I am leaving this on AntiSpam, but the same is true of ALL custom policies (where you can target users/groups/domains)

This is the current text as it reads in the AntiSpam article:

Domains: All recipients in the specified [accepted domains](https://learn.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains) in your organization.

What it should say is "Domains: All recipients who have that domain as their PRIMARY SMTP ADDRESS/User Principal Name"

Here's why:

If you have two antispam policies:

	1) Default (applies to all)
	2) A custom inbound named "Q" - blocking chris.lehr@gmail.com as a sender - applied to DOMAIN thelehrfamily.com

Two mailboxes:
	1) Chris Lehr (me@chrislehr.com as primary, chris@**thelehrfamily**.com as secondary)
	2) Quinlan Lehr (Quinlan@**thelehrfamily**.com as primary, quinlan@chrislehr.com as secondary

Test cases:

	1) Gmail to me@chrislehr.com - WORKED
	2) Gmail to chris@thelehrfamily.com - WORKED (this proves that the policy evaluation is done on PRIMARY email not secondary)
	3) Gmail to quinlan@thelehrfamily.com - QUARANTINED (as expected)
        4) Gmail to quinlan@chrislehr.com - QUARANTINED (this doubly proved the policy evaluation is done on PRIMARY email not secondaries!)

So basically - domain targeting has a potential perception issue - people think that they can swing a secondary domain over first to "test their new policy targeting domains" and its just not the case.

Please firm up the language if you agree and see it fit.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4babe398-9d2b-60ab-603b-4b564159ae3b
* Version Independent ID: 4babe398-9d2b-60ab-603b-4b564159ae3b
* Content: [Configure spam filter policies](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-policies-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-policies-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-policies-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chrislehr, I changed the domain description everywhere to say:

> **Domains**: All recipients in the organization with a primary email address in the specified [accepted domain](https://learn.microsoft.com/exchange/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains).

OK?

**Comment by chrislehr** [comment]
That totally works.  Thanks for the quick remedy, love it.
