### ISSUE TITLE
Sri Lanka‘s Phone number 2423 254 is incorrect. 

### ISSUE THREAD

**Issue by Sarahxxy** [MicrosoftDocs/microsoft-365-docs#12751]
Sri Lanka‘s Phone number 2423 254 is incorrect. 

it should be 0112423254

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fd44420-06a6-a5aa-973c-fb5fdc1ff758
* Version Independent ID: 4fd44420-06a6-a5aa-973c-fb5fdc1ff758
* Content: [Find Microsoft 365 for business support phone numbers by country or region - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/support-contact-info?view=o365-worldwide#sri-lanka)
* Content Source: [microsoft-365/admin/support-contact-info.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support-contact-info.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by Sarahxxy** [comment]
Hi, any update for this feedback?

**Comment by msbemba** [comment]
@Sarahxxy We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12763

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@msbemba I'm verifying with support before approving.

**Comment by Sarahxxy** [comment]
Hi All, 

We just received a new complaint from internal stakeholders regarding Sri Lanka M365 tech support customer facing number. The incorrect phone number has already badly impacted the CPE. Please help to verify and update the website. Thanks a lot.

**Comment by Sarahxxy** [comment]
Hi 

> @msbemba I'm verifying with support before approving.

Hi Cern, the hotline number is not updated yet. 
Please let us know if you need any update information or do you need someone to verify the hunber? You can connect to Bifang or me(v-xiaoyx) to arrange the test. 

The wrong number on website may lead potential CPE issue. Thanks for understanding.

**Comment by Sarahxxy** [comment]
> @msbemba I'm verifying with support before approving.

Hi Cern, sorry to push. Just want to check the ETA for the change. Thanks a lot.

**Comment by Sarahxxy** [comment]
> @msbemba I'm verifying with support before approving.

Hi Cern, 

I just checked the phone number for Sri Lanka  on https://learn.microsoft.com/en-us/microsoft-365/admin/support-contact-info?view=o365-worldwide#sri-lanka was not corrected yet. Could you let us know the ETA? And what else step needs to be taken? Thanks a lot.
