### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by apcsb** [MicrosoftDocs/microsoft-365-docs#12775]
> Intunwin file Upload Flow (unable to synchronize with Intune account)

Should read "Intunewin" in the first word. 

Side note: at first glance it looks unreasonable that one must both upload an IntuneWin package AND sync the app with Intune (why can't TestBase just download the package from Intune itself) - it almost looks like lazy design. It would be nice to have a few sentences explaining this decision and the related workflows so that people could see it for what it is.

Cheers :)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bcd3bc98-1584-60ad-33c4-d95c1d5412f2
* Version Independent ID: bcd3bc98-1584-60ad-33c4-d95c1d5412f2
* Content: [Test your Intune application on Test Base](https://learn.microsoft.com/en-us/microsoft-365/test-base/testintuneapplication?view=o365-worldwide)
* Content Source: [microsoft-365/test-base/testintuneapplication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/test-base/testintuneapplication.md)
* Service: **test-base**
* GitHub Login: @Tinacyt
* Microsoft Alias: **tinachen**

**Comment by msbemba** [comment]
@apcsb Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12803

Once the author approves, the changes will be live.

Thanks
Sri
