### ISSUE TITLE
Microsoft 365 Defender: Streaming API Settings page doesn't exist (anymore?)

### ISSUE THREAD

**Issue by Zoddo** [MicrosoftDocs/microsoft-365-docs#12776]
Following [this page](https://learn.microsoft.com/en-us/microsoft-365/security/defender/streaming-api-event-hub?view=o365-worldwide) to configure integration with a third-party SIEM, I'm unable to access the **Streaming API** settings because it looks like the page doesn't exist anymore.

I searched around and didn't found it anywhere.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/5215545/75bff2e0-e9a6-42c5-b37f-c51e2f800d32)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab552aac-1b60-da82-2266-8e3c0f61dcf1
* Version Independent ID: cc9dea71-92f1-1c0a-f96b-0c301b13b6d0
* Content: [Stream Microsoft 365 Defender events to Azure Event Hubs](https://learn.microsoft.com/en-us/microsoft-365/security/defender/streaming-api-event-hub?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/streaming-api-event-hub.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/streaming-api-event-hub.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Zoddo Thank you for your feedback. This seems to be a technical issue as I'm able to view the option

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/94bb2e23-9cc3-41b5-92d9-2daf1aebb792)


I'd recommend you contact support via the need help option in the admin center so that our support team can help you out.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Zoddo Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
