### ISSUE TITLE
Expected behaviour if Honor DMARC record policy when the message is detected as spoof:true and DMARC value=none

### ISSUE THREAD

**Issue by jbrianmoss** [MicrosoftDocs/microsoft-365-docs#12770]
What is the expected behaviour if

Honor DMARC record policy when the message is detected as spoof=true

and the DMARC pvalue is set to none

it isn’t clear what the behaviour would be. Assuming no filtering is applied this should be identified as a potential issue. If filtering is applied it would also be good to make that explicitly clear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies](https://learn.microsoft.com/en-ca/microsoft-365/security/office-365-security/anti-phishing-policies-about?view=o365-worldwide#spoof-protection-and-sender-dmarc-policies)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-policies-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-policies-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jbrianmoss, I think all roads lead to using the **If the message is detected as spoof by spoof intelligence** action (assuming, of course, that spoof intelligence is not turned off).

**Honor DMARC policy** On but `p=none` is 100% not covered by the `p=quarantine` or `p=reject` cases, so it would effectively be the same as **Honor DMARC policy** Off. This condition is effectively described in row 1 column 2 of the table in the article.

Back in the day before the **Honor DMARC policy** setting existed, if spoof intelligence was turned on, **everything** that was detected as spoof by Exchange Online Protection/Defender for Office 365 received the **If the message is detected as spoof by spoof intelligence** action (`p=whatever` in the DMARC record was completely ignored).

As long as spoof intelligence is turned on, EOP/MDO will act on a message that's detected as spoof. You either control what happens to it if `p=reject` or `p=quarantine` or not.

I'll see if I can dig up definitive answers.

**Comment by jbrianmoss** [comment]
May I suggest an edit then to the documentation to make it clear.

Current:
Separate actions for implicit and explicit email authentication failures:

- Implicit failures use the **If the message is detected as spoof by spoof intelligence** action the anti-phishing policy.
- Explicit failures for p=quarantine and p=reject DMARC policies use the **If the message is detected as spoof and DMARC policy is set as p=quarantine** and **If the message is detected as spoof and DMARC policy is set as p=reject** actions in the anti-phishing policy.

Suggested edit:
Separate actions for implicit and explicit email authentication failures:

- Implicit failures use the **If the message is detected as spoof by spoof intelligence** action the anti-phishing policy.
- Explicit failures for p=quarantine and p=reject DMARC policies use the **If the message is detected as spoof and DMARC policy is set as p=quarantine** and **If the message is detected as spoof and DMARC policy is set as p=reject** actions in the anti-phishing policy. Explicit failures for any other value of p than p=quarantine and p=reject, the **If the message is detected as spoof by spoof intelligence** action in the anti-phishing policy is used

**Comment by chrisda** [comment]
@jbrianmoss, thanks for the suggestions. I incorporated the information into the table. Feel free to modify it as necessary. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
