### ISSUE TITLE
404 Invalid Links

### ISSUE THREAD

**Issue by dbenn3268** [MicrosoftDocs/microsoft-365-docs#12784]
[Enter feedback here]
The links at the end of each row in the table lead to 404 Invalid Documents
They are 
1)  Defender for Business tenant administration guide.
2) Defender for Business security admin guide.
3)  Defender for Business security operations guide.

It would be great if these could be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c09ed539-d2c5-f0e1-2e92-84167e8103d4
* Version Independent ID: c09ed539-d2c5-f0e1-2e92-84167e8103d4
* Content: [Maintain your Microsoft Defender for Business environment](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-maintain-environment?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-maintain-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-maintain-environment.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @dbenn3268. I'm sorry for the broken links. I know that's frustrating. I'm fixing the article right now and the updates will be live later. The article you were viewing is actually replaced by this one, where you'll find all the information in one place: https://learn.microsoft.com/en-us/microsoft-365/business-premium/m365bp-mdb-maintain-environment?view=o365-worldwide&tabs=M365BP

Thank you so much for letting us know about this issue. Have a great rest of the week!
