### ISSUE TITLE
Line does not read well

### ISSUE THREAD

**Issue by stephenjoyceccw** [MicrosoftDocs/microsoft-365-docs#12787]
The following line does not read very well, and I do not understand it. What does it mean be "then enable"? I *think* I do not need to do anything if I receive an empty response for EwsEnabled, and I do not need to block anything. But it is very unclear.

If the command returns "EwsEnabled:" (empty is default), then enable, but only if need to block "Bookings with", and proceed to Step 2. Otherwise the default values of EwsEnabled is enough to leave "Bookings with me" enabled, no further changes are needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings with me](https://learn.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@stephenjoyceccw Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12802

Once the author approves, the changes will be live.

Thanks
Sri
