### ISSUE TITLE
onedrive deletion on BYOD

### ISSUE THREAD

**Issue by peterwww** [MicrosoftDocs/microsoft-365-docs#12795]
hey I'm trying to fully understand what happens when user accout  is deleted on M365 I got this article:

and part that makes me wonder is:

Important! If the deleted user used a personal computer to download files from SharePoint and OneDrive, there's no way for you to wipe those files they stored on their computer. They will continue to have access to any files that were synced from OneDrive.

does that mean Intune can't delete this data? I thought that's one of main selling points of BYOD with intune??

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6245943-00b8-c47b-f739-731531d5d357
* Version Independent ID: a9ec7066-ed8c-7b77-1d87-8c50bf74ec6c
* Content: [Delete a user from your organization - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/delete-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/delete-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/delete-a-user.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@peterwww Thank you for your feedback. In case the user downloads it on a personal and not the one that is configured via Intune (BYOD).

Hope this helps!

Thanks
Sri

**Comment by peterwww** [comment]
ok so as long as this personal BYOD is enrolled into Intune, work profile data can still be deleted? Is this correct?

Kind regards,

Peter Wiktorowski
Customer Success Manager | Modern Workplace
***@***.***
+44 (20) 76608537


***@***.***?anonymous&ep=signature>


Book time to meet with ***@***.***?anonymous&ep=plink>

[cid:5500883d-f44b-4397-873f-451a8e66cd57]

________________________________

**Comment by msbemba** [comment]
@peterwww  That is correct.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @peterwww Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
