### ISSUE TITLE
About [Configure remediation options using Group Policy]

### ISSUE THREAD

**Issue by MitsutomoSawa** [MicrosoftDocs/microsoft-365-docs#12794]
[Enter feedback here]
Regarding [Default setting (if not configured)] below, the default retention period for the device seems to be [90 days].

Please correct this mistake.

[Configure remediation options using Group Policy]
https://learn.microsoft.com/en-US/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus?view=o365-worldwide#configure-remediation-options-using-group-policy

- Setting
Quarantine
Configure removal of items from Quarantine folder.

- Description
Specify how many days items should be kept in quarantine before being removed.

- Default setting (if not configured)
Items are kept in the quarantine folder indefinitely and aren't automatically removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c974b4-7004-d52c-0ffe-c6f3729477f9
* Version Independent ID: 7162a35d-fc78-54ac-531a-02ec8c07a8ff
* Content: [Configure remediation for Microsoft Defender Antivirus detections](https://learn.microsoft.com/en-US/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-remediation-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@MitsutomoSawa Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12801

Once the author approves, the changes will be live.

Thanks
Sri
