### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by AnthonyPuca** [MicrosoftDocs/microsoft-365-docs#12792]
Network Routing Architecture hyperlink is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1f4de16-6600-515c-138e-0d43f330a7b0
* Version Independent ID: 547b7ad4-1722-bd71-4818-95abbaa475ad
* Content: [Azure ExpressRoute for Microsoft 365 - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/azure-expressroute?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/azure-expressroute.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/azure-expressroute.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@AnthonyPuca Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12799

Once the author approves, the changes will be live.

Thanks
Sri
