### ISSUE TITLE
I do not have access

### ISSUE THREAD

**Issue by kale1d0code** [MicrosoftDocs/microsoft-365-docs#12798]
Adding email aliases following these instructions requires administrative access to admin.microsoft.com
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@kale1d0code Thank you for your feedback. This article is for Microsoft 365 administrators who have business subscriptions. As a end user you will need to contact your administrator to fix the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kale1d0code Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
