### ISSUE TITLE
Missing Value in DeliveryLocation field

### ISSUE THREAD

**Issue by jdc0730** [MicrosoftDocs/microsoft-365-docs#12791]
We are seeing in our tenant, some events with "Unknown" EmailDirection have "Forwarded" as the DeliveryLocation. This is not listed in the description of DeliveryLocation as a possible value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bab6c037-ac04-4146-de43-6aea809c0cef
* Version Independent ID: 7d06f8df-e4bb-26de-0146-ee016a4e0f54
* Content: [EmailEvents table in the advanced hunting schema](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-emailevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-emailevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-emailevents-table.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by ajaj-shaikh** [comment]
@jdc0730 we would love to understand the email routing mechanism you have that might be resulting in "Unknown" EmailDirection. Can you please create a support ticket (Microsoft Defender for Office 365) with the details as this is not one of the expected values in EmailDirection and DeliveryLocation. Thanks!

**Comment by msbemba** [comment]
@jdc0730 Thank you for your feedback. The value "Unknown" is strange, I'd recommend you contact support via the need help option on the admin center so that our support engineers can help you fix this bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jdc0730 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
