### ISSUE TITLE
Bookings "unpublish" instructions unhelpful

### ISSUE THREAD

**Issue by meganmotis** [MicrosoftDocs/microsoft-365-docs#12805]
I'm looking for the "unpublish" button to unpublish my bookings page as the documentation states should be present on my bookings page but I cannot find anything that says "unpublish" -- can someone update the instructions to reflect the actual steps to take in order to unpublish a bookings page? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93b5cf44-bd31-017e-c70f-62cc26ae42ea
* Version Independent ID: 26f5a25f-c80b-0d09-f6c3-6cfc97b31988
* Content: [Customize and publish your booking page](https://learn.microsoft.com/en-us/microsoft-365/bookings/customize-booking-page?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/customize-booking-page.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/customize-booking-page.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@meganmotis Thank you for your feedback. I was able to follow instructions and unpublish the bookings page. If you still have trouble, I'd recommend you contact support via the need help section on the admin center so that the support engineer will be able to help you out.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @meganmotis Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
