### ISSUE TITLE
Identifying groups to be created

### ISSUE THREAD

**Issue by jrfuste** [MicrosoftDocs/microsoft-365-docs#12806]
How do I identify the groups in the source tenant that need to be created in the target tenant.   What happens if I miss any group(s)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd31f549-0f9e-0a8e-a2a8-99367b5a99d7
* Version Independent ID: bd31f549-0f9e-0a8e-a2a8-99367b5a99d7
* Content: [OneDrive Cross-tenant OneDrive migration FAQs - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-onedrive-migration-faqs?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-onedrive-migration-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-onedrive-migration-faqs.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by jrfuste** [comment]
Is the Group ID we are looking for the GroupId property obtained with this command?  Get-SPOSite -IncludePersonalSite $True -Limit All -Filter "Url -like '-my.sharepoint.com/personal/'"

**Comment by msbemba** [comment]
@jrfuste Thank you for your feedback. You can review the below link https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-onedrive-migration-step4?view=o365-worldwide for Pre-creating users and groups

Hope this helps!

Thanks
Sri
