### ISSUE TITLE
Filtering files from the source during migration

### ISSUE THREAD

**Issue by jrfuste** [MicrosoftDocs/microsoft-365-docs#12807]
Is it possible to filter the files that are copied to the target tenant during migration?  For example: I want to transfer only files with creation dates of Jan 2020 or newer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd31f549-0f9e-0a8e-a2a8-99367b5a99d7
* Version Independent ID: bd31f549-0f9e-0a8e-a2a8-99367b5a99d7
* Content: [OneDrive Cross-tenant OneDrive migration FAQs - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-onedrive-migration-faqs?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-onedrive-migration-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-onedrive-migration-faqs.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by msbemba** [comment]
@jrfuste thank you for your feedback. Sorry, we do not have that option currently and will update once the feature is made available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jrfuste Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
