### ISSUE TITLE
How long until the retention policy takes effect?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#1280]
For step 5, after running Start-ManagedFolderAssistant, when can I expect the new policy to take effect?  I created a test retention policy & tag to permanently delete anything in Deleted Items that is older than 7 days.  After running Start-ManagedFolderAssistant, I still don't see anything deleted per the policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your Office 365 organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Canis-Lupis Assuming your retention policy and tags are set up correctly and assuming the MFA has completed the processing of the mailbox, I would imagine 24 hours or so. Otherwise, you could contact Microsoft Support.
