### ISSUE TITLE
Update URL link to service health page

### ISSUE THREAD

**Issue by jonortoni** [MicrosoftDocs/microsoft-365-docs#12813]
Hi, I'm the product manager for Microsoft 365 Service Health.  

On this doc page we need to update the destination of the service status page as follows: 

Current:
"If you are unable to sign in to the admin center, you can use the [service status page](https://status.office365.com/) to check for known issues preventing you from logging into your tenant."

New:
"If you are unable to sign in to the admin center, you can use the [service status page](https://status.cloud.microsoft/) to check for known issues preventing you from logging into your tenant."

Thanks, 
Jon Orton 
jonorton@microsoft.com 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78608b78-4e38-2bb6-7152-bb91c32a2bff
* Version Independent ID: 873f4181-89d5-8d41-2276-d78b1a203431
* Content: [How to check Microsoft 365 service health - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/view-service-health?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-service-health.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-service-health.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@jonortoni Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12852

Once the author approves, the changes will be live.

Thanks
Sri
