### ISSUE TITLE
RESEND Training Notifications to Users

### ISSUE THREAD

**Issue by BrianLeFlem** [MicrosoftDocs/microsoft-365-docs#12816]
I don't see how to RESEND the training notifications.  Many users receive the emails and either delete them or forget about them.
Admins need a way to be able to resend the notification emails to users who forget to do the training or delete them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b480c7ad-d444-b167-6c3c-80a8e8fb714d
* Version Independent ID: a17b1117-7d8a-54b1-fa72-6cc7b644a254
* Content: [Attack simulation training deployment considerations and FAQ](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-faq.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BrianLeFlem, a couple of months ago, I was asked about manually resending training reminders. This was the answer I got:

 > If you have selected training reminder notification while launching the simulation at a certain frequency, it will keep going to the user at that frequency even after the training due date.

So, it looks like you can't manually resend training notifications.

**Comment by yogkumgit** [comment]
@BrianLeFlem Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
