### ISSUE TITLE
Title is incorrect, this is done in Exchange not Outlook

### ISSUE THREAD

**Issue by JasonSherry** [MicrosoftDocs/microsoft-365-docs#1282]
Title "Upgrade distribution lists to Office 365 Groups in Outlook" is wrong, this is done via Exchange Admin Center not in OWA or Outlook clients

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb1e873-a684-ba18-21b4-33c2c4cf5aeb
* Version Independent ID: badad26e-0e5e-ab12-f3ae-b6cab759e7b8
* Content: [Upgrade distribution lists to Office 365 Groups in Outlook](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by MaratMussabekov** [comment]
Hello @JasonSherry ,

"Upgrade distribution lists to Office 365 Groups in Outlook" doesn't mean "Upgrade distribution lists to Office 365 Groups **using** Outlook" it means 
Upgrade objects called "**distribution lists**" to objects called "**Office 365 Groups in Outlook**"

So basically you are using Exchange Admin Center to transform **distribution lists** to **Office 365 Groups in Outlook**

It is quite confusing that the object type is named "**Office 365 Groups in Outlook**"

Thank you

**Comment by Sirkkuw** [comment]
@MikePlumleyMSFT this feels like your documentation area.

**Comment by mypil** [comment]
@JasonSherry  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
