### ISSUE TITLE
Zero-dollar invoices

### ISSUE THREAD

**Issue by dmore54** [MicrosoftDocs/microsoft-365-docs#12823]
[Enter feedback here]
How do I get you to stop sending zero-dollar invoices? There's no mention of an option here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 925122d4-0d3a-f271-02d8-db773c647cbe
* Version Independent ID: c5d17dc9-54c4-3092-85a9-3710e15983cb
* Content: [Understand your invoice for your Microsoft MOSA billing account](https://learn.microsoft.com/en-au/microsoft-365/commerce/billing-and-payments/understand-your-invoice2?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/understand-your-invoice2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/understand-your-invoice2.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@dmore54 Thank you for your feedback. Sorry about that, I'd recommend you contact our billing team via the need help section on the admin center, so that our engineer can assist you with the query.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dmore54 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
