### ISSUE TITLE
Licenses must be assigned

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#12824]
The article says 
> Similarly, CSP partners must purchase a quantity of Multi-Geo licenses equal to or greater than 5% of their customer's total eligible Microsoft 365 seats.

However, in addition to being purchased, the licenses must be assigned before multi-geo features light up.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32b41c7e-29cd-eb5b-36b2-738b3babd08f
* Version Independent ID: 22eda3f7-1c04-b3b0-95fd-3474b3f991b2
* Content: [Microsoft 365 Multi-Geo - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-multi-geo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-multi-geo.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@jonwbstr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12850

Once the author approves, the changes will be live.

Thanks
Sri
