### ISSUE TITLE
Please fix the incorrect OMA-URI.

### ISSUE THREAD

**Issue by KENJISHIRAKI** [MicrosoftDocs/microsoft-365-docs#12835]
I believe the OMA-URI for DataDuplicationRemoteLocation on this page is incorrect.
Therefore,  could you please fix it?
In this page, the OMA-URI is "./Vendor/MSFT/Defender/Configuration/DataDuplicationRemoteLocation" as the OMA-URI.
However, the following public information lists "./Device/Vendor/MSFT/Defender/Configuration/DataDuplicationRemoteLocation".
<Configuration/DataDuplicationRemoteLocation>
https://learn.microsoft.com/en-us/windows/client-management/mdm/defender-csp#configurationdataduplicationremotelocation

In other words, "/Device" is required but not listed.
If the OMA-URI is set as described in this page, error 0x87d1fde8 will occur when the configuration profile is distributed from Intune.
So, could you please fix it to the correct OMA-URI?
Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3162a66-262e-660c-a6d2-512b9b7d3199
* Version Independent ID: b3162a66-262e-660c-a6d2-512b9b7d3199
* Content: [Deploy and manage using Intune](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-and-manage-using-intune?view=o365-worldwide#deploy-using-intune-oma-uri)
* Content Source: [microsoft-365/security/defender-endpoint/deploy-and-manage-using-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deploy-and-manage-using-intune.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @nimishasatapathy
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@KENJISHIRAKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12844

Once the author approves, the changes will be live.

Thanks
Sri
