### ISSUE TITLE
Clarifying the Agent updates Important Note

### ISSUE THREAD

**Issue by C-quintana** [MicrosoftDocs/microsoft-365-docs#12831]
In the documentation for Linux updates a note reads:
"When integrating Microsoft Defender for Endpoint and Defender for Cloud, the mdatp agent will automatically receive updates by default."

Can this be expanded to clarify a situation where you have enabled the integration, but switched off agent auto provisioning via the environment settings?

Or perhaps clarify it by saying something along the lines of "When Defender for Cloud is provisioning the MDE agent to Linux Servers, it will keep the client updated automatically"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc544677-215d-f313-1ec7-7c7f01ab6c2d
* Version Independent ID: 24dd4601-7d59-58e5-1110-a80247fca563
* Content: [Deploy updates for Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-updates?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-updates.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@C-quintana Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12851

Once the author approves, the changes will be live.

Thanks
Sri
