### ISSUE TITLE
URL needed

### ISSUE THREAD

**Issue by johnuwi** [MicrosoftDocs/microsoft-365-docs#12837]
where is the URL for "lighthouse" itself? Please include

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6b0ae25-469d-c298-3899-3bcc24af1b90
* Version Independent ID: f6b0ae25-469d-c298-3899-3bcc24af1b90
* Content: [View opportunities in Sales Advisor in Microsoft 365 Lighthouse - Microsoft 365 Lighthouse](https://learn.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-view-opportunities?view=o365-worldwide)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-view-opportunities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-view-opportunities.md)
* Service: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@johnuwi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12845

Once the author approves, the changes will be live.

Thanks
Sri
