### ISSUE TITLE
Broken Link to Graph Docs

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/microsoft-365-docs#12833]
Hi,
the link [Set up a multitenant organization using Microsoft Graph API](https://learn.microsoft.com/en-us/azure/active-directory/multi-tenant-organizations/configure-graph#step-2-create-a-multi-tenant-organization) in the Section 'Related Topics' is broken.

Maybe this is the right one:
https://learn.microsoft.com/en-us/azure/active-directory/multi-tenant-organizations/multi-tenant-organization-configure-graph

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0191a050-64de-1a38-e2a0-a09964f6dc2b
* Version Independent ID: 0191a050-64de-1a38-e2a0-a09964f6dc2b
* Content: [Set up a multitenant org in Microsoft 365 (Preview) - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/set-up-multi-tenant-org?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/set-up-multi-tenant-org.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/set-up-multi-tenant-org.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@J-a-k-o-b Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12848

Once the author approves, the changes will be live.

Thanks
Sri
