### ISSUE TITLE
Get-TeamsSecurityPreview not available

### ISSUE THREAD

**Issue by jimmywinberg** [MicrosoftDocs/microsoft-365-docs#12834]
I'm connecting with and admin account using connect-Exchangeonline using exchangeonlinemanagement **version 3.3.0**
but the Get-TeamsSecurityPreview is not recognized as the name of a cmdlet.

Get-TeamsSecurityPreview
Get-TeamsSecurityPreview : The term 'Get-TeamsSecurityPreview' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-TeamsSecurityPreview
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-TeamsSecurityPreview:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by yogkumgit** [comment]
@jimmywinberg We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
