### ISSUE TITLE
Content error

### ISSUE THREAD

**Issue by lynelal** [MicrosoftDocs/microsoft-365-docs#12838]
Change "The default theme can only be deleted once all group themes are deleted. Make sure you delete all group themes before you try to delete the group theme."

To: "The default theme can only be deleted once all group themes are deleted. Make sure you delete all group themes before you try to delete the default theme."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6c85cc-1680-588e-f520-bcafb1383d53
* Version Independent ID: ea446e6b-e094-dacd-54cc-e597b2f1354d
* Content: [Customize the theme for your organization - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/customize-your-organization-theme?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/customize-your-organization-theme.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/customize-your-organization-theme.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@lynelal Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12846

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by lynelal** [comment]
Thank you. Have a wonderful day!
