### ISSUE TITLE
Missing/contradicting information for email forwarding

### ISSUE THREAD

**Issue by crmax-it** [MicrosoftDocs/microsoft-365-docs#12843]
The learn page (Configure email forwarding in Microsoft 365) makes no mention of the possibility to forward emails from shared mailboxes.

Under the "Before you begin" section it is stated that "Email forwarding requires that the from account has a license."
However, shared mailboxes are shown as unlicensed and in order to forward email from a shared mailbox, you do not need to assign a license.

Can the "Before you begin" section be corrected?
It would be useful to add a mention of the option for forwarding email with shared mailboxes and/or mention the article "https://learn.microsoft.com/en-us/microsoft-365/admin/email/configure-a-shared-mailbox?view=o365-worldwide#forward-emails-that-are-sent-to-a-shared-mailbox" in the related content section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@crmax-it Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12847 

Once the author approves, the changes will be live.

Thanks
Sri
