### ISSUE TITLE
Information about signed scripts is lacking

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#12841]
The `run` command on this pages only briefly describes how to run scripts. It does not mention anything about signing and the related advanced setting of Defender for Endpoint. Please add something about that or refer to an article about signing scripts, publishing the certificate in the local machine Trusted Publishers store etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbb2f7d-1aa5-4536-d22b-8b5b1f94f5b3
* Version Independent ID: 8878dc91-fdb6-349f-a0c2-5d4717fb40ed
* Content: [Live response command examples](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response-command-examples?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/live-response-command-examples.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/live-response-command-examples.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @diannegali
* Microsoft Alias: **diannegali**

**Comment by yogkumgit** [comment]
@diannegali Please help us in resolving this issue. Thanks

**Comment by diannegali** [comment]
@yogkumgit looks like this is the same as issue #12842.
