### ISSUE TITLE
Can not enter range of IP in IP Allow list. (Microsoft 365 Defender)

### ISSUE THREAD

**Issue by hiroyukioura** [MicrosoftDocs/microsoft-365-docs#12856]
Dear support teams,

as per below document, I'm trying to enter range of IP address into IP Allow list in Microsoft 365 Defender.
However, "Connection filter policy (Default)" window doesn't recognize my input as range of IP address, so that I can not enter this.

https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/connection-filter-policies-configure?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-modify-the-default-connection-filter-policy

![issue](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/5727349/39a16ee3-8ea9-4772-8efd-d982e03b6912)

Could you kindly support how to fix this ?

IP ranges that I'm trying to enter is below;
40.92.0.0-40.93.255.255
40.107.0.0-40.107.255.255
52.100.0.0-52.103.255.255
104.47.0.0-104.47.127.255

thank you so much for your kind support,
Best regards,
Hiro

**Comment by msbemba** [comment]
@hiroyukioura Thank you for your feedback. This is a support issue and needs to be routed to the support team via the need help section on the admin center, so that our support team can assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hiroyukioura Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
