### ISSUE TITLE
.CSV files for blocked words is bad

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/microsoft-365-docs#1286]
Hi,
You wrote:
"

> **Custom blocked words**
> 
> You can enter a comma separated list of blocked words that will be blocked in group names and aliases.

"

But this is very bad idea. Think about your file with 2500 words? How do you plan to handle that file. Most preferable solution is to use regular .txt file. In the file you have a word per line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd68ed6-8c0c-3605-1179-b5d2e3b7f20a
* Version Independent ID: 10489b06-4b34-d413-d250-873c5ef015eb
* Content: [Office 365 Groups naming policy](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/groups-naming-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/groups-naming-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/groups-naming-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@Petri-X - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.  **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)**
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Petri-X** [comment]
So far the UserVoice has been very poor idea. E.g. here is one issue is crazy bug in Teams:
[Start calendar week on monday (or allow setting)](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/32067667-start-calendar-week-on-monday-or-allow-setting)

It has been open 2017. And Microsoft seems to had not even single eye to it.

So I have give up with User Voice.
