### ISSUE TITLE
Using PIM for Exchange Administrator Limits Quarantine Rights or this is a Bug

### ISSUE THREAD

**Issue by JSC-HFT** [MicrosoftDocs/microsoft-365-docs#12872]
Need to clarify, if you are using PIM to elevate an account to the Exchange Administrator role, when accessing the Quarantine page no emails are returned.  It seems only accounts with permanent assignment to these roles can view the Quarantine page under https://security.microsoft.com/quarantine?viewid=Email

However, connecting to Exchange Online PowerShell you are able to pull back results with the equivalent PowerShell commands.

This is one of the nuances of PIM for role elevation vs permanent assignment.  When you activate the Exchange Administrator role via PIM, you should essentially be in the Org Management role.  Since it works in PowerShell, it makes no sense by the GUI page doesn't show results.  Please fix or clarify.

**Comment by DMoenks** [comment]
From personal experience, there's just one difference between eligible/temporary and active/permanent role assignments: Time
This also matches the definition in the [documentation](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-configure#terminology)

When role assignments change, the changes need to replicate throughout affected Microsoft services, which can take a while for some services and even differ based on access method (web interface, Powershell, etc.). This is inevitably more noticeable with temporary role assignments...
I'm not sure if this "limitation" is mentioned in the documentation, maybe it should, if possible even with average activation/replication times for specific services

If the issue persists, creating a support request from within the tenant would be suggested though, as reporting issues within this repository is primarily meant to improve the product documentation

**Comment by msbemba** [comment]
@JSC-HFT Thank you for your feedback. This sounds like a bug and needs to be reported to the support team/Product group. I'd recommend you create a support ticket via the need help section on the admin center, so that our support engineer can assist.

Hope this helps!

Thanks
Sri

**Comment by JSC-HFT** [comment]
Thanks, I will submit a suppose case.
