### ISSUE TITLE
QR codes do NOT appear to get scanned - is this a documentation bug?

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#12875]
Hello,

I am attacking this from a few angles, but I am quite sure SafeLinks is not scanning QR codes, despite the documentation stating it does.

Twitter post: https://twitter.com/chrislehratx/status/1706738945667875303
MS case #2309260010003813
Submission ID # df56b396-c705-45e1-afe9-08dbbec2e20e

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Version Independent ID: e6524290-9545-28fc-9cae-5c4a540ad526
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Update: [This issue](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12380) and [this related PR](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/49c1ce9dfec9f2eae8f1820043e9bdbd8b14b0da) from July 2023.

**Comment by chrislehr** [comment]
I have a suspicion it was added too soon on the news of OCR and Synnex

**Comment by chrisda** [comment]
OK, the word is that Safe Links doesn't support QR code scanning like regular URLs -- yet.

I removed the offending text.

Thanks for the feedback.

Closing
