### ISSUE TITLE
Out of date. 

### ISSUE THREAD

**Issue by tmguinn** [MicrosoftDocs/microsoft-365-docs#1287]
The steps are out of date with the move to Endpoint Security. Please update. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74814ff4-77e8-71eb-e78a-fa90cdc37c2c
* Version Independent ID: 55e188f7-4368-6d6a-c567-41347098d66b
* Content: [Use the step-by-step guide to add Autopilot devices and profile - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/add-autopilot-devices-and-profile?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/business/add-autopilot-devices-and-profile.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/add-autopilot-devices-and-profile.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@tmguinn  I still see the AutoPIilot steps within Microsoft 365 Business as they are described in the document. I think that the Intune docs have maybe changed?
