### ISSUE TITLE
Outdated instructions for Connecting Power Automate to Defender for Cloud

### ISSUE THREAD

**Issue by uniQuk** [MicrosoftDocs/microsoft-365-docs#12879]
The instructions & video for connecting Power Automate to Defender for Cloud Apps are outdated. They are based on using: portal.cloudappsecurity.com which can be confusing especially if tenants also have "Redirection to Microsoft 365 Defender" enabled. 

Current Instructions are based on using - portal.cloudappsecurity.com: 
"Click Settings, select Security extensions, and then click Add token in the API tokens tab."

The new location for this settings in: https://security.microsoft.com
"Click Settings, Click Cloud Apps, Click API tokens and then select Add token in the API tokens tab."

Ideally, both instructions and video would be updated or at least a note where the settings are depending on if you are in:
https://portal.cloudappsecurity.com
or
https://security.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a541e506-e227-1fda-e6db-7e8441098753
* Version Independent ID: c1d7febc-d327-85ce-a341-8552617b74d8
* Content: [Investigate alerts in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/investigate-alerts?view=o365-worldwide#connect-power-automate-to-microsoft-defender-for-cloud-apps)
* Content Source: [microsoft-365/security/defender/investigate-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/investigate-alerts.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @diannegali
* Microsoft Alias: **diannegali**

**Comment by msbemba** [comment]
@uniQuk Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12888

Once the author approves, the changes will be live.

Thanks
Sri
