### ISSUE TITLE
maximum 365 copilot plugins

### ISSUE THREAD

**Issue by amarmohax** [MicrosoftDocs/microsoft-365-docs#12882]
Hi,

Currently openai allows maximum 3 active plugins only. With MS 365 Copilot that is released with plugin feature, is there a maximum number of plugins that one can have or is there no limit? 

regards,
Amar

**Comment by yogkumgit** [comment]
@amarmohax Please indicate the document you are referring to and wish to give the feedback for its improvement. Thanks

**Comment by yogkumgit** [comment]
@amarmohax We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
