### ISSUE TITLE
SCL of 7?

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#12883]
In the table it states 8/9 are HC spam and then says:
**The SCL values 2, 3, 4, and 7 aren't used by spam filtering.**
Later it says:
**If you use a mail flow rule to set the SCL, the values 5 or 6 trigger the spam filtering action for Spam, and the values 7, 8, or 9 trigger the spam filtering action for High confidence spam**

So there is a contradiction on SCL of 7...  is that not in use, or in use?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3791d0d-3b80-76be-ffe4-9b94b513c240
* Version Independent ID: e143b459-56ce-8dc3-7537-a9bd33a1de94
* Content: [Spam confidence level](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-spam-confidence-level-scl-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-spam-confidence-level-scl-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-spam-confidence-level-scl-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chrislehr, not a contradiction. **Spam filtering** will never examine and tag a message with an SCL value of 7 for high confidence spam; it will use either 8 or 9.

But an Exchange mail flow rule (transport rule) can set the SCL value to 7, at which point the message will be treated as high confidence spam.

Pwehpa I should change the offending sentence to say something like:

> Spam filtering never examines and tags messages with the SCL values 2, 3, 4, and 7.

Or I could remove that line altogether if it helps. 2, 3, 4, and 7 are blatantly missing from the table already.

**Comment by chrislehr** [comment]
I like the first edit.  I think mentioning their absence in the table is important for understanding.  TY

**Comment by chrisda** [comment]
Fixed.

Thanks for the feedback.

Closing
