### ISSUE TITLE
When will Microsoft Graph support self-service product policies ?

### ISSUE THREAD

**Issue by salbeck-sit** [MicrosoftDocs/microsoft-365-docs#12880]
It is very un-enterprise friendly to publish a Powershell-module that only supports interactive sign-in.
These days, everything else is being made available through the Graph API and I fail to see why these policies should be neglected. Especially given that a failure to regulate according with enterprise government policies - for a CSP this means across multiple tenants - gives rise to users enabling themselves to do stuff that they are not trained for and subsequently raising tickets without anybody knowning what they're supposed to be doing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e05e10b-691c-2357-25f5-1a9e810c662d
* Version Independent ID: 0d789543-2033-d759-1fe9-69f24e458c13
* Content: [Manage self-service purchases and trials (for admins)](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by salbeck-sit** [comment]
I've entered a suggestion for the Graph-team, 
https://feedbackportal.microsoft.com/feedback/idea/72d03931-905e-ee11-a81c-0022484e5453

**Comment by msbemba** [comment]
@salbeck-sit Thank you for your feedback. You did the right thing by Providing feedback on our main portal as that is where the Dev and Prodocut engineers check and respond.  Since we are from the content team, we don't have access to the details that you are asking for.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @salbeck-sit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
