### ISSUE TITLE
"Hanges"

### ISSUE THREAD

**Issue by v-etmon** [MicrosoftDocs/microsoft-365-docs#1288]
"This group is available for use to validate compatibility of applications with new policy or operating system hanges." Hanges should be "changes".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63d4e59b-1326-1d3f-a3b0-40e3b9f5f7af
* Version Independent ID: 31fad9a8-65f2-cd7d-42f0-2252bb62d7ed
* Content: [How updates are handled in Microsoft Managed Desktop - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/updates?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/managed-desktop/service-description/updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/updates.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@v-etmon - Thank you for pointing this out.

This issue has been resolved based on this merged https://github.com/MicrosoftDocs/microsoft-365-docs/commit/91b420993fd582d0c966823326d1c442b5360a6e.


Thank you and we appreciate your contribution to make the docs better!
