### ISSUE TITLE
missing device name from return

### ISSUE THREAD

**Issue by nalhemyariirexorg** [MicrosoftDocs/microsoft-365-docs#12896]
i'm running the api, but the results are missing DeviceName | string | Fully qualified domain name (FQDN) of the device.

I results are returning all the remaining properties but device name, also deviceid does not look familiar, i can't match it in AzureAD or Intune to any device in my tenant?

</body>
</html>
[Enter feedback here]
i'm running the api, but the results are missing DeviceName | string | Fully qualified domain name (FQDN) of the device.

I results are returning all the remaining properties but device name, also deviceid does not look familiar, i can't match it in AzureAD or Intune to any device in my tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43823bda-b13a-d6a9-9e08-ff4482bed785
* Version Independent ID: 43823bda-b13a-d6a9-9e08-ff4482bed785
* Content: [Export browser extensions assessment](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api/get-assessment-browser-extensions?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/api/get-assessment-browser-extensions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/api/get-assessment-browser-extensions.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @nalhemyariirexorg Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
