### ISSUE TITLE
Outdated license requirements?

### ISSUE THREAD

**Issue by TobiasAT** [MicrosoftDocs/microsoft-365-docs#12895]
Is this really true? 

> Loop workspaces currently require each user to have an Exchange Online license

1. Loop Workspaces are backed by Syntex repository services, which is powered by SharePoint. Why an Exchange Online license instead of a SharePoint Plan?
2. Recently you added a Microsoft Loop (Workspaces) service plan to M365 E5, E3, Business Premium and Business Standard licenses. I can also enable the Loop service plan even if Exchange or SharePoint service plan is disabled. 

It seems the license information on that page are outdated.

Best regards
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 093c11ef-791c-c4bd-71e6-c3e6ecc347e1
* Version Independent ID: 093c11ef-791c-c4bd-71e6-c3e6ecc347e1
* Content: [Manage Loop workspaces in Syntex repository services](https://learn.microsoft.com/en-us/microsoft-365/loop/loop-workspaces-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/loop/loop-workspaces-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/loop/loop-workspaces-configuration.md)
* Service: **sharepoint-online**
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

**Comment by TobiasAT** [comment]
@msbemba Thanks for the update. I quickly read the updated change. I think the "Loop with workspaces service plan" is just called "Microsoft Loop". 

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/7470044/d657a73f-595c-44e2-950d-d90265a2b4ce)

I also tested the impact if I disable the service plan. Then users get the information they have no Loop license and are in grace period, if they open Loop Workspace on the web. 

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/7470044/b231cf0a-abf8-45bd-a84a-8b94b4f2ad80)

I'm pretty sure either the service plan is not named correctly, or the official service plan is named just Microsoft Loop. 

Best regards
Tobias

**Comment by TobiasAT** [comment]
Updates about the license requirements? The documentation still mentions the Exchange Online license requirement.

**Comment by msbemba** [comment]
@yogkumgit and @TobiasAT We are still awaiting approval from author to merge the PR
