### ISSUE TITLE
Description is NOT clear

### ISSUE THREAD

**Issue by ddobric** [MicrosoftDocs/microsoft-365-docs#12891]
On this page, we should do the following:

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/1756871/ebf81744-3c22-44e6-8647-ad5632748742)

After the step 2, we do not see "other options"
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/1756871/f93201c6-35ab-4d08-aa0e-35f9bc8bd308)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 124f5536-4792-2800-8751-88c96d007fc8
* Version Independent ID: 124f5536-4792-2800-8751-88c96d007fc8
* Content: [Create a content center in Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/create-a-content-center)
* Content Source: [microsoft-365/syntex/create-a-content-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/create-a-content-center.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@ddobric -- Thank you for the feedback. We'll review and make updates as needed. Thanks again.

**Comment by chuckedmonson** [comment]
@seansquires -- Would you please review this feedback and advise? Thank you.

**Comment by chuckedmonson** [comment]
@ddobric -- thank you for the feedback. The article has been updated for now. An updated experience will be rolling out in a couple of weeks that might have additional updates. Thanks again.
