### ISSUE TITLE
URL Rewrite

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/microsoft-365-docs#1289]
Hello,

Please add more details regarding what Safe Links actually does. It is unclear from these articles what is meant by the phrase "rewrite URL". I also appears that behavior may have changed in the past year. Are protected links obfuscated? What do rewritten URLs look like? Will users be able to see the original URL? Is there a way to have Safe Links enabled without links being rewritten? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1541da6f-af9a-05d5-fa34-b1a5df61424f
* Version Independent ID: 88e111ed-67f7-41bc-d823-863ee7ea2a2e
* Content: [Set up Office 365 ATP Safe Links policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@ckssaas Thank you for the feedback. we have created a PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1455 to update the document. Meanwhile, we cannot have safe links enabled without having the URL rewritten.

Thanks
Sri

**Comment by mypil** [comment]
@ckssaas - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/a5846d0b29a63c28501b022046006a26eb015eb4. 


Thank you for your contribution to make the docs better! Much appreciated!
