### ISSUE TITLE
Submitting emails

### ISSUE THREAD

**Issue by onsite-insights** [MicrosoftDocs/microsoft-365-docs#12900]
I have submitted a valid email address multiple times and it continues to come back back "Should have been blocked". Need to just be able to white list something, it should not be so difficult.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Manage submissions](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-admin?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submissions-admin.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-admin.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
@onsite-insights, when you [do the submission](https://learn.microsoft.com/microsoft-365/security/office-365-security/submissions-admin#report-good-email-to-microsoft), do you select the **Allow emails with similar attributes** setting so an allow entry for the sender is created in the Tenant Allow/Block List?

**Comment by onsite-insights** [comment]
Hello - yes indeed, I have also supplied the reason in the comments section.

**Comment by chrisda** [comment]
@onsite-insights, your best way forward is to open a support ticket about this.
