### ISSUE TITLE
What additional heuristics does priority tagging get you?

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#12909]
"Priority account protection offers additional heuristics that are tailored to company executives that don't benefit regular employees. Priority account protection is better suited to the mail flow patterns of company executives based on extensive data from the Microsoft datacenters."

Customer has asked me what these additional protections are - can we elaborate on this?

The blog announce here: https://techcommunity.microsoft.com/t5/microsoft-365-blog/using-priority-accounts-in-microsoft-365/ba-p/1873314 also doesn't seem to reveal anything and just links back to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b896cae-3d32-b4ac-63c2-9289eeb0ea3e
* Version Independent ID: 2b896cae-3d32-b4ac-63c2-9289eeb0ea3e
* Content: [Configure and review priority account protection in Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/priority-accounts-turn-on-priority-account-protection?view=o365-worldwide#review-differentiated-protection-from-priority-account-protection)
* Content Source: [microsoft-365/security/office-365-security/priority-accounts-turn-on-priority-account-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/priority-accounts-turn-on-priority-account-protection.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
@chrislehr, we can give too much detail without providing a roadmap for attackers. The existing statements are about as far as we're going to go. The key point is "different" protection; not "better" or "more substantial"; just better suited to executives.

**Comment by yogkumgit** [comment]
@chrislehr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
