### ISSUE TITLE
Seeking Clarification: Impact of having both billing models configured

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#12905]
Given that some features are per-seat and some are only for pay-as-you-go, what would the impact be for those that have _both_ licensing/billing models implemented?

According to the Message Center post in the M365 Admin Center (https://admin.microsoft.com/?source=applauncher&ref=MessageCenter/:/messages/MC666614), the "Taxonomy Tagging" feature should be fully rolled out by now, but we are not seeing it in Setup. Could this be because, even though we have configured pay-as-you-go billing, we still have per-seat licenses assigned to users?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a755140b-0f04-a452-cfc7-adf7b67fa81f
* Version Independent ID: a755140b-0f04-a452-cfc7-adf7b67fa81f
* Content: [Licensing for Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/syntex-licensing)
* Content Source: [microsoft-365/syntex/syntex-licensing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/syntex-licensing.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@sparkitect -- Thank you for letting us know. Please let me look into this and I'll get back you.

**Comment by sparkitect** [comment]
In case it helps: Though we have definitely used some Syntex features since configuring pay-as-you-go roughly a month ago, we've yet to see a single cent billed in the Cost Analysis area of the configured Resource Group in Azure.

**Comment by chuckedmonson** [comment]
@sparkitect -- It looks like taxonomy tagging is still rolling out. You will be able to see the service when it gets completely rolled. Thanks for checking, and I regret the delay.
