### ISSUE TITLE
IP range for Teams clients (Direct routing use-cases)

### ISSUE THREAD

**Issue by ajeob** [MicrosoftDocs/microsoft-365-docs#12903]
Hello,

I send you this request as we saw in the past months that the Microsoft Teams Direct Routing related FQDNs for SIP PSTN Hubs are now resolved with 52.112.0.0/14 as previously, but also with 52.122.0.0/15 subnet IP addresses:
 
https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan#microsoft-365-office-365-and-office-365-gcc-environments
> The FQDNs sip.pstnhub.microsoft.com, sip2.pstnhub.microsoft.com, and sip3.pstnhub.microsoft.com are resolved to IP addresses from the following subnets:
> 
>     52.112.0.0/14
>     52.122.0.0/15
The media IP and ports ranges did not change:
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/126698102/1edb672c-3388-49fd-9b80-ae8c6b1b7d80)

We don't have the history of the related change on the current page for which I'm sending this request, but we are wondering if there is any mistake for the Teams clients to also use 52.122.0.0/15 instead of 52.120.0.0/14 previously ? 
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/126698102/cb9517da-ae9d-47f2-a5cb-eae3f87fc759)

If yes, may we ask to edit the page with the exact subnet for clients?

Thank you for your support,
best regards,
Anthony

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@ajeob We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).
