### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by reetij** [MicrosoftDocs/microsoft-365-docs#12918]
1.The below statement should read when Antivirus real-time protection is **not** enabled? seems "not" has been missed in error ? and are we suggesting EDR in block mode should be enabled along side Microsoft Defender Antivirus real-time protection (i.e. AV in active mode?) to get full benefits of real-time protection.
Important:

EDR in block mode does not provide all the protection that is available when Microsoft Defender Antivirus real-time **protection is enabled.** Some capabilities that depend on Microsoft Defender Antivirus to be the active antivirus solution will not work, such as the following examples:

======================

2. The Video on this page is misleading, are we recommending EDR in block mode should always be enabled irrespective of Defender AV in Active and Passive mode? Customers are thinking they are missing out on blocking if EDR block mode is not enable where Defender AV is primary. It also contradicts the other FAQ which suggests turning on EDR in block mode when Defender AV is passive and there is little benefit (what are those benefits?) when Defender AV is in active mode.

Do I need to turn EDR in block mode on if I have Microsoft Defender Antivirus running on devices?
The primary purpose of EDR in block mode is to remediate post-breach detections that were missed by a **non-Microsoft** antivirus product. There is minimal benefit in enabling EDR in block mode when Microsoft Defender Antivirus is in active mode, because real-time protection is expected to catch and remediate detections first. We recommend enabling EDR in block mode on endpoints where Microsoft Defender for Antivirus is running in **passive** mode. EDR detections can be automatically remediated by [PUA protection](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus?view=o365-worldwide) or by [automated investigation & remediation capabilities](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/automated-investigations?view=o365-worldwide) in block mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba0e285e-07c9-e98f-d96b-668a82b4b9fa
* Version Independent ID: 52fde7e4-0362-eb32-712d-f3e718836232
* Content: [Endpoint detection and response in block mode](https://learn.microsoft.com/en-gb/microsoft-365/security/defender-endpoint/edr-in-block-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/edr-in-block-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/edr-in-block-mode.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@reetij Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12923

Once the author approves, the changes will be live.


Regarding EDR in block mode, I will let the author @denisebmsft  respond about the video and make changes if need be.

Thanks
Sri
