### ISSUE TITLE
PowerShell?

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/microsoft-365-docs#1291]
No PowerShell option? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b5bbb4-4c14-9637-6834-02f0e3e95261
* Version Independent ID: da93570d-ecbc-d0c3-63c2-7445f7ba29b3
* Content: [Configure end-user spam notifications in Exchange Online - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-exchange-online?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-exchange-online.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-exchange-online.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@ckssaas Thank you for your feedback. We have added a reference to the more information section now via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1299

You can check the Document:- https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/set-hostedcontentfilterpolicy?view=exchange-ps to use Powershell.

Thanks
Sri

**Comment by mypil** [comment]
@ckssaas - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit [xxxx]. 


Thank you for your contribution to make the docs better! Much appreciated!

https://github.com/MicrosoftDocs/microsoft-365-docs/commit/7487707a82d1f6619a7e57752c142f6fc7267fd1
