### ISSUE TITLE
PowerShell/Graph API support?

### ISSUE THREAD

**Issue by viperthunder** [MicrosoftDocs/microsoft-365-docs#12924]
Many Microsoft Learn pages like this demonstrate ways to perform the same action using PowerShell or Graph API. Is it possible to perform the "Wipe Company Data" action from devices which are registered in Basic Security and Mobility using other methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90e5b93e-9372-b489-55f4-ac6dd72fa2e3
* Version Independent ID: b3f1e27e-655b-63d2-b42d-94994fec2370
* Content: [Wipe a mobile device in Basic Mobility and Security - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/basic-mobility-security/wipe-mobile-device?view=o365-worldwide)
* Content Source: [microsoft-365/admin/basic-mobility-security/wipe-mobile-device.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/basic-mobility-security/wipe-mobile-device.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@viperthunder Thank you for your feedback. Currently, the steps mentioned in the document are the only way to  Wipe a mobile which are registered in Basic Security and Mobility.

We will update the document once other methods are made available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @viperthunder Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
