### ISSUE TITLE
Wrong Description

### ISSUE THREAD

**Issue by AdrianJe** [MicrosoftDocs/microsoft-365-docs#12928]
In the User Activity Table, the descriptions for "Projects visited (Web)" and "Tasks created (Web)" are the same -- they both talk about the number of tasks created.  It seems that the description for the first should be the number of projects visited.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88b68222-3eac-0447-de7f-9b7ba70f1794
* Version Independent ID: 88b68222-3eac-0447-de7f-9b7ba70f1794
* Content: [Microsoft 365 admin center Project activity  - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/project-activity?view=o365-worldwide#interpret-the-project-activity-report)
* Content Source: [microsoft-365/admin/activity-reports/project-activity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/project-activity.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@AdrianJe Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12961

Once the author approves, the changes will be live.

Thanks
Sri
