### ISSUE TITLE
Is this available in GCCH? 

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/microsoft-365-docs#12936]
Can you please confirm if this is available in GCCH? If not, can you please note that in the documentation. 

Thank you. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 468f3403-e851-cda8-e37d-5774afd99b82
* Version Independent ID: 468f3403-e851-cda8-e37d-5774afd99b82
* Content: [Automatic attack disruption in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/automatic-attack-disruption?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/automatic-attack-disruption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/automatic-attack-disruption.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @diannegali
* Microsoft Alias: **diannegali**

**Comment by msbemba** [comment]
@J227668 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12969

Once the author approves, the changes will be live.

Thanks
Sri
