### ISSUE TITLE
Add Defender for Business to Requirements

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/microsoft-365-docs#12934]
On this page, on the requirements section it says "Defender for Endpoint Plan 1 and Plan 2 (standalone or as part of other Microsoft 365 plans)"

As far as I know, Defender for Business license (which is also available as part of Business Premium) also allows onboarding devices to the Defender for Endpoint service

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide#licensing-requirements)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by JMCA2** [comment]
related to https://github.com/MicrosoftDocs/memdocs/issues/4281

**Comment by JMCA2** [comment]
Defender for Business is listed on https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide

**Comment by denisebmsft** [comment]
Hello @JMCA2. Thank you for the feedback. The article has been updated and the changes should be live at around 4 p.m. Pacific Time today. Links like this one (https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-requirements?view=o365-worldwide) were added to the article. Thanks again, and I hope you have good rest of the day!

**Comment by JMCA2** [comment]
@denisebmsft Here you added "Defender for Business" to the list of licenses in "Defender for Endpoint" requirements.
Do you know if that also means using that using in Intune the "Defender for Endpoint Security Baseline" with "Defender for Business" license is supported?

I've been trying to get a definitive answer to this on https://github.com/MicrosoftDocs/memdocs/issues/4281 but no one responds, and Microsoft Support has not been very helpful.

Thanks

@mjcaparas
