### ISSUE TITLE
Links no longer valid. Correct Links attached

### ISSUE THREAD

**Issue by helreg** [MicrosoftDocs/microsoft-365-docs#12940]
Hi, 
I noticed that in the FAQ page, the links for the latest WindowsDefender.adml and WindowsDefender.admx files are no longer valied and have moved here respectively:
https://github.com/microsoft/mdatp-devicecontrol/blob/main/WindowsDefender.adml
https://github.com/microsoft/mdatp-devicecontrol/blob/main/WindowsDefender.admx
Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e25dc43-2f77-8f76-c532-e22836c3b8af
* Version Independent ID: 8e25dc43-2f77-8f76-c532-e22836c3b8af
* Content: [Printer Protection frequently asked questions](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/printer-protection-frequently-asked-questions?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/printer-protection-frequently-asked-questions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/printer-protection-frequently-asked-questions.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @nimishasatapathy
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@helreg Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12958

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by helreg** [comment]
Hi,
Hope you are well.
First of all the changes I have reported have not been changed.
You mentioned “Closed #12940 as completed via #12958.”. #12958 This is different than what I reported, likely something similar but in a different part of the site.

In hindsight maybe my explanation was too detailed but this is so poorly documented and a lot of people are struggling that I believe is very important.

So let’s try to break down this and simplify.
For case:
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12940
On this page:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/printer-protection-frequently-asked-questions?view=o365-worldwide
Under the question/section “Why is there no configuration UX for some policy groups?” the links for the WindowsDefender.adml and WindowsDefender.admx files are wrong.
Should be
respectively:
https://github.com/microsoft/mdatp-devicecontrol/blob/main/WindowsDefender.adml
and
https://github.com/microsoft/mdatp-devicecontrol/blob/main/WindowsDefender.admx

For case:
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/12953
In the page “Deploy and Manage Using Group Policy”
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-and-manage-using-group-policy?view=o365-worldwide
In the section "Deploy using group policy" if you scroll down a bit to the first Note it says "If you don't see this group policy objects, you need to add the group policy administrative template. You can download administrative template (WindowsDefender.admx and WindowsDefender.admx) from samples". The correct link for both samples is
https://github.com/microsoft/mdatp-devicecontrol/tree/main

NOTE: I’ll likely report other issues as I am going over all the documentation but in the meantime thanks in advance.

Helder Registo | End User Services Engineer
T:  +44 161 521 1301<tel:+44%20161%20521%201301>
[interactive investor]<http://www.ii.co.uk/>
About interactive investor
interactive investor (ii) is the UK's number one flat-fee investment platform, offering ISA, SIPP, Junior ISA and general investing accounts, plus leading investment content, tools, choice and service. Customers pay a flat monthly fee, even as their investments grow, meaning they keep more of their money. interactive investor is an award-winning platform and proud to be rated ‘Excellent’ on Trustpilot. ii is authorised and regulated by the Financial Conduct Authority and FSCS protected.

**Comment by msbemba** [comment]
@helreg Thank you for your feedback. We have made the changes as exactly per your suggestion. The reason why you are not seeing this live is because the changes could take 24-48 hours to reflect in the document.

Thanks
Sri

**Comment by helreg** [comment]
Hi,
Thanks for letting me know.
I can see the changes have been updated on the page.
Thank you.

Helder Registo | End User Services Engineer
T:  +44 161 521 1301<tel:+44%20161%20521%201301>
[interactive investor]<http://www.ii.co.uk/>
About interactive investor
interactive investor (ii) is the UK's number one flat-fee investment platform, offering ISA, SIPP, Junior ISA and general investing accounts, plus leading investment content, tools, choice and service. Customers pay a flat monthly fee, even as their investments grow, meaning they keep more of their money. interactive investor is an award-winning platform and proud to be rated ‘Excellent’ on Trustpilot. ii is authorised and regulated by the Financial Conduct Authority and FSCS protected.
