### ISSUE TITLE
Section detailing "Allow" is under "Block" heading

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/microsoft-365-docs#12947]
Under section:
https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure#create-block-entries-for-domains-and-email-addresses

**Create block entries for domains and email addresses**

There is a paragraph talking about discussing allowed, which is not the subject of this section:

_By default, allow entries for domains and email addresses exist for 30 days. During those 30 days, Microsoft learns from the allow entries and [removes them or automatically extends them](https://techcommunity.microsoft.com/t5/microsoft-defender-for-office/automatic-tenant-allow-block-list-expiration-management-is-now/ba-p/3723447). After Microsoft learns from the removed allow entries, messages that contain those entities are delivered, unless something else in the message is detected as malicious. By default, allow entries for spoofed senders never expire._

This paragraph should be in the section above it:

**Create allow entries for domains and email addresses**

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/66257685/b56d0768-e7b7-4bb1-960b-94aee5c859b3)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9b787f-def1-bbc5-48ca-42180f9560d2
* Version Independent ID: 3d9b787f-def1-bbc5-48ca-42180f9560d2
* Content: [Allow or block email using the Tenant Allow/Block List](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list-email-spoof-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mntorq, thanks for the catch. Actually, that same text is already in the third item in the purple Note, so instead of moving it as you described, I simply removed it from the block section.

Thanks for the feedback.

Closing
