### ISSUE TITLE
No information on the block option

### ISSUE THREAD

**Issue by neschram** [MicrosoftDocs/microsoft-365-docs#12955]
Can you please add information on what the block option actually does? From my seat, it appears to do absolutely nothing.

**Comment by yogkumgit** [comment]
@neschram Please indicate the document you are referring to and wish to give the feedback for its improvement. Thanks

**Comment by neschram** [comment]
@yogkumgit My apologies, for some reason I thought the page was included from the feedback link. But, I found the page with documentation on the block option. It appears I didn't look hard enough before submitting.
