### ISSUE TITLE
information about inserting sender property variables is missing

### ISSUE THREAD

**Issue by dunavitex** [MicrosoftDocs/microsoft-365-docs#12954]
information about inserting sender property variables is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a984a46-1f7b-6ef1-71f3-c5df6c142c01
* Version Independent ID: 4fab7da3-c9ae-0136-c693-ae99c1090f40
* Content: [Create organization-wide signatures and disclaimers - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/create-signatures-and-disclaimers?view=o365-worldwide#create-a-signature-that-applies-to-all-messages)
* Content Source: [microsoft-365/admin/setup/create-signatures-and-disclaimers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/create-signatures-and-disclaimers.md)
* Service: **microsoft-365-business**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@dunavitex Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/12973

Once the author approves, the changes will be live.

Thanks
Sri
