### ISSUE TITLE
Localized article (ja-jp)  is no longer displayed

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/microsoft-365-docs#1295]
I remember a few weeks ago there was a localized article about Microsoft 365 compliance. I was looking at a Japanese translated article (ja-jp), but for now it is redirected to an English article.

Are you having any problems?
Or are literal translation articles abolished?

Localized articles are important to non-English speaking users and we want them to be viewable.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/ja-jp/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by kefujino** [comment]
At the moment, you can see localized articles as before.
It may have been a temporary problem.

Please close it because it has been resolved.

**Comment by markjjo** [comment]
@kefujino Thanks for following up. Glad that issue resolved itself.
