### ISSUE TITLE
Why are you showing the process for GoDaddy instead of providing instructions that work for all registrars? 

### ISSUE THREAD

**Issue by michaelkuzmin** [MicrosoftDocs/microsoft-365-docs#12966]
The page is missing instructions on how to add a domain that is NOT registered with GoDaddy. Why are you pushing this particular registrar? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0012093-49ca-c2f6-a3f3-4e4252fca609
* Version Independent ID: 22784dda-ff03-971b-4d6e-5b0152f62942
* Content: [Add a domain to Microsoft 365 - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/add-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-domain.md)
* Service: **microsoft-365-business**
* GitHub Login: @nataliekagole
* Microsoft Alias: **nkagole**

**Comment by DMoenks** [comment]
The page might be missing **video** instructions for other DNS registrars, but all the information needed to configure DNS records for domain verification are stated in the text, including a list of other domain registrars supporting automatic configuration
Just selecting a possibly random registrar for an exemplary configuration video doesn't make that registrar any better or worse than the others or "push" its services. Providing the same video twice, showing automatic DNS configuration with another registrar, wouldn't provide any additional information from a technical perspective. Providing another video showing manual DNS configuration with another registrar would be heavily registrar-dependent though, possibly limiting its usefulness...

From an administrator's perspective, I actually find the article useful the way it is. I receive information on the possibility of automatic configuration, including a list of compatible providers and a video example, and steps on how to complete the manual configuration

**Comment by msbemba** [comment]
@michaelkuzmin Thank you for your feedback. The instructions stated in the text are accurate and work for all other registrars mentioned in the document as well. If you are referring to the video, We have given an example with Go daddy.

Hope this helps!

Thanks
Sri
