### ISSUE TITLE
Safe Docs sample files missing

### ISSUE THREAD

**Issue by johnkevinuy** [MicrosoftDocs/microsoft-365-docs#12962]
Hello,

Reporting that the links to the three files used to test the Safe Docs feature are missing. Clicking on them results in a 404 page not found in Github. Please help restore the links to the missing files as they're needed to demo Safe Docs feature to a customer of mine. Thank you.

Regards,
Kevin Uy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-documents-in-e5-plus-security-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-documents-in-e5-plus-security-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-documents-in-e5-plus-security-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@johnkevinuy, yes. The files were recently moved to the download center:

  - https://download.microsoft.com/download/1/9/7/19774467-5ff1-4c4d-9224-27b3751fa58f/SafeDocsDemo.docx
  - https://download.microsoft.com/download/b/e/f/bef1df26-2c91-45b3-b8d0-348c6fead4af/SafeDocsDemo.pptx
  - https://download.microsoft.com/download/d/1/5/d1547fa8-575b-4ae0-969c-0d5265f6d985/SafeDocsDemo.xlsx
 
I updated the article accordingly.

Thanks for the feedback.

Closing

**Comment by johnkevinuy** [comment]
@chrisda Thanks for the quick turnaround. FYI, I attempted to download and open all three files on my corporate Microsoft device but noticed that they simply opened up in protected view and presented the option for "Enable Editing". Is this the expected behavior? I anticipated seeing the banner that MDE/ATP is attempting to scan the file before declaring it's safe to open in edit mode...

**Comment by chrisda** [comment]
@johnkevinuy, if Safe Documents is available n turned on, you should get a warning message. Whether or not you can click through to view/edit is dependent on that second setting. I have no idea how corporate Microsoft is configured.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/33166947/6c1eb2c0-5053-4ab1-a229-b9fbd3205b90)

**Comment by johnkevinuy** [comment]
@chrisda Noted, thank you.
