### ISSUE TITLE
Bug in the way buffer time works?

### ISSUE THREAD

**Issue by AlexMIB13** [MicrosoftDocs/microsoft-365-docs#12967]
Hi,

We are using outlook Bookings with me for some months, for all our Sales in the company, and everything was great for now.
Starting Monday 9th October, we are experiencing some issues with the way Buffer Time works.
Indeed, our Sales used to plan a buffer time before and after a meeting, and before 9th October, it was ok, buffer time was just for them and customers didn't see anything.
Now, the buffer time is included in the meeting.
For example, if a meeting is 30 min, and buffer time is 15 mn before and 15 mn after, the email received by Sales and customer will mention 30 mn, but the event in the agenda is 60 min...  

Any idea what's wrong?
Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07dc8679-b516-3935-85f2-4d849de28905
* Version Independent ID: 02c5529f-28fd-ad68-0b3b-e3b3fb72cc97
* Content: [Set Bookings buffer time](https://learn.microsoft.com/en-us/microsoft-365/bookings/set-buffer-time?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/set-buffer-time.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/set-buffer-time.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@AlexMIB13 Thank you for your feedback. This looks like a technical bug, I'd recommend you contact support via the need help section on the admin center, so the support engineer can fix or escalate accordingly.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AlexMIB13 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
