### ISSUE TITLE
Inconsistent Vales for Bulk Email Threshold

### ISSUE THREAD

**Issue by AaronKingery** [MicrosoftDocs/microsoft-365-docs#12975]
<https://learn.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies#policies-in-preset-security-policies>

Indicates the Bulk Mail threshold level differently than this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58067ff3-737e-441e-1812-a50bdb97d832
* Version Independent ID: fa3aba35-e8d9-cff6-13c2-1c892c3f2cc4
* Content: [Bulk complaint level values](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-bulk-complaint-level-bcl-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-bulk-complaint-level-bcl-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-bulk-complaint-level-bcl-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@AaronKingery, Standard = 6, Strict = 5 is correct, so I updated the Preset security policies article.

Thanks for the feedback.

Closing
