### ISSUE TITLE
URL redirects to Defender homepage

### ISSUE THREAD

**Issue by mayday175** [MicrosoftDocs/microsoft-365-docs#12976]
The link provided in the line...
Go to the [Data export settings page](https://security.microsoft.com/interoperability/dataexport) in the Microsoft Defender portal.
... does not work as intended. The provided URL https://security.microsoft.com/interoperability/dataexport redirects to https://security.microsoft.com/ and I am unable to locate the "Data export settings" page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba39bf0-881d-fcdc-4c5c-13037a6f38ed
* Version Independent ID: 6ba39bf0-881d-fcdc-4c5c-13037a6f38ed
* Content: [Stream Microsoft Defender for Endpoint events to Azure Event Hubs](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api/raw-data-export-event-hub?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/api/raw-data-export-event-hub.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/api/raw-data-export-event-hub.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@mayday175 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13016

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by mayday175** [comment]
I see no difference when testing this change earlier today... the link provided momentarily takes me to https://security.microsoft.com/securitysettings/defender/raw_data_export then a moment later reverts to the Defender root page. 

However, I have recently learnt that the "raw data streaming" feature (that these instructions describe how to configure) is a preview feature... preview features must be enabled for the Defender tenant in order for your updated link to work. I followed instructions here https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-preview?view=o365-worldwide to enable preview features. 

Accessing the URL https://security.microsoft.com/securitysettings/defender/raw_data_export now works ok. And, following the original link https://security.microsoft.com/interoperability/dataexport now redirects me to https://security.microsoft.com/securitysettings/defender/raw_data_export of too.

I recommend a reference to enabling preview features be added to the "Before you begin" paragraph; this will save the next reader the confusion described above.
