### ISSUE TITLE
Some examples would be good

### ISSUE THREAD

**Issue by JimmyEdgar** [MicrosoftDocs/microsoft-365-docs#12982]
This page would be useful if some examples were given on how to use the commands detailed. Otherwise - how do you use them?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62ab7809-9202-5fce-7b0a-ff090a920ce5
* Version Independent ID: 62ab7809-9202-5fce-7b0a-ff090a920ce5
* Content: [Manage Folders and Rules feature in Microsoft 365 Groups - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/manage-folders-and-rules-feature?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/manage-folders-and-rules-feature.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-folders-and-rules-feature.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@JimmyEdgar Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13043

Once the author approves, the changes will be live.

Thanks
Sri
