### ISSUE TITLE
Permissions for Compliance Center

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1298]
Please make it easier to find this page https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-microsoft-365-compliance-security?view=o365-worldwide. It does not show up in the table of contents on the left side navigation nor is it referenced on the main landing pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e5d5245-ece6-6430-9221-efa0d80b9f6e
* Version Independent ID: 2ad2ab98-14c8-4f5c-70de-6c809f9d8933
* Content: [What's new in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @brendonb
* Microsoft Alias: **brendonb**

**Comment by get-itips** [comment]
Hello @chrisda Chris, as a frequent editor of both these articles and also as an assigned author of one of them.

The article that @DeanGross Dean references

[Permissions in the Microsoft 365 compliance center and Microsoft 365 security center](https://docs.microsoft.com/microsoft-365/security/office-365-security/permissions-microsoft-365-compliance-security?view=o365-worldwide)

 is very similar to this one 

[Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide)

The latter, has a link in the TOC and it seems it was made based on the Office 365 Security & Compliance admin center and the first one seems it was made with the new homes for Microsoft 365 security and compliance (when the admin centers were separated) in mind.

Should we also add this one to TOC? should we maintain only one?

I appreciate.

**Comment by chrisda** [comment]
OK. Added missing topic to the TOC. Thanks for the feedback.

Closing
