### ISSUE TITLE
Remediation required version did not exist 

### ISSUE THREAD

**Issue by PeterCheungHK** [MicrosoftDocs/microsoft-365-docs#12985]
Description
Update 7-zip to a later version 23.1.0.0 to mitigate 2 known vulnerabilities affecting your devices.

7zip did not have 23.1.0 only have 23.01

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7f01da1-17e3-c78e-1f9c-4c11dbf1b291
* Version Independent ID: e7f01da1-17e3-c78e-1f9c-4c11dbf1b291
* Content: [List of fixed customer reported inaccuracies](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/fixed-reported-inaccuracies?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/fixed-reported-inaccuracies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/fixed-reported-inaccuracies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@PeterCheungHK Thank you for your feedback. I don't see "Update 7-zip to a later version 23.1.0.0 to mitigate 2 known vulnerabilities affecting your devices" in this document. If you are referring to this alert on the admin center, I'd recommend you to contact support via the need help section on the admin center, so that the engineer can fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PeterCheungHK Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
