### ISSUE TITLE
What is meant by a panel action?

### ISSUE THREAD

**Issue by SylvM1** [MicrosoftDocs/microsoft-365-docs#12986]
Please update this page to include what is meant by a panel action. This term is used throughout the page and doesn't have a definition. This makes what we see in the usage reports unusable in my opinion. Please add this. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86e5dec5-c503-834b-9c2c-78a47d192fc6
* Version Independent ID: 86e5dec5-c503-834b-9c2c-78a47d192fc6
* Content: [Microsoft 365 admin center Teams usage activity reports - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft-teams-usage-activity?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/microsoft-teams-usage-activity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft-teams-usage-activity.md)
* Service: **microsoft-365-business**
* GitHub Login: @camillepack
* Microsoft Alias: **camillepack**

**Comment by msbemba** [comment]
@SylvM1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13018

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by SylvM1** [comment]
Hi Sri,

Thank you so much for the swift response. I'll be awaiting your confirmation.

With kind regards,

Sylvester
