### ISSUE TITLE
Limitations of isolate device

### ISSUE THREAD

**Issue by takuyatamaki** [MicrosoftDocs/microsoft-365-docs#12980]
[Enter feedback here]
I have configured isolate using custom detection.
Medium and High alerts can isolete terminals.
Low and Informational alerts cannot isolate a terminal.

I think this is a limitation of MDE.
Is it possible to include this in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbf510e0-742e-fce6-787e-18eb8a22f42d
* Version Independent ID: 23b77843-cf19-aacb-47af-1f51792c76a0
* Content: [Create and manage custom detection rules in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/custom-detection-rules?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/custom-detection-rules.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/custom-detection-rules.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@schmurky Thank you very much for sharing this explanation. @takuyatamaki Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
