### ISSUE TITLE
Can this be used for intra-tenant migraitons as well?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#12984]
Is there anything explicitly preventing this tool from being used to migrate content from one site to another site within the same tenant?

Large scale restructuring of SPO quickly hits the limits of the browser:
https://support.microsoft.com/en-us/office/move-or-copy-files-in-sharepoint-00e2f483-4df3-46be-a861-1f5f0c1a87bc

So it would be good to know if we could use this as a "back end" IT tool for rearranging SPO files withing a tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f025da8-8287-f98b-2167-5af04cabb254
* Version Independent ID: 7f025da8-8287-f98b-2167-5af04cabb254
* Content: [Cross-tenant SharePoint site migration overview (preview) - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-sharepoint-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-sharepoint-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-sharepoint-migration.md)
* Service: **microsoft-365-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by msbemba** [comment]
@Mike-Crowley Thank you for your feedback. This sounds more like a feature request and needs to be on the main feedback portal - https://feedbackportal.microsoft.com/ so that our product group or developers can directly respond back to you.

Hope this helps!

Thanks
Sri

**Comment by Mike-Crowley** [comment]
This is not a feature request, as I am not requesting a feature. I am asking if it is possible to use the tool in a specific way. If the answer is NO, then I can see how you would redirect me to create a feature request.

**Comment by msbemba** [comment]
Yes, This feature is not available for the same tenant. However, only the Product group can confirm if this is possible in the future or if there is a reason why this is not possible.

Hope this helps!

Thanks
Sri

**Comment by Mike-Crowley** [comment]
Thanks for clarifying!
