### ISSUE TITLE
Documentation does not match Production UI. 

### ISSUE THREAD

**Issue by erihnbapsjfdb** [MicrosoftDocs/microsoft-365-docs#12989]
Hello, 

It appears the documentation is out of date and does not match the UI of security.microsoft.com. 

Specifically, the following section. 
Options for Microsoft reporting tools:
```
Outlook section > Select an Outlook report button configuration section > When the Report button is clicked:

Show a pop-up message before email is reported: Select this setting to show users a pop-up notification in Outlook before they report a message.

To customize the text in the notification, select Customize before message. In the flyout that opens, enter the text in the Title and Message boxes. Use the variable %type% to include the submission type (junk, not junk, phishing, etc.). When you're finished in the flyout, select Confirm.

```

There is no longer an option to customize the pre-submission pop-up, only a checkbox. (With no customize link) "Ask the user to confirm before reporting." 
(Although previously configured messages are still being presented to our users.)

It would be nice if the documentation was kept up to date when product changes are made. Alas, this is a pipe dream. 
Anyways, I would greatly appreciate it if you could review this document for accuracy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User reported settings](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-configure-the-user-submissions-mailbox-for-email)
* Content Source: [microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submissions-user-reported-messages-custom-mailbox.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@erihnbapsjfdb, funny you should ask. I had updates sitting in the bullpen ready to go. I just got the greenlight to publish.

Thanks for the feedback.

Closing
