### ISSUE TITLE
Update order of precedence

### ISSUE THREAD

**Issue by JXG2300** [MicrosoftDocs/microsoft-365-docs#12999]
The numbers on the point below should be 5 and 6, based on the table above.

The message is identified as spoofing, because spoofing (4) is evaluated before user impersonation (5) in the order of processing for the email protection type.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4194fdd-c5de-d424-319a-5e83774b36c2
* Version Independent ID: 83997ad4-a9bd-146e-5da0-8022458cf3ea
* Content: [Order and precedence of email protection](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JXG2300, fixed.

In the future, you too can make changes like this directly. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md). 

Thanks for the feedback.

Closing
