### ISSUE TITLE
Canvas LTI with One drive is not working properly

### ISSUE THREAD

**Issue by ganeshubhare** [MicrosoftDocs/microsoft-365-docs#12990]
Hello,
I have found a bug in the . They setup is done correctly but when the students makes changes to the document and saves the copy each time they make a change only the first version which was saves is shown . Although it creates different versions of documents for each change . Student and teacher only sees the first version

**Comment by yogkumgit** [comment]
@ganeshubhare Please indicate which document you are referring to and what is your feedback. Thanks

**Comment by ganeshubhare** [comment]
Hi Yogesh,
Sorry! But it seems i have accidently raised this query under my personal account rather than company account. Is it possible to switch this to my ***@***.*** account? so I receive all the communication on my company email address?
ThanksGanesh
    On Friday, 20 October 2023 at 14:21:02 BST, Yogesh Kumar ***@***.***> wrote:  
 
 


@ganeshubhare Please indicate which document you are referring to and what is your feedback. Thanks

**Comment by msbemba** [comment]
@ganeshubhare Thank you for your feedback. This looks like a technical bug and it needs to be handled by our support team. I'd recommend you contact support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ganeshubhare Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
