### ISSUE TITLE
RSS change log for this documentations are included in https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide, or not. 

### ISSUE THREAD

**Issue by Namita2015-lab** [MicrosoftDocs/microsoft-365-docs#12994]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Other endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by Namita2015-lab** [comment]
The change log notification service added in Office 365 url includes ip list updates made to additional/other endpoints documents or not? 

![RSS change log](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/83926249/01de6927-e6f5-49d9-adad-394edffea6c6)

**Comment by Namita2015-lab** [comment]
How to be posted on the changes made to the Microsoft Graph change notifications IP list here - https://learn.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide 

I do not see a separate RSS change log for this document or any reference to the one here.

**Comment by yogkumgit** [comment]
@Namita2015-lab We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).
