### ISSUE TITLE
The section "Use flows to extract information" is only for V1 form processing model, it is true for V2 models

### ISSUE THREAD

**Issue by msqishengc** [MicrosoftDocs/microsoft-365-docs#12992]
[Enter feedback here]
The section "Use flows to extract information" is only for V1 form processing model, it is true for V2 models

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82d22cbb-b1f7-43d0-2029-4c52787fd734
* Version Independent ID: 82d22cbb-b1f7-43d0-2029-4c52787fd734
* Content: [Train a structured or freeform document processing model in Microsoft Syntex - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/create-a-form-processing-model)
* Content Source: [microsoft-365/syntex/create-a-form-processing-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/create-a-form-processing-model.md)
* Service: **microsoft-syntex**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by msqishengc** [comment]
OK, I missed the important notice:
The information in this section doesn't apply to the latest release of Syntex. It is left as reference only for the form processing models that were created in previous releases. In the latest release, you no longer need to configure the flows to process existing files.

**Comment by chuckedmonson** [comment]
@msqishengc -- Thank you for your comments. We appreciate you looking at the docs and making sure the information is accurate. Thanks again.
