### ISSUE TITLE
Love the obfuscation ...

### ISSUE THREAD

**Issue by Amondale** [MicrosoftDocs/microsoft-365-docs#13000]
Can MSFT *ever* keep up with their own products? Why does it take two years for a name change like AAD -> Entra ID to finally arrive in the documentation? Is it tail (devs) wagging the dog (docs)?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multifactor authentication for users - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide&redirectSourcePath=%252fen-US%252farticle%252fSet-up-multi-factor-authentication-for-Office-365-8f0454b2-f51a-4d9c-bcde-2c48e41621c6)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Amondale Thank you for your feedback. We are extremely sorry about the delay in updating the docs. We will ensure such delays don't happen again in the future.

Hope this helps!

Thanks
Sri
