### ISSUE TITLE
Section needs to be removed from this learn page

### ISSUE THREAD

**Issue by BlakeMsft** [MicrosoftDocs/microsoft-365-docs#13037]
This section needs to be removed from this learn page:

**Performance analyzer for Microsoft Defender Antivirus**

This PS cmdlet runs without needing to implement TSMode.  And is causing confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3733d6a9-d3c5-08b9-0b8a-c85b3b57a038
* Version Independent ID: 3733d6a9-d3c5-08b9-0b8a-c85b3b57a038
* Content: [Troubleshooting mode scenarios in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshooting-mode-scenarios?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshooting-mode-scenarios.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshooting-mode-scenarios.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Hello @BlakeMsft! Thank you so much for the feedback. We'll get this fixed. https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/22704
