### ISSUE TITLE
Question about Quarantine Policy for potentially malicious emails

### ISSUE THREAD

**Issue by jbrianmoss** [MicrosoftDocs/microsoft-365-docs#13038]
Good afternoon, I am wondering why the Strict quarantine policy for potentially malicious emails allows for users to release emails themselves.

For spam/bulk/annoying emails I completely understand why the DefaultFullAccessWithNotificationPolicy quarantine policy makes sense, and I also agree with known malicious emails that AdminOnlyAccessPolicy quarantine policy makes sense.

For these 5 detection types the Strict Quarantine policy is DefaultFullAccessWithNotificationPolicy, why allow users to release themselves? 

- Quarantine   policy for Phishing (PhishQuarantineTag)
- Quarantine   policy for Spoof (SpoofQuarantineTag)
- Quarantine   policy for user   impersonation (TargetedUserQuarantineTag)
- Quarantine   policy for domain   impersonation (TargetedDomainQuarantineTag)
- Quarantine   policy for mailbox   intelligence impersonation (MailboxIntelligenceQuarantineTag)

I would have expected either to use the AdminOnlyAccessPolicy, or potentially a different Quarantine Policy that allowed users to see the emails in quarantine, and get notified about them, but only request an admin release. Something like the Limited Access permissions defined in [Anatomy of a Quarantine Policy](https://learn.microsoft.com/microsoft-365/security/office-365-security/quarantine-policies#anatomy-of-a-quarantine-policy).

To resolve this, I believe it would require two changes:

1. create a new default quarantine policy "LimitedAccessWithNotificationPolicy" or "LimitedAccessWithNotificationPolicy", or something like this. It would have Limited Access permissions and notifications enabled
2. for the above 5 detection types set the Strict configuration to this newly quarantine policy

upon review it may not make sense to apply this new policy to all 5 detectiontypes above, maybe there are good reasons to apply AdminOnlyAccessPolicy to 1 or more of them.

Thank you for your consideration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jbrianmoss, you should open a support ticket and state your issues. Quarantined messages from the most dangerous verdicts (high confidence phishing and malware) aren't accessible to users.

**Comment by jbrianmoss** [comment]
@chrisda just to repeat back, I think you are saying that putting an issue request in for the documentation is only for documentation errors or improvements, but not where I should suggest changes to the actual products?

**Comment by chrisda** [comment]
@jbrianmoss, correct. I have no insight as to why the product team chose the settings in preset security policies, other than they very likely used observations from the datacenters to attempt the best balance between safety and functionality. Your situation is a bit unique in that you're not talking about something that's broken, which is the typical reason for opening a support ticket.
