### ISSUE TITLE
E5 required for default retention label to a document library, folder or document sets? 

### ISSUE THREAD

**Issue by Padavid** [MicrosoftDocs/microsoft-365-docs#1303]
We don't seem to call out in this article that E5 is a requirement for this but it is called out here - https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide#applying-a-default-retention-label-to-all-content-in-a-sharepoint-library-folder-or-document-set

Apply a default retention label to a document library, folder, or document set in SharePoint, so that all documents that arrive in that location inherit the default retention label.

Can we get clarification on if this is required and if it is can we please update this to reflect this requirement. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Padavid  Hi, can you clarify what you mean by "this" when you say "a requirement for this"?  The article is about retention labels but you can use them in different ways.  Applying a retention label as a default label for SharePoint is one way, and this requires E5 as documented.

**Comment by Padavid** [comment]
Sorry.

I am referring to this statement:
“Apply a default retention label to a document library, folder, or document set in SharePoint, so that all documents that arrive in that location inherit the default retention label.”

This should be called out that this is a E5 feature similar to how we call out that auto labeling is E5.

In this link https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide#applying-a-default-retention-label-to-all-content-in-a-sharepoint-library-folder-or-document-set. The same functionally above is called out and states that this requires E5

“In addition to enabling people to apply a retention label to individual documents, you can also apply a default retention label to a SharePoint library, folder, or document set, so that all documents in that location get the default retention label (default labels are an E5 feature)."

Patrick David
Sr. Premier Field Engineer (SharePoint, O365, Teams)
Microsoft
Modern Workpace - Public Sector
Office: +1 (216) 750-4604
Mobile: +1 (440) 821-9586
patrick.david@microsoft.com<mailto:patrick.david@microsoft.com>
[Twitter]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118885684&sdata=GMvICN4fL7tv9z2WXixrm%2BoC7vGIncuAIa%2FhfRRHrYw%3D&reserved=0>    [Facebook] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118885684&sdata=7GV6giUGL4UKalzU%2FysutD3ig8I%2BdKUC0wGFEJBEw2E%3D&reserved=0>     [Linkedin] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118895694&sdata=rZhit9e2v19xp48PflSj%2BhkM4PBYNb6GmIW%2B99O6M1s%3D&reserved=0>     [Youtube] <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FMicrosoft&data=02%7C01%7CPatrick.David%40microsoft.com%7C7e1e2899cd434843f3df08d6547245f0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636789247118895694&sdata=1QtQ8jCahvI1CmjaY1B%2FTvTo%2Fy%2FIJpy8HCoZdOOcgT0%3D&reserved=0>
[Microsoft Logo]

If you have any feedback about my work, please let either me or my manager Beth MacAlarney know at bethm@microsoft.com<mailto:bethm@microsoft.com>.

**Comment by cabailey** [comment]
@Padavid So the request is to word the licensing requirement for the default label in terms of user assignment, rather than the subscription required at the tenant level?  We're working with marketing to review and refine these statements, so your feedback is appreciated.

**Comment by fselkirk** [comment]
I am also looking at this and see: 
•	The boxed note states that _each user who edits items with automatically applied labels_ needs an E5 license. 
•	The section on automatically applied labels implies that only _the administrator who creates and applies the policy to automatically apply labels_ needs an E5 license. 
•	The parenthetical in the section on default labels implies that _the user who configures this for a site_ needs an E5 license. 
My gut feeling is that the latter two are true, but that the first is not. (I could be wrong!) I am testing the user edit scenario (which will take some time to set up) and reaching out to Compliance support for this. Do you have any response from marketing?

**Comment by cabailey** [comment]
Thank you for your feedback. After careful consideration, all licensing statements have been removed from this article and your feedback has been passed along so that they can be incorporated into one of the following articles that are dedicated to licensing:

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance

**Comment by Padavid** [comment]
@Carol Bailey it would be useful to have links to those two article in the document so people know to look at them for licensing question.

Also as feedback it very unclear in those two articles if I need E5 to do default labeling of libraries. Before it seemed clear and now it seems very unclear. Personally I liked it in the article as it was very clear but not consistent.

**Comment by cabailey** [comment]
@Padavid  Yes, I'll add them when these details are incorporated into those articles, but at the moment they do not so it wouldn't be very helpful.  In the meantime, people can get the links from this thread and do feel empowered to add feedback onto those pages for the changes you would like to see.  Licensing is owned by a different team, so when questions/feedback get reported from this page, I can't provide an authoritative answer.  In the meantime, if you have concerns about licensing requirements, consult your Microsoft Account Manager.  If you are a Microsoft employee, contact me direct and I'll put you in contact with the right people.
