### ISSUE TITLE
Teams Admin

### ISSUE THREAD

**Issue by jason-collab** [MicrosoftDocs/microsoft-365-docs#1304]
The steps noted work.  However, I notice that as a Teams Administrator, I can no longer create a team from the Teams desktop client?  It only allows me to join a team.  So, how would I "Create a team from an existing team"?  Can't do it in Teams Admin center or M365 Admin center.  I can only create new groups/teams from scratch there.

https://support.office.com/en-us/article/create-a-team-from-an-existing-team-f41a759b-3101-4af6-93bd-6aba0e5d7635

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create Office 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@jason-collab - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
