### ISSUE TITLE
getmissingkbs missing machines

### ISSUE THREAD

**Issue by croziors** [MicrosoftDocs/microsoft-365-docs#13047]
Hello
I have created a script to query all my machines on my windows tenant. I manage well the limitations of API calls.
I try again with the right time if ever I have a message to redo in X seconds everything is well done but when I execute my script I never have the same number of machines if I redo it 10 minutes later.

**Comment by croziors** [comment]
the machines must all be connected to the network or he can get the information even if they are offline. ?

**Comment by yogkumgit** [comment]
@croziors Please indicate which document you are referring to and what is your feedback. Thanks

**Comment by croziors** [comment]
microsoft-365/security/defender-endpoint/api/get-missing-kbs-machine.md


sometimes the script gives me a 404 but if I redo it by hand it works fine but sometime i need make 3 time

Error code: 404. Message: {"error":{"code":"ResourceNotFound","message":"Machine xxxxxx was not found","target":"|3xxxxx"}}

**Comment by msbemba** [comment]
@croziors Thank you for your feedback. This sounds more like a technical issue or a bug, I'd recommend you contact support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @croziors Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
