### ISSUE TITLE
TeachingBubble overflows for small viewports

### ISSUE THREAD

**Issue by BetaLyte** [MicrosoftDocs/microsoft-365-docs#13042]
When using ${EmailContent} with indicators, the resulting TeachingBubbles seem to always overflow horizontally, such that the content of the whole page get shiftet to the left, some times overflowing and not readable:

https://github.com/MicrosoftDocs/microsoft-365-docs/assets/6012093/9b458133-7061-4c74-8b27-e263e9ef5f8c

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f56aeac-fdf1-edf0-d98a-15001a299c05
* Version Independent ID: 6f56aeac-fdf1-edf0-d98a-15001a299c05
* Content: [Landing pages in Attack simulation training](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-landing-pages?view=o365-worldwide#create-landing-pages)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-landing-pages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-landing-pages.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@BetaLyte, you should open a support ticket about this.
