### ISSUE TITLE
Retention Tag - Deletion

### ISSUE THREAD

**Issue by ddamian67** [MicrosoftDocs/microsoft-365-docs#1305]
Once a retention tag is set up to delete email 10 years and older, Does the policy removes the existing email that 10 years old or the policy applies from the time it gets implemented, meaning from this point forward the policy will apply not to the exciting emails?
I hope i am clear on my question, any feedback will be greatly appreciated.

Regards,

Daniel.

**Comment by mypil** [comment]
@ddamian67 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by ddamian67** [comment]
@mypil - it is related to the link below:
https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide

**Comment by markjjo** [comment]
@ddamani8 The retention duration is based on when an email message is created (i.e. when it's sent or received). So the policy will apply to existing messages. Please see:

https://docs.microsoft.com/en-us/Exchange/security-and-compliance/messaging-records-management/retention-age

**Comment by ddamian67** [comment]
Thank you.

**Comment by ddamian67** [comment]
Thank you for the information it was very helpful. I set up the Retention policy and applied it to a test mailbox with existing e-mails older than 10 years, forced the "Managed Folder Assistant" and the policy worked.
