### ISSUE TITLE
Private Preview is unclear from doc

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#13058]
Article is a little unclear that this is in Private Preview. Only mention is here "If your organization is enrolled in Attack simulation training for Teams Private Preview, carry out the following configuration steps:"

Would be better mentioned at top of requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e94fd8c2-4d09-74bd-512a-ac8b9fe4abf4
* Version Independent ID: e94fd8c2-4d09-74bd-512a-ac8b9fe4abf4
* Content: [Microsoft Teams in Attack simulation training](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-teams?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-teams.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@aldoug, the big not at the top of the article isn't sufficient?

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/33166947/b8fbbfd6-b823-4f90-8bd0-e454421ce809)

**Comment by aldoug** [comment]
Correct. It doesn't make it clear to customers that they wont have access to this unless they are signed up for it in private preview. We're seeing the support cases (and even I had to check internally)

Alisdair Douglas
Support Escal Eng
Customer Services and Support
Office: +44 (118) 9095190
***@***.******@***.***>
Working hours: Monday - Friday 08:00 - 16:30 GMT/BST
[Microsoft Logo]
Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via 'Support' (headset icon)/'View service requests'/'Ticket #' (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by chrisda** [comment]
@aldoug, OK. I made the call-out at the top more specific and prominent.

Thanks for the feedback.

Closing

**Comment by aldoug** [comment]
[heart]         Alisdair Douglas reacted to your message:
________________________________
