### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by astrasia** [MicrosoftDocs/microsoft-365-docs#13054]
A broken link on the poster.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4308bf55-eadb-767d-6aaa-21190669c1ef
* Version Independent ID: d3e1731f-9f86-efba-4369-b0399cd99172
* Content: [Deploy your identity infrastructure for Microsoft 365 - Microsoft 365 Enterprise](https://learn.microsoft.com/en-my/microsoft-365/enterprise/deploy-identity-solution-overview?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/deploy-identity-solution-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/deploy-identity-solution-overview.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@astrasia Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13094

Once the author approves, the changes will be live.

Thanks
Sri
