### ISSUE TITLE
Clarification on create and view

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/microsoft-365-docs#13062]
_In order to target only a group of users in your organization to be able to create Loop content in workspaces, create a second group that targets All users, set this group to Disabled, and make it a lower priority than your target group that is set to Enabled. This will override the default Not Configured state to Disabled for all users but your target group._

This comment is not clear enough as the policy itself is named _"Create and view Loop workspaces in Loop"_. Is this to 
- target a certain group to create and **view** content OR
- target a certain group to create  content

Better would be: _In order to target only a group of users in your organization to be able to create **and view** Loop content in workspaces_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 093c11ef-791c-c4bd-71e6-c3e6ecc347e1
* Version Independent ID: 093c11ef-791c-c4bd-71e6-c3e6ecc347e1
* Content: [Manage Loop workspaces in Syntex repository services](https://learn.microsoft.com/en-us/microsoft-365/loop/loop-workspaces-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/loop/loop-workspaces-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/loop/loop-workspaces-configuration.md)
* Service: **sharepoint-online**
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

**Comment by msbemba** [comment]
@LennartaeHoefer Thank you for your feedback. You are right, it should be to create and view Loop content in workspaces. I have made the changes in the document and can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13092

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by LennartaeHoefer** [comment]
[heart]         Lennart Hoefer reacted to your message:
________________________________
