### ISSUE TITLE
Update Custom Domain Records via API

### ISSUE THREAD

**Issue by dlawrences** [MicrosoftDocs/microsoft-365-docs#1306]
Hi

Do you know if these custom records are available for updates through the Microsoft Graph API? I have been able to find only some potentially similar GET methods:
- List serviceConfigurationRecords
- List verificationDnsRecords

Additionally, do you know if Microsoft has any solution for Dynamic DNS situations?

Thanks

---
#### Detalii document

⚠ *Nu editați această secțiune. Este necesară pentru asocierea prin link a problemelor între docs.microsoft.com și GitHub.*

* ID: f0302478-af73-742b-a7d2-536375b92986
* Version Independent ID: 30f173d3-559b-85fc-6bdd-eb4fcf59d183
* Content: [Add or edit custom DNS records in Office 365](https://docs.microsoft.com/ro-ro/microsoft-365/admin/dns/add-or-edit-custom-dns-records?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/dns/add-or-edit-custom-dns-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/add-or-edit-custom-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by Mike-Crowley** [comment]
Office 365's DNS hosting service is for small businesses. If you want API access to DNS, you should look at Azure DNS or other enterprise DNS services.

**Comment by dlawrences** [comment]
Alright, thanks!
