### ISSUE TITLE
Standard setting for First Contact Safety Tip is now TRUE, but article incorrectly states it is FALSE.

### ISSUE THREAD

**Issue by jvaught48** [MicrosoftDocs/microsoft-365-docs#13068]
This page shows that the Standard settings under anti-phishing for the First Contact Alert is OFF (EnableFirstContactSafetyTips = FALSE). Recently we noticed in all our tenants the Standard Preset Security Policy now has this set to ON (EnableFirstContactSafetyTips = TRUE)

The page describing the Standard Preset Security Policy is here https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide and under the section "Policy settings in preset security policies" it states that

> The Standard, Strict, and Built-in protection policy setting values, including the associated [quarantine policies](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide#anatomy-of-a-quarantine-policy), are listed in the feature tables in [Recommended settings for EOP and Microsoft Defender for Office 365 security](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide).

This two articles conflict with the apparent recent change in this setting from defaulted OFF to defaulted ON. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jvaught48 also fixed as part of your other issue #13067.

Thanks for the feedback.

Closing

**Comment by jvaught48** [comment]
> @jvaught48 also fixed as part of your other issue #13067.
> 
> Thanks for the feedback.
> 
> Closing

Awesome thank you! Should it also be changed for "Strict"? Seems odd that for Standard it would be true but not for Strict. However, I personally did not check it on Strict, so I'm not actually sure.

**Comment by chrisda** [comment]
@jvaught48, I checked both Standard and Strict, and EnableFirstContactSafetyTips = TRUE was only true for Standard, not Strict.
