### ISSUE TITLE
USB control is a ME3 feature, not a ME5 feature.

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#13061]
This page calls out that USB control is a ME5 feature. 
Im not sure when that paragraph was written, but with the launch of MDE-P1, which include USB control, I cant see why we would need a E5 license to control USB devices .

This page says both MDE-P1 and MDE-P2 support the USB control
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control?view=o365-worldwide

This MDE-Plan1 links says its included
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1?view=o365-worldwide
**Device control** :  Sometimes threats to your organization's devices come in the form of files on removable drives, such as USB drives. Defender for Endpoint includes capabilities to help prevent threats from unauthorized peripherals from compromising your devices. You can configure Defender for Endpoint to block or allow removable devices and files on removable devices.
To learn more, see [Control USB devices and removable media](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/control-usb-devices-using-intune?view=o365-worldwide).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48609e18-20d4-ff9c-fbb2-d837a8d47adb
* Version Independent ID: 48609e18-20d4-ff9c-fbb2-d837a8d47adb
* Content: [Deploy and manage Removable Storage Access Control using group policy](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-group-policy?view=o365-worldwide#licensing-requirements)
* Content Source: [microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-group-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deploy-manage-removable-storage-group-policy.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@gbms311 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13093

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by henrywang08** [comment]
I think the request is **NOT** to add Microsoft 365 E3 in the license requirement, but to **remove** such Microsoft 365 E3 or E5 license requirement. 

The question here is - if a customer doesn't have Microsoft 365 E3 license, but only have Microsoft Defender for Endpoint Plan 1 license, can the customer access and use Removable Storage Access Control through group policy?

**Comment by gbms311** [comment]
MDE-P1 is part of M365 E3, but can also be purchased as a standalone . 
So, yes, the request would be to update the text to mention that for endpoint USB control,  the license required is at minimum MDE-P1. Higher band licenses of M365 E3 which includes MDE-P1, or M365 E5, which includes MDE-P1 plus MDE-P2 , can of course also suffice)

**Comment by gbms311** [comment]
@denisebmsft and @msbemba . Are you in agreement that MDE-P1 is all that is required for USB control?. Please can you update the content to reflect that MDE-P1 is sufficient, and not reliant on full ME3. (to me it looks like this was closed, but does not mention MDE-P1 min license required)
