### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cstanciumsft** [MicrosoftDocs/microsoft-365-docs#13069]
[Enter feedback here]

In the phrase 'Far less frequently, in will add your digital certificate to a list of trusted publishers' there is a typo - 'in' should be 'it'.
Correct: 'Far less frequently, it will add your digital certificate to a list of trusted publishers' 

This confused one of the customers. Please modify accordingly.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec45a06d-67d7-c3ff-2a20-8784f6a43351
* Version Independent ID: ec45a06d-67d7-c3ff-2a20-8784f6a43351
* Content: [Software developer FAQ](https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/developer-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/intelligence/developer-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/intelligence/developer-faq.yml)
* Service: **microsoft-365-security**
* Sub-service: **intelligence**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@cstanciumsft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13138

Once the author approves, the changes will be live.

Thanks
Sri
