### ISSUE TITLE
Policy Settings reference is incorrect.

### ISSUE THREAD

**Issue by jvaught48** [MicrosoftDocs/microsoft-365-docs#13067]
Under the section "Policy settings in preset security policies" it states that

> The Standard, Strict, and Built-in protection policy setting values, including the associated [quarantine policies](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide#anatomy-of-a-quarantine-policy), are listed in the feature tables in [Recommended settings for EOP and Microsoft Defender for Office 365 security](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide).

However, this is not correct because that page shows that the Standard settings for the First Contact Alert is OFF (EnableFirstContactSafetyTips = FALSE). Recently we noticed in all our tenants that this is now ON (EnableFirstContactSafetyTips = TRUE)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jvaught48, confirmed. Unclear if this change is intentional, but I updated the documentation accordingly.

Thanks for the feedback.

Closing

**Comment by jvaught48** [comment]
> @jvaught48, confirmed. Unclear if this change is intentional, but I updated the documentation accordingly.
> 
> Thanks for the feedback.
> 
> Closing

Awesome thank you! Should it also be changed for "Strict"? Seems odd that for Standard it would be true but not for Strict. However, I personally did not check it on Strict, so I'm not actually sure.
