### ISSUE TITLE
Applicable EDU license plans?

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/microsoft-365-docs#1307]
Only E5 or E3 plus the E5 compliance add in are mentioned.  What are the licensing requirements in EDU - are they equivalent?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb98e0ff-d34c-75bc-0ade-7dc70fc7f4bd
* Version Independent ID: 5172471f-e514-bcde-16e0-d8d8090a892a
* Content: [Get started with insider risk management - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/insider-risk-management-configure?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-configure.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@thewrabbit - thanks for the feedback. Yes, the A5 and A3 (EDU) subscriptions are supported and I've updated the license guidance in the topic (https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-configure?view=o365-worldwide#before-you-begin). Thanks again!
