### ISSUE TITLE
Not inclusive of all the required GCC Endpoints. 

### ISSUE THREAD

**Issue by Matt-Mueller-MSFT** [MicrosoftDocs/microsoft-365-docs#13073]
Pages "Office 365 requires connectivity to the Internet. The endpoints below should be reachable for customers using Office 365 plans, including Government Community Cloud (GCC)" yet it does not have the GCC Power Platform URLs. Since the M365 G3/G5 licensing includes some seeded capabilities within Power Platform the GCC Cloud equivalents should be included here, or maybe a standalone GCC Page needs to be published like there is for GCCH or DoD. 

This causes heartache for GCC Customers as they use this list to get their networking teams to open up and allow Microsoft endpoints related to M365 Services, yet it does not include all the services endpoints (mainly Power Platform GCC URLS) they need and causes them to have to use multiple sources to get the correct URL/Endpoint lists for their tenants to access the full capabilities included with their licensing. 

We really need to do better on our documentation for our GCC Customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&source=recommendations)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@Matt-Mueller-MSFT We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).

**Comment by Matt-Mueller-MSFT** [comment]
I'm a Microsoft employee, and I am telling you something is wrong. Please let me know who to address this to internally


﻿

Matt Mueller

CSA-E

Customer Success - Modern Work

Microsoft Federal

Mobile: 773-329-5593<tel:+17733295593>

***@***.******@***.***>


________________________________

**Comment by yogkumgit** [comment]
Please contact @tiburd
