### ISSUE TITLE
Issue with installing Microsoft Sense on Windows Server 2016

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/microsoft-365-docs#13070]
KB500592 is only an update. It does not install Microsoft Sense.

When I try to install the package, I get the following message in the MpSigStub.log file : 

```
============================ PackagesNotApplicable =============================

No products found to update.
End time: 2023-11-02 08:50:12Z
--------------------------------------------------------------------------------

I have attached the entire log file.


```

```
[MpSigStub.log](https://github.com/MicrosoftDocs/microsoft-365-docs/files/13236773/MpSigStub.log)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Version Independent ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Content: [Get started with troubleshooting mode in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Tarjei-stavanger Thank you for your feedback. A device running Windows 10 (version 19044.1618 or later), Windows 11, Windows Server 2019, or Windows Server 2022 is needed to run troubleshooting mode in Microsoft Defender for Endpoint.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Tarjei-stavanger Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
