### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by ColmanPerkins-Stephen** [MicrosoftDocs/microsoft-365-docs#13085]
The information on this page is not accurate now that the 365 defender pages have been moved around.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1541fb66-1414-579d-344c-fc1e25ba4ea0
* Version Independent ID: 1541fb66-1414-579d-344c-fc1e25ba4ea0
* Content: [How-to deploy and configure the report message add-in](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/step-by-step-guides/deploy-and-configure-the-report-message-add-in.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTBen
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@MSFTBen for visibility.

**Comment by msbemba** [comment]
@ColmanPerkins-Stephen Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13142

Once the author approves, the changes will be live.

Thanks
Sri
