### ISSUE TITLE
Quiz & Certificate

### ISSUE THREAD

**Issue by mfnaqvi** [MicrosoftDocs/microsoft-365-docs#1308]
At the end of course if there will be a quiz and certificate that will be great for CPEs etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88d48ed-b84b-3571-6c6e-e12ed8811c11
* Version Independent ID: a1aefdd8-25ed-f181-a167-c5d5f7a4efa3
* Content: [Chief Information Security Officer (CISO) Workshop, Module 1: Microsoft Cybersecurity Briefing - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/ciso-workshop-module-1?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/ciso-workshop-module-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/ciso-workshop-module-1.md)
* Service: **o365-seccomp**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by mypil** [comment]
@mfnaqvi - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**. 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
