### ISSUE TITLE
Wrong reference for "Turn on the Defender for Endpoint integration in Intune"

### ISSUE THREAD

**Issue by daves83** [MicrosoftDocs/microsoft-365-docs#13081]
In step 2, you are asked to log in to the Azure portal to activate the integration between MDE and Intune.
If I'm not mistaken, the correct procedure is to access the Intune portal (https://intune.microsoft.com) and select Endpoint Security > Microsoft Defender for Endpoint; at this point, the "Connect Windows devices version 10.0.15063 and above to Microsoft Defender for Endpoint" toolbox is available.

**Comment by msbemba** [comment]
@daves83  Thank you for your feedback. Are you referring to https://learn.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection? I dont see a reference to Turn on the Defender for Endpoint integration in Intune on this page. If not, please provide the document that you are referring to.

Thanks
Sri

**Comment by daves83** [comment]
Hi,
at the following link
<https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-conditional-access?view=o365-worldwide>,
you can find a step called "Step 2: Turn on the Defender for Endpoint
integration in Intune" where the actions proposed are wrong.

[image: image.png]

To accomplish this task, you need to follow these steps: access the Intune
portal (https://intune.microsoft.com) and select Endpoint Security >
Microsoft Defender for Endpoint; at this point, the "Connect Windows
devices version 10.0.15063 and above to Microsoft Defender for Endpoint"
toolbox is available.

Please let me know if I'm wrong.
Thanks,
Davide


Il giorno mar 14 nov 2023 alle ore 14:12 Sriraman M S <
***@***.***> ha scritto:

**Comment by daves83** [comment]
Great!
Is this will be marked as feedback contribution in the MVP activities list?

Thanks,
Davide

Il giorno mar 14 nov 2023 alle ore 16:05 Sriraman M S <
***@***.***> ha scritto:
