### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by adavisgann** [MicrosoftDocs/microsoft-365-docs#1309]
Link in See also section for Detect and Remediate Outlook Rules and Custom Forms Injections Attacks in Office 365 returns 404 - Page not found 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68b20762-e3ee-6aa6-7460-5bc7214fd00e
* Version Independent ID: 641814b7-9c30-2119-e5f9-7983118e102f
* Content: [Responding to a Compromised Email Account in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@adavisgann, fixed. Thanks for the feedback.

Closing
