### ISSUE TITLE
Add: How to check Dev Drive Status when "Show Volumes" isn't listed

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/microsoft-365-docs#13104]
I have data on a Dev Drive:

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/25464172/ccc2acd9-b5ff-4e29-896e-ff73b6e53391)

Yet in Security Center I have no "See Volumes" link:

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/25464172/0072dc74-336a-4f9e-9dad-d833bfd15d8c)

Is there a PowerShell command to view if performance mode is enabled. Because on my system, EndPoint protection is blocking on the Dev Drive.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08e9b3ce-af78-468f-abb7-92fef4f741c5
* Version Independent ID: 08e9b3ce-af78-468f-abb7-92fef4f741c5
* Content: [Protect Dev Drive using performance mode](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-antivirus-performance-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-antivirus-performance-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-antivirus-performance-mode.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **dansimp**

**Comment by pilcherd** [comment]
I guess the wording actually says Performance Mode is on... so it must be on for what it's worth, but there is still no See Volumes link like the documentation.

**Comment by msbemba** [comment]
@pilcherd Thank you for your feedback. SInce it says  Performance Mode is ON, Since do not see an option to check volumes,  I'd recommend you contact support via the need help button on the admin center, so the support engineers can fix or escalate this bug.

Hope this helps!

Thanks
Sri
