### ISSUE TITLE
"By default, the queue displays alerts seen in the last 30 days in a grouped view." is seems not correct now.

### ISSUE THREAD

**Issue by kash1064** [MicrosoftDocs/microsoft-365-docs#13106]
Hello team.

I think below line is not correct.
> By default, the queue displays alerts seen in the last 30 days in a grouped view. The most recent alerts are shown at the top of the list helping you see the most recent alerts first.

In my tenant, the queue displays alerts seen in **the last 7 days** by default.
Could you confirm that page is correct or not?

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5786c947-5055-fee0-268b-ab15c4d4055e
* Version Independent ID: e0379dac-2e6c-2a11-8649-98a1835a625d
* Content: [View and organize the Microsoft Defender for Endpoint Alerts queue](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/alerts-queue?view=o365-worldwide#understanding-alert-severity)
* Content Source: [microsoft-365/security/defender-endpoint/alerts-queue.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/alerts-queue.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@kash1064 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13148

Once the author approves, the changes will be live.

Thanks
Sri
