### ISSUE TITLE
CSV file format

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#1311]
The link to the sample partner CSV file includes a fourth field - the hardware hash, but the text suggests this is not required in the partner version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd1cbbf-99b1-f6ca-94ee-8f30015339f9
* Version Independent ID: c4d8538b-f436-7e3d-0372-0aae84955e01
* Content: [Steps for Partners to register devices - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/register-devices-partner?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/managed-desktop/get-started/register-devices-partner.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/register-devices-partner.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@jwmurraycmu could you double-check the sample files?

**Comment by jaimeo** [comment]
@jwmurraycmu

**Comment by jwmurraycmu** [comment]
@jaimeo , heya - confirmed! Sorry for the delay, but this is a good change to make. The system is smart enough to ignore the hash field in this situation, but it's still confusing. I suggest eliminating the extra field from the partner content.

**Comment by mypil** [comment]
@jaimeo @jwmurraycmu - Is this issue already resolved? Please confirm.

Thank you.
