### ISSUE TITLE
Wrong name for Azure Virtual Desktop

### ISSUE THREAD

**Issue by jkamping** [MicrosoftDocs/microsoft-365-docs#13111]
[Enter feedback here]
The note in this document refers to Windows Virtual Dekstop but must be Azure Virtual Desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92449682-399e-5966-059f-6733e23e41fd
* Version Independent ID: d9002b5e-944a-4bed-62a6-d02d573db8ff
* Content: [Integration with Microsoft Defender for Cloud](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/azure-server-integration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/azure-server-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/azure-server-integration.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jkamping Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13145

Once the author approves, the changes will be live.

Thanks
Sri
