### ISSUE TITLE
Update Document to reflect correct data type for Report ID

### ISSUE THREAD

**Issue by MichaelNell** [MicrosoftDocs/microsoft-365-docs#13125]
[Enter feedback here]
Please can we have this page updated to reflex the correct data type for report ID. In the portal the data type is string. 

![Screenshot 2023-11-10 141250](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/128721281/eb3c7ff6-4578-4619-8a6d-644935a61fad)

Our docs state the data type is long.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fda1ef87-e69b-5670-3f82-db5749fb4a92
* Version Independent ID: dea31201-c226-e1b0-c678-5a4292601842
* Content: [EmailAttachmentInfo table in the advanced hunting schema](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-emailattachmentinfo-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-emailattachmentinfo-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-emailattachmentinfo-table.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
thank you so much. addressed here: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/22929
