### ISSUE TITLE
No content in this section

### ISSUE THREAD

**Issue by MagrPain** [MicrosoftDocs/microsoft-365-docs#13123]
There's no content! It just says "Offboarding Windows Devices" and then nothing. Obviously not helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d52e56ae-7d90-fe14-2d04-99a12b5653d9
* Version Independent ID: 321c630e-3f0b-9213-593a-4bb9a394aad9
* Content: [Offboard devices](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/offboard-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/offboard-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/offboard-machines.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@MagrPain Thank you for your feedback. As there are three ways to offboard, We have added that information to the document now as a Link.

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/4024c0ce-c387-4a46-a869-b46dae39a9f2)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MagrPain Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
