### ISSUE TITLE
Precision request for auto claim policies for licence 

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/microsoft-365-docs#13127]
Assuming a user has no access on the application, will he get prompted tl get a license ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57d3c7ec-df48-1f82-8b07-283b5238fda4
* Version Independent ID: 89a71654-a370-2160-8606-93d15be87e99
* Content: [Manage auto-claim policies in the Microsoft 365 admin center](https://learn.microsoft.com/en-us/microsoft-365/commerce/licenses/manage-auto-claim-policies?view=o365-worldwide#auto-claim-policies-for-microsoft-power-apps)
* Content Source: [microsoft-365/commerce/licenses/manage-auto-claim-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/manage-auto-claim-policies.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@jeffangama Thank you for your feedback. If the user has no access on the application, he/she will not get prmpted to get the license.

However, If a user lacks a standalone Power Apps license and launches an app that requires a premium license, the system automatically grants a Power Apps per user license to the user.

If a user without a standalone Power Apps license launches an app within a Managed environment, they're automatically granted a Power Apps per user license.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jeffangama Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jeffangama** [comment]
Hi,
Could you please update the documentation to precise this point ?
Regards
