### ISSUE TITLE
As an admin, how I can allow my users to send emails with their alias?

### ISSUE THREAD

**Issue by lindemann-co** [MicrosoftDocs/microsoft-365-docs#13129]
The section "Sending email from the proxy address easily" states: _"When the global admin has set the Set-OrganizationConfig -SendFromAliasEnabled $true cmdlet, users within the organization will get access to a list of checkboxes where each entry corresponds to an alias in their Outlook settings."_

As a user with no experience with MS admin, I would really appreciate a link to a guide explaining how to set that setting. Can I do it from https://admin.microsoft.com? If not, then how?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide#sending-email-from-the-proxy-address-easily)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@lindemann-co Thank you for your feedback. This option is only available whenusing the [Set-OrganizationConfig PowerShell](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps) commandlet as part of the [Exchange Online PowerShell V2 Module](https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps). 

The admin needs to run Set-OrganizationConfig -SendFromAliasEnabled $true to enable this feature for all users in the organization.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lindemann-co Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
