### ISSUE TITLE
Can't add SPF in Microsoft 365 domain - errors shows that the SPF TXT already exists, but it doesn't appear in the list

### ISSUE THREAD

**Issue by Wang-Tinybots** [MicrosoftDocs/microsoft-365-docs#13122]
![Snip20231109_1](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/150358965/642645f2-bf5f-4bb1-8814-fcb5a5f9fdf4)

**Comment by yogkumgit** [comment]
@Wang-Tinybots Considering the nature of the issue please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
