### ISSUE TITLE
GPO path is slightly incorrect and policy setting name is incomplete.

### ISSUE THREAD

**Issue by helreg** [MicrosoftDocs/microsoft-365-docs#13132]
On this page:
https://learn.microsoft.com/microsoft-365/security/defender-endpoint/deploy-and-manage-using-group-policy in the "Deploy using group policy" section, on step 2. Set Default Enforcement:, theres' a couple of minor mistakes regarding the path and name for the GPO setting:
The mistakes are:
The path has "Features" line and the setting name is missing the word Policy in the end.

The correct path is (including the full setting name):
Go to Computer Configuration > Administrative Templates > Windows Components > Microsoft Defender Antivirus > Device Control > Select Device Control Default Enforcement **Policy**
The other minor mistake is the line right after which also should read (correct full name of the setting):
In the Select Device Control Default Enforcement **Policy** pane, select Default Deny:

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1cbd7616-d2e8-6a35-4187-6727df811baa
* Version Independent ID: 1cbd7616-d2e8-6a35-4187-6727df811baa
* Content: [Deploy and manage using group policy](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-and-manage-using-group-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/deploy-and-manage-using-group-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deploy-and-manage-using-group-policy.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @nimishasatapathy
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@helreg Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13171

Once the author approves, the changes will be live.

Thanks
Sri
