### ISSUE TITLE
Please correct "Web Content Filtering Details" to "Web content filtering categories details"

### ISSUE THREAD

**Issue by bedo1976** [MicrosoftDocs/microsoft-365-docs#13134]
[Enter feedback here]

Your text here is:

To dispute the category of a domain, navigate to Reports > Web protection > Web Content Filtering Details > Domains. On the domains tab of the Web Content Filtering reports, you will see an ellipsis beside each of the domains. Hover over this ellipsis and select Dispute Category.

But "Web Content Filtering Details " is wrong. It is now called "Web content filtering categories details"

See
https://security.microsoft.com/webcontentfilteringcategoriesdetailspage?viewid=webCategories&tid=8f017f12-844c-486a-946b-ead6f8f9d2a4

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fbaaa90e-6975-ee29-335a-545cb6a55986
* Version Independent ID: 75c93c17-4952-a13f-ed60-d2baefd0337e
* Content: [Web content filtering](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-content-filtering?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-content-filtering.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@bedo1976 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13172

Once the author approves, the changes will be live.

Thanks
Sri
