### ISSUE TITLE
Missing Text that states this is required from both Organizations

### ISSUE THREAD

**Issue by brandyngping** [MicrosoftDocs/microsoft-365-docs#13154]
There is a video on this page, and at the very end of that video it states this setup must be done by both parties. Currently this document does not state in text that both organizations need to be setup this way for shared channels to work properly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c083238f-2bbc-29e7-ca45-6ccc30c501bf
* Version Independent ID: c083238f-2bbc-29e7-ca45-6ccc30c501bf
* Content: [Collaborate with external participants in a shared channel (IT Admins)](https://learn.microsoft.com/en-us/microsoft-365/solutions/collaborate-teams-direct-connect?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-teams-direct-connect.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-teams-direct-connect.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Thanks, @brandyngping. I'll add a note to the article to call that out.
