### ISSUE TITLE
Instruction says Privileged Access where it should say Privileged Identity Management.

### ISSUE THREAD

**Issue by RSKadish** [MicrosoftDocs/microsoft-365-docs#13153]
Under "Create the security group in Microsoft Entra ID for elevated permissions", step 5 is:

_Go back into the group you've just created, and select Privileged Access > Enable Privileged Access._

This is incorrect.  The line should say:

Go back into the group you've just created, and select Privileged Identity Management> Enable PIM.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c1b40f7-129f-5fb9-cdde-42e35a8819f7
* Version Independent ID: 8c1b40f7-129f-5fb9-cdde-42e35a8819f7
* Content: [Use Azure Privileged Identity Management (PIM) in Microsoft Defender for Office 365 to limit admin access to cyber security tools.](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/pim-in-mdo-configure?view=o365-worldwide&viewFallbackFrom=o36)
* Content Source: [microsoft-365/security/office-365-security/pim-in-mdo-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/pim-in-mdo-configure.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@RSKadish Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13178

Once the author approves. the changes will be live.

Thanks
Sri
