### ISSUE TITLE
Priority for policies twisted in the docs?

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/microsoft-365-docs#13152]
I think it must be a higher priority for the all  users targeting policy. 

In order to target only a group of users in your organization to be able to create Loop content in workspaces, create a second group that targets All users, set this group to Disabled, and make it a **lower priority** than your target group that is set to Enabled. This will override the default Not Configured state to Disabled for all users but your target group.

<img width="493" alt="image" src="https://github.com/MicrosoftDocs/microsoft-365-docs/assets/94690779/cbbce426-446c-4cd8-bc20-bab6153c12b5">

Configurations with **lower priority** will take precedence
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 093c11ef-791c-c4bd-71e6-c3e6ecc347e1
* Version Independent ID: 093c11ef-791c-c4bd-71e6-c3e6ecc347e1
* Content: [Manage Loop workspaces in Syntex repository services](https://learn.microsoft.com/en-us/microsoft-365/loop/loop-workspaces-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/loop/loop-workspaces-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/loop/loop-workspaces-configuration.md)
* Service: **sharepoint-online**
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

**Comment by msbemba** [comment]
@LennartaeHoefer Thank you for your feedback. I understand the ambiguity on higher vs lower, however, the ones with higher priority (like 0,1) will take precedence over the once with lower priority(9,10).

Hope this helps!

Thanks
Sri

**Comment by LennartaeHoefer** [comment]
Thanks for the explanation dear @msbemba ! 
OK, so the screenshot says "lower priority takes precedence".
Looking at the text: If you now create a policy with a lower priority for all users (lower priority = precedence) wouldn't that override the setting for the target group which has a higher priority?
In that case also the "policy for all user" which is set by the switch in the MAC would not make any sense with prio 2 as this is the fallback in case the user is not catched by any other policy with lower priority.

**Comment by yogkumgit** [comment]
@msbemba please comment

**Comment by msbemba** [comment]
@LennartaeHoefer Priority means that an element has more or less importance or precedence than another. If an element has low priority, it means that it has no precedence towards anything. So in the screenshot, 3 is low priority and 0 is high priority.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LennartaeHoefer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
