### ISSUE TITLE
Step 10: Unable to create a new policy targeted to all recipients in your domain

### ISSUE THREAD

**Issue by wfm2003** [MicrosoftDocs/microsoft-365-docs#1315]
I have Microsoft Business. When I attempt to add a new policy targeted to all recipients, the system does not allow a new policy. It only allows edits to the default policy. Is this a corporate licence problem or a configuration issue with ATP Safe Links?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea79921a-7f83-58f1-c0a4-6eb0efce0d26
* Version Independent ID: b60110ef-71ad-9962-74de-734062708ff8
* Content: [Top 10 ways to secure Office 365 and Microsoft 365 Business plans](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@wfm2003 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
