### ISSUE TITLE
New and Federated domains are not affected by password expiration policy

### ISSUE THREAD

**Issue by NuAlex** [MicrosoftDocs/microsoft-365-docs#13163]
Customer might think this is a tenant-level policy but that's not how Entra ID works and can be misleading causing unexpected password expirations and blocked users.
Following internal incident (IcM 442034193) I would propose adding the following text under "_Important things you need to know about the password expiration feature_".

This feature sets the password policy expiration for each Managed domain present on the tenant, except Federated domains. If later you add a new domain or convert a domain from Federated to Managed, this domain will not contain the password expiration policy. Whenever you convert or add a new domain, you must re-enable password expiration policy to write the password policy expiration in the new domain.

Thank you.
/Nuno

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **microsoft-365-business**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@NuAlex Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13173

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per author's comment in PR. Thanks
