### ISSUE TITLE
page accessibility issue

### ISSUE THREAD

**Issue by TCPPort25** [MicrosoftDocs/microsoft-365-docs#13161]
It feels like it's an accessibility issue when the kusto syntax relevant to the page only appears in screenshots/pictures. There are examples of kusto queries in codeblocks, however the subsequent example for how to render it in a chart format only appears in images. Fix should be that the "| render " syntax should appear in text.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6c8b2d-1fa1-0f6e-a287-bd5d534ea2a3
* Version Independent ID: 1eea0bf3-2432-d56d-016a-9f57f09e84ff
* Content: [Work with advanced hunting query results in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-query-results?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-query-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-query-results.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@TCPPort25 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13176

Once the author approves, the changes will be live.

Thanks
Sri
