### ISSUE TITLE
Typo in wsl --version 

### ISSUE THREAD

**Issue by albanytech** [MicrosoftDocs/microsoft-365-docs#13169]
Where you have written "wsl -version" it should read "wsl --version"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: accf86dd-5bfe-9e65-3b84-083eafe66f03
* Version Independent ID: accf86dd-5bfe-9e65-3b84-083eafe66f03
* Content: [Microsoft Defender for Endpoint plug-in for Windows Subsystem for Linux (WSL)](https://learn.microsoft.com/en-gb/microsoft-365/security/defender-endpoint/mde-plugin-wsl?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/mde-plugin-wsl.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-plugin-wsl.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@albanytech Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13179

Once the author approves, the changes will be live.

Thanks
Sri
