### ISSUE TITLE
Script fix required

### ISSUE THREAD

**Issue by qishengc** [MicrosoftDocs/microsoft-365-docs#13167]
[Enter feedback here]

The example script:

# Create a new batch
$batch = New-PnPBatch

# Add files to classify to the batch
foreach ($listItem in $targetItems) {
    Request-PnPSyntexClassifyAndExtract -FileUrl $listItem.FileRef -Batch $classifyBatch
}

# Execute batch
Invoke-PnPBatch -Batch $batch

Two issues:
1. $batch was created, but it was referenced as  $classifyBatch later which is undefined
2. $listItem.FileRef  could contain whitespaces, so could be improved as: "$($listItem.FileRef)" 

Should be fixed as:

# Create a new batch
$batch = New-PnPBatch

# Add files to classify to the batch
foreach ($listItem in $targetItems) {
    Request-PnPSyntexClassifyAndExtract -FileUrl "$($listItem.FileRef)" -Batch $batch
}

# Execute batch
Invoke-PnPBatch -Batch $batch

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92b31af4-e9f0-a198-1b0c-68f56c9c7e89
* Version Independent ID: 92b31af4-e9f0-a198-1b0c-68f56c9c7e89
* Content: [Use PowerShell to request processing by a custom model - Microsoft Syntex](https://learn.microsoft.com/en-us/microsoft-365/syntex/powershell-syntex-processing)
* Content Source: [microsoft-365/syntex/powershell-syntex-processing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/syntex/powershell-syntex-processing.md)
* Service: **microsoft-syntex**
* GitHub Login: @jameseccles
* Microsoft Alias: **jaeccles**

**Comment by msbemba** [comment]
@qishengc Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13174

Once the author approves, the changes will be live.

Thanks
Sri
