### ISSUE TITLE
no en_CA

### ISSUE THREAD

**Issue by MrOCanada** [MicrosoftDocs/microsoft-365-docs#13170]
In the Quarantine Global Settings there is no en-CA or English_Canada to choose. there is only English_USA and English_Great Britain. 
 We found out through testing that English_Great Britain works with mailboxes that have en_CA as the language setting.  
If you don't add English_Great Britain to  your Global Settings and have mailboxes with en_CA, they get the Microsoft canned default Quarantine Report, not one that you customize in Global Settings.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faf5c5df-c3ab-8448-aef0-af05977db9b9
* Version Independent ID: adade895-f42b-1029-9948-5ddb5b038257
* Content: [Quarantine policies](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide#step-2-assign-a-quarantine-policy-to-supported-features)
* Content Source: [microsoft-365/security/office-365-security/quarantine-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MrOCanada, that's a know issue, and I tried to cover it with the following statement:

https://learn.microsoft.com/microsoft-365/security/office-365-security/quarantine-policies#customize-quarantine-notifications-for-different-languages

> [!TIP]
> If you have a mix of mailboxes with en-US and other English languages codes (en-GB, en-CA, en-AU, etc.), use the language value English_USA in one customized quarantine notification, and the language value English_Great Britain in another customized quarantine notification.

Clearly, that's not cutting it, so I removed it and updated the first alert in that section (the second paragraph is new):

> [!TIP]
> A custom quarantine notification for a specific language is shown to users only when their account/mailbox language matches the language in the custom quarantine notification.
>
> The value **English_USA** applies only to US English clients. The value **English_Great Britain** applies to all other English clients (Great Britain, Canada, Australia, etc.).

OK?

**Comment by MrOCanada** [comment]
Hi Chris. It’s nice to see feedback is actually monitored. 😊

That is more clear, thanks for that.


Mark Orser
Senior O365 Specialist
***@***.******@***.***>
t f


[Rogers - Corporate]<http://www.rogers.com/consumer/home>

**Comment by chrisda** [comment]
Thanks for the feedback.

Closing
