### ISSUE TITLE
Customer data location not available for Microsoft Office 365 Family accounts.

### ISSUE THREAD

**Issue by yairlevy** [MicrosoftDocs/microsoft-365-docs#13181]
[Enter feedback here]
This page doesn't answer where my customer data is located. Because I can't access such settings meanwhile I'm using a Microsoft Office 365 Family account...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53f8357e-400c-d29e-0394-9bfbeea5ed9c
* Version Independent ID: 0ec5d2be-13f3-19b3-1dc5-89f92e5c4816
* Content: [Data Residency for SharePoint Online and OneDrive for Business - Microsoft 365 Enterprise](https://learn.microsoft.com/en-GB/microsoft-365/enterprise/m365-dr-workload-spo?view=o365-worldwide#how-can-i-determine-customer-data-location)
* Content Source: [microsoft-365/enterprise/m365-dr-workload-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/m365-dr-workload-spo.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@yairlevy Thank you for your feedback. This document refers to Business and enterprise customers. I'd recommend you contact your support team via the help and support option so they can provide more information about the family account.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @yairlevy Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. You can contact Microsoft support via the need help section on the admin center. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
