### ISSUE TITLE
Microsoft delisting service - enhancement

### ISSUE THREAD

**Issue by ianpmurphy** [MicrosoftDocs/microsoft-365-docs#13194]
The 365 documentation page only contains two buttons. One to provide feedback on the documentation and the other to provide feedback for MS XDR. In this case I'd like to make a suggestion which is for neither of the two but don't know where I could make the suggestion.

The delisting service works well, but it works after the event. It would be very useful if a partner could register the IPs of clients connections and could recieve an alert when an IP is blocked. This would allow us to proactively intervene rather than waiting for something to fail. 
We have quite a lot of clients with systems which deliver email to their o365 mailboxes. These are older onprem systems, like multifunction scanners, embedded devices like UPS's and older software which simply doesn't support modern authentication and we need to be able to deliver plain old smtp email to o365,

Regards
Ian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95417878-bc32-8b18-9900-6ad4f10da2a9
* Version Independent ID: 30cd3f4e-9c51-f2fa-b6c0-036756f6b99e
* Content: [Troubleshooting mail sent to Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/external-senders-mail-flow-troubleshooting?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-senders-mail-flow-troubleshooting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-senders-mail-flow-troubleshooting.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@ianpmurphy Thank you for your feedback. I understand your issue and this needs to be passed on to the product group via the main feedback portal  ( https://feedbackportal.microsoft.com/ ) . So that our dev or product team can look into this query and respond.

Hope this helps!

Thanks
Sri
