### ISSUE TITLE
permissions to upen support case got misleading information

### ISSUE THREAD

**Issue by IDCheryl** [MicrosoftDocs/microsoft-365-docs#13192]
[Enter feedback here]

in Prerequistes section, it indicates that "Roles that include the action microsoft.office365.supportTickets/allEntities/allTasks can submit a case." 
But only with this permission(for example, security operator has the premission "microsoft.office365.supportTickets/allEntities/allTasks"), premier ticket could not be logged.
Only with Service Support Administrator OR Helpdesk Administrator role can premier ticket be logged.
Suggested to remove the statement "Roles that include the action microsoft.office365.supportTickets/allEntities/allTasks can submit a case."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ceca7593-5fc2-7088-d2c3-90bacbbbed9a
* Version Independent ID: 7af76ee9-424d-1809-c8b9-d074c95f9b2f
* Content: [Contact Microsoft Defender for Endpoint support](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/contact-support?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/contact-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/contact-support.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@IDCheryl Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13216

Once the author approves, the changes will be live.

Thanks
Sri
