### ISSUE TITLE
The RPO says 15 mins, but the FAQ document says 10 mins. Need correction

### ISSUE THREAD

**Issue by vishnookumar** [MicrosoftDocs/microsoft-365-docs#13199]
**The OneDrive account and full SharePoint site mentioned the RPO as 15 mins.**

<img width="575" alt="image" src="https://github.com/MicrosoftDocs/microsoft-365-docs/assets/70580406/7e1c37ea-af32-45e8-bd6f-07feb421ac12">

 **But the FAQ says 10 mins.** 
<img width="566" alt="image" src="https://github.com/MicrosoftDocs/microsoft-365-docs/assets/70580406/19122332-7b79-4d50-b54b-8b3d80fdb59d">

**Comment by msbemba** [comment]
@vishnookumar  Thank you for your feedback. Could you please provide the URL for the document you are referring to ?

Thanks
Sri

**Comment by yogkumgit** [comment]
@vishnookumar We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by vishnookumar** [comment]
@yogkumgit please find the links below:

Restore point frequency: https://learn.microsoft.com/en-us/microsoft-365/syntex/backup/backup-restore-data?tabs=onedrive#restore-point-frequency

FAQ: https://learn.microsoft.com/en-us/microsoft-365/syntex/backup/backup-faq

**Comment by yogkumgit** [comment]
@msbemba Please update.

**Comment by msbemba** [comment]
@vishnookumar Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13309

Once the author approves, the changes will be live.

Thanks
Sri
