### ISSUE TITLE
Link is not helpful

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#132]
The link in the Note to the Modern Desktop Deployment Center just opens a marketing site for Microsoft. The aka.ms address know longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec00a1bd-2fc6-6275-b4ac-c5f7526de0c7
* Version Independent ID: 8ba861e3-c974-a765-d1ff-e07a864c990a
* Content: [Getting Started - Modern Desktop Deployment](https://docs.microsoft.com/en-us/microsoft-365/enterprise/getting-started)
* Content Source: [microsoft-365/enterprise/getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/getting-started.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by matthiaspfenninger** [comment]
Created PR #136 for this issue.

**Comment by JGruszczyk** [comment]
Addressed 136 but fixed spelling, links
