### ISSUE TITLE
API documentation for Microsoft 365 MFA 

### ISSUE THREAD

**Issue by mamoona-aslam** [MicrosoftDocs/microsoft-365-docs#13208]
Hello,
i cant find any docuemntation in regard with setting up MFA for Microsoft office 365 via API, if any reference can be provided that would be helpful.

**Comment by msbemba** [comment]
@mamoona-aslam Thank you for your feedback. As of now, per-user MFA cannot be enabled via API. We will have a documentation when the option is available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mamoona-aslam Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
