### ISSUE TITLE
correcting info

### ISSUE THREAD

**Issue by zerodrool** [MicrosoftDocs/microsoft-365-docs#1320]
#1319 
submitted pull request to correct info in article
DI=SN
DI=SO
these descriptions need to be swapped.
can provide link to technet article with example of HRDP showing SO, as well.

**Comment by mypil** [comment]
@zerodrool - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/539ac671aad7555a84ad8d27e30026de0d964273. 


Thank you for your contribution to make the docs better! Much appreciated!
