### ISSUE TITLE
the path to setup this feature is incorrect there are no endpoints in settings section.

### ISSUE THREAD

**Issue by peterwww** [MicrosoftDocs/microsoft-365-docs#13213]
there are no endpoint in settings menu
![Screenshot 2023-11-24 182253](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/4084800/ad0fc5db-44d4-4205-b186-d3ccd42aaba5)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3afb40ff-f167-1d49-443f-a971611a6340
* Version Independent ID: 3afb40ff-f167-1d49-443f-a971611a6340
* Content: [Set up web content filtering in Microsoft Defender for Business](https://learn.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-web-content-filtering?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-web-content-filtering.md)
* Service: **microsoft-365-security**
* Sub-service: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@peterwww Thank you for your feedback. We can view the endpoints under the settings

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/45987684/613679f2-86e2-469c-a263-570f7101caaf)

If you continue to have this problem, I'd recommend you contact support via the need help section on the admin center, so that they can help you out.

Hope this helps!

Thanks
Sri

**Comment by peterwww** [comment]
thanks for checking , yes it seems to be issue on my side

Kind regards,

Peter Wiktorowski
Customer Success Manager | Modern Workplace
***@***.***
+44 (20) 76608537

[cid:36679133-46d6-4c1f-8065-271dc69c89ce]

***@***.***?anonymous&ep=signature>            Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________
