### ISSUE TITLE
Benefit of using PSExec?

### ISSUE THREAD

**Issue by thomasluxton** [MicrosoftDocs/microsoft-365-docs#13211]
Page feedback 26becb70-47ff-38fe-592f-99d84f6aba12
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-vdi?view=o365-worldwide#updating-virtual-desktop-infrastructure-vdi-images-persistent-or-non-persistent

What is the benefit of using PSExec when the instructions are relating to local computer?
![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/79663182/3cd8c053-eaf7-4d2a-987e-f72dc86ac7bf)

It adds unnecessary confusion.

Regards

**Comment by msbemba** [comment]
@thomasluxton Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13253

Once the author approves, the changes will be live.

Thanks
Sri
