### ISSUE TITLE
german translation contains incorrect/misleading information

### ISSUE THREAD

**Issue by killerkarnickel404** [MicrosoftDocs/microsoft-365-docs#13218]
Hello,

I don't know if I'm in the right place for translation errors in the Microsoft 365 Admin Center. 

It is about these settings
https://learn.microsoft.com/en-us/microsoft-365/troubleshoot/miscellaneous/reports-show-anonymous-user-name 

Go to the Microsoft 365 admin center.
Go to Settings > Org Settings > Services.
Select Reports.
Clear Display concealed user, group, and site names in all reports, and then select Save.

The German technical documentation describes it correctly.
Uncheck the box to deactivate the setting so that the names are displayed. 

In the German Microsoft 365 Admin Center 

German Text is: "Ausgeblendete Benutzer-, Gruppen- und Websitenamen in allen Berichten anzeigen"
In English the text means. 
Show hidden user, group and website names in all reports

The meaning is really the opposite of the english text.
In German it means check the box so that names are displayed. Which is wrong. 

![grafik](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/72160647/15c3fcc9-3e87-4ad9-94c6-9f6fa0a94589)

Best regards,
Martin

**Comment by msbemba** [comment]
@killerkarnickel404 Thank you for your feedback. This feedback needs to be passed on to our dev team so that the wording on the admin center can be corrected. 

You can post this feedback on our main feedback portal ( https://feedbackportal.microsoft.com/) so that the dev or product team can look at it and respond.

Hope this helps!

Thanks
Sri

**Comment by killerkarnickel404** [comment]
> @killerkarnickel404 Thank you for your feedback. This feedback needs to be passed on to our dev team so that the wording on the admin center can be corrected.
> 
> You can post this feedback on our main feedback portal ( https://feedbackportal.microsoft.com/) so that the dev or product team can look at it and respond.
> 
> Hope this helps!
> 
> Thanks Sri

All right.

I've done it. 

But I'm not very confident that a solution will be found in a timely manner.
