### ISSUE TITLE
Link to techcommunity article does not work

### ISSUE THREAD

**Issue by carlos-segundo** [MicrosoftDocs/microsoft-365-docs#13214]
[Enter feedback here]

Link to https://techcommunity.microsoft.com/t5/microsoft-defender-atp/introducing-edr-in-block-mode-stopping-attacks-in-their-tracks/ba-p/1596617 does not work anymore. Maybe the blog article has been removed or put on some page way down?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba0e285e-07c9-e98f-d96b-668a82b4b9fa
* Version Independent ID: 52fde7e4-0362-eb32-712d-f3e718836232
* Content: [Endpoint detection and response in block mode](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/edr-in-block-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/edr-in-block-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/edr-in-block-mode.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by carlos-segundo** [comment]
At least one finds it in the wayback machine: https://web.archive.org/web/20221222024035/https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/introducing-edr-in-block-mode-stopping-attacks-in-their-tracks/ba-p/1596617

**Comment by msbemba** [comment]
@carlos-segundo Thank youf or your feedback. We have removed the blog as it  has been archived, the changes are done through PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13252

Once the author approves, the changes will be live.

Thanks
Sri
