### ISSUE TITLE
Download URL for eicar.com.txt file is no longer valid

### ISSUE THREAD

**Issue by f-casas** [MicrosoftDocs/microsoft-365-docs#13220]
Documentation must be updated since current download URL for the eicar.com.txt malware test file, https://www.eicar.org/download/eicar.com.txt, is no longer valid and needs to be changed because the detection test no longer works and can create confusion for customers.
The new valid URL is: https://secure.eicar.org/eicar.com.txt

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide#sles-and-variants-1)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@f-casas Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13251

Once the author approves, the changes will be live.

Thanks
Sri
