### ISSUE TITLE
Lacking *.msidentity.cn in the 21v version URL list.

### ISSUE THREAD

**Issue by sscchh2001** [MicrosoftDocs/microsoft-365-docs#13238]
My customer implemented firewall whitelist according to the URLs listed in the document.
They were blocked when accessing Microsoft Entra portal pages in 21v environment because applicationmanagement.msidentity.cn was blocked by the firewall.
The URL list in the document did NOT contain *.msidentity.cn in it, while in the public version https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide, *.msidentity.com is listed.

We would also request you to review the rest of the URL list in the 21v version document in order not to miss any further URL being used in 21v Entra services.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1248ba04-fd9a-c009-9821-94c7b7aec88b
* Version Independent ID: eec20193-ee91-0f70-2d62-a8aa99e6e84a
* Content: [URLs and IP address ranges for Office 365 operated by 21Vianet - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges-21vianet?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges-21vianet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges-21vianet.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@sscchh2001 We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).
