### ISSUE TITLE
MemberOf

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#1323]
In my testing, I had to use the proxyAddress of the group in order to get the segment to work.

I used
New-OrganizationSegment -Name "SegmentA" -UserGroupFilter "MemberOf -eq 'BlueGroup@contoso.com'"
instead of:
New-OrganizationSegment -Name "SegmentA" -UserGroupFilter "MemberOf -eq 'BlueGroup'"

Using just the group name produced the following error:

Could not run the command New-ExoInformationBarrierSegment. Cause of the problem: The group id "InfoBarrier-BlueTeam" is neither a validExternalDirectoryObjectId nor a ProxyAddress.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ef060c7-6975-955e-63f9-3b71c7bc1e74
* Version Independent ID: e75be21f-aa53-480c-158f-920413c8ff9b
* Content: [Attributes for information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-attributes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers-attributes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-attributes.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@danmyhre 
- Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.
