### ISSUE TITLE
Confusing license requirements listed

### ISSUE THREAD

**Issue by joelkino** [MicrosoftDocs/microsoft-365-docs#13237]
At the top of this page it says it applied to both DFOP1 and P2
Towards the bottom of the page it says DFOP2 license are required

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e66cb3d-b771-af2b-860f-5355b2178db0
* Version Independent ID: 7ce9307c-ca00-cb47-6978-b9b09c139978
* Content: [Automated investigation and response in Microsoft Defender for Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/air-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/air-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/air-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
@joelkino, AIR is definitely a Defender for Office 365 Plan 2 only feature. It appears that the 'Applies to' label at the top of tis (and all the other?!?) AIR-related articles was incorrectly populated with the 'Plan 1 and Plan 2' value.

I fixed them all.

Thanks for the feedback.

Closing
