### ISSUE TITLE
Update 'Policy Conflict', GP wins over MDM

### ISSUE THREAD

**Issue by azureidentity** [MicrosoftDocs/microsoft-365-docs#13232]
Can you please update the statement about the conflict handling part below?
If a conflicting policy is applied via MDM and GP, the setting applied from MDM takes precedence.

Basically, when an ASR rule setting has both MDM and GP setting, the GP value wins. Note that MDMWinsOverGPO is not working for this policy. Please help to correct the statement so that when an org has both MDM and GP, admin can understand they need to clean GP settings explicitly to allow MDM version work as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@azureidentity Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13250

Once the author approves, the changes will be live.

Thanks
Sri
