### ISSUE TITLE
SPF record for the High-risk Delivery Pool

### ISSUE THREAD

**Issue by philhead** [MicrosoftDocs/microsoft-365-docs#13233]
Please publish an SPF record for the high-risk delivery pool so that receiving MTAs can make appropriate decisions on receipt of the mail.  e.g.  untrusted.spf.messaging.microsoft.com   TXT  "v=spf1 ip4:40.95.0.0/16 -all"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2dee626-2897-aa19-46c9-8cbafa54035d
* Version Independent ID: e69c5a66-6591-d1b8-9fcc-ad303b86b415
* Content: [Outbound delivery pools](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/outbound-spam-high-risk-delivery-pool-about?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/outbound-spam-high-risk-delivery-pool-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/outbound-spam-high-risk-delivery-pool-about.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@philhead, you should open a support ticket about this. All we do here is fix documentation.
