### ISSUE TITLE
How to Configure Reviewers for Esclation

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#1324]
In the Escalate section, it says, "Escalate: ...you can choose who else in your organization should review the message. Choose from a list of configured reviewers..." Can you please add information to this article on how to configure the list of reviewers for this action? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685ef016-8eaf-a40d-73af-0fc28e072e41
* Version Independent ID: 8fbf5517-d2bc-12eb-79d0-8209130e29ec
* Content: [Investigate and remediate communication compliance alerts - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-investigate-remediate?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance-investigate-remediate.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-investigate-remediate.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@EricaToelle - thanks for the feedback. When you use the policy wizard as outlined in the Configure communication compliance in Microsoft 365 (https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure) topic (Step 4), you select reviewers available for selection later in the escalation workflow for each alert. I'll clarify in the topic that this is where these contacts are configured. Thanks!
