### ISSUE TITLE
Billing Profile -HOW Do I Create One???

### ISSUE THREAD

**Issue by MHCLV** [MicrosoftDocs/microsoft-365-docs#13246]
This page assumes that one already HAS a billing profile.  It provide no information on how to create one nor does it have a link to another article that addresses the question.

Since a billing profile is required for some actions, knowing how to create one would be very useful.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9acd5a2f-9048-c5d2-0455-69f80f5e469e
* Version Independent ID: a832f7d9-57be-0742-7eca-7a47b34f85ec
* Content: [Understand your Microsoft business billing profile](https://learn.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-billing-profiles?view=o365-worldwide#view-your-billing-profiles)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@MHCLV Thank you for your feedback. A billing profile is automatically created when a billing account is created. meaning, if you purchase licenses from Microsoft and a tenant is created, then the administrator who adds the payment method gets a billing profile created. I'd recommend you contact support via the need help section on the admin center if you don't see a billing profile for your organization.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MHCLV Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
