### ISSUE TITLE
Block Sender Functionality 

### ISSUE THREAD

**Issue by nelli-d** [MicrosoftDocs/microsoft-365-docs#1325]
As configured, users receive a daily Quarantine notification email with the "Block Sender" option for each quarantined email.  Using the Outlook 2016 client, if a user selects "Block Sender", the user's browser pops up with a message: “Spam message sender was blocked in quarantine.”  (Yes “quarantine”).

I can find no evidence that the sender is blocked in "Quarantine" but it does add the sender to the user's Junk Email Options “Blocked Sender” list in the Outlook 2016 client.  This is problematic because the Junk Email Options “Blocked Sender” list is downstream of the Quarantine. 

Effectively, it appears that the "Block Sender" option does nothing to prevent the sender from continually showing up on the user's Quarantine notification emails each day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d461271f-7f09-494f-2c35-ae6aea40b400
* Version Independent ID: 8d813e88-a96a-91b6-4fa1-7ab77719ea31
* Content: [Configure end-user spam notifications in EOP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-eop?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@nelli-d - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
