### ISSUE TITLE
OMS Agent Guidance Down-level Servers

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/microsoft-365-docs#13266]
Is there any guidance around OMS deprecation and Windows Server 2016 and below? Current docs only provide information on using the OMS agent and I didn't see anything about migrating to AMA for ATP workloads.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3985e3b-6df1-892c-be7c-8b1f079b4053
* Version Independent ID: 61fee405-9ccd-cf53-4aa1-4c5e98f09cf7
* Content: [Onboard previous versions of Windows on Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-downlevel?view=o365-worldwide#configure-and-update-system-center-endpoint-protection-clients)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-downlevel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-downlevel.md)
* Service: **defender-endpoint**
* Sub-service: **onboard**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@johnjohnjohn87 Thank you for your feedback. Currently, We do not have documentation around migrating to AMA for ATP workloads. We will update you once it is made available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @johnjohnjohn87 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
