### ISSUE TITLE
MCA vs MOSA refund process

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/microsoft-365-docs#13265]
MCA vs MOSA - - if its yearly subscription  or term if we can after 7 days inbetween the year or stop the payment. 
Please confirm when refund is processed  and when it cannot be processed ?
Article missing refund process, previous we used to get prorated refund .
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a91e3ae5-842c-fb3d-8c27-d8001122aee8
* Version Independent ID: ddccec72-7088-4207-60cb-986a35becb67
* Content: [Cancel your Microsoft business subscription in the Microsoft 365 admin center](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/cancel-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/cancel-your-subscription.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @robinpoulose1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
