### ISSUE TITLE
Bookings problem

### ISSUE THREAD

**Issue by syarnellYIrsch** [MicrosoftDocs/microsoft-365-docs#13278]
[Enter feedback here]

I don't see where I can change the permissible days of the calendar to allow customers to book an appointment using Bookings.   I want to only allow bookings from Jan 1 to Jan 31.  I can't see how to do this.

Thanks

Steven
ps  I'm also puzzled why MSFT keeps asking me about Learnings or something.  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93466e00-def6-6d4c-6705-04cb62a32945
* Version Independent ID: 4e862a20-81c3-991d-6d6f-343b99503408
* Content: [Set Bookings scheduling policies](https://learn.microsoft.com/en-US/microsoft-365/bookings/set-scheduling-policies?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/set-scheduling-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/set-scheduling-policies.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@syarnellYIrsch Thank you for your feedback. For How to questions and technical problems, we recommend you to create a support ticket via the need help section on the admin center, so that our support team can assist you in fixing them.

Hope this helps!

Thanks
Sri
