### ISSUE TITLE
Not available in ZAF (South Africa)

### ISSUE THREAD

**Issue by matopablo** [MicrosoftDocs/microsoft-365-docs#1327]
Can we please update the doc to make the same statement for SouthAfrica than Germany and Switzterland? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7b7a25a-4cf8-1b51-0c40-6afa334ca537
* Version Independent ID: 0033b96f-ee7b-0e9f-5287-4a5371ce3734
* Content: [FAQ about importing PST files to Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/faqimporting-pst-files-to-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/faqimporting-pst-files-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/faqimporting-pst-files-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
Closing as per internal discussion that we only document were PST import is available.
