### ISSUE TITLE
Link to  Microsoft 365 Defender portal is incorrect

### ISSUE THREAD

**Issue by DoubleTom** [MicrosoftDocs/microsoft-365-docs#13289]
[Enter feedback here]
The link to page [Microsoft 365 Defender portal](https://sip.security.microsoft.com/homepage?tid=72f988bf-86f1-41af-91ab-2d7cd011db47) is incorrect. It has the tenant id in the url and it points to Microsoft's own tenant.
Correct link would be https://security.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fddea032-93aa-03fd-bd1f-e0462940f104
* Version Independent ID: 3738069f-2e32-6c04-0f07-77b8bb46edaf
* Content: [Review the results of Microsoft Defender Antivirus scans](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/review-scan-results-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/review-scan-results-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/review-scan-results-microsoft-defender-antivirus.md)
* Service: **defender-endpoint**
* Sub-service: **ngp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@DoubleTom Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13303

Once the author approves, the changes will be live.

Thanks
Sri
