### ISSUE TITLE
"ASR rules supported operating systems" section contains wrong information

### ISSUE THREAD

**Issue by theonlybrand** [MicrosoftDocs/microsoft-365-docs#13292]
The following policies do not apply to Windows Server 2016 via Security Settings Management
- Block JavaScript or VBScript from launching downloaded executable content
- Block persistence through WMI event subscription
- Block Win32 API calls from Office macros

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Version Independent ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Content: [Attack surface reduction rules reference](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md)
* Service: **defender-endpoint**
* Sub-service: **asr**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@theonlybrand Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/13304

Once the author approves, the changes will be live.

Thanks
Sri
