### ISSUE TITLE
Upgrading Windows 10 Home to Pro with M365 Business?

### ISSUE THREAD

**Issue by jebeld17** [MicrosoftDocs/microsoft-365-docs#133]
So, the content states a lot about the benefits of M365 giving users an upgrade to 10 Pro, if and only if they are on 7, 8, or 8.1 Professional -- But what about users currently on a Windows 10 Home SKU? If not, is there a 'why?'

I really think info like this would be beneficial to be documented in the FAQ.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059b7d44-f860-cfbe-86f2-e0e86ed612b3
* Version Independent ID: 08c38e6f-6f5a-0ac3-3570-ababa09c1110
* Content: [Microsoft 365 Business Frequently Asked Questions ](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @jasongroce
* Microsoft Alias: **jasgro**

**Comment by mrialsjr** [comment]
The problem with the Windows portion is that a Virtual desktop environment requires Windows 10 Enterprise which is a different animal than Pro. Although the Microsoft 365 license now allows the virtualization of the Windows install the benefits of it are lost without going to E3 and if you're in an environment that will never exceed 300 users there is gap of functionality for users caught in this gap.

**Comment by jebeld17** [comment]
The page documentation should address this. I feel like there's little to no documentation warning users that Pro is required for the upgrade.

**Comment by lizap** [comment]
Thanks for the feedback. The pre-reqs for M365 are doc'd here: https://docs.microsoft.com/en-us/microsoft-365/business/pre-requisites-for-data-protection. I've passed along your feedback to the content team - they'll include this change in the next update to the content. Thanks, Liza
