### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by millh0use** [MicrosoftDocs/microsoft-365-docs#1331]
The link for "Read WCAG reports for all our products and services." is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0368ee0-d8ae-cae1-c4a8-40c1e755b920
* Version Independent ID: 3ad2d527-8a1c-55c1-a40b-6b3876b468df
* Content: [Web Content Accessibility Guidelines - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-wcag-2-1?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-WCAG-2-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-WCAG-2-1.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@millh0use - thanks for the feedback, updating the topic with the correct link (https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/).
