### ISSUE TITLE
Teams compliance records

### ISSUE THREAD

**Issue by 12Knocksinna** [MicrosoftDocs/microsoft-365-docs#1333]
Conversations are not stored in EXO folders. The items held in the Team Chat folder are compliance records - they are imperfect copies of conversations and only exist in EXO to allow searches to be performed against their content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae0d608-5520-a99d-808e-c2cb475f015c
* Version Independent ID: b46ea38d-2ee8-4ade-8949-05d77a6c9e77
* Content: [Content stored in Exchange Online mailboxes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-is-stored-in-exo-mailbox?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/what-is-stored-in-exo-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-is-stored-in-exo-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@12Knocksinna Thanks for the feedback. Article has been updated in attempt to address your feedback.
