### ISSUE TITLE
 Lab Kit broken

### ISSUE THREAD

**Issue by valandilis** [MicrosoftDocs/microsoft-365-docs#1334]
Hello all,

Thanks for doing this.

This one has a few issues for me.
Yes, the file downloads fine, tried a second time just in case.
But the lab builds partially, no clients are created, but their vhdx are exported in the root folder.
The odd one, I created the client's folders manually and the installation was successful.

Another issue now is that the ADUC and GPMC are extremely slow to respond and to perform any tasks.
Also, the client's licenses show as expired.

Regards,

**Comment by mypil** [comment]
@valandilis - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by valandilis** [comment]
My bad, I just saw the page has an add feedback here tab: 

https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide#feedback

**Comment by mypil** [comment]
@valandilis - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
