### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/microsoft-365-docs#1335]
Hi team - a number of the download links are broken - file links below the images. The ones above the poster images are OK :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9377794-433d-4522-0b01-e9182283019a
* Version Independent ID: 9d9134d2-adaf-64df-ab10-780d9e5ca1b1
* Content: [Microsoft 365 for enterprise overview - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-overview?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-overview.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
These have been fixed. Thanks for letting us know.
