### ISSUE TITLE
Australia Bank Account Number Type incomplete

### ISSUE THREAD

**Issue by caiodaruizcorrea-avanade** [MicrosoftDocs/microsoft-365-docs#1336]
It seems that the "Australia Bank Account Number" type hasn't been fully setup with its keywords.
It might have been copied from other countries such as the US details (usa account) which is not relevant.
It would be great to have the Australian keywords such as Bank Account Number, Bank Account, Account Number, Savings Account, BSB, and so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [What the sensitive information types look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for?view=o365-worldwide#us-bank-account-number)
* Content Source: [microsoft-365/compliance/what-the-sensitive-information-types-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @caiodaruizcorrea-avanade 
Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365/Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
