### ISSUE TITLE
Audit events RecordType

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/microsoft-365-docs#1337]
Folks, the events I'm seeing in the audit log have a RecordType of "Discovery", not "DataGovernance" as suggested above. In addition, multiple events with the "AeD" RecordType are generated when working with policy matches, so you might want to include those as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea1461c-a9db-d934-d5a6-169360842e8b
* Version Independent ID: 6b214386-6f18-9de6-7a8b-b78e69d1387a
* Content: [Communication compliance feature reference - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-feature-reference?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance-feature-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-feature-reference.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@michevnew - thanks for the feedback. This is a good point and we've updated the PS examples in the Auditing section (https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-feature-reference) to reflect different record type queries. Thanks again!
