### ISSUE TITLE
Clarification needed on Teams data

### ISSUE THREAD

**Issue by turnma** [MicrosoftDocs/microsoft-365-docs#1338]
The article states that only Exchange/SharePoint/ODfB are in scope.  But it also says that Lockbox is used when "customer content" is accessed, and the definition of customer content in the article includes items such as "Skype for Business presentation file body" and "Instant messages (IM) or voice conversations", both of which sound more like SfB/Teams data.  Some Teams data is presumably protected because it's held in SfB, but clarification would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Office 365 Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by VLG17** [comment]
@turnma For Teams all "customer content" is saved in either Azure (Cosmos DB, Blob Storage, etc) or Office 365 (SharePoint, Exchange) according to [this article](https://docs.microsoft.com/en-us/microsoftteams/location-of-data-in-teams#location-of-teams-data-at-rest)

I assume it's the same for Skype for Business, although i cannot find a similar article. 

It's think it's also worth mentioning that Skype for Business Online will reach "End of Life" on July 31, 2021, so the focus is and will continue to be on Teams.

Keeping all of this in mind, i think what's stated in the mentioned article is correct. What do you think? Should we still add something to it?

**Comment by mypil** [comment]
@turnma - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
