### ISSUE TITLE
Does the static IP have to be unique?

### ISSUE THREAD

**Issue by xivizi** [MicrosoftDocs/microsoft-365-docs#1339]
Does the 'static IP' as referred to in the section 'Update DNS records in the Microsoft 365 admin center' have to be a unique static IP?  

I already have a static IP address but it has 5 separate websites (different domains) on this static IP address each with their own separate SSL cert.

Would this current static IP be OK or do I have to get another static IP specific to the public domain?

Clarification would be appreciated.  Thank you

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f087dd43-183d-08bb-37d7-d893bede6efb
* Version Independent ID: be429837-0300-3de8-6c7d-2da2fabc2c17
* Content: [Update DNS records to keep your website with your current hosting provider](https://docs.microsoft.com/en-gb/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by xivizi** [comment]
... just to clarify, each of the existing 5 domains on the static IP address has its own cPanel account.  Thank you

**Comment by msbemba** [comment]
@xivizi Thank you for your feedback. As the document suggests you will need to make these changes only Office 365 manages your DNS records, to route traffic to an existing public website hosted outside of Office 365,  If o365 manages your DNS records then static IP would work(even if it has multiple websites on the same IP).

 If you manage your DNS records directly on the Cpanel you don't have to worry about the steps in this topic. Your website stays where it is and people can still get to it.

Hope this helps!
Thanks
Sri

**Comment by xivizi** [comment]
@msbemba - Thank you for the clarification and yes, you have answered and resolved my question perfectly - very much appreciated.  

Please close this thread.

**Comment by mypil** [comment]
@xivizi - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba  so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
