### ISSUE TITLE
Correction required

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/microsoft-365-docs#134]
prioritize what you to move - should be "prioritize what you want to move" in the first line of this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0c748-09b6-1a61-6c01-4fafd1e47160
* Version Independent ID: f0a98175-92fd-ae6e-5bdd-ab1de2435d3d
* Content: [Step 1 - Device and App Readiness](https://docs.microsoft.com/en-us/microsoft-365/enterprise/step-1-device-and-app-readiness#feedback)
* Content Source: [microsoft-365/enterprise/step-1-device-and-app-readiness.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/step-1-device-and-app-readiness.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by matthiaspfenninger** [comment]
Created PR #136 for this issue.

**Comment by JGruszczyk** [comment]
Updated spelling and fixed typo + broken links
