### ISSUE TITLE
Guest users

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/microsoft-365-docs#1340]
Users in a tenant require the security addons or E5, but what about guest users in the tenant? Is there a 1 to 5 license ratio or what retention time if any are advanced compliance features available? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518cc4fa-16a4-9793-530f-fcc371273a2d
* Version Independent ID: f07fb0ad-85a3-7159-d9b1-77d188b3d5f0
* Content: [Set up users and cases in Office 365 Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@eschrader  Please see: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#advanced-ediscovery

Adding users as custodians to an AeD requires that users are licensed appropriately.
