### ISSUE TITLE
Incorrect Content

### ISSUE THREAD

**Issue by Robright** [MicrosoftDocs/microsoft-365-docs#1342]
The following highlight is incorrect: "If a person isn't a member of one of these eDiscovery-related role groups, or isn't a member of a role group that's assigned the Reviewer role, you can't add them as a member of an eDiscovery case."

You can add users to cases who don't have these permissions, but they just won't see the eDiscovery menu-option in the Security & Compliance center. You can assign the permissions after adding them to a case and, after the new permissions propagate, they'll see the menu items appear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24e97a56-f8f5-3725-cfda-954ec3ba71f6
* Version Independent ID: 0626a65e-d55d-48c7-90fe-1f982a18d729
* Content: [Manage eDiscovery cases in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery-cases?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/ediscovery-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Robright Thanks for the heads up. Article has been updated.
