### ISSUE TITLE
Incorrect content

### ISSUE THREAD

**Issue by Robright** [MicrosoftDocs/microsoft-365-docs#1343]
The following is incorrect: "As previous explained, only users who are members of the Reviewer or eDiscovery Manager role groups can be added as members of the case. "

You can add members to the cases without them having these permissions; they just won't be able to see the eDiscovery menu option when they go to the Security & Compliance center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24e97a56-f8f5-3725-cfda-954ec3ba71f6
* Version Independent ID: 0626a65e-d55d-48c7-90fe-1f982a18d729
* Content: [Manage eDiscovery cases in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery-cases?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/ediscovery-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Robright Thanks for the heads up. Article has been updated.
