### ISSUE TITLE
Incorrect value was updated

### ISSUE THREAD

**Issue by raaghavvv** [MicrosoftDocs/microsoft-365-docs#1345]
There was DI=SN set to the "message was routed through the HRDP". This is my first time i've noticed incorrect Microsoft Article. I had submit a request to the support to change it to DI=SO as my research says it should be DI=SO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58f8e2c-428a-4d8e-e8b7-a0342a0038db
* Version Independent ID: 6e7fab1b-1e24-9e36-176d-c3fb14f233a7
* Content: [Message trace in the Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/message-trace-scc.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/message-trace-scc.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@raaghavvv, are you saying the topic as currently written is correct or incorrect?

**Comment by raaghavvv** [comment]
It’s correct now, it’s updated on Friday. Prior to that it was incorrectly updated, I had to open a ticket with Microsoft to correct it.

**Comment by mypil** [comment]
@raaghavvv - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/0341d95. 


Thank you for your contribution to make the docs better! Much appreciated!
