### ISSUE TITLE
What subscription do you have to have?

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/microsoft-365-docs#1346]
Please indicate what subscription minimum is required for this feature (e.g. Office 365 E1, Microsoft 365 E3, etc.)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd283c0e-1421-d45d-83de-db7210a43936
* Version Independent ID: 33f52f1e-86e1-8b07-5420-4549597f3d63
* Content: [Communication compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-ca/microsoft-365/compliance/communication-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@giterdn - thanks for the feedback, the subscription requirements are outlined in the Before You Begin section on the Getting Started topic here (https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure).
