### ISSUE TITLE
'Unlicensed users with Exchange mailboxes or archives' filter not working

### ISSUE THREAD

**Issue by johnm-office** [MicrosoftDocs/microsoft-365-docs#1348]
All unlicensed users with mailbox showing in the exchange admin center are not displayed when we select this specific filter in O365 admin center &gt; Active users. Is this a know issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c070b6fc-af4d-3f7e-42d6-86bf0f450a9b
* Version Independent ID: 3545ea9f-7ae1-e5ab-94ed-b3aea7bbf2c1
* Content: [Create, edit, or delete a custom user view in Office 365](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/create-edit-or-delete-a-custom-user-view?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/create-edit-or-delete-a-custom-user-view.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/create-edit-or-delete-a-custom-user-view.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@johnm-office Thank you for your feedback. I was able to repro the issue, I'll keep you updated.

Thanks
Sri

**Comment by msbemba** [comment]
@johnm-office We got an update from the author that this doesn't show shared mailboxes which arent licensed Instead There are definitely scenarios under which this can be a Thing; we identified the following situations where we can have mailboxes in such state:

The mailbox has been recently migrated to O365 but the license was not assigned
The mailbox has been created using the new-mailbox CMDlet recently, and a license has not been assigned
We provisioned mailbox for user-created on-prem with New-RemoteMailbox command.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@johnm-office - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/3e2bb6fffeed1bec4231f589d25e3e822492709e. 


Thank you for your contribution to make the docs better! Much appreciated!
