### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by musiq787** [MicrosoftDocs/microsoft-365-docs#1350]
Hi Team, this article specifies required licenses as Microsoft 365 E5 or Office 365 E3 with Advanced Compliance Add-On. Can you please confirm if this product is also available as part of the Office 365 E5 license? Organisations may not need to upgrade to Microsoft 365 E5 because they don't need additional Windows 10 or EMS features. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42670ffb-8024-7cc2-cb1b-27cec02cc223
* Version Independent ID: fa22f173-b62e-93cb-62f2-e6ad0b4739d8
* Content: [Configure communication compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/communication-compliance-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-configure.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@musiq787 - thanks for feedback. We've actually just clarified and updated this in the topic, the new addition addresses your feedback. 

"Before you get started with communication compliance, you should confirm your Microsoft 365 subscription. Users included in communication compliance policies must have a Microsoft 365 E5 Compliance license, an Office 365 Enterprise E3 license with the Advanced Compliance add-on, **or be included in an Office 365 Enterprise E5 subscription**, or be included in a Microsoft 365 E5 subscription."

Thanks again!
