### ISSUE TITLE
SOC 2 implementation cost in Azure.

### ISSUE THREAD

**Issue by Jayesh040** [MicrosoftDocs/microsoft-365-docs#1351]
Can anyone please help me with SOC 2 implementation cost in Azure, Also the pre-requisites and how can we implement the SOC 2 compliance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09c26ea6-a3a4-0ad3-57db-f6b713738e2b
* Version Independent ID: 4856d3b2-bdec-a8c8-0a3b-3e2d89f117f1
* Content: [Service Organization Controls (SOC) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-soc?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-SOC.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-SOC.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@Jayesh040 - thanks for your feedback and I apologize for the long delay with an answer. I'm trying to see if there is other guidance that I can point you to instead of just pointing to Microsoft Support. Thanks for your patience!

**Comment by robmazz** [comment]
@Jayesh040 - I spoke with the Azure Team and unfortunately, there isn't a way to produce guidance to accurately cover the costs for organizations in way that would be accurate for specific customers. Organizations are just too varied to make this practical. Please see the Azure SOC 2 reports linked in the offering (https://gallery.technet.microsoft.com/Overview-of-Azure-c1be3942) for overall compliance details and we recommend that you engage with a Microsoft Partner for help implementation for your specific circumstances.
