### ISSUE TITLE
Which is right?

### ISSUE THREAD

**Issue by feetsdr** [MicrosoftDocs/microsoft-365-docs#1352]
This page 

https://www.microsoft.com/en-us/microsoft-365/blog/2014/11/12/office-2013-updated-authentication-enabling-multi-factor-authentication-saml-identity-providers/

makes it sound like the registry entries mentioned above shouldn't be needed because:

Later this month (back in 2014) we will release an update to the Office 2013 Windows client applications that enables new authentication flows, including support for Multi-Factor Authentication (MFA). 

But I still needed to do the registry changes. in 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac88f29-99a5-317d-2686-cc9534194a19
* Version Independent ID: 753c4eff-ddb3-6261-35f9-4a60b65d7147
* Content: [Enable Modern Authentication for Office 2013 on Windows devices](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by feetsdr** [comment]
Oh, and in setting up this comment, I had to create a github account.  I'd have thought since github is owned by microsoft it would take my microsoft account?  That wasn't the case.

**Comment by msbemba** [comment]
@feetsdr Thank you for the feedback. You can refer to Getting the update part on the document which talks about the update back in 2014. By default the new ADAL based authentication stack is disabled. The new authentication features must be enabled on each client machine and also for the Office 365 tenant that you are connecting to. 

Thanks
Sri

**Comment by mypil** [comment]
@feetsdr - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba  so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
