### ISSUE TITLE
Subscription Requirements?

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/microsoft-365-docs#1353]
It would be useful to have info on the page that indicates which subscription levels can use this feature (or a link to a page that explains that).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd695b47-a713-a904-9f2e-9c6c3e27bb18
* Version Independent ID: 60198f81-59f6-5ad2-53ea-a4d352125026
* Content: [Overview of the Advanced eDiscovery solution in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/overview-ediscovery-20?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/overview-ediscovery-20.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/overview-ediscovery-20.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Beschorr Please see: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#advanced-ediscovery

Will look into adding a link to this service description in overview topic.
