### ISSUE TITLE
Misspell

### ISSUE THREAD

**Issue by Robright** [MicrosoftDocs/microsoft-365-docs#1354]
"Over time, the list of custodians and their data sources may increase or decreasse"; decrease is misspelled. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a53db-59c2-5fdf-107b-a396acea8099
* Version Independent ID: 3d8adbaf-c351-1948-6a67-b54223cabde7
* Content: [Work with custodians in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/managing-custodians?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/managing-custodians.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/managing-custodians.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Robright Thanks for heads up. For typos, you can also fix these and then submit a pull request.

**Comment by Robright** [comment]
Thanks Mark! I didn’t know I could do it myself. 😊 Thanks for the heads-up…

Thanks,

Rob


[cid:image001.jpg@01D5F171.FCD084A0]

Rob Bright




Sr Premier Field Engineer (SharePoint)
Mobile:   513-312-6260
rob.bright@microsoft.com<mailto:rob.bright@microsoft.com>

If you have feedback of any kind, please email my manager, Tammy Calvin<mailto:tammyc@microsoft.com>

**Comment by Robright** [comment]
Hey Mark, quick question: Do you have a link on submitting these via a pull request?

Thanks,

Rob


[cid:image001.jpg@01D5F182.038D6BE0]

Rob Bright




Sr Premier Field Engineer (SharePoint)
Mobile:   513-312-6260
rob.bright@microsoft.com<mailto:rob.bright@microsoft.com>

If you have feedback of any kind, please email my manager, Tammy Calvin<mailto:tammyc@microsoft.com>
