### ISSUE TITLE
Date Governance should be Data Governance

### ISSUE THREAD

**Issue by DragonSpeedTheB** [MicrosoftDocs/microsoft-365-docs#1355]
Twice in this document:

Go to the Date governance &gt; Retention page in the Security & Compliance Center

This should be:

Go to the *Data* governance &gt; Retention page in the Security & Compliance Center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the Recoverable Items folder of cloud-based mailboxes on hold - Admin Help - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@DragonSpeedTheB Thanks for the heads up. Not only was "data" misspelled but this node in the SCC is now called "Information governance". Updated topic should be live later today or by tomorrow.
