### ISSUE TITLE
Commands Missing

### ISSUE THREAD

**Issue by tsullyman** [MicrosoftDocs/microsoft-365-docs#1356]
"Get-AzureADDirectorySetting : The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet"

Getting this, fixed by uninstalling azuread and installing azureadpreview but this is not clear enough in the doco.

**Comment by denisebmsft** [comment]
Hello @tsullyman, can you tell us to which article this feedback applies? That will help us route this issue to the correct writer. Thank you!

**Comment by mypil** [comment]
@tsullyman - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
