### ISSUE TITLE
Avoid (globally) spam classification when a recipient of an e-mail sends be back an answer

### ISSUE THREAD

**Issue by catshout** [MicrosoftDocs/microsoft-365-docs#1357]
Dear all,

we started using Office365 Business in our company. I send an e-mail to an external recipient. This recipient sends me a reply. Despite I've sent the e-mail before the reply is being flagged as SPAM and moved into my Junk folder.

Is there a global setting, that recipients of e-mails are automatically whitelisted to avoid that every user must whitelist every recipient manually?

Many thanks in advance.
Gerald

**Comment by mypil** [comment]
@catshout - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by catshout** [comment]
@mypil I'm referring to https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide

**Comment by mypil** [comment]
@catshout - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
