### ISSUE TITLE
No need Exchange hybrid delpoyment for searching

### ISSUE THREAD

**Issue by mikumeda** [MicrosoftDocs/microsoft-365-docs#1358]
It says that you can use Teams chat application if you have Exchange hybrid deployment in this Docs.
But as a fact, the written requirements and limitaions doesn't say you need to have Exchange hybrid deployment, and I say that you do not need such an environment, you just only need a dir sync environment for the search.
The picture in "How it works" and the writing may leed that you need a hybrid deployment, so would you fix the picture and add the description that YOU DON'T NEED a hybrid deployment?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0bb4d7-d9fa-ae92-d3ca-246147d1434a
* Version Independent ID: 7ba20db3-55e2-3d29-2d6c-6f68a6b577a8
* Content: [Searching cloud-based mailboxes for on-premises users in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mikumeda Thanks for feedback. We'll see if we can update topic about DirSync. One of the points this article is trying to make is that you can use cloud-based eDiscovery tools to search for Teams-related content even though a user might not have a cloud-based mailbox (in which Teams contents is associated with and can be returned in search results when searching mailboxes). An Exchange hybrid deployment is a typical scenario where on-premises users may not have cloud-based mailboxes. In your environment, what is DirSync synching?

**Comment by markjjo** [comment]
@mikumeda Based on our offline conversation, I will investigate updating this topic to address non-hybrid deployments, and then update the topic accordingly. I will follow up on this GitHub issue if/when topic is updated.
