### ISSUE TITLE
New Compromised User report details missing

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/microsoft-365-docs#1359]
In MC203355 there is notice about a new Compromised Users Report that is not documented on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e62b98-5f0c-8fc3-8163-c028fa5a6445
* Version Independent ID: b8262fa8-ff97-db0a-b2b5-4dd624fb057b
* Content: [View reports for Office 365 Advanced Threat Protection, malware reports, phish reports, compromised accounts, URL protection status, threat reporting, report threats - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-reports-for-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-reports-for-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-reports-for-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by kellybos** [comment]
Disregard. Information about this report is now available here with a link from the SCC - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-email-security-reports?view=o365-worldwide#compromised-users-report-new.

**Comment by mypil** [comment]
@kellybos - Thank you for submitting feedback.

From your last comment, it appears that you found the resolution of your issue so I will go ahead and close this issue.

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.
