### ISSUE TITLE
Still incorrect steps.

### ISSUE THREAD

**Issue by agoldenlife** [MicrosoftDocs/microsoft-365-docs#1360]
Already had an issue for this #1076.  So I will create a new one and reiterate to get it fixed as the old one is closed. 

Section, "What does an illicit consent grant attack look like in Office 365?"
Sub section, "Steps for finding signs of this attack"

**Step 4 is not correct.**  

- First you must click a "Filter Results" button.  
- Next you must put something into one of the columns 
    - Column choices are: Date, IP Address, User, Activity, Item, Detail. 
    - Clarify what is to be typed in what field.  

The results will then filter based on what you type into the filter.

Existing page specifies none of this and what should be used to filter is unintelligible.

If whomever updates the document would actually open the page it would be painfully obvious.

I will enter more tickets so as not to confuse anyone for other issues still existing that have not been fixed.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66854a7-7556-9b2a-0a33-886e3d881047
* Version Independent ID: 7ce3d8d5-cece-0b6f-68d5-143e12a3fff8
* Content: [Detect and Remediate Illicit Consent Grants in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Hello @agoldenlife James 👍 how are you?
I will take a look and get back.

**Comment by get-itips** [comment]
Hello @MSFTTracyP How are you?

Tried to follow the steps currently outlined in the article in my lab tenant.

It is true that the steps need a correction, as @agoldenlife James kindly says here, once you get to step 4, you need to Click on "Filter Results" button,  and next, you have to type something on a column. (Which I can suspect is _Activity_.). That is something I can fix thru a PR easily.

However, on my lab tenant, I consented an app to force an event of type _consent grant_ or similar to appear, and, I could not recognize a oAuth2PermissionGrant event, only a _User Logged in_ activity appeared and in ExtendedProperties an OAuth2:Authorize RequestType, this was the most closed I could get.

Can you kindly shed some light here on the exact type of activity that should we filter for on the audit log? I appreciate.

**Comment by MSFTTracyP** [comment]
Hi there. Thanks for your feedback, and for the valuable testing that's rendering that feedback. That's very useful for articles like these. I'd like to let you know, @agoldenlife and @get-itips, that I'm looking into your questions right now. Please let me know if you notice any other inaccuracies, and I'll update the thread when I have answers for each of these!

**Comment by get-itips** [comment]
> Hi there. Thanks for your feedback, and for the valuable testing that's rendering that feedback. That's very useful for articles like these. I'd like to let you know, @agoldenlife and @get-itips, that I'm looking into your questions right now. Please let me know if you notice any other inaccuracies, and I'll update the thread when I have answers for each of these!

Hello Tracy, I could finally log the _Consent to application._ event in my demo tenant, it is indeed of type activity, I will propose a Pull Request into the article for your to review. Thank you!

**Comment by MSFTTracyP** [comment]
@get-itips Thank you for letting me know! I would think, as it took a bit of work to sort out how this was done, that entering how to find this in the PR is valuable knowledge. Testing like yours is how we keep this information useful for everyone. Thank you so much for coming in here and letting me know how your testing was going! Please keep in touch!
