### ISSUE TITLE
Please include more information about Compromised User report

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/microsoft-365-docs#1361]
Can you share further details on the guidelines for restricting or considering users compromised?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69178933-1820-f17d-5efd-0ba9d55c3654
* Version Independent ID: a6766bb0-e49f-f0fe-0d81-67383e22a854
* Content: [View email security reports in the Security & Compliance Center, Compromised users, Encryption, Threat Protection Status, malware detections, Top malware, spam detection, sent and received email, user reported messages, read reports, detection, security data, security information - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-email-security-reports?view=o365-worldwide#compromised-users-report-new)
* Content Source: [microsoft-365/security/office-365-security/view-email-security-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-email-security-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@kellybos  Thank you for your feedback. This document pertains to activity reports. If you need details about responding to a compromised account below document will be handy. Let us know.


https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide

Thanks
Sri

**Comment by mypil** [comment]
@kellybos  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
