### ISSUE TITLE
Is M365B included Intune full license?

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/microsoft-365-docs#1362]
Hello,

There are written in this page like this.
---
Does Microsoft 365 Business include the full capabilities of Microsoft Intune?
Yes, Microsoft 365 Business subscribers are licensed to use full Intune capabilities for iOS, Android, MacOS, and other cross-platform device management. Features not available in the simplified management console in Microsoft 365 Business, like third-party app management and configuration of WiFi profiles, VPN certificates, can be managed in the full Intune console.
---

However in this page, there are written like this
https://docs.microsoft.com/ja-jp/configmgr/core/understand/product-and-licensing-faq
---
Configuration Manager isn't included in the Microsoft 365 Business plan.
---

Normally, Intune include Configuration Manager. However Intune in M365B does not include Configuration Manager. Therefore I think we can not say "Microsoft 365 Business subscribers are licensed to use full Intune capabilities"

Thank you

**Comment by mypil** [comment]
@takeakitake - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@takeakitake - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.

**Comment by takeakitake** [comment]
This article
https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs?view=o365-worldwide

Thank you
