### ISSUE TITLE
This page has not been updated in over 2 years and the Notification email structure is not correct

### ISSUE THREAD

**Issue by stuartschifter-AMA** [MicrosoftDocs/microsoft-365-docs#1363]
This page has not been updated in over 2 years and the Notification email structure no longer matches production

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98aa8fb0-57c8-f677-6543-2162cece3f4c
* Version Independent ID: cc5328d9-91c1-4f68-ef03-abafe1eb9ac4
* Content: [Sample notification when a sender is blocked sending outbound spam - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/sample-notification-when-a-sender-is-blocked-sending-outbound-spam?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/sample-notification-when-a-sender-is-blocked-sending-outbound-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/sample-notification-when-a-sender-is-blocked-sending-outbound-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@stuartschifter-AMA Thank you for your feedback. please let us know which part of the document you think needs an update as it has been updated recently.

Thanks
Sri

**Comment by chrisda** [comment]
@stuartschifter-AMA, you're right. I un-published the topic.

Thanks for the feedback.

Closing
