### ISSUE TITLE
Privacy statement

### ISSUE THREAD

**Issue by fuytters** [MicrosoftDocs/microsoft-365-docs#1364]
Hello, I was wondering if you have a privacy statement around the process of end-user submitting emails to your platform using the Report Message Add-in for Microsoft Outlook? What is actually submitted and how is it processed? Thanks in advance for clarifying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b12c078-eccb-7786-dec6-ea1bdb91d088
* Version Independent ID: aa1e8002-a8db-383e-cbeb-abf92c033bd3
* Content: [Submit spam, non-spam, and phishing scam messages to Microsoft for analysis - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@fuytters, the privacy policy link is available on the **Select add-in** page (step 4 in the [Get and enable the Report Message add-in for your organization](https://docs.microsoft.com/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide#get-and-enable-the-report-message-add-in-for-your-organization) section.  I'll include it here:

<https://privacy.microsoft.com/privacystatement>

Thanks for the feedback.

Closing
