### ISSUE TITLE
Missing audit activities

### ISSUE THREAD

**Issue by BrunoDrljanovcan** [MicrosoftDocs/microsoft-365-docs#1365]
Not all existing audit activities are listed.

e.g. **Exchange admin audit log** type does not have any activity listed.
Also activities from **Security and Compliance** center that exist like RemoveRetentionComplianceRule, NewSupervisoryReviewRule etc. 

There are for sure more that exist but are not listed as well. It would be nice to have all existing audit activities listed here in one place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@BrunoDrljanovcan Thanks for the feedback. In both of these cases that you cite (Exchange admin and Security&ComplianceCenter), these activities result from running PowerShell cmdlets, which are too numerous to include in this topic. In both cases, these activities are already documented in that the cmdlet is documented at https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell?view=exchange-ps. You can go to that page and search for cmdlets such as Remove-RetentionComplianceRule and New-SupervisoryReviewRule.

**Comment by BrunoDrljanovcan** [comment]
I understand, thank you for quick response.
