### ISSUE TITLE
Reduced Admin Portal functionality

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#1367]
"Devices that are out of compliance" section states that Admin Portal functionality will be reduced until new devices are deployed. Does that mean functionality is reduced ONLY for the out of compliance devices and not Current devices?
What does reduced functionality mean in practice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c9bf7d-827d-5c9c-9753-ab3613eeb952
* Version Independent ID: 889b6ae7-3283-0597-569d-ac178ff2289d
* Content: [Microsoft Managed Desktop product lifecycle - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/device-lifecycle?view=o365-worldwide#devices-that-are-out-of-compliance)
* Content Source: [microsoft-365/managed-desktop/service-description/device-lifecycle.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/device-lifecycle.md)
* Service: **m365-md**
* GitHub Login: @jaimeo

**Comment by jaimeo** [comment]
@jwmurraycmu another question you might be able to help us clarify?

**Comment by jwmurraycmu** [comment]
@jaimeo , we should remove this section I think. The portal functionality it references is not released, and thus the answer to ceaton001's question is "TBD".

**Comment by jaimeo** [comment]
OK @jwmurraycmu you can remove the section yourself, or let's chat offline about what exact change you're suggesting.

**Comment by jaimeo** [comment]
This is fixed.
