### ISSUE TITLE
A little perplexed

### ISSUE THREAD

**Issue by chrisward2020** [MicrosoftDocs/microsoft-365-docs#1373]
Hi, I'm trying to work out if I can use "Office 365 Home" to receive my email (by redirecting from my current provider).  This document seems to confirm that I can but I got very confused and worried by the warning box at the end: "If you are not using an Exchange license, you cannot use the domain to send or receive emails from the Office 365 tenant.".
I do not understand what this means. Specifically if I subscribe to "Office 365 Home" will I be using (or be able to use) an Exchange license (so I can send/receive email)? That information is not on the "Office 365 Home" order page ( https://products.office.com/sv-se/compare-all-microsoft-office-products?market=se&activetab=tab:primaryr1 ). (Sorry, I'm in Sweden, BTW).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1394eba-4e78-2fd6-84f3-4ee64aedab51
* Version Independent ID: 0ba9ff8c-20a8-58a9-dce7-a3bb0627c134
* Content: [Change your email address to use your custom domain](https://docs.microsoft.com/en-us/microsoft-365/admin/email/change-email-address?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/email/change-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/change-email-address.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@chrisward2020 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
