### ISSUE TITLE
HP EliteBook 1040 and IR camera

### ISSUE THREAD

**Issue by dugatlin** [MicrosoftDocs/microsoft-365-docs#1374]
The HP EliteBook 1040 always come with both the IR camera and fingerprint reader. 
So, please remove reference to the IR camera from the HP EliteBook 1040.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17190dc0-d62a-586f-d938-6666196c0092
* Version Independent ID: 0facfcae-f033-e4dd-a860-42ebd229b2d0
* Content: [Microsoft Managed Desktop devices - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/device-list?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/service-description/device-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/device-list.md)
* Service: **m365-md**
* GitHub Login: @jaimeo

**Comment by jaimeo** [comment]
@rekhanr - up to you if you feel this editorial suggestion is needed.

**Comment by jaimeo** [comment]
@rekhanr can you make this edit?

**Comment by mypil** [comment]
@dugatlin - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/5adb24a. 


Thank you for your contribution to make the docs better! Much appreciated!
