### ISSUE TITLE
Get/Remove-BlockedSenderAddress

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/microsoft-365-docs#1375]
There are no pages for the Get/Remove-BlockedSenderAddress that provide details about cmdlets. There are pages for other cmdlets that outline the parameters and limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c17e50d-aa8f-bd30-66af-ef4d63f02402
* Version Independent ID: 92cbda3f-c3a9-ed20-2038-7e966f491934
* Content: [Removing a user from the Restricted Users portal after sending spam email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@kellybos Thank you for your feedback. We have added the reference to the cmdlets in the below section

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam?view=o365-worldwide#use-exchange-online-powershell-to-view-and-remove-users-from-the-restricted-users-list


Remove-BlockedSenderAddress - https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/remove-blockedsenderaddress
Get--BlockedSenderAddres - https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/get-blockedsenderaddress

Hope this helps!

Thanks
Sri

**Comment by chrisda** [comment]
Topic was updated.

Closing
