### ISSUE TITLE
Step 6: Stop auto-forwarding for email

### ISSUE THREAD

**Issue by MHamilton-Ryder** [MicrosoftDocs/microsoft-365-docs#1377]
The suggested name for the exchange rule is misleading. The rule as suggested will prevent auto forwarding to ALL domains (including internal users) not just external domains. It will also block any user rules which forward emails to other internal users. Adding another condition to the rule where the "recipient is outside the organisation" should make the rule function as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea79921a-7f83-58f1-c0a4-6eb0efce0d26
* Version Independent ID: b60110ef-71ad-9962-74de-734062708ff8
* Content: [Top 10 ways to secure Office 365 and Microsoft 365 Business plans](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by VLG17** [comment]
@MHamilton-Ryder Thank you for providing this feedback. I have created a PR to add the missing condition.

**Comment by mypil** [comment]
@MHamilton-Ryder - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/be5125bd215bee40b87b33cb85f76fde2ea10081. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by neeksnz** [comment]
This is still not fixed in the documentation - this rule was just applied in my organisation word for word, and it blocked ALL domains. Please resolve!!!

**Comment by mypil** [comment]
@neeksnz - We were informed by the writing team that this has been fixed and the changes should now be reflected in the doc. Thank you.
