### ISSUE TITLE
Order of priority incorrect

### ISSUE THREAD

**Issue by RyanBlakeIT** [MicrosoftDocs/microsoft-365-docs#1382]
It should be Security and Compliance Center then the Exchange Transport Rules as that's what "Microsoft" (v-) even told me after responding to a ticket I created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5821435a-93ce-3ba9-312d-fb61a9dae127
* Version Independent ID: aaf49dab-bbdc-4c84-f9ef-a768da673279
* Content: [How DLP works between the Security & Compliance Center and Exchange admin center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/how-dlp-works-between-admin-centers?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/how-dlp-works-between-admin-centers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/how-dlp-works-between-admin-centers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @RyanBlakeIT 
I am guessing that your comment is referring to this paragraph. Is that correct?  Please respond on this thread. 

"If you've created DLP policies in the Exchange admin center, those policies will continue to work side by side with any policies for email that you create in the Security & Compliance Center. But note that rules created in the Exchange admin center take precedence. All Exchange mail flow rules are processed first, and then the DLP rules from the Security & Compliance Center are processed."

**Comment by mypil** [comment]
@RyanBlakeIT - We would like to follow up. Can you please respond to the query of chrfox?

Thank you.

**Comment by chrfox** [comment]
closing this no response for 15 days

**Comment by RyanBlakeIT** [comment]
My apologies on the delay, I forgot that I used my personal e-mail account to submit this.  In any case, @chrfox was correct with his statement.
