### ISSUE TITLE
The Default SharePoint members group has edit access

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#1383]
Hi - small thing, but in the section "Locking and unlocking a record" you say "...any user in the default Members group (the Contribute permission level) can unlock a record or lock an unlocked record."

The default SharePoint members group actually has the edit permission level, not the contribute level, which are two completely different things. Can you please update it? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Overview of records - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/records?view=o365-worldwide#locking-and-unlocking-a-record)
* Content Source: [microsoft-365/compliance/records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by chvukosw** [comment]
Thank you - we have made a the clarification today, which will publish soon.
