### ISSUE TITLE
Doc needs to clarify whether Tenant ID, Directory ID, Power Apps Tenant are one and the same?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/microsoft-365-docs#1384]
Doc needs to clarify whether the tenant sub-domain created at the time of signup 
&lt;Name&gt;.OnMicrosoftOnline.com 
is mapped to Tenant ID, Directory ID, Power Apps Tenant are one and the same?

https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains FAQ - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/setup/domains-faq?view=o365-worldwide#can-i-add-custom-subdomains-or-multiple-domains-to-office-365)
* Content Source: [microsoft-365/admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by VLG17** [comment]
@sing-ideas Tenant ID and Directory ID is the same thing when talking about Azure. 

I could not find any reference to Power Apps in the articles you mentioned, so i don't know the context, but a Power Apps tenant would be the Azure AD tenant on top of which you are buildng your Power Apps platform.

**Comment by mypil** [comment]
@sing-ideas - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
