### ISSUE TITLE
Missing files in ZPAQ?

### ISSUE THREAD

**Issue by mancerayder** [MicrosoftDocs/microsoft-365-docs#1385]
Hi, I've tried to unpack ZPAQ from the Windows and Office Deployment Lab Kit file twice in different locations, making sure the folder the files extracted to does not contain spaces. It seems like the Client VMs are missing files, so the CLIENT VMs are not created, only the Server ones. Please see example errors. 

PSHostUserInterface.ERROR: Failed to create a new virtual machine.

'HYD-CLIENT1' failed to realize. (Virtual machine ID 5CD3348E-652A-4665-ACB9-83BB3148FB40)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
PSHostUserInterface.ERROR: Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
PSHostUserInterface.ERROR: Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
PSHostUserInterface.ERROR: Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
PSHostUserInterface.ERROR: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
PSHostControl: WriteProgressNew(Source:53,Activity:0,ParentActivity:-1)
PSHostControl: WriteProgressFinished(Source:53,Activity:0,ParentActivity:-1)
PSHostControl: WriteProgressNew(Source:54,Activity:0,ParentActivity:-1)
PSHostControl: WriteProgressNew(Source:54,Activity:0,ParentActivity:-1)

PSHostUserInterface.ERROR: Failed to create a new virtual machine.

'HYD-CLIENT7' failed to realize. (Virtual machine ID 880AC037-9790-4FEE-8EE1-0DA5F4ED3AC2)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
PSHostUserInterface.ERROR: Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
PSHostUserInterface.ERROR: Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
PSHostUserInterface.ERROR: Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
PSHostUserInterface.ERROR: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

**Comment by mypil** [comment]
@mancerayder - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mancerayder** [comment]
Hi @mypil , I'm referring to this:
(https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)

**Comment by shervin-sa** [comment]
Why was this closed? I have downloaded the same kit, and these VM's are still missing.

**Comment by JGruszczyk** [comment]
Hi - we have tested and validated the VMs are there, please ensure that you have adequate resource space available for the full kit. We have independently verified the kit hydrates in two different instances

**Comment by shervin-sa** [comment]
I've downloaded the kit twice. 

I have installed it, and HYD-CLIENT1,2,3,4,5,6,7 are missing. The VHDX files for each of the corresponding clients are 4MB in size. All the servers install and import fine.

As for the environment, I am running this on a windows 10 machine with 32GB ram, and 1TB HD, with over 500GB free.

**Comment by joelmaldo82** [comment]
2023 and this is STILL happening with the Windows 11 21h2 labkit.  Well over 500GB of space  and all other specs are at max i7 13th gen , etc and many virtual machines are missing. I gave up and found an older lab kit zpaq file I downloaded in 2022. I opened and compared both zpaq files using Peazip and sure enough you can see the new zpaq does not have the missing VM's but the older one does. As far as I am concerned this is still not fixed and/or the changes have not been documented  properly anywhere that these vm machines are no longer included with 2023 lab kit downloads for Windows 11. In the lab guide it clearly states that they should be there, a screenshot is even included showing them in hyper-v.
