### ISSUE TITLE
Update preservation hold library information

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#1386]
Hi - in the section "How long until disposed content is permanently deleted" it says "Content in the Preservation Hold library will be permanently deleted within 7 days of disposition." This has changed recently and the information should be updated. Content from the preservation hold library is now moved to the second stage recycle bin and kept for 93 days. 

Here are the details about the current process: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#content-in-onedrive-accounts-and-sharepoint-sites

I am actually a bit confused if the preservation hold library is even used anymore with retention labels. You can modify a document with a retention label but cannot delete it from a library - you get an error.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d552f987-1606-01f7-d600-5887968ae60c
* Version Independent ID: 8c5f88de-93e7-862e-0550-fb9ac012be35
* Content: [Overview of disposition reviews - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/disposition-reviews?view=o365-worldwide#how-long-until-disposed-content-is-permanently-deleted)
* Content Source: [microsoft-365/compliance/disposition-reviews.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@EricaToelle  Yes, thank you - this content is in the process of being updated and includes this correction.

**Comment by mypil** [comment]
@EricaToelle - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author cabailey so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
