### ISSUE TITLE
MailItemsAccessed should have an asterisk since it is now default

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#1387]
In the section "Logon types and mailbox actions" the MailItemsAccessed does not have an asterisk but it should because it is now enabled by default as long as the DefaultAuditSet is applied. I tested this in my tenant and confirmed it is enabled by default for all three logon types (Owner, Delegate and Admin)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide#logon-types-and-mailbox-actions)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@itguysocal  Thank you for your feedback. We have the Asterisks added to the option now, Let us know if there are any other changes required on this document.

![image](https://user-images.githubusercontent.com/45987684/77861860-3ff3d900-7235-11ea-9069-fb077597298a.png)

Thanks
Sri

**Comment by chrisda** [comment]
Closing
