### ISSUE TITLE
Issues with updating manager value

### ISSUE THREAD

**Issue by lovethakker02** [MicrosoftDocs/microsoft-365-docs#1388]
We have set up 2 additional alias  for some of our business users by following [this](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md) link. This created separate User profile which is not mentioned in documentation.

But the real issue is the manager field used in the user profile is not syncing now. The manager user changed. So we deleted the old user and updated the details in Ad and it synced for main alias but not reflecting in other alias. We do not wish to go through all the user profile with other domain and verify that manager field. Can you please provide any solution, how can we update manager value for all the alias profiles?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@lovethakker02 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by lovethakker02** [comment]
It seems that the primary domain only gets the changes. We have asked our client to generate the ticket for same. If we get any update from them, we will surely post here.
