### ISSUE TITLE
Is it correct to understand Many Domains Emails are received in 1 O365 Login?

### ISSUE THREAD

**Issue by sing-ideas** [MicrosoftDocs/microsoft-365-docs#1390]
Doc need to clarify the understanding is correct or not. If I can add up to 900 domains to a single O365 Subscription, does that mean if I have 10 website domains for 10 brands of products/services under a same single legal business entity, I can send email from one O365 login with different From Email Address with unique email ID for each brand. All I have to do is update the same Mx Record in DNS Records of each brand domain names. It is not a question of money alone for licensing but from operation convenience. Do clarify whether it is a right thought.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains FAQ - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/setup/domains-faq?view=o365-worldwide#can-i-add-custom-subdomains-or-multiple-domains-to-office-365)
* Content Source: [microsoft-365/admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by VLG17** [comment]
@sing-ideas Yes, you could have 10 domains added to one O365 subscription, which would correspond to 10 brands of product/services, each with their own E-Mail domain:

user1@domain1.com
user2@domain2.com
.......
user10@domain10.com

From a licencing perspective, you still need to have valid Exchange Online licenses (or a Plan that contains them) for these users. It does not matter how they are split, if they are all @rootdomain.com or @domain1.com, @domain2.com and so on.

**Comment by mypil** [comment]
@sing-ideas  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
