### ISSUE TITLE
Azure app for : Admin consent for information barriers in Microsoft Teams

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/microsoft-365-docs#1393]
the powershell script or explanations are incomplete. Which type of app/ permissions need to be created, affected to the app ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @danone1985 
There are multiple PowerShell scripts with accompanying explanations in this topic.  Can you tell me which one you are having trouble with?

**Comment by mypil** [comment]
@danone1985 - We would like to follow up. Can you please respond to the query of chrfox?

Thank you.

**Comment by mypil** [comment]
@danone1985 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
