### ISSUE TITLE
Still can't get EDM to work in our Tenant

### ISSUE THREAD

**Issue by pradell1957** [MicrosoftDocs/microsoft-365-docs#1394]
I followed the step by step documentation in this article and still cannot get EDM to work. In fact I am getting watson errors in powershell and I even have one of my EDM DLP stuck in deleting state in the O365 Security Compliance center for over a month. Lastly I logged tickets to Microsoft under Unified Support and even the engineer was receiving watson errors and was unsuccessful in getting a test EDM DLP rule working. Was anyone able to get EDM to work successfully in their tenant?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@pradell1957 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.
