### ISSUE TITLE
Missing Settings

### ISSUE THREAD

**Issue by dumblerod** [MicrosoftDocs/microsoft-365-docs#1395]
Most of these settings are not available in either the preview mode or legacy console.  This page needs to be updated with either new location or settings.  These settings are referenced in the Launchpad app from partner site as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f617ab69-df14-137d-05c6-87eb0e7dd491
* Version Independent ID: c7bdc10c-dab5-e758-15d6-05f3be6f2974
* Content: [Set app protection settings for Android or iOS devices - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/app-protection-settings-for-android-and-ios?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/business/app-protection-settings-for-android-and-ios.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/app-protection-settings-for-android-and-ios.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@dumblerod I checked the android setting in the Devices > Policies pane in the Microsoft 365 Business admin center and the match with one exception, that I will fix today.  Is it possible that you are looking at Endpoint protection, or some other settings?

![image](https://user-images.githubusercontent.com/31521796/77185276-6031d400-6a8e-11ea-939a-361d7b29ae78.png)
