### ISSUE TITLE
Please clarify adding Mail Contacts to Office 365 Groups

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/microsoft-365-docs#1396]
On the user docs (support.office.com) article "Adding guests to Office 365 Groups" there is an FAQ: 

Can I add external mail contacts to groups?
Yes, you can. External mail contacts are contacts listed in your organization's's global address list. An example of this type of contact is a vendor company who regularly provides services to your organization.

(https://support.office.com/en-us/article/adding-guests-to-office-365-groups-bfc7a840-868f-4fd6-a390-f347bf51aff6)

I don't see support for mail contacts discussed anywhere here, can you clarify the workflow for adding a mail contact to an O365 group from an admin perspective please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Office 365 Groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by VLG17** [comment]
@cmcapellan Have you tried leveraging the "**Add-UnifiedGroupLinks**" cmdlet described in [this article](https://www.petri.com/external-access-office-365-groups) by a Microsoft MVP?

**Comment by mypil** [comment]
@cmcapellan - Can you please respond to the query of VLG17?

Thank you.

**Comment by mypil** [comment]
@cmcapellan - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.
