### ISSUE TITLE
On prem?

### ISSUE THREAD

**Issue by jmbainbridge** [MicrosoftDocs/microsoft-365-docs#1397]
We have a mixture of on-prem accounts and cloud. If I enable this for all users but do not pay for Azure AD Premium .. what happens to the on-prem users?
Are they able to reset their passwords? Which would make no sense as no write back to AD would occur.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad408574-36cc-9b96-f092-58a68708d3a0
* Version Independent ID: 97adbc3d-8f71-a6de-25c3-f9400125f885
* Content: [Let users reset their own passwords in Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/let-users-reset-passwords?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/let-users-reset-passwords.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/let-users-reset-passwords.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@Sirkkuw can you help answer this?

**Comment by Sirkkuw** [comment]
Nothing happens to the on-prem users if you keep the domain controller separate from the cloud identity. IF you set up hybrid, then the identity is controlled locally (your on prem domain) and you would have to use Azure Ad premium only if you wanted password write-back from Azure Ad if you changed things there. FOr more info, see https://docs.microsoft.com/en-us/Office365/Enterprise/set-up-directory-synchronization

**Comment by cmcatee-MSFT** [comment]
@jmbainbridge did that answer your question?

**Comment by mypil** [comment]
@jmbainbridge - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by Sirkkuw so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
