### ISSUE TITLE
UI has changed. 

### ISSUE THREAD

**Issue by andrewbettany** [MicrosoftDocs/microsoft-365-docs#140]
The UI has changed, and the graphic is now out of date.

There no longer is there an option to Manage Office deployment.  

There is now an option to Remove Device. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 071d262a-56d8-5eab-38ca-8b7f07d8bb2e
* Version Independent ID: ec866d0c-c886-27c4-341d-3e64814d48a5
* Content: [Reset Windows 10 devices to their factory settings](https://docs.microsoft.com/en-gb/microsoft-365/business/reset-devices-to-factory-settings)
* Content Source: [microsoft-365/business/reset-devices-to-factory-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/reset-devices-to-factory-settings.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
Thank you for your feedback - we are updating the documentation as the product gets updates. I will get the new steps in soon.
