### ISSUE TITLE
Custom app launcher tiles is not visible in the Organization Profile tab now

### ISSUE THREAD

**Issue by O365DevHero** [MicrosoftDocs/microsoft-365-docs#1401]
Custom app launcher tiles is not available and only custom Themes are available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9488caf7-b791-3002-8749-7fdc4b2ec8b3
* Version Independent ID: 08e61eb0-7bcd-f449-46ef-17e209138a8e
* Content: [Add custom tiles to the app launcher - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/customize-the-app-launcher?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/customize-the-app-launcher.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by Trundlore** [comment]
confirmed, the locations stated here do not seem to exist anymore. is this still possible?
given the current climate we are looking to put a tile to link users to the (awful address for) windows virtual desktop launcher

**Comment by dbaars** [comment]
Same here, we also don't see "custom app launcher tiles" - what gives?

**Comment by fredparadis** [comment]
Seems like only some Tenants don't have the option anymore.

Looking at 3 different Tenants, one created in January got the option.

One created last year doesn't have the option and same thing with a brand new Tenant from last week, no "Custom app launcher tiles" section anymore in "Organisation Profile".

**Comment by petegriggs** [comment]
Same here - unable to see it.

**Comment by msbemba** [comment]
@O365DevHero  Thank you for your feedback. We are checking this with the author and Product group. I will keep you updated and make changes if necessary.

Thanks
Sri

**Comment by zx3-at** [comment]
If you hold down the Windows key + Ctrl + right-shift and type in "Satya Nadella" on the keyboard, then immediately click the right mouse button, whilst hovering over the app menu, then this features does not return. It's gone guys....they've nuked it. Wish we knew why they did that :-(

**Comment by petegriggs** [comment]
It is still there guys. I raised a support ticket - the admin has to have a license assigned for Outlook - I licensed created my tile and then revoked license.

**Comment by msbemba** [comment]
@O365DevHero  Thank you for your feedback. We added a note to the document about what to do when you don't see the custom tile

 "If you don't see the custom tile created in the previous steps, make sure you have an Exchange Online mailbox assigned to you and you've signed into your mailbox at least once. These steps are required for custom tiles in Office 365."

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@O365DevHero @Trundlore @dbaars @fredparadis @petegriggs - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/132ad9d879db9d. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by entarc** [comment]
"Both you and your users need to perform these steps to promote custom tiles from the My apps page to the app launcher." What about administratively? I want to pin shortcuts to the app launcher for guests to easily jump to a SahrePoint page.

**Comment by coupalm** [comment]
The pin to launcher is not available anymore. However I can unpin. I'm on first release.
