### ISSUE TITLE
Azure AD Basic EDU licenses

### ISSUE THREAD

**Issue by labanex** [MicrosoftDocs/microsoft-365-docs#1402]
"The following people don't need Azure AD Premium or Azure AD Basic EDU licenses assigned to them:"
A lot of people may not know what this is "Azure AD Basic EDU licenses". A link to https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/license-users-groups would be helpful. It took me awhile to find the article that explains Azure AD Basic EDU Licenses and how you have to do it in Azure to do this.
If not adding a link, maybe a little more detail in License Requirements would be helpful because this product is not available in the Admin Center and not available in Users &gt; Active Users. Nothing explains that this has to be done in Azure. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create Office 365 Groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@labanex - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/1d2cbc29c5937d0a3a487c2bc5b4d6ac828b40d1. 


Thank you for your contribution to make the docs better! Much appreciated!
