### ISSUE TITLE
Refresh needed

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/microsoft-365-docs#1403]
Teams admin is now called "Teams Service Administrator"
Privileged role admin is now called "Privileged Authentication Administrator"

would be good to have role combination examples to highlight potential dependencies (i.E. Teams Admin role + User Admin to provision Users for Teams, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by kwekuako** [comment]
Updated the Teams service admin name. Confirming the Privileged auth admin change.

**Comment by kwekuako** [comment]
Privileged auth admin is a separate role from the privileged role admin. It's documented here: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles. Thanks.
