### ISSUE TITLE
update ToC

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1405]
The Table of Content (ToC) does still state twice 'What is EOP?' while the article is titled as 'What is Exchange Online Protection (EOP)'. The ToC should be updated so it's clear what it is about without opening the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14130f97-cb6e-999d-c2c8-47ef1d7bfff8
* Version Independent ID: 4511a0e0-4616-c882-a420-13f4b59ce88b
* Content: [What is EOP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/what-is-eop?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/what-is-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/what-is-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@giant, I only see one reference in the TOC file, and in search results for "What is EOP?

![image](https://user-images.githubusercontent.com/33166947/77967310-b88c8100-7299-11ea-98bc-a012d9bc0e29.png)

I guess we must have fixed it?

Thanks for the feedback.

Closing

**Comment by GiantCrocodile** [comment]
@chrisda I see the same behavior but if you check that one article the ToC entry doesn't match the article's title. So this should be updated too.
