### ISSUE TITLE
Is CNAME msoid still required?

### ISSUE THREAD

**Issue by aikensam** [MicrosoftDocs/microsoft-365-docs#1406]
It has been removed from other documents but still exists here and https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-web-com?view=o365-worldwide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6107c99-df0b-8a33-f291-086ea6fd5034
* Version Independent ID: 0ba87689-7a57-c3f8-af4b-3267c81b933d
* Content: [Create DNS records at Cloudflare for Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by VLG17** [comment]
@aikensam it's relevant only for [Office 365 operated by 21Vianet](https://docs.microsoft.com/en-us/microsoft-365/admin/services-in-china/purpose-of-cname?view=o365-21vianet).

I'll add a note about that.

**Comment by mypil** [comment]
@aikensam - Thank you for submitting feedback.

Please see response from the author @pebaum based on this https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1566#issuecomment-620176483.
