### ISSUE TITLE
Block guest users from a specific group - Can I do the opposite?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/microsoft-365-docs#1408]
Howdy,
We are looking to not allow guest access to any of our Teams except for a specific one we designate as the External Collaboration team.  Is there a way to make Guest access blocked by default and then only enable it for one team and to also have it blocked by default on all future created teams?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Office 365 Groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Allaen** [comment]
As far as I know you can't. You'll have to disable guest access for all O365 group individually after creation.

**Comment by kelemvor33** [comment]
Can that be done through the GUI or can it only be done through Powershell?

**Comment by Allaen** [comment]
> Can that be done through the GUI or can it only be done through Powershell?

To the best of my knowledge only via Powershell like in the example in this article.

**Comment by mypil** [comment]
@kelemvor33 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
