### ISSUE TITLE
Add Private Browsing shortcut for Edge as a browser

### ISSUE THREAD

**Issue by manknewl** [MicrosoftDocs/microsoft-365-docs#1411]
There are instructions for Internet Explorer, but not for Edge, which are the same as Chrome: CTRL + SHIFT + N

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b1b7b8-5414-2242-6b27-32ce18651ba9
* Version Independent ID: 47052c23-01a6-7ec2-f634-d95137c3dc63
* Content: [Use your free Azure Active Directory subscription in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-your-free-azure-ad-subscription-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-your-free-azure-ad-subscription-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-your-free-azure-ad-subscription-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@manknewl Thanks for pointing this out. I just tested, and keystrokes are the same as IE: CTRL + SHIFT + P. I will update document accordingly.

CTRL + SHIFT + N in edge opens a new (non-In Private) window.

**Comment by manknewl** [comment]
I use the beta version of edge, and CTRL + SHIFT + N (maybe it’s something else on my configuration but CTRL + SHIFT + P opened my printer.

**Comment by markjjo** [comment]
@manknewl Thanks for following up/clarifying. I do see the CTRL + SHIFT + N to open inprivate session in beta version of edge.
