### ISSUE TITLE
Settings menu is missing

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#1412]
Hi

I don't have the Settings menu in the "Microsoft 365 security" centre. If I navigate to https://security.microsoft.com/settings the page is empty. See image below

Thanks

![image](https://user-images.githubusercontent.com/8972968/76473068-4ee22b00-63ef-11ea-9fdb-fd8466802458.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d5414b-78ef-79a6-7cd3-5f67ee2ae6f9
* Version Independent ID: 617f3b58-2cc2-2413-7a00-eb0ba912a3e8
* Content: [Preview features in Microsoft Threat Protection - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/preview?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/preview.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi zlDev, 

This is likely due to a licensing or permissions issue. 

Please refer to: https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-enable?view=o365-worldwide#check-license-eligibility-and-required-permissions 

Thanks

**Comment by zlDev** [comment]
I'm a GlobalAdmin and I've got Microsoft 365 E5 **Developer** (Visual Studio Professional subscription) and Microsoft Defender ATP licenses assigned to me. The developer license is not listed, but I assume it is an oversight.

**Comment by mypil** [comment]
@zlDev - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author mjcaparas so we will close this issue. If you continue to experience technical problems, the best way forward is for you to open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by zlDev** [comment]
Ok, so the problem was with me using Microsoft 365 E5 Developer license. I have access to another tenant and this no longer an issue.

**Comment by zlDev** [comment]
Please explicitly mention that this type of license is not suitable for Security features testing. It is only for software development purposes.
