### ISSUE TITLE
Advanced hunting is missing a reference. 

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#1413]
Please add the reference page for the Advanced hunting page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac42403c-4226-bec2-986d-2e8a67e7c66d
* Version Independent ID: e8e0b323-ee46-f8e7-fe99-cbee91697213
* Content: [What's new in Microsoft Threat Protection - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/whats-new.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Hi zlDev, 
Thank you for your feedback. This page was intended to highlight capabilities that have just gone GA. 

We have links to Advanced hunting from this page and serves as the entry point for all the AH goodies. 

Thanks
