### ISSUE TITLE
Incidents, Action center, or Hunting are missing from the menu

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#1414]
According to the documentation
 
_"Before you turn on the service, the Microsoft 365 security center (security.microsoft.com) shows the Microsoft Threat protection welcome page when you select Incidents, Action center, or Hunting from the navigation pane. These navigation options are not shown if you are not eligible to use Microsoft Threat Protection."_

Please advise how does one become eligible and start using Microsoft Threat Protection 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7f625c-f3ef-882d-231f-6fef18e14137
* Version Independent ID: 3f335d54-6d65-d49a-e517-2c3a9a95e44d
* Content: [Turn on Microsoft Threat Protection in the Microsoft 365 security center - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-enable?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/mtp-enable.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/mtp-enable.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by zlDev** [comment]
Ok, so the problem was with me using Microsoft 365 E5 Developer license. I have access to another tenant and this no longer an issue.

**Comment by lomayor** [comment]
Thanks for checking and apologies for the slow responses. Please refer to this document for eligibility. Note that A5 was a recent addition and that there might be changes to the licensing requirements. For any concerns, don't hesitate to use Need Help on the portal to reach Support.

https://docs.microsoft.com/en-us/microsoft-365/security/mtp/prerequisites?view=o365-worldwide#licensing-requirements
