### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by cspencerna** [MicrosoftDocs/microsoft-365-docs#1415]
The how to of this section contains a typo: Optional: Azure Multi-Factor Authentication is enabled for your users, e.g. step 3 "Sign in to the Office 36 portal with the test user account."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50af9cec-786a-6026-0bcb-ed27be02a57b
* Version Independent ID: 7fa62474-154e-a5dc-cf4c-4e485b733b18
* Content: [Phase 2: Identity infrastructure exit criteria - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/identity-exit-criteria?view=o365-worldwide#optional-azure-multi-factor-authentication-is-enabled-for-your-users)
* Content Source: [microsoft-365/enterprise/identity-exit-criteria.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/identity-exit-criteria.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@cspencerna - Thank you for pointing this out.

PR #1425 has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
