### ISSUE TITLE
Typo/words missing

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/microsoft-365-docs#1416]
Under the heading "Content in OneDrive accounts and SharePoint sites", between steps 2 and 3, it reads like this "The Recycle Bin is not
ed and therefore searches do not find content there. This means that an eDiscovery hold can't locate any content in the Recycle Bin to hold it."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#how-a-retention-policy-works-with-content-in-place)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@campbellkerr  Thanks for flagging this - I'll fix it.  Should be "The Recycle Bin is not used and therefore...."

**Comment by cabailey** [comment]
Fixed now, closing.
