### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by krilbe** [MicrosoftDocs/microsoft-365-docs#1417]
These links give 404:
    Collaborate with guests in a site
    Collaborate with guests in a team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Office 365 Groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@krilbe thanks for catching this. Links should be fixed now.

**Comment by mypil** [comment]
@krilbe - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. 


Thank you for your contribution to make the docs better! Much appreciated!
