### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by Staeger** [MicrosoftDocs/microsoft-365-docs#1419]
In "Onboarding" section, please update the URL to downloadable Excel workbook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbb8b28d-6716-802d-8c63-5a62e18561a5
* Version Independent ID: 98744567-905b-2a55-4dc3-2374a2705581
* Content: [Microsoft 365 for enterprise foundation infrastructure for non-enterprises - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/deploy-foundation-infrastructure-non-enterprises?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/deploy-foundation-infrastructure-non-enterprises.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/deploy-foundation-infrastructure-non-enterprises.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by markjjo** [comment]
@staeger Thanks for the heads up. We've recently changed the directory structure in this GitHub repo, which broke this link. You can download spreadsheet at: https://github.com/MicrosoftDocs/microsoft-365-docs/raw/public/microsoft-365/media/deploy-foundation-infrastructure-non-enterprises/Group-License-Mgmt-PowerShell.xlsx

We'll update the topic.
