### ISSUE TITLE
StorageAccountType and VhdUri

### ISSUE THREAD

**Issue by schoier** [MicrosoftDocs/microsoft-365-docs#142]
I get error on this line:
$vm=Set-AzureRmVMOSDisk -VM $vm -Name WIN10-TestLab-OSDisk -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType "Standard_LRS"
And this is the error:
Set-AzureRmVMOSDisk : A parameter cannot be found that matches parameter name 'StorageAccountType'.

If I comment out StorageAccountType, I can go on but in the next step I'm prompted with the following:

$vm=Set-AzureRmVMOSDisk -VM $vm -Name WIN10-TestLab-OSDisk -DiskSizeInGB 128 -CreateOption FromImage #-StorageAccountType "Standard_LRS"

cmdlet Set-AzureRmVMOSDisk at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
VhdUri:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715b01d6-8397-42d6-77e5-6a82a6684a19
* Version Independent ID: 53957339-5a9a-6359-fb10-ce07a61d93b7
* Content: [Lightweight base configuration](https://docs.microsoft.com/en-us/microsoft-365/enterprise/lightweight-base-configuration-microsoft-365-enterprise)
* Content Source: [microsoft-365/enterprise/lightweight-base-configuration-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/lightweight-base-configuration-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@schoier - Thank you for your feedback, I will get this over to the Enterprise writing team for clarification.

**Comment by JoeDavies-MSFT** [comment]
@schoier   I have retested this PowerShell command block with AzureRM Module version 6.13.1 (the latest) and without the StorageAccountType parameter and everything worked fine. I have updated the article to remove the unneeded parameter. Thanks for letting us know about this.
