### ISSUE TITLE
Licensing Requirements

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1421]
There is nothing on this page about the type of license that must be assigned to users in each role. Please update the page to include this info, i.e., do people assigned to a Compliance Manager role, need O365 E1, E3, or  E5, can guests that don't have licenses be assigned a role?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f85a2df-74e6-8c40-9d10-adac43191db2
* Version Independent ID: 8f8586c5-bdea-eec8-b9f8-d5d4a15737c0
* Content: [Work with Microsoft Compliance Manager (Preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/working-with-compliance-manager?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/working-with-compliance-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/working-with-compliance-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Thank you for your input, we will be making updates to this page soon.
