### ISSUE TITLE
US Azure is now rated FedRAMP High in all regions

### ISSUE THREAD

**Issue by andywahr** [MicrosoftDocs/microsoft-365-docs#1422]
Please updated based on this:  https://azure.microsoft.com/en-us/blog/all-us-azure-regions-now-approved-for-fedramp-high-impact-level/  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659dd7bc-2bbb-097c-44c1-730f2e3c6988
* Version Independent ID: 9f8d678e-8069-6997-505d-dd21333e1902
* Content: [Federal Risk and Authorization Management Program (FedRAMP) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-fedramp?view=o365-worldwide#microsoft-azure-p-atos)
* Content Source: [microsoft-365/compliance/offering-FedRAMP.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-FedRAMP.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@andywahr - thanks for the feedback! We've opened a work item to update this topic to sync with Azure blog, it should be publishing in a few weeks. Please check back on the topic for the new changes. Thanks!
