### ISSUE TITLE
Article not hooked up to the TOC

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/microsoft-365-docs#1423]
By design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9690810c-2cc9-973f-6c0e-7a8f6c424fc2
* Version Independent ID: ace39850-2ef2-d182-bd7e-da300d5be639
* Content: [Create DNS records for Azure DNS zones - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-for-azure-dns-zones?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/create-dns-records-for-azure-dns-zones.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-for-azure-dns-zones.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@mairaw - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@pebaum - Can you please share your insights on this issue. 

Thank you.

cc: @kenwith

**Comment by pebaum** [comment]
yes this is intentional.
