### ISSUE TITLE
Is it available in the UK now?

### ISSUE THREAD

**Issue by KrisDeb-OptiIT** [MicrosoftDocs/microsoft-365-docs#1426]
I am an Insider, I have E5 and I can't see it. Tech support told me that it's only for US tenants, is that correct? Thanks - Kris.

**Comment by denisebmsft** [comment]
Hello @KrisDeb-OptiIT. Can you please tell us to which article your question applies? This will help us route your issue to the correct writer/team. Thank you!

**Comment by mypil** [comment]
@KrisDeb-OptiIT - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
