### ISSUE TITLE
Clarity on "Forever" and "Time Period with no Deletion"

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/microsoft-365-docs#1429]
This Article doesn't provide clarity on difference if option is selected to Retain items Forever Vs. Option to select a time period(e.g. 7 Years) but no deletion after that specific period. Would there be any difference if Unlimited Archive is enabled for the mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@3novsan   Yes, it's recently come to my notice that this article assumes a policy of retain and then delete, and doesn't explain the other paths of retain-only, and delete-only. I'm working on addressing that gap, with engagement from engineering.

**Comment by cabailey** [comment]
Page now updated for retain-only and delete-only retention policies, for both SharePoint and Exchange.
