### ISSUE TITLE
 Manage Office deployment pane no longer available

### ISSUE THREAD

**Issue by andrewbettany** [MicrosoftDocs/microsoft-365-docs#143]
The "Manage Office deployment" pane is no longer available in the M365 Business admin center.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca7312a-c908-d32d-e1e3-3e9227300c67
* Version Independent ID: e2b941e6-9048-3be7-3d2b-3b59424b126b
* Content: [Automatically install or uninstall Office on Windows 10 devices](https://docs.microsoft.com/en-gb/microsoft-365/business/auto-install-or-uninstall-office?redirectSourcePath=%252fen-us%252farticle%252fautomatically-install-or-uninstall-office-on-windows-10-devices-cbc6bfe5-565a-4fb8-95f0-b06e7b74ac46)
* Content Source: [microsoft-365/business/auto-install-or-uninstall-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/auto-install-or-uninstall-office.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
I added the steps to bring back the tile.

**Comment by andrewbettany** [comment]
Hi, I still dont see the Manage Office Deployment option within the user interface as a Device Action.  Please can you update the article or confirm that this option is still available in the M365B subscription? 
![image](https://user-images.githubusercontent.com/22380517/48024176-d4890300-e137-11e8-97a5-8816a4fb8e99.png)

**Comment by andrewbettany** [comment]
Ok I see, thanks. 
The Office deployment action can only be applied to groups of devices, and the option is not available on the manage device section.  The Office deployment action can only be found on the Devices tile, *which is not visible by default*.

**Comment by robmazz** [comment]
Closing issue
