### ISSUE TITLE
Step 5- Start-ManagedFolderAssistant

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/microsoft-365-docs#1430]
Created a new MRM Policy, Applied to a mailbox, Ran Start-ManagedFolderAssistant against that specific mailbox.
But When enabling Archive mailbox it shows same warning of Default MRM Policy "If you enable this person's archive mailbox, items in their mailbox that are older than two years will be moved to the new archive. Are you sure you want to enable this archive mailbox?" Results are same in multiple tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your Office 365 organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@3novsan Thanks for raising the issue. First, you might want to consider contacting MS Support about this issue if you are concerned. Second, you might consider testing your new policy to see if it really moves items older than 2 years to the archive mailbox. I assume that your new policy either doesn't move items to the archive or the retention duration is different than the default MRM policy. 

My guess is that the error message is a default error message (based on the assumption that the Default MRM retention policy is assigned to the mailbox). I don't think the error message is dynamic; in other words, when enabling the archive mailbox, the system is not looking at the actual MRM retention policy assigned to the mailbox. I think it is just a default message, similar to the one displayed on the Archive mailboxes page in the Security & Compliance Center: https://protection.office.com/archiving

But as I said, you might want to open a ticket with MS Support or test your implementation.
