### ISSUE TITLE
The documentation can be simplified 

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/microsoft-365-docs#1431]
The steps 1) & 2)  outlined in https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#enable-this-preview-and-synchronize-labels 
Maybe replaced by 
Connect-ExchangeOnline -UserPrincipalName your.namel@yourdomain.onmicrosoft.com -ConnectionUri 'https://ps.compliance.protection.outlook.com/powershell-liveid/'  -ExchangeEnvironmentName O365Default     

I stumbled on this syntax to be honest,  but thankfully, it creates an implicit  PS Session and even redirects your uri as appropriate, on your tenant .  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@westerdaled Hi Daniel, thanks for posting your feedback.  We are always looking for ways to make the documentation simpler.  Step 1 covers connecting to Azure AD and setting the EnableMIPLabels parameter, and step 2 connects to Office 365 Security & Compliance Center PowerShell, with example commands how to do that plus a link to the official reference for full instructions, "Connect to Office 365 Security & Compliance Center PowerShell" (https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps).

I think your suggested replacement offers an alternative connection method for step 2, which is available after downloading and installing the EXO V2 module, which still seems to be in preview, and you still need Set-ExecutionPolicy RemoteSigned.  I don't see how this replaces the first step that connects to Azure AD to set the EnableMIPLabels parameter? 

I am investigating why Connect-ExchangeOnline isn't included in the "Connect to Office 365 Security & Compliance Center PowerShell" article if it is a valid alternative.  But for the time being I'll keep the example commands in sync with our recommended steps in that article.

**Comment by westerdaled** [comment]
@cabailey 

"Connect to Office 365 Security & Compliance Center PowerShell" (https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps). , I believe works fine if you are not using MFA.  My approach works fine with when MFA is enabled .

**Comment by cabailey** [comment]
@westerdaled  There's a link for alternative instructions in that article if you're using MFA, which is why the original article says "For example" before the commands for step 2.  If you prefer using the EXO v2 module connection method, that's fine but it doesn't replace setting the Azure AD parameter in step 1, it does require extra steps to download and install this module if you haven't already, it still requires Set-ExecutionPolicy RemoteSigned, and this module is still in preview.  I've had confirmation that the documentation should not refer to this alternative method while the module remains in preview - so no changes at this time.
