### ISSUE TITLE
US Driver's License XML missing entity ID

### ISSUE THREAD

**Issue by jellybeard** [MicrosoftDocs/microsoft-365-docs#1432]
US driver's license entry doesn't have the entity ID in the XML, which makes it impossible to target a scan for that specific type. Please update the documentation.

**Comment by mypil** [comment]
@jellybeard - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by jellybeard** [comment]
https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for?view=o365-worldwide#us-drivers-license-number

**Comment by mypil** [comment]
@jellybeard - Thank you for pointing this out.

PR #1448 has been created by nihendle to fix this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
