### ISSUE TITLE
Update Azure App Registration link

### ISSUE THREAD

**Issue by rs-seccompsme** [MicrosoftDocs/microsoft-365-docs#1433]
Please consider updating the link in Step 1 to the new Azure App Registration process.  https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b68cfa-058a-8536-fb6a-b54e8fffa626
* Version Independent ID: dbcba365-2858-8cff-4f30-8a8a0068ac71
* Content: [Set up a connector to import HR data - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/import-hr-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/import-hr-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-hr-data.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rs-seccompsme Thanks for feedback. Will look into this. Have you verified that new Azure App registration process works for setting up an HR connector or any other third-party data connector?

**Comment by rs-seccompsme** [comment]
Yes.  I have completed the steps and the new process works. I have documented it for my internal Compliance Fast Track incubation team.  The issue with the old one is most tenants will not have the legacy Azure portal experience that is referenced and the steps will not follow.

**Comment by markjjo** [comment]
Thanks @rs-seccompsme. I was added to an internal email thread about this same issue that refered to an HR connector doc you created. I'll update this topic. As I assume you are internal MSFT, so you can ping me directly next time you have a suggested update. Thanks again.
