### ISSUE TITLE
Trusted Senders

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/microsoft-365-docs#1435]
"Microsoft subscribes to third-party sources of trusted senders."

Can we get visibility on the trusted senders and third parties so we know if this is applicable to our tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3094559e-4d03-8f6d-a620-a3f61ec33184
* Version Independent ID: d352d9b3-3d96-402b-c20e-df677b3e9d60
* Content: [Configure the connection filter policy, Allow list, Block list - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-connection-filter-policy?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/configure-the-connection-filter-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-connection-filter-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@sysadmin-scs - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)**.  
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
