### ISSUE TITLE
Do we need "-Scope CurrentUser" on Set-ExecutionPolicy RemoteSigned

### ISSUE THREAD

**Issue by narismadz** [MicrosoftDocs/microsoft-365-docs#1438]
I got this error when run the 1st PS code to connect Security & Compliance Center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@narismadz  What error message are you seeing?  Does it make a difference if you run the PowerShell session as an administrator?  For full instructions about connecting to Security & Compliance Center PowerShell, see https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps

**Comment by narismadz** [comment]
Previously, I got "Restricted" policy on CurrentUser scope so run that command may failed since I need to set policy "RemoteSigned" to CurrentUser scope first

My error is "Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of Restricted. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy"."

**Comment by cabailey** [comment]
@narismadz  After looking into this, I think the right answer is to run the PowerShell session with "Run as administrator", which is needed to change a previously set value for Set-ExecutionPolicy and also listed in https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/connect-to-scc-powershell/connect-to-scc-powershell?view=exchange-ps  I'll change the documentation to include this step.

**Comment by cabailey** [comment]
The page is updated now - closing.
