### ISSUE TITLE
Expired Status

### ISSUE THREAD

**Issue by stleun** [MicrosoftDocs/microsoft-365-docs#1441]
Please add that in expired status (in-grace), Admins will not be able to assign any unassigned users.
e.g Office 365 Business Premium (expired) 90/100 assigned, 10 users will not be able to be assigned anymore until subscription reactivation.

v-stleun@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@stleun Thanks for the comment. The article has been updated.
