### ISSUE TITLE
Retention Policy and Deletion of Objects

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/microsoft-365-docs#1442]
Can you please add some clarity on Objects (e.g. Mailbox, Site) deletion possibility when retention Policy is applied on to those objects, Such as 
1. According to this article If a user is included in an active retention policy that retains Teams data, then deleting a mailbox of such a user is not allowed since the storage of the data needs to be retained.
But we were able to delete multiple mailboxes which were part of Teams retention Policy.
2. Does this statements apply to O365 Group Policy as well? So if we apply a retention Policy to a group, Would we be able to delete O365 Group, Group mailbox and Group SPO Site without excluding that O365 group from Retention Policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@3novsan Yes, I will ask about this & report back.

**Comment by 3novsan** [comment]
3. Does this statements apply to Teams Chat and Channel messages Retention Policy as well? So if we apply a retention Policy to a Teams Would we be able to delete Teams without excluding that Teams from Retention Policy. In our testing we were able to delete a Team which was under a Retention Policy.

**Comment by cabailey** [comment]
Hi @3novsan I'm told the answer to all your questions lies with inactive mailboxes.  Although you can delete the container for the data (such as mailboxes or teams), the data is moved to an inactive mailbox when it's subject to retention.  I'll look to clarify this in the article, but meanwhile, you can learn more about inactive mailboxes here: https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide
