### ISSUE TITLE
List of Alerts Available in E3 and E5

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/microsoft-365-docs#1443]
Can we have a link to an article with list of all the Alerts covered under E3 and alerts covered under E5. e.g. "Deleted Site" Alert activity is only available in E5 but not in E3. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@3novsan Thanks for the question, though I'm uncertain what are you asking. If you're talking about the documenting the license requirement for  "Activity that the alert is tracking" (when you create a custom alert policy), the list is too large and dynamic. The activities available to your organization to create an alert policy will be listed in the dropdown list. We do include general guidelines in note in the topic that E5 licensing is generally required for threshold alerting.
