### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by Maartenf2** [MicrosoftDocs/microsoft-365-docs#1447]
Hi,

I tested the following scenario's with their results:

- Create encrypted doc in Word Webapp, from SHP and open it again afterwards in Webapp -> OK
- Create encrypted doc in Word Client, saved locally, copied to SHP, open in Webapp afterwards -> OK
- Create encrypted doc in Word Client, save it to SHP, open in Webapp afterwards ->
"Sorry, Word can't open this document in a browser because it's protected by Information Rights Management (IRM). To view this document, please open it in the desktop version of Microsoft Word."

The Preview is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?source=docs&view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Maartenf2 Please contact Microsoft Support (https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online), and be prepared to supply your tenant details and your label configuration.

**Comment by jimmylindo** [comment]
@Maartenf2 did you find any solution on this issue? I am experience exact the same.
