### ISSUE TITLE
OneNote is missing

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/microsoft-365-docs#1453]
In the list of resources provided for an Office 365, OneNote Notebook is not mentionned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Office 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **v-teflor**

**Comment by mypil** [comment]
@RomanNG - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/05b03ea072ac19583cce9cf52d4d0d0b49096547. 


Thank you for your contribution to make the docs better! Much appreciated!
