### ISSUE TITLE
Missing documentation for MS Roadmap Featured ID: 60407 which is rolling out in production.

### ISSUE THREAD

**Issue by stuartschifter-AMA** [MicrosoftDocs/microsoft-365-docs#1454]
Missing documentation for MS Roadmap Featured ID: 60407 which is rolling out in production.

Specifically we need the settings here:
Navigate to "Security & Compliance\Threat Management\Policy\User Submissions\"
Setting = "Set up a reporting mailbox"
Setting = "Customize confirmation message"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccec9e6-5bc6-bad8-a174-0f08716f365d
* Version Independent ID: 8f10d2a4-4f84-1d19-8b45-b4fd858a4752
* Content: [What's new in Office 365 Advanced Threat Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/whats-new-in-office-365-atp?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/office-365-security/whats-new-in-office-365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/whats-new-in-office-365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @stuartschifter-AMA and thank you for the feedback. I found the item you mentioned [here](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=O365%2CRolling%20out#owRoadmapMainContent) (https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=O365%2CRolling%20out#owRoadmapMainContent); however, that feature isn't specific to Office 365 Advanced Threat Protection (which is the scope of this article). Yes we will take a look at it for documentation purposes, but the content updates might not show up in the "What's new in Office 365 ATP" article. Either way, I'll add more details to this issue when I know more (reaching out to the assigned writers for this).

**Comment by denisebmsft** [comment]
Hello again! Our product team is still working on rolling out this feature and the roadmap will be updated accordingly. We probably won't include this in the ATP article because the feature is not specific to ATP. Thanks again for your feedback!!

**Comment by stuartschifter-AMA** [comment]
CONFIDENTIAL & RESTRICTED

Hi Denise,
The new ability to create a custom mailbox for submissions is directly related to ATP Anti-Phishing and also EOP Spam submissions.
This gets confusing as part of what was messaging security keeps moving to the Security & Compliance portal.
Regards, Stu
