### ISSUE TITLE
Spelling error in tip

### ISSUE THREAD

**Issue by onefellsloop** [MicrosoftDocs/microsoft-365-docs#1456]
Just before the section "Applying a retention label automatically based on condition" there is a tip that has SharePoint spelled wrong. I do it all the time too.
&gt; Tip
&gt; See Manage the lifecycle of SharePoint documents with retention labels for a detailed scenario about using managed properties in SharePont to auto-apply retention labels and implement event-driven retention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mypil** [comment]
@onefellsloop - Thank you for pointing this out.

PR #1458 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
