### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by marcjho** [MicrosoftDocs/microsoft-365-docs#1457]
The link labelled "Download the Azure Security and Compliance Blueprint - NIST CSF Risk Assessment Checklist" does not work.  I would really like to see this checklist.  Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95ff34d4-4202-156e-20ba-d3f9b3c3131d
* Version Independent ID: debb8e35-ca89-6a31-2c73-7529a769e2d6
* Content: [National Institute of Standards and Technology (NIST) Cybersecurity Framework (CSF) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-nist-csf?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-nist-csf.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-nist-csf.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@marcjho - thanks for the feedback, the link has been updated in the topic. Thanks!

**Comment by joelbyford** [comment]
Link appears broken again.  I'll submit a PR, but I believe the link should be pointing to: https://docs.microsoft.com/en-us/azure/governance/blueprints/samples/nist-sp-800-53-rev4/
