### ISSUE TITLE
Domains under 'Setup'.

### ISSUE THREAD

**Issue by nchokoev** [MicrosoftDocs/microsoft-365-docs#1459]
1. In the admin center, go to the Settings > Domains page.
should be
1. In the admin center, go to the Setup > Domains page.

at least that's in my case...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f087dd43-183d-08bb-37d7-d893bede6efb
* Version Independent ID: be429837-0300-3de8-6c7d-2da2fabc2c17
* Content: [Update DNS records to keep your website with your current hosting provider - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@nchokoev - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/dc3a6dbb393b68828addf13012ddc3763109d6ef. 


Thank you for your contribution to make the docs better! Much appreciated!
