### ISSUE TITLE
don't use "feedback on this product" its windows feedback hub

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/microsoft-365-docs#1460]
the data goes no where.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebdb9f0-76a5-eebc-4cd7-95f5407ed029
* Version Independent ID: 05abf201-e31c-08c0-a7fc-8fd46202e8b0
* Content: [Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@bakerm00 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.  
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
