### ISSUE TITLE
Is there a specific syntax the regex for custom DLPs use?

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/microsoft-365-docs#1463]
I tried using:

`\@.*\.com|.+[\@].+[\.com]`

and when I go try to test the sensitive info type with a document containing xyz@domain.com

nothing happens...it doesn't detect the email in a sample file

**Comment by mypil** [comment]
@Rykimaruh - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@Rykimaruh - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
