### ISSUE TITLE
What about Access to existing User / Employee files

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/microsoft-365-docs#1465]
This article talks explicitly about former user/employees. What about accessing existing user/employee onedrive files and email? 
Please add a note/tip to this article to explicitly clarify situation for existing users/employees. If there is a significantly different process (other than granting Admin access), please create a new page with the info. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Get access to and back up a former user's data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@Ronsss  Thank you for your feedback we have added a note on the document via PR # https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1522 to mention that the steps remain the same for existing users as well.

Thanks
Sri

**Comment by mypil** [comment]
@Ronsss - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/05b02d5195146cd93a441bbf637c50596f649039. 


Thank you for your contribution to make the docs better! Much appreciated!
