### ISSUE TITLE
Default groups aren't editable

### ISSUE THREAD

**Issue by Robright** [MicrosoftDocs/microsoft-365-docs#1466]
**Current documentation states:** "You can edit or delete the existing role groups, but we don't recommend this. Instead of editing a default role group, you can copy it, modify it, and then save it with a different name." However, these default groups haven't been editable for some time. Suggest these two sentences are removed from the document.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions in the Office 365 Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Robright, I agree. I removed those two sentences.

Thanks for the feedback.

Closing
