### ISSUE TITLE
Updated Disposition Review location

### ISSUE THREAD

**Issue by Robright** [MicrosoftDocs/microsoft-365-docs#1468]
Disposition is now located under Records Management, not Data Governance. :)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d552f987-1606-01f7-d600-5887968ae60c
* Version Independent ID: 8c5f88de-93e7-862e-0550-fb9ac012be35
* Content: [Overview of disposition reviews - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/disposition-reviews?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/disposition-reviews.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Robright :  Thanks for your feedback!  Yes, this page is due an update throughout for the Microsoft 365 compliance center.  On my list : )
