### ISSUE TITLE
Add Office client app usage stats to Microsoft 365 Usage Analytics

### ISSUE THREAD

**Issue by lkuhn65** [MicrosoftDocs/microsoft-365-docs#1474]
Please add Office client app usage stats (Word, Excel, PowerPoint, OneNote, Outlook) to Microsoft 365 Usage Analytics so that customers can track the usage of individual client apps on Windows, Mac, iOS, Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@lkuhn65 Thank you for your feedback. At the moment there is no data available on the admin portal to track usage of applications. This is more of a design change and I will check with the @mypil  and let you know what can be done.

Thanks
Sri

**Comment by mypil** [comment]
@lkuhn65 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Office 365/Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**. 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
