### ISSUE TITLE
Broken hyperlink to  Security in Office 365 White Paper

### ISSUE THREAD

**Issue by Disorganise** [MicrosoftDocs/microsoft-365-docs#1475]
The hyperlink to Security in Office 365 White Paper leads to an error 'no longer available'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e658c5-df2f-4ef7-7308-bac311aba657
* Version Independent ID: 594382c1-63cc-aa6b-b363-c81fc412a432
* Content: [Data Encryption in OneDrive for Business and SharePoint Online - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-encryption-in-odb-and-spo?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-encryption-in-odb-and-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-encryption-in-odb-and-spo.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@Disorganise - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/9f17bf28974bf588be3a0763870b516a93bef119. 


Thank you for your contribution to make the docs better! Much appreciated!
