### ISSUE TITLE
Are OneDrive and Sharepoint storage 'the same'

### ISSUE THREAD

**Issue by Disorganise** [MicrosoftDocs/microsoft-365-docs#1476]
Am I correct in understanding both use the same blob store and encryption techniques?
Are they effectively different UI's;  OneDrive providing the 'file explorer' view, whilst sharepoint provides the website/collaboration view (and adds more features such as check out).
I've mapped drives (drive letters) to sharepoint (webdav I guess) - would I use onedrive as an alternative to that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e658c5-df2f-4ef7-7308-bac311aba657
* Version Independent ID: 594382c1-63cc-aa6b-b363-c81fc412a432
* Content: [Data Encryption in OneDrive for Business and SharePoint Online - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-encryption-in-odb-and-spo?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-encryption-in-odb-and-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-encryption-in-odb-and-spo.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by Jared-Harrington-Gibbs** [comment]
Hope that helps!

as per: [O365 encryption for skype, onedrive, sharepoint, and exchange](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange?view=o365-worldwide)
Several workloads in Office 365 store data in SharePoint Online, including Microsoft Teams, which stores all files in SharePoint Online, and OneDrive for Business, which uses SharePoint Online for its storage.

In OneDrive for Business and SharePoint Online, there are two scenarios in which data enters and exits the datacenters.<br/>
1) **Client communication with the server** - Communication to SharePoint Online and OneDrive for Business across the Internet uses TLS connections.<br/>
1) **Data movement between datacenters** - The primary reason to move data between datacenters is for geo-replication to enable disaster recovery. For instance, SQL Server transaction logs and blob storage deltas travel along this pipe. While this data is already transmitted by using a private network, it is further protected with best-in-class encryption.<br/>

As per: [data encryption in odb and spo](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-encryption-in-odb-and-spo?view=o365-worldwide)
BitLocker is deployed for OneDrive for Business and SharePoint Online across the service. Per-file encryption is also in OneDrive for Business and SharePoint Online in Office 365 multi-tenant and new dedicated environments that are built on multi-tenant technology.

**Comment by mypil** [comment]
@Disorganise - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by Jared-Harrington-Gibbs so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
