### ISSUE TITLE
Update the Steps

### ISSUE THREAD

**Issue by iryanjan18** [MicrosoftDocs/microsoft-365-docs#1477]
Missing Step 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create Office 365 Groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@iryanjan18 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/7ee01586d764c941a4a38a5cc915dc1e4122adc8. 


Thank you for your contribution to make the docs better! Much appreciated!
