### ISSUE TITLE
Safe Link settings for "time-of-click protection" and "logging of click verdicts by ATP Safe Links" 

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#1478]
Please advise on the exact Safe Link settings for "time-of-click protection" and "logging of click verdicts by ATP Safe Links" to avoid confusion. I went through the Safe Links settings and that's not the naming conventions used in there. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and real-time detections, new to Threat Explorer, changes to Threat Explorer, new to Office 365, Security, Cloud Security, new to Security in ATP, new ATP features - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide#view-data-about-phishing-urls-and-click-verdict)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @zlDev and thank you for the feedback. I updated the Safe Links article (and changes will be live this afternoon) but am not clear on what is needed for the Threat Explorer article. Did you run into issues more with Threat Explorer, or more with ATP Safe Links?

**Comment by zlDev** [comment]
Hi @denisebmsft looking forward to getting that clarified as I'm about to start configuring it. In Threat explorer User-reported view is no longer available see screenshot attached. 

![image](https://user-images.githubusercontent.com/8972968/78825239-87b5f580-79d7-11ea-95d7-e622cd3e2d4f.png)

**Comment by denisebmsft** [comment]
Hello again @zlDev, the [Threat Explorer](https://docs.microsoft.com/microsoft-365/security/office-365-security/threat-explorer) article and the [ATP Safe Links policies](https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies) articles were both updated this week, and i think you'll find the answers to your questions in those articles. What was formerly called the User-Reported report is now called Submissions. 

Also, if you are looking for initial configuration guidance, check out [Protect against threats](https://docs.microsoft.com/microsoft-365/security/office-365-security/protect-against-threats). It provides some examples and suggestions for setting up ATP. 

I hope this helps!
