### ISSUE TITLE
Update reason codes

### ISSUE THREAD

**Issue by andy-guillen** [MicrosoftDocs/microsoft-365-docs#1479]
Please update reason codes to include the following:
6xx 	Means the message failed implicit email authentication, and the sending domain is one of your organization's accepted domains (this is part of self-to-self, or intra-org, spoofing).

From the following Microsoft's article:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spoofing-protection?view=o365-worldwide

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@andy-guillen Thank you for the feedback. We have updated the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1534

Thanks
Sri

**Comment by mypil** [comment]
@andy-guillen - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/f3cefa5015e7a3ff7797a7a5cddf60943b3c22ae.

Thank you for your contribution to make the docs better! Much appreciated!
