### ISSUE TITLE
Mai instead of Mail

### ISSUE THREAD

**Issue by bradrush** [MicrosoftDocs/microsoft-365-docs#1480]
In the article there is a letter l missing from the word mail

Outlook Blocked Senders (the Blocked Senders list that's stored in each mailbox)

Blocked sender lists or blocked domain lists (anti-spam policies)

Mai flow rules   &lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;

The IP Block List (connection filtering)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79bb5c3-e92a-583b-337a-1a038e50f064
* Version Independent ID: 253ccf77-2d74-dd95-2686-a8fcdc424c7a
* Content: [Create blocked sender lists in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bradrush, fixed, but in the future you can too (no need to open an Issue first). The instructions here are more slanted to PowerShell topics, but the general idea applies to any topic in any repo: <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks for the feedback.
