### ISSUE TITLE
User-reported view 

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#1485]
Hi

The user-reported view (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/automated-investigation-response-office?view=o365-worldwide#example-a-security-administrator-triggers-an-investigation-from-threat-explorer) is no longer available. Please update with correct instruction on how to trigger investigation for user-reported emails. 

Thanks

Dmitri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de70c835-f408-83a6-3cc7-885756bd7152
* Version Independent ID: 076708dd-80e4-39d7-7e23-42730c106900
* Content: [Automated investigation and response (AIR) in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/automated-investigation-response-office?view=o365-worldwide#example-a-security-administrator-triggers-an-investigation-from-threat-explorer)
* Content Source: [microsoft-365/security/office-365-security/automated-investigation-response-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/automated-investigation-response-office.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@zlDev thank you so much for submitting this feedback. And you are correct - what was formerly referred to as the "User-reported" view in Explorer is now called the "Submissions" view. The option to trigger an investigation is on the Actions menu, which is activated when you select one or more items on the Email tab. I have updated the article accordingly, and the changes should be live before 5 p.m. Pacific Time. I hope this helps. And thank you @mypil for your help as well!
