### ISSUE TITLE
what scc roles are required to use submissions?

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/microsoft-365-docs#1486]
please outline it clearly;;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Admin submissions in Office 365, O365 submissions, Office 365 spam problem, O365 false negative, submit phish in office 365, submit email for scanning, suspicious email in Office 365, scan a mail, have Microsoft scan for phish, have Microsoft scan for spam, submit e-mail, submit email, dodgy email, bad actor mail, suspicious, untrusted mail, report phish emails to Microsoft, report phish emails to Microsoft, report malicious email to Microsoft, report scam email to Microsoft, report malware in email to Microsoft, spam email in inbox office 365, virus in email office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@bakerm00, topic updated.

Thanks for the feedback,

Closing

**Comment by JeremyTBradshaw** [comment]
@chrisda sorry to call on you directly, but I'm thinking you'll likely know the answer.  If I'm solely assigned the Exchange Service Administrator role in AAD, which is automatically a member of EXO's Organization Management, is that good enough to satisfy the "Organization Management or Security Reader" requirement advertised here?  Where I'm working from, it's not working, but I'm trying to figure out if it's a problem or the way things work.

I do have a support case on the go, but figured I'd ask here which sometimes goes way smoother.

**Comment by chrisda** [comment]
@JeremyTBradshaw, if the cmdlets for a feature are available in Exchange Online PowerShell (and most of the security/protection related cmdlets are), you're in luck; you can use the procedures in [this topic](https://docs.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions). If the cmdlet is available in Security & Compliance Center PowerShell (most compliance-related features), no such luck.
