### ISSUE TITLE
Fix incorrect hyperlinks 

### ISSUE THREAD

**Issue by mzwetkow** [MicrosoftDocs/microsoft-365-docs#1488]
1. Hyperlink for Office 365 GxP Guidelines should be updated to point to the most recent version of the document which can be found here: https://resources.techcommunity.microsoft.com/wp-content/uploads/2019/05/Microsoft-Office-365-GxP-Guidelines.pdf

2. Montrium hyperlink should be updated to point to: https://www.montrium.com/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c91f23-19e5-4170-c4a5-e9bd05434ffa
* Version Independent ID: 4fbff369-1dc1-4597-df9e-dfcfdb130ba3
* Content: [Good Clinical, Laboratory, and Manufacturing Practices (GxP) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-gxp?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-gxp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-gxp.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@mzwetkow - thanks for the feedback, the link for the updated whitepaper has been added. The link for Montrium was already correct. Thanks!

**Comment by mzwetkow** [comment]
@robmazz - I see that the link for Office 365 whitepaper is still pointing to the old version.  The new version is located here: https://resources.techcommunity.microsoft.com/wp-content/uploads/2019/05/Microsoft-Office-365-GxP-Guidelines.pdf
