### ISSUE TITLE
Adding hundreds of new users - is there a way to automatically send the provisional passwords to their personal emails?

### ISSUE THREAD

**Issue by damblas** [MicrosoftDocs/microsoft-365-docs#1489]
I am one of the administrators of the Office 365 package in my association, which has almost 2000 members. I must add all the members as new users to Office 365. Hence, I have created a CSV file following the provided guidelines. However, I do not find a way to automatically send the created new provisional passwords to the personal email of each of the new users. Is there a way to do so? I could add the list of the member's emails to the CSV file in one of the columns I am not using (e.g. address) if necessary.
Many thanks for your support,

David

---
#### Detalls del document

⚠ *No editeu aquesta secció. Es necessita per a docs.microsoft.com ➟ enllaç de problemes del GitHub.*

* ID: 8319eb67-907b-5973-8690-6bfa50585ae7
* Version Independent ID: 1c0572e0-272c-ed12-d020-17dcdc45e81d
* Content: [Add users individually or in bulk to Office 365 - Microsoft 365 admin](https://docs.microsoft.com/ca-es/microsoft-365/admin/add-users/add-users?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/add-users.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@damblas I am not aware if there is a way - I will look into this

**Comment by Sirkkuw** [comment]
OK - this is not currently possible. It has been a feature request, however.

**Comment by damblas** [comment]
Ok, many thanks for your answer. Finally I manged to do so using the mail merge Personalization tool in Outlook, which allows you to send mass email using a csv list.
