### ISSUE TITLE
Unable to connect to Power BI Desktop

### ISSUE THREAD

**Issue by Ebenezerpaul** [MicrosoftDocs/microsoft-365-docs#1491]
I tried to connect the Usage Analytics using both the PBIT and Reporting API(ODATA), but both results in error. 
Able to connect to the Power BI service, but unable to download the PBIX file.
Please check if there is anything wrong with the "Microsoft 365 Usage Analytics.pbit" from Microsoft download centre, since I needed it to create a custom report in Power BI 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a146d3a-b3d6-8993-e7f6-1b9da59f4ced
* Version Independent ID: 71a7043f-adcf-42d7-1c4b-670306a764f7
* Content: [Customize the reports in Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/customize-reports?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/usage-analytics/customize-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/customize-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@Ebenezerpaul you need to have the Power BI Pro version in order to use this.Is that the problem?

**Comment by mypil** [comment]
@Ebenezerpaul - We would like to follow up. Can you please respond to the query of Sirkkuw?

Thank you.

**Comment by mypil** [comment]
@Ebenezerpaul - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.

**Comment by Ebenezerpaul** [comment]
Sorry for the late reply, I have a Power BI pro licence. I was able to connect to the Microsoft 365 Analytics using Power bi service. But, I had a problem while using the PBIT from the Download centre. While loading the data there is an error

**Comment by Ebenezerpaul** [comment]
I like to add a few more tables to the already available data model for Microsoft 365 Analytics. and report on it
