### ISSUE TITLE
Sensitivity Label Reader permission that is in Security Reader role doesn't work

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/microsoft-365-docs#1494]
Sensitivity Label Reader permission doesn't work -  it only gives a view of Security Information Types

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35afb875-bb47-fc7d-7e95-36cbde2b671b
* Version Independent ID: 3a2ad411-cae1-efa2-f089-97ed2df52fb4
* Content: [View label usage with label analytics - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/label-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/label-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/label-analytics.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by cabailey** [comment]
@bakerm00  I don't see the Sensitivity Label Reader role listed as supported on this page for label analytics?  Per my Yammer response to your post (https://www.yammer.com/askipteam/threads/608267557003264) this role is currently supported for the PowerShell labeling cmdlets only.  When it is supported in the Microsoft 365 compliance center, we'll update the documentation.

**Comment by cabailey** [comment]
@bakerm00  I haven't seen a reply here or on the Yammer post.  I don't see a problem with the documentation so I'll close this GitHub Issue but if you still have questions about this new role, I recommend you follow up on your Yammer post.
