### ISSUE TITLE
User-reported

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#1495]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide#review-email-messages-reported-by-users

The user-reported view is no longer available from the menu. I believe it has been moved to the "Review" section under "Threat management"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and real-time detections, new to Threat Explorer, changes to Threat Explorer, new to Office 365, Security, Cloud Security, new to Security in ATP, new ATP features - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide#review-email-messages-reported-by-users)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Hello @zlDev 
The document has been updated here https://github.com/MicrosoftDocs/microsoft-365-docs/commit/2a2c1b70a4a540a6f4a0bb3b37cd085b6a02df71
Thank you

**Comment by zlDev** [comment]
The screenshot is still showing the old menu.

**Comment by get-itips** [comment]
> The screenshot is still showing the old menu.

will create a PR to update it, good catch

**Comment by mypil** [comment]
@zlDev - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/4522bf03d52e99a153d92de3491c260f07ba106d. 


Thank you for your contribution to make the docs better! Much appreciated!
