### ISSUE TITLE
Word Online Safe Links in the browser

### ISSUE THREAD

**Issue by swhite-strath** [MicrosoftDocs/microsoft-365-docs#1496]
This document indicates that safe links works within office online documents. If i click a blocked link in a word online document it does not display a warning page where as if i use my desktop client it does. I have had a ticket open with Microsoft for weeks and am going round in circles trying to get an answer for this. Ticket #:18625079

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d33c51-09fd-8151-9e5b-9f2edbbaa5b2
* Version Independent ID: 7d3b3209-1382-62a5-75db-eb17ea34c928
* Content: [How Office 365 ATP Safe Links works - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-atp-safe-links-works?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/how-atp-safe-links-works.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-atp-safe-links-works.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by swhite-strath** [comment]
[Safe Links Online (Not Working.zip](https://github.com/MicrosoftDocs/microsoft-365-docs/files/4388251/Safe.Links.Online.Not.Working.zip)

**Comment by get-itips** [comment]
Hello @swhite-strath how are you? 👍  Opening a support ticket was the right thing to do, as some time has passed, did you get any confirmation about the issue?
Here, we can help with documentation issues, however, I would like to know to understand if any article needs to be fixed or improved, based on your feedback.

@MSFTTracyP 
I do not know if this is a transient error however I could not make ATP Safe Links work in, for example, Word Online. Just to be sure if we need to impact any documentation, in case this is a current issue or if you have more information about this, can you help? I appreciate.

**Comment by swhite-strath** [comment]
Thanks for getting back to me, I am not having much luck with the ticket. Its went cold and I'm no longer getting a reply from the support agent. I have messaged them again to try get some clarification.

**Comment by mypil** [comment]
@swhite-strath - We would like to follow up. Do you have any updates on this?

**Comment by swhite-strath** [comment]
Hi @mypil I was made the close my original ticket and open a new one as it was opened for too long. I have sent logs and step files of the issue and awaiting a response.

**Comment by mypil** [comment]
@swhite-strath - Thank you for engaging with the community here for the docs.

This git issues channel is for documentation changes only. For now, we will have to close this issue. Please open a new issue if you get any feedback from your support ticket with some information that can be added to make this doc better or if there are any documentation errors found so we can help to update the doc as needed.
