### ISSUE TITLE
Backing up a users email

### ISSUE THREAD

**Issue by lgkron** [MicrosoftDocs/microsoft-365-docs#1498]
I believe by default when you open a users email in your email account in Outlook it will download 1 year.  I think this article explains how to ensure that all email downloads locally before saving a back up PST:  https://support.office.com/en-us/article/turn-on-cached-exchange-mode-7885af08-9a60-4ec3-850a-e221c1ed0c1c. 
I just know that in my first attempt I was missing some email and changing cache to ALL seemed to allow me to get everything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Get access to and back up a former user's data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@lgkron Thank you for your feedback. We have added a note on the document to reference the default mail available offline and how to increase it. This is updated via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1522

Thanks
Sri

**Comment by mypil** [comment]
@lgkron  - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/05b02d5195146cd93a441bbf637c50596f649039. 


Thank you for your contribution to make the docs better! Much appreciated!
