### ISSUE TITLE
Problem with installing Export App on Microsoft Edge Chromium

### ISSUE THREAD

**Issue by misprogrammer** [MicrosoftDocs/microsoft-365-docs#1499]
I had trouble and found that I needed to change a registry key in order to download and work: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\Security\TrustManager\PromptingLevel
LocalIntranet to Enabled 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7e8e46-96fd-2679-908f-65862428d018
* Version Independent ID: b40db2b9-6918-9f89-ae5b-73b5760439fa
* Content: [Use the Office 365 eDiscovery Export Tool in Microsoft Edge - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/configure-edge-to-export-search-results?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/configure-edge-to-export-search-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/configure-edge-to-export-search-results.md)
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@misprogrammer Sound like you were able to troubleshoot this issue and was able to install the eDiscovery export tool. If possible, can you reply with what the trouble was and how you determined the registry fix? Can you send repro instructions or an error message? From engineering, is sounds like you reset the trust prompt behavior back to it's default setting, as per: https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-configure-the-clickonce-trust-prompt-behavior?view=vs-2019

If this is a common issue, I can look into documenting it. Thanks in advance for any assistance.
