### ISSUE TITLE
Examples are always great, Step 1 needs one badly

### ISSUE THREAD

**Issue by ITMHelps** [MicrosoftDocs/microsoft-365-docs#1500]
A sample command in Step 1 would go miles to making this article useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 464a4f5f-8740-79aa-3647-a9b5e351656c
* Version Independent ID: a51103db-92b2-d225-d493-81d624e6fc6b
* Content: [Search for and delete email messages in your Office 365 organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by get-itips** [comment]
Hello @ITMHelps how are you?
Created a PR to propose adding a working example to step # 1.
If it gets approval, it will be reflected on the article.
Thank you

**Comment by mypil** [comment]
@ITMHelps - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/9d4cf3991dcca2d04733b86248e5d8014a657d2f. 


Thank you for your contribution to make the docs better! Much appreciated!
