### ISSUE TITLE
Cloudflare Domain Registrar

### ISSUE THREAD

**Issue by nathanturnock** [MicrosoftDocs/microsoft-365-docs#1503]
The following statement in this page is false, Cloudflare does offer Registrar services. 

"Cloudflare does not offer domain registration services."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6107c99-df0b-8a33-f291-086ea6fd5034
* Version Independent ID: 0ba87689-7a57-c3f8-af4b-3267c81b933d
* Content: [Create DNS records at Cloudflare for Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by get-itips** [comment]
Hello @nathanturnock Thanks for noticing. I created a pull request to propose an edit to the article.
If it gets approval, it will be reflected on the online version of the article.
Thank you

**Comment by mypil** [comment]
@nathanturnock - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/fe2aa180853a317c3ae96ed0b4013bd8c1e50241. 


Thank you for your contribution to make the docs better! Much appreciated!
