### ISSUE TITLE
Email message options

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/microsoft-365-docs#1504]
With the changes to the email quarantine nightly email, I'm not certain if the 'release' button in email reports the message to Microsoft or not (there is no report option anymore). Can you clarify if people can use the release button in email to send feedback to Microsoft or if they have to go into the portal to review and release to have the option to provide feedback?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfc15d1-833b-3139-6bc0-1acb97d507c8
* Version Independent ID: 31e24618-c2e6-4fe4-9651-04d6007548a4
* Content: [Find and release quarantined messages as a user in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cchambers-cap, you are correct. The **Release** button does just that with no reporting. For reporting, you need to click **Review** to go into the Quarantine portal in the Security & Compliance Center where users can release and report their messages.

**Comment by mypil** [comment]
@cchambers-cap - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by chrisda  so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
