### ISSUE TITLE
typo found

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1508]
"356" - Alerts – Have greater visibility into all the alerts across your Microsoft 356 environment, 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d8f70e-8492-f634-413b-8c5b71383eba
* Version Independent ID: d63bbba4-ee59-81eb-a1ec-de343ac01599
* Content: [Overview of the Microsoft 365 security center - Microsoft 365 security](https://docs.microsoft.com/en-gb/microsoft-365/security/mtp/overview-security-center?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/mtp/overview-security-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/overview-security-center.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by mypil** [comment]
@challengelogic - Thank you for pointing this out.

PR #1509 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
