### ISSUE TITLE
Modern Desktop Lab Kit fails to extract and complete

### ISSUE THREAD

**Issue by qewade0701** [MicrosoftDocs/microsoft-365-docs#1510]
The lab kit fails to fully extract and complete the automated setup. Despite reachinng 100% only a sample of theVM's were created. The setup wizard is displaying a constant error. See screenshots for more info.
![VMs created](https://user-images.githubusercontent.com/62809155/77830290-8e01c300-70f5-11ea-8c63-a43dad3b1e43.PNG)
![Cannot validate error](https://user-images.githubusercontent.com/62809155/77830343-d7521280-70f5-11ea-8dbd-5746ed5f4a24.PNG)

**Comment by mypil** [comment]
Closing this issue as it is a duplicate to #1511.
