### ISSUE TITLE
Modern Desktop Lab Kit fails to extract and complete

### ISSUE THREAD

**Issue by qewade0701** [MicrosoftDocs/microsoft-365-docs#1511]
The lab kit fails to fully extract and complete the automated setup. Despite reaching 100% only a sample of the VM's were created. The setup wizard is displaying the following constant error as it retries.
"Cannot validate argument on parameter 'ParameterComplete'. The 129 argument is greater than the maximum allowed range of 100. Supply an argument that is less than or equal to 100 and then try the command again."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office Deployment Lab Kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Hi - it appears the host machine either has too little CPU or storage, probably storage. I've verified this works on fine on our end, however we’ll add a ‘troubleshooting’ section to the next version of the guide to help with this. Thanks!
