### ISSUE TITLE
Needs link to admin controls 

### ISSUE THREAD

**Issue by dsnorton** [MicrosoftDocs/microsoft-365-docs#1512]
This page needs to link on how to check if these are enabled and instructions on how to enable it or disable as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10769542-cd9f-30a1-be29-2a37627149fb
* Version Independent ID: a99e4d71-62da-563d-a1b2-97d8d0bc358c
* Content: [Using self-service sign up in your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/self-service-sign-up?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/self-service-sign-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/self-service-sign-up.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@dsnorton I've added a link to the article that tells how to do this.
