### ISSUE TITLE
German version outdated + table broken

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1513]
Hello,

the German version is older than the English version of this article. Additionally the table at the end of the article is broken in the German version. Please update this. Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea79921a-7f83-58f1-c0a4-6eb0efce0d26
* Version Independent ID: b60110ef-71ad-9962-74de-734062708ff8
* Content: [Top 10 ways to secure Office 365 and Microsoft 365 Business plans - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@GiantCrocodile the table is fixed - and  I am flagging loc re the German version.

**Comment by TinaMcN** [comment]
@GiantCrocodile thanks for reporting this.  I'm looking into why the German file is not updated. The same thing is true for the other languages too.

**Comment by GiantCrocodile** [comment]
@TinaMcN Hi! Would be great if you can share your insights here. Thank you!

**Comment by TinaMcN** [comment]
@GiantCrocodile the German article has now been updated and the table is fixed.  https://docs.microsoft.com/de-de/microsoft-365/admin/security-and-compliance/secure-your-business-data  Hope it looks ok for you now.

**Comment by GiantCrocodile** [comment]
@TinaMcN Thank you! It looks better now. I noticed another issue: When you click on the avatar of the Github user who edited that page (on the right of the estimated time to read the article) it leads to a 404 file not found error on GitHub. Seems like the GitHub link is wrong in the German articles.

**Comment by TinaMcN** [comment]
@GiantCrocodile wow, that is a good bug you found.  I see it repro's on multiple articles and multiple languages.  I will do some investigation to try to fix it soon.

**Comment by TinaMcN** [comment]
@GiantCrocodile I just wanted to let you know that the issue you noticed with the 404 from the avatar on German pages has finally been fixed, it took a lot of investigation to figure out what was going wrong.  Thanks again for bringing it to my attention.

**Comment by GiantCrocodile** [comment]
@TinaMcN Great to hear and thank you for the update!
