### ISSUE TITLE
Please add question and answer in FAQ

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#1514]
Hello,
Please add question about "duplicates". 
As example "What is happening with duplicates?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f9f87e-6f96-9663-114a-f6bd74a7a7f4
* Version Independent ID: b3ba56e3-0c78-f286-1c01-12375bf00f62
* Content: [Overview of importing your organization's PST files to Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/importing-pst-files-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/importing-pst-files-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@lightupdifire Thanks for the question. I will add a FAQ.

To answer the question, by default, the import service checks for duplication of items and doesn't copy the data from the PST file into the mailbox or archive if a matching item exists in the **target folder** in target mailbox or target archive. If you re-import the same PST into a different TargetRootFolder (that you specify in the PST import mapping file) than the one in the 1st import, all items will be reimported.
