### ISSUE TITLE
Global Admin cannot create New Team

### ISSUE THREAD

**Issue by luconsta** [MicrosoftDocs/microsoft-365-docs#1515]
It seems that after following the steps in this article, a Global Admin could no more create Teams from scratch, must create first a Group in Admin console. This is happening even if that Global Admin is also the Owner of the "Group Creators" group - the only option he's able to use is "Add to an existing Group". When the Global Admin, as owner of that group is added as a Member too, will have the option to create a team from scratch or from an existing group.
This will contradicts your statement from this article "Office 365 Global admins can create Groups via any means, such as the Microsoft 365 admin center, Planner, Teams, Exchange, and SharePoint Online."
So, I think I miss something or something must be corrected in this documentation? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create Office 365 Groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by omerahm** [comment]
Ok, I am facing the same issue the script has blocked everyone in the tenant to create teams including myself (global admin). This is not right, there must be a step to undo it.

**Comment by luconsta** [comment]
Hello @omerahm , 
How to "undo it" is documented already: set **$GroupName to** "" and **$AllowGroupCreation** to "**True**" and rerun the script.

It just seems that the **Global Administrator** must be also **member** in the **$GroupName** even if is the owner of that group because was creating it, and in my case this will solve the problem.

My problem was that the documentation was misleading with this statement:

> "Office 365 **Global admins can create Groups via any means,** such as the Microsoft 365 admin center, Planner, **Teams**, Exchange, and SharePoint Online."

In Teams the Global Admin must be member of the creators grup to be able to create a team from scratch, otherwise it has to create the group in the Admin center/Groups.

**Comment by omerahm** [comment]
Hi @luconsta,
Thanks for replying yes I had done it already.
By this, I have realised that it is not working on the GroupName but the entire tenant.  Moreover, when I corrected the issue I tired
$GroupName = "Groups Creation Denial"
$AllowGroupCreation = "True"
And the funny thing is before running the script I had deleted the group (20+ minutes ago) and there was no error, which Indicates the script is not checking $GroupName

**Comment by umair-iscs** [comment]
Hi, I am facing the same as it is applying for whole tenant, any possibility to apply only specific group, it is not checking security group I have revert back then only I am able to create a group or team.
How to enable the restriction for specific users/group, if anyone has done these please share your feedback.

**Comment by omerahm** [comment]
@umair-iscs couldn't find any solution to it yet. But try something create a user with Group Admin Role. Then run the script if the group admin can create groups then I hope this will resolve your issue. Since I have a huge tenant doing it will be a mess.

**Comment by umair-iscs** [comment]
I have fixed it by running this 

$Setting = Get-AzureADDirectorySetting -Id (Get-AzureADDirectorySetting | where -Property DisplayName -Value "Group.Unified" -EQ).id
$Setting["EnableGroupCreation"] = $False
$Setting["GroupCreationAllowedGroupId"] = (Get-AzureADGroup -SearchString "Allowed Security Group Name").objectid
Set-AzureADDirectorySetting -Id (Get-AzureADDirectorySetting | where -Property DisplayName -Value "Group.Unified" -EQ).id -DirectorySetting $Setting

hope this will help others !

**Comment by mypil** [comment]
@luconsta @omerahm - Thank you for submitting feedback.

From our understanding, the issue has been answered by @umair-iscs so we will close this issue.

Thank you for engaging with the community here for the docs.

**Comment by desarrollocdb** [comment]
Hello, I have a similar problem.
The global administrator cannot create teams. It is added in the security group and I have followed all the steps indicated by umair-iscs.

**Comment by umair-iscs** [comment]
You have to revert the setting to default then run the above script.
also you need to specify the security group name here (Get-AzureADGroup -SearchString "GroupName") where you have added the users/group are allowed to created group, those are not in your created security group will not be able to create groups.

Let me know if you need any further help.

**Comment by desarrollocdb** [comment]
So I don't run the script from step 2 but the script that you wrote?

**Comment by desarrollocdb** [comment]
It has already worked.

Thank you!

**Comment by desarrollocdb** [comment]
I cannot create or edit groups from the team manager but I can create them from teams

**Comment by Farinpt** [comment]
Hi, 
Thx for all support first of all.
I have undone the first script, then run @umair-iscs code, but now everyone is able to create teams again.
I have the security group set up and done the update to the code where my secure group name went to "My Allowed Security Group Name Here". Is this correct?

$Setting = Get-AzureADDirectorySetting -Id (Get-AzureADDirectorySetting | where -Property DisplayName -Value "Group.Unified" -EQ).id
$Setting["EnableGroupCreation"] = $False
$Setting["GroupCreationAllowedGroupId"] = (Get-AzureADGroup -SearchString "My Allowed Security Group Name Here").objectid
Set-AzureADDirectorySetting -Id (Get-AzureADDirectorySetting | where -Property DisplayName -Value "Group.Unified" -EQ).id -DirectorySetting $Setting
