### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1516]
Where it reads "Fill in your organization name (example: contosotoycompany), the two-character country code for your location, a common account password, and then run the following commands from the PowerShell prompt:" it should probably just say Country Code needs to be US... I attempted to put UK and the script didn't work.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24336d5d-743f-1f94-f7b6-c33b6a1ec7d8
* Version Independent ID: 4219dcf8-9cde-256b-5e2c-0c410ef5df1e
* Content: [Lightweight base configuration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-gb/microsoft-365/enterprise/lightweight-base-configuration-microsoft-365-enterprise?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/lightweight-base-configuration-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/lightweight-base-configuration-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@challengelogic The ISO 3166 standard Alpha 2 country code for the United Kingdom is "GB". See https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes for the list. Thanks for the feedback.
