### ISSUE TITLE
typo under your roles & responsibilities 

### ISSUE THREAD

**Issue by dchomas** [MicrosoftDocs/microsoft-365-docs#152]
Exchange Online misspelled as Oonline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b703df2-1359-0497-3096-d0f9eb176e27
* Version Independent ID: 70eab420-d40c-dac2-875e-4abf30072a3e
* Content: [Microsoft Managed Desktop roles and responsibilities](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/intro/roles-and-responsibilities)
* Content Source: [microsoft-365/managed-desktop/intro/roles-and-responsibilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/managed-desktop/intro/roles-and-responsibilities.md)
* Service: **m365-md**
* GitHub Login: @jdeckerMS

**Comment by jdeckerms** [comment]
@dchomas thanks for pointing that out, we'll get it fixed immediately.
