### ISSUE TITLE
Navigation suggestion

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1520]
On the new SharePoint admin center tab, click Access control - should be On the new SharePoint admin center tab, click Policies, then Access control.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1209ea6-15c8-1bb5-9837-608db57688b9
* Version Independent ID: b02e1c55-5398-9a38-ba79-037f2b2a49f3
* Content: [Increased Microsoft 365 security for your Microsoft 365 Enterprise test environment - Microsoft 365 Enterprise](https://docs.microsoft.com/en-gb/microsoft-365/enterprise/increased-o365-security-microsoft-365-enterprise-dev-test-environment?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/increased-o365-security-microsoft-365-enterprise-dev-test-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/increased-o365-security-microsoft-365-enterprise-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@challengelogic The article has been updated. Thanks for letting us know.
