### ISSUE TITLE
Enabling DKIM without Windows PowerShell

### ISSUE THREAD

**Issue by mikaelf** [MicrosoftDocs/microsoft-365-docs#1521]
There are no instructions for how to enabling DKIM for Office 365 without Windows PowerShell. How can I enable DKIM using another OS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [Use DKIM for email in your custom domain in Office 365, 2048-bit, 1024-bit, steps, How it works, SPF, DMARC - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Hello @mikaelf Mikael, how are you? 👍 
For now, you will have to rely on the admin center to do that, the article includes [those steps](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#enable-dkim-signing-for-your-custom-domain-in-office-365) too.
Hope this info helps you!

**Comment by mikaelf** [comment]
Hi! Thanks. Just to clarify, is it possible to enable DKIM for my custom domain from the web interface alone, without having to enter PowerShell commands? The article leads me to believe I have to do CLI stuff!

**Comment by get-itips** [comment]
> Hi! Thanks. Just to clarify, is it possible to enable DKIM for my custom domain from the web interface (the admin center) alone, without having to enter PowerShell commands? The article leads me to believe I have to do CLI stuff!

Yes, the article presents alternatives, you either use the admin center o powershell.

**Comment by mypil** [comment]
@mikaelf - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mikaelf** [comment]
I managed to follow the enable DKIM now. 

The hard part was actually to ["Publish two CNAME records for your custom domain in DNS"](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#publish-two-cname-records-for-your-custom-domain-in-dns). Would be pretty sweet to be able to get the correct CNAME records right there in the documentation, without having to run the two PowerShell commands or figure it out yourself reading the format or the example.

 @get-itips (@mypil)

**Comment by get-itips** [comment]
> I managed to follow the enable DKIM now.
> 
> The hard part was actually to ["Publish two CNAME records for your custom domain in DNS"](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#publish-two-cname-records-for-your-custom-domain-in-dns). Would be pretty sweet to be able to get the correct CNAME records right there in the documentation, without having to run the two PowerShell commands or figure it out yourself reading the format or the example.
> 
> @get-itips (@mypil)

@mikaelf **Thanks for your feedback**, while it is true that the section you mention starts with a PowerShell cmdlet, later on, explains how the DNS records should be created, with real examples (for _cohovineyard-com_) and meaning of each component, do you still feel this is not clear enough? **Thank you**

**Comment by mikaelf** [comment]
I still believe it could be easier and clearer. The rest of the docs are super easy to understand.

**Comment by Radiergummi** [comment]
@get-itips currently, the article says verbatim:
> 1. Sign in to Microsoft 365 with your work or school account.
> 2. Select the app launcher icon in the upper-left and choose Admin.
> 3. In the lower-left navigation, expand Admin and choose Exchange.
> 4. Go to Protection > dkim.
> 5. Select the domain for which you want to enable DKIM and then, for Sign messages for this domain with DKIM signatures, choose Enable. Repeat this step for each custom domain.

These steps lead to the dkim page in the old Exchange admin center, which shows the following banner:
> DKIM has a new home and improved functionality. By December 1, 2020 – the DKIM experience will be removed from the Exchange admin center. Please use the updated experience in the Security and Compliance Center, DKIM page.

The table also provides no controls at all, so naturally one reads the banner and follows through to the Security and Compliance Center link, which leads to [protection.office.com/dkimv2](https://protection.office.com/dkimv2).

Infuriatingly, though, it only shows the status for non-DKIM-enabled domains, without any way to change it:
> **Status**
> No DKIM keys saved for this domain.

As it is, both the docs are outdated and the UI is nonfunctional. How am I supposed to enable DKIM?

**Comment by sigurddev** [comment]
> @get-itips currently, the article says verbatim:
> As it is, both the docs are outdated and the UI is nonfunctional. How am I supposed to enable DKIM?

I don't think there is another way anymore. It used to be there in the past then suddenly Powershell was needed. That worked, but then a new url was needed to run the scripts, which worked too, but now both does not work anymore on my Windows 10 and neither on my Linux with PowerShell for Linux installed. How can a self-employed person that wants to use a normal security feature set up Office 365 with DKIM. They cannot. Even if you have knowledge of the technology, you cannot get it to work. It is a mess.

**Comment by Radiergummi** [comment]
@get-itips @MSFTTracyP @mypil I finally took the time to sort this out with MS365 support, which gave me the following answer (emphasis mine):

> Hello Moritz, 
> Hope you are doing good!
>
> I have checked all the possible ways to enable DKIM. However, **_it not possible without PowerShell_**. Please follow the below article to install PowerShell on macOS.
>
> [Installing PowerShell on macOS - PowerShell | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7.1#installation-via-direct-download)
> 
> Thank you for choosing Microsoft.
>
> Kind Regards,
> Nidhi
> O365 Ambassador​

I see this as confirmation that the documentation is definitely outdated, wrong, and misleading. The only reason I care about this is because the whole thing _really_ got on my nerves and wasted lots of time, so could you _please_ get this sorted to spare others from this?

**Comment by sigurddev** [comment]
I used this script on two domains and someone else did one with the same script. REPLACE the words in CAPITAL :)

```
Install-Module -Name ExchangeOnlineManagement
Import-Module ExchangeOnlineManagement
Get-Module ExchangeOnlineManagement
$credential = Get-Credential REPLACEWITHYOUROFFICE365MAILADRES
Connect-ExchangeOnline -Credential $credential -ShowProgress $true
New-DkimSigningConfig -DomainName DOMAINNAME -KeySize 2048  -Enabled $true
```
When you get an error, you could use this command:
`Set-ExecutionPolicy RemoteSigned`
and run again.

To check the DKIM status
`Get-DkimSigningConfig -Identity DOMAINNAME`

Replace the DKIM keys with a new one:
`Rotate-DkimSigningConfig -Identity DOMAINNAME`

**Comment by pgassmann** [comment]
@mypil Can you reopen this issue and find a solution? 

Setting up DKIM should be a simple process verified by the custom domain setup like spf and other dns entries. https://admin.microsoft.com/Adminportal/Home?#/Domains

**Comment by frankie567** [comment]
Definitely agree here. Having to use PowerShell to enable DKIM is completely crazy. You can't reasonably expect small business customers with limited tech knowledge (and no dedicated IT employees) to achieve this.

This is something that can be done in minutes with Google Workspace or e-mailing providers.

**Comment by Radiergummi** [comment]
@mypil not responding at all is one way to handle customer feedback. This issue is still standing - the admin center doesn't provide any way to change DKIM keys, and the docs don't even reflect the UI change.

**Comment by rtpHarry** [comment]
OK I thought I was being dumb but having to set up powershell and start messing with that sucks. I normally use Google Workspace and its a few clicks to get the DNS records I have to add. This needs to make it into the new security admin panel asap.

**Comment by chrisbuetti-dp** [comment]
This shouldn't be closed.
