### ISSUE TITLE
Publish two CNAME records for your custom domain in DNS

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#1523]
Hello,

About "For example, if you have an initial domain of cohovineyardandwinery.onmicrosoft.com, and two custom domains cohovineyard.com and cohowinery.com, you would need to set up two CNAME records for each additional domain, for a total of four CNAME records."

Can you please explain more?
Where to set it? For which domain? How this setup is in your view? What exactly do you mean by "set up two CNAME records for each additional domain"?

As an example, let's take a tenant: tenant.onmicrosoft.com
I have two custom domains:
domain1.com
domain2.com
Were domain1.com is set as default
Both domains DNS managed in Microsoft.
Now, what should be set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [Use DKIM for email in your custom domain in Office 365, 2048-bit, 1024-bit, steps, How it works, SPF, DMARC - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. 

Enabling DKIM for a domain requires two CNAME records(Selector1 and Selector2) to be added to your DNS registrar.

When you add a domain to o365 tenant, You have two options 1) Let Microsoft manage my DNS records 2) I'll manage the records myself.

If you choose 1) All you would do is to point your domain to Microsoft Provided NameServer records. No additional action needed in such a case and all your DNS records (CNAME, MX, TXT, etc gets automatically configured)

If you choose 2) You will have access to your DNS registrar and you can add the two CNAME records(selector 1 and 2) to the DNS registrar to enable DKIM. The below link provides you more information on adding the DNS records.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#publish-two-cname-records-for-your-custom-domain-in-dns

Please review and let me know if you think there is any change required in the document.

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba 
Thanks for checking this. It is clear now.
