### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by BayJayRakes** [MicrosoftDocs/microsoft-365-docs#1525]
Could this script be modified to work with admin accounts that use MFA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5315da9-9aa3-c091-04fd-1b3dd42b975c
* Version Independent ID: 13f78819-03d0-adf2-2cf8-33b924469d96
* Content: [Use Content Search to search the mailbox and OneDrive for Business site for a list of users - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@BayJayRakes Thanks for the inquiry. No, it's not possible to use a script to logon when MFA is enabled/required. Please see github issue #1428
