### ISSUE TITLE
Nice Start - but incomplete

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1526]
While this is helpful, it does not provide any guidance about tasks that should be performed to implement the numerous compliance tools in O365. It would be more helpful if it included some steps about insider risk, e-Discovery, compliance scorecard etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2650327-5996-2155-2b0f-b646be7752c7
* Version Independent ID: 859bf570-6c39-50ed-009a-e79262954247
* Content: [Plan for security & compliance in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/plan-for-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/plan-for-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/plan-for-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by get-itips** [comment]
Hello @DeanGross Dean, we are looking into this, thanks

**Comment by chrfox** [comment]
HI @DeanGross 
Thanks for the feedback, we are working on a project to add more higher level guidance.

Chris
