### ISSUE TITLE
Graph API support for Quarantine

### ISSUE THREAD

**Issue by akvadlamani** [MicrosoftDocs/microsoft-365-docs#1527]
Is there Graph API to support quarantine operations (list/release/others)? It has been pretty difficult to find the information. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7325da5e-3116-025e-7ae8-f8dc837897bf
* Version Independent ID: 313221de-4f12-3b21-4a1c-0bdd3d3cb1d2
* Content: [Manage quarantined messages and files as an admin in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Standard PowerShell support, which you can likely tie into programmatically:

- [Delete-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/delete-quarantinemessage)
- [Export-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/export-quarantinemessage)
- [Get-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/get-quarantinemessage)
- [Get-QuarantineMessageHeader](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/get-quarantinemessageheader)
- [Preview-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/preview-quarantinemessage)
- [Release-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/release-quarantinemessage)

**Comment by akvadlamani** [comment]
Thank you Chris. It would have nice to have the support in Graph API itself rather than to start learning Powershell now. Is it on the roadmap anytime soon?

**Comment by chrisda** [comment]
I was only aware of using Graph API for reporting.

**Comment by chrislogan2** [comment]
I think a perfectly valid use case would involve using the Graph API for quarantine reporting.  As far as I'm aware the Graph API still doesn't have a way to facilitate this. Seems like a gap that could be filled. 

Also worth mentioning the Graph API is definitely useful for more purposes than reporting.

**Comment by mayerlench** [comment]
Since these 

> Standard PowerShell support, which you can likely tie into programmatically:
> 
> * [Delete-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/delete-quarantinemessage)
> * [Export-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/export-quarantinemessage)
> * [Get-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/get-quarantinemessage)
> * [Get-QuarantineMessageHeader](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/get-quarantinemessageheader)
> * [Preview-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/preview-quarantinemessage)
> * [Release-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/release-quarantinemessage)

Since the powershell cmdlets are now REST based, is there documentation to use them if i did not want to use powershell and want to hit the endpoints directly?

**Comment by chrisda** [comment]
@mayerlench, I don't think so. Currently, there's no direct access to a REST API for those cmdlets. That doesn't mean it can't or won't in the future.

**Comment by mayerlench** [comment]
> @mayerlench, I don't think so. Currently, there's no direct access to a REST API for those cmdlets. That doesn't mean it can't or won't in the future.

Got it.

Could I technically get everything I need by using EWS apis?

**Comment by chrisda** [comment]
@mayerlench, I would presume so.

**Comment by alexburner** [comment]
My team is also interested in using the Graph API to access quarantined messages. Or, some sort of HTTP API — we're running this tool on a linux machine and would prefer to avoid PowerShell.

Here I am looking around 3 years later, and I'm not able to find documentation on EWS API endpoints or REST API access for the [aforementioned](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1527#issuecomment-606738660) PowerShell cmdlets.

Am I not looking hard enough, or is PowerShell still the only way to access quarantined message data?

@chrisda you seem to be the one to ask, but I know that may have changed in the 1,246 days since your last comment 🙂

**Comment by chrisda** [comment]
@alexburner, checking.

**Comment by alexburner** [comment]
Thank you @chrisda! Any updates on this?

**Comment by chrisda** [comment]
Not yet.

**Comment by sburner** [comment]
+1, it would save me a lot of time if this Graph API could access quarantined messages.

**Comment by vvidovic-croz** [comment]
+1

**Comment by alexburner** [comment]
@chrisda any update on this? Is there somewhere else we should be making these requests?

**Comment by chrisda** [comment]
@alexburner, nothing to report. Your best option is to open a support ticket and ask.
