### ISSUE TITLE
Can users specify expiry?

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/microsoft-365-docs#1528]
Is the expiry only available by PowerShell or does it respect message options chosen by user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5f55d9b-ad37-ff15-45c2-69287ff07b98
* Version Independent ID: d5a29d2f-8696-a089-93ae-42a12f656e3b
* Content: [Set an expiration date for email encrypted by Office 365 Advanced Message Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-advanced-expiration?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-advanced-expiration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-advanced-expiration.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by get-itips** [comment]
Hello @NickDorak do you refer to the "Expires after" message option, when, for example, sending an email thru Outlook client?

If that is the case, that expiration works differently to this one, on the OME case:

> The ExternalMailExpiryInDays parameter specifies the number of days that the encrypted message is available to external recipients in the Microsoft 365 portal

At the end of that time, the encrypted message will not be available.

And the Expires after option:

> When the expiration date passes, the message remains visible in the message list with a strikethrough. It can still be opened, but the strikethrough gives a visual clue that the message is out of date or no longer relevant.
[Source](https://support.microsoft.com/en-us/office/set-a-message-expiration-date-fcae213f-8d38-4318-a17b-42d83ac209ed?ui=en-us&rs=en-us&ad=us)

Hope this information helps you.

**Comment by mypil** [comment]
@NickDorak - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
