### ISSUE TITLE
What's new information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1530]
Please provide a what's new change log so that can easily learn when new services and activities are added to the log. For example, Microsoft Teams Healthcare activities was added, but I did not know this and I cannot tell when it happened.
Also, there should be messages posted in the O365 Message Center when these changes occur.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#microsoft-teams-healthcare-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@DeanGross Any substantial new additions to auditing activities are cited in this topic: https://docs.microsoft.com/en-us/microsoft-365/compliance/recently-updated-topics-mcc?view=o365-worldwide (btw, these healthcare activities were added in Oct. 2019). For MC posts, please give product feedback with this suggestion.
