### ISSUE TITLE
Only Works for Some Users

### ISSUE THREAD

**Issue by MarkInPA13** [MicrosoftDocs/microsoft-365-docs#1532]
The scripts appears to work for some of my users but other users still have the ability to create groups within the Teams app.  I reran the script and it definitely displays EnableGroupCreation = False on the last line.  I am unsure why it only partially works in my environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create Office 365 Groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@MarkInPA13 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by wingers999** [comment]
@MarkInPA13 - did you ever get this resolved as I am facing exactly the same problem?

**Comment by MarkInPA13** [comment]
> @MarkInPA13 - did you ever get this resolved as I am facing exactly the same problem?
I did not resolve the issue.

**Comment by wingers999** [comment]
Okay thanks for replying, can I ask did you contact Microsoft Support via service ticket or not?

**Comment by MarkInPA13** [comment]
@wingers999 - I did not.  I try to avoid that 5th ring of hell unless it is something absolutely critical.

**Comment by wingers999** [comment]
fair enough, I will give it a try and report back here if any success
