### ISSUE TITLE
AzureADPreview now uses different object property names

### ISSUE THREAD

**Issue by michalrok** [MicrosoftDocs/microsoft-365-docs#1535]
Same script but updated to new property names, and now matching security group by exact match not substring:
```PowerShell
$GroupName = "<your group name here>"
$AllowGroupCreation = "False"

Connect-AzureAD

$settingsObjectID = (Get-AzureADDirectorySetting | Where-object -Property DisplayName -Value "Group.Unified" -EQ).Id
if(!$settingsObjectID)
{
	  $template = Get-AzureADDirectorySettingTemplate | Where-object {$_.displayname -eq "Group.Unified"}
    $settingsCopy = $template.CreateDirectorySetting()
    New-AzureADDirectorySetting -DirectorySetting $settingsCopy
    $settingsObjectID = (Get-AzureADDirectorySetting | Where-object -Property DisplayName -Value "Group.Unified" -EQ).Id
}

$settingsCopy = Get-AzureADDirectorySetting -ObjectId $settingsObjectID
$settingsCopy["EnableGroupCreation"] = $AllowGroupCreation

if($GroupName)
{
	$settingsCopy["GroupCreationAllowedGroupId"] = (Get-AzureADGroup |Where-Object -Property DisplayName -EQ $GroupName).ObjectId
}
 else {
$settingsCopy["GroupCreationAllowedGroupId"] = $GroupName
}
Set-AzureADDirectorySetting -ObjectId $settingsObjectID -DirectorySetting $settingsCopy

(Get-AzureADDirectorySetting -ObjectId $settingsObjectID).Values
```

**Comment by mypil** [comment]
@michalrok - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by michalrok** [comment]
https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

**Comment by get-itips** [comment]
Hello @michalrok Michal, Can you specify please the version of the AzureADPreview module that you are using?
I am using 2.0.2.89, which appears to be the [last one](https://www.powershellgallery.com/packages/AzureADPreview), and there is no ObjectId parameter in Get-AzureADDirectorySetting

**Comment by mypil** [comment]
@michalrok - Can you please respond to the query of get-itips?


Thank you.

**Comment by mypil** [comment]
@michalrok - We appreciate any feedback you can provide to make the content in the Microsoft docs better. However, we did not get any response from you so we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!
