### ISSUE TITLE
What about M365 A3/A5 SKU for Education ?

### ISSUE THREAD

**Issue by amitpawar74** [MicrosoftDocs/microsoft-365-docs#1536]
The article only mentions Enterprise SKUs of M365. Lots of schools would love to use this policy with their academic licensing.

**Comment by mypil** [comment]
@amitpawar74 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by amitpawar74** [comment]
This is in reference to https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-case-study?view=o365-worldwide

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mypil** [comment]
@amitpawar74 - Thank you for this inquiry.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@robmazz - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by amitpawar74** [comment]
Adding my work email.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by robmazz** [comment]
@amitpawar74 - thanks for the feedback, we've recently updated this topic and the "Get Started with communication compliance" topics with new licensing guidance. Here's a link (https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-case-study?view=o365-worldwide#licensing) to the section you've referenced in this issue.
