### ISSUE TITLE
What PS Cmdlets should we use

### ISSUE THREAD

**Issue by noopman** [MicrosoftDocs/microsoft-365-docs#1537]
This page does not give any indication how to install the PS Cmdlets that we need to run the commands. I would of course have the correct version of things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52c6916-7e79-9a9c-b7a6-47041ddb81e3
* Version Independent ID: 43c9b873-d354-d814-3065-1e8832361b86
* Content: [Set an individual user's password to never expire - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by get-itips** [comment]
Hello @noopman Magnus 👍 how are you? I am proposing adding that info to the article thru a PR, if it gets approval, it will be reflected on the online version of the article. Thanks

**Comment by noopman** [comment]
Thank you, I'm good, in these times and all! I will gladly review the changes for you when they are through the process. Thanks for taking care of this! Hope you are good too!
