### ISSUE TITLE
Block Clarification

### ISSUE THREAD

**Issue by FrankMcGovern** [MicrosoftDocs/microsoft-365-docs#1539]
It would be beneficial to have on the documentation if "Actively block the email or file sharing from taking place" being enabled in the DLP policy means that encrypted emails or files would also be blocked. If so, how is Microsoft seeing the encrypted contents?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36344d-67bf-68cb-5004-9ac6f27ebf51
* Version Independent ID: 89a7d7e7-c643-eb06-d844-b97b80633b68
* Content: [Create, test, and tune a DLP policy - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/create-test-tune-dlp-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
HI @FrankMcGovern  Thanks for your question. Microsoft DLP will search the unencrypted meta data of the items, but not the encrypted contents.  See: https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#considerations-for-encrypted-content

Thanks

Chris
