### ISSUE TITLE
This script doesn't create the WIN10 vm.  Standard_A2_v2 is not available in specified location

### ISSUE THREAD

**Issue by cloudcrazie** [MicrosoftDocs/microsoft-365-docs#1541]

**Comment by mypil** [comment]
@cloudcrazie - Can you please share what specific issue you have and may we know which Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. Thank you.

**Comment by cloudcrazie** [comment]
I am getting error message saying Win 10 standard A2v2 is not available in West US.

[cid:278f4659-02af-4d2c-981f-4f4e880a6119]
________________________________

**Comment by mypil** [comment]
@cloudcrazie - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
