### ISSUE TITLE
What PIM Role to perform action??

### ISSUE THREAD

**Issue by GlennMillerNZ** [MicrosoftDocs/microsoft-365-docs#1542]
Can you please advise and update this article to advise what Privileged Identity roles we need to perform this action?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d49db57-a705-20aa-e98d-5b3d6bbbf9fd
* Version Independent ID: 5a056f2c-03c9-7a34-3196-8bfb1039f6a5
* Content: [Restore a deleted Office 365 group - Microsoft 365 admin](https://docs.microsoft.com/en-au/microsoft-365/admin/create-groups/restore-deleted-group?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/restore-deleted-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/restore-deleted-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@GlennMillerNZ Thank you for the feedback. You need to be a Global Administrator or a group administrator to be able to restore a group. This holds good for PIM roles as well. I have updated the document to reflect the same.

PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1609

Thanks
Sriraman

**Comment by mypil** [comment]
@GlennMillerNZ - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/59be220ed5cc97fe857445e8ae0af62bbfb7c496. 


Thank you for your contribution to make the docs better! Much appreciated!
