### ISSUE TITLE
Does ATP require Office 365 Business apps or ProPlus? or can it work with Office 365 Home apps?

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/microsoft-365-docs#1544]
My customer has Office 365 Business Essentials + ATP, they use Office 365 Home apps because they already purchased them before moving full cloud.  Does ATP require Office 365 Business or ProPlus? or can it work with Office 365 Home apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f4d9231-3dae-4719-7728-c212b6f72fec
* Version Independent ID: fb84d1b6-b388-553f-c707-baa06c78e072
* Content: [Office 365 ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-links?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/atp-safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-safe-links.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@AndySanchezVM Thank you for your feedback. ATP safe links require office 365 Business or Office 365 pro plus editions. It does not work with Office 365 Home.

For more information, you can visit:- https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-atp-safe-links-works?view=o365-worldwide#how-atp-safe-links-works-with-urls-in-office-documents

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@AndySanchezVM - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
