### ISSUE TITLE
To learn more about which resources are created for each group, visit Learn about Office 365 Groups.

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/microsoft-365-docs#1545]
Under 'Technical Architecture'
[The linked article](https://support.office.com/article/learn-about-office-365-groups-b565caa1-5c40-40ef-9915-60fdb2d97fa2) does not make clear: Which resources are created for each group.

The linked article has some description for Yammer/Outlook, mentions teams, but for some reason in much less detail, and no mention of Power BI.

There should be a definitive list/table that shows/explains every resource that the various Office 365 groups create.

Here are my unanswered questions that I thought this document should answer:
What resources are created when I create an Office 365 group in the Admin portal?
What resources are created when I create an Office 365 group from Teams?
What resources are created when I create an Office 365 group from Power BI?
If users create a plan in Planner, does it now automatically create other resources?
If users create a SharePoint site, does it now automatically create other resources?
Is there a way to disable automatic creation of these extra resources ?

Maybe this stuff is documented somewhere and I need to find a better table of contents/search page?

Everyone thinks... no big deal... let users make a mess and create as many resources as they want...
But guess what? Microsoft doesn't back up your data, so we pay for Veeam to do that...
Well, when users create extra unnecessary data, we now have to pay to back that up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9820974-822d-0ae2-9163-b09a4f9536ea
* Version Independent ID: 43b83cfa-3f1d-4feb-0242-0ba3d275f553
* Content: [Plan for Office 365 Groups governance - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/plan-for-groups-governance?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/Plan-for-groups-governance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/Plan-for-groups-governance.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @Krytical13 we are looking into this. Thanks

**Comment by MikePlumleyMSFT** [comment]
@Krytical13 you can find some of this information in the [Groups in Microsoft 365](https://docs.microsoft.com/Office365/Enterprise/microsoft-cloud-it-architecture-resources#groups-in-microsoft-365-for-it-architects) architecture poster. We are working on additional updates in this area.

**Comment by get-itips** [comment]
Thanks @MikePlumleyMSFT 
@Krytical13 I hope the information shared by Mike is the information you were looking for.

**Comment by Krytical13** [comment]
That PDF definitely helps and provides enough information for us to inform our service desk and admins properly!
Thank you very much!

**Comment by mypil** [comment]
@Krytical13 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MikePlumleyMSFT and @get-itips so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
