### ISSUE TITLE
Typo in table

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#1548]
In the last entry 2nd column (effect) for "Apply the above selection if malware scanning for attachments times out or error occurs, there is a typo. it reads

"Applies the action configured for unasfe attachments to the attachments that cannot be scanned (due to time out or error)"

and should read

"Applies the action configured for unsafe attachments to the attachments that cannot be scanned (due to time out or error)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be929ba-8bef-b75c-0475-041bb6ec441a
* Version Independent ID: 358f9e1a-1900-7c8c-814a-b878a9a22f9e
* Content: [Set up Office 365 ATP Safe Attachments policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@pjrcdf - Thank you for pointing this out.

PR #1556  has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
