### ISSUE TITLE
Vague wording

### ISSUE THREAD

**Issue by Robright** [MicrosoftDocs/microsoft-365-docs#1549]
"The Recycle Bin is not used and therefore searches do not find content there. This means that an eDiscovery hold can't locate any content in the Recycle Bin to hold it."

I'd suggest this should read something like: "The Recycle Bin is not indexed and therefore unavailable for searching. Thus, an eDiscovery search can't find any Recycle Bin content on which to place a hold."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Robright  Thanks for your feedback!  Investigating.

**Comment by cabailey** [comment]
This change is now incorporated - thanks for taking the time to improve the docs.
