### ISSUE TITLE
Word must appears twice

### ISSUE THREAD

**Issue by DevJonBirkett** [MicrosoftDocs/microsoft-365-docs#1550]
Priority/impact: Minor
**Section**
https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure?view=o365-worldwide#before-you-begin

The word "must" appears in the sentence following the list of licenses. 
Eg.
"Users included in communication compliance policies must must be assigned one of the licenses above."

**Comment by mypil** [comment]
@DevJonBirkett - Thank you for pointing this out.

PR #1555 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
