### ISSUE TITLE
Bypass Spam Filtering Rule Working -- Messages Still Ending Up In Quarantine

### ISSUE THREAD

**Issue by philkloose** [MicrosoftDocs/microsoft-365-docs#1553]
I've implemented the mail flow rule as described in this article and I still have messages that end up in the user's hosted quarantine.  I know the rule is working because I can see the custom X-Header and the SCL=-1 in a message trace, but then something further along the pipeline seems to be making the determination that it is indeed spam and applies an SCL=6 (or greater).  I was under the impression that the SCL=-1 should remove all future spam consideration and deliver the message to the user's mailbox.  If there is something else that might factor into this spam assessment, please add it to the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adafa10b-c26d-a4d5-b240-b569079d64d4
* Version Independent ID: cce238a6-384d-9da0-1f13-f9f6ea44ac9e
* Content: [Create safe sender lists in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by philkloose** [comment]
I know this isn't tech support, and I've already contacted them, but I'm expecting to have something of significance to add to this article by the time I finish troubleshooting this issue.  It seems that "Modify the message properties > set the spam confidence level (SCL) > Bypass spam filtering" action is simply adding another "SCL=" value and there is already an "scl=" value there.  Is that the expected behavior?  Is it a case-sensitivity issue?

**Comment by get-itips** [comment]
Hello @philkloose How are you? 👍  Hope you are doing good.

I wanted to test this to see if we need to impact the documentation somehow, to reproduce this can be difficult, however, I verified that the SCL was applied correctly, but in my case, the message was correctly bypassed.
I know that the article currently mentions that the allowed sender list should be used as a last resource, but wanted to check if you tried it in the process to see if you got a different result.

@chrisda Chris, currently, the mail flow UI is proposing not to use a mail flow and use an allow or block list in the spam filter:

![image](https://user-images.githubusercontent.com/36666927/80024415-682dcb00-84b5-11ea-9f19-ba30bcfb52ed.png)

Do you think we should change the article to comply with this? Thank you

**Comment by chrisda** [comment]
I don't think so. That 'allow or block list in the spam filter' link takes you to the EAC version of anti-spam policies, which is going away in favor of the [anti-spam policies in the SCC](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-your-spam-filter-policies).

Furthermore, the whole point of this "Create safe sender lists" topic is that a mail flow rule is preferred over using anti-spam policies.

**Comment by get-itips** [comment]
> I don't think so. That 'allow or block list in the spam filter' link takes you to the EAC version of anti-spam policies, which is going away in favor of the [anti-spam policies in the SCC](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-your-spam-filter-policies).
> 
> Furthermore, the whole point of this "Create safe sender lists" topic is that a mail flow rule is preferred over using anti-spam policies.

Understood, thanks @chrisda

**Comment by get-itips** [comment]
Hello @philkloose How are you? 👍 hope you are doing good.

Wanted to know if you have any news about the described issue, as I could not reproduce the issue to see if we have to make changes to the article, and I hope that the information shared by @chrisda was useful to you, other than that, I would recommend continuing with Support Services if you still can not bypass spam filtering by using this method.
Thanks

**Comment by philkloose** [comment]
I _think_ what I learned is that the the user's personal Blocked Senders list maintained in Outlook was confusing matters.  The doubled-up SCL values (scl= & SCL=) were only visible when I viewed the intermediate steps in a Message Trace.  By the time the message had been delivered (or not) to the user's mailbox, the headers did not show both values.  I didn't realize that the user's Blocked/Trusted senders list would override in this manner.  I figured that it wouldn't bother modifying the SCL values, and would simply take action on the message, but this appears to be wrong.

**Comment by get-itips** [comment]
Hello @philkloose 
Thanks for getting back and sharing your last feedback. Will dig into the documentation to see if that override by Outlook is documented somewhere.
Thanks

**Comment by get-itips** [comment]
> I _think_ what I learned is that the the user's personal Blocked Senders list maintained in Outlook was confusing matters. The doubled-up SCL values (scl= & SCL=) were only visible when I viewed the intermediate steps in a Message Trace. By the time the message had been delivered (or not) to the user's mailbox, the headers did not show both values. I didn't realize that the user's Blocked/Trusted senders list would override in this manner. I figured that it wouldn't bother modifying the SCL values, and would simply take action on the message, but this appears to be wrong.

Ok you probably have SFV:BLK header on that email message, even though you have configured the mail flow rule to bypass the spam filtering, the message is going to be blocked because 

> it was sent from an address in a user's Outlook Blocked Senders

Source : https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide

Hope this information helps closing this issue.

**Comment by mypil** [comment]
@philkloose - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @chrisda and @get-itips  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by RNalivaika** [comment]
@chrisda I think your comment makes no sense. If the link is to something outdated, just get it removed. Reference to an outgoing feature should be removed. Also, the text suggests using an unsecure method of "safelisting" and should absolutely be removed to not confuse, not learn users/admins insecure practices and not to contradict documentation. This should be checked by somebody else.
