### ISSUE TITLE
Architect

### ISSUE THREAD

**Issue by GeorgeChiuTheHartford** [MicrosoftDocs/microsoft-365-docs#1560]
It is not clear with either(1) E3 that customer lockbox feature is not available or (2) with customer lockbox feature available with E5 but the "require approval" switch is off that Microsoft support can access customer data without customer knowledge or not.  Please clarify

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Office 365 Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
Hi! Thanks for your question. We just posted a new Microsoft 365 licensing guidance for security & compliance. Let me know if you still have questions about E3 and E5 availability for Customer Lockbox.

**Comment by GeorgeChiuTheHartford** [comment]
All set, thanks!
