### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by sheriltx** [MicrosoftDocs/microsoft-365-docs#1561]
I need my Password reset because I tried 3 times.  This crazy but I cant get any number to accept my call. 

I am desperate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d29992b-3923-dee5-80ce-d2f6d742a22d
* Version Independent ID: 69b84bff-490f-7e75-51fd-b1f0e77dc247
* Content: [Assign admin roles the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/assign-admin-roles?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/assign-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/assign-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@sheriltx - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
