### ISSUE TITLE
Error in "Move from baseline policies to security defaults" instructions

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/microsoft-365-docs#1562]
In step 2 of the instructions in the "Move from baseline policies to security defaults" section, it says: "Next to Sign-in and security, under Make sign-in more secure, select View." However, there is no "Make sign-in more secure" section. I had to navigate to Azure Active Directory &gt; Security &gt; Conditional Access to turn off the Baseline policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for Office 365 users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#move-from-baseline-policies-to-security-defaults)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by rgsteele** [comment]
Update: I also had to disable the policies at the link mentioned in this comment on another GitHub issue: https://github.com/MicrosoftDocs/azure-docs/issues/43961#issuecomment-575595868

**Comment by Sirkkuw** [comment]
@rgsteele  - you are correct. this has been changed. I will update the doc.

**Comment by Sirkkuw** [comment]
@rgsteele fixed now
