### ISSUE TITLE
Unable to use Microsoft 365 Admin app to manage tenant

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/microsoft-365-docs#1563]
Hi,

I have two Microsoft 365 tenants that I manage. I am able to log into the Microsoft 365 app for one of these perfectly well using version 3.62.0 of the app and iOS 13.4.

However I have never been able to log into the second tenant successfully. I enter my username, am prompted for my password, then the app 'hangs' with a white screen and the small 'flower' circle going round and round forever. I would expect to receive an MFA prompt at this point, but it never appears. I have tried removing and reinstalling the app and it still doesn't work (although it always works for the 'other' tenant). Therefore I cannot use the app to manage this tenant.

The only difference I can think of that might be relevant for the tenant that does not work is that I enforce MFA using Conditional Access, with a bypass for devices that are Hybrid Azure AD Joined. This works on nearly every other app and is based on the following guide: https://practical365.com/security/azure-active-directory-conditional-access-enforce-multi-factor-authentication/. The other tenant has MFA enabled using Security Defaults, which do not permit a Hybrid Azure AD Join bypass.

I can only assume that the app pauses because it somehow cannot 'cope' with checking to see if the device is Hybrid Azure AD Joined.

Please test this scenario and fix the app so it works on both my tenants?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce65739-6428-fc57-012c-a6741a051c6b
* Version Independent ID: 3341ac81-3e21-4e71-e4f7-3eff41db05b8
* Content: [About the Microsoft 365 Admin mobile app - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-mobile-app?view=o365-worldwide)
* Content Source: [microsoft-365/admin/admin-overview/admin-mobile-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-mobile-app.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@ChrisAtMAF - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by ChrisAtMAF** [comment]
OK. I thought I could report an issue here, since the article says:

'Email feedback365@microsoft.com to report an issue with the app. Or you can give feedback at the bottom of this article.'
