### ISSUE TITLE
Spoof security features no longer available

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#1564]
In the table for Spoof security feature name there are 2 values noted that are only available via PowerShell.

EnableSuspiciousSafetyTip
TreatSoftPassAsAuthenticated

These parameters are no longer listed in the documentation for the set-antiphishpolicy or new-antiphishpolicy cmdlets and appear to have been deprecated.

Can you please update either this documentation or the documentation for those PowerShell cmdlets to reflect the correct status.

For the record if I do a get-antiphishpolicy in my E5 demo tenant I can see a value set to false for EnableSuspiciousSafetyTip and nothing for TreatSoftPassAsAuthenticated 

If i try and amend the visible value via set-antiphishpolicy I get "A parameter cannot be found that matches parameter name 'EnableSuspiciousSafetyTip'"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Office 365 ATP security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, security baselines, baselines for EOP, baselines for ATP, setup ATP, setup EOP, configure ATP, configure EOP, security configuration - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide#office-365-advanced-threat-protection-security)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by cammurray** [comment]
Hi @pjrcdf 

Both EnableSuspiciousSafetyTip and TreatSoftPassAsAuthenticated have been deprecated. I've submitted a pull request to have the recommended practices article updated to reflect this.

Thanks

**Comment by chrisda** [comment]
Confirmed that values are no longer listed in the topic.

Closing
