### ISSUE TITLE
Operation for user changed password

### ISSUE THREAD

**Issue by ionab10** [MicrosoftDocs/microsoft-365-docs#1572]
According to these documents, "Change user password" indicates that an "Administrator changed the password for a user." How would we find audit logs for a user changing their own password?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#sensitivity-label-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ionab10 Thanks for the question. It looks like the documentation is incorrect. I just tested and the "Changed user password" action will be triggered when a user resets their own password (assuming that users can reset their own passwords, which is configurable in Azure AD). You can also look at the auditing reports in Azure AD to see when a user resets their own password. Here's more info about password auditing/reporting in Azure: https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-sspr-reporting#activity-type-reset-password-self-service

The "Reset user password" action is triggered when an admin resets a user's password. 

I will update this article accordingly.
