### ISSUE TITLE
How about forwarding all mail at a server level?

### ISSUE THREAD

**Issue by pkiula** [MicrosoftDocs/microsoft-365-docs#1575]
It should be possible to forward all mail from this server to a new server. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding in Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@pkiula, you can set up mail forwarding rules for users only in Office 365 (Exchange Online). If you need help with a specific issue with on-premises servers, please [contact support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
