### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by NIxonden1** [MicrosoftDocs/microsoft-365-docs#1577]
I have no idea what all this means - I am no techie!! All I want to do is use Office Business 365 Premium to see my outlook on my devices and to have access to docs as I travel. It should be simple

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758b21fa-24c1-8c68-259f-daac0caf35ae
* Version Independent ID: bce80397-ee03-cacf-55cb-09b169e96e70
* Content: [Find your domain registrar for Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/find-your-domain-registrar?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/get-help-with-domains/find-your-domain-registrar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/find-your-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@NIxonden1 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
