### ISSUE TITLE
Impersonation behaviour when protected domains/users list is empty

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/microsoft-365-docs#1578]
If in the default Anti-Phishing policy you configure the "Action &gt; Domain impersonation" and set it to Quarantine the message, bu t leave the list under "Protect specific domains, include custom domains" empty, what is the expected behaviour? I would expect nothing, but have some hints that if the list is empty *all* non-owned domains are effected, resulting in all email send on behalf of... (for example via mailchimp, surveymonkey or any other mass mailing systems) directly to quarantine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@kennethvs, if **Include custom domains** is **On**, yet the list of domains is empty, I, too, would expect nothing to happen. Do you have evidence to the contrary?

![image](https://user-images.githubusercontent.com/33166947/78928005-b7571300-7a54-11ea-9902-8e084f64a00a.png)

**Comment by mypil** [comment]
@kennethvs - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by chrisda so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by kennethvs** [comment]
Hi All,

Sorry for not answering... we raised a MS Support ticket for this behavior (Case #:19498641) - it seems that the Domain Impersonation filtering was not working as we expected. Let's say for example that you have a domain called survey.nl and receive email from surveymonkey.com - that email is then considered domain impersonation causing it to end up in Quarantine. You should then mark surveymonkey.com as a trusted domain within the same policy. 

Regards,

Kenneth
