### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#1579]
Page currently reads

"Phase 2 is now progress with the following playbooks in public preview, providing recommendations for actions and aiding security administrators in investigating issues:"

Should read

"Phase 2 is now in progress with the following playbooks in public preview, providing recommendations for actions and aiding security administrators in investigating issues:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de70c835-f408-83a6-3cc7-885756bd7152
* Version Independent ID: 076708dd-80e4-39d7-7e23-42730c106900
* Content: [Automated investigation and response (AIR) in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/automated-investigation-response-office?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/automated-investigation-response-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/automated-investigation-response-office.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@pjrcdf thank you so much for catching that. My apologies. It's fixed, and you should see the change render live in a couple of hours.
