### ISSUE TITLE
France Driver's License Number

### ISSUE THREAD

**Issue by SabRom** [MicrosoftDocs/microsoft-365-docs#1580]
Hello,

The France Driver's License Number section seems to be mixed with the previous section (Finland passport number)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [What the sensitive information types look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/what-the-sensitive-information-types-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
HI @SabRom 
Thanks for letting us know, I have fixed the formatting issues and republished the topic.
