### ISSUE TITLE
Requirements for non-O365 recipients

### ISSUE THREAD

**Issue by felgar73** [MicrosoftDocs/microsoft-365-docs#1582]
Can you provide more details on what is required from external, non-O365 recipients (Google, Exch on-prem, etc.) to decrypt or access the OME portal and request the OTP? Is there a specific URL or URLs that are needed to be allowed via firewall such as, "*outlook.office365.com/Encryption/"?
-Thnx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Office 365 Message Encryption FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#what-email-clients-are-supported-to-read-and-reply-to-protected-emails)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by get-itips** [comment]
Hello @felgar73 Felix, how are you?

You are correct, the URL is that one and you can find more information about the process for external users [here](https://support.office.com/en-us/article/How-do-I-open-a-protected-message-1157a286-8ecc-4b1e-ac43-2a608fbf3098?ui=en-US&rs=en-US&ad=US)

Hope this info helps you

**Comment by mypil** [comment]
@felgar73 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by get-itips so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
