### ISSUE TITLE
O365CompatibilityChecker & MFA?

### ISSUE THREAD

**Issue by PiKappZ746** [MicrosoftDocs/microsoft-365-docs#1583]
Are there any plans to update the O365CompatibilityChecker to support MFA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@PiKappZ746 - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by TronPhung** [comment]
I just attempted to use this module and also noticed that MFA is not supported.  It appears to only allow basic authentication.

**Comment by Sirkkuw** [comment]
I am following up with PG.

**Comment by Sirkkuw** [comment]
The answer from the product group is: MFA is not currently supported. 
The plan to implement the support is added to the product backlog pipeline
