### ISSUE TITLE
Removing license

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/microsoft-365-docs#1584]
Can you please explicitly mention in the article what exactly happens when you remove a license, and also clearly state what is a *supported* configuration? For example, if a user has 100GB worth of files in their OneDrive and you choose to convert it to shared mailbox, with only removing the license and not deleting the user account. What will happen to the files, will ODFB still be accessible, can he add/remove files, is this a violation of the license agreement, etc?

The corresponding Onedrive documentation (https://docs.microsoft.com/en-us/onedrive/retention-and-deletion) refers to this article for the above scenario, which is not really explained here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6245943-00b8-c47b-f739-731531d5d357
* Version Independent ID: a9ec7066-ed8c-7b77-1d87-8c50bf74ec6c
* Content: [Delete a user from your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/delete-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/delete-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/delete-a-user.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by get-itips** [comment]
Hello @michevnew Vasil, how are you?
Did the test in my lab, and I still could access the ODFB files, both as an admin and as a user.
However, as I can not mimic 30 days to see what would happen the day after the default retention period, I need to ask @cmcatee-MSFT , Cern can you kindly clarify here? I appreciate.

**Comment by mypil** [comment]
@cmcatee-MSFT - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by cmcatee-MSFT** [comment]
This has been forwarded to the product team. We'll update the documentation when we receive clarification.
