### ISSUE TITLE
Confused about the new policy - 'Applied to settings'

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1586]
From 'Edit your policy', and under 'Policy setting' there is an opportunity to set 'Applied to' as a user and / or Domain. 
However if you click 'Edit' next to Impersonation there is an option to again 'Add users to protect' and 'Add domains to protect' - isn't this the same as I've already supplied under 'Policy setting'? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@challengelogic, I'm in the process of updating these topics, and I understand your confusion.

**Applied to** acts like any other policy where you specify who the settings in the policy apply to: all users in the org, specific individuals, members of a group, etc. Basically, you're defining the message recipients as a condition: If the recipient is one of the **Applied to** and the message is determined to be phishing....

**Impersonation** also known as protected users/domains is yet a different condition that's exclusive to anti-phishing policies that specifies spoofed senders or domains to look for as the message sender (the From address). Think high value targets like executives, admins, compromised accounts in the past, etc. So, the policy becomes: If the spoofed sender of the message is one of the protected users/domains, and if the the recipient is one of the **Applied to** and the message is determined to be phishing...

Does this make sense?

**Comment by mypil** [comment]
@challengelogic  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by chrisda so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
