### ISSUE TITLE
missing step

### ISSUE THREAD

**Issue by TimAbmgf** [MicrosoftDocs/microsoft-365-docs#1588]
within Step 2
Create a new retention policy for mailboxes on hold
under
Use the EAC to create a retention policy
#3 says: Under Retention tags, click Add + Icon.

When you are in Exchange online... there are 3 options when you click Add (that isn't spelled out in this instruction)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e247ee-12d5-add4-756c-b8a8d4ebb7a3
* Version Independent ID: 889ce47a-58f5-7bc1-2343-64dcd4bdac2a
* Content: [Increase the Recoverable Items quota for mailboxes on hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold?view=o365-worldwide#step-1-create-a-custom-retention-tag-for-the-recoverable-items-folder)
* Content Source: [microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@TimAbmgf Please correct me I'm wrong, but it sounds like you are on the **Retention tags** tab in the EAC and not on the **Retention policy** tab in the EAC. The behavior you're describing sounds like your creating a retention tag, but this step in this topic is about creating a retention policy:

In the EAC, go to Compliance management > **Retention policies**, and then click Add Add Icon.

If you've followed the steps in this topic, you've already created the retention tag in Step 1 (and you have to create it in PowerShell; you can't create in the EAC). In Step 2, you are adding that retention tag to a new retention policy. And then in Step 3 you assigned to new retention policy to mailboxes on hold.

Hope this helps.

**Comment by mypil** [comment]
@TimAbmgf - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by markjjo so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by TimAbmgf** [comment]
![image](https://user-images.githubusercontent.com/39526641/91209607-d92dfb00-e6c0-11ea-8f6a-e1aadc6f1a6b.png)
hopefully the screenshot I tried to post shows the 3 items I mentioned

**Comment by TimAbmgf** [comment]
this screenshot shows being in the retention tags section

![image](https://user-images.githubusercontent.com/39526641/91209719-0084c800-e6c1-11ea-869c-a5e559c71c46.png)

**Comment by TimAbmgf** [comment]
> @TimAbmgf Please correct me I'm wrong, but it sounds like you are on the **Retention tags** tab in the EAC and not on the **Retention policy** tab in the EAC. The behavior you're describing sounds like your creating a retention tag, but this step in this topic is about creating a retention policy:
> 
> In the EAC, go to Compliance management > **Retention policies**, and then click Add Add Icon.
> 
> If you've followed the steps in this topic, you've already created the retention tag in Step 1 (and you have to create it in PowerShell; you can't create in the EAC). In Step 2, you are adding that retention tag to a new retention policy. And then in Step 3 you assigned to new retention policy to mailboxes on hold.
> 
> Hope this helps.

I know this item was closed (probably due to my late reply); please see my screenshots.

**Comment by markjjo** [comment]
@TimAbmgf Not sure I recall what your question was but as per previous post, you have to create the retention tag using EXO powershell, as described here: https://docs.microsoft.com/en-us/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold?view=o365-worldwide#step-1-create-a-custom-retention-tag-for-the-recoverable-items-folder

Then you can add the retention tag to the Exchange retention policy. Note that the retention policy and tags discussed in this topic are Exchange MRM retention policies, not that retention polices in the O365/M365 compliance center, which is what the yellow banner in your screenshot refers to.
