### ISSUE TITLE
Content now called files?

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/microsoft-365-docs#1594]
Can you please review the following instruction: " (In the Security & Compliance Center, go to Threat management &gt; Review &gt; Quarantine and filter for Content.)". 
Content seems to be called "Files" now. Can you please doublecheck?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3831737-c7bf-b95c-4b1e-8ff2e5016e9c
* Version Independent ID: 01bd45b3-710e-f396-a2dd-971a97a29d67
* Content: [Office 365 ATP for SharePoint, OneDrive, and Microsoft Teams - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-for-spo-odb-and-teams?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/atp-for-spo-odb-and-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-for-spo-odb-and-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Thanks for noticing and reporting @sebhe

**Comment by get-itips** [comment]
PR has been merged, @mypil you can close this now. Thanks

**Comment by mypil** [comment]
@sebhe - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/d2d1fd120bc356419c8bf4b0b90e3ecae1556ded. 


Thank you for your contribution to make the docs better! Much appreciated!
