### ISSUE TITLE
Cannot delete folders inside the main archive once the archive has auto expanded and an aux archive has been created.

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#1595]
Our documentation says the following:

"You can delete items in a subfolder that points to an auto-expanded storage area, but the folder itself can't be deleted."

This paragraph implies that only folders that have been moved in aux archives or have a copy in an aux archive, can no longer be deleted. In reality, we cannot delete ANY folder which exists in the archive, regardless if it points to an aux archive location or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69e08cf1-3ef1-7d22-122e-ef0f45c26215
* Version Independent ID: e9677dc3-580d-0a66-80ac-30a8aabdd45f
* Content: [Overview of unlimited archiving in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/unlimited-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Alex-Catalin Thanks for the heads up. I'll confirm with engineering and then update the topic accordingly.
