### ISSUE TITLE
Clarity on admin privileges

### ISSUE THREAD

**Issue by v-olduch** [MicrosoftDocs/microsoft-365-docs#1597]
There are a lot of different admin roles and the statement about having admin privileges is not accurate enough. It would be useful to have specific requirements e.g. Global Administrator. Would also be interesting to specify what actions are available to other admin roles (Exchange admin, SharePoint Admin, etc...) if any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce65739-6428-fc57-012c-a6741a051c6b
* Version Independent ID: 3341ac81-3e21-4e71-e4f7-3eff41db05b8
* Content: [About the Microsoft 365 Admin mobile app - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-mobile-app?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/admin/admin-overview/admin-mobile-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-mobile-app.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by get-itips** [comment]
Hello @v-olduch Olivier how are you?
I tested in my lab and I could log in into the app using any of the available admin roles, so I think that the statement _admin privileges_ currently in the article, fits in this case.
The actions available will depend on the type of role that the admin has, for example a _HelpDesk admin_ can reset a password, a _billing admin_ can see the bills, and so on. As features are being added to the app constantly the actions available for each role will increase.
Hope this information helps you.

**Comment by v-olduch** [comment]
Alright, so any admin privilege would work, and the actions available to that specific admin role would be available in the app as well. It would be useful to have a breakdown of the different actions available for each admin roles in the app.

**Comment by get-itips** [comment]
Thanks for the feedback @v-olduch, will pass it along to @pebaum

**Comment by mypil** [comment]
@v-olduch - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
