### ISSUE TITLE
How do you get policy details from a quarantined message?

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/microsoft-365-docs#1598]
We should include details about how to expose the policy details for a particular message. This will help admins troubleshoot which policy applied to a message in quarantine. This is available by modifying the columns in quarantine and choosing to add Policy Name (you have to remove a column to add one as the maximum is seven). An admin can also use the Get-QuarantineMessage PowerShell cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfc15d1-833b-3139-6bc0-1acb97d507c8
* Version Independent ID: 31e24618-c2e6-4fe4-9651-04d6007548a4
* Content: [Find and release quarantined messages as a user in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. Note added.

Thanks for the feedback. @kellybos, in the future, you, too can add information like this directly to the topic; no need to file a GitHub issue first. For instructions (works for any repo), see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Closing
