### ISSUE TITLE
Bluehost Mail Entries

### ISSUE THREAD

**Issue by acynch** [MicrosoftDocs/microsoft-365-docs#1600]
What about pop, imap, smtp, webmail, and other CNAME entries that Bluehost included in the dns entries that along with an A record for mail.@ point back their hosting server. I'm guessing these should all either be removed or directed back towards outlook.com, office.com, or some other MS site.

It would be helpful if this article addressed those entries. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d9b2b9-5fbf-0ecd-13f4-0de1613ca854
* Version Independent ID: ccfb9be8-b68a-e7a6-ddd6-18244005a090
* Content: [Create DNS records at Bluehost for Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-bluehost?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-bluehost.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-bluehost.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by ScottStauffer** [comment]
Yes, Please... Guidance... seeing these as well and now I am wondering...

**Comment by get-itips** [comment]
Hello @acynch How are you?
From my understanding, in this scenario, the records you mention, included by BlueHost are not required, as the required entries for Office 365 are already being taken care of.
I would like to invite the article's designated author @pebaum Peter, can you kindly confirm? Thanks

**Comment by acynch** [comment]
Would love to have confirmation from @pebaum, but I went ahead and deleted those entries after the migration to bluehost and everything appears to be working correctly as far as I can tell.
