### ISSUE TITLE
'Configure policies' option missing

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1602]
In STEP 3: "Select Configure policies and select Add a policy." - In my 
Microsoft 365 admin center I do not have a 'Configure policies' option available to select... only a +New Request button (which is for use in STEP 4, item no. 4). I am using a M365 E5 Trial licence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bf337ec-3242-44b9-328b-7ca6381a2bcf
* Version Independent ID: eda3540f-7049-ad17-a259-7952e5665983
* Content: [Get started with privileged access management - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/privileged-access-management-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/privileged-access-management-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/privileged-access-management-configuration.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by challengelogic** [comment]
Please ignore the above, screen sized hid the option. I do have it!

**Comment by mypil** [comment]
@challengelogic - Thank you for submitting feedback.

Based on your last comment, our understanding is that there is no issue anymore so we will close this issue.

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.
