### ISSUE TITLE
Is this page applicable to the Data Security Protection Toolkit - Replacement to IG Tookit?

### ISSUE THREAD

**Issue by tcranston** [MicrosoftDocs/microsoft-365-docs#1603]
Hi, 

With the new Data Protection act adn successful implementation of the Data Security Protection Toolkit (DSPT) the Information Governance Toolkit (IGT) is being decomissioned (https://www.igt.hscic.gov.uk/).
Is this page & content relevant for DSPT?

Thanks

Tim

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158e4486-8514-5e04-b343-9e509a91ccd6
* Version Independent ID: a8c4c6d7-3ed2-f722-3f5c-8fb20e55abd8
* Content: [National Health Service (NHS) Information Governance (IG) Toolkit - Microsoft Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/offering-nhs-ig-toolkit-uk?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-NHS-IG-Toolkit-UK.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-NHS-IG-Toolkit-UK.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by get-itips** [comment]
Hello @robmazz Robert, how are you? Can you step in to clarify @tcranston inquiry? Thank you

**Comment by mypil** [comment]
@robmazz - Can you please share your insights on this issue?

Thank you,

cc: @kenwith

**Comment by robmazz** [comment]
@tcranston and @get-itips - thanks so much for the feedback. This offering topic definitely requires updating and I will make sure it is updated for the the new Data Security and Protection Toolkit rollout and the decommissioning of the Information Governance Toolkit. Please check back on this topic in the coming weeks for the new updates!
