### ISSUE TITLE
Fix link

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/microsoft-365-docs#1607]
The link in this paragraph:

"If you want to prevent your users from recycling old passwords, you can do so in Azure AD. See Set the password expiration policy for your organization."

points back to THIS article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@michevnew - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/93742d067830cc73dab23a1e272d792bdef6b378. 


Thank you for your contribution to make the docs better! Much appreciated!
