### ISSUE TITLE
Settings -> Setup

### ISSUE THREAD

**Issue by eino-makitalo** [MicrosoftDocs/microsoft-365-docs#1610]
Wrong instructions ... its Setup -&gt; Domains   not Settings -&gt; Domain in my  UI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0302478-af73-742b-a7d2-536375b92986
* Version Independent ID: 30f173d3-559b-85fc-6bdd-eb4fcf59d183
* Content: [Add or edit custom DNS records in Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/add-or-edit-custom-dns-records?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/dns/add-or-edit-custom-dns-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/add-or-edit-custom-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@eino-makitalo - Thank you for submitting feedback.  

PR #1659  has been created by @D3Design to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
