### ISSUE TITLE
This implies you should turn off audit logging if you're using a 3rd party SIEM 

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/microsoft-365-docs#1611]
Not sure its a good idea to imply turning off Audit Logging here, as it could be used for backup and is a prerequisite for using the O365 Activity Management API
https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn Office 365 audit log search on or off - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide&viewFallbackFrom=o365-worldwide%C2%A0)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jebalert Thanks for pointing this out. I'll add a note or otherwise address this.
