### ISSUE TITLE
Undocumented constraints for Import File

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#1615]
There are constraints on the import process that are neither documented here nor enforces when entering data manually in the browser:

Microsoft.Exchange.Management.Transport.ErrorParsingCSVException: Validation failed in the provided CSV at row 1 column "Notes". Error: Name: The length of the property is too long. The maximum length is 64 and the length of the value provided is 93.
Microsoft.Exchange.Management.Transport.ErrorParsingCSVException: Validation failed in the provided CSV at row 2 column "Notes". Error: Name: The length of the property is too long. The maximum length is 64 and the length of the value provided is 94.
Microsoft.Exchange.Management.Transport.ErrorParsingCSVException: Validation failed in the provided CSV at row 3 column "Comment". Error: Name: The length of the property is too long. The maximum length is 64 and the length of the value provided is 66.
Microsoft.Exchange.Management.Transport.ErrorParsingCSVException: Validation failed in the provided CSV at row 3 column "Notes". Error: Name: The length of the property is too long. The maximum length is 64 and the length of the value provided is 94.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Overview of file plan manager - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/file-plan-manager?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Thank you for this feedback.  Yes, on investigation, each string has a maximum of 64 characters for import. I'm adding this clarification into the documentation and if this limit is too low for you, I encourage you to post to UserVoice, in the data governance and records management category: https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=379531
