### ISSUE TITLE
XML Namespaces wrong in examples

### ISSUE THREAD

**Issue by bjdekker** [MicrosoftDocs/microsoft-365-docs#1620]
In the Body example parameter below **Sample code to call the REST API** the following example XML is written:
```xml
&lt;entry xmlns:d='https://schemas.microsoft.com/ado/2007/08/dataservices' xmlns:m='https://schemas.microsoft.com/ado/2007/08/dataservices/metadata' xmlns='https://www.w3.org/2005/Atom'&gt;
&lt;category scheme='https://schemas.microsoft.com/ado/2007/08/dataservices/scheme' term='Exchange.ComplianceRetentionEvent' /&gt;
```

All the namespaces are prefixed with http**s** shouldn't this be http?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e242e00-9737-43c0-eded-821faaa889cd
* Version Independent ID: 1a354075-9994-1dc6-ac43-006dbac0add8
* Content: [Automate event-driven retention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/automate-event-driven-retention?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/automate-event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/automate-event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bjdekker It seems these got accidentally updated as a result of a script.  Thanks for flagging, I'll revert to http.

**Comment by cabailey** [comment]
Fixed now, closing.

**Comment by bloodytourists** [comment]
I fell foul of the same issue, before I read this closed comment. The examples above still reference https intead of http. Changing these to http resolved my issue. Thanks

**Comment by cabailey** [comment]
@bloodytourists  Apologies - seems somebody with good intentions reverted the change.  I'll look into it.
