### ISSUE TITLE
There is no option to export CSV

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/microsoft-365-docs#1622]
## Problem

This page includes the following statement:

> **Export message results**
> 1. Select the messages you're interested in, and click Export results.
> 2. Click Yes in the confirmation message that warns you to keep the browser window open.
> 3. When your export is ready, you can name and choose the download location for the .csv file.

However, it looks like the [quarantine page](https://protection.office.com/quarantine) does not have the option to export CSV both for a single item action and bulk item actions. 

![image](https://user-images.githubusercontent.com/6519947/79224848-c5fb5b00-7e96-11ea-8324-f8504b9bc928.png)
**Fig. 1  Single item action**

![image](https://user-images.githubusercontent.com/6519947/79225011-0d81e700-7e97-11ea-9b51-b22aefaff14c.png)
**Fig. 2  Bulk item actions**

## Proposal

The section about CSV export should be removed from the document if it is doc bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7325da5e-3116-025e-7ae8-f8dc837897bf
* Version Independent ID: 313221de-4f12-3b21-4a1c-0bdd3d3cb1d2
* Content: [Manage quarantined messages and files as an admin in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hishikitetsuya, your screenshots are accurate, but they are from the EMAIL area of quarantine. The section that talks about exporting files is from the FILES area, which is only available in ATP for files in SharePoint/OneDrive/Teams:

https://docs.microsoft.com/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files#atp-only-use-the-security--compliance-center-to-manage-quarantined-files

![image](https://user-images.githubusercontent.com/33166947/79250798-15f50600-7e34-11ea-9c41-b53d8130f213.png)

**Comment by hishikitetsuya** [comment]
@chrisda  I am sorry for my carelessness check...  I understand the doc is correct so close the issue now. Thanks a lot.
