### ISSUE TITLE
Deploying report message globally shows up only in Outlooks.

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/microsoft-365-docs#1623]
Hi,

When installing report message add-in individually from the portal I can see addin in Outlook as well as on my android, however, when deploying from the Office admin portal - I get i only on Outlook on Windows not in Android. Is this behaviour expected? I've seen  this however when deployed directly from the store on my account.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@zaicnupagadi, I've been told that behavior is by design. You can file a support case, which can (might) help accelerate fixing the issue.

Thanks for the feedback.

Closing.

**Comment by shamst** [comment]
Hi, 

I was trying to use report messages add-in via outlook client 2016 but couldn't find the add-in in the client application.

I am able to see the report messages add-in in office 365 web app but most of our users use only outlook client app. 
Any suggestion of help would me much appreciated.
