### ISSUE TITLE
email forwarding in Microsoft 365 admin center vs Exchange Admin Center

### ISSUE THREAD

**Issue by nat1on** [MicrosoftDocs/microsoft-365-docs#1624]
What are the differences between settings up email forwarding in Microsoft 365 admin center vs Exchange Admin Center(https://docs.microsoft.com/en-us/Exchange/recipients/user-mailboxes/email-forwarding?view=exchserver-2019)?
Which one is preferred?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding in Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
Hi @nat1on, the article you linked to is for Exchange Server 2019. [This article for Exchange Online](https://docs.microsoft.com/en-us/Exchange/recipients-in-exchange-online/manage-user-mailboxes/configure-email-forwarding) is similar, but also clearly states that if you're using Office 365, you should use the Microsoft 365 admin center to configure email forwarding. The main reason for this is that the Microsoft 365 admin center is much easier to user and is much more user-friendly. Hope that helps.
