### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1626]
Whilst this document is great at describing how to form a query, its is not clear 'where' I would input the query. The 'run a Content Search' link doesn't explain how I would input my constructed query, it seems to ask for Keywords to search for instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93feab55-7743-09da-9883-ca3bb10b2181
* Version Independent ID: 5893dfec-d7dd-767d-4a31-2b941363acad
* Content: [Form a query to find sensitive data stored on sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/form-a-query-to-find-sensitive-data-stored-on-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/form-a-query-to-find-sensitive-data-stored-on-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/form-a-query-to-find-sensitive-data-stored-on-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by get-itips** [comment]
Hello @challengelogic 
The query you form is _Keyword Query Language (KQL)_ and yes, as you suspected, you have to input it in the Keywords Textbox when you run a Context Search.

![image](https://user-images.githubusercontent.com/36666927/81614369-59507f00-93b6-11ea-8700-116e1ff87f5e.png)

Hope this clarifies it to you.

**Comment by mypil** [comment]
@challengelogic - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
