### ISSUE TITLE
impact of changing duration of retention label

### ISSUE THREAD

**Issue by rstraker** [MicrosoftDocs/microsoft-365-docs#1630]
There is no information about changing the duration of a retention period of a retention label and the impact on items that already have the label applied, including those that are now records and cannot have a different label applied.  If the policy is 5 years and needs to be changed to 7 years will this automatically update the items that already have the label applied?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@rstraker  Thank you for your question - it's a very good one and I'll make this is covered in the docs going forward.  Yes, if you change the retention period it does automatically change for the content that's already labeled or identified by a retention policy and the new retention period will be adjusted the next time the retention job runs (between 1 and 7 days).  For a retention label that declares content a record, you can extend the retention time (but you can't make it shorter).

If you have existing content that is already labeled and for this content, you want to keep the old retention period and only new content should have the longer retention period - then create a new label with the longer retention period and unpublish the old retention label.

**Comment by rstraker** [comment]
Carol,

I have found one difference and that is with Retention Labels that have the retention based on when the label was applied instead of Created or last modified.
If the label Retain or Delete Content based on, field is set to ‘when it was labeled’ the duration cannot be changed.  This message is displayed under the duration.  Labels based on when the item was labeled can't have their duration modified.

Bob

**Comment by cabailey** [comment]
Interesting exception - thanks for the info!

**Comment by mypil** [comment]
@rstraker - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author- @cabailey so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
