### ISSUE TITLE
Permissions for ATP Reports

### ISSUE THREAD

**Issue by Breaker119** [MicrosoftDocs/microsoft-365-docs#1632]
I'm not sure that the listed permissions are correct to view the dashboards. For instance, I have a user set up with the Security Reader Role in AAD, assigned to Security Reader in Security & Compliance Center, and added directly to the View-Only Recipients in the EAC. The user cannot open the Threat Management dashboard or the Reports dashboard.

From what I can tell, this user cannot access any of the ATP-related or DLP-related reports...maybe more.  In short, this user cannot access: https://protection.office.com/searchandinvestigation/dashboard
https://protection.office.com/insightdashboard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e62b98-5f0c-8fc3-8163-c028fa5a6445
* Version Independent ID: b8262fa8-ff97-db0a-b2b5-4dd624fb057b
* Content: [View reports for Office 365 Advanced Threat Protection, malware reports, phish reports, compromised accounts, URL protection status, threat reporting, report threats - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-reports-for-atp?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/view-reports-for-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-reports-for-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@Breaker119 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by Breaker119** [comment]
Unfortunately, support via the Service Ticket (Case#19793769) is not providing satisfactory guidance – they have fallen to the “The user needs Global Admin role”. I’ve looped in our TAM now…hopefully we’ll get a resolution either to updating RBAC or a directive to update documentation.



Jason Heiser
about.me<https://about.me/jheiser>
