### ISSUE TITLE
Set up web-only access for guest users

### ISSUE THREAD

**Issue by Remi007** [MicrosoftDocs/microsoft-365-docs#1633]
Hi,
Current:  12. On the Client apps blade, click Yes for Configure, and then select the Mobile apps and desktop clients and Modern authentication clients settings.

Correct: On the Client apps blade, click Yes for Configure, and then select the Browser settings.

Regards
Remi :)

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a secure guest sharing environment](https://docs.microsoft.com/nb-no/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@Remi007 - Thank you for submitting feedback.

Please see the response from the author based on this https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1868#issuecomment-626675416. We will close this issue now.

Thank you for your contribution to make the docs better! Much appreciated!
