### ISSUE TITLE
Independent of client

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/microsoft-365-docs#1634]
"Safety Tips in Outlook doesn't depend on what version of Outlook you're using because we crack open and insert the Safety Tip directly into the message body. That means that whatever email client you're using will show the Safety Tip. It's done at the email filter level and not rendered at the mail client level."

See blog post of former PM Terry Zink:
https://docs.microsoft.com/en-us/archive/blogs/tzink/seven-things-to-know-about-safety-tips

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1daade0-c937-6daf-cdc5-e6e23214426d
* Version Independent ID: 49836613-b9a3-fc37-ffc8-3589dda16d45
* Content: [Safety tips in email messages in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safety-tips-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safety-tips-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safety-tips-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@trudolf-msft Thank you for the feedback. We have made changes to the document to reflect the same. This can be tracked via PR #https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1715

Thanks
Sri

**Comment by mypil** [comment]
@trudolf-msft - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/a4211a878bd1a92087f5824b488b0209d8b7ba5c. 


Thank you for your contribution to make the docs better! Much appreciated!
