### ISSUE TITLE
Log retention clarification 

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [MicrosoftDocs/microsoft-365-docs#1635]
As per this document exchange stores mailbox audit logs as an email messages in a hidden folder in the audited mailbox.

This leaves me with a few questions:
What happens when you delete the audited mailbox? E.g. Is the data also replicated into the unified audit log or would the data be lost?
What happens if the mailbox is cleared?
How are audit failures recorded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by Jared-Harrington-Gibbs** [comment]
Here is an example of an unexplained error message.

![audit report error](https://user-images.githubusercontent.com/27080239/79341408-beb96900-7ef9-11ea-95c9-5b33f1e1abf6.PNG)

**Comment by markjjo** [comment]
@Jared-Harrington-Gibbs See answers to questions and other comments. Would suggest you open a ticket with MS Support if you need more investigation.

First, I was able to repro the same behavior in the screenshot. In my case (and yours I'm guessing) is that the mailbox with the error was a O365 unified group. I ran a corresponding mailbox audit log search in PowerShell and the error returned was "The SMTP address has no mailbox associated with it". So I suspect this mailbox is not sending or receiving mail for some reason, which may be related to licensing or other issue. My guess is that there are no audit records related to this mailbox.

Other answers to your questions:

#1: Deleting a mailbox does not trigger any action to copied audit records to unified audit log. If the mailbox was ingesting audit records to the unified audit log prior to deletion, those records will persist until their retention period expires. If mailbox isn't ingesting audit records, then you'd no longer have access.

#2: I assume by "cleared" you mean all items in the mailbox were deleted/purged? If so, any mailbox audit records would persist. These records are stored in an Audits subfolder in the Recoverable Items folder. You can get statistics by running the Get-MailboxFolderStatistics <mailbox> -FolderScope RecoverableItems cmdlet, but you can't access or see these records. I ran this cmdlet against two O365 group mailboxes (that's errored like yours did) and there were only 3 items in the auditing folder, which I assume is administrative-related; not audit records; in comparison, a user mailbox I tested had 507)

#3: Not sure if errors are recorded. There is some redundancy in the unified audit log where there may be duplicate records if the system suspects any issue, but I don't think that's related.
