### ISSUE TITLE
Microsoft Cloud App Security

### ISSUE THREAD

**Issue by gychit** [MicrosoftDocs/microsoft-365-docs#1640]
Please note MCAS is only part of M365 E5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab2c963-204e-0e1d-8b1e-5909f7ef4d7d
* Version Independent ID: 3229ebe7-858c-76e2-40c6-c98387f4a685
* Content: [Top 12 tasks for security teams to support working from home](https://docs.microsoft.com/en-us/microsoft-365/security/top-security-tasks-for-remote-work?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/top-security-tasks-for-remote-work.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/top-security-tasks-for-remote-work.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by jreinhardtiv4** [comment]
I too would comment on this. While it may be included in M365 E3 in addition to E5 and certain other addon plans, I would especially think that it is not included in the "all Office 365 enterprise plans." Am I correct on that?

**Comment by BrendaCarter** [comment]
This is fixed. Thank you for the feedback!
https://docs.microsoft.com/en-us/microsoft-365/security/top-security-tasks-for-remote-work?view=o365-worldwide
