### ISSUE TITLE
Need help badly

### ISSUE THREAD

**Issue by FlyFishut** [MicrosoftDocs/microsoft-365-docs#1641]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709fda6f-3a7d-92aa-e7ad-afb09cd47cda
* Version Independent ID: 991f7ce4-e3a8-e044-c3c5-82de3b8837d3
* Content: [Office 365 admin overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-overview?view=o365-worldwide#who-has-admin-permissions-in-my-business)
* Content Source: [microsoft-365/admin/admin-overview/admin-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-overview.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by FlyFishut** [comment]
This has ruined several of my personal laptops and was never intended to be done in the first place

**Comment by cmcatee-MSFT** [comment]
@FlyFishut Can you be more specific about what "this" is that ruined your laptop?

**Comment by mypil** [comment]
@FlyFishut - We would like to follow up. Can you please give more details and respond to the question of cmcatee-MSFT? 

Thank you.

**Comment by mypil** [comment]
@FlyFishut - We appreciate any feedback you can provide to make the content in the Microsoft docs better. However, we did not get any response from you so we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thanks!
