### ISSUE TITLE
Well Structure Documentation Site

### ISSUE THREAD

**Issue by rjuun** [MicrosoftDocs/microsoft-365-docs#1642]
Dear all,

My company has finally adopted Office 365 and in the last 2 months me and my team have had better and better surprises....
I am the head of governance of my company and became very interested in having this very site structure to accommodate our "Policies & Procedures" documentation.

How could I approach one of you to implement this same structure of the site into our company ?

Kind regards,
Reginaldo Junior

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82b9891-876f-515b-5193-e2831dc05235
* Version Independent ID: ae11d0d4-c0d6-ad28-341f-c9de5e5080f3
* Content: [Reference Policies, practices, and guidelines - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/reference-policies-practices-and-guidelines?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/reference-policies-practices-and-guidelines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/reference-policies-practices-and-guidelines.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @rjuun and thank you for your feedback. This does not appear to be a documentation issue (which is all we can address here). I'm not sure how to route your request, but you could contact support as your starting point. Thanks again, and kind regards.
