### ISSUE TITLE
Incorrect word in instructions

### ISSUE THREAD

**Issue by SCV-Tech** [MicrosoftDocs/microsoft-365-docs#1644]
Under the "Use the Microsoft 365 admin center to convert a mailbox" and under the "Convert the mailbox of a deleted user" sections are the sentences "Don't delete the user's old mailbox. The shared mailbox needs it there as an anchor".  "user's old mailbox" should be "user's account" as referenced in the top section of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b3fbbe-fde3-fd52-f9cd-d8fca56a1494
* Version Independent ID: 73d71ee8-579d-78b5-a8cd-48d7ec51ebb8
* Content: [Convert a user mailbox to a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@SCV-Tech - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/c04ee23f47a9977993e3b1a2458fd8ee5ebeabef. 


Thank you for your contribution to make the docs better! Much appreciated!
