### ISSUE TITLE
More detail required on the 'special environment' used to facilitate ATP Safe Attachments scanning.

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/microsoft-365-docs#1645]
Hello,

We are engaged with a very security focused customer who requires more detail regarding the 'special environment' before they will consider upgrading to ATP. Can we get a little more detail as to what this environment constitutes?

For example:
Is the 'special environment' isolated per customer?
How long are attachments retained for within the 'special environment'?
Are any engineers able to directly access the content that is sent to the 'special environment'?
What safeguards are in place to prevent engineers accessing content sent to the 'special environment'?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a177ba2-5cff-b0a0-6afa-717689db2884
* Version Independent ID: 802f6c49-9a14-e76f-6cf3-67862b40f18d
* Content: [Office 365 Advanced Threat Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/office-365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello @mtwelve ,
 **requires more detail regarding the 'special environment'** - "special environment" here - is a dedicated VM where attachment is opened. After that, ATP checks whether anything was changed in the system of that VM.
**Is the 'special environment' isolated per customer?** - it is a black box isolated from everything
**How long are attachments retained for within the 'special environment'?** - until the check is completed
**Are any engineers able to directly access the content that is sent to the 'special environment'? What safeguards are in place to prevent engineers accessing content sent to the 'special environment'?** - this info is out of Microsoft docs scope, I would recommend to review [trust center](https://www.microsoft.com/en-us/trust-center) to collect information about Microsoft's approach to Security, Privacy and Compliance.
Thank you

**Comment by mypil** [comment]
@mtwelve - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mtwelve** [comment]
Thank you @MaratMussabekov for the explanation. This is really helpful information to have.
