### ISSUE TITLE
ATPv2 email reports have typos

### ISSUE THREAD

**Issue by SusanBradley** [MicrosoftDocs/microsoft-365-docs#1646]
Where does one go to report that the emailed ATPv2 reports have spelling typos in them.

Report is Schedule-Weekly-ATPV2

SafeAttachement

Top ATP safe attachmentss

Top ATP safe linkss

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e62b98-5f0c-8fc3-8163-c028fa5a6445
* Version Independent ID: b8262fa8-ff97-db0a-b2b5-4dd624fb057b
* Content: [View reports for Office 365 Advanced Threat Protection, malware reports, phish reports, compromised accounts, URL protection status, threat reporting, report threats - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-reports-for-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-reports-for-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-reports-for-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @SusanBradley. Thank you so much for letting us know about this. To report such things, you can use the "Leave feedback" link in the Security & Compliance Center. I will also pass this feedback along. Thanks again!

**Comment by faoquong** [comment]
@SusanBradley it is a little hard to repro the spelling issues you are referring. can you share snapshots of the actual report that has this issue?
