### ISSUE TITLE
Will this delete Teams that were created by Users who will no longer be permitted to create new Groups?

### ISSUE THREAD

**Issue by ghagenberger** [MicrosoftDocs/microsoft-365-docs#1647]
Looking to run these steps to restrict who can create moving Office365 Groups moving forward but, will this delete the existing groups who have been created by users who will not be able to create Groups moving forward?

**Comment by mypil** [comment]
@ghagenberger - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by ghagenberger** [comment]
Sorry about that! This is the article:

https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

Thank you for your assistance!

**Comment by joinimran** [comment]
@ghagenberger - Thank you for your query. Please note that already created groups will not be deleted automatically but the Admin can delete those groups.

Thanks.
Imran.

**Comment by ghagenberger** [comment]
Thank you for your assistance. Would there be a script or steps you could instruct me in to roll back these settings in the event they have some unintended side affects? Thanks again so much for your assistance!

**Comment by joinimran** [comment]
@ghagenberger - There is no as such script available but I am sure that it will not create any issues. If something goes wrong, you can contact Microsoft support.

Thanks.
Imran.

**Comment by mypil** [comment]
@ghagenberger - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @joinimran  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
