### ISSUE TITLE
DNS settings for 365 on GoDaddy

### ISSUE THREAD

**Issue by mannypitta** [MicrosoftDocs/microsoft-365-docs#1648]
Microsoft 365 admin center &gt; Setup &gt; Domains page does not exist in the GoDaddy MS 365 product. When I log in, it takes me to GoDaddy pages rather than the Microsoft pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854cbadf-a802-0782-5a3a-b839995ff7fd
* Version Independent ID: b511466a-2505-4e90-548c-3fa5b6f2aedc
* Content: [Gather the information you need to create Office 365 DNS records - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/information-for-dns-records?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/information-for-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by hodolizer** [comment]
I have the same problem as reported by mypl. I get redirected to GoDaddy and adding insult to injury get a 400 Bad Request when I hit there.

**Comment by msbemba** [comment]
@mannypitta and @hodolizer  Thank you for your feedback. The reason why you don't see these options on a GoDaddy o365 tenant is that they do not grant you access to most of the administrative options. You will have to contact them to make such a change and/or they maintain these settings for the customers.

This document pertains only to direct customer's of Microsoft who have access to https://admin.microsoft.com/

Hope this Helps.

Thanks
Sri

**Comment by mannypitta** [comment]
@msbemba Thank you for your response. It does look like GoDaddy does strip out a lot of the admin functions of their version of the product.

@hodolizer I found the info at GoDaddy after a lot of hunting around. Log into your GoDaddy account and go to My Products. Under Email & Office / Office 365 click on User Accounts. Next, click on Manage to the far right of your email address. Click on "Set mail destination". It will show you the custom DNS settings for your email account.

**Comment by hodolizer** [comment]
Thank you @msbemba and @mannypitta.  I had another complication that GoDaddy support helped me figure out. When I was selecting that Manage link it was giving me a 400 Bad Request there too. It turned out to be a browser caching problem.   So if anyone else hits something similar, try flushing the cache.

**Comment by mypil** [comment]
@mannypitta @hodolizer - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
