### ISSUE TITLE
Maybe "Migration" block should be related to transition of data ? 

### ISSUE THREAD

**Issue by dips23** [MicrosoftDocs/microsoft-365-docs#165]
Hello, 

Thank you for this great article about M365, however, here in the diagram - "Migration" block is mentioning about deployment of client and server softwares which is already a part of "Foundation Infrastructure" - In that case - Do we still need to mention "Migration" block under workloads ? Or it should be directed towards migration of historical data ? 

Looking forward to the clarification !

Thanks and Regards,
Dipti Chhatrapati

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 863db1df-d804-e38c-a90c-fae6a0244653
* Version Independent ID: 7d9d48a4-27a0-5bfc-a98f-8a94015dbde4
* Content: [Deploy Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/deploy-microsoft-365-enterprise)
* Content Source: [microsoft-365/enterprise/deploy-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/deploy-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@dips23 - Thank you for your feedback, I will get this over to the Enterprise writing team for clarification.

**Comment by JoeDavies-MSFT** [comment]
@dips23 Hi Dipti, You are correct in that parts of this are covered in the foundation infrastructure. Migration of data is handled in the steps of workloads, such as SharePoint Online. However, we need a central place to describe the entire migration story for Microsoft 365 Enterprise. Hope this helps.
