### ISSUE TITLE
Need to include Teams in the encryption statements

### ISSUE THREAD

**Issue by SeCossio** [MicrosoftDocs/microsoft-365-docs#1650]
Need to include Teams in the documentation, especially if any statement regarding encryption differs for Teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed881955-a2ba-6482-cb1b-8443909c4d52
* Version Independent ID: 57679a1a-7501-40fe-c1c4-5aff9a45c792
* Content: [Encryption in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@SeCossio Thank you for the feedback. We have modified the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1769

Thanks
Sri

**Comment by mypil** [comment]
@SeCossio - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/fc1c74023d69ef221d7ffe2743e1178b1e702612. 


Thank you for your contribution to make the docs better! Much appreciated!
