### ISSUE TITLE
Missing details for Teams encryption

### ISSUE THREAD

**Issue by SeCossio** [MicrosoftDocs/microsoft-365-docs#1651]
An issue with this same request was opened and closed last year and we still have no details here. Any chance the doc could be updated to include language regarding Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd33fd3f-2ee9-139e-5cb3-afc28acaadcf
* Version Independent ID: cbc94676-e994-137b-6ff6-f2dee2940393
* Content: [Office 365 Encryption for Skype, OneDrive, SharePoint, and Exchange - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@SeCossio Thank you for the feedback. We have added the details via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1768

Thanks
Sri

**Comment by mypil** [comment]
@SeCossio - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/be2fd6aa1c61a93cb21625450d23fb0daffc462d. 


Thank you for your contribution to make the docs better! Much appreciated!
