### ISSUE TITLE
Directions Missing or Unclear

### ISSUE THREAD

**Issue by ApeironThanatos** [MicrosoftDocs/microsoft-365-docs#1652]
The title of this doc is "Change your email address...", but there are no actual instructions on this page on how to change any email address. 

The doc goes into adding a custom domain, which is already in the Setup section. The doc then states the Add Custom Domain wizard will guide you, with no further instruction. 

If the Add Domain setup wizard is supposed to also change your Admin email from .onmicrosoft.com to your custom domain, that should be included in the Setup doc, Add Domain section. The Add Domain doc should then link here, where there should be instruction on how to manually update the default .onmicrosoft email account to the custom domain for the admin user, and then secondary users. For myself, the default admin account did not appear to change from the .onmicrosoft account, and no additional emails or aliases were added after adding a custom domain. I came here to find out how to do it manually. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1394eba-4e78-2fd6-84f3-4ee64aedab51
* Version Independent ID: 0ba9ff8c-20a8-58a9-dce7-a3bb0627c134
* Content: [Change your email address to use your custom domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/change-email-address?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/email/change-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/change-email-address.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by ApeironThanatos** [comment]
Here are some instructions that may help fill out this section. This is what I had to do to fix the my issue. Pretty simple, but should be included in the help docs. 

_Resolved Issue: After adding custom domain, your Username/E-Mail is still <user>@<tenant>.onmicrosoft.com_

How to change your email address to a custom domain

**You must of completed the Add Domain Setup to update your email address to custom domain**

1. Enter the Microsoft 365 Admin Center
2. Open Users > Active Users
3. Click on the Name of the user you wish you modify. 
_A side panel will open with the details of the user account._ 
4. Under Username/Email, click on Manage Username
5. Click the Dropdown to the right of the @ sign, containing the .onmicrosoft account address, and change it to your custom domain. 
6. Save Changes
_If you were logged in under the account you changed, Microsoft 365 will now log you out, and you can log in with your new Username/Email._

**Comment by msbemba** [comment]
@ApeironThanatos Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1767

Thanks
Sri

**Comment by lefodnes** [comment]
Well, there is only the *.onmicrosoft.com address to select. I wanted to change to my real address, but I do not want to have microsoft host my email. I have my own email server. Problem now, is that all my contacts on teams believe I have this onmicrosoft.com address. This article gave me hope there was a solution, but turns out it did not give any solution to this.

**Comment by mypil** [comment]
@ApeironThanatos @lefodnes - According to the author @pebaum, this article is being decommissioned and incorporated into another as indicated on this https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1767#issuecomment-631616048.

We will close this issue now. Thank you for your contribution to make the docs better! Much appreciated!
