### ISSUE TITLE
Typo under "What is Windows 10 Business?"

### ISSUE THREAD

**Issue by Duskofdawn** [MicrosoftDocs/microsoft-365-docs#1655]
Protection for web-based threads
Should be
Protection for web-based threats

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed7e43-7ec8-01f6-8cf0-6fd77519840e
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business frequently asked questions  - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@Duskofdawn - Thank you for pointing this out.

PR #1665 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
