### ISSUE TITLE
Compliance Center on GCC High?

### ISSUE THREAD

**Issue by MKansagra** [MicrosoftDocs/microsoft-365-docs#1657]
Is Compliance Center available in GCC High environments?
I am getting internal error when trying to access it.

If not, are there any plans for it? It would be nice to see the compliance score.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed7ade2-b6c8-83db-2d20-e87ee7a3cb5d
* Version Independent ID: d0591610-bebd-22c9-aaae-d4c1c3ef2ff7
* Content: [Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/microsoft-365-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@MKansagra - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@robmazz - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by MKansagra** [comment]
Hello, following up to see if there is an update!

**Comment by robmazz** [comment]
@MKansagra - thanks for the feedback, I'm working with the MCC Team to get an answer. I'll respond here shortly, thanks for your patience!

**Comment by MKansagra** [comment]
Hello!

I was able to get an answer from GCC High team. You may want to update the docs reflecting that Microsoft Compliance Center and Secure Score is not available in GCC High or DoD environment! 

It’ll save a lot of research times for admins!
