### ISSUE TITLE
Downgrade to a DL

### ISSUE THREAD

**Issue by taromielnaz** [MicrosoftDocs/microsoft-365-docs#1658]
Can we downgrade an office 365 group to distribution list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb1e873-a684-ba18-21b4-33c2c4cf5aeb
* Version Independent ID: badad26e-0e5e-ab12-f3ae-b6cab759e7b8
* Content: [Upgrade distribution lists to Office 365 Groups in Outlook - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@taromielnaz Thank you for the feedback. We don't have a straightforward way to convert a Office365 group to a distribution group. However, you can delete the O365 group and Create a new distribution list (all in one script) but there would be data loss.

The script available at https://gallery.technet.microsoft.com/office/Convert-Unified-Groups-to-808ecc71 would do the job. But this is not an out of the box  office365 feature to be added in the document.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@taromielnaz - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
