### ISSUE TITLE
Sample domain to check traffic to O365 edge

### ISSUE THREAD

**Issue by pjchacong** [MicrosoftDocs/microsoft-365-docs#1660]
Please add domain names that admins can use to check the network jumps to the closest O366 peering point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3aa33e4-58b7-0fdc-3d12-945efbfa15ca
* Version Independent ID: ed6eea3c-473b-0c46-f7f2-a51fa3d94021
* Content: [Step 3: Avoid network hairpins - Microsoft 365 Enterprise](https://docs.microsoft.com/en-US/microsoft-365/enterprise/networking-avoid-network-hairpins?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/networking-avoid-network-hairpins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/networking-avoid-network-hairpins.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@pjchacong I added a reference to the Office 365 Network Onboarding tool at http://connectivity.office.com/, which you can use to test domain names. Thanks for your question.
