### ISSUE TITLE
Error on page

### ISSUE THREAD

**Issue by scottpretty929** [MicrosoftDocs/microsoft-365-docs#1662]
2. setup &gt; add a domain,
Should be 
2.. Settings &gt; Domain &gt; add Domain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0012093-49ca-c2f6-a3f3-4e4252fca609
* Version Independent ID: 22784dda-ff03-971b-4d6e-5b0152f62942
* Content: [Add a domain to Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/setup/add-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by PrasadKasireddy** [comment]
@scottpretty929 - thanks a for reporting.
Could you please elaborate more on Error page, and error message description.

**Comment by scottpretty929** [comment]
Evening,

In the document it says to do go to a area when in fact it's in a different
place which I mentioned in the comment where the document should point
users. It's only a small mistake but I noticed it and thought I should
mention it.

Kind regards

Scott

**Comment by msbemba** [comment]
@scottpretty929 Thank you for the feedback. The document is updated with the step that you have mentioned. It is split into two steps 

2)Go to the Setup > Domains page.

3)Select Add domain.

Thanks
Sri

**Comment by mypil** [comment]
@scottpretty929 @PrasadKasireddy  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
