### ISSUE TITLE
Relationship between Azure AD roles and O365 S&C roles?

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#1668]
The article explains the relationship between Exchange role groups and Security & Compliance Center role groups, but it does not explain the relationship (if any) between Azure AD privileged roles and Security & Compliance Center role groups. Many of the roles shown in Office 365 Security & Compliance Center also appear as Azure AD administrative roles. For example: Compliance Administrator, Compliance data administrator, Security Reader, Security Operator, Security Administrator. On the other hand, many other roles in Office 365 Security & Compliance Center permissions do not appear as Azure AD administrative roles. For example, Insider Risk Management Admins, Quarantine Administrator (and many others.) If an administrator adds a user to an Azure AD role that exists in Office 365 Security & Compliance Center permissions, does the user get permissions in Office 365 Security & Compliance Center? If an administrator adds a user to an Office 365 Security & Compliance Center role group, is the user also added to the Azure AD administrative role of the same name? What is the recommended practice? The design of permissions in O365 S&C is confusing AF and the documentation does not explain it adequately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions in the Office 365 Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by robmacf** [comment]
Mea culpa, the article does explain the relationship with some overlapping AAD roles. But there are many additional roles that exist in both AAD and O365 S&C with identical names, and it's not explained whether they are they are synchronized or not.

**Comment by chrisda** [comment]
@robmacf, the topic that better explains the relationship between AAD roles and SCC role groups is:

<https://docs.microsoft.com/microsoft-365/security/office-365-security/permissions-microsoft-365-compliance-security?view=o365-worldwide>

Note that this topic was missing from the table of contents, and was only added recently (it now sits directly under the topic you're asking about).

From the other topic: 

> It's important to understand that you when you manage these roles in Azure Active Directory, you're doing so centrally for all Microsoft 365 services. However, when you manage a role in a specific service, such as the Office 365 Security & Compliance Center, you're managing the role for only that specific service. The assignments and permissions for a role in a service override any permissions granted to the Azure Active Directory role. <br><br>This can be useful – for example, if a person is assigned to the Security administrator role, they don't have permissions to manage incidents. But you can use the permissions in Windows Defender Advanced Threat Protection to give them the specific permission for incident management in that service.

**Comment by mypil** [comment]
@robmacf - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @chrisda  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
