### ISSUE TITLE
Record Type 51

### ISSUE THREAD

**Issue by cpayne26** [MicrosoftDocs/microsoft-365-docs#1669]
Shouldn't Record Type 51 be documented?  HygieneTenantEvents events are a searchable component on MCAS.  I'm looking for details and don't see a schema definition on this page or https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d18ff7-80de-a4d1-41a3-3601f09d3442
* Version Independent ID: dc3327c1-5c78-53ee-6ecb-18b274ddcdbd
* Content: [Detailed properties in the Office 365 audit log - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@cpayne26 Thanks for heads up. I'll look into adding this to the O365 management activity api documentation. Until that happens, here's the HygieneEvent schema:

  
  <edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
  <edmx:Reference Uri="http://schema.audit.exchange.microsoft.com">
  <edmx:Include Alias="Common" Namespace="Microsoft.Office.Audit.Schema" /> 
  </edmx:Reference>
  <edmx:DataServices>
  <Schema Namespace="Microsoft.Office.Audit.Schema.HygieneEvent" xmlns="http://docs.oasis-open.org/odata/ns/edm">
  <EntityType Name="HygieneEventRecord" BaseType="AuditRecord">
  <Annotation Term="Microsoft.Office.Audit.Schema.WorkloadType" EnumMember="Microsoft.Office.Audit.Schema.WorkloadType/SecurityComplianceCenter" /> 
  <Annotation Term="Microsoft.Office.Audit.Schema.RecordType" EnumMember="Microsoft.Office.Audit.Schema.AuditLogRecordType/HygieneEvent" /> 
  <Property Name="Reason" Type="Edm.String" /> 
  <Property Name="Audit" Type="Edm.String" /> 
  <Property Name="Event" Type="Edm.String" /> 
  <Property Name="EventId" Type="Edm.Int64" /> 
  <Property Name="EventValue" Type="Edm.String" /> 
  </EntityType>
  </Schema>
  </edmx:DataServices>
  </edmx:Edmx

**Comment by markjjo** [comment]
/  <?xml version="1.0" encoding="utf-8" ?> 
- <edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
- <edmx:Reference Uri="http://schema.audit.exchange.microsoft.com">
  <edmx:Include Alias="Common" Namespace="Microsoft.Office.Audit.Schema" /> 
  </edmx:Reference>
- <edmx:DataServices>
- <Schema Namespace="Microsoft.Office.Audit.Schema.HygieneEvent" xmlns="http://docs.oasis-open.org/odata/ns/edm">
- <EntityType Name="HygieneEventRecord" BaseType="AuditRecord">
  <Annotation Term="Microsoft.Office.Audit.Schema.WorkloadType" EnumMember="Microsoft.Office.Audit.Schema.WorkloadType/SecurityComplianceCenter" /> 
  <Annotation Term="Microsoft.Office.Audit.Schema.RecordType" EnumMember="Microsoft.Office.Audit.Schema.AuditLogRecordType/HygieneEvent" /> 
  <Property Name="Reason" Type="Edm.String" /> 
  <Property Name="Audit" Type="Edm.String" /> 
  <Property Name="Event" Type="Edm.String" /> 
  <Property Name="EventId" Type="Edm.Int64" /> 
  <Property Name="EventValue" Type="Edm.String" /> 
  </EntityType>
  </Schema>
  </edmx:DataServices>
  </edmx:Edmx>
