### ISSUE TITLE
dead link on page

### ISSUE THREAD

**Issue by pahuijbr** [MicrosoftDocs/microsoft-365-docs#1673]
In section: **Some differences between Threat Explorer and real-time detections**

For more details, see Office 365 ATP Service Description: Feature availability across Advanced Threat Protection (ATP) plans.

Link points to https://docs.microsoft.com/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans which gives a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and real-time detections, new to Threat Explorer, changes to Threat Explorer, new to Office 365, Security, Cloud Security, new to Security in ATP, new ATP features - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by PrasadKasireddy** [comment]
Hi @pahuijbr,

Fixing the broken link and raised PR.
The correct URL - https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans

**Comment by mypil** [comment]
@pahuijbr - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/531fe0824de487e77065c8cc21e285e9f1e6295f. 

@PrasadKasireddy - Thank you for creating the PR that resolved this issue.


Thank you for your contribution to make the docs better! Much appreciated!
