### ISSUE TITLE
Please add descriptions of X-Microsoft-Antispam-Mailbox-Delivery header

### ISSUE THREAD

**Issue by jas8522** [MicrosoftDocs/microsoft-365-docs#1682]
Here's an example of one:

```
abwl:0;wl:0;pcwl:0;kl:0;iwl:0;dwl:0;dkl:0;rwl:0;ucf:0;jmr:0;ex:0;auth:1;dest:J;OFR:SpamFilterAuthJ;ENG:(5062000262)(9000001)(9005001)(9015001)(9020002)(9025001)(5061607266)(5061608174)(4900115)(4920090)(6350004)(4950130)(4990090)(9140004);RF:JunkEmail;
```

Would be great to know what all of this means as the results appear to determine whether the message should be filtered to the Junk mailbox or the Inbox.

**Comment by mypil** [comment]
@jas8522 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by jas8522** [comment]
@mypil https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide#x-microsoft-antispam-message-header-fields

**Comment by get-itips** [comment]
Hello @jas8522 Jordan how are you? Hope you are doing good 👍 

I could find that this matter was discussed in the past, [here](https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/442). Please, kindly read that thread where the authors explained why this was not inteded to be documented and alternatives were provided.

Hope that helps

**Comment by jas8522** [comment]
@get-itips Ahh, I see, so you're saying that you're going to continue blocking emails for no clear reason, and never divulge that reason. You're going to provide generic information to resolve it that has already been implemented by mail administrators, leaving nothing left for the sending mail administrator to do to fix it, yet all their messages going to Microsoft spam boxes. 

Then because the people sending the emails need for their messages to be able to get through, they're likely to switch to Office 365, thus paying Microsoft for email services. How monopolistic of you. Can't say I didn't see it coming from Microsoft though.

**Comment by mypil** [comment]
@jas8522 - Thank you for engaging with the community here for the docs.

We greatly encourage collaboration from the readers and get constructive criticism, containing suggestions of what would improve the documentation. However, our work is restricted to making specific changes to docs so your suggestion and feedback might get more traction in the **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)** channel.

We hope this gets you pointed in the right direction. If you do find that there is a documentation error, feel free to comment back and we'll gladly look into fixing it.

**Comment by jas8522** [comment]
@mypil I'm very confused about this. You said:

> We greatly encourage collaboration from the readers and get constructive criticism, containing suggestions of what would improve the documentation. However, our work is restricted to making specific changes to docs

And what I'm requesting is absolutely about improving the documentation. If a mail admin has done everything your current documentation says to do to ensure messages are delivered to the recipient's inbox, yet all messages sent to Microsoft hosted addresses are still going to junk (despite reaching the inbox for other mail hosts, like Gmail), then your documentation is, by definition, incomplete.

The description of that documentation section is:
> Describes the anti-spam fields placed in Internet headers, which can help provide administrators with information about the message and about how it was processed.

Therefore if there are headers that the Exchange server software is adding to emails which are *not* described in that section (which there are) and which are required to understand in order to know why a message was processed to junk (which they are), you're clearly missing important information in your documentation.
