### ISSUE TITLE
Typo / grammar check

### ISSUE THREAD

**Issue by MSCM-GitHub** [MicrosoftDocs/microsoft-365-docs#1683]
Quote "Verify the junk email rule is enabled in the user's mailbox: It's enabled by default, but if it's isn't messages...". The following "but if it's isn't" expanded says "but if it is is not" doesn't make sense. I'm guessing it should read "but if it isn't".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbab747e-1a43-037e-09ca-9c402deec602
* Version Independent ID: 1c6d8e28-034d-24d6-5732-b96475411d6b
* Content: [Anti-spam protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-protection?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Fixed.

Thanks for the feedback.

Closing.
