### ISSUE TITLE
Business only?

### ISSUE THREAD

**Issue by joshtrupin** [MicrosoftDocs/microsoft-365-docs#1686]
Does this page refer to Microsoft 365 Business only, or are the stages the same for Microsoft 365 Enterprise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
"Microsoft 365 for business" (note the small "b") refers generally to any of the Microsoft 365 products, including Office 365 E1, E3, and E5.

**Comment by joshtrupin** [comment]
Thank you!
