### ISSUE TITLE
Misspelled Word

### ISSUE THREAD

**Issue by Orta373** [MicrosoftDocs/microsoft-365-docs#1687]
Microsfot 365 spam  at the top Microsoft is mispelled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge (ZAP) - retroactive protection against spam, malware, and phishing. - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Fixed. Thanks for the feedback.

Closing
