### ISSUE TITLE
Is it ProPlus or "Microsoft 365 Apps for enterprise"

### ISSUE THREAD

**Issue by MrMichaelJKelly** [MicrosoftDocs/microsoft-365-docs#1688]
At one point above, the text reads "Under Product Information, you should see Subscription Product and Microsoft Microsoft 365 Apps for enterprise, as shown in the following image."  However, the image does not show "Microsoft 365 Apps for enterprise" but "Microsoft Office 365 ProPlus".  Which is it (my Word shows ProPlus as the image does). Also, it's not clear what O365 license this corresponds to - is this an E3 license?  Is Business Premium not enough?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@MrMichaelJKelly  Thank you for your feedback. Office 365 ProPlus is now Microsoft 365 Apps for the enterprise. With Business premium, you get Microsoft 365 Apps for business/ Office 365 Business and that does not support Centralized deployment.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@MrMichaelJKelly  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
