### ISSUE TITLE
Please explain further

### ISSUE THREAD

**Issue by jopgommans** [MicrosoftDocs/microsoft-365-docs#1694]
Can this line "All other users will be asked to perform additional authentication when needed." be explained further. What can I expect for end-users when the security defaults have been turned on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@jopgommans Thank you for your feedback. After users complete Multi-Factor Authentication registration, they'll be prompted for additional authentication whenever necessary (This is based on your settings for users to be prompted every 7 or 14 days in the MFA settings - https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-manage-settings#turn-on-two-factor-verification-prompts-on-a-trusted-device)

Whereas an administrator will be prompted every time they sign in.

Hope this helps!
Thanks
Sri

**Comment by jopgommans** [comment]
Hi Sri,

Thanks for the reply!
I understand that yes, thanks 😊 The point I meant to make was, it would also be good explain further in the page itself so anyone reading it knows what they can expect. You also mention “This is based on your settings for users”, it would be good to explain which settings have impact on this. That’s what I meant.
Hope this helps you, again: thanks for the feedback!

Kind regards,​
JOP GOMMANS
CONSULTANT
+31620583115
<tel:+31620583115>
[cid:image008.png@01D621F7.FAD5E990]
Transformation Hub Amstelveen
<https://goo.gl/maps/GYUjVpmk9H1kUvQY7>
InSpark Lab Schiphol
<https://goo.gl/maps/YWrcoQ4diSYV59e89>
[cid:image009.png@01D621F7.FAD5E990]<https://www.linkedin.com/company/inspark>
[cid:image010.png@01D621F7.FAD5E990]<https://www.facebook.com/weareinspark/>
[cid:image011.png@01D621F7.FAD5E990]<https://twitter.com/we_are_inspark>
[cid:image012.png@01D621F7.FAD5E990]<https://www.youtube.com/channel/UCp6PCev9xIpg7jRE2Vi6t0w>
[cid:image013.png@01D621F7.FAD5E990]<https://www.instagram.com/we_are_inspark/>

**Comment by shereen-yong** [comment]
Hello! I am wondering if the multi-factor authentication described here can be used for an on-premises implementation of Dynamics 365 for Finance and Operations? For on-prem D365 F&O the users still access the application via web browser, however the difference is the application is not hosted on Azure. Would MFA still work and if so, would the way to implementing it be the same way as described here via AAD and Office 365 admin settings?
Any related information would be appreciated thanks!

**Comment by msbemba** [comment]
@jopgommans THank you for your feedback. We have modified the doc adding a reference to change 2fa settings Via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1935

Thanks
Sri

**Comment by msbemba** [comment]
@shereen-yong  Thank you for your feedback. This document refers to every new Microsoft 365 subscription. In your case, I would still recommend you to contact Dynamics Support to get clarity. @mypil  Would you be able to help @shereen-yong  On how to open a Dynamics support case?

Thanks
Sri

**Comment by mypil** [comment]
@shereen-yong  - You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so they can help resolve your technical issue.  Thank you!

**Comment by mypil** [comment]
@jopgommans - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/06e83da680a325f0c3222bb395a9882d68a5b1cd. 


Thank you for your contribution to make the docs better! Much appreciated!
