### ISSUE TITLE
Wrong details about section Bulgaria

### ISSUE THREAD

**Issue by Ivan-Mirchev** [MicrosoftDocs/microsoft-365-docs#1698]
Function name is wrong! It is written: Func_bulgaria_national_number, but it should be Func_bulgaria_eu_national_id_card.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ab1c1b-5497-8d9d-2b29-91876efcde2c
* Version Independent ID: dfff16cb-ce07-69da-f0f1-c8a01201c545
* Content: [EU National Identification Number - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/eu-national-identification-number?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/eu-national-identification-number.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/eu-national-identification-number.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Ivan-Mirchev Thank you for this feedback! I will look into this.

**Comment by cabailey** [comment]
Reassigning to correct article owner (@chrfox)

**Comment by chrfox** [comment]
HI @Ivan-Mirchev 
Thanks for letting me know about this. The content has to reflect what is coded into the product, I am checking with the owning product group and will update as appropriate.

**Comment by chrfox** [comment]
Hi @Ivan-Mirchev
This error has been fixed and the topic republished. Thanks for calling our attention to this.
