### ISSUE TITLE
DLP not functioning on macbooks?

### ISSUE THREAD

**Issue by katrakovic** [MicrosoftDocs/microsoft-365-docs#1699]
Hi, 

Policy tips are not being shown to those using mac o/s. 
Is there a reason for this or a different way to configure policy rules targetting those that use macbooks?

Thanks in advance for your help!

**Comment by mypil** [comment]
@katrakovic - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by katrakovic** [comment]
(https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide)

**Comment by mypil** [comment]
@katrakovic - Thank you for submitting feedback.

Policy tips are currently not supported for Outlook for Mac iOS clients based on this doc - [https://docs.microsoft.com/office365/troubleshoot/data-loss-prevention/data-loss-prevention-policy-tips#client-doesnt-support-mailtips](https://docs.microsoft.com/office365/troubleshoot/data-loss-prevention/data-loss-prevention-policy-tips#client-doesnt-support-mailtips). Please refer to the "Note" portion from that doc as shown below:


![image](https://user-images.githubusercontent.com/47188252/80319050-a9d7b200-87e4-11ea-8d25-ede720bb132b.png)
