### ISSUE TITLE
Domain 

### ISSUE THREAD

**Issue by gervert502** [MicrosoftDocs/microsoft-365-docs#170]
Back into my account 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c4de82-27a6-92e2-5af7-16c4d2a21fbb
* Version Independent ID: e7f16a4b-8380-62e3-4bb0-75fe9a58a1fc
* Content: [Office 365 Breach Notification Under the GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-breach-office365#office-365-investments-in-data-security)
* Content Source: [microsoft-365/compliance/gdpr-breach-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/compliance/gdpr-breach-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by robmazz** [comment]
@gervert502 - thanks for the update, closing this issue.
