### ISSUE TITLE
DLP Reports

### ISSUE THREAD

**Issue by katrakovic** [MicrosoftDocs/microsoft-365-docs#1700]
Hi,

When trying to extract "incident" reports, oftentimes I get reports with very little information about senders, what sensitive data was detected and so on. 
What is the best way to find relevant, detailed information on this? Is there a way to extract reports that also include policy overrides & user reports?

Thanks
Katarina

**Comment by katrakovic** [comment]
And is it possible to view real time reports or are reports only ready after 24 hrs?

**Comment by mypil** [comment]
@katrakovic - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by katrakovic** [comment]
(https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide)

**Comment by mypil** [comment]
@katrakovic - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by katrakovic** [comment]
There are the two types of reports, Incident report and Policy match report.
