### ISSUE TITLE
Multiple DLP email notifications being sent to one person

### ISSUE THREAD

**Issue by katrakovic** [MicrosoftDocs/microsoft-365-docs#1702]
Hi 
We are noticing that for one email sent that has sensitive information, two other emails are being sent to the individual to notify them that their action is against the organizations policies.

Why is this? Can we limit the amount of emails being sent to one person? Would it be possible to get a "bulk" e-mail sent with a summary of all the sensitive info that was shared?

Thanks for your help.

**Comment by mypil** [comment]
@katrakovic - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by katrakovic** [comment]
Sorry, here you go:
https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide

**Comment by mypil** [comment]
@katrakovic - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
