### ISSUE TITLE
Where is Secure Score found?

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1703]
The document should explain that Secure Score is found at https://security.microsoft.com/securescore on the Microsoft 365 Security portal page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a57c0a2-0a6c-4499-f31e-18016d006549
* Version Independent ID: 5587ca01-e40f-478d-1796-b7b4dc41cbf0
* Content: [Microsoft Secure Score - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/microsoft-secure-score?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/microsoft-secure-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/microsoft-secure-score.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
That's correct, I'll make an update.
