### ISSUE TITLE
Admin consent PowerShell code incorrect

### ISSUE THREAD

**Issue by dewaltk** [MicrosoftDocs/microsoft-365-docs#1705]
The PowerShell code for Admin consent seems incorrect. the login-AzureRmAccount and Get-AzureRmADServicePrincipal commands do not exist.

It seems like this was replaced by the Az module and I can connect with Connect-AzAccount but the other commands do not match and I am not able to find their replacement commands.

Login-AzureRmAccount 
$appId="bcf62038-e005-436d-b970-2a472f8c1982" 
$sp=Get-AzureRmADServicePrincipal -ServicePrincipalName $appId
if ($sp -eq $null) { New-AzureRmADServicePrincipal -ApplicationId $appId }
Start-Process  "https://login.microsoftonline.com/common/adminconsent?client_id=$appId"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by dewaltk** [comment]
Okay seems like the correct PowerShell command is this:

Login-AzAccount
$sp = Get-AzADServicePrincipal -ServicePrincipalName $appId
$appId="bcf62038-e005-436d-b970-2a472f8c1982"
if ($sp -eq $null) {New-AzADServicePrincipal -ApplicationId $appId }
Start-Process "https://login.microsoftonline.com/common/adminconsent?client_id=$appId"

**Comment by get-itips** [comment]
Hello @dewaltk thanks for your report.
I created a PR to update the article, if it gets approval, it will be reflected online.
Thank you

**Comment by mypil** [comment]
@dewaltk - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/fd8094b094be99beb0dc3748f85e05867ad6c10e. 


Thank you for your contribution to make the docs better! Much appreciated!
