### ISSUE TITLE
Link doc to import non-o365 data in the collect case data page

### ISSUE THREAD

**Issue by Biermugs** [MicrosoftDocs/microsoft-365-docs#1706]
While importing non-o365 data occurs within the working set, it is still part of the "collect case data" step. A link to the spot would be great here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdeaec7-dd56-7fc5-f6cd-9554d99b6afc
* Version Independent ID: a4125bcf-0160-869b-fdaf-656a85b55d3e
* Content: [Collect data for a case in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/collecting-data-for-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/collecting-data-for-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/collecting-data-for-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **esclee**

**Comment by markjjo** [comment]
@Biermugs Good suggestion! I will update this topic and then close this comment when updated topic is published.

**Comment by markjjo** [comment]
@Biermugs Done. Topic updated, added new section on adding non-o365 data to review set. Thanks again for suggestion.

https://docs.microsoft.com/en-us/microsoft-365/compliance/collecting-data-for-ediscovery?view=o365-worldwide#add-non-microsoft-365-data-to-a-review-set
