### ISSUE TITLE
Group must not be hidden

### ISSUE THREAD

**Issue by GarrettMichaelHayes** [MicrosoftDocs/microsoft-365-docs#1707]
There is a critical piece of information missing.  The Distribution Group must NOT be Hidden!  If it is, "Send As" fails with an error indicating you don't have "Send on behalf of" permission

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a862d8-4223-7bb7-42f1-9842cbeacf87
* Version Independent ID: 2c3c7e9a-a44d-168e-2083-b1527ab3f61c
* Content: [Allow members to send as or send on behalf of a Group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@GarrettMichaelHayes  Thank you for your feedback. I was able to test by sending from a group that is hidden. You will need to contact the Support team to resolve the issue at your end. @mypil  Could you help Garrett with contact information for the support team?

Thanks
Sri

**Comment by mypil** [comment]
@GarrettMichaelHayes - Thank you for submitting feedback.

Please open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
