### ISSUE TITLE
Delegated administration for Microsoft Partners

### ISSUE THREAD

**Issue by ad0m** [MicrosoftDocs/microsoft-365-docs#1709]
There are two options for Microsoft Partners that support clients: 

Full Administration  (aka Admin agent) 
Limited Administration (aka helpdesk agent) 

Full administration is an ALL inclusive and Limited pretty much provides nothing at all, there is no in-between. 

Secondly, Full Administration, does not give you the FULL experience of a global admin of your clients tenant. i.e. you cannot: 

- Manage users that leave (Converting to a shared mailbox 
- Manage SharePoint Admin centre on behalf of your customer 

This is mainly when you have a user support contract on top of being your clients MSP/CSP 

This limits us in having to create named accounts for all our helpdesk engineers in each of our client tenants. Which is a somewhat long winded process.  

Are there ever going to be any changes here?

**Comment by mypil** [comment]
@ad0m - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by ad0m** [comment]
Hi @mypil - it is via this link: https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide#delegated-administration-for-microsoft-partners 

It is in relation to how limited the admin roles are for delegated admins. The result is us having to script and create all our service desk users into each of our client tenants and then run a script to remove them when they leave, delegated admin just does not offer: 

1 - the right amount of support for Limited Administrator 
2 - Almost enough but still limitations around Full Administrator 

Both via delegated admin partner center. 

thanks for coming back to me.

**Comment by mypil** [comment]
@ad0m - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.  
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
