### ISSUE TITLE
Virtual switch step

### ISSUE THREAD

**Issue by tdav232** [MicrosoftDocs/microsoft-365-docs#1710]
During setup the document calls to create an external network for internet access. How necessary is this? Being that i specifically create an 'external' network.

I already have a switch that is configured to internal but it grants internet access my linux vm's seem to have no problem connecting using it. And apparently only 1 switch can be connected to a wireless thingy.

**Comment by mypil** [comment]
@flyinghotpocket - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by flyinghotpocket** [comment]
https://www.microsoft.com/en-us/evalcenter/evaluate-lab-kit Windows off and deployment lab zip. it comes with a setup guide docx.

**Comment by tdav232** [comment]
Yup looks like it is completely required, the installer wont proceed without a specific external network defined.
