### ISSUE TITLE
I don't see Settings in my (2020-04-22, Chrome, OS X) rendering of the New Admin Center

### ISSUE THREAD

**Issue by SteveMinar** [MicrosoftDocs/microsoft-365-docs#1712]
The instructions may need to be updated to reflect admin center changes.
I don't see Settings in my (2020-04-22, Chrome, OS X) rendering of the New Admin Center. The link provided takes me to the Services & add-ins page, but I can't figure out how to navigate to that page from the Admin Center home page.
If I search for Calendar, I can select from the search results and edit settings. At the bottom of the settings dialog presented, it suggests using the Exchange Admin Center to see more options (calendar related). I can't find those settings in the Exchange Admin Center either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b3bda19-af86-20e8-92c4-ccb0caee7cd2
* Version Independent ID: cc93f793-d8bf-e508-d1c1-ddada942623d
* Content: [Share calendars with external users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/share-calendars-with-external-users?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/manage/share-calendars-with-external-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/share-calendars-with-external-users.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by MaratMussabekov** [comment]
Hello, @SteveMinar 
it is now located at Settings-> Settings
![image](https://user-images.githubusercontent.com/48041687/81923379-04e81200-95f7-11ea-8a13-90ab35398341.png)
I will create a PR to add this info to the article
Thank you

**Comment by mypil** [comment]
@SteveMinar - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/1b4f6f7a2916e3d973a650a93f69ff0be59d074c. 


Thank you for your contribution to make the docs better! Much appreciated!
