### ISSUE TITLE
Audit Log Retention for less than E3 Plans

### ISSUE THREAD

**Issue by jreinhardtiv4** [MicrosoftDocs/microsoft-365-docs#1713]
What is the operation of the audit log retention for those on E1 or even the Business class SKUs of M365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jreinhardtiv4 If you're asking about audit log retention duration, then it's 90 days for **any** plan that has basic audit (unified audit logging) and **isn't** E5. One-year retention of audit logs is only available in E5 (or for users with E5 add-on licenses).

**Comment by jreinhardtiv4** [comment]
Thank you for your reply. Can I suggest that the verbiage be updated? Your answer confirms my experience, but I think the article could be improved. It seems the statements such as below should state the kind of "any plan with basic audit and isn't E5" rather than just saying M365 E3 and O365 E3. I'm particularly referring to the 3rd bullet under "Before you begin" and the question "How long are the audit records retained for?" under FAQs. Would that make sense to you?

**Comment by markjjo** [comment]
@jreinhardtiv4 Thanks for following up. I think that does make sense. To paraphrase (and add my own .02 cents) I think you're suggesting to cite plans (E1, E3, and E5) that support basic audit, and state that audit log retention period is 90 days for any plan that isn't E5 and that for E5 it's 1 yr. I have another request to specifically call out E1, which is why I think we should cite all plans. Does that work.

Also, a favor: can you please confirm for me that basic/unified auditing is available in E1 orgs? Thanks!

**Comment by jreinhardtiv4** [comment]
Yea, I am suggesting to cite specific plans or to just have a general statement that the baseline plans all include the 90 day audit length rather than just calling out E3 specifically. For some guidance, this [link](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center) affirms that unified auditing is available for nearly all O365/M365 SKUs and 
_a la carte_ plans with the exception of Skype for Business Plan 1/Plan 2. But it doesn't address the aduit log length that is primarily under consideration here. I can only confirm that the audit log search is indeed available in E1 tenants, but I can't speak to the 90 day retention period at this time.

Does this help? I think that link to the service description definitely seems to affirm that all plans get the audit log search. This article just needs to say that only E5 gets the 1 year legnth, but all others with access to the unified audit log will get the 90 day. At least that is what it looks like without further testing.

**Comment by markjjo** [comment]
@jreinhardtiv4 Thanks for the response. It was helpful. I went ahead and updated the topic based on your feedback/suggestions. I updated the bit in the before you begin section and the FAQ. Thanks again for the help.

https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-begin
