### ISSUE TITLE
Additional details that need to be added to this article on how Safe senders work

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/microsoft-365-docs#1714]
I would request that additional details be added that state:
The Aggregate Safe Sender list inside EOP has following sync limit 1024 safe senders (Safe sender email addresses, safe recipients, external contacts (if user has selected “also trust email from my contacts” in Junk Mail folder settings)) and 500 block sender entries (blocked domains, blocked sender addresses only).

Lists are not used and False Positive/False Negative management is done via the Admin submission tool:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission

For lists that are over the limit:
•	The rules synced to Azure Active Directory are mail contacts first(if trusted contacts is enabled) then Outlook Safe Sender & Safe Recipient lists combined, de-duplicated and sorted alphabetically each time a change is made for the first 1024 entries
•	The 1024 on the server are run and anything relevant gets stamped on the message
•	The ones over 1024 that did not get synced to Azure Active Directory are run as JMF when they get to Outlook (not Outlook on the Web) and are not stamped in the headers. 
•	Impact of enabling trusted contact in safe senders limit will reduce the number of Safe Sender & Safe Recipient that can be synced and if this is a concern then Turning Off Trusted Contacts is recommended.   
•	It is possible to disable trusted contacts with a group policy the policy is part of the Office policies
o	File name: outlk16.opax
o	Policy setting name: Trust e-mail from contacts

There are two places where safe senders are kept, one list per mailbox (Mailbox Junk Email Configuration), and a second list in the aggregate list inside EOP. Mailbox Junk email configuration has limit of 510 KB at client level; which includes all junk mail filter lists and additional junk mail filter settings. If the mailbox junk email configuration limit is hit, user can receive an error in Outlook like below:
Cannot/Unable add to the server Junk E-mail lists. You are over the size allowed on the server.  The Junk E-mail filter on the server will be disabled until your Junk E-mail lists have been reduced to the size allowed by the server.
 

When the aggregate list contains at least 1024, the list stops accepting more entries via PowerShell/OWA, but the user/admin does not receive any error. Outlook on the other hand can continue to add more entries till it reaches client limit of 510kb and utilizes the entries (presuming that something else in the transport stack does not block it (transport rule, ATP policy, etc.).

Shared Mailboxes
Safe Senders for shared mailboxes are not synced to Azure AD and EOP by design.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bec871b-790f-6826-b8f8-d1b7830c49ab
* Version Independent ID: 460db4e8-7f93-60a3-4889-f2d8f08fc75f
* Content: [Configure junk email settings on Exchange Online mailboxes in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Topic updated.

Thanks for the feedback.

Closing
