### ISSUE TITLE
Set a custom sender address for email notifications

### ISSUE THREAD

**Issue by michelangelobottura** [MicrosoftDocs/microsoft-365-docs#1716]
What is the default sender address for email notifications for Exchange content in DLP policies? Is there any options via web interface or powerhsell to set it to a custom value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by get-itips** [comment]
Hello @michelangelobottura Michel how are you?
Notifications should come from `postmaster@<default domain>.com`
I investigated and it seems there isn't currently an option to customize it thru Ps or UI, and I found [an uservoice suggestion](https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/33556768-allow-customization-for-sender-and-subject-for-cus). I voted for it.
Hope this information helps you.

**Comment by mypil** [comment]
@michelangelobottura  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
