### ISSUE TITLE
Questions regarding SharePoint DLP scenarios

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/microsoft-365-docs#1717]
Can we add/clarify a few specific points in this article? If they are already called out can we make them more prominent?

1) When a policy is added, modified, or deleted what is the time frame that it will "take effect" for example, publishing retention labels to SPO is documented to take up to 7 days before they become available. Can we add a call-out or table to show expected publishing / replication timeframes for DLP policy changes to different services?

2) For DLP policies for SharePoint Online and OD4B how is "data at rest" evaluation handled? If a NEW DLP policy is added will existing documents be re-evaluated for the new policy? Or will that new policy only be evaluated the next time the document is modified?

3) What is the behavior when a document is shared? Will it be evaluated before the sharing permissions are modified? Or is the evaluation triggered by the document being shared, and then if a DLP policy is triggered the sharing retroactively blocked? (e.g. Is there a window of time where a document has been shared and is accessible, but has not yet been evaluated by a DLP policy? Can we please clarify this scenario? Document exists in SharePoint and is not modified, a new DLP policy is added, the document is then shared?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@dotnick365 investigating if this where these questions should be answered

**Comment by chrfox** [comment]
HI @dotnick365 
These are great questions and I will take them as items to be worked into the content over the next few months. Thanks for asking them
