### ISSUE TITLE
DLP reports?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/microsoft-365-docs#1718]
If no notification or alert is specified in a DLP policy. Will policy matches still be reflected within the DLP reports in the Security & Compliance center?

Are DLP policy events written to the unified audit log, or available via the management activity API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@dotnick365  thanks for the great questions, I have taken them as work items to be added to updated content over the next few months.
