### ISSUE TITLE
Typo section 8e

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/microsoft-365-docs#1721]
"origninal server account" original

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains FAQ - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?view=o365-worldwide#why-do-i-have-an-onmicrosoftcom-domain)
* Content Source: [microsoft-365/admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@O365scripts - Thank you for pointing this out.

PR #1731 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
