### ISSUE TITLE
How is Teams affected without SRV support or multiple CNAMEs?

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/microsoft-365-docs#1722]
In the "If multiple CNAME records are not supported" and "If SRV records are not supported" there is only mention of SFBO but not of Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains FAQ - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?view=o365-worldwide#why-do-i-have-an-onmicrosoftcom-domain)
* Content Source: [microsoft-365/admin/setup/domains-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by get-itips** [comment]
Hello @O365scripts 
How are you? Hope you are doing great. 👍 
Teams relies on SRV/CNAME in an scenario of federation with SfB (Online or On-premises), so this line covers the affected services in case of no SRV:

>  **If SRV records are not supported**, the following Office 365 features are not available: 
> [...]
> - External communication (federation) with Skype for Business Online users in other organizations.

In the case of CNAME I will propose adding a line to the article to make it clearer.

Thank you

**Comment by mypil** [comment]
@O365scripts - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/b2112dd6cdcc27a5a9ea34b26077a424582185c9. 


Thank you for your contribution to make the docs better! Much appreciated!
