### ISSUE TITLE
DLP Notification emails being sent to external parties as well?

### ISSUE THREAD

**Issue by katrakovic** [MicrosoftDocs/microsoft-365-docs#1724]
Hi, 

When creating a data loss prevention policy, it was not clear that emails would also be sent to external policies notifying them their communication included sensitive information.

https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide

**Comment by chrfox** [comment]
Hi @katrakovic 
Thanks for your comment. Can you please clarify what you mean by 'external policies'. 

Thanks

**Comment by MaratMussabekov** [comment]
Hello @chrfox ,
I believe it was a misprint and @katrakovic meant that the notifications are being sent to external senders. It looks like some other users are having the same problem - https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/33729211-dlp-notifications-on-incoming-external-email

However, I wasn't able to reproduсe the issue and in my test environment notifications were not sent outside.

Thank you

**Comment by katrakovic** [comment]
Thank you @MaratMussabekov , it was indeed a typo. I meant to say that those external parties sending us sensitive information are being notified by the DLP tool.

**Comment by chrfox** [comment]
hi @katrakovic 
- Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.
