### ISSUE TITLE
Microsoft Security assessment was great, not anymore.

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#1725]
So much has been removed from the secure score that it has become really hard to perform the Microsoft Security assessment. Will you be updating the Microsoft Security assessment delivery kit to reflect changes? https://www.microsoft.com/microsoft-365/partners/security-assessment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a57c0a2-0a6c-4499-f31e-18016d006549
* Version Independent ID: 5587ca01-e40f-478d-1796-b7b4dc41cbf0
* Content: [Microsoft Secure Score - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/microsoft-secure-score?view=o365-worldwide#whats-new)
* Content Source: [microsoft-365/security/mtp/microsoft-secure-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/microsoft-secure-score.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by mypil** [comment]
@zlDev - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.


Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@levinec - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by levinec** [comment]
PM is investigating!

**Comment by erik-wahlstrom** [comment]
Thanks for the comment. While we will be updating public documentation and other tools, we do not yet have a committed date to update the Microsoft Security assessment delivery kit yet.

**Comment by xNiklasJern** [comment]
I can just add to this as well. Before it was a good indicator. but now more and more relevant information is removed from the tenant that it less and less attractive to use.
first Devices was removed, now data. soon there is nothing left to score
