### ISSUE TITLE
Clarification on Quarantine for High Confidence Phishing

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#1726]
There should be some clarification in the documentation that quarantine for high-confidence phishing goes to an admin quarantine and not user viewable quarantine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dc3925-c049-fd93-ac0a-d9c03e8bbdb4
* Version Independent ID: 6cb1a261-061b-366e-c7fb-9b5b0ad552bb
* Content: [Configure spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide#configure-end-user-spam-notifications)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
I'll need to think about this. While the topic doesn't mention phishing quarantine = visible to users; high confidence phishing = visible to admins, the description of the Quarantine action links off to topics that definitely talk about it.

**Comment by chrisda** [comment]
@dkotars, fixed and rationalized everywhere. What I found was, this topic was the only place where we got really specific about what end-users can do to their fishing messages.

Thanks for the feedback.

Closing
