### ISSUE TITLE
What permissions are needed to manual trigger investigation?

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/microsoft-365-docs#1727]
What permissions are needed to start investigation on sender or recipient?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e66cb3d-b771-af2b-860f-5355b2178db0
* Version Independent ID: 7ce9307c-ca00-cb47-6978-b9b09c139978
* Content: [Automated investigation and response (AIR) - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-air?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/office-365-air.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-air.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@pawp81 Thank you for your feedback. We have added a section which talks about required permissions (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-air?view=o365-worldwide#required-permissions-to-use-air-capabilities)


You need to be a - Global Administrator or a - Security Administrator to start an investigation.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @pawp81 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
