### ISSUE TITLE
Not possible to use due to wrong license

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/microsoft-365-docs#173]
"Microsoft 365 Business" plan, includes the Intune, so it can deploy the Office 365 Pro Plus desktop applications.
Only Office 365 Pro Plus, can be centraly deployed (GPO, Intune etc.) which is ok.

Howerver, this M365 Business license does not include license for Office 365 Pro Plus, instead it includes Office 365 Business edition.

So basically, users can deploy it, but can not activate the Office desktop applications.

Please check with product group / team and update the product info and documentation on how to deploy Office desktop apps in Microsoft 365 Business environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca7312a-c908-d32d-e1e3-3e9227300c67
* Version Independent ID: e2b941e6-9048-3be7-3d2b-3b59424b126b
* Content: [Automatically install or uninstall Office on Windows 10 devices](https://docs.microsoft.com/en-us/microsoft-365/business/auto-install-or-uninstall-office)
* Content Source: [microsoft-365/business/auto-install-or-uninstall-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/auto-install-or-uninstall-office.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
OK - so you can deploy from the M365B admin center as well as the Intune portal with Microsoft 365 Business license and the Office Business SKU.

**Comment by hkusulja** [comment]
This is not correct, and still the same issue.
Yes, I can deploy from Microsoft 365 Business admin center, as well as Intune portal.
However, the app that is deployed to windows10 computer is "Office 365 Pro Plus", which is not included in Microsoft 365 Business license, so user can not activate it.
Deployment is working, but wrong "thing" is deployed.

So, how can then user with Microsoft 365 Business license, active this deployed Office 365 Pro Plus? (error is, it should be only Office 365 Business desktop applications, which does not support intune or any central deployment)...
