### ISSUE TITLE
Where is it in the new Admin Center?

### ISSUE THREAD

**Issue by rpstester** [MicrosoftDocs/microsoft-365-docs#1730]
Please update step #1 to indicate where to find this setting in the "new" Microsoft 365 Admin Center, since there is no "Services & Add-ins" in it. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b13e4c14-5b0a-a4f6-1e65-7c79e49a0f10
* Version Independent ID: ec4223f2-8127-7605-07a0-306c4d412fed
* Content: [Turning Integrated Apps on or off - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/integrated-apps?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/misc/integrated-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/integrated-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@rpstester Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1807 to reflect the correct option. In the new admin center this is under Settings--> Settings-->Servives-->Integrated Apps.

Hope this Helps
Thanks
Sri

**Comment by mypil** [comment]
@rpstester - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/4c7bb049093bf5fee3c002e501429c3d7c41b6f0. 


Thank you for your contribution to make the docs better! Much appreciated!
