### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by secondsunrise** [MicrosoftDocs/microsoft-365-docs#1732]
At the very bottom of the page under the "Next steps" section, the URL for "Review and approve pending actions" starts off "https://review.docs.microsoft.com...". I think the correct URL should be "https://docs.microsoft.com/microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions" without the word "review" at the beginning of the URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95c4a4e9-d498-ff08-c084-3fc1c63506f9
* Version Independent ID: 44e7261a-64b7-4452-282f-a5b19103fa96
* Content: [View the results of an automated investigation in Microsoft 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/air-view-investigation-results?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/air-view-investigation-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/air-view-investigation-results.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@secondsunrise THANK YOU for telling us about this. Sorry for the inconvenience. I've fixed the link, and you'll see that update on the live site within the hour. Really appreciate you raising this. Thanks again!
