### ISSUE TITLE
404 – Page not found 

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1735]
For the section: Use PowerShell, see "Block apps that do not use modern authentication."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8cabb0-082b-0496-36cc-636e40135179
* Version Independent ID: adba3da4-6dc0-0907-bbf7-6b8e21de2d78
* Content: [Configure your Microsoft 365 tenant for increased security - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-wide-setup-for-increased-security?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-wide-setup-for-increased-security.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-wide-setup-for-increased-security.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@challengelogic - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/0e36fea0e07b357dd509ea8152ad0e2ed0eec123. 


Thank you for your contribution to make the docs better! Much appreciated!
