### ISSUE TITLE
Clarify Graph api security/securescorecontrolprofiles and security/secureScores for preview

### ISSUE THREAD

**Issue by christianarg** [MicrosoftDocs/microsoft-365-docs#1736]
Hi, the Graph api that shows information about secure score security/securescorecontrolprofiles and security/secureScores currently does not return data from the preview version (if we understood it correctly). We tried both with beta and v1.0 graph endpoints Please clarify how can we acces de preview programatically

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655194ea-3741-4039-ad60-cdf633fcec35
* Version Independent ID: 6b1877de-1a16-162a-d672-a5d71fb50c42
* Content: [What's coming in Microsoft Secure Score? - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/microsoft-secure-score-whats-coming?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/microsoft-secure-score-whats-coming.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/microsoft-secure-score-whats-coming.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by erik-wahlstrom** [comment]
Thanks for the question. There is work to make minor updates to the Graph APIs as we move forward with preview.  Unfortunately the UX and the API will not release synchronously. We will soon release a process to allow calling pre-release versions of the API on a separate endpoint.

**Comment by erik-wahlstrom** [comment]
Hi @christianarg , 
You are spot on about the new model and the lack of an API. It's something we're actively working on and we expect to make some announcements soon. In the mean time I can offer a little advice:
1) The current API will be available for an extended period, but will not be update
2) The update API will use the 0-10 based scoring

We are in the process of reaching out to our developer community.  If you'd like to be included please let me know.

--Erik

**Comment by christianarg** [comment]
hi @erik-wahlstrom ,

Thanks for taking your time to answer. When you say "the current API... will not be update" what do you mean? More specifically this is our concern:

1. A tenant (ex: one of our customers, we're CSP Parnter) gets updated to the new secure score
2. Customer completes one improvement action (ex: mfa for privilege roles)
3. The next day new secure score shows action as completed (10/10 points)
4. When we read the score from the current api /security/securescores will the improvement action return as completed??? In the example, mfa for privilege roles 50/50 ??? 

If that's not the case then our solution becomes effectively useless until you give us the new api (and we wasted hundreads of hours, at least until you give us the new api and we can fix our solution)

**Comment by erik-wahlstrom** [comment]
Hi @christianarg 

When I say "will not be updated" I mean that we will not be adding any new features. It will continue to work for new and existing tenants. The driver here is the new scoring model. In the old version there was no clear definition of max points. We made a breaking change to the scoring model to define the maximum possible points of any control. It will now be 10 points. 

However as you rightly point out the current API is not in sync with the UX. I have some thoughts on a work around but would rather discuss 1:1.

**Comment by erik-wahlstrom** [comment]
@christianarg, would love to talk. Can you please use the "feedback" button within the Microsoft Secure Score UX and we'll be in touch.

**Comment by christianarg** [comment]
@erik-wahlstrom Sorry I missed that last message. I'll contact you via the feedback button next week. Thanks in advance

**Comment by christianarg** [comment]
@erik-wahlstrom I used the feedback feature you mention last week but did not get any response.

**Comment by christianarg** [comment]
@erik-wahlstrom I'll insist one more time as you seemed to be willing to help but never got a response using the feedback feature.

**Comment by erik-wahlstrom** [comment]
Hi Christian,

Try firstname dot last name at microsoft.com

--Erik
