### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#1738]
proteciton

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32fd9ddd-5a5d-ab6a-b999-540a8f84614f
* Version Independent ID: d4bbbd4b-99d3-d7b5-e4b8-0ef63421bae2
* Content: [Overview of Office 365 Information Protection for GDPR - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-info-protection-for-gdpr-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/office-365-info-protection-for-gdpr-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-info-protection-for-gdpr-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@challengelogic  - Thank you for pointing this out.

PR #1752 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
