### ISSUE TITLE
Who can see the reports

### ISSUE THREAD

**Issue by Emmity** [MicrosoftDocs/microsoft-365-docs#1739]
Security Reader -role is not listed under "Who can see the reports", is it really so? The description for Security Reader -role is "Can read security information and reports in Azure AD and Office 365." so one would expect it to be able to see activity reports :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eaa6e98-66e9-aad3-2d67-543c22f4ce4b
* Version Independent ID: 26bddf9e-f338-329f-76e5-302a1343f7f1
* Content: [Activity Reports in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/activity-reports.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Emmity Thank you for your feedback. SEcurity reader doesn't have access to the reports section on the Microsoft 365 Admin center. The security reader role is allowed to view only sign in reports on the azure active directory - https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-sign-ins

Hope this helps!

Thanks
Sri

**Comment by UserAdminDEUS** [comment]
Y'all better fix my phone and put my IEM back on my phone before I
unsecured all of y'all

**Comment by mypil** [comment]
@Emmity - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba  so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
