### ISSUE TITLE
Mobile and Mail (iOS/mac) definitions?

### ISSUE THREAD

**Issue by Emmity** [MicrosoftDocs/microsoft-365-docs#1740]
Can you please open a bit the "Mobile" and "Mail (iOS/mac)" scopes? What do they exactly mean? Is "Mobile" only EAS-clients, or also other clients that use Modern Authentication? And does iOS Phone's native email app fall under "Mobile" or "Mail (iOS/mac)"? What about iPad's?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70e9c6c-8b88-9be4-5ce7-90338685ce95
* Version Independent ID: 755db873-a694-b50c-9478-eeb979dcf4cc
* Content: [Microsoft 365 Reports in the admin center - Email apps usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/email-apps-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/email-apps-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/email-apps-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by MaratMussabekov** [comment]
Hello @Emmity ,
**Mail(iOS/MAC) -** iOS/iPadOS/MacOS X native mail client
**Outlook (Mobile)** - Outlook for Mobile
**Mobile** - Any other EAS client

Also, the screenshot is outdaed, I will create a PR to replace it.

**Comment by MaratMussabekov** [comment]
Hello @Sirkkuw ,
it looks like I do not have the permission to create a PR here.
When I fork the repository I do not see the "Media" folder, where I need to replace the screenshot.
Original repository:
![image](https://user-images.githubusercontent.com/48041687/82008570-863ab580-9686-11ea-9366-20acb2a56764.png)
My fork:
![image](https://user-images.githubusercontent.com/48041687/82008595-95b9fe80-9686-11ea-8987-cd0287f1781b.png)

Could you please assist?
I need to change file c17b2a5c-db41-474a-8334-0e5a621b2f16.png to this one:
![image](https://user-images.githubusercontent.com/48041687/82008680-cd28ab00-9686-11ea-8692-b3d72117c20b.png)

Dear @mypil, for your information

Thank you

**Comment by MaratMussabekov** [comment]
Dear @Sirkkuw ,
thank you for uploading of the file, I added link to in the PR.

**Comment by yogkumgit** [comment]
@MaratMussabekov  Thank you very much for the contribution and updating the documentation with PR. @Emmity 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
