### ISSUE TITLE
Sold to and organisation address are same

### ISSUE THREAD

**Issue by mickday** [MicrosoftDocs/microsoft-365-docs#1741]
Change your Sold-To address is misleading, it infers that this is a separate entry when in fact this is exactly the same as changing the organisational address.  So it is not possible to have service name different from billing information.  So as a reseller I cannot have service in the name of end customer and invoices in a separate company name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50536931-a7c8-620a-aae0-9c4baec51f74
* Version Independent ID: 27ce5737-2b34-cb55-07b0-c8450c0e5d62
* Content: [Change your billing addresses](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@mickday Thank you for your feedback. The service name and the billing information will always be the same as the organizational address.  The reseller relationship works differently wherein you request the customer to add you as a partner of record/reseller through the below link.

https://support.microsoft.com/en-gb/office/partners-request-a-reseller-relationship-c0f2a4d0-bc61-4d8c-8696-fbb7eb1135df

Hope this helps!

Thanks
Sri

**Comment by mickday** [comment]
Thanks for the information, this is very useful.

Another question: Once I have reseller status with customer how do I transfer exiting services to be billed to me as reseller?

Thanks
Mick

**Comment by msbemba** [comment]
@mickday  Thank you for your feedback. It is usually done through the license reseller. I would recommend you to contact partner support for further assistance. @mypil  Can you provide details to contact support?

Thanks
Sri

**Comment by mypil** [comment]
@mickday - You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this issue can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.
