### ISSUE TITLE
Teams Organisation Switcher

### ISSUE THREAD

**Issue by Patrekees** [MicrosoftDocs/microsoft-365-docs#1743]
Changing the "Name" field in the organization information also changes the label that is visible when switching between organizations in the teams client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78b552c1-5a38-2a58-5ef9-3f9f3a324de6
* Version Independent ID: ffd9e488-bb85-365b-0a99-92525189341c
* Content: [Change your organization's address, technical contact, and more - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/change-address-contact-and-more?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/manage/change-address-contact-and-more.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/change-address-contact-and-more.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Patrekees Thank you for your feedback. We have added Teams to the list via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1808

Thanks again
Sri

**Comment by mypil** [comment]
@Patrekees - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/f91e81205e1ebfd8295cb5f7a1b9617043fbf19a. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by UnsnappedKhan8** [comment]
I got a shields and a message
heyo
