### ISSUE TITLE
Not correct

### ISSUE THREAD

**Issue by patrickvandenbulcke** [MicrosoftDocs/microsoft-365-docs#1747]
The pages states the 24/7 support is provided in English.
When this number is dialed for Tech support there is no English option, and I get the information that the offices are closed, so no 24/7, which is in contradiction with the information on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fad076-c736-dc9a-0d81-6ad22e95e009
* Version Independent ID: 31cb3c77-8da9-271e-8326-6f3002699d20
* Content: [Support information for Belgium - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/belgium?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/support/belgium.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/belgium.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@patrickvandenbulcke To help us investigate this issue, please send an email directly to me at cmcatee@microsoft.com and provide the following information (do not post this information here):

Country and Number being called:
Country and City of person calling to test:
Number tester is calling from:
Landline or Mobile Phone?
What Carrier does this number belong to?
Date and time of test call:
Exact details of errors or experience when calling:

**Comment by BerengarEnterprises** [comment]
I would like to confirm that this information is indeed incorrect. Both phone numbers provide a step by step menu, even stating "we've got more call than usual so waiting times might be higher".

Once every part of the menu has been followed through and "technical support" is selected an English voice states that the offices are now closed and asks to call back during business hours, 7am to 7pm CET. 

I want to add that the last time I called MS support (couple of months ago) there was 24/7 support available. This is highly annoying as I often work late hours or nights.

**Comment by cmcatee-MSFT** [comment]
@BerengarEnterprises We are currently investigating this issue. Please send an email directly to me at cmcatee@microsoft.com and provide the following information (do not post this information here):

Country and Number being called:
Country and City of person calling to test:
Number tester is calling from:
Landline or Mobile Phone?
What Carrier does this number belong to?
Date and time of test call:
Exact details of errors or experience when calling:

**Comment by mypil** [comment]
@patrickvandenbulcke @BerengarEnterprises - We will close this issue now. If you still have problems calling our support hotline and need help to troubleshoot your telephony issue, please send an email directly to  cmcatee@microsoft.com.

Thank you.
