### ISSUE TITLE
문구 수정 요청 합니다.-1122

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/microsoft-365-docs#175]
As-Is
다음 다이어그램은 관리자가 Microsoft 365 비즈니스를 설정 하는 방법을 설명 합니다. 
또한 Microsoft 365 비즈니스를 위한 Windows Pc를 준비 하는 단계를 설명 합니다. 
Windows 작업을 자동화할와 Microsoft 365 비즈니스 관리 센터에서 새 장치를 추가할 수도 있습니다. 
설정 및 사전 준비를 하 게 생산성 사용에 대 한 Microsoft 365 비즈니스 자격 증명을 사용 하 여 사용자가 로그인 하는 즉시 새 장치를 구성 하려면 작업을 자동화할을 사용할 수 있습니다.

To-Be
다음 다이어그램은 관리자가 Microsoft 365 비즈니스를 설정 하는 방법을 설명 합니다. 
또한 Microsoft 365 비즈니스를 위한 Windows PCs를 준비 하는 단계를 설명 합니다. 
Windows 작업을 자동화 할 Microsoft 365 비즈니스 관리 센터에서 새 장치를 추가할 수도 있습니다. 
새 장치를 구성 하기위해 설정 및 사전 준비를 하는 생산성 사용에 대한 Microsoft 365 비즈니스 자격 증명을 사용하여 사용자가 로그인 하는 즉시 
작업을 자동화 하여 사용할 수 있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: ab46e049-42d1-bf69-b71b-19e1e9116215
* Version Independent ID: 76d53a82-5778-9f45-6803-ee131ddcbe38
* Content: [Microsoft 365 Business 시작](https://docs.microsoft.com/ko-kr/microsoft-365/business/microsoft-365-business-overview?redirectSourcePath=%252farticle%252fget-started-with-microsoft-365-business-496e690b-b75d-4ff5-bf34-cc32905d0364)
* Content Source: [microsoft-365/business/microsoft-365-business-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/microsoft-365-business-overview.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
의견을 보내 주셔서 감사합니다. 이 문제를 해결하기 위해 번역 팀과 협력하고 있습니다.
