### ISSUE TITLE
data source not supported

### ISSUE THREAD

**Issue by adrwh** [MicrosoftDocs/microsoft-365-docs#1753]
When i try to connect to my Office365 tenant, i enter my Tenant ID, then i am told data source not supported. Connecting to data sources that require on premises gateway is currently not supported.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by adrwh** [comment]
closed.  The tenant ID should not include dashes.

**Comment by mypil** [comment]
@adrwh - Thank you for submitting feedback.

Based on your comment, you mentioned "closed", does this mean your issue has been resolved?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by adrwh** [comment]
Hi @mypil no problem.  In step 6, please update as follows or something similar.

## Original 
6. After clicking Connect, on the Connect to Microsoft 365 usage analytics screen, type in the tenant Id you copied in step (1) > Next.

## Updated
6. After clicking Connect, on the Connect to Microsoft 365 usage analytics screen, type in the tenant Id (removing the dashes "-" ) you copied in step (1)  > Next.

**Comment by mypil** [comment]
@adrwh - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/f9d9ddbe9da33cf5dbf712537f3a405b50401f67. 


Thank you for your contribution to make the docs better! Much appreciated!
