### ISSUE TITLE
Can't seem to control guest access

### ISSUE THREAD

**Issue by somedowntime** [MicrosoftDocs/microsoft-365-docs#1755]
I have set this all up and it seems to be working, except for controlling guest access.

I have sensitivity labels that prevent sharing, but when users create Teams/Groups with these labels, they can still share the team/group externally. Are there additional settings I need to change within Office 365 Groups? Or is this something that hasn't fully been implemented yet.

Sorry if I have missed this anywhere in the documentation!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by somedowntime** [comment]
I have done some additional testing, it would seem that the Microsoft Teams client is having the issue assigning the sensitivity label. The user can create the team, assign the label, but it doesn't seem to apply (the team is created without the label). If we assign the label to the Office 365 Group afterwards (the user **does** seem to be able to do it in SharePoint), then guest access is disabled. So this isn't so much a guest access thing, rather, a teams client issue?

If the user tries to use Teams to apply a sensitivity label **after** the Microsoft Team is created they get a "We're having trouble with updating your team. Please try again later." error.

Have I missed a configuration step here? or is it just because it is in Public Preview and it has some kinks to iron out?

**Comment by cabailey** [comment]
@somedowntime  I'm not aware of this issue so I recommend you open a support case for investigation.  If I learn anything that might explain/help with this issue, I'll update the thread.

**Comment by cabailey** [comment]
@somedowntime  I've had confirmation that asking Microsoft Support to investigate this is the right course of action.  If you share the ticket number here, we will follow up this end as well.

**Comment by somedowntime** [comment]
@cabailey thanks for this. I'm hopefully having a meeting with Microsoft FastTrack this week to discuss about implementing this. I'll update this when I have new information - especially if it is due to something I have configured.

**Comment by cabailey** [comment]
@somedowntime Thanks for the update.  Nothing missing in the documentation that we know of to explain this, so I'll close the issue but will monitor for any changes.
