### ISSUE TITLE
No Billing Frequency on page

### ISSUE THREAD

**Issue by lbradshaw27** [MicrosoftDocs/microsoft-365-docs#1757]
I don't see a Billing Frequency option:

Billing
Free trial subscription
Future payment method:
Visa ****#### Edit
 Your annual subscription will start when your free trial ends on August 24, 2020. You'll be charged 
$99.00 user/year, for 2 licenses.   Edit

When I select Edit, I see:

Recurring billing settings
Select a recurring billing setting for Microsoft 365 Apps for business Trial:

Recurring billing OFF:
Your subscription will expire on August 24, 2020.

Recurring billing ON:
Your subscription will be purchased on August 24, 2020 and will renew annually using the below payment method.

License quantity for your paid subscription 2

L****  Bradshaw **#### Exp. 0#/20##   Change

Submit

All I can do is change the payment method, not the billing frequency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d66f21-cff3-bb96-df38-6f67d95eb6cf
* Version Independent ID: 00256bad-f01c-02a6-9554-a0be1ce933ea
* Content: [Change your payment frequency](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-payment-frequency?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-payment-frequency.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-payment-frequency.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@lbradshaw27 You can't change the billing frequency while your subscription is a trial. After it moves to a paid subscription, then you'll be able to change it.

**Comment by Peter-CH-NZ** [comment]
I have a similar problem but I have a monthly subscription but can't find anywhere how to change this to yearly. I do NOT have a trial version. The Microsoft doc on this subject appears to be incorrect as I do not have an option to change to yearly (only to cancel the subscription).

**Comment by cmcatee-MSFT** [comment]
@Peter-CH-NZ Can you please send me the name of your domain in email (do not post it here): cmcatee@microsoft.com
Thanks!

**Comment by yogkumgit** [comment]
@cmcatee-MSFT  Kindly answer and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Thank you very much for sharing this explanation. @lbradshaw27 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by djmrky** [comment]
The edit billing frequency option is grayed out. How can I change this?

![image](https://user-images.githubusercontent.com/29006279/209734685-8d2c09bc-d52a-4d57-afd3-fb895b2a6ca6.png)
