### ISSUE TITLE
Does not match the UI in the tenant.

### ISSUE THREAD

**Issue by boomalator** [MicrosoftDocs/microsoft-365-docs#1758]
The steps to "remove a partner" do not match what is presented, which is only to to contact a reseller. There is nothing "greyed out".

In addittion, asking a customer to request permission of a reseller to no longer use that reseller is unacceptable.

I will attach a screenshot by email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 897c41b0-dbc7-d20f-38df-4fa682c35f6f
* Version Independent ID: a45c19e4-b070-afd1-084b-0f2c2b4b6c9c
* Content: [Add, change, or delete a subscription advisor partner - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/add-partner?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/add-partner.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/add-partner.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by MaratMussabekov** [comment]
Hello @boomalator ,
I just checked in my subscription (both old and new portal versions) and in **Settings > Partner relationships** page, there is no option to remove relationships (neither greyed out nor active). I can only see the option to delete partners from the subscription (as described [here](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/add-partner?view=o365-worldwide#delete-a-partner-from-a-subscription))
It looks like the information on the page is outdated.

Thank you

**Comment by yogkumgit** [comment]
@MaratMussabekov  Thank you very much for the contribution and updating the documentation with PR. @boomalator 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
