### ISSUE TITLE
Lync CNAME and SRV records for Teams only

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/microsoft-365-docs#1759]
Guys,

Please, someone could clarify if lync cname and srv records are necessary for a Teams only environment?

Thank you very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42d030-189c-a877-a431-f9c0d167414a
* Version Independent ID: 89079123-8860-ba7b-c707-5d4af1da59db
* Content: [Create DNS records at any DNS hosting provider - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@ingd  Thank you for your feedback. We have added a note  Via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1869. These records are required for dialing out and external communication etc.

Thanks
Sri

**Comment by ingd** [comment]
Hello @msbemba,

Thank you very much. You can close this case now.
