### ISSUE TITLE
Windows Pc 를 Windows PCs 로 변경 요청 합니다.

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/microsoft-365-docs#176]
Windows Pc 를 Windows PCs 로 변경 요청 합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: ab46e049-42d1-bf69-b71b-19e1e9116215
* Version Independent ID: 76d53a82-5778-9f45-6803-ee131ddcbe38
* Content: [Microsoft 365 Business 시작](https://docs.microsoft.com/ko-kr/microsoft-365/business/microsoft-365-business-overview?redirectSourcePath=%252farticle%252fget-started-with-microsoft-365-business-496e690b-b75d-4ff5-bf34-cc32905d0364)
* Content Source: [microsoft-365/business/microsoft-365-business-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/microsoft-365-business-overview.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
의견을 보내 주셔서 감사합니다. 이 문제를 해결하기 위해 번역 팀과 협력하고 있습니다.
