### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by JayPenney** [MicrosoftDocs/microsoft-365-docs#1762]
Please update this page as it is not current with Office 365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide#is-my-plan-eligible-for-office-365-extra-file-storage)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@JayPenney Can you please be more specific about which part is not current? Thanks.

**Comment by JayPenney** [comment]
Adding more space to SharePoint Office 365, the directions don’t apply anymore.

Jay Penney •  Network  Administrator
AYR FARMERS MUTUAL INSURANCE COMPANY
Toll Free: 1-800-265-8792 ext. 216
www.ayrmutual.com<http://www.ayrmutual.com/>

[Email Signature logo]

This e-mail message is confidential, for the exclusive use of the addressee, and its contents shall not constitute a commitment by Ayr Farmers Mutual Insurance Company, except as otherwise specifically provided in writing by Ayr Farmers Mutual Insurance Company. Any unauthorized disclosure, use or dissemination, either whole or partial, is prohibited. If you are not the intended recipient of the message, please notify the sender immediately.  Thank you.

**Comment by cmcatee-MSFT** [comment]
@JayPenney I need more information to troubleshoot this. Can you please provide the following information:
- Exact name of the subscription you're trying to add extra file storage to
- How you bought your subscription (from the web, through a CSP, or through volume licensing)

**Comment by JayPenney** [comment]
the new menu is up. I can find it now.
Under Billing -> Purchase Services -> select the account type we have - check the add-on's page
This now shows the per GB billing/month ($0.26/gb/month)

**Comment by cmcatee-MSFT** [comment]
Great! I'll close this thread, then. Thanks!
