### ISSUE TITLE
Permissions - which role groups?

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#1763]
Under the Permissions heading, steps are provided to grant permissions. Step 2 is "Create a role group on the Permissions page of the Security & Compliance Center." When creating a role group in S&C Compliance Center, one must specify at least one Role to assign to the Role Group, before choosing members. The procedure should specify which role(s) are relevant for DLP after step 2 and before the existing step 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide#permissions)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@robmacf - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/1f830ffc6d9f9557e1b342e04571bb4baf948d67. 


Thank you for your contribution to make the docs better! Much appreciated!
