### ISSUE TITLE
Senstivity Labels

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1765]
Please add some information about how files with Sensitivity labels are handled with encrypted email
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21613e57-8909-5adc-26ea-14e0a4771d3b
* Version Independent ID: dcd08c8d-4786-abbd-bd9d-47ad6d2117e6
* Content: [Email encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/email-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/email-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/email-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@MaratMussabekov Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DeanGross** [comment]
Thanks, but I'm not seeing anything on that page that describes what happens when an email is encrypted if the attachment is protected with a sensitivity label.  It would be helpful to know about scenarios like this.
