### ISSUE TITLE
Unannounced changes to billing statements?

### ISSUE THREAD

**Issue by testad** [MicrosoftDocs/microsoft-365-docs#1770]
All of a sudden, without  a notification in the message centre, we are receive billing notifications from "microsoft-noreply@microsoft.com" instead of "maccount@microsoft.com" for our UK tenant. The email is formatted differently, and most importantly, it does no longer include the attached invoice. This even though our "Receive billing statement as email attachment?" toggle is activated.

This is not acceptable as we need the email attachments to manage invoices effectively. For example, they are made available to people without access to the M365 portal (reducing the risk associated with multiple privileged accounts). We will not go to the portal to download every invoice separately to get them to the right stakeholders. It would be a complete waste of time. Please update the documentation with instructions on how to get the attachment included in the email.

Thanks for your support.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33f73374-3b86-fb8c-c80c-1cb60dc39c3c
* Version Independent ID: fe2c8b2f-2653-1b42-73dd-ebe22e085fe6
* Content: [Pay for your subscription](https://docs.microsoft.com/en-gb/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription?view=o365-worldwide#receive-a-copy-of-your-billing-statement-in-email)
* Content Source: [microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@testad Would you please send the email to me as an attachment so we can troubleshoot? Please send it directly to me at cmcatee@microsoft.com. Thanks!

**Comment by cmcatee-MSFT** [comment]
@testad Thanks for reporting this issue. The product team is investing this issue, so I'm going to close this. Thanks again!
