### ISSUE TITLE
Remove 5 minutes

### ISSUE THREAD

**Issue by eino-makitalo** [MicrosoftDocs/microsoft-365-docs#1772]
I removed domain with 2 users only and it takes more than 5 minutes. Dont estimate time if you cant keep a promise.  I can update to this ticket how long it takes with simple DNS records and 2 active users later. Now it has took over 20 minutes.  Your estimate is probably in some laboratory environment ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780db236-9235-2ce7-acbb-953fd997215b
* Version Independent ID: a5b80ea1-fb9f-d381-4fa6-7d4d8cce3f82
* Content: [Remove a domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/remove-a-domain?view=o365-worldwide#how-long-does-it-take-for-a-domain-to-be-removed)
* Content Source: [microsoft-365/admin/get-help-with-domains/remove-a-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/remove-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@eino-makitalo  Thank you for your feedback. The Time mentioned in the document is accurate in most cases. The delay Could be due to any other outages or Service incidents in the Geolocation or tenant.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@eino-makitalo - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
