### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Breaker119** [MicrosoftDocs/microsoft-365-docs#1774]
I have a user with Security & Compliance Center "Security Administrator" and they cannot view or manage Anti-Phish Policies. They are unauthorized for  Request: /api/antiphishpolicy

I am having this issue across the ATP landscape as is evidenced on the Threat Management Dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ea08aa-4520-8f48-93e2-0ce74cd43298
* Version Independent ID: 7be23d3d-f72b-abd3-e2c4-96ff3998a59b
* Content: [Configure ATP anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Breaker119, please open a support case. Security Administrator should work.

**Comment by mypil** [comment]
@Breaker119 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @chrisda so we will close this issue. You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Breaker119** [comment]
Actually no. It's still an issue. I know have an active support case. Case #:19793769


________________________________

**Comment by mypil** [comment]
@Breaker119 - Sorry to hear that you're having some technical issues. Please understand that this site is a product documentation site and not a support site. As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for technical support type issues. If you do find that it is a documentation error though, feel free to comment back and we'll gladly look into fixing it.  I hope this gets you pointed in the right direction. Thank you.

**Comment by Breaker119** [comment]
Yes thank you - fast was my point in creating the issue. Following the documentation precisely did not work. The permissions outlined do not provide free necessary access to the security dashboards.

Jason Heiser

________________________________
