### ISSUE TITLE
MailboxOwnerUPN is not in smtp format

### ISSUE THREAD

**Issue by madhavsankar** [MicrosoftDocs/microsoft-365-docs#1775]
MailboxOwnerUPN is in the format of Default-xyz@xyz-msonline-outlook-xyz.templateTenant. Why is it not displayed as an smtp address

**Comment by mypil** [comment]
@madhavsankar - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by madhavsankar** [comment]
https://docs.microsoft.com/en-us/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log?view=o365-worldwide
It reads that Mailbox Owner UPN is the email address of the person who owns the mailbox that was accessed. What is the format I'm receiving Default-xyz@xyz-msonline-outlook-xyz.templateTenant? Is this a valid email address?

**Comment by markjjo** [comment]
@madhavsankar I assume you're referring to an audit log record. If so, what audit log property are you referring to? What is the audit log record type? What is this operation? There might be other properties in the audit log record that helps to identify the mailbox.

**Comment by madhavsankar** [comment]
I'm referring to:
Property: MailboxOwnerUPN
Operation: MailboxLogin
I want to know what formats MailboxOwnerUPN can be in? I had assumed its the mail address of the mailbox owner, but doesnt that definition imply it has to be smtp address?

**Comment by markjjo** [comment]
@madhavsankar These values should be UPNs. If this isn't a user mailbox (e.g. group mailbox) or if it is in a state other than "active", that could be causing the email address format. Would suggest you open a ticket with MS Support to investigate.
