### ISSUE TITLE
Reported messages - receive reports

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/microsoft-365-docs#1778]
Hi,

It is immensely useful for a security team to receive immediate feedback on phishing scams reported by users. For the Report Message addin, documentation previously provided a very useful instruction on creating a forward rule. This allowed user reports to be sent directly to a security team's inbox for appropriate work.

However, we can see the below commit where this was all removed:

https://github.com/MicrosoftDocs/microsoft-365-docs/commit/222d9b1cf46b2bbd80221f1e6d6c38e4efc2227b#diff-b637e641bc6ae782742afe2304d58a62L129

Having previously implemented this feature, it still works and there are many blogs offering the above information as though it was still valid. I understand we can access this information manually by logging into the portal and clicking around but this is quite reactive, especially for an environment managing many different tenancies.

I can't see an obvious reason for removing this information, can request it either be put back, or provide some information about what should be done in its place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
The instructions were removed from this topic because they duplicated existing instructions in another topic. Originally, I eliminated the standalone topic and stashed the instructions in a different topic that I thought was more applicable, but I've brought the standalone topic back thanks to this issue:

https://docs.microsoft.com/microsoft-365/security/office-365-security/use-mail-flow-rules-to-see-what-your-users-are-reporting-to-microsoft

Thanks for the feedback.

Closing
