### ISSUE TITLE
Office 365 Compliance Manager DLP

### ISSUE THREAD

**Issue by katrakovic** [MicrosoftDocs/microsoft-365-docs#1779]
https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide

It would be helpful if you could explain what the difference is between high level of content detected and low level of content detected as can be seen in the section "Roll out DLP policies gradually with test mode". 

Thanks

**Comment by chrfox** [comment]
Hi @katrakovic 
Those are just the names of sample polices that were created for the purposes of illustration.
