### ISSUE TITLE
Auditing the use of Disposition Reviews

### ISSUE THREAD

**Issue by bloodytourists** [MicrosoftDocs/microsoft-365-docs#1780]
The document states that disposition actions are audited, and can  be found in the audit logs Could the documentation call out explicitly which Activities are generated in the logs around disposition. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d552f987-1606-01f7-d600-5887968ae60c
* Version Independent ID: 8c5f88de-93e7-862e-0550-fb9ac012be35
* Content: [Overview of disposition reviews - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/disposition-reviews?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/disposition-reviews.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bloodytourists: Noted.  This is something that's actively changing right now and when the engineering work is complete, I'll update the documentation to match. I'll close this thread for now, but I'll update it to alert you when the documentation includes this information.
