### ISSUE TITLE
Office apps - migration path

### ISSUE THREAD

**Issue by harryboyne** [MicrosoftDocs/microsoft-365-docs#1781]
Would it be possible to get some clarification on this document as to the migration path for Office 365 apps?

My understanding is that Office will automatically downgrade from 'Microsoft 365 Apps for enterprise' to 'Microsoft 365 Apps for business' - leaving no requirement for an uninstall/reinstall of Office.

However, this document doesn't make this clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655829e4-741a-dc96-35f9-2f3df4de2633
* Version Independent ID: f1c9dc75-d781-322c-1d74-8e0f39fafd1e
* Content: [Migrate to Microsoft 365 Business from Office 365 E3 - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/migrate-from-e3?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/business/migrate-from-e3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/migrate-from-e3.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@harryboyne  Thank you for your feedback. I'll check with the author and Keep you updated.

Thanks
Sri

**Comment by Hamspanner** [comment]
I guess there has been no response to this question.  I have the same question!  We have lots of clients on E plans that we want to migrate to 365 Business plans

**Comment by harryboyne** [comment]
I've spent time with the (MS) Technical Presales team and we're all in agreement that it's possible - it's just the documentation that needs to back it. We're starting to test with clients now.

These were the steps the PTC did to confirm this would work:

1.	Removed Office completely from the VM I was testing on, as to start fresh.
2.	Gave a user in my tenant an Office 365 E3 license.
3.	This user then went to portal.office.com and installed Office.
4.	Opened Office (Word, Excel and PowerPoint). Signed into Word, which was the first app I opened. This led to the user being signed in in all apps.
5.	Went back to the admin center, removed the E3 license and gave the same user an M365 Business Premium license.
6.	Went back to the VM, signed out of Office (File | Account | Sign Out). Signed back in with the same identity.
7.	Closed all Office apps and reopened these a few times.

Result: within a few minutes (approx. maybe 30), the Office subscription name changed from Apps for Enterprise to Apps for Business. The Inquire add-in was no longer available in Excel, which led me to believe that the SKU change was successful. Looking at control panel\add remove programs, I see it now says Office 365 Business.

**Comment by ryanharnwell** [comment]
This is a very common scenario and needs to be part of the documentation.

**Comment by msbemba** [comment]
Thank you, Everyone, for the feedback. We have modified the document with more information via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1985

Thanks
Sri

**Comment by mypil** [comment]
@harryboyne @Hamspanner - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/00c8ce48a1daa9195b2cf626e09330e94a2da106. 


Thank you for your contribution to make the docs better! Much appreciated!
