### ISSUE TITLE
Add example "Allow guest users for a specific group"

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/microsoft-365-docs#1782]
I would like to contribute an example to the cmdlet.
May somebody guide me how and where I can contribute?

I wanted to update a setting for a specific group based on this template:
[Block guest users from a specific group](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide#block-guest-users-from-a-specific-group). In contrary to this example I wanted to set `["AllowToAddGuests"]=$True` for a specific group.
However, I received the following error:
```powershell
PS C:\Users\<username>> New-AzureADObjectSetting -TargetType Groups -TargetObjectId $groupID -DirectorySetting $settingsCopy
New-AzureADObjectSetting : Error occurred while executing NewObjectSetting 
Code: Request_BadRequest
Message: A conflicting object with one or more of the specified property values is present in the directory.
At line:1 char:1
+ New-AzureADObjectSetting -TargetType Groups -TargetObjectId $groupID  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADObjectSetting], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.NewObjectSetting
```

I had previously applied a setting to this Azure AD group already. Therefore I had to adjust the present setting by the `Set-AzureADObjectSetting` cmdlet which required to retrieve the setting Id first.

As this may happen to other users, I'd like to contribute my code as an example:
```powershell
# Enter Group Name
$GroupName = "<GroupName>"

# Connect to Azure AD
Connect-AzureAD

# Lookup Azure AD group
Get-AzureADGroup -SearchString $GroupName

# Set AzureADObjectSetting to ["AllowToAddGuests"]=$True for Azure AD group
$template = Get-AzureADDirectorySettingTemplate | ? {$_.displayname -eq "Group.Unified.Guest"}
$settingsCopy = $template.CreateDirectorySetting()
$settingsCopy["AllowToAddGuests"]=$True
$groupID = (Get-AzureADGroup -SearchString $GroupName).ObjectId

# Check if there is already a present AzureADObjectSetting for that Azure AD group
Get-AzureADObjectSetting -TargetType Groups -TargetObjectI $groupID

# Get Id from present AzureADObjectSetting for that Azure AD group
$GroupsUnifedGuestId = (Get-AzureADObjectSetting -TargetType Groups -TargetObjectI $groupID).Id

# Set / Apply new AzureADObjectSetting from $settingsCopy to Azure AD group
Set-AzureADObjectSetting -TargetType Groups -TargetObjectId $groupID -Id $GroupsUnifedGuestId -DirectorySetting $settingsCopy

# Verify
(Get-AzureADObjectSetting -TargetType Groups -TargetObjectI $groupID).Values
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide#block-guest-users-from-a-specific-group)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
> I would like to contribute an example to the cmdlet. 
> May somebody guide me how and where I can contribute?

@Markus-Hanisch Markus, if you want to upload a contribution yourself, please read this readme at the repository's root [here](https://github.com/MicrosoftDocs/microsoft-365-docs)

**Comment by mypil** [comment]
@Markus-Hanisch  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
