### ISSUE TITLE
OneDrive for Business/SharePoint

### ISSUE THREAD

**Issue by 4DaddyT** [MicrosoftDocs/microsoft-365-docs#1784]
I see the licensing information above specifically states what is needed for mailboxes. What about what license is needed to place a OneDrive and SharePoint site on litigation hold?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24e97a56-f8f5-3725-cfda-954ec3ba71f6
* Version Independent ID: 0626a65e-d55d-48c7-90fe-1f982a18d729
* Content: [Get started with core eDiscovery cases in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-core-ediscovery?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/get-started-core-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-core-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@4DaddyT The same level of licensing is required for OD and SP. So E3 and higher or the appropriate add-on. I will update the article accordingly. See these licensing docs:

- https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

- https://docs.microsoft.com/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.xlsx

**Comment by markjjo** [comment]
@4DaddyT Looking at Billing > Subscriptions (look under Collaboration and communication) in the M365 admin center in my tenant (and the the security and compliance center service description that I linked to above) it looks like E1 + either SPO Plan 2 or OD Plan 2 would be the equivalent licensing to place an eDiscovery hold on sites. I'll update the topic.
