### ISSUE TITLE
Lab Guide Corrections

### ISSUE THREAD

**Issue by bignaaz** [MicrosoftDocs/microsoft-365-docs#1786]
Minor error in the Lab Kit 1909 lab guide v2 - 

On page 20, step 62 we are directed to "Enable automatic site-wide client push installation" and then on pages 23, 24, and 26 we are asked to "Install the Configuration Manager Client" using the Client Push Installation. 

The Client gets automatically installed on the VMs we create as a result of the setting on page 20. I do not think I missed anything so we may want to review the lab guide.

**Comment by mypil** [comment]
@bignaaz - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bignaaz** [comment]
Hi @mypil it is the Word document titled "Lab Kit_1909_lab guide_v2" inside the Windows and Office Deployment Lab Kit located here - https://www.microsoft.com/en-us/evalcenter/evaluate-lab-kit

**Comment by LauraWi** [comment]
Hi -- We've reported this issue to the marketing team that periodically updates this download so that it can be addressed when they next update.
