### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by RayJDM** [MicrosoftDocs/microsoft-365-docs#1787]
First link points to 27017 bacgrounder, while I think it should be 27018
"Learn about the benefits of ISO-Iec-27018 on the Microsoft Cloud: Download the ISO/IEC 27017 backgrounder"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99596e63-7347-8901-e5ff-d3c5a92f6233
* Version Independent ID: 80c3d750-f5a6-ec1c-731c-53858c143b23
* Content: [ISO/IEC 27018 Code of Practice for Protecting Personal Data in the Cloud - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-iso-27018?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-ISO-27018.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-ISO-27018.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@RayJDM - thanks for the feedback. We've actually just discontinued all the backgrounders for the compliance offering topics - they were basically just PDF copies of the online topics and they were frequently out-of-date as they needed manual updating. Please reference the online compliance offering topics for the most current information. Thanks!
