### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ceejey01** [MicrosoftDocs/microsoft-365-docs#1788]
I excluded a sharepoint site and group from my retention policy because I wanted to perform deletion but it took almost a week to successfully perform deletion. Please how long is the expected time for the retention holds to let go?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ceejey01 If I understand your question correctly, you configured a retention policy that included this SharePoint site and group, and then edited the policy to exclude them, and you want to know how quickly this change should take effect?  The delay here is replication latency for all endpoints to get the updated policy.  Usually it's fairly quick but can take several days.  When replication is complete you'll see the status of the retention policy in the Microsoft 365 compliance center change from "On (Pending)" to "On (Success)".
