### ISSUE TITLE
Native options in outlook on the web vs plugin

### ISSUE THREAD

**Issue by JamesSirdiifeld** [MicrosoftDocs/microsoft-365-docs#1790]
Apologies if this is not the correct place to post this, However i feel its not clear if we should be using the plugin across the board, IE Outlook client on Windows, Outlook mobile app and outlook on the web, Or if the native options within outlook on the web should be used rather than the plugin ?

Thanks

**Comment by UserAdminDEUS** [comment]
Agreed let it do all this work same way it was operating

😎😎😎😎😎

**Comment by mypil** [comment]
@JamesSirdiifeld - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@JamesSirdiifeld - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
