### ISSUE TITLE
OneDrive and OneDrive for Business Terms

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/microsoft-365-docs#1792]
Please consider updating the terminology to reflect that this applies to "OneDrive for Business" as it references "OneDrive". OneDrive generally refers to the personally consumer service rather than the Microsoft 365 products. This will help with consist terminology. For example it's referenced as OneDrive for Business here https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Get access to and back up a former user's data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@adrianwells Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/2009

Thanks
Sri

**Comment by adrianwells** [comment]
@msbemba Thank you. How does this relate to #1855 ? In that issue, there's discussion about the guidance on this maybe just being "OneDrive"? Thoughts?

**Comment by msbemba** [comment]
@adrianwells  I'm working with the author and will update you shortly.

**Comment by msbemba** [comment]
@adrianwells Sorry about the confusion. I have a new PR # https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1937 which will modify this document to reference Onedrive as Onedrive for business.

Thanks
Sri

**Comment by msbemba** [comment]
@adrianwells Once again thank you for the feedback. As you have seen the author mentioned that our context is M365 rather than home use,  Sp we've made sure all references on this page use "OneDrive", which also matches the current UI in the Microsoft 365 compliance center.


Thanks
Sri

**Comment by mypil** [comment]
@adrianwells - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
