### ISSUE TITLE
Verbiage Needs to Clearer for Account Type

### ISSUE THREAD

**Issue by karinjorge** [MicrosoftDocs/microsoft-365-docs#1793]
My customer has an O365 E5/G5 subscription but the default is not set to a year. The default is 90 days currently. When they read the statement in the first Note block, they were under the impression their default was 1 year but it's in fact only 90 days. "The default audit log retention policy only applies to audit records for activity performed by users who are assigned an Office 365 or Microsoft 365 E5 license or have a Microsoft 365 E5 Compliance add-on license. If you have non-E5 users in your organization, their corresponding audit records are retained for 90 days." I believe it CAN be set up to a year but it's not the default for O365 E5/G5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@karinjorge How is customer determining that 90 days is the default? If by the date picker in the audit log search UI in the SCC, that may not necessarily mean that 90 days is the audit log retention period. You might suggest they try running the Search-UnifiedAuditLog cmd in EXO PowerShell with a date range of one year. Also, in general, the new one-year retention period would be for events that occurred after Advanced Audit was released in Feb. 2020 

I assume that you are internal MSFT. Please contact me internally if you need more info.
