### ISSUE TITLE
Guide to always added Do not re-write for on-Premise Skype of Business link?

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/microsoft-365-docs#1794]
Are their current on-premise systems that should be added to ATP do not re-write?  Specifically Skype for Business, appears to break the experience for user of going direct from an Outlook Scheduled SfB Meeting link to the Desktop client before ATP.  After ATP changes the URL, it causes the web page to be triggered causing additional steps and clicks.  There should be a recommended set of defaults to added to the Do Not Re-write list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac84f75-b6d9-9495-873a-8f87b90b8034
* Version Independent ID: 18369495-0e0f-e3e1-6945-0200790fd107
* Content: [Set up a custom do-not-rewrite URLs list using ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@D-Jeffrey - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/78d1f20578eaa842ed8861199c96157020c40de8. 


Thank you for your contribution to make the docs better! Much appreciated!
