### ISSUE TITLE
Payment methods are not shared between admin

### ISSUE THREAD

**Issue by rickvanderzwet** [MicrosoftDocs/microsoft-365-docs#1798]
All items on Billing are shared between all admins, how-ever payment methods seems to be linked to a single user only. This is slightly confusing. 

"But you can only manage payment methods that you add." =&gt; "But you can only manage/use payment methods that you add." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14e33d-0d3e-45f4-fefe-dec3ae7d351f
* Version Independent ID: aeb53e2c-d35c-73fe-26f2-4f101bfeeea7
* Content: [Manage payment methods](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-payment-methods?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-payment-methods.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-payment-methods.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@rickvanderzwet Thank you for your feedback. We have made changes in the doc via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1870

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@rickvanderzwet The content has been updated to clarify who can use which payment methods and when.
