### ISSUE TITLE
Permissions procedure does not work

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#1799]
The procedure under the heading, "How to set permissions and roles in the Microsoft 365 compliance center" does not work. When one selects Permissions in Compliance Center, the page tells the user to go to Azure Active Directory or to Office 365. The documentation should be clear about where permissions need to be assigned: Azure AD or Office 365? And which permissions are needed to access Compliance Score.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f424cd-302d-5845-34fb-7b906bf7970c
* Version Independent ID: cfa50ebe-7ef1-de51-4456-a1212be9e7ec
* Content: [Microsoft Compliance Score setup - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score-setup?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/compliance-score-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-score-setup.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Hello, thanks for your note. We will look into this and get back to you, thanks.

**Comment by chvukosw** [comment]
Thank you  - we are clarifying the instructions, which should be published by the end of the day. Permissions will need to be set either in Azure AD or in Compliance Manager.
