### ISSUE TITLE
AzCopy switches out of date

### ISSUE THREAD

**Issue by amapleson** [MicrosoftDocs/microsoft-365-docs#1801]
Current version AzCopy does not support the switches mentioned in this article.
See: https://docs.microsoft.com/en-gb/azure/storage/common/storage-use-azcopy-blobs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86b2796-06fa-dfa7-bc0b-1a5760a396a0
* Version Independent ID: f9bfdc36-9c52-697f-f608-6e327d7c3c09
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@amapleson As per the note in the topic, only the version of AzCopy that can be download in the network upload wizard is supported. Currently, that is version 8.1.

"To import PST files using the network upload method and command syntax documented in this article, you must use the version of AzCopy that can be downloaded in step 6b in the following procedure. You can also download that same version of AzCopy from here. Using a different version of AzCopy isn't supported."

See github issues for similar issue:

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1009
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1015

Though unsupported, you could try this azcopy v10 syntax:

azcopy copy "SOURCE PATH OF PST" "SAS URL PROVIDED BY PST IMPORT TOOL" --check-length=false
