### ISSUE TITLE
Create alerts based on the content detected

### ISSUE THREAD

**Issue by rj192168** [MicrosoftDocs/microsoft-365-docs#1802]
if the attachment contains more than 200 email addresses. what is the best approach to create an alert and block the user from sharing the file to external users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rj192168 There are no content search/eDiscovery functionality that addresses your question. You could look into using Exchange transport rules (ETR) to prevent the message from being sent to external users, but not sure if there is a condition based on number of recipients. You might also be able to use DLP to prevent sensitive info from being sent but again not sure if you can base DLP being triggered based on number of recipients.

For more info:

ETR: https://docs.microsoft.com/en-us/Exchange/security-and-compliance/mail-flow-rules/mail-flow-rules

DLP: https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide

You can also create an alert policy (based on conditions and actions) but this only reactive; it will trigger an alert after the fact; it doesn't prevent email being sent. And not sure you can create a policy using the conditions you want to use: https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide

Hope this helps.
