### ISSUE TITLE
Step 6: Stop Auto-forwarding for email

### ISSUE THREAD

**Issue by neeksnz** [MicrosoftDocs/microsoft-365-docs#1803]
This step still refers to stopping auto-forward to external domains - yet, the rule itself would block ALL domains including internal. Refer issue 1377 from 2 months ago.
Also, the 'Setting' statement is incorrect for this step. It states in bold "Warn users before opening attachment of Office Files" This is incorrect. It should say something along the lines of "Reject Auto-Forward emails to external domains"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea79921a-7f83-58f1-c0a4-6eb0efce0d26
* Version Independent ID: b60110ef-71ad-9962-74de-734062708ff8
* Content: [Top 10 ways to secure Microsoft 365 for business plans - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@neeksnz  Thank you for your feedback. We have modified the doc via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1919

Thanks
Sri

**Comment by mypil** [comment]
@neeksnz - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/35619fe621711f219ab69649a5bef04d3c847815. 


Thank you for your contribution to make the docs better! Much appreciated!
