### ISSUE TITLE
OneDrive permissions

### ISSUE THREAD

**Issue by RayJDM** [MicrosoftDocs/microsoft-365-docs#1805]
Is there a requirement to be an admin of user OneDrive to set auto-labelling policy for OneDrive? Or should I use specific address?
I get an error message prompting me that I do not have required permissions (with global admin account).
Also - can you cover ALL OneDrive accounts or do you have to select those one-by-one ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@RayJDM  You can't select all OneDrive accounts in this early preview.  For your permissions error, it seems this is a known issue but please open a support ticket so it can be tracked and you'll be informed when it's fixed:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

**Comment by cabailey** [comment]
Closing because no issues with the documentation but I'll look to update when I hear the permissions issue is fixed.
