### ISSUE TITLE
Forms activity

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/microsoft-365-docs#1812]
Hello, I'd like to know if this report is related to the Microsoft Forms app only? Does it means "Report about the use of Microsoft Forms"? Or is it a report about forms created/responded with various tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc03c59-64a6-950b-adbd-bf5e1b5c59b3
* Version Independent ID: 7479ae58-d00e-e42d-39db-c4f029e32440
* Content: [Microsoft 365 Reports in the admin center - Forms activity - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/forms-activity?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/activity-reports/forms-activity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/forms-activity.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@FranNev Thank you for your feedback. The reports provide information about the activity of every user licensed to use Microsoft Forms by looking at their interaction with forms Including usage of forms in various other tools within Office365.

Thanks
Sri

**Comment by FranNev** [comment]
Hello @msbemba, thanks for your answer, it will help me a lot!
Have a nice day.

Best regards,
François
