### ISSUE TITLE
task-based access

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/microsoft-365-docs#1813]
Hello, what is a "task-based access", exactly?
"policies that provide additional security for task-based access to data and configuration settings for your organization" sounds a bit heavy, "policies that provide additional security for access to the data and configuration settings of your organization" could not fit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 726d7d3e-c8eb-c4c9-baf8-212b02cb0330
* Version Independent ID: 9f0a95bf-62a8-c981-4ce0-c1ec0ef824b8
* Content: [Step 7: Configure privileged access management - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/infoprotect-configure-privileged-access-management?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/infoprotect-configure-privileged-access-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/infoprotect-configure-privileged-access-management.md)
* Service: **o365-solutions**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@FranNev - thanks for the feedback. Task-based access is a differentiation from role-based access and is specific to privileged access management (as opposed to Azure AD Privileged Identity Management). Basically, it is access centered on completely specific tasks versus access centered on what role you’re assigned. I’ll look at trying to make that clearer here, please also refer to the explanation in the Privileged Access Management topic (https://docs.microsoft.com/microsoft-365/compliance/privileged-access-management-overview#layers-of-protection).

**Comment by FranNev** [comment]
Thanks a lot @robmazz ! Sorry if I'm bothering you, but I have a question regarding the page you mentioned. I wonder if this "Privileged access management" is just a specific type of access management among others, or if it's the name of a Microsoft solution? Because [if you look the definition here](https://www.microsoft.com/en-us/language/Search?&searchTerm=Privileged%20access%20management&langID=303&Source=true&productid=undefined), it's a bit confusing.
