### ISSUE TITLE
Link to Attestation

### ISSUE THREAD

**Issue by Lorenbain** [MicrosoftDocs/microsoft-365-docs#1815]
Azure PCI DSS Attestation of Compliance (AoC) link doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b95bd5-5663-90ab-f902-bab7887e4489
* Version Independent ID: 28d8c81c-5e29-b300-5b23-137e9692940e
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-pci-dss?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-PCI-DSS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by joinimran** [comment]
@Lorenbain - Thank you for your feedback. I have checked and confirmed that the link is working fine and pointing to https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide?command=Download&downloadType=Document&downloadId=425af30f-1236-41bc-b45c-98a52ee84c28&docTab=4ce99610-c9c0-11e7-8c2c-f908a777fa4d_PCI_DSS which is the correct resource.

From there, please click on Azure PCI DSS 3.2.1 AOC Package.zip to download the documents. 
![image](https://user-images.githubusercontent.com/47118050/81590386-29b06f80-93d4-11ea-8912-ddd880c672e3.png)

Thanks
Imran

@mypil FYI Please.

**Comment by mypil** [comment]
@Lorenbain - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @joinimran  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
