### ISSUE TITLE
Owners vs Members

### ISSUE THREAD

**Issue by adamfowlerit** [MicrosoftDocs/microsoft-365-docs#1819]
As someone can be a member, or owner, or both, it would be good to clarify if owners get all the permissions of a member or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@adamfowlerit  Thank you for your feedback.  I have now clarified via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1871

Thanks
Sri

**Comment by mypil** [comment]
@adamfowlerit - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author based on this https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1871#issuecomment-634072500 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
