### ISSUE TITLE
Time to update

### ISSUE THREAD

**Issue by richard-bf1** [MicrosoftDocs/microsoft-365-docs#1820]
Hi, how long should this take to take effect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?redirectSourcePath=%252fen-us%252farticle%252fmanage-who-can-create-office-365-groups-4c46c8cb-17d0-44b5-9776-005fced8e618&view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@richard-bf1 Thank you for your feedback. I tested this and it takes around 30 minutes for the changes to take effect. I have added a note to the document on the same via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1872

Thanks
Sri

**Comment by mypil** [comment]
@richard-bf1 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/26225b5ff1eb7c3a6b679cd49c7555166a4549ae. 


Thank you for your contribution to make the docs better! Much appreciated!
