### ISSUE TITLE
Step 5

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/microsoft-365-docs#1824]
When you read documentation regarding -Purge parameter in her: https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-content-search/new-compliancesearchaction?view=exchange-ps 
you'll find out that it will remove only 10 items at a time :(
Please do not deprecate Search-Mailbox functionality with it's fantastic -DumpsterOnly parameter :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the cloud mailbox on hold Recoverable Items folder - Admin Help - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide#step-3-remove-all-holds-from-the-mailbox)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@uz-it Please post a comment or vote here: https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/39431878-keep-search-mailbox
