### ISSUE TITLE
Alert activity counts/pending review

### ISSUE THREAD

**Issue by nanoonan538** [MicrosoftDocs/microsoft-365-docs#1825]
Customers have requested that the documentation also clarify how the "activities" and the 
pending/resolved items" are counted to clarify metrics/measurements (e.g. per item/row/attachment).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea1461c-a9db-d934-d5a6-169360842e8b
* Version Independent ID: 6b214386-6f18-9de6-7a8b-b78e69d1387a
* Content: [Communication compliance feature reference - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-feature-reference?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/communication-compliance-feature-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-feature-reference.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@nanoonan538 - thanks for the feedback. I'll include this feedback with our documentation updates included with upcoming feature enhancements this month. Thanks!
