### ISSUE TITLE
Group by family/conversation

### ISSUE THREAD

**Issue by nanoonan538** [MicrosoftDocs/microsoft-365-docs#1826]
customers are requesting more detail on the "Group by family/conversation" feature provided - which appears to enable expanding/collapsing the view

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685ef016-8eaf-a40d-73af-0fc28e072e41
* Version Independent ID: 8fbf5517-d2bc-12eb-79d0-8209130e29ec
* Content: [Investigate and remediate communication compliance alerts - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-investigate-remediate?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance-investigate-remediate.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-investigate-remediate.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@nanoonan538 - thanks for the feedback. I'll include this feedback with our documentation updates included with upcoming feature enhancements this month. Thanks!
