### ISSUE TITLE
Allow policy example is not correct

### ISSUE THREAD

**Issue by ZeyuanLi16** [MicrosoftDocs/microsoft-365-docs#1827]
The allow policy example should allow the segment to talk to itself. Add "AssignedSegment" into "SegmentsAllowed". Otherwise: 

New-InformationBarrierPolicy -Name "TestLegal" -AssignedSegment "Legal" -SegmentsAllowed "Client" -State inactive
&gt;&gt;
Your request failed to complete. Please retry. Error Details: Microsoft.Exchange.Management.Tasks.SegmentCannotCommunicateWithItselfException,Segment xxxxx associated with this policy will not be able to communicate with itself. Please correct the SegmentsAllowed or SegmentsBlocked parameter.

But after I setup allow policy like following:
1. Legal allows -&gt; Legal, Client
2. Client allows -&gt; Legal, Client

I got the policy is not symmetric error when I try to start the policyapp. Any idea what is the correct way to set up allow policy? Like in my case, I want to try set Legal and Client only talk to each other. Thanks!
 
PS C:\windows\system32&gt; Start-InformationBarrierPoliciesApplication
Your request failed to complete. Please retry. Error Details: Microsoft.Exchange.Management.Tasks.AsymmetricPoliciesException,IB Policies are not
symmetric. Please ensure that the policies are defined two-ways. For example, if there is a policy where Segment1 cannot communicate with Segment2,
then there must be another policy where Segment2 cannot communicate with Segment1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by get-itips** [comment]
Please see https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1835

**Comment by chrfox** [comment]
PR with fix merged
