### ISSUE TITLE
How often does retention look for data that needs to be removed?

### ISSUE THREAD

**Issue by jreyes4949** [MicrosoftDocs/microsoft-365-docs#1830]
If a retention label or policy is applied to a file that that has exceeded it's retention period and is set to be deleted, will the data be immediately sent to recycle bin or is there a period between where retention refreshes across a tenant service (e.g. onedrive, SPO) and then deletes data? is there a set interval of time when retention policies/label actually perform the deletions? (e.g. hourly, daily, weekly)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@jreyes4949  How retention works for SharePoint and OneDrive is documented here, with just a few differences for labels vs retention policies: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#content-in-onedrive-accounts-and-sharepoint-sites

We're looking at restructuring this documentation so the information is easier to find and you can learn about retention all-up and the differences between retention labels and retention policies. But until then, you can use this section to understand what's going on under the covers when the retention period has expired.

**Comment by jreyes4949** [comment]
@cabailey thanks for quick reply.  I guess my questions is around this specific step "If the content is not deleted during the retention period: At the end of the retention period, the document is moved to the first-stage Recycle Bin." and if the data is moved to recycle bin exactly when retention period ends or if there is a scheduled job that does the clean up and how often that occurs. do i need to ask that on the page you referenced?

**Comment by cabailey** [comment]
@jreyes4949  So you want to know if this happens immediately "on the clock" or as a recurring task - OK, will ask.  But curious why you're asking this level of granularity.  What would you do differently, for example?

**Comment by jreyes4949** [comment]
the reason i ask is because i'm working with retention labels. I have a label that essentially says "purge data last modified date > 7 days". on my first test it took about 5 days for the system to move the files i tagged to recycle bin. I then tagged more files for testing almost two weeks ago that have not been moved to recycle bin yet. I'm wondering if there is a cleanup job that runs at specific intervals and checks for data that needs to be deleted. I'm certain that there is no other retention policy/tag applied to my test data. I'm likely going to open a ticket with MS to see if they can help answer this as well.

![Screen Shot 2020-05-07 at 3 23 12 PM](https://user-images.githubusercontent.com/64169142/81350394-ad85f700-9076-11ea-8d44-dc2c10763646.png)

**Comment by cabailey** [comment]
@jreyes4949  Did you get an answer from Support?  It's the "timer job" documented as running "periodically" and for SharePoint/OneDrive it can take up to 7 days.  So, worst case scenario, 7 days for content to be deleted after the retention period expires.  I'm looking to make this clarification in the docs now.
