### ISSUE TITLE
About Azure AD Free

### ISSUE THREAD

**Issue by N4M4** [MicrosoftDocs/microsoft-365-docs#1831]
Hi, I have Azure AD Free license, can i execute this script? and what happened with the groups previously created by the users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@N4M4  Thank you for your feedback. As mentioned in the document you need Azure Ad premium license to be able to restrict using the script. For the other question, the groups that previously created are not impacted by the new restrictions in place.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@N4M4 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
