### ISSUE TITLE
Limitations of the connector

### ISSUE THREAD

**Issue by musiq787** [MicrosoftDocs/microsoft-365-docs#1832]
Hi team,

After working with Bloomberg to get the SFTP site set up, it appears that the Bloomberg connector has a daily import limit which is preventing my organisation from being able to archive data into O365. Error messages are as follows:

Error Message: Received more items 1078372 than supported limit (100000), push is throttled and will be delayed. 

We get this error every day and no data gets archived into O365. After raising 2 tickets with MS support I have been told that this limitation cannot be changed, which means that this connector is useless. Can you please expand this documentation to cover the limitations of the connector, any alternatives available and how the connector actually works. The daily exports from Bloomberg to the SFTP site generate several att, msg, ib and dscl files. From this documentation, customers don't have much information about which files are targeted for import and in what order they are performed. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b000c65c-3d18-7bb2-9379-732f3655add6
* Version Independent ID: f8069a1d-8652-9b1b-8d57-1d02949ebc0f
* Content: [Set up a connector to archive Instant Bloomberg data - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/archive-instant-bloomberg-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/archive-instant-bloomberg-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/archive-instant-bloomberg-data.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@musiq787 I've forwarded your issue to engineering team about additional documentation. I'll respond when/if there is more info about this.

**Comment by markjjo** [comment]
@music727 As per what you cited about the cases you opened with MS Support, 100K items per day is the limit, which is a limit in the ingestion pipeline. At this time, there are no alternative workarounds. Here's a list of the type of Instant Bloomberg items/elements that may be ingested to O365. I assume an instance of one of these types would be considered "an item" and there can be one or more of these per chat/conversation. You can probably assume that all of these content types are ingested by the connector.  We'll look into adding this to the documentation.

Attachment: Represents each unique file uploaded to a given conversation or chat room
Conversation:  Represents a given conversation or chat session
History: Represents every time that a user requests to view the historical transcript for a given conversation session or chat room
Invite: Represents an instance when a user initiated a given conversation session as well as all users that were invited to participate
Message: Represents each unique entry within the given conversation session or chat room
ParticipantEntered: Represent a user that just entered the given conversation session or chat room
ParticipantLeft: Represents a user that just left the given conversation session or chat room
SystemMessage:  Represents programmatic content within the given conversation session or chat room

**Comment by music727** [comment]
@musiq787 I believe the above reply was meant for you. 

Kind regards,
Milda

**Comment by musiq787** [comment]
Thanks guys. This means that companies should not make investments on O365 Compliance products. Features like Advanced eDiscovery & Communications Compliance are rendered useless if customers wish to unify their data from all sources to meet governance standards.. and all this because a connector like Bloomberg's has an import limit. Complete nonsense.

**Comment by markjjo** [comment]
@musiq787 Would suggest you provide this feedback to engineering team at https://office365.uservoice.com/forums/289138-office-365-security-compliance
