### ISSUE TITLE
Autopilot Hybrid Domain Join and Group Policy

### ISSUE THREAD

**Issue by akb0ss** [MicrosoftDocs/microsoft-365-docs#1833]
Hello,
is autopilot hybrid domain join supported and can we deploy on-prem group policies to the clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed7e43-7ec8-01f6-8cf0-6fd77519840e
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business Premium frequently asked questions  - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by MaratMussabekov** [comment]
Hello @akb0ss ,
**is autopilot hybrid domain join supported** - yes, more details are [here](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/user-driven#user-driven-mode-for-hybrid-azure-active-directory-join)
**can we deploy on-prem group policies to the clients** - no, you cannot do it using autopilot. To deploy on-prem group policies you need client PC to be able to access a domain controller to download GPO
Thank you

**Comment by mypil** [comment]
@akb0ss - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
