### ISSUE TITLE
No notification but email for Teams generated groups

### ISSUE THREAD

**Issue by FlorianRD** [MicrosoftDocs/microsoft-365-docs#1834]
I received emails for my soon to expire groups but they had been created via Teams.
I did not receive a notification in Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3e13d66-a454-b0d6-fdea-c50d9904a71e
* Version Independent ID: 4632edc1-4a14-6a74-669f-0cf9d208770b
* Content: [Groups expiration policy - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by mypil** [comment]
@FlorianRD - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
