### ISSUE TITLE
Allow policy powershell command is incomplete

### ISSUE THREAD

**Issue by alexthedude66** [MicrosoftDocs/microsoft-365-docs#1835]
When I create a policy to allow one department to communicate with another department only the command specified in this article is incomplete.

If I run this command below indicated in the article that creates a policy so that Manufacturing can only talk to HR

New-InformationBarrierPolicy -Name "Manufacturing-HR" -AssignedSegment "Manufacturing" -SegmentsAllowed "HR" -State Inactive

I get the following error:

Your request failed to complete. Please retry. Error Details: Microsoft.Exchange.Management.Tasks.SegmentCannotCommunicateWithItselfException,Segment 0aae9afc-8b4d-411e-9566-599fed800fb3 associated with this policy will not be able to communicate with 
itself. Please correct the SegmentsAllowed or SegmentsBlocked parameter.
Status: ProtocolError
Status code: InternalServerError (500)

In order to run the command successfully I have to add the Manufacturing segment among the SegmentsAllowed to be able to communicate with itself.
So the correct command in this case would be:

New-InformationBarrierPolicy -Name "Manufacturing-HR" -AssignedSegment "Manufacturing" -SegmentsAllowed "HR","Manufacturing" -State Inactive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by get-itips** [comment]
Hello @alexthedude66 
Thanks for reporting.
I could reproduce, expect an article update soon.

**Comment by mypil** [comment]
@alexthedude66 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/11cd176b7fbb49955e75bb3b69aa5042ddc86762. 


Thank you for your contribution to make the docs better! Much appreciated!
