### ISSUE TITLE
"One-way" Allow Policy doesn't work

### ISSUE THREAD

**Issue by alexthedude66** [MicrosoftDocs/microsoft-365-docs#1837]
Hi,

As far as I understand I should be able to create an allow policy (just as in your example above called Plan 3) 

However when I run the following commands and try to apply the policy I get the below error

New-OrganizationSegment -Name "Marketing_Segment" -UserGroupFilter "Department -eq 'Marketing'"

New-OrganizationSegment -Name "Research_Segment" -UserGroupFilter "Department -eq 'Research'"

New-InformationBarrierPolicy -Name "Marketing-Research_Only" -AssignedSegment "Marketing_Segment" -SegmentsAllowed "Research_Segment","Marketing_Segment" -State Active

 Start-InformationBarrierPoliciesApplication

Your request failed to complete. Please retry. Error Details: Microsoft.Exchange.Management.Tasks.AsymmetricPoliciesException,IB Policies are not symmetric. Please ensure that the policies are defined two-ways. For example, if there is a policy where
Segment1 cannot communicate with Segment2, then there must be another policy where Segment2 cannot communicate with Segment1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by get-itips** [comment]
Hello @alexthedude66 
To see if we need to update the article, tried to reproduce however I could not reproduce.
I ran the same cmdlets as you and I did not receive any error and could Start the IB.

**Comment by dewaltk** [comment]
I get the same issue, with block policies I have bi-directional policies and they work fine. With allow I only have one policy to allow communication from segment 1 to itself and segment 2.

**Comment by chrfox** [comment]
Hi @alexthedude66 

- Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.
