### ISSUE TITLE
Confusing instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1838]
I do not see anything on the Rules page about "Modify the Message Security" The above instructions are not accurate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe08d5e-4870-331e-b5f2-92848b5211b0
* Version Independent ID: 60ed3095-a42c-1bcb-f2fa-8325cfcd03f6
* Content: [Set up new Message Encryption capabilities - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-new-message-encryption-capabilities?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-new-message-encryption-capabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-new-message-encryption-capabilities.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@DeanGross  Thank you for your feedback. I was able to test and the Instructions are accurate. The instructions on this document are to update an existing rule. If you are looking for the option under a new rule, then you will need to follow the steps mentioned in  https://docs.microsoft.com/en-us/microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email?view=o365-worldwide

Hope this helps!
Thanks
Sri

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
