### ISSUE TITLE
Outdated info

### ISSUE THREAD

**Issue by analogitguy** [MicrosoftDocs/microsoft-365-docs#1839]
You are missing the period at the end of the cname instructions (enterpriseenrollment-s.manage.microsoft.com)

But more importantly the Network Solutions interface has been updated and during the CNAME instructions you are no longer able to leave the "Refers to hostname" selection blank or on select.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c6bbf8-c699-5317-5751-339dd499f8d7
* Version Independent ID: 20b3d64a-ef3e-da1f-a0b1-7bcb54acfeb2
* Content: [Create DNS records at Network Solutions for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-network-solutions?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-network-solutions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-network-solutions.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by analogitguy** [comment]
Another note is that each set of instructions does not take into account that the directions above it have been followed, so the screenshots all show no records. In reality you will have just added the other records. The biggest issue with this is the SPF records section. To verify your domain you will have already added a TXT record. Should you then erase and add the SPF record? The instructions say to combine records if something already exists... what does that even mean?

**Comment by msbemba** [comment]
@analogitguy Thank you for your feedback. We have added a reference to the document to Stating that the records should "This value MUST end with a period (.)" instead of explicitly mentioning it only for Cname. the other request to update SPF records has been changed in the document. The combine records mean to add the required Microsoft values to the current record so that you have a single SPF record that includes both sets of values. This has been modified as well.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @analogitguy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
