### ISSUE TITLE
Typo in the "Authentication-results message header fields used by Microsoft email authentication" section

### ISSUE THREAD

**Issue by kjssig** [MicrosoftDocs/microsoft-365-docs#1840]
I believe under the dmarc results bullets in this section, the last bullet for "none" should refer to DMARC TXT instead of DKIM TXT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@kjssig - Thank you for pointing this out.

PR #1862 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
