### ISSUE TITLE
Graph API alternative?!

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/microsoft-365-docs#1841]
Can you provide an actual link to the supposed Graph API replacements for the *-MailboxSearch cmdlets? As per the below text from the FAQ?

We use Copy Search to export email messages or instant Messages for purposes other eDiscovery and legal investigations. What other options do we have after these cmdlets are retired?

The Microsoft Graph APIs provide a number of methods for extracting data for analysis and other purposes that are far more resilient and scalable than the using the *-MailboxSearch cmdlets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b8bac8-ffc4-8c4c-2d59-f27a96dbd414
* Version Independent ID: b78fa02e-9ae3-fa72-e23a-f70cf96d2e0f
* Content: [Retirement of legacy eDiscovery tools - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement?view=o365-worldwide#-mailboxsearch-cmdlets)
* Content Source: [microsoft-365/compliance/legacy-ediscovery-retirement.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/legacy-ediscovery-retirement.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@michevnew eDiscovery PM suggested these two URLs:

- https://developer.microsoft.com/en-us/graph/
- https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

**Comment by michevnew** [comment]
I'm sorry but those are again just generic links. You can add a link to Google and it wont be any less vague. Can you provide the actual endpoints? And if none exists (because afaik that is indeed the case), can you update the FAQ correspondingly?
