### ISSUE TITLE
Teams_HasOtherAction metric: possible add more details?

### ISSUE THREAD

**Issue by bartbilliet** [MicrosoftDocs/microsoft-365-docs#1842]
The description of "Teams_HasOtherAction" is listed as "Boolean value if the user performed 'other actions' in Microsoft Teams."
Would it be possible to describe in a little more detail what is contained in "other actions"? 
Is this talking about Likes, Saved Messages, Reads/Views, sign-ins, ...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de44679b-998b-3de8-292b-d2993af9bad9
* Version Independent ID: 7fd9ecf7-0468-d01e-dcca-d18a19ebb7c2
* Content: [Microsoft 365 usage analytics data model - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics-data-model?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics-data-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics-data-model.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by bartbilliet** [comment]
@Sirkkuw can you help here? Thank you! :)

**Comment by msbemba** [comment]
@bartbilliet  Thank you for the feedback. I'm discussing this with the author internally and will update you shortly.

Thanks
Sri

**Comment by bartbilliet** [comment]
@msbemba Kindly checking in to see if you could already share something on this? Thanks you!

**Comment by msbemba** [comment]
@bartbilliet There has been an ongoing discussion on this. Rest assured you will have an update shortly.

Thanks
Sri

**Comment by Sirkkuw** [comment]
According to the product group:
Yes it contains all the other actions a user could perform in the Teams client.

**Comment by bartbilliet** [comment]
@Sirkkuw hehe, I get that. But could you list some examples of what these types of actions include? 
When we add "OtherActions" to our stats, the usage increase by 100% compared to the total of all other named actions (ChatMessages, ChannelMessage, CallParticipate, MeetingParticipate). So we are eager to understand which type of actions "other actions" include, and if these actions are relevant to consider real usage of the product, or if it only means the user signed in to the app without doing anything.

**Comment by Sirkkuw** [comment]
@bartbilliet  - sending the question back to product group.

**Comment by Sirkkuw** [comment]
I got this from PG
in the Teams user activity report, the definition of metric "Other activity" should be: the user is considered active but has a zero value for the Chat Messages, 1:1 calls, Channel Messages, Total Meetings, and Meetings organized. Examples actions are when the Microsoft Teams client is activated to the foreground, actions were taken in the compose message area, toasts appeared in the Microsoft Teams client, banners were shown in the Microsoft Teams client, and many more.

**Comment by Sirkkuw** [comment]
I got this clarification: the User is considered active but has a zero value for the Chat Messages, 1:1 calls, Channel Messages, Total Meetings, and Meetings organized metric values. Examples actions are when a user opens a Channel Message post but does not reply or when a Private message is received and it is read but not responded to.

**Comment by msbemba** [comment]
@Sirkkuw Thank you for getting us that information from PG.

@bartbilliet I have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2514 

Thanks
Sri

**Comment by bartbilliet** [comment]
Thanks @Sirkkuw @msbemba appreciate! :)

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @bartbilliet Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by NeilMcC-1** [comment]
I appreciate this issue is marked as closed but I'd like to re-iterate the usefulness of having a breakdown and understanding of what contributes to the HasOtherAction metric. We're a large EDU tenant and student use of Teams jumps roughly 3:1 when including HasOtherAction over existing HasTeamsActivity. In particular, we're trying to identify where Teams is being used at a depth that indicates educational use - things like Assignments, Class Notebook, Uploading files etc. We'd also like to differentiate users that are coming to Teams and only having superficial engagement - logging in, reading but not posting, viewing files but not contributing etc. Current metrics don't allow this and HasOtherAction is presumably a catch all for all non-message/meeting activity so the stats are hiding the real story.
