### ISSUE TITLE
No clear ways for Developers and Organizations to be alerted of blocks or reviews

### ISSUE THREAD

**Issue by r-wink** [MicrosoftDocs/microsoft-365-docs#1843]
Presently, our customers are experiencing blocks due to false positives or an issue with a file located on our platform -- we have no insight or ability to mark as a false positive directly as we do not use 365 protection ourselves.

There needs to be an easy way to alert domain owners and companies on perceived issues so they can proactively get ahead of it.

Google Search console offers such functionality (though an API would be better so we can consume the alerts/issues), while Microsoft doesn't or doesn't make it obvious for a non 365 using company to remediate easily.

Please provide documentation (and functionality) which explains this process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a21caf6-05ad-6226-59ea-5e4151d784b8
* Version Independent ID: 9cb6935a-184f-b18a-184c-7d4faf6256b6
* Content: [Report spam, non-spam, and phishing messages to Microsoft - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by get-itips** [comment]
Hello @r-wink Ryan, how are you?

I understand that you are not using Microsoft 365 and send emails to customers using 365.
I do not have the specifics on the "blocks" or "issues with the files" that your customers, using Microsoft 365, are experiencing, besides that, you could recommend your customers [to enable notifications when messages are quarantined](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages?view=o365-worldwide), so they are notified and can review them.

On reporting false positives you will have to rely on your customers, using Microsoft 365, to do that, with the article you referenced.

Hope this information helps you.

Thank you

**Comment by mypil** [comment]
@r-wink - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
