### ISSUE TITLE
Exchange Online P2 Licensing

### ISSUE THREAD

**Issue by cshearin** [MicrosoftDocs/microsoft-365-docs#1844]
While this article comprehensively covers licensing requirements for the M365 & O365 suites, it doesn't spell out the licensing requirements for the standalone solutions like Exchange Online, SharePoint Online and OneDrive for Business. With the In-Place Hold solution sunsetting for Exchange Online, having the appropriate licensing requirements here have become essential for customers to understand what licenses are required to support eDiscovery in Exchange Plan 2 only use cases. This article spells out the O365 E1 + ExO p2 use case, but doesn't say anything about ExO P2 standalone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24e97a56-f8f5-3725-cfda-954ec3ba71f6
* Version Independent ID: 0626a65e-d55d-48c7-90fe-1f982a18d729
* Content: [Get started with core eDiscovery cases in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-core-ediscovery?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/get-started-core-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-core-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@cshearin Please see this section in the Office 365 Security & Compliance Center Service Description, which we link to in the article: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#security--compliance-center-availability-for-standalone-plans

According to this table, EXO Plan 2 supports Core eDiscovery cases, eDiscovery holds, eDiscovery searches, and eDiscovery exports.
