### ISSUE TITLE
Please document how ZAP is differentiating between Spam and Phishing

### ISSUE THREAD

**Issue by jmvalente** [MicrosoftDocs/microsoft-365-docs#1845]
As someone who has been using Office 365 and its security features for several years, I am not sure if this is a result of a working product just not documenting its definitions, or ZAP's Phishing detection is incredibly broken. 

In order to help administrators properly configure filtering and protection tools, please provide some documentation on when a message is identified as "phishing" and when it is "spam". Looking at a rough sample, the vast majority of items I see marked as phishing are definitely just spam.  25% alone are from constant contact.  The rest are other forms of spam, ranging from bulk marketing to less legitimate forms of spam.  Only a very small minority are credential or financial harvesting messages--which is generally the commonly used definition of phishing. 

As it stands right now, it is almost impossible to find phishing messages in the flood of spam that ZAP identified as phishing. This also effectively breaks AIR as almost every investigation for a phishing URL is just spam--and often marketing emails from legitimate sources.

If this is, in fact, intended behavior please provide additional documentation for when a message is classified as spam and when it is classified as a phish.  This will enable administrators to more accurately filter "phishing" and craft policies based on this.   One part of it appears to be ZAP automatically tagging almost anything that does not pass SPF/DMARC as a phishing message, regardless of the content or sender reputation.

Even including a table highlighting when something is a phish, spam, or even both would be immensely helpful.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge (ZAP) - Email protection feature - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by MaratMussabekov** [comment]
Hello @jmvalente,
It looks like in terms of EOP, all spoofed emails considered as phishing.
For example, if you go **Treat protection status** report in Office 365 Security and Compliance center, and select **Email > Phish** view, you can clearly see that antispoofing detection is used as one of the reasons for emails to be marked as phishing. 
![image](https://user-images.githubusercontent.com/48041687/85221048-21335780-b3ca-11ea-9077-a3811c97d702.png)

Also, if you go to **Office 365 Security and Compliance > policy > anti-phishing** and create an antiphishing policy, you only able to set antispoofing configuration, and nothing else.

So, in this case, I suggest that marketing emails that do not use any type of spoofing/impersonation and pass SPF check are marked as spam, and all others - as phish.

Dear @chrisda , could you please confirm?

Thank you

**Comment by yogkumgit** [comment]
@MaratMussabekov  Thank you very much for the contribution and sharing this explanation. @jmvalente Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
