### ISSUE TITLE
how much time to sync?

### ISSUE THREAD

**Issue by haggisbreath** [MicrosoftDocs/microsoft-365-docs#1846]
to cedwards' point, I think --- how much time should this take to sync to Office 365 mailboxes?  How about to Outlook clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a862d8-4223-7bb7-42f1-9842cbeacf87
* Version Independent ID: 2c3c7e9a-a44d-168e-2083-b1527ab3f61c
* Content: [Allow members to send as or send on behalf of a Group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by RAJU2529** [comment]
@haggisbreath . I think it depends upon the  internet connection speed, proper DNS server, also contents of the mail attachments and size of the mails

**Comment by msbemba** [comment]
@haggisbreath  Thank you for your feedback. While It takes immediate effect, I would suggest giving it 2-5 minutes as it does not take more time than that.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@haggisbreath - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @RAJU2529 and @msbemba  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
