### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tjk123456789** [MicrosoftDocs/microsoft-365-docs#1847]
Groups link in Add a member to a group in the admin center is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40174ff9-7dc6-a706-c546-77e2391ab8d7
* Version Independent ID: a01b7077-976f-dded-ed25-18e8585b28b0
* Content: [Add or remove members from Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/add-or-remove-members-from-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/add-or-remove-members-from-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/add-or-remove-members-from-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by joinimran** [comment]
@tjk123456789 - Thank you for your feedback but I have confirmed that all of Groups link in the document is pointing to the correct resource https://go.microsoft.com/fwlink/p/?linkid=2052855 where after authentication we are directing to the Groups sections in Admin Center. 

Thanks.

**Comment by RAJU2529** [comment]
@tjk123456789 . Group link is working , first it asks to sign in with company e-mail address.

**Comment by mypil** [comment]
@tjk123456789 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @joinimran & @RAJU2529  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
