### ISSUE TITLE
Link to ISO/IEC 27001:2013 certificate is broken

### ISSUE THREAD

**Issue by jideuria** [MicrosoftDocs/microsoft-365-docs#1850]
The below link is broken and the certificate cannot be accessed via the Service Trust site either. I need this certificate ASAP please.

"Learn about the benefits of ISO-Iec-27001 on the Microsoft Cloud: Download the ISO/IEC 27001:2013"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea391196-6a78-34ac-becb-be7622c9f423
* Version Independent ID: 8e34eedc-30bf-aa9f-60d3-e678fcb13411
* Content: [ISO/IEC 27001:2013 Information Security Management Standards - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-iso-27001?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-ISO-27001.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-ISO-27001.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by joinimran** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

@mypil  FYI Please.

**Comment by joinimran** [comment]
@jideuria - Please visit https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide?command=Download&downloadType=Document&downloadId=47d89200-b24b-491d-b657-7c523ddfb6f9&docTab=4ce99610-c9c0-11e7-8c2c-f908a777fa4d_ISO_Reports to download the required resource. 

I have also updated the link and this change will live soon.

**Comment by robmazz** [comment]
Associated PR merged - resolving
