### ISSUE TITLE
One question about Outlook

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/microsoft-365-docs#1851]
Auditing does not record user sending/deleting emails in Outlook, is that right? And is there any other way for admins to check that?
And a couple small things. "User and admin activities are organized in to groups of related activities." - "organized into groups"
"Even when mailbox auditing on by default is turned on" - "auditing by default"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@hwkwicre Thanks for feedback. I'll fix the first item. Note that [mailbox auditing on by default](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing) is the (albeit clunky) feature name.

We don't currently audit when users send email. Alert policies can trigger alerts related to unusual behavior and you could maybe set up Exchange transport rules to copy mail to another mailbox sent by a specific user (but this could get noisy).

We do audit when they hard delete or soft delete messages in their mailbox. See the topic linked to above or https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#exchange-mailbox-activities
