### ISSUE TITLE
Hi There, may i know if this policy also can apply 

### ISSUE THREAD

**Issue by qingsj** [MicrosoftDocs/microsoft-365-docs#1852]
Hi There, may i know if this policy also can apply for Microsoft 365 Personal  and Family version please?
Eg: if i have sub-scripted Microsoft 365 Personal or Family version, when the Sub is expired, should i still can access the onedrive data in another 30 days please? thanks. by the way, if there is any official microsoft documents can support and provide please? thanks  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by qingsj** [comment]
Dear All;
if i could know any new update for this ticket please?
thanks

**Comment by cmcatee-MSFT** [comment]
@qingsj Here's the guidance on OneDrive data storage for your Microsoft 365 Home or Personal subscription. The article is [OneDrive storage plan and billing questions](https://support.office.com/en-us/article/OneDrive-storage-plan-and-billing-questions-989fce19-ade6-4e2f-81fb-941eabefee28). Click "I want to uninstall or cancel OneDrive" to find it.

**What happens to my data if I cancel my subscription or my bonus storage expires and I’ve exceeded my 5 GB free storage limit?**

If you cancel your subscription or if your free storage bonus expires, your data will continue to be accessible. You'll still be able to view, share, and download files on your OneDrive, but you won't be able to upload files until you [buy more storage](https://www.microsoft.com/en-us/microsoft-365/onedrive/compare-onedrive-plans?activetab=tab:primaryr1) or [free up space](https://support.office.com/en-us/article/delete-files-or-folders-in-onedrive-21fe345a-e488-4fa7-932b-f053c1bebe8a). If you continue to exceed your storage limit for an extended period of time, your account will be frozen. For info about bringing a frozen account back into good standing, see [What does it mean when your OneDrive account is frozen](https://support.office.com/en-us/article/what-does-it-mean-when-your-onedrive-account-is-frozen-5e76147b-b7d5-4bcb-ba28-b91e3eb636b6)?

**Comment by qingsj** [comment]
Dear Catee, thanks for the reply, may i know for the "If you continue to exceed your storage limit for an extended period of time, your account will be frozen. For info about bringing a frozen account back into good standing", how long will be the “extended period of time” please~? thx

**Comment by Infinitecupcakes** [comment]
The documentation states that when a subscription expires, Microsoft 365 admins will still have access to the admin center and applications. 

The article then goes on to state that when the subscription is disabled, the admin can’t assign licenses to users.

What the article does not clarify is: will the admin be able to assign licenses to users when the subscription is expired?

**Comment by cmcatee-MSFT** [comment]
Yes, admins can assign licenses while the subscription is in the expired state, but not after it moves into the disabled state (see table above).

**Comment by cmcatee-MSFT** [comment]
@qingsj I don't have further information about how data for non-business subscriptions is handled. I have made the consumer content team aware of the gap in their documentation, and they will work to address it.
