### ISSUE TITLE
Updated best practices?

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/microsoft-365-docs#1853]
With the GA of sensitivity labels with protection in SharePoint and OneDrive, do you reconsider to revise the principles used in this document? - see https://techcommunity.microsoft.com/t5/security-privacy-and-compliance/announcing-general-availability-of-sensitivity-labels-with/ba-p/1356224

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d8b5b1-6343-5611-9b4a-2e0a1b7cab60
* Version Independent ID: dc3836a2-1176-e021-d6fc-a120bbeec7a8
* Content: [Secure SharePoint Online sites and files - Office 365](https://docs.microsoft.com/en-ca/microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by yogkumgit** [comment]
This document is removed, no replacement yet, so closing it.
