### ISSUE TITLE
Spelling Mistakes on groups

### ISSUE THREAD

**Issue by fkalyva** [MicrosoftDocs/microsoft-365-docs#1854]
"An Microsoft 365 Group" should be corected to "a Microsoft 365 Group" - this mistake has probably been made after renaming "Office 365 Groups" to "Microsoft 365 Groups". See section "Applying a retention policy to an entire organization or specific locations". There is also a mistake somewhere saying "icrosoft 365 Group" instead of "Micorsoft 365 Group".  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mypil** [comment]
@fkalyva - Thank you for pointing this out.

PR #1859 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
