### ISSUE TITLE
Delegated Admin Access to Office 365 Security & Compliance Center

### ISSUE THREAD

**Issue by jcwalker0319** [MicrosoftDocs/microsoft-365-docs#1858]
The purpose of delegated administration is for the delegated partner to have the appropriate rights and privileges to administer the service.  Without this permission to the service, we lack the necessary delegation to accomplish that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 039e2a68-ab22-6a40-02d9-75415de32c85
* Version Independent ID: fac2bb6e-0c06-829e-71a7-f44dae9dc289
* Content: [Go to the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/go-to-the-securitycompliance-center?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/go-to-the-securitycompliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/go-to-the-securitycompliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@jcwalker0319  This seems to be product feedback rather than feedback about the documentation, so I recommend you post to the Office 365 Security & Compliance UserVoice: https://office365.uservoice.com/forums/289138-office-365-security-compliance
