### ISSUE TITLE
Info Missing: Where do file captured by safe attachments policy go?

### ISSUE THREAD

**Issue by jdemaree** [MicrosoftDocs/microsoft-365-docs#1860]
Quarantine right?! I don't see them there.
  
With the policy set to 'Replace' the email is still delivered, so it doesn't seems to show up in email quarantine section.  
However when you check in files portion of quarantine it says its specific to Teams, OneDrive, and SharePoint.  
In either even I don't see the files there either.

I have seen workarounds for this of sending the email to an "Admin" in the safe attachments policy and then just dumping them into a mailbox in case they are needed. 

It is possible I don't have the access to see it but with Security Admin I would hope?

Thanks for any info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e490a7ff-742e-426e-4a1c-b57c5b376910
* Version Independent ID: 5e49a6bd-ef37-08e7-566b-3a50e22c272e
* Content: [How ATP Safe Attachments works - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-atp-safe-attachments-works?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/how-atp-safe-attachments-works.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-atp-safe-attachments-works.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Hello @jdemaree 
To my understanding, when you use the "Replace" action and based on [this](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies?view=o365-worldwide) 

> Removes detected malware attachmentsNotifies recipients that attachments have been removed

the attachment is removed and you will not find it in quarantine, as you said, as using the Replace option, the message is still delivered, and you can redirect the attachment to a mailbox using policy options.
@MSFTTracyP Can you confirm this? Thank you

**Comment by jdemaree** [comment]
Apologies I forgot this was outstanding.  It does appear in quarantine as a
category of Safe Attachment Policy.

Apparently I just didnt have any in my search at the time.

I do think some clarification in the docs would be good.

**Comment by get-itips** [comment]
> Apologies I forgot this was outstanding. It does appear in quarantine as a category of Safe Attachment Policy. Apparently I just didnt have any in my search at the time. I do think some clarification in the docs would be good.


Thanks for getting back and share that feedback. Will test to see if we can improve the article.

**Comment by mypil** [comment]
@jdemaree - Thank you for submitting feedback.

We have already engaged the author @MSFTTracyP about your feedback for their consideration on future updates of this doc.


Thank you for your contribution to make the docs better! Much appreciated!
