### ISSUE TITLE
Issue on script results in execution error, does not finish

### ISSUE THREAD

**Issue by ddaanniieell9** [MicrosoftDocs/microsoft-365-docs#1861]
The script uses the following (Get-AzureADGroup -SearchString $GroupName).objectid
Since the script uses -SearchString it returns all groups in the tenant that contain the string.
Example, tenant has the following Groups:
 - Contoso
 - Contoso1
 - Contoso2
 - Contoso3
If we save Contoso in the variable $GroupName -> $GroupName = "Contoso"
During execution 4 groups will be returned instead of 1 and the execution will break.
This is resulting in customers opening support tickets with Microsoft.

Please fix using another search parameter for Get-AzureADGroup.

**Comment by mypil** [comment]
- May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by ddaanniieell9** [comment]
Here is the link – https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

**Comment by get-itips** [comment]
Hello @ddaanniieell9 
Thanks for noticing and reporting.
I checked and could reproduce.
I created a small fix to the script to use a different parameter to get the exact group by name, this is reflected on a pull request, if it gets approval, it will be published.
Thank you!

**Comment by ddaanniieell9** [comment]
Thank you, please let me know when this gets published so that I can let the customer that raised this issue know about the update.

Regards,
Daniel Portal

**Comment by mypil** [comment]
@ddaanniieell9 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/b3d740d1d2e62c4ba86976b1fcfabd2560eb644d. 


Thank you for your contribution to make the docs better! Much appreciated!
