### ISSUE TITLE
Office 365 Commercial Cloud FedRAMP

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/microsoft-365-docs#1863]
It is not clear whether Office 365 Commercial Cloud has any FedRAMP certifications. It is challenging to tell whether GCC is required for any level of FedRAMP needs, or if customers can stick with Office 365 commercial cloud for FedRAMP moderate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659dd7bc-2bbb-097c-44c1-730f2e3c6988
* Version Independent ID: 9f8d678e-8069-6997-505d-dd21333e1902
* Content: [Federal Risk and Authorization Management Program (FedRAMP) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-fedramp?view=o365-worldwide#microsoft-office-365-and-office-365-us-government-atos)
* Content Source: [microsoft-365/compliance/offering-FedRAMP.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-FedRAMP.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by MaratMussabekov** [comment]
Hello @SLeuthold ,
according to [FedRAMP portal](https://marketplace.fedramp.gov/#/products?sort=productName&productNameSearch=microsoft), both Office 365 Commercial Cloud and Azure  Commercial Cloud are FedRAMP Authorized
Thank you

**Comment by mypil** [comment]
@SLeuthold - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
