### ISSUE TITLE
Sensitive info match in content or document properties and email headers

### ISSUE THREAD

**Issue by SinghGurd** [MicrosoftDocs/microsoft-365-docs#1864]
Does sensitive info type only find matches within document content and email body or it inspects documents and emails in their entirety i.e. including document properties and email headers.

**Comment by mypil** [comment]
@SinghGurd - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by SinghGurd** [comment]
@mypil my query is about this article https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for?view=o365-worldwide

**Comment by chrfox** [comment]
Hi @SinghGurd 

that topic has been replaced with [Sensitive Information Type Entity Definitions](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-entity-definitions?view=o365-worldwide)

I believe that only content/body and unencrypted attachments can be searched
