### ISSUE TITLE
Manually upgrading your 1024 bit keys to 2048 bit keys - Reference signing domain

### ISSUE THREAD

**Issue by DevinSysAdmin** [MicrosoftDocs/microsoft-365-docs#1865]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#manually-upgrade-your-1024-bit-keys-to-2048-bit-dkim-encryption-keys

Article should explain to check the (signing) domain for this, which is by default the .onmicrosoft.com domain in the tenant. 

Confusion may occur when the user rotates the keys on domains other than the Default Signing Domain.

**Comment by mypil** [comment]
@DevinSysAdmin - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/26e9583eea1e41302f6eddf8b3bd07b54ce3dd7b. 


Thank you for your contribution to make the docs better! Much appreciated!
