### ISSUE TITLE
MFA possible for on-premises Dynamics 365 Finance and Operations application? 

### ISSUE THREAD

**Issue by shereen-yong** [MicrosoftDocs/microsoft-365-docs#1874]
*Firstly, Apologies I mistakenly left this comment as a child thread under the post below. I am reposting it here. 

Hello! I am wondering if the multi-factor authentication described here can be used for an on-premises implementation of 
Dynamics 365 for Finance and Operations? For on-prem D365 F&O the users still access the application via web browser, however the difference is the application is not hosted on Azure. Would MFA still work and if so, would the way to implementing it be the same way as described here via AAD and Office 365 admin settings?
Any related information would be appreciated thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?redirectSourcePath=%2Farticle%2FSet-up-multi-factor-authentication-for-Office-365-users-8f0454b2-f51a-4d9c-bcde-2c48e41621c6&view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@shereen-yong  this is a bit out of what I know. Here is a link to Azure content;
https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-mfa-howitworks
Hopefully that helps.
