### ISSUE TITLE
Outbound spam notifications

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#1875]
This is about: "(Optional) Expand the Notifications section to configure additional users who should receive copies and notifications of suspicious outbound email messages"
--&gt; This article is incorrect when advising to enable Outbound spam notifications by creating a new outbound spam policy since only the deafult outbound spam policy will generate these notifications. This was already escalated but not resolved by our Product group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, could you clarify?

The two available options are:

- Send a copy of suspicious outbound email messages to specific people.
- Notify specific people if a sender is blocked due to sending outbound spam.

Are you saying that one or both of these settings are only honored in the default outbound spam policy and ignored in any other custom policies? And where does the alert policy 'User restricted from sending email' fit in to this?

**Comment by JeroenDronkers** [comment]
Hello Chris,


The option “Send a copy of suspicious outbound email messages to specific people” only works for the default outbound spam policy.
Any customer outbound spam policy will not generate spam notifications although the “notifications” option is there.
I have raised a bug for this earlier but this is apparently not going to be fixed and causes confusion with customers.
These notifications are samples of the outbound spam emails which we need in support to be able to resolve the issue. The Alternative “Alerts” do not provide samples and are therefore useless.

The escalation: https://o365exchange.visualstudio.com/DefaultCollection/IP%20Engineering/_workitems/edit/1377606
The corresponding support case: Rave 18429987
The article is incorrect under: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide#use-the-security--compliance-center-to-create-outbound-spam-policies
Number 4: Expand the Notifications section to configure additional users who should receive copies and notifications of suspicious outbound email messages:

That will simply not do what it says.
Hope that clarifies.


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

**Comment by JeroenDronkers** [comment]
Hello Chris,

Sorry for the typo in previous email:
Any customer outbound spam policy will not generate spam notifications although the “notifications” option is there.

This needs to be: Any custom outbound spam policy will not generate spam notifications although the “notifications” option is there.







Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

From: Jeroen Dronkers
Sent: 12 May 2020 20:57
To: MicrosoftDocs/microsoft-365-docs <reply@reply.github.com>; MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Outbound spam notifications (#1875)

Hello Chris,


The option “Send a copy of suspicious outbound email messages to specific people” only works for the default outbound spam policy.
Any customer outbound spam policy will not generate spam notifications although the “notifications” option is there.
I have raised a bug for this earlier but this is apparently not going to be fixed and causes confusion with customers.
These notifications are samples of the outbound spam emails which we need in support to be able to resolve the issue. The Alternative “Alerts” do not provide samples and are therefore useless.

The escalation: https://o365exchange.visualstudio.com/DefaultCollection/IP%20Engineering/_workitems/edit/1377606
The corresponding support case: Rave 18429987
The article is incorrect under: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide#use-the-security--compliance-center-to-create-outbound-spam-policies
Number 4: Expand the Notifications section to configure additional users who should receive copies and notifications of suspicious outbound email messages:

That will simply not do what it says.
Hope that clarifies.


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

**Comment by chrisda** [comment]
@JeroenDronkers, I added notes calling out that notification settings only work in the default policy.

Thank for the feedback.

Closing
