### ISSUE TITLE
SharePoint Online 'Site Owner' Unclear / Undefined

### ISSUE THREAD

**Issue by mhendric** [MicrosoftDocs/microsoft-365-docs#1879]
In section 'Data table - Tenant SharePoint Online Usage', columns SitesWithOwnerActivities and SitesWithNonOwnerActivities refer to a 'site owner', however, it is unclear what the definition of 'site owner' is in this context. An example of why this is confusing is because if you run Get-SPOSite via PowerShell, it can show a different value for 'Owner' then what shows under 'Site owners' in the SharePoint admin center / Active sites. I request that 'site owner' be clearly defined on this page so that consumers know exactly what they are looking at.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de44679b-998b-3de8-292b-d2993af9bad9
* Version Independent ID: 7fd9ecf7-0468-d01e-dcca-d18a19ebb7c2
* Content: [Microsoft 365 usage analytics data model - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics-data-model?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics-data-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics-data-model.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by get-itips** [comment]
Hello @mhendric Mike how are you?
Would you be so kind sharing an example where you saw differences between the Owner property of SPOSite (returned by Get-SPOSite) and the Site Owners list (expanded) from the UI? 
This is to better understand your scenario as I could not repro.
Thank you

**Comment by mypil** [comment]
@mhendric - We appreciate any feedback you can provide to make the content in the Microsoft docs better. However, we did not get any response from you so we will close this issue. 

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. 

Thank you.

**Comment by mhendric** [comment]
Hi @mypil and @get-itips , sorry for the late response, was on vacation last week. Here's a couple examples. I don't have the ability to reopen this though. Can one of you do that for me?

Example 1:
![image](https://user-images.githubusercontent.com/11970059/83464323-65fc4c00-a425-11ea-8725-c9d76e91f52d.png)
![image](https://user-images.githubusercontent.com/11970059/83464347-7a404900-a425-11ea-949d-4e249f3944a5.png)

Example 2:
![image](https://user-images.githubusercontent.com/11970059/83464410-a5c33380-a425-11ea-88b8-5e95e5810d24.png)
![image](https://user-images.githubusercontent.com/11970059/83464451-c25f6b80-a425-11ea-8135-93ffe4c0a2ab.png)

**Comment by get-itips** [comment]
@mhendric Mike
Do you refer to the fact that, according to the admin panel, CommSite3 has no Owners (but admins) ?

**Comment by mhendric** [comment]
Hi @get-itips , I'm specifically calling out that depending on where you look within the service and available tools, Site Owner can show completely different things. This documentation talks about Site Owners, but that is clearly ambiguous at this point. In the context of these reports (and the dataset behind them), I'd like to clarify what a Site Owner actually is. Where do you look to see what the Site Owner is that is being referred to in these reports? PowerShell? SPO Admin Center? Somewhere else entirely?

**Comment by Sirkkuw** [comment]
This should probably go to @kaarins

**Comment by kaarins** [comment]
I understand this and can add this.

**Comment by get-itips** [comment]
> I understand this and can add this.

Thanks @kaarins

**Comment by mypil** [comment]
@kaarins - Do you have any updates on this?

Thank you.

**Comment by yogkumgit** [comment]
@kaarins Awaiting your response. Please revert. Thanks

**Comment by yogkumgit** [comment]
@kaarins This is a gentle reminder, please help us by adding the required information. Thanks

**Comment by get-itips** [comment]
Article has been updated to specify the definition of site owner.
@yogkumgit you can close this now.
