### ISSUE TITLE
collect gives access denied to path it cannot create

### ISSUE THREAD

**Issue by kmanoliadis** [MicrosoftDocs/microsoft-365-docs#1880]
hello, I'm having issues collecting the found PSTs, my collection creates the share to dump the pst, but cannot recreate the path and gives me an access denied error. Any advice?

<?xml version="1.0"?>
-<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">-<Parameters><Parameter Value="PST" Name="DataSource"/><Parameter Value="Collect" Name="Mode"/><Parameter Value="PstSearch1" Name="JobName"/><Parameter Value="DESKTOP-PST" Name="Locations"/><Parameter Value="C:\PST\ConfigurationLocation" Name="ConfigurationLocation"/><Parameter Value="\\192.168.77.10\pst\Files\" Name="CopyLocation"/><Parameter Value="C:\PST\Logs" Name="LogLocation"/><Parameter Value="Any" Name="CopyMethod"/></Parameters>-<Locations>-<Location Status="CopyError" Type="Machine" Path="DESKTOP-PST" JobId="878dfe25-7bc4-48bc-af78-f6e46979e80c">-<File Status="CopyError" FileSize="8201" FoundTime="2020-05-11 12:28" Owner="BUILTIN\Administrators" Location="DESKTOP-PST"><Path>C:\clutter.pst</Path><ErrorMessage>Access to C:\clutter.pst is denied. Reason: 'Access to the path '\\192.168.77.10\DESKTOP-PST\C' is denied.'.</ErrorMessage></File>-<File Status="CopyError" FileSize="8201" FoundTime="2020-05-11 12:28" Owner="BUILTIN\Administrators" Location="DESKTOP-PST"><Path>**C:\Users\administrator\Documents\Outlook Files\clutter.pst**</Path><ErrorMessage>Access to C:\Users\administrator\Documents\Outlook Files\clutter.pst is denied. Reason: 'Access to the path '\\192.168.77.10\DESKTOP-PST\C\Users\administrator\Documents\Outlook Files' is denied.'.</ErrorMessage></File></Location></Locations></Configuration>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af5cf2ac-3328-4c0f-486a-20975ae1f2f7
* Version Independent ID: 3d7aaf0f-7da3-c06b-565e-b0239ded63c3
* Content: [Use the PST Collection tool to find, copy, and delete PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/find-copy-and-delete-pst-files-in-your-organization?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/find-copy-and-delete-pst-files-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/find-copy-and-delete-pst-files-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@kmanoliadis Unfortunately, the PST Collection tool is unsupported, as per the note at the beginning of the topic. I haven't test this tool in years, but a few quick observations. Not sure if the error you're getting is access denied to the copy location or the source location of the PST files. If either of these are on your c: drive, maybe that is why access is denied? In step 3 in the topic, it looks like we're suggesting that you use a network share (e.g. -CopyLocation "\\FILESERVER03\PSTs") to copy the PST files to. Looks like you're trying to copy them to your c: drive. You might test different copy locations that aren't on your c: drive (e.g. a network share or a different local drive)?

**Comment by kmanoliadis** [comment]
Hi Mark

I’m getting an error on the destination, as it creates the share, it fails after it cannot create the rest of the path, (or because it does not create the rest of the path)

Thanks


[cid:image001.png@01D62837.B27AE880]<http://eepurl.com/UcO71>
_________________________________________
Kosta Manoliadis
Spécialiste de systèmes
[cid:image002.png@01D62837.B27AE880]<http://www.procontact.ca/>
T  514 940.1662  |  C  514 862.8271
F  514 688.9537 |  1 888 251.1622
Service technique : 418 263-3080

3249, rue Jean-Béraud
Laval (Québec)  H7T 2L2
REJOIGNEZ-NOUS :
[cid:image003.png@01D62837.B27AE880]<https://www.facebook.com/procontactqc>[cid:image004.png@01D62837.B27AE880]<http://www.linkedin.com/company/informatique-procontact>[cid:image005.png@01D62837.B27AE880]<http://www.procontact.ca/>

*Les opérations d’Informatique ProContact sont désignées essentielles dans la liste émise par le gouvernement du Québec sous la catégorie Maintenance et opérations des infrastructures stratégiques à titre de fournisseur de ressources informatiques (sécurité, entretien, besoins urgents liés à la situation).Le plan de continuité des affaires d’Informatique ProContact permet à nos employés d’effectuer leurs tâches en télétravail. L'ensemble de nos services sont maintenus.<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.procontact.ca%2Fetat-services%2F&data=02%7C01%7CKosta.Manoliadis%40procontact.ca%7C870f397ac3a747e3512008d7e2d26759%7Cc7d49bd103014851998b7cee3b88904d%7C0%7C0%7C637227265606375891&sdata=R0JzBqznUEpq9OocU05QScKStmgUtZaNrqH15DAe7HI%3D&reserved=0>


AVIS DE CONFIDENTIALITÉ : Le contenu de ce courriel est confidentiel et ne s'adresse qu'aux destinataires indiqués ci-dessus et peut contenir de l'information privilégiée,
confidentielle et/ou dispensée de divulgation aux termes des lois applicables. Si vous avez reçu ce courriel par erreur ou s'il ne vous est pas destiné,
veuillez en aviser immédiatement l'expéditeur et veuillez effacer ce courriel et détruire toute copie imprimée.

**Comment by markjjo** [comment]
@kmanoliadis Sorry, I can only point you to the documentation. From the errors you're getting, it looks like a permissions issue to me. From Step 3:


CopyLocation | Specifies the collection location where you want to copy the PST files to. You can copy files to a file server, a network file share, or a hard drive. **_The location must exist before you run the tool in the Collect mode._** The tool doesn't create the location, and will return an error saying that it doesn't exist. _**Also, you have to write permissions to the collection location specified by this parameter.**_
-- | --

**Comment by markjjo** [comment]
@kmanoliadis Please take a look at this github issue that was just opened: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1903

Not sure if this will fix your issue, but you might try mapping the destination share to a drive letter. I plan on updating the copylocation description and add an example/tip about mapping drive letter.

**Comment by D-Jeffrey** [comment]
_We don't mind the "AS IS" part of this, but then give us the source code so we can fix the bugs in the code to make it work correctly._

**Comment by markjjo** [comment]
@D-Jeffrey Ask here: https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=379531
