### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/microsoft-365-docs#1883]
"Microsoft 365 compliance enter" in two places

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 643cb341-cf88-69d6-561a-04f0eff3fe3e
* Version Independent ID: fe07a988-a832-92d8-9852-9956ecb2f655
* Content: [Close, reopen, and delete Core eDiscovery cases - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/close-reopen-delete-core-ediscovery-cases?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/close-reopen-delete-core-ediscovery-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/close-reopen-delete-core-ediscovery-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@hwkwicre Fixed and will be live by EOD. Thanks for heads up.
