### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/microsoft-365-docs#1884]
I believe that the eDiscovery hold link provided is not exactly right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4119f918-a0b2-4bdc-535e-11d2c476f675
* Version Independent ID: 1520175d-398b-4df1-86db-8ba6b26260df
* Content: [How to identify the type of hold placed on an Exchange Online mailbox - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@hwkwicre Fixed and will be live by EOD. Thanks for heads up.
