### ISSUE TITLE
Should differentiate more clearly between link for Chinese customers and ROW

### ISSUE THREAD

**Issue by philstubbington** [MicrosoftDocs/microsoft-365-docs#1887]
The structure of the top of the page is a little confusing, the first link appears to be for the rest of the world, followed by a link specific to Chinese customers.  

Should make this clearer, probably with a reference to Vianet.

**Comment by denisebmsft** [comment]
Hello @philstubbington! To which article(s) does your feedback apply? This will help us route the issue correctly.

**Comment by philstubbington** [comment]
Hi @denisebmsft - that certainly would have helped, wouldn't it? ;) 

I meant to add [this link](https://docs.microsoft.com/en-gb/microsoft-365/admin/microsoft-365-admin-center-preview?view=o365-worldwide#participate-in-the-new-admin-center).

**Comment by get-itips** [comment]
Hello @philstubbington Phil, how are you?
Thanks for noticing and reporting.
Will investigate and create a pull request to fix the article.
Thank you again

**Comment by philstubbington** [comment]
This still looks odd in step 2 as it refers to the .CN domain name?

**Comment by get-itips** [comment]
> This still looks odd in step 2 as it refers to the .CN domain name?

Hello! PR has not been reviewed and merged yet.

**Comment by mypil** [comment]
@philstubbington - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/1fd8a0a66bb5011eda769301bc7fed4dacf372d5. 


Thank you for your contribution to make the docs better! Much appreciated!
