### ISSUE TITLE
No recommendation tip for sensitivity labels is shown in the office apps and iOS

### ISSUE THREAD

**Issue by MischaR** [MicrosoftDocs/microsoft-365-docs#1888]
I set up sensitivity labels according to the documentations and I experience a strange behavior. I think that it is setup correctly as it is working as expected in the web app. In the office app it isn't working. Only when I close the app I see that the recommendation tip is shown. In iOS it isn't shown at all.

Already checked failure sources:
- The file or email already has a sensitivity label that's of equal or higher sensitivity than the label that would have been recommended.
- You have one of the following licenses assigned: Microsoft 365 E5, Azure Information Protection Premium P2
- You're connected to the internet.
- Office is configured to allow the use of connected experiences in Office that analyze content.
- You're using a version of Office that supports automatic and recommended sensitivity labeling.
- Your administrator has configured the conditions that trigger this feature, and has configured whether the sensitivity label should be automatically applied or recommended.

[demo-video.zip](https://github.com/MicrosoftDocs/microsoft-365-docs/files/4615638/demo-video.zip)

**Comment by cabailey** [comment]
MischaR  Looks like you've done your homework on this although this capability isn't supported on iOS, as per the tables: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#support-for-sensitivity-label-capabilities-in-apps

Seeing the recommended tooltip after closing the app (all apps - Word, Excel, PowerPoint, and Outlook?) does sounds like an issue with the product, so I recommend you open a support ticket for this:  https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online
