### ISSUE TITLE
Redundant information

### ISSUE THREAD

**Issue by robidog** [MicrosoftDocs/microsoft-365-docs#1889]
The paragraph after Step 6 ("How the import process works") is somewhat redundant as it merely repeats what was the main topic of the article. It adds no value to the text because by the time I reach it, I have already competed process.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86b2796-06fa-dfa7-bc0b-1a5760a396a0
* Version Independent ID: f9bfdc36-9c52-697f-f608-6e327d7c3c09
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@robidog Thanks for the feedback. Will take a look. This is added more for "nice to know" information rather than in the sequence of the stepped implementation process, which is why it's at the end.
