### ISSUE TITLE
Cannot delist IP 

### ISSUE THREAD

**Issue by matstocks** [MicrosoftDocs/microsoft-365-docs#1890]
I have been making repeated attempts to delist our IP for our web/mail server but without success. Who do we contact to escalate this?

**Comment by mypil** [comment]
@matstocks - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.
