### ISSUE TITLE
Broken Link for create-safe-sender-lists-in-office-365.md

### ISSUE THREAD

**Issue by gmi-dsmith** [MicrosoftDocs/microsoft-365-docs#1893]
The markdown is incomplete:
* Use the available safe sender lists: For information, see [Create safe sender lists](create-safe-sender-lists-in-office-365.md.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbab747e-1a43-037e-09ca-9c402deec602
* Version Independent ID: 1c6d8e28-034d-24d6-5732-b96475411d6b
* Content: [Anti-spam protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-protection?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gmi-dsmith, fixed.

In the future, you, too can make simple updates like this without opening a GitHub issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
