### ISSUE TITLE
macOS notifications integration

### ISSUE THREAD

**Issue by owenshaupt** [MicrosoftDocs/microsoft-365-docs#1897]
I really really wish Teams noifications were integrated through my OS. I can't use Do Not Disturb on my computer to control Do Not Disturb in Teams and Slack has supported this well before I ever even used it. This is a wel- known judging by the amount of forum discussion found online, I think this should be standard by now. Updates on timeline for this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d32f1ee8-5c57-e0b8-2632-1e7b2a9c06ff
* Version Independent ID: 5e1fd1e7-396a-58ca-31f2-2da3beb6aff6
* Content: [Support information for United States - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/united-states?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/support/united-states.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/united-states.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@owenshaupt Please use the [Microsoft Teams User Feedback Forum](https://microsoftteams.uservoice.com/) to give feedback specific to Microsoft Teams. Thanks.

**Comment by fishcharlie** [comment]
@cmcatee-MSFT Normally that is a great solution. But considering how the team basically provides next to no updates on UserVoice, you have to expect people to start reaching out on other platforms (ie GitHub Issues).

Alex said in April 2019 that they hope to have it released by the end of the quarter. That didn’t happen. Microsoft has claimed to be working on this issue for over 2 years. This isn’t a feature that should require 2 years of effort. It’s a straight forward thing.

I hope the correct people are aware that there are larger problems which are leading to an issue like this being created.

Simply closing the issue and redirecting to UserVoice won’t solve those underlying problems here...

https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16941685-use-built-in-notifications-for-macos#{toggle_previous_statuses}

**Comment by cmcatee-MSFT** [comment]
@fishcharlie I've made the product team aware of your feedback. They emphasize that they do monitor UserVoice constantly, and provide updates when they get them. So continuing to use that site is the correct way to share your input and concerns about Microsoft Teams. Thanks.
