### ISSUE TITLE
Need further information - Windows 10 upgrade from 7/8 Pro

### ISSUE THREAD

**Issue by bitn-rc** [MicrosoftDocs/microsoft-365-docs#1899]
This feature of the plan, needs more info about how one goes about using the upgrade with this plan, using the previous key:

"If you have devices that are licensed for Windows 7, 8, and 8.1 Professional, Microsoft 365 Business Premium provides an upgrade to Windows 10 Pro, which is the prerequisite for deploying Windows 10 Business.

 Important
You need to supply the original product key when you upgrade, otherwise the upgrade won't work."

How does the Microsoft 365 plan know that the computers Windows 7 Pro license is for that 365 account and thus allow upgrade to occur? I assume MS already know what keys are legit and the upgrade offer is still a free thing?

I assume the process is to then install Windows 10 then activate by just entering in the old Win 7 pro license, assuming all licenses are legit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed7e43-7ec8-01f6-8cf0-6fd77519840e
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business Premium frequently asked questions  - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by MaratMussabekov** [comment]
Hello @bitn-rc ,
Windows 7/8.1 product keys could still be used to activate Windows 10. However, doing that would be illegal, if you do not have appropriate Microsoft 365 subscription that provides an upgrade to Windows 10.

So you need both Microsoft 365 subscription and original product key to perform an upgrade.

Thank you

**Comment by mypil** [comment]
@bitn-rc - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @MaratMussabekov so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by bitn-rc** [comment]
Thanks @mypil it did answer it, however, I did have an update question to this that @MaratMussabekov may be able to answer.

So in a scenario where a Windows 7/8 user has Busines Premium and we want to get them to Windows 10, is the correct process for us to install Windows 10 Pro using the Microsoft provided ISO and then we login to Windows with the users 365 account? Or do we just enter the old Win7/8 key into the win10 install and it will allow us (obviously the legal part is that it's ok if the user has a 365 subscription active?

Thanks

**Comment by MaratMussabekov** [comment]
Hello @bitn-rc ,
Second option would work as well. There is no requirement to login using M365 account
Thank you

**Comment by bitn-rc** [comment]
Awesome thanks @MaratMussabekov for confirming.
