### ISSUE TITLE
Проблема со страницей

### ISSUE THREAD

**Issue by Dentaky** [MicrosoftDocs/microsoft-365-docs#1901]
Добрый день, на странице техподдержки для России нет адреса электронной почты, куда я могу написать по своей проблеме. Это очень плохо, прошу добавить.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a889f632-ec82-b908-95b1-757f32d31ea2
* Version Independent ID: a1bb913b-5bcb-bb85-919e-e6c8ad98a731
* Content: [Support information for Russia - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/russia?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/support/russia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/russia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by robmazz** [comment]
From Bing Translator:

Good afternoon, there is no email address on the technical support page for Russia, where I can write on my problem. That's very bad, please add.

**Comment by cmcatee-MSFT** [comment]
@Dentaky Customer support for business subscriptions is only available online via the Microsoft 365 admin center, or by telephone. If you are a Microsoft 365 admin, please use one of those options. If you do not have a business account, please contact consumer support by using [this form](https://support.office.com/home/chat?ContactUsExperienceEntryPointAssetId=S.HP.Main).
