### ISSUE TITLE
Where's the command line?

### ISSUE THREAD

**Issue by UoEMacManagement** [MicrosoftDocs/microsoft-365-docs#1902]
"The following command line syntax can be used to silently execute a compatibility scan and find out whether or not Windows Setup assesses the device as ready for upgrade."  A command line should follow, but doesn't.  Please could you add what it should be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0237c547-b170-95c5-f684-5c30a227844a
* Version Independent ID: 74836bfe-c4db-ccce-bf96-0962ca55d4ec
* Content: [Windows 7 to Windows 10 automated upgrades - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/windows-7-to-windows-10-upgrade-automated?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/windows-7-to-windows-10-upgrade-automated.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/windows-7-to-windows-10-upgrade-automated.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Hi - the command line would look like: Setup.EXE /Auto Upgrade /Quiet /NoReboot /Compat ScanOnly

Thanks for the comment, will get this added in
