### ISSUE TITLE
Please add a note for Network Shared

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/microsoft-365-docs#1903]
Please add a note that the Network Share can not be on a none Windows server (such as a SMB Appliance).  In order to work with such appliance, use a drive mapping to the NetShare instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af5cf2ac-3328-4c0f-486a-20975ae1f2f7
* Version Independent ID: 3d7aaf0f-7da3-c06b-565e-b0239ded63c3
* Content: [Use the PST Collection tool to find, copy, and delete PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/find-copy-and-delete-pst-files-in-your-organization?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/find-copy-and-delete-pst-files-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/find-copy-and-delete-pst-files-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@D-Jeffrey Thanks for the heads up and the suggestion. I updated the CopyLocation parameter description with your suggested fix.

https://docs.microsoft.com/en-us/microsoft-365/compliance/find-copy-and-delete-pst-files-in-your-organization?view=o365-worldwide#step-3-copy-the-pst-files-to-a-collection-location
