### ISSUE TITLE
Downgrade Office Apps

### ISSUE THREAD

**Issue by nayar34** [MicrosoftDocs/microsoft-365-docs#1904]
There is no guidance on how to downgrade the users from Apps for Enterprise to Apps for Business.  From what I can tell you need to go into an Office app like Outlook and go to your Office Account.  In the Office Account, you can choose Change License and then Update Office.  From my experience though this isn't always working.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655829e4-741a-dc96-35f9-2f3df4de2633
* Version Independent ID: f1c9dc75-d781-322c-1d74-8e0f39fafd1e
* Content: [Migrate to Microsoft 365 Business from Office 365 E3 - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/migrate-from-e3?view=o365-worldwide)
* Content Source: [microsoft-365/business/migrate-from-e3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/migrate-from-e3.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by RAJU2529** [comment]
@nayar34. You already experienced in this case,let wait for some days to getting advanced office 365  expert users will reply to you.
Keep waiting.

**Comment by MaratMussabekov** [comment]
Hello @nayar34 ,
I have tested it, to downgrade, you need to uninstall the office, change the user license and install the office back. I think it should be added to the article as a note. The option to Change License and then Update Office didn't work for me (may be it need more time to be applied, I am not sure)

Dear @Sirkkuw,
could you please confirm?

Thank you

**Comment by mypil** [comment]
@Sirkkuw - We would like to follow up. Can you please share your insights on this issue?

Thank you.

**Comment by Sirkkuw** [comment]
@mypil - I  have sent this to the PG as a question and will update here once I hear.

**Comment by Sirkkuw** [comment]
It’s supposed to happen on it’s own.  Within 72 hours, Office will detect the subscription change and download a new license.  Once the new license is downloaded, Office is supposed to see it and convert.
However the conversion might not always happen - this is getting fixed, or has been fixed.

**Comment by mypil** [comment]
@nayar34 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @Sirkkuw and @MaratMussabekov so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
