### ISSUE TITLE
OAuth on endpoint:  https://office365ingestionsvc.gble1.protection.outlook.com/service/ThirdPartyIngestionService.svc

### ISSUE THREAD

**Issue by sbacon17a4** [MicrosoftDocs/microsoft-365-docs#1905]
Does the endpoint, https://office365ingestionsvc.gble1.protection.outlook.com/service/ThirdPartyIngestionService.svc, support OAuth?  It does not appear to support it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d168aa8-f335-f879-d12f-d0b198f2a339
* Version Independent ID: 049d4291-2fd8-c80b-18a8-31e5ecb5fc88
* Content: [Work with a partner to archive third-party data - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/work-with-partner-to-archive-third-party-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/work-with-partner-to-archive-third-party-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/work-with-partner-to-archive-third-party-data.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by curtrobinson106** [comment]
A little more info from the 17a-4, llc (our company) side.

Using the 

We have a solution that writes to the Third-Party-Endpoint using Basic Authentication without issue. I have a method in our application that will create an OAuth token, which works successfully against the regular Office365 EWS endpoint (https://outlook.office365.com/ews/exchange.asmx) without issue. However, when I attempt to send messages to the Third-Party-Endpoint, I get an exception “The response received from the service didn't contain valid XML.”
The inner Exception was “DTD is prohibited in this XML document.”

An EWS Trace of the call has an "HTTP/1.1 500 Internal Server Error" in the EwsResponseHttpHeaders, and it returns an HTML page as the error which includes this:

`            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>
            <h2> <i>The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. </i> </h2></span>
            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">
            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
            <br><br>
            <b> Exception Details: </b>System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. <br><br>
            <b>Source Error:</b> <br><br>`

**Comment by markjjo** [comment]
@sbacon17a4 @curtrobinson106 

From engineering: "This does not support OAuth. The user has to use the credentials to authenticate." 

From Step 4 in article, these credentials are "The sign-in credentials (Microsoft 365 user ID and password) of the third-party data mailbox that you created in Step 2."

Since you are from one of the third-party partners listed in the topic, I would suggest you contact your contact at Microsoft for more information. Thanks.

**Comment by sbacon17a4** [comment]
Hi Mark, thank you for the responses.  We have contacted Microsoft for additional information.  Thanks.
