### ISSUE TITLE
Integration with other domains gmail or non azure ad domains

### ISSUE THREAD

**Issue by Kiran21500** [MicrosoftDocs/microsoft-365-docs#1906]
When i share files with sensitivity label to other domains rnd user could not open it.

**Comment by mypil** [comment]
@Kiran21500 - May we know which Microsoft document link you used in reference to this issue? Or are you having some technical issues which requires technical support?

If you have some issues with a particular doc, we would really appreciate it if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by Kiran21500** [comment]
Hi joyce,

Thanks for your mail.

https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide

I am refering to above site where i have applied sestivity labels with all neccessary permissions to files and sharing with non azure domains and public domains still the end users are getting they dont have permission to open and could not open saying the file is encrypted.

Could you please help us in this regard.
We also observed that when file is encrypted the end users couldnot open it using browser which is not the correct solution as we dont have control over the end user environment.

Thanks and regards
Kiran

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by cabailey** [comment]
@Kiran21500  Authenticating users from a social provider isn't support for encrypted documents that reside in SharePoint.  What you might be able to do here, is add them as guest accounts to your tenant in Azure AD or they use a Microsoft account with the email address of their choice - currently checking to see if this authenticated is accepted for this scenario.  However, a browser without Office for the web wouldn't be able to authorize users and decrypt content - for a list of supported apps, see https://docs.microsoft.com/en-us/azure/information-protection/requirements-applications#rms-enlightened-applications

**Comment by mypil** [comment]
@Kiran21500 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @cabailey  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by cabailey** [comment]
@Kiran21500 To confirm - Microsoft accounts are supported, and you can use these for guest access.  You can expect more information about this in the docs soon.
