### ISSUE TITLE
Too many commas

### ISSUE THREAD

**Issue by selleny** [MicrosoftDocs/microsoft-365-docs#1908]
There are way too many commas in these paragraphs. For example: "in a system" does not need to be between commas in this sentence: In cases where the customer would like to use Microsoft Online Services, in a system, that qualifies as PDIS through its architecture and types of information processed, Microsoft invites its customers to consider amongst other things available solutions, specified below. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24a8dfa-2eb1-eed5-8373-5158e5c3a167
* Version Independent ID: b4706457-147c-372a-04d0-448798119cd3
* Content: [Russian Personal Data Localization Requirements - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-russia-data-localization?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-russia-data-localization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-russia-data-localization.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@selleny  - Thank you for pointing this out.

I will get this issue over to the Microsoft 365 writing team for investigation.


Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JohanFreelancer9 - As discussed, please assist to do a copy/edit review to this doc and create a PR to resolve this issue. Thank you!

**Comment by robmazz** [comment]
PR merged - resolving
