### ISSUE TITLE
Note about Outlook sync behavior/impact

### ISSUE THREAD

**Issue by joesuffceren** [MicrosoftDocs/microsoft-365-docs#1912]
I am piloting adding delete-only policies for Exchange. I've noticed that after the policy is applied and start-managedfolderassistant is run, there is a great deal of sync activity that negatively impacts Outlook performance.

Policy: do not retain. Delete after 3 years
Client: Outlook Pro Plus Semi-Annual 1908
Client setting: cached mode, keep most recent 1 year offline

Even though none of the data being deleted was stored in the OST, we still saw a ton of negatively impacting sync activity for multiple users. Presumably, this is because all of the items (including those that are cached in the OST) are modified to add the retention policy to the item, and those changes are then synced down from the mailbox to support the "this item will expire in N days" UX?

If this is expected behavior, could the doc be updated to warm about it? If there are recommended remediations, could the doc be updated to mention them? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@joesuffceren  Hi, thanks for trying out retention policies for Exchange.  I asked engineering for advice about your post and I was told that there are too many variables for different environments to include anything meaningful in the docs about expected network traffic.  However, to provide more information about what's going on in the background, you might find it helpful to read this deep-dive explanation for Managed Folder Assistant for retention policies: https://docs.microsoft.com/en-us/archive/blogs/anya/understanding-of-managed-folder-assistant-with-retention-policies

If you still have questions, concerns, or would like somebody to do an analysis for your configuration and environment, I recommend you open a support ticket (https://docs.microsoft.com/office365/admin/contact-support-for-business-products).

**Comment by joesuffceren** [comment]
Carol,
The article you linked to includes the below snippet, which tells me definitively that applying a "delete after N days" policy will force an OST regeneration for every mailbox like I feared. That's not the answer I wanted, but I'm glad to have definitive documentation. Thank you. You are welcome to re-close this feedback item.

"Another important point that you should understand is that if you apply a retention policy that contains a default policy tag, the MFA stamps the default tag on every item in the mailbox. This action forces Outlook to download the complete contents of the mailbox the next time the client connects and synchronizes with Exchange."
