### ISSUE TITLE
Region Limitations - Again

### ISSUE THREAD

**Issue by maxw3l** [MicrosoftDocs/microsoft-365-docs#1913]
I would hazard a guess that the ongoing region limitation on Cortana is one of the reasons for its demise as a personal assistant platform.

Even now, with the revised Cortana, most features are nerfed for anyone who does not live in the United States.

I cannot begin to understand this decision making. Cortana should either be switched off completely in Windows 10 if it can't be used fully, or made accessible fully for those who enable it.

Most of the world, especially professionally, speaks English. Why not let everyone in English-speaking areas access all of the Cortana features to see if they are useful? If there are minor regionalisation issues we will deal with them or feed them back to you for future consideration.

The last thing we need on desktop is a digital assistant limited to telling jokes, providing weather or sending searches to Bing, which is precisely what we have today.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad4b3d3-b509-c6c6-e842-b53c68100c4e
* Version Independent ID: ec63705a-7ce3-abf6-5f4f-fe5bc95bc9b8
* Content: [Cortana integration with Office 365 - Microsoft 365 admin](https://docs.microsoft.com/en-AU/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/cortana-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/cortana-integration.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by mypil** [comment]
@maxw3l - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**. 

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
