### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/microsoft-365-docs#1917]
"Retention label names are immutable, which means that they and cannot be edited after they're created."
They and what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by PrasadKasireddy** [comment]
Thanks for reporting - this extra word "and" has been fixed in PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/1856, Microsoft team needs to merge

**Comment by cabailey** [comment]
Thank you for flagging this - this page had had substantial updates that do not include the original typo.
