### ISSUE TITLE
Downgrade windows 10 devices?

### ISSUE THREAD

**Issue by jonatanok** [MicrosoftDocs/microsoft-365-docs#192]
Hi, It seams like it's possible to uppgrade to windows 10 pro fith microsoft 365 business. But if you have devices with Windows 10 Enterprise, will it then downgrade the licens to windows 10 Pro?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059b7d44-f860-cfbe-86f2-e0e86ed612b3
* Version Independent ID: 08c38e6f-6f5a-0ac3-3570-ababa09c1110
* Content: [Microsoft 365 Business Frequently Asked Questions ](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs?ranMID=43674)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @jasongroce
* Microsoft Alias: **jasgro**

**Comment by jasongroce** [comment]
@lizap Can you look at this? I don't have permissions to modify this issue.

**Comment by lizap** [comment]
@greg-lindsay - can you take a look at this? The question is about whether you can downgrade from W10 Enterprise to W10 Pro. Thanks!

**Comment by mypil** [comment]
@greg-lindsay - We would like to follow up on this. Do you have any updates? Thanks.

**Comment by greg-lindsay** [comment]
The question doesn't seem to be about whether you can downgrade from Enterprise to Pro (this is possible if you read my downgrade topic), but rather if installing Microsoft 365 business will automatically perform a downgrade for some reason.  I really don't know the answer to this but I'm interested to find out. It doesn't seem like installing an app would downgrade your OS.  However if you read https://docs.microsoft.com/en-us/microsoft-365/business/pre-requisites-for-data-protection it says that Pro is required, so it's possible that Enterprise might be incompatible.  I will need to check with the writers for that topic though and see what they say.

**Comment by greg-lindsay** [comment]
I got a response, and as I suspected, installing M365 Business does not downgrade the OS from Enterprise to Pro. The software is fully supported on Enterprise. Specifically, it is fully supported on any commercial Windows SKU that is able to be AAD joined. You can even install on the Home edition, but since AAD join is not available on Home, most of the security features of M365 will not be available.

**Comment by mypil** [comment]
@jonatanok - Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
