### ISSUE TITLE
Receiving Data Source Error (Table: TenantOfficeLicenses)

### ISSUE THREAD

**Issue by kmthrush** [MicrosoftDocs/microsoft-365-docs#1921]
https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide 

Step 7:  I am able to successfully login, but when I attempt to connect to my data, I receive the following error:

Data source error{"error":{"code":"ModelRefresh_ShortMessage_ProcessingError","pbi.error":{"code":"ModelRefresh_ShortMessage_ProcessingError","parameters":{},"details":[{"code":"Message","detail":{"type":1,"value":"The column 'Any' of the table wasn't found."}}],"exceptionCulprit":1}}} Table: TenantOfficeLicenses.

**Comment by mypil** [comment]
Closing this issue as it is a duplicate to issue #1922
