### ISSUE TITLE
Network Connectivity points

### ISSUE THREAD

**Issue by lkuhn65** [MicrosoftDocs/microsoft-365-docs#1923]
This article needs to provide more detail about how points are earned for the Network connectivity score.  There is not a clear explanation about what specific steps can be taken to improve it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 411cc9ec-3de2-9aaf-00b8-d923d2b02f37
* Version Independent ID: c1a0daec-33a1-eb34-db3d-0b12b78a8aaf
* Content: [Microsoft Productivity score - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/productivity/productivity-score?view=o365-worldwide)
* Content Source: [microsoft-365/admin/productivity/productivity-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/productivity/productivity-score.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@lkuhn65 Thank you for your feedback. Microsoft productivity score is still in preview mode and Please share your thoughts about Productivity Score and your ideas about how to improve it. Use the Feedback sections within the product and/or reach out to the Productivity Score team at ProductivityScorePreview@service.microsoft.com.

@yogkumgit We can close this as the document is still under preview mode and the feedback can be shared directly with the productivity score team at ProductivityScorePreview@service.microsoft.com.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @lkuhn65 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
