### ISSUE TITLE
Verifying a message was Zapped

### ISSUE THREAD

**Issue by ryanfog** [MicrosoftDocs/microsoft-365-docs#1924]
The page states that message headers are not altered when a message is zapped. I see the following

![image](https://user-images.githubusercontent.com/25650327/81976445-28f32580-95ee-11ea-9982-fe9591fda9e0.png)

This "TimeTravelToQuarantine" seems to align with being zapped. 

In addition, I would like the status changed when doing message traces to reflect it being zapped over delivered and then being moved to say quarantine only when digging deeper into the message trace.

![image](https://user-images.githubusercontent.com/25650327/81976816-b6cf1080-95ee-11ea-9c73-24863854f10e.png)

**Comment by denisebmsft** [comment]
Hello @ryanfog. Thank you for the feedback! Can you please confirm to which article(s) this applies? It will help us route this to the correct writer. Thanks!

**Comment by ryanfog** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge?view=o365-worldwide#feedback

**Comment by MaratMussabekov** [comment]
Hello @ryanfog ,
it seems like if you change the action for phishing/spam messages in the anti-spam policy to **Quarantine**, this header is added. Otherwise, message header is not altered.

Dear @chrisda,
could you please confirm?

Thank you

**Comment by chrisda** [comment]
@ryanfog, I removed the offending Q and A from the topic.

Thanks for the feedback.

Closing
