### ISSUE TITLE
Quên mật khẩu quản trị khi chưa đăng ký Reset password

### ISSUE THREAD

**Issue by chienmaboys** [MicrosoftDocs/microsoft-365-docs#1928]
Hi Support team

Tôi là người quản trị của tài khoản datnt@qnu.edu.vn. Tôi quên mật khẩu đăng nhập vào tài khoản này, và đã cố gắng lấy lại mật khẩu trên trang đăng nhập của Office 365 nhưng không thành công. Lý do được hệ thống báo về là tôi chưa đăng ký thiết lập Reset password. Nhờ Team hướng dẫn xử lý giúp tôi để tôi có thể sử dụng lại tài khoản này bình thường.

Cảm ơn.
Nguyễn Thành Đạt

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 3caa6f8e-80e9-6f43-9efb-eb1ead8beed5
* Version Independent ID: 6ee3a580-815a-12d9-4c09-0806a0063984
* Content: [Support information for Vietnam - Microsoft 365 admin](https://docs.microsoft.com/vi-vn/microsoft-365/admin/support/vietnam?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/vietnam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/vietnam.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by denisebmsft** [comment]
Xin chào Nguyễn thanh đạt! Đây không phải là một cái gì đó chúng tôi có thể giúp bạn với. Vui lòng liên hệ với nhóm hỗ trợ kỹ thuật của chúng tôi để họ có thể hỗ trợ bạn đặt lại mật khẩu.
