### ISSUE TITLE
Can I confirm step 2 is correct for Search-UnifiedAuditLog?

### ISSUE THREAD

**Issue by Jimnar** [MicrosoftDocs/microsoft-365-docs#1929]
Can I confirm the Search-UnifiedAuditLog PowerShell command is accurate for step 2? It produces no results, but I get results for the same user and timeframe for the Search-MailboxAuditLog command.

Search-UnifiedAuditLog -StartDate 01/06/2020 -EndDate 02/20/2020 -UserIds &lt;user1,user2&gt; -Operations MailItemsAccessed -ResultSize 1000 | Where {$_.AuditData -like '\*"MailAccessType","Value":"Sync"\*'} | FL

Search-MailboxAuditLog -StartDate 01/06/2020 -EndDate 01/20/2020 -Identity &lt;user&gt; -Operations MailItemsAccessed -ResultSize 10000 -ShowDetails | Where {$_.OperationProperties -like "*MailAccessType:Sync*"} | FL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea44342-2111-160b-9806-d03e3ee00b1b
* Version Independent ID: ec9c9bc5-cfab-420a-c4c3-20184a7112ad
* Content: [Use Advanced Audit to investigate compromised accounts - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/mailitemsaccessed-forensics-investigations?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/mailitemsaccessed-forensics-investigations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/mailitemsaccessed-forensics-investigations.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by Jimnar** [comment]
Perhaps the issue is related to backslashes in this portion of the string? -like '\*"MailAccessType","Value":"Sync"\*' It seems to work when those characters are removed.

**Comment by markjjo** [comment]
@Jimnar Thanks for the heads up and following back with the fix. The backslash is an escape character in markdown, though it looks like it doesn't work in the cmdlet syntax code block. Not sure why it's there in the first place. Anyway, I will remove all backslashes. Thanks again!
