### ISSUE TITLE
Australian Tax File Number

### ISSUE THREAD

**Issue by Tin-Bui** [MicrosoftDocs/microsoft-365-docs#1931]
"No keyword from Keyword_Australia_Tax_File_Number or Keyword_number_exclusions is found."
Do you meant "A keyword from Keyword_Australia_Tax_File_Number and No Keyword_number_exclusions is found."?
Otherwise 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [What the sensitive information types look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/what-the-sensitive-information-types-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @Tin-Bui 
I'm not sure what you are asking, but the entire topic received a massive update today. Hopefully that will help.
