### ISSUE TITLE
Why don't messages disappear from Quarantine after they have been released?

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/microsoft-365-docs#1933]
Why don't messages disappear from Quarantine after they have been released?
Please explain why messages stay in the Quarantine, even after you have clicked on Release and released the message. Do you have to go back and Remove From Quarantine too? Thanks, Richard Artes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfc15d1-833b-3139-6bc0-1acb97d507c8
* Version Independent ID: 31e24618-c2e6-4fe4-9651-04d6007548a4
* Content: [Find and release quarantined messages as a user - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by faoquong** [comment]
@chrisda 
If end users do not want messages to remain in their quarantine, they can delete the messages. otherwise, the messages will expire from quarantine after 30 days.

**Comment by mypil** [comment]
@richard-artes - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @faoquong so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by v-kydela** [comment]
This does not seem to be resolved from my perspective. If messages are indeed supposed to remain in quarantine after they are released then the message we get when releasing them is misleading:

![image](https://user-images.githubusercontent.com/41968495/86188768-8ab31480-baf4-11ea-9f36-1465716d4514.png)

If messages stay in quarantine when released then there's no reason to refresh the query to see updated results.

**Comment by faoquong** [comment]
@v-kydela 
"If messages stay in quarantine when released then there's no reason to refresh the query to see updated results."

before a message is released, if you check the "Released" column for that message it will say "No"
only after the message has been released and you refresh the quarantine grid view will you see the "Released" column of the message update to "Yes"

Thanks
