### ISSUE TITLE
Instructions for anonymizing data is not accurate

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/microsoft-365-docs#1936]
The steps under "Make the collected data anonymous" points to locations/settings that no longer exist in the current Office 365 Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by jwojan** [comment]
It looks like the current mapping to this setting in the UI is under: 

Settings, Org Settings, and then Reports.

**Comment by mypil** [comment]
@jwojan - Thank you for pointing this out.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/f2d7c8b. 


Thank you for your contribution to make the docs better! Much appreciated!
