### ISSUE TITLE
No note about Hybrid scenarios or On prem Synced groups

### ISSUE THREAD

**Issue by elpinto007** [MicrosoftDocs/microsoft-365-docs#1939]
Hi

I came across this article and we are having issues with our implementation where we cannot share with Mail Enabled Security groups that are synced from our On Prem AD. I thought this was an issue and raised a ticket with Microsoft. However, I have been informed this is the intended design where mail enabled security groups synced to AAD from On Prem AD do not work.

Could someone please add this information to this MS doc so it is clear?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MaratMussabekov** [comment]
Hello @elpinto007 ,
could you please provide more details?
What kind of sharing you weren't able to set?
Thank you

**Comment by MaratMussabekov** [comment]
Hello @elpinto007 ,
could you please clarify which kind of sharing you tried to set?
Thank you

**Comment by yogkumgit** [comment]
@MaratMussabekov  Thank you very much for the contribution.  @elpinto007 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
