### ISSUE TITLE
Bypassing ATP Safe Links

### ISSUE THREAD

**Issue by arourke** [MicrosoftDocs/microsoft-365-docs#1940]
We know we can set up black list domains we always want to block, we also know we can exempt domains from being rewritten. Our problem is we have domains that are being picked up as "phish" and "ZapPhish" in AIR that are legitimate. We can of course choose not to act on the AIR investigations that are triggered, but these false positives are clogging up the investigation panel and making it difficult to use. How do we whitelist certain domains from being identified as phishing for our tenant in AIR? Better yet, is there a header we can add in a transport rule that allows all links in an email to bypass phishing and ZapPhish detection in AIR?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de70c835-f408-83a6-3cc7-885756bd7152
* Version Independent ID: 076708dd-80e4-39d7-7e23-42730c106900
* Content: [Automated investigation and response (AIR) overview - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/automated-investigation-response-office?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/automated-investigation-response-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/automated-investigation-response-office.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @arourke, and thank you for posting this question. I am looking into this, and I'll post an update here as soon as I have an answer for you.

**Comment by denisebmsft** [comment]
No updates yet but i am working on this.

**Comment by denisebmsft** [comment]
Still waiting on some input from our product team. Stay tuned.

**Comment by denisebmsft** [comment]
Didn't forget about this issue. Stay tuned.

**Comment by chrisda** [comment]
@arourke, do you think it's the sender's email address/domain that's triggering the alert? If so, the usual suspects are available for safe listing as described in [Create safe sender lists in EOP](https://docs.microsoft.com/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365).

If you think the URLs themselves are triggering the alerts, there's a new feature that allows you to allow specific URLs: [Manage URLs in the Tenant Allow/Block List](https://docs.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list). Note that this feature is currently in Preview. It's coming to everyone eventually, but it might not be available to you yet.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @arourke Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
