### ISSUE TITLE
Please remove mention of SharePoint in Step 2

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#1941]
In step #2, it says, "will be mapped to a hidden managed property in SharePoint named ComplianceAttribute." I realize on the backend SharePoint and OneDrive are the same, but this wording makes it seem like the ComplianceAttribute will be synced to SharePoint sites, which is not true. ComplianceAttribute is only available in OneDrive accounts.

Can you please update the language to remove the mention of SharePoint and/or make it more clear that this only works for OneDrive? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffb84a4-0c98-3fc2-8963-4c809efaa149
* Version Independent ID: 305dd7b2-382e-a0da-40b5-1457e6b625bd
* Content: [Set up compliance boundaries for eDiscovery investigations - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/set-up-compliance-boundaries.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-compliance-boundaries.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@EricaToelle Will do. Thanks for the heads up. Change (remove reference to SharePoint) should be published by end of day.
