### ISSUE TITLE
Records Management compliance statement

### ISSUE THREAD

**Issue by gavinmckay** [MicrosoftDocs/microsoft-365-docs#1942]
Can we please include which Records Management standard this functionality is compliant with? It doesn't comply with ISO 15489 or ISO 16175 which are applicable to Australia, New Zealand and the United Kingdom. It does comply with US Federal Records Management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc52e4d6-6373-204d-9eb2-d8c396375fb1
* Version Independent ID: 106caf2c-6de5-3cc9-6cdd-4dc81dcbcc8b
* Content: [Records management - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/records-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records-management.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@gavinmckay  Thanks for your feedback. These technical docs focus on how to use the records management solution in Microsoft 365.  When implemented, this feature can help you be compliant with the regulations you need to follow. Certifications for our products are typically documented in the Service Trust Portal (https://servicetrust.microsoft.com/).  If you can't find what you're looking for there and it's important to your deployment, let your Microsoft Account Manager know.
