### ISSUE TITLE
Hello Micro soft there are couple issues in help with one 

### ISSUE THREAD

**Issue by P-padre** [MicrosoftDocs/microsoft-365-docs#1943]
I received a message for providing a new method of payment. the system has a glitch for the 
 can you send me a link where i can change the method of payment for my email  account puerto. 

Also how do i get register as customer Microsoft products trading products at wholesale please advise thank you?   I get orders for electronic products and they often time ask for price quotes at wholesale. 
Let me know. 201-887-4935

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82583c48-08e6-9acb-657b-ce1fe44e76a5
* Version Independent ID: cbdcf652-3a68-4fa3-9f3b-92c518e0b710
* Content: [Change your payment method](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-payment-method?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-payment-method.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-payment-method.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by mypil** [comment]
@P-padre - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.

**Comment by P-padre** [comment]
Thank you Mypil  we resolved the computer glitches issue
