### ISSUE TITLE
Baseline concept

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1945]
Putting Information Protection and Threat Protection in the M365 silo implies that they don't apply to Azure and Power Platform which is not good. These are not services that are limited to M365 tenants, We need to plan to protect all the services. Adding another layer between AAD and the Subscription and Instance layer would help make this clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a68666a5-9ef4-4000-001f-63ca0bf72a4c
* Version Independent ID: 60b435e6-5a35-a0d9-1c32-b21afeba2599
* Content: [To identity and beyond — One architect's viewpoint](https://docs.microsoft.com/en-us/microsoft-365/solutions/identity-design-principles?view=o365-worldwide#baseline-concepts)
* Content Source: [microsoft-365/solutions/identity-design-principles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/identity-design-principles.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by alexshte** [comment]
Agree with your comment, but see my statement right after the picture "When you learn to swim it's better to start in the pool and not in the middle of the ocean. I am not trying to be technically accurate with this diagram. It's a model to discuss some basic concepts."  

LMK if you think that explains the intention.
