### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by bali0014** [MicrosoftDocs/microsoft-365-docs#1946]
The hyperlink / redirect to Download the ISO/IEC 27001:2013 -  to is broken
Link: https://go.microsoft.com/fwlink/p/?linkid=2100068 
Redirect: http://download.microsoft.com/download/1/2/9/12926039-8F90-4BAF-AC8F-7124D48F400B/ISOIEC_27001_Compliance_Backgrounder.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea391196-6a78-34ac-becb-be7622c9f423
* Version Independent ID: 8e34eedc-30bf-aa9f-60d3-e678fcb13411
* Content: [ISO/IEC 27001:2013 Information Security Management Standards - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-iso-27001?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-ISO-27001.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-ISO-27001.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@bali0014 -- Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/3047e3a5f0a9742caf5ee187cf0bcd41b9562e4f. 


Thank you for your contribution to make the docs better! Much appreciated!
