### ISSUE TITLE
SCCM LAB Kit Hyper-v server virtual machine won't turn on.

### ISSUE THREAD

**Issue by win-prac** [MicrosoftDocs/microsoft-365-docs#1949]
Hello Team,

I installed Hyper-v on my windows 10 machine. Downloaded the SCCM lab kit and ran the setup. I got all the virtual machines and its switches created in the hyper. The windows 7 machines are working fine, but the servers are not turning on. In the event log got the following error, "'HYD-DC1' was reset because an unrecoverable error occurred on a virtual processor that caused a triple fault. If the problem persists, contact Product Support. (Virtual machine ID 46DFBF46-47F5-4E84-99D1-63ED1CB75B52)". Event ID 18560. I checked for solutions, where it is mentioned that i should try using static Mac ID, but that solution did not work for me. I downloaded a Windows Server 2019 standard setup. Created a new virtual machine and it works fine. So i think some issue with the lab kit may be. My system specs are as follows.
Hyper -V version: 10.0.18362.1
Management Console: 3.0
Windows Version: 1909
OS Build: 18363.418
CPU: AMD ryzen 5 2600
Motherboard: Gigabyte B450 DS3H

Kindly Assist

**Comment by win-prac** [comment]
Hello Team,

I installed Hyper-v on my windows 10 machine. Downloaded the SCCM lab kit and ran the setup. I got all the virtual machines and its switches created in the hyper. The windows 7 machines are working fine, but the servers are not turning on. In the event log got the following error, "'HYD-DC1' was reset because an unrecoverable error occurred on a virtual processor that caused a triple fault. If the problem persists, contact Product Support. (Virtual machine ID 46DFBF46-47F5-4E84-99D1-63ED1CB75B52)". Event ID 18560. I checked for solutions, where it is mentioned that i should try using static Mac ID, but that solution did not work for me. I downloaded a Windows Server 2019 standard setup. Created a new virtual machine and it works fine. So i think some issue with the lab kit may be. My system specs are as follows.
Hyper -V version: 10.0.18362.1
Management Console: 3.0
Windows Version: 1909
OS Build: 18363.418
CPU: AMD ryzen 5 2600
Motherboard: Gigabyte B450 DS3H

Kindly Assist

**Comment by win-prac** [comment]
Hi @denisebmsft 

> Hello @win-prac! To which article(s) does your feedback apply? It'll help us route this issue to the right team/writer. Thanks!

I am closing this issue. It was for "https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide".
I created new virtual machines using the lab kit vhd files and it works fine now.

Thanks and Best Regards.

**Comment by szafrankk** [comment]
I've exactly got the same issue and I'm using the same CPU.

**Comment by szafrankk** [comment]
If anyone, ever, will come across the issue again try increasing minimum RAM on these devices ;)
