### ISSUE TITLE
Step 3 (optional): Set up groups for communication compliance 

### ISSUE THREAD

**Issue by IrolPinto** [MicrosoftDocs/microsoft-365-docs#1954]
As per the chart, We cannot add groups yet in communication compliance for reviewers.

 In the policy, you'll use email addresses to identify individuals or groups of people. To simplify your setup, you can create groups for people who have their communication reviewed and **groups for people** who review those communications. If you're using groups, you may need several.

**Comment by denisebmsft** [comment]
Hello @IrolPinto! To which article(s) does your feedback apply? It'll help us route the issue correctly.

**Comment by mypil** [comment]
@IrolPinto - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
