### ISSUE TITLE
Cannot use Delete with ReviewerEmail

### ISSUE THREAD

**Issue by bloodytourists** [MicrosoftDocs/microsoft-365-docs#1955]
The document states that you can enter a value for ReviewerEmail if the outcome is Delete of KeepAndDelete. This is incorrect, as a Reviewer can only be specified for KeepAndDelete. If you try and add a Reviewer to Delete then it will fail validation

"Validation failed in the provided CSV at row 1 column "ReviewerEmail". Error: ReviewerEmail can only be applied when retention action is KeepAndDelete."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Overview of file plan manager - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/file-plan-manager?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bloodytourists  Thanks for flagging this.  Yes, you must have a retain setting for disposition review, not supported for delete-only.  Fixing in the docs and should be live later today.

**Comment by cabailey** [comment]
Fix is live now, closing.
