### ISSUE TITLE
Capitalization?

### ISSUE THREAD

**Issue by Moshe-RA** [MicrosoftDocs/microsoft-365-docs#1956]
The new names for MS 365 Apps for "business" and MS 365 Apps for "enterprise" are conspicuously lowercase. Is this intentional?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d2d2b9-6658-1cb2-68f7-8fc7b20babb9
* Version Independent ID: ac7218d6-3d3f-6297-d3ca-e80c04ad525d
* Content: [Office 365 is now Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/new-subscription-names?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/new-subscription-names.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/new-subscription-names.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by PrasadKasireddy** [comment]
@Moshe-RA  - Yes, these names are lowercase.
Please refer the Announcement from Microsoft  - https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/30/new-microsoft-365-offerings-small-and-medium-sized-businesses/

Office 365 Business and Office 365 ProPlus will both become Microsoft 365 Apps. Where necessary we will use the “for business” and “for enterprise” labels to distinguish between the two.

![image](https://user-images.githubusercontent.com/11626905/82229117-a2b94500-9947-11ea-8a34-32c6364048c1.png)

**Comment by Moshe-RA** [comment]
Thank you for responding!

Moshe Armel – משה ארמל

Cell:     053-313-1716 :נייד

From US:  011-972-53-313-1716

moshearmel@gmail.com

**Comment by mypil** [comment]
@Moshe-RA - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @PrasadKasireddy so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Moshe-RA** [comment]
My pleasure!

Moshe Armel – משה ארמל

Cell:     053-313-1716 :נייד

From US:  011-972-53-313-1716

moshearmel@gmail.com
