### ISSUE TITLE
Junk email settings for EOP/ATP

### ISSUE THREAD

**Issue by ThijsLecomte** [MicrosoftDocs/microsoft-365-docs#1957]
Can we have some more clarification that the safe sender lists only have effect on EOP policies and not on ATP policies (such as Anti Phishing, Safe Attachments etc)

It's confusing and it's not clearly labeled in this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bec871b-790f-6826-b8f8-d1b7830c49ab
* Version Independent ID: 460db4e8-7f93-60a3-4889-f2d8f08fc75f
* Content: [Configure junk email settings on Exchange Online mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes?view=o365-worldwide#use-exchange-online-powershell-to-configure-the-safelist-collection-on-a-mailbox)
* Content Source: [microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by kennethvs** [comment]
I have a similar question, we had the situation where ATP Safe Links determined after delivery that a URL was malicious. The message itself had a SCL of -1, which I didn't understand. After creating a support call (case #20117105) the outcome was that EOP is skipped if an end-user adds someone to the safe senders list. If that is true, and we want to make sure that each message goes through EOP, does that mean that we need to disable the ability for end-users to define safe senders?

**Comment by ThijsLecomte** [comment]
@chrisda  looks good to me, thank you!
