### ISSUE TITLE
Migrate UserLoggedIn Activity Alerts to Alert Policies

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1958]
Hello,

according to the documentation Activity Alerts are deprecated. They should be migrated to Alert Policies. How can Office 365 E3 tenants convert activities that are missing in Alert Policies from Activity Alerts? E. g. UserLoggedIn activity exists in Activity Alerts but doesn't exist in Alert Policies.

1st and 2nd level Support doesn't have a solution beside buying a higher/additional license to be able to use Alert Policies in Cloud App Security panel. They can't help much more than this as that feature is supported by the Azure support team which can't be contacted as an Office 365 admin without buying a support plan.

Related to this:
- https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/34347670-activity-alerts-deprecating-but-new-alert-polici

Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance centers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@GiantCrocodile As I'm sure you know,  in the UI, you can create custom alert policies only for the activities in the Activities Is dropdown list. You might try using the [New-ProtectionAlert](https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/new-protectionalert?view=exchange-ps) cmdlet; see Example 1. 

As you point out in the link to the Office Voice, this feedback has been provided to the engineering team.

**Comment by GiantCrocodile** [comment]
@markjjo I will check out that cmdlet. Thank you for this information!

Is it correct that when Activitiy Alerts are removed, the Activity Alerts created via the button in the Audit Log Search page are still working and that the Activity Alerts of the Cloud App Security panel are independent from the deprecated ones or are all of these policies with the same name being based on the deprecated feature?

**Comment by markjjo** [comment]
@ Apologies, this is confusing. IMO, the "New alert policy" button on the audit log search page should have been removed a long time ago. This button does not create alert policies (New-ProtectionAlert). It lets you create an activity alert (New-ActivityAlert), which are being deprecated as you cited. I imagine existing activity alerts alerts will continue to work until they don't, but at some point you probably won't be able to create new ones.

I'm not very familiar with Cloud App Security alerts. But I'm pretty sure they are not the same as activity alerts. CAS alerts are triggered by CAS policies. And you can view CAS alerts on the Alerts page center. But these aren't activity alerts, they are CAS alerts triggered by CAS policies. See https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide#viewing-cloud-app-security-alerts

**Comment by GiantCrocodile** [comment]
Thanks for the great details @markjjo! This helped with better understanding the other information from the ongoing service request. When we find a feasible solution, I will post it here for other people with the same requirement. Right now, Cloud App Security isn't working as expected so I can't say more at the moment.

**Comment by GiantCrocodile** [comment]
Microsoft provided a solution for which you need an extra license as it's a standalone product: Activity Policies of Cloud App Security. It works.
