### ISSUE TITLE
Sign in risk evaluation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#1960]
In the require MFA based on Sign-in risk section, the table shows "Highly regulated	Leave all options unchecked to always enforce MFA". How does this provide more protection than "Sensitive	High, medium, low	Check all three"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0edb16f-03bd-e6f8-87e1-7fc713db726d
* Version Independent ID: 34252c76-c635-0fe0-e0fc-283d0e87d3b7
* Content: [Common identity and device access policies - Microsoft 365 Enterprise - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/identity-access-policies?view=o365-worldwide#next-steps)
* Content Source: [microsoft-365/enterprise/identity-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/identity-access-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@DeanGross  Thank you for the feedback. The sensitive protection enforces MFA on On low or above sign-in risk whereas the Highly regulated protection Forces MFA on On all-new sessions.

The below document has more information.

https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-policies-configurations?view=o365-worldwide#applying-these-capabilities-across-the-three-tiers-of-protection

Thanks
Sri

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
