### ISSUE TITLE
We need more specifics for drilldown reporting

### ISSUE THREAD

**Issue by bbeasley-opg** [MicrosoftDocs/microsoft-365-docs#1961]
All the metrics and reporting provided are wonderful but we are trying to push adoption in a specific area with specific set of users.  There is not a way to track this it seems.  I have looked at built in reports both at site and O365 Admin Center.  Even the Microsoft 365 Analytics data does not seem to have the detail.  We need to track a specific folder or file after pushing announcement/policy out.  See who viewed file and to see a list of files in that site that have been accessed and or those that have not been accessed.  All reports and data found are generic access (no site, no file, no folder) OR just the popular files and no details on who accessed the file.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8100e31a-0312-fd5e-805f-7c04dbe1c4d0
* Version Independent ID: d0b8f728-3aa2-685a-e78d-5f8dce194c72
* Content: [Active user in Microsoft 365 usage reports - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/active-user-in-usage-reports?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/usage-analytics/active-user-in-usage-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/active-user-in-usage-reports.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@bbeasley-opg - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**. 

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
