### ISSUE TITLE
OneNote Account

### ISSUE THREAD

**Issue by BobbyVillela** [MicrosoftDocs/microsoft-365-docs#1963]
I briefly used the login information from work to open TEAMS on my personal PC and now I can't sign in to ONENOTE with my personal email.  It still has my work email and it will not allow me to "switch" emails.
Keep getting this error: Error: "an unexpected host was loaded when attempting to perform silent auth"
Date: 2020-05-18T15:16:18.230Z
Session ID: fb9de8ef-e57b-440a-acb2-34026335547b

**Comment by mypil** [comment]
@BobbyVillela - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by BobbyVillela** [comment]
Thank you for replying @mypil - When I attempt to send a page (or anything) from my email, I click on the three dots on the upper right and select ONENOTE, this is where my work email is still there.  If I try to SWITCH accounts, I get the error mentioned above.  It will not let me switch accounts.
We
![OneNote 1](https://user-images.githubusercontent.com/60328520/82342595-6c1b1300-99b7-11ea-8475-59ada7c98019.PNG)
![OneNote 2](https://user-images.githubusercontent.com/60328520/82342599-6cb3a980-99b7-11ea-83ab-f025217c1c6e.PNG)

**Comment by mypil** [comment]
@BobbyVillela - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
