### ISSUE TITLE
Columns in OneDrive

### ISSUE THREAD

**Issue by CarissaB117** [MicrosoftDocs/microsoft-365-docs#1964]
Regarding this comment: You can also create a view of the library that contains the Labels column or Item is a Record column, so that you can see at a glance the retention labels assigned to all items and which items are records. Note, however, that you can't filter the view by the Item is a Record column.

Is this only available on the Admin side? I can't see that there is any column available to the end user to view "Record column" on SharePoint or OneDrive. Please provide more context on where this column is made available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Learn about retention labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@CarissaB117  In SharePoint, you're looking for the "Add column" > "Show/Hide columns" option.  Documented here: https://support.microsoft.com/en-us/office/show-or-hide-columns-in-a-list-or-library-b820db0d-9e3e-4ff9-8b8b-0b2dbefa87e2

**Comment by cabailey** [comment]
@CarissaB117  I double-checked, you can't add columns in OneDrive.  Updated the page to make this clear and added the how-to instructions reference.  Thanks for your feedback!  Closing.
