### ISSUE TITLE
Microsoft 365 API query

### ISSUE THREAD

**Issue by eduardosantos1989** [MicrosoftDocs/microsoft-365-docs#1969]
Dear All,

Is there any way to run advanced queries via API on the new Microsoft 365 Security Center platform, which means that for example specific EmailEvents or AlertInfo are available to be collected to third party systems.
Thank you.
Edmond

**Comment by denisebmsft** [comment]
Hello @eduardosantos1989. Can you please tell us to which article(s) your question applies? This information will help us route the issue to the correct writer/team. Thanks!

**Comment by eduardosantos1989** [comment]
Dear @denisebmsft,
I think this question is related to security/mtp platform.
Thank you!

**Comment by mypil** [comment]
@eduardosantos1989 - May we know which specific Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@eduardosantos1989 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.
