### ISSUE TITLE
Video and the text content publish is not match

### ISSUE THREAD

**Issue by ChongAlan** [MicrosoftDocs/microsoft-365-docs#1970]
The page title is Remove a former employee, the steps listed do not match the steps in the video - Delete a user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by MaratMussabekov** [comment]
Hello @ChongAlan ,
You are right, the part "To remove an employee" in the article is actually about the preventing user from logging in. I will create a PR to fix that.

The video shows the steps from the [section about the removing of the user account](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide#delete-a-former-employees-user-account).

Thank you

**Comment by mypil** [comment]
@ChongAlan - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/50c3b7ea1f7beaec43ba6b76b526916091f93e03. 


Thank you for your contribution to make the docs better! Much appreciated!
