### ISSUE TITLE
ATP Safe Links licensing requirements

### ISSUE THREAD

**Issue by vwethan** [MicrosoftDocs/microsoft-365-docs#1971]
Please be more specific in this line: "ATP is included in subscriptions, such as Microsoft 365 Enterprise, Microsoft 365 Business Premium, Office 365 Enterprise E5, Office 365 Education A5, etc."  It's confusing.  Microsoft 365 Enterprise E5 is the only M365 Enterprise is the only one that includes O365/M365 ATP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f4d9231-3dae-4719-7728-c212b6f72fec
* Version Independent ID: fb84d1b6-b388-553f-c707-baa06c78e072
* Content: [ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-links?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/atp-safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-safe-links.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@vwethan  Thank you for your feedback. We have made changes to the documnet via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2137

Thanks
Sri

**Comment by mypil** [comment]
@vwethan - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/3f085182f8a5d980876e51f186af3d8d64117f18. 


Thank you for your contribution to make the docs better! Much appreciated!
