### ISSUE TITLE
... 

### ISSUE THREAD

**Issue by cyanogenmod890** [MicrosoftDocs/microsoft-365-docs#1973]
!;:'B"?/^[@

---
#### Pojedinosti o dokumentu

⚠ *Nemojte uređivati ovu sekciju. Obavezno za docs.microsoft.com ➟ problem s povezivanjem na repozitoriju GitHub.*

* ID: cae455d4-6bc8-e72a-90d0-08c6ed0ef578
* Version Independent ID: 8fa768f4-f150-8fb8-cc02-d9028db6a913
* Content: [Install Office applications - Microsoft 365 admin](https://docs.microsoft.com/hr-hr/microsoft-365/admin/setup/install-applications?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/setup/install-applications.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/install-applications.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@cyanogenmod890 - We would like to get some details from you. Can you please share what specific issue you have and for which doc? Kindly provide the doc link so we can investigate.

Thank you.

**Comment by mypil** [comment]
@cyanogenmod890 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. 

Thank you.
