### ISSUE TITLE
in ability to feedback on product via uservoice on "this product"

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/microsoft-365-docs#1978]
because some calculations are plainly wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebdb9f0-76a5-eebc-4cd7-95f5407ed029
* Version Independent ID: 05abf201-e31c-08c0-a7fc-8fd46202e8b0
* Content: [Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@bakerm00 - Thank you for engaging with the community here for the docs.

Please follow this link to add your feedback via UserVoice:

[https://office365.uservoice.com](https://office365.uservoice.com)

You might find others have made a similar request that you can add to, or you can open a new one. 

Thank you for your contribution to make the docs better! Much appreciated!
