### ISSUE TITLE
Links to same URL

### ISSUE THREAD

**Issue by xNiklasJern** [MicrosoftDocs/microsoft-365-docs#198]
Both the  device security hyper link and the threat protection hyper link goes to the same URL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94fe923d-c208-f2c3-d9e2-d61c9c7e3b02
* Version Independent ID: 032ab4f8-0d7d-3672-3e6c-694f28d7d9a1
* Content: [Deploy Windows 10 Enterprise security features](https://docs.microsoft.com/en-us/microsoft-365/enterprise/windows10-enable-security-features)
* Content Source: [microsoft-365/enterprise/windows10-enable-security-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/windows10-enable-security-features.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by Justinha** [comment]
@xNiklasJern Thanks for catching that Niklas. The intro is rewritten with corrected links.
