### ISSUE TITLE
Is internet-message-id correct?

### ISSUE THREAD

**Issue by Jimnar** [MicrosoftDocs/microsoft-365-docs#1983]
Should this text say InternetMessageID instead of internet-message-id?

Access or collect all email messages the attacker accessed by using the internet-message-id to find them and then checking to see if any of those messages contains sensitive information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea44342-2111-160b-9806-d03e3ee00b1b
* Version Independent ID: ec9c9bc5-cfab-420a-c4c3-20184a7112ad
* Content: [Use Advanced Audit to investigate compromised accounts - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/mailitemsaccessed-forensics-investigations?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/mailitemsaccessed-forensics-investigations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/mailitemsaccessed-forensics-investigations.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Jimnar Thanks for heads up. I'll change to InternetMessageId, which is the property name in the MailItemsAccessed audit record.
