### ISSUE TITLE
Hover.com pages are not up to date

### ISSUE THREAD

**Issue by MikeAms** [MicrosoftDocs/microsoft-365-docs#1984]
These are not the current DNS record screens from Hover.com. for adding SRV records. We're having trouble reconciling the two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f2e4e45-6ad7-eb79-aecb-0d7a89b06a03
* Version Independent ID: 1059223e-5759-b130-41ac-5ea98cb5367e
* Content: [Create DNS records at Hover for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-hover?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-hover.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-hover.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by pebaum** [comment]
looking into this.

**Comment by yogkumgit** [comment]
@pebaum  Kindly answer and help us in resolving this issue. Thanks.

**Comment by lhcole** [comment]
We removed the Hover.com article and we're now pointing to general DNS records instructions: [Create DNS records at Hover for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider).
