### ISSUE TITLE
Please add link to the security and compliance portal

### ISSUE THREAD

**Issue by ericorman** [MicrosoftDocs/microsoft-365-docs#1986]
Step #1 of turning on Audit should be to navigate to the security and compliance portal, could you please provide link to url https://protection.office.com/unifiedauditlog as step #1. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn audit log search on or off - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ericorman Will do. In the future, since you are internal Microsoft, please go ahead and make the fix directly in the topic and then submit a PR. Ping me internally if you need instructions.
