### ISSUE TITLE
OperationsProperties or OperationProperties?

### ISSUE THREAD

**Issue by Jimnar** [MicrosoftDocs/microsoft-365-docs#1988]
Should references to OperationsProperties actually be OperationProperties, without the 's'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea44342-2111-160b-9806-d03e3ee00b1b
* Version Independent ID: ec9c9bc5-cfab-420a-c4c3-20184a7112ad
* Content: [Use Advanced Audit to investigate compromised accounts - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/mailitemsaccessed-forensics-investigations?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/mailitemsaccessed-forensics-investigations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/mailitemsaccessed-forensics-investigations.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Jimnar Fixed (topic will be updated later today) Also, since it looks like you are Microsoft vendor (or working as one) please feel free to fix these types of issues directly and submit a PR. Thanks in advanced.

**Comment by Jimnar** [comment]
@Markjjo, thank you for the guidance and prompt response to my inquiries.
