### ISSUE TITLE
Microsoft 365 Productivity Library URL not working

### ISSUE THREAD

**Issue by limjianan** [MicrosoftDocs/microsoft-365-docs#199]
As topic, Microsoft 365 Productivity Library  under Step 2 is not working
https://www.microsoft.com/microsoft-365/success

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f64ed9fb-07c5-d39a-92b1-230c4a528684
* Version Independent ID: ac936830-b74e-8e7b-5e2d-658a73888a4b
* Content: [Deploy Microsoft Teams for Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/teams-workload)
* Content Source: [microsoft-365/enterprise/teams-workload.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/enterprise/teams-workload.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT

**Comment by robmazz** [comment]
@limjianan - Thank you for your feedback, I will get this over to the Enterprise writing team for clarification/correction.

**Comment by JoeDavies-MSFT** [comment]
@limjianan The link works for me and resolves to https://www.microsoft.com/en-us/microsoft-365/success/?rtc=1. Can you tell me what your URL gets resolved to?

**Comment by JoeDavies-MSFT** [comment]
@limjianan   Looks like the URL is country-specific. I updated the link to point to https://www.microsoft.com/en-us/microsoft-365/success/?rtc=1. Best we can do right now. Thanks for letting us know about this.
