### ISSUE TITLE
Typo on first word

### ISSUE THREAD

**Issue by DuncThePunk** [MicrosoftDocs/microsoft-365-docs#1994]
"IIf you're an admin..."
Should read "If you're an admin..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24188a20-2483-27c4-ca55-b40fb218231b
* Version Independent ID: efa9becc-4220-ea8c-3783-2e3b43226ee6
* Content: [Submit malware and non-malware to Microsoft for analysis - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/submitting-malware-and-non-malware-to-microsoft-for-analysis?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/submitting-malware-and-non-malware-to-microsoft-for-analysis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submitting-malware-and-non-malware-to-microsoft-for-analysis.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@DuncThePunk - Thank you for pointing this out.

PR #1997 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!

**Comment by chrisda** [comment]
@DuncThePunk, I would add that you, too, can make simple fixes like this directly in the topic; no need to open a GitHub issue first. For more information, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks again for the feedback.
