### ISSUE TITLE
Issue #876 stuck

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#1998]
Hello,

the issue #876 has no progress since the issue was locked due to a spammer. I can't reach @dstrome via email or Microsoft Teams. It would be great if someone can continue to work on the issue as I think it has been forgotten due to the lock.

Best Regards,

**Comment by yogkumgit** [comment]
@KCCross  Please help us and answer this issue. Thanks

**Comment by KCCross** [comment]
resolved 876
