### ISSUE TITLE
Microsoft Translator should be included as an ISO 27001 covered product

### ISSUE THREAD

**Issue by avisuj** [MicrosoftDocs/microsoft-365-docs#2001]
per this blog Microsoft Translator should be included as a covered product: https://www.microsoft.com/en-us/translator/blog/2019/02/06/microsoft-translator-is-now-certified-compliant-to-meet-your-needs/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea391196-6a78-34ac-becb-be7622c9f423
* Version Independent ID: 8e34eedc-30bf-aa9f-60d3-e678fcb13411
* Content: [ISO/IEC 27001:2013 Information Security Management Standards - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-iso-27001?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-ISO-27001.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-ISO-27001.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@avisuj  Thank you for your feedback. We have made changes to the doc via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2167

Thanks
Sri

**Comment by mypil** [comment]
@avisuj - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/d7f2650091f5a06f69ffa13611fb72ace2d97ff7. 


Thank you for your contribution to make the docs better! Much appreciated!
