### ISSUE TITLE
Organizational Relationships Setting Moved

### ISSUE THREAD

**Issue by mister-dj** [MicrosoftDocs/microsoft-365-docs#2007]
"Organizational relationships" has been moved to Dashboard &gt; External Identities &gt; External collaboration settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147fb47a-99b2-f8ef-9ca6-35696d49c3fb
* Version Independent ID: b2f1b521-f231-48c2-b61f-f71bf9248d1c
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/solutions/collaborate-as-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-as-team.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by PrasadKasireddy** [comment]
@mister-dj  - Thanks for reporting issue.
yes, "Organizational relationships settings " has been moved  & renamed as External collaboration settings
Two ways you can set the External collaboration settings

a) Azure Active Directory > External Identities > External collaboration settings 
b) Azure Active Directory > user settings  > External collaboration settings

Update the changes through PR.

**Comment by mypil** [comment]
@mister-dj - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @MikePlumleyMSFT based on this https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2013#issuecomment-634064837 so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
