### ISSUE TITLE
Please expand section on Actions Menu 

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#2010]
Hi, it looks like the Actions menu section could be expanded. The screenshot is outdated as new actions have been added. Would be great if you could explain what each action does. For example, what will happen if I select "Report clean" action?

![image](https://user-images.githubusercontent.com/8972968/82642837-74b55880-9c06-11ea-84b0-9eb9ee479b2a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89aaa2af-ba47-4e6f-60f3-1b0b95df35f9
* Version Independent ID: 8495bb4c-045a-5085-64d9-1b9ae788cfdb
* Content: [Views in Threat Explorer and real-time detections - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer-views?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer-views.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer-views.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Closing this out. Thank you for letting me know.
