### ISSUE TITLE
How is Meetings derived?

### ISSUE THREAD

**Issue by chongsunlim** [MicrosoftDocs/microsoft-365-docs#2011]
Is it the number of Teams meeting the user organized or joined? I have some users, their data shows zero but they have been participating in many Teams meeting that month.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dae2c12c-f665-1fda-c80e-ae49f613a1b6
* Version Independent ID: d57d0fff-3011-b2d3-e385-1ba0068d400d
* Content: [Microsoft 365 Reports in the admin center - Microsoft Teams user activity - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/microsoft-teams-user-activity?WT.mc_id=365AdminCSH&view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/activity-reports/microsoft-teams-user-activity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft-teams-user-activity.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@chongsunlim Thank you for your feedback. We are discussing this with the author and will provide you an update shortly. 

Thanks
Sri

**Comment by Sirkkuw** [comment]
Following up with the PG.

**Comment by Sirkkuw** [comment]
It should be meetings participated in.
