### ISSUE TITLE
Reject action

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#2012]
When I Reject incorrectly identified emails (false positives), does the system capable of learning and excluding the rejected emails from future investigations. Or is there a way to do this in a manual way. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a98cd34-0725-fea7-fecf-d235cd12ada5
* Version Independent ID: e8dcaf4e-dcf8-b7c5-52f9-0cded3dc3cd8
* Content: [Approve or reject pending actions following an automated investigation - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-autoir-actions?view=o365-worldwide#review-a-pending-action-in-the-action-center)
* Content Source: [microsoft-365/security/mtp/mtp-autoir-actions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/mtp-autoir-actions.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@zlDev Thank you for your feedback. It does not exclude the rejected(false positive/negative) emails unless you report it to Microsoft. More information on that is available here - https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-autoir-report-false-positives-negatives?view=o365-worldwide#report-a-false-positivenegative-to-microsoft-for-analysis

In general, admins can use the Submissions portal in the Security & Compliance Center to submit email messages, URLs, and attachments to Microsoft for scanning to report False positives.


Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@zlDev - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
