### ISSUE TITLE
incorrect syntax on page

### ISSUE THREAD

**Issue by JM-Probado** [MicrosoftDocs/microsoft-365-docs#2015]
Syntax in example should be Get-AntiPhishPolicy not Get-PhishFilter under "Use the Security & Compliance Center to configure spoof intelligence"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c0cbdb-062e-08e1-7c7c-cedab550f01b
* Version Independent ID: 2791a840-3284-bc0d-7b9e-026b852797e6
* Content: [Configure spoof intelligence - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/learn-about-spoof-intelligence?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by JM-Probado** [comment]
* Get-PhishFilterPolicy apologies

**Comment by chrisda** [comment]
@JM-Probado, it's confusing, but spoof intelligence uses a combination of *-AntiPhishPolicy cmdlets (to enable/disable the feature entirely, enable/disable Unauthenticated Sender, and to set the MoveToJmf/Quarantine action) and *-PhishFilterPolicy cmdlets (identify the spoofed senders to allow or block).

I checked carefully through the topic, and all of the cmdlet references are OK. I cleaned up and consolidated the use of Get-AntiPhishPolicy in the "How do you know these procedures worked?" section based on unrelated issues.

Therefore, I'm closing this issue. Feel free to reopen as necessary.

Thanks for the feedback.
