### ISSUE TITLE
Admin role needed to view "Reports"

### ISSUE THREAD

**Issue by browningb** [MicrosoftDocs/microsoft-365-docs#2016]
Which admin role is needed to be able to view Reports within the Admin Center?

**Comment by chrisda** [comment]
@browningb, have you tried Security reader? And are you talking about a specific topic?

**Comment by mypil** [comment]
@browningb - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.

**Comment by browningb** [comment]
Thanks for the updates. I found out that Reports are not visible to admins within admin console for the DoD M365 environment yet.

>
