### ISSUE TITLE
Valid license add-ons

### ISSUE THREAD

**Issue by James-MCT** [MicrosoftDocs/microsoft-365-docs#2017]
I am working with a tenant that has Microsoft 365 E3 subscription + the Microsoft 365 E5 Insider Risk Management add-on as stated in the "Before You Begin" section, but get license error messages when trying to create or manage Communication Compliance policies in the Compliance center. We are a CSP but cannot find the E5 Compliance add-on listed to add to the tenant instead, can the license requirements please be clarified? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42670ffb-8024-7cc2-cb1b-27cec02cc223
* Version Independent ID: fa22f173-b62e-93cb-62f2-e6ad0b4739d8
* Content: [Get started with communication compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/communication-compliance-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-configure.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by James-MCT** [comment]
Is there any update available for this issue please - I have tenants that cannot go ahead with Teams until this is clearly understood. (PS, apologies for the double posting)

**Comment by msbemba** [comment]
@James-MCT  Thank you for your feedback. I have double-checked and the license requirements are correct (Microsoft 365 E3 subscription + the Microsoft 365 E5 Insider Risk Management add-on). I would recommend contacting support for this issue. @mypil  can you provide @James-MCT  with the support contact information?

Thanks
Sri

**Comment by mypil** [comment]
@James-MCT - You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so they can help resolve your technical issue.

Thank you for engaging with the community here for the docs.
