### ISSUE TITLE
Create policy wording

### ISSUE THREAD

**Issue by pctsltd** [MicrosoftDocs/microsoft-365-docs#2018]
It should be made clear in this document that to create a label policy you have to press the "publish labels" button in the compliance centre which then brings you into the create policy wizard. The wording is confusing as there is no "create/add policy" button like there was in Azure.  There is nothing in the document that tells you "how to create a label policy". Publishing a label - in fact creates the policy but to the avid reader the wording is not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Learn about sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@pctsltd  The scope of this article is high-level conceptual information to help explain what sensitivity labels are and how to use them.  How-to instructions for creating labels and publishing their policies are in the following article: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels 

If you need other how-to instructions to support specific scenarios, use the following list to help you identify the relevant information: https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-sensitivity-labels?view=o365-worldwide#common-scenarios-for-sensitivity-labels
