### ISSUE TITLE
Broken link on FFIEC Blueprint

### ISSUE THREAD

**Issue by pushsos** [MicrosoftDocs/microsoft-365-docs#2023]
[Enter feedback here]
https://servicetrust.microsoft.com/ViewPage/FFIECBlueprint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e126d243-a1d7-60f5-41d1-584e0cf18400
* Version Independent ID: aa844477-2721-df47-afd5-4793944c618c
* Content: [Federal Financial Institutions Examination Council (FFIEC) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-ffiec-us?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-FFIEC-US.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-FFIEC-US.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@pushsos - Thank you for pointing this out.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/72f8fd072d0cd3bbc693edba6e80ee44e8fe2685. 


Thank you for your contribution to make the docs better! Much appreciated!
