### ISSUE TITLE
Update Page to reflect Microsoft Endpoint Manager

### ISSUE THREAD

**Issue by Xcel1** [MicrosoftDocs/microsoft-365-docs#2027]
Since Intune and Config Manager are now call Microsoft Endpoint Manager, can this reflect the new product naming?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea391196-6a78-34ac-becb-be7622c9f423
* Version Independent ID: 8e34eedc-30bf-aa9f-60d3-e678fcb13411
* Content: [ISO/IEC 27001:2013 Information Security Management Standards - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-iso-27001?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/compliance/offering-ISO-27001.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-ISO-27001.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Xcel1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2214

Thanks
Sri

**Comment by msbemba** [comment]
@Xcel1 Thank you for the feedback. I have feedback from the author that the endpoint Manager includes Intune service (among others) and is not a 1:1 rebranding for Intune in all cases. The author will confirm the broader strategy for including Endpoint Manager in the compliance offering topics.

Thanks 
Sri

**Comment by mypil** [comment]
@Xcel1  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
