### ISSUE TITLE
Incorrect/incomplete information

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/microsoft-365-docs#2029]
Can you please clarify how exactly can we enforce password history in Azure AD? The link provided in the article is for on-premises AD, not relevant to the current article, or at the very least it should be clarified it applies only to PTA/ADFS scenarios. And if I'm wrong and there is actually a way to play with password history settings in Azure AD, please provide the instructions.

Next, can you add information about the PowerShell cmdlets we can use to configure policies?

And the bit about wiping a mobile device in order to "ensure the password is no longer stored and recycled from there" is just bad advice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@michevnew Thank you for your feedback. We have corrected the link for enforcing password history in Azure AD, Added steps to update password polices (only update is possible as of now), and removed the Mobile wipe statement mentioned in the document. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2520

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba hank you very much for the contribution and updating the documentation with PR. @michevnew Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
