### ISSUE TITLE
문구 수정 요청-1206

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/microsoft-365-docs#203]
As-Is
Exchange Online 보관 라이선스 연속 데이터 백업으로 쉽게 보관할 메시지를를 수 있습니다. 
검색 또는 복원 나중에 필요한 하는 경우 삭제 된 항목을 포함 하는 사용자의 전자 메일의 모든를 저장 합니다. 
또한 소송 보존, eDiscovery에 대 한 전자 메일 데이터를 유지 하기 위해 또는 규정 준수 요구 사항을 충족 하기 위해 다른 보존 정책을 사용할 수 있습니다.

To-Be
Exchange Online Archiving 라이센스는 연속적인 데이터 백업으로 메시지를 쉽게 보관할 수 있게 합니다. 
나중에 검색 또는 복원을 위해 필요할 경우를 대비하여 삭제 된 항목을 포함하여 사용자의 모든 전자 메일을 저장합니다. 
또한 다양한 보존 정책을 사용하여 소송 자료 보호, 전자 증거 검색 또는 준수 요구 사항 충족을 위해 전자 메일 데이터를 보존 할 수 있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 1d156f82-2ba0-2d66-a639-1df86554ac83
* Version Independent ID: 4e158c5b-09fd-7214-474f-e7ff44b86d39
* Content: [Microsoft 365 비즈니스 보안 기능](https://docs.microsoft.com/ko-kr/microsoft-365/business/security-features)
* Content Source: [microsoft-365/business/security-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/security-features.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
의견을 보내 주셔서 감사합니다. 이 문제를 해결하기 위해 번역 팀과 협력하고 있습니다.
