### ISSUE TITLE
Links to be reviewed

### ISSUE THREAD

**Issue by ManuInNZ** [MicrosoftDocs/microsoft-365-docs#2031]
Link to the Microsoft IT Showcase goes nowhere.

> Learn how IT experts at [Microsoft manage identities and secure access](https://www.microsoft.com/itshowcase/deploying-and-managing-microsoft-365#primaryR5).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4308bf55-eadb-767d-6aaa-21190669c1ef
* Version Independent ID: d3e1731f-9f86-efba-4369-b0399cd99172
* Content: [Phase 2: Identity - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/identity-infrastructure?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/identity-infrastructure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/identity-infrastructure.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@ManuInNZ This link URL has been corrected and published. Thanks so much for letting us know.
