### ISSUE TITLE
"Understand licenses" section doesn't even list licenses

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/microsoft-365-docs#2032]
Could you please add the available licenses, descriptions and if possible comparison chart, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805a04c5-96c4-ee47-7746-3105e0b7fc45
* Version Independent ID: 9efa7447-6731-6435-d4fc-8ba81344e85a
* Content: [Understand subscriptions and licenses in Microsoft 365 for business](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/subscriptions-and-licenses?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/licenses/subscriptions-and-licenses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/subscriptions-and-licenses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by WaynePal** [comment]
Very much needed

**Comment by msbemba** [comment]
@ingepepe  Thank you for your feedback. We have added a link on this page to another doc ( https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb) which talks about different licensing options

This can be tracked via PR # https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2215

Thanks
Sri

**Comment by mypil** [comment]
@ingepepe @WaynePal - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/840cfc7fdce8599f354fdb213f8536e29b9a7262. 


Thank you for your contribution to make the docs better! Much appreciated!
