### ISSUE TITLE
Add new communication role to this page

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#2033]
A new role called "communication" was added to eDiscovery permissions. It can manage all communications with the custodians identified in an Advanced eDiscovery case. Please add that role to this page. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94e0469-2c5c-2063-8c3e-7722ceb53577
* Version Independent ID: e99eb8aa-b3b7-8791-aba4-998e209694b5
* Content: [Assign eDiscovery permissions in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/assign-ediscovery-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/assign-ediscovery-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@EricaToelle Thanks for the heads up. Added info about Communication and Custodian roles.
