### ISSUE TITLE
Mmm

### ISSUE THREAD

**Issue by cyanogenmod890** [MicrosoftDocs/microsoft-365-docs#2034]
ulica ije Šiloboda Bolšića 19

**Comment by PrasadKasireddy** [comment]
@cyanogenmod890  - could you please brief your issue that would be help us to help you on this

**Comment by mypil** [comment]
@cyanogenmod890 - Možemo li znati koju ste Microsoftovu vezu dokumenta koristili u vezi s ovim problemom? Ili je ovo pitanje otvoreno greškom?

Ako imate problem s određenim dokumentom, mi bi stvarno poštovati ako ste u mogućnosti pomoći pružanjem više detalja. Hvala ti!

[Can we know which Microsoft document link you used in reference to this issue? Or did you open this issue by mistake?

If you have an issue with a particular document, we would really appreciate it if you are able to help by providing more details. Thank you!]

**Comment by mypil** [comment]
@cyanogenmod890 -  Cijenimo sve povratne informacije koje poboljšavaju sadržaj u Microsoft docs, ali nismo imali bilo koji odgovor od vas, tako da ćemo zatvoriti ovaj problem.

Ako postoji određeno područje dokumenata na kojem možemo poboljšati, slobodno otvorite novi problem klikom na odjeljak Povratne informacije na određenom Microsoftovu dokumentu koji se nalazi pri dnu stranice. Hvala ti.

[We appreciate any feedback that improves the content in Microsoft docs, but we haven't had any response from you, so we'll close this issue.

If there is a specific area of documents where we can improve, feel free to open a new issue by clicking the Feedback section on the specific Microsoft document at the bottom of the page. Thank you.]
