### ISSUE TITLE
Unable to update customized help desk info 

### ISSUE THREAD

**Issue by o365geek** [MicrosoftDocs/microsoft-365-docs#2035]
I made mistake with the information e.g email address typo. I have updated the detail from admin>seetings>org wide settings>help desk but still showing incorrect details . Please help

**Comment by mypil** [comment]
@o365geek - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@o365geek - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
