### ISSUE TITLE
Integrate with MacOS Notifications

### ISSUE THREAD

**Issue by jordanjones98** [MicrosoftDocs/microsoft-365-docs#2037]
Microsoft Teams should really integrate with MacOS Notifications. It causes awkward moments when you have do not disturb on and you get a message anyways. Also, when someone has a full screen window open it does not show the notifications. I know there is the user voice ticket open, but this is a ridiculous issue that has been in "working on" status for years. Something that the "User's Voice" has been wanting for a long time but the MS Teams team has been ignoring.

PS. We don't want to change between MS Teams notification's and Mac notifications. There is nothing that the Teams notifications gives us that the Mac notifications will not.

Please don't just close this and tell me to go to "User Voice" because that doesn't get the point across.

Thanks.

**Comment by mypil** [comment]
@jordanjones98 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by jordanjones98** [comment]
@mypil the user voice link is https://microsoftteams.uservoice.com/forums/555103-public/suggestions/16941685-integrate-with-macos-notifications

**Comment by mypil** [comment]
@jordanjones98 - Thank you for engaging with the community here for the docs.

We greatly encourage collaboration from the readers and get constructive criticism, containing suggestions of what would improve the documentation. However, our work is restricted to making specific changes to docs so your suggestion and feedback might get more traction in the UserVoice channel.

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.
