### ISSUE TITLE
Insider Risk Management add-on license

### ISSUE THREAD

**Issue by James-MCT** [MicrosoftDocs/microsoft-365-docs#2038]
I am currently working with a tenant that has Microsoft 365 E3 licenses and we added Microsoft 365 E5 Insider Risk Management add-on licenses, but I cannot create a communication compliance policy or manage a policy without getting license error messages. Can you please confirm the Risk Management add-on is still valid for this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42670ffb-8024-7cc2-cb1b-27cec02cc223
* Version Independent ID: fa22f173-b62e-93cb-62f2-e6ad0b4739d8
* Content: [Get started with communication compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-configure.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@James-MCT - yes, both insider risk management and communication compliance are included in the Microsoft 365 E5 Insider Risk Management add-on license. Make sure you've configured license correctly and it is displayed in Admin center > Billing . Licenses, and confirm that you've assigned the license to the users you included in these policies.
