### ISSUE TITLE
Manage Microsoft 365 Apps for enterprise (device) In Azure

### ISSUE THREAD

**Issue by kagw69** [MicrosoftDocs/microsoft-365-docs#2039]
This page address assigning the Microsoft 365 Apps for enterprise (device) license to a group created in azure.  However, after assignment, will Azure show a tally of license being used/available? Or will the customer have to mange this from the Microsoft 365 admin center portal?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bca3d86-2b5b-706f-ba26-291c8c0064ba
* Version Independent ID: 313eb228-35b4-6c47-4153-2137c62b6b20
* Content: [Manage licenses for devices](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/manage-licenses-for-devices?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/licenses/manage-licenses-for-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/manage-licenses-for-devices.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@kagw69 You should use the Microsoft 365 admin center for managing device licenses. You'll be able to see the counts of device licenses used & available there.
