### ISSUE TITLE
02-문구 수정 요청-1206

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/microsoft-365-docs#204]
As-Is
정보 보호와 같은 컨트롤이 포함 된 전자 메일 및 문서에서 중요 한 정보에 대 한 액세스를 제어 "를 수행 하지 앞 으로" 및 "복사 하지 않습니다." "Confidential"로 중요 한 정보를 분류 하 고 외부 분류 된 정보를 공유할 수 하는 방법 및 비즈니스 안에 지정할 수도 있습니다.

To-Be
정보 보호는 "전달하지 않음" 및 "복사 안 함"과 같은 컨트롤을 사용하여 전자 메일 및 문서의 중요한 정보에 대한 액세스를 제어하는 데 도움이됩니다. 민감한 정보를 "기밀"로 분류하고 기밀 정보를 비즈니스 외부 및 내부에서 공유 할 수있는 방법을 지정할 수도 있습니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 1d156f82-2ba0-2d66-a639-1df86554ac83
* Version Independent ID: 4e158c5b-09fd-7214-474f-e7ff44b86d39
* Content: [Microsoft 365 비즈니스 보안 기능](https://docs.microsoft.com/ko-kr/microsoft-365/business/security-features)
* Content Source: [microsoft-365/business/security-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/security-features.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
의견을 보내 주셔서 감사합니다. 저는 번역 팀과 협력하여 업데이트 작업을하고 있습니다.
