### ISSUE TITLE
Mysterious registry edits should be explained

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#2040]
The page would be improved if you could change this:
"From the desktop of APP1, open an administrator-level Windows PowerShell command prompt, and then run these commands:"

To this:
"From the desktop of APP1, open an administrator-level Windows PowerShell command prompt, and then run these commands to disable Internet Explorer Enhanced Security:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3352c5-eef3-b0ca-0883-d1db6b38bafe
* Version Independent ID: ff14cad8-a6a1-a397-4bb3-af62d823c006
* Content: [Password hash synchronization for your Microsoft 365 test environment - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/password-hash-sync-m365-ent-test-environment?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/password-hash-sync-m365-ent-test-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/password-hash-sync-m365-ent-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@robmacf You are correct on all counts! Updated and published. Thanks so much for letting us know.
