### ISSUE TITLE
Azure AD connect configuration fails

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#2042]
The steps to enable trust for the self-signed certificate need to be repeated on APP1 prior to reconfiguring Azure AD connect. If the server running Azure AD Connect does not trust the self-signed certificate, Azure AD connect will not allow the federation configuration to complete.

(The steps are documented under "Next, use these steps to install the self-signed certificate and configure PROXY1.")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1fbb47-3b21-a60d-f746-7337b5a7481f
* Version Independent ID: 4370ed21-436c-1456-335e-fead720a65ff
* Content: [Federated identity for your Microsoft 365 test environment - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/federated-identity-for-your-office-365-dev-test-environment?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/federated-identity-for-your-office-365-dev-test-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/federated-identity-for-your-office-365-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@robmacf I have updated the procedure to include APP1. Thanks so much for letting me know.
