### ISSUE TITLE
Lack of updates

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2043]
[Enter feedback here]
This page is supposed to be showing us What's New, but it does not get updated very often, only 2 times in the past year. I'm quite sure that there have been many more updates. Please put updating this page into some type of automated process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac42403c-4226-bec2-986d-2e8a67e7c66d
* Version Independent ID: e8e0b323-ee46-f8e7-fe99-cbee91697213
* Content: [What's new in Microsoft Threat Protection - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/whats-new.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
This page gets updated when features go GA.
In general, we update the Preview features topic with capabilities that go into public preview. 
After completing the public preview phase, it goes into GA.
