### ISSUE TITLE
Forwarding email outside organization

### ISSUE THREAD

**Issue by carljohngabato** [MicrosoftDocs/microsoft-365-docs#2044]
This section only applies to mailbox rules. How do you apply it on "Forwarding"?
![image](https://user-images.githubusercontent.com/45403903/82962173-0c91b880-9ff2-11ea-96f9-85c1e82bb94e.png)
https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#6-stop-auto-forwarding-for-email
I followed what was instructed in the article, it works only for mailbox rules. Forwarding on the other hand seems overlooked.

**Comment by msbemba** [comment]
@carljohngabato Thank you for your feedback. Step 6 that you are referring to explains how to Stop auto-forwarding via Transport rule. This should help in forwarding scenarios as well. Meanwhile, The other way to stop forwarding is to set up the remote domain option through the Exchange Online Admin Center > Mail Flow > Remote Domains and select the default remote domain. Uncheck the “allow automatic forwarding” box.

Hope this Helps!

Thanks
Sri

**Comment by mypil** [comment]
@carljohngabato  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
