### ISSUE TITLE
Missing from ToC

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/microsoft-365-docs#2047]
This document isn't shown in the table of contents. Please review where it would fit best so it can be discovered easily.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa19cef-7bad-ac40-1370-4a9b4f8474a8
* Version Independent ID: 42979548-8fc0-596b-b7d6-d79f4f0d734e
* Content: [Search the audit log for user and admin activity - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by dcbrown16** [comment]
Also, if I'm understanding correctly Power Platform Apps like Dynamics should be included in the list.
The Power Platform docs like the one below point to this page.
https://docs.microsoft.com/en-us/power-platform/admin/logging-powerapps

**Comment by markjjo** [comment]
@dcbrown16 Thanks for heads up. This topic hasn't been updated for two years and is deprecated and not indexed for search, so not sure how you accessed it. I'm going to unpublish it and redirect to topic on searching unified audit log. This topic contains link to power apps doc. Dynamics has a single activity and is not currently listed.
