### ISSUE TITLE
To include or exclude an entire location such as all Exchange email

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#2049]
Hello,

I think this part should be changed:
"To include or exclude an entire location such as all Exchange email or all OneDrive accounts, switch the Status of that location on or off";
We can't select a specific mailbox, only the Distribution group(s).
And I hope that members of the Distribution group will be only users to whom the policy is targeted?

![image](https://user-images.githubusercontent.com/39700914/83007979-c437c200-a014-11ea-9c03-32adfde8c1a2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0e7f42-60d0-1f95-57e9-6a24a5d87c2b
* Version Independent ID: 0080b139-e35b-b302-b38c-07a2e2e8c1ef
* Content: [Create a DLP policy from a template - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-dlp-policy-from-a-template?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-dlp-policy-from-a-template.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-dlp-policy-from-a-template.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@lightupdifire  Thank you for the update. You are correct the members of the distribution group will be the only users to whom the policy is targeted or excluded based on the selection. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2252

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba 
Thanks!
