### ISSUE TITLE
03-문구 수정 요청-1206

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/microsoft-365-docs#205]
As-Is
개인 식별 정보 (pii 개인) 보호 하기 위해 정책을 설정 하는 방법에 대 한 예제 서식 파일에서 DLP 정책 만들기 를 참조 하십시오.

To-Be
개인 식별 정보 (PII)로부터 보호 하도록 정책을 설정하는 방법에 대한 예제는 서식 파일에서 DLP 정책 만들기를 참조하십시오.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 1d156f82-2ba0-2d66-a639-1df86554ac83
* Version Independent ID: 4e158c5b-09fd-7214-474f-e7ff44b86d39
* Content: [Microsoft 365 비즈니스 보안 기능](https://docs.microsoft.com/ko-kr/microsoft-365/business/security-features)
* Content Source: [microsoft-365/business/security-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/master/microsoft-365/business/security-features.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
의견을 보내 주셔서 감사합니다. 번역 팀과 협력하여 업데이트를 진행하고 있습니다.
