### ISSUE TITLE
About the SCL -1

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/microsoft-365-docs#2050]
[Enter feedback here]
In the following github issue we discussed the safe senders list; https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1957#event-3367113669

This was updated in the document as followed: 

[!NOTE]
Messages from senders that users have added to their own Safe Senders lists will skip EOP filtering (the SCL is -1). To prevent users from adding entries to their Safe Senders list in Outlook, use Group Policy as mentioned in the About junk email settings in Outlook section later in this topic.

I personally think this will raise some questions and can be more specific

It therefore propose the following change:

[!NOTE]
Messages from senders that users have added to their own Safe Senders lists will skip connection filtering as part of EOP (the SCL is -1). To prevent users from adding entries to their Safe Senders list in Outlook, use Group Policy as mentioned in the About junk email settings in Outlook section later in this topic. Policy filtering, Content filtering and ATP checks will still be applied to the message.

Regards,

Kenneth
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bec871b-790f-6826-b8f8-d1b7830c49ab
* Version Independent ID: 460db4e8-7f93-60a3-4889-f2d8f08fc75f
* Content: [Configure junk email settings on Exchange Online mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kennethvs, OK. Done.

Thanks for the feedback.

Closing
