### ISSUE TITLE
broken link to download NEN7510

### ISSUE THREAD

**Issue by hora7ce** [MicrosoftDocs/microsoft-365-docs#2051]
[Enter feedback here]
link to download file is broken - 

https://protection.office.com/DownloadFile/ServiceAssurance/Document/compliance/Azure%20and%20Office%20365%20NEN7510-2011%20Standard%20Coverage/pdf

![image](https://user-images.githubusercontent.com/57032729/83036050-dfb9c180-a042-11ea-9059-b6892898dfae.png)

please check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0436bb6-1b01-68d5-163e-6f838d47c0cb
* Version Independent ID: 33e1241e-d444-d51a-dc97-55dec81a3ce2
* Content: [NEN 7510 - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-nen-7510-netherlands?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-NEN-7510-Netherlands.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-NEN-7510-Netherlands.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@hora7ce - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/7b8b987311a1f1095d62e15c5500524bc1745510. 


Thank you for your contribution to make the docs better! Much appreciated!
