### ISSUE TITLE
Set the spam confidence level (SCL) to...

### ISSUE THREAD

**Issue by RyanSmith-00** [MicrosoftDocs/microsoft-365-docs#2052]
The document says: "Bypass spam filtering: This sets the SCL to -1, which means the messages will skip spam filtering."

When you use https://outlook.office365.com/ecp/ and create a rule there is no -1 option, the dropdown now says "Bypass spam filtering".

![image](https://user-images.githubusercontent.com/64505593/83067149-61015c00-a023-11ea-9ebd-9e750a7a9e5a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c02536-94a1-b266-fc4f-a159e33832db
* Version Independent ID: e9a44f9d-6d0c-ff49-e8ce-9da02c22a9df
* Content: [Use mail flow rules to the SCL in messages - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-mail-flow-rules-to-set-the-spam-confidence-level-scl-in-messages?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-mail-flow-rules-to-set-the-spam-confidence-level-scl-in-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-mail-flow-rules-to-set-the-spam-confidence-level-scl-in-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Behind the scenes, the SCL is -1, but I can see how that would be confusing, so I fixed it.

Thanks for the feedback.

Closing
