### ISSUE TITLE
Missing "More external sharing settings"

### ISSUE THREAD

**Issue by ryanmck-msft** [MicrosoftDocs/microsoft-365-docs#2053]
An enterprise customer of mine just pointed out that this Docs page is missing any documentation on a portion of this SharePoint Admin Center form - the "More external sharing settings" once you dial up permissions a bit and that section shows up.  Would be great to add that section to this docs page.  Thanks.
![Sharing Docs](https://user-images.githubusercontent.com/65685971/83067970-243a6280-a02d-11ea-9d12-d258c19a4ab3.jpg)
 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01430e56-8d2c-1223-4aa1-f465118b136e
* Version Independent ID: 1d6f936a-f244-9d1a-53da-6a514f63241d
* Content: [Collaborate with guests on a document](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-on-documents?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-on-documents.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-on-documents.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@ryanmck-msft that info is covered in [Manage sharing settings](https://docs.microsoft.com/sharepoint/turn-external-sharing-on-or-off). We can add a link to this article.

**Comment by mypil** [comment]
@ryanmck-msft - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @MikePlumleyMSFT so we will close this issue.


Thank you for your contribution to make the docs better! Much appreciated!
