### ISSUE TITLE
Are there send out RUA reports by Microsoft Office 365?

### ISSUE THREAD

**Issue by aavdberg** [MicrosoftDocs/microsoft-365-docs#2056]
[Enter feedback here]

Are there send out RUA reports by Microsoft Office 365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@aavdberg Thank you for your feedback. A DMARC record invites DMARC reporting organizations to send DMARC aggregate report to the email address mentioned in RUA. It is not sent by Microsoft office 365.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@aavdberg  - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
