### ISSUE TITLE
Typo "findinformation"

### ISSUE THREAD

**Issue by imzahahs** [MicrosoftDocs/microsoft-365-docs#2057]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ddcac62-5092-efa7-4fed-4fdcc8145bba
* Version Independent ID: 648df366-a665-0a8f-4945-4eb7b4b1b4af
* Content: [Find your partner or reseller - Microsoft 365 admin](https://docs.microsoft.com/en-my/microsoft-365/admin/manage/find-your-partner-or-reseller?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/find-your-partner-or-reseller.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/find-your-partner-or-reseller.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@imzahahs - Thank you for pointing this out.

PR #2065 has been created to fix and close this issue once the PR is merged.


Thank you and we appreciate your contribution to make the docs better!
