### ISSUE TITLE
No Settings > Settings > Microsoft 365 Groups in M 365 Admin Center

### ISSUE THREAD

**Issue by pamelamontes01** [MicrosoftDocs/microsoft-365-docs#2058]
[I'm not able to find Settings > Settings > Microsoft 365 Groups in the Microsoft 365 Admin Center. This navigation does not exist in either the new admin center or the old.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
@pamelamontes01 
Pamela, how are you?

The current navigation is 

**Show all** \> **Settings** \> **Org settings** and on the **Services** tab, select **Office 365 groups**.

The name change from Office 365 Groups to Microsoft 365 Groups is rolling out and maybe you won't be able to see it just yet in your tenant.

Besides that, I will propose adding the Show all option to the article.

Thank you
