### ISSUE TITLE
linked info incorrect

### ISSUE THREAD

**Issue by tom-smith00** [MicrosoftDocs/microsoft-365-docs#2061]
The reference to step 8 in the linked content at the bottom of the page takes you to a page that only has 4 steps and does not have information on how to access a core ediscovery case from advanced ediscovery.  section copied below:

Step 3: Go a case in Advanced eDiscovery
After you create an eDiscovery case and add members, you (or any member of the case) can access the corresponding case in Advanced eDiscovery. To access a case in Advanced eDiscovery, see Step 8 in eDiscovery cases in the Microsoft 365 Security & Compliance Center.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518cc4fa-16a4-9793-530f-fcc371273a2d
* Version Independent ID: f07fb0ad-85a3-7159-d9b1-77d188b3d5f0
* Content: [Set up users and cases in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@tom-smith00 Thanks for the heads up. I will update the topic later today to point to this: https://docs.microsoft.com/en-us/microsoft-365/compliance/quick-setup-for-advanced-ediscovery?view=o365-worldwide#accessing-a-case-in-advanced-ediscovery
