### ISSUE TITLE
Can I run all steps in a script together?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#2063]
Can I put Start-ComplianceSearch in a script and then immediately run New-ComplianceSearchAction -Purge right after?  What I'm worried about is the Search still running to find items when the SearchAction -Purge also runs but fails to purge all items because the Search hasn't completed yet. 

If you need the Search to finish first before the SearchAction runs, is there a way have the SearchAction hold or wait until the Search is done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 464a4f5f-8740-79aa-3647-a9b5e351656c
* Version Independent ID: a51103db-92b2-d225-d493-81d624e6fc6b
* Content: [Search for and delete email messages in your organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Canis-Lupis Scripting really isn't supported in this forum and not really relevant to the topic that you logged this github issue against. But, I would suggest a few things:

1. Test it. I wonder if New-CSA cmdlet will return an error saying the search is still in progress. I think that running the New-CSA cmdlet reruns the compliance search that you create with New-CS. So not sure if this is an issue or if pausing the script (see #3) will make a difference.
2. Create two separate scripts. One to create/start the search; one to start New-CSA -Purge. Then you can allow enough time between the running of the search and deleting search results.
3. Delay the running of the New-CSA cmdlet in the script with this line after Start-CS and before New-CSA: **Start-Sleep -Seconds xx**; so, if you wanted to pause the script for 1 minute, it would be Start-Sleep -Seconds 120  -- Not 100% sure it this works that way I describe but you could try.

**Comment by markjjo** [comment]
FYI - Here's another example of Start-Sleep (for 10 seconds)

$search = new-compliancesearch
start-compliancesearch $search.name
do{Start-sleep 10} while{{get-compliancesearch $search.name}.status -ne "Completed"}}
new-compliancesearchaction -Purge

**Comment by Canis-Lupis** [comment]
Yes, thank you. I was curious if the commands as listed in the document needed one to complete before the other ran as it wasn't clarified.
________________________________
