### ISSUE TITLE
Per User: Why and How?

### ISSUE THREAD

**Issue by johnaweiss** [MicrosoftDocs/microsoft-365-docs#2064]
You don't say why per-user MFA isn't recommended. and you don't tell how to do it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@johnaweiss Thank you for your feedback. We have added a note to the document on why it is innt recommended and link to enable it per-user if need be. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2216

Thanks
Sri

**Comment by msbemba** [comment]
@johnaweiss  We have had a facelift to the document and the options have changed. Hope this helps!

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @johnaweiss Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
