### ISSUE TITLE
Multiple maximum possible secure scores

### ISSUE THREAD

**Issue by LeonardoFelippine** [MicrosoftDocs/microsoft-365-docs#2067]
Hello.

I work at a CSP, and as such, I have access to several client tenants, and I observed that the maximum possible secure score changes across different tenants. In my understanding, this is contrary to what the documentation states: "We show you the full set of possible improvements, regardless of license, so you can understand security best practices and improve your score. Your absolute security posture is represented by Secure Score, which stays the same no matter what product licenses your organization owns."

Can you please clarify if I misunderstood it, and if so, what will be taken into consideration to calculate the maximum possible secure score?

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a57c0a2-0a6c-4499-f31e-18016d006549
* Version Independent ID: 5587ca01-e40f-478d-1796-b7b4dc41cbf0
* Content: [Microsoft Secure Score (previous iteration) - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/microsoft-secure-score?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/microsoft-secure-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/microsoft-secure-score.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
@erik-wahlstrom

**Comment by LeonardoFelippine** [comment]
Hello, @mypil 
Would you have any updates on this?

Regards.

**Comment by erik-wahlstrom** [comment]
Hi Leonado, 

There are a couple possibilities here. I cannot be sure, but I suspect this is due to a phased rollout of the new scoring model.  The new scoring model standardized the maximum possible score to 10 points.  In the previous version this number was undefined. 

The new model was rollout out slowly to different customers.  Last week we finally transitioned to 100% on the new model. So now everyone should see the same thing.  

Another possibility is that some controls simply don't apply. For example cloud only tenants shouldn't see controls that only apply to hybrid tenants. 

Can you give specific examples you are seeing?

**Comment by LeonardoFelippine** [comment]
Hello, Erik.

Sorry for the delay.

Below you will see screenshots from two different tenants. Both of them have hybrid identities and pretty much the same licenses:
[cid:e74c79b9-bb61-4f9d-8ed9-2f1f0e482b21]

[cid:2e94dbb8-859f-4f21-b01f-a16060ac1e8c]

As you can see, one of them has pretty much twice as many possible points as the other.

And here you will see the secure score for a demo tenant I have:[cid:e1baf4f1-1388-4b1a-9d72-ec62d53ac58f]

This tenant is cloud only, and has maybe seven times the maximum possible score of the one above, even though they have the same licenses (M365 E5).

By the way, these screenshots were taken either Friday or today, so they are as updated as possible.

Regards,

Leonardo Felippine.
________________________________
De: Erik Wahlstrom <notifications@github.com>
Enviado: terça-feira, 16 de junho de 2020 21:26
Para: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: LeonardoFelippine <leonardo_filippine@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [MicrosoftDocs/microsoft-365-docs] Multiple maximum possible secure scores (#2067)


Hi Leonado,

There are a couple possibilities here. I cannot be sure, but I suspect this is due to a phased rollout of the new scoring model. The new scoring model standardized the maximum possible score to 10 points. In the previous version this number was undefined.

The new model was rollout out slowly to different customers. Last week we finally transitioned to 100% on the new model. So now everyone should see the same thing.

Another possibility is that some controls simply don't apply. For example cloud only tenants shouldn't see controls that only apply to hybrid tenants.

Can you give specific examples you are seeing?

**Comment by erik-wahlstrom** [comment]
@LeonardoFelippine 
Some how your screen shots aren't coming through, all I see is a cid: tag. Ant chance you can retry?

**Comment by LeonardoFelippine** [comment]
Hello, Erik.

Sure, here they are:
- Tenant 1:
![image](https://user-images.githubusercontent.com/40198251/85305734-611b3d00-b4a5-11ea-97f9-09cc59068b57.png)

- Tenant 2:
![image](https://user-images.githubusercontent.com/40198251/85306004-c7a05b00-b4a5-11ea-9dee-8e083641fce8.png)

- Demo tenant:
![image](https://user-images.githubusercontent.com/40198251/85306073-e141a280-b4a5-11ea-8f7c-7c0cf136332a.png)


Regards.

**Comment by erik-wahlstrom** [comment]
Got them. OK for the Demo Tenant, I'm guessing your have MDATP integration enabled. Right now the bulk of our controls are Device controls which are integrated with MDATP. 

For no. 2, I'm guessing you have MCAS. If you are comfortable posting your email address here, I'll contact you offline and can get a little more diagnostic offline.

--Erik

**Comment by LeonardoFelippine** [comment]
Hello, Erik.

You are correct on both assumptions, and that brings me to the question I asked on the original post: based on the documentation, I should see the same maximum possible score, independent of licensing, should I not?

I can contact you through other means (LinkedIn, maybe) and send you my email address.

Regards.
________________________________
De: Erik Wahlstrom <notifications@github.com>
Enviado: segunda-feira, 22 de junho de 2020 15:45
Para: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: LeonardoFelippine <leonardo_filippine@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [MicrosoftDocs/microsoft-365-docs] Multiple maximum possible secure scores (#2067)


Got them. OK for the Demo Tenant, I'm guessing your have MDATP integration enabled. Right now the bulk of our controls are Device controls which are integrated with MDATP.

For no. 2, I'm guessing you have MCAS. If you are comfortable posting your email address here, I'll contact you offline and can get a little more diagnostic offline.

--Erik

**Comment by erik-wahlstrom** [comment]
I can't answer this w/o getting the tenant Id.  If you can send them to me I can verify things. 

Linkedin is fine.

**Comment by yogkumgit** [comment]
@levinec  Kindly answer and help us in resolving this issue. Thanks.

**Comment by levinec** [comment]
This should be resolved. Closing now.
