### ISSUE TITLE
Baseline Policies Deprecated?

### ISSUE THREAD

**Issue by wil16098** [MicrosoftDocs/microsoft-365-docs#2068]
My Azure implementation indicates:
![image](https://user-images.githubusercontent.com/35205628/83271384-68de0f00-a18f-11ea-9c6a-42e271767bc2.png)
"Baseline policies... are no longer enforced, can't be enabled, and will disappear"
But this page, with an 05/27/2020 update stamp, discusses implementation of baseline policies.
This is confusing, because I am looking for Conditional Access guidance for Office 365 Business Premium and )365 business Essentials (Now Microsoft Business Standard and Basic), based on this article which indicates some factors of Conditional Access may be authorized for Business accounts without AD Premium P1:
https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/conditional-access-is-now-part-of-microsoft-365-business/ba-p/684063
I feel that navigating what is and is not allowed is quite difficult, and frequent product changes are not helpful. i understand that development is rapid, but I personally find that substantive, rapid changes in vocabulary, in particular, can be disruptive.
/struggling but grateful for the feedback opportunity,
Edward

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b76e510-b804-710f-fd4e-5ffdebd505fb
* Version Independent ID: f3a14b91-4406-113f-c0bb-f97e7e85484c
* Content: [Set up conditional access policies for Microsoft 365 campaigns - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/set-up-conditional-access-policies?view=o365-worldwide)
* Content Source: [microsoft-365/business/set-up-conditional-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/set-up-conditional-access-policies.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@wil16098 - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.   

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
