### ISSUE TITLE
"Manage" User Templates Means "Delete?"

### ISSUE THREAD

**Issue by klawrawkz** [MicrosoftDocs/microsoft-365-docs#2069]
The term _"manage"_ is misleading when the only actual functionality is _**"delete."**_ I know that this is 365 functionality. The term "manage" is used in the 365 admin UI. It would be _helpful to know up front that the only way to _"manage"_ a template in 365 is to _**"delete"**_ it._ Three different ways to "delete" but not a single means of "editing?" Why? **_Can we_** edit a custom user template in 365? _IMHO, it's not great for end user productivity that the term "manage" means "delete," b/c the typical behavior is to burn a lot of time searching, and searching, and ... for the "management" piece that allows one to **"edit."**_

Thanks,
klawrawkz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a03342-9a4b-cf1d-9a3b-7bdee0fe6b09
* Version Independent ID: 260c8359-f319-0647-ab77-a594ec872b2b
* Content: [Create and use a template to add users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/create-and-use-a-template-to-add-users?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/create-and-use-a-template-to-add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/create-and-use-a-template-to-add-users.md)
* Service: **o365-administration**
* GitHub Login: @SharS
* Microsoft Alias: **v-sharos**

**Comment by msbemba** [comment]
@klawrawkz  Thank you for your feedback. You are correct, there is no way to edit the template at the moment and the only option is to delete or create a new one. I have updated the document accordingly and this can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2253

Once we have an option to edit a template, the document will be updated accordingly. Unfortunately, there is no option to edit at this point in time.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @klawrawkz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by johnsparkmytech** [comment]
Is there a feature request that can be up voted for this?  I can't believe this is still not a feature at this point.

**Comment by Axon-Admin** [comment]
And still this is not an option - come on Microsoft, this is fairly basic functionality

**Comment by ms-fs** [comment]
+1

> And still this is not an option - come on Microsoft, this is fairly basic functionality
