### ISSUE TITLE
GCC Availability

### ISSUE THREAD

**Issue by tcfinney** [MicrosoftDocs/microsoft-365-docs#2070]
Hello,

The [About usage analytics page](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide) has a note at the top stating that M365 Usage Analytics **isn't** available for GCC.

The note at the top of [this page](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide) states that it **is** available for GCC. 

Need to clarify/confirm which is correct....

Thank you,
TC
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by tcfinney** [comment]
Hello - just wanted to get an idea on next steps on this request, please. Thank You.

**Comment by msbemba** [comment]
@tcfinney Thank you for your feedback. The usage analytics is not yet available for GCC. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2458

Thanks
Sri

**Comment by tcfinney** [comment]
Many thanks, @msbemba!  I'll monitor the document for the update :)

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @tcfinney Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
