### ISSUE TITLE
Update Page

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2071]
[Enter feedback here]

I'm quite sure that there have been items released since February. Please update this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e5d5245-ece6-6430-9221-efa0d80b9f6e
* Version Independent ID: 2ad2ab98-14c8-4f5c-70de-6c809f9d8933
* Content: [What's new in the compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @brendonb
* Microsoft Alias: **brendonb**

**Comment by msbemba** [comment]
@DeanGross  Thank you for your feedback. I'm working with the author to publish the missing information. 

Thanks
Sri

**Comment by mypil** [comment]
@brendonb - Can you please share your insights on this issue?

Thank you.

**Comment by robmazz** [comment]
@DeanGross  - thanks for the feedback. There has been some recent process reorganization and this topic will be updated soon. Please check back in a few weeks.
