### ISSUE TITLE
Query based holds language inaccurate

### ISSUE THREAD

**Issue by Robright** [MicrosoftDocs/microsoft-365-docs#2072]
The following is inaccurate: "To create a query-based hold with conditions, complete the following. Otherwise, to preserve all content in the specified content locations, click Next" 

The hold is applied at the site level regardless of any attempt in the query to narrow it down to specific items. The query box has no effect in applying granular holds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7263ba97-4e79-7144-a9d4-5138fe228fa2
* Version Independent ID: 316e242e-7f37-592e-9c8f-e754b23a29ca
* Content: [Create eDiscovery holds in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-ediscovery-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-ediscovery-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us and answer this issue. Thanks

**Comment by markjjo** [comment]
Topic updated with info about eDiscovery hold on site documents. https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide#query-based-holds-placed-on-site-documents
