### ISSUE TITLE
Typo - "user principle name"

### ISSUE THREAD

**Issue by sujitnaray** [MicrosoftDocs/microsoft-365-docs#2075]
Please change "user principle name" to "user principal name"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115cfe0b-c8b5-193d-19da-a6f9c03fdfc0
* Version Independent ID: 4a90cb9e-ce2a-a3f6-4b67-32f45c975323
* Content: [Manage holds in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/managing-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/managing-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/managing-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@sujitnaray - Thank you for pointing this out.


PR #2076 has been created to fix and close this issue once the PR is merged.



Thank you and we appreciate your contribution to make the docs better!

**Comment by markjjo** [comment]
PR merged
