### ISSUE TITLE
multi-user edit in Preview

### ISSUE THREAD

**Issue by paul-rich** [MicrosoftDocs/microsoft-365-docs#2077]
[Enter feedback here]
Hi folks! It is my understanding that co-authoring using the Office Web Apps is already available, either in Preview or GA. This document says that it is still under consideration as a feature, I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@paul-rich Hi Paul!  Yes, co-authoring is now GA when you enable this capability, but I can't find on this page where it says otherwise.  Can you please quote the actual text?

**Comment by cabailey** [comment]
@paul-rich I found one reference that still had "preview" in the title for enabling sensitivity labels for SharePoint and removed this - is this what you meant?  Good example of why I don't like including the release status in the actual title because too easy to miss updating them.  But I still can't find any references to "under consideration as a feature".  Can you let know?

**Comment by cabailey** [comment]
@paul-rich  Will leave open until Monday and then close if I don't hear from you.

**Comment by paul-rich** [comment]
Hi Carol,
Sorry for slow reply. You corrected the reference I came across. Thank you!

**Comment by cabailey** [comment]
Thanks for the update!  Closing.
