### ISSUE TITLE
Dismissed messages no longer exists

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#2078]
This page must be updated regarding terms and screenshots. There are no longer 'dismissed' messages. I think this has been replaced with term 'Archive' and 'Archived messages'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f3771a-247c-4f85-992a-e671285c70bd
* Version Independent ID: f3c2890a-2470-9349-ff77-924cf8566365
* Content: [Manage messages in Message center - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/manage/manage-messages?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-messages.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@GiantCrocodile Thank you for your feedback. We have made changes to the document accordingly and the same can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2254

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GiantCrocodile 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
