### ISSUE TITLE
Link to download a copy of the poster gives 404 error

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/microsoft-365-docs#208]
The link to the poster https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/raw/live/Enterprise/Media/Microsoft365Enterprise.pdf is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9377794-433d-4522-0b01-e9182283019a
* Version Independent ID: 9d9134d2-adaf-64df-ab10-780d9e5ca1b1
* Content: [Microsoft 365 Enterprise overview](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-overview)
* Content Source: [microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-overview.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by robmazz** [comment]
@bartvermeersch - Thanks for your feedback, I'll get this over to the Enterprise writing team for clarification/correction.

**Comment by JoeDavies-MSFT** [comment]
@bartvermeersch I have updated the link and it should work. Thanks for letting us know.
