### ISSUE TITLE
Add info about mailbox limit < 10 MB

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#2080]
Hello,

I got this warning in 'Publish labels' wizard in Microsoft 365 compliance panel and found no documentation about this limitation:

> It will take up to 1 day for labels to appear to your users. Labels will appear in Outlook and Outlook web app only for mailboxes that have at least 10 MB of data. 

Please add this information to the docs and an explanation for this limitation.

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57908eea-077f-363c-8d51-3b8335914f4c
* Version Independent ID: 0d1421f1-b546-677f-ef3b-7e3da294b5ef
* Content: [Create and publish sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@GiantCrocodile  We've documented the 24 hours wait in many places - for example, on this page "Typically, users see the labels in their Office apps within a couple of hours. However, allow up to 24 hours for your label policies and any changes to them to replicate to all users and services."

The limitation of 10 MB for Exchange is something I wasn't aware of for sensitivity labels and will investigate.

**Comment by cabailey** [comment]
@GiantCrocodile Can you confirm you definitely saw this message for sensitivity labels, and not retention labels?  You filed the issue on the page for sensitivity labels and when I create a sensitivity label policy I see only "Your sensitivity label policy has been created."

For retention labels, we have documented the 10 MB limitation, but say it can take up to 7 days for Exchange: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-labels?view=o365-worldwide#published-retention-labels

"If you publish retention labels to SharePoint or OneDrive, it can take one day for those retention labels to appear for end users. In addition, if you publish retention labels to Exchange, it can take 7 days for those retention labels to appear for end users, and the mailbox needs to contain at least 10 MB of data."

**Comment by GiantCrocodile** [comment]
@cabailey Actually I saw this message during the creation of a label policy. I wasn't able to find a label policy dedicated article but only mentions about it in this and other articles. As an admin, I would read this page and do use the suggested policy wizard which afterwards suggest to use a label policy to publish the label so your freshly created label is available to users. That's why I was wondered the info isn't given on this article or earlier as it might make your work useless if you have tiny mailboxes.

**Comment by cabailey** [comment]
@GiantCrocodile  But what type of label policy when you saw this message - were you in the "Information protection" solutions section in the compliance center where they have label policies for sensitivity labels (the documentation for this page), or were you in the "Information governance" or "Records management" sections where they have label policies for retention labels?  

The documentation for publishing retention label policies is here: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-labels  On that page, we do have the information about the 10 MB limitation and delay for when labels appear for users.

**Comment by GiantCrocodile** [comment]
@cabailey I was here: https://security.microsoft.com/retention?viewid=retentionlabelpolicies doing records management. I think I might have found only the first paragraph about the 10 MB limit on the page you linked to and just missed the 2nd paragraph about it. I might have discarded the first paragraph as relevant bec. I wasn't doing auto labeling.

**Comment by cabailey** [comment]
@GiantCrocodile  Thanks for the update.  I'm going to close this then, because it's filed against the documentation for creating sensitivity labels and their policies, and these labels don't have this 10 MB limitation for Exchange. It is documented where we have instructions for retention labels and their policies, but I will flag to engineering about the 1 day message, which seems correct for SharePoint and OneDrive, but the docs actually state 7 days for Exchange.
