### ISSUE TITLE
Instructions are outdated based on existing interface

### ISSUE THREAD

**Issue by glenlewis** [MicrosoftDocs/microsoft-365-docs#2081]
Where the phrase 

In the admin center, go to the Settings > Settings page.

It should be replaced with

In the admin center, go to the Settings > Org settings page.

As this is what appears on the page as of 1st June 2020.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad408574-36cc-9b96-f092-58a68708d3a0
* Version Independent ID: 97adbc3d-8f71-a6de-25c3-f9400125f885
* Content: [Let users reset their own passwords - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/let-users-reset-passwords?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/let-users-reset-passwords.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/let-users-reset-passwords.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by PrasadKasireddy** [comment]
@glenlewis  - Thanks for reporting the issue, I will update the change through PR.
