### ISSUE TITLE
Keyword 'tfn' mssing from Australian Tax File Number definition

### ISSUE THREAD

**Issue by acmcg** [MicrosoftDocs/microsoft-365-docs#2084]
Keyword 'tfn' mssing from Australian Tax File Number definition documentation, but is in the policy definition:
<code>
   <Keyword id="Keyword_Australia_Tax_File_Number">
      <Group matchStyle="word">
        <Term>australian business number</Term>
        <Term>marginal tax rate</Term>
        <Term>medicare levy</Term>
        <Term>portfolio number</Term>
        <Term>service veterans</Term>
        <Term>withholding tax</Term>
        <Term>individual tax return</Term>
        <Term>tax file number</Term>
        <Term>tfn</Term>
      </Group>

</code>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [Sensitive information type entity definitions - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-entity-definitions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitive-information-type-entity-definitions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitive-information-type-entity-definitions.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@acmcg Thank you for your feedback. We have added tfn to the keywords via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2257

Thanks
Sri

**Comment by chrfox** [comment]
queried PM for accuracy
