### ISSUE TITLE
Add content for keywords

### ISSUE THREAD

**Issue by acmcg** [MicrosoftDocs/microsoft-365-docs#2085]
Documentation should include instructions on how copy keywords from the original rule definitions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1391cf1-588f-a4a9-8692-8c07cf1e459a
* Version Independent ID: d57337a5-d0f3-de26-2259-6b7fa7613d05
* Content: [Customize a built-in sensitive information type - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customize-a-built-in-sensitive-information-type?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customize-a-built-in-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customize-a-built-in-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @acmcg  - Thank you for your comment, this is the first time this has been requested.  If more requests come in for this we'll consider the change.
