### ISSUE TITLE
Can this be updated for MFA

### ISSUE THREAD

**Issue by FindsTheLost** [MicrosoftDocs/microsoft-365-docs#2086]
I used this fine till this year now its failing on adding sharepoint. I have to connect to everything prior to running and # comment out the connect to exchange as it doesn't use MFA. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b759021-39d7-0383-2f50-b5b813217f97
* Version Independent ID: 5f5dfeab-1160-3994-2cb8-1ca7c67e3ff2
* Content: [Use a script to add users to a hold in an eDiscovery case in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@FindsTheLost Thanks for heads up. I'll look into updating script as per your suggestion or adding a note. Did you just comment out the lines related to connecting to SCC PowerShell? Did you have to comment out lines related to SPO PowerShell?
