### ISSUE TITLE
Roles assignments unclear or don't work

### ISSUE THREAD

**Issue by tjsawyer** [MicrosoftDocs/microsoft-365-docs#2088]
The roles needed for this feature do not make any sense.  The documentation is too vague and it seems the minimal level of access needed to grant someone reviewer rights basically gives them admin capabilities to all the Communications Compliance capabilities.  There are also several "Communications Compliance" roles available now in the permissions screen that have no documentation whatsoever.   

What we need is for a reviewer to be able to go to https://compliance.microsoft.com/supervisoryreview?viewid=Policies

and SEE the policies configured (not be able to edit them) and then to click into the policies themselves to perform their review functions.   A reviewer should be just that -- someone who can log in and review - not have access to change other things.  This is a simple 'least access' control that should be implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42670ffb-8024-7cc2-cb1b-27cec02cc223
* Version Independent ID: fa22f173-b62e-93cb-62f2-e6ad0b4739d8
* Content: [Get started with communication compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-configure.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@tjsawyer - thanks for this feedback. The roles and permissions for communication compliance are currently being updated to address these issues. As the feature role improvements are released later in July, the documentation will also be updated. Please check back at the end of July for these improvements.
