### ISSUE TITLE
From where can I downlaod

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/microsoft-365-docs#209]
Sir as a windows 10 end users,  where can the users download windows analytics upgrade readiness tool,
If possible give me the direct downloading link 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddfe050b-6adb-bd3c-3326-f7cc94b0ca5c
* Version Independent ID: 566540f3-e512-f931-2e8d-492ae03e07af
* Content: [Step 1 - Device and App Readiness](https://docs.microsoft.com/en-us/microsoft-365/enterprise/step-1-device-and-app-readiness#recommended-tool-windows-analytics-upgrade-readiness)
* Content Source: [microsoft-365/enterprise/step-1-device-and-app-readiness.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/step-1-device-and-app-readiness.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Hi! Please see the following docs article on how to get Windows Analytics setup - https://docs.microsoft.com/en-us/windows/deployment/update/windows-analytics-azure-portal

Thanks!

**Comment by RAJU2529** [comment]
Thanks sir
