### ISSUE TITLE
Infite/Query Based Holds with no location

### ISSUE THREAD

**Issue by Mlavieri** [MicrosoftDocs/microsoft-365-docs#2090]
When working with a query based hold no results are returned when a location is not specified. 

Could you please provide clarification where the docs states: 

> You create an infinite hold where all content is placed on hold. Alternatively, you can create a query-based hold where only the content that matches a search query is placed on hold.

Does the functionality to place a Hold on all content based on criteria exist or should this read something along the lines of 'a query based hold where only the content _in the specified locations_ that matches a search query'

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7263ba97-4e79-7144-a9d4-5138fe228fa2
* Version Independent ID: 316e242e-7f37-592e-9c8f-e754b23a29ca
* Content: [Create eDiscovery holds in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-ediscovery-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-ediscovery-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Mlavieri Not sure I understand. You have to select content locations to apply holds to. In the workflow of the holds wizard, you have to select locations before you specify a query. I guess I can see some confusion in this statement: "You create an infinite hold where all content is placed on hold." That is all content in the specified locations. The point of that sentence is that by not specifying a query, then all content is preserved. Similar to a search: if you don't specify an keywords or conditions, all content is returned. 

I will update topic as per your suggestion.

**Comment by Mlavieri** [comment]
Thanks Mark. Part of the reason I needed some clarification is that In both Core and Advanced eDiscovery the wizard does allow you to progress without specifying a location, just no data will be returned. 

![image](https://user-images.githubusercontent.com/1187519/83444908-b2d62780-a411-11ea-97df-a783850e773e.png)

**Comment by markjjo** [comment]
@Mlavieri Thanks for follow up. Though not great wizard design, no content on hold would be the expected behavior if no content locations are selected. You will also note that there is no org-wide toggle switch to include all mailboxes or all sites (the toggle is present in the search wizard), which also implies you have to specify individual mailboxes/sites to place on hold.

I can add something about this in the step on specifying content locations. You might consider providing this feedback (wizard doesn't force you to select content location) at https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=139404

**Comment by Mlavieri** [comment]
That makes sense and agreed that the difference between the experiences would imply that a location would have to be specified but just wanted to confirm it wasn't all by default. 

I've created a user voice to force a location be entered for anyone else who may see this: https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/40561987-force-specifying-at-least-one-location-when-creati

Thanks for your help and quick responses @markjjo
