### ISSUE TITLE
Supported countries limit?

### ISSUE THREAD

**Issue by BrianLevenson** [MicrosoftDocs/microsoft-365-docs#2091]
The list of countries where the M365 Admin Center supports third party subscriptions is a small subset of where customers can purchase SaaS subscriptions from Microsoft AppSource. Can the team please verify that list and provide guidance on what to do if the customer has purchased from a country where this experience is not available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7cf7a2d-2bf1-c605-f3c6-299cb55efa89
* Version Independent ID: 550ec250-27de-0553-324e-f30efa48f034
* Content: [Manage software-as-a-service apps for your organization](https://docs.microsoft.com/en-us/microsoft-365/commerce/manage-saas-apps?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/manage-saas-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/manage-saas-apps.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@BrianLevenson Thank you for your feedback. Unfortunately, this feature of activating/managing third party applications is only supported in certain countries as mentioned here -  https://docs.microsoft.com/en-us/microsoft-365/commerce/manage-saas-apps?view=o365-worldwide#supported-regions

Customer's who purchased M365 from a country that is not supported will have to wait. The document will be updated as soon as there are new regions added to the list.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@BrianLevenson - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
