### ISSUE TITLE
API's for Office 365 ATP are not updated.

### ISSUE THREAD

**Issue by NikhilMhatre09** [MicrosoftDocs/microsoft-365-docs#2093]
Hello,

The API's mentioned in this document are not updated. I am not able to see any API which are related to Office 365 ATP.

BR,
Nikhil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1245b43f-721b-0bd0-b081-5307b5537e57
* Version Independent ID: d9ffc009-5576-9174-cc7c-b7caef1bb82b
* Content: [SIEM integration with Advanced Threat Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/siem-integration-with-office-365-ti?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/siem-integration-with-office-365-ti.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/siem-integration-with-office-365-ti.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Greetings! Thank you @NikhilMhatre09 for raising this question. I have reached out to the product team for an update here. Will post an update as soon as i know more.

**Comment by denisebmsft** [comment]
Hello @NikhilMhatre09 and @yogkumgit. I have been in conversation with our product team and they assure me that the current documentation (such as this article https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema) is up to date. If you continue to have trouble with this, please open a service ticket and let me know. Thanks!
