### ISSUE TITLE
Rule priority

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/microsoft-365-docs#2094]
[Enter feedback here]

Regarding section:
"When content is evaluated against rules, the rules are processed in priority order. If content matches multiple rules, the rules are processed in priority order and the most restrictive action is enforced. For example, if content matches all of the following rules, **Rule 3** is enforced because it's the highest priority, most restrictive rule:"

.. Should this not be Rule 6 that is enforced if they are processed in priority order? (not Rule 3)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @challengelogic 
Thanks for your comment.  Rule three is higher priority than rule 6 and they are equally restictive, so the highest priority, most restrictive rule is applied, which is rule 3
