### ISSUE TITLE
Suggestion: Add Spam bypass for spam emails being reported & BCC'd onsite

### ISSUE THREAD

**Issue by emardee** [MicrosoftDocs/microsoft-365-docs#2095]
Hi. I have just followed these instructions to create a rule to add a BCC redirect to a spam monitoring shared mailbox for any emails that my staff send to Microsoft for spam reclassification purposes. However it struck me that letting such messages pass unhindered through the spam filter might also be important to make sure they definitely arrive correctly. Therefore I suggest adding the following extra action to the instructions on this page (either before or after the BCC action):
  
Modify the message properties > Set the spam confidence level (SCL) > Bypass Spam Filtering.

I hope this helps improve these instructions for those following behind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88f35e41-4289-a328-cea0-a71f4862c424
* Version Independent ID: c60b5e14-0a43-d9cb-9d98-65cd82910be5
* Content: [Use mail flow rules to see what your users are reporting to Microsoft - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-mail-flow-rules-to-see-what-your-users-are-reporting-to-microsoft?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-mail-flow-rules-to-see-what-your-users-are-reporting-to-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-mail-flow-rules-to-see-what-your-users-are-reporting-to-microsoft.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@emardee, it depends on the reporting method, but in most cases, the good/bad/suspect message is sent to Microsoft as an attachment in a new email message to preserve the original message headers, so I don't think there's a requirement for the message to bypass spam filtering. It probably won't hurt, but I don't think it's required.

**Comment by emardee** [comment]
Fair enough. You are probably right. I wasn’t sure… but I thought since we know the attachment is probably spam, and we are trying to let it through, why risk the spam filter possibly blocking it. 😊

 

Thanks for responding.

 

Mike

**Comment by mypil** [comment]
@emardee - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @chrisda so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
