### ISSUE TITLE
no precise information on enabling office 365 user based MFA settings

### ISSUE THREAD

**Issue by ranabanerjee15** [MicrosoftDocs/microsoft-365-docs#2098]
No Precise Information on how and where to navigate to enable/enforce Office 365 MFA for user-based setting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?redirectSourcePath=%252fen-us%252farticle%252f8f0454b2-f51a-4d9c-bcde-2c48e41621c6&view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@radiantspace Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2472

Thanks
Sri

**Comment by Sirkkuw** [comment]
@msbemba  - the PG advice is to NOT to use the per person MFA. This will go away.

**Comment by msbemba** [comment]
Thank you@Sirkkuw . @ranabanerjee15 Thank you for your feedback. This feature of Per person is going to go away and the Product group advise is not to use this feature.

@yogkumgit This can be closed as there is no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @ranabanerjee15 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
