### ISSUE TITLE
Please clarify the sender scope in the page

### ISSUE THREAD

**Issue by lytao** [MicrosoftDocs/microsoft-365-docs#2099]
Hello,

I am a bit confused about the sender mentioned in the page. It can be envelope sender (5321.MailFrom), or the From header (5322.From).

I did tests couple of years ago and seems the blocked sender list in policy just work for 5321.MailFrom only. I did same kinds of test these days:
- If 5322.From is matched by the block list, the messages got blocked with SFV:BLK, so that means it works for 5322.From as well.
- If 5321.MailFrom is matched by the block list, I got SFV:SPM which indicates the message is actually blocked by content scanning instead of sender blocked. That could because of unmatching between 5322.From and 5321.MailFrom. 

Anyway, I'd be appriciated if there is clear definitions about the sender, just like what is documented in the page [Create safe sender lists in EOP](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide):
Safe sender lists and safe domain lists in anti-spam policies in EOP inspect both the 5321.MailFrom and 5322.From addresses. Outlook Safe Senders only uses the 5322.From address.

thanks.
Tao Ling Yong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79bb5c3-e92a-583b-337a-1a038e50f064
* Version Independent ID: 253ccf77-2d74-dd95-2686-a8fcdc424c7a
* Content: [Create blocked sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@lytao, OK. I added the similar information from the safe sender lists topic.

Is this satisfactory?

**Comment by lytao** [comment]
Thank you for the quick response. I am still not quite sure 5321.MailFrom is inspected because the header SFV:SPM appear instead of SFV:BLK, but I can try to dig further. The document is clear enough.
You can close the issue. Thanks again.
