### ISSUE TITLE
Great article 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/microsoft-365-docs#210]
If possible, please upload applied settings ,with screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89a6189e-5f83-9a61-3700-aca7c8f0e874
* Version Independent ID: 31baf625-0f4e-71ab-7f8f-356d29365bad
* Content: [Step 5 - Security and Compliance Considerations](https://docs.microsoft.com/en-us/microsoft-365/enterprise/step-5-security-and-compliance)
* Content Source: [microsoft-365/enterprise/step-5-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/step-5-security-and-compliance.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Hi - what applied settings are you referring to that you would like to see screen shots of? Thanks!

**Comment by RAJU2529** [comment]
yes sir,  screenshots please, so that I can get some ideas , to apply or modify the settings.
Thanks for reply sir
