### ISSUE TITLE
Very confusing link in the "Turn on Targeted release" section

### ISSUE THREAD

**Issue by justadakaje** [MicrosoftDocs/microsoft-365-docs#2102]
The "Turn on Targeted release" section, step 2 appears to be a repeat of the first step, but appears to be a Chinese link? I think this section of the page needs to be edited with the appropriate regional URLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd08ca2-db5b-898f-8702-49698e7fe4b2
* Version Independent ID: b6696fd0-1739-14ba-7db7-8b50b1bdf344
* Content: [About the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/microsoft-365-admin-center-preview?view=o365-worldwide)
* Content Source: [microsoft-365/admin/microsoft-365-admin-center-preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/microsoft-365-admin-center-preview.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by pebaum** [comment]
looks like this issue is resolved. cant repro.
