### ISSUE TITLE
Unable to assign a specific Teams channel to a communication compliance policy

### ISSUE THREAD

**Issue by deividfoggi** [MicrosoftDocs/microsoft-365-docs#2103]
Consider the following statement:

"For Teams Channel communications: Assign every Microsoft Teams channel or Microsoft 365 group you want to scan that contains a specific user to the communication compliance policy. If you add the same user to other Microsoft Teams channels or Microsoft 365 groups, be sure to add these new channels and groups to the communication compliance policy." 

But when you are creating a policy, you can only assign users and/or groups. I can't find a way to assign a specific Teams channel during the steps to either create or edit a policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea1461c-a9db-d934-d5a6-169360842e8b
* Version Independent ID: 6b214386-6f18-9de6-7a8b-b78e69d1387a
* Content: [Communication compliance feature reference - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-feature-reference?view=o365-worldwide#groups-for-supervised-users-and-reviewers)
* Content Source: [microsoft-365/compliance/communication-compliance-feature-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-feature-reference.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@deividfoggi - thanks for the feedback, I'll make this is clearer that you need to make sure you select "Teams" in the Location page in the policy wizard to support Teams channels. Check back for feature and documentation updates later this month!
