### ISSUE TITLE
The instruction is not working

### ISSUE THREAD

**Issue by cupidchan** [MicrosoftDocs/microsoft-365-docs#2104]
I follow the exact same instruction but found out that Cmdlet provided in the Step 2 are not working. For example, Connect-AzureAD and Get-AzureADDirectorySetting just not there in module AzureADPreview. I also tried AzureAD.Standard.Preview but it also doesn't work. My PowerShell version is 7.0.1. Can you please confirm that the script provided in Step 2 is still valid?

Thanks,
Cupid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?redirectSourcePath=%252fen-ie%252farticle%252fmanage-who-can-create-office-365-groups-4c46c8cb-17d0-44b5-9776-005fced8e618&view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello @cupidchan Cupid how are you?
That's maybe because you are using PowerShell Core (7.0.1) and not Windows PowerShell, can you try running the AzureADPreview module [from Windows PowerShell](https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0)? 

I tried and had no issues.

Thanks

**Comment by cupidchan** [comment]
Hello:

I am using MacOS. Is Windows PowerShell only for Windows OS? I thought PowerShell is now cross-OS.

Thanks,
Cupid

On Jun 17, 2020, at 9:44 PM, Andres Mariano Gorzelany <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello @cupidchan<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcupidchan&data=02%7C01%7C%7C2b1a69a5db624a77f3b608d813291f07%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637280414613731189&sdata=b44yr9fv5x4FX05lrqGPPbMcnD0TWO2B0iJoVZ3ZPsY%3D&reserved=0> Cupid how are you?
That's maybe because you are using PowerShell Core (7.0.1) and not Windows PowerShell, can you try running the AzureADPreview module from Windows PowerShell<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fazure%2Factive-directory%2Finstall-adv2%3Fview%3Dazureadps-2.0&data=02%7C01%7C%7C2b1a69a5db624a77f3b608d813291f07%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637280414613731189&sdata=MUpe%2B82o11xZiBGzZ7ns4DUUYkIaiWXJl868CK%2F4LVc%3D&reserved=0>?

I tried and had no issues.

Thanks

**Comment by get-itips** [comment]
@cupidchan Cupid

PowerShell 7+ is cross OS like you say, however, AzureADPreview is still not ready for that version and you have to use Windows PowerShell (that only runs on Windows)
You can see [here](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/module-compatibility?view=powershell-7) the list of modules that are now ready to be used on PowerShell 7.

Hope this information helps you.

**Comment by cupidchan** [comment]
Thanks! Do you have any timeline for getting AzureADPreview ready for PowerShell 7+?

Regards,
Cupid

**Comment by get-itips** [comment]
> Thanks! Do you have any timeline for getting AzureADPreview ready for PowerShell 7+?
> 
> Regards,
> Cupid

I don't, sorry, However, I recommend monitoring https://techcommunity.microsoft.com/ and https://www.powershellgallery.com/packages/AzureADPreview/ for updates.

**Comment by mypil** [comment]
@cupidchan - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
