### ISSUE TITLE
Number of day messages are quarantined is slightly off

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/microsoft-365-docs#2105]
In the "How long are messages kept in the quarantine?" section, it states that messages are kept in quarantine for 30 days before being deleted automatically.  In reality, the messages are kept about 28 or 29 days, depending on the time of day they were quarantined.

If looking at the Expires and Received dates and times in the Security & Compliance Center, the difference between them ranges from just over 29 days to just under 30 days, depending on the time of day the message was received.  However, I noticed that, even though Expires shows 8:00 PM, the oldest messages start becoming inaccessible shortly after midnight (Eastern time).  This means that messages actually become inaccessible between 28 days and 4 hours after being received to 29 days and 4 hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd59e09-8b82-5c4e-a06f-3e468c9c3273
* Version Independent ID: 2ec32405-bc7a-60f2-782b-b527a2746b11
* Content: [Quarantined messages FAQ - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@VShrubowich, at this point, your best course of action is to open a support request.

**Comment by mypil** [comment]
@VShrubowich - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
