### ISSUE TITLE
What are the default EOP Outbound Spam Policy limits?

### ISSUE THREAD

**Issue by EricSMurphy** [MicrosoftDocs/microsoft-365-docs#2108]
When configuring the Outbound Spam Policy in the Office 365 Security and Compliance portal, the section for setting recipient limits (i.e. external hourly limit, internal hourly limit and daily limit, etc.) isn't clear as to what the default of 0 means, it just says "specify 0 to use defaults or a value between 0 and 10,000." [The doc guidance ](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide#use-the-security--compliance-center-to-create-outbound-spam-policies) just says. "the default value of 0, which means the service defaults are used...". Exactly what does the default value of 0 represent? [Adding clarity here would be helpful.](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide#eop-outbound-spam-policy-settings) Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Office 365 ATP security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, security baselines, baselines for EOP, baselines for ATP, setup ATP, setup EOP, configure ATP, configure EOP, security configuration - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide#eop-outbound-spam-policy-settings)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by EricSMurphy** [comment]
Hello, any update/answer here? Wanted to get this answered for a customer. Feel free to ping me offline if that's easier "ericsco". Thanks!

**Comment by chrisda** [comment]
@EricSMurphy, [The doc guidance](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy#use-the-security--compliance-center-to-create-outbound-spam-policies) that you mentioned says this:

> A valid value is 0 to 10000. The default value is 0, which means the service defaults are used. For more information, see [Sending limits across Microsoft 365 options](https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits-across-office-365-options).

Also, the parent conceptual topic about [outbound spam](https://docs.microsoft.com/microsoft-365/security/office-365-security/outbound-spam-controls#how-eop-controls-outbound-spam) says this:

> We don't advertise the exact limits so spammers can't game the system, and so we can increase or decrease the limits as necessary. The limits are high enough to prevent an average business user from ever exceeding them, and low enough to help contain the damage caused by a spammer.

Safe to say, the value must be between 1 and 10000.

In regards to your specific request for the specific topic, I added a link to the sending limits in the Service Description.

Thanks for the feedback.

Closing.

P.S.: If you have any further questions, please follow up in email (I see you are a Microsoft employee).
