### ISSUE TITLE
Customer Lockbox settings moved

### ISSUE THREAD

**Issue by hobbsenigma** [MicrosoftDocs/microsoft-365-docs#2110]
The instructions to turn on the Customer Lockbox are no longer accurate.  Please update!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@hobbsenigma Thank you for your feedback. We have made changes to the document with the updated steps. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2459

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @hobbsenigma Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
