### ISSUE TITLE
More detail needed on licensing

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/microsoft-365-docs#2114]
Is this in Office 365 ATP Plan 1 or Plan 2?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by kshi-docs** [comment]
This is not using the Office 365 ATP plans - from the licensing perspective, this feature is only available for Microsoft 365 E5 and Microsoft 365 E5 Security SKUs.

**Comment by ArttuArstila** [comment]
Hi, and thanks for the reply! Perhaps good to clarify that also in the text (not included in Office 365 ATP plans), as the technology has O365 ATP in its name.

**Comment by chrisda** [comment]
@ArttuArstila, done. Thanks for the feedback.

Closing
