### ISSUE TITLE
examples of X-Forefront-Antispam-Report and X-Microsoft-Antispam headers needed

### ISSUE THREAD

**Issue by rpremuz** [MicrosoftDocs/microsoft-365-docs#2115]
The article should give a few examples of X-Forefront-Antispam-Report and X-Microsoft-Antispam headers with some fields and values explained here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by metc** [comment]
I had the same issue has you. I finally used this tool (https://mha.azurewebsites.net/) as mentioned in the documentation. This tool decoded the Forefront Antispam Report Header field for me. For instance, information like Spam Confidence Level or Spam Filtering Verdict are extracted for you.

**Comment by chrisda** [comment]
@rpremuz, I jumped in and prepared to update the topic, yet, there are tons of header values documented for [X-Forefront-Antispam-Report](https://docs.microsoft.com/microsoft-365/security/office-365-security/anti-spam-message-headers#x-forefront-antispam-report-message-header-fields) and the one and only value that's present for [X-Microsoft-Antispam](https://docs.microsoft.com/microsoft-365/security/office-365-security/anti-spam-message-headers#x-microsoft-antispam-message-header-fields) (the BCL value) is documented.

So are you asking for a big example header with all of those values separated by spaces on one big line? I'm not sure I see the value of that.

The current section for X-Forefront-Antispam-Report states:

> Other fields in this header are used exclusively by the Microsoft anti-spam team for diagnostic purposes.

The implication is, yeah, there might be other values present, but we don't want to talk about them.

Or am I missing something?

**Comment by rpremuz** [comment]
I asked for examples of X-Forefront-Antispam-Report and X-Microsoft-Antispam headers because the article does not explain how header fields are combined together in the header.
In the meanwhile I found some emails in my inbox that have X-Forefront-Antispam-Report line in its header - here is a section of such header line:
`x-forefront-antispam-report: CIP:255.255.255.255;CTRY:;LANG:hr;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:AM4PR0401MB2308.eurprd04.prod.outlook.com;PTR:;CAT:NONE;SFTY:;`
From that example I understand that header fields are all joined together and each field ends with ";".
That is the information I was looking for.

**Comment by chrisda** [comment]
@rpremuz, I understand. That I can do. And I did.

Thanks for the feedback.

Closing
