### ISSUE TITLE
A part of the page is still saying "EDM is currently not supported in SharePoint"

### ISSUE THREAD

**Issue by taasakur** [MicrosoftDocs/microsoft-365-docs#2116]
To my understanding [the latest change](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/518f3c76d31f87b05ce4c04cf4534d6d55ccc083#diff-6e4ac536d0718658c738e0a00495efa4) was aimed at reflecting the recent addition of EDM support for SharePoint Online. However, the following part still says it is NOT supported, which makes the whole page pretty much confusing.

> 6. In the Status column, select Exchange email, OneDrive accounts, Teams chat and channel message , and then choose Next. (**Note: EDM is currently not supported in SharePoint sites and DLP policy will not detect files in Sharepoint for EDM**)

Could you please fix this? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
HI @taasakur 

Great catch! you are right, document updated and re-published.  Thank you!
