### ISSUE TITLE
Authenticator QR code can't be obtained any more?

### ISSUE THREAD

**Issue by macosmin** [MicrosoftDocs/microsoft-365-docs#2118]
[Enter feedback here]
How am I suppose to get the QR code again, in case I've uninstalled Authenticator from my mobile phone (because Teams on Android had trouble connecting and instructed me to reinstall Authenticator)?
As seen in the video on the page, there was a step where it should have asked for my mobile phone number -- this step I don't remember doing... maybe I did...
Now I'm moving back and forth: Logging in asks for code on my Authenticator app,
my Authenticator app asks for QR code or to enter manually a Code and URL, which I can't obtain any more.
In the video maybe you should have mentioned a screenshot of the QR code may help for troubleshooting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5f3d8d-c63f-d4ca-c310-36d9b91cd936
* Version Independent ID: c8b33fd1-75de-d2bf-27cc-6a9aa8f7826e
* Content: [Set up multifactor authentication - Microsoft 365 for Campaigns](https://docs.microsoft.com/en-us/microsoft-365/campaigns/m365-campaigns-multifactor-authenication?view=o365-worldwide)
* Content Source: [microsoft-365/campaigns/m365-campaigns-multifactor-authenication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/campaigns/m365-campaigns-multifactor-authenication.md)
* Service: **o365-administration**
* GitHub Login: @samanro
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@macosmin Thank you for your feedback. The Microsoft Authenticator app backs up your account credentials and related app settings, such as the order of your accounts, to the cloud. After backup, you can also use the app to recover your information on a new device, potentially avoiding getting locked out or having to recreate accounts. The instructions can be found here -https://docs.microsoft.com/en-us/azure/active-directory/user-help/user-help-auth-app-backup-recovery

In case if you still have trouble getting in the account, I would recommend creating a support ticket with the O365 technical support team.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @macosmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
