### ISSUE TITLE
Clarify encryption label limits

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/microsoft-365-docs#2119]
Near the end of the 'What label policies can do' section, just before "Label policy priority (order matters)" section  it reads, "There is no limit to the number of sensitivity labels that you can create and publish, with one exception: If the label applies encryption, there is a maximum of 500 labels".
It's not clear to what the maximum applies:

Is that 500 labels total as long as at least one has encryption ?  Or just 500 with encryption with an unlimited number of labels not encrypted? 

Is that limit then applicable to a single Label Policy ? Or, across all the Label Policies ? 

If the same label is used in multiple Label Policies, is it counted just once or for each instance it is used?

If it's 500 total labels when encryption is used across all label policies then 500 is the maximum and it might be good to make that explicit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Learn about sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bholzmmc  Thanks for the question, I'll clarify in the docs. The 500 limit is for creating and storing the backend protection templates that get automatically created when you configure a label for encryption.  So you can have 500 labels that include encryption and use these labels repeatedly in different policies. There is no limit to the number of labels without encryption because these don't create backend protection templates.

**Comment by bholzmmc** [comment]
Hi Carol,

A follow-up question, are ‘Archived’ templates counted as well as Published ones toward the 500 limit.

Thanks,

Brian

Brian Holzman, Storage Engineer
Marsh & McLennan Companies
Global Technology Infrastructure (MGTI) | Enterprise Systems Engineering
121 River Street, Hoboken, NJ 07030, USA
+1 201 284 3076 | Fax +1 201 256 8076 | brian.m.holzman@mmc.com<mailto:brian.m.holzman@mmc.com>
www.mmc.com<http://www.mmc.com/>

**Comment by cabailey** [comment]
@bholzmmc  Yes.  Very few customers hit this limit but if you do, evaluate whether you really need old templates and if not, delete them.  But do an export first, as a backup.  More info: https://docs.microsoft.com/en-us/azure/information-protection/configure-templates-with-powershell

**Comment by bholzmmc** [comment]
Do labels that have encryption but have the permission set to “Let users assign when they apply label”  count in any way ?
What about OME ?

And if not, why ?

Thanks,

Brian
