### ISSUE TITLE
Unclear statements

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#212]
I don't understand what these statements mean, some words seem to be missing. can these be reworded?
•	Central offices for all general Internet traffic
•	Branch offices for Optimize category endpoint traffic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6534af4-7691-76a8-cc68-04b7cf04c3e3
* Version Independent ID: 882f7efd-b9a7-f344-fcf4-2f859cd7ff44
* Content: [Deployment of Microsoft 365 Enterprise with existing infrastructure](https://docs.microsoft.com/en-us/microsoft-365/enterprise/deploy-with-existing-infrastructure)
* Content Source: [microsoft-365/enterprise/deploy-with-existing-infrastructure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/deploy-with-existing-infrastructure.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@DeanGross Hi Dean! Sorry about that. Not sure what happened there. New text is in place. Thanks for letting me know.
