### ISSUE TITLE
Custodian licensing

### ISSUE THREAD

**Issue by bluestarcs** [MicrosoftDocs/microsoft-365-docs#2121]
Do all custodians need to have an E5 license in order to send and track legal hold notices? Is there a way to send hold notices to external email addresses and track their acknowledgments?

**Comment by mypil** [comment]
@bluestarcs - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bluestarcs** [comment]
here you go!

https://docs.microsoft.com/en-us/microsoft-365/compliance/add-custodians-to-case?view=o365-worldwide
________________________________

**Comment by markjjo** [comment]
@bluestarcs Thanks for following up. 

1. To add and manage users as custodians in an AeD case (including managing all aspects of hold notifications), the user/custodian must be assigned an E5 license.
2. No, external users can't be managed as custodians in an AeD case and they can't be sent hold notifications.
