### ISSUE TITLE
fylo5

### ISSUE THREAD

**Issue by fylo5** [MicrosoftDocs/microsoft-365-docs#2123]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: d5caf38e-e511-0763-55c8-0f54dcc6abee
* Version Independent ID: 05e41f24-433e-7535-8434-b4d51995ae0c
* Content: [What is a domain? - Microsoft 365 admin](https://docs.microsoft.com/ar-sa/microsoft-365/admin/get-help-with-domains/what-is-a-domain?redirectSourcePath=%252farticle%252fc33d1ba6-077c-4cea-be04-cfffbe3f3ed8&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/what-is-a-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/what-is-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by mypil** [comment]
@fylo5 - هل يمكنك مشاركة ما هي المشكلة المحددة التي لديك مع هذه الوثيقة؟ أم أنك فتحت هذا السؤال عن طريق الخطأ؟

إذا كان لديك أي مشاكل مع هذه الوثيقة، ونحن نقدر ذلك إذا كنت يمكن أن توفر لنا المزيد من التفاصيل حول ما يجب تحريرها و / أو تضمينها. شكرا!

[Can you please share what specific issue you have with this document? Or did you open this issue by mistake?

If you have any issues with this document, we would appreciate it if you could provide us with more details on what needs to be edited and / or included. Thank you!]

**Comment by mypil** [comment]
@fylo5 - نحن نقدر أي ملاحظات تحسن المحتوى في مستندات Microsoft ولكن لم يكن لدينا أي استجابة منك لذلك نحن ذاهبون إلى إغلاق هذه المشكلة.

إذا كان هناك مجال معين من المستندات التي يمكننا تحسين على، لا تتردد في فتح قضية جديدة من خلال النقر على قسم الملاحظات على وثيقة مايكروسوفت محددة التي وجدت في الجزء السفلي من الصفحة. شكرا.

[We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.]
