### ISSUE TITLE
The default maximum number of Microsoft 365 groups that an organization can have is 500,000, but can be increased by request.

### ISSUE THREAD

**Issue by WeiPinChai** [MicrosoftDocs/microsoft-365-docs#2124]
"The default maximum number of Microsoft 365 groups that an organization can have is 500,000, but can be increased by request." 

the documentation did not specify how/where to submit request. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
@WeiPinChai to go beyond that limit you must contact Microsoft Support.

Thanks you for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.
