### ISSUE TITLE
Phishing campaigns will collect and process events for 30 days. Results may not be available for up to 30 days.

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#2127]
Opened a ticket with Microsoft about reports not showing accurate data. Their response was that phishing campaigns will collect and process events for 30 days.  You will need to wait 30 days for results. The full set of data won't be available until 30 days are up. Please clarify your instruction to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbdcbd5-7bd2-6b55-b72c-cbedfdea776c
* Version Independent ID: 1e6198f8-6ef1-6227-c9e8-f31944a5d1db
* Content: [Attack Simulator in ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by HarrisburgUSysAdmin** [comment]
Any update on this? We are dead in the water until we can get a resolution.

**Comment by yogkumgit** [comment]
Exactly the same as #2117 , Closing it here.Thanks
