### ISSUE TITLE
Missing Org setting in configuration location 

### ISSUE THREAD

**Issue by chaguile** [MicrosoftDocs/microsoft-365-docs#2129]
In

Step 2: Enable privileged access
In the Microsoft 365 Admin Center
Sign into the Microsoft 365 Admin Center using credentials for an admin account in your organization.

In the Admin Center, go to Settings > Settings > Security & Privacy > Privileged access.

Should be

Step 2: Enable privileged access
In the Microsoft 365 Admin Center
Sign into the Microsoft 365 Admin Center using credentials for an admin account in your organization.

In the Admin Center, go to Settings > **Org Settings** > Security & Privacy > Privileged access.

In all other instructions the Org Settings address is also missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bf337ec-3242-44b9-328b-7ca6381a2bcf
* Version Independent ID: eda3540f-7049-ad17-a259-7952e5665983
* Content: [Get started with privileged access management - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/privileged-access-management-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/privileged-access-management-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/privileged-access-management-configuration.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@chaguile - thanks for the feedback, topic updated - give it 15 minutes or so to render live. Thanks!
