### ISSUE TITLE
Phase 4 not consistent

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#213]
All of the phases, except for 4, identify Require and Optional steps. The Office ProPlus discussion should be rewritted to be consistent with the other phases

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6534af4-7691-76a8-cc68-04b7cf04c3e3
* Version Independent ID: 882f7efd-b9a7-f344-fcf4-2f859cd7ff44
* Content: [Deployment of Microsoft 365 Enterprise with existing infrastructure](https://docs.microsoft.com/en-us/microsoft-365/enterprise/deploy-with-existing-infrastructure#exit-criteria-for-office-365-proplus-phase-4)
* Content Source: [microsoft-365/enterprise/deploy-with-existing-infrastructure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/deploy-with-existing-infrastructure.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by jwhit-MSFT** [comment]
Dean--thanks for the feedback. This is a good catch--I'll look into revising this when we make the next major update to the content. For now, I'd say the assessment, plan, and deployment steps should all be considered "required" for any enterprise environment.
