### ISSUE TITLE
Key vs Value

### ISSUE THREAD

**Issue by tonydavies** [MicrosoftDocs/microsoft-365-docs#2133]
in the text 
_To enable modern authentication for any devices running Windows (for example on laptops and tablets), that have Microsoft Office 2013 installed, you need to set the following registry keys._

Do you mean value?

the example is

HKCU\SOFTWARE\Microsoft\Office\15.0\Common\Identity\EnableADAL

I thought EnableADAL is a value in the key KCU\SOFTWARE\Microsoft\Office\15.0\Common\Identity ?

Thanks

Tony

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac88f29-99a5-317d-2686-cc9534194a19
* Version Independent ID: 753c4eff-ddb3-6261-35f9-4a60b65d7147
* Content: [Enable Modern Authentication for Office 2013 on Windows devices - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/enable-modern-authentication?redirectSourcePath=%252fen-us%252farticle%252fEnable-Modern-Authentication-for-Office-2013-on-Windows-devices-7dc1c01a-090f-4971-9677-f1b192d6c910&view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@tonydavies Thank you for your feedback. You are correct. The Enable ADAL is the Regdword that needs to be created in the Identity folder and the value 1 or 0 decides whether modern auth is enabled or disabled.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tonydavies Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
