### ISSUE TITLE
missing details of the MDATP portal integration in step 5

### ISSUE THREAD

**Issue by vector-sigma** [MicrosoftDocs/microsoft-365-docs#2136]
A screenshot of the integration option for step 5. for MDATP, or at least the the name of the integration that its called in the MDATP portal would help. The documentations says Office 365 ATP but in MDATP the options are "Office 365 Threat Intelligence connection" (assuming this is indeed the correct integration option)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58031ac6-a7d2-59ac-59c1-b3e03fbc8f13
* Version Independent ID: 82c2a515-4f33-1771-a175-4ed7d9d31276
* Content: [Integrate Office 365 ATP with Microsoft Defender ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @vector-sigma. Thank you so much for your helpful feedback. I have updated the article to include the additional details, and the changes will be live later today.
