### ISSUE TITLE
Cannot connect as partner

### ISSUE THREAD

**Issue by BlueOdyssey** [MicrosoftDocs/microsoft-365-docs#2139]
When attempting to connect as a partner, we get a generic error. Do you have any further info on how this process is meant to work?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebdb9f0-76a5-eebc-4cd7-95f5407ed029
* Version Independent ID: 05abf201-e31c-08c0-a7fc-8fd46202e8b0
* Content: [Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-AU/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide#how-can-partners-access-the-data)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@BlueOdyssey Thank you for your feedback. As a partner, if you have delegated admin rights then you connect to the template app on behalf of your customer.

 If the access is present, Then I would start which checking if Microsoft usage analytics is enabled and the Template app is initiated in power BI. More information can be found in the document -https://docs.microsoft.com/en-AU/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide

Hope this helps!

Thanks
Sri
