### ISSUE TITLE
New OME for Mobile

### ISSUE THREAD

**Issue by alevere** [MicrosoftDocs/microsoft-365-docs#2144]
I would like to see new OME behave the same regardless of platform. It seems to me the feature should not just be available on Outlook for Windows/Mac and OWA, but also for outlook for mobile/smartphones.

"What email client do I need to use in order to create an OME encrypted message? What applications are supported for sending protected messages?
You can create protected messages from Outlook 2016, and Outlook 2013 for Windows and Mac, and from Outlook on the web"

**Comment by mypil** [comment]
@alevere  - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com/forums/289138-office-365-security-compliance)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
