### ISSUE TITLE
eDiscovery search - Prevent recipient expansion not working

### ISSUE THREAD

**Issue by mattgaspar** [MicrosoftDocs/microsoft-365-docs#2147]
The third note on this page that describes "recipient expansion" says to append an asterisk to prevent this.  It doesn't appear to work.  With the asterisk included as shown in the example, the results still include messages from a different account with the same Display Name.  The results returned do not contain the address that was being searched.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mattgaspar You might try adding the asterisk to the alias or LegacyExchangeDN for the user that you are trying to search. Otherwise, please open a ticket with MS Support to investigate.
