### ISSUE TITLE
endpoint.microsoft.com or devicemanagement.microsoft.com

### ISSUE THREAD

**Issue by limjianan** [MicrosoftDocs/microsoft-365-docs#2148]
do microsoft change the endpoint.microsoft.com from devicemanagement.microsoft.com?
Currently both of them looks identical. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87804d7-c76b-509d-eaa0-18b91b0563bd
* Version Independent ID: 7dc288f3-939a-590b-fe8b-31a266795fa3
* Content: [Microsoft security portals and admin centers - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/portals?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/portals.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/portals.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by msbemba** [comment]
@limjianan Thank you for your feedback. I have checked and this is correct, both the URL's will take you the Microsoft endpoint manager admin center. The URL has not been officially changed and you will see the document updated if it happens.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @limjianan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
