### ISSUE TITLE
Certificate expired for  https://sender.office.com/ 

### ISSUE THREAD

**Issue by freeat22** [MicrosoftDocs/microsoft-365-docs#2150]

**Comment by mypil** [comment]
@freeat22 - May we know which Microsoft document link you used in reference to this issue? Or are you having some technical issues which requires technical support?

If you have some issues with a particular doc, we would really appreciate it if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by mypil** [comment]
@freeat22 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
