### ISSUE TITLE
change-membership-type-for-a-group-powershell

### ISSUE THREAD

**Issue by elrod-johnson** [MicrosoftDocs/microsoft-365-docs#2152]
[change-membership-type-for-a-group-powershell](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-change-type#change-membership-type-for-a-group-powershell)
verbatim code from this page doesn't work

```
Set-AzureADMSGroup : A parameter cannot be found that matches parameter name 'MembershipRuleProcessingState'.
At Change_Membership_Type_for_a_Group.ps1:59 char:9
+         -MembershipRuleProcessingState "On" `
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureADMSGroup], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Open.MSGraphV10.PowerShell.SetMSGroup
```

```
Set-AzureADMSGroup : A parameter cannot be found that matches parameter name 'MembershipRule'.
At Change_Membership_Type_for_a_Group.ps1:59 char:9
+         -MembershipRule $dynamicMembershipRule
+         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-AzureADMSGroup], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Open.MSGraphV10.PowerShell.SetMSGroup
```

see [317](https://github.com/Azure/azure-docs-powershell-azuread/issues/317)
**317 was closed one year ago.**

is this not fixed yet?
i don't want to uninstall azuread and load azureadpreview every time i run this function.
what's the solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/create-groups/compare-groups?WT.mc_id=365AdminCSH&view=o365-worldwide#microsoft-365-groups)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by elrod-johnson** [comment]
i need some help here, please!
IMO this is the same issue as above, or very closely related:
can i create a **mail-enabled dynamic membership group** using powershell?
if so, how do i do it?

i do NOT want to create a security group. i know that works.

i have BOTH azuread and azureadpreview loaded.
latest versions for both as of today.

i did NOT have azureadpreview installed for my first post above.

when i run this:

New-AzureADMSGroup 
    -DisplayName "zz_test_dynamic_group" 
    -Description "zz test dynamic group" 
    **-MailEnabled $True** 
    -MailNickname "group" 
    **-SecurityEnabled $False** 
    **-GroupTypes "DynamicMembership"**

i get this:

New-AzureADMSGroup : Error occurred while executing NewMSGroup 
Code: Request_BadRequest
Message: The service does not currently support writes of mail-enabled groups. Please ensure that the mail-enablement property is unset and the 
security-enablement property is set.
InnerError:
  RequestId: d4bc2d81-f07f-401f-ac44-d6921877e3d1
  DateTimeStamp: Mon, 15 Jun 2020 12:50:39 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ New-AzureADMSGroup `
+ ~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [New-AzureADMSGroup], ApiException
     FullyQualifiedErrorId : Microsoft.Open.MSGraphV10.Client.ApiException,Microsoft.Open.MSGraphV10.PowerShell.NewMSGroup

**Comment by get-itips** [comment]
> [change-membership-type-for-a-group-powershell](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-change-type#change-membership-type-for-a-group-powershell)
> verbatim code from this page doesn't work
> 
> ```
> Set-AzureADMSGroup : A parameter cannot be found that matches parameter name 'MembershipRuleProcessingState'.
> At Change_Membership_Type_for_a_Group.ps1:59 char:9
> +         -MembershipRuleProcessingState "On" `
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Set-AzureADMSGroup], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Open.MSGraphV10.PowerShell.SetMSGroup
> ```
> 
> ```
> Set-AzureADMSGroup : A parameter cannot be found that matches parameter name 'MembershipRule'.
> At Change_Membership_Type_for_a_Group.ps1:59 char:9
> +         -MembershipRule $dynamicMembershipRule
> +         ~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Set-AzureADMSGroup], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Open.MSGraphV10.PowerShell.SetMSGroup
> ```
> 
> see [317](https://github.com/Azure/azure-docs-powershell-azuread/issues/317)
> **317 was closed one year ago.**
> 
> is this not fixed yet?
> i don't want to uninstall azuread and load azureadpreview every time i run this function.
> what's the solution?
> 

Hello @elrod-johnson How are you?

I checked the script to see if we had to correct the article and I was able to run it successfully. I recommend checking if you have the latest version of the AzureADPreview module, which you can run side-by-side with the AzureAD module.

Hope this info helps you

**Comment by mypil** [comment]
@elrod-johnson - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @get-itips  so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
