### ISSUE TITLE
where is the referenced security center & compliance accessed

### ISSUE THREAD

**Issue by myusrn** [MicrosoftDocs/microsoft-365-docs#2154]
This walkthrough instructs user to access the "security & compliance center in your tenant" which i don't see in my m365 admin.microsoft.com portal or azure portal.azure.com environments.  

It presumably is part of m365 suite but no details are given as to what subscription or subscription addon needs to be purchased in order to light it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66854a7-7556-9b2a-0a33-886e3d881047
* Version Independent ID: 7ce3d8d5-cece-0b6f-68d5-143e12a3fff8
* Content: [Detect and Remediate Illicit Consent Grants - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@myusrn, I added the link to the step.

Thanks for the feedback.

Closing

**Comment by myusrn** [comment]
Hi Folks thanks for adding that clarification.  When i visit that link, https://protection.office.com/, in my corporate m365 environment i only see Home | Records Mgmt | Threat Mgmt | Service Assurance.  I don't see a way to follow the next step that says "2. Navigate to Search and select Audit log search.".  Perhaps this is because i'm an end user in my tenant and not user with whatever m365 subscription role is necessary to see that or a specific m365 subscription license is required for it to be surfaced. 

One thing that would be a helpful piece of content is cheat sheet outlining all the current azure and m365 hosted security and compliance related services and the url one has to know about to get to them along with any special subscription licenses are needed for them to be exposed.

Here is a running list of the urls i've been collecting based on msft security videos and blog posts where thy refer to some azure and/or m365 security functionality and just assume people are keeping their own table of what role permissions and url to use to interact with what service.

1.  m365 -> azure endpoint manager / intune [ mdm+mam ] portal [ https://devicemanagement.microsoft.com/ ]
2. m365 security portal / msft defender atp [ https://securitycenter.microsoft.com/ ] is an edr [ endpoint detection and response ] / xdr solution
3. m365 security and compliance https://protection.office.com/
4. m365 security services catalog [ https://portal.office.com/adminportal/home?switchtomodern=true#/catalog ]
5. ???
