### ISSUE TITLE
Wrong License information

### ISSUE THREAD

**Issue by data-model** [MicrosoftDocs/microsoft-365-docs#2158]
When I export the list of users, I get wrong license information for some users. They are showing as NOT having an O365 license, when in fact they are licensed. The 'Activations' report seems to be driving the LicensedForXXXX columns in Active Users. The Activations Product Licenses column is only showing one product, MICROSOFT 365 APPS FOR ENTERPRISE for most users, but there are some showing PROJECT ONLINE DESKTOP CLIENT only, even though they have 365. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b694eb7a-4481-05a2-909d-76d2f79a3986
* Version Independent ID: 596780c7-bb02-bb01-3acd-56639d04e2dc
* Content: [Microsoft 365 Reports in the admin center - Active Users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/active-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/active-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/active-users.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by pebaum** [comment]
Thanks, @data-model . 

I think support should get involved here and take a look.

[Contact Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products)
