### ISSUE TITLE
The location here is incorrect 

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/microsoft-365-docs#2160]
it says:
Sharing
Navigation: Microsoft 365 admin center > Settings > Settings > Security & privacy tab > Sharing

it should say:
Sharing
Navigation: Microsoft 365 admin center > Settings > Org Settings> Security & privacy tab > Sharing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030743fd-0c22-025b-f190-f637a2772506
* Version Independent ID: fbded472-e3ea-4297-c527-810e117ea7ea
* Content: [Microsoft 365 guest sharing settings reference](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-guest-settings?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-guest-settings.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Strick1969 Thank you for your feedback. We have made the change on the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2473

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @Strick1969 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
