### ISSUE TITLE
Article not up to date

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#2161]
This is regarding the statement: "You need to be assigned permissions before you can perform these procedures. To add, modify, and delete anti-spam policies, you need to be a member of the Organization Management or Security Administrator role groups."

This is not complete since you can do the same actions with the Rbac Hygiene Management role group as per Product group investigation:
https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/1524463

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dc3925-c049-fd93-ac0a-d9c03e8bbdb4
* Version Independent ID: 6cb1a261-061b-366e-c7fb-9b5b0ad552bb
* Content: [Configure spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, confirmed. The Hygiene Management role group wasn't even documented in the Exchange Online permissions topic. That role group has the Transport Hygiene management role, which basically gives you access to any/app anti-spam/anti-virus protection features. I updated this topic, and a bunch of other related topics.

Thanks for the feedback.

Closing
