### ISSUE TITLE
Possibly Incorrect Information referencing Phone System avaiability on Microsoft 365 Business Premium in FAQ Page

### ISSUE THREAD

**Issue by NRClay** [MicrosoftDocs/microsoft-365-docs#2163]
Hello team, 

Can we verify that the following statement is updated to reflect the availability of Microsoft 365 Business Voice service?

Page: 
microsoft-365-docs/microsoft-365/business/support/microsoft-365-business-faqs.md
Statement:
----------------------------------------------
Can I add Phone System and Calling Plans to Microsoft 365 Business Premium?

No, Phone System and Calling Plan are reserved for customers who have more advanced needs. Customers who require these capabilities should look at Microsoft 365 Enterprise offerings.
----------------------------------------------

Reference to feature set for Small Business Phone system support available to M365 Business Premium:
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-voice-service-description
https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing?tabs=small-business

Thank you!
Clay

**Comment by msbemba** [comment]
@NRClay Thank you for your feedback. You are correct, Business voice subscription can be added to M365 business premium. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2474

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @NRClay Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
