### ISSUE TITLE
Put a note whether switching between group types is allowed

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/microsoft-365-docs#2164]
Put a note whether switching between group types is allowed or not.  I presume no, but it would be preferable to have it written down here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@trajano Thank you for your feedback. It is possible to upgrade DL to M365 groups and we have added a section to this document explaining this. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2475

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @trajano Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
