### ISSUE TITLE
Is this article outdated?

### ISSUE THREAD

**Issue by anyITsolution** [MicrosoftDocs/microsoft-365-docs#2165]
Hi,

can you get this article up to date? so the product is not even called AIP any more so I think tis time this article gets updated? isn't AIP now called MIP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21613e57-8909-5adc-26ea-14e0a4771d3b
* Version Independent ID: dcd08c8d-4786-abbd-bd9d-47ad6d2117e6
* Content: [Email encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/email-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/email-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/email-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@anyITsolution Thank you for your feedback. The article has been Rebranded/Debranded due to the recent changes and it is set correctly now. In case you need any explicit changes, continue to provide us feedback on this page. 

@yogkumgit  This can be closed as there is no changes needed in the document. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @anyITsolution Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
