### ISSUE TITLE
Audit log enabled?

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/microsoft-365-docs#2166]
Maybe this is a stupid question, but I could not find the answer in de docs: Do you need to enable Office 365 audit in order to audit Customer Lockbox requests ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide#auditing-customer-lockbox-requests)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by markjjo** [comment]
@BakkerJan Yes, you need to enable auditing. For steps, see https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide
