### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/microsoft-365-docs#2169]
In the "Set up multi-factor authentication for guests" section:
I was not able to find Conditional Access Policies in Azure Active Directory.
Is an admin supposed to purchase Microsoft Azure separately for this to work in SharePoint?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a secure guest sharing environment](https://docs.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@hwkwicre Thank you for your feedback. Using this conditional access required Azure AD Premium P1 license. I have added a note in the document about the same via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2462

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @hwkwicre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
