### ISSUE TITLE
One directional barriers

### ISSUE THREAD

**Issue by thomasbinder** [MicrosoftDocs/microsoft-365-docs#2173]
On https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers?view=o365-worldwide it is stated: "Information barriers only supports two way restrictions. One way restrictions, such as marketing can communicate with day traders, but day traders cannot communicate with marketing is not supported."

However the example of this page shows a one way restriction: Manufacturing should not be able to communicate to Sales and to Research. If the statement above is true, that should also require a two way restriction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @thomasbinder Sales and Research cannot communicate with Manufacturing
