### ISSUE TITLE
Link to Security Baselines for Windows 10 is out of date

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#2174]
[Enter feedback here]
In the Default Policies table the Security Baseline section contains a link "For more information, see Security baselines for Windows 10." The link goes to a page for the 1709 baselines & on a page that is no longer maintained. 
Security Baselines info has moved to this link - https://techcommunity.microsoft.com/t5/microsoft-security-baselines/bg-p/Microsoft-Security-Baselines
or this https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-baselines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9463e12a-fa6e-18b1-6800-8aff384e1a9b
* Version Independent ID: c2d876d9-bc43-52cf-63f0-d4ced60f3c40
* Content: [Device configuration - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/device-policies?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/service-description/device-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/device-policies.md)
* Service: **m365-md**
* GitHub Login: @jaimeo

**Comment by jaimeo** [comment]
Fixed.

**Comment by mypil** [comment]
@ceaton001 - Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/99f63ae. 


Thank you for your contribution to make the docs better! Much appreciated!
