### ISSUE TITLE
Broken URL on this page

### ISSUE THREAD

**Issue by nogeekleftbehind** [MicrosoftDocs/microsoft-365-docs#2176]
This URL is broken (404):

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf71804-c91b-2464-3313-57b973ee5583
* Version Independent ID: b7803227-625d-9354-ef0e-1fb94407e835
* Content: [Recommended secure document policies - Microsoft 365 Enterprise - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/sharepoint-file-access-policies?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/sharepoint-file-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/sharepoint-file-access-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@nogeekleftbehind Thank you for your feedback. The referencing document was an old one and does not exist anymore. So that has been removed now via PR##2449

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @nogeekleftbehind Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
