### ISSUE TITLE
S/MIME Certificates setup according to the documentation are not trusted by external recipients

### ISSUE THREAD

**Issue by Rainmaker52** [MicrosoftDocs/microsoft-365-docs#2177]
I've just read the page below, after receiving an email from someone setting up message signing, very likely according to this method.

As the page only mentions the fact that an internal CA needs to be created, an external user gets an email signed by some private CA. Which means that Outlook (correctly) warns me (as an external recipient) that the certificate's root is not trusted.

The page should mention that, to actually be a useful certificate for external recipients, the starting point should be a certificate obtained by a 3rd party provider. Furthermore, it would probably be wise to have the person setting this up use an intermediate certificate, instead of singing everything against the root directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132dea81-d2ff-4438-dcf1-e3be2972d00e
* Version Independent ID: c23ee300-4cac-05cf-c9bd-e60ca14933fc
* Content: [S/MIME for encryption in Exchange Online - Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/s-mime-for-message-signing-and-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/s-mime-for-message-signing-and-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/s-mime-for-message-signing-and-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Rainmaker52, topic updated as you described.

Thanks for the feedback.

Closing
