### ISSUE TITLE
Seems this is article is not valid, kindly remove it if it is not valid, this is confusing people like me.

### ISSUE THREAD

**Issue by ecegopi** [MicrosoftDocs/microsoft-365-docs#2179]
[Enter feedback here]
Seems this article is no more valid, kindly remove it if it is not valid, this is confusing people like me.

https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@ecegopi Can you be more specific about what's not valid? Also, please tell us what subscription you have. Thanks.

**Comment by ecegopi** [comment]
We have E3 and E5 licenses, when I follow the below steps, I dont see "Office 365 Extra File Storage" service/ add on there. I also searched, but could not find the option. Basically, Im trying to find how much costs to get 1TB additional Sharepoint storage for one year in USD?

Add storage to your subscription
If you haven't yet purchased extra storage for your subscription, you can do that.
In the admin center, go to the Billing > Purchase services page.
At the bottom of the Purchase services page, select Add-ons.
Select Office 365 Extra File Storage.
On the Office 365 Extra File Storage page, if shown, choose the base subscription, then enter the number of gigabytes of storage you want to add.

**Comment by cmcatee-MSFT** [comment]
@ecegopi The add-ons aren't listed in alphabetical order. Did you scroll all the way to the bottom of the add-ons list?

**Comment by ecegopi** [comment]
I checked all the services listed on Add-On, I could not find Office 365 Extra File Storage.

**Comment by cmcatee-MSFT** [comment]
@ecegopi Did you buy through a CSP or volume licensing? Traditional add-ons (of which Office 365 Extra File Storage is one example) aren't available if you bought through a CSP or VL.

**Comment by mypil** [comment]
@ecegopi - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author @cmcatee-MSFT so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
