### ISSUE TITLE
Inaccurate information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2187]
[Enter feedback here]

There have been many changes in the Compliance Center since February 2020, but the are not listed on this page. Please update the content. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e5d5245-ece6-6430-9221-efa0d80b9f6e
* Version Independent ID: 2ad2ab98-14c8-4f5c-70de-6c809f9d8933
* Content: [What's new in the compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @brendonb
* Microsoft Alias: **brendonb**

**Comment by robmazz** [comment]
@DeanGross  - thanks for the feedback. There has been some recent process reorganization and this topic will be updated soon. Please check back in a few weeks.
