### ISSUE TITLE
Broken link to implmentation guidance

### ISSUE THREAD

**Issue by dijitald** [MicrosoftDocs/microsoft-365-docs#2189]
this link is dead

Azure HIPAA implementation guidance
https://aka.ms/azure-hipaa-guide

**Comment by mypil** [comment]
@dijitald - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by dijitald** [comment]
on this page at the bottom
https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-hipaa-hitech?ranMID=24542&ranEAID=msYS1Nvjv4c&ranSiteID=msYS1Nvjv4c-xtQ9G3jXV.5ci8D5E1w2bw&epi=msYS1Nvjv4c-xtQ9G3jXV.5ci8D5E1w2bw&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=(ir__ptitw0dhr9kfthyjkk0sohznxm2xn92rjt2qzxk600)(7593)(1243925)(msYS1Nvjv4c-xtQ9G3jXV.5ci8D5E1w2bw)()&irclickid=_ptitw0dhr9kfthyjkk0sohznxm2xn92rjt2qzxk600&view=o365-worldwide#microsoft-and-hipaa-and-the-hitech-act

there is a link to the implementation guidance, which is broken.

**Comment by robmazz** [comment]
@dijitald - thanks for the feedback, link has been corrected and published - give it 15 minutes or so to render live. Thanks!
