### ISSUE TITLE
Replace TBD with the correct App ID/SPN for SPO/OneDrive

### ISSUE THREAD

**Issue by andypituch** [MicrosoftDocs/microsoft-365-docs#2190]
Under the section "For example, for SharePoint Online and OneDrive for Business:" it has the APP ID as "TBD" instead of the correct value when setting the key vault access policy. The correct app ID is shown earlier on the page, but is not in the example.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@andypituch Thank you for your feedback. We have made changes in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2476

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @andypituch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
