### ISSUE TITLE
Some templates not listed

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2191]
[Enter feedback here]
My tenant has more templates than those listed on this page, i.e, I see EU GDPR (Intune) EU GDPR (O365), Please update this page to include all of the available templates with some text that describes the differences when there are multiple versions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4325da2c-e262-0430-854d-cf3b869575b6
* Version Independent ID: e50c60f6-6b10-8f8a-5f45-5cf3befb6a61
* Content: [Microsoft Compliance Score - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score?view=o365-worldwide#assessments)
* Content Source: [microsoft-365/compliance/compliance-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-score.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Hello - the templates list shows the data protection and compliance standards for which there are pre-built templates for assessments. Thanks for your feedback, we'll keep it in mind as we publish updates to the templates list view and increase the number of templates offered. Note also that if you're seeing additional templates in your tenant beyond just an Intune or Office 365 variation, that would occur when your organization has uploaded its own modified or custom template.

**Comment by DeanGross** [comment]
What is the difference between the Intune and O365 version of a template?
