### ISSUE TITLE
Instructions do not match UI

### ISSUE THREAD

**Issue by sagy** [MicrosoftDocs/microsoft-365-docs#2193]
On section 10: Protect against phishing attacks with ATP Safe **Links**, the steps described do not match the UI.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea79921a-7f83-58f1-c0a4-6eb0efce0d26
* Version Independent ID: b60110ef-71ad-9962-74de-734062708ff8
* Content: [Top 10 ways to secure Microsoft 365 for business plans - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#malware)
* Content Source: [microsoft-365/admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by get-itips** [comment]
Hello @sagy thanks for your report, a fix is on the way.
