### ISSUE TITLE
Old Poster

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2196]
[Enter feedback here]

The link to the Information Protection poster points to a file that is 3 years old. Can this be updated to include some of the new functionality?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2650327-5996-2155-2b0f-b646be7752c7
* Version Independent ID: 859bf570-6c39-50ed-009a-e79262954247
* Content: [Plan for security & compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/plan-for-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/plan-for-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/plan-for-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
HI @DeanGross - There are no plans to update this poster. I've redirected the link to point to more current content
