### ISSUE TITLE
Export a Content Search report

### ISSUE THREAD

**Issue by Gassela** [MicrosoftDocs/microsoft-365-docs#2197]
Hi, I think there is an error in https://docs.microsoft.com/en-us/microsoft-365/compliance/export-a-content-search-report?view=o365-worldwide page.

I report the bad sentence:

This role is assigned to the built-in eDiscovery Manager and Organization Management role groups. It isn't assigned by default to the Organization Management role group.

How can a role to be assigned to built-in role group and not assigned to the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7c6cc6-acab-cf49-5bd2-00f06e7c3bf4
* Version Independent ID: 37970b6e-c07c-f6cc-d280-dbfd086b3c33
* Content: [Export a Content Search report - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-a-content-search-report?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/export-a-content-search-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-a-content-search-report.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Gassela Thanks for the heads up. The Compliance Search role is assigned by default to both the eDiscovery Manager and Organization Management role groups. I will fix the document.
