### ISSUE TITLE
ZAP instructions need clarification

### ISSUE THREAD

**Issue by MrsKay007** [MicrosoftDocs/microsoft-365-docs#2199]
Step by step user instructions should be provided to instruct how to identify a delivered email as malicious/phishing/etc. 

Does the Outlook Add-In Report Phishing tool deploy the ZAP removal of delivered email across the organization when they identify an email as malicious?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge (ZAP) - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MrsKay007, I'm not sure I understand the request. You don't need to identify a message as malicious in order for ZAP to work. How to recognize phishing/malicious messages is important, but I'm not sure it belongs in this topic.

To answer your second question, you could say that the Report Message add-in (or any method of reporting malicious messages/files) can influence ZAP. For example, messages that contain a malicious payload are delivered to some recipients in your organization. One of the recipients uses the Report Message add-in to report the message to Microsoft. Through their normal investigation Microsoft determines that the message was malicious, and they update the datacenter spam/phishing/malware filters to recognize the message/payload. All of this could take several hours to several days. If users still have copies of the message sitting in their mailbox, then ZAP will take action on them (move to Junk Email folder or Quarantine, based on the ZAP configuration and whether its spam vs. phishing vs. malware), not just in your organization, but in all other organizations in the service.

Does this help?

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @MrsKay007 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
