### ISSUE TITLE
Include note about mailbox permissions with external users (even M365 users)

### ISSUE THREAD

**Issue by JuanZQ** [MicrosoftDocs/microsoft-365-docs#2200]
Please include a note in this section, intended to make clear about mailbox permissions with out of tenant users, even those users from others 365 tenants. Some people need to know this is not possible. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b9d613a-f990-4045-f0d3-273ecc827db7
* Version Independent ID: ef031919-5994-8d21-1f62-ee0db6f235b0
* Content: [Give mailbox permissions to another user - Admin Help - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@JuanZQ Thank you for your feedback. We have added a note to the document. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2477

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @JuanZQ Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
