### ISSUE TITLE
Role - permissions to be able to "Initiate Sign-out"?

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/microsoft-365-docs#2203]
Hi - which permission is required to be able to "initiate sign-out" from O365 Admin console?
https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide#sign-out-now
**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide#block-a-former-employees-access-to-office-365-data)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ii-batman  Thank you for your feedback. You need to be a Global Administrator to initiate sign-out. We have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2482

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @ii-batman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
