### ISSUE TITLE
Ok so how to delete found content.

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/microsoft-365-docs#2204]
As teams is missing the ability to delete things a number of forum posts point towards this page.
So I figured out IM as per the skype section pertains to teams also so maybe you should update that section as I thought teams was the new favorite.

However now having confirmed the search will find the team IM message I need to delete there is no option to delete them from within the page only an option to export them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d452ad-cd94-d28b-0ea9-8d5a4ca00716
* Version Independent ID: 1e810e3c-086c-7529-c6d3-3511cf73187b
* Content: [Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@webstaff You can run the New-ComplianceSearchAction -Purge PowerShell command. Please see https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide

Also, more info about searching for content in Teams in the content search topic: https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide#searching-microsoft-teams-and-microsoft-365-groups

**Comment by webstaff** [comment]
Yeah I had already stumbled over that article but unfortunately I need to clean the whole mailbox or team chats.

So:
"A maximum of 10 items per mailbox can be removed at one time. Because the capability to search for and remove messages is intended to be an incident-response tool, this limit helps ensure that messages are quickly removed from mailboxes. This feature isn't intended to clean up user mailboxes."

Means that's a no from me..

And I can't wait for the 10,000 votes user voice item covering exactly this to be actioned, so I've just raised a ticket with MS support directly to ask them what are we supposed to do.

regards
Dave
________________________________
