### ISSUE TITLE
WHERE IS DNS SETTINGS ?????????????? WHERE ????????

### ISSUE THREAD

**Issue by ragnarokas** [MicrosoftDocs/microsoft-365-docs#2210]
On the Domains page, in the list of domains, select the domain you're using for your website, and then select DNS settings in the management panel

WHERE IS DNS SETTINGS ?????????????? WHERE ????????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f087dd43-183d-08bb-37d7-d893bede6efb
* Version Independent ID: be429837-0300-3de8-6c7d-2da2fabc2c17
* Content: [Update DNS records to keep your website with your current hosting provider - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by JakeMoe** [comment]
Looks like they changed it from DNS Settings to DNS records, perhaps? When I go there, the rest of the instructions seem fine.

The only other thing I can think of for your problem is you clicked the tick mark next to the domain rather than actually clicking the domain to get into the domain's DNS settings?

**Comment by sfilinto** [comment]
Step 2 in the link is wrong. You need to click on the domain name (not just select), then click on DNS Records tab. The next step 3 is correct.

additionally this page is hard to find. it should be linked to the page where you change your DNS Name server (https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide) as the next logical step.

**Comment by msbemba** [comment]
@ragnarokas Thank you for your feedback. We have modified the document with the correct settings and the same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2573



Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @ragnarokas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
