### ISSUE TITLE
Screenshots need updating

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/microsoft-365-docs#2211]
The screenshots in this article don't appear to match up to what my Content search page looks like.  I get a "Search query" section where I can add different conditions, each of which pops up in it's own box, where I can select what type of condition it is (equals, not equals, contains, etc), and then value(s) to match.  The screenshots seem to show a "keywords" box on it's own, then rows of conditions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide#examples-of-using-conditions-in-search-queries)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@JakeMoe Thanks for the heads up. Will look into updating these screenshots. The functionality is the same, with keywords box (same as box under "what do you want us to look for") and the ability to add conditions.
