### ISSUE TITLE
Preview vs GA

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#2217]
Hello,

Received info from Office 365 message center, that it is no longer Preview... This document is ready for GA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire  No, it is currently still preview and this page will be updated when it goes GA.  Where exactly in the message does it say that it's no longer preview?  The wording I see for when this will happen is "We will begin rolling this out in late June and expect the rollout to be complete in early July".  So, soon - but not today!

**Comment by lightupdifire** [comment]
Hello Carol,
Thank you for input, I see my colleagues pass the message to me incorrectly. Sorry for bothering you.
