### ISSUE TITLE
After upgrading to Windows 10 Pro, option to choose between personal use and organizational use not presented

### ISSUE THREAD

**Issue by CalvinQuark** [MicrosoftDocs/microsoft-365-docs#2218]
I just purchased a new Surface Book 3 from the online Microsoft store. The machine came configured for personal use with a Windows 10 Home version. I upgraded to Windows 10 Pro. However, the option to choose between setting up the machine for personal use versus organizational use was never presented. And it's not clear how to subsequently reconfigure the device for organizational use. Multiple tech support calls with various Microsoft personnel have shed no light on the situation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8e657e-2aa7-230d-0d9d-675c0200ac18
* Version Independent ID: 2028f003-2624-2bd3-34ea-6022d495e2c6
* Content: [Set up Windows devices for Microsoft 365 Business Premium users - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/set-up-windows-devices?view=o365-worldwide)
* Content Source: [microsoft-365/business/set-up-windows-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/set-up-windows-devices.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@CalvinQuark Thank you for your feedback. If the option did not get presented then there could be an issue with the configuration. The document is up to date and no modifications needed as of now. You can contact M365 support via the need help option in Admin portal and get immediate support.

 I'd say there are other options to connect to your work or school by following the below 

On Your info page, click Access work or school > Connect.
Choose Connect under Access work or school
![image](https://user-images.githubusercontent.com/45987684/89751868-8a446b00-daef-11ea-979e-6781df21f30d.png)
Hope this helps! 


@yogkumgit  The document is up to date and there is no modification needed as of now, Please proceed with closure.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @CalvinQuark Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
