### ISSUE TITLE
Audting creation of message

### ISSUE THREAD

**Issue by bartvermeersch** [MicrosoftDocs/microsoft-365-docs#2221]
The document states:

"An item was created in the Calendar, Contacts, Notes, or Tasks folder in the mailbox (for example, a new meeting request is created). **Creating, sending, or receiving a message isn't audited**. Also, creating a mailbox folder is not audited."

Based on our findings, the creation of messages does get audited and can be retrieved using the audit log search and MCAS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bartvermeersch, we need some more clarification:

- What report type and operation name values are returned in the audit record? Feel free to attach a sanitized snippet from the unified audit log.

- When you say "creation of a message does get audited" do you mean created and saved to Drafts, but not sent, or composed and sent?

- What subscription level do you have (E3, E5, etc.).

Thanks!

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for digging deep into it.  @bartvermeersch We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
