### ISSUE TITLE
Access from unmanaged devices combination with users OneDrive

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#2222]
Hello,

Can you please help to understand the possible combination of settings using policies, or PowerShell for:

1. Without Sensitivity labeling for SharePoint sites, we used SharePoint Access Control policy: if device not compliant (unmanaged) - then limit access apply, no download option;

2. Now when Sensitivity labeling for SPO will become available, we want to use it for some "truly Public data" sites and allow download for Guests/B2B users from those sites, but in order to use Sensitivity labeling per site, the general SharePoint Access Control policy must be turned off, this turn off protection for users OneDrive, then data of users OneDrive will be possible to download from the unmanaged device;

Question:

Is it possible to combine settings-policies-script to set up in a way that:
1. Some sites can be marked with Sensitivity label like **Public** and option for access from unmanaged devices: **full access**
2. Users OneDrive still protected and access from unmanaged devices: **limited access/view only**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by lightupdifire** [comment]
Hello,

I have found one possible solution, but this one requires to have Scheduled PowerShell script to run:

a) SharePoint Admin->Access Control->Unmanaged devices: Allow Full access
b) After 1st option **disabled**, this will disable Conditional Access policies for SharePoint access, those Conditional Access policies must be turned back ON
c) Run PowerShell:
Connect-SPOService -Url https://{tenantname}-admin.sharepoint.com;
Get-SPOSite -Identity "https://{tenantname}-my.sharepoint.com/personal/{user_profile_com}" | Set-SPOSite -ConditionalAccessPolicy AllowLimitedAccess;

Now I have access to 2x SharePoint sites and 2x user OneDrive sites, where:
d) Site1 - marked with Sensitivity: full access
e) Site2 - marked with Sensitivity: limited access
f) OneDrive1 - applied by PowerShell ConditionalAccessPolicy: AllowLimitedAccess
g) OneDrive2 - applied by PowerShell ConditionalAccessPolicy: AllowFullAccess

Using the account, that is included in the b) step in Conditional Access policy, try access to:
d) - receive full access, downloading files works;
e) - receive limited access, no download possible, limitation message shown;
f) - receive limited access, no download possible, limitation message shown;
g) - receive full access, downloading files works;

But, now if new user account created, then user account must be checked for ConditionalAccessPolicy settings by PowerShell and changed to "AllowLimitedAccess";

It would be great to have solution without a need to run PowerShell, but possibly not possible for a moment... but maybe I'm wrong? If not, should I go to UserVoice?

**Comment by cabailey** [comment]
@lightupdifire I checked with engineering - no, the product doesn't currently support what you want to do and the PowerShell option is a viable workaround but please do post this request to UserVoice.  There's a new category specifically created for sensitivity labels and containers: https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip?category_id=385024
