### ISSUE TITLE
Alert policies with Business subscriptions

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/microsoft-365-docs#2223]
From my tests, i saw the alert policies are available also for Business subscribers, even if not the "advanced" section, and around half of the default policies are there.
However the current article only includes Enterprise subscriptions. I cannot find the Alert Policies included in the security and compliance service descriptions to understand if they are really included or not. Could you please clarify this?

**Comment by mypil** [comment]
@teomonda - Closing this issue as it is a duplicate to issue #2224.
