### ISSUE TITLE
Alert policies for Small Business subscribers?

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/microsoft-365-docs#2224]
From my tests, i saw the alert policies are available also for Business subscribers, even if not the "advanced" section, and around half of the default policies are there.
However the current article only includes Enterprise subscriptions. I cannot find the Alert Policies included in the security and compliance service descriptions to understand if they are really included or not. Could you please clarify this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance centers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@teomonda Thanks for question. Which Business subscription do you have? Also, can you send a list of the default alert policies that are available? Are they the same ones that are only available in E1? Since Business subscriptions also support basic auditing, I assume they also support the basic alert policies. I would also assume the the *ProtectionAlert cmdlets are also available in SCC PowerShell. Is that correct? I'll follow up with engineering as well.

**Comment by teomonda** [comment]
hello @markjjo , thanks a lot for the quick reply!
I have M365 Business Standard in my test tenant. Definitively they are less default alerts compared to the E5 i have (11 versus 22). 
![Business_standard](https://user-images.githubusercontent.com/43137999/85515582-f6cdde00-b605-11ea-9a41-2f01a208411f.jpg)

I have not actually double checked Powershell as well. My confusion or actually the Microsoft Partner's with which i am working, relies in the fact that we solely depict Enterprise, Firstline and Government subscriptions in the current article as including this. Surely it may not be the only feature that works even though not properly licensed :) so my concern was if Business subscribers have to actually disable these to make sure they are compliant.

**Comment by markjjo** [comment]
@teomonda Thanks again for following up. I've sent this issue to both engineering and product marketing to try to resolve. I will update the service descriptions according if alert policies should be include for Business subscriptions.

I'm not sure how you would disable alert policies (other than to use RBAC permissions to prevent a user from accessing the page in the SCC. However, if it's available in a Business subscription, I'm not sure how you would be out of compliance? Even if you are able to create a custom alert policy, I don't think you would be out of compliance doing so. This is different that say, creating an org-wide retention policy that is assigned to some users who don't have the appropriate license.

If you still have concern, I would suggest you open a ticket with MS Support. I will respond back to this github issue if I get more info or if I update the SCC service description.
