### ISSUE TITLE
File types for auto-labeling policies for SharePoint, OneDrive, and Exchange

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/microsoft-365-docs#2225]
[Enter feedback here]
https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide#how-to-configure-auto-labeling-policies-for-sharepoint-onedrive-and-exchange

It is not clear what file types are supported for auto-labeling policies for SharePoint, OneDrive, and Exchange

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@DavidTaig  For SharePoint and OneDrive, the information is included in "Maximum of 25,000 automatically labeled files (Word, PowerPoint, or Excel) in your tenant per day." but to make the file types supported more obvious, I'll split this out into two separate bullets.  

For Exchange, included in "Unlike manual labeling or auto-labeling with Office apps, Office attachments and PDF attachments are also scanned for the conditions you specify in your auto-labeling policy."  For additional clarity, I'll "(Word, Excel, PowerPoint") for the Office attachments reference.

**Comment by cabailey** [comment]
Live now, closing. Thanks for your feedback!
