### ISSUE TITLE
Missing Information for DeviceTvmSecureConfiguratonAssessment Table

### ISSUE THREAD

**Issue by waltgithub** [MicrosoftDocs/microsoft-365-docs#2226]
Hi, it looks like this page is missing a description and information for the "Context" column, which contains important information related to the Antivirus Signature. When will it be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d8aa7f-0e71-9d55-7b6a-7097675f73d6
* Version Independent ID: dea5d670-3e02-4aed-5abb-c1934ea06695
* Content: [DeviceTvmSecureConfigurationAssessment table in the advanced hunting schema - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/advanced-hunting-DeviceTvmSecureConfigurationAssessment-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/advanced-hunting-devicetvmsecureconfigurationassessment-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/advanced-hunting-devicetvmsecureconfigurationassessment-table.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by yogkumgit** [comment]
@lomayor  Please help us and answer this issue. Thanks

**Comment by yogkumgit** [comment]
@lomayor Gentle reminder, Kindly answer and help us in resolving this issue. Thanks.

**Comment by lomayor** [comment]
@yogkumgit I'll get back to you after I confirm this change with the product team.

**Comment by lomayor** [comment]
@yogkumgit I'll update this article today to add three columns. Will close when done. Thanks.

**Comment by lomayor** [comment]
Updates merged. Closing.
