### ISSUE TITLE
Can this policy be scoped to specific users?

### ISSUE THREAD

**Issue by sukhrehal** [MicrosoftDocs/microsoft-365-docs#2228]
Typically we need to test impact of any policy changes before enabling. Is there any way to scope it to specific users\groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@sukhrehal, I'm told that currently, there's no way to scope the feature to specific users or groups.

Thanks for the feedback.

Closing
