### ISSUE TITLE
Can you please confirm that this great, new feature is "all or nothing"? In other words, there is no way to turn it on for a limited set of users to pilot it first, before blasting it out to all Office client users in an organisation?

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/microsoft-365-docs#2231]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jose-camacaro, yes, currently the feature is on or off for the whole organization.
