### ISSUE TITLE
unable to locate sharepoint library

### ISSUE THREAD

**Issue by bilal-docusign** [MicrosoftDocs/microsoft-365-docs#2232]
as O365 admin, unable to locate the site for which i want to export the site usage report in O365 admin

**Comment by mypil** [comment]
@bilal-docusign - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@bilal-docusign - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
