### ISSUE TITLE
Please use 'Concepts' instead of 'Themes'

### ISSUE THREAD

**Issue by eDiscoFever** [MicrosoftDocs/microsoft-365-docs#2233]
Non-standard terms inject unnecessary confusion in the legalese-techspeak discussion that's already difficult.  The issue of confusion that arose with the 'InPlace' term similarly occurs here with the term 'Themes'.  

No one in the eDiscovery industry uses this term.  It's concept searching ... just call it 'Concepts'. Here, from the EDRM, "Alternative search tools, such as **concept searching** and visualization, should also be considered."
https://www.edrm.net/resources/frameworks-and-standards/edrm-model/review-guide/perform-data-analysisworkflow/

eDiscovery is, in fact, the first cited entry on 'Uses' for Wikipedia's'Concept Search' page:
"eDiscovery – Concept-based search technologies are increasingly being used for Electronic Document Discovery (EDD or eDiscovery) to help enterprises prepare for litigation. In eDiscovery, the ability to cluster, categorize, and search large collections of unstructured text on a conceptual basis is much more efficient than traditional linear review techniques. Concept-based searching is becoming accepted as a reliable and efficient search method that is more likely to produce relevant results than keyword or Boolean searches" https://en.wikipedia.org/wiki/Concept_search 

This is a complex intersection of law and technology where terms of art have established, specific meanings and practices.  For example, I would have to re-explain 'Themes' in an eDiscovery declaration to a Court with something like "Microsoft 365 integrates a concept searching tool called "Themes" ... [insert 1) re-phrasing of this page to fit with 'Concept Search' secondary source practices and policies cited and 2) an explanation of concept search application in X case in Judge digestible language]"  Why? There is literature out there about concept searching and its defensible use in the legal context. It's how the discussion is framed already.

Moreover, "themes" in the legal context often refers to case themes related to specific legal elements - law school and lawyer stuff unrelated concept searching.  A non-technical lawyer could make statements about "Themes in discovery", which could confuse counsel and the courts.

Consider hiring someone from the industry to work through terminology or even as a project manager. This documentation should be plug-and-play with standard industry terminology for cited use. 

It's like trying to replicate Robocopy command switches using the PowerShell copy-item cmdlet ... it's more work then just using the original.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 021baa68-82e3-82fb-c69e-fc2be78afc3b
* Version Independent ID: 174b03c2-303d-0089-e07b-d51edf4f9050
* Content: [Themes - eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/themes-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/themes-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/themes-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@eDiscoFever Thanks for your feedback. I have forwarded it to the eDiscovery program management team.
