### ISSUE TITLE
Domain setting location typo

### ISSUE THREAD

**Issue by vinsonw** [MicrosoftDocs/microsoft-365-docs#2234]
On
> "Sign in to the Microsoft 365 admin center and select Show all > Settings > Domains."

I suppose it should be "Show all > **Setup** > Domains"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc42d030-189c-a877-a431-f9c0d167414a
* Version Independent ID: 89079123-8860-ba7b-c707-5d4af1da59db
* Content: [Add DNS records to connect your domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by pebaum** [comment]
the article as written is correct
