### ISSUE TITLE
E5 not required, E1 is sufficient

### ISSUE THREAD

**Issue by sep2li** [MicrosoftDocs/microsoft-365-docs#2235]
Communications Credits, Domestic Calling Plan, International Calling Plan do not require Office 365 Enterprise E5 but only E1. And that is good - E1 should be all that is needed, otherwise phone system will only work for a fraction of people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 903e8a02-dbce-4f9c-a397-f2c549b95b57
* Version Independent ID: fa546b6a-5c3a-5019-e97c-8510f782e4b8
* Content: [Buy or edit an add-on](https://docs.microsoft.com/en-us/microsoft-365/commerce/buy-or-edit-an-add-on?view=o365-worldwide#update-a-standalone-add-on)
* Content Source: [microsoft-365/commerce/buy-or-edit-an-add-on.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/buy-or-edit-an-add-on.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@sep2li Team confirmed that they are working on the issue and soon will update the documentation. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
