### ISSUE TITLE
Link redirection does'nt work for one link

### ISSUE THREAD

**Issue by MacKender** [MicrosoftDocs/microsoft-365-docs#2236]
[Enter feedback here]
The link for "Note that we won't discuss enabling guest sharing settings in this article. See [Collaborating with people outside your organization](https://docs.microsoft.com/en-us/Office365/Enterprise/collaborate-with-people-outside-your-organization) for details about enabling guest sharing for different scenarios." doesn't work, there's no redirection so the visitor gets a 404 Not Found error. Other links int he same article that contain 'Office365' in the URL seems to redirect correctly.

Link in article:
https://docs.microsoft.com/en-us/Office365/Enterprise/collaborate-with-people-outside-your-organization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a secure guest sharing environment](https://docs.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Thanks for catching that, @MacKender. I've submitted a pull request to update the link to point [here](https://docs.microsoft.com/microsoft-365/solutions/collaborate-with-people-outside-your-organization).

**Comment by mypil** [comment]
@MacKender - Thank you for submitting feedback.

From our understanding, the issue you raised has been resolved by the author @MikePlumleyMSFT so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
