### ISSUE TITLE
M365 SKU Changes not reflected.

### ISSUE THREAD

**Issue by jawboston** [MicrosoftDocs/microsoft-365-docs#2237]
The new(ish) M365 Business Premium now includes all the E3 stuff listed in this article.
Please update to reflect changes made in the last 4 months.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb38c4a-21b3-4906-267f-79d7d9e31ac6
* Version Independent ID: 42d74946-a041-f05d-d909-c14c981000f3
* Content: [Prerequisites for Microsoft Managed Desktop - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-ready/prerequisites?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-ready/prerequisites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-ready/prerequisites.md)
* Service: **m365-md**
* GitHub Login: @jaimeo

**Comment by jaimeo** [comment]
@DHB-MSFT can you assist with this?

**Comment by msbemba** [comment]
@jawboston Thank you for your feedback. We have made changes to the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2574

Thanks
Sri

**Comment by jaimeo** [comment]
Per Microsoft Managed Desktop SME, the changes in 2574 are incorrect. Following up with them.

**Comment by msbemba** [comment]
@jaimeo let us know what you find from the SME's, I can update the licensing section accordingly.

Thanks
Sri

**Comment by jaimeo** [comment]
Article was updated in https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2596

**Comment by msbemba** [comment]
Thank you @jaimeo. @jawboston The licensing section in the article is updated.

@yogkumgit We can proceed with closing this case as the document has been updated.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @jawboston Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
