### ISSUE TITLE
WIX doesn't support MX for subdomains

### ISSUE THREAD

**Issue by jgrisham** [MicrosoftDocs/microsoft-365-docs#2238]
Recommend adding a note to the following effect:

WIX does not appear to support DNS entries for subdomains, at least as of June 2020.

If you want to use a subdomain (e.g. www.sales.contoso.com), you will need to manage your DNS somewhere other than at WIX.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3200297-3d59-9cf3-4d8e-494e8d000bb1
* Version Independent ID: 3edaf8bb-829e-26a5-321c-19fb32f93460
* Content: [Create DNS records at Wix for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-wix?view=o365-worldwide#add-an-mx-record-so-email-for-your-domain-will-come-to-office-365)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-wix.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-wix.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@jgrisham Thank you for your feedback. We have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2575. Once the author approves the same you will see the Note live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @jgrisham Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
