### ISSUE TITLE
Where's the instructions for non-outlook using users? 

### ISSUE THREAD

**Issue by tenmilez** [MicrosoftDocs/microsoft-365-docs#2242]
I have users that want to add shared mailboxes to the iPhone using the default mail app. Where's the instructions for that? Or at least say it's not possible. I know Outlook is your product, but get with the times. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db2dbb29-38c4-afe4-bc0d-3bbc195f6288
* Version Independent ID: bcfee113-ecfe-e358-974e-6f9cd76b8d35
* Content: [Create a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@tenmilez Thank you for your feedback. We can only add shared mailboxes on outlook with Ios or android. I have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2512

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @tenmilez Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
