### ISSUE TITLE
Include info/link on encryption for Stream

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/microsoft-365-docs#2243]
Can we include some info and a link to the encryption information for Microsoft Stream?

"[When you upload] a new video or creates a live event, that video is transcoded, encrypted with AES-128 encryption, and stored in Azure Media Services. This means the videos are encrypted both in transit and at rest."
https://docs.microsoft.com/en-us/stream/network-overview#video-level-encryption-and-playback-flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed881955-a2ba-6482-cb1b-8443909c4d52
* Version Independent ID: 57679a1a-7501-40fe-c1c4-5aff9a45c792
* Content: [Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@npherson Thank you for your feedback. This is a Generic topic on M365 compliance so we have not explicitly mentioned about any particular application. But  We have added to the link to related topics via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2513

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @npherson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
