### ISSUE TITLE
Office 365 Extra File Storage is not an available add-in

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/microsoft-365-docs#2244]
[Enter feedback here]
Our O365 E3 licenses are apparently eligible for extra file storage. However, in step 3, the "Office 365 Extra File Storage" add-on is not an available option in the tenant.
![2020-06-25_9-44-42](https://user-images.githubusercontent.com/57106905/85762419-8f2c9700-b6c8-11ea-99cd-ffda69d14818.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@JLambEJG  Did you buy your subscription through a CSP or VL? Traditional add-ons, of which Extra File Storage is one, aren't available if you purchases through a CSP or VL.

**Comment by JLambEJG** [comment]
> @JLambEJG Did you buy your subscription through a CSP or VL? Traditional add-ons, of which Extra File Storage is one, aren't available if you purchases through a CSP or VL.

It seems that this is critical information that should be in the "is my plan eligible" section. Text searching the document for "VL" or "CSP" returns no results. As it is written, our tenant is eligible, but these instructions are inaccurate in our situation. Please update the document so that it is clear that VL/CSP customers need to acquire the add-on through other means.

**Comment by cmcatee-MSFT** [comment]
@JLambEJG I've updated the article so that information is at the top. Thanks for the feedback!
