### ISSUE TITLE
Unclear control overlap.

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [MicrosoftDocs/microsoft-365-docs#2245]
The [documentation ](https://docs.microsoft.com/en-us/powershell/module/msonline/set-msolcompanysettings?view=azureadps-1.0#parameters) for AllowAdHocSubscriptions states that it controls "whether to allow users to sign up for email based subscriptions" That sounds very similar to the intent of AllowSelfServicePurchase and the overlap, if there is any, between the two is unclear.

Are these complimentary controls or do they control separate areas?
E.g. Do they control the same thing in a different fashion?
E.g. Does AllowSelfServicePurchase not cover trial subscriptions which don't require a purchase?

Thanks in advance for the help.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e05e10b-691c-2357-25f5-1a9e810c662d
* Version Independent ID: 0d789543-2033-d759-1fe9-69f24e458c13
* Content: [Manage self-service purchases (Admins)](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@Jared-Harrington-Gibbs They control separate areas:

**AllowAdHocSubscriptions** covers the free subscriptions that users can sign up for, and applies across all products. You can read more about that here: [Manage self-service sign-up subscriptions](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/manage-self-service-signup-subscriptions).

**AllowSelfServicePurchase** lets an admin prevent or allow whether a user can buy the products we offer for self-service purchase (Power BI, Power Apps, Power Automate). It can be set on a per-product basis.

Hope that helps!

**Comment by Jared-Harrington-Gibbs** [comment]
Awesome, I thought that might be the case.
Thanks!
