### ISSUE TITLE
There should be a better way to ensure a group has access over all OneDrive accounts

### ISSUE THREAD

**Issue by cfizz34** [MicrosoftDocs/microsoft-365-docs#2247]
[I do not want to click on a link to grant myself access, I as a global admin always want full control over the OneDrive accounts]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Get access to and back up a former user's data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@cfizz34 Thank you for your feedback. By default, Administrators do not have access to All onedrive accounts. Having said that if you as an admin need access to all onedrive accounts, you will have to make the below changes

1)Login to your SharePoint Online Admin Center 

2)Click on User Profiles from the left navigation

3)Click on My Site Settings >> Setup My Sites >> Under "My Site Secondary Admin" section, Check "Enable My Site Secondary admin" tick box and set My Site Secondary Admin as below: (Add the admin or admin security group)

![image](https://user-images.githubusercontent.com/45987684/89077107-1d1e3080-d39f-11ea-9c55-72bff6477089.png)

The reason why you don't see this step in the document is that it pertains only to access and back up a former user's data. 

Hope this helps!

@yogkumgit Please proceed with closing the case as there is no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @cfizz34 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
