### ISSUE TITLE
What is a "Windows 2019 Client"?

### ISSUE THREAD

**Issue by colliefury** [MicrosoftDocs/microsoft-365-docs#225]
Under the section "Step 3: Office and Line of Business App Delivery", see the second sentence that references "Windows 2019 Client" - did you mean Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab55fc7e-f0eb-684a-cf8f-dd89990937c5
* Version Independent ID: 6d7e6627-cc17-853c-6563-420e02f87f45
* Content: [Getting Started - Modern Desktop Deployment](https://docs.microsoft.com/en-us/microsoft-365/enterprise/getting-started)
* Content Source: [microsoft-365/enterprise/getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/getting-started.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
addressed grammar error
