### ISSUE TITLE
Add a section containing Microsoft 365 groups location

### ISSUE THREAD

**Issue by OritOrlanczyk** [MicrosoftDocs/microsoft-365-docs#2266]
[Enter feedback here]
I would add a comment that you can include group mailbox and site using Microsoft 365 groups location.
There is a section that explains Files in Teams but no comment or section that include both Exchange and SPO location like in the article: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide

"Configuration information for Microsoft 365 groups: A retention policy applied to a Microsoft 365 group includes both the group mailbox and site. A retention policy applied to a Microsoft 365 group protects the resources created by a Microsoft 365 group, which includes Microsoft Teams."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention policies for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@OritOrlanczyk  Thanks for your feedback - good point and now expanded that section we had about files so it includes when to select Office 365 Groups vs SharePoint sites "https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide#additional-retention-policies-needed-to-support-teams"
