### ISSUE TITLE
Admin role requirements

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/microsoft-365-docs#2278]
Under admin role requirements, it is mentioned it needs the following roles - global administrator, report reader, Exchange administrator, Skype for Business administrator, or SharePoint administrator.

But "report reader" role doesn't exist in Office 365. Can you please confirm how to get report reader role.  Please see the attached screenshot for all the admin roles available in Office 365 and you can see that no "report reader" role exists. Is "Global Reader" role the alternative?

![image](https://user-images.githubusercontent.com/30608419/86044169-5c0f3e00-ba0f-11ea-90a8-4842a27b031d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide#enable-the-template-app)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
Assigning to @kwekuako

**Comment by kwekuako** [comment]
@haider392 you have to expand the See all roles option on the roles page to get to the reader report role. 
![image](https://user-images.githubusercontent.com/35539435/86623277-240b7c00-bf76-11ea-9ab4-5cb043613581.png)
