### ISSUE TITLE
The most important type of alert is missing. How do you configure and get alerts for failed login attempts?

### ISSUE THREAD

**Issue by billspeers** [MicrosoftDocs/microsoft-365-docs#2279]
The most important type of alert is missing. How do you configure and get alerts for failed login attempts and lock outs.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance centers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@billspeers Thanks for feedback. Currently, this functionality isn't in alert policies. Please provide this feedback at https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=137187

Also, you might look in AAD sign-in reports: https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/concept-sign-ins Note sure if there is a notification functionality or if you just have to track failed logons in the report.
