### ISSUE TITLE
Another funky sentence - may want to review entire article

### ISSUE THREAD

**Issue by colliefury** [MicrosoftDocs/microsoft-365-docs#228]
See the first sentence under "Step 1: Device and App Readiness" - "Begin your desktop deployment project with an inventory of your devices and apps, prioritize what you to move forward, test prioritized apps and devices, then remediate what’s needed to get ready for deployment." - Notice "Prioritize what you to move forward", this same mistake has been repeated again in this same article. At this point I'll stop providing detailed feedback as the mistakes are too numerous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddfe050b-6adb-bd3c-3326-f7cc94b0ca5c
* Version Independent ID: 566540f3-e512-f931-2e8d-492ae03e07af
* Content: [Step 1 - Device and App Readiness](https://docs.microsoft.com/en-us/microsoft-365/enterprise/step-1-device-and-app-readiness)
* Content Source: [microsoft-365/enterprise/step-1-device-and-app-readiness.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/step-1-device-and-app-readiness.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
addressed grammar error
