### ISSUE TITLE
Inaccurate statement

### ISSUE THREAD

**Issue by mustaphaarakji** [MicrosoftDocs/microsoft-365-docs#2281]
Hi,
I'm following this guide to export the list of resources shared with external users. At the end of the document at step number 5, there's this statement:

"Now Excel displays the rows for sharing events AND where the target user is outside of your organization, because external users are identified by the value TargetUserOrGroupType:Guest."

This is not accurate, as when I did an export, I noticed that the "TargetUserOrGroupType" value is blank when the operation is "AnonymousLinkCreated", but it's true for other operation like "SecureLinkCreated".

This has a major effect as it will lead to inaccurate analysis. Please ask someone to have a look.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a4e415a-1085-a8a3-3bb5-93599ad78989
* Version Independent ID: 132434ea-0154-3d74-10fa-cb94ffae3579
* Content: [Use sharing auditing in the audit log - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-sharing-auditing?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-sharing-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-sharing-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mustaphaarakji Thanks for the heads up. We'll look into it. If this is an issue for you, would suggest you open a ticket with MS Support to investigate.
