### ISSUE TITLE
Comparison of Retention Labels vs. Retention Policies

### ISSUE THREAD

**Issue by richardjgreen** [MicrosoftDocs/microsoft-365-docs#2285]
The documentation doesn't make it super clear to people when they should use Retention Labels vs. Retention Policies. For manual scenarios where labelling is being published to the user to apply it is clear, however, as both Labels and Policies have the option to auto-apply based on either Sensitive Info or Words and Phrases, I think clarity is needed.

A simple page that lists the features of Labels vs. Policies would be helpful with scenarios of when to use Labels vs. Policies.

**Comment by cabailey** [comment]
@richardjgreen I agree and have documentation in progress for this that I hope to publish soon.

**Comment by cabailey** [comment]
This comparison table is live now: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#compare-capabilities-for-retention-policies-and-retention-labels 

Let me know if this and the newly added information on this page is helpful!
