### ISSUE TITLE
Examples Do Not Appear to Work as Expected

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/microsoft-365-docs#2287]
Using this script gleaned from this article:
$Group = "Office Users"
$GroupId = (Get-AzureADGroup -SearchString $Group).ObjectId
$Setting = Get-AzureADObjectSetting -TargetObjectId $GroupId -TargetType Groups
$Setting["AllowGuestToAccessGroups"] = $False
$Id = (Get-AzureADObjectSetting -TargetObjectId $GroupId -TargetType Groups).Id
Set-AzureADObjectSetting -TargetType Groups -TargetObjectId $GroupId -Id $Id -DirectorySetting $Setting
Get-AzureADObjectSetting -TargetObjectId $GroupId -TargetType Groups | fl Values

It seems to run successfully but when the last line runs (Get-AzureADObjectSetting -TargetObjectId $GroupID -TargetType Groups | fl Values**) it comes back with:

**Values : {class SettingValue {
           Name: AllowToAddGuests
           Value: True
         }
         }**

So, it appears the change does not save.

Any ideas?

Thanks!
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@matziq  Thank you for your feedback. I was able to test the below script in the document and it works as expected. Maybe the document was updated after you entered this issue. But let us know if you need any changes in the document.

$GroupName = "<GroupName>"

Connect-AzureAD

$template = Get-AzureADDirectorySettingTemplate | ? {$_.displayname -eq "group.unified.guest"}
$settingsCopy = $template.CreateDirectorySetting()
$settingsCopy["AllowToAddGuests"]=$False
$groupID= (Get-AzureADGroup -SearchString $GroupName).ObjectId
New-AzureADObjectSetting -TargetType Groups -TargetObjectId $groupID -DirectorySetting $settingsCopy


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @matziq Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
