### ISSUE TITLE
There are certain scenarios in which Dynamic Delivery is not supported. 

### ISSUE THREAD

**Issue by iaasazure** [MicrosoftDocs/microsoft-365-docs#2288]
The page states
There are certain scenarios in which Dynamic Delivery is not supported. These include the following:
Should this read "There are certain scenarios in which Safe attachments including Dynamic Delivery are not supported"?
Also the list of limitations should be on the safe attachments page adjacent to this page in the hierarchy.

I think these are limitations of Safe Attachments generally though I may have misunderstood, please could you clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5966b7b-cbaa-eaa2-c9d6-5c6e7218df74
* Version Independent ID: cfcc8772-be5d-009a-0805-62624835ac5f
* Content: [Dynamic Delivery and previewing with ATP Safe Attachments - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/dynamic-delivery-and-previewing?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/dynamic-delivery-and-previewing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/dynamic-delivery-and-previewing.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@iaasazure Thank you for your feedback. The limitations are specifically for including Dynamic delivery so we will leave it here. We have made changes to the Document  to reflect your requests via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2453


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @iaasazure Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
