### ISSUE TITLE
ZAP Bypass procedure doesn't work

### ISSUE THREAD

**Issue by erroltuparker** [MicrosoftDocs/microsoft-365-docs#2290]
"Safe sender lists, mail flow rules (also known as transport rules), Inbox rules, or additional filters take precedence over ZAP. Similar to what happens in mail flow, this means that even if the service determines the delivered message needs ZAP, the message is not acted on because of the the safe senders configuration. This is another reason to be careful about configuring messages to bypass filtering."

This doesn't work or is incorrect and needs to be updated with the new procedure on how to bypass ZAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge (ZAP) - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@erroltuparker, why do you say that statement is incorrect? I asked, and this is what I was told:

> That is how it works. You can turn off ZAP, but not exceptions/overrides take precedence over ZAP. Meaning, that if you allow something that is good, it comes in because you allowed it, not because we said it was good. If you allow it, in a way, it does not matter what we say. If we later on find out it is bad, we go and try to ZAP it but because the item was marked as allowed, we can not touch it, even if it is malicious. That is another reason why allows are dangerous.

Please advise.

**Comment by erroltuparker** [comment]
The whole statement is incorrect. 

There is currently a user voice asking for a more direct desire to bypass zap because it doesn't work, to which you guys refer to that article on how to bypass, which doesn't work - https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/38237416-bypass-zap-feature-for-some-senders

I know that's how it is suppose to work, but it doesn't, which is why I've raised this stating that it's incorrect and needs to be either updated to reflect that you can't bypass ZAP, or the procedure is different other than safe senders or mail flow bypass spam.

Otherwise are you stating that ZAP will still detect the email which pushes it to the review section and even if you approve or decline it won't act on it?

**Comment by chrisda** [comment]
@erroltuparker, if it doesn't work as described, I would recommend that you open a support case.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @erroltuparker hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
