### ISSUE TITLE
Subscription count reduction

### ISSUE THREAD

**Issue by USAGonzo00** [MicrosoftDocs/microsoft-365-docs#2291]
Would like to see further clarification on what happens when the count is reduced but not expiring.  Example.  300 licenses is updated to 250 through renewal.   What happens if there are 300 licenses assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@USAGonzo00 If you have 300 licenses and try to reduce to 250, that action is blocked and you will be told to unassign licenses from users until you're at or below 250.
