### ISSUE TITLE
Gov cloud applicability?

### ISSUE THREAD

**Issue by USAGonzo00** [MicrosoftDocs/microsoft-365-docs#2292]
Any word on the applicability for GCC?  timelines or roadmap?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@USAGonzo00  We know customers are eagerly waiting for this but we can't comment on future releases in the documentation and notifications/announcements will be sent out using standard communication channels.  We have a Note callout in "Learn about sensitivity labels" (https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels) that sensitivity labels aren't yet available in US Government Community (GCC) organizations. I will be very happy to remove this note when that limitation no longer applies!
