### ISSUE TITLE
Conditional Access

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#2294]
Hello,

Is it possible that Conditional Access policies required for this setup?
If yes, can u please help to understand where it is documented for this solution and is it possible to explain how Conditional Access policies created if we build a new Label, as an example with "limited access" and apply this new label to the SharePoint site.

What I see, if run Get-SPOSite, when the label is applied, the site receives this parameter:
ConditionalAccessPolicy : AllowLimitedAccess
If I will apply a label that is not limiting access, then a new parameter applies:
ConditionalAccessPolicy : AllowFullAccess
As far I know, those parameters require the existence of the Conditional Access policies.
In order to use SharePoint Labeling per site, the SharePoint access control in SharePoint Admin must be changed/set to **Allow full access**;
If before it was set as **Limited access** and then we set to **Allow full access**, then this immediately disable Conditional Access policies;

So, if Conditional Access plays the main role here, can u please help to find where it is explained in this document?
If Conditional Access automatically applies in a backend, can you please explain a little bit on which step it is applied and how?

And some other discussion maybe can be added from here: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2187

It feels that this solution is forcing to undo another protection settings and both works with Conditional Access and nothing explained about Conditional Access in this document...

I see it as follow:

To use Sensitivity Labeling with SharePoint sites per site -> Conditional Access must exist;
To use Sensitivity Labeling with SharePoint sites per site -> SharePoint access control policy must be set to **Allow full access**;
If in a past used to limit access for OneDrive and SharePoint sites as SharePoint access control policy was set **Limited** and changed afterward to **Allow full access**, this will disable Conditional Access policies for SharePoint and will remove limitation for users OneDrive sites;
To restore protection for organization the disabled Conditional Access policy must be turned back ON and per-user OneDrive site we must run PowerShell script and set **ConditionalAccessPolicy : AllowLimitedAccess**;

My vision is correct or I'm missing some? :)

I'm very curious about services interaction with OneDrive, SharePoint, and Conditional Access.
How this article: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide
And this article: https://docs.microsoft.com/en-US/sharepoint/control-access-from-unmanaged-devices
Was supposed to work with each other? So we keep end-users OneDrive protected and apply Sensitivity Label per site to allow specific sites to download data. And why when this solution becomes available, in order to apply it, we must undo SharePoint access control policy and set to **Allow full access**, why this was not taken into account between product teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire  I think your question is covered with the following text and link on this page for the Unmanaged devices option, but double-checking in anything is missing:

- Unmanaged devices: For unmanaged devices (https://docs.microsoft.com/sharepoint/control-access-from-unmanaged-devices), allow full access, web only access, or block access completely. If you have configured this setting at the tenant level or for a specific site, the setting you specify here will be applied only if it's more restrictive.

In the linked article, it explains how this uses conditional access - for example: "Blocking or limiting access on unmanaged devices relies on Azure AD conditional access policies"

**Comment by lightupdifire** [comment]
@cabailey 
We have implemented for a long period already Unmanaged devices policy.
The issue here is that the SharePoint Sensitivity label, when you want to use it to limit download data from the site, requires Conditional Access policy. And **Unmanaged devices: For unmanaged devices (https://docs.microsoft.com/sharepoint/control-access-from-unmanaged-devices)** must be set to "allow full access";
I'm in contact with Sanjoyan Mustafi from Microsoft;

**Comment by cabailey** [comment]
@lightupdifire  This page contains the reference for the dependency and I see your other GitHub Issue was closed.  If your question is now about the product design and you're in communication with Sanjoyan, I'll close this issue.  He'll alert me if anything needs changing on this page.

**Comment by lightupdifire** [comment]
@cabailey 

After checking with Sanjoyan, I see that Conditional Access is mandatory to have for an Unmanaged device access scenario with SharePoint labeling. And if the previous configuration was already done for Unmanaged device access, then in order to apply SharePoint labeling it requires a strategy change.

So what happens now with our tenants is that we already used an Unmanaged device access solution and we already moved to modern authentication + Conditional Access + App Protection + MDM + WIP + DLP + etc. policies. 
All this setup limited our B2B users to download files from Unmanaged devices and we were waiting for this SharePoint labeling solution, where we can allow download for specific sites without using PowerShell/Scripting.

As understood from Sanjoyan there will be more changes in SharePoint labeling and I hope my message was read by product teams and future documents + solutions will support behavior when customers already implemented an Unmanaged device access solution.

**Comment by cabailey** [comment]
@lightupdifire  Yes, it works as documented, no changes needed on this page.  

UserVoice and not GitHub Issues is the right place to request product design changes, even if you hear from PMs that they are planning to make changes.  They have lots of changes on a backlog that they continually triage, and having votes on UserVoice helps to bump the priority.  Is this your post? https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/40739041-sharepoint-access-from-unmanaged-devices-combinati

**Comment by lightupdifire** [comment]
Hello Carol,
Yes, this is my post.
