### ISSUE TITLE
Requirement for Invoiced Account

### ISSUE THREAD

**Issue by groves226** [MicrosoftDocs/microsoft-365-docs#2296]
This write up, along with all the other pages that go over Customer Key(CK) do not mention that the setup of CK for Exchange requires an invoiced account. Not having this information up front has set my organization back over a month, and anyone else trying to work this on their own NEEDS to have this information up front.

"
**Mark Severson (DIGITAL INTELLIGENCE SYSTEMS L) <v-markse@microsoft.com>
Wed 6/3/2020 5:52 PM
The system will not physically allow accounts that are paid by credit card to be enabled for CK on our end, so your E5 licenses and KeyVault charges must be invoiced. Are you a reseller?

 

Thanks,

Mark Severson

Exchange Service Encryption Feature Crew 

Enterprise Cloud Team 

Microsoft Corporation 

v-markse@microsoft.com**
"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@groves226 Thank you for your feedback. Sorry that you had to go through this. We have made changes in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2452

Thanks
Sri

**Comment by groves226** [comment]
so I don't see the update in the document itself.. is the update still pending?
________________________________

**Comment by msbemba** [comment]
@groves226 That is correct. The Document has been edited but waiting for authors' approval to get published. We will let you know once that happens.

CC: @yogkumgit 
Thanks
Sri

**Comment by msbemba** [comment]
@groves226 The invoice requirement is for Azure Subscriptions that are used to create Azure Key Vaults for the Customer Key setup. Can you share the specific error that you received while using Non invoiced account?

Thanks
Sri

**Comment by groves226** [comment]
Ok, so you don't get a direct error. It isn't like you try to click something or execute one of the PS commands and it tells you 'no'.

During the early stages when you email the two teams (SPO and EXO) and provide your tenant information, you will be informed that you need an invoiced account to do the Customer Key(CK) process.

What sucks is that since this information isn't provided upfront, in the beginning of the documentation for CK, it causes a long delay as you go about becoming invoiced.

The processes for invoiced are to do it at time of purchase, change your billing method in the admin consoles, OR if invoice is not available to you in the console, you have to do a new purchase, and then start a tenant to tenant migration. Except that isn't fully true, if you start a support ticket and get someone that isn't just going to tell you to do a new purchase, you will get forwarded to the billing team, and they will work with the credit team to do the credit check required for invoiced billing. This can be a long process (9 weeks for us), and company (or personal) information will be shared, and tenant information will be changed to fit wording and information expected to be seen by the credit team.
Now, there are two credit teams. There is one for 365 and one for Azure, so this must be done with both teams, and their process is not synced.

Once you get to invoiced, either through a new purchase or through a drawn-out process getting to the credit teams, you can then continue the path of setting up CK with the SPO and EXO teams.
________________________________

**Comment by msbemba** [comment]
@KCCross @brdesai Could you Please help me to check with PG to see if this requirement is accurate? 

Thanks
Sri

**Comment by yogkumgit** [comment]
@KCCross Please reply to this query. This issue is pending for more that 2 months now. Thanks.

**Comment by KCCross** [comment]
Resolved - PR merged. CK does require an invoiced account.
