### ISSUE TITLE
Microsoft 365 vs Office 365 references

### ISSUE THREAD

**Issue by adamfowlerit** [MicrosoftDocs/microsoft-365-docs#2300]
Still several references to Office 365, looks like some have been changed to Microsoft 365 but not all.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6e20438-8387-bf21-297c-9feb5efe1f1c
* Version Independent ID: ee6a90dd-4050-fa9f-70f4-795f8e7bc3ca
* Content: [Load non-Microsoft 365 data into a review set - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/load-non-office-365-data-into-a-review-set?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/load-non-Office-365-data-into-a-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/load-non-Office-365-data-into-a-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@adamfowlerit Thanks for the heads up. Documentation will eventually make transition from O365 to M365 as the service transitions.
