### ISSUE TITLE
Missing IP from SPF

### ISSUE THREAD

**Issue by michelangelobottura** [MicrosoftDocs/microsoft-365-docs#2301]
Outgoing emails get bounced for SPF fail. The IP is
40.95.66.59

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed62cce4-7497-d557-8ee9-1e9d65dfc408
* Version Independent ID: 58739750-4fee-52d1-be71-9d379f59ee91
* Content: [Set up SPF to help prevent spoofing - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by get-itips** [comment]
Hello @michelangelobottura Michelangelo, how are you? Hope you are doing good.
Do you happen to have the e-mails headers showing the SPF fail, so I can analyze if we need to adjust any documentation?
Thank you

**Comment by get-itips** [comment]
Hello @michelangelobottura did you have chance to see my question? Thanks

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and digging deep into it.  @michelangelobottura We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by michelangelobottura** [comment]
Dear yogumgit,
I had seen your question but I cannot answer it because SPF does not work this way. SPF errors do not cause SMTP protocol errors nor get bounced . Mails which fail SPF checks are filed as spam or discarded silently depending on the SPF policy on the receiving end. Our users which send emails with recipient organization which implement SPF hard fail report their email are not received. Receiving end mentioned that IP to me. How can we move forward? Is there any logs I can retrieve from my tenant that can be useful to identify the issue? Thank you

**Comment by get-itips** [comment]
Hello @michelangelobottura how are you?
I think that, for your scenario, the best will be to open a support ticket from your Tenant, they will be able to help you with your specific situation as here we are limited to documentation fixes and updates. Thank you
