### ISSUE TITLE
Safe Documents

### ISSUE THREAD

**Issue by jason-ra** [MicrosoftDocs/microsoft-365-docs#2302]
Hi Team - this page needs an update to include Safe Documents. Specifically, can you add to the table that confirms whether its O365 ATP P1 or P2?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a177ba2-5cff-b0a0-6afa-717689db2884
* Version Independent ID: 802f6c49-9a14-e76f-6cf3-67862b40f18d
* Content: [Office 365 Advanced Threat Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/office-365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by PrasadKasireddy** [comment]
The safe document feature is only available to users with the Microsoft 365 E5 or Microsoft 365 E5 Security license (**not included in Office 365 ATP plans**).

Refer - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide under section 'What do you need to know before you begin?'

**Comment by PrasadKasireddy** [comment]
@jason-ra  - to avoid the confusion on this, I have added a additional point that the safe document feature details with respective licence. the PR is submitted.
