### ISSUE TITLE
Why is there no "total storage available"

### ISSUE THREAD

**Issue by auroraeosrose** [MicrosoftDocs/microsoft-365-docs#2304]
This report does NOT let you see the total usage because it does not tell you how much is actually available

Usage is more than just "this person has this much stored" but also "out of xGB you have yGB stored"

Please give us a total on the report  or explicitly state in the documentation that this report does NOT tell you total usage but rather a snapshot of individual usage with no percentage or amounts of the total available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be6f5c5f-874c-05a7-e633-bd46613d908e
* Version Independent ID: e0578fe4-2b3f-7659-052f-7a2cd0910b38
* Content: [Microsoft 365 Reports in the admin center - OneDrive for Business usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/onedrive-for-business-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/onedrive-for-business-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/onedrive-for-business-usage.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by get-itips** [comment]
Hello @auroraeosrose Elizabeth, how are you?
Thanks for your feedback.
I will propose to state that in the article thru a pull request, also, for your request to improve the report to reach the product team, I recommend opening a suggestion in https://office365.uservoice.com/
Thank you again.
Andrés
