### ISSUE TITLE
Clarity around what applications targetted release applies to

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/microsoft-365-docs#2310]
Hi,
Could you add some clarity please around how targeted releases affects teams and OneDrive, is it just the web version of these products that first release updates? i.e. the client version of OneDrive, its updates are linked to GPO and update ring you set, however what about the MS Teams client though as that always updates on a more regular basis? Ive seen a few discussion threads asking the same so its not crystal clear. The important section on this page is where this could be added rather than just say M365 I think this could be expanded
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd43f78a-7c74-5c56-c1f0-24deb342455f
* Version Independent ID: f7ed9828-2580-1b50-d126-003d222abb5e
* Content: [Set up the Standard or Targeted release options - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/release-options-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/release-options-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by MaratMussabekov** [comment]
Hello @obhayes ,
This article is about update channels for services. You can read about feature updates for client apps [here](https://docs.microsoft.com/en-us/deployoffice/overview-update-channels).
Thank you

**Comment by yogkumgit** [comment]
@MaratMussabekov  Thank you very much for the contribution and updating the documentation with PR. @obhayes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
