### ISSUE TITLE
Policies can't be disabled as described in the text

### ISSUE THREAD

**Issue by g7cnp** [MicrosoftDocs/microsoft-365-docs#2311]
This document states that the Policy option can be set to 'off' for trusted senders such as scanners, and fax machines yet policies can only be applied based on rules that depend on the recipient!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be929ba-8bef-b75c-0475-041bb6ec441a
* Version Independent ID: 358f9e1a-1900-7c8c-814a-b878a9a22f9e
* Content: [Set up Office 365 ATP Safe Attachments policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MaratMussabekov  Thank you very much for the contribution and updating the documentation with PR. @g7cnp 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
