### ISSUE TITLE
Security Center Hunting vs Microsoft 365 security Advanced Hunting - list of the reasons there are two

### ISSUE THREAD

**Issue by SergGu** [MicrosoftDocs/microsoft-365-docs#2312]
I realized there are TWO separate GUI for hunting:
1. https://securitycenter.windows.com/hunting
2. https://security.microsoft.com/advanced-hunting

Both look very similar, but the second one has more event types. Can you please address this discrepancy (for example explain why there is a difference) somewhere in documentation? "Frequently asked questions when turning on Microsoft Threat Protection" seems like for a good place for such explanations.

Best Regards,
Serg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d695bd6b-eea7-e9ba-1d0c-b0f473fcbc6c
* Version Independent ID: 36deb4fd-a391-0ea5-817a-201b5a16e167
* Content: [Frequently asked questions when turning on Microsoft Threat Protection - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-enable-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/mtp-enable-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/mtp-enable-faq.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by MaratMussabekov** [comment]
Hello @serggu,
https://securitycenter.windows.com/hunting - this one is for Microsoft Defender Advanced Threat Protection. See [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-overview)
https://security.microsoft.com/advanced-hunting - this one is for Microsoft Threat Protection. See [here](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/advanced-hunting-overview?view=o365-worldwide)
**Both look very similar, but the second one has more event types.** - the second one has wider scope. It includes workspaces from Microsoft Defender ATP, Office 365 ATP, Microsoft Cloud App Security, and Azure ATP.

**Can you please address this discrepancy (for example explain why there is a difference) somewhere in documentation? "Frequently asked questions when turning on Microsoft Threat Protection" seems like for a good place for such explanations.** - I am not sure this information must be mentioned in this article. I believe it should be added to the article dedicated to hunting in Microsoft Threat Protection (I will create a PR).

Thank you

**Comment by yogkumgit** [comment]
@MaratMussabekov Thank you very much for the contribution and updating the documentation with PR. @SergGu Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
