### ISSUE TITLE
Maximum site collections and policies typo and question

### ISSUE THREAD

**Issue by AndrewJolly** [MicrosoftDocs/microsoft-365-docs#2316]
I noticed a typo in the first section of the information, but I also wanted to confirm that the documentation is correct. 

Maximum of 10 sites collections across all policies. (Recommendation is to edit this to say '10 site collections' rather than 'sites'
Maximum of 10 policies across your tenant.

The other question I is on the accuracy of these two points. Does this mean the following scenarios would be true?

- A tenant can have maximum 10 policies but this would mean that each policy would only allow for 1 site to be specified. 
- A tenant can have one policy with 10 sites specified within it
- A tenant could have 3 policies, the first with 6 sites specified and the 2nd and 3rd with 2 sites each
- A tenant could have 4 policies with 2 sites specified within them

If the above statements are true then in summary the auto-apply sensitivity labels is only able to be applied to maximum of 10 site collections within a tenant. 
This would mean that organisations have to be very selective about which sites that want to have auto applied labelling to.

Are these assumptions correct.

**Comment by denisebmsft** [comment]
Hello @AndrewJolly! To which article(s) does your feedback apply? This information will help us route your issue to the correct writer/team.

**Comment by AndrewJolly** [comment]
Sorry i forgot to put the link in:
https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide

**Comment by yogkumgit** [comment]
@cabailey Please help us and answer this issue. Thanks

**Comment by cabailey** [comment]
@AndrewJolly & @yogkumgit You can leave this with me.  It's wording I inherited and I'm checking with engineering.  It seems "site collection" isn't the correct term to use with SharePoint but what I'm not sure about is whether the limit of 10 sites per policy means 10 site locations (where one SharePoint site can include subsites, if migrated from on-premises for example) or literally 10 sites even if some of these are subsites from the one specified.  If it's literally 10 sites per policy, and you can have 10 policies per tenant, that's a maximum of 100 sites.

**Comment by cabailey** [comment]
@AndrewJolly  Now reworded as "Maximum of 10 auto-labeling policies per tenant, each targeting up to 10 sites (SharePoint or OneDrive)"  Hopefully that is clearer.  I'm told very few customers have subsites for SharePoint Online, but if they do and the top-level site is specified, it's the top-level site only that gets counted (while the subsites are still scanned). You will know when you have reached the limit because the UI will prevent you from entering an 11th entry.
