### ISSUE TITLE
Customer Lockbox not visible.

### ISSUE THREAD

**Issue by R1ckH** [MicrosoftDocs/microsoft-365-docs#2317]
The site shows where to change the Customer Lockbox settings but as of today I don't see this in the admin portal. Even switching back to the 'old admin center interface' I don't see this
Where can I make the adjustment? (This is for point of Secure Score.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by PrasadKasireddy** [comment]
Thanks a reporting, Settings & policy option is moved to Org Settings - please refer the below screen, I will update the document.

![image](https://user-images.githubusercontent.com/11626905/86780717-ac734500-c07a-11ea-9969-804c56f19e63.png)

**Comment by R1ckH** [comment]
Hi PrasadKasireddy,

Thank you for your response.

I don't see this option:

![image](https://user-images.githubusercontent.com/67906230/86782883-eb47d180-c05f-11ea-8a94-15e48a40254e.png)


I'm checking the setting with a Global Administrator account.

Best Regards,

**Comment by GiantCrocodile** [comment]
It's only shown if you have a proper license e. g. Microsoft 365 E5 Compliance add-on or Microsoft 365 E5.

**Comment by R1ckH** [comment]
Thanks for the clarification. 
Does this apply with only 1 E5 license or do all users require this?

**Comment by msbemba** [comment]
@R1ckH THank you for your feedback. The customer lockbox is included with the Microsoft 365 or Office 365 E5 subscriptions and can be added to other plans with an Information Protection and Compliance or an Advanced Compliance add-on subscription. 

This has been added to the document and all users who need to use the customer lockbox feature should have the license added.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @R1ckH Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
