### ISSUE TITLE
On the Domains page, select a domain.

### ISSUE THREAD

**Issue by sfilinto** [MicrosoftDocs/microsoft-365-docs#2318]
"On the Domains page, select a domain."
this step seems to have changed & the documentation needs to be updated. its now 2 clicks. refer to https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2210

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c52d59a-7466-a5a8-7031-e4ea7b782f57
* Version Independent ID: e02a33bc-12c6-4192-cf3f-bcea567085c3
* Content: [Change nameservers to set up Microsoft 365 with any domain registrar - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@sfilinto Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2451

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sfilinto Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
