### ISSUE TITLE
Column for DataSource

### ISSUE THREAD

**Issue by laughingman42** [MicrosoftDocs/microsoft-365-docs#2319]
[Enter feedback here]
It would be good to have a column added  that described datasource(s) for each Table. 
AlertInfo - MCAS, D-ATP, O365 ATP
IdentityInfo - AzureAD, Azure ATP(?)
IdentityLogonEvents - MFA(?), ADFS(?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc9f0472-a1fe-8d1e-f081-fd3c97bbfc92
* Version Independent ID: ddc56801-5d2f-cef2-c6fe-3360368088fa
* Content: [Data tables in the Microsoft Threat Protection advanced hunting schema - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/advanced-hunting-schema-tables?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/advanced-hunting-schema-tables.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/advanced-hunting-schema-tables.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by dariomws** [comment]
Hi @laughingman42, thank you for your feedback and help us to improve docs.microsoft.com.

For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/.
There, your suggestion will reach the product team. Here we are limited to documentation issues and improvements.

**Comment by yogkumgit** [comment]
@laughingman42  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by laughingman42** [comment]
I am not sure this is a feature request. The data is already coming in. What's not clear in the documentation is where is the data coming from. Like For IdentityInfo the corresponding entry is: Account information from various sources, including Azure Active Directory
Is it not possible to define "various sources". And whether the data comes via Azure ATP or Defender ATP, or O365.

**Comment by dariomws** [comment]
@laughingman42 Now I understand, you're talking about add a new column to the table here:
https://docs.microsoft.com/microsoft-365/security/mtp/advanced-hunting-schema-tables#schema-tables
This column should have information about the source of the data.

I cannot provide this information but I'll forward your feedback. Thank you!

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for your initiative. @laughingman42  We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
