### ISSUE TITLE
This documentation doesn't explain anything

### ISSUE THREAD

**Issue by glenquarless** [MicrosoftDocs/microsoft-365-docs#232]
My business is moving to MMD and having read this page I still have no idea what that means, what is MMD? How is different from a desktop, this page doesn't clarify or elucidate on that, it's just says business-speak gibberish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68e02661-89f9-a356-3e08-deb7314e3f2b
* Version Independent ID: 6e845983-9524-fac0-c299-7ff37ecf7888
* Content: [Is Microsoft Managed Desktop right for you](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/intro/index)
* Content Source: [microsoft-365/managed-desktop/intro/index.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/intro/index.md)
* Service: **m365-md**
* GitHub Login: @TrudyHa

**Comment by robinwilson16** [comment]
Totally agree. It just needs to explain what exactly it is, then what you get and what the benefit is compared with other solutions and finally the price. Maybe throw in a few screenshots/photos too.
Then a further page could go into the technicalities such as what happens if there is a software problem that needs resolving.
None of the pages concisely tell you what exactly it is.

**Comment by mypil** [comment]
@TrudyHa - We would like to follow up on this. Do you have any updates? Thanks.

**Comment by mypil** [comment]
@TrudyHa - Do you have any updates on the progress of this?

**Comment by mypil** [comment]
@TrudyHa - We would like to follow up on this. Do you have any updates? Thanks.

**Comment by robmazz** [comment]
@TrudyHa - just checking in, can you address this question? Thanks!

**Comment by mypil** [comment]
@TrudyHa - We would like to follow up on this. Any updates on this? Thanks.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by TrudyHa** [comment]
Sorry for the late reply. I'm working with the Engineering team on updates to this topic. I'll publish updates when we have changes approved by all approriate stakeholders.
