### ISSUE TITLE
Groups object limit

### ISSUE THREAD

**Issue by kazukiy-MS** [MicrosoftDocs/microsoft-365-docs#2324]
[Enter feedback here]
"Groups an admin can create | Up to default tenant limit of 500K"
It seems the above limit refers to the below Azure AD limits, so it should be 300K now.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#active-directory-limits
*A maximum of 50,000 Azure AD resources can be created in a single directory by users of the Free edition of Azure Active Directory by default. If you have at least one verified domain, the default Azure AD service quota for your organization is extended to 300,000 Azure AD resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by PrasadKasireddy** [comment]
Duplicate request - https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2124

**Comment by PrasadKasireddy** [comment]
related to https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2124

**Comment by dariomws** [comment]
@kazukiy-MS I got the confirmation that the limit is 500k, to go beyond that limit you must contact Microsoft Support.

Thanks you for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.
