### ISSUE TITLE
Why can both Send As and Send On Behalf be set at the same time?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#2337]
Per the document, "You can configure Send as or Send on behalf for a given user, but not both. If you configure both, it will default to Send as."  So why does Exchange (specifically O365 Exchange) allow you to assign both at the same time?  

Seems more logical to only allow one set at a time.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3a862d8-4223-7bb7-42f1-9842cbeacf87
* Version Independent ID: 2c3c7e9a-a44d-168e-2083-b1527ab3f61c
* Content: [Allow members to send as or send on behalf of a Group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @Canis-Lupis, thank you for your feedback.

My apologies but I don't have this information. For feature requests, I need to kindly redirect you to this resource https://office365.uservoice.com/. There, your suggestion will reach the product team.

**Comment by Canis-Lupis** [comment]
That wasn't a feature request.
________________________________

**Comment by dariomws** [comment]
Thanks @Canis-Lupis, I don't have an explanation about why we can set both. Here we are limited to documentation issues and improvements.

**Comment by dariomws** [comment]
@Canis-Lupis Thank you again for taking the time to open this issue. My apologies again but I don't have the detail you are asking for.

My personal opinion is that in different systems you can apply a lot of permissions and always the most restrictive permission wins, and the same applies here.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Canis-Lupis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
