### ISSUE TITLE
Document conflict

### ISSUE THREAD

**Issue by heymybru** [MicrosoftDocs/microsoft-365-docs#2341]
Conflict 

https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-getting-started-with?view=o365-worldwide

"Where can you use trainable classifiers" section  states that "Trainable Classifiers" can be used as a condition in  Auto Labeling. The table in the following page - contradicts this statement.

https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide#compare-auto-labeling-for-office-apps-with-auto-labeling-policies 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3c5c98-9f47-9512-b932-2f72822796d2
* Version Independent ID: fd477cf9-4ee0-544f-10c6-f3dfccb10186
* Content: [Getting started with trainable classifiers (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-getting-started-with?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/classifier-getting-started-with.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-getting-started-with.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@heymybru 
After talking this through with the owner of the other topic and going through the UI we can confirm that both articles are correct.  I think perhaps a closer reading of the statement in https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-getting-started-with?view=o365-worldwide  will show that it is referring to **_retention_** label policies.

Where you can use trainable classifiers
Both built-in classifiers and trainable classifiers are available as a condition for auto-apply **_retention_** label policy based on a condition and communication compliance.

We went through the auto apply label table and UI to create one and confirmed that trainable classifiers  are supported for the Office apps BUT NOT supported in Auto-labeling policies.
