### ISSUE TITLE
Criteria for searching email body unclear

### ISSUE THREAD

**Issue by ChrisParrBIE** [MicrosoftDocs/microsoft-365-docs#2342]
There's plenty of information on how to search particular email message fields, but nothing that states clearly how to simply search for emails containing a particular string or even if that's possible.

e.g. I can easily search for emails set to or from a particular email address with the participants property, but can't see anything describing how to search for that email address in the message body.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/keyword-queries-and-search-conditions?redirectSourcePath=%252fen-us%252farticle%252fKeyword-queries-and-search-conditions-for-Content-Search-c4639c2e-7223-4302-8e0d-b6e10f1c3be3&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ChrisParrBIE Thanks for the question. There isn't a searchable "body" mail property. You would just search for keywords without specifying a property:value pair. In other words, in the search UI, you would type keyword, string, email address in the Keywords box. If an email address returns too many items with that address in the to, from, fields, you might try to exclude those with something like -participants:<emailaddress> or a "does not include these participants" condition.

I'll look for a way to add info to this topic about searching for keywords/strings in message body.
