### ISSUE TITLE
Verifying label synchronization with SPO

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/microsoft-365-docs#2343]
The section "Schedule roll-out after you create or change a sensitivity label" recommends
" 2.Wait for at least 24 hours after initial publication. Verify that the label has fully synchronized."    

Please provide instructions or guidance on how to verify that the label has synchronized.    Include guidance for multi-Geo tenants.

Consider that the administrator who can create/manage labels may NOT be a SharePoint administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Brian, I'm going to level with you:  When I took ownership of this article, this section was already written and I had similar questions  and proposed a reword, based on my understanding.  I'll revisit that with the PM but my understanding is there is no way for an admin (global or site admin) to verify the synchronization status of sensitivity labels other than wait for the prescribed period of time and test that the behavior is as expected.  By "fully synchronized" I think it's alluding to the fact that the label can appear more quickly in some apps than others - for example, appear quickly in the desktop app so the user selects the label and applies it to a document, then uploads it to SharePoint before the label has synchronized to that service.

**Comment by bholzmmc** [comment]
So to carry-out that process my understanding is that it would mean a user has to connect to each multi-geo SPO site and then:

-          access some sub-site or page that allows them to create or modify a document

-          Open an aforesaid document in the browser

-          Observe that the Sensitivity button appears with the expected labels and/or underlying functionality ?

Seems a lot of effort (I potentially foresee lots of labels and changes as this deploys to the 80,000 people spread across multiple lines of business across the globe).   Is there a simpler way ?

We have 12 Geo’s.

Brian

**Comment by cabailey** [comment]
When there's something specific required for Multi-Geo, we call that out - as we do on this page for enabling sensitivity labels.  But the replication latency time applies to all geos so testing on a single geo should be sufficient.  The key thing here, is wait the prescribed period of time between before rolling out a newly published label to all users because it might appear in desktop 
 apps before it's synchronized to SharePoint.

**Comment by bholzmmc** [comment]
Carol,

Thank you very much for remembering my concern and making me aware of this.  I did add a vote to it.
I  also created a UserVoice entry relating to the PowerShell equivalent of this
https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/40957477-make-the-get-labelpolicy-command-distributionstatu

You might be interested in a couple of others I’ve created.  Perhaps you know of others with similar concerns.
https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/40952164-unified-labeling-client-change-help-and-feedbac

https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/40957612-remove-the-links-to-aip-and-tell-me-more-at-the

Brian

**Comment by cabailey** [comment]
@bholzmmc  I support your vote :)  We can document only what's implemented and supported.  

The new (renamed) section is now live: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide#publishing-and-changing-sensitivity-labels that clarifies the current procedure is to wait the prescribed period of time.  You might be pleased to see the new, reduced timings (one hour for new labels and changes to label policies).  This timing improvement has just rolled out and completed for all tenants.  It doesn't address the verification issue but does help with the wait period.  Closing this doc issue now.
