### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by pear7777** [MicrosoftDocs/microsoft-365-docs#2345]
1) this is regardin a MICROSOFT product WHY do I get KICKED into m* UN-USEABLE GITHUB 
GITHUB IS SOMTHING LIKE A SECRET SECT IN USER LAND
DON'T MAKE SUPPORT ANY HARDER TO GET

SECOND

THE DOWNLOADER DOES NOT DOWNLOAD anyting.

THANK YOU 

[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 1da8786f-5fa8-8787-045b-5ca68d9749b5
* Version Independent ID: 9cf12db3-4a79-62d2-2ef3-bf565fd53a6d
* Content: [Get started with core eDiscovery cases in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/nl-nl/microsoft-365/compliance/get-started-core-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/get-started-core-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-core-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
no actionable feedback
