### ISSUE TITLE
Unable to edit billing frequency per documentation

### ISSUE THREAD

**Issue by ka24dime** [MicrosoftDocs/microsoft-365-docs#2346]
The page referenced indicates that there should be a link to edit the billing frequency between monthly and yearly, but my page does not have this.  Edit is only available for the card and whether or not the subscription should renew:

Billing
$15.00 (excluding tax)
Billed monthly
Visa ****XXXX Edit
Renews on 7/25/20 Edit
View last bill

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d66f21-cff3-bb96-df38-6f67d95eb6cf
* Version Independent ID: 00256bad-f01c-02a6-9554-a0be1ce933ea
* Content: [Change your payment frequency](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-payment-frequency?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-payment-frequency.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-payment-frequency.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by dariomws** [comment]
Hi @ka24dime, thank you for your feedback.

I can see the option as available:
![image](https://user-images.githubusercontent.com/33589238/88224485-6fdd4700-cc3f-11ea-9902-3398b010eb96.png)

I don't know how you adquired your license, but if you cannot change the payment frequency I need to kindly suggest opening a support ticket directly from your tenant's administration, they will be able to help you as here we are limited to documentation issues and improvements.

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @ka24dime Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
