### ISSUE TITLE
[Document update Request] outbound spam notification alerts been deprecated and replaced by Alerts in SCC

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/microsoft-365-docs#2347]
Need help to update this documentation that outbound spam notification alerts been deprecated and replaced by Alerts in SCC.
This is been confirmed here under issue 
Issue 1553788: [Customer Escalation] Issue Severity: 2 Online: [JPN] Outbound spam notification is not working as expected.

--
Excerpt from above escalation-
This notification is a legacy / deprecated setting and is going to be removed... Product team will not investigate issues reported with this notification anymore...  The correct place to configure these notifications is in the Alerts section of the SCC - which is the place to configure many different types of protection alerts from a single UI
--

Current wording although already discourage customers not to use outbound spam notification alerts as below, however we need to be clear saying it is legacy and deprecated and soon will be removed from settings in UI/Powershell

<need to change below from the documentation>
---
_We recommend that you use the alert policy rather than this setting in the outbound spam policy to notify admins and other users_
--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@qaehtesh, OK information added/updated.

Thanks for the feedback.

Closing
