### ISSUE TITLE
Number of Groups a user member of

### ISSUE THREAD

**Issue by GaneshPrabuBaburaj** [MicrosoftDocs/microsoft-365-docs#2349]
In this article it was mentioned, user can be member of 1000 groups. However the below article says a user can be part of any number of groups. Which one is correct?

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#active-directory-limits

**Comment by denisebmsft** [comment]
Hello @GaneshPrabuBaburaj! Thank you for the feedback. Can you please tell us to which article(s) your question applies? This will help us route the issue to the correct writer/team.

**Comment by GaneshPrabuBaburaj** [comment]
Hi @denisebmsft , The question is belong to the below article
https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#group-limits

**Comment by GaneshPrabuBaburaj** [comment]
Hi @denisebmsft , Hope you are in track of this question.

**Comment by GaneshPrabuBaburaj** [comment]
Hi @yogkumgit , Hope we are in track of this question. Could you please update, which article is correct?

**Comment by yogkumgit** [comment]
Closing via #2382
