### ISSUE TITLE
IB license requirements

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/microsoft-365-docs#2350]
In "Required licenses and permissions" section, the article lists the following licenses:

- Microsoft 365 E5
- Office 365 E5
- Office 365 Advanced Compliance
- Microsoft 365 Compliance E5

But another [article](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-barriers) gives us a different list of licenses:

* Microsoft 365 E5/A5
* Microsoft 365 E5/A5 Compliance
* Microsoft 365 Insider Risk Management
* Office 365 E5/A5
* Office 365 Advanced Compliance

Please update the articles to have a consistent license requirements. Or add a note explaining, why these lists are different.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Learn about Information barriers - Microsoft 365 Compliance](https://docs.microsoft.com/en-au/microsoft-365/compliance/information-barriers?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
hi @shivtorov thanks for catching this, I have updated the IB document
