### ISSUE TITLE
Teams Chat Records are not stored in Exchange mailboxes

### ISSUE THREAD

**Issue by 12Knocksinna** [MicrosoftDocs/microsoft-365-docs#2354]
The statement that Teams chat messages are stored in user mailboxes is incorrect. These are compliance records, not the actual Teams chat messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0bb4d7-d9fa-ae92-d3ca-246147d1434a
* Version Independent ID: 7ba20db3-55e2-3d29-2d6c-6f68a6b577a8
* Content: [Searching cloud-based mailboxes for on-premises users - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@yogkumgit @12Knocksinna Topic has been updated to address this issue.
