### ISSUE TITLE
MS record details not available

### ISSUE THREAD

**Issue by dmatranga** [MicrosoftDocs/microsoft-365-docs#2355]
Hit a wall on step 4 when trying to create the TXT record in DNS at GoDaddy. When I go to the Domains section in O365, the remainder of the record information is masked by "...". There's no way to expand the entry so I can see the full information, as far as I can tell.

![image](https://user-images.githubusercontent.com/75672/87354977-2a28cc00-c525-11ea-84a2-21d6fc451c40.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa9b019f-fa0b-5e2d-57fc-1e3acef0c75d
* Version Independent ID: a75691ca-2f8a-9b6f-4e1f-b7d726da1d96
* Content: [Create DNS records at GoDaddy for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-godaddy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-godaddy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-godaddy.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@dmatranga Thank you for your feedback. I was able to get to the record by clicking on the type (in your case TXT)

![image](https://user-images.githubusercontent.com/45987684/88119784-0b8a9b00-cbdf-11ea-89cb-9271e9684a43.png)


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @dmatranga Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
