### ISSUE TITLE
The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ProKrob** [MicrosoftDocs/microsoft-365-docs#2358]
PS Script failed with msg: The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by PrasadKasireddy** [comment]
Please let me know what is version of Azure Active Directory PowerShell, it seems to be issue with AzureAD poweshell manger  - please refer the following article - https://github.com/Azure/azure-docs-powershell-azuread/issues/189

**Comment by msbemba** [comment]
@ProKrob  Thank you for your feedback. I have tested with both Azure AD and Azure AD preview module and this is a known issue with  AzureAd module, you will have to Install-Module AzureADPreview to run this cmdlet as mentioned in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ProKrob Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
