### ISSUE TITLE
Outbound spam notifications

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#2359]
This article should mention that outbound spam notifications only work when configured on the default outbound spam policy.
They are not generated when enabled on any custom outbound spam policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, it kind of does already: <https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide#use-the-security--compliance-center-to-create-outbound-spam-policies>:

![image](https://user-images.githubusercontent.com/33166947/87975254-390d0280-ca80-11ea-80d0-35badf6873c2.png)

![image](https://user-images.githubusercontent.com/33166947/87975303-4924e200-ca80-11ea-9a68-9cdeb002e3d4.png)

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @JeroenDronkers Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
