### ISSUE TITLE
Wrong info: TargetedUserProtectionAction should be TargetedDomainProtectionAction

### ISSUE THREAD

**Issue by MichelvanVliet** [MicrosoftDocs/microsoft-365-docs#2360]
The following information is incorrect:
_Protected domains: If email is sent by an impersonated domain
_TargetedUserProtectionAction__
The command should be: **TargetedDomainProtectionAction**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Office 365 ATP security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, security baselines, baselines for EOP, baselines for ATP, setup ATP, setup EOP, configure ATP, configure EOP, security configuration - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide#anti-spam-anti-malware-and-anti-phishing-protection-in-eop)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by PrasadKasireddy** [comment]
Thanks @MichelvanVliet for reporting this issue, I will correct that through PR.

**Comment by PrasadKasireddy** [comment]
@robmazz  - please assign this request to my queue

**Comment by PrasadKasireddy** [comment]
sorry @robmazz  - it is accidentally removed as a assignment.   please reassign.
