### ISSUE TITLE
RichShops-Mic

### ISSUE THREAD

**Issue by 0842854175** [MicrosoftDocs/microsoft-365-docs#2361]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: ad8e657e-2aa7-230d-0d9d-675c0200ac18
* Version Independent ID: 2028f003-2624-2bd3-34ea-6022d495e2c6
* Content: [Set up Windows devices for Microsoft 365 Business Premium users - Microsoft 365 Business](https://docs.microsoft.com/th-th/microsoft-365/business/set-up-windows-devices?view=o365-worldwide)
* Content Source: [microsoft-365/business/set-up-windows-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/set-up-windows-devices.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by robmazz** [comment]
Closing, no actionable question or request.
