### ISSUE TITLE
Unclear which language would be used to display end-user notifications.

### ISSUE THREAD

**Issue by yvesrosius** [MicrosoftDocs/microsoft-365-docs#2362]
The default value is Default, which means end-user quarantine notifications use the **default language of the EOP organization**.

What does this mean???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed2861d-860e-5d27-9259-fb9db2187f4b
* Version Independent ID: 09ef5622-3a7e-30f9-00f9-4c5578f8e1ca
* Content: [Configure spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by faoquong** [comment]
@yvesrosius it simply means that end user spam notification will use the the default language of the cloud-based organization.

**Comment by chrisda** [comment]
@yvesrosius, I've been told that the value Default means English. I've updated the topic accordingly.

Thanks for the feedback.

Closing.
