### ISSUE TITLE
Any other way to test "Safe Documents" functionality from the end user side?

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/microsoft-365-docs#2364]
Hello,

I have enabled Safe Documents and I have downloaded a few office documents from the internet, but I still do not see ATP being mentioned in the yellow banner of Protected View. Is there any other way to test "Safe Documents" functionality from the end user side?

-Jose
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@jose-camacaro Thank you for your feedback. We tested this in the lab and looks like the feature is working as expected. Having said that there are a few reasons why users are not able to view the yellow banner 1) The Office Version is not 2004 (12730.x) or above 2) They are not assigned Microsoft 365 E5 or Microsoft 365 E5 Security license. If both the above criteria match, I would recommend you contacting M365 support via the need help option in the admin center. Having said that, there is no requirement at the moment to modify the document, so we will proceed with closing this issue. In case you find out something from the support that needs to be added or modified to this document, please let us know.

@yogkumgit  We can close this issue as the document does not need to be modified at the moment.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @jose-camacaro Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
