### ISSUE TITLE
Modify references to "Thales nShield HSMs" to be "nCipher nShield HSMs"

### ISSUE THREAD

**Issue by MPenny-nCipher** [MicrosoftDocs/microsoft-365-docs#2369]
Hello

Thales sold the nCipher business to Entrust Datacard some months back. The text on this page should therefore be modified to  show the "nCipher nShield HSMs" as opposed to "Thales nShield HSMs".

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@MPenny-nCipher  Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2414

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MPenny-nCipher Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
