### ISSUE TITLE
Session creation is throttled. Max value of MaxCountOfSuccessfulSessions is 2 when using EDM Upload Agent

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#2370]
Please consult with Engineering and document in this article the limit of uploading data into the same data store, which is at max twice per day.

If I try to upload data using the EDM Agent into the same data store, for a 3rd time in the same day, I will get this nice throttling message:

_"Session creation is throttled. Max value of MaxCountOfSuccessfulSessions is 2."_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Alex-Catalin  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2415

Thanks
Sri

**Comment by chrfox** [comment]
hi @Alex-Catalin thanks for pointing this out, a correction has been added and published
