### ISSUE TITLE
Steps changed

### ISSUE THREAD

**Issue by mevenega** [MicrosoftDocs/microsoft-365-docs#2374]
Hello,

Please review as the way you update your contact information changed recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecf0dbf6-b2f8-5370-fd04-f7a13073835a
* Version Independent ID: 8b58ecef-f957-4360-08a5-80d6fe8886e3
* Content: [Update your admin phone number and email address - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/update-phone-number-and-email-address?redirectSourcePath=%252fen-us%252farticle%252fUpdate-your-admin-phone-number-and-email-address-in-Office-365-767349fa-f646-46d9-9dab-4a65049bdd1f&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/update-phone-number-and-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/update-phone-number-and-email-address.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@mevenega Thank you for your feedback. We have made changes to the doc via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2429

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @mevenega Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
