### ISSUE TITLE
Article Not reflecting required permissions.

### ISSUE THREAD

**Issue by JDMEXOPRO** [MicrosoftDocs/microsoft-365-docs#2376]
When in O365 Admin Center as a Groups Admin role selecting an O365 Group there is warning on group pane.
Warning in yellow:  'You don't have permission to save changes'

The only way to make changes to an O365 Group in the O365 Admin Center is to have Groups Admin Role assigned and retain Ownership AND Membership. When those are met is when this warning goes away and an admin is able to modify group membership.

<img width="434" alt="Admin_Roles" src="https://user-images.githubusercontent.com/68434608/87801009-5f2a6c80-c80c-11ea-99e5-ec8faade9172.PNG">

![Groups Pane Error](https://user-images.githubusercontent.com/68434608/87801204-9e58bd80-c80c-11ea-9df3-8bd56bc808dc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40174ff9-7dc6-a706-c546-77e2391ab8d7
* Version Independent ID: a01b7077-976f-dded-ed25-18e8585b28b0
* Content: [Add or remove members from Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/add-or-remove-members-from-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/add-or-remove-members-from-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/add-or-remove-members-from-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@JDMEXOPRO Thank you for your feedback. We have added a note to the document which talks about admin roles needed to make changes to an o365 group. This can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2404

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed. The description now has the required admin roles needed to make changes.

"Only a global administrator, Exchange administrator, Groups administrator, or user administrator can make these changes"

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @JDMEXOPRO 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
