### ISSUE TITLE
Manage who can create Groups

### ISSUE THREAD

**Issue by Chandyno** [MicrosoftDocs/microsoft-365-docs#2377]
Instead can we do Manage who can't create Groups ? 
https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?view=o365-worldwide

**Comment by msbemba** [comment]
@Chandyno Thank you for your feedback. I find the information on the document to be accurate. Are you referring to change the Title of the document? If yes, I think it means the same as the document covers both the topics. The security group used in the script to enable office 365 group is the key, If the user is a part of the group they can create groups, if they are not they don't get an option to create a group.

Hope this helps!

Thanks
Sri

**Comment by Chandyno** [comment]
Hello Sri,

Thanks, 
The security group used in the script to enable office 365 group is the key,
==> Agreed.
 If the user is a part of the group they can create groups, if they are not they don't get an option to create a group.
=+>Agreed 

But lets take below example:-
Out of 5000user, I got 4800 user who are allowed to create O365 groups but only 200 users not allowed to create group.
So as per your statement I will need to create a Sec-Group with 4800 people to be allowed for group creation. 
Instead was wondering if we can create a small group who is not allowed ( Like200)  and make the script magical ?

Adding 4800 people is tiresome ( Huge Number) then doing the opp of just adding 200 people as this will make life easy. 

Hope I was able to explain the requirement.

**Comment by msbemba** [comment]
@Chandyno  Thank you for the detailed requirement. Unfortunately, the attributes available are minimal at the moment (Group creation allowed Group ID and Enable group creation) and you can only Manage who can create the groups and not the other way around.

![image](https://user-images.githubusercontent.com/45987684/88236654-1b67b500-cc9b-11ea-92af-53e96cbda47b.png)

If there are more attributes added to this parameter (Get-AzureADDirectorySetting), , we will keep you updated via the document. 

Hope this helps!

Thanks
Sri

**Comment by Chandyno** [comment]
Thank You for taking time to confirm the same. Appreciate.
