### ISSUE TITLE
Number of Groups a user member of

### ISSUE THREAD

**Issue by GaneshPrabuBaburaj** [MicrosoftDocs/microsoft-365-docs#2382]
In this article it was mentioned, user can be member of 1000 groups. However the below article says a user can be part of any number of groups. Which one is correct?

https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-service-limits-restrictions
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#active-directory-limits

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#group-limits)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by GaneshPrabuBaburaj** [comment]
Issue raised here as well #2349. Please update any one of the issue. 
cc: @yogkumgit

**Comment by msbemba** [comment]
@GaneshPrabuBaburaj Thank you for your feedback. The limitation of 1000 groups applies only to office365 groups. There is no limitation on being a part of Azure AD groups which includes security groups as well as O365 groups. For example,  a user can be a part of 10000 security groups and 1000 office365 groups but he cannot exceed the limit of 1000 w.r.t office365 groups.

I don't see a roadmap to increase the limit to office365 groups yet. 

Hope this helps! 
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GaneshPrabuBaburaj Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GaneshPrabuBaburaj** [comment]
> @msbemba Thank you very much for the contribution and sharing this explanation. @GaneshPrabuBaburaj Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

Hi @yogkumgit , As per the ticket with MS #20721418, they confirmed this limitation is not accurate and it is needs to be corrected.

**Comment by GaneshPrabuBaburaj** [comment]
Hi @yogkumgit , As per the ticket with MS #20721418, they confirmed this limitation is not accurate and it is needs to be corrected. They also confirmed user can be part of any number of groups irrespective of group type. Have give the ticket ID FYR as well. Please let me know, if you want me to create a new issue for this again.

**Comment by msbemba** [comment]
@GaneshPrabuBaburaj NO need to create a new issue. We don't have access to the ticket, But can confirm the same with the author. I'll provide you an update shortly.

**Comment by GaneshPrabuBaburaj** [comment]
> @GaneshPrabuBaburaj NO need to create a new issue. We don't have access to the ticket, But can confirm the same with the author. I'll provide you an update shortly.

Thank you @msbemba . Waiting for your reply.!

**Comment by GaneshPrabuBaburaj** [comment]
@dariomws , I understood the changes are waiting for approval. However, Could you please provide some tentative date.

**Comment by msbemba** [comment]
@GaneshPrabuBaburaj Sorry about the delay. The approval usually takes between 1-14 days depending on the issue. We will keep you updated.

Thanks
Sri

**Comment by GaneshPrabuBaburaj** [comment]
@msbemba , Is that approved ? Hope it is more than 2 weeks.

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Do we have any response from PM. Please help. Thanks

**Comment by GaneshPrabuBaburaj** [comment]
Hi @yogkumgit  @MikePlumleyMSFT , Its almost a month, still the article is not updated. Have raised the suggestion just to ensure no one Should mislead by the incorrect information. But still for some reason this is not approved yet! Please check and close this issue. Let me know if you need any information from my side. Thanks!

**Comment by GaneshPrabuBaburaj** [comment]
OMG! Still this one s not approved and showing wrong data in the article!😐

**Comment by msbemba** [comment]
@MikePlumleyMSFT  Can we document the soft limit as 7000 as discussed with the SME?

**Comment by GaneshPrabuBaburaj** [comment]
> @MikePlumleyMSFT Can we document the soft limit as 7000 as discussed with the SME?

Hi @msbemba , Can you explain on the word soft limit. Because as per the ticket and other article , MS team mentioned there is no limit.

**Comment by msbemba** [comment]
@GaneshPrabuBaburaj We have got a confirmation from the Product group and Engineering team that the limit is 7000. A user can be a member of 7000 Groups. Author @MikePlumleyMSFT  has merged the PR and the document should be live in the next 24 hours.

Thanks
Sri

**Comment by GaneshPrabuBaburaj** [comment]
Hi @msbemba , Thanks for the explanation. Since we suggest 7000 groups as soft limit, If the user want to be part of more than 7000 groups (SharePoint), Can the SharePoint admin increase the limit? If there is no option to increase the limit by admin, will the user face some difficulty in SharePoint if it exceed the soft limit ?

**Comment by msbemba** [comment]
@GaneshPrabuBaburaj There is no option for the SharePoint admin to increase this limit. When you go beyond 7000 it can place stress on SharePoint and users/admins could face some difficultly accessing. 

We are sorry about the delay in getting this documented. We had to verify a few facts and do testing before this went live. We really appreciate your feedback, Keep providing such feedbacks.

@yogkumgit  PR has been merged and the correct limitation has been documented. Please proceed with closing this issue.

Thanks
Sri

**Comment by GaneshPrabuBaburaj** [comment]
Hi @msbemba , Appreciate your response! Thanks!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GaneshPrabuBaburaj Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
