### ISSUE TITLE
Strangely US centric wording in the datacentre paragraph

### ISSUE THREAD

**Issue by andytuke-jisc** [MicrosoftDocs/microsoft-365-docs#2384]
The paragraph

"In the Americas, all Exchange Online mailboxes are located in U.S. datacenters, with the exception of South America where datacenters in Brazil and Chile are used and in Canada where datacenters in Canada are used"

So when you say "In the Americas, all Exchange mailboxes are located in U.S datacenters", you actually mean only about 20% by land mass of the Americas, and all the remaining 80% is the exception.  While I appreciate the 365 usage per person in the United States is much higher than the rest of the 2 continents, to those of us not in the States this feels like a very odd choice of phrase

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8878304-7f4b-15c3-d2b6-8a5583930199
* Version Independent ID: 329f3b45-a087-6743-0664-e74dd9e0fc46
* Content: [Exchange Online Protection (EOP) overview - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/exchange-online-protection-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/exchange-online-protection-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/exchange-online-protection-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andytuke-jisc, perhaps the original intent was to keep everything on one line like the others? I don't suffer from that, so I made the statement longer and more clear.

Thanks for the feedback.

Closing

**Comment by andytuke-jisc** [comment]
Thank you,  there's probably not many big tech companies that have such a responsive way of handling issues with huge document libraries like this. 😁
