### ISSUE TITLE
Volume Licensing and CSP add-on availability 

### ISSUE THREAD

**Issue by miguelvidex** [MicrosoftDocs/microsoft-365-docs#2385]
Hi Team,
I would like to mention that the following sentence is not clear:
_If you bought your subscription through Volume Licensing or a CSP, you can't buy Office 365 Extra File Storage for your organization. Contact your representative or partner for help._

Because it's not true that if a customer bought his subscriptions through Volume Licensing or a CSP, he can't buy Office 365 Extra File Storage for his organization. **He can buy it**

I think that what you would like to mention is that he will not be able to buy it directly to Microsoft as described in the documentation and that he will need to buy through Volume Licensing or a CSP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@miguelvidex  Thank you for your feedback. We have updated the note in the document to reflect your feedback. This can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2403

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @miguelvidex Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
