### ISSUE TITLE
Broken hyperlinking for bulleted lists

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/microsoft-365-docs#2386]
Content after [Step 1: Complete your technical planning](https://docs.microsoft.com/en-us/microsoft-365/enterprise/sharepoint-online-onedrive-workload?view=o365-worldwide#step-1-complete-your-technical-planning) is not hyperlinking correctly. 

![image](https://user-images.githubusercontent.com/17114534/87959010-e0396c00-ca77-11ea-8b92-9bf2f8992041.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04567f90-44e2-7fe8-9d61-688adecb48fc
* Version Independent ID: 7c6675fc-948a-c26d-bfba-bde517670f87
* Content: [Deploy SharePoint and OneDrive for Microsoft 365 Enterprise - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/sharepoint-online-onedrive-workload?view=o365-worldwide#step-1-complete-your-technical-planning)
* Content Source: [microsoft-365/enterprise/sharepoint-online-onedrive-workload.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/sharepoint-online-onedrive-workload.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT

**Comment by PrasadKasireddy** [comment]
@yogkumgit  - Can I pick this, please assign it to me

**Comment by msbemba** [comment]
@milesgratz  Thank you for your feedback. We have made changes to the document via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2394

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @milesgratz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
