### ISSUE TITLE
Defender ATP information in Compatibility section

### ISSUE THREAD

**Issue by markoshea1212** [MicrosoftDocs/microsoft-365-docs#2390]
There are a couple of issues here - it should be Microsoft Defender Advanced Threat Protection, and now it is available as a standalone add-on to other SKUs, not only through Windows 10 Enterprise E5 or M365 E5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed7e43-7ec8-01f6-8cf0-6fd77519840e
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business Premium frequently asked questions  - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs?view=o365-worldwide)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@markoshea1212  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2396

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @markoshea1212 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
