### ISSUE TITLE
Any quick way to check/test the functionality on the end user side (device)?

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/microsoft-365-docs#2391]
[Enter feedback here]

Any quick way to check/test the functionality on the end user side (device)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jose-camacaro, we're looking into it.

**Comment by yogkumgit** [comment]
@chrisda  Kindly answer and help us in resolving this issue. Thanks.

**Comment by chrisda** [comment]
@jose-camacaro, the download locations for files that you can use to test Safe Documents have been added to the topic. These files are harmless, but will trigger a Safe Documents response, similar to the EICAR.TXT file for testing anti-malware/virus solutions.

Thanks for the feedback.

Closing.
