### ISSUE TITLE
Email address incorrect?

### ISSUE THREAD

**Issue by lukewegener** [MicrosoftDocs/microsoft-365-docs#2392]
In the section: https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide#register-azure-subscriptions-to-use-a-mandatory-retention-period it says to email spock@microsoft.com

Is this address valid? I am working through this process with a customer and the email bounces with 'recipient address rejected'. We've tried from a couple of different sources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide&source=docs#register-azure-subscriptions-to-use-a-mandatory-retention-period)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@lukewegener Thank you for your feedback. We are checking with the engineering team and will update you shortly.

Thanks
Sri

**Comment by lukewegener** [comment]
I have just been told that there was an issue with the spock email alias
and that it has been fixed

**Comment by msbemba** [comment]
@lukewegener Thank you. I was able to test this from my side as well and the emails are getting delivered.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @lukewegener Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
