### ISSUE TITLE
The document needs more details on MDATP Requirements

### ISSUE THREAD

**Issue by nlepagnez** [MicrosoftDocs/microsoft-365-docs#2393]
It is not very clear if Microsoft Defender ATP is a prerequisite on the workstations, or if only the Cloud version is used and if MDATP configuration is necessary.

In the article, MDATP is mentioned several times, suggesting that if the workstation does not have MDATP installed, Safe Documents cannot work. In only one small place is it mentioned that it would be MDATP Cloud that would be used.

I think we should be clearer about the prerequisites with MDATP and specify that it is the Cloud version accessible without any configuration other than the E5 license and not dependent on an agent on the workstation that is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide#how-does-microsoft-handle-your-data)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda  Kindly answer and help us in resolving this issue. Thanks.

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@nlepagnez, I think the current topic accurately describes the license requirements. If you disagree, feel free to reopen.

**Comment by netaneladar** [comment]
@chrisda I am confused myself as well. The article says that "Safe Documents sends files to the Microsoft Defender for Endpoint cloud for analysis" which sounds like the Microsoft Defender for Endpoint agent is NOT needed. Nevertheless, why not just explicitly say if the agent is or isn't required? Further, someone opened the question, so why not just answer the question explicitly instead of just saying that the requirements are already outlined? Clearly, it is not understood. 
Thank you in advance Sir

**Comment by chrisda** [comment]
@netaneladar, @nlepagnez fair enough. I updated the topic to be much more specific.

**Comment by netaneladar** [comment]
Thanks again Chris. We have all the requirements in our large tenants, but don't have Defender. It is important for us to understand the requirements before rolling out a global setting.
