### ISSUE TITLE
The mail flow comment midway through the page doesn't link to anywhere specific. Just goes to microsoft.com

### ISSUE THREAD

**Issue by aszalacinski** [MicrosoftDocs/microsoft-365-docs#2395]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc96d989-29fd-363e-82b6-0dc3807be297
* Version Independent ID: 2a7ffa92-86b1-919d-6f97-ed0df2310bcd
* Content: [Find and fix issues after adding your domain or DNS records - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/find-and-fix-issues?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/find-and-fix-issues.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/find-and-fix-issues.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@aszalacinski Thank you for your feedback. We have got the correct link updated in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2454

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @aszalacinski Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
