### ISSUE TITLE
Device onboarding section referencing the wrong portal

### ISSUE THREAD

**Issue by LouMercuri** [MicrosoftDocs/microsoft-365-docs#2402]
The instructions at https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide#onboarding-devices refer to the "Microsoft Compliance Center" settings page and provides a screen shot. This is the wrong console. It should be referencing the "Microsoft Defender Security Center" and the settings page there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @LouMercuri 
Thanks for your comment. I have reviewed the procedures and the reference to the portal is correct.

**Comment by LouMercuri** [comment]
Yep, I realised after hitting send that my tenant is not yet onboarded and so I don’t see the Settings option yet.
