### ISSUE TITLE
Video is missing

### ISSUE THREAD

**Issue by mohanse** [MicrosoftDocs/microsoft-365-docs#2405]
The following video shows how Double Key Encryption works to secure your content.

Video is missing , seeing video could not be found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by PrasadKasireddy** [comment]
Thanks for sharing feedback, I will update the correct URL

**Comment by msbemba** [comment]
@mohanse Thank you for your feedback. The Microsoft video was removed and instead, we have added another link to that via Youtube (https://youtu.be/vDWfHN_kygg) 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mohanse Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
