### ISSUE TITLE
Revised Timeline for TLS 1.0 and 1.1 deprecation in Office 365 - October 15, 2020

### ISSUE THREAD

**Issue by tcfinney** [MicrosoftDocs/microsoft-365-docs#2407]
Hello,

This [article](https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide) does not reflect the updated deprecation timeline for TLS 1.0 and 1.1 as stated in [TLS 1.0 and 1.1 deprecation for Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365?view=o365-worldwide).

Please update this article to reflect the revised timeline for deprecation of TLS 1.0 and 1.1 to October 15, 2020.

Thank you,
TC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f7e4139-a562-6b81-6584-277efc4f6103
* Version Independent ID: e812b33a-f183-8b6a-bab0-447ddab2f26f
* Content: [Preparing for TLS 1.2 in Office 365 and Office 365 GCC - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/prepare-tls-1.2-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prepare-tls-1.2-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @simonxjx
* Microsoft Alias: **v-six**

**Comment by msbemba** [comment]
@tcfinney  Thank you for your feedback. The document now updated with the correct date of October 15, 2020, as stated in  TLS 1.0 and 1.1 deprecation for Office 365. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tcfinney Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
