### ISSUE TITLE
Windows Analytics Deprecated

### ISSUE THREAD

**Issue by dustygooden** [MicrosoftDocs/microsoft-365-docs#2408]
Windows Analytics has been retired and replaced by Desktop Analytics. The section referencing Windows Analytics this should be updated to reflect the changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49affecb-7a8a-87fd-7a41-fe244dee06a6
* Version Independent ID: 57d75d53-f22e-42b7-a46c-814429f3308a
* Content: [Windows 10 Enterprise infrastructure for Microsoft 365 Enterprise - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/windows10-infrastructure?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/windows10-infrastructure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/windows10-infrastructure.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@dustygooden Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2456

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @dustygooden Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
