### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by ramuvr** [MicrosoftDocs/microsoft-365-docs#2409]
[Enter feedback here]

When running the script .\Get-AllTenantRulesAndForms.ps1 received the below error (see screenshot)
![image](https://user-images.githubusercontent.com/27629864/88187230-dcb90700-cc68-11ea-9c2f-32dff4bc15de.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d82939-8b5a-2d4c-6cc9-5a3443ee5b99
* Version Independent ID: 8d4fd954-0a92-67e8-f2fd-ca5ffaaacac2
* Content: [Detect and remediate the Outlook rules and custom forms injections attacks. - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-outlook-rules-forms-attack?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-outlook-rules-forms-attack.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-outlook-rules-forms-attack.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@ramuvr Thank you for your feedback. We tested this on our test environment and the script works without any issues. So there is no changes required in the document. I would request you to contact Microsoft from the need help section on your admin portal to take this forward.

If you find anything that needs to change int he document, Please let us know.

@yogkumgit  This can be closed as the document does not need any modification.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @ramuvr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
