### ISSUE TITLE
"a record" not "an record" 

### ISSUE THREAD

**Issue by mvg73** [MicrosoftDocs/microsoft-365-docs#2410]
[Enter feedback here]
It's "a record" not "an record" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Learn about records - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/records?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@mvg73 Hi, thanks for flagging this typo.  Now fixed.
