### ISSUE TITLE
Incorrect information regarding s/mime considerations for chromium edge?

### ISSUE THREAD

**Issue by PatrickBraam** [MicrosoftDocs/microsoft-365-docs#2411]
I'm wondering if the text is correct in that Domain Joined computers are a prerequisite, as I am successfully able to load the S/MIME extension on AAD joined devices using a Intune Administrative Template, configuring the Edge setting: Control which extensions are installed silently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e106b4-4d03-6027-39ed-711e3949aef8
* Version Independent ID: ff0ca4b3-2583-51dc-24ce-ac4cfaa12eb0
* Content: [Configure S/MIME settings - Exchange Online for Outlook on web - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@PatrickBraam Thank you for your feedback. It works on AAD joined devices as well. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2480

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @PatrickBraam Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
