### ISSUE TITLE
Conflicting 'Set-OrganizationConfig' advice

### ISSUE THREAD

**Issue by ntw2** [MicrosoftDocs/microsoft-365-docs#2413]
This assertion:

> If you run the Set-OrganizationConfig -AutoExpandingArchive command to enable auto-expanding archiving for your organization, you don't have to run the Enable-Mailbox -AutoExpandingArchive on individual mailboxes. 

Seems to conflict with this statement:

> Running the Set-OrganizationConfig cmdlet to enable auto-expanding archiving for your organization doesn't change the AutoExpandingArchiveEnabled property on user mailboxes to True.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a7c1600-c310-fb7f-7976-2025ee9256f3
* Version Independent ID: 9241081b-eabb-78a8-af86-2c0f27e7e671
* Content: [Enable unlimited archiving — Admin Help - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-unlimited-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ntw2 The point the second statement is trying to make is if you enable auto-expanding archiving for your entire org, the setting on the mailbox is ignored (in otherwords, the mailbox property isn't set to True). So if AutoExpandingArchive  is set to True for the org, it's enabled for all mailboxes, auto-expanding archiving is enabled even if the AutoExpandArchive mailbox property (Get-Mailbox | FL AutoExpandArchive) equals False. Please submit a PR with any suggested change to make this clearer.
