### ISSUE TITLE
Teams dependent services architecture diagram 

### ISSUE THREAD

**Issue by imanboukly** [MicrosoftDocs/microsoft-365-docs#2418]
Hi,
Please replace Office 365 group with Microsoft 365 group name under Teams dependent services architecture illustration diagram. Thank you, Iman Boukly

**Comment by denisebmsft** [comment]
Hello @imanboukly. Can you please tell us to which article(s) your feedback applies? This information will help us route the issue to the correct writer/team. Thanks!

**Comment by msbemba** [comment]
@imanboukly  Thank you for your feedback. Can you provide us the Article which needs to be updated?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and digging deep into it.  @imanboukly We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by imanboukly** [comment]
Hi, The article was [Teams dependent services architecture ]

**Comment by imanboukly** [comment]
The URL is https://docs.microsoft.com/en-us/microsoft-365/enterprise/teams-access-policies?view=o365-worldwide

**Comment by imanboukly** [comment]
> Hello @imanboukly. Can you please tell us to which article(s) your feedback applies? This information will help us route the issue to the correct writer/team. Thanks!

Hi, Please dont close the case the link was https://docs.microsoft.com/en-us/microsoft-365/enterprise/teams-access-policies?view=o365-worldwide

**Comment by msbemba** [comment]
@imanboukly I'm looking into this and will update you shortly.

**Comment by imanboukly** [comment]
Thank you

**Comment by msbemba** [comment]
@imanboukly Thank you for your feedback. We have edited the Media file via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2523

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @imanboukly Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
