### ISSUE TITLE
Connection limit error if script run more than a couple times

### ISSUE THREAD

**Issue by Kpapadak1** [MicrosoftDocs/microsoft-365-docs#2422]
[Enter feedback here]
The script does not disconnect from tenant after running. If you need to run the script more than a couple times you will hit a connection throttling limit. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b759021-39d7-0383-2f50-b5b813217f97
* Version Independent ID: 5f5dfeab-1160-3994-2cb8-1ca7c67e3ff2
* Content: [Use a script to add users to a hold in a Core eDiscovery case in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Kpapadak1 Thanks for the feedback. Are you hitting the connecting limit for EXO PowerShell, SPO PowerShell, or both? I'll look into adding something to the before you begin section (similar to what we have documented [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide#before-you-use-content-search).

Until then, as you probably already know, you can run Get-PSSession |  Remove-PSSession to disconnect from all EXO sessions and run Disconnect-SPOService to disconnect from SPO.
