### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by patrichard** [MicrosoftDocs/microsoft-365-docs#2424]
The doc says to give the policy a name and specify the URLs not to rewrite. But you can't enter URLs unless you turn on at least one of the features:
**On - URLs will be rewritten and checked against a list of known malicious links when user clicks on the link.**
Once that's checked, you can enter the URLs in the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac84f75-b6d9-9495-873a-8f87b90b8034
* Version Independent ID: 18369495-0e0f-e3e1-6945-0200790fd107
* Content: [Set up a custom do-not-rewrite URLs list using ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@patrichard Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2481

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @patrichard Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
