### ISSUE TITLE
Incorrect Instructions for Admin page

### ISSUE THREAD

**Issue by jesslyn-omm** [MicrosoftDocs/microsoft-365-docs#2425]
The settings under "Microsoft 365 Groups guest settings" for settings are obsolete.  The settings mentioned are no longer applicable for the Microsoft 365 admin page. 
Steps in error
To set Microsoft 365 Groups guest settings

In the Microsoft 365 admin center, in the left navigation, expand Settings.
Click Services & add-ins.
In the list, click Microsoft 365 Groups.
Ensure that the Let group members outside your organization access group content and Let group owners add people outside your organization to groups check boxes are both checked.
If you made changes, click Save changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147fb47a-99b2-f8ef-9ca6-35696d49c3fb
* Version Independent ID: b2f1b521-f231-48c2-b61f-f71bf9248d1c
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-as-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-as-team.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@jesslyn-omm Thank you for your feedback. The steps have changed and we have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2450

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jesslyn-omm Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
