### ISSUE TITLE
Not enough information

### ISSUE THREAD

**Issue by 1trevor** [MicrosoftDocs/microsoft-365-docs#2426]
This article contains steps on how to enable the feature, but does not explain at all what the feature does or how it works. This appears to be the only article on this feature, so there is effectively no documentation explaining what the feature is or does.

Does it require the endpoint is enrolled in MDATP?
When/how are documents uploaded to the "MDATP cloud"?
Where does the document need to reside to be scanned? E-mail? SharePoint? Anywhere?
What is the user experience?
Is there any reporting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us and answer this issue. Thanks

**Comment by yogkumgit** [comment]
@chrisda  Gentle reminder, Kindly answer and help us in resolving this issue. Thanks.

**Comment by chrisda** [comment]
The relevant parties who can answer these questions have been notified multiple times, and updates have been done to this topic.

Closing
