### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by LFAdmin** [MicrosoftDocs/microsoft-365-docs#2428]
This link is broken 
https://docs.microsoft.com/en-us/azure/information-protection/faqs.md#whats-the-difference-between-the-azure-information-protection-classic-and-unified-labeling-clients

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@LFAdmin Thank you for your feedback. We have fixed the link in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2448

Thanks
Sri

**Comment by LFAdmin** [comment]
Welcome.

Regards,
Prabhat Nigam | Microsoft MVP

On Jul 27, 2020, at 12:56, Sriraman M S <notifications@github.com> wrote:

﻿

@LFAdmin<https://github.com/LFAdmin> Thank you for your feedback. We have fixed the link in the document via PR##2448<https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2448>

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @LFAdmin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
