### ISSUE TITLE
Step 5: Delete items in the Recoverable Items folder does not contain proper information

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#2434]
Step 5 is not really very accurate, since the article is about deleting items from Recoverable Items folder specifically in a mailbox, the reference made to the article https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide is not really helpful.

The customer needs to know how to use New-ComplianceSearch and New-ComplianceSearchActions specifically for Recoverable Items folder in a mailbox, because that's what the main article is about "Delete items in the Recoverable Items folder of cloud-based mailboxes on hold - Admin Help".

Searching emails specifically from a certain folder (Search-Mailbox had "SearchDumpsterOnly", but the cmdlet is deprecated in Exchange Online), is described here: https://docs.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide. Please unify the content or explain the steps clearly as to how customers can use New-ComplianceSearch and New-ComplianceSearchAction to delete data only from Recoverable Items and not from the entire mailbox.

The overview of the steps would be (please refine the instructions):

1. Connect Powershell to SCC
2. Connect Powershell to EXO
3. Run in Powershell connected to EXO the script found in article https://docs.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide to get the FolderID of the specific folder under Recoverable Items (DiscoveryHolds, Deletions or Purges)
4. In the Powershell session connected to SCC, run the following:

- New-ComplianceSearch -Name "name of the search" -ExchangeLocation user@domain.com -ContentMatchQuery "FolderID:<GUID value corresponding to the folder you want to search from the mailbox>"

- Start-ComplianceSearch -Identity "name of the search"

- New-ComplianceSearchAction -SearchName "name of the search" -Purge -PurgeType HardDelete - this is just an example

Referrences:

https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide
https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide
https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps
https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearch?view=exchange-ps
https://docs.microsoft.com/en-us/powershell/module/exchange/start-compliancesearch?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the cloud mailbox on hold Recoverable Items folder - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Alex-Catalin Thanks for the feedback and the suggested solution. Using targeted collection and FolderID is a good solution to lack of "search dumpster" parameter for Content Search. I will add this to my backlog of work. I assume that you're internal Microsoft and that you have tested your proposed solution. If so, please ping me offline and follow up with your test results.
