### ISSUE TITLE
What languages are supported?

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/microsoft-365-docs#2436]
What languages/locales are supported for keyword dictionary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 196b87de-20ff-37ea-79b8-beb37a1361e0
* Version Independent ID: d3aa9f91-0cec-b9df-6fc7-415242393e3f
* Content: [Create a keyword dictionary - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-keyword-dictionary?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-keyword-dictionary.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-keyword-dictionary.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@sleuthold - thanks for asking, I am checking with the engineering team

**Comment by msbemba** [comment]
@SLeuthold Thank you for your feedback. Keyword dictionaries support up to 100,000 terms per dictionary and support any language. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2492

Thanks
Sri

**Comment by SLeuthold** [comment]
@msbemba @chrfox What languages are supported was the original ask. Is there a list of languages supported somewhere?

**Comment by msbemba** [comment]
@SLeuthold  I don't see a list of languages mentioned anywhere. I will wait for @chrfox to see if he can get that. But from my last interaction and testing, it supports all languages.

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrfox Please merge this PR. Thanks.

**Comment by chrfox** [comment]
I am not aware of any language restrictions.  I have queried engineering and will update this topic as necessary

**Comment by SLeuthold** [comment]
@chrfox thank you. I'll watch this thread. I see it is marked as closed, is that intentional?
