### ISSUE TITLE
Change on premises

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/microsoft-365-docs#2437]
Hi folks,

can we change  "on premises" to on-premises please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a7c1600-c310-fb7f-7976-2025ee9256f3
* Version Independent ID: 9241081b-eabb-78a8-af86-2c0f27e7e671
* Content: [Enable unlimited archiving — Admin Help - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-unlimited-archiving?view=o365-worldwide#enable-auto-expanding-archiving-for-specific-users)
* Content Source: [microsoft-365/compliance/enable-unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@r-milne Thanks for heads up. Next time, please fix typos like this by submitting a pull request. Here's how: https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-quick-update?branch=master
