### ISSUE TITLE
Exclusion list for Targeted Release

### ISSUE THREAD

**Issue by mcantin** [MicrosoftDocs/microsoft-365-docs#2444]
If Microsoft Teams is excluded, can we add that to the first note, and/or be more specific to which services targeted release affects? This article was a little confusing since Microsoft Teams and SharePoint Online are joined at the hip.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd43f78a-7c74-5c56-c1f0-24deb342455f
* Version Independent ID: f7ed9828-2580-1b50-d126-003d222abb5e
* Content: [Set up the Standard or Targeted release options - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?redirectSourcePath=%252fen-us%252foffice%252f3b3adfa4-1777-4ff0-b606-fb8732101f47&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/release-options-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/release-options-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@mcantin Thank you for your feedback. We have moved the Important note to the top of the page and added teams to the exclusion list. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2490

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @mcantin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
