### ISSUE TITLE
The warning is confusing.  

### ISSUE THREAD

**Issue by edwardclau** [MicrosoftDocs/microsoft-365-docs#2445]
Your warning regarding setting passwords to never expire is confusing.  I believe you mean that if you set a password to never expire then change it back to "none" or a number of days - the password age count still remains at the place it was when the password policy was set to not expire.  NOT the password set to never expire - expires in 90 days as it appears to read.  The wording isn't clear.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52c6916-7e79-9a9c-b7a6-47041ddb81e3
* Version Independent ID: 43c9b873-d354-d814-3065-1e8832361b86
* Content: [Set an individual user's password to never expire - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@edwardclau Thank you for your feedback. I'll explain the warning 

Change made on 07/29/2020 for Org Wide to 90 days(All users)
Change made on 08/29/2020 for a user "John Smith" to never expire

John's passwords will expire on 10/29/2020, 90 days from the date when the org-wide setting was updated.


1) In the meantime, if John changed his passwords, then the passwords will never expire from the date when the password was updated.
2)If this never expire was set to the entire organization, the same thing applies whereas the users password will expire once after 90 days (unless the password was changed).  But if there were new users created after the password policy was applied to never expire then there will be no password expiration.

Hope this helps! Let me know if you think a change is required in the document.

Thanks
Sri

**Comment by msbemba** [comment]
@edwardclau  Hope the confusion is cleared now. @yogkumgit  There is no requirement for the document to modified, So this can be closed for now.

Thanks
Sri
