### ISSUE TITLE
The ENS certificate is expired since April 23 2020

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#2446]
The certificate available for download here: https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-ens-spain?view=o365-worldwide#azure and here https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-ens-spain?view=o365-worldwide#office-365 has expired.

The certificate comes in the form of a PDF file, it's not an SSL certificate. I believe the document should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3688d6a0-6c3b-3df6-d46a-9f77faac7863
* Version Independent ID: 224293df-fb45-f4d7-a334-60c211ea090e
* Content: [Spain Esquema Nacional de Seguridad (ENS) High-Level Security Measures - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-ens-spain?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-ENS-Spain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-ENS-Spain.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Alex-Catalin Thank you for your feedback. We are checking this with the author and will update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@robmazz The certificates available for reference in document https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-ens-spain?view=o365-worldwide . The Certificates available via https://aka.ms/AzureNationalSecurityFrameworkENSCertificate and https://aka.ms/Office365NationalSecurityFrameworkENSCertificate are expired effective April 2020. 

Please share the URL for the updated certificate so that the document can be updated.

Thanks
Sri

**Comment by robmazz** [comment]
@Alex-Catalin  - thanks for the feedback. The Certificate PDFs on the Service Trust Portal (https://servicetrust.microsoft.com/ViewPage/MSComplianceGuide?command=Download&downloadType=Document&downloadId=4e52ba52-d780-4fe2-a0ec-1cefe39af3ad&docTab=4ce99610-c9c0-11e7-8c2c-f908a777fa4d_ENS_Audit_Reports_and_Certificates) have been updated (on 7/20/20) and the certificates are good through 7/30/22. These are not meant to be SSL certs, but certificate of conformity/compliance.
