### ISSUE TITLE
GCC Availability for Report Message Add-In

### ISSUE THREAD

**Issue by jbrysonMSFT** [MicrosoftDocs/microsoft-365-docs#2447]
With the updated "user submission" policy in GCC, the report message add-in now works.  Verified in a test and customer tenant.  The submission policy disables the option to send the reported message to Microsoft.

> The Report Message add-in is currently not available for:
> 
> Mailboxes in on-premises Exchange organizations
> GCC, GCC HIGH, or DoD subscriptions

This screen shot is from a GCC (demo) tenant.

![Report-Message-Add-In_GCC](https://user-images.githubusercontent.com/54324805/88568518-ba274500-cffe-11ea-8505-327a0b161901.png)

![GCC-usersubmission-reportmessage](https://user-images.githubusercontent.com/54324805/88571499-5fdcb300-d003-11ea-93c1-6c839384b08c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide#what-do-you-need-to-know-before-you-begin)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jbrysonMSFT, fixed.

Thanks for the feedback.

Closing
