### ISSUE TITLE
It's not a crime to be blessed by God Almighty 

### ISSUE THREAD

**Issue by Dongiftedgh** [MicrosoftDocs/microsoft-365-docs#2463]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5caf38e-e511-0763-55c8-0f54dcc6abee
* Version Independent ID: 05e41f24-433e-7535-8434-b4d51995ae0c
* Content: [What is a domain? - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/what-is-a-domain?redirectSourcePath=%252farticle%252fc33d1ba6-077c-4cea-be04-cfffbe3f3ed8&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/what-is-a-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/what-is-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by Dongiftedgh** [comment]
Hello

**Comment by msbemba** [comment]
@Dongiftedgh  Thank you for your feedback. Could you please provide us more information on what needs to be updated in the document or if you have any questions?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and digging deep into it.  @Dongiftedgh We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
