### ISSUE TITLE
Docs refer to Intune Azure Portal experience that is being retired on August 1, 2020.

### ISSUE THREAD

**Issue by jseerden** [MicrosoftDocs/microsoft-365-docs#2466]
Referring to: "1. Verify MDM Authority in Intune
Go to portal.azure.com and on the top of the page search for Intune. On the Microsoft Intune page, select Device enrollment, and on the Overview page make sure MDM authority is Intune.

If MDM authority is None, click the MDM authority to set it to Intune.
If MDM authority is Microsoft Office 365, go to Devices > Enroll devices and use the Add MDM authority dialog on the right to add Intune MDM authority (the Add MDM Authority dialog is only available if the MDM Authority is set to Microsoft Office 365)."

On August 1, 2020, the current Intune Azure Portal experience will be retired. I can't seem to find the equivalent in the Microsoft Endpoint Manager Admin Center. How to change the MDM authority when the Intune Azure Portal experience is retired?

The current URL where the MDM authority can be changed, for example when this is set to Microsoft Office 365 instead of Microsoft Intune, is https://portal.azure.com/#blade/Microsoft_Intune_Enrollment/EnrollmentMenu/overview

It works by replacing portal.azure.com with endpoint.microsoft.com in the deep-link, however, this page is (AFAIK) not available via the Endpoint Manager GUI.

--- EDIT---
Added screenshot for reference:

![image](https://user-images.githubusercontent.com/20967759/88648924-bca1a180-d0c7-11ea-88a3-74b537dffe7a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fe27259-1194-cfca-4225-1d2db4331152
* Version Independent ID: d86eaa73-b12d-f8a0-7b64-961da7322108
* Content: [Enable domain-joined Windows 10 devices to be managed by Microsoft 365 for business - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/manage-windows-devices?view=o365-worldwide)
* Content Source: [microsoft-365/business/manage-windows-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/manage-windows-devices.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@jseerden Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2510

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @jseerden Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
