### ISSUE TITLE
max number of entries seems to be 500

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/microsoft-365-docs#2467]
The custom list of blocked URLs seems to have a limit of 500. This limit is not yet mentioned on the page, can you please add?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393afc64-7cf4-1a2c-33b5-8cb818f8c7fd
* Version Independent ID: 82fbfb15-1e17-7bfc-9a6b-bfff3e97a0bb
* Content: [Set up a custom blocked URLs list using ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-blocked-urls-list-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-blocked-urls-list-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-blocked-urls-list-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@sebhe Thank you for your feedback. We have added a note to the document to mention this fact. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2493

Thanks
Sri

**Comment by yogkumgit** [comment]
@ Thank you very much for the contribution and updating the documentation with PR. @sebhe Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
