### ISSUE TITLE
Content search reference page - feedback column on right hand side 

### ISSUE THREAD

**Issue by chloegilbert** [MicrosoftDocs/microsoft-365-docs#2468]
On this page the feedback column on the right hand side flows over the content in the middle column and you cant close the feedback tab to see the text. Even zooming out on the page just makes the right hand column wider. 
Happens in Chrome and in Edge. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/keyword-queries-and-search-conditions?redirectSourcePath=%252fen-us%252farticle%252fKeyword-queries-and-search-conditions-for-Content-Search-c4639c2e-7223-4302-8e0d-b6e10f1c3be3&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@chloegilbert Thanks for feedback, but not sure I understand, and can't seem to repro. Some of the tables in this topic have horizontal scroll bars, which is a result of column-width do to non-breaking lines. But not sure if that is what you're referring to. Maybe you could attach a screenshot, but I may not be about to do much if its related to the browser chrome.

**Comment by yogkumgit** [comment]
@markjjo  Thank you very much for digging deep into it.  @chloegilbert We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
