### ISSUE TITLE
Link leads to a 404 error.

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/microsoft-365-docs#2469]
The link at the bottom of the page, "Use Centralized Deployment PowerShell cmdlets to manage add-ins" leads to "404 - Page not found"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62dfa25-e420-38e4-ff47-05cca62d14ec
* Version Independent ID: 5ea03ce0-38b9-e005-a430-e98442e2ec83
* Content: [Deploy add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@GitRomney Thank you for your feedback. We have corrected the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2494

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @GitRomney Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
