### ISSUE TITLE
Required Build

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2471]
[Enter feedback here]
what build of Windows 10 is required? please add this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 820cb23f-f33d-241d-5ce2-1d824bcd3747
* Version Independent ID: 36d24f60-27b6-f2c1-ccda-1b49a1d4f073
* Content: [Learn about Microsoft 365 Endpoint data loss prevention (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-learn-about?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have added the minimum required build (Version 10.0.17134.1) to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2497

Thanks
Sri

**Comment by chrfox** [comment]
its build 1809  and up, not sure 10.0.17134.1 is correct, this change was not merged into the documentation

**Comment by msbemba** [comment]
@DeanGross  The information has been updated in the Getting started document - https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide

Hope this helps!

@yogkumgit  We can close this issue.

Thanks
Sri
