### ISSUE TITLE
Step 3 to enroll in a Trial does not work.

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/microsoft-365-docs#2478]
Step 3 from this doc for selecting a Trial is not an option, at least in my tenant. I only have a Buy option:

On the next page, select Get free trial, which gives you 25 user licenses for a one-month term, or you can Buy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3893a86c-51f0-48cf-ff7c-9b4a0eff6ccc
* Version Independent ID: 1918a9ed-1461-5bad-217f-9ccd3b799a5c
* Content: [Try or buy a Microsoft 365 subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/try-or-buy-microsoft-365?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/try-or-buy-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/try-or-buy-microsoft-365.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@jwojan Thank you for your feedback. I tested this and See we no longer have this option from o365 E3, But Trial is available for M365 E3 and E5. I have also made these changes on the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2495

**Comment by msbemba** [comment]
@yogkumgit We can proceed with closure as @cmcatee-MSFT has merged the PR

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @jwojan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
