### ISSUE TITLE
Give an example for creating DEP in SPO/OneDrive Geo

### ISSUE THREAD

**Issue by andypituch** [MicrosoftDocs/microsoft-365-docs#2479]
Hello!

The documentation for Register-SPODataEncryptionPolicy does not list an example nor does this documentation. The instructions for a DEP in Exchange online provided an example/sample values and I'd like to see the same for SPO.

SPO is different since it asks for 3 pieces of information versus using the URI for the key like it does in EXO...  So displaying how that breaks down would be helpful to have in the documentation. I'd recommend having a sample in the cmdlet reference for Register-SPODataEncryptionPolicy as well but at minimum it should be here just like it is for EXO.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@andypituch  Thank you for your feedback. We have added an example to this document via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2509 and also added an example to Register-SPODataEncryptionPolicy the via PR#https://github.com/MicrosoftDocs/office-docs-powershell/pull/6252

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andypituch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
