### ISSUE TITLE
Enabling Customer Lockbox for Office 365 from Graph API or Powershell

### ISSUE THREAD

**Issue by egdeeptha** [MicrosoftDocs/microsoft-365-docs#2483]
Hi,
Is it possible to enable the customer lockbox feature through Graph API or through Powershell. ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@egdeeptha Thank you for your feedback. Enabling Customer lockbox is available only on the GUI as mentioned the document. However, Approve/Deny can be done via Powershell. I have added a note to the doc via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2496

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @egdeeptha Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
