### ISSUE TITLE
Minimum required version (Windows Desktop)

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#2485]
I don't get these minimum required versions for Windows Desktop, e.g. Word/Excel/PowerPoint.
The table lists "1910+" as a minimum level for even the most basic features like "Manually apply, change, or remove label".
I (my enterprise) have Office 365 ProPlus, 1908 (build 11929.20904). But no issue here - things work as expected.
Or is it because I have installed the AIP Unified Labeling Client? Does "1910+" mean that from that version upwards the AIP UL client isn't required anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Use sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#support-for-sensitivity-label-capabilities-in-apps)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@andrePKI  Yes, the minimum versions are for built-in labeling and not relevant if you're using the Azure Information Protection unified labeling client.  See the section https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#office-built-in-labeling-client-and-the-azure-information-protection-client 

Even if you have the minimum version for Windows, you might still want to continue using the AIP client - the section referenced has more info about this.
