### ISSUE TITLE
Great article! Please update its title.

### ISSUE THREAD

**Issue by tfurstms** [MicrosoftDocs/microsoft-365-docs#2487]
Thanks so much for the content on this page and keeping it up to date! My ask is if you can update the title of the page to include the word/phase "deprovision", "remove" or "delete" users.  I am asking because Bing searches for these words did not find this article.  Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@tfurstms Thank you for your feedback. We have added a word Delete to the title via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2529 . Once the author approves the same will be published.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @tfurstms Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
