### ISSUE TITLE
Document missing information on excluding SharePoint sites from Retention Policy

### ISSUE THREAD

**Issue by Murdos-AU** [MicrosoftDocs/microsoft-365-docs#2498]
There is the option in Retention Policy under SharePoint to exclude specified sites from the policy. This capability is not mentioned or detailed in this document. Getting this feature to work is problematic at best.

Please create some detailed instructions on how to exclude a SharePoint site from the policy. Also include information and steps on how to investigate known errors (eg when exclusions don't appear to apply)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Murdos-AU  Thank you for your feedback.  This page focuses to how retention works for SharePoint and OneDrive.  For instructions to configure a retention policy, see https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide.

Specifically for configuring the SharePoint and OneDrive locations, see https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide#configuration-information-for-sharepoint-sites-and-onedrive-accounts

I'm not aware of problems for excluding sites - it should be a case of selecting "Exclude sites" and then providing the site URL, which is validated when you complete the wizard.  If you are excluding a site and items are still be retained/deleted in that site, and these items are not subject to another retention policy or retention label, I suggest you open a ticket with Support for investigation.  If I hear of any known issues, I'll update this thread.
