### ISSUE TITLE
GDPR Blueprint Implementation

### ISSUE THREAD

**Issue by Jothi3125** [MicrosoftDocs/microsoft-365-docs#250]
For some of the GDPR controls, the Blueprint Reference Architecture is marked as NO. 
What are the scope of the Azure Resources that can be used to implement those controls? What will be the Service Configuration Details for the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d7d882-f847-ac05-04b5-ebedbbe6c8d4
* Version Independent ID: 81246f1e-10b9-de66-3882-24e3a5e044b6
* Content: [Microsoft 365 GDPR action plan — Top priorities for your first 30 days, 90 days, and beyond](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-action-plan)
* Content Source: [microsoft-365/compliance/gdpr-action-plan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-action-plan.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by robmazz** [comment]
@Jothi3125 - thanks for the feedback, I'll get this over to the Enterprise content team for clarification.

**Comment by Jothi3125** [comment]
Is there any update on this??

**Comment by BrendaCarter** [comment]
Hi @Jothi3125, can you provide more information about what you are looking for? Which products? What level of detail? Thank you!

**Comment by Jothi3125** [comment]
There are some GDPR controls for which the Blueprint says, the controls are not implemented yet. So, wanted to know which Azure Resources are to be focussed in order to achieve the compliance controls. 

Following is the link for the  GDPR CRM, which I refered. 
https://aka.ms/gdprCRM

**Comment by BrendaCarter** [comment]
Working on chasing this request down . . . It might take a day or two.

**Comment by Jothi3125** [comment]
Is there any update on this?

**Comment by BrendaCarter** [comment]
Hello, we're still tracking down an answer. Thank you for checking in again!

**Comment by Jothi3125** [comment]
Is there any update regarding the same?

**Comment by BrendaCarter** [comment]
Hi Jothi3215, thank you for checking in. Last week the Azure engineering team did confirm there is a discrepancy in the blueprints. They are working to fix this.

**Comment by BrendaCarter** [comment]
Thank you for your question.  We are currently reviewing the GDPR blueprint.  While this review is being undertaken, we encourage you to peruse our other GDPR documentation on Trust Center. https://www.microsoft.com/en-us/trustcenter/privacy/gdpr/gdpr-overview

**Comment by mypil** [comment]
@BrendaCarter - We would like to follow up on this. Do you have any updates? Thanks.

**Comment by BrendaCarter** [comment]
Hello, we are still working on the updates. Thank you for checking in!

**Comment by mypil** [comment]
@BrendaCarter - Do you any updates on the progress of this? Thank you.

**Comment by BrendaCarter** [comment]
Greetings, I believe the content in question has been removed. We recommend using the Trust Center instead. https://www.microsoft.com/en-us/trustcenter/privacy/gdpr/accountability-documentation

**Comment by mypil** [comment]
@Jothi3125 - Thank you for submitting feedback.

From our understanding, the issue has been answered by BrendaCarter. If you feel it hasn't been resolved please re-open this issue.

Thank you for engaging with the community here for the docs.
