### ISSUE TITLE
Feature not working

### ISSUE THREAD

**Issue by joyd86** [MicrosoftDocs/microsoft-365-docs#2500]
Please confirm if the feature mentioned in the document relates the Featured ID: 63831 which is still in development or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding, Automatic forwarding, 5.7.520 Access Denied, disable external forwarding, Your administrator has disabled external forwarding, outbound anti-spam policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@joyd86 Thank you for your feedback. I tested this feature and this is still in the development stage and will be rolled out in a phased manner. We have added a note on the document "Disabling automatic forwarding to external addresses in Office 365 is being rolled out in phases with details communicated via Message Center posts."

Hopefully, you can start using this feature once it is rolled out to your tenant.

@yogkumgit There is no changes required in the document as such, We can close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @joyd86 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
