### ISSUE TITLE
Please clarify behaviour of safe links for email messages

### ISSUE THREAD

**Issue by Moodjbow** [MicrosoftDocs/microsoft-365-docs#2501]
Dear Microsoft,

The tenor of your article supposes that the entire organization policy (Step 2) defines the baseline security, and the specific email policies (Step 3) define exceptions, i.e. relaxed rules.
But the "Default" policy explicitly states under "Settings that apply to content except email", that the below settings (use safe links in O 365 applications; do not track; do not let user click through safe links) "don't apply to email messages".
My reading is that I should then create in Step 3 a policy for all users to enable the above mentioned three settings explicitly for email messages. But this contradicts with the exceptions logic that you describe.
Please specify more precisely the safe links default and specific users' policies scope and behavior.
Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1541da6f-af9a-05d5-fa34-b1a5df61424f
* Version Independent ID: 88e111ed-67f7-41bc-d823-863ee7ea2a2e
* Content: [Set up Office 365 ATP Safe Links policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Moodjbow Thank you for your feedback. The steps mentioned in step 3 can be used for all employees if you want a custom policy as the default policy has fewer options w.r.t email. I have created a PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2542 which will be reviewed by the author and approved if they are found True.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Moodjbow 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
