### ISSUE TITLE
Office 365

### ISSUE THREAD

**Issue by Gmaup86** [MicrosoftDocs/microsoft-365-docs#251]
some of my machines are now running 1803 or 1809 Version of Windows 10 Pro. I was once able to do the above steps no problem and it would allow me to sign into a Microsoft account. As of January 4th 2019 when doing above steps I now get an error stating that it could not register my device with the organization, did something get updated with Microsoft that you now have to buy licensing to do above steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8e657e-2aa7-230d-0d9d-675c0200ac18
* Version Independent ID: 2028f003-2624-2bd3-34ea-6022d495e2c6
* Content: [Set up Windows devices for Microsoft 365 Business users](https://docs.microsoft.com/en-us/microsoft-365/business/set-up-windows-devices)
* Content Source: [microsoft-365/business/set-up-windows-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/set-up-windows-devices.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@Gmaup86  can you expand on your scenario here please? I am not sure I completely understand. Are you saying that the user who is registering with Azure AD does not have a license to Microsoft 365 Business or some other Office 365 for business or EDU subscription? I do believe a license is required.

**Comment by Gmaup86** [comment]
I will provide you with a step by step...

I will create a new user in the microsoft admin. I will assign a office 365
business premium license or an E3 license. once that is all done I will
either set up a brand new laptop. when setting up the laptop I get a prompt
to either sign in as a microsoft user and or sign in with a local account.
I try and sign in as this new created user in the admin that has licensing
for office 365. but I always get an error message. If I create a local
account and then go to setting work or school account and try signing in
with the microsoft account I still get an error message that does not allow
me to sign into my organizations network. For the past two or three months
I have been able to log in either of these ways as the new created user but
since January 4th something seems to have changed on Microsoft's side. the
frusterating thing is that Not One Single person from Microsoft can give me
an answer as to of what happened and or a resolution. pretty disappointing.

let me know if you require any more information. or want to remote into a
machine and see what is happening.

**Comment by Sirkkuw** [comment]
I assume you have tried support based on your frustration? I am following up with product team with the extra information you provided to see if they can help me dig up info.

**Comment by jurion** [comment]
Same situation here. Setting up a new Surface Pro for an user in our  organization, impossible to complete installation of Windows 10 when selecting "Organization". Stuck after authentification and impossible to continue. We are forced to setup local accounts manually for users. This problem did not exist 3-4 months ago. Very frustrating.

**Comment by Sirkkuw** [comment]
@jurion and @Gmaup86 This is what I got from support at work:
If this person is an admin, they should be able to use the **Need Help** widget at admin.microsoft.com. The support team can escalate to the product team after basic troubleshooting.  That’s the recommended route since the case will have the information we need to troubleshoot further. 

Alternatively, you can ask them for their support ticket reference number. That wouldn’t be PII (personally identifiable info), and we could cross-reference the information to check what’s going on. 
I will also forward @jurion your comment to them.

**Comment by Gmaup86** [comment]
Soo I have actually gotten a little further with a Microsoft team memeber.
They are actually having a management group setup a co-existence between
0365 and intune. will not require any extra licensing. It sounds like it is
on the back end of their servers that creates this realationship. I will
let know if this fixes the issue.

thank you!

**Comment by jurion** [comment]
Thank you for additional information.

After a reboot and UEFI auto update, we now getting an error message complaining about mobile device management authority.

I will try to follow this article https://docs.microsoft.com/fr-fr/intune/mdm-authority-set
Yury


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jurion** [comment]
Solved problem for our case. 
We hade InTune for trial period. After trial ended, we decided to not use it, but did not restored default MDM manager. 
Doing so here https://portal.office.com/EAdmin/Device/IntuneInventory.aspx permitted to enroll device and setup went without problems

**Comment by Sirkkuw** [comment]
Ah - so you actually do not have Microsoft 365 Business license?

**Comment by jurion** [comment]
@Sirkkuw, yes we do : some of them are Office 365 Business Essentials, but most Office 365 Business Premium

**Comment by Sirkkuw** [comment]
I actually meant the specific license for Microsoft 365 Business, not Office 365 Business Premium. The topic in question (That the issue is attached to) is specific to Microsoft 365 Business. Still this is interesting information. You are saying that you were able to set up Win 10 for Office 365 BP also, and due to not having Intune set up (trial expired) etc. you were unable to.
Anyway- I am glad this got resolved.
