### ISSUE TITLE
MFA doc improvements

### ISSUE THREAD

**Issue by jseerden** [MicrosoftDocs/microsoft-365-docs#2516]
Steps described in https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#1-set-up-multi-factor-authentication describe enabling ["legacy per person MFA"](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#turn-off-legacy-per-person-mfa)

MFA for individual users, which is also known as "Legacy per person MFA" is also the "not recommended" option, described here: https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/multi-factor-authentication-microsoft-365?view=o365-worldwide#mfa-for-an-individual-user-account-not-recommended

Microsoft 365 Business Premium now includes Azure AD Premium P1. For this license type, the steps need to describe the use of Conditional Access policies to require MFA for user accounts based on group membership, apps, or other criteria, instead of using a legacy and non-recommended way of configuring it.

Additionally, the different docs pages describe the same solution, but named differently, which confuse the readers. For example:

- [MFA for an individual user account](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/multi-factor-authentication-microsoft-365?view=o365-worldwide#mfa-for-an-individual-user-account-not-recommended)
- [Per-user account setting (not recommended)](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/multi-factor-authentication-microsoft-365?view=o365-worldwide#using-these-methods-together)
- [Legacy per person MFA](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/multi-factor-authentication-microsoft-365?view=o365-worldwide#using-these-methods-together)

All describe the same solution. Please give it a single name and stick to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6041d7c1-58b2-84db-32b8-928d2efb9319
* Version Independent ID: 004304b1-8e37-95e8-5967-b201176f2b5c
* Content: [Top 10 ways to secure Microsoft 365 for business plans - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@jseerden Thank you for your feedback. We have made changes to the wordings (Legacy Per person MFA) via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2531

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jseerden Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
