### ISSUE TITLE
FoxIt PDF Reader link not home *kinda*

### ISSUE THREAD

**Issue by bigttys0** [MicrosoftDocs/microsoft-365-docs#2521]
FoxIt PDF Reader link not home *kinda*.  When I say kinda, I mean the link to download is there but what's linked on MS is not the direct link.
Here's the direct link - https://www.foxitsoftware.com/downloads/#Foxit-PhantomPDF-Business/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da662e1-5ae5-7760-1321-26cd2bab997a
* Version Independent ID: 60319761-1406-6c06-1620-e1a484468879
* Content: [SharePoint-Compatible PDF readers that support Microsoft Information Rights Management services - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@bigttys0 Thank you for your feedback. We have made changes to the document by fixing the broken links. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2527

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @bigttys0 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
