### ISSUE TITLE
Broken link in Excel sheet

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#2524]
The downloadable Excel workbook (in the green box) that generates the information barriers PowerShell has a broken documentation link for "Attributes for information barrier policies". 

Thanks for the spreadsheet - it's very helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@EricaToelle Thank you for your feedback. We have created fix this excel file and waiting for it to go live once the author approves. Related PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2532

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @EricaToelle Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
