### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by mdcaddic** [MicrosoftDocs/microsoft-365-docs#2525]
Last link on the page (https://portal.azure.com/#blade/Microsoft_Intune_DeviceSettings/ExtensionLandingBlade/overview) no longer exists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87804d7-c76b-509d-eaa0-18b91b0563bd
* Version Independent ID: 7dc288f3-939a-590b-fe8b-31a266795fa3
* Content: [Microsoft security portals and admin centers - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/portals?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/portals.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/portals.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by msbemba** [comment]
@mdcaddic Thank you for your feedback. We have made changes to the document to fix the broken link via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2526

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @mdcaddic Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
