### ISSUE TITLE
unable to find windows 10 upgrade card

### ISSUE THREAD

**Issue by rayjgraham** [MicrosoftDocs/microsoft-365-docs#253]
Sirkku, Please provide detail on where within Microsoft admin center to find the windows 10 upgrade card. thanks, ray

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d66a7a3-2230-d907-5ff3-b3f7ed8c166a
* Version Independent ID: e437b87d-0845-bb6f-3b0b-8d9fd2b3013a
* Content: [Upgrade Windows devices to Windows Pro Creators Update](https://docs.microsoft.com/en-us/microsoft-365/business/upgrade-to-windows-pro-creators-update)
* Content Source: [microsoft-365/business/upgrade-to-windows-pro-creators-update.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/upgrade-to-windows-pro-creators-update.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
Hi Ray,
 I am not sure what happened to it and I am following up on this, But you can still find it, if in the admin center you flip off the preview mode, and on the home page click the big + sign to add a card, and you can find it in the list. I will update the topic as soon as I find out what happened to it in the Preview view.
