### ISSUE TITLE
What permission do you need to view the DLP policy details ?  Security Reader does not seem to be enough.

### ISSUE THREAD

**Issue by julesb2018** [MicrosoftDocs/microsoft-365-docs#2538]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36344d-67bf-68cb-5004-9ac6f27ebf51
* Version Independent ID: 89a7d7e7-c643-eb06-d844-b97b80633b68
* Content: [Create, test, and tune a DLP policy - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-test-tune-dlp-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@julesb2018 Thank you for your feedback. The permission to view the DLP policy is available only for tenant Admin. However, it can be managed using a compliance management role. I have added instructions on how to manage permissions to the document and can be tracked via# PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2554

Thanks
Sri

**Comment by chrfox** [comment]
updated

**Comment by julesb2018** [comment]
Thanks for the update - do you know when this will be published ?  Still seems to be older version - https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy?view=o365-worldwide
