### ISSUE TITLE
Password History

### ISSUE THREAD

**Issue by Chad-Campus** [MicrosoftDocs/microsoft-365-docs#2539]
Says
Prevent last password from being used again
If you want to prevent your users from recycling old passwords, you can do so in Azure AD. See Enforce password history.

But that link takes you to a page on how to do it in On-Prem AD not Azure AD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Chad-Campus Thank you for your feedback. We have modified the document to add Azure Ad information. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2552

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @Chad-Campus Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
