### ISSUE TITLE
Get-AzureADDirectorySetting

### ISSUE THREAD

**Issue by DXL88** [MicrosoftDocs/microsoft-365-docs#2544]
Hi,

The command "(Get-AzureADDirectorySetting -Id $settingsObjectID).Values" appears not correct, because cmdlet Get-AzureADDirectorySetting doesn't have -Id option, it has -ObjectId instead.

Regards
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e935bd03-8b2a-2271-b886-5643f5c7ea51
* Version Independent ID: 82a7b468-c1b6-ac74-3600-e96f274bbe89
* Content: [Manage who can create groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-creation-of-groups?redirectSourcePath=%252farticle%252fmanage-who-can-create-office-365-groups-4c46c8cb-17d0-44b5-9776-005fced8e618&view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@DXL88 Thank you for your feedback. We tested it and the cmdlet seems to be right.
![image](https://user-images.githubusercontent.com/45987684/89561811-ad90c100-d836-11ea-98fd-88259e07ad8b.png)

For more information on how to use this command, Please see - https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectorysetting?view=azureadps-2.0-preview

Hope this Helps!

@yogkumgit As such, there are no changes required in the document. So we can proceed with closing this.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @DXL88 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DXL88** [comment]
Hi Sriraman,

Can you run "Get-AzureADDirectorySetting -Id $settingsObjectID"?

The issue I raised is not about cmdlet Get-AzureADDirectorySetting, it's about the -Id option which is not available (at least not available under tap completion)

From what I can see "Get-AzureADDirectorySetting -Id $settingsObjectID" is not working.

Regards
David
________________________________

**Comment by DXL88** [comment]
Hi guys,

I raised the issue when I saw it, but you just closed it without paying attention to the issue.

Disappointed to say the least.

David

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by msbemba** [comment]
@DXL88 I'm sorry about that. The cmdlet works without any issues. You can see the same from the below screenshot. 

![image](https://user-images.githubusercontent.com/45987684/89650244-c43f2280-d8df-11ea-8c89-c91e3f2c6844.png)


If you are trying to run "Get-AzureADDirectorySetting -Id $settingsObjectID" without assigning value to $settingsobjectid it will not work. So use the script as-is.

Hope this helps!

Thanks
Sri

**Comment by DXL88** [comment]
Hi Sri,

The issue I see is that the cmdlet does not accept -Id as an option.

Regards

David

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by msbemba** [comment]
@DXL88 Thank you for the response, David. The cmdlet does accept -id as a parameter.

![image](https://user-images.githubusercontent.com/45987684/89692107-697de900-d928-11ea-821e-64ab8adbb195.png)

![image](https://user-images.githubusercontent.com/45987684/89692125-77cc0500-d928-11ea-9c86-8a2982050719.png)

If the above script does not work for you and you think there are changes needed in the document please let me know with screenshots of what works/does not work and changes that you think are needed in the document.

Thanks
Sri
