### ISSUE TITLE
Network settings for Azure Key Vault.

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#2545]
When Azure Key Vault is created you need to select from which network locations it will be available:

1. Public networks
2. Public networks (selected IP)
3. Private networks

Which setting should be used for Customer Key? Can private network be used in such case? If not and we want to avoid  allowing access from all IPs what IPs need to be added to allow Office 365 access the Key Vault?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide#complete-tasks-in-azure-key-vault-and-microsoft-fasttrack-for-customer-key)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us and answer this issue. Thanks

**Comment by yogkumgit** [comment]
@KCCross  Gentle reminder, Kindly answer and help us in resolving this issue. Thanks.

**Comment by KCCross** [comment]
Forwarding to product team. I don't know of any limitations.

**Comment by tabriggs** [comment]
@KCCross - I'd probably work with Brijesh Desai on AKV network settings. I have no history configuring Key Vault settings for Customer Key. Sumedh Barde might also be able to opine on best practices.

**Comment by KCCross** [comment]
Yes, Brijesh is the person to ask for this information. Brijesh, please review this issue and make recommendations for updates.

**Comment by KCCross** [comment]
Adding kelley vice for network discussion

**Comment by brdesai** [comment]
AKV access to EXO and SPO is granted by the customer by configuring Access Policy on AKV. The customer grants explicit access to EXO or SPO ServicePrincipal to perform get/wrap/unwrap operations.

Key Vault Auth options are described here: https://docs.microsoft.com/en-us/azure/key-vault/general/secure-your-key-vault#key-vault-authentication-options. Customer Key uses the application-only method for EXO and SPO to access the keys.

So it is up to the customer how they want to restrict access to their AKVs. Customer Key would work as long as the EXO / SPO applications (ServincePrincipal) are granted explicit access to perform get/wrap/unwrap operations on those AKVs.

**Comment by Larryngolog** [comment]
Hi @brdesai just to clarify how I understand your answer - does it mean that the network location settings are not impacting how EXO and SPO access to AKV is granted and it will work regardless of which setting for AKV network location is being used?

**Comment by brdesai** [comment]
EXO and SPO Customer Key should function independent of the AKV network settings as long as the services are granted explicit permission to perform get/wrap/unwrap operations using AKV as called out in the documentation.

**Comment by yogkumgit** [comment]
@brdesai Thank you very much for sharing this explanation. @Larryngolog Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Larryngolog** [comment]
Thanks a lot, yes now all is clear.
