### ISSUE TITLE
Permissions for disposition

### ISSUE THREAD

**Issue by Jimnar** [MicrosoftDocs/microsoft-365-docs#2546]
[Enter feedback here]

The article says to create create a new role group called Disposition Reviewers, with one role from Exchange Online and one role from the Security & Compliance Center. Where should the role group be created? I'm assuming the Security & Compliance center, but it isn't clear. Is it possible to include a role from one admin center in the role group of another admin center?

Anything that can be done to make the permissions setting process would be much much appreciated.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad8e9d1-9cd8-0231-b4ef-47c2657449d1
* Version Independent ID: e2be2f00-9a29-592b-f202-ad73d6e7a99d
* Content: [Disposition of content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/disposition?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/disposition.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/disposition.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Jimnar  Yes, you can create this role group in the Security & Compliance Center.  It's not always possible to include a role from one admin center in the role group of another admin center. However, in this specific case, View-only Audit Logs from EAC can be assigned to a user as part of the Disposition Reviewers role group created in the Security & Compliance Center.

The engineering team is looking at making improvements to the permissions model for retention and records management, to make it simpler.  But I strongly encourage you to post this request on UserVoice, to help bump the priority and you can monitor progress.  Use this category: https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=379531

**Comment by Jimnar** [comment]
@cabailey, thank you so much for the clarification. I think just making it a bit more clear in Docs would be a beautiful thing. Maybe take the text from your post and put it into the artilce: 

It's not always possible to include a role from one admin center in the role group of another admin center. However, in this specific case, View-only Audit Logs from EAC can be assigned to a user as part of the Disposition Reviewers role group created in the Security & Compliance Center.

**Comment by cabailey** [comment]
@Jimnar  I'm pleased my clarification helped but I'm hesitant to put "It's not always possible to include a role from one admin center in the role group of another admin center" into this documentation.  That statement is true today but might not always be true, and I might not be informed of such a change.  Instead, I would rather keep this documentation focused on what to do, and the instructions documented are possible by using by the Security & Compliance Center.  If it required a special configuration, such as PowerShell only, that would be documented.
