### ISSUE TITLE
fylo microsoft 356

### ISSUE THREAD

**Issue by fylo5** [MicrosoftDocs/microsoft-365-docs#2547]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 709fda6f-3a7d-92aa-e7ad-afb09cd47cda
* Version Independent ID: 991f7ce4-e3a8-e044-c3c5-82de3b8837d3
* Content: [Admin center overview - Microsoft 365 admin](https://docs.microsoft.com/ar-sa/microsoft-365/admin/admin-overview/admin-overview?view=o365-worldwide#who-has-admin-permissions-in-my-business)
* Content Source: [microsoft-365/admin/admin-overview/admin-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-overview.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@fylo5 Please write your comment in English.

**Comment by yogkumgit** [comment]
@fylo5 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
