### ISSUE TITLE
No "INFO" or "SYNC" button under Connected to Azure AD option

### ISSUE THREAD

**Issue by abhinandanmadaan** [MicrosoftDocs/microsoft-365-docs#2549]
While joining my organisation's Azure AD, after login I try to click on the "**_Connected to ___ Azure AD_**" to find the **_"info"_** button, but turns out there is just one button of "**_Disconnect_**" there. There is no INFO button nor any SYNC option.
Using windows 10 pro 6 bit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8e657e-2aa7-230d-0d9d-675c0200ac18
* Version Independent ID: 2028f003-2624-2bd3-34ea-6022d495e2c6
* Content: [Set up Windows devices for Microsoft 365 Business Premium users - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/set-up-windows-devices?view=o365-worldwide)
* Content Source: [microsoft-365/business/set-up-windows-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/set-up-windows-devices.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@abhinandanmadaan Thank you for your feedback. I tested this on a new machine and it does show Info and sync button.

![image](https://user-images.githubusercontent.com/45987684/89564558-d1ee9c80-d83a-11ea-8eb4-2f682ed49ef4.png)

![image](https://user-images.githubusercontent.com/45987684/89564602-e16de580-d83a-11ea-801e-50b88c462cf6.png)


This could be more related to your environment and i would suggest you to create a support ticket with our technical team to troubleshoot this issue. You can contact M365 Support team from the need help option in the admin center. 

If there are any other changes required in the document, please do let us know.

@yogkumgit There is no changes required in the document as such and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @abhinandanmadaan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by abhinandanmadaan** [comment]
![Issue](https://user-images.githubusercontent.com/36622007/89639118-a3b89d80-d8ca-11ea-9056-d3d8dbb3383c.png)
You can refer to this screenshot.

**Comment by msbemba** [comment]
@abhinandanmadaan This is strange as it should show up the info button. This is more an issue on your Azure tenant and there are no changes required in the document. I'd recommend you contact M365 support via the need help option in the admin center to sort this out.

![image](https://user-images.githubusercontent.com/45987684/89650619-5810ee80-d8e0-11ea-9e9a-faebed1371e5.png)

If there are any other changes required in the document, please do let us know.

Thanks
Sri
