### ISSUE TITLE
Group Restored Not Seeing SharePoint Contents Restored

### ISSUE THREAD

**Issue by shs-hathawayrob** [MicrosoftDocs/microsoft-365-docs#2550]
I restored the group. But the SharePoint site content is not restore.  The site is under active SharePoint sites.  But the URL doesn't work.  Clicking on the site has greyed out metadata.  
I removed the group last night.  I restored a few minutes.  Maybe it takes more time for the site and files to be restored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d49db57-a705-20aa-e98d-5b3d6bbbf9fd
* Version Independent ID: 5a056f2c-03c9-7a34-3196-8bfb1039f6a5
* Content: [Restore a deleted group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/restore-deleted-group?redirectSourcePath=%252farticle%252fb7c66b59-657a-4e1a-8aa0-8163b1f4eb54&view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/restore-deleted-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/restore-deleted-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@shs-hathawayrob Thank you for your feedback. In some cases, it may take as long as 24 hours for the group and all of its data to be restored.

We have added a similar note to the document.

As such, there is no changes required in the document and this can be closed @yogkumgit 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @shs-hathawayrob Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
