### ISSUE TITLE
Can't promote tile to App Launcher

### ISSUE THREAD

**Issue by dhilgarth** [MicrosoftDocs/microsoft-365-docs#2551]
I am unable to pin the custom tile launcher.

The description under "Promote the tile to App Launcher" seems to be incorrect, because I don't get the option "Pin to launcher" when I click the ellipsis. I tried both from the office 365 main page as well as from the admin portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9488caf7-b791-3002-8749-7fdc4b2ec8b3
* Version Independent ID: 08e61eb0-7bcd-f449-46ef-17e209138a8e
* Content: [Add custom tiles to the app launcher - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/customize-the-app-launcher?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/customize-the-app-launcher.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@dhilgarth Thank you for your feedback. I tested with an administrator account and the pin to launcher works. Remember that the account used for this activity needs to have an exchange online mailbox.

We have a note in the document which talks about this:- 

If you don't see the custom tile created in the previous steps, make sure you have an Exchange Online mailbox assigned to you and you've signed into your mailbox at least once. These steps are required for custom tiles in Microsoft 365.


As such, there are no changes required in the document, so this issue can be closed @yogkumgit 

Thanks
Sri

**Comment by dhilgarth** [comment]
I am the admin of the whole organization and I have an exchange online mailbox.
I do see the custom tile but I don't see that option. On no tile.
Obviou6, the documentation is lacking something, otherwise I could identify the location I am supposed to see this option.
Can you please post a screenshot here?

**Comment by msbemba** [comment]
@dhilgarth Please do post what you see on the Admin center. I tested it and it works as seen below

![image](https://user-images.githubusercontent.com/45987684/89566079-22ff9000-d83d-11ea-96f6-f12bf04c40b0.png)

**Comment by dhilgarth** [comment]
Please check https://cloud.sovarto.com/f/85e5739d22c7495181ba. It's a video that shows how I create the custom tile and how I am trying to pin it to the launcher

**Comment by msbemba** [comment]
@dhilgarth Thank you for your feedback and the effort in posting the video. I followed the document and was able to create a custom tile and pin it to the launcher, so there is no changes required in the document as of now. We are from the documentation team and unfortunately cannot troubleshoot. This issue relates more to your tenant and. I'd recommend you contact Microsoft 365 technical support via the need help option in the admin center to troubleshoot.

 Post troubleshooting with Microsoft tech support if you think information is missing in the documentation, do let us know by replying to this issue.

@yogkumgit We can close this issue for now as there is no changes needed in the documentation.

Thanks
Sri

**Comment by dhilgarth** [comment]
@msbemba So from the video you saw that I did the right steps as intended by the documentation? If so, I agree, the documentation needs no change.

**Comment by msbemba** [comment]
@dhilgarth This could be a bug just on your tenant which can be fixed in the backend. As far as the document is concerned the steps work on multiple 365 tenants that I tested. As I said I'd recommend you contact Microsoft 365 technical support via the need help option in the admin center to troubleshoot and let us know.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dhilgarth Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
