### ISSUE TITLE
Service domain support and logic/syntax details

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/microsoft-365-docs#2553]
Can details be added to service domains similar to the file path section to detail what's supported regarding wildcards, subdomains, directories and combinations thereof? E.g. `*.gov, drive.google.com, contosos.sharepoint.com/sites/allowed, *.sharepoint.com, contoso.sharepoint.com/sites/hr/*`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76da4eda-4ccf-ff34-6a48-d9c5553c2ed6
* Version Independent ID: 7e887aff-1b85-1651-2bff-63425c54ae63
* Content: [Using  Endpoint data loss prevention (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-using?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-using.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
HI @ssccaavvookk  - 
Thanks for your comment, service domains do not accept wildcards.
