### ISSUE TITLE
Wildcard SPF Record for subdomains that dont send mail?

### ISSUE THREAD

**Issue by MediumBrownToast** [MicrosoftDocs/microsoft-365-docs#2558]
Hi,

I noticed that this article and none of the other SPF articles in the MS KB contain a suggestion for adding a wildcard SPF TXT record. Isn't it best practice to add a record like below to prevent spoofing of subdomains? The articles talk about SPF TXT records for a "domain" but it might be more helpful to explicitly state something like "an SPF TXT record should be created for each subdomain that sends email" and "a wildcard record should be created to prevent spoofing of all other subdomains".

`*.contoso.com. TXT "v=spf1 –all"`

I believe this also applies to DKIM. The asterisk allows for selector 1 or selector 2 :

`*._domainkey.contoso.com. TXT "v=DKIM1; p="`

or at the very least, creating a record for existing subdomains that should not send email:

`*._domainkey.SubDomainThatShouldntSendMail.contoso.com. TXT "v=DKIM1; p="`

And a wildcard-type policy for DMARC when subdomains shouldn't be sending email, by adding the "sp" value:
`_dmarc.contoso.com. TXT "v=DMARC1; p=reject; sp=reject; ruf=mailto:authfail@contoso.com; rua=mailto:aggrep@contoso.com"`

Relevant MS Documentation:
https://docs.microsoft.com/en-au/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing
https://docs.microsoft.com/en-au/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email
https://docs.microsoft.com/en-au/microsoft-365/security/office-365-security/use-dmarc-to-validate-email

and to a lesser extent:
https://docs.microsoft.com/en-us/office365/enterprise/external-domain-name-system-records
https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider#add-a-txt-record-for-spf-to-help-prevent-email-spam

**Comment by denisebmsft** [comment]
Hello @MediumBrownToast. Thank you for posting your question. Can you please tell us to which article(s) your feedback applies? This information will help us route the issue to the correct writer/team. Thanks!

**Comment by MediumBrownToast** [comment]
Hi @denisebmsft, thank you for your response. I have updated the original post with additional information and links to documents that may be relevant.

Thanks

**Comment by msbemba** [comment]
@MediumBrownToast Thank you so much for the feedback. We have updated all three documents via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2587 , PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2588, and PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2589

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MediumBrownToast Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
