### ISSUE TITLE
Lab Guides 2004?

### ISSUE THREAD

**Issue by mempoweredau** [MicrosoftDocs/microsoft-365-docs#2559]
Just downloaded lab kit 2004. The Evaluation center mentions the following under description;

The lab kit consists of two self-extracting zip files: the lab environment and the lab guides.

I've ran the setup.exe and all VMs are setup etc. There are only 3 files in the downloaded zip
Setup.exe
zpaq.exe
DeploymentLabKit.zpaq

Checked the folder and there are snapshots, virtual disks and virtual machines but no sign of any lab guides. What am I missing?

**Comment by denisebmsft** [comment]
Hello @mempoweredau and thank you for posting your question. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team.

**Comment by mempoweredau** [comment]
Hi,

This is from the following article;

https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide


Thanks

Luke


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by msbemba** [comment]
@mempoweredau Thank you for your feedback. We checked the link again - https://www.microsoft.com/en-us/evalcenter/evaluate-lab-kit and found the lab guides. 

![image](https://user-images.githubusercontent.com/45987684/89802874-b68fd400-db4f-11ea-9fe1-6e7510f7bfb6.png)

![image](https://user-images.githubusercontent.com/45987684/89802936-cb6c6780-db4f-11ea-9d42-51d6c0daccce.png)



@yogkumgit As such, there are no changes required in the document and we can proceed with closing the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mempoweredau Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
