### ISSUE TITLE
ccpa

### ISSUE THREAD

**Issue by andysalvadors** [MicrosoftDocs/microsoft-365-docs#2560]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac49698-fb03-c04b-e420-c7e54f8daa06
* Version Independent ID: b0202a29-7010-7689-0600-438b3da8bc2e
* Content: [California Consumer Privacy Act (CCPA) FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ccpa-faq?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ccpa-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ccpa-faq.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@andysalvadors The FAQ seems to be up to date and in fact, we recently updated the document in March. Could you please clarify what exactly is missing or needs modification in the document?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution.  @andysalvadors We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
