### ISSUE TITLE
Microsoft 365 Groups can now be used as Security Groups?

### ISSUE THREAD

**Issue by JBHorne** [MicrosoftDocs/microsoft-365-docs#2561]
Some sort of change was made recently in which new groups created as Microsoft 365 groups are also flagged as Security Groups. Any of our previous Office 365 groups are not. There is no indication on AAD that these new groups are also security groups, but it is clear if you download the Group CSV from AAD, or attempt to assign an app to a Microsoft 365 group. Previously, this was not possible and we had to create separate Microsoft 365 groups and Security Groups. I cannot find this change documented anywhere, so felt I should get clarification here. The documentation makes no reference to this change either.

Also, I cannot find a way now to convert legacy Office 365 groups to Microsoft 365 groups WITH "securityEnabled".

Here's an example of a recently created group that shows it's both a Microsoft 365 group AND can be used for security:

![image](https://user-images.githubusercontent.com/25235262/89668321-6a643b80-d892-11ea-8301-8f50eb30a6dd.png)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@JBHorne Thank you for your feedback. I found the same behavior and worked with the PG/Author and found that this is a feature gap they are tracking separately(to be resolved/updated soon) – However, M365 groups can be used as security groups, but it’s not recommended.

@yogkumgit Above is the update we received from PG. This can be closed as they are tracking this feature gap separately.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JBHorne Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
