### ISSUE TITLE
Searchable Properties are now available?

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#2562]
Unless it is still only in preview / target release, the functionality mentioned in the following sentence is now available:

> Support for adding searchable properties (for example, subject:) is coming soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef663fdc-1776-3c73-7743-332796c284e6
* Version Independent ID: ceb29788-39be-8c30-b92a-7a22243ebe83
* Content: [Create and configure retention policies to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@sparkitect Thank you for your feedback. The searchable properties are now available and we have updated the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2576

Thanks
Sri

**Comment by cabailey** [comment]
Yes, confirmed by engineering.  I'll merge the PR.
