### ISSUE TITLE
Query cannot make use of an Alias for "searchable properties"

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#2563]
In the section "Auto-apply labels to content with keywords or searchable properties" it (perhaps) should be noted that the _Alias_ for a Managed Property cannot be used in the query; it must be the **actual name** of the Managed Property (e.g. RefinableString01).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a4716f6-31db-306c-2804-56591e3af7e6
* Version Independent ID: 8dfc13ff-3b6a-ba25-2911-db7a3dcd2e8a
* Content: [Automatically apply a retention label to retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-retention-labels-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-retention-labels-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-retention-labels-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@sparkitect Thank you for your feedback. I have added a line to the document about this and can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2582

Thanks
Sri

**Comment by cabailey** [comment]
Yes, this clarifying detail is confirmed by engineering, I'll merge the PR.
