### ISSUE TITLE
Creating Mailboxes on a new domain prior to change MX seems contradictory

### ISSUE THREAD

**Issue by jess8bit** [MicrosoftDocs/microsoft-365-docs#2564]
Hello,
not really an issue, more like a clarification or rephrasing?
About this:
`Make sure you've created mailboxes in Microsoft 365 for everyone who has email on your domain BEFORE you change the MX record.`
Here's my process:
step 1: Say I 

1. have 1 user : emperor@palpatine.onmicrosoft.com
2. step 2: Now I add my new domain darkside.com
3. step 3: Now I

 can change the primary address to emperor@darkside.com
The phrase I quoted suggests I should have somehow created emperor@darkside.com before adding the domain, whic is technically impossible (isn't it?) 
The term "mailbox" may be interpreted as a User or as an Email Address. The User does exist before adding the new domain, but the new address doesn't and cannot until the domain (MX) is added
Am I mixing up something here?
Thanks!

**Comment by msbemba** [comment]
@jess8bit Thank you for your feedback. Are you referring to the document - https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/find-and-fix-issues?view=o365-worldwide ? 

Make sure you've created mailboxes in Microsoft 365 for everyone who has email on your domain BEFORE you change the MX record means that after you verify your domain, change the primary address for all users to the domain before pointing the MX record to m365.

In your process 

have

Step 1 user : emperor@palpatine.onmicrosoft.com
step 2: Now I add my new domain darkside.com (you are verifying that you own the domain)
step 3: Now I can change the primary address to emperor@darkside.com
Step4: Change the MX record to point to M365.

Hope this helps! 



Thanks
Sri

**Comment by jess8bit** [comment]
Oh!! Thank you so much for that precision.

As a matter of fact I had never realized it was actually possible to change the primary address as soon as right after the Verification step and before changing the MX record to point to 365!!

I thought you had to go through the whole Add your domain process to be able to change the primary address.

Also, does that mean I can simply have the domain Verified, then put the process on hold for some days and come back later to finalize the domain connection in 365 Admin ?

Thanks for shedding some light on this 😊

Best regards,
J

**Comment by msbemba** [comment]
@jess8bit That is correct! You can verify the domain, Put the process on hold and/or migrate user accounts and Cutover MX at a later date.

Hope this helps!

@yogkumgit Question has been clarified and no changes required on the document. Please close the issue.

Thanks
Sri

**Comment by jess8bit** [comment]
Thanks for the quick reply, appreciate it!

Sorry if it was out of scope,

Have a great day,
J

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jess8bit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
