### ISSUE TITLE
Old link / missing content for "pilot Microsoft 365"

### ISSUE THREAD

**Issue by kastman** [MicrosoftDocs/microsoft-365-docs#2566]
The link to FAQ with the text "You can take steps to pilot Microsoft 365 with just a few email addresses instead." doesn't actually have that relevant content. Has it been moved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1394eba-4e78-2fd6-84f3-4ee64aedab51
* Version Independent ID: 0ba9ff8c-20a8-58a9-dce7-a3bb0627c134
* Content: [Change your email address to use your custom domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/change-email-address?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/change-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/change-email-address.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@kastman Thank you for your feedback. We have fixed this via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2583

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @kastman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
