### ISSUE TITLE
Prerequisite section has wrong licensing

### ISSUE THREAD

**Issue by mastood** [MicrosoftDocs/microsoft-365-docs#2568]
This section on licensing/prerequisite section is wrong.  The following text needs to be updated with the correct licensing: 

Every account that accesses and uses data classification must have a license assigned to it from one of these subscriptions:
Microsoft 365 (E5)
Office 365 (E5)
Advanced Compliance (E5) add-on
Advanced Threat Intelligence (E5) add-on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37494e01-d673-2fcb-4a86-baecb716120e
* Version Independent ID: 1f46b90e-3691-5b81-9f9e-ce3c94f18a1d
* Content: [Get started with data classification - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@mastood Thank you for your feedback. For specific rights by license, see the detailed Microsoft 365 Compliance Licensing Comparison. (PDF - https://opdhsblobprod04.blob.core.windows.net/contents/e0993bf6e82e4fa8ac18b48839521869/2ce5e803079c3427c011efbce08b900a?sv=2018-03-28&sr=b&si=ReadPolicy&sig=KAG1lGSeWNpMVjfNAkfb1pKjGDpk8kuCyiMNPbZE%2BpA%3D&st=2020-08-10T19%3A40%3A49Z&se=2020-08-11T19%3A50%3A49Z)

I have made changes to the documentation accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2585

Thanks
Sri

**Comment by chrfox** [comment]
HI @mastood -  confirming licensing requirements with engineering and will update the topic as appropriate.
