### ISSUE TITLE
ADD LINK text with no link. 

### ISSUE THREAD

**Issue by ilyapozharsky** [MicrosoftDocs/microsoft-365-docs#2569]
Under this link. https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-policies?view=o365-worldwide#data-leaks-by-priority-users-preview
 
the first paragraph ends with "ADD LINK"  looks to be a mistake. 

![image](https://user-images.githubusercontent.com/67023198/89713920-f8125a80-d968-11ea-9926-35b4705d1e30.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3096e5de-0e2b-eb0e-850e-0cee9118078e
* Version Independent ID: 732f4433-84cb-43d5-131c-b21c358c7f99
* Content: [Insider risk management policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-policies?view=o365-worldwide#data-leaks-by-priority-users-preview)
* Content Source: [microsoft-365/compliance/insider-risk-management-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@ilyapozharsky Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2577

Thanks
Sri

**Comment by robmazz** [comment]
@ilyapozharsky - thanks for your feedback, these changes were fixed in a separate update PR.
