### ISSUE TITLE
Section about exceptions

### ISSUE THREAD

**Issue by ACarlockAKA** [MicrosoftDocs/microsoft-365-docs#2570]
I think you should add a section about exceptions.  There are times when you need to manually remove addresses, and that should be mentioned in this document.  After attempting these steps, I'm receiving this error message:

"The automatic remove process cannot be scheduled right now. This occurs if you are a partner managing a different account (currently not a supported scenario), the detected dependencies cannot be removed by automatic process or the automatic removal is not yet enabled in your region. Please consider manually removing remaining dependencies."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780db236-9235-2ce7-acbb-953fd997215b
* Version Independent ID: a5b80ea1-fb9f-d381-4fa6-7d4d8cce3f82
* Content: [Remove a domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/remove-a-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/remove-a-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/remove-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@ACarlockAKA Thank you for your feedback. There are no exceptions as such, however if you receive any error during the removal process you can follow the link -https://docs.microsoft.com/en-us/office365/troubleshoot/administration/error-remove-domain-from-office-365 or contact Support. We have added this link to the document via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2584

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The Link to contact support has been added to the document in case there are issues removing the domain. Please close the issue.

Thanks
Sri
