### ISSUE TITLE
Content search can find Yammer content

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#2571]
You can now use content search for Yammer content if Yammer is running in native mode. It might be good to add this information to the section "Using the Content Search eDiscovery tool to respond to DSRs". Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 632c11fa-8975-afd4-a050-7ff42ca3eb33
* Version Independent ID: 2b736015-0f61-4159-e102-77a056f8abec
* Content: [Office 365 Data Subject Requests Under the GDPR and CCPA - Microsoft GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-dsr-office365?view=o365-worldwide#additional-considerations-for-selected-applications)
* Content Source: [microsoft-365/compliance/gdpr-dsr-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-dsr-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@EricaToelle Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2609

Thanks
Sri

**Comment by robmazz** [comment]
@EricaToelle - thanks for the feedback, will confirm through GDPR CELA process and incorporate as appropriate.
