### ISSUE TITLE
Direct message ancestors only?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/microsoft-365-docs#2572]
[Enter feedback here]
In the diagram of Thread1, if message2 matched the keyword and date range query, and this was added into a review set with conversation retrieval enabled, would message3 and message4 also be added to the review set, or only message1 (the direct ancestor)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c7b265-cceb-fe6b-2490-ab225665695b
* Version Independent ID: af062eb4-4d5f-e5d5-0638-0e627c09ce09
* Content: [Review conversations in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/conversation-review-sets?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/conversation-review-sets.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/conversation-review-sets.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Michael-Sampson The entire conversation thread will be added to the review set. So if if you add the search results to a conversation review set, all messages from the thread are added when one of those messages matches your search query. And you'll be able to view (and export) the threaded conversation and individual messages in the conversation. 

Also, I believe that we use an 8-hour bookending/window to determine/construct a conversation thread. That means we include messages from the thread that occur 4 hrs before the chat message that matched the search criteria and 4-hrs after that same message.

**Comment by markjjo** [comment]
@Michael-Sampson Also meant to add that I will look into adding the 8-hour bookending info to the documentation.
