### ISSUE TITLE
Phish clarification

### ISSUE THREAD

**Issue by iaasazure** [MicrosoftDocs/microsoft-365-docs#2578]
t is not clear what types of phish messages users can see and what they can do with them.

"Admins can also enable end-user spam notifications in anti-spam policies. Users can release quarantined spam messages but not quarantined phishing messages directly from these notifications. For more information, see End-user spam notifications in EOP.

Messages that were quarantined for high confidence phishing, malware, or by mail flow rules (also known as transport rules) are only available to admins. Phishing messages can be reviewed by users, but only released by admins. For more information, see Manage quarantined messages and files as an admin in EOP."

To clarify is the below correct? I have change the terms to match the functions i.e. preview rather than review.

All quarantined messages are available to admins, all functions are available including preview and release.
Messages that were quarantined for high confidence phishing, malware, or by mail flow rules (also known as transport rules) are not visible to end users.
Low confidence phishing messages can be previewed by users, but only released by admins.

End-user spam notification emails allow users to release spam emails directly from these notifications using the release button on the email. Phish messages only present the review button in the end-user spam notification email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfc15d1-833b-3139-6bc0-1acb97d507c8
* Version Independent ID: 31e24618-c2e6-4fe4-9651-04d6007548a4
* Content: [Find and release quarantined messages as a user - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@iaasazure, the 'review' vs. 'preview' thing is rather subtle. The intent was to say 'admins can do things to these messages' 'users can see the messages'. 

I clarified the statements in the topics based on what you said.

Thanks for the feedback.

Closing
