### ISSUE TITLE
Typo in available templates section

### ISSUE THREAD

**Issue by Jens-Lorenz** [MicrosoftDocs/microsoft-365-docs#2586]
In the section available templates under Global it lists "ISO 27001:2019" but it should be "ISO 27701:2019" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a406f24f-e0c1-9143-9130-ce0459a66235
* Version Independent ID: e040197a-12cc-281a-d75d-16395b24c46f
* Content: [Microsoft Compliance Score (preview) templates - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score-templates?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-score-templates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-score-templates.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Thank you - this will be corrected before the end of today.
