### ISSUE TITLE
Article Length

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#259]
This article is exceptionally long, please break it up into many articles that will be easier to read

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 632c11fa-8975-afd4-a050-7ff42ca3eb33
* Version Independent ID: 2b736015-0f61-4159-e102-77a056f8abec
* Content: [Office 365 Data Service Requests Under the GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-dsr-office365?toc=/microsoft-365/enterprise/toc.json)
* Content Source: [microsoft-365/compliance/gdpr-dsr-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-dsr-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by markjjo** [comment]
This is by design; this is a user guide for all Office 365 applications.

**Comment by DeanGross** [comment]
most of the pages in Docs are less than 10 minutes to read, this one is more 2 hours which is entirely too long for reading online and keep track of where we are on the page
