### ISSUE TITLE
Emptying SubstrateHolds folder?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/microsoft-365-docs#2591]
[Enter feedback here]
The section "Content paths for delete-only retention policy" includes this line: "If a user deletes the message from there [the SubstrateHolds folder] or empties the SubstrateHolds folder, the item is permanently deleted." What enforcement do you have to prevent this from happening under the other scenarios, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Michael-Sampson  Yes, this wording isn't quite right - leave it with me.  A standard user doesn't have access to the (hidden) SubstrateHolds folder, which is where the content in place data is stored.  So this sentence simply shouldn't be there.

**Comment by Michael-Sampson** [comment]
Thanks, Carol. Sounded a bit weird when I read it.
