### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by 383apps** [MicrosoftDocs/microsoft-365-docs#2593]
Hi,
This page is out of date following the 16.07.20 ruling by the EUJC to say that the EU-US Privacy Shield is now invalid as the US does not secure their data significantly enough. How is Microsoft ensuring the data they transfer from EU to US is protected?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf67c4b7-2382-8438-1b15-a6f46373ead4
* Version Independent ID: 831a060a-e8ed-95ab-ce10-c1847d3bb5db
* Content: [EU-US and Swiss-US Privacy Shield Frameworks - Microsoft Compliance](https://docs.microsoft.com/en-GB/microsoft-365/compliance/offering-eu-us-privacy-shield?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-EU-US-Privacy-Shield.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-EU-US-Privacy-Shield.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@383apps - thanks for the feedback, I'm checking with our legal review folks for an answer on the EU-US Privacy Shield Framework. I hope to have an answer in a week or two (holidays for a lot of the reviewers in August).

**Comment by yogkumgit** [comment]
@robmazz  Do we get the answer, Kindly help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@383apps - thanks for your patience on this, circling back to let you know this has been updated. The original topic on this request has been deleted, please see the EU model clauses topic - https://docs.microsoft.com/compliance/regulatory/offering-eu-model-clauses. Thanks!
