### ISSUE TITLE
Factually incorrect

### ISSUE THREAD

**Issue by Eric2XU** [MicrosoftDocs/microsoft-365-docs#2594]
the following phrase: 

"These features are currently available in the English (United States) market for users with mailboxes in the US geo"

Its not true. It has NOTHING to do with Mailbox location. It is set based on "Usage Location" which is 'Location' under 'Licenses and Apps' in the O365 Admin UI OR can be found by using this command: Get-MsolUser -UserPrincipalName "User@domain.com" | fl UsageLocation

Please update the docs to reflect reality and think about putting a note section with the location in the GUI as well the command that can be run to demine if a user is eligible. It took over 5 weeks with an open support case for even support to figure this out because (and here is the kicker) all they do is google and find this wrong article.  Case: 21073947 for ref. 

Cheers! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad4b3d3-b509-c6c6-e842-b53c68100c4e
* Version Independent ID: ec63705a-7ce3-abf6-5f4f-fe5bc95bc9b8
* Content: [Cortana in Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/cortana-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/cortana-integration.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Eric2XU Thank you for your feedback. Sorry for what you had to go through in the past 5 weeks to get this information. I have added a link to find out the usage location via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2616

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @Eric2XU Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
