### ISSUE TITLE
Quarantine reason for anti-phishing?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/microsoft-365-docs#2597]
Various quarantine reasons are listed in the article. However they all seem to apply to EOP quarantine possibilities. What if O365 ATP Anti-Phishing Policy is configured with quarantine action, what is shown as the quarantine reason for those messages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an admin - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@ArttuArstila Thank you for your feedback. It remains the same, as there are always 5 quarantine reasons regardless if it is ATP or EOP quarantining the message, they are 

Policy

Bulk

Phish

Malware

Spam

High Confidence Phish

Hope this helps!

@yogkumgit No changes required in the document and this can be closed.

Thanks
Sri

**Comment by ArttuArstila** [comment]
Thanks for the reply! What are the exact reasons that are used by ATP? That is not documented anywhere.

**Comment by msbemba** [comment]
@ArttuArstila Thank you for your feedback. It is not mentioned because ATP and EOP use the same quarantine folder and the quarantine reasons remain the same except for the Transport rule which kicks in before ATP.

Thanks
Sri

**Comment by ArttuArstila** [comment]
I understand what you are saying, but mapping ATP actions to quarantine reasons in documentation would be extremely helpful. For example "ATP user impersonation with quarantine action results in phish reason in quarantine" etc. This is now missing.

**Comment by msbemba** [comment]
@ArttuArstila I'm checking this with Author and will update you shortly.

**Comment by yogkumgit** [comment]
@chrisda  Kindly answer and help us in resolving this issue. Thanks.

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@ArttuArstila, the Phish reason includes messages quarantined by anti-phishing protection (spoof settings or impersonation protection). I've updated the topic accordingly.

Thanks for the feedback.

Closing
