### ISSUE TITLE
No 'VIA' in the Outlook web app when the (spoofed) address is an office 365 group.

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/microsoft-365-docs#2599]
We have executed a phishing test in our company. The sender spoofed the sending email as IT@contoso.com.
At our company, we have an office 365 group called 'IT' (IT@contoso.com).

The signs to check for a spoofed message are described [here](https://support.microsoft.com/en-us/office/identify-suspicious-messages-in-outlook-com-and-outlook-on-the-web-3d44102b-6ce3-4f7c-a359-b623bec82206?ui=en-us&rs=en-us&ad=us).

In Outlook Desktop, I can clearly see that the email is being spoofed (as described in the documentation):
![image](https://user-images.githubusercontent.com/20435853/90027626-0807a280-dcb9-11ea-8e32-f01da99ea44d.png)

However, in OWA, the spoofed address is shown as being the O365 group, and there is no hint that the sender was spoofed:
![image](https://user-images.githubusercontent.com/20435853/90027349-bced8f80-dcb8-11ea-982c-2a27ac160396.png)

It actually looks very legit.

Is this expected behavior? Is there another way that my users can see the address is being spoofed (except for looking at the headers in the message details)?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e130b60f-b97b-cfb1-4857-a08e79fdfd59
* Version Independent ID: 19e405c4-a6c0-7c75-b925-ff9637f1889e
* Content: [Anti-spoofing protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spoofing-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spoofing-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spoofing-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@w0ut0 Thank you for your feedback. This is not the expected behavior. I tested it and it does not look like this and shows the original email address in brackets both in outlook and OWA.

 I'd recommend you contact the support team via the Need help button on the admin center and report/troubleshoot this as there could be a bug. After troubleshooting, if you feel there is a modification needed in the document, let us know so that we can verify and make the changes. 

@yogkumgit Please close the issue as there is no changes needed.

Thanks
Sri

**Comment by chrisda** [comment]
@w0ut0, definitely open a a support case, which will get the attention of the product team. I'm told that it's supposed to work in OWA.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @w0ut0 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by w0ut0** [comment]
Thank you all for your feedback @msbemba @chrisda @yogkumgit, I opened the support case (office 365 support #21395898).

The support agent escalated the issue and got back to me with the message that OWA is not designed to show the 'via' address on spoofed emails??

`Hello Wout,


Thank you for your time and patience with us.


As informed, OWA will not show up the information as showing in the Outlook Desktop by product design.

We are sharing the Product Feedback link with you, so that you can provide your feedback regarding the issue and feature:  

We appreciate your opinions and recommendations on Office 365 products as a valued customer. The feedback that our customers submit are logged and read by our development team. The more times that certain features or issues are submitted the higher chance of it getting added or fixed in the next release  

http://office365.uservoice.com/   

As discussed, we will be archiving this case for now and feel free to write back to us for any query or concerns and we will be glad to assist you further.
`
In my opinion, this is a very strange reaction, no? According to [the documentation](https://support.microsoft.com/en-us/office/identify-suspicious-messages-in-outlook-com-and-outlook-on-the-web-3d44102b-6ce3-4f7c-a359-b623bec82206?ui=en-us&rs=en-us&ad=us), it should be supported.

I will follow up with the support case.

**Comment by w0ut0** [comment]
Update, the documentation I supplied, only applies to Outlook on the web Outlook.com Outlook on the web for Exchange Server 2016. Not to office 365 OWA.

The functionality is not supported, I created a uservoice suggestion:
https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/41192461-show-the-via-option-for-spoofed-email-adresses

There is already an existing suggestion to stop linking spoofed adresses to group/user images: https://office365.uservoice.com/forums/264636-general/suggestions/35657518-stop-automatically-linking-user-profile-pictures-w)
