### ISSUE TITLE
Clarify policy processing

### ISSUE THREAD

**Issue by cj8686** [MicrosoftDocs/microsoft-365-docs#2602]
Please clarify how policy processing works when there are multiple policies that apply to the same users/groups. Are they additive or will the first policy that matches (in order of priority) apply and only that policy?

One scenario to explain this might be if a customer needs to protect more than the max of 60 users per policy, they might create a second policy to capture the additional users. All policies apply to all users. Would this be a valid scenario, or would only the first policy with the highest priority apply, leaving the remaining policy ineffective? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ea08aa-4520-8f48-93e2-0ce74cd43298
* Version Independent ID: 7be23d3d-f72b-abd3-e2c4-96ff3998a59b
* Content: [Configure ATP anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cj8686, according to [Order and precedence of email protection] (https://docs.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined), only the settings of first matched policy are applied. Policy processing stops after the first policy, so the settings aren't additive.

**Comment by cj8686** [comment]
Thanks for coming back. That article you linked to appears to contain the info i was looking for. Since the original article discusses the priority of custom policies, it should either mention the 'combining' behaviour or reference to the other article, as without this context it is difficult to understand the policy behaviour.  

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies?view=o365-worldwide#set-the-priority-of-custom-atp-anti-phishing-policies

**Comment by chrisda** [comment]
@cj8686, OK. Done.

Thanks for the feedback.

Closing
