### ISSUE TITLE
This page is out of date with how Bluehost is currently setup now.

### ISSUE THREAD

**Issue by aszalacinski** [MicrosoftDocs/microsoft-365-docs#2604]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d9b2b9-5fbf-0ecd-13f4-0de1613ca854
* Version Independent ID: ccfb9be8-b68a-e7a6-ddd6-18244005a090
* Content: [Create DNS records at Bluehost for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-bluehost?view=o365-worldwide#BKMK_add_CNAME)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-bluehost.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-bluehost.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by yogkumgit** [comment]
@pebaum Please reply and help us in resolving this issue. Thanks.

**Comment by pebaum** [comment]
looking into it.

**Comment by yogkumgit** [comment]
@pebaum  Gentle reminder, Kindly answer and help us in resolving this issue. Thanks.

**Comment by lhcole** [comment]
We are in the process of retiring the Bluehost article and redirecting to this topic: [Add DNS records to connect your domain]https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider
