### ISSUE TITLE
Can you specify more than one password with the password spray attack?

### ISSUE THREAD

**Issue by Nick-Shortal** [MicrosoftDocs/microsoft-365-docs#2605]
[Enter feedback here]

With the password Spray attack is it possible to have more that one password supplied and if so how are these to be seperated?

Single spacing does not appear to work.  Nor does there appear to be an option to upload a list of common passwords to run as part of this simulation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbdcbd5-7bd2-6b55-b72c-cbedfdea776c
* Version Independent ID: 1e6198f8-6ef1-6227-c9e8-f31944a5d1db
* Content: [Attack Simulator in ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Nick-Shortal, per the topic, for a password spray attack, you can only specify one password, but you can specify multiple accounts. If you want to try multiple passwords, use the Brute force (dictionary) attack:

 > For the password spray attack, you can only specify one password to try, and you can specify one or many users.

> For the dictionary attack, you can specify one or many passwords to try (manually entered or in an uploaded file), and you can specify one or many users.

**Comment by msbemba** [comment]
@Nick-Shortal Thank you for your feedback. As per the design and document you can only specify one password for multiple accounts if you are using a password spray attack. 

Hope this helps!

@yogkumgit Please proceed with closing the issue as there is no changes needed in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @Nick-Shortal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
