### ISSUE TITLE
Microsoft 365 group expiration policy - retention policies

### ISSUE THREAD

**Issue by s0041464** [MicrosoftDocs/microsoft-365-docs#2606]
I am trying to figure out how to restore a Microsoft 365 Group once it has reached 30 day expiry and a retention policy kicks in.
What is the retention container and how is it found?

"How expiry works with retention policies
If you have setup retention policy in Security and Compliance center for groups, expiration policy works seamlessly with retention policy. When a group expires, the group's conversations in mail box and files in the group site are retained in the retention container for the specific number of days defined in the retention policy. Users will not see the group, or its content, after expiration however."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3e13d66-a454-b0d6-fdea-c50d9904a71e
* Version Independent ID: 4632edc1-4a14-6a74-669f-0cf9d208770b
* Content: [Groups expiration policy - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@s0041464 Thank you for your feedback. If you are looking for a way to restore an M365 group after its 30 day expiry period then it is not possible, however, you can use the discovery/content search to find the data associated with the group till its retention period (per policy set in the company). 

Basically the principles of retention policy are that retention wins over deletion and in your case, the group is deleted and can be reused (as new) after its expiry but the data cannot be recovered back to the group. however, if there is a need to do a content search for a reason the data will be available until its retention period (per policy).

Hope this helps!

@yogkumgit There is no change required in the document as this is more of a question and it has been answered. Please go ahead with the closure.

Thanks
Sri

**Comment by s0041464** [comment]
Thank you this is what I suspected (the use of eDiscovery) however I was confused by the use of the term “retention container”.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @s0041464 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
