### ISSUE TITLE
Warning at bottom needs to be worded

### ISSUE THREAD

**Issue by Weychris** [MicrosoftDocs/microsoft-365-docs#2607]
Warning:

Passwords set to -PasswordPolicies DisablePasswordExpiration still age based on the pwdLastSet attribute. If you set the user passwords to never expire and then 90+ days go by, the passwords expire. Based on the pwdLastSet attribute, if you change the expiration to -PasswordPolicies None, all passwords that have a pwdLastSet older than 90 days require the user to change them the next time they sign in. This change can affect a large number of users.

--

The above makes zero sense to me no matter how many times I read it. Believe it's missing information or typoed and needs to be reworded to make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52c6916-7e79-9a9c-b7a6-47041ddb81e3
* Version Independent ID: 43c9b873-d354-d814-3065-1e8832361b86
* Content: [Set an individual user's password to never expire - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Weychris Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by shashishailaj** [comment]
@msbemba So from what you have mentioned , it seems until the password is updated for the object the user will continue to follow the org-wide settings (all users.) Because when the user's password is changed/updated , the pwdLastSet attribute is changed and the never expire policy only takes affect after the password attribute(which also updates the pwdLastSet) for the user object is changed. Is that right ?

**Comment by msbemba** [comment]
That is correct @shashishailaj .
