### ISSUE TITLE
Image notation format in compliance/whats-new.md breaks localized images on live site

### ISSUE THREAD

**Issue by elenaost** [MicrosoftDocs/microsoft-365-docs#2611]
The image notation in the following format breaks appearing of images on live pages in machine translated content. In some languages quotes get added to alt-text translations to support language grammar:
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md:
:::image type="content" source="../media/mcc-records-management-page.png" alt-text="Records management section in Microsoft 365 compliance center":::
[Russian](https://github.com/MicrosoftDocs/microsoft-365-docs-pr.ru-RU/blob/live/microsoft-365/compliance/whats-new.md):
:::image type="content" source="../media/mcc-records-management-page.png" alt-text="Раздел "**Управление записями"** в центре соответствия требованиям Microsoft 365":::

Could you please change a notation for the image in microsoft-365/compliance/whats-new.md asap:
from
 :::image type="content" source="../media/mcc-records-management-page.png" alt-text="Records management section in Microsoft 365 compliance center":::
 to: 
![<title>](..<path to.png>)

Thanks,
Elena

**Comment by msbemba** [comment]
@elenaost Thank you for your feedback. We have made changes to the document image notation via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2656

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @elenaost as author is taking looking into it, We proceed here to close it. If you see a documentation update is required, please feel free to open an issue for the same.  Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
