### ISSUE TITLE
Automatic Forwarding

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/microsoft-365-docs#2612]
I noticed the new option "Automatic Forwarding" in the outbound spam filter policy.

Tried several settings, but none are effective - is this working yet? Also the explanation of what the "Automatic - System-controlled" (default) setting does, doesn't really make sense.

In the documentation now:  "Default setting that allows the system to control automatic forwarding with automatic forwarding disabled by default."

What system?
It's enabled by default in my tenant, but forwarding is still possible (so disabled by default is not true, or does disabled mean that forwarding is enabled?)

With Kind Regards,

Kenneth van Surksum

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kennethvs, per Message Center post MC218984 and <https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=63831>, this feature is coming in September. The settings are currently available, but aren't enforced.

I'm in the process of updating the topic accordingly. I, too, would like to know the difference between **Off** and **Automatic**. My guess is that **Automatic** allows a trickle of automatically forwarded messages, but once you are compromised and start going wild, you're blocked. But I'll confirm before I publish.

Thanks for the feedback.

Closing
