### ISSUE TITLE
Update request - Third Party Phishing Test Supportability

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#2613]
Could we update the doc to advise that the DoNotRewrite list is the only supported method to be used when carrying out third party phishing tests with customers protected by O365 ATP / Safe Links policies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac84f75-b6d9-9495-873a-8f87b90b8034
* Version Independent ID: 18369495-0e0f-e3e1-6945-0200790fd107
* Content: [Set up a custom do-not-rewrite URLs list using ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@aldoug, done.

Thanks for the feedback.

Closing.
