### ISSUE TITLE
Connect-MSCommerce - no option for passing authentication credentials

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/microsoft-365-docs#2618]
In the cmdlet Connect-MSCommerce, the only valid parameters I can see are
- ClientId
- RedirectUri
- Resource

There is no parameter to pass credentials for sign in via scripts. This is important as we need to ensure this can be configured via automatic scripts.

How can the Connect-MSCommerce cmd be used via a script with no interactive log on? Sample script below fails

```powershell
$adminuser = $env:GAUsername
$password = ConvertTo-SecureString $env:GAPassword -AsPlainText -Force

$GlobalAdmin = New-Object System.Management.Automation.PSCredential ($adminuser, $password)
    
Connect-MSCommerce -Credential $GlobalAdmin
```

Script output is 
```
Connect-MSCommerce : A parameter cannot be found that matches parameter name 'Credential'.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by StrohBCBSTX** [comment]
Looking for an update - New Viva Self-service trial experience just announced for my tenant and I need to turn this off ASAP.  
Standard user accounts should not have privileged access roles, we need to run this module with vaulted credentials, non-interactive.
