### ISSUE TITLE
Orca report dosent reflect pre-set policies

### ISSUE THREAD

**Issue by msellar-inst** [MicrosoftDocs/microsoft-365-docs#2619]
When running an ORCA report (https://www.powershellgallery.com/packages/ORCA/1.9.11) pre and post applying the Strict EOP/ATP pre-set policies (https://security.microsoft.com/presetSecurityPolicies) there is no change in the ORCA report. It is unclear whether the recommend settings have been applied or not?
(https://docs.microsoft.com/en-nz/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies - Office 365](https://docs.microsoft.com/en-nz/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by andypunt** [comment]
The Preset Security Policies and the ORCA report are somewhat different tools. The Preset Security Policies are pre-canned policies that already meet the recommendations so those policies should never show up in ORCA or Config Analyzer (upcoming feature release that will essentially be ORCA in the service). ORCA on the other hand analyzes all of the policies that are found and will return recommendations on those that need it. Again, since the preset policies are good, they should not show up in a recommendations report. In order to get ORCA to change, you need to manually make the recommended changes it suggests in your report.

**Comment by msellar-inst** [comment]
My requirement is to know that settings are set or to be able to show a client an (ORCA) report showing this.
The MS steps for proving settings are difficult: https://docs.microsoft.com/en-nz/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide#how-do-you-know-these-procedures-worked

Once Preset policies are applied, they seem to only mostly show in Orca, for example below (Strict applied to EOP & ATP):

Bulk Complaint - this shows the default and standard/strict that the preset applied
[https://vo2-my.sharepoint.com/:i:/g/personal/matt_sellar_theinstillery_com/EWk-QDax62pMr-1awE8w6qEBC0rn5G23kaIjmn7iMzRELQ?e=yvfz7p](url)

Outbound Spam Policy - this only shows the default
[https://vo2-my.sharepoint.com/:i:/g/personal/matt_sellar_theinstillery_com/EYfGIj5yOUhKmZWSSYtlUCkBedktQWp8jISFLH1ZwFItmw?e=3Vasu4](url)

Safe Attachments SharePoint and Teams - this only shows the default
[https://vo2-my.sharepoint.com/:i:/g/personal/matt_sellar_theinstillery_com/EXZZAuDLlqRNiL9j949jxDoBTNMvUaq3B0lDeS6m9RgBQQ?e=XSxTs0](url)

So, the question is how do I know for example that "Safe Attachments SharePoint and Teams " is on or off? 
Strict Preset policy would say its on, but Orca says its off, also the Screenshots from  https://security.microsoft.com/safeattachmentv2 seem to suggest its off
[https://vo2-my.sharepoint.com/:i:/g/personal/matt_sellar_theinstillery_com/EZVRKA_hk6dElgY8gZr4LeABonAdXD5R1DatVQXPrkqhXg?e=innJvX](url)
[https://vo2-my.sharepoint.com/:i:/g/personal/matt_sellar_theinstillery_com/EWpSdyxa3qNJqeiEJt-Y01IBlmcK_pyM3_t63r-KapK-7A?e=EPmzIy](url)

**Comment by andypunt** [comment]
I am not able to access your screenshots. Either way, it ay be better to get a case opened with Support to go through these questions. Thanks.

**Comment by msellar-inst** [comment]
I checked my links in Private browsing windows in FF and Edge and they opened? if clicking link doesnt work, perhaps cut n paste URL?

**Comment by andypunt** [comment]
The Preset Security Policies does not cover Outbound spam policy in its current iteration. Otherwise, the Safe Attachments setting should be on. If you do not see that, you will need to open a service ticket from the portal to get it looked at. This forum is to discuss documentation questions. Thanks.

**Comment by msellar-inst** [comment]
> reset Security Policies does not cover Outbound spam policy in its

Just on your most recent comment,  you correctly say pre-sets don't cover outbound policy.
However in the portal it says this:

_"Preset security policies
A preset security policy is compilation of settings for all security policies: anti-spam, **outbound spam filter,** anti-malware, anti-phishing, ATP Safe Links, and ATP Safe Attachments."_

https://security.microsoft.com/presetSecurityPolicies

the Portal text is wrong.

**Comment by andypunt** [comment]
You are correct. We will update the portal. Thanks!

**Comment by chrisda** [comment]
UI has been updated.

Thanks for the feedback.

Closing
