### ISSUE TITLE
Log Analytics include in trials?

### ISSUE THREAD

**Issue by bpe71** [MicrosoftDocs/microsoft-365-docs#262]
Was trying to run the lab based on Azure and M365 trial accounts. Seem to be running in to issues trying to activate the Log Analytics trial. Not possible to activate a marketplace app in the trial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Modern Desktop Deployment and Management Lab Kit](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Thank you for the feedback - we'll investigate what's going on with the log analytics trial and update the instructions
