### ISSUE TITLE
Additional CA policy required to enforce restrictions for unmanaged devices?

### ISSUE THREAD

**Issue by pmeuser** [MicrosoftDocs/microsoft-365-docs#2623]
I have followed the guide to run through some tests in my lab, but any restriction settings (block, web only) to access from unmanaged devices was ignored.

Is it possible, that an additional step is required to create a cond. acc. policy  with session control to "use app enforced restrictions" for SharePoint online?

Thanks a lot for clarifying and eventually extending the documentation.

Peter

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@pmeuser For the unmanaged devices option, we have on this page: "For unmanaged devices (https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices), allow full access, web only access, or block access completely. If you have configured this setting at the tenant level or for a specific site, the setting you specify here will be applied only if it's more restrictive."

If you follow that link for unmanaged devices, it has the following note:

Blocking or limiting access on unmanaged devices relies on Azure AD conditional access policies. Learn about Azure AD licensing For an overview of conditional access in Azure AD, see Conditional access in Azure Active Directory. For info about recommended SharePoint access policies, see Policy recommendations for securing SharePoint sites and files. If you limit access on unmanaged devices, users on managed devices must use one of the supported OS and browser combinations, or they will also have limited access."

So yes, Azure AD conditional access is a prerequisite for this option and the UI you see offers another window to configure the same settings that you can configure for a SharePoint site. That was the point of the link - it's not an independent setting.
