### ISSUE TITLE
No Disconnect cmdlet

### ISSUE THREAD

**Issue by SjoerdV** [MicrosoftDocs/microsoft-365-docs#2624]
I would appreciate a Disconnect cmdlet, so gracefully unloading the module and removing it completely from a system when finished running commands in the same sessions is possible. The thought of having this module on my or any other system longer than necessary makes me nervous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide#example-script-to-disable-allowselfservicepurchase)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@SjoerdV Thanks for the feedback! I have forwarded your comments to the product team for consideration.
