### ISSUE TITLE
Content missing from the Document. 

### ISSUE THREAD

**Issue by ZainIbnShamsher** [MicrosoftDocs/microsoft-365-docs#2625]
Hello There, 

I am working on an Express Route issue and was referred to the article: https://docs.microsoft.com/en-gb/microsoft-365/enterprise/routing-with-expressroute?view=o365-worldwide

When I went to the article's Selective Routing with Express Route section, I found the option I was looking for: 
_PAC files/URLs - directing Office 365 destined network traffic for specific FQDNs to route on a specific path. This selectively routes by client computer as identified by PAC file deployment._

But the URL for the PAC File Deployment is not there, it is directing to a 404 Not found page on the Microsoft Website. 
Please help us by updating the article. Thank you!
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e54e547-0ef6-6a9c-5c50-61c76efe3a10
* Version Independent ID: ca3518a9-3add-256b-c15a-7b3f702445fc
* Content: [Routing with ExpressRoute for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-gb/microsoft-365/enterprise/routing-with-expressroute?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/routing-with-expressroute.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/routing-with-expressroute.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by JoeDavies-MSFT** [comment]
@ZainIbnShamsher This has been fixed. Sorry about the inconvenience. Thanks so much for letting us know.
