### ISSUE TITLE
Add Mailbird to the list of clients that supports Modern Authentication

### ISSUE THREAD

**Issue by mol** [MicrosoftDocs/microsoft-365-docs#2626]
On the page is listed a range of clients/services that supports Modern Authentication.

[Mailbird](https://www.getmailbird.com/) is one such email client and we would love to be added to the list if at all possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b91bd7f-7001-8c42-1861-9a62cccbf001
* Version Independent ID: 0758cd4d-14e6-e39a-8aff-8ffd71c0c6a3
* Content: [Microsoft 365 Client App Support — Modern Authentication - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-client-support-modern-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-client-support-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-client-support-modern-authentication.md)
* Service: **office 365 administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@mol This page lists Microsoft-provided clients and cloud services that support Modern Authentication. It is not intended to list clients and cloud services for other software providers. Sorry.
