### ISSUE TITLE
what are the certain scenarios when we see traffic on vpn adapter even if split tunnel is configured for deny the office365 data?

### ISSUE THREAD

**Issue by arunkumar4003** [MicrosoftDocs/microsoft-365-docs#2627]
[Enter feedback here]
https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b783ee-9449-56db-3abd-f17dcf6b5d54
* Version Independent ID: d2146ff5-4248-12ec-a873-c951220aaa14
* Content: [Implementing VPN split tunneling for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
@arunkumar4003 - sorry it took so long to get back to you on this issue. If this is still an open question, can you provide a little more context?

**Comment by arunkumar4003** [comment]
The issue related to this topic went on hold. So we are not actively working on it.

**Comment by arunkumar4003** [comment]
Closing the topic for now.
