### ISSUE TITLE
How to enable the S/MIME on a computer without joining domain or Azure AD?

### ISSUE THREAD

**Issue by akklaw** [MicrosoftDocs/microsoft-365-docs#2629]
[Enter feedback here]
I am trying to get a computer working with S/MIME on Chrome and Edge, but my computer is not joining any domain.  What should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e106b4-4d03-6027-39ed-711e3949aef8
* Version Independent ID: ff0ca4b3-2583-51dc-24ce-ac4cfaa12eb0
* Content: [Configure S/MIME settings - Exchange Online for Outlook on web - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@akklaw Thank you for your feedback. Please note that it is a prerequisite to have a domain-joined machine to be able to use S/MIME on chrome and/or Edge.

Considerations for new Microsoft Edge (Chromium-based) - 
https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app?view=o365-worldwide#considerations-for-new-microsoft-edge-chromium-based

Considerations for Google Chrome - 

https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app?view=o365-worldwide#considerations-for-chrome


If you have issues having it domain joined, You may want to talk to Microsoft support as both effectively requires domain-joined computers.

Hope this helps!

@yogkumgit There is no changes required in the document as both Chrome and edge need Domain joined machines to enable S/Mime. Please proceed with closure

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @akklaw Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
