### ISSUE TITLE
eDiscovery - Export Content Search results - Skipped Items

### ISSUE THREAD

**Issue by LaPhi** [MicrosoftDocs/microsoft-365-docs#2638]
_**Skipped Items** When you export search results from SharePoint and OneDrive for Business sites, the export will usually include a skipped items report (SkippedItems.csv). The items cited in this report are typically items that won't be downloaded, such as a folder or a document set. Not exporting these types of items is by design. For other items that were skipped, the 'Error Type' and 'Error Details' field in the skipped items report show the reason the item was skipped and wasn't downloaded with the other search results._
[https://docs.microsoft.com/en-us/microsoft-365/compliance/export-search-results?view=o365-worldwide](url)

From my understanding (Core eDiscovery). Empty folders from a SPO Document Library are not created at export. Filled folders are created. 
Please can you add this detail to the documentation and describe it a little bit more detailed? Questions from the Auditors/Lawyers are very precisely about this topics and it´s not 100 % clear in the documentation.

**Comment by markjjo** [comment]
@LaPhi Can you please add a little more detail about what you're looking for and how it's related to skipped items? What details are you looking for? What exactly are the questions about this that you're receiving from Lawyers/Auditors? Is there an expectation that an empty folder from a doc library should be exported?

**Comment by markjjo** [comment]
@laphi Also, since your are internal Microsoft, you can send email directly to me about this issue.

**Comment by yogkumgit** [comment]
@LaPhi Hope you are following the given advise. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
