### ISSUE TITLE
Article up to date

### ISSUE THREAD

**Issue by geneagoe** [MicrosoftDocs/microsoft-365-docs#264]
Hello,

Is this article still up to date? By going in M365 Portal, App management, we can deploy Office C2R on 64-Bit Architecture. 

Thanks,
George  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb1be80-0fd7-30ea-8829-52638a71e7a7
* Version Independent ID: e069acfc-c11a-2382-b548-a2c74c3db340
* Content: [Prepare for Office client deployment by Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/prepare-for-office-client-deployment)
* Content Source: [microsoft-365/business/prepare-for-office-client-deployment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/prepare-for-office-client-deployment.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@geneagoe  - I am looking into this.

**Comment by Sirkkuw** [comment]
@geneagoe apparently it is up to date - 32-bit is recommended or default.
