### ISSUE TITLE
Insert notes for hyperlinks not working

### ISSUE THREAD

**Issue by PowerShellPat-MYOB** [MicrosoftDocs/microsoft-365-docs#2642]
When navigating to hyperlinks in important sections, the pages are not found:

![image](https://user-images.githubusercontent.com/61482500/90573555-0b8bb400-e1fa-11ea-9fbc-afd6fb7c4cdf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2a332c-34ed-49fd-519a-4df38e9f4f60
* Version Independent ID: 19968ae0-b43e-d02d-fee3-14da766c7832
* Content: [Investigate malicious email that was delivered in Office 365, Find and investigate malicious email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@PowerShellPat-MYOB THank you for your feedback. We have made changes to the document by fixing the links via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2655

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PowerShellPat-MYOB Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
