### ISSUE TITLE
Change default action for "Anti-ransomware rule: warn users" from Notify to Prepend a Disclaimer

### ISSUE THREAD

**Issue by gregbnz** [MicrosoftDocs/microsoft-365-docs#2643]
Setting the "Notify" action for the transport rule "Anti-ransomware rule: warn users" results in double-up emails that confuse recipients and do not provide a clear message about the action required.

Instead, I would recommend this is changed to "Prepend a Disclaimer" so that the warning is stamped onto the original email message, making it clear what content the warning applies to, and providing a more familiar experience to the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6041d7c1-58b2-84db-32b8-928d2efb9319
* Version Independent ID: 004304b1-8e37-95e8-5967-b201176f2b5c
* Content: [Top 10 ways to secure Microsoft 365 for business plans - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#ransomware)
* Content Source: [microsoft-365/admin/security-and-compliance/secure-your-business-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/secure-your-business-data.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gregbnz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
