### ISSUE TITLE
Add notes on moving OneNote files

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/microsoft-365-docs#2644]
Add information about moving OneNote files.  One person noted that the OneNote importer app did not work for them in a business account 
https://answers.microsoft.com/en-us/msoffice/forum/all/migrating-one-note-from-a-private-microsoft/53444b35-1519-45c2-ac3d-facbdd314ded 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b274939b-2cc7-5f9d-c3da-dd254fd68a4d
* Version Independent ID: 45939253-ed6a-e985-5b8f-3600f3e54eda
* Content: [Transfer data manually between two accounts - Microsoft 365 admin](https://docs.microsoft.com/en-ca/microsoft-365/admin/get-help-with-domains/transfer-data-manually?redirectSourcePath=%252fen-ie%252farticle%252ftransfer-data-manually-between-two-office-365-accounts-7dc5d983-84b2-4802-bef0-602ae1780a42&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/transfer-data-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/transfer-data-manually.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Ronsss Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Ronsss** [comment]
Right, thanks.
