### ISSUE TITLE
Finding the products one user has licensed with Powershell

### ISSUE THREAD

**Issue by stephent122** [MicrosoftDocs/microsoft-365-docs#2645]
As an administrator I would like to find out what products a user has licensed not what products are available on the tenant.

A code example to do that would be welcome particularly since matching short codes to products is a opaque process with what appears to be unnecessary complexity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc0555a1-2410-5679-03f3-e5768a1dc9cd
* Version Independent ID: e3d2444e-22f6-f697-03a4-9edb8226b72e
* Content: [View Microsoft 365 licenses and services with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@stephent122 Thank you for your feedback. This document is more specific to Microsoft 365 licenses and services available in the tenant. For powershell cmdlets on checking this for individual accounts, Please Visit https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-account-license-and-service-details-with-microsoft-365-powershell?view=o365-worldwide

You can use these commands to list the licenses that are assigned to a user account.

$userUPN="<user account UPN, such as belindan@contoso.com>"
$licensePlanList = Get-AzureADSubscribedSku
$userList = Get-AzureADUser -ObjectID $userUPN | Select -ExpandProperty AssignedLicenses | Select SkuID 
$userList | ForEach { $sku=$_.SkuId ; $licensePlanList | ForEach { If ( $sku -eq $_.ObjectId.substring($_.ObjectId.length - 36, 36) ) { Write-Host $_.SkuPartNumber } } }


Thanks again for your feedback.

@yogkumgit  I have provided the required information and there are no changes required in this document. Please proceed with closing this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @stephent122 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
