### ISSUE TITLE
Permissions for Compliance Center

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2648]
[Enter feedback here]

This pages is focused on the old Security and Compliance center at protection.microsoft.com. Please provide a similar page that is focused on the Compliance center at compliance.microsoft.com
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e7332f-6c1d-19cf-dc71-4cebaa93c1cc
* Version Independent ID: a8e4bd77-725f-af7a-63bc-95d8ea92f554
* Content: [Give users access to the Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/grant-access-to-the-security-and-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/grant-access-to-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/grant-access-to-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@DeanGross  While the PR was merged. The Author thinks t  we likely need a new and separate page for granting permissions to the Security Center and also the Compliance Center, and we can cross-link between them all. That way, when the Security & Compliance Center ultimately goes away, we can just eliminate the topic without any impact on the Security Center or Compliance Center topics. You will soon see a new document covering this topic.

@yogkumgit THe PR was merged by Chris and we are likely to create a new document to cover this topic shortly. Please proceed with closing this issue for now.

Thanks
Sri

**Comment by DeanGross** [comment]
Thanks, I agree, the permissions for these centers are very complicated and anything that can be done to simplify the instructions will be greatly appreciated.  It would be very helpful if there was consistent use of security trimming, sometimes we can attempt to do something only to find out when we get to the Save step that we don't have the right role assigned and the messages do not always clearly identify which role is needed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
