### ISSUE TITLE
Please remove obsolete SEEmail document/link

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/microsoft-365-docs#2653]
[Enter feedback here]
This doc is old and inaccurate - please delete the line:

**Office 365: SEEMail Integration and Reference Architecture (additional Microsoft NZ guidance on cloud service adoption)**

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e44739-0adf-8948-9527-c8d8b3bddf03
* Version Independent ID: eb4ab4fb-9e55-c91e-0045-553045172377
* Content: [New Zealand Government Cloud Computing Security and Privacy Considerations - Microsoft Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/offering-nz-cc-framework-nz?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-nz-cc-framework-nz.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-nz-cc-framework-nz.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@PeteHaigh-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2660 and Once the author approves and merges the PR the document will be modified.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PeteHaigh-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
