### ISSUE TITLE
PDF for Identity and device protection for Office 365 and File Protection Solutions in Office 365

### ISSUE THREAD

**Issue by tfurstms** [MicrosoftDocs/microsoft-365-docs#2658]
Hello - Looking to confirm that the PDFs on this page for "Identity and device protection for Office 365 " for the "File Protection Solutions in Office 365" are the latest versions. 

- "Identity and device protection for Office 365" has 2018 year in the footer of the document. 
- "File Protection Solutions in Office 365" has 2017 year in the footer of the document. 

The content in both PDFs appear to be current but people have asked if this is a current/latest revision of the document due to the older dates in them. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5a37de-78a2-8e22-835f-24ad600d0f90
* Version Independent ID: 1a137731-f3b5-27b4-33b2-5c537a77f018
* Content: [Identity and device access configurations - Microsoft 365 for enterprise - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-policies-configurations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-policies-configurations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-policies-configurations.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@tfurstms Thank you for your feedback. The document is up to date and needs no changes. For the dates in the PDF, I have sent an email cloudadopt@microsoft.com for that to be modified whenever possible. for any feedback about the PDF documentation, you can also email cloudadopt@microsoft.com.

Hope this helps!


@yogkumgit There is no changes required to the parent document, I have emailed the concerned team for changes in the dates in PDF. This issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tfurstms Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
