### ISSUE TITLE
Adding Endpoint DLP to this page

### ISSUE THREAD

**Issue by tfurstms** [MicrosoftDocs/microsoft-365-docs#2659]
Hello - This page is a great overview of what is possible. As of 8/20/2020, Endpoint DLP is in preview but it would be great to see it called out on this page. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675e8944-c870-cf62-b324-e3a2876c8e27
* Version Independent ID: 40f60c6b-0258-f0f0-3294-609e78ae8a4e
* Content: [Protect information subject to data privacy regulation](https://docs.microsoft.com/en-us/microsoft-365/solutions/information-protection-deploy-protect-information?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/information-protection-deploy-protect-information.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/information-protection-deploy-protect-information.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@tfurstms Thank you for your feedback. We have added M365 Endpoint DLP to this page via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2685 Once this is approved by the author you will see the changed on the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tfurstms Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
