### ISSUE TITLE
"10 企業の Windows" needs to be replaced with "Windows 10 Enterprise"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/microsoft-365-docs#266]
https://docs.microsoft.com/ja-jp/microsoft-365/enterprise/windows10-infrastructure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49affecb-7a8a-87fd-7a41-fe244dee06a6
* Version Independent ID: 57d75d53-f22e-42b7-a46c-814429f3308a
* Content: [Windows 10 Enterprise infrastructure for Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/windows10-infrastructure)
* Content Source: [microsoft-365/enterprise/windows10-infrastructure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/windows10-infrastructure.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by lizap** [comment]
@robmazz - this is an issue with the localization, not the content. Is there a process to handle this kind of feedback? Unassigning Greg for now. Thanks!

**Comment by robmazz** [comment]
@lizap and @greg-lindsay - yes, please open a bug with loc so they can review. I'll email you guys contact.

**Comment by mypil** [comment]
@greg-lindsay - We would like to follow up on this. Do you have any updates? Thanks.

**Comment by greg-lindsay** [comment]
@ mypil this is the same issue as the other one, it's a loc issue. Why are you asking me?

**Comment by mypil** [comment]
@greg-lindsay - thanks for your response. Let me tag @samanthaw and @MollyMalone on this translation issue as they might be able to help address this or refer us to someone who can.
Looping in @AndreaBarr for FYI.

**Comment by greg-lindsay** [comment]
Can you please unassign me from this? I don't have permission to do anything at all in this repo.

**Comment by MollyMalone** [comment]
@hyoshioka0128 Thanks for reporting this. However we will not fix the over-translation of Windows 10 Enterprise at this time. It is a known issue that some of our Product names are being unnecessarily translated by the machine translation tool. We are investigating a tool solution to fix these issues. At this time we can not fix each issue individually.

**Comment by hyoshioka0128** [comment]
@MollyMalone Thanks.
