### ISSUE TITLE
Deadish link

### ISSUE THREAD

**Issue by richpi** [MicrosoftDocs/microsoft-365-docs#2661]
Azure PCI DSS 3.2.1 Responsibility Matrix link fails (links to technet page)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b95bd5-5663-90ab-f902-bab7887e4489
* Version Independent ID: 28d8c81c-5e29-b300-5b23-137e9692940e
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-pci-dss?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-PCI-DSS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@richpi - thanks for the feedback. Link updated to Azure Blueprint for PCI-DSS 3.2.1 (https://docs.microsoft.com/azure/governance/blueprints/samples/pci-dss-3.2.1/).
