### ISSUE TITLE
*.outlook.office.com is listed on ER Yes and ER No

### ISSUE THREAD

**Issue by abdielnino** [MicrosoftDocs/microsoft-365-docs#2662]
Please verify the end point: *.outlook.office.com, it is really under ER or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@abdielnino Sorry for my delayed reply. The differences in IDs 5, 6, and 8 for the *.outlook.office.com endpoint are the destination TCP ports. Ports 143, 993, and 995 are optional and ER. Ports 443 and 80 are default and not ER. Hope this helps. Thanks for your question.

**Comment by abdielnino** [comment]
@JoeDavies-MSFT , the difference is with the **ID 1:** *.outlook.office.com under 80 and 443 ports with **ER=Yes** and the ID 8: *.outlook.office.com under 80 and 443 ports with ER=No.
I'm Customer engineer (former PFE) in Microsoft, and one customer ask me these because they are implementing an Proxy PAC, obviously under our web services everything it is OK, but if we look these list is not pretty clear if the *.outlook.office.com endpoint is under ER or not. Thank you!

**Comment by abdielnino** [comment]
@JoeDavies-MSFT , the difference is with the ID 1: outlook.office.com under 80 and 443 ports with ER=Yes and the ID 8: *.outlook.office.com under 80 and 443 ports with ER=No.
I'm Customer engineer (former PFE) in Microsoft, and one customer ask me these because they are implementing an Proxy PAC, obviously under our web services everything it is OK, but if we look these list is not pretty clear if the *.outlook.office.com endpoint is under ER or not.

BTW, our https://docs.microsoft.com/en-us/microsoft-365/enterprise/managing-office-365-endpoints?view=o365-worldwide#pacfiles
PAC File results on *.outlook.office.com and outlook.office.com, both in the exception to be used DIRECTLY, so if somebody based the PAC file creation on the https://aka.ms/o365ips the endpoint with the ER=No will not be included.

Thank you.
Regards!
________________________________
