### ISSUE TITLE
M365 Endpoint DLP license clarification

### ISSUE THREAD

**Issue by Sizzl** [MicrosoftDocs/microsoft-365-docs#2667]
Ref SKU/subscriptions licensing: Could we please qualify whether the Endpoint DLP item granted within Compliance / Information Protection and Governance SKUs would be in addition to a SKU that grants Defender ATP in the first place?

Naturally this doesn't need qualification with the M365 A5/E5 bundle, but Defender ATP isn't present in the Compliance / IPG SKUs, and with the exception of references to device onboarding, the documentation flow reads as if it could be optional (and if this is the case, it would benefit from clarification).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Sizzl Thank you for your feedback. I'm currently checking with the Author, will update you shortly.

Thanks
Sri

**Comment by chrfox** [comment]
HI @Sizzl 

Thanks for your comment. MDATP licensing is not required for Endpoint DLP.
