### ISSUE TITLE
Specify Stream in Mult-Geo 365 capabilites

### ISSUE THREAD

**Issue by djtrustgod** [MicrosoftDocs/microsoft-365-docs#2671]
Stream is not listed in the Microsoft 365 Multi-Geo capabilities.  Stream either does or does not have Multi-Geo capabilities.  Please indicate this in the Multi-Geo documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b890c9af-0bab-84c6-8b9d-1ee93cb4683f
* Version Independent ID: 98fddfad-754b-ef65-7f5f-5f8bd8f59004
* Content: [Administering a multi-geo environment - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/administering-a-multi-geo-environment?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/administering-a-multi-geo-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/administering-a-multi-geo-environment.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@djtrustgod Thank you for your feedback. We have Added the information as M365 Video portal - https://docs.microsoft.com/en-us/microsoft-365/enterprise/administering-a-multi-geo-environment?view=o365-worldwide#video-portal

In a multi-geo tenant, the O365 Video Portal is served only from default geo and all users will be redirected to that central portal url. Hence, the Remote Media Service (RMS) for that region will be used, as follows based on your central location.

Stream is currently available in the following regions:

North America, hosted in the United States
Europe
Asia Pacific
However, Stream is not yet available in the following regions that are currently supported for Microsoft 365 Video, therefore for these local instances, we will use the RMS that is in the closest supported region.

Australia
Canada
India
United Kingdom

Hope this Helps!

@yogkumgit There is no changes required in the documentation. Please proceed with closure.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @djtrustgod Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
