### ISSUE TITLE
Hi! The 365 Usage Analytics is good! But the docs is not correct I think?

### ISSUE THREAD

**Issue by emwes** [MicrosoftDocs/microsoft-365-docs#2672]
The description of the underlying dataset - accessible as an Odata resource at 'https://reports.office.com/pbi/v1.0/<tenantid> - is wrong: 
It lists 11 data tables, it's only 10 today?  The table below is not in the dataset anymore, is it? 

Tenant Office Licenses
------------------------
Contains data about number of Microsoft Office   subscriptions assigned to users
--
Contains end-of-month state data for a rolling   12-month period including the current partial month.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de44679b-998b-3de8-292b-d2993af9bad9
* Version Independent ID: 7fd9ecf7-0468-d01e-dcca-d18a19ebb7c2
* Content: [Microsoft 365 usage analytics data model - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics-data-model?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics-data-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics-data-model.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@emwes Thank you for your feedback. I don't see the option as well. I have modified the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2710 Once the author approves the document will be updated.

Thanks
Sri

**Comment by msbemba** [comment]
@emwes Thank you for the feedback. We received an update from the author and PG that all (11) data tables are available. In case it doesn't show up on your tenant, please contact Support via the need help option in the M365 admin center.

@yogkumgit The author has confirmed that PG recently updated the document and there are 11 data tables. So this issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @emwes Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
