### ISSUE TITLE
Unclear what happens to user data when new subscription has same or more services

### ISSUE THREAD

**Issue by dofzin** [MicrosoftDocs/microsoft-365-docs#2673]
While it's reasonable that user data will be deleted when a subscription ends, this article is not at all clear about what happens when the subscription expiration is due to moving from one subscription tier to another when the new tier provides the user with the same (or more) services. For example, if a user is switched from Microsoft 365 Business Basic to Microsoft 365 Business Standard (or from Standard to Premium), does the user still need to backup Exchange and OneDrive data (and if so, presumably then restore the data into the "new" subscription)? The logical assumption would be that the user data is not impacted in any way (same user, same services available, just a different subscription), but that may be a dangerous assumption. The article does not address this question, and implies that user data must always be backed up when a subscription expires (and when switching from one tier to another, the UI still will show the "old" subscription tier as expiring on a certain date). Some simple language such as "user data will always be preserved and no action need be taken for any individual service that is present in both an expiring subscription and a replacement subscription assigned to the same user" would provide much needed clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 848ce1e8-2d62-82f6-8be7-8bfc5b078ae0
* Version Independent ID: 545667a2-66ff-7318-ebee-f52443bb9b1f
* Content: [Back up data before changing plans](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/back-up-data-before-switching-plans?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/back-up-data-before-switching-plans.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/back-up-data-before-switching-plans.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@dofzin Thank you for your feedback. We have made changes to the document by adding a note. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2682

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dofzin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
