### ISSUE TITLE
Office 2013 Modern Auth Failing

### ISSUE THREAD

**Issue by RowanAdvisors** [MicrosoftDocs/microsoft-365-docs#2675]
I've setup the registry values as indicated in the article, but Modern Auth is failing back to basic auth.  The modern auth dialog pops up, but after entering an email address to login the basic authentication window pops up.  No error is displayed and fiddler doesn't report any http errors.

This is happening for both a standard release and targeted release tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac88f29-99a5-317d-2686-cc9534194a19
* Version Independent ID: 753c4eff-ddb3-6261-35f9-4a60b65d7147
* Content: [Enable Modern Authentication for Office 2013 on Windows devices - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@RowanAdvisors Thank you for your feedback. I tested it on an Office 2013 standard release and I was able to get the modern auth Pop-up. Hope you have the below registry key set to 1
HKCU\SOFTWARE\Microsoft\Office\15.0\Common\Identity\EnableADAL

If the registry key is set correctly, I'd recommend you contact Microsoft support Via the need help option in the M365 Admin center.

@yogkumgit There are no changes needed in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @RowanAdvisors Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
