### ISSUE TITLE
From where can one access the audit reports?

### ISSUE THREAD

**Issue by jmuehlenbein** [MicrosoftDocs/microsoft-365-docs#2677]
I've tested enabling auditing as an Information Management Policy but cannot figure out where to access the resulting audit reports. Can you please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b270c9f7-c829-a6ac-0390-59d43d87a2e8
* Version Independent ID: 8a03f50c-78c4-75cf-7117-b27fbda09d3f
* Content: [Create and apply information management policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-info-mgmt-policies?redirectSourcePath=%252fen-us%252foffice%252f8ccac9e4-3a50-49fa-a95b-d186032a6ee3&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-info-mgmt-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-info-mgmt-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@jmuehlenbein Thank you for your feedback. We have the Audit logs reports covered in other documents like the below as this one pertains to only Creating  and applying information management policies

Auditing reports -   https://docs.microsoft.com/en-us/microsoft-365/compliance/reports-in-security-and-compliance?view=o365-worldwide#auditing-reports

Search the audit log in the Security & Compliance Center - https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by jmuehlenbein** [comment]
I think this is still not clear as it’s implied that enabling auditing in the Information Policy provides data which is different from that provided in the Unified Audit Logs (which is already provided by default). If it’s the same audit data, why does this “option” exist?

**Comment by msbemba** [comment]
@jmuehlenbein I'm currently checking with the author and will update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@MSFTTracyP After enabling auditing as an Information Management Policy, Could you please help us to find the audit reports as this is different from the unified audit log? I have checked in the security and compliance center (Reports) but it isn’t found there.

Thanks
Sri

**Comment by yogkumgit** [comment]
@MSFTTracyP Please reply to this query. Thanks.
