### ISSUE TITLE
Opening app links (not http/https) on a mobile device

### ISSUE THREAD

**Issue by anthonychung14** [MicrosoftDocs/microsoft-365-docs#2678]
We've implemented a user flow that takes the user from their email client into their mobile app.

Tapping the link within the email opens a browser window that then attempts to open a location such as `app://`

While `app://` might be registered on the device, we've noticed ATP blocking this request from ever completing.

This [part of the docs](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp?view=o365-worldwide#to-view-or-edit-a-custom-do-not-rewrite-urls-list) seems to suggest that adding `app://` to the Safe Link policies list would work.

Or, would it be possible to simply disable [scanning URLs that come from a particular domain](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies?view=o365-worldwide#policies-that-apply-to-specific-email-recipients)?

I do not have ATP and am only surmising how it works based on the docs provided.

Thank you for your time and help!

**Comment by msbemba** [comment]
@anthonychung14 Thank you for your feedback. Can you provide more details on which document that you referring to? 

In general, I would suggest disabling scanning URLs or allow URLs to pass through that come from a particular domain. 

Thanks
Sri

**Comment by anthonychung14** [comment]
I am referring to [Safe Link Policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies?view=o365-worldwide#policies-that-apply-to-specific-email-recipients).

How do these policies interact with non-`http` urls? schemes such as `app://` instead of `http://` are commonly implemented in mobile application environments.

If we can allow a particular domain, such as `https//ourcompany.com` to open `app://` from a browser's redirect, this has sufficiently answered our concerns.

**Comment by msbemba** [comment]
@anthonychung14 Thank you for your feedback. Safe links work on HTTP URLs. If you add Https//ourcompany.com to do not rewrite list it should open app:// from a browser's redirect as it is excluded from  ATP Safe Links scanning.

Hope this helps!

Thanks
Sri

**Comment by anthonychung14** [comment]
@msbemba thank you for the clarification. this was immensely helpful

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @anthonychung14 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
