### ISSUE TITLE
Microsoft why do I need to signup to yet another site, login, etc with your Sharepoint help?  Anyway, at long last a clear set of instructions.  Just stop users having to access a million sites to get information please.

### ISSUE THREAD

**Issue by brettr-TSF** [MicrosoftDocs/microsoft-365-docs#2679]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb311ed9-a649-8f67-51ea-3789ad914b00
* Version Independent ID: 165a9d7e-25e6-d5e5-d960-acaa675e4400
* Content: [Collaborate with guests in a site](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-in-site?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-in-site.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-in-site.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@brettr-TSF Thank you for your feedback. Can you elaborate on which part of this document that you need information or modification to be done?

Thanks
Sri

**Comment by brettr-TSF** [comment]
Hi Sri

Very happy with the actual instructions provide.  For once the screen shots match what I see on my screen and the presentation is simple and straight forward avoiding “Microsoft terms”.   This is much appreciated.  The issue is we have SharePoint but find we have to create an account in GitHub to make comments.  Sadly, the account name can not be and email address and demands yet another password.  I not sure about you but tracking and remembering accounts and passwords is way put my mental ability nowadays.

Cheers Brett


Brett Russell
Chief Financial Officer

Tasmanian Seafoods Pty Ltd
P.O. Box 239
Smithton Tas 7330
(03) 6452 1275
Mobile No. 0419 374 971
Email : brettr@tasmanianseafoods.com.au<mailto:brettr@tasmanianseafoods.com.au>

**Comment by msbemba** [comment]
@brettr-TSF Thank you for the detailed explanation. Microsoft Documents are handled Via Github and it is necessary for the users to have a GitHub account to add/modify/merge items to the document. For security reasons,, you cannot use your M365 password and have to create another one. I'm glad that you have one now so you can provide feedback for us to improve the documentation. 


Hope this helps!

@yogkumgit There are no changes needed in the document and this issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @brettr-TSF Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
