### ISSUE TITLE
Easier way to resolve the problem listed in troubleshooting section

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/microsoft-365-docs#2681]
The solution to the problem noted on this page points to Configuration Manager documents and is super complicated. Isn't really relevant for most admins. Instead, running the following three commands is a much easier way to resolve the error by upgrading to TLS 1.2:

PS C:\> [Net.SecurityProtocolType]
		
PS C:\> [System.Net.ServicePointManager]::SecurityProtocol
		
PS C:\> [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12

I found this here:

https://office365itpros.com/2019/11/20/microsoft-releases-control-self-service-purchases/#comment-781

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@GitRomney Thank you for your feedback. We have added the syntax to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2718 . Once it is approved you will find the update in the live document.


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GitRomney Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
