### ISSUE TITLE
Microsoft 365 Apps usage report - data does not cover up to the last 24 to 48 hours

### ISSUE THREAD

**Issue by anlorint** [MicrosoftDocs/microsoft-365-docs#2683]
Dear Team, 

The official article below states the following: "The data in each report usually covers up to the last 24 to 48 hours."
However, based on what we've noticed in the past weeks, the Microsoft 365 Apps usage report gets updated only once per week, on Tuesdays. 
For example, today it shows the _data as of: Tuesday, August 18, 2020 (UTC)_
I would like to understand if there is an issue with the Microsoft 365 Apps usage reports, or if the information found in the article is inaccurate. 

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7957baf3-919b-fa91-073c-d71672282268
* Version Independent ID: 418a59f1-83bd-ff70-fbff-c3980f083ff8
* Content: [Microsoft 365 Reports in the admin center - Microsoft 365 Apps usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft365-apps-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/microsoft365-apps-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft365-apps-usage.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@anlorint Thank you for your feedback. I have modified the document to reflect the correct number which is the past 7 days. The same can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2717

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @anlorint Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
