### ISSUE TITLE
Limitation should be explained

### ISSUE THREAD

**Issue by TimAbmgf** [MicrosoftDocs/microsoft-365-docs#2684]
When I add 2 domains, the 1st = https://domain.com. While adding the 2nd domain http://domain.com.
The 1st entry is removed and replaced with the non S version of the URL.
also vice versus; if I add the non S 1st and then the HTTPS sencond, the non S disappears being replaced with the S version.

I see on this site the example of **asterics**.contoso.com/**asterics**
if this is the intent to cover both HTTPS and HTTP, by placing the *.    in front of the domain, the example should show some samples of HTTP://www.contoso.com  (w/o the S).

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac84f75-b6d9-9495-873a-8f87b90b8034
* Version Independent ID: 18369495-0e0f-e3e1-6945-0200790fd107
* Content: [Set up a custom do-not-rewrite URLs list using ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@chrisda  Gentle reminder, Kindly answer and help us in resolving this issue. Thanks.

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@TimAbmgf, apologies for the delay.

Can you confirm or deny if there is some type of automatic URL redirection going on that forces HTTP requests to HTTPS (i.e., 302 error redirection)?

I'm told that if there is no automatic redirection, then HTTP and HTTPS entries are treated separately. People with domains that don't automatically redirect don't experience the automatic replacement swap as you described.

**Comment by chrisda** [comment]
@TimAbmgf, the original topic is now gone and redirects to  <https://docs.microsoft.com/microsoft-365/security/office-365-security/safe-links#do-not-rewrite-the-following-urls-lists-in-safe-links-policies>, so I added the following text there:

> - If a URL uses automatic redirection for HTTP to HTTPS (for example, 302 redirection for `http://www.contoso.com` to `https://www.contoso.com`), and you try to enter both HTTP and HTTPS entries for the same URL to the list, you might notice that the second URL entry replaces the first URL entry. This behavior does not occur if the HTTP and HTTPS versions of the URL are completely separate.

Thanks for the feedback.

Closing
