### ISSUE TITLE
Is there a way to do this with the Azure Active Directory PowerShell for Graph module

### ISSUE THREAD

**Issue by socialsoft** [MicrosoftDocs/microsoft-365-docs#2687]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e0c0537-bbc1-02c8-7ae2-78646b2a2e98
* Version Independent ID: a9becd2e-5989-da88-8b6c-0e51476a21c7
* Content: [Disable access to Microsoft 365 services with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@socialsoft Thank you for your feedback. Unfortunately, it is not available in AAD Powershell for graph. However, you can Disable access to Microsoft 365 services while assigning user licenses using AAD Powershell for graph Module - Please see https://docs.microsoft.com/en-us/microsoft-365/enterprise/disable-access-to-services-while-assigning-user-licenses?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in the document. Have answered Justin's question and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @socialsoft Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
