### ISSUE TITLE
Can't get past Step 1.

### ISSUE THREAD

**Issue by the-epoch** [MicrosoftDocs/microsoft-365-docs#2689]
Step 1 ("1. In the admin center, go to the Settings > Org Settings.") seems inaccurate. 
Where is "Settings" in the Admin center? And where is Org Settings?  This is a Global Admin user logged in and have no idea where to find this.
The Settings cog (top right corner) just has the following option:
-  Themes
-  Language and Timezone
-  Password > change your password
-  Contact Preferences
-  Support Pin.

There is no "Org Settings" option in the Settings cog. Is there another Settings option you are referring to in the Admin center?
Why can't you keep your doco accurate??? Microsoft doco is atrocious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@the-epoch Thank you for your feedback. The settings menu in admin center is available in the left navigation pane

![image](https://user-images.githubusercontent.com/45987684/91500240-baa64a80-e8e0-11ea-8923-97d2f6f2aea9.png)

Hope this helps!

@yogkumgit There are no changes needed to the document, this issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @the-epoch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
