### ISSUE TITLE
Exchange Administrator required to access Custom Mailbox.

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/microsoft-365-docs#2692]
Article assumes that the _administrator_ has an "Exchange Administrator" role assigned via the O365 Admin Center. 
Administrators that do not necessarily have "Exchange Administrator" roles - like a "Security Administrator" (they are administrators too), defined solely in the Office 365 Security & Compliance Center, still sees the User Submissions page, but no "Custom Mailbox" tab. 
![image](https://user-images.githubusercontent.com/45165076/91291757-1a5d0280-e7c8-11ea-8ec3-21811a211737.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [Specify a mailbox for user submissions of spam and phishing messages - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jadesolis,I added Exchange Administrator to the permissions call-out.

Thanks for the feedback.

Closing

**Comment by jadesolis** [comment]
The following statement still does not appear accurate:
- Th option of Organization Management **OR** Hygiene Management in Exchange Online still doesn't grant access to the "Custom Mailbox" tab. 

In the absence an Exchange Online Administrator role, Organization Management **AND** Hygiene Management are **_both_** required in Exchange Online. 

The Organization Management (role group) is actually made up of  several other roles; it would have been more appreciated if the articled listed the minimum RBAC roles required in EOL
![image](https://user-images.githubusercontent.com/45165076/91529204-77c59080-e93b-11ea-9a2a-d1e3892b95b6.png)

**Comment by chrisda** [comment]
@jadesolis, I hear you, but we've found it easier to list the role groups (which, confusingly, are called 'roles' in Azure AD), because that's where you actually add/remove members. Sometimes, we'll say, "Access is controlled by the <blah> role, which is typically assigned to the <a>, <b>, and <c> role groups..." which I could potentially do in this case.

Membership in both the Organization Management AND Hygiene Management role groups in ExO should not be required. The Hygiene Management role group gives you the Transport Hygiene, View-Only Configuration, and View-Only Recipients roles. By default, all of these roles are already assigned to the Organization Management role group in ExO. There are only a small number of unrelated roles that aren't assigned to Organization Management by default in ExO (if memory serves: Address Lists, Mailbox Import Export, Mailbox Search, and Reset Password).

So what would you like the permissions blurb to say?

**Comment by jadesolis** [comment]
"Membership in both the Organization Management AND Hygiene Management role groups in ExO should not be required." - Apparently this does not hold true, hence the feedback.

**Comment by chrisda** [comment]
@jadesolis, let me put it another way: have you done any role group customization that would account for those three roles from Transport Hygiene not being assigned to Organization Management?

**Comment by jadesolis** [comment]
@chrisda No, and immaterial. 'Organization Management' is no the issue here.
As it stands, 'Hygiene Management' in itself doesn't give you access to the 'Custom Mailbox tab.'

**Comment by chrisda** [comment]
@jadesolis, I'll refer to my question a couple of posts ago: If the statement about permissions is still incorrect, what would you like it to say?

**Comment by jadesolis** [comment]
@chrisda I will refer to my response a couple of posts back:
In the absence an Exchange Online Administrator role, Organization Management AND Hygiene Management are both required in Exchange Online.

**Comment by chrisda** [comment]
@jadesolis, I did my own testing. I used a Global Admin to take these actions:

- I specified a reporting mailbox at <https://protection.office.com/userSubmissionsReportMessage>. If you don't do this step, no one, including Global Admins, sees the Custom mailbox tab at <https://protection.office.com/reportsubmission>.

- I added an ordinary user to the Organization Management role group in the Exchange admin center (EAC).
  - Custom mailbox tab on <https://protection.office.com/reportsubmission> = YES
  - Access to User submissions at <https://protection.office.com/userSubmissionsReportMessage> = YES

- I added a different ordinary user to the Hygiene Management role group in the EAC.
  - Custom mailbox tab on <https://protection.office.com/reportsubmission> = NO (entire page is blank)
  - Access to User submissions at <https://protection.office.com/userSubmissionsReportMessage> = NO (entire page is blank)

- I added a different ordinary user to the Organization Management role group in the Security & Compliance Center (SCC). 
  - Custom mailbox tab on <https://protection.office.com/reportsubmission> = NO
  - Access to User submissions at <https://protection.office.com/userSubmissionsReportMessage> = YES

  Adding this same user to the Hygiene Management role group in the EAC and logging off/on had no effect (same results).

- I added a different ordinary user to the Security admin role in the Microsoft 365 admin center (MAC).
  - Custom mailbox tab on <https://protection.office.com/reportsubmission> = YES
  - Access to User submissions at <https://protection.office.com/userSubmissionsReportMessage> = YES

- I added a different ordinary user to the Exchange admin role in the MAC.
   - Custom mailbox tab on <https://protection.office.com/reportsubmission> = NO (entire page is blank)
   - Access to User submissions at <https://protection.office.com/userSubmissionsReportMessage> = NO (entire page is blank)

  Adding this same user to the Organization Management role group in the SCC and logging off/on had no effect (same results).

I'll update both this topic AND the topic where you actually click on the Custom mailbox tab (<https://docs.microsoft.com/microsoft-365/security/office-365-security/admin-submission>) accordingly.
