### ISSUE TITLE
IPv6 support Teams

### ISSUE THREAD

**Issue by rdekramer** [MicrosoftDocs/microsoft-365-docs#2693]
MS Teams supports IPv6 however we do not state this in our docs. Could this page be updated? Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41916ef7-635a-80f9-914a-207040a3829e
* Version Independent ID: 1f372ebc-774b-a1f5-5e43-73b42f74b198
* Content: [IPv6 support in Office 365 services - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/ipv6-support?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/ipv6-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/ipv6-support.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@rdekramer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2711

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This issue can be closed as the PR is now merged successfully.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rdekramer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
