### ISSUE TITLE
KQL syntax for auto applied retention label

### ISSUE THREAD

**Issue by mishmishilicous** [MicrosoftDocs/microsoft-365-docs#2694]
Trying to come up with the best filter for auto retention to be set with.
What will be the best way to auto apply retention on a SharePoint site to not include non end user working data? files in site assets or style library etc.

I'm trying to just target documents, any files within working libraries and list items which may include attachments.
(ContentType:'Document' OR ContentType:'Item') AND -FileType:aspx
Above returns items like site icon, associated page design files etc.

Using IsDocument:1 clause does not return list items and also skips files stored in working libraries.

Can I restrict locations that are used in an sp site by default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a4716f6-31db-306c-2804-56591e3af7e6
* Version Independent ID: 8dfc13ff-3b6a-ba25-2911-db7a3dcd2e8a
* Content: [Automatically apply a retention label to retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-retention-labels-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-retention-labels-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-retention-labels-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks.

**Comment by cabailey** [comment]
@mishmishilicous  Checking, but by default, system files won't be retained so I don't think you need to worry about the query excluding these.  Is there a reason why you're using an auto-apply label here rather than a retention policy for the site, or apply the label as a default label if you want to apply the same retention settings to all documents in the site?

**Comment by mishmishilicous** [comment]
@cabailey, I'm using an auto applied label for newly added content to ensure initial retention is set. 
Later on content is labeled by end users with other provisioned labels thru the UI later in the life cycle.
When I open the site assets library I can see the label shows up on system files which makes sense since the content type is a match ("Document"). I've created the label and associated it into a retention policy. In the policy I list the sites I'm interested in for this auto applied label. I'm not sure what you meant by "rather than a retention policy for the site".

Regarding the second part of your answer, "apply the label as a default label..", Do you mean in specific locations like libraries (via library settings) is so, this is not answering the requirement I have.

The requirement is to ensure an initial retention is set. Users later on work and collaborate with the data. At a certain point the user will choose an appropriate label to set an accurate retention is set.

With that being said, I need to find a way to ensure that initial retention is set documents (ContentType:'Document'), list items (ContentType:'Item') including attachments and miscellaneous files that are stored within a library (like zip or what not).

**Comment by cabailey** [comment]
We took this offline so closing this GitHub Issue. But in summary, we determined the best workaround for your scenario was to exclude files you didn't want to retain in the Site Assets library and other default document libraries by using a KQL query such as NOT(DocumentLink:"<URL to Site Assets library>")  You're going to follow up with your TAM to file a DCR for a neater solution and I'll look to clarify in the docs exactly what is and isn't retained/deleted by default.
