### ISSUE TITLE
Update to reflect new Recoverable Items option

### ISSUE THREAD

**Issue by rhite-vp** [MicrosoftDocs/microsoft-365-docs#2695]
The Exchange Team announced a [new recoverable items procedure](https://techcommunity.microsoft.com/t5/exchange-team-blog/a-new-recoverableitems-experience-comes-to-exchange-online/ba-p/1505353) in July 2020.
Thanks!
Ron

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9d3d55-537e-52f4-72f6-c0879a1b595a
* Version Independent ID: ea130146-6bd6-348a-bc8f-4e65ad1ae987
* Content: [Recover deleted items in a user mailbox - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@rhite-vp Thank you for your feedback. 
If you want to use this new functionality you need to use the new (and in preview) admin center - https://admin.exchange.microsoft.com/#/mailboxes

Once this is available to all tenants (out of preview) the document will be updated.

CC: @JoeDavies-MSFT 

Thanks
Sri

**Comment by rhite-vp** [comment]
Good point. Thanks!

**Comment by msbemba** [comment]
@yogkumgit No changes required at the moment and the issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rhite-vp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
