### ISSUE TITLE
Stipulation unclear

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/microsoft-365-docs#2697]
"To analyze a user's data using Advanced eDiscovery, the user (the custodian of the data) must be assigned an Office 365 E5 license. Alternatively, users with an Office 365 E1 or E3 license can be assigned an Advanced eDiscovery standalone license. Administrators and compliance officers who are assigned to cases and use Advanced eDiscovery to analyze data don't need an E5 license."

Does this mean data custodians (users being investigated) can be assigned either an O365 E5 or an E1/E3 + Advanced eDiscovery add-on?

Does this also say Admins doing the investigation, e.g., Advanced eDiscovery Admin don't need any license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518cc4fa-16a4-9793-530f-fcc371273a2d
* Version Independent ID: f07fb0ad-85a3-7159-d9b1-77d188b3d5f0
* Content: [Set up users and cases in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-users-and-cases-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jebalert First, I would suggest that you look at the licensing requirements for Advanced eDiscovery 2.0, which you can find here: https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-advanced-ediscovery?view=o365-worldwide#step-1-verify-and-assign-appropriate-licenses

Here is some additional info about AeD licensing: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#ediscovery

and

https://docs.microsoft.com/en-us/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.xlsx

Advanced eDiscovery v1.0 (also called "classic") is being retired. More info about that retirement here: https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement?view=o365-worldwide#advanced-ediscovery-v10

To answer your questions: Yes, the users who are being investigated require an E5 license or an E1/E3 plus an appropriate add-on license.

Admins doing the investigation need to be licensed and have an account in your organization, but they don't need an E5 license or a compliance add-on license. For example, an E3 license would be sufficient.

Hope this helps.
