### ISSUE TITLE
My software and hardware

### ISSUE THREAD

**Issue by Verdinjoshua26** [MicrosoftDocs/microsoft-365-docs#270]
[Enter feedback here]
My software and hardware and the New developments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61842d32-48bb-c5cb-ba55-31b0ca31ad5f
* Version Independent ID: 89aaf135-d085-c17b-a33d-e756e0d6d8ba
* Content: [Data protection impact assessments](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-data-protection-impact-assessments)
* Content Source: [microsoft-365/compliance/gdpr-data-protection-impact-assessments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-data-protection-impact-assessments.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by robmazz** [comment]
@Verdinjoshua26 - not sure of your question about the topic, can you be more specific with your feedback? Thanks!

**Comment by mypil** [comment]
@Verdinjoshua26 - We would like to follow up on this. Can you please be more specific with your feedback? Please assist to provide more details as to what should be edited and/or included.

Thank you.

**Comment by mypil** [comment]
@Verdinjoshua26 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mypil** [comment]
@AndreaBarr - This issue can be closed. Thank you.
