### ISSUE TITLE
The ip ranges are NOT the latest, please keep the docs synced, thanks!

### ISSUE THREAD

**Issue by Code2Life** [MicrosoftDocs/microsoft-365-docs#2702]
[Enter feedback here]

https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
I didn't found the IP: **13.85.192.123** in the document above, but this IP is come from Graph Notification Validation Request!

it caused **plenty of** "Subscription validation request timed out" error in Graph SDK from our service.

I don't know if there are any other IPs which will send Graph Notification Validation Request, if so, please keep document SYNCED so that we could sync security group of our service, plz, plz, plz, thanks !!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Code2Life Not all of the IP addresses are listed. See this blog post for an explanation: https://techcommunity.microsoft.com/t5/office-365-networking/why-are-some-office-365-network-endpoints-provided-as-urls-only/m-p/310490#M97
Hope this helps.
