### ISSUE TITLE
Missing July Updates

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2703]
[Enter feedback here]
The page shows that it was updated near the end of August, but there is nothing shown for July. Please add the what's new information for July

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89486ebd-f4fa-9d07-ee93-d04fd8d41027
* Version Independent ID: 667019d9-aac6-f466-1605-651a800fc212
* Content: [What's new in Microsoft 365 compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @brendonb
* Microsoft Alias: **brendonb**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. I'm working with the author to get this updated as soon as possible.

Thanks
Sri

**Comment by msbemba** [comment]
@DeanGross  Sorry about the time taken. We have added the July updates now. 

@yogkumgit  This took longer than expected. The author has updated the document with July updates. Please proceed with closing the issue.


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DeanGross** [comment]
while that is helpful, it is now the end of September, what about August?

**Comment by msbemba** [comment]
@brendonb Could you also please add august updates to the document?
