### ISSUE TITLE
Missing Cards

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2704]
[Enter feedback here]
The documentation shows that many cards can be added to the home page, In my tenant, i only have the ability to add 2 cards to the home page, Is my tenant broken? do I need to open a support ticket. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed7ade2-b6c8-83db-2d20-e87ee7a3cb5d
* Version Independent ID: d0591610-bebd-22c9-aaae-d4c1c3ef2ff7
* Content: [Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/microsoft-365-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. I was able to test this and can add all the cards to the home page 

![image](https://user-images.githubusercontent.com/45987684/92037091-e2892880-ed8e-11ea-9a4e-821e56ec009c.png)

![image](https://user-images.githubusercontent.com/45987684/92037192-0d737c80-ed8f-11ea-9165-541477afcf05.png)

So this looks like an issue on your tenant and you may have to open a support ticket via the need help section on the admin portal.

Hope this helps!

@yogkumgit There are no changes required in the document as such and this issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @DeanGross Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it.
