### ISSUE TITLE
Third and fourth name servers need to be updated

### ISSUE THREAD

**Issue by marcbeacom** [MicrosoftDocs/microsoft-365-docs#2708]
Should the third and fourth NS be:
ns3.bdm.microsoftonline.com
ns4.bdm.microsoftonline.com

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c52d59a-7466-a5a8-7031-e4ea7b782f57
* Version Independent ID: e02a33bc-12c6-4192-cf3f-bcea567085c3
* Content: [Change nameservers to set up Microsoft 365 with any domain registrar - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@marcbeacom Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2747

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @marcbeacom Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
