### ISSUE TITLE
Bypass Clutter/Other Inbox - Transport Rule

### ISSUE THREAD

**Issue by robert5150** [MicrosoftDocs/microsoft-365-docs#2709]
On this page: 

New-TransportRule -Name <name_of_the_rule> -From "Payroll Department" -SetHeaderName "X-MS-Exchange-Organization-BypassFocusedInbox" -SetHeaderValue "true"

The above command is recommended to bypass the clutter/other folder, however the command says to create a transport rule:

-SetHeaderName "X-MS-Exchange-Organization-**BypassFocusedInbox**" -SetHeaderValue **"true"**

I dont understand why we would set the header to BYPASS the Focused inbox, when I want the message to go into the FOCUSED inbox. 

Thanks, 

Robert 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a29483-a070-ccc1-b064-176dfa49d5e9
* Version Independent ID: bad082c0-9ca2-0ade-6b1f-0ba5ac26017b
* Content: [Configure Focused Inbox for everyone in your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/configure-focused-inbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/configure-focused-inbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/configure-focused-inbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@robert5150  Thank you for the feedback. I had a similar doubt when I read this document first, however Focused Inbox is a feature that automatically evaluates incoming emails and directs them to two views: "Focused" and "Others". To make sure that emails are always delivered to the user's "Focused" inbox, you must create a transport rule to bypass the evaluation. The PowerShell cmdlet to do that would be New-TransportRule -Name <name_of_the_rule> -From "Payroll Department" -SetHeaderName "X-MS-Exchange-Organization-BypassFocusedInbox" -SetHeaderValue "true"

Hope this helps!

@yogkumgit  There are no changes required in the document and we can proceed with closure.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @robert5150 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.e in future also.
