### ISSUE TITLE
Get-HybridMailFlowDatacenterIps disagrees vehemently.

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#2713]
[Enter feedback here]
Guys, check this out....  the article has like 6 ranges, and this shows 30.   
![image](https://user-images.githubusercontent.com/10875667/91525043-76518500-e8b5-11ea-81f3-498f39d4a5ae.png)

And one subnet range is off.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue as it is a Highly Structured document. Thanks

**Comment by JoeDavies-MSFT** [comment]
@chrislehr From https://docs.microsoft.com/en-us/powershell/module/exchange/get-hybridmailflowdatacenterips, "This cmdlet has been deprecated and is no longer used." The addresses listed on https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide are the definitive list. Thanks for letting us know.
