### ISSUE TITLE
Add more information regarding "Purging the recoverable items folder" at Step 5.

### ISSUE THREAD

**Issue by serran0** [MicrosoftDocs/microsoft-365-docs#2714]
No helpful information on how to perform a New-ComplianceSearch with targeting only the Recoverable Items folder exist in the links provided at Step 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the cloud mailbox on hold Recoverable Items folder - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@serran0 Please see this github issue for a solution to scope the compliance search (and subsequently the purge action) to items in the Recoverable Items folder: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2598 We're working to update this article with this info.

**Comment by markjjo** [comment]
@serran0 FYI that we've updated Step 5 in this topic. Added info about using targeted collection script to obtain folderid of recoverable items subfolder and then use that value to scope the search to the recoverable items folder. Hope this helps.
