### ISSUE TITLE
Endpoint list needs updating or Maybe separate page for GCC

### ISSUE THREAD

**Issue by Matt-Mueller-MSFT** [MicrosoftDocs/microsoft-365-docs#2716]
The GCC Power Platform Endpoints/URLs are not included in this document, even though it states it is for Worldwide and GCC.  Maybe since GCC uses different URLs for the Power Platform it should be on a separate page from https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&source=docs#feedback.

Or other option is to add the GCC PowerPlatform URLs to the current page..

The GCC Endpoints can be found https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government#power-apps-us-government-service-urls

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue as it is a Highly Structured document. Thanks

**Comment by JoeDavies-MSFT** [comment]
@Matt-Mueller-MSFT Starting an internal email thread to discuss this issue. Thanks for letting us know.
