### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by helloitsliam** [MicrosoftDocs/microsoft-365-docs#2719]
Nothing major but the line "Classifies data for you, using one of the built-in classifiers or train a classier with your own content" needs to modified. The phrase "train a classier" should be "train a classifier".

Thanks

Liam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9616c17-a6cb-3b45-dbc6-07b4932bf7c7
* Version Independent ID: 4cb4c135-d8ae-8d44-985d-297374aab6f1
* Content: [Microsoft Information Protection in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/protect-information?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/protect-information.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/protect-information.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi Liam  Thanks for flagging this typo - don't know how we all missed it before!  Fixed now.

**Comment by helloitsliam** [comment]
Perfect. No worries at all.

Liam

On Aug 28, 2020, at 6:55 PM, Carol Bailey <notifications@github.com> wrote:

﻿

Closed #2719<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fissues%2F2719&data=02%7C01%7C%7Cdb565248d8ff42cc815508d84ba57de6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637342521429934613&sdata=Ua9nFQ9Zvruf1PgvSM1ESCTpdJBIm1sUAxla1F2eOZg%3D&reserved=0>.
