### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by RyanSmith-00** [MicrosoftDocs/microsoft-365-docs#2720]
[Enter feedback here]

Jump to the remediation article here. link is broken
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2a332c-34ed-49fd-519a-4df38e9f4f60
* Version Independent ID: 19968ae0-b43e-d02d-fee3-14da766c7832
* Content: [Investigate malicious email that was delivered in Office 365, Find and investigate malicious email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@RyanSmith-00 Thank you for your feedback. We have fixed the Comment and link on the Note to remediation article. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2720

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @RyanSmith-00 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
