### ISSUE TITLE
Administration 

### ISSUE THREAD

**Issue by LaiClaudio** [MicrosoftDocs/microsoft-365-docs#2722]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709fda6f-3a7d-92aa-e7ad-afb09cd47cda
* Version Independent ID: 991f7ce4-e3a8-e044-c3c5-82de3b8837d3
* Content: [Admin center overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-overview?view=o365-worldwide#who-has-admin-permissions-in-my-business)
* Content Source: [microsoft-365/admin/admin-overview/admin-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-overview.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@LaiClaudio Thank you for your feedback. Could you please provide more information on what modification or questions you have on this document?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @LaiClaudio We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by LaiClaudio** [comment]
So sorry but I get a few problems with the computer and I didn't have any time to replay.
I just try to understand my self how to spend time and learn all this work that you guys do.
is very hard for me because I'm Italian and is all in English.

**Comment by msbemba** [comment]
@LaiClaudio That is totally understandable. We are more than happy to help you in case you think the document needs modification. If you have any technical queries on how this works. I'd say the best way to handle that would be to contact technical support via the Need help option on the admin center. The technical support has multiple language options.

Thanks
Sri
