### ISSUE TITLE
apis.live.net EOL?

### ISSUE THREAD

**Issue by khilker15** [MicrosoftDocs/microsoft-365-docs#2725]
Line item 53 apis.live.net appears to be end of life, per https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/migrating-from-live-sdk?view=odsp-graph-online

Is this still a requirement for M365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@khilker15 Thank you for your feedback. We will work with the Author and let you know once the changes are complete.

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@khilker15 I have forwarded this issue to the product team that maintains the endpoints for this section of the article for their consideration of a future update. Thanks so much for letting us know.
