### ISSUE TITLE
Security Center OR Compliance Center?

### ISSUE THREAD

**Issue by dennish78** [MicrosoftDocs/microsoft-365-docs#2726]
The article mentions the Security & Compliance Center as a single admin center.
We have 2 admin centers: the Security Center and the Compliance Center. Which of the 2 does the article refer to? Please amend article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5bb1b82-5bde-ce65-ca17-9e982b030a5c
* Version Independent ID: 704d9708-5308-4b5d-0ffa-d6b31fa7d0f3
* Content: [Auto-forwarded messages insight - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dennish78, actually, for the purposes of this discussion, there are three admin centers from oldest to newest:

Security & Compliance Center <https://protection.office.com>

Compliance Center <https://compliance.microsoft.com>

Security Center <https://security.microsoft.com>

All three are equally alive and well. New features are still being added to the Security & Compliance Center.

At some point, as there becomes more parity between features in the SCC and the SC, we'll likely convert all of the SCC topic content (procedures, UI, etc.) to the SC.

**Comment by dennish78** [comment]
Hi Chris,
Good to know that, thanks.
It's weird then that the SCC is no longer a link in the list of Admin
Centers. We have a choice of SC and CC. Guess I'll add the SCC to my
bookmarks and patiently await its deprecation.
Perhaps you could add a link to this (Classic? Legacy?) Center in the doc
to help other admins who also no longer have a direct link from the Admin
Center.

**Comment by msbemba** [comment]
@dennish78 Thank you for the feedback. I have added the LInk to security and compliance center to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2739

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dennish78 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
