### ISSUE TITLE
How to restrict sending to max 20 x recipients outbound for user mailboxes and allow more for systems sending out.

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/microsoft-365-docs#2729]
[Enter feedback here]
![Q1](https://user-images.githubusercontent.com/60931858/91863918-8b3c6880-ec67-11ea-94a7-7e6db1992ffa.PNG)
I need to restrict the number of recipients for outbound email to 20 per message for 99% of my user mailboxes.

However I have systems that send using a SMTP server that connects to the on-prem Exchange server, these systems won't have a mailbox (anon senders)

How should I be configuring this policy for both cases? 

See pic attached.
As always Thanks a million for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ii-batman, I don't understand this statement:

> However I have systems that send using a SMTP server that connects to the on-prem Exchange server, these systems won't have a mailbox (anon senders).

How does that relate to **outbound** mail flow from the cloud, which is what outbound spam policies cover?

**Comment by ii-batman** [comment]
> @ii-batman, I don't understand this statement:
> 
> > However I have systems that send using a SMTP server that connects to the on-prem Exchange server, these systems won't have a mailbox (anon senders).
> 
> How does that relate to **outbound** mail flow from the cloud, which is what outbound spam policies cover?

Hi Chris, sorry for not being clear.

We have hybrid exchange setup - so system on-prem send email via the on-prem exchange servers which route out via 0365.
These systems don't have a mailbox - they just send via the on-prem servers.

I hope this helps - let me know.

**Comment by chrisda** [comment]
@ii-batman, I don't think that type of mail would be affected by outbound spam policies. You should be OK to configure the default outbound spam policy with the values you want for users.

**Comment by ii-batman** [comment]
OK thanks Chris.
Now my main question... how to configure that policy if I only want to allow 20 x recipients per email sent out?

**Comment by chrisda** [comment]
@ii-batman, outbound spam filter policies are limited to the limits that you see, and max number of recipients isn't one of them.

It looks like you'll need to use the _RecipientLimits_ parameter on the Set-Mailbox cmdlet or (as of very recently) _MaxRecipientEnvelopeLimit_ parameter on the Set-TransportConfig cmdlet. This is described in the following blog posts: <https://techcommunity.microsoft.com/t5/exchange-team-blog/customizable-recipient-limits-in-office-365/ba-p/1183228> and <https://techcommunity.microsoft.com/t5/exchange-team-blog/customizable-tenant-level-recipient-limits/ba-p/1571564>.

Relatedly, I need to update the Set-TransportConfig cmdlet topic to indicate that _MaxRecipientEnvelopeLimit_ is now available in Exchange Online.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for updating the documentation. @ii-batman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by HarrisburgUSysAdmin** [comment]
We do not have a default outbound spam filter in our tenant.  How can this be restored?
![SS](https://user-images.githubusercontent.com/52167303/101267616-9b615980-3728-11eb-93c2-ce1b0cb256f9.PNG)
