### ISSUE TITLE
More details about Secure Score info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2731]
[Enter feedback here]
Please provide  specific information about what licenses are need for each control to get automatic updates from Secure score. for the Configure External Sharing action,  I  am seeing "Your organization's O365 subscription doesn't support continuous Secure Score update for this action" and I don't know why we are getting this. The documentation does not provide enough information to troubleshoot. We have O365 E5 and EMS E5. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6713dbeb-b6cf-eaf3-58a9-ffb8a9b5e858
* Version Independent ID: 858c0b49-3ffa-7bb0-9a0c-4b81b89b08c9
* Content: [Microsoft Compliance Manager Overview - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-manager-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Hello, thanks for your feedback. That is an error that Secure Score will give when it's monitoring a service that a tenant doesn't have access to. I'll work with the engineering team to provide more clarity in the documentation, which will be updated later this month.
