### ISSUE TITLE
What does EOP stand for?

### ISSUE THREAD

**Issue by LeonardPeris** [MicrosoftDocs/microsoft-365-docs#2734]
In the docs, the abbreviation **EOP** is used in many places. Unfortunately it doesn't appear the doc discloses what it stands for. 

First appears on line 204.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@LeonardPeris Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2770

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @LeonardPeris Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
