### ISSUE TITLE
"Microsoft account as the Authentication method > Sign in" not available!

### ISSUE THREAD

**Issue by carloreggiani** [MicrosoftDocs/microsoft-365-docs#2737]
I'm trying to configure PowerBI App " Microsoft 365 usage analytics" following the document, but in my Authentication method there is not "Microsoft account" option!

Here the option to choose:

- Anonymous
- Basic
- Key
- OAuth2

Trying OAuth2 it is not working.

Carlo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/usage-analytics/enable-usage-analytics?WT.mc_id=365AdminCSH&view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@carloreggiani Thank you for your feedback. I tested this and The Microsoft account option is no longer available, Instead, you need to use OAuth2. I have updated the document accordingly via PR #https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2802

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @carloreggiani Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
