### ISSUE TITLE
Thanks for videos

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/microsoft-365-docs#274]
Today i heared about new ways for  deployemnt with new  microsoft 365 tool . and i have downloaded  required videos from youtube , then i combined in single file. Thanks to the demostration , i hope those vvideos are helpful .

But i could not able to see one video named "Value Discovery and Business Case"  , because ythere is no video. Please add video  as soon as possible and share the link .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbbe4414-f9a2-0843-cf37-7d501131d7e0
* Version Independent ID: 8899e600-a97d-1151-83da-87ccecaff444
* Content: [Modern Desktop Deployment Center](https://docs.microsoft.com/en-us/microsoft-365/enterprise/desktop-deployment-center-home)
* Content Source: [microsoft-365/enterprise/desktop-deployment-center-home.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/desktop-deployment-center-home.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by robmazz** [comment]
@RAJU2529 - thanks for the feedback, I'll get the Microsoft 365 content team to check the link. Look for an update later here.

**Comment by JGruszczyk** [comment]
There is currently no plans for a video for the value discovery and business case section but thank you for the feedback!
