### ISSUE TITLE
Link seems to be missing

### ISSUE THREAD

**Issue by mastood** [MicrosoftDocs/microsoft-365-docs#2741]
In the following paragraph it seems we are missing a link after the word see. 

Enable retrieval for modern attachment - use this control to include modern attachments or linked files in the collection for further review; read more about the new searchable field names that are available to group this content, see [document metadata fields in advanced ediscovery]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dac6d75-9258-1cb4-2eec-1c640cbdfef6
* Version Independent ID: abf1c8f8-7b34-578e-32ca-4cb0f877fa79
* Content: [Add search results to a review set - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-data-to-review-set?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/add-data-to-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-data-to-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mastood Thanks for the heads up. This link should point to this article: https://docs.microsoft.com/en-us/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery?view=o365-worldwide

I will fix the missing link.
