### ISSUE TITLE
CM1 fails to generate

### ISSUE THREAD

**Issue by sdickson02** [MicrosoftDocs/microsoft-365-docs#2742]
Hello, I've tried downloading and installing the new Lab Deployment Kit (2004) multiple times, and always get the same problem. CM1 seems to unpack, but it does not correctly register in Hyper-V. I don't get any errors during the installation, but CM1 is not available in Hyper-V after the install completes. I'm trying to use the Lab Deployment Kit specifically to test SCCM packages, so CM1 is critical. 

When I try to add it manually, it fails no matter which Import Type I choose, stating an error in the configuration file. This could easily be a problem with my own machine because I can't find any other complaints of the same issue, but the last version worked without fail.

![cm1](https://user-images.githubusercontent.com/43976554/92019881-2ab33700-ed0c-11ea-863d-3d65e3179349.png)

**Comment by denisebmsft** [comment]
Hello @sdickson02. Sorry you are running into an issue. Can you please tell us to which article(s) this issue applies? It will help us route the questions correctly.

**Comment by msbemba** [comment]
@sdickson02 Thank you for your feedback. I think you are referring to https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide

I'll download and deploy this today and let you know if there are any changes required in the documentation. Meanwhile, If this is not the correct document, let us know which one you are referring to.

Thanks
Sri

**Comment by sdickson02** [comment]
@denisebmsft @msbemba Yes that is the correct article, thank you! Apologies for not including it in my original post.

**Comment by msbemba** [comment]
@sdickson02 Thank you for your feedback. Per testing CM1 works (Unpack and register) and is available after the installation. I'd recommend you contact support via the need help option in the M365 admin center to fix the issue. If you think there are any modifications needed in the document(post troubleshooting) Please let us know.

@yogkumgit Per my testing this works so no changes are required in the document. Please proceed with closing this issue.

Thanks
Sri

**Comment by sdickson02** [comment]
@msbemba Thank you for your help! I'm afraid that I'm not an administrator for our organization, so I don't have access to our M365 admin center. I just have to use SCCM to deploy applications to lab computers, so I was installing this lab kit in order to test them. Is there another way to contact someone for help besides through the admin center? (Or maybe I'm misunderstanding what is required to access the admin center?)

**Comment by msbemba** [comment]
Thank you for your feedback. Only administrators can create a ticket and receive support. @yogkumgit  Do you have details on how to contact support via Phone/email?

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @sdickson02 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
Link: https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online
