### ISSUE TITLE
SharePoint Encryption Policy - PS Command Change

### ISSUE THREAD

**Issue by groves226** [MicrosoftDocs/microsoft-365-docs#2744]
The PS command example shown has "- Identity" in it.. this switch is no longer used for this command

Page URL and PS command below... **_bold text_** is switch that can be removed

https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide#create-a-data-encryption-policy-dep-for-each-sharepoint-online-and-onedrive-for-business-geo

Register-SPODataEncryptionPolicy **_-Identity <SPOAdminSiteUrl>_** -PrimaryKeyVaultName <PrimaryKeyVaultName> -PrimaryKeyName <PrimaryKeyName> -PrimaryKeyVersion <PrimaryKeyVersion> -SecondaryKeyVaultName <SecondaryKeyVaultName> -SecondaryKeyName <SecondaryKeyName> -SecondaryKeyVersion <SecondaryKeyVersion>

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide#create-a-data-encryption-policy-dep-for-each-sharepoint-online-and-onedrive-for-business-geo)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@groves226 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2772

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @groves226 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
