### ISSUE TITLE
does this apply to education tenant too ?

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/microsoft-365-docs#2750]
when i follow those step, i can't limit class creation, allowed users cant view the class option anymore
ive raised a microsoft ticket for that
thank you

**Comment by yogkumgit** [comment]
@jeffangama Please indicate which document your are referring to. Thanks

**Comment by yogkumgit** [comment]
@jeffangama We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
