### ISSUE TITLE
Security Administrator Permisisons in AAD

### ISSUE THREAD

**Issue by GuyPartridge** [MicrosoftDocs/microsoft-365-docs#2751]
Hi, it says here for the Security Administrator role group "However, it will be a member of the Security Administrators role in Azure Active Directory and will inherit the capabilities of that role".
Checking this, it is not the case. If I add a user to the role group they do not get added as a member of the Security Administrators role in AAD. If I log on as the user I do not have rights to do things a Security Admin would do such as access identity protection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions - Microsoft 365 Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@GuyPartridge, you're right. I think most of the information is there, but I think there's some miswording that's confusing.

Here are the required statements:

- By default, the Security Administrator role group in the SCC might appear to have no members.
- The Security Administrator role from Azure AD is assigned to this role group in the SCC.
- The role group in the SCC inherits the capabilities and membership of the Security Administrator role from Azure AD.
- You should update membership in Azure AD.
- Changes to the role group in the SCC (members or permissions) only apply to the SCC.

The table entry about Security Reader suffers from these same types if issues, so I updated them both accordingly.

Thanks for the feedback.

Closing
