### ISSUE TITLE
How would a customer leverage this?

### ISSUE THREAD

**Issue by scsiwuzzy** [MicrosoftDocs/microsoft-365-docs#2752]
While this is good to hear, how would I, the customer, leverage this in support of an Enterprise environment?  We support 80k+ users across 12 US states, the Philippines, India, Canada and the UK.  QOS/QOL is very difficult for an IT person in Texas to know what is happening with regards to performance and quality for users hundreds or thousands of miles away.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2592a784-244d-eab0-5e32-1f48f0f34289
* Version Independent ID: 91427338-7d3f-e819-9cbd-a5d38fb97f0b
* Content: [Microsoft 365 Monitoring and Self-Healing - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-monitoring-and-self-healing?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-monitoring-and-self-healing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-monitoring-and-self-healing.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@scsiwuzzy Thank you for your feedback. Microsoft Monitoring and Self-healing approach helps take humans out of the recovery equation.  Managed availability specifically provides a native health checking and recovery solution that monitors and protects the end user's experience through recovery-oriented action. So as a Customer, you are not required to take any action.

Hope this helps!

@yogkumgit There are no changes required to the document. Please close the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @scsiwuzzy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
