### ISSUE TITLE
Receiving DKIM signed messages docs are lacking technical detail

### ISSUE THREAD

**Issue by MartinSGill** [MicrosoftDocs/microsoft-365-docs#2753]
There is no real technical information here on why a DKIM message would be rejected (signature verification failed).

For example we send an email with a DKIM signature including signed headers `Date`, `From`, `Message-ID`, `Subject`, `To` and we get a message `dkim=fail (signature did not verify)` . We send an identical message with headers  `From`, `Subject`, `To`  and receive `dkim=pass (signature was verified)'. We tested using both relaxed and simple validation schemes.

Why is this happening? Does the exchange DKIM only support certain headers? Can you please ensure this is documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c4afdda-1981-4bea-4402-c852ebd0d7ae
* Version Independent ID: 4a8b424e-8e3a-af22-adfa-d6df989b5bd1
* Content: [Support for validation of DKIM signed messages - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/support-for-validation-of-dkim-signed-messages?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/support-for-validation-of-dkim-signed-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/support-for-validation-of-dkim-signed-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@MartinSGill Thank you for your feedback. DKIM supports all the headers you had mentioned like Date, From, Message-ID, Subject, and To. I would recommend you contact our support team via the need help option on the admin center to get this fixed /escalated to the product group if it is a BUG or an issue with your tenant. Post interaction with support if you think there is a change required on the document, let us know.


@yogkumgit There are no changes required in the document as such. Martin is requested to contact Microsoft support. 

Thanks
Sri

**Comment by MartinSGill** [comment]
Thanks @msbemba you are correct, we figured that it was a combination of things that led us to the wrong conclusion. Apologies.
