### ISSUE TITLE
When does OCR extract text from images in Advanced edisocvery?

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/microsoft-365-docs#2754]
[Enter feedback here]
The article says "When you add custodians and non-custodian data sources to a case on the Sources tab, all partially indexed items (like image files) from Microsoft 365 are processed to make them fully searchable. " Another article [here ](https://docs.microsoft.com/en-us/microsoft-365/compliance/configure-search-and-analytics-settings-in-advanced-ediscovery?view=o365-worldwide#optical-character-recognition-ocr) says : OCR will be run on image files that are added to review sets so that image text can be reviewed. Customers are confused as to when does text extraction from image happen in advanced eDiscovery? Before adding search results to review set or after adding search results to review sets. Clarification required please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eed7e93-b767-39bf-65e8-73d045e61e47
* Version Independent ID: a51b0660-d06d-5f49-47e7-e70a2b5f7e23
* Content: [Advanced indexing of custodian data - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/indexing-custodian-data?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/indexing-custodian-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/indexing-custodian-data.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo  Please reply and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@markjjo  Gentle reminder, Kindly answer and help us in resolving this issue. Thanks.

**Comment by markjjo** [comment]
@bubhat As per our internal discussion with the eDiscovery PM, the OCR processing behavior is this:

- When a custodian is added to a case, the Advanced indexing process will perform the OCR processing. That means a collection search against custodians will return hits against extracted text from an image.

- If an image file from additional data source that was searched in a collection search is returned in search results, OCR processing will be performed on that image file when it is added to a review set.

I will update the documentation accordingly.
