### ISSUE TITLE
Instructions and UI do not align; very common with Security and Compliance centers

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/microsoft-365-docs#2755]
The section "How to create an eDiscovery hold" does not align with what is experience in the UI at the address https://compliance.microsoft.com/ 

This is very common with any of the Security and Compliance or Security or Compliance admin centers. Microsoft 365 team seems to change things in those interfaces so often that no one can keep up. Update suggested.

Thanks as always!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7263ba97-4e79-7144-a9d4-5138fe228fa2
* Version Independent ID: 316e242e-7f37-592e-9c8f-e754b23a29ca
* Content: [Create eDiscovery holds in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-ediscovery-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-ediscovery-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@ckssaas Thank you for your feedback. I was able to follow the instructions and the UI is aligned. Could you please verify if you have the matching Licenses and Permissions?

You can check - https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-core-ediscovery?view=o365-worldwide for more information.

Thanks
Sri

**Comment by ckssaas** [comment]
Hi Sri,

Since eDiscovery search & export was available in the Security & Compliance center, and since this page doesn't mention licensing requirements, I moved forward with the instructions as if there weren't any licensing requirements. I suggest adding a "requirements" section/link at the top of the page. 

This would not have been as confusing if there weren't multiple eDiscovery tools and compliance admin centers named the same things, all performing the same functions but with different licensing requirements. Please close.

Thanks

**Comment by msbemba** [comment]
@ckssaas Thank you for your feedback. The licensing requirements are added to the previous page - (Get started with Core eDiscovery) -  as this page is exclusively created to highlight steps to create an eDiscovery hold. 
https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-core-ediscovery?view=o365-worldwide 



Hope this helps!

@yogkumgit There are no changes required in the document. Please close the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ckssaas Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
