### ISSUE TITLE
Update needed?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2756]
[Enter feedback here]

Microsoft has made many changes to their compliance tools over the past few years. Is there anything in this guidance that needs to be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f47362e-5ac2-badf-9a90-f9f7831e5767
* Version Independent ID: 2c5b4b0a-29ca-6d6c-121c-5d7a81d6ca7e
* Content: [Microsoft 365 NIST 800-53 action plan, priorities for the first 30 days, 90 days, and beyond - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/nist-action-plan?toc=%2Fmicrosoft-365%2Fsolutions%2Ftoc.json&bc=%2Fmicrosoft-365%2Fsolutions%2Fbreadcrumb%2Ftoc.json&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/NIST-action-plan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/NIST-action-plan.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by yogkumgit** [comment]
@BrendaCarter  Please reply and help us in resolving this issue. Thanks.

**Comment by BrendaCarter** [comment]
Hi Dean, thank you for checking in! I am looking to see if we can resource an update to these. Have these action plans been valuable? How have you used these?

**Comment by DeanGross** [comment]
I have not used this but I do have  several projects in my pipeline that are expected to need to be NIST compliant. I was doing some research and found this document. As an Elite Partner, We have been meeting with the MS Compliance Center/Compliance Manager Team to discuss collaboration.  We may be able to help get this updated if necessary

**Comment by yogkumgit** [comment]
@BrendaCarter  In the light of new information shared by @DeanGross can you answer and help us in resolving this issue. Thanks.

**Comment by BrendaCarter** [comment]
Hi @DeanGross, given the investments into Compliance Manager, do you think updating these action plans provides additional help? Or are these resources redundant?

**Comment by yogkumgit** [comment]
@DeanGross Please share your comment. Thanks.

**Comment by yogkumgit** [comment]
@BrendaCarter Thank you very much for digging deep into it.  @DeanGross We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
