### ISSUE TITLE
Date password expiry begins

### ISSUE THREAD

**Issue by sn131678** [MicrosoftDocs/microsoft-365-docs#2757]
Does it begin from the date a password change policy was enabled? Or does it begin from the date the users password was last modified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/misc/password-policy-recommendations?WT.mc_id=365AdminCSH&view=o365-worldwide#password-guidelines-for-administrators)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@sn131678 Thank you for your feedback. It does not begin from the date when the password change policy was enabled. the password still ages based on the pwdLastSet attribute.

More information can be found at -https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-sspr-policy


Hope this helps!

@yogkumgit There are no changes needed in the document. Please proceed with closure as the questions are answered.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sn131678 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
