### ISSUE TITLE
Update the content

### ISSUE THREAD

**Issue by Divya-RP** [MicrosoftDocs/microsoft-365-docs#2759]
[Enter feedback here]
Kindly add a reference/note under IMAP/exchange online: if using 3rd party application, recommended to download the Root CA and the Intermediate CA bundle on the application system. Referencing the certificate providers used by O365: https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-certificate-chains?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@Divya-RP Thank you for your feedback. We have added this to the related topics section of the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2795

Thank you
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Divya-RP Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Divya-RP** [comment]
@yogkumgit , kindly add a reference in https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams to the article: O365: https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-certificate-chains?view=o365-worldwide.

 if using 3rd party application, recommended to download the Root CA and the Intermediate CA bundle on the application system.
