### ISSUE TITLE
May-June report results

### ISSUE THREAD

**Issue by tbrowningcds** [MicrosoftDocs/microsoft-365-docs#2760]
The May/Jun report from AV Test gave Defender a 6 out of 6:

https://www.av-test.org/en/antivirus/business-windows-client/windows-10/june-2020/microsoft-windows-defender-antivirus-4.18-202513/

You might want to update this page with that result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0665c47f-53f5-bd90-bb22-c99650f2c0ff
* Version Independent ID: a832271a-63b1-71fe-043e-0e3910bb61e0
* Content: [Top scoring in industry tests - Microsoft Threat Protection - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/top-scoring-industry-tests?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/top-scoring-industry-tests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/top-scoring-industry-tests.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
This will be updated later today. Thank you!
