### ISSUE TITLE
The 

### ISSUE THREAD

**Issue by Matt-Mueller-MSFT** [MicrosoftDocs/microsoft-365-docs#2762]
[The link for worldwide on this page does not include GCC specific endpoints like the PowerApps and the Power Automate Endpoints, there is not a separate link for GCC.
The URLs for these can be found at the below link. My customer is looking for the associated IPs to allow in their strict networking restrictions. Does not see the IPs I am getting back from Pings to these URLs fit on the lists for Worldwide. 
https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government#power-apps-us-government-service-urls ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd333ae2-34f6-4afd-cdb1-db72303a5736
* Version Independent ID: 5fc52fe8-dade-b8b7-7126-c4e7dd902e62
* Content: [Office 365 IP Address and URL web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/microsoft-365-ip-web-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Matt-Mueller-MSFT Thank you for your feedback. We are currently checking with the author and will update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@kelleyvice-msft The IP’s Associated with Power Apps US Government service URLs are not updated. We do not see the IPs that we are  getting back from Pings to these URLs fit on the lists for Worldwide. The URL that needs update  :- https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7



Thanks
Sri

**Comment by kelleyvice-msft** [comment]
Looking into this.

**Comment by LauraWi** [comment]
These workloads haven't been onboarded to the service that populates this table. Does the information in this article help:
https://docs.microsoft.com/en-us/power-automate/limits-and-config#ip-addresses
