### ISSUE TITLE
Please, insert information about Teams Admin Center and Planning feature, instead of suggesting Skype calculator

### ISSUE THREAD

**Issue by Rodrigo30Horas** [MicrosoftDocs/microsoft-365-docs#2766]
Dear all,

As my title already said, please, remove the info for Skype calculator, and promote the Planning features and rich capabilities inside the Teams Admin Center portal. It is a amazing feature to predict how much bandwidth Teams will consume, and it is totally integrated to 365 best practices.

Thanks!
Rodrigo A. Dias (FTC)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 677e2ded-11ef-1bc1-6e41-d0826bbe20c4
* Version Independent ID: 81a18ad4-22ed-e97d-949d-2e969a69c91b
* Content: [Network and migration planning for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/network-and-migration-planning?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/network-and-migration-planning.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/network-and-migration-planning.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Rodrigo30Horas Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2834

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Rodrigo30Horas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
