### ISSUE TITLE
For Item 7, "Microsoft Account" should be changed to "OAuth2"

### ISSUE THREAD

**Issue by stuart2155** [MicrosoftDocs/microsoft-365-docs#2767]
Hi, 
On Item 7 for this page:

_7. On the next screen, select Microsoft account as the Authentication method > Sign in. If you choose any other authentication method, the connection to the template app will fail._

I think this is incorrect or outdated: "Microsoft Account" was not an option. User should select "OAuth2"

Options were "Anonymous, Basic, OAuth2"

OAuth2 worked for me and authenticated using my Microsoft Account

Thanks

Stuart Jacobs

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-GB/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@stuart2155 Thank you for your feedback. We will test this and update the document accordingly.

Thanks
Sri

**Comment by msbemba** [comment]
@stuart2155 Thank you for your feedback. I have another Pull Request for the same document. So I have added this fix as well to the PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2802

Thanks
Sri
