### ISSUE TITLE
Does Office Message Encryption provide confidentiality against an attacker able to intercept clear-text mail?

### ISSUE THREAD

**Issue by dtbullock** [MicrosoftDocs/microsoft-365-docs#2768]
Answer: No, it doensn't.  The attacker can simply follow the link in the first email, and get the OTP from the second email.

Followup question: does this make OME essentially useless?
Answer: yet it does.

Followup question: what could Microsoft actually do to protect email confidentiality?
Answer: send the OTP via a separate channel/factor, stupid!

Followup question: why does some guy on the internet have to point this out to the industry?
Answer: ???

**Comment by msbemba** [comment]
@dtbullock Thank you for your feedback. This looks more like a feature request/gap. This section of the document is to modify or edit Microsoft documents in general. To provide product feedback to the product group you can either use the Feedback channel on the M365 admin center or the Uservoice forum. (https://office365.uservoice.com/) 

@yogkumgit There are no changes required pertaining to Microsoft documents. Please close this.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dtbullock Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
