### ISSUE TITLE
ASP Version

### ISSUE THREAD

**Issue by timkittelberger-sits** [MicrosoftDocs/microsoft-365-docs#2769]
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '2.1.1' was not found.
  - The following frameworks were found:
      3.1.7 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=2.1.1&arch=x64&rid=win10-x64
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[2604] customerkeystore.dll' has exited with code -2147450730 (0x80008096).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide#install-software-prerequisites)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@timkittelberger-sits Thank you for your feedback. The prerequisite is to install .NET Core 3.1 SDK. Are you having trouble installing that? Could you please elaborate more on which part of the document needs modification?

Thanks
Sri

**Comment by timkittelberger-sits** [comment]
@msbemba: Thx for the reply. The error is coming if I try to open the root page localhost:5001 but if I open the key website it is showing the key so maybe the error is not relevant. The error message look like some of the commands need the old net core libs. I installed the 3.1 SDK and I will test further.

**Comment by msbemba** [comment]
@timkittelberger-sits Thank you for your feedback. You are correct as this required only 3.1SDK. If that doesn't work I'd recommend you contact our support team via the need help button on the admin center. 

In case you would like to make some modifications to the document post troubleshooting, let us know.

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @timkittelberger-sits Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
