### ISSUE TITLE
Global Settings

### ISSUE THREAD

**Issue by Bertug** [MicrosoftDocs/microsoft-365-docs#2773]
The feature is now under Global Settings. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b24a80e-c6fd-97e9-b251-b2cbe8509ba6
* Version Independent ID: 58029e4e-c992-c4c4-ee68-9cc70cbc67be
* Content: [Turn on Office 365 ATP - SharePoint, OneDrive, & Teams - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/turn-on-atp-for-spo-odb-and-teams?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/turn-on-atp-for-spo-odb-and-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/turn-on-atp-for-spo-odb-and-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Bertug Thank you for the feedback. The option to Turn on Office365 ATP is still available In the Security & Compliance Center, in the left navigation pane, under Threat management, choose Policy > Safe Attachments.

While there are multiple ways to achieve it, this option is still accurate to date. 

@yogkumgit There are no changes required in the document. Please close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Bertug Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
