### ISSUE TITLE
Content incorrect

### ISSUE THREAD

**Issue by abulooz** [MicrosoftDocs/microsoft-365-docs#2775]
On the page it says "In the admin center, select Users > Active users." but in my "admin center -> users" all I see is "All Users (preview) and there is no "User templates" option anywhere on the page :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a03342-9a4b-cf1d-9a3b-7bdee0fe6b09
* Version Independent ID: 260c8359-f319-0647-ab77-a594ec872b2b
* Content: [Create and use a template to add users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/create-and-use-a-template-to-add-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/create-and-use-a-template-to-add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/create-and-use-a-template-to-add-users.md)
* Service: **o365-administration**
* GitHub Login: @SharS
* Microsoft Alias: **v-sharos**

**Comment by msbemba** [comment]
@abulooz Thank you for your feedback.Are you on the new Exchange admin center or M365 Admin center? If we access https://admin.microsoft.com/AdminPortal/Home#/homepage --> Users-->Active Users-->User Templates are available

![image](https://user-images.githubusercontent.com/45987684/93008524-5a2b3480-f593-11ea-805c-a685df074521.png)

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  There are no changes required to the document. Please close this issue.

Thanks
Sri

**Comment by omarelanis** [comment]
Sorry I was using Azure portal rather than the 365 admin center, confusing as it doesn't mention in the article which one to use but I should have noticed it was in the parent directory of office 365 admin center for this article https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/create-and-use-a-template-to-add-users?view=o365-worldwide

The link I was using:
https://portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade/MsGraphUsers

Thanks for the quick answers!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @abulooz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
