### ISSUE TITLE
Does not give enough/any instruction on how to delete.

### ISSUE THREAD

**Issue by samuelleung83** [MicrosoftDocs/microsoft-365-docs#2776]
Although there is a title of "Find and delete suspicious email that was delivered", the article doesn't go into any detail about Deleting/Actioning the suspicious emails after they have been identified as threats.

Although it is simple enough without explanation, it would be good if each of the Actions were described in the article. As well as how to get back to the "Action Log" once an action has been executed. I still haven't found a way to get back to the Action Log once the pane is dismissed or closed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2a332c-34ed-49fd-519a-4df38e9f4f60
* Version Independent ID: 19968ae0-b43e-d02d-fee3-14da766c7832
* Content: [Investigate malicious email that was delivered in Office 365, Find and investigate malicious email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@samuelleung83 Thank you for your feedback. This document pertains only to finding and investigating Malicious email, Hence the wordings have been corrected via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2835.

Meanwhile for remediation, Please refer to https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365?view=o365-worldwide 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @samuelleung83 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
