### ISSUE TITLE
Link to TechNet Gallery

### ISSUE THREAD

**Issue by ianalderman** [MicrosoftDocs/microsoft-365-docs#2777]
Hey Team, some of the links here refer to the resource here https://gallery.technet.microsoft.com/Azure-Responses-to-CSA-46034a11.  This has a banner saying it will be retired.  Should this page be updated (and hopefully the excellent content on the Gallery moved to a new home)?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f8b874d-efda-92bc-e371-ea8cddb97025
* Version Independent ID: 4e8cde1e-c323-9b1e-f197-f57ee427d1b2
* Content: [Shared Assessments Program - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-shared-assessments?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-shared-assessments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-shared-assessments.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@ianalderman Thank you for your feedback. The Technet document has been migrated indeed, We have updated the same via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2777


The new link is https://azure.microsoft.com/en-in/resources/azure-standard-response-to-rfi-on-security-privacy-and-compliance/

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ianalderman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
