### ISSUE TITLE
Bad aka.ms URL

### ISSUE THREAD

**Issue by Loftys** [MicrosoftDocs/microsoft-365-docs#2778]
"Microsoft GDPR Data Discovery Toolkit at https://aka.ms/gdprpartners."
The URL takes you to MS homepage and not anything relating to the GDPR Data Discovery Toolkit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55211697-1a2f-bf38-8f77-5c9bd1e74fa6
* Version Independent ID: 5b549922-54b0-2216-10fb-60ea51d6fc55
* Content: [GDPR for on-premises file shares - Microsoft GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-for-on-premises-file-shares?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/gdpr-for-on-premises-file-shares.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-for-on-premises-file-shares.md)
* Service: **o365-seccomp**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Loftys Thank you for your feedback. I'll check with the author and update the broken link.

Thanks
Sri

**Comment by msbemba** [comment]
@MikePlumleyMSFT Need help with a correct AKA.ms link for Microsoft GDPR Data Discovery Toolkit at https://aka.ms/gdprpartners as it is broken. Could we please get the update aka.ms or the original link so that this document can be updated?

Thanks
Sri

**Comment by MikePlumleyMSFT** [comment]
@BrendaCarter do you know if the GDPR toolkit is still available?

**Comment by yogkumgit** [comment]
@BrendaCarter Please reply to this query. Thanks.

**Comment by yogkumgit** [comment]
@BrendaCarter Gentle reminder Please reply to this query. Thanks.

**Comment by BrendaCarter** [comment]
@robmazz do you know where the GDPR toolkit is or if it still exists?

**Comment by robmazz** [comment]
@BrendaCarter and @MikePlumleyMSFT - not aware of any current toolkit. Since most of the references relate to the Azure Information Protection scanner, maybe just link to the the AIP overview topic? https://docs.microsoft.com/azure/information-protection/deploy-aip-scanner

**Comment by MikePlumleyMSFT** [comment]
@yogkumgit let's update the link as robmazz suggests.

**Comment by msbemba** [comment]
Thank you @MikePlumleyMSFT . I have updated the link via PR#https://github.com/MicrosoftDocs/Compliance/pull/6

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Loftys Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
