### ISSUE TITLE
What about retention policies in Information Governance--Retention?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#2779]
These instructions are very different than the retention policies that can be setup in Security & Compliance/Information Governance/Retention.  Do retention polices setup in EAC as described here override those set up in Information Governance/Retention? Or the other way around?  Even the Retention Policies tab in EAC states, "You can now create a single retention policy in the Office 365 Security & Compliance Center..." so why should I be creating polices in EAC?  Having two different locations to create policies with different rules is very confusing. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@Canis-Lupis Thank you for your feedback. These are two places where you could create retention policies (EAC and Security& Compliance). In EAC you can only create policies pertaining to Exchange, whereas in Security and compliance you have options to create retention policies for more than one service like Exchange, SharePoint, Teams, etc. It's possible or even likely that content might have several retention policies and retention labels applied to it, each with a different action (retain, delete, or retain and then delete) and retention period. At a high level, you can be assured that retention always takes precedence over deletion, and then the longest retention period wins.

You can find more detals on the principles of retention, or what takes precedence -- https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#the-principles-of-retention-or-what-takes-precedence

Hope this helps!

@yogkumgit There are no changes needed in the document and the issue can be closed.

Thanks
Sri

**Comment by markjjo** [comment]
@Canis-Lupis Also, as per a primary goal outlined in the topic, you have to use MRM retention policies in the EAC to move items to archive mailboxes.
