### ISSUE TITLE
How to get the version of office installed on each device / activation?

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/microsoft-365-docs#2780]
Hi, 

This doc goes into the details of how to get a list of activations, but, it doesn't have details on how to get more info for each activation. 

Could this be added please?

https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft-office-activations?view=o365-worldwide

Thanks,

**Comment by msbemba** [comment]
@haneef95 Thank you for your feedback. The version information is unfortunately not available on the reports/usage page. The way to install Office and Track the version of Office installed on each device is to manage it through intune - https://docs.microsoft.com/en-us/mem/intune/apps/apps-add-office365

Hope this helps!

@yogkumgit There are no changes required in the document and this issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @haneef95 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
