### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Arkthos** [MicrosoftDocs/microsoft-365-docs#2782]
[Enter feedback here]
The page doesn't mention pre reqs on this implementation, as part of the entitlement management reqs you need P2 in the tenant but this is not mentioned here, also creating an access packahge requires to have Global admin or user admin roles in the directory but I cannot see mention of what permission I need to create the extranet.

The article should be more explicite on what is needed for this particular implementation so not to especulate and hit road ends along the way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f2ae19-dbe7-3249-0021-28e70482cf40
* Version Independent ID: 03d808da-f488-0588-ba1a-b001e3c25ebd
* Content: [Create a B2B extranet with managed guests](https://docs.microsoft.com/en-us/microsoft-365/solutions/b2b-extranet?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/solutions/b2b-extranet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/b2b-extranet.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Arkthos Thank you for your feedback. We have added the licensing requirements to this page as per your request and can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2823

There is a link that has been added to the document for Azure Active Directory Entitlement Management -https://docs.microsoft.com/en-us/azure/active-directory/governance/entitlement-management-overview. This has details pertaining to admin and non-admin access.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Arkthos Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
