### ISSUE TITLE
License requirements

### ISSUE THREAD

**Issue by sysadmin-scs** [MicrosoftDocs/microsoft-365-docs#2783]
Article states AAD P2 is required, and that it's available in Enterprise Mobility + Security E3, which is incorrect.

![image](https://user-images.githubusercontent.com/62264844/92524921-e84c9700-f1f0-11ea-8648-485e5fec9b6a.png)

I'd also like to confirm that Microsoft Defender Advanced Threat Protection is indeed a prerequisite. It seems that you should be able to run Microsoft Managed Desktop without it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0867814-bf53-5c19-72c0-af781820cd42
* Version Independent ID: be31f818-4114-5b40-d2fe-e06180cbf67d
* Content: [Prerequisites for Microsoft Managed Desktop - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-ready/prerequisites?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-ready/prerequisites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-ready/prerequisites.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@dannoakes can you advise?

**Comment by msbemba** [comment]
@sysadmin-scs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2822

MDATP is indeed a prerequisite to Provide detection, monitoring, alerting, and response to threats.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@sysadmin-scs One of our SME's will be providing a comprehensive update to the article shortly as he feels the edit is not 100% accurate.

**Comment by msbemba** [comment]
@yogkumgit  Since the SME is going to provide a comprehensive update. Please go ahead and close this issue.

Thanks
Sri
