### ISSUE TITLE
Client for which this does not currently work

### ISSUE THREAD

**Issue by greganth1** [MicrosoftDocs/microsoft-365-docs#2784]
There should be a section in the document or the FAQ to cover supported clients. The split-tunnel configuration covered works for desktop clients but does not work for Teams running in a browser.  Browsers where supported use WebRTC and the media stack call setup logic is different from that of the desktop client.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b783ee-9449-56db-3abd-f17dcf6b5d54
* Version Independent ID: d2146ff5-4248-12ec-a873-c951220aaa14
* Content: [Implementing VPN split tunneling for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel?view=o365-worldwide#howto-guides-for-common-vpn-platforms)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@greganth1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2837

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @greganth1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
