### ISSUE TITLE
Basic Authentication is still used

### ISSUE THREAD

**Issue by Enigma102083** [MicrosoftDocs/microsoft-365-docs#2785]
The GetFolderSearchParameters.ps1 script still uses Basic Auth and can't connect to Office 365 anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136c161f-13b8-fb62-01de-53b1219b5290
* Version Independent ID: f1843c14-29da-d831-c7ce-9e3f624a01ed
* Content: [Use Content Search for targeted collections - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-content-search-for-targeted-collections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-content-search-for-targeted-collections.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Enigma102083 Thanks for heads up. Scripts won't work with MFA. Please see github issue #1428 for a possible work around using trusted IPs. Here is another alternative: https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps

You can also try to remove the connection steps from the script, then connect to EXO powershell (to search for Exchange folder IDs) or SCC powershell (to search for document paths) and then run the script.
