### ISSUE TITLE
Cannot email feedback email

### ISSUE THREAD

**Issue by mrapoc** [MicrosoftDocs/microsoft-365-docs#2786]
Hi - when I email about my issue using my Office 365 address I get the following bounceback:

Your message to edindCSEengAdm@microsoft.com couldn't be delivered.
--
The group edindCSEengAdm   only accepts messages from people in its organization or on its allowed   senders list, and your email address isn't on the list.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce65739-6428-fc57-012c-a6741a051c6b
* Version Independent ID: 3341ac81-3e21-4e71-e4f7-3eff41db05b8
* Content: [About the Microsoft 365 Admin mobile app - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/admin-overview/admin-mobile-app?redirectSourcePath=%252farticle%252fe16f6421-2a1a-4142-bf9d-9846600a060a&view=o365-worldwide)
* Content Source: [microsoft-365/admin/admin-overview/admin-mobile-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-mobile-app.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@mrapoc Thank you for your feedback. I'm currently working with the author and the engineering team to fix this. 

Thanks
Sri

**Comment by msbemba** [comment]
@mrapoc The feedback emails need to be sent to feedback365@microsoft.com. I tested and it works. 

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes required as such in the document as per testing the email address works. Please close the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mrapoc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
