### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by martin-rublik** [MicrosoftDocs/microsoft-365-docs#2787]
src\customer-key-store\scripts\key_store_tester.ps1 is missing in github repo https://github.com/Azure-Samples/DoubleKeyEncryptionService/ could you please update the repo or the documentation?

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@martin-rublik Thank you for your feedback. I'm currently working with the author and will update this shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@KCCross We need help with updating another repo. key_store_tester.ps1 is missing in https://github.com/Azure-Samples/DoubleKeyEncryptionService/

This PS1 file is required to validate the deployment and key store settings. We need help from you to get this updated on the other repo https://github.com/Azure-Samples/DoubleKeyEncryptionService/

Thanks
Sri

**Comment by yogkumgit** [comment]
@KCCross Please reply to our query. Thanks.

**Comment by KCCross** [comment]
The file is there. You're looking in the wrong folder. 
src\customer-key-store\scripts\key_store_tester.ps1
