### ISSUE TITLE
Block clients that don't support modern auth question

### ISSUE THREAD

**Issue by robert-bunch** [MicrosoftDocs/microsoft-365-docs#2788]
[Enter feedback here]

This section is a little confusing to me. "Block clients that don't support modern authentication" yet the directions say to choose _**Mobile apps and desktop clients**_ which is listed under "Modern Authentication Clients" in the CA policy. Is this accurate? To me it seems as if we check "Mobile apps and desktop clients" under modern authentication and then we set Block access on this policy, it will block modern auth apps as well?

Conditions | Client apps | Choose Yes for ConfigureCheck **_Mobile apps and desktop clients_** and Other clients
-- | -- | --

Select the client apps this policy will apply to

**Modern authentication clients**

_Browser
Mobile apps and desktop clients_

**Legacy authentication clients**

_Exchange ActiveSync clients
Other clients_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0edb16f-03bd-e6f8-87e1-7fc713db726d
* Version Independent ID: 34252c76-c635-0fe0-e0fc-283d0e87d3b7
* Content: [Common identity and device access policies - Microsoft 365 for enterprise - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/identity-access-policies?view=o365-worldwide#block-clients-that-dont-support-modern-authentication)
* Content Source: [microsoft-365/enterprise/identity-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/identity-access-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@robert-bunch You are correct. This instruction has been corrected and will be published today. Thanks so much for letting us know.
