### ISSUE TITLE
The page appears to have been half updated to use Content Types but the changes not completed

### ISSUE THREAD

**Issue by andytuke-jisc** [MicrosoftDocs/microsoft-365-docs#2796]
In the information architecture section the columns used for the label auto assignment are of the type Managed Metadata.  The page suddenly pivots to talking about Content Types, which to be fair would be a better way to design the example solution in my opinion, before reverting back to using Managed Metadata columns in the described implementation.  Content types aren't actually used at all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38185ae9-6017-736a-adf2-1a6f62d4ae09
* Version Independent ID: 1f57cbcc-bdea-e712-2f35-d9282c133433
* Content: [Use retention labels to manage the lifecycle of documents stored in SharePoint - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/auto-apply-retention-labels-scenario?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/auto-apply-retention-labels-scenario.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/auto-apply-retention-labels-scenario.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please add your comment and help us in resolving this issue. Thanks.

**Comment by cabailey** [comment]
Not sure I understand this comment, assigning to @fredericlapierre who authored the original article

**Comment by cabailey** [comment]
Not seeing Fred's GitHub account available to assign - adding back @yogkumgit.  Fred is a Microsoft employee, so we can take this up with him internally, but he told him he saw no discrepancies in the article.

**Comment by yogkumgit** [comment]
@andytuke-jisc However there is no discrepancy in the article still Carol will take this up internally. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
