### ISSUE TITLE
Missing screenshot

### ISSUE THREAD

**Issue by drmarkrwarnes** [MicrosoftDocs/microsoft-365-docs#2797]
[Enter feedback here]

Under Step 3, list item 7, it states:

_For example, the following screenshot shows the parameter names from the sample CSV file for the employee resignation HR scenario shown in Step 1._

However, the screenshot is not present in the document.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b68cfa-058a-8536-fb6a-b54e8fffa626
* Version Independent ID: dbcba365-2858-8cff-4f30-8a8a0068ac71
* Content: [Set up a connector to import HR data - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/import-hr-data?view=o365-worldwide#step-1-prepare-a-csv-file-with-your-hr-data)
* Content Source: [microsoft-365/compliance/import-hr-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-hr-data.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@drmarkrwarnes Thanks for the heads up. I'll look into this. Until then, the screenshot would look something like the below. The point is that you have to map your csv column names to the required properties. 

![HRConnectorWizard3](https://user-images.githubusercontent.com/36746813/93119264-5b815d80-f676-11ea-9a4b-5f4d18697222.png)
