### ISSUE TITLE
Links to MS365 Controls please.

### ISSUE THREAD

**Issue by whoiskevinrich** [MicrosoftDocs/microsoft-365-docs#2798]
Page offers no direction on where to set options. A clear link at the top of the page would be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd1ebad6-d8d1-8973-7595-71cb8a50b833
* Version Independent ID: d1d565cb-2f31-c847-860e-513dcaefa123
* Content: [Email authentication in Microsoft 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/email-validation-and-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/email-validation-and-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/email-validation-and-authentication.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@whoiskevinrich Thank you for your feedback. Configure email authentication (with steps) are available in the document (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/email-validation-and-authentication?view=o365-worldwide#configure-email-authentication-for-domains-you-own) to set up DKIM, DMARC, and SPF. You need to access the link individually to configure.

Hope this Helps.

@yogkumgit There are no changes required in the document and this issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @whoiskevinrich Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
