### ISSUE TITLE
Missing License Type in Prerequisites

### ISSUE THREAD

**Issue by Staja** [MicrosoftDocs/microsoft-365-docs#2808]
Prerequisites section should also include A5 license as per
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37494e01-d673-2fcb-4a86-baecb716120e
* Version Independent ID: 1f46b90e-3691-5b81-9f9e-ce3c94f18a1d
* Content: [Get started with data classification - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Staja Thank you for your feedback. We have made changes to the prerequisites section of the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2808

Once the Author approves the changes will be merged.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Staja Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
