### ISSUE TITLE
Reference to proxycalc missing and its trigger after domain change

### ISSUE THREAD

**Issue by paweber8** [MicrosoftDocs/microsoft-365-docs#2809]
Would it be possible to add in the troubleshooting guide for the domain verifications a reference to the fact that a change on a domain triggers the proxycalc process for the complete directory and users will see massive numbers of updates. Currently this is only described under [Reports and Monitoring](https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/troubleshoot-audit-data-verified-domain)

Thanks a lot for feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc96d989-29fd-363e-82b6-0dc3807be297
* Version Independent ID: 2a7ffa92-86b1-919d-6f97-ed0df2310bcd
* Content: [Find and fix issues after adding your domain or DNS records - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/find-and-fix-issues?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/find-and-fix-issues.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/find-and-fix-issues.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@paweber8  Thank you for your feedback. We have added a reference to Proxy calc to the related content section of this document. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2847

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @paweber8 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
