### ISSUE TITLE
What service plan is really needed for Endpoint DLP?

### ISSUE THREAD

**Issue by wbach82** [MicrosoftDocs/microsoft-365-docs#2810]
So i have a Tenant (O365 Developer) with 25 Microsoft E5 Developer which includes Service Plans for Information protection 1+ 2:

![image](https://user-images.githubusercontent.com/41477614/92922595-62219200-f436-11ea-9abf-e850062c7590.png)
 but Endpoint DLP rules are not possible/visible. 

![image](https://user-images.githubusercontent.com/41477614/92922645-72397180-f436-11ea-9701-73866e74fe3c.png)

What is the difference between the "normal" Microsoft 365 E5 and Microsoft E5 Developer. Which Service plan is missing in M365 Developer so that i can't use Endpoint DLP there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@wbach82 Thank you for your feedback. The name of the SKU that is missing in the M365 E5 developer is Microsoft Endpoint DLP.

![image](https://user-images.githubusercontent.com/45987684/93429504-e6fd2780-f8de-11ea-981a-1d8c47243e86.png)

Hope this helps!

@yogkumgit There are no changes required in the document. Please close the issue.

Thanks
Sri
