### ISSUE TITLE
Adding user

### ISSUE THREAD

**Issue by tabularjon** [MicrosoftDocs/microsoft-365-docs#2811]
Hello,

I am new to 365 and am administering users.

I added a new user xxx@mathsnoproblem.onmicrosoft.com.

I allowed the system to generate a password.

How do I send an invite?

I would expect to have found somewhere to enter the user’s email address for the invite, but this was not there. So how is this achieved?

The documentation on this page does not address this very basic how to. Other systems, such as Google provide a secondary email or recovery email facility which is used for this, but 365 seems to leave me totally in the lurch...

Thank you,

Jon Bearman
Head of IT
Maths — No Problem!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83719909-241b-2902-5ff1-496934da24e3
* Version Independent ID: d05e079d-f0d6-11ac-577c-f407cc49fcb7
* Content: [Add users and assign licenses - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/add-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/add-users.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@tabularjon Thank you for your feedback. This document pertains to only adding users and assigning licenses Via M365 Admin center. 

If you referring to Sending the user his password - We have it covered on the below document

https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/resend-user-password?view=o365-worldwide#resend-user-password

Hope this helps!

Thanks
Sri

**Comment by tabularjon** [comment]
Hi Sri,

Okay, great — thanks.
Kind regards,

Jon 



Jonathan Bearman
Head of IT
Maths — No Problem!

Office: 01892 537706  Direct: 01892 577101  Mobile: 07958 663493
www.mathsnoproblem.com <http://mathsnoproblem.com/>
 <https://twitter.com/MathsNoProblem>  <https://www.instagram.com/mathsnoproblem_/>  <https://www.facebook.com/MathsNoProblem/>  <https://linkedin.com/company/maths-no-problem>
Proud winners of:
The IPG Independent Publishing Awards, 2017–2018
The British Book awards, 2018

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in the document and the issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tabularjon Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
