### ISSUE TITLE
Use PowerShell to view outbound spam filter rules - Markdown missing quotation mark

### ISSUE THREAD

**Issue by Kickball** [MicrosoftDocs/microsoft-365-docs#2812]
The first code block under the Use PowerShell to view outbound spam filter rules heading is missing a closing quotation mark for the -identity parameter example.

`Get-HostedOutboundSpamFilterRule [-Identity "<RuleIdentity>] [-State <Enabled | Disabled]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide#use-the-security--compliance-center-to-create-outbound-spam-policies)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Kickball, thanks for the feedback. In the future, you can fix issues like this directly without opening a GitHub Issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks again.
