### ISSUE TITLE
More info required for parameters, please.

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#2814]
[Enter feedback here]
We have a former employee returning to our organization, JSmith.  He has been gone over 30 days but we put a retention on his mailbox and it does show up as an inactive mailbox.  So, we re-enabled his AD account (we have a hybrid environment) and his account has synced to O365.  O365 will not create a new mailbox for him because his ExchangeGUID is already in use on his old inactive mailbox, which is understandable.

However, when I try to recover his inactive mailbox back to his account,  I keep getting errors that the name (JSmith) is already in use. This doesn't make any sense; he's a returning employee so of course his account is going to use his name (and MicrosoftOnlineServiceID for that matter).  So I'm confused on how you recover a former employee's inactive mailbox to his account if his account can't actually  have is -Name and -MicrosoftOnlineServicesID parameters. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e8e1ab-8080-9c2f-d6af-97fc01b0a2c0
* Version Independent ID: d8debc69-c7bf-6e28-6e9f-8b7fae822dfd
* Content: [Recover an inactive mailbox - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/recover-an-inactive-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/recover-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/recover-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Canis-Lupis As per the topic, I assume that you are using either the DN or Exchange GUID to recover the inactive mailbox. If so, and you're still having issues, I would suggest that you open a ticket with MS Support.
