### ISSUE TITLE
Not complete info

### ISSUE THREAD

**Issue by omidhdp** [MicrosoftDocs/microsoft-365-docs#2820]
This page doesn't have any info on how to add storage using CSP, I was with Microsoft Tech call for 2 hours after I added the product through our CSP D&H, so we found out by ourself that it is per GB for each license and for 500GB we need to add 500 license from CSP, 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@omidhdp Thank you for your feedback. I verified both on CSP and Direct Microsoft,  You are correct the license count is per GB for Extra storage space and as mentioned in the document you need to enter the number of GBs of storage space that you want for the subscription.

The Addition of license using CSP is handled specifically by the partner using their internal tool and this document pertains to adding extra storage space for your subscription via Microsoft Admin center(Direct). We have added a note to the document stating that  If you bought your subscription through Volume Licensing or a CSP, you can't buy Office 365 Extra File Storage for your organization directly from Microsoft. Contact your representative or partner for help.

Hope this helps!

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @omidhdp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
