### ISSUE TITLE
No ClickOnce option on Mac

### ISSUE THREAD

**Issue by twigbranch** [MicrosoftDocs/microsoft-365-docs#2825]
Unlike what the documentation shows, there is no ClickOnce option/flag on Edge for the Mac.  How does one get it to work?

**Comment by yogkumgit** [comment]
@twigbranch Please tell us which document you are referring to.Thanks

**Comment by yogkumgit** [comment]
@twigbranch We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by twigbranch** [comment]
To download the export tool in Office 365 for exporting PST files, ClickOnce is required - but Edge for Mac doesn't have that option!

**Comment by twigbranch** [comment]
Could you reopen this please?

**Comment by msbemba** [comment]
@twigbranch Sorry about the delay. Could you please provide us the document which talks about this scenario? If you are looking to report a bug or need support you may have to contact our support team via the need help section on the admin center. If you would like to provide feedback about our docs, this is the right place, but we would like to know which document you are referring to.

Thanks
Sri

**Comment by JohnGreenhow** [comment]
@msbemba , @yogkumgit  - this is the document that refers to use of this flag on Mac version of Edge: https://learn.microsoft.com/en-us/microsoft-365/compliance/configure-edge-to-export-search-results?view=o365-worldwide

**Comment by rafa-fmg** [comment]
why is this issue closed when the documentation has not been updated?
https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-configure-edge-to-export-search-results?view=o365-worldwide

**Comment by captDG** [comment]
This is not resolved, therefore it should not be closed. As of this posting, downloading eDiscovery content is not possible on a Mac. This is unreasonable in 2023

**Comment by jkelly80** [comment]
Please reopen this issue.

**Comment by plasmak** [comment]
This issue needs to be reopened and addressed.
