### ISSUE TITLE
Source IP addresses for the incoming traffic

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#2829]
Hello, for regulated organizations it is required to restrict access for incoming traffic to the end points only to only specific IP ranges. What are the IP ranges that the calls from MS DCs to customer endpoints are coming from - for example in rows 7 and 8 (Exchange hybrid free-busy) or 14 (S4B hybrid)?

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/pl-pl/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please help us in resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
@Larryngolog Sorry for the extended delay. Please see https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide for information on how to handle hybrid traffic. Thanks for your question.

**Comment by Larryngolog** [comment]
Hello, I know the article you have mentioned. The issue is that the mentioned article does not include the IPs used for the inbound traffic. For example for EX free-busy it states only "Exchange Hybrid co-existence functions such as Free/Busy sharing. | Customer on-premises Exchange server | Inbound server traffic".

The need is following - regulated customers need to harden their environments and do not allow access to their on-prem end points from all sources. They want to restrict the access to EX server only to calls coming from EXO service.
