### ISSUE TITLE
Conflicting information for Recommended

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/microsoft-365-docs#2830]
The recommendation on this page is to create a mail flow rule yet when you are creating the Bypass Spam Filtering rule in the EAC, the info text reads "_You don't need to create a transport rule to bypass spam filtering or mark email as spam for a sender or domain. Click here to use an allow or block list in the spam filter._"

On this page it says using the allow list is the "_least desirable_" option.

Looking to have some clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MarcLaf, you are correct. The recommendations in the topic are the most current. From the topic:

> Mail flow rules allow the most flexibility to ensure that only the right messages are allowed. Allowed sender and allowed domain lists in anti-spam policies aren't as secure as the IP Allow List, because the sender's email domain is easily spoofed. But, the IP Allow List also presents a risk, because email from _any_ domain that's sent from that IP address will bypass spam filtering.

And

> The least desirable option is to use the allowed sender list or allowed domain list in anti-spam policies. You should avoid this option *if at all possible* because senders bypass all spam, spoof, and phish protection, and sender authentication (SPF, DKIM, DMARC). This method is best used for temporary testing only.

I'll see about getting that text removed from the EAC.

Thanks for the feedback.

Closing
