### ISSUE TITLE
page body typo

### ISSUE THREAD

**Issue by orbis-ming-chang** [MicrosoftDocs/microsoft-365-docs#2831]
[Enter feedback here]
typo this line:

\<img height\="?1"? width\="?1"? sr\c=.?http\://

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37115a33-d073-cf0d-1506-2d2571cf1007
* Version Independent ID: 07dd4b19-c5a5-1fba-cbad-3650922d357f
* Content: [Use mail flow rules to filter bulk email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@orbis-ming-chang, fixed as you described. In the future, you too can make fixes like this directly without opening a GitHub Issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
