### ISSUE TITLE
"convert to shared mailbox" is NOT on page as described. 

### ISSUE THREAD

**Issue by cvanelli-ducks** [MicrosoftDocs/microsoft-365-docs#2833]
The link for "convert to shared mailbox is not under mail>more actions as stated on the page. It is not anywhere on Office 365 site. It has been there before and I am a global administrator. How is it possible that this page was updated less than 2 months ago and already it is incorrect!!!!! Microsoft documentation for Azure/O365 S U C K S!!!!!

Chris

**Comment by denisebmsft** [comment]
Hello @cvanelli-ducks, and thank you for the feedback. Just to confirm, does your feedback apply to this article: https://docs.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?

**Comment by cvanelli-ducks** [comment]
Yes, that is correct. On the page under the heading 'Use the Microsoft 365 admin center to convert a mailbox', step #4

Chris

**Comment by msbemba** [comment]
@cvanelli-ducks Thank you for your feedback. The option to convert a shared mailbox is still available under Users-->active users-->Select the account-->Mail Tab-->Under More actions-->Convert to shared mailbox

![image](https://user-images.githubusercontent.com/45987684/93266326-83cca180-f7c7-11ea-90a4-54caf2a7dcc8.png)

Let us know what you see on your end.

Hope this Helps!

Thanks
Sri

**Comment by cvanelli-ducks** [comment]
Here’s what I see:

https://ducio-my.sharepoint.com/:i:/g/personal/cvanelli_ducks_org/Ec3WMzbraR9KlWjPzjM54-EBkrukqQ3GSxJgSDTCr8P0lw?e=Q0WiOi


----------------------------------------------------
Chris Vanelli
Sr. Systems Engineer II - NHQ
Ducks Unlimited, Inc.
One Waterfowl Way
Memphis TN 38120
mobile: 901-378-7518
office: 901-758-3885
www.ducks.org<http://www.ducks.org/>

**Comment by msbemba** [comment]
@cvanelli-ducks That is strange. I checked on another M365 Tenant and see the convert to a shared mailbox option under more actions. I'd recommend you contact support via the need help option on the admin center to troubleshoot this issue as this looks like a bug on the tenant. 

@yogkumgit There are no changes required on the document. This issue can be closed.

Thanks
Sri

**Comment by cvanelli-ducks** [comment]
This ticket cannot be closed. I have a ticket open with support, and we will see what they say.

**Comment by cvanelli-ducks** [comment]
So I opened a ticket as you suggested (#‎21910303‎) from the 'need help' option in the portal. Sawan was the technician. He said that your documentation is wrong. It used to be there but the portal has changed and that option is no longer available under more actions. He also checked his tenant and another, and it was NOT available. 
So when can we expect the documentation to be corrected?

**Comment by msbemba** [comment]
@cvanelli-ducks Thank you for the quick response. I'll check with the Author and/or engineering team to understand this behavior and update you as well as the document if required.

Thanks
Sri

**Comment by msbemba** [comment]
@cvanelli-ducks Thank you for your feedback. We have made the changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2952

Thanks
Sri

**Comment by cvanelli-ducks** [comment]
How long does it take before this change is reflected in the page?

**Comment by msbemba** [comment]
@cvanelli-ducks Once the PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2952 is merged it takes 24 to 48 hours for the changes to reflect in the live document.

Thanks
Sri

**Comment by cvanelli-ducks** [comment]
It's been a week. So, let me ask the right question. When will the PR##2952 be merged?

**Comment by msbemba** [comment]
@cmcatee-MSFT Could you please help us merge #https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2952 ?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cvanelli-ducks Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by cvanelli-ducks** [comment]
It IS helpful for me. Thank you for such an open way to correct the documentation!

Thanks
Chris
