### ISSUE TITLE
An important mention!

### ISSUE THREAD

**Issue by danialonso** [MicrosoftDocs/microsoft-365-docs#2842]
Hi,
It is essential to clarify that these cycles are only possible in direct subscriptions, not by reseller via CSP (for example). When it comes to a subscription via CSP, these licenses will go from active to directly suspended without a grace period.

Thank you very much, greetings.
Daniel Alonso [MSFT]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@danialonso Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2846

Thanks
Sri

**Comment by danialonso** [comment]
Hi again,
This article talks about retention for only 30 days, not 90:
https://docs.microsoft.com/en-us/microsoft-365/compliance/in...

but this article talks about 90 days:
https://docs.microsoft.com/en-us/microsoft-365/commerce/subs...

Are the retention periods different for Exchange Online? I see a major conflict between both specs! :-(

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @danialonso Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
