### ISSUE TITLE
The section/instructions about ensuring use of the OME portal is not clear 

### ISSUE THREAD

**Issue by paulypoteat** [MicrosoftDocs/microsoft-365-docs#2843]
Section: 
https://docs.microsoft.com/en-us/microsoft-365/compliance/manage-office-365-message-encryption?view=o365-worldwide#ensure-all-external-recipients-use-the-ome-portal-to-read-encrypted-mail 

The steps provided, specifically the powershell command below, just create a transport rule that references the one template you already have.  It doesn't mention or consider that you want to force OME portal use and not allow decryption in Outlook.

New-TransportRule -name "<mail flow rule name>" -FromScope "InOrganization" -ApplyRightsProtectionTemplate "<option name>" -ApplyRightsProtectionCustomizationTemplate "<template name>"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33bb6e61-f899-955c-948d-bf17f0168fea
* Version Independent ID: be8ea691-3547-a442-d2ca-617e17225740
* Content: [Manage Office 365 Message Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/manage-office-365-message-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/manage-office-365-message-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/manage-office-365-message-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@paulypoteat Thank you for your feedback. Per the transport rule, you are using the template "OME Configuration" with Encrypt only, The template"Ome Encryption" by default has OTP Enabled Set to True so it will force OME portal use and not allow decryption in outlook.

![image](https://user-images.githubusercontent.com/45987684/93875848-65006a80-fcf3-11ea-9a8a-9f668741b419.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @paulypoteat Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
