### ISSUE TITLE
Giphy URL requirements

### ISSUE THREAD

**Issue by khilker15** [MicrosoftDocs/microsoft-365-docs#2845]
The firewall URL requirements to support Giphy are not documented in this article.

Per another article: https://docs.microsoft.com/en-us/microsoftteams/location-of-data-in-teams
Giphy GIFs are stored as a reference link to the original Giphy service URL. Giphy is a non-Microsoft service.

For this feature of Teams to work, our customers need to know what URLs are required to communicate with the Giphy service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#bkmk_teams)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Kindly answer and help us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@khilker15 I have forwarded your request to the team that manages these endpoints for consideration in a future update. Thanks for letting us know.
