### ISSUE TITLE
"Organisational Relationships" no longer exists in Azure AD.

### ISSUE THREAD

**Issue by stephendt** [MicrosoftDocs/microsoft-365-docs#2850]
The video on this page is out of date and needs updating. It asks people to view "organisational relationships", but that option does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb311ed9-a649-8f67-51ea-3789ad914b00
* Version Independent ID: 165a9d7e-25e6-d5e5-d960-acaa675e4400
* Content: [Collaborate with guests in a site](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-in-site?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-in-site.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-in-site.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@stephendt Thank you for your feedback. We have modified the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2904

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @stephendt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
