### ISSUE TITLE
Add Office applications to list of session lifetimes

### ISSUE THREAD

**Issue by mchibams** [MicrosoftDocs/microsoft-365-docs#2852]
I think all Office applications (Such as Outlook, Excel, Word, PowerPoint and Teams) should be included in the list of session lifetimes.

These are the same as "SharePoint and OneDrive mobile apps for Android, iOS, and Windows 10"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e1c6c9c-c519-379c-80ef-fa562391bd45
* Version Independent ID: 4623f118-a29c-0a32-9f68-92f3c9f92546
* Content: [Session timeouts for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/Enterprise/session-timeouts?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@mchibams Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2903

The content has now been covered under the Azure active directory section (Office and M365 apps with modern auth enabled ).

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mchibams Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
