### ISSUE TITLE
Delete an inactive mailbox with org-wide holds

### ISSUE THREAD

**Issue by desmondgc** [MicrosoftDocs/microsoft-365-docs#2853]
The "Delete an inactive mailbox" page only mentions litigation holds and in-place holds. But there's another way that a mailbox can be made inactive: using org-wide holds (retention policies). Could you extend this documentation with official guidance how to delete an inactive mailbox which is inactive due to org-wide holds?

(In simple cases it's possible to use `Set-Mailbox <identity> -ExcludeFromAllOrgHolds` but this seems not to work for shared mailboxes or room/equipment mailboxes.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c129f4e-664c-971f-e438-18ae3eb87f17
* Version Independent ID: e63b5be8-3c3c-2592-72bf-3f00cca0e525
* Content: [Delete an inactive mailbox - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-an-inactive-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/delete-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@desmondgc Thanks for the heads up about this gap and the suggested fix. Will look into adding info about this and about. As per the Set-Mailbox cmdlet help topic, you could also use the -ExcludeFromOrgHolds parameter if you have the GUID for the retention policy applied to the inactive mailbox. 

Note that as per our guidance in the [Overview of inactive mailboxes](https://docs.microsoft.com/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-microsoft-365-retention-policies) topic, we suggest you consider having a specific retention policy (not an org-wide) to apply to mailboxes that you plan to make inactive. This requires a bit of planning, but the topic outlines the benefits. Thanks again.
