### ISSUE TITLE
No mention of eDiscovery search for Exchange online in multi geo

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#2854]
How does multi geo eDiscovery search work for Exchange online as the data is also stored in PDL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaed282-c3c5-1814-f61c-16505f0925f3
* Version Independent ID: bb9a0fdd-e96d-584e-9298-1f42307c4d7c
* Content: [Configure Microsoft 365 Multi-Geo eDiscovery - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-ediscovery-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/multi-geo-ediscovery-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/multi-geo-ediscovery-configuration.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Kindly answer and help us in resolving this issue. Thanks.

**Comment by MikePlumleyMSFT** [comment]
@AdwoodMicrosoft can you help?

**Comment by yogkumgit** [comment]
@AdwoodMicrosoft Gentle reminder, we need your help here. Thanks

**Comment by yogkumgit** [comment]
@sujitnaray suggested it is @nickjrobinson to answer this. Thanks

**Comment by yogkumgit** [comment]
@ninacchen As suggested by @nickjrobinson , please help us in resolving this issue. Thanks

**Comment by ninacchen** [comment]
Advanced eDiscovery (AeD) search automatically fans out across all locations. For EXO, all data centers will be searched when using AeD so you don't need to do any configuration - PDL or not. Closing this thread now. If you there is any other questions please raise a support issue as doc github is not the best place to asking questions regarding the production. Thanks!

**Comment by yogkumgit** [comment]
@nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
