### ISSUE TITLE
Incorrect Information

### ISSUE THREAD

**Issue by jhonbike** [MicrosoftDocs/microsoft-365-docs#2856]
It shows 4 name servers but repeated:

ns1.bdm.microsoftonline.com
ns2.bdm.microsoftonline.com
ns2.bdm.microsoftonline.com
ns2.bdm.microsoftonline.com

It should be:

ns1.bdm.microsoftonline.com
ns2.bdm.microsoftonline.com
ns3.bdm.microsoftonline.com
ns4.bdm.microsoftonline.com

The section is:
https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide#change-your-domains-nameserver-ns-records

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f087dd43-183d-08bb-37d7-d893bede6efb
* Version Independent ID: be429837-0300-3de8-6c7d-2da2fabc2c17
* Content: [Update DNS records to keep your website with your current hosting provider - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@jhonbike Thank you for the feedback. We have modified the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2902

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jhonbike 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
