### ISSUE TITLE
internal screenshots

### ISSUE THREAD

**Issue by malidgi** [MicrosoftDocs/microsoft-365-docs#2857]
hey team,

this doc contains internal screenshots- the engineering tools at the navbar and the Diagnostic orange box indicate it.

Thanks,
Matika  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Insider risk management settings - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@malidgi Thank you for your feedback. We have replaced the images on the document with updated ones. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2920

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and collaborating with author. @malidgi as author has closed the PR, we proceed closing this issue. Changes will be reflected soo, Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
