### ISSUE TITLE
Expired lab

### ISSUE THREAD

**Issue by RayJDM** [MicrosoftDocs/microsoft-365-docs#2859]
Is the new version available? Webpage says it is valid till 12th of september and a new one will be added prior - seems like that is not the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office Deployment Lab Kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@RayJDM The article has been updated to reflect the new expiration date of December 4, 2020. Thanks for letting us know.
