### ISSUE TITLE
Gov clouds?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2860]
[Enter feedback here]
Is this available to government cloud tenants? please add information to help us understand where we can expect to find this functionality

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbce796-0aec-3236-d505-607ae8371773
* Version Independent ID: 473cdc81-dc01-f7fd-d570-73e9a07cb972
* Content: [Configuration analyzer for security policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DeanGross, the authoritative source for feature announcements and/or schedules is the Microsoft 365 Roadmap and any related Message Center posts in the admin center.

According to the roadmap, it's coming:

<https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=config%2Canalyzer>

Thanks for the feedback.

Closing
