### ISSUE TITLE
For read-only access to preset security policies

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2861]
The Global Reader role is not listed as being allowed to view these policies. Is this correct or does this role need to be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please add your comment and help us resolving this issue. Thanks

**Comment by chrisda** [comment]
Lack of Global Reader was an omission that has since been fixe.

Thanks for the feedback.

Closing
