### ISSUE TITLE
M365 Datacenter design for smaller Geos

### ISSUE THREAD

**Issue by Rkhan-ms** [MicrosoftDocs/microsoft-365-docs#2863]
[Enter feedback here]
Hi,

My customer - is in the process of setting up Multi-Geo. They would like to confirm that their Exhange High availability configuration outlined within this document will still be relevant for smaller regions. One in particualr is Germany. Can we update the document with the the number of datacenter locations for the Germany Geo? Similar to how we have outlined India, Australia and Japan.

Thanks in advance.

Ray Khan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad3e6ca-fbbb-70e3-b7c3-595736cb8bd7
* Version Independent ID: 8870f5ba-b56c-71e3-222a-955fabcce880
* Content: [Exchange Online Data Resiliency in Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-exchange-data-resiliency?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/microsoft-365-exchange-data-resiliency.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-exchange-data-resiliency.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by Rkhan-ms** [comment]
Hi,

Any update on this request? 

KInd Regards,

Ray

**Comment by msbemba** [comment]
@Rkhan-ms Thank you for your feedback.  Afaik Multi geo options are not available for Germany. I'm checking with the author/Product group to confirm.

Thanks
Sri

**Comment by msbemba** [comment]
@robmazz Could you please help let us know if the Exchange High availability configuration outlined within this document is still relevant for smaller regions in particular in Germany?

Thanks
Sri

**Comment by yogkumgit** [comment]
@robmazz Please reply to this query. Thanks.

**Comment by Rkhan-ms** [comment]
HI Both @robmazz and @yogkumgit - Can you provide an update on this please?

**Comment by robmazz** [comment]
@Rkhan-ms  - thanks for the feedback. Checking with internal contact.

**Comment by robmazz** [comment]
@Rkhan-ms  and @msbemba - Thanks for you patience. I only answers I've been able to get so far is that unless, specified (like India, et al), the common configuration is four database copies in four datacenters for geos. However, this topic is up for a review and I'll make a note to try to amplify this for clarity in the upcoming updates.
