### ISSUE TITLE
Add-in deployment now under Settings > Integrated apps > Add-ins

### ISSUE THREAD

**Issue by QuickBASIC** [MicrosoftDocs/microsoft-365-docs#2865]
Documentation should be updated with correct navigation for Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62dfa25-e420-38e4-ff47-05cca62d14ec
* Version Independent ID: 5ea03ce0-38b9-e005-a430-e98442e2ec83
* Content: [Deploy add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@QuickBASIC Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2900

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @QuickBASIC Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
