### ISSUE TITLE
As of April 1 there now is a mini add-on sku called Microsoft 365 E5 eDiscovery and Audit 

### ISSUE THREAD

**Issue by nayar34** [MicrosoftDocs/microsoft-365-docs#2868]
[Enter feedback here]
With the Microsoft 365 E5 eDiscovery and Audit sku you can increase audit retention from 90 days to 365 days.
So you no longer need the full E5 Compliance license if you just want this functionality.  
What is not clear though is what is the license requirements for adding just the Microsoft 365 E5 eDiscovery and Audit sku.
I have seen info where it can be added to any M365 sku while I have also seen you must at least be at O365 E3. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027a1632-76a4-9e87-8376-c10ddfc3e116
* Version Independent ID: 10c72509-5d4a-25d3-caf8-361474f68cd8
* Content: [Advanced Audit in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/advanced-audit.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/advanced-audit.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@nayar34 Thanks for heads up. I will add the E5 eDiscovery and Audit add-on to this topic and a link to M365 licensing info.

As for the qualifying licensing info, you can find that here in the Online Services Product Terms site: https://www.microsoft.com/licensing/terms/productoffering/Microsoft365/CSP#FromSA

In short, here is qualifying licensing info:

License | License Prerequisites
-- | --
Microsoft 365 E5/A5 Compliance | Microsoft 365 E3 or Office 365 E3 and Enterprise Mobility + Security E3
Microsoft 365 E5/A5 eDiscovery and Audit | Any Microsoft 365, Office 365, Exchange Online, SharePoint Online or OneDrive for Business plan license
