### ISSUE TITLE
Correct page "last updated" to reflect recent commits

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/microsoft-365-docs#2870]
[Enter feedback here]
Page shows last updated "07/08/2019" but commit history shows 20 commits since Jan 1, 2020. Please update the metadata to correctly show that the page is recently updated. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Learn about Information barriers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by softwarecraft** [comment]
This matters cos content on stale dated pages has less credibility, so folks might discount the content on this page

**Comment by yogkumgit** [comment]
@chrfox Kindly answer and help us in resolving this issue. Thanks.

**Comment by chrfox** [comment]
fixed
