### ISSUE TITLE
Link to "learn more about roles and permissions" may not be suitable

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/microsoft-365-docs#2871]
[Enter feedback here]
Immediately below a list of roles required to config this capability, this page says "(To learn more about roles and permissions, see Permissions in the Office 365 Security & Compliance Center.)" However, the link https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/protect-against-threats makes no mention of Information Barriers or any of the roles listed from this page. The link does refer to roles required for M365 ATP but that is not related.

Recommend to find an alternate link or rephrase the text on this page to indicate how the link is relevant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Learn about Information barriers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by softwarecraft** [comment]
The correct link is probably this page, https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center

**Comment by softwarecraft** [comment]
In addition to the link correction, please also review the text of this section, https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers#required-licenses-and-permissions as this page is not consistent with the link. This page omits _Compliance Data Admin_ role (AAD role or role group as it is called on the link) along with two other roles, and this page confusingly equates the permission (role) _IB Compliance Management_ with the other roles (role groups) listed. They are not the same thing and you can't directly assign an AAD user or group the _IB Compliance Management_ permission (role). You must use the predefined roles (role groups) or create a custom AAD role.

**Comment by yogkumgit** [comment]
@chrfox Kindly answer and help us in resolving this issue. Thanks.

**Comment by chrfox** [comment]
@softwarecraft 
thanks for this. I am investigating this issue

**Comment by chrfox** [comment]
links updated, thanks
