### ISSUE TITLE
News 

### ISSUE THREAD

**Issue by JustineNicole2020** [MicrosoftDocs/microsoft-365-docs#2876]
[Enter feedback here]

Get-HostedConnectionFilterPolicy -Identity Default
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3094559e-4d03-8f6d-a620-a3f61ec33184
* Version Independent ID: d352d9b3-3d96-402b-c20e-df677b3e9d60
* Content: [Configure the default connection filter policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-connection-filter-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-connection-filter-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-connection-filter-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@JustineNicole2020 Thank you for your feedback. I was able to test the cmdlet and verify the settings. Could you please elaborate on what changes you need on this document?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @JustineNicole2020 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
