### ISSUE TITLE
More information needed about the MSCommerce Module

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/microsoft-365-docs#2880]
I am missing information about the MSCommerce Powershell module:
How can I use the module with delegated admin permissions (DAP)?
Is there a more in depth documentation of the module available listing the commands and their parameters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@joergrenn Thank you for your feedback. Currently, it is not possible for someone with DAP to access the Commerce module for a tenant. However, Partners who have delegated administration privileges can see self-service purchases in the Microsoft 365 admin center, just like an admin.

There is no in-depth document about the module, However, this document covers all commands that are available in the module

![image](https://user-images.githubusercontent.com/45987684/93873974-40ef5a00-fcf0-11ea-9306-199346dd2822.png)

Hope this Helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @joergrenn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
