### ISSUE TITLE
There is no step to configure the Connector

### ISSUE THREAD

**Issue by jhonbike** [MicrosoftDocs/microsoft-365-docs#2888]
Without a Connector, the configured "Internal Relay"domain could not send emails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738692b6-47ec-2a49-e576-bb6ff0cd3471
* Version Independent ID: c9d7a0ad-2db4-dda1-6021-831e5bb38098
* Content: [Pilot Microsoft 365 from my custom domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/pilot-microsoft-365-from-my-custom-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/pilot-microsoft-365-from-my-custom-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/pilot-microsoft-365-from-my-custom-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@jhonbike THank you for your feedback. We need a connector from o365 to the email server. I have updated the document accordingly and the same can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2922

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jhonbike Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
