### ISSUE TITLE
Article says, GetBestRoute returns local interface (what is mean by local interface, is it physical adapter or virtual adapter created by VPN?)

### ISSUE THREAD

**Issue by arunkumar4003** [MicrosoftDocs/microsoft-365-docs#2890]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b783ee-9449-56db-3abd-f17dcf6b5d54
* Version Independent ID: d2146ff5-4248-12ec-a873-c951220aaa14
* Content: [Implementing VPN split tunneling for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Kindly answer and help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
Hello @arunkumar4003,

My understanding is that the GetBestRoute function (not a method, I will correct this in the topic) only examines the routing table and therefore cannot distinguish between physical and virtual adapters. More information on GetBestRoute: https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getbestroute

Does this adequately address your question?

**Comment by yogkumgit** [comment]
@kelleyvice-msft Thank you very much for sharing this explanation. @arunkumar4003 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
