### ISSUE TITLE
Shared mailboxes?

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/microsoft-365-docs#2891]
Is the report-mesasge-add-in supported with the usage of shared mailboxes?

If not, how can users report suspicious emails that they received in a shared mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@sebhe Thank you for your feedback. The add-in is available via the web version of outlook  The report-message add-in is not available for shared/delegate mailboxes when accessed via outlook. This has been added to the user voice section - https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/36313066-report-message-additional-mailbox which is addressed by the engineering team. Hopefully, this feature will be added soon.

Hope this helps!


@yogkumgit  There are no changes required in the document. Please close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sebhe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
