### ISSUE TITLE
Auto-forwarding methods needs more detail

### ISSUE THREAD

**Issue by abhitalks** [MicrosoftDocs/microsoft-365-docs#2894]
The section describing auto-forwarding methods: mail flow rules, Inbox rules, and SMTP forwarding need a little more detail on what are these methods and especially what is "SMTP forwarding" and where should administrators look for the user defined rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5bb1b82-5bde-ce65-ca17-9e982b030a5c
* Version Independent ID: 704d9708-5308-4b5d-0ffa-d6b31fa7d0f3
* Content: [Auto-forwarded messages insight - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@abhitalks, apparently, this is the forwarding that admins can configure on mailboxes as described in [Configure email forwarding for a mailbox](https://docs.microsoft.com/Exchange/recipients-in-exchange-online/manage-user-mailboxes/configure-email-forwarding). I've updated the topic accordingly.

Thanks for the feedback.

Closing.
