### ISSUE TITLE
Graph Notification IP address list is incomplete

### ISSUE THREAD

**Issue by williamlooney** [MicrosoftDocs/microsoft-365-docs#2895]
[Enter feedback here]
A MSFT partner has reported that the Graph Notification IP address list on this page is incomplete. Specifically, they report getting Notifications for changes on the CallRecord resource from the following IP addresses that are not listed on this page:

- 51.104.159.213
- 51.138.90.7
- 51.138.90.52

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@williamlooney Taking this discussion internal to Microsoft. Thanks for letting us know.
