### ISSUE TITLE
Need more Exchange Online X-Headers documented on the page

### ISSUE THREAD

**Issue by NoahsMyBro** [MicrosoftDocs/microsoft-365-docs#2897]
I often am tasked with examining emails to understand the hows & whys of a message's delivery. There are many X-Microsoft or X-MS-Exchange headers that are undocumented.

Example: "x-ms-oob-tlc-oobclassifiers" OLM:_____

I'm _guessing_ oob = Out of band? OLM = ? And the numeric values stamped to OLM - ?

My job will be made easier if you can document more of these headers. 

Thanks.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@NoahsMyBro, I hear you. But, as described in the topic:

> The <x> header contains many different fields and values. Fields that aren't described in the table are used exclusively by the Microsoft anti-spam team for diagnostic purposes.

Trust me, if documenting other header fields and values could be useful to customers and could help reduce support calls, we would do it.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @NoahsMyBro Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
