### ISSUE TITLE
Automation 

### ISSUE THREAD

**Issue by shredwerd009** [MicrosoftDocs/microsoft-365-docs#2899]
Please consider an unattended scripted approach with powershell, so that those who wish to automate the process can try that out. Otherwise good article, i'll be trying to use it to craft my own powershell script for this task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@shredwerd009  Thank you for your feedback. That is a nice idea and I'm a big fan of automation and scripts, however, Microsoft docs objective is to provide details to admins and users on how some of these M365 features work. We generally do not add scripts to documents as they are risky if not used correctly. Especially in a sensitive topic like this. Hope this helps! 

Please continue to leave your feedback on Microsoft docs.

@yogkumgit There are no changes required in the docs as such. Please close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @shredwerd009 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
