### ISSUE TITLE
Cloud Management Gateway

### ISSUE THREAD

**Issue by spadge007** [MicrosoftDocs/microsoft-365-docs#290]
Hi, I am trying to complete section 5 and cannot get a cloud management gateway to provision correctly, At each attempt I simply get error in the status. The guide does provide any guidance as to what to do if this occurs. I have spent several hours trying to fix this problem but no luck so far. I have tried removing the created apps and resource group but the same error occurs.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Modern Desktop Deployment and Management Lab Kit](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab#feedback)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Hi - this series of articles is not designed to go into troubleshooting guidance. Please check out this article to see if it helps you identify or resolve your issue - https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/setup-cloud-management-gateway

Thanks!
