### ISSUE TITLE
Feature deprecated?

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/microsoft-365-docs#2901]
Exchange Admin center shows this alert:

As per the original notice announced on July 31, 2017, the In-Place eDiscovery & Hold functionality in the Exchange Admin Center is being retired.
During this process, for a better customer experience, we encourage your organization to start using the eDiscovery search and hold features in the Microsoft 365 Compliance Center. Learn more
Here are the key milestones for this process:
 July 1, 2020 - You won't be able to create new searches and holds, but you can still run, edit and delete existing searches at your own risk. Microsoft Support will no longer provide assistance per this notice.
 October 1, 2020 - The In-Place eDiscovery & Hold functionality in the Exchange admin center will be placed in a read-only mode. This means you'll only be able to remove existing searches and holds.

**Maybe new instructions are needed?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9d3d55-537e-52f4-72f6-c0879a1b595a
* Version Independent ID: ea130146-6bd6-348a-bc8f-4e65ad1ae987
* Content: [Recover deleted items in a user mailbox - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@ingepepe Thank you for your feedback. I'm working with the author and will update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please advise us to resolve this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@ingepepe Please see this current version of the content of the article you reference above: https://docs.microsoft.com/en-us/Exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages 

We intend to delete the older version of the article and redirect its URL to the current version. Please let us know if the more current version of the article addresses your issue. Thanks.

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT and @msbemba Thank you very much for the contribution and sharing this explanation. @ingepepe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
