### ISSUE TITLE
Naming inconsitency when talking about Microsoft 365 Groups

### ISSUE THREAD

**Issue by plamber** [MicrosoftDocs/microsoft-365-docs#2909]
Hello,
I noticed that this page is using the terms "Microsoft 365 Groups", "Office Groups", "Office 365 Groups" interchangeably. I am wondering if it wouldn't be better to always use the official term "Microsoft 365 Groups" instead?

If this is fine for you I can go and perform the changes and make a pull request.

br,
Patrick 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8db9afe-21ec-9ab9-12ef-14decd05c84b
* Version Independent ID: 5ccc9689-83e2-c090-6a13-4472c5476dbc
* Content: [Manage Microsoft 365 Groups with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@plamber Thank you for your feedback. Office 365 groups are now called Microsoft 365 groups.  We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2935

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @plamber Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
