### ISSUE TITLE
WordPress.com not WordPress

### ISSUE THREAD

**Issue by cnewcomer90** [MicrosoftDocs/microsoft-365-docs#2910]
Hi, "WordPress' refers to the open-source WordPress project, not WordPress.com. When referring to "WordPress" as a domain registrar, the correct name should be "WordPress.com". You can see https://wpisnotwp.com/ for more details.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0012093-49ca-c2f6-a3f3-4e4252fca609
* Version Independent ID: 22784dda-ff03-971b-4d6e-5b0152f62942
* Content: [Add a domain to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/add-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@cnewcomer90 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2934

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cnewcomer90 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
