### ISSUE TITLE
Users with +50GB Mailbox before license change

### ISSUE THREAD

**Issue by ad0m** [MicrosoftDocs/microsoft-365-docs#2911]
General Feedback - this page is good for understanding the upgrade path, however, one key element I think it should include is the O365 E3 Mailbox being at 100GB and the M365 BP Mailbox being at 50GB - When a user is migrated from O365 to M365 and have a mailbox larger then the 50GB limit - What should happen? 

In our case for a client we've implemented Exchange Online Archiving and set retention for 3 years so that users with a mailbox larger then 50GB won't loose mail when their license changes from O365  E3 to M365 BP. 

i.e.: I believe the below is required before moving a user with a too big of mailbox from O365 E3 to M365 BP

1 - Enable Archiving on all user mailboxes 
2 - Change mailbox archive policy from 2 years to X years (depending on client request) 
3 - Set new archive policy of X years as default 
4 - Run the managed folder assistant to apply the new settings (Give it some time to move users mail - Maybe a few days)
5 - Change the users licenses from O365 E3 to M365 BP”

Regards,
Adam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655829e4-741a-dc96-35f9-2f3df4de2633
* Version Independent ID: f1c9dc75-d781-322c-1d74-8e0f39fafd1e
* Content: [Migrate to Microsoft 365 Business from Office 365 E3 - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/migrate-from-e3?view=o365-worldwide)
* Content Source: [microsoft-365/business/migrate-from-e3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/migrate-from-e3.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@ad0m Thank you for your feedback. That is a good catch and important information. In these situations, Microsoft recommends you to switch to an Exchange online plan 2 for those users who are exceeding the 50GB storage limit. I have made changes to the document to reflect this via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2933

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ad0m Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
