### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/microsoft-365-docs#2912]
Why are you calling out "Important: This procedure is only applicable to OAuth and NTLM. **Kerberos is not supported**."?

Clearly Kerberos is working alongside NTLM for AAD-joined devices: https://docs.microsoft.com/en-us/azure/active-directory/devices/azuread-join-sso

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ba9775-1242-af4d-a9c0-8979cc5d57dc
* Version Independent ID: 5063400b-fe96-79f4-e37f-6c89e26ee9d0
* Content: [Access on-premises resources from an Azure AD-joined device in Microsoft 365 Business - Microsoft 365 Business](https://review.docs.microsoft.com/en-us/microsoft-365/business/access-resources?view=o365-worldwide&branch=master)
* Content Source: [microsoft-365/business/access-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/access-resources.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@GenerAhl Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2931. Once the author approves the document will be updated.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GenerAhl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
