### ISSUE TITLE
[ATP SafeLinks] Explain the URL rewritte schemata

### ISSUE THREAD

**Issue by philippkahr** [MicrosoftDocs/microsoft-365-docs#2913]
[Enter feedback here]

I think that this page lacks the information of a detailed description on the rewritten URL. E.g. [University Knowledgebase](https://www.queensu.ca/its/microsoft-office-365/security-features/advanced-threat-protection/atp-safe-links) explain all the parts of the links. We got a lot of customer feedback asking `why is my mail showing up in this link`. Additionally, I would like to see an explanation on when, URLs get properly rewritten.

If I send a suspicious link to philipp.kahr@company.com I can see that the URL contains philipp.kahr@company.com. Which totally makes sense, as the mail always is rewritten to the recipient one.

If philipp.kahr@company.com forwards the mail without touching the contents of it to philipp@company.com, the URL again is rewritten to contain philipp@company.com instead of philipp.kahr@company.com.

However, if philipp.kahr@company.com, rights clicks on the URL and copy and pastes the long safelink URL into a new mail and sends this mail to philipp@company.com, the URL is *not* rewritten to contain philipp@company.com, instead it still shows philipp.kahr@company.com.

I personally feel like the second one is a bug, as the ATP safe links mechanic should properly detect links and recreate them.

If you would like me to write the explanation including screenshots, I will be happy to do this, just give a bump.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1541da6f-af9a-05d5-fa34-b1a5df61424f
* Version Independent ID: 88e111ed-67f7-41bc-d823-863ee7ea2a2e
* Content: [Set up Office 365 ATP Safe Links policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@philippkahr Thank you for your feedback. I'll test this and make necessary changes to the document.

Thanks
Sri

**Comment by msbemba** [comment]
@philippkahr Thank you for your feedback. I have made changes to the document to explain a bit more on when the URL is rewritten and what happens when this is forward or replied. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2950

Meanwhile, Once ATP Safe Links has rewritten a URL, if the message is forwarded or replied to, the URL will remain rewritten. Additional links added to the message being replied to or forwarded will not be rewritten. Similarly when you copy the Safe Link URL it does not change from philipp.kahr@company.com to  philipp@company.com as it contains a rewritten URL.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @philippkahr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
