### ISSUE TITLE
Update to include OverrideAdminDomain property

### ISSUE THREAD

**Issue by techangelsau** [MicrosoftDocs/microsoft-365-docs#2917]
Hi everyone,
Can you please add the following information for connecting to a CsOnlineSession. One of the common issues is that internal and external DNS is not always used simultaneously, and cannot resolve to the UPN of a user. 
Please add the steps to use the "OverrideAdminDomain" option, as this was able to resolve an issue for me, and I would like to share it with anyone using the document. :) 
New-CsOnlineSession -OverrideAdminDomain domain.onmicrosoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289b637a-ad53-2710-3b6e-7f4ac15916fa
* Version Independent ID: e8de4044-38f3-1002-9816-12515d0cdda0
* Content: [Manage Skype for Business Online with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@techangelsau Thank you for your feedback. The parameter overrideadmindomain is used only when the administrator has permissions to manage more than one tenant. The Parameter is explained in detail on the New-CsOnlineSession document ( https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlinesession?view=skype-ps). This document is used by admins to connect to SFB and most of them use the copy feature to paste it on Powershell ISE or while creating a script. So I'm afraid there is no need for general audience to use this parameter as such. 

Thank you again for leaving your valuable feedback and continue to do so.

@yogkumgit There are no changes required in the document and this can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @techangelsau Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
