### ISSUE TITLE
Add a line "Local Toll Free" under the number 000 800 440 2038

### ISSUE THREAD

**Issue by yuliuleo** [MicrosoftDocs/microsoft-365-docs#2918]
Hi Team,

I would like to pass a feedback regarding the link below. 
https://docs.microsoft.com/en-in/microsoft-365/admin/support/india?view=o365-worldwide#feedback

Can you please add a line "Local Toll Free" under the number 000 800 440 2038 to clearly tell the customer that this is the toll free number in India?
This is an internal request from Microsoft CPR team.
Thank you,
Leo
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eff5027-9b64-7353-757b-1aaa0de12e6c
* Version Independent ID: 222b1ebf-7147-dd6e-ae20-e667a33ece67
* Content: [Support information for India - Microsoft 365 admin](https://docs.microsoft.com/en-in/microsoft-365/admin/support/india?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/india.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/india.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@yuliuleo THank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2930

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @yuliuleo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
