### ISSUE TITLE
NERC CIP-013

### ISSUE THREAD

**Issue by jcmgsec** [MicrosoftDocs/microsoft-365-docs#2924]
I would like Microsoft to consider updating this NERC document to include the relevant and necessary information a customer needs to comply with CIP-013 as it pertains to Supply Chain.

Requirements can be found on nerc's website, https://www.nerc.com/_layouts/15/PrintStandard.aspx?standardnumber=CIP-013-1&title=Cyber%20Security%20-%20Supply%20Chain%20Risk%20Management&jurisdiction=United%20States

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74a30bb6-bda6-e3e4-5fcd-68e58091573c
* Version Independent ID: 53eb69ee-8232-3b0b-9ccb-c04367d98ec1
* Content: [North American Electric Reliability Corporation (NERC) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-nerc-cip?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-nerc-cip.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-nerc-cip.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@jcmgsec Thank you for your feedback. We have added the Direct URL to the document under the resources section. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2983.

Once the author @robmazz  approves it will be updated.

Thanks
Sri

**Comment by robmazz** [comment]
@jcmgsec  - changed was merged in September
