### ISSUE TITLE
"How to get to the Groups report" section does not describe the current UI of usage reports page.  

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/microsoft-365-docs#2932]
The instructions for how to get to the Groups report do not match what I see.  There is no "Select a report" drop down on that page.  Instead, I see several summary cards showing reports for different services, and I can click a View More button under each one to dig deeper.  None of those reports appear to focus on Office 365 Groups though.  

The descriptions and images on the [reports overview]( ) page seem to match what I get, again with no mention of an Office 365 Groups report. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d43b01f-5c1e-515a-900a-7aab927c294e
* Version Independent ID: 23b1fc80-9d25-c9fb-2600-3d91b11b9063
* Content: [Microsoft 365 Reports in the admin center - Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/office-365-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@NeighborGeek Thank you for your feedback. 

Select **View more** under **Active users - Microsoft 365 Services****, then Select a report** drop-down, select **Office 365** \> **Groups activity**.

We have made changes to the document to reflect the correct steps to access the group activity report. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2960

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @NeighborGeek Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
