### ISSUE TITLE
Missing Message Type

### ISSUE THREAD

**Issue by ClearSkyyes** [MicrosoftDocs/microsoft-365-docs#2936]
The Message Type in M365 Message Center now has 4 types, but this document only lists 3.  The Data Privacy type is missing.  What is a Data Privacy message?  Can an example be included?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d48710a5-bfd4-dbbd-dc97-741feccd00af
* Version Independent ID: 5540a0cf-7de7-3082-59d2-a93ece028f60
* Content: [Message center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/message-center?view=o365-worldwide#messages)
* Content Source: [microsoft-365/admin/manage/message-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/message-center.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@ClearSkyyes Thank you for your feedback. Data privacy label is not a different message type instead it is an option for the admins to choose what type of information they want to look in the admin center. For example, In an organization, there could be a global admin, an exchange admin, a team admin, and a data privacy admin. The global admin most likely will want to see any and all alerts but the Data Privacy admin may only care about seeing things specific to Data Privacy. So the options are available to pick and choose what they want to see in the message center.

Hope this helps!

Thanks
Sri.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ClearSkyyes Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ClearSkyyes** [comment]
This is now listed as a filter, so I assumed it was being split out as a new message type.  Am I understanding correctly that Data Privacy messages will actually be one of the primary types (Plan for Change, Stay Informed, Prevent/Fix Issue) and this other option available in the filter will just be an additional field that shows elsewhere in that message?

**Comment by msbemba** [comment]
@ClearSkyyes That is correct. The categories remain the same 1) Plan for Change 2) Stay informed 3)Prevent/Fix Issue. Data privacy is more service-related and the issues arising out of it will fall into one of the categories.

Thanks
Sri

**Comment by ClearSkyyes** [comment]
Thank you for the clarification!
