### ISSUE TITLE
Which Microsoft licensing agreement is in effectfor a subscription/tenant?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/microsoft-365-docs#2939]
Please include instruction for how to find out which Microsoft licensing agreement is used for a specific tenant or subscription.

On the page [Microsoft licensing agreements](https://partner.microsoft.com/en-US/licensing/licensing-agreements) there's a list of different agreements under which Microsoft cloud services can be bought.

Where the portal does it show the agreement which currently is in effect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7703649a-ac89-7b4c-fbb2-9754cee5a304
* Version Independent ID: 45f5e853-d26a-5e5f-cf53-b8719f96c569
* Content: [What subscription do I have? - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/what-subscription-do-i-have?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/admin-overview/what-subscription-do-i-have.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/what-subscription-do-i-have.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Bartolomeus-649 Thank you for your feedback. This document talks about the subscription so we don't have information about different types of agreements here. Microsoft licensing agreement is used by partners (CSP program). If you are looking for agreements for  Government, Education, or commercial tenants - It can be found at https://portal.office.com/commerce/mosa.aspx


If you are looking for Other agreements like Enterprise or volume licensing, the details and comparison can be found here -http://download.microsoft.com/download/1/F/5/1F5357DD-F7C8-4CC8-8C5F-7F6B1569ECF0/Transactional_Licensing_Comparison_Chart.pdf

Hope this helps!

@yogkumgit There are no changes required in the document and this issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Bartolomeus-649 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Bartolomeus-649** [comment]
@yogkumgit , @msbemba Not helpful at all. It seems like you didn't even read the issue.

**Comment by msbemba** [comment]
@Bartolomeus-649  Sorry about that. I meant there is no place in the portal you can view the license agreement. Instead, it can be found at https://portal.office.com/commerce/mosa.aspx 

if you are referring to the partner agreement, It is not found on the portal but provided to you by the partner.

Thanks
Sri

**Comment by Bartolomeus-649** [comment]
I don't want to view the agreement, I want to find out which agreement is in effect for a specific tenant.

**Comment by msbemba** [comment]
It is not possible to find out which agreement is in effect for a tenant. A tenant can have multiple subscriptions like M365, Azure, and Dynamics.  Every subscription is an agreement with Microsoft to use one or more Microsoft cloud platforms or services, You can find more information about this here - https://docs.microsoft.com/en-us/microsoft-365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings?view=o365-worldwide#subscriptions

Thanks
Sri
