### ISSUE TITLE
Microsoft 365 E3 Exchange Features

### ISSUE THREAD

**Issue by srobin2** [MicrosoftDocs/microsoft-365-docs#2940]
It says that for "Organization subscription: To access Core eDiscovery in the Microsoft 365 compliance center or the Office 365 Security & Compliance Center and use the hold and export features, your organization must have a Microsoft 365 E3 or Office 365 E3 subscription or higher".

However, the Microsoft Product compare, https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4Dz8M, says that Core eDiscovery, which includes legal hold, nor Email archiving are part of Microsoft 365 E3 subscription. It has become hard to find correct information on Microsoft articles when it comes to licensing information.

**Comment by markjjo** [comment]
@srobin2 Thanks for the query. There are lots of problems/errors in the product compare doc that you link to. You might submit feedback about this to https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=139404

For core eDiscovery, the licensing requirements listed here:  https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-core-ediscovery?view=o365-worldwide

AND

https://docs.microsoft.com/en-us/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.xlsx

are correct. In short, Core eDiscovery requires E3; Advanced eDiscovery requires E5.

**Comment by srobin2** [comment]
Ok, will do. Thank you.

**Comment by markjjo** [comment]
@srobin2 Also, in the doc you linked to, some other errors:  

- E3 supports archive mailboxes (specifically, users needs an EXO Plan 2 license or a EXO Archiving add-on license)
- E3 supports basic audit
- E3 supports content search
