### ISSUE TITLE
Deletion policies and the need to enable an archive mailbox

### ISSUE THREAD

**Issue by eric92315** [MicrosoftDocs/microsoft-365-docs#2942]
Please see my suggestion to the Note on the page to add "or deletion".  Because I only wanted to implement a deletion policy without any archive polices, it was not clear if I needed to enable an archive mailbox, so I opened a ticket (21713052) with Premier support on it.  They said that enabling archive mailboxes was required even for deletion policies.

 Note

You can enable archive mailboxes any time during this process, just as long as they're enabled at some point before you complete the process. If an archive mailbox isn't enabled, no action is taken on any items that have an archive **or deletion** policy assigned to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@eric92315 Thanks for following up about this. I will incorporate your suggested fix. Update should be published by tomorrow or so.
