### ISSUE TITLE
Page is incomplete.

### ISSUE THREAD

**Issue by joebeitler** [MicrosoftDocs/microsoft-365-docs#2943]
Incomplete page.  Video is dated.  Does not show current menu structures of the portals.

All settings for my org are checked and verified.  I still can't add guests to a Team.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147fb47a-99b2-f8ef-9ca6-35696d49c3fb
* Version Independent ID: b2f1b521-f231-48c2-b61f-f71bf9248d1c
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-as-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-as-team.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@joebeitler Thank you for your feedback. The steps on the documents are accurate, however, the video is currently being fixed by the author @MikePlumleyMSFT . If you still have an issue adding guests to a team, I'd encourage you to contact the Support team via the need help option on the admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @joebeitler Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
