### ISSUE TITLE
wow very fascinating

### ISSUE THREAD

**Issue by kingfr0z** [MicrosoftDocs/microsoft-365-docs#2945]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd9ad252-50c2-e9d6-9e1a-ab5efde15e60
* Version Independent ID: 7d82a046-e1e2-015f-cb09-27798701b131
* Content: [Overview of the Contoso Corporation - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/contoso-overview?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/contoso-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/contoso-overview.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@kingfr0z Thanks so much for your comment! Let us know how we can improve this content going forward.
