### ISSUE TITLE
Documents contain incorrect update dates

### ISSUE THREAD

**Issue by tokitamo-ms** [MicrosoftDocs/microsoft-365-docs#2948]
The documentation says "Last updated: MM/DD/YYYY" but may include further updates if verified using RSS or changes web methods.
Incorrect dates may prevent customers from noticing the update. 
Please always update the date to the most appropriate one.

![image](https://user-images.githubusercontent.com/54471197/94094417-66987280-fe5a-11ea-8f82-acb16cca1f12.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@tokitamo-ms Date of the latest updates for these endpoint articles will be published today based on the change log subscription link. Thanks for letting us know.

**Comment by tokitamo-ms** [comment]
@JoeDavies-MSFT Thank you for your quick response.
