### ISSUE TITLE
Double mention at the start of the document

### ISSUE THREAD

**Issue by CRutter12** [MicrosoftDocs/microsoft-365-docs#2951]
The article opens with "This article applies to both Microsoft 365 Enterprise and Microsoft 365 Enterprise."
That's a little much ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b05a56d-f714-2d99-747e-b3150f581f38
* Version Independent ID: e8924d3f-20e7-6ce2-2279-cec010e7d3f3
* Content: [Prepare for directory synchronization to Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-for-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@CRutter12 This correction (This article applies to both Microsoft 365 Enterprise and Office 365 Enterprise) will be published today. Thanks for letting us know.
