### ISSUE TITLE
SetupCrossTenantRelationshipForTargetTenant script

### ISSUE THREAD

**Issue by TheUn1que** [MicrosoftDocs/microsoft-365-docs#2953]
While trying to run the SetupCrossTenantRelationshipForTargetTenant script I'm receiving the error for step 11 (Create an organization relationship with resource tenant authorizing migration), and I believe that -New-OrganizationRelationship & -New-MigrationEndpoint are not yet updated to have MailboxMoveCapability & RemoteTenant parameters.

Log:

A parameter cannot be found that matches parameter name 'MailboxMoveCapability'.
    + CategoryInfo          : InvalidArgument: (:) [New-OrganizationRelationship], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-OrganizationRelationship
    + PSComputerName        : outlook.office365.com
 
A parameter cannot be found that matches parameter name 'RemoteTenant'.
    + CategoryInfo          : InvalidArgument: (:) [New-MigrationEndpoint], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-MigrationEndpoint
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by georgiahuggins** [comment]
Hello @yogkumgit. Could you please send these details and your tenant names to crosstenantmigrationpreview@service.microsoft.com? Thank you.

**Comment by JoeDavies-MSFT** [comment]
@TheUn1que (For Georgia) Could you please send these details and your tenant names to crosstenantmigrationpreview@service.microsoft.com? Thank you.
