### ISSUE TITLE
How to get the Source (Source of Authority) attribute programmatically?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#2955]
I would like to get this attribute in my Powershell scripts for groups and accounts. It is shown in the portal as "Cloud", "Azure Active Directory" or "Windows server AD" so I suspect it must be retrieveable...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a9b681e-0845-4440-3ae6-96bdaae14804
* Version Independent ID: 52f31f6b-0451-8c24-a3fd-efefc0b08646
* Content: [View Microsoft 365 user accounts with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-user-accounts-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@andrePKI The updates to the article for your request are now published in the "View account synchronization status" section. Thanks to @msbemba for adding this new content. Thanks for your request and the opportunity to improve this article.
