### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/microsoft-365-docs#2956]
In the German translation of this page it says that M365 Business Standard does not work for Shared Mailboxes, which is incorrect:

Abonnementanforderungen: Um ein freigegebenes Postfach zu erstellen, müssen Sie einen Microsoft 365 for Business-Plan abonnieren, der e-Mails enthält (Exchange Online Dienst). Das Microsoft 365 apps for Business-Abonnement enthält keine e-Mails; **Microsoft 365 Business Standard funktioniert nicht.**

In the French translation it just says "M365 Business Standard":
Conditions requises en matière d’abonnement : Pour créer une boîte aux lettres partagée, vous devez vous abonner à un forfait Microsoft 365 pour les entreprises qui inclut le courrier électronique (le service Exchange Online). L’abonnement apps pour les applications Microsoft 365 n’inclut pas le courrier électronique ; **Microsoft 365 Business standard**.

This is the concerned paragraph in English language:

Subscription requirements: To create a shared mailbox, you need to subscribe to a Microsoft 365 for business plan that includes email (the Exchange Online service). The Microsoft 365 Apps for business subscription doesn't include email; **Microsoft 365 Business Standard does.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289f2440-9c44-7d93-20e3-baa9e9892cd9
* Version Independent ID: abc4e209-a071-d28a-cb01-aa72bbaee7c0
* Content: [About shared mailboxes - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/about-shared-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/about-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/about-shared-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by TinaMcN** [comment]
@SilviaEid thank you very much for reporting this issue.  It seems that the machine translation mistranslated the sentence.  We will update the English text and run the machine translation and hopefully that will fix the issue.

**Comment by yogkumgit** [comment]
@TinaMcN Please update if the issue is fixed. Thanks.

**Comment by TinaMcN** [comment]
@SilviaEid @yogkumgit the issues appears to be fixed now.  

The English text was updated to:
 Subscription requirements: To create a shared mailbox, you need to subscribe to a Microsoft 365 for business plan that includes email (the Exchange Online service). The Microsoft 365 Apps for business subscription doesn't include email. Microsoft 365 Business Standard does include email.

And the German text is now:
Abonnementanforderungen: Um ein freigegebenes Postfach zu erstellen, müssen Sie einen Microsoft 365 for Business-Plan abonnieren, der e-Mails enthält (Exchange Online Dienst). Das Microsoft 365 apps for Business-Abonnement enthält keine e-Mails. Microsoft 365 Business Standard enthält e-Mail.

This was also an issue in other languages because the machine translation struggled with the original English sentence. 
 @SilviaEid thanks again for letting us know about this issue.  Please close it you confirm it's fixed now.

**Comment by SilviaEid** [comment]
@TinaMcN thanks for letting me know. Yes, this is now correct in German and French as well:

Conditions requises en matière d’abonnement : Pour créer une boîte aux lettres partagée, vous devez vous abonner à un forfait Microsoft 365 pour les entreprises qui inclut le courrier électronique (le service Exchange Online). L’abonnement aux applications pour les entreprises Microsoft 365 n’inclut pas le courrier électronique. Microsoft 365 Business standard inclut le courrier électronique.

**Comment by TinaMcN** [comment]
@SilviaEid as you have previously provided excellent feedback on the German Docs content I wanted to let you know that we are starting a pilot project to enable community Editing (PR's) and Feedback (Issues) on the German Microsoft Teams content https://docs.microsoft.com/de-de/microsoftteams/teams-overview. We have a German linguist on standby to review any suggestions during December and January.  
If you have any time to look at the translation quality of the German Teams content we would love to get your feedback. Note that the content is a mixture between human translated and partially-machine-translated articles - the MT ones have a purple banner at the top. The editing feature will only be enabled on the human translated articles. If you know of anyone else that might be interested to help us out feel free to share.
Best wishes
Tina
Localization manager for Docs content for Teams, M365, Windows, SharePoint, Exchange, Edge, Surface etc.

**Comment by SilviaEid** [comment]
Hi Tina,

Thank you for the email. I can have a look at the German translations. Do you want me to check any of the documents under the link specifically, or all of them (as far as I can)?

Best regards,

Silvia Eid
LicenseQ Team - German

**Comment by SilviaEid** [comment]
Hi Tina,

I would also like to know if you need the feedback to be provided via the feedback link on the website, or by another method?

Best regards,

Silvia

From: Silvia Eid (Arvato Direct Services)
Sent: Monday, December 28, 2020 12:54 PM
To: MicrosoftDocs/microsoft-365-docs <reply@reply.github.com>; MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Translation Error (#2956)

Hi Tina,

Thank you for the email. I can have a look at the German translations. Do you want me to check any of the documents under the link specifically, or all of them (as far as I can)?

Best regards,

Silvia Eid
LicenseQ Team - German

**Comment by TinaMcN** [comment]
Hi @SilviaEid it would be great to get your feedback on the German translations on any of the Microsoft Teams articles https://docs.microsoft.com/de-de/microsoftteams/teams-overview.
Ideally it would be very helpful it you can try editing the files (using the Bearbeiten option).   This option is only available on the articles which are human translated.  Once you submit a suggestion this way, Volker, the German linguist will review the changes before they are published.
![image](https://user-images.githubusercontent.com/53281468/103251570-0b30c180-492e-11eb-903e-40fc50b11076.png)

There are a number of articles which are machine translated, they have a purple banner at the top of the page.  The Bearbeiten option is not available for them but you use the "Feedback" option on those ones if you notice any bad machine translation errors.
![image](https://user-images.githubusercontent.com/53281468/103251618-3f0be700-492e-11eb-85ff-7079a8494936.png)

We look forward to seeing your feedback!
Best wishes,
Tina

**Comment by SilviaEid** [comment]
Hi Tina,

Thank you for the information. I tried both options today, and I have one question about the editing of the human translated articles: Is it sufficient to click "Propose Changes", or is it necessary to use "Create pull request"?

Best regards,

Silvia

**Comment by TinaMcN** [comment]
@SilviaEid thank you so much, I see you created a number of detailed Issues - I'll take a close look at them next week when I'm back from vacation.    For the editing it is necessary to click "Create pull request" so that we can see them.
Best wishes,
Tina
