### ISSUE TITLE
Document the default value for the BCL threshold on the default Anti-spam policy.

### ISSUE THREAD

**Issue by NoahsMyBro** [MicrosoftDocs/microsoft-365-docs#2958]
In the brief table describing the different BCL levels, should include an asterisk that indicates the threshold set in the default, Out-Of-The-Box Anti-Spam Policy. Or at least document the default threshold somewhere on the page.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58067ff3-737e-441e-1812-a50bdb97d832
* Version Independent ID: fa3aba35-e8d9-cff6-13c2-1c892c3f2cc4
* Content: [Bulk complaint level values - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/bulk-complaint-level-values?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/bulk-complaint-level-values.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/bulk-complaint-level-values.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@NoahsMyBro, OK. Fixed.

Thanks for the feedback.

Closing.

**Comment by NoahsMyBro** [comment]
Fantastic, thanks!
