### ISSUE TITLE
Could not locate OneDrive

### ISSUE THREAD

**Issue by Dakineintx** [MicrosoftDocs/microsoft-365-docs#2959]
I am stuck here. I have access to the site and can browse out to the OneDrive.

Getting the URL for each user's OneDrive for Business site.
	You cannot call a method on a null-valued expression.
	At E:\eDiscovery\CreateCaseUsersEmailOneDrive\Step_2.ps1:110 char:1
	+ $strAuthCookie = $spCreds.GetAuthenticationCookie($AdminUrl)
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
	    + FullyQualifiedErrorId : InvokeMethodOnNull

WARNING: Could not locate OneDrive for email.address@something.com

LocationsNotOnHold.txt contents
Users without OneDrive locations
================================
email.address@something.com

I hard coded the AdminURL. is that not allowed?
$AdminUrl = "https://tenantname-admin.sharepoint.com"
$mySiteUrlRoot = "https://tenantname-my.sharepoint.com"

**Comment by msbemba** [comment]
@Dakineintx Thank you for your feedback. Could you please provide the document that you would like to modify or have questions with?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @Dakineintx We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
