### ISSUE TITLE
Duplication in URL endpoints specification

### ISSUE THREAD

**Issue by qiufasheng** [MicrosoftDocs/microsoft-365-docs#2963]
Hi, Dear Office team,

I found there are a lot of overlapping in the URL specification. For example in id 37, below endpoints are listed. Isn't *.sharepointonline.com covering all the rest already? Any reason to list them separately? 

*.sharepointonline.com,cdn.sharepointonline.com,privatecdn.sharepointonline.com,publiccdn.sharepointonline.com,spoprod-a.akamaihd.net,static.sharepointonline.com

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@qiufasheng Thank you for your feedback. We will check with the author for more information and let you know.

Thanks
Sri

**Comment by msbemba** [comment]
@JoeDavies-MSFT I was not able to edit the IP or the URL's, Probably because this is a highly structured document. Could you please update the Overlapping URL's like *.sharepointonline.com,cdn.sharepointonline.com,privatecdn.sharepointonline.com,publiccdn.sharepointonline.com,spoprod-a.akamaihd.net,static.sharepointonline.com as there is *.sharepointonline.com covering all 

CC: @yogkumgit 

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@qiufasheng I have forwarded your request to the product team that manages the list of endpoints for their consideration in a future update. Thanks for letting us know.
