### ISSUE TITLE
Is there a way to measure the specific Office Templates (Word, Excel, PPT, etc) which a user uses (touches, activates)

### ISSUE THREAD

**Issue by RKD993** [MicrosoftDocs/microsoft-365-docs#2966]
Need to be able to find out how users are using Templates (dotx, dotm, etc). Surely this should be possible through the analytics. We need to audit the use of such templates in large government organizations. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de44679b-998b-3de8-292b-d2993af9bad9
* Version Independent ID: 7fd9ecf7-0468-d01e-dcca-d18a19ebb7c2
* Content: [Microsoft 365 usage analytics data model - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics-data-model?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics-data-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics-data-model.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@RKD993 Thank you for your feedback. I'll be checking this in the backend and will update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@Sirkkuw I had tested this in my tenant and looks like there is no place to get information about templates (Dotx, dotc, etc..) activated or used by users. Is there a way to find that out via M365 usage Analytics?

CC: @yogkumgit 

Thanks
Sri

**Comment by Sirkkuw** [comment]
I don't know. I will ask someone on the PG.

**Comment by msbemba** [comment]
@RKD993 Thank you for your feedback. We have checked with the product group and we do not have this capability today. 

@yogkumgit No changes required in the document, please close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @RKD993 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
