### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by Appie1701** [MicrosoftDocs/microsoft-365-docs#2967]
Just a small typo thing, but the purists might notice :-) It is OneDrive for Business and not One drive.

Kind regards,

Albert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c2bb05c-4f7c-58cf-6b72-22af2b0377b1
* Version Independent ID: 184b8cb5-327a-41c5-6e61-1cae40965994
* Content: [Use sensitivity labels as conditions in DLP policies (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-sensitivity-label-as-condition?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-sensitivity-label-as-condition.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-sensitivity-label-as-condition.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Appie1701 Thank you for your feedback. We have fixed this via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2981

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Appie1701 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
