### ISSUE TITLE
More ;365 payload to be added

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/microsoft-365-docs#2968]
Hey, 
There are payload which is not in the list e.g Booking, Shifts, Todo etc. 
Can you please add all payloads to the page on not only the major once?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by msbemba** [comment]
@JohanssonMarkus Thank you for your feedback. These services use Exchange and teams to store data.

1)  Microsoft To do Data is stored as tasks in your Exchange Online mailbox, which also hosts data from other Exchange modules such as emails, events, contacts, and/or notes. 

2) All customer content is stored in the Exchange Online mailbox that hosts the organization's Bookings.

3) Microsoft Shift is a native app of MS Teams so this adheres to the MS team's data location.

Hope this helps.

Thanks
Sri

**Comment by JohanssonMarkus** [comment]
Ok make sence, will you upate the website with the same?
/Markus

**Comment by msbemba** [comment]
@JohanssonMarkus The document has been updated via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3009

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JohanssonMarkus 
Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
