### ISSUE TITLE
Guest users in Microsoft 365 admin center Typo

### ISSUE THREAD

**Issue by cuthbertnibbles** [MicrosoftDocs/microsoft-365-docs#2969]
Once you have added a **uer** in the Azure AD portal, that user will also be listed on the Guest users page in the Microsoft 365 admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1015a9d3-f0bb-dad5-7210-e3dd9b62881c
* Version Independent ID: 5c517c9b-cd05-2794-2f5d-c89c4d72b4a4
* Content: [Guest users in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-guest-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-guest-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-guest-users.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@cuthbertnibbles Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3015
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cuthbertnibbles Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
