### ISSUE TITLE
Preview information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2973]
[Enter feedback here]

Please add documentation about the a preview version of Attack simulator that is now available at https://security.microsoft.com/attacksimulator?viewid=overview 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbdcbd5-7bd2-6b55-b72c-cbedfdea776c
* Version Independent ID: 1e6198f8-6ef1-6227-c9e8-f31944a5d1db
* Content: [Attack Simulator in ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulator.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@DaniHalfin Gentle reminder, please add your comment and help us resolving this issue. Thanks

**Comment by DaniHalfin** [comment]
Hi @DeanGross ,
Information about the Attack simulation training experience currently in public preview on the Microsoft 365 security center is available as follows:

- [Simulate a phishing attack](https://docs.microsoft.com/microsoft-365/security/office-365-security/attack-simulation-training)
- [Create a custom payload for Attack simulation training](https://docs.microsoft.com/microsoft-365/security/office-365-security/attack-simulation-training-payloads)
- [Gain insights through Attack simulation training](https://docs.microsoft.com/microsoft-365/security/office-365-security/attack-simulation-training-insights)

cc: @yogkumgit

**Comment by DeanGross** [comment]
Sorry, i was not very clear. It would be helpful if this page, which currently describes the old version, that is being replaced contained some information about the new version or a link to the documentation you reference. @DaniHalfin

**Comment by DaniHalfin** [comment]
Hi again @DeanGross ,
Thanks for clarifying. I've submitted a change to link off to the public preview content from this page. Hope this fully addresses this issue.
