### ISSUE TITLE
Action Types

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#2974]
[Enter feedback here]

When I look at the new Compliance Manager filters, I see new action types for : Technical, Procedural, Documentation, Operational, Contractual, Management and Privacy. I don't see any discussion about these types and their recommended usage. Please update the documentation to provide us some guidance on how MS envisions their use. The categories seem to overlap and its not clear to me how this many categories will provide value. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491e66c0-bfe6-58fa-4a1e-d79ee4ac0e2b
* Version Independent ID: 676dbe71-1ed1-e5db-2f16-f7c12c7565f7
* Content: [Compliance score calculation - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score-calculation?view=o365-worldwide#technical-and-non-technical-actions)
* Content Source: [microsoft-365/compliance/compliance-score-calculation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-score-calculation.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Hello - engineering is looking into filtering types that were impacted in the most recent deployment. We'll get back to you soon with an update, thanks.

**Comment by chvukosw** [comment]
Hi there - the only action types are operational, documentation, and technical, as listed in the documentation. If you are seeing other filter types, you may need to accept the latest versioning updates for improvement actions - thanks.

**Comment by DeanGross** [comment]
@chvukosw I have accepted all of the updates that I have seen but I'm still seeing the action types that are not listed in the documentation. Should I open a support ticket?
