### ISSUE TITLE
Clarification on New Filters of Message Center Message Types

### ISSUE THREAD

**Issue by ClearSkyyes** [MicrosoftDocs/microsoft-365-docs#2975]
Original question (updated/clarified question at the bottom):  The Message Type in M365 Message Center now has 4 types, but this document only lists 3. The Data Privacy type is missing. What is a Data Privacy message? Can an example be included?

msbemba commented 23 hours ago
@ClearSkyyes Thank you for your feedback. Data privacy label is not a different message type instead it is an option for the admins to choose what type of information they want to look in the admin center. For example, In an organization, there could be a global admin, an exchange admin, a team admin, and a data privacy admin. The global admin most likely will want to see any and all alerts but the Data Privacy admin may only care about seeing things specific to Data Privacy. So the options are available to pick and choose what they want to see in the message center.

Hope this helps!

Thanks
Sri.

@yogkumgit
 
Collaborator
yogkumgit commented 7 hours ago
@msbemba Thank you very much for the contribution and sharing this explanation. @ClearSkyyes Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

ClearSkyyes commented 11 seconds ago
**This is now listed as a filter, so I assumed it was being split out as a new message type. Am I understanding correctly that Data Privacy messages will actually be one of the primary types (Plan for Change, Stay Informed, Prevent/Fix Issue) and this other option available in the filter will just be an additional field that shows elsewhere in that message?**

**Comment by yogkumgit** [comment]
@ClearSkyyes Thanks. closing with  #2936 reference.
