### ISSUE TITLE
Link Error: Verify the device is upgraded to Windows 10 Business

### ISSUE THREAD

**Issue by proofy** [MicrosoftDocs/microsoft-365-docs#298]
the link anker Verify the device is upgraded to Windows 10 Business dosn't wirk

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@proofy - Thank you for pointing this out.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@proofy  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
