### ISSUE TITLE
Wrong Tech Support Hours

### ISSUE THREAD

**Issue by bradhawkins85** [MicrosoftDocs/microsoft-365-docs#2986]
The web page says tech support is open 24x7 however when I call I get a message the office is closed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91381a76-fc2d-c5c2-90f0-60eb7e21c5de
* Version Independent ID: 1f5231d0-9008-e858-b446-124a3801d68b
* Content: [Support information for Australia - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/australia?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/australia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/australia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@bradhawkins85 Thank you for your feedback. I'll check with the Author to see if we can verify with the concerned team before we can make this change.

Thanks
Sri

**Comment by msbemba** [comment]
@cmcatee-MSFT I tested it at 4 PM EST i.e. 6 AM AEST and it did not work. It worked later at 9:30 AM AEST. Could you please help us in identifying the correct timings so that the document can be updated accordingly.

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@msbemba I've escalated this internally to have it investigated.

**Comment by cmcatee-MSFT** [comment]
@bradhawkins85  or @msbemba We need a bit more information to know where the call is routing to. Would you please tell me which number you dialed, what options you selected in the call menu, and what time you tried to call?

**Comment by bradhawkins85** [comment]
I have replied via email, thank you.

**Comment by cmcatee-MSFT** [comment]
@msbemba Can you please try the call again and then send the call information to me directly?

CFN/TFN/Customer dialing number
ANI(Caller's number)
Date of call
Time of call with time zone
Outgoing/incoming call
The options you selected that resulted in hearing the message "office is closed"
Call ID/interaction ID (if available)

**Comment by msbemba** [comment]
@cmcatee-MSFT 

CFN/TFN/Customer dialing number : +61 02 8223 9959 and 1800 197 503
ANI(Caller's number) + 91 9972711773
Date of call : 06 October 2020 
Time of call with time zone 11:45 PM IST 
Outgoing/incoming call :Outgoing call
The options you selected that resulted in hearing the message "office is closed" : Selected 1 For o365 Business Selected 1 again for Technical support-- > It says Please wait while we connect to a tech support representative and then we hear a recording saying that the offices are closed.
Call ID/interaction ID (if available):N/A

**Comment by cmcatee-MSFT** [comment]
@msbemba Please send the info to me directly at cmcatee@microsoft.com

**Comment by cmcatee-MSFT** [comment]
This has been escalated internally. Closing this issue since no documentation change is needed.
