### ISSUE TITLE
Pages not clear / DKIM broken in Exchange Admin

### ISSUE THREAD

**Issue by flowl** [MicrosoftDocs/microsoft-365-docs#2988]
I am trying to [setup DKIM keys in Exchange 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide).

The section `Steps you need to do to manually set up DKIM` is incomplete and not working at all.

1. Publish two CNAME records for your custom domain in DNS

I have done that: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_exchon-mso_o365b/no-dkim-keys-saved-for-this-domain/7538665a-c450-4b99-b81f-4f0b72a7e08c?tm=1600971613735

2. To enable DKIM signing for your custom domain through the admin center

This step is not working, the admin interface doesn't see any keys automatically or let us enable DKIM.

2. (alternative) To enable DKIM signing for your custom domain by using PowerShell

This step requires `Connect to Exchange Online PowerShell.`.

I tried connecting to Exchange Online using MacOS PowerShell and Windows 10 PowerShell and the instructinos do not work for both.

Either due to [Microsoft declaring its own packages broken without alternative](https://github.com/PowerShell/PowerShell/issues/5561) or due to errors like [`New-ExoPSSession : unknown_user_type: Unknown User Type`](https://stackoverflow.com/questions/64068859/new-exopssession-unknown-user-type-unknown-user-type).

Please publish an easy to follow instruction on how to enable DKIM in Microsoft 365 Office 365 Exchange 365.

Consider using a vanilla computer for writing the docs and not a fully setup Microsoft admin computer with all dependencies and workarounds already baked in.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6adeef66-5e54-ba2f-37ac-c1898ef942c6
* Version Independent ID: f8a6eda6-b300-dc76-4392-9aeb6c532822
* Content: [Connect to all Microsoft 365 services in a single PowerShell window - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by flowl** [comment]
I got it all figured out after a dozen of exceptions and unexpected problems.

I list some:

1. You cannot put your own keys, created on your own machine, into Exchange via web interface. This route I expect it to be done but I was completely wrong. A security rule of thumb is: Do not trust keys you have not generated yourself. Microsoft is breaking this security rule.

2. Keys have to be created using PowerShell on the outlook online machine.

3. The whole step of enabling DKIM is starting from the wrong way. It should start by making clear how setup works and creating keys. Instead, it currently starts with DNS entries. This should be the last part, not the first.
4. Even all our data is going through Germany, we cannot use German-Cloud login environment, that's confusing.
5. OSX support is poor and needs workarounds and dependencies installed which are not part of official docs.
6. Dependencies need to be installed on the local machine instead of beeing present on the remote machine. This is completely contraire to what I expect and what I'm used to as a unix using person.

**Comment by msbemba** [comment]
@flowl Thank you for your feedback. Sorry that you had to go through a lot before getting this solved. But to answer a few questions and reiterate things that you mentioned above

To Enable DKIM for a Custom domain

1)Add the DNS Entry.
2)Enable DKIM Via EAC or Powershell.
3)Test to Confirm DKIM signing is configured properly for Microsoft 365.

Hope this helps!

Thanks
Sri

**Comment by flowl** [comment]
Thank you Sri for your reply, tbh, having it setup once, it works like a charm.

This is the most confusing part:

> 2. Enable DKIM Via EAC or Powershell

DKIM keys can't be generated through EAC.

The correct way is:

1. Create keypair using PowerShell
2. Add CNAME DNS entry (no TXT required)
3. Enable DKIM in EAC
4. Test and confirm signing

**Comment by JoeDavies-MSFT** [comment]
@flowl Can you add your conclusion above as an issue to the https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide article? The author will investigate and update its content appropriately. 

Also, does the https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide article need to be updated based on your experiences?

Thanks

**Comment by flowl** [comment]
Hello @JoeDavies-MSFT,

I couldn't get things to work on OSX and on Windows there is one dependency I had to install:

**Comment by JoeDavies-MSFT** [comment]
@flowl Thanks. Please add your conclusion above as an issue to the https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide article? The author will investigate and update its content appropriately. Thanks for letting us know.
