### ISSUE TITLE
Incorrect Name servers?

### ISSUE THREAD

**Issue by ChrystalSolutions** [MicrosoftDocs/microsoft-365-docs#2989]
Shouldn't Name Servers 3 and 4 be:
ns3.bdm.microsoftonline.com
ns4.bdm.microsoftonline.com

Current Name Servers 2, 3 and 4 are all: 
ns2.bdm.microsoftonline.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c52d59a-7466-a5a8-7031-e4ea7b782f57
* Version Independent ID: e02a33bc-12c6-4192-cf3f-bcea567085c3
* Content: [Change nameservers to set up Microsoft 365 with any domain registrar - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@ChrystalSolutions Thank you for your feedback. We see the Name servers are updated correctly to 

First nameserver | ns1.bdm.microsoftonline.com
Second nameserver | ns2.bdm.microsoftonline.com
Third nameserver | ns3.bdm.microsoftonline.com
Fourth nameserver | ns4.bdm.microsoftonline.com

@yogkumgit  There are no changes required in this document and the issue can be closed.

Thanks
Sri
