### ISSUE TITLE
Broken next step links for multifactor authentication page. 

### ISSUE THREAD

**Issue by dahifi** [MicrosoftDocs/microsoft-365-docs#2991]
[Set up multi-factor authentication](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)

Three of the links listed under next steps are broken: 

How to register for their additional verification method
How to deal with situations like a new smart phone
Troubleshoot MFA sign-ins

**Comment by msbemba** [comment]
@Sirkkuw  We have three links in the document which are broken and all are pointing to support.microsoft.com articles. It looks like these documents are broken and we don't have an equivalent document on docs.microsoft.com. Could you please tell us if these links can be removed or is this a temporary issue with some of these support.microsoft.com links?

Three links in question are:

1) How to register for their additional verification method - https://support.microsoft.com/office/ace1d096-61e5-449b-a875-58eb3d74de14

2) Troubleshoot MFA sign-ins - https://support.microsoft.com/en-us/office/fix-common-problems-with-multi-factor-authentication-6951be76-af50-49a4-847f-21391eaa59f2

3)How to deal with situations like a new smart phone - https://support.microsoft.com/office/6951be76-af50-49a4-847f-21391eaa59f2

Thanks
Sri

**Comment by Sirkkuw** [comment]
@yogkumgit please take out for now - I am following up with the team as to why these are not redirected.

**Comment by msbemba** [comment]
@Sirkkuw We have removed the links via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3031


@dahifi Thank you for your feedback. We have found these links to be broken and removed from the document. Once these links are restored, The Author will be updating the document as well.

Thanks
Sri

**Comment by Sirkkuw** [comment]
Can you replace the three with this one for now:
https://support.microsoft.com/en-us/help/4577374/what-is-multifactor-authentication

**Comment by msbemba** [comment]
@Sirkkuw  I have added the URL as per your suggestion.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dahifi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
