### ISSUE TITLE
SMTP also included

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/microsoft-365-docs#2993]
Hi. This document references clients connecting to Exchange services but implies OWA/MAPI connections. Can you confirm that SMTP connections must also support TLS1.2 from October 15th?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f7e4139-a562-6b81-6584-277efc4f6103
* Version Independent ID: e812b33a-f183-8b6a-bab0-447ddab2f26f
* Content: [Preparing for TLS 1.2 in Office 365 and Office 365 GCC - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/prepare-tls-1.2-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prepare-tls-1.2-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @WorkShay
* Microsoft Alias: **shmehta**

**Comment by WorkShay** [comment]
Are you referring to SMTPS? SMTP is at the application layer. TLS is the transportation layer. So if SMTP is being secured and transported using TLS (aka SMTPS) then it needs to support TLS 1.2 from Oct 15.

**Comment by msbemba** [comment]
@yogkumgit There are no changes in this document. This can be closed as this is answered.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cabtilx Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
