### ISSUE TITLE
I want to search for specific content items in the body of the email for which that I am looking for

### ISSUE THREAD

**Issue by cfizz34** [MicrosoftDocs/microsoft-365-docs#2994]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@cfizz34 There is not a "body" search property. You can use keywords in the keyword box to return messages that contain that keyword in the body.

**Comment by cfizz34** [comment]
how do i do that with a content search?

**Comment by markjjo** [comment]
@cfizz34 See: https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide#create-a-search

![image](https://user-images.githubusercontent.com/36746813/94466681-b2a72800-0176-11eb-9793-cac1859c2a2c.png)

**Comment by cfizz34** [comment]
how do i do it via powershell like I do these?   ContentMatchQuery                     : (c:c)'(subject:"info") and (from:domain.com) and
                                        (sent>=01/26/2020)'
