### ISSUE TITLE
Please allow content search to find YAMMER only specific related items

### ISSUE THREAD

**Issue by cfizz34** [MicrosoftDocs/microsoft-365-docs#2995]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@cfizz34 Please see: https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide#searching-yammer-groups

We'll look into adding similar content about searching Yammer in the keywords and queries topic.
