### ISSUE TITLE
Download link for Lab files invaild

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/microsoft-365-docs#300]
It appears that the link to download the Modern Desktop Deployment and Management Lab Kit (https://aka.ms/mddlabs_evalcenter) is invalid. It does redirect to the Evaluation Center but looks like a generic landing page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Modern Desktop Deployment and Management Lab Kit](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab#download-the-modern-desktop-deployment-and-management-lab-kit)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Hi - thanks for this, we are looking into it now and will get it corrected shortly!
