### ISSUE TITLE
Service admin is the incorrect name

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/microsoft-365-docs#3003]
The Service Admin role has been renamed and is now Service Support Admin role as detailed here https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#service-support-administrator

Please update this document and any others that may have the wrong name.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@scottsa-msft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3014

Thanks
Sri

**Comment by msbemba** [comment]
@scottsa-msft The Changes have been updated. Thank you again for your feedback.

@yogkumgit The PR has been merged, the issue can be closed now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @scottsa-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
