### ISSUE TITLE
Download link for Lab files invalid, again

### ISSUE THREAD

**Issue by Schwa87** [MicrosoftDocs/microsoft-365-docs#301]
Hi,

The lab files are not working again. Can you please fix the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Modern Desktop Deployment and Management Lab Kit](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab#feedback)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Hi - we are working on resolving this issue, thanks!

**Comment by Schwa87** [comment]
Please leave this open until it is finished.

**Comment by Hoosier-IT** [comment]
Has this issue been resolved? It appear to be happening with all product in the Microsoft Evaluation Center. The customer support line does not appear aware of the issue and hung up on me after 45 min on hold waiting for a solution or direct link.

**Comment by ayeso** [comment]
Yup looks like its all eval site. I was trying as well.

**Comment by Schwa87** [comment]
Can't imagine it'd take long to link to the files, but it could also just be a bigger issue. Hopefully it's fixed soon.

**Comment by Hoosier-IT** [comment]
Certainly hope so... exam is coming up and I'd like the lab for practice. Site reporting new error: Respond in the allocated time, the server did not. (not sure if that's better or worse than, Not Found)

**Comment by Hoosier-IT** [comment]
Appears to be working now

**Comment by JGruszczyk** [comment]
Eval center has been fixed

**Comment by alliedcvil** [comment]
It's not functional again.

**Comment by JGruszczyk** [comment]
We have contacted the eval center team and waiting for the fix to go in place
