### ISSUE TITLE
Please give minimum version of Powershell needed to run this script

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/microsoft-365-docs#3011]
Please give minimum version of Powershell needed to run this script. I had a Server 2012R2 with Powershell 5.0.10586 but it didn't work with that (JSon error) until I upgraded to Powershell version  5.1.177 so I suspect there is a version in between somewhere that is minimum version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@MikePlumleyMSFT Hello Mike, I was able to test this only with newer versions 5.1XX and it works. According to the PowerShell gallery, the minimum requirement to install AzureADPreview module is PowerShell 3.0  -https://www.powershellgallery.com/packages/AzureADPreview/2.0.2.117

Do you know if this was changed so that I can update the document with the minimum requirements?

Thanks
Sri

**Comment by MikePlumleyMSFT** [comment]
@msbemba the PowerShell gallery is correct place to document PowerShell versions required for its modules.

**Comment by msbemba** [comment]
Is there any contact to make these changes on the PowerShell Gallery or get a confirmation if the existing minimum requirement (PowerShell 3.0) ?

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in this document and this can be closed.

 The PowerShell team will need to update this in the PowerShell gallery as it is the right place to document the versions required for its modules.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @richard-artes Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
