### ISSUE TITLE
How is the "oldest rule" calculated?

### ISSUE THREAD

**Issue by henascim** [MicrosoftDocs/microsoft-365-docs#3012]
Under the tittle "Only one retention label at a time", when it is mentioned that "If there are multiple rules that assign an auto-apply label and content meets the conditions of multiple rules, the retention label for the **oldest** rule is assigned.", how exactly is the oldest rule calculated? Is it by the creation date? Or is it by the "last modified" date?
The document could be a bit clearer in that regard.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@henascim  "Oldest" is by creation date, not modified date.  I'll clarify this in the docs, thanks for your question!
