### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by StereoRocker** [MicrosoftDocs/microsoft-365-docs#3017]
[Enter feedback here]
The link "How to deal with situations like a new smart phone" under Next Steps is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@StereoRocker Thank you for your feedback. We are working with the author to see if the link can be replaced or removed. 
I will update the document shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@StereoRocker Thank you for your feedback. We discussed with the author and this link is no longer available so we have removed it from the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3031

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @StereoRocker Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
