### ISSUE TITLE
Format of partner CSV

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#3018]
[Enter feedback here]
Is the order of the fields in the CSV correct?
Document states "....or the OEM name, serial number, and model (in that column order)". All other references I've seen have the order Device serial number,,,Manufacturer name,Device model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd1cbbf-99b1-f6ca-94ee-8f30015339f9
* Version Independent ID: c4d8538b-f436-7e3d-0372-0aae84955e01
* Content: [Steps for Partners to register devices - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/register-devices-partner?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-started/register-devices-partner.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/register-devices-partner.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@ceaton001 Thank you for your feedback. We have corrected the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3061

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ceaton001 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
