### ISSUE TITLE
How to rollback DKIM 

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/microsoft-365-docs#3019]
[Enter feedback here]
I understand from that document how to enable DKIM on a custom domain (contoso.eu.com for example) 
and there is also a section on how to [disable DKIM](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#disabling-the-dkim-signing-policy-for-a-custom-domain) - but that same section says: 
_"Disabling the signing policy does not completely disable DKIM. After a period of time, Microsoft 365 will automatically apply the default policy for your domain._"

**As such what is actually required to rollback enabling DKIM?**

I am looking for steps in Office365 EAC and on public DNS side.

My idea of rollback is:

1. Disable DKIM in Office356 EAC

2. Remove the selectors DNS records from public DNS.

Is this correct?

Thanks, M

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@ii-batman THank you for your feedback. It is correct that Microsoft will automatically apply the default policy for your domain after disabling the signing policy. if you do not want that to happen, You are correct on the steps-- Disable  DKIM and delete the DNS records( both the Cname records) from the public DNS.

Hope this Helps!

@yogkumgit  No changes are required on the document and this can be closed.

Thanks
Sri

**Comment by ii-batman** [comment]
@msbemba  @yogkumgit 
Before you close can you expand more on the "My domain MS Default Policy"?
What is the policy set as and how can I find out more about what is my Domain Default Policy? 
Thanks for the assistance.

**Comment by msbemba** [comment]
@ii-batman Thank you for your feedback.  Default policy means Microsoft 365 automatically creates a 1024-bit DKIM public key for your default domain and the associated private key which we store internally in our datacenter, It is not available to users/admins via Powershell or EAC. However, you can view them in the header information.

If you do not enable DKIM or disable DKIM (and delete the DNS records) Microsoft 365 uses a default signing configuration for domains that do not have a policy in place. This means that if you do not set up DKIM yourself, Microsoft 365 will use its default policy and keys it creates to enable DKIM for your domain.

More detials are also available under -https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#default-behavior-for-dkim-and-microsoft-365

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ii-batman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ii-batman** [comment]
@msbemba 
Thank you for your quick reply.
To finallise this is my understanding

- If no DKIM is enabled then the Default Policy applies to contoso365.onmicrosoft.com only and **not to my custom domains**
- If I enable DKIM for my custom domain (contoso.eu.com) I will need the selector keys and public DNS records 
- If I want to disable DKIM for my custom domain (contoso.eu.com) then all I need to turn it off in Office365 and remove my DNS records - this means that no DKIM is enable for custom domain but MS will apply the Default Policy to my domain (contoso365.onmicrosoft.com)

I hope this is clear?
Thanks Sri for all your help - really appreciate it.

**Comment by msbemba** [comment]
@ii-batman That is correct.  If you enable DKIM yourself, the domain will be the same as the domain in the From: address, If you don't, it will not align and instead will use your organization's initial domain.

Thanks
Sri
