### ISSUE TITLE
Clarity on DLP Permissions

### ISSUE THREAD

**Issue by josuvil** [MicrosoftDocs/microsoft-365-docs#3022]
The "Permissions for DLP Reports" section discusses three roles. But it is unclear to me if either one or all three are required. I'm assuming that any one of the three roles will allow you to view DLP reports, correct? Or are all three required? Also, I wonder if you can add which Azure AD Roles can be used to view DLP Reports. For example, you have Azure AD Compliance Admins, Compliance Data Admins, Global Reader, Security Admins, and Security Reader roles. I understand that belonging to some Azure AD roles grants access to some roles in EAC. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec12506-ca29-0a03-3b01-699cb22b7ab7
* Version Independent ID: 6dc6083d-fcde-3622-5653-61c5be4bb5db
* Content: [View the reports for data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/view-the-dlp-reports?view=o365-worldwide&source=docs#permissions-for-dlp-reportshttps://docs.microsoft.com/en-us/office365/securitycompliance/view-the-dlp-reports#permissions-for-dlp-reports)
* Content Source: [microsoft-365/compliance/view-the-dlp-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-the-dlp-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us resolving this issue. Thanks

**Comment by chrfox** [comment]
investigating

**Comment by chrfox** [comment]
investigating
