### ISSUE TITLE
URL incorrect

### ISSUE THREAD

**Issue by brucelaing** [MicrosoftDocs/microsoft-365-docs#3028]
The URL for Email issues for priority accounts, returns a 404 page error.

https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/mail-flow-insights/mfi-email-issues-for-priority-accounts

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fe9020-6803-bee8-7fcc-fae3971e6feb
* Version Independent ID: 480b994c-7d3f-d234-8847-e415360c6bf7
* Content: [What's new in the Microsoft 365 admin center? - Microsoft 365 admin](https://docs.microsoft.com/en-GB/microsoft-365/admin/whats-new-in-preview?WT.mc_id=365AdminCSH&view=o365-worldwide)
* Content Source: [microsoft-365/admin/whats-new-in-preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/whats-new-in-preview.md)
* Service: **o365-administration**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @brucelaing Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
