### ISSUE TITLE
Bookings connect to Facebook

### ISSUE THREAD

**Issue by ecomsetters** [MicrosoftDocs/microsoft-365-docs#3029]
[Enter feedback here]
I was sent to this page from Microsoft Bookings by clicking the Connect button where the option to Connect Microsoft Bookings to Facebook is but, this article is not showing how to do this anyway...

I've tried check other sites and I can see a previous version of Bookings really was integrated with Facebook but apparently not anymore... is that right?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb53eb7-85a1-6aa0-dfd1-e2b54586008a
* Version Independent ID: 5532470a-a47d-e3bd-4e74-02b2c822cae1
* Content: [Microsoft Bookings](https://docs.microsoft.com/en-gb/microsoft-365/bookings/bookings-overview?redirectSourcePath=%252farticle%252fconnect-microsoft-bookings-to-your-facebook-page-858db050-3d10-4bb5-82f1-df6ebeda2685&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-overview.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ecomsetters Thank you for your feedback. We worked with the author and the product group and found that we are no longer supporting Booking's connection to Facebook. So we have informed the product group to get the button removed from the bookings page to avoid any confusion. Thank you again for the feedback.

@yogkumgit  There are no changes to the document  and we can proceed with closing the issue.

Thanks
Sri

**Comment by msbemba** [comment]
@ecomsetters we’re no longer supporting Bookings connection to Facebook. We are working with the PM to file a bug to get the button removed.

@yogkumgit There are no changes required in the document and the issue can be closed.

CC: @kwekuako 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ecomsetters Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
