### ISSUE TITLE
SSPR Options have been updated

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/microsoft-365-docs#3030]
In step 2, the option to set/update additional phone/email has moved from **Settings & Privacy** to the **Security Info** section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecf0dbf6-b2f8-5370-fd04-f7a13073835a
* Version Independent ID: 8b58ecef-f957-4360-08a5-80d6fe8886e3
* Content: [Update your admin phone number and email address - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/update-phone-number-and-email-address?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/update-phone-number-and-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/update-phone-number-and-email-address.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@kerbos Thank you for the feedback. The settings are under **My account** \> **Settings and Privacy*-->In the **Privacy** Tab under  **Contact Preferences** section, select **Contact preferences for admins only**. I have made the changes Via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3058

The settings under Security info is to add an additional verification method for a password reset (users) But the Privacy tab is used for contact preferences for admins only.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kerbos Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
