### ISSUE TITLE
Auto-apply labels and precedence

### ISSUE THREAD

**Issue by joemccla** [MicrosoftDocs/microsoft-365-docs#3032]
[Enter feedback here]
The rules here: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#the-principles-of-retention-or-what-takes-precedence

Should mention that auto-apply labels still take precidence over broad location specific retention policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @joemccla - are you referring to this?

"If a retention policy includes a specific location, such as a specific user's mailbox or OneDrive account, that retention policy takes precedence over another retention policy that applies to all users' mailboxes or OneDrive accounts but doesn't specifically include that user's mailbox." 

Or do you mean all auto-apply polices that use labels take precedence over retention policies that don't use labels?

**Comment by yogkumgit** [comment]
@cabailey Thank you very much for digging deep into it.  @joemccla We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
