### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Noah-de-Wit** [MicrosoftDocs/microsoft-365-docs#3036]
The link on "Email issues for priority accounts" is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 134a0b6c-728a-d952-2f1c-a6fd868db10c
* Version Independent ID: 640bb6ef-2003-c604-9d25-380b774cbbc0
* Content: [Manage and monitor priority accounts - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/priority-accounts?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/priority-accounts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/priority-accounts.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Noah-de-Wit Thank you for your feedback. The reference document has been modified hence it leads to a broken link

 The hyperlink has been removed from the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3060 to void confusion and this will be updated once there is a relevant document ready.

Thanks
Sri

**Comment by yogkumgit** [comment]
The topic has been updated and the link is going to the correct location.
