### ISSUE TITLE
Data Move No Longer Allowed

### ISSUE THREAD

**Issue by jasonseatosky** [MicrosoftDocs/microsoft-365-docs#3038]
For MSP's who are using delegated admin there was no notification of a data move deadline. The deadline to migrate data to the Canadian data centre has now passed. We have multiple government clients who NEED their data migrated to the Canadian servers and M365 support is not willing to assist us.

How can we put in a request to move the clients data? Who can assist us with this request? I'm grasping at straws here. Please email me at jason@seatosky.com
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87cb379c-82ae-0a6e-8dd5-0c41b09364ab
* Version Independent ID: a15c3919-e63e-f0dc-bd6b-45f311b387b5
* Content: [How to request your data move - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/request-your-data-move?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/request-your-data-move.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/request-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by msbemba** [comment]
@jasonseatosky Thank you for your feedback. Yes, I see the deadline was June 30, 2020. Ideally, it needs to be done via the M365 support as we don't have much access to this. However, I will check with the author to see if there is a possibility to make this happen. I shall update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @jasonseatosky  Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jasonseatosky** [comment]
Hello,

I have opened the following ticket numbers with Office 365 support and they are not actioning my reques
t to have the customer data moved to Canada.

22109347
22045204
22108981
22109070
22109173
22063336
22109218
22109246
22109366



Jason Bristow
Managing Partner
t: 604.628.6970 | d: 604.628.6973 |
 tf: 1.877.662.2759
a: 
2554 Vine St., Vancouver, BC, V6K 3L1

**Comment by msbemba** [comment]
@jasonseatosky We understand your situation, but our team handles documentation and for support related queries you will have to contact the support team. If they are not actioning due to missing the deadline then I'm afraid it might not be possible to move the data.

Thanks
Sri
