### ISSUE TITLE
Wording clarification

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#3039]
[10:05 AM] Alisdair Douglas
    25 seconds between receipt and delivery on the detailed trace,  This kind of says it but really badly worded

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-attachments?view=o365-worldwide#dynamic-delivery-in-safe-attachments-policies

There are scenarios **where Safe Attachments is unable to scan messages:**

	
Messages in public folders.
	
		
Messages that are routed out of and then back into a user's mailbox using custom rules.
	

Messages that are moved (automatically or manually) out of cloud mailboxes to other locations, including archive folders.
	
	
	
Deleted messages.
	

that should read 'scenarios where dynamic delivery is unable to replace messages", as it uses http delivery to replace the attachment in the mailbox. If the mail is moved then cannot replace the attachment via http

Safe Attachments - Office 365Admins can learn about the Safe Attachments feature in Office 365 Advanced Threat Protection (ATP).docs.microsoft.com<https://teams.microsoft.com/l/message/19:ad2585045a8a48d1b50cbc1717471b77@thread.skype/1601543111371?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=eac17924-ac04-4443-b067-cad89610b39f&amp;parentMessageId=1601479751617&amp;teamName=EOP (Transport &amp; Security): CSS Technical Community&amp;channelName=General&amp;createdTime=1601543111371>

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5966b7b-cbaa-eaa2-c9d6-5c6e7218df74
* Version Independent ID: cfcc8772-be5d-009a-0805-62624835ac5f
* Content: [Safe Attachments - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-attachments?view=o365-worldwide#dynamic-delivery-in-safe-attachments-policies)
* Content Source: [microsoft-365/security/office-365-security/atp-safe-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-safe-attachments.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@aldoug, the original statement from the now removed Dynamic Delivery only topic said this:

> There are certain scenarios in which Safe Attachments (including Dynamic Delivery) is not supported. These include:

So I took that to mean more about Safe Attachments in its entirety and less about Dynamic Delivery specifically.

But you're saying that's incorrect?

**Comment by aldoug** [comment]
I would say it’s the other way round, safe Attachments will work in those scenario’s, only dynamic delivery wont. If they disable dynamic delivery the scan would complete before delivery and the following would be unaffected (im not sure on expectations with public folders)

•  Messages that are routed out of and then back into a user's mailbox using custom rules.
•  Messages that are moved (automatically or manually) out of cloud mailboxes to other locations, including archive folders.
•  Deleted messages.

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (0) 7876 657707

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by chrisda** [comment]
@aldoug, I reworded and refactored that section to only apply to Dynamic Delivery.

Thanks for the feedback.

Closing

**Comment by aldoug** [comment]
Nice one Chris, thanks

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (0) 7876 657707

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG
