### ISSUE TITLE
Consider updating documentation to reflect limitations on adding domains to protect

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#3040]
When adding domains to protect, the GUI indicates that you cannot add more than 20 domains, and PowerShell seems to limit this to 50 domains.  It may be worth adding this to this documentation for awareness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ea08aa-4520-8f48-93e2-0ce74cd43298
* Version Independent ID: 7be23d3d-f72b-abd3-e2c4-96ff3998a59b
* Content: [Configure ATP anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-atp-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dkotars, done. Thanks for the feedback.

Closing
