### ISSUE TITLE
Microsoft 365 Apps Usage Report - Web Column (formerly Active on Web) is always No

### ISSUE THREAD

**Issue by bt101** [MicrosoftDocs/microsoft-365-docs#3041]
It's unclear where one can report an issue with the actual Office 365 Admin Portal Usage Reports but I am hoping this will get the attention of the appropriate team.

Since late June 2020, potentially linked to when the activity values were changed from True/False to Yes/No, the Web column (formerly Is Active on Web) is always "No" for every user for every Office 365 Tenant regardless of their actual usage.  I believe this is an issue affecting every tenant's Microsoft 365 Apps Usage Reports and is not limited to the Tenants I have seen.

Here is a link to the actual usage report:
https://admin.microsoft.com/AdminPortal/Home#/reportsUsage/ProPlusUsage

**Comment by msbemba** [comment]
@bt101 Thank you for your feedback. I'm assuming this is more related to the document https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft365-apps-usage?view=o365-worldwide . I'll test the report and make changes to the document if need be. 

Thanks
Sri

**Comment by msbemba** [comment]
@bt101 Thank you for your feedback. I tested this on multiple tenants and found the same issue. Since this is a product bug and nothing needs to be changed on the document, I'd recommend you to contact support and pass the feedback.  You can open a support ticket from the need help section on the M365  admin center.

@yogkumgit This seems to be a product bug as per testing and no changes required in the document as of now. Please close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bt101 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bt101** [comment]
@yobougaz Thank you for confirming it's a product bug.  Given that you are a member of Microsoft and that this is a Microsoft Product bug I'm a bit surprised that you closed the issue and asked me to open an issue with the product team. Given you write the documents to support the product I would expect you would have a close relationship with the team and have an ability to pass the issue to the appropriate team including your findings.

**Comment by yobougaz** [comment]
@bt101 
Hello bt101, 

I apologize but I am not following you, was your message supposed to go to me or @yogkumgit ?

Thank you 😊
