### ISSUE TITLE
How to sync into my Azure SQL Server

### ISSUE THREAD

**Issue by zwiddoss** [MicrosoftDocs/microsoft-365-docs#3043]
Is there a way to sync the email activity data from the 365 admin portal to a table in sql server without having to upload a flat file?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be45e626-ed67-3f48-1a80-5d69f938638b
* Version Independent ID: de7bbfaa-17fb-01eb-fd74-a854d615dc23
* Content: [Microsoft 365 Reports in the admin center - Email activity - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/email-activity?WT.mc_id=365AdminCSH&view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/email-activity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/email-activity.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@zwiddoss Thank you for your feedback. The Email activity data is only available on the reports page in  M365 admin center. There are ways to connect or call the M365 Messaging system via logic apps that are used in Azure Sentinel. More information can be found in the blog -https://techcommunity.microsoft.com/t5/azure-sentinel/office-365-email-activity-and-data-exfiltration-detection/ba-p/1169652 

You can also contact the Azure Support team via the Need help section on the M365 Admin center.

Hope this helps!

@yogkumgit  As such there are no changes required in this document. Please close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @zwiddoss Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by zwiddoss** [comment]
@msbemba @yogkumgit I am circling back on this - the article shows how to use the logic app to send data to azure sentinal, but i do not use azure sentinal.  Is there anything on sending this to an Azure sql database?

**Comment by msbemba** [comment]
@zwiddoss This document pertains only to Email activity reports via the O365 Admin center. I'd recommend you contact Azure Support to see if there is a way to sync or pull the required data. You can contact them via the Need help section on the M365 Admin center.

Thanks
Sri
