### ISSUE TITLE
Limit?

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/microsoft-365-docs#3044]
Is there a limit to how many priority accounts can be monitored. Please call this out in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 134a0b6c-728a-d952-2f1c-a6fd868db10c
* Version Independent ID: 640bb6ef-2003-c604-9d25-380b774cbbc0
* Content: [Manage and monitor priority accounts - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/priority-accounts?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/priority-accounts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/priority-accounts.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@sinnamingrrl Thank you for your feedback. Apparently, You can actively monitor only up to 250 accounts. We have added this to the document under https://docs.microsoft.com/en-us/microsoft-365/admin/setup/priority-accounts?view=o365-worldwide#monitor-your-priority-accounts

Hope this helps!

@yogkumgit There are no changes required in the document. We can close this issue

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sinnamingrrl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
