### ISSUE TITLE
Endpoints need to be updated for Forms

### ISSUE THREAD

**Issue by GregDSmith** [MicrosoftDocs/microsoft-365-docs#3046]
[Enter feedback here]
The endpoints need to be updated for "Skype for Business Online and Microsoft Teams" and "Microsoft 365 Common and Office Online". When a user tries to access a "Form from within the Teams windows client they also need access to "forms.office.com". id 75 makes no mention of this URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@GregDSmith Thank you for your feedback. Looks like the URL is missing from the list. I'll work with the author and get this updated.

**Comment by msbemba** [comment]
@dmwmsft We need help in adding the URL Forms.office.com to ID 75 as Teams client needs access to it. Could you please help us in adding the URL?

Thanks
Sri

**Comment by dmwmsft** [comment]
I am not sure what you are referring to?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by msbemba** [comment]
> I am not sure what you are referring to? 

Sorry I meant to add @JoeDavies-MSFT  to this.

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT please answer and help us. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@GregDSmith The forms.office.com FQDN is covered by the *.office.com FQDN in table entry 147. Thanks for your question.

**Comment by msbemba** [comment]
Thank you @JoeDavies-MSFT .
