### ISSUE TITLE
Question on mobile devices

### ISSUE THREAD

**Issue by usvjosh** [MicrosoftDocs/microsoft-365-docs#3049]
Will the command to turn focused inbox off (Set-OrganizationConfig -FocusedInboxOn $false) affect mobile devices? We would like to notify our end users of the change we are about to make but it appears that this setting does not work for mobile devices. I'd just like to know if it should or not. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a29483-a070-ccc1-b064-176dfa49d5e9
* Version Independent ID: bad082c0-9ca2-0ade-6b1f-0ba5ac26017b
* Content: [Configure Focused Inbox for everyone in your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/configure-focused-inbox?redirectSourcePath=%252fen-us%252farticle%252fconfigure-focused-inbox-for-everyone-in-your-organization-613a845c-4b71-41de-b331-acdcf5b6625d&view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/configure-focused-inbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/configure-focused-inbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@usvjosh You are correct. This command turns it Off at the Mailbox level in exchange online. So the users no matter what the client or device they are using it inherits the setting from the server so it should not show up on mobile devices as well.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @usvjosh Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by kwekuako** [comment]
Just adding a caveat that the Powershell command does not block individual users from enabling Focused Inbox (on Mobile or any other endpoint) so while Focused Inbox should be off by default (when a user opens up the client), users can still enable it on Mobile, OWA, Desktop. Hope that helps as well.

**Comment by msbemba** [comment]
@kwekuako  Thank you for that additional information.

**Comment by usvjosh** [comment]
I'm not seeing the expected behavior of focused inbox being disabled for mobile devices. It works fine for us with the full Outlook application on Windows though. I may engage with Microsoft support to troubleshoot this further. We are using Intune to manage this setting on our mobile devices as well. So there could be a conflict in the configuration there. 

Thank you @msbemba  and @kwekuako for the assistance.

**Comment by msbemba** [comment]
@usvjosh Thank you for the update. In case there are changes need to the document please do let us know.
