### ISSUE TITLE
Product name and broken link

### ISSUE THREAD

**Issue by write4joy** [MicrosoftDocs/microsoft-365-docs#3053]
[Enter feedback here]
Hi.

In the article you write Windows Defender ATP, which is a 2 generation old name. Since september 22nd the correct name is Microsoft Defender for Endpoints.

Under the Feedback heading the link to "EU Model Clauses FAQ for Dynamics 365 and Office 365" leads to a page stating that the content is not available.

Thanks,

Predrag

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6853ccb3-e484-1eae-c5d1-9f7ae27ea13c
* Version Independent ID: b4d13120-f0d5-9db8-b6e2-a46e8918136a
* Content: [European Union Model Clauses - Microsoft Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/offering-eu-model-clauses?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/offering-EU-Model-Clauses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-EU-Model-Clauses.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@write4joy  Thank you for your feedback. We have corrected the Name in the document (PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3057) and will work with the author to get the updated link.

Thanks
Sri

**Comment by msbemba** [comment]
@robmazz The reference  Link to "EU Model Clauses FAQ for Dynamics 365 and Office 365" seems to be broken. I do not have another Microsoft document to replace it. Is it ok to remove the broken link or would you be able to get this fixed with the concerned team?

Thanks
Sri

**Comment by yogkumgit** [comment]
@robmazz Please help us with your answer. Thanks.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @write4joy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
