### ISSUE TITLE
clarification require for option "Automatic"

### ISSUE THREAD

**Issue by srchauhan29** [MicrosoftDocs/microsoft-365-docs#3056]
[Enter feedback here]
Hello,

While Automatic forwarding is set to "Automatic" and I do not have any ETR rule or Remote Domain defined to block, in that case forwarding is working from mailbox rule or any other method. While below line in the article says that the system will block automatic external forwarding.  

Can you please test the scenario and confirm my findings? If it is correct then kindly make necessary changes to article. 

**"This is the default mode and in this mode the system will block automatic external forwarding."**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding, Automatic forwarding, 5.7.520 Access Denied, disable external forwarding, Your administrator has disabled external forwarding, outbound anti-spam policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@srchauhan29 Thank you for your feedback. I tested this and you are correct. the automatic option does not block automatic external forwarding instead it is  System-controlled meaning it allows outbound spam filtering to control automatic external email forwarding. We have made the changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3097


Thanks
Sri

**Comment by srchauhan29** [comment]
It is still showing the same old in below link. Please check https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide Sent from Mail for Windows 10 From: Sriraman M SSent: Thursday, October 8, 2020 5:43 PMTo: MicrosoftDocs/microsoft-365-docsCc: Snehal Chauhan; MentionSubject: Re: [MicrosoftDocs/microsoft-365-docs] clarification require for option "Automatic" (#3056) @srchauhan29 Thank you for your feedback. I tested this and you are correct. the automatic option does not block automatic external forwarding instead it is System-controlled meaning it allows outbound spam filtering to control automatic external email forwarding. We have made the changes to the document via PR##3097ThanksSri—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by msbemba** [comment]
@srchauhan29 We have now submitted the changes via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3097 and it takes 48 hours to show up live after the author merges it.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @srchauhan29 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
