### ISSUE TITLE
Problem with EFT Account Number in Indonesia

### ISSUE THREAD

**Issue by Rob-ab** [MicrosoftDocs/microsoft-365-docs#3062]
There is a problem with the EFT account number in Indonesia. When I want to pay for my subscription via mobile banking, it tells me that the Citibank Account Number is not available ("tidak tersedia"). Can you fix this problem please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aa8e333-0044-00fd-43c9-3fb3503ce8fc
* Version Independent ID: 771de524-9a71-5e34-edce-bd4cd57b7204
* Content: [Payment information for Indonesia](https://docs.microsoft.com/en-us/microsoft-365/commerce/pay/indonesia?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/pay/indonesia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/pay/indonesia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Rob-ab Thank you for your feedback. This is more of a support query and needs to be answered by our Billing team. You can raise a support request from the need help option on the admin center.

@yogkumgit There are no changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@Rob-ab Can you please send me your tenant id and an invoice id so we can investigate? [Here are steps to find your tenant id](https://docs.microsoft.com/onedrive/find-your-office-365-tenant-id). Please send directly to me: cmcatee@microsoft.com
Thanks!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Rob-ab Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
