### ISSUE TITLE
Hybrid url domain missing 

### ISSUE THREAD

**Issue by teamneroblanco** [MicrosoftDocs/microsoft-365-docs#3063]
The hybrid wizard has changed its location to https://shcwreleaseprod.blob.core.windows.net which isn’t in the list for number 9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@teamneroblanco The shcwreleaseprod.blob.core.windows.net FQDN is covered by the *.blob.core.windows.net FQDN in row 67 of the https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide article. Thanks for you question.

**Comment by teamneroblanco** [comment]
[cid:image001.png@01D69CD5.AD07E070]

Row 67 says Security and Compliance Center eDiscovery export.  That’s hardly suggesting HCW is it?
