### ISSUE TITLE
Planning to add the ability to run Get cmdlets under a reader role for the MSCommerce PS module?

### ISSUE THREAD

**Issue by DragosC21** [MicrosoftDocs/microsoft-365-docs#3065]
see title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide#requirements)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@DragosC21 Thank you for your feedback. For now, I see only Global and Billing Admins have access to the module. However, There is a UserVoice created for this feature and can be tracked here -https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/40751890-allow-read-only-access-to-mscommerce-module

You can vote for the idea with your email address and will be intimated when the feature goes live.

Hope this helps!

@yogkumgit  There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DragosC21 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
