### ISSUE TITLE
AI Builder credits relation in SharePoint Syntex unclear

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#3066]
Hello,

it's unclear to me how and when AI Builder credits are consumed and thus it's unclear for me what the SharePoint Syntex plan includes and when additional fees/costs occur due to AI Builder credits consumption.

Please explain this better as the relevance of the current paragraph about AI Builder credits is unclear from reading the article.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding?view=o365-worldwide#ai-builder-credits)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please help us resolving this issue. Thanks.

**Comment by seansquires** [comment]
Thanks for the feedback. SharePoint Syntex uses the same service credits as if you used AI Builder separately, but we include 1M/month if you have 300 or more licenses (otherwise you'd have to purchase additional licenses or these credits separately). Like the other license add-ons, these service credits are pooled at the tenant level, there is no roll-over to the next month, and their consumption is the same as if you used form processing models in other applications (this can vary based on usage frequency and other factors, but would cover processing about 1K pages/month.

**Comment by GiantCrocodile** [comment]
I see @seansquires. So what do we actually pay the 5$/M for for SharePoint Syntex? It looks like that I can do the very same with other Office 365 services or Azure sertvices with the same expenses and the same or nearly the same afford without needing the SharePoint Syntex license on top. I noticed that other customers feel the same regarding unclear benefits of this license.

**Comment by InspireCloudTech** [comment]
I agree with @GiantCrocodile I am unsure why tenants with less than 300 licensed Syntex Users would need to pay $5PM? Are we paying to have the buttons available, but no AI Credits to actually use the Forms Processing service, which this service needs to work? 

Also, should the note about the AI Builder Credits being required be included at the top level of the documentation for Syntex, not the last document hidden in the Setup section, where it could easily be missed.

Finally, I just re-checked the Syntex Pricing Page and there's nothing noted in the 'FAQ' to note that you need to pay $500PM for 1 Unit (assumed that you have about 1K Pages / Month) if you buy less than 300 Licenses for Syntex. That really should be added as a FAQ.

**Comment by MikePlumleyMSFT** [comment]
@seansquires, anything more you can add?

**Comment by InspireCloudTech** [comment]
@MikePlumleyMSFT I may be wrong, but following my comment back in October i went back and reviewed other content and the sessions from Ignite and now understand the below:

My understanding is that the $5PM is to provide the Document Understanding Model, which effectively means you use .docx files and they need to have the same layout to allow the understanding model to pull the metadata. However I guess this is more useful in contracts or documents that the client (who was the tenant) issues out.

The additional cost is for the Forms Processing Model (where I think Syntex becomes more useful) to use the AI Builder Credit to support PDFs and other file formats (much like OCR) and you can support many different models. This is more useful if you receiving files from external parties, as the file format and layout can differ - so you need many models - an example would be Invoices. 

So, I think that is my understanding - but I do think the FAQ's could be more clear though - as most people won't read hours of additional content to understand it.

**Comment by yogkumgit** [comment]
@seansquires We need your help here. Thanks

**Comment by seansquires** [comment]
Apologies - thought this item had been closed per separate email threads. Yes, the Syntex license cost includes the rest of the feature set (content center, document understanding models, model analytics, add'l MMS features, and yes, the AI Builder form processing integration w/ SharePoint libraries). The service credit addendum is based on the seat count minimum and appreciate the feedback that this can be clearer in both product page FAQ and any licensing documentation. We are working on updating/providing both.

**Comment by yogkumgit** [comment]
@GiantCrocodile Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
