### ISSUE TITLE
Data move for a customer in Germany

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#3068]
Hello,

according to the article a customer from Germany should be able to have a data move from European Union to Germany from 1st of October 2020 on. I checked the tenant's organization profile and there's no option to request the data move.

Did the start date for the data move request get delayed?

Is there some other requirement that needs to be fulfilled but isn't mentioned in the article? The tenant was created on September 2019.

Thank you for clarification.

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87cb379c-82ae-0a6e-8dd5-0c41b09364ab
* Version Independent ID: a15c3919-e63e-f0dc-bd6b-45f311b387b5
* Content: [How to request your data move - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/request-your-data-move?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/request-your-data-move.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/request-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by andybergen** [comment]
Delayed slightly. Customers will receive a notification in Message Center when it is enabled.

________________________________

**Comment by GiantCrocodile** [comment]
@andybergen Thank you for this excellent response time! This is something a lot of customers, including me, look for and thus this is awaited for a long time. Great to hear. If I should close this issue as no article update is needed, just let me know.

**Comment by andybergen** [comment]
Article update TBD, if required I will take care of it by end of day Tues. thanks.

________________________________

**Comment by yogkumgit** [comment]
@andybergen Thank you very much for sharing this explanation. @GiantCrocodile Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
