### ISSUE TITLE
Page wrong: Junk Reporting doesn't install on current versions of Outlook

### ISSUE THREAD

**Issue by Scribliotech** [MicrosoftDocs/microsoft-365-docs#3069]
When trying to install the Junk Reporting Add-in for Office, it responds with a window titled, "Microsoft Junk E-mail Reporting Add-in". The text in the window reads, "The installation is unable to proceed due to missing dependencies. Please verify you have all the pre-requisites installed on your machine."

I assume this is because it doesn't work with Outlook after Outlook 2016, and Microsoft/Office 365 is effectively Outlook 2019. This page is either just wrong (for not sending us to the right place to get the right version of the add-in) or missing critical information that the tool is now obsolete on current versions of Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d71dab-a58d-fbd9-c30f-14f5884f094e
* Version Independent ID: 13e0112c-213d-b462-7833-9d0fe30fc99c
* Content: [Install and use the Junk Email Reporting add-in for Microsoft Outlook - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Scribliotech, several months ago, I was able to successfully install the add-in on my own Windows 10 PC with Outlook 2019 (that's where I got the screenshots). Just now, I uninstalled and reinstalled the add-in without error. According to the topic, the important (only?) prerequisite is the .NET Framework 2.0 (which you enable in Turn Windows features on or off in Control Panel in Windows 10). I realize the System Requirements info on the Download Links page talks about needing Primary Interop Assemblies for various older version of Outlook. But, for me with Windows 10 and Outlook 2019, those weren't required. Please confirm.

Ideally, you would install and use the newer [Report Message Add-in](https://docs.microsoft.com/microsoft-365/security/office-365-security/enable-the-report-message-add-in) for a variety of reasons. Is there a specific reason why you aren't using the Report Message Add-in?

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @Scribliotech Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by david-tap** [comment]
> Ideally, you would install and use the newer [Report Message Add-in](https://docs.microsoft.com/microsoft-365/security/office-365-security/enable-the-report-message-add-in) for a variety of reasons. Is there a specific reason why you aren't using the Report Message Add-in?

Is the Junk Reporting Addon officially deprecated?

**Comment by chrisda** [comment]
Not deprecated. As long as it's available at the Download Center, it's supported. Based on age and the information on the download page, I doubt it was ever tested in Outlook 2019, but it does seem to install and work.

I purposefully left the information for the Junk Email Reporting Add-in for Microsoft Outlook not as encouragement for people to start using it. Instead, I left it there for large organizations who already went through the trouble of installing and using it in the past. If you have never used it before, there's really no reason to start now. The [Report Message Add-in](https://docs.microsoft.com/microsoft-365/security/office-365-security/enable-the-report-message-add-in) or the [Report Phishing add-in](https://docs.microsoft.com/microsoft-365/security/office-365-security/enable-the-report-phish-add-in) are much more modern.

In particular for Microsoft/Office 365, the newer add-ins integrate with [the Admin Submissions portal](admin-submission.md), [Automated investigation and response (AIR) results](air-view-investigation-results.md), the [User-reported messages report](view-email-security-reports.md#user-reported-messages-report), and [Threat Explorer](threat-explorer-views.md#email--submissions). The same cannot be said for the Junk Email Reporting Add-in for Microsoft Outlook.
