### ISSUE TITLE
MS article needs revision

### ISSUE THREAD

**Issue by Mr-K07** [MicrosoftDocs/microsoft-365-docs#3071]
The steps described in the article do not work. When going to https://outlook.office.com/people/group/deleted , there is no deleted Microsoft 365 group despite the fact that I was an owner of the group when I deleted it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d49db57-a705-20aa-e98d-5b3d6bbbf9fd
* Version Independent ID: 5a056f2c-03c9-7a34-3196-8bfb1039f6a5
* Content: [Restore a deleted group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/restore-deleted-group?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/restore-deleted-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/restore-deleted-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Mr-K07  Thank you for your feedback. I tested this and it works for me in multiple tenants/groups. This could be more of a support related query and request you to contact Microsoft support via the need help section on the m365 admin center.

![image](https://user-images.githubusercontent.com/45987684/95592462-4a095680-0a66-11eb-830e-ad11d30040b6.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Mr-K07 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
