### ISSUE TITLE
Page lacks crucial info

### ISSUE THREAD

**Issue by kaidoloor** [MicrosoftDocs/microsoft-365-docs#3072]
This page: https://docs.microsoft.com/en-us/microsoft-365/admin/support/estonia?view=o365-worldwide lacks information on how to add organisations to my account. Lets say I start a new business. I want to have a new OneDrive for business for that. How to achieve having a new organisation?

br,
Kaido

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22287d6c-4733-ed93-05db-9b46f2a6fe28
* Version Independent ID: 1c66ac29-6277-4c3b-0ada-6ba0127808cd
* Content: [Support information for Estonia - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/estonia?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/estonia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/estonia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@kaidoloor The page you referenced is only intended to provide support contact information for Estonia. For adding a new organization, you'd have to look at the overall admin content [here](https://docs.microsoft.com/microsoft-365/admin/setup/). 

If you bought your subscription directly from the Microsoft web site, you can't add a new organization to your account. You need to set up a new account and buy a new subscription for it. If you bought your subscription through Microsoft Sales, contact your Microsoft representative to set up a new organization within your Microsoft account.
