### ISSUE TITLE
old information-financial services blog

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3075]
[Enter feedback here]
The financial services blog that is referenced on this page has not been updated in 2 years. Was that blog moved to another location or abandonded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ca331a-1909-1e88-0864-ba584551c0bf
* Version Independent ID: 9748f59e-903b-c3d8-043f-11a939cba24d
* Content: [Securities and Exchange Commission (SEC) Rule 17a-4(f) United States - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-sec-17a-4?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-SEC-17a-4.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-SEC-17a-4.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@robmazz We have a Financial services blog -https://techcommunity.microsoft.com/t5/financial-services-blog/bg-p/FinancialServicesBlog which was last updated in 2018, is this still relevant/updated or can we remove the reference from this page?

Thanks
Sri

**Comment by yogkumgit** [comment]
@robmazz Please help us resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder, please review the comment and help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@DeanGross - thanks for the feedback. The blog appears abandoned, please use the parent discussion space (https://techcommunity.microsoft.com/t5/financial-services/ct-p/FinancialServices). I'll update the topic, thanks!
