### ISSUE TITLE
Steps you need to do to manually set up DKIM

### ISSUE THREAD

**Issue by flowl** [MicrosoftDocs/microsoft-365-docs#3076]
Steps you need to do to manually set up DKIM

1. [Publish two CNAME records for your custom domain in DNS](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#Publish2CNAME)

2. [Enable DKIM signing for your custom domain](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#EnableDKIMinO365)

Step 2 is step 3 and real step 2 is missing: **Create keypair**

Please ellaborate on how to connect to Exchange365, which requirements are involved (Windows OS + [EOM package](https://www.powershellgallery.com/packages/ExchangeOnlineManagement/2.0.3)).

Basically, the command is mentioned in the section [Manually upgrade your 1024-bit keys to 2048-bit DKIM encryption keys](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#manually-upgrade-your-1024-bit-keys-to-2048-bit-dkim-encryption-keys) but I wouldn't read that section if I have no keys at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@flowl Thank you for your feedback. I tested it now and was able to enable DKIM with the two steps mentioned in the document. Could you please elaborate on what happens when you follow the two steps?

1) Publish Cname
2)Enable DKIm from EAC

Thanks
Sri

**Comment by flowl** [comment]
@msbemba there is no "Enable DKIM" button until the keys have been generated on the server... it is impossible it worked for you but I think you have the keys already generated.

This is a screenshot of a domain without generated keys, **no** enable/disable button available:

![Screenshot 2020-10-11 at 15 12 20](https://user-images.githubusercontent.com/4543262/95679618-58758080-0bd4-11eb-870d-0722b0f3af4c.png)

Here is a screenshot of a domain with generated keys, enable/disable button is available:

![Screenshot 2020-10-11 at 15 12 26](https://user-images.githubusercontent.com/4543262/95679632-6e834100-0bd4-11eb-9233-046b6effa37e.png)


Please share a screenshot of the button to generate the keys you say you have.

**Comment by flowl** [comment]
@msbemba I found there is actually a way to add keys with the webinterface: https://protection.office.com/dkimv2

1. This page is not mentioned or linked from the above how-to or the DKIM page in mail protection. This is actually step 2 of 3 and DKIM cannot be enabled with only "2 steps" like you claim. DNS, Keys, Enable, 3 steps on completely different pages.

2. The method is buggy and doesnt work:

![Screenshot 2020-10-11 at 15 21 45](https://user-images.githubusercontent.com/4543262/95679811-91fabb80-0bd5-11eb-8a03-c3bdc88c8a04.png)

**Comment by msbemba** [comment]
@flowl Thank you for your feedback. I just tried to do it for a test tenant and did not have to create a key.

![image](https://user-images.githubusercontent.com/45987684/95708653-74336200-0c7a-11eb-82cb-3d59f893fd96.png)

 I hit the enable Button and get the below screen tp publish DNS records

![image](https://user-images.githubusercontent.com/45987684/95708715-94632100-0c7a-11eb-866c-f6cce501ec21.png)

I'm going to check with the author and Engineering team to understand the different scenarios around this.

Thanks
Sri

**Comment by msbemba** [comment]
@MSFTTracyP Could you please help with these steps? I have tried to enable DKIM on a couple of tenants and it works without me creating a key pair. Which means Just publishing CName (wait for 10 minutes) and then enable DKIM from EAC. However,  @flowl Has posted screenshots of it asking for Keypair creation(above). Let us know if the creation of keypair is required so that we can add that to the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us in resolving this issues. Thanks

**Comment by MSFTTracyP** [comment]
@Flowl are you using a DKIM key from some other source that you generate and include in DNS as a TXT file? If you are, yes, you'll need to create and rotate the key pairs yourself and maintain DNS for these. However, outside of that instance, Microsoft handles the DKIM key and its rotations on the backend, so that all that's required is for customers to create the CNAME entries that forward DKIM requests to Microsoft from some external DNS.

Please let me know if you created your own public DKIM key, and we can continue from there.

**Comment by flowl** [comment]
@MSFTTracyP I'm not using any self generated key...

This problem is at least 4 years old:

https://www.cgoosen.com/2019/01/exchange-online-no-dkim-keys-saved-for-this-domain/
https://www.oxcrag.net/2018/08/31/fixing-no-dkim-keys-saved-for-this-domain-in-eop-and-office365/
https://www.krneki.net/Blog/post/no-dkim-keys-saved-for-this-domain
https://www.reddit.com/r/Office365/comments/hxhl6k/no_dkim_keys_saved_for_this_domain/
http://www.wave16.com/2016/03/office-365-dkim-no-dkim-keys-saved-for.html

**Comment by flowl** [comment]
@yogkumgit @msbemba @MSFTTracyP 

I'm implying there is an annoying bug in the Office 365 platform.

**Comment by MSFTTracyP** [comment]
@Flowl, You need to head to Support to report this issue and also hand them this thread so that they can contact me when the cause is found. This is not a Support channel. While writers can and will do what they can to help you, they cannot usually test or repro your issues and work with you to resolve them. Finally, please take a look at https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#to-enable-dkim-signing-for-your-custom-domain-by-using-powershell, and the 'To enable DKIM signing for your custom domain by using PowerShell' for more on the error 'No DKIM keys saved for this domain'. However, I need to emphasize, this is a Support issue.

**Comment by flowl** [comment]
You are working for Microsoft, not me.
You can forward the problem way better than I could do.
I am not the one who is going to beg Microsoft to fix their issues while the ones beeing paid don't care about their product.

You software is broken, you need to fix it, not me. I'm the customer, I paid for the product. 
If you pay me, I could try to forward the issue.

**Comment by yogkumgit** [comment]
@MSFTTracyP  Thank you very much for sharing this explanation. @flowl Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by flowl** [comment]
@MSFTTracyP @yogkumgit 

It took you almost 4 month to tell me you won't fix the problems with broken DKIM nor are you able to forward the issue to the appropriate department. They can reproduce the steps on their own, I don't have any domains left which aren't yet configured in Exchange.
Why do you think I'm gonna do work for Microsoft with this low level service and, opposed to you, not beeing paid by Microsoft?

**Comment by flowl** [comment]
@MSFTTracyP @yogkumgit 

I contacted support like you suggested.
It's very hard to communicate with them.
I got a reply that says: "Only Microsoft articles are considered source of information" I think Mr. or Mrs. Ola did not visit this GitHub issue. Further He or she says: "There is no bug, you need to use PowerShell". Which means the docs and the Exchange Admin contain wrong information.

I hope you understand that this makes me very upset, Microsoft is avoiding bugfixes and communication by letting me struggle between you and the support. Instead of Microsoft people improving their software, they let me write emails and reports and afterall nothing changes.

**Comment by flowl** [comment]
@MSFTTracyP @yogkumgit 

I reached back at the support and they told me:

Steps you need to do to enable DKIM:

1. Publish DNS
2. CREATE KEYPAIR THROUGH POWERSHELL
3. Enable DKIM


So like I said 4 months before already, your documentation is wrong.

Please fix your documentation. without creating the keypair via powershell, there is no way to use DKIM.
There is no "you can chosoe. from enabling DKIM via powershell or via exchange admin".

Thanks....

**Comment by flowl** [comment]
The docs have gotten better when you added the "Important" note about "No DKIM keys saved for this domain" on https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#to-enable-dkim-signing-for-your-custom-domain-by-using-powershell

It seems "Publishing DNS" and "Creating keypair" is the same step but they should be different.
Publishing DNS is something I do outside of Microsoft, where my DNS provider is at.
Then there need keys to be created at Microsoft through powershell,
then I need to enable DKIM through Webinterface.

It's 3 steps and steps 1 and 2 are super confusing in the docs.

**Comment by flowl** [comment]
@MSFTTracyP @yogkumgit 

After a phone call with the support things have been solved way easier than by textual communication.

The status quo is, while it was possible in the past to activate DKIM for a custom domain via web interface, it has been disabled during the past year. For the initial setup of a custom domain, **Power Shell is required.**

This is how DKIM for a custom domain is setup:

1. Setup Custom Domain DNS (mx, ...)
2. Generate Keys (and Microsoft internal DNS) using PowerShell
3. Enable DKIM in Exchange Admin

I've seen your improvements and it looks clear now that at some point setting up Power Shell is a point in the docs but the overall document could be much simpler by just following those three steps.

The problem with Power Shell for me as a MacOS user is, the current PowerShell-ExchangeAuthentication module is outdated and not working without unofficial patches.

Finally I want to thank you and appreciate your efforts and time and polite communication.

It would be cool if setting up DKIM would be possible again without PowerShell!

And it would be super cool if you people at Microsoft would simply cross connect for those things. Aren't you using Microsoft Teams?

**Comment by flowl** [comment]
@yogkumgit Ticket shouldn't be closed as support confirmed my suggestions.

**Comment by msbemba** [comment]
@flowl Thank you for your feedback. Any design change request would have to go through the user voice ->product group.We have a similar request on user voice portal -https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/42523222-enable-dkim-key-creation-in-admin-center . You can Vote for this Idea and get notified when this feature becomes available.

Thanks
Sri

**Comment by flowl** [comment]
@msbemba 
1. "This site is currently not active" and requirings creating yet another user account. 100% not gonna do that.

You don't respect the effort I put in this, improving your software. I am doing free quality assurance for you, gathering information from the past 4 years, verifying the issue, talking to different MS people, doing your homework. What are you doing in return?

Please just fix the documentation.

It's not for me, because I already know I need a windows computer with PowerShell.
This is for other people, who don't know, who are new and try to follow a wrong documentation.

You are making easy stuff very complicated and it takes MONTHS and still nothing happened.

**Comment by msbemba** [comment]
@flowl The document now contains steps to enable DKIM via Powershell -https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#to-enable-dkim-signing-for-your-custom-domain-by-using-powershell

I had referred you to UserVoice since you wanted a design change.

Thanks
Sri

**Comment by flowl** [comment]
@msbemba 

"Once you have published the CNAME records in DNS, you are ready to enable DKIM signing through Microsoft 365. You can do this either through the Microsoft 365 admin center or by using PowerShell."

This is still wrong.

YOU NEED POWERSHELL + WINDOWS COMPUTER!

**Comment by flowl** [comment]
Microsoft should pay me for participating here, having to fight MS employes who don't understand their own product.

**Comment by flowl** [comment]
This discussion feels unrewarding.

**Comment by msbemba** [comment]
@flowl accept my apologies for the delay. I have added another line stating  "If you are configuring DKIM for the first time and see the error 'No DKIM keys saved for this domain.' you need to use Windows PowerShell to enable Dkim Signing as explained in the next step.
"

This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4342

You guys make our documents look better.  sorry that you felt unrewarding.

Thanks 
Sri

**Comment by flowl** [comment]
Thank you @msbemba
