### ISSUE TITLE
Outdated content not compatible with MFA

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/microsoft-365-docs#3077]
Invoke-CompatibilityCheck poweshell command doesn't seem to work with MFA which majority of tenant have to use. Could this page and/or powershell be updated please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#centralized-deployment-compatibility-checker)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@SvenBell Thank you for your feedback. We have added a note to the document to mention that this works only without MFA. This can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3115

Please note this feature is still under discussion and can be found here in UserVoice -https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/36561154-enable-mfa-on-central-deployment-for-add-ins-power

Thanks
Sri

**Comment by SvenBell** [comment]
Thanks for adding note about the O365CompatibilityChecker tool only working without MFA.

I have voted on UserVoice link provided. I note that it has been 21+ months of no progress on enabling MFA for this essential tool, ideally this should have been resolved before the new Deployment experience begun rolling out and effecting production tenancies. MFA is now default for Admin's so bit disappointing it's had no progress to help customers with issues.

**Comment by msbemba** [comment]
Agree with you that this should not be delayed. I have voted as well, hopefully, we will have this feature resolved as soon as possible.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SvenBell Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
