### ISSUE TITLE
Outdated page contents, missing Add-ins

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/microsoft-365-docs#3078]
Outdated page contents don't match match current version of O365 Admin Centre. Add-ins page is missing and Report message add-in has recently disapeared from Outlook having been deployed previously. How does one add/re-add with current version of O365 Admin Centre?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#centralized-deployment-compatibility-checker)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@SvenBell Thank you for your feedback. This document is intended to determine is Centralized deployment works for your organization. For information about Managing your add-ins, Please visit -https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide

If for a reason you are not able to see the add-in after deploying them, I'd recommend you contacting support via the need help button on the admin center.

Also, we have added a note in the document that the admin center is getting updated to deployment experience with Integrated Apps. If you don't see the above steps, go to the Centralized Deployment section by going to Settings > Integrated apps. On top of the Integrated apps page, choose Add-ins.

Hope this helps!

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SvenBell Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SvenBell** [comment]
Thanks for adding the extra Note to the page about the Updating of deployment experience 👍 
The old Add-In's menu option has gone missing for us, it was there a few weeks ago, Settings>Integrated apps is also not a menu option for our tenancy yet...

**Comment by msbemba** [comment]
@SvenBell The Menu options are rolled out in a phased manner. Hopefully, you will see the new options soon. If you don't see either of the options, I'd recommend contacting the Support team to ensure that the settings and configurations are up to date on the tenant.

Thanks
Sri
