### ISSUE TITLE
Opt out option not available 

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/microsoft-365-docs#3082]
Turn off Microsoft Threat Protection
To stop using Microsoft Threat Protection, go to Settings > Microsoft Threat Protection > Opt-in / Opt-out in the Microsoft 365 security center. Unselect Turn on Microsoft Threat Protection and apply the changes.

Is not available check on 3 tenants : 

![image](https://user-images.githubusercontent.com/64666203/95249807-de618800-07de-11eb-9d73-df1220a3b8cd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7f625c-f3ef-882d-231f-6fef18e14137
* Version Independent ID: 3f335d54-6d65-d49a-e517-2c3a9a95e44d
* Content: [Turn on Microsoft Threat Protection in the Microsoft 365 security center - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-enable?view=o365-worldwide#turn-off-microsoft-threat-protection)
* Content Source: [microsoft-365/security/mtp/mtp-enable.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/mtp-enable.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by msbemba** [comment]
@lomayor We see that the option to Turn Off or Opt-out has been removed from the admin center. 

I just wanted to confirm with you that it is indeed removed so that we can make the changes accordingly to the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@lomayor Please reply to this query. Thanks.

**Comment by yogkumgit** [comment]
@lomayor Gentle reminder, Please reply to this query. Thanks.

**Comment by lomayor** [comment]
@yogkumgit ... I'll need to verify this with the PM. Please wait for a little bit.

**Comment by lomayor** [comment]
@yogkumgit, confirmed. Please remove this section:

**Turn off Microsoft Threat Protection**
To stop using Microsoft Threat Protection, go to Settings > Microsoft Threat Protection > Opt-in / Opt-out in the Microsoft 365 security center. Unselect Turn on Microsoft Threat Protection and apply the changes.

Corresponding features will be removed from the Microsoft 365 security center.

**Comment by msbemba** [comment]
@lomayor Thank you for your feedback. We have removed this section and the same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3082

Thanks
Sri

**Comment by chrisda** [comment]
Merged #3082 to remove opt-out section as described.

Closing
