### ISSUE TITLE
Conflicting info in "in-scope cloud services" section

### ISSUE THREAD

**Issue by Katerine459** [MicrosoftDocs/microsoft-365-docs#3083]
Among the in-cloud services, are the following two listings:
- Microsoft Professional Services: Premier and On Premises for Azure, Dynamics 365, Intune, and for medium business and enterprise customers of Microsoft 365 for business
- Office 365, Office 365 U.S. Government, and Office 365 U.S. Government Defense

Wasn't Office 365 renamed to Microsoft 365? In which case... is Office 365 for small business in-scope or not? The first listing implies that only medium and enterprise customers are in-scope, while the second indicates that all 365 customers are in-scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545aa0d-ba68-3113-413b-0c0b176b08bd
* Version Independent ID: bb2ce8e1-7f40-e5ed-60c4-f8bb0912661d
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-hipaa-hitech?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Katerine459 Thank you for your feedback. The first listing implies to Microsoft professional services that are available to medium and enterprise businesses. To answer your question yes, M365 for Small, Medium and Enterprise business are all in-scope.

I have renamed O365 to M365 in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3116

Thanks
Sri

**Comment by msbemba** [comment]
@Katerine459 Just received an update from the author that the changes need to be cleared and synced with supporting PDF download and the same is Currently in discussions about updates and reformatting of this download. You will see changes to this soon.

@yogkumgit Author is currently in discussion about updates and reformatting of this download and will be fixing this in the backend. PR has been closed so please close the issue.
