### ISSUE TITLE
Configuration under "Configuring and securing Teams media traffic" section

### ISSUE THREAD

**Issue by arunkumar4003** [MicrosoftDocs/microsoft-365-docs#3085]
[Enter feedback here]
Hello Team,

The article says, 
In certain scenarios, often unrelated to Teams client configuration, media traffic still traverses the VPN tunnel even with the correct routes in place. If you encounter this scenario then using a firewall rule to block the Teams IP subnets or ports from using the VPN should suffice.
With Pulse Secure VPN and correct routes are in place we are still seeing the traffic in Virtual Adapter. We would like to know what are those scenarios that would cause this behavior and how to resolve it with in the scope of VPN server and client.

Regards,
Arun.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b783ee-9449-56db-3abd-f17dcf6b5d54
* Version Independent ID: d2146ff5-4248-12ec-a873-c951220aaa14
* Content: [Implementing VPN split tunneling for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us resolving this issue. Thanks.

**Comment by arunkumar4003** [comment]
Hello Team,

Could you please give update to the query?

Regards,
Arun.

**Comment by LauraWi** [comment]
Hi @arunkumar4003 Writers are not able to troubleshoot scenarios like this in the context of documentation feedback. Your best bet is to open a case with support. Thanks.
