### ISSUE TITLE
This capability is not yet supported for macOS or iOS

### ISSUE THREAD

**Issue by LeeMin-Z** [MicrosoftDocs/microsoft-365-docs#3086]
Under part 
Sharing encrypted documents with external users
“This capability is not yet supported for macOS or iOS.”

Specific functions and features are now supported on IOS and MAC OS. Refer Support for sensitivity label capabilities in apps https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#support-for-sensitivity-label-capabilities-in-apps

**Comment by msbemba** [comment]
@LeeMin-Z Thank you for your feedback. Could you please provide us with the document which states it is not yet supported for macos or ios?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LeeMin-Z Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
