### ISSUE TITLE
userPrincipalName and allowed characters

### ISSUE THREAD

**Issue by AlexCesarini** [MicrosoftDocs/microsoft-365-docs#3088]
When using characters like **ì** or **ò** in the upn
ex: userì@domain.com I get an error during the sync

ExtraErrorDetails:
[{"Key":"ObjectId","Value":["xyz"]},{"Key":"InvalidAttributeName","Value":["userPrincipalName"]}]

Characters with accent are not listed as invalid in the document under
**userPrincipalName** section.

userPrincipalName valid characters should be only

- A – Z
- a - z
- 0 – 9
- ' . - _ ! # ^ ~

as described here
https://docs.microsoft.com/en-us/office/troubleshoot/office-suite-issues/username-contains-special-character

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b05a56d-f714-2d99-747e-b3150f581f38
* Version Independent ID: e8924d3f-20e7-6ce2-2279-cec010e7d3f3
* Content: [Prepare for directory synchronization to Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-for-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@AlexCesarini Thank you for your feedback. We have added the allowed characters to the document via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3096

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AlexCesarini Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
