### ISSUE TITLE
Rename "Service Admin" to "Service Support Admin" per "Administrator role permissions in Azure Active Directory"

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/microsoft-365-docs#3090]
[Enter feedback here]
This page refers to the "Service Admin" role, however this role was renamed to "Service Support Admin" per https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#service-support-administrator. Suggest to rename it here to align to this terminology.

> Note
> 
> Previously, this role was called "Service Administrator" in Azure portal and Microsoft 365 admin center. We have renamed it to "Service Support Administrator" to align with the exsiting name in Microsoft Graph API, Azure AD Graph API, and Azure AD PowerShell.
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide&preserve-view=true#roles-available-in-the-microsoft-365-admin-center)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@softwarecraft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3095

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @softwarecraft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
