### ISSUE TITLE
Please add retention details on SharePoint Lists and OneNote Notebooks

### ISSUE THREAD

**Issue by pbinksma** [MicrosoftDocs/microsoft-365-docs#3094]
There is some confusion on business side about the way retention policies and retention labels work with SharePoint Online Lists and OneNote Notebooks.

I suggest that you add a statement to the chapter "Applying a default retention label to all content in a SharePoint library, folder, or document set" where you explicitly explain that SharePoint Lists basically behave the same like a Document Library with documents. Each list item ages individually (like a document in a library), you can apply labels on individual list items or on the whole list (same way you would do on a SharePoint Library).

OneNote Notebooks are also a bit special. My tests in the past showed that OneNote-Sections were aging individually. So with a deletion policy the notebook will become "cleaned" section by section. To prevent that you can apply e.g. a retention library on your Notebook, but then it will protect the Notebook as a whole entity (technically it seem to be a folder with document per section).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b974f07-d9f4-38c6-39ac-5d53aeda45fc
* Version Independent ID: fab281b5-1ff8-6e71-1756-c0579770f523
* Content: [Create retention labels and apply them in apps to retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-apply-retention-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-apply-retention-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-apply-retention-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please add your comment and help us in resolving this issue. Thanks.

**Comment by cabailey** [comment]
I'm adding some clarification to the section for a default label that each item will be retained/deleted separately, although I haven't heard this of being a point of confusion before.  The request to clarify OneNote is very valid if you don't realize that each OneNote section is a separate file - so I added a new section specifically for this: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-retention-works-for-onenote-content

However, I didn't understand the comment that you could apply "a retention library on your Notebook" ?

**Comment by pbinksma** [comment]
The past few years we had our own, custom retention/deletion job to implement retention policy for our on premise team sites on Sharepoint 2010 and later 2013. That job did not touch lists and some dedicated libraries like the site assets. With our move to SPO this retention behavior obviously change. It would be helpful to have more clarity especially on the retention/deletion behavior on lists, as it helps to communicate that this behavior is not a bug, but actually a feature😉

I like the new section on OneNote. For me it makes things clear. Thank you.

> However, I didn't understand the comment that you could apply "a retention library on your Notebook" 

That is a typo. I wanted to say, that you can apply a retention ***label*** on your notebook to overrule the policy affecting your notebook sections.

**Comment by yogkumgit** [comment]
@cabailey Thank you very much for sharing this explanation. @pbinksma Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
