### ISSUE TITLE
Inappropriate recommendation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3098]
[Enter feedback here]

Task 5 is recommending that we use PAM for the Compliance Center admin roles. This does not currently  appear to be possible because PAM is limited to Exchange and does not work with the roles used in the Compliance Center. Please replace task 5 with something that can actually be performed. (or enhance the functionality of PAM to include a broader set of services)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0c715a-7dec-d9b8-94bb-de2d96fa3084
* Version Independent ID: 2ebda82f-ffe5-78ae-1c99-fff2e24a9cd7
* Content: [Quick tasks for getting started with Microsoft 365 compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-quick-tasks?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-quick-tasks.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-quick-tasks.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. I'll confirm with the author and make changes accordingly.

Thanks
Sri

**Comment by msbemba** [comment]
@robmazz Currently PAM is available only for Exchange and not beyond that. However, I see from the roadmap that Privileged access management will be available in other Office 365 workloads soon. Can I remove the task 5 to avoid confusion? or Do you think we should add a note that this feature will be added soon?

Thanks
Sri

**Comment by msbemba** [comment]
@DeanGross We have removed that task 5 as PAM is not available for compliance admin roles.  This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3222

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
