### ISSUE TITLE
Duplicate paragraphs

### ISSUE THREAD

**Issue by Somu76** [MicrosoftDocs/microsoft-365-docs#3099]
There seem to be duplicate paragraphs in this section:
https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/difference-between-document-understanding-and-form-processing-model?view=o365-worldwide#where-they-are-created

**Form processing models are created in PowerApps AI Builder, but the creation is initiated directly from a SharePoint document library. Form processing model creation needs to be enabled on your document library in order for a user to create a form processing model for it, and an admin can do this in the content understanding admin settings. Form processing models use PowerAutomate flows to process files when they are uploaded to the document library.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7acbcb-25a1-2241-3738-0582ed407ad5
* Version Independent ID: d3c1802f-a8b4-3400-a350-734e9bad2b5d
* Content: [Difference between document understanding and form processing models](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/difference-between-document-understanding-and-form-processing-model?view=o365-worldwide)
* Content Source: [microsoft-365/contentunderstanding/difference-between-document-understanding-and-form-processing-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/difference-between-document-understanding-and-form-processing-model.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@Somu76 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3141

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Somu76 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
