### ISSUE TITLE
Invalid character update

### ISSUE THREAD

**Issue by DanielBirmingham** [MicrosoftDocs/microsoft-365-docs#3100]
Under section '2. Directory object and attribute preparation', bullet point 'userPrincipalName', it states 'An umlaut is also an invalid character.'  While that is true, other diacritical marks are also not supported, such as tildes and accents, and this has led to customer confusion.  It would be ideal to update the sentence to something along the lines of:

Letters with diacritical marks are invalid characters, such as umlauts, accents, and tildes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b05a56d-f714-2d99-747e-b3150f581f38
* Version Independent ID: e8924d3f-20e7-6ce2-2279-cec010e7d3f3
* Content: [Prepare for directory synchronization to Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-for-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@DanielBirmingham Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3140

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DanielBirmingham Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
