### ISSUE TITLE
Requirements for S/MIME Extension in Microsoft Edge

### ISSUE THREAD

**Issue by rmda** [MicrosoftDocs/microsoft-365-docs#3102]
Hello,

The documentation here is useful but it should perhaps elaborate more on the two required components for Microsoft Edge to successfully use S/MIME in OWA. Specifically:

1) The Microsoft Edge S/MIME Extension available here: https://microsoftedge.microsoft.com/addons/detail/microsoft-smime/gamjhjfeblghkihfjdpmbpajhlpmobbp
2) SmimeOutlookWebChrome.msi (or at least my understanding is that this is a separate piece of the required components. Please correct me if I am mistaken.)

The issue is I can get S/MIME to work once I used the MSI, but using the add-on page in (1) didn't work for me. Can the OWA team confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e106b4-4d03-6027-39ed-711e3949aef8
* Version Independent ID: ff0ca4b3-2583-51dc-24ce-ac4cfaa12eb0
* Content: [Configure S/MIME settings - Exchange Online for Outlook on web - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@rmda Thank you for your feedback. We are testing this and will confirm shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@rmda Thank you for your feedback. From the testing, I see that all I to do was to go to  Settings > Mail > S/MIME to install the S/Mime control (Edge and Chrome). 

@robmazz Is the S/Mime extension available here: https://microsoftedge.microsoft.com/addons/detail/microsoft-smime/gamjhjfeblghkihfjdpmbpajhlpmobbp a required component? Could you please confirm so I can update the document accordingly?

Thanks
Sri

**Comment by rmda** [comment]
@msbemba  What application are you seeing that? I can't go to Settings > Mail > S/MIME in Windows

**Comment by rmda** [comment]
Why is the public facing extension this build? "20.20.514.1" https://microsoftedge.microsoft.com/addons/getproductdetailsbycrxid/gamjhjfeblghkihfjdpmbpajhlpmobbp?hl=en-US&gl=US

But the one delivered through Outlook's handler later? "20.20.729.1" https://outlook.office.com/owa/SmimeCrxUpdate.ashx


I'm only able to get the older public facing extension working but the newer one doesn't seem to work.

**Comment by msbemba** [comment]
@chrisda This sounds more like a Support issue to me. However, I would like to get your feedback on whether but S/Mime extension available here: https://microsoftedge.microsoft.com/addons/detail/microsoft-smime/gamjhjfeblghkihfjdpmbpajhlpmobbp a required component.

@rmda Meanwhile, The best way to reach out to the OWA team and troubleshoot would be to open a support ticket via the need help option in the admin center. We will also try to get the requirements clarified with the author in the meantime.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @rmda Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future
