### ISSUE TITLE
Create an Audit Log retention policy in Compliance Center

### ISSUE THREAD

**Issue by ctryphon** [MicrosoftDocs/microsoft-365-docs#3104]
[Can you please update the documentation on this page (https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide&viewFallbackFrom=o365-worldwide%22) and let users know the "Audit retention policies" tab on the Audit page (https://compliance.microsoft.com/auditlogsearch) is not yet available.  I attempted to create a report using the "Create audit renetion policy" button, but couldn't find the report anywhere.  According to the documentation on that page, it says "the new audit retention policy is listed on the Audit retention policies tab.", but the tab doesn't display. 
Spent a few hours on this looking for the report and after opening a Microsoft ticket we found out this feature is not yet available. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ctryphon Thanks for the heads up/feedback. I will remove the bit about the tab. As per the section on viewing audit retention policies, youshould be able to get info about your policies by running the following command in EXO PowerShell:

Get-UnifiedAuditLogRetentionPolicy | Sort-Object -Property Priority -Descending | FL Priority,Name,Description,RecordTypes,Operations,UserIds,RetentionDuration

**Comment by markjjo** [comment]
Correction: you run the Get-UnifiedAuditLogRetentionPolicy in Security & Compliance Center PowerShell.
