### ISSUE TITLE
typo ('were' instead of 'where')

### ISSUE THREAD

**Issue by yeezus24** [MicrosoftDocs/microsoft-365-docs#3110]
[Enter feedback here]

Fourth line of the Message Submission Format block should start with 'where'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User submissions policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@yeezus24, I fixed it. But in the future, you can make updates like this directly without opening a GitHub issue first. For more information, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>. 

Thanks for the feedback.

Closing
