### ISSUE TITLE
authenication

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/microsoft-365-docs#3117]
Can we update the url and add the missing T?
Thanks!

https://docs.microsoft.com/en-us/microsoft-365/campaigns/m365-campaigns-multifactor-**authentication**?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae5f3d8d-c63f-d4ca-c310-36d9b91cd936
* Version Independent ID: c8b33fd1-75de-d2bf-27cc-6a9aa8f7826e
* Content: [Set up multifactor authentication - Microsoft 365 for Campaigns](https://docs.microsoft.com/en-us/microsoft-365/campaigns/m365-campaigns-multifactor-authenication?view=o365-worldwide)
* Content Source: [microsoft-365/campaigns/m365-campaigns-multifactor-authenication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/campaigns/m365-campaigns-multifactor-authenication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@O365scripts Thank you for your feedback. I have checked and don't find this broken URL in this document. Could you please help where the URL is missing T?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @O365scripts  appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
