### ISSUE TITLE
Wrong ISO

### ISSUE THREAD

**Issue by UrmasO** [MicrosoftDocs/microsoft-365-docs#3125]
ISO/IEC 27701 for security techniques requirements.
ISO/IEC 27001 for privacy management requirements.

Are you sure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac42bb5-3204-4839-6fcb-5a5052a0d9cb
* Version Independent ID: 57cde474-a2e7-fc4b-339d-3e28377ae035
* Content: [Accountability readiness checklist for the GDPR - Microsoft GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-arc-office365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/gdpr-arc-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-arc-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@UrmasO Thank you for your feedback. We have made changed to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3139

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @UrmasO check the comment added by Robert in PR. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
