### ISSUE TITLE
Documentation Outdated - References Resource Quota which is deprecated in SP Shell 

### ISSUE THREAD

**Issue by seancorryio** [MicrosoftDocs/microsoft-365-docs#3126]
Hi, this documentation is not correct. 

When running the provided script I get an error message WARNING: The parameter ResourceQuota is obsolete.

Would really appreciate update to documentation and powershell script as current documentation does not work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad800da8-dcea-57bd-6ab7-a238a6b27475
* Version Independent ID: 80a16be5-ccc0-2f05-0537-76c309919b28
* Content: [Create SharePoint Online sites and add users with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/create-sharepoint-sites-and-add-users-with-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/create-sharepoint-sites-and-add-users-with-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/create-sharepoint-sites-and-add-users-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@JoeDavies-MSFT I was able to test the resource quota on modern sites and it doesn't work, but for classic sites, it works. Could you please confirm so that I can add a note to the document?

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@msbemba Confirmed. Please add the note. Thanks.

**Comment by msbemba** [comment]
@seancorryio Thank you for your feedback. We have added a note that this parameter has been deprecated on modern sites but works only with classic sites. The same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3126

Thanks
Sri

**Comment by seancorryio** [comment]
Thank you very much for the quick response and for sharing the info to begin with!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @seancorryio Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
