### ISSUE TITLE
E-mail on UPDATES

### ISSUE THREAD

**Issue by davidslight** [MicrosoftDocs/microsoft-365-docs#3127]
We need to have emails on UPDATED status - for example the date on 67138 just went back by two weeks but there was no email sent to alert us. I guess it will be in the weekly digest but that is not sufficient.
Please add option to get alerts when items are UPDATED
David 
REFER TO: [Case #:22312909] - Teams meeting recordings to OneDrive for Business

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d48710a5-bfd4-dbbd-dc97-741feccd00af
* Version Independent ID: 5540a0cf-7de7-3082-59d2-a93ece028f60
* Content: [Message center - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/manage/message-center?WT.mc_id=365AdminCSH&view=o365-worldwide#unsubscribe-from-message-center-emails)
* Content Source: [microsoft-365/admin/manage/message-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/message-center.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@davidslight Thank you for your feedback. I have this turned on my tenant and receive an Email notification for major updates. If you want to receive email notices about major updates, verify that Send me emails for major updates is ON.

Hope this helps!

Thanks
Sri

**Comment by davidslight** [comment]
I also have this turned on for my many tenants. I am very familiar.
But I want another update when a “major update” is updated as was the case for MC222640
David

(Updated) Microsoft Teams: meeting recordings saved to OneDrive and SharePoint
MC222640, Plan For Change, Published date: Sep 22, 2020
Admin impact, New feature, User impact

**Comment by msbemba** [comment]
@davidslight Thank you for the feedback. 

@Sirkkuw This could be a one-off issue as well as I can confirm I received other updates but not on this one. Could you please check and let us know if this bug needs to be reported to the product group? 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Sirkkuw  Could you please check and let us know if this bug needs to be reported to the product group?

**Comment by lhcole** [comment]
This looks like it might have been a one-off issue and we'll be monitoring to see if this happens again.
