### ISSUE TITLE
ATP Safe Attachment counter in dashboard remains blank, while the feature is actively working?

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/microsoft-365-docs#3128]
Greetings,

Over a month ago, we enabled "ATP Safe Attachments" feature in Office 365 Security & Compliance. We also configured it to send notice of attachment blocks to an email address to monitor its effectiveness, and we have seen thousands of legitimate blocks (malicious attachments, no false positives). We were expecting these numeous occurances to show up as a rolling weekly sum in the "Threat Management Summary", but it remains blank as of today.

Is there any additional configuration required to allow the "ATP Safe Attachments" successful blocks to summarise and show up in the "Threat Management Summary"?

Best regards,
Jose

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a27a4e04-14ad-9e71-4e09-f696989c7e43
* Version Independent ID: 415df01d-14e6-9ec5-b928-1ae5c38d6df7
* Content: [Security dashboard overview - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/security-dashboard?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/security-dashboard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/security-dashboard.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by denisebmsft** [comment]
Adding @chrisda who now owns Office 365 ATP Safe Attachments.

**Comment by yogkumgit** [comment]
@chrisda Please add your explanation and help us resolving this issue. Thanks

**Comment by chrisda** [comment]
I should have read more closely. No additional configuration required. Basically, there are different Safe Attachments technologies going on that can be enabled/ disabled independently of each other:

- ATP (Safe Attachments) for SharePoint, OneDrive, and Microsoft Teams
- Safe Attachments policies (attachments in email messages)

The following reports will contain information about Safe Attachments detections:

- [ATP (Defender for Office 365) file types report](https://docs.microsoft.com/microsoft-365/security/office-365-security/view-reports-for-atp?view=o365-worldwide#defender-for-office-365-file-types-report).

- [Threat protection status report](https://docs.microsoft.com/microsoft-365/security/office-365-security/view-email-security-reports?view=o365-worldwide#threat-protection-status-report)

If detections aren't appearing in the Threat Management Summary, I suggest that you open a support case; there's nothing that we can do here from a documentation perspective.

**Comment by chrisda** [comment]
Closing
