### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by jennifer-eilers** [MicrosoftDocs/microsoft-365-docs#3130]
At the end of these steps, your domain will stay registered with the host that you purchased the domain from, but Microsoft 365 can use it for you email addresses (like user@yourdomain.com) and other services.

You should be your 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f2e4e45-6ad7-eb79-aecb-0d7a89b06a03
* Version Independent ID: 1059223e-5759-b130-41ac-5ea98cb5367e
* Content: [Add DNS records to connect your domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@jennifer-eilers Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3138

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jennifer-eilers Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
