### ISSUE TITLE
Old instructions about how to use eDiscovery

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#3131]
The article still contains instructions about how to use eDiscovery in Exchange Online, instead of Security and Compliance. The article should be updated, to contain the same detailed instructions, but adapted for eDiscovery/Content Search in SCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9d3d55-537e-52f4-72f6-c0879a1b595a
* Version Independent ID: ea130146-6bd6-348a-bc8f-4e65ad1ae987
* Content: [Recover deleted items in a user mailbox - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT gentle reminder, please help us resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
@Alex-Catalin Sorry for the extended delay. I will be removing this article today and redirecting it to its new version here: https://docs.microsoft.com/Exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages
