### ISSUE TITLE
images with links

### ISSUE THREAD

**Issue by hetzbh** [MicrosoftDocs/microsoft-365-docs#3132]
Although the content on this page is useful, the screenshots are tiny and they are not linked to a full size screenshots. Any chance that you could fix it please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58981cc-c653-509e-2bbf-3d2d0231b18c
* Version Independent ID: 7aa12d46-4f12-e06a-407d-7916e1748b69
* Content: [Threat Trackers - New and Noteworthy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-trackers?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/threat-trackers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-trackers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP  Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@MSFTTracyP gentle reminder please help us resolving this issue. Thanks.

**Comment by MSFTTracyP** [comment]
@hetzbh Thanks for your feedback on this. I'll look into scheduling a change to this article, time and workload permitting. My apologies for delays.

**Comment by tiburd** [comment]
The images in the article have been updated and can be expanded.
Closing this issue.

FYI: @yogkumgit
