### ISSUE TITLE
error in regex

### ISSUE THREAD

**Issue by elrod-johnson** [MicrosoftDocs/microsoft-365-docs#3133]
`<img height="?1"? width="?1"? sr\c=.?http\://`

do you really want `sr\c=` in the above line?
i don't think so, it should be `src=`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37115a33-d073-cf0d-1506-2d2571cf1007
* Version Independent ID: 07dd4b19-c5a5-1fba-cbad-3650922d357f
* Content: [Use mail flow rules to filter bulk email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-transport-rules-to-configure-bulk-email-filtering.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@elrod-johnson Thank you for your feedback. We have made necessary changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3177

The changes will reflect in the document once the author approves and merges the above PR.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @elrod-johnson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
