### ISSUE TITLE
Certificates on Hardware Tokens

### ISSUE THREAD

**Issue by michaelvgibson** [MicrosoftDocs/microsoft-365-docs#3134]
Hello, could you please add a section discussing whether or not medium security certificates, or certs tied to a hardware device such as USB, can be used (or not used) with the online product versions?  Thanks so much, Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132dea81-d2ff-4438-dcf1-e3be2972d00e
* Version Independent ID: c23ee300-4cac-05cf-c9bd-e60ca14933fc
* Content: [S/MIME for encryption in Exchange Online - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/s-mime-for-message-signing-and-encryption?view=o365-worldwide#supported-scenarios-and-technical-considerations)
* Content Source: [microsoft-365/security/office-365-security/s-mime-for-message-signing-and-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/s-mime-for-message-signing-and-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda  Please add your comment and help us in resolving this issue. Thanks.

**Comment by chrisda** [comment]
@michaelvgibson, I'm told that S/MIME in Outlook (Windows) and Outlook on the web support hardware based s/mime encryption certificates like on a smartcard, yubikey, or others.

Whether or not your medium-assurance certificate is S/MIME capable, and whether or not your machine is configured to use a hardware based encryption certificate is up to your admin.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @michaelvgibson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by michaelvgibson** [comment]
Sorry for the late reply.  Thanks for the feedback.  It appears that documentation is starting to roll out on how to accomplish this with Outlook on the Web.  It appears that on chromium based browsers that you need to enable an extension. 
 https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app?view=o365-worldwide

Thanks so much for the feedback.  All the best, Mike.
