### ISSUE TITLE
Admin -> Settings -> Settings

### ISSUE THREAD

**Issue by markburland** [MicrosoftDocs/microsoft-365-docs#3142]
Admin -> Settings -> Settings

Doesn't exist!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba164b8e-a574-0744-ce02-23bda994e505
* Version Independent ID: 05018469-d6f8-0eb5-956c-730991912f8b
* Content: [Turn Microsoft Bookings on or off](https://docs.microsoft.com/en-us/microsoft-365/bookings/turn-bookings-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/turn-bookings-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/turn-bookings-on-or-off.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@markburland Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3172

The correct navigation path to Bookings would be Admin-->Settings-->Org Settings

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @markburland Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
