### ISSUE TITLE
Blocking Senders In Quarantine

### ISSUE THREAD

**Issue by TomTurkington** [MicrosoftDocs/microsoft-365-docs#3143]
I keep clicking block sender in quarantine and the same senders keep showing up in my quarantine email.  If I click block sender that should mean don't quarantine them, kill them instead, so I don't understand why they keep showing up in the quarantine email/why blocking them isn't really working.  Otherwise, Outlook had a wonderful feature where you could just block domains and not just individual senders.  The quarantine email should have a similar option...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedcd379-0c7e-5b68-be04-e272ac53638d
* Version Independent ID: 664acd84-b4df-c943-e027-677f4340768e
* Content: [End-user spam notifications in Microsoft 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@TomTurkington Thank you for your feedback. It is by design that when you block a sender or domain, the blocked person can still send you mail, but if anything from his or her email address makes it to your email account, it’s immediately moved to the end-user quarantine.

If you are looking to delete the email without notifying anyone, you may have to use mail flow rules to accomplish that. For more information on mail flow rules, please refer to https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules

Hope this helps!

Thanks
Sri

**Comment by TomTurkington** [comment]
Thanks, but am not sure why the quarantine email says 'Block Sender' – it would be clearer if instead it said 'Always Quarantine' because apparently that's what it means.  Having the same spam senders show up in the quarantine email daily is a waste of my time as I have to check it to see if there are senders I don't want quarantined; I'd rather not get a quarantine email if all it contains is emails from people I've previously identified as spammers.  I'll review the mail flow rules, but I think it would behoove you to consider adding a link to those mail flow rules in the quarantine message so that users at least know that 'a', the block sender button doesn't really mean block sender, and 'b' there's actually a way to truly block them.

Tom Turkington
(206) 352-8202
tomt@zumasys.com

**Comment by msbemba** [comment]
@TomTurkington Thank you for the feedback. I have added a note to the document regarding the same. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3205.

Please note that once the author approves it takes 24-48 hours for the document to get updated.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TomTurkington Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
