### ISSUE TITLE
Incorrect Operation values for Azure AD operations

### ISSUE THREAD

**Issue by mbrancato** [MicrosoftDocs/microsoft-365-docs#3144]
Most of the audit log Operations do not have whitespace. In the section for Azure AD, however, the Operation values are a bit different. Seeing as this seems to be the official documentation for possible values, there seems to be a slight inaccuracy to the possible event values.

For example there is an Operation value listed in the documentation as:
```
Add member to group
```

However, the actual value returned from Azure AD is:
```
Add member to group.
```

The period at the end is important when using equality operators to detect events. Is there any further guidance that we are missing here to explain this? I'm assuming this applies to the other Azure AD events as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mbrancato** [comment]
I looked and the same goes for events in the "Application administration activities" section. There may be more. If this documentation is not the correct source for the audit log values, please let me know where the primary source is located.

**Comment by markjjo** [comment]
@mbrancato In general, I think you are correct in that the operation name for all **Azure** activities (at least ones where RecordType=8) end with a period. This is not the case for activities in other services. Not sure what you mean "equality operators", but I assume you're referring to something that is scripted or in PowerShell. I will add the period to operation names in the article you cited. 

I believe some of these RecordType=8 activities used to be documented in Azure documentation, but I spent a little time looking but couldn't find anything. 

However, I do have the following list of Azure operation names, where RecordType = 8. I don't think all of these are documented in this topic, and I don't plan to add them if they are not, but here is the is the list for your benefit. Note that, for some reason, the last 9 operations don't have a period. I assume this is not in error.

I hope this helps.

Set users oath token metadata enabled.
Remove owner from service principal.
Add role from template.
Add unverified domain.
Add contact.
Device no longer compliant.
Add member to group.
Delete device.
Add device configuration.
Remove partner from company.
Add app role assignment to group.
Set force change user password.
Delete group.
Add label.
Delete label.
Set DirSyncEnabled flag.
Update role definition.
Restore Group.
Set directory feature on tenant.
Add group.
Add registered users to device.
Device no longer managed.
Disable Strong Authentication.
Remove owner from policy.
Add users strong authentication phone app detail.
Remove unverified domain.
Update external secrets
Verify domain.
Hard Delete user.
Set user manager.
Remove OAuth2PermissionGrant.
Update domain.
Create application password for user.
Remove app role assignment from group.
Remove verified domain.
Add eligible member to role.
Update device.
Update role.
Add a deletion-marked app role assignment grant to group as part of link removal.
Set domain authentication.
Add app role assignment to service principal.
Convert federated user to managed.
Add a deletion-marked app role assignment grant to service principal as part of link removal.
Set federation settings on domain.
Remove owner from application.
Delete group settings
Remove app role assignment from user.
Add user.
Remove member from role.
Update policy.
Revoke consent.
Update contact.
Create group settings
Enable account.
Remove registered users from device.
Set DirSync feature.
Hard Delete application.
Add member to role.
Consent to application.
Add owner to policy.
Remove member from group.
Add verified domain.
Remove eligible member from role.
Add registered owner to device.
Change user license.
Add owner to service principal.
Update user.
Update company settings
Change user password.
Remove app role assignment from service principal.
Add OAuth2PermissionGrant.
Add policy to application.
Enable Strong Authentication.
Update application.
Add device.
Add policy to service principal.
Update device configuration.
Add member to administrative unit.
Add owner to application.
Remove users strong authentication phone app detail.
Add app role assignment grant to user.
Start applying group based license to users.
Remove policy credentials.
Add application.
Add service principal.
Finish applying group based license to users.
Remove service principal.
Delete application.
Add partner to company.
Add role assignment to role definition.
Delete role definition.
Remove policy from application.
Promote company to partner.
Delete application password for user.
Disable account.
Update label.
Remove member from administrative unit.
Add policy.
Update group.
Set Company Information.
Add role definition.
Remove policy from service principal.
Delete user.
Trigger group license recalculation.
Set group license.
Restore user.
Reset user password.
Add a deletion-marked app role assignment grant to user as part of link removal.
Delete policy.
Update StsRefreshTokenValidFrom Timestamp.
Remove service principal credentials.
Add owner to group.
Set password policy.
Remove registered owner from device.
Delete contact.
Remove owner from group.
Add service principal credentials.
Update service principal.
Hard Delete group.
Set company multinational feature enabled.
Restore application.
Add scoped member to role.
Remove scoped member from role.
Remove role assignment from role definition.
Update administrative unit.
Delete subscription.
Delete administrative unit.
Assign label to group.
Add administrative unit.


Directory scheduled for deletion
Directory deleted permanently
Update company
Update group settings
Create company
Create company settings
Delete company settings
Update application
Set Partnership
