### ISSUE TITLE
SIEM is standing for Security Information and Event Management not Security Incident and Event Management

### ISSUE THREAD

**Issue by mshaheen75** [MicrosoftDocs/microsoft-365-docs#3145]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1245b43f-721b-0bd0-b081-5307b5537e57
* Version Independent ID: d9ffc009-5576-9174-cc7c-b7caef1bb82b
* Content: [SIEM integration with Advanced Threat Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/siem-integration-with-office-365-ti?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/siem-integration-with-office-365-ti.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/siem-integration-with-office-365-ti.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@mshaheen75 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3168. Once the author approves the change, it could take 24-48 hours for the changes to reflect in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mshaheen75 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
