### ISSUE TITLE
How to check on the status of retention labels published to Exchange - Is third command correct?

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#3146]
The command shows:

" $xmlprops.Properties.MailboxTable.Property | ? {$_.Name -like "ELC*"}   ```"

That generates an error (yes ran the 2 pervious commands):

Where-Object : A positional parameter cannot be found that accepts argument '``'.

Should the command be:

" $xmlprops.Properties.MailboxTable.Property | ? {$_.Name -like "ELC*"}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b974f07-d9f4-38c6-39ac-5d53aeda45fc
* Version Independent ID: fab281b5-1ff8-6e71-1756-c0579770f523
* Content: [Create retention labels and apply them in apps to retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-apply-retention-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-apply-retention-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-apply-retention-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3146. Once this approved and merged by the author, the document will be live in 24 to 48 hours.

Thanks
Sri

**Comment by cabailey** [comment]
Yes, the erroneous ``` seems to be a formatting error used in Markdown for end of code block, and shouldn't be included in the actual command.  Thanks for flagging!  The actual PR to delete these characters are in https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3167 that I'll approve.
