### ISSUE TITLE
Add a link to more info on controlling the feature referenced.

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/microsoft-365-docs#3147]
There is a couple of locations to include in my case it was the https://security.microsoft.com/antispam default outbound policy not allowing double forwarding which was trail and error to find as there is no info on the definition of automatic vs enable setting. was only a mention on a blog article that tipped me off.
but some basic inclusion of there to look next would still be a great start,
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding, Automatic forwarding, 5.7.520 Access Denied, disable external forwarding, Your administrator has disabled external forwarding, outbound anti-spam policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@webstaff Thank you for your feedback. We have made changes to the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3204

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @webstaff Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
