### ISSUE TITLE
Service and Add-In's link doesn't go to page specified if new interface is enabled.

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/microsoft-365-docs#3148]
If I go to https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide and then https://admin.microsoft.com/AdminPortal/Home#/Settings/ServicesAndAddIns, it doesn't take me to the service and add-on page, since I have the new interface enabled.  It takes me to Org settings, which doesn't have an add-on option as mentioned in the instructions.  It has been moved over to the left side under org settings.
![Screenshot 2020-10-14 095033](https://user-images.githubusercontent.com/72881999/96020336-b8516e80-0e02-11eb-9e1e-98046d0d3804.png)

![Screenshot 2020-10-14 094711](https://user-images.githubusercontent.com/72881999/96020011-42e59e00-0e02-11eb-8173-f12d45b0542e.png)

**Comment by msbemba** [comment]
@rconiv Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3166. Once the author approves this it could take 24 to 48 hours for the changes to be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rconiv Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
