### ISSUE TITLE
missing key steps

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#315]
Mdm push cert and other preamble plus byod mam, byod Mdm, and Corp Device Mdm enrollment steps all missing - please add

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b63155-715a-14bf-c3bb-31b52ffcf8ec
* Version Independent ID: d274ba6f-50f2-a4ff-5981-f53561b7e438
* Content: [Get started with Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-overview#feedback)
* Content Source: [microsoft-365/business/microsoft-365-business-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/microsoft-365-business-overview.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by VLG17** [comment]
@gkens The article is describing how to download Office apps on your device and how to subsequently login with Microsoft 365 business credentials.

![image](https://user-images.githubusercontent.com/41186174/56638661-6dc0bd00-6677-11e9-830d-781ce7618dde.png)

The goal of this article is not to cover specific enrollment scenarios (BYOD) or types of software that can be used for MDM,MAM and MIM (Intune in this case). Adding this information would, in my opinion, overcomplicate this article.

Should one require this information, there are detailed articles covering it, such as:

https://docs.microsoft.com/en-us/intune/device-enrollment
https://docs.microsoft.com/en-us/intune/enrollment-options
https://docs.microsoft.com/en-us/intune/apple-mdm-push-certificate-get
https://docs.microsoft.com/en-us/intune/device-management

**Comment by gkens** [comment]
Perhaps add these links to an appendix?

Some of these are quite important such as the Mdm push cert  if you are using Mdm and iOS devices

Glenn Kime
Principal
Enspired IT of Ann Arbor
Voice: 734-228-7077
Fax: 734 219-5469
glenn.kime@enspireditaa.com
www.enspireditaa.com

________________________________
