### ISSUE TITLE
Auto-labeling for SharePoint Online

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/microsoft-365-docs#3152]
"Maximum of 25,000 automatically labeled files in your tenant per day."
"Maximum of 10 auto-labeling policies per tenant, each targeting up to 10 sites (SharePoint or OneDrive)."

Can we clarify the following related to these limits.
1) Can these limits be increased/modified on request for large customer tenants? (e.g. 100,000 users+?)
2) Is that 10 auto-label policies per sensitivity label per tenant? How would organizations which have more than 10 sensitivity labels apply auto-labeling?
3) Is the limit of 10 sites per policy only if specific sites are being specified vs an "entire organization"? Can we include guidance on how is this intended to be used when most large organizations have hundreds of thousands of SharePoint sites?
4) Do both of these limits apply to BOTH SharePoint and OneDrive collectively, or do they apply 25,000 for SPO and 25,000 for OneDrive, 10 SPO policies, 10 OD4B policies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide#compare-auto-labeling-for-office-apps-with-auto-labeling-policies)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please add your comment and help us, resolving this issue. Thanks.

**Comment by cabailey** [comment]
@dotnick365:  You must specify individual sites for SharePoint (and OneDrive) and cannot currently specify "an entire organization".  We are aware that these limitations in this first release are too restrictive for many customers.  Please open a support ticket to see if they can extend these limits for you.  Alternatively, (and I encourage you do this anyway) provide this product feedback on the UserVoice site: https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip
