### ISSUE TITLE
Repeated Configure

### ISSUE THREAD

**Issue by klishb** [MicrosoftDocs/microsoft-365-docs#3154]
Current document contains the following:

_"Never configure configure mail flow rules"_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@klishb Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3165. Once this is approved and merged the document will be live in 24-48 hours.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @klishb Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
