### ISSUE TITLE
Separate existing and new pc prep

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#316]
Please clearly state that autopilot is only for PCs not yet deployed or acquired.  Please clearly show the options for enrolling existing PCs 

Note that the link on how to upgrade from win 7 to win 10 pro has instructions that require a key.  Please add to note that 365 business users should just skip that step as 365 enrollment will provide a key, if my understanding is correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b63155-715a-14bf-c3bb-31b52ffcf8ec
* Version Independent ID: d274ba6f-50f2-a4ff-5981-f53561b7e438
* Content: [Get started with Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-overview#feedback)
* Content Source: [microsoft-365/business/microsoft-365-business-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/microsoft-365-business-overview.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
Thank you for the feedback. We have this topic on setting up new and existing PCs manually: https://docs.microsoft.com/en-us/microsoft-365/business/set-up-windows-devices
We are also in progress of updating the docs and I will make sure the fact that Autopilot is for new computers will be explained.
As for the key issue, I have reached out to the product group to ask for clarification, but usually I would point to Windows docs for upgrade issues.
