### ISSUE TITLE
This document is hard to find - not available in navigation

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#3160]
Please link this document to this article  https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption?view=o365-worldwide and this article https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption?view=o365-worldwide as well as put it on the navigation in the encryption section.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b0b9911-441e-68b7-e0dd-472f8e66b0ac
* Version Independent ID: 3760032b-5f82-b058-471f-97b4387d7bcc
* Content: [Encryption Risks and Protections - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-risks-and-protections?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/office-365-encryption-risks-and-protections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-encryption-risks-and-protections.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@Larryngolog Thank you for the feedback. We have added Encryption Risks and protections to the Related topics on the Encryption document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3242. I'll also check with the author to see if this can be added to the navigation in the encryption section.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Larryngolog Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Larryngolog** [comment]
Thanks!
