### ISSUE TITLE
Missing information about keys for at-rest encryption

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#3161]
Information about at rest and in transit is in this article https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-risks-and-protections?view=o365-worldwide but this article is not liked anywhere in this section. Please concatenate information from both of these articles or at least link them toghether.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14a729bb-ad0e-27bf-b119-beb99f1df9f4
* Version Independent ID: bc005f28-aa37-f52d-c328-ff547c1eb7b3
* Content: [Technical reference details about encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/technical-reference-details-about-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/technical-reference-details-about-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/technical-reference-details-about-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@Larryngolog Thank you for your feedback. It makes sense to relate both the topics. We have added a reference in the related topics section. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3241

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Larryngolog Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
