### ISSUE TITLE
AES128 for EXO

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#3162]
Hi! Is this up to date information that AES128 is still used by EXO? This article do not mention use of AES128 https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-bitlocker-and-distributed-key-manager-for-encryption?view=o365-worldwide 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b0b9911-441e-68b7-e0dd-472f8e66b0ac
* Version Independent ID: 3760032b-5f82-b058-471f-97b4387d7bcc
* Content: [Encryption Risks and Protections - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-risks-and-protections?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/office-365-encryption-risks-and-protections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-encryption-risks-and-protections.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@Larryngolog Thank you for the feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3240. Once the author approves the PR it could take 24-48 hours for the document to go live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Larryngolog Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Larryngolog** [comment]
Hi! Thanks for updating the document. Please also update the "FIPS 140-2 Validated" column for EXO in the table for MultiTenant - since all servers will be using 256 bit key, then I understand that the annotation "Yes, for servers that use AES 256-bit**" is no longer needed and the column for EXO should just say "Yes" like it does for SPO and S4BO. And this would mean that the footnote "**Most servers in the Exchange Online multi-tenant environment have been deployed with AES 256-bit encryption for BitLocker. Servers using AES 128-bit are being phased out." can also be removed.

**Comment by msbemba** [comment]
@Larryngolog Thank you. We have created a new PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3162 to update the document.


Thanks
Sri
