### ISSUE TITLE
Undoing an accidental submission is not covered

### ISSUE THREAD

**Issue by sk1tt1sh** [MicrosoftDocs/microsoft-365-docs#3164]
I had a user report a phish on accident and I can see the submission but can't undo that. Please provide guidance. Where can the user retrieve the email (it's not in quarantine) and where can I revert it, there's no option in the user submissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Admin submissions - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@sk1tt1sh Thank you for your feedback. Did the user report it via the report message add-in? I tested it now and the admin can only view what the user reported and cannot revert the user submission, however, the user can undo it by restoring it from Junk/deleted folder. I'll do a few more testing and add more details on this feature to the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sk1tt1sh Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
