### ISSUE TITLE
Typos and dupe info

### ISSUE THREAD

**Issue by dawholl** [MicrosoftDocs/microsoft-365-docs#3169]
Missing spaces and content with typos is duped

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92701183-1413-9e14-3109-53c2debe7d8b
* Version Independent ID: c1b54dbd-ac96-4582-b577-f09e8beba365
* Content: [Manage Industry news - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-industry-news?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-industry-news.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-industry-news.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@dawholl Thank you for your feedback. We have made corrections to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3224

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dawholl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
