### ISSUE TITLE
This link is dead

### ISSUE THREAD

**Issue by rfcomp** [MicrosoftDocs/microsoft-365-docs#3175]
https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/raw/live/Enterprise/media/maintain-group-membership-with-microsoft-365-powershell/GroupMaintPowerShellGenerator.xlsx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78793749-293c-d077-758a-8153b7c66e65
* Version Independent ID: 6b0c4055-ab10-5b9c-e3fa-ea7e447516ae
* Content: [Maintain Microsoft 365 group membership with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/maintain-group-membership-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/maintain-group-membership-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/maintain-group-membership-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@rfcomp Thank you for your feedback. The Excel file is no longer valid so the Tip has been removed from the document.

@yogkumgit This issue can be closed as there are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rfcomp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
