### ISSUE TITLE
Doc needs updating

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/microsoft-365-docs#3176]
It was very hard to find and took some time, but the dash board can be found here:
- https://protection.office.com/datamanagement/dashboard

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe34f7ee-fa7e-f023-1d3f-9049cdde25a2
* Version Independent ID: f251bf03-1d6e-6755-8a00-bcf6bcddfaee
* Content: [View the data governance reports - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/view-the-data-governance-reports?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/view-the-data-governance-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-the-data-governance-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@fixx-er Thank you for your feedback. We have added a Hyperlink to the document for easy access to the dashboard. The same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3239

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fixx-er Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
