### ISSUE TITLE
Allow word download

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#318]
Allow both word and pdf downloads so we can add steps while we customize our own 365 setup checklist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b63155-715a-14bf-c3bb-31b52ffcf8ec
* Version Independent ID: d274ba6f-50f2-a4ff-5981-f53561b7e438
* Content: [Get started with Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-overview#feedback)
* Content Source: [microsoft-365/business/microsoft-365-business-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/microsoft-365-business-overview.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
Hi,

Thank you for your feedback. Unfortunately our build system only allows producing a PDF downloadable.

Sirkku
