### ISSUE TITLE
Custom Senstive Information types NOT supported for content search.

### ISSUE THREAD

**Issue by fvhemert** [MicrosoftDocs/microsoft-365-docs#3185]
Since moving to substrate creating a search using CUSTOM sensitive information types does no longer work. Please remove the line below from the documentations and add a note saying SensitiveType only works for out-of-box classifiers.

You can also use the SensitiveType property to search for the name of a custom sensitive information type that you (or another administrator) created for your organization.

Francois van Hemert
Compliance Architect Modern Desktop COE
franvanh@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@fvhemert Thanks for the heads up. I've updated this info, adding a new section about limitations of searching for sensitive info types. In the future, as you are internal MSFT, you can contact me directly about changes to this topic. Revised topic will be published by end of day.
