### ISSUE TITLE
Limits - admins need to be able to measure

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/microsoft-365-docs#3189]
The limits section says a user can create up to 250 groups.
https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#group-limits

Can this section include instructions (or a link to relevant information) for determining which/how many groups a user has created? Or from the other direction, which user created the group? I'm only able to find this info in audit logs (which are only kept for 90 days) and not as an attribute of the resulting group when looking with get-unifiedgroup. Is it burried in graph somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#group-limits)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@npherson Thank you for your feedback. Unfortunately, there is no place in the admin center to view the number of groups a user has created. This has been added to Microsoft user voice as feature request and hopefully, this feature will be added soon.

User Voice -https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/33485983-office-365-group-owner

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @npherson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
