### ISSUE TITLE
Product key

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#319]
Need to inform 365 business admins and end users that they can skip requests for product key as long as they enroll in 365 (add details)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d66a7a3-2230-d907-5ff3-b3f7ed8c166a
* Version Independent ID: e437b87d-0845-bb6f-3b0b-8d9fd2b3013a
* Content: [Upgrade Windows devices to Windows Pro Creators Update](https://docs.microsoft.com/en-us/microsoft-365/business/upgrade-to-windows-pro-creators-update#feedback)
* Content Source: [microsoft-365/business/upgrade-to-windows-pro-creators-update.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/upgrade-to-windows-pro-creators-update.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@officedocsbot assign @mypil
