### ISSUE TITLE
Information is repeated two times in the last part of the document.

### ISSUE THREAD

**Issue by emmanhaider** [MicrosoftDocs/microsoft-365-docs#3191]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed89413a-e385-a12a-a32b-43d8cbd990d4
* Version Independent ID: a0c4c5c0-9a12-c20a-68c0-3a694e5d2521
* Content: [Form processing overview](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/form-processing-overview?view=o365-worldwide)
* Content Source: [microsoft-365/contentunderstanding/form-processing-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/form-processing-overview.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@emmanhaider Thank you for your feedback. The repeated information has been removed from the document.

@yogkumgit The issue can be closed as this was merged via Commit #https://github.com/MicrosoftDocs/microsoft-365-docs/commit/66d4647c408867db85f905a59aab1ed43909059d

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @emmanhaider Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
