### ISSUE TITLE
Information on this page not applicable for files in MSFT Teams ?

### ISSUE THREAD

**Issue by Raj-MCITP** [MicrosoftDocs/microsoft-365-docs#3192]
[Enter feedback here]

If I select SharePoint as a location, will my Teams SPO site will inherit the auto labelling option ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@Raj-MCITP Thank you for your feedback. Teams SPO site will not inherit the auto labeling option when you choose SP as a location. Instead one needs to select the sensitivity label for the new team during creation. Once it is selected the service automatically applies the same sensitivity label to the Microsoft 365 group and the connected SharePoint team site.

Apply Sensitivity Label to a new team -https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide#apply-a-sensitivity-label-to-a-new-team

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Raj-MCITP Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
