### ISSUE TITLE
Errors (typos) on the scripts on the page

### ISSUE THREAD

**Issue by artAlexion** [MicrosoftDocs/microsoft-365-docs#3193]
For, example the script start with GGet- instead of Get-  
I also see both -isLicensed filtered as false though the second one should probably be $True

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde00c3a-d106-76a1-1dc4-ad2306497187
* Version Independent ID: 27e87ec9-9ff3-333f-32fe-b45a4ee3d3fb
* Content: [View licensed and unlicensed Microsoft 365 users with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-licensed-and-unlicensed-users-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-licensed-and-unlicensed-users-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-licensed-and-unlicensed-users-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@artAlexion Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3233

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @artAlexion Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by artAlexion** [comment]
> @artAlexion Thank you for your feedback. We have made changes to the document via PR##3233
> 
> Thanks
> Sri

Thank you for acting so quickly!

**Comment by msbemba** [comment]
@artAlexion Thank YOU for providing timely feedback and making our documents look better.

Thanks
Sri
