### ISSUE TITLE
Only Global administrators can view\assign device based licenses

### ISSUE THREAD

**Issue by jasonfritts** [MicrosoftDocs/microsoft-365-docs#3195]
Section https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/manage-licenses-for-devices?view=o365-worldwide#assign-licenses-to-devices should be updated to reflect that you must be an AAD Global Administrator to see\assign device based licensing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bca3d86-2b5b-706f-ba26-291c8c0064ba
* Version Independent ID: 313eb228-35b4-6c47-4153-2137c62b6b20
* Content: [Manage licenses for devices](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/manage-licenses-for-devices?view=o365-worldwide#assign-licenses-to-devices)
* Content Source: [microsoft-365/commerce/licenses/manage-licenses-for-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/manage-licenses-for-devices.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@jasonfritts Thank you for your feedback. You are correct to Manage licenses for devices you need to be a Global Admin and an Important Note has been added to the document stating that You must be a Global admin to complete the tasks in this article.

Hope this helps!

@yogkumgit The issue can now be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jasonfritts Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
