### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by JST1MOteKILLya** [MicrosoftDocs/microsoft-365-docs#3196]
This guide needs to be updated, as it still references using EAC for searches when this has been depreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9d3d55-537e-52f4-72f6-c0879a1b595a
* Version Independent ID: ea130146-6bd6-348a-bc8f-4e65ad1ae987
* Content: [Recover deleted items in a user mailbox - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox?view=o365-worldwide#top)
* Content Source: [microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@JST1MOteKILLya Thank you for your feedback. Please see this current version of the content of the article you reference above: https://docs.microsoft.com/en-us/Exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages

We intend to delete the older version of the article and redirect its URL to the current version. Please let us know if the more current version of the article addresses your issue. Thanks.

CC: @JoeDavies-MSFT 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JST1MOteKILLya Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
