### ISSUE TITLE
Services & add-ins now Integrated Apps

### ISSUE THREAD

**Issue by brucelaing** [MicrosoftDocs/microsoft-365-docs#3201]
On newer tenancies the "Services & add-ins" option isn't available and you need to follow a different work flow. To roll out the Report Message for an organisation use "Integrated Apps", find the Report Message Add-in and it takes you through a new wizard to enable to the entire organisation or just certain users. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@brucelaing, it appears that this was fixed in PR #3166 based on related Issue #3148 

Thanks for the feedback,

Closing.
