### ISSUE TITLE
Microsoft Learning Azure / 365 - Incorrect page loading

### ISSUE THREAD

**Issue by Amudhan-GitHub** [MicrosoftDocs/microsoft-365-docs#3202]
[Enter feedback here]
I was going through Microsoft Azure Learning material for 
Examine privacy, compliance, and data protection standards.
On page 5, under Access Azure compliance documentation, within this sub heading
'Examine PCI DSS compliance' , I navigated to 'Azure compliance documentation' page, specifically to PCIDSS sectin under Audit Reports.

After reaching the PCIDSS page ( which I believe is part of Microsoft 365 Documentation), under this folder structure 
Microsoft 365    /  Compliance offerings    / Industry  / Financial    / PCI DSS  

On this page, 

Under Microsoft in-scope cloud services, the first bullet item
 •Azure and Azure Government
Upon clicking this URL, it took me  to 'Compliance offerings' (https://azure.microsoft.com/en-us/resources/microsoft-azure-compliance-offerings/)
which is incorrect, as it suppose to bring page for Azure Government (https://azure.microsoft.com/en-gb/global-infrastructure/government/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b95bd5-5663-90ab-f902-bab7887e4489
* Version Independent ID: 28d8c81c-5e29-b300-5b23-137e9692940e
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-pci-dss?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-PCI-DSS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Amudhan-GitHub Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3236

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Amudhan-GitHub Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
