### ISSUE TITLE
Confusing/mismatched information?

### ISSUE THREAD

**Issue by TheITguy666** [MicrosoftDocs/microsoft-365-docs#3206]
On this page you mention:
>> "When you want to block segments from communicating with each other, **you define two policies**: one for each direction. Each policy blocks communication one way only"

but on the previous page that I came (https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers) it mentions: 
>> "Information barriers **only supports two way restrictions**. One way restrictions, such as marketing can communicate with day traders, but day traders cannot communicate with marketing is not supported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please add your comment and help us resolving this issue. Thanks.

**Comment by chrfox** [comment]
The information is correct
