### ISSUE TITLE
End User Documentation

### ISSUE THREAD

**Issue by ChrisSweeneyMSFT** [MicrosoftDocs/microsoft-365-docs#3207]
Hey All, Chris from MMD CAT - These used to be links to end user PDF's (getting started with your new mmd device) at this page but they have been removed. Can we have these reinstated? Thanks heaps - Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 265113b7-c487-368f-d158-64579b855eb0
* Version Independent ID: 9c0624af-ca0a-8559-2d0a-a23134be72a4
* Content: [Get support for Microsoft Managed Desktop - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/working-with-managed-desktop/end-user-support?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/working-with-managed-desktop/end-user-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/working-with-managed-desktop/end-user-support.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
OH dear! I'm investigating....

**Comment by jaimeo** [comment]
@ChrisSweeneyMSFT are you talking about the 4 versions of downloadable PDFs in this article? https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/get-started-devices?view=o365-worldwide . All 4 downloaded for me just fine.

I don't think we've ever had a downloadable in microsoft-365/managed-desktop/working-with-managed-desktop/end-user-support.md ....

**Comment by christia53** [comment]
thank you so much

**Comment by ChrisSweeneyMSFT** [comment]
Yep got my wires crossed, Sorry Jamie. Thanks heaps.
