### ISSUE TITLE
I got alert "A high-severity alert has been triggered" , what should i do ?

### ISSUE THREAD

**Issue by zoelkarnain** [MicrosoftDocs/microsoft-365-docs#3208]
I got alert "A high-severity alert has been triggered" , what should i do ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance centers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@zoelkarnain If you're an admin in your org you might consider opening a ticket with [MS Support](https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide) and let them know what alert policy triggered the alert. If you're not an admin, you might consider contacting an admin in your organization.
