### ISSUE TITLE
Which group types are instantly finally deleted?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#3209]
Hello,

according to the Office 365 page at https://admin.microsoft.com/Adminportal/Home#/deletedgroups there are groups which are instantly and finally deleted thus no restore after 30 days is possible. Please mention which group types exist and which are non-restorable within 30 days.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d49db57-a705-20aa-e98d-5b3d6bbbf9fd
* Version Independent ID: 5a056f2c-03c9-7a34-3196-8bfb1039f6a5
* Content: [Restore a deleted group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/restore-deleted-group?WT.mc_id=365AdminCSH&view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/restore-deleted-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/restore-deleted-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@GiantCrocodile Thank you for your feedback. This document pertains to M365 groups and it will be retained for 30 days by default unless force deleted. The groups that are nonrestorable or permanently deleted are Non M365 groups like a distribution group or a  security group which do not have data attached to them.

Hope this helps!

Thanks
Sri

**Comment by GiantCrocodile** [comment]
@msbemba That did help! Would be great if this is mentioned in a short paragraph/note or if this information is linked to from some other article where this is mentioned. It may make sense to adjust the wording of the relevant sentence in the admin panel as it's somehow misleading then if you just can't restore those kind of groups simply because there's no content to restore.

**Comment by msbemba** [comment]
@GiantCrocodile Thank you for your feedback. We have added a note to the document stating that this describes restoring only M365 groups and not any other type of group. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3243

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GiantCrocodile Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GiantCrocodile** [comment]
@msbemba @yogkumgit I think the new note doesn't help that much. It just tells you that some groups are instantly deleted but it doesn't provide the reason for this. This information was given by the admin control panel of Office 365 already so that's no new information to the reader; the important part was which groups ain't restorable and that it is caused because they don't have data attached as you told me.

**Comment by msbemba** [comment]
@GiantCrocodile I get it. However, there are other data groups available in the power platforms (which cannot be accessed through this section) and it would only create confusion to add something like that. This document pertains only to M365 groups and the note mentions that other groups cannot be retrieved, So my opinion is to leave it as it is. I'll check with the author as well.

@MikePlumleyMSFT I'd like to get your opinion on this so we can modify the document if needed.

Thanks
Sri

**Comment by MikePlumleyMSFT** [comment]
@GiantCrocodile, I agree with @msbemba. The article is meant to provide simple task instructions. I think the note is a useful add, and definitely appreciate your input, but we wouldn't go into details around the behaviors of different group types in this article.

**Comment by GiantCrocodile** [comment]
@msbemba @MikePlumleyMSFT Maybe this discussion should be forwarded to the internal team at Microsoft who manages the texts in the user interface in admin cp of Office 365 as the text is misleading there: The text tells you that you won't get 100 % of data recovered which is bad and as an admin you want to read more about the details of that in the article that they refer to but the article doesn't deal with this as it doesn't fit in the article's context.

**Comment by MikePlumleyMSFT** [comment]
@GiantCrocodile I can follow up on that. Do you have a screenshot of the UI that you're referring to?

**Comment by GiantCrocodile** [comment]
@MikePlumleyMSFT I refer to this page https://admin.microsoft.com/Adminportal/Home#/deletedgroups with this paragraph:

```
Deleted groups

Deleted ‎Microsoft 365‎ groups will be shown here for 30 days before the group and its associated data are permanently deleted. If you need to, you can restore an ‎Microsoft 365‎ group and its data within this period. All other group types are permanently deleted immediately.

Learn more about restoring ‎Microsoft 365‎ groups
```

The last sentence (Learn more ...) refers to this article.

**Comment by MikePlumleyMSFT** [comment]
Thanks, @GiantCrocodile. Can you clarify what you mean by "The text tells you that you won't get 100 % of data recovered"? Are you referring to other types of groups being permanently deleted?

**Comment by GiantCrocodile** [comment]
@MikePlumleyMSFT Yes, that's what I mean. The last sentence is that other groups are being permanently deleted and thus non-recoverable. For details you shall read the article so you expect the article to not provide only information about how to delete M365 Groups but also why other groups won't be recoverable as it might be important to know as an admin.

**Comment by MikePlumleyMSFT** [comment]
Thanks, @GiantCrocodile. There isn't much additional information we can include. As far as I know, the other group types have never had a recycle bin capability. I'll talk to the UI writer to see if we can add clarity to the delete process for the other group types. I think that experience can be improved. If recycle bin for other group types is a feature that you'd like to see, I encourage you to post it to [UserVoice](https://office365.uservoice.com/forums/273493-office-365-admin).

**Comment by GiantCrocodile** [comment]
@MikePlumleyMSFT Thank you!
