### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#321]
Show troubleshooting steps if things go wrong during enrollment such as windows 10 business upgrade not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b63155-715a-14bf-c3bb-31b52ffcf8ec
* Version Independent ID: d274ba6f-50f2-a4ff-5981-f53561b7e438
* Content: [Get started with Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/microsoft-365-business-overview#feedback)
* Content Source: [microsoft-365/business/microsoft-365-business-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/microsoft-365-business-overview.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by VLG17** [comment]
@gkens There are specific articles covering how to troubleshoot failing Windows 10 updates/upgrades, such as:

https://docs.microsoft.com/en-us/windows/deployment/upgrade/resolve-windows-10-upgrade-errors
https://docs.microsoft.com/en-us/windows/deployment/upgrade/troubleshoot-upgrade-errors
https://support.microsoft.com/en-us/help/10587/windows-10-get-help-with-upgrade-installation-errors

If these do not help, the recommendation is to contact support. It's the fastest way of solving such an issue.

**Comment by mypil** [comment]
@officedocsbot close
