### ISSUE TITLE
DLP is blocking Internal Also for MS Teams

### ISSUE THREAD

**Issue by svijayababu81** [MicrosoftDocs/microsoft-365-docs#3210]
I have configured DLP for Teams in our environment. we configured  blocked only for External. But its blocking Internal also.

**Comment by yogkumgit** [comment]
@svijayababu81 Please provide the name of the document you are referring to. Thanks.

**Comment by yogkumgit** [comment]
@svijayababu81 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
