### ISSUE TITLE
M365 Apps for Business vs. M365 Apps for Enterprise

### ISSUE THREAD

**Issue by jreinhardtiv4** [MicrosoftDocs/microsoft-365-docs#3211]
This article isn't explicit in saying whether M365 Apps for Enterprise is required for the built-in labeling client. Put differently, will the built-in client be available to M365 Apps for Business clients running at the required build numbers? I've had difficulty finding an answer to this elsewhere, and this article seems to be a good place to explain this. Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Use sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#support-for-sensitivity-label-capabilities-in-apps)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@jreinhardtiv4 Thank you for your feedback. To use sensitivity labels that are built into Office desktop apps for Windows and Mac, you must use a subscription edition of Office (M365 Apps for Business or M365 Apps for Enterprise).

We have added it to the document and also made a note that this labeling client doesn't support standalone editions of Office, such as Office 2016 or Office 2019 but works with subscription versions.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This issue can be closed as there are no changes required in the document.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jreinhardtiv4 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
