### ISSUE TITLE
Update to state preview policies are not used

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/microsoft-365-docs#3213]
Hi folks,

can this be updated to say that the old preview policies are not EOL and should not be used.  Customers are to create their own.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 965d1d2f-81dd-8057-5a13-4f75cfe0c1f7
* Version Independent ID: 7bd2fc7a-93dd-9081-6d98-3e28fdebe342
* Content: [Set up conditional access policies - Microsoft 365 for Campaigns](https://docs.microsoft.com/en-us/microsoft-365/campaigns/m365-campaigns-conditional-access?view=o365-worldwide)
* Content Source: [microsoft-365/campaigns/m365-campaigns-conditional-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/campaigns/m365-campaigns-conditional-access.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@r-milne Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3238. Please note that once the author approves it could take 24-48 hours for the document to go live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @r-milne Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
