### ISSUE TITLE
"To force a sync between Intune and Microsoft Store for Business" refers to old Intune portal

### ISSUE THREAD

**Issue by mnkii** [MicrosoftDocs/microsoft-365-docs#3217]
The 'To force a sync between Intune and Microsoft Store for Business' section refers to Intune in portal.azure.com. Intune is no longer in Azure, but at https://endpoint.microsoft.com.

I am unable to locate 'force sync' in the new portal.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93e0cf16-3124-085e-d830-ffa849320f9d
* Version Independent ID: 5abfaf19-5d3d-b188-53c5-3dcd20a142d3
* Content: [Deploy apps to devices - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/deploy-apps?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-started/deploy-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/deploy-apps.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@aczechowski or @StuEwen or @ChristopherTulip can any of you advise on this?

**Comment by aczechowski** [comment]
@jaimeo what little I know of the topic, I think this article should help: https://docs.microsoft.com/en-us/mem/intune/apps/windows-store-for-business#configure-synchronization

CC @Erikre

**Comment by msbemba** [comment]
@mnkii Thank you for your feedback. To Force sync you need to follow the below instructions

1. Sign in to the [Microsoft Endpoint Manager admin center](https://go.microsoft.com/fwlink/?linkid=2109431).
2. Select **Tenant administration** > **Connectors and tokens** > **Microsoft Store for Business**.
3. Click **Sync** to get the apps you've purchased from the Microsoft Store into Intune.

I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3256

Thanks
Sri

**Comment by jaimeo** [comment]
Fixed in PR 3256

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mnkii Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
