### ISSUE TITLE
Label Analytics not working in M365 Security or Compliance centre

### ISSUE THREAD

**Issue by andrewrsww** [MicrosoftDocs/microsoft-365-docs#3218]
I can see label analytics within the Azure Information Protection portal but nothing showing in M365 Security or M365 Compliance center portals. Says Preview, is this feature working?
Configure analytics button just takes me to Azure Information Protection configure analytics pane, which is enabled, as demonstrated by information present in the AIP Usage report

**Comment by yogkumgit** [comment]
@andrewrsww Please mention the document you are referring to. Thanks.

**Comment by andrewrsww** [comment]
sorry thought it linked from the page
https://docs.microsoft.com/en-us/microsoft-365/compliance/label-analytics?view=o365-worldwide

**Comment by yogkumgit** [comment]
@chrfox  Please add your comment and help us in resolving this issue. Thanks.

**Comment by chrfox** [comment]
Hi @andrewrsww 
Thanks for your comment.  You should contact Microsoft support services to resolve your issue.
