### ISSUE TITLE
In the Set up web-only access for guest users - Client App feature is no longer in preview

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#3219]
The Set up web-only access for guest users section needs updating as the Clients app feature is no longer in preview. The steps and screenshot needs to be updated as the process is now different

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a secure guest sharing environment](https://docs.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document accordingly and the same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3237. Please note that once the author approves the PR it could take 24-48 hours for the document to go live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
