### ISSUE TITLE
Update the e-Discovery instructions from EAC to SCC usage

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#3220]
The article contains the instructions on how to perform an e-Discovery from Exchange Admin Center when we are pushing for the usage of the same feature from Security and Compliance Center.

The article should be updated to contain the same steps, but done from Security and Compliance Center, not from EAC.

The documentation can be updated, starting from these 3 articles:

https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions?view=o365-worldwide

https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide#create-a-search

https://docs.microsoft.com/en-us/microsoft-365/compliance/export-search-results?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9d3d55-537e-52f4-72f6-c0879a1b595a
* Version Independent ID: ea130146-6bd6-348a-bc8f-4e65ad1ae987
* Content: [Recover deleted items in a user mailbox - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/recover-deleted-items-in-a-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@Alex-Catalin Thank you for your feedback. Please see this current version of the content of the article you reference above: https://docs.microsoft.com/en-us/Exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages

We intend to delete the older version of the article and redirect its URL to the current version. Please let us know if the more current version of the article addresses your issue. Thanks.

CC: @JoeDavies-MSFT

**Comment by Alex-Catalin** [comment]
Hey,

Actually I see this part in the article, still mentioning that article that I want to be modified:

https://docs.microsoft.com/en-us/Exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages#more-information

As previously explained, you can also use the In-Place eDiscovery tool to find and export deleted items to a PST file. The user will use this PST file to restore the deleted messages to their mailbox. For detailed instructions, see Recover deleted items in a user's mailbox - Admin Help<https://docs.microsoft.com/en-us/office365/enterprise/recover-deleted-items-in-a-mailbox>.

And that article has references to the old EAC eDiscovery feature. So, if you plan on deleting the article, then don’t mention it anymore in the new article, in the More Information section 😊.

To be honest, I would still add in the new article the eDiscovery instructions, this time around from Security and Compliance, because some admins will feel more comfortable using this instead of Powershell cmdlets. The rest of the article seems fine to me.

Thank you,

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+3)
[cid:image001.png@01D6AC35.74B0DB40]

**Comment by msbemba** [comment]
@JoeDavies-MSFT I think what Alex says makes sense. Can I proceed with making changes to this article to reflect Security and compliance steps instead of the old EAC method?

Thanks
Sir

**Comment by msbemba** [comment]
@Alex-Catalin I have got a confirmation that we will be deleting the older version of the article and redirect its URL to the current version. All references to this document will be modified as well.

Hope this helps!

@yogkumgit I have got a confirmation that this will be deleted soon and will replace it with another document. Please close this issue.

Thanks
Sri

**Comment by Alex-Catalin** [comment]
Thank you Sriraman!

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+3)
[cid:image001.png@01D6B27C.52088FF0]

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Alex-Catalin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
