### ISSUE TITLE
CRL d-trust.net need to be added

### ISSUE THREAD

**Issue by tajaber** [MicrosoftDocs/microsoft-365-docs#3221]
As per doc https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes  the list of CRLs includes following 2 CRLs which are not listed under any required category
http://www.d-trust.net
http://root-c3-ca2-2009.ocsp.d-trust.net
Can you update this doc if both are required?

**Comment by yogkumgit** [comment]
@msmbaldwin  Please add your comment and help us in resolving this issue. Thanks.

**Comment by msmbaldwin** [comment]
@yogkumgit Sorry, can you clarify what you mean by "not listed under any required category"?  

d-trust **is** listed in the "What's Changing" section ("D-TRUST Root Class 3 CA 2 2009").

**Comment by yogkumgit** [comment]
@tajaber hope this explains else please clarify more about your query as asked by Baldwin.

**Comment by tajaber** [comment]
@msmbaldwin  I mean it is not added in the following doc https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please add your comment and help us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@tajaber Sorry about the extended delay. I have forwarded this request to the product team that maintains the list of endpoints for their consideration in a future update. Thanks for letting us know.
