### ISSUE TITLE
minimum versions of office 365 pro that this will work in need to be listed

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/microsoft-365-docs#3223]
minimum versions of office 365 pro that this will work in need to be listed

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Office 365 ATP - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@chrisda I was able to test Safe documents with multiple versions of O365 Pro plus./ M365 apps for enterprise, Is there is a minimum version required, or does it work with all versions of O365 Pro plus./ M365 apps for enterprise? Based on your feedback I shall update the document.

Thanks
Sri

**Comment by kshi-docs** [comment]
Minimum Version is Office Pro Plus Version 2004+.

**Comment by msbemba** [comment]
@kshi-docs Thank you for the input. 

@bakerm00 The minimum version is Office pro plus Version  2004+ and we have updated the same in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3281

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @bakerm00 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
