### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/microsoft-365-docs#3225]
This link "Export or delete user data using Business center privacy portal" is invalid and not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 632c11fa-8975-afd4-a050-7ff42ca3eb33
* Version Independent ID: 2b736015-0f61-4159-e102-77a056f8abec
* Content: [Office 365 Data Subject Requests Under the GDPR and CCPA - Microsoft GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-dsr-office365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/gdpr-dsr-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-dsr-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@robmazz The LInk to Export or delete user data using Business center privacy portal is broken and there are no other replacement documents. Could you please check internally to see if the site is down temporarily or can we remove the invalid link from this document?

Invalid Link:- https://support.office.com/article/export-or-delete-user-data-using-business-center-privacy-portal-eb48e2c1-4c91-4421-988d-5de497d1e8d8


Thanks
Sri

**Comment by yogkumgit** [comment]
@robmazz Please reply to this query. Thanks

**Comment by msbemba** [comment]
@robmazz Do you know if the Invalid URL can be fixed? or Can we remove the invalid URL from the document?

**Comment by robmazz** [comment]
@ahamin01 - thanks for the feedback, confirming new link with GDPR contacts.

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder

**Comment by robmazz** [comment]
@ahamin01 and @msbemba - thanks for your patience. No responses from resources, updating link to https://businessaccount.microsoft.com/ for now. Will update if it needs to be changed.
