### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by BayJayRakes** [MicrosoftDocs/microsoft-365-docs#3226]
Can this be updated to work with MFA?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5315da9-9aa3-c091-04fd-1b3dd42b975c
* Version Independent ID: 13f78819-03d0-adf2-2cf8-33b924469d96
* Content: [Search the mailbox & OneDrive for Business site for a list of users with Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-mailbox-and-onedrive-for-business-for-a-list-of-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@BayJayRakes Scripts won't work with MFA. Please see github issue #1428 for a possible work around using trusted IPs. Here is another alternative: https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps

You can also try to remove the connection steps from the script, then connect to EXO powershell or SharePoint powershell and then run the script.
