### ISSUE TITLE
Can you add PowerApps to the IL4 certified list of SaaS services?

### ISSUE THREAD

**Issue by dpardpar** [MicrosoftDocs/microsoft-365-docs#3227]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c79f14a-7b76-26cf-b97d-e8f2a922bb75
* Version Independent ID: e73e89a7-a122-67ce-154f-6cee9d6f41c5
* Content: [US Department of Defense (DoD) Provisional Authorization - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-dod-disa-l2-l4-l5?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-DoD-DISA-L2-L4-L5.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-DoD-DISA-L2-L4-L5.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@dpardpar Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3269

Please note that once the author approves this PR it could take 24-48 hours for the document to go live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dpardpar please check comment by Robert in PR. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
