### ISSUE TITLE
Disappointment

### ISSUE THREAD

**Issue by eddierocky** [MicrosoftDocs/microsoft-365-docs#3228]
[Enter feedback here]
Tried calling support which clearly stated that technical support is provide 24x7 on your website.
To my disappointment, no one pick the phone up. Then a machine voice says that to call back tomorrow
during working hours. 
If that is the case, why don't you just says so on your website.

Being a highly successful corporation, such a disappointment in purchasing your product. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a020c1-2f9f-26e7-5221-25b802bbc570
* Version Independent ID: 199e13d2-1b21-0b57-325f-91121b8f104d
* Content: [Support information for Malaysia - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/malaysia?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/malaysia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/malaysia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@eddierocky I'm sorry you had a poor experience trying to contact support. Would you please send the following information to me directly at cmcatee@microsoft.com so I can troubleshoot the problem?

•	ANI (Caller's telephone number)
•	Date of call
•	Time of call with time zone
•	Options, selected if any
•	Experience of call (no answer, got recording then disconnected, etc.)

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Can this issue be resolved. Please confirm. Thanks.

**Comment by cmcatee-MSFT** [comment]
Received no response to my request for further info, closing this issue.
