### ISSUE TITLE
typo Remediation means taking a proscribed action . should be prescribed

### ISSUE THREAD

**Issue by replyxf** [MicrosoftDocs/microsoft-365-docs#3234]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: badda2b8-bdb2-0518-18e4-35940e506c9b
* Version Independent ID: b7045ea1-ca2a-5bd3-0149-f7baed6fe6cf
* Content: [Remediate malicious email that was delivered in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@replyxf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3263

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @replyxf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
