### ISSUE TITLE
In-scope cloud services - does that include Power Platform

### ISSUE THREAD

**Issue by sayanghosh123** [MicrosoftDocs/microsoft-365-docs#3246]
[Enter feedback here]

The "Microsoft in-scope cloud services" mentions Dynamics 365. We are curious to understand if that includes the Power Platform services (given under the hood there are many common denominators). We have a customer ask this question so any feedback will be much helpful.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cf07d8-0269-34c9-c3b0-4b5d76998aaa
* Version Independent ID: 05fa83fb-08f2-881b-05af-16b872214ed9
* Content: [Australian Prudential Regulation Authority (APRA) - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-apra-australia?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-APRA-Australia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-APRA-Australia.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@robmazz On the ARPA Document, We have Microsoft In-scope cloud services and it mentions Azure, O365, and Dynamics 365. In my research, I found that the power platform and flow are included in Dynamics 365. Would you be able to confirm the same?

Thanks
Sri

**Comment by msbemba** [comment]
@robmazz Could you also please check these In-scope cloud services So that we can update the issue and the document.

Thanks
Sri

**Comment by robmazz** [comment]
@sayanghosh123 - thanks for this feedback, will certainly add if applicable. @msbemba - AUS CELA is reviewing, will add when approved (pending other changes).
