### ISSUE TITLE
No Reports dropdown in Reports > Usage

### ISSUE THREAD

**Issue by useyourblinker** [MicrosoftDocs/microsoft-365-docs#3247]
The M365 reports page shows no such drop-down to let you choose reports.

I'm not sure if it did at some point - but it certainly doesn't now.

Can this page be updated to reflect the Reports > Usage page properly? I can't find the Exchange usage of the users.

The proper way to get to this seems to be to actually click on a report first with the 'View more' button.

THEN at the upper left, you can change the report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e612a4e4-d051-27a7-e54a-bb1ac3fe0849
* Version Independent ID: 653be32f-e4e8-8a72-98b3-a629238ecbd5
* Content: [Microsoft 365 Reports in the admin center - Mailbox usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/mailbox-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/mailbox-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@useyourblinker Thank you for your feedback. We have modified the document to reflect the correct steps. The same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3264

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @useyourblinker Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
