### ISSUE TITLE
Additional Info Needed for Admins Retiring On-Prem Active Directory

### ISSUE THREAD

**Issue by jsavage8** [MicrosoftDocs/microsoft-365-docs#3248]
Like many before me (probably), I came to this article because I'm helping a client retire their on-premise Active Directory environment and move fully into Azure and I could use a little more info on what other steps to take to clean up Azure when you intend to retire Azure AD Connect permanently.  For example, if I simply follow these steps to disable directory synchronization, I'll still receive alerts from the AAD Connect Health Service that it's not receiving the latest data from the server.  Ideally there would be instructions for safely disabling \ cleaning that up too.

Might be better to have a whole separate article on retiring on-premise Active Directory, but if there is one, I haven't been able to find it and this seems like the closest thing.  If there is one, then I would think this article should at least have a link to it.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3edc072a-e71f-02a2-7974-3b2d4f820b39
* Version Independent ID: f20102f3-a74b-4c46-8ca7-04fdf4ad2886
* Content: [Turn off directory synchronization for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/turn-off-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/turn-off-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/turn-off-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@jsavage8 Thank you for your feedback. This document pertains only to Turning Off Directory synchronization. I have searched and could not find a Microsoft blog that talks about retiring on-prem AD.  The closest I could find was for Common use-cases and scenarios for Azure Active Directory Domain Services - https://docs.microsoft.com/en-us/azure/active-directory-domain-services/scenarios

@JoeDavies-MSFT Do you know if we have another document that talks about retiring On-prem AD so that we can link it to this document?

Thanks
Sri

**Comment by msbemba** [comment]
@jsavage8 Unfortunately there are no documents in M365 or Azure which talk about retiring  On-prem AD and moving to AAD. If you have any other questions or modifications that need to be done on this document, let us know.

@yogkumgit There are no changes required in this document at the moment. Please close the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jsavage8 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TiloGit** [comment]
@jsavage8 can you share any steps you needed to take to retire your on-prem AD? Any pitfalls?

**Comment by TechHead-Marcus** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>Let's gather
important things to check </p>

<div style='direction:ltr'>



Source | Area | Comment
-- | -- | --
Marcus | Groups Review | Before shutting   down AD Connect sync, be certain to check all dynamic groups for possible   links to on-site user parameters. See Tech Heads M365 audit log @ ~2-3 PM   8/23/23 for the change that reset the dynamic group population query.
Learn | Cutover task | Be   ready to stop sync related alerts from occurring when you turn off sync. Receive activity log alerts on Azure service   notifications using Azure portal - Azure Service Health \| Microsoft Learn in reverse. 🤔
Imaginary | Final Tasks | If   you want to remove Azure AD Connect completely, you should also delete the   service principals, the synchronization account, and the sync groups that   were created by the installation. You can use PowerShell commands or the   Azure portal to do this. For more details, see the official documentation: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-steps-delete (link doesn't work, AI generated 🤣)



</div>


</body>

</html>
Let's gather important things to check 
Source	Area	Comment
Marcus	Groups Review	Before shutting down AD Connect sync, be certain to check all dynamic groups for possible links to on-site user parameters. If so, change that dynamic group population query with only cloud parameters. This was my one error. 
Learn	Cutover task	Be ready to stop sync related alerts from occurring when you turn off sync. [Receive activity log alerts on Azure service notifications using Azure portal - Azure Service Health | Microsoft Learn](https://learn.microsoft.com/en-us/azure/service-health/alerts-activity-log-service-notifications-portal) in reverse. 🤔
Imaginary	Final Tasks	If you want to remove Azure AD Connect completely, you should also delete the service principals, the synchronization account, and the sync groups that were created by the installation. You can use PowerShell commands or the Azure portal to do this. For more details, see the official documentation: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-steps-delete (link doesn't work, AI generated 🤣)

**Comment by TiloGit** [comment]
i also dumped out all user and group info (with object id and Immutable Id)

here my PS: 
```powershell
#Report Synced Users
#########
$vfUsers = Get-MsolUser -All
###
$FileDate = get-date -uformat "%Y-%m-%d_%H%M%S"
$vfUsers | Where {$_.UserType -ne "Guest"} | Where {$_.ImmutableId -ne $null} | Sort-Object UserPrincipalName | Select-Object UserPrincipalName,DisplayName,ObjectId,ImmutableId,ValidationStatus,WhenCreated,UserType,IsLicensed,Errors | Export-csv "$($FileDate)_ADSyncedUsers.csv" -NoTypeInformation

###Report Synced Groups
#########
$vfGrp = Get-MsolGroup -All
###
$FileDate = get-date -uformat "%Y-%m-%d_%H%M%S"
$vfGrp | Where {$_.LastDirSyncTime -ne $null} | Sort-Object CommonName | Select-Object CommonName,ObjectId,LastDirSyncTime,GroupType | Export-csv "$($FileDate)_ADSyncedGroups.csv" -NoTypeInformation


####################################
####################################
import-module azuread
Connect-AzureAD 

##for user
#########
$vfUsers = Get-AzureADUser -All:$true -Filter "DirSyncEnabled eq true"
###
$FileDate = get-date -uformat "%Y-%m-%d_%H%M%S"
$vfUsers | Select UserPrincipalName,DisplayName,AccountEnabled,ObjectId,ImmutableId,OnPremisesSecurityIdentifier,UserType, @{n="onPremDN"; e={$_.ExtensionProperty.onPremisesDistinguishedName}}, @{n="createdDateTime"; e={$_.ExtensionProperty.createdDateTime}} | Export-csv "$($FileDate)_ADSyncedUsers.csv" -NoTypeInformation

##for groups
#########
$vfGrp = Get-AzureADGroup -All:$true -Filter "DirSyncEnabled eq true"
###
$FileDate = get-date -uformat "%Y-%m-%d_%H%M%S"
$vfGrp | Sort-Object DisplayName | Select-Object DisplayName,ObjectId,LastDirSyncTime,OnPremisesSecurityIdentifier | Export-csv "$($FileDate)_ADSyncedGroups.csv" -NoTypeInformation
```
