### ISSUE TITLE
Clarity on apostrophe in userPrincipalName

### ISSUE THREAD

**Issue by VinnyBenfanti** [MicrosoftDocs/microsoft-365-docs#3251]
Under userPrincipalName in section 2. Directory object and attribute preparation, we list the apostrophe as both an Invalid character and Character allowed.

Invalid characters: \ % & * + / = ? { } | < > ( ) ; : , [ ] " '
Characters allowed: A – Z, a - z, 0 – 9, ' . - _ ! # ^ ~

**Comment by yogkumgit** [comment]
@VinnyBenfanti Please mention which document you are referring to. Thanks

**Comment by VinnyBenfanti** [comment]
@yogkumgit Here is a link to the document [Prepare for directory synchronization to Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-for-directory-synchronization?view=o365-worldwide#2-directory-object-and-attribute-preparation)

**Comment by msbemba** [comment]
@VinnyBenfanti Thank you for your feedback. The apostrophe is a valid character and we have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3279

Thanks
Sri

**Comment by VinnyBenfanti** [comment]
Thanks Sri.

Vinny Benfanti, CISSP<mailto:vinny.benfanti@microsoft.com>
Security Architect
Customer Experience & Success
Worldwide Commercial Business

[cid:image001.png@01D6ABFA.25FF4B70]

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @VinnyBenfanti Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
