### ISSUE TITLE
Import User template in documentation is incorrect. Does not match headers listed in 'Import_User_Template_en.csv' downloaded from tenant. (Additional 'Fax' column.)

### ISSUE THREAD

**Issue by QuickBASIC** [MicrosoftDocs/microsoft-365-docs#3252]
**Columns from 'Import_User_Template_en.csv' example downloaded from Portal:**

    User Name,First Name,Last Name,Display Name,Job Title,Department,Office Number,Office Phone,Mobile Phone,Fax,Address,City,State or Province,ZIP or Postal Code,Country or Region

**Columns provided in documentation.**

    User Name,First Name,Last Name,Display Name,Job Title,Department,Office Number,Office Phone,Mobile Phone,Fax,Address,City,State or Province,ZIP or Postal Code,Country or Region

Attempting to import CSV from text block in documentation gives error:
![image](https://user-images.githubusercontent.com/7226914/96923068-bfb9ed00-147e-11eb-85fd-411c971d710b.png)

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99474cca-d2bc-d602-71ba-5c20e894429a
* Version Independent ID: 5aa17d74-a77f-82ed-48db-ff10413784bb
* Content: [Add several users at the same time to Microsoft 365 - Admin Help - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/add-several-users-at-the-same-time?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/add-several-users-at-the-same-time.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/add-several-users-at-the-same-time.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@QuickBASIC Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3266

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @QuickBASIC Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
