### ISSUE TITLE
Problem with a column in one place

### ISSUE THREAD

**Issue by Kajt90** [MicrosoftDocs/microsoft-365-docs#3255]
Hello!

The document needs a small change to the formatting in this part:

SFV:SFEFiltering was skipped and the message was allowed because it was sent from an address in a user's Safe Senders list.
For more information about how admins can manage a user's Safe Senders list, see Configure junk email settings on Exchange Online mailboxes.

The text needs to be moved to the next cell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Kajt90, I fixed it: `|`SFV:SFE`Filtering...` to `|`SFV:SFE`|Filtering...`.

Thanks for the feedback.

Closing

**Comment by Kajt90** [comment]
Thx, have a great one!

pt., 23 paź 2020, 19:12 użytkownik Chris Davis <notifications@github.com>
napisał:
