### ISSUE TITLE
SharePoint Syntex: Managed Metadata entity extractor not fetching values in document library

### ISSUE THREAD

**Issue by pk091990** [MicrosoftDocs/microsoft-365-docs#3257]
I've set up SharePoint Syntex on my sharepoint online tenant and attach model to another site document library.
I'm getting values of Single line of text field in my document library but not for managed metadata field.

In the below image: BChannel is a Managed metadata field which is attached to a global termset and BChannelText is Single line of text field.

![image](https://user-images.githubusercontent.com/46436213/97017604-c07c7d00-156b-11eb-9b0e-0157fdc2b538.png)

Steps to create MM Entity Extractor:
1: Create a global termset "**ABC**" in SharePoint Admin Center and add two terms i.e. DIRECT and INDIRECT.
2: Create site column "BChannel" of MM type in content center site collection and mapped to ABC termset.
3: In the content center site, click on New Entity Extractor, select newly created site column BChannel and train the model for the same.
![image](https://user-images.githubusercontent.com/46436213/97018265-937c9a00-156c-11eb-99f6-e4dc9238c3a0.png)
4: Sync the attached library , Select documents -> Click on "Classify and extract" button. Wait for loading of managed metadata.
5: All Single line of text entity data autopupulate after sometime but not managed metadata.

Please let me know if I'm missing anything. Thanks in advance !

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fa54e6e-7eb6-c9de-d159-5603720614f3
* Version Independent ID: fc7e230a-19f4-d336-5ce6-5bb9f2a87fd2
* Content: [Create an extractor](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/create-an-extractor?view=o365-worldwide)
* Content Source: [microsoft-365/contentunderstanding/create-an-extractor.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/create-an-extractor.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by pk091990** [comment]
Any update on this ?

**Comment by yogkumgit** [comment]
@efrene  Please add your comment and help us in resolving this issue. Thanks.

**Comment by MikePlumleyMSFT** [comment]
@seansquires can you help?

**Comment by seansquires** [comment]
Apologies for the delayed reply - thank you for reporting the issue @pk091990 - you did all the right steps and uncovered a code regression. The team has already identified and submitted a fix. It's rolling out now and should be working as advertised (against a global term set) next week. Thanks for reporting - and your patience!

**Comment by yogkumgit** [comment]
@seansquires Thank you very much for the contribution and sharing this explanation. @pk091990 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
