### ISSUE TITLE
Table in "Step 3 (optional): Set up groups for communication compliance" seems incomplete

### ISSUE THREAD

**Issue by jebeckham** [MicrosoftDocs/microsoft-365-docs#3258]
In the first row, M365 Groups are mentioned but not in the second row.  In the second row, Mail-enabled security groups are mentioned but not in the first row.  Are M365 Groups supported to assign reviewers and are Mail-enabled security groups supported to apply the policy to supervised users?

**Comment by msbemba** [comment]
@jebeckham Thank you for your feedback. I guess you are referring to the document:- https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure?view=o365-worldwide


1)Reviewers are be assigned individually and no groups are supported.
2)mail enabled security groups are not supported to apply the policy to supervised users. 

I have made a change to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3288

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jebeckham Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
