### ISSUE TITLE
missing endpoint *.servicebus.windows.net

### ISSUE THREAD

**Issue by tajaber** [MicrosoftDocs/microsoft-365-docs#3267]
Following 2 endpoints need to be added explicitly in the table of "Microsoft 365 Common and Office Online"

*.passwordreset.microsoftonline.com
*.servicebus.windows.net

For *.passwordreset.microsoftonline.com , it is already under *.microsoftonline.com ID 59, but still better to add another row for Password Writeback and SSPR

For *.servicebus.windows.net it is not in the doc, even it is required for SSPR, it is only mentined on the troubleshooting guide https://docs.microsoft.com/en-us/azure/active-directory/authentication/troubleshoot-sspr-writeback 
and it is not mentioned in the SSPR or Writeback requirements docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@tajaber *.windows.net is listed in https://docs.microsoft.com/en-us/azure/azure-portal/azure-portal-safelist-urls?tabs=public-cloud. Adding subdomains of the *.microsoftonline.com endpoint can become a Microsoft and customer administrative burden. Thanks for your suggestions.
