### ISSUE TITLE
Couldn't find Delete directory option in Azure Active Directory admin center

### ISSUE THREAD

**Issue by grzegorz-silarski** [MicrosoftDocs/microsoft-365-docs#3268]
Couldn't find **Delete directory** option on Azure Active Directory admin center page.
I found **Delete tenant** instead that i believe is the right option here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adb403b-fded-7b9c-c093-915ca9bb348d
* Version Independent ID: df08fc6b-a752-084b-448a-a253db2a40d5
* Content: [Close your account](https://docs.microsoft.com/en-us/microsoft-365/commerce/close-your-account?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/close-your-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/close-your-account.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@grzegorz-silarski Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3280

You are correct the option is changed to Delete tenant now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @grzegorz-silarski Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by grzegorz-silarski** [comment]
Thank you @msbemba @yogkumgit. I'm happy that I could help here.
