### ISSUE TITLE
max simultaneous ps sessions that can be opened by a single admin

### ISSUE THREAD

**Issue by bobsun0917** [MicrosoftDocs/microsoft-365-docs#3271]
[Enter feedback here]

Could you please share the exact number for max simultaneous ps sessions that can be opened by a single admin? How to check the current open sessions? I've searched the documents but not able to find the answers. 

"A default PowerShell throttling policy is assigned to each tenant at tenant creation. These settings affect other items, such as the maximum number of simultaneous PowerShell sessions that can be opened by a single administrator."

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7b428f-d987-3ff3-a710-ed2e657f488c
* Version Independent ID: 90c77de6-05e6-db91-d684-2a7052c73301
* Content: [Microsoft 365 Resource Limits - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-resource-limits?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-resource-limits.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-resource-limits.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@JoeDavies-MSFT I tested this and It works for three connections Simultaneously. However, wanted to get a confirmation from you before making edits to the document. Could you please confirm the max simultaneous PS sessions that can be opened by a single admin?

Thanks
Sri

**Comment by msbemba** [comment]
@JoeDavies-MSFT I can confirm that it worked on three sessions simultaneously on Powershell. Could you please confirm this limit with engineering so that I can update the document?

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@bobsun0917 @msbemba The maximum number of simultaneous sessions is 5. The articles that describe the limit of 3 are being updated.

**Comment by msbemba** [comment]
@JoeDavies-MSFT Thank you for the update.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bobsun0917 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
