### ISSUE TITLE
Note on Point 125 in the list of common endpoints to whitelist

### ISSUE THREAD

**Issue by toskr** [MicrosoftDocs/microsoft-365-docs#3273]
What is currently listed in point 125of this document:

"*.entrust.net, *.geotrust.com, *.omniroot.com, *.public-trust.com, *.symcb.com, *.symcd.com, *.verisign.com, *.verisign.net, apps.identrust.com, cacerts.digicert.com, cert.int-x3.letsencrypt.org, crl.globalsign.com, crl.globalsign.net, crl.identrust.com, crl.microsoft.com, crl3.digicert.com, crl4.digicert.com, isrg.trustid.ocsp.identrust.com, mscrl.microsoft.com, ocsp.digicert.com, ocsp.globalsign.com, ocsp.int-x3.letsencrypt.org, ocsp.msocsp.com, ocsp2.globalsign.com, ocspx.digicert.com, secure.globalsign.com, www.digicert.com, www.microsoft.com"

It would be great if there was a note, that those endpoints are required for certificate validation.

It's for important for Hybrid customers, who only whitelist the endpoints mentioned in this article:
https://docs.microsoft.com/en-us/sharepoint/hybrid/cloud-hybrid-search-faq

And every few months they have an outage, after we change certificates in Azure/SPO endpoints, and their on-prem servers cannot establish SSL connections to Azure any more, as they cannot validate new intermediate certificates from DigiCert.

It would be really helpful if a note was added in this FAQ too:
https://docs.microsoft.com/en-us/sharepoint/hybrid/cloud-hybrid-search-faq

Near the end of it, there's a section about endpoints to be whitelisted. It should say that that whitelisting CA and CRL Urls is also required, referencing this article for a full list of endpoints required for certificate validation.

Unfortunately I cannot open an Issue for that FAQ, because the GitHub feedback button is missing from that page.

Why is that GitHub button missing from so many pages nowadays?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@toskr Thank you for your feedback.  We will work internally and get this note added to the document.

**Comment by msbemba** [comment]
@JoeDavies-MSFT I'm not able to add a note to this document on point 125. This links to another file that I don't have access to. Could you please help us in adding a note that the endpoints mentioned in 125 are required for certificate validation?

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@toskr Sorry for the extended delay. I have forwarded your request to the team that maintains that information for their consideration in a future update. Thanks for letting us know.
