### ISSUE TITLE
In proper information.

### ISSUE THREAD

**Issue by tanmoy1338** [MicrosoftDocs/microsoft-365-docs#3274]
![97183644-092e7300-17c4-11eb-9d48-6e8c9a04beca](https://user-images.githubusercontent.com/30682809/98816852-4430d780-244f-11eb-879b-3996881fd1d3.png)
This site does not provide real information to users where the Personal OneDrive data are stored. After going through this [site](https://docs.microsoft.com/en-in/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide) it seems that my Personal OneDrive data is stored in India (I'm from India), however my network tools provides me information that OneDrive application is uploading data to the IP address highlighted in the screenshot.

Country -United States (US)
Continent - North America (NA)
Coordinates - 37.751 (lat) / -97.822 (long)
Time- 2020-10-26 09:01:09 (America/Chicago)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://docs.microsoft.com/en-in/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by tanmoy1338** [comment]
![Untitled](https://user-images.githubusercontent.com/30682809/97183644-092e7300-17c4-11eb-9d48-6e8c9a04beca.png)

**Comment by yogkumgit** [comment]
@dmwmsft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by dmwmsft** [comment]
We do not publish the data location for Personal OneDrive.

**Comment by yogkumgit** [comment]
@dmwmsft Thank you very much for sharing this explanation. @tanmoy1338 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
