### ISSUE TITLE
License levels are wrong

### ISSUE THREAD

**Issue by AaronDinnage** [MicrosoftDocs/microsoft-365-docs#328]
The headers for Office 365, Windows, and EMS all say "E3", but the features listed include a mix of E3 and E5 license requirements.  For example, Windows features include Defender ATP as a required component, it requires Windows E5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4d0218-aec5-1ac8-9511-7f9eeed72757
* Version Independent ID: ac0ad701-2cdb-ddbf-9426-b0ede6e646f0
* Content: [Microsoft Managed Desktop technologies](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/intro/technologies#feedback)
* Content Source: [microsoft-365/managed-desktop/intro/technologies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/intro/technologies.md)
* Service: **m365-md**
* GitHub Login: @TrudyHa

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@AaronDinnage - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by jdeckerms** [comment]
Assigning to Jaime

**Comment by mertenar** [comment]
Updated for accuracy, but will be looking to make larger revision to relevant MMD sections in near future to better align with 365 and EMS license descriptions on their sites.

**Comment by mypil** [comment]
@AaronDinnage  - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
