### ISSUE TITLE
SPO file types scanned

### ISSUE THREAD

**Issue by vpatton777** [MicrosoftDocs/microsoft-365-docs#3282]
Can you please elaborate on the statement "Heuristics determine the files to scan". Which file types are scanned for malware?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9cd0ac5-2049-7e80-302e-e0f08857f6b4
* Version Independent ID: 7ca74c37-9929-bfc2-8a27-046457d2f67a
* Content: [Built-in virus protection in SharePoint Online, OneDrive, and Microsoft Teams - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/virus-detection-in-spo?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/virus-detection-in-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/virus-detection-in-spo.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP  Please add your comment and help us in resolving this issue. Thanks.

**Comment by chrisda** [comment]
@vpatton777, I don't think we can go into much detail without revealing methods that might help attackers. It's likely a combination of file type, files of similar name/type/fingerprint that were reported as malware by others in the service, frequency/rate of similar files uploaded throughout the service, etc.

The important point is: not all uploaded files are automatically scanned.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @vpatton777 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
