### ISSUE TITLE
Chromium Edge should be added to SharePoint-Compatible PDF readers

### ISSUE THREAD

**Issue by mitanabe** [MicrosoftDocs/microsoft-365-docs#3293]
Chromium Edge should be added as a supported viewer for windows 10 in this page (https://docs.microsoft.com/en-us/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm).
The following page shows Chromium Edge is supported for SharePoint IRM.

https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers
Support for previous formats

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da662e1-5ae5-7760-1321-26cd2bab997a
* Version Independent ID: 60319761-1406-6c06-1620-e1a484468879
* Content: [SharePoint-Compatible PDF readers that support Microsoft Information Rights Management services - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@mitanabe Thank you for your feedback. We have added Chromium Edge to the list and the same can be tracked viaPR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3316

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mitanabe Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
