### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by SabRom** [MicrosoftDocs/microsoft-365-docs#3294]
Hello,

This page seems outdated as those menus were replaced by the microsoft endpoint manager admin center.

I can't find a GUI feature to assign an autopilot profile to a new, csv imported device.

Regards,

Romain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74814ff4-77e8-71eb-e78a-fa90cdc37c2c
* Version Independent ID: 55e188f7-4368-6d6a-c567-41347098d66b
* Content: [Use the step-by-step guide to add Autopilot devices and profile - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/add-autopilot-devices-and-profile?view=o365-worldwide)
* Content Source: [microsoft-365/business/add-autopilot-devices-and-profile.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/add-autopilot-devices-and-profile.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@SabRom Thank you for your feedback. We have made changes to the document and the same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3352. Note that once the changes are approved by the author it takes 48 hours for the document to go live.

Thanks
Sri

**Comment by msbemba** [comment]
@SabRom  The particular topic is for the autopilot experience within Microsoft 365 Business Premium admin center. The options are still available.

Hope this helps! 

@yogkumgit Please close the issue as there are no changes required.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SabRom Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
