### ISSUE TITLE
Подключение к сети

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/microsoft-365-docs#3296]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e748ed-63fe-0d00-6b60-c1a778797afa
* Version Independent ID: 3cd66c90-ed09-7c28-7dbb-0a11769f8033
* Content: [Network connectivity in the Microsoft 365 Admin Center (preview) - Microsoft 365 Enterprise](https://docs.microsoft.com/en-US/microsoft-365/enterprise/office-365-network-mac-perf-overview?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/office-365-network-mac-perf-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/office-365-network-mac-perf-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@matuhinal Please add the description in English. Thanks

**Comment by yogkumgit** [comment]
@matuhinal We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
