### ISSUE TITLE
Last link on page is broken -Monitor for breaches of personal data.

### ISSUE THREAD

**Issue by gemmadev** [MicrosoftDocs/microsoft-365-docs#3301]
the following link at bottom of page brings you to 404 page 
Monitor for breaches of personal data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32fd9ddd-5a5d-ab6a-b999-540a8f84614f
* Version Independent ID: d4bbbd4b-99d3-d7b5-e4b8-0ef63421bae2
* Content: [Overview of Office 365 Information Protection for GDPR - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-info-protection-for-gdpr-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/office-365-info-protection-for-gdpr-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-info-protection-for-gdpr-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@gemmadev Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3313

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gemmadev Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
