### ISSUE TITLE
Clarity: Add-UnifiedGroupLinks

### ISSUE THREAD

**Issue by L1ttl3J1m** [MicrosoftDocs/microsoft-365-docs#3303]
Add-UnifiedGroupLinks |  Add hundreds or thousands of users

What about if I only want to add a dozen or so? Is it a different command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8db9afe-21ec-9ab9-12ef-14decd05c84b
* Version Independent ID: 5ccc9689-83e2-c090-6a13-4472c5476dbc
* Content: [Manage Microsoft 365 Groups with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@L1ttl3J1m Thank you for your feedback. We have changed the description to reflect that this cmdlet is used to add members, owners, and subscribers to an existing  Microsoft 365 Group.

This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3314

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @L1ttl3J1m Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
