### ISSUE TITLE
Missing Microsoft 365 usage analytics tile on https://admin.microsoft.com/Adminportal/Home?#/reportsUsage

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/microsoft-365-docs#3305]
Hi,
On https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics-errors?view=o365-worldwide#:~:text=To%20fix%20this%20error%3A%20Go,connecting%20to%20the%20template%20app. you explain how to deal with error code 404. However I can not locate the Microsoft 365 usage analytics tile on https://admin.microsoft.com/Adminportal/Home?#/reportsUsage ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32d4d89d-05e0-b2f8-75af-6014364107f9
* Version Independent ID: 8aa9a383-6b58-c5ff-5661-5fc32ee2b3fe
* Content: [Troubleshooting Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics-errors?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics-errors.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics-errors.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@gvggvg Thank you for your feedback. The usage analytics tile is on the bottom right corner of the usage page under reports

![image](https://user-images.githubusercontent.com/45987684/98044595-24952000-1e4d-11eb-93e0-4ffb9e8014bd.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @gvggvg Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
