### ISSUE TITLE
Automate Event Generation

### ISSUE THREAD

**Issue by bloodytourists** [MicrosoftDocs/microsoft-365-docs#3306]
Could you please provide more information on how you can automate Event Generation using REST APIs over HTTPS for companies which are using MFA (as Basic Auth will not work). Also, provide permissions required to generate events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad33cc1-dc5f-d9f9-ee8e-b103839945ef
* Version Independent ID: 1bc3101d-afe8-2056-3cda-6a86a209c460
* Content: [Start retention when an event occurs - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
After checking with engineering, I'm told we support basic auth only at the moment but looking at integrating with MS Graph in the future. It would be very helpful to raise this request by submitting it to UserVoice - this category: https://office365.uservoice.com/forums/289138-office-365-security-compliance?category_id=379531

The permissions required to use the REST APIs are the same as manually creating an event using the UI - for example, you can use Compliance Administrator.
