### ISSUE TITLE
Typo - mult-geo spelt wrong

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#3307]
I have noticed a type in the following paragraph of text ( mult-geo is spelt wrong)
Read User experience in a mult-geo environment for details about your end users' experience in a multi-geo environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f648e8f-a784-82d1-9495-f470330014ca
* Version Independent ID: 01a84ed4-7193-093a-5926-1c91ca078693
* Content: [Plan for Microsoft 365 Multi-Geo - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/plan-for-multi-geo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/plan-for-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/plan-for-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
