### ISSUE TITLE
Doubled information and unclear statement

### ISSUE THREAD

**Issue by pbnet** [MicrosoftDocs/microsoft-365-docs#3308]
[Enter feedback here]

Duplicate lines:

https://docs.microsoft.com/en-us/microsoft-365/enterprise/ipv6-support?view=o365-worldwide#sharepoint-online-and-ipv6

_Office 365 Government G1/G3/G4/K1 If the program that you use to connect to SharePoint Online supports IPv6, it will attempt to use IPv6 by default._ is listed twice

If a company's DNS server is just forwarding requests to Google's DNS or Cloudflare DNS, what's the point on having CIDR notated IP addresses for your organization's DNS infrastructure sent to Microsoft?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41916ef7-635a-80f9-914a-207040a3829e
* Version Independent ID: 1f372ebc-774b-a1f5-5e43-73b42f74b198
* Content: [IPv6 support in Office 365 services - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/ipv6-support?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/ipv6-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/ipv6-support.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by LauraWi** [comment]
Updates queued/
