### ISSUE TITLE
"Convert a user's mailbox in a hybrid environment" is outdated 

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#3309]
The guidance listed in the section "Convert a user's mailbox in a hybrid environment" is outdated. Specifically the entire section is no longer accurate. Since October 11th, 2018, Exchange Hybrid now supports creating remote shared mailboxes starting in Cumulative Update 21 for Exchange Server 2013 and Cumulative Update 10 for Exchange Server 2016 in an on-premises Exchange Server environment, you can directly create or modify a remote shared mailbox by using the new parameter -shared 
•	Enable-RemoteMailbox: [-Identity user] [-Shared] [-RemoteRoutingAddress user@domain]
•	New-RemoteMailbox: [-Shared] [-Name remoteMailboxName]
•	Set-RemoteMailbox: [-Name user] [-Type Shared] 

I recommend changing that section to reference the syntax above and or reference this article here: https://support.microsoft.com/en-us/help/4133605/cmdlets-to-create-modify-remote-shared-mailbox-in-on-premises-exchange

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b3fbbe-fde3-fd52-f9cd-d8fca56a1494
* Version Independent ID: 73d71ee8-579d-78b5-a8cd-48d7ec51ebb8
* Content: [Convert a user mailbox to a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide#convert-a-users-mailbox-in-a-hybrid-environment)
* Content Source: [microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@itguysocal Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3353

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @itguysocal Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
