### ISSUE TITLE
Entitlements for SCCM based on Intune in Microsoft 365 Business

### ISSUE THREAD

**Issue by dmo-tf** [MicrosoftDocs/microsoft-365-docs#332]
The current FAQ does not address if the Intune entitlement included in Microsoft 365 Business allows the user to benefit from SCCM as well. It has been the case that Intune licenses included SCCM usage rights for deployment purposes, but none of this is clearly mentioned in the FAQ.

What is the current status and can this be clarified?

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@dmo-tf - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by dmo-tf** [comment]
The link where the information was expected is [here](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs), it does have a `Does Microsoft 365 Business include the full capabilities of Microsoft Intune?` section, in which the answer to the question was expected, but the keyword `SCCM` is not mentioned in the document even once.

Somewhat confusingly, the answer to the question is present [here](https://docs.microsoft.com/en-us/sccm/core/understand/product-and-licensing-faq), (in a FAQ about SCCM), which confirms SCCM is indeed included under `I have purchased EMS or Microsoft 365 through a Cloud Solution Provider (CSP), do I have rights to use Configuration Manager?`.

It seems considerably more intuitive for a user to begin their query from `What does Microsoft 365 Business include...` when looking to answer licensing questions and end up on the `Microsoft 365 Business` FAQ than the other way around, however, thus including this in the Microsoft 365 Business FAQ / Documentation would be beneficial.

**Comment by mypil** [comment]
@dmo-tf - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
