### ISSUE TITLE
May need to update IP range.

### ISSUE THREAD

**Issue by spuninst** [MicrosoftDocs/microsoft-365-docs#3321]
[Enter feedback here]
I'm receiving traffic from outside 52.96.0.0/14 but within 52.96.0.0/12.
IP address: 52.98.77.213

should we update the documentation? thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
@spuninst The address 52.98.77.213 is within the 52.96.0.0/14 range, which includes 52.96.0.0 - 52.99.255.255. Thanks for your question.

**Comment by spuninst** [comment]
Awesome thank you.
