### ISSUE TITLE
Clarity on who needs to be licensed for SPO and ODfB

### ISSUE THREAD

**Issue by scottyv** [MicrosoftDocs/microsoft-365-docs#3323]
Can the portion of this page that refers to only one DEP for SPO/ODfB/Teams, be updated to reflect that any users that need to access any SPO site, ODfB or Teams needs to be licensed for Customer Key?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a585eca1-dad6-3afd-43ce-8c4b11102dd3
* Version Independent ID: a1d708a7-774f-0c23-b428-28919ef5d46a
* Content: [Service encryption with Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-overview?view=o365-worldwide#about-the-data-encryption-policy-dep)
* Content Source: [microsoft-365/compliance/customer-key-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@scottyv Thank you for your feedback. We have added a line to the paragraph saying that all accounts need to have the appropriate licenses to assign DEP. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3347

Thanks
Sri

**Comment by msbemba** [comment]
@scottyv We have got a confirmation that the users don't need to have licenses for Customer key (individually) and DEP is assigned on a Site level.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @scottyv Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
