### ISSUE TITLE
 my domen 

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/microsoft-365-docs#3324]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf8d18e-b7d0-1f46-ac91-9f4ccc0ff25f
* Version Independent ID: cc2f1946-8911-c82f-81ae-aeae7f81ec92
* Content: [DNS basics - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/get-help-with-domains/dns-basics?WT.mc_id=365AdminCSH&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/dns-basics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/dns-basics.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@matuhinal Thank you for your feedback. I reviewed the document and could not find anything incorrect or needs modification. DNS records help the Internet send emails to the right place so let us know how we can help you modify or explain this document?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @matuhinal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
