### ISSUE TITLE
Подключение

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/microsoft-365-docs#3325]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf8d18e-b7d0-1f46-ac91-9f4ccc0ff25f
* Version Independent ID: cc2f1946-8911-c82f-81ae-aeae7f81ec92
* Content: [DNS basics - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/get-help-with-domains/dns-basics?WT.mc_id=365AdminCSH&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/dns-basics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/dns-basics.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by yogkumgit** [comment]
@matuhinal Please describe your feedback in English. Thanks.
