### ISSUE TITLE
WDATP

### ISSUE THREAD

**Issue by dougyoda** [MicrosoftDocs/microsoft-365-docs#3327]
WDATP is what exactly? I'm assuming it means Windows Defender for ATP, but that term is long gone. I find numerous assumed acronyms in Microsoft Docs that are confusing to the reader. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58031ac6-a7d2-59ac-59c1-b3e03fbc8f13
* Version Independent ID: 82c2a515-4f33-1771-a175-4ed7d9d31276
* Content: [Use Microsoft Defender for Office 365 together with Microsoft Defender for Endpoint - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@dougeby Thank you for your feedback. The Term WDATP is now Microsoft Defender ATP (MDATP). The references on this document reflect the same. 

Hope that helps!

@yogkumgit There are no changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dougyoda Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by l-ip** [comment]
> 
> 
> WDATP is what exactly? I'm assuming it means Windows Defender for ATP, but that term is long gone. I find numerous assumed acronyms in Microsoft Docs that are confusing to the reader. 
> 
> 
> 
> 
> 
> ---
> 
> #### Document Details
> 
> 
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> 
> 
> * ID: 58031ac6-a7d2-59ac-59c1-b3e03fbc8f13
> 
> * Version Independent ID: 82c2a515-4f33-1771-a175-4ed7d9d31276
> 
> * Content: [Use Microsoft Defender for Office 365 together with Microsoft Defender for Endpoint - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp?view=o365-worldwide)
> 
> * Content Source: [microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md)
> 
> * Service: **o365-seccomp**
> 
> * GitHub Login: @denisebmsft
> 
> * Microsoft Alias: **deniseb**
