### ISSUE TITLE
Flow chart is illegible

### ISSUE THREAD

**Issue by bryhall** [MicrosoftDocs/microsoft-365-docs#3332]
The flow chart near the end of the article is too small to read, and no link to the full size diagram is directly available.  It might be available through a linked article, but I believe it is more beneficial to provide the direct link to the image from this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide#how-microsoft-365-utilizes-authenticated-received-chain-arc)
* Content Source: [microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@johanfreelancer9 I have the image source in the media file., Could you please help me to click and make it open in a new tab so customers can enlarge it?

**Comment by bryhall** [comment]
I can confirm that it is now clickable and links to the full size image.  Thank you!

**Comment by msbemba** [comment]
Thank you for the confirmation @bryhall
