### ISSUE TITLE
Header string documentation for focused inbox needs the header string in text in addition to screenshot.

### ISSUE THREAD

**Issue by bobfrankly** [MicrosoftDocs/microsoft-365-docs#3333]
https://docs.microsoft.com/en-us/microsoft-365/admin/setup/configure-focused-inbox?view=o365-worldwide#use-the-ui-to-create-a-transport-rule-to-direct-email-messages-to-the-focused-view-for-all-your-users

Please document the header string properly, instead of in a small blurry screenshot where we can't copy/paste it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a29483-a070-ccc1-b064-176dfa49d5e9
* Version Independent ID: bad082c0-9ca2-0ade-6b1f-0ba5ac26017b
* Content: [Configure Focused Inbox for everyone in your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/configure-focused-inbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/configure-focused-inbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/configure-focused-inbox.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by kwekuako** [comment]
Hi @bobfrankly can you clarify? Do you mean the "set message header" part? Put the text in the doc as well as the screenshot?

**Comment by bobfrankly** [comment]
@kwekuako  Exactly. Similarly to the powershell code blocks above and below, in a form that makes copy/paste an optional alternative to the screen cap. The screen cap is useful as a point of reference, but when dealing with "use this string exactly" scenarios, every admin appreciates copy/paste.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@kwekuako  fixed and updated by adding a note in the topic calling out what the message header value text is. closing.
