### ISSUE TITLE
Managing External Domain spoofing

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/microsoft-365-docs#3335]
Under the section for legitimate External domain spoofing you mention this scenario:

The sender is on a mailing list (also known as a discussion list), and the mailing list relays email from the original sender to all the participants on the mailing list.

Are there any examples on how to remedy issues with this? If there are many members of the discussion list, that's a lot of individual "allow to spoof" toggles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c0cbdb-062e-08e1-7c7c-cedab550f01b
* Version Independent ID: 2791a840-3284-bc0d-7b9e-026b852797e6
* Content: [Configure spoof intelligence - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/learn-about-spoof-intelligence?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MarcLaf, the other option is to [use PowerShell](https://docs.microsoft.com/microsoft-365/security/office-365-security/learn-about-spoof-intelligence#use-powershell-to-manage-spoofed-senders). The important information is in a CSV file.

**Comment by MarcLaf** [comment]
Right I see that option but again, that's a lot of manual combing through and adding to the allow list. Was just looking for an alternate solution or suggestions on how to deal with it.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @MarcLaf If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
