### ISSUE TITLE
Incorrect Licensing instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3338]
When I try to enable Syntex, i see SharePoint Syntex and the apps are Common data services for SP Syntex, SharePoint Syntex, and SharePOint Syntex - SPO type. I think that the documentation needs to be updated to reflect the actual name instead of the code names
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding?view=o365-worldwide)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by MikePlumleyMSFT** [comment]
@DeanGross @yogkumgit  The article has been updated to show the latest experience.
