### ISSUE TITLE
Seems to be incorrect steps regarding initial enablement of Cloud App Security

### ISSUE THREAD

**Issue by henryphillipsid** [MicrosoftDocs/microsoft-365-docs#334]
So 1, it would be nice to spell out that only certain subscriptions will even have this option but also, compliance in the new world has its own admin centre, as does security. However the option of manage advanced alerts unless I am missing something is only present by way of the old combined protection.office.com portal. Although I could just bypass these instructions and go to the cloudappsecurity portal but I thought someone should know as a newbie using this to learn could get very confused quickly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296080bc-a98c-1374-ef7a-5b493808ffc6
* Version Independent ID: adf7e122-1d08-c2fa-e95f-2c1b7109150f
* Content: [Protect global administrator accounts in your Microsoft 365 Enterprise test environment](https://docs.microsoft.com/en-us/microsoft-365/enterprise/protect-global-administrator-accounts-microsoft-365-test-environment#feedback)
* Content Source: [microsoft-365/enterprise/protect-global-administrator-accounts-microsoft-365-test-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/protect-global-administrator-accounts-microsoft-365-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by henryphillipsid** [comment]
To be fair I have since considered and the fact that the article heading mentions Microsoft 365, that might be enough subscription wise but the steps still don't match entirely.

**Comment by mypil** [comment]
@henryphillipsid - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.
