### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#3343]
It would be helpful to amend the instructions for creating the DEP policy for SharePoint Online to include the -identity parameter and include this in your stated example to illustrate what value you need to enter, as you are immediately prompted for this value when you run the command as currently listed.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide#complete-tasks-in-azure-key-vault-and-microsoft-fasttrack-for-customer-key)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross  Please add your comment and help us in resolving this issue. Thanks.

**Comment by KCCross** [comment]
Added
