### ISSUE TITLE
What is Facebook Business? 

### ISSUE THREAD

**Issue by new-kirte** [MicrosoftDocs/microsoft-365-docs#3348]
What kind of product is Facebook Business? Is it Facebook or Workplace by Facebook?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d67ad4c-6a94-9d9a-672c-eb29861206ec
* Version Independent ID: 4d4ad232-7a70-21a5-7f84-cfba6d732c25
* Content: [Deploy a connector to archive Facebook Business pages data - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/deploy-facebook-connector?view=o365-worldwide#step-1-create-an-app-in-azure-active-directory)
* Content Source: [microsoft-365/compliance/deploy-facebook-connector.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/deploy-facebook-connector.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@new-kirte I believe Facebook Business and Workplace by Facebook are two different Facebook products. Would suggest you follow up with Facebook. 

https://www.facebook.com/business
https://www.workplace.com/

Microsoft does offer a data connector for each: https://docs.microsoft.com/en-us/microsoft-365/compliance/archiving-third-party-data?view=o365-worldwide#third-party-data-connectors
