### ISSUE TITLE
Wait period to enable the Directory synchronization

### ISSUE THREAD

**Issue by sabarivasanN** [MicrosoftDocs/microsoft-365-docs#3349]
The wait time of 72 hours to enable back the directory sync once disabled is a worse thing. Admin turn off this particularly when they issues on their environment and separate from on-prem but this wait period makes it worse than the exact issue. This wait period should be reduced to the least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3edc072a-e71f-02a2-7974-3b2d4f820b39
* Version Independent ID: f20102f3-a74b-4c46-8ca7-04fdf4ad2886
* Content: [Turn off directory synchronization for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/turn-off-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/turn-off-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/turn-off-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@sabarivasanN Thank you for your feedback. The 72 hours mentioned in the document is the maximum wait time before you can enable Directory synchronization. This at the moment cannot be decreased as other factors contributing to the delay like the number of Cloud accounts in the subscriptions etc. 

Hope this helps!

@yogkumgit  There are no changes required in the document at the moment. Please close the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sabarivasanN Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
