### ISSUE TITLE
Unable to complete unless password writeback has been enabled

### ISSUE THREAD

**Issue by henryphillipsid** [MicrosoftDocs/microsoft-365-docs#335]
No mention for the requirement within this article of Password writeback being required and this does not flow well if going through the identity features page: https://docs.microsoft.com/en-us/microsoft-365/enterprise/m365-enterprise-test-lab-guides#identity as writeback comes after this. So I would either mention or switch up the order or both

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7bd31b7-34a7-82ad-da52-8d6dcfaa7b12
* Version Independent ID: 51b0435d-96fa-917a-6278-187769d0c95c
* Content: [Password reset for your Microsoft 365 test environment](https://docs.microsoft.com/en-us/microsoft-365/enterprise/password-reset-m365-ent-test-environment)
* Content Source: [microsoft-365/enterprise/password-reset-m365-ent-test-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/password-reset-m365-ent-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@henryphillipsid - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@henryphillipsid The content has been corrected to require password writeback before password reset. Thanks for letting us know.

**Comment by Malind19** [comment]
@mypil This has been closed when I was trying to work on.
