### ISSUE TITLE
access URI w/ proxy authentication

### ISSUE THREAD

**Issue by sigurd-de** [MicrosoftDocs/microsoft-365-docs#3350]
If a company has proxy authentication is place it is critical to understand if the URI access is in user or machine context.
Pls. add this information to the listed URIs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@sigurd-de I have passed your suggestion to the product teams who maintain these endpoint lists for their consideration in a future update. Thanks for your suggestion.
