### ISSUE TITLE
Screen Shots

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3354]
I noticed the Data Category in the secure score images, does not contain any values. I am seeing the same thing in my tenant. Is this a known limitation? i.e., should there be a value from Microsoft Information Protection or is this still a future item? The explanation at the top of the page makes it clear that Infrastructure should not have any points, but I'm expecting to see points in the Data category.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a2c77d-f8c2-b663-57a1-1b1ec8565e89
* Version Independent ID: 69cc2b0f-d0d0-d4b1-8cb9-13c246d67e70
* Content: [Assess your security posture through Microsoft Secure Score - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/microsoft-secure-score-improvement-actions?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/microsoft-secure-score-improvement-actions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/microsoft-secure-score-improvement-actions.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by levinec** [comment]
@DeanGross you are correct, there are actually no values for Microsoft Information Protection currently. I'll update the doc today.

**Comment by DeanGross** [comment]
OMG, I have been arguing with the Support team for weeks about this. They were insistent that it was not showing up because of licensing. I was adamant that the docs said it would work. This has caused me to waste a tremendous of time. Do you have timeline for when the Data category score will be usable?
