### ISSUE TITLE
Make clearer the need/benefit to signing in before starting the test

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/microsoft-365-docs#3356]
It is preferable to be signed in to your M365 tenant before starting the test so the results will be uploaded to the tenant and available to the tenant admin. This doc page mentions this only at the end of the first section "Once the tests are completed..." Instead please make it one of the first points that folks should sign in before starting the test.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37aa6426-21fd-53b4-d22c-4c136abdf78d
* Version Independent ID: dbc918f9-6677-9003-4884-7a824ee07224
* Content: [Microsoft 365 network connectivity test tool (preview) - Microsoft 365 Enterprise](https://docs.microsoft.com/en-CA/microsoft-365/enterprise/office-365-network-mac-perf-onboarding-tool?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/office-365-network-mac-perf-onboarding-tool.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/office-365-network-mac-perf-onboarding-tool.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@softwarecraft Thank you for your feedback. We have added a note to the document to log in before running the tests. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3439

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @softwarecraft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
