### ISSUE TITLE
How long does it take to enable the feature? Permissions not clear

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#3358]
How long does it normally take to enable sensitivity labels for SharePoint and OneDrive?
My Global Admin went to the compliance portal, saw the "yellow box" on the information protection tab (which I did not see as Compliance Administrator) and clicked "turn on now".
Immediately the yellow notification disappeared, but still we see the notice "first complete these steps to enable the feature."
Does this take a while? (Documentation suggests it's immediate). Am I missing something?

It is stated that "If you aren't signing in as a global admin, see Permissions required to create and manage sensitivity labels."
That reference lists Security Admin, Compliance Admin and Compliance Data Admin. But these roles don't cut the cake. As described above, we needed to use Global Admin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please add your comment and help us in resolving this issue. Thanks.

**Comment by cabailey** [comment]
Same issue as https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3357 - resolved
