### ISSUE TITLE
Additional Retention Policy for Yammer

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/microsoft-365-docs#3360]
"To retain and delete **email messages for your Yammer network**, configure an additional retention policy that includes any Microsoft 365 groups that are used for Yammer, by using the Microsoft 365 Groups location."

Can you please describe what these "email messages for your Yammer network" means here?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef663fdc-1776-3c73-7743-332796c284e6
* Version Independent ID: ceb29788-39be-8c30-b92a-7a22243ebe83
* Content: [Create and configure retention policies to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
For example, notification emails that contain requests to join a Yammer network or posts that get sent to your inbox.
