### ISSUE TITLE
Usage reports page missing dropdown

### ISSUE THREAD

**Issue by naps1saps** [MicrosoftDocs/microsoft-365-docs#3368]
> How to get to the mailbox usage report
>    In the admin center, go to the Reports > Usage page.
>    From the Select a report drop-down, select Exchange > Mailbox usage.

The dropdown is missing in 365 admin center since several months ago.  I believe there was a UI update.  Please update documentation for viewing mailbox usage reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e612a4e4-d051-27a7-e54a-bb1ac3fe0849
* Version Independent ID: 653be32f-e4e8-8a72-98b3-a629238ecbd5
* Content: [Microsoft 365 Reports in the admin center - Mailbox usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/mailbox-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/mailbox-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@naps1saps Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3440

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @naps1saps Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
