### ISSUE TITLE
Missing information or link

### ISSUE THREAD

**Issue by Astartes74** [MicrosoftDocs/microsoft-365-docs#3372]
Team, why does this page not link to information about the cost of adding additional storage to SharePoint?  This is fundamental to what the page is discussing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Astartes74 Thank you for your feedback. This page is accessed globally and the price differs for every region. If the Admin navigates as per the steps provided in the document, they will be able to view the exact price for their tenant/region.

Hope this helps!

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri
