### ISSUE TITLE
Admin consent - Replace Connect-AzureAD  with Connect-AzAccount

### ISSUE THREAD

**Issue by uhoefner** [MicrosoftDocs/microsoft-365-docs#3374]
Within the admin consent it seems that the command 'Connect-AzureAD' needs to be replaced with 'Connect-AzAccount'

---
Connect-AzureAD 
$appId="bcf62038-e005-436d-b970-2a472f8c1982" 
$sp=Get-AzADServicePrincipal -ServicePrincipalName $appId
if ($sp -eq $null) { New-AzADServicePrincipal -ApplicationId $appId }
Start-Process  "https://login.microsoftonline.com/common/adminconsent?client_id=$appId"
---

Thanks + Best regards
Uwe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide#prerequisites)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@uhoefner Thank you for your feedback. I have made changes to the document and is under review. Once this is approved by the author the changes will be live in 24-48 hours.

The PR can be tracked via#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3441

Thanks
Sri

**Comment by robmazz** [comment]
@uhoefner and @msbemba - thanks for the feedback, associated PR merged with update.
