### ISSUE TITLE
What will happen, if a matching Keyword removed from Auto labelled document

### ISSUE THREAD

**Issue by Raj-MCITP** [MicrosoftDocs/microsoft-365-docs#3377]
If I remove a matching keyword from a autolabelled document.. will the auto label get removed automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please add your comment and help us in resolving this issue. Thanks.

**Comment by cabailey** [comment]
@Raj-MCITP Thanks for your question!  I've actually got a revision in the works for [this section](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#only-one-retention-label-at-a-time) to help clarify when/if a label can be removed or changed that covers all scenarios.  But in the meantime, I can confirm that after a retention label is applied by an auto-labeling policy, it will never be automatically removed or changed - to do so requires manual intervention by an admin or end user.
