### ISSUE TITLE
zpaq file currupted

### ISSUE THREAD

**Issue by ozs1** [MicrosoftDocs/microsoft-365-docs#338]
the file is not opening

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@ozs1 - Can you please share more details on this issue you are having? May we also know which Microsoft document link you used in reference to this issue? 

Please share it with us so we can investigate further. Thank you.

**Comment by ozs1** [comment]
Modern desktop lab kit the 30gb zip file is not working.  Did not extract well

??? ?? Outlook ???? Android<https://aka.ms/ghei36>

________________________________

**Comment by mypil** [comment]
@ozs1 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
