### ISSUE TITLE
Potential improvement on docs

### ISSUE THREAD

**Issue by peter-stratis** [MicrosoftDocs/microsoft-365-docs#3381]
I'm wondering if... 

b. A message header > includes any of these words > Header name: <CustomHeaderName> Header value: <CustomHeaderValue>.
![image](https://user-images.githubusercontent.com/67962002/98415407-45c35f80-204b-11eb-9569-e3142394a1ab.png)

Should be modified to... 

Modify the message properties >> set a message header >> Set the message header <CustomHeaderName> to the value <CustomHeaderValue>
![image](https://user-images.githubusercontent.com/67962002/98415212-d9486080-204a-11eb-9403-b8298c800cbe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@peter-stratis, OK. Done.

Thanks for the feedback.

Closing
