### ISSUE TITLE
Tenant Allow/Block List link doesn't work

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/microsoft-365-docs#3382]
https://protection.office.com/tenantAllowBlockList doesnt link to anything, and the powershell command is not there.

1. update or remove the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allowed and blocked URLs in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SquirrelAssassin, as it states at the top of the topic:

> [!NOTE]
> The features described in this topic are in Preview, are subject to change, and are not available in all organizations.

If the link doesn't work for you, then you likely aren't part of the Preview.

**Comment by SquirrelAssassin** [comment]
Use a different area of documentation for prod and preview documentation, y’all gotta start thinking more.

**Comment by SquirrelAssassin** [comment]
Let me re iterate a consulting company Microsoft owns created tickets on our side about permissions out side did not give them and wasted life hours.  Use a preview documentation url.  If you don’t have (a site to show) don’t show any site at all. Once it hits google it’s scripture and obviously it already burned real human life hours.  Be responsible for what you show and how you show it.
