### ISSUE TITLE
Outlook Customer Manager has been deprecated.  Please remove the reference to it. 

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/microsoft-365-docs#3384]
Outlook Customer Manager has been deprecated.  Please remove the reference to it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d1bfdf-f250-d2a1-17dc-36a8a305b82a
* Version Independent ID: a8d0892a-dfc9-e115-d77b-a191bf5423fc
* Content: [Migrate from Microsoft 365 Business to Microsoft 365 E3 - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/migrate-from-microsoft-365-business-to-microsoft-365-enterprise?view=o365-worldwide)
* Content Source: [microsoft-365/business/migrate-from-microsoft-365-business-to-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/migrate-from-microsoft-365-business-to-microsoft-365-enterprise.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@dgordonb Thank you for your feedback. We have made changes to the document via PR##https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3432

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dgordonb Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
