### ISSUE TITLE
Outlook Customer Manager has been deprecated.  Please remove the reference to it. 

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/microsoft-365-docs#3385]
Outlook Customer Manager has been deprecated.  Please remove the reference to it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 632c11fa-8975-afd4-a050-7ff42ca3eb33
* Version Independent ID: 2b736015-0f61-4159-e102-77a056f8abec
* Content: [Office 365 Data Subject Requests Under the GDPR and CCPA - Microsoft GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-dsr-office365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/gdpr-dsr-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-dsr-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@dgordonb Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3431

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dgordonb Closing the issue as per the comment in PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
