### ISSUE TITLE
Which Office 365 or Azure features are limited or no longer available in Office 365 region Germany?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#3388]
Hello,

I seek for information in the documentation which Office 365 or Azure features are not available or limited regarding performance/functionalities if you migrate from the EU datacenters to the new Office 365 region Germany (Berlin, Frankfurt).

According to this article from an expert (https://www.rakoellner.de/2020/10/neue-dienste-der-microsoft-kommen-nun-aus-deutschland-und-die-migration-nach-deutschland-ist-nun-moeglich/) there are limitations/unavailable features: see section 'Achtung Umzug – Was bedeutet RZ aus Deutschland' of the linked article.

Please provide information/documentation about this as it's very important to know to make this decision.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1e01d29-0717-798a-c3b6-166653ea6323
* Version Independent ID: 75f13bba-c18a-2d8d-5f1f-83d53ecd8b39
* Content: [During and after your data move - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/during-and-after-your-data-move?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/during-and-after-your-data-move.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/during-and-after-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by yogkumgit** [comment]
@andybergen Please add your comment and help us in resolving this issue. Thanks.

**Comment by andybergen** [comment]
Migration of Office 365 core customer data at rest to Germany is a data residency change for Exchange Online, SharePoint Online, OneDrive for Business, and Teams chat service data.  There is no impact to feature availability as part of the broader global service.

**Comment by GiantCrocodile** [comment]
Hi @andybergen! I appreciate your quick response. Does this mean the mentioned article is wrong, especially the mentioned features which will be unavailable or limited, e. g. no live events? I'm surprised by your statement as the article is quite precise and the author (who's quite known for his Office 365 competence) mentioned somewhere else that there's other stuff to keep in mind that's not listed in that article.

**Comment by andybergen** [comment]
I am not commenting on the article.  I am stating that in migrating customer data we will not cause features to be unavailable.  Note that the committed date for migrations to Germany to complete is spring 2023.

**Comment by GiantCrocodile** [comment]
I see @andybergen. It's a bit difficult now as we have two completely different statements and a tenant core data move can't be cancelled or reverted.

**Comment by yogkumgit** [comment]
@andybergen Please help us here. Thanks

**Comment by msbemba** [comment]
@GiantCrocodile We have a confirmation from the author that I continue to affirm that in migrating M365 core customer data at rest we will not cause features to be unavailable. Note that the committed date for migrations to Germany to complete is spring 2023.  https://aka.ms/move 

CC : @yogkumgit @andybergen 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GiantCrocodile Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
