### ISSUE TITLE
Group Type?

### ISSUE THREAD

**Issue by henryphillipsid** [MicrosoftDocs/microsoft-365-docs#339]
I see a lot of articles just going for O365 as group type but this to me seems far too excessive for some of the use cases, as an O365 group will create a lot of uneccesary resources in most cases and should not be the default choice. Or if you could at least expand on why you think an O365 group would be the best candidate in this instance over others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6a568af-159f-5335-e8c3-33cfbb1e9f54
* Version Independent ID: 9945d19a-4c7f-a96b-2677-f82479f8e326
* Content: [Device compliance policies for your Microsoft 365 Enterprise test environment](https://docs.microsoft.com/en-us/microsoft-365/enterprise/mam-policies-for-your-microsoft-365-enterprise-dev-test-environment)
* Content Source: [microsoft-365/enterprise/mam-policies-for-your-microsoft-365-enterprise-dev-test-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/mam-policies-for-your-microsoft-365-enterprise-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@henryphillipsid - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
@mypil Created PR. I have specified the possibility of using both group types and mentioned the downside of O365 group. 

https://github.com/MicrosoftDocs/microsoft-365-docs/pull/350

**Comment by mypil** [comment]
@henryphillipsid - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
