### ISSUE TITLE
Azure Resource Manager Control & Data Plane & ExpressRoute

### ISSUE THREAD

**Issue by lachlanmd** [MicrosoftDocs/microsoft-365-docs#3391]
Currently, the documentation under the "Microsoft 365 Common and Office Online" subsection lists "management.azure.com", part of ID 59, as not routable by ExpressRoute.

According to [this docs page](https://docs.microsoft.com/en-us/azure/expressroute/expressroute-routing#service-to-bgp-community-value), the BGP community **12076:5070** _can_ route Azure Resource Manager requests, including requests made to both the Azure Control and Data plane (Would also be encompassed by any relevant regional BGP community too).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@lachlanmd I have forwarded this issue to the product team that owns the list that includes row ID 59 for their consideration in a future update. Thanks for letting us know.
