### ISSUE TITLE
Duplicate row 7.2.3

### ISSUE THREAD

**Issue by dennis131** [MicrosoftDocs/microsoft-365-docs#3393]
Determine when consent is to be obtained (7.2.3) row is listed twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac42bb5-3204-4839-6fcb-5a5052a0d9cb
* Version Independent ID: 57cde474-a2e7-fc4b-339d-3e28377ae035
* Content: [Accountability readiness checklist for the GDPR - Microsoft GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-arc-office365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/gdpr-arc-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-arc-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@dennis131 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3434

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dennis131 Hope the comment added by Robert in PR is helpful. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
