### ISSUE TITLE
Enquiries about support option availibility

### ISSUE THREAD

**Issue by prontohostau** [MicrosoftDocs/microsoft-365-docs#3394]
[Could some one check that above statement is still valid. This will be life saving help.
"Microsoft support staff can help provision or deprovision the service and related resources on your tenant" ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7f625c-f3ef-882d-231f-6fef18e14137
* Version Independent ID: 3f335d54-6d65-d49a-e517-2c3a9a95e44d
* Content: [Turn on Microsoft 365 Defender in the Microsoft 365 security center - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/mtp-enable?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/mtp-enable.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/mtp-enable.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by prontohostau** [comment]
Note

Microsoft Defender for Endpoint automatically provisions in European Union (EU) data centers when turned on through Azure Defender. Microsoft 365 Defender will automatically provision in the same EU data center for customers who have provisioned Defender for Endpoint in this manner.

**Comment by msbemba** [comment]
@prontohostau Thank you for your feedback. This is still valid and Microsoft support staff can help provision or de-provision the service and related resources on your tenant. For assistance, select Need help? in the Microsoft 365 security center or the admin center. When contacting support, mention Microsoft 365 Defender.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @prontohostau Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
