### ISSUE TITLE
Link for How Domain Rename Works goes to old version

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/microsoft-365-docs#3397]
Under "Change your Primary Domain", the link for How Domain Rename Works goes to a page with info on Server 2003/2008 with the note: "We're no longer updating this content regularly."
While the "Applies to" section includes 2012, the content makes no references to that version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be15ac4-2297-90eb-57f0-2c3eebfbdd91
* Version Independent ID: 959cf2d6-b6cd-59b9-21e4-dc31e8fba0b9
* Content: [Prepare a non-routable domain for directory synchronization - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@GLComputing Thank you for your feedback. The Server document is not up to date, so the link has been removed via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3442.

The document has detailed steps to change your primary domain from your non routable domain.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GLComputing Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
