### ISSUE TITLE
Another option for third-party servers

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/microsoft-365-docs#3398]
In the section "Set up DKIM so that a third-party service can send, or spoof, email on behalf of your custom domain," another possibility is that the third-party server can have it's own CNAME records with different selectors.

EG:
customdkim._domainkey.domain.com   CNAME   customdkim._domainkey.customserver.com
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#Publish2CNAME)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@GLComputing Thank you for your feedback. We have added that to the description via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3465

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GLComputing Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
