### ISSUE TITLE
Activities on items missing

### ISSUE THREAD

**Issue by arnauvc** [MicrosoftDocs/microsoft-365-docs#3399]
It seems like there're 2 activities missing in the documentation that are already available in Endpoint DLP:

- copy to clipboard
- modify a file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 820cb23f-f33d-241d-5ce2-1d824bcd3747
* Version Independent ID: 36d24f60-27b6-f2c1-ccda-1b49a1d4f073
* Content: [Learn about Microsoft 365 Endpoint data loss prevention (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-learn-about?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@arnauvc Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3443. Once the author approves, these changes will be live in 24 to 48 hours.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per the comment in PR #3443
