### ISSUE TITLE
Non personal data breach

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#340]
Hello, if there is a non-personal data breach - that is there was data breach but leaked data was not personal data but rather other customer data like documents do you follow the same process and the same contact information is used to implement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c02d1823-44c9-a42d-2625-ff3d42e61dc7
* Version Independent ID: 3e5c377d-bcc2-4a59-9e67-02bfeb280f20
* Content: [Office 365 Breach Notification Under the GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-breach-office365#feedback)
* Content Source: [microsoft-365/compliance/gdpr-breach-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-breach-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @herviicban
* Microsoft Alias: **heicba**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Larryngolog - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
@mypil The article is about GDPR and only the personal data are applied under GDPR. Kindly advice.

**Comment by mypil** [comment]
@Malind19 - let's get the inputs from the author @herviicban.

@herviicban - can you please share your insights on how to address this issue? Please advise if a PR needs to be created and what needs to be added so we can have @Malind19 do it. 

Thank you!

**Comment by herviicban** [comment]
Hi @mypil! As there is no personal data breach involved, this is out of scope from GDPR perspectives.  However, as there's information that was leaked, you have to check what company policy this violates to and follow the respective process in place.

**Comment by mypil** [comment]
@Larryngolog - From our understanding, the issue you raised has been answered by @herviicban. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
