### ISSUE TITLE
Please Update This Article on Upgrading Distribution Lists to Office 365 Groups

### ISSUE THREAD

**Issue by eblackbird** [MicrosoftDocs/microsoft-365-docs#3407]
Please Update [This Article](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?redirectSourcePath=%252fen-us%252farticle%252fupgrade-distribution-lists-to-office-365-groups-in-outlook-787d7a75-e201-46f3-a242-f698162ff09f&view=o365-worldwide#which-distribution-lists-cannot-be-upgraded) on Upgrading Distribution Lists to Office 365 Groups

I really appreciate the detail in this article, but I believe it is out of date. I have been trying to upgrade some distribution lists to Office 365 groups, and I have had no success thus far. (Here's my ticket number, in case you're interested: 22464219.) I have been following the guidelines in this article, but it is difficult to troubleshoot when the guidelines I am following are not current. Here are some things I have observed that lead me to believe the article needs to be updated:

1. The article indicates that having the **RecipientTypeDetails** set to anything other than **UserMailbox**, **SharedMailbox**, **TeamMailbox**, or **MailUser** will render a distribution list ineligible for upgrade, but some of my DLs have **RecipientTypeDetails** set to **MailUniversalDistributionGroup** and _are_ eligible for upgrade.

2. The article also states that distribution lists for which **MemberJoinRestriction** and/or **MemberDepartRestriction** is **Closed** will be ineligible. Some of my DLs have these settings set to **Closed** and _are_ eligible for upgrade.

3. The article indicates that adding a user to an Office 365 group will not send a welcome email—that welcome emails are set to "false" by default. My testing has suggested that this is not the case right now. I have tried creating Office 365 groups from scratch and adding test users to them, and those test users receive welcome emails.

I think this article is clearly out of date (even though it was published only four months ago). I would really appreciate an update. This seems to be a well-written collection of information; the information simply does not appear to be current.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb1e873-a684-ba18-21b4-33c2c4cf5aeb
* Version Independent ID: badad26e-0e5e-ab12-f3ae-b6cab759e7b8
* Content: [Upgrade distribution lists to Microsoft 365 Groups in Outlook - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?redirectSourcePath=%252fen-us%252farticle%252fupgrade-distribution-lists-to-office-365-groups-in-outlook-787d7a75-e201-46f3-a242-f698162ff09f&view=o365-worldwide#which-distribution-lists-cannot-be-upgraded)
* Content Source: [microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@eblackbird Thank you for your feedback. 

For 1) It talks about recipient type, So are you able to upgrade DL's that have nested groups in them?
2)I'm testing this and will update the article accordingly.
3)This feature is set to False by default. Can you check get-UnifiedGroup <groupname> |Select UnifiedGroupWelcomeMessageEnabled and check if it is set to False or True ? This setting can be changed using Set-UnifiedGroup <groupname> -UnifiedGroupWelcomeMessageEnabled:$<true/false>

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @eblackbird Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
