### ISSUE TITLE
little ambiguity

### ISSUE THREAD

**Issue by TANSHUAI1993** [MicrosoftDocs/microsoft-365-docs#3408]
Modern Authentication is a method of identity management that offers more secure user authentication and authorization. It's available for Office 365 hybrid deployments of Skype for Business server on-premises and Exchange server on-premises,
Mean is Modern Authentication support Exchange server on-premises. And looks like Azure AD Connect is unnecessary. 
But in General prerequisites part say:

-Your identity configurations are any of the types supported by Azure AD Connect, such as password hash sync, pass-through authentication, and on-premises STS supported by Office 365.

-You have Azure AD Connect configured and functioning for user replication and sync.

Looks like Azure AD Connect is necessary.

My question is :if I don't have azure ad connect and office 365 tenant，just on-premise deployment exchange+ADFS , can we use Modern Authentication?

**Comment by msbemba** [comment]
@TANSHUAI1993 Thank you for your feedback. I don't see a document linked to this question. However, I can answer this for you.

OAuth Can be enabled for Exchange on-premise as well. Only Hybrid Modern auth requires AD to connect and user replication/sync. I'm not able to find a relevant Microsoft document about enabling Oauth on Exchange on-prem servers. But you can enable Oauth and also get technical support from the Microsoft Support team  If need be.

Hope this helps!

Thanks
Sri
