### ISSUE TITLE
Use of "Technical contact" field

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#341]
Article states that "[Global Privacy Contact field] is related to, but distinct from, the existing “Technical Contact” field in AAD". What is the "technical contact" field used for? Does this contact will also receive information about data breach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c02d1823-44c9-a42d-2625-ff3d42e61dc7
* Version Independent ID: 3e5c377d-bcc2-4a59-9e67-02bfeb280f20
* Content: [Office 365 Breach Notification Under the GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-breach-office365#feedback)
* Content Source: [microsoft-365/compliance/gdpr-breach-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-breach-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @herviicban
* Microsoft Alias: **heicba**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Larryngolog - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
@mypil As the article suggests and from what I found, the 'Technical Contact' field also can be configured, but not by default. So, whats specified in the article is having enough clarity. Shall we contact the author as well to verify?

**Comment by mypil** [comment]
@herviicban - can you please share your insights on this issue? 

Thank you.

**Comment by herviicban** [comment]
Hi @mypil! As this is a technical information, you will need to confirm this information with O365 team.  Thanks!

**Comment by msbemba** [comment]
@Larryngolog Thank you for submitting the feedback. The technical contact is the one who will receive communications about Office 365 service status. However, the Technical contact will not be informed about the data breach, Only Global Privacy Contact and the tenant administrator will be notified.
Hope this helps!

Regards
Sriraman MS

**Comment by mypil** [comment]
@Larryngolog - From our understanding, the issue you raised has been answered by Malind19, herviicban and msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by Larryngolog** [comment]
@mypil msbemba has provided the clarification I needed.

**Comment by mypil** [comment]
@officedocsbot close
