### ISSUE TITLE
Security issue 

### ISSUE THREAD

**Issue by FlorentReynal** [MicrosoftDocs/microsoft-365-docs#3412]
[Enter feedback here]
The powershell command ask the user to run powershell -ExecutionPolicy Unrestricted but does not indicate to set it back to its default value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05581e98-a835-1277-3cef-aea6221d9065
* Version Independent ID: e2b54d7d-8f38-5118-ef85-ce9b16da291f
* Content: [Register new devices yourself - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/register-devices-self?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/managed-desktop/get-started/register-devices-self.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/register-devices-self.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@FlorentReynal Thank you for your feedback. We have added a note about the same and it can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3438

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @FlorentReynal Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
