### ISSUE TITLE
Cannot find the same configuration in my test tenants !!

### ISSUE THREAD

**Issue by MGamil-MSFT** [MicrosoftDocs/microsoft-365-docs#3416]
Checked this configuration in 2 of my test tenants and it is totally different from the configuration located in this article!!

Not sure if I need to enable something in my test tenants or this article need to be updated ?

![image](https://user-images.githubusercontent.com/39204008/98820754-425b1a00-2437-11eb-94b6-1fd3747f5dfd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf8d5bc-e77a-5db8-5686-1dcb5a5a96dc
* Version Independent ID: 9e49294a-e1b4-851c-8792-2cdf33927a74
* Content: [Microsoft Productivity Score - Privacy - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/productivity/privacy?view=o365-worldwide#de-identification-of-user-level-metrics)
* Content Source: [microsoft-365/admin/productivity/privacy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/productivity/privacy.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@MGamil-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3484

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit Author has updated the document. We can proceed with closure.

Thanks
Sri
