### ISSUE TITLE
Setting Up Syntex is in "Settings" > "Organizational Knowledge", not Files and Content

### ISSUE THREAD

**Issue by davidsrhans** [MicrosoftDocs/microsoft-365-docs#3417]
the document at this section:

https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding#to-set-up-sharepoint-syntex

should say organisational knowledge, and not Files and Content, when you are about to setup Automate content understanding

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@davidsrhans Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3467. Once the author approves the changes will be live in 48 hours.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @davidsrhans Hope the comment added in PR  is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
