### ISSUE TITLE
Which exactly information is being used to contact tenant admins

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#342]
I'm missing the following information about notifying admins:
- which admin roles get notified (global admins only or other admins from this list https://docs.microsoft.com/en-us/office365/admin/add-users/about-admin-roles?view=o365-worldwide)?
- which contact information is being used for contact? Information from AAD like mail or smtp account attribute or contact information provided by admins on their profile card https://portal.office.com/account/#personalinfo ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c02d1823-44c9-a42d-2625-ff3d42e61dc7
* Version Independent ID: 3e5c377d-bcc2-4a59-9e67-02bfeb280f20
* Content: [Office 365 Breach Notification Under the GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-breach-office365#feedback)
* Content Source: [microsoft-365/compliance/gdpr-breach-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-breach-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @herviicban
* Microsoft Alias: **heicba**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Larryngolog - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Malind19** [comment]
@mypil as per the article, it is clearly mentioned the answers to two questions above as follows. 

1. Tenant administrator gets notified. Additionally the Global Privacy Contact alias is notified via email. So in terms of the administrators, it is the tenant administrator. 
2. Email is the mode use for this communication. So the O365 email address of the tenant administrator and the Global Privacy Contact's will be used. 

Kindly clarify what additional suggestions to add to article.

**Comment by mypil** [comment]
@Larryngolog - From our understanding, the issue you raised has been answered by Malind19. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close

**Comment by Larryngolog** [comment]
Hello.
@Malind19 
1. By "Tenant administrator" do you mean "Global administrator" or any of the administrator roles mentioned in the article I have linked above?
2. By "E-mail" which exactly attribute you have in mind. There are e-mail several attributes for the AAD account and my customers need to know which will be used.

**Comment by MaratMussabekov** [comment]
dear @Larryngolog ,
all the notifications are sent to your organization's contact email. It usually is the alternate email of the person who registered Office 365 tenant. Please check [here](https://docs.microsoft.com/office365/admin/manage/change-address-contact-and-more?view=o365-worldwide) in the "Technical contact" section

[How to change main and alternate email](https://docs.microsoft.com/office365/admin/manage/update-phone-number-and-email-address?view=o365-worldwide)

Thank you
