### ISSUE TITLE
Page is out of date

### ISSUE THREAD

**Issue by jbize** [MicrosoftDocs/microsoft-365-docs#3420]
It's November 2020... will you meet the "December 31, 2017, compliance deadline" for CDI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c79f14a-7b76-26cf-b97d-e8f2a922bb75
* Version Independent ID: e73e89a7-a122-67ce-154f-6cee9d6f41c5
* Content: [US Department of Defense (DoD) Provisional Authorization - Microsoft Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-dod-disa-l2-l4-l5?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/offering-DoD-DISA-L2-L4-L5.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-DoD-DISA-L2-L4-L5.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz  Please add your comment and help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@jbize - thanks for the feedback. This topic is currently under review and in the process of being updated, this section will be changed. Please check back in a few weeks for the most current information. Thanks!
