### ISSUE TITLE
Commonly used Microsoft 365 admin center roles

### ISSUE THREAD

**Issue by Gassela** [MicrosoftDocs/microsoft-365-docs#3444]
This page is not aligned with roles listed in M365 Admin portal.
I refer to page you got clicking on **Manage Roles** option within **Active Users** page.
here you can click on Show all by category section and you see another more complete list grouped by focus area as Collaboration, Identity, Device, etc....

Wouldn't it be appropriate to align this important DOCS page with the contents and logic visible on this M365 admin portal page?

The risk of not doing it consists of creating confusion in our customers.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Gassela Thank you for your feedback. You are correct,  the list only comprises commonly used admin roles. We have added a link to the document which has detailed information, including the cmdlets associated with a role, see Administrator role permissions in Azure Active Directory. - https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#available-roles

Hope this helps!

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Gassela Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
