### ISSUE TITLE
Embedded term "Domain Connect" opens a spam website

### ISSUE THREAD

**Issue by Attreyu** [MicrosoftDocs/microsoft-365-docs#3448]
"Domain Connect" redirects to a spam website - I won't copy paste it here for security reasons.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0012093-49ca-c2f6-a3f3-4e4252fca609
* Version Independent ID: 22784dda-ff03-971b-4d6e-5b0152f62942
* Content: [Add a domain to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/add-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@Attreyu Thank you for your feedback. I have removed the link to the third party site. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3469

Thanks
Sri
