### ISSUE TITLE
Changeing Default Domain name in MS 365

### ISSUE THREAD

**Issue by saeedtalpur** [MicrosoftDocs/microsoft-365-docs#3449]
If I change the default domain name from olddomain.com to newdomain.com will all my organization's email address also change to new domain name?

Thanks

**Comment by denisebmsft** [comment]
Hello @saeedtalpur, and thank you for your question. Can you please tell us to which article(s) this applies? This information will help us route the issue to the correct writer/team. Thanks!

**Comment by msbemba** [comment]
@saeedtalpur Thank you for your feedback. I don't see a document linked to this question. But I think I understand the context. 

The impact of changing the default domain is only for new users that will be added to the tenant. When you add new users, their email addresses and usernames will use this new domain. If a user has multiple email addresses, the default domain is used as their reply-to address. You will still have an option to choose another domain when creating a new user. Just that it will default to this domain.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @saeedtalpur Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
