### ISSUE TITLE
Email sent out using legacy OME emails doesn't get branding applied using OME V1

### ISSUE THREAD

**Issue by raneem634** [MicrosoftDocs/microsoft-365-docs#3453]
[Enter feedback here]

Branding is only for OMEv2. OMEv1 does not support custom branding. It is by design. There was documentation error and we need to update it as soon as possible. Legacy OME does not support branding for the notification mail.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 820a7382-167a-e81f-bc8f-a565d14c662d
* Version Independent ID: 31cb2b1b-e56c-ffa2-e56b-0a19142123d4
* Content: [Legacy information for Office 365 Message Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-information-for-message-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/legacy-information-for-message-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/legacy-information-for-message-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@raneem634 Thank you for your feedback. We have added a line stating that this feature is available in the new OMEV2. this can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3474

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @raneem634 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
