### ISSUE TITLE
Missing standards?

### ISSUE THREAD

**Issue by CarissaB117** [MicrosoftDocs/microsoft-365-docs#3456]
Assessment templates was shared during a training today and ISO 15489 is in the Compliance Center but not in this list. Can you update the list to be an accurate representation of what is in the system?

What role do I need to see the list of templates?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a406f24f-e0c1-9143-9130-ce0459a66235
* Version Independent ID: e040197a-12cc-281a-d75d-16395b24c46f
* Content: [Microsoft Compliance Manager templates list - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-templates-list?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-manager-templates-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-templates-list.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by yogkumgit** [comment]
@chvukosw  Please add your comment and help us in resolving this issue. Thanks.

**Comment by chvukosw** [comment]
Hello, you are correct, ISO 15489 was a recently-added template in Compliance Manager. The templates list page in the documentation (https://docs.microsoft.com/microsoft-365/compliance/compliance-manager-templates-list) will be updated by the end of today. Users holding any role are able to access all templates, both the included templates and premium templates, from the assessment templates page in Compliance Manager. Thank you.
