### ISSUE TITLE
Updated model schedule

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3457]
Can you provide some estimate about when the updated security model can be expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91837ba8-f6f2-3c52-2d89-c8f4c4bce09c
* Version Independent ID: eb3c1fd8-9143-0dc1-77e7-e664ccaefc33
* Content: [Microsoft cloud architecture models - enterprise resource planning](https://docs.microsoft.com/en-us/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/cloud-architecture-models.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/cloud-architecture-models.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by yogkumgit** [comment]
@samanro  Please add your comment and help us in resolving this issue. Thanks.

**Comment by samanro** [comment]
@JoeDavies-MSFT reports that he's shooting for the end of January for an updated model.

**Comment by yogkumgit** [comment]
@samanro Thank you very much for sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
