### ISSUE TITLE
Instructions and description for running target tenant script are not accurate

### ISSUE THREAD

**Issue by GRJ78** [MicrosoftDocs/microsoft-365-docs#3458]
The instructions do not seem to be accurate. You mention that the vault will be created automatically but this is not the case.
The script asks for application id and key vault url. According to your description, these are supposed to be created automatically.

Could you update your description?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#prepare-target-user-objects-for-migration)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@GRJ78 Thank you for your feedback. 

The PS cmdlet is as follows

C:\Users\Admin\scripts\T2TMovesV2> .\SetupCrossTenantRelationshipForTargetTenant.ps1 -ResourceTenantDomain contoso.onmicrosoft.com -ResourceTenantAdminEmail admin@contoso.onmicrosoft.com -TargetTenantDomain fabrikam.onmicrosoft.com -ResourceTenantId ksagjid39-ede2-4d2c-98ae-874709325b00 -SubscriptionId e4ssd05d-a327-49ss-849a-sd0932439023 -ResourceGroup "Cross-TenantMoves" -CertificateName "Contoso-Fabrikam-cert" -CertificateSubject "CN=Contoso_Fabrikam" -AzureAppPermissions Exchange, MSGraph -UseAppAndCertGeneratedForSendingInvitation 


If you don't provide values for these three parameters a new one is created by the script.
 -KeyVaultName 
-KeyVaultAuditStorageAccountName 
-KeyVaultAuditStorageResourceGroup 

If this still doesn't work, please send us a screenshot of the error you are receiving.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GRJ78 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by xaven15** [comment]
ScrA parameter cannot be found that matches parameter name 'MailboxMoveCapability'.
    + CategoryInfo          : InvalidArgument: (:) [New-OrganizationRelationship], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-OrganizationRelationship
    + PSComputerName        : outlook.office365.comipt no longer works on the following:

So I've been plugging away on this for a couple weeks.  I USED to be able to set MAILBOXMOVECAPABILITY but now it is not a valid parameter.  Something has changed.
