### ISSUE TITLE
Incorrect statement of "Microsoft Intune" column in feature area "Conditional access based on device compliance"

### ISSUE THREAD

**Issue by henrywang08** [MicrosoftDocs/microsoft-365-docs#3460]
[Enter feedback here]

The statement of "Microsoft Intune" column in feature area "Conditional access based on device compliance" is incorrect. The statement should be "Yes", since Intune has the capability to support "Conditional access based on device compliance". 

Feature area | Feature highlights | Basic Mobility and Security | Microsoft Intune
-- | -- | -- | --

Conditional access based on device compliance | Prevent noncompliant devices from accessing corporate email and data from the cloud. | Not supported on Windows 10.Limited to controlling access to Exchange Online, SharePoint Online, and Outlook. | No
-- | -- | -- | --

Reference:
Conditional Access is an Azure Active Directory capability that is included with an Azure Active Directory Premium license. Intune enhances this capability by adding mobile device compliance and mobile app management to the solution.
https://docs.microsoft.com/en-us/mem/intune/protect/conditional-access

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd65bdb-26f7-32ec-0e00-0cea0f1dc304
* Version Independent ID: 0ffa2937-a9ed-f59d-d1d7-33a587872003
* Content: [Choose between Basic Mobility and Security and Intune - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/basic-mobility-security/choose-between-basic-mobility-and-security-and-intune?view=o365-worldwide)
* Content Source: [microsoft-365/admin/basic-mobility-security/choose-between-basic-mobility-and-security-and-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/basic-mobility-security/choose-between-basic-mobility-and-security-and-intune.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@henrywang08 Thank you for the feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3475

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @henrywang08 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
