### ISSUE TITLE
"To set up SharePoint Syntex" is different in my tenant

### ISSUE THREAD

**Issue by thomyg** [MicrosoftDocs/microsoft-365-docs#3462]
Point 2 "In the Files and content section, select Automate content understanding." at https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding#to-set-up-sharepoint-syntex looks different in my tenant. There is no "Files and Content" section but this:

![image](https://user-images.githubusercontent.com/10920072/99246815-3344e500-2806-11eb-8f56-0120b16f19cf.png)

From there it's the same. Second small addition, the article doesn't reference the need of licensing users beforehand. Had to google that from a different source. Would be great to have everything in this page though. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding#requirements)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by MikePlumleyMSFT** [comment]
"Files and content" is replacing "Organizational knowledge." The update should be live soon.

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Thank you very much for sharing this explanation. @thomyg Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
