### ISSUE TITLE
Page not found for the CSV file template.

### ISSUE THREAD

**Issue by AlexBlain** [MicrosoftDocs/microsoft-365-docs#347]
it redirects to : https://github.com/MicrosoftDocs/microsoft-365-docs-pr/raw/live/microsoft-365/managed-desktop/get-started/downloads/device-registration-sample-self.xlsx but shows a 404 not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05581e98-a835-1277-3cef-aea6221d9065
* Version Independent ID: e2b54d7d-8f38-5118-ef85-ce9b16da291f
* Content: [Register devices in Microsoft Managed Desktop yourself](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/register-devices-self#feedback)
* Content Source: [microsoft-365/managed-desktop/get-started/register-devices-self.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/register-devices-self.md)
* Product: **w10**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by jaimeo** [comment]
That's very odd--it works fine for me and I believe also worked for James and Jose. I'll investigate further.

**Comment by jaimeo** [comment]
Drat--it works fine for us behind the firewall but not from outside. Which is bizarre. Investigating....

**Comment by jaimeo** [comment]
Fixed! We had a little glitch in the URL format.

**Comment by AlexBlain** [comment]
Yep it is working for now
