### ISSUE TITLE
Request for Links

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3477]
Please add links to the appropriate Insider Risk Management documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d142783e-21ff-8680-45c6-2b77158d89d9
* Version Independent ID: db8175c4-8acd-d8b5-4da7-afbb4a519ecb
* Content: [Key compliance and security considerations for US banking and capital markets](https://docs.microsoft.com/en-us/microsoft-365/solutions/financial-services-secure-collaboration?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/financial-services-secure-collaboration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/financial-services-secure-collaboration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by yogkumgit** [comment]
@msbemba thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
