### ISSUE TITLE
Nothing about using AIP Scanner

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3478]
I would expect this document to mention AIP Scanner as a tool to learn about sensitive information types in on-premises data stores. Is there a reason that it is not mentioned?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63b6844d-dbb1-e9b8-8ce5-35090ce1d89e
* Version Independent ID: 5bbe339f-be21-49d3-6c0b-0c3394aeda20
* Content: [Assess data privacy risks and identify sensitive items with Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/solutions/information-protection-deploy-assess?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/information-protection-deploy-assess.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/information-protection-deploy-assess.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. I have added a note to the document with a reference link to Find what sensitive information you have in files stored on-premises.
This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3565

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
