### ISSUE TITLE
Manually specify emails to ZAP?

### ISSUE THREAD

**Issue by wickid187** [MicrosoftDocs/microsoft-365-docs#3479]
If an email is reported to an admin that it is malicious or contains phishing/spoofed content, is there a way for us to go into our portal and manually kick off ZAP to find the emails that have been inboxed for various mailboxes in the organization and have them ZAP'ed quickly?  

I know when doing analysis in the protection.office.com portal, the tools are there to find Similar Emails, and if we are able to identify one bad email based on user reporting, it would be great to be able to quickly tell Microsoft to look for the message ID, find similar emails and ZAP them quickly.

Is this possible currently, and if not, do you know if there is a roadmap for this to potentially be put into place?

**Comment by msbemba** [comment]
@wickid187 Thank you for your email. There is no automatic way to Zap them as of now.  The best possible way to do this currently is to Search and purge them via content search - https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This is more of a technical query not related to a document. The issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @wickid187 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
