### ISSUE TITLE
EOP w

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/microsoft-365-docs#3482]
From this article is not clear what features will work on a scenario with EOP for on-premises mailboxes.

Mailbox Intelligence it is clear that it will not work as described: "Mailbox intelligence: Enables or disables artificial intelligence (AI) that determines user email patterns with their frequent contacts. This setting helps the AI distinguish between legitimate and spoofed email from those contacts. Mailbox intelligence is only available for Exchange Online mailboxes."

However, the remaining features of impersonation settings (Users to protect, domains to protect, Actions for protected users and emails. safety tips, trusted senders and domains) are not clear.

I've also checked https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/eop-features?view=o365-worldwide and no clarification is found there as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide#impersonation-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rtrigueiro, to be clear the impersonation protection settings in anti-phishing policies are only available in Microsoft Defender for Office 365 (formerly Office 365 Advanced Threat Protection).

It's safe to presume that unless we call it out as not being available, then it's available. The nature of how mailbox intelligence works definitely requires cloud mailboxes. The other features you mentioned do not.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @rtrigueiro Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
