### ISSUE TITLE
Permission to delete policies is being pushed out right now

### ISSUE THREAD

**Issue by bigdpnc** [MicrosoftDocs/microsoft-365-docs#3486]
We opened a case with Microsoft when we found that after creating policies in the communication compliance tool we were not able to delete the policies.  It was original setup to where only the creator of the policy was able to delete the policy.  And this particiulary gave us an issue because the account it logged was different then my upn being captured when I logon to the compliance center.  So Microsoft pushed a change that anyone with access to the compliance center can now delete polices.  I would suggest getting the exact specifications on that and updating the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea1461c-a9db-d934-d5a6-169360842e8b
* Version Independent ID: 6b214386-6f18-9de6-7a8b-b78e69d1387a
* Content: [Communication compliance feature reference - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-feature-reference?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance-feature-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-feature-reference.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@bigdpnc  - thanks for the feedback, this update will be included in the documentation soon. It is in progress with other feature improvements. Thanks!
