### ISSUE TITLE
How long do files stay in quarantine?

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/microsoft-365-docs#3487]
For seciton: Microsoft Defender for Office 365 Only: Use the Security & Compliance Center to manage quarantined files

Please add information on how long the files identified as malicious by ATP for SharePoint, OneDrive, and Microsoft Teams remain in Quarantine. That information is included for emails in quarantine, but not for files. What happens when files expire from quarantine?

Thanks.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an admin - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide#microsoft-defender-for-office-365-only-use-the-security--compliance-center-to-manage-quarantined-files)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@itishnitsa, I'm checking, but in the absence of other information, I would presume 30 days just like email.

**Comment by chrisda** [comment]
@itishnitsa, I'm glad I asked. It's currently 15 days, just like malware. I updated the topic.

Thanks for the feedback.

Closing

**Comment by itishnitsa** [comment]
HI Chris,

Thanks for following up on that. What happends to the file after 15 days? Does it get deleted? Does it stay in locked state indefinetly? If it doesn’t get deleted, and we leave download option available, I assume the user can still download it?

Thanks,
Tanya

**Comment by chrisda** [comment]
Looking into it.

**Comment by chrisda** [comment]
@itishnitsa, this is the response I got:

After 15days, the files are purged out of the database. neither an end user nor Admin will have access to it any longer.
