### ISSUE TITLE
Please add clarity on who this policy applies to

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/microsoft-365-docs#3488]
Please add clarification: If enabled, ATP for SharePoint, OneDrive, and Teams applies to.....
all sites in the tenant? Are there any license enforcement? Are there any license implications when only a portion of users have A5 or A5 security license assigned to them.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d2c56d3-d020-3ca4-c681-0637a8f35a19
* Version Independent ID: eb7eecb7-899b-e282-9d7a-f2a8df36197c
* Content: [ATP for SharePoint, OneDrive, and Microsoft Teams - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-for-spo-odb-and-teams?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/atp-for-spo-odb-and-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-for-spo-odb-and-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@itishnitsa, ATP for SharePoint, OneDrive, and Teams applies to all users with Microsoft Defender for Office 365 (formerly known as Office 365 Advanced Threat Protection) licenses (as part of x5 (x=E,, etc.) or as an add-on subscription).

So yeah, if some of your users have the required licenses and some don't, then there could be issues.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @itishnitsa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
