### ISSUE TITLE
Windows 7-10 Upgrade then cancel M365

### ISSUE THREAD

**Issue by robcondon88** [MicrosoftDocs/microsoft-365-docs#349]
I have several machines that will be upgraded to Win10Pro from Win7Pro by subscribing to Microsoft365 Business. 
What happens to the Windows 10Pro license if we let the subscription expire. Does it become unlicensed? Do we have to roll back to Windows7

**Comment by mypil** [comment]
@robcondon88 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products: **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
