### ISSUE TITLE
email forwarding was somehow disabled on September 2020

### ISSUE THREAD

**Issue by canoas** [MicrosoftDocs/microsoft-365-docs#3490]
email forwarding was somehow disabled on September 2020. this document is incomplete now as we need to do more changes in ECP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by canoas** [comment]
https://docs.microsoft.com/en-us/answers/questions/126453/office-365-outlook-email-issue.html?childToView=128806#comment-128806

**Comment by carlosmiguelsns** [comment]
> https://docs.microsoft.com/en-us/answers/questions/126453/office-365-outlook-email-issue.html?childToView=128806#comment-128806
> 
> default outbound policy in https://protection.office.com/antispam needs to be changed for forwarding to work again.

There may be a case that sometimes this option is not enough.
For the issue about "can't save the "on" state for allowing forwarding to an external address.", it may be related to the server itself. You need to **create a new outbound policy** to fix the issue - it took affect right away.

**Comment by msbemba** [comment]
@canoas Thank you for your feedback. We have added a note to the document about Controlling the auto-forwarding feature via the outbound spam policy. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3530

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @canoas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
