### ISSUE TITLE
Update of workload routing through Azure Peering Services

### ISSUE THREAD

**Issue by alexandreweiss** [MicrosoftDocs/microsoft-365-docs#3493]
Hi team,

I would suggest that we update the doc to also tell customers that a workload can be routed (or not)through our new [Azure Peering Services](https://docs.microsoft.com/en-us/azure/peering-service/about) offer as we are also receiving M365 IPs from the 8075 by this path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@alexandreweiss I have forwarded your suggestion to the product team owners who own the networking story for Office 365 for their consideration. Thanks for letting us know.

**Comment by alexandreweiss** [comment]
Thanks Joe! Have a nice WE.

Sent from my mobile

________________________________
