### ISSUE TITLE
Update to faciliate Information Protect Compatibility

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/microsoft-365-docs#3494]
this document in 3 years old and needs to be updated to reflect Microsoft Information Protection

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da662e1-5ae5-7760-1321-26cd2bab997a
* Version Independent ID: 60319761-1406-6c06-1620-e1a484468879
* Content: [SharePoint-Compatible PDF readers that support Microsoft Information Rights Management services - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sp-compatible-pdf-readers-for-irm.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@robmazz  Please add your comment and help us in resolving this issue. Thanks.

**Comment by robmazz** [comment]
@KCCross  - this is actually your topic, can you take a look?

**Comment by KCCross** [comment]
sure.
