### ISSUE TITLE
Broken md link

### ISSUE THREAD

**Issue by brenle** [MicrosoftDocs/microsoft-365-docs#3495]
In the section "Onboarding devices into device management", last paragraph, the link is broken:

Follow the [With devices onboarded into Microsoft Defender for Endpoint procedure](endpoint-dlp-getting-started.md#with-devices-onboarded-into-microsoft-defender-for- endpoint)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@brenle Thank you for your feedback. It was linking back to the same document. I have removed the reference link via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3518

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @brenle Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
