### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by kevincallanan** [MicrosoftDocs/microsoft-365-docs#3496]
The Linked text "Removing duplicate and unwanted proxy addresses in Exchange." points to an MS article that cannot be loaded and redirects to the main MS Support search site. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b05a56d-f714-2d99-747e-b3150f581f38
* Version Independent ID: e8924d3f-20e7-6ce2-2279-cec010e7d3f3
* Content: [Prepare for directory synchronization to Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-for-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@kevincallanan Thank you for your feedback. Looks like the document does not exist anymore. I have removed the broken link till we get the original document fixed. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3517

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kevincallanan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
