### ISSUE TITLE
Owner7005w

### ISSUE THREAD

**Issue by owner7005** [MicrosoftDocs/microsoft-365-docs#3498]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92d6d38-7da4-341d-7462-b9d6336aad13
* Version Independent ID: 0dd10346-a372-a383-b178-6f3f26301922
* Content: [Set up Microsoft 365 Apps for business - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/setup-apps-for-business?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/setup-apps-for-business.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/setup-apps-for-business.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@owner7005 Thank you for your feedback. Could you please elaborate more on the question/feedback about this document. Please note that this document refers to M365 Apps for business(Office Suite)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @owner7005 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
