### ISSUE TITLE
Disk space requirements on this page are 150GB, are 300GB in actual setup guide

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#3500]
From the 2004 lab setup guide:

> The Windows and Office Deployment Lab Kit is a testing environment based on Windows Server 2019 and Windows 10, Version 2004. It must be imported and created onto a Hyper-V server installed on Windows Server 2012 R2 or Windows Server 2016 or Windows 10. It is recommended to use a Windows Server OS and should be fully updated. The Hyper-V Host must preferably meet the following specifications:
>
> -	Hyper-V role installed
> -	Administrative rights on the host
> -	**300 gigabytes of free disk space or more**
> -	High-throughput disk subsystem
> -	Up to 32 gigabytes of memory
> -	Preferably a High-end processor for faster processing
> -	An External virtual switch in Hyper-V connecting to the external adapter of the host machine for internet connectivity, example External 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide#step-by-step-labs)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@JeremyTBradshaw I have asked the owner of the Windows and Office deployment lab kit download to comment on this issue. Thanks for letting us know.

**Comment by msbemba** [comment]
@JeremyTBradshaw Thank you for your feedback. While 150 GB of free disk space is required, 300 GB is recommended as per the prerequisite. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3531

CC: @JoeDavies-MSFT 

Thanks
Sri

**Comment by JeremyTBradshaw** [comment]
Closing since it's address in @msbemba 's PR.  Thanks!
