### ISSUE TITLE
Confirming accuracy of role required to enable device management

### ISSUE THREAD

**Issue by Jimnar** [MicrosoftDocs/microsoft-365-docs#3501]
Can you confirm this statement below is correct? 

If it is correct, where are these roles assigned? Azure AD, O365 SCC? 

To enable device management, the account you use must be a member of any one of these roles:

Global admin
Security admin
Compliance admin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Jimnar Thank you for your feedback. The Security admin and compliance admin roles are assigned via the O365 Security and compliance center.

I have added the reference link to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3532
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide

Once the author approves, the changes will be live in 24-48 hours.

Thanks
Sri

**Comment by Jimnar** [comment]
Thanks for the update. Also, do you mean Security **Administrator** and Compliance **Administrator** as opposed to Security **Admin** and Compliance **Admin**?

**Comment by msbemba** [comment]
@Jimnar That is correct.

**Comment by Jimnar** [comment]
@msbemba can I confirm you will be adding the "istrator" to the end of Admin to improve the accuracy of the instructions?

**Comment by msbemba** [comment]
@Jimnar  The roles in Azure AD and O365 Admin center show up as admin instead of an administrator. That is the reason why the documents say so. Hope this helps!


![image](https://user-images.githubusercontent.com/45987684/100743790-ce42df00-3402-11eb-912d-863e22cb437f.png)

Thanks
Sri

**Comment by Jimnar** [comment]
@msemba, it does help. Why these roles show up in Azure AD with "admin" and O365 as "administrator" is a mystery to me.

**Comment by msbemba** [comment]
@Jimnar It shows up as Admin in O365 as well. The above Snip is from O365.

@yogkumgit There are no changes required in this document. The issue can be closed.

**Comment by Jimnar** [comment]
@msbemba, sorry for mixing up the place where "admin" and "administrator" are used. I mean to say Azure AD uses "administrator" and O65/M365 uses "admin". Take care.

**Comment by msbemba** [comment]
@Jimnar Thank you for the clarity.  Admin is the acronym for Administrator, there is no difference as such in the roles when you assign it from O365 or AAD.

Hope this helps!
Thanks
Sri
