### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by CyberJR** [MicrosoftDocs/microsoft-365-docs#3502]
The item highlighted in this screenshot should read "Microsoft 365 Compliance"  not Security

![image](https://user-images.githubusercontent.com/74684762/99590831-bdc24b80-29a2-11eb-8253-97b37091911f.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4fd73b-9632-b0c1-45cb-825f2f1a03dd
* Version Independent ID: 8aeca19b-cf40-33c1-b947-f951a58e9520
* Content: [Microsoft 365 network connectivity principles - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-network-connectivity-principles?view=o365-worldwide#comparing-network-perimeter-security-with-endpoint-security)
* Content Source: [microsoft-365/enterprise/microsoft-365-network-connectivity-principles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-network-connectivity-principles.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@CyberJR Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3516. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CyberJR Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
