### ISSUE TITLE
comment to password length

### ISSUE THREAD

**Issue by Raharney** [MicrosoftDocs/microsoft-365-docs#3504]
[I found this point confusing: "Maintain an 8-character minimum length requirement (longer isn't necessarily better)".
I was always of the opinion "longer is better".  Am I wrong?
Or are you making a different point?]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://docs.microsoft.com/en-GB/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide#password-expiration-requirements-for-users?WT.mc_id=365AdminCSH)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Raharney Thank you for your feedback.  Longer is definitely better, but eight to twelve characters can be adequate that uses mixed case and numbers instead of a longer and easy to guess password. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Raharney Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
