### ISSUE TITLE
Cross Tenant Migration

### ISSUE THREAD

**Issue by xaven15** [MicrosoftDocs/microsoft-365-docs#3507]
I have followed to Documentation several times exactly as it says.  Everything verifies.  However I keep receiving the following error no matter what I do:

Error: MigrationPermanentException: Your organization does not authorize 'pull' or Inbound moves from the remote organization. Contact your administrator to confirm organization relationships are configured correctly. --> Your organization does not authorize 'pull' or Inbound moves from the remote organization. Contact your administrator to confirm organization relationships are configured correctly.

PLEASE HELP!!

**Comment by msbemba** [comment]
@xaven15 Thank you for your feedback. Could you please provide us the document that was followed for cross tenant migration?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @xaven15 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
