### ISSUE TITLE
double information

### ISSUE THREAD

**Issue by nataliarozycka** [MicrosoftDocs/microsoft-365-docs#3521]
In "Breakdown of messages by type in Microsoft Teams" section there is duplicate info in point 3. Visualization .

![image](https://user-images.githubusercontent.com/74779149/99810327-dcac1380-2b43-11eb-887c-95e10a4fa135.png)
Second section should be changed to:

People sending channel messages: The colored portion and the fraction represent the use of channel messages within people sending messages on Microsoft Teams. The fraction is constructed from:
Numerator: People who sent channel messages on Microsoft Teams in the last 28 days.
Denominator: People who sent messages on Microsoft Teams in the last 28 days.

Thank you.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 81ee4664-d4a2-025d-6ec6-1f87b0c5864c
* Version Independent ID: 7d3c0489-b5bd-502e-91f5-297231ef430a
* Content: [Microsoft Productivity Score - Communication - Microsoft 365 admin](https://docs.microsoft.com/pl-pl/microsoft-365/admin/productivity/communication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/productivity/communication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/productivity/communication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@nataliarozycka Thank you for the feedback. We have fixed the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3564

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nataliarozycka Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
