### ISSUE TITLE
Missing apostrophe

### ISSUE THREAD

**Issue by gs-spec** [MicrosoftDocs/microsoft-365-docs#3529]
Example of enabling privileged access via PowerShell (Step 2) is missing an apostrophe before "sys2@fabrikamorg.onmicrosoft.com')"

Current line: 
`Enable-ElevatedAccessControl -AdminGroup 'pamapprovers@fabrikam.onmicrosoft.com' -SystemAccounts @('sys1@fabrikamorg.onmicrosoft.com', sys2@fabrikamorg.onmicrosoft.com')`

Should be: 
`Enable-ElevatedAccessControl -AdminGroup 'pamapprovers@fabrikam.onmicrosoft.com' -SystemAccounts @('sys1@fabrikamorg.onmicrosoft.com', 'sys2@fabrikamorg.onmicrosoft.com')`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bf337ec-3242-44b9-328b-7ca6381a2bcf
* Version Independent ID: eda3540f-7049-ad17-a259-7952e5665983
* Content: [Get started with privileged access management - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/privileged-access-management-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/privileged-access-management-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/privileged-access-management-configuration.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@gs-spec Thank you for feedback. We have made the changes to the example on the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3568

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gs-spec Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
