### ISSUE TITLE
documentation which employs acronyms/jargon must define terms

### ISSUE THREAD

**Issue by trcoley** [MicrosoftDocs/microsoft-365-docs#3534]
We arrived at this page from an Office 365 notification with the following title:
"Secure by Default - Honoring EOP/ATP detonation verdicts"

Nowhere in that article was EOP defined.
Nowhere in that article was ATP defined.

After two layers of linking, we arrived at this page where EOP is defined, and ATP can only be inferred.

Please teach new documentation writers to define acronyms and jargon terms without assuming the audience knows their meaning. A footnote is a minimally intrusive solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472b3a0c-7ad8-8245-9b57-29431490370b
* Version Independent ID: 8671f04a-b7b3-402c-1e65-59a52c1cdaf5
* Content: [Secure by default in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-by-default?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/secure-by-default.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-by-default.md)
* Service: **o365-seccomp**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@trcoley Thank you for your feedback. Sorry about the confusion. Microsoft Defender for Office 365 is the new name for Office 365 Advanced Threat Protection. We have now added a note on the document to explicitly mention this change.

Thanks
Sri

**Comment by chrisda** [comment]
@trcoley, I totally agree. Currently, I can find no references to advanced threat protection or ATP within the topic. I made sure the one reference to Microsoft Defender for Office 365 was linked. I also made sure that a link exists for Exchange Online Protection (EOP).

Thanks for the feedback.

Clsoing
