### ISSUE TITLE
Problem with support

### ISSUE THREAD

**Issue by edisoss** [MicrosoftDocs/microsoft-365-docs#3536]
I'm very unhappy about this support because I been calling all weak and they say technician will call back but now calls me back

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda2bd9d-db22-2b5c-4195-7aeb8e28f2d5
* Version Independent ID: 375d5f30-19de-0e2f-63df-dfbbff863b44
* Content: [Support information for Latvia - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/latvia?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/latvia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/latvia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@edisoss Thank you for your feedback Sorry about the issue that you have. We are the documentation team and do not have access to the supporting system(ticketing queue). I'd recommend you opening a ticket via the Need help section on the M365 admin center.

Hope this helps!

@yogkumgit There are no changes in the document. We can close the issue.

Thanks
Sri

**Comment by edisoss** [comment]
And how can i do it if i canot login in admin

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @edisoss Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by edisoss** [comment]
Can you maybe give me headquarters email or phone number where I can tell my issue?

**Comment by msbemba** [comment]
@edisoss Thank you for your feedback. We can help you in modifying the document if there is incorrect information and I have verified that the support number is correct. Unfortunately, we don't have a way to create support tickets. If you are the only admin and you have forgotten your password, then you need to get in touch with the support team on either 1-877-696-7786 or the Latvia number at 8000 42 33 between M-F 9-5 PM. If you another admin who can access the site, you can also have them help you create a ticket via the need help option in the admin center.

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@edisoss I'm sorry you're having so much trouble contacting support for your country. Would you please provide me with the following information so that I can have our internal support team check for issues with the number? Please send this information directly to me at cmcatee@microsoft.com (do not post it here):

- Caller's telephone number
- Support # called
- Date of call
- Time of call with time zone
- IVR options selected, if any
- Call results (description of the caller experience after calling)

Thanks,
Cern

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Thank you very much for your help. @edisoss If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
