### ISSUE TITLE
Update alternate email

### ISSUE THREAD

**Issue by mevenega** [MicrosoftDocs/microsoft-365-docs#3537]
The steps to update alternate email are not accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78b552c1-5a38-2a58-5ef9-3f9f3a324de6
* Version Independent ID: ffd9e488-bb85-365b-0a99-92525189341c
* Content: [Change your organization's address, technical contact, and more - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/change-address-contact-and-more?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/change-address-contact-and-more.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/change-address-contact-and-more.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@mevenega Thank you for your feedback. We have modified the steps to edit the alternate email address. The same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3566


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mevenega Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mevenega** [comment]
Thank you all!



Melina Venegas
SR TECHNICAL ADVISOR | Microsoft 365 Data Protection
mevenega@microsoft.com<mailto:mevenega@microsoft.com>
[Microsoft]

[cid:image002.png@01D6C952.8EF80B10]
How secure is your Office 365 organization? Go to Microsoft 365 Security Documentation<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fsecurity%2F&data=02%7C01%7CMelina.Venegas%40microsoft.com%7C66b502777bf74e6761d408d84589e26c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637335805792181388&sdata=7RgqEq1DRaLuZBq%2FRx8LJvzNsbc1xjpWMyjSVmPM%2Bvc%3D&reserved=0>to learn more!
