### ISSUE TITLE
Page link and questions on Teams vs Skype

### ISSUE THREAD

**Issue by D-Jeffrey** [MicrosoftDocs/microsoft-365-docs#3541]
1) The first link does not work
https://support.office.microsoft.com/article/Gather-the-information-you-need-to-create-Office-365-DNS-records-77f90d4a-dc7f-4f09-8972-c1b03ea85a67

2) The Callout for Skype indicates they Skype records are required, but there is nothing within each records that references Teams.  Does that mean that the Skype DNS records are not used if a customer is in Teams Only Mode?  It is assumed that Or is this required for inter-op compatibility with Webex and other products?

3)Is there a standard Host/Alias for the Office 365 Single Sign-On A record?  This is stuck in the text, but may not have the same context as the other records listed on this page.

Keep up the good work improving the quality of the information.  It does feel like we are getting better information in the last few months.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce215c7-f61f-44c5-43c1-2fa1f2a39220
* Version Independent ID: d65a9513-432a-d0fe-1431-da5ad2e631eb
* Content: [External Domain Name System records for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/external-domain-name-system-records?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/external-domain-name-system-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/external-domain-name-system-records.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
Fixed broken link in PR #11478. The other items in this issue appear to have been resolved by other writers since this issue was created.
