### ISSUE TITLE
Does "fapiao" means invoice ?

### ISSUE THREAD

**Issue by Code2Life** [MicrosoftDocs/microsoft-365-docs#3544]
[Enter feedback here]
Seems like typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7b9f169-db90-943e-afb4-aa90be48acbd
* Version Independent ID: 2336b9a6-8d5f-dc27-2d4d-b42a2df6cdbf
* Content: [View your bill or get a Fapiao in Office 365 operated by 21Vianet - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/services-in-china/view-your-bill-or-get-a-fapiao?view=o365-21vianet)
* Content Source: [microsoft-365/admin/services-in-china/view-your-bill-or-get-a-fapiao.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/services-in-china/view-your-bill-or-get-a-fapiao.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Code2Life Thank you for your feedback. A fapiao is a legal receipt that serves as proof of purchase for goods and services. So this is more like an invoice.

Hope this helps!

@yogkumgit There are no changes required in the document. Please close the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Code2Life Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
