### ISSUE TITLE
Missing 's' in header

### ISSUE THREAD

**Issue by JoffVerby** [MicrosoftDocs/microsoft-365-docs#3553]
Morning! Look like there's an 's' missing at the end of the heading "Learn about other admin role"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d6f9a72-eac8-f9c7-6dc4-85c0b6ef95cd
* Version Independent ID: 453e6941-933f-a499-f745-031594b84dab
* Content: [About the Exchange Online admin role - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-exchange-online-admin-role?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-exchange-online-admin-role.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-exchange-online-admin-role.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@JoffVerby Thank you for your feedback. We have fixed the missing "s" via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3569

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JoffVerby Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
