### ISSUE TITLE
License requirements for shared mailboxes

### ISSUE THREAD

**Issue by donnyatmsft** [MicrosoftDocs/microsoft-365-docs#3554]
In the list you should include also Microsoft Defender for Office 365 if customers wants to protect the shared mailbox with this advanced protection, right? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd8b6d7d-1a95-d263-595e-78649069275f
* Version Independent ID: bacc64b9-916b-bb3d-a885-46fe5d096826
* Content: [Remove license from shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/remove-license-from-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/remove-license-from-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/remove-license-from-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@donnyatmsft Thank you for your feedback. We have added this information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3571

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @donnyatmsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
