### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by donnyatmsft** [MicrosoftDocs/microsoft-365-docs#3555]
Hi prerequisites for Activity and Content Explorer should include also the following two licenses:

- Microsoft 365 E5 Compliance
- Microsoft 365 E5/A5 Info Protection & Governance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334e743d-c929-c74a-c996-2b8e0b68a46b
* Version Independent ID: 91c4563c-72c1-4655-72f7-d467b6098540
* Content: [Get started with content explorer - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-content-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@donnyatmsft Thank you for your feedback. We have added these two licenses to the prerequisites. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3572

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @donnyatmsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
