### ISSUE TITLE
Expiration time for alert activity list

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#3556]
We don't seem to have this documented anywhere. When an alert is triggered, we will also make available a list of messages that matched the alert, list that can be viewed by the customer when selecting the alert in the Alerts dashboard. After 7 days, instead of being able to access the messages that matched the alert, we see "The activities for this alert have expired".

Please confirm with the Engineering team what is the expected behavior and update the article accordingly. The URL would be https://protection.office.com/viewalerts and when you click on a given alert to resolve it for example, you also have the ability to click on "View activity list" on the alert details. This is where after 7 days, we have the message "The activities for this alert have expired" instead "View activity list" on a given alert.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance centers - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Alex-Catalin Please go ahead and update the article with this change and submit a pull request. Thanks.
