### ISSUE TITLE
Restore a team from the Teams app

### ISSUE THREAD

**Issue by JohanssonMarkus** [MicrosoftDocs/microsoft-365-docs#3557]
From this page 
https://docs.microsoft.com/en-us/microsoftteams/archive-or-delete-a-team#restore-a-deleted-team
I'm linked to this page where instruction is saying M365 group should be restored from Outlook. That is Catch22 as all teams are hidden from the Outlook client it's not possible. Please update with instruction on how to restore a deleted team from the Teams application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d49db57-a705-20aa-e98d-5b3d6bbbf9fd
* Version Independent ID: 5a056f2c-03c9-7a34-3196-8bfb1039f6a5
* Content: [Restore a deleted Microsoft 365 group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/restore-deleted-group?view=o365-worldwide&tabs=outlook)
* Content Source: [microsoft-365/admin/create-groups/restore-deleted-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/restore-deleted-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@JohanssonMarkus Thank you for your feedback. The document is updated with two tabs about restoring a group. 1)Restore from outlook 2) Restore from the Admin center. There is no specific way to restore a team from MS Teams directly.

The third method is to restore from the Azure Active Directory, Please refer to https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-restore-deleted

Hope this helps!

Thanks
Sri

**Comment by JohanssonMarkus** [comment]
I see, but then please take into consideration to have this built into the Teams client. Nothing else make sense right?

**Comment by msbemba** [comment]
@JohanssonMarkus I hear you. We have a few other users as well who have requested for this change and we have requested for a design change via Uservoice- https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39789685-i-want-to-restore-a-team-from-the-teams-app

You can vote for this design change and will be notified once this is approved and live. Meanwhile, the document will also be updated when the change is in force.

Hope this helps!

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@JohanssonMarkus  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
