### ISSUE TITLE
Ambiguity in wording, and bug when setting passwords to never expire

### ISSUE THREAD

**Issue by RipRapRob** [MicrosoftDocs/microsoft-365-docs#3559]
In the documentation on https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide

`If you don't want users to have to change passwords, select the checkbox next to Set user passwords to expire after a number of days.`

Surely this should be DESELECT the checkbox`?

I've DEselected the checkbox, but new users I created days after deselecting the checkbox still has the setting "PasswordNeverExpires" as FALSE.

Is this a known bug or am I reading the documentation wrong?

**Comment by msbemba** [comment]
@RipRapRob Thank you for your feedback. I'm testing this scenario currently and will let you know. Meanwhile, you can use the cmdlet Set-AzureADUser -ObjectId <user ID> -PasswordPolicies DisablePasswordExpiration for the affected user to disable password expiration.

Thanks
Sri

**Comment by RipRapRob** [comment]
Thank you @msbemba 😊

I've already changed it for the users we've created after we (thought we) disabled the 'password expires' setting, but it would be nice that we didn't have to do it manually each time we add a user.

**Comment by msbemba** [comment]
@RipRapRob Thank you for your feedback. I have made changes to the document stating that we need to uncheck the option to not let the password expire. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3585

Meanwhile, If the option is deselected and you still have a password policy forced, I'd recommend you contact support to fix the bug on your tenant. Let me know how it goes and if you still need any changes in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @RipRapRob Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
