### ISSUE TITLE
Size limit for encrypted messages is not correct in documentations

### ISSUE THREAD

**Issue by mohanse** [MicrosoftDocs/microsoft-365-docs#3561]
[Enter feedback here]
As per this- https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits-across-standalone-options

Size limit for encrypted messages(new OME) for Exchange Online plan 2 is 150 MB.

But as per this - https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits-1

Size limit for encrypted messages(new OME)  in O365 E5 Plan is 25 MB.  But O365 E5 includes Exchange Online Plan 2, so technically the size limit is 150 MB ?

And as per this: https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#is-there-a-size-limit-for-messages-you-can-send-with-ome

Size limit is 30 MB

can you update documentation with the correct size limit for encrypted messages ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@mohanse Thank you for the feedback. We have made changes to the document to reflect the new size limit of 150 MB. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3580

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit We have got a confirmation from @KCCross that this limit is changed to 25 MB by the product group recently. This has been updated in this document accordingly.  This issue can be closed.

Thanks
Sri
