### ISSUE TITLE
This article has not been updated with the new naming scheme for Microsoft Business Basic/Standard/Premium

### ISSUE THREAD

**Issue by AustinBoak** [MicrosoftDocs/microsoft-365-docs#3562]
This article has not been updated with the new naming scheme for Microsoft Business Basic/Standard/Premium. Bookings should be shown as available for Business Standard and Business Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7484dd4-5d94-dd6c-0dbe-551c852677c1
* Version Independent ID: 257d60e2-9313-e08b-dccf-120cb4b30f5b
* Content: [Microsoft Bookings Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/bookings/bookings-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-faq.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@AustinBoak Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3579

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AustinBoak Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
