### ISSUE TITLE
Add link to personal Productivity Score

### ISSUE THREAD

**Issue by madduci** [MicrosoftDocs/microsoft-365-docs#3563]
On the page it's stated that a Microsoft 365 Admin can review Productivty Scores, but there's no mention to user's own Personal Productivity Score link. It should be added, since it's a personal information that **can always be reviewed** from each owner of a Microsoft 365 account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 411cc9ec-3de2-9aaf-00b8-d923d2b02f37
* Version Independent ID: c1a0daec-33a1-eb34-db3d-0b12b78a8aaf
* Content: [Microsoft Productivity Score - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/productivity/productivity-score?view=o365-worldwide)
* Content Source: [microsoft-365/admin/productivity/productivity-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/productivity/productivity-score.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@madduci Thank you for your feedback. Are you referring to the productivity insights that the customers can view on Workplace Analytics?

Thanks
Sri

**Comment by madduci** [comment]
@msbemba thank you for replying. Yes: as a not Microsoft 365 Administrator, but just as a standard Microsoft 365 in an Organization, how can be possible to access those Productivity Insights? There's no mention to it in the documentation.

Thanks

**Comment by msbemba** [comment]
@madduci Thank you. The document pertains more towards how admins can Interpret the Productivity Score. The productivity insights is  a part of workplace analytics and documentation can be found her -https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/dashboard-2

Thanks
Sri

**Comment by madduci** [comment]
@msbemba thank you for your reply and feedback. I guess it would be still relevant to add at the end of the page the link to the productivity insights you've pasted here, so to have a cross-reference.
Thanks

**Comment by msbemba** [comment]
@madduci  Thank you for the feedback. I have added a note at the end of the page via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3589

Once the author approves the PR you will see the changes live on the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @madduci Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
