### ISSUE TITLE
Inform what is the futur mechanism that replaces In-Place Hold

### ISSUE THREAD

**Issue by PhilGude** [MicrosoftDocs/microsoft-365-docs#3567]
Dear Team, 

I was reading the good article "Data resiliency in M365" interested to understand how the continuity offered by the platform mitigate the risks of data loss and disaster recovery. 

Then continued in the page  "Exchange Online Data Resiliency" to see in detail how this is implemented in Exchange I found the point "Store logical corruption" particularly appealing. It is mentioned  "The In-Place Hold features in Exchange Online provides protection from store logical corruption" but if you click on the In-Place Hold link there is this message saying this mechanism is retired. 

I you follow my navigation path, I believe the last article deserve an explanation of what is then the new mechanism for Exchange Resilience otherwise it felt all the efforts created in the main articles are waisted because it is retired..

Hope you see what I mean. 

Have a great day !
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad3e6ca-fbbb-70e3-b7c3-595736cb8bd7
* Version Independent ID: 8870f5ba-b56c-71e3-222a-955fabcce880
* Content: [Exchange Online Data Resiliency in Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-exchange-data-resiliency?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-exchange-data-resiliency.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-exchange-data-resiliency.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@PhilGude Thank you for the feedback. This is a very important point that you bring in, I have added an important note to the document about the same and can be tracked via PR#https://github.com/MicrosoftDocs/Compliance/pull/5

You can view more information about this on Retirement of legacy eDiscovery tools and how 
 this is handled now https://docs.microsoft.com/microsoft-365/compliance/legacy-ediscovery-retirement

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PhilGude Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
