### ISSUE TITLE
Old material

### ISSUE THREAD

**Issue by DiavoloRosso** [MicrosoftDocs/microsoft-365-docs#3574]
Old video with very very old platform.
Usefull with new login page and offic.com experience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0557523-00aa-de0f-5904-36ade8ac0d0d
* Version Independent ID: 6730d75d-fa65-b8df-5922-3b887c31cd4a
* Content: [Get started with Microsoft 365 for business - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/get-started-with-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/admin/admin-overview/get-started-with-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/get-started-with-office-365.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by yogkumgit** [comment]
@twernermsft Please update and add a comment to resolve this issue. Thanks

**Comment by lhcole** [comment]
@DiavoloRosso Thanks for reaching out. Would you give me a few more details about your request? Are you asking that I remove a specific link from the Get started page? Can you identify which one should be removed?

**Comment by yogkumgit** [comment]
@lhcole Thank you very much for the contribution and digging deep into it.  @DiavoloRosso We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
