### ISSUE TITLE
Possible to add details on how to change languages settings in Admin mobile app ? 

### ISSUE THREAD

**Issue by gemmadev** [MicrosoftDocs/microsoft-365-docs#3575]
Hi there, 

Suggestion to add steps on how to change  language settings in Admin Mobile app
Non English users may  not be aware on how to change language settings. 

Thinking maybe of adding it to this section on the page ? 

What languages are supported by the app?
The app supports all 39 languages that the web-based Microsoft 365 admin center supports.

thx
Gemma

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce65739-6428-fc57-012c-a6741a051c6b
* Version Independent ID: 3341ac81-3e21-4e71-e4f7-3eff41db05b8
* Content: [About the Microsoft 365 Admin mobile app - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-mobile-app?view=o365-worldwide)
* Content Source: [microsoft-365/admin/admin-overview/admin-mobile-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-mobile-app.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@gemmadev Thank you for your feedback. We have added the steps to the FAQ section via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3646

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gemmadev Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
