### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by AJRus** [MicrosoftDocs/microsoft-365-docs#3578]
Basic auth on exchange online has been depreciated, this script is out of date.  get-compliancecase is not a valid cmdlet with the powershell module exchangeonlinemanagement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b759021-39d7-0383-2f50-b5b813217f97
* Version Independent ID: 5f5dfeab-1160-3994-2cb8-1ca7c67e3ff2
* Content: [Use a script to add users to a hold in a Core eDiscovery case in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@AJRus To use modern auth in the script, you can replace these lines:

# Get user credentials &amp; Connect to Office 365 SCC, SPO
$credentials = Get-Credential -Message "Specify your credentials to connect to the Security & Compliance Center and SharePoint Online"
$s = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://ps.compliance.protection.outlook.com/powershell-liveid" -Credential $credentials -Authentication Basic -AllowRedirection -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck)
$a = Import-PSSession $s -AllowClobber
    if (!$s)
    {
        Write-Error "Couldn't create PowerShell session."
        return;
    }

with these lines:

# Connect to SCC PowerShell using modern authentication

if (!$SccSession)
{
   Import-Module ExchangeOnlineManagement
   Connect-IPPSSession
}

# Get user credentials to connect to SPO

$credentials = Get-Credential -Message "Type your credentials again to connect to SharePoint Online Management Shell"


I will update the script in the topic accordingly.  Thanks for the heads up.

**Comment by markjjo** [comment]
sorry, previous post include git formatting. should be (github escape characters added)

replace this:

\# Get user credentials &amp; Connect to Office 365 SCC, SPO
$credentials = Get-Credential -Message "Specify your credentials to connect to the Security & Compliance Center and SharePoint Online"
$s = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://ps.compliance.protection.outlook.com/powershell-liveid" -Credential $credentials -Authentication Basic -AllowRedirection -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck)
$a = Import-PSSession $s -AllowClobber
    if (!$s)
    {
        Write-Error "Couldn't create PowerShell session."
        return;
    }

with this

\# Connect to SCC PowerShell using modern authentication

if (!$SccSession)
{
   Import-Module ExchangeOnlineManagement
   Connect-IPPSSession
}

\# Get user credentials to connect to SPO

$credentials = Get-Credential -Message "Type your credentials again to connect to SharePoint Online Management Shell"
