### ISSUE TITLE
Powershell issue

### ISSUE THREAD

**Issue by pbox** [MicrosoftDocs/microsoft-365-docs#3581]
There's an issue in the powershell code under "To view the list of all user accounts in your organization that have been assigned any of your licensing plans (licensed users), run the following command:"

The wrong code starts with :

> Get-AzureAdUser | ForEach { $licensed=$True ; 

however $licensed should be initialized with $false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde00c3a-d106-76a1-1dc4-ad2306497187
* Version Independent ID: 27e87ec9-9ff3-333f-32fe-b45a4ee3d3fb
* Content: [View licensed and unlicensed Microsoft 365 users with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-licensed-and-unlicensed-users-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-licensed-and-unlicensed-users-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-licensed-and-unlicensed-users-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@pbox Thank you for your feedback. Per the document, you would make the below changes in the cmdlets

To view the list of all user accounts in your organization that have NOT been assigned any of your licensing plans (unlicensed users), you use $licensed=$False

To view the list of all user accounts in your organization that have been assigned any of your licensing plans (licensed users), you use $licensed=$True

So, I don't think any changes are required. Hope this clarifies your question. 

Thanks
Sri

**Comment by pbox** [comment]
I understand what your saying, but the point of that code is to "To view the list of all user accounts in your organization that have been assigned any of your licensing plans (licensed users)" but it does not work because **it show every user (licensed and unlicensed)** because nothing ever sets $licensed to $false.

**pseudo code bellow**

for each user in azure {
   licensed = true
   if at least one license is applied{
      licensed=true
   }
   if licensed = true { **this is always true**
      display user 
   }
}





The only difference between showing licensed or unlicensed users should be in the if statement.


**wrong code from the site bellow, simply formated better**
```
 Get-AzureAdUser | ForEach {
     $licensed=$True ; # <= should be $false
     For ($i=0; $i -le ($_.AssignedLicenses | Measure).Count ; $i++) { 
         If( [string]::IsNullOrEmpty(  $_.AssignedLicenses[$i].SkuId ) -ne $True) {
             $licensed=$true 
         } 
     } 

      If( $licensed -eq $true) {  # <= $true or $false whether you're trying to check if licensed or not
         Write-Host $_.UserPrincipalName
      } 
}
```

**Comment by msbemba** [comment]
Thank you. I will test the code and update the document if required. 

 

Thanks,

Sri

**Comment by msbemba** [comment]
@pbox Thank you again for your valuable feedback. You are correct! The code needs to be modified and I have done that via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3647

The document will be modified once the author approves the Pull request.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pbox Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
