### ISSUE TITLE
Is deleting a account a valid option to delete a Bookings Calendar

### ISSUE THREAD

**Issue by deuxpointzero** [MicrosoftDocs/microsoft-365-docs#3582]
Hello,

Do I have to delete the user so that it deletes the calendar. Am i reading correctly these instructions ? There should be a warning before doing that you are deleting an account and not just the calendar ? Am I right ?

The rest of the solution state to execute powershell commands to delete the calendar which is ok.
But the first solution seems to be a bit too strong to just delete a calendar.

I am happy to see that there's a powershell solution.

Thanks,

Bruno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa612c0e-c089-8b3e-8e2e-dd12b6fc382c
* Version Independent ID: fa014ea6-7aa2-b2bd-d913-165c3241675f
* Content: [Delete a booking calendar](https://docs.microsoft.com/en-us/microsoft-365/bookings/delete-calendar?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/delete-calendar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/delete-calendar.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@deuxpointzero Thank you for your feedback. You are correct, There are only two options to delete a booking calendar (Admin GUI to delete the account and the PS method). The  GUI option is strong and we got to delete the entire mailbox /user account. There has been a design request(user voice) to delete the calendar alone at the user/admin level (GUI) -https://outlook.uservoice.com/forums/314907-microsoft-bookings/suggestions/18203092-delete-a-bookings-calendar-test

You can vote for this design change and will be notified when it is approved. We will also update the document when there are feature changes made on Bookings.

Hope this helps! @yogkumgit There are no changes required on this document and the issue  can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@deuxpointzero  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
