### ISSUE TITLE
Usernames reset to default in o365 when removing non-default domain.

### ISSUE THREAD

**Issue by yukahey** [MicrosoftDocs/microsoft-365-docs#3583]
We have a hybrid setup for 5 years in o365 with 4 other domains within the tenant. All usernames upon setup had .onmicrosoft and we didn't want to confuse our many non-technical user base with that username, so we changed usernames to the Active Directory username + @ourdomain. We recently deleted one of the non-default domains and all usernames instantly changed back to the original username with .onmicrosoft.ourdomain.com. Sure, it's easy enough to redo the usernames but we endured the panic and calls to the helpdesk that no one could log in and email was not flowing. Microsoft support said this happens when a domain is removed - the usernames goes back to the default, but it's not listed anywhere as of Thanksgiving 2020.  This simple one page instructions to remove a domain in o365 needs this 'gotcha' attached OR this flaw to be fixed.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780db236-9235-2ce7-acbb-953fd997215b
* Version Independent ID: a5b80ea1-fb9f-d381-4fa6-7d4d8cce3f82
* Content: [Remove a domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/remove-a-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/remove-a-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/remove-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@yukahey Thank you for the feedback.  When you remove a domain, Office 365 user accounts will revert back to .onmicrosoft.com address as the Primary SMTP/UserprincipalName. I have added this as a Note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3619 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @yukahey Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
