### ISSUE TITLE
What permissions are needed to view the Defender for Office 365 reports

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3584]
The Global Reader role is not listed in this section,, is that an oversight? I would expect that role to be able to be able to view these reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e62b98-5f0c-8fc3-8163-c028fa5a6445
* Version Independent ID: b8262fa8-ff97-db0a-b2b5-4dd624fb057b
* Content: [View reports for Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-reports-for-atp?view=o365-worldwide#what-permissions-are-needed-to-view-the-defender-for-office-365-reports)
* Content Source: [microsoft-365/security/office-365-security/view-reports-for-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-reports-for-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@DeanGross, simple oversight. I tested and added Global Reader.

Thanks for the feedback.

Closing
