### ISSUE TITLE
NSG is not assigned to subnet after following instructions

### ISSUE THREAD

**Issue by JeremyHargis** [MicrosoftDocs/microsoft-365-docs#359]
Hello,

I'm trying to follow the guide [here](https://docs.microsoft.com/en-us/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise). I've reached the step which requires this code:

```
$rgName="<name of your new resource group>"
$locName=(Get-AzResourceGroup -Name $rgName).Location
$corpnetSubnet=New-AzVirtualNetworkSubnetConfig -Name Corpnet -AddressPrefix 10.0.0.0/24
New-AzVirtualNetwork -Name TestLab -ResourceGroupName $rgName -Location $locName -AddressPrefix 10.0.0.0/8 -Subnet $corpnetSubnet -DNSServer 10.0.0.4
$rule1=New-AzNetworkSecurityRuleConfig -Name "RDPTraffic" -Description "Allow RDP to all VMs on the subnet" -Access Allow -Protocol Tcp -Direction Inbound -Priority 100 -SourceAddressPrefix Internet -SourcePortRange * -DestinationAddressPrefix * -DestinationPortRange 3389
New-AzNetworkSecurityGroup -Name Corpnet -ResourceGroupName $rgName -Location $locName -SecurityRules $rule1
$vnet=Get-AzVirtualNetwork -ResourceGroupName $rgName -Name TestLab
$nsg=Get-AzNetworkSecurityGroup -Name Corpnet -ResourceGroupName $rgName
Set-AzVirtualNetworkSubnetConfig -VirtualNetwork $vnet -Name Corpnet -AddressPrefix "10.0.0.0/24" -NetworkSecurityGroup $nsg
```

Based on the surrounding context and on the commands in the block, it seems like the the NSG should now be assigned to the new subnet, but this doesn't happen. There are no errors returned and everything else seems to be successfully created and configured. I deleted everything and tried again from scratch several times. I can successfully assign the NSG to the subnet using the graphical interface at portal.azure.com. Are the commands in the block above outdated or incorrect?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6989d21-f7a7-043b-c91a-cd019a19c0e6
* Version Independent ID: 39e286bc-58fe-768e-ee65-2a2fedf1e544
* Content: [Simulated enterprise base configuration for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise)
* Content Source: [microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@JeremyHargis The article has been updated to include the "$vnet | Set-AzVirtualNetwork" command after the Set-AzVirtualNetworkSubnetConfig command. This is now required to force the change in the overall VNet configuration. This was not required in the previous version of these commands. Thanks for letting me know.
