### ISSUE TITLE
Bookings Address Field Issue

### ISSUE THREAD

**Issue by jhambach** [MicrosoftDocs/microsoft-365-docs#3592]
When using a bookings public page, the address field doesn't display properly on the Outlook Calendar event page. If you manually create the booking it works fine, but if the booking is done from the booking page the address doesn't get added properly and shows up as "Other"

**Comment by denisebmsft** [comment]
Hello @jhambach. To which article(s) does your feedback apply? This information will help us route the issue to the correct writer/team. Thanks!!

**Comment by msbemba** [comment]
@jhambach Thank you for your feedback. Are you referring to this document - https://docs.microsoft.com/en-us/microsoft-365/bookings/create-a-manual-booking?view=o365-worldwide?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jhambach Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
