### ISSUE TITLE
What permissions are required to list the onboarded devices in M365 Compliance > Settings > Devices onboarding > Devices?

### ISSUE THREAD

**Issue by Jimnar** [MicrosoftDocs/microsoft-365-docs#3594]
Members of the Compliance Administrator or Security Administrator role group in O365 SCC are not able to view the onboarded devices list. Must one be a Global Administrator? Can we add any clarification to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Jimnar Thank you for your feedback. I was able to test this feature on a new account and it works with a Security/compliance admin role. 

![image](https://user-images.githubusercontent.com/45987684/101243285-132d8500-3725-11eb-83da-0a53425eb634.png)

What is the error message you receive when you access the devices list?

Thanks
Sri

**Comment by Jimnar** [comment]
I can confirm the role I have configured as a compliance admin CAN see the onboarded devices. I'll close the issue.
