### ISSUE TITLE
Microsoft Defender for Office 365 Plan 1 and Plan 2

### ISSUE THREAD

**Issue by lucafabbri365** [MicrosoftDocs/microsoft-365-docs#3596]
Hello,
currently **Microsoft Defender for Office 365 Plan 1 and Plan 2** are available on Microsoft 356 admin portal as available (purchasable) add-ons of **Microsoft 365 Business Standard** plan; however looking at this Microsoft Docs page, **Microsoft 365 Defender for Office 365** seems to be available for Office 365 Enterprise E1, E2, E4 (not for Microsoft 365 Business Standard). So, what I miss ?

Thank you,
Luca

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 903e8a02-dbce-4f9c-a397-f2c549b95b57
* Version Independent ID: fa546b6a-5c3a-5019-e97c-8510f782e4b8
* Content: [Buy or edit an add-on](https://docs.microsoft.com/en-us/microsoft-365/commerce/buy-or-edit-an-add-on?view=o365-worldwide#available-add-ons)
* Content Source: [microsoft-365/commerce/buy-or-edit-an-add-on.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/buy-or-edit-an-add-on.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@lucafabbri365 Thank you for your feedback. We have updated the document with defender availability. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3622

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @lucafabbri365 author confirmed that table in question is removed hence We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
