### ISSUE TITLE
Add information for when adding a secondary domain 

### ISSUE THREAD

**Issue by SingingTech** [MicrosoftDocs/microsoft-365-docs#3597]
[When adding a secondary domain for a tenant within GCC high, it is my understanding that the MX records are the same BUT you need to add it into  azure AD and verify the domain first before creating users and/or aliases under that domain. Could we include this information in the article somewhere?  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a8b9e7-32c2-9e42-5f9d-8824bd15ab8e
* Version Independent ID: 4e4ba710-bb50-569d-34a6-8ef122d57aa6
* Content: [DNS records for Office 365 GCC High - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/dns-records-for-office-365-gcc-high?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/dns-records-for-office-365-gcc-high.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/dns-records-for-office-365-gcc-high.md)
* Service: **o365-administration**
* GitHub Login: @dzazzo
* Microsoft Alias: **dzazzo**

**Comment by dzazzo-msft** [comment]
Discussed this offline with @SingingTech - I'm not sure this is an appropriate edit.  I agree that there's some orders of operations work that needs to happen here (you need to add the domain to the tenant before you can use it to accept email), but the process of adding and verifying the domain (with the ms= MX or TXT record) is external to this guidance and isn't part of the Office-specific DNS guidance.  I'll noodle on this some more though.

We're also working to try to get the Domains functionality reintroduced to the Office 365 Admin Center for GCC High and DOD which will deprecate these two pages altogether.

**Comment by msbemba** [comment]
@SingingTech Thank you for the feedback. 

@dzazzo-msft  I have added a reference link at the bottom which talks about adding a new domain to an existing tenant. If you think it is a suitable edit, please approve. Reference PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3650

Thanks
Sri

**Comment by dzazzo-msft** [comment]
Ordinarily, I'd say yes, but on this one - no, this will add more confusion. Domain management is not currently available within the Office 365 Admin portals for GCC High and DOD. Hopefully will change soon, but not yet.

**Comment by msbemba** [comment]
@dzazzo-msft Thank you for the update. I'll close the PR.

@yogkumgit This issue can be closed as there are no changes required to the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SingingTech Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
