### ISSUE TITLE
Incorrect usage instructions

### ISSUE THREAD

**Issue by glen-ritchie** [MicrosoftDocs/microsoft-365-docs#3599]
These instructions in this page are incorrect and do not work.

> In the admin center, go to the Reports > Usage page.
> Select View More under Active users - Microsoft 365 Services.
> From the Active users drop-down list, select Exchange > Mailbox usage.

If you follow these instructions, there is no "Active users drop-down list" to select anything from, 

To view the mailbox usage you must instead:

1. Click "View More" under **"Email Activity"** 
2. Click "Email Activity" drop down and select "Exchange - Mailbox usage"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e612a4e4-d051-27a7-e54a-bb1ac3fe0849
* Version Independent ID: 653be32f-e4e8-8a72-98b3-a629238ecbd5
* Content: [Microsoft 365 Reports in the admin center - Mailbox usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/mailbox-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/mailbox-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@glen-ritchie  We are in the process of updating the navigation path since it changed. I will let you know once this is updated and the document is live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @glen-ritchie Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
