### ISSUE TITLE
Wrong sub menu

### ISSUE THREAD

**Issue by limp15000** [MicrosoftDocs/microsoft-365-docs#3602]
[Enter feedback here]
The custom dns page should not be under the productivity score. "Monitor user productivity with Productivity score "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f2e4e45-6ad7-eb79-aecb-0d7a89b06a03
* Version Independent ID: 1059223e-5759-b130-41ac-5ea98cb5367e
* Content: [Add DNS records to connect your domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@limp15000 Thank you for the feedback. I will work internally with the author to get this sorted.

Thanks
Sri

**Comment by msbemba** [comment]
@Sirkkuw We notice that the document - Microsoft Productivity score (https://docs.microsoft.com/en-us/microsoft-365/admin/productivity/productivity-score?view=o365-worldwide) has an incorrect submenu linking to this Custom DNS Page (https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide) 

Could you please help in removing this article from the sub-menu? 

CC: @pebaum @yogkumgit 

Thanks
Sri

**Comment by Sirkkuw** [comment]
Ah yes. I will remove this. Cut and paste error...

**Comment by msbemba** [comment]
@Sirkkuw Thank you for the update.

@yogkumgit This can be closed as the sub menu has been removed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @limp15000 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
