### ISSUE TITLE
Classic Settings Page is deprecated

### ISSUE THREAD

**Issue by ihloff** [MicrosoftDocs/microsoft-365-docs#3603]
This article states following:
"4. In the left pane, choose settings, and then choose classic settings page."
As the Classic Settings Page is deprecated and no longer available this needs to be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29df28b-0065-a059-f22d-3433c1dd65a0
* Version Independent ID: 83b44475-2a39-5747-fc3c-2a92d0d958f2
* Content: [Set up Information Rights Management (IRM) in SharePoint admin center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-irm-in-sp-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-irm-in-sp-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-irm-in-sp-admin-center.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@ihloff Thank you for your feedback. This setting is still available if you click on the Go to the classic setting page at the bottom

![image](https://user-images.githubusercontent.com/45987684/101008349-b183e400-3587-11eb-99fe-cafed76a2ba3.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ihloff Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
