### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Matthew-Kent** [MicrosoftDocs/microsoft-365-docs#3604]
Foe example, you could run the following Windows PowerShell

Should read

For example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be15ac4-2297-90eb-57f0-2c3eebfbdd91
* Version Independent ID: 959cf2d6-b6cd-59b9-21e4-dc31e8fba0b9
* Content: [Prepare a non-routable domain for directory synchronization - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@Matthew-Kent Article updated thanks to @TeeVenDick. Thanks for letting us know.
