### ISSUE TITLE
Error in documentation about Mailbox Usage

### ISSUE THREAD

**Issue by Franckiboy15** [MicrosoftDocs/microsoft-365-docs#3609]
In Step 2, "Select View More under Active users - Microsoft 365 Services."  the option is not in this panel anymore but in the Email activity section.

In step 3, the drop down list name is Email activity and not active user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e612a4e4-d051-27a7-e54a-bb1ac3fe0849
* Version Independent ID: 653be32f-e4e8-8a72-98b3-a629238ecbd5
* Content: [Microsoft 365 Reports in the admin center - Mailbox usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/mailbox-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/mailbox-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Franckiboy15 We are in the process of updating the navigation path since it changed. I will let you know once this is updated and the document is live.

Thanks
Sri

**Comment by msbemba** [comment]
reference PR #https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3573

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Franckiboy15 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
