### ISSUE TITLE
Updated version of Windows and Office Lab kit

### ISSUE THREAD

**Issue by Scotthrobinson** [MicrosoftDocs/microsoft-365-docs#361]
Is there an updated version of the kit. The website shows the expiration is today?

"The lab expires May 13, 2019. A new version will be published prior to expiration."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office Deployment Lab Kit](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab#feedback)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by mypil** [comment]
@Scotthrobinson - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JGruszczyk - Can you please share your insights on this issue?

Thank you.

**Comment by JGruszczyk** [comment]
Hi - we will continue to update the deployment lab kit, we had some last minute changes we're working on

**Comment by karelklatovsky** [comment]
Hi, any updates pls? Thx.

**Comment by JGruszczyk** [comment]
We are pushing a new version to the evaluation center today, will be live by end of week!

**Comment by keshu2313** [comment]
Hi JGruszczyk,

Thanks for Uploaded new version of the evaluation cente.
I have tried to download the file but unfortunetly  the file downloding is stopping at 3 GB.
Could you please let me know what was the issue.

My internet speed  1Gb download speed
