### ISSUE TITLE
Mail Flow Rules + Outbound Spam Filter

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#3610]
What if you have both configured to block auto-forwarding? Will the user get the mail flow rule kickback or the kickback from the outbound spam rule?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding, Automatic forwarding, 5.7.520 Access Denied, disable external forwarding, Your administrator has disabled external forwarding, outbound anti-spam policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@HarrisburgUSysAdmin, I'm told that transport rules will hit first.

**Comment by HarrisburgUSysAdmin** [comment]
Ok, we are having a significant issue with the outbound spam filter and working with Microsoft.  They can't figure out why our emails are coming back with the NDR when our outbound spam policy clearly is set to allow external forwarding.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by msbemba** [comment]
@HarrisburgUSysAdmin Thank you for your feedback. I was able to test this and I see the NDR from the mail flow rule.Let us know how the Support Personnel fixes this and based on the outcome, we can modify the document if needed.

Thanks
Sri

**Comment by HarrisburgUSysAdmin** [comment]
@chrisda and @msbemba - I'm unable to test this because we are having issues with our outbound spam filter.  We have 2 polices the default policy and the HU Outbound Spam Policy. Both have auto forwarding set to ON. We still get the NDR. Our support tech is unable to figure this one out.

[Case #:23164797]

**Comment by HarrisburgUSysAdmin** [comment]
I think I may know why this is not working for us. Our "default" outbound spam filter is not viewable via the GUI.  A user on reddit tipped me off about this saying how he manages some 10 tenants and all have the default outbound spam filter viewable in the GUI. We do not.  This is only accessible via PowerShell.

**Comment by msbemba** [comment]
@HarrisburgUSysAdmin That is definitely a bug.The outbound spam policy should be viewable on the GUI to make changes. Unfortunately, we do not have access to support tickets to view the current status. Did you get this escalated for them to fix? Let us know the outcome. There are no changes required in the document but will wait for you to confirm before we close this issue.

Thanks
Sri

**Comment by chrisda** [comment]
I'm tempted to close #3644 as a dupe of this issue.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @HarrisburgUSysAdmin 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future
