### ISSUE TITLE
missing endpoints

### ISSUE THREAD

**Issue by menewol** [MicrosoftDocs/microsoft-365-docs#3612]
Please update the list of endpoints appropriately to reflect the endpoints used by Microsoft Streams (particularly within MS Teams, e.g. as new Card/Tab within a channel)
If this is not the right place to find the used endpoints for a MS service (particularly MS Streams), would you please be so kind to point me in the right direction? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@menewol Thank you for your feedback. I have added MS Stream's endpoints to the resources section of the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3687

Thanks
Sri
