### ISSUE TITLE
Please update the information on how to proceed after the  request deadline is over.

### ISSUE THREAD

**Issue by Navesai** [MicrosoftDocs/microsoft-365-docs#3613]
Not mentioned - What to do after 30th June,2020 ?

How Can I raise a request for GoLocal for South Africa tenant now ?

Can you please update the information on how to proceed after the  request deadline is over ?

**Comment by yogkumgit** [comment]
@Navesai We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
