### ISSUE TITLE
Manage staff - Bookable yes/no

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/microsoft-365-docs#3614]
How to change bookable attribute under Manage staff?
Please add this question to FAQ.

According to answer of Arun Satyarth <Arun.Satyarth@microsoft.com>:
When the staff was added, he would have received an email for accepting or rejecting the request. They can open the same email and select "Reject" . This will make him non bookable. We currently do not have a way to toggle this from inside the app. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7484dd4-5d94-dd6c-0dbe-551c852677c1
* Version Independent ID: 257d60e2-9313-e08b-dccf-120cb4b30f5b
* Content: [Microsoft Bookings Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-faq.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@trudolf-msft Thank you for the feedback. We have added this to the FAW section via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3688

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @trudolf-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
