### ISSUE TITLE
X-MS-Exchange-Organization-Network-Message-Id not available in quarantines messages

### ISSUE THREAD

**Issue by Crimsonfox89** [MicrosoftDocs/microsoft-365-docs#3620]
Under the "Submit a questionable email to Microsoft" heading, it states to use the "X-MS-Exchange-Organization-Network-Message-Id". This value does not seem to appear in the header of a message that has been quarantined (https://protection.office.com/quarantine). In that case the **X-MS-Office365-Filtering-Correlation-Id** value is identical and can be used instead.

It would be useful to note this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Admin submissions - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **siosulli**

**Comment by chrisda** [comment]
@Crimsonfox89, I updated the topic as you described. In the future, you too can make changes like this without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
