### ISSUE TITLE
Remove "Get-OutlookAnywhere | FL server,*url*" - this is not correct

### ISSUE THREAD

**Issue by pakondra** [MicrosoftDocs/microsoft-365-docs#3623]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae987bba-faf5-916d-c3b1-74f547ff8d90
* Version Independent ID: 9f5a7979-af5a-8fbf-45f0-287bb9fa4772
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by pakondra** [comment]
In this section: https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication?view=o365-worldwide#add-on-premises-web-service-urls-as-spns-in-azure-ad

Please remove "Get-OutlookAnywhere | FL server,*url*" as it is not applicable.

**Comment by msbemba** [comment]
@pakondra Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3690

You are correct  "Get-OutlookAnywhere | FL server,url" is Incorrect, but you need to use Get-OutlookAnywhere | FL server, HostName to get the relevant URLs:

Thanks
Sri

**Comment by LauraWi** [comment]
PR merged
