### ISSUE TITLE
Threat management > Policy > Tenant Allow/Block Lists Doesn't Exists

### ISSUE THREAD

**Issue by JBurdGitsIT** [MicrosoftDocs/microsoft-365-docs#3624]
Step 1 includes the words "go to Threat management > Policy > Tenant Allow/Block Lists." 

The Allow/Block Lists option no longer exists; therefore, the document's usefulness is greatly diminished. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allowed and blocked URLs in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JBurdGitsIT, as described at the top of the topic:

 > [!NOTE]
> The features described in this topic are in Preview, are subject to change, and are not available in all organizations.

Are you saying the Tenant Allow/Block list was available to you in the past but now it's gone?

**Comment by chrisda** [comment]
Closing
