### ISSUE TITLE
SharePoint Syntex error during training of a model

### ISSUE THREAD

**Issue by jschnei5** [MicrosoftDocs/microsoft-365-docs#3625]
Hello,
I received an error while setting up SharePoint Syntex that has not yet been described here. Maybe it is due to the configuration of the system. If so, please include it in the manual. Unfortunately, I have not found a solution yet or received a solution from your support. 
The error occurs when you want to train a model. It is displayed, no text is recognized in the documents.

**Error**: AADSTS500011 The resource principal named https://germanywestcentral1-mediap.svc.ms was not found in the tenant named ....

![2020-11-24 15_26_33-Authentication on API APP - Error_ AADSTS500011](https://user-images.githubusercontent.com/26413703/101048103-a8444880-3582-11eb-9ec0-85790fe3147b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding#feedback)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@jschnei5 Considering the nature of the issue, we advise, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
