### ISSUE TITLE
$AllowGroupCreation = "False" should be $AllowGroupCreation = $false

### ISSUE THREAD

**Issue by MutantCarrot** [MicrosoftDocs/microsoft-365-docs#3626]
as per title.  otherwise you get:

Message: The value '' for property 'EnableGroupCreation' does not match the expected type 'System.Boolean'.

**Comment by chrisda** [comment]
@MutantCarrot, the topic in question is <https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups>. I fixed it.

In the future, you too can make updates like this directly without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
