### ISSUE TITLE
Out of date instructions 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3627]
The link to run a search points to protection.office.com, since this is getting phased out, a better link would be to https://compliance.microsoft.com/auditlogsearch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@DeanGross Thanks for feedback. Eventually, audit log search in SCC will be redirected to MCC.

**Comment by markjjo** [comment]
Also, I assume you have seen this banner as well, with the link to the MCC audit log search tool:

![image](https://user-images.githubusercontent.com/36746813/101078399-f6ddec80-355a-11eb-8810-2eebde05b8f2.png)

**Comment by DeanGross** [comment]
Yes, that is what inspired my comment, The docs send me to that page, which then redirects me to the new site. It would be nice to skip that middle step.
