### ISSUE TITLE
Missing Operations

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3628]
When I look in an exported file, I see Operations that are not listed as audited events, specifically for the Exchange workload

New-AuthenticationPolicy
Set-OrganizationConfig
Set-AuthenticationPolicy
Set-HostedContentFilterPolicy
New-ReportSubmissionPolicy
 are in my file but are not described in the documentation. Please update the documentation to ensure that it accurately describes all of the events that are audited. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@DeanGross It's not really feasible to document all Exchange admin audit operations in the context of auditing. This topic addresses this by citing the Exchange admin audit log and that these operations correspond to cmdlets in EXO, which are documented in cmdlet reference topics. Please see: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#exchange-admin-audit-log

**Comment by DeanGross** [comment]
Thanks, i totally missed that explanation
