### ISSUE TITLE
Azure Free Trial subscription has 3 day deletion limitation

### ISSUE THREAD

**Issue by gluebags** [MicrosoftDocs/microsoft-365-docs#3632]
Reads 'contact support if unable to delete immediately' 

The Delete subscription option isn't available until three days after you cancel a 'Free Trial' Azure subscription. 

Experiences with support suggest that this 3 day limit cannot be bypassed for Free Trials.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adb403b-fded-7b9c-c093-915ca9bb348d
* Version Independent ID: df08fc6b-a752-084b-448a-a253db2a40d5
* Content: [Close your account](https://docs.microsoft.com/en-us/microsoft-365/commerce/close-your-account?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/close-your-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/close-your-account.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@gluebags Thank you for the feedback. You are correct about the restriction on Azure Free trial Subscription, We have added the restriction to the note section of the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3689


Thanks
Sri

**Comment by msbemba** [comment]
@gluebags We have got an update from the author that If you have a free trial subscription, you don't have to wait 30 days for the subscription to automatically delete. You can delete your subscription three days after you cancel it. The Delete subscription option isn't available until three days after you cancel your subscription.

Wait three days after the date you canceled the subscription.
Select your subscription on the Subscriptions page in the Azure portal.
Select the subscription that you want to delete.
Select Overview, and then select Delete subscription.

This has been updated in the document 
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/cancel-azure-subscription#delete-free-trial-subscription

Hope this helps!

@yogkumgit There are changes in the document. Please proceed with closure.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution. @gluebags Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
