### ISSUE TITLE
Instead of *url*, filter for *hostname* to get the relevant URLs from Get-OutlookAnywhere

### ISSUE THREAD

**Issue by svajda** [MicrosoftDocs/microsoft-365-docs#3634]
In the "Add on-premises web service URLs as SPNs in Azure AD" section, the cmdlet sample to gather all the URLs that we need to add in AAD shows this:

Get-OutlookAnywhere | FL server,*url*

Filtering for *url* is fine for the Get-*VirtualDirectory cmdlets, however, for Get-OutlookAnywhere, we should use a syntax like this to get the relevant URLs:

Get-OutlookAnywhere | FL server, *HostName*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae987bba-faf5-916d-c3b1-74f547ff8d90
* Version Independent ID: 9f5a7979-af5a-8fbf-45f0-287bb9fa4772
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@svajda Thank for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3690

Thanks
Sri

**Comment by LauraWi** [comment]
PR now merged
