### ISSUE TITLE
I follow the instruction however I don't see the custom record "Under DNS settings, select Custom Records, and then choose New custom record."

### ISSUE THREAD

**Issue by bhakuparkharsohtun** [MicrosoftDocs/microsoft-365-docs#3635]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c52d59a-7466-a5a8-7031-e4ea7b782f57
* Version Independent ID: e02a33bc-12c6-4192-cf3f-bcea567085c3
* Content: [Change nameservers to set up Microsoft 365 with any domain registrar - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by lertoo** [comment]
Has MS removed this feature? I cannot see my custom DNS records for my Azure VM I entered before.

**Comment by msbemba** [comment]
@bhakuparkharsohtun Thank you for your feedback. You will see the option only when you have Microsoft NS records are added.  If that is the case could you please provide us a Screenshot? Also, the option is changed to manage DNS instead of DNS Settings. This change can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3691

Thanks
Sri

**Comment by lertoo** [comment]
I can see the “Custom records” now - it wasn't there when I checked.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @bhakuparkharsohtun Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
