### ISSUE TITLE
Incorrect

### ISSUE THREAD

**Issue by rsun0525** [MicrosoftDocs/microsoft-365-docs#3636]
Our Data Privacy team complained that all of our users outside of the US were receiving the Cortana Daily Briefing.  Based on your information in this link, it said only users in the US geo should get it.  We opened up a ticket under Premier Support, and they said according to this URL https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Rolling%20out&searchterms=57204, the feature is being rolled out worldwide as of August CY2020.  They told me if I have a concern, I should provide feedback this way.  Can you revise your page to say it's possible that everyone in your tenant could be receiving this message?

This is the specific text that raised a concern with our Data Privacy team: “New Microsoft 365 experiences, such as the Briefing email and Play My Emails, will be enabled using Cortana enterprise services and fully comply with those promises. These features are currently available in the English (United States) market for users with mailboxes in the US geo, and for employees of multi-national corporations with US-based mailboxes.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad4b3d3-b509-c6c6-e842-b53c68100c4e
* Version Independent ID: ec63705a-7ce3-abf6-5f4f-fe5bc95bc9b8
* Content: [Cortana in Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/cortana-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/cortana-integration.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@rsun0525 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3692

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rsun0525 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
