### ISSUE TITLE
This doesn't work for me

### ISSUE THREAD

**Issue by cornwallcare** [MicrosoftDocs/microsoft-365-docs#3637]
Whenever I run this script I get this error please help:

At C:\WINDOWS\system32\groupcreation.ps1:23 char:43
+ $settingsCopy["GroupCreationAllowedGroupId"] = $GroupName
+                                           ~~~~~~~~~~~~~~~
The string is missing the terminator: ".
At C:\WINDOWS\system32\groupcreation.ps1:2 char:29
+ $AllowGroupCreation = $False"
+                             ~
Unexpected token '"
Connect-AzureAD
$settingsObjectID = (Get-AzureADDirectorySetting | Where-object -Property Displayname -Value "' in expression or
statement.
At C:\WINDOWS\system32\groupcreation.ps1:6 char:95                                                                      + ... g | Where-object -Property Displayname -Value "Group.Unified" -EQ).id                                             +                                                    ~~~~~~~~~~~~~~~~~~~~~~                                             Unexpected token 'Group.Unified" -EQ).id                                                                                if(!$settingsObjectID)
{
    $template = Get-AzureADDirectorySettingTemplate | Where-object {$_.displayname -eq "group.unified"}
    $settingsCopy = $template.CreateDirectorySetting()
    New-AzureADDirectorySetting -DirectorySetting $settingsCopy
    $settingsObjectID = (Get-AzureADDirectorySetting | Where-object -Property Displayname -Value "Group.Unified"
-EQ).id
}
$settingsCopy = Get-AzureADDirectorySetting -Id $settingsObjectID
$settingsCopy["EnableGroupCreation"] = $AllowGroupCreation
if($GroupName)
{
  $settingsCopy["GroupCreationAllowedGroupId"] = (Get-AzureADGroup -SearchString $GroupName).objectid
}
 else {
$settingsCopy["GroupCreationAllowedGroupId"] = $GroupName
}
Set-AzureADDirectorySetting -Id $settingsObjectID -DirectorySetting $settingsCopy
(Get-AzureADDirectorySetting -Id $settingsObjectID).Values' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

**Comment by msbemba** [comment]
@cornwallcare Thank you for the feedback. Are you referring to the document  https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide?

If yes, then you need to Replace <SecurityGroupName> with the name of the security group that you created. For example:

$GroupName = "Group Creators"

Hope this help!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cornwallcare Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
