### ISSUE TITLE
In seek of confirmation of changes to CC and/or Subscription

### ISSUE THREAD

**Issue by JGDickerson** [MicrosoftDocs/microsoft-365-docs#3638]
Thank you for updating this page with more detailed instructions - super helpful.  Two Q's for you!

- Is there a confirmation in the Admin Portal to be confident that changes to payments occurred and my account is not suspended?
- Is an email sent to confirm the changes to make me even more confident?
- 
Cheers
JGD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14e33d-0d3e-45f4-fefe-dec3ae7d351f
* Version Independent ID: aeb53e2c-d35c-73fe-26f2-4f101bfeeea7
* Content: [Manage payment methods](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-payment-methods?view=o365-worldwide#replace-a-payment-method)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-payment-methods.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-payment-methods.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@JGDickerson There should be a confirmation that your change to a payment method was made, but it's not guaranteed that your account automatically goes back to active after that change is made. It depends on where you're at in the suspension of your account. If it's within the first 30 day grace period, it will be picked up & recharged. If it's after that period, your account will stay suspended until you manually settle the balance.

We do not send confirmation email that changes were made to the payment method. You only see a notification in the admin center after the change is saved.

Hope that helps!
Cern

**Comment by yogkumgit** [comment]
@cmcatee-MSFT  Thank you very much for  sharing this explanation. @JGDickerson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by JGDickerson** [comment]
Appreciate the collaboration!  Thank you

JULES
