### ISSUE TITLE
Missing Link?

### ISSUE THREAD

**Issue by DefenseStormCorp** [MicrosoftDocs/microsoft-365-docs#3639]
I am not seeing a link to the "Readiness assessment tool" anywhere on the page (or in a search engine for that matter). Could a link be added for us to download the tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2edbbcfe-6534-59d7-0607-c3de3ff3ccf2
* Version Independent ID: ed5a4eab-c164-5cb7-51c1-3e9eab7d1dd3
* Content: [Readiness assessment tool - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-ready/readiness-assessment-tool?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-ready/readiness-assessment-tool.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-ready/readiness-assessment-tool.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
You don't download the tool--it's available to you online as you go through the onboarding process.
