### ISSUE TITLE
Outbound Spam Filter External Forwarding

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#3644]
Both our default and custom outbound spam policies are set to allow external email forwarding. The setting is set to ON. No question.

However we are getting the NDR only when an email is sent from an external sender but to an internal mailboxes that is forwarding external. 

Example: Gmail user Bob emails internal mailbox named HELP that has a exchange external mailbox forwarding rule set. The mail is not sent to the external forwarding address and the NDR arrives in the internal mailbox HELP.

To complicate things.  If someone emails HELP from an internal address the forwarding works. This only occurs when the mail orginates from an external email domain. 

5.7.520 Access denied, Your organization does not allow external forwarding. Please contact your administrator for further assistance. AS(7555)

It's been a long long day on the phone with Microsoft trying go troubleshoot this with no luck.  This started randomly yesterday evening. 

Any thoughts?

**Comment by chrisda** [comment]
@HarrisburgUSysAdmin, are you saying you have an open support case that is still pending? Unclear at this point what a documentation update can do to help this; a support case is likely the only way to go.

**Comment by chrisda** [comment]
Closing this as dupe of #3610
