### ISSUE TITLE
Remote Server returned '550 5.7.520 Access denied, Your organization does not allow external forwarding. Please contact your administrator for further assistance. AS(7555)'

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#3648]
No matter what we set. This policy does not work for us. We think this is a MS bug.

Remote Server returned '550 5.7.520 Access denied, Your organization does not allow external forwarding. Please contact your administrator for further assistance. AS(7555)'

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding, Automatic forwarding, 5.7.520 Access Denied, disable external forwarding, Your administrator has disabled external forwarding, outbound anti-spam policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@HarrisburgUSysAdmin, you should open a support case. Nothing we can do from a documentation perspective (yet).

**Comment by chrisda** [comment]
Closing as duplicate of #3644
