### ISSUE TITLE
Apparrent Conflict

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/microsoft-365-docs#3649]
In the  excerpt below,  I see guidance that conditional access policies both do & do not apply to external users.

**Conditional Access policies only apply to guest access** in Teams because there is a corresponding Azure AD B2B account.

See Policy recommendations for securing Teams chats, groups, and files for more information about securing identity and device access policies for Teams.

**Require MFA always for guest and external users
This policy prompts guests to register for MFA in your tenant, regardless of whether they're registered for MFA in their home tenant. When accessing resources in your tenant, guest and external users are required to use MFA for every request.**

Please clarify
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4806dd-a0d0-966c-8130-e752676090a5
* Version Independent ID: 6403c614-26bc-f037-262a-1ec33fc7d385
* Content: [Identity and device access policies for allowing guest and external B2B access - Microsoft 365 for enterprise - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/identity-access-policies-guest-access?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/identity-access-policies-guest-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/identity-access-policies-guest-access.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@gkens Thank you for your feedback. The new Policy does require MFA always for guest and external users. I have made changes to the document accordingly. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3708

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gkens Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
