### ISSUE TITLE
BD

### ISSUE THREAD

**Issue by rohitpc363** [MicrosoftDocs/microsoft-365-docs#3652]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91837ba8-f6f2-3c52-2d89-c8f4c4bce09c
* Version Independent ID: eb3c1fd8-9143-0dc1-77e7-e664ccaefc33
* Content: [Microsoft cloud architecture models - enterprise resource planning](https://docs.microsoft.com/en-us/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/cloud-architecture-models.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/cloud-architecture-models.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by denisebmsft** [comment]
Hello @rohitpc363. Did you have a question or comment for us?

**Comment by yogkumgit** [comment]
@rohitpc363 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
