### ISSUE TITLE
Out of data info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3653]
There were many new changes in the compliance center in November. please update this page. It is very challenging to keep up with the changes and when the what's new pages are not maintained it is even more difficult. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89486ebd-f4fa-9d07-ee93-d04fd8d41027
* Version Independent ID: 667019d9-aac6-f466-1605-651a800fc212
* Content: [What's new in Microsoft 365 compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @brendonb
* Microsoft Alias: **brendonb**

**Comment by robmazz** [comment]
@DeanGross - thanks for the feedback, page has been updated for NOV/DEC 2020
