### ISSUE TITLE
Quotation missing in code

### ISSUE THREAD

**Issue by tjclark2** [MicrosoftDocs/microsoft-365-docs#3654]
Step 2: Run PowerShell commands - need a beginning quotation in the $AllowGroupCreation = "$False" line before False.

**Comment by denisebmsft** [comment]
Hello @tjclark2. Thanks for the feedback! Can you please tell us to which article this applies?

**Comment by tjclark2** [comment]
Hey Denise!

Sorry – here is the article I mentioned:

Manage who can create Microsoft 365 Groups | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide>

Respectfully…

Thomas J. Clark
Consultant | Microsoft Federal
954.375.3649  | thomas.clark@microsoft.com<mailto:thomas.clark@microsoft.com>
[MSFT_logo_Print_small]

**Comment by msbemba** [comment]
@tjclark2 Thank you for the feedback. Since $false is a boolean value. we don't need a quotation. I tested the same and it works. Let me know if you receive any specific error when you run without a quotation or as it is in the document.

Thanks
Sri

**Comment by tjclark2** [comment]
Hey Sri!

I went to the site and it looks good now. When I reported the problem there was a quotation mark at the end of $False. When we tested it, it didn't work unless we added the matching quotation mark in the beginning. Removing both works as well. Thank you!

Respectfully...

Thomas J. Clark
Consultant | Microsoft Federal
954.375.3649  | thomas.clark@microsoft.com<mailto:thomas.clark@microsoft.com>
[MSFT_logo_Print_small]

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tjclark2 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
