### ISSUE TITLE
Coming soon

### ISSUE THREAD

**Issue by bloodytourists** [MicrosoftDocs/microsoft-365-docs#3659]
Could you provide more details on the Coming Soon details. The section has not changed in a long time so was wondering exactly what is coming soon and when we will be able to preview. I have spoken to some folk in Microsoft who do not seem to know what this is referring to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7052266e-b8f3-4d4f-4df7-bbf93780790d
* Version Independent ID: 9050a1bf-4a04-e629-eb6b-4b8277a16bfd
* Content: [Permissions in the Microsoft 365 security and compliance centers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-microsoft-365-compliance-security?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-microsoft-365-compliance-security.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-microsoft-365-compliance-security.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by chrisda** [comment]
@bloodytourists, in checking the current interface in both the Security center and the Compliance center, nothing has changed (other than the Global Reader role now being available):

- You still can't manage roles directly in the Security center or Compliance center (you still link off to manage role membership in Azure AD).
- You still can't customize roles by adding or removing permissions.
- You still can't create custom roles.

**Comment by chrisda** [comment]
I inspected and updated the topic 3+ weeks ago. Closing
