### ISSUE TITLE
The Spoof intelligence now has four reports and the content does not reflect this

### ISSUE THREAD

**Issue by wobblewobble** [MicrosoftDocs/microsoft-365-docs#3660]
On the portal https://protection.office.com/searchandinvestigation/dashboard
The Spoof intelligence now has four reports.
![spoofed_domains](https://user-images.githubusercontent.com/1448864/101478704-fffaff00-3948-11eb-82ae-b608a9634322.png)

Likely Spoofed Domains over the past 7 days with suspicious and non suspicious.
Impersonations over the past 7 days with Domains impersonated and Users impersonated
The content does not reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb5aaaa-d804-cdbe-79ca-826cb67cc3e5
* Version Independent ID: dd128a8c-afe2-c507-5f19-ed588f00bc7a
* Content: [Walkthrough - Spoof intelligence insight - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@wobblewobble, I updated the topic with a new screenshot and information based on current reality for the Spoof intelligence insight.

Technically, spoof intelligence and impersonation protection are different technologies. That impersonations insight is new, but is separate from spoof intelligence, so I'm not going to include it.

Thanks for the feedback.

Closing
