### ISSUE TITLE
What LinkedIN data specifically is archived? - Messages, articles, connections, company follows etc? Please elaborate

### ISSUE THREAD

**Issue by lmurthy-git** [MicrosoftDocs/microsoft-365-docs#3663]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a96542-6e0f-d441-13db-6e47439c0583
* Version Independent ID: 524ca3e3-3e80-4693-206e-01a9533292f8
* Content: [Set up a connector to archive LinkedIn data - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/archive-linkedin-data?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/archive-linkedin-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/archive-linkedin-data.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@lmurthy-git Only parent posts, posted by the organization to the company page are imported. No comments on the posts or posts made by external users or other items are imported/archived.
