### ISSUE TITLE
Destructive changes

### ISSUE THREAD

**Issue by ficus** [MicrosoftDocs/microsoft-365-docs#3665]
Broke all our email forwarding now I am here reading this garbage instead of doing something else. Grrr

Set it to allow forwarding. Went back in to set the forwarder on account and the save button is still disabled. 

What really pisses me off, besides the whole change and having to read docs produced by Microsoft,  I don't know what forwarders were set for all these mailboxes and have no way to restore them. Is that data just lost forever? This is absurd.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding, Automatic forwarding, 5.7.520 Access Denied, disable external forwarding, Your administrator has disabled external forwarding, outbound anti-spam policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by ficus** [comment]
Turns out docs are just wrong/stale... Its not through admin > exchange > mailboxes... email forwarding there just seems broken, no way to click save. Instead had to go through admin > users > active users and set it there. Still kn way to see what the email forwarders were set to before this change broke them. Having to comb through old correspondence to see if I can figure that out,

**Comment by msbemba** [comment]
@ficus Thank you for your feedback. 
Unfortunately, there is no direct method to restore forwarders that were set earlier. As you mentioned the workaround would be to check mail flow (for old correspondence) and identify the emailaddress.

Both options (M365 admin center and Exchange admin center) does the same thing. I was able to save after making changes through EAC. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ficus Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
