### ISSUE TITLE
Wifi profile template not working

### ISSUE THREAD

**Issue by AlexBlain** [MicrosoftDocs/microsoft-365-docs#367]
Wifi profile template not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73aadf1a-466a-6188-ea22-44033bc49eb2
* Version Independent ID: 571b56f7-7443-74d0-a179-7c49da110adc
* Content: [Prepare certificates and network profiles for Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-ready/certs-wifi-lan)
* Content Source: [microsoft-365/managed-desktop/get-ready/certs-wifi-lan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-ready/certs-wifi-lan.md)
* Service: **m365-md**
* GitHub Login: @jaimeo

**Comment by jaimeo** [comment]
Thanks for letting me know! I'll investigate Monday.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by jaimeo** [comment]
Small typo in the filename--I've pushed a fix that hopefully will be live after 1000 today.

**Comment by mypil** [comment]
@AlexBlain - Thank you for submitting this feedback.

From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
