### ISSUE TITLE
Exact definition of the functions and built-in keyword lists?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#3673]
Before we report an potential issue, we would like to determine if it is in the MS default definitions/keyword lists.
But we can't see the real implementation ("source code" if you will) of the functions and keyword lists.
We only see this page and two pages with definitions (we can't give feedback on BTW): 
[![image](https://user-images.githubusercontent.com/23510294/101627479-b41a8980-3a1e-11eb-897e-ca6ddb13a8a7.png)](url)
[![image](https://user-images.githubusercontent.com/23510294/101627504-bbda2e00-3a1e-11eb-8460-d90e74d7ffe1.png)](url)
We think we use the O365 definition of "Netherlands Citizen's Service (BSN) Number", but it seems we have the EXO one.
That is, we selected this sensitivity info type in the portal when defining the label. It should honour both _bsn_ and _BSN_ but it only detects the uppercase variant. And that is exactly one of the differences between the two definitions. Now - how do we know which one is which or better yet - where can we find the specs of the functions and keyword lists?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ebaf450-d84e-c333-125c-b0e6d4662bad
* Version Independent ID: efcb8b51-f2fe-765b-221d-75890b4a2d64
* Content: [What the Data Loss Prevention (DLP) functions look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-dlp-functions-look-for?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/what-the-dlp-functions-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-dlp-functions-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox  Please add your comment and help us in resolving this issue. Thanks.

**Comment by chrfox** [comment]
HI @andrePKI 
The keywords in the topic and the XML code are the authoritative source. I suggest you contact Microsoft Support Services to help resolve your issue
