### ISSUE TITLE
Download of Hybrid Configuration Wizard not included in list of Additional Endpoints

### ISSUE THREAD

**Issue by colbyMS** [MicrosoftDocs/microsoft-365-docs#3674]
Tried to download HCW from a restricted server that had the flows configured.  Link to HCW is aka.ms/hybridwizard.  Following endpoints failed:

- aka.ms
- https://shcwreleaseprod.blob.core.windows.net/shcw/Microsoft.Online.CSE.Hybrid.Client.application

This may just be a 1 time connection; however, each time the HCW runs, it will attempt that URL to get updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@Colbyms Thank you for your feedback. I'll check internally with the author and add this information to the document.

@JoeDavies-MSFT Need your help in adding a Hybrid configuration wizard as a new Purpose and add the destination? I don't have access to editing these rows in the document.

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
This is being discussed within Microsoft.
