### ISSUE TITLE
External forward blocking stated behavior is inconsistent

### ISSUE THREAD

**Issue by ayprof** [MicrosoftDocs/microsoft-365-docs#3677]
Docs says that:
"When automatic forwarding is disabled, the recipient will receive a non-delivery report (also known as an NDR or bounce message) if external senders send email to a mailbox that has forwarding in place. If the email is sent by an internal sender, the sender will get the NDR."

However, it's only true that the internal sender will get an NDR if the method of forwarding is via SMTP forwarding—it does not occur if the forwarding is due to an inbox rule.  

That said, it would be nice if there was a way for the internal sender to NOT receive an NDR if the checkbox for SMTP forwarding to 'Keep a copy of forwarded messages' is checked, since the email has been delivered in that case.  Due to this behavior, we're having to convert user SMPT forwarding rules to inbox rules so that we can block external forwarding without causing confusing NDR messages to be sent everywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure outbound spam filtering - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ayprof, for feature suggestions like this, you're better off going to <https://office365.uservoice.com/>.

**Comment by ayprof** [comment]
That's fine, but the case of senders not getting an NDR if the method of forwarding to an external domain via an inbox rule is still valid.

**Comment by ayprof** [comment]
Also, it does seem like a bug or a design flaw since the email HAS been delivered to the mailbox—only the copy has not been delivered.  In that case, if the box to Keep the email has been checked, I would expect the recipient to get an NDR if the forwarded email is blocked; if the box is not checked, for the sender to get an NDR.

**Comment by chrisda** [comment]
@ayprof, I updated the original statement as you described:

When automatic forwarding is disabled, the recipient will receive a non-delivery report (also known as an NDR or bounce message) if external senders send email to a mailbox that has forwarding in place. If the message is sent by an internal sender **and** the forwarding method is [mailbox forwarding](https://docs.microsoft.com/exchange/recipients-in-exchange-online/manage-user-mailboxes/configure-email-forwarding) (also known as _SMTP forwarding_), the internal sender will get the NDR. The internal sender does not get an NDR if the forwarding occurred due to an inbox rule.

> That's fine, but the case of senders not getting an NDR if the method of forwarding to an external domain via an inbox rule is still valid.
> Also, it does seem like a bug or a design flaw since the email HAS been delivered to the mailbox—only the copy has not been delivered. In that case, if the box to Keep the email has been checked, I would expect the recipient to get an NDR if the forwarded email is blocked; if the box is not checked, for the sender to get an NDR.

I would suggest that you open a support case to see what they say.

**Comment by ayprof** [comment]
Thanks Chris, will do.

**Comment by chrisda** [comment]
Closing
