### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by ClaytonIT** [MicrosoftDocs/microsoft-365-docs#3679]
![image](https://user-images.githubusercontent.com/41170428/101701483-01155480-3a4d-11eb-9f5f-2bb22c3ade37.png)

[Noticed the missing L in the word only// Search text ="web-ony" 
Site Address: https://docs.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide
Thanks for all the great knowledge in a wonderfully fun database :-D ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a secure guest sharing environment](https://docs.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide#set-up-web-only-access-for-guest-users)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@ClaytonIT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3693

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ClaytonIT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
