### ISSUE TITLE
Duplicate related topic link

### ISSUE THREAD

**Issue by Crimsonfox89** [MicrosoftDocs/microsoft-365-docs#3681]
The two following links in the related topic section end up at the same location

[Managing Office 365 endpoints](https://docs.microsoft.com/en-us/microsoft-365/enterprise/managing-office-365-endpoints?view=o365-worldwide)

[Troubleshooting Office 365 connectivity](https://support.office.com/article/d4088321-1c89-4b96-9c99-54c75cae2e6d.aspx)

I suggest changing the second to the following link as I can't locate a suitable article that covers troubleshooting.

[Monitor Microsoft 365 connectivity](https://docs.microsoft.com/en-us/microsoft-365/enterprise/monitor-connectivity?view=o365-worldwide)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@Crimsonfox89 Thank you for your feedback. We have made changes to the related topics section in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3709

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Crimsonfox89 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
