### ISSUE TITLE
Missing guidance on how to

### ISSUE THREAD

**Issue by paulsilverstein** [MicrosoftDocs/microsoft-365-docs#3684]
Regarding this: An organization's administrator can opt in for location to be included in the network measurements used by this feature

How? Where? There should be guidance on how an org admin can opt in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d34c651f-db16-2fd8-502e-582b97e6140b
* Version Independent ID: 20c2dcba-da3b-a4ef-4593-7561d998748e
* Content: [Microsoft 365 Network Connectivity Location Services (preview) - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/office-365-network-mac-location-services?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/office-365-network-mac-location-services.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/office-365-network-mac-location-services.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please add your comment and help us in resolving this issue. Thanks.

**Comment by LauraWi** [comment]
More information is provided in the linked topics at the bottom of the article.
