### ISSUE TITLE
Training Reminders

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#3685]
How often are users reminded of training assigned to them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d7b1d53-4fd3-9bde-7c58-223525236f93
* Version Independent ID: 4700cbec-8554-6bc1-fe99-8d077e37b6bb
* Content: [Gain insights through Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-insights?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-insights.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-insights.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by chrisda** [comment]
@HarrisburgUSysAdmin, I'm told that users are reminded once a week but only after the training is overdue (still not completed past due date).

**Comment by chrisda** [comment]
Question answered. Closing
