### ISSUE TITLE
Missing Support Line for Bulgaria

### ISSUE THREAD

**Issue by ivaydesign** [MicrosoftDocs/microsoft-365-docs#3686]
Hello, 

I have bought a license key for Microsoft Office Pro-2016. For more than 30 days, I'm trying to add the license to the product 
but won't work. The supplier cannot resolve the issue. Same time I'm trying to resolve the issue by activating it via phone, but the phones given for Bulgaria Region even in this page are not responding. They forwarding the call to the server, which cannot be a place for support. I call 4- times already in the regular hours, and nobody respond on my call.

Again, I'm fighting to install, a license which I own for MS Office Pro 2016.
This page, and contacts/phone is not supporting the line with people/organization winch such issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef2273c-fbf5-b34d-19c3-c4a8fdbf2539
* Version Independent ID: 07eddc2c-a408-3f47-d056-5cf1bd95ca4e
* Content: [Support information for Bulgaria - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/bulgaria?view=o365-worldwide#phone-number)
* Content Source: [microsoft-365/admin/support/bulgaria.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/bulgaria.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@ivaydesign Thank you for your feedback. In order to check this with the internal support team about call routing, Could you please provide us the below details?

CC: @cmcatee-MSFT 

CFN/TFN/Customer dialing number :
ANI(Caller's number) 
Date of call:-
Time of call with time zone
Outgoing/incoming call :
The options you selected in the IVR:- : 
Call ID/interaction ID (if available):- 

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@ivaydesign Please do not post that information here. Please send it directly to me: cmcatee@microsoft.com

**Comment by cmcatee-MSFT** [comment]
@msbemba would you please email me?

**Comment by msbemba** [comment]
@cmcatee-MSFT Sorry I missed this. I don't have access to call this number, It is not connecting from India. @ivaydesign Were you able to send the details to cmcatee@microsoft.com ?

Thanks
Sri

**Comment by msbemba** [comment]
@ivaydesign I'm currently working with the author to see if we can get this information. Meanwhile, would you be able to share the below information with cmcatee@microsoft.com ?

CFN/TFN/Customer dialing number :
ANI(Caller's number)
Date of call:-
Time of call with time zone
Outgoing/incoming call :
The options you selected in the IVR:- :
Call ID/interaction ID (if available):-

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@msbemba I received the call info from @ivaydesign and have forwarded it internally for investigation. Thanks!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ivaydesign Hope it helped. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
