### ISSUE TITLE
Permissions for PowerShell

### ISSUE THREAD

**Issue by PJNield** [MicrosoftDocs/microsoft-365-docs#3695]
The document needs to indicate the Exchange Permissions ("Transport Hygiene") needed to access the PowerShell cmdlets to managed quarantined messages, and which role in Exchange has that included ("Hygiene Management").

The Quarantine role in Security and Compliance only provides access through Security and Complianc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an admin - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@PJNield, OK, done.

Thanks for the feedback.

Closing
