### ISSUE TITLE
Transparent PNG's in Dark Mode

### ISSUE THREAD

**Issue by tlourey** [MicrosoftDocs/microsoft-365-docs#3699]
Some of the PNG's on this page have transparent backgrounds but are items on the diagram are coloured assuming a white background. 

This one has a white background and is good: https://docs.microsoft.com/en-us/microsoft-365/media/fc87b8fd-a191-47a7-9704-1e445599813a.png?view=o365-worldwide
This one has a transparent background and is not good: https://docs.microsoft.com/en-us/microsoft-365/media/4d4c07cc-a928-42b8-9a54-6c3741380a33.png?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4fd73b-9632-b0c1-45cb-825f2f1a03dd
* Version Independent ID: 8aeca19b-cf40-33c1-b947-f951a58e9520
* Content: [Microsoft 365 network connectivity principles - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-network-connectivity-principles?view=o365-worldwide#BKMK_Principles)
* Content Source: [microsoft-365/enterprise/microsoft-365-network-connectivity-principles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-network-connectivity-principles.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by LauraWi** [comment]
Thanks for the feedback. As this is an aesthetic issue that does not negatively impact the technical accuracy of the article it is a low priority for a fix. I am closing the issue.
