### ISSUE TITLE
No Extra File Storage option

### ISSUE THREAD

**Issue by sganta** [MicrosoftDocs/microsoft-365-docs#3700]
I am trying to see how I can add additional storage to my Microsoft 365 account.  I followed the instructions on this page. However, I did not find "Office 365 Extra File Storage" under add-ons or other categories.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@sganta Thank you for your feedback. I'm able to see the Extra file storage option. There are a few pre requisites to be met before you could add this add-on. Could you please provide more information about your existing licenses?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sganta Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
