### ISSUE TITLE
Update IPv6 support in M365 documentation with latest information

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/microsoft-365-docs#3701]
This page is more than 2 years old, so likely needs to be updated to reflect changes in how M365 supports IPv6. Customers are asking for detail, but don't trust a 2 year old document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41916ef7-635a-80f9-914a-207040a3829e
* Version Independent ID: 1f372ebc-774b-a1f5-5e43-73b42f74b198
* Content: [IPv6 support in Office 365 services - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/ipv6-support?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/ipv6-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/ipv6-support.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by LauraWi** [comment]
Engineering initiated updates are pending.
