### ISSUE TITLE
"Turn on the Unified Audit Log" moved to admin centre called "Security"

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/microsoft-365-docs#3705]
"Turn on the Unified Audit Log" is moved to admin centre called "Security"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c17d605-af9d-3020-cde8-d808c918a24c
* Version Independent ID: 78e876f7-ea14-2f92-35d4-4e75f92e6166
* Content: [Increase threat protection - Microsoft 365 for Campaigns](https://docs.microsoft.com/en-us/microsoft-365/campaigns/m365-campaigns-increase-protection?view=o365-worldwide)
* Content Source: [microsoft-365/campaigns/m365-campaigns-increase-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/campaigns/m365-campaigns-increase-protection.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by yogkumgit** [comment]
#3704 duplicate, closing
