### ISSUE TITLE
"Disable or manage calendar sharing" moved 

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/microsoft-365-docs#3706]
"Disable or manage calendar sharing" moved to Settings -> Org Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c17d605-af9d-3020-cde8-d808c918a24c
* Version Independent ID: 78e876f7-ea14-2f92-35d4-4e75f92e6166
* Content: [Increase threat protection - Microsoft 365 for Campaigns](https://docs.microsoft.com/en-us/microsoft-365/campaigns/m365-campaigns-increase-protection?view=o365-worldwide)
* Content Source: [microsoft-365/campaigns/m365-campaigns-increase-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/campaigns/m365-campaigns-increase-protection.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@gb5757870 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3711

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gb5757870 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
