### ISSUE TITLE
Additional roles grant access to activity explorer

### ISSUE THREAD

**Issue by Wh00T** [MicrosoftDocs/microsoft-365-docs#3707]
The doc states:

> Data from Endpoint DLP can be viewed in Activity explorer. There are four roles that grant permission to activity explorer, the account you use for accessing the data must be a member of any one of them.
> 
> - Global admin
> - Compliance admin
> - Security admin
> - Compliance data admin

But also these roles grant access:
- Global reader
- Security reader
- Reports reader

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Wh00T Thank you for your feedback. I tested with the other three roles and was able to view details in activity explorer. I have modified the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3786

Thanks
Sri
