### ISSUE TITLE
EnableAntiSpoofEnforcement - EOP default anti-phishing policy settings

### ISSUE THREAD

**Issue by rafaelborter** [MicrosoftDocs/microsoft-365-docs#3713]
Hi, 

I can no longer set the EnableAntispoofEnforcement parameter on multiple O365 tenants.
**MS Docs**: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide#eop-default-anti-phishing-policy-settings
**Security feature name**: EnableAntispoofEnforcement

PowerShell (default policy):
PS C:\> Get-AntiPhishPolicy  | fl name, EnableAntispoofEnforcement
Name : Office365 AntiPhish Default

PS C:\> Set-AntiPhishPolicy -Identity "Office365 AntiPhish Default" -EnableAntiSpoofEnforcement $true
A parameter cannot be found that matches parameter name 'EnableAntiSpoofEnforcement'.
    + CategoryInfo          : InvalidArgument: (:) [Set-AntiPhishPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-AntiPhishPolicy
    + PSComputerName        : outlook.office365.com
PS C:\>

PowerShell (new policy):
PS C:\repos\isolutions.PowerShell\Cloud Security Communication\Security> New-AntiPhishPolicy -Name "TEST" -AdminDisplayName "TESTING" -EnableAntiSpoofEnforcement $true -AuthenticationFailAction MoveToJmf -EnableUnauthenticatedSender $true
A parameter cannot be found that matches parameter name 'EnableAntiSpoofEnforcement'.
    + CategoryInfo          : InvalidArgument: (:) [New-AntiPhishPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-AntiPhishPolicy
    + PSComputerName        : outlook.office365.com

Does the EnableAntispoofEnforcement parameter still exist or has it been removed?

Regards
Rafael Borter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, security baselines, baselines for EOP, baselines for Defender for Office 365 , set up Defender for Office 365 , set up EOP, configure Defender for Office 365, configure EOP, security configuration - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide#office-365-advanced-threat-protection-security)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@rafaelborter Thank you for your feedback. I was not able to use the parameter as well, I shall check with the product group/author and update the document accordingly.

@MSFTTracyP We are not able to use the parameter -EnableAntispoofEnforcement. I don't see any updates around removing this feature. Could you please help us verify if this parameter is available? I shall update the document accordingly.

Thanks
Sri

**Comment by SignorelliDenis** [comment]
@rafaelborter EnableAntispoofEnforcement has been renamed to EnableSpoofIntelligence

**Comment by rafaelborter** [comment]
@SignorelliDenis 
Great, I was now able to adjust the settings successfully.

@msbemba 
Can you please update the [documentation](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp?view=o365-worldwide#eop-default-anti-phishing-policy-settings)? Thank you very much.

**Comment by msbemba** [comment]
@MSFTTracyP I don't see any official announcement about the name change. Could you please confirm if EnableAntispoofEnforcemen has been renamed to EnableSpoofIntelligence? I can update the document accordingly once you confirm.

Thanks
Sri

**Comment by yogkumgit** [comment]
@MSFTTracyP Please reply our query. Thanks.

**Comment by chrisda** [comment]
@msbemba, @yogkumgit, I confirmed in a PROD (no flighting) E5 tenant that  _EnableAntispoofEnforcement_ is gone, and _EnableSpoofIntelligence_ exists. The cmdlet reference topics have been updated in the PowerShell repo per the earlier referenced 7001 pull request.

So, I updated the references in this topic, and in two other topics in the repo.

Thanks for the feedback.

Closing
