### ISSUE TITLE
Missing "Select a Report" dropdown?

### ISSUE THREAD

**Issue by ScottBeeson** [MicrosoftDocs/microsoft-365-docs#3715]
I do not see the "Select a report" dropdown as mentioned on this page.  The admin page I am on is https://admin.microsoft.com/Adminportal/Home?#/reportsUsage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70e9c6c-8b88-9be4-5ce7-90338685ce95
* Version Independent ID: 755db873-a694-b50c-9478-eeb979dcf4cc
* Content: [Microsoft 365 Reports in the admin center - Email apps usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/email-apps-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/email-apps-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/email-apps-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ScottBeeson Thank you for your feedback. There have been some changes recently and we will update the document accordingly.

@kwekuako The Email apps report is not available anymore under usage. Do you know if the product team is working on this or is this document is not relevant anymore?

Thanks
Sri

**Comment by Sirkkuw** [comment]
@msbemba Looking into this. Will let you know. Definitely looks like the UI has been updated.

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder, please resolve this. Thanks

**Comment by kwekuako** [comment]
@yogkumgit, looks like its been resolved. I don't see that text in the topic anymore.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ScottBeeson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
