### ISSUE TITLE
Add details about limitations for mailbox recover/restore if auto-expanding archive is active

### ISSUE THREAD

**Issue by testad** [MicrosoftDocs/microsoft-365-docs#3716]
According to[ this article and headline](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-auto-expanding-archives), restore and recover is not possible for inactive mailboxes with an auto-expanding archive. I suggest to add information about this under the headline "Before you enable auto-expanding archiving".

Many thanks,
PT
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a7c1600-c310-fb7f-7976-2025ee9256f3
* Version Independent ID: 9241081b-eabb-78a8-af86-2c0f27e7e671
* Content: [Enable unlimited archiving - Admin Help - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-unlimited-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by jonwbstr** [comment]
Yikes! thanks for sharing. Agreed, it would be very useful for this page to reference that article.

**Comment by markjjo** [comment]
@testad Article updated. Added bulleted item to "Before you begin" section about inactive mailbox limitations.
