### ISSUE TITLE
eDiscovery Output

### ISSUE THREAD

**Issue by brucemurchie** [MicrosoftDocs/microsoft-365-docs#3718]
Hi,

Reference the output of the content after running eDiscovery to generate a PST file from O365.

Poor explanation of the tools that are required and the process to generate an output.

Biggest issue is where is the PST file?????

I get local download of Export Summary, manifest, Results and trace. None of which I am interested in.

Where the hell is the PST?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f612d934-0811-53ad-14b9-e4d44eca9448
* Version Independent ID: 284b8ae6-51d5-7571-3f70-7824e34f94a8
* Content: [Export Content Search results - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-search-results?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/export-search-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-search-results.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@brucemurchie Depending on how you choose to export items to the PST, PST files would be exported to a folder that is a peer of the other exported items that you mentioned above. The name of this is "Exchange" (or maybe something different based on the PST export option you selected. Based on your explanation, it sounds like you might have exported the Export report and not the actual search results. To export the search results to a PST, click "Export results" (don't choose "Export report").

![image](https://user-images.githubusercontent.com/36746813/102125102-fcaabc00-3dfd-11eb-812d-1ef1ed6a2507.png)


![image](https://user-images.githubusercontent.com/36746813/102125915-38925100-3dff-11eb-8f63-8e8abae7c3dd.png)


If I'm misunderstanding the problem or if you continue to have issues, I would suggest you open a ticket with Microsoft Support.

**Comment by brucemurchie** [comment]
Mark,

Thank you for the prompt reply and clarification.

Yes that has resolved the issue,

Regards

Bruce

Bruce Murchie
Xenium Solutions Limited
Mobile Application Solution Providers
G-Cloud Supplier CCS Framework
+44 7802227837 UK
+61 449275520 Australia
www.xeniumsolutions.com<http://www.xeniumsolutions.com/>
