### ISSUE TITLE
Report Message submissions aren't actually shown in the admin center

### ISSUE THREAD

**Issue by GMZephyr** [MicrosoftDocs/microsoft-365-docs#3721]
Hi

Based on this article, submissions made by the Report Message Outlook add-in should be shown in the Admin Center, but they are not.  I am not sure where this issue originates.  Submissions that are done directly in the Admin Center do show up.

![image](https://user-images.githubusercontent.com/76010707/102129459-9aa58300-3e0c-11eb-8f23-7507f09e0ecc.png)
![image](https://user-images.githubusercontent.com/76010707/102129526-b7da5180-3e0c-11eb-8c25-5f68a06b3201.png)

Other than that, the article was exactly what I was looking for - I wasn't previously aware of this functionality, and was introduced to it by MS tech support.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Admin submissions - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@GMZephyr Thank you for your feedback. 

If you've deployed the Report Message add-in, or people use the built-in reporting in Outlook on the web, you can see what users are reporting on the User submissions tab.

In the Security & Compliance Center, go to Threat management > Submissions.

Select the User submissions tab, and then click New submission.

However, If there is a Custom policy to not report those to Microsoft, instead diverted to a Custom mailbox you may not be able to view the user submissions.

Please Navigate to https://protection.office.com/userSubmissionsReportMessage to check User submission policy and verify if the reports are forwarded to Microsoft. 

![image](https://user-images.githubusercontent.com/45987684/102997271-af8bc000-454a-11eb-96d0-37059fb3874d.png)


If this still doesn't work, I'd recommend reporting this issue/bug to Microsoft support via the need help option on the admin center.

Hope this helps!


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GMZephyr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GMZephyr** [comment]
Hi,
The submission policy is correct (Report To Microsoft) - this appears to be a bug, and I have created a support ticket.  Thanks for the help!
