### ISSUE TITLE
Created 10 years'retention policy with/without add-on license

### ISSUE THREAD

**Issue by ericburger-nl** [MicrosoftDocs/microsoft-365-docs#3724]
The FAQ says both "Any audit log data covered by a 10-year audit log retention policy that you create after general availability will be retained for 10 years." AND  "When the 10-year audit log retention add-on license is available in early 2021, you will need to purchase add-on licenses for users who's audit data is being retained by an existing 10-year audit retention policy." When creating a 10 years retention policy now (before early 2021), this suggests both that log data will be retained AND an additional license will be needed to retain. How can this be both true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027a1632-76a4-9e87-8376-c10ddfc3e116
* Version Independent ID: 10c72509-5d4a-25d3-caf8-361474f68cd8
* Content: [Advanced Audit in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/advanced-audit.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/advanced-audit.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ericburger-nl We made 10-yr audit log retention available before we rolled out the required licensing. When the licensing becomes available, customers will need to purchase it to remain in licensing compliance. In other words, audit records will be retained for 10 yrs regardless of whether user has appropriate add-on license. If you don't acquire the add-on license when they become available, you won't be in compliance with licensing requirements. I assume/hope more communication about this will be sent out when the add-on licenses become available for purchase.
