### ISSUE TITLE
Add regkey AlwaysUseMSOAuthForAutoDiscover

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/microsoft-365-docs#3725]
HKEY_CURRENT_USER\Software\Microsoft\Exchange AlwaysUseMSOAuthForAutoDiscover 0x1
https://docs.microsoft.com/en-us/outlook/troubleshoot/authentication/outlook-prompt-password-modern-authentication-enabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac88f29-99a5-317d-2686-cc9534194a19
* Version Independent ID: 753c4eff-ddb3-6261-35f9-4a60b65d7147
* Content: [Enable Modern Authentication for Office 2013 on Windows devices - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/enable-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/enable-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@trudolf-msft Thank you for the feedback. You are correct, we need to create or enable AlwaysUseMSOAuthForAutoDiscover in some scenarios. I have added this to the related article section via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3761

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @trudolf-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
