### ISSUE TITLE
MS Bookings: SMS for Maximum Number of Attendees > 1 Not working

### ISSUE THREAD

**Issue by lfzn2** [MicrosoftDocs/microsoft-365-docs#3726]
I am able to send and receive SMS without issue when the maximum number of attendees is set to 1 under Services.

However, when you set the maximum number of attendees to more than 1, then the text messages do not seem to go out.  I can not find any other way to modify this, but it seems consistent and reproducible on my system.   Is this feature in development?

**Comment by yogkumgit** [comment]
@lfzn2 Please mention which document we are referring to. Thanks

**Comment by msbemba** [comment]
@lfzn2 Thank you for your feedback. Are you referring to https://docs.microsoft.com/en-us/microsoft-365/bookings/define-service-offerings?view=o365-worldwide ?

Thanks
Sri

**Comment by msbemba** [comment]
@lfzn2 This sounds more like a bug to me as there are no restrictions to be able to send and receive SMS. I'd recommend you contact the support team via the need help section on the m365 admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@kwekuako Please add your comment and close this issue.

**Comment by kwekuako** [comment]
Not a content issue. Following up with product support.
