### ISSUE TITLE
No need to contact support when closing subscriptions with 25+ users

### ISSUE THREAD

**Issue by AlexV-P** [MicrosoftDocs/microsoft-365-docs#3727]
The documentation instructs users with subscriptions of over 25 users to contact support to cancel. On multiple occasions, the support team has been unaware of this advice and instructed me to simply reduce the number of subscriptions to below 25, then cancel online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a91e3ae5-842c-fb3d-8c27-d8001122aee8
* Version Independent ID: ddccec72-7088-4207-60cb-986a35becb67
* Content: [Cancel your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/cancel-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/cancel-your-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@AlexV-P Thank you for your feedback. You can reduce the number of licenses to below 25 and cancel the licenses, however, there are other retainers, security and technical reasons like Implications of data purge for all customers are why we would want customers to contact support. Support will explain the implications of canceling a subscription before asking you to reduce the count to less than 25.

Hope this helps!

CC: @cmcatee-MSFT 

Thanks
Sri

**Comment by AlexV-P** [comment]
Would it be worth updating the documentation to include these implications and explain that the next step is to reduce the license count?

**Comment by msbemba** [comment]
@AlexV-P Thank you for your feedback. I have added that information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3788

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AlexV-P Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
