### ISSUE TITLE
Docs are  not clear that just editing the Team description or Avatar would trigger naming policy. 

### ISSUE THREAD

**Issue by kzbierski** [MicrosoftDocs/microsoft-365-docs#3728]
Docs states that "It gets applied when a user creates a group and when group name or alias is edited for an existing group.". But it also is applied for existing teams when in Edit Team feature if the description/avatar are changed. That too triggers the Naming Policy as well. Even just clicking "Update" and not changing anything triggers it as well. That should be clearly defined not just "when group name or alias is edited".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b42caf5d-70e6-9898-7af2-91b5b5f4f9bd
* Version Independent ID: d73b64aa-cef0-4327-78f5-c2a53dbeb8c3
* Content: [Microsoft 365 groups naming policy](https://docs.microsoft.com/en-us/microsoft-365/solutions/groups-naming-policy?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/groups-naming-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/groups-naming-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@kzbierski Thank you for your feedback. We have made changes to the document and the same can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3803

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kzbierski Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
