### ISSUE TITLE
Read email in another user's mailbox should be called Full access

### ISSUE THREAD

**Issue by ACarlockAKA** [MicrosoftDocs/microsoft-365-docs#3729]
The "Read email in another user's mailbox" section should make it clear that this grants the "Full Access" mailbox permission.  and that "Full Access" grants Read and Modify permissions in the mailbox but not Send as or Send on behalf of. There's another GitHub comment about this from years ago that got off track because of how Full access works.  I would have commented there, but it's closed.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b9d613a-f990-4045-f0d3-273ecc827db7
* Version Independent ID: ef031919-5994-8d21-1f62-ee0db6f235b0
* Content: [Give mailbox permissions to another user - Admin Help - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user?redirectSourcePath=%252farticle%252fRead-email-from-another-user-s-mailbox-in-Office-365-cb3b6a8a-c6e8-4342-803c-3e54b6428cc2&view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ACarlockAKA Thank you for your feedback. I have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3762. Once the author Approves the PR, it takes 24-48 hours for the changes to reflect.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ACarlockAKA Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
