### ISSUE TITLE
Incorrect location for PS settings

### ISSUE THREAD

**Issue by carlyrevier** [MicrosoftDocs/microsoft-365-docs#3733]
In the bottom section, "Capability to opt out of people experiences," the instructions say to go to Settings > Org Settings > Reports. However, this is incorrect. This setting has been moved to Settings > Org Settings > Productivity Score.

Also, including information on how to turn off Productivity Score all together (including Endpoint Analytics) would be helpful. I can imagine a scenario where someone turns it on at an organization but then they decide they want to turn it off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf8d5bc-e77a-5db8-5686-1dcb5a5a96dc
* Version Independent ID: 9e49294a-e1b4-851c-8792-2cdf33927a74
* Content: [Microsoft Productivity Score - Privacy - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/productivity/privacy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/productivity/privacy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/productivity/privacy.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@carlyhublou Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3774

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @carlyrevier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
