### ISSUE TITLE
OCM is retired.

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/microsoft-365-docs#3734]
OCM was retired July 1, 2020.  Please remove this reference in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655829e4-741a-dc96-35f9-2f3df4de2633
* Version Independent ID: f1c9dc75-d781-322c-1d74-8e0f39fafd1e
* Content: [Migrate to Microsoft 365 Business from Office 365 E3 - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/migrate-from-e3?view=o365-worldwide)
* Content Source: [microsoft-365/business/migrate-from-e3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/migrate-from-e3.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@dgordonb Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3734

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dgordonb Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
