### ISSUE TITLE
9.25 is missing

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/microsoft-365-docs#3739]
I've a message where I have 9.25 as the reason (see screenshot). This article only list until 9.24 and I'm not able to identify the issue why the message was sent to the quarantine.

![image](https://user-images.githubusercontent.com/23408264/102319618-787e4300-3f7b-11eb-8d94-9985f04f656a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@myfope, I'm told that 9.25 is related to first contact by that sender as part of [impersonation protection and mailbox intelligence](https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#impersonation-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365). It's not that the message is necessarily phishing, it's just that this was the first message received from that sender.

The general consensus seems to be this value should be removed. Therefore, I'm also playing the all-encompassing trump card that's explained in the article:

> The X-Forefront-Antispam-Report header contains many different fields and values. Fields that aren't described in the table are used exclusively by the Microsoft anti-spam team for diagnostic purposes.

Thanks for the feedback.

Closing

**Comment by kfasick** [comment]
> it's just that this was the first message received from that sender.
This "first message received from that sender" tracks with what I see when we enable the Mail tip when senders are new that adds: "You don't often get email from...". That email has SFTY:9.25 - I searched looking for what it meant, too, and found this thread.
