### ISSUE TITLE
Clarify that settings from the Anti-Spam policy are still honored

### ISSUE THREAD

**Issue by FrankPlawetzki** [MicrosoftDocs/microsoft-365-docs#3740]
We should clarify that action taken on any message is determined by the setting configured in the antispam policy. Secure by default will not change that and messages with the high confidence phish action will just take effect as it normally would; although, we do recommend that tenants move to the quarantine experience.

**Comment by yogkumgit** [comment]
@FrankPlawetzki Please mention which document you are referring to. Thanks

**Comment by FrankPlawetzki** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-by-default?view=o365-worldwide

**Comment by FrankPlawetzki** [comment]
For clarification:
Although the documentation includes the sentence: "Email identified as high confidence phishing will be handled according to the anti-spam policy action." in my opinion it is not clear, that the anti-spam policy settings will still be honored and e.g. customers can still send high confidence phish to the junk mail folder instead of quarantine, although this is not recommended by Microsoft

**Comment by msbemba** [comment]
@FrankPlawetzki Thank you for your feedback. You are correct,  We have added that part in the document -- Anti-spam policies are still honored as secure by default is not a full takeover of your available options for high confidence phishing messages in anti-spam policies. Although we recommend Quarantine, the other actions that have always been available are still available (Move to Junk Email folder or Redirect to an email address).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @FrankPlawetzki Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
