### ISSUE TITLE
Need to add https://unpkg.com to required URLs for Microsoft Teams

### ISSUE THREAD

**Issue by erictechtips** [MicrosoftDocs/microsoft-365-docs#3744]
In order for the praise feature to work in Teams, Microsoft Teams has to reach out to endpoints such as https://unpkg.com/@microsoft/teams-js@1.3.6/dist/MicrosoftTeams.min.js   If this URL is not added to the list of required URLs in Teams, the praise feature in Microsoft Teams will not work.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@erictechtips Thank you for your feedback. I'll check with the author to confirm if this information can be added to the document.

Thanks
Sri

**Comment by msbemba** [comment]
@JoeDavies-MSFT I was able to test this feature on a new device without having to whitelist https://unpkg.com/@microsoft/teams-js@1.3.6/dist/MicrosoftTeams.min.js.

Let me know if this information is accurate so that we can add this to URLs.

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@erictechtips I have submitted this request to the product team that manages these endpoints for their consideration in a future update. Thanks so much for letting us know.
