### ISSUE TITLE
update info about Cloudflare Orange cloud setting

### ISSUE THREAD

**Issue by TomasHurtz** [MicrosoftDocs/microsoft-365-docs#3745]
YOU HAVE THIS:  Select the DNS Traffic icon (orange cloud) to bypass the Cloudflare servers.

IT SHOULD SAY THIS (to avoid confusion) 
Select the DNS ONLY icon (change orange cloud to grey) to bypass the Cloudflare servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6107c99-df0b-8a33-f291-086ea6fd5034
* Version Independent ID: 0ba87689-7a57-c3f8-af4b-3267c81b933d
* Content: [Create DNS records at Cloudflare for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@TomasHurtz Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3777

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TomasHurtz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
