### ISSUE TITLE
Identity Protection alerts are missing in Microsoft 365 Defender even if the integration with MCAS has been enabled

### ISSUE THREAD

**Issue by nitzdaniel** [MicrosoftDocs/microsoft-365-docs#3746]
Identity Protection can be integrated with MCAS to import those alerts into the MCAS solution. MCAS is a security provider and can synchronize alerts to Microsoft 365 Defender, except alerts delivered from the Identity Protection module into MCAS. 
It should be added as additional information that those alerts are not synchronized and need to be checked in MCAS separately.
BTW: Is there an ETA for this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12da25d4-df48-3219-cdb1-0ba1866f27d1
* Version Independent ID: 9b6242bb-caf4-e2b1-a99e-459a6b70e2c6
* Content: [Deploy services supported by Microsoft 365 Defender - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/deploy-supported-services?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/deploy-supported-services.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/deploy-supported-services.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by msbemba** [comment]
@nitzdaniel Thank you for your feedback. I tested this and was able to reproduce the scenario. I'll check with the author/PG to see if we have this in the roadmap.

@lomayor The alerts generated by identity protection are not found in Microsoft defender. Instead, it shows up only in Microsoft cloud app Security. Is this by design, if yes I can update the document accordingly. Also, Could we check with PG to see if this feature is going to be avialable anytime soon?

Thanks
Sri

**Comment by yogkumgit** [comment]
@lomayor Kindly answer this query. Thanks.

**Comment by nitzdaniel** [comment]
Hi, do we have an update on this? @yogkumgit

**Comment by yogkumgit** [comment]
@lomayor Gentle reminder, please help us in resolving this issue. Thanks

**Comment by lomayor** [comment]
@Dansimp, do we have someone who can take over this doc? I'm actually not sure if this is a support issue, i.e. M365D is failing to ingest IDP alerts from MCAS or this is an actual limitation that needs to be documented. If it is the latter, I think a this should be discussed in detail where we provide instructions on how to integrate the IDP alerts:

https://docs.microsoft.com/en-us/cloud-app-security/aadip-integration

**Comment by Dansimp** [comment]
This is a docs feedback issues, and we can't support product bugs or roadmap items. I will note that Defender for Identity are integrating into Microsoft 365 Defender, so identity-based alerts should be showing up in the portal now, provided you have the appropriate product license. Thank you.
