### ISSUE TITLE
Outlook 2013 Won't Authenticate Microsoft 365 Account, Missing Reg Keys

### ISSUE THREAD

**Issue by chrishill206** [MicrosoftDocs/microsoft-365-docs#3747]
Outlook 2013, Windows, M365 Business Basic. 
I have reviewed this note but I do not have these registry keys.
https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide

Any recommendations?

**Comment by msbemba** [comment]
@chrishill206 Thank you for your feedback. I tested this on a New machine with outlook 2013 and these registry keys do not exist. However, you can add the Key EnableADAL under HKCU\SOFTWARE\Microsoft\Office\15.0\Common\Identity\

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @chrishill206 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
