### ISSUE TITLE
Security Note

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/microsoft-365-docs#3749]
Should we be condoning the use of Basic authentication?  Not a good security practice.

$UserCredential = Get-Credential
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell-liveid -Credential $UserCredential -Authentication Basic -AllowRedirection
Import-PSSession $Session -DisableNameChecking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97efdb7a-efb0-f786-b901-d64d055efd5a
* Version Independent ID: 559ce33c-b1e2-966f-62a7-55f226a97477
* Content: [Configure permissions filtering for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/permissions-filtering-for-content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/permissions-filtering-for-content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/permissions-filtering-for-content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@r-milne Topic will be updated; will remove the connection instructions and point to topic on connecting to powershell using modern auth.
