### ISSUE TITLE
Update documention on effects of disabling spoof intelligence

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/microsoft-365-docs#3752]
Disabling spoof intelligence only disables implicit spoof protection. So DMARC=fail action=reject/quarantine would NOT be affected. It would be good to update the article to clarify it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide#spoof-settings)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pawp81, OK. Done.

Thanks for the feedback.

Closing
