### ISSUE TITLE
Folders Not Clearing, even when all steps are followed

### ISSUE THREAD

**Issue by 000111al** [MicrosoftDocs/microsoft-365-docs#3753]
[Enter feedback here]
During step 5, it is mentioned that you should be able to clear the /Purges, /SubstrateHolds, and /DiscoveryHolds folders, however, when you run the New-ComplianceSearchAction on searches tied to these folders, the files don't actually get removed from the folders. The commands look like they run correctly, but no items are removed. 

Best
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the Recoverable Items folder of cloud mailbox's on hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@000111al You have to make sure that all holds/retention policies are removed from the mailbox, include those explicitly assigned and those that are part of an org-wide or service-wide policy. This includes any retention policy for Teams messages. Step 3 lists the different hold types, including delay hold. If necessary, would suggest you open a support ticket with MS Support for assistance.
