### ISSUE TITLE
First table in "Microsoft SharePoint Syntex adoption: Get started" page confusing, misleading, wrong?

### ISSUE THREAD

**Issue by mcox13579** [MicrosoftDocs/microsoft-365-docs#3755]
Trying to get an understanding of how Microsoft Syntex can be applied in business intranet and content management and this page is vague, confusing and seems like something got cut/copied/pasted wrong with that first table.
[Enter feedback here]
![image](https://user-images.githubusercontent.com/12144220/102566840-2a5d6280-4095-11eb-928c-5ae1687e5d05.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ccad8b2-6373-57f2-2bcf-f88e288bfd88
* Version Independent ID: 8508430c-5dff-c69a-497a-9895e485e63d
* Content: [Microsoft SharePoint Syntex adoption: Get started](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/adoption-getstarted#document-understanding-scenario-example)
* Content Source: [microsoft-365/contentunderstanding/adoption-getstarted.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/adoption-getstarted.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by samanro** [comment]
Thanks for letting me know. I've removed the stray extra cell in the right and changed to "structured" documents. Pushing out the fix today.

**Comment by yogkumgit** [comment]
@samanro Thank you very much for updating the documentation. @mcox13579 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by amondelloSP** [comment]
HI @yogkumgit  I find this VERY confusing: 

Uses AI Builder credits - 1M credits = 2000 pages; Consumption is about 2000 invoices=2 units. 

The first part of the sentence says to me that ingesting 2,000 document pages uses up 1 million credits.
The second part is a mystery - what do "Units" have to do with pages or credits? 

Can you please clarify? Thank you!

**Comment by samanro** [comment]
Hi - thanks again for your feedback. I have updated again, and included a link to the AI Builder explanations of credits and units. Hope that helps.
