### ISSUE TITLE
Common approaches and negative impacts

### ISSUE THREAD

**Issue by jvedmls** [MicrosoftDocs/microsoft-365-docs#3756]
The section regarding Some common approaches and their negative impacts should be better organized or defined as its own section - it is easy to mistake the common approaches as recommended policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jvedmls Thank you for your feedback. I reviewed the document and found that the section "Some common approaches and their negative impacts" is followed by "Successful Patterns" in which we have stated "In contrast, here are some recommendations in encouraging password diversity" So I don't think users would get confused between these two.

Hope this helps! 

CC: @kwekuako 
@yogkumgit There are no changes required in the document, We can close this issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jvedmls Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
