### ISSUE TITLE
Availability Key

### ISSUE THREAD

**Issue by fklx** [MicrosoftDocs/microsoft-365-docs#3757]
The page is referencing the "Availability Key" page - which doesn't contain any information if and how CMK encryption at the tenant level is also affected by the Availability Key. Would be great to clarify. 

Thank you FKALECK@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18803bfa-118a-09ee-947b-abf1ee996b7a
* Version Independent ID: 87179b6d-d917-1aa9-259a-6f2de072c049
* Content: [Customer Key for Microsoft 365 at the tenant level (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-tenant-level?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-tenant-level.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-tenant-level.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help in resolving this issue. Thanks.

**Comment by KCCross** [comment]
Feedback noted as part of public preview. We have much more story to tell about how the new coverage is woven into the existing Customer Key story. Thank you for taking the time to send this.
