### ISSUE TITLE
Where is data stored in a multi-geo scenario? 

### ISSUE THREAD

**Issue by MikeParker365** [MicrosoftDocs/microsoft-365-docs#3758]
The FAQ "Where is the cloud-based storage for on-premises users located?" says that Cloud-based storage is provisioned in the same datacenter as your organization. What does this mean in the context of multi-geo? Is the PDL for the user honoured, or are all Cloud-based storage mailboxes stored in the central tenant location? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0bb4d7-d9fa-ae92-d3ca-246147d1434a
* Version Independent ID: 7ba20db3-55e2-3d29-2d6c-6f68a6b577a8
* Content: [Search for Teams chat data for on-premises users - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@MikeParker365 Thank you for your feedback. I'm sure the PDL is honored. However,  I'm working with the author about this and will update you shortly.


Thanks
Sri

**Comment by msbemba** [comment]
Greetings @markjjo 

The document states that Cloud-based storage is provisioned in the same datacenter as your organization.  I could not find any reference materials related to the Data stored in a multi-geo scenario. Afaik, the PDL for individual users is honoured in a multi-geo scenario. Could you please confirm this so that I can add more information to the document?

Thanks
Sri

**Comment by yogkumgit** [comment]
@markjjo

**Comment by markjjo** [comment]
@MikeParker365 @msbemba You are both correct that cloud-based storage for on-premises users honors the PDL, **regardless of the geo-configuration**. In other words, if multi-geo or not, data is stored in PDL. I'm sure you both know this (I didn't) but the PreferredDataLocation (PDL) attribute in AAD is forward-synced to EXO/cloud as MailboxRegion. 

@msbemba If you want to update the article and comment me on the PR I will review and merge. Thanks very much.

**Comment by msbemba** [comment]
@markjjo Thank you so much for confirming. I have added this scenario to the FAQ section via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3906

Thanks
Sri
