### ISSUE TITLE
Examples missing for MFA with New-CsOnlineSession (Module MicrosoftTeams)

### ISSUE THREAD

**Issue by DEberhardt** [MicrosoftDocs/microsoft-365-docs#3759]
Hello,

apologies for the mess on this issue, I have since figured out most of what I need, however one element is still remaining:

`New-CsOnlineSession` cannot be called with the -Credential parameter if MFA is to be used.
Calling the command without Parameters helps and allows use for MFA, however it does not allow to pre-fill the Username anymore, I am trying to get this re-evaluated with https://github.com/MicrosoftDocs/office-docs-powershell/issues/6997

I propose to change the example for MFA as follows:

```
$acctName="<UPN of the account, such as belindan@litwareinc.onmicrosoft.com>"
$orgName="<for example, litwareinc for litwareinc.onmicrosoft.com>"
#Azure Active Directory
Connect-AzureAD
#SharePoint Online
Connect-SPOService -Url https://$orgName-admin.sharepoint.com
#Skype for Business Online
Import-Module MicrosoftTeams
$sfboSession = New-CsOnlineSession
Import-PSSession $sfboSession
#Exchange Online
Import-Module ExchangeOnlineManagement
Connect-ExchangeOnline -UserPrincipalName $acctName -ShowProgress $true
```

The New-CsOnlineSession command now calls `Connect-MicrosoftTeams` and connects to SkypeOnline **and** Teams 👍 

I understand that the command was added to the Teams Module for backward compatibility, but is there a plan for `Connect-MicrosoftTeams -AccountId $acctName` to also support establishing both connections going forward? (If so, it would solve my request regarding the Username Parameter)

What is the plan for administering the Teams backend (i.E. CsOnline) come FEB 2021 when the Skype Online Connector is phased out? Will these commands be available natively through connecting to MicrosoftTeams using `Connect-MicrosoftTeams`?
Or will the method be the same (New-CsOnlineSession)?

We need to plan for this in the coming months as we need to update all our Scripts to work with the new Module and need clarity on this topic. The more information the better. :)

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6adeef66-5e54-ba2f-37ac-c1898ef942c6
* Version Independent ID: f8a6eda6-b300-dc76-4392-9aeb6c532822
* Content: [Connect to all Microsoft 365 services in a single PowerShell window - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by DEberhardt** [comment]
To drive the point home, here is the result running the following lines:

```
$credential = Get-Credential

Connect-AzureAD -Credential $credential

Import-Module MicrosoftTeams -Force #Added Force as it is fickle!
$sfboSession = New-CsOnlineSession -Credential $credential
Import-PSSession $sfboSession

#Import-Module MicrosoftTeams
Connect-MicrosoftTeams -Credential $credential 

```

Result:
```
One or more errors occurred. (raised by: Connect-AzureAD)
AADSTS50076: Due to a configuration change made by your administrator, or because you mov
ed to a new location, you must use multi-factor authentication to access '00000002-0000-0
000-c000-000000000000'.
Trace ID: c0586140-c6d0-4a35-874b-fad5904c2900
Correlation ID: 249f0ffb-ea40-4470-bdc9-399fd9246da9
Timestamp: 2020-12-19 11:19:53Z (raised by: Connect-AzureAD)
Response status code does not indicate success: 400 (BadRequest). (raised by: Connect-Azu
reAD)
{"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration 
change made by your administrator, or because you moved to a new location, you must use m
ulti-factor authentication to access '00000002-0000-0000-c000-000000000000'.\r\nTrace ID:
 c0586140-c6d0-4a35-874b-fad5904c2900\r\nCorrelation ID: 249f0ffb-ea40-4470-bdc9-399fd924
6da9\r\nTimestamp: 2020-12-19 11:19:53Z","error_codes":[50076],"timestamp":"2020-12-19 11
:19:53Z","trace_id":"c0586140-c6d0-4a35-874b-fad5904c2900","correlation_id":"249f0ffb-ea4
0-4470-bdc9-399fd9246da9","error_uri":"https://login.microsoftonline.com/error?code=50076
","suberror":"basic_action"}: Unknown error (raised by: Connect-AzureAD)
{"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration 
change made by your administrator, or because you moved to a new location, you must use m
ulti-factor authentication to access '00000002-0000-0000-c000-000000000000'.\r\nTrace ID:
 c0586140-c6d0-4a35-874b-fad5904c2900\r\nCorrelation ID: 249f0ffb-ea40-4470-bdc9-399fd924
6da9\r\nTimestamp: 2020-12-19 11:19:53Z","error_codes":[50076],"timestamp":"2020-12-19 11
:19:53Z","trace_id":"c0586140-c6d0-4a35-874b-fad5904c2900","correlation_id":"249f0ffb-ea4
0-4470-bdc9-399fd9246da9","error_uri":"https://login.microsoftonline.com/error?code=50076
","suberror":"basic_action"}: Unknown error (raised by: Connect-AzureAD)
One or more errors occurred. (raised by: Connect-AzureAD)
New-CsOnlineSession : Command Connect-MicrosoftTeams failed; One or more errors 
occurred.
At line:5 char:1
+ $sfboSession = New-CsOnlineSession -Credential $credential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-CsOnlineSession], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Teams.ConfigAPI.Cmdlets.SfbOnl 
   ine.CsSession.NewCsOnlineSession
```

**Comment by DEberhardt** [comment]
My current working Script is `Connect-Me -UserName $Username` (Module: TeamsFunctions) which does the following:

```
# By default only the first two are executed:
Connect-SkypeOnline -UserName $Username 
Connect-AzureAD -AccountId $Username
# Additionally it can also connect to these two:
Connect-MicrosoftTeams -AccountId $Username
Connect-ExchangeOnline -UserPrincipalName $Username -ShowProgress:$true -ShowBanner:$false
```

Connect-SkypeOnline does work with v6 and v7 of the SkypeOnlineConnector (v6 used the `-Credential` parameter available now), whereas v7 has also `-UserName` available...) but assuming the functionality of the newest Connector would be made available in the MicrosoftTeams Module, I would have expected it to run like this:

`New-CsOnlineSession -UserName $UserName `

**Comment by DEberhardt** [comment]
Workaround / proposed Example:

Skype & Teams put together in reverse order. This enables Single-Sign-on for Skype, however, if connected to multiple tenants, a Popup is still shown by New-CsOnlineSession because a Username cannot be passed to the command

```
$acctName="<UPN of the account, such as belindan@litwareinc.onmicrosoft.com>"
$orgName="<for example, litwareinc for litwareinc.onmicrosoft.com>"
#Azure Active Directory
Connect-AzureAD -AccountId $acctName
#SharePoint Online
Connect-SPOService -Url https://$orgName-admin.sharepoint.com
#Exchange Online
Import-Module ExchangeOnlineManagement
Connect-ExchangeOnline -UserPrincipalName $acctName -ShowProgress $true
#Teams & Skype for Business Online
Import-Module MicrosoftTeams
Connect-MicrosoftTeams -AccountId $acctName
$sfboSession = New-CsOnlineSession
Import-PSSession $sfboSession
```

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please add your comment and guide us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@DEberhardt I have updated the article with your suggestions and the results of additional testing. Thanks so much for your time and effort to help improve this content.
