### ISSUE TITLE
Symmetrical requirement for single policy that allows two Segments?

### ISSUE THREAD

**Issue by Ads-Khan** [MicrosoftDocs/microsoft-365-docs#3763]
I am trying to deploy Information Barriers in our dev environment.

Below is an example policy definition:

```
#  Wall-A can talk to Wall-C but not Wall-B

New-InformationBarrierPolicy -Name "Wall-A" -SegmentsAllowed "Wall-A", "Wall-C" -State Inactive -AssignedSegment "Wall-A"

Start-InformationBarriersPoliciesApplication
```

Trying to start an application instance states I must have a symmetrical policy but I have not defined any blocked segments?

**Comment by yogkumgit** [comment]
@chrfox Can you please help us here with comment. Thanks

**Comment by chrfox** [comment]
Please contact Microsoft Technical support
