### ISSUE TITLE
Spoof Intelligence - Anti-Phishing (Not Spam) - Information missing?

### ISSUE THREAD

**Issue by hugo-costa** [MicrosoftDocs/microsoft-365-docs#3764]
Hi,

This article mentions about managing spoof intelligence in spam but not in Anti-Phishing.

I notice that when following the steps to see the spoof intelligence list in Anti-Span and reviewing the list from the dashboard:
https://protection.office.com/spoofintelligence

The lists of domains are see here are completely different to the list in which can be viewed by the in the anti-spam policy section. Is this documented somewhere else? (Apologies if I have missed it.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c0cbdb-062e-08e1-7c7c-cedab550f01b
* Version Independent ID: 2791a840-3284-bc0d-7b9e-026b852797e6
* Content: [Configure spoof intelligence - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/learn-about-spoof-intelligence?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@hugo-costa Thank you for your feedback. You are correct! The Spoofintelligence insight in Microsoft defender  is different and more details about it can be found here - https://docs.microsoft.com/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight?view=o365-worldwide

Hope this helps!

@yogkumgit There are no changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hugo-costa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
