### ISSUE TITLE
Failed script

### ISSUE THREAD

**Issue by BryanAdvisicon** [MicrosoftDocs/microsoft-365-docs#3765]
This script fails because it cannot find  The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@BryanAdvisicon Thank you for your feedback. I tested this script and I was able to run this cmdlet successfully. Could you please confirm if you connected to AzureAD using Connect-AzureAD before you run this cmdlet?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @BryanAdvisicon Hope this comment is helpful for you, we appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue. If you see a documentation update is required, please feel free to reopen this issue. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
