### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Mark-Cates** [MicrosoftDocs/microsoft-365-docs#3766]
What are the requirements for using Tenant switcher?  We have a customer setup with our partner information in their 365 subscription, but we do not see the Tenant switcher option on our admin side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b378de4-ca71-a16b-6669-369e3e3ff9d4
* Version Independent ID: 1a1a6ec6-8c04-2172-7afa-49d268191687
* Content: [Manage multiple tenants - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/multi-tenant/manage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/multi-tenant/manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/multi-tenant/manage.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@Mark-Cates Thank you for your feedback. The requirements are that If you have been designated partner of record (Associated Partner) for a Microsoft cloud org, you will see a new double-arrow switcher icon in the upper left-hand corner of the Microsoft 365 admin center next to the org’s name. If you meet the requirement, I'd recommend you to raise a support request with the partner team to ensure this feature is made available for your tenant.  Once this feature is available, you will see a double-arrow switcher icon next to your org's name.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Mark-Cates Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Mark-Cates** [comment]
"If you have been designated partner of record (Associated Partner) for a Microsoft cloud org"

Unfortunately, there seems to be more to it than that so I plan on submitting a support request. We are definitly listed as "authorized to work with your organization"

But the switch option still doesn't show up.

thanks

**Comment by msbemba** [comment]
@Mark-Cates Thank you for the update. Please go ahead with your plan and submit a support request. Do let us know if there are any changes required in the document.

Thanks
Sri
