### ISSUE TITLE
Conflicting information about On-Premises resource authentication

### ISSUE THREAD

**Issue by ACarlockAKA** [MicrosoftDocs/microsoft-365-docs#3769]
The first paragraph states "You can also allow access to on-premises resources like line of business (LOB) apps, file shares, and printers. To allow access, use Azure AD Connect to synchronize your on-premises Active Directory with Azure Active Directory."  But then the last section states "Users won't be able to authenticate to applications that depend on Active Directory authentication. Evaluate the legacy app and consider updating to an app that uses modern Auth, if possible."  These two statements seem to conflict.  Please remove the incorrect statement or clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ba9775-1242-af4d-a9c0-8979cc5d57dc
* Version Independent ID: 5063400b-fe96-79f4-e37f-6c89e26ee9d0
* Content: [Access on-premises resources from an Azure AD-joined device in Microsoft 365 Business - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/access-resources?view=o365-worldwide)
* Content Source: [microsoft-365/business/access-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/access-resources.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@ACarlockAKA Thank you for your feedback. Apps and resources that depend on Active Directory machine authentication don't work because Azure AD joined devices don't have a computer object in AD.I have updated the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3802

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ACarlockAKA Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
