### ISSUE TITLE
Missing protocol information

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/microsoft-365-docs#3770]
Some customers require also protocol information (HTTP, SMTP, IMAP, etc.).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@paulomorgado Thank you for your feedback. We have added a link to a related document at the bottom of this page for reference. PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3800

Thanks
Sri

**Comment by paulomorgado** [comment]
I'm sorry, @msbemba, but there must be more than SMTP, POP and IMAP protocols in there.

This is the list I compiled from [IANA](https://www.iana.org/assignments/service-names-port-numbers):

Port Number|Transport Protocol|Service Name|Description
-:|--|--|--
25|tcp|smtp|Simple Mail Transfer
80|tcp|http|World Wide Web HTTP
80|tcp|www|World Wide Web HTTP
80|tcp|www-http|World Wide Web HTTP
143|tcp|imap|Internet Message Access Protocol
443|tcp|https|http protocol over TLS/SSL
587|tcp|submission|Message Submission
993|tcp|imaps|IMAP over TLS protocol
995|tcp|pop3s|POP3 over TLS protocol
3478|udp|stun|Session Traversal Utilities for NAT (STUN) port
3478|udp|turn|TURN over UDP
3478|udp|stun-behavior|STUN Behavior Discovery over UDP
3479|udp|twrpc|2Wire RPC
3480|udp|plethora|Secure Virtual Workspace
3481|udp|cleanerliverc|CleanerLive remote ctrl

**Comment by msbemba** [comment]
@JoeDavies-MSFT These are some common protocols with descriptions and port numbers. Let me know if this can be added to the document.

Thanks
Sri

**Comment by paulomorgado** [comment]
Like I said, some customers require that information because they also filter protocols.

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please guide us. Thanks

**Comment by JoeDavies-MSFT** [comment]
@paulomorgado   We can add a link to https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml at the bottom of the article. We cannot add protocol names to each of the TCP or UDP port numbers in each of the tables.

**Comment by msbemba** [comment]
Thank you @JoeDavies-MSFT . I have added it to the related topics via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3925

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @paulomorgado Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
