### ISSUE TITLE
Possibility to customize M365 Group expiration policy Email content and logo

### ISSUE THREAD

**Issue by gurubn** [MicrosoftDocs/microsoft-365-docs#3771]
Microsoft-365-groups-expiration-policy is fantastic feature . Is it possible to customize the email which is sent part of expiration ?. We have a need to add additional information inside email which is sent. Also possibility to add logo would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979f0a6e-be32-af1e-5724-d1104ebe3ef5
* Version Independent ID: cb9b993a-2224-5bb8-64b8-d1afa7a71c8e
* Content: [Microsoft 365 group expiration policy](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-groups-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@gurubn Thank you for your feedback. While I don't think this is possible, I'll test this and provide you an update.

Thanks
Sri

**Comment by msbemba** [comment]
@gurubn Thank you for your feedback. This is currently not possible and we have a UserVoice open for this -https://office365.uservoice.com/forums/286611-microsoft-365-groups/suggestions/20487847-customize-group-expiration-email and the product group is already looking at a few options to see how we can solve this problem.

@yogkumgit There are no changes in the document. This issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @gurubn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
