### ISSUE TITLE
Support for list item view event

### ISSUE THREAD

**Issue by takawazo** [MicrosoftDocs/microsoft-365-docs#3772]
M365 doesn't support list item view events in SharePoint currently, but I found it actually shows list item view event (ListItemViewed) which shows the access record to the specific list item.  (Only modern UI)
Does it support list item view events and this document hasn't been updated yet ? or is it in preview (or rolling out) stage ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#sharepoint-list-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@takawazo It might be that we need to added this event to the documentation. Can you email me a ListItemViewed audit record to my corp account (including the RecordType enum value) and the search you ran to return it and I will try to follow up with the SPO engineering team.
