### ISSUE TITLE
Cannot perform migration due to missing endpoint in the source tenant

### ISSUE THREAD

**Issue by GRJ78** [MicrosoftDocs/microsoft-365-docs#3778]
Hi there,

I have followed the process described in the documentation and was successful. Even the verification attempts with the PowerShell returned the correct results just like depicted in the documentation.
Nonetheless, I cannot perform the migration because the endpoint is created just in the source tenant.
Basically, I am using the new Exchange Admin Center in the source tenant to perform the move and I am asked for an endpoint.
In the documentation there is a reference to an endpoint only with respect to the target tenant.
Is the procedure supposed to create an endpoint in the source tenant as well?
If not, how could I get around the issue of the missing endpoint in the source tenant?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@GRJ78 Thank you for your feedback. The endpoint is supposed to be created only in the target as this is a pull move. You can use the PS cmdlet Get-MigrationEndpoint Idenityoftheendpoint | fl Identity, RemoteTenant, ApplicationId, AppSecretKeyVaultUrl to check.

I'd recommend contacting Support via the Need help section on the admin center to assist you in creating the correct endpoints and organization relationship.

Thanks
Sri

**Comment by GRJ78** [comment]
Hi Sri,

Thanks for that information. The organizational relationships are in place as is the endpoint in the target tenant. What I was doing wrong is that I was trying to initiate the migration from the admin portal of the source tenant. I tried to do the same from the target tenant and it is working.
Nonetheless, I will have to contact support since the migration batch got stuck at "syncing" status.

**Comment by msbemba** [comment]
@GRJ78 Thank you for the update. Sometimes the syncing state could also be due to throttling, so support can help increase the limit. 

@yogkumgit There are no changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GRJ78 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
