### ISSUE TITLE
No endpoint created in the source tenant

### ISSUE THREAD

**Issue by GRJ78** [MicrosoftDocs/microsoft-365-docs#3779]
Hi there,

I have followed the process of preparing he tenants as described in the documentation.
I have even verified the results as mentioned using PowerShell.
Everything seems to be correct.
Still I am not able to perform any migration as it asks for an endpoint.
I am trying to perform the migration using the new Exchange Admin Center.
In the documentation is stated that the endpoint is created in the target tenant. In my case I checked and it is there as well.
Nevertheless, in the source tenant no endpoint was created. Is this expected behavior?
If not, what needs to be done in order to have this rectified so that I can perform the migration?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@GRJ78 Thank you for your feedback. The source tenant does not need an endpoint. however, it needs to have an Organizationrelationship setup.

Use the PS cmdlets in both source and target to check if the organization relationships in both source and target tenants and migration endpoint in the target were created successfully.

https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#verify-setup

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GRJ78 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
