### ISSUE TITLE
the no-junk e-mailaddress is wrong on this page

### ISSUE THREAD

**Issue by andydedeckker** [MicrosoftDocs/microsoft-365-docs#3780]
The no-junk e-mailaddress for the false positives should be not_junk@office365.microsoft.com instead of false_positive@messaging.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88f35e41-4289-a328-cea0-a71f4862c424
* Version Independent ID: c60b5e14-0a43-d9cb-9d98-65cd82910be5
* Content: [Use mail flow rules to see what your users are reporting to Microsoft - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-mail-flow-rules-to-see-what-your-users-are-reporting-to-microsoft?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-mail-flow-rules-to-see-what-your-users-are-reporting-to-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-mail-flow-rules-to-see-what-your-users-are-reporting-to-microsoft.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@andydedeckker Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3799

Thanks
Sri

**Comment by chrisda** [comment]
PR #3799 merged. Thanks for the feedback.

Closing
