### ISSUE TITLE
Unable to set the ExchangeGUID if Exchange Hybrid env is not present

### ISSUE THREAD

**Issue by AlfredoLarracuente** [MicrosoftDocs/microsoft-365-docs#3783]
IMHO, the procedure as written in the article must specify that an Exchange Hybrid environment is necessary as there's no way to pre-stage a mailbox in cloud only environment with a specific ExchangeGUID matching the source mailbox or change it afterwards. If I'm missing something, or if there's a way to accomplish this, please advise. Look forward to the final release of this much needed solution.

This is in reference to article: https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide
 
Happy holidays!

**Comment by msbemba** [comment]
@AlfredoLarracuente Thank you for your feedback. For any mailbox moving from a source organization, you must provision a MailUser object in the Target organization: The ExchangeGUID needs to be set on the new mail user object in the target tenant. You can use Set-MailUser -identity abcd@contoso.com -Exchangeguid ***

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AlfredoLarracuente Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
