### ISSUE TITLE
Pay attention on upper-/lower-case

### ISSUE THREAD

**Issue by LudwigWurmannstaetter** [MicrosoftDocs/microsoft-365-docs#3785]
When one is doing the Validation on the DKE Service, thoroughly pay attention you are using the the right case on the Key Name. In the appsettings.json you create a Name for your Key. This name will be used when doing the Validation step, either by browsing to your DKE Server - **https://Your-Server/Your-Key-Name** or by using the Script **key_store_tester.ps1 https://Your-Server/Your-Key-Name**. In both cases the Key Name needs to be provided in exactly the same way as in the appsettings.json.
Errors:
Browse to the Site: You will see something that start with "{"ClassName":"Sys...." instead of the Key "{"key":{"kty":"RSA","n":"3mHAFFj....."
When using the Script it fails with a red line saying "Validation failure: Unable to access the provided url Bad Request" instead of a green line saying "Validation successful!"

Lastly, the same URL will be used when creating a Label for DKE usage, the label fails as well, when the Key Name is not exactly as it is in the appsettings.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide#register-your-key-store)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@LudwigWurmannstaetter Thank you for your feedback. We have added a note to the section mentioning the importance. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3798

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @LudwigWurmannstaetter Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
