### ISSUE TITLE
How to Identify in Audit Logs if the emails are deleted by User or by Retention Policy

### ISSUE THREAD

**Issue by shrikantdatke** [MicrosoftDocs/microsoft-365-docs#3787]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1c2e44-357c-8096-5bdf-40e205778ded
* Version Independent ID: 19c7b5d9-1e0c-501b-7b70-df5aab48b36e
* Content: [Learn about retention for Exchange - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-exchange?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-exchange.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by shrikantdatke** [comment]
Hi Team,

I have created an Email Deletion Policy from Compliance Portal to Delete Emails that are 1 day Old.

The policy is active and emails are deleted and sent to the "Recoverable Items" folder. 

Now I am querying the Audit logs to find out all emails deleted by the policy and not by the individual user, how can I identify the same ?

**Comment by markjjo** [comment]
@shrikantdatke I'm not 100% sure that email deleted by a deletion policy generate audit records, but I would suggest that you search for [SoftDelete and HardDelete mailbox activities](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#exchange-mailbox-activities) (leaving the user field blank to return all records in the date range) and then export the audit search results to a csv file. Then format the csv file using Power Query (as described here: https://docs.microsoft.com/en-us/microsoft-365/compliance/export-view-audit-log-records?view=o365-worldwide) . Then you could look at/filter records that might indicate the the items were deleted as the results of a deletion policy.
