### ISSUE TITLE
Typo for this doc: https://docs.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-a-license-to-a-guest-user

### ISSUE THREAD

**Issue by clfilipe** [MicrosoftDocs/microsoft-365-docs#3790]
_"to learn about **guess** users"_. It is not "guess" but "guest" users.

![image](https://user-images.githubusercontent.com/44497350/103012312-51071780-4533-11eb-8c72-85ea98ab6c50.png)

Please correct this typo. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42a261b-afb1-e8d4-e61d-c9d30cb71a00
* Version Independent ID: 3649a463-b7d6-104a-608f-cfcf16b66cb5
* Content: [Assign licenses to users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/assign-licenses-to-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/assign-licenses-to-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@clfilipe Thank you for the feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3797

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @clfilipe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
