### ISSUE TITLE
Conditional Access location needs updated 

### ISSUE THREAD

**Issue by AdamNSTA** [MicrosoftDocs/microsoft-365-docs#3791]
[Enter feedback here]

The Conditional Access page is now under the Security blade.

Azure Active Directory > Security > Conditional Access

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 965d1d2f-81dd-8057-5a13-4f75cfe0c1f7
* Version Independent ID: 7bd2fc7a-93dd-9081-6d98-3e28fdebe342
* Content: [Set up conditional access policies - Microsoft 365 for Campaigns](https://docs.microsoft.com/en-us/microsoft-365/campaigns/m365-campaigns-conditional-access?view=o365-worldwide)
* Content Source: [microsoft-365/campaigns/m365-campaigns-conditional-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/campaigns/m365-campaigns-conditional-access.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AdamNSTA** [comment]
https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3794

**Comment by kwekuako** [comment]
Updated and merged.
