### ISSUE TITLE
*.pods.officeapps.live.com is required endpoint for Microsoft Teams

### ISSUE THREAD

**Issue by chwakims** [MicrosoftDocs/microsoft-365-docs#3792]
[Enter feedback here]
It seems that Microsoft Teams need to access *.pods.officeapps.live.com for sharing PPT content in meeting, but the endpoint is not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@chwakims Thank you for the feedback. I'll work with the author to get this portion updated.

**Comment by msbemba** [comment]
@JoeDavies-MSFT We see *.online.office.com, *broadcast.officeapps.live.com, *excel.officeapps.live.com, *onenote.officeapps.live.com, *powerpoint.officeapps.live.com, *rtc.officeapps.live.com, *shared.officeapps.live.com, *view.officeapps.live.com, *visio.officeapps.live.com, *word-edit.officeapps.live.com. However,  *.pods.officeapps.live.com is missing from the endpoint list and it is required for Sharing Powerpoint in teams meeting.

Would you be able to work with the team to add this information as this is highly restricted content?

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@chwakims I have forwarded this request to the product teams that maintain these lists for their consideration in a future update. Thanks so much for letting us know.
