### ISSUE TITLE
Need organize excel sheet for permission

### ISSUE THREAD

**Issue by Raees29** [MicrosoftDocs/microsoft-365-docs#3793]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions - Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Raees29, we keep the information in regular content so it can be localized into other languages.

Apparently, one of the issues that makes copy/paste from the topic into Excel is the carriage return between each value in the third column of the tables. That carriage return is important for clarity on the page. Without them, each entry runs together and it's hard to see the distinct values.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @Raees29 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
