### ISSUE TITLE
Inaccurate product description

### ISSUE THREAD

**Issue by jlgill** [MicrosoftDocs/microsoft-365-docs#3795]
I have a user with Microsoft 365 Apps for Business License and Exchange Online Plan 1 and they are able to utilize OME.  According to the product description I need to either have 'Office 365 Message Encryption is offered as part of Office 365 Enterprise E3 and E5, Microsoft Enterprise E3 and E5, Microsoft 365 Business Premium, Office 365 A1, A3, and A5, and Office 365 Government G3 and G5' or add-on licensing for the above app.

Is the description of the service incorrect or is this a 'bug'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#what-subscriptions-do-i-need-to-use-the-new-ome-capabilities)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@jlgill Thank you for your feedback. This could be a bug on the customer's tenant as you need to have Azure Information Protection Plan 1 to be able to use the new OME features. 

More details about subscriptions you need to use the new OME capabilities

https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#what-subscriptions-do-i-need-to-use-the-new-ome-capabilities

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jlgill Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
