### ISSUE TITLE
Office 365 Advanced Threat Protection Plan

### ISSUE THREAD

**Issue by m80dunn** [MicrosoftDocs/microsoft-365-docs#380]
The link for Office 365 Advanced Threat Protection takes you to a page describing both Plan 1 and Plan 2.  I had to login to Office 365 and look at the subscription for Microsoft 365 Business in order to find that it is Plan 1 that is included.  I could not find this information anywhere else.  This causes confusion when you are reading about a particular feature only to find out later it is not available with your Plan. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d156f82-2ba0-2d66-a639-1df86554ac83
* Version Independent ID: 4e158c5b-09fd-7214-474f-e7ff44b86d39
* Content: [Microsoft 365 Business security and compliance features](https://docs.microsoft.com/en-us/microsoft-365/business/security-features)
* Content Source: [microsoft-365/business/security-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/security-features.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@m80dunn - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@m80dunn - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
[User Voice](https://office365.uservoice.com) 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
