### ISSUE TITLE
Portal Links Change

### ISSUE THREAD

**Issue by haydanbarry** [MicrosoftDocs/microsoft-365-docs#3801]
This guide describes using the Security & Compliance Audit Log to identify 'Consent To Application' activities. I couldn't find this activity in the S&C or in the Compliance audit logs. However, I was able to find this activity in the Azure Audit Log.
Please update this guide to indicate that the Azure Audit Log is the place to go to find this activity.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66854a7-7556-9b2a-0a33-886e3d881047
* Version Independent ID: 7ce3d8d5-cece-0b6f-68d5-143e12a3fff8
* Content: [Detect and Remediate Illicit Consent Grants - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@haydanbarry Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3854

Thanks
Sri

**Comment by yogkumgit** [comment]
@MSFTTracyP Please merge the PR #3854

**Comment by chrisda** [comment]
PR merged.

Closing
