### ISSUE TITLE
User and device sync for subscription activation

### ISSUE THREAD

**Issue by ClientAdmin** [MicrosoftDocs/microsoft-365-docs#3804]
Hi all,
I'm trying to get a special information and cannot find it anywhere. Do the user object and the device object have to be synced to the same Azure AD (tenant) to be able to use subscription activation? For example lets take the user named Peter and a device named W10TestDevice. The device is Azure AD joined to tenant A. The user Peter is synced to Azure AD of tenant B. Can subscription activation be used in this case?
Kind regards,
Matias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 032295e8-534c-71d5-0f9e-c7f96554a179
* Version Independent ID: f7da2f5a-09b6-59b4-15d7-b2c926748f32
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@ClientAdmin Thank you for your feedback., Per design, the user and the device that he is trying to sign in for subscription activation must be synchronized with the same Azure AD.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ClientAdmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
