### ISSUE TITLE
Very small grammar issue

### ISSUE THREAD

**Issue by avEggHead** [MicrosoftDocs/microsoft-365-docs#3805]
There are two 'that's in a row in the first paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7a02dd4-7f59-96d5-2586-3331c43ead5f
* Version Independent ID: 02324641-66cb-34e1-afc7-915e368b50f1
* Content: [Microsoft 365 for enterprise for the Contoso Corporation - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/contoso-case-study?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/contoso-case-study.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/contoso-case-study.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@avEggHead  Thank you very much for the contribution and updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
