### ISSUE TITLE
Verified publisher for cross tenant applications

### ISSUE THREAD

**Issue by bhaslip** [MicrosoftDocs/microsoft-365-docs#3808]
We are running into an issue where Microsoft now requires publisher verification for cross tenant applications. This is especially detrimental for consumers of application that are not a part of the Microsoft Partner Network. This leaves them no way to consent to the application in the source tenant. Any work arounds that you are aware of?

**Comment by yogkumgit** [comment]
@bhaslip please indicate, which document you are referring to. Thanks.

**Comment by yogkumgit** [comment]
@bhaslip We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
