### ISSUE TITLE
OneDrive and SharePoint sharing is affected with another solution

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/microsoft-365-docs#3810]
[Enter feedback here]
I went through the steps and the share choices were still grayed out.  I am check the following tomorrow, but I think this page should include the below reference.  It would save people a lot of time and trouble.  One person said if we cant fix this he will get fired.  I think he was half serious, but still.

https://docs.microsoft.com/en-us/sharepoint/troubleshoot/administration/sharing-options-grayed-out-when-sharing-from-sharepoint-online-or-onedrive#limited-access-user-permission-lockdown-mode

This affects OneDrive sharing, doesn't it?
When in SharePoint or webpage of OneDrive I didn't see a way into the above mentioned setting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147fb47a-99b2-f8ef-9ca6-35696d49c3fb
* Version Independent ID: b2f1b521-f231-48c2-b61f-f71bf9248d1c
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-as-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-as-team.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@fixx-er Thank you for your feedback. The limited-access user permission lockdown mode affects Sharepoint online and one drive. I have also added this document as a reference article so that it helps users. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3853

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fixx-er Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
