### ISSUE TITLE
URL missing

### ISSUE THREAD

**Issue by Michal-Witwicki** [MicrosoftDocs/microsoft-365-docs#3812]
URL for AD Azure Connect is missing from the website: https://docs.microsoft.com/pl-pl/azure/active-directory/hybrid/tshoot-connect-connectivity#troubleshoot-connectivity-issues-in-the-installation-wizard

* .www.d-trust.net
* .root-c3-ca2-2009.ocsp.d-trust.net
* .oneocsp.microsoft.com

URLs on the website https://docs.microsoft.com/pl-pl/azure/active-directory/hybrid/tshoot-connect-connectivity#troubleshoot-connectivity-issues-in-the-installation-wizard have a wildcard and on this site is given without a wildcard.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/pl-pl/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@Michal-Witwicki The Office 365 URLs and IP address ranges - Microsoft 365 Enterprise article is for Microsoft 365 for enterprise endpoints and does not include Azure-specific endpoints. Thanks for letting us know.
