### ISSUE TITLE
office-365-worldwide-endpoints Missing IP Range for smtp.office365.com

### ISSUE THREAD

**Issue by gitdevmod** [MicrosoftDocs/microsoft-365-docs#3813]
smtp.office365.com seems not up to date:
52.98, 52.97, 40.100 are not listed and maybe more
Thanks

> smtp.office365.com
Serveur :   dns.google
Address:  8.8.8.8

Réponse ne faisant pas autorité :
Nom :    LHR-efz.ms-acdc.office.com
Addresses:  2603:1026:c06:22::2
          2603:1026:c06:2e::2
          2603:1026:c06:1419::2
          2603:1026:c06:1d::2
          52.98.145.66
          52.97.211.242
          52.97.133.226
          40.100.175.146
Aliases:  smtp.office365.com
          outlook.office365.com
          outlook.ha.office365.com
          outlook.ms-acdc.office.com

**Comment by yogkumgit** [comment]
@gitdevmod Please indicate which document you are referring to. Thanks

**Comment by gitdevmod** [comment]
https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

**Comment by msbemba** [comment]
@JoeDavies-MSFT Is there a way I can add the missing IPs to the addresses list for SMTP.office365.com? I remember you had once told me that this section is only accessed by PG and it is highly restricted content to modify. 

Below are some of the IP's But there could be more that are missing, so if you can check with PG that would be great

52.98.145.66
52.97.211.242
52.97.133.226
40.100.175.146

Thanks
Sri

**Comment by msbemba** [comment]
@gitdevmod Thank you for your feedback. I'm working with the author to get this updated.

**Comment by JoeDavies-MSFT** [comment]
@gitdevmod 52.98 and 52.97 are covered by the 52.96.0.0/14 range and 40.100 is covered by the 40.96.0.0/13 range.
