### ISSUE TITLE
How to Add Users later

### ISSUE THREAD

**Issue by bderiso** [MicrosoftDocs/microsoft-365-docs#3816]
How can we properly "add users" later? After the wizard is finished, it's not obvious how to replicate that access,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db2dbb29-38c4-afe4-bc0d-3bbc195f6288
* Version Independent ID: bcfee113-ecfe-e358-974e-6f9cd76b8d35
* Content: [Create a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@bderiso Thank you for your feedback. We have made changes to the document and added more information about adding users via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3852. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @bderiso Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
