### ISSUE TITLE
Microsoft Azure Datacenter IP Ranges link

### ISSUE THREAD

**Issue by thedxt** [MicrosoftDocs/microsoft-365-docs#3817]
Microsoft Azure Datacenter IP Ranges link goes to the deprecated one that was deprecated June 30, 2020.

The correct links should be

Public: https://www.microsoft.com/en-us/download/details.aspx?id=56519
US Gov: http://www.microsoft.com/en-us/download/details.aspx?id=57063
Germany: http://www.microsoft.com/en-us/download/details.aspx?id=57064
China: http://www.microsoft.com/en-us/download/details.aspx?id=57062 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-ca/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@thedxt Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3851

Thanks
Sri

**Comment by thedxt** [comment]
@msbemba oh sorry I wasn't sure how to link them I created PR##3818 for this already

**Comment by msbemba** [comment]
Nice. I'll close the other PR to avoid confusion.

**Comment by thedxt** [comment]
thanks

**Comment by thedxt** [comment]
Issue was solved with PR #3818 Merge
