### ISSUE TITLE
Require MFA for admins preview mode and user exclusions

### ISSUE THREAD

**Issue by SinghGurd** [MicrosoftDocs/microsoft-365-docs#382]
Has something changed recently with these policies?...I am sure 'Require MFA for admins' policy no longer had '(preview)' in its title and there was a control available to exclude users. However, somehow '(preview)' has come back for our tenant and there is no option to exclude users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b76e510-b804-710f-fd4e-5ffdebd505fb
* Version Independent ID: f3a14b91-4406-113f-c0bb-f97e7e85484c
* Content: [Set up conditional access policies for Microsoft 365 campaigns](https://docs.microsoft.com/en-us/microsoft-365/business/set-up-conditional-access-policies)
* Content Source: [microsoft-365/business/set-up-conditional-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/set-up-conditional-access-policies.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@SinghGurd - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@SinghGurd - I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close
