### ISSUE TITLE
On the Permissions tab, you can assign roles to users to pay invoices. | there is no permission tab | share screenshot

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/microsoft-365-docs#3820]
[Enter feedback here]

On the Permissions tab, you can assign roles to users to pay invoices. | there is no permission tab | share screenshot
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9acd5a2f-9048-c5d2-0455-69f80f5e469e
* Version Independent ID: a832f7d9-57be-0742-7eca-7a47b34f85ec
* Content: [Understand billing profiles](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-billing-profiles?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by robinpoulose1** [comment]
As per the sentence " On the Permissions tab, you can assign roles to users to pay invoices. "   there is no such permission tab to change the role. 
Please share the screenshot of the permission tab

**Comment by msbemba** [comment]
@robinpoulose1 Thank you for your feedback. I shall work with the Author and Product group and provide you an update and modify the document if need be.

**Comment by msbemba** [comment]
@cmcatee-MSFT Could you please confirm if the permission tab was removed from the billing profiles? Unfortunately, I do not have a test tenant with the billing profiles feature as this is only available if you bought your subscription directly through Microsoft Sales.

Thanks
Sri

**Comment by robinpoulose1** [comment]
But the document don't say specific to sales,  It still written as Microsoft ( which can be online purchase or partners ). User / customer are getting confused due to inadequate information.  Billing profile is there for all tenant but create new profile is not  there.
Link for billing profile :
https://admin.microsoft.com/Adminportal/Home?source=applauncher#/billoverview/billing-profiles

Please update the document as  Microsoft Sales instead of Microsoft ( it can be Microsoft portal as well ).
![image](https://user-images.githubusercontent.com/17806101/103759419-b54ccf80-5039-11eb-8743-6858d44acb26.png)

**Comment by robinpoulose1** [comment]
The last feedback submitted was for same issue and still the document is not updated.

**Comment by cmcatee-MSFT** [comment]
We are making updates to this article, but there are interdependencies with several other articles that are also undergoing updates, so they will all be republished at the same time.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Thank you very much for sharing this information. @robinpoulose1 Hope this information is helpful, request you please have patience and keep checking. As author confirmed it will be published. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
