### ISSUE TITLE
Getting Microsoft Defender for Identity data

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/microsoft-365-docs#3822]
The link https://docs.microsoft.com/en-us/cloud-app-security/aatp-integration is 404.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7f625c-f3ef-882d-231f-6fef18e14137
* Version Independent ID: 3f335d54-6d65-d49a-e517-2c3a9a95e44d
* Content: [Turn on Microsoft 365 Defender in the Microsoft 365 security center - Microsoft 365 security](https://docs.microsoft.com/en-gb/microsoft-365/security/mtp/mtp-enable?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/mtp-enable.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/mtp-enable.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by chrisda** [comment]
@icelava, confirmed. Apparently, the correct link is (now)  <https://docs.microsoft.com/cloud-app-security/mdi-integration>. I updated the link in this topic and three other affected topics.

Thanks for the feedback.

Closing
