### ISSUE TITLE
Text content inconsistency

### ISSUE THREAD

**Issue by gfard** [MicrosoftDocs/microsoft-365-docs#3825]
in the content it is mentioned that:
"The message is marked and treated as spoof, because spoofing has a higher priority (4) than user impersonation (8)."
The mistake is in the 8th priority of UIMP.

However from the main table we see that the User Impersonation is in the (5) 5th Priority and not in the 8th.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4194fdd-c5de-d424-319a-5e83774b36c2
* Version Independent ID: 83997ad4-a9bd-146e-5da0-8022458cf3ea
* Content: [Order and precedence of email protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gfard, confirmed. A very knowledgeable party updated the table to match current reality, but we forgot to check the rest of the content for the implications of the table update. I fixed the incorrect text.

In the future, you too can make corrections like this without opening an Issue. Check out <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
