### ISSUE TITLE
Add the Security portal URL to the article

### ISSUE THREAD

**Issue by Inbalsas** [MicrosoftDocs/microsoft-365-docs#3826]
[Enter feedback here]
In "Required permissions to access items in content explore" section [https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer?view=o365-worldwide#required-permissions-to-access-items-in-content-explorer]
Please add the Security Portal URL: https://protection.office.com/permissions 
In order to grant Content Explorer List viewer or Content Explorer Content viewer permissions.
Customers that are using Azure PIM are not aware to the Security portal URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334e743d-c929-c74a-c996-2b8e0b68a46b
* Version Independent ID: 91c4563c-72c1-4655-72f7-d467b6098540
* Content: [Get started with content explorer - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-content-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Inbalsas Thank you for you feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3863

Thanks
Sri
