### ISSUE TITLE
Error after copying links to consent URI

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/microsoft-365-docs#3830]
I receive the following error after accepting the links in both the source and destination tenants, and then pressing enter on the powershell.

Send-AdminConsentUri : Could not retrieve a token for invitation manager api call
At C:\Scripts\Migration\SetupCrossTenantRelationshipForTargetTenant.ps1:217 char:9
+         Send-AdminConsentUri $TargetTenantDomain $ResourceTenantDomai ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Send-AdminConsentUri

The application is created at both Azure AD. I have MFA enabled on the azure account in the destination, but not in the source.

**Comment by yogkumgit** [comment]
@StuBeck32 Please indicate which document you are referring to. Thanks.

**Comment by StuBeck32** [comment]
The first script.

Stuart
________________________________

**Comment by StuBeck32** [comment]
Never mind, selecting "This page" caused an error, I'll just create a new issue.
