### ISSUE TITLE
Virus Protection or Malware Protection

### ISSUE THREAD

**Issue by leenana365888** [MicrosoftDocs/microsoft-365-docs#3832]
This article talks about the built-in virus protection in SPO.  Is it just virus protection or overall malware protection (as mentioned in this article: https://docs.microsoft.com/en-us/compliance/assurance/assurance-malware-and-ransomware-protection). Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9cd0ac5-2049-7e80-302e-e0f08857f6b4
* Version Independent ID: 7ca74c37-9929-bfc2-8a27-046457d2f67a
* Content: [Built-in virus protection in SharePoint Online, OneDrive, and Microsoft Teams - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/virus-detection-in-spo?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/virus-detection-in-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/virus-detection-in-spo.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@leenana365888 Thank you for your feedback. The Built-in Virus protection is available in SPO, Onedirve, and Teams. However,  Microsoft 365 includes protection mechanisms to prevent malware from being introduced into Microsoft 365 as a service. Anti-malware software provides both preventive and detective control over malicious software. Where in the built-in anti-virus capabilities are a way to help contain viruses. Having said that, I think it is better to have a reference link in the document about the anti-malware solution.

I have created a PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3875 for the same.

Thanks
Sri

**Comment by leenana365888** [comment]
Thanks Sri!  Does this mean that the built-in protection available for docs in SPO, OneDrive, and Teams will only check for virus and not malware in general?  Many thanks!

**Comment by msbemba** [comment]
@leenana365888 That is correct. The built-in anti-virus capabilities are a way to help contain viruses. They aren't intended as a single point of defense against malware for your environment. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @leenana365888 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
