### ISSUE TITLE
MFA Authentication : error (?) in exemple and posible amelioration

### ISSUE THREAD

**Issue by Lerritier** [MicrosoftDocs/microsoft-365-docs#3833]
Hello,

Two remarks for this article :
1) In all the exemples for the MFA authentication, in the section of code concerning Skype for Business Online you use the argument UserName in the CmdLet New-CsOnlineSession, This argument is not existing for the CmdLet out of MicrosoftTeams module.
2) In the exemple for "basic" authentication, you show a way to connect to all services by saving the credential in a variable. Is it also possible in the MFA authentication. If yes, how ?

Thanks a lot in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6adeef66-5e54-ba2f-37ac-c1898ef942c6
* Version Independent ID: f8a6eda6-b300-dc76-4392-9aeb6c532822
* Content: [Connect to all Microsoft 365 services in a single PowerShell window - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@Lerritier Thank you for your feedback. 

1-  We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3905

2-  It is currently not possible to save the credentials if the account is enabled MFA. However, you can use an App password instead. App passwords allow replacing your regular account password and will enable an app to bypass multi-factor authentication.  -https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Lerritier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
