### ISSUE TITLE
Error after copying links to consent URI

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/microsoft-365-docs#3836]
I receive the following error after accepting the links in both the source and destination tenants in the SetupCrossTenantRelationsForTargetTenant script and then pressing enter on the powershell.

Send-AdminConsentUri : Could not retrieve a token for invitation manager api call
At C:\Scripts\Migration\SetupCrossTenantRelationshipForTargetTenant.ps1:217 char:9

It appears to be failing to send the e-mail. I have MFA setup on the account being used to set this up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by StuBeck32** [comment]
The issue was that I was connecting to Azure AD before running the script. This caused the e-mail to not send for some reason. Annoyingly, the e-mail not sending should not be a cause for the script to bomb out, as the link given before this failure includes what is in the e-mail. Thus the link in the e-mail is redudent. Recommend the error be changed to "e-mail not sent, please give second link above to source tenant admin" and then continue with the script. 

I would also recommend user script be given for online only users. The current script shown on the page for on-prem users is not relevant for the settings required. The scripts on the page also do not copy properly into Notepad++ for example.

**Comment by msbemba** [comment]
@StuBeck32 Thank you for your feedback. I'm testing this currently and will update accordingly.

Thanks
Sri

**Comment by msbemba** [comment]
@StuBeck32 Thank you for your feedback. I tested the script on two test tenants and it seems to work as described in the document. However, I see your recommendation about the errors and that makes sense to continue with the script without bombing out. Please note that this is still in preview and once this goes live you will see a better mechanism of handling errors.

As mentioned, in the document there are a few known issues and one among that is When msExchRemoteRecipientType is set to 8 (DeprovisionMailbox), for on-premises MailUsers that are migrated to the target tenant, the proxy scrubbing logic in Azure will remove nonowned domains and reset the primarySMTP to an owned domain. By clearing msExchRemoteRecipientType in the on-premises MailUser, the proxy scrub logic no longer applies.

Hope this helps!


CC : @JoeDavies-MSFT  

Thanks
Sri

**Comment by StuBeck32** [comment]
Just to clarify, the first script issue was when you are already connected to AzureAD through powershell, it doesn't run the rest of the script. Did you test that?

I'd also recommend putting instructions for cloud only users.
________________________________

**Comment by msbemba** [comment]
@StuBeck32 I did not. As I  Create a Remote PowerShell connection to the source/Target tenant with your Exchange Administrator permissions.

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @StuBeck32 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Flansuel** [comment]
After running the script, the error below appears:

Send-AdminConsentUri : Could not retrieve a token for invitation manager api call
No D:\Downloads\cross-tenant\SetupCrossTenantRelationshipForTargetTenant.ps1:278 caractere:9
+         Send-AdminConsentUri $TargetTenantDomain $ResourceTenantDomai ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Send-AdminConsentUri

Has anyone experienced this error?
