### ISSUE TITLE
Block ActiveSync clients policy instructions

### ISSUE THREAD

**Issue by c3474** [MicrosoftDocs/microsoft-365-docs#384]
Follow the instructions to create the policy, but it won't let me save the policy. Gives a message, "MAM policy should be applied to Android or IOS client platforms."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18267b13-4890-4196-16e8-e183ece73d70
* Version Independent ID: 64887e62-4187-cb6e-fbb3-ff7e12a18841
* Content: [Secure email recommended policies - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/secure-email-recommended-policies#feedback)
* Content Source: [microsoft-365/enterprise/secure-email-recommended-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/secure-email-recommended-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@c3474 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by martincoetzer** [comment]
Hi @c3474 , we have implemented stricter rules for the MAM policy and it now requires you also specifying a device platform condition. Before step 8, Go to **Conditions**, Select **Device platforms**, Choose **Configure**, then under **Include**, choose **Select device platforms**, Select **Android** and **iOS**. Click **Done** and **Done** again. Follow step 8

**Comment by martincoetzer** [comment]
We will update to page with this information. #please-close

**Comment by mypil** [comment]
@officedocsbot close

**Comment by BrendaCarter** [comment]
Updates are now live in the article. Thank you Martin and c3474!
