### ISSUE TITLE
Improve explanation of retention policy specific inclusion/exclusion limits

### ISSUE THREAD

**Issue by deividfoggi** [MicrosoftDocs/microsoft-365-docs#3840]
Consider the following section: A policy with specific inclusions or exclusions

The statement says that every time we use specific locations we cannot exceed 1000 mailboxes per inclusion/exclusion. I noticed that it doesn't make clear that you can workaround by using groups and also that there is a possibility of to create multiple retention policies to satisfy the need to apply the same retention settings to more than 1000 inclusions/exclusions. I think would be better for readers to understand how to workaround the limits besides knowing the existence of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef663fdc-1776-3c73-7743-332796c284e6
* Version Independent ID: ceb29788-39be-8c30-b92a-7a22243ebe83
* Content: [Create and configure retention policies to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@deividfoggi Thank you for your feedback. I have added information about the workaround. Once the author approves it will be live within the next 24-48 hours. The change can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3876

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @deividfoggi Hope the comment added by Author is helpful for you.  We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
