### ISSUE TITLE
Missing scenario from how to reactivate M365 subscription instructions

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/microsoft-365-docs#3843]
This document doesn't cover the scenario where the 'reactivate subscription' is greyed out.

This seems to occur if the subscription was a MAPS based subscription and is flagged as  commercial direct.
I am currently on a support call and even they do not know what i should do.

The partner center in UI guidance also doesn't cover this scenario - it says to use the extend button (which doesn't exist in this scenario)

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/reactivate-your-subscription.md

Example of greyed out reactivate subscription:

![image](https://user-images.githubusercontent.com/11369180/103695987-6f690c00-4f52-11eb-8c00-1e905968ffbc.png)

**Comment by msbemba** [comment]
@scyto Thank you for your feedback. Global or billing admins can reactivate the subscription in the admin center if the subscription is in disabled status. As mentioned in the document, If you don't see Reactivate as an available action, call Support to reactivate your subscription as they can reactivate it in the backend. There could other issues and only support can help you in this case.

Let us know if support was able to reactivate or what action plan was provided, So we can update the document if need be.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @scyto Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
