### ISSUE TITLE
Availability should be highlighted at the start of this page

### ISSUE THREAD

**Issue by ekiswd** [MicrosoftDocs/microsoft-365-docs#3849]
It should be made clear that IMPORT of PST overall is only available in certain regions.

The context on this page makes it sound that the import service is available to all 365 subscribers when it is not. Not all 365 tenants have this privilege.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f9f87e-6f96-9663-114a-f6bd74a7a7f4
* Version Independent ID: b3ba56e3-0c78-f286-1c01-12375bf00f62
* Content: [Overview of importing your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/importing-pst-files-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/importing-pst-files-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ekiswd The [FAQ section](https://docs.microsoft.com/en-us/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-worldwide#using-network-upload-to-import-pst-files) in the same article lists the regions that support PST Import.

**Comment by msbemba** [comment]
@markjjo Do you think this should be highlighted at the start of the page ?

Thanks
Sri

**Comment by markjjo** [comment]
@msemba No, as per my comment. Sri, please contact me internally for inquires like this.

**Comment by msbemba** [comment]
Thank you @markjjo  I'll do that.
