### ISSUE TITLE
IP range for SPF examples is wrong

### ISSUE THREAD

**Issue by mcmeeking** [MicrosoftDocs/microsoft-365-docs#3850]
IP range given for Exchange states that `ip4:23.103.224.0/19 ip4:206.191.224.0/19 ip4:40.103.0.0/16 include:spf.protection.outlook.com` covers Exchange Online emails, but emails are regularly sent from hosts outside that range.

Latest example of this for me was 40.107.14.44 and 40.107.13.74.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed62cce4-7497-d557-8ee9-1e9d65dfc408
* Version Independent ID: 58739750-4fee-52d1-be71-9d379f59ee91
* Content: [Set up SPF to help prevent spoofing - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@mcmeeking Thank you for your feedback. The Ip range mentioned is for Exchange online Dedicated customers only. For Normal Exchange online(Multitenant) all you need to use is include:spf.protection.outlook.com. This is common for all customers.

Hope this helps!

Thanks
Sri

**Comment by mcmeeking** [comment]
Thanks, that doesn't include the range that emails are regularly sent from though. Emails sent from 40.107.0.0/16 fail SPF if the record is only set to include:spf.protection.outlook.com

**Comment by msbemba** [comment]
@mcmeeking Ideally it should not fail SPF as long as it is sent from the exchange online mailbox. There is no such IP address that needs to be added to your SPF record while using M365 services. I'd recommend you to contact the support team via the Need help option on the admin center to identify and troubleshoot this issue.

If you still think there are modifications needed on this document, let us know.

Thanks
Sri

**Comment by mcmeeking** [comment]
> Ideally it should not fail SPF as long as it is sent from the exchange online mailbox

I agree, that's why I raised this initially. I'll raise a ticket and get back to you.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @mcmeeking Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
