### ISSUE TITLE
Add DG Upgrade to O365 Group Script to docs article

### ISSUE THREAD

**Issue by hazemembaby** [MicrosoftDocs/microsoft-365-docs#3856]
[Enter feedback here]
Could we add the below steps automating each factor considered as a blocker for distribution group to office 365 group upgrade process clarified on the article(in addition to other factors ex.duplicate alias) to assist admins on that topic and our support engineers to detect group upgrade blockers in a fast & easy way, the script will log steps taken and an HTML status report will be created containing blockers found.

Please find steps below:

1st: Run PowerShell as administrator
2nd:Install O365troubleshooters module then import that module.
   
![image](https://user-images.githubusercontent.com/71065889/103769874-c1cb2b00-502d-11eb-95b0-5613a992b67e.png)

3rd:Run Start-O365troubleshooters command then press any key to launch another PowerShell session with the menu.
![image](https://user-images.githubusercontent.com/71065889/103769948-defff980-502d-11eb-91d7-95e73aa1aedf.png)

   
4th: Enter 5 to choose Groups Diag and press enter

 
![image](https://user-images.githubusercontent.com/71065889/103769995-f0490600-502d-11eb-8aef-28a4449af4b3.png)

 
5th:Enter GA account username & password to connect to EXO & MSODS
![image](https://user-images.githubusercontent.com/71065889/103770076-17073c80-502e-11eb-805b-5c9d36bfcfd2.png)

  
6th:Enter the SMTP of the requested group.
 
![image](https://user-images.githubusercontent.com/71065889/103770117-25edef00-502e-11eb-9365-db17b514cb05.png)

 
7th:Finally choose either to open HTML report now or later 
   
![image](https://user-images.githubusercontent.com/71065889/103770239-56358d80-502e-11eb-9649-cdd9036244b7.png)

 
Report appearance containing all checks failed\succeeded
 
![image](https://user-images.githubusercontent.com/71065889/103770287-69485d80-502e-11eb-96e6-1e4f96bc67d5.png)

Expanding some failed checks
 
![image](https://user-images.githubusercontent.com/71065889/103770408-a0b70a00-502e-11eb-8794-c0517e74c7e2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb1e873-a684-ba18-21b4-33c2c4cf5aeb
* Version Independent ID: badad26e-0e5e-ab12-f3ae-b6cab759e7b8
* Content: [Upgrade distribution lists to Microsoft 365 Groups in Outlook - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide&source=docs#which-distribution-lists-cannot-be-upgraded)
* Content Source: [microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@Sirkkuw I tested this module and it works as mentioned. Is it okay to add steps to this document as this module is available in the PowerShell gallery?

Link to the module- https://www.powershellgallery.com/packages/O365Troubleshooters/2.0.0.13

CC: @yogkumgit 

Thanks
Sri

**Comment by msbemba** [comment]
@hazemembaby Thank you for your feedback. While it works correctly. I don't think we can add information about the Module to this document. However, I shall check with the author and get back to you.

Thanks
Sri

**Comment by hazemembaby** [comment]
Hello @msbemba do you have any feedback after checking with the author ?

Thanks
Hazem

**Comment by msbemba** [comment]
@msbemba I don't have an update yet. But will circle back with the concerned team.

**Comment by msbemba** [comment]
@hazemembaby Thank you for your feedback. I have checked with the PM and the Author, It is not possible to add a script at this time but we'll look at the details and see if we can add it later.

CC : @yogkumgit  @kwekuako 
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hazemembaby Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
