### ISSUE TITLE
Describe permissions scheme for saved/shared queries

### ISSUE THREAD

**Issue by s4parke** [MicrosoftDocs/microsoft-365-docs#3857]
It would be helpful to include a section describing what built-in roles & role groups allow users to (a) save and (b) share saved threat hunting queries.

For example, it is not clear whether the *Security Reader* role provides (a & b), just (a), or neither capability. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bf88b1-0da2-59ec-75c2-d09d715110b6
* Version Independent ID: 0d46b6a8-606f-af02-bea8-155c7a0369d0
* Content: [Use shared queries in Microsoft 365 Defender advanced hunting - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/advanced-hunting-shared-queries?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/advanced-hunting-shared-queries.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/advanced-hunting-shared-queries.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by msbemba** [comment]
@s4parke Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3904 . Once the author validates and approves, you will be able to view the changes in the live document.

Thanks
Sri

**Comment by msbemba** [comment]
New PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4647 Created

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @s4parke Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by s4parke** [comment]
Thanks all, I really appreciate it!
