### ISSUE TITLE
Advise way to make this a one click solution

### ISSUE THREAD

**Issue by JamesEdmonds89** [MicrosoftDocs/microsoft-365-docs#3865]
It would be great if the docs could advise a way to store this set of commands into a script that could be imported and run, from a fresh powershell window.
This would make accessing all of these services much easier, as it could be a one liner!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6adeef66-5e54-ba2f-37ac-c1898ef942c6
* Version Independent ID: f8a6eda6-b300-dc76-4392-9aeb6c532822
* Content: [Connect to all Microsoft 365 services in a single PowerShell window - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@JamesEdmonds89 Thank you for your feedback. Ideally, the copy button next to the PowerShell script can be used to copy the entire block and run it via Powershell.

You can Also open a PowerShell ISE window and paste the block and save it as a script if need be.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JamesEdmonds89 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by JamesEdmonds89** [comment]
Hi, sorry just for clarity, what I mean was for the script itself to be written in a way that users can just run the script with a single command or click to connect all services at the same time.

Thanks.

**Comment by msbemba** [comment]
@JamesEdmonds89 Thank you for your feedback. Ideally, users could use documents like - https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/how-to-write-and-run-scripts-in-the-windows-powershell-ise?view=powershell-7.1 to understand how to save cmds to a script and execute them. I'm afraid we may not be able to add such instructions to this document.

Thanks
Sri
