### ISSUE TITLE
you forgot the root permission

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/microsoft-365-docs#3866]
What permissions do you need to view the permissions tab in the first place?  We need to assign a service account to programmatically assign permissions to groups.  When we even ask another tech to take a look at them, they dont see the tab, they are already exchange admins / security administrators .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions - Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SquirrelAssassin, it's the Role Management role in the Security & Compliance Center that gives access to the Permissions tab. By default, that role is only assigned to the Organization Management role group. Members of this role group or the Global Administrators role in Azure AD are likely the only ones who can see the Permissions tab.

Your other option is to create a new role group, assign only the Role Management role to it, and add the members that you want. Be advised that this will allow those member to create, modify, and remove role groups. There doesn't appear to be a way to grant read-only access to Permissions tab. Global Reader, Security Reader, and Security Operator in Azure AD don't do it.

**Comment by SquirrelAssassin** [comment]
This is perfect thanks!
