### ISSUE TITLE
This page still references Skype for Business

### ISSUE THREAD

**Issue by PaulEdlund** [MicrosoftDocs/microsoft-365-docs#3869]
[Enter feedback here]
It seems like this page should have information for Teams instead of Skype for Business.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2f2581-292d-a72b-0683-897eaac0adb0
* Version Independent ID: d10014a1-164d-1aea-635f-8c63da26b44c
* Content: [Service Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-service-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/office-365-service-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-service-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@PaulEdlund Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3901

Thanks
Sri

**Comment by KCCross** [comment]
See the PR. Closing this issue.
