### ISSUE TITLE
Inconsistent experience when environment is locked for group creation for Global Admins

### ISSUE THREAD

**Issue by mikewaretena** [MicrosoftDocs/microsoft-365-docs#3870]
The phrase:

"The steps in this article won't prevent members of certain roles from creating Groups. Office 365 Global admins can create Groups via any means, such as the Microsoft 365 admin center, Planner, Teams, Exchange, and SharePoint Online. Other roles can create Groups via limited means, listed below."

gives me the impression that a Global admin will be able to go to the Teams client and have the option to create a team or go to the SharePoint Home and create a team site, this is not what I've experienced today on one of my tenants. 

Please clarify if the global admin needs to resort to Admin centers to create objects that depend on groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@mikewaretena Thank you for your feedback. If the entire organization is locked for group creation, Admins in the roles listed below will retain the access to create groups and teams. This has been added to the document as well. 

Exchange Administrator: Exchange Admin center, Azure AD
Partner Tier 1 Support: Microsoft 365 Admin center, Exchange Admin center, Azure AD
Partner Tier 2 Support: Microsoft 365 Admin center, Exchange Admin center, Azure AD
Directory Writers: Azure AD
SharePoint Administrator: SharePoint Admin center, Azure AD
Teams Service Administrator: Teams Admin center, Azure AD
User Management Administrator: Microsoft 365 Admin center, Yammer, Azure AD

Hope this helps!

Thanks
Sri

**Comment by mikewaretena** [comment]
Thank you for the quick reply, this is helpful!

Cheers,

Miguel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mikewaretena Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
