### ISSUE TITLE
Typo on this page "you to spam"

### ISSUE THREAD

**Issue by paulbaber** [MicrosoftDocs/microsoft-365-docs#3871]
On this page, https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide, the text "that you to spam filtering" should probably be "that you make to spam filtering".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@paulbaber, done. In the future, you too can make fixes like this directly without opening an Issue first. Fir instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
