### ISSUE TITLE
Office365 IP Address and URL query

### ISSUE THREAD

**Issue by ShadowSamauri** [MicrosoftDocs/microsoft-365-docs#3873]
Hi,

Thanks for providing all this information. I can clearly see that a lot of effort has been invested in putting this together and keeping it accurate.

Forgive me if I’ve missed/overlooked what I was looking for, however I think the Office365 URL and IP Address document would benefit from a statement clarifying how to interpret the document when both FQDNs/wildcard domain names and IP addresses are listed in a single endpoint set, e.g. Exchange Online ID 1. 

When this happens, does this require that both conditions need to be true, for traffic to be allowed by the edge firewall? E.g. one firewall rule that requires both the IP address **and** URL to match in the same connection for traffic to be allowed.

Or alternatively, does it mean that either the IP Address **or** URL needs to match to be allowed through the perimeter firewall (e.g. two rules).

The context is allowing workstations to communicate directly with Office365 over the internet through a firewall, not using a proxy.

Please can you clarify in response to this post and consider including a statement in the documentation.

Many Thanks in advance :-) 

Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by LauraWi** [comment]
Looping in @pandrew1 for possible clarification on this question and recommendation with respect to any doc updates.

**Comment by pandrew1** [comment]
The answer to the customers question would depend on their network perimeter configuration. They have to allow the network traffic from their users to Microsoft. They say their configuration is just a firewall and no proxy server. If their firewall is configured with FQDNs then they can just use the FQDNs we publish and they don't need to use the IP Addresses. If they have a firewall which requires IP Addresses then they can use those as well

**Comment by yogkumgit** [comment]
@pandrew1 Thank you very much for the contribution and sharing this explanation. @ShadowSamauri Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
