### ISSUE TITLE
wildcards and non-default ports

### ISSUE THREAD

**Issue by grzegorzwierzbicki** [MicrosoftDocs/microsoft-365-docs#3877]
Hi
What about wildcards and non-default ports ?
Lets say I need to exclude contoso.com:444 - including all subdomains and paths
Will `*.contoso.com/*` work for this ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-links?view=o365-worldwide#do-not-rewrite-the-following-urls-lists-in-safe-links-policies)
* Content Source: [microsoft-365/security/office-365-security/atp-safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-safe-links.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@grzegorzwierzbicki Thank you for your feedback. I'm assuming you are referring to Block the following URLs. If so, Yes, *.contoso.com/* allows people to visit subdomains and paths in the specified domain.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @grzegorzwierzbicki Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
