### ISSUE TITLE
Update Exchange Version Reference

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/microsoft-365-docs#3879]
Hi folks,

Can we update this bit with a reference to current Exchange.  It implies that I may be able to offboard to Exchange 2013 for example.

 Exchange organization. Auto-expanding archiving isn't supported for on-premises mailboxes in Exchange Server 2010.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a7c1600-c310-fb7f-7976-2025ee9256f3
* Version Independent ID: 9241081b-eabb-78a8-af86-2c0f27e7e671
* Content: [Enable unlimited archiving - Admin Help - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-unlimited-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@r-milne Will do, thanks for feedback. To be clear, auto-expanding archiving isn't supported for on-premises mailboxes for any version of Exchange Server.

**Comment by r-milne** [comment]
Exactly- that is what should be explicitly stated.
