### ISSUE TITLE
Can an admin block/hide an individual add-in from the Store?

### ISSUE THREAD

**Issue by slw07g** [MicrosoftDocs/microsoft-365-docs#3881]
Can the docs explicitly mention whether it is possible at this time to block specific individual add-ins from being installed (as opposed to disallowing all add-ins). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61e46dd-c1ff-dfec-5e0e-9f2e7251a5c1
* Version Independent ID: 49f69fa9-33e8-373f-a7f9-26b828510fda
* Content: [Manage add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-addins-in-the-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-addins-in-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@slw07g Thank you for your feedback I have researched and tested. Looks like there is no current mechanism, to hide or block individual add-ins by admin. Having said that you can request such features directly from the developers via https://officespdev.uservoice.com/ . 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@slw07g  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
