### ISSUE TITLE
Log retention for external users.

### ISSUE THREAD

**Issue by pbevis** [MicrosoftDocs/microsoft-365-docs#3885]
If would be useful the article could explicitly state the behaviour for external (guest) users. I assume from reading the article that they require a license but its not obvious. Could the article be updated to clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@pbevis Thank you for your feedback. All users including guests/external who are not assigned an Office 365 or Microsoft 365 E5 license or have a Microsoft 365 E5 Compliance or E5 eDiscovery licenses, their corresponding audit records are retained for 90 days. I have added this to the note via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3902


Thanks
Sri

**Comment by pbevis** [comment]
Thanks for clarifying Sri.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by markjjo** [comment]
Closing issue
