### ISSUE TITLE
Missing 2021 data

### ISSUE THREAD

**Issue by Karlheinzrettig** [MicrosoftDocs/microsoft-365-docs#3888]
In the MS Usage analytics I miss the 2021 data. 
Can you leave a comment what could be the reason?
edback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebdb9f0-76a5-eebc-4cd7-95f5407ed029
* Version Independent ID: 05abf201-e31c-08c0-a7fc-8fd46202e8b0
* Content: [Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?redirectSourcePath=%252farticle%252f77ff780d-ab19-4553-adea-09cb65ad0f1f&view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@Karlheinzrettig Thank you for your feedback. I tested in a couple of tenants and I was able to see 2021 data.

![image](https://user-images.githubusercontent.com/45987684/104483951-b4461000-55ee-11eb-8a1b-a4228eb2bdd4.png)

Also, check if the Data updated date shows a date in 2021, If not you can refresh the data set from the workspace.

![image](https://user-images.githubusercontent.com/45987684/104484118-e35c8180-55ee-11eb-97e5-beaee18883b2.png)

If it shows that the data is updated in 2021 and you still don't see 2021 data, I'd request you to contact the support team via the need help option on the M365 admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Karlheinzrettig Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
