### ISSUE TITLE
License requirement is taking too much page area

### ISSUE THREAD

**Issue by deeksha-microsoft** [MicrosoftDocs/microsoft-365-docs#3889]
Licensing requirement is taking too much page area which causes a lot of unnecessary scroll to get to the required section.
There could probably be a separate page for license requirement for all the solutions
![image](https://user-images.githubusercontent.com/58860268/104182899-27a52180-5437-11eb-8bdd-f98dc873af59.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0630c9-36da-97a6-2240-4d559611b887
* Version Independent ID: f9b42858-3eb1-e720-9ba7-a812f38f9bfc
* Content: [Insider risk solution - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-solution-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-solution-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-solution-overview.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@deeksha-microsoft - yes, agreed and worked on reformatting to list view instead of table. Should be live soon. Thanks!
