### ISSUE TITLE
Delegated administration for Microsoft Partners

### ISSUE THREAD

**Issue by aka-cardz** [MicrosoftDocs/microsoft-365-docs#3890]
The role assignments under "Delegated administration for Microsoft Partners" no longer exist.

> A partner can assign these roles:
>    Full administration Privileges equivalent to a global admin, with the exception of managing multi-factor authentication through the Partner Center.
>    Limited administration Privileges equivalent to a helpdesk admin.

They've been moved to the partner portal.
https://partner.microsoft.com/en-us/dashboard/account/v3/usermanagement#users
Also, the role names are different. They are "Admin agent" and "Helpdesk agent".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@aka-cardz Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3903

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @aka-cardz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
