### ISSUE TITLE
Cannot find content center site in my sharepoint admin center templates

### ISSUE THREAD

**Issue by jamilhaddadin** [MicrosoftDocs/microsoft-365-docs#3893]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c7584f-82d8-8351-3634-a9f9eb06ab61
* Version Independent ID: d2367a72-2839-782f-4ef8-f8cb058098cf
* Content: [Create a content center in Microsoft SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/create-a-content-center?view=o365-worldwide)
* Content Source: [microsoft-365/contentunderstanding/create-a-content-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/create-a-content-center.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by yogkumgit** [comment]
@efrene  Please add your comment and help us in resolving this issue. Thanks.

**Comment by efrene** [comment]
Sorry for the delay in replying back to you.  First, can I ask you if you are able to access your default content center site that was created during setup? You can find this by going to your Microsoft 365 Admin Center, selecting Setup, going to the Files and content section, and then selecting the Manage button in "Automate content understanding".

**Comment by yogkumgit** [comment]
@jamilhaddadin

**Comment by efrene** [comment]
@jamilhaddadin - Just checking back with you on this. Are you still having issues with this?  If you are, please provide me more information on the issue.  Thanks

**Comment by efrene** [comment]
@jamilhaddadin - Have not heard back, so will close this assuming this is no longer an issue. Please let me know if this is not the case. Thanks.
