### ISSUE TITLE
Can support expand the archive manually?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#3895]
According to the FAQ linked on this page, it doesn't seem like M365 support had the tools to manually expand the archive in 2018, and ingesting more than 100GB using a 3rd party tool was not supported at that time. See below for your convenience 

**Can I ingest more than 100GB into the archive via a third party tool?**
This is quite a tricky one for us. We don’t officially support bulk ingestion of more than 100GB into the archive at any one given time. There is currently work on going to provide solutions for these scenarios in the future, but we don’t have any timelines to share right now. Since there are multiple ingestion scenarios we suggest that you contact Microsoft so that we can understand your situation and advise you on the best way forward for your ingestion project.

It's been 3 years, what is the latest on this question? I suggest a adding another bullet to the bottom of this article with the latest guidance:

Original
> * Administrators can't adjust the storage quota.

Suggested Change
> * Administrators can't expand the storage quota.
> * Microsoft support can['t] adjust the storage quota.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69e08cf1-3ef1-7d22-122e-ef0f45c26215
* Version Independent ID: e9677dc3-580d-0a66-80ac-30a8aabdd45f
* Content: [Overview of unlimited archiving - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/unlimited-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by jonwbstr** [comment]
I opened Case (23632685) and received the following response:
> Microsoft support was able to raise the size to 130GB (this may take some time to reflect at your end) but is seems that we cannot do much since anything from the backend is beyond our control. In case you would like to give it a try the workaround is to try running the script Enable-Mailbox <User mailbox> -AutoExpandingArchive and even though it shows a warning that it's already enable, my team thinks that it will still add up another 10GB until you reach 150GB. However, it will take a while for the space to reflect. You can run the script below to check the available Archive storage quota by running Get-Mailbox -Identity user@contoso.com | FL ArchiveQuota. 

Also, the related blog talks about the autoexpanding happening when Managed Folder Attendant runs, so theoretically we could queue MFA and maybe get it to expand every ~7-14 days?

I'm not sure if admins can set the quota to 130GB or if that's restricted to MS support...

**Comment by msbemba** [comment]
@jonwbstr Thank you for your feedback. There are no tools available to ingest more than 100GB of data. The 130Gb quota is generally not available for admin and/or support. However, the case might have been escalated to the Product group and the increase could have happened, So we do not want to explicitly mention that Microsoft support can increase the quota.

In general, It can take up to 30 days for the additional storage space to be provisioned. Also, staring at MFA can quicken the process, but the archive will not expand beyond a given point even after running MFA unless the difference between the mailbox size and the capacity is less than 10GB.

Hope this helps!

Thanks
Sri

**Comment by markjjo** [comment]
Closing issue. Also note that the MFA processes EXO mailboxes at least once every 7 days.
