### ISSUE TITLE
No Calendar to select in list

### ISSUE THREAD

**Issue by clintoj** [MicrosoftDocs/microsoft-365-docs#3897]
I only see Cortana under C in the services list and if I Search all settings I still can't find a calendar setting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b3bda19-af86-20e8-92c4-ccb0caee7cd2
* Version Independent ID: cc93f793-d8bf-e508-d1c1-ddada942623d
* Content: [Share calendars with external users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/share-calendars-with-external-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/share-calendars-with-external-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/share-calendars-with-external-users.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@clintoj Thank you for your feedback. I tested this on a couple of tenants and The steps seem to be correct and we can see the calendar option under the services. Could you please provide a screenshot of what you see under services?

![image](https://user-images.githubusercontent.com/45987684/105070844-e00f3d00-5aa9-11eb-8cae-db99e70f8a18.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @clintoj Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
