### ISSUE TITLE
No love for Australia?

### ISSUE THREAD

**Issue by danfairscan** [MicrosoftDocs/microsoft-365-docs#3899]
Why is Australia left out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd9ad252-50c2-e9d6-9e1a-ab5efde15e60
* Version Independent ID: 7d82a046-e1e2-015f-cb09-27798701b131
* Content: [Overview of Contoso Corporation - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/contoso-overview?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/contoso-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/contoso-overview.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@danfairscan Thank you for your feedback. There are a couple, One in Sydney and the other in Melbourne. The same has been added to the document.

Hope this helps!

@yogkumgit The Issue can be closed.

Thanks
Sri
