### ISSUE TITLE
Add additional URL for SPO/ODFB

### ISSUE THREAD

**Issue by rickjewell-msft** [MicrosoftDocs/microsoft-365-docs#3907]
[Enter feedback here]
Hello,
Can you please add the following URL to the SPO /ODFB section for GCCHigh, or the requests will time out to oneDrive.
*.officeapps.live.com 

Thank you,
Rick Jewell
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0043b9f3-d91c-569f-1efc-720e4162c5e7
* Version Independent ID: 0289deef-82e4-5f56-7258-ab574c8d0e70
* Content: [Office 365 U.S. Government GCC High endpoints - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-u-s-government-gcc-high-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@rickjewell-msft Thank you for your feedback. I'm internally working with the author to make these changes to the document. We will update you soon.

Thanks
Sri

**Comment by LauraWi** [comment]
@rickjewell-msft Please find me on Teams and I will explain the internal process for these updates. This info cannot be manually updated.
