### ISSUE TITLE
Item missing, we are eligible as-per the article.

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/microsoft-365-docs#3909]
The article states that if the item is missing, then we are not eligible. However, in the eligibility section, it lists O365 E3, which is our primary license. We should be eligible, but the item is not available in our M365 admin UI for purchase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide#is-my-plan-eligible-for-office-365-extra-file-storage)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@JLambEJG Thank you for your feedback. I Shall test it with an E3 license and update the document if needed.

Thanks
Sri

**Comment by msbemba** [comment]
@JLambEJG Thank you for your feedback. I can see the Office 365 Extra File Storage option for the O365 E3 subscription. Is this subscription direct with Microsoft or through a partner? I'd suggest you contact Support via the need help section on the admin center and let us know if the document still needs any modifications.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @JLambEJG Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
