### ISSUE TITLE
INconsistent Info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3911]
The page states that Planner is not supported, however when I try to change the settings on one of my Plans, I can assign a sensitivity label. Please investigate and update the instructions as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Will do, Dean - thanks for flagging

**Comment by cabailey** [comment]
@DeanGross  It seems support has just started to roll out for Planner but not expected to complete for a few weeks. So what I've done is moved Planner from the "unsupported" list to "supported" and added the rolling out disclaimer for customers who don't yet see this option. Reviewed the other unsupported items and these remain accurate at this time. 

Now the page is updated, closing this issue.
