### ISSUE TITLE
'Customize the email subject' topic missing

### ISSUE THREAD

**Issue by mevaibhav83** [MicrosoftDocs/microsoft-365-docs#3912]
[Enter feedback here]

'Customize the email subject' topic is missing so no idea how to customize, what are those variables to use to make subject email customization dynamic like 'customize the email text' topic where dynamic variables can be use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@mevaibhav83 Thank you for your feedback. Currently, we do not have an option to customize the subject. However, this design change has been requested via UserVoice- https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/33556768-allow-customization-for-sender-and-subject-for-cus and you can upvote this design change to be notified when this change goes live.

Hope this helps!

@yogkumgit There are no changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@mevaibhav83  Thank you very much for your kind feedback. Considering your valuable feedback, as advised please vote for this User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
