### ISSUE TITLE
Doesn't say whether it analyses the default policy?!

### ISSUE THREAD

**Issue by Sweggle** [MicrosoftDocs/microsoft-365-docs#3913]
The page doesn't say whether it analyses the 'default' Office365 AntiPhishing Policy, as i have a feeling like it doesn't?

I have configured the default policy with lots of good settings, but the configuration analyser still says these settings aren't set. 

They have been set for a long time (months). 

Therefore do i assume that this needs to say that the default policy isn't assessed? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbce796-0aec-3236-d505-607ae8371773
* Version Independent ID: 473cdc81-dc01-f7fd-d570-73e9a07cb972
* Content: [Configuration analyzer for security policies - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Sweggle, I'm told that the Configuration Analyzer should analyze the default policy. Since it obviously isn't for you, you should open a support case.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @Sweggle Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
