### ISSUE TITLE
Addon license requirement?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#3914]
Where do we find out what licenses is add-on "Microsoft 365 E5 Compliance" and "E5 eDiscovery Audit" are available for?

There are two statements that refer to these add-on licenses:
> The default audit log retention policy only applies to audit records for activity performed by users who are assigned an Office 365 or Microsoft 365 E5 license or have a Microsoft 365 E5 Compliance or E5 eDiscovery and Audit add-on license.

and
>To retain an audit log for longer than 90 days, the user who generated the audit log must be assigned an Office 365 E5 or Microsoft 365 E5 license or have a Microsoft 365 E5 Compliance or E5 eDiscovery and Audit add-on license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jonwbstr I believe you can find the the add-on licenses that are available to your organization on the Billing ==> Purchase services page in the M365 admin center.

You can find more about what features are included in these add-ons in this download: https://www.microsoft.com/download/details.aspx?id=102427

We link to that download from this [service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance) and we link to the service description in the beginning of the AdvAudit overview topic.
