### ISSUE TITLE
Follow up to #3914 because someone closed it

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#3915]
In ticket #3914 I asked what license the add-on license is available for. The responder didn't answer the question and closed the ticket.

The tangled web of license add-on dependencies is almost as bad as the spiderweb of deciding what features are available in what product.

When talking about an add-on license, you are saying that the add-on license is available for the following Base licenses. What are those base licenses? Can I add-on this license to O365 Business essentials? can I add it onto Microsoft 365 Voice? How about Microsoft 365 Business, Microsoft 365 Business Standard, there are lots of licenses what can I add it to?

The answer I got was, go into the partner portal and pick random licenses and see if it's available and if it is there is your answer. Our sales team doesn't have access to just hunt for the license requirements for an add-on license. SO. What resource can we provide them to help clients navigate the topic of licenses, and addons?

I honestly think every feature should have a "license requirements" section that directs to some page, github repository or something with info graphics and spreadsheets that enable the viewer to find the answer to those questions. As it is, some pages outline the license requirements one way, others do it a different way and in the case of #3914, they talk about some and leave the rest up for guesswork.

Our internal licensing team spends hours helping the sales team answer the questions and I'm tired of having to track it down and call Microsoft resources for help to track down what should be simple questions about a license or feature.

Lets try to make this stuff easier to track down

**Comment by jonwbstr** [comment]
I've been talking to account manager, they shared a slide deck with some useful stuff that also included confidential information.
They also directed me to the partner center to download the cloud reseller offer matrix
partner.microsoft.com > CSP > Sell > Pricing and offers > Cloud Reseller offer matrix

The matrix is not user friendly. Ended up using a powerbi dashboard to unpivot the dependancies, and the excel doc is missing some of the products including "E5 eDiscovery Audit"

It does have an entry for "Microsoft 365 E5 Compliance"

Also, the license offers has the following Offer Display Name. (yes, 3 spaces!) So the offer exists in the catalog but not the matrix. Either it doesn't depend on anything and the documentation is out of date, or the matrix is out of date/having some other issue.
Microsoft 365 E5   eDiscovery and Audit

**Comment by jonwbstr** [comment]
The catalog says the eDiscovery and Audit license is NON-SPECIFIC so I don't believe it has a dependency. Suggesting the matrix is right, and doc incorrectly says it is an addon when it is not.

**Comment by yogkumgit** [comment]
@jonwbstr comment added by author in 3914 is must be helpful. Hence we proceed here to close this issue. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
