### ISSUE TITLE
Can't connect Bookings to Facebook

### ISSUE THREAD

**Issue by alathrop** [MicrosoftDocs/microsoft-365-docs#3916]
I'd like to get specific instructions for connecting my Bookings account to Facebook. 

This [page](https://www.microsoft.com/en-us/microsoft-365/blog/2016/10/19/connect-microsoft-bookings-to-your-facebook-page-and-grow-your-business/) has a [link](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?redirectSourcePath=%252fen-us%252farticle%252fConnect-Microsoft-Bookings-to-your-Facebook-page-858db050-3d10-4bb5-82f1-df6ebeda2685&view=o365-worldwide) to a page that says it provides instructions, but it does not have instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb53eb7-85a1-6aa0-dfd1-e2b54586008a
* Version Independent ID: 5532470a-a47d-e3bd-4e74-02b2c822cae1
* Content: [Microsoft Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?redirectSourcePath=%252fen-us%252farticle%252fpublish-your-business-calendar-online-with-microsoft-bookings-47403d64-a067-4754-9ae9-00157244c27d&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-overview.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@alathrop Thank you for your feedback. I checked with the author and confirmed that we’re no longer supporting Bookings connection to Facebook. We are working with the PM to file a bug to get the button removed.

@yogkumgit There are no changes required in the document and the issue can be closed.

CC: @kwekuako


Thanks
Sri

**Comment by kwekuako** [comment]
@alathrop thanks for the feedback. We updated the page with a banner stating that connecting to Facebook is no longer supported. The button should be removed from the Bookings app shortly. Thanks.
