### ISSUE TITLE
Trouble connecting Bookings to Facebook

### ISSUE THREAD

**Issue by alathrop** [MicrosoftDocs/microsoft-365-docs#3917]
I was directed to this page for instructions to connect Bookings to my Facebook account. It does not have instructions and I cannot find them anywhere else. 

Can you provide instructions to connect Bookings to Facebook?

Thanks,
Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb53eb7-85a1-6aa0-dfd1-e2b54586008a
* Version Independent ID: 5532470a-a47d-e3bd-4e74-02b2c822cae1
* Content: [Microsoft Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?redirectSourcePath=%252farticle%252fconnect-microsoft-bookings-to-your-facebook-page-858db050-3d10-4bb5-82f1-df6ebeda2685&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-overview.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by kwekuako** [comment]
@alathrop  thanks for the feedback. We updated the page with a banner stating that connecting to Facebook is no longer supported. The button should be removed from the Bookings app shortly. Thanks.
