### ISSUE TITLE
Can't connect Bookings page to Facebook

### ISSUE THREAD

**Issue by alathrop** [MicrosoftDocs/microsoft-365-docs#3918]
I landed on this page from a link that said it provides instructions for linking my Bookings page to Facebook - but there are no instructions here and I can't find them anywhere else. When I click on the "Connect" button in Bookings it also takes me to this page.

Can you provide instructions for connecting Bookings to Facebook?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb53eb7-85a1-6aa0-dfd1-e2b54586008a
* Version Independent ID: 5532470a-a47d-e3bd-4e74-02b2c822cae1
* Content: [Microsoft Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?redirectSourcePath=%252farticle%252fconnect-microsoft-bookings-to-your-facebook-page-858db050-3d10-4bb5-82f1-df6ebeda2685&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-overview.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
Duplicate #3917
