### ISSUE TITLE
Does Tenant Level Encryption for exchange online encrypt shared mailboxes and public folder mailboxes as well as standard user mailboxes?

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/microsoft-365-docs#3924]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18803bfa-118a-09ee-947b-abf1ee996b7a
* Version Independent ID: 87179b6d-d917-1aa9-259a-6f2de072c049
* Content: [Customer Key for Microsoft 365 at the tenant level (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-tenant-level?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-tenant-level.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-tenant-level.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@sinnamingrrl Thank you for your feedback. You are correct, Tenant level Encryption for Exchange online encrypts the entire service. It means Service encryption ensures that content at rest is encrypted at the service layer. Your data is always encrypted at rest in the Microsoft 365 service with BitLocker and DKM (All Exchange Online content including e-mail body content, calendar entries, and the content within email attachments)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sinnamingrrl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
