### ISSUE TITLE
Flow to Power Automate and Power BI reference please

### ISSUE THREAD

**Issue by sksumner** [MicrosoftDocs/microsoft-365-docs#3927]
[Enter feedback here]

Please can we update to refer to Power Automate and not Flow on this page

Additionally there is no mention of Power BI which would seem logical to mention here. Even if its just a link to this page would be useful https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b890c9af-0bab-84c6-8b9d-1ee93cb4683f
* Version Independent ID: 98fddfad-754b-ef65-7f5f-5f8bd8f59004
* Content: [Administering a multi-geo environment - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/administering-a-multi-geo-environment?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/administering-a-multi-geo-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/administering-a-multi-geo-environment.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@sksumner Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3948

Thanks
Sri

**Comment by msbemba** [comment]
@sksumner Thank you for your feedback. We have received confirmation from the author and reviewers that Power BI regions are not related to Microsoft 365 Multi-Geo.

@yogkumgit Please proceed with closing the case as there are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sksumner Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
