### ISSUE TITLE
Bad English Grammar, technical inaccuracies on Set up SharePoint Syntex page

### ISSUE THREAD

**Issue by mcox13579** [MicrosoftDocs/microsoft-365-docs#3932]
The Set up SharePoint Syntex page has multiple sentences with bad English grammar, technical inaccuracies and also an out-of-date screen shot.
![image](https://user-images.githubusercontent.com/12144220/104850125-19755c00-58a2-11eb-96a2-8836bf5e17e8.png)

The Screen shot of the "Configure form processing" page is out of date. 
The incorrect screen shot is highlighted below:

![image](https://user-images.githubusercontent.com/12144220/104850212-97396780-58a2-11eb-8b30-2e1ee2c32ba3.png)

The following screen shot is the actual screen in the MS 365 Admin Center today:
![image](https://user-images.githubusercontent.com/12144220/104850231-b59f6300-58a2-11eb-8cc0-400ea45cf866.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@mcox13579 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3960

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mcox13579 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
