### ISSUE TITLE
MDE Settings or Defender for Endpoint Settings

### ISSUE THREAD

**Issue by arranl148** [MicrosoftDocs/microsoft-365-docs#3933]
A minor one:
Step "3 In the upper right corner of the screen, choose Defender for Endpoint Settings."

Would be clearer if it said either "Microsoft Defender for Endpoint Settings" or "Defender for Endpoint Settings (MDE Settings)"

Thx
A
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58031ac6-a7d2-59ac-59c1-b3e03fbc8f13
* Version Independent ID: 82c2a515-4f33-1771-a175-4ed7d9d31276
* Content: [Use Microsoft Defender for Office 365 together with Microsoft Defender for Endpoint - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@arranl148 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3942

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @arranl148 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
