### ISSUE TITLE
Tenant Level Customer Key Encryption

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/microsoft-365-docs#3939]
[Enter feedback here]
Please confirm if encryption is applied to public folder mailboxes and shared mailboxes in Exchange online as well.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18803bfa-118a-09ee-947b-abf1ee996b7a
* Version Independent ID: 87179b6d-d917-1aa9-259a-6f2de072c049
* Content: [Customer Key for Microsoft 365 at the tenant level (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-tenant-level?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-tenant-level.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-tenant-level.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@sinnamingrrl Thank you for your feedback. Yes, Encryption is applied to all contents in Exchange Online including the Public folders, Shared mailboxes, e-mail body content, calendar entries, and the content within email attachments.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sinnamingrrl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
