### ISSUE TITLE
Clarification of settings

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#394]
In the Define Device-compliance policies section above, it states "The following settings are recommended for Windows 10" and a table of values is presented. Then there is a System Security table with recommendations, but it is not clear what type of devices these apply to, they can't be for windows 10 so I'm assuming that they are for phones, but this is not stated.  Please clarify which tables are appropriate for each type of device. Adding some text to the table titles may a simple way to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0edb16f-03bd-e6f8-87e1-7fc713db726d
* Version Independent ID: 34252c76-c635-0fe0-e0fc-283d0e87d3b7
* Content: [Common identity and device access policies - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/identity-access-policies#define-device-compliance-policies)
* Content Source: [microsoft-365/enterprise/identity-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/identity-access-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @DeanGross,
the policy allows to specify the platform it would be applied for.
as you can see in the beginning of the section:
**Create a policy for each platform:
Android
Android enterprise
iOS
macOS
Windows Phone 8.1
Windows 8.1 and later
Windows 10 and later**

**"Then there is a System Security table with recommendations, but it is not clear what type of devices these apply to"** - it will apply to the platform you have chosen while creating the policy. For example, if you chose "iOS", the policy will be applied to the devices running iOS only.

I would also recommend to read this article written by a third-party author [Protect Office 365 Exchange Online With Intune](http://arnaudpain.com/2019/03/04/protect-office-365-exchange-online-with-intune/)

Thank you

**Comment by mypil** [comment]
@DeanGross - From our understanding, the issue has been answered by MaratMussabekov. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by BrendaCarter** [comment]
@DeanGross - Feel free to send me mail directly if this doesn't address your concerns. Brenda

**Comment by mypil** [comment]
@officedocsbot close
