### ISSUE TITLE
What about full access for a mailbox

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/microsoft-365-docs#3940]
Hello,

in the OME FAQ I am missing a statements for the following questions:
- Can users with "full access" permission to a user mailbox (not a shared mailbox) view OME encrypted messages?
- Can users with "send as" permissions send encrypted emails for a user mailbox or a shared mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@joergrenn Thank you for your feedback.

1) For full access to a user mailbox -Users can open encrypted messages as long as they are given direct access and automapping is turned ON. We don't support if the access to granted via an email enabled security group.

2) When someone sends an email message that matches an encryption mail flow rule, the message is encrypted before it's sent.

I have added these two to the document via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3987

Thanks
Sri

**Comment by joergrenn** [comment]
@msbemba Thank you for providing this information. This makes things clearer.
I am interested in preventing access to encrypted mails to anyone (with full access or delegated) except the one owner of the mailbox. When you say it is "supported", do you know if there is a way to safely prevent access?
I mean based on you answer I could not directly assign users but via a security group. But I assume the team could just add a feature and start supporting also access via security groups and suddenly I have a problem.

**Comment by msbemba** [comment]
@joergrenn That is correct. Users with delegated/full access can still access the encrypted mailboxes.

There is a similar user voice request( Design change) - https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/33578686-prevent-fullaccess-delegated-users-to-read-protect and you can upvote this idea and get notified when this change is made available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @joergrenn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
