### ISSUE TITLE
"Windows Product ID" can be blanc?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/microsoft-365-docs#3941]
According to documentation one need following three columns in a CSV:

![image](https://user-images.githubusercontent.com/6450056/105054920-d4545400-5a72-11eb-828b-a9ec56f47b5a.png)

It says nothing about any of the columns being null/ empty.

Looking at the references PowerShell script/ module, ```Get-WindowsAutoPilotInfo``` from [PowerShellGallery](https://www.powershellgallery.com/packages/Get-WindowsAutoPilotInfo), the part that gets out "Windows Product ID" is returning an empty string.

From [Get-WindowsAutoPilotInfo.ps1 version 3.5](https://www.powershellgallery.com/packages/Get-WindowsAutoPilotInfo/3.5/Content/Get-WindowsAutoPilotInfo.ps1)

![image](https://user-images.githubusercontent.com/6450056/105055219-22695780-5a73-11eb-8f4f-d32153bc959d.png)

Questions that is not answered in current documentation IMO:

* Can "Windows Product ID" be empty in the CSV one upload to Intune?
  * https://devicemanagement.portal.azure.com/#blade/Microsoft_Intune_DeviceSettings/DevicesWindowsMenu/windowsEnrollment 
* What is "Windows Product ID"; the product key used for activating installed version of OS edition, or OEM key from BIOS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74814ff4-77e8-71eb-e78a-fa90cdc37c2c
* Version Independent ID: 55e188f7-4368-6d6a-c567-41347098d66b
* Content: [Use the step-by-step guide to add Autopilot devices and profile - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/add-autopilot-devices-and-profile?view=o365-worldwide)
* Content Source: [microsoft-365/business/add-autopilot-devices-and-profile.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/add-autopilot-devices-and-profile.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@o-l-a-v Thank you for your feedback. 

1) You are correct, This script uses WMI to retrieve properties needed for a customer to register a device with Windows Autopilot. Note that it is normal for the resulting CSV file to not collect a Windows Product ID (PKID) value since this is not required to register a device. Only the serial number and hardware hash will be populated.

I have added this as a note via  PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4013

2) ProductKey:  This is the Windows product ID, a.k.a. PKID, a 13-digit number that corresponds to the Windows product key that was inserted into the firmware of the device at manufacturing time. OEM's have started to put this value on the box itself, as a bar code

Hope this helps!

Thanks
Sri

**Comment by o-l-a-v** [comment]
> @o-l-a-v Thank you for your feedback. 
> 
> 1) You are correct, This script uses WMI to retrieve properties needed for a customer to register a device with Windows Autopilot. Note that it is normal for the resulting CSV file to not collect a Windows Product ID (PKID) value since this is not required to register a device. Only the serial number and hardware hash will be populated.
> 
> I have added this as a note via  PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4013
> 
> 2) ProductKey:  This is the Windows product ID, a.k.a. PKID, a 13-digit number that corresponds to the Windows product key that was inserted into the firmware of the device at manufacturing time. OEM's have started to put this value on the box itself, as a bar code
> 
> Hope this helps!
> 
> Thanks
> Sri
> 
> 

Thanks. Please also add to the documentation that PKID being NULL in the output CSV is totally fine.

**Comment by msbemba** [comment]
@o-l-a-v Thank you. That is added to the note as well.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @o-l-a-v Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
