### ISSUE TITLE
Paragraph in wrong place?

### ISSUE THREAD

**Issue by emwes** [MicrosoftDocs/microsoft-365-docs#3946]
**Get started with content explorer > 
    Prerequisites > 
         Permissions >** 
          _In order to get access to the content explorer tab, an account must be assigned membership in 
          any one of these roles or role groups.

          [A DLP policy can help protect sensitive information, which is defined as a sensitive information type. 
           Microsoft 365 includes definitions for many common sensitive information types ....] ?????_

The paragraph in square brackets above must be missplaced, isn't it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334e743d-c929-c74a-c996-2b8e0b68a46b
* Version Independent ID: 91c4563c-72c1-4655-72f7-d467b6098540
* Content: [Get started with content explorer - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-content-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@emwes Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3988

Thanks
Sri
