### ISSUE TITLE
Disabling EWS connectivity to mailbox breaks free/busy calendar and Report Message Add-In Customization

### ISSUE THREAD

**Issue by CMS009** [MicrosoftDocs/microsoft-365-docs#3949]
Disabling EWS connectivity to mailbox breaks checking other users free/busy calendars.   The free/busy calendar issue appears to be random failures between users.  For example User A can't see User B, but can see User C and D.  User B can't see User D, but can see User A and C.

https://support.microsoft.com/en-us/help/3028900/outlook-or-lync-connections-fail-when-the-ews-protocol-is-disabled-in

It also disables any administrator custom settings for the "Report Message" plug-in.  For example, if the administrator has configured the plug-in to redirect to a custom mailbox vs. sending direct to Microsoft.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4f6b67-85ac-ef6e-5260-6ae160cfd6d8
* Version Independent ID: b4ae42b8-dd36-9f18-092b-af0b55b3c0fb
* Content: [Best practices for configuring EOP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/best-practices-for-configuring-eop?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/best-practices-for-configuring-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/best-practices-for-configuring-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@CMS009, I'm told the add-in apparently uses REST, but will fall back to EWS if REST isn't available. I'm seeking clarification, and I will likely update the topic based on what I'm told.

**Comment by chrisda** [comment]
@CMS009, additional follow-up:

## Exchange Server requirements:

- Exchange Online
- Exchange Server 2016 or 2019

## Outlook client requirements:

- **Windows**: M365 subscription, or Outlook 2019 one-time purchase.
- **Mac**: M365 subscription, or Outlook 2016 or later one-time purchase.
- Outlook for iOS and Android
- Outlook on the web (OWA)
If both the client AND server-side requirements are met, then the add-in uses REST; otherwise, the add-in will fall back to EWS.

Comments?

**Comment by yogkumgit** [comment]
@CMS009 Please share your comment if you have any?

**Comment by chrisda** [comment]
Topic updated with relevant information about Outlook dependencies on EWS, and options for reducing the attack surface if you can't globally disable EWS.

Thanks for the feedback.

Closing
