### ISSUE TITLE
Request for additional info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3950]
Please provide links to information about how to use Sensitivity Labels for each of the Supported Apps, I can't find anything about how to do this with Stream or Forms, 

It's not clear what is meant by the "the following apps support sensitivity labels" could you please elaborate on what this means. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
The full statement is "support sensitivity labels configured for sites and group settings" - which is subtly different from supporting all settings in sensitivity labels.   All the listed apps and services use Microsoft 365 Groups, which means that they can benefit from using sensitivity labels as part of their configuration. 

When you create groups in the apps and services listed as supported, you should see an option to select sensitivity labels - where you can select a label that has been configured for groups and sites.  For example, when you create a new group in Stream, specify the Name, Description, and then for Edit settings, use the dropdown list for Sensitivity to select one of the published labels.

If it's not obvious where to select a sensitivity label when you create a group in the listed apps, that's good feedback for the relevant teams.

**Comment by DeanGross** [comment]
Thanks for the explanation that is helpful, but I think that we still need some additional text to elaborate on exactly what happens to the content created by the supported apps when a sensitivity label is applied to a container. For example, how does the Control Sharing from labeled SharePoint sites setting affect Forms and videos in Stream? how does the Access from unmanaged devices affect these apps, the documentation and the instructions on the configuration page in the portal don't address these scenarios.

On a related note, what about apps that are added to teams from the Teams App catalog, I assume that they are not affected/supported, but it would be helpful to have the confirmed and explicitly stated in the documentation

**Comment by cabailey** [comment]
To clarify, the settings that you can configure in a sensitivity label and then apply to a group or site are not new settings.  They are existing settings for Microsoft 365 groups or SharePoint sites that a sensitivity label bundles together as a single policy. When you publish the label, these settings can then more easily be applied when groups are created in these apps. Planner, Forms, and Stream all use groups and have an associated SharePoint site.

**Comment by yogkumgit** [comment]
@cabailey Thank you very much for sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
