### ISSUE TITLE
When to unassign old license, not clear.

### ISSUE THREAD

**Issue by woter1832** [MicrosoftDocs/microsoft-365-docs#3951]
In [step 4](https://docs.microsoft.com/en-gb/microsoft-365/commerce/subscriptions/change-plans-manually?view=o365-worldwide#step-4-reassign-licenses), It doesn't say when I should unassign the old license.

Is the switch just metadata on the backend or is there actual data migration meaning the user needs both licenses applied for a period of time?

e.g. Upgrading a user from Exchange Online to O365 Standard, when can I unassign Exchange Online?

Thanks

P.S. Step 4.3, I think you mean "On t**h**e licenses...", not "On te licenses...". 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f93e2c37-479d-a277-acdc-bc41ec6f0591
* Version Independent ID: 5ba19142-3450-9a6b-3f0c-5305299b35c9
* Content: [Change Microsoft 365 for business plans manually](https://docs.microsoft.com/en-gb/microsoft-365/commerce/subscriptions/change-plans-manually?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/change-plans-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/change-plans-manually.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@woter1832 Thank you for your feedback. We have made changes on Step 4.3 via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3989

Meanwhile, When you select Replace existing product license assignment, It removes all existing licenses and assigns the new license. The switch metadata is on the backend and there is no requirement to keep both licenses active (In fact it cannot be as there will be conflicting SKU's)

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @woter1832 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
