### ISSUE TITLE
Spelling error in Principles of Retention precedence graphic

### ISSUE THREAD

**Issue by ferringer** [MicrosoftDocs/microsoft-365-docs#3954]
The graphic depicting the order of precedence for evaluating the principles of retention has a spelling error. In the second item, "retention" is misspelled as "retenton".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Don't know how we all missed this!  Will get it fixed, thanks for flagging it.

**Comment by cabailey** [comment]
Fixed now, closing.
