### ISSUE TITLE
How to i update Mailbox Usage Report

### ISSUE THREAD

**Issue by tb-mtg** [MicrosoftDocs/microsoft-365-docs#3956]
How can manually force the "Last updated" date to update for the "Mailbox usage" in Microsoft 365 Reports in the admin center?

https://admin.microsoft.com/?source=applauncher#/reportsUsage/MailboxUsage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e612a4e4-d051-27a7-e54a-bb1ac3fe0849
* Version Independent ID: 653be32f-e4e8-8a72-98b3-a629238ecbd5
* Content: [Microsoft 365 Reports in the admin center - Mailbox usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/mailbox-usage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/mailbox-usage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/mailbox-usage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@tb-mtg Thank you for your feedback. Unfortunately, there is no manual way to force update the Usage report. It usually takes 24-48 hours for this data to be available.

Hope this helps!

Thanks
Sri

**Comment by tb-mtg** [comment]
Thanks @msbemba, but It would be nice to be able to force an updated report anytime after getting some users to clean out their mailbox.

**Comment by msbemba** [comment]
Thank you for the feedback. @tb-mtg This would be a design change request.  I'd recommend you open a new user voice request( Typically all design changes go through the user voice portal) -https://office365.uservoice.com/forums/273493-office-365-admin

Hope this helps!

Thanks
Sri

**Comment by tb-mtg** [comment]
User Voice has been raised:

https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/42550636-manual-update-of-mailbox-usage-report?category_id=127975

**Comment by yogkumgit** [comment]
@tb-mtg Thank you very much for your kind feedback and raising User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
