### ISSUE TITLE
Commands don't seem to act on multiple pages

### ISSUE THREAD

**Issue by MrOCanada** [MicrosoftDocs/microsoft-365-docs#3958]
The Quarantine, when pulling from powershell is separated into multiple pages.  
Using the get-QuarantineMessage it seems to only look in the first page.  In a large environment there is no way to easily get every page and release?  This needs to be designed for large environments too.  Even the Quarantine GUI has no search filters for columns.  i.e in the Released column only so result of "no" . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd59e09-8b82-5c4e-a06f-3e468c9c3273
* Version Independent ID: 2ec32405-bc7a-60f2-782b-b527a2746b11
* Content: [Quarantined messages FAQ - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MrOCanada, with the [Get-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/get-quarantinemessage) cmdlet, can you use the PageSize parameter to increase the number of values per page (max 1000), and the then the Page parameter to see how many pages there are?

**Comment by MrOCanada** [comment]
> @MrOCanada, with the [Get-QuarantineMessage](https://docs.microsoft.com/powershell/module/exchange/get-quarantinemessage) cmdlet, can you use the PageSize parameter to increase the number of values per page (max 1000), and the then the Page parameter to see how many pages there are?

Thanks Chrisda,
I wrote the following to get page per page the hits and release them.  Perhaps an example like this on the page to help people handle mass quarantines.  The Quarantine GUI could really use a filter feature for the columns though.  To sort by Released (Yes or No) would go a long way for those with an environment sized where that GUI is good enough. 
My tenant is 40,000+ mailboxes with millions of messages in a 24 hours period.  When a mass quarantine occurs for whatever reason and the content is valid, releasing using the GUI is not feasible.

Not sure if there is a better way to share code, I looked for something in the menu to wrap code in but not sure. 
Hope this below helps someone mass delete from quarantine.  There are spaces in the write-host to help see them visually. Please excuse my code abilities :)  This will search 50 pages for matching content.

**********************************************
#First test with the Get-QuarantineMessage command and filters to be sure you are targeting what you need.
$Page = 1
$List = $Null

Do
{
write-host "Getting Page " $Page

$List = (Get-QuarantineMessage -Type Spam -pagesize 1000 -page $page | where {$_.SenderAddress -like "*contoso.com" -and $_.RecipientAddress -like "hello@data.com" -and $_.Released -like "False"})
write-host "                     " $List.count " rows in this page match"
write-host "                                                             Exporting List to appended csv for logging"
$List | export-csv -NoTypeInformation Matches-Logging.csv -Append

write-host "Releasing Page " $Page
$List | foreach {Release-QuarantineMessage -Identity $_.Identity -ReleaseToAll}

$Page = $Page + 1

} Until ($Page -eq 50)

******************************************************

**Comment by chrisda** [comment]
@MrOCanada, thanks for the code. For feature requests, please open an issue at <https://office365.uservoice.com/>.

**Comment by yogkumgit** [comment]
@MrOCanada Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by chrisda** [comment]
@MrOCanada, I added your script information to the topic.
