### ISSUE TITLE
Missing Exchange Free/Busy Flow

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/microsoft-365-docs#3961]
Hi folks,

we have this in the article:

7 | Exchange Hybrid co-existence functions such as Free/Busy sharing. | Customer on-premises Exchange server | Inbound server traffic

That is only service -> on-premises.

There really should also be a separate  line which states the on-premises Exchange servers required outbound TCP 443 to the tenant so that an on-premises mailbox can view the calendar for a cloud mailbox.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@r-milne Thank you for your feedback. We are working with the author to verify and make necessary changes to the document.

Thanks
Sri

**Comment by kelleyvice-msft** [comment]
The line referenced (7) explicitly states that it only applies to inbound traffic from the service to the on-premises Exchange server. It is correct as is. Also, the requirement for outbound 443 is not covered in this topic; it is not an exception, but applies to every organization. Closing the issue.
