### ISSUE TITLE
Please update to reflect correct time to remove restrictions

### ISSUE THREAD

**Issue by MyTestingAccountThatIUse** [MicrosoftDocs/microsoft-365-docs#3964]
The last few users I have removed from "Restricted users" have taken over 24 hours to have all restrictions removed.

Please update the tooltip to reflect the maximum time taken to have restrictions removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c17e50d-aa8f-bd30-66af-ef4d63f02402
* Version Independent ID: 92cbda3f-c3a9-ed20-2038-7e966f491934
* Content: [Remove blocked users from the Restricted Users portal - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MyTestingAccountThatIUse, tool tip change = code change. Your best bet for results is to open a support case and/or file a suggestion at <https://office365.uservoice.com/>.

In the topic (which I can fix), the current mention of time says:

> It may take 30 minutes or more before restrictions are removed.

So I should change this to say:

> It might take up to 24 hours for all restrictions to be removed from the user.

**Comment by msbemba** [comment]
Thank you @chrisda . I have updated the Document to reflect the changes PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/3991

Thanks
Sri

**Comment by chrisda** [comment]
PR approved.

Closing
