### ISSUE TITLE
Expand to Microsoft 365 scope to include migration of Windows 10

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/microsoft-365-docs#3965]
Great article. It would be helpful to expand the discussion from Office 365 to Microsoft 365 and cover tenant-to-tenant migration for Windows 10 PCs (especially those that are only Azure AD-joined) and Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78fbba03-39f0-9d11-12b0-b57830942db8
* Version Independent ID: f14feef7-7041-5e60-c193-8eb480097511
* Content: [Microsoft 365 tenant-to-tenant migrations - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by JoeDavies-MSFT** [comment]
@adamgourd Based on your request, I am now investigating the tenant-to-tenant migration steps for Windows 10 where the devices have a Microsoft 365-based subscription activation and license. I will update the poster and article when I have all the details. As for Intune, the current poster mentions it, but I am working on adding more detail. Thanks for your suggestion as it led to these new efforts to complete the story for Microsoft 365.
