### ISSUE TITLE
Key missing policy?  Alert if any alerts are modified!

### ISSUE THREAD

**Issue by CClayton000** [MicrosoftDocs/microsoft-365-docs#3968]
I tried looking in the O365 Security & Compliance Alert Policy area, but cannot find the option.  Is there any way to know and be alerted if someone changes an existing Alert Policy?  
I know IT and those with access to this area should be well vetted, but the rogue administrator is the main point for some of these existing rules.  What is stopping that rogue administrator from changing the alert policy, doing his dirty work, and then toggling the rule back on?  
I know we have the audit trail history, but that is an after-the-fact item and Microsoft still has a short lifespan on the log of 90 days.

**Comment by markjjo** [comment]
@CClayton000 You might consider providing this product feedback here: https://office365.uservoice.com/forums/289138-office-365-security-compliance

Also, you might look into creating a custom alert policy using the [New-ProtectionAlert](https://docs.microsoft.com/en-us/powershell/module/exchange/new-protectionalert?view=exchange-ps) cmdlet in SCC PowerShell. Not sure if this will work or not, but I would suggest you edit and/or delete an alert policy (like you think a rogue admin would) and the find the corresponding audit log record. I'm guessing the the operation/activity logged in the audit record will be Set-ProtectionAlert. If so, then you might be able to create the new alert policy, using the -Operation parameter to specify the same operation that is returned in the audit lot (I assume the RecordType will be SecurityComplianceCenterEOPCmdlet, enum value = 18). You can also use the -NotifyUser parameter to send an email notification when an alert is triggered. Of course, a rogue admin with permissions to create/configure alert policies could tamper with this policy or delete it, but worth a try if you can get it to work.
