### ISSUE TITLE
Clarity that Exceptions are considered conditions.

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#3969]
Article states that:

Outlook 2013 and later supports showing policy tips for only some conditions
Currently, Outlook 2013 and later supports showing policy tips only for these conditions:

Content contains
Content is shared
Note that all of these conditions work in Outlook, where they will match content and enforce protective actions on content. But showing policy tips to users is not yet supported.

Because Conditions and Exceptions are separate sections in the DLP rule interface. It is worth mentioning that Exceptions are considered conditions, as this has caused some confusion for one of my customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide#outlook-2013-and-later-supports-showing-policy-tips-for-only-some-conditions)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback.  In DLP policies, Conditions define what to include and Exceptions define what to exclude. You can find more information about that on DLP policy conditions, exceptions, and actions document (preview)https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-conditions-and-exceptions?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by dkotars** [comment]
No it doesn't. The article I am mentioning states:

**Outlook 2013 and later supports showing policy tips for only some conditions
Currently, Outlook 2013 and later supports showing policy tips only for these conditions:

Content contains
Content is shared
Note that all of these conditions work in Outlook, where they will match content and enforce protective actions on content. But showing policy tips to users is not yet supported.**

If you implement a DLP rule that has an exception that is not content contains/content is shared, this will prevent to policy tip from appearing as well. This is not noted in the document.

**Comment by msbemba** [comment]
@dkotars Thank you for the explanation. I shall test this on outlook 2013 and update the document if required.

Thanks
Sri

**Comment by msbemba** [comment]
@dkotars Thank you for the feedback. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4265. Once the author validates and approves the document will be updated.

Thanks
Sri
