### ISSUE TITLE
"Review and edit settings for the Report Phishing add-in"

### ISSUE THREAD

**Issue by EgorEmeliyanov** [MicrosoftDocs/microsoft-365-docs#3970]
The section "Review and edit settings for the Report Phishing add-in" can be improved in two ways:

1) The current link to "Services and add-ins" is outdated -- it takes user to the "Org settings" page. Instead, it should be /Settings/Addins ("Add ins" or "Integrated apps" in newer releases). If user follows the link he's never find "Report phishing" in that list.

2) More importantly, in this section there should be a link or a brief description of "User submissions policy" from the "Security and Compliance center" -- that's what most people are looking to configure after enabling the add-in.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 214e9296-0909-0946-57b0-dca5f22ee854
* Version Independent ID: 689f3c32-eeb9-9c60-5d7c-78ebd6dcb165
* Content: [Enable the Report Phish add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-phish-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-phish-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-phish-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
I have fixed this links in the [Enable the Report Phish add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-phish-add-in?view=o365-worldwide) article and it should be available shortly. 

Users submissions is already referenced in the what-do-you-need-to-know-before-you-begin section and the view-and-review-reported-messages sections.
