### ISSUE TITLE
Required Permissions - Security Operator

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#3977]
How come Security Operator is not listed in the roles to start an AIR process? is this an oversight?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e66cb3d-b771-af2b-860f-5355b2178db0
* Version Independent ID: 7ce9307c-ca00-cb47-6978-b9b09c139978
* Content: [Automated investigation and response in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-air?view=o365-worldwide#required-permissions-to-use-air-capabilities)
* Content Source: [microsoft-365/security/office-365-security/office-365-air.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-air.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We have added the role to the list via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4011

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
