### ISSUE TITLE
Information regarding creation of new Billing Profiles is inaccurate.

### ISSUE THREAD

**Issue by ross-brasseaux** [MicrosoftDocs/microsoft-365-docs#3982]
The documentation describes Billing Profiles as a useful way to customize granular billing environments, such as departments within your company. It also states that you can add Billing Profiles from the provided link, which (at least for me) routes me to my Microsoft admin dashboard (which is not where you can add billing profiles). I also examined each page under the "Billing" navigation menu, but none of those allow you to add Billing Profiles either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9acd5a2f-9048-c5d2-0455-69f80f5e469e
* Version Independent ID: a832f7d9-57be-0742-7eca-7a47b34f85ec
* Content: [Understand billing profiles](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-billing-profiles?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-billing-profiles.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@ross-brasseaux THank you for your feedback. Billing profiles feature as this is only available if you bought your subscription directly through Microsoft Sales. Having said that, We discussed this with the @cmcatee-MSFT (Author) and received confirmation that they are making updates to this article, but there are interdependencies with several other articles that are also undergoing updates, so they will all be republished at the same time.

Hope this helps!

@yogkumgit There are no changes required to this document at the moment.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ross-brasseaux Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
