### ISSUE TITLE
Is Azure AD Premium license required to modify "group.unified.guest" settings?

### ISSUE THREAD

**Issue by hrfmjp** [MicrosoftDocs/microsoft-365-docs#3986]
I don't see any mention of required licenses in this article, do I need Azure AD Premium to modify "AllowToAddGuests" of "group.unified.guest"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e00be85-c1bd-bfd9-e09b-78fea811f864
* Version Independent ID: bdfb2aad-6aa8-76a8-46cf-1603f8255df4
* Content: [Prevent guests from being added to a specific group](https://docs.microsoft.com/en-us/microsoft-365/solutions/per-group-guest-access?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/per-group-guest-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/per-group-guest-access.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@hrfmjp Thank you for your feedback. There is no requirement as such and I was able to test it successfully without AAD P1/2 licenses.

Hope this helps!

@yogkumgit There are no changes required on this document. Please close this issue.

Thanks
Sri

**Comment by hrfmjp** [comment]
@msbemba Thank you for your reply. I can found additional information in another article.
https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-settings-cmdlets#template-settings

The Table of "Template settings" section say that AAD P1 required to modify "AllowToAddGuests" property.
Is this description valid for "group.unified.guest" settings?

**Comment by msbemba** [comment]
@hrfmjp It does not look like it is valid for "group.unified.guest" settings. I can confirm that this works without AAD P1.

Thanks
Sri

**Comment by msbemba** [comment]
@hrfmjp Thank you for your feedback. I have tested and it is not valid for the group.unified.guest. There is no license requirement as such to make these changes.

Hope this helps!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hrfmjp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
