### ISSUE TITLE
can not verify safe document feature based on official document 

### ISSUE THREAD

**Issue by iovex** [MicrosoftDocs/microsoft-365-docs#3993]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide

1. SafeDocsDemo.docx
2. SafeDocsDemo.pptx
3. SafeDocsDemo.xlsx

can not verify feature of safe documents due to three test files above dont work , 
need to  use the test files in eicar website to instead.
https://www.eicar.org/?page_id=3950

please update the document in time

**Comment by msbemba** [comment]
@iovex Thank you for your feedback. I don't think we can refer to the Eicar website as EICAR cannot be held responsible when these files when users download/tests them. I will work with the author and update accordingly.

Thanks
Sri

**Comment by chrisda** [comment]
@iovex, the 3 test files should work. But, even if you don't have the correct licenses for Safe Documents, you can still 'enable' the feature (see [this issue](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4179)). So, could we be dealing with a licensing issue here?

Also, the EICAR.TXT file is caught by basic anti-malware filtering in the service, so those 3 test files are the only way to test the Safe Documents feature itself.

**Comment by msbemba** [comment]
@chrisda Thank you for the help!

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @iovex Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
