### ISSUE TITLE
Link to Explanation Types points to wrong page

### ISSUE THREAD

**Issue by davidsrhans** [MicrosoftDocs/microsoft-365-docs#3994]
Hi, the link to Explanation Types does not have the correct hyperlink behind it.  

Currently it is pointing to the Form Processing Overview page https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/form-processing-overview  

Instead of https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/explanation-types-overview

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e75e792-3bda-28dc-57f5-b7903ccf13ec
* Version Independent ID: 7c936519-9933-9565-9b1e-cf22f3982bb3
* Content: [Introduction to Microsoft SharePoint Syntex](https://docs.microsoft.com/en-gb/microsoft-365/contentunderstanding/)
* Content Source: [microsoft-365/contentunderstanding/index.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/index.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@davidsrhans Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4008

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @davidsrhans Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
