### ISSUE TITLE
better explain "Apply the above selection if malware scanning for attachments times out or error occurs" option

### ISSUE THREAD

**Issue by rpremuz** [MicrosoftDocs/microsoft-365-docs#3996]
In **Use the Security & Compliance Center to create Safe Attachments policies** step 4 includes the following statement:

* **Apply the above selection if malware scanning for attachments times out or error occurs**: The action specified by **Safe Attachments unknown malware response** is taken on messages even when Safe Attachments scanning can't complete. Always select this option if you select **Enabled redirect**. Otherwise, messages might be lost.

So, it says that if I select "Enable redirect" option, I should also select "Apply the above selection if malware scanning for attachments times out or error occurs" option.

But actually when I unselected "Enable redirect" option and selected "Apply the above selection if malware scanning for attachments times out or error occurs" option, the policy creation reported:

> WARNING: The "Enable redirect" option should be selected when "Apply the above selection if malware scanning for attachments times out or error occurs" is selected. Not enabling redirect could result in loss of messages.

If this warning is correct, then the above statement should be changed to the following:

* **Apply the above selection if malware scanning for attachments times out or error occurs**: The action specified by **Safe Attachments unknown malware response** is taken on messages even when Safe Attachments scanning can't complete. If you selected this option always select **Enabled redirect**. Otherwise, messages might be lost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be929ba-8bef-b75c-0475-041bb6ec441a
* Version Independent ID: 358f9e1a-1900-7c8c-814a-b878a9a22f9e
* Content: [Set up Safe Attachments policies in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-attachments-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rpremuz, done.

Thanks for the feedback.

Closing
