### ISSUE TITLE
url link broken

### ISSUE THREAD

**Issue by maxst33l** [MicrosoftDocs/microsoft-365-docs#3997]
leads to 404:
Configure Privileged Access Workstations (PAWs) for admin activity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b680bb5-de3b-ee83-3764-91695bab77ed
* Version Independent ID: 9c770adf-a66e-ed32-25aa-ffbc46eaef82
* Content: [Microsoft 365 security roadmap - Top priorities - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/security-roadmap?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/security-roadmap.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/security-roadmap.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@maxst33l Thank you for your feedback. We are working with the author to fix the broken link and the document will be updated shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@BrendaCarter We have fixed this broken link via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4209 as per your suggestion. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @maxst33l Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
