### ISSUE TITLE
FAQ says split tunnel doesn't work with browser - still correct?

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/microsoft-365-docs#3999]
I had a customer say that after implementing split tunneling for Teams media that they could finally do Teams Meetings via a browser, but this article says that split tunneling **shouldn't** work for browser clients. Is that entry still correct, or have we made changes in the browser client to make split tunneling work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b783ee-9449-56db-3abd-f17dcf6b5d54
* Version Independent ID: d2146ff5-4248-12ec-a873-c951220aaa14
* Content: [Implementing VPN split tunneling for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Issue resolved by another writer 2 months ago, updated guidance specifies that it is possible and links to relevant content. Closing.
