### ISSUE TITLE
Pencil Icons

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#400]
What do the pencil icons on the diagram signify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf71804-c91b-2464-3313-57b973ee5583
* Version Independent ID: b7803227-625d-9354-ef0e-1fb94407e835
* Content: [Recommended secure document policies - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/sharepoint-file-access-policies)
* Content Source: [microsoft-365/enterprise/sharepoint-file-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/sharepoint-file-access-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@BrendaCarter - Can you please share your insights on this issue?

Thank you.

**Comment by BrendaCarter** [comment]
Sorry this is not clear. The pencil icon indicates the policies that you need to update for the workload. In most cases you just need to make sure the workload is included in the scope of the policies, like Exchange Online. "The following diagram illustrates the common identity and device access policies and indicates which policies need to be updated to protect email."

**Comment by robmazz** [comment]
Closing per Brenda's response
