### ISSUE TITLE
Shared mailbox direct logon

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#4002]
Hello,
Still not clear, is it possible to use Shared mailbox for direct logon only to Exchange Online services, as for example for scanner, can we set up some shared: scanner@domain.com, reset a password via Azure/Admin and add it into scanner settings (same for some web apps, like a ticketing system). I know it is working if we would be doing this and this document informs when to use license for a shared mailbox: https://docs.microsoft.com/en-us/microsoft-365/admin/email/remove-license-from-shared-mailbox?view=o365-worldwide , so in our scenario, it is safe to use!? The general article also says that if a hacker can still creds of the shared mailbox then can access it, but the same happens with a normal user account and delegated access, only the hacker needs some time to test access to the GAL list of shared mailboxes of the organization by running some script wouldn't take a long time...

Just curious if we can use Shared mailbox and reset a password for it and use it for:
1. Scanner
2. Ticketing portal
3. Direct outlook setup, like secretary use only info@domain.com 100% of her working time
**It is working now,** but is it allowed? what will be happening if we use like this long time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289f2440-9c44-7d93-20e3-baa9e9892cd9
* Version Independent ID: abc4e209-a071-d28a-cb01-aa72bbaee7c0
* Content: [About shared mailboxes - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/about-shared-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/about-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/about-shared-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. A shared mailbox is not intended for direct sign-in via outlook, ticketing tool, or a device like a scanner by its associated user account. You should always block sign-in for the shared mailbox account and keep it blocked. It is not designed for that and If you would like to use it with a password assigning the license is the correct way.

Hope this helps!

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba 
Thanks, Sri! Strange that it is not well explained in this document and most advanced IT knows that it is working just fine even without a license... and the sentence "it is not designed" doesn't really say it is not allowed to use this way :) so a little bit confused, especially knowing some setups based on Microsoft docs, where in the Windows Servers 2019 we must follow steps from Windows Server 2003 as an example... On one side I can understand your strategy and if you find that it is nothing to update in the doc, like a more clear explanation, then you can close this case.

**Comment by msbemba** [comment]
@lightupdifire Every shared mailbox has a corresponding user account. Notice how you weren't asked to provide a password when you created the shared mailbox? The account has a password, but it's system-generated (unknown). You aren't supposed to use the account to log in to the shared mailbox. More details can be found here - https://docs.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox?view=o365-worldwide#block-sign-in-for-the-shared-mailbox-account

 I have added this to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4034

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba 
In the last 5 years, for about 1000 users, I have integrated all services from Microsoft 365 E3 license, but before that, I have migrated Exchange 2016 on-premise to Exchange Online, AD DS to AD Connect + AD FS, File Servers to SharePoint Online, SCCM to Intune, user MFA to Conditional Access MFA, data protection to DLP and AIP, on-premise legacy tools to RDS and WVD, so I have noticed A LOT :)
But have you noticed that you can **Enable** a Shared mailbox and **reset** a password for it and **use** it together with Conditional Access MFA so the account stays protected **with MFA**?
Thanks for calling the new PR! will wait for an update.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lightupdifire Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
