### ISSUE TITLE
Consolidate similar instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4003]
Please do something to consolidate/cross-reference the instructions on this page and those on https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-install-prerequisites#prepare-your-on-premises-data and on https://microsoft.github.io/idfix/

They are similar but different, its confusing to have 3 different sets of instructions about how to prepare for syncing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b05a56d-f714-2d99-747e-b3150f581f38
* Version Independent ID: e8924d3f-20e7-6ce2-2279-cec010e7d3f3
* Content: [Prepare for directory synchronization to Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-for-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. I Shall consolidate and update the document accordingly.

Thanks
Sri

**Comment by JoeDavies-MSFT** [comment]
@DeanGross Hi Dean. I have asked the writer of the Azure AD article to correct their reference to the IDFix content back to this article. IDFix is a deprecated tool. After the fix, the single source of AD DS domain preparation will be this article.

**Comment by msbemba** [comment]
@yogkumgit  There are no changes in the document as of now and the other document (Azure AD article) will be fixed by another writer and this one can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
