### ISSUE TITLE
Unable to enable preview features

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4005]
WHen I look at the settings page, I don't see an option to enable preview features. What admin role is required? please update this page to state this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d5414b-78ef-79a6-7cd3-5f67ee2ae6f9
* Version Independent ID: 617f3b58-2cc2-2413-7a00-eb0ba912a3e8
* Content: [Preview features in Microsoft 365 Defender - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/preview?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/preview.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. I have added the required permissions to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4073


Accounts assigned the following Azure Active Directory (AD) roles can Turn On  Microsoft 365 Defender Preview features

- Global administrator
- Security administrator
- Security Operator
- Global Reader

Thanks
Sri

**Comment by DeanGross** [comment]
Thanks, but are you sure that Global Reader can do this, that does not seem appropriate

**Comment by msbemba** [comment]
@DeanGross Thank you. I have updated the PR accordingly.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
