### ISSUE TITLE
"Block URL (time-of-click)" - Details

### ISSUE THREAD

**Issue by ChrisOnSecurity** [MicrosoftDocs/microsoft-365-docs#4007]
Details about "Block URL (time-of-click)" are not provided in the table.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433c88d2-30bd-1e6c-eeb9-1d16b203d4f1
* Version Independent ID: 858e20e0-1e2f-2bae-ed28-da4e1de34c44
* Content: [Remediation actions following automated investigation in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/air-remediation-actions?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/air-remediation-actions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/air-remediation-actions.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@ChrisOnSecurity Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4107

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChrisOnSecurity Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
