### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by rpsenski** [MicrosoftDocs/microsoft-365-docs#4009]
![image](https://user-images.githubusercontent.com/18269794/106153088-03ce2500-6133-11eb-89fa-59adab578a16.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81ee4664-d4a2-025d-6ec6-1f87b0c5864c
* Version Independent ID: 7d3c0489-b5bd-502e-91f5-297231ef430a
* Content: [Microsoft Productivity Score - Communication - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/productivity/communication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/productivity/communication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/productivity/communication.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rpsenski Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
