### ISSUE TITLE
Pencil icons

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#401]
What do the pencil icons signify on the diagram above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18267b13-4890-4196-16e8-e183ece73d70
* Version Independent ID: 64887e62-4187-cb6e-fbb3-ff7e12a18841
* Content: [Secure email recommended policies - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/secure-email-recommended-policies)
* Content Source: [microsoft-365/enterprise/secure-email-recommended-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/secure-email-recommended-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
This issue is similar to #400.

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting this feedback.

I will get this over to @BrendaCarter  for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by BrendaCarter** [comment]
Sorry this is not clear. The pencil icon indicates the policies that you need to update for the workload. In most cases you just need to make sure the workload is included in the scope of the policies, like Exchange Online. "The following diagram illustrates the common identity and device access policies and indicates which policies need to be updated to protect email."

**Comment by robmazz** [comment]
Closing per Brenda's response
