### ISSUE TITLE
Downloading ISO Troubles

### ISSUE THREAD

**Issue by ttricktt** [MicrosoftDocs/microsoft-365-docs#402]
Hello,
In the latest lab document (1903) that refers to downloading the Windows 7, W10 1809, and W10 1903 images. The links bring you to a page that says (Unable to Service Request). I tried several times and made sure I was logged into the Microsoft site. Different browsers didn't help either. 

Thanks for your hard work developing these labs!
Rick M.

**Comment by mypil** [comment]
@ttricktt - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by ttricktt** [comment]
From the Lab Guide, Updated: June 11, 2019
Page 22, Download Windows 7 ISO, https://msdn.microsoft.com/subscriptions/securedownloads/
Page 23, Download Windows 10 1809 ISO, https://msdn.microsoft.com/subscriptions/securedownloads/
Page 23, Download Windows 10 1903 ISO, https://msdn.microsoft.com/subscriptions/securedownloads/

**Comment by mypil** [comment]
@ttricktt - Can you please share the URL link for that Lab Guide? 

The link (https://msdn.microsoft.com/subscriptions/securedownloads/) that you shared does not seem to be part the microsoft-365-docs repository. 

Thank you.

**Comment by ttricktt** [comment]
https://www.microsoft.com/en-us/evalcenter/evaluate-lab-kit
After you click the link to download the zip file you're brought to a page that offers the lab or the MDlab_1903_lab guides.zip file. I'm using the 1903 lab guide.

**Comment by mypil** [comment]
@ttricktt - This Lab Guide doc link (https://www.microsoft.com/en-us/evalcenter/evaluate-lab-kit) that you shared also does not appear to be part of the microsoft-365-docs repository.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. 

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

**Comment by robmazz** [comment]
Closing per recommendation to contact MS Support
