### ISSUE TITLE
Great sample script - Is there one that works for an MFA enabled admin account?

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/microsoft-365-docs#4020]
Many of the sample scripts are great, but many times admins now have MFA enabled and that changes this process completely. These scripts now do not run correctly. Is there an effort to help bring some of these samples to a more secure process (with an MFA enabled account)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b759021-39d7-0383-2f50-b5b813217f97
* Version Independent ID: 5f5dfeab-1160-3994-2cb8-1ca7c67e3ff2
* Content: [Use a script to add users to a hold in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-a-script-to-add-users-to-a-hold-in-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@Jmartinez589 Thank you for your feedback. 

To run PowerShell scripts, create a service account with a strong password and don't enable the account for two-step verification.

After Azure AD Multi-Factor Authentication is enabled on a user's account, app passwords can be used with most non-browser clients like Outlook and Microsoft Skype for Business. However, administrative actions can't be performed by using app passwords through non-browser applications, such as Windows PowerShell. The actions can't be performed even when the user has an administrative account.

Hope this helps!

Thanks
Sri

**Comment by markjjo** [comment]
@Jmartinez589 Thanks @msbemba for the information. Here is more info about App passwords: https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2

Also, I will update the script in this topic to use modern auth to connect to SharePoint Management Shell. And close both PS session when script is complete.
