### ISSUE TITLE
Incorrect screen shot, steps to assign licenses incorrect or obsolete on "Set up SharePoint Syntex" page

### ISSUE THREAD

**Issue by mcox13579** [MicrosoftDocs/microsoft-365-docs#4024]
The "Assign licenses" section of the "Set up SharePoint Syntex" page contains an incorrect/obsolete screen shot and the steps documented are incorrect or obsolete.
The "Assign licenses" section specifies step #3 is to "Select **Assign more**."  When I select "Manage product licenses," the right-side panel is displayed as shown below. 

![image](https://user-images.githubusercontent.com/12144220/106338666-39653200-6249-11eb-8ac3-f3339f1b0382.png)

There is no "Assign more" link or button on this screen. Therefore, the steps are impossible to follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding?source=docs)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@mcox13579 Thank you for your feedback. the screenshot is correct, but the navigation has changed as assign more option is not available anymore.

After you click on manage licenses-->Apps--> Shows apps for Sharepoint syntex. I have updated the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4075

Note that Sharepoint syntex is an addon that needs to be purchased separately. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mcox13579 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
