### ISSUE TITLE
To get started, turn on your location opt-in setting to automatically collect data from devices using Windows Location Services, go to your Locations list to add or upload location data, or have someone run the Microsoft 365 network connectivity test from your office locations.

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/microsoft-365-docs#4028]
https://admin.microsoft.com/adminportal/home?#/networkperformance
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e748ed-63fe-0d00-6b60-c1a778797afa
* Version Independent ID: 3cd66c90-ed09-7c28-7dbb-0a11769f8033
* Content: [Network connectivity in the Microsoft 365 Admin Center (preview) - Microsoft 365 Enterprise](https://docs.microsoft.com/en-US/microsoft-365/enterprise/office-365-network-mac-perf-overview?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/office-365-network-mac-perf-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/office-365-network-mac-perf-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@matuhinal Thank you for your feedback. We have added the phrase to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4074

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @matuhinal Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
