### ISSUE TITLE
Page does not make it clear where custom MMD roles can be assigned

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/microsoft-365-docs#4029]
In many cases, it is preferable to add roles to existing AAD groups. To do so is not clarified in this page. It refers to the 'custom MMD roles' but not where they can be assigned.

According to a support ticket (222597197) this is supposed to be done from the _Modern Workplace Customer APIs_ entry in Enterprise Applications. EDIT: Actually that's not present in our tenant... so I'm not sure what we're supposed to do. Asking for further clarity in the ticket, but perhaps this will get updated in the meantime.

Please clarify this page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c08614-27d9-ebce-ca7b-4892e2d26405
* Version Independent ID: 8cfc0923-6899-e317-f8e8-ac867842934e
* Content: [Access the Admin portal - Microsoft Managed Desktop](https://docs.microsoft.com/en-gb/microsoft-365/managed-desktop/get-started/access-admin-portal?view=o365-worldwide&WT.mc_id=Portal-Microsoft_EMM_ModernWorkplace)
* Content Source: [microsoft-365/managed-desktop/get-started/access-admin-portal.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/access-admin-portal.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@StuEwen , tried to assign this to you, but I guess you don't have the right perms. In any case, can you make edits to clarify the article or otherwise help this person?

**Comment by yogkumgit** [comment]
@StuEwen Please add your comment and help us in resolving this issue. Thanks

**Comment by jaimeo** [comment]
I believe Stuart made an edit to this article in response to this already.... @StuEwen ?

**Comment by yogkumgit** [comment]
@StuEwen Thank you very much for  updating the documentation with PR #4060 . @webash Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by webash** [comment]
This is great! thanks all!
