### ISSUE TITLE
deactivated and not available for Password attack campaigns in the new security console - you reduce features???

### ISSUE THREAD

**Issue by Pascal-KOTTE** [MicrosoftDocs/microsoft-365-docs#4031]
Password attack campaigns 
deactivated and not available in the new security console - you reduce features???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbdcbd5-7bd2-6b55-b72c-cbedfdea776c
* Version Independent ID: 1e6198f8-6ef1-6227-c9e8-f31944a5d1db
* Content: [Attack Simulator in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulator.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Pascal-KOTTE, I suggest that you open a support case and/or an issue at <https://office365.uservoice.com/>.

**Comment by yogkumgit** [comment]
@chrisda  Thank you very much for sharing this explanation. @Pascal-KOTTE Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
