### ISSUE TITLE
Instructions do not work for GCC customers

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/microsoft-365-docs#4033]
Please update this article to call out the steps that do not work in GCC, and provide instructions for how GCC users can leverage the PBIX file and then publish to Power BI Online service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebdb9f0-76a5-eebc-4cd7-95f5407ed029
* Version Independent ID: 05abf201-e31c-08c0-a7fc-8fd46202e8b0
* Content: [Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by yogkumgit** [comment]
@scotvidican Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us here. Thanks

**Comment by cmcatee-MSFT** [comment]
@yogkumgit I've assigned this to @efrene to look into. He now owns most of sirkkuw's old topics.

**Comment by yogkumgit** [comment]
@efrene Please reply and resolve this issue. Thanks.

**Comment by efrene** [comment]
@npherson, Thanks for your patience. I have recently taken over this task as will be looking into your suggested changes this week.

**Comment by CJScott88** [comment]
Hello @efrene any progress on this? We have another customer that is using an older legacy version of this report that is no longer working properly and would like to update.

**Comment by efrene** [comment]
@CJScott88 Sorry,  I got a bit delayed in addressing this. I will make sure to make time for this over the next few days.

**Comment by efrene** [comment]
@npherson - Just checking to see if you had a chance to review the draft yet. Thanks.

**Comment by npherson** [comment]
Thank you so much for the ping - I had completely lost track of this!!! I'll try to get you notes quick.

**Comment by efrene** [comment]
Closing issue.
