### ISSUE TITLE
Export to PDF does not export this page

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#404]
When I download PDF I do not see this page in PDF&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 632c11fa-8975-afd4-a050-7ff42ca3eb33
* Version Independent ID: 2b736015-0f61-4159-e102-77a056f8abec
* Content: [Office 365 Data Service Requests Under the GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-dsr-office365?toc=%2Fmicrosoft-365%2Fenterprise%2Ftoc.json#feedback)
* Content Source: [microsoft-365/compliance/gdpr-dsr-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-dsr-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@robmazz - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@Larryngolog - Can you share more details about this issue that you have? Which portion of this document are you referring to?

**Comment by Larryngolog** [comment]
Hi! It looks like I must have overlooked something. Now when I clicked on the download PDF I got document with everything I needed. Sorry for wasting your time.

**Comment by mypil** [comment]
@Larryngolog - We're glad to know that your issue has been resolved already. I will proceed to close this issue now.

Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you for your contribution to make the docs better!

**Comment by mypil** [comment]
@officedocsbot close
