### ISSUE TITLE
Retention Policies vs. Retention Labels with Label Policies

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/microsoft-365-docs#4046]
Under the section: Retention policies and retention labels

I suggest to change:
You can use both retention policies and retention labels with label policies to assign your retention settings to content.

With:
You can configure the retention settings to be applied to you content using either of the following options:
- Retention Policies
- Retention Labels with Label Policies

Reason:
It's way clearer that two options are available and which ones they are. You don't know how much time it took me to figure that out. All this time hiding right under my nose, lol

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by ingepepe** [comment]
Oh wow, I didn't see that one coming! lol
Thanks for letting me know. I'll look into it.

________________________________

**Comment by cabailey** [comment]
Updated the text to "To assign your retention settings to content, use **retention policies** and **retention labels with label policies**. You can use just one of these methods, or combine them."

Hopefully that makes it clearer.  I opted for bolding the two methods rather than put them in a bullet list that at first glance might look like you have choose one or the other.

**Comment by ingepepe** [comment]
I like it!

________________________________

**Comment by cabailey** [comment]
Great - in that case, I'll close this issue.  Thanks for your feedback!
