### ISSUE TITLE
Why you're not posting price for adding additional SharePoint storage?

### ISSUE THREAD

**Issue by ichkoj** [MicrosoftDocs/microsoft-365-docs#4047]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@ichkoj  We don't include pricing for any add-ons in our articles, because prices will vary based on locale and currency. The best way to find out how much any given add-on will cost is to look on the [Purchase services](https://go.microsoft.com/fwlink/p/?linkid=868433) page.

**Comment by ichkoj** [comment]
So you must buy FIRST some of your products in order to see the price ... how do you plan
________________________________
