### ISSUE TITLE
Alterities to the URL pattern of "*cdn.onenote.net"

### ISSUE THREAD

**Issue by MFisherIT** [MicrosoftDocs/microsoft-365-docs#4049]
When reviewing the list of URLs from the Office 365 IP Address and URL web service I found that an address under the common ([Microsoft 365 Common and Office Online](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online)) service area of **"\*cdn.onenote.com" (ID:51)** did not conform to the regular expression used for validation. Because the address does not conform to the following regular expression our firewalls will not be able to use the URL pattern specified. Regular Expression used for validation:
```regex
(\*\.)?([a-zA-Z0-9_](([a-zA-Z0-9_-])*[a-zA-Z0-9_])?\.)+([a-zA-Z])+
```
[Searching for the URL](https://www.bing.com/search?q=site%3Adocs.microsoft.com++%2B%22cdn.onenote.net%22+-%22non-Enterprise%22) I found Microsoft documentation referring to an address of "site-cdn.onenote.net". Assuming that the URL is pattern is correct, **can alterities to the URL pattern of "\*cdn.onenote.net" be listed? Would a pattern of "site-cdn.onenote.net" be sufficient or a wider pattern of "\*.onenote.net" be necessary?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
I'm looking into this with the web service PM.

**Comment by LauraWi** [comment]
Is your firewall able to use/validate the versions included in the Web service? This article is provided for human reference. Recommendation is to access them directly from the service. https://docs.microsoft.com/en-us/microsoft-365/enterprise/managing-office-365-endpoints?view=o365-worldwide
