### ISSUE TITLE
Notification emails do not notify all incidents and status update.

### ISSUE THREAD

**Issue by yutoy1439** [MicrosoftDocs/microsoft-365-docs#4054]
Please include a note in the following text.

========
To sign up for email notifications of new incidents that affect your tenant and status changes for an active incident, select Preferences > Email , click Send me service heath notifications in email , and then specify:

Up to two email addresses.
Whether you want notifications for incidents or advisories
The services for which you want notification
========

 If the service is restored immediately, or depending on the scope of the incident and advisory, email notifications may be skipped at the discretion of our data center.

As a precaution, is it possible to add a statement that notifications may be skipped?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d8b9c3-7ff2-d3b7-a0ce-0310171c71d5
* Version Independent ID: 7b45c0a3-94ca-b749-50e4-7d4cbf204764
* Content: [How to check Microsoft 365 service health - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-service-health?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/view-service-health.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@yutoy1439 Thank you for your feedback. I'm checking with the author and will update you shortly.

Thanks
Sri

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the documentation team. 

Closing this issue.

cc: @yogkumgit @msbemba
