### ISSUE TITLE
Missing detail of Microsoft default settings

### ISSUE THREAD

**Issue by deeksha-microsoft** [MicrosoftDocs/microsoft-365-docs#4055]
The documentation says " If you prefer, you can also choose to keep the default event threshold levels recommended by Microsoft", but does not give any info about what these defaults are? Please add description/sidenote or link to this info.
https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide#indicator-level-settings-preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Insider risk management settings - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@deeksha-microsoft Thank you for your feedback. I'm trying to get the default values so they can be documented. I shall update you once the PR is ready.

**Comment by robmazz** [comment]
@deeksha-microsoft - thanks for your feedback. New updates are coming in both the feature UI and documentation about this, please look for updates in the next few weeks. Thanks!
