### ISSUE TITLE
Wrong command

### ISSUE THREAD

**Issue by vivitribal** [MicrosoftDocs/microsoft-365-docs#4057]
It should be set-organizationconfig not set-organization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 749a8389-eda6-3059-b713-5d0b3755fe9c
* Version Independent ID: 53000b70-b561-ec33-0b94-f0c26650548b
* Content: [Use a QR code to sign-in to the Outlook mobile apps - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/use-qr-code-download-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/use-qr-code-download-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/use-qr-code-download-outlook.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@vivitribal Thank you for your feedback. The document is updated with set-oraganizationconfig. I have reviewed and the rest of the details look good. We will be closing this Issue as there are no changes required in the document.

CC: @yogkumgit 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @vivitribal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
