### ISSUE TITLE
Ori Epstein

### ISSUE THREAD

**Issue by martinrobson** [MicrosoftDocs/microsoft-365-docs#4058]
[Enter feedback here]

Are they related to Jeffry Epstein? 

Maybe change his name eh
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bec871b-790f-6826-b8f8-d1b7830c49ab
* Version Independent ID: 460db4e8-7f93-60a3-4889-f2d8f08fc75f
* Content: [Configure junk email settings on Exchange Online mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
I'll take that under advisement.

Closing
