### ISSUE TITLE
Able to SideLoad addins after Store is disabled

### ISSUE THREAD

**Issue by anPalmei** [MicrosoftDocs/microsoft-365-docs#4063]
Hi,

Currently if the Office Store is disabled users can still sideload addins. This happens online and on desktop app.

Can you please review issue #3121 where the note "Preventing users from accessing the office store will also prevent them from Sideloading Office Add-ins for testing." was added.

**Comment by msbemba** [comment]
@anPalmei Thank you for your feedback. This was not the case earlier in 2020 so I'll test and update the document if need be.

Thanks
Sri

**Comment by anPalmei** [comment]
@msbemba Hi, Thanks. Please keep me updated.

**Comment by msbemba** [comment]
@anPalmei Thank you for the feedback. I tested it does not work only when trying to Sideload Office Add-ins for testing from a network share (https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins). I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4160

Thanks
Sri

**Comment by SKjerland** [comment]
@yogkumgit - I merged PR#4160. Thanks! Closing this issue.
