### ISSUE TITLE
Licensing Information Is Incorrect

### ISSUE THREAD

**Issue by michaelcizmar** [MicrosoftDocs/microsoft-365-docs#4080]
I believe the license information is incorrect.  The Apps that you can assign via the License are:

- Graph Connectors Search with Index
- Topic Experiences

There does not seem to be a "Viva Topics license" anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6989b324-615d-47d2-fadb-5664c4dfeb13
* Version Independent ID: 2cc9f587-ac4f-a9ef-ab62-7a80923d65c2
* Content: [Set up Microsoft Viva Topics](https://docs.microsoft.com/en-us/microsoft-365/knowledge/set-up-topic-experiences#assign-licenses)
* Content Source: [microsoft-365/knowledge/set-up-topic-experiences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/knowledge/set-up-topic-experiences.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@yogkumgit note that I've updated this via an internal PR.

**Comment by yogkumgit** [comment]
@michaelcizmar document is updated through internal PR. Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
