### ISSUE TITLE
Default mailbox audit configuration appears out-of-date

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/microsoft-365-docs#4084]
The mailbox actions which are listed as audited by default for each of the three roles (Admin, Delegate, Owner) appear to be out-of-date with what's currently the case on Exchange Online.

For all three roles:
- The _MailItemsAccessed_ and _Send_ actions are documented as being audited by default but are not contained in the set of audited actions on a mailbox
- The _ApplyRecord_ action is included in the set of audited actions but is not documented as being audited by default

Verified against a new mailbox and a mailbox reset to the default audit configuration using the `Set-Mailbox -DefaultAuditSet Admin,Delegate,Owner` command. The audit actions for both mailboxes matched but are inconsistent with the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide#restore-the-default-mailbox-actions)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by markjjo** [comment]
@ralish Thanks for the feedback. ApplyRecord has been added to the default set for all logon types. I will update the documentation, so thanks for the heads up.

MailItemsAccessed and Send are E5 mailbox audit actions (also called ["crucial events" in Advanced Audit](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide#access-to-crucial-events-for-investigations)). So the mailbox must be assigned an E5 license (or add-on that supports Advanced Auditing). If user doesn't have appropriate license, then these two mailbox actions won't be assigned as audited by default. See this topic for steps on how to verify the licensing: https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit#set-up-advanced-audit-for-users

If licensing is correct and you think MailItemsAccessed and Send should be part of the default assignment, would suggest you contact MS Support.
