### ISSUE TITLE
SharePoint Syntex - Managed Metadata entity extractor not populating values from Synonyms

### ISSUE THREAD

**Issue by vigneshvdm** [MicrosoftDocs/microsoft-365-docs#4086]
I have created an extractor and added few labels

When the labels match the exact terms, the managed metadata column is getting populated. But when the label is defined as a synonym for a term in term store management, the column is not getting populated with the respective term.

For instance, I have a term called Metallurgy which has electrolyte, electrolysis defined as synonyms. When the document electrolyte it is not adding the term Metallurgy.

The labels are getting extracted, because I mapped the same label to a single line of text column and Syntex added the value electrolyte to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e87ae4b6-5ba5-4f94-94f7-d7a16a633e86
* Version Independent ID: 2486de11-2337-e1b7-3dbc-8fc94fd46e40
* Content: [Leverage term store taxonomy when creating an extractor](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/leverage-term-store-taxonomy)
* Content Source: [microsoft-365/contentunderstanding/leverage-term-store-taxonomy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/leverage-term-store-taxonomy.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by yogkumgit** [comment]
Duplicate #4085 Closing
