### ISSUE TITLE
Please remove the contradiction 

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/microsoft-365-docs#4087]
[Enter feedback here]

Hello : 

the document has a contradiction : 

At the beginning it says " You can also allow access to on-premises resources like line of business (LOB) apps, file shares, and printers.".

At the end it says " Users won't be able to authenticate to applications that depend on Active Directory authentication"
(that is false, AADJ computers are able to obtain Kerberos TGS from domain controllers to authenticate to legacy app (ok , not all, see below)

Must be correct in something like  " Users might be not able to authenticate to applications that depend on the presence of computer account object in Active Directory : evaluate the legacy app and consider updating to an app that uses modern Auth, if possible".

In my lab I tested successful authentication to legacy app : FileShare, IIS in kerberos mode, Remote Desktop-RestrictedAdmin, MSSQL Management Studio (SQL 2012). 

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ba9775-1242-af4d-a9c0-8979cc5d57dc
* Version Independent ID: 5063400b-fe96-79f4-e37f-6c89e26ee9d0
* Content: [Access on-premises resources from an Azure AD-joined device in Microsoft 365 Business - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/access-resources?view=o365-worldwide)
* Content Source: [microsoft-365/business/access-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/access-resources.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@dbona75 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4102

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dbona75 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
