### ISSUE TITLE
QR code sign-in for Azure Authenticator/My Sign-ins | Passwordless

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#4088]
Hello,

The QR code could be a good option for a Passwordless, as for "first time sign-in" option. 
Any ideas were to look to check how QR code sign-in can be implemented in Azure Authenticator setup or in access to My-Signs/MFA-setup page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 749a8389-eda6-3059-b713-5d0b3755fe9c
* Version Independent ID: 53000b70-b561-ec33-0b94-f0c26650548b
* Content: [Use a QR code to sign-in to the Outlook mobile apps - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/use-qr-code-download-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/use-qr-code-download-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/use-qr-code-download-outlook.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@lightupdifire Thanks again for your feedback. I checked and found Currently we only have the option to use QR code to add a School/work account o the authenticator but there is no option to implement a QR code sign-in in the Azure Authenticator setup or in access to My-Signs/MFA-setup page.

We will have a new document created when the feature becomes available.

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba 
Thanks, Sri! This QR code is like replacing username-password sign-in behavior, is it something that can be generated by ourselves, or only MS can do this for a moment?

**Comment by msbemba** [comment]
@lightupdifire I might have got confused. QR code is available now for Authenticator setup(adding account) but not for Azure or m365 portal login as of now. Do you mean you found  MS already using this feature to replace username and password?

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba 
No, I didn't find anything, I'm just re-reading all docs and look for a solution for "first-time sign-in with Passwordless",
I see a new option become available in Azure tenant called "Temporary access pass", but seems no doc for it as well.
Thanks for all effort, I hope new docs will come soon, so we can close this comment.

**Comment by c016smith** [comment]
Microsoft is actually deploying QR code to Sign-in via Outlook for Android and iOS.

Microsoft 365 Roadmap feature IDs and link below:
https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=69147
https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=69148

This is an essential user experience for the future of passwordless sign-in.   I am looking for this option to be included in Microsoft Teams IP Phone device, so users could see a QR code as part of the device sign-in experience, and just scan it with their Microsoft Authenticator app to be prompted/authorize a sign-in to the resource. 
Or use camera to trigger QR code which should open Authenticator (like QR code menus open a browser or custom app)
