### ISSUE TITLE
Reports > Usage page: hyperlink does not work

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/microsoft-365-docs#4089]
Reports > Usage page

The hyperlink on Usage does not go anywhere. I think it needs updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9262b85d-883b-2b04-07ee-d4120dc7669f
* Version Independent ID: 7244aa48-52b4-1bc3-7c94-f87061869e41
* Content: [Microsoft 365 Reports in the admin center - Microsoft Office activations - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft-office-activations?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/microsoft-office-activations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft-office-activations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@richard-artes Thank you for the feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4100

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @richard-artes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
