### ISSUE TITLE
The phone line does not appear to be operated

### ISSUE THREAD

**Issue by 2bad2furious** [MicrosoftDocs/microsoft-365-docs#4090]
I have contacted this phone line multiple times during the last few days from multiple phones at during times but always between 9AM - 6PM.  All I hear is something like "The line is experiencing large amount of poeple calling in." and "You can connect with our technician faster by creating a new ticket in the office administration panel".

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6249ede3-3a34-e982-3fb1-d79c9a0a056e
* Version Independent ID: f1846df0-d5a1-f7d7-79a9-8bccb6350204
* Content: [Support information for Czech Republic - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/support/czech-republic?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/czech-republic.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/czech-republic.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@2bad2furious I'm sorry to hear you're having trouble contacting support. Would you please send the following information directly to me (do not post your response here), at cmcatee@microsoft.com

- The # you tried to call from
- The support # you called
- Date of the call
- Time of the call, with time zone
- IVR options selected, if any
- Call results (description of the caller experience after calling)
- The type of subscription, or product you have that you called about

This information will help us troubleshoot this issue. 
Thanks,
Cern

**Comment by cmcatee-MSFT** [comment]
The licensing issue was resolved. However, support could find nothing wrong with the # for the Czech Republic. @2bad2furious, if the recording states that call volumes are high, please allow more time for a support agent to be available to take your call. If your issue doesn't require an answer immediately, then creating a ticket in the help pane of the admin center is a better way to go.
