### ISSUE TITLE
Using the Office 365 CDN for downloads?

### ISSUE THREAD

**Issue by ekdegerman** [MicrosoftDocs/microsoft-365-docs#4091]
In the section "Determine which static assets you want to host on the CDN", one of the examples listed as suitable for the Office 365 CDN is "Large files like executables and installation files". The section also says "Larger files such as installation executables can be downloaded from the CDN, delivering a positive performance impact and subsequent reduction of the load on your SharePoint Online site, even if they are not accessed as often.". We were hoping to try this out in our tenant, however, as far as I can tell, links to files are not rewritten to use either type of CDN even though it has been activated for the extension and origin in question. I can see the references to on-page images and scripts being rewritten, but if I create a link on the page to the same file it is still collected from SharePoint instead of the CDN. Same goes for downloads directly from the document libraries activated as origins. Do you have any details on how this is intended to work for files such as executables and installation files? Is there any out-of-the-box web part that would do the rewrite for downloads and allow our users to download them through the Office 365 CDN as described on this page? (the private one preferably)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cfe2b0-c14d-1083-7c88-a91e58593cfa
* Version Independent ID: 2d15076c-0dcd-6bd6-e0fb-f8ac5ffd0091
* Content: [Use Office 365 Content Delivery Network (CDN) with SharePoint Online - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by ekdegerman** [comment]
@kelleyvice-msft @yogkumgit Any update on this one?

**Comment by ekdegerman** [comment]
In addition to file links not being rewritten in SharePoint, there seem to be a size limitation in effect. If I try to manually create a URL for an asset in my public CDN origin and call it (testing with exe files), I seem to get a http error like the one below for anything larger than 50GB. This makes the statement about using it for large files like executables and installation files seem even more misleading, since they are quite likely to be larger than that. Googling the error code does not give me any useful documentation on this limitation. Please help clarify what is actually supported in this CDN.
{"HttpStatus":"NotAcceptable","ErrorMessage":"Asset exceeds allowed size limit","ErrorCode":406011}

**Comment by kelleyvice-msft** [comment]
Checking with the PG.

**Comment by kelleyvice-msft** [comment]
After investigation, I found that the current Microsoft 365 CDN does not in fact support executables. You can, if you like, configure a custom Azure CDN to accomplish this; see https://docs.microsoft.com/en-us/azure/cdn/ for details. I am revising our content to correct this mistake and clarify the supported file types and limitations. I apologize for the confusion, and I hope this adequately resolves your concerns. 
Kelley
