### ISSUE TITLE
Typo: Should be G3, not G5

### ISSUE THREAD

**Issue by scottyv** [MicrosoftDocs/microsoft-365-docs#4094]
There is typo on this page:
Microsoft 365 G5 subscription (paid or trial version)
Microsoft 365 G5 subscription + the Microsoft 365 G5 Compliance add-on
Microsoft 365 G5 subscription + the Microsoft 365 G5 Insider Risk Management add-on

The last two lines should says: G3 and not G5.

Scott
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb98e0ff-d34c-75bc-0ade-7dc70fc7f4bd
* Version Independent ID: 5172471f-e514-bcde-16e0-d8d8090a892a
* Content: [Get started with insider risk management - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-configure?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/insider-risk-management-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-configure.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@scottyv  - yes, thanks! I will correct now and republish.
