### ISSUE TITLE
Preview of encrypted emails

### ISSUE THREAD

**Issue by leenana365888** [MicrosoftDocs/microsoft-365-docs#4098]
The statement below implies that we will not be able to preview protected email messages:
![image](https://user-images.githubusercontent.com/76983722/107341743-54159180-6afa-11eb-947e-8fb18b38c440.png)

However in my tenant, I am able to preview them as the eDiscovery Manager.. emails that are protected by OME and those that are protected by sensitivity labels.

May I ask for your confirmation please?  Perhaps I just misunderstood the statement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f612d934-0811-53ad-14b9-e4d44eca9448
* Version Independent ID: 284b8ae6-51d5-7571-3f70-7824e34f94a8
* Content: [Export Content Search results - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-search-results?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/export-search-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-search-results.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@leenana365888 Thank you for your feedback. The statement clarifies that you can preview the decrypted file(attachment) when previewing them as the eDiscovery manager, but to view the entire message content you need to export the data. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @leenana365888 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
