### ISSUE TITLE
Moving from M365 E3 to Business Premium - Office apps

### ISSUE THREAD

**Issue by mitsubishop** [MicrosoftDocs/microsoft-365-docs#4099]
In this article it suggests the following when upgrading from M365 Business Premium to M365 E3.

"Your Microsoft 365 Apps for business client installed on your devices will automatically begin to use the features of Microsoft 365 Apps for enterprise. After migration, you can now use:"

Does this also work the opposite way round? Does moving from Office Apps for Enterprise to Office Apps for Business continue to work or is a re-install required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d1bfdf-f250-d2a1-17dc-36a8a305b82a
* Version Independent ID: a8d0892a-dfc9-e115-d77b-a191bf5423fc
* Content: [Migrate from Microsoft 365 Business to Microsoft 365 E3 - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/migrate-from-microsoft-365-business-to-microsoft-365-enterprise?view=o365-worldwide)
* Content Source: [microsoft-365/business/migrate-from-microsoft-365-business-to-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/migrate-from-microsoft-365-business-to-microsoft-365-enterprise.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@mitsubishop Moving back to Microsoft 365 Business would not require a re-installation. Thanks for your question.
