### ISSUE TITLE
Bad links on page https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-a-shared-mailbox?view=o365-worldwide

### ISSUE THREAD

**Issue by Bob-Fx** [MicrosoftDocs/microsoft-365-docs#4101]
[Shared mailboxes link opens page with error > Something went wrong and we couldn't get the page to display.
Error code: ‎c9eb3027-29b8-41fc-9566-61fd419821ca‎]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198eb002-1d99-5a13-05d4-34d1cbb8d9d9
* Version Independent ID: 6218b3c9-f0a2-ed0e-ef0a-c99c3c280030
* Content: [Configure shared mailbox settings - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-a-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-a-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@Bob-Fx Thank you for your feedback. I have checked the document and all links that point to shared mailboxes are live and not broken. You will need to be an admin to sign in to the shared mailboxes page.  Try on an Edge(in private browsing) and let me know if you still have an issue.

Thanks
Sri

**Comment by Bob-Fx** [comment]
I just tried the links and they are now working correctly (using Chrome).
Not sure what was broken the other day.

Thanks for the followup!

Regards,

Bob Fenske
Network Systems Manager

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Bob-Fx Glad that problem resolved. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
