### ISSUE TITLE
missing guides

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4105]
There used to many TLGs, now this page only has a link to one, what happened to the others?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 078ede0e-a27c-1aeb-bf64-7a0da4839dbd
* Version Independent ID: d17b3b15-5e9e-ec9c-d1f0-921dec05a89b
* Content: [Test Lab Guides for solutions and scenarios](https://docs.microsoft.com/en-us/microsoft-365/solutions/test-lab-guides-overview-solutions?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/test-lab-guides-overview-solutions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/test-lab-guides-overview-solutions.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@DeanGross Hi Dean. I have added a link in this article to the larger set of Microsoft 365 Test Lab Guides at https://docs.microsoft.com/en-us/microsoft-365/enterprise/m365-enterprise-test-lab-guides?view=o365-worldwide. The update should publish today. Thanks for letting us know.
