### ISSUE TITLE
issue with microsoft feedback

### ISSUE THREAD

**Issue by rsgmodelworks** [MicrosoftDocs/microsoft-365-docs#4116]
requiring a github login for feedback on help pages is unhelpful.  the old system was better.  wanting me to  identify myself would be one thing but requiring a login is intrusive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073882cd-36d0-b95a-77b2-aadd06fa34a5
* Version Independent ID: 463f2f77-3fb0-8078-5b49-878747f2842b
* Content: [Responding to a Compromised Email Account - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by denisebmsft** [comment]
Hello @rsgmodelworks. Thank you for posting this! There are two ways to submit feedback: (1) Open an issue (as you have done here); and (2) Use the "Is this page helpful?" rating mechanism. As soon as you choose Yes or No, you can submit your feedback. Verbatims from #2 come in anonymously.... that is, you shouldn't have to sign in to leave a comment that way.
