### ISSUE TITLE
not the page microsoft hands out

### ISSUE THREAD

**Issue by rsgmodelworks** [MicrosoftDocs/microsoft-365-docs#4117]
as of yesterday 2/8/2021 this is not the page microsoft hands out when you talk to support.  It would be good if thee things were consistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073882cd-36d0-b95a-77b2-aadd06fa34a5
* Version Independent ID: 463f2f77-3fb0-8078-5b49-878747f2842b
* Content: [Responding to a Compromised Email Account - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by denisebmsft** [comment]
Hello @rsgmodelworks. Thank you for the feedback! Can you tell us which page you were pointed to when talking to support? It will help us resolve the issue.

**Comment by msbemba** [comment]
@rsgmodelworks Thank you for your feedback. I reviewed the entire document and this should indeed be the right page for an admin to look at when such a situation arises. Are you saying the support team at Microsoft is not providing this link or not following the steps mentioned in this document?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rsgmodelworks Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
