### ISSUE TITLE
issue using github for feedback

### ISSUE THREAD

**Issue by rsgmodelworks** [MicrosoftDocs/microsoft-365-docs#4118]
when you click the github link for feedback it drops you into github making it difficult to get back to the page you were looking at.  Giving feedback should split off to a separate page, not act as a roach motel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073882cd-36d0-b95a-77b2-aadd06fa34a5
* Version Independent ID: 463f2f77-3fb0-8078-5b49-878747f2842b
* Content: [Responding to a Compromised Email Account - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by denisebmsft** [comment]
Hello @rsgmodelworks. Thank you for posting your feedback here. We will pass it to our GitHub team. As this isn't a specific documentation issue, I am going to close this issue for now. However, please know that your feedback will be shared with the correct team.
