### ISSUE TITLE
"SharePoint Information Rights Management (IRM) and sensitivity labels" section

### ISSUE THREAD

**Issue by yoshimin-msft** [MicrosoftDocs/microsoft-365-docs#4119]
Hi
In this section "SharePoint Information Rights Management (IRM) and sensitivity labels", there is a statement about he behavior  
 when we can use both protection solutions together as follows:

"If you label a file using Office on the web, any encryption settings from the label are enforced. For these files, coauthoring, eDiscovery, DLP, and search are supported."

However, it seems like we can't apply labels enabling IRM feature on the library.

Could I make sure if this statement is correct or there is any condition that it should meet to work along the statement?

**Comment by yogkumgit** [comment]
@yoshimin-msft Please indicate which document you are referring to and have feedback about. Thanks

**Comment by yoshimin-msft** [comment]
Hi
Thanks for checking my request.

Here is the link that includes the statement that I would like to make sure of.
https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide#sharepoint-information-rights-management-irm-and-sensitivity-labels

From my test, with Office on the web, I can always open the documents on the IRM enabled library with view-only, regardless what permission I have, so I could apply any labels. 

I'm sorry If I'd read it wrong but I'd appreciate if you could check it.

Thanks

**Comment by yogkumgit** [comment]
@cabailey Please add your comment and help us in resolving this issue. Thanks.

**Comment by cabailey** [comment]
@yoshimin-msft  If labeled and enabled documents open as expected in libraries that aren't configured for SharePoint IRM, please open a support ticket for investigation.

**Comment by Kaypyosh** [comment]
@cabailey thanks.

If IRM setting is disabled, I can apply labels. That's normal behavior without IRM setting. However the statement is described about the case when the IRM setting is enabled. "**using both protection solutions together**" means the sensitivity label and the IRM configuration are both enabled, doesn't it?

----
However, you can **use both protection solutions together** and the behavior is as follows:

 If you label a file using Office on the web, any encryption settings from the label are enforced.

**Comment by yoshimin-msft** [comment]
@cabailey thanks

If the IRM setting is disabled, I can apply labels. That's normal behavior without IRM setting. 

However, the statement is described about the case when the IRM setting is enabled. "**using both protection solutions together**" means the sensitivity label and the IRM configuration are both enabled, doesn't it?

----
However, you can **use both protection solutions together** and the behavior is as follows:

If you label a file using Office on the web, any encryption settings from the label are enforced. For these files, coauthoring, eDiscovery, DLP, and search are supported.

**Comment by cabailey** [comment]
Yes, the expected behavior is you can use both together as documented  Please follow up with Support - they can always contact me internally.
