### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by bahnjee** [MicrosoftDocs/microsoft-365-docs#412]
Link is broken again/still.  Immediate error "Couldn't download - Network issue."  That's the message that Edge-Dev gives but all browsers fail with similar messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office Deployment Lab Kit](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@bahnjee - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@bahnjee - Which portion / link within this document are you referring to?

**Comment by bahnjee** [comment]
"Download the Windows and Office Deployment Lab Kit"

The first link tries to download, but fails as I described earlier.
[https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab#download-the-windows-and-office-deployment-lab-kit
](url)

The second link (farther down the page) to same leads to a more generic page, asking me to "Get Started".  I'm already started...just need to download the kit.
([https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab#download-the-windows-and-office-deployment-lab-kit-1])

**Comment by mypil** [comment]
@JGruszczyk - Can you please share your insights on this issue?

**Comment by JGruszczyk** [comment]
The first link is working for me: https://www.microsoft.com/evalcenter/evaluate-lab-kit

I have submitted a change to update the second link to the first. If you are receiving network errors trying to download the lab kit that is not a Docs issue
