### ISSUE TITLE
Add info to paragraph around reducing licenses.

### ISSUE THREAD

**Issue by imcdnzl** [MicrosoftDocs/microsoft-365-docs#4123]
In the section "What if I don't see the Buy licenses or Remove licenses buttons?"

I would modify this paragraph:
See Add licenses to a subscription paid for using a product key.

to:
See Add licenses to a subscription paid for using a product key. When you add an extra product key, this will also allow you to reduce the existing license count if you wish.

The reason for this change is that it's not obvious when using a product license key how to reduce licenses and I faced this when I applied a key today.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 614340fe-7189-b055-d1c8-cce70407c310
* Version Independent ID: 5b660e44-5e3a-d2a0-023c-d6bfac287636
* Content: [Buy or remove licenses](https://docs.microsoft.com/en-gb/microsoft-365/commerce/licenses/buy-licenses?view=o365-worldwide#what-if-i-dont-see-the-buy-licenses-or-remove-licenses-buttons)
* Content Source: [microsoft-365/commerce/licenses/buy-licenses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/buy-licenses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by imcdnzl** [comment]
In case it's not clear this is for page https://docs.microsoft.com/en-gb/microsoft-365/commerce/licenses/buy-licenses?view=o365-worldwide#what-if-i-dont-see-the-buy-licenses-or-remove-licenses-buttons

**Comment by msbemba** [comment]
@imcdnzl Thank you for your feedback. We have added the statement to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4148 . Once the author approves, the changes will be live in the next 48 hours.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please merge this PR. Thanks

**Comment by cmcatee-MSFT** [comment]
No change needed at this time.
