### ISSUE TITLE
Information about the importance of the email address

### ISSUE THREAD

**Issue by Eternal-student** [MicrosoftDocs/microsoft-365-docs#4125]
It might be worth explicitly saying whether the email address used to verify the delisting is important.  ie. as an MSP I'm not sure if using my own company email address will work or whether I need to use my customers email address and domain (or in fact the printer's email address which is what I'm trying to sort out) to delist the IP address.
Many thanks,
Eternal-student

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Remove yourself from the blocked senders list - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Eternal-student Thank you for your feedback.  Ensure that you use the email address to which the error message was sent to remove the account from the blocked sender's list. This has been added to the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Eternal-student Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
