### ISSUE TITLE
How to use DKIM

### ISSUE THREAD

**Issue by DJHConsult** [MicrosoftDocs/microsoft-365-docs#4126]
Reference your webpage https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide.  I have been in contact with the o365sup@microsoft.com case reference: 23884876.

The recommended host settings for DKIM CNAME Configuration entries for all entries in for custom domains are listed in this page as;

Host name:            selector1._domainkey
Points to address or value:    selector1-cohovineyard-com._domainkey.cohovineyardandwinery.onmicrosoft.com
TTL:                3600

Host name:            selector2._domainkey
Points to address or value:    selector2-cohovineyard-com._domainkey.cohovineyardandwinery.onmicrosoft.com
TTL:                3600

Host name:            selector1._domainkey
Points to address or value:    selector1-cohowinery-com._domainkey.cohovineyardandwinery.onmicrosoft.com
TTL:                3600

Host name:            selector2._domainkey
Points to address or value:    selector2-cohowinery-com._domainkey.cohovineyardandwinery.onmicrosoft.com
TTL:                3600

It is not possible to follow this instruction in the Godaddy DNS service as they require the host connectors to be unique values.  The selectors I used to enter the necessary CNAME records and successfully enable DKIM are listed below for the following domain and it's sub domains;

djhitco.uk

selector1._domainkey

marketing.djhit.co.uk

selector1._domainkey.marketing

operations.djhit.co.uk

selector1._domainkey.operations

This appears to confuse your support desk as well as it took us several days to sort out.

Regards,
Duncan

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@DJHConsult Thank you for your feedback. This paragraph that you pointed talks about adding DKIM/DNS records to the custom domains. So each custom domain will have these DKIM values and they will be unique and not on the same page.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DJHConsult Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
