### ISSUE TITLE
Question about Topic Discovery

### ISSUE THREAD

**Issue by meganbM365** [MicrosoftDocs/microsoft-365-docs#4127]
How long should it take the AI to discover and start suggesting Topics?

For reference: We set everything up on Feb 5 and have 0 suggested topics five days later. Perhaps this indicates a problem, but the documentation gives no indication of when we should consider troubleshooting...

**Comment by denisebmsft** [comment]
Hello @meganbM365! Can you please tell us to which article(s) your question applies? This will help us route this issue to the correct writer/team.

**Comment by meganbM365** [comment]
https://docs.microsoft.com/en-us/microsoft-365/knowledge/topic-experiences-discovery
"979c48e9-93d6-1e8e-4d17-8f47a1313219"

**Comment by meganbM365** [comment]
Found answer 👉 [here ](https://techcommunity.microsoft.com/t5/microsoft-viva-blog/introducing-microsoft-viva-topics/bc-p/2116438/highlight/true#M54)👈

> it takes about _two days to two weeks_ for AI to fetch and index and then Topics to display any info

(em added)

**Comment by yogkumgit** [comment]
@meganbM365 Thank you very much for sharing this explanation. If you see a documentation update is required, please feel free to open an issue for the same. As question is resolved, we proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
