### ISSUE TITLE
Conflicting Documentation

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/microsoft-365-docs#4128]
These example on how to enable archive on this page contradict the page below.

**You should not use the ArchiveStatus property value to check the status of the archive**
https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/archivestatus-set-none

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@stephenc01 Thanks for the heads up about this and the link to the troubleshooting topic.

I will update the cmdlet examples in this topic to filter on ArchiveGuid (as mentioned in the troubleshooting topic), instead of ArchiveStatus. For example:

Get-Mailbox -Filter {ArchiveGuid -eq "00000000-0000-0000-0000-000000000000" -AND RecipientTypeDetails -eq "UserMailbox"}

and

Get-Mailbox -Filter {ArchiveGuid -ne "00000000-0000-0000-0000-000000000000" -AND RecipientTypeDetails -eq "UserMailbox"}

**Comment by krlrp** [comment]
عليق
تعليقات
تضمين التغريدة stephenc01 علق on 11 Feb
تتعارض هذه الأمثلة حول كيفية تمكين الأرشيف في هذه الصفحة مع الصفحة أدناه.

يجب ألا تستخدم قيمة خاصية ArchiveStatus للتحقق من حالة الأرشيف
https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/archivestatus-set-none

تفاصيل المستند
⚠ لا تقم بتحرير هذا القسم. وهو مطلوب من أجل docs.microsoft.com ➟ GitHub ربط المشكلة.

المعرف: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
معرف الإصدار المستقل: 3b513017-641c-38ae-3938-03a9ee3a6923
المحتوى: قم بتمكين علب بريد الأرشيف في مركز الأمان والتوافق - التوافق مع Microsoft 365
مصدر المحتوى: microsoft-365 / الامتثال / enable-archive-mailboxes.md
الخدمة: o365-seccomp
تسجيل الدخول إلى جيثب: markjjo
الاسم المستعار لـ Microsoft: markjjo
تضمين التغريدة ماركيجو علق on 11 Feb
@ stephenc01 نشكرك على التنبيهات حول هذا الموضوع والارتباط الخاص بموضوع استكشاف الأخطاء وإصلاحها.

سوف أقوم بتحديث أمثلة cmdlet في هذا الموضوع للتصفية على ArchiveGuid (كما هو مذكور في موضوع استكشاف الأخطاء وإصلاحها) ، بدلاً من ArchiveStatus. على سبيل المثال:

Get-Mailbox -Filter {ArchiveGuid -eq "00000000-0000-0000-0000-000000000000" -AND RecipientTypeDetails -eq "UserMailbox"}

و

Get-Mailbox -Filter {ArchiveGuid -ne "00000000-0000-0000-0000-000000000000" -AND RecipientTypeDetails -eq "UserMailbox"}
