### ISSUE TITLE
Link to Reports > Usage not working

### ISSUE THREAD

**Issue by anomalousdigitalemissions** [MicrosoftDocs/microsoft-365-docs#4129]
Under the "Enable the template app" section, the "Usage" link is out of date.

Current link is https://go.microsoft.com/fwlink/p/?linkid=2074756, which redirects to https://admin.microsoft.com/Adminportal/Home?#reportsUsage, but returns error code: ‎ee24da56-82e7-47e1-8a37-475a4202d436‎.

The correct redirection link is probably https://admin.microsoft.com/#/reportsUsage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@anomalousdigitalemissions thank you for your feedback. I'm able to access the links without any issues,.could you please check on in-private browsing and see if it works?

Thanks
Sri

**Comment by anomalousdigitalemissions** [comment]
@msbemba - Sri, thanks for verifying. My computer must have been having a bad day. Link is working perfectly. Thanks.
