### ISSUE TITLE
The Words 'a long time ago' are not helpful for knowing when to turn on Modern Auth.

### ISSUE THREAD

**Issue by GrantErickson** [MicrosoftDocs/microsoft-365-docs#4130]
We struggled with this for many hours. It would be good to know how many years ago this is. For example, new wording could be:
If your tenant was set up prior to January 1st, 2017, it is likely that you will need to turn on Modern Authentication in order to get features like Multi-Factor Authentication (MFA) to work in Windows clients like Outlook. To turn on Modern Authentication, follow these steps in the Microsoft 365 admin portal.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@GrantErickson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4155

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GrantErickson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
