### ISSUE TITLE
DLP policy override options

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/microsoft-365-docs#4131]
You state:
  Blocks access, sends a notification, and allows override

But you don't expand on the override option.  What happens if a user wants to override, what is the process?  One of the options under Override is allowing a business justification - what exactly does that mean? I haven't found an explanation (or example) in your documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-US/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide#options-for-configuring-policy-tips?WT.mc_id=365AdminCSH)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@SeaGT Thank you for your feedback. If the policy tips are configured to allow override, You will see the  Show Details option on the email > Override > enter a business justification or report a false positive > Override. The screenshots and details are added to the document - https://docs.microsoft.com/en-US/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide#policy-tips-in-outlook-on-the-web-and-outlook-2013-and-later

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SeaGT Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SeaGT** [comment]
Yogesh, why I agree the information is in the docs, you should have a link to that explanation of the exception in the document where you discuss policy creation and where the exception option is 1st mentioned.  Your author assumes that people reading the doc will see that there is no explanation of the exception, but will continue reading through the document in case there is one. 

I went to the doc looking for an explanation of the exception because I was creating a policy, and when it wasn’t there under the policy creation information and there wasn’t a link to more information, I left the page and didn’t use the exception.  I didn’t keep scrolling through the pages looking further down on the chance there was an explanation 4 or 5 pages down. 

Greg                                      

gregt@preceptwine.com   

Desk: 206.576.6012 | IT Support: 206.576.6013

**Comment by msbemba** [comment]
@SeaGT Thank you for your feedback. I have added the DLP conditions and Exceptions Document(link) to the more information section of this article. Hope this helps!

This change can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4195

Thanks
Sri
