### ISSUE TITLE
powershell example is incorrect

### ISSUE THREAD

**Issue by brkdncr** [MicrosoftDocs/microsoft-365-docs#4132]
the powershell command is looking for "Company Administrator" which doesn't exist.  It should be "Global Administrator"

Get-AzureADDirectoryRole | where { $_.DisplayName -eq "Company Administrator" } | Get-AzureADDirectoryRoleMember | Ft DisplayName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a37f7f-cdbf-b609-978c-fbe674d9a0e7
* Version Independent ID: 512a5a59-c466-20f2-7c4d-37303700d191
* Content: [Protect your Microsoft 365 global administrator accounts - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/protect-your-global-administrator-accounts?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/protect-your-global-administrator-accounts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/protect-your-global-administrator-accounts.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@brkdncr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4157

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @brkdncr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
