### ISSUE TITLE
Priority and Rules

### ISSUE THREAD

**Issue by PeeyushSri** [MicrosoftDocs/microsoft-365-docs#4133]
Article needs to provide a clarity on Priority and Rules

Can Priority 0 Have Rule1, Rule2, Rule 3 ...

If not then we need to be clear that 

Priority o Rule 1
Priority 1 Rule 2
----
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@PeeyushSri Thank you for your feedback. The statement says "When you create rules in a policy, each rule is assigned a priority in the order in which it's created — meaning, the rule created first has first priority, the rule created second has second priority, and so on."

It means the rule created first has priority 0 and second has priority 1

Priority o Rule 1
Priority 1 Rule 2

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PeeyushSri Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
