### ISSUE TITLE
Reporting a Microsoft Attack Simulator Phishing Campaign

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#4134]
What message will the user get when they report a simulated phishing campaign sent from the Microsoft Attack Simulator? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@HarrisburgUSysAdmin When reporting it through the report message add-in, they will not be receiving any message as such and the mail will be moved to the junk/deleted folder. The selected messages will be sent to Microsoft for analysis. To confirm that the messages have been submitted, open your Sent Items folder to view the submitted messages. 

As an admin, you can Gain insights through Attack simulation training - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-insights?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @HarrisburgUSysAdmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
