### ISSUE TITLE
User reports phishing campaign.

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#4135]
Does the user get a "congratulations" message if they report a phishing campaign email sent by IT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbdcbd5-7bd2-6b55-b72c-cbedfdea776c
* Version Independent ID: 1e6198f8-6ef1-6227-c9e8-f31944a5d1db
* Content: [Attack Simulator in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulator.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@HarrisburgUSysAdmin, I'm told that currently, the user who reports the test phishing message does not receive a "congratulations" message.

**Comment by msbemba** [comment]
@HarrisburgUSysAdmin Thank you for your feedback. I have tested and Microsoft does not send any congratulations mail after the user reports a phishing campaign. However, if they click on the phishing link you can have a custom landing page with your message. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @HarrisburgUSysAdmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
