### ISSUE TITLE
Change the organization name in org settings does not change the company name in Sold-To Address I have tested only change the letter case causes the problem.

### ISSUE THREAD

**Issue by ijrzhong** [MicrosoftDocs/microsoft-365-docs#4136]
Change the organization name in org settings does not change the company name, which is greyed indicating it cannot be changed, in Sold-To Address.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50536931-a7c8-620a-aae0-9c4baec51f74
* Version Independent ID: 27ce5737-2b34-cb55-07b0-c8450c0e5d62
* Content: [Change your billing addresses](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@ijrzhong Thank you for your feedback. I tested this and found that changing the Organization name in org settings in fact changes the company name in sold to address.

Could you please screenshots of what you see in the organization?

Thanks
Sri

**Comment by ijrzhong** [comment]
> @ijrzhong Thank you for your feedback. I tested this and found that changing the Organization name in org settings in fact changes the company name in sold to address.
> 
> Could you please screenshots of what you see in the organization?
> 
> Thanks
> Sri

I mean only changing letters cases of company name in org settings does not reflect the change in sold to address.

**Comment by msbemba** [comment]
@ijrzhong Thank you for the feedback. Change in Case does not change in the address in Sold to address as it is not case sensitive. If you would like to see it in a different case, the workaround would be to change it to something else and revert back to what you need.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ijrzhong Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
