### ISSUE TITLE
Limit available geos

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#4144]
Please add details on how to limit which geos may be used within an organization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd213abb-c697-3da5-4055-c1cb0e8bf93e
* Version Independent ID: cf0968f3-3b1a-7884-00d0-dd9654cb3bd2
* Content: [Administering Exchange Online mailboxes in a multi-geo environment - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/administering-exchange-online-multi-geo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/administering-exchange-online-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/administering-exchange-online-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. This is a part of the planning phase and you can configure any of the available locations to be satellite locations where you can host OneDrive and SharePoint sites, and Exchange mailboxes. As you plan for multi-geo, make a list of the locations that you want to add to your Microsoft 365 tenant. We recommend starting with one or two satellite locations and then gradually expanding to more geo-locations, if needed. More information can be found at - https://docs.microsoft.com/en-us/microsoft-365/enterprise/plan-for-multi-geo?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by danmyhre** [comment]
That is the part that needs documentation - adding them to the tenant. With ODfB/SPO, the admin can control this through the SPO admin center, but what about on the EXO side?

This article also isn't clear and it references "a company in v1", which no one will understand what that means.
https://docs.microsoft.com/en-us/powershell/module/msonline/set-msolcompanyalloweddatalocation?view=azureadps-1.0

**Comment by chrisda** [comment]
@danmyhre, I received and answer and I added the following statement to the topic:

> In Exchange Online multi-geo environments, you don't need to do any manual steps to add geos to your tenant. After you receive the Message Center post that says multi-geo is ready for Exchange Online, all available geos will be ready and configured for you to use.

Is this sufficient? If so, please close the issue at your convenience.

**Comment by danmyhre** [comment]
What about being able to set which ones are allowed? I have confirmed new geos for EXO can be added by simply adding that string into the PDL in AD for the user.

And does this even do anything anymore?
https://docs.microsoft.com/en-us/powershell/module/msonline/set-msolcompanyalloweddatalocation?view=azureadps-1.0

Thanks!

**Comment by msbemba** [comment]
@danmyhre  The set-msolcompanyalloweddatalocations adds additional goes for the service, This value must match one of the currently supported data locations by the service type. This is done on a tenant level, however, if you are looking for a user-level configuration then the PDL value set by the Admin in AD is honored for Onedrive and EXO.

Thanks
Sri

**Comment by danmyhre** [comment]
Hi - thanks, but this contradicts what @chrisda mentioned above. I think this highlights the importance of the docs to be updated to bring some clarity to this. I am also still curious on admins being specifically able to limit which geos can be used for Exchange. People who have delegated rights to manage users should not be able to deploy data to a new country simply by updating the PDL on a user object.

**Comment by scorp508** [comment]
There are no plans to limit geos in EXO at this time. The only reason this is possible with SPO/ODB is due to a different architecture which requires a per-geo URL to be specified while EXO uses a global single namespace for client access.

The only service which relies on CompanyAllowedDataLocation is SPO/ODB due to their architecture requirements, and their admin UI will automatically populate those fields if an admin goes through the motions to configure a geo.

**Comment by msbemba** [comment]
Thank you for the clarification @scorp508

**Comment by danmyhre** [comment]
Thanks @scorp508 - this is good to know. May want to add something to this section about that:

https://docs.microsoft.com/en-us/microsoft-365/enterprise/administering-exchange-online-multi-geo?view=o365-worldwide#view-the-available-geo-locations-that-are-configured-in-your-exchange-online-organization

**Comment by msbemba** [comment]
Thank you @danmyhre  for the feedback.

@yogkumgit  The document has been updated and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
