### ISSUE TITLE
Creating a new topic

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/microsoft-365-docs#4146]
It would help people following the guidance if a step is added before "1. In the Name this topic section". 

The step would be:

1. Create a new Topic Page

Select the option to create a new Topic Page from the ribbon on the Manage Topics page

![image](https://user-images.githubusercontent.com/13903544/107750553-1a1fd780-6d14-11eb-944f-8bc7c29660df.png)

2. In the Name this topic section ....

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d900e7e9-54ac-1641-bbd7-27ec24717067
* Version Independent ID: c1b2af7e-ec5d-bf4d-a47b-6528c31a3c89
* Content: [Create a new topic in Microsoft Viva Topics](https://docs.microsoft.com/en-gb/microsoft-365/knowledge/create-a-topic?source=docs)
* Content Source: [microsoft-365/knowledge/create-a-topic.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/knowledge/create-a-topic.md)
* Service: ****
* Product: **microsoft-365-enterprise**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@buildbod Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4184

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @buildbod Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
