### ISSUE TITLE
Assigning a License via Cloud Shell and bash

### ISSUE THREAD

**Issue by WeirdCircumstances** [MicrosoftDocs/microsoft-365-docs#4153]
Is there a way to accomplish the same management with the Azure Cloud shell and bash?
Create an user and after assigning a license (Office A1 for students) mangaging groups etc works flawlassly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073b885d-191e-8c00-fa59-ad83ba79ec10
* Version Independent ID: 4bd5799d-9baf-90b6-634d-398fbea6b66f
* Content: [Assign Microsoft 365 licenses to user accounts with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@WeirdCircumstances Thank you for your feedback. As of now, this feature of assigning licenses using ACS and/or bash is not available. While there is a way to connect to Exchange Online via ACS by using the cmd connect-exopssession and  manage EXO workloads like creating and managing groups etc, there is no way to assign the licenses yet. Once it is available, there will be a new document related to it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @WeirdCircumstances Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
