### ISSUE TITLE
O365 message trace REST URL's

### ISSUE THREAD

**Issue by aniketjambhale** [MicrosoftDocs/microsoft-365-docs#4156]
Hello,

I would like to know about REST URL's to fetch O365 message trace.

Old REST URL's are still in use ?

https://docs.microsoft.com/en-us/previous-versions/office/developer/o365-enterprise-developers/jj984328(v=office.15)

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58f8e2c-428a-4d8e-e8b7-a0342a0038db
* Version Independent ID: 6e7fab1b-1e24-9e36-176d-c3fb14f233a7
* Content: [Message trace in the Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/message-trace-scc.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/message-trace-scc.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@aniketjambhale Thank you for your feedback. Many of the REST-based and related cmdlets were deprecated in January 2018. However, for Message trace and details the old REST URI's are still in use as I have seen a lot of 3rd party applications/software collects message trace logs from the Message Trace REST API.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @aniketjambhale Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
