### ISSUE TITLE
Admin Role Required

### ISSUE THREAD

**Issue by sara-barbosa** [MicrosoftDocs/microsoft-365-docs#4159]
Could you please add a note, or clarify of which admin role is required to access / manage the Centralized Deployment Page (Integrated Apps)?

**Suggestion:** 
The Integrated Apps is a new feature that is supposed to be visible for Global administrator only, while for others the old experience still exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62dfa25-e420-38e4-ff47-05cca62d14ec
* Version Independent ID: 5ea03ce0-38b9-e005-a430-e98442e2ec83
* Content: [Deploy add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@sara-barbosa Thank you for your feedback. We have added information about this in the requirements document -  https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide

A Global admin can assign an add-in directly to a user, to multiple users via a group, or to everyone in the organization.

Hope this helps!

Thanks
Sri

**Comment by sara-barbosa** [comment]
@msbemba thanks for your message. 

From my point of view, that's not enough, this is still causing confusion, as the previous add-ins page was available to Global Admin and EXO Admin, now the centralized deployment - Integrated Apps Page is still only for Global Admins, we should make it clear for customer. That is the reason behind of my suggestion:

'The Integrated Apps is a new feature that is supposed to be visible for Global administrator only, while for others the old experience still exist.'

I can provide more details if you need too.

Thanks for your time.

**Comment by msbemba** [comment]
@sara-barbosa Thank you for the feedback. I have added a note to the document about the requirement. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4194

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sara-barbosa Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by sara-barbosa** [comment]
@yogkumgit @msbemba thanks to you. May I ask you to provide the link where that note was added, please? 
I was checking this link https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#deploy-an-office-add-in-using-the-admin-center - did not find the updated note.

**Comment by sara-barbosa** [comment]
@msbemba sorry to bother you again. Could you please point me to the updated noted? is in this page right? https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#deploy-an-office-add-in-using-the-admin-center

**Comment by msbemba** [comment]
@sara-barbosa  Looks like the Merged PR is not live yet. I'll check with the author and update you.

**Comment by msbemba** [comment]
@kwekuako I see the merge is complete, However, the data is not live on the document. Would you be able to check this?

Thanks
Sri

**Comment by sara-barbosa** [comment]
Hi @kwekuako, hope you are doing well. 
I still don't see the changes in this page: https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#deploy-an-office-add-in-using-the-admin-center

**Comment by msbemba** [comment]
@sara-barbosa Sorry about the delay. there are some issues with Github publishing at the moment. It should be merged and published once the fix is in. 

Thanks
Sri
