### ISSUE TITLE
Printing is not supported on Office on the Web for protected files

### ISSUE THREAD

**Issue by Bievens** [MicrosoftDocs/microsoft-365-docs#4161]
Appears printing is not supported on Office on the Web for protected files, is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Manage sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Investigating

**Comment by cabailey** [comment]
@Bievens   Now confirmed.  I hadn't realized printing wasn't supported for encrypted documents in Office for the web.  Now added to the list of limitations, here: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide#limitations

It seemed a strange limitation to me until I learned that in the background, to support a printable format, apps get converted to PDF.  Conversion to PDF is not allowed for encrypted documents, so printing is disabled.  To make printing possible, the conversion to PDF would need to change.  Not impossible but not a quick fix, and if this is important to you, you can up-vote an existing UserVoice request I found: https://office365.uservoice.com/forums/928576-microsoft-information-protection-mip/suggestions/42004780-office-online-print-option-greyed-out   You can also request a design change using your Microsoft Support contacts.
