### ISSUE TITLE
Forward in OWA?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/microsoft-365-docs#4162]
And where exactly does the forwarding feature in OWA fit into all of this?

![image](https://user-images.githubusercontent.com/7513795/108003838-3eb9cf00-6ff4-11eb-8314-f622a9fab330.png)

**Please document the procedure of finding out where all settings are which, in one way or another, affect mail forwarding.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding, Automatic forwarding, 5.7.520 Access Denied, disable external forwarding, Your administrator has disabled external forwarding, outbound anti-spam policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide&preserve-view=true#how-the-outbound-spam-filter-policy-settings-work-with-other-automatic-email-forwarding-controls)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Bartolomeus-649 Thank you for your feedback. The forwarding that a user sets up in Owa is more like inbox rules and Admin does not have an option to remove it from the admin center. You can use outbound spam filter policies to also control such automatic forwarding to external recipients.

Hope this answers your questions.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Bartolomeus-649 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
