### ISSUE TITLE
Display the organization branding on notification and warning pages

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/microsoft-365-docs#4163]
Our Safe Links policy now shows a new option: "Display the organization branding on notification and warning pages". I don't find this yet in the documentation. How and where can we configure the organization branding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-links?view=o365-worldwide#safe-links-settings-for-email-messages)
* Content Source: [microsoft-365/security/office-365-security/atp-safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@sebhe Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4203.

The option is available under Threat management > Policy > ATP Safe Links-->Edit Policy-->Settings

![image](https://user-images.githubusercontent.com/45987684/108634325-1d972980-749f-11eb-83c1-d8b1a67c14e4.png)

Thanks
Sri

**Comment by sebhe** [comment]
okay, I see. But my question was more related to the actual branding itself. Where do I configure the organization branding that is applied to the warning pages? Where do I configure the logo (?) that is displayed?

**Comment by msbemba** [comment]
@sebhe Thank you for your feedback. The next page (Notification) has the option to add custom notification text

![image](https://user-images.githubusercontent.com/45987684/108725607-91dbd680-754c-11eb-8829-5f76a92af0af.png)

The custom branding will appear above this warning as a banner and a small logo for your company. The branding is picked up from your organization branding setup on m365. - If you don't have one setup yet you can do so by following the instructions here -  https://docs.microsoft.com/en-gb/azure/active-directory/fundamentals/customize-branding

Hope this helps!


Thanks
Sri

**Comment by sebhe** [comment]
ah great, thanks! That was the information I was looking for.
maybe it does make sense to link this article in this article?

**Comment by msbemba** [comment]
@sebhe Thank you. I have added information about customize branding via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4203

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sebhe Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
