### ISSUE TITLE
Template file Date table needs updating

### ISSUE THREAD

**Issue by toomasmottus** [MicrosoftDocs/microsoft-365-docs#4165]
Analytics template file referred in this part of text 
(You can download the Power BI template file from the Microsoft download center from the Download center. After you have downloaded the Power BI template file follow these steps to get started), 
has date table only until 2020-12-31. Usage Details do not show values, as there is no period 2021-01.

Updating Date table throws up a number of USERELATIONSHIP errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebdb9f0-76a5-eebc-4cd7-95f5407ed029
* Version Independent ID: 05abf201-e31c-08c0-a7fc-8fd46202e8b0
* Content: [Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@toomasmottus I don't see an Analytics template on this page. Are you referring to the M365 usage analytics document?

Thanks
Sri

**Comment by toomasmottus** [comment]
Yes, the document referred to here: https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/usage-analytics.md

Usage Activity page is empty because it uses date table that ends at 2020-12-31. 

The version of that report that is available through Power BI App gallery works fine.

The problem is with the Microsoft Download Center version of template (PBIT) that is referred to on this page https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/usage-analytics?view=o365-worldwide

**Comment by msbemba** [comment]
@toomasmottus Thank you for your feedback. I'm currently working with the author and PG to fix this in the backend. We will update you shortly.

Thanks
Sri

**Comment by SKjerland** [comment]
@guochen2010 - Can you please look into this issue? It sounds like there's a problem with the Power BI template in the Download Center. I know you recently updated this file to address this related issue: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4056. I'm not sure what's going on. Thanks!

**Comment by guochen2010** [comment]
I've verified the link in the doc https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/customize-reports?view=o365-worldwide#use-the-microsoft-365-usage-analytics-template and the template file works fine for me. I can get data for Feb.

**Comment by toomasmottus** [comment]
Yes, Calendar table range has been updated to 2025.

[image: image.png]

We will encounter the same problem again in January 2026. :)

All fine for now!


Kontakt guochen2010 (<notifications@github.com>) kirjutas kuupäeval L, 6.
märts 2021 kell 04:42:

**Comment by yogkumgit** [comment]
@SKjerland Thank you very much for sharing this explanation. @toomasmottus We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
