### ISSUE TITLE
VITSL

### ISSUE THREAD

**Issue by rezwansarker** [MicrosoftDocs/microsoft-365-docs#4166]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 709fda6f-3a7d-92aa-e7ad-afb09cd47cda
* Version Independent ID: 991f7ce4-e3a8-e044-c3c5-82de3b8837d3
* Content: [Admin center overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-overview?view=o365-worldwide#who-has-admin-permissions-in-my-business)
* Content Source: [microsoft-365/admin/admin-overview/admin-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-overview.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@rezwansarker Thank you for your feedback. Could you please brief us on what changes are required or if you have any questions on this document?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @rezwansarker We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
