### ISSUE TITLE
RSS invalid

### ISSUE THREAD

**Issue by davecober** [MicrosoftDocs/microsoft-365-docs#4167]
When I put the RSS feed into my feed reader, it never updates. Inoreader shows a last update time of August 2020, other rss readers show it as invalid or expired. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac42403c-4226-bec2-986d-2e8a67e7c66d
* Version Independent ID: e8e0b323-ee46-f8e7-fe99-cbee91697213
* Content: [What's new in Microsoft 365 Defender - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/whats-new.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback. We've recently rebranded and that affected the URL.

Will update the feed to: https://docs.microsoft.com/api/search/rss?search=%22Lists+the+new+features+and+functionality+in+Microsoft+365+defender%22&locale=en-us&facet=
