### ISSUE TITLE
Dead link:  Use Centralized Deployment PowerShell

### ISSUE THREAD

**Issue by LaumanK** [MicrosoftDocs/microsoft-365-docs#4168]
**Dead link:**  _Use Centralized Deployment PowerShell cmdlets to manage add-ins_ @ https://docs.microsoft.com/en-us/office365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins

**Replace with:**  https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61e46dd-c1ff-dfec-5e0e-9f2e7251a5c1
* Version Independent ID: 49f69fa9-33e8-373f-a7f9-26b828510fda
* Content: [Manage add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-addins-in-the-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-addins-in-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@LaumanK Thank you for your feedback. We have fixed this via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4212

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The Deadlink is now fixed and the issue can be closed.
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LaumanK Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by LaumanK** [comment]
No problem at all.  Glad to help.  No concerns about closing.

Thanks,
Kristin Lauman
Email & Calendar Architect and Technical Lead
c  630-849-3985

**Comment by msbemba** [comment]
@yogkumgit The issue can be closed.
