### ISSUE TITLE
Note about permission requirement needs to be more specific

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/microsoft-365-docs#4171]
The article states that you need to be a member of the Security Administrator (SA) role in order to access the anti-spam settings.  It does not specify that you must use the Security Administrator role within Exchange.  I have had a couple customers try to use the SA role listed under the permissions of protection.office.com.  This role does not give you access to the underlying Exchange PowerShell cmdlets, nor does it give you access to the functionality through the Security and Compliance Center GUI.

You either need to be part of the SA role in all workloads (as I believe you can define through Azure) or in Exchange.
If you are familiar with RBAC you can also use cmdlets like Get-ManagementRoleEntry "*\new-hosted*" to research the specific Exchange roles required to access anti-spam functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed2861d-860e-5d27-9259-fb9db2187f4b
* Version Independent ID: 09ef5622-3a7e-30f9-00f9-4c5578f8e1ca
* Content: [Configure spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cablechewer, fixed in this topic and in other affected topics. Note that it will take a while for the updates to publish.

Thanks for the feedback.

Closing
