### ISSUE TITLE
Password expiry notification in the lower right corner

### ISSUE THREAD

**Issue by rajatbhasin** [MicrosoftDocs/microsoft-365-docs#4176]
The article talks about a user getting a password expiry notification at the lower right corner of the screen.
**Step 7 here** - https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?redirectSourcePath=%252fen-us%252farticle%252fset-the-password-expiration-policy-for-your-organization-0f54736f-eb22-414c-8273-498a0918678f&view=o365-worldwide#set-password-expiration-policy

However, this behavior does not exist. 
Wasn't the support for notifications through M365 Suite Header removed in 2019 ? 
Is the article referring to the same behavior or is this a new behavior ? 
Can you clarify the old behavior and the new behavior in the article ?
If this is incorrect information, please update it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?redirectSourcePath=%252fen-us%252farticle%252fset-the-password-expiration-policy-for-your-organization-0f54736f-eb22-414c-8273-498a0918678f&view=o365-worldwide#set-password-expiration-policy)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@rajatbhasin Thank you for your feedback. We are currently checking with PG/Author to confirm the same and will update the document accordingly.

Thanks
Sri

**Comment by kwekuako** [comment]
Hi, I removed the part about the password expiry in the topic. I couldn't confirm with PM that this is still supported so I removed until we can confirm that this is correct. Thanks.

**Comment by yogkumgit** [comment]
@kwekuako Thank you very much for sharing this explanation. @rajatbhasin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
