### ISSUE TITLE
Disabling TLS 1.0 and 1.1 for Microsoft 365

### ISSUE THREAD

**Issue by Linas08** [MicrosoftDocs/microsoft-365-docs#4177]
does not hint at how to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec089a7-8f7b-d4d9-a763-e8abd73fb2c9
* Version Independent ID: 41ba8999-f0ea-5847-afad-8620dd83492a
* Content: [Disabling TLS 1.0 and 1.1 for Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @WorkShay
* Microsoft Alias: **fasqiu**

**Comment by msbemba** [comment]
@Linas08 Thank you for your feedback. The below document provides guidance to help make sure that your clients are using TLS 1.2 or a later version and to disable TLS 1.0 and 1.1. -https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide#references

I have also added this information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4221


Hope this helps!

Thanks
Sri

**Comment by Linas08** [comment]
Sorry no help I don’t know what a TLS dependency could be?

**Comment by msbemba** [comment]
@Linas08 The document talks about how to prepare for the change depending on the applications - https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide#references


If you are using o365 as standalone and do not have any third-party applications or an SMTP relay. you do not have to worry. Meanwhile, you could also contact the support team using the need help section on the admin center. They can help you verify your setup and help you with it.

Thanks
Sri

**Comment by WorkShay** [comment]
Hi Yogesh,

@***@***.***> owns the comms for TLS. I no longer work on this project and my new PM counterpart is @***@***.***>.

Best,
Shayna

Pronouns: they/them<https://www.mypronouns.org/they-them#:~:text=A%20person%20who%20goes%20by%20%E2%80%9C%20they%20%E2%80%9D,theirs.%20I%20like%20both%20them%20and%20their%20ideas.%E2%80%9D> || she/her<https://www.mypronouns.org/she-her#:~:text=A%20person%20who%20goes%20by%20%E2%80%9C%20she%20%E2%80%9D,hers.%20I%20like%20both%20her%20and%20her%20ideas.%E2%80%9D>
Name pronounciation: [SHā-nah]

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Linas08 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ispoole** [comment]
1.	Is there a specific date at which it will no longer be possible to connect to Microsoft 365’s SMTP service with TLS 1.0/1.1? Documentation we’ve found online indicates that deprecation began on September 2020, but it is still ‘working’ and we have found no references to an end-of-service date past which connections will be refused.
2.	If the rollout is progressive, is there a way to tag this particular tenant so that it gets executed later rather than sooner?

**Comment by WorkShay** [comment]
@Fasheng ***@***.***>

Best,
Shayna

Pronouns: they/them<https://www.mypronouns.org/they-them#:~:text=A%20person%20who%20goes%20by%20%E2%80%9C%20they%20%E2%80%9D,theirs.%20I%20like%20both%20them%20and%20their%20ideas.%E2%80%9D> || she/her<https://www.mypronouns.org/she-her#:~:text=A%20person%20who%20goes%20by%20%E2%80%9C%20she%20%E2%80%9D,hers.%20I%20like%20both%20her%20and%20her%20ideas.%E2%80%9D>
Name pronunciation: [SHā-nah]
