### ISSUE TITLE
Adding a role group as a member on an Advanced eDiscovery case.

### ISSUE THREAD

**Issue by rhampton1** [MicrosoftDocs/microsoft-365-docs#4178]
The following error occurs when adding a role group as a member to an Advanced eDiscovery case. It appears to say that the role group eDiscoveryManagers must be a member of a role group with the Case Management or Review roles.

![image](https://user-images.githubusercontent.com/64498847/108221665-0acece80-7106-11eb-882e-18db7f0ca76b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 492b920b-f938-146c-1435-7bc7ba5c74f1
* Version Independent ID: b5f70139-4b8d-5079-5370-ad861dcc42ec
* Content: [Add or remove members from a case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 492b920b-f938-146c-1435-7bc7ba5c74f1
* Version Independent ID: b5f70139-4b8d-5079-5370-ad861dcc42ec
* Content: [Add or remove members from a case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rhampton1 Thanks for question. I assume that you are trying to add the role group to the AeD case. If so, you have to be a member of that same role group that you are trying to add to the case. You also need to be assigned the Case Management role to add members to an AeD case, but you have to be a member of the role group you are trying to add to the case. There is more info about using role groups in this topic: https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries

If your scenario is different, then I would suggest you contact Microsoft Support.
