### ISSUE TITLE
Safe Documents feature can be enabled without having licenses

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#4179]
The Safe Documents feature can be enabled even though there are no ‘Microsoft 365 E5’ or ‘Microsoft 365 E5 Security’ licenses available in the tenant. When enabling this feature without having the licenses, the feature will not work.
It is (softly spoken) not a very good idea to offer this feature while licenses are not available in the tenant.
Customers are enabling this feature and are frustrated because it doesn't work while it is no supposed to work but this is generating Support cases!

The option to enable the feature should be removed or greyed out until there are proper licenses available in the tenant.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, I suggest that you open a support case about this. We already call out the licensing requirements in the topic, which is about all we can do from a documentation perspective

**Comment by JeroenDronkers** [comment]
Hello Chris,

Unfortunately I cannot raise support cases as Microsoft Support engineer.
We receive these cases from our customers…
I’ll see what I can do.

Thanks,


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

**Comment by chrisda** [comment]
@JeroenDronkers, the other option is to suggest this as a feature request at <https://office365.uservoice.com>. From a documentation perspective, there's nothing more we can do.

**Comment by JeroenDronkers** [comment]
Hello Chris,


Thanks but Uservoice is gone 😊



Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
***@***.******@***.***>

[abc]
﻿
Team Manager | Frances Early ***@***.******@***.***>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @JeroenDronkers this is the best help we can provide here . We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
