### ISSUE TITLE
Link to Online Services Terms does not work

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#418]
Please chage it to http://aka.ms/ost

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac42bb5-3204-4839-6fcb-5a5052a0d9cb
* Version Independent ID: 57cde474-a2e7-fc4b-339d-3e28377ae035
* Content: [Office 365 accountability readiness checklist for the GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-arc-office365)
* Content Source: [microsoft-365/compliance/gdpr-arc-Office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-arc-Office365.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@Larryngolog - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Larryngolog - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
