### ISSUE TITLE
Request for more details

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4186]
I don't see any prerequisite information about the required location of mailboxes, i.e, will these features work for people who have their mailbox in Exchange Server? Please provide some information about hybrid exchange environments.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e396c36f-1f7f-a92a-f425-a08b3aaf44e3
* Version Independent ID: 2f15dfb7-1695-9cf7-7560-f9a51eadd745
* Content: [Microsoft 365 Defender prerequisites - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/prerequisites?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/prerequisites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/prerequisites.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. I have added information about mailbox requirements via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4264. Once the author approves the PR will be merged.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The changes have been made to the document.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
