### ISSUE TITLE
Stream / Live Events IPs missing

### ISSUE THREAD

**Issue by regnertomas** [MicrosoftDocs/microsoft-365-docs#4188]
This list does not include all IP addresses listed on this site:
https://docs.microsoft.com/en-us/stream/network-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@regnertomas Thank you for your feedback. I'm currently working on this with the author and will update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please update this and help us in resolving this issue. Thanks.

**Comment by LauraWi** [comment]
I am following up to determine whether Stream requires onboarding to the tool that generates this article.

**Comment by LauraWi** [comment]
After conferring with the engineering SMEs for Office 365 endpoints, I have determined that it would not be appropriate to add these Stream endpoints to the O365 article. Guidance in Stream-specific article may need to be updated. This has been flagged to that team.
