### ISSUE TITLE
Unclear data formatting

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#4191]
Issues:

- In the "modify" section, some of the descriptive text is erroneously in the code block
- The instructions are incomplete for saving the text file
- Windows 10's Notepad does not offer "Unicode" as a save as option. Choices are: ANSI, UTF-16 LE, UTF-16 BE, UTF-8, UTF-8 with BOM
- Article states we should save as UTF-16, but does not specify LE or BE, which is a required choice in notepad.
- Conflicting article uses UTF8 (https://docs.microsoft.com/en-us/powershell/module/exchange/set-dlpkeyworddictionary?view=exchange-ps)
- Formatting is wrong on the "The output of the command looks like this:" and other paragraphs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 196b87de-20ff-37ea-79b8-beb37a1361e0
* Version Independent ID: d3aa9f91-0cec-b9df-6fc7-415242393e3f
* Content: [Create a keyword dictionary - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-keyword-dictionary?view=o365-worldwide#modifying-an-existing-keyword-dictionary)
* Content Source: [microsoft-365/compliance/create-a-keyword-dictionary.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-keyword-dictionary.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox  Please add your comment and help us in resolving this issue. Thanks.

**Comment by chrfox** [comment]
HI @Mike-Crowley 

The formatting issues have been fixed and the others are being researched and will be corrected as appropriate.
