### ISSUE TITLE
Recommend allowing in proxies

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/microsoft-365-docs#4192]
Worked with a customer where Palo Alto actually blocked our mock phishing sites as phishing so can we add a blurb to the Note section where we recommend allowing in browsers to also allow in proxies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c87455-77af-093a-6fb6-286049aad15a
* Version Independent ID: b2690e98-781d-4a27-a9bc-bd621964feb0
* Content: [Get started using Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-get-started.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jmmowrer, new content is coming that talks about this. Feel free to close this issue when you see it.

**Comment by yogkumgit** [comment]
@jmmowrer Hope this information is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
