### ISSUE TITLE
Missing info regarding M365 Business Basic

### ISSUE THREAD

**Issue by Quartermaster-007** [MicrosoftDocs/microsoft-365-docs#4193]
It looks like info is missing to clarify that Business Basic does not get the functionality of Office Scripts. The wording suggests that any M365 or O365 Business or Enterprise subscription would work. However, after testing this myself, I could only access the feature with a Business Standard license and not with a Business Basic license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a5bcf4d-f5ce-d4d7-5ac8-c26d34a0c4b4
* Version Independent ID: 14b25292-216b-d4be-32e9-616dddd2aad4
* Content: [Manage Office Scripts settings - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-office-scripts-settings?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-office-scripts-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-office-scripts-settings.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@Quartermaster-007 Thank you for your feedback. We have added the information to "Before you begin" section of the document

Ensure users in your organization have a valid license for a Microsoft 365 or Office 365 commercial or EDU plan that includes access to Office desktop apps, such as one of the following plans:

Microsoft 365 Business Standard
Microsoft 365 Apps for business
Microsoft 365 Apps for enterprise
Office 365 E3
Office 365 E5
Office 365 A3
Office 365 A5

Hope this helps!

@yogkumgit There are no changes required in the document and can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Quartermaster-007 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
