### ISSUE TITLE
Add the new "Integrate a third-party cloud app with ‎Azure AD‎" Wizard to documentation

### ISSUE THREAD

**Issue by nikkelly** [MicrosoftDocs/microsoft-365-docs#4197]
[Enter feedback here]
**Name:** Integrate a third-party cloud app with ‎Azure AD
**Description:** Improve the user experience and provide an additional layer of security by integrating your third-party app with ‎Azure Active Directory‎ (‎Azure AD‎). With this end-to-end experience you can do most of the configuration directly from this wizard. Where appropriate, we'll redirect you to the corresponding configuration page.

Wizard link: [https://admin.microsoft.com/Adminportal/Home?#/azureadappintegration](https://admin.microsoft.com/Adminportal/Home?#/azureadappintegration)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e0e0337-ad80-74c2-07df-1164a0641feb
* Version Independent ID: 7f19f87a-79cf-33b6-c64f-4449b1add0d9
* Content: [Setup guides for Microsoft 365 and Office 365 services - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/setup-guides-for-microsoft-365?view=o365-worldwide#guides-for-authentication-and-access)
* Content Source: [microsoft-365/enterprise/setup-guides-for-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/setup-guides-for-microsoft-365.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@nikkelly Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4220

Thanks
Sri
