### ISSUE TITLE
Please add docs for 'Device Discovery'

### ISSUE THREAD

**Issue by panovattack** [MicrosoftDocs/microsoft-365-docs#4201]
Device Discovery is now configurable via settings, but there is no supporting docs.

**Comment by msbemba** [comment]
@panovattack  Thank you for your feedback. Are you referring to the device discovery in windows 10 or endpoint manager?

Thanks
Sri

**Comment by panovattack** [comment]
In new M365 Security Center --> Setttings --> Device Discovery

**Comment by msbemba** [comment]
@panovattack  Thank you for the details. I shall verify the list and document and update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@panovattack Thank you for the information. I do not see device discovery yet. Are you referring to the detection test available under device management(in endpoints) ?
![Uploading image.png…]()

Thanks
Sri

**Comment by panovattack** [comment]
Image Attached. 
![DeviceDiscovery](https://user-images.githubusercontent.com/17179159/109406855-f24e8780-7941-11eb-8b02-b03cbeb75c17.PNG)

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @panovattack Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
