### ISSUE TITLE
Add guests to a Microsoft 365 dynamic group

### ISSUE THREAD

**Issue by Ben-m-s** [MicrosoftDocs/microsoft-365-docs#4202]
Please consider adding a note on the "Add guests to a Microsoft 365 group from the admin center" section indicating that the groups which membership is managed through rules (dynamic groups) on AAD, the option "View all and manage members" is not available.

AAD membership rules support Guest users, which is another way to add external members to groups. Especially important if you create dynamic groups where you do not want external users to get accidental membership, as you need to explicitly set rules to exclude them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Ben-m-s Thank you for your feedback. We have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4219

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Ben-m-s Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
