### ISSUE TITLE
how to assign Office365 licenses to all users on a machine

### ISSUE THREAD

**Issue by LukeChung** [MicrosoftDocs/microsoft-365-docs#4205]
We have a machine used for remote desktop that any user can connect to. They all have their corporate Office365 account, but when they first log into the remote desktop server, Office isn't activated for them. Is there a way to do that so everyone doesn't have to manually do it? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42a261b-afb1-e8d4-e61d-c9d30cb71a00
* Version Independent ID: 3649a463-b7d6-104a-608f-cfcf16b66cb5
* Content: [Assign licenses to users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/assign-licenses-to-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/assign-licenses-to-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@LukeChung Thank you for your feedback. What licenses are the users assigned? As long as they have M365 apps for the enterprise they will have the Shared computer activation. MOre details can be found here - https://docs.microsoft.com/en-us/deployoffice/overview-shared-computer-activation#how-to-enable-shared-computer-activation-for-microsoft-365-apps

**Comment by LukeChung** [comment]
We have Office 365 E3, but when a user with that license logs into the Remote Desktop machine and launches an Office program for the first time, Office isn’t activated.

I’m wondering if we don’t have Office 365 accounts and our network Active Directory integrated together. Is there something that needs to be done to connect the two?

Not everyone we assign Office accounts should be able to log into our network, but there are many who log into our network and also have an Office 365 E3 license.

**Comment by msbemba** [comment]
@LukeChung The installation needs to be done differently here when shared activation is involved. More information can be found here - https://docs.microsoft.com/en-us/deployoffice/overview-shared-computer-activation

I'd recommend you create a support ticket via the need help section on the admin center and work with a support engineer to get this installed the correct way.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @LukeChung Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by LukeChung** [comment]
Thanks. We installed Office 365 using the instructions provided in that other page but it doesn’t handle the licensing for all users.

Each user still needs to manually sign into their Office 365 account when they remote to the machine the first time. This wasn’t the case with Office 2010 where we could install a Remote Desktop Office license.

So the problem remains.

Luke

**Comment by msbemba** [comment]
@LukeChung Thank you for the response. I'd still recommend you contact Microsoft on this as this is not the expected behavior and if this is a bug, they can get it escalated internally. Let us know how it goes.

Thanks
Sri

**Comment by LukeChung** [comment]
Yea, we’ve done that. Looks like every user has to manually enter their Office 365 login the first time they remote to a VM that has Office 365 installed for it in shared mode. With hundreds of users and multiple remote desktop hosts, that’s too much of a mess.

The workaround that should be mentioned is that this isn’t an issue with Office 2010 using a remote desktop Office license. That’s what we’ll continue to use until this is resolved for 365.

**Comment by msbemba** [comment]
@LukeChung I agree that you have a sign in for the first time, but I'm surprised that the support did not give you other options about Azure Active Directory Seamless Single Sign-On or ADFS for that matter. - You can check the below document- 

https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso

Let me know if this helps

Thanks
Sri
