### ISSUE TITLE
Clarification on Message Submission Format

### ISSUE THREAD

**Issue by glr0221** [MicrosoftDocs/microsoft-365-docs#4206]
Hello Microsoft,

Good day to all of you. 

This inquiry is about this document : https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide

I would like to clarify some details regarding the submission format you described in the document. You have the following writeup : 

```
- The message is being reported as phishing.
- The Network Message ID is 49871234-6dc6-43e8-abcd-08d797f20abe.
- The Sender IP is 167.220.232.101.
- The From address is test@contoso.com.
- The message's subject line is "test phishing submission"
3|49871234-6dc6-43e8-abcd-08d797f20abe|167.220.232.101|test@contoso.com|(test phishing submission)
```

1. **Network Message ID** - there are two message-ID-related email-headers and these are : (1) X-MS-Exchange-Organization-Network-Message-Id and (2) X-MS-Exchange-CrossTenant-Network-Message-Id. Both have same values, which is best to use?
2. **Sender IP** - Is the value of 'X-Originating-IP' email-header best to use for this? Or is the IP in the topmost 'Received' header best to use?
3. **Email Address** - Do you also support "FirstName LastName &lt;email_address@domain.com&gt;" format?
4. **Subject** - How do we escape '|' (vertical bar/pipe) and other special characters in the email subject?
5. **Body of the Email** - What happens the if email body is non-empty?
6. **Attachment** - As for attachments, do you support MSG file format only? Or are EML-files supported too? Can we use customized/use-preferred names for the attached report emails too?

Thank you very much for taking time to read my inquiries. And thank you in advance for your answers.

More power to all of you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User submissions policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@glr0221 Thank you for the feedback.

Network Message ID - Use the  X-MS-Exchange-Organization-Network-Message-Id

Sender IP - It is 'X-Originating-IP' email-header 

Email Address - Supports only  the from address (You cannot provide First name and last name) instead it can be firstname.lastname@domain.com if that the email that the message is sent from.

Subject - The email subject is always under ( ) So the pipes or characters do not matter.
If your question is about the subject of the message submission format - It still needs to be SafetyAPIAction|NetworkMessageId|SenderIp|FromAddress|(Message Subject)

Body of the Email - Ideally it doesn't matter (unless you are reporting false positive to not_junk@office365.microsoft.com
Attachment - Use either .msg (default Outlook format) or .eml (default Outlook on the Web format) formats for the attached messages.

Hope this helps!

Thanks
Sri

**Comment by glr0221** [comment]
Thank you very much @msbemba sri. You answers are well-appreciated. 

To clarify: 

1. What if the subject is something like this :  "We have ) and ( signs in the subject." 
There is no need to escape the sample subject string stated above right? Even if I have parenthesis in the subject.

2. The EML part is awesome to know. Now I have some peace of mind as to the integrity and quality of data I am sending.

As a follow up question, as you know, the MSG file formats has many properties/meta-data/attributes in its structure.
Would you know or any of the developers know what attributes/properties are mandatory for the MSG file format? 
Currently we are using our own MSG writer, and when submitting a report we are sending out an MSG with "significant" property values only. These property-values include PR_SENDER_EMAIL_ADDRESS_W, PR_SENDER_NAME_W, PR_MESSAGE_CLASS_W and others. 

Is there a list of MSG-properties that need to be supported to ensure that the reported msg file has a complete set of data required for reports to be processed/generated correctly? 

3. Sender IP - It is 'X-Originating-IP' email-header
There are some cases where this particular header is absent. (i.e. gmail-sent emails) So i am currently looking into **`"Authentication-Results: spf=none (sender IP is 209.85.208.46)"`** as an augmentation/secondary solution to X-Originating-IP. 


I hope the three items I raised are clear and made sense. 
Thank you always for your support, you guys rock!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @glr0221 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
