### ISSUE TITLE
Purpose of page

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4208]
While I like the idea of release notes, I don't see this being provided for other services very often. The what's new pages with dates showing when items are released seems to work very well and I would recommend using that approach for this type of information. In fact, it would be great if all of the Compliance Solutions had their own What's New page to us keep up with the changes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c695499-0180-91aa-72bf-b61968f000c0
* Version Independent ID: 24459c69-85a3-450d-2b5a-ca62504b5d1a
* Content: [Data classification release notes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-pub-preview-relnotes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-pub-preview-relnotes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-pub-preview-relnotes.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @DeanGross 
Thanks for bringing this up.

Chris
