### ISSUE TITLE
When I run the  DeviceTvmSecureConfigurationAssessment it only returns WIN 10 OS and none of my Server 2016/2019. Can you update?

### ISSUE THREAD

**Issue by johnB007** [MicrosoftDocs/microsoft-365-docs#4211]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4fe829d-1049-f4fc-5238-792d86f33126
* Version Independent ID: c52c503e-3fd2-9324-8fd2-ad05b91b1930
* Content: [DeviceTvmSecureConfigurationAssessment table in the advanced hunting schema - Microsoft 365 security](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/advanced-hunting-devicetvmsecureconfigurationassessment-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/mtp/advanced-hunting-devicetvmsecureconfigurationassessment-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/advanced-hunting-devicetvmsecureconfigurationassessment-table.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by yogkumgit** [comment]
@lomayor  Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@lomayor Gentle reminder, Need your help here, please.

**Comment by lomayor** [comment]
@schmurky @Dansimp, since this table is simply pulling info from TVM, I believe this needs to be addressed in TVM docs. Can you please help check if we have sufficient info in TVM docs indicating whether or not we have Windows Server coverage for secure configurations?

**Comment by schmurky** [comment]
I am checking now.

**Comment by schmurky** [comment]
I checked TVM and according to [this](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-supported-os?view=o365-worldwide ) you should be able to see server 2016 and 2019. PM advised opening a support case so it can be investigated.

**Comment by yogkumgit** [comment]
@johnB007 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
