### ISSUE TITLE
CDN is available in GCC/GCCH

### ISSUE THREAD

**Issue by robgarrett** [MicrosoftDocs/microsoft-365-docs#4214]
[Enter feedback here]
Tested both getting and setting public/private CDN in GCC and GCC-H tenants and it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 584f6602-a1c2-c853-8da5-cb3636a6942d
* Version Independent ID: b94cfe21-d86c-d36a-8791-c5e4d7f8dbd7
* Content: [Office 365 Content Delivery Network (CDN) Quickstart - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/office-365-cdn-quickstart?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/office-365-cdn-quickstart.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/office-365-cdn-quickstart.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@robgarrett Thank you for your feedback, Rob. I'm working with the author to verify and will update the document accordingly.

Thanks
Sri

**Comment by LauraWi** [comment]
Hi @robgarrett Can you follow up via internal channels so we can have confirmation via engineering owners? Tested & works is not always the same as supported.
