### ISSUE TITLE
Office 365 Global admins unable to create groups in Teams and Outlook

### ISSUE THREAD

**Issue by CarolWangMS** [MicrosoftDocs/microsoft-365-docs#4218]
Hi Experts,

I have recently did a test about this document: 
https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide

As I can see from my test, the Office 365 Global admins who was not in the group can create groups via Planner,SPO and admin center. However, they will have trouble when trying to create groups via Teams or Outlook. 

Could you please check this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@CarolWangMS Thank you for your feedback. I test this as well and you are right The steps in this article won't prevent members of certain roles from creating Groups. Office 365 Global admins can create Groups via any means, such as the Microsoft 365 admin center, Planner, Teams, Exchange, and SharePoint Online. The same has been mentioned in the document as well for clarity.

Hope this helps!

Thanks
Sri

**Comment by CarolWangMS** [comment]
Hi @msbemba Thank you for your reply. My friend and I has tested, but we both have the same issue.
May I confirm again that After you set up the configuration as the document, an O365 global admin **who is not in the security group** can still create groups via Teams and OWA? 
We have tested that users and admins in the group works as expected. but global admin who is not in the group looks different.

**Comment by msbemba** [comment]
@CarolWangMS Thank you. I May have misunderstood the initial request. I'm not able to create via teams, web app and outlook. But can do it through the  Planner, SPO, and Admin center. I will update the document accordingly.

Thanks
Sri

**Comment by CarolWangMS** [comment]
Hi @msbemba  Thank you so much for verifying this. Now we share the same results.

**Comment by msbemba** [comment]
@CarolWangMS We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4533

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CarolWangMS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
