### ISSUE TITLE
Microsoft 365 Groups (missing information)

### ISSUE THREAD

**Issue by Pher0ah** [MicrosoftDocs/microsoft-365-docs#4223]
[Enter feedback here]
Please note that M365 Groups also create a Stream and Planner for each group; this doesn't seem to be mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Pher0ah** [comment]
Hi Sri, I am afraid the practical test shows differently. Also the MS700
coursework says it does, so please test and let me know.

kind regards,

Hany

**Comment by msbemba** [comment]
@Pher0ah Thank you for the feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4398

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Pher0ah Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
