### ISSUE TITLE
It should say "user account is deleted" not "mailbox is deleted"

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#4224]
Hi!

Looks like there is a mistake in 2 places in document - "mailbox is deleted" should be changed to "User account is deleted":
- in paragraph "Inactive mailboxes and Microsoft 365 retention policies" it says "It has to be configured to retain content or retain and then delete content. If a retention policy is configured to only delete content, a mailbox that the policy is applied to won't become inactive when the **mailbox is deleted**." But since we are talking about inactive mailbox it should say "User account is deleted". As a consequence the mailbox will be deleted as well since inactive mailbox will not be made, but this is a second step of the process.
- in paragraph "Creating an inactive mailbox" it says "After the **mailbox is deleted**, any Exchange Online license associated with it will be available to assign to a new user." but it's not the mailbox that is deleted but the user account. Mailbox stays as it became inactive and is guarded by the hold.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Overview of inactive mailboxes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Larryngolog Thanks for the feedback. Good points. I will update the documentation as per your suggestions.
