### ISSUE TITLE
Update versions information for Outlook client

### ISSUE THREAD

**Issue by hbteibet** [MicrosoftDocs/microsoft-365-docs#4230]
The information on the docs site and in the M365 admin center, "Deploy a new add-in" > "Choose from the Store" pages contradicts. At the link below, it shows that the "Report Phishing" button is only compatible with Outlook 2016 for Mac, but the Store shows "Outlook 2016 or later on Mac". 

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-phish-add-in?view=o365-worldwide#what-do-you-need-to-know-before-you-begin

![image](https://user-images.githubusercontent.com/14109246/108901526-9782fc00-75e0-11eb-99ee-1d21c609859a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 214e9296-0909-0946-57b0-dca5f22ee854
* Version Independent ID: 689f3c32-eeb9-9c60-5d7c-78ebd6dcb165
* Content: [Enable the Report Phish add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-phish-add-in?view=o365-worldwide#get-and-enable-the-report-phishing-add-in-for-your-organization)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-phish-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-phish-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@hbteibet Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4297

Thanks
Sri

**Comment by chrisda** [comment]
For posterity, [this topic](https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac) describes the Office (and presumably Outlook) for Mac version history.
