### ISSUE TITLE
E3 vs E5 - Programmatically applying a retention label

### ISSUE THREAD

**Issue by Encodian** [MicrosoftDocs/microsoft-365-docs#4231]
Hi,

Whilst the documentation clearly outlines the available automation options (Specific conditions, trainable classifiers and events) for applying retention labels, and the M365 Compliance Licensing Comparison guide details which of these options are available for the Microsoft 365 E3 and Microsoft 365 E5 licence types.

However, we can't find documentation or guidance confirming whether utilising an API (REST API or CSOM for example) to apply a retention label programmatically is covered by a Microsoft 365 E3 licence or whether a Microsoft 365 E5 licence would be required. 

This is covered in the M365 Compliance Licensing Comparison guide for sensitivity labels (Enable 3rd party integration into Microsoft Information Protection (MIP) using MIP SDK), but it's not clear for retention labels. 

Can this clarity be provided, please?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a4716f6-31db-306c-2804-56591e3af7e6
* Version Independent ID: 8dfc13ff-3b6a-ba25-2911-db7a3dcd2e8a
* Content: [Automatically apply a retention label to retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/apply-retention-labels-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-retention-labels-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-retention-labels-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi Encodian  We link to "Microsoft 365 licensing guidance for security & compliance" (https://aka.ms/ComplianceSD) at the top of this page because licensing is owned by another team, so we can't give you authoritative answers to these types of questions.  That would be the right page to submit your question so it's seen by people who can answer it.  Alternatively, you can ask your Microsoft account manager.
