### ISSUE TITLE
Clarification on the  Set-OrganizationConfig -AutoExpandingArchive command

### ISSUE THREAD

**Issue by djxspike** [MicrosoftDocs/microsoft-365-docs#4232]
"If you run the `Set-OrganizationConfig -AutoExpandingArchive` command to enable auto-expanding archiving for your organization, you don't have to run the `Enable-Mailbox -AutoExpandingArchive` on individual mailboxes. Running the `Set-OrganizationConfig` cmdlet to enable auto-expanding archiving for your organization doesn't change the AutoExpandingArchiveEnabled property on user mailboxes to True."

The way this is worded isn't very clear... it sounds like  `Set-OrganizationConfig -AutoExpandingArchive` doesn't do anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a7c1600-c310-fb7f-7976-2025ee9256f3
* Version Independent ID: 9241081b-eabb-78a8-af86-2c0f27e7e671
* Content: [Enable unlimited archiving - Admin Help - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-unlimited-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@djxspike This is trying to say that if you run Set-OrganizationConfig -AutoExpandingArchive $True, then doing that doesn't change the value of the AutoExpandingArchive property on a mailbox to "True". So, if Get-OrganizationConfig | FL AutoExpadingArchive returns a value of True, auto expanding archiving is enabled for all mailboxes in the org, regardless of what the value for the AutoExpandingArchive property is for a mailbox. Please let me know how/if you would clarify further.
