### ISSUE TITLE
Missing important information about interaction of the Add-in with Shared Mailboxes

### ISSUE THREAD

**Issue by Breid125** [MicrosoftDocs/microsoft-365-docs#4235]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide#what-do-you-need-to-know-before-you-begin

The Report Phishing and Report Message add-in function is not available when accessing a Shared Mailbox within Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by Breid125** [comment]
Frankly, it should be. Shared Mailboxes are generally the delivery point of publicly posted email addresses and tend to be subject 
 to increased malicious mail flow....but until such time as THAT issue is resolved, the documentation should be clear about this limitation.

**Comment by msbemba** [comment]
@Breid125 Thank you for your feedback. If the shared mailbox is auto mapped, you may not be able to view the add-in on outlook.
A multitude of features are only available when the mailbox is added as an additional account, there's nothing specific to the report message add-in here.

Hope this helps!

Thanks
Sri

**Comment by Breid125** [comment]
So not providing the warning that the Report buttons will not work for a mailbox added in that manner is an acceptable omission of information? Consider that “group mailboxes” like info@ purchasing@ etc are among the most frequently targeted for attack, and that an org looking to protect itself buy using these adding leave themselves a hole in defence. Consider the cost of having customer contact Support asking “why doesn’t this work” and the time And money  wasted by not noting this limitation in the documentation.

Ignite 2019 indicated better support for addins on Shared Mailboxes, if this isn’t the case then tell your customers about the inherent limitation. If this is a documented issue, reflect that in the information.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by msbemba** [comment]
@Breid125 Thank you for the feedback. It makes sense to add that information. So I Have added the limitation to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4299

Thanks
Sri

**Comment by siosulli** [comment]
Thanks @Breid125
I've made an update to the what-do-you-need-to-know-before-you-begin section to include some text around 
the Report Message add-in not working on Shared Mailbox within Outlook.

**Comment by Breid125** [comment]
Thank you.

Same text should be applied to:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-phish-add-in?view=o365-worldwide

As they’re effectively the same add-in but with different UI process for submission.

If/when this get’s fixed, I’ll come back and let you know.  =)

-Brendan

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Breid125 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
