### ISSUE TITLE
Clarification of licensing requirements

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4236]
The text states that an org needs the P2 license, but its not clear if each user that is subject to simulated attack needs this license. Please clarify if this is a requirement

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbdcbd5-7bd2-6b55-b72c-cbedfdea776c
* Version Independent ID: 1e6198f8-6ef1-6227-c9e8-f31944a5d1db
* Content: [Attack Simulator in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator?view=o365-worldwide#step-2-create-and-launch-the-spear-phishing-campaign)
* Content Source: [microsoft-365/security/office-365-security/attack-simulator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulator.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DeanGross, in most cases, P2 licenses are purchased and assigned per user. But, there are also rare instances where the P1 or P2 license is org-wide and can't be assigned to individual users. The only example I know of is ATP_ENTERPRISE_FACULTY, but there *might* be others. If you try to install a license to a user in that type of environment, you'll get an error stating that you can't assign individual licenses.

So yes, the users involved need to have P2 licenses.

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
