### ISSUE TITLE
Missing information about required licensing

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/microsoft-365-docs#4238]
Hi, This page is missing vital information to use the Import PST method... This is a premium feature which requires at least _Exchange Online Plan 2_ or _Exchange Online Archiving_ license. 
If not licensed enough, the role _Mailbox Import Export_ is not listed to be able to assign it to _Organisation Management_ role.
Could you please add this detail asap.
Many Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by SvenBell** [comment]
![image](https://user-images.githubusercontent.com/52518943/108934430-a62cea00-7698-11eb-9e33-ce007e917a7d.png)

**Comment by SvenBell** [comment]
**Mail Import Export** role not showing in list of roles to add or remove.

**Comment by markjjo** [comment]
@SvenBell Thanks for feedback. As far as I know, there isn't a licensing requirement for RBAC roles in Exchange Online. In your screenshot above, you might try clicking "Add" under "Roles" and then add the Mailbox Import Export role to the Organization Management role group. As per the doc, this role isn't assigned to Org Management by default.  The list of roles that are displayed in your screenshot are the roles currently assigned to that role group.

If this doesn't work and the role isn't available, would suggest you contact Microsoft Support to investigate.

![image](https://user-images.githubusercontent.com/36746813/109053397-7e865380-7691-11eb-9d96-64bf7aa9e651.png)
