### ISSUE TITLE
Issue with the tenantAllowBlockList Link

### ISSUE THREAD

**Issue by gfard** [MicrosoftDocs/microsoft-365-docs#4240]
Is the link describe in the document applicable anymore? https://protection.office.com/tenantAllowBlockList

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide#url-syntax-for-the-tenant-allowblock-list)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gfard, yes. The feature is currently in some level of Preview. Are you saying you had access to it and it went away, or you never had access to it and you can't access it?

**Comment by gfard** [comment]
Dear Chris

Thank you for your reply.

I had never access to it. Just read about it in MS Docs and tried it access
it. I have the roles mentioned in the matrix and the licenses needed (e5)
Perhaps some screenshots would be useful.

Thank you for your time in advance.


Georgios

Sent by George Fardellas at Gmail dot com

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @gfard Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
