### ISSUE TITLE
Organisation-wide Security & Compliance Retention Policies

### ISSUE THREAD

**Issue by LukeAllinson-NS** [MicrosoftDocs/microsoft-365-docs#4243]
Helllo,

Can I ask if the documentation could be updated to include a note about changing the organisation-wide Security & Compliance Retention policies applied to inactive mailboxes. 
The documentation does state (albeit on a different page) that you cannot change the retention policy that an inactive mailbox is assigned to; this makes sense for policies where mailboxes are explicitly included as an inactive mailbox cannot be explicitly added to a policy.
The documentation does not make it clear that if an additional organisation-wide policy is created, that it is applied to inactive mailboxes too. I have a customer where they want to change the existing global policy for a new one, and it is not obvious what would happen when one is removed and another is added. I have tested this in a lab environment and it appears that the new policy is indeed applied to inactive mailboxes but it would be good if this could be clarified.
For reference, the mailbox hold-types table example of "Mario Necaise" provides the basic use case, but could be expanded to include something about changes in global policies.

Many Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6beff2-9c08-e965-d363-3bebcbf4e6c1
* Version Independent ID: 8547a870-691a-2aed-682a-39c014869683
* Content: [Change the hold duration for an inactive mailbox - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/change-the-hold-duration-for-an-inactive-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/change-the-hold-duration-for-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/change-the-hold-duration-for-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
Closing. Referring the comment  in 4246.
