### ISSUE TITLE
So If we have setup 10 yrs. Audit Logs retention policy then can we access, search or do eDiscovery on Audit logs from the UI and PowerShell up to 10 yrs. back? or do we have contact Microsoft as not sure UI will support access to logs upto 10 yrs back as it is not mention clearly on the documentation page

### ISSUE THREAD

**Issue by sumitvalecha** [MicrosoftDocs/microsoft-365-docs#4247]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@sumitvalecha Audit log retention periods are not retro-active. For 10-yr  audit retention policy, the retention period would be initiated/start after the policy is created/applied. For example, if you created a 10-yr audit retention policy on Mar. 1, 2021, any in-scope audited activity performed **after** Mar. 1, 2021 would be retained 10 yrs in the future (for example, in 2023, you could search for these activities). But audit records for activities performed **before** Mar 01 2021 would not be retained for 10 years, but would be retained according to the retention period in effect at the time the activity was performed. Also, note the 10-yr retention requires that users are assigned E5 licenses with an 10-yr retention add-on (which I 'm not sure is available yet). 10-year retention is an Advanced Audit feature; see this [FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide#faqs-for-advanced-audit) - However, as stated in the FAC, if you have created a 10-yr audit retention policy, those records will be retained for 10 yrs. You just have to purchase the add-on of those users when it does becomes available.

**Comment by markjjo** [comment]
Closing

**Comment by sumitvalecha** [comment]
Sorry for not responding quick.  We have e5 license. I got your point that logs are retained for 10 yrs since the day we create it but my question was more about searching the Audit logs from compliance.microsoft.com or protection.microsoft.com UI. Documentation doesn't mentions it clearly that UI will support the capability to search the backdated logs upto 10yrs So i need confirmation on that and if you can update the documentation to mention it clearly
