### ISSUE TITLE
PowerShell instructions refer to old and non-MFA friendly connection method

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/microsoft-365-docs#4249]
Please update the PowerShell section of this article to link to more up-to-date guidance about how to use Exchange Online PowerShell, rather than include the outdated use of PsSession which doesn't support Modern Authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa612c0e-c089-8b3e-8e2e-dd12b6fc382c
* Version Independent ID: fa014ea6-7aa2-b2bd-d913-165c3241675f
* Content: [Delete a booking calendar](https://docs.microsoft.com/en-us/microsoft-365/bookings/delete-calendar?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/delete-calendar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/delete-calendar.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@webash Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4298

Thanks
Sri

**Comment by webash** [comment]
Nicely done. Thanks :)
