### ISSUE TITLE
In place holds have been retired

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4250]
In the holds for mailboxes you are mention an option is In place holds for mailboxes. This functionality has been retired.
I am cross referencing to the following page for more information
 On Microsoft Docs page  https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-and-litigation-holds is says this 
As we continue to invest in different ways to preserve mailbox content, we're announcing the retirement of In-Place Holds in the Exchange admin center (EAC) in Exchange Online. Starting July 1, 2020, you won't be able to create new In-Place Holds. But you'll still be able to manage In-Place Holds in the EAC or by using the Set-MailboxSearch cmdlet in Exchange Online PowerShell. However, starting October 1, 2020, you won't be able to manage In-Place Holds. You'll only be able to remove them in the EAC or by using the Remove-MailboxSearch cmdlet. Using In-Place Holds in Exchange Server and Exchange hybrid deployments will still be supported. You will also still be able to place mailboxes on Litigation Hold. For more information about the retirement of In-Place Holds in Exchange Online, see Retirement of legacy eDiscovery tools.

When a reasonable expectation of litigation exists, organizations are required to preserve electronically stored information (ESI), including email that's relevant to the case. This expectation often exists before the specifics of the case are known, and preservation is often broad. Organizations may need to preserve all email related to a specific topic or all email for certain individuals. Depending on the organization's electronic discovery (eDiscovery) practices, the following measures can be adopted to preserve email:

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4119f918-a0b2-4bdc-535e-11d2c476f675
* Version Independent ID: 1520175d-398b-4df1-86db-8ba6b26260df
* Content: [How to identify the type of hold placed on an Exchange Online mailbox - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@nikki-c Good point. In-Place Holds are still listed in this topic because it's possible that an existing In-Place Holds may still be applied to mailboxes (especially inactive mailboxes) and they can be removed. So this topic explains how to identify them. I could add a note to the topic stating this. Is that your recommendation/ask?

**Comment by nikki-c** [comment]
I would make it clearer as it is misleading at the moment. And maybe reference the the link I added.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by markjjo** [comment]
@nikki-c Will do. Thanks.
