### ISSUE TITLE
Android Developer Platform 

### ISSUE THREAD

**Issue by rezwansarker** [MicrosoftDocs/microsoft-365-docs#4252]

**Comment by rezwansarker** [comment]
Go Google My Way

**Comment by yogkumgit** [comment]
@rezwansarker What is your feedback and which document you are referring to. Please mention.

**Comment by yogkumgit** [comment]
@rezwansarker We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
