### ISSUE TITLE
The powershell script you list errors out.

### ISSUE THREAD

**Issue by jgdolph** [MicrosoftDocs/microsoft-365-docs#4253]
[The powershell script you list in the document to identify all Bookings associated mailboxes is Get-Mailbox -RecipientTypeDetails SchedulingMailbox -ResultSize:Unlimited | Get-MailboxPermission |Select-Object Identity,User,AccessRights | Where-Object {($\_.user -like '\*@\*')} and it errors out because you have \ in three places you shouldn't.  Correct syntax should be:
Get-Mailbox -RecipientTypeDetails SchedulingMailbox -ResultSize:Unlimited | Get-MailboxPermission |Select-Object Identity,User,AccessRights | Where-Object {($_.user -like '*@*')}  
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7484dd4-5d94-dd6c-0dbe-551c852677c1
* Version Independent ID: 257d60e2-9313-e08b-dccf-120cb4b30f5b
* Content: [Microsoft Bookings Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-faq.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jgdolph Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4292

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jgdolph Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
