### ISSUE TITLE
"Document size equals or is greater than" - unit of measure

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/microsoft-365-docs#4254]
For the condition "Document size equals or is greater than" there's no unit of measure included, and the Security and Compliance console doesn't specify when adding the condition to a rule, either. 

Is this measured in bytes?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28be949f-8589-8f7c-8e08-c029389a1f6e
* Version Independent ID: f5928319-0360-41fa-dda0-5473b4e1a5b2
* Content: [DLP policy conditions, exceptions, and actions (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-conditions-and-exceptions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-conditions-and-exceptions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-conditions-and-exceptions.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
from the New-DLPComplianceRule cmdlet

The DocumentSizeOver parameter specifies a condition for the DLP rule that looks for messages where any attachment is greater than the specified size.

When you enter a value, qualify the value with one of the following units:

- B (bytes)
- KB (kilobytes)
- MB (megabytes)
- GB (gigabytes)
- TB (terabytes)
