### ISSUE TITLE
How to access a specific tenant directly (URL)

### ISSUE THREAD

**Issue by hilari0n** [MicrosoftDocs/microsoft-365-docs#4255]
The document describes how to switch a tenant. It does not specify, how can you access a specific tenant directly, e.g. if there's a URL I can use to access a specific tenant without having to access the default one and switch to the target one.
This sounds like a minor inconvenience, but becomes a real issue, if access to admin center on my default tenant is blocked - then I have no way to get to the UI for switching it to the one where I should have that access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b378de4-ca71-a16b-6669-369e3e3ff9d4
* Version Independent ID: 1a1a6ec6-8c04-2172-7afa-49d268191687
* Content: [Manage multiple tenants - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/multi-tenant/manage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/multi-tenant/manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/multi-tenant/manage.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@hilari0n Thank you for your feedback. I understand the inconvenience mentioned on the issue, however, Azure AD issues security tokens for the permitted tenant and if you are locked out of the default tenant then access to other tenants is also not possible using this method. Unfortunately, there is no direct URLs to Specific tenants available at the moment. You could request a design  change from the user voice forum -https://office365.uservoice.com/

Hope this helps!

Thanks
Sri

**Comment by hilari0n** [comment]
> Azure AD issues security tokens for the permitted tenant and if you are locked out of the default tenant then access to other tenants is also not possible using this method.

I'm not sure I understand. Azure AD issues tokens for the tenant the application is requesting for or for auto-detected (default) tenant if the application does not indicate one (the "common" pseudo-tenant).
If by this you mean, that this is how Microsoft 365 admin page works, then that's clear. If you are saying, that it's not technically possible to work with a tenant if I don't have access for an application (M365 admin app in this case) in the default tenant, then that's not true - I have used (and wrote some) apps, which don't require you to have access to the app in the default tenant to be able to use it in other tenants.
If by "locked out of the default tenant" you mean my account being fully blocked there, then it's understandable that I can't access anything, as that's the tenant which is always responsible for authentication, but that's not the case I described (I only was talking about no access to that specific app in the default tenant, not being locked out of the default tenant completely).

> Unfortunately, there is no direct URLs to Specific tenants available at the moment.

OK. Thanks for this clarification. It is sad how Microsoft does not seem to know how to support their own features (multi-tenancy, B2B) in their own solutions, but at least I know now there's no point in looking for a document on this. It'd be nice if this was clearly mentioned in the documentation.

> You could request a design change from the user voice forum -https://office365.uservoice.com/

I could if the site worked. What I now see there is "This site is not currently active".

**Comment by msbemba** [comment]
@hilari0n Thank you for your feedback. Looks like Microsoft will be moving away from UserVoice feedback sites throughout the 2021 calendar year.

https://support.microsoft.com/en-us/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a

Note there is a design change needed, you will need to provide feedback through one of our channels

1)https://support.microsoft.com/en-us/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a
2)Click on the Feedback button on the M365 Admin center.

I'm sorry we could not help you much in this case as this is more of a documentation team and can document as is.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hilari0n Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
