### ISSUE TITLE
Navigation improvements?

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/microsoft-365-docs#4256]
The article is really good but it's not obvious how to do the things the article tells you about. You can sort of find the things it mentions in the left nav, but might be good to hyperlink from text in this article to the content that explains more in depth about the thing being talked about (Like MFA or Safe Links). Some of the things in the article (like DLP) don't appear by the exact same name in the left nav so might be harder for customer to find.

Also, nitpick, "Safe Links" is a feature name, I think, so probably should be capitalized in the left nav if it can be. :-) 

Adding @pebaum just in case, since it looks like Sirrku might still be set as the primary on this topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2430fe66-6275-30c3-c43d-75164ecd69cc
* Version Independent ID: 0f0dd353-743b-b3d5-3e42-5d5210183ac3
* Content: [Overview of Microsoft 365 Business Premium Security](https://docs.microsoft.com/en-us/microsoft-365/business-video/overview-m365-security?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/overview-m365-security.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/overview-m365-security.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by efrene** [comment]
Added links in this article to others for more information.

**Comment by MazenGhazal** [comment]
this article was not updated because of name changes from ATP.
you should update this ASAP
