### ISSUE TITLE
Missing CNAME record in step by step guide for 123.Reg

### ISSUE THREAD

**Issue by Splish70** [MicrosoftDocs/microsoft-365-docs#4258]
Hi,

When following the great instructions i found the section around adding CNAME lines to be confusing as it denotes there are 6 CNAME records to add but only gives 5 of them!

It may be there are only 5 lines to add and the text needs to be corrected or the missing 6th needs to be added to the instructions.

Kind regards and if i've missed something be kind...its my first post! 

Splish70

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac69fb3-1a2f-cb6d-8a0b-1bbc6169e50d
* Version Independent ID: 2b9e64b6-023f-41ca-c774-c8e51e85802c
* Content: [Create DNS records at 123-reg.co.uk for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-123-reg-co-uk?view=o365-worldwide#BKMK_add_MX)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-123-reg-co-uk.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-123-reg-co-uk.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@Splish70 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4293

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Splish70 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
