### ISSUE TITLE
Filter to get all mailboxes with disabled archive is not accurate

### ISSUE THREAD

**Issue by deividfoggi** [MicrosoftDocs/microsoft-365-docs#4259]
Consider the following section:

Enable archive mailboxes

Run the following command to enable the archive mailbox for all users in your organization (whose archive mailbox is currently not enabled).

Get-Mailbox -Filter {ArchiveGuid -Eq "00000000-0000-0000-0000-000000000000" -AND RecipientTypeDetails -Eq "UserMailbox"} | Enable-Mailbox -Archive

The command above will not get any user that had archive mailbox enabled previously but by any reason it was disabled. If the user had archive in any time and it has been disabled, the archive guid will keep the guid, which means that the command will not enable archive mailboxes for all users whose archive mailbox is currently disabled. It will be more accurate to run the following below, which will return any user including those ones with ArchiveGuid not equal to "00000000-0000-0000-0000-000000000000" but with archive status "None":

Get-Mailbox -ResultSize Unlimited -Filter {ArchiveStatus -eq "None" -and RecipientTypeDetails -eq "UserMailbox"} | Enable-Mailbox -Archive

Also, make sure to include the -ResultSize Unlimited otherwise it will enable archive only for the 1000 first users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@deividfoggi This cmdlet syntax was recently updated to filter on ArchiveGuid property base on github issue #4128 opened by another customer. We made this change because of the issue about AchiveStatus = None documented here: https://docs.microsoft.com/en-us/office365/troubleshoot/archive-mailboxes/archivestatus-set-none

So there seems to be issues with both of these properties. Do you know if the ArchiveDatabaseGuid property could be used or does it have same issue of the value not being cleared out if an active archive is disabled? 

I will follow up with engineering as well.

**Comment by deividfoggi** [comment]
Looks like ArchiveDatabaseGuid wasn't cleared out as well. Archive mailbox for this user is disabled, but both guids are there with status none. Looking forward to see the engineering answer. If needed, you guys can contact me internally. Thanks!

![image](https://user-images.githubusercontent.com/39340082/109231461-69024e00-77a5-11eb-9e5a-11110b10c467.png)

**Comment by yogkumgit** [comment]
@markjjo do we have any additional input on this issue. Please update. Thanks
