### ISSUE TITLE
Warning for Yammer Native Mode

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/microsoft-365-docs#4263]
Hi, to section where you mentioned the activities automatically renew Microsoft 365 Group, you should add warning that "All Company" group converted in Yammer Native Mode to Microsoft 365 Group does not support such, and Yammer activities does not count. At least to time, when Yammer address this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979f0a6e-be32-af1e-5724-d1104ebe3ef5
* Version Independent ID: cb9b993a-2224-5bb8-64b8-d1afa7a71c8e
* Content: [Microsoft 365 group expiration policy](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-groups-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Kazzan Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4339. Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Kazzan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
