### ISSUE TITLE
Can we include Content Explorer Indexing rate?

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/microsoft-365-docs#4270]
It would be good to provide some detail on how long interrogation of data for sensitive info types takes and how often this inspection happens. None of the documentation tells me how long I would have to wait to see a reasonable report on a large block of data that is uploaded to Sharepoint Online or the services that depend on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 824cab2c-6c02-7661-745a-75f555576067
* Version Independent ID: c11ebc43-42ce-6a5d-8e8f-dc3ea4d13405
* Content: [Get started with activity explorer - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-activity-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-activity-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please add your comment and help us in resolving this issue. Thanks.

**Comment by chrfox** [comment]
HI @jwojan 
Thanks for your comment. As I am sure you already know, the answer is going to be "it depends" how much content you have, where it is network wise etc.  I can ping the PG to ask them about the frequency of jobs.

Chris

**Comment by jwojan** [comment]
Hey Chris, that would be helpful, as you might imagine, we get questions from customers asking “what can I expect” WRT the ability of this to crawl through data? Anything that can help frame that conversation will be an improvement.

-Jon
