### ISSUE TITLE
Small page title mismatch

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/microsoft-365-docs#4272]
Small thing but the page title says "Insider risk solution" and probably should say "...solutions" (plural) to be consistent with the article title or have "overview" appended.
![image](https://user-images.githubusercontent.com/43045782/109370694-4d0ab500-7856-11eb-8fe6-bed71bd316c6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0630c9-36da-97a6-2240-4d559611b887
* Version Independent ID: f9b42858-3eb1-e720-9ba7-a812f38f9bfc
* Content: [Insider risk solution - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-solution-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-solution-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-solution-overview.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Beschorr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4291

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Beschorr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
