### ISSUE TITLE
teamsdevicemgmtsvcprod.blob.core.windows.net missing from Teams section

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/microsoft-365-docs#4273]
As reported [here](https://techcommunity.microsoft.com/t5/microsoft-teams/device-management-in-teams-urls-and-ip-address-ranges/m-p/1489484) and verified by me, Teams Phones download their firmware updates from this URL, which is missing from the "Skype for Business Online and Microsoft Teams" section of the document:

    https://teamsdevicemgmtsvcprod.blob.core.windows.net

Tagging @kruthikaponnusamy  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@rgsteele Thank you for your feedback. I'm currently working with the author to get the document updated. 

Thanks
Sri

**Comment by LauraWi** [comment]
@pandrew1 Please advise if Teams org needs to onboard this endpoint.

**Comment by pandrew1** [comment]
I made a request to the Teams engineering team regarding this

**Comment by LauraWi** [comment]
Engineering has been engaged.
