### ISSUE TITLE
Licensing for ZAP to work.

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/microsoft-365-docs#4275]
I realize that reflecting ever-changing Microsoft licensing requirements in documentation is hard, but I feel this page should **make clear what licensing level is required for ZAP to work.**

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge (ZAP) - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@SwiftOnSecurity Thank you for your feedback. There are no licensing requirements for ZAP to work. I have added the information on the FAQ section via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4338

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SwiftOnSecurity Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
