### ISSUE TITLE
How about the other way round? and no coments

### ISSUE THREAD

**Issue by markquinnuk** [MicrosoftDocs/microsoft-365-docs#4278]
What about if you want to allow everyone except users that are in a certain group? Surely this is the more logical approach. Keep things as default and have a group that disallows M365 groups to be created.

The script has no comments and I am finding it very difficult to follow. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@markquinnuk Thank you for your feedback. Unfortunately, the attribute Enable group creation can either be set to False or true and the attribute GroupCreationAllowedGroupId is the only option available to lock the creation of groups at the moment. If the option to allow except users from a certain group becomes available we will update the document. But for now this is the only option available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @markquinnuk Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
