### ISSUE TITLE
Soft delete period for the SharePoint site

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4282]
Can you confirm what the soft delete period of the SharePoint site associated with the Team is? This page says soft delete for everything in the group is 30 days. 

However on the SharePoint microsoft doc pages it states the SharePoint site is soft deleted for 93 days https://docs.microsoft.com/en-us/sharepoint/delete-site-collection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d49db57-a705-20aa-e98d-5b3d6bbbf9fd
* Version Independent ID: 5a056f2c-03c9-7a34-3196-8bfb1039f6a5
* Content: [Restore a deleted Microsoft 365 group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/restore-deleted-group?view=o365-worldwide&tabs=outlook)
* Content Source: [microsoft-365/admin/create-groups/restore-deleted-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/restore-deleted-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. Microsoft 365 group-connected team sites are in a soft deleted state only for 30 days unlike other SharePoint sites.

Hope this helps!
Thanks
Sri

**Comment by nikki-c** [comment]
It may be worth mentioning that on the Microsoft Docs page. I have been asked this question several times rom clients. It would be good to be able to point them to a specific Microsoft Docs page.

Nikki Chapple
Organisational Change Manager
United Kingdom | Cloud Communications
NTT

T:
+442080800656
M:
+447500766185

NTT Cloud Communications UK Ltd. is an entity of NTT Ltd.

[cid:image001.jpg@01D711A8.46DF82B0]<https://arkadin.com/> [cid:image002.jpg@01D711A8.46DF82B0] <https://twitter.com/arkadinservices#xd_co_f=MDgwMzM4NzQtY2Y5Mi00YTEyLWIxMGQtODQwNWIxMzhiZDgz~>  [cid:image003.jpg@01D711A8.46DF82B0] <https://www.linkedin.com/company/arkadin/>  [cid:image004.jpg@01D711A8.46DF82B0] <https://www.facebook.com/ArkadinCloudComm>  [cid:image005.jpg@01D711A8.46DF82B0] <https://www.instagram.com/globalntt/>  [cid:image006.jpg@01D711A8.46DF82B0] <https://www.youtube.com/user/ArkadinConference>
[cid:image007.jpg@01D711A8.46DF82B0]<http://www.arkadin.com/>

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. The document now contains "After 30 days, the group and its associated contents are permanently deleted and cannot be restored." 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
