### ISSUE TITLE
Bracket in text.

### ISSUE THREAD

**Issue by CherokeeBoose** [MicrosoftDocs/microsoft-365-docs#4283]
Hello! Thanks for the info on this page. I just wanted to share a minor typo with a stray bracket as noted below between following and policy:

"You can select from the following[policy templates to quickly get started with insider risk management:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b230596-3cff-a5b9-e9b6-09297a52796e
* Version Independent ID: e51c4653-7d8a-6090-baa8-3558a2efca57
* Content: [Learn about insider risk management - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@CherokeeBoose Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4324

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CherokeeBoose Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
