### ISSUE TITLE
Misleading Document Title

### ISSUE THREAD

**Issue by steve-novanex** [MicrosoftDocs/microsoft-365-docs#4284]
Thank you for this information; I was hoping to be able to allow external members (contacts) of a distribution list group to be able to send email on behalf of the group, but apparently that isn't allowed.  Given that limitation, the title and first paragraph could be improved by using the term "users" instead of "members" because not all "members" can be set up that way.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b725ac58-0fa5-9f7d-84fa-a8541477fe0e
* Version Independent ID: f2acd0d0-60b8-0744-e241-06fb753aa5d1
* Content: [Allow members to send as or send on behalf of a Group](https://docs.microsoft.com/en-us/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@steve-novanex Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4340

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @steve-novanex Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
