### ISSUE TITLE
Use of Microsoft DLP in Windows Server versions

### ISSUE THREAD

**Issue by paul-rich** [MicrosoftDocs/microsoft-365-docs#4286]
If an organization is using Virtualization of Windows (virtual desktop, such as with Citrix) and the choice is made to use Windows Server 2016, the reader of this article wants to know of the DLP capabilities shown as available in Windows 10 would also be available in Windows Server 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36344d-67bf-68cb-5004-9ac6f27ebf51
* Version Independent ID: 89a7d7e7-c643-eb06-d844-b97b80633b68
* Content: [Create, test, and tune a DLP policy - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-test-tune-dlp-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox  Please add your comment and help us in resolving this issue. Thanks.

**Comment by chrfox** [comment]
HI @paul-rich 
Windows server 2016 is not a supported endpoint for Endpoint DLP.
