### ISSUE TITLE
Clarification on Azure AD registered device removal and impacts

### ISSUE THREAD

**Issue by erik365online** [MicrosoftDocs/microsoft-365-docs#4288]
One of our customers is preparing to get migrated from Microsoft Cloud Deutschland. Our technical Microsoft contact for this recommended to start removing Azure AD registred devices soon, because it can take some time to get this done.
Therefore, I'm in using the section "Azure AD Registered (Company owned)" to get started. The customer has only Azure AD registred devices because no computer objects are synced using Azure AD Connect. 

To me, what's unclear or confusing in the section, is there a need to also run the WPJCleanup tool, besides running the dsregcmd /leave for a registered Azure AD device which should be removed from Azure AD?
I was removing the Azure AD registered device, running the dsregcmd /leave which worked for users but a few test users/clients had issues to proceed using the Office apps after this. Or is it really sufficient to only deploy the CleanupWPJ tool and the registry value?

Could you please clarify this description and also mention possible impacts of running the CleanupWPJ, because users need to be able to proceed using Office 365 apps afterwards as long as the migration from the Microsoft Cloud Germany is not scheduled. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1ecdbe-3ae9-c996-a707-dbf1b31eb4e6
* Version Independent ID: 2c1e763b-73a0-b376-55a3-6240c5d6b230
* Content: [Additional device information for the migration from Microsoft Cloud Deutschland - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/ms-cloud-germany-transition-add-devices?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/ms-cloud-germany-transition-add-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/ms-cloud-germany-transition-add-devices.md)
* Service: **o365-solutions**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by yogkumgit** [comment]
@andybergen  Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@andybergen Gentle reminder, please help us here. Thanks

**Comment by msbemba** [comment]
@erik365online Thank you for your feedback. The author has confirmed that in migrating M365 core customer data at rest we will not cause features to be unavailable. Note that the committed date for migrations to Germany to complete is spring 2023.  https://aka.ms/move 


CC : @yogkumgit 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @erik365online Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
