### ISSUE TITLE
Typo "** Azure Active Directory**" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/microsoft-365-docs#4289]
Typo "** Azure Active Directory**" (ja-jp)

ja-jp: "https://docs.microsoft.com/ja-jp/microsoft-365/compliance/use-your-free-azure-ad-subscription-in-office-365?view=o365-worldwide"
![use-your-free-azure-ad-subscription-in-office-365_j](https://user-images.githubusercontent.com/40815708/109619171-ccacc280-7b7b-11eb-81e7-2e730472fe6a.png)

en-us: "https://docs.microsoft.com/en-us/microsoft-365/compliance/use-your-free-azure-ad-subscription-in-office-365?view=o365-worldwide"
![use-your-free-azure-ad-subscription-in-office-365_e](https://user-images.githubusercontent.com/40815708/109619195-d2a2a380-7b7b-11eb-980a-41f3d4304b3a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b1b7b8-5414-2242-6b27-32ce18651ba9
* Version Independent ID: 47052c23-01a6-7ec2-f634-d95137c3dc63
* Content: [Use your free Azure Active Directory subscription - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-your-free-azure-ad-subscription-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-your-free-azure-ad-subscription-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-your-free-azure-ad-subscription-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@TinaMcN This looks like a loc issue in the ja-jp version, it is not in the en-us version. This is being caused by a space between the double asterix and "Azure". Removing this space in the ja-jp version should fix this.

![image](https://user-images.githubusercontent.com/36746813/109698573-65275080-7b44-11eb-975c-95b31f981427.png)

**Comment by TinaMcN** [comment]
@hyoshioka0128 thanks for reporting it. @marjkjo thanks for the extra info. I passed on to the localization vendors to fix it.

**Comment by TinaMcN** [comment]
@hyoshioka0128 the issue is now fixed, thanks again for letting us know about it.
