### ISSUE TITLE
Clarification about Group users limit

### ISSUE THREAD

**Issue by tomek-wday** [MicrosoftDocs/microsoft-365-docs#4296]
[Enter feedback here]

Hello
I found in the documentation the upper limit of how many users can be part of group.
Implicitly it passes the message 'there is no limit'
But according to community post :
[https://techcommunity.microsoft.com/t5/microsoft-365-groups/office-group-membership-limitation/m-p/170207](url)
There is undocumented limit 2500 users per group. 
Can you please document it?

It's relevant information for large scale integration my team is working on.

Thank you,
Tomasz
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@tomek-wday Thank you for your feedback. In fact, the number of users per group as per Teams limitation is 25000. I'll confirm with the author and make changes accordingly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@siunies Please help us in resolving this issue. Thanks

**Comment by msbemba** [comment]
@tomek-wday I just got the confirmation that we haven’t documented it as a single limit for Groups because the limits apply differently based on the experience i.e. the limit is different when using a Group in Yammer or Teams or SharePoint or Outlook/Email.

For Teams -https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams%C2%A0

@yogkumgit  I have checked with the author and there are no changes required in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @tomek-wday Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
