### ISSUE TITLE
Invoices sent to incorrect recipient

### ISSUE THREAD

**Issue by andrewhellyer** [MicrosoftDocs/microsoft-365-docs#4311]
I have a customer who is being sent invoices to an email address not configured to receive them, and is not assigned any of the roles which would receive them. I am unable to see any billing profile or billing account details, the pages show nothing. It seems there is something else, but is not covered under this help page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50536931-a7c8-620a-aae0-9c4baec51f74
* Version Independent ID: 27ce5737-2b34-cb55-07b0-c8450c0e5d62
* Content: [Change your billing addresses](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@andrewhellyer Thank you for your feedback. Only Billing administrators receive invoices related to the tenant. If there is some else receiving the invoice, I'd start checking the alternate email address as mentioned in the section(https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses?view=o365-worldwide#change-the-alternate-email-address-your-billing-notifications-are-sent-to). If there are still no email addresses configured, the support team at Microsoft can verify why an invoice is being sent to a wrong address.

To contact Microsoft support, you can click on the need help icon on the admin center. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @andrewhellyer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
