### ISSUE TITLE
missing support of shared mailboxes

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/microsoft-365-docs#4312]
Microsoft Support just confirmed that the usage of the report message add-in is not working / supported for shared / team mailboxes.

Can you add such a note to this article?

I would assume the same applies to the report phishing add-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
Hi @sebhe and update on this was actually made yesterday to reflect this and should be available shortly!

**Comment by sebhe** [comment]
Ha, that is funny coincidence. Maybe this was due to my support ticket :-)
looking forward to the updated version

**Comment by siosulli** [comment]
Closing this now as this following is now in the article:

The Report Message add-in is not available for shared mailboxes or mailboxes in on-premises Exchange organizations.
