### ISSUE TITLE
Expected Behavior - Hybrid Exchange Organization

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4316]
Please provide some information about what we should expect when some people in a chat have their mailboxes in Exchange Server and some have them in Exchange Online. How do the DLP policies affect the messages in this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaab3f7-d1d4-c649-efe8-f24913da4f3e
* Version Independent ID: c5710ebf-0ca5-ab46-c490-64ebc308defe
* Content: [Data loss prevention and Microsoft Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-microsoft-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox  Please add your comment and help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@chrfox Gentle reminder, Please help us here. Thanks

**Comment by Nfortini** [comment]
If customer is asking if Teams supports On-prem or Online mailboxes, we already have this info in the documentation that this is supported.

**Comment by chrfox** [comment]
hi @DeanGross 

This scenario is supported.
