### ISSUE TITLE
Missing information in inbound autodiscover rule requirements 

### ISSUE THREAD

**Issue by andrasg** [MicrosoftDocs/microsoft-365-docs#4317]
The "Additional endpoints not included in the Office 365 IP Address and URL Web service" page lists in row 10 the following information:

![image](https://user-images.githubusercontent.com/10730249/109833179-55416680-7c41-11eb-999d-a79076d8eed9.png)

In my view the wildcard DNS names cannot be utilized to filter inbound traffic on an on-premise infrastructure.

Without exact DNS names it does not make sense to have wildcard DNS entries (`*.acompli.net`, `*.outlookmobile.com`, `*.outlookmobile.us`) listed as the source. 

Asks:
- either publish the source IP ranges associated with the these URLs
- or publish the exact DNS names that translate to the IP addresses of the service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
Looking into this.

**Comment by kelleyvice-msft** [comment]
I've requested information from the product group about this, and will update when I get a response.

**Comment by kelleyvice-msft** [comment]
I have updated this information in the article, and also removed the obsolete domain *.acompli.net.
