### ISSUE TITLE
Clarity on how this sign-in experience is triggered in Outlook

### ISSUE THREAD

**Issue by huzzeytech** [MicrosoftDocs/microsoft-365-docs#4321]
Is there a way for a user to request the QR logon form within Outlook? The language here suggests the user may or may not see the option to download Outlook for mobile and in turn be given a QR code. Additional clarity would be great! Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 749a8389-eda6-3059-b713-5d0b3755fe9c
* Version Independent ID: 53000b70-b561-ec33-0b94-f0c26650548b
* Content: [Use a QR code to sign-in to the Outlook mobile apps - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/use-qr-code-download-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/use-qr-code-download-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/use-qr-code-download-outlook.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@huzzeytech Thank you for your feedback. QR logon form does not show within outlook. However, Outlook on the web and Outlook desktop will show the education reminder to users who aren't using Outlook for iOS and Android to check their company email and calendar events from their phone. If users choose to send themselves an SMS text message to download the app on their mobile device, a QR code will then appear on their computer.

The users will see these education reminders only when the MobileAppEducationEnabled is set to true.

Note that this feature is not available for all organizations at the moment, We’ll be expanding to more organizations in the coming weeks through public preview. 

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes required on the document as of now and this can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @huzzeytech Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
