### ISSUE TITLE
Link 404: Use Centralized Deployment PowerShell cmdlets to manage add-ins

### ISSUE THREAD

**Issue by david-ps** [MicrosoftDocs/microsoft-365-docs#4322]
Link Broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61e46dd-c1ff-dfec-5e0e-9f2e7251a5c1
* Version Independent ID: 49f69fa9-33e8-373f-a7f9-26b828510fda
* Content: [Manage add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-addins-in-the-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-addins-in-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@david-ps Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4337

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @david-ps Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
