### ISSUE TITLE
eDiscovery data location is mentioned without explanation

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/microsoft-365-docs#4327]
On the page there is a table explicitly listing 'eDiscovery data locations' 
but the page does not explain what this is , notr refer to an explanation.

I suggest to add a link to a page such as the below , where this is explained :

https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-ediscovery-configuration?view=o365-worldwide#:~:text=Table%201%20%20%20%20Geo%20location%20,%20Europe%20datacenters%20%2011%20more%20rows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f648e8f-a784-82d1-9495-f470330014ca
* Version Independent ID: 01a84ed4-7193-093a-5926-1c91ca078693
* Content: [Plan for Microsoft 365 Multi-Geo - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/plan-for-multi-geo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/plan-for-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/plan-for-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Josverl Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4380

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Josverl Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
