### ISSUE TITLE
Confirm Audit Logging Behavior

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#4329]
Could you please confirm the meaning of "Although mailbox audit logging on by default is enabled for all organizations, only users with E5 licenses will return mailbox audit log events in audit log searches in the Security & Compliance Center or via the Office 365 Management Activity API by default." under "More Information"

It reads as if the UAL is not going to receive any mailbox audit information unless:

1. A user is assigned an E5 license
or
2. The mailbox has "-AuditEnabled $true" set.

Please verify the behavior of mailbox auditing due to this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SeanTGeoghegan, if 'audit logging on by default' is on for the whole organization, but your organization (for example) has a mixture of E3 and E5 licenses, then only those users with E5 licenses automatically appear in audit log searches. That is the main point of the text you quoted.

For E5 users in organizations where 'audit logging on by default' is turned on, the individual AuditLogEnabled parameter on the mailbox does nothing; they're audited by default. To keep them from being audited, you need to use the Set-MailboxAuditBypassAssociation cmdlet as described in the topic.

For E3 licensed users (entire org or in mixed E3/E5 orgs), the ONLY way for those users to appear in audit log searches in the Security & Compliance Center or via the O365 Management API is to set AuditLogEnabled on their mailboxes to $true. In other words, the 'audit logging on by default' being turned on in the organization does nothing for them. To turn off audit logging for those E3 users, you set AuditLogEnabled on their mailbox to (or back to) $false.

Does this make sense? Is there a wording change in the topic that will help clarify?

**Comment by yogkumgit** [comment]
@SeanTGeoghegan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
