### ISSUE TITLE
Missing Drive-By URL under Select a Social Engineering Technique

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/microsoft-365-docs#4330]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c312fd69-72cd-bc86-4fe1-993b60b97bc6
* Version Independent ID: b7887ba6-4775-39f0-e368-68f140ce233d
* Content: [Simulate a phishing attack with Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jwojan, added.

Thanks for the feedback.

Closing

**Comment by jwojan** [comment]
Nothing appears to have been done. The page is still missing Drive-By URL as an option, so the material is still incomplete/incorrect.

**Comment by chrisda** [comment]
Give it a bit. I made the change; it's only a matter of time before the updates are published.
