### ISSUE TITLE
Typo in the page title

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/microsoft-365-docs#4331]
The article title is correct, but the page title has a typo. "Join a Team as **s** guest".

Adding @pebaum as Sirkku still seems to be the listed alias.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ace0390-915a-9b19-83cb-19d4aaffbb02
* Version Independent ID: d8d29213-a347-922a-c1d4-9db0e4d2704d
* Content: [Join a team as s guest](https://docs.microsoft.com/en-us/microsoft-365/business-video/join-team-guest?redirectSourcePath=%252farticle%252fjoin-a-team-as-a-guest-928d1eef-61e2-49ec-b754-c2fe86b34824&view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/business-video/join-team-guest.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/join-team-guest.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@Beschorr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4368

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Beschorr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
