### ISSUE TITLE
GroupLists 

### ISSUE THREAD

**Issue by foyinb** [MicrosoftDocs/microsoft-365-docs#4333]
[Can this article be updated to include the specific admin roles that can create 500k groups? It just says admin. Does this mean anyone with a write admin role in O365? Many Thanks]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@foyinb Thank you for your feedback. Yes, you are correct. Anyone with the write admin role can create m365 groups.
Office 365 Global admins can create Groups via any means, such as the Microsoft 365 admin center, Planner, Teams, Exchange, and SharePoint Online. Other roles can create Groups via limited means, listed below.

Exchange Administrator: Exchange Admin center, Azure AD
Partner Tier 1 Support: Microsoft 365 Admin center, Exchange Admin center, Azure AD
Partner Tier 2 Support: Microsoft 365 Admin center, Exchange Admin center, Azure AD
Directory Writers: Azure AD
SharePoint Administrator: SharePoint Admin center, Azure AD
Teams Service Administrator: Teams Admin center, Azure AD
User Management Administrator: Microsoft 365 Admin center, Yammer, Azure AD

This is why there is no explicit mention of which admin can create as anyone who has access to create the groups can create 500k groups.

Hope this helps!


Thanks
Sri

**Comment by foyinb** [comment]
Yes it does. Many thanks Sri.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @foyinb Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
