### ISSUE TITLE
Lab Documentation

### ISSUE THREAD

**Issue by RobertDLindholmJr** [MicrosoftDocs/microsoft-365-docs#434]
I'm not able to immediately locate any of the lab guides in the "hydrated" lab package, are they available online or how do I go about obtaining them?
Thx,
Bob

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@RobertDLindholmJr - May we know which Microsoft document link you used in reference to this issue?  Please share it with us so we can investigate further. 

Thank you.

**Comment by RobertDLindholmJr** [comment]
Joyce:

I downloaded the "Windows and Office Deployment Kit" from the following [Microsoft] web site:

https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab

and unpacked the lab, which did create the virtual lab environment, however, there didn't seem to be any lab documentation as outlined on the web site above, so if you can please let me know how I can can access the lab documentation, I would appreciate it.

Thank you,

Bob

________________________________

**Comment by mypil** [comment]
@RobertDLindholmJr  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JGruszczyk - Can you please share your insights on this issue? 

**Doc Content:** https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab

**Content Source:** https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md

Thank you.

**Comment by JGruszczyk** [comment]
I have confirmed the lab documentation is in the ZIP folder when downloading
