### ISSUE TITLE
Migrate tenant-to-tenant without on-prem Windows Server Active Directory and Azure AD Sync

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/microsoft-365-docs#4344]
We've attempted the procedure and found that it's impossible to perform without using Azure AD Sync on the target tenant. Namely, the source e-mail needs to be stamped on the destination MailUser's proxyAddress in order for the migration to proceed, however the system removes it automatically. Only by using AD Sync to sync the MailUser object from an on-prem AD can the attribute be protected from removal.

I suggest to update documentation about requirements of Windows Server Active Directory with Azure AD Sync in-place.
Or, if I am wrong, please update how to do tenant-to-tenant, without on-prem WSAD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
(from Georgia Huggins) Hello Hrvoje,

Only the source’s X500 email addresses need to be stamped on the target MailUser’s proxyAddresses. 

Please let me know if we can answer any other questions.

**Comment by yogkumgit** [comment]
@georgiahuggins Please help us in resolving this issues. Thanks

**Comment by georgiahuggins** [comment]
Hello - Yes, we are aware the sample script to populate the attributes on the target mail user object is incorrect. We are working to post an updated (and working) sample script to the docs article shortly. If you are unable to manually update the target mail user object with the correct X500 proxies, please send email to crosstenantmigrationpreview@service.microsoft.com for additional assistance and one of my devs will help you. Thank you!

**Comment by yogkumgit** [comment]
@georgiahuggins Thank you very much for sharing this explanation. @hkusulja Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by hkusulja** [comment]
Please reopen this issue, since documentation is not updated with new script and information, once this is resolved, i suggest closing it then. In mean time, i will send also email to this email address asking for temporary workaround.
