### ISSUE TITLE
Need Geo and data location details

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/microsoft-365-docs#4346]
[How can we know for the Asia-Pacific geo location where data are really stored ? As an example: a central tenant in Europe, require multi-geo feature for Thailand (using APC code). This link "https://docs.microsoft.com/en-us/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide#data-center-geographies" says that "Locations where customer data may be stored" are "Hong Kong, Japan, Malaysia, Singapore, South Korea". Which country will be used to store Thailand data (Exchange/SharePoint/Onedrive online services) ?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32b41c7e-29cd-eb5b-36b2-738b3babd08f
* Version Independent ID: 22eda3f7-1c04-b3b0-95fd-3474b3f991b2
* Content: [Microsoft 365 Multi-Geo - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-multi-geo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@RomanNG Thank you for your feedback.  The locations where customer data may be stored can change within 
Hong Kong, Japan, Malaysia, Singapore and, South Korea. Using PDL the admins can choose only APC and Microsoft will store within these 5 locations mentioned.

While Exo,SPO, and Onedrive store in APC there are other services that will still be stored in the US.

![image](https://user-images.githubusercontent.com/45987684/110784249-792f2880-828f-11eb-9e5f-4e9c5afefed5.png)

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in the document and the issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @RomanNG Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
