### ISSUE TITLE
Missing Drive-By URL under Select a Social Engineering Technique section

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/microsoft-365-docs#4351]
@jwojan, added.
I am not sure why this issue was closed before actually updating/correcting the materials in issue 4430, but I would like this to remain open until the public documentation actually reflects the capabilities in the tool.

Thanks for the feedback.

Closing

_Originally posted by @chrisda in https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4330#issuecomment-791535310_

**Comment by chrisda** [comment]
@jwojan, you can always reopen a closed issue if you like; no need to open another one.

And, I confirmed the changes published, so I'm closing this.

Thanks for the feedback.
