### ISSUE TITLE
Have a question that I didn't see in the FAQ

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [MicrosoftDocs/microsoft-365-docs#4356]
I didn't see any mention of what happens on the firewall when an endpoint is removed from the web service. When an endpoint is removed from the web service, do any existing rules that were created before-hand get removed from the firewall?

In other words, is the removal of firewall rules based off of the web service just as dynamic as creation of them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7dc5655-eddb-360e-8906-d61b8e12f667
* Version Independent ID: c7939a12-24ce-5b98-c958-94a66b90ff1a
* Content: [Managing Office 365 endpoints - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/managing-office-365-endpoints?view=o365-worldwide#office-365-network-endpoints-faq)
* Content Source: [microsoft-365/enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
@FMCUSystemAdmins, thanks for reaching out. Sorry for the delayed response.
The M365 endpoints web service doesn't provide a mechanism for updating firewall rules. Network administrators must either update firewall rules manually or implement their own automation to update rules when changes to endpoints are published through the web service.

**Comment by FMCUSystemAdmins** [comment]
Thank you
