### ISSUE TITLE
Entry syntax not working as documented in tests

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/microsoft-365-docs#4358]
Hi,
The document states:

contoso.com | Allows access to https://contoso.com but not subdomains or paths.
-- | --

https://contoso.com/a | Allows access to https://contoso.com/a, but not subpaths like https://contoso.com/a/b
-- | --

When I tested using either contoso.com and https://contoso.com/, in both instances the links with path(s) (https:/contoso.com/page1/page2) and subdomains (https://path.contoso.com) were not re-written. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-links?view=o365-worldwide#entry-syntax-for-the-do-not-rewrite-the-following-urls-list)
* Content Source: [microsoft-365/security/office-365-security/atp-safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@itishnitsa Thank you for your feedback. I shall test this and update the document if required.

Thanks
Sri

**Comment by msbemba** [comment]
@itishnitsa Thank you for your feedback. Upon testing this works on my test tenant. If this is still an issue, I'd recommend you contact the support team(to raise a bug of fix this in the backend)  via the need help section in the admin center.

If there are still any changes required in the document, Please let us know.

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @itishnitsa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
