### ISSUE TITLE
Permission to update password expiration policy

### ISSUE THREAD

**Issue by AndreasNilssonSWE** [MicrosoftDocs/microsoft-365-docs#4359]
Who has the permission to update password expiration policy?
"_You must be a global admin or password admin to perform these steps._"
"_Only global admins can perform these steps._"
What is it that the password admin can do? Or is this a typo? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@AndreasNilssonSWE Thank you for your feedback. I have tested and only global admins can perform these steps. The document has also been updated to reflect the same. The changes can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4381

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AndreasNilssonSWE Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by AndreasNilssonSWE** [comment]
Thanks @msbemba and @yogkumgit! Take care and be safe.
