### ISSUE TITLE
Apparently there is a need to add a dot at the end of certain operations such as "Add member to role"

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#4362]
I just had a bug raised with our Engineering team that for a customer, protection alerts are not working when an admin adds another user as a member in an admin role.

My customer created the alert by using the operation "Add member to role" and the alert never triggered. Engineering advised me in this bug https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/1988929, that the correct Operation to be added in the alert is "Add member to role."

This is because the unified audit log records the actions in this exact way:

RunspaceId   : ec6225e6-fa45-4b7e-b8dc-b4401c7e4de9
RecordType   : AzureActiveDirectory
CreationDate : 3/4/2021 12:50:48 PM
UserIds      : admin@contoso.onmicrosoft.com
Operations   : Add member to role.

My ask is to please check with Engineering which actions should have the "." at the end, because here https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#role-administration-activities, the dot is missing for each of the operations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#audited-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Alex-Catalin I assume your customer is using PowerShell to create the alert policy. Azure activities (user, group, role, directory, application) contain a period in the operation. So the period much be included when specifying these operation name in parameter values for PowerShell command. I will update the search audit log topic, add the period to the operation names, and include this note:

 Note

The operation names listed in the the Operation column in the following table contain a period ( . ). You must include the period in the operation name if you specify the operation in a PowerShell command when searching the audit log, creating audit retention policies, creating alert policies, or creating activity alerts. Also be sure to use double quotation marks (" ") to contain the operation name.

**Comment by Alex-Catalin** [comment]
Yes Mark, that's correct, they are using Powershell because the interface no longer gives you the possibility to create alerts with certain operations. This is because we are deprecating activity alerts which were initially being used for operations such as the one "Add member to role".

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+2)
[cid:image001.png@01D714B4.D261C2D0]

**Comment by markjjo** [comment]
@Alex-Catalin Thx. The topic has been updated. for example: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#azure-ad-group-administration-activities
