### ISSUE TITLE
Document May Need Updating

### ISSUE THREAD

**Issue by leenana365888** [MicrosoftDocs/microsoft-365-docs#4365]
Hi, this page was last modified in 2016.  I noticed that it is no longer aligned with the current UI in https://compliance.microsoft.com/contentsearch.  Perhaps the document can be reviewed?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2366188c-80ba-dbf5-3feb-56424f3a183e
* Version Independent ID: ef53e022-afd7-1a5f-692d-99716912f50f
* Content: [Check your Content Search query for errors - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/check-your-content-search-query-for-errors?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/check-your-content-search-query-for-errors.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/check-your-content-search-query-for-errors.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@leenana365888 Thank you for your feedabck. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4564
