### ISSUE TITLE
URL of "Terms Of use" are not included in the URL Referential

### ISSUE THREAD

**Issue by Tomtom10000** [MicrosoftDocs/microsoft-365-docs#4367]
The url "https://tokenprovider.termsofuse.identitygovernance.azure.com" is not included in the repository:
https://docs.microsoft.com/fr-fr/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
We use this repository to open the flow for all proxies in our company, if not in the repository, users will not access it and therefore it will not be able to access O365 because they can not validate temsofuse.

**Comment by msbemba** [comment]
@Tomtom10000 Thank you for your feedback. We will work with the author and Update the document as needed.

Thanks
Sri

**Comment by LauraWi** [comment]
@pandrew1  -- not sure if this URL should be in scope for this topic.

**Comment by pandrew1** [comment]
I am not familiar with identity governance. I did find this one reference to the URL in a web search which implies you could forward this to the Teams org for review. https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/39756391-terms-of-use-agent-string

**Comment by yogkumgit** [comment]
@LauraWi

**Comment by yogkumgit** [comment]
@LauraWi Gentle reminder, please reply.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I'm discussing a proposed solution to this issue with the product group.
