### ISSUE TITLE
Document content is outdated

### ISSUE THREAD

**Issue by OskarNet** [MicrosoftDocs/microsoft-365-docs#4371]
Document content is outdated.
The menu items and links are not as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae8bb5b-f369-5898-eabf-61b179666333
* Version Independent ID: 24d27dd6-c2cb-2025-e0b8-c292dd275965
* Content: [Move users to a different subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/move-users-different-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/move-users-different-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/move-users-different-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@OskarNet Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4438

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @OskarNet Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
