### ISSUE TITLE
Ambigous requirements for mailbox migration/Hybrid servers

### ISSUE THREAD

**Issue by PM735** [MicrosoftDocs/microsoft-365-docs#4373]
The line 6 in the table is supposed to address requirements for inbound traffic during mailbox migration or Hybrid coexistence.

Here are the issues:

**1. Missing SMTP traffic**

Mailbox migration requires inbound SMTP traffic to on-premise servers
No mention in the line 6 and in table on what source IPs are to be authorized for inbound SMTP traffic to Hybrid servers on-premise.
Please indicate what source IP ranges are to be authorized for incoming SMTP connections during mailbox migration.

**2. Reference to the table "Office 365 URLs and IP address ranges"**

To find Microsoft's source IP addresses to be authorized for mailbox migration, the line 6 sends readers back to the table "Office 365 URLs and IP address ranges". However this table is designed for endpoints and outbound traffic and contains  URLs with wildcards. It is not technically possible to authorize URLs like *.protection.outlook.com as source for inbound traffic on firewalls,
Please indicate clarify this ambiguity about URLs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by PM735** [comment]
Can the table be reowrked to clearly specify **O365 source IPs** and **on-premise destination ports** required for on-premise Hybrid servers. 

We have hard time understanding this table, as it does not contain this important information for customers that want to propely manage their firewalls.

**Comment by yogkumgit** [comment]
@kelleyvice-msft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by PM735** [comment]
Any update?

**Comment by tiburd** [comment]
@kelleyvice-msft
Thank you for sharing the information.
Closing this issue.

FYI: @yogkumgit
