### ISSUE TITLE
Powershell command to view spam policies created in Protection.office.com

### ISSUE THREAD

**Issue by jreyes4949** [MicrosoftDocs/microsoft-365-docs#4378]
In protection.office.com under threat management we've created a custom outbound anti-spam policy. Is there a powershell command to "get" and "set" properties for these policies created in the portal? If i run  Get-HostedConnectionFilterPolicy in exchange online module that does not return the four default anti-spam policies + our 1 custom policy that we see in the protection.office.com portal.

**Comment by chrisda** [comment]
@jreyes4949 , use the *-HostedOutboundSpamFilterPolicy cmdlets as explained here: <https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy#use-exchange-online-powershell-or-standalone-eop-powershell-to-configure-outbound-spam-policies>.

**Comment by msbemba** [comment]
@jreyes4949 Thank you for your feedback. You had mentioned that you don't see the default policy or the custom one that is created when you run Get-HostedConnectionFilterPolicy?

What exactly is the output that you are receiving? Meanwhile, I tested and it shows the Custom as well as the Default policy

![image](https://user-images.githubusercontent.com/45987684/111790123-e1ad8380-88e7-11eb-99b3-511122a7b037.png)


Thanks
Sri

**Comment by chrisda** [comment]
To clarify:

- Get-HostedConnectionFilterPolicy = [connection filter policies](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-the-connection-filter-policy) (IP Allow List and IP Block List)
- Get-HostedContentFilterPolicy = [anti-spam policies](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-your-spam-filter-policies)
- Get-HostedOutboundSpamFilterPolicy  = [outbound spam filter policies](https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy)

All of those policies should have a default policy named Default. To see what's up, run the following command:

```powershell
Get-HostedConnectionFilterPolicy | Format-Table Name,IsDefault; Get-HostedContentFilterPolicy | Format-Table Name,IsDefault; Get-HostedOutboundSpamFilterPolicy | Format-Table Name,IsDefault
```

**Comment by msbemba** [comment]
@chrisda Thank you for a detailed explanation.

@yogkumgit There are no changes required in the document as of now. Please close the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @jreyes4949 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
