### ISSUE TITLE
Link broken for Architecture approaches for Microsoft cloud tenant-to-tenant migrations

### ISSUE THREAD

**Issue by septst** [MicrosoftDocs/microsoft-365-docs#4379]
Hello,

After removing tenant-to-tenant file from downloads folder, the link in [Microsoft cloud for enterprise architects illustrations](https://docs.microsoft.com/en-us/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide ) to the same seems broken. Is there a new document to be linked?

**Comment by yogkumgit** [comment]
@septst please indicate which document you are referring to. Thanks

**Comment by septst** [comment]
> @septst please indicate which document you are referring to. Thanks

In [Microsoft cloud for enterprise architects illustrations](https://docs.microsoft.com/en-us/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide), please check the PDF link under the penultimate section [Architecture approaches for Microsoft cloud tenant-to-tenant migrations](Architecture approaches for Microsoft cloud tenant-to-tenant migrations).

**Comment by msbemba** [comment]
@septst Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4439

Thanks
Sri
