### ISSUE TITLE
there is no "test" function in the information type in compliance centre

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/microsoft-365-docs#4384]
"In the Compliance Center, go to Data classification > Sensitive info types and choose the sensitive information type from the list to open the details pane and choose Test."
there is no test function in the compliance centre - only copy, edit, delete and close

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb7953e-5257-2578-4607-2d93940d6845
* Version Independent ID: 8e59d041-619e-d54f-f28e-faac2bc18ef2
* Content: [Get started with custom sensitive information types - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@bakerm00 Thank you for your feedback. I'm working with the author in the backend and will update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@bakerm00 Thank you for your feedback. I can now see the test option on the page. Let us know if you still have an issue.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bakerm00 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
