### ISSUE TITLE
Confusing dates

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4385]
The page shows that it was last updated in January, but there is information about new features in Feb/March. This inconsistency is confusing and doesn't make sense. Is the page date wrong, or the section heading?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cccec9e6-5bc6-bad8-a174-0f08716f365d
* Version Independent ID: 8f10d2a4-4f84-1d19-8b45-b4fd858a4752
* Content: [What's new in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/whats-new-in-office-365-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/whats-new-in-office-365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/whats-new-in-office-365-atp.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. We had few issues with Github PR merges and that is why you see the inconsistency in the date. Once we update the document next you should see consistent Dates on the document.

@yogkumgit There are no changes in the document, The date mismatch was due to merge issues with GitHub and this will get fixed in the subsequent update.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
