### ISSUE TITLE
URL are not included in the O365 referential #71786

### ISSUE THREAD

**Issue by BhargaviAnnadevara-MSFT** [MicrosoftDocs/microsoft-365-docs#4386]
_Originally posted by @Tomtom10000 in https://github.com/MicrosoftDocs/azure-docs/issues/71786#issue-824606359_

The url "https://tokenprovider.termsofuse.identitygovernance.azure.com"  is not included in the repository:
https://docs.microsoft.com/fr-fr/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
We use this repository to open the flow for all proxies in our company, if not in the repository, users will not access it and therefore it will not be able to access O365 because they can not validate temsofuse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by LauraWi** [comment]
@BhargaviAnnadevara-MSFT  -- I don't think this endpoint is actually appropriate for the M365 URLS and IP ranges topic. At any rate, this article is autogenerated from an internal tool and info cannot be manually added to the article (or it will be overwritten). Follow up with me via internal email if you need info about onboarding to the M365 endpoints process.
