### ISSUE TITLE
Failed to retrieve product policy with PolicyId 'AllowSelfServicePurchase'

### ISSUE THREAD

**Issue by desmondgc** [MicrosoftDocs/microsoft-365-docs#4387]
Commands involving `Get-MSCommerceProductPolicies` don't seem to work. (This is not the TLS issue hinted at the bottom of the page.)

```powershell
PS C:\Users\Desmond> Get-MSCommerceProductPolicies -PolicyId AllowSelfServicePurchase
HandleError : Failed to retrieve product policy with PolicyId 'AllowSelfServicePurchase', ErrorMessage - The remote server returned an error: (404) Not Found. ErrorDetails - {"errorCode":"Unknown","reason":"GetProductDetailsByProductIdAsync failed{\"code\":\"NotFound\",\"data\":[],\"details\":[],\"innererror\":{\"code\":\"ResourceNotFound\",\"data\":[\"product\"],\"details\":[],\"message\":\"Requested resource product not found.\"},\"message\":\"The requested resource could not be found.\",\"source\":\"DCatFD\"}"}
At C:\Program Files\WindowsPowerShell\Modules\mscommerce\1.6\MSCommerce.psm1:220 char:5
+     HandleError -ErrorContext $_ -CustomErrorMessage "Failed to retri ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,HandleError
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide#view-a-list-of-self-service-purchase-products-and-their-status)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by vladcatrinescu** [comment]
Hey there @desmondgc ,  I was in the same boat and managed to connect with someone at Microsoft who said they're aware of the issue and should be fixed shortly . In case you're blocked, here is a workaround that would work. 

Check using the 
Product | ProductId
-- | --
Power   Apps per user | CFQ7TTC0KP0P
Power   Automate per user | CFQ7TTC0KP0N
Power   BI Pro | CFQ7TTC0L3PB
Project   Plan 1 | CFQ7TTC0KXND
Project   Plan 3 | CFQ7TTC0KXNC
Visio   Plan 1 | CFQ7TTC0KXN9
Visio   Plan 2 | CFQ7TTC0KXN8

To enable the policy setting for a specific product, run the following command:
Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId CFQ7TTC0KP0N -Enabled $True

To disable the policy setting for a specific product, run the following command:
Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId CFQ7TTC0KP0N -Enabled $False

It's not perfect and you cannot run the "Get", however at least you can update them for now! 

Hope this helps :).  (Btw, I am not Microsoft, but had an issue opened like you and just saw yours here and trying to help :) )

**Comment by yogkumgit** [comment]
@vladcatrinescu Thank you very much for the contribution and sharing this explanation. @desmondgc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
