### ISSUE TITLE
Items listed under "In this section" don't match left side navigation

### ISSUE THREAD

**Issue by texasgirl** [MicrosoftDocs/microsoft-365-docs#440]
Currently it reads like this:
"In this section
End user support for Microsoft Managed Desktop
Admin support for Microsoft Managed Desktop
Manage apps in Microsoft Managed Desktop"

Should be changed to:
"In this section
Admin support for Microsoft Managed Desktop
End user support for Microsoft Managed Desktop
Manage apps in Microsoft Managed Desktop"

so that it matches the left hand navigation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1049457d-73fe-1509-4803-5c17376f5f02
* Version Independent ID: 6e87f95d-b3ce-7426-388c-688e50202a6c
* Content: [Working with Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/working-with-managed-desktop/#feedback)
* Content Source: [microsoft-365/managed-desktop/working-with-managed-desktop/index.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/working-with-managed-desktop/index.md)
* Service: **m365-md**
* GitHub Login: @jaimeo

**Comment by jaimeo** [comment]
Thanks. We'll be reworking this landing page overall fairly soon, and so can reorganize things at that time.

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@texasgirl - From our understanding, the issue has been answered by jaimeo. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
