### ISSUE TITLE
Adjustment to [Revoke admin access to a user's OneDrive] section

### ISSUE THREAD

**Issue by bhawthorne** [MicrosoftDocs/microsoft-365-docs#4402]
In the Revoke section, the steps outlined require an elevation of permissions (and steps) which is not required. The same steps for the [Grant] section will get you to where you need to be to revoke admin access. Adding that path as an option for someone with access to the address book, but not to the SharePoint Admin center, would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Get access to and back up a former user's data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by twernermsft** [comment]
Hi Brent – what is this in regards to? Is there action required by me? I’m currently reassigning topics that were assigned to me to our vendor for updates.

From: Brent Hawthorne ***@***.***>
Sent: Wednesday, March 10, 2021 2:10 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Tom Werner ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/microsoft-365-docs] Adjustment to [Revoke admin access to a user's OneDrive] section (#4402)


In the Revoke section, the steps outlined require an elevation of permissions (and steps) which is not required. The same steps for the [Grant] section will get you to where you need to be to revoke admin access. Adding that path as an option for someone with access to the address book, but not to the SharePoint Admin center, would be helpful.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
  *   Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
  *   Content: Get access to and back up a former user's data - Microsoft 365 admin<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fadmin%2Fadd-users%2Fget-access-to-and-back-up-a-former-user-s-data%3Fview%3Do365-worldwide&data=04%7C01%7Ctwerner%40microsoft.com%7C384456ee905643101d1e08d8e41132b4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510109803481095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=al6ajyv8rq6wr4PDDUI9qklU6fpQPuzRjqIpBjNzgZ0%3D&reserved=0>
  *   Content Source: microsoft-365/admin/add-users/get-access-to-and-back-up-a-former-user-s-data.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fblob%2Fpublic%2Fmicrosoft-365%2Fadmin%2Fadd-users%2Fget-access-to-and-back-up-a-former-user-s-data.md&data=04%7C01%7Ctwerner%40microsoft.com%7C384456ee905643101d1e08d8e41132b4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510109803481095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N6V9OSqOVsbfQqhwFyWBaoaturmcvr839pq5csHyQAo%3D&reserved=0>
  *   Service: o365-administration
  *   GitHub Login: @twernermsft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftwernermsft&data=04%7C01%7Ctwerner%40microsoft.com%7C384456ee905643101d1e08d8e41132b4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637510109803491052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ybhZpG8Odqgg%2BCYAH6oiPxByQoqH%2BqChUKb8zXMZQgc%3D&reserved=0>
  *   Microsoft Alias: twerner

**Comment by bhawthorne** [comment]
The link for feedback on the documentation page took me to that location. The particular section on revoking admin access seems out of date, per my included comment.

**Comment by yogkumgit** [comment]
@twernermsft Please help us in resolving this issue. Thanks

**Comment by lhcole** [comment]
@bhawthorne @yogkumgit I'm happy to take care of any article updates but I'm not following what needs to be updated. Is there a section that should be removed? A path that should be added? You'll have to help me out here. Feel free to reopen with particulars. Thanks.
