### ISSUE TITLE
Is "Insider" the same as "targetted" Release.  Please explain where they both fit in release strategy

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/microsoft-365-docs#4405]
Where does the Office Insider program fit in the corporate setting. I was under the impression that Insider "channel" access comes before "Targeted" Channel / track. 

Please add a note to the page explaining if the  Office Insider channel applies in a corporate setting and where it fits in the tracks diagrammed on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd43f78a-7c74-5c56-c1f0-24deb342455f
* Version Independent ID: f7ed9828-2580-1b50-d126-003d222abb5e
* Content: [Set up the Standard or Targeted release options - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/release-options-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/release-options-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@Ronsss Thank you for your feedback.  Office Insider for Windows is available for those with a Microsoft 365 subscription in two levels: Beta Channel and Current Channel (Preview).

Beta Channel (Ring 2)

Formerly called Insider channel (or Insider Fast), this level is best for those who want to use the latest builds to identify issues and provide feedback about new features still in development, and don’t mind the bit of risk involved in using unsupported builds.

Current Channel (Preview) (Ring 3)

Formerly called Monthly Channel (Targeted as you rightly pointed out) (or Insider Slow), Current Channel (Preview) is best for fans or early adopters who want early access but also want to receive less frequent, more stable updates. Builds come out monthly and are fully supported.


We have now added a link to office insider program (https://insider.office.com/en-us/join/windows) on this article  via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4475 and that explains the channel's available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Ronsss Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Ronsss** [comment]
That is better.
What I would like to see added to the update release options page is description of how MS uses hidden (registry?) "feature flags" to further provide control for "phased roll out". That is the big question I keep seeing, ie someone asks something along line "I have exactly the same version:build:channel as this guy sitting next to me, but he has a new feature that I don't ... WHY?!?" 

TEAMS BLOG: WHY DO I NOT SEE A NEW FEATURE BUT MY COLLEAGUE DOES? - TEAMS
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-release-processes-why-do-i-not-see-a-feature-but/bc-p/2113533#M7903 
The blog link (above) is an “official” MS excuse for the confusion where one user sees’s a “new feature” while another does not. 
They have confirmed my diagnosis/suspicion that they are using a “hidden flag”, which they call a “feature flag”, to control exactly what new features a specific user sees. The blog even has a pretty picture. 
.
This information should be spread more widely and the flags should not be hidden. We, as users and administrators have valid questions about why we see or don't see specific new features that are supposedly released.
