### ISSUE TITLE
Deleting unlicensed user after shared mailbox is created

### ISSUE THREAD

**Issue by ramire-cc** [MicrosoftDocs/microsoft-365-docs#4407]
Hi, this is more of a question,
What happens if I delete the user after the shared mailbox has been created after a month?
Will the shared mailbox still be there?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ramire-cc Thank you for your feedback. The Shared mailbox gets purged as soon as the linked unlicensed user account is deleted from the admin center. They are linked and the user when deleted can still be retrieved for the next 30 days.

Hope this helps!

Thanks
Sri

**Comment by ramire-cc** [comment]
Hi Sri,

Thank you for the response.

So to confirm, if the user is deleted from admin center, so as the shared mailbox’s contents?

I have a shared mailbox on my desktop outlook that I set-up when an employee left. The user is already unlicensed and I don’t see new emails coming in.

Now I want to delete the user completely from admin center but want to keep the shared mailbox contents.

Can I proceed in doing it?

Regards,

[Image]
Ramir Enriquez
Cloudster Connect
a:
Australia, The Philippines, India
w:
www.cloudsterconnect.co<http://www.cloudsterconnect.co/>  e: ***@***.******@***.***>

**Comment by msbemba** [comment]
@ramire-cc While that is possible, the approach needs to be a little different. I'd suggest you to contact Microsoft support via the need help section so that they can help you sort this out.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @ramire-cc Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
