### ISSUE TITLE
Error dot(.) in URL list

### ISSUE THREAD

**Issue by AidarKydyrbekov** [MicrosoftDocs/microsoft-365-docs#4409]
Good day, 

I just want to show you typo or misprint in official docunentation:
we have detected that in documentation of O365 you provided URLs  ".onenote.com"  and ".secure.skypeassets.com", but in real system it trying to connect to "https://onenote.com"  and "https://secure.skypeassets.com"  WITHOUT dot (.)
For URL filtering its a big different between "https://onenote.com" and "https://.onenote.com"
And in the connectivity test resource it is wrote with dot, but testing connection without.

Please correct this two URLs in documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please add your comment and help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
Corrected in a previous update by prepending * to these URLs.
