### ISSUE TITLE
Multifactor authentication should be supported when using the Central Deployment PowerShell module

### ISSUE THREAD

**Issue by SilviuTanasescu** [MicrosoftDocs/microsoft-365-docs#4411]
in the article:
https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide
we provide Centralized Deployment Compatibility Checker.

This tool is not compatible with Multifactor authentication - which means admins need to assume a security risk to use it:
 Note - Multifactor authentication is not supported when using the Central Deployment PowerShell module.

Please provide the possibility to run it while signing in with Multifactor authentication. We have a Premier customer reporting the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@SilviuTanasescu Thank you for your feedback. Unfortunately at the moment, the compatibility checker is not compatible with MFA and the same has been updated in the document accordingly. We keep the documents up to date, but cannot make design changes as such. However, if you would like to leave feedback to the Product group you can do it via the User voice section - https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@SilviuTanasescu Thank you very much for your kind feedback. Considering your valuable feedback, as advised please log this issue as a User Voice. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
