### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tictag** [MicrosoftDocs/microsoft-365-docs#4417]
"Content impace" should read "Content Impact" in section "What's the user and device impact?"

HTH

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e5b93e-9372-b489-55f4-ac6dd72fa2e3
* Version Independent ID: b3f1e27e-655b-63d2-b42d-94994fec2370
* Content: [Wipe a mobile device in Basic Mobility and Security - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/basic-mobility-security/wipe-mobile-device?view=o365-worldwide)
* Content Source: [microsoft-365/admin/basic-mobility-security/wipe-mobile-device.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/basic-mobility-security/wipe-mobile-device.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@tictag Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4422

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tictag Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
