### ISSUE TITLE
Source IP and ports are not specified for Hybrid connections

### ISSUE THREAD

**Issue by PM735** [MicrosoftDocs/microsoft-365-docs#4420]
The rows that refer to Hybrid servers (row 7 and row 8) do not indicate ports and source IP addresses.
Please add **destination on-premise ports** and **O365 source IP addresses** for these rows.
Customers do not expect to allow ANY source to their on-premise Hybrid servers, especially in the context of the recent Exchange bugs and compromises.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please add your comment and help us in resolving this issue. Thanks.

**Comment by PM735** [comment]
Any update?

**Comment by LauraWi** [comment]
Tagging @pandrew1 for comment.

**Comment by pandrew1** [comment]
The additional endpoints page is not currently generated by my teams portal. To find the ports required to be opened customers have to click the link to the Exchange Hybrid docs page to learn more

**Comment by yogkumgit** [comment]
@LauraWi

**Comment by LauraWi** [comment]
Customers are encouraged to use the Exchange Deployment Assistant (linked in topic) for this info. https://docs.microsoft.com/en-us/exchange/exchange-deployment-assistant?view=exchserver-2019
