### ISSUE TITLE
missing in the explanation of ExpressRoute

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/microsoft-365-docs#4421]
Hello

I feel that the explanation of ExpressRoute is different.
In No46, officeapps.live.com is supposed to go through a fast route.
In No81, only odc.officeapps.live.com does not go through ExpressRoute.
However, cdn.odc.officeapps.live.com does not follow the fast route.
Therefore, I think cdn.odc.officeapps.live.com should be listed in No81. 

how is it? 

__
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please add your comment and help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
This issue has been resolved in a previous update.
