### ISSUE TITLE
EOP inbound port-25 SMTP IP address list has been removed, but is still needed

### ISSUE THREAD

**Issue by billvolt** [MicrosoftDocs/microsoft-365-docs#4426]
Step 4 of the document states:  "Following this, restrict inbound port-25 SMTP traffic on your firewall or mail servers to accept mail only from the EOP datacenters, specifically from the IP addresses listed at Exchange Online Protection IP addresses."  In this a link is provided to the following URL:

<https://docs.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges>

The document at the provided URL states specifically that it does not answer the question from step 4, "It does not include network connections from Microsoft into a customer network, sometimes called hybrid or inbound network connections."

Please provide the list promised in step 4.

If by chance it is appropriate to configure Exchange Server's Edge Transport with DNS names (rather than IP addresses) for EOP servers making inbound connections, that would be a valuable addition to this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad38c0e5-d4fa-e34f-fd58-b3a4a07e5276
* Version Independent ID: e55c6ee7-87f4-7ce4-6e25-655a0a36ce44
* Content: [Set up your standalone EOP service - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-your-eop-service?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-your-eop-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-your-eop-service.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@billvolt, I hear you. This same issue was brought up in a different repo (officedocs-exchange). A decision out of our control was made to remove those IP address ranges from the aforementioned urls-and-ip-address-ranges topic (which is apparently automatically generated).

<https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1559>

As you can see, it got rather nasty at times.

Does anything in that other issue help?

**Comment by yogkumgit** [comment]
@billvolt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
