### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by DavidCouzens** [MicrosoftDocs/microsoft-365-docs#4428]
[Enter feedback here]

Microsoft is spelt incorectly half way down the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac69fb3-1a2f-cb6d-8a0b-1bbc6169e50d
* Version Independent ID: 2b9e64b6-023f-41ca-c774-c8e51e85802c
* Content: [Create DNS records at 123-reg.co.uk for Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/create-dns-records-at-123-reg-co-uk?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-123-reg-co-uk.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-123-reg-co-uk.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@DavidCouzens Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4470

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DavidCouzens Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
