### ISSUE TITLE
Need support for PowerShell 6+ to get license information. 

### ISSUE THREAD

**Issue by josh-at-tally** [MicrosoftDocs/microsoft-365-docs#4430]
How am I suppose to adopt using PowerShell Core/ Pwsh 7 when I can't see licenses available before creating a new user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc797a9a-7bdf-4fbc-92db-b1dc5d54eda9
* Version Independent ID: d6907c1a-08ff-e881-37cb-a206f8bffc3d
* Content: [View Microsoft 365 account license and service details with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-account-license-and-service-details-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-account-license-and-service-details-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-account-license-and-service-details-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@josh-at-tally Thank you for your feedback. Currently, the MSOL module does not work with Powershell core/ pwsh 7 and the same has been updated in the document.

The workaround If you are using PowerShell 7 is you can load the module in compatibility mode

import-module AzureAD -usewindowspowershell

We will update the document once the module is available in Powershell core.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @josh-at-tally Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by josh-at-tally** [comment]
Okay thanks, but licensing info is still unable in PowerShell 6+

**Comment by msbemba** [comment]
@josh-at-tally Thank you for your feedback. you are correct. It works only with windows powershell.

Thanks
Sri

**Comment by josh-at-tally** [comment]
Okay, so how am I supposed to adopt this platform without this feature?

This seems to be an issue, why was it closed?

**Comment by msbemba** [comment]
@josh-at-tally Thank you for your feedback.  You are requesting a design change/ Feature request. Unfortunately, we only handle the documentation part. You can provide you feedback through one of our channels regarding the feature requests - https://support.microsoft.com/en-us/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a and the product group/engineering team will look into the feedback.

Hope this helps!

Thanks
Sri
