### ISSUE TITLE
Please add personas to the baseline policies table

### ISSUE THREAD

**Issue by chraymu** [MicrosoftDocs/microsoft-365-docs#4432]
It would be really helpful to have personas added as a column in the table to help with the protection level.

![image](https://user-images.githubusercontent.com/50723702/111165990-a6b8f200-856d-11eb-84bc-cf981670d501.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77aedd2-47a9-fcf5-3cc3-b46fe8548314
* Version Independent ID: 6942764e-b1c3-a1a1-007f-e34d44c5c696
* Content: [Common identity and device access policies - Microsoft 365 for enterprise - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/identity-access-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/identity-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/identity-access-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@chraymu  Thank you for your feedback. What exactly are the changes that you are looking for? The policies can be assigned to different personas based on the organization's requirement.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The issue can be closed as there are no changes required in the document.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @chraymu Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
