### ISSUE TITLE
timescales

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/microsoft-365-docs#4433]
Hi, I am testing insider risk. Everything is setup, have craeated and uplaoded my leaver. I have actioned copying files to USB and cloud etc. how long does it take for a device to report any violations to the console? timescales dont appear to be listed in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Insider risk management settings - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide#indicator-level-settings-preview)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@chiners68 - thanks for your feedback. Some policy templates have prerequisites that must be configured for the policy to generate relevant alerts, so it's not easy to give you a specific time frame. Please see this topic about policies if you're not seeing users or device in-scope for your policy (https://docs.microsoft.com/microsoft-365/compliance/insider-risk-management-policies#policy-health-preview).
