### ISSUE TITLE
You can no longer do this via exchange admin center.

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/microsoft-365-docs#4437]
No longer able to change this via classic exchange admin center and if you follow the links to the security center when accessing the admin center as a partner it says f off..
Another example of you not caring about partners :'(

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@webstaff Thank you for your feedback. This is the expected behavior unfortunately and fixing this needs to start from the RABC roles assigned to delegated administrators. I would recommend you contact Support for partners and provide feedback. 

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in this document.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @webstaff Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
