### ISSUE TITLE
Clarify that owa/ecp and activesync are not supported

### ISSUE THREAD

**Issue by brolifen** [MicrosoftDocs/microsoft-365-docs#4448]
Should add a note on the page somewhere to clarify that Exchange Active Sync and OWA/ECP are not supported for HMA. To be more precise this sort of information should be added.

EAS: Is "partially" supported if you meet all prereqs but there is also no reference to this document:
https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019

OWA/ECP: Refer to Azure AD App Proxy to protect owa and ecp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae987bba-faf5-916d-c3b1-74f547ff8d90
* Version Independent ID: 9f5a7979-af5a-8fbf-45f0-287bb9fa4772
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@brolifen Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4607

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @brolifen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
