### ISSUE TITLE
This document contradicts another document in Azure documentation

### ISSUE THREAD

**Issue by useyourblinker** [MicrosoftDocs/microsoft-365-docs#4451]
[Enter feedback here]

https://azure.microsoft.com/en-us/pricing/details/information-protection/

This seems to list that Microsoft 365 Business includes AIP P1, but the document I am leaving this feedback for does not. Which is it?

I find conflicting information all over the web, but one of these documents has to be incorrect!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#what-subscriptions-do-i-need-to-use-the-new-ome-capabilities)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@useyourblinker Thank you for your feedback. AIP P1 is a part of M365 Business premium . It is available as an add-on on M365 business standard and basic *(needs to be purchased separately). 

The document  https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#what-subscriptions-do-i-need-to-use-the-new-ome-capabilities is accurate.

We will work internally to see if the https://azure.microsoft.com/en-us/pricing/details/information-protection/ can be corrected.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @useyourblinker Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
