### ISSUE TITLE
No mentions about encryption of file and log data

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/microsoft-365-docs#4453]
Hi,

As Dataverse and based on that D365 store attachments in a App Files storage and store logs also outside of the database this article is not complete. Please add description about encryption of these two non-SQL-DB storages.

Thanks.
Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 869cdad4-a8e0-09f1-081d-2da38c269ffc
* Version Independent ID: 16485783-e1be-5d4e-15c0-b52434a068d0
* Content: [Encryption in Microsoft Dynamics 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-in-microsoft-dynamics-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/office-365-encryption-in-microsoft-dynamics-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-encryption-in-microsoft-dynamics-365.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by KCCross** [comment]
This issue has been forwarded over to the dynamics team for resolution.

**Comment by yogkumgit** [comment]
@KCCross Can we assign this to the dynamics team member here in Github, it will help us in tracking. Thanks

**Comment by KCCross** [comment]
No, the doc lives with me. I addressed this issue from the private repo after consult with the Dynamics writing team.

**Comment by soutchilin** [comment]
Any progress on that?
