### ISSUE TITLE
Instructions don't match 

### ISSUE THREAD

**Issue by greggcyrus** [MicrosoftDocs/microsoft-365-docs#4454]
The instructions say to go to "Explorer" under "Threat Management" but I don't have the same options. Under "Threat Management", I see 

- Dashboard
- Submissions
- Real-time Detections
- Review
- Policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58031ac6-a7d2-59ac-59c1-b3e03fbc8f13
* Version Independent ID: 82c2a515-4f33-1771-a175-4ed7d9d31276
* Content: [Use Microsoft Defender for Office 365 together with Microsoft Defender for Endpoint - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@greggcyrus Thank you for your feedback. I tested that and see Real-time detections only. Later released that you may have Microsoft defender for Office 365 plan 1.

If you have Microsoft Defender for Office 365 Plan 2, then you have Explorer.
If you have Microsoft Defender for Office 365 Plan 1, then you have real-time detections.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @greggcyrus Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
