### ISSUE TITLE
How can these logs be automatically exported to a SIEM?

### ISSUE THREAD

**Issue by mgalhouse** [MicrosoftDocs/microsoft-365-docs#4455]
I would like to see instructions here for how to get these audit logs automatically sent to a SIEM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mgalhouse, although admins and others have access to the content in the logs, there's no way to provide the logs to anyone. To view/search the logs, I'm told you have these options:

- Use the [Office 365 Management API](https://docs.microsoft.com/office/office-365-management-api/office-365-management-activity-api-reference).

- [Use a PowerShell script to search the audit log](https://docs.microsoft.com/microsoft-365/compliance/audit-log-search-script)

**Comment by mgalhouse** [comment]
Thank you, @chrisda. The Office 365 Management API looks promising. Our SIEM vendor has a built-in connection for Office 365 logging. If the audit logs are not already captured by that, I hope they can include it in a feature request.
