### ISSUE TITLE
QR code on-demand

### ISSUE THREAD

**Issue by Rudolf112** [MicrosoftDocs/microsoft-365-docs#4460]
How and when are these notifications displayed? How can a user view this QR code on-demand?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 749a8389-eda6-3059-b713-5d0b3755fe9c
* Version Independent ID: 53000b70-b561-ec33-0b94-f0c26650548b
* Content: [Use a QR code to sign-in to the Outlook mobile apps - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/use-qr-code-download-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/use-qr-code-download-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/use-qr-code-download-outlook.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Rudolf112 Thank you for your feedback.

. If users use outlook/owa, This will soon be available on they will see notifications about using this on their mobile devices.  . This is not an option that can be requested on-demand currently. This option is currently available only on targeted release tenants (You can set your tenant to revive targeted release as well -https://docs.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide)

We will be expanding this to public preview soon.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Rudolf112 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Rudolf112** [comment]
My question was 'how' and 'when', neither of those questions were answered. You just re-stated what was already in the documentation.

We switched to targeted release on the tenant, but those notifications haven't shown up anywhere and its been a few weeks.

**Comment by msbemba** [comment]
@Rudolf112 Thank you for your feedback. If you are in the targetted release you should see the option on outlook and OWA. If it is not showing up then this is probably an issue in the backend and should be resolved by our support team. Please use the Need help option in the admin center to open a support ticket. Based on the outcome, If you think this document still needs an update, do let us know.

Thanks
Sri
