### ISSUE TITLE
CSV specifications

### ISSUE THREAD

**Issue by DaveVernon** [MicrosoftDocs/microsoft-365-docs#4461]
The docs say "Import from CSV allows you to import a predefined set of users for this simulation."

What format does the CSV expect?  Email addresses?  Any headers?  Please don't make me guess :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c312fd69-72cd-bc86-4fe1-993b60b97bc6
* Version Independent ID: b7887ba6-4775-39f0-e368-68f140ce233d
* Content: [Simulate a phishing attack with Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DaveVernon, I finally got an answer. It's one email address per line. I updated the topic accordingly.

Thanks for the feedback.

Closing
