### ISSUE TITLE
Mail flow rule does not operate as expected

### ISSUE THREAD

**Issue by OverengineeredNetwork** [MicrosoftDocs/microsoft-365-docs#4462]
### Issues
- I never received the verbiage I populated in the _reject the message and include an explanation_ settings. I pulled a message trace for the two organizational email addresses I used for testing and neither of them showed any sign of an attempted/failed messages.
- It seems that the **Sender: Inside the organization** is unnecessary or at least less necessary than the **Recipient: Outside the organization** setting I added. Thoughts on adjusting the article to reflect this?

### Background
- Automatic forwarding is set to **On - Forwarding** via https://protection.office.com/antispam > Outbound spam filter policy > Automatic Forwarding
- I created the mailflow rule depicted in this article:
- Sender: Inside the organization
- Recipient: Outside the organization (I had to add this because internal auto-forwarding is ok and necessary)
- Message Type: Auto-forward 
- Action: Block the message, then reject the message and include an explanation.

### Testing
- Set up autoforwarding from my organizational email to my external email via OWA > Gear > View All outlook settings > Forwarding > Enable forwarding
- Sent an email from another external email address to my organizational email: **received the auto-forwarded email externally. No explanation verbiage presented.**
- Sent an email from another organizational email address to my organizational email: **did not receive the auto-forwarded email externally. No explanation verbiage presented.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6924feb-c0eb-6ec2-01cb-0265e181beea
* Version Independent ID: 67de4f08-035e-abf4-8c17-61fd10193cc7
* Content: [Stop auto-forwarding emails](https://docs.microsoft.com/en-us/microsoft-365/business-video/stop-email-auto-forward?redirectSourcePath=%252fen-us%252foffice%252fstop-auto-forwarding-emails-in-microsoft-365-f9d693ba-5c78-47c0-b156-8e461e062aa7&view=o365-worldwide)
* Content Source: [microsoft-365/business-video/stop-email-auto-forward.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/stop-email-auto-forward.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@OverengineeredNetwork Thank you for your feedback. I'll test this and update the document if required.

Thanks
Sri

**Comment by msbemba** [comment]
@OverengineeredNetwork Thank you for your feedback. This sounds more like a support issue and we recommend you to contact Support from the need help option on the M365 admin center. If you feel there are any changes required in the document post your support experience, let us know.

Hope this helps!

@yogkumgit No changes required in the document as of now.
Thanks
Sri

**Comment by OverengineeredNetwork** [comment]
@msbemba I completely disagree. 

The steps in the documentation do not produce the stated outcome and should either be updated to reflect the fact that the _reject the message and include an explanation_ verbiage does not work OR whatever team is involved with this functionality should be looped in to fix the underlying issue. 

Also, this article should be updated to reflect which settings are essential and which settings are optional. As far as I can tell, the *Sender: Inside the organization* is unnecessary or at least less necessary than the *Recipient: Outside the organization* setting.

**Comment by msbemba** [comment]
@OverengineeredNetwork I have tested this mail flow rule and it doesn't work for me as well. This sounds more like a bug in the backend. I will check internally on how to proceed with this.

Thanks
Sri

**Comment by OverengineeredNetwork** [comment]
@msbemba thank you very much. I look forward to your findings.

**Comment by supportguy** [comment]
Hello:

I'm trying to use the steps outlined in this doc, and I am having the same issue.

Mail is getting block but no report is being send to the sender. 

Is there any updates on this?

**Comment by msbemba** [comment]
@efrene We have escalated it to the author/product group. For immediate assistance, we request you to contact support via the need help section on the admin center.

Thanks
Sri

**Comment by efrene** [comment]
@msbemba  Can you let me know who you escalated this to on the product team side?   I want to verify with them if any changes are needed to the article.  Thanks!

**Comment by msbemba** [comment]
@efrene This was escalated to the author/PG thru @yogkumgit  and we do not have information on who is working on it from PG.

Thanks
Sri

**Comment by yogkumgit** [comment]
@efrene I sent the email/escalated to you only. :)

**Comment by efrene** [comment]
Forwarded the information of this issue to engineering. Thanks!

**Comment by OverengineeredNetwork** [comment]
Good afternoon,

While re-testing our custom mail flow rule designed to block autoforwarding emails out of our organization I received the expected NDR message.

Would others in this thread (@supportguy) be able to re-test to see if it is resolved for you?
