### ISSUE TITLE
Details missing on how to request this feature to be enabled

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4465]
Throughout this article it mentions about this feature needs to be switched on/ enabled. However this article does not mention how to switch on the ability for users with on premise mailboxes to have their chat data store in the online mailbox. 
I had previously read that it was a support ticket to Microsoft. Can this article confirm the process to enable this feature.

Also can this article confirm what happens when the feature is enabled. Is the user data stored in the online mail box from the date the features is enabled or if the will it store data back to 2018 as that section is not clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0bb4d7-d9fa-ae92-d3ca-246147d1434a
* Version Independent ID: 7ba20db3-55e2-3d29-2d6c-6f68a6b577a8
* Content: [Search for Teams chat data for on-premises users - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by nikki-c** [comment]
Here is the link to the Microsoft article that mentions contacting Microsoft to enable this feature https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-supports-ediscovery-for-teams-users-in-a/ba-p/200009

**Comment by markjjo** [comment]
@nikki-c Thanks for the feedback. This feature is now enabled by default for all organizations. Previously, as per the blog post (from 2018) you had to open a support request to have this enabled. That is no longer the case. I removed this requirement from the article, but not all the references to "having to enable" or "after you enable". Good catch and bad on me. I will fix this.

What happened when you had to request this? The request resulted in displaying the "Add Office App content for on-premises users" checkbox to the search UI. Now we display this by default. This checkbox corresponds to the IncludeUserAppContent parameter for New-ComplianceSearch cmdlet. Here's a description of this parameter:

_The IncludeUserAppContent parameter specifies that you want to search the cloud-based storage location for users who don't have a regular Microsoft 365 user account in your organization. These types of users include users without an Exchange Online license who use Office applications, Microsoft 365 guest users, and on-premises users whose identity is synchronized with your Microsoft 365 organization. Valid values are:

$true: The cloud-based storage location for the users specified in the ExchangeLocation parameter will be included in the search. If you use the value All for the ExchangeLocation parameter, the cloud-based storage location for any guest or on-premises user will be included in the search.

$false: The cloud-based storage location for the users specified in the ExchangeLocation parameter won't be included in the search. This is the default value._

So checking this checkbox in the UI will include cloud-based storage locations in the search.

**Comment by nikki-c** [comment]
Mark
Thanks for the speedy response. Can you add a statement to say this is now enabled by default. As I was not aware of the change and actions like this are not often added to the roadmap or message centre. Or if it did it passed me by

So just to confirm that now it is enabled by default all the chat data has been retrospectively added to the cloud mailboxes back to 31 Jan 2018. So the organisaton can search back until that date.

My final question is that I assume if the on prem user gets deleted as per normal processes the change is synced to Azure AD and the shadow online mailbox will also get deleted. If so is the soft delete the standard 30 days before hard delete is no retention or holds have been applied

Nikki
