### ISSUE TITLE
Instructions for adding storage do not work

### ISSUE THREAD

**Issue by ararag** [MicrosoftDocs/microsoft-365-docs#4471]
The instructions for adding storage direct the reader to buy an add-on named "Office 365 Extra File Storage", but there is no such add-on in M365 admin center, under "purchase services". Where can I find it, or alternatively, how can I buy extra file storage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@ararag Which product do you have? Is it one of the ones listed in [Is my plan eligible for Office 365 Extra File Storage?]( https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide#is-my-plan-eligible-for-office-365-extra-file-storage)

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Thank you very much for digging deep into it.  @ararag We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
