### ISSUE TITLE
I am totally confused

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4472]
There is a big long discussed about how policy tips are supported in OWA and Outlook 2013, but then in https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide#outlook-2013-and-later-supports-showing-policy-tips-for-only-some-conditions, it says 

"Currently, Outlook 2013 and later **supports showing policy tips** only for these conditions:

- Content contains
- Content is shared

Note that Exceptions are considered conditions and all of these conditions work in Outlook, where they will match content and enforce protective actions on content. **But showing policy tips to users is not yet supported**.

The scenarios in which policy tips work is entirely too complicated. I can't figure out what to tell our customers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide#policy-tips-in-excel-powerpoint-and-word)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
HI @DeanGross  Please refer to this topic https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-tips-reference?view=o365-worldwide
