### ISSUE TITLE
Microsoft Bookings Duplicate Page

### ISSUE THREAD

**Issue by IFramesGames** [MicrosoftDocs/microsoft-365-docs#4473]
Business Closure is posted twice. It is the same exact page with the same exact title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 487eeebe-1112-6c09-ea92-f991efb93409
* Version Independent ID: 1117edc2-ce3d-7bfc-3254-1f5660b3ae5b
* Content: [Schedule business closures, time off, and vacation time](https://docs.microsoft.com/en-us/microsoft-365/bookings/schedule-closures-time-off-vacation?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/bookings/schedule-closures-time-off-vacation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/schedule-closures-time-off-vacation.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@IFramesGames Thank you for your feedback. Could you please provide the link for the duplicate page?

Or Are you referring to the steps on this page? If yes, The first one is to Schedule ad hoc business closures which are for All staff members, whereas Schedule employee time off is for one or more staff members.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @IFramesGames Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
