### ISSUE TITLE
Build and manage assessments in Compliance Manager

### ISSUE THREAD

**Issue by Gassela** [MicrosoftDocs/microsoft-365-docs#4474]
Hi,
this page reports the following Note:

_Only users who hold a Global Administrator or Compliance Manager Administration role can create and modify assessments. Learn more about roles and permissions_.

The following page (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide) reports:

- **Create assessments**, implement improvement actions, and update test status for improvement actions.
- Roles enabled to to this action: Compliance Manager Administrators, **Compliance Manager Assessors**

OR

- **Create assessments** and perform work to implement improvement actions.
- Roles enabled to to this action: Compliance Manager Administrators, **Compliance Manager Assessors**

Is it a bit misaligned, isnt 't?
So what are the minimal privileges to create an assessment?

Thanks

**Comment by msbemba** [comment]
@Gassela Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4568

Thanks
Sri

**Comment by msbemba** [comment]
@Gassela I have applied the changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4568 

The changes will only reflect post-approval from the author. It reflects exactly what you had said.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit Author has updated the document. The document is now live and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution. @Gassela Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
