### ISSUE TITLE
Description doesn't match reality

### ISSUE THREAD

**Issue by cupntea** [MicrosoftDocs/microsoft-365-docs#4479]
Hi,
When we specified the path with subfolder as described in the document: 

> "/Dest:"https://3c3e5952a2764023ad14984.blob.core.windows.net/ingestiondata/PSTFiles?sv=2012-02-12&amp;se=9999-12-31T23%3A59%3A59Z&amp;sr=c&amp;si=IngestionSasForAzCopy201601121920498117&amp;sig=Vt5S4hVzlzMcBkuH8bH711atBffdrOS72TlV1mNdORg%3D"

The PST file was imported into /ingestiondata and renamed from "outlook.pst" to "PSTFiles". It actually took us a while to understand what's wrong because we couldn't validate CSV file. When we entered "/" after PSTFiles, then we got the following error:
`"Transfer from a file to a directory path is not supported. Please update /Dest with an absolute path to a file." `
meaning that description about subfolder:

> Tip: (Optional) You can specify a subfolder in the Azure Storage location to upload the PST files to. You do this by adding a subfolder location (after "ingestiondata") in the SAS URL. 

is frustrating and false.

Also, it may be important to note that AzCopy has to only be downloaded from "PST import job" itself and not acquired from the official AzCopy Tools website. As only version 8.1.0 allows to upload files from file share (and has the same syntax described in the document).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@cupntea Thanks for feedback. Were you able to resolve this issue and get the PST files uploaded to the subfolder? If so, what was your fix? I'll also forward this to engineering team and try to repro/troubleshoot in my test tenant.

As to your other comment, the article does include a note about only using the version of azcopy that can be downloaded in the new import job wizard. https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#step-1-copy-the-sas-url-and-install-azcopy

**Comment by cupntea** [comment]
@markjjo you are right about the correct version, apologies.

Regarding subfolder no, we couldn't find the way to do that. We essentially named our PST files after user plus incremental. I would like to also note, that files with the same name cannot co-exist in Azure Storage, the last one uploaded replaces the existing one, so they have to be named differently, that's where that fake subfolder came in useful and we managed to upload PSTs with the same name from different users at once (via PS foreach).

**Comment by markjjo** [comment]
@cupntea Thanks for info. Your response reminds me that PST files with the same filename is a core scenario of ingesting to subfolders. But I would think that PST files with identical names would need to be uploaded to different subfolders in the Azure blob. If I understand your reply, I assume you solved this by using unique names for the PST files. I'm not sure how the tool/process can support PST files with identical names (unless they reside in different folders in Azure). Do you have a suggested fix for the documentation? (other than stating that the PST files that you upload must have unique filenames) or if two PST files have the same filename they must be in different subfolders in Azure?

**Comment by cupntea** [comment]
@markjjo you are right, the same name is a very common scenario for PST import, I wonder why no one complained about it so far, though. You assumed correct, we solved it by assigning a unique name for each imported PST _(we added a variable to ".../ingestiondata/'$variable'.pst?sv=..." path)_.
I wasn't familiar with Azure Blobs and I thought it creates a unique subfolder for every import, but turns out it's a very straight forward mechanism.
I don't have a fix, as "Transfer from a file to a directory path is not supported", I don't think there is one, other than generating unique names for every PST.

**Comment by markjjo** [comment]
@cupntea Thanks for the responses, and back and forth. And you're right that I don't recall a customer citing this issue before. I think I should go ahead and add to documentation that PST file names need to be unique (otherwise, how would the import service know which PST file to ingest into a specific mailbox?)  Thanks again.
