### ISSUE TITLE
Set-Content -Encoding

### ISSUE THREAD

**Issue by GitRandyAZ** [MicrosoftDocs/microsoft-365-docs#4481]
I was unable to export the XML of the current rules using PowerShell Core v7.1.3 as it appears that Byte type encoding is not supported.

Error message:
Set-Content: Cannot process argument transformation on parameter 'Encoding'. 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')

I was able to export the XML using the built-in PowerShell of Win10 v5.1.19041.868 as documented in this article.
https://docs.microsoft.com/en-us/microsoft-365/compliance/customize-a-built-in-sensitive-information-type?view=o365-worldwide#export-the-xml-file-of-the-current-rules

Since encoding type of Byte is not in PowerShell Core v7.1, what would be the correct type to export the compliance rules XML?
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-7.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1391cf1-588f-a4a9-8692-8c07cf1e459a
* Version Independent ID: d57337a5-d0f3-de26-2259-6b7fa7613d05
* Content: [Customize a built-in sensitive information type - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customize-a-built-in-sensitive-information-type?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customize-a-built-in-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customize-a-built-in-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @GitRandyAZ 
Thanks for your comment.  You should contact Microsoft Support to help you with your question.

**Comment by GitRandyAZ** [comment]
I don't need technical support. I was just pointing out the Microsoft documentation could be better to annotate the task can't use powershell core v7.x as the called out export option is not available in that version.
