### ISSUE TITLE
Search query section is out of date

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4490]
The text and diagram in the Search query section is out of date. It now includes the option to search for Teams chats stored in the online mailboxes created for on on-premises users and guest guests see article https://docs.microsoft.com/en-gb/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide
![image](https://user-images.githubusercontent.com/69439002/111912203-86eb6780-8a60-11eb-90f9-24a80627e1c9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e514aa-9f04-5cc9-93f6-9f5f2f614c2a
* Version Independent ID: dea1ab15-bc09-05c1-b48b-1a06c0b53b50
* Content: [Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the diagram via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4565

Thanks
Sri
