### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4491]
There is a spelling mistake in the follow paragraph (highlighted in bold):  massages should say messages
The following table identifies the supported tasks that can be performed in Microsoft 365 eDiscovery tools on encrypted files attached to email **massages** and encrypted documents in SharePoint and OneDrive. These supported tasks can be performed on encrypted files that match the criteria of a search. A value of N/A indicates the functionality isn't available in the corresponding eDiscovery tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e38718be-6244-3988-7851-7c8c5625dd9f
* Version Independent ID: 4581a9e4-b838-c1a9-93a8-d52630128195
* Content: [Decryption in eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery-decryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-decryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-decryption.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@nikki-c Thanks for heads up. Fixed. Should be live by end of day.
