### ISSUE TITLE
Step 4 does not work.  Please update the command to be Get-EXOMailbox -RecipientTypeDetails SchedulingMailbox

### ISSUE THREAD

**Issue by csbescos** [MicrosoftDocs/microsoft-365-docs#4494]
Update the command in step 4 to be Get-EXOMailbox -RecipientTypeDetails SchedulingMailbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa612c0e-c089-8b3e-8e2e-dd12b6fc382c
* Version Independent ID: fa014ea6-7aa2-b2bd-d913-165c3241675f
* Content: [Delete a booking calendar](https://docs.microsoft.com/en-us/microsoft-365/bookings/delete-calendar?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/delete-calendar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/delete-calendar.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@csbescos Thank you for the feedback. 

Tried with Get-EXOMailbox -RecipientTypeDetails Scheduling and it failed, we have made changes to the document to reflect the correct cmdlet

Get-EXOMailbox -RecipientTypeDetails SchedulingMailbox

Hope this helps!

Thanks again for your feedback.


@yogkumgit The document reflects the correct cmdlet now and this issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @csbescos Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
