### ISSUE TITLE
Some submitted emails are not being processed. 

### ISSUE THREAD

**Issue by glr0221** [MicrosoftDocs/microsoft-365-docs#4498]
Hello Microsoft,

A great day to all of you. 

I have manually reported several emails but I was a bit surprised that some of the emails were not being processed/reflected in the User-reported messages. Here is what I found out : 

1. Dragging an email as an attachment to the report email works perfectly, and is reflected in the user-reported messages.
2. Using the MSReport button also works 100%.
3.  Creating a report email and "attaching" an eml file to the report email does not work sometimes.

After some investigation, I found out that some eml files, which are perfectly viewable in outlook, seem to be unacceptable/unprocessable by report mechanism. I say that they are unprocessed because they do not reflect in the "user-reported" messages. 

That being said, is there any difference between a dragged email and an "attached" eml file? What headers are important in making sure that the eml is processable by the system? Or did I miss something in the configuration.

Thank you very much. 

PS : I can freely share the "failing" eml file contents if you need them for testing. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b12c078-eccb-7786-dec6-ea1bdb91d088
* Version Independent ID: aa1e8002-a8db-383e-cbeb-abf92c033bd3
* Content: [Manually submit messages to Microsoft for analysis - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by glr0221** [comment]
I just want to update this with my reproduction steps which are as follows : 

1.  Using MAC-Outlook, save an email as an eml file.
2. Open a browser and open Outlook on the web.
2. Using OWA, create a draft email for phish/junk/not_junk@office365.microsoft.com with a valid subject and an empty body.
3. Click on the attach button (DO NOT DRAG THE EML FILE.) and attach the eml file saved using MAC-for-Outlook.
4. Send the email.
5. Wait for 30-60 minutes and check the user-reported messages count. 

I have tried this 4 times and have found these steps capable of reproducing my reported issue. Thank you.

**Comment by glr0221** [comment]
@yogkumgit 

Any updates on this matter?

Thank you.

**Comment by glr0221** [comment]
@chrisda  @andypunt 

I sincerely apologize for having to mention you on this comment. I checked the history of the document and found several commits by both of you. Again I apologize profusely for having to mention you in this ticket.

As you can see, we have been trying to integrate our solution with the Microsoft solution. Unfortunately, we have seen little to virtually zero progress. This ticket, and the updated comment I made are the reasons why our integration efforts are not progressing.

Due to some time limitations, I am thinking that a short conversation with any MS dev would be truly helpful. Is there any chance I can ask for clarification from the developers of the "phishing-report" solution that microsoft has? So far, the method described in the link below does not work if the eml is file is generated (via outlook) and attached (not dragged) to a report email   : 

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis?view=o365-worldwide

Moreover, submission to custom mailbox by manually attaching an eml file does not work as well. As described in the link below : 

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide

I am not discounting the fact that I may be doing it wrong. But so far, the results have been consistent. "Attaching-by-dragging an email." works. But "manually attaching an eml file." does not work it seems.

Thank you again for your time, patience and understanding regarding this matter.

More power.

**Comment by andypunt** [comment]
You should open a case with support to get help on this. This path should only be used for help for things like clarity on documentation.

**Comment by msbemba** [comment]
@glr0221 Thank you for your feedback. This sounds like an issue with your tenant and we recommend you open a support ticket with Microsoft (via the need help section on the admin center). 

After consulting, If you think there are changes required in the document, let us know.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in the document and the issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @glr0221 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
