### ISSUE TITLE
URL threat protection report "Clicked through during scan"

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#4501]
[In regards to the part of this article about the URL threat protection report, there is mentioned: "Clicked through during scan", but it is not explained what this means. Nobody will understand this and we will get questions from customers about this in support. Can this article be adjusted with an explanation for: "Clicked through during scan" ?

Thanks,]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e62b98-5f0c-8fc3-8163-c028fa5a6445
* Version Independent ID: b8262fa8-ff97-db0a-b2b5-4dd624fb057b
* Content: [View Defender for Office 365 reports in the Reports dashboard - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-reports-for-atp?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-reports-for-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-reports-for-atp.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@JeroenDronkers Thank you for your feedback. We have added more information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4501


**Blocked** (the user was blocked from navigating to the URL)
 **Blocked and clicked through** (the user choose to continue navigating to the URL)
 **Clicked through during scan** (the user clicks on the URL before the scan is complete)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JeroenDronkers Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
