### ISSUE TITLE
Feedback and support for PermanentlyClearPreviousMailboxInfo switch

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#4502]
The feedback is that I am very interested in a first-party tenant to tenant migration option. The information here is a great resource. My perfect possible future for this article is for it to contain a script that does everything for me aside from authenticate to the endpoints needed to run the script, after I populate a few variables, or as close to that as possible within reason (no need to spend 3h to find a way to do something that can be done in a portal in 30s)

Currently, I'll need to digest all this information and then build a script. Once I have that, I'll share feedback of the working script, unless someone beats me to it. :)

Regarding support for the PermanentlyClearPreviousMailboxInfo switch, I'm not quite sure how critical this is to the overall process. But, according to [this issue](https://github.com/MicrosoftDocs/office-docs-powershell/issues/7028) I opened earlier this year, that switch is not supported by Exchange Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@jonwbstr Thank you for your feedback. The switch is available in exchange online. I tested it a few minutes ago.

PS C:\WINDOWS\system32> Set-User test1 -PermanentlyClearPreviousMailboxInfo

Confirm
Are you sure you want to perform this action?
Delete all existing information about user "test1"?. This operation will clear existing values from Previous home MDB
and Previous Mailbox GUID of the user. After deletion, reconnecting to the previous mailbox that existed in the cloud
will not be possible and any content it had will be unrecoverable PERMANENTLY. Do you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "Y"):
WARNING: The command completed successfully but no settings of 'test1' have been modified.

Thanks
Sri

**Comment by jonwbstr** [comment]
I'm not denying that the command does stuff. But it does not work as
intended when working with an online only mailbox.

I created an online mailbox, checked the 3xchange guide, next i removed the
license and ran this command, then readded the license and checked the
exchange guid. It matched the original guid and the mailbox content was
back.

As you noticed the command ran successfully and said no changes were made.
In my scenario it does not say 'no changes were made' and yet the
experience is that the exchange guid does not change.

Feel free to discuss with the owners of the other issue, and I can put you
in touch with the owners of my support ticket who told be it doesn't work
as described.

**Comment by msbemba** [comment]
@jonwbstr I tested this and the Guid Remains after cleaning the mailbox info. I will work with the author and provide you an update.

**Comment by JoeDavies-MSFT** [comment]
@georgiahuggins, Can you help with this issue? Thanks

**Comment by yogkumgit** [comment]
@georgiahuggins Gentle reminder, Please help us. Thanks

**Comment by jonwbstr** [comment]
I don't follow, you have an internal repro of the switch not working as
intended. Do with that info what you want. I have a separate issue looking
into the situation. I thought someone over here might be in a good position
to help fix both articles. If not, that's okay.

**Comment by yogkumgit** [comment]
@jonwbstr  Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
