### ISSUE TITLE
Please clarify the minimum requirements for Azure AD Connect Configuration

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/microsoft-365-docs#4504]
We recently attempted to describe how to configure Azure AD Connect using this document on our video 
 https://youtu.be/dUJnIakSPkA. However we believe that the documents don't provide a clear set of minimum requirements for Azure AD Connect.  The docs simply discuss the options available in the link through on step 1, but it doesn't clarify what's minimally required to make this work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00ba9775-1242-af4d-a9c0-8979cc5d57dc
* Version Independent ID: 5063400b-fe96-79f4-e37f-6c89e26ee9d0
* Content: [Access on-premises resources from an Azure AD-joined device in Microsoft 365 Business - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/access-resources?view=o365-worldwide)
* Content Source: [microsoft-365/business/access-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/access-resources.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@AdamGrossTX Thank you for your feedback. We have added Prerequisites for Azure AD Connect
 via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4534. 

Thanks
Sri

**Comment by AdamGrossTX** [comment]
Sorry but I don't believe your change answers my issue. I want to know the minimum configuration within AAD Connect that will enable on-prem access. I don't need the pre-reqs for installing AAD Connect.

**Comment by msbemba** [comment]
@AdamGrossTX Sorry about that. Are you referring to Cloud provisioning agent requirements? If yes, then this should help https://docs.microsoft.com/en-us/azure/active-directory/cloud-sync/how-to-prerequisites#cloud-provisioning-agent-requirements

Thanks
Sri

**Comment by AdamGrossTX** [comment]
> @AdamGrossTX Sorry about that. Are you referring to Cloud provisioning agent requirements? If yes, then this should help https://docs.microsoft.com/en-us/azure/active-directory/cloud-sync/how-to-prerequisites#cloud-provisioning-agent-requirements
> 
> 
> 
> Thanks
> 
> Sri

No. I specifically want to know what the MINIMUM requirements are to enable access to on-premises resources when configuring Azure AD connect. We thought that Password Hash Sync was needed but have heard from MS that this is not the case, but the actual MINIMUM configuration for Azure AD Connect isn't documented in this doc. This doc simply points to the general setup procedure for Azure AD Connect but doesn't provide any guidance for Which options are required to enable access to on-premises resources.

**Comment by msbemba** [comment]
@AdamGrossTX There are multiple sign-on method's and at least one of those option needs to be selected. For step by step custom installation, this document should help -https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-install-custom

CC : @Sirkkuw 

Thanks
Sri

**Comment by pamcdo** [comment]
Hey there @msbemba,

The question that is really being asked here is what is required to be configured to sync to AAD in order for SSO to on-premises resources to work.

This article has been in need of some technical clarification for a while - We're basically saying that it just works as long as you have AADConnect installed and syncing users and, while that is true, it is an over-simplification of what is happening.

We know what is necessary to make this work happens by default because the attributes for accountName, domainFQDN, and domainNetBios are populated by the appropriate values on-premises and written to AAD so that when an AAD user goes to access an on-premises resource the normal kerberos tgt process can take place on-premises. But we don't say any of that in this article.

The best thing to do at this point may be to have a discussion internally on some changes we want reflected in this article to make it more clear how this actually works.

**Comment by pamcdo** [comment]
@msbemba - I have submitted a PR on the internal repo for this article, #7621

**Comment by msbemba** [comment]
@pamcdo  Thank you.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AdamGrossTX Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by AdamGrossTX** [comment]
I'm confused. What was updated? Have the changes from the internal PR that @pamcdo referenced been published?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit  The internal Merge from @pamcdo  is still pending. Once it merges the document will be updated.

**Comment by msbemba** [comment]
@pamcdo I don't have access to PR#7621. Do you know if this was merged as the live document has not been updated?

Thanks
Sri

**Comment by msbemba** [comment]
@pamcdo I don't have access to PR#7621. Do you know if this was merged as the live document has not been updated?

Thanks
Sri
