### ISSUE TITLE
End of support information missing.

### ISSUE THREAD

**Issue by therealsterk** [MicrosoftDocs/microsoft-365-docs#4505]
Currently there is a list of supported operating systems, but no indication of when an operating system may drop out of support. For example, if an OS goes “end of support”, does it cease to be supported in MDE as well? Without this information provided, how does someone have any advanced warning of future deprecation of support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks.

**Comment by mjcaparas** [comment]
Typically notifications are added on top of a page with deprecation notices to inform customers in advance. Thanks.
