### ISSUE TITLE
time zone change in Microsoft 365 Defender not possible to change same as in MDE. 

### ISSUE THREAD

**Issue by gitmarecki** [MicrosoftDocs/microsoft-365-docs#4507]
applies to Defender for Endpoint - yes, but Microsoft 365 Security - these settings are not available (any more?) and it is not possible to change display time zone. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23a7695c-722d-22af-662c-e8680a492899
* Version Independent ID: b607ed60-729a-0dac-4464-dbc116531b40
* Content: [Microsoft Defender Security Center time zone settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/time-settings?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/time-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/time-settings.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@gitmarecki Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4566
