### ISSUE TITLE
Guidance for Testing

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4509]
Can you please provide some more detailed guidance for creating a test environment. Some information about the pros/cons of each approach listed on this page would be helpful. e.g., when can we use a subdomain instead of a separate tenant, etc. 

----

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4f6b67-85ac-ef6e-5260-6ae160cfd6d8
* Version Independent ID: b4ae42b8-dd36-9f18-092b-af0b55b3c0fb
* Content: [Best practices for configuring EOP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/defender-365-security/best-practices-for-configuring-eop?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-365-security/best-practices-for-configuring-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-365-security/best-practices-for-configuring-eop.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DeanGross, I think the domain vs. subdomain is more about whether you have an active EOP organization or not. If mail is actively flowing through EOP, you'll likely want to use a new, never used subdomain to test settings before rolling them out globally to recipients/senders in the main domain.

The main takeaway from that point should be go slowly and test settings with a small group of users first before you roll them out to everyone. Start with the recommended Standard settings, but be aware of your organizational requirements (i.e., don't turn off IMAP4 and authenticated SMTP submissions if your organization still requires them).

Does this help?

**Comment by DeanGross** [comment]
yes, it does and that makes sense, but when I was reviewing this with a client, they had a lot of questions and we got caught up in wide ranging discussion about testing in O365. Any additional guidance that could be provided to help orgs get comfortable with safe ways to make changes in their production environment would be helpful

**Comment by yogkumgit** [comment]
@DeanGross If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
