### ISSUE TITLE
Untrusted Repos

### ISSUE THREAD

**Issue by mickhowarth** [MicrosoftDocs/microsoft-365-docs#4510]
Following both install instructions in this document give an "Untrusted Repo" warning in MS Powershell.

`Install-Module -Name AzureAD   `

_Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure
 you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): N
WARNING: User declined to install module (AzureAD)._

`Install-Module MSOnline`

_Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure
 you want to install the modules from 'PSGallery'?_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55574af9-0105-dcd1-7eb0-77513df4e54f
* Version Independent ID: 5fe2849b-d39a-4d75-a5ce-e8f577c9a161
* Content: [Connect to Microsoft 365 with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@mickhowarth Thank you for your feedback. I'm going to assume that this issue is about the prompt that is popped when installing a module from the PowerShell Gallery -- the PowerShell Gallery is set as an "untrusted repository" by default to prevent users from installing any module or script from this open gallery without first verifying that they are sure they want to install the given module or script; this applies even for Microsoft-developed modules, such as AzureAd or MSonline. To bypass this prompt in the cases that you're confident the module or script you're installing is safe, you can provide the -Force parameter:

Install-Module -Name AzureAD -Repository PSGallery -Force

You can also set the PSGallery repository to "trusted" to avoid this prompt altogether, but it's advised to keep the repository as it is.
Hope this helps!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by mickhowarth** [comment]
Hi @msbemba 

You're correct, this is what popped up when I was installing a the module as per the instructions in the doc (I put the commands I typed in my comment!).  

It's up to you guys if you want to adjust the document, however I can tell you from being a user here with little to no prior experience with Powershell and attempting an early/simple step here it did take **_a lot_** of extra searching and reading to confirm that it would be okay to trust the repo.

I actually found an note in another advanced step of what I was trying to achieve explaining that the repo might show as untrusted the first time.
**https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install**

It is a small and unobtrusive note that would have saved a user a lot of extra time and frustration.

Surely letting the user know that this might be the case in such an early step of attempting something might be a good idea?

I know in my case it would have saved me a lot of time and to not put information in such an early step. To advise no changes needed, and not to put it in probably explains why I overall had such a horrid experience with the Office365/Powershell documentation yesterday trying to fix something.

Error after error and no explanation as to why. 

Lack of details, caveats and too many assumptions in general.

Cheers,

Michael

**Comment by msbemba** [comment]
@mickhowarth Thank you for your feedback.
 I have added that information on the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4552

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mickhowarth Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mickhowarth** [comment]
Thank you guys. If not me, I think it will help others.
