### ISSUE TITLE
Where is the Allow?

### ISSUE THREAD

**Issue by jrutkowskiIII** [MicrosoftDocs/microsoft-365-docs#4511]
The O365 Policy is Block\Allow List.

There is only Blocking on the Policy page. Where's the Allow capability? 
We get a lot of false positives with Known Phishing, from Microsoft's Announcement and other vendors updates which have no element of phishing in them. I need to be able to add to the Allow list for the domains. To at least skip the phishing analysis.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/defender-365-security/tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-365-security/tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jrutkowskiIII, the feature is still in Preview and evolving.

**Comment by msbemba** [comment]
@jrutkowskiIII LIke Chris mentioned this is under preview. We have added a note on the document to avoid any confusion.

The features described in this article are in Preview, are subject to change, and are not available in all organizations.

You can't configure allowed items in the Tenant Allow/Block List at this time.

Hope this helps!

@yogkumgit There are no changes required in the document and can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @jrutkowskiIII Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
