### ISSUE TITLE
Install the MicrosoftTeams module does not work

### ISSUE THREAD

**Issue by bbollaer** [MicrosoftDocs/microsoft-365-docs#4513]
I m on a MAC Big Sur
I ve installed homebrew.
I ve installed powershell, I ve tested it (pwsh command)

Now trying to install the MicrosoftTeams module through the following command : 
**Import-Module MicrosoftTeams
$userCredential = Get-Credential
Connect-MicrosoftTeams -Credential $userCredential**

Here is the error message  I have : 
Import-Module MicrosoftTeams
Import-Module: The specified module 'MicrosoftTeams' was not loaded because no valid module file was found in any module directory.
PS /Users/xxxx> $userCredential = Get-Credential

PowerShell credential request
Enter your credentials.
User: xxxx@xxxx.onmicrosoft.com
Password for user xxxx@xxxx.onmicrosoft.com: *********

PS /Users/xxx> Connect-MicrosoftTeams -Credential $userCredential
Connect-MicrosoftTeams: The term 'Connect-MicrosoftTeams' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289b637a-ad53-2710-3b6e-7f4ac15916fa
* Version Independent ID: e8de4044-38f3-1002-9816-12515d0cdda0
* Content: [Manage Skype for Business Online with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@bbollaer Thank you for your feedback. What version of Powershell are you using? There are known issues with PowerShell 7 and Teams PowerShell. For the best experience, we recommend that you use PowerShell 5.1.- For more information about teams module, Visit  https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bbollaer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
