### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/microsoft-365-docs#4514]
Both of the images/screenshots on this article are showing as broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 696edac6-9f06-ca79-5969-ef1e30ad0817
* Version Independent ID: a5a5fad9-5fbb-014a-f628-610fdbfe1ddf
* Content: [Customize controlled folder access](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/customize-controlled-folders?view=o365-worldwide&source=docs#allow-specific-apps-to-make-changes-to-controlled-folders)
* Content Source: [microsoft-365/security/defender-endpoint/customize-controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/customize-controlled-folders.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thanks @Beschorr

**Comment by denisebmsft** [comment]
This issue has been fixed, and the changes will render live later today. Closing for now.
