### ISSUE TITLE
Clarification of what can be done with E3 license

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4518]
The section describes what can not be done without E5, but it is not clear to me what can actually be done with E3. The statement about Advanced features, is rather vague. Could you please add a table that lists all of the features with columns for e3 and e5 and checkmarks in the columns as appropriate. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96cedf2c-e6fa-bbfb-61f0-ab4bcaae1479
* Version Independent ID: 45ca9ffb-55e9-7721-3433-017a513a59be
* Content: [Use attack surface reduction rules to prevent malware infection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
@yogkumgit we have a work item in the queue for this. Allow a couple of weeks for the assigned writer to review, draft content, and get it reviewed. Thank you so much for your help!

**Comment by denisebmsft** [comment]
It looks like my colleague has addressed this issue with the article https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules?view=o365-worldwide, and in this section: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#attack-surface-reduction-features-across-windows-versions

Please let us know if you still have questions.
