### ISSUE TITLE
Pulling additional information with the report

### ISSUE THREAD

**Issue by AlliJM** [MicrosoftDocs/microsoft-365-docs#4519]
Is there a way to export additional data when pulling the TSV file report on Bookings?

**Comment by yogkumgit** [comment]
@AlliJM Please mention the document you are referring to. Thanks.

**Comment by AlliJM** [comment]
> @AlliJM Please mention the document you are referring to. Thanks.

On the home page of the bookings page, the admin has the option to download a TSV file with bookings data. Is there a way to change what gets pulled when that tsv file is downloaded?

**Comment by msbemba** [comment]
@AlliJM Thank you for your feedback. As of April 1 2020, You can export only up to 120 days of recent data as a TSV file. Additional data is not available.

We have a document that explains this in detail -https://docs.microsoft.com/en-us/microsoft-365/bookings/reporting-info?view=o365-worldwide#:~:text=You%20can%20now%20see%20a,spreadsheet%20program%2C%20such%20as%20Excel.


Hope this helps!

@yogkumgit  There are no changes required in the document. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AlliJM Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
