### ISSUE TITLE
broken link and inaccurate desciption of ISO27001

### ISSUE THREAD

**Issue by gaborvar** [MicrosoftDocs/microsoft-365-docs#452]
See https://github.com/MicrosoftDocs/microsoft-365-docs/issues/445 to resolve broken link under ISO/IEC CD 27552.  Additionally, ISO/IEC 27001 is not accurately described as privacy management requirements. It is about general security management. 27701 adds privacy to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18c55c05-67a0-51d2-7737-df9822f7416b
* Version Independent ID: 94e7d95e-21cd-862b-ee78-6d30b8d103fd
* Content: [Microsoft Support and Professional Services accountability readiness checklist for the GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-arc-prof-services)
* Content Source: [microsoft-365/compliance/gdpr-arc-prof-services.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-arc-prof-services.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@gaborvar - Thank you for pointing this out.

I would like to clarify, are you suggesting to replace the description of the 2nd bullet point under the Introduction from ISO/IEC 27001 for privacy management requirements to **ISO/IEC 27001 for general security management**?

Please confirm or give us more details on how this content could be edited to incorporate your feedback.

**Comment by gaborvar** [comment]
Yes, and swapped. It can read as follows:

(bullet) ISO/IEC 27001 for information security management requirements in general.
(bullet) ISO/IEC 27701 for privacy information management techniques and requirements.

**Comment by mypil** [comment]
@gaborvar - PR #458  has been created to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by robmazz** [comment]
Closing as corrected
