### ISSUE TITLE
SharePoint Multi-Geo for ISV development-testing environment

### ISSUE THREAD

**Issue by yaniv-intlock** [MicrosoftDocs/microsoft-365-docs#4520]
Can you advise how [SharePoint Multi-Geo](https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-microsoft-365?view=o365-worldwide) can be used and tested by ISVs, particularly in a developer subscription tenant where the number of seats is much lower than the minimum required.

**Comment by yogkumgit** [comment]
@yaniv-intlock Please mention the document you are referring to. Thanks.

**Comment by yaniv-intlock** [comment]
> @yaniv-intlock Please mention the document you are referring to. Thanks.


https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-microsoft-365?view=o365-worldwide

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
@MikePlumleyMSFT Mike, Can you help here? Thanks

**Comment by MikePlumleyMSFT** [comment]
@AdwoodMicrosoft can you help?

**Comment by MikeMorawski** [comment]
Any update on this? There are a lot of nuances I see coming out of this when developing solutions for this type of setup

**Comment by yogkumgit** [comment]
@yaniv-intlock Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
