### ISSUE TITLE
Confusing title

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4527]
The title is misleading. the article is not about creating a custom sensitive information type, it is about creating a rule package. Please change the title to decrease confusion.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d6af897-cba3-dc5c-beb1-4a650fadbaea
* Version Independent ID: 12d1e00e-36c2-71a1-0632-844455b1d00c
* Content: [Create a custom sensitive information type using PowerShell - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @DeanGross 
Thanks for your comment, I'll keep it in mind as the DLP content set is refined.
