### ISSUE TITLE
type "Deserialized.Microsoft.Open.AzureAD.Model.AssignedLicenses" to type "Microsoft.Open.AzureAD.Model.AssignedLicenses"

### ISSUE THREAD

**Issue by genghisCr0n** [MicrosoftDocs/microsoft-365-docs#4528]
When executing the example Powershell code I am receiving the following exception:

Set-AzureADUserLicense: Cannot bind parameter 'AssignedLicenses'. Cannot convert value "class AssignedLicenses {
  AddLicenses: System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AssignedLicense]
  RemoveLicenses: System.Collections.Generic.List`1[System.String]
}
" to type "Microsoft.Open.AzureAD.Model.AssignedLicenses". Error: "Cannot convert the "class AssignedLicenses {
  AddLicenses: System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AssignedLicense]
  RemoveLicenses: System.Collections.Generic.List`1[System.String]
}
" value of type "Deserialized.Microsoft.Open.AzureAD.Model.AssignedLicenses" to type "Microsoft.Open.AzureAD.Model.AssignedLicenses"."

Any direction or clarification is greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073b885d-191e-8c00-fa59-ad83ba79ec10
* Version Independent ID: 4bd5799d-9baf-90b6-634d-398fbea6b66f
* Content: [Assign Microsoft 365 licenses to user accounts with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@genghisCr0n Thank you for your feedback. The PowerShell code is correct as I'm able to test this at my end. For support-related queries, we recommend you contact Microsoft support via the need help link on your m365 admin center.

![image](https://user-images.githubusercontent.com/45987684/113325100-935fa200-9335-11eb-9673-96d7ced17008.png)

@yogkumgit There are no changes required in the document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @genghisCr0n Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
