### ISSUE TITLE
Condensed directory structure exported to your Azure Storage account

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#4537]
[This article should be updated with a detailed description of how to use "Condensed directory structure exported to your Azure Storage account". Apparently this was available previously but was removed(?). Now customers have to trial and error to make this work and we receive support cases about it in CSS'
In order for it to work, an SAS token for the storage account and NOT the container needs to be used.
This is in contradiction to the UI hints and is not mentioned anywhere in the documentation.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2290d327-7e3c-bc52-ca1a-2e6b60d502c0
* Version Independent ID: 4b775396-e48c-717a-fccf-61705776f2ba
* Content: [Export documents from a review set - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-documents-from-review-set?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/export-documents-from-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-documents-from-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@JeroenDronkers Thanks for flagging this. I've reached out to you and PM internally to discuss.

**Comment by markjjo** [comment]
@JeroenDronkers New topic on exporting to custom-owned Azure Storage account has been published. 

https://docs.microsoft.com/en-us/microsoft-365/compliance/download-export-jobs?view=o365-worldwide
