### ISSUE TITLE
Targeted release terminology

### ISSUE THREAD

**Issue by LindaCicero** [MicrosoftDocs/microsoft-365-docs#4538]
Hello! Just wanted to confirm that "Targeted release" is still being used (vs Preview, which I see everywhere else). TY. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd43f78a-7c74-5c56-c1f0-24deb342455f
* Version Independent ID: f7ed9828-2580-1b50-d126-003d222abb5e
* Content: [Set up the Standard or Targeted release options - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/release-options-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/release-options-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@LindaCicero Thank you for your feedback. It used to be the First Release, now it’s usually called Targeted Release or Preview Channel. Since the Admin center still says Targeted release and Standard release, we will stick to that in this document.

Hope this helps!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LindaCicero Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
