### ISSUE TITLE
How to do this on the new Security portal

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/microsoft-365-docs#4539]
How do we replicate this on the new security.microsoft.com portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8db0f60-99aa-1da5-6174-702349863a5f
* Version Independent ID: 24834977-8b8c-0baf-d1d4-4d979afaeaf1
* Content: [Access the Microsoft Defender Security Center MSSP customer portal](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/access-mssp-portal?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/access-mssp-portal.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/access-mssp-portal.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@thommck Thank you for your feedback. At this point, only access to the customer's Microsoft Defender Security Center is available via https://securitycenter.Microsoft.com/?tid=<CustomerTenantId>

We will update when there is an option for MSSP to access the new security portal.

Hope this helps!

@yogkumgit  There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @thommck Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by martin-rojahn** [comment]
Any progress on making this available for the new Security Portal?
