### ISSUE TITLE
Add note specific to Advanced Hunting data retention

### ISSUE THREAD

**Issue by jbrysonMSFT** [MicrosoftDocs/microsoft-365-docs#4540]
Can we add a note on #how-long-will-microsoft-store-my-data-what-is-microsofts-data-retention-policy specific to Advanced Hunting data?

This raw data is only retained for 30 days.  It's a bit confusing as reading this page you'd think it's retained along with other day for the 30-180 days you select when you onboard the service.  You can find this information on the Advanced Hunting page, but when customers go to look at data retention, it's not specified.

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-overview?view=o365-worldwide

"Advanced hunting is a query-based threat-hunting tool that lets you explore up to 30 days of raw data."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df30eb4f-795f-17a3-2a9a-a68c73a2ba75
* Version Independent ID: d9f2b07e-0deb-2bc9-99e3-bdc4f7752914
* Content: [Microsoft Defender for Endpoint data storage and privacy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/data-storage-privacy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/data-storage-privacy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/data-storage-privacy.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jbrysonMSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4595

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jbrysonMSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
