### ISSUE TITLE
"Delete the message before it's delivered: Silently deletes the entire message, including all attachments." mechanic

### ISSUE THREAD

**Issue by dreeves14** [MicrosoftDocs/microsoft-365-docs#4549]
Does this place it in the user's deleted items or is it DELETED aka not delivered aka blown away, no retrievable. **This matters** because I had a question on the MS-101 referencing these exact mechanics and there were 2 answers. One stated it was DELETED and NOT delivered, the other that it was placed in the mailbox deleted folder. You can't expect people to use your own material to study and then have it so open-ended. I wasted 10-15 minutes mulling that question over because stuff like this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dreeves14, it's deleted, as in it never reaches the user's mailbox aka blown away. The only protection/security scenario where you have a delivered message moving around in a mailbox after delivery is related to [zero-hour auto purge (ZAP)](https://docs.microsoft.com/microsoft-365/security/office-365-security/zero-hour-auto-purge). But even then, a message is only moved to the Junk Email folder or quarantine; never to Deleted Items.

**Comment by dreeves14** [comment]
Perfect, thank you for clarifying.
    
    
    
    Dalton Reeves    
    IT Infrastructure Support Analyst    
    P (314) 655-5523 | F (314) 309-3103    
    ***@***.*** | anderscpa.com    
    800 Market Street, Suite 500 | St. Louis, MO 63101   

    ANDERS CPAs + ADVISORS
From: Chris Davis ***@***.***>
Sent: Tuesday, March 30, 2021 11:31 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Dalton Reeves ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/microsoft-365-docs] "Delete the message before it's delivered: Silently deletes the entire message, including all attachments." mechanic (#4549)


<https://github.com/dreeves14>

Warning: This email originated from outside of the Anders email system. Do not click links or attachments in this email unless you recognize the sender and know the contents are safe.<https://github.com/dreeves14>


<https://github.com/dreeves14>
<https://github.com/dreeves14>
________________________________
@dreeves14<https://github.com/dreeves14>, it's deleted, as in it never reaches the user's mailbox aka blown away. The only protection/security scenario where you have a delivered message moving around in a mailbox after delivery is related to zero-hour auto purge (ZAP)<https://docs.microsoft.com/microsoft-365/security/office-365-security/zero-hour-auto-purge>. But even then, a message is only moved to the Junk Email folder or quarantine; never to Deleted Items.

**Comment by yogkumgit** [comment]
@dreeves14 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
