### ISSUE TITLE
get-spoofmailreport shows that it can get data for 90 days - differs to other doco. 

### ISSUE THREAD

**Issue by dogborne** [MicrosoftDocs/microsoft-365-docs#4550]
[The page shows that the "The Get-SpoofMailReport shows data for up to 90 days". When you go to the specific page about Get-SpoofMailReport it shows that data is only available from the last 10 days. Which is true? https://docs.microsoft.com/en-us/powershell/module/exchange/get-spoofmailreport?view=exchange-ps]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb5aaaa-d804-cdbe-79ca-826cb67cc3e5
* Version Independent ID: dd128a8c-afe2-c507-5f19-ed588f00bc7a
* Content: [Walkthrough - Spoof intelligence insight - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dogborne, the statement in the spoof intelligence topic is accurate (I tested it a few weeks ago):

> The spoof intelligence insight shows data from the last 7 days. The spoof intelligence policy and the corresponding Get-PhishFilterPolicy cmdlet in Exchange Online PowerShell shows data from the last 30 days. The Get-SpoofMailReport shows data for up to 90 days.

I'll update the corresponding cmdlet reference topics.

**Comment by chrisda** [comment]
Updated cmdlet ref topics, so Closing.

Thanks for the feedback.
