### ISSUE TITLE
Teams > Send copies of conversations to group members' inboxes -- note that it does not send a copy to the sender's inbox

### ISSUE THREAD

**Issue by bt101** [MicrosoftDocs/microsoft-365-docs#4553]
In the "Send copies of conversations to group members' inboxes" section (https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-groups?view=o365-worldwide#send-copies-of-conversations-to-group-members-inboxes), I believe it is important to note that the member sending the message to the group will not receive a copy of the message, only all other members.  This feature leads one to believe that all members, including the sender, will receive a copy of the message.  In my opinion, sending a copy to the sender (sending the message to ALL members) is actually preferred.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18c17598-3ade-528a-922d-1904f194b931
* Version Independent ID: a9561e0d-3247-58bd-654b-41898affc6ea
* Content: [Manage a group in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@bt101 Thank you for your feedback. When you send a message to a group, you will no longer receive a copy of the message in your inbox by default. If you want to get a copy of messages you send to the group in your inbox follow these steps: -https://support.microsoft.com/en-us/topic/i-m-not-receiving-a-copy-of-messages-i-send-to-a-group-in-my-inbox-07567cda-f5ce-4e52-b278-4c63dfdd6617

Hope the above explanation helps.


@yogkumgit  There are no changes needed in the document as such and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bt101 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
