### ISSUE TITLE
Intune Kernel extensions settings cannot be applied to Mac with Apple M1 - Results in failure

### ISSUE THREAD

**Issue by RedVortex** [MicrosoftDocs/microsoft-365-docs#4557]
I had to completely remove the kernel extensions settings and only keep the system extensions for Apple device running Big Sur that have the new M1 CPU (Intel devices are not affected by this). The custom extensions profile was not applying to M1 devices and was ending in error because of the Kernel extension part and thus, Defender ATP couldn't run properly and did not have full access to disk and was not allowed to run its system extensions on those devices because the profile couldn't be applied, not even partially it seems.

The current documenation page doesn't take this new issue into account in its explanation of what needs to be configured in Intune. It is also not something well known since the M1 is quite new and there is most likely not many people that have encountered/troubleshooted this issue yet. Since this is still working (not giving any error and profile applying correctly) for Intel devices (also running Big Sur, so it's not a OS only issue, it seems to be an OS/Architecture mix issue), it's probably not something many people noticed, yet.

My guess is Apple completely removed support for kernel extensions in Big Sur for M1 CPUs, unlike Intel ones or something similar and that prevents the profile from being applied. Intel's version of Big Sur may still allow it even though it doesn't use it anymore and this may explain why it doesn't fail, yet, on Intel but does so on M1.

I also use the combined mdatp profile config (https://github.com/microsoft/mdatp-xplat/tree/master/macos/mobileconfig/combined) from @maximvelichko which also triggers this issue, I had to remove the part of the kernel extension which was preventing the profile from being loaded onto MacOS Big Sur for Apple Silicon (M1) devices, it was working for Intel CPU but not Apple (M1) ones as well.

I would've update the doc and Maxim's mobileconfig but I'm not sure what is best between completely removing any reference to kernel extensions and only keep system extensions since that is the way forward since Catalina and especially Big Sur or just explain in the doc to not use the kernel extensions if you're going to apply this to M1 devices and just use the system extensions part, etc... I did not want to remove kernel extensions completely in case someone still uses old MacOS versions that still requires the kernel extensions settings...

I'll leave it up to you to decide how approach this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680cec4a-027f-5aa8-b56a-85410d2c7819
* Version Independent ID: 691a04d1-ee6e-ff6e-b8da-4048eb3976b4
* Content: [Deployment with a different Mobile Device Management (MDM) system for Microsoft Defender ATP for Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-other-mdm?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-with-other-mdm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-with-other-mdm.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @maximvelichko
* Microsoft Alias: **mavel**

**Comment by RedVortex** [comment]
I think this explain the behaviour for Apple devices with Mac Silicon chip (M1 / Arm CPU)

https://support.apple.com/en-us/HT211860

Especially the last part about "Additional requirements for Mac computers with Apple silicon": https://support.apple.com/en-us/HT211860#silicon

This is probably what prevents the profile from loading at all. It is only applicable to Apple Silicon and not Intel for Big Sur.

**Comment by RedVortex** [comment]
Seems there is also an article written to explain this by the Intune support team: https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-kernel-extensions-on-macs-running-apple-silicon-are/ba-p/2238727

**Comment by maximvelichko** [comment]
@RedVortex , thanks for reporting it!
I'd advise to install [individual profiles](https://github.com/microsoft/mdatp-xplat/tree/master/macos/mobileconfig/profiles) for the time being. Let's see what to do with the combined profile, as far as I know configuration profiles are natively supported by MDM (i.e. Intune relies on built in OS functionality to deliver them), I wish Apple would make it more reliable/unified on all architectures/versions. If it's not going to happen, then having one profile per payload type would be the best solution.

Have you tried to report this issue to Intune?

**Comment by RedVortex** [comment]
@maximvelichko I think they are already aware of this issue according to this article that seems to have been written by them: https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-kernel-extensions-on-macs-running-apple-silicon-are/ba-p/2238727

I think for now, we should probably do the same thing as they did, that is: tell people in the 365 Docs or in the combined profile readme to not configure/use the kernel extensions configs for Apple Silicon devices until defender ATP doesn't use (maybe it's already the case) kernel extensions at all. Once Defender ATP stops having/using/supporting kernel extensions altogether, the kernel extensions configs become irrelevant and those parts of the 365 Docs, combined profile readme and also the configs themselves in the profile can all be safely removed.

Or we explain the differences, create 2 profiles and suggest to use on or the other depending if you have Apple Silicon devices or not in Intune by the way of inclusion/exclusion of devices or users.

**Comment by maximvelichko** [comment]
@RedVortex , unfortunately, I see no easy way to deploy a config profile conditionally (i.e. profile A to those with version >= 11, and profile B with version <11, or profile A for Intel, and profile B for M1). Maintaining a group with explicit list of machines is prone to errors (think about an owner of a bring-your-own-device machine who decided to upgrade to Big Sur). It could be solved on Intune's side (by documenting how to conditionally deploy profiles)

Yes, having two profiles is an option, though it has to be evaluated first, otherwise it can be a burden for enterprises that have a mixed set of devices (i.e. most of them).

**Comment by maximvelichko** [comment]
Thank you @RedVortex!

I've added https://github.com/microsoft/mdatp-xplat/blob/master/macos/mobileconfig/combined/mdatp-nokext.mobileconfig to support M1 deployment, will update the documentation later

**Comment by yogkumgit** [comment]
@maximvelichko When documentation is updated then please close this issue. Thanks
