### ISSUE TITLE
Mis-translating public CDNs in Japanese article

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/microsoft-365-docs#4559]
Hello,

Public CDNs should generally avoid handling sensitive data. However, a Japanese article recommends that we store the sensitive data on the Public CDN due to a mistranslation.

-Original

> To ensure that your data remains secure, we recommend that you **never store user content or other sensitive data in a public CDN**. 

https://docs.microsoft.com/en-us/microsoft-365/enterprise/content-delivery-networks?view=o365-worldwide&source=docs#is-my-data-safe

-Japanese
>データが安全に維持される状態を維持するために、ユーザー コンテンツや他の機密データをパブリック CDN に**保存し続けすることをお勧めします**。

https://docs.microsoft.com/ja-jp/microsoft-365/enterprise/content-delivery-networks?view=o365-worldwide&source=docs#is-my-data-safe

-My Suggestion
>データが安全に維持される状態を維持するために、ユーザー コンテンツや他の機密データをパブリック CDN に**保存しないことをお勧めします**。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3e4d9f-5c87-71ae-24c3-1d2490812632
* Version Independent ID: 12818354-d3c6-9058-78a5-495ad511fb6d
* Content: [Content delivery networks - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/content-delivery-networks?view=o365-worldwide&source=docs#is-there-a-list-of-all-the-cdns-that-office-365-uses)
* Content Source: [microsoft-365/enterprise/content-delivery-networks.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/content-delivery-networks.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@TinaMcN and @samanro  Kindly suggest, who can help here to resolve this translation issue. Thanks

**Comment by TinaMcN** [comment]
@kefujino thank you for reporting this, it appears to be a machine translation issue.  I sent the article to be human translated and it should be completed in approx. 3 business days.

**Comment by TinaMcN** [comment]
@kefujino the article is now human translated.  Can you please check if the translation is ok now and close if it is.  Thanks again for reporting it.
