### ISSUE TITLE
Grace period not sufficiently explained

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#4562]
I'm missing information that grace period is the expired period, during which (also for trials) users retain access to data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Larryngolog Thank you for your feedback. We have made changes to the document  via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4609

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit Cern confirmed that this has been addressed in another PR and the issue can be closed.

**Comment by Larryngolog** [comment]
Thanks!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Larryngolog Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
