### ISSUE TITLE
Microsoft and non-company owned computers

### ISSUE THREAD

**Issue by cmanhoff** [MicrosoftDocs/microsoft-365-docs#457]
I need to protect company data so I am setting up Microsoft 365 to take advantage of the enhanced security.  However, I have several contractors working for me on a freelance basis.  I can't afford to buy a machine for every contractor and it is commonly expected that freelancers will use their personal machines.  For efficiency sake, we usually provide them with a limited company network account and email.  So, I have two questions:

1) If the contractor is using an Apple computer, I know they can install the Mac version of Office.  What about other features such as Exchange and AD?  What about the device policy if they are using an iOS product?  Will the Microsoft 365 products work with these products?

2) When they logon, my understanding is that their computer will be upgraded to Windows 10 Pro and all other policies applied, even if they own the computer.  How will this impact their personal use, such as visiting websites that we want to block, such as Facebook? If they finish their contract with me, what happens to the Windows 10 Pro software and other programs they've installed.  Can I deprovision their machines and return it to its original state?

If I have to provide them with a company machine that they will return, I will but I'd like to avoid that expense if I could.

Thanks for the help.

**Comment by mypil** [comment]
@cmanhoff - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
