### ISSUE TITLE
Obsolete information in the article

### ISSUE THREAD

**Issue by rezabj** [MicrosoftDocs/microsoft-365-docs#4572]
In the section "TLS certificate information for Exchange Online" are obsolet information. Current certificate is issued by the intermediate authority "DigiCert Cloud Services CA-1", not by "GlobalSign Root CA – R1". The intermediate authority "DigiCert Cloud Services CA-1" is subordinate to root authorit "DigiCert Global Root CA". Current certificate validity is from 6.2.2021 to 6.2.2022.

So there are wrong information in the section "Prepare for the new Exchange Online certificate".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f032f4f-c4b0-9133-aaab-a44f28910472
* Version Independent ID: ffc3850e-1378-850b-5cd6-bde82db00f25
* Content: [How Exchange Online uses TLS to secure email connections - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@rezabj Thank you for your feedback. I'm internally working with the author to confirm and update the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Sent a request through email also. Thanks

**Comment by KCCross** [comment]
This is under review.
