### ISSUE TITLE
What does Security Group refer to? SharePoint Groups, M365 groups? AD groups?

### ISSUE THREAD

**Issue by TGatTheCDC** [MicrosoftDocs/microsoft-365-docs#4573]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2033ca4a-ada3-e874-bc6d-46acfe2079be
* Version Independent ID: 808886b3-8bb2-7dd8-73f6-6466b55c24d5
* Content: [SharePoint Online modern portal site limits - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/Enterprise/modern-portal-limits?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-portal-limits.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-portal-limits.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@TGatTheCDC Thank you for your feedback. The Security group that is referred to includes all types of security groups that can be granted access to a  SharePoint modern site (SP groups& AD security groups etc). Again, this is just a recommendation and not a hard limit.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @TGatTheCDC Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
