### ISSUE TITLE
Domain Setting Location has changed

### ISSUE THREAD

**Issue by fuzailm** [MicrosoftDocs/microsoft-365-docs#4574]
[Enter feedback here]

Domain registration settings on admin.microsoft.com have moved to **Setup>Domains** do not live under **Settings>Domains**. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0012093-49ca-c2f6-a3f3-4e4252fca609
* Version Independent ID: 22784dda-ff03-971b-4d6e-5b0152f62942
* Content: [Add a domain to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?redirectSourcePath=%252fen-US%252fArticle%252fAdd-your-domain-to-Office-365-ffdb2216-330d-4d73-832b-3e31bcb5b2a7&view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/add-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@fuzailm Thank you for your feedback. I can confirm that the add a domain setting is still under settings-->Domains. 

![image](https://user-images.githubusercontent.com/45987684/113196301-f6433180-9280-11eb-81ca-c27d0baeaacc.png)


Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes in the document and the issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @fuzailm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
