### ISSUE TITLE
Outlook for IoS version information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4577]
The table shows that version 4.7.1 or higher is needed. When I look in the Apple App store, the current version is 4.2112. Is this table correct? if so how do we get that version? If not, please correct the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Manage sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@DeanGross  Hi Dean, this is the version I've been given by engineering.  I'll look into it.  Thanks for flagging.

**Comment by cabailey** [comment]
I have the answer, but not sure yet how to clarify this in the table. They changed the versioning format - 4.7.1 is a very old version that using their current numbering format is effectively 4.0007.1. But when it released, it released as 4.7.1 so the number in the table is accurate, but hard to understand when you view the current versions and history that uses the new format. The versioning format for Word, Excel, PowerPoint has remained the same (2.xx).

I could change it in the table to be 4.0007.1+ so the numbering format is consistent and easier to understand in context with current versions, but it's not the version number actually released.  Do you think that's preferable?

**Comment by cabailey** [comment]
Thinking about this some more, I'm inclined to leave it as it's currently documented. It's not untypical to miss off leading zeros and to change it now might look like the version information has changed when it hasn't. When this version released, that was the version number/format they used.

**Comment by DeanGross** [comment]
@cabailey  my confusion is being caused by the version number I see in the Apple Store and in the About setting . I don't have anything close to 4.7. It appears to me that a much newer versions is required, but its not available.

**Comment by cabailey** [comment]
Yes, 4.7.1 is a very old build and no longer showing in the history version in the Apple store. For easier comparison, read 4.7.1+ (no leading zeros) as 4.0007.1+, (not 4.7000.1).  As your version of 4.2112 is higher than 4.0007, you're good to go.

**Comment by cabailey** [comment]
No doc updates needed here, closing.
