### ISSUE TITLE
Office 365 IP Address and URL web service documentation incorrect for endpoint instance type parameter

### ISSUE THREAD

**Issue by andyprinceuk** [MicrosoftDocs/microsoft-365-docs#4578]
The Office 365 IP Address and URL web service documentation available [here](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide#endpoints-web-method) incorrectly notes that the Instance of endpoints (the specific set: Worldwide vs China vs Germany etc) to fetch is provided as a URL parameter, for example
`https://endpoints.office.com/endpoints/?Instance=Worldwide&ClientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7`

However, in actuality it is passed as part of the path, like this:
`https://endpoints.office.com/endpoints/Worldwide?ClientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7`

which the rest of the documentation also demonstrates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd333ae2-34f6-4afd-cdb1-db72303a5736
* Version Independent ID: 5fc52fe8-dade-b8b7-7126-c4e7dd902e62
* Content: [Office 365 IP Address and URL web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/microsoft-365-ip-web-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
Tagging @pandrew1 for comment.

**Comment by pandrew1** [comment]
We do not provide details on the doc page as to the difference between URL parameters and QUERY parameters. Instance is a URL parameter and the others are all QUERY parameters. andyprinceuk assumes that they are all QUERY parameters and therefore the Instance documentation is incorrect. You could add additional documentation to clarify the difference between these two if needed

**Comment by andyprinceuk** [comment]
Within the context of several parameters that are _query_ parameters, along with using formatting indicative of URL parameters:
`ServiceAreas=<Common | Exchange | SharePoint | Skype>
TenantName=<tenant_name>
NoIPv6=<true | false>
Instance=<Worldwide | China | Germany | USGovDoD | USGovGCCHigh>`
It is, in my opinion, not a stretch to interpret the _Instance_ parameter as a _query_ parameter as it is written as one would expect for a query parameter: `Foo=Bar`. Not differentiating between the path and query parameters in this documentation is the cause of this confusion.

**Comment by yogkumgit** [comment]
@pandrew1 Please guide.

**Comment by LauraWi** [comment]
Will monitor for additional customer confusion on this point and possible updates.
