### ISSUE TITLE
Required roles to view service health?

### ISSUE THREAD

**Issue by HoCGeek** [MicrosoftDocs/microsoft-365-docs#4579]
This article says that "People who are assigned the global admin or service administrator role can view service health", but there is no "service administrator" role.  Is this referring to the Service Support Administrator role?

This article also links to the page "About admin roles" (https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?preserve-view=true&view=o365-worldwide#commonly-used-microsoft-365-admin-center-roles) that lists "Commonly used Microsoft 365 admin center roles".  Unfortunately that document lists "monitor service health" as an activity (presumably through the service health page?), but only for the Billing admin, Helpdesk admin, Office Apps admin, and User admin roles, and NOT the "Service support admin" role.

Please clarify whether or not the "Service Support Administrator" role provides access to the service health page and update the documents appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d8b9c3-7ff2-d3b7-a0ce-0310171c71d5
* Version Independent ID: 7b45c0a3-94ca-b749-50e4-7d4cbf204764
* Content: [How to check Microsoft 365 service health - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-service-health?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-service-health.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@HoCGeek Thank you for your feedback. I can confirm that the service support admin role does have the ability to view and monitor service health. We have made changes on both the documents to reflect the same. This can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4631 and PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4630 


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @HoCGeek Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
