### ISSUE TITLE
Incorrect cmdlet in PowerShell example.

### ISSUE THREAD

**Issue by AveryBaker** [MicrosoftDocs/microsoft-365-docs#4581]
In the PowerShell example this cmdlet is used to change the site sensitivity label.

**$sites | ForEach-Object {Set-SPOTenant $_.url -SensitivityLabel $Id}**

Set-SPOSite needs to be used so the example should read:

**$sites | ForEach-Object {Set-SPOSite $_.url -SensitivityLabel $Id}**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @AveryBaker  Have you tried the command as documented and it didn't work, or are you going by the PowerShell documentation that I'm told needs updating?

**Comment by cabailey** [comment]
@AveryBaker Haven't heard back from you but please see the response by the PM owner for https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4611.  If the command as documented isn't working for you, I recommend you file a support ticket for investigation and you're welcome to reference this thread for the support engineer to contact me.
