### ISSUE TITLE
Max character lengh for domain name

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/microsoft-365-docs#4583]
Upon signing up for a new tenant, the lengh of the *.onmicrosoft.domain seems to be 43 characters at max. (the "*" portion can contain up to 27 characters)

![image](https://user-images.githubusercontent.com/49895263/113242711-98e4ca00-92ec-11eb-8f71-745b69d8eb34.png)

However, this content says domain can be 48 characters long.
Please confirm and edit the content as needed.

![image](https://user-images.githubusercontent.com/49895263/113242879-e3fedd00-92ec-11eb-8fd1-8adebd0387d5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18000a40-502c-a43b-5a4e-0e23813a0494
* Version Independent ID: e259a7ab-f890-a939-f4af-3b71af8b956e
* Content: [What is a domain? - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/what-is-a-domain?redirectSourcePath=%252farticle%252fc33d1ba6-077c-4cea-be04-cfffbe3f3ed8&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/what-is-a-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/what-is-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@UKayo Thank you for your feedback. The Custom domain name will need to be at least 4 and a maximum of 48 characters. The limit for an onmicrosoft.com domain is 27 but a custom domain can have 48 characters,

![image](https://user-images.githubusercontent.com/45987684/113821640-ff109780-9799-11eb-84e6-531bf54def85.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @UKayo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
