### ISSUE TITLE
Adding payment method with th

### ISSUE THREAD

**Issue by saado9** [MicrosoftDocs/microsoft-365-docs#4587]
Hi , I was paying for my Microsoft Power BI Pro subscription through my credit card and the county was Saudi arabia.
Now I need to add my new credit card from the same bank, but I am getting the country as Jordan and cant be changed.
I know its is linked to the tenant country, but how i was able to add my visa card in SAudi arabia the first time!!
My subscription is due to renew in 8/4/2021. 

[Enter feedback here]

![image](https://user-images.githubusercontent.com/81733980/113247060-e2202400-92c2-11eb-9c1e-0fe24d95bc8f.png)
![image](https://user-images.githubusercontent.com/81733980/113249386-4218c980-92c7-11eb-9c8d-d1eb3d03af3c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14e33d-0d3e-45f4-fefe-dec3ae7d351f
* Version Independent ID: aeb53e2c-d35c-73fe-26f2-4f101bfeeea7
* Content: [Manage payment methods](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-payment-methods?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-payment-methods.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-payment-methods.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@saado9 I spoke with the product team, and there haven't been any changes to how credit cards are processed. Your best option is to contact support through the admin center and open a support ticket to have this investigated.
