### ISSUE TITLE
What is the upper limit of this mailbox?

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/microsoft-365-docs#4588]
The article implies that there is an expansion of the mailbox the is unlimited, but is there a upper limit of 140GB?

Please be more specific on what the client can expect when they enable this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69e08cf1-3ef1-7d22-122e-ef0f45c26215
* Version Independent ID: e9677dc3-580d-0a66-80ac-30a8aabdd45f
* Content: [Overview of unlimited archiving - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/unlimited-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Jmartinez589 Thanks for feedback. Auto-expanding archiving will continue to provision additional archive storage space as necessary. If your customers get to a point where additional archive storage is no longer provisioned, then they should contact Microsoft Support. Another important aspect of auto-expanding archiving is that customers adhere to proper use of archive mailboxes as described in the important note in this topic:

**Important:** Auto-expanding archive is only supported for mailboxes used for individual users (or shared mailboxes) with a growth rate that doesn't exceed 1 GB per day. A user's archive mailbox is intended for just that user. Using journaling, transport rules, or auto-forwarding rules to copy messages to an archive mailbox is not permitted. Microsoft reserves the right to deny unlimited archiving in instances where a user's archive mailbox is used to store archive data for other users or in other cases of the inappropriate use.
