### ISSUE TITLE
no FAQ section

### ISSUE THREAD

**Issue by gnerd** [MicrosoftDocs/microsoft-365-docs#4590]
See the FAQ section for tips on putting Microsoft 365 Groups and Microsoft Teams on hold.

There isnt an FAQ section...and I would like to know about this topic..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115cfe0b-c8b5-193d-19da-a6f9c03fdfc0
* Version Independent ID: 4a90cb9e-ce2a-a3f6-4b67-32f45c975323
* Content: [Manage holds in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/managing-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/managing-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/managing-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@gnerd Thanks for the heads up. Will remove reference to FAQ (which doesn't exist). Here are a few articles that discussing placing sites and team on hold. The basics will be applicable to hold in Advanced eDiscovery.

https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds

https://docs.microsoft.com/en-us/microsoftteams/legal-hold
