### ISSUE TITLE
Better explanation about correlation with embedded security reporting option on Outlook Web vs Report Add-In

### ISSUE THREAD

**Issue by dneto-ame** [MicrosoftDocs/microsoft-365-docs#4593]
Hi there,

I hope you can improve documentation on how this add-in can be confusing for end-user, since Outlook Web already has the standard option to mark as Junk or Phishing.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-and-phishing-scams-in-outlook-on-the-web-eop?view=o365-worldwide

We should able to remove the standard option in favor of Add-In because seems to be more complete from a security perspective and reporting to Microsoft admin. Keep both sometimes confuses user experience and internal document generation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by chrisda** [comment]
@dneto-ame, I agree that this is confusing. The Report Message add-in or the Report Phishing add-in are definitely the preferred way to go.

In looking at the ReportJunkEmailEnabled parameter in the [Set-OwaMailboxPolicy](https://docs.microsoft.com/powershell/module/exchange/set-owamailboxpolicy) cmdlet, the parameter is described correctly, but does nothing to help remove/hide the built-in reporting option.

I suggest that you open a support case about this. I'm not sure that we can do anything from a documentation perspective to help.

**Comment by siosulli** [comment]
@dneto-ame I have checked and I will update the documentation so it is similar to the iOS and Android article where the Report Message add-in and the Report Phishing add-ins are recommended.

As @Chrisda said though, in terms of being able to remove the standard option you could open a support case for this.

**Comment by siosulli** [comment]
Hi @dneto-ame to address your first point, I have the updated the article to be in-line with the iOS and Android article and to recommend the use of the Report Message and the Report Phishing add-ins over the other options. 

For the second point to remove the standard option in favor of Add-In, this would need to be dealt with in a support ticket.

Thank you for your feedback on this!
