### ISSUE TITLE
Do we need Azure AD Premium license for Global Admin or not???

### ISSUE THREAD

**Issue by NiteshSharma2K19** [MicrosoftDocs/microsoft-365-docs#4597]
Hi Team,

Thanks for the article. I have a feedback and a request. The wording in this document is little confusing to me. 
![image](https://user-images.githubusercontent.com/49910457/113339817-072f8980-92f9-11eb-8c70-fc3e361e2c7a.png)

I understand that the steps in the article if performed will not affect my Global Admin Account. Irrespective of the license assigned, but the later under license requirements

![image](https://user-images.githubusercontent.com/49910457/113339952-3e059f80-92f9-11eb-9429-e4982621ab94.png)

it says that the admin who configures these group creation setting requires license. So if the steps in the article doesn't affect my Global Admin, why do I need the license? Can you please make the language little simpler so we can understand it easily.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by NiteshSharma2K19** [comment]
Hello Team,
Is there any update on this request?

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please help us in resolving this issue. Thanks

**Comment by MikePlumleyMSFT** [comment]
@ArunMSFT can you confirm the license requirements?

**Comment by Jordanndahl** [comment]
@ArunMSFT @MikePlumleyMSFT

**Comment by ArunMSFT** [comment]
Confirmed with Jordan that the admin doesn't need to have the license.

**Comment by yogkumgit** [comment]
@ArunMSFT Thank you very much for sharing this explanation. @NiteshSharma2K19 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by NiteshSharma2K19** [comment]
Hi @yogkumgit 

Thanks for the information and confirmation. Can you please update that in the document? This will help others as well. 

Regards
