### ISSUE TITLE
Green safety tips inside message body can be fake

### ISSUE THREAD

**Issue by alphanimal** [MicrosoftDocs/microsoft-365-docs#4599]
> Safety tips in Outlook do not depend on what version of Outlook you're using because the safety tip is cracked open and inserted directly into the message body.

How do I know a malicios sender did not just add their own green "This message is from a trusted sender." box into their fake message? If the message would be displayed in the email client GUI independent of the message body, it would be more trustworthy and not lead users to believe things that could easily be faked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1daade0-c937-6daf-cdc5-e6e23214426d
* Version Independent ID: 49836613-b9a3-fc37-ffc8-3589dda16d45
* Content: [Safety tips in email messages - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safety-tips-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safety-tips-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safety-tips-in-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@alphanimal, you could very well be correct. However, this is the place for documentation updates, not feature requests. If you want to get serious traction on this issue, I would recommend opening up a support case.

**Comment by yogkumgit** [comment]
@alphanimal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
