### ISSUE TITLE
Clarify Block ActiveSync Policy

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/microsoft-365-docs#460]
Why would you not just define the policy like: User &gt; Accessing EXO &gt; Using ActiveSync &gt; BLOCK

Why use 'Require Approved App' as the control? Also, isn't 'Require Approved App' only supported for iOS and Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18267b13-4890-4196-16e8-e183ece73d70
* Version Independent ID: 64887e62-4187-cb6e-fbb3-ff7e12a18841
* Content: [Secure email recommended policies - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/secure-email-recommended-policies)
* Content Source: [microsoft-365/enterprise/secure-email-recommended-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/secure-email-recommended-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@toddjohnson39 - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by adamfowlerit** [comment]
Also note that if you follow this guide to the letter, you get the error 'MAM policy should be applied to Android or IOS client platforms.' and can't create it.

**Comment by msbemba** [comment]
@toddjohnson39 Thank you for your feedback. With Azure Active Directory (Azure AD) Conditional Access, you can restrict access to your cloud apps to approved client apps that can protect your corporate data. In the require approved app, outlook on the phone will work but not any third party apps.

Below URL gives more information about required approved app and conditional access
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/app-based-conditional-access

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@toddjohnson39  Thank you for your feedback. With Azure Active Directory (Azure AD) Conditional Access, you can restrict access to your cloud apps to approved client apps that can protect your corporate data. in this document after configuring require approved app, outlook on the phone will work but not any third-party apps.

Below URL gives more information about required approved app and conditional access
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/app-based-conditional-access

Hope this helps!
Thanks
Sri

**Comment by BrendaCarter** [comment]
Hi @toddjohnson39, I reached out to a couple of our PMs and here's what I learned:

"This grant control delivers a specific quarantine message, basically install Outlook mobile. Other grant controls deliver different messages."

"The policy is two-fold: 1. Only allow Outlook Mobile, 2. Block ActiveSync."

Does this make sense?

**Comment by mypil** [comment]
@toddjohnson39 - From our understanding, the issue has been answered by BrendaCarter & msbemba. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.
