### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by v-jaskee** [MicrosoftDocs/microsoft-365-docs#4600]
The current Docs article provides for a NOTE at the top re: latency.  Then further below an additional NOTE re: once a day and/or reboot.  Overall this seems a bit confusing, as the first seems to relate to usage in the Portal, while the other relates to the endpoint "registering" itself.

Certainly if the below needs to go towards support or an Insight let me know....happy to reroute.

Also, in my testing; I am noticing that even a reboot does not set a newly created tag (when configured via manual RegEdit or from within the M365 Security/Device Inventory portal).

Do we happen to know if this is the expected behavior (24hrs or reboot)?  Or does a Device Inventory happen; 
- only once per day, regardless?
- take <enter elapse mins/hrs> in order to then report in again, post reboot?
- can this Device Inventory be forced elsewhere?  I attempted to Start several default Device related Scheduled Tasks (devicecensus.exe), but that did not work.  Assuming then, Device Inventory is triggered with MsSense....which would require a reboot??

My test client has been rebooted twice since adding tags, however 'Last device update' is still two hours old - from when the VM was first powered up/logged on. Perhaps an issue with my test VM, which I will look to test with another VM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c29286-b601-4dad-0e65-227c8d045ee4
* Version Independent ID: 2af4acf9-4089-5dff-d628-16b8425e0a57
* Content: [Create and manage device tags](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-tags?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine-tags.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine-tags.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Please contact support.
