### ISSUE TITLE
Teams installation problem

### ISSUE THREAD

**Issue by aldo-ipo** [MicrosoftDocs/microsoft-365-docs#4603]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a020c1-2f9f-26e7-5221-25b802bbc570
* Version Independent ID: 199e13d2-1b21-0b57-325f-91121b8f104d
* Content: [Support information for Malaysia - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/malaysia?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/support/malaysia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/malaysia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@aldo-ipo If you're having trouble installing Teams, please see [Troubleshoot Microsoft Teams installation and update issues on Windows](https://docs.microsoft.com/microsoftteams/troubleshoot-installation). If you continue to have problems, please contact a support agent  using [Support information for Malaysia](https://docs.microsoft.com/en-us/microsoft-365/admin/support/malaysia)
