### ISSUE TITLE
Teams problem

### ISSUE THREAD

**Issue by aldo-ipo** [MicrosoftDocs/microsoft-365-docs#4604]
Purchased Office package yesterday. Installed on the computer. Teams cannot launch. First ask account, then phone number, after send a verification code. Code inserted correctly. Error several times. Now cannot even today try again because of too many codes inserted yesterday. Asked to microsoft helpdesk to solve the issue, they forward me to Teams-Skype support, that forward me to Malaysia support. Both the two support working and communicating. When tried to connect to malaysia support, i saw no chat online, so i called the phone number that after many steps just told me to refer to the online support. It must be a kind of joke related to 1st of April. Please start to work and help me to finalize this issue.

**Comment by yogkumgit** [comment]
@aldo-ipo Sorry for the inconvenience. The issues section of this repository is intended for product documentation problems, not support. If you have any feedback with respect to a document, please mention the document name here and let us know what improvements you expect. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also for document update purpose.
