### ISSUE TITLE
Microsoft Defender for Endpoint for Mac is included in Windows E5 / MDE stand-alone

### ISSUE THREAD

**Issue by AaronDinnage** [MicrosoftDocs/microsoft-365-docs#4605]
As per this conversation on Yammer (https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiOTAxMTU2ODYwMDU5NjQ4In0) the product marketing manager has confirmed the current description of Microsoft Defender for Endpoint Mac licensing on this page is incorrect and the licensing list should also include Windows E5 and Microsofty Defender for Endpoint stand-alone license types.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e9b530-4f11-0483-ed65-42b23082f9f6
* Version Independent ID: 38263c08-7cab-7d52-552d-e724ede401aa
* Content: [Microsoft Defender for Endpoint for Mac](https://docs.microsoft.com/en-au/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac?view=o365-worldwide#licensing-requirements)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@AaronDinnage Thank you for your feedback. We have made the changes in document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4629

thanks
Sri
