### ISSUE TITLE
Endpoints of Microsoft Whiteboard should be added to the Office 365 URLs and IP address ranges

### ISSUE THREAD

**Issue by mitanabe** [MicrosoftDocs/microsoft-365-docs#4606]
The following endpoints should be added to the Office 365 URLs and IP address ranges for Microsoft Whiteboard.

whiteboard.microsoft.com 
wbd.ms
*.whiteboard.microsoft.com
whiteboard.ms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by mitanabe** [comment]
@yogkumgit Thank you for your triage.

**Comment by mitanabe** [comment]
@kelleyvice-msft Could you let us know the current status?

**Comment by LauraWi** [comment]
Hi  -- This topic is autogenerated from an internal tool used to maintain endpoint data. It cannot be manually edited. I will follow up to see if this is a gap.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I have informed the appropriate engineering team of this issue and requested that they go through the process of adding their endpoints to the web service. Once they complete this process, the endpoints should be included in future updates. -Kelley

**Comment by loaderladdy-work** [comment]
by way of explanation, currently MS WB URLs augloop.office.com and *.whiteboard.microsoft.com are only covered by the "Default" O365 IP Address and URL category and this means corporates following MS guidance send the traffic to proxy appliances.  Proxy appliances that are typically doing SSL Break and Inspect to keep out malware and DLP.  SSL Break and Inspect breaks WebSockets.  At least having this info published and kept up to date somewhere like the O365 IP Addresses and URLs Web Service gives corp IT depts a fighting chance to keep services running in a secure way.  here is an example from Edge Dev Tools where web sockets are blocked in WhiteBoard app.

![image](https://user-images.githubusercontent.com/107871665/222733920-fe5ec719-086d-404d-8bac-f1dbfed358b2.png)

**Comment by loaderladdy-work** [comment]
could this issue be reopened until either an explanation of why this cannot happen is provided, or WhiteBoard is moved in to the web service please @kelleyvice-msft ?

**Comment by LauraWi** [comment]
Tagging @pandrew1 for comment. The writing team does not have visibility into status of service onboarding to the endpoint process.
