### ISSUE TITLE
Conditional Access

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/microsoft-365-docs#461]
This article should be updated based on Conditional Access added to Microsoft 365 Business Suite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed7e43-7ec8-01f6-8cf0-6fd77519840e
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business Frequently Asked Questions ](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@Kazzan - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@Kazzan Thank you for your feedback. We have added information about conditional access added to o365 Business suite via PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/465

Thanks
Sri

**Comment by mypil** [comment]
@Kazzan - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
