### ISSUE TITLE
What features are part of Targeted release

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4614]
Please provide more information about which compliance features are part of the targeted release process. We need to be able to tell out people in that ring what to expect so that we can properly evaluate the new functionality.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89486ebd-f4fa-9d07-ee93-d04fd8d41027
* Version Independent ID: 667019d9-aac6-f466-1605-651a800fc212
* Content: [What's new in Microsoft 365 compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @brendonb
* Microsoft Alias: **brendonb**

**Comment by yogkumgit** [comment]
@brendonb Please help us in resolving this issue. Thanks.

**Comment by yogkumgit** [comment]
@v-tophillips Please comment and resolve this issue. Thanks

**Comment by yogkumgit** [comment]
@DeanGross Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
