### ISSUE TITLE
Need to add limit of 1500 calls per hour

### ISSUE THREAD

**Issue by mjmelone** [MicrosoftDocs/microsoft-365-docs#4616]
Need to also note that there is a limit of 1500 API calls per hour
`
{
  "error": {
    "code": "429",
    "message": "API calls quota exceeded! maximum allowed 45 per 00:01:00",
    "target": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  }
}
{
  "error": {
    "code": "429",
    "message": "API calls quota exceeded! maximum allowed 1500 per 01:00:00",
    "target": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  }
}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53a61a50-f7f2-f09a-a008-759c3afba97b
* Version Independent ID: 872c0e23-c626-3e22-efea-d4ef4ad7f32b
* Content: [Advanced Hunting API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-api?view=o365-worldwide#limitations)
* Content Source: [microsoft-365/security/defender-endpoint/run-advanced-query-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-advanced-query-api.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@mjmelone Thank you for your feedback. 
We have the document updated to reflect the same

The number of executions is limited per tenant:
   - API calls: Up to 45 calls per minute, up to 1500 calls per hour.
   - Execution time: 10 minutes of running time every hour and 3 hours of running time a day.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mjmelone Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
