### ISSUE TITLE
Incorrectly iterated bullets

### ISSUE THREAD

**Issue by coproyer** [MicrosoftDocs/microsoft-365-docs#4618]
Within the section 'Use the Security & Compliance Center to configure the user submissions mailbox' (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide#use-the-security--compliance-center-to-configure-the-user-submissions-mailbox) for the second level bullets of the section, both the first and second bullets are "a".

![User submissions policy - Office 365 _ Microsoft Docs](https://user-images.githubusercontent.com/56403740/113741911-f1ceac80-96b6-11eb-8d6d-f05dee86b49b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User submissions policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@coproyer Thank you for your feedback. We have created a PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4621 to fix this.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @coproyer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
