### ISSUE TITLE
I need how to use API of threat-explorer (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer)

### ISSUE THREAD

**Issue by d3sysint** [MicrosoftDocs/microsoft-365-docs#4625]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and Real-time detections - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@d3sysint Thank you for your feedback. We have another document that talks about access Microsoft 365 Defender APIs -https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-access?view=o365-worldwide and https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-overview?view=o365-worldwide

You have multiple options to use the APIs, Like APplication context, User context, and partner context. based on your requirement you could follow the steps.

I you have trouble using these APIs then you could contact support via the need help option on the admin center to help you out..
Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @d3sysint Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
