### ISSUE TITLE
Which users are shown in the report

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/microsoft-365-docs#4632]
I would like to know which users are going to be shown in the table view of the user activity report and exported data. Will it show only users that were using the service in any way, all users licensed with Teams license or all users present in given tenant?

We are looking for a way to find inactive users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e8bbc80-90d7-5bb5-520d-87db92c10c16
* Version Independent ID: b69c7d34-18ed-b3a3-fc4e-7ed2ab86d5c5
* Content: [Microsoft 365 Reports in the admin center - Microsoft Teams user activity - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft-teams-user-activity-preview?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/microsoft-teams-user-activity-preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft-teams-user-activity-preview.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Larryngolog Thank you for your feedback. The user activity reports will show details of all users in the tenant. The report does have columns such as "Is licensed" and "Last activity date" for you to sort it and find out the inactive users.

Hope this helps!

Thanks
Sri

**Comment by Larryngolog** [comment]
Thanks a lot! This clarifies my question.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Larryngolog Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
