### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rfoust** [MicrosoftDocs/microsoft-365-docs#4636]
I believe the license requirement listed is not correct? From my understanding, A1 licenses (which include Exchange Plan 1) support litigation hold, based on what is documented at this link:

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education

Just search for "In-Place Hold and Litigation Hold" on that page. The differences between these two pages are causing confusion here. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff3e4302-c038-67aa-eb29-8b01c7fc4ed6
* Version Independent ID: 680317f5-19be-7268-5b40-f181ea3485da
* Content: [Create a Litigation Hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-litigation-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-litigation-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-litigation-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rfoust Thanks for feedback. I've added note about lithold support in Office 365 EDU A1 subscriptions, and added link to the service description.
