### ISSUE TITLE
Suggest to provide guidance specific to Live Events

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/microsoft-365-docs#4637]
Suggest to include networking guidance for Live Events, potentially sourcing some of that content from the following blog post:

https://techcommunity.microsoft.com/t5/office-365-blog/how-to-optimize-stream-amp-live-events-traffic-in-a-vpn-scenario/ba-p/1439767

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4fd73b-9632-b0c1-45cb-825f2f1a03dd
* Version Independent ID: 8aeca19b-cf40-33c1-b947-f951a58e9520
* Content: [Microsoft 365 network connectivity principles - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-network-connectivity-principles?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-network-connectivity-principles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-network-connectivity-principles.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by LauraWi** [comment]
cc'ing @pandrew1 for consideration.

**Comment by pandrew1** [comment]
@LauraWi I believe this is published here: https://docs.microsoft.com/en-us/stream/network-overview#general-microsoft-stream-endpoints

**Comment by yogkumgit** [comment]
@davidjfriedman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
