### ISSUE TITLE
Please add more detail to this page for Premier Support.  What are the steps a Premier/Unified Customer must take to log a case.  This page is very vague. 

### ISSUE THREAD

**Issue by kyouells** [MicrosoftDocs/microsoft-365-docs#4639]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceca7593-5fc2-7088-d2c3-90bacbbbed9a
* Version Independent ID: 7af76ee9-424d-1809-c8b9-d074c95f9b2f
* Content: [Contact Microsoft Defender ATP support](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/contact-support?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/contact-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/contact-support.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@kyouells Thank you for your feedback. The steps to open ticket for premier/unified/advanced/Concierge support all remains the same. Clicking on the need help? the section lets customers/admins open a support ticket with Microsoft and the ticket gets routed to the correct Microsoft team depending on the support contract.

Hope this helps!

Thanks
Sri

**Comment by kyouells** [comment]
I get the steps to create the case is the same, but the tenant must be matched with Premier in order to even get into Premier.  That is what is not clear, so can we note that if you are a Premier/Unified Support Customer you must see the "Premier" or "Unified Support" badge at the top.  If you do not, reach out to your Customer Success Account Manager.


Kelly Youells | Sr. Customer Success Account Manager
701-492-6318 (o) | 701-238-7413 (m) | ***@***.******@***.***>
[MSFT_logo]<https://www.microsoft.com/>

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@kyouells I have added a note on the ticket about the badges showing up on the widget. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4704. Once the author approves this you will see the changes on the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kyouells Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
