### ISSUE TITLE
Microsoft Highly Confidential PDF Download?

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/microsoft-365-docs#4641]
Hi,

maybe the security of the document is no longer "Microsoft Strictly Confidential" or someone shared a document that should not be publicly available.
The article has a link to Validation Instructions for Data-at-rest Encryption for Microsoft 365 which points to https://aka.ms/CustomerKey/PublicPreviewValidation
This ends in a PDF file download which is classified as "Classified as Microsoft Highly Confidential"
Can you check this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18803bfa-118a-09ee-947b-abf1ee996b7a
* Version Independent ID: 87179b6d-d917-1aa9-259a-6f2de072c049
* Content: [Customer Key for Microsoft 365 at the tenant level (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-tenant-level?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-tenant-level.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-tenant-level.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@myfope Thank you for your feedback. We are checking this internally with the author and will provide an update shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@myfope Thank you for the feedback. We have removed the Classification on the file in the backend. The PDF does not contain the header now.

@yogkumgit The issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @myfope Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
