### ISSUE TITLE
A little fix is needed

### ISSUE THREAD

**Issue by uzef1x** [MicrosoftDocs/microsoft-365-docs#4643]
[Enter feedback here]

The menu link is correct but the link name is wrong:

![image](https://user-images.githubusercontent.com/75022360/114021101-fa6ee080-9878-11eb-8040-7da4af218a68.png)

Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01048d4-36ad-9241-10c7-dcab6dcc2d52
* Version Independent ID: c38e975b-296a-3af3-02df-48db5d983f1b
* Content: [Manage partner relationships](https://docs.microsoft.com/en-us/microsoft-365/commerce/manage-partners?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/manage-partners.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/manage-partners.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@uzef1x Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4679
