### ISSUE TITLE
Invalid link 404 for DeviceEvents

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/microsoft-365-docs#4644]
DeviceEvent link in schema fails 404 

Invalid link 404 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-deviceevents-table.md?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9fd21fa-e367-78d4-bc86-80f2b75a64b8
* Version Independent ID: 97a42f10-ba7f-f2d4-6c5c-69e38a99f277
* Content: [DeviceAlertEvents table in the advanced hunting schema](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@bledMS82 Thank you for your feedback. The link in the document for the device event does work. Could you please clarify which page has this broken link?

Thanks
Sri

**Comment by bledMS82** [comment]
This looks to be corrected as it was the link shown here .
***@***.***D72FB0.74808BD0]


TJ Bledsoe
Cyber Security Technical Advisor | Azure Security
Customer Service & Support | Microsoft Corporation
* TJ.Bledsoe@Microsoft.com<mailto:TJ.Bledsoe@Microsoft.com>

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bledMS82 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
