### ISSUE TITLE
Missing 'Learn the advanced hunting query language page'

### ISSUE THREAD

**Issue by KitSkin** [MicrosoftDocs/microsoft-365-docs#4645]
At the bottom of the page is the link to the [Learn the advanced hunting query language page](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-query-language); this is also the same link and address on the left menu.  However, if you go to that [link](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-query-language) today, you get a **404 - Page not found** error.

Here is a cached copy of the page:
[Learn the advanced hunting query language page (cached)](https://cc.bingj.com/cache.aspx?q=https%3a%2f%2fdocs.microsoft.com%2fen-us%2fmicrosoft-365%2fsecurity%2fdefender-endpoint%2fadvanced-hunting-query-language.md%3fview%3do365-worldwide&d=5065450263818577&mkt=en-US&setlang=en-US&w=rioBIvJN8YX_gGTvMJB5bzwjunRhFHa-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2bcd1e2-1c90-7d98-e930-e59a5425fbfa
* Version Independent ID: bd223ebe-79e8-bab6-fae7-9a2fec2872dd
* Content: [Overview of advanced hunting in Microsoft Defender ATP](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/advanced-hunting-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/advanced-hunting-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
I had a redirections and TOC edit PR yesterday that did not push through because of GH issues. But now it's up and this issue and hopefully others of a similar nature is resolved.
