### ISSUE TITLE
Poorly worded Docs site for Advanced Audit functionality 

### ISSUE THREAD

**Issue by KeithP-Microsoft** [MicrosoftDocs/microsoft-365-docs#4648]
[ This document is out-of-date. It references February 2021 like it's a date in the future, when in reality, it's from nearly 2 months in the past. Also, the term who's (which means who is) should really be "whose" (wrong version of 2 words that are similar but not the same meaning. All of this occurs in the bottom section of the page labelled as "FAQs for Advanced Audit". ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027a1632-76a4-9e87-8376-c10ddfc3e116
* Version Independent ID: 10c72509-5d4a-25d3-caf8-361474f68cd8
* Content: [Advanced Audit in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/advanced-audit.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/advanced-audit.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@KeithP-Microsoft Thanks for feedback. We have updated the FAQ and retained the bit about preserving 10-yr retention policies that were created before the add-on license was made available.
