### ISSUE TITLE
What value can be used to enable "warn mode" using group policy?

### ISSUE THREAD

**Issue by cygnetix** [MicrosoftDocs/microsoft-365-docs#4653]
This page shows how to configure ARS using a GPO with the following rule values:
Disable = 0
Block (enable ASR rule) = 1
Audit = 2

But this doesn't include how to enable "warn mode" as per: https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/attack-surface-reduction-rules-warn-mode-with-mem-m365-defender/ba-p/2211653

Am I correct in thinking this would be `Rule = 3`? If so, can the doco please be updated to cover this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by cygnetix** [comment]
Actually, from a bit of trial and error, I believe the Id for WarnMode is `6` and the parameter to pass via PowerShell is `Warn` (rather than WarnMode like I'd originally assumed).

It'd be good to have this added in the doco to clear up any confusion.

**Comment by msbemba** [comment]
@cygnetix Thank you for your feedback. 
The values to enable (Block), disable, warn, or enable in audit mode are added in the document. You are correct the parameter is not warn mode, Just warn.

0 : Disable (Disable the ASR rule)
1 : Block (Enable the ASR rule)
2 : Audit (Evaluate how the ASR rule would impact your organization if enabled)
6 : Warn (Enable the ASR rule but allow the end-user to bypass the block)

Hope this helps!

@yogkumgit There are no additional changes in the document and the  issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cygnetix Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
