### ISSUE TITLE
SPO DLP support for file extensions points to SPS list minus and plus some formats

### ISSUE THREAD

**Issue by Esaggese** [MicrosoftDocs/microsoft-365-docs#4657]
The SPO documentation should be self-contained wherever possible. Currently, on the topic of file formats supported by SPO DLP, the documentation says "DLP evaluates any content that can be indexed." and then points to the SharePoint *server* documentation, which in turns says "SPO is the same, plus these formats and minus these formats". Since SPO is Microsoft's primary platform, this is not how this topic should be documented (especially since it is easy to miss the nuance that the page linked by the SPO article is not for SPO but for SPS, and that there's a notice there that says "but SPO is different from the list below", this can lead to people looking at the list and thinking it is the applicable list (in fact I just did a quick survey and all three people I asked incorrectly interpreted the list as being for SPO). 
The list of supported file extensions should be in a page that's specific to SPO, and should be up to date with the formats supported by SPO.

**Comment by msbemba** [comment]
@Esaggese Thank you for your feedback. Could you please point us to the document which you think needs to be updated?

Thanks
Sri

**Comment by Esaggese** [comment]
Hi. The information should be included in https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide#how-it-works, or in a separate page linked from there. Currently that page has a link to a page that lists the formats supported in SPS, not SPO, and adds some clarification about the differences in SPO. Also, the linked article is named "default file extensions..." which sets  the expectation that the list can be changed, which is not the case for SPO. The article I link to should instead either include the list for SPO explicitly, or point to a page that details the list for SPO and not the one for SPS.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Esaggese Thank you for your feedback. SharePoint in Microsoft 365 supports the same file name extensions as in the table, except for .eml or .mht files. In addition, SharePoint in Microsoft 365 also supports the following: .xlt .xlc .xlb. This has been added as a note on the document.

Hope this helps!

Thanks
Sri

**Comment by Esaggese** [comment]
I know it's documented, but SharePoint Online is Microsoft's primary platform, and SharePoint Server is a legacy platform. Microsoft should not document SharePoint Online by making references to the SPO documentation and highlighting the differences, SPO should be documented directly since otherwise it puts an extra burden on SPO administrators and it potentially causes confusion when this document is linked directly from the SPO documentation on other topics and admins may not realize they are in the page for SPS and not even check the notes.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Esaggese The document states that it applies to 2013, 2016, 2019, and SharePoint in Microsoft 365 and there is no alternate document currently available for just SPO.

CC: @chrfox 

@yogkumgit 

Thanks
Sri
