### ISSUE TITLE
Please add instructions for generating the QR code

### ISSUE THREAD

**Issue by rbreneman** [MicrosoftDocs/microsoft-365-docs#4658]
Please add instructions for existing users to generate the QR code. For example if I've had an active mailbox for 2 years but get a new phone, I'd like to know how to generate a QR code from Outlook (desktop) or OWA and use that code to setup Outlook on a brand new iOS device.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 749a8389-eda6-3059-b713-5d0b3755fe9c
* Version Independent ID: 53000b70-b561-ec33-0b94-f0c26650548b
* Content: [Use a QR code to sign-in to the Outlook mobile apps - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/use-qr-code-download-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/use-qr-code-download-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/use-qr-code-download-outlook.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@rbreneman Thank you for your feedback. This feature is not on public preview yet, If your organization has turned on Targeted release, users will see notifications informing them that they can use outlook on mobile( This shows up even if they have another device configured). Like mentioned in the document " If users choose to send themselves an SMS text message to download the app on their mobile device, a QR code will appear on their computer. They will be able to scan the QR code to log into Outlook on their phone or tablet." this is all instructions user needs to be able to scan the QR code to log into Outlook on their phone or tablet.

The notification comes up for all users on the tenant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rbreneman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
