### ISSUE TITLE
RSS feed or email subscription for page changes

### ISSUE THREAD

**Issue by jgc4q** [MicrosoftDocs/microsoft-365-docs#4660]
The "What's new in Microsoft Defender for Endpoint for Mac" page has useful information that is fast changing.  I would like an RSS feed or a way to subscribe to email alerts when the page changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00948177-b26b-c26c-8ff3-7ad66f388623
* Version Independent ID: f370db23-e9ec-93c1-9ce2-957e111dcfce
* Content: [What's new in Microsoft Defender for Endpoint for Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-whatsnew?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/mac-whatsnew.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-whatsnew.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jgc4q Thank you for your feedback. I have checked and currently, we do not have an option to subscribe to email alerts or have RSS feeds. However, if you are signed in to the documents using your account, you will see an option to bookmark.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jgc4q Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
