### ISSUE TITLE
Azure Security Center/Defender for Servers and Arc

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#4661]
"Option 2: Onboard Windows servers through Azure Security Center" is not accurate if one is using Azure ARC.
Instead of "Microsoft Defender for Endpoint with Azure Security Center" one should follow the instructions in [Enabling the Microsoft Defender for Endpoint integration](https://docs.microsoft.com/en-us/azure/security-center/security-center-wdatp#enabling-the-microsoft-defender-for-endpoint-integration). Would be nice if the text below Option 2 makes note of that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@andrePKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4700

Thanks
Sri

**Comment by andrePKI** [comment]
Excellent, thank you!
