### ISSUE TITLE
Global Setting for Safe Links

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4662]
Please provide some additional discussion about why "tracks user clicks in supported Office 365 apps." is set to true for the Standard and Strict categories and what an organization is supposed to do with the generated data. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
@DeanGross, does the explanation of what the setting does over at  [Safe Links settings for Office 365 apps](https://docs.microsoft.com/microsoft-365/security/office-365-security/safe-links#safe-links-settings-for-office-365-apps).

Even though the setting is turned on by default, if you have no Safe Links policies, then the protection is not applied to anyone.

The setting only applies to links in supported Office documents. The equivalent setting for links in the body of email messages is described in [Safe Links settings for email messages](https://docs.microsoft.com/microsoft-365/security/office-365-security/safe-links#safe-links-settings-for-email-messages).

So, if you understand why to track URL clicks in email messages, the same logic applies for why to track URL clicks in Office documents.

**Comment by DeanGross** [comment]
yes that does help, but I am not seeing anything about where the clicks are reported or any guidance about what should be done with the data. Am I missing something?

**Comment by chrisda** [comment]
@DeanGross, probably the best place to see the results of Safe links is the [URL threat protection report](https://docs.microsoft.com/microsoft-365/security/office-365-security/view-reports-for-mdo#url-threat-protection-report).

**Comment by yogkumgit** [comment]
@chrisda Thank you very much for sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
