### ISSUE TITLE
ASR with defender in passive mode?

### ISSUE THREAD

**Issue by jp-costa** [MicrosoftDocs/microsoft-365-docs#4665]
Can ASR be used in audit mode, if Windows Defender is in passive mode? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad81808-0605-037f-364e-9d061d593078
* Version Independent ID: 62044527-8d7e-3dea-d872-83638fe7b14c
* Content: [Attack surface reduction frequently asked questions (FAQ)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @martyav
* Microsoft Alias: **v-maave**

**Comment by msbemba** [comment]
@jp-costa Thank you for your feedback. A specific requirement for enabling the ASR rule is that Microsoft defender must be active and cannot be in passive mode.

You can find more information about  Demystifying attack surface reduction rules here-https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/demystifying-attack-surface-reduction-rules-part-1/ba-p/1306420

Hope this helps!!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jp-costa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
