### ISSUE TITLE
confusing directions

### ISSUE THREAD

**Issue by bradw2k** [MicrosoftDocs/microsoft-365-docs#4667]
"Select the name of the user whose email you want to forward to open the properties page."

The placement of "to" in this sentence is very confusing! Should NOT select user "you want to forward to" ... instead should select the user whose email should be forwarded.

You might try:

"Select the name of the user whose email you want forwarded, then open the properties page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@bradw2k Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4701

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @bradw2k Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
