### ISSUE TITLE
Provide feature info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4668]
Please provide some information about which Defender for Endpoint features are actually available for MacOS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e9b530-4f11-0483-ed65-42b23082f9f6
* Version Independent ID: 38263c08-7cab-7d52-552d-e724ede401aa
* Content: [Microsoft Defender for Endpoint for Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help in resolving this issue. Thanks.

**Comment by mjcaparas** [comment]
At this point - out of scope.
