### ISSUE TITLE
X-MS-Exchange-Organization-BypassFocusedInbox uses the term bypass

### ISSUE THREAD

**Issue by TheMasterPrawn** [MicrosoftDocs/microsoft-365-docs#4670]
[Enter feedback here]

I don't understand in this doc that X-MS-Exchange-Organization-BypassFocusedInbox = true If I want to "Use the UI to create a transport rule to direct email messages to the Focused view for all your users" . By definition the value should be false if I did not want the mail to Bypass the Focused Inbox. In this instruction, all mail matching this rule should end up in other.

Can anyone clarify this please ?
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a29483-a070-ccc1-b064-176dfa49d5e9
* Version Independent ID: bad082c0-9ca2-0ade-6b1f-0ba5ac26017b
* Content: [Configure Focused Inbox for everyone in your organization - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/setup/configure-focused-inbox?redirectSourcePath=%252fen-us%252farticle%252fConfigure-Focused-Inbox-for-everyone-in-your-organization-613a845c-4b71-41de-b331-acdcf5b6625d&view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/configure-focused-inbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/configure-focused-inbox.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@TheMasterPrawn Thank you for your feedback. I understand the ambiguity here, but I have tested and can confirm that the X-MS-Exchange-Organization-BypassFocusedInbox should be set to true for it to bypass the Other folder and land in the focused inbox. 

Hope this helps!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @TheMasterPrawn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
