### ISSUE TITLE
Bad hyperlink in "Microsoft Defender Antivirus configuration requirement" section

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/microsoft-365-docs#4675]
In the "Microsoft Defender Antivirus configuration requirement" section, there is a hyperlink "Manage Microsoft Defender Antivirus updates and apply baselines." that points to https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/manage-updates-baselines-microsoft-defender-antivirus

Visiting this URL results in a 404 error. The hyperlink should be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by denisebmsft** [comment]
Hello @franklesniak and THANK YOU for letting us know about this. A fix is in and you'll see the updates live later this morning (at around 11 AM Pacific Time). In the meantime, here's the correct URL: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus?view=o365-worldwide
