### ISSUE TITLE
Can you update this page for Defender for Linux?

### ISSUE THREAD

**Issue by Field5555** [MicrosoftDocs/microsoft-365-docs#4676]
Page still claims Linux is "Unsupported". Can you add info for Defender for Linux here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1f5402-b627-d205-8e88-ca3fe609ef5f
* Version Independent ID: 0c91f8eb-368a-681a-209c-b03ff823945a
* Content: [Supported operating systems and platforms for threat and vulnerability management](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-supported-os?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/tvm-supported-os.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tvm-supported-os.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Related: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/8000

**Comment by msbemba** [comment]
@Field5555 Thank you for the feedback. Linux and mac are not currently supported by threat and vulnerability management.  We have added a note on the document that The supported systems and platforms for threat and vulnerability management may be different from the Minimum requirements for Microsoft Defender for Endpoint list.

Hope this helps!

@yogkumgit  There are no changes required in the document.
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Field5555 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
