### ISSUE TITLE
Make the "Other supported operating systems" section more specific, or add link to supplemental doc

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/microsoft-365-docs#4678]
In the "Other supported operating systems" section, the page vaguely references that Android, iOS, macOS, and Linux are supported, but is not specific about the versions/distributions that are supported. This information should be added - or a link to a supplemental page that contains this information should be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by franklesniak** [comment]
For example, this page lists the requirements for Linux: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide#system-requirements

**Comment by mjcaparas** [comment]
Thanks for the feedback. Will add links in.
