### ISSUE TITLE
Time Stamps

### ISSUE THREAD

**Issue by john-louden** [MicrosoftDocs/microsoft-365-docs#468]
Hi,

Would be good if the document (the portal would be better) could detail if the timestamps shown in explorer are UTC or Local Time. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and real-time detections, new to Threat Explorer, changes to Threat Explorer, new to Office 365, Security, Cloud Security, new to Security in ATP, new ATP features](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/threat-explorer#feedback)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by mypil** [comment]
@john-louden - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[User Voice](https://office365.uservoice.com)** 

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
