### ISSUE TITLE
Compatibility Checker using EXO PS legacy authentication module

### ISSUE THREAD

**Issue by kortamon** [MicrosoftDocs/microsoft-365-docs#4685]
Hello, I was wondering if the tool published in this article will be updated to use the new EXO PS module.
I can see the warning related to MFA not supported but, IMO, the limitations are beyond this.
As there are many ways to block Basic Auth to EXO right now, I believe the information in the article is incomplete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?redirectSourcePath=%252fen-us%252farticle%252fDetermine-if-Centralized-Deployment-of-add-ins-works-for-your-Office-365-organization-b4527d49-4073-4b43-8274-31b7a3166f92&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@kortamon Thank you for your feedback. The O365CompatibilityChecker module works with Legacy and modern authentication but does not support multi-factor authentication as of now(tested). Once that feature gets updated the note will be removed.

Hope this helps!

@yogkumgit There are no changes required in this document.

Thanks
Sri

**Comment by kortamon** [comment]
I am not sure that's entirely correct.
Could you please double check this?

I had tested it: Create a new authentication policy in EXO and block legacy PowerShell. Assign that policy to the user and try to use this tool. You will get an access denied with no further information anywhere.
Adding this limitation to the document will help people in this situation to find the cause

Thank you in advance

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@kortamon Thank you. I'll test and make changes to the document accordingly.

**Comment by msbemba** [comment]
@kortamon Thank you for your feedback. Seems like this works only with basic auth and I have made an update to the note on the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4966

Meanwhile, After checking roadmap I do not see an item for compatibility checker working in new EXO PS module(s). So this could take longer.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kortamon Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
