### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by clconlin** [MicrosoftDocs/microsoft-365-docs#469]
Chart your Microsoft 365 compliance path and information protection strategy link to Ignite session is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d7d882-f847-ac05-04b5-ebedbbe6c8d4
* Version Independent ID: 81246f1e-10b9-de66-3882-24e3a5e044b6
* Content: [Microsoft 365 GDPR action plan — Top priorities for your first 30 days, 90 days, and beyond](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-action-plan#feedback)
* Content Source: [microsoft-365/compliance/gdpr-action-plan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-action-plan.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by clconlin** [comment]
So too is Microsoft GDPR Assessment Tool

**Comment by mypil** [comment]
@clconlin - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@clconlin - thanks for your feedback, this has been corrected.
