### ISSUE TITLE
Policy stacking ambiguos

### ISSUE THREAD

**Issue by mostverydoge** [MicrosoftDocs/microsoft-365-docs#4693]
The meaning of "protection type" seems to change in the middle of this page, so it's not quite clear how the actual combining process works.  The table of priorities lists 8 categories. Below the table, the paragraph "For each protection type (anti-spam, anti-malware, anti-phishing, etc.), " implies that the categories are broader, and there are fewer of them, reflecting the visible divisions in the actual management web GUI (protection.office.com/threatpolicy): anti-spam, anti-malware, anti-phishing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4194fdd-c5de-d424-319a-5e83774b36c2
* Version Independent ID: 83997ad4-a9bd-146e-5da0-8022458cf3ea
* Content: [Order and precedence of email protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mostverydoge, I agree, it's unlear. I changed the offending sentence:

> For each protection type (anti-spam, anti-malware, anti-phishing, etc.)...

To

> For each type of policy (anti-spam, anti-malware, anti-phishing, etc.)...

The point of that sentence is: for each particular type of policy, the first policy that's applied to the user (determined by Priority) is the only policy of that type that's applied to the user. So, different policies with different settings that could potentially apply to the same user aren't applied concurrently or combined in any way.

Thanks for the feedback.

Closing
