### ISSUE TITLE
Clarification when disabling co-authoring for encrypted files. 

### ISSUE THREAD

**Issue by fthorild** [MicrosoftDocs/microsoft-365-docs#4694]
If turning it off it says co-authoring will not work. Does that mean across the board in the tenant or does it mean it will not work for encrypted docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed8ccbd-b955-4a11-f4dd-3a70b549a5f7
* Version Independent ID: 257024d1-afb3-954f-c848-21549cb64fac
* Content: [Enable co-authoring for documents encrypted by sensitivity labels in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-coauthoring?view=o365-worldwide#how-to-enable-co-authoring-for-files-with-sensitivity-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels-coauthoring.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-coauthoring.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@fthorild  It means "..... will no longer work in your tenant for labeled and encrypted documents".  Now added this clarification.  Thanks for the question!

**Comment by fthorild** [comment]
Thanks @cabailey!
