### ISSUE TITLE
404 from navigation

### ISSUE THREAD

**Issue by mjmelone** [MicrosoftDocs/microsoft-365-docs#4695]
This page has a link in navigation, but the page it refers to is a 404.

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-recommendation-by-id?view=o365-worldwide

I can see the page appears to exist, not sure the issue.  Link is in navigation here:
Docs / Microsoft Defender for Endpoint / Reference / Management and APIs / Microsoft Defender for Endpoint API / Microsoft Defender for Endpoint APIs Schema / Recommendation / get-recommendation-by-id

**Comment by denisebmsft** [comment]
Hello @mjmelone. Thanks for posting your feedback. I checked, but I can't find a broken link. The article renders, and the navigation links work as well. Can you confirm that whatever might have been broken is now fixed?
