### ISSUE TITLE
Clarity Request.

### ISSUE THREAD

**Issue by JordanTheITGuy** [MicrosoftDocs/microsoft-365-docs#4696]
"The discovery engine distinguishes between network events that are received in the corporate network versus outside of the corporate network. By correlating network identifiers across all tenant's clients, events are differentiated between ones that were received from private networks and corporate networks. Private network devices will not be listed in the inventory and will not be actively probed."

It would really be great if this spelled out some more  clear guidelines on how a home network is different from a production network. I know there are some allusions to it but some clear detection logic might help cut down on peoples knee jerk stop looking at my stuff reaction. 

Such as - it looks for a certain number of company devices to be on the same network etc. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cf1ccce-15c7-a833-019e-2c0664984247
* Version Independent ID: f7dd7503-7695-37fd-81ea-1388c2d25a69
* Content: [Device discovery frequently asked questions](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-discovery-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-discovery-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-discovery-faq.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resoling this issue. Thanks

**Comment by mjcaparas** [comment]
adding some clarification.
