### ISSUE TITLE
Add information on checking for Delay Holds

### ISSUE THREAD

**Issue by jmeddy** [MicrosoftDocs/microsoft-365-docs#4697]
I experienced an issue where I went through the steps to remove an In-Place Hold from a few mailboxes with a "full (100 GB in size) Recoverable Items folder, and was still not seeing a size decrease until I found this:

https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox?view=o365-worldwide#managing-mailboxes-on-delay-hold

Set-Mailbox <username> -RemoveDelayHoldApplied
Set-Mailbox <username> -RemoveDelayReleaseHoldApplied

Indeed, the commands are listed in Step 4 of this page but have no context to earlier checks.
Therefore, it may be beneficial to expand the checks in Step 1 to provide more useful output and clarify that the above commands are indeed needed with something like the following.

Get-Mailbox <username> | FL *Hold*
or
Get-Mailbox <username> | FL *HoldApplied

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the Recoverable Items folder of cloud mailbox's on hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jmeddy Thanks for the feedback. To be clear, you're suggesting that steps/cmdlets to determine if delay hold is applied should be moved to Step 1 (Get- cmdlets). And Step 4 would be about removing those delay holds (Set- cmdlets). Is that correct?

**Comment by markjjo** [comment]
@jmeddy Fixed. Added step about getting delayhold info in step 1 on gathering information and then focused step 4 on removing delay holds. Thanks again for feedback.
