### ISSUE TITLE
High-Confidence Spam action?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/microsoft-365-docs#471]
What does this sentence mean for "high-confidence spam action - does it matter what is the value, or should it also be "move to junk" in order for ZAP to work: "Spam action is set to Move message to Junk Email folder. You can also create a new spam filter policy that applies only to a set of users if you don't want all mailboxes to be screened by ZAP."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge - protection against spam and malware](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@ArttuArstila  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@ArttuArstila "Move messages to Junk" is the default action for High Confidence Spam according to:

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies 

"**Move message to Junk Email folder**: Sends the message to the Junk Email folder of the specified recipients. **This is the default action for spam, high confidence spam, and bulk.**"

**Comment by mypil** [comment]
@ArttuArstila - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
