### ISSUE TITLE
Misleading/confusing guidance regarding shared mailbox support

### ISSUE THREAD

**Issue by KeepSloanWeird** [MicrosoftDocs/microsoft-365-docs#4710]
[Enter feedback here]
The statement "Users can open protected mails in a shared mailbox where the shared mailbox received a protected mail as part of a distribution group." is not proving true when attempted in a real-world scenario. So far we have only been able to open encrypted/protected messages when the shared mailbox and direct recipients are in the same Distribution Group, as suggested in the statement. However, that negates the use of the shared mailbox. We have yet to figure out a process where a full-access user of a shared mailbox can open an encrypted message in that shared mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#can-i-open-encrypted-messages-sent-to-a-shared-mailbox)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@KeepSloanWeird Thank you for your feedback. Outlook and the Azure Information Protection unified labeling client require the user to have full access permissions and have automapping enabled. So if the shared mailbox is auto mapped to outlook or if the user Uses the Open another mailbox option to open the message in OWA, they can open protected emails.

This part is added to the document "We don't support assignment through an email enabled security group. We only support access provided by direct user assignment to the shared mailbox and that automapping is enabled for Exchange Online. Automapping is enabled by default for Exchange Online."

Hope this helps!

Thanks
Sri

**Comment by KeepSloanWeird** [comment]
Based on your reply there's a pretty critical piece of information missing in this section of the FAQ then:

> Outlook and the **_Azure Information Protection unified labeling client_** require the user to have full access permissions and have automapping enabled.

No where in the Shared Mailbox supported config section is the AIP UL client mentioned. I understand that the UL client is a prerequisite for a number of OME scenarios, but within the context of the shared mailbox specific section that prerequisite isn't referenced. That requires that an assumption is made that the reader already knows about the UL client, but that's a dangerous assumption when the various parts of the FAQ have deep link anchors.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@KeepSloanWeird Thank you for the feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4795

Thanks
Sri

**Comment by yogkumgit** [comment]
@KCCross PR merge request pending. Thanks
