### ISSUE TITLE
Update to section of: Error/issue: Downloaded export shows no results

### ISSUE THREAD

**Issue by funkadelic91** [MicrosoftDocs/microsoft-365-docs#4714]
The last section for "Error/issue: Downloaded export shows no results" ; 

We've had the issue here at KeyBank - one of the things that fixed our issue after months of dealing with this was to use the PowerShell script for removing the exports and searches directly from ExchangeOnline.  The delete script provided in another section worked perfectly.  I would put some explanation in there about how to do this and emphasize to remove all searches and all exports entirely.  Then talk about how PowerShell/EXO/Azure all work as a stack and how when jobs are pushed into the search or export, it actually becomes similar to a queue line in the PowerShell framework on the back end in the background. 

Because of that, if there are outstanding searches from months or years ago, sometimes the GUI will show as completed or other status, but when you run the PS script to view the report on all content searches or exports, the status could actually be different.  We found that there were a handful of searches from over 12 months prior that said complete in the GUI but actually showed up as "pending" or "running" when we ran the PS script.  We removed them all using the PS script with EXO to delete the searches, waited for 48 hours, ran the PS reports again to verify, and then began using the GUI again to stage searches or exports.

Since doing this, there hasn't been any issues with the "zero results/zero bytes" when pushing a search over to export.

All the scripts used were found using the set of PS scripts provided in the content search references and eDiscovery references.

To the point, we also used the same technique to verify and validate the eDiscovery Core holds and the subsequent case and hold information as active, valid, and working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec3c3d62-f46b-bffb-cddb-c7f0932798c3
* Version Independent ID: 71e167e0-2711-32ab-12f4-91b22487cd66
* Content: [Troubleshooting common eDiscovery issues - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery-troubleshooting-common-issues?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery-troubleshooting-common-issues.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery-troubleshooting-common-issues.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@funkadelic91 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4802

Once the author approves, you will see the update on the live document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @funkadelic91 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by funkadelic91** [comment]
> @msbemba Thank you very much for the contribution and updating the documentation with PR. @funkadelic91 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

Thank you for taking the time to update as well!  I appreciate it.  I'll be on the lookout for more areas over time
