### ISSUE TITLE
[LOC]Back-Translation " 電源自動化"→"Power Automate" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/microsoft-365-docs#4715]
ja-jp:"https://docs.microsoft.com/ja-jp/microsoft-365/commerce/subscriptions/self-service-purchase-faq?view=o365-worldwide"
![self-service-purchase-faq_j](https://user-images.githubusercontent.com/40815708/114966751-307e1700-9eae-11eb-9ff3-6dee71060b9f.png)

en-us:"https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq?view=o365-worldwide"
![self-service-purchase-faq_e](https://user-images.githubusercontent.com/40815708/114966761-34119e00-9eae-11eb-9eee-0e67b6a4733d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by TinaMcN** [comment]
@hyoshioka0128 this is caused by machine translation overlocalization.  I sent the topic to be human translated.

**Comment by TinaMcN** [comment]
@hyoshioka0128 the article is now human translated.  Please close if it looks ok now.  Thanks for reporting it.

**Comment by hyoshioka0128** [comment]
@TinaMcN | @yogkumgit - Fixed. Thanks!
Closed #4715 .
