### ISSUE TITLE
Inherit the labels

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#4718]
Hello,

We have 2x labels for groups&sites, they work fine, we use more for unmanaged/managed device access control.

But when we change the sensitivity label in the MS Teams app or via Outlook for MS Teams group (Edit Team, change label), then the label changes and we see a new label applied, but if we go to the SharePoint site, it is not changing in SharePoint site, is it the normal behavior or label that is applied to "Team" should also apply to the MS Team SharePoint site?

As example:
1. Use the MS Teams app and create a new Teams site: "GMTeam"
2. Apply "Label A"
3. SharePoint site created and we can browse and see that site also has "Label A"
4. We go to MS Teams app and change the label to "Label B"
5. In the MS Teams app we see a new label applied, but if we go to the SharePoint site GMTeam, then there we still see "Label A"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by SanjoyanM** [comment]
@lightupdifire : Please open a ticket with Microsoft support. We need a deeper investigation. Also provide the URL to the site in your ticket. Are you able to consistently repro?

**Comment by lightupdifire** [comment]
@SanjoyanM 
I will proceed with the MS case. We can repro the issue, we were waiting for 24 hours, just in case will do one more test and test 48, will come back in 2x days.

**Comment by lightupdifire** [comment]
@SanjoyanM 
Quite interesting result, used 2x Teams, for one team the label was changed at SharePoint site, but for another not... I will do one more test with another 2x Teams and then will go for support.

**Comment by lightupdifire** [comment]
@SanjoyanM
What I did is:
Edit General policy under protection.office.com that applies sensitivity labels to all users, click on next-next-save, then it worked for all sites, but indeed 24 hours sync required. pfeewwww :) case close.
