### ISSUE TITLE
viewing user submitted email reports.

### ISSUE THREAD

**Issue by technonath** [MicrosoftDocs/microsoft-365-docs#472]
The documentation here does not appear to be correct, although you get the graph that shows the user submitted reports, you cannot see the details unless you have an Office 365 Advanced Threat Protection plan. Why should I need an ATP plan to see user submitted reports that do not require an ATP plan?
as per support  [Ticket #:16217153]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69178933-1820-f17d-5efd-0ba9d55c3654
* Version Independent ID: a6766bb0-e49f-f0fe-0d81-67383e22a854
* Content: [View email security reports in the Security & Compliance Center](https://docs.microsoft.com/en-gb/microsoft-365/compliance/view-email-security-reports)
* Content Source: [microsoft-365/compliance/view-email-security-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-email-security-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@technonath  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
Hi @technonath , are you looking at the "Sent and received email report" or the "Top Senders and Recipients report"? When you say details, do you mean the option "View Details Table"?

So you see the graph, but when you click under "View Details Table" what do you see/get?

I want to try to repro this, that's why I'm asking for all the details. Also, you provided a support ticket number...what did support say about this?

**Comment by technonath** [comment]
i am just trying to get clarification from the engineer, as they have now
changed their tune and are saying that it should work without an ATP
subscription and that it has now possibly been fixed without them telling
my engineer. I will reply back when I have clarification.

What a shambles!

**Comment by VLG17** [comment]
@technonath Thank you for replying. From my tests i would also expect it to work without having ATP. Looking forward to a confirmation from support.

**Comment by mypil** [comment]
@technonath - From our understanding, the issue has been answered by VLG17. If you feel it hasn't been answered or if you find any documentation error, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by technonath** [comment]
I have no official answer from the support team, but it now looks like it
has been fixed without them telling anyone and that despite the earlier
testing where it failed without ATP and the guidance I was given 10 weeks
ago, ATP is not required for this to work.
Thank you.
