### ISSUE TITLE
Inaccurate statement - "A single retention policy can be set to apply to Microsoft 365 Groups, Teams chat, and Teams channel messages."

### ISSUE THREAD

**Issue by tshinkle** [MicrosoftDocs/microsoft-365-docs#4721]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4f3e5c-7dd7-ca98-8cd1-21177e7fe26d
* Version Independent ID: 083f0f2c-8c72-582d-3e13-1679684ea88c
* Content: [Compliance options for Microsoft 365 groups, Teams, and SharePoint collaboration](https://docs.microsoft.com/en-us/microsoft-365/solutions/groups-teams-compliance-governance?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/groups-teams-compliance-governance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/groups-teams-compliance-governance.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@tshinkle Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4739

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tshinkle Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
