### ISSUE TITLE
Cannot Disable Antimalware Service Executable

### ISSUE THREAD

**Issue by rafaelcastrocouto** [MicrosoftDocs/microsoft-365-docs#4722]
Despite turning everything off in the security settings (real time protection, cloud-delivery, auto sample submission and tamper protection), the windows defender antivirus keeps running and taking device memory (and sometimes a lot of CPU as well). There's no guides on the Microsoft support on how to disable the service or kill the process and security policies prevent even Admins from turning off the service.

After reading [this documentation](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide) I realized there seems to be some sort of passive mode but no information on how to disable it.

I understand that disabling security might be a risk for most users, but not presenting a way to turn it off will only make users rely on third party solutions that have high risk.  As a user I have the right to choose what software will run in my operational system and because of my type of work, every bit of memory is very important for my workflow.

Can someone please provide a guide on how to REALLY stop the windows defender antivirus, since all safe guides and tools that I could find online don't work after the last updates?

Thanks
![Untitled](https://user-images.githubusercontent.com/422159/115116191-c24d5900-9f6e-11eb-92a6-c147e9a93a1d.png)

**Comment by msbemba** [comment]
@rafaelcastrocouto Thank you for your feedback. You are right, If you are enrolled in Microsoft Defender for Endpoint and you are using a third-party antimalware product, then the passive mode is enabled which cannot be disabled (unless you are on windows server 2016). But this tabular column gives you details about Microsoft Defender Antivirus state - https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide#antivirus-and-microsoft-defender-for-endpoint

Note that all of this is automatic and no changes can be done by the end-user to move the status of Microsoft Defender Antivirus.

Hope this helps!

Thanks
Sri

**Comment by rafaelcastrocouto** [comment]
Thanks for the response @msbemba

I did NOT enrolled into Microsoft Defender Endpoint, my machine is a Samsung notebook that has the default windows 10 installation. I do not use or want to use any type of third-party product nor do I want to use the Microsoft Defender. I just want to turn it off and keep my machine resources for my needs.
If a user is able to turn it off on windows server 2016, seems to me like the Microsoft company is intentionally blocking me from turning their app off in other versions. This clearly represents **product tying** since I'm not obligated to use any kind of anti-virus in order for Windows operational system to work. 

"... no changes can be done by the end-user to move the status of Microsoft Defender Antivirus."
This is unacceptable and there's no technical argument to sustain this.

If not, it's very likely that a bunch of new hacks will pop up just like this old ones:

https://www.alitajran.com/turn-off-windows-defender-in-windows-10-permanently/
https://superuser.com/questions/947873/disable-windows-defender-in-windows-10
https://superuser.com/questions/1054257/how-do-i-kill-antimalware-service-executable
https://www.download3k.com/articles/How-to-Turn-Off-Windows-Defender-Permanently-in-Windows-10-01350

... and remember, their existence only make your software less secure.

I really hope you guys are good people and will help me and other users to use their devices as they see fit.

**Comment by msbemba** [comment]
@rafaelcastrocouto Thank you for your feedback. This issue looks unique since you don't have Defender endpoint enfolled. I'd recommend you contact our Microsoft Support line or raise a support ticket via the need help option on the M365 admin center.

@yogkumgit  There are no changes in the document as this document applies only to Microsoft defender for endpoint.

Thanks
Sri

**Comment by rafaelcastrocouto** [comment]
After 2 hours talking to Microsoft support, I was NOT able to make this process stop.
They indicated me to do the following but none worked:

- Kill the process in task manager (not allowed)
- Add a registry with DisableAntiSpyware in hklm\software\policies\microsoft\windows defender (don't work)
- Disable scans in windows scheduler (don't work)
- Stop the windows defender services (not allowed)
- Add MsMpEng.exe to the exclusion list (don't work)

Can someone plz help me stop this process from running?

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @rafaelcastrocouto  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here we are limited to documentation issues and improvements.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ValZapod** [comment]
It is very simple to do. Jusg disable kernel mode driver and that is all.

**Comment by rafaelcastrocouto** [comment]
@ValZapod can you help me? how can I disable it?

**Comment by ValZapod** [comment]
Reboot in safe mode and then do this https://superuser.com/a/947898/1033761

Works in windows 11.

**Comment by rafaelcastrocouto** [comment]
Thanks for the fast reply but there was no gpedit.msc in my windows. I downloaded and got gpedit to work but it does NOT show 'Windows Defender' inside 'Windows Components' group.
Is there a way to fix this or should I try the CLI ?

**Comment by ValZapod** [comment]
You cannot use gpedit. 
In safe mode:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services.
Look for services starting with "wd" that have "Windows Defender" in the Description value. A possibly incomplete list is: wdboot, wdfilter, wdnisdrv, wdnissvc, windefend.
Change the Start value for each service to 0x4 (hex 4, decimal 4).
Reboot to normal mode.

**Comment by rafaelcastrocouto** [comment]
Did that, now windows won't boot anymore. Great now I gotta format my drive 🙎‍♂️

**Comment by ValZapod** [comment]
> now I gotta format my drive

I know how to do it without windows and yet do not know how to restore bootloader? Are you trolling?

**Comment by rafaelcastrocouto** [comment]
sorry, not trolling at all. just losing my patience with a problem that didn't existed til the latest updates that enforced this antivirus. 
I'm not an expert (specially in boot stuff) so this is kind of a headache for sure.
I have no idea how and where to access and undo windows reg data. Any help is welcome at this point.

**Comment by ValZapod** [comment]
> specially in boot stuff) so this is kind of a headache for sure.

Does it bluescreen on boot? On what stage? Because it must boot.

**Comment by ValZapod** [comment]
You should have also set to 4 the Sence service there. Totaly forgot.

**Comment by rafaelcastrocouto** [comment]
it does boot but windows keeps failing and restarting even in safe/prompt mode

**Comment by ValZapod** [comment]
Try to reboot holding shift it will allow you to go to EUFI recovery where you will have access to command prompt and then just use a command to set Start of Sense to 4 too.

**Comment by rafaelcastrocouto** [comment]
Finnally I was able to open the prompt ... can you help me with the command to change that value?

**Comment by ValZapod** [comment]
> command to change that value?

reg add "HKLM\System\CurrentControlSet\Services\Sense" /v "Start" /t REG_DWORD /d "4" /f

**Comment by rafaelcastrocouto** [comment]
That didn't work. The new added reg is there but it's still rebooting. I tryed to undo the previous modifications but on the prompt reg query seems like all those services were deleted from the registry

**Comment by ValZapod** [comment]
> like all those services were deleted from the registry

They are just not visable to normal user, only to system.

**Comment by rafaelcastrocouto** [comment]
thx for your help. i'm guessing i cant sudo in windows 😅

**Comment by rafaelcastrocouto** [comment]
I've just factory reset the PC  ... no programs, nothing. And windows defender is disabled.

STILL the antimalware is the number one in the memory list 

![Untitled](https://user-images.githubusercontent.com/422159/144706567-e970cd5c-c588-4686-9388-c9f9a5a0a270.png)

**Comment by ValZapod** [comment]
Did you turn off real time protection? Ehat about UAC? Without it you will not be able to do anything. You can also try this (disable inheritence hack on whole WinDefend app). Again, here the first hack with disabling kernel mode drivers worked perfectly yesterday. Why does it start rebooting in your case I have no idea. I also have secureboot on all the time and stuff. So very strange.

This will of course still load the kernel mode drivers so worse idea, but whatever: https://lazyadmin.nl/win-11/turn-off-windows-defender-windows-11-permanently/

**Comment by rafaelcastrocouto** [comment]
I'm on windows 10 home edition ... that won't work.

**Comment by ValZapod** [comment]
> that won't work.

What?

**Comment by rafaelcastrocouto** [comment]
For all of those that have the same struggle here's how I solved:

1st: Install "Update for Windows 10 x64 based Systems (KB4480730)" - this seems to be required and will make a lot of things work as they shoud in the other tutorials

2nd: Install "Defender Control" - https://www.sordum.org/9480/defender-control-v2-0/ - since I was tired of playing around with the registry with no success I tried this one and it worked as a charm

As always users gotta rely on 3rth party software to fix Microsoft mistakes.

**Comment by dragonhart6505** [comment]
> For all of those that have the same struggle here's how I solved:
> 
> 1st: Install "Update for Windows 10 x64 based Systems (KB4480730)" - this seems to be required and will make a lot of things work as they shoud in the other tutorials
> 
> 2nd: Install "Defender Control" - https://www.sordum.org/9480/defender-control-v2-0/ - since I was tired of playing around with the registry with no success I tried this one and it worked as a charm
> 
> As always users gotta rely on 3rth party software to fix Microsoft mistakes.

I made an account just to thank you. Holy hell does that ~200-300mb of memory make a big difference in a lot of applications/games and the fact that it's no longer using every ounce of my HDD activity anytime I access ANYTHING from that drive is miraculous. You, sir, are a godsend!

**Comment by Iterambere** [comment]
> For all of those that have the same struggle here's how I solved:
> 
> 1st: Install "Update for Windows 10 x64 based Systems (KB4480730)" - this seems to be required and will make a lot of things work as they shoud in the other tutorials
> 
> 2nd: Install "Defender Control" - https://www.sordum.org/9480/defender-control-v2-0/ - since I was tired of playing around with the registry with no success I tried this one and it worked as a charm
> 
> As always users gotta rely on 3rth party software to fix Microsoft mistakes.

Thank you very much for this.....

**Comment by ValZapod** [comment]
Used defender control 2.1, and it works in 22H2.

**Comment by ValerianoItaliano** [comment]
Hello, I have the same issue, is it possible to be a litlle be more detailed in the process of solving this issue as I do not completly understand. Thanks in advance! this issue is really annoyin

**Comment by ValerianoItaliano** [comment]
> For all of those that have the same struggle here's how I solved:
> 
> 1st: Install "Update for Windows 10 x64 based Systems (KB4480730)" - this seems to be required and will make a lot of things work as they shoud in the other tutorials
> 
> 2nd: Install "Defender Control" - https://www.sordum.org/9480/defender-control-v2-0/ - since I was tired of playing around with the registry with no success I tried this one and it worked as a charm
> 
> As always users gotta rely on 3rth party software to fix Microsoft mistakes.

Can u help me with more details/steps for how to manage this ? thx

**Comment by ValZapod** [comment]
Did you install https://www.sordum.org/9480/defender-control-v2-0/

It is very simple after that.

**Comment by ValerianoItaliano** [comment]
oh, my concern was where i get the win upd, but i tried without and it seemed to work perfectly. Thank you so much for this fix.
