### ISSUE TITLE
Why Was Defender Scan Terminated?

### ISSUE THREAD

**Issue by bsfinkel** [MicrosoftDocs/microsoft-365-docs#4725]
I received a Defender EventID 1002 during a full scan.  All this documentation tells me is that the scan was terminated before it completed.  I was not at the computer when the scan terminated, so I was not the one who terminated the scan.  I want more information as to why the full Defender scan was terminated.  This is Windows 10 professional 20H2 64-bit.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102c5c34-0c04-cc14-8e9c-74ff42e1fdc2
* Version Independent ID: 6a06016e-6ac1-ab00-5a33-1d1226e2e45d
* Content: [Microsoft Defender AV event IDs and error codes](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@bsfinkel Thank you for your feedback. Per the Event Id, it looks the scan was canceled by the user, If your computer was still turned ON when you returned to it, then I would recommend you contact support to investigate this further. Post contacting support, if you think information is missing on the document, do let us know.

@yogkumgit There are no changes required on the document. 

Thanks
Sri

**Comment by bsfinkel** [comment]
Simple question - How do I contact support?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@bsfinkel You can use one of the support options mentioned here- https://docs.microsoft.com/en-us/defender-for-identity/support#support-options-and-community-resources

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @bsfinkel  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
