### ISSUE TITLE
Maximum number of members per group

### ISSUE THREAD

**Issue by junecastillote** [MicrosoftDocs/microsoft-365-docs#4728]
According to [Group Limits](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#group-limits):
| Number of members | **More than 1,000** |
-- | --

Is there any specific maximum number of members that you can provide aside from "more than 1,000"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@junecastillote Thank you for your feedback. We haven’t documented it as a single limit for Groups because the limits apply differently based on the experience i.e. the limit is different when using a Group in Yammer or Teams or SharePoint or Outlook/Email.

Hope this helps!

@yogkumgit There are no changes required in the document as of now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @junecastillote Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
