### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by mltytskr** [MicrosoftDocs/microsoft-365-docs#473]
The link for the "Step-by-step instructions" in the "Fore more information" section no longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b0319e8-f6d0-942a-f802-f035d753b670
* Version Independent ID: 7c74eb1c-30b5-6186-6775-6cd94fc8eaa4
* Content: [How Office 365 uses Sender Policy Framework (SPF) to prevent spoofing](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing#SPFTroubleshoot)
* Content Source: [microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@mltytskr  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mltytskr - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/c08fffec409254cea26c4a5375aa412dfcf66ccb but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
