### ISSUE TITLE
Downloaded pdf is blank after page 83

### ISSUE THREAD

**Issue by EricKY26** [MicrosoftDocs/microsoft-365-docs#4735]
So I Click 'Download PDF' on the webpage of this Microsoft 365 Docs, 
![image](https://user-images.githubusercontent.com/19644162/115332439-654ddf00-a1ca-11eb-81fe-bd4a43fe9db1.png)
But when I open the downloaded pdf on my computer(surface pro 7), it shows blank after page 83 (Title: Use the Office365 Content Delivery Network (CDN) with SharePoint Online), no matter which software I use, (Microsoft Edge browser,foxit pdf reader and xodo docs, even Word)
![image](https://user-images.githubusercontent.com/19644162/115332668-dc837300-a1ca-11eb-90ae-bfef5f9e2489.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cfe2b0-c14d-1083-7c88-a91e58593cfa
* Version Independent ID: 2d15076c-0dcd-6bd6-e0fb-f8ac5ffd0091
* Content: [Use Office 365 Content Delivery Network (CDN) with SharePoint Online - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@EricKY26 Thank you for your feedback. I'm able to replicate this at my end. We will fix this in the backend and let you know.

Thanks
Sri

**Comment by EricKY26** [comment]
@msbemba Thank you. Then I'll wait for the good news :)

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@LauraWi Gentle reminder. Please.

**Comment by LauraWi** [comment]
Issue opened with docs platform team.

**Comment by LauraWi** [comment]
Platform team has declined to fix.
