### ISSUE TITLE
PDL

### ISSUE THREAD

**Issue by GarySurati** [MicrosoftDocs/microsoft-365-docs#4736]
[Enter feedback here]
It might be good idea to write "Preferred Data Location (PDL)" if you going to use PDL as short form in same article. Instead of just writing "When users in a multi-geo environment create a Microsoft 365 Group, the group preferred data location is automatically set to that of the user." it would be better to write "When users in a multi-geo environment create a Microsoft 365 Group, the group Preferred Data Location (PDL) is automatically set to that of the user."

This way it's easy to read and understand without wondering what PDL is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100a5943-5329-63f6-1fef-5724b29d162a
* Version Independent ID: 7819933f-ed32-98bf-d0b2-b088fbbce067
* Content: [Create a Microsoft 365 Group with a specific PDL - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-add-group-with-pdl?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/multi-geo-add-group-with-pdl.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/multi-geo-add-group-with-pdl.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@GarySurati Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4817

Thanks
Sri
