### ISSUE TITLE
SharePoint Search  about Sensitive Data 

### ISSUE THREAD

**Issue by LiDamon** [MicrosoftDocs/microsoft-365-docs#4741]
Can we use SharePoint Search about Sensitive Type? We used ClassificationType instead of SensitiveType in Sharepoint search was worked, but we did not found any introduction about ClassificationType .

The Sample Like:
**ClassificationType:a44669fe-0d48-453d-a9b1-2cc83f2cba77**
Same as eDiscovery Search
**SensitiveType: U.S. Social Security Number (SSN)**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@LiDamon Thanks for your inquiry. Your comment seems to imply that you are using SharePoint Search and not an eDiscovery tool (Content search, Core eDiscovery, and Advanced eDiscovery). The topic that you opened this github issue against is about queries in these eDiscovery tools (and not SharePoint Search).

I checked with the engineering team and for eDiscovery searches, you should use SensitiveType, which will return all classification types (so it depends on the value that you provide for the SensitiveType property.

If you have a different experience in your organization, I would suggest that you contact MS Support.
