### ISSUE TITLE
Clarification on M365 Reports Dashboard Information

### ISSUE THREAD

**Issue by seymourdixongais** [MicrosoftDocs/microsoft-365-docs#4744]
Hi everyone, I'm trying to wrap my head around the meaning of a couple of these reports - specifically the "Active Users - M365 Services" and "Active Users - M365 Apps". I figure asking this might be useful in case anyone else is wondering the same thing. 

https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide

Firstly.. what is the difference between a Service and an App? Particularly the "Teams" bar as it looks like it exists in both graphs. I presume one is for the desktop application, but not sure what constitutes the "Teams" service.

Secondly, what is the relation between the number of active / inactive users in these graphs and the number of licenses assigned? I was under the impression that active users + inactive users = total licensed users. However in my tenant for example, when I compare the total user count for Teams for either graph against licenses assigned for M365 E3 licenses (this is the only Office license we have for end users), they do not match.

Any clarification is much appreciated!!

![image](https://user-images.githubusercontent.com/43426805/115435916-58d08300-a1d8-11eb-90b2-131cf4f2d5e2.png)

**Comment by denisebmsft** [comment]
Hello @seymourdixongais and thanks for posting your question. Can you please tell us to which article(s) this applies? This information will help us route the issue correctly. Thank you!

**Comment by seymourdixongais** [comment]
Sure thing, thanks for looking into this @denisebmsft! 

The main page where this graphic was sourced from comes from [here](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide)

For "Active Users - Microsoft 365 Services" graph, [this](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/active-users-ww?view=o365-worldwide) is the applicable article.

For "Active Users - Microsoft 365 Apps" graph, [this](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/microsoft365-apps-usage-ww?view=o365-worldwide) is the applicable article.

Please let me know if any additional information is required!

**Comment by denisebmsft** [comment]
Thank you @seymourdixongais

**Comment by seymourdixongais** [comment]
Additional information for the second question's Teams example: I noticed my tenant also has a number 'Microsoft Teams Exploratory' licenses assigned out. In addition to the Office 365 E3 licenses, could these licenses also play a role into the total count of the active + inactive users?

**Comment by msbemba** [comment]
@seymourdixongais Thank you for your feedback. 

* Service consists of different services. For example, Exchange Online, Sharepoint Online, Teams, etc.
* Apps include Applications like Word, Outlook, Excel, Teams, etc.
* The active  + inactive users include all paid and Free licenses like Teams Exploratory licenses assigned out.

Hope this information helps!

Thanks
Sri
