### ISSUE TITLE
Branding portal page does not list how to log into Powershell.

### ISSUE THREAD

**Issue by useyourblinker** [MicrosoftDocs/microsoft-365-docs#4747]
[Enter feedback here]

Microsoft -

Just a suggestion here - on any of these pages, maybe there should be a little section at the top listing which Powershell module should be used while connecting.

While you have ones for Sharepoint, Exchange Online, and a dozen others - this page does not list that you need to first connect to Connect-IPPSSession before you do this portal branding.

While someone might think that's obvious (because it's the security and compliance center powershell login), portal branding is often well outside the parameters of what people would consider to be a "security" setting. 

If you at least have a small section at the top that maybe recurs around your site (with things that need it), that say "to connect to your security and compliance center in powershell, do X, Y, Z" or link https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04de3d3-6a94-29f8-3a3d-68ed9422e058
* Version Independent ID: e50fc407-2c78-a3cc-71cd-7978ca340189
* Content: [Add your organization brand to your encrypted messages - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by useyourblinker** [comment]
Microsoft - Sorry as I was already connecting to the wrong thing in frustration here - but I actually meant to direct that at Connect-ExchangeOnline instead of Connect-IPPSSession. It's been a long week.

But anyway, my point is the same - the document doesn't even list which module you should be connecting to in order to start with!

**Comment by msbemba** [comment]
@useyourblinker Thank you for your feedback. The document has that information and it says you need to connect to Exchange Online PowerShell before executing the cmdlet. I tested and it works after connecting to Exchange online module, So I don't think there are any changes needed in the document at this time.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @useyourblinker Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by useyourblinker** [comment]
I'm 100% sure I left this feedback on the wrong page here so I am circling back to try to figure out which page I actually meant to leave that feedback on. Thank you.
