### ISSUE TITLE
Managing individual users' signatures

### ISSUE THREAD

**Issue by rylcode** [MicrosoftDocs/microsoft-365-docs#4749]
This document lacks information on managing individual users' mail signatures. An administrator may be tasked with ensuring all users' signatures are formatted in a unified way, while ensuring the information is correct. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a984a46-1f7b-6ef1-71f3-c5df6c142c01
* Version Independent ID: 4fab7da3-c9ae-0136-c693-ae99c1090f40
* Content: [Create organization-wide signatures and disclaimers - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/create-signatures-and-disclaimers?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/create-signatures-and-disclaimers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/create-signatures-and-disclaimers.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by yogkumgit** [comment]
@twernermsft  Please add your comment and help us in resolving this issue. Thanks.

**Comment by lhcole** [comment]
@rylcode Thanks for your feedback. I've forwarded your comments to the writing team. They evaluate whether to include these changes in the next round of revisions in this feature area content.
