### ISSUE TITLE
How to segregate subscriptions?

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/microsoft-365-docs#4750]
[Enter feedback here]
We would like to deploy Defender to our prod and non-prod environments. We have an Azure subscription for both environments. It would be good to know how to configure Defender to report in to the corresponding security center for each environment, or at least know if this is possible or not?

Some other agents get deployed with a special string or config that tells them about the license and environment to report to.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b25b8545-b7f0-e035-ca6e-26b1530feddb
* Version Independent ID: 93b5152a-2ba2-1239-ded7-42896cacc074
* Content: [Set up Microsoft Defender for Endpoint deployment](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/production-deployment?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/production-deployment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/production-deployment.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas  Please add your comment and help us in resolving this issue. Thanks.

**Comment by mjcaparas** [comment]
Please contact support.
