### ISSUE TITLE
wrong Link 

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/microsoft-365-docs#4752]
The link in the section: 
https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-service-encryption?view=o365-worldwide#customer-key named " See Enhancing transparency and control for Office 365 customers for the original announcement." redirects to a not existent site. The right one seems to be: 
https://www.microsoft.com/en-us/microsoft-365/blog/2015/04/21/enhancing-transparency-and-control-for-office-365-customers/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2f2581-292d-a72b-0683-897eaac0adb0
* Version Independent ID: d10014a1-164d-1aea-635f-8c63da26b44c
* Content: [Service Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-service-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/office-365-service-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-service-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@J-a-k-o-b Thank you for your feedback. We have made changes tot he document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4818

Thanks
Sri

**Comment by yogkumgit** [comment]
@J-a-k-o-b I will close the issue, after PR is merged. Reopening.

**Comment by tiburd** [comment]
@yogkumgit - I closed the related PR because the link is updated.
