### ISSUE TITLE
Grammar in Step 2

### ISSUE THREAD

**Issue by JimKCode** [MicrosoftDocs/microsoft-365-docs#4755]
The NOTE in Step 2 is missing the word "if" in the second sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the Recoverable Items folder of cloud mailbox's on hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide#step-2-prepare-the-mailbox)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@JimKCode Thanks for the heads up.  I will fix. Note that in future you can also fix issues like these by signing into to your msft-connected github account, clicking the Edit button on the topic, and submitting a pull request. See: https://review.docs.microsoft.com/office-authoring-guide/contribute-get-started-setup-quick-update?branch=master
