### ISSUE TITLE
CPU core requirements

### ISSUE THREAD

**Issue by cjkeist** [MicrosoftDocs/microsoft-365-docs#4756]
[Requirements section doesn't specify a minimum of 2CPU cores, only memory. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Hi @cjkeist, is there a 2 cores minimum?
Can you point me in the right direction on where you found this information so I can add it via a PR?

**Comment by cjkeist** [comment]
Hello,
   It’s in the mde_installer.sh script. It checks number of cores and fails if only one core is found. Along with number of cores it also checks for minimum of 2GB of RAM free and disk space.


--
CJ Keist
Assistant Director, CoSINe IT Services
Division of Arts and Sciences
Oregon State University
541-737-1066 | Strand Ag Hall 062C



From: Thomas Sjögren ***@***.***>
Reply-To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Date: Tuesday, April 27, 2021 at 1:36 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: "Keist, CJ" ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] CPU core requirements (#4756)


[This email originated from outside of OSU. Use caution with links and attachments.]

Hi @cjkeist<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcjkeist&data=04%7C01%7C%7C6cf6e500911d48ac975908d909578c27%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637551093881692695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EBSAa2KeijFzrpEKoH2QfnF4qie2mIR8fo3xUaOxCeU%3D&reserved=0>, is there a 2 cores minimum?
Can you point me in the right direction on where you found this information so I can add it via a PR?

**Comment by konstruktoid** [comment]
Yeah, that script doesn't really follow the memory requirements either.

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide:
Disk space: 1GB
Memory: 1GB
No CPU requirements.

https://github.com/microsoft/mdatp-xplat/blob/master/linux/installation/mde_installer.sh#L17-L19
Cores: 2
Memory: 2048
Disk space: 1024

**Comment by yogkumgit** [comment]
@Dansimp Please share your opinion and help us in resolving the issue and PR. Thanks

**Comment by konstruktoid** [comment]
Hi again @cjkeist, could you verify the shell script after the code merge?

**Comment by yogkumgit** [comment]
Changes will be reflected within 24 hours. @cjkeist Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by cjkeist** [comment]
Yes, I see the changes have been made. Thanks!


--
CJ Keist
Assistant Director, CoSINe IT Services
Division of Arts and Sciences
Oregon State University
541-737-1066 | Strand Ag Hall 062C



From: Thomas Sjögren ***@***.***>
Reply-To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Date: Friday, May 7, 2021 at 2:32 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: "Keist, CJ" ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] CPU core requirements (#4756)


[This email originated from outside of OSU. Use caution with links and attachments.]

Hi again @cjkeist<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcjkeist&data=04%7C01%7C%7C7061400ee25a44e20ef708d9113b0b2f%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637559767570819887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K%2BrJ%2BTwEqK3SCfifNez5XVa2%2Ft4YvlVSgKd2P%2FjkTMg%3D&reserved=0>, could you verify the shell script after the code merge?
