### ISSUE TITLE
404 error on hyperlink

### ISSUE THREAD

**Issue by WoodneyUK** [MicrosoftDocs/microsoft-365-docs#4762]
Link to https://docs.microsoft.com/en-us/collect-diagnostic-data.md is not valid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a08b6ae-6445-ab2b-d380-627df46cf3d5
* Version Independent ID: c855d3af-002e-aff2-b2d6-8c6e549850a2
* Content: [Troubleshoot performance issues](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-performance-issues?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-performance-issues.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-performance-issues.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by denisebmsft** [comment]
Hello @WoodneyUK and thank you for letting us know about this. We have fixed the link, and the changes will be live tomorrow, April 23.

**Comment by schmurky** [comment]
Thank you @denisebmsft!
