### ISSUE TITLE
Link to Linux documentation 404s.

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/microsoft-365-docs#4765]
If you click the link to Linux documentation, it is a dead end that results in a 404 notification. The URL it points to that fails is:

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-atp-linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e914c02a-e905-fc32-439c-feb1fafa09b8
* Version Independent ID: 1a6a15e9-717a-33c1-b90e-96925c680228
* Content: [Microsoft Defender for Endpoint for non-Windows platforms](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/non-windows?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/non-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/non-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by jwojan** [comment]
It looks like all of the links to documentation for Linux, MacOS, Android and IOS are ALL BROKEN.

**Comment by mjcaparas** [comment]
PR already checked in to fix this.
