### ISSUE TITLE
It would recommend including a section on data residency 

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4768]
It would recommend including a section on data residency and the option for multi-geo be able to store Teams, SharePoint, OneDrive and  Exchange online content in a local geo to comply with local regulations.  I find this is a key question that I am asked as a Gold Partner. 
Microsoft Docs reference pages 
Multi geo in teams https://docs.microsoft.com/en-us/microsoftteams/teams-experience-o365odb-spo-multi-geo 
Multi geo https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-multi-geo?view=o365-worldwide
Multi geo SharePoint Online and OneDrive for Business https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-microsoft-365?view=o365-worldwide
Location of data in Teams lhttps://docs.microsoft.com/en-us/microsoftteams/location-of-data-in-teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4f3e5c-7dd7-ca98-8cd1-21177e7fe26d
* Version Independent ID: 083f0f2c-8c72-582d-3e13-1679684ea88c
* Content: [Compliance options for Microsoft 365 groups, Teams, and SharePoint collaboration](https://docs.microsoft.com/en-us/microsoft-365/solutions/groups-teams-compliance-governance?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/groups-teams-compliance-governance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/groups-teams-compliance-governance.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT  Please add your comment and help us in resolving this issue. Thanks.

**Comment by MikePlumleyMSFT** [comment]
Thanks, @nikki-c, @yogkumgit. I added a data residency section to the doc.

**Comment by yogkumgit** [comment]
@nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
