### ISSUE TITLE
clarification needed

### ISSUE THREAD

**Issue by MarzelLaning42** [MicrosoftDocs/microsoft-365-docs#4772]
[Enter feedback here]
"Your subscription directory must either be in, or federated to Azure Active Directory"
and
"An on-premises directory service"

'subscription directory' is a vague term. There is an Azure Active Directory where accounts live and subscription are also referenced as license plans, sometimes called subscription. But azure subscriptions are something totally different and have a relation with Azure AD tenant.

What I would like to know is:
Are Hybrid Identity scenario's supported or not. The statement that "An on-premises directory service" is not supported, seems to imply that a Hybrid scenario is not supported. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@MarzelLaning42 Thank you for your feedback. Centralized deployment of add-ins works on a Hybrid identity scenario as long as the mailbox is hosted in Exchange online.

Hope this helps!

Thanks
Sri
