### ISSUE TITLE
Peculiarities of different group types not getting clear

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/microsoft-365-docs#4778]
From the list of different group types it's not getting clear which features come along with each type. The different paragraphs barely describe their peculiarities but not their similarities.

May I suggest to provide an intersection diagram to the page, depicting the peculiarities as well as the similarities of each of the different group types, like in this sketch:

![Group Features](https://user-images.githubusercontent.com/9283914/115868097-35a60d80-a43c-11eb-86f4-c813d8864f61.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@SetTrend Thank you for your feedback. Below is the description of groups in the document. I think it does explain precisely on what the groups can be used for, Is there any feature or group that you think is missing or creating ambiguity?

Microsoft 365 groups (formerly Office 365 groups) are used for collaboration between users, both inside and outside your company.
Distribution groups are used for sending notifications to a group of people.
Security groups are used for granting access to resources such as SharePoint sites.
Mail-enabled security groups are used for granting access to resources such as SharePoint, and emailing notifications to those users.
Shared mailboxes are used when multiple people need access to the same mailbox, such as company information or support email address.


Thanks
Sri

**Comment by SetTrend** [comment]
Thank you for replying.

Well, that's the peculiarities - but what are the similarities?

- Which of the group types can be addressed by e-mail?
- Which of the group types can be added to a Teams channel?
- ...

**Comment by msbemba** [comment]
@SetTrend That's a valid point. I'll add the information to the document shortly.

**Comment by msbemba** [comment]
@SetTrend I have made changes to the document via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4872

**Comment by SetTrend** [comment]
Thank you, @msbemba, your expertise is very much appreciated.
