### ISSUE TITLE
Outlook issue

### ISSUE THREAD

**Issue by Galbadrah** [MicrosoftDocs/microsoft-365-docs#4779]
I have an issue with outlook. We got office 365  education for our school. Almost all apps work but outlook did not work. It displays error 500.

Error 500 says "Something went wrong.
We couldn't find a mailbox for this account. Either they don't have a mailbox or don't have a license assigned.

To fix it, contact your Email Admins and ask them to assign a valid license to your user account using M365 Admin Portal per instructions Getting a mailbox not found an error in Outlook on the web?"

I tried it but it did not work. What should I do now?
I hope you would help me.
I am looking forward to hearing from you.

**Comment by denisebmsft** [comment]
Hello @Galbadrah. Sorry to hear you are having issues with Outlook. You need to contact support. See who in your school can help, and see this page, too. https://support.microsoft.com/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.education
