### ISSUE TITLE
Change nameservers to set up Microsoft 365 breaks website - no instructions for remedy in the docs

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/microsoft-365-docs#4780]
The steps to remedy the fact that an existing website won't be reached after adding Microsoft NS records to the original provider's DNS records end with ... no information:

> 4. Select the type of DNS record you want to add, and type the information for the new record.

I don't want to add anything. I just want to get my website running back again. What's precisely required here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3db0d1ba-e79a-77ab-fced-a8a80f5b07b3
* Version Independent ID: 30dda152-9ad2-24c3-caf6-e00f3443b173
* Content: [Change nameservers to set up Microsoft 365 with any domain registrar - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@SetTrend Thank you for your feedback. When you change you nameservers to Microsoft it will break the other dependencies, like website. So you need to follow the below steps mentioned in the document.

Additional steps that might be required for email and website hosting:

Move all email addresses that use your domain to Microsoft 365 before you change your NS records.

Want to add a domain that's currently used with a website address, like www.fourthcoffee.com? You can take below steps while you add the domain to keep its website hosted where the site is hosted now so people can still get to the website after you change the domain's NS records to point to Microsoft 365.

In the admin center, go to the Settings > Domains page.

On the Domains page, select the domain and then choose DNS Records.

Under Manage DNS, select Custom Records, and then choose New custom record.

Select the type of DNS record you want to add, and type the information for the new record.

Select Save.

In case you are not sure which record is required to keep your Website up and running, Contact you website host and ask them for the DNS records and follow the steps mentioned above.

Hope this helps!

Thanks
Sri

**Comment by SetTrend** [comment]
Hello @msbemba,

thank you for replying.

> Select the type of DNS record you want to add, and type the information for the new record.

Actually, that is of no informational use. _"Select the type of DNS record you want to add"_ ... I do not "want to add" anything. I have no knowledge of what to add at all. I just followed the Microsoft 365 domain migration wizard's instructions.

Microsoft cannot expect everyone willing to migrate to Microsoft 365 to become a DNS expert.

The Microsoft 365 guided domain migration setup wizard should provide two distinct paths when leading the user through its instructions. The first question should be "Do you already run a website on your custom domain?" - and if so, a different setup path should be provided by the guided migration wizard.

As of today, I'm now in a situation where I followed the Microsoft 365 domain migration setup wizard 1:1 and our website isn't available anymore.
<br/>

#### So, the question is:

What exact DNS settings do the Microsoft 365 servers want me to add to our DNS server settings?

**Comment by msbemba** [comment]
@SetTrend Got it! Microsoft cannot provide that information as it depends on the type of website. So that is why the document states If you're not familiar with DNS, contact support at the domain registrar. Meanwhile, A and CNAME records for the website are the common ones that are used. So you may want to try that first to see if it works.

Thanks
Sri

**Comment by SetTrend** [comment]
Thank you, @msbemba.

> Microsoft cannot provide that information as it depends on the type of website.

Although I'm not a DNS expert, I believe there is a delimited set of rules in DNS configuration that must apply for a website to be reachable.

I would suppose the migration wizard to initially query the currently configured DNS server first before starting the migration and then suggest correct settings as a final step for finalize the migration.

**Comment by SetTrend** [comment]
I removed the `NS` records from our DNS now, and everything seems to run smoothly now.

I don't understand why the domain migration wizard recommends setting `NS` servers to microsoft servers if that's not necessary.

I believe the usability of the wizard should be greatly overhauled.

And the documentation should explain the edge cases when to update `NS` DNS records - and when to leave them as-is.

**Comment by msbemba** [comment]
@SetTrend The document is for people who want Microsoft 365 to manage your DNS records for you. (If you prefer, you can manage your own DNS records (Link with instructions are provided. The document also has been updated with the below Caution 

"When you change your domain's NS records to point to the Microsoft 365 nameservers, all the services that are currently associated with your domain are affected. If you skipped any steps of the wizard, such as adding email addresses, or if you're using your domain for blogs, shopping carts, or other services, there are additional steps that are required. Otherwise this change could result in service downtime, such as lack of email access or your current website being inaccessible."

Hope this helps!

Thanks
Sri

**Comment by SetTrend** [comment]
Well, it's rather the missing information about _when_ to setup `NS` records and when to rather refrain from doing so. The documentation (as well as the wizard itself) lacks this information.

When you're looking for information on what's required to migrate your domain from a custom provider to Microsoft 365, this (misleading) content is found:

### (1)
[Set up your domain (host-specific instructions)](https://docs.microsoft.com/microsoft-365/admin/get-help-with-domains/set-up-your-domain-host-specific-instructions)

> To start using a custom domain (contoso.com) with Microsoft 365, you need to verify your domain and configure your domain's DNS records.
>
> You can add and manage DNS records using the administrative tools at your domain host, or give Microsoft control of your domain records and we'll set them up for you.
Let Microsoft 365 manage your DNS records
>
> Learn how to change nameservers to set up Microsoft 365 with any domain registrar.

### (2)
[Change your domain's nameserver (NS) records](https://docs.microsoft.com/microsoft-365/admin/get-help-with-domains/change-nameservers-at-any-domain-registrar#change-your-domains-nameserver-ns-records)

> When you get to the last step of the domains setup wizard in Microsoft 365, you have one task remaining. To set up your domain with Microsoft 365 services, like email, you change your domain's nameserver (or NS) records at your domain registrar to point to the Microsoft 365 primary and secondary nameservers. Then, because Microsoft 365 hosts your DNS, the required DNS records for your services are set up automatically for you. You can update the nameserver records yourself by following the steps your domain registrar may provide in the help content at their website. If you're not familiar with DNS, contact support at the domain registrar.
<br/>

None of the above articles mentions a doubt in whether to alter NS records or not.

**Comment by SetTrend** [comment]
Do you know, is there a repository for the domain setup wizard? I'd like to add an issue there and cross-reference to this issue here, so they have a change to amend the domain setup wizard, too.

**Comment by msbemba** [comment]
@SetTrend This document -https://docs.microsoft.com/en-us/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider?view=o365-worldwide talks about updating DNS Records in the admin center. 

I'll add these steps to the document and hopefully, that should help customers.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SetTrend Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
