### ISSUE TITLE
Associated Log File

### ISSUE THREAD

**Issue by mgetzem** [MicrosoftDocs/microsoft-365-docs#4782]
Reviewing microsoft-365/security/office-365-security/external-email-forwarding.md page - trying to find the log file that would be associated with this change. Would someone be able to provide either a sample log file generated, or how to search for this change log?

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding

**Comment by msbemba** [comment]
@mgetzem Thank you for your feedback. There are no such log files that get generated. Are you referring to an Admin audit log that confirms this change being made on the tenant? 

Thanks
Sri

**Comment by mgetzem** [comment]
Yes, i apologize. I meant which admin audit log would capture this change

**Comment by msbemba** [comment]
@mgetzem You can view the admin audit log from the EAC. You can find the steps here -https://docs.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/view-administrator-audit-log#use-the-eac-to-view-the-administrator-audit-log

The specific cmdlet that you need to look for in the Log would be Set-HostedOutboundSpamFilterPolicy

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mgetzem Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
