### ISSUE TITLE
End User Spam Notification only Showing Email for the Date Delivered.

### ISSUE THREAD

**Issue by mrstephenson2142** [MicrosoftDocs/microsoft-365-docs#4784]
We have the end user spam notification enabled and reporting every seven days. The notification is only showing email for that day and not all email received since the last notification. Is that by design or should we be seeing all email since the last notification was sent? The documentation does not specify. If this is by design could that notion be added somewhere? We want to keep the number of messages that our users receive lower, but if the notification for spam goes out on a day they didn't receive spam, they may not know to check their quarantine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedcd379-0c7e-5b68-be04-e272ac53638d
* Version Independent ID: 664acd84-b4df-c943-e027-677f4340768e
* Content: [End-user spam notifications in Microsoft 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mrstephenson2142, based on research and contacting people, it sounds like the next notification should contain all email since the last notification.

Your best course of action is to open a support case about this. Report back here with the final result, which may or may not require an update to the documentation.

**Comment by yogkumgit** [comment]
@mrstephenson2142 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
