### ISSUE TITLE
This document recommends a different setting for “Turn off Microsoft Defender Antivirus.” than what other document suggest (the latter actually fixed issue for customer)

### ISSUE THREAD

**Issue by anaguile** [MicrosoftDocs/microsoft-365-docs#4785]
[Please reference previous feedack: https://github.com/MicrosoftDocs/windows-itpro-docs/issues/9341

From RAVE case 24527130 https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mcafee-to-microsoft-defender-setup?view=o365-worldwide#enable-microsoft-defender-antivirus-on-your-windows-client-devices recommends “Turn off Microsoft Defender Antivirus.” to be set to "Disabled" .

However, https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/use-group-policy-microsoft-defender-antivirus?view=o365-worldwide says it should be “Not Configured” instead to ensure any installed third-party antivirus apps work correctly, that setting is what actually fixed the problem in customer's scenario, which was Defender not going into passive mode despite being onboarded on MDE with McAfee AV installed (they provided the feedback that this should be addressed/corrected).]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0ea1ec-1cb7-4802-8e91-b86aadb67784
* Version Independent ID: 54a4c0bb-8488-b19b-10b1-ca4a3ee47fd8
* Content: [McAfee to Microsoft Defender for Endpoint - Setup](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mcafee-to-microsoft-defender-setup?view=o365-worldwide&source=docs#enable-microsoft-defender-antivirus-on-your-windows-client-devices)
* Content Source: [microsoft-365/security/defender-endpoint/mcafee-to-microsoft-defender-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mcafee-to-microsoft-defender-setup.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by anaguile** [comment]
@yogkumgit , please put a hold on this request.

actually it appears the problem may be related to a different thing and that would mean that our documentation is fine.

I will report back.

**Comment by msbemba** [comment]
@anaguile Thank you for your feedback. This document pertains more to Switching from Mcafee to Microsoft defender for Endpoint. So not sure if this change in required in this document. But as per your comment, we will wait for you to report back.

Thanks
Sri
