### ISSUE TITLE
M365 Endpoint DLP block settings not applying

### ISSUE THREAD

**Issue by natpascual1027** [MicrosoftDocs/microsoft-365-docs#4789]
Hi,

I'm testing M365 Endpoint DLP on a virtual machine in my local device. My DLP policy  is configured to detect sensitive information types and all actions (e.g. copy to clipboard, transfer through bluetooth, etc) are set to **block** except for remote desktop services set to **audit only**. My policy is already turned on for 3 days now. But I don't seem to see the block settings taking effect. Activity Explorer shows that it's just auditing my actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76da4eda-4ccf-ff34-6a48-d9c5553c2ed6
* Version Independent ID: 7e887aff-1b85-1651-2bff-63425c54ae63
* Content: [Using  Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-using?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-using.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@natpascual1027 Thank you for your feedback. I shall test and update the document if needed.

Thanks
Sri

**Comment by natpascual1027** [comment]
@msbemba Hi. I'm specifically having trouble on the scenario of detecting a custom sensitive info type on my endpoint. My setting is to block all actions (print, copy to clipboard, etc). Activity explorer sometimes show that the action with the document containing the sensitive info is detected but only audited. Not blocked.

**Comment by msbemba** [comment]
@natpascual1027 Thank you for the update. I was able to test this on a high level, Since you have issues with detecting a custom sensitive info type, we suggest you get in touch with Microsoft support via the Need help section on the admin center. If you think there are any changes required in the document post you communicate with support.

@yogkumgit  There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @natpascual1027 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mariuszo-at-microsoft-com** [comment]
@natpascual1027 check "Always audit file activity for devices" setting under Data loss prevention > Endpoint DLP settings.  If it is turned on, then it might be overriding your active DLP policy.  Try to turn it off.
