### ISSUE TITLE
Link changed

### ISSUE THREAD

**Issue by ArBixD** [MicrosoftDocs/microsoft-365-docs#4791]
Hi, the first Link directs one to the Azure Portal. When i search for Intunes there, and click the icon, it tells me the page was moved to https://endpoint.microsoft.com/. Can you adjust the Page so you land directly there? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8387555-2aea-a843-2e8f-e831629fc004
* Version Independent ID: c40f9512-87e3-5334-832e-ab153e608925
* Content: [How to control USB devices and other removable media using Intune (Windows 10)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/control-usb-devices-using-intune?view=o365-worldwide#block-installation-and-usage-of-removable-storage)
* Content Source: [microsoft-365/security/defender-endpoint/control-usb-devices-using-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/control-usb-devices-using-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ArBixD Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4835

Thanks
Sri
