### ISSUE TITLE
Add Licensing information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#4796]
Please add something to identify which licenses are required to get this functionality. I have a customer that is not seeing this and I'm not sure if its a bug or a licensing issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d55651b-e677-6784-78ec-043f3368da2e
* Version Independent ID: afc4b465-6f0f-cc78-cbe1-b104bf033f3a
* Content: [Track and respond to emerging threats with threat analytics](https://docs.microsoft.com/en-us/microsoft-365/security/defender/threat-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/threat-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/threat-analytics.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@DeanGross Threat Analytics applies to Microsoft defender for office 365. No other specific License requirements as such. If the customer is not able to view Threat Analytics on the Microsoft Defender security center, Please have them log a case with Microsoft support via the need help option on the admin center.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit There are no changes required in the document.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
