### ISSUE TITLE
Please address forced tunnel VPN with Isolate Machine and add recommendation for split tunneling for MDE

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/microsoft-365-docs#4797]
[Enter feedback here]
Please add disclaimer to Isolate Machine section (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#isolate-devices-from-the-network)

IMPORTANT!
When isolating a device, only certain processes and destinations are allowed. Therefore, devices that are behind a full VPN tunnel won't be able to reach the Microsoft Defender for Endpoint Cloud service after the device is isolated. The recommendation is to use split-tunneling VPN for Microsoft Defender for Endpoint and Defender AV cloud-based protection related traffic 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb7742-1171-00f4-ab40-6bcc479078ca
* Version Independent ID: 9a79f573-5f20-0e4c-822e-8af4ebf65422
* Content: [Take response actions on a device in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#isolate-devices-from-the-network)
* Content Source: [microsoft-365/security/defender-endpoint/respond-machine-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/respond-machine-alerts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@vboyev-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4836

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @vboyev-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
