### ISSUE TITLE
Access retention area in the M365 interface.

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/microsoft-365-docs#4799]
How is this done in the new interface?  Under Information Governance, there isn't a retention option, just dashboard and archive.

View a list of inactive mailboxes
To view a list of the inactive mailboxes in your organization:

Go to https://protection.office.com and sign in using the credentials for an administrator account in your organization.

Click Information governance > Retention.

On the Retention page, click MoreNavigation Bar ellipses, and then click Inactive mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7108464d-597a-c79d-cac8-94e35d9dd3d0
* Version Independent ID: ba0d3744-707d-c506-47f4-83519022d4cb
* Content: [Create and manage inactive mailboxes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-and-manage-inactive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rconiv Thanks for inquiry. In the M365 compliance center (MCC), the inactive mailbox button is basically in the same place: Information governance > Retention > Inactive mailbox (see screenshot below). You might also try the direct URL: https://compliance.microsoft.com/informationgovernance/retention/inactivemailbox. Of course, you can also use Get-Mailbox -InactiveMailboxOnly command in EXO PowerShell.

Not sure why you aren't seeing all the tabs on the Information governance page. That seems like an RBAC/permissions issues. But you should see Retention tab in the MCC if you could see it in the old security & compliance center (SCC) interface. If this persists, you might want to contact Microsoft support.

I will update this topic with the new instructions to view inactive mailboxes in MCC.

![image](https://user-images.githubusercontent.com/36746813/116130650-55c60e80-a680-11eb-931e-73d2b84f7a37.png)

**Comment by rconiv** [comment]
Thanks, it could be a permissions thing.  I don’t have complete admin rights in M365.  This is all I see when I go to Home - Security & Compliance (office.com)<https://protection.office.com/homepage> from the link in Create and manage inactive mailboxes - Microsoft 365 Compliance | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes?view=o365-worldwide>.  The link you gave got me to it.

***@***.***D73A8E.D789AC50]


@rconiv<https://github.com/rconiv> Thanks for inquiry. In the M365 compliance center (MCC), the inactive mailbox button is basically in the same place: Information governance > Retention > Inactive mailbox (see screenshot below). You might also try the direct URL: https://compliance.microsoft.com/informationgovernance/retention/inactivemailbox. Of course, you can also use Get-Mailbox -InactiveMailboxOnly command in EXO PowerShell.

Not sure why you aren't seeing all the tabs on the Information governance page. That seems like an RBAC/permissions issues. But you should see Retention tab in the MCC if you could see it in the old security & compliance center (SCC) interface. If this persists, you might want to contact Microsoft support.

I will update this topic with the new instructions to view inactive mailboxes in MCC.

[image]<https://user-images.githubusercontent.com/36746813/116130650-55c60e80-a680-11eb-931e-73d2b84f7a37.png>
