### ISSUE TITLE
Logo constraints

### ISSUE THREAD

**Issue by JurrenG** [MicrosoftDocs/microsoft-365-docs#480]
This page states the logo should be 170x70, but the actual default image is 360x125. Is the documentation wrong or does MS divert from its own guidelines?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b04de3d3-6a94-29f8-3a3d-68ed9422e058
* Version Independent ID: e50fc407-2c78-a3cc-71cd-7978ca340189
* Content: [Add your organization brand to your encrypted messages](https://docs.microsoft.com/nl-nl/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages#feedback)
* Content Source: [microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@JurrenG - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@KCCross - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by KCCross** [comment]
That's unexpected :) 
@samschan-ms - Looks like the graphic we're using doesn't match the guidelines. Can you help me answer the question here?

**Comment by JurrenG** [comment]
I now see a garbeled html statement in the template, a missing < in the background color statement, the mail based on the template now starts with `style="background-color:0xFFFFFF";>`. We didn't change anything, might be an oops trying to correct this? Changing the color doesn't help, we're now trying to create a new template to see if this persists.

**Comment by KCCross** [comment]
Looks like the default template from us no longer contains a graphic. That's on purpose. I'll pass on the oops! In the meantime, just to let you know that I confirmed that the recommended size documented here is in fact the recommended size.

Thanks for keeping us up to date!

**Comment by DanLevin-Git** [comment]
The recommended log size of 170x70 is so small that it is hard to read.  It looks bad-- like a hacker copied and pasted our logo from our website.  Encrypting emails is supposed to give the impression of security but the logo size undercuts that impression.  Microsoft, please re-engage looking into the logo size.
