### ISSUE TITLE
How to Delete Preset Policies?

### ISSUE THREAD

**Issue by toddalbers** [MicrosoftDocs/microsoft-365-docs#4804]
I chose the option to use Preset Policies (Strict).  Now I don't want them.  I can disable them, but can't remove\delete them under each section.  Why can't I delete them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@toddalbers, do you see the "Recommended Settings" policies under their respective policy types at <https://protection.office.com/threatpolicy>?

- [Anti-phishing policies](https://protection.office.com/antiphishing)
- [Anti-spam policies](https://protection.office.com/antispam)
- [Anti-malware policies](https://protection.office.com/antimalwarev2)
- [Safe Attachments policies](https://protection.office.com/safeattachmentv2)
- [Safe Links policies](https://protection.office.com/safelinksv2)

If they are visible, you should be able to delete them.

**Comment by yogkumgit** [comment]
@toddalbers Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
