### ISSUE TITLE
Incorrect instructions for adding an email alias

### ISSUE THREAD

**Issue by martillodecampo** [MicrosoftDocs/microsoft-365-docs#4805]
This sentence is incorrect: "On the Active Users page, select the user > Manage email aliases. "

Instead what I had to do was:

- Select auser in the list of Active Users
- In the header row at the top of the list of users, I clicked on _Manage username and email_
- This opened up a flyout where I was able to manage the email aliases for the user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@martillodecampo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4839

Thanks
Sri
