### ISSUE TITLE
Doesn't tell you what to do if the delist is denied.

### ISSUE THREAD

**Issue by sevenok** [MicrosoftDocs/microsoft-365-docs#4807]
This doc is fairly good until the page tells you that your delist is denied for whatever reason.

Example: [Screenshot](https://prnt.sc/123zvff)

Here, as you can see there is no info about what to do next. In my case I've been waiting for more than 2 months for a message from the Microsoft Support and nothing has came through. 

What should I do next then? I've followed the steps over and over again, about 5 times, waiting for days and then trying again and nothing yet. The same denial message every time.

Really annoying and and disappointing and nowhere I've found (including this doc) what to do to solve this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Remove yourself from the blocked senders list - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@sevenok Thank you for your feedback. Ideally, the Microsoft support team reaches out within 24 hours if the Delist is denied. If that did not happen, Please open a support ticket directly with Microsoft support via the need help section on the administrator to get this sorted.

Thanks
Sri

**Comment by sevenok** [comment]
Hi @msbemba thanks for answering. I'll keep it in mind. I think it will be great to add this to the doc, that way everyone knows how to proceed in case this happens.

**Comment by msbemba** [comment]
@sevenok Were you able to get this resolved after contacting Support?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @sevenok  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
