### ISSUE TITLE
Ansible syntax for key add incorrect and apt source filename shouldn't include .list

### ISSUE THREAD

**Issue by ghgit** [MicrosoftDocs/microsoft-365-docs#4808]
When adding the microsoft key (- name: Add Microsoft APT key)
keyserver is using https url so it should be the [url syntax](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html#examples) and specify the key name:
`    keyserver: https://packages.microsoft.com/`
change to
`    url: https://packages.microsoft.com/keys/microsoft.asc`

Also in the adding the apt repo (- name: Add Microsoft apt repository for MDATP) the filename shouldn't specify the ".list" extension since it is [added by ansible automatically](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html#parameter-filename) (creating .list.list):
`    filename: microsoft-[channel].list`
change to
`    filename: microsoft-[channel]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5b7c531-90a1-7f6b-4c1d-0a126cdea398
* Version Independent ID: 5a10f1bb-6407-d706-0b79-bf448a8eda9d
* Content: [Deploy Microsoft Defender for Endpoint on Linux with Ansible](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-ansible?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-with-ansible.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Thanks for opening this issue @ghgit, submitted PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4809

**Comment by yogkumgit** [comment]
@Dansimp Please share your opinion and help us in resolving the issue and PR. Thanks
