### ISSUE TITLE
No Custom App Launcher Tiles

### ISSUE THREAD

**Issue by jgriff500** [MicrosoftDocs/microsoft-365-docs#4810]
There is no No Custom App Launcher Tiles under Org Settings / Organization Profile as this article states.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9488caf7-b791-3002-8749-7fdc4b2ec8b3
* Version Independent ID: 08e61eb0-7bcd-f449-46ef-17e209138a8e
* Content: [Add custom tiles to the app launcher - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/customize-the-app-launcher?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/customize-the-app-launcher.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@jgriff500 Thank you for your feedback. I have not been able to locate the Customer app launcher as well.  We are internally checking with the Author to confirm if this feature has been removed. Based on the update I shall update the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@twernermsft Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@twernermsft Gentle reminder, please reply. Thanks

**Comment by msbemba** [comment]
@twernermsft  I'm able to locate the "Custom app launcher tiles".

![image](https://user-images.githubusercontent.com/45987684/137161100-32f53025-b1e5-4d17-b0a2-84f717051bf4.png)


@jgriff500 I'm able to look at the option currently. Could you please check again? If it does not show up, I'd recommend you contact Microsoft support via the need help link on the admin center to check if there is an issue with the tenant.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jgriff500 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
