### ISSUE TITLE
MailboxMovePublishedScopes

### ISSUE THREAD

**Issue by ryanfog** [MicrosoftDocs/microsoft-365-docs#4812]
It appears the new security model does not play well with the Organizational Relationship command. I have created a security group in Azure AD both mail enabled and non mail enabled and neither work and give the same error message.

Set-OrganizationRelationship -Identity targettenant_sourcetenant01_3370 -MailboxMovePublishedScopes MailboxesInscope
WARNING: Access scope specified 'MailboxesInscope' is not a security group. This scope will not be added to the organization relationship.

![Impossible to add new security model](https://user-images.githubusercontent.com/25650327/116250976-d6921280-a733-11eb-835f-86508919901a.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@ryanfog Thank you for your feedback. I have been able to test this successfully with a mail-enabled security group. It is strange that you are receiving the warning in spite of the group being a mail-enabled SG. This sounds more like a support issue to me and we request you to contact Microsoft support via the need help button on the Admin center. Post interaction with support, if you feel there are any changes required in the document, please do let us know.

@yogkumgit  No changes to the documentation required as of now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ryanfog Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
