### ISSUE TITLE
Typo on this page "producvitivy score"

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/microsoft-365-docs#4816]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe3e20f-ec8b-1c49-2fb8-25a900533ade
* Version Independent ID: ed13a2a7-ef92-bc3c-d051-c2cfa22b2415
* Content: [Microsoft 365 Network Insights (preview) - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/office-365-network-mac-perf-insights?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/office-365-network-mac-perf-insights.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/office-365-network-mac-perf-insights.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@MSFTEfeedback Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4880

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MSFTEfeedback Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
