### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by csbuja** [MicrosoftDocs/microsoft-365-docs#482]
FollowupFlag not shown in searchable properties in email

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for Content Search](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions#feedback)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@csbuja - We appreciate your efforts to clarify the docs.

Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? 

If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. 

Thank you.

**Comment by mypil** [comment]
@csbuja - We appreciate/value any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.
