### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/microsoft-365-docs#4822]
https://docs.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-licenses-to-multiple-users

In the section "Assign licenses to multiple users" it should be mentioned that the "Active users" page has a limit of 40 users at a time and if you need to assign licenses for a large number of users, such as hundreds or thousands of users, use Powershell or group-based licensing in Azure Active Directory (Azure AD)
https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-groups-assign

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42a261b-afb1-e8d4-e61d-c9d30cb71a00
* Version Independent ID: 3649a463-b7d6-104a-608f-cfcf16b66cb5
* Content: [Assign licenses to users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-licenses-to-multiple-users)
* Content Source: [microsoft-365/admin/manage/assign-licenses-to-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/assign-licenses-to-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@ssmiller60 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4905

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ssmiller60 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
