### ISSUE TITLE
Enabling "Preset Security Policy" (Either Strict or Standard) creates a new Policy in each of the 3 sections that can not be deleted.  Why?  

### ISSUE THREAD

**Issue by toddalbers** [MicrosoftDocs/microsoft-365-docs#4831]
Why is it non-reversible?  You can disable it.  But, why can't you delete it?  If you make the mistake of "Enabling" one of these options, should you be forever committed to having it listed in each of the policy sections forever, even if you don't want it?

Or is something wrong with the "Delete" button on these 3 new "Strict" policies?  I try to delete them, and it lets me try in some cases, but nothing happens.  Other cases the "Delete" button is greyed out and not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@toddalbers, this is already being discussed in #4804. Let's continue the discussion there. Feel free to jump in and comment on the steps I outlined there.

Thanks,

Closing
