### ISSUE TITLE
GRAMMAR ERROR IN DELETING LABEL SECTION

### ISSUE THREAD

**Issue by FamousBern** [MicrosoftDocs/microsoft-365-docs#4832]
Kindly help clarify and correct the following sentence under "removing and deleting label"

Attached is the snip of the section.

![label](https://user-images.githubusercontent.com/32365949/116378477-d7ea3a80-a81a-11eb-9416-a9d8c74af497.PNG)

**Comment by msbemba** [comment]
@FamousBern Thank you for your feedback. We have made changes to the document:-https://docs.microsoft.com/microsoft-365/compliance/create-sensitivity-labels  via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4886

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @FamousBern Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
