### ISSUE TITLE
Safe Docs - test malicous files

### ISSUE THREAD

**Issue by Rkhan-ms** [MicrosoftDocs/microsoft-365-docs#4834]
Hi,

Can someone verify that the files included in this article will actually show up as malicous? I've set this up in my tenant as has my customer and in both instances we are seeing the same resulst. We can open the files even theough the article suggests that they shoul dbe highlighted as malicous.

Thanks in advance,

Ray

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Rkhan-ms, you have the required Microsoft 365 E5 or Microsoft 365 E5 Security licenses, and one of those licenses is assigned to the user that you are testing? And you're testing in Microsoft 365 Apps for enterprise version 2004 or later?

**Comment by yogkumgit** [comment]
@Rkhan-ms Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Rkhan-ms** [comment]
Hi Chrisda and Yogkumgit. 

I have the required M365 E5 as does my customer. And we are testing with M365 Apps version 2004 and later. They are still expereincing the same issue. Can you re-open this case and work further on it with me please?

Thanks,

Ray

**Comment by chrisda** [comment]
@Rkhan-ms, check the following items:

1. SafeDocs must be present in the list services included:
   a. At <https://myaccount.microsoft.com/?ref=MeControl>
   b: And enabled as described in the topic:

     ![image](https://user-images.githubusercontent.com/33166947/117705805-5df27380-b181-11eb-89a6-477cc7faf135.png)

2.  Next, close Word, Excel, and PowerPoint and do these steps:
   a. Go to `%localappdata%\Microsoft\Office\Licenses\5` and delete any license files in this folder.
   b. Start Word, Excel, PowerPoint apps again. This should add new license files to the previous folder location.
   c. Check these registry settings at: `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Common\UrlReputation\UserPolicy\<userid>`

     ![SafeDocsRegSettings](https://user-images.githubusercontent.com/33166947/117706496-394acb80-b182-11eb-983f-d1072b4945f3.png)
3. Try opening one of the test documents.

**Comment by Rkhan-ms** [comment]
Thanks Chris - Checking with my customer today. Will update you later.

**Comment by chrisda** [comment]
@Rkhan-ms: One other thing to try:  when you open the test file does it open in protected view or not? If the file is has been trusted (e.g. no longer considered ‘from the internet’) it won’t open into protected view and thus SafeDocs doesn’t kick in. We've confirm that the test files work in triggering as malicious. Can you manually open the file into protected view: SHIFT+RightClick on the file then select “Open in Protected View” ?

**Comment by Rkhan-ms** [comment]
Hi Chris,

Thanks for this - We have tried the steps you suggested below and still we are not seeing anything being flagged as malicious.

Can you confirm the expected behaviour we should see when we open the file in protected mode? I also don't see any errors when opening up the .ppt file on my Microsoft corp account.

Should we be observing the kinds of warnings observed in the following link?

Safe Documents (microsoft.com)<https://support.microsoft.com/en-us/topic/safe-documents-e2071599-fb31-442b-a30c-198c25e2aacd>

TIA.

Kind Regards,

Ray

**Comment by chrisda** [comment]
@Rkhan-ms, the test files should work as described, so it's time to open a support case and ask why they don't.

**Comment by Rkhan-ms** [comment]
Thanks Chris,

Will do. Thanks for your assistance.

Kind Regards,

Ray

**Comment by yogkumgit** [comment]
@Rkhan-ms Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
