### ISSUE TITLE
The screenshot should be replaced with new one

### ISSUE THREAD

**Issue by mitanabe** [MicrosoftDocs/microsoft-365-docs#484]
The screenshot is different from the current GUI. It should be replaced with new one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn Office 365 audit log search on or off](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off#feedback)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@mitanabe  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@mitanabe @mypil Screenshot in topic is updated. Thanks for the heads up.
