### ISSUE TITLE
Rollout the S/MIME Control at system level to make it work with Microsoft Edge

### ISSUE THREAD

**Issue by joegoerlich** [MicrosoftDocs/microsoft-365-docs#4842]
While the Microsoft's Security Baseline for MS Edge recommends to set the policy 'NativeMessagingUserLevelHost" (Allow user-level native messaging hosts (installed without admin permissions)) to "Disabled", in order to MS Edge can only use native messaging hosts when they are installed at the system level. 
The msi installer seems to not support installing the S/MIME Control on system level but only on user level.
Is there any kind of Enterprise installer for the S/MIME Control which we can use for rollout to our managed clients to still be compliant with Microsofts Security Baseline?

**Comment by yogkumgit** [comment]
@joegoerlich Please indicate which document you are referring to. Thanks

**Comment by joegoerlich** [comment]
Im referring to the Microsoft Security baseline for MS Edge which is part of the Microsoft Security Compliance Toolkit. You can find the latest announcement here: https://techcommunity.microsoft.com/t5/microsoft-security-baselines/security-baseline-for-microsoft-edge-version-90/ba-p/2275943

**Comment by msbemba** [comment]
@joegoerlich Thank you for your feedback. This sounds more like a support-related query. We request you to contact Support via the need help section on your M365 admin center.

@yogkumgit The issue can be closed as this is a support-related question.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @joegoerlich Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
