### ISSUE TITLE
Adding Teams.live.com to the list

### ISSUE THREAD

**Issue by jamilhaddadin** [MicrosoftDocs/microsoft-365-docs#4846]
It might be a good idea to add teams.live.com to the list of Urls, this links is needed when an MS Teams Consumer user creates a meeting and Office 365 Teams users wants to join.
I totally understand that MS Teams consumer is a different product, but you have already added a list of optional URLs for other products (outlook.com) so it might be acceptable to add teams.live.com here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft and @LauraWi Please help us in resolving this issue

**Comment by LauraWi** [comment]
Following up with @jamilhaddadin via internal channels regarding the process for updating this article and getting teams onboarded to the endpoint process.
