### ISSUE TITLE
Wildcard examples

### ISSUE THREAD

**Issue by eepyaich** [MicrosoftDocs/microsoft-365-docs#485]
Your wildcard example `*contoso.com*` is useful.  However, it seems this could be abused by an attacker to register the domain "fakecontoso.com" and have their links passed.  Does an example of `*.contoso.com*` work better?  Does this even work in the filter?
In fact, maybe this would still allow attacks of the form "www.fake.contoso.completelyfake.com"?  What's the best advice?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac84f75-b6d9-9495-873a-8f87b90b8034
* Version Independent ID: 18369495-0e0f-e3e1-6945-0200790fd107
* Content: [Set up a custom do-not-rewrite URLs list using Office 365 ATP Safe Links](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@eepyaich  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by eepyaich** [comment]
FWIW - I've actually configured the rules on my site to *.contoso.com/*.  This seems to actually work well (and guards against the "fakery" I was suggesting).

**Comment by mypil** [comment]
@eepyaich - Based on your last comment, you mentioned that you configured the rules on your site to .contoso.com/ which worked well. We hope this means that your issue has been resolved. 

Please feel free to re-open this issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you!

**Comment by eepyaich** [comment]
While I've managed to resolve my configuration, the real issue here was that the documentation was not as helpful as it could have been.

It's obviously up to you, but I would suggest that an example of `*.contoso.com/*` would be a useful addition.

[Note that my previous comments seemed to "lose" the wildcards!]

**Comment by mypil** [comment]
@eepyaich - We value collaboration and appreciate your efforts to clarify the docs.
Could you please assist us by providing more details on how this content could be edited to incorporate your feedback? If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by MaratMussabekov** [comment]
hello @eepyaich 
please have a look at the PR I have created
**the bullet beginning "Do not include a forward slash..." should be removed or replaced** - could you please explain why you recommend it to be removed/replaced?

Thank you

**Comment by eepyaich** [comment]
I've had a look at the PR and made a comment.  
The point about the second bullet is that, as per the example I'm suggesting, I don't think it is correct to say "don't use forward slashes" as we've now come up with some examples where a forward slash is useful.

Fundamentally, I think you need to have someone who actually understands the code behind this feature confirm what sensible examples and text should be.  I'm just an end user and noted that the examples as they were could allow someone to create a URL which would be whitelisted while clearly being fraudulent (e.g. `http://www.fake.contoso.completelyfake.com` which would match the original example of `*contoso.com*`).

**Comment by MaratMussabekov** [comment]
Hello @eepyaich ,
I've seen your comments to the PR, but I am not sure whether *.contoso.com/* makes http://www.contoso.com unavailable. From my experience it works ok (if I allow *.contoso.com/* users can access http://www.contoso.com, if I allow http://contoso.com/a/* users can access http://contoso.com/a, etc.)
Anyways, lets contact the author.
Dear @MSFTTracyP, could you please have a look?

Thank you

**Comment by being-a-geek** [comment]
Has anyone looked at this and gotten clarification? We're currently in the same boat and wondering whether it's safer to whitelist *.blahblah.com/* or are we okay with whitelisting *blah.com*

**Comment by eepyaich** [comment]
@being-a-geek - good question!  All I'll say is that we went for whitelisting the `*.blahblah.com/*` format and it seems to work for us.

**Comment by chrisda** [comment]
@eepyaich, your comments and critiques of the previous PR make sense to me, so I basically removed that bullet about forward slashes, and I added more explanation text about the potential evils of `*contoso.com*`. We know 100% that `*.contoso.com/*` eliminates that potential issue, so what's the benefit of using `*contoso.com*`? None, he said, answering his own question, so we shouldn't advocate using it.

Thanks for the feedback.

**Comment by kevintaber** [comment]
Keep in mind I think the list will need two entries to handle situations where www is included and sometimes isn't.

Meaning if you didn't want to re-write either of these sites, including potential paths:
https://contoso.com and https://www.contoso.com

*.contoso.com/* 
https://contoso.com/*
