### ISSUE TITLE
Add more information about retention limitations for private channels

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4851]
In the section called 'Retention Polices for Teams section' there is a brief mention in point 3 that mentions that retention policies do not apply to private channels. Please add the following information to provide more details 

Teams messages in private channels are currently not supported for retention policies. Code snippets, recorded voice memos from the Teams mobile client, thumbnails, announcement images, and reactions from others in the form of emoticons are not retained when you use retention policies for Teams. Cross reference to https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide for more information
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef663fdc-1776-3c73-7743-332796c284e6
* Version Independent ID: ceb29788-39be-8c30-b92a-7a22243ebe83
* Content: [Create and configure retention policies to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4887

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
