### ISSUE TITLE
Before the 'filter' should insert '`'

### ISSUE THREAD

**Issue by banhao** [MicrosoftDocs/microsoft-365-docs#4853]
** Before the 'filter' should insert '`' **

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72110011-1fc5-4e78-8e54-e43bc181b860
* Version Independent ID: c974e3d8-983a-02d4-d9dc-9603a3f8b510
* Content: [OData queries with Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-odata-samples?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/exposed-apis-odata-samples.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/exposed-apis-odata-samples.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@banhao Thank you for your feedback.I see other issues in the document which I will be fixing shortly, Can you elaborate on which example  "`"  is missing? 

Thanks
Sri

**Comment by banhao** [comment]
@msbemba In the online document, the example is like following:
'''
HTTP GET  https://api.securitycenter.microsoft.com/api/machines?$filter=startswith(computerDnsName,'mymachine')
'''

But when I used PowerShell to test it, the URL is like following: 
'''
$url = "https://api.securitycenter.microsoft.com/api/machines?`$filter=startswith(computerDnsName,'$ComputerName')"
'''

I spent lots of time to figure it out that when using the "OData Queries" need to insert '`' before the $filter.
