### ISSUE TITLE
Constancy in time quoted for restricted users documentation.  

### ISSUE THREAD

**Issue by leifdavisson** [MicrosoftDocs/microsoft-365-docs#4854]
I have seen several different time amount given 1 hour, 3-4 hours. What is the amount of time it takes to unblock a user? Can we update the restricted dialog and documentation to match on the time? Can we just change them all to 24 hours that way the user knows not to send mass email from their mailbox. 

Protection>Restricted Users said 1 hour

Admin Center>Get Help said 3-4 hours
![image](https://user-images.githubusercontent.com/8397918/116623789-a4331180-a8fb-11eb-98ef-aa4b8bde5332.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c17e50d-aa8f-bd30-66af-ef4d63f02402
* Version Independent ID: 92cbda3f-c3a9-ed20-2038-7e966f491934
* Content: [Remove blocked users from the Restricted Users portal - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@leifdavisson Thank you for your feedback. The document has been updated with a note stating that it could up to 24 hours for all restrictions to be removed from the user. While we see Majority of the time it takes less than 4 hours for the user to start sending emails, so the get-help numbers cannot be changed.

Thanks
Sri

**Comment by leifdavisson** [comment]
Thanks #Close

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @leifdavisson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
