### ISSUE TITLE
HOW Does One "Send As"

### ISSUE THREAD

**Issue by MHCLV** [MicrosoftDocs/microsoft-365-docs#4855]
This article omits any reference or link on how one actually uses "Send As" of "Send on Behalf Of".   Put another way, now that I have permission to do this, how do I actually do it?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b725ac58-0fa5-9f7d-84fa-a8541477fe0e
* Version Independent ID: f2acd0d0-60b8-0744-e241-06fb753aa5d1
* Content: [Allow members to send as or send on behalf of a group](https://docs.microsoft.com/en-us/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@MHCLV Thank you for your feedback. We have added a related article to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4906

The document - https://docs.microsoft.com/en-us/microsoft-365/admin/manage/send-email-as-distribution-list?view=o365-worldwide has instructions to send as a Distribution list.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@MHCLV Thank you for your feedback. The author confirmed that a Tip has now been added to the document which talks about how to Send as a group.

@yogkumgit There are no more changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MHCLV Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
