### ISSUE TITLE
Set up multi-factor authentication

### ISSUE THREAD

**Issue by alareed** [MicrosoftDocs/microsoft-365-docs#4858]
Not a big deal although maybe see if what got me is something that could be a problem, could have just been one of thosee dys for me also. LOL.

Having these two paragraphs 

- [Link](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#turn-on-modern-authentication-for-your-organization)
- [Link](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#turn-off-legacy-per-user-mfa)

at the bottom of the page, within the workflow, had me a little turned around _especially since_ the first item to do
_(same page 2nd paragraph [Link](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#before-you-begin))_
is to **"Turn off legacy per-user MFA"**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide#turn-off-legacy-per-user-mfa)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@alareed Thank you for your feedback. Ideally, the Turn off Legacy per-user MFA should be a part of the Before you being section (linked). I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4909

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @alareed Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
