### ISSUE TITLE
Teams powershell cmlet does not include all skype cmlets : New-CsOnlineVoiceRoute / Set-CsUse

### ISSUE THREAD

**Issue by dana23746** [MicrosoftDocs/microsoft-365-docs#4859]
Hey, 

Facing issue while trying to set up SBC within teams. 
As i am no longer able to download the skype module, i've tryed to do it directly from teams, but cmlets are missing. 

module version : 
2.3.0      MicrosoftTeams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289b637a-ad53-2710-3b6e-7f4ac15916fa
* Version Independent ID: e8de4044-38f3-1002-9816-12515d0cdda0
* Content: [Manage Skype for Business Online with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@dana23746 Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. As we can address here only the issues, pertaining to document update. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
