### ISSUE TITLE
What does EFV:NLI means?

### ISSUE THREAD

**Issue by Yanal-Yves** [MicrosoftDocs/microsoft-365-docs#486]
Hello,

Emails I am trying to send from my custom domain ends in outlook.com with this header:

`X-Forefront-Antispam-Report: EFV:NLI`

Could you elaborate on the EFV:NLI so that I can "Determine the reason why the message was marked as spam" ?

Have a good day !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbab747e-1a43-037e-09ca-9c402deec602
* Version Independent ID: 1c6d8e28-034d-24d6-5732-b96475411d6b
* Content: [How to prevent false positives from happening in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/prevent-email-from-being-marked-as-spam#targetText=SFV%3ASPM%20Indicates%20that%20the,prior%20to%20the%20content%20filter.)
* Content Source: [microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by mypil** [comment]
@Yanal-Yves  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @Yanal-Yves , have you tried any option from https://answers.microsoft.com/en-us/outlook_com/forum/all/email-ist-going-to-junk-folder-although-antispam/08262593-ef1a-4436-8a23-182ca43015ff

I would recommend you to open up a support case with Office365 support team for its further investigation. I would recommend checking if your domain not marked as blacklist on the internet.  For this purpose you can use any domain blacklist check tool.

Regards,
Imran.

**Comment by mypil** [comment]
@Yanal-Yves - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by leonNL** [comment]
@mypil , 
I don't think that the question "What does EFV:NLI mean?" has been answered.
Where does EFV:NLI stand for? And what triggers it?
I am having the same issue as @Yanal-Yves

**Comment by mypil** [comment]
@Yanal-Yves @leonNL - I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by Yanal-Yves** [comment]
@joinimran, the link you are suggesting didn't help me to get the meaning of `X-Forefront-Antispam-Report: EFV:NLI`.

1. SPF and DKIM are correctly configured according to mail-tester.com.
2. Our email provider is maiJet and according to the dashboard our domain is correctly configured.
3. Emails sent from our domain are not falling in Gmail spam

I read somewhere that using a new IP to send emails is a reason to fall in the outlook spam.

So I will wait and see if our emails continue to fall in the spam.

Anyway, I wasn't raising an issue to get support for my particular issue but simply get the anti spam report directive documented for the community and then maybe I was hopping to find a solution for my particular problem.

Do you guys at Microsoft knows what `X-Forefront-Antispam-Report: EFV:NLI` means?

**Comment by anyITsolution** [comment]
Did you review the EOP codes on this link? https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers

**Comment by LauraWi** [comment]
Hi @Yanal-Yves Any headers not documented here (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers) are internal and used exclusively by the Microsoft anti-spam team for diagnostic purposes.

**Comment by leonNL** [comment]
@LauraWi (Principal Content Experience Manager at Microsoft)
Are you stating that EFV:NLI is only for DIAGNOSTIC reasons and does is NOT has effect how mail are handled (e.g. Outlook) and that it NOT causes the mail to arrive in unwanted messages folder?

**Comment by Yanal-Yves** [comment]
@LauraWi, so if any hearders not documented in the page you mentioned is internal, maybe the resolution for this ticket is to add this information to the wiki page. That would avoid (or at list limit) this kind of ticket in the future :-).

**Comment by LauraWi** [comment]
Hi Yanal -- The topic already includes this information in the statement " Other fields in this header are used exclusively by the Microsoft anti-spam team for diagnostic purposes." But we can look at making the information more prominent (perhaps in a note), if confusion persists. Thanks.
