### ISSUE TITLE
Identify new/modified/removed entries

### ISSUE THREAD

**Issue by AndrewWarriner** [MicrosoftDocs/microsoft-365-docs#4860]
[Enter feedback here]
Can this page with URL list be modified to highlighting (or some other method) to make it clear which entries are new/modified/removed - highlighting them in some way would make it easier/quicker to identify changes.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@AndrewWarriner Thank you for your feedback. I have looked at the document and this is a VERY highly structured reference topic that is to be used as a dictionary and is maintained by the engineering team. This cannot be modified at this point in time.

@yogkumgit There are no changes required in the document at this point in time.

Thanks
Sri

**Comment by AndrewWarriner** [comment]
Thanks for your response anyway, appreciate it.
