### ISSUE TITLE
CSV Import for LAN subnet office locations

### ISSUE THREAD

**Issue by bilginbaldji** [MicrosoftDocs/microsoft-365-docs#4863]
[Enter feedback here]
4 b. CSV import fails if value is entered in the Name column with error "Location id/name can't be edited.". The article defines the column as required.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e748ed-63fe-0d00-6b60-c1a778797afa
* Version Independent ID: 3cd66c90-ed09-7c28-7dbb-0a11769f8033
* Content: [Network connectivity in the Microsoft 365 Admin Center (preview) - Microsoft 365 Enterprise](https://docs.microsoft.com/en-GB/microsoft-365/enterprise/office-365-network-mac-perf-overview?view=o365-worldwide#pre-requisites-for-network-connectivity-assessments-to-appear?WT.mc_id=365AdminCSH_inproduct)
* Content Source: [microsoft-365/enterprise/office-365-network-mac-perf-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/office-365-network-mac-perf-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@bilginbaldji Thank you for your feedback. I was able to test and import the file with the name field. Make sure that the userenetered value is set to 1. If you still have issues, I would recommend contacting Microsoft support via the need help link in the admin center.

![image](https://user-images.githubusercontent.com/45987684/118382789-6bdb4500-b616-11eb-8f75-b89b9795e852.png)

![image](https://user-images.githubusercontent.com/45987684/118382784-63830a00-b616-11eb-858a-7c087e51595d.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bilginbaldji Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
