### ISSUE TITLE
Shifted columns 

### ISSUE THREAD

**Issue by artemterentyev** [MicrosoftDocs/microsoft-365-docs#4864]
It looks like values in sub-category rows of the subscription table should be shifted one column to the right.
![image](https://user-images.githubusercontent.com/83510751/116789605-7c12f200-aa64-11eb-82be-91fdcec00437.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a802bdc-9d61-ea4e-6161-46e67fa78681
* Version Independent ID: df81ea65-84e0-a8a6-ae65-d5658a7af5e5
* Content: [Choose a Microsoft 365 subscription](https://docs.microsoft.com/en-us/microsoft-365/business-video/choose-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/choose-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/choose-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@artemterentyev Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4911

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @artemterentyev Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
