### ISSUE TITLE
Screenshots are not clear

### ISSUE THREAD

**Issue by sandeepmzc** [MicrosoftDocs/microsoft-365-docs#4865]
It would be helpful If these screenshots have a zoom option. Currently, it's difficult to see it clear unless I Zoom the full page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6713dbeb-b6cf-eaf3-58a9-ffb8a9b5e858
* Version Independent ID: 858c0b49-3ffa-7bb0-9a0c-4b81b89b08c9
* Content: [Microsoft Compliance Manager - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Thank you for this feedback. We currently don't have a zoom option but we will look into creating the size of these screenshots.
