### ISSUE TITLE
Required DNS Settings (Can't find MX records) doesn't exist

### ISSUE THREAD

**Issue by friek108** [MicrosoftDocs/microsoft-365-docs#4867]
There is no option: "Required DNS settings" - doesn't exist anywhere or it's impossible to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 854cbadf-a802-0782-5a3a-b839995ff7fd
* Version Independent ID: b511466a-2505-4e90-548c-3fa5b6f2aedc
* Content: [Gather the information you need to create DNS records - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/information-for-dns-records?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/information-for-dns-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/information-for-dns-records.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@friek108 Thank you for your feedback. The options have changed and we have made those changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4912

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @friek108 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
