### ISSUE TITLE
Assign a DEP to a mailbox in hybrid environment

### ISSUE THREAD

**Issue by IdahoR** [MicrosoftDocs/microsoft-365-docs#487]
Could you please provide instructions to assign a DEP to a mailbox in a hybrid environment where directory sync means that mailbox attributes are managed from on-prem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a585eca1-dad6-3afd-43ce-8c4b11102dd3
* Version Independent ID: a1d708a7-774f-0c23-b428-28919ef5d46a
* Content: [Controlling your data in Office 365 using Customer Key](https://docs.microsoft.com/en-us/microsoft-365/compliance/controlling-your-data-using-customer-key#office-365-setting-up-customer-key-for-exchange-online-and-skype-for-business)
* Content Source: [microsoft-365/compliance/controlling-your-data-using-customer-key.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/controlling-your-data-using-customer-key.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@IdahoR  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@IdahoR - Thank you for your message, Please note DEP is only applicable on Office365 online. You can't manage them from on-prem.

You can your feedback using the user voice channel.

@mypil FYI please.

**Comment by mypil** [comment]
@IdahoR - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in 
**[User Voice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
