### ISSUE TITLE
There is no clear information about licensing requirements for Cortana

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/microsoft-365-docs#4876]
There is no clear information  about licensing requirements for Cortana, also no detailed information about activating Cortana in Outlook and Teams clients

**Comment by yogkumgit** [comment]
@Balamurugan-dot Please indicate which document you are referring to and having improvement feedback. Thanks

**Comment by Balamurugan-dot** [comment]
Hi Yogesh,

I'm talking about this documentation<https://docs.microsoft.com/en-us/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide>.

Thanks!

Regards,
B.G

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by Balamurugan-dot** [comment]
Do we have any updates on this please?

Regards,
B.G

From: Balamurugan Ganesan
Sent: Monday, May 3, 2021 9:21 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>; MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] There is no clear information about licensing requirements for Cortana (#4876)

Hi Yogesh,

I'm talking about this documentation<https://docs.microsoft.com/en-us/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide>.

Thanks!

Regards,
B.G

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder.

**Comment by yogkumgit** [comment]
@Balamurugan-dot Forwarded to Cortana team. They will address. Thanks for your feedback. Closing.
