### ISSUE TITLE
Unclear about Office 365

### ISSUE THREAD

**Issue by Floriszz** [MicrosoftDocs/microsoft-365-docs#4878]
[Enter feedback here]
The url below shows in the left menu; 'MFA for Office 365', which is linked to this page. But on this page there is no mentioning about 'Office 365', only 'Microsoft 365'.
https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-mfa-licensing

https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication
is redirected to this link below:
https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide

From many different sites and sources it tells me that 'Office 365' is not completely the same as 'Microsoft-365', is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multi-factor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Floriszz Thank you for your feedback. As of April 21, 2020, the official branding of Microsoft's productivity suite has changed from Office 365 to just Microsoft 365. The new naming convention reflects Microsoft's strategy of providing a single complete productivity platform for its customers. So there are no changes required in the document - https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication as it is updated.

We request you to hit the feedback button on ttps://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-mfa-licensing and open an issue, they should be able to fix the wordings on the Azure document.

Thanks
Sri

**Comment by Floriszz** [comment]
Dear,
Does that mean there is no difference between Office 365 E3 and Microsoft 365 E3 subscription!? According to other resources there is a difference exactly in regards to EMS included or not and of course the pricing.
So just renaming is not the case, is it?
________________________________

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Floriszz Office 365 as a service has been rebranded as MIcrosoft 365.

**Comment by msbemba** [comment]
@Floriszz Thank you for your feedback. That is a good question. Office 365 as a service has been rebranded as Microsoft 365. Below are the changes you will see in the name of the subscriptions

Some Office 365 subscriptions automatically become Microsoft 365 subscriptions. No action required if you had older licenses.

Office 365 Personal becomes Microsoft 365 Personal.
Office 365 Home becomes Microsoft 365 Family.
Office 365 Business Essentials becomes Microsoft 365 Business Basic.
Office 365 Business Premium becomes Microsoft 365 Business Standard.
Microsoft 365 Business becomes Microsoft 365 Business Premium.
Office 365 Business becomes Microsoft 365 Apps for business.
Office 365 ProPlus becomes Microsoft 365 Apps for enterprise.
 

There are no changes to the following Office 365 for enterprise plans:

Office 365 E1
Office 365 E3
Office 365 E5

The equivalent M365  E3 and E5 versions Includes the security services and rights to Windows 10 Enterprise. But to answer your question, in general, the service which was called Office 365 is now Microsoft 365, However these subscriptions Office 365 e1,e3 and e5 still exist.

Hope this helps!

**Comment by Floriszz** [comment]
Thank you. I left my feedback as suggested to the first document url. As it is unclear what level of MFA is included in 'Office 365'.
