### ISSUE TITLE
Check for EvoSts Auth server powershell line is not correct

### ISSUE THREAD

**Issue by gbriem** [MicrosoftDocs/microsoft-365-docs#4879]
Hi !,

It states to check the authserver with command:

Get-AuthServer | where {$_.Name -eq "EvoSts"}

Which returns nothing even when it's correctly implemented.

It should be:

Get-AuthServer | where {$_.Name -like "EvoSts*"}

**Comment by gbriem** [comment]
Maybe even better:
Get-AuthServer | where {$_.Name -like "EvoSts*"} | ft Name,IsDefaultAuthorizationEndpoint,Enabled

**Comment by yogkumgit** [comment]
@gbriem  Please indicate which document you are referring to and having improvement feedback. Thanks

**Comment by gbriem** [comment]
Hi,

Document:
https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication?view=o365-worldwide

I think my suggestion is applicable if the oauth config is done by the Exchange hybrid wizard.





​Met vriendelijke groet / With kind regards / Mit freundliche Grüssen,
 
Guido Briem
Noorderpoort 69, 5916 PJ Venlo - Postbus 213, 5900 AE Venlo
t: +31 77 472 00 15 | m: +31 6 13 40 43 24
e: gbriem@Insign.it | w: www.insign.it

ISO 9001 and ISO 27001 certified by BSI under certificate numbers QSC778, ISC161
​

**Comment by msbemba** [comment]
@gbriem Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4914

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gbriem Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
