### ISSUE TITLE
the link to unblock a user is dead

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#488]
https://docs.microsoft.com/en-us/office-365-security/securitycompliance/removing-user-from-restricted-users-portal-after-spam
should be
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68b20762-e3ee-6aa6-7460-5bc7214fd00e
* Version Independent ID: 641814b7-9c30-2119-e5f9-7983118e102f
* Content: [Responding to a Compromised Email Account in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/responding-to-a-compromised-email-account)
* Content Source: [microsoft-365/compliance/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/responding-to-a-compromised-email-account.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@Mike-Crowley  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Mike-Crowley - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
