### ISSUE TITLE
Page does not contain information as listed from another page. 

### ISSUE THREAD

**Issue by staylor130** [MicrosoftDocs/microsoft-365-docs#4881]
[Enter feedback here]
This page is referenced by page: 
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide
to learn how to "Create DNS records for Microsoft 365 when you manage your DNS records."  However this page does not provide information on how to create the DMARC record and even points back to referenced page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f2e4e45-6ad7-eb79-aecb-0d7a89b06a03
* Version Independent ID: 1059223e-5759-b130-41ac-5ea98cb5367e
* Content: [Add DNS records to connect your domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@staylor130 Thank you for your feedback. You are right, The link does not help in adding a DMARC record on your DNS host, I'll proceed with removing the statement, however, there are instructions to create a DMARC record (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide#best-practices-for-implementing-dmarc-in-microsoft-365)

once you have formed your record, you need to update the record at your domain registrar. (Instructions cannot be added as it depends on the domain registrar)

I have created to PR to remove the link from the document. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4936

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @staylor130 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
