### ISSUE TITLE
Link to uservoice no longer accurate

### ISSUE THREAD

**Issue by turnma** [MicrosoftDocs/microsoft-365-docs#4893]
Page links to uservoice for making suggestions about future Lockbox product scope.  However, uservoice page now states that is is effectively no longer active.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by LauraWi** [comment]
Current experience is intentional. In the meantime, the page customers are taken to for product feedback does provide other channels they can use to provide feedback.
