### ISSUE TITLE
Article misleading - received further information from engineering team

### ISSUE THREAD

**Issue by SDkempf94** [MicrosoftDocs/microsoft-365-docs#4895]
Hi Team

We've received feedback from a customer that they wanted to have more explicitly clear in this documentation under the unsupported browsers section. 
During troubleshooting we discovered that DLP policies only work with Microsoft Edge Chromium and it's the only supported browser - please can you make this explicitly clear in the documentation?

Even if you configure the policy on Chromium edge, if your users are not using chromium edge, then it's DLP is ignored.

Kind regards

Sebastian 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76da4eda-4ccf-ff34-6a48-d9c5553c2ed6
* Version Independent ID: 7e887aff-1b85-1651-2bff-63425c54ae63
* Content: [Using  Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-using?view=o365-worldwide&source=docs#unallowed-browsers)
* Content Source: [microsoft-365/compliance/endpoint-dlp-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-using.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
HI @SDkempf94
Thanks for your comment. For your customers information, all the requirements are clearly stated in Prepare your Endpoints  https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide#prepare-your-endpoints
