### ISSUE TITLE
Booking Link Availability Incorrect

### ISSUE THREAD

**Issue by dcccpavitras** [MicrosoftDocs/microsoft-365-docs#4897]
Using the custom availability option, I set specific hours, but they are not appearing in the booking link. 

![image](https://user-images.githubusercontent.com/83669459/117055961-c48f1180-ace9-11eb-8ce4-3abfae61f562.png)

![image](https://user-images.githubusercontent.com/83669459/117056020-d40e5a80-ace9-11eb-9b23-027ddf2308b2.png)

**Comment by msbemba** [comment]
@dcccpavitras Thank you for your feedback. Let me test this and update you. Meanwhile, do you have a document that refers to these steps that you are following?

Thanks
Sro

**Comment by dcccpavitras** [comment]
I do not have a document other than the screenshots I attached

**Comment by msbemba** [comment]
@dcccpavitras Thank you for your feedback. This sounds more like a support issue as per my testing it works accurately on other tenants. You can create a support ticket via the need help option on the admin center and a Microsoft support representative will be able to take this forward.

@yogkumgit  There are no changes required, We can proceed with closing the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dcccpavitras Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
