### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by PhilStollery** [MicrosoftDocs/microsoft-365-docs#4899]
This page seems to be incomplete: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prepare-deployment?view=o365-worldwide#environment

There is a description column in the table, but no description provided for each entry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c20ab25-de01-7794-8025-43c3f859e272
* Version Independent ID: bd4264bb-cca6-7fc4-45bc-c94e519c06cc
* Content: [Prepare Microsoft Defender for Endpoint deployment](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prepare-deployment?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prepare-deployment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prepare-deployment.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Thank you for the feedback. Will update the page with the missing info.
