### ISSUE TITLE
ATP SA Dynamic Delivery with inbox rules to move messages to other mailbox folder

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#4900]
This article needs an update it seems in regards to the part about the limitations of Dynamic Delivery. It says that it won't work when emails are forwarded out of the cloud mailbox but according to previous escalation Dynamic Delivery also doesn't work when inbox rules move the email to a different folder than the inbox. See: [link redacted]. Receiving cases about this in support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5966b7b-cbaa-eaa2-c9d6-5c6e7218df74
* Version Independent ID: cfcc8772-be5d-009a-0805-62624835ac5f
* Content: [Safe Attachments - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-attachments?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-attachments.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeroenDronkers, I updated the topic.

Thanks for the feedback.

Closing
