### ISSUE TITLE
Remember Outlook The Program??

### ISSUE THREAD

**Issue by MHCLV** [MicrosoftDocs/microsoft-365-docs#4907]
This article is only half complete because it offers no information on how to accomplish the subject task from Outlook the program.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce15c00-cd78-c0d9-985f-bd17206e1d50
* Version Independent ID: e958aac9-a604-6ff6-acc5-e2e172b821c2
* Content: [Send email as a distribution list - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/send-email-as-distribution-list?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/send-email-as-distribution-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/send-email-as-distribution-list.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@MHCLV Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4960

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MHCLV Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
