### ISSUE TITLE
Need information about the Update Type in Improvement actions for secure score

### ISSUE THREAD

**Issue by mlamberty** [MicrosoftDocs/microsoft-365-docs#4915]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a2c77d-f8c2-b663-57a1-1b1ec8565e89
* Version Independent ID: 69cc2b0f-d0d0-d4b1-8cb9-13c246d67e70
* Content: [Assess your security posture through Microsoft Secure Score](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score-improvement-actions?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-secure-score-improvement-actions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-secure-score-improvement-actions.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@mlamberty Thank you for your feedback. There are two types of "Update Type" In improvement actions

1)Microsoft added Actions
2)Microsoft Updated action points

1) Microsoft added actions mean that Microsoft has added an improvement action for a service - For example https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score-whats-new?view=o365-worldwide#added-six-accounts-related-improvement-actions-for-microsoft-defender-for-endpoint

2) MIcrosoft updated action points means that Microst has updated an existing action point- For example https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score-whats-new?view=o365-worldwide#updated-improvement-action-for-azure-active-directory

You can follow the Article - What's new in Microsoft Secure Score ( https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score-whats-new?view=o365-worldwide) to understand If Microsoft has Added an action or updated an existing action point.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mlamberty Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
