### ISSUE TITLE
There is no clear information about licensing requirements for Cortana, also no detailed information about activating Cortana in Outlook and Teams clients

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/microsoft-365-docs#4920]
There is no clear information about licensing requirements for Cortana, also no detailed information about activating Cortana in Outlook and Teams clients

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad4b3d3-b509-c6c6-e842-b53c68100c4e
* Version Independent ID: ec63705a-7ce3-abf6-5f4f-fe5bc95bc9b8
* Content: [Cortana in Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/cortana-integration?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/cortana-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/cortana-integration.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Balamurugan-dot Thank you for your feedback. We have added the information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4987

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Balamurugan-dot Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
