### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by geo2mac** [MicrosoftDocs/microsoft-365-docs#4921]
The page references a URL with German TLD. See highlighted pic

![image](https://user-images.githubusercontent.com/54373200/117296611-421a6500-ae43-11eb-9250-c96627a91685.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83719909-241b-2902-5ff1-496934da24e3
* Version Independent ID: d05e079d-f0d6-11ac-577c-f407cc49fcb7
* Content: [Add users and assign licenses - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/add-users?redirectSourcePath=%252farticle%252f997596b5-4173-4627-b915-36abac6786dc&view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/add-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
This was a due to a markdown error, which I have fixed.
