### ISSUE TITLE
Bad Link in Referenced Workbook

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#4923]
The excel workbook references an internal domain (https://review.docs.microsoft.com/). This results in a forbidden error for users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Define information barrier policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide#prerequisites)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by danmyhre** [comment]
Yes, in the workbook you can download from github (https://github.com/MicrosoftDocs/OfficeDocs-O365SecComp/raw/public/SecurityCompliance/media/InfoBarriers-PowerShellGenerator.xlsx)

The link for "See this article for the list of attributes:" points to https://**review**.docs.microsoft.com/en-us/Office365/SecurityCompliance/information-barriers-attributes?branch=infobarriers-working

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@danmyhre Thank you for the information. We are looking into this and will test and update the URL.

Thanks
Sri

**Comment by robmazz** [comment]
@danmyhre - thanks for your feedback. This workbook is being deprecated, please use the example scenario guidance in the Define information barrier policies topic (https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies). Thanks!
