### ISSUE TITLE
Clarification - if endpoint is already onboarded to MDE - you do not need to  re-onboard

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/microsoft-365-docs#4926]
Can we update the onboarding section to reflect if the endpoint is already onboarded to MDE - you don't have to redeploy MDE - you just need to turn on the service integration?

https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?source=docs&view=o365-worldwide#with-devices-onboarded-into-microsoft-defender-for-endpoint

Maybe something like:
If the endpoint is already onboarded to MDE - you simply need to configure the service side integration from https://compliance.microsoft.com in Settings>Device Onboarding>Devices and select "Turn on Device Onboarding"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?source=docs&view=o365-worldwide#with-devices-onboarded-into-microsoft-defender-for-endpoint)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
the article already states this
