### ISSUE TITLE
missing code to update IOC

### ISSUE THREAD

**Issue by sanderdewit** [MicrosoftDocs/microsoft-365-docs#4927]
The page describes how to add IOCs and this works perfectly.
However updating van Indicator seems to be not possible, it will always create a new one.

Please provide some examples if updating is possible.
if updating is not possible, please change the page name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea229ca-05ce-38c5-003e-4d811b0bed25
* Version Independent ID: 765b3d95-745c-357b-b19e-87ee0b0a1661
* Content: [Submit or Update Indicator API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/post-ti-indicator?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/post-ti-indicator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/post-ti-indicator.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@mjcaparas Gentle reminder. Please.

**Comment by mjcaparas** [comment]
Checking with team

**Comment by mjcaparas** [comment]
@sanderdewit 
According to the team:

If you submit a 2nd indicator with the same: IndicatorValue, IndicatorType, action and rbacGroups. It will edit the same indicator. 

If you change one of those properties, it will create a new one.
