### ISSUE TITLE
Running the Test

### ISSUE THREAD

**Issue by MIkeMIP** [MicrosoftDocs/microsoft-365-docs#493]
Receiving an error when trying to run test unless signed in as a global admin. are their other roles that could run this test?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb7953e-5257-2578-4607-2d93940d6845
* Version Independent ID: 8e59d041-619e-d54f-f28e-faac2bc18ef2
* Content: [Create a custom sensitive information type in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type#feedback)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by lorenzocastro** [comment]
Same here, would expect security admin to be able to run these?

**Comment by mypil** [comment]
@MIkeMIP @cloud-e-lc - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@mlkem Can you please share error details so that we can better help you.

Regards,
Imran.

**Comment by mypil** [comment]
@MIkeMIP - We would like to follow up. Can you please answer the query of joinimran?

Thank you.

**Comment by MIkeMIP** [comment]
It is an unauthorized error: (Because i am not a global admin, this should be something a Security Admin or Information Protection admin can do also though, being that they set all of this up usually.)
Request: /api/DlpTestCustomClassification
Status code: 403
Exception: System.UnauthorizedAccessException
Diagnostic information: {Version:17.00.3576.009,Environment:WUSPROD,DeploymentId:1a8a677ec0c840078c9e0642f8e2d59f,InstanceId:WebRole_IN_2,SID:e3d2dc9b-0f72-4c19-b5eb-bf132c9ed93e,CID:0716c18a-f46a-43d5-9652-98ace51296fe}
Time: 2019-10-09T13:14:54.4599138Z

**Comment by joinimran** [comment]
@MIkeMIP I would recommend you to contact your Global Admin to give you the necessary permissions so that you can run this test.

Additionally, please see https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-dlp-policy-recommendations for more details.

Regards,
Imran.

**Comment by cloud-e-lc** [comment]
I was able to confirm that you need compliance admin to test information
types.  You need to define this in the azure portal as the role in the scc
will not work.  Seems illogical that the security admin can manage the
lifecycle with the exception of testing.

**Comment by joinimran** [comment]
In such a case, I would request you to use the user voice channel to send your feedback to the respective teams.

@mypil Can you please guide use how to use user voice channel.

**Comment by mypil** [comment]
@MIkeMIP @cloud-e-lc - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature request on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)** 
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
