### ISSUE TITLE
Outdated Information in Section "Learn how to get a new client secret"

### ISSUE THREAD

**Issue by syntaxbearror** [MicrosoftDocs/microsoft-365-docs#4930]
To obtain a new secret, the section in the menu has changed from Keys to Certificates & Secrets. Then there is a section on that page specifically for Client Secrets, where you can issue a new secret, or delete existing ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86d8f68c-8e4e-e4e7-4bb4-ab50b7f509b6
* Version Independent ID: 9e1f8f09-31de-ed5e-8b14-0d3503e0d3e9
* Content: [Troubleshoot SIEM tool integration issues in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-siem?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-siem.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-siem.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@syntaxbearror Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4955

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @syntaxbearror Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
