### ISSUE TITLE
Teams chats an be reconstructed in Advanced eDiscovery

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#4932]
This statement needs updating to include the functionality for conversation threading in Advanced eDiscovery.
(Items found in eDiscovery searches can be exported, however there no context or structure from their original source remains – they are simply individual messages.)

Using advanced eDiscovery you can reconstruct a Teams chat conversations see this link for more info https://docs.microsoft.com/en-us/microsoft-365/compliance/conversation-review-sets?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6824f30e-ded2-dbcc-8fa0-ce4f4af64509
* Version Independent ID: cc94e220-315d-756b-ffe6-a5eb548aa931
* Content: [End of lifecycle options for groups, teams, and Yammer](https://docs.microsoft.com/en-us/microsoft-365/solutions/end-life-cycle-groups-teams-sites-yammer?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/end-life-cycle-groups-teams-sites-yammer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/end-life-cycle-groups-teams-sites-yammer.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
