### ISSUE TITLE
detection Script fault. 

### ISSUE THREAD

**Issue by guyhorn1964** [MicrosoftDocs/microsoft-365-docs#4937]
Remmove the '=' from the Powershell script. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d716f82-0a0f-49b8-587e-589d166e602e
* Version Independent ID: 2c91a5fb-0567-f267-29f9-4f2660742f6a
* Content: [Run a detection test on a newly onboarded Microsoft Defender for Endpoint device](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-detection-test?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-detection-test.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-detection-test.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@guyhorn1964 Thank you for your feedback.  $ErrorActionPreference = 'silentlycontinue' is correct, There was a missing space there which has been added to the script via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4949

ErrorActionPreference variable in PowerShell is to control the non-terminating errors by converting them to terminating errors. Error handling depends upon which value you assign to $ErrorActionPreference variable.

Hope this helps!

Thanks
Sri
