### ISSUE TITLE
Following up on Previous case Safe Docs - test malicous files #4834

### ISSUE THREAD

**Issue by Rkhan-ms** [MicrosoftDocs/microsoft-365-docs#4938]
Hi,

Can someone verify that the files included in this article will actually show up as malicous? I've set this up in my tenant as has my customer and in both instances we are seeing the same resulst. We can open the files even theough the article suggests that they shoul dbe highlighted as malicous.

Thanks in advance,

Ray

FAO -Chrisda and Yogkumgit.

I have the required M365 E5 as does my customer. And we are testing with M365 Apps version 2004 and later. They are still expereincing the same issue. Can you either re-open the case or work on this one with me please?

Thanks,

Ray

**Comment by chrisda** [comment]
@Rkhan-ms, no need to open another Issue. Closing, because the original issue is still open (#4834).
