### ISSUE TITLE
broken link for education blog

### ISSUE THREAD

**Issue by klishb** [MicrosoftDocs/microsoft-365-docs#4940]
The "education availability" link on this page is broken.  It's currently pointing to:
https://educationblog.microsoft.com/2019/08/attention-it-administrators-announcing-office-365-proplus-device-based-subscription-for-education

This is the correct location:
https://educationblog.microsoft.com/en-us/2019/08/attention-it-administrators-announcing-office-365-proplus-device-based-subscription-for-education

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bca3d86-2b5b-706f-ba26-291c8c0064ba
* Version Independent ID: 313eb228-35b4-6c47-4153-2137c62b6b20
* Content: [Manage licenses for devices](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/manage-licenses-for-devices?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/licenses/manage-licenses-for-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/manage-licenses-for-devices.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@klishb Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4950

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @klishb Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
