### ISSUE TITLE
PPT download link not working

### ISSUE THREAD

**Issue by sesmailjee** [MicrosoftDocs/microsoft-365-docs#495]
This link from this page:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/ciso-workshop-module-1
Download PowerPoint summary: Module 1: Microsoft Cybersecurity Briefing
https://docs.microsoft.com/microsoft-365/security/media/ciso-workshop-1-cybersecurity-briefing.pptx
is not working, please check and correct
BTW - this is GREAT content!
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88d48ed-b84b-3571-6c6e-e12ed8811c11
* Version Independent ID: a1aefdd8-25ed-f181-a167-c5d5f7a4efa3
* Content: [Chief Information Security Officer (CISO) Workshop, Module 1: Microsoft Cybersecurity Briefing](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/ciso-workshop-module-1#feedback)
* Content Source: [microsoft-365/security/office-365-security/ciso-workshop-module-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/ciso-workshop-module-1.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@sesmailjee  Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@sesmailjee - thanks for your feedback, investigating this with our repo management team.

**Comment by dstrome** [comment]
@sesmailjee - this is now fixed. You should be able to download the PowerPoint file. Thanks for bringing this to our attention.

@robmazz
