### ISSUE TITLE
Default sensitivity label to apply

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#4951]
Hello,

We have applied a policy that requires a sensitivity label when creating a new site or group and removed the option to select None, but in the MS Teams App it is possible to create Team using Template, as an example one of the defaults available "Manage a Project", when creating that, the Default sensitivity label or any label not visible at all to select during creation wizard... 

![image](https://user-images.githubusercontent.com/39700914/117664259-e08b2b00-b1a1-11eb-84ea-fc6ce2061a70.png)

Go next

![image](https://user-images.githubusercontent.com/39700914/117664291-e8e36600-b1a1-11eb-9662-5dfcef10f8ad.png)

Select Private

![image](https://user-images.githubusercontent.com/39700914/117664316-f13ba100-b1a1-11eb-9cbe-af28ed146581.png)

The next screen creates a team, but it will be created without a sensitivity label

![image](https://user-images.githubusercontent.com/39700914/117664371-fe589000-b1a1-11eb-8b7e-1015ccdfdfef.png)

Question: Something is in a roadmap to include sensitivity labels in the templates for MS Teams App?

Note: When creating a normal Team, the default label is present and not possible to create without a label.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 groups, and SharePoint sites - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire  Templates aren't supported yet and you'll find this on the list of limitations, here: https://docs.microsoft.com/en-us/microsoftteams/sensitivity-labels#limitations   When they are supported, we'll remove them from this list.

**Comment by yogkumgit** [comment]
@lightupdifire Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by lightupdifire** [comment]
Thanks for the info! Will be waiting for update, going back to the script :p
