### ISSUE TITLE
broken url on this page

### ISSUE THREAD

**Issue by ps959** [MicrosoftDocs/microsoft-365-docs#4952]
This url  on this page is dead. . Is there an updated url ? https://docs.microsoft.com/en-us/microsoft-365/enterprise/monitor-connectivity?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f903b4-8b86-70f6-8495-e8a9905ceb03
* Version Independent ID: 57fd3cc7-af0e-8d08-40c7-a5e070c1a237
* Content: [Monitor Microsoft 365 connectivity - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/monitor-connectivity?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/monitor-connectivity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/monitor-connectivity.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@ps959 Thank you for your feedback. We have removed the broken URL on this document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4993 as the blog is no longer active.

There is no replacement URL available, however, the guide is available when you download the System center management Pack for o365.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ps959 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
