### ISSUE TITLE
Incorrect Platform Version

### ISSUE THREAD

**Issue by scottvalentine** [MicrosoftDocs/microsoft-365-docs#4953]
The [published version](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus?view=o365-worldwide#monthly-platform-and-engine-versions) of this document has the platform minor version of "19" beginning in February rather than 18, e.g. 4.19.2102.3 rather than 4.18.2102.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01ab32b-6045-10f0-2a73-598961814f55
* Version Independent ID: 5bdbaa76-52aa-9330-fb23-03e90a28e32f
* Content: [Manage Microsoft Defender Antivirus updates and apply baselines](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @scottvalentine and thank you so much for the feedback. This is now resolved.
