### ISSUE TITLE
Needs update to Get-EXO... commands

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/microsoft-365-docs#4954]
Trying to use the EXO V2 module of exchange and cant get commands to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the Recoverable Items folder of cloud mailbox's on hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@fixx-er Thanks for following up. Glad you fixed it.
