### ISSUE TITLE
"Enable mailbox intelligence" and "Enable mailbox intelligence based impersonation protection"

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#496]
The above page could do with some more information on what these settings actually do (Maybe some examples). Current explanation does not really go anywhere towards why users would want to chose enable or disable, and what the outcomes are

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@aldoug - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by aldoug** [comment]
Thanks Joyce😊

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 09:00 - 18:00
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by joinimran** [comment]
Hello @aldoug thank you for your feedback. As per my understanding if you visit the document https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#learn-about-atp-anti-phishing-policy-options you can see "Use when you want to" and this section includes examples whenever required.

**Comment by mypil** [comment]
@aldoug - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
