### ISSUE TITLE
Can I view all the schema and tables in one big spreadsheet?

### ISSUE THREAD

**Issue by xiaoweiwu12701** [MicrosoftDocs/microsoft-365-docs#4962]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2518c0-9184-479d-5f39-755f8a10cddc
* Version Independent ID: 9d76fac7-5f54-abbb-d860-fb1723d2149d
* Content: [Advanced hunting schema reference](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-schema-reference?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/advanced-hunting-schema-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/advanced-hunting-schema-reference.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@xiaoweiwu12701 Thank you for your feedback. As the Advanced hunting data schema changes very often there is no spreadsheet that is available as such to view all schema in one place.

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by xiaoweiwu12701** [comment]
I do have a need to systematically download all the attributes, and its descriptions for documentation purposes. Doing a copy and paste line by line doesn’t seem to efficient.
Would you really consider this in the near future?

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @xiaoweiwu12701 we do understand what you saying but in the current scenario scope is limited to this document only.  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
