### ISSUE TITLE
Azure ActiveDirectory(MSOline) being deprecated but nothing on this page shows that

### ISSUE THREAD

**Issue by andrewn2000** [MicrosoftDocs/microsoft-365-docs#4964]
[https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-msonlinev1?view=azureadps-1.0](url)

Please note that we will begin to deprecate this module when the functionality of this module is available in the newer Azure Active Directory PowerShell for Graph module. We advise customers who are creating new PowerShell scripts to use the newer module instead of this module.

This note should be pasted above just like the reference document or perhaps remove the section "Use the Microsoft Azure Active Directory Module for Windows PowerShell" since it will be deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073b885d-191e-8c00-fa59-ad83ba79ec10
* Version Independent ID: 4bd5799d-9baf-90b6-634d-398fbea6b66f
* Content: [Assign Microsoft 365 licenses to user accounts with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@andrewn2000 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4992

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andrewn2000 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
