### ISSUE TITLE
Can we make a clarification about condition "Content is shared with people inside your organization" as it actually cannot be used to judge if a file is actually shared or not within the organization?

### ISSUE THREAD

**Issue by AlexPan0310** [MicrosoftDocs/microsoft-365-docs#4965]
Currently, when user upload file to OneDrive(not sure for SharePoint Online but I assume they are same), even user didn't share it with anyone(the file status shows private), DLP will still consider it as shared inside the organization. This is a current by design behavior according to PG. So can we make some clarification in this article in case other customers thought that DLP can judge if a file is shared or not inside the organization. (which leads to a wrong expectation for business requirements.)

**Comment by AlexPan0310** [comment]
> @AlexPan0310 Please indicate which article you are referring to. Thanks

Hi @yogkumgit , I mean this article https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide , the condition part.

**Comment by AlexPan0310** [comment]
> @AlexPan0310 Please indicate which article you are referring to. Thanks

@yogkumgit Any ideas?

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by AlexPan0310** [comment]
> @chrfox Please help us in resolving this issue. Thanks

Hi @yogkumgit  and @chrfox Any update for this request?

**Comment by yogkumgit** [comment]
@chrfox Gentle reminder.

**Comment by chrfox** [comment]
this article is hidden from the TOC and being deprecated
