### ISSUE TITLE
No mention of support or limitations for Public Folders mailboxes

### ISSUE THREAD

**Issue by andrew-harris** [MicrosoftDocs/microsoft-365-docs#4968]
I encountered an issue with one of our users recently and after I was able to consistently replicate that issue through testing, I'm led to believe that there are significant limitations with using Message Encryption with Public Folder mailboxes. The FAQ discusses limitations when using Shared Mailboxes but makes no mention of Public Folder mailboxes. It would be helpful to include a section on that and what limitations might be expected.

As an FYI, the issue identified above, was that while sending an encrypted email from a public folder mailbox is possible and is readable at the recipient's end; if the recipient replies back to that message, the following happens:

1. The email arrives but is not automatically decrypted and readable in the Public Folder. Instead, you see the "<Email Address> has sent to you a protect message" with a link to open it in a browser.
2. When clicking on that 'Read the Message' link, it tries to open an OWA sessions but never quite succeeds. Instead it gets stuck with a spinning wheel in the centre of the screen.

**Comment by denisebmsft** [comment]
Hello @andrew-harris and thank you for the feedback. Can you please tell us to which article(s) this applies? That information will help us route this issue to the correct writer/team.

**Comment by andrew-harris** [comment]
Hi @denisebmsft Sorry, I just assumed that info came through when I clicked the link. The page in question was:

https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
@denisebmsft - any chance you can help with this issue?

Thank you!!

**Comment by denisebmsft** [comment]
Hi @yogkumgit. The correct writer to help with this is @KCCross

**Comment by yogkumgit** [comment]
@KCCross Please update.

**Comment by yogkumgit** [comment]
@andrew-harris Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
