### ISSUE TITLE
Related article

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#4972]
Hello,

The following document shows how to add exclusions for Microsoft Defender using Powershell. 

Consider adding a link to that page to make it easier to find, and even including the powershell example in this article. Don't need it in two places obviously.

https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#add-exclusions-for-windows-defender-by-using-powershell

Thanks!
-jon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38e59489-cf97-ea8b-40b6-0ab7c299ea17
* Version Independent ID: 9fe50747-84c3-aabb-f98a-ef0a77721136
* Content: [Onboard Windows 10 multi-session devices in Windows Virtual Desktop](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-10-multi-session-device?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/Onboard-Windows-10-multi-session-device.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/Onboard-Windows-10-multi-session-device.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jonwbstr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/4991

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jonwbstr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
