### ISSUE TITLE
Needs more notations and/or breaking up the listed categories more

### ISSUE THREAD

**Issue by FuryoftheStars** [MicrosoftDocs/microsoft-365-docs#4975]
This document could benefit from more notes on what services are affected from each group of URLs and/or splitting everything up more.  For example, in my case, I'm trying to setup a web filter on our company's firewall that blocks everything except for very specific services for certain user groups.  In the case of Microsoft services, we only need them to be able to access their webmail via the Office 365 subscription we have for them.  However, there's more to it then simply whitelisting outlook.office.com and/or outlook.office365.com.  The login page, login.microsoftonline.com, also needs whitelisting, but simply doing that even is not enough (the login page shows up blank).

So, to be more specific, it'd be nice to have this noted and/or broken up to be clearer on what specifically is needed for webmail access vs onedrive vs onenote, etc, and what specifically is required for the login page to work correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
This issue is autogenerated as human-readable reference info from the same source as the web service, so we're limited in our ability to insert editorial copy that won't be overwritten.
