### ISSUE TITLE
Recoverable Items folder operation

### ISSUE THREAD

**Issue by Bievens** [MicrosoftDocs/microsoft-365-docs#4976]
“For Exchange mailboxes: The copy is retained in the Recoverable Items folder.”
Requesting an addition of clarifying information: Which subfolder in the Recoverable Items folder is being used and preserved? Or are all items in the Recoverable item’s subfolders preserved?

How does this interact with items preserved by the in-place hold, eDiscovery hold, and litigation holds? Example if you have retention policy and remove a eDiscovery hold normally the following would occur “After a mailbox user is removed from In-Place Hold or Litigation Hold, items in the DiscoveryHold, Purges, and Versions folders are purged by the Managed Folder Assistant.” In this situation does a retention policy preserve the items in these folders?

Reference
https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-and-litigation-holds

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@Bievens Thank you for your feedback. 

1) If In-Place Hold, Litigation Hold, or a Microsoft 365 or Office 365 retention policy is enabled, The "versions" folder contains the original copy of the item, and also if the item is modified multiple times, a copy of the item before modification is saved.

2)There are no conflicts between retention policies and Hold. In this scenario, the retention policy continues to preserve the items in this folder.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Bievens Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
