### ISSUE TITLE
block-persistence-through-wmi-event-subscription -- Intune?

### ISSUE THREAD

**Issue by mikesierra2** [MicrosoftDocs/microsoft-365-docs#4977]
I see that most of these settings have an Intune name for setting through Intune. This one does not:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-persistence-through-wmi-event-subscription

I need to set that through Intune. Can you please give me feedback on:
1) The doco is wrong, there is an option in Intune, we will update the doco?
2) The doco is correct, and MS are working on adding this in to Intune soon?
3) The doco is correct, there is no way to set this in Intune Policy, and MS are not going to add this option to Intune, I must find another way?
4) Other?

Thanks 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96cedf2c-e6fa-bbfb-61f0-ab4bcaae1479
* Version Independent ID: 45ca9ffb-55e9-7721-3433-017a513a59be
* Content: [Use attack surface reduction rules to prevent malware infection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-persistence-through-wmi-event-subscription\)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by mikesierra2** [comment]
To clarify this, all other items on this page have an "Intune name". This one does not, and there is no information on why that is the case. Defender for Endpoint is stating that we should set this option on, and does not give any advice on how to do so, neither does this documentation page. Any advice on how to make-it-so is greatly appreciated.

**Comment by msbemba** [comment]
@mikesierra2 Thank you for your feedback. The ASR Rule "Block persistence through WMI event subscription" can not be configured via Intune., However, we have a UserVoice section where the request has been added. You can Upvote this idea here- https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/40862476-asr-rule-block-persistence-through-wmi-event-subs and receive an email once this is implemented.

@yogkumgit There are no changes required in this document as of now.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mikesierra2 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
