### ISSUE TITLE
Intune Documentation for Enable Controlled Folder Access is out-dated / completely incorrect

### ISSUE THREAD

**Issue by AlphaXD001** [MicrosoftDocs/microsoft-365-docs#4981]
The documentation for configuring Controlled folder access is wrong - there is no way to follow the path provided to enable.
The proper path as of May 12, 2021 (since Microsoft keeps everything in Intune a moving target):
endpoint.microsoft.com > Endpoint Security > Attack Surface Reduction > Create Policy ... Windows 10 and later - Attack Surface reduction rules - then at the very bottom:
 - Enable Folder Protection (NC | Enable | Audit Mode | Block disk Modification | Audit Disk Modification)
 - List of Additional Folders that need to be protected:
 - List of apps that have access to protected folders:
 - Exclude Files and Paths from Attack Surface Reduction Rules

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25faafb3-297a-dbb1-651b-dcf18081e95b
* Version Independent ID: 61a3c7ca-8094-5219-7f7c-688124bab07c
* Content: [Enable controlled folder access](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-controlled-folders?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-controlled-folders.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@AlphaXD001 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5010

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AlphaXD001 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
