### ISSUE TITLE
Add API permission list

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/microsoft-365-docs#4982]
Could we have the individual permissions for the Defender API added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d4287b-0207-5c4f-ae5b-9b0fc33d36a9
* Version Independent ID: 53fdc584-5530-cf5e-fb2c-75591bb082bf
* Content: [Access the Microsoft Defender for Endpoint APIs](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/apis-intro?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/apis-intro.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/apis-intro.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jmmowrer Thank you for your feedback. We have added a link via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5011 to create an AAD APP which talks about the permissions list.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jmmowrer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
