### ISSUE TITLE
I'm so confused as how to buy Microsoft Defender for Endpoint

### ISSUE THREAD

**Issue by npiasecki** [MicrosoftDocs/microsoft-365-docs#4984]
I have a warehouse with more machines than users, but I'd like to run Microsoft Defender for Endpoint on the machines. They're logged in as a shared kiosk-type user.

It seems like there should be some kind of device license in addition to user licenses? Does just one user need to be Microsoft 365 E5 to enable access to the tool? 

So I'm not sure if it is unclear documentation, or just a difficult licensing scheme for the product.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@npiasecki Thank you for your feedback. The licensing requirements include Microsoft defender for endpoint(Standalone). As long as you have the supported Operating system version you can purchase the Standalone Microsoft Defender for Endpoint from your M365 Admin center. If you still need assistance to purchase, navigate to the need help section on your Admin center and contact Support.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @npiasecki Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
