### ISSUE TITLE
Anchor to "Can Microsoft 365 Business Premium customers use Microsoft Defender for Endpoint?" is incorrect

### ISSUE THREAD

**Issue by lof747** [MicrosoftDocs/microsoft-365-docs#4986]
[Enter feedback here]
The anchor link to "Can Microsoft 365 Business Premium customers use Microsoft Defender for Endpoint?" subsection points to "Where can I learn more about the opportunities and benefits in becoming a Microsoft Partner?" instead of the correct section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07ad1d58-d970-7e3c-91b7-84639d307ed8
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business Premium frequently asked questions ](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs?view=o365-worldwide#where-can-i-learn-more-about-the-opportunities-and-benefits-in-becoming-a-microsoft-partner)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/support/microsoft-365-business-faqs.yml)
* Product: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@lof747 Thank you for your feedback. The URL https://partner.microsoft.com/en-US/membership/cloud-solution-provider/find-a-provider points to a page to Find an indirect provider. 

The next topic has a link  https://partner.microsoft.com/membership/cloud-solution-provider which points to  Where can I learn more about the opportunities and benefits in becoming a Microsoft Partner

Both the URL's are accurate.

@yogkumgit There are no changes required in this document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lof747 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
