### ISSUE TITLE
This should be a module published at forge.puppet.com

### ISSUE THREAD

**Issue by binford2k** [MicrosoftDocs/microsoft-365-docs#4989]
It would be far easier to instruct users to `puppet module install` a module or add it to their `Puppetfile` than to laboriously walk them through creating a manifest to deploy. And it comes with the benefit that the user can just update the module when you make changes to it!

Happy to help make that happen if you need assistance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a5df48-1f27-18fe-f668-22fa03b9a680
* Version Independent ID: a0291804-533d-803e-c41b-0b0bc7f9a308
* Content: [Deploy Microsoft Defender for Endpoint on Linux with Puppet](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-puppet?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-with-puppet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-with-puppet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by B-starboy** [comment]
I would like to take you up on the offer of instruction on puppet module install or add to puppetfile ?

**Comment by B-starboy** [comment]
@binford2k

**Comment by binford2k** [comment]
@B-starboy to install like that, the authors of this code should put it into a module and publish it on the Forge or in a git repository.

**Comment by B-starboy** [comment]
Thanks for your response Ben . I will go check out the site .Don’t know much about puppets module , but sounds like a good way to automate .
Thanks again !

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder.

**Comment by mjcaparas** [comment]
The team has received the suggestion and will put for consideration.
