### ISSUE TITLE
Format of the bottom of the page seems broken

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#499]
The bottom of this page seems to be broken: the format seems to be bad (maybe some Markdown mistake).

![grafik](https://user-images.githubusercontent.com/6271057/65817192-9fc8e300-e204-11e9-81f1-58ba2d20ad7e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d15f061-ae97-6eab-12a4-1e0344a01fa0
* Version Independent ID: fa58e7e0-d50b-8629-2d5a-d4827e03f644
* Content: [Protect SharePoint Online files with retention labels and DLP](https://docs.microsoft.com/en-us/microsoft-365/compliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp#feedback)
* Content Source: [microsoft-365/compliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp.md)
* Service: **o365-seccomp**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@GiantCrocodile  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@GiantCrocodile - PR #504  has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!

**Comment by JoeDavies-MSFT** [comment]
@GiantCrocodile Your PR has been merged and published. Thanks so much for your contribution!

**Comment by GiantCrocodile** [comment]
Thank you for this quick fix @mypil @JoeDavies-MSFT!

**Comment by GiantCrocodile** [comment]
Oh I just noticed that this happens for the de-de language version too. Can you get it fixed there too @JoeDavies-MSFT @mypil?

**Comment by JoeDavies-MSFT** [comment]
@GiantCrocodile The changes I make to the English article are picked up and localized by other teams. This will happen over time. You can refer to the English one https://docs.microsoft.com/en-us/microsoft-365/compliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp in the meantime.
