### ISSUE TITLE
Wrong operation for AddMailboxPermissions

### ISSUE THREAD

**Issue by Jones-Bones** [MicrosoftDocs/microsoft-365-docs#4994]
Hi,

Operation for "Added delegate mailbox permissions" is wrong. It is Add-MailboxPermission instead of AddMailboxPermissions. Add-MailboxPermission shows up in both GUI and Search-UnifiedAuditLog output. Operation for delegation removal is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#audited-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Jones-Bones Thanks for the heads up. Looks like the cmdlet name is displayed as the operation value. I will update the documentation.
