### ISSUE TITLE
Use PowerShell to manage spoofed senders

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#4995]
In Step 2: "Edit the CSV file to add or modify the SpoofedUser (email address) and AllowedToSpoof (Yes or No) values. Save the file, read the file, and store the contents as a variable named $UpdateSpoofedSenders", can we change this to represent what we really need to add to the CSV: Sender, SpoofedUser, AllowedtoSpoof and SpoofType?

Just adding SpoofedUser and AllowedtoSpoof for a new line will just give you errors telling you to fill in the other listed fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c0cbdb-062e-08e1-7c7c-cedab550f01b
* Version Independent ID: 2791a840-3284-bc0d-7b9e-026b852797e6
* Content: [Configure spoof intelligence - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/learn-about-spoof-intelligence?view=o365-worldwide#use-powershell-to-manage-spoofed-senders)
* Content Source: [microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@dkotars Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
