### ISSUE TITLE
correction in "Onboard to the service" section

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/microsoft-365-docs#4999]
The **Onboard to the service** section says to:

> "_select any item under the **Endpoints** section, such as Incidents, Hunting, Action center, or Threat analytics to initiate the onboarding process._" 

In the portal these items are not located in the **_Endpoints_** section, but in "main", unnamed section, just under _Home_ item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7f625c-f3ef-882d-231f-6fef18e14137
* Version Independent ID: 3f335d54-6d65-d49a-e517-2c3a9a95e44d
* Content: [Turn on Microsoft 365 Defender in the Microsoft 365 security center](https://docs.microsoft.com/en-us/microsoft-365/security/defender/m365d-enable?view=o365-worldwide#start-using-the-service)
* Content Source: [microsoft-365/security/defender/m365d-enable.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/m365d-enable.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @lomayor
* Microsoft Alias: **lomayor**

**Comment by msbemba** [comment]
@mariuszo-at-microsoft-com Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5045

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mariuszo-at-microsoft-com Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
