### ISSUE TITLE
Search by content type

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/microsoft-365-docs#500]
Hello,

In the section "Retain content that contains specific keywords" its been mention that "Support for adding searchable properties (for example, subject:) is coming soon".

Does that mean that we can not use something like below?

contenttype:document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by mypil** [comment]
@ravick4u  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@ravick4u - Thank you for your query. Please note that contenttype:document type is support with sharepoint online but not with emails. See https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions for details. 

Searchable properties related to email mentioned https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions will be available soon. 

Regards,
Imran

**Comment by mypil** [comment]
@ravick4u - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by ravick4u** [comment]
Thanks for the response
