### ISSUE TITLE
MDATP package is missing in https://packages.microsoft.com/opensuse/15/prod/

### ISSUE THREAD

**Issue by alexey-zhel** [MicrosoftDocs/microsoft-365-docs#5007]
As per article we are supposed to use following command to configure repository: "sudo zypper addrepo -c -f -n microsoft-prod https://packages.microsoft.com/config/opensuse/15/prod.repo", however mdatp package is missing in that repository. IT is only available in https://packages.microsoft.com/opensuse/42.3/prod/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
I'm not a SSSE user myself but it seems only the SUSE Linux Enterprise Server packages (https://packages.microsoft.com/sles/) are up-to-date.
The OpenSUSE releases are all end-of-life, https://en.opensuse.org/Lifetime#Discontinued_distributions:
    openSUSE Leap 15.1 - Feb 2nd 2021
    openSUSE Leap 15.0 - Dec 3rd 2019
    openSUSE Leap 42.3 - Jul 1st 2019
    openSUSE Leap 42.2 - Jan 26th 2018
    openSUSE Leap 42.1 - May 17th 2017

**Comment by yogkumgit** [comment]
@Dansimp Please confirm and help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder.

**Comment by mjcaparas** [comment]
openSUSE is not supported.

For list of supported Linux server distributions see:

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide#system-requirements
