### ISSUE TITLE
"Block Office communication application from creating child processes" Prevents Tooltips and DLP warnings in Outlook

### ISSUE THREAD

**Issue by ab-aayers** [MicrosoftDocs/microsoft-365-docs#5008]
It appears enabling the Mentioned ASR (GUID:26190899-1602-49e8-8b27-eb1d0a1ce869) Blocks outlook from displaying tooltips or DLP override options from displaying in outlook.  
When attaching a document that would trigger a DLP rule (configured within 365 security) the user recieves a "defender blocked an action" and the outlook window does not display the mentioned tooltips and override toolbars within the message window.
the blocked action shows that defender blocked outlook.exe from creating process **C:\Program Files\Microsoft Office\root\Client\AppVDllSurrogate.exe** that must be related to these controls.  Disabling the ASR OR enabling the ASR while adding the C:\Program Files\Microsoft Office\root\Client\AppVDllSurrogate.exe path to exclusions for ASR allows it to work correctly.
I suspect this behavior should be documented OR the ASR should be modified to allow such a call to a trusted process?
![image](https://user-images.githubusercontent.com/47149062/118371972-143ccb00-b57d-11eb-86d4-e34d1ffca8d0.png)
![image](https://user-images.githubusercontent.com/47149062/118372009-3fbfb580-b57d-11eb-8853-eb5c4cc74a89.png)

**Comment by msbemba** [comment]
@ab-aayers Thank you for your feedback.  I shall test this and update the document if need be.

Document :- https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-office-communication-application-from-creating-child-processes

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ab-aayers Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
