### ISSUE TITLE
Clarify Location Limitations for Exchange Online

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#501]
When assigning a Location, the UI shows Choose Distribution Group. This does not seem to work with an Office Group. Please update the documentation to clearly state which type of groups can be used to limit the locations affected by the DLP, I'm guessing that it only works for Exchange Distribution List and possibly mail enabled security groups, but this is not stated anywhere. Also, are there any plans to make this work for Office Groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies#more-information)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@DeanGross  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @DeanGross,
**When assigning a Location, the UI shows Choose Distribution Group.** - "Distribution Group" is a Microsoft term for Exchange distribution lists (for example, see here - [Create distribution groups in the Microsoft 365 admin center](https://docs.microsoft.com/office365/admin/setup/create-distribution-lists?view=o365-worldwide))
**are there any plans to make this work for Office Groups** - plans are out of the scope of docs.microsoft.com portal, I think Microsoft wouldn't post this type of information here... 
Thank you

**Comment by mypil** [comment]
@DeanGross - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
