### ISSUE TITLE
This article is still using legacy OME information

### ISSUE THREAD

**Issue by BLTTEST** [MicrosoftDocs/microsoft-365-docs#5012]
Hi Teams,

I think this article hasn't been updated after new OME published: [https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-version-comparison?view=o365-worldwide
](url)

It says “OME doesn't let you apply usage restrictions to messages. For example, you can't use it to stop a recipient from forwarding or printing an encrypted message.” However, new OME has supported encryption and access restriction. It also led to the wrong "Recommendations and example scenarios" section. [https://docs.microsoft.com/en-us/microsoft-365/compliance/email-encryption?view=o365-worldwide#comparing-email-encryption-options-available-in-office-365](url)

I think this article may need a full review to update lots of outdated information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21613e57-8909-5adc-26ea-14e0a4771d3b
* Version Independent ID: dcd08c8d-4786-abbd-bd9d-47ad6d2117e6
* Content: [Email encryption in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/email-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/email-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/email-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@BLTTEST Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
