### ISSUE TITLE
PDF encryption initiated from iOS/Android Outlook

### ISSUE THREAD

**Issue by BLTTEST** [MicrosoftDocs/microsoft-365-docs#5013]
Hi Teams,

Under the question "Are PDF file attachments supported?", it says: "For Outlook on the web, Outlook for iOS, and Outlook for Android, you can encrypt PDFs you send without any more steps. These clients natively support PDF encryption."

However, under the question "How is this feature related to legacy Office 365 Message Encryption (OME) and Information Rights Management (IRM) features?", it says "End-user initiated from Outlook for Windows, Outlook for Mac, or Outlook on the web; or through mail flow rules".

So, I'm a little confused how could users initiate a PDF attachment encryption when OME even doesn't support initiating from mobile Outlook? Please kindly check that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2a02f3-0560-f5c7-9743-d7e65ad5d1a4
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.yml)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@BLTTEST Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
