### ISSUE TITLE
The screenshots are not showing for the event viewer components

### ISSUE THREAD

**Issue by DanWeinstock909** [MicrosoftDocs/microsoft-365-docs#5014]
Within the below web site;
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/event-views?view=o365-worldwide#feedback

The screenshots are not showing for the event viewer components, this is in steps below;
import an existing XML custom view
step 3

Copy the XML directly
step 2

List of attack surface reduction events
step 3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0059f8-8430-bb71-09c8-1fb220a52109
* Version Independent ID: c932e178-bfc3-e88b-d3b9-c3deb78d39df
* Content: [View attack surface reduction events](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/event-views?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/event-views.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/event-views.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@DanWeinstock909 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5046

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DanWeinstock909 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
