### ISSUE TITLE
The "Use the compliance center to turn on audit log search" should be updated to compliance.microsoft.com

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/microsoft-365-docs#5016]
Guidance in "Use the compliance center to turn on audit log search" section should be updated to experience in compliance.microsoft.com (including URL in step 1, descriptions in step 2&3, and screenshot in step 3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn audit log search on or off - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@mariuszo-at-microsoft-com Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5043

Thanks
Sri

**Comment by markjjo** [comment]
@mariuszo-at-microsoft-com Updated topic will be published by end of today. Thanks again for the heads up.
