### ISSUE TITLE
Link to MS Mechanics YoutTube video not working

### ISSUE THREAD

**Issue by M1KK3Lz** [MicrosoftDocs/microsoft-365-docs#5017]
Link does not work:
Watch this video for an introduction to Encryption in Office 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21613e57-8909-5adc-26ea-14e0a4771d3b
* Version Independent ID: dcd08c8d-4786-abbd-bd9d-47ad6d2117e6
* Content: [Email encryption in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/email-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/email-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/email-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@M1KK3Lz Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5044. Please note that the video link is removed as it is unavailable/private at the moment. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @M1KK3Lz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
