### ISSUE TITLE
Duplicate Category

### ISSUE THREAD

**Issue by core2lord** [MicrosoftDocs/microsoft-365-docs#5018]
Duplicate Found: Line #189 & #204.
- question: Why do I have an "onmicrosoft.com" domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35470cb5-bb30-146d-ae76-719079861c5f
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?redirectSourcePath=%252farticle%252f5481401f-7771-490e-b728-b3a81305a32e&view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.yml)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@core2lord Thank you for your feedback. Both are different as it talks about "onmicrosoft.com"  and "onmicrosoft.de" domain. The .de tenants are created for users in Germany. 

Hope this helps!

@yogkumgit There are no changes required in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @core2lord Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by core2lord** [comment]
Oh my gosh...I'm so embarrassed to have wasted your time on this
matter and sincerely apologize for my mistake. This was my first
submission in this regard and that was likely a lot to do with the
confidence I felt for being such an easy fix(so I had hoped for
anyhow) - I could have sworn that I looked over those two questions 10
different times, but I guess i'll take it for what it is and learn
from it.

Thank you so much for your understanding.
