### ISSUE TITLE
Permission Required

### ISSUE THREAD

**Issue by scottclarke1** [MicrosoftDocs/microsoft-365-docs#502]
Hi Guys!
What permission level is required in Office 365 to facilitate someone being able to see the Message Trace functionality in the Security and Compliance Center? With Security Administrator elevated, the dashboard is visible but not the ability to create a new search.
Could we please clarify this in the article?
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58f8e2c-428a-4d8e-e8b7-a0342a0038db
* Version Independent ID: 6e7fab1b-1e24-9e36-176d-c3fb14f233a7
* Content: [Message trace in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc#message-trace-page)
* Content Source: [microsoft-365/security/office-365-security/message-trace-scc.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/message-trace-scc.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@scottclarke1  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@scottclarke1 - From our understanding, the issue has been resolved based on the merged commit [[575924f](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/575924f94663c6a808ee34bcb9ee919e6827365a)]. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
