### ISSUE TITLE
PowerShell Advanced Delivery

### ISSUE THREAD

**Issue by rudischenck** [MicrosoftDocs/microsoft-365-docs#5020]
Will the powershell exchange online module be updated to allow these settings/rules to be edited/created via powershell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17ce75e-79ba-0acd-066c-a0120a29d65d
* Version Independent ID: 14673b1c-8489-0abc-90a0-42f35d516424
* Content: [Configure the delivery of third-party phishing simulations to users and unfiltered messages to SecOps mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-advanced-delivery?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-advanced-delivery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-advanced-delivery.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by rudischenck** [comment]
Is there any update on this?

**Comment by chrisda** [comment]
@rudischenck, the cmdlet reference topics published just yesterday 6/16/21:

- <https://docs.microsoft.com/powershell/module/exchange/get-phishsimoverridepolicy>
- <https://docs.microsoft.com/powershell/module/exchange/new-phishsimoverridepolicy>
- <https://docs.microsoft.com/powershell/module/exchange/remove-phishsimoverridepolicy>
- <https://docs.microsoft.com/powershell/module/exchange/set-phishsimoverridepolicy>

- <https://docs.microsoft.com/powershell/module/exchange/get-phishsimoverriderule>
- <https://docs.microsoft.com/powershell/module/exchange/new-phishsimoverriderule>
- <https://docs.microsoft.com/powershell/module/exchange/remove-phishsimoverriderule>
- <https://docs.microsoft.com/powershell/module/exchange/set-phishsimoverriderule>

- <https://docs.microsoft.com/powershell/module/exchange/get-secopsoverridepolicy>
- <https://docs.microsoft.com/powershell/module/exchange/new-secopsoverridepolicy>
- <https://docs.microsoft.com/powershell/module/exchange/remove-secopsoverridepolicy>
- <https://docs.microsoft.com/powershell/module/exchange/set-secopsoverridepolicy>


- <https://docs.microsoft.com/powershell/module/exchange/get-secopsoverriderule>
- <https://docs.microsoft.com/powershell/module/exchange/new-secopsoverriderule>
- <https://docs.microsoft.com/powershell/module/exchange/remove-secopsoverriderule>
- <https://docs.microsoft.com/powershell/module/exchange/set-secopsoverriderule>

I'll get the PowerShell procedures in the topic as I'm able.

**Comment by yogkumgit** [comment]
@rudischenck Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
