### ISSUE TITLE
In the troubleshooting section, the article says "If the */clientsideassets origin is missing, SharePoint Framework solutions will fail, and no warning or error messages are generated."  But it's not clear if this means you cannot use SPFx solutions if you haven't enabled the public CDN or if it means you can use SPFx solutions without a public CDN but if you DO enable the public CDN it must have */clientsideassets as an origin.  I suspect it's the latter but need to confirm.  Thanks!

### ISSUE THREAD

**Issue by scottmurdock** [MicrosoftDocs/microsoft-365-docs#5021]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cfe2b0-c14d-1083-7c88-a91e58593cfa
* Version Independent ID: 2d15076c-0dcd-6bd6-e0fb-f8ac5ffd0091
* Content: [Use Office 365 Content Delivery Network (CDN) with SharePoint Online - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo?view=o365-worldwide#troubleshooting-the-office-365-cdn)
* Content Source: [microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@scottmurdock Thank you for your feedback. You are correct! If you have CDN enabled, it must have the */clientsideassets as an origin. Sharepoint Framework solutions work without CDN. 

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by scottmurdock** [comment]
Thanks Sri!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @scottmurdock Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
