### ISSUE TITLE
text issue on page

### ISSUE THREAD

**Issue by Mhudson97** [MicrosoftDocs/microsoft-365-docs#5022]
top of the page appears as such:

If you're using version 2006 of Configuration Manager, you can manage tamper protection settings on Windows 10, Windows Server 2016, and Windows Server 2019 by using a method called tenant attach. Tenant attach enables you to sync your on-premises-only Configuration Manager devices into the Microsoft Endpoint Manager admin center, and then deliver endpoint security configuration policies to on-premises collections & devices.

![Windows security experience in Endpoint Manager](images/win-security- exp-policy-endpt-security.png)

 Note

-----
Note the embedded issue:
![Windows security experience in Endpoint Manager](images/win-security- exp-policy-endpt-security.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31e7b39-b7c3-188a-0b2a-02ff10a5be6d
* Version Independent ID: 44940a13-0a2d-e281-560b-cb4d8a5d1ccf
* Content: [Protect security settings with tamper protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @Mhudson97 for letting us know about this! I'll get this fixed today.
