### ISSUE TITLE
missing GPO settings

### ISSUE THREAD

**Issue by jdravet** [MicrosoftDocs/microsoft-365-docs#5025]
Under Other recommended configuration settings, Update endpoint protection configuration, I can see the GPO settings for \Windows Components\Windows Defender ATP but \Windows Components\Windows Defender Antivirus does not exist.  I have been following the directions until this point.  My deployment zip file only contained a 3KB AtpConfiguration.admx file.  The server is Windows 2019 with all updates.  The GPOs are using a central store.

UPDATE:  Found the missing settings.  Microsoft changed the name of Windows Defender to Microsoft Defender.  This includes the GPO settings.  The ATPConfiguration will need renaming as well as Windows Defender SmartScreen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523651c3-a318-2369-6892-d13e04991596
* Version Independent ID: 624c5e05-f87d-1bd4-bc87-bd55dcac1d86
* Content: [Onboard Windows 10 devices to Microsoft Defender for Endpoint via Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-gp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jdravet Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
