### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by sravenscroft** [MicrosoftDocs/microsoft-365-docs#5027]
There is a typo on the page - "Related articles" section header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d8d111-4435-5ae1-af2a-a27da62f16ef
* Version Independent ID: ceb9434d-0f1e-9ed6-b3c5-437cc5aa2ac6
* Content: [Use PowerShell to create reports for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-windows-powershell-to-create-reports-in-microsoft-365?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/use-windows-powershell-to-create-reports-in-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-windows-powershell-to-create-reports-in-microsoft-365.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@sravenscroft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5032

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sravenscroft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
