### ISSUE TITLE
Block process creations originating from PSExec and WMI commands

### ISSUE THREAD

**Issue by Anoni-Mouse** [MicrosoftDocs/microsoft-365-docs#5028]
[Enter feedback here]

Block process creations originating from PSExec and WMI commands
This rule blocks processes created through PsExec and WMI from running. **Both PsExec and WMI** can remotely execute code, so there is a risk of malware abusing this functionality for command and control purposes, or to spread an infection throughout an organization's network.

 Warning

**Only use this rule if you're managing your devices with Intune or another MDM solution. This rule is incompatible with management through Microsoft Endpoint Configuration Manager because this rule blocks WMI commands the Configuration Manager client uses to function correctly.**

**Why on earth did you stick WMI and PSExec together? Couldn't you separate them? I would like to block PSExec and PUA tools but keep WMI as I still manage clients with SCCM. Is this all for bringing customers to Intune only and leave the on-premises solutions???**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96cedf2c-e6fa-bbfb-61f0-ab4bcaae1479
* Version Independent ID: 45ca9ffb-55e9-7721-3433-017a513a59be
* Content: [Use attack surface reduction rules to prevent malware infection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-process-creations-originating-from-psexec-and-wmi-commands)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@Anoni-Mouse Thank you for your feedback.I agree with you that this could be separated. I have created a user voice /design change request - https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/43467372-separate-wmi-and-psexec-commands-from-the-block-pr

This design change request usually takes a few weeks for review and execution.  You can upvote this request to receive an update when this feature goes live.

@yogkumgit There are no changes in the document as of now and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Anoni-Mouse Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
