### ISSUE TITLE
Adjustment in script

### ISSUE THREAD

**Issue by robbonnema** [MicrosoftDocs/microsoft-365-docs#5029]
I had to remove the _-Type Spam_ after the Get-QuarantineMessage command in the script. Otherwise I didn't get the Quarantine results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aee91306-ef26-a762-844b-c3f70e8f0722
* Version Independent ID: 2ec32405-bc7a-60f2-782b-b527a2746b11
* Content: [Quarantined messages FAQ](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-faq?view=o365-worldwide#can-i-release-or-report-more-than-one-quarantined-message-at-a-time-)
* Content Source: [microsoft-365/security/office-365-security/quarantine-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-faq.yml)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@robbonnema, a couple of questions:

1. Are you saying the _Type_ parameter isn't available (resulting in errors in the script), or that `-Type Spam`  was returning zero results?
2. There appears to be a _QuarantineTypes_ parameter on Get-QuarantineMessage that does the same thing as the _Type_ parameter. My tenants appear to have both parameters. How does the _QuarantineTypes_ parameter work for you in this situation?

**Comment by robbonnema** [comment]
Now I see what's happening. The *-Type Spam* is resulting nothing because
the reason of Quarantine is High Confidence Phish, so I had to use *-Type
HighConfPhish*
Lesson learned for next time. Released the messages yesterday. Thanks.

Op di 18 mei 2021 om 18:42 schreef Chris Davis ***@***.***>:

**Comment by yogkumgit** [comment]
@robbonnema Thanks. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by chrisda** [comment]
@robbonnema, thanks for checking. Be advised that the false positive rate for high confidence phishing should be quite low (if not virtually zero), so use extreme caution when releasing those messages.
