### ISSUE TITLE
Outdated screenshot in step 5

### ISSUE THREAD

**Issue by sschutten** [MicrosoftDocs/microsoft-365-docs#503]
The screenshot in Step 5: Create an event is outdated. The Events section is now found under Records Management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad33cc1-dc5f-d9f9-ee8e-b103839945ef
* Version Independent ID: 1bc3101d-afe8-2056-3cda-6a86a209c460
* Content: [Overview of event-driven retention](https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention#feedback)
* Content Source: [microsoft-365/compliance/event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by mypil** [comment]
@sschutten - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@sschutten @mypil Fixed. Removed screenshot and updated navigation path to Records management > Events.
