### ISSUE TITLE
Limitations of Safe Links for Public Folders

### ISSUE THREAD

**Issue by FrogThomas** [MicrosoftDocs/microsoft-365-docs#5030]
The "Safe Links" feature, which is part of Microsoft Defender for Office 365, does not work for email enabled public folders. Unfortunately, this restriction is not documented.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide

**Comment by msbemba** [comment]
@FrogThomas Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5062
Once this is approved by the author you will see the changes reflect on the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @FrogThomas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
