### ISSUE TITLE
Clarify permissions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#5031]
please add some information that defines all of the different roles that can create/edit DLP policies. It is not clear if compliance admins, security admins or others can do this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Data Loss Prevention Reference - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies?view=o365-worldwide#permissions)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@DeanGross By default, Global admin,Compliance admin  and security admin have access to create and modify a DLP policy. I have added that to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5031. Once the author approves, the changes will be available in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
