### ISSUE TITLE
Add new "Type" parameter value to output a PAC file that excludes URLs detailed in O365 Tenant Restrictions 

### ISSUE THREAD

**Issue by loaderladdy** [MicrosoftDocs/microsoft-365-docs#5035]
```
.PARAMETER Type

The type of prioritization to give. Valid values are 1 and 2, which are 2 different modes of operation.
Type 1 will send Optimize traffic to the direct route. Type 2 will send Optimize and Allow traffic to
the direct route.
```

Type 2 includes URLs that feature in the Microsoft article on configuring tenant restrictions  here [https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/tenant-restrictions](url)

As manual configuration of Get-PacFile.ps1 PowerShell script output could lead to a security incident for an organisation that relies on tenant restrictions to reduce the attack surface of their exposure to the internet, especially for insider threats.

I have submitted this issue here because the code for Get-PacFile includes this snippet... 

`.PROJECTURI http://aka.ms/ipurlws`

**Comment by yogkumgit** [comment]
@loaderladdy Please indicate which document you are referring to. Thanks

**Comment by loaderladdy** [comment]
@yogkumgit hi, get-pacfile is maintained by @pandrew1 and @michael.carrillo and is found at [https://www.powershellgallery.com/packages/Get-PacFile/1.0.4](url)

the "Project Site" info link for Get-PacFile refers to this page [https://docs.microsoft.com/en-gb/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide](url) on Microsoft Docs

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
@loaderladdy  -- Can you clarify that the ask is to update the package on the Powershell gallery? That's not actionable for the tech docs team, but I can route the request if that's the case.

**Comment by loaderladdy** [comment]
Hi @LauraWi, your spot on with your assessment. It was a circular reference I guess. The landing page for Get-PacFile.ps1' on PowershellGallery references Microsoft Docs, so although this particular Microsoft Docs page refers to the workings of Get-PacFile PowerShell script, my issue is basically a suggestion back to Get-PacFile's authors. As a suggestion it can be routed to our friendly devs that'd be great don the issue can then be closed.  Many thanks Pete

**Comment by LauraWi** [comment]
Suggested update forwarded to engineering owners of file at issue.
