### ISSUE TITLE
Azure AD Connect Servers - narrower domain list.

### ISSUE THREAD

**Issue by sullcromenterprise** [MicrosoftDocs/microsoft-365-docs#5036]
It would be really nice if Microsoft could provide more details on the necessary ports and domains/URLs that are required for Azure AD Connect Servers > to MS Cloud Service.  The absolute mininum required ports/domains/urls should be listed. 

The current list is to broad and is not narrowly scoped enough for Microsoft Azure AD Connect Servers.  Especially when these servers have a very specific role/task unlike the entire user endpoint population.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
I have followed up with engineering to understand if this addition would be appropriate/in scope.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. The Office 365 endpoints web service is only designed to include endpoints that are specific to Office 365 services and features. The services you mentioned are not part of Office 365 and are therefore outside the scope of endpoints we can include in the database. -Kelley
