### ISSUE TITLE
Shared Inbox app functionality

### ISSUE THREAD

**Issue by shAFXr** [MicrosoftDocs/microsoft-365-docs#5037]
Documentation states that attachments sent within an encrypted email to a shared inbox, cannot be viewed when using the mobile Outlook apps. Testing against this document, it seems the statement is incorrect and encrypted messages and their attachments sent to shared inboxes, **can** be viewed on Outlook for iOS. If the docs team could clarify the functionality table, it'd be great. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2a02f3-0560-f5c7-9743-d7e65ad5d1a4
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.yml)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@shAFXr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5124

Thanks
Sri

**Comment by yogkumgit** [comment]
@KCCross PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @shAFXr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
