### ISSUE TITLE
Some of the download links return a 404 not found. 

### ISSUE THREAD

**Issue by shung818** [MicrosoftDocs/microsoft-365-docs#5038]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbbbdfb-c916-be79-2a91-5576d58a30e1
* Version Independent ID: 793f2f73-6fbc-04e5-fa8a-54908d74d860
* Content: [Microsoft 365 productivity illustrations](https://docs.microsoft.com/en-us/microsoft-365/solutions/productivity-illustrations?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/productivity-illustrations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/productivity-illustrations.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by msbemba** [comment]
@shung818 Thank you for your feedback. I was able to download PDF from all the downloadable links in the document. Could you please check and provide the link that is returning a 404 error?

Thanks
Sri

**Comment by shung818** [comment]
Hello Sri,

I had just checked today and they all are valid with no errors.

Thanks for checking in, I can relay this to my customer who had brought up the issue.

**Comment by msbemba** [comment]
@shung818  Thank you for the update. 

@yogkumgit  There are no changes required in the document. 
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @shung818 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
