### ISSUE TITLE
Need confirmation of deduplication

### ISSUE THREAD

**Issue by vikassou** [MicrosoftDocs/microsoft-365-docs#5041]
Document states that "if you choose the de-duplication option is that all Exchange items are exported in a single PST file and the folder structure from the source mailboxes isn't preserved. " But actually testing deduplication shows that the folder structure is preserved while exporting to PST.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035e4cc5-59a4-5034-2f10-f83651a8156d
* Version Independent ID: a4480d06-934b-6b35-0429-fbcb270bd060
* Content: [Differences between estimated and actual eDiscovery search results - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/differences-between-estimated-and-actual-ediscovery-search-results?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/differences-between-estimated-and-actual-ediscovery-search-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/differences-between-estimated-and-actual-ediscovery-search-results.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@vikassou Thanks for the heads up. Your testing is correct; the folder structure is preserved. I have also tested and confirmed. The documentation was out of date and was describing old behavior from In-Place eDiscovery searches in Exchange Online. I have updated the documentation. This doc change will be live by end of day. Thanks again for the raising this issue.
