### ISSUE TITLE
Outdated info

### ISSUE THREAD

**Issue by user0604** [MicrosoftDocs/microsoft-365-docs#5048]
[Enter feedback here]
The information on this page is outdated and therefore giving incorrect instructions 
1. In Exchange admin center there is no longer "Recipients > Groups", instead you can directly access "Groups"
2. In "Group > Edit" there is no longer "Group delegation"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b725ac58-0fa5-9f7d-84fa-a8541477fe0e
* Version Independent ID: f2acd0d0-60b8-0744-e241-06fb753aa5d1
* Content: [Allow members to send as or send on behalf of a group](https://docs.microsoft.com/en-us/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide#allow-members-to-send-email-as-a-group)
* Content Source: [microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@user0604 Thank you for your feedback. I'm able to access group delegation in the classic admin center. The link in the document points to the classic exchange admin center (https://outlook.office365.com/ecp/)

![image](https://user-images.githubusercontent.com/45987684/119490383-66020400-bd7a-11eb-8be5-c16561b9b19b.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @user0604 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
