### ISSUE TITLE
These illustrations have nothing to do with Enterprise Architecture

### ISSUE THREAD

**Issue by mark-wilson** [MicrosoftDocs/microsoft-365-docs#5049]
Please remove references to Enterprise Architect on this page. The information is great for Architects, but nothing to do with Enterprise Architecture.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91837ba8-f6f2-3c52-2d89-c8f4c4bce09c
* Version Independent ID: eb3c1fd8-9143-0dc1-77e7-e664ccaefc33
* Content: [Microsoft cloud architecture models - enterprise resource planning](https://docs.microsoft.com/en-gb/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/cloud-architecture-models.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/cloud-architecture-models.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by msbemba** [comment]
@mark-wilson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5122.

Once the author approves, the change will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mark-wilson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
