### ISSUE TITLE
Add Users to Protect Limit

### ISSUE THREAD

**Issue by jhernandez212** [MicrosoftDocs/microsoft-365-docs#505]
Is the 60 users defined a per policy limit or a per tenant limit.  We have observed the latter.  We have multiple Phish Policies defined and have observed that the policy with the highest priority is the one that works.  All other policies are ignored.  If I disable the highest priority policy then the next highest priority policy starts to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@jhernandez212 - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@jhernandez212 Thank you for your feedback. I would suggest you open a support ticket so that this can be routed to the concerned team to help you better. 

@mypil Please guide the user on how a support ticket can be opened. 

Regards,
Imran

**Comment by mypil** [comment]
@jhernandez212 - You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so your issue can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by MSFTTracyP** [comment]
The limit is per policy, but there can be conflicts if users are scoped to other high priority policy, like if, for example, they're in policies Pri 1 and Pri 2 the user will always be assessed by Pri 1. Conflicts like these can cause confusion.

**Comment by jhernandez212** [comment]
I have had a support ticket for this issue for a few weeks now.   What I was trying to achieve is to have multiple policies with discrete set of protected users applied to all of our users.  If I am reading @MSFTTracyP's comment correctly, you cannot have multiple policies applied to the same group of users because the higher priority policy will always take precedence?  (This is what we have observed).
