### ISSUE TITLE
Update page as the site sharing options can now be configures with sensitivity labels

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#5050]
In the Site guest sharing settings section it mentions than an additional step needs to be undertaken after creating the team to change the default SharePoint site sharing permissions to restrict access.

The configuration for the sensitivity labels for groups now allows you to also set the SharePoint site sharing permissions. This means if you create a new team and you select a sensitivity label then this will configure:

- privacy settings
- external guest access
- SharePoint site sharing is required. 
- Access from unmanaged devices

See reference https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5def8560-b22f-769a-e7e9-a88bfcc01d99
* Version Independent ID: abb6e6ba-d74d-7d13-3674-6f47ba2062d2
* Content: [Configure teams with protection for highly sensitive data](https://docs.microsoft.com/en-us/microsoft-365/solutions/configure-teams-highly-sensitive-protection?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/configure-teams-highly-sensitive-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/configure-teams-highly-sensitive-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
Thanks, @nikki-c. I actually just updated that section this morning and it should be live later today. I removed the additional step of setting the sharing setting in SharePoint, and just left it as updating the default sharing link type.

**Comment by yogkumgit** [comment]
@nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
