### ISSUE TITLE
Following instructions for forwarding does not address error

### ISSUE THREAD

**Issue by gourken** [MicrosoftDocs/microsoft-365-docs#5053]
When I am setting up my users (in this case myself) to automatically forward their e-mail to an external address, I get the following error message: 

![image](https://user-images.githubusercontent.com/84468348/118856089-8e828d80-b8a4-11eb-8363-f52ecc8e2010.png)

The message indicates that my organization does not allow external forwarding (which it does, but I may have implemented it incorrectly).  I have followed the instructions in the recommended document precisely but it does not seem to address the error message at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?WT.mc_id=365AdminCSH_support%3FWT.mc_id%3D365AdminCSH_globalsearch&view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@gourken Thank you for your feedback. 

When users configure automatic forwarding to recipients on a remote domain, the remote domain settings override users' automatic forwarding settings (messages are blocked if automatic forwards are disabled for the remote domain).

For more information on configuring remote domains -https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/remote-domains/manage-remote-domains

I have added this to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5110

Hope this helps!

Thanks
Sri

**Comment by Baryczka** [comment]
I'm having very similar problems, Antispam outbound policies are set, remote domain is keep default(which allows forwarding) and I receive the same message, what is surprising it was working for one whole day.
@gourken  Any news?

**Comment by gourken** [comment]
> I'm having very similar problems, Antispam outbound policies are set, remote domain is keep default(which allows forwarding) and I receive the same message, what is surprising it was working for one whole day.
> @gourken Any news?

My problem turned out to have been that I hadn't adjusted the antispam rules correctly and when I corrected then it worked as planned. The documents could be made clearer on the prerequisites for setting up email forwarding. I hope you find a solution for your problem.

**Comment by Baryczka** [comment]
@gourken  Apparently there was global outage/incident yesterday in the MS Exchange infra which was the cause. Now is working again 👍

**Comment by gourken** [comment]
> @gourken Thank you for your feedback. This could happen if automatic forwarding is disabled in remote domains.
> 
> When users configure automatic forwarding to recipients on a remote domain, the remote domain settings override users' automatic forwarding settings (messages are blocked if automatic forwards are disabled for the remote domain).
> 
> For more information on configuring remote domains -https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/remote-domains/manage-remote-domains
> 
> I have added this to the document via PR##5110
> 
> Hope this helps!
> 
> Thanks
> Sri

Thanks for your response. In my case it seems that I had misconfigured the Anti-spam options which caused the problem. I hope Microsoft takes the time to update the documentation to give all of the prerequisites necessary for forwarding to occur, including adjusting the anti-spam options. It would have saved me a bunch of time.

**Comment by gourken** [comment]
> @gourken There was global outage/incident yesterday in the MS Exchange infra which was the cause. Now is working again 👍

My problem seems to have been longer term. I had never successfully been able to get any auto-forwarding to work. Once I fixed my configuration for the anti-spam the problem resolved itself. It is good to know that there was a general outage though, and I thank you for that information.
