### ISSUE TITLE
'Submit Message' option not in Exchange Admin Centre

### ISSUE THREAD

**Issue by MSCM-GitHub** [MicrosoftDocs/microsoft-365-docs#5054]
In 'Office 365 Security & Compliance', on performing a 'Message Trace', there is an option to Submit an email that was not filtered to be evaluated. However, in Exchange Admin Centre (where the 'Message Trace' feature is to be moved to) that option is not given. Will it be added before the removal of the feature from O365S&C?

**Comment by denisebmsft** [comment]
Hello @MSCM-GitHub and thank you for posting your question here. Can you please tell us to which article(s) this applies? This information will help us route the issue to the correct writer/team.

**Comment by MSCM-GitHub** [comment]
Hi. This is not a reference to a document. It is regarding the '365 admin center'. If I need to post the suggestion to another system, please advise which one.

**Comment by MSCM-GitHub** [comment]
I have submitted the same comment via the Feedback feature on the '365 admin center'.

**Comment by msbemba** [comment]
@MSCM-GitHub Thank you for your feedback. In the new Exchange admin center(https://admin.exchange.microsoft.com/), when you perform a message trace, you should see an option to report the message, which handles the submissions to Microsoft.

![image](https://user-images.githubusercontent.com/45987684/119577289-f9b5ed80-bdd7-11eb-949d-3473b9f49b8f.png)

This option Is not available in the Classic Exchange admin center.

Hope this helps!
Thanks
Sri
