### ISSUE TITLE
please develop way to disable WPAD entirely

### ISSUE THREAD

**Issue by oliver27b** [MicrosoftDocs/microsoft-365-docs#5055]
[Enter feedback here]
WPAD is huge huge security risk.  Win10 now no longer allows you to disable the service.

we DO NOT want to _access the internet through someone else's proxy_  we do not know their intentions

actually we do know their intentions.  they want to hack every computer in the friggen world

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@oliver27b Thank you for your feedback. We understand the security risks with WPAD, however, Microsoft ensures that regular security patches are made available to the said service.

If you wish to leave feedback on the design, we recommend you provide it in the feedback section in the M365 admin center. We handle the document and do not have access to make design-level changes.

Hope this helps!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @oliver27b Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
