### ISSUE TITLE
Confusion with the 10-year add-on license requirement for logs longer than 1 year. 

### ISSUE THREAD

**Issue by jonnunez** [MicrosoftDocs/microsoft-365-docs#5057]
I am confused with the following statement from the documentation:

"To retain an audit log for longer than 90 days (and up to 1 year), the user who generates the audit log (by performing an audited activity) must be assigned an Office 365 E5 or Microsoft 365 E5 license or have a Microsoft 365 E5 Compliance or E5 eDiscovery and Audit add-on license. **To retain audit logs for 10 years, the user who generates the audit log must also be assigned a 10-year audit log retention add-on license in addition to an E5 license.**"

That last sentence (in bold). Do I just need the 10 year add-on license for the person generating the logs in addition to the E5 license they have? or do I have to purchase the 10-year add-on license for the entire company for it to work?

My understanding is that only 1 license is required for generating the logs. So for example if internal audit asks me to generate logs for a SharePoint site in the last 5 years, I would require that 10-year add-on license to do so and not the entire company.

Is this correct? Am I wrong?

thankful for any clarifications provided on this matter!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jonnuenez Sorry for the confusion. In your scenario, it would be per user licensing. So, to retain audit logs for activities that *you* perform, then you would need to be assigned an E5 license + an 10-year add-on (or an E3 + E5 Compliance + 10-year add on). The key point is that to retain audit records for up to 10 years, users have to be assigned the 10 year add on in addition to their E5 license. Again, the auditing licensing is per user licensing and licensing that is assigned to the user who is performing the activities (e.g. delete a file from a sharepoint site) that generate a corresponding audit record.

Also, in response to your scenario above, retention of audit records is not retroactive. So assigning a 10-yr add on to a user doesn't mean that an audit record for an activity performed 5 years ago will be accessible or retained. If would mean that an audit record will be retained for 5 years into the future. So if if you delete a file today, the audit record will be retained for 5 years from today.

One other thing: your org will need to create audit retention policies that retain audit records for 10 yrs. Currently, for example, SharePoint audit records are retained for 1 yr by default in Advanced Audit. To retain SP audit records for 10 yrs, you'll have to create a audit retention policy to achieve that. And, as per the first part of my answers, users will have to be assigned E5 + 10 year add on, to retain the audit records that are in scope for that audit retention policy.

Hope this helps. Let me know how the documentation can be updated to mitigate this confusion.

**Comment by jonnunez** [comment]
So to understand what I read from your post:

To retain activities for the entire organization, the option would be to assign the 10-year retention add-on to all the users in said organization. This 10 year feature works the moment you turn it on and it is not retroactive meaning that any files deleted after 90 days will remain as such. This feature will retain files deleted **after** activating the 10 year policy.

This means that I will be only able to generate a 10 year audit log from someone if they have that add-on assigned. If they do not have it, then it will cause an error occurs?

**Comment by markjjo** [comment]
@jonnunez You're not really generating a 10 yr audit log. The system will retain audit records for 10 years after the audit record is generated/triggered by some user activity. 

What happens if a user who was in scope for a 10 yr audit retention policy didn't have the correct license? I'm not sure if the system checks licensing when you create an audit retention policy (and returns an error or not). Hopefully it does when adding specific users to a audit retention policy but not sure what happens if you leave the Users field blank, which then assigns to policy to all users.  At a minimum, you would not be in compliance with your user licensing agreement. I'll follow up with engineering and respond to this github issue if I get more info. You might want to open a ticket with MS Support if you're seeing unexpected behavior.

**Comment by jonnunez** [comment]
Don't worry I didn't encounter any odd behavior, just trying to understand how the system would work in such scenario. Do let me know what engineering says about that.

As to the documentation update, I think modifying that last sentence in bold would help. Adding details that for any user who you want to retain for 10 years and generate a report on their activities, they too need to have this add on assigned regardless.

This addon license is per user.

So if we want to retain the organization's activities for 10 years, then that would mean that this addon needs to be assigned to each user that is in said organization.

**Comment by markjjo** [comment]
@jonnunez Thanks for doc suggestion. I will look at updating. Also, to be clear, in addition to the 10 yr add on, the user would also need to be assigned an E5 license or and E3 + upgrade license. In other words, user would have to be assigned licensing that supports Advanced Audit. Those licensing options are listed here: https://docs.microsoft.com/en-us/microsoft-365/compliance/auditing-solutions-overview?view=o365-worldwide#licensing-requirements
