### ISSUE TITLE
The settings mentioned for industry news doesn't match 

### ISSUE THREAD

**Issue by harshdamaniahd** [MicrosoftDocs/microsoft-365-docs#5060]
[The News Settings doesn't have a general tab, to get company based news feed.]

![image](https://user-images.githubusercontent.com/11780473/118935271-a4975900-b94b-11eb-9a42-1056c0bbf735.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92701183-1413-9e14-3109-53c2debe7d8b
* Version Independent ID: c1b54dbd-ac96-4582-b577-f09e8beba365
* Content: [Manage Industry news - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-industry-news?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-industry-news.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-industry-news.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@harshdamaniahd Thank you for your feedback. We have tested and found the options remain intact. If you are still not able to view the General tab under News, Please contact the Microsoft support team via the need help section on the admin center.

![image](https://user-images.githubusercontent.com/45987684/119486344-c773a400-bd75-11eb-995f-a2bb86e1916b.png

Hope this helps!

@yogkumgit There are no changes required in the document as of now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @harshdamaniahd Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
