### ISSUE TITLE
Other products

### ISSUE THREAD

**Issue by TurnerMarshall** [MicrosoftDocs/microsoft-365-docs#5061]
[Enter feedback here]
Is there anyway we can get the rest of the the M/O 365 applications added in here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45a2f60-4f5f-2ee3-5a2a-aeccf6c8b767
* Version Independent ID: 2335370f-07a5-0ef1-1c9d-54c1c36e449b
* Content: [Office 365 US Government DOD endpoints - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-u-s-government-dod-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@TurnerMarshall  Thank you for your feedback. The endpoints are grouped into four service areas. The first three service areas can be independently selected for connectivity. The fourth service area is a common dependency (called Microsoft 365 Common and Office) and must always have network connectivity. When checked with the author previously, it was determined that it would not be appropriate to add other endpoints to this O365 article. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @TurnerMarshall Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
