### ISSUE TITLE
Check Allow lists

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#507]
Be worth adding something about checking allow lists follow guidance in https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b97d9a-ce45-c521-a495-64819b0bd374
* Version Independent ID: bca02d32-0cc5-d439-25e7-d7c1256cfdf2
* Content: [How to reduce spam email in Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/reduce-spam-email)
* Content Source: [microsoft-365/security/office-365-security/reduce-spam-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/reduce-spam-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@aldoug - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @aldoug ,
could you please clarify what are you talking about?
whitelisting is already mentioned in "Fixing allowed spam" section of the article.
What do you think should be added to the article?
Thank you

**Comment by aldoug** [comment]
The mention of it “The most common of which is configuring your domains in a mail flow rule (also known as a transport rule) to bypass filters or listing your domain(s) in the allowed/safe-senders list. This is not good because these messages skip spam filtering and could have otherwise been caught.”

Is really brief in comparison to the issues it causes, and doesn’t actually give any detail. This could be resolved by adding a link to the new article https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365

This would save a bit of searching around in responding to these cases too😊


Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 09:00 - 18:00
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by MaratMussabekov** [comment]
Hello @aldoug,
good point, I will create a PR to add this link to the article.
Thank you

**Comment by mypil** [comment]
@aldoug  - From our understanding, the issue has been resolved based on the merged commit [[38ddc9c](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/38ddc9cffd87d39de5bde8f6192210396f15b7e7)] but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
