### ISSUE TITLE
Clarify roles required to run the online readiness assessment tool

### ISSUE THREAD

**Issue by csruane** [MicrosoftDocs/microsoft-365-docs#5070]
Suggest to change the text
"Anyone with at least the Global Reader or Intune Administrator role will be able to run this tool, but two of the checks (Conditional access policies and Multifactor authentication require additional permissions."

to:

"The Intune Administrator role is required to run this tool, with Global Reader required for two of the checks (Conditional access policies and Multifactor authentication) "

basically both roles are required to run the tool.
If the Global Reader role is missing, the readiness tool will always show that CA and MFA checks fail.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2edbbcfe-6534-59d7-0607-c3de3ff3ccf2
* Version Independent ID: ed5a4eab-c164-5cb7-51c1-3e9eab7d1dd3
* Content: [Readiness assessment tools - Microsoft Managed Desktop](https://docs.microsoft.com/en-gb/microsoft-365/managed-desktop/get-ready/readiness-assessment-tool?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-ready/readiness-assessment-tool.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-ready/readiness-assessment-tool.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@csruane Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5109

Thanks
Sri

**Comment by yogkumgit** [comment]
@csruane SMEs are checking and update .If you see ant other documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
