### ISSUE TITLE
Splunk Supported?

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/microsoft-365-docs#5073]
Per this article
https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/microsoft-defender-atp-third-party-solution-integrations/ba-p/532042

Splunk is listed as an available 3rd Party SIEM integration tool, However it's not listed in this doc. Does this doc need to be updated to reflect this capability?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36bbd71-ef7b-e08f-d565-d2b1e8b9deed
* Version Independent ID: 60fad392-2d82-84ca-6b0b-671122738b38
* Content: [Enable SIEM integration in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-siem-integration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-siem-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-siem-integration.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jpcast88 Thank you for your feedback. 

Defender for Endpoint currently supports the following specific SIEM solution tools through a dedicated SIEM integration model:

IBM QRadar
Micro Focus ArcSight

Other SIEM solutions (such as Splunk, RSA NetWitness) are supported through a different integration model based on the new Alert API that is why you don't see more information about Splunk. The details available here- https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-siem?view=o365-worldwide#pull-detections-using-security-information-and-events-management-siem-tools
.
Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba hank you very much for the contribution and sharing this explanation. @jpcast88 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
