### ISSUE TITLE
Factory Reset on Microsoft 365 Admin Center

### ISSUE THREAD

**Issue by ahmetarslan2020** [MicrosoftDocs/microsoft-365-docs#5074]
[Enter feedback here]

Hello,

We want to learn more about the Factory Reset Feature available on Microsoft 365 Admin Center.
If we hit the Factory Reset button for a Windows 10 Pro device, what exactly happens on the background? What happens to the Bitlocker hard drive encryption after factory reset?
Is Factory Reset same process as Intune Wipe? Or Intune Fresh Start?
Does it fully clean the hard drive? For e.g. when you manually reset a windows 10 device, you have these options: remove everything, plus fully clean the drive.

We will be grateful if you can provide more information.

Thank you for your support.

Ahmet Arslan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73fabca-12f9-819c-7e9a-cada191c4bc4
* Version Independent ID: ec771aea-0fe4-30db-7444-389a4eafa1d3
* Content: [Reset Windows 10 devices to their factory settings - Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/reset-devices-to-factory-settings?WT.mc_id=365AdminCSH_support&view=o365-worldwide)
* Content Source: [microsoft-365/business/reset-devices-to-factory-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/reset-devices-to-factory-settings.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@ahmetarslan2020 Thank you for your feedback. The Factory reset action returns the device to its factory default settings. This removes all personal and company data and settings from this device including the encryption.  It is very similar to intune Wipe or Fresh start, as the action cannot be reverted.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ahmetarslan2020 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
