### ISSUE TITLE
IP4 addresses for "Allow" and "Optimize" categories

### ISSUE THREAD

**Issue by Nyffe-Noob** [MicrosoftDocs/microsoft-365-docs#5075]
[Enter feedback here]
Hi. Will you still provide all the required IP addresses for the "allow" and "optimize" category in the future? Our firewall can't process URLs and we've noticed that you removed the required ip adresses from a "allow" category some days ago (ID:65 / URL www.office.com). It seems that the problem is fixed now, (www.office.com was moved to a "default" category) but we are unsure if this will happen again.

Best Regards
Andreas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7dc5655-eddb-360e-8906-d61b8e12f667
* Version Independent ID: c7939a12-24ce-5b98-c958-94a66b90ff1a
* Content: [Managing Office 365 endpoints - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/managing-office-365-endpoints?view=o365-worldwide#my-firewall-requires-ip-addresses-and-cannot-process-urls-how-do-i-configure-it-for-office-365)
* Content Source: [microsoft-365/enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by msbemba** [comment]
@Nyffe-Noob Thank you for your feedback. We try to provide all required information (IP and URL) in the document so that it makes it easy for readers and admins.

@yogkumgit  There are no immediate changes required in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Nyffe-Noob Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
