### ISSUE TITLE
Feedback | Start scoring user section - csv import, in case of regional language such as Japanese needs correction

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/microsoft-365-docs#5076]
[Enter feedback here]

For the start scoring user section - csv import, in case of regional language such as Japanese,
the csv file paramter [user principal name] also needs to be in regional language such as 「ユーザー プリンシパル名」 otherwise this throws error.
Could you help updating public documentation to reflect this accordingly as non-english customer may get confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3096e5de-0e2b-eb0e-850e-0cee9118078e
* Version Independent ID: 732f4433-84cb-43d5-131c-b21c358c7f99
* Content: [Insider risk management policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-policies?view=o365-worldwide#immediately-start-scoring-user-activity)
* Content Source: [microsoft-365/compliance/insider-risk-management-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-policies.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@TinaMcN Please help us in resolving this issue. Thanks

**Comment by TinaMcN** [comment]
@qaehtesh thank you very much for highlighting this issue.   I sent this article to be human translated for all languages which should be complete in 3 business days.  If it's not fixed then I'll follow up with the translators to use the approved translation for "user principal name"

**Comment by TinaMcN** [comment]
@qaehtesh an update on this issue.  Even after the article is human translated the string "user principal name" is not translated.  I asked the translators to fix it and they should complete it within a few days.

**Comment by TinaMcN** [comment]
@qaehtesh this has been fixed for all languages now.  Thanks again for reporting this issue.
