### ISSUE TITLE
End user usability impact

### ISSUE THREAD

**Issue by lyndon678** [MicrosoftDocs/microsoft-365-docs#5078]
This is often a huge topic and high threshold when Active Directories with .local namespaces as primary 
It would be really helpful to learn about the consequences and possible impacts to end user experience with sign-in scenarios on-prem when changes are done to user accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2be15ac4-2297-90eb-57f0-2c3eebfbdd91
* Version Independent ID: 959cf2d6-b6cd-59b9-21e4-dc31e8fba0b9
* Content: [Prepare a non-routable domain for directory synchronization - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-a-non-routable-domain-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
Thank you for the suggestion. We will monitor for additional customer demand on this topic. At this time, we're not resourced to support this content request.
