### ISSUE TITLE
OneDrive sync clients will not download files that contain viruses

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#5079]
[The statement in this article : "OneDrive sync clients will not download files that contain viruses. The sync client will display a notification that the file can't be synced" is wrong. 
The behaviour is: When a malicious file is uploaded to Onedrive it will be synced to the local machine already before it is even marked as malware in the service. After it is marked as malware in O365, the end user won't be able to open the synced file anymore from his/her local machine..]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9cd0ac5-2049-7e80-302e-e0f08857f6b4
* Version Independent ID: 7ca74c37-9929-bfc2-8a27-046457d2f67a
* Content: [Built-in virus protection in SharePoint Online, OneDrive, and Microsoft Teams - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/virus-detection-in-spo?view=o365-worldwide#what-happens-when-the-onedrive-sync-client-tries-to-sync-an-infected-file)
* Content Source: [microsoft-365/security/office-365-security/virus-detection-in-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/virus-detection-in-spo.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
@JeroenDronkers. Topic updated.

Closing
