### ISSUE TITLE
How long does it take to delete

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#508]
the docs tell us that Turning off can take up to 45 minutes. Please provide some information about how long we should expect Deleting a policy to take. (I' ve been waiting over 1 hour which seems very long)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0e7f42-60d0-1f95-57e9-6a24a5d87c2b
* Version Independent ID: 0080b139-e35b-b302-b38c-07a2e2e8c1ef
* Content: [Create a DLP policy from a template](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-dlp-policy-from-a-template)
* Content Source: [microsoft-365/compliance/create-a-dlp-policy-from-a-template.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-dlp-policy-from-a-template.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@chrfox - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by chrfox** [comment]
fix published
