### ISSUE TITLE
Sharing malware in SPO

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/microsoft-365-docs#5080]
[The following statement in this article is incorrect: "By default, users can't open, move, copy, or share malicious files that are detected by ATP. However, they can delete and download malicious files."
--> Users can still share malware by going to the "manage access" option where the Share option is still available. This really looks like a bug]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16930552-e148-ef20-581d-5171c2df1117
* Version Independent ID: 21dc2ac0-48f0-19c9-36db-1924c6e530d7
* Content: [Turn on Safe Attachments for SharePoint, OneDrive, and Microsoft Teams - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/turn-on-mdo-for-spo-odb-and-teams?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/turn-on-mdo-for-spo-odb-and-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/turn-on-mdo-for-spo-odb-and-teams.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
@JeroenDronkers, I updated the topic to mention this.

Closing
