### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by aandrew129** [MicrosoftDocs/microsoft-365-docs#5081]
The second section of the document contains a broken link for "System requirements for Microsoft 365."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0ecc06-296e-5d4b-437f-6fb2b334783f
* Version Independent ID: 50e394a4-0da6-cc94-74bd-6e06493c7ce6
* Content: [Microsoft 365 Client App Support: Single Sign-On - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-client-support-single-sign-on?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-client-support-single-sign-on.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-client-support-single-sign-on.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@aandrew129 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5141

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @aandrew129 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
