### ISSUE TITLE
Enhancement request - guide access for non-commercial users

### ISSUE THREAD

**Issue by aandrew129** [MicrosoftDocs/microsoft-365-docs#5082]
I'm super jealous of these configuration guides on this page. It would be amazing if they were made available to people in tenants other than commercial, such as GCCH and DoD, for instance.

**Comment by yogkumgit** [comment]
@aandrew129 Please indicate which document you are referring to and proposing improvements. Thanks

**Comment by aandrew129** [comment]
Apologies, I must not have created the ticket in the correct place. Below is information from another ticket from the same doc I was referring to:

"Version Independent ID: 7f19f87a-79cf-33b6-c64f-4449b1add0d9
Content: [Setup guides for Microsoft 365 and Office 365 services - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/setup-guides-for-microsoft-365?view=o365-worldwide#guides-for-initial-setup)
Content Source: [microsoft-365/enterprise/setup-guides-for-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/setup-guides-for-microsoft-365.md)
Service: o365-administration
GitHub Login:   ##@JoeDavies-MSFT
Microsoft Alias: josephd"

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Gentle reminder.

**Comment by JoeDavies-MSFT** [comment]
@aandrew129 Sorry for delayed response. I have forwarded your request to the product team for their future consideration. Thanks for letting us know about this.
