### ISSUE TITLE
Escape characters before angle-brackets

### ISSUE THREAD

**Issue by hempux** [MicrosoftDocs/microsoft-365-docs#5083]
[Enter feedback here]

Powershell-examples with the angle-brackets (< > ) . (such as the [Upgrade multiple DLs in a batch](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide#upgrade-multiple-dls-in-a-batch) example) seems to have unintentional escape-characters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb1e873-a684-ba18-21b4-33c2c4cf5aeb
* Version Independent ID: badad26e-0e5e-ab12-f3ae-b6cab759e7b8
* Content: [Upgrade distribution lists to Microsoft 365 Groups in Outlook - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?redirectSourcePath=%252fsv-SE%252farticle%252fMigrate-distribution-lists-to-Office-365-Groups-Admin-help-787d7a75-e201-46f3-a242-f698162ff09f&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@hempux Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5142

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @hempux Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
