### ISSUE TITLE
When are you going to update the releasing-a-policy-for-retention section to reflect MC244318?

### ISSUE THREAD

**Issue by pjsfonseca69** [MicrosoftDocs/microsoft-365-docs#5085]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#releasing-a-policy-for-retention)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Investigating the status of this nice update & when confirmed, will update the docs.

**Comment by cabailey** [comment]
@pjsfonseca69  Confirmed - this behavior change is now complete for all tenants & the docs are updated to match.  Thanks for your question!
