### ISSUE TITLE
Update the resources a user can't create when limited

### ISSUE THREAD

**Issue by prejedj** [MicrosoftDocs/microsoft-365-docs#5086]
The list of resources a user can't create when restricted by the group creation is very short. According to this article that I've confirmed there are at least 3-4 other resources they can't create. https://sharepointmaven.com/20-ways-to-create-an-office-365-group/

Specifically where it says a user can't create SharePoint sites, Teams, or Planners needs to have the following added:
1. Outlook group calendar
2. Shared Library in OneDrive
3. A Shared Power BI Workspace
4. Stream Group
5. Yammer Group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809bcea7-ebd6-58bc-9ff0-e764a459016d
* Version Independent ID: f86ecf79-7095-772a-980e-356a995061c5
* Content: [Overview of Microsoft 365 Groups for administrators - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/office-365-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/office-365-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@prejedj Thank you for your feedback. I have made changes to the document, Once it is approved by the author you will see the updated document.

PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5151 for tracking

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @prejedj Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
