### ISSUE TITLE
Article does not really tell how you can give another standard user, or staff member access to a former employees OneDrive data.

### ISSUE THREAD

**Issue by stelladew** [MicrosoftDocs/microsoft-365-docs#5087]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Step 4 - Give another employee access to OneDrive and Outlook data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-4?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-4.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-4.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@stelladew Thank you for your feedback. We have added steps to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5154

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @stelladew Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
