### ISSUE TITLE
Guests terminology has multiple meetings

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#5088]
The guest terminology has multiple meaning and is unclear

Guests is most often used when you add a guest to Teams.. in this scenario they get a B2b account. However this article about inviting a guest to a meeting without adding them to a team. In this scenario a guest does not mean a guest with a B2B account. It means an external user.

Is it possible to have consistent terminology
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a380458-a920-38e1-d886-a1ca90f82431
* Version Independent ID: f9887f48-a90e-f182-f778-e29d34ee60d2
* Content: [Schedule a Teams meeting with guests](https://docs.microsoft.com/en-us/microsoft-365/business-video/schedule-guest-meeting?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/schedule-guest-meeting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/schedule-guest-meeting.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5088

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
