### ISSUE TITLE
Bad link in the documentation

### ISSUE THREAD

**Issue by student-forever** [MicrosoftDocs/microsoft-365-docs#509]
In the Note: "Important
To learn how multiple technologies are applied, please visit how policies and protections are combined." the hyperlink leads to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-in/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@student-forever - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Solving Issue #509 in PR #516

**Comment by mypil** [comment]
@student-forever - From our understanding, the issue has been resolved but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
