### ISSUE TITLE
DLP Endpoint Protection

### ISSUE THREAD

**Issue by silbermano** [MicrosoftDocs/microsoft-365-docs#5092]
All devices must be Azure Active Directory (Azure AD) joined, AD joined, Hybrid Azure AD joined, or **AAD registered**.

AAD registered devices are not support according to "https://docs.microsoft.com/en-us/learn/modules/m365-compliance-information-prevent-data-loss/knowledge-check" in question 4

Please verify and correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
Hi @silbermano - I am forwarding this to the proper team

**Comment by yogkumgit** [comment]
@lizap Please update. Thanks

**Comment by yogkumgit** [comment]
@lizap Gentle reminder.

**Comment by tiburd** [comment]
@silbermano - it looks like [the article](https://docs.microsoft.com/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide) has been updated to include "AAD Registered" for question 4:

> ![image](https://user-images.githubusercontent.com/54688693/133131686-e18368f7-be4b-4e29-a4ad-9286326eb91e.png)

I am closing this issue. If you find that your concern still exists, please open a new issue.

Thank you!
