### ISSUE TITLE
Inconsistent filenames

### ISSUE THREAD

**Issue by afscrome** [MicrosoftDocs/microsoft-365-docs#5099]
The file in the github repo is `MDAV.wprp`, but the docs recommend you download it and save it locally as `WD.wprp`.  It would be clearer if the same filename was used consistently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a08b6ae-6445-ab2b-d380-627df46cf3d5
* Version Independent ID: c855d3af-002e-aff2-b2d6-8c6e549850a2
* Content: [Troubleshoot performance issues](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-performance-issues?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-performance-issues.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-performance-issues.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
Thank you very much for this feedback. You are correct. I have updated the doc to change all instances of WD.wprp to MDAV.wprp.

**Comment by yogkumgit** [comment]
@afscrome Thanks you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
