### ISSUE TITLE
Enable log

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#510]
Hello,
Should we enable in Office 365 Compliance & Security PS:
Set-AuditConfig & New-AuditConfigurationPolicy & New-AuditConfigurationRule ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn Office 365 audit log search on or off](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@lightupdifire - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @lightupdifire could you please kindly elaborate further your inquiry? Is it something you see that needs to be corrected in the referenced article? Thank you

**Comment by markjjo** [comment]
@lightupdifire @get-itips Unified audit logging in O365 doesn't need to be configured. As per the topic, you can turn it on or turn if off.  When it's on, it works. You'll note that the corresponding Get- cmdlet return nothing even thought unified audit logging turned on. You can control who can run audit log searches using EXO RBAC permissions. See the cmdlet help topics for these cmdlets for a little more information.

**Comment by lightupdifire** [comment]
@markjjo @get-itips 
We got issue that Audit log didn't return results, by troubleshooting tenant found that multiple powershell commands that can be used with different combination to enable audit log in tenant.
Then reading this article and looking into discovered powershell commands, was not clear what exactly should be enabled and configured.
Commands found:

https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/set-adminauditlogconfig?view=exchange-ps

https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/set-auditconfig?view=exchange-ps

https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/set-auditconfigurationrule?view=exchange-ps

https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/new-auditconfigurationpolicy?view=exchange-ps

https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-audit/new-auditconfigurationrule?view=exchange-ps

But only reasonable explanation is in this document regards:
"Set-AdminAuditLogConfig -UnifiedAuditLogIngestionEnabled $true"

So was wondering if more action required since new Office 365 Security & Compliance portal become available and opened this case.

But i see that @markjjo answered my question :)
