### ISSUE TITLE
Link to Microsoft Online Services Sign-in Assistant for IT Professionals RTW is broken 

### ISSUE THREAD

**Issue by jpringle03** [MicrosoftDocs/microsoft-365-docs#5100]
https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide#step-1-install-the-required-software-1

Under step 1 there is a link to "Microsoft Online Services Sign-in Assistant for IT Professionals RTW" which goes to https://www.microsoft.com/Download/details.aspx?id=28177. This download has apparently been removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55574af9-0105-dcd1-7eb0-77513df4e54f
* Version Independent ID: 5fe2849b-d39a-4d75-a5ce-e8f577c9a161
* Content: [Connect to Microsoft 365 with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell)
* Content Source: [microsoft-365/enterprise/connect-to-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@jpringle03 Thank you for your feedback. We are working with the author to fix this.

Thanks
Sri

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
@jpringle03 The link in that section is for https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_32bit.msi, which is a valid download. Can you clarify? Thanks

**Comment by msbemba** [comment]
@JoeDavies-MSFT Looks like the link has been updated now. Thank you.

@yogkumgit The document has been updated in the backend. Please close the issue.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jpringle03 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
