### ISSUE TITLE
Data usage

### ISSUE THREAD

**Issue by hhainesms** [MicrosoftDocs/microsoft-365-docs#5101]
What about device cellular data usage when this app is deployed on iOS devices?  From looking at data usage indicators on the iOS device, it appears to double the cellular data usage on the device when Defender is deployed to run VPN on the device.   This has negative impact to anyone with cellular data caps or who would be subjected to throttling when data usage exceed a certain amount per period.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d4eae37-e4cf-2642-d2cf-c648f90d2cc6
* Version Independent ID: 7cb88605-ddc9-5a1a-67f4-a28da1819227
* Content: [Configure Microsoft Defender for Endpoint on iOS features](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-configure-features?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-configure-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-configure-features.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by sunasing** [comment]
Hi @hhainesms, Thanks for sharing this feedback. Since Microsoft Defender for Endpoint (MDE) uses a VPN, iOS inaccurately accounts data usage to Microsoft Defender for Endpoint. The actual data usage is not as high as seen in the Settings app. Having said that, we are working on further data usage optimization on our side to ensure MDE uses as less data as possible to provide all the functionalities.

**Comment by yogkumgit** [comment]
@sunasing Thank you very much for the contribution and sharing this explanation. @hhainesms Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
