### ISSUE TITLE
Anti-Malware URL in this article points to old experience (Ex Admin), and not the new SCC experience. Please update the URL in this article. 

### ISSUE THREAD

**Issue by christinamorillo** [MicrosoftDocs/microsoft-365-docs#5104]
The _https://protection.office.com/antimalware_ URL in this article is now outdated and does not redirect to the updated experience. The correct URL (as of Dec 2020, and as per the M365 portal*) is **https://protection.office.com/antimalwarev2**

Screen capture attached for current URL redirect message when one goes to the currently listed URL. 
![GH-Issue-Docs-URL](https://user-images.githubusercontent.com/8405480/119411338-40acc180-bcb8-11eb-8975-145c78c5b70e.png)

Thank you for updating this at your earliest convenience. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db041b73-f7c9-db6c-070b-a7c974de640c
* Version Independent ID: dffb7045-3ba8-a014-d1be-462ca1d609b5
* Content: [Configure anti-malware policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-anti-malware-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-anti-malware-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-anti-malware-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@christinamorillo, funny you should ask.

The Microsoft 365 security center became globally available (not just in Preview) only a few weeks ago. We've just started our effort to convert any/all procedures/click paths/UI references under <https://docs.microsoft.com/microsoft-365/security/office-365-security/> from Security & Compliance Center to Microsoft 365 security center. That will be a rolling effort over the next several weeks (and possibly months).

For the Configure anti-malware policies topic, I did all of the updates last week and just merged the changes earlier today. The updated topic should go live after 5:00 PM PDT today Mon 5/24).

I'm going to close this issue, but feel free to re-open if you don't see the changes.

Thanks for the feedback.
