### ISSUE TITLE
Enable HMA with newer Versions "domain name" question

### ISSUE THREAD

**Issue by pstutzinger** [MicrosoftDocs/microsoft-365-docs#5106]
Hi.
the article states that with newer exchange hybrids we should use:
Set-AuthServer -Identity "EvoSTS - {GUID}" -Domain "Tenant Domain" -IsDefaultAuthorizationEndpoint $true

i know that this is because of the GUID change in newer HCW setups. But what is with this "Domain" Parameter? First there is only the Parameter "DomainName", second, currently in our setup this Value is Emty, and HMA is working as expected. Is this Parameter only an identifier for the "Set-AuthServer" Cmdlet or should it contain a value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae987bba-faf5-916d-c3b1-74f547ff8d90
* Version Independent ID: 9f5a7979-af5a-8fbf-45f0-287bb9fa4772
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@pstutzinger Thank you for your feedback. The parameter is called Domainname and the same has been updated in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5144 . The domain name parameter is needed when your Exchange  is in hybrid with multiple tenants.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pstutzinger Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
