### ISSUE TITLE
21Vianet?

### ISSUE THREAD

**Issue by cwidhelm** [MicrosoftDocs/microsoft-365-docs#5114]
What is up with the reference to 21Vianet on this page in the menu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1feb89e6-c5e0-693e-425e-8fd8b0198001
* Version Independent ID: 7b683879-67a9-299a-73e9-6e3654846fdf
* Content: [Set up file storage and sharing - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/set-up-file-storage-and-sharing?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/set-up-file-storage-and-sharing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/set-up-file-storage-and-sharing.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@cwidhelm Thank you for your feedback. We are working with the author to find out and fix the Menu.

Thanks
Sri

**Comment by cmcatee-MSFT** [comment]
@msbema I believe @cwidhelm is asking why "Office 365 operated by 21Vianet is showing up in the left nav (TOC). This issue isn't specific to this article, as that navigation is displayed for every article on the site. It should only display when "Office 365 operated by 21Vianet (China)" is selected in the Version drop-down list. I will investigate this and try to resolve it. However, this more a nuisance than a content issue, so I'm closing this.

@cwidhelm  Thank you for bringing this to our attention.
