### ISSUE TITLE
Lab Kit 20H2 guides v2

### ISSUE THREAD

**Issue by phlr2020** [MicrosoftDocs/microsoft-365-docs#5115]
Deveriam publicar também em português de Portugal.
[Escreva aqui os seus comentários]

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/pt-pt/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by yogkumgit** [comment]
@TinaMcN Please help us in resolving this issue. Thanks

**Comment by TinaMcN** [comment]
Olá @phlr2020 ,
Estou a gerir a tradução destes conteúdos mas, infelizmente, os conteúdos técnicos do Microsoft 365 não estão traduzidos para Português de Portugal.  Segue aqui o artigo em Português do Brasil, caso possa ajudar: https://docs.microsoft.com/pt-br/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.  
Cumprimentos,
Tina

**Comment by yogkumgit** [comment]
@TinaMcN Thank you very much for the contribution and sharing this explanation. @phlr2020 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
