### ISSUE TITLE
Difference between documentation and guidance in compliance portal.

### ISSUE THREAD

**Issue by limp15000** [MicrosoftDocs/microsoft-365-docs#5119]
Hi 
Documentation states : Priority: This value determines the order in which audit log retention policies in your organization are processed. A higher value indicates a higher priority. For example, a policy with a priority value of 5 would take priority over a policy with a priority value of 0. As previously explained, any custom audit log retention policy takes priority over the default policy for your organization.

But in the compliance center the guidance is the opposite : 
"Valid priorities are a numerical value between 1-10000. 1 is considered the highest priority, and 10000 is the lowest priority"

Not sure if the doc is correct or if the statement in O365 compliance center is right.

![image](https://user-images.githubusercontent.com/23700466/119555398-1d5c4200-bd9e-11eb-9fe3-367924489b32.png)

Many thanks for clarifying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide#create-an-audit-log-retention-policy)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@limp15000 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5143

Once the author approves, the document will be updated.

Thanks
Sri

**Comment by markjjo** [comment]
@limp15000 Please contact me via internal MSFT email and I can provide status on this. I am also following up with engineering.

**Comment by markjjo** [comment]
@limp15000 Confirmed with engineering that lower values take priority. Updated documentation will be published. We also updated the corresponding *UnifiedAuditLogRetentionPolicy cmdlet reference topics. Thanks again for heads up.
