### ISSUE TITLE
How do I get this section bad links

### ISSUE THREAD

**Issue by bryceroney** [MicrosoftDocs/microsoft-365-docs#512]
The links in the _How do I get this?_ section which go to other documentation pages are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed7ade2-b6c8-83db-2d20-e87ee7a3cb5d
* Version Independent ID: d0591610-bebd-22c9-aaae-d4c1c3ef2ff7
* Content: [Overview of the new Microsoft 365 compliance center](https://docs.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center#feedback)
* Content Source: [microsoft-365/compliance/microsoft-365-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@bryceroney  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@bryceroney  - thanks for the feedback, publishing the link fixes now.
