### ISSUE TITLE
Does M365 Business include clean installations, provided the computer is licensed for Windows 7?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#513]
There seems to be a lot of confusion throughout various forum posts. 

We understand that a licensed Windows 7 user can upgrade to Windows 10 with M365. However, often this is accomplished by reformatting the computer first. Windows 10 doesn't activate properly when this is done. 

The same concern would apply to a hard drive failure, for example. If a user needs a new hard drive do they need to keep Windows 7 installation media around for the life of the computer to do the in-place upgrade? I'm hoping not, because this is not an advisable practice, but we need clarity more than anything.

Contacting Technical support does not help here, because they do not seem to understand the difference between M365 Business and the M365 E3/E5 SKUs, and they are citing subscription activation which explicitly states that it does not apply to M365 Business (in the GitHub comments) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed7e43-7ec8-01f6-8cf0-6fd77519840e
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business Frequently Asked Questions ](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@Mike-Crowley  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Dear @Mike-Crowley ,
as far as I know, in scenario described by you, there is no need for Windows 7 installation media - you can install Windows 10 machine using Windows 7 key.
Dear @mypil, would it be possible to contact the Microsoft representative to confirm it? 
Thank you

**Comment by mypil** [comment]
@Mike-Crowley @MaratMussabekov - We can loop in the doc owner to get her inputs.

@Sirkkuw - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by PsychoData** [comment]
This [MS Site](https://www.microsoft.com/en-us/microsoft-365/business#compareProductsRegion) about the features seems to think that you can Upgrade from 7,8,8.1 to Windows 10 Pro. Don't know about direct installation though

![Hello World](https://i.imgur.com/7tWwcPQ.png)

**Comment by Mike-Crowley** [comment]
Yes Kevin, I said that in my opening statement.

**Comment by mypil** [comment]
@Mike-Crowley - Here's the information we received from the doc owner:

The prereqs are here- **https://docs.microsoft.com/en-us/microsoft-365/business/pre-requisites-for-data-protection**

You can upgrade from these SKUs: Windows 7 Professional, Windows 8 Pro, or Windows 8.1 Pro

With regards to the issue with the clean install, like do you need a key from the initial windows install for 7 Professional?  _Sometimes that is the case. You may need the win 7 key sometimes, but not the media._

The big thing though is that M365B only entitles you to an upgrade to Win 10 Pro from the above versions. If you have the Win 10 home SKU, for instance, you will have to upgrade to Win 10 Pro and pay for it.

We hope this helps to address your issue. Thank you for your contribution to make the docs better!

**Comment by Mike-Crowley** [comment]
I'm sorry, but this doesn't answer the question at all. 

"sometimes that is the case"

Sounds like you're guessing? What constitutes "sometimes"? Are you stating that we are to enter the Windows 7 product key into the Windows 10 activation process? If so, please document this. The link you included does not speak to anything wrelated to activation.

**Comment by Sirkkuw** [comment]
The product team is working on this issue and the topic will be updated as we get that information. For now, you will need the key for Win 7 to upgrade from Windows 7 Pro.

**Comment by Mike-Crowley** [comment]
> 
> 
> The product team is working on this issue and the topic will be updated as we get that information. For now, you will need the key for Win 7 to upgrade from Windows 7 Pro.

This topic should not have been closed, as this was never the question. The possession of the key is not the problem. As I stated in the introduction, the question is whether customers are prohibited from doing a clean installation of Windows 10.
