### ISSUE TITLE
Assign to me no longer available.

### ISSUE THREAD

**Issue by kimoppalfens** [MicrosoftDocs/microsoft-365-docs#5131]
The screenshot at the top and the section around assignment references an 'Assign to Me' option in the portal in the Alerts Queue. After verifying multiple environments I can only conclude the option is no longer there.

Kim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e663245-4894-4edc-032f-5f21568c007a
* Version Independent ID: e294b3ad-cf6f-3e79-d694-a3669bb04ca9
* Content: [Manage Microsoft Defender for Endpoint alerts](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-alerts?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/manage-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-alerts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by kimoppalfens** [comment]
The screenshot at the top and the section around assignment references an 'Assign to Me' option in the portal in the Alerts Queue. After verifying multiple environments I can only conclude the option is no longer there.

Kim

**Comment by mjcaparas** [comment]
Thank you for your feedback. You're right! The screenshot needs to be updated. 

The option however, has been modified to Manage alerts > Assign to.

**Comment by kimoppalfens** [comment]
Do you have more details as to where to find this option?
The 2 tenants I have access to don't have that option in the Securitycenter.microsoft.com portal. The option 'Manage alerts' is available but there's no 'assign to' option.

**Comment by mjcaparas** [comment]
@kimoppalfens sounds like a role restriction: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/user-roles?view=o365-worldwide#permission-options
