### ISSUE TITLE
Are "recipients" or "mailboxes" protected, there is a huge difference between the two?

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/microsoft-365-docs#5132]
Please clarify, when creating an exchange retention policy, in GUI it shows to be assigned to "recipients" not "mailboxes".

Is the GUI incorrect?
Is the full mailbox retained, including sent items, or only emails that are sent to a particular recipient identified in the policy?

This issue MUST be clarified in the documentation.

Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1c2e44-357c-8096-5bdf-40e205778ded
* Version Independent ID: 19c7b5d9-1e0c-501b-7b70-df5aab48b36e
* Content: [Learn about retention for Exchange - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-exchange?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-exchange.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@ssmiller60 Thank you for your feedback. The Exchange email location supports retention for users' email, calendar, and other mailbox items, by applying retention settings at the level of a mailbox. 

When you see the option recipients, it means it can be applied to Mailboxes, Shared mailboxes, O365 groups, resources, etc. All of these together are called recipients. 

![image](https://user-images.githubusercontent.com/45987684/120243758-1180ec00-c286-11eb-9354-5d19d79752dc.png)


Hope this helps!
Thanks
Sri

**Comment by ssmiller60** [comment]
Great info, thank you!  How do we get it added to the documentation?

**Comment by cabailey** [comment]
@ssmiller60  "Recipients" is a Exchange term that has a broad range.  Not everything listed in the previous response is included in an Exchange retention policy for email and in the article you referenced, we list the Exchange items that are included in this policy location.  What do you think is missing that would make this clearer?

**Comment by ssmiller60** [comment]
My thoughts are that since the exchange definition of "recipients" varies
from the commonly accepted English definition of the word in this context,
that should be noted specifically.  Especially since the two different
definitions result in a different understanding of the way the
functionality would work.

Possibly a note like:  "Note, the use of the word recipient is referencing
the exchange definition *here*"

(For *here*, put a link to the exchange documentation including the
definition)

**Comment by msbemba** [comment]
@ssmiller60 Thank you for your feedback. I have updated the information to a document which talks in detail about configuring retention policy - https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide#configuration-information-for-exchange-email-and-exchange-public-folders

This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5199

The retention policy can be applied on below recipient types

1)Mailbox (licensed)
2)Distribution group or mail-enabled security group(all mailboxes that are currently members of the group)

Thanks
Sri

**Comment by cabailey** [comment]
After discussing with the PM, I'm going to close this and the linked PR with two action items: First, look at the word "Recipient" to see if we need to find an alternative but more likely, add a clarifying explanation into the UI. It's not accurate to replace with "Mailboxes" because when you select users, they often have multiple mailboxes. But it's not accurate to replace it with "Users" either because shared mailboxes are also supported, although less often used.  We will double-check exactly what's supported for this UI selection but for now, you can assume user mailboxes and shared mailboxes.  Second, when we have that confirmation, I'll add it to the docs.  @msbemba if you have further questions, you can contact me internally.
