### ISSUE TITLE
It should be 249 users instead of 250

### ISSUE THREAD

**Issue by Lucas-mn** [MicrosoftDocs/microsoft-365-docs#5138]
"How small or large can the spreadsheet be? The spreadsheet must have at least two rows. One is for the column headings (the user data column label) and one for the user. You cannot have more than 251 rows. If you need to import more than **250** users,  you can create more than one spreadsheet."

The first row would always be the headings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99474cca-d2bc-d602-71ba-5c20e894429a
* Version Independent ID: 5aa17d74-a77f-82ed-48db-ff10413784bb
* Content: [Add several users at the same time to Microsoft 365 - Admin Help - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/add-several-users-at-the-same-time?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/add-several-users-at-the-same-time.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/add-several-users-at-the-same-time.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Lucas-mn Thank you for your feedback. I was able to test with 250 users. Ideally, the spreadsheet cannot have more than 251 rows, Out of which one is for the column headings, and you are left with 250 more rows for the users. 

Hope this helps!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Lucas-mn Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
