### ISSUE TITLE
Outdated article mentioned to use rules to automatically forward messages

### ISSUE THREAD

**Issue by raaghavvv** [MicrosoftDocs/microsoft-365-docs#5139]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by raaghavvv** [comment]
In https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide#:~:text=To%20forward%20to%20multiple%20email,rules%20to%20automatically%20forward%20messages.

<img width="498" alt="Outdated article inbox rules" src="https://user-images.githubusercontent.com/61713813/119798223-92438f00-bef8-11eb-9bae-734eda30d736.PNG">

**Comment by msbemba** [comment]
@raaghavvv Thank you for your feedback. Using Inbox rules to forward to multiple email addresses is correct. The option to forward to one email address is available from the admin center, however, you cannot add more than one address.

![image](https://user-images.githubusercontent.com/45987684/120236054-083d5280-c279-11eb-8d58-9e0088a60d17.png)


Hope this helps!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by raaghavvv** [comment]
Thanks for the response, I am talking about the article "Use rules to automatically forward messages" here which is integrated with this article. I mean this is a Microsoft 365 article (as mentioned in the article "Configure email forwarding in Microsoft 365") not applicable on Exchange Server 2013 or 2010 obviously then why do we reference article for inbox rule which is outdated and only applicable for Exchange 2013 and 2010. 

See this  article point no 4, when you click on this article it would redirect you to this article "https://support.microsoft.com/en-us/office/use-rules-to-automatically-forward-messages-45aa9664-4911-4f96-9663-ece42816d746?ui=en-US&rs=en-US&ad=US" which is for Exchange 2013 not for Microsoft 365 as Microsoft 365 has different inbox rules options

I hope I was able to explain it now

![image](https://user-images.githubusercontent.com/61713813/120272321-8544e800-c2ca-11eb-8838-2fb34bd3e111.png)

**Comment by msbemba** [comment]
@raaghavvv Thank you for your feedback. I have removed the Link and added steps to create an inbox rule to set up forwarding. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5182

Thanks
Sri

**Comment by raaghavvv** [comment]
Thanks @msbemba it looks good now, However it's Outlook client app steps you've mentioned
you could also update OWA steps as below. (this will be convenient for the end-users)

Idea is to make this document user friendly, Outlook and OWA steps would give them better clarity (that's my two cents). 

OWA:
---------------------------------

Go to https://outlook.office.com/mail/options/mail/rules/inboxRules OR OWA --> Settings (gear icon) --> Type Inbox rules in "Search Outlook settings"
Name your rule
Add new rule --> Add a condition --> Select "To" --> raghav@contoso.com
Add an action --> Select "Forward to" --> random@contoso.com
Save

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @raaghavvv Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
