### ISSUE TITLE
PUA Events query not working

### ISSUE THREAD

**Issue by mgrote03** [MicrosoftDocs/microsoft-365-docs#5145]
The query to detect PUA events with Advanced Hunting does not seem to work. I am getting the following error:

```
 Semantic error
Error message
'where' operator: Failed to resolve scalar expression named 'ThreatName'
How to resolve
Fix semantic errors in your query
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277950a2-8ece-d717-b02b-29dbe579b85b
* Version Independent ID: 9efa9a6f-519c-c3ca-f2e3-a902280231d9
* Content: [Block potentially unwanted applications with Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Thank you @mgrote03 for letting us know about this issue. My apologies for the query not working correctly. And thank you @yogkumgit for your help. I have reached out to a PM on the product team to help get this resolved. It might take a few more days but I will update the content as soon as I get a response. Will post an update here soon.

**Comment by denisebmsft** [comment]
@mgrote03, please try this query:

DeviceEvents
| where ActionType == "AntivirusDetection"
| project Timestamp, DeviceName, FolderPath, FileName, SHA256, x = parse_json(AdditionalFields)
| evaluate bag_unpack(x)
| where ThreatName startswith_cs 'PUA:'
| project Timestamp, DeviceName, FolderPath, FileName, SHA256, ThreatName, WasExecutingWhileDetected, WasRemediated


I have updated the content, and the changes will be live at around noon (Pacific Time) tomorrow.

Thanks again for letting us know about this issue!

**Comment by mgrote03** [comment]
Hi, no problem!
This query works fine, thanks!
