### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by davidslight** [MicrosoftDocs/microsoft-365-docs#5156]
[Enter feedback here]
Looking for guidance on privacy for Topics - I see a page for Insights with useful information but this page does not actually have the word privacy mentioned apart from the title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa2fdc1-25c2-cf11-9466-0182c55f6e8b
* Version Independent ID: 17a436fd-13e1-5684-09e4-d019021dd781
* Content: [Microsoft Viva Topics security and privacy](https://docs.microsoft.com/en-us/microsoft-365/knowledge/topic-experiences-security-privacy)
* Content Source: [microsoft-365/knowledge/topic-experiences-security-privacy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/knowledge/topic-experiences-security-privacy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please help us in resolving this issue. Thanks

**Comment by MikePlumleyMSFT** [comment]
@cjtancortex  can you help?

**Comment by MikePlumleyMSFT** [comment]
@davidslight I added a section noting that users' personal data (email and OneDrive) is not included in topic discovery. Let me know if there's other information that you're looking for.

**Comment by yogkumgit** [comment]
@davidslight Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
