### ISSUE TITLE
CBC ciphersuites not supported by Office365

### ISSUE THREAD

**Issue by janekbaj** [MicrosoftDocs/microsoft-365-docs#5157]
Based on report from sslscan only Ciphers below are supported:

```
sslscan www.office.com
Version: 2.0.6-static
OpenSSL 1.1.1g  21 Apr 2020

Connected to 13.107.6.156

Testing SSL server www.office.com on port 443 using SNI name www.office.com

  Supported Server Cipher(s):
Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-384 DHE 384
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve 25519 DHE 253
Accepted  TLSv1.2  256 bits  DHE-RSA-AES256-GCM-SHA384     DHE 2048 bits
Accepted  TLSv1.2  128 bits  DHE-RSA-AES128-GCM-SHA256     DHE 2048 bits

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14a729bb-ad0e-27bf-b119-beb99f1df9f4
* Version Independent ID: bc005f28-aa37-f52d-c328-ff547c1eb7b3
* Content: [Technical reference details about encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/technical-reference-details-about-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/technical-reference-details-about-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/technical-reference-details-about-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@janekbaj Thank you for your feedback. I'm currently checking with the author and will update the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@janekbaj Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
