### ISSUE TITLE
US Address function does not work on zips that start with 0

### ISSUE THREAD

**Issue by kdillaway** [MicrosoftDocs/microsoft-365-docs#5158]
Currently any zip code that starts with 0 is not detected by the function and this needs to be added AND added to the documentation found here: https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-dlp-functions-look-for?view=o365-worldwide

This has to be updated so that customers know the limitation clearly which is pretty huge since it will not pick up any zip code associated with most of the New England states nor ones located in Boston, so the functions is missing millions of potential addresses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ebaf450-d84e-c333-125c-b0e6d4662bad
* Version Independent ID: efcb8b51-f2fe-765b-221d-75890b4a2d64
* Content: [What the Data Loss Prevention (DLP) functions look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-dlp-functions-look-for?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/what-the-dlp-functions-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-dlp-functions-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
Hi @kdillaway forwarding this to the product team.  The documentation follows the product code, so if this needs to be fixed, it must be fixed in the product first.

**Comment by kdillaway** [comment]
Ok, I just want to make sure that it is updated so that it clearly states that any zip that starts with ) will not be picked up by the function.  Besides being documented, this should be fixed as it seems pretty crazy that it would be by design to not catch millions of addresses in the Northeast US.

How can we track that this is fixed?

Kevin
