### ISSUE TITLE
Clarify which ASR rules generate alerts and which ones don't - and whether this is configurable

### ISSUE THREAD

**Issue by franklesniak** [MicrosoftDocs/microsoft-365-docs#5163]
The Notifications and Alerts section (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#notifications-and-alerts) vaguely indicates that some ASR rules trigger alerts and others don't ("when certain attack surface reduction rules are triggered, alerts are generated").

It'd be helpful if this was more specific. Which ASR rules trigger alerts? Which ones do not? Is there anything that can be configured to make them generate an alert?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96cedf2c-e6fa-bbfb-61f0-ab4bcaae1479
* Version Independent ID: 45ca9ffb-55e9-7721-3433-017a513a59be
* Content: [Use attack surface reduction rules to prevent malware infection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#notifications-and-alerts)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@denisebmsft Gentle reminder.

**Comment by denisebmsft** [comment]
Opened task 5351236

**Comment by denisebmsft** [comment]
My colleague is still working on this. He is waiting on some needed information.

**Comment by jweston-1** [comment]
In progress - a few issues still to be resolved.

**Comment by jweston-1** [comment]
Fixed, but will add additional details when provided by the product team. 
See: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#per-rule-alert-and-notification-details
