### ISSUE TITLE
Fix steps to be from simplified view

### ISSUE THREAD

**Issue by AntoniaBlume** [MicrosoftDocs/microsoft-365-docs#5165]
In the Get Business Assist section, modify the steps to show how you get there in Simplified view. Since you have to have fewer than 5 users, high likelihood that they are using simplified view.
1. In the simplified view of Microsoft 365 admin center, on the Subscriptions tab, select Add products. 
2. On the Purchase services page, select Other services, and then select Details for Business Assist for Microsoft 365. 
3. Complete your purchase. 

Also, please change "less than 5 users" to "fewer than..." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f142f7c-6415-8c7d-144b-71a56af357c5
* Version Independent ID: 6c709916-49bd-3673-82cd-e4ae2765823b
* Content: [Business Assist for Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/business-assist?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/business-assist.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/business-assist.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@AntoniaBlume Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5178

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AntoniaBlume Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
