### ISSUE TITLE
Bad link in impersonation protection configuration

### ISSUE THREAD

**Issue by tp-seiso** [MicrosoftDocs/microsoft-365-docs#517]
In the Security and Compliance center under Threat Management, Policy, Anti-phishing, the menu for adding users to an impersonation protection policy has a link titled "Get tips for adding users to protect" pointed at https://go.microsoft.com/fwlink/?linkid=864553

This link returns a 404 at the time of posting the issue

**Comment by mypil** [comment]
@tp-seiso - May we know which Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. Thank you.

**Comment by tp-seiso** [comment]
@mypil - Thanks for the quick reply. I was referring to the page titled "Set up Office 365 ATP anti-phishing and anti-phishing policies" https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies when I found the bad link in the Security and Compliance center of o365

**Comment by mypil** [comment]
@tp-seiso - I could not seem to find that link in the doc. Just for clarification, is the bad link found within this documentation? or is it in your tenant?

Thank you.

**Comment by tp-seiso** [comment]
The link is in all of the tenants to which I have access. Here's a link to a screenshot https://i.imgur.com/yFZY7ab.png

**Comment by mypil** [comment]
@tp-seiso - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by tp-seiso** [comment]
I got feedback on a trouble ticket. The support representative reported that the page in question is still under development and that the 404 is expected for the time being.

**Comment by mypil** [comment]
@tp-seiso - Thank you for sharing this additional information. This could be a possible bug that you found. Let me get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

@

**Comment by kenwith** [comment]
@tp-seiso , I agree with @mypil , thank you for taking the time to open the issue here and also for following up with your feedback from support. @mypil thank you for escalating this to me. Since this is a 404 in the Admin Center (thank you for screenshot) I am going to track down the group that can help get that fixed. I will keep this Issue updated as we get it sorted. I really appreciate the effort to make the product better! Thank you again!

**Comment by mypil** [comment]
@tp-seiso - We were informed that the link has been fixed. Can you please check in your tenant and let us know if the issue has been resolved?

Thank you.

**Comment by tp-seiso** [comment]
@mypil - Looks good to me now! Thanks for helping to drive a quick resolution.
