### ISSUE TITLE
Suggestion for additional content

### ISSUE THREAD

**Issue by schbrownie** [MicrosoftDocs/microsoft-365-docs#5170]
Excellent Article!  I was looking for something exactly like this earlier this year.  Thank you

However, this does not completely address our tennant....  we were originally an on-premise AD and now have a Hybrid AD environment.  Can you please either add (or link to existing articles) content about recommended steps for completely removing someone including from either an on-premise AD, Hybrid AD or Azure AD?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@kwekuako Please update. Thanks

**Comment by yogkumgit** [comment]
@kwekuako Gentle reminder.

**Comment by msbemba** [comment]
@schbrownie Thank you for your feedback. While there is no separate article for disabling users in the Active directory. As an Admin once the employee leaves the company, he is usually disabled and Moved to an OU which does not sync with M365.

The "restore a user link" in the document can be used to restore the user (which then makes the account just an M365 account) and the rest of the steps remain the same.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed as there are no additional changes to the document.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @schbrownie Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
