### ISSUE TITLE
SharePoint IRM versus Sensitivity labels (AIP)

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/microsoft-365-docs#5175]
Is SharePoint IRM still updated and therefore recommended by Microsoft?
OR shall we move to sensitivity labels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29df28b-0065-a059-f22d-3433c1dd65a0
* Version Independent ID: 83b44475-2a39-5747-fc3c-2a92d0d958f2
* Content: [Set up Information Rights Management (IRM) in SharePoint admin center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-irm-in-sp-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-irm-in-sp-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-irm-in-sp-admin-center.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@teomonda Thank you for your feedback. 

While the option to use IRM in Sharepoint admin center is still available, Office 365 sensitivity labels are the preferred way to protect content stored in SharePoint Online and OneDrive for Business. They are more flexible and powerful than the traditional approach of protecting SharePoint libraries with IRM.

Hope this helps!

Thanks
Sri

**Comment by teomonda** [comment]
Thanks for your info, Sri.
Does it make sense that we add a note or something in the article, pointing out to the sensitivity labels?

**Comment by msbemba** [comment]
@teomonda Thank you for your feedback. We have now added documents relating to sensitivity labels to the recommended content section of this document. 

Hope this helps!
Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @teomonda Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
