### ISSUE TITLE
Not all roles are listed and described

### ISSUE THREAD

**Issue by giterdn** [MicrosoftDocs/microsoft-365-docs#5176]
[Enter feedback here]

The Message center reader is referenced in this article, but not explicitly listed or described.  Can you add this role, and any other roles that are missing?  Otherwise, can you advise what article is the definitive list of M365 admin roles?

Thank you,

Steve
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@giterdn Thank you for your feedback. We have added Message center reader role and a few other roles in the document. The same can be tracked via  PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5234

Thanks
Sri

**Comment by giterdn** [comment]
Thank you.  I don't the see the changes so I will wait a few days and check back.

Steve
STEVE KISH | Manager - Desktop, Mobility, Telecom & Audio-visual

CITY OF SURREY
Corporate Services, IT Division
13450 104 Ave, Surrey, BC, Canada V3T 1V8
T 604.591.4878 | C 604.345.0288  www.surrey.ca<http://www.surrey.ca/>

**Comment by msbemba** [comment]
@giterdn Yes, The request needs to be approved and merged by the author. You will receive an update when that is complete.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @giterdn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
