### ISSUE TITLE
Rollout completion ETA?

### ISSUE THREAD

**Issue by MikeDembek** [MicrosoftDocs/microsoft-365-docs#518]
When is this rollout expected to be completed?

Is there a corresponding entry in the O365 roadmap? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c7c32e-6f64-353b-0822-f6c7b4072998
* Version Independent ID: 1a0d4ab3-c309-daa2-7855-93257071c29e
* Content: [Unverified Sender](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/unverified-sender-feature#feedback)
* Content Source: [microsoft-365/security/office-365-security/unverified-sender-feature.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/unverified-sender-feature.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@MikeDembek  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by MSFTTracyP** [comment]
For existing clients called out by the article, this feature is rolled out. But if you use semi-annual updates, this may not appear for you. The feature is not rolled to Mac, or mobile yet. I hope that helps, @MikeDembek!
