### ISSUE TITLE
Office built-in labeling client and the Azure Information Protection client

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#5181]
Hello,

About "If users have the Azure Information Protection client installed, by default, the built-in labeling client is turned off in their Office apps." it looks like there is an issue with it and the built-in labeling not being disabled, as an example, we install AIP UL on the device, and when user try to send email FROM Shared mailbox, the Justification prompt appear that label change appear and user must provide an explanation why lowering down the label. If we disable the cloud client (by the registry), then the "Justification prompt" disappears.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Manage sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#office-built-in-labeling-client-and-the-azure-information-protection-client)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire Are you referring to this issue that we documented on the same page:

If you use the Group Policy setting Use the Sensitivity feature in Office to apply and view sensitivity labels and set this to 1, there are some situations where the Azure Information Protection client might still load in Office apps. Blocking the add-in from loading in each app prevents this happening.

**Comment by lightupdifire** [comment]
@cabailey 
What if we don't use the Group Policy setting? And we want to use the Azure Information Protection client installed and not the other way around.
Why then it is saying in the doc "If users have the Azure Information Protection client installed, by default, the built-in labeling client is turned off in their Office apps." so it is not true?

**Comment by cabailey** [comment]
As documented, "there are some situations where the Azure Information Protection client might still load in Office apps. Blocking the add-in from loading in each app prevents this happening."  If you still experience this problem after following the guidance to disable the add-in for the Office apps, please open a Support case: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#office-built-in-labeling-client-and-the-azure-information-protection-client 

This updated guidance was released in March (https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide#march-2021)

**Comment by lightupdifire** [comment]
@cabailey 
We want to use the Azure Information Protection client, we require that this client is loaded in the Office apps.

**Comment by cabailey** [comment]
@lightupdifire  In that case, use the same configuration procedure, but with the setting of 1: The add-in is always enabled, as documented here: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/reqs-ul-client#configure-your-group-policy-to-prevent-disabling-aip

**Comment by lightupdifire** [comment]
@cabailey 
But the Azure Information Protection client installed well and the add-in is there on all 1000 PCs.
The thing is we want to use the Azure Information Protection client and not the Office 365 built-in.
Then for us, this "If users have the Azure Information Protection client installed, by default, the built-in labeling client is turned off in their Office apps." would be the perfect scenario... but it is not true, the Office 365 built-in for some reason is still running at the back. So I try to understand why here it is telling "If users have the Azure Information Protection client installed, by default, the built-in labeling client is turned off in their Office apps" and we already run the MS Support case, because it was a "break-fix: case we only received a solution to apply for registry entry the "useofficeforlabelling". But according to this document, to this sentence "If users have the Azure Information Protection client installed, by default, the built-in labeling client is turned off in their Office apps." we shouldn't do anything...

**Comment by cabailey** [comment]
The docs have instructions how to ensure the Azure Information Protection add-in remains loaded (or unloaded) in Office apps. By default, built-in labeling is turned off when the Azure Information Protection client is installed because the Azure Information Protection add-in takes precedence.  But there are some scenarios where the add-in can unload, so built-in labeling becomes active instead. From your description, it sounds like you're experiencing this issue in which case following the instructions to always enforce the add-in is the right course of action to follow.  If the problem persists after this, please follow up with Support.
