### ISSUE TITLE
"DLP Settings" section is missing descriptions for "Unallowed Bluetooth apps" and "Always audit file activity for devices" settings.

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/microsoft-365-docs#5188]
The "DLP Settings" section is missing descriptions for "Unallowed Bluetooth apps" and "Always audit file activity for devices" settings.  Please add them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76da4eda-4ccf-ff34-6a48-d9c5553c2ed6
* Version Independent ID: 7e887aff-1b85-1651-2bff-63425c54ae63
* Content: [Using  Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-using?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-using.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@mariuszo-at-microsoft-com Thank you for your feedback. We have added the missing information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5232. Once the author approves, the changes will be available on the live document.

Thanks
Sri
