### ISSUE TITLE
Documentation bug 

### ISSUE THREAD

**Issue by ilyapozharsky** [MicrosoftDocs/microsoft-365-docs#5191]
The documentation for running the local scripts on this page still refers to the old package name (WindowsDefenderATPOnboardingPackage.zip) in multiple places. 

The command to run the script also refers to the old script name. 

Documentation says to run 
%userprofile%\Desktop\WindowsDefenderATPOnboardingScript.cmd

Current script name is: 
DeviceComplianceLocalOnboardingScript.cmd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f044e756-d5d8-5db6-edbb-f042b1b22b3c
* Version Independent ID: 5d016fa2-3407-e757-1595-118728158c46
* Content: [Onboard Windows 10 devices using a local script](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-script?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-script.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-script.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@ilyapozharsky Thank you for your feedback. I downloaded the package from Defender Security center and still see WindowsDefenderATPOnboardingPackage.zip

![image](https://user-images.githubusercontent.com/45987684/120801518-e2f16280-c55e-11eb-8e07-6a69d12abd78.png)

Thanks
Sri

**Comment by mjcaparas** [comment]
Addressed by msbemba pr 5222
