### ISSUE TITLE
There is no "Organization Theme" link

### ISSUE THREAD

**Issue by jeffreyoliver** [MicrosoftDocs/microsoft-365-docs#5193]
I'm logged in with my Global Admin account and browse to Settings --> Org Settings. Then I click on the "Organization Profile" tab. There is no Organization Theme link here. The only thing I see is "Custom Themes"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6c85cc-1680-588e-f520-bcafb1383d53
* Version Independent ID: ea446e6b-e094-dacd-54cc-e597b2f1354d
* Content: [Customize the theme for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/customize-your-organization-theme?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/customize-your-organization-theme.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/customize-your-organization-theme.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jeffreyoliver Thank you for your feedback. Yes, It has been changed to custom themes. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5221

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jeffreyoliver Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
