### ISSUE TITLE
No update on the changes over New Exchange Admin center 

### ISSUE THREAD

**Issue by yashbhilware** [MicrosoftDocs/microsoft-365-docs#5195]
I certainly enjoy the change but few thing they are considering that compliance portal can handle but i guess they are far behind to give that feature available through changes. 

One of the important feature i am considering here is Retention tags, and I strongly believe this feature should not be remove.
 
![image](https://user-images.githubusercontent.com/80253684/120541215-394b8d80-c407-11eb-9586-bbf527ddc472.png)
from https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/default-retention-policy

They say Retention policy from compliance center should take care of it from here. But i strongly disagree. There is no option to create tag on the basis of folders, No labels for moving data into archives after certain period.

MRM is not part of legal compliance, Team has to understand that it is always the part of Mailbox Hygiene and should still be there. 

In this specific article they are not even talking on how to handle 3 year, 4 year and 5 year move to archive through new portal updates be it be Exchange admin center or Compliance portal.

Please suggest! how we can achieve?

~Yash from CloudNerdy
yash@cloudnerdy.onmicrosoft.com/yashbhilware@hotmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@yashbhilware Thank you for your feedback.

1. You should continue using MRM to move messages to archive mailboxes as the feature is not available yet in the New exchange admin center or compliance center. Once the feature if available, you will see that added to the document.

2. Retention labels can be applied on folder level in outlook -https://docs.microsoft.com/en-us/microsoft-365/compliance/create-apply-retention-labels?view=o365-worldwide#manually-apply-retention-labels

The recommendation is to use retention policy and retention labels from the compliance center for proactive deletion or retention as this is a single mechanism to control the content across Microsoft 365. Also, note that MRM will continue side by side with the retention policy and labels as mentioned in the document.

Hope this helps!

Thanks
Sri
