### ISSUE TITLE
Word Repetition

### ISSUE THREAD

**Issue by thr0nes** [MicrosoftDocs/microsoft-365-docs#5200]
In the sentence: 

Advanced eDiscovery provides an end-to-end workflow to preserve, collect, analyze, review, analyze, and export content that's responsive to your organization's internal and external investigations. 

Analyze is repeated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd695b47-a713-a904-9f2e-9c6c3e27bb18
* Version Independent ID: 60198f81-59f6-5ad2-53ea-a4d352125026
* Content: [Overview of the Advanced eDiscovery solution in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/overview-ediscovery-20?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/overview-ediscovery-20.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/overview-ediscovery-20.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@thr0nes Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5218

Thanks
Sri
