### ISSUE TITLE
Indexing not implemented on keywordQuery["EnableMultiGeoSearch"]

### ISSUE THREAD

**Issue by himasusan90** [MicrosoftDocs/microsoft-365-docs#5201]
**keywordQuery["EnableMultiGeoSearch"] = true;** this line errors out saying KeywordQuery cannot be indexed. This has to be changed to **keywordQuery.Properties["EnableMultiGeoSearch"] = true;**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42ae5faa-8153-2236-7df4-a648388c5952
* Version Independent ID: 9c9a95de-76d6-1581-0c01-7d8a653acfa1
* Content: [Configure search for Microsoft 365 Multi-Geo - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-search-for-multi-geo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/configure-search-for-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/configure-search-for-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by msbemba** [comment]
@himasusan90 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5219

Thanks
Sri

**Comment by tklarsen** [comment]
closed
