### ISSUE TITLE
Phone number invalid

### ISSUE THREAD

**Issue by simionea** [MicrosoftDocs/microsoft-365-docs#5203]
The phone support number is not valid. Upon calling it hangs up right away.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8479060-e7dd-9d7f-6cd2-9954bdd59551
* Version Independent ID: d8abccbe-2b92-c1e0-b38b-7956b988ac41
* Content: [Support information for Moldova - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/moldova?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/moldova.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/moldova.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@simionea I'm sorry you had trouble reaching customer support for your location. Please send me the following information I can investigate this further: 

	• ANI (Caller's number)
	• Support # called
	• Date of call
	• Time of call with time zone
	• IVR options selected if any
	• Call results (description of the caller experience after calling)

Do not post this information here. Please send the information directly to me at: cmcatee@microsoft.com

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please update, if it was further investigated. Thanks

**Comment by cmcatee-MSFT** [comment]
@yogkumgit I've been working with internal support and with @simionea directly to get this resolved. Investigation is still ongoing.

**Comment by yogkumgit** [comment]
@simionea as Cern is working with you internally, so we proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
