### ISSUE TITLE
Use sensitivity labels as conditions in DLP policies Outlook bit versions

### ISSUE THREAD

**Issue by Marius-M7** [MicrosoftDocs/microsoft-365-docs#5204]
By "Outlook win 32" you mean Outlook 32bit version?
It's going to work on Outlook 64bit versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c2bb05c-4f7c-58cf-6b72-22af2b0377b1
* Version Independent ID: 184b8cb5-327a-41c5-6e61-1cae40965994
* Content: [Use sensitivity labels as conditions in DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-sensitivity-label-as-condition?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-sensitivity-label-as-condition.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-sensitivity-label-as-condition.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Marius-M7 Thank you for your feedback. I'm confirming this with the author and will update shortly. 

Thanks
Sri

**Comment by msbemba** [comment]
@Marius-M7 This refers to the 32-bit outlook client. It works on 64-bit outlook clients.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Marius-M7 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
