### ISSUE TITLE
Download link is not available. Please update the article 

### ISSUE THREAD

**Issue by raaghavvv** [MicrosoftDocs/microsoft-365-docs#5205]
Hi Team, 

I've found that the link in this article for " Microsoft Online Services Sign-in Assistant for IT Professionals RTW" is no longer available. Please update.

When you go to **Step 1: Install the required software**
There is point number 1 there is a download link associated  which give below error 

![image](https://user-images.githubusercontent.com/61713813/120642138-216d1b80-c492-11eb-9257-7c47dedf5931.png)

![image](https://user-images.githubusercontent.com/61713813/120641872-caffdd00-c491-11eb-9547-b42bd8ceb192.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55574af9-0105-dcd1-7eb0-77513df4e54f
* Version Independent ID: 5fe2849b-d39a-4d75-a5ce-e8f577c9a161
* Content: [Connect to Microsoft 365 with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@raaghavvv Thank you for your feedback. The option to download to the Microsoft Online services Sign -in assistant is no longer available. We have removed that part from the document.

Hope this helps!

@yogkumgit There are no changes required in this document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @raaghavvv Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
