### ISSUE TITLE
Data location for information that spans people in multiple geos

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#5206]
Please add details on how Teams handles chats that involve people from multiple geos - is it stored in both? Is it stored only in the geo of the person that started the chat? Is a conversation split between geos based on who posted the message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 279b8e5a-103f-087b-97f1-bc894d8503fc
* Version Independent ID: c365f29b-2baa-1914-9e1a-568405bf9abd
* Content: [Moving core data to new Microsoft 365 datacenter geos - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/moving-data-to-new-datacenter-geos?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/moving-data-to-new-datacenter-geos.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/moving-data-to-new-datacenter-geos.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. Conversations in chats, channel messages, and meeting IM notes/chats within the Teams experience aren't Multi-Geo-aware and are all kept only inside the central location of the tenant. Typically, chat conversations aren’t applied to data residency needs. 

I have added a related link to this document which talks in detail about Teams experience in a Microsoft 365 Multi-Geo-enabled tenancy -https://docs.microsoft.com/en-us/microsoftteams/teams-experience-o365odb-spo-multi-geo

The changes can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5282

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @danmyhre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danmyhre** [comment]
@msbemba this is actually going to be out of date soon with the release of multi-geo for Teams, which is why I posted the feedback. Thoughts on this?

**Comment by msbemba** [comment]
@danmyhre That is correct. The roadmap item for Teams Multi-geo support is still in development. The changes will be made on the document on the design change is live.

Thanks
Sri

**Comment by danmyhre** [comment]
It has already been announced in the admin center. We need to get the information posted prior to release for us admins!! :)
