### ISSUE TITLE
Localized article not having localized phone number

### ISSUE THREAD

**Issue by PascalStil** [MicrosoftDocs/microsoft-365-docs#5208]
The article is available in several localized languages, but the numbers under phone support still only show United States, Australia, Canada and United Kingdom, which doesn't really make sense in localized versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9fe16db-f502-6d93-8e0a-d4b892064416
* Version Independent ID: 1ecf27fd-ed6c-f387-b56a-80673117e480
* Content: [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/get-help-support.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@PascalStil We don't have a way to put the locale-specific support numbers in the localized pages. Please use the drop-down list that's included in the article to find support numbers for your locale or region.
