### ISSUE TITLE
Permissions no longer listed in S&C

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/microsoft-365-docs#5212]
I'm not sure where they were moved to, but the steps in this page no longer work - 'Permissions' must have been moved to the new Compliance center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94e0469-2c5c-2063-8c3e-7722ceb53577
* Version Independent ID: e99eb8aa-b3b7-8791-aba4-998e209694b5
* Content: [Assign eDiscovery permissions in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/assign-ediscovery-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/assign-ediscovery-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@pyoungberg Thanks for heads up. Permissions have been moved to the M365 compliance center. You can go to https://compliance.microsoft.com, click on Permissions in the left nav, and then click Roles under Compliance center. UI is very similar to the one in SCC. I will update the topic.
