### ISSUE TITLE
Is ownership of a mailbox transferred to the manger as with OneDrive?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#522]
OneDrive retention states, "by default, when you delete a user, ownership of the OneDrive is transferred to the user's manager."  (From article located here:  https://docs.microsoft.com/en-us/onedrive/retention-and-deletion#configure-automatic-access-delegation)
Is this default ownership transfer the same for mailboxes as well?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Overview of inactive mailboxes in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@Canis-Lupis - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@Canis-Lupis No, there isn't any kind of transfer of mailbox ownership. But you can:

- Use eDiscovery tools to search and export content from inactive mailbox.
- [Restore inactive mailbox](https://docs.microsoft.com/en-us/microsoft-365/compliance/restore-an-inactive-mailbox), which means to merge/import content from inactive mailbox to an active mailbox
- [Recover inactive mailbox](https://docs.microsoft.com/en-us/microsoft-365/compliance/recover-an-inactive-mailbox), which means to convert inactive mailbox to a new, active mailbox.
