### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gianlucadardia** [MicrosoftDocs/microsoft-365-docs#5224]
[Enter feedback here]

Link 
Learn more about Microsoft 365 Defender
https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-threat-protection

doesn't work
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881d6a41-be6c-430e-d4f3-26e08fa1bb50
* Version Independent ID: 5bb5aaaa-8d13-f3e1-52b1-3a043f7ff4fe
* Content: [Integrate Microsoft Defender for Endpoint with other Microsoft solutions](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/threat-protection-integration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/threat-protection-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/threat-protection-integration.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@gianlucadardia Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5267

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gianlucadardia Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
