### ISSUE TITLE
PowerShell command not working

### ISSUE THREAD

**Issue by fmokren** [MicrosoftDocs/microsoft-365-docs#5225]
I'm able to set the EnableControlledFolderAccess value to any value using the Group Policy Editor. 
When I try to do it using PowerShell, 'Set-MpPreference -EnableControlledFolderAccess Disabled' for example, the property is not getting set.

I'm trying this on Windows 10 OS Build 19041.985. How can I report this to the product team?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25faafb3-297a-dbb1-651b-dcf18081e95b
* Version Independent ID: 61a3c7ca-8094-5219-7f7c-688124bab07c
* Content: [Enable controlled folder access](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-controlled-folders?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-controlled-folders.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@fmokren Thank you for your feedback. I'm currently testing this and will update you shortly.

**Comment by msbemba** [comment]
@fmokren  I was able to test and verify that it works. We recommend you contact Microsoft support via the need help section on the admin center.

![image](https://user-images.githubusercontent.com/45987684/121637034-6f8fa980-caa6-11eb-9ef4-55115f6f8d57.png)


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @fmokren Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. 
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
