### ISSUE TITLE
ATP Rebranded to MDO - fix link

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#5228]
[Please consider changing the Roadmap link from pointing to "Advanced Threat Protection" query to "Defender" (or similar?) - since the old "ATP" verbiage doesn't return all results for Defender for Office anymore after the rebrand on the Roadmap.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a86153a-3d20-abef-8525-c766839c0557
* Version Independent ID: 8af145e7-6b58-74f9-006a-bf6ab603e38c
* Content: [Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/defender-for-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@hudish Thank you for your feedback. I have made changes to the link via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5285

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @hudish Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
