### ISSUE TITLE
lists requirements for connectivity from a user's machine to Office 365

### ISSUE THREAD

**Issue by Taha1308** [MicrosoftDocs/microsoft-365-docs#5235]
“Endpoint data below lists requirements for connectivity from a user's machine to Office 365. It does not include network connections from Microsoft into a customer network, sometimes called hybrid or inbound network connections.”

“Endpoint data below lists requirements for connectivity from a user's machine AND NETWORK CONNECTIONS to Office 365.”

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by Taha1308** [comment]
1.	Documentation only states outbound settings
2.	Documentation only states requirements on clients, not servers
3.	Documentation only states hybrid configuration for Exchange Online <-> Exchange On Premise
4.	Concerns are we are going to open several subnet ranges bi-directional on multiple ports to key on premise services

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. This issue was resolved in the article **[Other endpoints not included in the Office 365 IP Address and URL Web service](https://aka.ms/o365otherips)**, which lists hybrid endpoints and other related information. -Kelley
