### ISSUE TITLE
Incorrect / Missing Documentation

### ISSUE THREAD

**Issue by gpriest-github** [MicrosoftDocs/microsoft-365-docs#5236]
We have an Exchange 2016 CU19 on premises environment, with Hybrid Services enabled for Exchange Online and also has HMA (Hybrid Modern Auth) enabled. What we are finding is, as we begin to turn on services like Microsoft Teams users are accessing the Calendar in the MSTeams app it was showing a blank AND creating MS Teams enabled meetings in through delegate calendars it was showing the following error:

 "Sorry, but we can't connect to the server right now. Please try again later"

We have configured our internet facing Cisco ASA firewalls using a script and the IP addresses found in this  article (those entries tagged as Exchange online). 

However I will specifically call out that this document is for outbound connections to Exchange Online and not the other way; see 

“Endpoint data below lists requirements for connectivity from a user's machine to Office 365. It does not include network connections from Microsoft into a customer network, sometimes called hybrid or inbound network connections.”

So this URL does not contain IP addresses that would be expected to be seen as INBOUND and hitting Exchange EWS. If I review the additional endpoint configuration using this document

Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise | Microsoft Docs
https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide

I find NO information on what IP addresses from Office 365 are expected to hit the Exchange 2016 CU19 on premise EWS service from Office 365 services (like MS Teams). The Microsoft Teams integration with Exchange Calendar and setup with this document

Integration between Skype for Business Online and Exchange server - Skype for Business Server 2015 | Microsoft Docs) 
https://docs.microsoft.com/en-us/skypeforbusiness/deploy/integrate-with-exchange-server/oauth-with-online-and-on-premises

I have raised a case via our Premier contract but simply being told to "provide feedback" to the article. I've also raised a business impact statement to our account manager due to the outage we've seen from this to the 1200 users on MS Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I'm sorry this issue has caused problems for you. It appears that the specific items you mention have been resolved in recent updates to the guidance in the article **[Other endpoints not included in the Office 365 IP Address and URL Web service](https://aka.ms/o365otherips)**. Please reply back if you need further clarification or feel that more specific guidance is needed. -Kelley
