### ISSUE TITLE
Include a Microsoft Teams section

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/microsoft-365-docs#524]
There needs to be a section specifically for Microsoft Teams that includes the Teams/Channel conversations, chats, and conversation. Which would be similar to the Skype for Business section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd33fd3f-2ee9-139e-5cb3-afc28acaadcf
* Version Independent ID: cbc94676-e994-137b-6ff6-f2dee2940393
* Content: [Office 365 Encryption for Skype, OneDrive, SharePoint, and Exchange](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange)
* Content Source: [microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-encryption-for-skype-onedrive-sharepoint-and-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@NickElniff -  Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for their consideration.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@KCCross - Can you please share your insights on this issue? 

Thank you.

cc: @kenwith

**Comment by KCCross** [comment]
Hey everyone. Update to this finally. We have some traction with the Teams team. It's going to take a bit to research the information and update the article here, but the research has begun. The task is on the January sprint and PMs and writers are signed up. Closing out this request. Thank you.
