### ISSUE TITLE
Revision request for platform version number

### ISSUE THREAD

**Issue by yoshiband** [MicrosoftDocs/microsoft-365-docs#5240]
[Enter feedback here]
Hello, whom it may concern,

I found the following description for the platform version 4.18.1911.3 in this page
> Known Issues
> When this update is installed, the device needs the jump package 4.10.2001.10 to be able to update to the latest platform version.

However, we can see that the jump package version is "4.18.2001.10" at [Microsoft Update Catalog site](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4052623).
By searching with "KB4052623", it shows as follows.

Update for Windows Defender Antivirus antimalware platform - KB4052623 (Version 4.18.2001.10) | Windows Defender | Updates | 4/30/2020 | n/a | 13.1 MB
-- | -- | -- | -- | -- | --

So, "4.10.2001.10" should be "4.18.2001.10", could you check this point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01ab32b-6045-10f0-2a73-598961814f55
* Version Independent ID: 5bdbaa76-52aa-9330-fb23-03e90a28e32f
* Content: [Manage Microsoft Defender Antivirus updates and apply baselines](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @yoshiband, and thank you for letting us know about this issue. I have updated the article and you'll see the changes live on the site soon. In the meantime, you are correct:  "4.10.2001.10" should be "4.18.2001.10" in the November 2019 platform release "Known issues" section. Thanks again for posting about this!

**Comment by yoshiband** [comment]
Thank you very much for revising this. 
I have confirmed. Thank you so quick response!!
