### ISSUE TITLE
Add-in Deployment: Prerequisite Roles

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#5243]
Need clarification on the following, as there's no documentation found that relate to "Other Admin roles" and add-in deployment:

> Global Admin is the recommended role with complete access to add-in management lifecycle. **_Other Admin roles have a limited access to add-in deployment lifecycle_**. If you're the person who purchased your Microsoft 365 for business subscription, you are the Global admin.

Is there anything that specifies which roles (other than Global Admin) can perform which actions with add-in deployment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32aaf301-bc79-ea37-f3fd-94ae9e9ab02f
* Version Independent ID: 7482cca5-faac-3276-8481-e6323cafef31
* Content: [Centralized Deployment FAQ - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide#which-admin-role-do-i-need-to-manage-add-ins-for-my-organization)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-FAQ.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-FAQ.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@SeanTGeoghegan Thank you for your feedback. Earlier, Exchange and Office apps admin used to have limited access to deploying add-in. However, the options are no longer available after the change to integrated apps. I have updated the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5293

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SeanTGeoghegan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
