### ISSUE TITLE
Information regarding adding all recordtypes using powershell?

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/microsoft-365-docs#5246]
I noticed that the documentation doesn't talk about what type of value to use as a parameter for RecordType. In the event that we would require to retain all RecordTypes for 1 year, is there a particular value that could be used? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Rykimaruh From documentation: "The audit record type the policy applies to. If you leave this property blank, you must select a user in the Users box. You can select a single record type or multiple record types:"

So you could retain all audit records to specified users. To retain all audit records for all record types, you might have to enter each records type in this field. List of record type values can be found here: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#auditlogrecordtype

**Comment by Rykimaruh** [comment]
But in the GUI, I was able to do some tests and it let me choose all of them without specifying a user.

I'm looking to replicate this

![image](https://user-images.githubusercontent.com/5460795/121100291-86dd4700-c7c7-11eb-96ee-97235e4dfbfd.png)
