### ISSUE TITLE
DLs with membership approvals set to CLOSED can still be upgraded to M365 group

### ISSUE THREAD

**Issue by glenrmag16** [MicrosoftDocs/microsoft-365-docs#5247]
The article states: 

Distribution lists where MemberJoinRestriction and/or MemberDepartRestriction is Closed = not eligible for upgrade.

However upon testing, it actually works.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb1e873-a684-ba18-21b4-33c2c4cf5aeb
* Version Independent ID: badad26e-0e5e-ab12-f3ae-b6cab759e7b8
* Content: [Upgrade distribution lists to Microsoft 365 Groups in Outlook - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/upgrade-distribution-lists.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/upgrade-distribution-lists.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@glenrmag16 Thank you for your feedback. I shall test this and update the document.

Thanks
Sri

**Comment by msbemba** [comment]
@glenrmag16 Thank you for your feedback. I was able to test it as well. The document is now updated via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5292

Thanks
Sri

**Comment by glenrmag16** [comment]
Hi, it still says "NO" where it should be "YES" under the "Eligible?" column. Which update are you talking about?

**Comment by msbemba** [comment]
@glenrmag16 Sorry about the confusion. It takes 24-48 hours after the PR has been approved by the Author. So ee will update you when that is complete.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @glenrmag16 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
