### ISSUE TITLE
Licences

### ISSUE THREAD

**Issue by JamieWilsonCC** [MicrosoftDocs/microsoft-365-docs#5249]
What are the licence requirements for custom sensitive information types? Can this be done within E3? “sensitive information types with Exact Data Match” has a Required licenses and permissions section however this page does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb7953e-5257-2578-4607-2d93940d6845
* Version Independent ID: 8e59d041-619e-d54f-f28e-faac2bc18ef2
* Content: [Get started with custom sensitive information types - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@JamieWilsonCC Thank you for your feedback. As mentioned in the document,  Your organization must have a subscription, such as Office 365 Enterprise, that includes Data Loss Prevention (DLP).  Yes, Office 365 E3 and E5 include DLP. This is a broader list as any subscription with DLP in it can get started with custom-sensitive information types.

For more information, you can view feature availability here for DLP-https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feature-availability

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JamieWilsonCC Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
