### ISSUE TITLE
Broken Link to UserVoice Page

### ISSUE THREAD

**Issue by ITSourcePro** [MicrosoftDocs/microsoft-365-docs#5259]
Under Shared Mailboxes:
Currently it's not possible to migrate a shared mailbox to a Microsoft 365 group. Is this something you want? Let us know. **Vote here**

The Vote here link goes to a link that no longer exist as Microsoft no longer uses UserVoice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/create-groups/compare-groups?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@ITSourcePro Thank you for your feedback. We will be moving away from UserVoice feedback sites on a product-by-product basis throughout the 2021 calendar year. So the link is no longer available and the same has been removed from the document. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5286

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ITSourcePro Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
