### ISSUE TITLE
Permissions for viewing Activity Explorer

### ISSUE THREAD

**Issue by MichaelRyan87** [MicrosoftDocs/microsoft-365-docs#5261]
Hello,

Should this:

Data from Endpoint DLP can be viewed in Activity explorer. There are four roles that grant permission to activity explorer, the account you use for accessing the data must be a member of any one of them.

Global admin
Compliance admin
Security admin
Compliance data admin
Global reader
Security reader
Reports reader

Be this:

Data from Endpoint DLP can be viewed in Activity explorer. There are four roles that grant permission to activity explorer, the account you use for accessing the data must be a member of any one of them.

Global admin
Compliance admin
Security admin
Compliance data admin

It would be great if I could give users who don't need admin access, the ability to view the activity explorer tab, but it appears to be only restricted to the admin roles, the readers do not provide permission. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@MichaelRyan87 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5291

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MichaelRyan87 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
