### ISSUE TITLE
Download Link for Junk E-Mail Reporting Add-in is dead

### ISSUE THREAD

**Issue by hakenbeck** [MicrosoftDocs/microsoft-365-docs#5262]
Hi,
the link provided in the "Install" section no longer works.
https://www.microsoft.com/download/details.aspx?id=18275

Kind regards
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d71dab-a58d-fbd9-c30f-14f5884f094e
* Version Independent ID: 13e0112c-213d-b462-7833-9d0fe30fc99c
* Content: [Install and use the Junk Email Reporting add-in for Microsoft Outlook - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by yogkumgit** [comment]
@siosulli Please us in resolving this issue. Thanks

**Comment by siosulli** [comment]
@Dansimp the issue I sent you on yesterday. Thanks!

**Comment by anthonynz** [comment]
+1

If I use the version that was available earlier this year, it results in an NDR for every junk message reported.

"Your message to abuse@messaging.microsoft.com couldn't be delivered"

**Comment by yogkumgit** [comment]
@Dansimp  Gentle reminder, please reply. Thanks

**Comment by yogkumgit** [comment]
Duplicate #5359
