### ISSUE TITLE
List of remediation actions that can be undone

### ISSUE THREAD

**Issue by DanielYusteAroca** [MicrosoftDocs/microsoft-365-docs#5263]
This article states that "In some cases, you can undo a remediation action." but does not list which remediation actions can be undone. 

The article https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-auto-investigation?view=o365-worldwide#undo-completed-actions is having a list of the actions on devices or files that can be undone in Microsoft Defender for Endpoint. 

It would be quite useful to have a similar list in this article,  to make clear which remediation actions on email can be undone in Microsoft Defender for Office365 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75038ca4-5640-5792-4dd9-0baeedb9ad29
* Version Independent ID: f87ee7c8-1869-295a-6d65-079681545baf
* Content: [Review and manage remediation actions in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
@DanielYusteAroca The article and section has a list of remediation actions that can be undone in the Microsoft Security Center. Can you clarify? Thanks

**Comment by DanielYusteAroca** [comment]
Sorry @yogkumgit and @JoeDavies-MSFT but in the article  [Review and manage remediation actions in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions?view=o365-worldwide) I can not find the list of remediation actions for email that can be undone.  Could you please share the link for such a list? 

I have the list in the article [Review remediation actions following an automated investigation](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-auto-investigation?view=o365-worldwide#undo-completed-actions) but all of these are actions for endpoints, as the article seems to be part of documentation for Microsoft Defender for Endpoint.

Thanks for you help.

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Do you have this information? Please reply and resolve. Thanks

**Comment by JoeDavies-MSFT** [comment]
Researching this now...

**Comment by JoeDavies-MSFT** [comment]
Based on current information, quarantine is the only available action to undo. I will update the article. Thanks for your question.
