### ISSUE TITLE
License Assignment Questions

### ISSUE THREAD

**Issue by adagioajanes** [MicrosoftDocs/microsoft-365-docs#5265]
Does the scheduler license get assigned to users, or to the Cortana account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db644b10-3e07-35eb-9f68-f0bf184e4c27
* Version Independent ID: 6c17de36-8318-651c-35a4-afa31fe4b84f
* Content: [Scheduler for Microsoft 365 FAQs](https://docs.microsoft.com/en-us/microsoft-365/scheduler/scheduler-faqs?view=o365-worldwide)
* Content Source: [microsoft-365/scheduler/scheduler-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/scheduler/scheduler-faqs.md)
* Service: **scheduler**
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @adagioajanes Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by adagioajanes** [comment]
I believe this should be added to the documentation. It is not clear on any of the Scheduler documentation what account needs to be licensed. Please add that the license must be assigned to the end user, not the Cortana account.
