### ISSUE TITLE
Query not working

### ISSUE THREAD

**Issue by RichardSwart** [MicrosoftDocs/microsoft-365-docs#5269]
If you copy and paste the query into the advanced editor and try and run it, it says Semantic error

Error message
'where' operator: Failed to resolve table or column expression named 'EmailPostDeliveryEvents'
How to resolve
Fix semantic errors in your query

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df69e1b-b972-1c13-3ad0-cfdc23cdc51f
* Version Independent ID: 11704756-a7bc-919d-1b1a-6b87c8f483ca
* Content: [Microsoft Defender for Office 365 in Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-center-mdo?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-365-security-center-mdo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-security-center-mdo.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@RichardSwart Thank you for your feedback. I was able to test the query and it seems to be working fine.

![image](https://user-images.githubusercontent.com/45987684/122440863-9bd18b80-cfba-11eb-90b4-3b75cf43a71c.png)


This could be more of an issue for your tenant, The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @RichardSwart Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
