### ISSUE TITLE
link for licencing information is not found

### ISSUE THREAD

**Issue by choccieman** [MicrosoftDocs/microsoft-365-docs#5278]
as title, link next to licencing goes to page not found.

**Comment by denisebmsft** [comment]
Hello @choccieman, and thank you for posting your question here. Can you please tell us to which article(s) your feedback applies?

**Comment by choccieman** [comment]
apologies - i didn't realise that using the page link didn't include the url. It's on the new scheduler docs https://docs.microsoft.com/en-us/microsoft-365/scheduler/scheduler-setup?view=o365-21vianet

**Comment by yogkumgit** [comment]
@AshaIyengar21 Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@AshaIyengar21 Gentle reminder, please reply. Thanks

**Comment by JoanneHendrickson** [comment]
section & link to the Scheduler pricing/licensing page is now included at the top of the article (will go live shortly).
