### ISSUE TITLE
Is Python still required after mdatp is installed?

### ISSUE THREAD

**Issue by dm3942** [MicrosoftDocs/microsoft-365-docs#5289]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Hi @dm3942, you don't specify which distribution you are using but, even if python isn't required by mdatp after installation, removing python would surely cause a lot of other issues.

**Comment by msbemba** [comment]
@dm3942 Thank you for your feedback. It is recommended not to remove python as it could cause a lot of other issues as suggested by Thomas.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dm3942 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
