### ISSUE TITLE
Installation log file path is wrong in the doc

### ISSUE THREAD

**Issue by haiderim** [MicrosoftDocs/microsoft-365-docs#5290]
It should be /var/log/microsoft/mdatp/install.log not /var/log/microsoft/mdatp_install.log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f88efa4-ff30-7f9d-bc89-22ee1c94098b
* Version Independent ID: 028b68d0-f721-bafd-5a7c-4ab2303081eb
* Content: [Microsoft Defender for Endpoint on Linux resources](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-resources?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-resources.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by konstruktoid** [comment]
Thanks for opening this issue @haiderim, PR submitted.
