### ISSUE TITLE
Typo in the first Note in "How retention works with Microsoft Teams" section

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/microsoft-365-docs#5300]
The first Note in the "How retention works with Microsoft Teams" section has an extra "a" in the first sentence.  It should read "and you delete a mailbox" instead of "and you a delete a mailbox".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Thanks for flagging!  Getting this fixed today.
