### ISSUE TITLE
Add note about disabling add-in acquisition from the ribbon for recommended features

### ISSUE THREAD

**Issue by AlexJerabek** [MicrosoftDocs/microsoft-365-docs#5302]
Add-ins such as Visio Data Visualizer, Bing Maps, and People Graph will still show up in the ribbon, even if an admin has disabled the Store. Users will be unable to download those add-ins, as expected, but may still wish to remove their display. To remove these links, admins must disable the store through GPO.

Internal ADO item and discussion [here](https://office.visualstudio.com/OC/_workitems/edit/5121015?src=WorkItemMention&src-action=artifact_link).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61e46dd-c1ff-dfec-5e0e-9f2e7251a5c1
* Version Independent ID: 49f69fa9-33e8-373f-a7f9-26b828510fda
* Content: [Manage add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-addins-in-the-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-addins-in-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@AlexJerabek Thank you for your feedback. We have added a note on the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5351

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AlexJerabek Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
