### ISSUE TITLE
broken link for Standalone EOP

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/microsoft-365-docs#5304]
Link at start of article for standalone EOP is https://docs.microsoft.com/en-us/exchange/standalone-eop/standaonline-eop but should be https://docs.microsoft.com/en-us/exchange/standalone-eop/standalone-eop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8878304-7f4b-15c3-d2b6-8a5583930199
* Version Independent ID: 329f3b45-a087-6743-0664-e74dd9e0fc46
* Content: [Exchange Online Protection (EOP) overview - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/exchange-online-protection-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/exchange-online-protection-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/exchange-online-protection-overview.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@softwarecraft Thank you for your feedback. We have made changes to the document  via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5315

Thanks
Sri

**Comment by chrisda** [comment]
@softwarecraft, in the future, you, too can make fixes like this yourself directly; no need to open a GitHub Issue first. For instructions, see <https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/README.md>.

Thanks again for the feedback.

Closing (related PR approved)
