### ISSUE TITLE
An additional video of the Guest experience where MFA is mandatory for guest accounts

### ISSUE THREAD

**Issue by alex--thomas** [MicrosoftDocs/microsoft-365-docs#5306]
[Enter feedback here]
It would be a very useful enhancement of this content to also have a video of the Guest user experience where the guest account policy includes a MFA experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ace0390-915a-9b19-83cb-19d4aaffbb02
* Version Independent ID: d8d29213-a347-922a-c1d4-9db0e4d2704d
* Content: [Join a team as a guest](https://docs.microsoft.com/en-us/microsoft-365/business-video/join-team-guest?redirectSourcePath=%252farticle%252fjoin-a-team-as-a-guest-928d1eef-61e2-49ec-b754-c2fe86b34824&view=o365-worldwide)
* Content Source: [microsoft-365/business-video/join-team-guest.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/join-team-guest.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by yogkumgit** [comment]
@efrene Please help us in resolving this issue. Thanks.

**Comment by efrene** [comment]
@alex--thomas - Thank you so much for this great feedback.  I'll look into the possibility of doing this. Thanks again!
