### ISSUE TITLE
Microsoft 365 Defender REST API Internal Server Error and OData Protocol $filter System Query Option

### ISSUE THREAD

**Issue by 0xThiebaut** [MicrosoftDocs/microsoft-365-docs#5307]
When interacting with the [Microsoft 365 Defender API](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-error-codes?view=o365-worldwide), an internal server error occurs if the OData Service Model is requested in the JSON format, as specified in the [OData v4.01 URL Conventions section 4.1](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingtheModelforaService).

The documentation states that in the absence of an error code, Microsoft should be contacted without specifying where/how this should occur.
> 
> InternalServerError | Internal Server Error (500) | Note: No error message,  retry the operation or contact Microsoft if it does not get resolved
> -- | -- | --
> 
> 

Could the documentation be completed to indicate how these kinds of errors could be reported? The documentation does further not specify whether the [`$format` system query option](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31358963) is globally supported (as would be required by the OData protocol) or not. This is quite important given model endpoints (e.g.: `/incidents`) return JSON by default whereas the model endpoint (i.e. `/$metadata`) returns XML by default.

Compliance with the OData protocol is initially mentioned at [Supported Microsoft 365 Defender APIs](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-supported?view=o365-worldwide):
> All APIs along the `/api` path use the OData Protocol; for example, https://api.security.microsoft.com/api/incidents.

```
=== RUN   TestApi_MetadataJSON
==== Querying	https://api.security.microsoft.com/api/$metadata?%24format=json
==== Response	Code 500
{
  "error": {
    "code": "",
    "message": "An error has occurred."
  }
}
    incident_test.go:31: 500 Internal Server Error
--- FAIL: TestApi_MetadataJSON (2.47s)

=== RUN   TestApi_MetadataXML
==== Querying	https://api.security.microsoft.com/api/$metadata?%24format=xml
==== Response	Code 200
<?xml version="1.0" encoding="utf-8"?><edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx"><edmx:DataServices><Schema Namespace="microsoft.windowsDefenderATP.api" xmlns="http://docs.oasis-open.org/odata/ns/edm"><EntityType Name="AdvancedHunting"><Key><PropertyRef Name="query" /></Key>...
--- PASS: TestApi_MetadataXML (0.12s)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2334c49d-0ba7-e015-b987-ff5aa46fede2
* Version Independent ID: b3a79951-1800-3f8d-eb46-a494e9f58e7f
* Content: [Common Microsoft 365 Defender REST API error codes](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-error-codes?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/api-error-codes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/api-error-codes.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@0xThiebaut Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5318

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @0xThiebaut Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
