### ISSUE TITLE
Update PowerShell samples

### ISSUE THREAD

**Issue by JetzeMellema** [MicrosoftDocs/microsoft-365-docs#5310]
1. Correctly capitalize Set-Mailbox and Get-Mailbox.
2. Add -Identity parameter for consistency with other docs.
3. Get-Mailbox returns only 1000 items by default and will fail to give result if the Scheduler Assistant mailbox is not included in the first 1000 mailboxes, add -ResultSize Unlimited to search all mailboxes.

Now:
Set-mailbox cortana@contoso.com -SchedulerAssistant:$true

Should be:
Set-Mailbox -Identity cortana@contoso.com -SchedulerAssistant:$true

Now:
Get-mailbox | where {$_.PersistedCapabilities -Match "SchedulerAssistant"}

Should be:
Get-Mailbox -ResultSize Unlimited | where {$_.PersistedCapabilities -Match "SchedulerAssistant"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d33f8e34-9baa-3efd-b1cc-03f3e3ab44f0
* Version Independent ID: 201878c7-a0d7-a744-c60c-d65f714d2a9d
* Content: [Setting up Scheduler for Microsoft 365.](https://docs.microsoft.com/en-us/microsoft-365/scheduler/scheduler-setup?view=o365-21vianet&source=docs)
* Content Source: [microsoft-365/scheduler/scheduler-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/scheduler/scheduler-setup.md)
* Service: **scheduler**
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by msbemba** [comment]
@JetzeMellema Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5319

The changes will reflect once the author approves the PR.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JetzeMellema Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
