### ISSUE TITLE
Powershell or Graph API for Activity Explorer

### ISSUE THREAD

**Issue by sumitmodi84** [MicrosoftDocs/microsoft-365-docs#5313]
[Do you have any graph api or powershell commands to query activities. Could not find any documentation for the same.
https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer?view=o365-worldwide]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 824cab2c-6c02-7661-745a-75f555576067
* Version Independent ID: c11ebc43-42ce-6a5d-8e8f-dc3ea4d13405
* Content: [Get started with activity explorer - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-activity-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-activity-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@sumitmodi84 Thank you for your feedback. There is no Graph API or PowerShell at the moment, we will update the document once it is made available.

Hope this helps!

Thanks
Sri

**Comment by sumitmodi84** [comment]
@msbemba Thanks for the update.
Cany you also help me with the following
- Is it in Roadmap? 
- Is there any way i can listen to sensitivity events in real time like webhooks

**Comment by msbemba** [comment]
@sumitmodi84 Thank you for your feedback. We do not have it in the roadmap yet and don't have a way to listen to sensitive events. Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-compliance.html). 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sumitmodi84 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
