### ISSUE TITLE
How to put Windows Defender Antivirus in Passive Mode on Server 2019

### ISSUE THREAD

**Issue by surje23** [MicrosoftDocs/microsoft-365-docs#5316]
I'm running Windows Server 2019 Standard Version 10.0.17763 Build 17763, and I tried the registry entry you provided to put Windows Defender Antivirus in Passive Mode, but even after adding that key and restarting, when I run the Get-MpComputerStatus PowerShell cmdlet the AMRunningMode line still shows Normal.  Do you have any other directions on how to put Windows Defender Antivirus in Passive Mode or is that not possible on the version of Windows Server that I'm running?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9a2869-614c-e077-8d71-351448810897
* Version Independent ID: 09369dc3-f8d1-9b19-0043-47fa733a3b81
* Content: [Microsoft Defender Antivirus on Windows Server](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @surje23. Thank you for posting this question. I will look into this issue and will post an update here soon.

**Comment by surje23** [comment]
Any progress?

Thank you,
Stephen Jordan

From: Denise Vangel-MSFT ***@***.***>
Sent: Monday, June 14, 2021 11:09 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: S Jordan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/microsoft-365-docs] How to put Windows Defender Antivirus in Passive Mode on Server 2019 (#5316)


Hello @surje23<https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcOoW5neFPaXpljg0nEEvDfYq3gujH4PEanQBBSvmw_BOQ23y5qcjjQI-7ASZZMSYHQ~~>. Thank you for posting this question. I will look into this issue and will post an update here soon.

-

**Comment by denisebmsft** [comment]
Hello @surje23. Yes, I have an update. The docs have been updated to do a better job of explaining passive mode on Windows Server and how to set it as such. Please see https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server?view=o365-worldwide#need-to-set-microsoft-defender-antivirus-to-passive-mode. Thank you!

**Comment by surje23** [comment]
Hi Denise,

I have reviewed the article at the link you provided, and tough it is clearly explained, that process for putting Microsoft Defender Antivirus in passive mode on Server 2019, namely that registry change, does not work.  However, if my reaching out to others in the industry hasn't lead me down an incorrect path, I believe what might be missing from this article is the process others are telling me about for onboarding those servers through Microsoft Endpoint Manager, something I know nothing about and that I haven't done.  So, I think the problem is that there is more to this story than just what is contained in that article. Or in other words, I think that article assumes some additional steps have been taken beyond just installing Windows Server 2019.  If nothing else has been done other than Windows Server 2019 being installed, which automatically installs Microsoft Defender Antivirus, then that registry change is not going to work.  If you believe I'm incorrect, please feel free to set me straight, and I don't mind paying for some consulting time for that if needed.

This link below talks about the onboarding process:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide

Thank you,
Stephen Jordan
(432)570-8324 (Option 1 for sales.)

[Logo12%]<http://www.techwiseit.com/>

From: Denise Vangel-MSFT ***@***.***>
Sent: Tuesday, July 20, 2021 5:50 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: S Jordan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/microsoft-365-docs] How to put Windows Defender Antivirus in Passive Mode on Server 2019 (#5316)


Hello @surje23<https://url.emailprotection.link/?buEq4eyNl9NRYRhKUfm4VcOoW5neFPaXpljg0nEEvDfYq3gujH4PEanQBBSvmw_BOQ23y5qcjjQI-7ASZZMSYHQ~~>. Yes, I have an update. The docs have been updated to do a better job of explaining passive mode on Windows Server and how to set it as such. Please see https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server?view=o365-worldwide#need-to-set-microsoft-defender-antivirus-to-passive-mode<https://url.emailprotection.link/?bGc_Vm5f3ezqpCyzqYPaSIoKZsrkrePiRE24PwaHFtnaIrEH4aFELLt6POZruAmwkHHMBf176kpcXfiDHv4rXn5v1cdgqD5J2Upo_UWEvnzayElW_Q2vLzZvl3-_6q6y8FcD9IXxxQnMCCXuX8bBFczR1Rd40jFwHhbcIJINYplNMt7XywaCyw0RtdYzFbneoZ2QP25NYSLCp7g8KCIbAsA~~>. Thank you!

-
