### ISSUE TITLE
Several GPO options are wrong in the documentation

### ISSUE THREAD

**Issue by jdcc2** [MicrosoftDocs/microsoft-365-docs#5327]
In the "Update endpoint protection configuration" section the "Enable sample collection on machines" policy option Is not located at "\Windows Components\Windows Defender SmartScreen*" but at "\Windows Components\Windows Defender ATP/".

Furthermore, the policy location " \Windows Components\Microsoft Defender AntivirusScan" does not exist an should probably be  \Windows Components\Microsoft Defender Antivirus\Scan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523651c3-a318-2369-6892-d13e04991596
* Version Independent ID: 624c5e05-f87d-1bd4-bc87-bd55dcac1d86
* Content: [Onboard Windows 10 devices to Microsoft Defender for Endpoint via Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-gp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jdcc2 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5401

Thanks
Sri
