### ISSUE TITLE
License Required for Insider Risk Management in Government - GCC

### ISSUE THREAD

**Issue by lmarianko** [MicrosoftDocs/microsoft-365-docs#5329]
Insider Risk Management license states that this license is required: Microsoft 365 G5 subscription (paid or trial version)
Be aware that this license is not an active SKU in government clouds yet.    There is only still Office 365 G5 and Enterprise Mobility and Security E5.  What license do you need in GCC for using Insider Risk Management?  I assume you also need the Compliance add on?  The only thing I see in GCC for compliance add on is "Compliance Manager Premium Assessment Add-On for GCC".  Is that what you need?  Or is that an Insider Risk Management add on?  Tx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb98e0ff-d34c-75bc-0ade-7dc70fc7f4bd
* Version Independent ID: 5172471f-e514-bcde-16e0-d8d8090a892a
* Content: [Get started with insider risk management - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-configure?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-configure.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by robmazz** [comment]
@lmarianko - thanks for the feedback, Have you checked the Microsoft 365 Government - how to buy topic (https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy)? The Microsoft 365 Government G5 plan includes support for insider risk management.

**Comment by yogkumgit** [comment]
@lmarianko Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
