### ISSUE TITLE
Document Microsoft 365 Defender API OData Protocol Version

### ISSUE THREAD

**Issue by 0xThiebaut** [MicrosoftDocs/microsoft-365-docs#5330]
The documentation states the following:
> All APIs along the `/api` path use the OData Protocol; for example, https://api.security.microsoft.com/api/incidents.

Could you extend the documentation to specify which OData protocol the API uses? According to the API's `$metadata` endpoint it would be `4.0` which I'd like confirmation of.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf3971a-9371-bd6b-6848-9c0564dbd4db
* Version Independent ID: a9c7c896-8f44-9447-1465-a7510a16d27e
* Content: [Supported Microsoft 365 Defender APIs](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-supported?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/api-supported.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/api-supported.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@0xThiebaut Thank you for the feedback. You are correct, the API uses Open Data Protocolversion 4.0.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @0xThiebaut  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
