### ISSUE TITLE
日本語訳でX-MS-Exchange-EnableFirstContactSafetyTipの値が分からなくなっている。

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/microsoft-365-docs#5333]
値が有効な X-MS-Exchange-EnableFirstContactSafetyTip という名前のメッセージヘッダーをメッセージに追加することをお勧めします。 
と表示されているが、ヘッダーにはNameとValueを設定する必要がある。
よって以下のような記述が正しくなる。
X-MS-Exchange-EnableFirstContactSafetyTip という名前のメッセージヘッダーを作成して値にEnableと設定し、メッセージに追加することをお勧めします。 

English translation:

> We recommend that you add a message header to the message that is named X-MS-Exchange-EnableFirstContSafetyTip with a valid value.

But the header must be set to Name and Value.

Therefore, the following description becomes correct:

> We recommend that you create a message header named X-MS-Exchange-EnableFirstContActSafetyTip, set the value to Enable, and add it to the message.

Topic in question is [Anti-phishing policies in Microsoft 365](/microsoft-365/security/office-365-security/set-up-anti-phishing-policies)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?WT.mc_id=M365-MVP-5002496&view=o365-worldwide#impersonation-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TomoharuMisawa, I updated the text as you described.

Thanks for the feedback.

Closing
