### ISSUE TITLE
Cloud Shell Information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#5335]
Please add some information about how to use the Cloud Shell editor in the M365 Admin Center to this documentation. This is a big gap
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2917486-3681-3696-9358-a569d19b8cd9
* Version Independent ID: 4b1b7859-a4c7-0a14-f80e-2012ed0eaf10
* Content: [Get started with PowerShell for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/getting-started-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/getting-started-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/getting-started-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
@DeanGross Hi Dean! I have updated the article for the Cloud Shell editor in the M365 Admin Center. Thanks for letting us know!
