### ISSUE TITLE
GCC specific urls for endpoints

### ISSUE THREAD

**Issue by junterpfe** [MicrosoftDocs/microsoft-365-docs#5336]
now that PowerAutomate/Apps has has it's split for GCC they land here
gov.flow.microsoft.us
make.gov.powerapps.us
apps.gov.powerapps.us
do we need to update the doc to reflect this since it is still showing GCC/Worldwide or should we split them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@LauraWi Gentle reminder.

**Comment by junterpfe** [comment]
Any ideas when this might be updated? many of our customers won't even consider unblocking something if it isn't in this list.

**Comment by LauraWi** [comment]
This is still sitting with engineering. I will ping them again. This topic is autogenerated and cannot be updated manually by writers, so updated info needs to flow through an internal process/tool.

**Comment by junterpfe** [comment]
Thanks for the update @LauraWi let me know if there is anything i can do to help.

**Comment by junterpfe** [comment]
@LauraWi any news?

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. It appears that all of the endpoints you mentioned have been removed from the web service entirely. I will follow up with the engineering team to find out why, and they will have to determine whether this is an actual issue or the result of a deliberate decision. In the meantime, I am closing this issue as we cannot resolve it directly. -Kelley
