### ISSUE TITLE
Enabling Security Defaults does not award full points for an improvement action mentioned on this page

### ISSUE THREAD

**Issue by jurjenoskam** [MicrosoftDocs/microsoft-365-docs#5337]
Under the heading "Security Defaults", the following is stated:

> If you turn on security defaults, you'll be awarded full points for the following improvement actions:
>
> *  Ensure all users can complete multi-factor authentication for secure access (9 points)

In a tenant I manage, this is not the case. Security Defaults is enabled, but the improvement action only gets some of the points awarded, not all. I have submitted a Support Request, and received the reply stating that this was working as designed.

Could this paragraph be updated to not mention that full points will be awarded for the improvement action mentioned above?

(Tenant ID and Support Request ID available on request)

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a57c0a2-0a6c-4499-f31e-18016d006549
* Version Independent ID: 5587ca01-e40f-478d-1796-b7b4dc41cbf0
* Content: [Microsoft Secure Score](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-secure-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-secure-score.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jurjenoskam Thank you for your feedback. I have tested and the Secure score does increase when the recommendations like Security defaults are enabled. If you have waited for over 24 hours, The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide).  as there could be an issue specific to the tenant.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @jurjenoskam 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jurjenoskam** [comment]
@yogkumgit @msbemba I already have gone through a Support Request, the number of which I can send you if you like. They saw the same thing as what I and @msmemba above saw: the Secure Score for the improvement point "Ensure all users complete multi-factor authentication for secure access" did indeed _increase_ when Security Defaults is enabled, but **the documentation says something else**:

>   If you turn on security defaults, you'll be awarded **full points** for the following improvement actions:
>
>     * Ensure all users can complete multi-factor authentication for secure access (9 points)

(Emphasis mine)

The documention states that all 9 points are awarded when Security Defaults are enabled, but that is _not_ what happens: it only _increases_ a few points. In the Support Request it was determined that the current behavior is by design, and that the documentation should not state that **full points** are awarded for this improvement action.

**Comment by msbemba** [comment]
@jurjenoskam I'll verify this internally and update the document if need be.

Thanks
Sri
