### ISSUE TITLE
Automation options

### ISSUE THREAD

**Issue by pieterhancke** [MicrosoftDocs/microsoft-365-docs#5341]
Is there any way to create / manage roles outside of the UI, for example PowerShell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 796818f1-67d6-9a20-9498-94baf03276d6
* Version Independent ID: a9293050-acc0-7710-52cf-5cf64689d719
* Content: [Create and manage roles for role-based access control](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/user-roles?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/user-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/user-roles.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@pieterhancke Thank you for your feedback. You can use PowerShell to assign basic permissions to access the portal. The document -https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/basic-permissions?view=o365-worldwide talks about this in detail.

We don't have options to assign more granular or RBAC roles via PowerShell yet. 

Hope this helps!


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @pieterhancke Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
