### ISSUE TITLE
Policy Tips and conditions for overrride

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#5342]
We may want to consider updating the documentation to indicate when the user will get an override justification window. 

we were advised by support that the behavior is as follows:

<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/dakotars/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel="themeData" href="file:///C:/Users/dakotars/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/dakotars/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

Notification Rule | Notify/Block | Override | Require Justification
-- | -- | -- | --
Notify Only | Notify | No | No
Notify + AllowOverride + False positive + With Justification | Notify | No | No
Notify + AllowOverride | Notify | Yes | No
Notify + Block | Block | No | No
Notify + Block + AllowOverride | Block | Yes | No
Notify + Block + AllowOverride + With Justification | Block | Yes | Yes

It may be worth including this in the article to remove confusion, or referring to the article where this information appears.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
Hi @dkotars - This is great information. Can you share with me (chrfox@microsoft.com) who in support gave you this table?  I want to include it in upcoming documentation.

**Comment by dkotars** [comment]
Ravi Sharma - ***@***.***

Respectfully,

Dan Kotarski

Customer Engineer
Messaging/Security and Compliance
Microsoft Services

Upcoming PTO:
June 18 , 2021
July 15 (Afternoon), 2021
July 21-27, 2021
Office: +1 (518) 292-2983
***@***.******@***.***>
[Twitter]<https://twitter.com/Microsoft>    [Facebook] <https://www.facebook.com/Microsoft>     [Linkedin] <https://www.linkedin.com/company/microsoft>     [Youtube] <https://www.youtube.com/user/Microsoft>

[A picture containing drawing, woman, red, blue  Description automatically generated]
[Microsoft 365 Certified: Enterprise Administrator Expert]
[Microsoft 365 Certified: Security Administrator Associate]
[Microsoft 365 Certified: Messaging Administrator Associate]
[Microsoft Certified Trainer 2019-2020]
[A picture containing clock, room, white, blue  Description automatically generated]

Schedule some time with me via ***@***.***>

**Comment by yogkumgit** [comment]
@chrfox can we proceed and close it? Thanks

**Comment by chrfox** [comment]
keep this open I am tracking this here
