### ISSUE TITLE
Common Attacks and Microsoft Capabilities That Protect Your Organization Last Rev 2017 - Need Update or Removal?

### ISSUE THREAD

**Issue by doug-strother** [MicrosoftDocs/microsoft-365-docs#5347]
Greetings,

The Cloud Architecture Model referenced herein is from 2017. 

Many features have been renamed or evolved. The branding should be updated.

Content is lagging behind - example, attack concepts such as APT should be added and existing attack concepts freshened up. 

Or if a better poster exists anywhere else on docs.microsoft.com. perhaps that can be leveraged or used as replacement.

I regularly use visual aids such as this for my own learning and to inform and educate my customers. They are a great resource.

Please accept my feedback as constructive and in good faith. Thanks.

-Doug

https://docs.microsoft.com/en-us/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide#common-attacks-and-microsoft-capabilities-that-protect-your-organization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91837ba8-f6f2-3c52-2d89-c8f4c4bce09c
* Version Independent ID: eb3c1fd8-9143-0dc1-77e7-e664ccaefc33
* Content: [Microsoft cloud architecture models - enterprise resource planning](https://docs.microsoft.com/en-us/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/cloud-architecture-models.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/cloud-architecture-models.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by yogkumgit** [comment]
@samanro Please help us in resolving this issue. Thanks

**Comment by samanro** [comment]
@BrendaCarter - do we have this page on the list to update with our vendors?

**Comment by BrendaCarter** [comment]
Hi Doug, Thank you for this request! I'm working with a partner to update this poster. If you would like to be included in the review, please email me -- bcarter @ micrsoft.com

**Comment by yogkumgit** [comment]
@BrendaCarter Is the issue resolved and can be closed? Please reply. Thanks
