### ISSUE TITLE
Attack Simulator Brute Force Attacks No Longer Functioning 

### ISSUE THREAD

**Issue by thequesarito** [MicrosoftDocs/microsoft-365-docs#535]
We are using the brute force simulator to find out which users who are not yet on MFA have basic passwords. 
Previously we were able to confirm that this works for users not on MFA. However, I noticed no users failed my last attempt. To confirm that it was working correctly we tested this with user accounts that we reset the passwords for, and it didn't work when entered manually and when put on a .csv. We know the passwords were the same as were entered, yet we saw 0 compromised users. 
What is extra strange is that on the mentioned user accounts we actually saw this log on as successful.

**Comment by mypil** [comment]
@thequesarito - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by thequesarito** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator#brute-force-password-attack

**Comment by mypil** [comment]
@thequesarito -  Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
