### ISSUE TITLE
MFA Setup guide is not consistent.

### ISSUE THREAD

**Issue by artur-gawrych** [MicrosoftDocs/microsoft-365-docs#5353]
In the video user is asked to select **"Receive notifications for verification"**, but at the end of the video he's asked to take a note of the code displayed on a mobile device and enter the code manually rather than use the notification option.

I was hoping to share this video with my clients but it would cause more problems and confusion than help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 394141f6-743e-48b1-55f6-041128648f1b
* Version Independent ID: c4aed007-2735-8e67-44c9-db6f555595d2
* Content: [Set up multi-factor sign-in on your phone](https://docs.microsoft.com/en-us/microsoft-365/business-video/set-up-mfa?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/set-up-mfa.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/set-up-mfa.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@artur-gawrych Thank you for your feedback. At the end of the video, the option to use a verification code to contact was selected at 0.42

That is why you notice the narrator asking to copy the verification code.

Hope this helps!

Thanks
Sri

**Comment by artur-gawrych** [comment]
You're right, my bad.

**Comment by mordyort** [comment]
it seems the video is completely out of date for new tenants can we get an updated video
