### ISSUE TITLE
Incorrect selection Name

### ISSUE THREAD

**Issue by haydanbarry** [MicrosoftDocs/microsoft-365-docs#5354]
[Enter feedback here]
Step 4 on this page is:
4. Select the user's name to go to their properties pane, and on the Account tab, select Initiate sign-out.

Please change "select Initiate sign-out" to "Sign out of all sessions".  This is what is actually displayed on the Accounts section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ecd4f58-0a50-05f2-426d-6bc8ca8f5940
* Version Independent ID: b3344450-204e-3bb4-54ad-5fa4f85a2695
* Content: [Step 1 - Stop an employee from logging in to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-1?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-1.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@haydanbarry Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5379

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @haydanbarry Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
