### ISSUE TITLE
Steps out of date?

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/microsoft-365-docs#5356]
The set of steps on this page don't appear to be accurate anymore. In Step 2 there isn't any "Increase protection from advanced threats" on the Setup page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43be63d8-b28e-1a2c-e2d5-7e0e55919553
* Version Independent ID: 56399ab7-cd7f-bd65-afe0-a8724ae28b60
* Content: [Manage Safe Links](https://docs.microsoft.com/en-us/microsoft-365/business-video/safe-links?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/business-video/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/safe-links.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Beschorr Thank you for your feedback. We have made changes to the steps via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5403

Meanwhile, Steps 1 and 2 still remain the same. If you have the Microsoft Defender ATP license, you should be able to see the options.

Thanks
Sri

**Comment by Beschorr** [comment]
Thanks Sri. I was looking at an M365 Business Premium admin center when it appeared that the steps were different. Perhaps we need some note for customers using that SKU that their steps may appear slightly different?

Ben Schorr (he/him)
Senior Content Designer | Experiences + Devices | Microsoft 365 Cybersecurity
https://support.microsoft.com/security
[Microsoft Logo]
________________________________

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Beschorr Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
