### ISSUE TITLE
Junk email reporting add-in tool broken.

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/microsoft-365-docs#5359]
The link to download the Report Junk Email add-in is dead.

On this page:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook?view=o365-worldwide#install-the-junk-email-reporting-add-in

The download link:
https://www.microsoft.com/download/details.aspx?id=18275

And actually, the add-in sends junk reports to abuse@messaging.microsoft.com which now produces NDR for an unknown address

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d71dab-a58d-fbd9-c30f-14f5884f094e
* Version Independent ID: 13e0112c-213d-b462-7833-9d0fe30fc99c
* Content: [Install and use the Junk Email Reporting add-in for Microsoft Outlook - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/junk-email-reporting-add-in-for-microsoft-outlook.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@anthonynz Thank you for your feedback. We are working internally on this matter and will update the document if need be.

Thanks
Sri

**Comment by yogkumgit** [comment]
@siosulli Please help us in resolving this issue. Thanks

**Comment by siosulli** [comment]
Hi @yogkumgit 

Just to confirm - is this a duplicate of https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5262? 

I will take a look and see if we can resolve this so we can close both issues. 

Thanks
Sinead

**Comment by msbemba** [comment]
@siosulli That is correct. It is a duplicate of 5262.

Thanks
Sri

**Comment by siosulli** [comment]
Thank you reporting this issue! 

This link is no longer a valid link. The Junk Email Reporting add-in is now an Outlook native experience. 
 
The article with this link has now been removed.  It will redirect to https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide which is the recommended method for reporting messages.

@yogkumgit this issue can be closed and #5262 can be resolved as duplicate.

**Comment by yogkumgit** [comment]
@anthonynz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by anthonynz** [comment]
@yogkumgit 
Thanks for the update Yogesh,  Can you also please provide a link to the roadmap article about deprecating the old method?

This doesn't seem to have been communicated at all.
