### ISSUE TITLE
Auto-Applied Retention Policies Not Working?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/microsoft-365-docs#536]
I have tried creating multiple auto-applied retention policies in my dev tenant (with E5 licenses), all of which result in the following error messages (and seem to remain indefinitely):

![image](https://user-images.githubusercontent.com/38665906/66431484-ea024f00-e9d0-11e9-9dd2-c6d23e339b1e.png)

In addition, I have tried to apply a retention label at the document library level of both a modern Teams site and Communications site.  It appears to work, but then the retention label never gets assigned to any pre-existing documents I have in the library or any new documents I upload.  

Anyone else having trouble with this functionality, or am I doing something wrong...?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels#applying-a-retention-label-automatically-based-on-conditions)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@TracyGH  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TracyGH - I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
