### ISSUE TITLE
Typo in consent URL

### ISSUE THREAD

**Issue by mediaguycouk** [MicrosoftDocs/microsoft-365-docs#5361]
The consent URL has a backslash, which should not be present
`adminconsent?client\_id=2d94989f-457a-47c1-a637-e75acdb11568`
`adminconsent?client_id=2d94989f-457a-47c1-a637-e75acdb11568`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac2edeec-b96d-f265-d676-f16177d13d2d
* Version Independent ID: a975c834-52f2-4e9c-8486-57a77e2f076a
* Content: [Use Microsoft Teams classes with Blackboard](https://docs.microsoft.com/en-us/microsoft-365/lti/teams-classes-lms?view=o365-worldwide)
* Content Source: [microsoft-365/lti/teams-classes-lms.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lti/teams-classes-lms.md)
* Service: **o365-administration**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by msbemba** [comment]
@mediaguycouk Thank you for your feedback. We have removed the backslash from the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5367

Thanks
Sri

**Comment by mediaguycouk** [comment]
Thank you
