### ISSUE TITLE
Customer information within screenshot

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/microsoft-365-docs#5362]
Hi,

within the screenshot directly beneath the URL [https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide#threats-in-urls](url) we can see a customer name. Should be removed, I think. Visible in the URL samples and the MessageID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and Real-time detections - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@myfope Thank you for your feedback. We have removed customer information from the screenshot. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5405

Thanks
Sri

**Comment by yogkumgit** [comment]
@MSFTTracyP Please merge the PR #5405

**Comment by yogkumgit** [comment]
@KCCross PR merge request pending. Thanks

**Comment by chrisda** [comment]
Fixed.

<https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/12149>

Closing
