### ISSUE TITLE
Attach Surface Reduction rules number

### ISSUE THREAD

**Issue by MatteoC5** [MicrosoftDocs/microsoft-365-docs#5363]
Hello,

the section 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#attack-surface-reduction-rules 
says the wrong number of total rules present.

The table below contains 16 rules, while the text indicates 15 rules

Thank you

**Comment by denisebmsft** [comment]
Hello @MatteoC5. Thank you for the feedback. I have updated the article, and the changes will render live later today. Thank you again!
