### ISSUE TITLE
E1 includes holds?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#537]
in the "before you begin" section of this article, it states that you need an exchange online plan 2 or archiving license to get an office 365 retention policy, however this article now seems to state that this is included in E1: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#security--compliance-center-availability-for-business-and-enterprise-plans

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7108464d-597a-c79d-cac8-94e35d9dd3d0
* Version Independent ID: ba0d3744-707d-c506-47f4-83519022d4cb
* Content: [Create and manage inactive mailboxes in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes)
* Content Source: [microsoft-365/compliance/create-and-manage-inactive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Mike-Crowley No, there's been no change. You still need and EXO Plan 2 license to apply a retention policy to a mailbox (as per the inactive mailbox topic). If you're referring to the "Manual retention policy" row in the service description, then the "Yes" value in the E3 column is incorrect. Also, the idea of "Manual retention policy" is odd. This might really be referring to the publishing of retention labels which then allows users to manually apply them to content. In any case, thanks of the heads up. We'll fix this.

**Comment by Mike-Crowley** [comment]
Yes, that was the column I was referring to. thanks for clarifying that the other document is wrong.

**Comment by Mike-Crowley** [comment]
I opened a bug on the other page and they are saying that they are right. Can you two please sort this out?

https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/211#event-2742038160
