### ISSUE TITLE
The logotype resolution is not consistent between documentation and the office admin portal.

### ISSUE THREAD

**Issue by lars-whta** [MicrosoftDocs/microsoft-365-docs#5371]
According to the admin portal:

"Must be at least 200x30 pixels or larger. May be scaled to fit in that size. Highly suggested for tenant branding."

According to this page:

"Default logo: Add a URL location that points to your logo. Make sure that the URL uses HTTPS. Add a HTTPS image url that allows anonymous access and doesn't require authentication. For default theme, you also have an option to upload a logo image that is less than 10kb. Your default logo can be in the JPG, PNG, GIF, or SVG format. For SVG images, they will be resized to fit 24 pixels vertically. JPG, PNG, GIF images will be scaled to fit 200 x 48 pixels. Logo aspect ratio will always be preserved."

Supplying a 200x30 pixel image will alter the aspect ratio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6c85cc-1680-588e-f520-bcafb1383d53
* Version Independent ID: ea446e6b-e094-dacd-54cc-e597b2f1354d
* Content: [Customize the theme for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/customize-your-organization-theme?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/customize-your-organization-theme.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/customize-your-organization-theme.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@lars-whta Thank you for your feedback. I'm working internally with the team and will update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by msbemba** [comment]
@lars-whta Thank you for your feedback. We worked with author or the engineering team and the changes have been made to the admin center. This could take a week or two to reflect in the M365 admin center.

Thanks again for providing your valuable feedback.

@yogkumgit You can close the issue as the updates have been pushed in the backend to the Admin center by the author.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lars-whta Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
