### ISSUE TITLE
Extra File Storage for academic service plans

### ISSUE THREAD

**Issue by redmondChris** [MicrosoftDocs/microsoft-365-docs#5373]
Academic service plans are not listed on the eligible list. If M365 A* SKUs are not eligible for the extra file storage described here, please add a note and if possible, provide a link to a page about extra file storage for academic plans.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide#is-my-plan-eligible-for-office-365-extra-file-storage)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@redmondChris Thank you for your feedback. I have added  Office 365 A3 and A5(Faultly) to the document as i can see the option to Purchase extra file storage on them. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5454

Once the author verifies and approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @redmondChris Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
