### ISSUE TITLE
Default DLP Policy?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/microsoft-365-docs#538]
I'm not seeing a 'Default O365 DLP Policy' in my dev tenant Security & Compliance center.  
All that appears is a policy that I created.  Per this document (see below) - should it be there?  

![image](https://user-images.githubusercontent.com/38665906/66439682-4cfde100-e9e5-11e9-9753-b33a180043d8.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c11defbb-77c3-c56c-41f2-65e3a4dfafc5
* Version Independent ID: bde5b77f-712d-f811-2315-d775d66fc8a6
* Content: [Get started with the default DLP policy](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-the-default-dlp-policy)
* Content Source: [microsoft-365/compliance/get-started-with-the-default-dlp-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-with-the-default-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@TracyGH  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@TracyGH - You mentioned in your comment that "All that appears is a policy that I created.". This could be the reason why you are not seeing that 'Default O365 DLP Policy' in your dev tenant. Please refer to the below screen shot found on the [When the widget does and does not appear](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-the-default-dlp-policy#when-the-widget-does-and-does-not-appear) section of the doc: 

![image](https://user-images.githubusercontent.com/47188252/66487412-da712c00-eade-11e9-8357-826f06cfac8d.png)

We hope this answers your question. Thank you!

**Comment by TracyGH** [comment]
@mypil - Thank you for the quick response!  Unfortunately, I didn't see the Default policy listed in my dev tenant even before creating my own.  I also asked a colleague to check their brand-new O365 dev tenant (no DLP policies created), and it does not show a Default policy either.  
Can you confirm on your end?  
![image](https://user-images.githubusercontent.com/38665906/66501141-b0385380-ea77-11e9-9bbb-425b0172123d.png)

**Comment by TracyGH** [comment]
@mypil - Yes, I read that part too but never saw that webpart manifest in the Dashboard of my Security and Compliance center.  I even tried hitting the '+More', but it did not appear as an option.  In any case, the 'Refine DLP policy' link should take me to the Default policy which does not exist.  

Also, as mentioned in [my other issue](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/536), the contact support options you have listed in your link are disabled in my development tenant.

**Comment by mypil** [comment]
@TracyGH -  Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via **[User Voice](https://office365.uservoice.com/)**. I know the product teams are always looking for user feedback on how to make Office 365 better. You might find others have made a similar request that you can add to, or you can open a new one.

For technical queries or troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a service ticket. However,  if you cannot open a service ticket in your tenant, you also have the option to contact technical support via [Phone support](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone) or [In-Store support](https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=instore). We strongly recommend for you to get in touch with technical support so they can help troubleshoot to fix your issue. 

I hope this gets you pointed in the right direction. If you do find that it is a documentation error though, feel free to comment back and we'll gladly look into fixing it. Thank you.

**Comment by TracyGH** [comment]
Never mind - I figured out how to open a support request in my Dev tenant, (not sure what I was doing wrong before).  Thanks! :-)
