### ISSUE TITLE
Link for Scheduler licencing goes to a 404

### ISSUE THREAD

**Issue by Atreidae** [MicrosoftDocs/microsoft-365-docs#5380]
Hi Team,  The link for more information on the Scheduler licencing in the table at the top of the page goes to a 404
The link points here: https://www.microsoft.com/microsoft-365/meeting-scheduler-pricing
When it should probably point here: https://www.microsoft.com/en-us/microsoft-365/meeting-scheduler-pricing

This table is what I'm referring to
<html>
<body>

What do I need? | Description
-- | --
Cortana mailbox | Tenant admins will need to set a mailbox to serve as the “Cortana” mailbox (that is, cortana@yourdomain.com).
Exchange Online mailbox | Users must have an Exchange Online mail and calendar
Scheduler license | For licensing and pricing information, [see Scheduler for Microsoft 365.](https://www.microsoft.com/microsoft-365/meeting-scheduler-pricing)

</body>
</html>

---

Additionally, the article isn't clear on the licencing requirements,

* What licences are required on the Cortana mailbox? 
* * Just e3? Just shared? Just e3 Plus Scheduler? E5?

* I think we should also point out that the scheduler licence will need to be assigned to each user using the service.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d33f8e34-9baa-3efd-b1cc-03f3e3ab44f0
* Version Independent ID: 201878c7-a0d7-a744-c60c-d65f714d2a9d
* Content: [Setting up Scheduler for Microsoft 365.](https://docs.microsoft.com/en-us/microsoft-365/scheduler/scheduler-setup?view=o365-21vianet)
* Content Source: [microsoft-365/scheduler/scheduler-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/scheduler/scheduler-setup.md)
* Service: **scheduler**
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by msbemba** [comment]
@Atreidae Thank you for your feedback. We have fixed the link internally and it routes to the correct page now.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Atreidae Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
