### ISSUE TITLE
 Eventhub blocking graph change notifications confirmation of Graph API IP Address Range

### ISSUE THREAD

**Issue by leco36** [MicrosoftDocs/microsoft-365-docs#5382]
Turning the Allow access from Selected Networks on is causing the eventhub to reject Microsoft Graph Change Notifications. We have specified the addresses in 23 on https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide.

Does anyone know if the address range is the most up to date or if there is any other ip addresses needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide&viewFallbackFrom=o365-worldwide.)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@LauraWi Gentle reminder

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. Is this still happening, or has it been resolved?

**Comment by kelleyvice-msft** [comment]
Closing this issue, as my understanding is that the problem has been corrected in later endpoints web service updates.
