### ISSUE TITLE
Review global admin requirement

### ISSUE THREAD

**Issue by MrAzureAD** [MicrosoftDocs/microsoft-365-docs#5385]
Typically, office policy configuration does not require Global Admin, but also works with Office Apps Admin.
Details: https://docs.microsoft.com/en-us/deployoffice/overview-office-cloud-policy-service

This document however does not offer any alternative permissions and requires Global Admin.
I am quite sure Office Apps Admin will also work here, so kindly review the permission statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d2ba49-5e22-3373-5034-bb2fde743762
* Version Independent ID: 3a02dcf2-1310-561d-4106-d495eaec63b7
* Content: [Manage Microsoft feedback for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-feedback-ms-org?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-feedback-ms-org.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-feedback-ms-org.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **Kwekua**

**Comment by msbemba** [comment]
@MrAzureAD Thank you for your feedback. You are correct! The document has been updated and does not state the global admin requirement anymore.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MrAzureAD Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
