### ISSUE TITLE
How can we view the lists

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#5388]
How can we see the lists that have been created for the IOCs? where is the data stored, and how can it be reviewed? Please add some documentation for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04266df-a692-ddef-5f05-ea40d82a0eed
* Version Independent ID: d0ac62e7-498f-399d-c701-d7cbeb85cced
* Content: [Create indicators](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-indicators?view=o365-worldwide#create-indicators-for-ips-and-urlsdomains)
* Content Source: [microsoft-365/security/defender-endpoint/manage-indicators.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-indicators.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-manage?view=o365-worldwide

**Comment by DeanGross** [comment]
Thanks, but what about the list that stores acceptable IP addresses? When we are investigating an incident that has a suspicous IP address, we can add it to an Allowed list rule. How can we view addresses that were added by other soc analysts?
