### ISSUE TITLE
Where is the Microsoft-Teams-Sync-for-Canvas Azure app?

### ISSUE THREAD

**Issue by neumarke** [MicrosoftDocs/microsoft-365-docs#5395]
Would appreciate more detail in how to find and approve the "Microsoft-Teams-Sync-for-Canvas Azure app" which is a prerequisite for the steps on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b696e622-361b-0be8-0b1f-b2ad9708c877
* Version Independent ID: 18403e7b-adb6-2828-54c6-ddd410eacadd
* Content: [Use Microsoft Teams classes with Canvas](https://docs.microsoft.com/en-us/microsoft-365/lti/teams-classes-with-canvas?view=o365-worldwide)
* Content Source: [microsoft-365/lti/teams-classes-with-canvas.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lti/teams-classes-with-canvas.md)
* Service: **o365-administration**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by msbemba** [comment]
@neumarke You will have to sign in to Canvas and then integrate it with Azure using the steps mentioned here -https://docs.microsoft.com/en-us/microsoft-365/lti/teams-classes-with-canvas?view=o365-worldwide#microsoft-office-365-admin

It is not an enterprise application that is available to add in the Azure, If at all you are searching for this application directly on Azure.

Hope this helps!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @neumarke Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
