### ISSUE TITLE
Explain Differences between Retention Policies

### ISSUE THREAD

**Issue by MarkF26** [MicrosoftDocs/microsoft-365-docs#5398]
Consider the following document: 
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide

Can you please explain the difference between the following retention policies? 
choice A is when you select the **“Retention for a specific period**” https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide#retaining-content-for-a-specific-period-of-time

, and choice B is when “**Delete items when they reach a certain age**” https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide#deleting-content-thats-older-than-a-specific-age

Retention settings- Choice A
Retain items for 7 years based on when they were last modified
Delete items at end of retention period

OR 

Retention settings – Choice B
Delete items that are older than 7 years based on when they were last modified
Delete items at end of retention period

Perhaps an example would help.

**Comment by rconiv** [comment]
If I read it right, in one of the many documents I have been grinding through to find information about retention, say you modified a document 6 years ago.  A year from now, it will be deleted, since that will be the 7 year mark since it was modified.  If you had modified it 8 years ago, it would be deleted immediately since it was modified more then 7 years ago.

Myself, I wish there was an option of 7 years from when the retention policy was applied.

**Comment by MarkF26** [comment]
I am sorry, but I am asking the difference between the two options. I am not sure which options you are explaining.

**Comment by msbemba** [comment]
@MarkF26 Thank you for your feedback.
Choice A is to retain, No matter who deletes the data, it will be retained in the organization (retention hold) (more of Information governance-  if there is a requirement to retain data for a certain period of time)

Choice B is to delete after a specific age if the users delete them manually, the data is not retained ( More of a cleanup process).

Thanks
Sri

**Comment by MarkF26** [comment]
Thanks, that helps.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MarkF26 If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
