### ISSUE TITLE
Where is the device control report?

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/microsoft-365-docs#5399]
Where is the device protection report in https://security.microsoft.com/securityreports ? Mine isn't listed. Under Reports and Endpoints all I can see is Thread protection, Device health and compliance, Vulnerable devices an Web protection reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8deee5-bb2d-24da-0a31-0d41ccb4492c
* Version Independent ID: 77b994cf-7b5c-f813-0a1f-a38f046a2a02
* Content: [Protect your organization’s data with device control](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-report?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-control-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-control-report.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Hello @nhogarth86. Thank you so much for filing this issue. Please use the "Device health and compliance report" (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-reports?view=o365-worldwide). I have updated our content accordingly. Appreciate you letting us know about this so we could correct it.
