### ISSUE TITLE
Organization Management role

### ISSUE THREAD

**Issue by dchall1** [MicrosoftDocs/microsoft-365-docs#540]
The note says "To perform message trace, administrator must be member of Organization Management, Compliance Management or Help Desk role groups." What is the Organization Management role? Nothing like that appears in the list of available roles...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58f8e2c-428a-4d8e-e8b7-a0342a0038db
* Version Independent ID: 6e7fab1b-1e24-9e36-176d-c3fb14f233a7
* Content: [Message trace in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc#feedback)
* Content Source: [microsoft-365/security/office-365-security/message-trace-scc.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/message-trace-scc.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@dchall1 - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
hello @dchall1 ,
the message trace is a feature based on the Exchange Online functionality.
Listed roles are Exchange Online roles (more details here [Permissions in Exchange Online](https://docs.microsoft.com/exchange/permissions-exo/permissions-exo))
If you are Office 365 Global Admin, you have Organization Management role by default
Thank you

**Comment by mypil** [comment]
@dchall1 - From our understanding, the issue you raised has been answered by MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
