### ISSUE TITLE
Old screenshot of Microsoft Defender Baseline in Intune

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/microsoft-365-docs#5400]
The screenshot under the "Use Microsoft Defender for Endpoint baseline settings" section is old. The new baseline does not contain "Device control"

**Comment by msbemba** [comment]
@nhogarth86 Thank you for your feedback. I do not see a device control option in the screenshot  in the Microsoft defender for endpoint baseline document -https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-machines-security-baseline?view=o365-worldwide

Could you please provide the document that you are referring to?

Thanks
Sri

**Comment by nhogarth86** [comment]
Sorry you can close this. I was referring to the wrong doc. I meant https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/control-usb-devices-using-intune?view=o365-worldwide#use-microsoft-defender-for-endpoint-baseline-settings
