### ISSUE TITLE
Difference between Install-Module and Import-Module?

### ISSUE THREAD

**Issue by GeorgHue** [MicrosoftDocs/microsoft-365-docs#5402]
Hi,

what is the difference between
`Install-Module -Name O365CentralizedAddInDeployment`
and
`Import-Module -Name O365CentralizedAddInDeployment`
?
Which command is recommended in the article's context?

Greetings, Georg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a092120-6209-1c44-8bc1-f989f62f37b7
* Version Independent ID: f9eb09fb-e430-d797-25d3-b8bb67a85512
* Content: [Use the Centralized Deployment PowerShell cmdlets to manage add-ins - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@GeorgHue Thank you for your feedback. You will have to install the module only once (for the first time) as mentioned in https://www.powershellgallery.com/packages/O365CentralizedAddInDeployment. However, you will import the module every time you try to use the Centralized Deployment PowerShell cmdlets.

Hope this helps!
Thanks
Sr

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GeorgHue Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
