### ISSUE TITLE
Encryption - what kind of encryption?

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/microsoft-365-docs#5408]
Can you please provide more details on the encryption chapter? What kind of encryption (OME, AIP/sensitivity labels, S/MIME) are you referring to?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289f2440-9c44-7d93-20e3-baa9e9892cd9
* Version Independent ID: abc4e209-a071-d28a-cb01-aa72bbaee7c0
* Content: [About shared mailboxes - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/about-shared-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/about-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/about-shared-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@sebhe Thank you for your feedback. The encryption topic refers to all types of encryptions supported in Microsoft 365. While, you can still encrypt if a shared mailbox has a license assigned, however, members might not be able to read the email (depending on which public key the email was encrypted with).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sebhe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
