### ISSUE TITLE
Possible modification for Section 2 above.

### ISSUE THREAD

**Issue by michaelvgibson** [MicrosoftDocs/microsoft-365-docs#5409]
I think a How-To for section 2 above is warranted.  Not sure if it is possible to export a PST from the web version of the Outlook portal.  There could be a link to "Add an email account to Outlook"   https://support.microsoft.com/en-us/office/add-an-email-account-to-outlook-6e27792a-9267-4aa4-8bb6-c84ef146101b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2ba944-52a9-1dc9-eebe-e16111a8ccc4
* Version Independent ID: 22f2b1ec-a287-b315-ae6c-caeabc86beba
* Content: [Step 2 - Save the contents of a former employee's mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-2?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-2.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@michaelvgibson Thank you for your feedback. It should have been  outlook desktop application instead of web app. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5441

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @michaelvgibson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
