### ISSUE TITLE
Value of SharePointAssetIdQuery

### ISSUE THREAD

**Issue by markgort86** [MicrosoftDocs/microsoft-365-docs#541]
Is it possible to use this value "SharePointAssetIdQuery" at the following way? SharePoint Column Name + Value? For example: create an event automatically in the Security and Compliance center and use projectnr:12345 as a value for the field assed ID.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 5e242e00-9737-43c0-eded-821faaa889cd
* Version Independent ID: 1a354075-9994-1dc6-ac43-006dbac0add8
* Content: [Automate event-driven retention](https://docs.microsoft.com/nl-nl/microsoft-365/compliance/automate-event-driven-retention)
* Content Source: [microsoft-365/compliance/automate-event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/automate-event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@markgort86 - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@markgort86 You should be fine with using something like "projectnr:12345", keeping in mind that the the type of **-SharePointAssetIdQuery** is **String**.

https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/new-complianceretentionevent?view=exchange-ps

**Comment by mypil** [comment]
@markgort86 - From our understanding, the issue you raised has been answered by VLG17. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by markgort86** [comment]
@VLG17 I tried to create an retention event and used a custom column. After that i wait for several days if tagged documents are visible within the event status of the created event. They are only visible when creating an event and make use of the standard column ComplianceAssetID.

**Comment by VLG17** [comment]
@markgort86 Could you please share the exact cmdlet which works and the one that does not work in your case? I want to test the exact same thing.

**Comment by markgort86** [comment]
Here two lines of code i use within a Microsoft Flow to create this event. The first example makes use of the column named "Projectnr" (type: Single line of text) with the value "12345" and doesn't work. The second one works correctly and make use of the default field ComplianceAssetID, which is empty in the first example after assigning a retention label on the document. <d:SharePointAssetIdQuery>@{triggerBody()?['Projectnr:12345']}</d:SharePointAssetIdQuery>
<d:SharePointAssetIdQuery>@{triggerBody()?['12345']}</d:SharePointAssetIdQuery>

**Comment by LauraWi** [comment]
Hi, according to the PM accountable for this space, the answer is in this article: https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention#step-7-enter-keywords-or-an-asset-id
Also, yes it is possible to use a SharePoint column instead of the built-in asset ID

**Comment by mypil** [comment]
@markgort86 - From our understanding, the issue you raised has been answered by VLG17 and LauraWi. If you feel it hasn't been resolved and you still require technical assistance then we suggest for your to open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP.

However, if in case you find that it is a documentation error, feel free to comment back here and we'll be glad to help fix it. Thank you!
