### ISSUE TITLE
PST Max File Size Clarification

### ISSUE THREAD

**Issue by UnexpectedLemon** [MicrosoftDocs/microsoft-365-docs#5411]
The documentation notes: As previously stated, each PST file that you upload to the Azure Storage location should be no larger than 20 GB. PST files larger than 20 GB may impact the performance of the PST import process that you start in Step 6.

What does this actually mean, is this a hard limit, or do we just need to wait and should consider submitting large PSTs in their own job?

1) We submitted a ticket and the feedback we got was possible silent data loss as a consequence of attempting to ingest PSTs larger than 20GB. Is this true? If so it needs to be mentioned on this page. Or what is a recommended path if we need to ingest PSTs larger than 20GB? Ideally we can just submit a job and "may impact the performance" means we just need to wait.

2) Is the 20GB based on the actual file size of the PST, or only the actual space used within the PST (and we could compact the PST if not)?

3) Is there any item count limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@UnexpectedLemon The article states the 20GB limit. Would suggest you continue working with support on this issue and to answer these questions. Seems that you could also test some of your suggested workarounds. You could also try using the New-MailboxImportRequest cmdlet in Exchange Online PowerShell for the large PST, but that cmdlet **is not** supported in Exchange Online. Not sure if doing that offers any advantages.

I believe the only count limits would be the maximum folder limits for Exchange Online mailboxes (or any other EXO limit for mailbox items). See: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-folder-limits

**Comment by UnexpectedLemon** [comment]
Thanks @markjjo -- I don't read this as a hard 20GB service limit if it only states "PST files larger than 20 GB may impact the performance of the PST import process." Same for this quote earlier in on this page "Large PST files may impact the performance of the PST import process. So we recommend that each PST file you upload to the Azure Storage location in Step 2 should be no larger than 20 GB." -- I do not read this as a hard limit, it is "recommended" but does not explain what a consequence of impacted performance is. Hope this feedback helps improve the documentation.
