### ISSUE TITLE
import file required fields

### ISSUE THREAD

**Issue by nanoonan538** [MicrosoftDocs/microsoft-365-docs#5412]
[Enter feedback here]
To assist customers with building their import files, it would be helpful to include which fields/attributes are required vs. optional in our documentation for easy reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Use file plan to manage retention labels throughout the content lifecycle - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/file-plan-manager?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Yes, looking into this

**Comment by cabailey** [comment]
This isn't as simple as it first sounds - technically, only the Name property is required for import.  Then there are some conditional dependencies (if you specify one optional property, another becomes required), and in one case there's a cascading dependency.  I've addressed these with both a new Required column and additional text in the description.  Let me know if this is helpful!

**Comment by yogkumgit** [comment]
@nanoonan538 Hope this comment is helpful for you. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by nanoonan538** [comment]
Thank you! This was a request on behalf of a customer and will help reduce time/avoid error. We appreciate your quick response!
