### ISSUE TITLE
Request for review of the following statement "Audit logging is turned on by default for Microsoft 365 and Office 365 enterprise organizations. This includes organizations with E3/G3 or E5/G5 subscriptions."

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/microsoft-365-docs#5416]
Please confirm the accuracy of the following statement in the documentation "Audit logging is turned on by default for Microsoft 365 and Office 365 enterprise organizations. This includes organizations with E3/G3 or E5/G5 subscriptions."

I have not found this to be accurate in enterprise tenants (E3, **G3**, E5, **G5** (or dev tenants). Requires admin to turn the logging feature on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn auditing on or off - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jebalert Can you please clarify what exact subscriptions require that auditing be enabled? Are you saying that auditing has to be enabled in G3 and G5. Also, what is a dev tenant? Not sure this would be in-scope. Mote details would be helpful.

**Comment by jebalert** [comment]
Hey Mark,

Not saying there's a need, I'm saying the documentation says it's on by default but that's not been the case for me. I've always had to turn it on. Was looking to make sure the statement in the documentation is accurate.

Thanks

**Comment by markjjo** [comment]
@jebalert The statement is accurate. Auditing was not always enabled by default, but it is now. Not sure why or in what situations you are having to turn if on. Not sure if this extends to dev tenants (we typically don't call dev tenant behavior if it is different from other subscriptions). You might consider opening a ticket with MS Support for G3/G5 tenants. I will also follow up with engineering and respond to this thread if documentation needs to be updated.
