### ISSUE TITLE
MMD R&R - 

### ISSUE THREAD

**Issue by soupman98** [MicrosoftDocs/microsoft-365-docs#5418]
With the deprecation of 1st party support the User Support section (Microsoft) is no longer accurate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84224d97-478e-9bf6-85af-a74d0bbfe382
* Version Independent ID: ee3d7788-67a1-8cd0-9326-84248a858703
* Content: [Microsoft Managed Desktop roles and responsibilities - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/intro/roles-and-responsibilities?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/intro/roles-and-responsibilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/intro/roles-and-responsibilities.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@mertenar has a whole set of updates and articles coming to address this.
