### ISSUE TITLE
MMD R&R - Device/peripherals

### ISSUE THREAD

**Issue by soupman98** [MicrosoftDocs/microsoft-365-docs#5419]
with the deprecation of 1PS, and in general.... This document should more clearly call out that device support and hardware support  at a hardware level is the responsibility of the customer. Repair or warranty work for Surface devices and peripherals, monitors, keyboards, cameras, printers, docking stations beyond driver deployment via Windows Update (MMD) is the responsibility of the customer.

**Comment by yogkumgit** [comment]
@soupman98 Please indicate which document you are referring to. Thanks

**Comment by msbemba** [comment]
@soupman98  Thank you for your feedback. From the information provided, I assume you are referring to https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/intro/roles-and-responsibilities?view=o365-worldwide
There is a whole set of articles and updates coming to this document.

@yogkumgit There are no changes required at the moment.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @soupman98 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
