### ISSUE TITLE
No documentation for "Email sending limit exceeded"

### ISSUE THREAD

**Issue by vitahall** [MicrosoftDocs/microsoft-365-docs#542]
We have a "Email sending limit exceeded" default alert, for which the condition is "Activity is EmailSendingLimitExceeded", which doesn't seem to be addressed here. It's not clear to me exactly what this is actually looking at or what it means. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance center](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies#feedback)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@vitahall  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@vitahall Thank you for your feedback. I have added the missing information to the document  via PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/549

Thanks
Sri

**Comment by mypil** [comment]
@vitahall - Please refer to the author's response here- https://github.com/MicrosoftDocs/microsoft-365-docs/pull/549#issuecomment-540719487

We hope this helps to address your issue. Thank you for your contribution to make the docs better! Much appreciated!
