### ISSUE TITLE
'Sending email from the proxy address easily' : Easy, but not working yet

### ISSUE THREAD

**Issue by koulchi** [MicrosoftDocs/microsoft-365-docs#5425]
Hello,
It would be nice to update the following section, which states:

> **Sending email from the proxy address easily**
> A new feature is rolling out in April 2021 that allows users to send from their aliases easily when using Outlook on the web. When the feature rolls out to a tenancy where the tenant admin uses the Set-OrganizationConfig -SendFromAliasEnabled $true cmdlet, users within the tenancy will get access to a list of checkboxes where each entry corresponds to an alias in their Outlook settings. Selecting an alias will make it appear in the From dropdown in the Compose form.

But this is not true. Even with `-SendFromAliasEnabled $true`, the recipient receives email from the primary SMTP. 

Today the only way to achieve is with shared mailbox and forwarding rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@koulchi Thank you for your feedback. According to the roadmap the feature is supposed to be released in July 2021. I have updated the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5549

More information about the roadmap can be found here -https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=Sending%2Cemail%2Cfrom%2Calias

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @koulchi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
