### ISSUE TITLE
Missing Instructions - Vulnerabilities Notification rules

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#5427]
I cannot find any instructions about configuring the Notification Rules for Vulnerabilities on https://security.microsoft.com/preferences2/email_notifications/vulnerabilities. 

Please add this to the documentation
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f066b4c-ef35-cb0a-50af-8d8cfd381790
* Version Independent ID: 379396f5-064a-2048-dce7-7b2e4ff69dda
* Content: [Configure alert notifications in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-email-notifications?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-email-notifications.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-email-notifications.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. There is another document that talks about Configuring Vulnerability email notifications -https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-vulnerability-email-notifications?view=o365-worldwide

I have added this to the related topics via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5562

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
