### ISSUE TITLE
RSS link not complete?

### ISSUE THREAD

**Issue by ekston** [MicrosoftDocs/microsoft-365-docs#5428]
[Enter feedback here]

The RSS feed starts with /api/ and it is unclear to which URL this must be added to.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3c8fbe3-a993-4685-e747-fbee780bc661
* Version Independent ID: 1dfaaf75-255d-af48-b240-a4314e91bf3a
* Content: [What's new in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-atp?view=o365-worldwide&locale=en-us&facet=&viewFallbackFrom=o365-worldwide%2Fapi%2Fsearch%2Frss%3Fsearch%3D%22features%20are%20generally%20available%20(GA)%20in%20the%20latest%20release%20of%20Microsoft%20Defender%20for%20Endpoint%22)
* Content Source: [microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-atp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@ekston Thank you for your feedback. We have updated the document with the correct rss feed URL -https://docs.microsoft.com/api/search/rss?search=%22features+are+generally+available+%28GA%29+in+the+latest+release+of+Microsoft+Defender+for+Endpoint%22&locale=en-us&facet=

This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5504

Thanks
Sri

**Comment by ekston** [comment]
Awesome news. Thank you for the update.
