### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/microsoft-365-docs#543]
[Enter feedback here]
On the line: 
"_Set specific permissions for records manager functions in your organization to **have the right access**._"
Have a link, but the URL leads to 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc52e4d6-6373-204d-9eb2-d8c396375fb1
* Version Independent ID: 106caf2c-6de5-3cc9-6cdd-4dc81dcbcc8b
* Content: [Records management in Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/records-management)
* Content Source: [microsoft-365/compliance/records-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records-management.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@Petri-X  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Petri-X - From our understanding, the issue has been resolved based on the merged commit [[b0ea535](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/b0ea53538cc6969716323bde35b20e72d5c81381)]. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
