### ISSUE TITLE
KeyVaults and Multi-geo

### ISSUE THREAD

**Issue by varunaggar** [MicrosoftDocs/microsoft-365-docs#5431]
What are the best practices for AKV when the tenant is multi-geo ?

Should there be only two AKV close to the default geo or should there be two AKV for each geo ?

If the AKV's are in default geo, then does it impact on the data stored in satellite geo's ?
If the AKV's in default geo are down or unreachable due to any reason does it mean that data in satellite geo is un-accessible

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in  resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@KCCross Gentle reminder

**Comment by yogkumgit** [comment]
@varunaggar Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
