### ISSUE TITLE
Download PST using OWA? 

### ISSUE THREAD

**Issue by motoki1** [MicrosoftDocs/microsoft-365-docs#5432]
"...Outlook web app, and then export the data to a .pst file"
Can't export to PST in OWA/outlook.com, but that would be a great feature to have. Please let me know if I'm wrong about that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2ba944-52a9-1dc9-eebe-e16111a8ccc4
* Version Independent ID: 22f2b1ec-a287-b315-ae6c-caeabc86beba
* Content: [Step 2 - Save the contents of a former employee's mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-2?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-2.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@motoki1 Thank you for your feedback. The document now states the outlook desktop app instead of the outlook web app(which was incorrect). Hope that helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @motoki1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
