### ISSUE TITLE
Assigning Retention Policy Issue

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/microsoft-365-docs#5433]
It would be handy if there were instructions on how to do this process in the modern environment that they have been pushing us to go to, though for some reason in Edge Chromium, if I go to the classic exchange mode, and go to mailbox, I get an error to try again later.  Works fine in other browsers.

My main issue is, that I go to the mailbox, pick a user, and go to the area where I can pick retention policies, and the policies I created, and show are available, are not in the list.  Is there some type of process that needs to get them there, or a permission needed to see them, though our group admin can't see them either, and they have all the permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1c2e44-357c-8096-5bdf-40e205778ded
* Version Independent ID: 19c7b5d9-1e0c-501b-7b70-df5aab48b36e
* Content: [Learn about retention for Exchange - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-exchange?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-exchange.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-exchange.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@rconiv  Are you using messaging records management (MRM)? (https://docs.microsoft.com/exchange/security-and-compliance/messaging-records-management/messaging-records-management) rather than retention policies for Microsoft 365 information governance?  If you are, it looks like the following page is the right one to leave this feedback: https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/apply-retention-policy

**Comment by rconiv** [comment]
MRM is the default.  So might be.

**Comment by yogkumgit** [comment]
@rconiv Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it as here, we are limited to documentation fixes and improvements only. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
