### ISSUE TITLE
Step 8 is incorrect. 

### ISSUE THREAD

**Issue by Rodwhite** [MicrosoftDocs/microsoft-365-docs#5436]
Since we're attempting to tell the Endpoints where to find the file within the GPO we need to change it from:

-  Enter the file name and location of the shared WindowsDefenderATPOnboardingScript.cmd file.

    TO:

-  Enter the NetBIOS path to the shared WindowsDefenderATPOnboardingScript.cmd file.  
    (i.e. \\Servername\Shared_folder\WindowsDefenderATPOnboardingScript.cmd)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523651c3-a318-2369-6892-d13e04991596
* Version Independent ID: 624c5e05-f87d-1bd4-bc87-bd55dcac1d86
* Content: [Onboard Windows 10 devices to Microsoft Defender for Endpoint via Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-gp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
Changed from Enter the file name and location of the shared WindowsDefenderATPOnboardingScript.cmd file.

TO: Enter the NetBIOS path to the shared WindowsDefenderATPOnboardingScript.cmd file.

**Comment by msbemba** [comment]
@JohanFreelancer9 please copy review

**Comment by msbemba** [comment]
@Rodwhite Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5543

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Rodwhite Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Rodwhite** [comment]
It looks like the change was made under the Offboarding section but NOT under the Onboarding process.
Step 8 on both processes:

Onboarding states:  (Still wrong)
Enter the file name and location of the shared WindowsDefenderATPOnboardingScript.cmd file.

Offboarding states:  (Corrected)
Enter the NetBIOS path of the shared WindowsDefenderATPOffboardingScript_valid_until_YYYY-MM-DD.cmd file.

**Comment by msbemba** [comment]
@Rodwhite Thank you for the feedback. I have updated the onboarding steps as well now via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5573

Thanks
Sri
