### ISSUE TITLE
Unclear how to change the spf

### ISSUE THREAD

**Issue by AndrewRobinsonSKEDA** [MicrosoftDocs/microsoft-365-docs#5437]
The document describes how the spf record works and how to format it with various examples, but I was simply trying to edit my spf record (hosted on MS DNS). I was going into my domains in Office365 and clicking ... Manage DNS, and it made me jump through the original dns setup sequence when I had already setup the DNS a long time ago. What I needed to know was to modify the existing spf record in MS DNS, I had to click on the domain and THEN click the DNS Records tab, whereby I could scroll down to the Exchange Online section and click the ... beside the existing spf record and update it. Simple UI failure really, Manage DNS is poor wording and would be better to be called Initialise DNS, or Setup DNS, where as ManageDNS should go to the record management page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b0319e8-f6d0-942a-f802-f035d753b670
* Version Independent ID: 7c74eb1c-30b5-6186-6775-6cd94fc8eaa4
* Content: [How Sender Policy Framework (SPF) prevents spoofing - Office 365](https://docs.microsoft.com/en-US/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@AndrewRobinsonSKEDA Thank you for your feedback. To edit the SPF record, click on the domain instead of selecting Manage DNS-->You can then right-click on the ellipse next to TXT and edit the record

![image](https://user-images.githubusercontent.com/45987684/125057776-39eed800-e0c7-11eb-9da4-1d2dd9d383ad.png)

Hope this helps!
Thanks
Sri

**Comment by AndrewRobinsonSKEDA** [comment]
Yes, thanks, I worked it out eventually but the documentation could be improved, hence my feedback

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by msbemba** [comment]
@AndrewRobinsonSKEDA Thank you for the response. This document has only technical information about How SPF prevents Spoofing, so we could not add information about how to add or edit SPF records on the admin center.

Hope this helps!

@yogkumgit  There are no changes required in this document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AndrewRobinsonSKEDA Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
