### ISSUE TITLE
Report Export

### ISSUE THREAD

**Issue by Burn907** [MicrosoftDocs/microsoft-365-docs#5438]
In large organisations using a single tenant, it is required to be able to export and filter the excellent data in the Business Continuity & Productivity reports. There appears to be no option to do this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 411cc9ec-3de2-9aaf-00b8-d923d2b02f37
* Version Independent ID: c1a0daec-33a1-eb34-db3d-0b12b78a8aaf
* Content: [Microsoft Productivity Score - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/productivity/productivity-score?view=o365-worldwide)
* Content Source: [microsoft-365/admin/productivity/productivity-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/productivity/productivity-score.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@Burn907 Thank you for your feedback.  I looked into this issue for you, and it seems like there isn't currently a way to do this. To make sure that your feedback gets routed to the appropriate team, please post it on the Microsoft 365 Q&A portal and the product team (if this looks like a good idea) will implement a way to achieve this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Burn907 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
