### ISSUE TITLE
Only passwords for user accounts that are not synchronized through directory synchronization can be configured to not expire. 

### ISSUE THREAD

**Issue by grryf** [MicrosoftDocs/microsoft-365-docs#5439]
Below sentence doesn't seem to be true because: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-password-hash-synchronization#enforcecloudpasswordpolicyforpasswordsyncedusers

"Only passwords for user accounts that are not synchronized through directory synchronization can be configured to not expire. For more information about directory synchronization, see Connect AD with Azure AD."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52c6916-7e79-9a9c-b7a6-47041ddb81e3
* Version Independent ID: 43c9b873-d354-d814-3065-1e8832361b86
* Content: [Set an individual user's password to never expire - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@grryf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5560

Once the author approves, you will see the changes reflect in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @grryf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
