### ISSUE TITLE
Cloud Teams

### ISSUE THREAD

**Issue by haydanbarry** [MicrosoftDocs/microsoft-365-docs#5456]
This page needs information about which of the 3 location options includes Teams chat data? (Teams person to person chat data). Its unclear if content search can be used to retrieve this information. Can it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e514aa-9f04-5cc9-93f6-9f5f2f614c2a
* Version Independent ID: dea1ab15-bc09-05c1-b48b-1a06c0b53b50
* Content: [Create and run a Content search in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@haydanbarry Yes you can. Information about searching Teams in is this topic: https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search-reference?view=o365-worldwide#searching-microsoft-teams-and-microsoft-365-groups

1:1 and 1:N Teams chat data is stored in the mailboxes of the chat participants. Teams channel chat messages are store in the mailbox associated with the Team.

To return all Teams chat messages, you could search all mailboxes in the organization and then use this keyword search query:

kind:im AND kind:microsoftteams

To search for 1:1 chats for specific users, you can search their mailbox(es) and use the query above. 

Hope this helps. I'll look into adding info about 1:1 chats and/or link to info about search teams in this article.
