### ISSUE TITLE
Old screenshot of Microsoft Defender Baseline in Intune

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/microsoft-365-docs#5458]
The screenshot under the "Use Microsoft Defender for Endpoint baseline settings" section is old. The new baseline does not contain "Device control"

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/control-usb-devices-using-intune?view=o365-worldwide#use-microsoft-defender-for-endpoint-baseline-settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8387555-2aea-a843-2e8f-e831629fc004
* Version Independent ID: c40f9512-87e3-5334-832e-ab153e608925
* Content: [How to control USB devices and other removable media using Intune (Windows 10)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/control-usb-devices-using-intune?view=o365-worldwide#use-microsoft-defender-for-endpoint-baseline-settings)
* Content Source: [microsoft-365/security/defender-endpoint/control-usb-devices-using-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/control-usb-devices-using-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@nhogarth86 Thank you for your feedback. We have removed the Old screenshot from the document as the option is no longer available in Baseline settings. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5641

Thanks again for your valuable feedback.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nhogarth86 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
