### ISSUE TITLE
Instructions and screenshots still show the old Security and Compliance Center.

### ISSUE THREAD

**Issue by chrisbues** [MicrosoftDocs/microsoft-365-docs#5464]
Content needs to be updated to reflect the new experience customers are being prompted to switch to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1c5a0b-ea21-d3bb-f1e7-6d0c199734a3
* Version Independent ID: 1d2b5a8f-cf03-2f92-051e-a9cb24c91040
* Content: [Configure Microsoft 365 Defender pillars for the trial lab or pilot environment](https://docs.microsoft.com/en-us/microsoft-365/security/defender/config-m365d-eval?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/config-m365d-eval.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/config-m365d-eval.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@chrisbues Thank you for the feedback. We are working on updating the document with new screenshots and navigation steps.

Thanks
Sri

**Comment by msbemba** [comment]
@chrisbues Thank you for your feedback. This document has been removed and more details about setting up defender can be found here - https://docs.microsoft.com/en-us/microsoft-365/security/defender/?view=o365-worldwide

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @chrisbues Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
