### ISSUE TITLE
micrisoft

### ISSUE THREAD

**Issue by Babygitzy100** [MicrosoftDocs/microsoft-365-docs#5469]
I love how Microsoft has how to videos. they are so easy to understand.  thank you Microsoft!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
Thanks
