### ISSUE TITLE
How to set the max page size to 1000?

### ISSUE THREAD

**Issue by j1151300783** [MicrosoftDocs/microsoft-365-docs#5470]
Maximum page size of the API Request(such as List Machines) is 10,000.
How to set the max page size to 1000?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07828149-8c9b-2b6f-b5f6-9558cfcfa650
* Version Independent ID: 2101b098-7da1-86ca-6a31-fddfa7a5cb62
* Content: [List machines API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-machines.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@j1151300783 Thank you for your feedback. I looked into this issue for you, and it seems like there isn't currently a way to do this. To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365) and the product team (if this looks like a good idea) will implement a way to achieve this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @j1151300783 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
