### ISSUE TITLE
Microsoft Defender Antivirus OR Microsoft Defender for Endpoint

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/microsoft-365-docs#5471]
Microsoft Defender Antivirus and Microsoft Defender for Endpoint are 2 **separate** products as mentioned here:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/why-use-microsoft-defender-antivirus?view=o365-worldwide

This article says, Applies to: Microsoft Defender for Endpoint
BUT
Isn't it actually an article about: Microsoft Defender Antivirus

The "Applies to" section should be corrected

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4449fe2-eb1b-0c55-cdb1-c8ff00681204
* Version Independent ID: e0c1d23c-9dbd-85df-9c97-fa551c09f91e
* Content: [Manage Windows Defender in your business](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configuration-management-reference-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configuration-management-reference-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configuration-management-reference-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@ssmiller60 Thank you for your feedback. We have added Microsoft defender antivirus to the applied to section via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5557

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ssmiller60 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
