### ISSUE TITLE
UK drivers license number

### ISSUE THREAD

**Issue by tigattack** [MicrosoftDocs/microsoft-365-docs#548]
The format says "Five digits in the date format DDMMY for date of birth". It's actually "Five digits in the date format MMDDY for date of birth". Females also have an extra 50 added to the MM, so a female born in September (month number "09") would have the month as 59 in their license number.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [What the sensitive information types look for](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for#uk-drivers-license-number)
* Content Source: [microsoft-365/compliance/what-the-sensitive-information-types-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@tigattack  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by chrfox** [comment]
PR 553 merged, closing issue
