### ISSUE TITLE
Outlook

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#5480]
This page is not complete. It doesn't mention the impact on the address book in Outlook desktop and OWA. Both are inconsistent in how they hide / show the policy blocked users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Learn about information barriers in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder.

**Comment by robmazz** [comment]
@danmyhre - thanks for the feedback. Currently, information barriers do not apply to email communications. Only Microsoft Teams, SharePoint Online, and OneDrive for Business support information barriers. Thanks!

**Comment by danmyhre** [comment]
@robmazz  I know it doesn't cover mail transport, but much of how it is implemented is based on Exchange Online address book policies. It **does** have an impact on the OAB.

**Comment by robmazz** [comment]
@danmyhre - thanks for the feedback. Yes, IB is based on ABPs and the focus of this topic is an overview of the IB feature at a higher level. I'll discuss your feedback about this impact with the PG during our upcoming documentation review and where it may fit in the guidance. Thanks again for your input.
