### ISSUE TITLE
Missing details on impact on Bing search for work

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#5481]
People search on bing is also impacted and not mentioned in this article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Learn about information barriers in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@robmazz Gentle reminder

**Comment by robmazz** [comment]
@danmyhre - thanks for the feedback, but I'm not sure I understand your concern. Can you clarify? Thanks!

**Comment by danmyhre** [comment]
@robmazz Hi - IBs will limit the information shown on the people search and contact card in Bing for work (https://www.bing.com/work/search?q=usernamehere&form=HDRMSB#Person-people)
