### ISSUE TITLE
Verify vanity domain with MX record - misleading recommendation

### ISSUE THREAD

**Issue by heikobischoff** [MicrosoftDocs/microsoft-365-docs#5486]
Feedback for this section:
https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide#verify-with-an-mx-record

The MX records priority must be the highest value to avoid mail routing issues as stated.

The article recommends the following values for the MX record:

Record Type: MX
Priority: Set to the highest value available**, typically 0.**
Host Name: @
Points to address: Copy the value from the admin center and paste it here.
TTL: 3600‎ (or your provider default)

-> When the validation MX record is set to 0, it has the highest priority and will introduce mail routing issues.
Instead, the value must be higher than all existing records. I would recommend to remove "typically 0", in my opinion this is very misleading.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f2e4e45-6ad7-eb79-aecb-0d7a89b06a03
* Version Independent ID: 1059223e-5759-b130-41ac-5ea98cb5367e
* Content: [Add DNS records to connect your domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@heikobischoff Thank you for your feedback. When the validation MX record is set to 0, it has the highest priority so there should not be any mail routing issues. I don't think it is misleading as the Microsoft recommended priority for MX record is 0.

Hope this helps!

Thanks
Sri

**Comment by heikobischoff** [comment]
@msbemba I do not agree. Setting the priority for MX record to 0 for the validation record will definitively break your mail routing.

Additionally, the admin center team do not recommend to set the value to 0 as well:
![image](https://user-images.githubusercontent.com/34372415/124558708-30e9d680-de3b-11eb-92b2-c0665d560aa0.png)

**Comment by msbemba** [comment]
@heikobischoff Thank you for your feedback. There was confusion on my end about the MX priority for email routing. Looks like we are talking about verifying the domain, so you are definitely right. I'll make the changes accordingly.

**Comment by yogkumgit** [comment]
@pebaum  PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pebaum Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
