### ISSUE TITLE
Product Naming

### ISSUE THREAD

**Issue by ggarruba** [MicrosoftDocs/microsoft-365-docs#5491]
"Microsoft 365 Defender architecture" section has a few inconsistencies in product naming. 
In this illustration: "Microsoft 365 Defender for Office 365" should be "Microsoft Defender for Office 365"

Two instances of "Microsoft Defender" should be "Microsoft 365 Defender" unless you are including references to Azure Defender, which I didn't see. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9afb9bd-0d73-62ef-a10b-2942f16370c2
* Version Independent ID: ce228ca6-001d-24a0-7c5f-3ef183050c83
* Content: [Evaluate and pilot Microsoft 365 Defender, an XDR, to prevent, detect, investigate, respond, endpoints, identities, apps, email, collaborative applications, data.](https://review.docs.microsoft.com/en-us/microsoft-365/security/defender/eval-overview?view=o365-21vianet&branch=zarka-defender-eval)
* Content Source: [microsoft-365/security/defender/eval-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/eval-overview.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@ggarruba Thank you for your feedback.  The Evaluation document has been merged with the overview document here- https://docs.microsoft.com/en-us/microsoft-365/security/defender/overview-security-center?view=o365-worldwide

Hope this helps!

@yogkumgit The document has been merged with the overview document and the issue can be closed.
Thanks
Sri
