### ISSUE TITLE
Group Policy requires ASR Guids

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#5492]
Hello,

I found the instructions in the "[Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction#group-policy)" section, then had to go back to my search engine to find the GUIDs needed to configure the policy. Please add a link to this list of Attack Surface Reduction rules. Thanks!

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction#attack-surface-reduction-rules

p.s. a reference from the ASR rules page back to this one for the poor souls that are configuring ASR using group policy or powershell would be welcome. Though, hopefully I never have to configure this via group policy ever again!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @jonwbstr and thank you so much for your feedback. Apologies for the inconvenience of having to hunt for the rule IDs. I have added a link to this article (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules?view=o365-worldwide), and the changes will be live later today. Thank you again for your helpful suggestion!
