### ISSUE TITLE
This isn't clear enough

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/microsoft-365-docs#5497]
Hi,

In the manually upgrading the key section, I'm not sure how to proceed. We have the default DKIM setup, i.e. we chose to do nothing (Tip You can choose to do nothing about DKIM for your custom domain too...), so does that translate to 'we already have DKIM configured' and should follow commands for that scenario as in:

Rotate-DkimSigningConfig -KeySize 2048 -Identity {Guid of the existing Signing Config} rather than:

New-DkimSigningConfig -DomainName <Domain for which config is to be created> -KeySize 2048 -Enabled $true

Also, in the steps to manually setup DKIM, I'm supposed to run 2 PS commands to create the selector records, but those records already exist, because again, we chose to do nothing, if I just run the Get-DkimSigningConfig command, so what is the point of the first command;

New-DkimSigningConfig -DomainName <domain> -Enabled $false

That's like saying "I'm going to buy a New-Car but -NewCar -Enabled $false." So I'm not buying a car then...

Sorry if I'm missing something (like any PS training, perhaps) but not breaking this is probably preferable to a support call to MS.

Alan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@alanbmhs Thank you for your feedback.

You are correct, we have changed the ps cmdlet to reflect -enabled to $true. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5539

Meanwhile for your custom domain, you dont need to do either of Rotate-DkimSigningConfig  or New-DkimSigningConfig. Microsoft 365 creates a private and public key pair, enables DKIM signing, and then configures the Microsoft 365 default policy for your custom domain.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @alanbmhs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
