### ISSUE TITLE
This is very unclear on license part

### ISSUE THREAD

**Issue by mengpinhung** [MicrosoftDocs/microsoft-365-docs#5498]
Hello team,
please kindly make below statement CLEAR.
"Configuring and using the expiration policy for Microsoft 365 groups requires you to possess but not necessarily assign Azure AD Premium licenses for the members of all groups to which the expiration policy is applied."
It is very confused -> Do i need AADP license or not?

Please make it clear enough as a official document reference.

thanks!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979f0a6e-be32-af1e-5724-d1104ebe3ef5
* Version Independent ID: cb9b993a-2224-5bb8-64b8-d1afa7a71c8e
* Content: [Microsoft 365 group expiration policy](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-groups-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@mengpinhung Thank you for your feedback. As an Admin, when you set up the Expiration policy for groups you will need AADP licenses, however, it is not needed for all members of the group.

Hope this helps!

Thanks
Sri

**Comment by mengpinhung** [comment]
Please update the article if possible

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by msbemba** [comment]
@mengpinhung Thank you for your feedback. The below statement in the document is very clear.

Configuring and using the expiration policy for Microsoft 365 groups requires you to possess but not necessarily assign Azure AD Premium licenses for the members of all groups to which the expiration policy is applied. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mengpinhung Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
