### ISSUE TITLE
Possible Onboarding Methods missing

### ISSUE THREAD

**Issue by digitalzomb** [MicrosoftDocs/microsoft-365-docs#5501]
On this section for Windows Server 2019 and later, Windows Server 2019 core edition, Windows Server version 1803 and later it does not mention Azure Defender / Security Center as a way to onboard these server version, I would assume that if these are available in Azure, they would be available to onboarded on the Azure Defender / Security Center methods.

Also, it is quite unclear which methods work based on where the VM lives, as there's different methods that'll work if the VM is on-premise vs. in Azure or another cloud.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f43ff24-610d-5bd7-cc54-14a418b7d494
* Version Independent ID: 3a677b3a-712c-dd35-e31c-dfcc18808c43
* Content: [Switch to Microsoft Defender for Endpoint - Onboard](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-onboard?view=o365-worldwide#onboard-devices-to-microsoft-defender-for-endpoint)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-onboard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-onboard.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @digitalzomb and thank you so much for your feedback. I am looking into this and will post an update here soon. Appreciate you raising this to our attention!

**Comment by denisebmsft** [comment]
Greetings @digitalzomb @yogkumgit 

The article has been updated and the changes will be live later today (around 4 p.m. Pacific Time). Thank you again for the helpful feedback!
