### ISSUE TITLE
Connection to what to run the powershell example provided?

### ISSUE THREAD

**Issue by dodge1350-frp** [MicrosoftDocs/microsoft-365-docs#5502]
I can't tell you how disappointed I am to view the powershell examples provided in absolutely every powershell example that requires a connection to something before the powershell can be performed.  In each and every case, the connection to use the powershell is ommitted, as if everyone is supposed to know organically what the connection should be to for the powershell to run.  With all the different frameworks and crazy paths for connections ( some of the azure ad connections for things outside of exchange, require the exchange framework to connect to ), it is an absolute must.  Instead I find myself having to go off to search engines to try and cipher out what connection is required for the powershell you have provided to run.  This is unacceptable.  PROVIDE THE DAMN CONNECTION INFORMATION@!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@dodge1350-frp Thanks for feedback. Auditing article makes it clear that cmdlets are run in EXO powershell. I will look into adding link to the connection topic. We try to avoid including the  actual connection steps in topic and just [link to topic with the connection steps](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps). This allows us to maintain one authoritative source, in case the connection steps change like they did with basic auth was deprecated. You also might consider bookmarking links to the connection steps for the various services. Another alternative is to create and use scripts to connect to powershell.

**Comment by dodge1350-frp** [comment]
Great, since this isn't going to be addressed, who should I create a ticket with for each event I encounter so I can get results quicker than I am today?  I don't have the luxury of spending boatloads of time trying to figure out how to connect to something via powershell when it should be readily provided in the powershell example.
