### ISSUE TITLE
Add a note to the table of capabilities per supported operating systems

### ISSUE THREAD

**Issue by D4m4** [MicrosoftDocs/microsoft-365-docs#5503]
While TMV covers a wide range of features in down-level OS it is also not clear from the table in (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-supported-os?view=o365-worldwide#capabilities-per-supported-operating-systems-os-and-platforms) that there are certain features that are not supported in down-level OS. 

For ex.  scid-2012 as per the MDE portal "This security control is only assessed for machines on Windows 10, version 1709 or later, and Windows Server 2016 and 2019." but the table would indicate that all TVM features are covered also in servers 2008/2012 R2. 

Adding a note stating " some features are not available for down-level OS, check the Portal scid for more details on supported OS" would be helpful when we deal with this questions from customers. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1f5402-b627-d205-8e88-ca3fe609ef5f
* Version Independent ID: 0c91f8eb-368a-681a-209c-b03ff823945a
* Content: [Supported operating systems platforms and capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-supported-os?view=o365-worldwide#capabilities-per-supported-operating-systems-os-and-platforms)
* Content Source: [microsoft-365/security/defender-endpoint/tvm-supported-os.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tvm-supported-os.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@D4m4 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5605

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @D4m4 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
