### ISSUE TITLE
Update text on CSV file

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#5505]
[Enter feedback here] In the section about the CSV it would be worth highlighting that the file should never be edited with Excel as it may corrupt the file data. Also, to make sure that any leading zeroes are preserved in the device serial numbers.
(I have had several customers trip up on these points).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05581e98-a835-1277-3cef-aea6221d9065
* Version Independent ID: e2b54d7d-8f38-5118-ef85-ce9b16da291f
* Content: [Register new devices yourself - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/register-devices-self?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-started/register-devices-self.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/register-devices-self.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@ceaton001 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5640

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ceaton001 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
