### ISSUE TITLE
Update CSV file guidance

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#5506]
[Enter feedback here] In the section about the CSV it would be worth highlighting that the file should never be edited with Excel as it may corrupt the file data. Also, to make sure that any leading zeroes are preserved in the device serial numbers.
(I have had several partners trip up on these points).

Also, the comment about using a different Get-AutopilotInfo.ps1 is no longer true as csv format is common now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd1cbbf-99b1-f6ca-94ee-8f30015339f9
* Version Independent ID: c4d8538b-f436-7e3d-0372-0aae84955e01
* Content: [Steps for Partners to register devices - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/register-devices-partner?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-started/register-devices-partner.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/register-devices-partner.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@ceaton001 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5639

Once the author approves PR, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ceaton001 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
