### ISSUE TITLE
I have followed the instructions and continue to receive the error.

### ISSUE THREAD

**Issue by meahesachin** [MicrosoftDocs/microsoft-365-docs#5511]
[Enter feedback here]

I have followed the instructions and continue to receive the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00421a8e-42cf-c393-f91d-da1b7d7cc7da
* Version Independent ID: de00b816-762d-2171-eb7f-1ce6a55ec189
* Content: [Getting a mailbox not found error in Outlook on the web - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/mailbox-not-found-error?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/mailbox-not-found-error.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/mailbox-not-found-error.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@meahesachin Thank you for your feedback. The issue could happen if there are any objects or aliases blocking the mailbox from being provisioned. Generally, if it is a new user, assigning the license should take care of the provisioning. However, in your case if it still has not been solved and if you are continuing to receive the error in the outlook web app, I'd recommend contacting Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @meahesachin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
