### ISSUE TITLE
Background color and disclaimer changes?

### ISSUE THREAD

**Issue by Jens-Lorenz** [MicrosoftDocs/microsoft-365-docs#552]
I noticed that the background color is not applied to the background of the logo any longer? =&gt; in the above example the black background behind the Office 365 logo. This also changed for existing branding.
Also, the disclaimer has now an added link to the Microsoft privacy policy plus an information, that the mail is protected with Office 365 Mail Encryption and a link to the Office support page. 

Is this an intended change (I just missed) and if so, will it be possible to change the link to an organisational privacy policy (as this service is usually used in the contact of an organisation where Microsoft is the processor) and to remove the information and link regarding OME?

Will the change that the background color does not apply to the logo background stay or will the logo background be adjustable separately? (The latter would be great.) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04de3d3-6a94-29f8-3a3d-68ed9422e058
* Version Independent ID: e50fc407-2c78-a3cc-71cd-7978ca340189
* Content: [Add your organization brand to your encrypted messages](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages#feedback)
* Content Source: [microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@Jens-Lorenz - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@KCCross - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by samschan-ms** [comment]
there's a bug with the background logo not showing, and we  that we are fixing that.

For the disclaimer, it's a new layout change, and you will be able to  to point to the organization's privacy. We're just setting up the new layout, and there'll be more details on setting the privacy later.

**Comment by mypil** [comment]
@samschan-ms - We would like to follow up. Do you have any updates if the bug has been fixed?

Thank you.

**Comment by mypil** [comment]
@Jens-Lorenz - From our understanding, the issue you raised has been answered by KCCross and samschan-ms so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by roderick-cloudlife** [comment]
@Samschan-ms when will the disclaimer option be added to set a custom privacy policy?
