### ISSUE TITLE
Allow setting password expiration policy on other platforms

### ISSUE THREAD

**Issue by bowlerma** [MicrosoftDocs/microsoft-365-docs#5521]
Is there a way of setting the password expiration policy that doesn't rely on a Windows only PowerShell module?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52c6916-7e79-9a9c-b7a6-47041ddb81e3
* Version Independent ID: 43c9b873-d354-d814-3065-1e8832361b86
* Content: [Set an individual user's password to never expire - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@bowlerma Thank you for your feedback. Yes, you can set the policy from the M365 Admin center but if you would like to use the never expire attribute on the policy it can be only performed via powershell. 

If you would like to setup a password expiration policy via the M365 admin center, Below are the steps

Follow the steps below if you want to set user passwords to expire after a specific amount of time.

In the admin center, go to the Settings > Org Settings.

Go to the Security & privacy page. If you aren't a global admin, you won't see the Security and privacy option.

Select Password expiration policy.

If you don't want users to have to change passwords, uncheck the box next to Set user passwords to expire after a number of days.

Type how often passwords should expire. Choose a number of days from 14 to 730.

In the second box type when users are notified that their password will expire, and then select Save. Choose a number of days from 1 to 30.

Reference:- https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide#set-password-expiration-policy

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bowlerma Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
