### ISSUE TITLE
"Define the maximum size of downloaded files and attachments to be scanned" Max Filesize missing

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/microsoft-365-docs#5522]
What is the Defaultsze if you do not configure this setting. It´s missing on the website and in the ADMX-Template
"Define the maximum size of downloaded files and attachments to be scanned"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88462853-9de7-d95d-37bc-a34cb58d45ba
* Version Independent ID: 495ad6de-ff5b-ea4b-e6af-65e1b275fbbf
* Content: [Enable and configure Microsoft Defender Antivirus protection capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-real-time-protection-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-real-time-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-real-time-protection-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@PehDeh Thank you for your feedback. We have made the changes in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5600

Thanks
Sri

**Comment by yogkumgit** [comment]
@PehDeh Changes are not approved by PM, closing this issue. Thanks. @msbemba Let the PM to decide, they have the big picture. Thanks for your contribution.
