### ISSUE TITLE
Guest Sharing article includes incomplete sentence.

### ISSUE THREAD

**Issue by TinaMcN** [MicrosoftDocs/microsoft-365-docs#5529]
The localization vendors noticed that this sentence appears to be incomplete:
"For each specified group, you can choose of those users can share with Anyone links."

Should it include "which" or some other alteration so the sentence makes sense?
"For each specified group, you can choose **which** of those users can share with Anyone links."

![image](https://user-images.githubusercontent.com/53281468/124195981-4dbf8c00-da80-11eb-8434-a532ab53d97d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030743fd-0c22-025b-f190-f637a2772506
* Version Independent ID: fbded472-e3ea-4297-c527-810e117ea7ea
* Content: [Microsoft 365 guest sharing settings reference](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-guest-settings?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-guest-settings.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@TinaMcN, yes, it should include "which."

**Comment by msbemba** [comment]
@TinaMcN Thank you for your feedback. We have made changes to the document via PR#5603 

Thanks
Sri

**Comment by TinaMcN** [comment]
@msbemba @yogkumgit thanks very much for your help!
