### ISSUE TITLE
Switch from Google Workspace should consider using SharePoint Migration Manager

### ISSUE THREAD

**Issue by tomresing** [MicrosoftDocs/microsoft-365-docs#5534]
Migrate [Google files to Microsoft 365 for business](https://docs.microsoft.com/en-us/microsoft-365/business-video/moveto-microsoft-365/mover-migrate-files?view=o365-worldwide) in the Switch from Google Workspace to Microsoft 365 might need an update. I see that it was authored in January. [Migrate Google Workspace to Microsoft 365 with Migration Manager](https://docs.microsoft.com/en-us/sharepointmigration/mm-google-overview) is more recent and uses a different method that may be easier for small businesses to follow.

I think @JoanneHendrickson and @twernermsft will be interested in this.

**Comment by twernermsft** [comment]
@Efren ***@***.***> something to think about with the Google Workspace > M365 migration content?

From: Tom Resing ***@***.***>
Sent: Friday, July 2, 2021 3:07 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Tom Werner ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/microsoft-365-docs] Switch from Google Workspace should consider using SharePoint Migration Manager (#5534)


Migrate Google files to Microsoft 365 for business<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fbusiness-video%2Fmoveto-microsoft-365%2Fmover-migrate-files%3Fview%3Do365-worldwide&data=04%7C01%7Ctwerner%40microsoft.com%7C9fc4d9b946e94fea62c908d93da5a933%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637608604216107180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Js8IriUuDJEbcX0XFHE4ZzhcKK%2FReXXwKBFYI1GBPfY%3D&reserved=0> in the Switch from Google Workspace to Microsoft 365 might need an update. I see that it was authored in January. Migrate Google Workspace to Microsoft 365 with Migration Manager<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fsharepointmigration%2Fmm-google-overview&data=04%7C01%7Ctwerner%40microsoft.com%7C9fc4d9b946e94fea62c908d93da5a933%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637608604216117182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7IgRMkVdaF0tF6EfAvoRN1RL58D%2B68n1A0UPBH55XXQ%3D&reserved=0> is more recent and uses a different method that may be easier for small businesses to follow.

I think @JoanneHendrickson<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJoanneHendrickson&data=04%7C01%7Ctwerner%40microsoft.com%7C9fc4d9b946e94fea62c908d93da5a933%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637608604216117182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bJPCM3pWVvr8hbxTQRPp5Bb%2FTN0oO597SPTtg%2Fra4SM%3D&reserved=0> and @twernermsft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftwernermsft&data=04%7C01%7Ctwerner%40microsoft.com%7C9fc4d9b946e94fea62c908d93da5a933%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637608604216127175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gfqALbXaI4WsLnC780NLMPWxyms5hM3i07qn0ekViEw%3D&reserved=0> will be interested in this.

-

**Comment by yogkumgit** [comment]
@efrene Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@efrene Gentle reminder.

**Comment by efrene** [comment]
Thanks. The old article has been swapped out for the newer one in the Switch from Google Workspace to Microsoft 365 set.  We hope to have an accompanying video in the near future. Thanks,
