### ISSUE TITLE
 audit log was not enabled by default.

### ISSUE THREAD

**Issue by nakamae1983** [MicrosoftDocs/microsoft-365-docs#5535]
[Enter feedback here]
I get some new tenants, but the audit log was not enabled by default.

Is the explanation reversed?

Auditing must be enabled as in "Turn on auditing".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn auditing on or off - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@nakamae1983 The documentation is up-to-date. For new tenants, would suggest that you verify that auditing is enabled. 

We've added a section in the topic about doing this: https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide#verify-the-auditing-status-for-your-organization
