### ISSUE TITLE
[LOC]Fixed inappropriate japanese "「セキュリティ Connectコンプライアンス センター PowerShell &」"→"セキュリティ & コンプライアンス センター PowerShell に接続する" (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/microsoft-365-docs#5542]
ja-jp:"https://docs.microsoft.com/ja-jp/microsoft-365/enterprise/cmdlet-references-for-microsoft-365-services?&view=o365-worldwide#sharepoint-online-powershell-cmdlets"
![cmdlet-references-for-microsoft-365-services_j](https://user-images.githubusercontent.com/40815708/124536745-79ad8980-de53-11eb-9190-8f60e6c61db7.png)

en-us:"https://docs.microsoft.com/en-us/microsoft-365/enterprise/cmdlet-references-for-microsoft-365-services?&view=o365-worldwide#sharepoint-online-powershell-cmdlets"
![cmdlet-references-for-microsoft-365-services_e](https://user-images.githubusercontent.com/40815708/124536734-74503f00-de53-11eb-81d0-e2b83671b886.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf689c7-49db-7fdc-f958-220598816c6b
* Version Independent ID: 0c205cf8-0b5c-9395-f6f7-524f3be5c8de
* Content: [Cmdlet references for Microsoft 365 services - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cmdlet-references-for-microsoft-365-services?WT.mc_id=DT-MVP-4039701&view=o365-worldwide#sharepoint-online-powershell-cmdlets)
* Content Source: [microsoft-365/enterprise/cmdlet-references-for-microsoft-365-services.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cmdlet-references-for-microsoft-365-services.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@TinaMcN Please help us in resolving this issue. Thanks

**Comment by TinaMcN** [comment]
@hyoshioka0128 thanks for reporting the issue.  I sent the article for human translation.

**Comment by yogkumgit** [comment]
@TinaMcN

**Comment by TinaMcN** [comment]
@hyoshioka0128 the article is human translated now.  Can you please check it and see if it looks ok now?

**Comment by hyoshioka0128** [comment]
@TinaMcN  - Thanks! Fixed.
Closed #5542 .
