### ISSUE TITLE
Offboarding server 2019 (ASC Integration)

### ISSUE THREAD

**Issue by D4m4** [MicrosoftDocs/microsoft-365-docs#5545]
Clearer instructions for **offboarding Server 2019 which has been onboarded using the ASC integration.** The information there is vague and does not clarify that for servers onboarded via the ASC integration the offboarding method is the same as win10 - local script, there is nothing that suggest otherwise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks.

**Comment by mjcaparas** [comment]
added links to offboarding.
