### ISSUE TITLE
The requirements is not correct any more

### ISSUE THREAD

**Issue by AndersMaletzki** [MicrosoftDocs/microsoft-365-docs#5546]
Hello

The requirements is not correct any more. They package name is now Microsoft E5 Securtiy 
![ms](https://user-images.githubusercontent.com/43332520/124567342-339cf980-de44-11eb-86f9-318277babbdf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0e285e-07c9-e98f-d96b-668a82b4b9fa
* Version Independent ID: 52fde7e4-0362-eb32-712d-f3e718836232
* Content: [Endpoint detection and response in block mode](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/edr-in-block-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/edr-in-block-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/edr-in-block-mode.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@AndersMaletzki Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5602

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AndersMaletzki Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
