### ISSUE TITLE
Duplicate entries in the product list

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/microsoft-365-docs#5548]
the product list has duplicate entries for:
.  *  Office 365 A3
.  *  Office 365 A5
.  *  Office 365 E3
.  *  Office 365 E5

Are you missing some products? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805a04c5-96c4-ee47-7746-3105e0b7fc45
* Version Independent ID: 9efa7447-6731-6435-d4fc-8ba81344e85a
* Content: [Understand subscriptions and licenses in Microsoft 365 for business](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/subscriptions-and-licenses?view=o365-worldwide#how-many-devices-can-people-install-office-on)
* Content Source: [microsoft-365/commerce/licenses/subscriptions-and-licenses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/subscriptions-and-licenses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@Ronsss Which duplicates are you referring to? Are you interpreting Microsoft 365 E3 and Office 365 E3 as being the same? If so, they're not. The products named Office 365 are separate from the ones named Microsoft 365, this includes A3 & A5, and E3 & E5.

**Comment by Ronsss** [comment]
Right you are.  Blame marketing ...
.
 I foolishly ass-umed that when MS (dis)"improved"  the bundle name from
"Office" to "Microsoft" they were consistent and did it for all bundles.
Silly me. (stupid change, I have a whole rant about using the name
"Mircosoft 365...")

Now that you pointed it out I found this page that shows Office 365 E3 is
still offered
https://www.microsoft.com/en-us/microsoft-365/enterprise/compare-microsoft-365-and-office-365

I don't understand the difference, between the 2 offerings, but I'm not
going to worry about that.

Yes, I agree, close the ticket.

Thanks for the information.
