### ISSUE TITLE
What subscription level/license(s) are required for O365 Sensitivity Labels?

### ISSUE THREAD

**Issue by TracyGH** [MicrosoftDocs/microsoft-365-docs#555]
What subscription level/license(s) are required to leverage O365 Sensitivity Labels?  I cannot find any information in the relevant documentation for sensitivity labels.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Overview of sensitivity labels](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by LauraWi** [comment]
Hi @TracyGH You can find SKU/license info in the Service Descriptions. Sensitivity labels require E3 or E5: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

**Comment by mypil** [comment]
@TracyGH - From our understanding, the issue you raised has been answered by LauraWi. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by pctsltd** [comment]
Hi there - it should be noted that if you don't have E3/E5 then you can just buy Azure Information Protection P1 or P2 which should also work.
