### ISSUE TITLE
SPF still Failing

### ISSUE THREAD

**Issue by Zainabalbasri** [MicrosoftDocs/microsoft-365-docs#556]
I have included spf.protection.outlook.com in the SPF record although the DMARC report still shows an SPF failure with the domain apc01-sg2-obe.outbound.protection.outlook.com !!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email#feedback)
* Content Source: [microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@Zainabalbasri - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
