### ISSUE TITLE
When will this be on general release

### ISSUE THREAD

**Issue by rpidgley** [MicrosoftDocs/microsoft-365-docs#557]
For people on the Targeted release for selected users when will this feature be available on the Microsoft 365 Admin Centre?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dfd658-4729-d198-0aa4-16bed3e8cd97
* Version Independent ID: 456d3090-c924-252e-334e-1a080005b9a1
* Content: [Automatically install or uninstall Office on Windows 10 devices](https://docs.microsoft.com/en-us/microsoft-365/business/auto-install-or-uninstall-office#feedback)
* Content Source: [microsoft-365/business/auto-install-or-uninstall-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/auto-install-or-uninstall-office.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@rpidgley  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@Sirkkuw - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by Sirkkuw** [comment]
This is coming soon (in the Old admin center it is still there) -when it is available it will be on the **Setup** page (find **Setup** on the left nav). I am not sure exactly when as these features are getting rolled out in phases.

**Comment by mypil** [comment]
@rpidgley - From our understanding, the issue you raised has been answered by Sirkkuw. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
