### ISSUE TITLE
Critical information missing regarding Microsoft 365 Group member types

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/microsoft-365-docs#5574]
Hello,

I hope the documentation team will take this request seriously. There is some VERY important information missing from Microsoft 365 Group aka Unified Group documentation: 

There are limitations about which recipient type can be members of Unified Groups. There is also a restriction that keeps Unified Groups from being members of traditional security and distribution groups. This is REALLY critical information to have prior to upgrading to or creating Unified Groups. I can't find this information anywhere in Microsoft documentation. It's also nowhere to be found in the Admin GUI during group creation or upgrade. 

Apparently only mailbox users can be members of Unified Groups? Apparently Unified Groups can't be members of traditional security or distribution groups? This should be well documented across all articles relating to Unified Groups since it's such a massive loss of functionality compared to traditional security and distribution groups (not to mention the unbridled zeal Microsoft applies toward encouraging organizations to upgrade to this group type). Please add membership type guidance to all relevant articles about Unified Groups and please make it known to the development team that a warning should be placed in the Bulk Upgrade and Creation wizards.

I just "upgraded" (arguable word) a long series of nested distribution groups to Microsoft 365 Groups for a customer and now the previously thought-out group nesting logic is no longer available to the company. Both mail routing logic and group memberships have to be completely reworked for all of these groups due to a lack of documentation. Neither myself nor my customer are happy. 

I hope people heed this warning before making the mistake to upgrade. Please fix this so it doesn't happen to other organizations!

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40174ff9-7dc6-a706-c546-77e2391ab8d7
* Version Independent ID: a01b7077-976f-dded-ed25-18e8585b28b0
* Content: [Add or remove members from Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/add-or-remove-members-from-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/add-or-remove-members-from-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/add-or-remove-members-from-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@ckssaas the limitations for migrating to Microsoft 365 groups are covered in [Upgrade distribution lists to Microsoft 365 Groups in Outlook](https://docs.microsoft.com/microsoft-365/admin/manage/upgrade-distribution-lists). Let us know if you find that anything's missing there. @kwekuako fyi.

I'll note in [Compare groups](https://docs.microsoft.com/microsoft-365/admin/create-groups/compare-groups) that Microsoft 365 groups can't be members of security groups or distribution lists. Note that non-mailbox users can be members of Microsoft 365 groups.

**Comment by ckssaas** [comment]
Hi @MikePlumleyMSFT,

After re-reading both the articles you have linked I still disagree that the Microsoft 365 Group group nesting limitations have been made explicitly clear. 

I agree that the limitations of upgrading groups is very clear in the Upgrade article. However, I would argue that the topic of "upgrading groups" vs. the topic of "group limitations" are independent topics. Without describing the link between the two topics, the limitations of the upgrade "wizard" are somewhat arbitrary and I think it's a stretch to assume administrators would make this connection. Nested grouping is not merely a limitation of upgrading; it's a fundamental limitation of the object type.  

I suggest that detailed limitations be added to both the [Compare Groups](https://docs.microsoft.com/en-gb/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide) article and [Learn about Microsoft 365 Groups](https://support.microsoft.com/en-us/office/learn-about-microsoft-365-groups-b565caa1-5c40-40ef-9915-60fdb2d97fa2) articles and that one of the fundamentals articles be linked in the [Upgrade Groups](https://docs.microsoft.com/en-gb/microsoft-365/admin/manage/upgrade-distribution-lists?view=o365-worldwide) article to completely clarify the topic.

Thanks!

**Comment by MikePlumleyMSFT** [comment]
@ckssaas I've submitted updates to [Compare groups](https://docs.microsoft.com/microsoft-365/admin/create-groups/compare-groups) to call out the nesting limitations and link to the upgrade article. They should be published in the next day or so. [Learn about Microsoft 365 Groups](https://support.microsoft.com/office/b565caa1-5c40-40ef-9915-60fdb2d97fa2) is aimed at end users rather than admins, so we wouldn't include info on nesting there.

**Comment by yogkumgit** [comment]
@ckssaas Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
