### ISSUE TITLE
missing tasks.office.com , to open Planner in Teams

### ISSUE THREAD

**Issue by akamarvin** [MicrosoftDocs/microsoft-365-docs#5578]
[Enter feedback here]
Hi, 
I think this helpful list of endpoints list is missing    
  tasks.office.com:443 
which is accessed whenever you try to open a Planner view from a Teams channel. 
And for that same important matter (Planner) , 
   dc.services.visualstudio.com:443 
also seems not so optional, as entry 75 would let you believe.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@LauraWi Gentle reminder.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. The reason tasks.office.com is not listed is because it is covered by *.office.com. Also, dc.services.visualstudio.com is optional because it only applies to certain environments and is not required by all Office 365 configurations. -Kelley
