### ISSUE TITLE
Please review "To update your phone number and email address"  section of the article

### ISSUE THREAD

**Issue by MartaRosaGomes** [MicrosoftDocs/microsoft-365-docs#5579]
Hi team, 

In the section "To update your phone number and email address"  the steps to change the phone number and email address don't replicate on Support's side in CMAT and thus sometimes it's difficult to entitle an Admin due to this. 
The way an Admin can edit any User's info in the admin center in a way that would be replicated on Support's side in CMAT are:

To change the alternative email address:

Go to https://admin.microsoft.com/AdminPortal/ > Users > Active Users  > Click on user's name > Alternate email address (edit address) and change to their email address. 

To change the phone number:
Go to https://admin.microsoft.com/AdminPortal/ > Users > Active Users  > Click on user's name > Phone Number (Click on Manage contact information and edit the phone number .

Any questions let me know!

BR
Marta 

**** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecf0dbf6-b2f8-5370-fd04-f7a13073835a
* Version Independent ID: 8b58ecef-f957-4360-08a5-80d6fe8886e3
* Content: [Update your admin phone number and email address - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/update-phone-number-and-email-address?view=o365-worldwide#to-update-your-phone-number-and-email-address)
* Content Source: [microsoft-365/admin/manage/update-phone-number-and-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/update-phone-number-and-email-address.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@MartaRosaGomes Thank you for your feedback. The document pertains to adding an alternate phone number or email address and these are the methods to contact admin when they reset the password. I can confirm that this is the right way to do it, I would request you to check internally to see why the details are not syncing with CMAT. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MartaRosaGomes Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
