### ISSUE TITLE
Schema ActionType AmsiContent

### ISSUE THREAD

**Issue by Bievens** [MicrosoftDocs/microsoft-365-docs#5580]
Unable to locate ActionType "AmsiContent" in the schema. Is this actiontype not available to advanced hunting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc9f0472-a1fe-8d1e-f081-fd3c97bbfc92
* Version Independent ID: ddc56801-5d2f-cef2-c6fe-3360368088fa
* Content: [Data tables in the Microsoft 365 Defender advanced hunting schema](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-schema-tables?view=o365-worldwide#get-schema-information-in-the-security-center)
* Content Source: [microsoft-365/security/defender/advanced-hunting-schema-tables.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-schema-tables.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@Bievens Thank you for the feedback. I was not able to locate "AmsiContent" in the schema and I don't see them in any of the reference documents for advanced hunting. So, I'd say this action type is not available for advanced hunting. If you'd like to see this action type in the schema,  you can provide feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Bievens Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by schmurky** [comment]
@bievens for additional guidance, not all ActionTypes are documented, only tables and column names are. Kindly check inside the portal under DeviceEvents for AmsiContent.
