### ISSUE TITLE
Ported from https://github.com/MicrosoftDocs/powerapps-docs/issues/2480

### ISSUE THREAD

**Issue by tapanm-MSFT** [MicrosoftDocs/microsoft-365-docs#5582]
feedback from: https://github.com/MicrosoftDocs/powerapps-docs/issues/2480

------------------------------
Could you please add the blue "Important" or purple "Note" tag to the following paragraph on this page:

"If a user is defined in multiple policies of the same type, only the policy with the highest priority is applied to them. Any remaining policies of that type are not evaluated for the user (including the default policy)."

There are SEVERAL blogs out in the world with the wrong information on this. Specifically, folks are saying to use multiple polcies to get around the 60 (now 350) limit for Impersonated User Protection.

As written, this paragraph is perfect, but easy to miss. Please consider calling it out as a note (like the blue one at the top of the page) or important tag (purple).
------------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4194fdd-c5de-d424-319a-5e83774b36c2
* Version Independent ID: 83997ad4-a9bd-146e-5da0-8022458cf3ea
* Content: [Order and precedence of email protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@tapanm-MSFT Thank you for the feedback. The document has been updated via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5595. Once the author approves this change, you will be able to see the updates in the document.

Thanks
Sri

**Comment by chrisda** [comment]
PR approved.

Thanks for the feedback.

Closing
