### ISSUE TITLE
Use modern Mg Graph cmdlets

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/microsoft-365-docs#5588]
Azure AD API will be end of support in 1 year.
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

The example should be updated to both:
1. Use the Microsoft Graph Powershell SDK
1. Teach the user to build a function so that they can reuse the function easier later

Here is a function to simplify things:
https://gist.github.com/JustinGrote/57a8efadc7ed5c689dc629737c9a5d48

So instruct the user to save the script, import it the same way as mentioned, then run the following commands:
```powershell
Connect-MgGraph -Scopes 'Directory.ReadWrite.All'
Select-MgProfile 'Beta'
Get-MgGroup 'MyTeamsGroup' | Set-MgM365CreatorGroup
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Gentle reminder.

**Comment by msbemba** [comment]
@JustinGrote Thank you for your feedback. I'm currently working with the author on the script and will update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please reply. Thanks

**Comment by tiburd** [comment]
Closing this issue due to age and inactivity.

FYI: @yogkumgit
