### ISSUE TITLE
Incorrect text

### ISSUE THREAD

**Issue by AlexanderSaad-Crayon** [MicrosoftDocs/microsoft-365-docs#5591]
Under the section "Azure External collaboration settings" the screenshot of the available Azure collaboration settings -> "Guest Invite settings" shows the actual options in the portal. However, the instructions bellow are incorrect:

_Click External identities.
On the Get started screen, in the left navigation pane, click External collaboration settings.
Ensure that Admins and users in the guest inviter role can invite and Members can invite are both set to Yes._ 

Those options are deprecated. Could you update the documentation so that it is clear which if the portal settings do what?

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147fb47a-99b2-f8ef-9ca6-35696d49c3fb
* Version Independent ID: b2f1b521-f231-48c2-b61f-f71bf9248d1c
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide#azure-external-collaboration-settings)
* Content Source: [microsoft-365/solutions/collaborate-as-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-as-team.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@AlexanderSaad-Crayon Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5638

Once the PR is approved by the author the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AlexanderSaad-Crayon Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
