### ISSUE TITLE
How many devices for business users? 

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/microsoft-365-docs#5594]
Please clarify the number of devices business users can install on. The way this page is written suggests either 10 or 15 devices.
This video implies 10 devices https://www.youtube.com/watch?v=ahhajwWQtUw  Video: 1min

Do business users have same 5 device limit as consumers? 
Or do they have the right to install on 5 devices in each of 2 classes?
ie 5 PC / Macs / Tablets and 5 phones
Or do they have the right to install on 5 devices in each of the 3 classes? 
ie 5 PC / Macs and 5 Tablets and 5 phones

ie: https://www.bbc.com/worklife/article/20180723-the-commas-that-cost-companies-millions 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805a04c5-96c4-ee47-7746-3105e0b7fc45
* Version Independent ID: 9efa7447-6731-6435-d4fc-8ba81344e85a
* Content: [Understand subscriptions and licenses in Microsoft 365 for business](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/subscriptions-and-licenses?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/licenses/subscriptions-and-licenses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/subscriptions-and-licenses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Ronsss Thank you for your feedback. Each person can install Office on up to five PCs or Mac, five tablets, and five phones. They cannot exceed 5 on any of the classes mentioned above. 

I.e  5 PC / Macs and 5 Tablets and 5 phones

Hope this helps!

Thanks
Sri

**Comment by Ronsss** [comment]
Thank you for the confirmation of what I thought.

Now can you get MS to update all of the MS documentation to reflect what
you just said?  Particularly the sales pages, since they are the first
place users look. This is a significant difference from 365 consumer, so
the "natural" assumption is that both 365 consumer and business is the
same.

**Comment by msbemba** [comment]
@Ronsss Thank you for the quick response. Would you be able to help us with the link where it says this incorrectly? This channel is to fix issues with this particular document, however, if you can provide the URL for documents that have incorrect information I shall try to route it to the correct team.

Thanks
Sri

**Comment by Ronsss** [comment]
Start with this search:
https://duckduckgo.com/?t=ffab&q=buy+365+business&ia=web
most of the links have the vague info.
.
Do the net searches for the search string I identified in the original
report.
I've identified an issue for free, you are paid to fix it ...

This is up to you, try using Bing search ... right Bing is useless

**Comment by msbemba** [comment]
@Ronsss Thank you for the quick response. As mentioned earlier, we handle issues or modifications only on this repository and I'll update the concerned team about fixing the vague information on other support/sales documents.

Thanks
Sri

**Comment by Ronsss** [comment]
Thank you I appreciate that. MS should have a clear and consistent message
to users. Hopefully the other areas will act on the suggestion.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Ronsss Your feedback is passed on to the backend team, they will take an appropriate action. Thank you very much for your active participation. We proceed here to close it. Thanks again for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
