### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by StobR** [MicrosoftDocs/microsoft-365-docs#5599]
Point 3 under 'Set strong passwords' should read:

You can turn **OFF** strong password requirements for specific users with this command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be4677b-4f4c-5447-4af6-bd773b485051
* Version Independent ID: 0fc99a74-53c8-d9c7-b4ae-58adee1d48db
* Content: [Turn off strong password requirements for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/strong-password?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/strong-password.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/strong-password.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@StobR Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5637

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @StobR Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
