### ISSUE TITLE
Discrepancy in EnableAuthenticationSafetyTip Documentation

### ISSUE THREAD

**Issue by MikeDembek** [MicrosoftDocs/microsoft-365-docs#560]
In this document, it's strongly encouraged to leave the EnableAuthenticationSafetyTip set to true, which is its default setting:

https://docs.microsoft.com/en-us/powershell/module/exchange/advanced-threat-protection/set-antiphishpolicy?view=exchange-ps

However, here, the recommendation is that it be set to False except in an aggressive anti-phishing policy.  Which document is accurate for typical environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3992d573-0771-7433-a811-e798bdf0c8fa
* Version Independent ID: 83ea1968-321b-7c5f-f0a1-7c604da04960
* Content: [Configuration best practices for EOP and Office 365 ATP security, best practices, settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work,](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/best-practices-config-exchange-online-protection-sec)
* Content Source: [microsoft-365/security/office-365-security/best-practices-config-exchange-online-protection-sec.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/best-practices-config-exchange-online-protection-sec.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@MikeDembek  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
@MikeDembek - I'm relatively sure this is the document you should attend to, but I'm also checking in to your question to be sure. Thanks very much for jumping on this!

**Comment by MaratMussabekov** [comment]
Hello @MikeDembek , @mypil 
Looks like the source article was removed.
Anyways, the idea to keep EnableAuthenticationSafetyTip enabled is a good way to warn the users about potential phishing.
Thank you

**Comment by mypil** [comment]
@MikeDembek - From our understanding, the issue you raised has been answered by MSFTTracyP and MaratMussabekov. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
