### ISSUE TITLE
More specific guidance on what permissions are needed for the task in the article

### ISSUE THREAD

**Issue by halligas** [MicrosoftDocs/microsoft-365-docs#561]
Saying "Using a work or school account that has global administrator privileges (or appropriate Security & Compliance Center roles" is not a good way to put it.  The goal is to reduce the number of global admins.  Call out the specific roles needed so that least privileges can be granted 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an administrator in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files#feedback)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@halligas  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @halligas, that's definitely a good point and current wording is the opposite of the recommended principle of least privilege.
Dear @MSFTTracyP ,
as far as I know:
1. to view quarantined messages you need either: 

- **Office 365 roles**: global admin, exchange admin or compliance admin 
- **Exchange Online roles**: Organization Management or Hygiene Management
2. to view quarantined files you need Office 365 global admin, Sharepoint admin or compliance admin role
3. to set the quarantine retention period, you need Exchange Online Organization Management 
 Hygiene Management role
 
could you please advise, am I correct?

Thank you

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by halligas** [comment]
Well, I am digging into this.  There is now a “Quarantine” role in Security and Compliance Center, but it does not appear to be working for me.  My thought is that Security Reader + Quarantine _should_ be enough.

I am actually Microsoft myself.  Adding my internal email to this thread.  I am engaging the PG to get the right answer.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mypil** [comment]
@halligas - Do you have any updates on the findings from the PG? Please advise if there is anything you found that can be added in the docs so we can let @MaratMussabekov create a PR for it.

Thank you.

**Comment by mypil** [comment]
@halligas - We would like to follow up. Do you have any updates on this?

Thank you.

**Comment by mypil** [comment]
@halligas - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by halligas** [comment]
I am not sure how to reopen this.  There is now a role in Security and Compliance Center called “Quarantine Administrator” that gives these permissions.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MaratMussabekov** [comment]
Hello @halligas, @MSFTTracyP 
Please have a look at the PR above, do you think it will be enough? 
Thank you

**Comment by halligas** [comment]
Would be better to be specific and call out the specific roles, but this is better than before.

**Comment by mypil** [comment]
**Re-opening issue until PR #808 will be merged**

**Comment by pawp81** [comment]
Could you please document what permissions are required to access email messages and files in the quarantine?
Currently this article says: "You must have global administrator (GA) permissions in Office 365, or be a member of one or more Security & Compliance Center role groups, to work with quarantined messages or quarantined files. See Permissions in the Office 365 Security & Compliance Center for more information." "
however referenced article doesn't cover permissions for Quarantine at all.

**Comment by gtyrozz** [comment]
I found Hygiene Management closest to the goal, however it allows access to threat management policies as well. It creates conflict of interests for us. As the one, who's job is to assess captured messages, should not be in position to configure policies, which capture it.
https://docs.microsoft.com/en-us/exchange/hygiene-management-exchange-2013-help
describes, Management roles assigned to this role group, however again none of these are Quarantine dedicated.
My question would be what role (not role group) explicitly allows access to work on quarantined messages- search, release etc.?

**Comment by mypil** [comment]
@halligas - Closing issue since PR #808 has been merged.
@pawp81 - Please open a new issue and add in your feedback or suggestions in the related doc - Permissions in the Office 365 Security & Compliance Center.
@gtyrozz - It would be best if you open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so they can answer your technical query. 

Thank you all for engaging the community to help improve the MS docs. We appreciate your feedback and keep it coming!
