### ISSUE TITLE
Out of dATE

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/microsoft-365-docs#5610]
This information appears out of date, there is no "Products" tab on the cost management + billing pane anymore and thus I cannot find how to delete a subscription
https://docs.microsoft.com/en-us/microsoft-365/commerce/close-your-account?view=o365-worldwide#step-3-delete-all-disabled-subscriptions
![image](https://user-images.githubusercontent.com/15258962/125491908-94417ef4-4f7e-4927-9db7-67326e67bea7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8adb403b-fded-7b9c-c093-915ca9bb348d
* Version Independent ID: df08fc6b-a752-084b-448a-a253db2a40d5
* Content: [Close your account](https://docs.microsoft.com/en-us/microsoft-365/commerce/close-your-account?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/close-your-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/close-your-account.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@JustinGrote Thank you for your feedback. I was able to navigate to the products page on the M365 admin center to cancel M365 subscriptions. Looks like you are on the Azure Page trying to cancel an Azure subscription, If that is the case Please follow the document which talks in detail about Cancelling subscription in the Azure portal -https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/cancel-azure-subscription

Hope this helps!

Thanks
Sri

**Comment by JustinGrote** [comment]
@msbemba I think you're right, my bad! Apologies
