### ISSUE TITLE
Threat Explorer link does not work

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/microsoft-365-docs#5617]
The instructions under [View details about spoofed messages](https://docs.microsoft.com/microsoft-365/security/office-365-security/learn-about-spoof-intelligence#view-details-about-spoofed-messages) fail to work.

Following this link takes you to the security.microsoft.com "Explorer" page, which only shows Malware and Phish options, and displays no spoofed messages.

<https://security.microsoft.com/threatexplorer?dltarget=explorer>

The entire change to these new portals has caused a complete loss of fidelity in the documentation and product with links not being updated correctly and documentation now out of date.

The product no longer functions as advertised.

Also using Spoof intelligence to allow/block senders is poor practice.  Microsoft should be recommending that people contact the senders to correctly configure their email Authentication.

Also, why is the Spoof Intelligence report not available under Security portal / Review?  
It's buried under the Allow/Block policy for Threat Policies, which oddly does not always appear with the link to view spoofing activity.

Microsoft are not contributing to the wider community here by failing to obey DMARC reporting, and recommending people turn off SPF Hardfail simply so they get more telemetry to consume themselves. 

Clearly Microsoft are NOT your friend.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c0cbdb-062e-08e1-7c7c-cedab550f01b
* Version Independent ID: 2791a840-3284-bc0d-7b9e-026b852797e6
* Content: [Spoof intelligence insight - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/learn-about-spoof-intelligence?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anthonynz, I updated the statement in the topic to say:

> A link to open [Threat Explorer](threat-explorer.md) to see additional details about the sender under **View** \> **Phish** in Microsoft Defender for Office 365.

The information is there, but you need to change the view to View \> Phish.

Also, most (virtually all?) of the topics under <https://docs.microsoft.com/microsoft-365/security/office-365-security> were converted/updated from Security & Compliance Center procedures to Microsoft 365 Defender portal procedures by the end of June. Some topics will never be converted (for example, [Permissions in the Security & Compliance Center](https://docs.microsoft.com/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center)), and will remain until the Security & Compliance Center is no longer available.

**Comment by yogkumgit** [comment]
@anthonynz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by anthonynz** [comment]
Thanks guys, adding the note in documentation is fine as it explains we need to change the view to "phish".

But this means there's a product bug... 

The shortcut from the new spoof intelligence view for should take us directly to a view in Threat Explorer that is filtered as "Phish" with the "Sender Domain" populated.

Currently it sends us to threat explorer with the "Malware" view selected, and populates the Malware filter with Sender Domain = "Spoofed Domain"

Also, this threat explorer view doesn't allow viewing of Spoof Intelligence domains marked as "Allowed" in spoof intelligence.

Ideally selecting a sample email in Spoof Intelligence would directly open up the message details for that particular email with Message Header available for download.

I can't find the old protection.office.com version of Spoof Intelligence policy, was it replaced with the new experience in M365 Defender ?
