### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/microsoft-365-docs#5619]
In the below article it says Defender for Office 365 is available in G5 licenses 
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-3

But in this article it says Microsoft 365 Defender is not available for US GCC customers. which article is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e396c36f-1f7f-a92a-f425-a08b3aaf44e3
* Version Independent ID: 2f15dfb7-1695-9cf7-7560-f9a51eadd745
* Content: [Microsoft 365 Defender prerequisites](https://docs.microsoft.com/en-us/microsoft-365/security/defender/prerequisites?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/prerequisites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/prerequisites.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@bubhat Thank you for your feedback. As mentioned in this document Microsoft  Defender for 365 is not available for GCC customers yet.  We will work internally to fix the documentation on the other document -https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-3

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bubhat Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
