### ISSUE TITLE
Outdated table for "What sensitivity label capabilities are supported in Office today?"

### ISSUE THREAD

**Issue by gesmyrli** [MicrosoftDocs/microsoft-365-docs#562]
Hello, when was the last time the table under the title "What sensitivity label capabilities are supported in Office today?" was updated? Certain features such as "Apply a sensitivity label to content automatically" are already rolled out to Windows for Word,Excel,PowerPoint and Outlook and this table does not reflect that. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [How sensitivity labels work in Office apps](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by gesmyrli** [comment]
The are also some other features that are defined as TBD or Coming Soon that are already rolled out. Also we need more clear guidance for the features that are rolled out to Outlook for Android and iOS since the Q4 of 2019 is not reflecting current state. thank you

**Comment by mypil** [comment]
@gesmyrli  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Quark35** [comment]
Will there be anyway to label email sent by the iOS default mail app?  or a catch-all to apply a default label to any email without one?

**Comment by greg-lindsay** [comment]
There are two questions here. I've sent a query to the product team and I'm awaiting a reply.

**Comment by MikePaer-MSFT** [comment]
> Certain features such as "Apply a sensitivity label to content automatically" are already rolled out to Windows for Word,Excel,PowerPoint and Outlook and this table does not reflect that. Thank you.

> The are also some other features that are defined as TBD or Coming Soon that are already rolled out.

@gesmyrli - this table refers to the support for sensitivity labeling functionality built-in to the Office applications directly, without any add-ins. The built-in support exists as described in the table. Alternatively, the [Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection), an add-in for Office for Windows, can be used for sensitivity labeling and does support these features already. I think you may be referring to that add-in. We'll look into clarifying this difference in the documentation.

> Also we need more clear guidance for the features that are rolled out to Outlook for Android and iOS since the Q4 of 2019 is not reflecting current state. thank you

@gesmyrli - Support for sensitivity labels in Outlook on iOS and Android is on its way. Q4 (October-December) of calendar year 2019 is the correct target, and I can confirm rollout will be starting _very soon_. You can expect to see an update to this table in the coming weeks with a more precise statement on availability for this.

> Will there be anyway to label email sent by the iOS default mail app? or a catch-all to apply a default label to any email without one?

@Quark35 - No, the iOS default mail app does not support [sensitivity labels](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels). Outlook for iOS and Android will soon support this, which includes support for the the "default label" setting.

**Comment by drmarkrwarnes** [comment]
Are there any ways to disable the sensitivity labels in Outlook for the web and the mobile apps? Not all organisations use labelling within Outlook (disabling the Office add-in using group policy) and having the labels suddenly appear is not a good user experience for large organisations.

**Comment by mypil** [comment]
@greg-lindsay @MikePaer-MSFT - Can you please assist to share your inputs on the additional query from drmarkrwarnes?

Thank you.

**Comment by greg-lindsay** [comment]
Mike should answer this question. It's getting a little into product type questions rather than content questions but it's good to iron out some of these details. I'll ping Mike to make sure he sees this.

**Comment by MikePaer-MSFT** [comment]
> Are there any ways to disable the sensitivity labels in Outlook for the web and the mobile apps? Not all organisations use labelling within Outlook (disabling the Office add-in using group policy) and having the labels suddenly appear is not a good user experience for large organisations.

Thanks for the feedback. I am not aware of controls to disable sensitivity labels in individual endpoints like Outlook for the web or Outlook mobile. I've taken this feedback back to the relevant product teams.
