### ISSUE TITLE
Clarification needed * Auto-labeling isn't currently available in all regions. 

### ISSUE THREAD

**Issue by wbach82** [MicrosoftDocs/microsoft-365-docs#5622]
https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide#compare-auto-labeling-for-office-apps-with-auto-labeling-policies

regarding "* **Auto-labeling isn't currently available in all regions**. If your tenant can't support this functionality, the Auto-labeling tab isn't visible in the admin labeling center."

Can you please describe in details in which regions this feature is not available.. just found out you can't use it in tenants located in germany. Would be good to get detailed information regarding global availability.

**Comment by wbach82** [comment]
@cabailey you have added the footnote. maybe you can give some insights? Thanks

https://github.com/MicrosoftDocs/microsoft-365-docs/commit/0267f1705924ac79f894e8131de73423a662c60e#diff-f3dbfc61c7742bb4929275af8c9951049f73a4db10a77121c2ea3ead7d32a59e

**Comment by cabailey** [comment]
Unfortunately, I don't have insights into the details, because it's an external dependency.  I'm trying to find out if this information is available to customers, in which case I'll add a link for details.  Otherwise, the most accurate statement to publish is what we already have - if your region isn't supported, you won't see the Auto-labeling tab.

**Comment by wbach82** [comment]
thanks a lot @cabailey .. also asked here but got no satisfyingly answer... https://www.yammer.com/askipteam/#/Threads/show?threadId=1285686020857856

**Comment by yogkumgit** [comment]
@wbach82 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
