### ISSUE TITLE
Commands not available in linked Exchange Online PowerShell module

### ISSUE THREAD

**Issue by s-ACS** [MicrosoftDocs/microsoft-365-docs#5625]
Hi Team,
The PS commands 
 New-DkimSigningConfig
and
 Get-DkimSigningConfig
mentioned in the "Manual Custom Domain Setup  - Publish two CNAME records for your custom domain in DNS" section are not included in the ExchangeOnlineManagement module per "Connect to Exchange Online PowerShell".

How can we execute these PS commands to generate the selector records?
 New-DkimSigningConfig
 Get-DkimSigningConfig

Please advise.
----
Figured it out after previously unsuccessful attempts to connect to the Exchange Online PowerShell.
The ExchangeOnlineManagement module only includes the commands to **connect to** the Exchange Online PowerShell.
Once connected _successfully_, the PS commands  **New-DkimSigningConfig** etc are available in the cloud Exchange Online PowerShell.
Could have been made clearer in the MS document(s) ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@s-ACS Thank you for your feedback. I have been able to test the cmdlets on the new module, as the document states Once you are connected to the Exchange online module, you should be able to run the New-DkimSigningConfig and Get-DkimSigningConfig cmdlets. 

Hope this helps!

@yogkumgit There are no changes required in the document for now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @s-ACS Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
