### ISSUE TITLE
Example URI 3 & 4 does not work 

### ISSUE THREAD

**Issue by andreasvogt89** [MicrosoftDocs/microsoft-365-docs#5626]
Hello guys,

 I just tried to use the example URL 3 & 4 and run in:
`Invalid Instance string specified or ClientRequestId not specified in the Url. Documentation is available at http://aka.ms/ipurlws`

I removed `amp;` from the URI and it worked properly. So I gues this is a mistake :)
![image](https://user-images.githubusercontent.com/30302212/125755441-43f983c2-9c8c-4deb-8c5e-1b13fc7588e8.png)

👋
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd333ae2-34f6-4afd-cdb1-db72303a5736
* Version Independent ID: 5fc52fe8-dade-b8b7-7126-c4e7dd902e62
* Content: [Office 365 IP Address and URL web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-ip-web-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by LauraWi** [comment]
PR merged.
