### ISSUE TITLE
Where's the "Initiate Sign-out" section?

### ISSUE THREAD

**Issue by linx-collin** [MicrosoftDocs/microsoft-365-docs#5628]
[Enter feedback here]
The instructions on this page doesn't mention signing the user out of all the products. When you block the account, if they happen to be logged in to Teams or something they can still use it for some time. If it's a disgruntled employee this can be quite contentious. In the Old admin console, you could go into the OneDrive settings and initiate a Sign-out which would disconnect them from all MS products. I can't seem to find that functionality in my current Admin Console.

Thanks
Collin
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@linx-collin Thank you for your feedback. The initiate sign-out is moved to the account tab under users. Click on the Users-->Account tab- Sign out all sessions.

![image](https://user-images.githubusercontent.com/45987684/126350095-f5b7a30f-635d-4359-8eb8-10771215e869.png)

Hope this helps!

Thanks
Sri

**Comment by linx-collin** [comment]
Thanks, apologies, I was trying to initiate a sign-out after the user had already been blocked. Hence why the sign-out feature was not showing.



Regards


Collin

________________________________

**Comment by msbemba** [comment]
@linx-collin Thank you for the quick response. Have a nice day.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @linx-collin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
