### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by bcraigie** [MicrosoftDocs/microsoft-365-docs#563]
Security best practices for Office 365 gives a 404 when clicked.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd8eda3-422f-0ca5-328c-cf049daf296e
* Version Independent ID: 24a28789-1473-dc1f-aa94-67015c1ff12d
* Content: [How Office 365 validates the From address to prevent phishing](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/how-office-365-validates-the-from-address#feedback)
* Content Source: [microsoft-365/security/office-365-security/how-office-365-validates-the-from-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-office-365-validates-the-from-address.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@bcraigie  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Dansimp** [comment]
Thanks for submitting the PR. Approved. Will be live soon.

**Comment by mypil** [comment]
@bcraigie - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
