### ISSUE TITLE
Giphy not listed in urls

### ISSUE THREAD

**Issue by Strick1969** [MicrosoftDocs/microsoft-365-docs#5632]
[There should be a listing for giphy.com under the URL section for Microsoft Teams. If the customer has this url blocked they will not be able to use them.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by msbemba** [comment]
@Strick1969  Thank you for your feedback. I'm currently working with the author to update the giphy.com URL. I shall update you shortly.

Thanks
Sri

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. The Office 365 endpoints web service is only designed to include endpoints that are specific to Office 365 services and features. The services you mentioned are not part of Office 365 and are therefore outside the scope of endpoints we can include in the database. -Kelley
