### ISSUE TITLE
Update how to enable litigation hold

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#5634]
The current steps say to use the classic exchange admin center (eac). Is that still the recommended approach or should we be using the new compliance center (https://compliance.microsoft.com)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff3e4302-c038-67aa-eb29-8b01c7fc4ed6
* Version Independent ID: 680317f5-19be-7268-5b40-f181ea3485da
* Content: [Create a Litigation Hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-litigation-hold?view=o365-worldwide#place-a-mailbox-on-litigation-hold)
* Content Source: [microsoft-365/compliance/create-a-litigation-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-litigation-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jonwbstr  Thanks for the heads up. There's not a way to enable lithold in the M365 compliance center. But you can still use classic EAC, the new EAC, the M365 admin center, or EXO PowerShell. I'll update this topic with instructions for using the M365 admin center. In short, go to Users > Active users in the admin center, select a user, and then click the Mail tab on the user properties flyout page. Then select Manage litigation hold under More actions.
