### ISSUE TITLE
Alert - Admin Submission Result Completed missing in documetation

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/microsoft-365-docs#564]
With the recent introduction of Office ATP automated investigation , a new Alert is added to the Alert policies list: 

Admin Submission Result Completed
This alert is triggered once the admin submission result is generated or updated. -V1.0.0.0

This Alert is not yet referenced in the documentation. 

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance center](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@alexverboon - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@alexverboon Thanks for the heads up. I've added description for this alert policy to the [topic](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies#default-alert-policies). In short, this policy is related to Admin Submissions in advanced threat protection, which is documented here: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission
