### ISSUE TITLE
Import PST files to mailbox

### ISSUE THREAD

**Issue by natlims18** [MicrosoftDocs/microsoft-365-docs#5642]
Could you explain to me if when I upload PST files to users mailbox, the pst files use the size of mailbox available? For example, I have an user that have 30 GB available in size mailbox, if I upload a pst file of 20GB the user will be mailbox size available 10GB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f9f87e-6f96-9663-114a-f6bd74a7a7f4
* Version Independent ID: b3ba56e3-0c78-f286-1c01-12375bf00f62
* Content: [Overview of importing your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/importing-pst-files-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/importing-pst-files-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@natlims18 Thank you for your feedback. That is correct, If you have a user that has30 GB storage space available and you upload a pst file of 20GB, the user will have 10GB of free space if the mailbox import is 100% successful. There are chances that there are corrupted or duplicate items in the PST which might fail during the import stage, so there is a chance that the mailbox size could be more than 10GB after the import.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @natlims18 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
