### ISSUE TITLE
Cannot change URL

### ISSUE THREAD

**Issue by isaacgandalf** [MicrosoftDocs/microsoft-365-docs#5645]
This article states that: 
"You can't rename your team site URL. Your team site URL is based on your onmicrosoft.com domain name. Unfortunately, because of the way SharePoint Online architecture works, you can't rename the team site."

However, I saw this article: https://docs.microsoft.com/en-us/sharepoint/tenant-rename

"It's now possible to change the SharePoint domain name for your organization in Microsoft 365. For example, if the name of your organization changes from "Contoso" to "Fabrikam," you can change contoso.sharepoint.com to fabrikam.sharepoint.com."

Won't renaming the SPO domain name also rename the Team site URL?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35470cb5-bb30-146d-ae76-719079861c5f
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.yml)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@isaacgandalf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5678

Once the author approves the PR, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@pebaum  PR merge request pending. Thanks

**Comment by pebaum** [comment]
this rename feature is not generally available at this time. will update this article once it is.
