### ISSUE TITLE
"Send us your feedback" link goes to a video, not to feedback

### ISSUE THREAD

**Issue by dmland** [MicrosoftDocs/microsoft-365-docs#5647]
In the section "[Send us your feedback](https://docs.microsoft.com/en-us/microsoft-365/security/defender/overview-security-center?view=o365-worldwide#send-us-your-feedback)" on the page [Microsoft 365 Defender overview](https://docs.microsoft.com/en-us/microsoft-365/security/defender/overview-security-center?view=o365-worldwide), the link clearly labeled "[send us your Microsoft 365 Defender feedback](https://www.microsoft.com/videoplayer/embed/RE4K5Ci)" does not allow the user to send feedback, as promised, but leaves the current page to show a useless marketing video _about_ feedback.

Please do not mislead users: The link should be labeled "Learn how Microsoft uses your feedback" or "Watch this video to find out how you can trust us to read your feedback."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5529d2e-f984-0ab7-2140-0af18ccca40a
* Version Independent ID: cdcc45f8-3ce7-dfe9-3342-c8f1680c4f6c
* Content: [Microsoft 365 Defender overview, combining MDO, MDE, MDI, and MCAS](https://docs.microsoft.com/en-us/microsoft-365/security/defender/overview-security-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/overview-security-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/overview-security-center.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@dmland Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5676

Once the author approves the PR, the document will be live.

Thanks
Sri

**Comment by dmland** [comment]
Thanks, but perhaps another "gentle reminder" is needed: 16 days later, it still links to the video.

**Comment by yogkumgit** [comment]
@MSFTTracyP  PR merge request pending. Thanks

**Comment by chrisda** [comment]
Topic updated, but in a different PR than msbemba's.

Thanks for the feedback.

Closing.
