### ISSUE TITLE
Sensitivity and retention labels cannot have the same name

### ISSUE THREAD

**Issue by kkazala** [MicrosoftDocs/microsoft-365-docs#565]
This article suggest creation of "Highly Confidential" retention label, which is impossible, if the default Sensitivity Labels are created (Confidential and Highly Confidential). 
When I try, the following error is displayed "compliance rule with name 'Confidential' already exists."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d8b5b1-6343-5611-9b4a-2e0a1b7cab60
* Version Independent ID: dc3836a2-1176-e021-d6fc-a120bbeec7a8
* Content: [Secure SharePoint Online sites and files](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files)
* Content Source: [microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by BrendaCarter** [comment]
Thank you for this feedback! We're in the process of updating this article with new guidance which will recommend creating a custom label name or a sublabel. Look for it in the next few weeks.

**Comment by mypil** [comment]
@kkazala - From our understanding, the issue you raised has been answered by BrendaCarter. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
