### ISSUE TITLE
On the subscription details page, under Partner information, select Remove.

### ISSUE THREAD

**Issue by jwbqv** [MicrosoftDocs/microsoft-365-docs#5654]
[There' no "Remove" button where the doc says there should be.   Where is it?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 897c41b0-dbc7-d20f-38df-4fa682c35f6f
* Version Independent ID: a45c19e4-b070-afd1-084b-0f2c2b4b6c9c
* Content: [Add, change, or delete a subscription advisor partner - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/add-partner?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/add-partner.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/add-partner.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@jwbqv Thank you for your feedback. You will not see the delete option you are trying to remove a reseller relationship. If you are trying to remove a reseller, you will have to ask your reseller partner to follow instructions here- https://docs.microsoft.com/en-us/partner-center/remove-a-relationship

If you are trying to remove a partner with the below type and still don't see the delete button, I'd recommend you contact Microsoft support from the need help link on your admin center to help you with the request.

1)Partner
2)Advisor
3)MPSA Partner
4)LOB partner
5)Delegated Administrator

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jwbqv Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
