### ISSUE TITLE
This app is blocked  This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

### ISSUE THREAD

**Issue by ThaungHtaikZan** [MicrosoftDocs/microsoft-365-docs#5656]
When I try authorize the mover app . I get this error message "This app is blocked.This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access"

![image](https://user-images.githubusercontent.com/54620266/126074290-725ed45e-e5fa-4639-980b-dc59da0014cd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb326992-4956-af90-0ecb-0eed2e023017
* Version Independent ID: 205f8d3a-0ded-47ef-dc58-8da74abf06bd
* Content: [Migrate Google files to Microsoft 365 for business ](https://docs.microsoft.com/en-us/microsoft-365/business-video/moveto-microsoft-365/mover-migrate-files?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/moveto-microsoft-365/mover-migrate-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/moveto-microsoft-365/mover-migrate-files.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@ThaungHtaikZan THank you for your feedback. I was able to test it in the lab and it works without any issues. There are chances that your google settings are blocking any third-party apps- You can view more information here at https://support.google.com/a/answer/7281227?hl=en#zippy=%2Cblock-all-third-party-api-access and allow access to the app.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ThaungHtaikZan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
