### ISSUE TITLE
Preview Search Results Image

### ISSUE THREAD

**Issue by Exnav29** [MicrosoftDocs/microsoft-365-docs#566]
The image in the Preview Search Results section should be changed to show the new wording. "Search Profile" has been changed in the UI to say "Search statistics".  

I would have made the edit myself but I don't know how to upload a new screenshot.  

Also, the wording in the article needs to be corrected to show the new wording of "Search statistics" instead of "Search profile" once the image has been changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e514aa-9f04-5cc9-93f6-9f5f2f614c2a
* Version Independent ID: dea1ab15-bc09-05c1-b48b-1a06c0b53b50
* Content: [Content Search in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search#feedback)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Exnav29 Thanks for the heads up. The screenshot and reference in the topic have been updated.
