### ISSUE TITLE
Please document RBAC permissions required to manage alerts

### ISSUE THREAD

**Issue by stukey** [MicrosoftDocs/microsoft-365-docs#5660]
Please update the "Managing Alerts" section to document which RBAC permissions are required to manage alerts, e.g. to assign a status to an alert or mark alerts as resolved. The documentation covers the RBAC permissions required to view alerts but it doesn't document the permissions required to manage alerts.

**Comment by yogkumgit** [comment]
@stukey Please indicate which document you are referring to. Thanks

**Comment by stukey** [comment]
Sorry, I thought that when I clicked "submit and view feedback for this page" button on the doc, it would have automatically included which document I was referring to. The document is "[Alert policies in the Microsoft 365 compliance center](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide)". Specifically the "Managing Alerts" section of the doc. Thanks.

**Comment by markjjo** [comment]
@stukey Thanks for feedback. The topic does state the permissions to create and update alert policies (Manage alerts) in this section: https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide#alert-policy-settings

But I will add it to section on managing alerts. By the way, the same role.

**Comment by stukey** [comment]
Thanks @markjjo. Just to clarify... my report was about documenting the permissions that are required in order to take action against a generated alert in the security & compliance portal (e.g. mark the alert as resolved) - it was not about managing the alert policies themselves. It doesn't seem to be documented anywhere what RBAC permissions are required for a user to be able to update/close alerts. Thanks!

**Comment by markjjo** [comment]
@stukey Sorry, I should have read your question closer as you were specific about managing alerts. The [section on the RBAC permissions required to view alerts](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies#rbac-permissions-required-to-view-alerts) and access the Alerts page in the compliance center touches on this: "This design (based on RBAC permissions) lets you determine which alerts can be viewed (and managed) by users in specific job roles in your organization." So, RBAC permissions control which alerts a user can see on the Alerts page. If a user can see/access an alert, I assume that they can manage it. FWIW, I can't find a corresponding PowerShell cmdlet (like there is for managing alert policies) for managing alerts, so this is done some other way in code. 

I can try to make this a bit about RBAC roles more clear in the section on managing alerts.
