### ISSUE TITLE
Confusing information

### ISSUE THREAD

**Issue by andy-guillen** [MicrosoftDocs/microsoft-365-docs#5661]
Hello!

In the document is stated the below under section "URL syntax for the Tenant Allow/Block List":

"All subpaths are not implied by a right wildcard.
For example, contoso.com/* does not include contoso.com/a."  

I assume the dot after the "a" is because the sentence ended, correct?

Later in the article is stated the below under section "URL entry scenarios, Scenario: Right wildcard suffix":

"Entry: contoso.com/*
    Allow match and Block match:
        contoso.com/a"

So, my question is, does contoso.com/* include contoso.com/a or not?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andy-guillen, I tried to account for that by using codeInline formatting (shaded gray) to indicate the values. Anything that's not shaded gray is not part of the value:

![image](https://user-images.githubusercontent.com/33166947/126243266-278b3dda-0673-476a-a086-c7730893f2f7.png)

![image](https://user-images.githubusercontent.com/33166947/126243359-827f65e9-32b2-4abd-ab2f-22badd084a4a.png)

Does that help?

**Comment by andy-guillen** [comment]
Hi Chris. Thank you very much for your response. Then the information is confusing because it states

[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33166947%2F126243266-278b3dda-0673-476a-a086-c7730893f2f7.png&data=04%7C01%7Candy%40miami.edu%7C2f04cbe63914478cb97108d94b13bdec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637623370450490782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zc8TEiO%2Fr1usgvokiEBLwRzcg9vPxDWNqcXxIsYlm14%3D&reserved=0>
And then it's stated that Allow match and Block match contoso.com/a
Please let me know if I am missing something here. Thank you!


From: Chris Davis ***@***.***>
Sent: Monday, July 19, 2021 8:17 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Guillen, Andy ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/microsoft-365-docs] Confusing information (#5661)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.


@andy-guillen<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandy-guillen&data=04%7C01%7Candy%40miami.edu%7C2f04cbe63914478cb97108d94b13bdec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637623370450490782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=J8e2qHoFgLGO2Aq%2BJ%2B5p6ewDsxQdCcgMC4TJ%2Fm4dP7Y%3D&reserved=0>, I tried to account for that by using codeInline formatting (shaded gray) to indicate the values. Anything that's not shaded gray is not part of the value:

[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33166947%2F126243266-278b3dda-0673-476a-a086-c7730893f2f7.png&data=04%7C01%7Candy%40miami.edu%7C2f04cbe63914478cb97108d94b13bdec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637623370450490782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zc8TEiO%2Fr1usgvokiEBLwRzcg9vPxDWNqcXxIsYlm14%3D&reserved=0>

[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33166947%2F126243359-827f65e9-32b2-4abd-ab2f-22badd084a4a.png&data=04%7C01%7Candy%40miami.edu%7C2f04cbe63914478cb97108d94b13bdec%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637623370450500775%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l3N8C2eIIhEHIrXPtdlmjqVZZL8P0e2Cu6NPmpExkro%3D&reserved=0>

Does that help?

-

**Comment by chrisda** [comment]
@andy-guillen, OK, I see now. I removed that statement (the first one) because it clearly conflicts with the second statement with multiple examples.

Thanks for the feedback.

Closing
