### ISSUE TITLE
Typo in link ...

### ISSUE THREAD

**Issue by shungite** [MicrosoftDocs/microsoft-365-docs#5662]
[Enter feedback here]

There is a typo in this link ...

[Screen.pdf](https://github.com/MicrosoftDocs/microsoft-365-docs/files/6842756/Screen.pdf)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1feb89e6-c5e0-693e-425e-8fd8b0198001
* Version Independent ID: 7b683879-67a9-299a-73e9-6e3654846fdf
* Content: [Set up file storage and sharing - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/set-up-file-storage-and-sharing?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/set-up-file-storage-and-sharing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/set-up-file-storage-and-sharing.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@shungite Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5674

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @shungite Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
