### ISSUE TITLE
Service Domain docs are inadequate

### ISSUE THREAD

**Issue by Eric-Hacker** [MicrosoftDocs/microsoft-365-docs#5663]
The brief section on Service Domains does not include any information on how the domains should be formatted or what is necessary to match a particular domain. There is not even an example. Based on a prior comment asking for more info, it was noted that wildcards are not supported and that has been added to the page, but there is still no other information.

For instance, if I need to block file uploads to LinkedIn, do I enter linkedin.com? www.linkedin.com? Obviously, not *.linkedin.com (though there is no checking in the UI, so don't forget to hover over the info button if you want to know anything at all). 

This finally seems to work with www.linkedin.com. The lack of any ability to troubleshoot logs made this an extremely frustrating exercise in guessing. Note that Service Domain pattern match wasn't the only issue, just the last one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76da4eda-4ccf-ff34-6a48-d9c5553c2ed6
* Version Independent ID: 7e887aff-1b85-1651-2bff-63425c54ae63
* Content: [Using  Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-using?view=o365-worldwide#dlp-settings)
* Content Source: [microsoft-365/compliance/endpoint-dlp-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-using.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
Thanks for this, I'll approach the PG for examples

**Comment by chrfox** [comment]
content updated
