### ISSUE TITLE
Syntax errors in cron jobs

### ISSUE THREAD

**Issue by guarismo** [MicrosoftDocs/microsoft-365-docs#5664]
All crontab entries are wrong and won't work in any of the Linux flavours described
Please correct to:

#!RHEL and variants (CentOS and Oracle Linux)

0 6 * * sun [ $(date +\%d) -le 15 ] && sudo yum update mdatp >> ~/mdatp_cron_job.log

#!SLES and variants

0 6 * * sun [ $(date +\%d) -le 15 ] && sudo zypper update mdatp >> ~/mdatp_cron_job.log

#!Ubuntu and Debian systems

0 6 * * sun [ $(date +\%d) -le 15 ] && sudo apt-get install --only-upgrade mdatp >> ~/mdatp_cron_job.log

Please NOTE the spaces between the schedule parts (0 6 * * sun), and space after opening square bracket '[' and before closing the square bracket ']' of the condition statement.
Also, the need for double ampersand '&&' to execute the command following if the statement inside the bracket is true.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19248657-fdd4-e6d5-f61e-828181b38817
* Version Independent ID: 2244848d-24df-ce71-4e36-89cf067eedd5
* Content: [How to schedule an update of the Microsoft Defender for Endpoint (Linux)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-update-mde-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-update-MDE-Linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-update-MDE-Linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@guarismo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5675

Once the author approves the PR you will see the changes live in the document.

Thanks
Sri
