### ISSUE TITLE
Need to include scripts for Enabling and Disabling Guest Access as well

### ISSUE THREAD

**Issue by ClintSwiney** [MicrosoftDocs/microsoft-365-docs#5667]
After using the script to disable all groups for Teams there needs to be a way to toggle the setting $true or $false. 

I worked with MS to develop the following 2 helper scripts that perform this function:

Enable-TeamsGuestAccess:

```
<#
Enable Guest access for a specific team
#>
$groupname = Read-Host -Prompt "Enter Group Display Name to Enable Guest Access"

#Enable Guest Access
    $template = Get-AzureADDirectorySettingTemplate | ? {$_.displayname -eq "group.unified.guest"}
    $settingsCopy = $template.CreateDirectorySetting()
    $settingsCopy["AllowToAddGuests"]=$True
    $groupID= (Get-AzureADGroup -SearchString $GroupName).ObjectId
    $id = (get-AzureADObjectSetting -TargetType groups -TargetObjectId $groupID).id
    Set-AzureADObjectSetting -TargetType Groups -TargetObjectId $groupID -DirectorySetting $settingsCopy -id $id
```

Disable-TeamsGuestAccess:

```
<#
Disable Guest access for a specific team
#>
$groupname = Read-Host -Prompt "Enter Group Display Name to Disable Guest Access"

#Disable Guest Access
    $template = Get-AzureADDirectorySettingTemplate | ? {$_.displayname -eq "group.unified.guest"}
    $settingsCopy = $template.CreateDirectorySetting()
    $settingsCopy["AllowToAddGuests"]=$False
    $groupID= (Get-AzureADGroup -SearchString $GroupName).ObjectId
    $id = (get-AzureADObjectSetting -TargetType groups -TargetObjectId $groupID).id
    Set-AzureADObjectSetting -TargetType Groups -TargetObjectId $groupID -DirectorySetting $settingsCopy -id $id

```
IMHO this should be integrated into the documentation for this process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e00be85-c1bd-bfd9-e09b-78fea811f864
* Version Independent ID: bdfb2aad-6aa8-76a8-46cf-1603f8255df4
* Content: [Prevent guests from being added to a specific group](https://docs.microsoft.com/en-us/microsoft-365/solutions/per-group-guest-access?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/per-group-guest-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/per-group-guest-access.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@ClintSwiney Thank you for your feedback. While this document only pertains to blocking guest access, I'm sure users who read this would also want to know how to toggle back to allow guest access. So, I have added the script to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5713

Once the author approves the PR, the document will be live.

Thanks again for taking time to provide feedback.

Thanks
Sri
