### ISSUE TITLE
Legacy deprecated Per-User MFA clarification required

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/microsoft-365-docs#5671]
Hi there,

Your documentation does not explain per-user MFA deprecation, or why it is referenced as Legacy MFA on some articles and not others.  There is no consistent message and this makes it difficult to explain to our customers that Conditional MFA is the preferred method when your articles don't clearly explain why.

These two issues mention that Per-user MFA (also commonly referred to as Microsoft MFA, Office 365 MFA and legacy MFA) is deprecated and should not be used.  The product group advice is not to use this feature and it is going away.

I think this also needs to be backed with some roadmap information, and it must be included in the document.

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2098
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/2064

Issue 2064 references changes to the document to make it clearer as to why you should not use Legacy MFA, but it has not made it clearer, it has clouded the message.  Even @Sirkkuw commented on the update to say that it was unclear what was being said, but it made it into a published state anyway.
Refer here: https://github.com/MicrosoftDocs/microsoft-365-docs/pull/2216#issuecomment-651934479

This article doesn't even mention that per-user MFA is not recommended, or deprecated.
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-userstates

This article considers the "service settings" page of legacy MFA as a legacy portal:
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-mfasettings#mfa-service-settings

So I think this article needs 3 things:

- Clarity about deprecation of the Per-user MFA and when/why it is "going away"
- Reference to a roadmap for Per-user MFA.
- Explanation on why it differs from Conditional Access MFA and is not recommended.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multifactor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
@efrene - thank you for helping resolve this issue.

**Comment by efrene** [comment]
@anthonynz Thanks so much for your comments and detailed information. I am taking ownership of this content area from Sirkku, and will follow up on updating the article as soon as I am able to. Sorry for the inconvenience.

**Comment by yogkumgit** [comment]
@efrene Please update. Thanks

**Comment by dataCollegechurch** [comment]
@efrene - any updates here. I think @anthonynz is spot on with his insights. I think there is a renewed urgency to update this documentation with rollout of the [Authentication methods policy](https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-methods-manage) underway. It is unclear to me how Legacy Per User MFA will interact with the Authentication methods policies.

**Comment by efrene** [comment]
I'll look into updating the article next week, noting the comments from anthonynz.  Sorry for the delay.

**Comment by tiburd** [comment]
Article is updated.
