### ISSUE TITLE
How do we get access to this? 

### ISSUE THREAD

**Issue by JDFlannery** [MicrosoftDocs/microsoft-365-docs#5679]
I appreciate that this is in preview and isn't available in tenants everywhere but is there an option to opt in to it? We started a Phish security test and I'd love to use the Advanced option to not have to filter out the incidents\alarms this is producing. 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17ce75e-79ba-0acd-066c-a0120a29d65d
* Version Independent ID: 14673b1c-8489-0abc-90a0-42f35d516424
* Content: [Configure the delivery of third-party phishing simulations to users and unfiltered messages to SecOps mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-advanced-delivery?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-advanced-delivery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-advanced-delivery.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JDFlannery, I have no real insight into the process, but it is truly a case of "don't call us, we'll call you". Microsoft will approach the tenants that they want to be part of the preview based on some specific criteria (size, industry, use of specific features, previous support cases, etc.).

**Comment by chrisda** [comment]
@JDFlannery, this is live and available for everyone as of Wednesday July 28.

[Feature ID 72207](https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=72207)

Thanks for the feedback.

Closing
