### ISSUE TITLE
Please explain the "selected" option, not just the "All" option

### ISSUE THREAD

**Issue by pmckinstryholyfamilycs** [MicrosoftDocs/microsoft-365-docs#5683]
The Docs say to select "All" when enabling Self Serve Password Reset". Please describe the other option "Selected". If I specify a group, can that group have groups as members, or does this only apply to direct members of the specified group as in some other areas of Microsoft's products?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad408574-36cc-9b96-f092-58a68708d3a0
* Version Independent ID: 97adbc3d-8f71-a6de-25c3-f9400125f885
* Content: [Let users reset their own passwords - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/let-users-reset-passwords?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/let-users-reset-passwords.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/let-users-reset-passwords.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by Leicham** [comment]
"Selected" means you can set up SSPR for members of particular Azure AD groups.  You are able to nest the groups, so if you have a main group with a sub-group beneath it, the policy applied to the main group will apply to those in the sub-group as well.

**Comment by msbemba** [comment]
@pmckinstryholyfamilycs Thank you for your feedback. Since this document talks about turning on SSPR for everyone in your business, it does not have details about Selected.

The Selected option can be used to add groups which will enable the option to all members within the group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @pmckinstryholyfamilycs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
