### ISSUE TITLE
Typos in Page

### ISSUE THREAD

**Issue by theokou** [MicrosoftDocs/microsoft-365-docs#5684]
A:
Note

Activity alerts are being deprecated. We recommend that you start using alert policies in the security and compliance center instead of creating new activity alerts. Alert policies provide addition functionality such as the ability to create an alert policy that triggers an alert when any user performs a specified activity, and displaying alerts on the View alerts page in the security and compliance center. For more information, see Alert policies.

Should be:

 Note

Activity alerts are being deprecated. We recommend that you start using alert policies in the security and compliance center instead of creating new activity alerts. Alert policies provide additional functionality, such as the ability to create an alert policy that triggers an alert when any user performs a specified activity and displaying alerts on the View alerts page in the security and compliance center. For more information, see Alert policies.

B:
 Tip

You might want to create an activity alert for just one activity that's performed by any user. Or you might want to create an activity alert that track multiple activities performed by one or mores users.

Should be:

 Tip

You might want to create an activity alert for just one activity that's performed by any user. Or you might want to create an activity alert that track multiple activities performed by one or more users.

**Comment by denisebmsft** [comment]
Hello @theokou! Can you please tell us to which article(s) your feedback applies? I suspect it's in our compliance content, but to be sure, and to route it to the correct writer, it would help to know which article we need to address. Thanks!

**Comment by theokou** [comment]
> Hello @theokou! Can you please tell us to which article(s) your feedback applies? I suspect it's in our compliance content, but to be sure, and to route it to the correct writer, it would help to know which article we need to address. Thanks!

Hi Denise, 

I am referring to article "Create activity alerts",  https://docs.microsoft.com/en-us/microsoft-365/compliance/create-activity-alerts?view=o365-worldwide

**Comment by markjjo** [comment]
@leicham Thanks for submitting PR with fixes for these issues. I merged that PR.
