### ISSUE TITLE
Microsoft IPv6 ranges missing from spf.protection.outlook.com

### ISSUE THREAD

**Issue by BondiChris** [MicrosoftDocs/microsoft-365-docs#5695]
I am getting compliance issues for messages originating from SYCPR01CA0029.ausprd01.prod.outlook.com (2603:10c6:10:e::17).

None of the 2603:10c6:10::/48 range is included.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce215c7-f61f-44c5-43c1-2fa1f2a39220
* Version Independent ID: d65a9513-432a-d0fe-1431-da5ad2e631eb
* Content: [External Domain Name System records for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-au/microsoft-365/enterprise/external-domain-name-system-records?redirectSourcePath=%252farticle%252fExternal-Domain-Name-System-records-for-Office-365-c0531a6f-9e25-4f2d-ad0e-a70bfef09ac0&view=o365-worldwide#BKMK_SPFrecords)
* Content Source: [microsoft-365/enterprise/external-domain-name-system-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/external-domain-name-system-records.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by BondiChris** [comment]
I also noticed that the microsoft.com SPF seems to be a mess. The original message purported to have been sent by <quarantine@messaging.microsoft.com> to my O365 mailbox.

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by BondiChris** [comment]
> I also noticed that the microsoft.com SPF seems to be a mess. The original message purported to have been sent by [quarantine@messaging.microsoft.com](mailto:quarantine@messaging.microsoft.com) to my O365 mailbox.

**microsoft.com**: "v=spf1 include:_spf-a.microsoft.com include:_spf-b.microsoft.com include:_spf-c.microsoft.com include:_spf-ssg-a.microsoft.com include:spf-a.hotmail.com include:_spf1-meo.microsoft.com -all"

**_spf-a.microsoft.com**: "v=spf1 ip4:216.99.5.67 ip4:216.99.5.68 ip4:202.177.148.100 ip4:203.122.32.250 ip4:202.177.148.110 ip4:213.199.128.139 ip4:213.199.128.145 ip4:207.46.50.72 ip4:207.46.50.82 ip4:65.55.42.224/28 ip4:13.78.233.182 include:spf.protection.outlook.com ~all"

**_spf-b.microsoft.com**: "v=spf1 include:_spf-mdm.microsoft.com ip4:207.46.22.35 ip4:207.46.22.98/29 ip4:217.77.141.52 ip4:217.77.141.59 ip4:203.32.4.25 ip4:131.107.0.0/16 ip4:23.103.224.0/19 ip4:206.191.224.0/19 ip4:65.52.80.137/32 ip4:51.140.75.55 ip4:13.70.32.43 ~all"

**_spf-c.microsoft.com**: "v=spf1 ip4:213.199.138.181 ip4:213.199.138.191 ip4:207.46.52.71 ip4:207.46.52.79 ip4:86.61.88.25 ip4:167.220.67.232/29 ip4:157.58.196.96/29 ip4:147.243.128.24 ip4:147.243.128.26 ip4:147.243.1.153 ip4:147.243.1.47 ip4:147.243.1.48 ip4:52.250.126.174 ~all"

**_spf-ssg-a.microsoft.com**: "v=spf1 include:_spf-ssg-a.msft.net ip4:111.221.26.0/27 ip4:207.46.200.0/27 ip4:207.46.50.192/26 ip4:65.55.234.192/26 ip4:65.55.52.224/27 ip4:94.245.112.0/27 ip4:167.220.67.238 ip4:51.4.71.62 ip4:23.103.131.7 ip4:131.253.121.20 ip4:131.253.121.52 ~all"

**spf-a.hotmail.com**: "v=spf1 ip4:157.55.0.192/26 ip4:157.55.1.128/26 ip4:157.55.2.0/25 ip4:65.54.190.0/24 ip4:65.54.51.64/26 ip4:65.54.61.64/26 ip4:65.55.111.0/24 ip4:65.55.116.0/25 ip4:65.55.34.0/24 ip4:65.55.90.0/24 ip4:65.54.241.0/24 ip4:207.46.117.0/24 ~all"

**_spf1-meo.microsoft.com**: "v=spf1 ip4:52.165.175.144 ip4:52.247.53.144 ip4:157.55.254.216 ip4:13.74.143.28 ip4:104.214.25.77 ip4:207.46.225.107 ip4:51.137.58.21 ip4:138.91.172.26 ip4:52.250.107.196 ip4:13.92.31.129 ip4:40.77.102.222 ip4:51.144.100.179 ip4:52.160.39.140 ip4:52.244." "206.214 ip4:13.72.50.45 ~all"

**_spf-mdm.microsoft.com**: "v=spf1 ip4:134.170.113.0/26 ip4:131.253.30.0/24 ip4:157.56.120.128/26 ip4:134.170.174.0/24 ip4:134.170.141.64/26 ip4:134.170.143.0/24 ip4:157.58.249.3 ip4:65.55.29.77 ip4:131.253.121.0/26 -all"

That's a lot of addresses authorised to send microsoft.com emails - with one whole /16 block, a number of /24 blocks and some smaller ranged included:

13.70.32.43, 13.72.50.45, 13.74.143.28, 13.78.233.182, 13.92.31.129, 23.103.131.7, 23.103.224.0/19, 40.77.102.222, 51.4.71.62,
51.137.58.21, 51.140.75.55, 51.144.100.179, 52.160.39.140, 52.165.175.144, 52.244.206.214, 52.247.53.144, 52.250.107.196,
52.250.126.174, 65.52.80.137/32, 65.54.51.64/26, 65.54.61.64/26, 65.54.190.0/24, 65.54.241.0/24, 65.55.29.77, 65.55.34.0/24,
65.55.42.224/28, 65.55.52.224/27, 65.55.90.0/24, 65.55.111.0/24, 65.55.116.0/25, 65.55.234.192/26, 86.61.88.25, 94.245.112.0/27,
104.214.25.77, 111.221.26.0/27, **131.107.0.0/16**, 131.253.30.0/24, 131.253.121.0/26, 131.253.121.20, 131.253.121.52,
134.170.113.0/26, 134.170.141.64/26, 134.170.143.0/24, 134.170.174.0/24, 138.91.172.26, 147.243.1.153, 147.243.1.47,
147.243.1.48, 147.243.128.24, 147.243.128.26, 157.55.0.192/26, 157.55.1.128/26, 157.55.2.0/25, 157.55.254.216, 157.56.120.128/26,
157.58.196.96/29, 157.58.249.3, 167.220.67.232/29, 167.220.67.238, 202.177.148.100, 202.177.148.110, 203.32.4.25,
203.122.32.250, 206.191.224.0/19, 207.46.22.35, 207.46.22.98/29, 207.46.50.192/26, 207.46.50.72, 207.46.50.82, 207.46.52.71,
207.46.52.79, 207.46.117.0/24, 207.46.200.0/27, 207.46.225.107, 213.199.128.139, 213.199.128.145, 213.199.138.181,
213.199.138.191, 216.99.5.67, 216.99.5.68, 217.77.141.52, 217.77.141.59

**Comment by BondiChris** [comment]
Any response on this issue? I am still getting messages from Office365 domains that fail SPF origin checks.

**Comment by vedranmiletic** [comment]
> Any response on this issue? I am still getting messages from Office365 domains that fail SPF origin checks.

+1

**Comment by LauraWi** [comment]
@kelleyvice-msft Can you investigate? Thanks!

**Comment by grimaldispizzeria** [comment]
I have opened a support ticket to try to get this resolved and it's a miserable process. Hoping this route will actually get to somebody competent enough to understand the issue.

2603:10b6:a03:::  is another range that is not included in the SPF record but MS is still sending from addresses in that range.

2603:10b6:a02:c3::15
2603:10b6:a03:2d8::16

are two examples.

Here's [a thread](https://techcommunity.microsoft.com/t5/exchange/exchange-online-protection-spf-record/m-p/1358371) where people are the same issues; first the problem of MS' own SPF record being incomplete, but second the problem of abysmal support who do not comprehend this simple issue.

It would be nice if this could be fixed by not just fixing the problem but the process as well.

**Comment by grimaldispizzeria** [comment]
> @kelleyvice-msft Can you investigate? Thanks!

Please @kelleyvice-msft if you could also let someone in support know that they have an absolute terrible response to this problem, see case 29043035 for an example. 

Multiple rounds of back and forth where I'm being asked for extensive details that are not required to fix a problem that is on MS' side. Assurances of being understood followed by demonstrations to the contrary. 

I recognize this isn't a support channel but it's one company so maybe you could escalate this to whomever is responsible for not letting errant processes create terrible support feedback loops.

**Comment by jacobcalvert** [comment]
Looks like 2a01:111:f400:7e8b::/64 is also missing, started getting issues two days ago with various addresses in this range. Very frustrating to pay for a service and only to have your mail get marked spam or blackholed....

**Comment by kelleyvice-msft** [comment]
My apologies for the delayed response. I will read through all this and figure out how to escalate appropriately, and reply back to this issue.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.

**Comment by BondiChris** [comment]
Hi Kelley,

The original issue is not resolved. I reported missing SPF coverage for an email from quarantine@messaging.microsoft.com(mailto:quarantine@messaging.microsoft.com) that originated from IPv6 address 2603:10c6:10:e::17 - it's not a Microsoft 365 Enterprise customer issue, it's a Microsoft corporate problem.

You may want to check out the report from this service: 

[https://www.spf-record.com/spf-lookup/messaging.microsoft.com?ip=2603:10c6:10:e::17](https://www.spf-record.com/spf-lookup/messaging.microsoft.com?ip=2603:10c6:10:e::17)

I know that Microsoft is a large corporation, but other large companies are able to get this stuff to work.
