### ISSUE TITLE
Can I configure Cortana to schedule meetings that start on the :05 and :10?

### ISSUE THREAD

**Issue by BarryBo** [MicrosoftDocs/microsoft-365-docs#5696]
My org has standardized on 30 minute meetings starting on the :05, and longer ones on the :10.  Outlook now supports this, and it's great.  Does Cortana?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f868289-23b3-1f57-c698-6e90c71d3a1a
* Version Independent ID: 3fb0cb3a-714c-351c-58dd-acbed8371636
* Content: [Using Scheduler for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/scheduler/scheduler-using?view=o365-21vianet)
* Content Source: [microsoft-365/scheduler/scheduler-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/scheduler/scheduler-using.md)
* Service: **scheduler**
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by msbemba** [comment]
@BarryBo Thank you for your feedback. Nope, Cortona does not do that automatically now, Unless you specify the timing stating scheduled a 30-minute meeting start at 9:05 AM. Having said that, Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @BarryBo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
