### ISSUE TITLE
Software Inventory missing certain software like QGIS

### ISSUE THREAD

**Issue by adonm** [MicrosoftDocs/microsoft-365-docs#5697]
We noted that the DeviceTvmSoftwareInventory in advanced hunting doesn't appear to capture all the software listed on the device > software inventory page (such as QGIS below):

![image](https://user-images.githubusercontent.com/121014/126448895-18694c3f-0058-49ba-8e16-3f3d7f043264.png)

Is there another inventory table or equivalent with Advanced Hunting that includes that information / full software list? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2032527f-e290-1e2e-31db-db0472f10c36
* Version Independent ID: e371dfad-cb29-4078-b632-46b39296b29e
* Content: [Software inventory in threat and vulnerability management](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-software-inventory?view=o365-worldwide#funktionsweisehow-it-works)
* Content Source: [microsoft-365/security/defender-endpoint/tvm-software-inventory.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tvm-software-inventory.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
Topic has moved to <https://docs.microsoft.com/microsoft-365/security/defender-vulnerability-management/tvm-software-inventory>.

**Comment by yogkumgit** [comment]
@adonm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
