### ISSUE TITLE
No work 2FA

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/microsoft-365-docs#5698]

**Comment by yogkumgit** [comment]
@matuhinal Please indicate which document you are referring to. Thanks

**Comment by msbemba** [comment]
@matuhinal Thank you for your feedback. Are you referring to this page - https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-userstates? 

If yes, could you please tell us what happens when you enable 2fa?

Thanks
Sri

**Comment by matuhinal** [comment]
Yes, there is a security issue. The request is open in M 365, but has not been resolved yet

**Comment by matuhinal** [comment]
2FA problem with work account Can't change phone number to another

**Comment by msbemba** [comment]
@matuhinal Thank you for the quick response. Since you have a support ticket open with the M365 support team, I'd let you continue working with them. This channel is specifically created for updates in documentation(Microsoft docs).

Hope this helps!

Thanks
Sri

**Comment by matuhinal** [comment]
Здравствуйте Не помогает)

**Comment by msbemba** [comment]
@matuhinal Thank you for the response. The issue needs to be addressed by the support team and we do not troubleshoot technical issues in the forum. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). 

@yogkumgit There are no changes in this document. Please close the issue.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @matuhinal Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
