### ISSUE TITLE
Enabled and disabled pictures are the same. 

### ISSUE THREAD

**Issue by Andywareaus** [MicrosoftDocs/microsoft-365-docs#5699]
Enabled and disabled pictures are the same.   Disabling the defender interface should change what icons appear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9870c42b-eede-b869-3d4d-cd2c53be82ed
* Version Independent ID: 8ae67d57-bb69-1e7c-92df-2960e2a2f152
* Content: [Hide the Microsoft Defender Antivirus interface](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-end-user-interaction-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-end-user-interaction-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-end-user-interaction-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@Andywareaus Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5864

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Andywareaus Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
