### ISSUE TITLE
O365 Storage Add'on no longer visibile in my portal

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/microsoft-365-docs#5700]
I have a test tenant, no CSP or Volume licensing involved and I used to see this license type in Billing.
now it's absent and i was wondering if something may have changed with it.

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add storage space for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@teomonda Thank you for your feedback. What are the other licenses that exist in your tenant? Note that  If you don't see the Office 365 Extra File Storage in the list of available add-ons, it means your plan is not eligible.

Thanks
Sri

**Comment by teomonda** [comment]
Hello Sri, I do have eligible plans in my tenant, it is very difficult not to I would say, considering the long list with plans that we have here: https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide#is-my-plan-eligible-for-office-365-extra-file-storage 
![image](https://user-images.githubusercontent.com/43137999/127290215-a9e13d24-310c-4989-ad04-02c03968bc45.png)

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @teomonda Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
