### ISSUE TITLE
Broken links in the MDE Section

### ISSUE THREAD

**Issue by MathiasAaron** [MicrosoftDocs/microsoft-365-docs#5701]
[Enter feedback here]
Seems to have a couple of broken links in the MDE Section.
Might help if the hyperlink for "supported Tools and methods" 
pointed to 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-configure?view=o365-worldwide#in-this-section
instead of 
https://docs.microsoft.com/en-us/defender-endpoint/onboard-configure

Also if "minimum requirements" which currently points to 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide
instead of 
https://docs.microsoft.com/en-us/defender-endpoint/minimum-requirements

I didn't think I would have the rights to do it myself and even if I did, I woukld have wanted it moderated before publishing, hence me sending you guys this.

Cheers.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6823d882-abc4-dc8c-cec0-0cbbd9eb282f
* Version Independent ID: 19aa0df5-be26-4092-c548-e2bb4e95fe02
* Content: [Promote your Microsoft 365 Defender evaluation environment to Production, Microsoft 365 Defender evaluation, try an evaluation, keep an evaluation, production evaluation](https://docs.microsoft.com/en-us/microsoft-365/security/defender/eval-defender-promote-to-production?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/eval-defender-promote-to-production.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/eval-defender-promote-to-production.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@MathiasAaron Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5720

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MathiasAaron Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
