### ISSUE TITLE
The API documentation has no description on the idempotency for "stop and quarantine file"

### ISSUE THREAD

**Issue by wuqiany2** [MicrosoftDocs/microsoft-365-docs#5702]
Hi, 

Could you add a section that describes the idempotency of the API? E.g. what happens when the same request was posted multiple times in a short time range, while the first machine action is still pending.

My experience so far is that the API will return HTTP 400 code when the same request gets submitted multiple times while the first machine action is still pending, which makes little sense to me. What prevents returning the initial machine action ID that was created for subsequent requests?

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec8a077-8b23-eb52-fe12-3c24bae33bf6
* Version Independent ID: 999a81d7-e9e1-6851-c636-121ccf4e181c
* Content: [Stop and quarantine file API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/stop-and-quarantine-file?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/stop-and-quarantine-file.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/stop-and-quarantine-file.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
There is some engineering action required to address this. Not a simple doc fix.
