### ISSUE TITLE
Feedback Link Misdirects

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/microsoft-365-docs#5706]
The "Feedback for this product" link still points at the reference page for the Windows 10 Feedback Hub.  Bookings is not a Windows 10 product and there's no facility to provide Bookings feedback via the Windows 10 Feedback hub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 764ebef6-2c8d-54b1-42e7-8d79cd7dff3c
* Version Independent ID: 257d60e2-9313-e08b-dccf-120cb4b30f5b
* Content: [Microsoft Bookings Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-faq.yml)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@FC-EricWeller Thank you for your feedback. We are working internally to fix this. We shall update you once this is complete.

Thanks
Sri

**Comment by msbemba** [comment]
@FC-EricWeller Thank you for your feedback. We have fixed the feedback widget on the page. It will now route users to the O365 admin center feedback widget.

@kwekuako Thank you for your help.

@yogkumgit  This can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @FC-EricWeller Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
