### ISSUE TITLE
id and autodiscover question

### ISSUE THREAD

**Issue by arkayenro** [MicrosoftDocs/microsoft-365-docs#5708]
Hi,

in the description of the id field could you state if it will remain constant or not.  ie we include some of the sets based on id, so can we rely on id 74 always being the remote connectivity data set? or could microsoft change it at some point?

would it also be possible to update id 154 to include `"autodiscover.*.mail.onmicrosoft.com"`?
this set has `autodiscover.*.onmicrosoft.com` which works for cloud but for hybrid its going to hit `autodiscover.*.mail.onmicrosoft.com` instead - and yes, our proxy prompted for auth when it tried to do that essentially breaking outlook so it would be really nice if the `*.mail` variant could be added so we dont have to manually add it to the pac file.

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out, @arkayenro. You should expect that changes to Office 365 endpoints, both URLs and IP addresses, may take place as services are updated. To find out how to get notifications of updates, see https://docs.microsoft.com/microsoft-365/enterprise/managing-office-365-endpoints#change-management-for-office-365-ip-addresses-and-urls. 

With regards to autodiscover.*.mail.onmicrosoft.com, that URL is actually listed in both the GCCHigh and DoD web service instances. I have requested that the engineering team add the URL to the Worldwide instance as well, in which case it will appear in a future update.

Thanks,
Kelley
