### ISSUE TITLE
Outlook on iOS minimum supported version number

### ISSUE THREAD

**Issue by walidelmorsy** [MicrosoftDocs/microsoft-365-docs#5709]
Hi there,

in this article (https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#sensitivity-label-capabilities-in-outlook), for the "Dynamic markings with variables" under the Outlook on iOS version number , it says "4.7.1+", however just noticed that the latest version in the App Store for Outlook is 4.2128.0, wondering if the "4.7.1" is still valid and is the minimum supported version for this feature to work.

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Manage sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#sensitivity-label-capabilities-in-outlook)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @walidelmorsy!  4.7.1 is a very old build of the app (the support for dynamic markings was server-side, not client-side). For easier comparison, read 4.7.1+ (no leading zeros) as 4.0007.1+, (not 4.7000.1). The version you quoted of 4.2128.0 is obviously higher than 4.0007.1, so this latest version supports dynamic markings.

**Comment by cabailey** [comment]
@walidelmorsy - can we close this now?

**Comment by yogkumgit** [comment]
@cabailey Thank you very much for sharing this explanation. @walidelmorsy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by walidelmorsy** [comment]
Thanks very much @cabailey! I think this makes much more sense, the only suggestion I would have is to specify the (0007) bit in the article itself, otherwise we will have more questions about it moving forward :), just my 2 cents :). Thanks once again!

**Comment by cabailey** [comment]
@walidelmorsy Yes, we're monitoring this and so far, only got a couple of inquiries.  We considered updating all references of 4.7.1 to 4.0007.1 but this has other repercussions, and the app wasn't released as 4.0007.1.  If you still had that version installed it would show 4.7.1 (common to drop leading zeros for software versions)  It's such an old version, I'm not even sure Apple would support it any more so what we might do, is increase our minimum supported version that would then make it easier to compare with current versions.  I think this is a problem bigger than this one instance and I'll discuss with the relevant people before making any changes to the docs.
