### ISSUE TITLE
removing licenses from migrated mailboxes

### ISSUE THREAD

**Issue by daliokas7** [MicrosoftDocs/microsoft-365-docs#5712]
After removing license from migrated source tennant user mailbox(which no longer a mailbox, but a Mail user pointer), Mail user pointer with external address is deleted. How to correctly remove licence from migrated user? There ir no reason to use license for a pointer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@daliokas7 Thank you for your feedback. We have added this to the Known issues section

MailUser objects are pointers to non-local mailboxes. In the case of cross-tenant mailbox migrations, we use MailUser objects to represent either the source mailbox (from the target organization’s perspective) or the target mailbox (from the source organization’s perspective). The main users will have an ExternalEmailAddress (targetAddress) that points to the SMTP address of the actual mailbox (ProxyTest@fabrikam.onmicrosoft.com) and a primary SMTP address that represents the displayed SMTP address of the mailbox user in the directory. If you wish to persist these external domains on MailUser, either before the migration or after migration, you need to alter your migration processes to strip licenses after the move completes or before the move to ensure that the users have the expected external branding applied.

An example script to remove the service plans on a MailUser in the Contoso.onmicrosoft.com tenant is shown here.

$LO = New-MsolLicenseOptions -AccountSkuId "contoso:ENTERPRISEPREMIUM" DisabledPlans
"LOCKBOX_ENTERPRISE","EXCHANGE_S_ENTERPRISE","INFORMATION_BARRIERS","MIP_S_CLP2","
MIP_S_CLP1","MYANALYTICS_P2","EXCHANGE_ANALYTICS","EQUIVIO_ANALYTICS","THREAT_INTE
LLIGENCE","PAM_ENTERPRISE","PREMIUM_ENCRYPTION"
Set-MsolUserLicense -UserPrincipalName proxytest@contoso.com LicenseOptions $lo


CC: @JoeDavies-MSFT 

Hope this answers your question

Thanks
Sri

**Comment by daliokas7** [comment]
@msbemba thank you for an answer.

I did not tried removing license from powershell, however, after removing license from Source tennant Admin Center, Mailuser(pointer) with External Address disappeared together with ability to receive emails(i.e. emails sent to Source user returned error 'user not found'). After license removal from a Source user I couldn't create pointer again and therefore deleted source user altogether. Only after removal source user from Deleted Users I was able to recreate pointer on Source Tennant with external address.
Aforementioned Mailuser do appear in Contacts section at old Exchange Admin Center after migration. And it disappears after license removal from Source tennant migrated user.
Therefore I altered source script in order to export group names to which Source user belongs and created post-migration script to delete Source user, recreate it with all aliases and external addresses and assign groups.
This wrangling creates a few minutes gap when Source User is unable to receive emails. 

I think there should be a more elegant solution to remove license from Source user without all problems I just mentioned.

**Comment by msbemba** [comment]
@daliokas7 Thank you for your feedback. When you use the PS script, I have noticed that the mail user's PrimarySMTPAddress(External address) is no longer scrubbed. The Target domain is not owned by the Source tenant and will persist as the primary SMTP address shown in the directory.

If the proxy addresses continue to get scrubbed, I would recommend you contact Microsoft support via the need help link on the admin center to verify and troubleshoot the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @daliokas7 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it as here, we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
