### ISSUE TITLE
DMARC and DKIM records are missing

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#5714]
This article should mention DKIM and DMARC records. 

i.e.
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide#what-is-a-dmarc-txt-record

i.e.
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide#step-4-form-the-dmarc-txt-record-for-your-domain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce215c7-f61f-44c5-43c1-2fa1f2a39220
* Version Independent ID: d65a9513-432a-d0fe-1431-da5ad2e631eb
* Content: [External Domain Name System records for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/external-domain-name-system-records?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/external-domain-name-system-records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/external-domain-name-system-records.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Mike-Crowley Thank you for your feedback. We have a note in the document which talks about DKIm and DMARC and references are in place to route users to the document pointed out.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Mike-Crowley Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
