### ISSUE TITLE
You are missing the step to enable the developer key for the Teams LTI Tool

### ISSUE THREAD

**Issue by buckett** [MicrosoftDocs/microsoft-365-docs#5715]
Before you can add the Teams LTI tool using the Client ID as an admin you need to go to the Developer Key listing in the main account, switch to the inherited keys, load all the keys and then enable the Teams one.

Otherwise when adding the App you get a message about the Client ID being disabled.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b696e622-361b-0be8-0b1f-b2ad9708c877
* Version Independent ID: 18403e7b-adb6-2828-54c6-ddd410eacadd
* Content: [Use Microsoft Teams classes with Canvas](https://docs.microsoft.com/en-gb/microsoft-365/lti/teams-classes-with-canvas?view=o365-worldwide)
* Content Source: [microsoft-365/lti/teams-classes-with-canvas.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lti/teams-classes-with-canvas.md)
* Service: **o365-administration**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by msbemba** [comment]
@buckett Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5765

Once the author approves the PR, document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @buckett Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
