### ISSUE TITLE
Customer Lockbox Approval Alerts

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#5717]
Certain regulatory bodies require events like Customer Lockbox to be alerted on, any time a request has been approved. However, alert policies for this event are not available in the Unified Audit Log.

I've set up alerts for this via MCAS, and wondered if it is worth adding a callout to creating Alert Policies for Customer Lockbox Requests somewhere on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?WT.mc_id=365AdminCSH_RAVE&view=o365-worldwide#auditing-customer-lockbox-requests)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by msbemba** [comment]
@SeanTGeoghegan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6206

Once the author approves, changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@KCCross PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SeanTGeoghegan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
