### ISSUE TITLE
Incorrect Example

### ISSUE THREAD

**Issue by Erick-Michael** [MicrosoftDocs/microsoft-365-docs#5722]
The code for the example "To check the blocked status of a user account use the following command:" does not work because -UserPrincipalName is not a working command for Get-AzureADUser.

Get-AzureADUser -UserPrincipalName <UPN of user account> | Select DisplayName,AccountEnabled

This code can be corrected by changing -UserPrincipalName to -ObjectID.

Thank you,
Erick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bc2eb03-4b03-99ff-3be0-d47e0a785948
* Version Independent ID: 7c0929d0-85d6-a3dc-cf91-15c4d90bd7a8
* Content: [Block Microsoft 365 user accounts with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/block-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/block-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/block-user-accounts-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@Erick-Michael Thank you for your feedback. We have made the changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5763

Once the author approves the PR, document will be live.

Thanks
Sri
