### ISSUE TITLE
 nonprofit Microsoft problem with domain email name,  subscription for Microsoft 365 small business premier

### ISSUE THREAD

**Issue by GRCAINC** [MicrosoftDocs/microsoft-365-docs#5724]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db386473-5b1f-7cee-c094-802bc5f491c5
* Version Independent ID: 50c3acf6-b285-3b3b-619a-163525a826f4
* Content: [Sign up for Microsoft 365 Business Premium subscription](https://docs.microsoft.com/en-us/microsoft-365/business-video/sign-up?redirectSourcePath=%252foffice%252f9ac1a0f1-789b-4143-b954-5821d5d89298&view=o365-worldwide)
* Content Source: [microsoft-365/business-video/sign-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/sign-up.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@GRCAINC Thank you for your feedback. This document pertains to details about signing up for the M365 business premium subscription. If you are looking for details about signing up for this service for non profit, please visit -https://www.microsoft.com/en-us/nonprofits/microsoft-365

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GRCAINC Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
