### ISSUE TITLE
W niczym nie pomaga

### ISSUE THREAD

**Issue by Vertigo12** [MicrosoftDocs/microsoft-365-docs#5726]
Kompletnie niezrozumiałe, dostępne tylko dla specjalistów. w ogóle nie rozwiązuje problemu.  Potrzebna jest jasna i czytelna instrukcja, jak włączyć dodatki.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/pl-pl/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Vertigo12 Thank you for your feedback. This document pertains only to determine if centralized deployment works for the user/admin. To know more about deploying add-ins, please visit -https://docs.microsoft.com/pl-pl/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Vertigo12 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
