### ISSUE TITLE
Document Update Request - Items moved across Non Indexed folder to Indexed folder does not get indexed.

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/microsoft-365-docs#5728]
Could we help to include following note in the documentation that when we move an item from a folder that is not part of Indexing, to a folder that is part of Indexing,
we do not reset certain flags and so the item may still remain unindexed and non searchable.
We confirmed this with engineering and is by design currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a813c062-e1c1-a3f3-a31d-30e7ff74d935
* Version Independent ID: 12b13db5-ebe5-4098-b3f6-953d4da0586f
* Content: [Partially indexed items in Content Search and other eDiscovery tools - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/partially-indexed-items-in-content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/partially-indexed-items-in-content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/partially-indexed-items-in-content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. Thanks

**Comment by qaehtesh** [comment]
Thank you Mark, I created the below PR Document Update Request - Items moved across Non Indexed folder to In... by qaehtesh * Pull Request #9859 * MicrosoftDocs/microsoft-365-docs-pr (github.com)<https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/9859>
