### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mamidu3** [MicrosoftDocs/microsoft-365-docs#573]
The link embedded within "Learn about ATP anti-phishing policy options" throws a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0ef695c-464d-43b3-2cc4-d9fe7f5aa261
* Version Independent ID: bb02b3da-6bd7-b81c-ffd8-3a3b8940dd2a
* Content: [Increase threat protection for Microsoft 365 Business](https://docs.microsoft.com/en-us/microsoft-365/business/increase-threat-protection#raise-the-level-of-protection-against-malware-in-mail)
* Content Source: [microsoft-365/business/increase-threat-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/increase-threat-protection.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by mypil** [comment]
@mamidu3  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@mamidu3 PR #579 has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
