### ISSUE TITLE
Add warning regarding PowerShell only works with 5.1 not 7

### ISSUE THREAD

**Issue by LordBoBCUP** [MicrosoftDocs/microsoft-365-docs#5730]
With regards to the section "Use the Azure Active Directory PowerShell for Graph module" please add a warning that is doesn't work with Powershell Version 7, it however does work ok with 5.1. Better yet work on fixing the errors when running version 7
`Set-AzureADUserLicense -ObjectId xxxx -AssignedLicenses $LicensesToAssign

Set-AzureADUserLicense: Cannot bind parameter 'AssignedLicenses'. Cannot convert value "class AssignedLicenses {
  AddLicenses: System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AssignedLicense]
  RemoveLicenses:
}
" to type "Microsoft.Open.AzureAD.Model.AssignedLicenses". Error: "Cannot convert the "class AssignedLicenses {
  AddLicenses: System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AssignedLicense]
  RemoveLicenses:
}
" value of type "Deserialized.Microsoft.Open.AzureAD.Model.AssignedLicenses" to type "Microsoft.Open.AzureAD.Model.AssignedLicenses"."`

I think this is what this issue that has been closed is in reference to: [Link](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4528)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073b885d-191e-8c00-fa59-ad83ba79ec10
* Version Independent ID: 4bd5799d-9baf-90b6-634d-398fbea6b66f
* Content: [Assign Microsoft 365 licenses to user accounts with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@LordBoBCUP Thank you for your feedback. We have added a note in the document which talks about this module not working in powershell core.

 "Note

PowerShell Core does not support the Microsoft Azure Active Directory Module for Windows PowerShell module and cmdlets with Msol in their name. To continue using these cmdlets, you must run them from Windows PowerShell."

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LordBoBCUP Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by radimek** [comment]
@LordBoBCUP thanks for comment, but after 8 months this compatibility still exist. We are not able to run scriupt for user creation under PS 7.2

This command return null:
**_$LicensedUser.AssignedLicenses.SkuId_**


When this bug will be fixed? Exist any workaround how to assign licence under PS7. When I try to assign license directly a have the this message: **_Error: "Cannot convert the "class AssignedLicenses { AddLicenses: System.Collections.Generic.List_**
