### ISSUE TITLE
More techy details

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/microsoft-365-docs#5731]
Can we get some detailed techy style info on how Defender for Endpoint gets Data from its Clients?  Win10, Server 2012 R2, 2016, 2019 etc...

Do clients Push their logs to Defender for Endpoint (via a ScheduledTask, the Microsoft Monitoring Agent or something else) or does Azure Pull the data via its API into the Cloud?

It would be great to have a "Run full Device Scan Now" option aka Collect all Logs to see how many Security Recommendations are now complaint after changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76a978b2-de1e-d59d-016d-023cb2ff4851
* Version Independent ID: d2891133-a976-edbf-2aad-d6971182dbbf
* Content: [Fix unhealthy sensors in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/fix-unhealthy-sensors?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/fix-unhealthy-sensors.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/fix-unhealthy-sensors.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
This sounds like feature request rather than a documentation issue.  Please use the smiley button and provide in-product feedback.

**Comment by yogkumgit** [comment]
@mattsmacblog Thank you very much for your kind feedback. 😊
