### ISSUE TITLE
Incorrect web link

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#5733]
The web link for "Shop Windows 10 Pro Business Devices" is invalid. Page does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81fad33-84ec-9554-b0bf-b56ff062146c
* Version Independent ID: 03daf255-ebff-3b79-dce7-8ad996b99219
* Content: [Validate new devices - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/validate-device?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-started/validate-device.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/validate-device.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@ceaton001 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5762

Once the author approves the changes the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ceaton001 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
