### ISSUE TITLE
Incorrect web link

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#5734]
The web link for "Shop Windows 10 Pro Business Devices" is invalid. Page does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9af2d6-5aa8-d3be-24cf-56e61a8f5817
* Version Independent ID: 5905b5c1-2e87-205a-7bae-2b5760b5180f
* Content: [Device requirements - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/device-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/service-description/device-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/device-requirements.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@ceaton001 Thank you for your feedback. We have fixed the link via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5761

Once the author approves this the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ceaton001 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
