### ISSUE TITLE
The help page is OUTDATED!

### ISSUE THREAD

**Issue by heyvoon** [MicrosoftDocs/microsoft-365-docs#5736]
The instructions on the help page is outdated and folowing it doesn't lead to the right place.

**Comment by denisebmsft** [comment]
Hello @heyvoon. Can you please tell us to which page your feedback applies? This information will help us route the issue to the correct writer/team. Thanks!

**Comment by yogkumgit** [comment]
@heyvoon We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
