### ISSUE TITLE
Authentication-results message header: dmarc bestguesspass - explanation incomplete

### ISSUE THREAD

**Issue by rawIce** [MicrosoftDocs/microsoft-365-docs#5738]
hello, 
under the section "Authentication-results message header fields" under the field "dmarc" the different results of DMARC checks are explained. 

For "bestguesspass" it says the following:
> Indicates that no DMARC TXT record for the domain exists, but if one had existed, the DMARC check for the message would have passed.

This is true.

Then it continues with: 
> This is because the domain in the 5321.MailFrom address (also known as the MAIL FROM address, P1 sender, or envelope sender) matches the domain in the 5322.From address (also known as the From address or P2 sender).

This is only true in case the DMARC check has passed with SPF-alignment only. 
However an email can also pass DMARC validation with DKIM alignment alone or SPF and DKIM alignment combined.  These cases are not covered in this explanation. 

Therefore the current explanation suggests that only SPF-alignment is accepted as "bestguesspass" which is definitely not true.  Adding DKIM alignment to the paragraph would make the total explanation even longer, therefore I would suggest to simply remove the second part of the description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rawIce, you state the paragraph that you want added, and I'll add it.

Or, you can add it directly as described in <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>

**Comment by rawIce** [comment]
I have created this PR #5741

**Comment by rawIce** [comment]
PR has already been merged. Issue closed.
