### ISSUE TITLE
Office 365 F1 and Microsoft 365 F1 Licensing?

### ISSUE THREAD

**Issue by computeronix** [MicrosoftDocs/microsoft-365-docs#574]
This page is amazing and has helped me with a number of questions!  There is one item that is lacking form it though and leaves room for questions.  What about Office 365 F1 licensing and what is available on the alert side as a result of this licensing?  The same goes for M365 F1 (assuming there is something else you get on top of it, but if you directly get Office 365 F1 as part of M365 F1, then feel free to ignore).

Could you provide the specific alert capabilities that are provided as a result of Office 365 F1 licensing?  If F1 is equivalent to an E1 lets say then a blurb on this page mentioning that will be sufficient.

For reference:
https://www.microsoft.com/en-us/microsoft-365/business/office-365-f1

https://www.microsoft.com/en-gb/microsoft-365/compare-all-microsoft-365-plans

Thank you for this documentation!!  It greatly helps!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance center](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@computeronix *E1 and *F1 are equivalent. I will update the documentation. In the future, you can also update topics directly and submit a pull request.
