### ISSUE TITLE
Attack simulation training limits question

### ISSUE THREAD

**Issue by jm15502** [MicrosoftDocs/microsoft-365-docs#5742]
More than a year ago, i started sending emails to 3000 users as part of a phishing campaign but had to do it in separate groups because there was a 500 sending limit that was applied, multiplying my work by 6. Is that limit still in place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b480c7ad-d444-b167-6c3c-80a8e8fb714d
* Version Independent ID: a17b1117-7d8a-54b1-fa72-6cc7b644a254
* Content: [Attack simulation training deployment considerations and FAQ - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-faq.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by jm15502** [comment]
Hi Yogesh, any update?
Thanks

**Comment by msbemba** [comment]
@jm15502 Thank you for your feedback. The limit was recently updated to 1000 via our roadmap# 55025.


Currently, you can only change the recipient limits via PowerShell, but the corresponding UI bits are also rolling out and should be available at some point in the EAC. Here are some examples on how you can utilize this. First, if you want to change the recipient limit for a single mailbox, you can use the Set-Mailbox cmdlet:

Set-Mailbox user@domain.com -RecipientLimits 999

If you want to perform the change against a group of users, you can easily do so by using filters or importing the list from a CSV file. For example, here’s how to do it on all users in a specific department:

Get-User -RecipientTypeDetails UserMailbox -Filter {Department -eq "Marketing"} | Set-Mailbox -RecipientLimits 999

Or if you want to change it for all user mailboxes in the organization:

Get-Mailbox -RecipientTypeDetails UserMailbox -ResultSize Unlimited | Set-Mailbox -RecipientLimits 999

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jm15502 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
