### ISSUE TITLE
Password Expiration Notifications Retired per MC219002

### ISSUE THREAD

**Issue by jasonfritts** [MicrosoftDocs/microsoft-365-docs#5744]
This doc should be updated to reflect the fact that Password Expiration Notifications are no longer supported in Office Portal or any Office apps. See Message Center MC219002: Retirement of notifications functionality in all Office 365 web apps except Outlook.  Email notifications do not seem to be functional any longer either.  It's not clear in this article's "Set password expiration policy" section that step 6 for choosing notification window in days has no effect any longer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide#set-password-expiration-policy)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jasonfritts Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5781

Once the author approves the PR the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jasonfritts Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
