### ISSUE TITLE
o365-solutions

### ISSUE THREAD

**Issue by rupamcc** [MicrosoftDocs/microsoft-365-docs#5745]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab55fc7e-f0eb-684a-cf8f-dd89990937c5
* Version Independent ID: 6d7e6627-cc17-853c-6563-420e02f87f45
* Content: [Desktop Deployment Center - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/desktop-deployment-center-home?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/desktop-deployment-center-home.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/desktop-deployment-center-home.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by denisebmsft** [comment]
Hello @rupamcc. Can you please give us a little more information in your feedback?

**Comment by yogkumgit** [comment]
@rupamcc We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
