### ISSUE TITLE
PowerShell and Graph APIs

### ISSUE THREAD

**Issue by grzegorzwierzbicki** [MicrosoftDocs/microsoft-365-docs#5747]
This article should cover how to perform each task with PowerShell and Graph APIs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Step 4 - Give another employee access to OneDrive and Outlook data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-4?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-4.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-4.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@grzegorzwierzbicki Author confirmed that he has added it in the backlog. Document will be updated accordingly. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
