### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by dyerseve** [MicrosoftDocs/microsoft-365-docs#5749]
Can we see an example for adding a group to the addin?
I've added one deployment through the web and trying to replicate that success using powershell and I'm coming up short. Not sure if it's the tools or me.

**Comment by denisebmsft** [comment]
Hello @dyerseve. Can you please tell us to which article your feedback applies? This information will help us route the issue correctly. Thank you!

**Comment by yogkumgit** [comment]
@dyerseve We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
