### ISSUE TITLE
Need definition for people outside or inside your organization

### ISSUE THREAD

**Issue by NileshGhodekar** [MicrosoftDocs/microsoft-365-docs#575]
Hi, this page mentioned on of the conditions that can be specified is "Content is shared with people outside or inside your organization". However, there is no definition of who counts as an outside person vs who count as an inside person and if this definition is consistent across O365 services. For example, a Azure AD B2B users can be onboarded as guests or as members in the host tenant AAD. Do they all treated as outside persons in EXO as well as SPO? A mail user account for a contractor in local AD/ synced to AAD, is it treated as outside person not just in EXO but in SPO as well? It will be good to get a clarity on which service treats who as an outsider vs insider if the definition is not consistent across Azure AD and O365 services and each one is looking at different user attributes. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ac1028-da5c-2f6b-a8ef-ae21b0b4b858
* Version Independent ID: 22cdcee5-fb52-f07e-5d63-d925cb84915d
* Content: [Overview of data loss prevention](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-loss-prevention-policies#feedback)
* Content Source: [microsoft-365/compliance/data-loss-prevention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-loss-prevention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@NileshGhodekar  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @NileshGhodekar 
**For example, a Azure AD B2B users can be onboarded as guests or as members in the host tenant AAD. Do they all treated as outside persons in EXO as well as SPO?** - yes, b2b guests are external (source [Key properties of the Azure AD B2B collaboration user](https://docs.microsoft.com/azure/active-directory/b2b/user-properties#key-properties-of-the-azure-ad-b2b-collaboration-user))
**A mail user account for a contractor in local AD/ synced to AAD, is it treated as outside person not just in EXO but in SPO as well?** - yes, in both services mailusers are external 
**It will be good to get a clarity on which service treats who as an outsider vs insider if the definition is not consistent across Azure AD and O365 services and each one is looking at different user attributes** - it is consistent, the attribute to look for is "UserType", for internal users it has value "Member"
Thank you

**Comment by NileshGhodekar** [comment]
@MaratMussabekov,
So you have now introduced a new term "external" in this discussion in addition to the confusion around person inside / outside the organisation and person member / guest!! The link that you shared already mentions that B2B users can be either guests or members. and it is this property that determines users associate to the host organization. Quote: "The UserType has no relation to how the user signs in, the directory role of the user, and so on. This property simply indicates the user's relationship to the host organization and allows the organization to enforce policies that depend on this property."  So Azure AD is clearly looking at UserType, but I'm pretty sure a B2B user with UserType = Member will be treated as person outside the organisation by EXO/SPO DLP policy as their mailbox is somewhere else (I've no reason to believe that this will work differently that say how it already works when you define DLP rules in EXO transport rules). The converse of this will also be true. You can sync a population of your onpremises users as UserType = Guest via AAD Connect. I'm pretty sure EXO/SPO will treat them all as "inside the organisation" if they are licensed in O365 appropriately / have local EXO mailbox. At the minimum, I see this as an increading concern for confusion and a clear and common definition / terminology is needed across Microsoft services.

**Comment by MaratMussabekov** [comment]
Hello @NileshGhodekar,
thank you for the provided information, unfortunately I do not have sufficient environment to test suggested scenarios for Azure AD B2B users. I think we should request Microsoft representatives to clarify the used terminology.
Thank you

**Comment by mypil** [comment]
@chrfox - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by chrfox** [comment]
PR merged that addresses this question
