### ISSUE TITLE
Add clarification for which URLs to open on firewall

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/microsoft-365-docs#5751]
There is some confusion about what URLs to open on the firewall in terms of opening all the URLs or just the ones for your data location.   I think this doc edit will help clarify:

In this section:
Enable access to Microsoft Defender for Endpoint service URLs in the proxy server

This statement:
_The following downloadable spreadsheet lists the services and their associated URLs that your network must be able to connect to. You should ensure that there are no firewall or network filtering rules that would deny access to these URLs, or you may need to create an allow rule specifically for them._ 

Can we add a statement that directs customers to use the spreadsheet as follows?:
1) In your firewall, open all the URLs where the geography column is WW.
2) For rows where the geography column is not WW, open the URLs to your specific data location.  You can verify your data location setting using the instructions here: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/data-retention-settings?view=o365-worldwide#verify-data-storage-location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jmmowrer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5792.

Once the author approves the PR, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jmmowrer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
