### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#5752]
Licensing section needs rework. It says it is an add-on, but then also says it is typically through a Microsoft 365 license.

This section:
https://docs.microsoft.com/en-us/microsoft-365/scheduler/scheduler-setup?view=o365-worldwide#scheduler-end-user-license-requirements

Doesn't even mention it is an add-on, so it sounds like it is included with all of the plans in the bulleted list.

This section:
https://docs.microsoft.com/en-us/microsoft-365/scheduler/scheduler-setup?view=o365-worldwide#exchange-online-mailbox

should not be talking about licensing, unless it is talking about licensing the scheduler mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d33f8e34-9baa-3efd-b1cc-03f3e3ab44f0
* Version Independent ID: 201878c7-a0d7-a744-c60c-d65f714d2a9d
* Content: [Setting up Scheduler for Microsoft 365.](https://docs.microsoft.com/en-us/microsoft-365/scheduler/scheduler-setup?view=o365-worldwide)
* Content Source: [microsoft-365/scheduler/scheduler-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/scheduler/scheduler-setup.md)
* Service: **scheduler**
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. I have made changes to the document clearly stating the add-on requirement via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5764

Once the author approves the PR, you will see changes in the document.

Thanks
Sri

**Comment by danmyhre** [comment]
sounds good, thanks much!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @danmyhre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
