### ISSUE TITLE
404 link to MDE URL XLSX is dead

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/microsoft-365-docs#5753]
https://download.microsoft.com/download/8/a/5/8a51eee5-cd02-431c-9d78-a58b7f77c070/mde-urls.xlsx

results in a 404 error
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@vboyev-MSFT Thank you for your feedback. I was able to download the XLS file using the link. Could you please confirm if the problem exists?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @vboyev-MSFT Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
