### ISSUE TITLE
Example script to disable AllowSelfServicePurchase (Additional note)

### ISSUE THREAD

**Issue by lwolf-sagetechs** [MicrosoftDocs/microsoft-365-docs#5757]
When the script command
`Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId $product.ProductID -Enabled $false`
is run, it will fail if $product contains multiple values.

When there are multiple products, you can run the command individually for each value like this.
`Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId $product[0].ProductID -Enabled $false`
`Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId $product[1].ProductID -Enabled $false`
etc.

Or you can loop through all the ProductIDs in $product this way.
`foreach ($id in $product.ProductId)`
`{  Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId $id -Enabled $false  }`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@lwolf-sagetechs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5834

Once the author approves, the document will be live.
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lwolf-sagetechs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
