### ISSUE TITLE
Export options differ between Docs and real-time export in Advanced eDiscovery

### ISSUE THREAD

**Issue by MubDubs** [MicrosoftDocs/microsoft-365-docs#5758]
The export options for conversation threading of 1:1 Teams messaging differ between what is seen in the docs vs what we see in Advanced eDiscovery on the compliance.microsoft.com platform. We need the documentation updated to reflect the different UI and export options as some of the options shown in the documentation are no longer there.

The export options now shown are what is seen in this document. There is no 'metadata' options, no 'content' options for conversation review sets.
https://docs.microsoft.com/en-us/microsoft-365/compliance/export-documents-from-review-set?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c7b265-cceb-fe6b-2490-ab225665695b
* Version Independent ID: af062eb4-4d5f-e5d5-0638-0e627c09ce09
* Content: [Review conversations in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/conversation-review-sets?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/conversation-review-sets.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/conversation-review-sets.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. Thanks

**Comment by markjjo** [comment]
@MubDubs Thanks for the heads up. I updated the export section in this article by linking to the AeD export article, which is up to date.

https://docs.microsoft.com/en-us/microsoft-365/compliance/conversation-review-sets?view=o365-worldwide#exporting-conversations

**Comment by MubDubs** [comment]
Thank you for the update! It is much appreciated and will help many others.

Kyle Jones
