### ISSUE TITLE
api access

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/microsoft-365-docs#5759]
All the connection information says you need a bearer token and they all point to using an App.  This has to be incorrect.   

I can use my browsers bearer token I get from my web browser by just pressing F12 going to the header and Microsoft defender api calls work just fine.  

Is there anywhere that shows me from PowerShell how to get a bearer token interactively with only my account?

The whole process to make a application to get a token is sort of a farce if the browser can get one without this.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aa01e74-4303-b044-086e-44340dac3141
* Version Independent ID: fc1a3aa5-4889-2c62-d726-4957b8d85e6b
* Content: [Supported Microsoft Defender for Endpoint APIs](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/exposed-apis-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/exposed-apis-list.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Checking with team.

**Comment by mjcaparas** [comment]
To use our public APIs (via user context or app context) you'll need to create your own app.

While taking the portal token works for some APIs today, this method may not work in the long term.
