### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MisterBendo** [MicrosoftDocs/microsoft-365-docs#5766]
In the section called "About junk email settings in Outlook", in the second paragraph, it says...
When the Outlook Junk Email Filter is set to the default value No automatic filtering in Home > Junk > Junk E-Mail Options > Options, Outlook doesn't attempt to classify **massages** as spam

Outlook doesn't attempt to classify messages, not massages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bec871b-790f-6826-b8f8-d1b7830c49ab
* Version Independent ID: 460db4e8-7f93-60a3-4889-f2d8f08fc75f
* Content: [Configure junk email settings on Exchange Online mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MisterBendo, Fixed.

In the future, you, too can make changes like this without opening a GitHub Issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing

**Comment by MisterBendo** [comment]
Thanks.  I was unaware I could make fixes myself.  I will read the instructions and correct any future mistakes per the article.

Michael Donovan |  ***@***.******@***.***>
Senior Systems Engineer - Microsoft 365 Communication Services
T. +01 (303) 471 3457 | M. +01 (303) 726 2139
