### ISSUE TITLE
Clarification needed on what "administrator account" means

### ISSUE THREAD

**Issue by turnma** [MicrosoftDocs/microsoft-365-docs#5769]
Page states
"sign in using the credentials _for an administrator account_ in your organization."

This needs clarification on exactly which RBAC roles can achieve this task.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7108464d-597a-c79d-cac8-94e35d9dd3d0
* Version Independent ID: ba0d3744-707d-c506-47f4-83519022d4cb
* Content: [Create and manage inactive mailboxes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-and-manage-inactive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-and-manage-inactive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@turnma Thank you for your feedback.AFAIK, compliance and global administrators can perform this action. I'm currently testing this with different admin roles and will update the document shortly.


Thanks
Sri

**Comment by msbemba** [comment]
@turnma I was able to test this with only global and compliance admin roles. I have made changes to the document accordingly via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5835

Thank you again for your valuable feedback.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @turnma Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
