### ISSUE TITLE
Error applying Model to a library

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#5772]
When applying a Model to a Document Library, an error message is displayed upon clicking Add button:

![image](https://user-images.githubusercontent.com/9206808/127525374-82ca5c3c-706b-4d14-804a-bac7488c3fba.png)

> Specified argument was out of range of valid values. Parameter name: index.

Usually works the _third_ time...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3000f1d8-7c81-d9c2-adfc-fa5f76612d73
* Version Independent ID: 9fbcb2c9-69d3-c825-73bb-1547158ee051
* Content: [Apply a document understanding model to a document library](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/apply-a-model)
* Content Source: [microsoft-365/contentunderstanding/apply-a-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/apply-a-model.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by yogkumgit** [comment]
@chuckedmonson Please help us in resolving this issue. Thanks

**Comment by chuckedmonson** [comment]
@seansquires -- Can you please advise sparkitect on another issue in the inquiry above? Thank you.

**Comment by chuckedmonson** [comment]
@sparkitect -- The reason you see an error is you have a managed metadata field “Document Type” whose term set can’t be found, you’ll want to look into this (perhaps it has been deleted).
We absolutely acknowledge that the error message isn’t helpful. We will change that to be more explicit about not being able to find the term set, we’ll get that updated. Thanks for the feedback.

**Comment by sparkitect** [comment]
I just checked and can verify that the column wasn't bound to a Term Set at all.
My bad 😊

**Comment by chuckedmonson** [comment]
@sparkitect -- thanks!
