### ISSUE TITLE
Number of forms created

### ISSUE THREAD

**Issue by IfEyeOnlyKnew** [MicrosoftDocs/microsoft-365-docs#5773]
[Enter feedback here] - On the page can you distinguish that the "Number of forms created" is any time/date and not just the 30 to 180 days reporting?  Or is the count from the last 30 - 180 days?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc03c59-64a6-950b-adbd-bf5e1b5c59b3
* Version Independent ID: 7479ae58-d00e-e42d-39db-c4f029e32440
* Content: [Microsoft 365 Reports in the admin center - Forms activity - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/forms-activity-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/forms-activity-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/forms-activity-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@IfEyeOnlyKnew Thank you for your feedback. By default, it displays 30 days date. But if you click on the drop-down at the top of the page, you can switch either 7, 90, or 180 days. The data does not go beyond 180 days.

![image](https://user-images.githubusercontent.com/45987684/128062871-bb564d5e-cc02-457a-a5dd-b0962ea9e2e9.png)

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @IfEyeOnlyKnew Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
