### ISSUE TITLE
How about steps for doing this with Powershell Az module?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#5778]
With the push to stop using the legacy AzureAD module, can this be done with the Az module instead? I already uninstalled the older module we are supposed to stop using.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide#steps-for-doing-this-with-powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66854a7-7556-9b2a-0a33-886e3d881047
* Version Independent ID: 7ce3d8d5-cece-0b6f-68d5-143e12a3fff8
* Content: [Detect and Remediate Illicit Consent Grants - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@jonwbstr Thank you for your feedback. I was not able to execute the script using the AZ module. it still expects to connect to AzureAD.

I will work with the team internally and update you shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@jonwbstr I can confirm that currently, the script only works with the  Legacy Azure AD module. When we have steps for the new AZ module the document will be updated.

Hope this helps!

@yogkumgit  There are no changes to the document for now. Once the script is updated in the backend to work with the AZ module, this would automatically get fixed. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jonwbstr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
