### ISSUE TITLE
Parameter -DecryptAttachmentFromPortal is depreciated

### ISSUE THREAD

**Issue by Jens-Lorenz** [MicrosoftDocs/microsoft-365-docs#578]
In the section service-side decryption of email attachments for web browser mail clients the parameter Set-IRMConfiguration -DecryptAttachmentFromPortal &lt;$true|$false&gt; is depreciated and -DecryptAttachmentForEncryptOnly should be used instead. Maybe this should be updated on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33bb6e61-f899-955c-948d-bf17f0168fea
* Version Independent ID: be8ea691-3547-a442-d2ca-617e17225740
* Content: [Manage Office 365 Message Encryption](https://docs.microsoft.com/en-us/microsoft-365/compliance/manage-office-365-message-encryption)
* Content Source: [microsoft-365/compliance/manage-office-365-message-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/manage-office-365-message-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@Jens-Lorenz - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
This parameter was updated in PR #611, which was merged.
