### ISSUE TITLE
Indicate to use UNC path and FQDN rather than NetBIOS name

### ISSUE THREAD

**Issue by loosus** [MicrosoftDocs/microsoft-365-docs#5787]
The following is one of the steps:

> Go to the **Actions** tab and click **New...** Ensure that **Start a program** is selected in the **Action** field. Enter the NetBIOS path of the shared _WindowsDefenderATPOnboardingScript.cmd_ file.

However, as enterprises start disabling NetBIOS and NTLM, the following may be more precise going forward:

> Go to the **Actions** tab and click **New...** Ensure that **Start a program** is selected in the **Action** field. Enter the UNC path, using the file server's fully qualified domain name (FQDN), of the shared _WindowsDefenderATPOnboardingScript.cmd_ file.

In fact, in environments that have fully or partially disabled NTLM, using what has been called the "NetBIOS name" won't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523651c3-a318-2369-6892-d13e04991596
* Version Independent ID: 624c5e05-f87d-1bd4-bc87-bd55dcac1d86
* Content: [Onboard Windows 10 devices to Microsoft Defender for Endpoint via Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-gp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@loosus Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5796

Once the author approves the PR, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @loosus Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
