### ISSUE TITLE
RSS Feed link incomplete

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/microsoft-365-docs#5791]
RSS Feed link incomplete

Reads 
/api/search/rss?search=%22Lists+the+new+features+and+functionality+in+Microsoft+365+defender%22&locale=en-us
Shouldn't this have https://docs.microsoft.com in front of this?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac42403c-4226-bec2-986d-2e8a67e7c66d
* Version Independent ID: e8e0b323-ee46-f8e7-fe99-cbee91697213
* Content: [What's new in Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/whats-new.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@dcaddick Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5794

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dcaddick Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
