### ISSUE TITLE
Link to Get-AzureADPSPermissions.ps1 is different than 'App consent grant investigation' docs article 

### ISSUE THREAD

**Issue by timhaintz** [MicrosoftDocs/microsoft-365-docs#5793]
Hello, the link for Get-AzureADPSPermissions.ps1 references the repo and script [Get-AzureADPSPermissions.ps1](https://gist.github.com/psignoret/41793f8c6211d2df5051d77ca3728c09)

In the Docs article [App consent grant investigation](https://docs.microsoft.com/en-us/security/compass/incident-response-playbook-app-consent) the link to the script is: https://aka.ms/getazureadpermissions. Which links to the [AzureADToolkit](https://github.com/microsoft/AzureADToolkit#exporting-a-list-of-service-principals-and-applications-with-risk-scores-requires-external-module-to-generate-excel-workbook) PowerShell module.

Could the link in this article please be updated?
Thank you, Tim.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66854a7-7556-9b2a-0a33-886e3d881047
* Version Independent ID: 7ce3d8d5-cece-0b6f-68d5-143e12a3fff8
* Content: [Detect and Remediate Illicit Consent Grants - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@timhaintz Thank you for your feedback. We have made changes to the document via PR#
https://github.com/MicrosoftDocs/security/pull/52

Once the author approves the PR the document will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This has been merged via different PR. The document is updated and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @timhaintz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
