### ISSUE TITLE
Mapping File

### ISSUE THREAD

**Issue by 29039** [MicrosoftDocs/microsoft-365-docs#5799]
Where is it? I am on the step where I am to tick "I have access to the mapping file", but I actually don't. I don't see it on the companion guide linked: https://go.microsoft.com/fwlink/?linkid=544944#BKMK_NetworkUpload / https://docs.microsoft.com/en-gb/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-worldwide#BKMK_NetworkUpload and using CTRL+F word "mapping".  Perhaps the location of this file could be made more obvious?

**Comment by msbemba** [comment]
@29039 Thank you for your feedback. The step by step instructions are available here at https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by 29039** [comment]
Thanks Sri, I had eventually found that link, but it should have been part of the overview instructions as it's a critical step which can't be guessed.

**Comment by msbemba** [comment]
@29039 I have added the download link to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5840

Once the author approves the change, the PR will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  The document we are updating is https://docs.microsoft.com/en-gb/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-worldwide#BKMK_NetworkUpload

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @29039 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
