### ISSUE TITLE
Need notation for system requirements

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/microsoft-365-docs#5800]
Can we add a link to the minimum endpoint OS requirements for this AutoIR API to work against?  Right now it doesn't say anything about the fact that this won't work against Mac and Linux.  

Here's the link the min requirements.
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/automated-investigations?view=o365-worldwide#requirements-for-air

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9177cc8b-bd7f-22b1-7985-ddb89fc70a80
* Version Independent ID: 7f2f23f0-3681-5be8-e0fe-65b463295a37
* Content: [Start Investigation API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/initiate-autoir-investigation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/initiate-autoir-investigation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/initiate-autoir-investigation.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jmmowrer Thank you for your feedback. We have added the information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5836

Once the author approves PR, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jmmowrer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
