### ISSUE TITLE
Misinformation

### ISSUE THREAD

**Issue by trkrdy1** [MicrosoftDocs/microsoft-365-docs#5801]
I always hear customers say "how do we put MDE in passive mode?" And after seeing this page I get why they ask, MDE does not get put into passive mode. MDAV does, can we please correct this page to reflect this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e795a9bd-0d5a-ab4d-4f44-c1e365dce162
* Version Independent ID: 429ebad4-c2ab-e481-0984-301a8900c14d
* Content: [Make the switch from non-Microsoft endpoint protection to Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-migration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-migration.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @trkrdy1 and thank you so much for the feedback! I have a work item in the queue to get the diagram corrected. Really appreciate your taking the time to let us know about this!

**Comment by denisebmsft** [comment]
Hello @trkrdy1 and @yogkumgit! Just wanted to let you know that I fixed the diagram today. You will see the updates render live a little later this afternoon. Thank you again for the helpful feedback!
