### ISSUE TITLE
Need notation for supported OS'

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/microsoft-365-docs#5803]
Can we add a link that refers to this document for the minimum device OS requirements for this feature to work?

Here's the link that should have the min requirements.  It doesn't now but I will add another doc issue for that.
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#collect-investigation-package-from-devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab25f12f-c60d-609f-ed7e-4ae0c3457189
* Version Independent ID: d6899a59-0f2a-e111-7c77-43b05f5100aa
* Content: [Collect investigation package API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/collect-investigation-package?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/collect-investigation-package.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/collect-investigation-package.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jmmowrer Thank you for your feedback. We have added the information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5860

Once the author approves PR, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jmmowrer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
