### ISSUE TITLE
Need notation for supported OS'

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/microsoft-365-docs#5805]
Can we add a link that refers to this document for the minimum device OS requirements for this feature to work?

Here's the link that should have the min requirements. It doesn't now but I will add another doc issue for that.
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#collect-investigation-package-from-devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8946a2-a2ea-1dc7-a6ce-13c56d11b485
* Version Independent ID: 9de7a1fa-d8d9-4ea6-33fc-7e50528b1c04
* Content: [Get package SAS URI API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-package-sas-uri?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-package-sas-uri.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-package-sas-uri.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jmmowrer Thank you for your feedback. We have added the information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5861


Once the author approves PR, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jmmowrer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jmmowrer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
