### ISSUE TITLE
Query "Check if files from a known malicious sender are on your devices" has semantic errors

### ISSUE THREAD

**Issue by m8r1us** [MicrosoftDocs/microsoft-365-docs#5814]
Query "Check if files from a known malicious sender are on your devices" is not correct.

Fixed version adding DeviceName and DeviceId to DeviceFileEvents query to receive the values in the last project statement.

```kusto
EmailAttachmentInfo
| where SenderFromAddress =~ "MaliciousSender@example.com"
//Get emails with attachments identified by a SHA-256
| where isnotempty(SHA256)
| join (
//Check devices for any activity involving the attachments
DeviceFileEvents
| project FileName, SHA256, DeviceName,DeviceId
) on SHA256
| project Timestamp, FileName, DeviceName, DeviceId, SHA256, NetworkMessageId, SenderFromAddress, RecipientEmailAddress
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7512859a-b097-af0b-e298-65933353c5ac
* Version Independent ID: 3206d0e2-5e4f-11e1-a21c-f032280bddfb
* Content: [Hunt for threats across devices, emails, apps, and identities with advanced hunting](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-query-emails-devices?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-query-emails-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-query-emails-devices.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@m8r1us Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5830

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @m8r1us Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
