### ISSUE TITLE
ActionType - NamedPipeEvents

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/microsoft-365-docs#5820]
Product group tells me MDE collects of ActionType "**NamedPipeEvents**" - this type of events is not mentioned in docs or in the portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c292f6dc-0eca-e5d1-04f3-d29adeb5c77f
* Version Independent ID: f75be752-3169-cf4f-3e9b-9d5115d2c352
* Content: [DeviceEvents table in the advanced hunting schema](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-deviceevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-deviceevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-deviceevents-table.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
@Rvvhub They are not available right now but it is currently being worked on to be available in the next couple of months. Kindly check back with us then.

**Comment by yogkumgit** [comment]
@Rvvhub Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
