### ISSUE TITLE
Does the scripts support Visual Studio Subscription as the Source tenant/subscription?

### ISSUE THREAD

**Issue by rzhangongit** [MicrosoftDocs/microsoft-365-docs#5829]

**Comment by yogkumgit** [comment]
@rzhangongit Please indicate which document you are referring to and what is your feedback. Thanks

**Comment by rzhangongit** [comment]
Hi Yogkumgit, Thank you for reaching out. The document is for "Cross-tenant mailbox migration" published at https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide

We are following the instructions to perform cross-tenant mailbox migration, but could not get through the step 6.

Sorry this is the first time I posted a question on the feedback link, and not sure how to link the question with the document.

Thanks again for your time.
Ruben

**Comment by msbemba** [comment]
@rzhangongit Thank you for your feedback. Unfortunately, It doesn't work with a visual studio subscription. You need to have an Azure subscription to use for creating resources.

Hope this helps!

Thanks
S\ri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @rzhangongit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
