### ISSUE TITLE
Proxy Service URLs confirmation

### ISSUE THREAD

**Issue by gonz-kelv** [MicrosoftDocs/microsoft-365-docs#5832]
Hi,

Was reviewing the Firewall Proxy URL Defender for Endpoint Sensor needs to communicate. Saw theres one entry row 73 in Defender for Endpoints sheet where it says 
Current
*download.windowsupdate.com
Should there be a period after the wildcard?
*.download.windowsupdate.com

Thanks,
Kelvin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b25b8545-b7f0-e035-ca6e-26b1530feddb
* Version Independent ID: 93b5152a-2ba2-1239-ded7-42896cacc074
* Content: [Set up Microsoft Defender for Endpoint deployment](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/production-deployment?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/production-deployment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/production-deployment.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@gonz-kelv Thank you for your feedback. I'll work with the author internally and update you.

Thanks
Sri

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@mjcaparas Gentle reminder

**Comment by mjcaparas** [comment]
The sheet was updated last September to address this.
