### ISSUE TITLE
After consent is granted - receive a token not found error

### ISSUE THREAD

**Issue by rhoward9416** [MicrosoftDocs/microsoft-365-docs#5833]
When executing the SetupCrossTenantRelationshipForTargetTenant.ps1, after granting consent using both URL's for the target and resource domain, the following error occurs.  We are running the script using 2 test tenants, one as the source and the other as the target. 

<img width="387" alt="tokenNotFound" src="https://user-images.githubusercontent.com/88398440/128061887-59c79ebb-7b31-4465-bf3d-b90435e4286e.PNG">
AADSTS90002: Tenant 'token' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator. 
<img width="688" alt="PScapture" src="https://user-images.githubusercontent.com/88398440/128062859-7a0c90f9-dd2f-4066-9b76-3d2f244d3ba1.PNG">

What are we missing?

**Comment by yogkumgit** [comment]
@rhoward9416 Considering the nature of the issue,  please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
