### ISSUE TITLE
Change the line 12 to Optimize to make emergency calling in teams available for remote users.

### ISSUE THREAD

**Issue by alfimasing** [MicrosoftDocs/microsoft-365-docs#5839]
Hi Team,

I would request a change in Category for line 12 in the table for TEAMS and SFB from "Allow" to "Optimize".
All our docs regarding Networking are stating that at least the Optimize category should bypass customers onprem security environment as much as possible. For VPN we are recommending using Split tunnel and excluding at least Optimize category. This is not enough for emergency calling.
To get Emergency calling in US to a legal state, our customers need to know if the Users are remote. 
In Teams it's done through the signaling steam. Signaling is the line number 12.
I ask you to change the category  line 12 from "Allow" to "Optimize" to align with other docs towards what is necessary to have a good and reliable environment.
Thank you for your support.
Kind regards Alfred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
Hi @alfimasing Are you MS internal? Can you find me on email so I can connect you with the engineering folks who drive this guidance. Thanks.
