### ISSUE TITLE
UPDATE ROADMAP

### ISSUE THREAD

**Issue by CaseyPatrickOConnor** [MicrosoftDocs/microsoft-365-docs#584]
An updated Roadmap for 2020 would be helpful for CSP needing to advise clients on the upcoming year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ac92ed3-7f03-1031-df85-13f1f1504879
* Version Independent ID: 0794e7ba-c0a9-5603-6c5b-bd5036b810f1
* Content: [Office 365 security roadmap - Top priorities for the first 30 days, 90 days, and beyond](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/security-roadmap#feedback)
* Content Source: [microsoft-365/security/office-365-security/security-roadmap.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/security-roadmap.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@CaseyPatrickOConnor - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@BrendaCarter - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by BrendaCarter** [comment]
Hi CaseyPatrickOConnor, we're looking into how we'd like to update the roadmap. Another resource that is fresh is https://docs.microsoft.com/en-us/microsoft-365/security/microsoft-365-security-for-bdm.

**Comment by mypil** [comment]
@CaseyPatrickOConnor - From our understanding, the issue has been answered by BrendaCarter.

Thank you for engaging with the community here for the docs.

**Comment by SergGu** [comment]
Can you please include new BDM link to the old 30-90-beyond roadmap? I suggest to do it in **BOLD** on the top of the document. That is because I'm concerned about great BDM document being overlooked.

New link - https://docs.microsoft.com/en-us/microsoft-365/security/microsoft-365-security-for-bdm
Old roadmap - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/security-roadmap
