### ISSUE TITLE
Information about how the retention impacts Sharepoint quota is missing

### ISSUE THREAD

**Issue by deividfoggi** [MicrosoftDocs/microsoft-365-docs#5841]
It is not clear in this article how the retention of information by using retention policies will impact the storage quotas in Sharepoint and which quota will be consumed: site quota or tenant`s total storage quota?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@deividfoggi  Yes, this is important information so we put it on the main page, where we introduce the concept of retention in place and explain "For SharePoint and OneDrive sites: The copy is retained in the Preservation Hold library."(https://docs.microsoft.com/microsoft-365/compliance/retention#how-retention-settings-work-with-content-in-place):

The Preservation Hold library consumes storage that isn't exempt from a site's storage quota. You might need to increase your storage when you use retention settings for SharePoint and Microsoft 365 groups.

**Comment by deividfoggi** [comment]
It may be clear in english but it is not in portuguese and I don't think it is a matter of automatic translation. More than one customer asked me about it because it is not a direct sentence. They wonder if it is going to impact only the tenant's total quota or the site quota which means it will prevent users from saving files because the respective site quota is reached. If the site quota is impacted because items get stored in its preservation library due to retention hold period then the administrative burn is considerably high in comparison with the supposed scenario where the retention will impact only tenant's total quota. Considering how it is important and critical for the customers I think it could be more direct like "The preservation hold library consumes the site's storage quota" making it clear that the retention of items has a significantly potential to impact each site's quota. Thanks.

**Comment by cabailey** [comment]
OK, will look into making this clearer - thanks for your feedback!

**Comment by cabailey** [comment]
Updated now - I think it was because the original wording was expressed negatively ("isn't exempt") instead of a positive statement that made it harder to understand/translate.  I've changed this & condensed the two sentences:

Because the Preservation Hold library is included in the site's storage quota, you might need to increase your storage when you use retention settings for SharePoint and Microsoft 365 groups.

**Comment by cabailey** [comment]
Closing - thanks for your feedback that helps to make the docs better for everybody!
