### ISSUE TITLE
Confusion about the Note around CDN availability for government cloud

### ISSUE THREAD

**Issue by andydlayton** [MicrosoftDocs/microsoft-365-docs#5842]
I have had some confusion from GCC customers (they are in the commercial cloud, but a logically separated data enclave).  Can we call out in the note that the CDN is available for Commercial and GCC customers to distinguish.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cfe2b0-c14d-1083-7c88-a91e58593cfa
* Version Independent ID: 2d15076c-0dcd-6bd6-e0fb-f8ac5ffd0091
* Content: [Use Office 365 Content Delivery Network (CDN) with SharePoint Online - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by msbemba** [comment]
@andydlayton Thank you for your feedback. There is already a note which states The Office 365 CDN is only available to tenants in the Production (worldwide) cloud - This is the commercial cloud.
Tenants in the US Government, China, and Germany clouds do not currently support the Office 365 CDN.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @andydlayton Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
