### ISSUE TITLE
Security Operator role

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#585]
Is there a reason that  Azure AD Security Operator role is not listed or cannot be used to view the reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e62b98-5f0c-8fc3-8163-c028fa5a6445
* Version Independent ID: b8262fa8-ff97-db0a-b2b5-4dd624fb057b
* Content: [View reports for Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-reports-for-atp#what-permissions-are-needed-to-view-the-atp-reports)
* Content Source: [microsoft-365/security/office-365-security/view-reports-for-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-reports-for-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by denisebmsft** [comment]
Greetings! I'm working on this. Stay tuned!

**Comment by mypil** [comment]
@denisebmsft - Do you have any updates on this?

Thank you.

**Comment by mypil** [comment]
@DeanGross - From our understanding, the issue has been resolved based on the following merged commits https://github.com/MicrosoftDocs/microsoft-365-docs/commit/63e3c3490408c00b8bb013f8a5a348ac61621736 and https://github.com/MicrosoftDocs/microsoft-365-docs/commit/6c38af9c7933d360eea9d116da5a4e287e6d2cff. 


Thank you for your contribution to make the docs better! Much appreciated!
