### ISSUE TITLE
Update with licensing requirements

### ISSUE THREAD

**Issue by techangelsau** [MicrosoftDocs/microsoft-365-docs#5854]
Please update this documentation at the beginning to specify what 365 license is required for Communications Compliance. (365 E5).
https://compliance.microsoft.com/supervisoryreviewtrial 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd283c0e-1421-d45d-83de-db7210a43936
* Version Independent ID: 33f52f1e-86e1-8b07-5420-4549597f3d63
* Content: [Learn about communication compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/communication-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@techangelsau Thank you for your feedback. The Document is only an overview of what one can do with communication compliance. The next Page on the document ( Plan for communication compliance) has all details about permissions needed. The following document (get started with communication compliance ) has details about subscriptions and licensing.

Reference :- https://docs.microsoft.com/en-us/microsoft-365/compliance/communication-compliance-configure?view=o365-worldwide#subscriptions-and-licensing

To access and use communication compliance, your organization must have one of the following subscriptions or add-ons:

Microsoft 365 E5 subscription (paid or trial version)
Microsoft 365 E3 subscription + the Microsoft 365 E5 Compliance add-on
Microsoft 365 E3 subscription + the Microsoft 365 E5 Insider Risk Management add-on
Microsoft 365 A5 subscription (paid or trial version)
Microsoft 365 A3 subscription + the Microsoft 365 A5 Compliance add-on
Microsoft 365 A3 subscription + the Microsoft 365 A5 Insider Risk Management add-on
Microsoft 365 G5 subscription (paid or trial version)
Microsoft 365 G5 subscription + the Microsoft 365 G5 Compliance add-on
Microsoft 365 G5 subscription + the Microsoft 365 G5 Insider Risk Management add-on
Office 365 Enterprise E5 subscription (paid or trial version)
Office 365 A5 subscription (paid or trial version)
Office 365 Enterprise E3 subscription + the Office 365 Advanced Compliance add-on (no longer available for new subscriptions, see note)
Users included in communication compliance policies must be assigned one of the licenses above.


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @techangelsau Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
