### ISSUE TITLE
Incorrect Role

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#5856]
There is no role called "IB Compliance Management"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions - Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@danmyhre, I checked in two different E5 tenants. They both have it:

```powershell
PS C:\Users\chrisda> Get-ManagementRole "ib compliance management"

Name                     RoleType
----                     --------
IB Compliance Management IBComplianceManagement
```

The [info barriers topic](https://docs.microsoft.com/microsoft-365/compliance/information-barriers) mentions the following licensing requirements:

> Information barriers are rolling out now, and are included in subscriptions, such as:
> 
> - Microsoft 365 E5/A5
> - Office 365 E5/A5
> - Office 365 Advanced Compliance
> - Microsoft 365 Compliance E5/A5
> - Microsoft 365 Insider Risk Management

The **rolling out now** language makes me think the feature might not be available everywhere yet?

**Comment by danmyhre** [comment]
You are right @chrisda , I checked a few tenants and I have it too...not sure what happened earlier, must have missed it. Thanks for the quick response!
