### ISSUE TITLE
Typo in content

### ISSUE THREAD

**Issue by wdiggleCANCOM** [MicrosoftDocs/microsoft-365-docs#5862]
There appears to be a mistake in the content...

In the hairpin section it reads...  (such as security stack, cloud access broker, of cloud-based web gateway) 

Should it instead read... (such as security stack, cloud access broker, or cloud-based web gateway) 

Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4fd73b-9632-b0c1-45cb-825f2f1a03dd
* Version Independent ID: 8aeca19b-cf40-33c1-b947-f951a58e9520
* Content: [Microsoft 365 network connectivity principles - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-network-connectivity-principles?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-network-connectivity-principles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-network-connectivity-principles.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@wdiggleCANCOM Thank you for your feecback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5953

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @wdiggleCANCOM Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
