### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by wybesmits** [MicrosoftDocs/microsoft-365-docs#5863]
[Enter feedback here]
URL not working on: "For configuration steps, see **Use Microsoft OneDrive LTI with Canvas.**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 699da01d-e317-390b-cdb6-67ce21b80d30
* Version Independent ID: eeb105a1-d032-fdd5-3bef-6972fb2919f6
* Content: [An Overview to LTI Apps](https://docs.microsoft.com/en-us/microsoft-365/lti/?view=o365-worldwide#onedrive-lti-with-canvas)
* Content Source: [microsoft-365/lti/index.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lti/index.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by yogkumgit** [comment]
@wybesmits Closing as the PR comment. Thanks
