### ISSUE TITLE
Update doc to include info on Office 365 Threat Intelligence connection

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#5866]
[Enter feedback here]
In the M365 Defender portal, Settings > Endpoint > Advanced Features, there is a slider for turning on/off "Office 365 Threat Intelligence connection" and the link redirects to this page.  However this page has no mention of that setting or this integration at all.  Please update this doc with a description of what that integration does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4352228-5f34-5590-9721-a1d7cab2ac38
* Version Independent ID: 2a484437-5f3c-ab9f-b10e-67cd71f111a4
* Content: [Threat investigation & response capabilities - Microsoft Defender for Office 365 Plan 2 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-ti?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/office-365-ti.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-ti.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@jrhi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6038

Thanks
Sri

**Comment by yogkumgit** [comment]
@MSFTTracyP  PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jrhi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
