### ISSUE TITLE
Broken links...

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/microsoft-365-docs#5870]
Links to detailed information on this page are broken.
Eg: 
https://docs.microsoft.com/en-us/defender-endpoint/overview-endpoint-detection-response
https://docs.microsoft.com/en-us/defender-endpoint/overview-attack-surface-reduction
https://docs.microsoft.com/en-us/defender-endpoint/behavioral-blocking-containment
https://docs.microsoft.com/en-us/defender-endpoint/automated-investigations
https://docs.microsoft.com/en-us/defender-endpoint/advanced-hunting-overview
https://docs.microsoft.com/en-us/defender-endpoint/threat-analytics

etc....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e7ed6af-baba-eeb2-de6a-66048c2cfd07
* Version Independent ID: 0dff4d82-7586-7d8b-815d-cde8ea483c34
* Content: [Review Microsoft Defender for Endpoint architecture requirements and key concepts](https://docs.microsoft.com/en-us/microsoft-365/security/defender/eval-defender-endpoint-architecture?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/eval-defender-endpoint-architecture.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/eval-defender-endpoint-architecture.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@Rvvhub Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5954

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Rvvhub Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
