### ISSUE TITLE
Broken links throughout page

### ISSUE THREAD

**Issue by t3chn1ckmo** [MicrosoftDocs/microsoft-365-docs#5872]
Most links on this page are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17553211-2782-9631-14f7-728ed0bdb5ab
* Version Independent ID: 2badff24-1d2e-9902-3d32-493fd6ebe967
* Content: [Cloud-delivered protection Microsoft Defender Antivirus sample submission](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/cloud-protection-microsoft-antivirus-sample-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/cloud-protection-microsoft-antivirus-sample-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/cloud-protection-microsoft-antivirus-sample-submission.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@t3chn1ckmo Thank you for your feedback. I'm able to access all the links on this page. Could you please point out which link is broken?

Thanks
Sri

**Comment by msbemba** [comment]
@t3chn1ckmo Thank you for conforming and taking the time to submit feedback.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @t3chn1ckmo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
