### ISSUE TITLE
Incorrect examples

### ISSUE THREAD

**Issue by awaneet** [MicrosoftDocs/microsoft-365-docs#5873]
Incorrect examples

On the page https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide at very bottom in Search tips and tricks section it is mentioned "You can use only prefix searches; for example, \cat* or \set*. Suffix searches (*cat), infix searches (c*t), and substring searches (*cat*) are not supported." But the examples in brackets are wrong. Prefix should be \*cat or \*set and suffix should be \cat* or \set*. 

Thanks 
Awaneet
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@awaneet Thanks for feedback. But [earlier in this same topic](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide#search-operators), we define prefix searches (also call prefix matching) and use the same examples as the ones you cite. AFAIK, these are correct. Here is link to section in SPO KQL documentation about prefix matching, where asterix comes at the end; https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#wildcard-operator
