### ISSUE TITLE
Advanced hunting API page missing limit on max query result size in bytes

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5874]
If a query result is too large (in byte size, not rows), it will return HTTP 400 Bad Request with the message "Query execution has exceeded the allowed result size. Optimize your query by limiting the amount of results and try again". This value is not documented, but it appears to be limited to approximately 130 million bytes or 124MB. Please ensure all limitations with the advanced hunting API query are documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53a61a50-f7f2-f09a-a008-759c3afba97b
* Version Independent ID: 872c0e23-c626-3e22-efea-d4ef4ad7f32b
* Content: [Advanced Hunting API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-api?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-advanced-query-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-advanced-query-api.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5970

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
