### ISSUE TITLE
Batch update alerts does not show in left panel

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5875]
In the page content, one of the Alert methods is "Batch update alerts"; however, this does not show in the panel on the left side of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b65fe-28c7-42c1-ec6c-cffb63014eb9
* Version Independent ID: e23e1eac-de5e-7c99-2e46-89b4ffd32d4b
* Content: [Get alerts API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/alerts.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Checking with team. Thanks.

**Comment by mjcaparas** [comment]
Added to TOC via pr: #10199
