### ISSUE TITLE
Assessment export property lists not complete and not in the right case

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5877]
All properties on the main page and each specific assessment export page with the API calls are shown in the wrong case (upper vs. lowercase). The JSON response returns properties like "configurationCategory" and "osPlatform" rather than "ConfigurationCategory" and "OSPlatform". The file exports; however, do appear to use the case shown (starting with uppercase letter).

The list under the "Export secure configurations assessment" "Properties (JSON response)" section does not include "osVersion" and "rbacGroupId"; however, they appear in the real output of the API call. This is true for both the main assessment page and the specific page for "Export secure configuration assessment" (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-assessment-secure-config?view=o365-worldwide).

The list under the "Export software inventory assessment" "Properties (JSON response)" section does not include "rbacGroupId"; however, it appears in the real output of the API call. This is true for both the main assessment page and the specific page for "Export software inventory assessment" (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-assessment-software-inventory?view=o365-worldwide).

The list under the "Export software vulnerabilities assessment" "Properties (JSON response)" and "Properties (delta export JSON response)" sections do not include "rbacGroupId"; however, it appears in the real output of the API calls. This is true for both the main assessment page and the specific page for "Export software vulnerabilities assessment" (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-assessment-software-vulnerabilities?view=o365-worldwide).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57b8d46d-5e90-4b8b-c9c7-4beb77bb93ca
* Version Independent ID: 821c862e-673d-2b67-d055-d4aa86f4a1fb
* Content: [Export assessment methods and properties per device](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-assessment-methods-properties?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-assessment-methods-properties.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-assessment-methods-properties.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by MastaDisasta** [comment]
An additional item, in the "Export software inventory assessment" properties, it shows "id" as a valid field. However, this field does not appear to be in the actual output of the API call.

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6035

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
