### ISSUE TITLE
Investigation properties list shows wrong field

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5878]
The "Properties" section shows a field "investigationState"; however, the real value in actual results from the API call (and in the example on the page) is "state".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c31d3b-fd0b-46b7-5c3a-6ac0478bcbd4
* Version Independent ID: 521aeb41-4406-fd9d-441a-06b9361e91d5
* Content: [Investigation resource type](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/investigation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/investigation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/investigation.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5958

Thanks
Sri

**Comment by MastaDisasta** [comment]
@msbemba - thank you for the update, this appears to address the issue.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
