### ISSUE TITLE
List investigations OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5879]
The OData's $filter query is also supported on the "id" field; however, that is not listed. Additionally, $top and $skip are supported but not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3e1789-673f-3c48-0663-9f2ae8e2380c
* Version Independent ID: 8c5c0bd0-2a2c-c167-199a-11a5584e8803
* Content: [List Investigations API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-investigation-collection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-investigation-collection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-investigation-collection.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5978

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
