### ISSUE TITLE
Domain alerts response incorrect

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5880]
The "Response" section shows "If domain does not exist - 404 Not Found"; however, it appears to return 200 OK with an empty set. This was tested by using registered domains not in any alerts on the tenant, unregistered domains that could be legitimate if registered, and domains that had TLDs that are invalid. All returned 200 OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51cc644d-9bdd-a132-070d-1958ebcb174b
* Version Independent ID: 5853bd71-85fd-3df4-bfeb-535857b71cad
* Content: [Get domain-related alerts API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-domain-related-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-domain-related-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-domain-related-alerts.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6026

Thanks
Sri
