### ISSUE TITLE
Domain machines response incorrect

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5881]
The "Response" section shows "If domain do not exist - 404 Not Found"; however, it appears to return 200 OK with an empty set. This was tested by using registered domains not in any alerts on the tenant, unregistered domains that could be legitimate if registered, and domains that had TLDs that are invalid. All returned 200 OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776417af-7b1e-8829-5143-7f7f3e700292
* Version Independent ID: 0e18b1a2-3c61-dab6-f3f8-146aac8802a4
* Content: [Get domain related machines API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-domain-related-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-domain-related-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-domain-related-machines.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6025

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
