### ISSUE TITLE
Domain statistics response incorrect

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5882]
The "Response" section shows "If domain does not exist - 404 Not Found"; however, it appears to return 200 OK with an prevalence of 0 and first and last seen null. This was tested by using registered domains not in any alerts on the tenant, unregistered domains that could be legitimate if registered, and domains that had TLDs that are invalid. All returned 200 OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eae16f9-5929-ae70-8356-4bcea2380be0
* Version Independent ID: a8c5ee2a-6c0c-0e1d-18e1-471fa7b37085
* Content: [Get domain statistics API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-domain-statistics?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-domain-statistics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-domain-statistics.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6023

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
