### ISSUE TITLE
File alerts limitations not documented, response incorrect

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5884]
In the API description, this shows "Retrieves a collection of alerts related to a given file hash." However, it does not specify the hash type. It appears only SHA-1 is supported (not MD5 or SHA-256).

The "Response" section shows "If file does not exist - 404 Not Found"; however, it appears to return 200 OK with an empty set. This was tested by using random hash values like "1111111111111111111111111111111111111111".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffef2800-e821-264c-c24d-3e114fd8c0dd
* Version Independent ID: 7e924df1-9c4b-e357-6b22-2ece52956952
* Content: [Get file-related alerts API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-file-related-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-file-related-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-file-related-alerts.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5980

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
