### ISSUE TITLE
File machines limitations not documented, response incorrect

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5885]
In the API description, this shows "Retrieves a collection of Machines related to a given file hash." However, it does not specify the hash type. It appears only SHA-1 is supported (not MD5 or SHA-256).

The "Response" section shows "If file does not exist - 404 Not Found"; however, it appears to return 200 OK with an empty set. This was tested by using random hash values like "1111111111111111111111111111111111111111".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af9f9f80-f385-09be-0614-13dfa1d50100
* Version Independent ID: c0fa3b9c-af79-4fec-6b27-515d7c2ffe7d
* Content: [Get file-related machines API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-file-related-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-file-related-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-file-related-machines.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5979

Once the author approves the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
