### ISSUE TITLE
File statistics lookBackHours limitation not documented, duplicate fields

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5886]
The documentation does not show a maximum for "lookBackHours"; however, it appears to be 720 hours (30 days).

There appear to be duplicate fields for org and global prevalence. The "organizationPrevalence" and "orgPrevalence" fields appear to both show how many devices the file was seen on within the tenant. The "globalPrevalence" and "globallyPrevalence" fields appear to both show how many devices the file was seen on across all tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8ca30c-5aa2-2f82-9d16-9443152cb78e
* Version Independent ID: 83ef1d76-1149-7d34-4f70-7255ac5921aa
* Content: [Get file statistics API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-file-statistics?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-file-statistics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-file-statistics.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
