### ISSUE TITLE
List indicators OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5889]
The OData's $filter query is also supported on the "application", "createdByDisplayName", "expirationTime", "generateAlert", "title", "rbacGroupNames", and "rbacGroupIds" fields; however, those are not listed. Additionally, $top and $skip are supported but not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e304063-f223-fab7-6a40-65798b0860d2
* Version Independent ID: c010a94b-b837-c7ad-5424-ef706ce54a70
* Content: [List Indicators API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-ti-indicators-collection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-ti-indicators-collection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-ti-indicators-collection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6004

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
