### ISSUE TITLE
Submit/update indicator options

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5890]
The "Response body" section does not have a complete list of supported parameters and values. See https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5887 for related info.

- Incomplete list of valid values for "indicatorType". At least "FileMd5" and "CertificateThumbprint" are valid but not documented. Unsure of other possible values.
- Incomplete list of valid values for "action". At least "Warn", "Block", "Audit", and "BlockAndRemediate" are valid but not documented. Unsure of other possible values.

Additionally, the following fields are valid but not documented:
- category
- educateUrl
- bypassDurationHours
- notificationId
- notificationBody
- version
- mitreTechniques
- historicalDetection (if enabled on tenant)
- lookBackPeriod (if enabled on tenant)
- generateAlert
- additionalInfo
- externalId
- certificateInfo

The "application" field is documented as updatable but it will only work for new indicators, it will not update the value on an existing indicator. Additionally, the "version" and "certificateInfo" fields which are undocumented can only be used for submitting new indicators and will not update the value on an existing indicator.

Also, I'm not sure if it's the intended behavior of the API, but if you submit an update to an existing indicatorValue but change the action, such as from "Alert" to "Block", it will create a duplicate indicator rather than updating the existing one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea229ca-05ce-38c5-003e-4d811b0bed25
* Version Independent ID: 765b3d95-745c-357b-b19e-87ee0b0a1661
* Content: [Submit or Update Indicator API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/post-ti-indicator?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/post-ti-indicator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/post-ti-indicator.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by MastaDisasta** [comment]
One additional item is that the documentation says "rbacGroupNames" is of type String; however, in the example and through testing the API, it appears this field should be submitted as a list of strings rather than a single string separated by commas.

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6199

There are other changes that will be made once the author gets more information from the engineering team.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
