### ISSUE TITLE
IP address alerts

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5891]
The response shows "If IP do not exist - 404 Not Found." However, if the IP address is unknown but valid, it will return an empty set. If the IP address is invalid, e.g. 256.x.x.x, it will return HTTP 400.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6acd9b19-5308-1fb5-9e40-8d7d94e3b16f
* Version Independent ID: 1a2508f0-8038-9ace-1dd9-c9923ec35130
* Content: [Get IP related alerts API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-ip-related-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-ip-related-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-ip-related-alerts.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5972

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
