### ISSUE TITLE
IP address statistics lookBackHours limitation not documented, duplicate fields, incorrect response

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5892]
The documentation does not show a maximum for "lookBackHours"; however, it appears to be 720 hours (30 days).

There appear to be duplicate fields for org prevalence. The "organizationPrevalence" and "orgPrevalence" fields appear to both show how many devices the IP address was seen on within the tenant.

The response shows "IP do not exist - 404 Not Found." However, if the IP address is unknown but valid, it will return prevalence of 0. If the IP address is invalid, e.g. 256.x.x.x, it will return HTTP 400.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0657f4eb-c983-aaad-1d51-fcf06a03cce1
* Version Independent ID: a136757c-5fc9-6db1-c9b1-4b13163dc387
* Content: [Get IP statistics API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-ip-statistics?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-ip-statistics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-ip-statistics.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5982

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
