### ISSUE TITLE
Machine properties incorrect

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5893]
The "Properties" show "exposureScore"; however, that field does not actually exist. The correct field is "exposureLevel". Additionally, there is a field "rbacGroupName" but not "rbacGroupId" even though when using the list machines API call, it is filterable on ID but not name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71010864-b3f8-23e1-33fe-496f136bf2b7
* Version Independent ID: e4c58cda-d42f-4445-3a03-6f4c8c1e6460
* Content: [Machine resource type](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
@msbemba - I believe this is similar to the other issues. Can you help?

**Comment by msbemba** [comment]
Yes, I can handle this.

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6031

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
