### ISSUE TITLE
List machines OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5894]
The OData's $filter query is also supported on the "id", "version", "lastIpAddress", "exposureLevel", "deviceValue", "aadDeviceId", and "machineTags" fields; however, those are not listed. Additionally, $top and $skip are supported but not listed.

Also, the field "rbacGroupId" is filterable even though it is not a field in the Machine output. The field in the output is "rbacGroupName" which is not filterable. See https://github.com/MicrosoftDocs/microsoft-365-docs/issues/5893

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07828149-8c9b-2b6f-b5f6-9558cfcfa650
* Version Independent ID: 2101b098-7da1-86ca-6a31-fddfa7a5cb62
* Content: [List machines API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-machines.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
@msbemba - I believe this is similar to the other issues. Can you help?

**Comment by msbemba** [comment]
Yes, I can handle this.

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6032

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
