### ISSUE TITLE
Update machine incorrect limitation and response

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5895]
Under "Limitations", this shows "Update machine only appends tags to the tag collection" and under "Response", this shows "If machine tags collection in body doesn't contain existing machine tags - 400 Invalid Input and a message informing of the missing tag/s." However, the API call does not return HTTP 400 error or append the tags. It replaces all tags with the tags provided in the request body. So, if the existing tags are "tag1" and "tag2" and the request body only has "tag3", it removes the first two tags and adds the third tag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de75f8e0-de5a-d4b2-b1ec-b720115ef6ae
* Version Independent ID: 41a298e5-65fe-8a4b-ca34-bb0390005dbd
* Content: [Update machine entity API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/update-machine-method?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/update-machine-method.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/update-machine-method.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6033

Once the author approves the PR, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
