### ISSUE TITLE
Machine actions incomplete properties

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5896]
The documentation shows the list of possible values for "type"; however, the value "Live Response" is not documented but shows in real output. Unsure if other undocumented values exist.

The documentation shows the list of possible values for "status"; however, "Canceled" is not a valid status, the correct value is "Cancelled" (two L's).

The value "lastUpdateTimeUtc" is documented, but it does not exist. The real field is "lastUpdateDateTimeUtc" (listed below).

Additionally, the following fields are not documented but are returned in real output:
- lastUpdateDateTimeUtc
- title
- cancellationRequestor
- cancellationComment
- cancellationDateTimeUtc
- errorHResult
- externalId
- requestSource
- commands
- troubleshootInfo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b878866-1f3c-cdca-08c2-caab294b3815
* Version Independent ID: a6054c77-7c3f-adeb-dfea-651f7b399da5
* Content: [machineAction resource type](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machineaction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machineaction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machineaction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have created a PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6034 for the same.

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
