### ISSUE TITLE
List machine actions OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5899]
The OData's $filter query is also supported on the "id" field; however, it is not listed. Additionally, $top and $skip are supported but not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a592758-861c-92ee-e2bf-a1c7fd4773f0
* Version Independent ID: 9a44a6f5-58eb-0df5-b572-bd1c318cce9d
* Content: [List machineActions API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machineactions-collection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-machineactions-collection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-machineactions-collection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5998

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
