### ISSUE TITLE
Incorrect referral to DNS record type (A instead of TXT) 

### ISSUE THREAD

**Issue by MichelvanVliet** [MicrosoftDocs/microsoft-365-docs#590]
In this article the following is listed:

The CNAME records in your DNS will point to already created A records that exist in DNS on the Microsoft DNS servers for Office 365.

However the DNS records which are created on the Microsoft DNS servers are actually TXT records.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [Use DKIM for email in your custom domain in Office 365, 2048-bit, 1024-bit, steps, How it works, SPF, DMARC](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email#feedback)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@MichelvanVliet  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by greg-lindsay** [comment]
Hi - this isn't my article, but I thought I would comment.

Although DKIM are TXT records, the sentence you are referring to isn't talking about DKIM records. It is talking about A records that are used to create CNAMEs as a prerequisite to creating DKIM records.

**Comment by MaratMussabekov** [comment]
Dear @greg-lindsay,
I've never seen the A record that was created in onmicrosoft.com DNS zone for DKIM, are you sure about this prerequisite A record?
Could you please have a look at the following article - https://www.altitude365.com/2018/11/09/enable-dkim-for-a-custom-domain-in-office-365-in-five-simple-steps/
The good thing about this article is that the records described there are actually exist.
The author created the CNAME record, and a TXT record selector2-altitude365-se._domainkey.altitude365.onmicrosoft.com was created in onmicrosoft.com DNS zone.
There is no any A record there for this name.
For example, please check there - https://network-tools.com/dns-records/#search=dns&search=selector2-altitude365-se._domainkey.altitude365.onmicrosoft.com&target=dns_20&form=ntscform&base10toip=false

Thank you

**Comment by mypil** [comment]
@MichelvanVliet - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/a0fb4f28c694be68fc0692f7079925cc54bbbb1a. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
