### ISSUE TITLE
Get investigation package URL undocumented limitation/response

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5901]
If the machine action for the collection exists but is not complete, this will return 404 Not Found, but that response is not documented.

Additionally, there is no API call limit specified, but it appears to be 2 calls per minute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8946a2-a2ea-1dc7-a6ce-13c56d11b485
* Version Independent ID: 9de7a1fa-d8d9-4ea6-33fc-7e50528b1c04
* Content: [Get package SAS URI API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-package-sas-uri?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-package-sas-uri.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-package-sas-uri.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5996

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
