### ISSUE TITLE
Get live response result incorrect reponse

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5902]
The documentation shows the response will include "name" and "script_error"; however, the real values are "script_name" and "script_errors".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd8827-66cd-625d-a992-d42ec38ce0d6
* Version Independent ID: 67e04899-ef6e-20d3-8aec-d1765349bc32
* Content: [Get live response results](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-live-response-result?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-live-response-result.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-live-response-result.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5957

Thanks
Sri

**Comment by MastaDisasta** [comment]
@msbemba - thank you for the reply and fixing the property value for "script_name". However, the property "script_error" should be "script_errors" (with an 's' at the end) as well. Thank you.

**Comment by msbemba** [comment]
@MastaDisasta Thank you. I have updated the PR.
