### ISSUE TITLE
Isolate device incorrect response

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5903]
The following is not documented as a limitation or response:
When you send multiple API calls to isolate the same device, there are inconsistent results. It may depend on how much time has passed since you last issued an isolate API call. Some duplicate calls returned the pending machine action instead of a new machine action and some duplicate calls returned HTTP 400 with the message "Action is already in progress". Additionally, if the machine is already isolated (or pending isolation) and you send a duplicate isolate API call, the new machine action will be stuck in the "pending" status even if you later submit another API call to remove isolation. Also, the remove isolation action can only be performed over the API as the pending duplicate isolation action makes it so the portal thinks isolation is still pending (and the option to remove is grayed out).

It appears the duplicate action that was stuck in pending status was only completed after duplicate remove isolation API calls were made. The order of API calls was: "isolate", "isolate", "remove isolation", "remove isolation" but the order of completion was "isolate", "remove isolation", "remove isolation", "isolate" resulting in the device still being isolated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2484bbe8-9fd4-cfcd-b9fe-73e1a0ee249c
* Version Independent ID: d6079609-ea2a-d6f9-6170-eb8e02f76a1e
* Content: [Isolate machine API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/isolate-machine?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/isolate-machine.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/isolate-machine.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. I'm working with the author on this.

Thanks
Sri

**Comment by mjcaparas** [comment]
This sounds like there's a required programmatic change. Please submit feedback through the portal using the frown button.
