### ISSUE TITLE
Remove isolation incorrect limitations/response

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5904]
The following is not documented as a limitation or response:
When you send multiple API calls to remove isolation for the same device, there are inconsistent results. It may depend on how much time has passed since you last issued the associated API call. Some duplicate calls returned the pending machine action instead of a new machine action and some duplicate calls returned HTTP 400 with the message "Action is already in progress". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f1b4014-7546-1d8a-0879-c55c0c113171
* Version Independent ID: 497244b3-4e95-456b-6ffa-e02b5085248a
* Content: [Release device from isolation API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/unisolate-machine?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/unisolate-machine.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/unisolate-machine.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document  via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5995

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
