### ISSUE TITLE
Remove app restriction incorrect limitations/response

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5906]
The following is not documented as a limitation or response:
When you send multiple API calls to remove app restriction for the same device, there are inconsistent results. It may depend on how much time has passed since you last issued the associated API call. Some duplicate calls returned the pending machine action instead of a new machine action and some duplicate calls returned HTTP 400 with the message "Action is already in progress".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70c49ba4-b953-8b93-6e2e-76eb68d26e4a
* Version Independent ID: 32830f76-070c-f0cb-6cab-988ae8504731
* Content: [Remove app restriction API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/unrestrict-code-execution?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/unrestrict-code-execution.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/unrestrict-code-execution.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5993

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
