### ISSUE TITLE
Run live response incorrect limitations/response

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5908]
When you send multiple API calls to run different live response commands for the same device, it returns HTTP 400 with the message "Action is already in progress". It should be documented that live response commands cannot be queued up and can only be executed one at a time (the documented workaround is to include multiple commands in a single API call, but that has the limitation of if one command fails, all following commands are not executed).

Additionally, the documentation shows successful API calls will return 200 OK, but it appears to actually return 201 Created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3e5349-9b67-18ff-6c1c-d123b1f21a72
* Version Independent ID: fe100af9-381b-8b0f-cd7b-94ac62b6b313
* Content: [Run live response commands on a device](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-live-response?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-live-response.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-live-response.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5973

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
