### ISSUE TITLE
Sharing with OneDrive

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#591]
Hello,
While testing DLP, when sharing file from Desktop/OneDrive, simply right mouse click and choose Share, then OneDrive sharing window appear,
When sharing sensitive data to external source, a message showed that sharing will be blocked and there is a link "Show policy tip", when clicking on that link, then a message appears "Policy tip couldn't be displayed. Please try again."
Were trying to find information regards this "sharing" option, but can't find..
It would be good to explain if possible to modify this specific policy tip and update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by lightupdifire** [comment]
Print screen attached: 

![Untitled](https://user-images.githubusercontent.com/39700914/67281701-4df83d80-f4d0-11e9-81dc-1494fef6ec56.png)

**Comment by mypil** [comment]
@lightupdifire  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by lightupdifire** [comment]
Hello,
Seems the same happening if do:

1. Used OneDrive with KFM
2. From desktop, open Word document with sensitive data using Word app
3. From Word try share file
4. Policy tip showed with link "view policy tip"
5. Click on "view policy tip" give a message: "Policy tip couldn't be displayed. Please try again."
![image](https://user-images.githubusercontent.com/39700914/67369869-0fb75880-f57a-11e9-902a-4f0e6804bdcb.png)

**Comment by lightupdifire** [comment]
Hello,
During tests found strange behavior:
1. When sharing files from SharePoint sites, using OneDrive client or directly Online or from OneDrive mobile app - "view policy tip" works fine
2. When sharing files from OneDrive, using OneDrive client or directly Online or from OneDrive mobile app - "view policy tip" not working

**Comment by lightupdifire** [comment]
Hello,
We were troubleshooting with O365 Support, they confirmed that same happening on the MS test platform, so it is something related to "technical" and not to the "document", closing case.

**Comment by lightupdifire** [comment]
I will again recommend, if possible, please try add FAQ/Known issues documentation, this is not the first time when I find some issues from the technical side and then troubleshoot myself and find some answers that are related to the technical issues. I understand that it is maybe not nice, to publish "Product" with known issues, but then add a "working plan" for those issues resolution process/progress, etc..
But if FAQ would be here, I could quickly understand what known issues now and wouldn't spend my time, time of MS support on investigating a "product" productivity, this makes product view more badly because investigation takes a lot of effort. Also, we might just wait with a product deployment until some issues are resolved or accept some risks but we would be aware of issues...
