### ISSUE TITLE
Recommendation properties incomplete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5910]
The list under the "Properties" section does not include "recommendedVendor" and "recommendedProgram"; however, these show in actual output.

Additionally, a field is documented as "exposureImpacte", but the correct field appears to be "exposureImpact".

Also, the possible values for "recommendationCategory" includes "SecurityStack", but the correct value appears to be "Security controls".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d80863-ef08-945f-148e-3818b580fa70
* Version Independent ID: 796f462f-063c-7985-19cc-10fac7980c82
* Content: [Recommendation methods and properties](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/recommendation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/recommendation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/recommendation.md)
* Product: **m365-security**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5991

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
