### ISSUE TITLE
Failed to change payment method

### ISSUE THREAD

**Issue by clix5cash** [MicrosoftDocs/microsoft-365-docs#5913]
I have an email purchased via Godaddy and have purchased the SharePoint which has not used for months after a month testing and need to be unsubscribed. The issue is I could not access to the Microsoft 365 admin center to change the subscription as it alway to redirect to Godaddy site when click to admin tab to change the payment method as guidance.
Redirect page link: https://productivity.godaddy.com/settings#/mailbox/13306604
I have contacted Godaddy support but they could not solve and advise to contact MS.
How can I unsubscribe the SharePoint that not use anymore if I could not access to my admin?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14e33d-0d3e-45f4-fefe-dec3ae7d351f
* Version Independent ID: aeb53e2c-d35c-73fe-26f2-4f101bfeeea7
* Content: [Manage payment methods](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-payment-methods?view=o365-worldwide#change-a-payment-method-for-a-single-subscription)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-payment-methods.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-payment-methods.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@clix5cash Thank you for your feedback. If the Subscription was purchased through Go-daddy, You will not have access to manage payment methods nor the m365 admin center to access the payment section. 

If the subscription was purchased through Go daddy, they will be able to help unsubscribe or remove the subscription.

Hope this helps!

Thanks
Sri

**Comment by clix5cash** [comment]
Thanks. The subscription sharepoint was purchased from MS, only my e-mail account was purchased from GDD so they could not help to solve this issue.

**Comment by msbemba** [comment]
@clix5cash This needs to be addressed by the billing team. I'd recommend you contact Microsoft Billing support via the need help section on the admin center. 

@yogkumgit  There are no changes required in this document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @clix5cash Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
