### ISSUE TITLE
@matuhinal Thank you for your feedback. I reviewed the document and could not find anything incorrect or needs modification. DNS records help the Internet send emails to the right place so let us know how we can help you modify or explain this document?

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/microsoft-365-docs#5915]
@matuhinal Thank you for your feedback. I reviewed the document and could not find anything incorrect or needs modification. DNS records help the Internet send emails to the right place so let us know how we can help you modify or explain this document?

Thanks
Sri

_Originally posted by @msbemba in https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3324#issuecomment-721387872_

**Comment by matuhinal** [comment]
Все же требуется объяснение для подключения новых доменных имен на портале техподдержки M365

**Comment by denisebmsft** [comment]
Translated @matuhinal's comment:

Still requires an explanation to connect the new domain names in the M365 support portal

**Comment by msbemba** [comment]
Thank you @denisebmsft 

@matuhinal Thank you for your feedback. This document talks only about DNS Basics. For more information on how to connect new domain names in M365 Admin center/ Admin portal - Please follow -https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?view=o365-worldwide


Follow these steps to add, set up, or continue setting up a domain.

Go to the admin center at https://admin.microsoft.com.
Go to the Settings > Domains page.
Select Add domain.
Enter the name of the domain you want to add, then select Next.
Verify the domain
Add DNS Records
Finish

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @matuhinal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
