### ISSUE TITLE
List recommendations OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5921]
The OData's $filter query is not documented for the list recommendations API call, but it is supported on the following fields:
- id
- productName
- vendor
- recommendedVersion
- recommendationCategory
- subCategory
- severityScore
- remediationType
- status
- recommendedVendor
- recommendedProgram

Additionally, $top and $skip are supported but not listed.

Also, with other API calls that support OData queries, the error messages are more descriptive; however, with this call, the error is generic "Filter parameter is invalid" to mean both the field is not valid for filtering and the filter was malformed/the types don't match

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 839aff5a-5f31-8453-2c59-0fefdd5741c7
* Version Independent ID: 643df190-bddc-33ef-d89f-5bd40040f8ff
* Content: [List all recommendations](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-all-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-all-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-all-recommendations.md)
* Product: **m365-security**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by yogkumgit** [comment]
@DulceMontemayor Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@DulceMontemayor  PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
