### ISSUE TITLE
Page does not match

### ISSUE THREAD

**Issue by ryancanfield** [MicrosoftDocs/microsoft-365-docs#5922]
The description on the page does not match the current version of https://compliance.microsoft.com/info.

There is no "show all", there is no "content search". I do have limited permissions on this page, so that might be part of the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e514aa-9f04-5cc9-93f6-9f5f2f614c2a
* Version Independent ID: dea1ab15-bc09-05c1-b48b-1a06c0b53b50
* Content: [Create and run a Content search in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ryancanfield Thanks for the heads up about Show all. This used to be the navigation path when the Microsoft 365 compliance center was initially released, but looks to be updated. I'll update the article. Until then, you could also try the direct URL: https://compliance.microsoft.com/contentsearch

You are correct to assume that you need to be assigned the Compliance Search role in the compliance center to access the content search tool. For more info about eDiscovery permissions, see: https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions?view=o365-worldwide#rbac-roles-related-to-ediscovery

**Comment by markjjo** [comment]
@ryancanfield Correction: direct URL is https://compliance.microsoft.com/contentsearchv2
