### ISSUE TITLE
List remediation activity OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5924]
The OData's $filter query is not documented for the list remediation activity API call, but it is supported on the following fields:
- createdOn
- status

Additionally, $top and $skip are not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef23eda-5f78-cdcf-ec94-ea5db4734a84
* Version Independent ID: 8b5f28a6-e988-e992-a49e-1d99b3d3687e
* Content: [List all remediation activities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-remediation-all-activities?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-remediation-all-activities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-remediation-all-activities.md)
* Product: **m365-security**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5990

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
