### ISSUE TITLE
Score properties incomplete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5925]
The list under the "Properties" section does not include "rbacGroupId"; however, it shows in actual output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34a2a1df-c601-eb2b-66c6-2dcfcd6bee54
* Version Independent ID: 80180d1e-8d1c-2091-bde9-96b3fae9b51f
* Content: [Score methods and properties](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/score?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/score.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5989

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
