### ISSUE TITLE
List exposure score incorrect description

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5926]
The description says "Retrieves a collection of alerts related to a given domain address."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b03ca33-d760-68fe-15d0-13de7deb27fd
* Version Independent ID: c1df280f-d9e5-975c-e231-ace08a3023d4
* Content: [List exposure score by device group](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machine-group-exposure-score?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-machine-group-exposure-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-machine-group-exposure-score.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5955

Thanks
Sri

**Comment by MastaDisasta** [comment]
@msbemba - thank you for the reply. However, I believe the correct description should be "Retrieves the exposure score for each machine group" rather than retrieves alerts. Here is example output from the API call. I only have one RBAC group, but I imagine this would have multiple entries if I had more RBAC groups.

```
{
"@odata.context":"https://api.securitycenter.microsoft.com/api/$metadata#ExposureScore",
"value":[
  {
  "time":"2021-08-11T05:20:31.2624445Z",
  "score":65.96521739130435,
  "rbacGroupName":null,
  "rbacGroupId":0
}]
}
```

**Comment by msbemba** [comment]
@MastaDisasta I have updated the PR. Thanks again.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
