### ISSUE TITLE
Get user related alerts incorrect response

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5927]
The "Response" section shows "If the user does not exist - 404 Not Found." However, it appears if the user does not exist, it will return 200 OK with an empty set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8aa7cc-c6e3-4233-dba1-ce65ab92e9cb
* Version Independent ID: 7af0a421-72ca-a339-eab3-b2e2cb7bd139
* Content: [Get user-related alerts API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-user-related-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-user-related-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-user-related-alerts.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5988

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
