### ISSUE TITLE
Integration with Sentinel

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#593]
Given that Sentinel is GA and that it ingests O365 data for no cost, it would make sense to add some information to this page about this SIEM provided by Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dfa4781-2270-ba4e-ff3e-d659b5850a3a
* Version Independent ID: ee2ee461-805f-76b4-334c-3be362b1c4e1
* Content: [SIEM server integration with Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/siem-server-integration)
* Content Source: [microsoft-365/security/office-365-security/siem-server-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/siem-server-integration.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by Dansimp** [comment]
@DeanGross, is this what you are looking for? Or specifically Office 365 ATP? https://docs.microsoft.com/en-us/azure/sentinel/connect-office-365

**Comment by DeanGross** [comment]
thanks, sorry, i was not very clear. There is a table on this page that lists several other SIEMs but it does not include Sentinel. I think that it would be helpful to add something so that people will be informed about this new integration opportunity.

**Comment by mypil** [comment]
@denisebmsft - Can you please share your insights on this issue?

Thank you.

**Comment by denisebmsft** [comment]
@DeanGross thank you for raising this issue, and @mypil thank you for helping address it. I have revised the article to now include links to Azure Sentinel information. I hope this helps! I am going to close this issue for now, as the content is live, but please let me know if anything else is needed.
