### ISSUE TITLE
Vulnerabilities incomplete methods

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5930]
The "Methods" section does not include "List vulnerabilities by machine and software" even though it is in the left panel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fde81ac4-accc-9a93-90fb-62bbe9a66326
* Version Independent ID: 130d79fe-73d0-14f6-3b44-e9cbae763837
* Content: [Vulnerability methods and properties](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/vulnerability?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/vulnerability.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/vulnerability.md)
* Product: **m365-security**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5956

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MastaDisasta Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
