### ISSUE TITLE
List vulnerability by machine and software OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5931]
It states the "The OData $filter is supported on all properties." However, this API call actually has a different set of returned properties than the base "list all vulnerabilities" properties, and these properties are not specifically documented (other than the example result on this page). Additionally, $top and $skip are supported but not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7fff2b4-1c3e-b8e7-aa06-f02da48a970a
* Version Independent ID: 39144698-6ab3-7eb6-b253-eaf498803678
* Content: [Get all vulnerabilities by machine and software](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-all-vulnerabilities-by-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-all-vulnerabilities-by-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-all-vulnerabilities-by-machines.md)
* Product: **m365-security**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6068

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
