### ISSUE TITLE
Remove the SIEM mention under note for Mac and Linux

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/microsoft-365-docs#5932]
The "Note" under Mac and Linux that mentions "SIEM" should be removed.  SIEM is supported as all data that flows into MDE can be sent to a SIEM.  Confirmed with Helen Allas.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e914c02a-e905-fc32-439c-feb1fafa09b8
* Version Independent ID: 1a6a15e9-717a-33c1-b90e-96925c680228
* Content: [Microsoft Defender for Endpoint for non-Windows platforms](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/non-windows?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/non-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/non-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jmmowrer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5943

Once the author approves the PR, the change will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jmmowrer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
