### ISSUE TITLE
List vulnerabilities OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5933]
The OData's $filter query is not documented for the list vulnerabilities API call, but it is supported on the following fields:
- id
- name
- description
- severity
- cvssV3
- publishedOn
- updatedOn

Additionally, $top and $skip are not listed but are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa36594-d122-8490-9c17-bc310e8e8431
* Version Independent ID: 9eeae5b3-e864-49bb-cba0-df3e6fcb2906
* Content: [Get all vulnerabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-all-vulnerabilities?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-all-vulnerabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-all-vulnerabilities.md)
* Product: **m365-security**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5987

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
