### ISSUE TITLE
List software OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5934]
The OData's $filter query is not documented for the list software API call, but it is supported on the following fields:
- id
- name
- vendor

Additionally, $top and $skip are not listed but are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aabaf97f-4313-dc71-8fdb-69349dd08ed1
* Version Independent ID: c17beb7f-e5df-fce8-0e03-dcd2a0a8d6c3
* Content: [List software](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-software?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-software.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-software.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5986

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
