### ISSUE TITLE
Repeated Instructions for Steps to Cancel Your Subscription

### ISSUE THREAD

**Issue by ayan-b** [MicrosoftDocs/microsoft-365-docs#5935]
The highlighted part is repeated (point 3 to 5).

![image](https://user-images.githubusercontent.com/29725587/128751720-83f8148a-4a22-4460-b49a-06a8c7f02a51.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a91e3ae5-842c-fb3d-8c27-d8001122aee8
* Version Independent ID: ddccec72-7088-4207-60cb-986a35becb67
* Content: [Cancel your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/cancel-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/cancel-your-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@ayan-b Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5944

Thanks
Sri

**Comment by yogkumgit** [comment]
@ayan-b Author confirmed, issue is fixed. If you see any other documentation update, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
