### ISSUE TITLE
List alerts OData options not complete

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#5937]
The OData's $filter query is also supported on the "id", "asssignedTo", "detectionSource", and "lastEventTime" fields; however, those are not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c484780-4288-59e1-d30a-ab4460a34537
* Version Independent ID: d347c3bd-6e5f-b22b-4e30-eb4588f6bda2
* Content: [List alerts API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-alerts.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
