### ISSUE TITLE
How2 configure blocking non-compliant emails? How to drill down DLP activity?

### ISSUE THREAD

**Issue by hb-webdev** [MicrosoftDocs/microsoft-365-docs#5938]
Why does my DLP Activity Explorer successfully show a bar graph of offenses, but I can't drill down to see specifics? (Below the bar graph it says "No data available".)
![image](https://user-images.githubusercontent.com/85006632/128758626-f8498bf2-22cf-4342-9b8e-6d730bd7e9e2.png)

I still don't understand how to determine if a DLP policy is configured to block emails from going through or where to override any blocked emails. Does the setting below block the email from getting sent at all?
![image](https://user-images.githubusercontent.com/85006632/128759198-ebd91c74-b444-4fe5-8e69-042e38f644bc.png)

We had a user trigger this policy & get a "Notification: " (in the Subject line) DLP email back when he tried sending an email with a couple .pdf's attached. Apparently attaching a couple .pdf's is considered sharing "Content from Microsoft 365"? I guess 'cause the email is going through Exchange? ("Applies only to content shared from **Exchange, SharePoint, OneDrive, and Teams**.")
![image](https://user-images.githubusercontent.com/85006632/128759453-d0daf381-22b9-4461-beb5-075fb1f82b55.png)

Also, if a policy is only configured to "Notify" (and not block), why is there a toggle under "User override"? Why would you need to "override" a simple notification? Also, the note says you _can't_ override any Microsoft 365 content anyway ("Users won't be able to override policy restrictions in **Exchange, SharePoint, OneDrive, Teams**, and On Premises Scanner."), which is the only type of content that triggers this policy in the first place...so is this toggle doubly useless?
![image](https://user-images.githubusercontent.com/85006632/128759633-d09c695f-277d-4559-9c10-18d417347c21.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide#default-email-notification)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks
