### ISSUE TITLE
ETRs can not be created to encrypt inbound external email

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/microsoft-365-docs#594]
There is presently a defect in the ETR UI that allows admins to choose the option to create an ETR that encrypts inbound mail from external senders.  The examples in this doc are all correct because none of them conflict with this limitation, however the fact that inbound external email is out of scope of ETRs is not evident.

Even when the UI defect is eventually resolved (and hopefully the PowerShell cmdlet too), it is still worth mentioning the above limitation so it is clearly understood, and so nobody decides to open a support case for clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0e7a9a-356a-724b-77ab-41a3c456154b
* Version Independent ID: 78ce0ee4-bd8f-4cfa-cea4-170af5d21aff
* Content: [Define mail flow rules to encrypt email messages in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email#feedback)
* Content Source: [microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@mrkeiths  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mrkeiths** [comment]
@mypil thank you.  FYI. You may wish to reconsider waiting b/c even though there is a fix planned to block admins from creating such a transport rule... if such a rule is created, it will NOT work.

The ETR will fire and can be seen in message trace detail but even though encryption is said to have been applied, it really hasn't.  It might be better to inform people not to create such a rule now in this doc, even though the UI/pshell permit creating a non-working rule.

**Comment by joinimran** [comment]
@mrkeiths - Thank you for your feedback. Can you please correct me if my understanding is wrong?

You basically wanted to say that ETR that encrypts inbound mail from external senders doesn't work and this is out of the scope of this article.

Or let me know what exactly should be added as note in the document so that I can make necessary changes in the document. 

Thanks.

**Comment by mrkeiths** [comment]
Hello Imran,

 

Apologies for the late response.

 

Right now it is possible to create an ETR that is configured to encrypt inbound external email due to the open defects I shared.

 

Right now if such a rule is created, it will not work as the admin probably expects.  Get-MessageTraceDetail may indicate the ETR was triggered (an Action to “Rights protect message” will appear in the trace details) but encryption is not applied to the message.

 

The product group shared that the ETR logic is working correctly (the solution design is not supposed to support encrypting inbound external email).  The problems right now are the EAC web UI and pshell cmdlets do not correctly enforce the solution design constraint.

 

 

I am suggesting a note be added in the section titled “Create mail flow rules to encrypt email messages with the new OME capabilities” to clarify external inbound email cannot be encrypted using a mail flow rule and OME, and that this limitation is by design.

 

My opinion is that even after the UI/pshell defects are corrected, it will be helpful for admins to understand the option is purposefully not available.

 

Thanks for reaching out to get clarification.

 

Regards,

Keith

**Comment by mypil** [comment]
@mrkeiths - The author added this info in the doc, kindly refer to https://github.com/MicrosoftDocs/microsoft-365-docs/pull/756#issuecomment-555745612.

We appreciate your effort and feedback that helps us improve the content. Thank you.
