### ISSUE TITLE
Update the DLP Licensing for Microsoft Teams

### ISSUE THREAD

**Issue by annferre** [MicrosoftDocs/microsoft-365-docs#5945]
Can you update the [DLP Licensing for Microsoft Teams](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide#dlp-licensing-for-microsoft-teams)
From:
Office 365 E5/A5
Microsoft 365 E5/A5
Microsoft 365 Information Protection and Governance
Office 365 Advanced Compliance
To:
•	Office 365 E5/A5/G5
•	Microsoft 365 E5/A5/G5
•	Microsoft 365 E5/A5/G5 Information Protection and Governance
•	Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaab3f7-d1d4-c649-efe8-f24913da4f3e
* Version Independent ID: c5710ebf-0ca5-ab46-c490-64ebc308defe
* Content: [Data loss prevention and Microsoft Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-microsoft-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@annferre Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6015

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @annferre Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
