### ISSUE TITLE
notification from trainingassignment@microsoft.com saying they have not completed the training.  

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#5946]
I have raised a support case with Microsoft (Case #:26254527). The case was closed and resolved as a bug thus why I'm posting this here.

To summarize, we have users who have completed all their assigned training but still constantly get the email notification from trainingassignment@microsoft.com saying they have not completed the training.  

Any help to fix this issue would be great appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c87455-77af-093a-6fb6-286049aad15a
* Version Independent ID: b2690e98-781d-4a27-a9bc-bd621964feb0
* Content: [Get started using Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-get-started.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@HarrisburgUSysAdmin, we typically don't update the documentation for bugs until we find out what the end goal is: if they're going to fix the bug, that would then render any updates incorrect, which would then need to be fixed.

It's been quite a while. Has the bug been fixed? Are the notifications behaving correctly now?

**Comment by HarrisburgUSysAdmin** [comment]
This was fixed for Microsoft and listed as a bug.

**Comment by chrisda** [comment]
@HarrisburgUSysAdmin, sorry, so does this mean the problem still exists for you? Or have you noticed an improvement?

I'm asking because it's been 4+ months, and I thought you might have noticed if the problem no longer exists.

**Comment by HarrisburgUSysAdmin** [comment]
The issue was resolved.  We no longer have the issue.

**Comment by chrisda** [comment]
Excellent!

Thanks for the feedback.

Closing.
