### ISSUE TITLE
404 on Microsoft Defender for Endpoint link at the top

### ISSUE THREAD

**Issue by epinto** [MicrosoftDocs/microsoft-365-docs#5947]
The "Microsoft Defender for Endpoint" at the top of the document isn't found. Error message:

<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:6eb4e705-d01e-0070-402b-8e64e3000000 Time:2021-08-10T21:09:18.9076096Z</Message>
</Error>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8deee5-bb2d-24da-0a31-0d41ccb4492c
* Version Independent ID: 77b994cf-7b5c-f813-0a1f-a38f046a2a02
* Content: [Protect your organization's data with device control](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-report?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-control-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-control-report.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@epinto Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/5999

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @epinto Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
