### ISSUE TITLE
How to request a move post-deadline?

### ISSUE THREAD

**Issue by MonstarSuperS** [MicrosoftDocs/microsoft-365-docs#5948]
The site does not show how you're supposed to request data residency move after the deadline. What if our company missed the opportunity to have your data migrated during that deadline? At least provide an option to know that more opportunities will come down the line, because not being able to request a move is a bit odd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87cb379c-82ae-0a6e-8dd5-0c41b09364ab
* Version Independent ID: a15c3919-e63e-f0dc-bd6b-45f311b387b5
* Content: [How to request your data move - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/request-your-data-move?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/request-your-data-move.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/request-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by msbemba** [comment]
@MonstarSuperS Thank you for your feedback. We have a set of general questions like these added to the FAQ Section - vhttps://docs.microsoft.com/en-us/microsoft-365/enterprise/data-move-faq?view=o365-worldwide#what-happens-if-i-do-not-request-a-move-before-the-deadline-

We cannot accept requests for migration after the open enrollment period.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MonstarSuperS Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
