### ISSUE TITLE
Moving an auto-expanded archive folder

### ISSUE THREAD

**Issue by rsirwaturai** [MicrosoftDocs/microsoft-365-docs#5949]
Can I move an auto-expanded archive folder to another location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69e08cf1-3ef1-7d22-122e-ef0f45c26215
* Version Independent ID: e9677dc3-580d-0a66-80ac-30a8aabdd45f
* Content: [Overview of unlimited archiving - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/unlimited-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rsirwaturai We're looking into your question, and I will follow up on this issue when I have an answer. In the mean time, you might want to open a request with MS Support. Are you trying to move a folder to another auto-expanded storage area or are you trying to move it to the main archive? Note that you can't delete folders in the archive. That includes folder in the main archive and folders in an auto-expanded storage area.

**Comment by yogkumgit** [comment]
@rsirwaturai Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by rsirwaturai** [comment]
Dear Mark,
Apologize for the late reply. I've been studying Exchange Online archive mailbox and found that archived items will be stored inside a folder with the same name as the master folder with an additional year number as a suffix. 
My question is the archive folder movable to another folder inside the Outlook folder tree?  
    Pada Selasa, 17 Agustus 2021 04.12.28 WIB, Mark Johnson - MSFT ***@***.***> menulis:  
 
 


@rsirwaturai We're looking into your question, and I will follow up on this issue when I have an answer. In the mean time, you might want to open a request with MS Support. Are you trying to move a folder to another auto-expanded storage area or are you trying to move it to the main archive? Note that you can't delete folders in the archive. That includes folder in the main archive and folders in an auto-expanded storage area.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
