### ISSUE TITLE
Retention Polices on Soft Deleted OneDrives, Sites, Mailboxes, Etc.

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/microsoft-365-docs#595]
If you delete a SharePoint site, a mailbox, or a Onedrive and then apply a retention policy to your entire organization while these collections are in a soft deleted state, will the retention policy still apply to the soft deleted entities? The situation I encountered is that a OneDrive was soft deleted and then followed the normal retention cycle set in the Onedrive admin center instead of the retention policy I applied. The retention policy was applied after the deletion of the user and the soft deletion of the OneDrive. Is this normal? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@microsoftsearch  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@microsoftsearch Thank you for the feedback. A retention policy is applied to an active mailbox, site and one drive accounts, So this is normal. Meanwhile, If you restore the mailbox or the site the retention policy will be auto-applied if the policy is set to the entire org.

Hope this helps!
Thanks
Sri

**Comment by mypil** [comment]
@microsoftsearch - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
