### ISSUE TITLE
Microsoft S/Mime Control for Outlook on the web for Chrome Issue

### ISSUE THREAD

**Issue by sysadmin84** [MicrosoftDocs/microsoft-365-docs#596]
Extension is only installed if the user downloads and runs the msi. If running from an application package it does not install until the user downloads and executes the msi. Is there a workaround to install for all users and stop the prompts for download and installation?

**Comment by mypil** [comment]
@sysadmin84 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by sysadmin84** [comment]
@mypil - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-s-mime-settings-for-outlook-web-app

**Comment by mypil** [comment]
@sysadmin84 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
