### ISSUE TITLE
Exchange Litigation Hold and Teams Chat Retention

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/microsoft-365-docs#5960]
Hi, 
in the article is described that Exchange Retention Policies don't handle Teams Conversations which were stored in the participating users mailbox. What happens if a mailbox is set to litigation hold:
Set-Mailbox abc@qwe.com -LitigationHoldEnabled:$true
Will the messages form the mailbox also if a user delets them from the chat client? And if a modern Retention Policy handles the expiry of chat messages, how does this works combined with Exchange Litigation Hold. I assume that a Exchange Litigation hold "beats" an deletion triggered by an modern Retention Policy and that a Teams message will persist. Or is the special Folder which holds Teams Messages excluded from the LitigationHold somehow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @J-a-k-o-b  Litigation holds & eDiscovery holds work differently from retention policies - they do preserve the copied messages for Teams that are stored in a mailbox.  If the mailbox is subject to a litigation hold or eDiscovery hold, the first principle of retention applies: permanent deletion is suspended.

**Comment by J-a-k-o-b** [comment]
Thank you for the fast answer @cabailey. Maybe you can make an Info-Box in the docs somewhere that contain this information.

**Comment by yogkumgit** [comment]
@J-a-k-o-b Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
