### ISSUE TITLE
webhelp shared mailbox not working

### ISSUE THREAD

**Issue by bvdsande** [MicrosoftDocs/microsoft-365-docs#5961]
hi,

trying to create a shared mailbox, it is going well in the web app but the outlook app does not work yet(deliverable message).
on the webhelp the links below mentioned are not working.
they might hold some crucial explaination to get it fixed.

https://docs.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox?view=o365-worldwide

![image](https://user-images.githubusercontent.com/88771863/129004361-82936427-b1e8-4573-833c-f312d21d72a1.png)

thanks in advandce.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db2dbb29-38c4-afe4-bc0d-3bbc195f6288
* Version Independent ID: bcfee113-ecfe-e358-974e-6f9cd76b8d35
* Content: [Create a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@bvdsande Thank you for your feedback. The links under the section Add a shared mailbox to outlook seems to be working. Could you please elaborate on which part of the documents needs modification and what exactly happens when you add a shared mailbox to outlook? 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bvdsande Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
