### ISSUE TITLE
Missing URLs specific to Azure AD

### ISSUE THREAD

**Issue by jreinhardtproarch** [MicrosoftDocs/microsoft-365-docs#5962]
In an article about Azure AD Connect (https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-ports#table-2---azure-ad-connect-and-azure-ad), it refers back to this page to get specific URLs that need to be open for Azure AD Connect to Azure AD traffic. However, no specific categories on this list mention Azure Active Directory. Therefore, it seems there's a gap in the documentation for clients that only allow certain URLs on ports 443 and 80. Thanks for looking into this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2&view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
Azure AD endpoints should be with Azure docs and would be out of scope for the O365 article.https://www.microsoft.com/en-us/download/details.aspx?id=56519
