### ISSUE TITLE
Hong Kong Identity Card (HKID) Number

### ISSUE THREAD

**Issue by nvprophecy** [MicrosoftDocs/microsoft-365-docs#597]
HKID should be a keyword for Hong Kong Identity Card (HKID) Number.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [What the sensitive information types look for](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for)
* Content Source: [microsoft-365/compliance/what-the-sensitive-information-types-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@nvprophecy - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by chrfox** [comment]
Hi @nvprophecy 
Thank you for your suggestion. I will forward your suggestion to the product team to include in the keywords for the  Hong Kong Identity Card (HKID) sensitive information type.
Chris

**Comment by nvprophecy** [comment]
Hi Team,

 Why is this close. I remember that 'HKID' was a keyword; now it's not.
