### ISSUE TITLE
Unable to add a DNS record

### ISSUE THREAD

**Issue by EbonyKnight** [MicrosoftDocs/microsoft-365-docs#5984]
[Enter feedback here]
I am unable to add a new DNS record to point to my new website. Microsoft 365 support tells me that I can't add a new record since I didn't purchase my domain from Microsoft. They insist that I make the change at the hosting site which will halt my email flow. After the A record is added to the hosting domain the point the MX records back to Microsoft. I don't understand why I can't add the A record through my 36t5 admin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f087dd43-183d-08bb-37d7-d893bede6efb
* Version Independent ID: be429837-0300-3de8-6c7d-2da2fabc2c17
* Content: [Update DNS records to keep your website with your current hosting provider - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider?view=o365-worldwide)
* Content Source: [microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/update-dns-records-to-retain-current-hosting-provider.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@EbonyKnight Thank you for your feedback. You don't have to purchase the domain from Microsoft to be able to add a A record. If you are using Microsoft Name servers (NS records) then you will be able to add additional records via Settings > Domains --> DNS records --> Add records.

If your domain was purchased outside of Microsoft and you are using the third-party service to add DNS records, then adding any additional details in the Microsoft 365admin center will not help. So if you would like to make all your changes in Microsoft 365 admin center, you'll have to use Microsoft Name server records.

Hope this helps!

Thanks
Sri

**Comment by EbonyKnight** [comment]
That is how we solved the problem. The issue was no one, including me, understood the custom software interface. This was a prime time for a training exercise.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
