### ISSUE TITLE
Expired Version of SCCM after fresh eval. lab build

### ISSUE THREAD

**Issue by obitstack** [MicrosoftDocs/microsoft-365-docs#599]
Hi there, is there another workaround other then starting a new VM en get a fresh trial/evaluation version installed? Thanks in advance 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office Deployment Lab Kit](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?ocid=AID763438_QSG_319286#feedback)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
Hi - thanks for the comment. Currently there is not but we'll work to get something posted!

**Comment by obitstack** [comment]
Thanks for the quick reply! Allright, I'll try to work around with a new VM for now.
