### ISSUE TITLE
How to remove via tag

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/microsoft-365-docs#600]
It's not clear from the document how to remove the "via" tag from the recipient side. I'm getting this behavior with an allowed sender and the document says that this shouldn't apply to people in a user's individual allowed sender list. I don't see the domain pair show up under the spoof intelligence insight section in security and compliance. As a side note, the hyperlink is missing from the page for this document https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c7c32e-6f64-353b-0822-f6c7b4072998
* Version Independent ID: 1a0d4ab3-c309-daa2-7855-93257071c29e
* Content: [Unverified Sender](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/unverified-sender-feature)
* Content Source: [microsoft-365/security/office-365-security/unverified-sender-feature.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/unverified-sender-feature.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by j0rt3g4** [comment]
Hello @microsoftsearch 
Related to the tag that you're getting mistakenly working or partial working please contact support about it.

Related to the missing or broken link can you be more specific?

**Comment by microsoftsearch** [comment]
Thank you for the response. Under this section "How to manage which messages receive the unverified sender treatment" there is this bullet "Add the domain pair through the Spoof Intelligence Insight. For more details, see Walkthrough: spoof intelligence insight". The walkthrough: spoof intelligence insight is not a hyperlink and I believe that it should be to this document https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/walkthrough-spoof-intelligence-insight

**Comment by j0rt3g4** [comment]
Added information on PR #784

**Comment by mypil** [comment]
@microsoftsearch - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/3fdb521b9d2d576e2aafac1778688113e10f793d. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by arourke** [comment]
Also experiencing the same issue as the OP. The article says that senders in the safe sender list won't get the unverified sender treatment. I've added a particular domain to this list and, while there is no longer a "?" where the email picture should be, a "via" tag still appears. This article implies that both the "?" and "via" are part of the "unverified sender" feature. Therefore, both of these should be removed when I add the domain to the safe sender list.

**Comment by chrisda** [comment]
@arourke, bit of a late response, but it's my understanding that individual senders in a user's Safe Senders list are honored, but domain entries are not (at least from an anti-spam perspective). Could that be part of the issue?
