### ISSUE TITLE
Phrasing not clear

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/microsoft-365-docs#6001]
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-vdi?view=o365-worldwide#for-windows-10-or-windows-server-2019

The use of a negative in the wording for item 2. a is confusing and almost caused me to open a support ticket, please change to:

a. If you are implementing multiple entries for each device - one for each session, copy WindowsDefenderATPOnboardingScript.cmd.

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5b23fe-37ce-e3b0-ad76-55a416eaa865
* Version Independent ID: 26becb70-47ff-38fe-592f-99d84f6aba12
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) devices](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-vdi?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-vdi.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@ssmiller60 Thank you for your feedback. We have made changes to the document via  PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6022

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ssmiller60 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
