### ISSUE TITLE
When a user is deleted, can recipients still read the e-mail addition to the FAQ

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#6002]
Here is a question suitable to add to this FAQ which I have a hard time finding an answer for. If User A in a tenant sends an e-mail that is encrypted with Message Encryption to user B in the same tenant and user C in another tenant. A few weeks later, user A leaves the company and his account is deleted. Will user B and C still be able to open the encrypted e-mail or is this gone since it was actually just stored in user A mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2a02f3-0560-f5c7-9743-d7e65ad5d1a4
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.yml)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@JonesMikael Thank you for your feedback. The account deletion does not impact the encryption as does not depend on the mailbox instead depends on the label. I was able to test and confirm the same as well.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JonesMikael Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
