### ISSUE TITLE
logon UPN match their primary SMTP address recommendations are blocking deployment

### ISSUE THREAD

**Issue by maartenk99** [MicrosoftDocs/microsoft-365-docs#6003]
[Enter feedback here]
can you share more background on the remark at the bottom of the page " It is best practice, however, to have the person's logon UPN match their primary SMTP address."?  Is this just for user convenience or are there technical requirements? I have several customers that are confused about this statement that is a deployment blocker for them. 

Thanks
maartenk@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42a1bfc-8920-c16d-f4c9-d29b401b7f6c
* Version Independent ID: 979b71da-fdff-238d-41fb-472f1591e51e
* Content: [Change a user name and email address - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/change-a-user-name-and-email-address?view=o365-worldwide#tip-keep-the-persons-old-email-address)
* Content Source: [microsoft-365/admin/add-users/change-a-user-name-and-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/change-a-user-name-and-email-address.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@maartenk99 Thank you for your feedback. Ideally, Users will need to understand what their UPN is and that it is the login for all things Office 365 related. There are some prompts that will say “enter your email” but they will in fact need to use their UPN.

Office ProPlus, the iOS versions of Office and OneDrive will prompt the user for their email address for login or activation, they really mean the UPN. So this is more for user convenience.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @maartenk99 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
