### ISSUE TITLE
Advanced HTTP level monitoring: questions

### ISSUE THREAD

**Issue by helgeklein** [MicrosoftDocs/microsoft-365-docs#6007]
The documentation states: _Defender for Endpoint supports advanced HTTP level monitoring through network protection. When turned on, a new type of event is surfaced which exposes the real target domain names._

That leaves the following **questions regarding advanced HTTP level monitoring**:

* Does it work with HTTPS encryption between the endpoint and the proxy?
* Does it work with HTTPS encryption between the endpoint and the target server?
* Does it need to be turned on specifically, or is it sufficient to enable network protection as described [here](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-network-protection?view=o365-worldwide)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0456c5aa-06b5-3248-332b-b532598dba4c
* Version Independent ID: ce0b411a-de90-7c7b-1b88-f8855b7feb07
* Content: [Investigate connection events that occur behind forward proxies](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/investigate-behind-proxy?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/investigate-behind-proxy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/investigate-behind-proxy.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Response from team:
- Yes
- Yes
- No need to turn on anything besides enabling network protection.
