### ISSUE TITLE
Adding of Giphy.com

### ISSUE THREAD

**Issue by EthanRodz** [MicrosoftDocs/microsoft-365-docs#6009]
Giphy.com is the provider of GIFs to Microsoft Teams. This requires the Teams client to directly reach out to Giphy.com to retrieve and surface those GIFs in Teams. Giphy.com should be listed on the required optional URLs for Teams. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Additional endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@EthanRodz Thank you for your feedback. I'm currently working with the author to update the giphy.com URL. I shall update you shortly.

Thanks
Sri

**Comment by BrianMcNeese** [comment]
Hi, any progress on getting giphy.com URL added?

**Comment by kelleyvice-msft** [comment]
Hi @BrianMcNeese,
We cannot add URLs that are not part of Microsoft 365 to the web service. The web service only contains endpoints that are owned by Microsoft and are part of the M365 system. 
Thanks,
Kelley
