### ISSUE TITLE
CD.Latest Folder redirects o D:\ on CM1

### ISSUE THREAD

**Issue by SeSeicht** [MicrosoftDocs/microsoft-365-docs#601]
The Folder 
`C:\Program Files\Microsoft Configuration Manager\CD.Latest` is a `JUNCTION `to `[d:\CMPackageCache]`. 
Per Default the CM1 machine doesn't have a partition D:. So the Folder is not accessible. Because of that you can't do a site recovery in this environment. 
<img width="348" alt="cdlatest" src="https://user-images.githubusercontent.com/48480298/67406666-a6a20600-f5b6-11e9-8882-a017b842860b.png">

@MrRoundRobin

**Comment by SeSeicht** [comment]
depending: Windows and Office Deployment Lab Kit
https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab

**Comment by SeSeicht** [comment]
@mypil this is not specific to my tenant. It's about the `Windows and Office Deployment Lab Kit`. This is a general bug in this Kit.

**Comment by mypil** [comment]
@SeSeicht - We appreciate your efforts to clarify the docs.

 Is there something within this doc - **https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab** that you suggest to be edited to incorporate your feedback?

If you could suggest what the appropriate text and where it should be placed, I could assign one of our team members to create a Pull Request to get it added or you may also create a Pull Request to add in your suggestion and just link this issue so I can have the doc owner review and merge the content. Thank you.

**Comment by mypil** [comment]
@SeSeicht - We appreciate/value any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue. 

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.
