### ISSUE TITLE
Topic Groups

### ISSUE THREAD

**Issue by noAlvaro** [MicrosoftDocs/microsoft-365-docs#6013]
How could I cluster or cascade a number of Topics within one "Topic Group"?
A feature like this might be important to allow linear exploration of correlated Topics.
_- How about it?_

**Comment by yogkumgit** [comment]
@noAlvaro Please indicate the the document you are referring to and wish to give the feedback for its improvement. Thanks

**Comment by yogkumgit** [comment]
@noAlvaro We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
