### ISSUE TITLE
Minor correction on usage of switch EnableLitigationHoldForMigration

### ISSUE THREAD

**Issue by testitwithme** [MicrosoftDocs/microsoft-365-docs#6014]
In the "Prepare target user objects for migration"/Prerequisites section of the Cross-tenant mailbox migration document at the 3rd part, the command "Set-MailUser -EnableLitigationHoldForMigration $TRUE" doesn't require the $TRUE swith, correctly it should be:
"Set-MailUser -EnableLitigationHoldForMigration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@testitwithme Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6020

Thanks
Sri

**Comment by testitwithme** [comment]
Hello Sriraman,

I can see the change, thank you.
I really like this very detailed document, which answered a couple of my
questions and helped me a lot during the migration of mailboxes.
I would have another comment: On the source tenant only the accept the
permission requires Global Admin right. I would add it to 1. on the
"Step-by-step instructions for the source tenant admin" section as it is on
the target side at 8.
Original:
 Step-by-step instructions for the source tenant admin
1. Sign in to your mailbox as the -ResourceTenantAdminEmail specified by
the target admin during their setup. Find the email invitation from the
target tenant, and then select the Get Started button.Should be:
Should be:
1. Sign in to your mailbox as the -ResourceTenantAdminEmail specified by
the target admin during their setup. *This account has to have Global Admin
rights. *Find the email invitation from the target tenant, and then select
the Get Started button.Should be:
As it is on section:
Step-by-step instructions for the target tenant admin
8. *Sign in with your Global Admin credentials*. When the following screen
is presented, select Accept.

The option -Resource*TenantAdmin*Email should suggest that Global admin
rights are needed, but it's not obvious.

Thank you,
Janos

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@testitwithme I have made the changes via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6084

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @testitwithme Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
