### ISSUE TITLE
Download of prod.list for Ubuntu fails

### ISSUE THREAD

**Issue by iboettcher** [MicrosoftDocs/microsoft-365-docs#6016]
The document says to run 

curl -o microsoft.list https://packages.microsoft.com/ubuntu/20.04/prod.list

to download the current package list. This was working before, but now fails with http 404 error. There is no such file in any of the other Ubuntu subfolders, too. Can someone explain, what the reason is? Thx!

**Comment by denisebmsft** [comment]
Hello @iboettcher! Thank you for the feedback. Can you please tell us to which article(s) your feedback applies? This information will help us route the issue correctly. Thanks!

**Comment by iboettcher** [comment]
Sorry, I thought that there is an automatic referral to the right article. 

Thats the article: 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide

The line in the article is:
curl -o microsoft.list https://packages.microsoft.com/ubuntu/18.04/prod.list

This will fail to download anything, since https://packages.microsoft.com/ubuntu/18.04/prod.list does not exist. It does not exist for i.e. 20.04 either.

**Comment by msbemba** [comment]
@iboettcher Thank you for your feedback. I was able to download the current package list after the URL has been updated to https://packages.microsoft.com/config/ubuntu/20.04/prod.list. The config part was missing which was fixed,

Hope this helps!

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by iboettcher** [comment]
Thank you, I can confirm it is working now.
