### ISSUE TITLE
W365 Business prerequisites

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#6018]
Please consider updating the prerequisites section that currently states "There are no prerequisites to set up Windows 365 Business” to state that the following are prerequisites:
1. The cloudbprt user needs to be excluded from any CA policies that require MFA
2. in Device settings, toggle the require MFA to off for Azure AD join
3. If Intune is used, the cloudbprt user needs to be added to the intune MDM scope

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 948c0bd4-e387-2530-5c20-de54a4964f01
* Version Independent ID: c4788787-69e3-ddd9-d708-ec68280fb7b9
* Content: [Get started with Windows 365 Business and Cloud PCs - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/get-started-windows-365-business?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/get-started-windows-365-business.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/get-started-windows-365-business.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@itguysocal Thank you for your feedback.

The document now states there are no licensing prerequisites and has a link to the setup troubleshooting guide(https://docs.microsoft.com/en-us/microsoft-365/admin/setup/troubleshoot-windows-365-business?view=o365-worldwide) to make sure your environment preferences are optimized for Windows 365 Business.

The setup t/s guide talks about these and a few more.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @itguysocal Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
