### ISSUE TITLE
Link to https://partners.office.com/TEIBusiness does not work

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/microsoft-365-docs#602]
Link to https://partners.office.com/TEIBusiness does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed7e43-7ec8-01f6-8cf0-6fd77519840e
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business Frequently Asked Questions ](https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs#deployment)
* Content Source: [microsoft-365/business/support/microsoft-365-business-faqs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/support/microsoft-365-business-faqs.md)
* Product: **microsoft-365-business**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by markjjo** [comment]
@jozefizso Thanks for the heads up. The correct link is https://www.microsoft.com/microsoft-365/partners/PartnerTEI 

We'll fix this link in the topic.
