### ISSUE TITLE
Update reference to classic EAC

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#6027]
Hi Chris,

I noticed the "Recommended Content" section for this article references the classic EAC
https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results, 

and earlier in the page is a reference to the modern EAC

> Note
> Message trace in the Microsoft 365 Defender portal is just a pass through to Message trace in the Exchange admin center. For more information, see Message trace in the modern Exchange admin center.

The article currently references both the classic and modern EAC.

I propose replacing the classic reference with the modern reference which is
https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/message-trace-modern-eac

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58f8e2c-428a-4d8e-e8b7-a0342a0038db
* Version Independent ID: 6e7fab1b-1e24-9e36-176d-c3fb14f233a7
* Content: [Message trace in the Microsoft 365 Defender portal - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/message-trace-scc.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/message-trace-scc.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jonwbstr, OK. Be my guest.

**Comment by jonwbstr** [comment]
Hehehe, okay. Do what you want with this, I only wanted to share the observation so I'm good to close if that's what you're thinking.

**Comment by chrisda** [comment]
Closing.
