### ISSUE TITLE
More guidance needed on registration numbers

### ISSUE THREAD

**Issue by DracinschiG** [MicrosoftDocs/microsoft-365-docs#6037]
We need to have additional guidance for specific countries, such as: Armenia, Belarus, Kazakhstan, Kyrgyzstan, Moldova, South Africa, Tajikistan, Ukraine, Uzbekistan, Venezuela. 
There is only reference as to what the registration number means and not where to find it, such as what we have for Turkey. 

Thank you!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e2ac78-e08b-d7c8-5eec-baf9e9c13b62
* Version Independent ID: 66014f69-00c9-0e9b-fe0a-d0e10f2ca5eb
* Content: [About registration numbers and under review notifications](https://docs.microsoft.com/en-US/microsoft-365/commerce/about-registration-numbers?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide&viewFallbackFrom=o365-worldwide%22%20%5Cl%20%22registration-numbers-by-country)
* Content Source: [microsoft-365/commerce/about-registration-numbers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/about-registration-numbers.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us in resolving this issue. Thanks

**Comment by cmcatee-MSFT** [comment]
I've removed the table and added a link to the OECD's site where they include a comprehensive list of [TAX ID information](https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/).
