### ISSUE TITLE
Migration from Symantec to Microsoft Defender

### ISSUE THREAD

**Issue by JitenderPrasad** [MicrosoftDocs/microsoft-365-docs#6041]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e795a9bd-0d5a-ab4d-4f44-c1e365dce162
* Version Independent ID: 429ebad4-c2ab-e481-0984-301a8900c14d
* Content: [Make the switch from non-Microsoft endpoint protection to Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-migration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-migration.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@JitenderPrasad Thank you for your feedback.

The migration from Symantec to Microsoft defender is carried out in Three phases

1) Preparation for your migration. (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-prepare?view=o365-worldwide)

2) Set up defender for endpoint (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-setup?view=o365-worldwide)

3) Onboard to defender for endpoint(https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-microsoft-defender-onboard?view=o365-worldwide)

Hope this helps! If you have technical difficulties during the migration, Please contact Microsoft support via the needhelp section on the m365 admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JitenderPrasad Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
