### ISSUE TITLE
SecureScore links won't open, need an update.

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#6042]
Please update all SecureScore links to point to Microsoft 365 Defender (https://security.microsoft.com/securescore)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b680bb5-de3b-ee83-3764-91695bab77ed
* Version Independent ID: 9c770adf-a66e-ed32-25aa-ffbc46eaef82
* Content: [Microsoft 365 security roadmap - Top priorities - Office 365](https://review.docs.microsoft.com/en-us/microsoft-365/security/office-365-security/security-roadmap?view=o365-worldwide&branch=main)
* Content Source: [microsoft-365/security/office-365-security/security-roadmap.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/security-roadmap.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by msbemba** [comment]
@hudish Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6107

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @hudish Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by hudish** [comment]
not sure if fixed? still seeing the old links.

alex

**Comment by msbemba** [comment]
@hudish I see the changes have not been reflected in the Document, however, the PR is merged. This should be live shortly.
