### ISSUE TITLE
Please check the URLs in your Article

### ISSUE THREAD

**Issue by D1Ck3n** [MicrosoftDocs/microsoft-365-docs#6044]
Good day,

i found some dead URLs in this Documentation as i tried to install MS Defender on linux:

https://packages.microsoft.com/[distro]/[version]/[channel].list -> Error 404
https://packages.microsoft.com/config/[distro]/[version]/[channel].list -> works!

i hope i could help

best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@D1Ck3n Thank you for your feedback. The document currently has the URL which works (https://packages.microsoft.com/config/%5Bdistro%5D/%5Bversion%5D/%5Bchannel%5D.list)

Note that multiple URLs had this issue and all have been fixed recently.

Hope this helps!

@yogkumgit There are no changes needed in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @D1Ck3n Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
