### ISSUE TITLE
Unclear wording in regards to permanent deletion of OneDrive Data

### ISSUE THREAD

**Issue by enfo** [MicrosoftDocs/microsoft-365-docs#6046]
I believe the wording about OneDrive content beeing permanantly deleted is a bit misleading. It says: _If you don't move the files within the retention period after deleting the user, the OneDrive content will be permanently deleted._ 

However, as documented here https://docs.microsoft.com/en-us/onedrive/retention-and-deletion#the-onedrive-deletion-process, content will still be recoverable from the recycle bin for 93 days after the retention period is over.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6245943-00b8-c47b-f739-731531d5d357
* Version Independent ID: a9ec7066-ed8c-7b77-1d87-8c50bf74ec6c
* Content: [Delete a user from your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/delete-a-user?view=o365-worldwide#things-to-consider)
* Content Source: [microsoft-365/admin/add-users/delete-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/delete-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@enfo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6070

Thanks
Sri

**Comment by yogkumgit** [comment]
@kwekuako  PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @enfo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
