### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by majorshelton** [MicrosoftDocs/microsoft-365-docs#6047]
The multi-select option on content search is no longer available.  This article is no longer relevant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73897547-4dce-3d3e-8189-dc09c27e89b8
* Version Independent ID: bf6f8886-c2aa-9fbb-7769-d55253aa1a3b
* Content: [Bulk edit Content Searches - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/bulk-edit-content-searches?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/bulk-edit-content-searches.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/bulk-edit-content-searches.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@majorshelton Thanks for the heads up. I will retire the article.
