### ISSUE TITLE
Create alert incorrect permission

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6049]
The application permissions show as "Alerts.ReadWrite.All"; however, the true permission is "Alert.ReadWrite.All" (without the 's').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee49d7e-aa5b-d448-a602-6ae9987f6798
* Version Independent ID: 645d063c-91a0-7998-2778-71f43ba969d9
* Content: [Create alert from event API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/create-alert-by-reference?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/create-alert-by-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/create-alert-by-reference.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6071

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
