### ISSUE TITLE
Batch update alert incorrect permission

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6050]
The application permissions show as "Alerts.ReadWrite.All"; however, the true permission is "Alert.ReadWrite.All" (without the 's').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff057342-8179-720d-35ac-ff57db76df0c
* Version Independent ID: ecd62fbc-1e03-3e01-b692-6d7fc94f097a
* Content: [Batch Update alert entities API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/batch-update-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/batch-update-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/batch-update-alerts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6090

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
