### ISSUE TITLE
Get live response results incorrect permission

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6053]
The application permissions show as "Machine.LiveResponse"; however, the true permission is "Machine.Read.All" or "Machine.ReadWrite.All".

'code': 'Forbidden', 'message': 'The application does not have any of the required application permissions (Machine.Read.All, Machine.ReadWrite.All) to access the resource.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd8827-66cd-625d-a992-d42ec38ce0d6
* Version Independent ID: 67e04899-ef6e-20d3-8aec-d1765349bc32
* Content: [Get live response results](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-live-response-result?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-live-response-result.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-live-response-result.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
