### ISSUE TITLE
Run live response commands undocumented limitation

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6054]
If the machine that you are trying to run this API call on is in an RBAC device group that does not have an automated remediation level assigned to it, you receive the following error message:

'code': 'DisallowedOperation', 'message': "This device has no automation level assigned to it. You'll need to at least enable the minimum Remediation Level for a given Device Group."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3e5349-9b67-18ff-6c1c-d123b1f21a72
* Version Independent ID: fe100af9-381b-8b0f-cd7b-94ac62b6b313
* Content: [Run live response commands on a device](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-live-response?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-live-response.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-live-response.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6075

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
