### ISSUE TITLE
Stop and quarantine file incorrect permission

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6055]
The application permissions show as "Machine.StopAndQuarantine"; however, it appears you also need "Machine.Read.All" or "Machine.ReadWrite.All".

If you only have Machine.StopAndQuarantine, you get the following error message:
'code': 'Forbidden', 'message': 'The application does not have any of the required application permissions (Machine.Read.All, Machine.ReadWrite.All) to access the resource.'

If you only have Machine.Read.All or Machine.ReadWrite.All, you get the following error message:
'code': 'Forbidden', 'message': 'The application does not have any of the required application permissions (Machine.StopAndQuarantine) to access the resource.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec8a077-8b23-eb52-fe12-3c24bae33bf6
* Version Independent ID: 999a81d7-e9e1-6851-c636-121ccf4e181c
* Content: [Stop and quarantine file API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/stop-and-quarantine-file?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/stop-and-quarantine-file.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/stop-and-quarantine-file.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6095

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
