### ISSUE TITLE
List software by recommendation incorrect permission

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6056]
The application permissions show as "SecurityRecommendation.Read.All"; however, the true permission is "Software.Read.All".

'code': 'Forbidden', 'message': 'The application does not have any of the required application permissions (Software.Read.All) to access the resource.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf90f771-d5e6-089d-ddd4-a9aa97ba9b91
* Version Independent ID: 8735337a-91bc-c36c-d88d-50312815ee9c
* Content: [List software by recommendation](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/list-recommendation-software?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/list-recommendation-software.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/list-recommendation-software.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6077

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
