### ISSUE TITLE
List vulnerabilities by recommendation incorrect permissions

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6057]
The application permissions show as "SecurityRecommendation.Read.All"; however, the true permission is "Vulnerability.Read.All".

'code': 'Forbidden', 'message': 'The application does not have any of the required application permissions (Vulnerability.Read.All) to access the resource.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9735cd8-e95d-eeba-84d0-a7c39948cc5b
* Version Independent ID: 97049201-3b4c-8ac1-8706-bdabce0bdb39
* Content: [List vulnerabilities by recommendation](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-recommendation-vulnerabilities?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-recommendation-vulnerabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-recommendation-vulnerabilities.md)
* Product: **w10**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6094

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
