### ISSUE TITLE
Get one remediation activity incorrect permissions

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6058]
The application permissions show as "RemediationTask.Read.All"; however, the true permission is "RemediationTasks.Read.All" (with an 's').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff8fa05-2ca9-fd79-e5d1-27b91e27ef50
* Version Independent ID: 1028f35f-e819-38a1-6fe7-28a67b501aeb
* Content: [Get one remediation activity by Id](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-remediation-one-activity?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-remediation-one-activity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-remediation-one-activity.md)
* Product: **m365-security**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6078

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
