### ISSUE TITLE
What type of labels are included

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#606]
Does this include Retention and/or Sensitivity labels? it does not states which type of labels are included 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3d3633-893d-9354-9402-c47ed7dec790
* Version Independent ID: fc12340b-403f-b531-04be-91f00a8f0af6
* Content: [View label activity for documents](https://docs.microsoft.com/en-us/microsoft-365/compliance/view-label-activity-for-documents)
* Content Source: [microsoft-365/compliance/view-label-activity-for-documents.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-label-activity-for-documents.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by LauraWi** [comment]
As part of the unified labeling experience, it supports both sensitivity and retention labels. https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Updates-to-Advanced-Data-Governance-Unified-labeling-analytics/ba-p/261876

**Comment by DeanGross** [comment]
Thanks for the confirmation, that is what I was hoping to hear.

**Comment by mypil** [comment]
@DeanGross - From our understanding, the issue has been answered by LauraWi. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.
