### ISSUE TITLE
List exposed devices of remediation activity incorrect permission

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6060]
The application permissions show as "RemediationTask.Read.All"; however, the true permission is "RemediationTasks.Read.All" (with an 's').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e33302-15ec-ba50-03a1-242537ba57d2
* Version Independent ID: 96b05779-a59b-9c6e-8cd8-5f0bb10a9033
* Content: [List exposed devices of one remediation activity](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-remediation-exposed-devices-activities?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-remediation-exposed-devices-activities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-remediation-exposed-devices-activities.md)
* Product: **m365-security**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6060

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
