### ISSUE TITLE
List vulnerabilities by software incorrect permission

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6061]
The application permissions show as "Software.Read.All"; however, the true permission is "Vulnerability.Read.All".

'code': 'Forbidden', 'message': 'The application does not have any of the required application permissions (Vulnerability.Read.All) to access the resource.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32929011-dffd-5336-8cb2-ebbe42502ba7
* Version Independent ID: 23a0c7b2-2b6f-0ef0-7039-8f1a4bd4d013
* Content: [List vulnerabilities by software](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-vuln-by-software?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-vuln-by-software.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-vuln-by-software.md)
* Product: **m365-security**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6093

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
