### ISSUE TITLE
Cancel machine action incorrect permission

### ISSUE THREAD

**Issue by MastaDisasta** [MicrosoftDocs/microsoft-365-docs#6062]
The application permissions show as "Machine.CollectForensic"; however, that permission does not work. It might be an API coding error, as the correct permission is "Machine.CollectForensics" (with an 's'). **This is not simply a typo on the documentation page, the actual API code is incorrect, too.** Using any of the other listed permissions does work.

When only using the Machine.CollectForensics permission, you get the following error:
{'code': 'Forbidden', 'message': 'The application does not have any of the required application permissions (Machine.Isolate, **Machine.CollectForensic**, Machine.Scan, Machine.RestrictExecution, Machine.StopAndQuarantine, Machine.Offboard, Machine.LiveResponse) to access the resource.'

Note how in the error message Machine.CollectForensic does not have the 's'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8153baa-e1d9-4c62-a5db-2ad249e39829
* Version Independent ID: a256a854-0a15-6c14-9d5c-2eee283f75d8
* Content: [Cancel machine action API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/cancel-machine-action?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/cancel-machine-action.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/cancel-machine-action.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MastaDisasta Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6096

We will also work with the team to fix this API bug internally.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MastaDisasta Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
