### ISSUE TITLE
What does SDS stand for?

### ISSUE THREAD

**Issue by porterkim** [MicrosoftDocs/microsoft-365-docs#6063]
What does SDS stand for in the Prerequisites Before Deployment section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b696e622-361b-0be8-0b1f-b2ad9708c877
* Version Independent ID: 18403e7b-adb6-2828-54c6-ddd410eacadd
* Content: [Use Microsoft Teams classes with Canvas](https://docs.microsoft.com/en-us/microsoft-365/lti/teams-classes-with-canvas?view=o365-worldwide)
* Content Source: [microsoft-365/lti/teams-classes-with-canvas.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lti/teams-classes-with-canvas.md)
* Service: **o365-administration**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by msbemba** [comment]
@porterkim Thank you for your feedback. School Data Sync (SDS) is a free service in Office 365 for Education that reads the school and roster data from a school's Student Information System (SIS). It creates Office 365 Groups for Exchange Online and SharePoint Online, class teams for Microsoft Teams and OneNote Class notebooks, school groups for Intune for Education, and rostering and SSO integration for many other third-party applications.

To learn more about SDS, please visit https://sds.microsoft.com.

I have also added the abbreviation to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6079

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @porterkim Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
