### ISSUE TITLE
DLP email notification does not trigger for Teams sensitive message sending.

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/microsoft-365-docs#6065]
Hi Team,

Here is a issue for DLP email notification for Teams.
Issue repro steps:
1) In DLP policy, configure customize the email text in User notifications. 
![image](https://user-images.githubusercontent.com/40224592/129845694-612e8006-79ea-48cd-9c89-4795c6695823.png)

User send sensitive message in Teams chat, then warning or flag message shows up as expected.

Repro Results:  However user did not receive customize email notification. Expected Results: user should receive email notification for this customize email text message.

If same user sent sensitive message in Outlook, then user is able to receive this customize email notification as below.
![image](https://user-images.githubusercontent.com/40224592/129845743-eec6e53b-187b-43dd-8a17-ec5c37d10dd0.png)
The issue can be reproduced in house in multiple tenants.

However, customer's concern is that the official MS document has option to define or customize the email text as below screenshot in this document. 

![image](https://user-images.githubusercontent.com/40224592/129845314-fe6f8ae9-df93-42a6-a6de-32d23f577047.png)

Could you please help to check and adjust the statement from document in order to avoid confusion for customer, before the feature is improved or issue is fixed?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaab3f7-d1d4-c649-efe8-f24913da4f3e
* Version Independent ID: c5710ebf-0ca5-ab46-c490-64ebc308defe
* Content: [Data loss prevention and Microsoft Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-microsoft-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by msbemba** [comment]
@XixiHuang333 I was able to test this and I did not receive the Customized email notification. I'll wait for another 24 hours and test again. Meanwhile, you can report this as a bug to the product team via the feedback section on the admin center or Contact Microsoft support to report the bug if the issue still exists.

Thanks
Sri

**Comment by msbemba** [comment]
@XixiHuang333 I'm able to reproduce the issue. We recommend you to contact Microsoft support via the need help button on the admin center to report this issue. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @XixiHuang333 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
