### ISSUE TITLE
Available for GCC or not??

### ISSUE THREAD

**Issue by leighannfletcher** [MicrosoftDocs/microsoft-365-docs#6069]
[Enter feedback here]
On this page you say this is available for GCC tenants.  Here, https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide 

you say it is not.  Is Microsoft 365 Usage Analytics available for GCC or not?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by efrene** [comment]
@leighannfletcher - Thanks so much for the feedback. Sorry for the confusion.  This article will be updated today to link to the article that describes how to use the Usage Analytics report in a Microsoft 365 GCC tenant.  Viewing Usage Analytics data in a Microsoft 365 GCC tenant is supported, but your need to download a Power BI template that is not available in the Power BI Marketplace (described in the other article). Again, sorry for the confusion, and thank you for noting this to us.
