### ISSUE TITLE
No more Fixed mode

### ISSUE THREAD

**Issue by TGBX** [MicrosoftDocs/microsoft-365-docs#6083]
Fixed mode has been removed from the admin console, but is still mentioned in the doco and should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d688bc03-7d86-46d8-ffe7-3fad3974d4cf
* Version Independent ID: 7482cca5-faac-3276-8481-e6323cafef31
* Content: [Centralized Deployment FAQ](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide#will-centralized-deployment-provide-admins-the-flexibility-to-choose-the-deployment-method-for-outlook-add-ins--)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-FAQ.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-FAQ.yml)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@TGBX Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6108

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TGBX Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
