### ISSUE TITLE
variable referenced but not created anywhere

### ISSUE THREAD

**Issue by orandev** [MicrosoftDocs/microsoft-365-docs#6089]
Hello,
In the "Managing large numbers of users" section, there is the following line:

Invoke-Command -Session $s [...]

But the $s variable is not mentioned anywhere else on the page, so we don't know what is inside and how to create it.

I think you should add the following line at the top of the code block:

**$s = Get-PSSession | Where-Object { ($_.ComputerName -like '*.online.lync.com' -or $_.Computername -eq 'api.interfaces.records.teams.microsoft.com') -and $_.State -eq 'Opened' -and $_.Availability -eq 'Available' }**
$users = Get-CsOnlineUser -Filter { ClientPolicy -eq $null } -ResultSize 500

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b40e7e54-3354-4cb2-e5c0-7ba5411dbdf1
* Version Independent ID: 572d0957-750d-6986-f62c-4167fdb8cb4a
* Content: [Assign per-user Skype for Business Online policies with PowerShell for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/assign-per-user-skype-for-business-online-policies-with-microsoft-365-powershell?view=o365-worldwide#managing-large-numbers-of-users)
* Content Source: [microsoft-365/enterprise/assign-per-user-skype-for-business-online-policies-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/assign-per-user-skype-for-business-online-policies-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@orandev Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6109

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @orandev Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
