### ISSUE TITLE
Change "Discovery Mangers" to "Discovery Managers" :)

### ISSUE THREAD

**Issue by adamgourd** [MicrosoftDocs/microsoft-365-docs#6098]
Change "Discovery Mangers" to "Discovery Managers" :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffb84a4-0c98-3fc2-8963-4c809efaa149
* Version Independent ID: 305dd7b2-382e-a0da-40b5-1457e6b625bd
* Content: [Set up compliance boundaries for eDiscovery investigations - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-compliance-boundaries.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-compliance-boundaries.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@adamgourd Thanks for catching this. I will fix.
