### ISSUE TITLE
Point 5a is incorrect - Run this script as

### ISSUE THREAD

**Issue by jgriff500** [MicrosoftDocs/microsoft-365-docs#6100]
Run this script using the logged on credentials -- should be NO since most users do not have (or should not have ) local admin on their computer.  Setting to YES causes this script to fail.   Setting to NO an allowing to run as System allows the script to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fbdd3c-a33c-84ef-082a-df4a483e3201
* Version Independent ID: 58d81554-45f9-192a-04a9-e0a6b92fe11f
* Content: [Get started with the Microsoft Compliance Extension - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-chrome-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-chrome-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-chrome-get-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jgriff500 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
