### ISSUE TITLE
Request to restore the original version of this page

### ISSUE THREAD

**Issue by ThatMicrosoftGuy** [MicrosoftDocs/microsoft-365-docs#6102]
Hello Team,

I was curious to find that this links page used to advise admins on how to migrate from Office 365 E3 to Microsoft 365 Business Premium. It would include the comparison table found [https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb#feature-comparison-microsoft-365-business-premium-and-office-365-e3](url) and would then go to guide the admin on the steps they needed to perform in order to finish the process.

The original link can still be found via a google search (migrating from Office 365 E3 to Microsoft 365 Business Premium) however bing has already renamed it. 
[https://www.google.com/search?q=microsoft+365+business+premium+vs+e3&ei=nLAeYavUD8XatQb7irSYBg&oq=microsoft+365+business+premium+vs+e3&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAELADEEMyDQguEMgDELADEEMQkwIyCgguEMgDELADEENKBQg4EgExSgQIQRgAUABYAGDMkgtoAXACeACAAZIBiAGSAZIBAzAuMZgBAMgBC8ABAQ&sclient=gws-wiz&ved=0ahUKEwirkvHS6L3yAhVFbc0KHXsFDWMQ4dUDCA4&uact=5](url)

Is there an archive of the original page that I an download for future reference? Admins are reaching out to me to tell me that the new format has made the link irrelevent at this point.
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/89220930/130133355-93b892be-6148-4120-87a8-a3d073ff3c09.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3519dc1-b7fa-cb9f-d9d7-cc5831ddbd67
* Version Independent ID: 18096313-720b-9f75-f9e0-6509b7dc8578
* Content: [Upgrade to a different business plan](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/upgrade-to-different-plan?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/upgrade-to-different-plan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/upgrade-to-different-plan.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ThatMicrosoftGuy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
