### ISSUE TITLE
File share security requirements

### ISSUE THREAD

**Issue by castellcoch** [MicrosoftDocs/microsoft-365-docs#6113]
What are the Share and NTFS permissions required on the VDI security intelligence update file share?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87fa68a-a881-7ab7-97df-5da73dc56692
* Version Independent ID: 0c031441-cc26-903a-4d53-c044ea790d2d
* Content: [Microsoft Defender Antivirus Virtual Desktop Infrastructure deployment guide](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
The share and NTFS permissions required are included in the section, [Download and unpackage the latest updates](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus?view=o365-worldwide#download-and-unpackage-the-latest-updates).
