### ISSUE TITLE
Office 365 CDN for media/video file

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/microsoft-365-docs#6117]
There are two articles about office 365 CDNs, both of which have architecture diagrams for Office 365 CDNs.

Content Delivery Networks (CDNs)
https://docs.microsoft.com/en-us/microsoft-365/enterprise/content-delivery-networks?view=o365-worldwide#the-office-365-cdn

Use the Office 365 Content Delivery Network (CDN) with SharePoint Online
https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo?view=o365-worldwide

An example of Private assets is "picture" in the former, but "Videos" and "Software" in the latter. I think the difference in the diagram between the two articles is the difference in the freshness of the article.
But, my understanding is that video files on the SPO use Azure CDN, not Office 365 CDN anyway. So, if my understanding is correct, we should remove "Videos" from the diagram or  separate Office 365 CDN and Azure CDN section for videos because users never reference videos  from the Office 365 CDN,.

![image](https://user-images.githubusercontent.com/13634805/130435358-38c613e6-8f05-454a-b073-e78f58ac647e.png)

https://docs.microsoft.com/en-us/microsoft-365/enterprise/content-delivery-networks?view=o365-worldwide#azure-cdn

>Beginning in Q3 2020, SharePoint Online will begin caching videos on the Azure CDN to support improved video playback and reliability. Popular videos will be streamed from the CDN endpoint closest to the user. This data will remain within the Microsoft 365 compliance boundary. This is a free service for all tenants and it does not require any customer action to configure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cfe2b0-c14d-1083-7c88-a91e58593cfa
* Version Independent ID: 2d15076c-0dcd-6bd6-e0fb-f8ac5ffd0091
* Content: [Use Office 365 Content Delivery Network (CDN) with SharePoint Online - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-microsoft-365-cdn-with-spo.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@scotvidican Please reply. Thanks

**Comment by kelleyvice-msft** [comment]
I will bring this to the attention of the CDN PM and figure out what needs to be updated. Thank you!

**Comment by kelleyvice-msft** [comment]
I've discussed this with the PM, and you are entirely correct. I will revise the diagrams and other guidance to reflect this. Thanks, @kefujino! 
Kelley
