### ISSUE TITLE
SharePoint Syntex not synchronising content types within a few minutes

### ISSUE THREAD

**Issue by CallumCrowley** [MicrosoftDocs/microsoft-365-docs#6118]
**Issue**

When many sites are associated with a Hub at the same time, SharePoint Syntex does not synchronise content types with those sites within a few minutes (as described in the documentation).

This is a problem for situations where a number of users create different sites and associate those sites with the Hub.

**Steps to reproduce**

1. Ensure you have a content type already pushed to a Hub.
2. Create 5 to 10 sites
3. Associate these sites with the Hub
4. Wait for the content type to be synchronised to the sites.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4760c99-cd14-4733-1655-786ab727fa6e
* Version Independent ID: 4ef91a24-bf3a-3d0b-da44-f153b788df10
* Content: [Push content types to a hub](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/push-content-type-to-hub)
* Content Source: [microsoft-365/contentunderstanding/push-content-type-to-hub.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/push-content-type-to-hub.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@CallumCrowley Thank you for your feedback. This seems to be a technical issue and we recommend you to contact Microsoft support via the need help link to resolve the issue or report it as a bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @CallumCrowley Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
