### ISSUE TITLE
Getting a mailbox not found error in Outlook on the web

### ISSUE THREAD

**Issue by jjtrinquet** [MicrosoftDocs/microsoft-365-docs#6119]
Hi,
I have this message when trying to sign in to email web, Office Business Standard 365.
There is a license assigned to this user.
The email address is a custom domain name jj-trinquet.com. The email address is avocat@jj-trinquet.com
Any help with this will be greatly appreciated.
Yours kindly JJ Trinquet 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00421a8e-42cf-c393-f91d-da1b7d7cc7da
* Version Independent ID: de00b816-762d-2171-eb7f-1ce6a55ec189
* Content: [Getting a mailbox not found error in Outlook on the web - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/mailbox-not-found-error?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/mailbox-not-found-error.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/mailbox-not-found-error.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by shollist** [comment]
I've hit this error with two accounts today. Both have recently been updated, both have licenses, both have had email addresses and mailboxes in 365 for a while now.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @jjtrinquet Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
