### ISSUE TITLE
[LOC] Typo in a sentence

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/microsoft-365-docs#612]
Hello, there is a typo in an article please see more details below:

**Repro steps:**

1. Go to https://docs.microsoft.com/en-us/microsoft-365/enterprise/secure-teams-highly-regulated-data-scenario
2. Search for following sentence: "Use a sensitivity sublabel when you have a large number of labels or want to organize labels for private teams the under the highly regulated label."
3. See the redundant word "the" before the "under the highly regulated label."

**Actual results**:
redundant word "the" is present in the sentence
**Expected results**:
redundat word "the" should not be present

**GH article**:
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/secure-teams-highly-regulated-data-scenario.md
![image](https://user-images.githubusercontent.com/47977325/67468741-51fc9a80-f64b-11e9-8857-33b6a69cf2cf.png)

**Comment by mypil** [comment]
@OfficeGlobal - PR #615 has been created to fix and close this issue once the PR is merged.

Thank you for your contribution to make the docs better!  Much appreciated!
