### ISSUE TITLE
How does teams manage blocked users?

### ISSUE THREAD

**Issue by BrianLeFlem** [MicrosoftDocs/microsoft-365-docs#6120]
Would be good if the page described how people are removed from the team.  We blocked a user while they were on holiday, and they got removed from the team.  When they unblocked them today, they did not automatically get added back into the team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c674715-5bd3-7e2c-6689-7ce636be53bc
* Version Independent ID: 0b3649a2-cf33-346d-86dc-c1a984c67502
* Content: [Create an org-wide team](https://docs.microsoft.com/en-us/microsoft-365/business-video/org-wide-team?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/org-wide-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/org-wide-team.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@BrianLeFlem Thank you for your feedback. Are you referring to Blocking the users on teams or on the M365 admin center?

Thanks
Sri

**Comment by BrianLeFlem** [comment]
M365 Admin Center.  Cheers

**Comment by msbemba** [comment]
@BrianLeFlem Thank you for the response. I tested it and don't see the users getting removed from MS teams when they are blocked.

Blocking someone prevents anyone from signing in as this user, and is a good idea when you think their password or username may have been compromised. When you block someone, it immediately stops any new sign-ins for that account, and if they’re signed in, they’ll be automatically signed out from all Microsoft services within 60 minutes.

This won't stop the account from receiving mail or remove them from Microsoft teams. However, If you find the accounts getting removed when blocked, please reach out to Microsoft support via the need help button to resolve the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @BrianLeFlem Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
