### ISSUE TITLE
This does not seem to be working yet

### ISSUE THREAD

**Issue by stackorama** [MicrosoftDocs/microsoft-365-docs#6122]
[Enter feedback here]
I am just wondering if this is working for anyone.  I have turned on Sharing externally via the Microsoft 365 admin center per the article and created a policy in exchange and assigned it to myself.  Currently it is still not working about 1/2hr later.  Anyone know how long it takes to kick in? - Christine
![image](https://user-images.githubusercontent.com/12790368/130489994-3203d1c6-9cd6-4e26-acb2-6d8aa58774c6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b3bda19-af86-20e8-92c4-ccb0caee7cd2
* Version Independent ID: cc93f793-d8bf-e508-d1c1-ddada942623d
* Content: [Share calendars with external users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/share-calendars-with-external-users?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/manage/share-calendars-with-external-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/share-calendars-with-external-users.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @stackorama Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
