### ISSUE TITLE
Add info about Outlook.com (Consumer Sender Support)

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#6123]
[Enter feedback here]
Please add a section in the very end of the doc that the filtering and delisting process for **Outlook.com** - our consumer service - is different. Please ask to follow the link https://sendersupport.olc.protection.outlook.com/pm/troubleshooting.aspx where the process is described for all senders to our consumer service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Remove yourself from the blocked senders list - Office 365](https://review.docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide&branch=master)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by hudish** [comment]
Beg to differ: many issues in the comments of this article are about outlook.com deliverability. Mentioning the right article reference will provide self-guidance to resolve those issues.

Please reconsider?

Alex

**Comment by msbemba** [comment]
@hudish Thank you for the response. The documents are related to Microsoft 365 and its customers. If this is a repository centered on all Microsoft products, I'll be the first one to relate it to the document. But unfortunately, that is not the case.

Hope you understand!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hudish Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by msbemba** [comment]
@yogkumgit I can confirm that Tracy has added the information in the document - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide#more-information



Thanks
Sri
