### ISSUE TITLE
Convert all targeted devices to Autopilot must be set to NO for autopilot test to succeed

### ISSUE THREAD

**Issue by sveinungre** [MicrosoftDocs/microsoft-365-docs#6124]
Please update documentation to state that if you have an existing autopilot deployment profile (even if its not assigned), the setting "Convert all targeted devices to Autopilot" must be set to "No" for the managed desktop readiness test for autopilot to succeed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30588070-d5b3-ca1a-2601-234f22d3866d
* Version Independent ID: c0a91e5f-93a6-3df6-dfd3-940b90de3729
* Content: [Fix issues found by the readiness assessment tool - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-ready/readiness-assessment-fix?view=o365-worldwide#autopilot-deployment-profile)
* Content Source: [microsoft-365/managed-desktop/get-ready/readiness-assessment-fix.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-ready/readiness-assessment-fix.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@yogkumgit Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6201

Once the author approves the PR, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@jaimeo  PR merge request pending. Thanks

**Comment by jaimeo** [comment]
@hathin can you confirm this is accurate?

**Comment by jaimeo** [comment]
@hathin can you confirm this is accurate?

**Comment by sveinungre** [comment]
You can refer to Microsoft support case 27126560 for confirmation.

**Comment by jaimeo** [comment]
W/o a direct link, I have not way to access that support case. And I still want confirmation from the product SME.

**Comment by hathin** [comment]
Hi all,

Confirming that this is accurate and we need to add this language to the docs.

Thanks,
Harman

**Comment by yogkumgit** [comment]
@msbemba

**Comment by jaimeo** [comment]
I don't have a button to merge this directly, but please go ahead and merge.

**Comment by yogkumgit** [comment]
@tiburd Kindly help.

**Comment by tiburd** [comment]
Merged PR. Closing issue. Thanks!
