### ISSUE TITLE
Error: [object Object]

### ISSUE THREAD

**Issue by ckhordiasma** [MicrosoftDocs/microsoft-365-docs#6125]
When I try to use the live response capability with a simple command, like `processes`, i just get the error response: 

Error: [object Object]

Any reason why this is happening??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbb2f7d-1aa5-4536-d22b-8b5b1f94f5b3
* Version Independent ID: 8878dc91-fdb6-349f-a0c2-5d4717fb40ed
* Content: [Live response command examples](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response-command-examples?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/live-response-command-examples.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/live-response-command-examples.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @ckhordiasma Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
