### ISSUE TITLE
Thank microsoft-365

### ISSUE THREAD

**Issue by 16015299** [MicrosoftDocs/microsoft-365-docs#6126]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de70c835-f408-83a6-3cc7-885756bd7152
* Version Independent ID: 076708dd-80e4-39d7-7e23-42730c106900
* Content: [How automated investigation and response works in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/automated-investigation-response-office?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/automated-investigation-response-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/automated-investigation-response-office.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@16015299 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any feedback from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
