### ISSUE TITLE
Wrong image on page

### ISSUE THREAD

**Issue by weshieone** [MicrosoftDocs/microsoft-365-docs#6130]
[Enter feedback here]

In the section " how to create an EDiscovery hold"  item 7  choose locations wizard. There is an image of Choose locations, that is wrong. It shows the locations wizard  for creating a search not a hold. In a search if you turn on exchange  mailboxes this shows under the included  heading as All. But in an Ediscovery hold you  have to select specific mailboxes therefore under the included heading should show as None in the image.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7263ba97-4e79-7144-a9d4-5138fe228fa2
* Version Independent ID: 316e242e-7f37-592e-9c8f-e754b23a29ca
* Content: [Create eDiscovery holds in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-ediscovery-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-ediscovery-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@weshieone Thanks for the heads up. Appreciate it. I will update the screenshot.
