### ISSUE TITLE
is there GA timeline?

### ISSUE THREAD

**Issue by Paul-Lo** [MicrosoftDocs/microsoft-365-docs#6133]
is there any GA timeline for this feature?

Quite a few customers are asking GA for this. Without this feature GA, AIP has huge negative impact on productivity and on their willing to purchase more user licenses. 

thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed8ccbd-b955-4a11-f4dd-3a70b549a5f7
* Version Independent ID: 257024d1-afb3-954f-c848-21549cb64fac
* Content: [Enable co-authoring for documents encrypted by sensitivity labels in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-coauthoring?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-coauthoring.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-coauthoring.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by Paul-Lo** [comment]
thanks for someone who see this request. 
My customer asks if they enable this "AIP encrypted file co-authoring" preview feature in their production tenant, can the encrypted files still be opened and edited after GA? Customer is afraid that their company important files that work in the Preview phase won't be able to be opened after GA.

This customer is Microsoft Premier support customer and opened a case but CSS doesn't support Preview feature and can't escalate since it's not even GA.

My alias is paulky and please feel free to ping me in teams for further discussion. 
thanks a lot.

**Comment by cabailey** [comment]
We can't give release timelines in the technical docs - the Microsoft 365 roadmap is the go-to place for this information.  For this feature, they have September as the expected GA date, so very soon!  https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=82112
