### ISSUE TITLE
Inquiry on how we can configure successful sending of malicious/suspicious attachments to a pre-configured end user.

### ISSUE THREAD

**Issue by glr0221** [MicrosoftDocs/microsoft-365-docs#6135]
Hello Microsoft, 

I would just like to inquire if there is a way for us to bypass the anti-malware mechanism and to be able to successfully send/receive emails with malicious or suspicious attachments to a particular email address.

The use-case for which is when we are sending such samples to our own internal security team who may want a copy of the said attachment for further analysis.

Thank you very much.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 180de890-8454-96ba-3a68-53d1a9a0b319
* Version Independent ID: a702d0cf-c426-f3d7-ed50-144e4f26d4d7
* Content: [Anti-malware protection FAQ](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-malware-protection-faq-eop?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-malware-protection-faq-eop.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-malware-protection-faq-eop.yml)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@glr0221, advanced delivery to SecOps mailboxes is what you want:

<https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-advanced-delivery>

**Comment by yogkumgit** [comment]
@glr0221 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by glr0221** [comment]
Sorry for the late response @yogkumgit @chrisda. 

I had been a bit busy for some time. Our team will surely look into thiis. 
Thank you so very much!!!
