### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by dagroll** [MicrosoftDocs/microsoft-365-docs#6138]
Under "Type of Monitoring" the link for the description of "Use System Center to Monitor Microsoft 365" is no longer active and should be updated or removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f903b4-8b86-70f6-8495-e8a9905ceb03
* Version Independent ID: 57fd3cc7-af0e-8d08-40c7-a5e070c1a237
* Content: [Monitor Microsoft 365 connectivity - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/monitor-connectivity?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/monitor-connectivity.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/monitor-connectivity.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@dagroll Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6274

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dagroll Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
