### ISSUE TITLE
Migration Permanent Exception Error

### ISSUE THREAD

**Issue by karmicsynergy** [MicrosoftDocs/microsoft-365-docs#6139]
this does not work, i spent time setting up the PowerShell parts witch eventual worked after updated discontinued commands 
but the actual migration part fails with one of the two below errors

1. MigrationPermanentException: Target user ‎'USER' already has a primary mailbox. --> Target user ‎'USER' already has a primary mailbox.

2. MigrationRecipientNotFoundException: A recipient wasn‎'t found for "USER" on the target. Create a recipient of the appropriate type for this migration on the target and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@karmicsynergy Thank you for your feedback. I'm currently testing this and will update the document if need be.

**Comment by msbemba** [comment]
@karmicsynergy Thank you for your feedback. Sorry about the delay, I was able to test the scripts and migrate using my lab tenant. If this continues to be an issue, please contact Microsoft support via the need help option in the M365 admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @karmicsynergy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
