### ISSUE TITLE
Client-based Authentication does not work on modern Macs

### ISSUE THREAD

**Issue by sverasch** [MicrosoftDocs/microsoft-365-docs#6141]
Outlook does not currently support CTK for authentication, it still utilizes the deprecated tokend framework. As a consequence, client certificates and SmartCards cannot be used for client certificates for authentication.

see https://answers.microsoft.com/en-us/msoffice/forum/all/emptyblank-certificate-after-launching-outlook-for/2fcfc2ac-023b-4529-b02b-4333c92a1279

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c62d861d-b54f-a023-ce0c-11e858660301
* Version Independent ID: 3c49dd2d-22c1-3755-4a46-f7adcaa4f1b2
* Content: [Microsoft 365 Client App Support: Certificate-based Authentication - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-client-support-certificate-based-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-client-support-certificate-based-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-client-support-certificate-based-authentication.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@sverasch  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
