### ISSUE TITLE
Please update us on the changes made by MC275344.

### ISSUE THREAD

**Issue by teraco** [MicrosoftDocs/microsoft-365-docs#6145]
Microsoft 365 admin center: Reports in the Admin Center - user information pseudonymized by default
According to MC275344, the default value is "cannot be able to see user identifiable information" and you need to go to the Settings > Org Settings > Services page to see the user information.

The page says "In the Reports pane, select the options you want, and then save your changes." Could you please correct this statement?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eaa6e98-66e9-aad3-2d67-543c22f4ce4b
* Version Independent ID: 26bddf9e-f338-329f-76e5-302a1343f7f1
* Content: [Activity Reports in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/activity-reports.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@teraco Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6221

Thanks
Sri

**Comment by yogkumgit** [comment]
@kwekuako  PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @teraco Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
