### ISSUE TITLE
Missing IP Range in ID12 for *.teams.microsoft.com

### ISSUE THREAD

**Issue by Nyffe-Noob** [MicrosoftDocs/microsoft-365-docs#6147]
[Enter feedback here]
The ip range for monitoringplatform.teams.microsoft.com ist missing in ID12 (*.teams.microsoft.com)
![image](https://user-images.githubusercontent.com/84561268/130766492-a8786cce-b92e-43bd-a3b5-0ff6e5ee6142.png)

The URL "https://monitoringplatform.teams.microsoft.com/api/v1/mta/rule" is used in the Teams Admin Center - Notifications&Alerts - Rules Page
![image](https://user-images.githubusercontent.com/84561268/130766764-032352bb-da42-47c3-b2f7-2d4e7ce886ea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. It appears that the IP addresses for the URL monitoringplatform.teams.microsoft.com have been changed to the 52.112.0.0/14 CIDR block, which is included in ID 12. -Kelley
