### ISSUE TITLE
Update Links from Windows Virtual Desktop to Azure Virtual Desktop

### ISSUE THREAD

**Issue by BenMartinBaur** [MicrosoftDocs/microsoft-365-docs#6148]
Hi, the article is referring to "Windows Virtual Desktop" what is now "Azure Virtual Desktop".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87fa68a-a881-7ab7-97df-5da73dc56692
* Version Independent ID: 0c031441-cc26-903a-4d53-c044ea790d2d
* Content: [Microsoft Defender Antivirus Virtual Desktop Infrastructure deployment guide](https://review.docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus?view=o365-worldwide&branch=main)
* Content Source: [microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@BenMartinBaur Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6222

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BenMartinBaur Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
