### ISSUE TITLE
Shared Mailbox Licensing

### ISSUE THREAD

**Issue by DanMan32** [MicrosoftDocs/microsoft-365-docs#6149]
O365 admin portal does not show shared mailbox user accounts, licensed or not.

I could not find any current instructions on how to add a license to a shared mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd8b6d7d-1a95-d263-595e-78649069275f
* Version Independent ID: bacc64b9-916b-bb3d-a885-46fe5d096826
* Content: [Remove license from shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/remove-license-from-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/remove-license-from-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/remove-license-from-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@DanMan32 Thank you for your feedback. I was able to test this on my lab and can view the details under users-->Active users. All mailboxes are listed here and usually shared mailboxes that are not licensed show up as unlicensed.

![image](https://user-images.githubusercontent.com/45987684/131551693-b5c42285-5805-47e2-ad70-da39338737a1.png)


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DanMan32 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
