### ISSUE TITLE
Correction on "Microsoft Teams (currently in TAP Preview)" is now GA as of 7/27/2021

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#6150]
Please update the 2nd bullet to reflect that Teams is now in GA no longer "TAP Preview"
"Microsoft Teams (currently in TAP Preview): Safe Links protection for links in Teams conversations, group chats, or from channels is also controlled by Safe Links policies. There is no default Safe Links policy, so to get the protection of Safe Links in Teams, you need to create one or more Safe Links policies."
Here is the GA announcement:
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/announcing-general-availability-of-safe-links-for-microsoft/ba-p/2588677

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@itguysocal, thanks. I also found some other references to fix in the following topics:

 - <https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-safe-links-policies>
- <https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office>

Thanks for the feedback.

Closing
