### ISSUE TITLE
‎Manage mailbox auditing

### ISSUE THREAD

**Issue by Blake-nisius** [MicrosoftDocs/microsoft-365-docs#6157]
This article states: 

> To retrieve mailbox audit log entries for users without E5 licenses, you can:
>
> - Manually enable mailbox auditing on individual mailboxes (run the command, `Set-Mailbox -Identity [MailboxIdentity] -AuditEnabled $true)`. After you do this, you can use audit log searches in the Microsoft 365 compliance center or via the Office 365 Management Activity API."

Does this still have to be done if at the organizational level we have mailbox auditing enabled as per this section?: 

> Although mailbox audit logging on by default is enabled for all organizations, only users with E5 licenses will return mailbox audit log events in audit log searches in the Microsoft 365 compliance center or via the Office 365 Management Activity API by default."

It seems contradictory to state that its enabled for all organizations by default, yet action is required on my part to enable as a non E5 customer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@Blake-nisius Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
