### ISSUE TITLE
Typos in Sample code 

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#6158]
In the Permanently delete a Microsoft 365 group section, the PowerShell scripts include opening and closing quotes, which is an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18c17598-3ade-528a-922d-1904f194b931
* Version Independent ID: a9561e0d-3247-58bd-654b-41898affc6ea
* Content: [Manage a group in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-groups?view=o365-worldwide#permanently-delete-a-microsoft-365-group)
* Content Source: [microsoft-365/admin/create-groups/manage-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@sparkitect Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6216

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sparkitect Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
