### ISSUE TITLE
Actions changed since MC191185 and Roadmap ID 55102.

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/microsoft-365-docs#616]
Block Sender and Review is only options now. Also please note, you require now to sign into Quarantine portal, where previously you didn't - Great from a mobile device. Not now :( 
The list doesn't include Size as well now

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedcd379-0c7e-5b68-be04-e272ac53638d
* Version Independent ID: 664acd84-b4df-c943-e027-677f4340768e
* Content: [Use user spam notifications to release and report quarantined messages in Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages#feedback)
* Content Source: [microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@DavidTaig - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by jptechie** [comment]
All my users as of 24 hours ago were able to release quarantine email directly from their inbox.  The release button at a minimum  needs to be restored! Please restore these options.  Asking a user to sign in to release a quarantined email just increased the probably of falling for a malicious phishing campaign. Lastly- thanks for the notification about this change.

**Comment by mypil** [comment]
@jptechie - We suggest for you to submit your feedback via **[UserVoice](https://office365.uservoice.com)**. Thank you!
