### ISSUE TITLE
Document should also link to doc describing how to enable external e-mail forwarding

### ISSUE THREAD

**Issue by richrundmsft** [MicrosoftDocs/microsoft-365-docs#6161]
The current document doesn't describe the steps need to configure external e-mail forwarding. 

I think it would be beneficial to link to the following document which describes steps needed to allow e-mail to be forwarded externally:
https://docs.microsoft.com/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide

The default behavior seems to be for Defender to prevent forwarding of e-mail externally, so without following the steps in the above document users who try to forward e-mail externally get an NDR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@richrundmsft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6223

Thanks
Sri

**Comment by yogkumgit** [comment]
@kwekuako  PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @richrundmsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
