### ISSUE TITLE
Expiration policy for archived Teams

### ISSUE THREAD

**Issue by jwspo** [MicrosoftDocs/microsoft-365-docs#6167]
Hi Team,
the expiration policy also applies to teams that have been archived. Is there a way to avoid this?

**Comment by yogkumgit** [comment]
@jwspo We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
