### ISSUE TITLE
First Contact safety tip & user privacy?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/microsoft-365-docs#6171]
One of the notifications of First Contact safety tip is: "Some people who received this message don't often get e-mail from xxx". Is that a potential privacy issue, as if there are not many recipients, the user learns about the communication patterns of the user's colleagues? This needs to be documented in detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide#first-contact-safety-tip)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ArttuArstila, I'm told that the system does not learn communication patters of the user's colleagues. It only learns the patterns of the user themselves.

When multiple protected recipients receive the same message AND if most of those recipients have never received a message from that sender, THEN those recipients will receive the first contact safety tip.

Does this make sense?

**Comment by ArttuArstila** [comment]
Thanks for the reply! Let me explain the concern with an example. We hade an incoming mail where there were three internal recipients. One of them saw this tip: "Some people who received this message don't often get e-mail from xxx". Now the recipient who got the tip knows that the other two internal recipients do not regularly communicate with the sender - which means he learns about the communication habits of the others. If it is truly so, then it is an issue in EU countries for examples and should be documented.

**Comment by chrisda** [comment]
@ArttuArstila, I added the following Note to the first contact safety tip section:
 
> [!NOTE]
> If the message has multiple recipients, whether the tip is shown and to whom is based on a majority model. If the majority of recipients have never or don't often receive messages from the sender, then the affected recipients will receive the **Some people who received this message...** tip. If you're concerned that this behavior exposes the communication habits of one recipient to another, you should not enable the first contact safety tip and continue to use mail flow rules instead.

**Comment by ArttuArstila** [comment]
Thank you, this is good! The note is not yet visible, but I assume it will be soon.

**Comment by chrisda** [comment]
Yeah, I forgot to merge my changes yesterday. The update is visible now.
