### ISSUE TITLE
Peer to peer Traffic between to VPN endpoints must be also considered as part of the split tunnel traffic

### ISSUE THREAD

**Issue by aalejandroaraujo** [MicrosoftDocs/microsoft-365-docs#6174]
[This article is great, but lacks of an explicit explanation about how should P2P traffic behave in case there're two clients connected to the VPN (which should be directly between them, using local Internet breakout). If it is somewhere mentioned, it's not clearly documented and references to "peer to peer" or "endpoint to endpoint" or "P2P"  traffic for two clients on the VPN network must be considered here too.
Also the pictures should include that scenario too, in which two different computers are remotely connected to the VPN network and peer to peer traffic happens through the Teams service and not over the VPN network either]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b957cd-f53c-0e64-9be5-3288ff9f7e5e
* Version Independent ID: 179c5c9e-4bfb-9626-baea-75be00adf639
* Content: [Overview: VPN split tunneling with Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-split-tunnel?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-split-tunnel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. This question is addressed in a new article here: https://docs.microsoft.com/microsoft-365/enterprise/microsoft-365-vpn-securing-teams.
