### ISSUE TITLE
Using SafeDocs license to control the rollout?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/microsoft-365-docs#6179]
Enabling the feature is a global setting, which is bit problematic for large organizations. Now there is "Office 365 SafeDocs" license in E5 plans. Can enabling/disabling this license be used to control the deployment? If so, would be good to mention in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
It's true that Safe Documents is enabled or disabled globally, but only the users who (as described in the topic) have Microsoft 365 E5 or Microsoft 365 E5 Security licenses assigned get the protection.

I would presume that if Office 365 SafeDocs licenses can be assigned or removed without affecting other E5 features, then yeah, you can use that to control who has it.

If you want a definitive answer, I would suggest opening a support case. Report back here with what they say, and I'll update the documentation accordingly.

**Comment by ArttuArstila** [comment]
Thanks for replying! I started my own test on this, and preliminarily it looks that the user-level license control would work. I know it is not mandatory for documentation, but considering that very large end user organizations want to roll this out, they naturally want to pilot it and roll out gradually. And if there is a method for that, it would be useful for it to be documented.

**Comment by chrisda** [comment]
@ArttuArstila, OK I added some information to the topic. Have a look, and make any updates that you see fit as described in <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

**Comment by ArttuArstila** [comment]
I did not dare to make this update myself as I was not certain that individual access can be configured this way. Good to have it in the docs now, thank you!

**Comment by chrisda** [comment]
@ArttuArstila, I basically guessed about how to do it (although it was an educated guess). Typically, you turn whatever it is on globally, then turn it off individually. In this case, the other way around didn't make any sense. By asking you to make updates, I was merely deferring to your hands-on knowledge and testing experience to see if I missed anything, and to make *slight* modifications as required. Thanks.
