### ISSUE TITLE
If "com.microsoft.scmx" isn't listed, select "Microsoft Defender for Endpoint"

### ISSUE THREAD

**Issue by toinevl** [MicrosoftDocs/microsoft-365-docs#6180]
the process "com.microsoft.scmx" isn't listed on my device (Poco F3, MIUI 12.5.3) - you need to select "Microsoft Defender for Endpoint" as the App in order to make this work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3c4a1d-a030-0d30-cce5-d12337fcfdd4
* Version Independent ID: dca55864-acee-0617-218a-efd08eae46eb
* Content: [Troubleshoot issues on Microsoft Defender for Endpoint on Android](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/android-support-signin?view=o365-worldwide#unable-to-allow-permission-for-permanent-protection-during-onboarding-on-some-oem-devices)
* Content Source: [microsoft-365/security/defender-endpoint/android-support-signin.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/android-support-signin.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@toinevl Thank you for your feedback. I was able to test this. It shows Microsoft defender for endpoint, which you need to locate and select Don’t Optimize. We have that updated in our document.

@yogkumgit There are no changes required in this document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @toinevl Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
