### ISSUE TITLE
Guest user capabilities incomplete...

### ISSUE THREAD

**Issue by jitterbox** [MicrosoftDocs/microsoft-365-docs#6188]
Guest users can also access their plans/tasks in **Planner** (but only via mobile app), which is not noted.
And for Teams access, they can use their "guest context" by switching organizations, but only via mobile and desktop apps (not web apps).

The "organization switcher" is only available in a handful of places, none of which involve the core Office 365 web apps where guest access is supported (Teams, SharePoint)... guest access is not at all intuitive, can the docs help provide better overall clarification of how it works?

Minimally, can you update this article with a comprehensive list of all capabilities guest users truly have, and via which app types (or platforms)?

This really calls for a matrix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1015a9d3-f0bb-dad5-7210-e3dd9b62881c
* Version Independent ID: 5c517c9b-cd05-2794-2f5d-c89c4d72b4a4
* Content: [Guest users in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-guest-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-guest-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-guest-users.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@kwekuako Thanks for your reply in the email. Will wait for the update.

**Comment by yogkumgit** [comment]
@jitterbox Author confirmed that he has added in the backlog. Document will be updated accordingly. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
