### ISSUE TITLE
No wildcard search as stated

### ISSUE THREAD

**Issue by andy-guillen** [MicrosoftDocs/microsoft-365-docs#619]
Hello,

The article states "Wildcards are supported (*@contoso.com or scot?@contoso.com)" and per Microsoft escalation support ticket we opened, the only available wildcard is *@contoso.com and not scot?@contoso.com. Please update article accordingly.

Thank you,
Andy

**Comment by mypil** [comment]
@andy-guillen - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by andy-guillen** [comment]
Hello,

Please see the link below:

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/message-trace-scc#options-for-a-new-message-trace

Thank you,
Andy

Pardon typos. Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mypil** [comment]
@andy-guillen  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
Topic was updated, so closing this issue.
