### ISSUE TITLE
Required roles for activity explorer

### ISSUE THREAD

**Issue by Wh00T** [MicrosoftDocs/microsoft-365-docs#6190]
Hi,

you recently removed the roles "Reports reader" & "Security reader" for access to the Activity explorer:
https://github.com/MicrosoftDocs/microsoft-365-docs/commit/1421931300959b540ef9753daf4375fb76782621

"Changing the roles required for viewing Activity explorer. The reader roles no more have access to activity explorer(tested and verified)"
Small mistake here: security reader still has access. There is a delay between assigning the role and being able to access the activity explorer blade (took about 1hr in my lab).
Reports reader lost access, thats correct.

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Wh00T Thank you for your feedback. I have been assigned the role for over an hour and still do not have access to activity explorer. I'll wait for another 24 hours to test and update.

CC : @chrfox 

Thanks
Sri

**Comment by Wh00T** [comment]
Some more info: I tested with a new user and the AAD role "Security reader". I access the Activity Explorer via:
- Data Classification > Activity Explorer
OR
- Data Loss Prevention > Activity Explorer

Using the first way, there is an error message popping up that I don't have permission once I click on Data Classification. I just acknowledge the popup with OK and switch to the Activity Explorer tab. Adjust the dates and all data is visible.
No errors if I use the 2nd way via DLP.

**Comment by msbemba** [comment]
@Wh00T Thank you for your response. I'm able to reproduce the issue. I'll work with the author and update accordingly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrfox

**Comment by msbemba** [comment]
@Wh00T Thank you for your response. We have updated the document - https://docs.microsoft.com/en-ca/microsoft-365/compliance/data-classification-activity-explorer?view=o365-worldwide with details on roles required to access activity explorer. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Wh00T Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
