### ISSUE TITLE
old info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#6192]
This page is 3 years old and I know that many things in DLP have changed. Please update as appropriate.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec12506-ca29-0a03-3b01-699cb22b7ab7
* Version Independent ID: 6dc6083d-fcde-3622-5653-61c5be4bb5db
* Content: [View the reports for data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/view-the-dlp-reports?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/view-the-dlp-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-the-dlp-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@chrfox Gentle reminder
