### ISSUE TITLE
Advanced hunting past 30 day retention

### ISSUE THREAD

**Issue by Nosferatu-Dk** [MicrosoftDocs/microsoft-365-docs#6205]
Is it possible to have advance hunting queries go back more than 30 days ?

If not possible, would Azure Sentinel be able to increase the data retention ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2bcd1e2-1c90-7d98-e930-e59a5425fbfa
* Version Independent ID: bd223ebe-79e8-bab6-fae7-9a2fec2872dd
* Content: [Overview of advanced hunting in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/advanced-hunting-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/advanced-hunting-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@Nosferatu-Dk Thank you for your feedback. Hunting data in Microsoft Defender ATP is only available for 30 days. Two new built-in methods of storing the data for an extended period are:

Azure Storage Account (https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview)
Azure Event Hub(https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-about)

I have added both the articles as related content to this document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6273

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Nosferatu-Dk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Nosferatu-Dk** [comment]
Thanks Sri, it's appreciated.


Den man. 6. sep. 2021 kl. 23.33 skrev Sriraman M S ***@***.***
