### ISSUE TITLE
Its not clear whether we can use this icons or not. 

### ISSUE THREAD

**Issue by KaushikDell** [MicrosoftDocs/microsoft-365-docs#6208]
[Enter feedback here]
Its not clear whether we can use this icons or not. 
what do you mean by permitted use ? how do you define that. 
can i copy those icons and use them in my powerbi reports (prod) or not..

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65739277-0243-0728-8216-523656c94435
* Version Independent ID: c70c7e14-c605-6a9a-003e-bd19cabdbce4
* Content: [Microsoft 365 architecture icons and templates](https://docs.microsoft.com/en-us/microsoft-365/solutions/architecture-icons-templates?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/architecture-icons-templates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/architecture-icons-templates.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by samanro** [comment]
You may use them in architectural diagrams, training materials, or documentation about Microsoft 365. I would not use them in a PowerBI report.
