### ISSUE TITLE
Bookings doesn't appear on Admin Center/Settings/Org Settings    https://admin.microsoft.com/#/Settings/Services

### ISSUE THREAD

**Issue by rondfw** [MicrosoftDocs/microsoft-365-docs#6209]
[Enter feedback here]
Bookings doesn't appear on Admin Center/Settings/Org Settings    https://admin.microsoft.com/#/Settings/Services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba164b8e-a574-0744-ce02-23bda994e505
* Version Independent ID: 05018469-d6f8-0eb5-956c-730991912f8b
* Content: [Turn Microsoft Bookings on or off](https://docs.microsoft.com/en-us/microsoft-365/bookings/turn-bookings-on-or-off?redirectSourcePath=%252fen-gb%252farticle%252fturn-microsoft-bookings-on-or-off-for-your-organization-c27537fa-525e-47a8-aadf-9b07ee75c227&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/turn-bookings-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/turn-bookings-on-or-off.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@rondfw Thank you for your feedback. I was able to test this in the lab and cannot repro the issue. I can view bookings under Org settings-->Services

![image](https://user-images.githubusercontent.com/45987684/131553996-ef257455-f5bb-40da-88ab-bfee372fb1f0.png)

If you have any of the below subscriptions and being a global administrator you still cannot view the bookings app, Please contact Microsoft support via the need help link in the admin center
 Office 365 A3, A5, E3, E5, F1, F3, Microsoft 365 A3, A5, E3, and E5, Business Standard, Business Premium are supported.

Hope this helps!

Thanks
Sri

**Comment by rondfw** [comment]
I don't doubt that it appears for you but please know that it doesn't appear for me.  Our license is E3 for education (but others available; see below).  As you suggested, I opened support ticket #:  27257081

![Screen Shot 2021-08-31 at 1 52 04 PM](https://user-images.githubusercontent.com/40880140/131559745-d55aad13-bac8-473c-a0ab-d1a7add4abc5.png)


![Screen Shot 2021-08-31 at 1 54 05 PM](https://user-images.githubusercontent.com/40880140/131559956-8b46c68b-b439-4e0c-a7bd-57b57236c9e7.png)

**Comment by rondfw** [comment]
![Screen Shot 2021-08-31 at 1 56 46 PM](https://user-images.githubusercontent.com/40880140/131560606-cb30f4d9-837d-404e-98b6-368cd2b8ad39.png)

**Comment by msbemba** [comment]
@rondfw Thank you for your response. This could be an issue with the tenant, you have done the right thing by contacting support.

@yogkumgit There are no changes required in the document.

Thanks
Sri

**Comment by kwekuako** [comment]
Hi @rondfw, I'm seeing Bookings in my test organization. Couple of questions:
1. Are you in the Microsoft 365 admin center on the Dashboard view or the Simplified view? If you're in Simplified view, use the navigation menu on top left of the screen or search for Bookings in the search bar.

2. Make sure that you're using a Microsoft 365 subscription that supports Bookings. Bookings is supported in the following:
