### ISSUE TITLE
this article is outdated 

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/microsoft-365-docs#621]
Unfortunately they changed the daily email last night to a new template.  the new template sucks i wish they kept the old one where you can release emails directly with a link in the email

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedcd379-0c7e-5b68-be04-e272ac53638d
* Version Independent ID: 664acd84-b4df-c943-e027-677f4340768e
* Content: [Use user spam notifications to release and report quarantined messages in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages)
* Content Source: [microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@netaneladar - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
