### ISSUE TITLE
Incorrect Reference

### ISSUE THREAD

**Issue by ehalsey** [MicrosoftDocs/microsoft-365-docs#6212]
Option #2 has an invalid link.  Should be a link to step 4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2ba944-52a9-1dc9-eebe-e16111a8ccc4
* Version Independent ID: 22f2b1ec-a287-b315-ae6c-caeabc86beba
* Content: [Step 2 - Save the contents of a former employee's mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-2?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-2.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ehalsey Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6219

Thanks
Sri
