### ISSUE TITLE
Report Message Add-in vs "Report as Junk"

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/microsoft-365-docs#6213]
I may have missed it, but I cannot see any mention of the exisitng "Report as Junk" functionality.

Is this add-in a replacement to the built-in Junk email handling?

![image](https://user-images.githubusercontent.com/1064418/131428697-80742844-3ec7-4ce8-a451-1172638a171e.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide#entireorg)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **siosulli**

**Comment by msbemba** [comment]
@anthonynz Thank you for your feedback. I'm on the latest build but don't see this option anymore. Could you please provide me more information on the version of the office?  I shall test and update the document accordingly. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @anthonynz We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by anthonynz** [comment]
Hi guys, sorry I completely missed the email notification for this one.

I'm running the lastest patched release of Outlook.
Microsoft® Outlook® for Microsoft 365 MSO (16.0.14326.20384) 64-bit 

The report as junk option has existed for a very long time, it just seems like the "report message" add-in is unnecessary, or does it provide additional functionality over and beyond the built-in functionality?

That's the only reason I raised it, because I couldn't see a clear explanation about how the add-in differs from the built-in feature.

**Comment by msbemba** [comment]
@anthonynz Thank you for your feedback. The Built-in function is not available on all office suites. You are correct, Both the options are available for people to report false negatives (bad email allowed) to Microsoft and its affiliates for analysis. The report Message Add-in does the same job as the built-in tool.

Hope this helps!

Thanks
Sri
