### ISSUE TITLE
Typo in article

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#6215]
Typo in the following text

"As a recipient of a quarantined message, what you can do to the message as an ordinary use (not an admin) is described in the following table:"

I believe this should read

"As a recipient of a quarantined message, what you can do to the message as an ordinary user (not an admin) is described in the following table:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfc15d1-833b-3139-6bc0-1acb97d507c8
* Version Independent ID: 31e24618-c2e6-4fe4-9651-04d6007548a4
* Content: [Find and release quarantined messages as a user - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pjrcdf, fixed. In the future, you too can make fixes like this yourself without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing.
