### ISSUE TITLE
Changes to SPF After DKIM

### ISSUE THREAD

**Issue by andypleasants** [MicrosoftDocs/microsoft-365-docs#622]
There is a section in this document that states:
However, there are some cases where you may need to update your SPF TXT record in DNS. For example........

You intend to set up DKIM and DMARC (recommended).

However I don't see what changes need to be made after setting up DKIM??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed62cce4-7497-d557-8ee9-1e9d65dfc408
* Version Independent ID: 58739750-4fee-52d1-be71-9d379f59ee91
* Content: [Set up SPF in Office 365 to help prevent spoofing](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by greg-lindsay** [comment]
The statement isn't meant to describe the updates that should be made to SPF. These changes would be very much dependent on the scenario. The statement is only meant to mention some scenarios where a change might be needed.

**Comment by mypil** [comment]
@andypleasants - From our understanding, the issue you raised has been answered by greg-lindsay. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by j0rt3g4** [comment]
In other words:

If you are in a single Office 365 cloud environment and you implement DKIM, there is no changes needed into SPF.

If you are on O365 but you are also sending emails from any external source (like goodady, namecheap, sendgrid or any other service) you'd need to add those into the SPF.

So the general rule is..
SPF is the policy where you say to the internet from which servers are allowed to send emails using your domain. that's it.
