### ISSUE TITLE
URL redirect expired

### ISSUE THREAD

**Issue by wobblewobble** [MicrosoftDocs/microsoft-365-docs#6226]
In the initial section the url directing you to the attack simulator **see Get started using Attack simulation training.** is redirecting you to https://protection.office.com/attacksimulator which has expired.
Needs to redirect to https://security.microsoft.com/attacksimulator?viewid=overview

Attack simulation training in Microsoft Defender for Office 365 lets you run benign cyberattack simulations on your organization to test your security policies and practices, as well as train your employees to increase their awareness and decrease their susceptibility to attacks. This article walks you through creating a simulated phishing attack using attack simulation training.

For getting started information about Attack simulation training, see Get started using Attack simulation training.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c312fd69-72cd-bc86-4fe1-993b60b97bc6
* Version Independent ID: b7887ba6-4775-39f0-e368-68f140ce233d
* Content: [Simulate a phishing attack with Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@wobblewobble, clarification, please. In the topic in question, I see the sentence you're talking about and the link you're talking about, but that "Get started using Attack simulation training" link goes to [Get started using Attack simulation training](https://docs.microsoft.com/microsoft-365/security/office-365-security/attack-simulation-training-get-started).

Neither of these topics contain any links to protection.office.com.

On the Overview tab of Attack simulation training at <https://security.microsoft.com/attacksimulator?viewid=overview>, I see a "Learn more about Attack simulation training" link, which incorrectly points to [Attack Simulator in the Security & Compliance Center](https://docs.microsoft.com/microsoft-365/security/office-365-security/attack-simulator).

So what exactly are we talking about?

**Comment by wobblewobble** [comment]
It appears to be fixed now! Apologies, but when I reported it, it was redirecting to the https://protection.office.com/attacksimulator page
