### ISSUE TITLE
Updates to screenshots and commands

### ISSUE THREAD

**Issue by desinnic** [MicrosoftDocs/microsoft-365-docs#6227]
[Would it be possible to update this page with the following changes

**Current**
Run MDELiveAnalyzer.ps1 
GetFile "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Downloads\MDEClientAnalyzerResult.zip"

**Requested**
Run MDELiveAnalyzerAV.ps1 <This is the script from the download link on the page>

**Requested**

GetFile "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\Downloads\MDEClientAnalyzerResult.zip" <Add this to separate section and highlight this to be used after the data is collected>

**Requested**

The screenshot shows Run MDATPLiveAnalyzer.ps1 should this changed to Run MDELiveAnalyzerAV.ps1

**Requested**

Is it possible to include a list of logs collected by the tool. This may help customers with troubleshooting especially connectivity checks 

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 085e66bf-0187-3a42-f624-aaa0658e627a
* Version Independent ID: 85a31808-2b3c-c39d-8cb9-cc053bdf26c5
* Content: [Collect support logs in Microsoft Defender for Endpoints using live response](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-collect-support-log?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-collect-support-log.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-collect-support-log.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@desinnic Thank you for your feedback. There are two scripts and you need to choose the appropriate one, 1) Microsoft Defender for Endpoint client sensor logs only and 2)Microsoft Defender for Endpoint client sensor and Antivirus logs. This document has steps and screenshots for 1). The only change for AV is that you would use a different Script to upload and run, the remaining instructions are the same. Let me know if you are requesting to see option 2 elaborated as well.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @desinnic Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
