### ISSUE TITLE
Who needs an E5-license

### ISSUE THREAD

**Issue by Simon-de-V** [MicrosoftDocs/microsoft-365-docs#623]
In the note it says 'Disposition reviews require an Office 365 Enterprise E5 subscription.'. It's unclear who actually needs an E5 subscription: only the persons in the 'Disposition Management role and the View-Only Audit Logs role' or everyone within the organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d552f987-1606-01f7-d600-5887968ae60c
* Version Independent ID: 8c5f88de-93e7-862e-0550-fb9ac012be35
* Content: [Overview of disposition reviews](https://docs.microsoft.com/en-us/microsoft-365/compliance/disposition-reviews#feedback)
* Content Source: [microsoft-365/compliance/disposition-reviews.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@Simon-de-V - Thank you for submitting feedback.

I will get this issue over to the O365ITPro writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
dear @Simon-de-V ,
Here, and for all other Office 365 features, licenses requirements are stated for users, not for administrators.
So, talking about disposition reviews, you will need E5 license for all users you want to enable disposition reviews labels for.
Thank you
