### ISSUE TITLE
Need to add onboardingStatus to list of Properties

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#6230]
onboardingStatus was added as a filterable property of Machines earlier this year  Need to add that to the list of properties on the page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71010864-b3f8-23e1-33fe-496f136bf2b7
* Version Independent ID: e4c58cda-d42f-4445-3a03-6f4c8c1e6460
* Content: [Machine resource type](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jrhi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6328

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jrhi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
