### ISSUE TITLE
Update Properties that support $filter - Machine - to include onboardingStatus

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#6231]
this section needs to include that onboardingStatus is a filterable property for Machines API:

Properties that support $filter
Alert: alertCreationTime, lastUpdateTime, incidentId,InvestigationId, status, severity and category.
Machine: ComputerDnsName, LastSeen, HealthStatus, OsPlatform, RiskScore and RbacGroupId
MachineAction: Status, MachineId, Type, Requestor and CreationDateTimeUtc.
Indicator: indicatorValue, indicatorType, creationTimeDateTimeUtc, createdBy, severity and action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72110011-1fc5-4e78-8e54-e43bc181b860
* Version Independent ID: c974e3d8-983a-02d4-d9dc-9603a3f8b510
* Content: [OData queries with Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-odata-samples?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/exposed-apis-odata-samples.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/exposed-apis-odata-samples.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jrhi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6272

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jrhi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
