### ISSUE TITLE
Cannot forward email for some reason

### ISSUE THREAD

**Issue by galdalali** [MicrosoftDocs/microsoft-365-docs#6235]
**Trying to configure email forwarding, enabled the forwarding and added remote domain according to the [documentation ](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide) but I get the following error when my Microsoft work mailbox try's to forward a mail to my personal mailbox:**

Remote Server returned '550 5.7.520 Access denied, Your organization does not allow external forwarding. Please contact your administrator for further assistance. AS(7555)'

Resent-From: <Gal@oversight-ar.com>
ARC-Seal: i=2; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=pass;
 b=ZX1I8OErEPpYNwHcLIgws+Q+a3d4Xx6uW4gHcXbQzghBi5HY+qVvxHLha/7cL1xGb77SyNWz2JOxU9zHW1v1BuJplEdfJc6O8SNCZJtNjjwgawO2Wxkn8AlQx+EeZ0T9rdGUVhCiQZ9F9kKcB8NHwYN8mIP34rVk1mR1TxeF97pRGCisOT10pHjwI6UdcXNyB3ErVKs5Osj4wsboo+Edtpj+3cw4/Sqiy38DWbIYNVdyIF8m9kfwubYVZ+qFBKhc5DHZrWEfQLVuAR9nMH1ymq+4crwchtl9ah/XK9RuueNwfjsIVPDEk4AIYUPnkd9pEEWQmFowm1cEkMzGwEiL4A==
ARC-Message-Signature: i=2; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901; h=From:Date:Subject:Message-ID:Content-Type:MIME-Version;
 bh=slzxmFSkxFTueg6Gsnp+kaTC0xE5vOVLw2G4zjhaXyU=;
 b=UWZuc0SAgYzS9Eby1k94p3h3Ox5cMeiBrUov0hZL+8QtFzH1ViIHGNhZiOIlkh3m+GwjqpqZ4whNikhyQXtGUv1cwhqL4VWsfrnw5bsIMg8+CxfzqO8nE0Dh8EvId+zD2qnMlTtgS8AoydK/aPbV/St5sNAMMZykbrg57wk8Yh07dF0jTK/82Ogacga6naa4nlc0RtcZE0UxG00TkgO5JoKoKSzUvyzEO0nOz15gutuXmev5OWxD6eeY3s7tG1ycz5je90QhfEhU03xpe1C2cxSe+8PIXgW3RMp1rvBoSAp8TwDfzM1w8EV4PXI3n2geRVoOYsCALChTmQevZMazeQ==
ARC-Authentication-Results: i=2; mx.microsoft.com 1; spf=pass (sender ip is
 40.92.75.102) smtp.rcpttodomain=oversight-ar.com smtp.mailfrom=hotmail.com;
 dmarc=pass (p=none sp=none pct=100) action=none header.from=hotmail.com;
 dkim=pass (signature was verified) header.d=hotmail.com; arc=pass (0 oda=0
 ltdi=1)
Received: from DB3PR08CA0002.eurprd08.prod.outlook.com (2603:10a6:8::15) by
 DU2PR01MB8406.eurprd01.prod.exchangelabs.com (2603:10a6:10:2dd::10) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4478.21; Thu, 2 Sep
 2021 07:22:45 +0000
Received: from DB8EUR06FT044.eop-eur06.prod.protection.outlook.com
 (2603:10a6:8:0:cafe::f3) by DB3PR08CA0002.outlook.office365.com
 (2603:10a6:8::15) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4478.17 via Frontend
 Transport; Thu, 2 Sep 2021 07:22:45 +0000
Authentication-Results: spf=pass (sender IP is 40.92.75.102)
 smtp.mailfrom=hotmail.com; oversight-ar.com; dkim=pass (signature was
 verified) header.d=hotmail.com;oversight-ar.com; dmarc=pass action=none
 header.from=hotmail.com;
Received-SPF: Pass (protection.outlook.com: domain of hotmail.com designates
 40.92.75.102 as permitted sender) receiver=protection.outlook.com;
 client-ip=40.92.75.102; helo=EUR04-VI1-obe.outbound.protection.outlook.com;
Received: from EUR04-VI1-obe.outbound.protection.outlook.com (40.92.75.102) by
 DB8EUR06FT044.mail.protection.outlook.com (10.233.253.24) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.4478.19 via Frontend Transport; Thu, 2 Sep 2021 07:22:45 +0000
ARC-Seal: i=1; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=none;
 b=B2681GWkOIZbwNWY5+gC3ysK5bfh2M892f5FwdKJeD4TAhfvNVDtSTU3XPbC0YOeY2ab3zpSsnbPsoOSiOi8yqz5y8314J12sLTsN1s28X41wAsXA51id9UtdjyvA3XqYdAxsQC2MLbHz93N9g72cMgLLsxfeoo5qhsdwzOttD/QZgfwPhF3HGrS0vGSVWDoyY3it9BT49kER7dg2IdDvo0iCMWDEh/doYYWC1DKFnv/6prbpQS3RrDeV9NSSy54o/CHK0koPm+bYZmoQJ0zG6hEUtzFU5vEymyXB7sNKkllxPMXUfwp+hE5AEi9GQqvAg2/tz7S0ZV9rvywB/3e2g==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=microsoft.com;
 s=arcselector9901;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=slzxmFSkxFTueg6Gsnp+kaTC0xE5vOVLw2G4zjhaXyU=;
 b=c4uK+cMmORDtmkt1dfSOUTNKqL3g/k1uNRWRe0/kqjb/901KJz/DmbjpbfHiTMj/23Yx1CK4kw3UMlCn7IiW+hc9n1pL72Pbd1eMnvwZqpDqHXaNlJhr84t2JrXEdnxOFvZgpwfJPtZfWgm8LyHephpGcMHTj/WDa3K2e3tr7F9IhQv3l5KY5wzZfmT2HSz1FV03tIh9es0/YuGNtnbwFaA+TL9tFnRoH+0LnLBHxxbrply0tk/aplNzjA9pUP9a4ZDWIDjSkizW0xXHCbFO5kwVnEl2SnwDem9QsO654N3NQJEfSZ0KOOLuiYyEtcgIEEkottdYSyjXj/PCc0LOFQ==
ARC-Authentication-Results: i=1; mx.microsoft.com 1; spf=none; dmarc=none;

dkim=none; arc=none
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=hotmail.com;
 s=selector1;
 h=From:Date:Subject:Message-ID:Content-Type:MIME-Version:X-MS-Exchange-SenderADCheck;
 bh=slzxmFSkxFTueg6Gsnp+kaTC0xE5vOVLw2G4zjhaXyU=;
 b=cAZUNNbHJ83TZ5JGy1ocVYFsbabhtw5L3ujTU4XbZPRSBH8j2MNpKpHrXpoBkS3y2b+VxJr/gESBOuo7rbq9T69/Ep8liO6fLtJtLyyWhlsymQLjLvqyrQGbCfhaVw2TLdEeUFjPuxPe40/kxMFBooFfaDchdjxUZz2uoN5RVaw9zve62/t3oVb4F1gaC1s1rHFKJRxpP0eLvGYJ9yugvKBui6Ipk9htAQHDiXQ52GctsnohTTMngBk3e1opPg6I/5DRghBU+Ck3/feitVCqimbrBNAcLLtmWCAMmw5JNanOOcXBk01PLh0xOYl0A4OM+d7C5XS6WFK1fDn4NPsY8w==
Received: from VI1PR02MB3999.eurprd02.prod.outlook.com (2603:10a6:803:7b::26)
 by VI1PR02MB4654.eurprd02.prod.outlook.com (2603:10a6:803:a2::21) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4436.24; Thu, 2 Sep
 2021 07:22:43 +0000
Received: from VI1PR02MB3999.eurprd02.prod.outlook.com
 ([fe80::c90f:c193:998c:8911]) by VI1PR02MB3999.eurprd02.prod.outlook.com
 ([fe80::c90f:c193:998c:8911%6]) with mapi id 15.20.4457.025; Thu, 2 Sep 2021
 07:22:43 +0000

**Comment by yogkumgit** [comment]
@galdalali  Please indicate which document you are referring to and what is your feedback. Thanks

**Comment by galdalali** [comment]
> @galdalali Please indicate which document you are referring to and what is your feedback. Thanks

Updated the issue

**Comment by denisebmsft** [comment]
@yogkumgit https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide

**Comment by msbemba** [comment]
@galdalali Thank you for your feedback. There are outbound spam filter policies that need to be configured.  This feature independence allows you to (for example) allow automatic forwarding in outbound spam filter policies, but use remote domains to control the external domains that users can forward messages to.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide#how-the-outbound-spam-filter-policy-settings-work-with-other-automatic-email-forwarding-controls

We have now updated the document with related content that talks about this change when setting up external forwarding. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6270

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @galdalali Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by galdalali** [comment]
Thanks that's clarifying things
