### ISSUE TITLE
Broken link - aka.ms/tsstools

### ISSUE THREAD

**Issue by deividfoggi** [MicrosoftDocs/microsoft-365-docs#6237]
Under the section _Additional support logs_, the link https://aka.ms/TssTools seems to be broken and it is opening bing,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b783ee-9449-56db-3abd-f17dcf6b5d54
* Version Independent ID: d2146ff5-4248-12ec-a873-c951220aaa14
* Content: [Implementing VPN split tunneling for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel?view=o365-worldwide#configuring-and-securing-teams-media-traffic)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@Jwaegebaert Thank you very much for the contribution and updating the documentation with PR. @deividfoggi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
