### ISSUE TITLE
Threat Experts - Documentation update

### ISSUE THREAD

**Issue by maharumman** [MicrosoftDocs/microsoft-365-docs#6238]
information about how to activate or apply for Targeted attack notifications is incorrect. the steps need to be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e312ba4d-6340-52f0-1290-7e5505f7a9c0
* Version Independent ID: f7d45e69-56d2-01c5-898c-2e039edafe04
* Content: [Microsoft Threat Experts](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-threat-experts?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-threat-experts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-threat-experts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@maharumman Thank you for your feedback. I'm able to follow the steps (Settings > Endpoints > General > Advanced features > Microsoft Threat Experts - Targeted Attack Notifications to apply) in our lab. 


![image](https://user-images.githubusercontent.com/45987684/132259407-e991c129-1dcc-44f8-86bb-8d18f5cf0931.png)

If this is not the case in your tenant, the issue could be related to your tenant and I'd recommend you to contact Microsoft support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @maharumman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
