### ISSUE TITLE
Links lead to 404 page

### ISSUE THREAD

**Issue by codylc** [MicrosoftDocs/microsoft-365-docs#6239]
Both hyperlinks for "Windows Defender Application Guard" and "Windows Defender System Guard" lead to a 404. Drop the markdown extension (.md) from the URL and the pages load correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f92f5322-fcf5-f9af-6ba8-692225b1b042
* Version Independent ID: ee810b60-b5b8-9355-b5bc-b26e983f9fd7
* Content: [Hardware-based isolation (Windows 10)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/overview-hardware-based-isolation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/overview-hardware-based-isolation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/overview-hardware-based-isolation.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@codylc Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6267

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @codylc Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
