### ISSUE TITLE
Domain Does not Resolve, is this accurate?

### ISSUE THREAD

**Issue by sullcromenterprise** [MicrosoftDocs/microsoft-365-docs#6240]
[Enter feedback here]

The domain notify.windows.com does not resolve to anything is this the correct domain or has it changed?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebbedca-b2ed-d094-bb51-739116c32497
* Version Independent ID: 75b0a1ca-b956-d04c-3626-ce700003aebf
* Content: [Troubleshoot Microsoft Defender for Endpoint live response issues](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-live-response?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-live-response.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-live-response.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Please reach out to support.
