### ISSUE TITLE
Impacts on changing the default domain

### ISSUE THREAD

**Issue by Stricnis** [MicrosoftDocs/microsoft-365-docs#6251]
In the section "How do I set or change the default domain in Microsoft 365?", that would be very useful to add a note detailing the implications of such a change in Exchange Online, OneDrive, Sharepoint Online, Dynamics etc...
Once all these apps are setup, this change is not so obvious and a few comments can be found on the internet, often contradictory (harmless vs dangerous).
According to your support, this change is harmless except if you go further (changing the UPN of the users, removing aliases and so on...). A piece of text in Microsoft documentation would be authoritative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.yml)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@Stricnis Thank you for your feedback. I have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6268

Thanks
Sri

**Comment by Stricnis** [comment]
You're welcome, thanks for the modifications!

**Comment by yogkumgit** [comment]
@pebaum  PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Stricnis Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
