### ISSUE TITLE
Sharepoint site usage page does not list correct site URLs

### ISSUE THREAD

**Issue by anze-brvar-cookie** [MicrosoftDocs/microsoft-365-docs#6253]
I am having some troubles reading out the [Sharepoint site usage page](https://portal.office.com/adminportal/home?#/reportsUsage/SharePointSiteUsageV1). The list of sites in the bottom of the page contains `Site URL` and `Site owner principal name`, but the values are looking to be some sort of UUID or hashed value.

Looking at [the docs](https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide) it's clear that values for `Site URL` in that list should be "The full URL of the site".

The same thing is returned on the graph API calling an endpoint below.

    https://graph.microsoft.com/v1.0/reports/getSharePointSiteUsageDetail(period='D30')

Can someone explain what those values represent? Is there a way to convert the returned `Site URL` to a real site URL or ID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5a67cc-bf49-d25c-f89b-60dd30948f6d
* Version Independent ID: 56a98096-97f9-67d4-d2ed-befc800b6771
* Content: [Microsoft 365 Reports in the admin center - SharePoint site usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/sharepoint-site-usage-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@anze-brvar-cookie Thank you for your feedback. I'll test it with reports and update it accordingly.

**Comment by anze-brvar-cookie** [comment]
@msbemba I dig out the [troubleshooting page](https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/reports-show-anonymous-user-name) describing the same error. This is actually a feature, anonymising the user IDs and site URLs and can be turned off in Microsoft 365 admin center unselecting the `In all reports, display de-identified names for users, groups, and sites`.

It would be nice however to include that details in [the docs](https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide).

![Screenshot 2021-09-10 at 15 24 55](https://user-images.githubusercontent.com/77897875/132861960-868fdf16-0baf-4436-aaca-ef688e34aa7c.png)

**Comment by msbemba** [comment]
@anze-brvar-cookie Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6311

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @anze-brvar-cookie Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
