### ISSUE TITLE
Bullet 5 is not showing the email address. It is a 32-character string.

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/microsoft-365-docs#6256]
Bullet 5 is not showing the email address. It is a 32-character string. Is there an error somewhere?

5. Username is the email address of the user who connected to Microsoft 365 services using Microsoft browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f954abb9-d978-b70d-c136-623a76317ddc
* Version Independent ID: d4a88bcd-ac54-ca82-9b9a-0e22da92b74b
* Content: [Microsoft 365 Reports in the admin center - Microsoft browser usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/browser-usage-report?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/browser-usage-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/browser-usage-report.md)
* Service: **o365-administration**
* GitHub Login: @sarahwxy
* Microsoft Alias: **waxiaoyu**

**Comment by msbemba** [comment]
@pagejustin Thank you for your feedback. I'll test the reports and update the document if need be.

Thanks
Sri

**Comment by pagejustin** [comment]
@msbemba Thank you. I opened a ticket with Miscrosoft and they walked me through the following instructions: https://docs.microsoft.com/en-us/office365/troubleshoot/miscellaneous/reports-show-anonymous-user-name

**Comment by yogkumgit** [comment]
@pagejustin If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
