### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by csritchie** [MicrosoftDocs/microsoft-365-docs#6257]
Typo within "Get an access token using PowerShell" section of this page.
$clientId variable is misspelled within the $response variable " -ClientId $cleintId "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb191c54-e48e-c031-5310-e2fd584dc412
* Version Independent ID: 201b65d3-a983-8746-3e02-631e5c77a792
* Content: [Create an app to access Microsoft 365 Defender APIs on behalf of a user](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-create-app-user-context?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/api-create-app-user-context.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/api-create-app-user-context.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@Jwaegebaert Thank you very much for the contribution and updating the documentation with PR. @csritchie Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
