### ISSUE TITLE
Missing People API

### ISSUE THREAD

**Issue by artekartian** [MicrosoftDocs/microsoft-365-docs#6259]
Hello,
The doc provides insufficient info in the section - Enable API usage for the project, Point 4.
Missing item “**People API**”. Without enabling People API, the migration always ends with an error to be find below.

Suggestion – change to point 4 to: “4. Repeat this process for Google Calendar API, **People API** and Contacts API.”

Error: TooManyTransientFailureRetriesPermanentException: The job encountered too many transient failures (61) and is quitting. The most common failure is GoogleContactClientTransientException/GoogleApiException with the hit count 60. --> The Remote Server has thrown an Exception because of 'Forbidden' status. --> Google.Apis.Requests.RequestError People API has not been used in project xxxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/people.googleapis.com/overview?project=xxxxxxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [403] Errors [ Message[People API has not been used in project xxxxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/people.googleapis.com/overview?project=xxxxxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.] Location[ - ] Reason[accessNotConfigured] Domain[usageLimits] ]
Last successful sync date: 9/4/2021 07:36
Data consistency score: Perfect

Thanks,
Sebastian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6aa6bf7-da0a-22fc-8c2f-0aaabddc890a
* Version Independent ID: 7cd582a0-3980-acf0-6f20-96c2f6765b8d
* Content: [Migrate business email and calendar from Google Workspace](https://docs.microsoft.com/en-us/microsoft-365/business-video/moveto-microsoft-365/migrate-email?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/moveto-microsoft-365/migrate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/moveto-microsoft-365/migrate-email.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@artekartian Thank you for your feddback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6297

Thanks
Sri

**Comment by artekartian** [comment]
Great to hear, thanks Sri.
seb

**Comment by yogkumgit** [comment]
@twernermsft  PR merge request pending. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @artekartian Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
