### ISSUE TITLE
The Content after 'The Office 365 CDN' section (after page 195) can not be shown in downloaded PDF.

### ISSUE THREAD

**Issue by EricKY26** [MicrosoftDocs/microsoft-365-docs#6265]
So I Click 'Download PDF' on the webpage of this Microsoft 365 Docs, 
The Content after 'The Office 365 CDN' section (after page 195) can not be shown in downloaded PDF.
![PDF](https://user-images.githubusercontent.com/19644162/132156689-0e6392da-894d-4f83-bc81-3c0beb893b04.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e3e4d9f-5c87-71ae-24c3-1d2490812632
* Version Independent ID: 12818354-d3c6-9058-78a5-495ad511fb6d
* Content: [Content delivery networks - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/content-delivery-networks?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/content-delivery-networks.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/content-delivery-networks.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
Update: platform bug. This is currently sitting with the dev team for the docs platform.
