### ISSUE TITLE
Lack of clarity

### ISSUE THREAD

**Issue by new-kirte** [MicrosoftDocs/microsoft-365-docs#6266]
[Enter feedback here]
This version is a step back. As an owner of Microsoft Defender product in the FIS organisation I need to know  exactly what data is stored in Azure, so I can communicate it to a regulator. These details were available in the previous version of this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df30eb4f-795f-17a3-2a9a-a68c73a2ba75
* Version Independent ID: d9f2b07e-0deb-2bc9-99e3-bdc4f7752914
* Content: [Microsoft Defender for Endpoint data storage and privacy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/data-storage-privacy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/data-storage-privacy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/data-storage-privacy.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Looking at the history of this page - it hasn't gone through major updates apart from rebranding. Not sure what exact Azure info is being sought for.

**Comment by new-kirte** [comment]
The exact information on what Defender data is stored on Azure, can the Azure integration be disabled, what would be the implication?
