### ISSUE TITLE
authenticator

### ISSUE THREAD

**Issue by virginia3930** [MicrosoftDocs/microsoft-365-docs#6275]
I mistakenly delete my email from authenticator, how can i retrieve my email?

**Comment by virginia3930** [comment]
If any one can explain how i can retrieve the email.

**Comment by yogkumgit** [comment]
@virginia3930 Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
