### ISSUE TITLE
ZAP for Phishing seem to be the same as Auto ZAP

### ISSUE THREAD

**Issue by farshadt2019** [MicrosoftDocs/microsoft-365-docs#6277]
What is the difference in Phase 4 between following items, they seem to be the same?

2. Zero-Hour Auto-purge (ZAP) for phishing retroactively detects and neutralizes malicious phishing messages that have already been delivered to Exchange Online mailboxes.

4. AP for phishing retroactively detects and neutralizes malicious spam messages that have already been delivered to Exchange Online mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e32e2ed-5ae3-d1c6-6a5b-25b225647dbf
* Version Independent ID: 3f5d0ae5-a9b0-f755-c2f6-c38c75e3e485
* Content: [Step-by-step threat protection stack in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@farshadt2019 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6325

Thanks
Sri

**Comment by yogkumgit** [comment]
@MSFTTracyP PR merge request is pending. Thanks

**Comment by chrisda** [comment]
Fixed in msemba's PR.

Closing
