### ISSUE TITLE
Incorrect - MDE for Linux Limitation

### ISSUE THREAD

**Issue by MS-Fraser** [MicrosoftDocs/microsoft-365-docs#6278]
The following capabilities are not currently supported on Linux endpoints:

Data loss prevention
Live response
SIEM

This section around SIEM limitation is incorrect. MDE Agents on Linux will generate alerts into the MDE Tenant which can be suck up via a SIEM using the API. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e914c02a-e905-fc32-439c-feb1fafa09b8
* Version Independent ID: 1a6a15e9-717a-33c1-b90e-96925c680228
* Content: [Microsoft Defender for Endpoint for non-Windows platforms](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/non-windows?view=o365-worldwide#microsoft-defender-for-endpoint-on-linux)
* Content Source: [microsoft-365/security/defender-endpoint/non-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/non-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MS-Fraser Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6324

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MS-Fraser Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
