### ISSUE TITLE
Which type of admin can edit payment methods?

### ISSUE THREAD

**Issue by gallafent** [MicrosoftDocs/microsoft-365-docs#6279]
It would be useful if this page told me which type of admin access is required to add / edit / delete a payment method. The full list of admin roles is long! I need to give access to a particular member of the team to do this, but clearly don't want to make them a global admin … I'm _guessing_ it is the “Billing admin” role, but it would be good to know for sure (and not have to “try it out” and repeatedly round-trip if I guessed wrongly!).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d84279a1-a40d-df46-a43c-f925a63f2a94
* Version Independent ID: 7689e7a8-0abc-eab9-f213-18e716ba9d5c
* Content: [Update your payment method](https://docs.microsoft.com/en-us/microsoft-365/business-video/update-payment?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/update-payment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/update-payment.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@gallafent Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6323

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gallafent Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
