### ISSUE TITLE
Can you add a link to the uservoice page boycotting this feature please

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/microsoft-365-docs#628]
This feature is a joke right?

https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/38878723-ability-to-block-self-service-purchase-capabilitie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by DDog80sRocked** [comment]
Voted to block this ability and passed it around for others to vote for it as well.  This is a step backwards for those that can't work this way.

**Comment by ctermaat** [comment]
So as an admin, you can’t block access to someone purchasing this, but you are left cleaning up the licensing mess afterwards: 

What happens to a self-service purchase if a user leaves the organization?
“Valid users will continue to have full use of the self-service purchase for the duration of the subscription. The subscription remains active until the purchaser directly cancels it or an admin requests that the subscription be cancelled through customer support. Admins may also choose to assign a centrally purchased license to users of the cancelled subscription.”

**Comment by wrooot** [comment]
Voting to add a control to block this.

**Comment by ClaudioTorresAcevedo** [comment]
Really, this is not something that Microsoft should be allowed to do. We are not prepared for all the administrative processes here. We have an Enterprise agreement for these things, reservations are being used for quick license handling. Also, we have approval that need to be taken into account. Please all vote asap on this, Microsoft have given us little time to act.

**Comment by PhatJez** [comment]
This is out of order by Microsoft. This contravenes our corporate purchasing policies and breaks any cost controls that we have. This should be a feature that can be switched off by admins at the behest of their organisation. To justify this move by stating that it adheres to governance is total BS, it completely blows a hole in ours. This must be optional for organisations. It just seems like a bid by Microsoft to generate more revenue of businesses to me.

**Comment by VanelopeVonGlitch** [comment]
It is not the first time Microsoft has released a feature that bypasses IT administrative controls.   Microsoft has been allowing users to do their own PowerApps trials and has been advertising and communicating directly with end-users for the past few years.   This is all completely inappropriate and unacceptable.

**Comment by PhatJez** [comment]
> It is not the first time Microsoft has released a feature that bypasses IT administrative controls.   Microsoft has been allowing users to do their own PowerApps trials and has been advertising and communicating directly with end-users for the past few years.   This is all completely inappropriate and unacceptable.

@VonGlitch , We disabled Ad-Hoc licensing (see https://community.powerbi.com/t5/Service/How-can-I-prevent-my-existing-users-from-starting-to-use-Power/td-p/689060) and then placed the SKU's under Azure Group Based licensing so that you can control who has access to any trials. Often there are ways to circumvent Microsoft's daft policy decisions, sadly in the case of this latest one they've really done us over.

**Comment by 86theheadaches** [comment]
This feature causes more problems than it solves. Strongly request that Microsoft provide ability to turn Self Service Purchase off !

**Comment by wrooot** [comment]
It can't be tested yet, but there might be a way once it is live https://office365itpros.com/2019/10/28/blocking-power-platform-self-service-purchases/

**Comment by PhononicIT** [comment]
Our company may already have purchased subscription licenses at a discount.  These licenses could go unused while end users purchase their own licenses at full cost.  Plus the added expense of Accounts Payable processing the individual purchases.

This change is inappropriate from the perspective of cost, administrative overhead, and support.

**Comment by GitHubFilipe** [comment]
Microsoft, you are going too far with this one. Stop it while you can.

**Comment by HandyAndyOnGitHub** [comment]
Our organisation requires a method to switch this OFF.  We have procurement processes for a reason.

**Comment by cmcatee-MSFT** [comment]
Based on your feedback, we’ve adjusted our approach to better address the needs of both IT admins and end users within organizations.  We are providing IT admins a way to turn off self-service purchasing on a per product basis via PowerShell.

**Comment by DDog80sRocked** [comment]
Hi @PhatJez.  Can you elaborate on how you leveraged Azure Group-based licensing to control trials for PowerApps?  We're looking to prevent that.  We already use group-based licensing so only people in a group get the PowerApps license but that doesn't prevent people from getting a PowerApps trial...
