### ISSUE TITLE
DKIM setup - which elements are mandatory and how to validate

### ISSUE THREAD

**Issue by TheS0upDrag0n** [MicrosoftDocs/microsoft-365-docs#6280]
I have been trying to enable DKIM for a new O365 domain. I am not a system admin - just a volunteer with some tech knowledge trying to manage email for a voluntary organization. I have completed the tasks in "Steps to Create, enable and disable DKIM from Microsoft 365 Defender portal" but it does not seem to have worked.

It is not clear to me whether that is all I need to do and how to validate that it has worked. Looking in the headers of sent messages DKIM seems to still be off. It would be helpful if this page could be updated to clarify which sections are necessary to enable DKIM and how to validate that it has worked. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@TheS0upDrag0n Thank you for your feedback. If you have enabled DKIM on the M365 Admin center, you can test it by sending an external email.  For example, Send it to your gmail.com or outlook.com account and check the headers to see if DKIM is Signed. If not, there could be an issue with the keys and you may have to contact Microsoft support from the need help option on the admin center.

Hope this helps!

Thanks
Sri

**Comment by TheS0upDrag0n** [comment]
Thanks. My point is that it is not very clear which topics in this page are mandatory. My issue has been resolved thanks to some support from MS - one key OK therefore passed by the GUI but other key hada  minor typo.
