### ISSUE TITLE
Event URL's have extra characters in Defender Endpoint Arcsight configuration documentation

### ISSUE THREAD

**Issue by loukkis** [MicrosoftDocs/microsoft-365-docs#6281]
Events URL's seems to have extra characters in it: `"<i></i>".` 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97959c89-9504-ec6d-5a47-f90b5b12a992
* Version Independent ID: 08382ab8-34a7-c11c-23a4-2e37c7f2f36f
* Content: [Configure Micro Focus ArcSight to pull Microsoft Defender for Endpoint detections](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-arcsight?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-arcsight.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-arcsight.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@loukkis Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6303

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @loukkis Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
