### ISSUE TITLE
404 error when adding yum repos to RHEL 8

### ISSUE THREAD

**Issue by stlccjmixen** [MicrosoftDocs/microsoft-365-docs#6282]
The add_apt_repo.yml playbook gets 404 errors when trying to navigate / add the yum repository to RHEL8. Also the following in the playbook for the RedHat block is not accurate:

- name: Add Microsoft DNF/YUM key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_os_family == "RedHat"

- name: Add  Microsoft yum repository for MDATP
  yum_repository:
    name: packages-microsoft-com-prod-[channel] <--(this is incorrect as there is no prod-prod package I could find on the site)
    description: Microsoft Defender for Endpoint
    file: microsoft-[channel]
    baseurl: https://packages.microsoft.com/config/[distro]/[version]/[channel]/ <--( when filled out RHEL 8 cannot find this repo)
    gpgcheck: yes
    enabled: Yes
  when: ansible_os_family == "RedHat"

Also when I went to the following page: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide

When I click on https://packages.microsoft.com/config/rhel/8/prod/ to find my package it gives a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5b7c531-90a1-7f6b-4c1d-0a126cdea398
* Version Independent ID: 5a10f1bb-6407-d706-0b79-bf448a8eda9d
* Content: [Deploy Microsoft Defender for Endpoint on Linux with Ansible](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-ansible?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-with-ansible.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by stlccjmixen** [comment]
Wanted to bump this and see if any update was available?

**Comment by yogkumgit** [comment]
@Dansimp Gentle reminder

**Comment by stlccjmixen** [comment]
It appears at some point or in another issue that my issue has been resolved. The repository pointers in the current documentation dated 03/25/2022 work for Ansible playbooks. Also noticed a few other changes where made to the playbooks as well on Microsoft's side.
