### ISSUE TITLE
Link to "Scheduler for Microsoft 365 licensing" leads nowhere.

### ISSUE THREAD

**Issue by Steltek** [MicrosoftDocs/microsoft-365-docs#6283]
Link to "Scheduler for Microsoft 365 licensing" (https://www.microsoft.com/microsoft-365/meeting-scheduler-pricing) leads nowhere. (target page is 404)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e510e72-fe28-afda-6b12-a51fb0c0f36b
* Version Independent ID: 2a420c61-a348-b61c-aa80-a90d5ce0410d
* Content: [Scheduler for Microsoft 365 Overview](https://docs.microsoft.com/en-GB/microsoft-365/scheduler/scheduler-overview?view=o365-worldwide#pricing-and-licensing)
* Content Source: [microsoft-365/scheduler/scheduler-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/scheduler/scheduler-overview.md)
* Service: **scheduler**
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by msbemba** [comment]
@Steltek Thank you for your feedback. I'm able to access the link now.

![image](https://user-images.githubusercontent.com/45987684/132698139-de724940-9b07-4b3e-b17f-f906cc86df70.png)

What is the locale that you see on the URL, Like you see en-us in this URL "https://www.microsoft.com/en-us/microsoft-365/meeting-scheduler-pricing?rtc=1" ?

Thanks
Sri

**Comment by Steltek** [comment]
https://www.microsoft.com/microsoft-365/meeting-scheduler-pricing just worked once for me now.

I'm coming from https://docs.microsoft.com/en-GB/microsoft-365/scheduler/scheduler-overview?view=o365-worldwide#pricing-and-licensing and the "Learn more" link redirects me to https://www.microsoft.com/fr-ww/microsoft-365/meeting-scheduler-pricing?rtc=1 first and finally results in an error https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=KccbQlvfz0KEuprf.0.4.0.

Retrying https://www.microsoft.com/microsoft-365/meeting-scheduler-pricing after that keeps failing. Opening a different browser (Edge instead of Firefox) and I still get the error, so it's not session/cookie related.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Steltek Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
