### ISSUE TITLE
74 testconnectivity.microsoft.com - IP-Addresses

### ISSUE THREAD

**Issue by almacho** [MicrosoftDocs/microsoft-365-docs#6285]
For restricted customers, it would be required to know the Source-IP-Addresses in use by testconnectivity.microsoft.com to test against the local Exchange-Servers. So if customer is blocking every incoming traffic except O365 ip-ranges, the test-traffic would also be blocked.
In the past, following ips were used: 65.55.150.61, 65.55.150.158, 65.55.150.160, 207.46.14.52, 207.46.14.62, 207.46.14.63 - but it is stated in the version history that the ips have changed - pointing only to this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. In this case, the IP address is not published because the URL _testconnectivity.microsoft.com_ is covered under _*.microsoft.com_ as an optional **Default** category endpoint that can be routed with normal internet traffic. -Kelley
