### ISSUE TITLE
Missing HRConnector.ps1 reference

### ISSUE THREAD

**Issue by astaykov** [MicrosoftDocs/microsoft-365-docs#6288]
The documentation makes a couple of references to PowerShell script named HRConnector.ps1, but there is no reference to the actual script. 
Funny enough, if one take the steps inside the Compliance portal to actually create a connector, on the very last step, there is a link to PowerShell script. However that sample is actually named `upload_termination_records.ps1` and not `HRConnector.ps1`. The actual script may well be dependent on the choice we make during connector setup. But this documentation should be more clear and also provide links to the actual PowerShell scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b68cfa-058a-8536-fb6a-b54e8fffa626
* Version Independent ID: dbcba365-2858-8cff-4f30-8a8a0068ac71
* Content: [Set up a connector to import HR data - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/import-hr-data?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/import-hr-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-hr-data.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@astaykov Thanks for feedback. You can download the script as per Step 8.b or download it after the HR script is created, as per the screenshot in Step 8. You can change name of script or leave it as it. HRConnector.ps1 is just an example, as per the topic.

I will add a link to download the script from here: https://github.com/microsoft/m365-hrconnector-sample-scripts/blob/master/upload_termination_records.ps1
