### ISSUE TITLE
Incorrect screenshots

### ISSUE THREAD

**Issue by zlDev** [MicrosoftDocs/microsoft-365-docs#6289]
The documentation references the new compliance portal, but the screenshots are from the old security and compliance portal.
UI no longer looks like it is referenced in the documentation.
Also, there are more locations available (on-prem & devices).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0e7f42-60d0-1f95-57e9-6a24a5d87c2b
* Version Independent ID: 0080b139-e35b-b302-b38c-07a2e2e8c1ef
* Content: [Create a DLP policy from a template - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-dlp-policy-from-a-template?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-dlp-policy-from-a-template.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-dlp-policy-from-a-template.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@zlDev Thank you for your feedback. I'm working on updating the document with latest UI.

**Comment by msbemba** [comment]
@zlDev Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6521

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @zlDev Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
