### ISSUE TITLE
Incomplete Description

### ISSUE THREAD

**Issue by arhoads76** [MicrosoftDocs/microsoft-365-docs#6291]
This page describes the first part of the process, but does not describe how to complete the process once the delisting request is initially denied and a request for escalation has been initiated.  There doesn’t seem to be any mention of how to follow-up on the escalation request.  As the owner of an IP which was abused by a previous owner, there doesn’t seem to be a path forward to clean this IP address with MS.  It is not on any public blacklist, and it is not banned anywhere else by Exchange Online.  A description of how to move forward would be helpful.

Thanks,
Aaron

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Remove yourself from the blocked senders list - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@MSFTTracyP Gentle reminder

**Comment by arhoads76** [comment]
Well, I’m not sure how to help. I don’t have any knowledge of the internal workings of MS. The page says to do one thing, but that doesn’t work. In the end I got a new IP address because nothing would work to “clean” the inherited mess I got with the original IP address.

**Comment by chrisda** [comment]
@arhoads76, your best path forward is to open a support case.

**Comment by yogkumgit** [comment]
@arhoads76 Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
