### ISSUE TITLE
correct inaccuracies on passive mode and rtp

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#6293]
Following statement says "For example, real-time protection works when Microsoft Defender Antivirus is in active or passive mode, but not when Microsoft Defender Antivirus is disabled or uninstalled." but then in the table below that text, it says that RTP is not available in passive mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61024433-366d-5ea3-4a3f-0cdd5cdcd900
* Version Independent ID: 348d3fc9-0937-b3a6-897e-09d1236d7019
* Content: [Microsoft Defender Antivirus compatibility with other security products](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@jrhi Thank you for your feedback. We have it tagged for the reason why it is No. In general, when Microsoft Defender Antivirus is in passive mode, real-time protection does not provide any blocking or enforcement, even though it is enabled and in passive mode. 

Hope this helps!
Thanks
Sri

**Comment by jrhi** [comment]
Can we possibly clarify/expand on that in the docs?  It is terribly confusing for customers.

**Comment by msbemba** [comment]
Sorry about that. I think I was not clear. We have tagged it with point no:5) so that people can understand why it is a NO while the earlier statement says it works when it is in passive mode.

![image](https://user-images.githubusercontent.com/45987684/133163011-bd534f47-469c-40fe-b37e-12c2330ca56c.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jrhi Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
