### ISSUE TITLE
MDE for Mac -- Missing License after initial deployment 

### ISSUE THREAD

**Issue by JoeMSFT** [MicrosoftDocs/microsoft-365-docs#6295]
[Enter feedback here]

This error/event can also occur when the MDE Mac agent isn't up-to date.   For example; if you do not configure Jamf to use AutoUpdate for MDE, after several releases, you will encounter the same 'missing license' error.  

The solution is to update your pkg/agent.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9a61ad-de4b-90c3-883b-c8bd3c2a55be
* Version Independent ID: 5c5ebc8d-bfa3-a194-8aa9-1439be8d1ea7
* Content: [Troubleshoot license issues for Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-support-license?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-support-license.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-support-license.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Updating the topic to include this scenario.
