### ISSUE TITLE
Partners requesting a wider variety of admin roles when managing customer O365 tenants

### ISSUE THREAD

**Issue by laurapa63** [MicrosoftDocs/microsoft-365-docs#6296]
From one of our largest global MS partners, they really need the ability to have more admin roles available to them when they are managing multiple customer tenants. Is the ability for customers to assign different admin roles other than just global and helpdesk admin to the partner they are working with already available, or will this be a new feature for a future version?  If the latter, what can I tell them under NDA?  thank you

From the partner "It is my understanding that when our customers add our firm as a partner to O365, we can access their tenant as a Global Admin or a Helpdesk Admin. It would be better if we had the ability to use a wider variety of roles."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@laurapa63 Thank you for your feedback. For Partners, there are only two roles available and I don't see anything changing per roadmap. 

Admin Agent - Equivalent to Globa Admin
Helpdesk Agent - Equivalent to Helpdesk Admin.


https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide#delegated-administration-for-microsoft-partners

Hope this helps!

Thanks
Sri

**Comment by laurapa63** [comment]
Hi Sri!  Thank you for the response and confirmation, next question:  how can this partner (or myself on behalf of the partner), submit a feature request for more partner admin role types?

Thank you,

-Laura Payne

**Comment by msbemba** [comment]
@laurapa63 You can provide feedback via the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365) so that your feedback gets routed to the appropriate team.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @laurapa63 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
