### ISSUE TITLE
What are all these "NT AUTHORITY\SYSTEM" accounts in my logs?

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/microsoft-365-docs#630]
Example: 
Date: 2019-10-21 06:03:13
IP address: [2603:1036:a03:41::5]:4825
User: NT AUTHORITY\SYSTEM (w3wp)
Activity: New-Mailbox //Really? Creating a new mailbox!?!
Item:
NAMPR19A004.PROD.OUTLOOK.COM/Microsoft Exchange Hosted Organizations/westseattle.onmicrosoft.com/3s_m365_66a88757-258c-4c72-893c-3e8bed4d6899_nam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#step-2-view-the-search-results)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@SeaDude - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by retrep** [comment]
Hi @SeaDude did you ever get an answer to this?

**Comment by busyb0x** [comment]
Hi @SeaDude Did you get any response to this from Microsoft? 

Appreciate your response. Thanks

**Comment by markjjo** [comment]
@busyb0x FYI that NT Authority\System is a system account and often performs admin tasks on behalf of your org to maintain your cloud-based tenant. System accounts are briefly documented: "[UserID field: The user who performed the action (specified in the Operation property) that resulted in the record being logged. Audit records for activity performed by system accounts (such as SHAREPOINT\system or NT AUTHORITY\SYSTEM) are also included in the audit log."

The new mailbox cited in this github issue could have a system or arbitration mailbox or some other mailbox required to run your Exchange Online organization. As per mypil's response, consider opening a ticket with MS Support if you have concerns.
