### ISSUE TITLE
Instructions for Ansible repo add are wrong

### ISSUE THREAD

**Issue by samrobillard** [MicrosoftDocs/microsoft-365-docs#6306]
[Enter feedback here]
The baseUrl in the repo configuration section should be https://packages.microsoft.com/[distro]/[version]/[channel]/ and name should be packages-microsoft-[channel] instead of packages-microsoft-prod-[channel]. At least, this is what I had to modify to deploy MDATP Prod via Ansible. There might be other parts to review.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5b7c531-90a1-7f6b-4c1d-0a126cdea398
* Version Independent ID: 5a10f1bb-6407-d706-0b79-bf448a8eda9d
* Content: [Deploy Microsoft Defender for Endpoint on Linux with Ansible](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-ansible?view=o365-worldwide#log-installation-issues)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-with-ansible.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Dansimp Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6381

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @samrobillard Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
