### ISSUE TITLE
Cannot determine what enables the toggle 'replace all links in the email message with the phishing link.'

### ISSUE THREAD

**Issue by CitizenSnipsX** [MicrosoftDocs/microsoft-365-docs#6307]
We cannot seem to find any working examples across multiple tenants of this Tip mentioned: To save time, toggle on the option to replace all links in the email message with the phishing link.
Are they any other requirements for this toggle that are not mentioned? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d7729b-c103-e9bf-0e53-39ecd8d915ba
* Version Independent ID: 427c29e6-7048-75a7-09db-219377bbbd96
* Content: [Create a payload for Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-payloads?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-payloads.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-payloads.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by msbemba** [comment]
@CitizenSnipsX Thank you for your feedback. I have not been able to test this successfully. I'll alert the author and Product team about this.

Thanks
Sri

**Comment by chrisda** [comment]
@CitizenSnipsX, I tested and confirmed that the toggle is not available if you selected **Malware attachment** or **Link in attachment** on the **Select technique** page, but is available for everything else. I added the following text to the description:

> The **Replace all links in the email message with the phishing link** toggle is available only if you selected **Credential harvest**, **Link to malware**, or **Drive-by URL** on the **Select technique** page.
