### ISSUE TITLE
Brute force and pasword spray 

### ISSUE THREAD

**Issue by KONIKPK** [MicrosoftDocs/microsoft-365-docs#6309]
we are redirected to security.microsoft.com when try run any of atack.
On this page i cant find this atacks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fbdcbd5-7bd2-6b55-b72c-cbedfdea776c
* Version Independent ID: 1e6198f8-6ef1-6227-c9e8-f31944a5d1db
* Content: [Attack Simulator in the Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulator.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@KONIKPK, clarification please.

The topic in question is for the old v1 Attack Simulator, which is retired and can't be used anymore.

The newer Attack Simulation Training is available in the Microsoft 365 Defender portal (security.microsoft.com) at <https://security.microsoft.com/attacksimulator>. There are 4-6 topics about this (for example <https://docs.microsoft.com/microsoft-365/security/office-365-security/attack-simulation-training-get-started>.

So are you saying that help links or admin center links in other places are directing you to the wrong place? If so, where are they

**Comment by KONIKPK** [comment]
OK where can i find Brute force password and Password spray attack ?

**Comment by yogkumgit** [comment]
@chrisda

**Comment by chrisda** [comment]
@KONIKPK, Attack simulation training is different than the original Attack Simulator. The topic in question describes the available attack techniques:

- **Credential harvest**
- **Malware attachment**
- **Link in attachment**
- **Link to malware**
- **Drive-by URL**

If you think something is missing, your best course of action is to open a support case. All we do here is update documentation.

**Comment by yogkumgit** [comment]
@KONIKPK Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
