### ISSUE TITLE
Keyword dictionary

### ISSUE THREAD

**Issue by IngoGege** [MicrosoftDocs/microsoft-365-docs#631]
In the example keyword dictionary was created via the XML. This will not work as you will retrieve an error, once you try to import the XML. The proper way is to use the Cmdlet New-DlpKeywordDictionary. Therefore the example should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d6af897-cba3-dc5c-beb1-4a650fadbaea
* Version Independent ID: 12d1e00e-36c2-71a1-0632-844455b1d00c
* Content: [Create a custom sensitive information type in Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@IngoGege  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @IngoGege - Thank you for your feedback. Please note that the process of creation Keyword dictionary is already listed at https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-keyword-dictionary. This is the next topic in Sensitive information types.

Thanks.

**Comment by IngoGege** [comment]
Hi @joinimran ,
I get that, but shouldn't the documentation be corrected? People are still taking the sample XML, which has the keyword dictionary in:
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell#sample-xml-of-a-rule-package
Ciao,
Ingo

**Comment by joinimran** [comment]
Thank you @IngoGege  Can you please share me a screenshot where the dictionary is mentioned as a keyword because I can not find this in the document. 

Thanks.

**Comment by chrfox** [comment]
Hi @IngoGege and @joinimran 

Thank you for your comment and discussion. 
Ingo - Can you please attach a file that shows where the error in the XML, what the error is, and what you feel the fixed code should be?

This will help me address the question you raised.

Thanks
Chris

**Comment by chrfox** [comment]
no reply received on request for clarification, closing issue

**Comment by IngoGege** [comment]
Hi @chrfox ,
sorry for the delay. As mentioned previously the XML file contains keywords:
<Keyword id="Keyword_employee">
		<Group matchStyle="word">
			<Term>Identification</Term>
			<Term>Contoso Employee</Term>
		</Group>
	</Keyword>
	<Keyword id="Keyword_badge">
		<Group matchStyle="string">
			<Term>card</Term>
			<Term>badge</Term>
			<Term caseSensitive="true">ID</Term>
		</Group>
	</Keyword>
	<Keyword id="Keyword_false_positives_local">
		<Group matchStyle="word">
			<Term>credit card</Term>
			<Term>national ID</Term>
		</Group>
	</Keyword>
	<Keyword id="Keyword_false_positives_intl">
		<Group matchStyle="word">
			<Term>identity card</Term>
			<Term>national ID</Term>
			<Term>EU debit card</Term>
		</Group>
	</Keyword>
This is causing the validation to fail, when you try to upload the file.
Ciao,
Ingo
