### ISSUE TITLE
Do you have a better example for understanding domain allow or deny?

### ISSUE THREAD

**Issue by Darrelo365** [MicrosoftDocs/microsoft-365-docs#6310]
Hi, I don't have hands-on expereince of sensitivity labels so I'm not sure if what my org is asking me is possible.

We have some content that can only be shared with Org 123. When creating a sensitivity label for a container, it looks like you can apply it to a particular domain, presumably my org + Org 123 for example. Does it always add your org with access or do you have to add it? And Org 123 has to use Azure AD? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Restrict access to content using sensitivity labels to apply encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#assign-permissions-to-specific-users-or-groups)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @Darrelo365!  You asked this question from the page that covers restricting access by using encryption, which is for documents and emails.  But then you mention labels for containers, which maps to https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites 

From what you've said, it does sound like you want to encrypt documents so all users in another organization can view or edit them, which yes, you can do by specifying a domain name and yes, authentication will use Azure AD.  For more information about sharing encrypted documents with external users, take a look at this section: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#sharing-encrypted-documents-with-external-users

By default, no, all users in your organization won't have access to a document that's labeled in this - just the user who labeled the document and the users in the other organization.  If you want all users in your organization to have access, you'll need to also add them in the label configuration.  Choose "Add all users and groups in your organization" and grant them the relevant permissions.  Or if you want just some users in your organization to have access, specify them with one or more groups.

Hopefully that helps!

**Comment by Darrelo365** [comment]
Thanks Carol. Sounds like I've some reading to do 👍
