### ISSUE TITLE
typo - missing word

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/microsoft-365-docs#6312]
Under the header:

"Working with partially indexed items"

There is a missing word

"In cases when you need to examine partially items to validate that they don't contain relevant information,"

should read

"In cases when you need to examine partially indexed items to validate that they don't contain relevant information,"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6580cdcf-280e-215c-f4a0-d778b501946f
* Version Independent ID: 3f88be2e-6413-c8e7-f234-f62a74075a2d
* Content: [Investigating partially indexed items in eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/investigating-partially-indexed-items-in-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/investigating-partially-indexed-items-in-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/investigating-partially-indexed-items-in-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@exactmike Thanks for catching this. I will fix it today.
