### ISSUE TITLE
ASR rules supported by GPO and PowerShell

### ISSUE THREAD

**Issue by AnsKuo** [MicrosoftDocs/microsoft-365-docs#6319]
[Enter feedback here]
Hi Team,

I have a question for the table under [Supported configuration management systems](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules?view=o365-worldwide#supported-configuration-management-systems). GPO and PowerShell are actually can configure ASR rules by its GUID and not only one rule is supported. Why this table indicate there is only one ASR rule supported?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c664e229-9294-6515-f586-12a1f0348308
* Version Independent ID: a97f107c-fd36-143a-ea68-ee2248f11362
* Content: [Attack surface reduction rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules?view=o365-worldwide#supported-configuration-management-systems)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by yogkumgit** [comment]
@jweston-1 Pleas help us in resolving this issue. Thanks

**Comment by jweston-1** [comment]
In progress

**Comment by jweston-1** [comment]
Fixed. See: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#supported-configuration-management-systems
