### ISSUE TITLE
What is the daily powershell to detect these purchases, and the api to cancel them?

### ISSUE THREAD

**Issue by chadcarlton** [MicrosoftDocs/microsoft-365-docs#632]
So it looks like I will have to write powershell to detect and cancel these purchases. Does anyone have links to API's/cmdlets etc. to do so?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by chadcarlton** [comment]
"Why are self-service purchases not subject to admin approval?

We’re being responsive to our customers who have requested this capability while allowing admins to maintain control over the services and respecting data governance and compliance. To learn more about managing Azure AD service principals, see Set-MsolServicePrincipal. Additionally, admins have full visibility as to who has made a self-service purchase and which users on their tenants have been assigned a license from a self-service purchase. Organizations can then rely on their own internal policies, procedures and communications to ensure that those individuals making self-service purchases are complying with company policies." 

The shift from Sentence 1 to sentence 2 is very sudden. Why suddenly talk about Set-MsolServicePrincipal? It looks like there may be a way to manage this via Service Principal?

**Comment by cmcatee-MSFT** [comment]
Based on your feedback, we’ve adjusted our approach to better address the needs of both IT admins and end users within organizations.  We are providing IT admins a way to turn off self-service purchasing on a per product basis via PowerShell.

**Comment by apachegit** [comment]
So when will we get to see the magical Powershell code that will let us disable this?
