### ISSUE TITLE
Better indent of row

### ISSUE THREAD

**Issue by mmangiante** [MicrosoftDocs/microsoft-365-docs#6321]
Please indent better the row AddRemoveProgramsWOW64.csv: it seems that it is a folder and the following rows seems to are files stored in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b85d3bb-8af3-87d5-27fb-65b81c1b9721
* Version Independent ID: 031c833c-7a05-c54b-fe83-62ca80efd3ad
* Content: [Run the client analyzer on Windows](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-analyzer-windows?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-analyzer-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-analyzer-windows.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback. Page updated.
