### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by D4m4** [MicrosoftDocs/microsoft-365-docs#6322]
Hi,

The link to "See **take response actions on a machine**  for more information about response actions functionality via Microsoft Defender for Endpoint." is not working:
![image](https://user-images.githubusercontent.com/86731035/133098616-a3b2f8eb-25e9-4d03-9d44-48e375583e1a.png)
![image](https://user-images.githubusercontent.com/86731035/133098653-34ab5308-f61c-424b-a867-86591568c4a1.png)

Thanks!
Dama

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05007b38-2a58-d34a-6afb-838e2ddd380e
* Version Independent ID: d0e699b6-abe7-e8f6-a093-ecec52559dec
* Content: [Offboard machine API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/offboard-machine-api?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/offboard-machine-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/offboard-machine-api.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you for your feedback. Fixed link.
