### ISSUE TITLE
Are you completely insane?

### ISSUE THREAD

**Issue by DukeMcAwesome** [MicrosoftDocs/microsoft-365-docs#633]
Please rescind this immediately, businesses have strict procurement processes in place for a reason. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-gb/microsoft-365/commerce/subscriptions/self-service-purchase-faq#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by OutlawCash** [comment]
Totally agree - this is ridiculous. There is absolutely no reason end-users should have the ability to increase organizational spend at their whim. YOU'D BETTER offer a switch for organizations to turn this off.

**Comment by sempervictus** [comment]
If this also bypasses an admins explicit requirement to authorize installation of so much as a system library, it will cause compliance breaches in several industries. In practice that sort of thing can also degrade security posture by allowing the unprivileged user to proxy expansion of the attack surface through the trusted installer (not a new trick by _any_ means). Once someone figures out how to mitm/hijack that process, an unattended power deployed component would be a root shell with OS-level persistence.
Even if all of this is purely cloud hosted and just racks up Wells Fargo style charges, it may either have data of value which the business did not account for in their locality documentation or provide other resources for pivot/ops to attackers.
Nothing good will come of this for anyone but bean counters (not the end-users') and red team/actual adversaries.

**Comment by charlesccarmichael** [comment]
This a further example of the changing IT landscape -- Microsoft we get it, as IT professional we will not always have 'full' control.  But this just smells bad, this is another example of bad judgement in how to roll out a feature or service. 

Stop choosing for us what is best for our company.  

For me most of my users will not even find this feature -- but you are now getting into organizational policies and we as IT are at the center of ensuring our policies are applied correctly.  This Naïve attitude you have about training can be done through education.  If that is the case most IT systems wouldn't exist -- Microsoft at least treat us as professionals.  This clearly has other motives at play, saying "we are listening to our customers" means we want more end-users to find use of these tools and start paying and bypass IT procurement processes -- in the process you are biting the hand that feeds you.

IT procurement serves a purpose, be careful how far you push this.

**Comment by johnmharte** [comment]
May not be retiring Tableau after all.....

**Comment by cmcatee-MSFT** [comment]
Based on your feedback, we’ve adjusted our approach to better address the needs of both IT admins and end users within organizations.  We are providing IT admins a way to turn off self-service purchasing on a per product basis via PowerShell.

**Comment by OutlawCash** [comment]
Excellent news! Thanks for listening to your customers!




Get Outlook for Android







On Fri, Nov 1, 2019 at 8:54 AM -0700, "Cern McAtee" <notifications@github.com> wrote:












Based on your feedback, we’ve adjusted our approach to better address the needs of both IT admins and end users within organizations.  We are providing IT admins a way to turn off self-service purchasing on a per product basis via PowerShell.
