### ISSUE TITLE
Possible spelling error

### ISSUE THREAD

**Issue by Lady-MCSE** [MicrosoftDocs/microsoft-365-docs#6333]
In the green "tip" area, there is reference to backscatter.org and later an actual link to a site with backscatterER.org in its address. Therefore I think the first reference is a typo missing the second ER at the end.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955d52db-5da8-5845-28ea-f78b2a85b688
* Version Independent ID: 6dacde19-dfbf-4305-27b7-b0ecd3bcb9ac
* Content: [Backscatter in EOP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/backscatter-messages-and-eop?view=o365-worldwide&form=MY01SV&OCID=MY01SV)
* Content Source: [microsoft-365/security/office-365-security/backscatter-messages-and-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/backscatter-messages-and-eop.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Lady-MCSE, fixed. In the future, you too can make fixes like this directly without opening an Issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
