### ISSUE TITLE
Data Process and Storage

### ISSUE THREAD

**Issue by oscargsune** [MicrosoftDocs/microsoft-365-docs#6336]
The Data process and storage section has a repeated sentence, one with hyperlinks and one without. Suggest to delete the sentence without the hyperlinks

https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/privacy-personal-data?view=o365-worldwide#microsoft-managed-desktop-data-process-and-storage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70c7d29a-8fc7-6895-530d-2d29ff775a01
* Version Independent ID: fd4facf5-3e8e-151c-adc4-3aae0af57d9e
* Content: [Privacy and personal data - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/privacy-personal-data?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/service-description/privacy-personal-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/privacy-personal-data.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by msbemba** [comment]
@oscargsune Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6346

Thanks
Sri

**Comment by oscargsune** [comment]
Awesome! Glad I could help :)

Oscar Gonzalez
Technical Specialist- Security and Compliance
0430 845 111
________________________________

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @oscargsune Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
