### ISSUE TITLE
ctofp.network

### ISSUE THREAD

**Issue by JeanSaint-Elme** [MicrosoftDocs/microsoft-365-docs#6338]
I felt that something was wrong but I was afraid to say it since I am new to the system. I still do not know what went wrong because I placed and I am still placing 100% trust on Google. I became a little sceptic when I could not get access to my email saintelmejean3@gmail.com. I would never forget the password of this email address. I feel more comfortable with Microsoft  mostly with with the one launch login. It looks like the COMMUNITY UNITED FOR HEALTH AND PREVENTION, INCORPORATED is going to do business with Microsoft for a very long time.

Thank you MICROSOFT.COM

**Comment by yogkumgit** [comment]
@JeanSaint-Elme Do you have any feedback to improve the documentation? Which document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@JeanSaint-Elme We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
