### ISSUE TITLE
Adjust answer to question "What Office 365 data at rest is covered by Customer Key"

### ISSUE THREAD

**Issue by tomjan7** [MicrosoftDocs/microsoft-365-docs#634]
The answer to the question is not accurate. We opened a support case and received response that customer key is only used to encrypt files it does not encrypt any other SharePoint Online content such as metadata in document libraries, data in lists except attachments, data stored in user profile, data stored in search index, data stored in other services such as Planner, Stream, Delve, Microsoft Teams, Yammer etc. This should be clearly stated in the answer to the question or maybe there should be another question with answer such as What Office 365 data at rest is not covered by Customer Key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4350fc6-0826-830b-bbb4-c585839570dc
* Version Independent ID: 4e3f696b-0ef3-a7ef-622b-d9c07fab1b94
* Content: [Service encryption with Customer Key for Office 365 FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/service-encryption-with-customer-key-faq#feedback)
* Content Source: [microsoft-365/compliance/service-encryption-with-customer-key-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/service-encryption-with-customer-key-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@tomjan7  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by GiantCrocodile** [comment]
Please add further information like what about Power BI, Power Automate/Microsoft Flow, etc. @joinimran @mypil.

**Comment by mypil** [comment]
@tomjan7 @GiantCrocodile - Please see author's response based on this https://github.com/MicrosoftDocs/microsoft-365-docs/pull/681#issuecomment-586505218.

We hope this helps to address your issue.


Thank you for your contribution to make the docs better!
