### ISSUE TITLE
Incorrect IBAN Info?

### ISSUE THREAD

**Issue by SDkempf94** [MicrosoftDocs/microsoft-365-docs#6340]
[Hi please can you check the published IBAN and confirm if this is correct?

IBAN: GB31CITI18500812510049  is stated here but we believe that it is meant to be GB95CITI18500812510049 - please can you verify this as soon as possible?
 ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afea22ca-c974-f0ef-07f1-4a44a390c058
* Version Independent ID: a1f02905-3ac6-be64-a400-23287f7e2879
* Content: [Payment information for Saudi Arabia](https://docs.microsoft.com/en-us/microsoft-365/commerce/pay/saudi-arabia?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/commerce/pay/saudi-arabia.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/pay/saudi-arabia.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@SDkempf94, please download your invoice from the [Microsoft 365 admin center](https://admin.microsoft.com), and check the payment instructions shown on the PDF.

**Comment by SDkempf94** [comment]
> @SDkempf94, please download your invoice from the [Microsoft 365 admin center](https://admin.microsoft.com), and check the payment instructions shown on the PDF.

It says GB95CITI18500812510049 and it seems to be the same for other Saudi Arabia tenants too - if this is the case, will you update this public facing documentation?
