### ISSUE TITLE
yh

### ISSUE THREAD

**Issue by Dburke225** [MicrosoftDocs/microsoft-365-docs#6341]
Can you link to the actual service you're talking about. Everytime I find a doc of something useful but have no clue how to actually get or use the tool....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334e743d-c929-c74a-c996-2b8e0b68a46b
* Version Independent ID: 91c4563c-72c1-4655-72f7-d467b6098540
* Content: [Get started with content explorer - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-content-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@Dburke225 Thank you for your feedback. You can find information on How to use content explorer from the below link :- https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer?view=o365-worldwide#how-to-use-content-explorer

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Dburke225 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
