### ISSUE TITLE
QRadar Link does not work anymore.

### ISSUE THREAD

**Issue by annemaarie** [MicrosoftDocs/microsoft-365-docs#6344]
Integration SIEM to QRadar link does not work anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36bbd71-ef7b-e08f-d565-d2b1e8b9deed
* Version Independent ID: 60fad392-2d82-84ca-6b0b-671122738b38
* Content: [Enable SIEM integration in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-siem-integration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-siem-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-siem-integration.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@annemaarie Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6520

Thanks
Sri
