### ISSUE TITLE
my domain name forgotten

### ISSUE THREAD

**Issue by markkristian88** [MicrosoftDocs/microsoft-365-docs#6349]
i need help .  i cant access my outlook account and account i use to work and school .  i sisnt know who made a 25digits recovery code from my account . please help me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758b21fa-24c1-8c68-259f-daac0caf35ae
* Version Independent ID: bce80397-ee03-cacf-55cb-09b169e96e70
* Content: [Find your domain registrar - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/find-your-domain-registrar?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/find-your-domain-registrar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/find-your-domain-registrar.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by yogkumgit** [comment]
@markkristian88  Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
