### ISSUE TITLE
Setting up OME by following documentation is not possible due to deprecated Microsoft functionality

### ISSUE THREAD

**Issue by W0GER** [MicrosoftDocs/microsoft-365-docs#6353]
In the section "Create mail flow rules to encrypt email messages with the new OME capabilities", it states that templates must be setup in Azure Information Protection; however, that feature of Microsoft Azure was deprecated in March 31, 2021.  This page was supposedly updated on 9/10/2021.

1. Links point to "Configuring and managing templates for Azure Information Protection" 
2. Navingating to that page states:
> The content in this article is provided to support customers with extended support only. We recommend that you migrate to unified labeling and upgrade to the unified labeling client. Learn more in our recent deprecation blog.

I would really like a straight forward document on how to enable Office 365 Message Encryption without relying on deprecated products.  I am unable to find any way to create RMS Templates so that the Template can be applied to a Message Transport Rule. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0e7a9a-356a-724b-77ab-41a3c456154b
* Version Independent ID: 78ce0ee4-bd8f-4cfa-cea4-170af5d21aff
* Content: [Define mail flow rules to encrypt email messages - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/define-mail-flow-rules-to-encrypt-email.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by KCCross** [comment]
Thank you for bringing this to my attention. I'm working with the owner of the relevant articles to clarify the steps you need to take.

**Comment by KCCross** [comment]
The note in the Azure article states "The content in this article is provided to support customers with extended support only. All current Azure Information Protection classic client customers must migrate to the Microsoft Information Protection unified labeling platform and upgrade to the unified labeling client. Learn more in our migration blog." However, the powershell equivalents are supported. The conceptual information in that article is still valid and supported. For information about the powershell cmdlets, see https://docs.microsoft.com/en-us/azure/information-protection/configure-templates-with-powershell

**Comment by yogkumgit** [comment]
@W0GER Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
