### ISSUE TITLE
Uninstall Defender for Endpoint MacOS

### ISSUE THREAD

**Issue by seliyyah** [MicrosoftDocs/microsoft-365-docs#6356]
Can you provide uninstall documentation for MacOS?

**Comment by yogkumgit** [comment]
@seliyyah Please indicate which document you are referring and what improvements you suggest. Here, we are limited to documentation fixes and improvements.

**Comment by seliyyah** [comment]
I was just referring to any documentation around uninstalling Defender for Endpoint on MacOS.  I haven’t been able to find official documentation, so technically it’s not a documentation improvement request.  Apologies for any confusion.  Thank you.

**Comment by yogkumgit** [comment]
@seliyyah Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
