### ISSUE TITLE
Label with Encrypt Only does not display in Mac outlook client

### ISSUE THREAD

**Issue by migoboy2001** [MicrosoftDocs/microsoft-365-docs#6358]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Manage sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#sensitivity-label-capabilities-in-outlook)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @migoboy2001  Sorry to hear this label configuration isn't working for you in Outlook for Mac.  If per the information on this page you're running the minimum supported version (16.48+) and mode known as "the new Outlook for Mac", and you've waited at least 24 hours for the label to display, please open a support ticket for investigation.  It would be helpful to confirm that the same label configuration for the same user is displaying as expected on Windows.

**Comment by yogkumgit** [comment]
@migoboy2001  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
