### ISSUE TITLE
Licensing Update Required?

### ISSUE THREAD

**Issue by Dusted1969** [MicrosoftDocs/microsoft-365-docs#6359]
[Enter feedback here]

This section doesn't note that an F1 or F3 is now licensed for using bookings as per major change announcement MC266481.

https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide#how-do-end-users-access-the-bookings-app-

Correct licensing requirements appear here later in the FAQ.  This could be confusing for customers:

https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide#how-do-i-get-microsoft-bookings-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7484dd4-5d94-dd6c-0dbe-551c852677c1
* Version Independent ID: 257d60e2-9313-e08b-dccf-120cb4b30f5b
* Content: [Microsoft Bookings Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-faq.yml)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Dusted1969 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6380
