### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/microsoft-365-docs#636]
In the section "Solutions to additional causes of too much spam", Three of the four links for admins are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbab747e-1a43-037e-09ca-9c402deec602
* Version Independent ID: 1c6d8e28-034d-24d6-5732-b96475411d6b
* Content: [How to prevent false positives from happening in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/prevent-email-from-being-marked-as-spam#feedback)
* Content Source: [microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@JLambEJG  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@JLambEJG - From our understanding, the issue has been resolved based on the merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/d6215271fc742badc4cf1e377b8f256ba0fd8662. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
