### ISSUE TITLE
Conditional Access

### ISSUE THREAD

**Issue by simonburbery** [MicrosoftDocs/microsoft-365-docs#6360]
Hi, it would be good to list here what happens with Conditional Access with regards to geo-blocking if both 4 and 6 are enabled on the client.  If we create a an allow rule for a country based location without allowing unknown locations (which includes IPv6 addresses), the preferred IPv6 connection would fail authentication.  Does the client then retry the connection using IPv4 automatically so the authentication can succeed?

Thanks,
Simon
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41916ef7-635a-80f9-914a-207040a3829e
* Version Independent ID: 1f372ebc-774b-a1f5-5e43-73b42f74b198
* Content: [IPv6 support in Microsoft 365 services - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/ipv6-support?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/ipv6-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/ipv6-support.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
@scotvidican, can you take a look? FYI to @yogkumgit, Scot has taken this content area over on his team.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. My understanding is that if both ipV4 and V6 are enabled on the client, ipV4 would be used to authenticate by default in the scenario you describe. You can see https://techcommunity.microsoft.com/t5/azure-active-directory-identity/conditional-access-policy-amp-ipv6/m-p/1737586 for additional discussion. I will work with the product group to confirm and add information to the article.
