### ISSUE TITLE
MCAS/Conditional access may break...

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#6362]
Why is  `*.cas.ms` and `*.mcas.ms` and` *.mcas-gov.us` not included?
As per [this doc](https://docs.microsoft.com/en-us/cloud-app-security/troubleshooting-proxy-url) it may be required.
Our network guys say it is not part of this list, so will not include it, and things have broke.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd333ae2-34f6-4afd-cdb1-db72303a5736
* Version Independent ID: 5fc52fe8-dade-b8b7-7126-c4e7dd902e62
* Content: [Office 365 IP Address and URL web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-ip-web-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
@scotvidican - can you please take a look?

**Comment by andrePKI** [comment]
Too bad an explanation for the closure is missing. I now think I commented on the wrong page - I have entered a new issue at [https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide](url)
#6452
