### ISSUE TITLE
URL (web) service?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#6364]
[Product question but UserVoice is unavailable]
The article lists a spreadsheet with the URLs that must be allowed through the proxy. Once configured this requires periodic checks for changes, which is inconvenient.
Perhaps it is possible to create a webservice like [described for Office365](http://aka.ms/ipurlws) ? Please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by Dansimp** [comment]
This request requires developer assistance, which we don't have at this point in time. We'll keep this in mind for the future, but not something our team can support at the moment.
