### ISSUE TITLE
Grammar/Spelling: Too go directly to the Restricted users page, use https://security.microsoft.com/restrictedusers.

### ISSUE THREAD

**Issue by bt101** [MicrosoftDocs/microsoft-365-docs#6368]
I believe the sentence should read "To go directly to the Restricted users page, use https://security.microsoft.com/restrictedusers."  It wouldn't hurt to have someone proof read the pages for grammar, spelling and accuracy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c17e50d-aa8f-bd30-66af-ef4d63f02402
* Version Independent ID: 92cbda3f-c3a9-ed20-2038-7e966f491934
* Content: [Remove blocked users from the Restricted users portal - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bt101, fixed. In the future, you too can make fixes like this yourself without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
