### ISSUE TITLE
Is ISRG Root X1 missing on the list?

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/microsoft-365-docs#6369]
This page includes DST Root CA X3, which will be expired on this month.

> <html>
> <body>
> 
> 
> Subject | CN=DST Root CA X3O=Digital Signature Trust Co.
> -- | --
> Serial Number | 44:AF:B0:80:D6:A3:27:BA:89:30:39:86:2E:F8:40:6B
> Public Key Length | RSA 2048 bits (e 65537)
> Signature Algorithm | sha1RSA
> Validity Not Before | Sep 30 21:12:19 2000 UTC
> Validity Not After | **Sep 30 14:01:15 2021 UTC**
> 
> 
> </body>
> </html>

I guess the root certificate is listed because Let's Encrypt depends on it.

> <html>
> <body>
> 
> 
> Subject | CN=Let's Encrypt Authority X3O=Let's EncryptC=US
> -- | --
> Issuer | **CN=DST Root CA X3**O=Digital Signature Trust Co.
> 
> 
> </body>
> </html>

However, Let's Encrypt changed its root CA from _DST Root CA X3_ to _ISRG Root X1_ (ref: [here](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)). 

If you still use certificates issued by Let's Encrypt in any M365 services, I think we need to add _ISRG Root X1_ root certificate on the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f283e6d-8054-3abf-becf-65037e9c70b7
* Version Independent ID: e8dfaaad-a731-bd2e-7c7b-c5d0b80462de
* Content: [Microsoft 365 encryption chains - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-certificate-chains?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-office-365-certificate-chains.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-certificate-chains.md)
* Service: **o365-seccomp**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@hishikitetsuya Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6551

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by LauraWi** [comment]
@kelleyvice-msft  -- note related PR I just assigned to you.

**Comment by kelleyvice-msft** [comment]
Merged. I will make sure the related .p7b file is updated to match both this topic and the DoD topic.

**Comment by kelleyvice-msft** [comment]
Related PR merged and closed.
