### ISSUE TITLE
LAWSUIT

### ISSUE THREAD

**Issue by OutlawCash** [MicrosoftDocs/microsoft-365-docs#637]
This is an incredibly irresponsible feature to deploy to without an option to disable by administrators. You are setting yourselves up for a class action lawsuit which will undoubtedly occur within six months of turning this on.

I also, cannot believe, that you have received overwhelming feedback from your customers 'requesting this'. That, I believe, is Fake News.

**Comment by mypil** [comment]
@OutlawCash - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by OutlawCash** [comment]
Yes, sorry, I thought it came with the comment: 




https://admin.microsoft.com/AdminPortal/home#/MessageCenter?id=MC193609&MCLinkSource=DigestMail




Get Outlook for Android







On Tue, Oct 29, 2019 at 3:20 AM -0700, "Joyce Y." <notifications@github.com> wrote:












@OutlawCash - May we know which Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@OutlawCash - That link you shared might be within your tenant. Would you be able to share the specific Microsoft document link please?

**Comment by OutlawCash** [comment]
https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq




Get Outlook for Android







On Tue, Oct 29, 2019 at 6:23 AM -0700, "Joyce Y." <notifications@github.com> wrote:












@OutlawCash - That link you shared might be within your tenant. Would you be able to share the specific Microsoft document link please?

**Comment by cmcatee-MSFT** [comment]
@OutlawCash Based on your feedback, we’ve adjusted our approach to better address the needs of both IT admins and end users within organizations.  We are providing IT admins a way to turn off self-service purchasing on a per product basis via PowerShell.
