### ISSUE TITLE
Citing Security and Compliance page as one

### ISSUE THREAD

**Issue by luamcortez** [MicrosoftDocs/microsoft-365-docs#6371]
Security and Compliance are now two different pages. It'd be nice to indicate which one this feature refers to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e391a3b9-fc52-bedf-353a-3564752240dd
* Version Independent ID: 89376ace-9c00-7c45-3771-a9a913f81bed
* Content: [Search for and delete email messages in your organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@luamcortez Thanks for feedback. Not sure I understand what you are referencing. This topic mostly references Security & Compliance PowerShell, which is still the correct name, as it contains cmdlets related to both security and compliance features. You are right that we now have separate security and compliance admin portals, but I don't see reference to those. If you use an admin portal to perform eDiscovery or search related tasks, then you would use the compliance center.
