### ISSUE TITLE
need to add onboardingStatus as odata filter

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#6372]
onboarding status is supported as an odata filter for the API and should be reflected in the docs.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07828149-8c9b-2b6f-b5f6-9558cfcfa650
* Version Independent ID: 2101b098-7da1-86ca-6a31-fddfa7a5cb62
* Content: [List machines API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-machines.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jrhi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6437

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jrhi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
