### ISSUE TITLE
Office 365 Anti-Spam IP Delist Portal

### ISSUE THREAD

**Issue by deco1974** [MicrosoftDocs/microsoft-365-docs#6373]
The service sender.office.com is down. 
It keeps saying "Step 1: Our messaging service has experienced a temporary issue, please resubmit your information below."

**Comment by msbemba** [comment]
@deco1974 Thank you for your feedback. I see that you are referring to the document - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide

Btw, The service  sender.office.com is up and running now. If you continue to have a problem with the site or with delisting, Please contact Microoft support via the need help button on your M365 admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @deco1974 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
