### ISSUE TITLE
Aplicação Tarefas Repetivas

### ISSUE THREAD

**Issue by riwmat** [MicrosoftDocs/microsoft-365-docs#6375]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1feb89e6-c5e0-693e-425e-8fd8b0198001
* Version Independent ID: 7b683879-67a9-299a-73e9-6e3654846fdf
* Content: [Set up file storage and sharing - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/set-up-file-storage-and-sharing?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/set-up-file-storage-and-sharing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/set-up-file-storage-and-sharing.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@riwmat Thank you for your feedback. Are you referring to automating these repetitive tasks? If this was related to the Sync client, yes The data upload is automatic once you set that up.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @riwmat Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
