### ISSUE TITLE
Couldn't make it work without offline access

### ISSUE THREAD

**Issue by unboundadam** [MicrosoftDocs/microsoft-365-docs#6377]
We followed the instructions and deployed the sample service.
It all works as long as the label "Offline access" is set to "Always" - in this state, the "Decrypt" method is not called at all.
When changing it to "Never" it stops working - on save we get a Login dialog and eventually a "You don't have permissions to view this document" message box. This happens as Office tries to use the Decrypt method with OAuth but fails

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide#create-sensitivity-labels-using-dke)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@unboundadam Thank you for your feedback. I can confirm that this works in a test tenant. However, In your case we recommend you to contact Microsoft support via the need help section so that a dedicated engineer can look at this and fix it (if this is a bug or a configuration issue).

Hope this helps!

Thanks
Sri
