### ISSUE TITLE
App governance MCAS policies listing issue

### ISSUE THREAD

**Issue by anarii** [MicrosoftDocs/microsoft-365-docs#6378]
In the **Step 3: Add integration with MCAS** section there seems to be additional review actions after enabling MCAS integration wrongly listed as newly created policies.

These are the policies that will be created after the MCAS app governance integration has been enabled:

Microsoft 365 OAuth app Reputation
Microsoft 365 OAuth Phishing Detection
Microsoft 365 OAuth App Governance

These are not MCAS policies, but seem to be additional actions to review the configuration after successfully enabling the integration. They are currently listed as "new policies" for some reason:

Review App Governance widget in MCAS dashboard
Review newly generated App Governance alerts in MCAS alerts
Review MCAS Microsoft 365 OAuth policies in App Governance policy list
Review newly generated  MCAS Microsoft 365 OAuth alerts  in App Governance alerts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146c1b53-f788-d175-ee4f-5455c8c65cc9
* Version Independent ID: c38e475b-82b3-2db0-0bd8-baf23e6ed7f7
* Content: [Get Started with app governance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/app-governance-get-started?view=o365-worldwide#add-integration-with-mcas)
* Content Source: [microsoft-365/compliance/app-governance-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/app-governance-get-started.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@anarii Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6523

Once the author approves, you will see the changes live.

Thanks
Sri

**Comment by v-tophillips** [comment]
This was already addressed as part of normal documentation updates.
