### ISSUE TITLE
Delete SharePoint Site

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/microsoft-365-docs#638]
When an admin tries to delete a site or subsite that is included in a retention policy they receive following message: "This site cannot be deleted because it is included in an eDiscovery case or retention policy". This seems like expected behavior based off this statement from this article: "Note that a user receives an error if they try to delete a library, list, folder, or site that's subject to a retention policy." Please confirm this is the case. Also, please provide a solution. If we don't want a site to show any longer in SPO there should be a way of deleting it, or at least removing it from view. Why does it not go to the 'Preservation Hold library' like other objects? Please advise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@toddjohnson39  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LauraWi** [comment]
Hi @toddjohnson39 Yes, the behavior you note is expected. This section explains how retention works for in-place items: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#how-a-retention-policy-works-with-content-in-place 
If content is modified, a copy of the original is placed in Preservation Hold, but the content remains in place until the retention period expires. If your goal is to remove a site from view in SPO, you can explore removing links to the site in navigation and changing search settings to make it less discoverable.

**Comment by LauraWi** [comment]
Closing issue.
