### ISSUE TITLE
How the Power BI data location matches to Office 365?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/microsoft-365-docs#6382]
Hi,
When looking for the services list, I could not found Power BI from here. Is that expected, or how it should be? At least when following this: [Find the default region for your organization](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-where-is-my-tenant-located) I could see we have different location for Power BI compared of our company info on O365 admin center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide#sweden)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by msbemba** [comment]
@Petri-X Thank you for your feedback. The region you select during sign-up determines where data is stored. This region will be the same location for all users in your organization, no matter where they are. If a different location shows up for users' powerBI data, I'd request you to contact Microsoft support from the need help section on the admin center.  Also Note that Customers that have purchased Power BI Premium capacity can specify a data region for each capacity. The region for the capacity can be different than the default region. You can view - https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo for more details.

Thanks
Sri

**Comment by Petri-X** [comment]
Hi @msbemba 
Thank you for your reply, but my question was actually is the location of Power BI without any links to Office 365 tenant?

Also what you wrote; "_If a different location shows up for users' powerBI data,_" brings a question to my head, is it possible for me as admin to review and confirm users data location somehow per user?

**Comment by msbemba** [comment]
@Petri-X Thank you for your response. I meant different regions showing up for users in Select Help & Support (?) > About Power BI. (West US, East US, etc). But powerBI location does not have links with Office 365 tenant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Petri-X Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
