### ISSUE TITLE
Extraneous item in list of supported clients

### ISSUE THREAD

**Issue by mealiffe** [MicrosoftDocs/microsoft-365-docs#6385]
In the list of supported email clients under Organization-level scenarios, the e-mail client "Open Outlook on the web" seems to be an error. "Outlook on the web" is listed earlier, and there isn't such a thing as "Open Outlook on the web".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c476abb1-28db-ffe7-bd2f-3a9fa2505d17
* Version Independent ID: 5b6842d5-50a2-10e3-5061-cabefecc9ccd
* Content: [Exchange Online monitoring for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-exchange-monitoring?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-exchange-monitoring.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-exchange-monitoring.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@mealiffe Thank you for your feedback. We have made changes the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6436

Thanks
Sri
