### ISSUE TITLE
This document needs to mention which kind of admin access is needed to create the Alias

### ISSUE THREAD

**Issue by pinaki-intellify** [MicrosoftDocs/microsoft-365-docs#6388]
This document needs to mention which kind of admin access is needed to create the Alias. User Admin access is not sufficient and Global Admin access is needed to create an Alias. This page just links to the admin page which has no mention of an Alias. So user cannot the information they need on this page. I had to fetch for this information from a reddit link that you need global admin access to create an Alias.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@pinaki-intellify Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6435

Thanks
Sri
