### ISSUE TITLE
Auto-labeling

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#639]
Hello,
Regards "The capability to apply labels automatically requires an Azure Information Protection P2 subscription"
I'm using Microsoft 365 E3 and it is working for me, is it possible there was some update that not added to this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Apply a sensitivity label to content automatically](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@lightupdifire  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LauraWi** [comment]
Hi @lightupdifire   According to engineering, once this feature is out of Public Preview and reaches General Availability, it will be limited to Microsoft 365 E5 customers.

**Comment by lightupdifire** [comment]
@LauraWi Can you please provide information were it shows that it is now in Public Preview?

**Comment by LauraWi** [comment]
Hi @lightupdifire The M365 sensitivity labeling space is rapidly evolving, with incremental enhancements shipping frequently. Here's the freshest blog post I can find (timed with Ignite) announcing some of the newer capabilities. https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Understand-where-your-sensitive-data-is-located-and/ba-p/960465. I would also recommend tracking the Microsoft 365 Roadmap site: https://www.microsoft.com/en-us/microsoft-365/roadmap  We will be updating the content frequently as new capabilities light up.

**Comment by LauraWi** [comment]
Tagging in @btbennett who is tracking some of the moving pieces here.

**Comment by cabailey** [comment]
@lightupdifire  The preview status for auto-labeling is in the table from the following section: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#support-for-sensitivity-label-capabilities-in-word-excel-and-powerpoint

The licensing information is included in the referenced link on this page, but to help make it more obvious, I'll change the link to go to the relevant section (https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#subscription-and-licensing-requirements-for-sensitivity-labels).
