### ISSUE TITLE
Incorrect English in the Core eDiscovery bullet under eDiscovery solutions heading

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/microsoft-365-docs#6390]
The phrase "Core eDiscovery builds on the basic search and export functionality of Content search enabling you to create eDiscovery cases and eDiscovery managers who can only access the case their members of. " should read something like "Core eDiscovery builds on the basic search and export functionality of Content search enabling you to create eDiscovery cases and eDiscovery managers who can only access the cases of which they are members."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562b6b1d-b0fd-0d65-9db8-37df67bd7035
* Version Independent ID: 92c4403b-0d6b-88aa-74f4-ba3b7640ad00
* Content: [Microsoft 365 eDiscovery solutions - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@exactmike Thanks for the heads up. I will fix this.
