### ISSUE TITLE
issue with restricting users from creating Teams

### ISSUE THREAD

**Issue by HansonITTechies** [MicrosoftDocs/microsoft-365-docs#6394]
I have encountered an issue with the script, when running there is a syntax error on line 22. else { is no longer recognized as the name of a cmdlet, function, script file or operable program.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@HansonITTechies Thank you for your feedback. I was able to run the script and test it in the lab without issues. 

![image](https://user-images.githubusercontent.com/45987684/134956144-0c698faa-85ef-4971-971a-aea0a2c261e0.png)


If you are still having issues with the script, I'd recommend opening a support ticket via the need help option in the admin center.

Thanks
Sri
