### ISSUE TITLE
Mention non-ascii characters also not supported. EG Aarsø will not sync to AzureAD

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/microsoft-365-docs#6395]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b05a56d-f714-2d99-747e-b3150f581f38
* Version Independent ID: e8924d3f-20e7-6ce2-2279-cec010e7d3f3
* Content: [Prepare for directory synchronization to Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/prepare-for-directory-synchronization?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/prepare-for-directory-synchronization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/prepare-for-directory-synchronization.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@richard-artes Thank you for your feedback. We have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6504

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @richard-artes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
