### ISSUE TITLE
Too many admin roles.

### ISSUE THREAD

**Issue by programify** [MicrosoftDocs/microsoft-365-docs#6398]
16 Admin Roles ! Sixteen! Well done Micro$oft for making life 16 times more complicated than it needs to be.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-GB/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@programify Thank you for your feedback. These admin roles are unique in their own way. Thank you for providing feedback to help improve a Microsoft product! To make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Hope this helps!

Thanks
Sri
