### ISSUE TITLE
Why delisting portal no longer sending verification email?

### ISSUE THREAD

**Issue by azizparacha** [MicrosoftDocs/microsoft-365-docs#640]
https://sender.office.com/ never sends verification email no matter what address do we provide. How do we delist an IP then? Why nobody is complaining even though I see this not working for weeks now?

**Comment by mypil** [comment]
@azizparacha - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by gkrasuski7** [comment]
I have the same problem. I submitted delist request and did not get an email. When I tried with other email address (on the other server) I got the email immediately, but as far as I understand I need to receive an email on the blocked server/IP. What can I do?

**Comment by azizparacha** [comment]
> I have the same problem. I submitted delist request and did not get an email. When I tried with other email address (on the other server) I got the email immediately, but as far as I understand I need to receive an email on the blocked server/IP. What can I do?

How did you get email? I tried hotmail/gmail email ID but never got an email link?

**Comment by gkrasuski7** [comment]
Thank you for your answer. It turned out that probably it was a problem 
with my domain rDNS. After fixing it, everything works fine.

W dniu 30.10.2019 o 08:35, azizparacha pisze:

**Comment by mypil** [comment]
@azizparacha - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
