### ISSUE TITLE
Inconsistency in the Preservation Hold Library documentation

### ISSUE THREAD

**Issue by mkwiley** [MicrosoftDocs/microsoft-365-docs#6402]
Regarding this verbiage:
_You can view this library on the Site contents page in the top-level site of the site collection. Most users can't view the Preservation Hold library because it's visible only to site collection administrators._

There is no documentation on how to find the PHL through the GUI.  I was able to document how to navigate through the GUI, and also by changing the URL.  These two tactics behave differently.  Navigating through the GUI only provides access to to PHL for SharePoint or Global admin role.  However, changing URL allows user to actually get access, since the user is the site collection administrator.  I created a document on this and can provide it.

Michael Wiley
Microsoft Sr. Customer Engineer
MSFT alias: micwil
[Locating the Preservation Hold Library using the GUI.pdf](https://github.com/MicrosoftDocs/microsoft-365-docs/files/7213439/Locating.the.Preservation.Hold.Library.using.the.GUI.pdf)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#how-retention-works-for-sharepoint-and-onedrive)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
I will follow up on this.

**Comment by cabailey** [comment]
@mkwiley  Thanks for flagging that the navigation instructions no longer worked for SharePoint.  Always a challenge when they move things around!  But after discussing this with engineering, rather than update the navigation instructions, we've removed them.  The Preservation Hold library is designed for automatic processes for compliance requirements rather than interactive use, and you can expect changes in the future that will make it hidden.

**Comment by mkwiley** [comment]
Thanks for the info!
