### ISSUE TITLE
Fedora Linux Support

### ISSUE THREAD

**Issue by collinjc** [MicrosoftDocs/microsoft-365-docs#6404]
Fedora is not listed as a supported operating system, despite the existence of the necessary packages and repositories for Fedora. Is there a reason it is absent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@collinjc Thank you for your feedback. I'm currently checking this with the team and will update the document if need be.

Thanks
Sri
