### ISSUE TITLE
Documentations uses old product names.

### ISSUE THREAD

**Issue by hedbergtech** [MicrosoftDocs/microsoft-365-docs#6409]
The document describing "Common attacks and Microsoft capabilities that protect your organization" you are referring to "Advanced Threat Analytics" when it comes to protecting and monitoring on-premises Active Directory for lateral movements etc. Since the product is replaced by MDI, wouldn´t it be better to have MDI represented here instead? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91837ba8-f6f2-3c52-2d89-c8f4c4bce09c
* Version Independent ID: eb3c1fd8-9143-0dc1-77e7-e664ccaefc33
* Content: [Microsoft cloud architecture models - enterprise resource planning](https://docs.microsoft.com/en-us/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/cloud-architecture-models.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/cloud-architecture-models.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by hedbergtech** [comment]
https://docs.microsoft.com/en-us/microsoft-365/solutions/cloud-architecture-models?view=o365-worldwide

**Comment by samanro** [comment]
Thank you for flagging this! We'll check into it.

**Comment by BrendaCarter** [comment]
Hi, Thank you Viktor. You are right and this has been fixed in the poster.
