### ISSUE TITLE
Worst decision ever

### ISSUE THREAD

**Issue by mrLoganz** [MicrosoftDocs/microsoft-365-docs#641]
Our Finance Directors credit card is linked to our office 365 account for purchasing licences. Are you really sure you want to green light employees to purchase licences using his credit card without his authorization and without the ability to block it? Empowering people to spend other peoples money is a dangerous game.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@mrLoganz Self-service purchases are not linked to the credit card used for organization-wide purchases. The individual making the self-service purchase will be asked to provide their own credit card and will be responsible for making the payment.
