### ISSUE TITLE
The path examples for variables for "%userprofile" are wrong

### ISSUE THREAD

**Issue by sullcromenterprise** [MicrosoftDocs/microsoft-365-docs#6415]
[Enter feedback here]
%userprofile% = c:\users\JohnDoe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87906607-83fd-8dc8-facb-89719390f824
* Version Independent ID: 92f3359d-84ac-90c3-33d5-513feffc4173
* Content: [Configure and validate exclusions based on extension, name, or location](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@sullcromenterprise . I am investigating this

**Comment by msbemba** [comment]
@sullcromenterprise Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6500

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sullcromenterprise Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by RAJU2529** [comment]
@yogkumgit Please verify this PR #6874
