### ISSUE TITLE
M365 F5 Licenses missing

### ISSUE THREAD

**Issue by olthomps** [MicrosoftDocs/microsoft-365-docs#6416]
Kindly include the M365 F5 Compliance or Security & Compliance SKU in the eDiscovery Subscription comparison list. These are currently missing. 
https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide#ediscovery-subscription-comparison

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562b6b1d-b0fd-0d65-9db8-37df67bd7035
* Version Independent ID: 92c4403b-0d6b-88aa-74f4-ba3b7640ad00
* Content: [Microsoft 365 eDiscovery solutions - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@olthomps Thanks for feedback. I have added this info and updated articles will be published tomorrow.
