### ISSUE TITLE
So Microsoft is now in charge of what our users can do ???

### ISSUE THREAD

**Issue by marquer** [MicrosoftDocs/microsoft-365-docs#642]
SO MS opens the door for our users to buy product without any admin control then tells us you handle it..."Organizations can then rely on their own internal policies, procedures and communications to ensure that those individuals making self-service purchases are complying with company policies."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by VeroniquePalmer** [comment]
Exactly, it's not on.  Plus we need this off by default, and not managed via PowerShell.

**Comment by cmcatee-MSFT** [comment]
@marquer Based on your feedback, we’ve adjusted our approach to better address the needs of both IT admins and end users within organizations.  We are providing IT admins a way to turn off self-service purchasing on a per product basis via PowerShell.

**Comment by marquer** [comment]
Why can you just have that functionality at the admin console ??

Bob

Sent from my iPhone


> On Nov 1, 2019, at 10:54, Cern McAtee <notifications@github.com>
wrote:
> 
> ﻿
> @marquer Based on your feedback, we’ve adjusted our approach to better
address the needs of both IT admins and end users within organizations.
We are providing IT admins a way to turn off self-service purchasing on
a per product basis via PowerShell.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

LinkedIn -
http://www.linkedin.com/company/16817?trk=tyah&trkInfo=clickedVertical%3Acompany%2Cidx%3A3-1-7%2CtarId%3A1432328924645%2Ctas%3Aedward%20don

Twitter - http://twitter.com/EdwardDonCo

Facebook -
http://www.facebook.com/pages/Edward-Don-Company/113824285620323

Instagram - http://instagram.com/edwarddonco

YouTube - http://www.youtube.com/user/EdwardDonCo
