### ISSUE TITLE
 "<UndesirableService1>", "<UndesirableService2>"...

### ISSUE THREAD

**Issue by jtsveigdalen** [MicrosoftDocs/microsoft-365-docs#6422]
Step 1, powershell:  This should probably read "UndesiredService" rather than Undesire_**able**_Service.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e0c0537-bbc1-02c8-7ae2-78646b2a2e98
* Version Independent ID: a9becd2e-5989-da88-8b6c-0e51476a21c7
* Content: [Disable access to Microsoft 365 services with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/disable-access-to-services-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@jtsveigdalen Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6489

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jtsveigdalen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
