### ISSUE TITLE
Fantastic

### ISSUE THREAD

**Issue by povlhp** [MicrosoftDocs/microsoft-365-docs#643]
Microsoft makes so much more money from individual licenses than enterprise agreements.
This will give a fantastic boost for Microsoft shares. But will likely make lots of customers unhappy. Marketing guys are da ting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by VeroniquePalmer** [comment]
It was a brilliant sales drive - but they have under-estimated the power of the community.  This must be stopped!

**Comment by cmcatee-MSFT** [comment]
@povlhp & @VeroniquePalmer Based on your feedback, we’ve adjusted our approach to better address the needs of both IT admins and end users within organizations. We are providing IT admins a way to turn off self-service purchasing on a per product basis via PowerShell.

**Comment by VeroniquePalmer** [comment]
That is not the solution we have requested.  Please see the overwhelming response from the public on Uservoice about this issue<https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/38878723-ability-to-block-self-service-purchase-capabilitie>.  A PowerShell command per product is not an acceptable solution.  This functionality must be off by default with radio button opt-in / opt-out settings in the tenant admin centre.
