### ISSUE TITLE
Centralized Deployment requirements

### ISSUE THREAD

**Issue by clavx** [MicrosoftDocs/microsoft-365-docs#6430]
We are aware that Microsoft 365 E3/E5/F3 and Office 365 E1/E3/E5 are different plans.

https://www.microsoft.com/en-us/microsoft-365/enterprise/compare-office-365-plans
https://www.microsoft.com/en-us/microsoft-365/compare-microsoft-365-enterprise-plans

We have confirmed that the developer license for the Office 365 E3 plan can be used the Centralized Deployment.

The document does not indicate which Office 365 E1/E3/E5 plans support centralized deployment.

> Centralized deployment of add-ins requires that the users are using Microsoft 365 Enterprise SKUs: E3/E5/F3 or Business SKUs: Business Basic, Business Standard, Business Premium (and are signed into Office using their organizational ID), and have Exchange Online and active Exchange Online mailboxes. 

Could you please update the document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@clavx Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6492

Thanks
Sri

**Comment by clavx** [comment]
@msbemba Thank you for your reply.

I see that there was also the Office 365 F3 plan.
https://www.microsoft.com/en-us/microsoft-365/enterprise/frontline#office-SKUChooser-0dbn8nt

I also saw "Microsoft 365 Enterprise SKUs: E3/E5/F3" listed in the "Office Requirements" section just below.

Thanks.
