### ISSUE TITLE
Time required to reflect Centralized Deployment

### ISSUE THREAD

**Issue by clavx** [MicrosoftDocs/microsoft-365-docs#6431]
From the following text, it reads as if the reflection will be completed within 24 hours.

> How long does it take for add-ins to show up for all users?
> 
> It can take up to 24 hours for an add-in to show up for all users. It can take the same amount of time for add-in updates, changes from turn on or turn off, or add-in removals.

The following operations seemed to be reflected within 24 hours.
(1) Add or Remove users
(2) Turn add-ins On or Off
(3) Remove add-ins

However, the following operations seemed to be reflected in about a week.
(4) Update the manifest by version up (change the `<Version>1.0.0.0</Version>`)
(5) Update the manifest by deleting and then adding because of the same version or version down

As for (5), we have confirmed the following behavior.

(a) Remove the registered add-in in the centralized deployment
(b) After 24 hours, confirm that it is no longer visible to the user's Outlook
(c) Add the same add-in again in the centralized deployment
(d) The latest information is displayed in the admin screen, but it will be restored to the user's Outlook within 24 hours with the old content at the time of deletion.

Then, after about a week from the time when the manifest with the old content was delivered to the user's Outlook, it seemed to reflect the latest content.

From the above, we think that it takes more than 24 hours to update the manifest (update the add-in).

Could you tell us what is the expected behavior when using centralized deployment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32aaf301-bc79-ea37-f3fd-94ae9e9ab02f
* Version Independent ID: 7482cca5-faac-3276-8481-e6323cafef31
* Content: [Centralized Deployment FAQ](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-FAQ.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-FAQ.yml)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@clavx Thank you for your feedback. I'm currently testing this and will update you shortly. If there are changes needed, I'll ensure that the document is updated.

Thanks
Sri

**Comment by clavx** [comment]
Thank you for your reply.
Here is some additional information.

The information I wrote above is based on when I tried to install an Outlook add-in from "Upload custom apps".
I have not tried it with any other add-ins (Excel‎, ‎PowerPoint‎, ‎Word‎).

Procedure for (4).
1. Upload the manifest of the Outlook add-in from "Upload custom apps" and register it by specifying the users to be applied.
2. After 24 hours, confirm that the registered add-in appears in the Outlook of the target user.
3. Rewrite the `Version` and `Description` of the manifest file, and then register it with "Update Add-in".
4. After about a week, confirm that the content registered in No3 is reflected in the Outlook of the target user.

Procedure for (5).
1. Upload the manifest of the Outlook add-in from "Upload custom apps" and register it by specifying the users to be applied.
2. After 24 hours, confirm that the registered add-in appears in the Outlook of the target user.
3. Delete the Outlook add-in registered in No1.
4. After 24 hours, confirm that the deleted add-in will no longer be displayed in Outlook for the target user.
5. Register the manifest file of the same Outlook add-in with the `Version` unchanged and the `Description` rewritten, and specify the same target user as in No1.
6. After 24 hours, confirm that the add-in appears in the Outlook of the target user with the content of the manifest when it was registered in No1.
7. After about a week, confirm that the content registered in No5 is reflected in the Outlook of the target user.

**Comment by msbemba** [comment]
@clavx Thank you for your detailed feedback. From the details we have, it can only take up to 24 hours for an add-in to show up for all users.  This is the same when there is an updated manifest.  I'm not certain if it is the add-in that is causing an issue, But the recommended way to fix or escalate this issue would be to contact Microsoft support via the need help icon on the admin center.

If you think there are changes required in the document post contacting support, do let us know.

Thanks
Sri

**Comment by clavx** [comment]
Okay, I will contact Microsoft support.

Thanks for your support.
