### ISSUE TITLE
(Recommended) Use mail flow rules / Secure by default in Office 365

### ISSUE THREAD

**Issue by rafaelborter** [MicrosoftDocs/microsoft-365-docs#6432]
Because Microsoft wants to keep our customers secure by default, some tenants overrides are not applied for malware or high confidence phishing. These overrides include:
- Allowed sender lists or allowed domain lists (anti-spam policies)
- Outlook Safe Senders
- IP Allow List (connection filtering)
- Exchange mail flow rules (also known as transport rules)
This information are documented [here](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-by-default?view=o365-worldwide).

However, [this page](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide) is missing the caution information for "(Recommended) Use mail flow rules".

Why is the caution information not displayed here?

**Comment by chrisda** [comment]
@rafaelborter, I added the information to the topic.

Thanks for the feedback.

Closing
