### ISSUE TITLE
DEP for multiple Microsoft 365 workloads - Unified Audit log stirage

### ISSUE THREAD

**Issue by mohanse** [MicrosoftDocs/microsoft-365-docs#6433]
[Enter feedback here]

Hi - I believe "DEP for multiple Microsoft 365 workloads" - now encrypts the Unified Audit log storage. If so, can the documentation be updated with relevant details pls

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a585eca1-dad6-3afd-43ce-8c4b11102dd3
* Version Independent ID: a1d708a7-774f-0c23-b428-28919ef5d46a
* Content: [Service encryption with Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-overview?view=o365-worldwide#about-data-encryption-policies)
* Content Source: [microsoft-365/compliance/customer-key-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@mohanse Thank you for your feedback. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6502

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mohanse Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mohanse** [comment]
Thanks. I still dont see the updates. when is this going live ?
