### ISSUE TITLE
Page is missing detail on understanding the results of the admin submission

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#644]
The "Rescan" tab could do with some explanation as to the fields "verdict","delivery details" and "recommendations" as we are getting a lot of calls relating to this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Admin submissions in Office 365, O365 submissions, Office 365 spam problem, O365 false negative, submit phish in office 365, submit email for scanning, suspicious email in Office 365, scan a mail, have Microsoft scan for phish, have Microsoft scan for spam, submit e-mail, submit email](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@aldoug  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@aldoug - Can you please explain some more details on this. Also can you please share a screenshot of Rescan tab as from where we can access this option. 

Thanks.

**Comment by aldoug** [comment]
@joinimran - Hi. I think the developers responsible for creating the Admin Submission portal would be better placed to address the expectations?

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by mymebenha** [comment]
I agree, we need more information.  I submitted and obvious phishing message and delivery reason was no policy was hit and result verdict not junk.  So now what?  Is Microsoft going to review the message or did they already determine it's not junk.  I hope not because it's a phishing email.

**Comment by chrisda** [comment]
@aldoug, @mymebenha, this issue is quite old, and the topic has been substantially updated.

Is the topic still lacking?

**Comment by aldoug** [comment]
Hi Chris, thanks for coming back to me

It still lacks any information on the Rescan verdict, which is the key part as it tells the user whether their submission has done anything

I think it would be beneficial for the original creators to detail the possible results and their meanings, as I only know a couple, and whilst I think I understand them I cant say for certain



Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (0) 7876 657707

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by chrisda** [comment]
Possible solutions are being discussed in internal email, and the correct people have been notified.

Closing
