### ISSUE TITLE
Perhaps the term OST should be replaced - as contract structure has changed

### ISSUE THREAD

**Issue by HedgieTheHedgehog** [MicrosoftDocs/microsoft-365-docs#6443]
I think one should rewrite (and perhaps find correct linkt) when referring to the OST - the are no more anline services terms as the changes done in 15th of September.

BR,

Emmi Stubin
Client Technology Lead
Microsoft

---
#### Asiakirjan tiedot

⚠ *Älä muokkaa tätä osiota. Sitä tarvitaan kohteessa docs.microsoft.com GitHub-ongelmien linkityksessä.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://docs.microsoft.com/fi-FI/microsoft-365/enterprise/o365-data-locations?ms.officeurl=datamaps&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by msbemba** [comment]
@HedgieTheHedgehog Thank you for your feedback. I'm currently checking this internally with the team and will update the document shortly.

Thanks
Sri

**Comment by msbemba** [comment]
@HedgieTheHedgehog Thank you for your feedback. We have updated OST to Online Services Data Protection Addendum (DPA). The changes can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6552

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @HedgieTheHedgehog Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
