### ISSUE TITLE
Teams Guest Settings - Missing/wrong navigation step

### ISSUE THREAD

**Issue by MacKender** [MicrosoftDocs/microsoft-365-docs#6444]
The section on "Teams Guest Settings" is missing/has a wrong navigation step; One needs to expand 'Users' on the left and then select 'Guest access' as 'Org-Wide Settings' is gone from the left navigation pane.

i. e.:
To set Teams guest access settings

Step 4 should read **4. In the Teams admin center, in the left navigation pane select Users > Guest access.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147fb47a-99b2-f8ef-9ca6-35696d49c3fb
* Version Independent ID: b2f1b521-f231-48c2-b61f-f71bf9248d1c
* Content: [Collaborate with guests in a team](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-as-team?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-as-team.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-as-team.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@MacKender Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6503

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MacKender Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
