### ISSUE TITLE
ER advertisement

### ISSUE THREAD

**Issue by dagroll** [MicrosoftDocs/microsoft-365-docs#6445]
[Can you edit this article to add clarity or additional context to what this statement means specifically?  "However, it should not be assumed that no routes are advertised for an endpoint set where ER is No."   It appears under the ER bullet in the article.
  
Does this mean that it IS possible for non-ExpressRoute traffic to be routed through the ER circuit even though it is not advertised for specific endpoint sets?  Does it mean that traffic could be routed through ER on a temporary basis, say when we remove a ER advertisement for a specific endpoint set, but we don't remove the routing/path through ER for those endpoints?  I have had 2 different customers that use ER for O365 connectivity ask me about what this specific statement means, so I suspect it is causing confusion for others as well.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
@kelleyvice-msft I have added this to the endpoints queue.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I agree that this sentence is confusing, and I will revise it for clarification. My understanding is that it is possible that some routes may be advertised in more than one BGP community, making it possible for certain endpoints within the IP range to traverse the ER circuit, but still be unsupported for reasons related to performance or latency. In all cases, the value of a given endpoint set's ER column should be respected. See https://docs.microsoft.com/en-us/microsoft-365/enterprise/bgp-communities-in-expressroute?view=o365-worldwide#key-planning-considerations-to-using-bgp-communities for more information. -Kelley
