### ISSUE TITLE
PDF Protection

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/microsoft-365-docs#645]
I thought PDF was now natively supported by AIP, do you mean AIP protected PDFs won't keep their protection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Office 365 Message Encryption FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq#are-pdf-file-attachments-supported)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@Martony78  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @Martony78  - Thank you for your query. You can view the detailed list of AIP supported file type at https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-file-types

This topic covers all the required information. 

Thanks.

**Comment by Martony78** [comment]
Hi @joinimran,
I know the topic you mentioned states PDF are supported, but the topic we are currently commenting states not. So which topic is wrong? Which topic do you have to correct?

**Comment by joinimran** [comment]
@Martony78 You are saying that like its mentioned that you need to enable this feature. Correct? I am going to update this and thanks for more clarification. 

Thanks.

**Comment by mypil** [comment]
@Martony78 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/bf56a07. 


Thank you for your contribution to make the docs better! Much appreciated!
