### ISSUE TITLE
MCAS/Conditional access may break...

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#6452]
Why is *.cas.ms and *.mcas.ms and *.mcas-gov.us not included?
As per this doc it may be required.
Our network guys say it is not part of this list, so will not include it, and things have broke.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by LauraWi** [comment]
@kelleyvice-msft  -- I have added this to the endpoints queue

**Comment by yogkumgit** [comment]
@kelleyvice-msft Gentle reminder

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. The Office 365 endpoints web service is only designed to include endpoints that are specific to Office 365 services and features. The services you mentioned are not part of Office 365 and are therefore outside the scope of endpoints we can include in the database. Users of services such as Microsoft Defender for Cloud Apps must follow the guidance for that service to ensure proper configuration and to avoid disruption of Office 365 connectivity. -Kelley
