### ISSUE TITLE
Bookings: Instructions for adding a non-bookable admin do not work on the new Bookings experience

### ISSUE THREAD

**Issue by synesthesia** [MicrosoftDocs/microsoft-365-docs#6453]
The method described on this page (to add an Administrator who is not shown as bookable to clients) only works on the legacy Bookings experience. If you switch to the new Bookings Experience when logged in as such a user, all settings screens become read-only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fcbd22b-e14b-fe97-7b7f-eb672e84d382
* Version Independent ID: f9a024d7-6600-4922-02b5-2c8ceeae13ab
* Content: [Add staff to Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/add-staff?redirectSourcePath=%252farticle%252f23ee9b4c-0241-40ff-b663-67a309c378f8&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/add-staff.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/add-staff.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@synesthesia Thank you for your feedback. We have added a note stating the same while the product team fixes the new bookings experience. The changes can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6550

Thanks
Sri
