### ISSUE TITLE
Information is incorrect for stopping forwarding (doesn't list all the ways forwarding can be set up and stopped). 

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#6459]
Information is incorrect for stopping forwarding (doesn't list all the ways forwarding can be set up and stopped). Article should point to the steps here. 

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6924feb-c0eb-6ec2-01cb-0265e181beea
* Version Independent ID: 67de4f08-035e-abf4-8c17-61fd10193cc7
* Content: [Stop auto-forwarding emails](https://docs.microsoft.com/en-us/microsoft-365/business-video/stop-email-auto-forward?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/stop-email-auto-forward.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/stop-email-auto-forward.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @hudish Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MSFTTracyP** [comment]
All right. This issue is resolved. Closing now. Thanks!
