### ISSUE TITLE
captcha is broken

### ISSUE THREAD

**Issue by picklesrein** [MicrosoftDocs/microsoft-365-docs#646]
The captcha on https://sender.office.com does not work. Tried this for 30 minutes in different browsers. Asked three colleagues to try it. Apparently our company is made of cyborgs.

**Comment by bobhwasatch** [comment]
Mine too. We're all robots I guess. The whole thing is absurd. No reason for why I am blocked, can't solve the captcha to unblock, and nobody else is blocking me. Seems pretty broken.

**Comment by mypil** [comment]
@picklesrein @bobhwasatch - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
