### ISSUE TITLE
XMDE Client Analyzer for Linux - Two user experience problems need correcting.

### ISSUE THREAD

**Issue by rywaters** [MicrosoftDocs/microsoft-365-docs#6460]
1st Error:
User goes to run the extracted xmdeclientanalyzer.  If they run as non-root/non-sudo, installation of dependencies work fine, but if they run with "performance" flag at the end of the command as the script tool tip suggests:  
./mde_support_tool.sh performance

Tthe command will install dependancies fine, but will fail with:  __main__.py:  error:  perf is not installed.  Obviously this is because they aren't running the command with -d, but users won't know to do this if they don't read the documentation on the web first or know it even exists.

Looking in the directory structure perf.py is installed, but it seems it can only be called when using -d which a user will not know about when they first run the application.  This presents a bad user experience.  -d is listed as diagnostic, but are likely looking for performance traces and may not know the difference.  It should be simplified or combined to cause less confusion.

2nd Error:
If the user runs the extracted xmdeclientanalyzer as root/sudo, the installation provides the dependencies but with wrong permissions leaving the user wondering why the tool doesn't work properly later.

What's expected?
A user should just be able to run ./mde_support_tool.sh, and then get a tooltip stating if they require performance audit tracing to run with -d instead of "performance" flag which will fail, it fails with the 1st error listed above.  The two options are confusing in what they do, and are going to default to "Performance" flag because it's listed first and sounds like more along the lines of what they want to obtain.  (But isn't).

When the performance flag is done they get an error that states:
__main__.py: error: perf is not installed.

Which is also broken and should work since the tooltip shows it as an option. 

P.S.  I'm posting this under Docs feedback because the link on the docs page for product feedback doesn't lead to anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95ba8ed0-8234-d514-f06e-3ce69e60bfec
* Version Independent ID: 51d6d3ae-6100-7acb-af46-e8ec6b9fe84f
* Content: [Run the client analyzer on macOS or Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@rywaters Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
