### ISSUE TITLE
Incorrect Example Provided

### ISSUE THREAD

**Issue by jaredburnett** [MicrosoftDocs/microsoft-365-docs#6464]
In article, under section "The work flow at a glance" in Part 2: Hash and upload the sensitive data 
After Step #5, the example given is incorrect according to https://o365exchange.visualstudio.com/DefaultCollection/IP%20Engineering/_workitems/edit/2373969
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification?view=o365-worldwide#links-to-edm-upload-agent-by-subscription-type)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks
