### ISSUE TITLE
Onboarding with Microsoft 365 E5 Security and existing Azure Security Center

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#6467]
Hello,

We have:

1. Azure Security Center - so it enables the Windows Defender Security Center platform and we can on-board into Defender ATP the Windows 10 device using Intune MDM onboarding step -> but then this gives price ~10 Euro per device
2. Intune MDM via Microsoft 365 E3
3. We have bought Microsoft 365 E5 Security per User licenses (~10Euro per user), now to onboard, do we follow the same steps for Intune MDM on-boarding, and is it possible that we will receive a bill from Azure Security Center per device (10Euro) and we continue to pay per user per Microsoft 365 E5 Security license assigned (+10Euro)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e228a0-6a2c-2ae2-655b-ada8b6f313bc
* Version Independent ID: fe0dcf35-c7f7-8dce-f829-9bc03827a40a
* Content: [Onboarding using Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboarding-endpoint-manager?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboarding-endpoint-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboarding-endpoint-manager.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. Regarding licenses and whether you would get a bill from the Azure security center, I'd recommend you contact Microsoft support via the need help Icon on the admin center as they can check your existing licenses and future invoice to confirm if you will receive an extra bill for Azure security center.

Hope this helps!

Thanks
Sri
