### ISSUE TITLE
For more information on Microsoft Intune policy settings see, Windows 10 policy settings in Microsoft Intune.

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#6468]
Hello,

Hyperlink not found for this place
"For more information on Microsoft Intune policy settings see, **Windows 10 policy settings in Microsoft Intune**."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c75cd7f-3cba-ac55-e8fb-809e64e7ce36
* Version Independent ID: 9085cbcc-a241-14aa-47f6-6714d5475a23
* Content: [Onboard Windows 10 devices using Mobile Device Management tools](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-mdm?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-mdm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-mdm.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6519

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lightupdifire Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by lightupdifire** [comment]
Thank you!
