### ISSUE TITLE
out of date reference

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#647]
there is reference to an Ignite presentation from 2018 that has a broken link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f47362e-5ac2-badf-9a90-f9f7831e5767
* Version Independent ID: 2c5b4b0a-29ca-6d6c-121c-5d7a81d6ca7e
* Content: [Microsoft 365 NIST 800-53 action plan — Top priorities for your first 30 days, 90 days, and beyond](https://docs.microsoft.com/en-us/microsoft-365/compliance/nist-action-plan)
* Content Source: [microsoft-365/compliance/NIST-action-plan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/NIST-action-plan.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@DeanGross  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@DeanGross  Thank you for the feedback. I have removed outdated information from the doc via PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/682

**Comment by mypil** [comment]
@DeanGross - From our understanding, the issue has been resolved. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
