### ISSUE TITLE
Is there an option to add logo to high contrast blue theme

### ISSUE THREAD

**Issue by harshdamaniahd** [MicrosoftDocs/microsoft-365-docs#6470]
[Missing documentation on high contrast theme logo]

![image](https://user-images.githubusercontent.com/11780473/135477535-2a91438f-5b39-46da-87e6-73af84b11fec.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6c85cc-1680-588e-f520-bcafb1383d53
* Version Independent ID: ea446e6b-e094-dacd-54cc-e597b2f1354d
* Content: [Customize the theme for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/customize-your-organization-theme?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/customize-your-organization-theme.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/customize-your-organization-theme.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by harshdamaniahd** [comment]
any update on this

**Comment by kwekuako** [comment]
Hi @harshdamaniahd, can you give us some more context on this? What documentation is missing?

**Comment by yogkumgit** [comment]
@harshdamaniahd We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
