### ISSUE TITLE
Not clear on Compliance Methodology 

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/microsoft-365-docs#648]
I am still not clear on the formula for calculation of the compliance number? How would the calculation of all the elements of “Essence”, “Threat” and “External Drivers” results in a compliance score of “6”? You should provide clarity with a few examples from the real compliance score.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491e66c0-bfe6-58fa-4a1e-d79ee4ac0e2b
* Version Independent ID: 676dbe71-1ed1-e5db-2f16-f7c12c7565f7
* Content: [Compliance Score Methodology](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score-methodology#feedback)
* Content Source: [microsoft-365/compliance/compliance-score-methodology.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-score-methodology.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by mypil** [comment]
@knssub  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by chvukosw** [comment]
Hi @knssub , we recently published an update to this page to align with the public preview release of Microsoft Compliance Score. Can you take a look to see if that helps answer your question? Thanks.

**Comment by knssub** [comment]
Thanks for the update, appreciate your quick action. The information is clearer compared to earlier data. I found the below page to be more useful on the securing scoring methodology, which is what I was looking for to provide better clarity to a customer on scoring methodology. However, not sure if it still applies to the latest preview release of the product. 
https://docs.microsoft.com/en-us/microsoft-365/compliance/meet-data-protection-and-regulatory-reqs-using-microsoft-cloud

**Comment by chvukosw** [comment]
@knssub Hi there, you are welcome. This week we launched the public preview of Compliance Score, which is a new feature that is a simplified version of Compliance Manager. The score calculation article was updated along with the new documentation we published for Compliance Score, and I invite you to check it out: https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score. The article you link to above actually goes to the older ("classic") version of Compliance Manager, but there's a purple "note" box at the top that hopefully redirects customers to Compliance Score, 

Compliance Score does share a backend with the public preview version of Compliance Manager, and its updated documentation lives here: https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-overview.

**Comment by Soulsailor** [comment]
@chvukosw Is there anywhere where you've documented the relationship between Compliance Score and Compliance Manager?
Which should we be using? It seems like Compliance Score is a broad-brush indicator, whereas Compliance Manager allows deeper dive and analysis into specific compliance regulations etc?

**Comment by chvukosw** [comment]
@Soulsailor  Yes, on the Compliance Score overview topic, https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score, there is a section explaining the relationship. While much of the functionality of managing compliance (most notably, managing assesments) has been brought into Compliance Score, some of it still remains in Compliance Manager.
