### ISSUE TITLE
In the section "Example for this first principle", for the example made for Exchange items, would it be possible to clarify that after the three-year period the items continue to be retained, but in the RecoverableItems of the mailbox? Thank you.

### ISSUE THREAD

**Issue by inmamede** [MicrosoftDocs/microsoft-365-docs#6481]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @inmamede, I see you are a Microsoft employee.  I'll contact you internally.

**Comment by cabailey** [comment]
Closing as discussed & agreed internally.  The principles of retention focus on whether an item will be retained or permanently deleted, not where the item is stored.  The text before the example covers this: 

"While this principle ensures that content is preserved for compliance reasons, the delete process is still initiated and can remove the content from user view and searches. For SharePoint, for example, a document moves from the original folder to the Preservation Holds folder. However, permanent deletion is suspended. For more information about how and where content is retained, use the following links for each workload:"
