### ISSUE TITLE
Office 365 Admin Settings ARE A NIGHTMARE

### ISSUE THREAD

**Issue by mrjasonm** [MicrosoftDocs/microsoft-365-docs#6484]
In all of my 25+ years of using computers, I have literally never had a worse experience than I have with using the Office 365 admin and settings pages. Just trying to track down one little setting has taken over an hour, each and every time.

Add to this experience the fact that this page references options that don't even exist on the pages described and linked to in this article.

It says:
In the admin center, go to the Users > Active users page.
Select a user.
In the right pane, select OneDrive. Under Get access to files, select Create link to files. 

But there is no 'right pane' on that page.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Step 4 - Give another employee access to OneDrive and Outlook data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-4?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-4.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-4.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@mrjasonm Thank you for your feedback. I have updated the document to reflect that it is not the right pane, but the user properties page that appears when you click on a user.  The changes can be tracked via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6528

![image](https://user-images.githubusercontent.com/45987684/136206568-a3c3708e-cec2-45d6-b5a8-3c7e386ca22b.png)


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mrjasonm Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
