### ISSUE TITLE
Policy ID and Entry ID GUIDS

### ISSUE THREAD

**Issue by desinnic** [MicrosoftDocs/microsoft-365-docs#6486]
[Hello, I was wondering if there is any information (clarity) on how the Policy IDs and Entry IDs get created? In the document it highlights you can have multiple Entry IDs but it does not specifically confirm how you would generate the GUIDS.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7a5c17-1358-990b-968d-432a3aab2e17
* Version Independent ID: 1b4d4eff-3e22-47d7-4054-6cc9ed0217d0
* Content: [Microsoft Defender for Endpoint Device Control Removable Storage Access Control, removable storage media](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control?view=o365-worldwide#scenario-1-prevent-write-and-execute-access-to-all-but-allow-specific-approved-usbs)
* Content Source: [microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by mhollaus** [comment]
Hello,
you can use the powershell command: **New-Guid** _for creating a new_ **GroupId, EntryId or PolicyRuleId**.
For more details about creating a new GUID´s have a look a this documentation page: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/new-guid?view=powershell-7.2
I hope I could help you with that information.
br, Markus
