### ISSUE TITLE
Powershell example for SPO is not correct

### ISSUE THREAD

**Issue by alapie** [MicrosoftDocs/microsoft-365-docs#6487]
Hi, the powershell cmdlet and example are not correct

Register-SPODataEncryptionPolicy  https://contoso.sharepoint.com 

command "Register-SPODataEncryptionPolicy" sowan't require the URL

Regards
Alan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bbe84f4-e076-750f-62b7-842c9cd03736
* Version Independent ID: 3380a064-f592-a639-fc4f-35ec021438a3
* Content: [Manage Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-manage?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-manage.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by KCCross** [comment]
Cmdlet instruction updated. Thx for the feedback!
