### ISSUE TITLE
Encryption sensitivity labels and compatibility between clients (desktop and online) 

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#6490]
In this paragraph https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#let-users-assign-permissions, we say right below the table of supported options _"When both settings are selected, the label is therefore visible in both Outlook and in Word, Excel, and PowerPoint."_

This is not the case apparently, as it can create issues with the online apps (Outlook on the web, Word Online, PowerPoint Online etc), where the label would not be visible if these options are enabled on it:

- In Outlook, enforce restrictions with the Do Not Forward or Encrypt-Only option
- In Word, PowerPoint, and Excel, prompt users to specify permissions

Please confirm what is the expected behavior with Engineering and update the article accordingly. From the testing that I've done, I get these results:

**EncryptionEnabled  : True** - the label is of type "encryption" 
**EncryptionEncryptOnly : True** - _this doesn't allow the label to show up in Word, Excel, PowerPoint_
**EncryptionProtectionType : UserDefined** - _the permissions which the label allows to be configured are set to "user defined" and it doesn't allow the label to show up in Office Online apps_
**EncryptionPromptUser**                           **: True** - _this doesn't allow the label to show up in Outlook_

So, basically it means that we cannot have one encryption sensitivity label to rule them all, one that would be usable across all clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Restrict access to content using sensitivity labels to apply encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#example-configurations-for-the-encryption-settings)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Alex-Catalin  The design is that when both options are selected, the label is visible in Outlook, Word, Excel, and PowerPoint. 
 However, not all platforms support this yet - always check the capabilities table to verify support across platforms.  For this one, see "Let users assign permissions: - Prompt users" from  https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#sensitivity-label-capabilities-in-word-excel-and-powerpoint).  You'll be please to know that this capability is coming soon to Office on the web and you can track it with this roadmap item: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=85619

In the meantime, when you enable sensitivity labels for Office files in SharePoint and OneDrive, we list this as one of the limitations (https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide#limitations).

The Encrypt-Only option is for Outlook only - which is why there's no entry for this capability in the table for Word, Excel, and PowerPoint.  If you need a single label to apply encryption across Word, Excel, PowerPoint, Excel, Outlook - and across all platforms - use the Assign permissions now option.

**Comment by cabailey** [comment]
Checking the text on this page, in this section - it begins with "Important: Not all labeling clients support all the options that let users assign their own permissions. Use this section to learn more." and then for "In Word, PowerPoint, and Excel, a user is prompted to select their own permissions for specific users, groups, or organizations" we have the text "To check which apps that use built-in labeling support this option, use the capabilities table for Word, Excel, and PowerPoint and the row Let users assign permissions: - Prompt users."

No doc update needed here, closing.

**Comment by Alex-Catalin** [comment]
Hi Carol,


Regarding “If you need a single label to apply encryption across Word, Excel, PowerPoint, Excel, Outlook - and across all platforms - use the Assign permissions now option.”, do we say this anywhere in the document 😊?

We should be as clear and as transparent as possible with our documentation, so that our customers can actually understand what steps they need to follow to get their desired setup up and running.

Also, this “When both settings are selected, the label is therefore visible in both Outlook and in Word, Excel, and PowerPoint.” should probably be changed to something like “When both settings are selected and the client versions are supported, the label is therefore visible in both Outlook and in Word, Excel, and PowerPoint. Refer to these articles for more details about sensitivity label capabilities across Office clients” I am saying this because clearly at this point, this is not supported as I have seen recently when troubleshooting this issue (missing label) for a customer.

Thank you,


Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
***@***.******@***.***>
9 AM - 6 PM (GMT+2)
***@***.***

**Comment by cabailey** [comment]
@Alex-Catalin  Having reviewed the documentation, I think it's very clear and we're very transparent about these options that aren't available across all platforms.  The section starts off with the note to this effect "Not all labeling clients support all the options that let users assign their own permissions" and the previous section for "Assign permissions to specific users or groups" does not.  The bulleted list that describes each option directs them to the exact row to check in the capabilities tables with a link.  And the text right above the table says "**When the options are supported,** use the following table to identify when users see the sensitivity label".  I think customers will be confused only if they look at the table and following sentence without reading the rest of the section.  The information you proposed is already there.  And for Office on the web, it's also in the Limitations section for "Enable sensitivity labels for Office files in SharePoint and OneDrive". 

The UI also warns them about this when they configure the label, showing an information callout "The labeling behavior for these settings varies depending on which operating system platform is used to apply the label."  It doesn't have that callout for the Assign permissions now option.

If your customers aren't aware of the capabilities tables, please do direct them to this valuable resource.  New features are lighting up all the time and it's expected that they won't immediately be supported by all apps, on all platforms.  If this isn't an acceptable tradeoff for their environment, they shouldn't select the option when they configure a sensitivity label.  They are all optional settings.

**Comment by Alex-Catalin** [comment]
Hi Carol,

Thanks for replying. I hope our customers will be able to understand all the information.

Alex
