### ISSUE TITLE
Regarding Error tags & Error Properties column in unindexeditems.csv file

### ISSUE THREAD

**Issue by vikassou** [MicrosoftDocs/microsoft-365-docs#6497]
Testing shows that the Error tags & Error Properties column is always blanks and doesn't show the error why these items could not be indexed.
Yes, Using the PowerShell script PartiallyIndexedItems.ps1, it possible to find these items.

Information in the docs states "When you export eDiscovery search results or a search report using one of these options, the export includes a report named Unindexed Items.csv. This report includes most of the same information as the ResultsLog.csv file; however, the Unindexed Items.csv file also includes two fields related to partially indexed items: Error Tags and Error Properties" , which I feel needs to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6580cdcf-280e-215c-f4a0-d778b501946f
* Version Independent ID: 3f88be2e-6413-c8e7-f234-f62a74075a2d
* Content: [Investigating partially indexed items in eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/investigating-partially-indexed-items-in-ediscovery?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/investigating-partially-indexed-items-in-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/investigating-partially-indexed-items-in-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@vikassou Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
