### ISSUE TITLE
No info on Advanced Phishing thresholds

### ISSUE THREAD

**Issue by tllampi** [MicrosoftDocs/microsoft-365-docs#650]
Led here by link in O365 S&C Center when editing Advanced phishing thresholds. This page seems to have no information on said thresholds and neither do any of the Related topics.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4186938-9985-7168-674d-0403343bec2f
* Version Independent ID: 86d4eb4a-f7f5-ceff-c58f-b268111cdec9
* Content: [Anti-phishing protection in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-phishing-protection#feedback)
* Content Source: [microsoft-365/security/office-365-security/anti-phishing-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-phishing-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by tllampi** [comment]
More specifically this link : http://go.microsoft.com/fwlink/?LinkId=869586

**Comment by mypil** [comment]
@tllampi - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@tllampi Thank you for your feedback. I have checked and the link presented in the S&C admin center is incorrect. I'll check with the author to see how we can get this corrected quickly. Meanwhile, the correct link would be https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies

Thanks
Sri

**Comment by mypil** [comment]
@tllampi - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
Still requires doc owner's inputs.. Reopening issue

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your inputs on this issue?

Thank you.

**Comment by MSFTTracyP** [comment]
Updated. Thank you.
