### ISSUE TITLE
DLP for on-prem File Servers

### ISSUE THREAD

**Issue by vianeyhm** [MicrosoftDocs/microsoft-365-docs#6507]
Hello team;

I see that based on this documentation DLP for on-prem File Servers is on GA, and when I go to the DLP wizard to create a policy, it shows a message saying that DLP for on-prem File Servers and SharePoint on-prem is in Preview. Could you please confirm if to is GA or not? I have to ensure this info to one of our partners working with a customer who is looking for this capability.
I want to be sure that the customer will have support in case of any issue during the deployment phase. Thanks in advance!

Vianey
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feb442b7-6653-cf98-8a0a-e9994d6606b8
* Version Independent ID: 3cfb788a-15ab-cc23-c8cc-cfd399731a85
* Content: [Get started with Microsoft 365 data loss prevention on-premises scanner - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-on-premises-scanner-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-on-premises-scanner-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-on-premises-scanner-get-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks
