### ISSUE TITLE
Need to update the URL link which written in "Change Log subscription" in "Office 365 URLs and IP address ranges" KB

### ISSUE THREAD

**Issue by o365tatsuyan** [MicrosoftDocs/microsoft-365-docs#6509]
[Enter feedback here]
URL links which written in "Change Log subscription" in "Office 365 URLs and IP address ranges" KB (https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide) should be updated to the correct link.

Repro Steps
----------------
1. Click Change Log subscription in "Office 365 URLs and IP address ranges" KB (https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide).
2. Click the link of  "https://endpoints.office.com/changes/Worldwide/2021092800?singleVersion=true&amp;clientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7
" to check the content of "2021092800 - Worldwide".

Expected result
===========
Supposed to show the "Office 365 Worldwide Services instance" change log as in JSON format.

Current result
===========
It returns following message:
"Valid ClientRequestId Guid is required in the query string. Documentation is available at http://aka.ms/ipurlws"

Reson of error
=============
The "&" mark in the link is displayed as an HTML-encoded string "& amp;".

Current link
https://endpoints.office.com/changes/Worldwide/2021092800?singleVersion=true&amp;clientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7

Should be display the link as below
https://endpoints.office.com/changes/Worldwide/2021092800?singleVersion=true&clientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@o365tatsuyan Thank you for your feedback. I'm currently able to view the correct log in JSON format and it points to https://endpoints.office.com/version/worldwide?allversions=true&format=rss&clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7

Hope this helps!
Thanks
Sri

**Comment by o365tatsuyan** [comment]
hi @msbemba, thank you for responding to this subject. But as far as I can see it still contains "& amp;" in the URL. 
https://endpoints.office.com/version/worldwide?allversions=true&format=rss&clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7 

![image](https://user-images.githubusercontent.com/33974498/136202376-57e1827b-9e17-4385-856b-7198f56eff98.png)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by LauraWi** [comment]
Tagging endpoints and assigning to @kelleyvice-msft for assessment.

**Comment by kelleyvice-msft** [comment]
All links in the article have been corrected.
