### ISSUE TITLE
Information about the "Mark as and Notify" and what it does

### ISSUE THREAD

**Issue by Breid125** [MicrosoftDocs/microsoft-365-docs#6511]
Please update this documentation to cover the new "Mark as and Notify" feature.

Does this kick off any Phish Zap or remediation if we flag a message as Phishing?

-Brendan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Manage submissions - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Breid125 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6810

"Mark as and Notify" does not kick off any Phishing Zap or remediation. The reported message will be marked as either false positive or false negative, and an email will be automatically sent from within the portal notifying the user who reported the message.

Hope this helps!
Thanks
Sri

**Comment by Breid125** [comment]
Thank you so much!

And now the Review interface changed again! Can’t get ahead on these things lol.

-Brendan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Breid125 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
