### ISSUE TITLE
Bad Link (404 error)

### ISSUE THREAD

**Issue by proximityeffect** [MicrosoftDocs/microsoft-365-docs#6513]
[Connect to the Security & Compliance Center using remote PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell&clcid=0x409)  <-bad link

Good link? 
https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec12506-ca29-0a03-3b01-699cb22b7ab7
* Version Independent ID: 6dc6083d-fcde-3622-5653-61c5be4bb5db
* Content: [View the reports for data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-au/microsoft-365/compliance/view-the-dlp-reports?WT.mc_id=M365-MVP-4039827&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/view-the-dlp-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-the-dlp-reports.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @proximityeffect Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
