### ISSUE TITLE
AzureRm commands still referenced

### ISSUE THREAD

**Issue by Gideon122** [MicrosoftDocs/microsoft-365-docs#654]
This article still references the use of AzureRm commands, when according to https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az, the Az module should be used instead. Has this article not been updated because it requires the AzureRm module? Would using the Az command equivalents cause issues?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a585eca1-dad6-3afd-43ce-8c4b11102dd3
* Version Independent ID: a1d708a7-774f-0c23-b428-28919ef5d46a
* Content: [Controlling your data in Office 365 using Customer Key](https://docs.microsoft.com/en-us/microsoft-365/compliance/controlling-your-data-using-customer-key)
* Content Source: [microsoft-365/compliance/controlling-your-data-using-customer-key.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/controlling-your-data-using-customer-key.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by get-itips** [comment]
Hello @Gideon122 I am proposing thru a pr the use of the new Az module, if the author approves, it will be used instead of the current Azure Rm.
Thanks

**Comment by KCCross** [comment]
PowerShell updates complete.
