### ISSUE TITLE
page not linked in TOC

### ISSUE THREAD

**Issue by barlan** [MicrosoftDocs/microsoft-365-docs#6542]
This page doesn't have a link in the TOC, though I assume it should populate underneath the "Troubleshoot" node.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00421a8e-42cf-c393-f91d-da1b7d7cc7da
* Version Independent ID: de00b816-762d-2171-eb7f-1ce6a55ec189
* Content: [Getting a mailbox not found error in Outlook on the web - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/mailbox-not-found-error?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/mailbox-not-found-error.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/mailbox-not-found-error.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by yogkumgit** [comment]
@pebaum Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@pebaum Gentle reminder. Thanks

**Comment by tiburd** [comment]
Thank you for the feedback.

The article has been updated and added to the TOC via the private repo:
https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/21817
