### ISSUE TITLE
Command-Lines in the document appear to have incorrect charaters

### ISSUE THREAD

**Issue by desinnic** [MicrosoftDocs/microsoft-365-docs#6553]
[I recently used some of the commands documented here with a customer that did not work

wget --quiet -O XMDEClientAnalyzer.zip https://aka.ms/XMDEClientAnalyzer * <The Asterix here causes the download of the tool to fail>

unzip -q XMDEClientAnalyzer.zip

cd XMDEClientAnalyzer

chmod +x mde_support_tool.sh" <The addition of the " on this command-line means that the command does not run>

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95ba8ed0-8234-d514-f06e-3ce69e60bfec
* Version Independent ID: 51d6d3ae-6100-7acb-af46-e8ec6b9fe84f
* Content: [Run the client analyzer on macOS or Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@desinnic Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6578

Thanks
Sri

**Comment by desinnic** [comment]
Hi Sriraman

I have just reviewed the updated document but I still see the Asterix on the command below which seemed to cause the download to fail.

Without it the Asterix it worked

wget --quiet -O XMDEClientAnalyzer.zip https://aka.ms/XMDEClientAnalyzer *

Kind Regards

Dean

Dean Sinnick
Support Escalation Engineer | Apps & Infra | Security - Microsoft Defender for Endpoint
Customer Service & Support | Microsoft Corporation
Working hours: Monday - Friday 8am - 5pm  (UTC+1)
* +44 (118) 9094639 * ***@***.******@***.***>

***@***.***

If you have any feedback about my work, please let either me or my manager Daniel Balan know at ***@***.******@***.***>



From: Dean Sinnick
Sent: Tuesday, October 12, 2021 2:35 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>; MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Command-Lines in the document appear to have incorrect charaters (#6553)

Hey Sriraman,

Thanks for updating the documentation

Kind Regards

Dean

**Comment by msbemba** [comment]
@desinnic I have updated it via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6596

Thanks for the feedback.

Thanks
Sri

**Comment by desinnic** [comment]
Many Thanks Sri
