### ISSUE TITLE
Exchange Admin Centre in Exchange Online

### ISSUE THREAD

**Issue by linx-collin** [MicrosoftDocs/microsoft-365-docs#6554]
This page details the steps for the Exchange Admin Center (EAC) then at the bottom there's a link entitled "Exchange admin center in Exchange Online" but when you go to that link, the resulting page doesn't explain how to do what the previous page was attempting to explained for EAC?

When you click on the 'Exchange' option under 'Admin centers' on the 'Microsoft 365 admin center' page, it takes you to **https://outlook.office365.com/ecp** and not **https://admin.exchange.microsoft.com/** which is where the link in the instructions on this document takes you. This distinction needs to be pointed out in the document.

Without that distinction, in the Exchange admin center that opens when you click on the 'Exchange' option under 'Admin Centers' on the 'Microsoft 365 admin center' page there is no "Manage email apps" in the right hand _Details Pane_ as instructed in the document. There is indeed such an option in the  "**Microsoft admin center**" in the 'Mail' tab of the Properties fly-out when you select a user in the 'Active users' section. And, of course as you rightly describe, that option is there in the 'Exchange admin center' if you access the one under **https://admin.exchange.microsoft.com**.

if for some reason my 'Microsoft 365 admin center' is not up-to-date, I'd appreciate some guidance on how to ensure it's the latest iteration.

Thanks
Collin

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ecd4f58-0a50-05f2-426d-6bc8ca8f5940
* Version Independent ID: b3344450-204e-3bb4-54ad-5fa4f85a2695
* Content: [Step 1 - Stop an employee from logging in to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/add-users/remove-former-employee-step-1?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-1.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@linx-collin Thank you for your feedback. When you click on Admincenters-->Exchange, You should ideally be redirected to https://admin.exchange.microsoft.com/ as this is the new Exchange admin center, If you are still seeing the classic admin center, you can click on New Exchange admin center and follow the instructions. The classic admin center should no longer be the default page when you click on Exchange under admin centers. If that continues, I'd recommend you to contact Microsoft support and understand if there is a problem with the tenant in the backend.

Hope this helps!
Thanks
Sri
