### ISSUE TITLE
Need to update link to NPP page

### ISSUE THREAD

**Issue by ScottSchnoll** [MicrosoftDocs/microsoft-365-docs#6559]
We need to change the NPP page link from https://www.microsoft.com/microsoft-365/partners/O365networkingpartners to https://cloudpartners.transform.microsoft.com/m365networkingpartners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8fb78a-6077-98ec-af2c-10eead8c6d93
* Version Independent ID: 728fd5ea-8e57-ea6f-3230-3578b517fc2f
* Content: [Microsoft 365 Networking Partner Program - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-networking-partner-program?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/microsoft-365-networking-partner-program.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-networking-partner-program.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@tiburd Please help here. Thanks

**Comment by tiburd** [comment]
@ScottSchnoll 
Hi, you can create a PR in the private repo, [microsoft-365-docs-pr](https://github.com/MicrosoftDocs/microsoft-365-docs-pr), to submit that change.

For information, you can review the [MARVEL Authoring Guide for Docs](https://review.docs.microsoft.com/en-us/office-authoring-guide/office-docs-authoring-overview?branch=master).

If you need additional assistance, you can post your question(s) on the [Ask an Admin Teams channel](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fchannel%2F19%253aea9a561f603c4fbb9cf3931a6849eae4%2540thread.skype%2FAsk%252520an%252520Admin%3FgroupId%3D7079ffbf-1420-4ee2-9ddc-a2c351337320%26tenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47&data=02%7C01%7Cv-reagie%40microsoft.com%7C9508ddf4587f4b13920b08d75e3379c4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637081450935535631&sdata=vGG3BJvVSwYIUXt54IWALvcyeIT%2BFm09VMBhCMLdjF0%3D&reserved=0).

Thanks!
