### ISSUE TITLE
Microsoft IPs in audit logs

### ISSUE THREAD

**Issue by sssseossss** [MicrosoftDocs/microsoft-365-docs#656]
Hello,
I'm wondering if you could direct me to the answer - sometimes audit search results in entries with Microsoft IP addresses in source field, e.g. 40.119.148.223 or 52.157.234.216.
What are those hosts and how to identify Microsoft services with customer instances in Azure cloud ?
Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@sssseossss As you've identified, some activities that are logged in the audit log are performed by Microsoft as part of maintaining the cloud-based service. This includes configuration changes/updates. Other audit records for some services result from a trusted application calling into the service on behalf of a user (or your tenant). One example of this is  Office on the web apps. 

To help you identify these, in an audit record, you and view the RecordType and Workload properties and the UserID and UserType properties. For more info about audit log record properties, see:

https://docs.microsoft.com/en-us/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log

https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema

Hope this helps.
