### ISSUE TITLE
WVD to AVD

### ISSUE THREAD

**Issue by nyflash** [MicrosoftDocs/microsoft-365-docs#6562]
[Enter feedback here]
should be azure virtual desktop, not windows virtual desktop.. the chart is also a bit confusing.. maybe the question should be "launch/access application from laptop" with AVD, the customer still has to have an Laptop/device to run the AVD client on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9e777b-afbb-5b77-f5b8-56ce92593261
* Version Independent ID: e61ad6c2-ccf1-c26c-ca17-38e4314baa15
* Content: [Step 2. Provide remote access to on-premises apps and services](https://docs.microsoft.com/en-us/microsoft-365/solutions/empower-people-to-work-remotely-remote-access?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/empower-people-to-work-remotely-remote-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/empower-people-to-work-remotely-remote-access.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nyflash Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
