### ISSUE TITLE
Information Barriers, as part of Office 365 and Microsoft 365 A1, A3 or A5 faculty and student licensing

### ISSUE THREAD

**Issue by rsoakford** [MicrosoftDocs/microsoft-365-docs#6568]
I read at https://admin.microsoft.com/AdminPortal/home#/MessageCenter/:/messages/MC290063 (Published Oct 8, 2021) that  "You will also see a new service plan, Information Barriers, as part of your Office 365 and Microsoft 365 A1, A3 or A5 faculty and student licensing details."

I assume that means the license requirements are changing - perhaps this documentation could be updated to reflect those license changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Learn about information barriers in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by rsoakford** [comment]
@msbemba , thank you for updating me - it seems the changes to the document have not been merged - is that because the message center announcement regarding availability of Information Barriers feature for Microsoft 365 A1 and A3 licenses is no longer current?

**Comment by msbemba** [comment]
@rsoakford Thank you for your feedback. The Author will verify the changes with the Product group and merge changes once it is approved. it could take 24-48 hours after the PR is merged.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rsoakford Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
