### ISSUE TITLE
page sends product feedback to feedback hub that doesn't support SCC categorisation

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/microsoft-365-docs#657]
page sends product feedback to feedback hub that doesn't support SCC categorisation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Alert policies in the security and compliance center](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@bakerm00 Not sure why this is taking you to a Windows feedback hub. But, you can go here to provide feedback for SCC: https://office365.uservoice.com/forums/289138-office-365-security-compliance

Thanks for taking the time to do this.
