### ISSUE TITLE
Mail-enabled security groups as data locations?

### ISSUE THREAD

**Issue by Wh00T** [MicrosoftDocs/microsoft-365-docs#6575]
The docs state that only individual mailboxes and distribution groups are supported as data locations:
_Type into the search box the name or alias (a minimum of three characters) of user mailboxes or distribution groups_

The wizard allows me to select mail-enabled security groups & M365 groups as well, I'm curious if they are supported and just missing in this documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aab7cc9-714d-2322-c349-5e5e4eaea227
* Version Independent ID: 1f5ebfdf-6949-9d28-d374-3338fc189eeb
* Content: [Add custodians to an Advanced eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-custodians-to-case?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/add-custodians-to-case.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-custodians-to-case.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Wh00T Thanks for reaching out. These other groups can be associated to a custodian in Advanced eDiscovery. So, if the group can be resolved (that is, displayed in the picker list ) it can be associated with the custodian. We will update the documentation.
