### ISSUE TITLE
Issues using New-OrganizationAddIn with SSO-enabled Outlook add-in

### ISSUE THREAD

**Issue by elegault** [MicrosoftDocs/microsoft-365-docs#6579]
The `New-OrganizationAddIn` cmdlet doesn't work reliably when attempting to deploy an SSO-enabled Outlook add-in:  

1. After the `New-OrganizationAddIn` cmdlet is run, the following text is sometimes not output to the console and the script appears to hang until the ENTER key is hit multiple times:
>     The Add-In you are trying to upload supports Single Sign On and to upload the Add-In you need to use Office 365 Admin Center.
>     Press Enter to consent to the Add-In in Office 365 Admin Center.
>     If there are any issues you can go to
>     https://portal.office.com/adminportal/home?assetid=lob&mktcmpid=powershell#/Settings/ServicesAndAddIns
>     And go to Settings > Services & Add-Ins
2. The page that is launched in a browser (/ServicesAndAddIns) appears to be incorrect

What is expected:

1. The `New-OrganizationAddIn` cmdlet should immediately display the above text and process the ENTER key
2. The browser should be launched to the "Configure add-in" page at https://portal.office.com/adminportal/home?assetid=lob&mktcmpid=powershell#/Settings/AddIns, where consent can be provided to the deployment of the SSO-enabled add-in

Note that I see that there's potential issues with MFA enabled, but I'm able to successfully call `Connect-OrganizationAddInService`, login and approve the sign-in request with the Microsoft Authenticator app.  I've also tested with an Application Registration that has had no admin consent granted to Graph API permissions for the tenant, and with admin consent granted.

Would the lack of a MPN ID for Publisher verification in the Application Registration impact the usage of this cmdlet in any way?

Also, can it be confirmed that this cmdlet automates anything at all for SSO-enabled Office add-ins?  Or if will still be an entirely manual process for the admin?  If it is the latter, the documentation should be updated to state that the cmdlet is intended only for non SSO-enabled Office add-ins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a092120-6209-1c44-8bc1-f989f62f37b7
* Version Independent ID: f9eb09fb-e430-d797-25d3-b8bb67a85512
* Content: [Use the Centralized Deployment PowerShell cmdlets to manage add-ins - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
@elegault, thanks for reaching out. Since this is a technical problem, not a content issue, I cannot help you directly. I have contacted the listed owners of the [O365CentralizedAddInDeployment](https://www.powershellgallery.com/packages/O365CentralizedAddInDeployment/1.5.0.3) module to ask for the best way for you to report the issue and get help. I will update this issue when I get a response.

You can also contact the owners of the module yourself at https://www.powershellgallery.com/packages/O365CentralizedAddInDeployment/1.5.0.3/ContactOwners if you prefer.

Sorry I couldn't be of more help.
Kelley
