### ISSUE TITLE
Spelling and Grammer

### ISSUE THREAD

**Issue by helloitsliam** [MicrosoftDocs/microsoft-365-docs#658]
Nothing major, couple of gramer/spelling items:

Spelling Mistake: "The recomendation is to use restrictive ETRs where possible.", recommendation is spelt incorrectly.
Space need here: "the header text as appropriate.When a message"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365#feedback)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@helloitsliam  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@helloitsliam - PR #670 has been created by to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
