### ISSUE TITLE
Please separate out the section for skype from teams

### ISSUE THREAD

**Issue by rbishop-etq** [MicrosoftDocs/microsoft-365-docs#6583]
Please separate the Skype for Business and Teams section. We are trying to move AWAY from skype and ensure all employees are on teams, so it would be very helpful if you indicated the differences so we can block the skype-only domains to ensure nobody is using that product anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@LauraWi Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
I have notified the engineering team of this request, and they are aware of the problem. My understanding is that they are working on a resolution, but that there may be some overlap in IP address ranges between the two services, at least in certain configurations. Hopefully, we will see these services separated in a future update. -Kelley
