### ISSUE TITLE
Auditing and licensing

### ISSUE THREAD

**Issue by bchris999** [MicrosoftDocs/microsoft-365-docs#659]
"Only users with E5 licenses or mailboxes where mailbox audit logging was manually enabled by an admin will return mailbox audit log events in audit log searches in the Security & Compliance Center or via the Office 365 Management Activity API."

I can't get Exchange Audit events for users on the Office 365 Business Essentials license through the Management Activity API, although I can see these through a Powershell session.  Does Exchange audit events through the Management API require an E5 license?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing](https://docs.microsoft.com/en-gb/microsoft-365/compliance/enable-mailbox-auditing)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@bchris999  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@bchris999, when you say you can see the auditing events .."through a PowerShell session", I presume you mean using the New-MailboxAuditLogSearch and/or Search-AdminAuditLog cmdlets and NOT Search-UnifiedAuditLog in Exchange Online PowerShell? If so, that's expected.

Visibility of mailbox auditing events in the Management API requires EITHER an E5 license for the mailbox in question OR mailbox auditing is manually enabled on the mailbox in question (for all other licenses). This all has to do with 'mailbox auditing on by default', which basically only works for E5 licenses. Everyone else needs to manually turn on mailbox auditing on the mailbox to see auditing events in the SCC or via the Management API.

**Comment by bchris999** [comment]
Thanks. After some further investigate, it looks like, although it shows as enabled if you look at the AuditOwner etc properties on Get-Mailbox, you need to explicitly manually enable it again for it to produce events through Set-Mailbox. This really isn't clear in the documentation.

e.g. Set-Mailbox -AuditEnabled $true -AuditOwner HardDelete

**Comment by mypil** [comment]
@chrisda - Can you please share your inputs on the additional feedback from bchris999? 

Thank you.

**Comment by chrisda** [comment]
bchris999 is correct. That's what I meant and what the content talks about when you 'manually enable audit logging on a mailbox'.

**Comment by JeremyTBradshaw** [comment]
I have to ask @chrisda, this E5 or manually-enable point, is it only referring to the mailbox audit log?

What I'm trying to confirm is if that statement is also referring to logs showing up in the unified audit log.  My understanding is that the auditing on by default (Set-OrganizationConfig) with the default settings leads to all mailboxes being enabled for mailbox auditing (of the default audited activities per logon type).

**Comment by mypil** [comment]
@bchris999 - Thanks for your confirmation that you found the resolution to your issue. We will close this issue now.

In case there is something you feel should be improved in the doc, we strongly encourage our readers to contribute by creating a Pull request to add in what you found. 

Thank you for helping us improve the documentation!
