### ISSUE TITLE
license requirements for Microsoft Defender for Endpoint on Mac

### ISSUE THREAD

**Issue by sringler** [MicrosoftDocs/microsoft-365-docs#6599]
In the license requirements section for Microsoft Defender for Endpoint on Mac states "Windows 11". I guess it should mean "Windows 11 E5"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e9b530-4f11-0483-ed65-42b23082f9f6
* Version Independent ID: 38263c08-7cab-7d52-552d-e724ede401aa
* Content: [Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sringler Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
