### ISSUE TITLE
needs a little extra explanation on retention

### ISSUE THREAD

**Issue by joshfolcik** [MicrosoftDocs/microsoft-365-docs#6600]
If items in the mailbox are held by a retention policy, such as a record label, or mailbox retention policy from compliance center policies - retention - when the license is removed is that data still retained? Or does the account need to be "deleted" instead of unlicensing it as a way to make sure that data is retained for the length of the retention period or record label policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d850211-99b4-faf7-09fc-4621919dd74b
* Version Independent ID: 9b294f13-b1e3-291e-25a1-75f7c5755b6c
* Content: [Unassign licenses from users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/remove-licenses-from-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/remove-licenses-from-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/remove-licenses-from-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @joshfolcik Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
