### ISSUE TITLE
Outdated Instructions and Video

### ISSUE THREAD

**Issue by fabiotelesMS** [MicrosoftDocs/microsoft-365-docs#6602]
I would like to point out that the instruction video on this site is still using the old Azure Portals and names, so it harder to follow up the instructions.

The **Registering AD Application and Permissions** it different right know. Made my own personal notes on this and the steps where:

![image](https://user-images.githubusercontent.com/92537712/137355634-d24b940b-98bf-4477-beb6-9104e46b5731.png)

![image](https://user-images.githubusercontent.com/92537712/137355805-390e78f4-ec3f-46fa-89ea-2912f4e87d62.png)

Just letting you know about this for a possible review that will help all the customers and users of this product, with the new Portals and names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d4287b-0207-5c4f-ae5b-9b0fc33d36a9
* Version Independent ID: 53fdc584-5530-cf5e-fb2c-75591bb082bf
* Content: [Access the Microsoft Defender for Endpoint APIs](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/apis-intro?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/apis-intro.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/apis-intro.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Thank you for the feedback. Currently not slated for immediate update but will add to radar for future update.
