### ISSUE TITLE
You must reverse this

### ISSUE THREAD

**Issue by yborjoe** [MicrosoftDocs/microsoft-365-docs#661]
Enterprise Customers must have administrative and billing control over these applications and tools. I am not that control nut and generally try to make things less restrictive, but allowing end use to directly procure, assign, etc products is wreckless and irresponsible from a corporate governance standpoint. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by VeroniquePalmer** [comment]
Totally agree.

**Comment by jktech89** [comment]
100% terrible. This encourages users to utilize company CC or financial resources to purchase MS licenses to their own accounts. Admins need full control over SW licensing & in no way should allow users to assign their own licensed without admin approval or assigning the license.  Plus your undercutting your partners by trying to provide direct support when the rest of the products all are administered though the o365 It admins.

**Comment by yborjoe** [comment]
Wanted to circle back and express appreciation to Microsoft for posting plans, listening to feedback and for the willingness to act on it, as outlined in the new update as of last week. Beyond allowing adjustment through PowerShell, I suggest a means of simply enabling or disabling this ability by user account. In the end, I believe we most likely will decided admin on a per user / role basis vs product by product. Having the product distinction is helpful as well, but primary judgement will center on determining if the user should have the ability and then ensure proper understanding and application of the ability in the organization.

**Comment by cmcatee-MSFT** [comment]
@yborjoe Thank you for your feedback. We continue to review and evaluate feedback from customers on this feature.
