### ISSUE TITLE
So how do we truly whitelist exceptions (i.e. phishing simulations, mail to SecOps)

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/microsoft-365-docs#6613]
Hello,

The last section in the article refers to Exceptions. How do we add true whitelisting for those exact use cases that are exceptions like making sure the phishing simulation emails are not blocked? We cannot report to Microsoft as a false positive each time we run an automated phishing simulation. 

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472b3a0c-7ad8-8245-9b57-29431490370b
* Version Independent ID: 8671f04a-b7b3-402c-1e65-59a52c1cdaf5
* Content: [Secure by default in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-by-default?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/secure-by-default.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-by-default.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
msbemba's pull request contains the update.

Closing

**Comment by netaneladar** [comment]
Thank you very much
