### ISSUE TITLE
Label Activity Explorer

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#662]
Please identify the permissions needed to view the Label activity explorer, I assumed that the Compliance Administrator would be able to do this, but they cannot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center#permissions-needed-to-use-features-in-the-security--compliance-center)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@DeanGross  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
@DeanGross 

I would suggest
* Compliance Data Administrator 
* eDiscovery Manager and
* Compliance Administrator

**Comment by chrfox** [comment]
Hi @DeanGross 
I have confirmed with the product team that Compliance admin role has access to this page.
Chris
