### ISSUE TITLE
Required Permissions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#663]
What role is required to see this page? I can't get to it using the Compliance Admin or the Compliance Data Admin roles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3d3633-893d-9354-9402-c47ed7dec790
* Version Independent ID: fc12340b-403f-b531-04be-91f00a8f0af6
* Content: [View label activity for documents](https://docs.microsoft.com/en-us/microsoft-365/compliance/view-label-activity-for-documents)
* Content Source: [microsoft-365/compliance/view-label-activity-for-documents.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/view-label-activity-for-documents.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@DeanGross  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by chrfox** [comment]
Working with PG to get an answer

**Comment by chrfox** [comment]
Hi Dean - According to PM, Compliance Admin should see this page. I don't know why you are not seeing it.
