### ISSUE TITLE
Issues using Remove-OrganizationAddIn with SSO-enabled Outlook add-in

### ISSUE THREAD

**Issue by elegault** [MicrosoftDocs/microsoft-365-docs#6637]
The `Remove-OrganizationAddIn` cmdlet doesn't work when attempting to remove an SSO-enabled Outlook add-in.  If I run this command:

`Remove-OrganizationAddIn -ProductId 309aa6a5-85a4-4910-a9a2-4eb5fb3f6e41`

This error is output:
````
Remove-OrganizationAddIn : Add-In could not be removed. Activity ID: 4a8b3f36-c448-43e7-a246-ec40587dd311
At C:\{SCRIPT PATH}.ps1:138 char:17
+ ... ovedAddin = Remove-OrganizationAddIn -ProductId 309aa6a5-85a4-4910-a9 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (309aa6a5-85a4-4910-a9a2-4eb5fb3f6e41:Guid) [Remove-OrganizationAddIn], AddInDeletionException
    + FullyQualifiedErrorId : UiRequired,Microsoft.OrganizationAddInPowerShell.Cmdlets.RemoveOrganizationAddIn
````

I also tried deleting the associated App Registration in Azure first, but I got this error the first time (the second time I tried, I got the error above):

````
Remove-OrganizationAddIn : One or more errors occurred.
At C:\{SCRIPT PATH}.ps1:138 char:17
+ ... ovedAddin = Remove-OrganizationAddIn -ProductId 309aa6a5-85a4-4910-a9 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-OrganizationAddIn], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.OrganizationAddInPowerShell.Cmdlets.RemoveOrganizationAddIn
````

What is expected:

- The add-in is deleted

Note that this is possibly related to other issues with SSO add-ins, as per #6579. I'm guessing the UiRequired error implies that SSO add-ins can only be deleted from the Microsoft 365 admin center and that the Centralized Deployment cmdlets cannot be used. Can this be confirmed?

**Comment by kelleyvice-msft** [comment]
See related issue https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6579 for more information about what I've done to try and find help for you. Closing this issue as it is a technical problem, not a content issue.
