### ISSUE TITLE
Incorrect instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#664]
I don't see this page under the Classification heading as described above, I do it under the Information Governance heading. Please update the instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35afb875-bb47-fc7d-7e95-36cbde2b671b
* Version Independent ID: 3a2ad411-cae1-efa2-f089-97ed2df52fb4
* Content: [View label usage with label analytics](https://docs.microsoft.com/en-us/microsoft-365/compliance/label-analytics)
* Content Source: [microsoft-365/compliance/label-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/label-analytics.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@DeanGross  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LauraWi** [comment]
Hi @DeanGross Thank you for the feedback. With the sweeping changes to Compliance UI rolling out between Ignite 2019 and January, we are planning a global scrub of content to update UI references. Thanks.
