### ISSUE TITLE
microsoft

### ISSUE THREAD

**Issue by THANAWIWAT** [MicrosoftDocs/microsoft-365-docs#6644]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 0735069a-c3cd-f230-52a5-01b093c2dc3d
* Version Independent ID: 32eb9da0-b2d6-d9d3-f37c-6610db9406e2
* Content: [Support information for Thailand - Microsoft 365 admin](https://docs.microsoft.com/th-th/microsoft-365/admin/support/thailand?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/thailand.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/thailand.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@THANAWIWAT We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
