### ISSUE TITLE
What is meant by "merge" the contents of an inactive mailbox to another mailbox?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#665]
For "Restore an inactive mailbox", how does the inactive mailbox show up in the active mailbox?  Does it appear like a shared mailbox on the user's account/Outlook?  Or is all the inactive inbox, sent, deleted, etc... mail mixed in with the active user's inbox, sent, deleted, etc... folders?  How are the user created folders merged?  "Merge" to me sounds like it is all just mixed in with the active mailbox without being easily distinguishable.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Overview of inactive mailboxes in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Canis-Lupis Please take a look at these topics: 

https://docs.microsoft.com/en-us/microsoft-365/compliance/restore-an-inactive-mailbox#restore-an-inactive-mailbox

https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/New-MailboxRestoreRequest

Restoring the contents of an inactive mailbox into an active mailbox is accomplished by using the New-MailboxRestoreRequest cmdlet in EXO PowerShell. If you use the TargetRootFolder parameter, you can specify a folder in the target mailbox (the active mailbox) to copy the content from the inactive mailbox into. See step 2 in the section above for an example of the syntax to use. This will let you keep the items from the inactive mailbox separate from the content in the target mailbox. If you don't use the TargetRootFolder parameter, then "the contents of the inactive mailbox (source mailbox) will be merged into the corresponding folders in the existing mailbox (target mailbox)" and "new folders are created if they don't already exist in the target folder structure".

Hope this helps.

**Comment by Canis-Lupis** [comment]
Thank you.
