### ISSUE TITLE
Interactive guide outdated

### ISSUE THREAD

**Issue by chrisshilt** [MicrosoftDocs/microsoft-365-docs#6650]
The interactive guide is outdated. The product name is incorrect, and the portal is the old portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a541e5c3-8a8d-d766-918e-f53091e32294
* Version Independent ID: 44e9ef9e-1355-8ded-f79d-7683fadaec0c
* Content: [Overview of Microsoft Defender Security Center](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/use?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/use.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/use.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
At this time, the interactive guide is not slated for an immediate update but it’s on the radar.
