### ISSUE TITLE
Access denied, banned sending IP 

### ISSUE THREAD

**Issue by AbbasM14** [MicrosoftDocs/microsoft-365-docs#666]
I am trying to send emails via a SMTP relay server in CORP and I get the following error. We do not have a dedicated public IP.
Diagnostic-Code: smtp;550 5.7.606 Access denied, banned sending IP [xxxx]. To request removal from this list please visit https://sender.office.com/ and follow the directions. For more information please go to http://go.microsoft.com/fwlink/?LinkID=526655 (AS16012609) [xxxxxEop-nam06.prod.protection.outlook.com]

**Comment by mypil** [comment]
@AbbasM14 - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by AbbasM14** [comment]
Hi Joyce,
I followed the following link and following couple of tickets with the exchange team they directed me here.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis

However, we do not have a dedicated public IP and I have delisted few IPs but still the issue exists. Emails are being sent using ipsback@microsoft.com<mailto:ipsback@microsoft.com>.

Thanks
Abbas Ali Mohammed
DPS Catalog : https://aka.ms/dps
DPS Request forms : http://aka.ms/dpsrequestforms

**Comment by mypil** [comment]
@AbbasM14 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
