### ISSUE TITLE
Missing Step (Settings)

### ISSUE THREAD

**Issue by PortableTech** [MicrosoftDocs/microsoft-365-docs#6662]
Between steps 1 and 2 you need to add a step to select Settings.  The Device Onboarding is under settings while this page implies it is at the top level which it is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0ac0e1-6f08-2f8b-10c7-a967e53886f8
* Version Independent ID: f510237f-0ec9-d266-3ec6-0ad6b49e2522
* Content: [Get started with Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-getting-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-getting-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PortableTech Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
