### ISSUE TITLE
Is CloudFlare a supported DNS Provider/Registrar

### ISSUE THREAD

**Issue by PsychoData** [MicrosoftDocs/microsoft-365-docs#6664]
The DNS Providers list does not include CloudFlare, but I think they support all the required record types? 

They are who is hosting DNS for all of my domains, and Registrar for most of them - Is CloudFlare supported to use this with Office 365? Should it be added to the list? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?redirectSourcePath=%252farticle%252f39cee536-6a03-40cf-b9c1-f301bb6001d7&view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.yml)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PsychoData Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
