### ISSUE TITLE
Update manual submission process to reflect new policies in effect for spam report processing

### ISSUE THREAD

**Issue by langjtl** [MicrosoftDocs/microsoft-365-docs#6669]
The Microsoft Security Research Spam Analysis team replied to a manually submitted spam report saying their automation cannot process spam reports sent without Abuse Reporting Formatting standards. Outlook does not add ARF when a message is sent with the offending email attached. The documentation for manual submission does not reflect this requirement. According to the spam analyst who informed the customer of the inability to process the submitted attachment, their team is not allowed to open attachments sent to junk@office365.microsoft.com or phish@office365.microsoft.com. If the sender uses the Outlook junk mail reporting add-in, the proper format is added to the submission. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b12c078-eccb-7786-dec6-ea1bdb91d088
* Version Independent ID: aa1e8002-a8db-383e-cbeb-abf92c033bd3
* Content: [Manually submit messages to Microsoft for analysis - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
@langjtl, so it sounds like manually reporting messages by sending them to email addresses is effectively no longer supported. I removed the topic and any references to it, and redirected it to the main [Report messages and files to Microsoft](https://docs.microsoft.com/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft).

Thanks for the feedback.

Closing
