### ISSUE TITLE
Prerequisite KB missing reference numbers

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/microsoft-365-docs#6673]
In Prerequisites under the section the Endpoint data loss prevention (Endpoint DLP) the following KB reference is appears to be missing some of the number ? Please can this be corrected ? thanks
Windows 10 2004 with KB **46013**

**Comment by msbemba** [comment]
@quickclix75 Thank you for your feedback. I can confirm that the missing reference numbers are  Windows 10 2004 - KB4568831, KB4577063. This has been updated in https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide.

Do you see any other document which is missing this information?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @quickclix75 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
