### ISSUE TITLE
Validating the Environment status

### ISSUE THREAD

**Issue by ryeguy637** [MicrosoftDocs/microsoft-365-docs#6677]
It would be very helpful if the Validating the Environment section gave additional detail on what the ComatibilityStatus messages "Warning" and "Incompatible" mean (and what the administrator can do for mitigation).

For example, on 10/15/21, I received this

![image](https://user-images.githubusercontent.com/37934378/138479743-516052b2-a03b-4ebe-b781-ab100ea7a183.png)

On 10/22/21, I received this

![image](https://user-images.githubusercontent.com/37934378/138479838-8d35363d-8a37-4342-a243-10f348585a0e.png)

It would be helpful if this page gave more information about these status messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7694fb1-d70c-1951-b9df-cd43809f3cf2
* Version Independent ID: a8002dd0-d033-4049-1545-e77fd570f276
* Content: [Move a OneDrive site to a different geo location - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/move-onedrive-between-geo-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/move-onedrive-between-geo-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/move-onedrive-between-geo-locations.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@ryeguy637 Hope this comment is helpful for you. If you see any other documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
