### ISSUE TITLE
Templates List - grouping by functional area + full names

### ISSUE THREAD

**Issue by nanoonan538** [MicrosoftDocs/microsoft-365-docs#6678]
Could we include some of these types of updates to help customers navigate what templates are available and what applies to them? It is hard for a customer to know what some of these are without taking other steps to look them up. It is also hard to know which align with each discipline (e.g. what a privacy officer what a records manager, what info security team might use to navigate their program).

1. List the full name of the assessment. Include the link to the source if possible. e.g.:
a. [ISO 15489:1: 2016](url) Information and documentation - Records management - Part 1: Concepts and principles
b. [ISO 16175-1:2020](url): Information and documentation — Processes and functional requirements for software for managing records — Part 1: Functional requirements and associated guidance for any applications that manage digital records

2. Provide how these match to different risk, compliance and privacy disciplines. Perhaps building a table that can group by global vs. regional, discipline, industry, included vs. premium, etc.?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a406f24f-e0c1-9143-9130-ce0459a66235
* Version Independent ID: e040197a-12cc-281a-d75d-16395b24c46f
* Content: [Microsoft Compliance Manager templates list - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-templates-list?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-manager-templates-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-templates-list.md)
* Service: **o365-seccomp**
* GitHub Login: @jmgriffee
* Microsoft Alias: **v-jgriffee**

**Comment by yogkumgit** [comment]
@jmgriffee Please help us in resolving this issue. Thanks

**Comment by jmgriffee** [comment]
Hi. I think I found this issue in GitHub, but this is going to take some time to review. This is a massive list and I don't have all of the info requested. Is this blocking the push request I made for this morning? I need to get those out today and there's no way I can edit the template list per this request that soon.

Thanks,

  *   jenny

**Comment by jmgriffee** [comment]
As it happens, I'm being asked to wait to push my other edits live, but my question still stands about the issue: is this going to block any other publishing requests? I'm going to need some time to review, and want to be sure this isn't a blocker for other day-to-day changes in the section. Thank you!

  *   jenny

From: Jenny Griffee (Robert Half International)
Sent: Monday, November 1, 2021 8:03 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Subject: RE: [MicrosoftDocs/microsoft-365-docs] Templates List - grouping by functional area + full names (Issue #6678)

Hi. I think I found this issue in GitHub, but this is going to take some time to review. This is a massive list and I don't have all of the info requested. Is this blocking the push request I made for this morning? I need to get those out today and there's no way I can edit the template list per this request that soon.

Thanks,

  *   jenny

**Comment by nanoonan538** [comment]
From my perspective this is simply a recommendation/enhancement on how to make this page more usable for our customers, as it can be difficult for them to find which assessments apply to them. There is not a specific blocker or other indicator of priority. It may just help customers more quickly find/use what is relevant to their programs.

**Comment by jmgriffee** [comment]
Okay, thank you. Sorry for my concern there -- this morning's been a bit of a fire drill. :) I'll review the issue in more detail and discuss it with the rest of the team.

**Comment by yogkumgit** [comment]
@jmgriffee When you complete the review and plan an update, please close this issue. Thanks

**Comment by yogkumgit** [comment]
@jmgriffee Please reply and resolve this issue. Thanks

**Comment by jmgriffee** [comment]
In the near term, I'm adding a note to the template list page that you can view individual templates in CM to see a description. (I think we want to avoid duplicating that info into the docs, since A; it's an ongoing maintenance challenge and B: would make the page very long and unwieldy very quickly.) Later this month, engineering is also adding a wizard to CM to aid in selecting templates that are relevant to your organization, based on properties like your industry and country. This should help streamline the whole process of template selection and get around a few of the concerns that I think led to this ask to begin with, since it'll narrow your scope to the templates that should matter most to you. Longer term, I think the concept/structure of this page might still benefit from a revisit, but I'm in the process of handing work over to a different member of my team, so I'll run it by her for awareness before my contract ends.
