### ISSUE TITLE
Self Service Licensing must be OFF by default and not managed via PowerShell

### ISSUE THREAD

**Issue by VeroniquePalmer** [MicrosoftDocs/microsoft-365-docs#668]
Thanks for responding Microsoft, but the self-service licensing must be off by default, not on.  And be configurable using opt-in / opt-out radio buttons on the admin centre, not via PowerShell,  Otherwise you are just creating more issues for companies not large enough to have a fulltime / qualified IT Pro to manage this for them.

**Comment by mypil** [comment]
@VeroniquePalmer  - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by VeroniquePalmer** [comment]
This one, sorry, I couldn't figure out how to add the comment to the thread.

https://docs.microsoft.com/en-gb/microsoft-365/commerce/subscriptions/self-service-purchase-faq



Sent from my phone, please excuse any brevity or typos


-------- Original message --------

**Comment by UmbraTenebrae** [comment]
To further comment on this - just so MSFT is aware, these self-service policies have resulted in us updating our Acceptable Use Policy to include use of the self-service options as a fireable offense.  I assume it is not MSFT's intent to cost people their jobs but that is what these changes are exposing the end-users to.

**Comment by cmcatee-MSFT** [comment]
@UmbraTenebrae  Thank you for your feedback, Microsoft looks to balance the needs across its customer base including IT Pros and users.  By providing a per application toggle through Powershell and providing adequate notification we are looking to provide IT organizations the control they need while ensuring consideration is given to the features intended to provide end-user productivity value.

**Comment by VeroniquePalmer** [comment]
What about all the companies out there that are NOT IT companies…..?
