### ISSUE TITLE
Is the e-Discovery search feature available via API?

### ISSUE THREAD

**Issue by grandunity** [MicrosoftDocs/microsoft-365-docs#669]
Curious if I can run a search across all mailboxes via Graph API similar to the Outlook 2.0 API, I didn't see anything in the API reference.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e514aa-9f04-5cc9-93f6-9f5f2f614c2a
* Version Independent ID: dea1ab15-bc09-05c1-b48b-1a06c0b53b50
* Content: [Content Search in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@grandunity  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@grandunity Neither APIs you cite are related to Content Search. Content Search is based on *ComplianceSearch cmdlets in Security & Compliance Center PowerShell. You can use the Content Search tool in the Security & Compliance Center or the New-ComplianceSearch cmdlet to search all mailboxes in the org. Would suggest that you contact Microsoft Support with API questions.
