### ISSUE TITLE
356 off

### ISSUE THREAD

**Issue by THANAWIWAT** [MicrosoftDocs/microsoft-365-docs#6692]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b25a9f3-ff11-7b5a-a485-060ef6246abd
* Version Independent ID: aceda4b9-d6df-2dff-bd46-209b48f9aa75
* Content: [Manage Windows 10 Pro device policies with Microsoft 365 Business Premium](https://docs.microsoft.com/en-US/microsoft-365/business-video/secure-win-10-pro-devices?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/secure-win-10-pro-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/secure-win-10-pro-devices.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@THANAWIWAT Please let us know what is your feedback, regarding improving this documentation.

**Comment by yogkumgit** [comment]
@THANAWIWAT We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
