### ISSUE TITLE
Amend article to show details on "Antivirus status" and its various values

### ISSUE THREAD

**Issue by benpaul4u** [MicrosoftDocs/microsoft-365-docs#6697]
Please amend article to show details on "Antivirus status" and its various values similar to Onboarding Status.

We see "Not supported", "Not updated", "Updated" and "Uknown" values when export Device Inventory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d401bb34-5a2e-7f66-8fcd-28a395c62a99
* Version Independent ID: 1022827b-273c-7351-ee5d-189e6caa5fee
* Content: [View and organize the Microsoft Defender for Endpoint devices list](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machines-view-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machines-view-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machines-view-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@benpaul4u Thank you for your feedback. I'm currently working with the author to get more information on these statuses.

Thanks
Sri

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Still pending PG response.

**Comment by mjcaparas** [comment]
Table reflects correct status - Disabled, not updated, unknown.

**Comment by IngramQ** [comment]
Was this issue addressed as the report dose indeed include the following status:

Updated
Not Supported
Unknown
Not Updated
Disabled

The status I am most curious about is Not Supported.
