### ISSUE TITLE
mdatp binary supports --output switch

### ISSUE THREAD

**Issue by import-au** [MicrosoftDocs/microsoft-365-docs#6700]
The mdatp binary for macos (and Linux) supports the `--output` switch. I know it supports json, not sure what other output types are allowed. Would be nice to have this documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9240d179-335e-1031-d077-6bc0dbc8d5a7
* Version Independent ID: b3a7140b-d37e-e27f-d973-2cf6f10a4af8
* Content: [Resources for Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-resources?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-resources.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@import-au Thank you for your feedback. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6806

Once the author approves or adds new output to the PR, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @import-au Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
