### ISSUE TITLE
Step 6 is ambiguous

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/microsoft-365-docs#6703]
Step 6 says to select the user. This isn't clear as what you need to do is double click the user to get to the next page where you can assign a license. Simply clicking the check box or single clicking the user does not give you the option of assigning a license. 

It would be helpful in the next step to indicate a page would open as well. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42a261b-afb1-e8d4-e61d-c9d30cb71a00
* Version Independent ID: 3649a463-b7d6-104a-608f-cfcf16b66cb5
* Content: [Assign licenses to users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-licenses-to-users-on-the-licenses-page)
* Content Source: [microsoft-365/admin/manage/assign-licenses-to-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/assign-licenses-to-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@StuBeck32 closing as per author's feedback. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
