### ISSUE TITLE
Hybrid envrionment.  Can't add external contacts to o365 groups.  global admin.  Can't see group settings.

### ISSUE THREAD

**Issue by dimmthewitted** [MicrosoftDocs/microsoft-365-docs#6704]
Hybrid envrionment.  Can't add external contacts to o365 groups.  global admin.  Can't see group settings.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?redirectSourcePath=%252fen-us%252farticle%252fmanage-guest-access-in-office-365-groups-9de497a9-2f5c-43d6-ae18-767f2e6fe6e0&view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @dimmthewitted 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
