### ISSUE TITLE
Document Update Request |  Email attachments file name currently does not work for Exchange Events

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/microsoft-365-docs#6707]
[Enter feedback here]
The documentation says DLP  Exchange Event alerts  includes name of the attachment however that does not seems to be the case. Have confirmed this in repro environment and there seems to be active feature request /DCR in progress.
So requesting to update/remove following section that email attachment name are not included in Exchange events as if now.

--------------

Email attachments | Names of the attachments in the email that violated the DLP policy | Exchange events
---------------
-- | -- | --

</body>
</html>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e9f547-6180-2981-6e7a-895fc17b7703
* Version Independent ID: 58334631-7058-1809-0804-c107457b4470
* Content: [Configure and view alerts for data loss prevention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-configure-view-alerts-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-configure-view-alerts-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-configure-view-alerts-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
queried PG

**Comment by chrfox** [comment]
confirmed with the PG that what is documented is correct.
