### ISSUE TITLE
What to do with Outbound False Positive EOP detections

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#671]
Could do with some guidance on supported submission methods for these, as I believe admin submissions from new portal for outbound false positives are not currently supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542e0451-1d3b-e811-3a39-c96ddc02668c
* Version Independent ID: 80a8fd41-992a-9f68-70bc-61346dee9b2f
* Content: [Control outbound spam in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/outbound-spam-controls#feedback)
* Content Source: [microsoft-365/security/office-365-security/outbound-spam-controls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/outbound-spam-controls.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@aldoug  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello @aldoug - Thank you for your query. I would suggest you visit https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission to see if this is something that will help you to submit messages for analysis.

Thanks.

**Comment by mypil** [comment]
@aldoug - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
