### ISSUE TITLE
redirect configuration not available anymore

### ISSUE THREAD

**Issue by grabery** [MicrosoftDocs/microsoft-365-docs#6710]
Hello all
It seems, that the redirect configuration is not available anymore. In compliance.microsoft.com > Settings, there is no "compliance center redirection". Protection.microsoft.com is also not reachable anymore, so I guess the redirection can't be set anymore. I checked it with two tenants and with the appropriate rights to do so (global admin & compliance admin) and it's the same for both tenants. If this is globally the case, the docs should be updated, that this is not possible anymore, also not as a short-term solution as stated in this article. Can you confirm that this is the case?

Best,
Yannic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f27732-40e2-dc52-177f-775afa16a753
* Version Independent ID: 13cb2ee3-168b-2e80-7fe1-01b798ebd524
* Content: [Redirect users from the Office 365 Security and Compliance center to the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center-redirection?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/microsoft-365-compliance-center-redirection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-compliance-center-redirection.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@grabery - thanks for the feedback, this has been updated in the topic.
