### ISSUE TITLE
install_mdatp_dnf.yml 'enable repo' not working

### ISSUE THREAD

**Issue by blakebourgeois** [MicrosoftDocs/microsoft-365-docs#6716]
To get the code in 'install_mdatp_dnf.yml' to work, I first had to swap "dnf" to "yum" on CentOS. I am not sure if the difference between dnf and yum caused an issue with the enablerepo value.

In the commands provided in the 'install_mdatp_dnf.yml' section, the enablerepo value is "packages-microsoft-com-prod-[channel]"

Using yum with this value, ansible fails to install mdatp.

Setting the value to "packages-microsoft-prod" did work. 

I assume the suggested value should read "packages-microsoft-[channel]" instead, or additional clarification/yml examples may be useful for yum if they are distinct from dnf. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5b7c531-90a1-7f6b-4c1d-0a126cdea398
* Version Independent ID: 5a10f1bb-6407-d706-0b79-bf448a8eda9d
* Content: [Deploy Microsoft Defender for Endpoint on Linux with Ansible](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-ansible?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-with-ansible.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-with-ansible.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@blakebourgeois Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6808

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @blakebourgeois Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
