### ISSUE TITLE
Could you Please add that when setting "Action" to "Audit", GenerateAlert needs to be specified.

### ISSUE THREAD

**Issue by KENJISHIRAKI** [MicrosoftDocs/microsoft-365-docs#6717]
[Enter feedback here]
A customer of mine was having trouble creating an indicator from the API explorer, because setting 'Audit' in the action resulted in an error.
The reason was that the API was missing a setting called "GenerateAlert": "TRUE".
"GenerateAlert" is an item that must be set to "TRUE" when creating an action with "Audit".
I have received a request to improve it as it is not mentioned in the Docs.
so, please correct the above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea229ca-05ce-38c5-003e-4d811b0bed25
* Version Independent ID: 765b3d95-745c-357b-b19e-87ee0b0a1661
* Content: [Submit or Update Indicator API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/post-ti-indicator?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/post-ti-indicator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/post-ti-indicator.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@KENJISHIRAKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6809

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @KENJISHIRAKI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
