### ISSUE TITLE
What to do with Outbound False Positive EOP detections form the "Send a copy of all suspicious outbound email messages to the following email address" option

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#672]
Could do with some guidance on supported submission methods for these, as I believe admin submissions from new portal for outbound false positives are not currently supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure the outbound spam policy](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@aldoug  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by VLG17** [comment]
@aldoug Is the admin swamped with a lot of false positives for outbound mails that go through EOP? The normal thing to do is submit these for scanning using the submition tool (i don't know why you say it's currently unsupported)- more details [here](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission)

![image](https://user-images.githubusercontent.com/41186174/69531788-2c7dec00-0f7d-11ea-9b87-d667d89830a9.png)

If the admin sees a lot of false positives, it might be the case that there are users who need to send bulk messages, which is not a supported use of the EOP service, as described [here] (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/outbound-spam-controls)

"Recommended workarounds for customers who want to send outbound a lot of email through EOP
It is difficult to strike a balance between customers who want to send a large volume of email vs. protecting the service from compromised accounts and bulk emailers with poor list acquisition practices. Again, the cost of an outbound IP landing on a 3rd party blocklist is higher than blocking a customer from sending outbound email. **_As described in the Exchange Online Service Description, using EOP to send bulk email is not a supported use of the service and is only permitted on a "best-effort" basis._**"

**Comment by aldoug** [comment]
Hi

As per the guidance provided in the internal release announcement around the submission portal, submission requests for outbound spam are not supported

Is it possible to continue this conversation internally?

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by MSFTTracyP** [comment]
@aldoug I will follow up with you, directly.

**Comment by mypil** [comment]
@aldoug - We will close this issue as it will be handled internally based on the comment from the author @MSFTTracyP.

 Thank you for your contribution to make the docs better!
