### ISSUE TITLE
Note referencing shared computer activations needs to be re-added to this article...

### ISSUE THREAD

**Issue by ferringer** [MicrosoftDocs/microsoft-365-docs#6723]
This article used to contain a note stating "You must be a global administrator, global reader or reports reader in Microsoft 365 or an Exchange, SharePoint, or Skype for Business administrator to see reports. Shared computer activations are not included in this report."

It appears that the entire note containing that quoted text was removed as a part of a batch update to these report articles targeting the first sentence of the note (https://github.com/MicrosoftDocs/microsoft-365-docs/commit/71b76ec8029dc9a806a4c94dc175b7569b64950b#diff-443ab17167df7ebc460b38551306fce8583ab01d2df08174175e57b2d1971217), but in the case of this article I believe the second sentence covering shared computer activations should not have been removed. This limitation is still in place and should be communicated in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7957baf3-919b-fa91-073c-d71672282268
* Version Independent ID: 418a59f1-83bd-ff70-fbff-c3980f083ff8
* Content: [Microsoft 365 Reports in the admin center - Microsoft 365 Apps usage - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/microsoft365-apps-usage-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/microsoft365-apps-usage-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/microsoft365-apps-usage-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ferringer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
