### ISSUE TITLE
Change this setting via web?

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/microsoft-365-docs#6728]
How can I change this setting using the web GUI interface instead of poewrshell scripts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DontNeedNoGit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
