### ISSUE TITLE
Wrong title, this is not demonstrating what the title says

### ISSUE THREAD

**Issue by idefy** [MicrosoftDocs/microsoft-365-docs#6730]
This is not how to create A shared calendar. This is creating a group to view SEVERAL calendars together side by side.
Expected: A shared calendar is a single calendar where multiple people contribute too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a466b2e-2dbf-41c2-1f4d-f31522752389
* Version Independent ID: 9ec6a420-11ba-0f35-3c98-fe11b3d83a1a
* Content: [Create a shared calendar](https://docs.microsoft.com/en-us/microsoft-365/business-video/shared-calendar?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/shared-calendar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/shared-calendar.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @idefy Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
