### ISSUE TITLE
missing KB numbers

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/microsoft-365-docs#6733]
The Windows KB Prerequisite section appears to have missing numbers on one of the KB references..

Endpoint data loss prevention (Endpoint DLP):

Windows 10 1809 with KB 4601383
Windows 10 1903 and 1909 with KB 4601380
**Windows 10 2004 with KB 46013**

Please can this be updated

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed8ccbd-b955-4a11-f4dd-3a70b549a5f7
* Version Independent ID: 257024d1-afb3-954f-c848-21549cb64fac
* Content: [Enable co-authoring for documents encrypted by sensitivity labels in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/sensitivity-labels-coauthoring?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-coauthoring.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-coauthoring.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@quickclix75  Apologies the KB number got truncated - should be KB 4601382 and updated in the article now.  Thanks for flagging this.  Closing.

**Comment by quickclix75** [comment]
> @quickclix75 Apologies the KB number got truncated - should be KB 4601382 and updated in the article now. Thanks for flagging this. Closing.

Thanks @cabailey I have advised our client as appropriate
