### ISSUE TITLE
Delist portal doesn't trigger an email

### ISSUE THREAD

**Issue by bcebulla** [MicrosoftDocs/microsoft-365-docs#674]
The portal here is not sending a verification email after the form is submitted: https://sender.office.com/

I have tried this two dozen times with different emails and have enlisted other employees and friends to try to see if they can get the portal to work. Nope. We have all checked our junk folders as well. 

This is of course frustrating because this is the block message we're getting. Opening up support tickets with Office and Outlook postmaster have been fruitless, they have no idea how to help us. 
> 550 5.7.606 Access denied, banned sending IP [XXX.XX.XXX.XXX]. To request removal from this list please visit https://sender.office.com/ and follow the directions. For more information please go to http://go.microsoft.com/fwlink/?LinkID=526655 (AS16012609) [SN1NAM04FT033.eop-NAM04.prod.protection.outlook.com]

**Comment by mypil** [comment]
@bcebulla - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by bcebulla** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis

**Comment by mypil** [comment]
@bcebulla - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by bcebulla** [comment]
Creating a service ticket was not helpful unfortunately, they did not know how to help us. 

I did, however, solve this problem, it might be worth either fixing this issue, or updating your documentation to mention that mailbox providers may be blocking MSFT's email verification email because it's poorly configured.

The problem is that MSFT's form is sending a misconfigured email (https://twitter.com/snootgirl/status/1177037875260612608), so Gmail is blocking MSFT's email, which is super ironic.

I solved this by using a made up email address at http://www.yopmail.com/en/, they'll accept anything. Sure enough, got the email immediately.

**Comment by mypil** [comment]
@bcebulla - Can you please share with us the MS support ticket number when you were troubleshooting with the MS support rep?

Thank you.

**Comment by bcebulla** [comment]
Ticket #: 17404814

**Comment by mypil** [comment]
@bcebulla - We have already engaged with the author and the product engineering team to look into the Delist portal issue. I will close this issue now but please refer to issue #592 on updates on the status. 

Thank you for your contribution to make the docs better! We truly appreciate it.

**Comment by MSFTTracyP** [comment]
@andypunt I'm including you to ask you about this statement: 'because it's poorly configured.
The problem is that MSFT's form is sending a misconfigured email (https://twitter.com/snootgirl/status/1177037875260612608), so Gmail is blocking MSFT's email, which is super ironic. I solved this by using a made up email address at http://www.yopmail.com/en/, they'll accept anything. Sure enough, got the email immediately.'

**Comment by andypunt** [comment]
I don't see this as an issue. I just tested and I got the message as expected with a GMail account. If GMail is blocking good mail, that is configured to send correctly, then one should check personal settings or call GMail to see why.

**Comment by MSFTTracyP** [comment]
Thank you, @andypunt. @mypil Please direct issues where this issue happens to Support for resolution and, if necessary, root cause analysis. Thank you.

**Comment by bcebulla** [comment]
@andypunt I think that is incorrect, unless MSFT has since fixed this issue. Please see the message from @ex-bart on how your mail is configured incorrectly: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/592#issuecomment-566010173

```
When I tried delisting, I got this in my exim's rejectlog:
2019-12-13 10:38:01 1ifhOb-0001j0-Vk H=mail-dm6nam12on2089.outbound.protection.outlook.com (NAM12-DM6-obe.outbound.protection.outlook.com) [40.107.243.89] F=<no-reply@microsoft.com> rejected after DATA: maximum allowed line length is 998 octets, got 3172

```

**Comment by andypunt** [comment]
As Tracy stated, open a case with Support. Otherwise, the original statement was GMail was rejecting and that did not repro. If this is happening on the EXIM server, then I am not sure how that is set up and you should work with Support. Thanks.
