### ISSUE TITLE
Performance analyzer for Microsoft Defender Antivirus - Hangs using PS ISE

### ISSUE THREAD

**Issue by ms-jamesholt** [MicrosoftDocs/microsoft-365-docs#6741]
found that if you run the command in a non ISE PowerShell window the command works as expected, BUT if you run it in PowerShell ISE it fails and hangs.

![image](https://user-images.githubusercontent.com/93407309/139499189-4e04fe22-8694-4419-9626-99006cceeaa4.png)

![image](https://user-images.githubusercontent.com/93407309/139499217-dc49a440-4a8d-495a-b2ab-ab79d828aa20.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e075325-c8a9-4152-352f-6399e036c896
* Version Independent ID: 03ff8166-3867-23f1-5dc3-75f603cfe919
* Content: [Performance analyzer for Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tune-performance-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

**Comment by msbemba** [comment]
@ms-jamesholt Thank you for your feedback. I'm able to reproduce the issue and this happens only on ISE. We handle the documentation part, so I'd recommend you report the issue as a bug to the Product group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@ms-jamesholt Thank you for reporting this feedback here. This list is focused on content issues and I want to make sure your immediate product issue does not get lost in this list. If you would please open a service ticket the support engineers will be able to identify if there is a bug (highly likely) and escalate to the appropriate product team. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
