### ISSUE TITLE
“Formally Intune”

### ISSUE THREAD

**Issue by DarrenBennett** [MicrosoftDocs/microsoft-365-docs#6744]
[Enter feedback here]

Why does this article state Endpoint Manager is “formally Intune”?

The Microsoft docs for Endpoint Manager clearly state Intune is a feature of Endpoint Manager. Endpoint Manager is not “formally Intune”, it’s a suite of solutions that include Intune. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 673970ca-2f79-a288-978c-ceb4845c5062
* Version Independent ID: 2a58449f-b0d4-bf17-1209-d7b8ec0481b6
* Content: [Turn on network protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-network-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@DarrenBennett Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6805

Thanks
Sri

**Comment by DarrenBennett** [comment]
@msbemba Thanks for the update of the document and for updating me.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DarrenBennett Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
