### ISSUE TITLE
Why not add a few examples?

### ISSUE THREAD

**Issue by flavorlabadmin** [MicrosoftDocs/microsoft-365-docs#6745]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd851389-130d-f800-f73d-b7561ccff612
* Version Independent ID: 58ee1cc9-d047-da22-0f56-865643d10d7c
* Content: [Use the command line to manage Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/command-line-arguments-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/command-line-arguments-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/command-line-arguments-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@flavorlabadmin Thank you for your feedback. The example on the document explains how to  the utility and perform a full scan

Example:
MpCmdRun.exe -Scan -ScanType 2

The commands and their description are mentioned in the document as well. let me know if you need more information.

Hope this helps!
Thanks
Sri
