### ISSUE TITLE
Last successful sync at... not visible on Admin Center - Viva Learning settings

### ISSUE THREAD

**Issue by sanand0** [MicrosoftDocs/microsoft-365-docs#6747]
On the Admin Settings, I don't see the "Last successful sync at ..." message. If there are any conditions under which it's displayed, or if it's an upcoming/retired feature, could you please document that?

This is what my screen looks like:
![image](https://user-images.githubusercontent.com/63734/139612398-cbb694ce-976c-4560-b35c-819b2a14e7f4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5a0a8a-12c2-f5f2-df76-21a97ebb9639
* Version Independent ID: 23bdcd81-ec3e-4e68-8fed-f69a025c32eb
* Content: [Manage content sources for Microsoft Viva Learning in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/microsoft-365/learning/content-sources-365-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/learning/content-sources-365-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/learning/content-sources-365-admin-center.md)
* Service: ****
* Product: **microsoft-365-enterprise**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by daisyfell** [comment]
@sanand0 I'm checking with the team to confirm and will adjust the documentation accordingly. Thanks for bringing this to my attention!

**Comment by daisyfell** [comment]
@sanand0 and @yogkumgit This is a GA feature. You should be able to see this anytime after 1 November.
