### ISSUE TITLE
Error for User

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/microsoft-365-docs#6748]
This setting seems not to work in Intune: "./Vendor/MSFT/Policy/Config/Printers/EnableDeviceControlUser". It gives an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0131f7d-e811-d9bc-c372-c56b19b4a091
* Version Independent ID: 0fc6d8db-b125-3985-b9d7-c97587d4ebd2
* Content: [Microsoft Defender for Endpoint Device Control Printer Protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/printer-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/printer-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/printer-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Lovina-Saldanha
* Microsoft Alias: **v-lsaldanha**

**Comment by msbemba** [comment]
@Air-Git Thank you for your feedback. This seems to be working. 

Hope you are using the setting

OMA-URI setting 
Name: Provide a name for the OMA-URI setting to distinguish it from other similar settings
Description: (Optional) Provide a description for the OMA-URI setting to further differentiate settings
OMA-URI: Specify ./Vendor/MSFT/Policy/Config/Printers/EnableDeviceControl as value
Data type: Select String
Value: Specify <enabled/> as value

If this is still an issue, I'd recommend contacting Support via the need help section on the admin center.


Hope this helps!
Thanks
Sri

**Comment by Air-Git** [comment]
Yes, the device setting works. The user setting does not.

The settings are unusual because normally a device setting would be: "./Device/Vendor..." and a user setting would be "./User/Vendor....". A setting like "./Vendor..." is interpreted as the default "./Device/Vendor..."

But in this case the "User" part has been added at the end. And it does not work.

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Air-Git 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
