### ISSUE TITLE
Does "applied automatically to entire mailbox (default)" apply to a user's online archive as well?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#675]
I'm a little confused on how to set an auto deletion policy for an online archive.  There isn't a separate option for this, so does "applied automatically to entire mailbox (default)" mean that if you set perm deletion for it that it applies to the online archive as well?  For example, if I set 'move to archive' after 2 years but set deletion to after 3 years, does everything in my mailbox AND online archive get deleted after 3 years?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your Office 365 organization](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@Canis-Lupis  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@Canis-Lupis As per the scenario at the beginning of this topic: "Automatically (and permanently) deletes items that are 7 years old from both the primary and archive mailbox." You can apply both a DPT configured as and archive policy and a DPT configured as a deletion policy to a mailbox, as we have done in this scenario. The trick is configure the retention period for the archive policy that is shorter than the retention period configured for the deletion policy. That is why the retention period is 3 years for the archive policy and 7 years for the deletion policy. This strategy is further described here: https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/retention-tags-and-policies#retention-policies: "The DPT with the Move to Archive action must have a lower retention age than the DPT with a deletion action. For example, you can use a DPT with the Move to Archive action to move items to the archive mailbox in two years, and a DPT with a deletion action to remove items from the mailbox in seven years. Items in both primary and archive mailboxes will be deleted after seven years."
