### ISSUE TITLE
How to use Email Related APIs

### ISSUE THREAD

**Issue by shanajira** [MicrosoftDocs/microsoft-365-docs#6756]
Email related events are not query-able with API
is there a Limitation for programmatically extracting Email related events?

I tried polling the EDR endpoints for these events:

EmailAttachmentInfo
EmailEvents
EmailPostDeliveryEvents
EmailUrlInfo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2083c132-17ab-50a8-bbe2-0957d2badafa
* Version Independent ID: 1e0578f5-57f1-afc1-1910-d1995e09e391
* Content: [Get relevant info about an entity with go hunt](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-go-hunt?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-go-hunt.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-go-hunt.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by shanajira** [comment]
![emailimage](https://user-images.githubusercontent.com/67111632/139766979-a34e936d-dc7b-417f-b477-fcd941f8363f.jpg)

**Comment by schmurky** [comment]
Not sure if this is related but I see a public preview/prerelease note on the doc for EmailAttachmentInfo. Are you able to access the tables inside the product/not via API?

**Comment by shanajira** [comment]
@schmurky  Yes. I was able to login to EDR Console at security.microsoft.com and was able to write a small query and pull meta data on EmailAtttachmentInfo table.
no problems there.
Problem seems to be only in API way of extracting the these tables.
I tried via my Python application as well as using API explorer -both ways fails.
Error message in both cases are different though

**Comment by shanajira** [comment]
@yogkumgit any ETA on fixing this issue?

**Comment by yogkumgit** [comment]
@schmurky Thank you very much for the contribution and sharing this explanation. @shanajira Hope this comment is helpful for you. Here, we are limited to documentation changes only. If you see a documentation update is required, please feel free to open an issue for the same else contact support. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mshalev** [comment]
@shanajira - Email events are part of Microsoft 365 Defender - you are calling the Microsoft Defender for Endpoint endpoint (//api.securitycenter.windows.com/) instead of the M365 Defender endpoint (//api.security.microsfot.com/).
See [Microsoft 365 Defender Advanced Hunting API](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-advanced-hunting?view=o365-worldwide#:~:text=Advanced%20hunting%20is%20a%20threat-hunting%20tool%20that%20uses,API%20allows%20you%20to%20programatically%20query%20event%20data.) for details on achieving your intent.

**Comment by schmurky** [comment]
Hi @yogkumgit perhaps we can remove the doc-enhancement label as the issue doesn't seem to be in need of a doc update. Thank you!

**Comment by yogkumgit** [comment]
@schmurky This for internal reporting purpose only. :)

**Comment by schmurky** [comment]
Got it! :)
