### ISSUE TITLE
Update replication time for Single Item Recovery

### ISSUE THREAD

**Issue by janeannilagan** [MicrosoftDocs/microsoft-365-docs#6758]
PS C:\temp> Set-Mailbox $mbx -SingleItemRecoveryEnabled $false
WARNING: The single item recovery setting may take up to 240 minutes to take effect.

The documentation needs an update from 60 minutes to 240 minutes for proper expectation and change window.
Step 2 - Item 3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the Recoverable Items folder of cloud mailbox's on hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@janeannilagan Thanks for the heads up. I confirmed as well and will update the doc. Thanks again!
