### ISSUE TITLE
How an Owner of the group can add/remove members from a Distiri

### ISSUE THREAD

**Issue by ahmetarslan2020** [MicrosoftDocs/microsoft-365-docs#6759]
[Enter feedback here]
I added a regular user to the owners of a distribution list. How owners of a distribution list can add/remove members from a distribution list?  Is this possible without giving access to Exchange admin center? 

Please advice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccf354ec-86a0-ab68-1403-b1cdf8d2d96c
* Version Independent ID: e9b97cc4-4889-58ab-6f93-fc28bf13ba26
* Content: [Add a user or contact to a distribution group - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-user-or-contact-to-distribution-list?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-user-or-contact-to-distribution-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-user-or-contact-to-distribution-list.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ahmetarslan2020 Thank you for your feedback. Yes, Once the user is added as an owner, they can add and remove members to a group.

The owner needs to login to outlook web app (outlook.office365.com) and Select Settings Settings icon > Options > Groups > Distribution groups I own.

In the dialog box, select the group you want to edit. You can search for a group by typing all or part of its name in the search window, and then selecting the search icon search. To clear the search results, select Clear discard.

Select Edit edit.

Make the changes you want.

Select Save to save your changes, or Cancel to leave without saving.


We have not added this to the document as the current document pertains only to M365 Admin. You can find more information on https://support.microsoft.com/en-us/office/distribution-groups-e8ba58a8-fab2-4aaf-8aa1-2a304052d2de

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ahmetarslan2020 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ahmetarslan2020** [comment]
Thank you @msbemba and @yogkumgit! This was super helpful and quick.
