### ISSUE TITLE
Please explain the "Updated warning page"

### ISSUE THREAD

**Issue by ichkoj** [MicrosoftDocs/microsoft-365-docs#676]
What should we do if we get the "Updated warning page" contact microsoft or .. obviously its some sort of error who can fix it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c33b6b0-0fa5-ccdd-91fc-61b047061670
* Version Independent ID: c5d85233-4f4f-3c87-af9f-2921434c4998
* Content: [Office 365 ATP Safe Links warning pages](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-links-warning-pages)
* Content Source: [microsoft-365/security/office-365-security/atp-safe-links-warning-pages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/atp-safe-links-warning-pages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@ichkoj  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@ichkoj - Can you please share a screenshot of your error message so that I can better help you.

Thanks.

**Comment by ichkoj** [comment]
Sorry 
here you go 

![image](https://user-images.githubusercontent.com/44307699/68561698-874f0980-03fb-11ea-9bee-a678f9ca74b3.png)

**Comment by joinimran** [comment]
Thank you for sharing the screenshot. Can you please confirm which website you were trying to access?

I would suggest you contact your IT support team and if you are an IT Support team member please open a support case with the Microsoft support team to address this issue.

@mypil FYI Please.

**Comment by mypil** [comment]
@ichkoj - As suggested by joinimran, you may open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs. Thank you.
