### ISSUE TITLE
Block senders via AntiSpam Policy

### ISSUE THREAD

**Issue by Raj-MCITP** [MicrosoftDocs/microsoft-365-docs#6761]
If the block list reached the 1000 limit on the Anti-Spam policy1, creating the new Anti-Spam policy and add the new block list for the same set of the Policy1 applied users.. will work right?

I have a new Anti-Spam Policy and configured few blocked senders list. Email from One blocked sender reached users mailbox. Searched, Junk email configuration, connection filtering Transport rules etc to find whether that blocked user added as safe sender. but it is not there. but the Blocked senders email delivered in users mailbox. How to find why the new spam policy skipped in identifying the blocked sender?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79bb5c3-e92a-583b-337a-1a038e50f064
* Version Independent ID: 253ccf77-2d74-dd95-2686-a8fcdc424c7a
* Content: [Create blocked sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Raj-MCITP, regarding your first question, you can create another anti-spam policy, but only one anti-spam policy (or any type of of policy) is applied to a user/recipient. After the first user/recipient match in the policy, processing stops for that type of policy (no other policies of that type are applied). For more information, see [Order and precedence of email protection](https://docs.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined).

If the recipient is included in multiple anti-spam policies, the one with the highest priority (lowest priority number) is applied first, and is the only one applied. So, verify that the blocked sender is configured in the first anti-spam policy that applies to the recipient.

**Comment by Raj-MCITP** [comment]
Hi Chris, I understood how this works now. Thank you very much for the detailed explanation.
