### ISSUE TITLE
Duplicate Paragraph

### ISSUE THREAD

**Issue by angusmclean11** [MicrosoftDocs/microsoft-365-docs#6762]
The following paragraph is written twice:

If you are looking for a pre-made simulation, you can use our "Do It Yourself" attack scenarios. These scripts are safe, documented, and easy to use. These scenarios will reflect Defender for Endpoint capabilities and walk you through investigation experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302ee74c-812a-51b2-13e5-7b5daaa411f7
* Version Independent ID: 37fca1db-b257-588f-db65-4d5c6d7fd53f
* Content: [Microsoft Defender for Endpoint evaluation lab](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluation-lab?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/evaluation-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/evaluation-lab.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@angusmclean11 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6821

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @angusmclean11 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
