### ISSUE TITLE
IOC import via csv is 500

### ISSUE THREAD

**Issue by BlakeMsft** [MicrosoftDocs/microsoft-365-docs#6763]
Need to add a Note section that states there is a 500 indicator limit in a csv file when importing.

![image](https://user-images.githubusercontent.com/93606977/139905175-c9530eb1-8a4d-4e5f-b402-922d68c6f5bc.png)

Thanks, Blakemo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03d3a25-4ee0-0c3a-4fde-c6f9ef7a3773
* Version Independent ID: b08640a7-7e66-2653-bf3f-727fbb90709d
* Content: [Manage indicators](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-manage?view=o365-worldwide#import-a-list-of-iocs)
* Content Source: [microsoft-365/security/defender-endpoint/indicator-manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/indicator-manage.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@BlakeMsft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6830

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BlakeMsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
