### ISSUE TITLE
Clarify the Limits for number of mailbox holds and site holds in a single case.

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/microsoft-365-docs#6764]
In regard to the maximum number of Mailboxes in a case hold, can the meaning be clarified further?  Specifically, if an Advanced eDiscovery user has more than 1000 custodians in a case can we understand that an additional case hold can be created in the same case for additional custodians over 1000?  If so, could the wording be changed to say:

"Maximum number of mailboxes in a single case hold. This limit includes the combined total of user mailboxes, and the mailboxes associated with Microsoft 365 Groups, Microsoft Teams, and Yammer Groups.  Additional case holds may be created if more than 1000 mailboxes are required to be on hold in the case."

Otherwise, if the limit is 1000 mailboxes on hold for the case regardless of the number of holds in the case can be wording be changed to say:

"Maximum number of mailboxes in a single case hold. This limit includes the combined total of user mailboxes, and the mailboxes associated with Microsoft 365 Groups, Microsoft Teams, and Yammer Groups (for all holds in the case)."

There is a similar concern with the meaning of the wording for the limits on sites included in a case hold.  

If the meaning is that additional holds can be created within the case then suggest this wording:

"Maximum number of sites in a single case hold. This limit includes the combined total of OneDrive for Business sites, SharePoint sites, and the sites associated with Microsoft 365 Groups, Microsoft Teams, and Yammer Groups. Additional case holds may be created if more than 100 sites are required to be on hold in the case."

Or if the limit is across all holds in the entire case:

"Maximum number of sites in a single case hold. This limit includes the combined total of OneDrive for Business sites, SharePoint sites, and the sites associated with Microsoft 365 Groups, Microsoft Teams, and Yammer Groups (for all holds in the case)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b5b9f-5ee0-cf64-d39a-38f010315b8a
* Version Independent ID: f9bdd1e6-e8e1-eef1-f9ca-b9a2b473dc7d
* Content: [Advanced eDiscovery limits - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/limits-ediscovery20?view=o365-worldwide#hold-limits)
* Content Source: [microsoft-365/compliance/limits-ediscovery20.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/limits-ediscovery20.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. thanks

**Comment by markjjo** [comment]
@exactmike As per my response to #6765 , Advanced eDiscovery will provision a new hold for a case for more than 1000MBX and 100 Site. A footnote describing that has been added to the limits topic (but needs to be added in a few more places, which I will do.)
