### ISSUE TITLE
Hold experience clarification when importing more than 1000 custodians or 100 OneDrive for Business Sites

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/microsoft-365-docs#6765]
In the first Note on this page the Note advises concerning the mailbox limit (1000) and site limit (100) per case hold and that a user can add more than 1000 custodians to a case using the CSV import process.  What it doesn't say is how the import will behave if importing more than 1000 custodians.  Can the note be extended to include this information?   For example, if the first 1000 will be placed on hold the following wording could be added:

"When adding more than 1,000 custodians to a case only the first 1,000 processed by the import will be placed on hold."

Or, alternatively, if the hold will not be placed on any of the custodians imported in a batch of more than 1000 then the following wording could be added: 

"When adding more than 1,000 custodians to a case none of the custodians will automatically be placed on hold."

Or, alternatively if the user experience is different than either of the above scenarios a brief sentence describing what to expect would be helpful.  

Similarly, a short sentence describing what a user should expect in regard to holds on OneDrive for Business sites when importing more than 100 custodians would be helpful.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9cf8117-7084-9cec-d16b-f5c69643e392
* Version Independent ID: e0ac087a-ae84-a311-0b78-bdeea2bbe1b0
* Content: [Import custodians to an Advanced eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/bulk-add-custodians?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/bulk-add-custodians.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/bulk-add-custodians.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. Thanks
