### ISSUE TITLE
SharePoint does not allow you to delete a document with a label set "Retain the content"

### ISSUE THREAD

**Issue by jessica-seiya** [MicrosoftDocs/microsoft-365-docs#677]
Hi Docs Team,

This doc mentions that SPO allows end-user to delete a document with label using "Retain the content"option.
[Section]Content in OneDrive accounts and SharePoint sites:  
[Body]If this is the first change since the policy was applied, the retention policy copies the content to the Preservation Hold library, and then **allows the person to change or delete the original content.** 

But according to our test based on the latest version of O365, when a label is set to "Retain the content", no matter whether "classify content as a "Record"" option is selected or not, SP does not end-user to delete any document tagged with this label. It prevents end-user from taking deletion action directly, instead of allowing to delete after backing up it on Preservation Hold library.

Could you please confirm this? Is the logic changed? Or the document is not accurate?
![cannot delete](https://user-images.githubusercontent.com/44768852/68171067-3e3b2780-ffad-11e9-9f77-4916fe0e35d1.png)

**Comment by mypil** [comment]
@jessica-seiya  - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by LauraWi** [comment]
Hi -- are you referring to this: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#how-a-retention-policy-works-with-content-in-place ?

**Comment by jessica-seiya** [comment]
Hi there,
Yes, i'm referring this doc
https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#how-a-retention-policy-works-with-content-in-place

![2019-11-06_9-04-24](https://user-images.githubusercontent.com/44768852/68259315-76f20400-0074-11ea-826c-1ffc270f306e.png)

Thanks for your quick response.

**Comment by LauraWi** [comment]
Hi @jessica-seiya According to engineering,  **_retention policies_**  do allow the customer to delete the content while it’s preserved behind the scenes. However, **_retention labels_** (sounds like this is what you've applied) do not let the customer delete the item; it actually stays in place even though it might not be a record. There's a User Voice item requesting a change to this behavior (in case you want to up vote): https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/34687639-office-365-labels-allow-deletion-of-documents-wi
