### ISSUE TITLE
Instructions under "Use Group Policy to configure folder or file extension exclusions" lack clarity

### ISSUE THREAD

**Issue by zszabo2000** [MicrosoftDocs/microsoft-365-docs#6772]
- This feedback is regarding the information contained here: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide
- Step 4.d begins with "If you are specifying a file..." and ends with "Enter 0 in the Value column." Since this step begins with a conditional, it is not clear whether '0' is to be entered in the Value column only for file name entries, or for paths as well.
- To improve clarity, I suggest moving the "Enter 0 in the Value column" statement to separate step 4.e and specifying what is to be done/not done for each type of entry. If all entries require a '0' under Value column, then moving the existing statement to a separate step will still improve clarity (see reason above).
- ****This is separate from the above**** Step 6.c has a minor formatting issue: it currently reads (copied verbatim): "...Value name columnEnter 0 in the Value column." It's missing a period and space between the words "column" and "Enter." I suggest changing it to "Value name column. Enter 0 in the Value column." Alternatively, move "Enter 0...." to step 6.d (see above).

Thanks for your consideration.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87906607-83fd-8dc8-facb-89719390f824
* Version Independent ID: 92f3359d-84ac-90c3-33d5-513feffc4173
* Content: [Configure and validate exclusions based on extension, name, or location](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@zszabo2000 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6831

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @zszabo2000 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
