### ISSUE TITLE
Run Tests: DKIM button lead nowhere useful

### ISSUE THREAD

**Issue by toggenation** [MicrosoftDocs/microsoft-365-docs#6774]
There is a button on this document labelled "Run Tests: DKIM" which point to https://aka.ms/diagdkim when I click and log into my tenant It places "Diag: DKIM" in a field under "How can we help?" heading on a pane to the right and then returns "no solutions found"

Button goes no-where useful. Would be better if it lead to an actual DKIM setup testing form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@toggenation Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6827

The correct link is  https://admin.microsoft.com/AdminPortal/?searchSolutions=DKIM#/homepage

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @toggenation Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
