### ISSUE TITLE
Encrypted messages are supported for a Shared Mailbox. What are the limitations?

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/microsoft-365-docs#678]
In this article https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq, it is mentioned that **Yes! Encrypted messages are supported for a Shared Mailbox. Some limitations apply**. So what are the limitations? Those limitations should be mentioned in this article.
Also, I am not able to read encrypted message from a shared mailbox via Outlook desktop client. So is this supported now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Office 365 Message Encryption FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq#feedback)
* Content Source: [microsoft-365/compliance/ome-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@prashant1380  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by na1D** [comment]
Equally interested in an answer to; "I am not able to read encrypted message from a shared mailbox via Outlook desktop client. So is this supported now?". Please can this be clarified. Please can we indicate the positioning of this within the Microsoft 365 RoadMap.

**Comment by KCCross** [comment]
The list is coming from Ignite. Soon as I have clarification on it, I'll publish.

**Comment by joinimran** [comment]
@prashant1380  - Thank you for your message. Can you please share the error screenshot you are getting while open email on outlook desktop client?

Can you please confirm if that is accessible via OWA/Webmail?

Thanks.

**Comment by prashant1380** [comment]
Yes, encrypted email opens in OWA and in Outlook mobile app. But in Outlook desktop client, first it says below when viewed in reading pane.
![image](https://user-images.githubusercontent.com/44681027/68663572-9c38b380-0547-11ea-9793-8b17afd305ae.png)
Then i double click the message to open it, but i get this message
![image](https://user-images.githubusercontent.com/44681027/68663687-cab68e80-0547-11ea-9ebf-c32d3b91c068.png)
Then I click OK and click on Read Message link available in email which tries to open the message in OWA but this gives an error like below
![image](https://user-images.githubusercontent.com/44681027/68663839-018ca480-0548-11ea-8029-df767a1609af.png)

So tried all possible ways in desktop client but email is not readable. If I directly open OWA, I am able to read the message.

**Comment by joinimran** [comment]
@prashant1380 as @KCCross is the primary author of the document and she will update the details regarding this soon. 

In the meantime I would suggest you to you a support case with Microsoft to help you with this.

Thanks.

@mypil FYA Please.

**Comment by nsonew** [comment]
I am having the same problem.  Any updates on the "limitations" or more important, a fix?

**Comment by AHawky** [comment]
We have been battling with OME and shared mailboxes for weeks, as far as we can see nothing has technically changed whatsoever. I suspect Microsoft have decided to change their wording so it didn't sound as negative, but instead has probably made it worse. I suspect the limitations will be what we all know a.k.a you must open the content in OWA. 

We've had to setup a transport rule which relies on us knowing the external recipient team mailbox address and asking our users to trigger encryption using the confidential flag, the result being OMEv2 is removed and the message is encrypted with OMEv1. It means a user can email an external team shared inbox and that inbox receives an OMEv1 message which gives them the OTP option instead. A huge pain to support but it works.

**Comment by mypil** [comment]
@prashant1380 @nsonew - You may try the suggested fix provided by @AHawky or the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by CraigC1976** [comment]
Please advise how this is closed. This constraint is prohibiting us from adopting OME and sadly, it seems there have been no changes to the functionality, simply a change in wording as previously where 'shared mailboxes are not supported' is deemed too negative. I personally would prefer the truth over a politicians answer. To summarise - Shared Mailboxes are NOT supported unless using OWA (which is not feasible).

**Comment by KCCross** [comment]
Update: I am updating the content with a more complete picture of supported scenarios. Yes, Outlook on the web is supported, but it's not the only method for consuming encrypted email or email attachments sent to shared mailboxes. Experiences that are blocked within supported scenarios indicate things that we need to fix. Please do continue to escalate through support and our product team will work diligently to fix them. You can expect the content to be updated much later today.

**Comment by KCCross** [comment]
Content updated to describe supported scenarios.

**Comment by bloodytourists** [comment]
Still not fixed. Still not working for Outlook on Desktop (As it clearly says it should). Is this just being ignored?? Please move this back to open. Thanks
