### ISSUE TITLE
Could you expand on data collected from an end user's privacy perspective.

### ISSUE THREAD

**Issue by mapoitras** [MicrosoftDocs/microsoft-365-docs#6781]
Wondering if you could expand on what data is collected by Defender for endpoint.  For example, when you say "Information collected includes file data (such as file names, sizes, and hashes)"  Does this mean it collects the name of all the files on a user's laptop.  What happens when this is a personal device that is enrolled using Intune and Defender is pushed to this personal device.  What personal information is being collected and what is visible to the employer?  What  about mobile devices vs Pc's?  For Intune, there is good documentation on this:
 https://docs.microsoft.com/en-us/mem/intune/user-help/what-info-can-your-company-see-when-you-enroll-your-device-in-intune    We should provide the same level of details for Defender.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df30eb4f-795f-17a3-2a9a-a68c73a2ba75
* Version Independent ID: d9f2b07e-0deb-2bc9-99e3-bdc4f7752914
* Content: [Microsoft Defender for Endpoint data storage and privacy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/data-storage-privacy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/data-storage-privacy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/data-storage-privacy.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
At this time, the published information is all that we have.
