### ISSUE TITLE
Defender AV randomisation time incorrect

### ISSUE THREAD

**Issue by KieryBUK** [MicrosoftDocs/microsoft-365-docs#6782]
Incorrect value in table "Group Policy settings for scheduling scans"

"In Microsoft Defender Antivirus, randomize the start time of the scan to any interval from 0 to 4 hours."

should read

"In Microsoft Defender Antivirus, randomize the start time of the scan to any interval from 0 to 23 hours."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8195657b-949f-869c-b499-1e4390d39f9a
* Version Independent ID: 8308cec0-964e-a4f2-df7c-bdc1a671a2aa
* Content: [Schedule antivirus scans using Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/schedule-antivirus-scans-group-policy.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@KieryBUK Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6822

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @KieryBUK Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
