### ISSUE TITLE
Cannot find SecOps Dashboard in Defender (as described here)

### ISSUE THREAD

**Issue by mikerobyn** [MicrosoftDocs/microsoft-365-docs#6785]
Is the "Defender Security Center Dashboard" still current? Cannot find in security.microsoft.com Portal.
In my opinion, URLs of the respective Portals described in MS Docs should always be added. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a541e5c3-8a8d-d766-918e-f53091e32294
* Version Independent ID: 44e9ef9e-1355-8ded-f79d-7683fadaec0c
* Content: [Overview of Microsoft Defender Security Center](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/use?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/use.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/use.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@mikerobyn Thank you for your feedback. I was not able to locate the security operations dashboard as well. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6914

Once the author verifies and approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mikerobyn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
