### ISSUE TITLE
Is second 'Windows "temp.edb" files entry correct?

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/microsoft-365-docs#6786]
Hi,

Under the first section, 'Windows "temp.edb" files', the second entry is:

`%ProgramData%\Microsoft\Search\Data\Applications\Windows\*\*.log`

Based on the section heading, this seems incorrect. I can't find any *.log files in this entry. I can't even find 'temp.edb'. However I can find 'Windows.edb'. Which files does Defender exclude?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1664d524-cf0b-a4d4-695a-114f5df1d33e
* Version Independent ID: 31bff983-8c0c-915c-6f88-f5a0a719987c
* Content: [Configure Microsoft Defender Antivirus exclusions on Windows Server](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@ChrisAtMAF Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6836

Once this is approved by the author, you will see the changes live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChrisAtMAF Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
