### ISSUE TITLE
Is '%systemroot%\System32\dfsr.exe' entry correct?

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/microsoft-365-docs#6787]
Hi,

Under the section 'Process exclusions', is the following entry correct?

`%systemroot%\System32\dfsr.exe`

I do not believe this is a Windows system file. Is it referring to `%systemroot%\System32\dfssvc.exe` instead?

Many thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1664d524-cf0b-a4d4-695a-114f5df1d33e
* Version Independent ID: 31bff983-8c0c-915c-6f88-f5a0a719987c
* Content: [Configure Microsoft Defender Antivirus exclusions on Windows Server](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-exclusions-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ChrisAtMAF Thank you for your feedback. I believe the entry is correct.  Dfsr.exe runs the Distributed File System Replication program that replicates data across servers. This is used for synchronizing multiple devices connected over a network. This is a critical Windows component.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ChrisAtMAF Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
