### ISSUE TITLE
Missing steps in Endpoint section

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/microsoft-365-docs#6788]
Between the following two steps, selecting platform and profile type is missing to see Endpoint Protection. 

Go to Devices > Configuration profiles > Create profile.

In the Create a profile flyout, select Endpoint protection from the list of templates, and then select Create.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 673970ca-2f79-a288-978c-ceb4845c5062
* Version Independent ID: 2a58449f-b0d4-bf17-1209-d7b8ec0481b6
* Content: [Turn on network protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-network-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@StuBeck32 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6837

Once the author approves the PR, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@denisebmsft Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @StuBeck32 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
