### ISSUE TITLE
Update this page

### ISSUE THREAD

**Issue by rushifaldu** [MicrosoftDocs/microsoft-365-docs#6789]
Can we please update this page as it is referring to old classic AIP portal and some old UI from MDE settings as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfe25bce-8af4-4326-f256-aa287b4c40df
* Version Independent ID: 3b6435b3-eba4-bb45-99b5-806b52bb4fe3
* Content: [Information protection in Windows overview](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/information-protection-in-windows-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/information-protection-in-windows-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/information-protection-in-windows-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
This feature has been deprecated. Will deprecate page as well.
