### ISSUE TITLE
Retention labels vs Sensitivity labels

### ISSUE THREAD

**Issue by kkazala** [MicrosoftDocs/microsoft-365-docs#679]
The article is focusing on Retention Labels. However, the "DLP policies for your SharePoint Online sites
" paragraph point 15, contains the following: "In the text box, type or paste in one of the following tips, **_depending on if you implemented Azure Information Protection to protect highly confidential files:_**"

AFAIK, AIP's unified labelling works with sensitivity labels, and not retention labels. Also, these labels cannot use the same name. 
What is the meaning of this statement then?

**Comment by mypil** [comment]
@kkazala - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by kkazala** [comment]
Oh, I'm sorry, since I made the comment from the article, I thought it was connected :)

https://docs.microsoft.com/en-us/microsoft-365/compliance/protect-sharepoint-online-files-with-office-365-labels-and-dlp

**Comment by mypil** [comment]
@kkazala  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by kkazala** [comment]
Further looking into the configuration, I see that the encryption _may_ be used with protection settings defined in Sensitivity Labels. I guess this is the connection between retention and sensitivity labels. 

However, the encryption only applies to Exchange, and point 7 of the procedure is: _"In the list of locations, **disable the Exchange email,** OneDrive accounts, and Teams chat and channel messages locations, and then click Next."_

Thank you for looking into it, I'm looking forward reading the revised version :)

**Comment by LauraWi** [comment]
Hi @kkazala Do you still have questions? My understanding of the wording you called out in your initial issue was that people might not need to direct users (in the policy tip text) to manually protect the document if encryption is already being applied

**Comment by kkazala** [comment]
Hi @LauraWi 
I must admit I still find the document confusing, but maybe it's just me :)
Since the reference to the AIP was made in the procedure regarding retention labels, I would expect a connection between these two. 
Instead, I think it's rather a remark that if a user happens to apply both: sensitivity labels and DLP policies based on retention labels to the same content, then they may want to mention it in the policy tip. But there is no automation between these two. Is that correct?

**Comment by LauraWi** [comment]
Hi @kkazala Tagging in @JoeDavies-MSFT, who authored the article above.

**Comment by JoeDavies-MSFT** [comment]
@kkazala  You are correct. There is no connection between the retention labels used by the DLP policy and the AIP/sensitivity labels used to encrypt the file and define access permissions. The policy tip provides instructions for the two cases; 1. if the file is not encrypted with a sensitivity label, encrypt it manually, 2. If the file is encrypted with an AIP/sensitivity label, the encryption and permissions travel with the file.
