### ISSUE TITLE
Third party reporting tools in compressed format

### ISSUE THREAD

**Issue by tanjoht** [MicrosoftDocs/microsoft-365-docs#6793]
Hi I have a third party reporting tool that compresses the EML into a zip file and then forwards the mail. Is there any way to have this show up in the User Submission page for our admins to review? Or will this format not be parsed properly? We aren't looking for MS defender to parse it or do any post processing - just want it to show up under user submission.

**The only requirement is that the original message is included as a .EML or .MSG attachment (not compressed) in the message that's sent to the custom mailbox (don't just forward the original message to the custom mailbox).**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User reported message settings - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@tanjoht Thank you for your feedback. Ideally, this should show up on the user submission page for review. However, this falls under our support request category and we request you to get in touch with Microsoft Support via the need help section on the admin center. 

Post contacting Support, If there are any changes needed in the document do let us know.

Hope this helps!
Thanks
Sri
