### ISSUE TITLE
App Type in MEM Intune

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#6794]
Why wouldn't you use the Microsoft 365 App type in Intune instead of a Win32 app?

There are also no details on the install process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2725620-2c67-d5a7-00d0-4fb297a9c16b
* Version Independent ID: 7585c72b-82c2-48aa-930f-f6111824f4bc
* Content: [Install Microsoft Project or Microsoft Visio on Microsoft Managed Desktop devices - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/get-started/project-visio?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/get-started/project-visio.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/get-started/project-visio.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@AlexBlain does this article need an update?

**Comment by AlexBlain** [comment]
@jaimeo no it does not need an update. MMD built custom Project and Visio Win32 app to improve the reliability of the deployment compared to the default Microsoft 365 app in Intune.

**Comment by danmyhre** [comment]
@AlexBlain This sounds like it really needs to be brought up with the Intune team then. This sort of thing causes a lot of problems. Intune is the modern management platform that MSFT wants us using and that we have invested in. The native deployment in that tool should have been improved instead of building yet another way that office components are installed and managed. That increases complexity, reduces consistency and makes management overall more difficult than in needs to be be.
