### ISSUE TITLE
one question is mentioned twice, with two slightly different answers.

### ISSUE THREAD

**Issue by srinivasa247** [MicrosoftDocs/microsoft-365-docs#6795]
The below FAQ is mentioned twice in the article.
"How long does it take to import a PST file to a mailbox?"

Answer1: 
It depends on the capacity of your network, but it typically takes several hours for each terabyte (TB) of data to be uploaded to the Azure Storage area for your organization. After the PST files are copied to the Azure Storage area, a PST file is imported to a Microsoft 365 mailbox at a rate of at approximately 24 GB per day*. If this rate doesn't meet your needs, you might consider other methods for migrating email data to Office 365. For more information, see Ways to migrate multiple email accounts to Office 365.

* This rate is not guaranteed. Server workload and transient performance issues might decrease this rate.

If different PST files are imported to different target mailboxes, the import process occurs in parallel; in other words, each PST/mailbox pair is imported simultaneously. If multiple PST files are imported to the same mailbox, they will be imported sequentially (one at a time), not simultaneously

+++++

Answer2: 
After the PST files are uploaded to the Azure Storage area, Microsoft 365 analyzes the data in the PST files (in a safe and secure manner) to identify the age of the items and the different message types included in the PST files. When this analysis is complete, you'll have the option to import all the data in the PST files or set filters to that control what data gets imported. After you start the import job, a PST file is imported to a Microsoft 365 mailbox at a rate of at least 24 GB per day. If this rate doesn't meet your needs, you might consider other methods for importing email data to Office 365. For more information, see Ways to migrate multiple email accounts to Office 365.

If different PST files are imported to different target mailboxes, the import process occurs in parallel; in other words, each PST/mailbox pair is imported simultaneously. If multiple PST files are imported to the same mailbox, they will be imported sequentially (one at a time), not simultaneously.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7b7a25a-4cf8-1b51-0c40-6afa334ca537
* Version Independent ID: 0033b96f-ee7b-0e9f-5287-4a5371ce3734
* Content: [FAQ about importing PST files](https://docs.microsoft.com/en-us/microsoft-365/compliance/faqimporting-pst-files-to-office-365?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/faqimporting-pst-files-to-office-365.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/faqimporting-pst-files-to-office-365.yml)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by srinivasa247** [comment]
The phrase "rate of at least 24 GB per day" in the second answer is not realistic. and the Answer1 is more realistic in describing the rate of data transfer

**Comment by srinivasa247** [comment]
The phrase "rate of at least 24 GB per day" in the second answer is not realistic. and the Answer1 is more realistic in describing the rate of data transfer

**Comment by markjjo** [comment]
@srinivasa247 Thanks for the feedback. I will update the drive shipping FAQ (the second answer).
