### ISSUE TITLE
Broken link "Use mail flow rules to filter bulk email"

### ISSUE THREAD

**Issue by CristianDEA** [MicrosoftDocs/microsoft-365-docs#6796]
[Broken link]
In section "Define spam and bulk user experiences" you have broken link in "Use mail flow rules to filter bulk email.". 

https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/use-rules-to-filter-bulk-mail.md

It works fine removing the .md at the end.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce7455d-8c2d-e20a-567e-0873e0a4f533
* Version Independent ID: 4ce7455d-8c2d-e20a-567e-0873e0a4f533
* Content: [Migrate to Microsoft Defender for Office 365 Phase 1: Prepare - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/migrate-to-defender-for-office-365-prepare?view=o365-worldwide#check-your-existing-protection-configuration-in-microsoft-365)
* Content Source: [microsoft-365/security/office-365-security/migrate-to-defender-for-office-365-prepare.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/migrate-to-defender-for-office-365-prepare.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@CristianDEA, fixed. In the future, you too can make fixes like this yourself; no need to open an Issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
