### ISSUE TITLE
Quarantine release request alerts missing

### ISSUE THREAD

**Issue by ckey1** [MicrosoftDocs/microsoft-365-docs#6799]
The section "System alerts for quarantine release requests" refers to alerts that do not exist. Perhaps because this feature is new and still rolling out, but there is not currently a default alert policy called "User requested to release a quarantined message". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf5c5df-c3ab-8448-aef0-af05977db9b9
* Version Independent ID: adade895-f42b-1029-9948-5ddb5b038257
* Content: [Quarantine policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ckey1, just like you said, the feature is new and still rolling out (as indicated at the very top of the topic).

Out of curiosity, do you have quarantine policies, but not the "User requested to release a quarantined message" alert policy? Or do you have neither?

The E5 tenant that I have access to has both.

**Comment by ckey1** [comment]
I have the new quarantine policy just rolled out to us yesterday. But no requested release alert policy. I've been eagerly waiting for this feature ever since it was announced many months ago. 

When I tested it yesterday the "Request Release" button did not send me (Global Administrator) any alert or notification. It did change the message in quarantine to the new status of "Release requested".

Unrelated, is there a way to set user-level permissions? Most of my users don't have access to release but only to request release. But I want a few exceptions such as administrators (including myself!) to still have the "Release" button for one-click release.

**Comment by chrisda** [comment]
> I have the new quarantine policy just rolled out to us yesterday. But no requested release alert policy. I've been eagerly waiting for this feature ever since it was announced many months ago.

I would say give it a couple of days.

> When I tested it yesterday the "Request Release" button did not send me (Global Administrator) any alert or notification. It did change the message in quarantine to the new status of "Release requested".

I know that _end-user spam notifiations_ (now called quarantine notifications) are disabled in the DefaultFullAccessPolicy that's basically used everywhere (except malware and high confidence phishing). It sounds like admin notifications are disabled, too.

> Unrelated, is there a way to set user-level permissions? Most of my users don't have access to release but only to request release. But I want a few exceptions such as administrators (including myself!) to still have the "Release" button for one-click release.

Yes, but you would also need to create a new anti-spam, anti-malware, anti-phishing or whatever policy:

1. Create a new quarantine policy that has the permissions and notification options that you want.
2. Create a new [anti-spam or whatever] policy that a) only applies to the select users that you want, and b) has a higher priority (lower number) that the "regular" policy so it gets applied first.
3. As part of Step 2, use the new quarantine policy from Step 1 in any quarantine actions.

**Comment by ckey1** [comment]
> I know that end-user spam notifiations (now called quarantine notifications) are disabled in the DefaultFullAccessPolicy that's basically used everywhere (except malware and high confidence phishing). It sounds like admin notifications are disabled, too.

Since we had end-user notifications on, we don't use the DefaultFullAccessPolicy but instead use the NotificationEnabledPolicy. I configured the settings I wanted before the notification emails were sent last night so I was able to test. The notification emails were sent, but the Request Release button was not sending admin notifications. I'll give it a few more days.

> Yes, but you would also need to create a new anti-spam, anti-malware, anti-phishing or whatever policy:
>1. Create a new quarantine policy that has the permissions and notification options that you want.
>2. Create a new [anti-spam or whatever] policy that a) only applies to the select users that you want, and b) has a higher priority (lower number) that the "regular" policy so it gets applied first.
>3. As part of Step 2, use the new quarantine policy from Step 1 in any quarantine actions.

Brilliant idea. Thanks!

Last question, is there a way to remove the "Review" button on the notification emails? Every other button is configurable but I don't see anywhere to configure that one.

**Comment by chrisda** [comment]
I don't think so. Review is what takes you into quarantine.

**Comment by ckey1** [comment]
> I don't think so. Review is what takes you into quarantine.

Right, we want everything to be done through admin requests, with end users not accessing the quarantine at all.  That's how we have it set up currently (via a complex combination of redirect mail flow rules and VBA code). Can I submit this as a feature request to the development team?

Thanks again for all your help!

**Comment by Grassyhopper** [comment]
I also do not have the default alert policy.

**Comment by chrisda** [comment]
@Grassyhopper, I would wait a few days. 100% World Wide roll-out of quarantine polices was announced on Friday.

**Comment by ckey1** [comment]
> @Grassyhopper, I would wait a few days. 100% World Wide roll-out of quarantine polices was announced on Friday.
@chrisda can you please confirm that this alert will be available to our Microsoft 365 Business tenant? I hope that this isn't one of the "Enterprise" alerts that require an Enterprise license.

**Comment by chrisda** [comment]
@ckey1, @Grassyhopper, alert policies aren't my area, but the main [Alert policies topic](https://docs.microsoft.com/microsoft-365/compliance/alert-policies) says this near the top:

> ![NOTE]
> Alert policies are available for organizations with a Microsoft 365 Enterprise, Office 365 Enterprise, or Office 365 US Government E1/F1/G1, E3/F3/G3, or E5/G5 subscription.

So, I guess you need Enterprise.

**Comment by Grassyhopper** [comment]
Alright so a Microsoft 365 E3 license should cover that then, hopefully the alert policy shows up soon! Thanks for your help @chrisda

**Comment by ckey1** [comment]
> 
> 
> @ckey1, @Grassyhopper, alert policies aren't my area, but the main [Alert policies topic](https://docs.microsoft.com/microsoft-365/compliance/alert-policies) says this near the top:
> 
> > ![NOTE]
> > Alert policies are available for organizations with a Microsoft 365 Enterprise, Office 365 Enterprise, or Office 365 US Government E1/F1/G1, E3/F3/G3, or E5/G5 subscription.
> 
> So, I guess you need Enterprise.

I saw that too but 365 Business does have access to many of those alerts including the default alert policy. So the documentation is likely not accurate. Since this alert is an integral part of the Quarantine workflow, I very much hope this will be released for Business as well.

I think I will submit feedback on that page asking to clarify which policies and alerts apply to 365 Business tenants.

**Comment by chrisda** [comment]
I'm told that if you see <https://quarantine.microsoft.com/quarantine>, you'll have the "User requested to release a quarantined message" alert policy.

I'm also told that it will take up to ~3 weeks from 10/31 (so ~11/21) for you to see the alert policy.

**Comment by ckey1** [comment]
> 
> 
> I'm told that if you see https://quarantine.microsoft.com/quarantine, you'll have the "User requested to release a quarantined message" alert policy.
> 
> I'm also told that it will take up to ~3 weeks from 10/31 (so ~11/21) for you to see the alert policy.

Sounds good, thanks for the update! I assume the link should say https://**security**.microsoft.com/quarantine

**Comment by chrisda** [comment]
Yes. Sorry, fixed.

**Comment by yogkumgit** [comment]
@ckey1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
