### ISSUE TITLE
The "Action" parameter is required for New-ComplianceSecurityFilter

### ISSUE THREAD

**Issue by PaulRNewell** [MicrosoftDocs/microsoft-365-docs#6802]
Hi there,
Reviewing this article ([Configure permissions filtering for eDiscovery](https://docs.microsoft.com/en-us/microsoft-365/compliance/permissions-filtering-for-content-search)) I see that the instruction and example cmdlets are incomplete. The "Action" parameter is required. I'm recommending that the example cmdlets (and explanations) be updated to include that, for the sake of completeness. 
Here's the New-ComplianceSecurityFilter article for reference: [New-ComplianceSecurityFilter](https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesecurityfilter?view=exchange-ps)
The actions available are Export, Preview, Purge, Search, or All.

Thanks! 

Paul Newell (paulnew)

EDIT: I also opened issue [6803](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/6803) on the _Set up compliance boundaries for eDiscovery investigations_ page.

**Comment by msbemba** [comment]
@PaulRNewell Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6838

Once the author approves the PR, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
closing as per authors' feedback. Thanks
