### ISSUE TITLE
Hi Author,

### ISSUE THREAD

**Issue by NiteshSharma2K19** [MicrosoftDocs/microsoft-365-docs#6807]
Hi Author,

We tested the send as an alias from Office 365 mailboxes and it works like charm but the problem now we are facing is that the Display Name on the recipient's side is only showing email address (alias) in place of Display Name. We have tested with multiple domains and users and OS, it seems to be only happening when we are using OWA, the desktop outlook seems to be working fine.

Please let us know if this is expected behavior 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@NiteshSharma2K19 Thank you for your feedback. This sounds more like a support issue as it works in outlook. We recommend you contact Microsoft support via the need help link on the admin center.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @NiteshSharma2K19 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
