### ISSUE TITLE
Advanced Audit benefits for Stream, Teams, Yammer and Forms

### ISSUE THREAD

**Issue by frndlyy** [MicrosoftDocs/microsoft-365-docs#6813]
Hey folks,
The following services generate audit logs with basic audit. What special events, from these services, will we miss without Advanced Audit? Thanks

> Microsoft Forms
> Microsoft Stream
> Microsoft Teams
> Yammer

https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide#other-advanced-audit-events-in-microsoft-365

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. Thanks

**Comment by markjjo** [comment]
@frndlyy If you click on each of the links in the [Other Advanced Audit events](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide#other-advanced-audit-events-in-microsoft-365) section, they will take you to a list of audited events for those services. Advanced Audit events are identified with an asterisk. Also, these events were highlighted in this Ignite blog last week: https://techcommunity.microsoft.com/t5/security-compliance-and-identity/expanded-audit-events-with-advanced-audit/ba-p/2898982

Hope this helps.

**Comment by frndlyy** [comment]
@markjjo That really helps, thank you. I'd recommend making that clear on the page too. Thanks again.
