### ISSUE TITLE
Mail flow report - noticed that the numbers in th report keeps changing 

### ISSUE THREAD

**Issue by stanley-samuel** [MicrosoftDocs/microsoft-365-docs#6814]
I tried downloading the report for the same period (month of Oct) on different dates in Nov and I happen to get different numbers. Can you help us understand why we see this variance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041a2c32-e0b9-77e9-766c-3b4f5b07ff3a
* Version Independent ID: 597960ea-f734-09c7-eea8-aab24a06c9f8
* Content: [View mail flow reports in the Reports dashboard - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-mail-flow-reports?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-mail-flow-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-mail-flow-reports.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@stanley-samuel, it sounds like your issue would be best handled by opening a support ticket.

**Comment by yogkumgit** [comment]
@stanley-samuel Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
