### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/microsoft-365-docs#6815]
The link under "Use mail flow rules to set the SCL in messages." pointing to https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/use-rules-to-set-scl.md is a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17ce75e-79ba-0acd-066c-a0120a29d65d
* Version Independent ID: 14673b1c-8489-0abc-90a0-42f35d516424
* Content: [Configure the delivery of third-party phishing simulations to users and unfiltered messages to SecOps mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-advanced-delivery?view=o365-worldwide&data=04%7C01%7C%7Ccd230c8e695045881d0008d93bb177dd%7C3cfadf87221245b5b7c757c1e0f21997%7C0%7C0%7C637606455672812570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sHT2HaGUIchv9%20khaFFHRbxdBsj8LMJS4XWofRs%20NvM%3D&reserved=0#additional-scenarios-that-require-filtering-bypass)
* Content Source: [microsoft-365/security/office-365-security/configure-advanced-delivery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-advanced-delivery.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mattdreher, it was that extra '.md' at the end. I removed it.

Thanks for the feedback.

Closing
