### ISSUE TITLE
eDiscovery subscription comparison has incorrect minimum subscription requirements for Content search & Core eDiscovery

### ISSUE THREAD

**Issue by davebirr** [MicrosoftDocs/microsoft-365-docs#6816]
https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide#ediscovery-subscription-comparison

Microsoft 365 Business Premium also includes Content Search & Core eDiscovery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562b6b1d-b0fd-0d65-9db8-37df67bd7035
* Version Independent ID: 92c4403b-0d6b-88aa-74f4-ba3b7640ad00
* Content: [Microsoft 365 eDiscovery solutions - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@yogkumgit Thank you very much for the contribution and updating the documentation with PR. @davebirr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
