### ISSUE TITLE
Finish the sentence

### ISSUE THREAD

**Issue by expta** [MicrosoftDocs/microsoft-365-docs#6817]
we created the policy named NotificationEnabledPolicy to use in place of DefaultFullAccessPolicy for those organizations that needed it (organizations where end-user spam notifications were turned **on**).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf5c5df-c3ab-8448-aef0-af05977db9b9
* Version Independent ID: adade895-f42b-1029-9948-5ddb5b038257
* Content: [Quarantine policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/office-365-security/quarantine-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@expta, fixed. In the future, your too can make updates like this directly to topics; no need to open a GitHub issue first. For instructions, go [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
