### ISSUE TITLE
Windows Defender Event ID 1127 is not documented

### ISSUE THREAD

**Issue by gxtaillon** [MicrosoftDocs/microsoft-365-docs#6818]
Event ID 1127 is not documented.

This seems to correspond to "Protected memory access blocked" in Protection History.

FYI - Windows Defender is triggering itself with this repeatedly (sometimes 5 times per hour).

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Windows Defender" Guid="{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}" /> 
  <EventID>1127</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2021-11-05T21:31:02.2198731Z" /> 
  <EventRecordID>2844</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="8636" ThreadID="6188" /> 
  <Channel>Microsoft-Windows-Windows Defender/Operational</Channel> 
  <Computer>DESKTOP-NS4AHIN</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="Product Name">Microsoft Defender Antivirus</Data> 
  <Data Name="Product Version">4.18.2110.6</Data> 
  <Data Name="Unused" /> 
  <Data Name="ID" /> 
  <Data Name="Detection Time">2021-11-05T21:31:02.219Z</Data> 
  <Data Name="User">NT AUTHORITY\SYSTEM</Data> 
  <Data Name="Path">\Device\HarddiskVolumeShadowCopy3</Data> 
  <Data Name="Process Name">C:\Windows\System32\svchost.exe</Data> 
  <Data Name="Security intelligence Version">1.353.493.0</Data> 
  <Data Name="Engine Version">1.1.18700.4</Data> 
  </EventData>
  </Event>

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102c5c34-0c04-cc14-8e9c-74ff42e1fdc2
* Version Independent ID: 6a06016e-6ac1-ab00-5a33-1d1226e2e45d
* Content: [Microsoft Defender Antivirus event IDs and error codes](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
The information about Event ID 1127 is now included in the article. Thank you for the feedback!
