### ISSUE TITLE
Cannot use Headers to designate an Internal Sender as a Safe Sender

### ISSUE THREAD

**Issue by jaredburnett** [MicrosoftDocs/microsoft-365-docs#6819]
Hey Team,

Can we get the article update to denote that internal senders cannot be made Safe Senders via message flow/headers due to security concerns? 
Obviously PowerShell would still work, but I had a Premier Support ticket go long due to this lack of information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide#recommended-use-mail-flow-rules)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Removing support links (this repo is public).

**Comment by chrisda** [comment]
@jaredburnett, OK. Fixed.

Thanks for the feedback.

Closing
