### ISSUE TITLE
Upgrade from Teams Exploratory Trial to Microsoft 365 Business Standard...

### ISSUE THREAD

**Issue by Yuelin-Liang** [MicrosoftDocs/microsoft-365-docs#6823]
Hi,
I am currently on a one year trial of Teams Exploratory. With this trial version I have stored data on OneDrive, set up domain and customised email address, and created Teams channels etc.
I will buy a product key of Microsoft 365 Business Standard from a Microsoft Partner Company. Given that I have already set up the Trial version, how should I activate the product key? Will I lose the set up and data? How should I upgrade without re-configuring everything?
Thanks for any advice.

**Comment by msbemba** [comment]
@Yuelin-Liang Thank you for your feedback. Ideally, when you replace a trail license with a Purchased one, the services are not impacted. However, I'd recommend you to contact Microsoft via the need help section to be sure that the services in the trial are covered in the new license that you are purchasing.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Yuelin-Liang Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
