### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by Fysiks97** [MicrosoftDocs/microsoft-365-docs#6828]
Hi, 

I was redirected to this page via [Hybrid Identity Required Ports and Protocols](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-ports). I have a customer who requires URLs and IPs for whitelisting on their firewall. However, they requested a description of  what each URL/IP is used for, which the current document is missing. Also, this document does not clearly specify which rule is for which service. In this case, we are looking for Azure AD Connect which is not specified in the document, hence it is confusing for us on which rule applies to us. Please update this, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. Currently, we do not have descriptions of the purpose of each endpoint. The endpoints data in this article is autogenerated by the Office 365 endpoints web service and originates from the engineering team for each service area. It is often not possible to separate IP addresses by specific purpose or type of traffic (other than ports, which are noted). Future improvements to the web service may include more granular details.

With respect to AAD Connect, the Office 365 endpoints web service is only designed to include endpoints that are specific to Office 365 services and features. The AAD Connect service is not part of Office 365 and is therefore outside the scope of endpoints we can include in the database. -Kelley
