### ISSUE TITLE
Quality Updates in the table - are we using 3 days not 7 days now?

### ISSUE THREAD

**Issue by rhelanor** [MicrosoftDocs/microsoft-365-docs#6829]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63d4e59b-1326-1d3f-a3b0-40e3b9f5f7af
* Version Independent ID: 31fad9a8-65f2-cd7d-42f0-2252bb62d7ed
* Content: [How updates are handled in Microsoft Managed Desktop - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/updates?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/service-description/updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/updates.md)
* Service: **m365-md**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@sh783 can you review and update if needed?

**Comment by rhelanor** [comment]
I have checked and was seeing 0-0-0-3 referred to in a customer presentation - which I'm told is awaiting updating by marketing and should now reflect the 0-0-0-7...

Apologies for the confusion
