### ISSUE TITLE
Incorrect link on page

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#683]
On the page/section https://docs.microsoft.com/en-us/microsoft-365/compliance/configure-supervision-policies#create-a-new-role-group

The link **Permissions in the Compliance Center** goes to the incorrect page. 

The correct link: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 790dd931-fe1f-86c3-ea6d-1d298c5bb012
* Version Independent ID: 74279ba8-4542-7297-4697-2df34f1540d5
* Content: [Configure supervision policies for Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/configure-supervision-policies)
* Content Source: [microsoft-365/compliance/configure-supervision-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/configure-supervision-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@EricaToelle  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@EricaToelle - PR #694 has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
