### ISSUE TITLE
Broken link to German M365 sign-in portal 

### ISSUE THREAD

**Issue by AlexJerabek** [MicrosoftDocs/microsoft-365-docs#6834]
Under the [General information](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/learn-about-office-365-germany?view=o365-germany#general-information) section of the article, the link given for the sign-in portal (https://portal.office.de) is not working. It links to an unsecure page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b7d0ac-caf6-82bc-ee11-129695bdc028
* Version Independent ID: 2c1e2edb-7a65-770d-2f9d-f561fae87145
* Content: [Learn about Office 365 Germany - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/learn-about-office-365-germany?redirectSourcePath=%252farticle%252f8a5a4bbc-667a-4cac-8769-d8ac9015db4c&view=o365-germany&viewFallbackFrom=o365-worldwide)
* Content Source: [microsoft-365/admin/admin-overview/learn-about-office-365-germany.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/learn-about-office-365-germany.md)
* Service: **o365-administration**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by msbemba** [comment]
@AlexJerabek Thank you for your feedback. I'm able to repro the issue too. 

@LoreenLa Could you please confirm if I can change this link to portal.office.com or Is this a known bug with portal.office.de?

CC: @yogkumgit 

Thanks
Sri

**Comment by yogkumgit** [comment]
@TinaMcN Please help us in resolving this issue. Thanks

**Comment by TinaMcN** [comment]
@yogkumgit this is an issue on the English page. @LoreenLa let me know if you need help finding someone knowledgeable about  Office 365 Germany and I can see if I can find someone in the German subsidiary.

**Comment by yogkumgit** [comment]
@LoreenLa Kindly help. Thanks

**Comment by yogkumgit** [comment]
@LoreenLa Gentle reminder

**Comment by LoreenLa** [comment]
Just remove the entire row with the sign-in link, please. As an FYI - I have not owned this article for several years.

**Comment by msbemba** [comment]
@LoreenLa  I have made the changes on PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6982

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AlexJerabek Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
