### ISSUE TITLE
ZAP doesn't always move messages to the Junk mail folder

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/microsoft-365-docs#684]
The sections in this doc that discuss Phish Zap and Spam Zap functionality both state that "if the policy [Phish | Spam] action is set to take an action on a mail (Redirect, Delete, Quarantine, Move to Junk), then Zap will move the message to the Junk mail folder of the user's inbox."

The way this is written, this doc is saying a Phish/Spam message will *always* be moved to the Junk Email folder, even if the defined action is something different (e.g. like quarantine).

This is not accurate and should be updated to reflect messages will be moved to the Junk Email folder if the assigned policy action specifies to do so (or just indicate that the defined action will be taken).

It's still valid to point out how these two policy preferences behave differently, depending on whether the message is read/unread.

Thanks,
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge - protection against spam and malware](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge#phish-zap)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@mrkeiths - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mrkeiths** [comment]
Hello Joyce,

 

Thank you for reaching out.  I’m in touch with the product group and have been informed the documentation is accurate and that there are planned changes that will result in documentation being updated soon anyway.

 

At this point, I think it is safe to close this inquiry.

 

Thank you,

Keith

**Comment by mypil** [comment]
@mrkeiths - Closing this issue now. Thank you for this update.
