### ISSUE TITLE
link below "Next Steps" at bottom of page incorrect

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/microsoft-365-docs#6840]
link below "Next Steps" at bottom of page incorrect

Currently shows:
Proceed to Phase 1: Setup.

Should read:
Proceed to Phase 1: Prepare

NOTE - link works correctly and proceed to 1:Prepare

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71fea5e3-4515-b0a0-2db7-94f320343509
* Version Independent ID: 71fea5e3-4515-b0a0-2db7-94f320343509
* Content: [Migrate from a third-party protection service to Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/migrate-to-defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/migrate-to-defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/migrate-to-defender-for-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dcaddick, fixed.

Thanks for the feedback.

Closing
