### ISSUE TITLE
Comparing Secure Score with other organizations

### ISSUE THREAD

**Issue by ShawnHag** [MicrosoftDocs/microsoft-365-docs#6841]
Hi, I have a quick question about the comparison feature of secure score.

As written in Docs, I rememeber being able to customize the comparison details by industry, company size, and so on.

However, the "Manage comparisons" tab dissapeared in my environment.
Is this just for my environment? Or is it going under some maintanece, updates, etc?

Heres a screenshot of my envrionment ↓
![image](https://user-images.githubusercontent.com/93202918/140866108-8bca0f3e-cdfb-4435-b2ab-afa695aeb642.png)
As you can see, the tab is missing, and I am unable to customize my comparison.

Thank you in advance

Best Regards, 
Shawn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e063499a-77c4-6ea7-7c53-ccdad55c10ca
* Version Independent ID: b06de493-e6af-12a6-a877-92e7a59bd016
* Content: [Track your Microsoft Secure Score history and meet goals](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score-history-metrics-trends?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-secure-score-history-metrics-trends.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-secure-score-history-metrics-trends.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ShawnHag Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6916 as the manage comparisons are no longer available to customize. 

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ShawnHag Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dferraiolo** [comment]
Hi @msbemba, can you share the reason why this feature (manage comparisons, customized to select industry to compare etc.) has been removed? Who can I ask to know this? I have a customer asking this question. Thank you

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@dferraiolo Thank you for your feedback. Of course, you can Provide your feedback or ask a question on our feedback portal -https://feedbackportal.microsoft.com

The concerned team will be able to provide you with more details on why this feature was removed.

Thanks
Sri
