### ISSUE TITLE
Conflicting information in documentation

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#6844]
In this article you state: 

> On the **Bulk email threshold & spam properties** page that appears, configure the following settings:
>
> - **Bulk email threshold**: Specifies the bulk complaint level (BCL) of a message that triggers the specified action for the **Bulk** spam filtering verdict that you configure on the next page (greater than the specified value, not greater than or equal to). A higher value indicates the message is less desirable (more likely to resemble spam). The default value is 7. For more information, see [Bulk complaint level (BCL) in EOP](https://docs.microsoft.com/microsoft-365/security/office-365-security/bulk-complaint-level-values.md) and [What's the difference between junk email and bulk email?](https://docs.microsoft.com/microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md).
>
> By default, the PowerShell only setting _MarkAsSpamBulkMail_ is `On` in anti-spam policies. This setting dramatically affects the results of a **Bulk** filtering verdict:
>
> - **_MarkAsSpamBulkMail_ is On**: A BCL that's greater than the threshold is converted to an SCL 6 that corresponds to a filtering verdict of **Spam**, and the action for the **Bulk** filtering verdict is taken on the message.
> - **_MarkAsSpamBulkMail_ is Off**: The message is stamped with the BCL, but _no action_ is taken for a **Bulk** filtering verdict. In effect, the BCL threshold and **Bulk** filtering verdict action are irrelevant.

But, in this artiicle: 

<https://docs.microsoft.com/microsoft-365/security/office-365-security/anti-spam-message-headers>

It states:

> The message was identified as bulk email by spam filtering and the bulk complaint level (BCL) threshold. When the MarkAsSpamBulkMail parameter is On (it's on by default), a bulk email message is marked as high confidence spam (SCL 9). For more information, see Configure anti-spam policies.

Need clarity on MarkAsSpamBulkMail whether it sets SCL to 6 or 9.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed2861d-860e-5d27-9259-fb9db2187f4b
* Version Independent ID: 09ef5622-3a7e-30f9-00f9-4c5578f8e1ca
* Content: [Configure spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dkotars, based on a detailed email thread I found from last year (which resulted in the content you quoted in the anti-spam policies topic), I believe SCL=6 is correct. I changed the headers topic to match (SCL=6).

Thanks for the feedback.

Closing
