### ISSUE TITLE
New version yet?

### ISSUE THREAD

**Issue by virtualcomputerguy** [MicrosoftDocs/microsoft-365-docs#6845]
The old version expired on the 6th of November. Is there an update for the next release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows 10 and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by virtualcomputerguy** [comment]
Please use a broad bandwidth to download this content to enhance your downloading experience. Lab expires November 6, 2021. A new version will be published prior to expiration.

**Comment by msbemba** [comment]
@virtualcomputerguy Thank you for your feedback. I'm currently checking with the team in the backend to update the new version.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@virtualcomputerguy The kit has been updated. Lab expires on February 16, 2022. A new version will be published prior to expiration.

@yogkumgit  This issue can be closed.

Thanks
Sri

**Comment by virtualcomputerguy** [comment]
Awesome 👍

Thanks,
Matt Sample
________________________________

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @virtualcomputerguy  If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
