### ISSUE TITLE
Need to validate statements on fallback order

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#6848]
there is conflicting info on line about fallback order.  This article says we go immediately to the next in fallback order if one source is not available.  Other docs and my understanding is that we only go to hte next in the list when signatures are considered "out of date."
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-outdated-endpoints-microsoft-defender-antivirus?view=o365-worldwide#set-the-number-of-days-before-protection-is-reported-as-out-of-date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f9be21b-f9c7-5022-4389-5f860847ffb3
* Version Independent ID: 42a36c44-baf3-419d-b4ff-0a205f2ac8f8
* Content: [Manage how and where Microsoft Defender Antivirus receives updates](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-protection-updates-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-protection-updates-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-protection-updates-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Greetings! We are working on this. Expect an update soon.

**Comment by denisebmsft** [comment]
Thank you @jrhi for the feedback. I have updated the article, and the changes will be live later today. Please let me know if there are any other issues.
