### ISSUE TITLE
Missing list of Bluetooth Apps

### ISSUE THREAD

**Issue by gkneale** [MicrosoftDocs/microsoft-365-docs#6849]
The tooltips within "Add or edit unallowed Bluetooth apps" refer to this page, citing "When turned on, recommended Bluetooth apps will be included in the list by default.
Learn which apps are included​.". However, this page seems to be missing the list of apps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76da4eda-4ccf-ff34-6a48-d9c5553c2ed6
* Version Independent ID: 7e887aff-1b85-1651-2bff-63425c54ae63
* Content: [Using  Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-using?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-using.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@gkneale Thank you for your feedback. I'm trying to get more information from the team to update the document. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@btbennett Email sent on 11-16-2021

**Comment by yogkumgit** [comment]
@btbennett Gentle reminder

**Comment by chrfox** [comment]
closing this per guidance from product team
