### ISSUE TITLE
option to use Email alias on new receiver

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/microsoft-365-docs#6850]
Does the option with FW means we need to keep paying license for the former employee? 

Can we add an email alias for the new target recipient? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2bdb60-b559-ddf3-0eec-be4943fc94fd
* Version Independent ID: 5b176c0f-6c35-a187-2ccb-53a23e154978
* Content: [Step 3 - Forward a former employee's email to another employee or convert to a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-3?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-3.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@TiloGit Thank you for your feedback.

You don't need to pay for the license as the mailbox would already be converted to a shared mailbox before you set up email forwarding (if you are following the article). You can also add it is an alias to the target recipient, however not when the account is active as a user or a shared mailbox. The email address or alias needs to be unique.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @TiloGit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
