### ISSUE TITLE
Can MECM/SCCM manage Defender AV on Server 2012R2 after new unified solution install?

### ISSUE THREAD

**Issue by CAT-hs** [MicrosoftDocs/microsoft-365-docs#6851]
Apologies if this is not the best place for this, but it is my first time providing feedback on any documentation and I'm not sure if this is the best place for this, but we are having difficulty and there didn't seem to be a better way to provide feedback on the documentation and get answers. 

We have Server 2012R2 systems managed with SCEP, used the helper script with the new modern unified solution installer to set up Defender AV and Defender for Endpoint. As expected with the script SCEP was removed, and Defender for Endpoint installed and onboarded. I see event log ID 7045 entries for 3 Defender services (including AV) installed and they show up in Services control panel. Additionally the Powershell get-mpcomputerstatus and get-mppreference are working as expected, so it appears everything worked. 

However, during the next SCCM maintenance window SCEP was reinstalled according to Client Settings/Endpoit Protection to enable management of the endpoint protection settings, but it replaced the Defender AV with SCEP instead of simply taking over management of Defender's configuration as occurs on our uplevel clients. 

So, is it not possible to manage Defender's AV settings using SCCM with the new modern unified solution?

For now I have set my Endpoint Protection Client Settings in SCCM to 'Manage endpoint protection client=yes' and 'install endpoint protection client=no' but the documentation isn't clear on how this configuration will behave so we are waiting to see what this does when the system processes everything and hits a maintenance window. With this configuration will SCCM even be able to manage endpoint protection settings for uplevel clients with Defender?

At the very least the documentation for the new modern unified solution for Defender for Endpoint on 2012R2 should explain if it is not currently possible to manage Defender AV's configuration with SCCM, and link to the alternatives for this configuration, or if it is expected to work but doesn't need the 'install endpoint protection client on client computers' it would help to state this to prevent SCEP overwriting Defender AV. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#new-functionality-in-the-modern-unified-solution-for-windows-server-2012-r2-and-2016-preview)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by CAT-hs** [comment]
Update: The first time we installed the defender package we did not reboot after it completed, and SCEP reinstalled during the maintenance window that evening and broke Defender AV. We set the "install endpoint protection client" back to Yes, uninstalled everything from that first system, then went through the install process for Defender again and rebooted, and during the maintenance window SCEP install ran again, adding the Microsoft Antimalware Service this time without touching the Microsoft Defender Antivirus Service. 

Unfortunately now SCEP is just running at the same time as Defender AV and Defender isn't getting policies. Both instances of MsMpEng.exe are running (C:\Program Files\Windows Defender\MsMpEng.exe and C:\Program Files\Microsoft Security Client\MsMpEng.exe). The system is reporting in SCCM that it applied our custom policy, confirmed in EndpointProtectionAgent.log and SCEP's about screen, but get-mppreference returns values that don't match our custom policy. Running both AV engines is definitely less than ideal.

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by CAT-hs** [comment]
I just found the note in https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/server-migration?view=o365-worldwide which indicates that Configuration Manager 2111 is recommended with 2107 being the minimum required for using the Endpoint Protection node for configuration. We are currently on 2010 with an internal Change Request submitted to upgrade as soon as possible. Would it be possible to confirm this behavior is one of the things to expect with older Configuration Manager version? 

Also, I recommend including a similar note in the linked document/section below as the page below is logically the first place someone will arrive when looking to onboard the downlevel servers. There is a link to the above page, but it is in the sentence "If you have previously onboarded your servers using MMA..." which many may not have done, so they will not see the Config Mgr version note or the other useful content in the above linked page.
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#new-functionality-in-the-modern-unified-solution-for-windows-server-2012-r2-and-2016-preview

**Comment by yogkumgit** [comment]
@mjcaparas Please reply. Thanks

**Comment by CAT-hs** [comment]
Another update: we did upgrade MECM to 2107 and now 2012r2 systems appear to be managed without issue, so the above mentioned documentation clarification might be the only update required, pending response from knowledgeable parties.

**Comment by elcov** [comment]
@mkjoung I'm experiencing a similar issue with our deployment and that led me here, but we're still on 2103. The first "note" in this link [https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection](url) mentions "Configuration Manager 2107 _with the update rollup_" so maybe install that too if you haven't already. Good luck

**Comment by elcov** [comment]
As an update to our own rollout, we successfully migrated to SCCM 2111 and noticed that the antimalware settings were still not immediately managed on our unified DFE clients as well. Once the SCCM agents on the affected machines started getting updated to the newer version, however, the settings applied with no further intervention.

**Comment by mjcaparas** [comment]
MECM version 2111 with the hotfix rollup is required to manage the unified solution. Version 2207 and later have automated deployment support. 
For other issues, please contact support.
