### ISSUE TITLE
Includes instructions for retired EAC

### ISSUE THREAD

**Issue by faboo** [MicrosoftDocs/microsoft-365-docs#6854]
It looks like the portal instructions are for the old Exchange Admin Center, which has a banner stating "This feature has been retired." The retention policy creation process in the new Compliance Manager is quite different and it's not clear if/how policies made in the retired product carry over to the current one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e247ee-12d5-add4-756c-b8a8d4ebb7a3
* Version Independent ID: 889ce47a-58f5-7bc1-2343-64dcd4bdac2a
* Content: [Increase the Recoverable Items quota for mailboxes on hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/increase-the-recoverable-quota-for-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@faboo First, if you're having issues with the procedures in this topic, please contact Microsoft Support. That said, I'm pretty sure the classic version of the EAC is still available to use to implement the solution outlined in this topic. The underlying PowerShell cmdlets are still available. So suggest you continue to use the classic EAC. I can't explain why the new EAC doesn't let you manage Exchange/MRM retention policies. Also, I'm not sure what "Compliance Manager" in your original message refers to or how it's related to the solution for increasing Recoverable Items quota. I do know that the two key parts of this solution (creating an Exchange/MRM retention tag for the Recoverable Items folder and moving items to the archive mailbox) are not supported by M365 retention policies that are managed in the M365 compliance center. Those limits are described [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#use-retention-policies-and-retention-labels-instead-of-older-features). So until you can do those two things with M365 retention policies, the solution outlined in this topic is the supported method of increasing recoverable item quota.

I hope this helps.
