### ISSUE TITLE
can not  see office 2021 ltsc product key referring official documents

### ISSUE THREAD

**Issue by iovex** [MicrosoftDocs/microsoft-365-docs#6855]
https://docs.microsoft.com/en-us/microsoft-365/admin/setup/download-software-licenses-csp?view=o365-worldwide

I can not see my office 2021 LTSC product key which is from CSP program referring to this document ,why ?

**Comment by msbemba** [comment]
@iovex  Thank you for your feedback. Office LTSC 2021 is available only via volume licensing, so it is not included in this article. We have an end to end deployment guide for LTSC 2021 which can be found here -  https://docs.microsoft.com/en-us/deployoffice/ltsc2021/overview

It includes deployment, update, and activation.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @iovex Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
