### ISSUE TITLE
Error in text

### ISSUE THREAD

**Issue by davidkench** [MicrosoftDocs/microsoft-365-docs#6857]
The section

Notify recipients when messages are quarantined as malware:

If you select this option, the message is quarantined with no notification to the intended recipients.

If you don't select this option, the message is quarantined. A copy of the message is delivered to the recipients, but all attachments (not just the detected ones) are replaced with a single text file named Malware Alert Text.txt.

should be vice versa.  ie.:

If you don't select this option, the message is quarantined with no notification to the intended recipients.

If you select this option, the message is quarantined. A copy of the message is delivered to the recipients, but all attachments (not just the detected ones) are replaced with a single text file named Malware Alert Text.txt.

Also, can it be clarified if the Quarantine Policy would override this setting?

Thanks and kind regards,

David Kench
M365 Engineer | Intelligent Workspace

501 Ann Street, Fortitude Valley, QLD 4006, Australia
Email: david.kench@datacom.com.au | Mobile: +61 435 160 796
www.datacom.com.au

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db041b73-f7c9-db6c-070b-a7c974de640c
* Version Independent ID: dffb7045-3ba8-a014-d1be-462ca1d609b5
* Content: [Configure anti-malware policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-anti-malware-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-anti-malware-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-anti-malware-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@davidkench, thanks for the correction. The issue that's a bit strange is the "notification" isn't really a notification in the traditional sense (for example, a separate email message that states, "you received a message that has been quarantined"). Instead, it's the delivery of a copy of original message, but with all attachments stripped out and replaced by a notification text file.

The quarantine policy that's assigned would determine whether the traditional, separate quarantine notification (end-user spam notification) is sent or not, and I don't think they conflict with each other, but I'll confirm that. I rewrote the description to say this:

>   - **Notify recipients when messages are quarantined as malware**:
>     - If you select this option, the message is quarantined. A copy of the message is delivered to the recipients, but *all* attachments (not just malware attachments) are replaced with a single text file named **Malware Alert Text.txt**.
>
>       The default text in the replacement text file is described in [Anti-malware policies](https://docs.microsoft.com/microsoft-365/security/office-365-security/anti-malware-protection#anti-malware-policies). To use custom text instead, enter the text in the **Custom notification text to recipient** box.
>
>     - If you don't select this option, the message is silently quarantined.
>
>     > [!NOTE]
>     > Regardless of the option that you select, the quarantine policy determines whether recipients receive quarantine notifications (email notifications for messages that were quarantined as malware).

**Comment by davidkench** [comment]
Hi Chris,

Thanks very much.  That's very helpful to understand that they are different and separate notifications.

Kind regards,

David Kench
M365 Engineer | Intelligent Workspace

501 Ann Street, Fortitude Valley, QLD 4006, Australia
Email: ***@***.******@***.***> | Mobile: +61 435 160 796
www.datacom.com.au<http://www.datacom.com.au/>

***@***.***

**Comment by yogkumgit** [comment]
@davidkench Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by chrisda** [comment]
And just to be clear, my updated description is accurate as of now. It's always possible that the current malware "notification" method of delivering the message with stripped out attachments will be removed in favor of quarantine policy notifications only. If/when that happens, we'll update the documentation again (that would involve lots of settings removal in the UI).
