### ISSUE TITLE
Dates on page are outdated - 2019-2020 - changes required

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/microsoft-365-docs#6858]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87cb379c-82ae-0a6e-8dd5-0c41b09364ab
* Version Independent ID: a15c3919-e63e-f0dc-bd6b-45f311b387b5
* Content: [How to request your data move - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/request-your-data-move?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/request-your-data-move.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/request-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by yogkumgit** [comment]
@andybergen Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Andy updated this on Nov 16. Issue resolved.
