### ISSUE TITLE
AH Query for SmartScreen is incorrect

### ISSUE THREAD

**Issue by Princetimber** [MicrosoftDocs/microsoft-365-docs#6859]
I noticed that the AH Query is incorrect on the last line

DeviceEvents 
| where ActionType == "SmartScreenUrlWarning"
| extend ParsedFields=parse_json(AdditionalFields)
| project DeviceName, ActionType, Timestamp, RemoteUrl, InitiatingProcessFileName, Experience=tostring(ParsedFields.Experience)
| where Experience == "CustomPolicy"
---

The correct parameter should be | where Experience == "CustomBlockList"
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 209bd885-0ac5-2652-8c04-a1f6e0b4eeea
* Version Independent ID: bed8f47f-4b29-95b0-347e-811b57c7feb7
* Content: [Web protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-protection-overview?view=o365-worldwide#advanced-hunting-for-web-protection)
* Content Source: [microsoft-365/security/defender-endpoint/web-protection-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-protection-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Princetimber Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6890

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Princetimber Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
