### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by over2under3** [MicrosoftDocs/microsoft-365-docs#6866]
[Enter feedback here]

Hello...

The link for download ".NET Framework 3.5.1 (KB315418)" shows a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3985e3b-6df1-892c-be7c-8b1f079b4053
* Version Independent ID: 61fee405-9ccd-cf53-4aa1-4c5e98f09cf7
* Content: [Onboard previous versions of Windows on Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-downlevel?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-downlevel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-downlevel.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@over2under3 Thank you for your feedback. The links are restored now, Please check again and let us know if you are still receiving a 404 error.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @over2under3 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
