### ISSUE TITLE
Old Product name used in video image.

### ISSUE THREAD

**Issue by quekmc** [MicrosoftDocs/microsoft-365-docs#6867]
This video 
![image](https://user-images.githubusercontent.com/89065520/141287104-90f9fa8b-81bc-403a-ac97-759f92f063c0.png)
is still referring to the old product name in the slide still.  Check out 36 to 43 second of the video, the image still says Microsoft Defender Advanced Threat Protection.  It should be Microsoft Defender for Endpoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8690a332-f672-8db8-1552-5ee16e78746f
* Version Independent ID: 3df5b553-4e29-da25-c0e4-10686c5fed20
* Content: [Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Will add in the radar for future updates.
