### ISSUE TITLE
The documentation and procedure to Onboard windows server 2016 are not correct or up to date.

### ISSUE THREAD

**Issue by joaogpinto** [MicrosoftDocs/microsoft-365-docs#6868]
Hi 
I'm João Pinto a Support Engineer from Microsoft Defender for Endpoint team and spotted some incorrect information.
The documentation and procedure to Onboard windows server 2016 are not correct or up to date.
It says to download the installation package, but for this type o OS the onboarding is by setting the OMS on the MMA by the Workspace ID adn Key, this is confusing the customer because on the Microsoft 365 Defender portal there is no package to download as you can see in attachement.
Please review this information and correct it accordingly.

Thank you in advance for the support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide&ns-enrollment-id=1k0wiwnq8qrkwd#windows-server-2012-r2-and-windows-server-2016)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara*
![Windows Server 2016 Onboarding documentation](https://user-images.githubusercontent.com/94046512/141294421-10120270-b32d-4c86-b96d-f47e7c51f0d3.jpg)
![Onboarding server 2016 server Step on M365D](https://user-images.githubusercontent.com/94046512/141295054-7fa74ea9-60f8-44db-a596-12a0850201dc.jpg)

*

**Comment by msbemba** [comment]
@joaogpinto Thank you for your feedback. I could locate the download installation package when selecting Server 2012 R2 and 2016.

![image](https://user-images.githubusercontent.com/45987684/141675233-71947e8b-820b-4b34-aa42-5e0d6a7b2780.png)

Let me know if you see that option.

Thanks
Sri

**Comment by joaogpinto** [comment]
Hi @msbemba  Thank you for your reply.
I understand that in some particular endpoints like test tenants this package still available there, but for Microsoft, customers don't.
As you can see in the print I provide in the beginning only have the Workspace Key and ID to onboard a device and it is by MMA.
So at least update the page, if there is another way to onboard a device please add those two options in there so the customer can choose from which one he fits and can follow the procedure.

Thanks.

**Comment by msbemba** [comment]
@joaogpinto I see what you are saying.

This document has a note stating the below

While this method of onboarding Windows Server 2012 R2 and Windows Server 2016 is in preview, you can choose to continue to use the previous onboarding method using Microsoft Monitoring Agent (MMA). For more information, see Install and configure endpoints using MMA - https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-downlevel?view=o365-worldwide#install-and-configure-microsoft-monitoring-agent-mma

Hope these are the steps that you are referring to.

Thanks
Sri

**Comment by joaogpinto** [comment]
Hi Sri

yes, that is great.
just have a note that the onboarding process can be done by MMA with the Workspace ID and Key from M365D or if available by downloading and installing the onboarding package.

Thanks.

**Comment by msbemba** [comment]
@joaogpinto That is correct. The note states the different options that are available

![image](https://user-images.githubusercontent.com/45987684/142017309-8f8a089e-cabe-4af9-8057-62af5971a839.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @joaogpinto Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
