### ISSUE TITLE
Remove roles button not available

### ISSUE THREAD

**Issue by henricstromgren** [MicrosoftDocs/microsoft-365-docs#6870]
[Enter feedback here]

Hi, there is no hint on what to do if the "remove roles" function is unavailable for a partner. I.e. the button does not exist.
Can you please add this information, thanks.

regards
Henric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01048d4-36ad-9241-10c7-dcab6dcc2d52
* Version Independent ID: c38e975b-296a-3af3-02df-48db5d983f1b
* Content: [Manage partner relationships](https://docs.microsoft.com/en-us/microsoft-365/commerce/manage-partners?view=o365-worldwide#remove-partner-admin-roles)
* Content Source: [microsoft-365/commerce/manage-partners.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/manage-partners.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@henricstromgren Thank you for your feedback. Ideally you would be contacting support if the option does not show up, I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6905

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @henricstromgren Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
