### ISSUE TITLE
Preferences in Message Center missing

### ISSUE THREAD

**Issue by aktifit** [MicrosoftDocs/microsoft-365-docs#6871]
I don't know if the guide is wrong/outdated or if it's a permission thing, but me and my colleague have access to the message center but the preferences button is missing. Can you update the guide to reflect this behavior?

![messagecenter](https://user-images.githubusercontent.com/26491534/141315758-c5f7dde4-d5c6-46db-805a-9178452a28b3.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f3771a-247c-4f85-992a-e671285c70bd
* Version Independent ID: f3c2890a-2470-9349-ff77-924cf8566365
* Content: [Message center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/message-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/message-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/message-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@aktifit Thank you for your feedback. I have tested in multiple tenants across different regions and I'm able to view the "Preferences" option.

![image](https://user-images.githubusercontent.com/45987684/141825959-dbf97ad4-3f6d-424e-8d3d-6070cb645431.png)

Not sure, if it was a glitch while you submitted this feedback. If you continue to not see the preferences option, I'd recommend you to contact Microsoft support via the ned help link on the admin center.

Hope this helps!

Thanks
Sri

**Comment by aktifit** [comment]
@msbemba 
It seems there is an issue when accessing the Service Health page as a guest user, I can see that it appears if I log in as a regular admin that is homed in the same tenant. I'll open a support ticket, thanks for the hint though.
