### ISSUE TITLE
unable to delete policy created under communication compliance, stuck in deleting status 

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/microsoft-365-docs#6872]
[Communication compliance.docx](https://github.com/MicrosoftDocs/microsoft-365-docs/files/7521095/Communication.compliance.docx)

When trying to delete the policy it is stuck on deleting status. Tried on different browser chrome , edge but it is stuck on deleting status. 
after page refresh it returns .

Any powershell command to delete the policy will be helpful.
attached screenhsot

**Comment by robinpoulose1** [comment]
More About the Comm compliance portal:
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/communication-compliance-policies.md

**Comment by msbemba** [comment]
@robinpoulose1 Thank you for your feedback. I was not able to repro the issue, Is it happening to all the policies? I'd recommend you to contact Microsoft support using the need help link on the admin center, to identify if this is an issue with your tenant or file a bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @robinpoulose1 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
