### ISSUE TITLE
Lab expired

### ISSUE THREAD

**Issue by lightsabregl** [MicrosoftDocs/microsoft-365-docs#6873]
Hi
do you know when the deployment kit will be updated, as it expired on the 6th of Nov

Thanks

Gareth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows 10 and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide#where-to-find-the-windows-10-and-office-365-deployment-lab-kit)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@lightsabregl Thank you for your feedback. I'm currently checking this with the author and will update you shortly.

Thanks
Sri

**Comment by rebrec** [comment]
also waiting for this Labkit👍

**Comment by lightsabregl** [comment]
I can see the page hasn't updated, but the download now has an expiry of Feb 2022 so I assume the lab ha been updated?

**Comment by yogkumgit** [comment]
@lightsabregl We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
