### ISSUE TITLE
PowerShell errors when running Automate hash and upload script

### ISSUE THREAD

**Issue by jaredburnett** [MicrosoftDocs/microsoft-365-docs#6875]
I am getting a series of PowerShell errors when trying to use the script provided in the "Automate hash and upload" steps. It seems that there is a series of unneeded backslashes in the script provided, my hunch being they were added by GitHub automatically. 

![image](https://user-images.githubusercontent.com/76020255/141339873-c015a7ae-efea-44e6-ba75-637f4c790b5f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification?view=o365-worldwide#to-schedule-hashing-and-upload-in-a-combined-step)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
sending to engineering for script QA check

**Comment by yogkumgit** [comment]
@chrfox Kindly update. Thanks
