### ISSUE TITLE
Updates to content please

### ISSUE THREAD

**Issue by jonathanwootton** [MicrosoftDocs/microsoft-365-docs#688]
1. Should "Office 365 Enterprise E5" simply be "Office 365 E5"?
2. Can a screenshot of the disposition review email be provided?
3. What type of file extensions are captured in a disposition review (i.e. docx, xlsx, jpg, pdf)?
4. If I create a retention label that retains content for 1-day based on "date created" and then requires a disposition review, how long will it take for me to see the content under the 'Pending disposition' tab?
5. During the disposition review process, how does the reviewer "Return the content to clients or transfer it to another organization"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d552f987-1606-01f7-d600-5887968ae60c
* Version Independent ID: 8c5f88de-93e7-862e-0550-fb9ac012be35
* Content: [Overview of disposition reviews](https://docs.microsoft.com/en-us/microsoft-365/compliance/disposition-reviews#feedback)
* Content Source: [microsoft-365/compliance/disposition-reviews.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/disposition-reviews.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@jonathanwootton  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LauraWi** [comment]
Hi @jonathanwootton 
#1 -- Branding is correct as is (c.f. the Office 365 Service Descriptions)
#2 -- The text of the disposition mail would be variable, depending on the events triggering disposition, so it's hard to provide a screenshot of that. We could consider this for future revisions
#3 -- Supported file extensions include those supported for Exchange mailboxes, SharePoint sites, OneDrive accounts, and Office 365 groups.
#4 -- It is challenging for me to guesstimate for your test scenario. Keep in mind that it takes a while for a label to sync after it is created. See https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention
#5 -- RE: "Return the content to clients or transfer it to another organization": This item is in a list outlining various general hypothetical actions (some of them might even be manual) that an organization might need to take (depending on business and/or regulatory needs) with content reaches the end of its retention period. It is not a reference to specific functionality.

**Comment by LauraWi** [comment]
Closing issue.
