### ISSUE TITLE
List of Attributes or properties supported is incomplete

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/microsoft-365-docs#6880]
The list of properties supported in a filter currently shows:
First Name
Last name
Display name
Job title
Department
Office
Street address
City
State or province
Postal code
Country or region
Email addresses
Alias
Exchange custom attributes: CustomAttribute1 - CustomAttribute15

However this is out of sync with Microsoft's presentation located here:
https://mipc.eventbuilder.com/event/52683/occurrence/49452/recording?rauth=853.3181650.1f2b6e8b4a05b4441f19b890dfeadcec24c4325e90ac492b7a58eb3045c546ea

I also have a customer who has been able to use Company as a filter.  We may need to link this article to one that lists all the queryable fields for filters or for KQL.  Since I am not sure what the full list of supported properties is my assumption is that this might require pinging the product group to get the best possible list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 592d6717-d670-14a8-acbe-c648958ca208
* Version Independent ID: 9bc46fd9-50e1-1e58-4852-22068e2980ae
* Content: [Configure retention settings to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide#configuration-information-for-adaptive-scopes)
* Content Source: [microsoft-365/compliance/retention-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@cablechewer Thank you for your feedback.  Since you are a Microsoft employee, you can always contact me directly through internal channels.  I don't see Company listed as a selectable attribute in the simple query builder, so I will ask about this. We don't currently have documentation for a full list of properties for KQL queries, although this has been requested.

**Comment by cabailey** [comment]
@cablechewer That presentation is for the advanced query builder, which explains why you don't see Company listed as an attribute for the simple builder query - it would be impractical to list every supported attribute in that table. I've clarified that the attributes in the table aren't exhaustive and link to the presentation if using the advanced query builder. 

The feature is newly released in preview and we are looking into providing additional documentation for KQL supported attributes.
