### ISSUE TITLE
Microsoft 365 Compliance Licensing Comparison XLS

### ISSUE THREAD

**Issue by annferre** [MicrosoftDocs/microsoft-365-docs#6881]
Hi there, the Microsoft 365 Compliance Licensing Comparison sheet is out of date. Can you replace with https://aka.ms/M365EnterprisePlans. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eca8dc5-c382-f624-7d0c-affe1c864744
* Version Independent ID: 076f6f2e-559f-386e-6d49-490c4121b45f
* Content: [Microsoft 365 compliance extensibility - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-extensibility?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-extensibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-extensibility.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@annferre Will do. Thanks for heads up. In the future, you can update the article directly with these type of changes. Here's how: https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-quick-update?branch=master
