### ISSUE TITLE
Add app launcher tiles to the navigation bar

### ISSUE THREAD

**Issue by dimachernov** [MicrosoftDocs/microsoft-365-docs#6885]
The "Learn More" link under Next Steps doesn't have details on how to add app launcher tiles to the navigation bar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9488caf7-b791-3002-8749-7fdc4b2ec8b3
* Version Independent ID: 08e61eb0-7bcd-f449-46ef-17e209138a8e
* Content: [Add custom tiles to the app launcher - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/customize-the-app-launcher?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/customize-the-app-launcher.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@dimachernov Thank you for your feedback. I don't see the option to add it to the navigation bar exists anymore.  We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6917

Once the author verifies and approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dimachernov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
