### ISSUE TITLE
Book Meeting Rooms

### ISSUE THREAD

**Issue by FinnErpff** [MicrosoftDocs/microsoft-365-docs#6889]
Hello, 
we have the issue, that MS Bookings is lacking to provide a proper connection to resources, like a meeting room.
One of our cases is that the manual scheduling of product presentations should be made easier with bookings. Therefor we need the sales rep as a staff member and also a meeting room as the location for the booking. It is possible to link a meeting room in the location section, but this does not affect the availability of the staff member, nor does it block the meeting room, when booked through bookings.

One solution would be to also link the meeting room as a staff member, but at the moment bookings also does not provide the function to make the availability of two staff members required.

Is there any workaround or feature coming up in the next time?

Many thanks in advance.

Best regards

**Comment by yogkumgit** [comment]
@FinnErpff Please indicate which document you are referring to. Thanks

**Comment by FinnErpff** [comment]
@yogkumgit Maybe I am too new to this platform, but how do you link this to a document and also where to find a document?

**Comment by FinnErpff** [comment]
@yogkumgit My request does not refer to any document. It is a customer request for a feature, to either:

Book a staff member and a resource together.

enable the setting, that multiple staff members are required for one booking.

This way a sales rep could be booked together with the meeting room that is required to perform his online product presentation.

**Comment by yogkumgit** [comment]
@FinnErpff Considering the nature of the issue, as observed, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
