### ISSUE TITLE
Virus detection in SharePoint online only available with ATP?

### ISSUE THREAD

**Issue by kuwaharaS** [MicrosoftDocs/microsoft-365-docs#689]
The article states:

> Files are scanned for viruses after they are uploaded. If a file is found to be infected, a property is set so that users can't download or sync the file.

But there is nothing referencing ATP. And as far as I know ATP is required for virus scanning in SharePoint online, or did that change? If this is still a requirement, not mentioning that this requires an additional license is missleading.

Note: Tested with EICAR test file, uploaded to OneDrive for Business and SharePoint online. Files were not blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9cd0ac5-2049-7e80-302e-e0f08857f6b4
* Version Independent ID: 7ca74c37-9929-bfc2-8a27-046457d2f67a
* Content: [Virus detection in SharePoint Online](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/virus-detection-in-spo)
* Content Source: [microsoft-365/security/office-365-security/virus-detection-in-spo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/virus-detection-in-spo.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@kuwaharaS  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @kuwaharaS,
I didn't found any reference where it is told that ATP is not required anymore, so I think this info is missed. I created a PR to add it.
Thank you

**Comment by chetferg** [comment]
Has there been any update to this?

**Comment by AntoineJo** [comment]
Office ATP should only be required for unknown malware analysis and detection in SharePoint Online. Known malware are handled by Microsoft Antimalware engine included in Sharepoint online from my knowledge.

**Comment by kuwaharaS** [comment]
As I mentioned above, I uploaded EICAR test files to SharePoint online. They are still there, and if I try to download them I can. And I assume EICAR is a known malware, if not I would be very worried for testing this..

**Comment by L4nk5** [comment]
I'm in the same boat as kuwaharaS. I uploaded an EICAR test file to my SharePoint online instance with no issues and was able to download it with no warnings. Is there any update on this?

**Comment by mypil** [comment]
@MSFTTracyP - Can you please share your insights on this issue?

Thank you.

**Comment by eldonti** [comment]
same test result with eicar as the other colleagues

**Comment by AntoineJo** [comment]
EICAR never worked for sharepoint online. Try using mimikatz zip file for example, and please note that antimalware scan is asynchronous so it won't be block on upload and depending on your sharepoint settings you might still be able to download it as described here https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/virus-detection-in-spo

**Comment by MikeCreel-creelmt** [comment]
Any update on this open item -- is O365 ATP required for the functionality described above?

**Comment by Mike-Crowley** [comment]
I agree, this article should state that this feature is limited to ATP, if true. Which, according to this other article, it is: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/protect-against-threats?view=o365-worldwide#requirements

**Comment by cobdev** [comment]
Hello Everyone,

I'm trying to evaluate the virus scan status of list items using the "VirusStatus" column.  I'm using PowerShell in combination with the Microsoft.SharePoint.Client.  I can get a result for each file's "VirusStatus" attribute, but I can't make heads or tails of the data.

For example, I have two files in the target Document library that I'm pulling down.  When looking at the data returned for the "VirusStatus" field, I get the following:

LookupId LookupValue TypeId                                
-------- ----------- ------                                
      22 3578721776  {f1d34cc0-9b50-4a78-be78-d5facfcccfb7}
      23 482595566   {f1d34cc0-9b50-4a78-be78-d5facfcccfb7}

Is there a way to interpret the 'LookupValue' for each one?  I've looked at the following sites for guidance, but no luck... 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.spbuiltinfieldid.virusstatus?view=sharepoint-server
https://sharepoint.stackexchange.com/questions/263196/csom-access-to-virus-scanning-status

Thanks for any help! :)

**Comment by GPUpdate** [comment]
So is ATP required or not? It would be nice for it to state this because if SPO out of the box actually requires an E5 license just to get ATP/anti-virus...

**Comment by MSFTTracyP** [comment]
I'm updating the article with a More information section that points to Protect against threats and Turn on ATP for SharePoint, OneDrive, and Microsoft Teams. This should help users to turn on Anti-virus for SharePoint / know to use ATP. Thank you all for your work on this!
