### ISSUE TITLE
Does not include enabling DisallowInfectedFileDownload parameter in SharePoint Online PowerShell

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/microsoft-365-docs#6891]
Hi,

This document includes various recommended security settings for EOP and Defender for Office 365 - but it does not include the recommended action to run the Set-SPOTenant cmdlet with DisallowInfectedFileDownload parameter set to $true.

This is described as recommended for configuring 'Safe Attachments policies in Microsoft Defender for Office 365' here:

https://docs.microsoft.com/microsoft-365/security/office-365-security/protect-against-threats#part-4---protection-from-malicious-urls-and-files-safe-links-and-safe-attachments-in-defender-for-office-365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide#anti-spam-anti-malware-and-anti-phishing-protection-in-eop)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@ChrisAtMAF, interesting observation.  The intent of that topic is effectively to state our recommended Standard and Strict values for policies within Exchange Online Protection and Microsoft Defender for Office 365. The majority of the settings are also use by the Standard and Strict [preset security policies](https://docs.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies). That SharePoint setting falls outside of that.

The setting in question is also mentioned in these topics:

- <https://docs.microsoft.com/microsoft-365/security/office-365-security/turn-on-mdo-for-spo-odb-and-teams#step-2-recommended-use-sharepoint-online-powershell-to-prevent-users-from-downloading-malicious-files>
- <https://docs.microsoft.com/microsoft-365/security/office-365-security/virus-detection-in-spo#what-happens-when-a-user-tries-to-download-an-infected-file-by-using-the-browser>

I added information in the **Comments** cell in the **Turn on Defender for Office 365 for SharePoint, OneDrive, and Microsoft Teams** row.

Thanks for the feedback.

Closing
