### ISSUE TITLE
Placeholder text for ". add screenshot."

### ISSUE THREAD

**Issue by LindaCicero** [MicrosoftDocs/microsoft-365-docs#6895]
Hello - if you search this page for ". add screenshot." you'll see that there's some placeholder text that was left behind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b5bfd1-3aea-0a87-1057-4e06a6fd4c00
* Version Independent ID: 46b5bfd1-3aea-0a87-1057-4e06a6fd4c00
* Content: [Learn about how to provide feedback to Microsoft - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/feedback-provide-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/feedback-provide-microsoft.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **Kwekua**

**Comment by msbemba** [comment]
@LindaCicero Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6899

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @LindaCicero Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
