### ISSUE TITLE
SignInOptions in Office blocks modern authentication on Outlook

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#6900]
The following item should be added to prerequisites. 

When the SignInOptions setting in Microsoft Office is configured to its most restrictive setting, Outlook will be blocked from using modern authentication. When SignInOptions is set to its most restrictive setting, the error message described on the following page will be presented by Outlook after modern authentication is enabled: https://docs.microsoft.com/en-us/office365/troubleshoot/access-management/office-feature-disabled

Administrators should verify that the settings described in this article are not applied in their environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6967c48-088b-9648-a84e-24717f592389
* Version Independent ID: bff5a2db-aa33-ec7d-fd39-070bf0d77a36
* Content: [Hybrid Modern Authentication overview and prerequisites for use with on-premises Skype for Business and Exchange servers - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/hybrid-modern-auth-overview?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/hybrid-modern-auth-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/hybrid-modern-auth-overview.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@robmacf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7008

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @robmacf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
