### ISSUE TITLE
Folder content types being pushed to lists

### ISSUE THREAD

**Issue by CallumCrowley** [MicrosoftDocs/microsoft-365-docs#6901]
**Issue**

SharePoint Syntex only distinguishes content types that need to be pushed to libraries and those that need to be pushed to lists by those content types derived from the "Document" content type. However, this means that content types derived from the "Folder" content type are pushed to lists. Users only use folder content types in document libraries, therefore this appears to be an oversight. 

Additionally, folder content types being pushed to events lists is causing considerable errors which can only be resolved by deleting the folder content types from the events list.

_"A pushed content type will be added to a document library only if it derives directly or indirectly from the Document content type, and a content type will be added to a list only if it does not derive from the Document content type directly or indirectly."_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4760c99-cd14-4733-1655-786ab727fa6e
* Version Independent ID: 4ef91a24-bf3a-3d0b-da44-f153b788df10
* Content: [Push content types to a hub](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/push-content-type-to-hub)
* Content Source: [microsoft-365/contentunderstanding/push-content-type-to-hub.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/push-content-type-to-hub.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@seansquires fyi

**Comment by seansquires** [comment]
Thanks for the feedback, @CallumCrowley. Folder content types can be added to standard lists (noting that the option to add from the new item menu is off by default), but we are missing a check to prevent these from being added to event lists. Thank you for catching this. We are working on a code fix and will update the documentation accordingly.

**Comment by yogkumgit** [comment]
@CallumCrowley Hope this comment is helpful for you.  We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by CallumCrowley** [comment]
Thanks for the quick response and resolution @seansquires :)

Also, thanks for the great work on SharePoint Syntex, some really useful new features!
