### ISSUE TITLE
Broken link on this page

### ISSUE THREAD

**Issue by ShaXam-King** [MicrosoftDocs/microsoft-365-docs#6903]
Greetings!

This article has a broken link in this sentence "If you haven't already done so, integrate Microsoft Defender for Office 365 with Microsoft Defender for Endpoint.". The link there points to https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/integrate-office-365-ti-with-wdatp.

I get a 404 error when clicking that link.

Also, I searched for that term and got back the same docs link.  It looks like that page is gone.

Thx!
Dan.
(danking@microsoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4edb515-8512-06c0-aea6-5d0d3b4fb536
* Version Independent ID: bf5f9747-8b9d-b8c1-77a9-0746e48282c9
* Content: [Better together - Microsoft Defender Antivirus and Office 365 (including OneDrive) - better protection from ransomware and cyberthreats](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/office-365-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/office-365-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/office-365-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@ShaXam-King Thank yu for your feedback. we have fixed the broken link in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6940

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ShaXam-King Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
