### ISSUE TITLE
Set behavior monitoring in Linux configuration file

### ISSUE THREAD

**Issue by nielsvdGH** [MicrosoftDocs/microsoft-365-docs#6904]
What is the correct key name to configure behavior monitoring through a configuration profile?
In the documentation the key is referred to as "name".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ef0d15-6735-bb94-0d86-d57ffbaa05f7
* Version Independent ID: 52e516b5-b365-4950-334a-c4797333093d
* Content: [Set preferences for Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-preferences?view=o365-worldwide#enabledisable-behavior-monitoring)
* Content Source: [microsoft-365/security/defender-endpoint/linux-preferences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-preferences.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@nielsvdGH Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6941

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nielsvdGH Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
