### ISSUE TITLE
Request for document update

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/microsoft-365-docs#691]
Hoping to get a comment/note added for the following statement in this documentation.
" This new subfolder points to the items that were moved. The naming convention that Office 365 uses to name this folder is <folder name>_yyyy (Created on mmm dd, yyyy h_mm)"

Recently working with Product Group, they suggested that "Not all folders that are mapped to aux archives result in this naming/format. This is done in some circumstances to help distribute the content of a folder but it is not required for a folder to be mapped."

Refer to David's comment in below link
https://o365exchange.visualstudio.com/DefaultCollection/IP%20Engineering/_workitems/edit/1257427

So it would help to make the documentation clear by stating that it is not always that the nomenclature have this format and may vary based on circumstances.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69e08cf1-3ef1-7d22-122e-ef0f45c26215
* Version Independent ID: e9677dc3-580d-0a66-80ac-30a8aabdd45f
* Content: [Overview of unlimited archiving in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/unlimited-archiving)
* Content Source: [microsoft-365/compliance/unlimited-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/unlimited-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@qaehtesh  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@qaehtesh The article has been updated with the requested info.

**Comment by Mohkam** [comment]
I guess in september 2019, “The unlimited archiving feature in Office 365 (called auto-expanding archiving) provides up to 1 TB of storage in archive mailboxes in Exchange Online.”  as it still shows in  https://docs.microsoft.com/zh-tw/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description#unlimited-archive-storage-quota

Is the upper limit still the same (1 TB) or its changed ?
