### ISSUE TITLE
Adding the Swedish Region in the list. 

### ISSUE THREAD

**Issue by EAWerner** [MicrosoftDocs/microsoft-365-docs#6915]
[Enter feedback here]
I'm sure it's in the works but it seems like it should be time to add details about the Swedish region here. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87cb379c-82ae-0a6e-8dd5-0c41b09364ab
* Version Independent ID: a15c3919-e63e-f0dc-bd6b-45f311b387b5
* Content: [How to request your data move - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/request-your-data-move?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/request-your-data-move.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/request-your-data-move.md)
* Service: **o365-administration**
* GitHub Login: @andybergen
* Microsoft Alias: **andyber**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@EAWerner Thank you for your feedback. The data on the sheet is handled by the product group and it will be available on the document once they have this worked out for the Swedish region. You can also submit feedback on our main feedback portal- https://feedbackportal.microsoft.com/feedback/ to get status updates on this particular query.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @EAWerner Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by EAWerner** [comment]
Thank you everyone. I also noticed the page have been updated now so case closed!
