### ISSUE TITLE
Shared mailboxes mention

### ISSUE THREAD

**Issue by burtzz** [MicrosoftDocs/microsoft-365-docs#692]
Hi, there should be a mention to shared mailboxes, and perhaps other mailbox types, on the Exchange section.
Is not clear if retention covers shared mailboxes or not.

As far as I know a retention policy doesn't cover a shared mailbox.
But what if it's a licensed shared mailbox, are they automatically cover by an existing retention policy applied to entire Exchange estate? 
I do believe they are covered, hope so, as we have licensed many critical shared mailboxes for retention, not only, purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies#feedback)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@burtzz  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LauraWi** [comment]
@burtzz Yes, retention covers shared mailboxes. See footnote 2 here: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#storage-limits-across-office-365-options

**Comment by LauraWi** [comment]
Closing issue.
