### ISSUE TITLE
Hint, show us where things are in your documentation.

### ISSUE THREAD

**Issue by ok2play** [MicrosoftDocs/microsoft-365-docs#6922]
The biggest problem with Microsoft documentation is it seems we are expected to know where this shit is. Please point me in this page to where I find this Microsoft Defender Security Center Security operations dashboard.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52cf9eaa-c236-18f7-1a55-9707b953859c
* Version Independent ID: 59ee1886-914c-1d7d-ab5c-241efe9e2724
* Content: [Microsoft Defender Security Center Security operations dashboard](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/security-operations-dashboard?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/security-operations-dashboard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/security-operations-dashboard.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
It's literally the landing page once you log into securitycenter.windows.com.

**Comment by ok2play** [comment]
Mjcaparas, thank you for the literal link. 

The link you provide just redirects to security.microsoft.com so not able to get to securitycenter.microsoft.com

And for those that don't know what securitycenter I'd please go to admin.microsoft.com and tell me where security center is? Oh, not a freaking thing on the page says security center.
