### ISSUE TITLE
Licensing requirement not correct

### ISSUE THREAD

**Issue by Nosferatu-Dk** [MicrosoftDocs/microsoft-365-docs#6923]
[
![Licensing requirements](https://user-images.githubusercontent.com/39123128/142162653-2d66910a-f8fa-4f11-936b-792c151d4cf1.png)
The M365 E3 + EMS E5 Security Add on is missing as licensing option. Source here : https://docs.microsoft.com/en-us/microsoft-365/security/defender/prerequisites?view=o365-worldwide#licensing-requirements 
And also listed here at Page 3 - https://aka.ms/M365EnterprisePlans Source URL : https://www.microsoft.com/da-dk/licensing/product-licensing/microsoft-365-enterprise?rtc=1&activetab=m365-enterprise%3aprimaryr5 
Also the Bussines Premium licensing option should be valid soon, so maybe it would be an option to add that license now also
Just a thougth :)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Nosferatu-Dk Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6978

We will add M365 business premium once it is available on the public preview.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Nosferatu-Dk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
