### ISSUE TITLE
question about connection filter whiteliting

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/microsoft-365-docs#6926]
Does the connection filter whitelist (by IP) also whitelist the anti-malware engine malware checks? or do whitelisted IPs in the connection filter only whitelist the reputation?

**Comment by chrisda** [comment]
@netaneladar, any sort of whitelisting in Office 365 (see [this topic](https://docs.microsoft.com/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365), including connection filtering by IP, does not skip filtering for malware or (as of very recently) high confidence phishing messages from anti-spam policies.

**Comment by yogkumgit** [comment]
@netaneladar  Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by netaneladar** [comment]
Thank you. I see in the article that you sent that "Messages that are identified as malware or high confidence phishing are always quarantined, regardless of the safe sender list option that you use."

This answers my question.
