### ISSUE TITLE
ISO dates in search

### ISSUE THREAD

**Issue by paulaustin-automutatio** [MicrosoftDocs/microsoft-365-docs#6927]
[Enter feedback here]
What formats are there for dates in the sent field.

Dates should be the ISO standard YYYY-MM-DD as it is non ambiguous. USA style dates MM/DD/YYYY are just confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e83b77e5-e3ec-6a5f-1f09-e232e2dda483
* Version Independent ID: 0b263c72-95a2-d111-20a7-68857f288369
* Content: [Keyword queries and search conditions for eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/keyword-queries-and-search-conditions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/keyword-queries-and-search-conditions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@paulaustin-automutatio Thanks for feedback. I will update examples in this article to use YYYY-MM-DD format.
