### ISSUE TITLE
Using retention labels to declare records

### ISSUE THREAD

**Issue by Soulsailor** [MicrosoftDocs/microsoft-365-docs#693]
In the section "Using retention labels to declare records" it states:

"Using a retention label that declares content as a record requires an Office 365 Enterprise E5 license for each user who has permissions to edit the content. Users who simply have read-only access don't require an E5 license."

Is this a mistake? I thought records retention was available in E3?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Overview of records](https://docs.microsoft.com/en-us/microsoft-365/compliance/records#feedback)
* Content Source: [microsoft-365/compliance/records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@Soulsailor  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LauraWi** [comment]
Hi @soulsailor I think the nuance here is between what's supported for data governance (manual labels) and advanced data governance (i.e., policy-driven retention): https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

**Comment by Soulsailor** [comment]
@LauraWi Thanks for your response. So I think what you are saying is as follows:
Auto Applying a Records Retention label requires E5, but an en-user manually adding a Records Retention label to content is still E3?
If that is the case then, yes it is semantics, but I think the note box should mention the "auto apply" aspect for clarity.

**Comment by LauraWi** [comment]
Yes, that's it. Thanks for the feedback on clarity. We'll be revising RM content.
