### ISSUE TITLE
New changes appear to have flipped un-intended policies.

### ISSUE THREAD

**Issue by n0nexistence** [MicrosoftDocs/microsoft-365-docs#6932]
It appears that this change may have flipped our default policy from send emails to Junk instead to go to quarentine in our GCCH anti-spam policy. I know high-confidence spam is required now, but I didn't see anything about flipping the other values.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472b3a0c-7ad8-8245-9b57-29431490370b
* Version Independent ID: 8671f04a-b7b3-402c-1e65-59a52c1cdaf5
* Content: [Secure by default in Office 365 - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/secure-by-default?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/secure-by-default.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-by-default.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@n0nexistence Thank you for your feedback. Email with suspected malware will automatically be quarantined and Email identified as high confidence phishing will be handled according to the anti-spam policy action. Enabling security defaults will override your anti-spam policy in case of suspected malware.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @n0nexistence Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
