### ISSUE TITLE
Can't save change in email mailbox permissions.

### ISSUE THREAD

**Issue by bizdevguy** [MicrosoftDocs/microsoft-365-docs#6935]
> Hi.

This page has no save button. The help topic says there is a save button.

![image](https://user-images.githubusercontent.com/10223197/142289991-374cd1df-89a0-4273-b711-88807e1d9c01.png)

[Enter feedback here]

Help
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b9d613a-f990-4045-f0d3-273ecc827db7
* Version Independent ID: ef031919-5994-8d21-1f62-ee0db6f235b0
* Content: [Give mailbox permissions to another user - Admin Help - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@bizdevguy Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6968

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @bizdevguy Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
