### ISSUE TITLE
Suggestion for clarification

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/microsoft-365-docs#6936]
It is unclear from this page as to what the difference is between "Send email from another user's mailbox" and "Send email on behalf of another user".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b9d613a-f990-4045-f0d3-273ecc827db7
* Version Independent ID: ef031919-5994-8d21-1f62-ee0db6f235b0
* Content: [Give mailbox permissions to another user - Admin Help - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@deejerydoo Thank you for your feedback.

Send as permissions: Your message will appear to have come from the user that granted you this permission.
Send on behalf of permissions: The "From" address in any message sent by you will indicate that the message was sent by you on behalf of the user that granted you this permission.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @deejerydoo Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
