### ISSUE TITLE
מספר הטלפון שאתם מציגים לתמיכה בישראל (1800344179) איננו מחובר !!!

### ISSUE THREAD

**Issue by sbaron858** [MicrosoftDocs/microsoft-365-docs#6937]
מספר הטלפון שאתם מציגים לתמיכה בישראל (1800344179) איננו מחובר !!!

---
#### פרטי המסמך

⚠ *אין לערוך מקטע זה. פעולה זו נדרשת עבור קישור לנושאים ב- docs.microsoft.com ← GitHub.*

* ID: 88b50cb4-3243-6395-ee10-c60531d6b214
* Version Independent ID: 01e32c73-f641-ab7b-599d-f279a008a4ea
* Content: [Support information for Israel - Microsoft 365 admin](https://docs.microsoft.com/he-il/microsoft-365/admin/support/israel?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/israel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/israel.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@sbaron858 What is your feedback to improve the documentation. Please share it in English. Thanks

**Comment by yogkumgit** [comment]
@sbaron858 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
