### ISSUE TITLE
Does it work on Office applications on Macs?

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/microsoft-365-docs#6939]
The version requirement of 2004 or higher is for Windows.

My Macs are at version 16.55 - will they be supported with this feature?

**Comment by yogkumgit** [comment]
@netaneladar Which document you are referring to. What is your feedback to improve it. Thanks

**Comment by netaneladar** [comment]
"63773389-8a4f-926f-8430-8c80b19ff2da" 
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide

**Comment by netaneladar** [comment]
is there an update on this?

Does the Safe Documents feature work on Office apps in Mac?

**Comment by netaneladar** [comment]
Any update?

**Comment by netaneladar** [comment]
I've deployed this across the organization and applied all the Microsoft 365 E5 licenses BUT only the windows users have the feature (office apps version 2102), and Macs don't seem to get the safe documents scans (office apps version 16.55)

**Comment by netaneladar** [comment]
![Screen Shot 2021-11-25 at 10 59 07](https://user-images.githubusercontent.com/43445138/143411037-6e9b0b27-06c6-4003-9c69-ca7052672c79.png)

**Comment by msbemba** [comment]
@netaneladar Thank you for your feedback. This feature is only available in the Windows version of Microsoft 365 Apps for enterprise. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @netaneladar Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by netaneladar** [comment]
Thank you. Can this please be added to the documentation?
