### ISSUE TITLE
Please do not forget about the "New Exchange Admin version"

### ISSUE THREAD

**Issue by jevreni** [MicrosoftDocs/microsoft-365-docs#6944]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34c90550-34c3-c6de-81d4-6d85a8bc3f90
* Version Independent ID: 151fb754-7bea-f489-5115-e3551db0f303
* Content: [Step 5 - Wipe and block a former employee's mobile device - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-5?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-5.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-5.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jevreni Thank you for your feedback. I tested and found that the Wipe option is not available in the new Exchange admin center.
Once the option is made available the document will be updated.

Also, If you are looking for other ways to do a remote wipe -here are the options

https://docs.microsoft.com/en-us/microsoft-365/admin/basic-mobility-security/wipe-mobile-device?view=o365-worldwide#:~:text=Wipe%20a%20mobile%20device%201%20Go%20to%20the,Factory%20reset.%20...%207%20Select%20Yes%20to%20confirm. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jevreni Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
