### ISSUE TITLE
Set up the Microsoft Defender for Endpoint on macOS policies in Jamf Pro: Step 2.2

### ISSUE THREAD

**Issue by dan-snelson** [MicrosoftDocs/microsoft-365-docs#6948]
First, thank you for the detailed documentation.

For [Set up the Microsoft Defender for Endpoint on macOS policies in Jamf Pro: Step 2.2](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide#step-2-create-a-configuration-profile-in-jamf-pro-using-the-onboarding-package), please consider changing …

> 2. In the Jamf Pro dashboard, select **New**.

… to:

> 2. Login to Jamf Pro and navigate to: **Computers > Configuration Profiles** and click **New**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a947a2-093c-0f4e-7053-c30112d1cee1
* Version Independent ID: 12fbc5ca-2b24-6717-ac98-331f0bba5278
* Content: [Set up the Microsoft Defender for Endpoint on macOS policies in Jamf Pro](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@dan-snelson Thank you for the feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6979

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dan-snelson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
