### ISSUE TITLE
Set up the Microsoft Defender for Endpoint on macOS policies in Jamf Pro: Step 2.4 

### ISSUE THREAD

**Issue by dan-snelson** [MicrosoftDocs/microsoft-365-docs#6949]
The documentation for [Set up the Microsoft Defender for Endpoint on macOS policies in Jamf Pro, Step 2.4](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide#step-2-create-a-configuration-profile-in-jamf-pro-using-the-onboarding-package) is outdated when using Jamf Pro 10.33.0.

**Current:**
4. In **Application & Custom Settings** select **Configure**.

**Proposed:**
4. Navigate to the **Application & Custom Settings** payload and select **Upload > Add**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a947a2-093c-0f4e-7053-c30112d1cee1
* Version Independent ID: 12fbc5ca-2b24-6717-ac98-331f0bba5278
* Content: [Set up the Microsoft Defender for Endpoint on macOS policies in Jamf Pro](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@dan-snelson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6980

Thanks
Sri
