### ISSUE TITLE
Capitalize the “y” in “you”, directly following “-“ in the 3rd item, “Choose the conditions that must be matched for a policy to be applied to an item” under “DLP policy configuration overview”.

### ISSUE THREAD

**Issue by zbraiterman** [MicrosoftDocs/microsoft-365-docs#6950]
This will improve upon grammatical consistency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adedbe4e-fdfa-473e-6f55-4f0247658472
* Version Independent ID: ee52c4d5-6588-215c-ef92-035211cb302f
* Content: [Learn about data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-learn-about-dlp?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/dlp-learn-about-dlp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-learn-about-dlp.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@zbraiterman Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6981

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @zbraiterman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
