### ISSUE TITLE
Compat issues? Or maybe lack of features

### ISSUE THREAD

**Issue by d3s3rtf0x** [MicrosoftDocs/microsoft-365-docs#6951]
[Enter feedback here]

I'm having some issues managing the VOIP for my company. With the recent move to force the Teams PowerShell connector I have found a sudden lack for certain features I have used with the Skype for business connector (LyncOnlineConnector). More specifically, I can't seem to find a way to do issue these cmdlets with the new connector.

Set-CsUser -identity {UserMail} -EnterpriseVoiceEnabled $true -HostedVoicemail $true

Grant-CsOnlineVoiceRoutingPolicy -Identity "UserMail" -PolicyName "PolicyNameHere"

Grant-CsTeamsCallingPolicy -PolicyName AllowCalling -Identity {UserMail}

The first one being the most unpleasant it seems.

Unfortunately the combination of these three commands cannot be done through the Teams Admin Center since the VOIP provider isn't Microsoft. For whatever reason.

Any Support would be greatly appreciated. 

-JE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289b637a-ad53-2710-3b6e-7f4ac15916fa
* Version Independent ID: e8de4044-38f3-1002-9816-12515d0cdda0
* Content: [Manage Skype for Business Online with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@d3s3rtf0x Thank you for your feedback. This looks more like a support issue, we recommend you contact Microsoft support to fix this issue. You can use the need help option on the admin center to reach out to the support team.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @d3s3rtf0x Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.

We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
