### ISSUE TITLE
inactive mailbox and archive

### ISSUE THREAD

**Issue by joshfolcik** [MicrosoftDocs/microsoft-365-docs#6952]
The statement here, seems very vague and misleading:
https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-auto-expanding-archives

Because if I then read this, it looks like any worry I had reading the first part, is negated by the following which says the opposite, that an inactive mailbox with an online archive can be restored to another mailbox that has an archive. It also talks about auto expanding, but doesn't explain much about that in the top one, most of the time you would refer to an archive as an Online Archive.
https://docs.microsoft.com/en-us/microsoft-365/compliance/restore-an-inactive-mailbox?view=o365-worldwide#restore-the-archive-from-an-inactive-mailbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Learn about inactive mailboxes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@joshfolcik Thanks for inquiring about this. I think a note should be added to the second article you cite saying that an inactive mailbox can't restored (or recovered) if auto-expanding archiving was enabled on the mailbox before it was made inactive.

Background is that there are two archive mailbox states. 1. You can enable the archive mailbox for a user's primary mailbox. When you do this, the archive is created with a quota of 100 GB. 2. Additionally, you can also enable the auto-expanding archiving for a user's archive mailbox (note that the archive has to be enabled before you can "turn on" auto-expanding archiving. Auto-expanding archiving will provision additional archive storage space in 50 GB increments until a maximum of 1.5. TB of additional space is provisioned.

That said, you can recover or restore an inactive mailbox only when the archive mailbox is enabled (#1 above). If auto-expanding archiving was also enabled before the mailbox was made inactive, then it cannot be recovered or restored. The workaround, as per the article is to use content search tool to search the inactive mailbox, export that content, and then import it to a different active mailbox.

Hope that helps to clarify.
