### ISSUE TITLE
Order of policy precedence clarification

### ISSUE THREAD

**Issue by cj8686** [MicrosoftDocs/microsoft-365-docs#6953]
https://docs.microsoft.com/microsoft-365/security/office-365-security/preset-security-policies#order-of-precedence-for-preset-security-policies-and-other-policies

in the above section the behaviour described is per-setting processing, i.e. all policies that are applicable to a given user are applied, in reverse order of precedence (much like windows group policy). the resulting set of policy will be a blend of all of the policies. 

this is in contrast to what is explained in the following doc: https://docs.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined

with specific reference to: "If a user is defined in multiple policies of the same type, only the policy with the highest priority is applied to them. Any remaining policies of that type are not evaluated for the user (including the default policy)."

I'm left unclear as to how policy processing works when a security preset is involved.

If it helps, the specific use case I have is: We want to use the security presets, but we want to configure named individuals in the anti-impersonation anti-phishing policy. The security preset should apply to all users. We should then create a custom anti-phishing policy to specify 'users to protect' since we can't modify the security preset policy. Since 'users to protect' is not a configured setting in the preset policy, if I believe the wording in the preset security policies ms doc my custom policy should carry over into the resulting policy. If I believe the other doc then only whole policies are applied, and the security presets trump custom policies, so my 'users to protect' doesn't apply.

Hopefully that makes sense, i'd be grateful if you could clarify the behaviour.

Thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cj8686, you've touched on the current weakness of preset security policies: super-easy to configure, impossible to customize.

> in the above section the behaviour described is per-setting processing, i.e. all policies that are applicable to a given user are applied, in reverse order of precedence (much like windows group policy). the resulting set of policy will be a blend of all of the policies.

Sorry, that's incorrect. If you look at the example in the "order of precedence" topic, Policy A is applied, and Policy B is skipped. There is never a blending of policies of the same type. ALL settings in the first policy that hits (user is defined) are applied, and then policy processing for that type of policy stops.

> I'm left unclear as to how policy processing works when a security preset is involved.

As described in the "preset security policies" topic, if a given user (recipient) is defined in multiple policies of the same type, preset security policies are applied before custom policies are applied before the default policy. For preset security policies, Strict is applied before Standard. For custom policies, the priority controls everything (lower number = higher priority; also the same as the order that they're displayed in the admin center). The default policy is "the policy of last resort" and is always applied last, or better stated, "is never applied if the user is defined in a preset security policy or a custom policy".

So, if you want to define users and/or domains for impersonation protection in anti-phishing policies that apply to ALL users, you can't use preset security policies at all; use custom policies and/or the default policies for everything.

If you can live with a subset of users who receive impersonation protection while the rest of the users do not, you can use custom anti-phishing policies for the subset users, and preset security policies for the rest of the users. Just make sure that the subset users are ONLY defined in the custom/default policies, while the rest of the users are ONLY defined in preset security policies.

Does this make sense?

**Comment by yogkumgit** [comment]
@cj8686 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
