### ISSUE TITLE
'We don't recommend the built-in reporting experience in Outlook because it can't use the user submission policy. We recommend using the Report Message add-in or the Report Phishing add-in instead.'

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/microsoft-365-docs#6954]
Under 'What do you need to know before you begin?' the following Information box appears:

'We don't recommend the built-in reporting experience in Outlook because it can't use the user submission policy. We recommend using the Report Message add-in or the Report Phishing add-in instead.'

Is it worth providing the following PowerShell for Set-OwaMailboxPolicy where the built-in experience can be disabled?

Set-OwaMailboxPolicy -Identity OwaMailboxPolicy-Default -ReportJunkEmailEnabled $false

https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ChrisAtMAF Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7000

Once the author approves the changes will be live.

Thanks
Sri

**Comment by chrisda** [comment]
Topic updated per referenced pull request.

Thanks for the feedback.

Closing
