### ISSUE TITLE
Disabling reporting in Outlook on the web

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/microsoft-365-docs#6955]
Under the main heading there is the text with the link:

'If reporting has been **disabled in Outlook on the web**, enabling user reported messages here will override that setting and enable users to report messages in Outlook on the web again.'

However the link does not describe how to disable reporting in Outlook on the Web. I am not sure but this may be how you do it?

Set-OwaMailboxPolicy -Identity OwaMailboxPolicy-Default -ReportJunkEmailEnabled $false

https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User reported message settings - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ChrisAtMAF Thank you for your feedback. We have updated the linking document -https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-false-positives-and-false-negatives?view=o365-worldwide#disable-or-enable-junk-email-reporting-in-outlook-on-the-web

via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7001 

Once the author approves, the document will be live.

Thanks
Sri

**Comment by chrisda** [comment]
Topic updated per reference pull request.

Thanks for the feedback.

Closing
