### ISSUE TITLE
Disabling built-in junk email reporting

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/microsoft-365-docs#6957]
The important warning reads as follows:

'The built-in experience for reporting junk or phishing in Outlook can't use the user submission policy. We recommend using the Report Message add-in or the Report Phishing add-in instead.'

Is it worth providing the following PowerShell for Set-OwaMailboxPolicy where the built-in experience can be disabled?

Set-OwaMailboxPolicy -Identity OwaMailboxPolicy-Default -ReportJunkEmailEnabled $false

https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps

I have also submitted some other page modifications where it is suggested that this information is included in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e0344cf-9692-43ff-94c3-f86f7d61e53b
* Version Independent ID: bd84da4a-c6c1-d5ae-2a68-a0093629b460
* Content: [Report false positives and false negatives in Outlook - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-false-positives-and-false-negatives?view=o365-worldwide#disable-or-enable-junk-email-reporting-in-outlook-on-the-web)
* Content Source: [microsoft-365/security/office-365-security/report-false-positives-and-false-negatives.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/report-false-positives-and-false-negatives.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ChrisAtMAF Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7001

Thanks
Sri

**Comment by chrisda** [comment]
Pull request related to this issue was merged, so closing.

Thanks for the feedback.
