### ISSUE TITLE
Liungle


### ISSUE THREAD

**Issue by Lovygoogle** [MicrosoftDocs/microsoft-365-docs#6960]
https://https://g.dev/Ira/liungle

**Comment by yogkumgit** [comment]
@Lovygoogle Which document you are referring to and what is your feedback. Thanks

**Comment by Lovygoogle** [comment]
يتم ترحيل المستندات تلقائيا

**Comment by Lovygoogle** [comment]
> @Lovygoogle Which document you are referring to and what is your feedback. Thanks

احاول إرجاع بعض الخدمات
