### ISSUE TITLE
Delegate access/permissions ambiguity...

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/microsoft-365-docs#6962]
When setting these permissions in the MS 365 console, we are given the following three access permissions:
1. Read and manage permissions
2. Send as permissions
3. Send on behalf of permissions

Your article explains "Read" permissions but says nothing about what the "manage" part means in "Read and manage". If the permission goes so far as to explicitly state "read AND MANAGE" then why would you not even mention what "manage" means? Of the two parts of the permission "read and manage" I would say that the "read" part is pretty self explanatory. The "Manage" part not so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b9d613a-f990-4045-f0d3-273ecc827db7
* Version Independent ID: ef031919-5994-8d21-1f62-ee0db6f235b0
* Content: [Give mailbox permissions to another user - Admin Help - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@deejerydoo Thank you for your feedback. 

Read and Manage permission allows the assigned user mailbox(es) to read as well as manage emails in the user mailbox on which the permission is assigned. Manage could be anything that you can do with full access( Create a rule, move emails in the mailbox, create a new folder, etc).

I have made a change to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7003

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @deejerydoo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
