### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/microsoft-365-docs#6963]
Hi,

Pretty sure this is just a doco that needs updating by the listed O\S under the sub section called Block executable content from email client and webmail are currently listed as

Windows 10, version 1709
Windows Server, version 1809
Windows Server 2019
Microsoft Endpoint Manager CB 1710
Windows Server 2016
Windows Server 2012 R2

Is Windows 11 included in this, and or later editions of Windows 10?

Regards
John Louden

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96cedf2c-e6fa-bbfb-61f0-ab4bcaae1479
* Version Independent ID: 45ca9ffb-55e9-7721-3433-017a513a59be
* Content: [Use attack surface reduction rules to prevent malware infection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-executable-content-from-email-client-and-webmail)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@Jlouden9 Thank you for your feedback. You are correct, Windows 11 is included in this.

The page reflects correctly now

Windows 10, version 1709 (RS3, build 16299) or greater, or Windows 11
Windows Server 2016
Windows Server 2012 R2

@yogkumgit  There are no changes needed in this document and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Jlouden9 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
