### ISSUE TITLE
Office for Germany has been deprecated

### ISSUE THREAD

**Issue by annferre** [MicrosoftDocs/microsoft-365-docs#6967]
Requested change:
Office 365 Endpoints for Germany - Remove Germany endpoints from traversing across our other clouds
When you access the Offce365 URL's and IP ranges, you are able to traverse across these endpoints for our different cloud options.  Please remove the "Office 365 endpoints for Germany - Microsoft 365 Enterprise"
The web page for URL and endpoints for MS at 21Vianet is available at the link:  https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges-21vianet?view=o365-worldwide  .  At the service description it shows how to link over to the different clouds info, including Germany which needs to be removed as an option
forward link to: https://aka.ms/germanymigrateassist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1248ba04-fd9a-c009-9821-94c7b7aec88b
* Version Independent ID: eec20193-ee91-0f70-2d62-a8aa99e6e84a
* Content: [URLs and IP address ranges for Office 365 operated by 21Vianet - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges-21vianet?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges-21vianet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by tiburd** [comment]
@yogkumgit - this issue is being worked on internally; don't assign to a freelancer. Thanks!

**Comment by tiburd** [comment]
@annferre @kelleyvice-msft - Please submit your PR(s) via the private repo. Thanks!
