### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#6975]
Under the "See Also" section at the bottom, this is a broken link:
Automated investigation and response in Microsoft 365 Defender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ebc792-00f8-b204-f5c1-579a037d2d06
* Version Independent ID: 53f7089f-6783-1866-d116-5f461c125fca
* Content: [Use automated investigations to investigate and remediate threats](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/automated-investigations?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/automated-investigations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/automated-investigations.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@itguysocal Thank you for your feedback. The article is not available now, I have removed the broken link via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/6991

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @itguysocal Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
