### ISSUE TITLE
Update Disconnect code

### ISSUE THREAD

**Issue by Ryu-Syrius** [MicrosoftDocs/microsoft-365-docs#6977]
I am fairly certain the Skype For Business modules is deprecated.

https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide#close-the-powershell-window

You can remove `Remove-PSSession $sfboSession ; ` from the code block.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6adeef66-5e54-ba2f-37ac-c1898ef942c6
* Version Independent ID: f8a6eda6-b300-dc76-4392-9aeb6c532822
* Content: [Connect to all Microsoft 365 services in a single PowerShell window - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Thanks, @Ryu-Syrius. I'll fix that.

**Comment by kelleyvice-msft** [comment]
Updated in https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/11664.
