### ISSUE TITLE
The 2 links that I needed from this page do not work

### ISSUE THREAD

**Issue by MattITMan** [MicrosoftDocs/microsoft-365-docs#6985]
One of the links gives a 404 error and the other just goes to a general Blog page and not the actual Blog that I need. They are in the paragraph shown below.

Other entitlements:

Microsoft 365 Business Premium customers also have access to Windows Virtual Desktop and Office Shared Computer Activation capabilities. Read the Microsoft 365 Business Premium blog to learn more. See also the Microsoft 365 for business service description.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ed7e43-7ec8-01f6-8cf0-6fd77519840e
* Version Independent ID: 1cb6b2df-6565-e248-ee83-6154c49a0056
* Content: [Microsoft 365 Business Premium frequently asked questions ](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/microsoft-365-business-faqs?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/microsoft-365-business-faqs.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/microsoft-365-business-faqs.yml)
* Product: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by yogkumgit** [comment]
@efrene Please help us in resolving this issue. Thanks

**Comment by efrene** [comment]
Corrected links.

**Comment by yogkumgit** [comment]
@MattITMan Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MattITMan** [comment]
Yes. Thanks for fixing it. It is nice to see a company that will actually fix errors like this. Especially when it is information that I need. I hope you have a great day.

Matthew Tisdel

________________________________

**Comment by efrene** [comment]
@MattITMan Thanks for the kind note, and sorry for the delay in fixing this. Have a great day!
