### ISSUE TITLE
Email Forwarding is really Email Redirecting

### ISSUE THREAD

**Issue by Dburke225** [MicrosoftDocs/microsoft-365-docs#6989]
You should really change the name from Email Forwarding to Email Redirecting. 

It changes the To field to the user's mailbox that it is forwarding to, rather than keeping the original recipient. That is redirecting, your changing the intended recipient. This confused us when we had to trace and investigate emails and hurt our reporting numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5885a586-76b8-83ae-161b-6c9c8793b42d
* Version Independent ID: 681fe343-6272-a75a-ed00-dc7ef4355e67
* Content: [Configure email forwarding - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-email-forwarding.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Dburke225  Thank you for your feedback.

If you use redirect, your email will be redirected to another email address specified by the user. This will redirect the emails as if they came directly from the original sender's email address.

If you use forward, your email will be forwarded to another email address, but you will not be able to reply to the original sender. Forwarded emails will arrive as if it was forwarded to you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Dburke225 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
