### ISSUE TITLE
partnerID in SAP SuccessFactors / Viva Learning Doc

### ISSUE THREAD

**Issue by dborchers-gc** [MicrosoftDocs/microsoft-365-docs#6992]
What means partnerID in this DOC? The Tenant-Name or CompanyID from SAP is longer than 10 Charachters and the Tenant-ID vom M365-Tenant is longer than 10 charcters too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19287016-f48c-d381-a098-d78aab1c968a
* Version Independent ID: 19287016-f48c-d381-a098-d78aab1c968a
* Content: [Configure SAP SuccessFactors as a content source for Microsoft Viva Learning](https://docs.microsoft.com/en-US/microsoft-365/learning/configure-successfactors-content-source?view=o365-worldwide)
* Content Source: [microsoft-365/learning/configure-successfactors-content-source.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/learning/configure-successfactors-content-source.md)
* Service: ****
* Product: **microsoft-365-enterprise**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by msbemba** [comment]
@dborchers-gc Thank you for your feedback. I checked this in the SAP help portal and found that this is the Partner ID for the support partner. 

![image](https://user-images.githubusercontent.com/45987684/144234275-822f0048-695d-4808-be43-b481552694e0.png)

https://help.sap.com/viewer/bcf28adaf97342979c4afa49a1ec89c7/2111/en-US/08b46fc196ca4bfa93285e281257a490.html

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dborchers-gc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
