### ISSUE TITLE
Include M365 Business Premium license in this docs page

### ISSUE THREAD

**Issue by smedin4** [MicrosoftDocs/microsoft-365-docs#6994]
Licensing requirements doesn't include the new Microsoft 365 Business Premium license which includes support for Microsoft Defender for Endpoint for SMB customers (<300 seats in the tenant).

According to the following article, macOS devices are also covered by the threat protection from MDE:
https://www.microsoft.com/en-us/security/business/threat-protection/microsoft-defender-business
Reference text: _Cross_ platform: Extend protection across devices for Windows, MacOS, iOS, and _Android._

Another reference: https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/introducing-microsoft-defender-for-business/ba-p/2898701
Reference text: _Defender for Business helps you to protect against cybersecurity threats including malware and ransomware across Windows, macOS, iOS, and Android devices._

Please confirm macOS is also covered and update the license part of this page to include also Microsoft 365 Business Premium license.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e9b530-4f11-0483-ed65-42b23082f9f6
* Version Independent ID: 38263c08-7cab-7d52-552d-e724ede401aa
* Content: [Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-mac.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@smedin4 Thank you for your feedback. We have added M365 Business premium to the license part via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7037

Mac  os is also covered and this has been updated in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @smedin4 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
