### ISSUE TITLE
Cross-tenant mailbox migration

### ISSUE THREAD

**Issue by RichAcevedo1** [MicrosoftDocs/microsoft-365-docs#6995]
i have read through this document and tried to follow it and boy do you guys make it difficult.
so many missing pieces. has anyone that has actually written an article tried to follow these directions on a fresh Tenant?
will the future of this be to run it all via PowerShell?
 will there be a way to monitor the migration via the EAC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@RichAcevedo1 Thank you for your feedback. This feature is still under preview and we are not exactly sure how the future of this would be (PowerShell or eac). I'd recommend you post questions directly on our feedback site( https://feedbackportal.microsoft.com) to get the latest updates and roadmaps about this feature.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @RichAcevedo1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
