### ISSUE TITLE
Despite changing the password policy user is prompted with the default suggestion

### ISSUE THREAD

**Issue by Surajbudhani1994** [MicrosoftDocs/microsoft-365-docs#6999]
We have create and assigned new password policy for the user however they still get the default suggections when resetting the password. Can you please ass a clarity on this

![image](https://user-images.githubusercontent.com/15276380/143413746-368848de-4d9d-4720-9bdd-c61cab7392fa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Surajbudhani1994 Thank you for your feedback. I tested this as well and the change in password policy does not change the default suggestion. If you think a design change is required that can suggest based on password policies, I'd recommend you provide feedback to our Product group via the portal-  https://feedbackportal.microsoft.com

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Surajbudhani1994 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
