### ISSUE TITLE
Video and instructions do not match navigation in Compliance Center

### ISSUE THREAD

**Issue by Smithenstein** [MicrosoftDocs/microsoft-365-docs#7004]
The content on this page and the video do not match the current UI.  There is no classification navigation item with sub items underneath it.  Clicking on Data Classification does not match this in any way.  Very confusing
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70377d79-7c97-fca0-c357-1b520ff91f1f
* Version Independent ID: 5fe80ade-e3b5-ded4-20c4-2c535d8c13c8
* Content: [Create sensitivity labels](https://docs.microsoft.com/en-us/microsoft-365/business-video/create-sensitivity-labels?view=o365-worldwide)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene
![Screenshot 2021-11-25 105157](https://user-images.githubusercontent.com/71409730/143485052-fbebb52d-b5cc-4821-bc53-71adb91dd31c.png)
*
![Screenshot 2021-11-25 105353](https://user-images.githubusercontent.com/71409730/143485317-76e5bb5a-b74a-4abe-831c-43d40d865a48.png)
*

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Smithenstein Thank you for your feedback. For Vidoe changes, I have routed this to the author. The steps on the page have been updated via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7104

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@Smithenstein closing as per PR comment. Thanks
