### ISSUE TITLE
Policy "Turn on script scanning" missing

### ISSUE THREAD

**Issue by vTa47** [MicrosoftDocs/microsoft-365-docs#7005]
Hello,

I downloaded the latest security baseline for Windows Server 2022. In the Group Policy Report for the MSFT Defender Antivirus Server 2022, there is a parameter "Turn on script scanning" (supported from Server 2012/Win8) in the Real-time Protection section which is missing from the latest WindowsDefender.admx version. This parameter is added in Security Baseline for server 2022 but was not for Security Baseline for Server 2019.

So, this parameter must still exist for servers ? There is something to update in the latest ADMX ?
You don't mention this parameter in this documentation page.

Thank you in advance for your reply.

Kind regards,
Téva

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67ba09a9-8323-a87f-83e7-61590de89e36
* Version Independent ID: 41962064-f36a-f283-55d4-721c4c457cac
* Content: [Configure Microsoft Defender Antivirus with Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/use-group-policy-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/use-group-policy-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/use-group-policy-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
@yogkumgit I have reached out to the product team. Will post an update here soon.

**Comment by denisebmsft** [comment]
Thank you @vTa47 for raising this issue. And thank you @yogkumgit for your help. I have updated the content, and the revisions will be live later today. Updates include a link to script scanning information (https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender) and the latest Group Policy Reference Spreadsheets. (Win 10: https://www.microsoft.com/download/details.aspx?id=101451; Win 11: https://www.microsoft.com/download/details.aspx?id=103506)
