### ISSUE TITLE
edit connections phrase

### ISSUE THREAD

**Issue by LeoGoGarcia** [MicrosoftDocs/microsoft-365-docs#7012]
[Enter feedback here]

Hello, 

in the phrase "Once a user confirms their connection to a topic, the user can make edits to the topic page to curate their connection. For example, they can provide more information about their connection to the topic." we suppose a READER can curate (edit his/her connection) once he/she validates the connection itself. It's not true (or I'm not getting it done). 

Can you review please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ec5941-a94f-b7be-75fc-ab15e221ca66
* Version Independent ID: 0077e670-2e77-5d97-02f7-78653c2d69a0
* Content: [Topic center overview in Microsoft Viva Topics](https://docs.microsoft.com/en-us/microsoft-365/knowledge/topic-center-overview#home-page)
* Content Source: [microsoft-365/knowledge/topic-center-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/knowledge/topic-center-overview.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by yogkumgit** [comment]
@chuckedmonson Please help us in resolving this issue. Thanks

**Comment by chuckedmonson** [comment]
@LeoGoGarcia -- Will investigate and get back to you about the inquiry. Thank you.

**Comment by chuckedmonson** [comment]
@LeoGoGarcia -- You need to have edit permissions to update the "Pinned People" section. The best approach is to enable editing for everyone so you can truly crowdsource. If that's not an option, contact the last editor, and they can remove. Thank you for your feedback, and we are working on improving this experience.
