### ISSUE TITLE
Guests Shadow mailbox experience

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#7014]
Can you add a new section to make it clearer about guests having a shadow mailbox and what their experience is.
It is mentioned under meeting and external user that 
'If an external user joins by using a guest account in your tenant, this user has a shadow mailbox that can be subject to your organization's retention policy for Teams. Any messages from the meeting are stored in both your users' mailbox and the shadow mailbox.'

However when you ready page https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide under known configuration issues it states

'When you select Edit for the Teams chats location, you might see guests and non-mailbox users. Retention policies aren't designed for these users, so don't select them.'
This seems to conflict with the text on this page.

A guest user has a shadow mailbox is created which stores the compliance copies of chats as per internal users.

Is the Guest's Azure AD B2B account is subject to retention policies. I know I can see guest users can been seen when searching under the retention policies user scope. However it is not clear whether 

Also can you confirm what happens when a guest's Azure AD B2B account gets deleted. I am assuming that their shadow mailbox goes through the same deletion and retention policies in the same manner that an when a user leaves the organization. 

Also if guests are in scope of retention polices can we create adaptive scopes for them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide#whats-included-for-retention-and-deletion)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
After investigating, shadow mailboxes aren't supported for retention, even though they might be included in an org-wide policy.  I've updated the text on this to clarify.  Shadow mailboxes can be supported by eDiscovery, which is why we documented where copies of guest messages are stored.

**Comment by yogkumgit** [comment]
@nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
