### ISSUE TITLE
What happens if a Microsoft 365 group is deleted via an expiration policy and has a retention policy applied

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#7015]
Can I confirm the behaviour for What happens if a Microsoft 365 group is deleted after a policy is applied when the Azure AD Group Expiration policy is applied.

With the Group expiration policy if the group is not renewed within the time period the group is deleted.
If the group is not subject to a retention policy then it is soft deleted and can be restored for 30 days.

However if the group has a retention policy and the group is expired then is will align to the rules as described on the is page. Does that mean that the group cannot be restored within the soft delete window directly. You need to submit a support ticket to Microsoft.
This seems to conflict with some of the information on page  https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-lifecycle  as it mentions that the groups is expired it is deleted and the owner gets an email  to state the group can be restored within 30 days of its deletion by selecting Restore group or by using PowerShell cmdlets

![image](https://user-images.githubusercontent.com/69439002/143694709-4d364eb0-8048-4b4b-98bc-98acf3bc881b.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 592d6717-d670-14a8-acbe-c648958ca208
* Version Independent ID: 9bc46fd9-50e1-1e58-4852-22068e2980ae
* Content: [Configure retention settings to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide#configuration-information-for-adaptive-scopes)
* Content Source: [microsoft-365/compliance/retention-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
I'm not sure I understand the question but we have a section specific to what happens when the group is deleted (which includes group expiration): https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide#what-happens-if-a-microsoft-365-group-is-deleted-after-a-policy-is-applied

**Comment by yogkumgit** [comment]
@nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
