### ISSUE TITLE
Discrepancies for Service Encryption Key 

### ISSUE THREAD

**Issue by ChristopheLux** [MicrosoftDocs/microsoft-365-docs#7017]
Hello 

in this page mentioned here https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-risks-and-protections?view=o365-worldwide you are saying that Service Encryption is on the roadmap for Exchange 

AND in this one
https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-service-encryption?view=o365-worldwide

You are saying it is used for Exchange Online....

Which one is correct
Thanks in advance

In case of Service Encryption with MMK is there any way in PowerShell or Graph API to check the default DEP?

Thanks a lot again in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b0b9911-441e-68b7-e0dd-472f8e66b0ac
* Version Independent ID: 3760032b-5f82-b058-471f-97b4387d7bcc
* Content: [Encryption Risks and Protections - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-risks-and-protections?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/office-365-encryption-risks-and-protections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-encryption-risks-and-protections.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@ChristopheLux Thank you for your feedback. The feature is available in Exchange online, we have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7035

To return all DEPs in your organization, run the Get-DataEncryptionPolicy cmdlet without any parameters.

Thanks
Sri

**Comment by ChristopheLux** [comment]
Thanks @msbemba 
If there is only for the moment the standard MMK DEP in place the command will return nothing?

Best Regards
Chris

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChristopheLux Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
