### ISSUE TITLE
Document Library default view changed by SharePoint Syntex during push to libraries

### ISSUE THREAD

**Issue by CallumCrowley** [MicrosoftDocs/microsoft-365-docs#7019]
**Issue**

When content types are pushed to document libraries in a hub or associated sites, a series of views are created in the library (one for each content type pushed to the library).

SharePoint Syntex is changing the library's default view to one of these automatically created views. This is not described in the documentation. A user for example may want the "All documents" view to be the default view but when Syntex pushed the views to the library it will change the default view to one of the automatically created Syntex views. Feedback I have received from users is that they would want their choice of default view to be respected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4760c99-cd14-4733-1655-786ab727fa6e
* Version Independent ID: 4ef91a24-bf3a-3d0b-da44-f153b788df10
* Content: [Push content types to a hub](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/push-content-type-to-hub)
* Content Source: [microsoft-365/contentunderstanding/push-content-type-to-hub.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/push-content-type-to-hub.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@CallumCrowley Thank you for your feedback. For the product group or owners to make these changes, this feedback needs to be directed to them. I recommend you submit this feedback directly on our feedback portal -https://feedbackportal.microsoft.com so that you will get a response directly from the team and also get updates on when this feature is changed.

Hope this helps!

Tanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@CallumCrowley I have added this to our documentation via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7103


Once the author approves, the changes will be live.

Thanks
Sri

**Comment by CallumCrowley** [comment]
@msbemba is there any information regarding which view will be set as the default? For example, if 5 different content types are pushed to a library which corresponding view would be set as the default view?

**Comment by msbemba** [comment]
@CallumCrowley  I had the same question and posted this to the author and PG. I'll provide you with an update as soon as I receive one.

Thanks
Sri

**Comment by CallumCrowley** [comment]
Thanks @msbemba, the more information regarding the automatically created views the better. Some end users would prefer them not be created at all so understanding their purpose may help.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CallumCrowley Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by CallumCrowley** [comment]
@yogkumgit this is still an issue unfortunately. The update does not include any information on which view gets set to the default view when multiple views are automatically created in a library. @msbemba has mentioned this in the comments.

Please reopen this issue since the documentation does not provide enough clarity on the automatically created views in general.

**Comment by yogkumgit** [comment]
@msbemba Please review

**Comment by msbemba** [comment]
@yogkumgit  I have emailed the author and will provide an update once I have more information.

Thanks
Sri

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Email sent on 10 Dec with query.

**Comment by msbemba** [comment]
@CallumCrowley We have recieved the below update from the author/PG. I'll update the document accordingly.

When content types are pushed to the hub, we do create a new view for the content type and set it as the default view in the libraries it is pushed to. If there are multiple content types pushed to the same library, then the latest one (based on the order of the user’s action of pushing those content types to the hub this library belongs to) is what will be set as the default view. So if CT1 is pushed first, followed by CT2, the library will have views for both CT1 and CT2, and it will be the CT2 view that is set as default.

Thanks 
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CallumCrowley Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
