### ISSUE TITLE
Unable to Edit or Remove Custom Tile

### ISSUE THREAD

**Issue by tnordin** [MicrosoftDocs/microsoft-365-docs#7020]
Per the instructions on this page to Edit or Delete a Custom Tile, I should

"On the Organization profile page, next to Add custom tiles for your organization, select Edit."

I do not see Edit option, I only see Add Custom Tile.  

Also, do not see where I have the ability to delete a custom tile.

Thank you!
![Custom App Tile Launcher](https://user-images.githubusercontent.com/94127847/143921517-d0e6d485-c128-48e8-9194-9ace960bc850.PNG)
![Organization Profile](https://user-images.githubusercontent.com/94127847/143921520-3b441d2c-fb3e-4d99-8815-73f767462772.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9488caf7-b791-3002-8749-7fdc4b2ec8b3
* Version Independent ID: 08e61eb0-7bcd-f449-46ef-17e209138a8e
* Content: [Add custom tiles to the app launcher - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/manage/customize-the-app-launcher?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/customize-the-app-launcher.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/customize-the-app-launcher.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@tnordin Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7036

The Edit custom tile option is available when you select Custom app launcher tiles-->Click on the three dots next to the tile that you want to edit.

![image](https://user-images.githubusercontent.com/45987684/144232915-c72c0fc6-334e-43a0-aedc-5da8f452f74e.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tnordin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
