### ISSUE TITLE
Incorrect info in purple note regarding certificate-based authentication on iOS

### ISSUE THREAD

**Issue by dmennis** [MicrosoftDocs/microsoft-365-docs#7022]
The purple box Note about Edge for iOS and Android are incorrect as of iOS 14.2. Third-party apps CAN access client-certificates from the keychain and have access to the public key in the keychain that points to an external smart card. Native Apple apps,  and any third-party app implementing SFSafariViewController,  ASWebAuthenticationSession, or WKWebView (requires a few lines of code) all have access to view client certificates stored on the iOS device. All without the need for an MDM profile. For any clients implementing the latest MSAL library with modern authentication enabled, these apps automatically support certificate-based authentication when using the default system browser (ASWebAuthenticationSession) set by the MSAL library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c62d861d-b54f-a023-ce0c-11e858660301
* Version Independent ID: 3c49dd2d-22c1-3755-4a46-f7adcaa4f1b2
* Content: [Microsoft 365 Client App Support: Certificate-based Authentication - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-client-support-certificate-based-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-client-support-certificate-based-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-client-support-certificate-based-authentication.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by dmennis** [comment]
https://developer.apple.com/documentation/cryptotokenkit/using_cryptographic_assets_stored_on_a_smart_card

**Comment by msbemba** [comment]
@dmennis Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7082

Once the author approves the PR, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@dmennis Author confirmed that this topic is deprecated. Closing
