### ISSUE TITLE
Microsoft 365 Multi-Geo Licensing

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/microsoft-365-docs#7023]
Hi team

Could you please more explicitly document Microsoft 365 Multi-Geo licensing requirements for resource (room/equipment) and shared mailboxes?

[This 3 years old blog post](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/multi-geo-in-exchange-online-and-onedrive/ba-p/182710) says we must license resource and shared mailboxes

"Licensing" section in this article says if we remove licenses, then mailbox is not moved back to central region.

Sounds like we need to only temporary license resource and shared mailboxes, verify they are in the correct region, and then licenses can be removed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32b41c7e-29cd-eb5b-36b2-738b3babd08f
* Version Independent ID: 22eda3f7-1c04-b3b0-95fd-3474b3f991b2
* Content: [Microsoft 365 Multi-Geo - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-multi-geo?view=o365-worldwide#licensing)
* Content Source: [microsoft-365/enterprise/microsoft-365-multi-geo.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-multi-geo.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@WayneEwington can you help?

**Comment by WayneEwington** [comment]
@Brian ***@***.***> This looks like an exchange question - Can you help answer/clarify this?


Thanks, Wayne

**Comment by shivtorov** [comment]
This question is about "Multi-Geo Capabilities in Office 365" license SKU. Specifically, this docs article does not outline Multi-Geo licensing requirements for resource accounts. Thus, the request to update the article.

1. Do we have to assign "Multi-Geo Capabilities in Office 365" license SKU to Azure AD user accounts (that represent resource/shared mailboxes in Exchange Online) in order to have these mailboxes moved to Geo location specified in PDL attribute of Azure AD user? (Normally, these accounts are not licensed with Exchange Online licenses)
2. When we remove "Multi-Geo Capabilities in Office 365" license SKU from Azure AD user accounts (that represent resource/shared mailboxes in Exchange Online), will the mailboxes stay in the Geo location.

**Comment by yogkumgit** [comment]
@WayneEwington Please reply. Thanks

**Comment by WayneEwington** [comment]
This question is related to Exchange Online (and not SharePoint Online) and should really be directed @briandaymsft as previously stated.

**Comment by briandaymsft** [comment]
This is a challenging area, and more documentation would likely do little to provide clarity.

Resource/Room mailboxes are required to have a MG license to be compliant as far as licensing goes. However, the licensing system will not allow the customer to assign these mailboxes a MG license as they usually do not have the necessary pre-req license assigned to them which blocks the assignment. To date we have told customers to keep a sufficient # MG of licenses in reserve in their license pool to cover however many resource/room mailboxes they have moved out of their home geo. It isn't the best situation but all we have right now.

**Comment by yogkumgit** [comment]
@shivtorov Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
