### ISSUE TITLE
No Audit option available

### ISSUE THREAD

**Issue by kishan729g** [MicrosoftDocs/microsoft-365-docs#7024]
In compliance manager I don't have a 'Audit' option on left menu - even if I do show all. Below is what I see:

![image](https://user-images.githubusercontent.com/95279430/144018089-9ff472ea-4022-405f-b230-bded5f33bbd8.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5432a60a-d95c-eafc-bed8-9b98e2331b6c
* Version Independent ID: 204f8092-ee37-e130-bde0-7643751fc642
* Content: [Set up Basic Audit in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-basic-audit?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-basic-audit.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-basic-audit.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kishan729g Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
