### ISSUE TITLE
SharePoint list items with retention label applied are not being deleted

### ISSUE THREAD

**Issue by Ian-Hawk-Hawkins** [MicrosoftDocs/microsoft-365-docs#7025]
Hi,

We have applied automatic retention labels to SharePoint lists to automatically delete list items 6 months after they are created.  The list items are showing they have the retention label applied to them.

However, the items older than 6 months are not being deleted.  We have left it over 10 days, in case there was any issues with the scheduled job that runs, but they are not being deleted.

Within the Advanced list settings, the option for "Allow items from this list to appear in search results?" is set to No, as we don't want the list items appearing in search.  However, we have noticed if we change this setting to "Yes", then after a few days the old items seem to be deleted.

I can't see anywhere in the documentation that says "Allow items from this list to appear in search results?" has to be enabled for retention labels to work.  Does this option have to be selected?

Many thanks for confirming how this should be configured to work,
Ian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a4716f6-31db-306c-2804-56591e3af7e6
* Version Independent ID: 8dfc13ff-3b6a-ba25-2911-db7a3dcd2e8a
* Content: [Automatically apply a retention label to retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-retention-labels-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-retention-labels-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-retention-labels-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Ian-Hawk-Hawkins Yes, apparently this is correct - and new to me, today confirmed with engineering.  Today (and this might change in the future) when a list item is labeled but excluded from search, it will be retained but not deleted.  An odd variation, now added to this section where we list support statements: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide#whats-included-for-retention-and-deletion 

When retention labels are applied to supported list items, they will always be retained according to the retention settings, but not deleted if they are hidden from search.

**Comment by yogkumgit** [comment]
@Ian-Hawk-Hawkins Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
