### ISSUE TITLE
Actionable Release Notes for Microsoft Defender for Endpoint on Linux

### ISSUE THREAD

**Issue by DGG-IT** [MicrosoftDocs/microsoft-365-docs#7028]
The Microsoft Defender for Endpoint for Linux Version release notes here do not provide much useful information to teams which need to closely track changes to their environment, head off potential issues, track resolution of previously noted issues, etc.

Please provide more meaningful release beyond "Performance improvements & bug fixes".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38276f58-2d15-9f05-cd4a-87646ec11b27
* Version Independent ID: 12f1b3df-123f-7005-9f68-38ab20df09cd
* Content: [What's new in Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-whatsnew?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-whatsnew.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-whatsnew.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us resolving this issue. Thanks
