### ISSUE TITLE
Rule Package 'xxx' already exists when trying tu upload an modified XML rule package 

### ISSUE THREAD

**Issue by mezzofix** [MicrosoftDocs/microsoft-365-docs#703]
From the document:
> The Version element is also important. When you upload your rule package for the first time, Office 365 notes the version number. Later, if you update the rule package and upload a new version, make sure to update the version number or Office 365 won't deploy the rule package.
But when trying to upload a modified XML it gives an error that the rule package already exists! Do I have to change the RulePack Id as well?? 

```

PS C:\Users\xxxxx> New-DlpSensitiveInformationTypeRulePackage -FileData ([Byte[]]$(Get-Content -Path "C:\Users\xxxxx\Desktop\Adam_custom2_v1.xml" -Encoding Byte -ReadCount 0))

Rule Package 'F6F9528E-DFEA-4020-8FAC-D04039BF4043' already exists.

    + CategoryInfo          : InvalidData: (:) [New-DlpSensitiv...TypeRulePackage], RulePackageAlreadyExistsException

    + FullyQualifiedErrorId : [Server=BN3NAM04WS014,RequestId=4d4e7238-062b-4c8f-a9bf-8806d1dda141,TimeStamp=11/7/2019 9:46:26 PM] [FailureCategory=Cmdlet-RulePackageAlreadyExistsException] 65E510E7,Microsoft.Office.CompliancePolicy.Tasks.NewDlpSensitiveInformationTypeRulePackage

    + PSComputerName        : nam04b.ps.compliance.protection.outlook.com
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d6af897-cba3-dc5c-beb1-4a650fadbaea
* Version Independent ID: 12d1e00e-36c2-71a1-0632-844455b1d00c
* Content: [Create a custom sensitive information type in Security & Compliance Center PowerShell](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell)
* Content Source: [microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by markjjo** [comment]
@mezzofix Have you tried to use Set-DlpSensitiveInformationTypeRulePackage to upload the modified rule package?

See Step 3 here: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell#modify-a-custom-sensitive-information-type

**Comment by mezzofix** [comment]
@markjjo Yep, that worked. Thank you! Just one more question. Should I generate a new GUID for Publisher id or can I leave it as the one that is in the exported XML for the default rule package?

**Comment by markjjo** [comment]
@mezzofix Glad that worked. I'm not a DLP or sensitive info type guy; I just noticed you were using a New-* cmdlet to update an existing object. ;-)

But, glancing through the topic, I am guessing that you don't need to update that GUID. However, the topic does state that you should update the version if you update the rule package: "The Version element is also important. When you upload your rule package for the first time, Office 365 notes the version number. Later, if you update the rule package and upload a new version, make sure to update the version number or Office 365 won't deploy the rule package." - The topic doesn't say anything that I can see about updating the GUID for the rule pack. See: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell#other-rule-package-markup-rulepack-guid

Of course, you should probably test to make sure things are working as expected.

HTH
