### ISSUE TITLE
You can also create groups in a local geo via Graph API Create Group

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#7034]
In addition to creating groups in a specific using the SharePoint Admin Center or PowerShell you can also create a unified Group in a specific geo using Graph API Create Group
Then in the HTTP Request body set the preferredDataLocation to the relevant geo location code

Example

POST https://graph.microsoft.com/v1.0/groups
Content-type: application/json

{
  "description": "Multi-geo-group name",
  "displayName": "Multi-Geo",
  "groupTypes": [
    "Unified"
  ],
  "mailEnabled": true,
  "mailNickname": "Multi-Geo",
  "securityEnabled": false,
      "owners@odata.bind": [
      "https://graph.microsoft.com/v1.0/users/XXXXXX"
      ],
   "preferredDataLocation": "GBR"
}

reference link https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100a5943-5329-63f6-1fef-5724b29d162a
* Version Independent ID: 7819933f-ed32-98bf-d0b2-b088fbbce067
* Content: [Create a Microsoft 365 Group with a specific preferred data location - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-add-group-with-pdl?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/multi-geo-add-group-with-pdl.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/multi-geo-add-group-with-pdl.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. I have added the document to related topics via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7097

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
