### ISSUE TITLE
Notify users from within the portal

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#7040]
Does anyone have an example message sent to the user when an admin marks this as "phishing" and "no threat found"? What email address does the email come from?

The reported message will be marked as a false positive or a false negative. An email notification be sent automatically from within the portal to the user who reported the message.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide#notify-users-from-within-the-portal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Manage submissions - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@HarrisburgUSysAdmin Thank you for your feedback. I'm currently testing this and will update the document once I have more information.

Thanks
Sri

**Comment by msbemba** [comment]
@HarrisburgUSysAdmin I was able to get a response from submissions@messaging.microsoft.com. It looks something like this

![image](https://user-images.githubusercontent.com/45987684/146056774-cab45e40-0dcf-4026-aad3-2e0ea4ac2e5f.png)


If your users are not notified, I'd request you to contact support via the need help option in the admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @HarrisburgUSysAdmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by HarrisburgUSysAdmin** [comment]
@msbemba - Thank you very much.
