### ISSUE TITLE
Remove the last line in this article

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#7048]
The last line "For more information, see Create safe sender lists in EOP." links to this very same article and is redundant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hudish, fixed. In the future, you too can make fixes like this without opening an Issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
