### ISSUE TITLE
PowerShell ease of use

### ISSUE THREAD

**Issue by RyanG314** [MicrosoftDocs/microsoft-365-docs#7049]
Regarding the published documentation stating:
$Mailboxes = Get-Mailbox -ResultSize Unlimited -Filter {RecipientTypeDetails -eq "UserMailbox"}
these parameters fail at the point of filter.
I've found that: $Mailboxes = Get-Mailbox "mailbox@domain.com" -ResultSize Unlimited
sets $Mailboxes correctly so you are able to run:
$Mailboxes.identity | Start-ManagedFolderAssistant
and enact changes to retention/deletion policies immediately. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Set up an archive and deletion policy for mailboxes in your organization - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@RyanG314 Thanks for feedback. I can't repro your issue.  I ran the command and it loads the variable with all user mailboxes in the org. But it looks like in your situation you found a workaround. Obviously, goal is to get a list of all mailboxes so that you can run the MFA against the list.
