### ISSUE TITLE
Can't Use Information Barrier Policies

### ISSUE THREAD

**Issue by KareemAve** [MicrosoftDocs/microsoft-365-docs#7050]
Information barrier policies in our tenant cannot be applied. The error message "our request failed to complete. Please retry. Error Details:

 Microsoft.Exchange.Management.Tasks.AsymmetricPoliciesException, IB Policies defined on segment% 2281f7b21a-4eb6-4b83-81d4-62eea8c464d0% 22 and% 22b355de1a-9a7a- appears here. 407f-b61e-76cd4f654765% 22 are not symmetric. Please ensure that the policies are defined two-ways. For example, if there is a policy where Segment1 cannot communicate with Segment2, then there must be another policy where Segment2 cannot communicate with Segment1. " 

Furthermore, the InformationBarrierPolicy-ApplicationStatus has been in the "CancelInProgress" status for more than two hours

Here are the commands i use for more info 

https://kareemave-my.sharepoint.com/:t:/g/personal/kareema_avestar_xyz/EVE8DJ-BfWRJtVrwYE9D-ooBlVpJxuSMm26lkmjBVKkDAw?e=XyDR47

**Comment by msbemba** [comment]
@KareemAve Thank you for your feedback. Since this is a support request, I recommend you contact Microsoft support via the need help section on the M365 admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @KareemAve 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
