### ISSUE TITLE
Steps for Configuring Simulation Mode are Incomplete

### ISSUE THREAD

**Issue by AveryBaker** [MicrosoftDocs/microsoft-365-docs#7053]
To have an AutoSenstivityLabelPolicy in simulation mode start running the simulation you must first run this cmdlet:
**set-autosensitivitylabelpolicy -identity MyPolicy -startsimulation $true**

This step is not included in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Automatically apply a sensitivity label to content in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@AveryBaker  If you are following the instructions on this page (use the UI to create auto-labeling policies), you should not have to run this PowerShell cmdlet.  Were you told otherwise?

**Comment by yogkumgit** [comment]
@AveryBaker Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
