### ISSUE TITLE
Clarifying how Safe links works

### ISSUE THREAD

**Issue by vianeyhm** [MicrosoftDocs/microsoft-365-docs#7058]
Hello team;

Based on this documentation, it is not clear if Safe Links uses a sandbox to evaluate the URLs received thru email, in an Office document or Teams chat, I may assume that yes based on the fact that any time the user clicks a URL, Microsoft open it and analyze it (in real-time) but not really sure if it works like that, could be good to clarify it in this documentation based on the fact that some customers are asking us about it. Thanks in advance!
Vianey

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@vianeyhm, both Safe Links and Safe Attachments use a hypervisor/sandbox environment to detonate the links/attachments to see what happens.

So what's the question?
