### ISSUE TITLE
Bring us localized end-user spam notifications!

### ISSUE THREAD

**Issue by marc-fom** [MicrosoftDocs/microsoft-365-docs#706]
We need notifications that follow the user's preferred language. How do you expect that in a company with worldwide presence everyone can read and understand english?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7b5bbb4-4c14-9637-6834-02f0e3e95261
* Version Independent ID: da93570d-ecbc-d0c3-63c2-7445f7ba29b3
* Content: [Configure end-user spam notifications in Exchange Online](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-exchange-online)
* Content Source: [microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-exchange-online.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-end-user-spam-notifications-in-exchange-online.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@marc-fom  - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature request on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
