### ISSUE TITLE
IE Report Internal or External users

### ISSUE THREAD

**Issue by fajr365** [MicrosoftDocs/microsoft-365-docs#7060]
Looking for more detailed information on the IE usage report. Like the number of users that are on network access vs Off network access. This would help identify if the users IE usage was from a corp device or personal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f954abb9-d978-b70d-c136-623a76317ddc
* Version Independent ID: d4a88bcd-ac54-ca82-9b9a-0e22da92b74b
* Content: [Microsoft 365 Reports in the admin center - Microsoft browser usage - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/browser-usage-report?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/browser-usage-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/browser-usage-report.md)
* Service: **o365-administration**
* GitHub Login: @sarahwxy
* Microsoft Alias: **waxiaoyu**

**Comment by msbemba** [comment]
@fajr365 Thank you for your feedback. That is a good idea and I'd recommend you to post it on our product feedback portal where the product group can look into it and provide you an update when they implement the idea.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@fajr365  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
