### ISSUE TITLE
log name is incorrect - is "Microsoft-Windows-Windows Defender/Operational" [notice the space between Windows Defender]

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/microsoft-365-docs#7062]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c453008-4ccc-186c-b6da-64536d62c89c
* Version Independent ID: a00180f1-4f69-956f-cd92-77b7bf21fc16
* Content: [Evaluate network protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluate-network-protection?view=o365-worldwide#review-network-protection-events-in-windows-event-viewer)
* Content Source: [microsoft-365/security/defender-endpoint/evaluate-network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/evaluate-network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@anwarmahmood1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7090

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @anwarmahmood1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
