### ISSUE TITLE
Enabling Bi-Directional (Full-on) Access Changes to Disabled (by design)

### ISSUE THREAD

**Issue by lccctemp** [MicrosoftDocs/microsoft-365-docs#7066]
Under "Monitor all files in Real time protection", we are instructed to set "Configure monitoring for incoming and outgoing file and program activity" to "Enabled" with the option "bi-directional (full-on access)" but when we do, GPM Editor shows the policy state as "Disabled". 

After researching this further, I found this Q&A which states that this is by design. The setting is just badly worded as pointed out here: https://docs.microsoft.com/en-us/answers/questions/492031/windows-defender-real-time-pretection-configuratio.html. 

Should this note be added to the documentation for clarity? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523651c3-a318-2369-6892-d13e04991596
* Version Independent ID: 624c5e05-f87d-1bd4-bc87-bd55dcac1d86
* Content: [Onboard Windows devices to Microsoft Defender for Endpoint via Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-gp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@lccctemp Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7101

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lccctemp Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
