### ISSUE TITLE
Microsoft Defender Antivirus > Signature Updates Path Not Found

### ISSUE THREAD

**Issue by lccctemp** [MicrosoftDocs/microsoft-365-docs#7067]
In the "Check for signature update" section, the screen shot shows a setting called "Specify the interval to check for definition updates" within the path "**Windows** Defender Antivirus > **Signature** Updates", but this path does not exist. 

Is this supposed to be "Specify the interval at which to check for **security intelligence** updates" within the path "Computer Configuration > Policies > Administrative Templates > Windows Components > **Microsoft** Defender Antivirus > **Security Intelligence** Updates" instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523651c3-a318-2369-6892-d13e04991596
* Version Independent ID: 624c5e05-f87d-1bd4-bc87-bd55dcac1d86
* Content: [Onboard Windows devices to Microsoft Defender for Endpoint via Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-gp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@lccctemp Thank you for your feedback. Yes, You are correct. It is Security Intelligence Updates instead of Signature Updates. I'll get the document updated.


Thanks
Sri

**Comment by msbemba** [comment]
@lccctemp Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7182

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lccctemp Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by lccctemp** [comment]
Hi Yogesh, 

I see that you closed this ticket but as of today, this document has not 
been updated to show Security Intelligence Updates instead of Signature 
Updates. Was this closed because perhaps it's in a queue to be updated?

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide



-------------------------------------------------
Sandra Norton
Local Area Network Manager
Luzerne County Community College
521 Trailblazer Drive
Nanticoke, PA 18634
Ph: 570-740-0754
Fx: 570-740-0760

The trouble with most of us is that we would rather be ruined by praise 
than saved by criticism. 
- Norman Vincent Peale



From:   "Yogesh Kumar" ***@***.***>
To:     "MicrosoftDocs/microsoft-365-docs" 
***@***.***>
Cc:     "lccctemp" ***@***.***>, "Mention" 
***@***.***>
Date:   01/06/2022 10:06 AM
Subject:        [EXTERNAL]  Re: [MicrosoftDocs/microsoft-365-docs] 
Microsoft Defender Antivirus > Signature Updates Path Not Found (Issue 
#7067)



Closed #7067.
?
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>




The contents of this email message and any attachments originating from Luzerne County Community College's email system are for the intended recipients only and may contain confidential and/or privileged information legally protected from disclosure.   If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by replying to the email and then deleting the message and any attachments.   Also, if you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

Luzerne County Community College
"Northeastern Pennsylvania's Community College"
www.luzerne.edu
800-377-5222
