### ISSUE TITLE
Clarify if Get-Addin is available for GCC customers

### ISSUE THREAD

**Issue by DanyHebert** [MicrosoftDocs/microsoft-365-docs#7069]
Hello,

We would like to clarify if the Get-Addin option is available for GCC customers. According to MS support, this is not and organizations must be using Centralized Deployment. However there is no clear mention of this on any public facing MS documentation.

Would it be possible to confirm this information and clarify the documentation if required? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@DanyHebert Thank you for your feedback. This document pertains to Centralized deployment and it is available on all M365 tenants. Whereas for Get-addins we are not sure if this is available on GCC tenants. I recommend you leave feedback 
 here - https://feedbackportal.microsoft.com. The feedback is routed to the appropriate team who can confirm and update you accordingly.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@DanyHebert  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
