### ISSUE TITLE
CAT:GIMP and CAT:AMP missing

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#707]
Graph based intelligence and common attachment block respectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@aldoug  - Thank you for submitting feedback.

Can you please share what specific issue you have with this doc? Or are you having some technical issues which requires technical support?

If you have some issues with this doc, we would really appreciate if you are able to help by providing more details as to what should be edited and/or included. Thank you!

**Comment by aldoug** [comment]
Hi Joyce

The 2 categories I mentioned are category descriptions (headers) that are missing from the doc. I believe PG should be asked to review the article and add any categories that are missing (as there may be other ones I am not aware of)

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by aldoug** [comment]
Hi @mypil. Feel free to reach out to me direct via my alias if it's easier

**Comment by mypil** [comment]
@aldoug - Is this somewhat related to issue #736 which you opened just today?

I can see that you may have some relevant information that you can add to this topic that would make this doc better so it would really be awesome if you could share your expertise. Same with the other issue, can you possibly help us by suggesting how this content could be edited to incorporate your feedback? If you could create the PR to update the doc then it would be really great. Thank you.

**Comment by aldoug** [comment]
Hi guys

Sure

The info here is some new headers we see in support for the section

https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/anti-spam-message-headers

CAT:
The category of protection policy, applied to the message:
MALW: Malware
PHSH: Phishing
HSPM: High confidence spam
SPOOF: Spoofing
SPM: Spam
BULK: Bulk
DIMP: Domain Impersonation
UIMP: User Impersonation
Potentially, an incoming message may be flagged by multiple forms of protection and multiple detection scans. Policies have different priorities, and the policy with the highest priority will apply. See What policy applies when multiple protection methods and detection scans run on your email<https://docs.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined>.


The new ones are

CAT:GIMP Graph based Impersonation

And

CAT:AMP (Which I am not 100% sure on what it relates to at this time, though appears to be malware related, following up)

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by MaratMussabekov** [comment]
Hello @aldoug ,
category GIMP was already added,
but as to AMP, I cannot find any reference about this category. Could please advise?
**CAT:AMP (Which I am not 100% sure on what it relates to at this time, though appears to be malware related, following up)** - as it is malware-related, it should be either Common Attachment Types Filter or Malware Zero-hour Auto Purge, correct?
Thank you

**Comment by aldoug** [comment]
Hi there Marat

Unfortunately I would need engineering to advise

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
aldoug@microsoft.com<mailto:aldoug@microsoft.com>
Working hours: Monday – Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers (jedronke@microsoft.com<mailto:jedronke@microsoft.com>)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by mypil** [comment]
@aldoug - Do you have any updates from the engineering team? We would like to get your suggestions on what should be added/edited in this doc. Please advise so we can let @MaratMussabekov create a PR for this. Thank you.

**Comment by mypil** [comment]
@aldoug - We appreciate any feedback that improves the content in the Microsoft docs but we haven't received any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.

**Comment by aldoug** [comment]
@mypil - I'd like to see the CAT:AMP added, but I have no method of getting the information. I do not have a channel open to me to do so. Do you have any contacts in engineering?

**Comment by mypil** [comment]
@aldoug - We have engaged the author regarding this issue and tagged her on the new issue #1202  you opened. Thank you.
