### ISSUE TITLE
Typos/unclear wording

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/microsoft-365-docs#708]
I believe there are typos, missing words, or this paragraph needs to be re-written for clarity: "DMARC prevents spoofing examining a message's sender - the one that the user sees in their email client (in the examples above, this is service.outlook.com, outlook.com, and accountprotection.microsoft.com) - with the domain that passed SPF or DKIM. That is, the domain that the user sees has been authenticated and is therefore not spoofed. For a more complete discussion, see the section "Understanding why email authentication is not always enough to stop spoofing" later on in this article." Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e130b60f-b97b-cfb1-4857-a08e79fdfd59
* Version Independent ID: 19e405c4-a6c0-7c75-b925-ff9637f1889e
* Content: [Anti-spoofing protection in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spoofing-protection)
* Content Source: [microsoft-365/security/office-365-security/anti-spoofing-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spoofing-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@ckssaas  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
PR #731  has been created by @JohanFreelancer9 to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
