### ISSUE TITLE
''''

### ISSUE THREAD

**Issue by ananalek** [MicrosoftDocs/microsoft-365-docs#7084]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 4eabafd4-aa2e-d159-dad1-47a0e7d15b02
* Version Independent ID: 4a9e22e9-eafb-bac6-851a-b1544dbf0b9b
* Content: [Upgrade Windows 10 Home to Windows 10 Pro](https://docs.microsoft.com/th-th/microsoft-365/business-video/upgrade?view=o365-worldwide)
* Content Source: [microsoft-365/business-video/upgrade.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-video/upgrade.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by ananalek** [comment]
ID: 4eabafd4-aa2e-d159-dad1-47a0e7d15b02
รุ่นอิสระ ID: 4a9e22e9-eafb-bac6-851a-b1544dbf0b9b
เนื้อหา: อัปเกรด Windows 10 Home เป็น Windows 10 Pro
ที่มาของเนื้อหา: microsoft-365/business-video/upgrade.md
บริการ: o365-administration
GitHub เข้าสู่ระบบ: @cmcatee-MSFT
Microsoft นามแฝง: cmcatee

**Comment by yogkumgit** [comment]
@ananalek What is your feedback to improve the documentation.

**Comment by yogkumgit** [comment]
@ananalek We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
