### ISSUE TITLE
Request to add onboard cautions using local script

### ISSUE THREAD

**Issue by kahosoka** [MicrosoftDocs/microsoft-365-docs#7087]
[Enter feedback here]
Hi Team,

There are parts of Microsoft Defender for Endpoint that I feel are missing in explaining how to handle local scripts.
Therefore, I would like to correct the contents that are currently written in Docs.

・Additional Request Contents
1.Could you explain in detail why onboard using local scripts is limited to a maximum of 10?

Comments to be amended:
I would like you to correct the contents written in the following Docs.
Url:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-script?view=o365-worldwide

Excerpt:
Important
This script has been optimized for use on up to 10 devices.
To deploy at scale, use other deployment options. For example, you can deploy an onboarding script to more than 10 devices in production with the script available in Onboard Windows devices using Group Policy.

proposed amendment：
This script has been optimized for use on up to 10 devices.
Local scripting is a special on-board method for evaluating Microsoft Defender for Endpoint.
The data reporting frequency is set higher than the other on-board method when the on-board by local script is performed.
This setting is for evaluation purposes and is not normally used in production deployments.
For this reason, there are concerns about environmental impact, so please limit the number of deployments using local scripts to 10.
If you are deploying to a production environment as described above, consider deploying using Group Policy or Microsoft Endpoint Configuration Manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f044e756-d5d8-5db6-edbb-f042b1b22b3c
* Version Independent ID: 5d016fa2-3407-e757-1595-118728158c46
* Content: [Onboard Windows devices using a local script](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-script?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-script.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-script.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@kahosoka Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7102

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kahosoka Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
