### ISSUE TITLE
Cannot read diagram

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#709]
On the page [Creating a trainable classifier (preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-creating-a-trainable-classifier):

You cannot read the sample timeline at the top of the page because the image is too blurry. Please upload a higher resolution image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f21ae81f-df7d-2d52-efbd-7de3cf5d170c
* Version Independent ID: afca7794-e169-c228-9c40-224603aeaeac
* Content: [Create a trainable classifier (preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-creating-a-trainable-classifier#feedback)
* Content Source: [microsoft-365/compliance/classifier-creating-a-trainable-classifier.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-creating-a-trainable-classifier.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@EricaToelle - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by chrfox** [comment]
@EricaToelle
Hi, Thank you and I apologize for the blurriness of the image. We take having our content legible to all customers very seriously.  I too noticed it as difficult to read when looking at it against a dark background. I'll ask our art department to make it more legible.  
Thank you again for bringing this to our attention
Chris

**Comment by chrfox** [comment]
@EricaToelle  - I have updated the art with a version that is more legible against both dark and light backgrounds.  Thank you again for bringing this to our attention.
Chris
