### ISSUE TITLE
Update licensing information

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/microsoft-365-docs#7092]
Hi,

could someone update the article to reflect the correct licensing statement about DKE?
As listed here [https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide#system-and-licensing-requirements-for-dke](url) it tells us "Microsoft 365 E5" is required. But this is not exactly true, as e.g. E5 Compliance is also fine to use with DKE regarding this article here: [https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-8](url) and the information provided here: [https://m365maps.com/Microsoft%20365%20Enterprise%20-%20E5.htm](url)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@myfope Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7148

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Please update.
