### ISSUE TITLE
Link in Related content is incorrect

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#7093]
Under related content link to "Reports in the Security & Compliance Center (article)" goes to https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/activity-reports?view=o365-worldwide (Microsoft 365 Reports in the admin center)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d43b01f-5c1e-515a-900a-7aab927c294e
* Version Independent ID: 23b1fc80-9d25-c9fb-2600-3d91b11b9063
* Content: [Microsoft 365 Reports in the admin center - Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/office-365-groups-ww?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-Reports-in-the-admin-center-Office-365-groups-a27f1a99-3557-4f85-9560-a28e3d822a40&view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/office-365-groups-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/office-365-groups-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7127

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dkotars Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
