### ISSUE TITLE
RBAC for Threat Analytics

### ISSUE THREAD

**Issue by import-au** [MicrosoftDocs/microsoft-365-docs#7094]
What permissions or roles are required to view Threat Analytic reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1834aed2-8822-5a3b-c5c5-ac70b86fa277
* Version Independent ID: 525f0820-aedb-8822-8518-27a5f983f68d
* Content: [Track and respond to emerging threats with Microsoft Defender for Endpoint threat analytics](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/threat-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/threat-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/threat-analytics.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@import-au Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7094

Thanks
Sri
