### ISSUE TITLE
Defender macOS Custom Profile, e.g. Onboarding, does not specify Deployment Channel

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/microsoft-365-docs#7095]
macOS Custom Profiles in Intune now require specifying the deployment channel, e.g. device or user. Docs do not specify the required/supported channel for this in the UX or instructions and require updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd66a255-36e5-29dc-7610-d50ef8bca3f3
* Version Independent ID: 17375473-bc07-f8e5-a85f-d732bbba3d71
* Content: [Intune-based deployment for Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#create-system-configuration-profiles)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-with-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-with-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jerryabo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7180

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jerryabo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
