### ISSUE TITLE
AzureAD Preview Modules

### ISSUE THREAD

**Issue by alschneiter** [MicrosoftDocs/microsoft-365-docs#710]
You need Azure ADPreview modules. Get-AzureADDirectorySetting is a part of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@alschneiter  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@alschneiter  Thank you for your feedback. We have updated the doc with more information via PR https://github.com/MicrosoftDocs/microsoft-365-docs/pull/767

Thanks
Sri

**Comment by cabailey** [comment]
@alschneiter This is now resolved - thanks for flagging this!
