### ISSUE TITLE
Regarding the permission requirements

### ISSUE THREAD

**Issue by peyman** [MicrosoftDocs/microsoft-365-docs#7107]
The article mentions that you must have "manage security settings" permissions to create labs. This does not match any of the azure admin permissions. I am not if it's a mistake or if I am not looking in the right place for permission sets. Could you please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302ee74c-812a-51b2-13e5-7b5daaa411f7
* Version Independent ID: 37fca1db-b257-588f-db65-4d5c6d7fd53f
* Content: [Microsoft Defender for Endpoint evaluation lab](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluation-lab?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/evaluation-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/evaluation-lab.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@peyman  Thank you for your feedback. Under permission options in https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/user-roles?view=o365-worldwide#permission-options you have 
Manage portal system settings - Configure storage settings, SIEM and threat intel API settings (applies globally), advanced settings, automated file uploads, roles, and device groups

You can login to M365 defe -> Settings->Enpoints-->Roles to view this option.

![image](https://user-images.githubusercontent.com/45987684/145938624-5f9e87ed-568f-4172-b96a-a6f7b13736ca.png)

Hope this helps!

Thanks
Sri

**Comment by peyman** [comment]
Thanks Sri, makes sense. Thanks for clarifying.
