### ISSUE TITLE
What permission for e.g. Audit tab?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#7108]
I would like to see a reverse list: what permissions are required to see the several menu entries and associated blades.
E.g. what permission/role do I need to see the Audit menu item and blade?
(Yes, I know I can find it [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-search-the-audit-log), but that is just one of the many blades)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 468343fc-2808-0f78-f1a7-9d34b8fa8e16
* Version Independent ID: e3b7630f-75a9-d236-6c8b-7ebd27a7e9c0
* Content: [Permissions in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/microsoft-365-compliance-center-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-compliance-center-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @andrePKI Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
