### ISSUE TITLE
Reading this manual and don't know how notice templates are applied to users

### ISSUE THREAD

**Issue by Matthewchalkwood** [MicrosoftDocs/microsoft-365-docs#7113]
have been going through this manual for insider risk management notice templates and I don't understand how the notice templates are applied to people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669b588b-868b-742e-0ceb-dbbd3cadee92
* Version Independent ID: 44df5253-a1b9-0d1e-c3a5-f5b2699003c9
* Content: [Insider risk management notice templates - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-notices?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-notices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-notices.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@Matthewchalkwood Thank you for your feedback. This document pertains to the Creation of notice templates (To notify the sender of a violation, you can set up a template to be used to provide an approved and crafted message to the user).

Once you see alerts in the dashboard, you can take the below actions

Actions explained:

Resolve: if the item is not questionable or non-compliant, you would resolve it. This will move it into the Resolved tab. Optional: you could tag it first as Compliant although this is not required
Tag as: Questionable, Compliant, Non-Compliant. You can then filter on these tags making this a very helpful feature, particularly in large result sets. It appears you cannot customize these tags as you can in Advanced eDiscovery
**Notify** using the notice template we created in a previous step, you can send a notice to the sender of the selected communication. You will have the opportunity to edit the notice or create a new one in the moment before sending
Escalate: if escalation is required on an item, an email will be sent to someone you identify to further review the item(s) selected. 


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Matthewchalkwood Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
