### ISSUE TITLE
Does enabling modern authentication create a policy in exchange 

### ISSUE THREAD

**Issue by karimzaki** [MicrosoftDocs/microsoft-365-docs#7114]
Details aren’t clear
When enabling modern authentication is it creating policy for exchange online? How many hours to be applied.
Why users are prompted for adding user and password and what impact on auto discovery

**Comment by denisebmsft** [comment]
Hello @karimzaki. Can you please tell us to which article(s) your feedback applies? This information will help us route the issue to the correct writer/team.

**Comment by yogkumgit** [comment]
@karimzaki We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
