### ISSUE TITLE
Details missing about autodiscover behavior 

### ISSUE THREAD

**Issue by karimzaki** [MicrosoftDocs/microsoft-365-docs#7115]
[What will happen to exchange online authentication policy will it be enabled]
What will happened to outlook autodiscover it asks for user and password 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e6c9a-9644-6d86-3962-d36bf1efd656
* Version Independent ID: 96142d6c-71de-6ea9-0361-dbec82647b15
* Content: [Set up multifactor authentication for users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide&source=docs#turn-off-legacy-per-user-mfa)
* Content Source: [microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/set-up-multi-factor-authentication.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@karimzaki Thank you for your feedback. Is your question more on how to enable Modern auth?. If yes, We have that coming in the next document in the list -https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/enable-modern-authentication?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @karimzaki Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
