### ISSUE TITLE
Bring back bank account list for EFT payments

### ISSUE THREAD

**Issue by v-nathanc** [MicrosoftDocs/microsoft-365-docs#7116]
Hi team,

There used to be a link under "Where do I send my check or EFT payment?" that customers could use to find out which Microsoft bank account to send their EFT to. This was incredibly helpful for customers who have switched to invoice pay and can't wait for a new invoice to be generated. It was also useful for customers who are looking to pay a written off balance and typically pay by card. Can this list of Microsoft bank account details please be re-instated on this document?

If you have any questions, please let me know.

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82583c48-08e6-9acb-657b-ce1fe44e76a5
* Version Independent ID: cbdcf652-3a68-4fa3-9f3b-92c518e0b710
* Content: [Paying for your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/pay-for-your-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@v-nathanc Thank you for your feedback. This was recently removed by the author, I'm checking for the exact reasons behind that and will update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cmcatee-MSFT email sent on 10 Dec with query.

**Comment by v-nathanc** [comment]
> @v-nathanc Thank you for your feedback. This was recently removed by the author, I'm checking for the exact reasons behind that and will update you shortly.
> 
> Thanks Sri

Thanks Sri. I look forward to hearing from you.

**Comment by msbemba** [comment]
@v-nathanc I have got confirmation from the author that those details which were removed are no longer relevant.
They should consult their invoice for payment information. If they are a credit card customer who needs to make a one-time payment via check or EFT, then they must contact billing support.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @v-nathanc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
