### ISSUE TITLE
Documentation incorrect? 

### ISSUE THREAD

**Issue by mdlister** [MicrosoftDocs/microsoft-365-docs#7118]
The statement:

> In Europe, the Middle East, and Africa (EMEA), all Exchange Online mailboxes are located in EMEA datacenters, and all messages are routed through EMEA datacenters for EOP filtering.

This section is missing the United Kingdom? 
after requesting data to be moved to the UK, email contents would reside in the UK datacenters would that also apply to EOP?

https://docs.microsoft.com/microsoft-365/enterprise/request-your-data-move

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8878304-7f4b-15c3-d2b6-8a5583930199
* Version Independent ID: 329f3b45-a087-6743-0664-e74dd9e0fc46
* Content: [Exchange Online Protection (EOP) overview - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/exchange-online-protection-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/exchange-online-protection-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/exchange-online-protection-overview.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mdlister, checking.

**Comment by chrisda** [comment]
@mdlister, likely not the answer that you're looking for, but we've decided to dial down the specificity. I was hoping there was some other resource that I could link off to, but there apparently isn't. Frankly, the existing information wasn't terribly helpful. It would be important if you're located in region/country A, but your data is stored/processed in region/country B, but that doesn't seem to be happening. So, this existing statement seems to be the most important:

> EOP performs load balancing between datacenters but only within a region. If you're provisioned in one region all your messages will be processed using the mail routing for that region.

Thanks for the feedback.

Closing.

Feel free to reopen as necessary.
