### ISSUE TITLE
Need Document update

### ISSUE THREAD

**Issue by SanguptaMSFT** [MicrosoftDocs/microsoft-365-docs#7121]
We need documents to have information from below google article or should atleast point to this article:

https://firebase.google.com/docs/cloud-messaging/concept-options#messaging-ports-and-your-firewall

This is based on internal engineering escalation. please reach out to me for more details about the escalation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
I'll discuss this with the endpoints PM.

**Comment by SanguptaMSFT** [comment]
@kelleyvice-msft there is an internal discussion thread going on with Engineering. let me know if you want me to add.

**Comment by SanguptaMSFT** [comment]
done. Thanks,

**Comment by SanguptaMSFT** [comment]
@kelleyvice-msft any updates ?

**Comment by SanguptaMSFT** [comment]
@kelleyvice-msft can you confirm the latest status ? @yogkumgit this is still pending.

**Comment by kelleyvice-msft** [comment]
@SanguptaMSFT I'm just back from vacation and getting caught up. I'll get back to you his afternoon after I look through the thread again.

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please update. Thanks

**Comment by kelleyvice-msft** [comment]
I am publishing an update today to the article https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide that resolves this issue for both Android and Apple mobile devices. See the new row 25 of the endpoints table. PR: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/14652. -Kelley
