### ISSUE TITLE
Services and URLs list is incomplete

### ISSUE THREAD

**Issue by DuncanClay** [MicrosoftDocs/microsoft-365-docs#7123]
I allowed the listed URLs through our firewall, but Defender/MAPS could not connect to the cloud service.
"%ProgramFiles%\Windows Defender\MpCmdRun.exe" -ValidateMapsConnection failed with hr = 0x800705B4

Based on the output of the MDE Client Analyzer, I needed to add the following URLs (will vary by region):

EDRCloud CnC
winatp-gw-weu.microsoft.com
winatp-gw-neu.microsoft.com

EDRCloud Cyber
eu.vortex-win.data.microsoft.com
eu-v20.events.data.microsoft.com

EDRCloud AutoIR
automatedirstrprdweu.blob.core.windows.net
automatedirstrprdneu.blob.core.windows.net

After allowing those URLs, the ValidateMapsConnection test was successful, and computers appeared in the M365 Defender portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1575e3-b233-ffd2-95c1-fd34fd242651
* Version Independent ID: 02b44885-5bff-1580-0974-f9050bee639c
* Content: [Configure and validate Microsoft Defender Antivirus network connections](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus?view=o365-worldwide#validate-connections-between-your-network-and-the-cloud)
* Content Source: [microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Hello @DuncanClay and thank you for the feedback. We have looked into this issue and have updated the article.
