### ISSUE TITLE
review this page

### ISSUE THREAD

**Issue by albertv-devpro** [MicrosoftDocs/microsoft-365-docs#7126]
[Enter feedback here]
This rule for implementation is found in exchange admin center under advanced threat.
please can you update the method on how to implement this, it took me time to figure this out.

best regards,
v.albert

**Comment by yogkumgit** [comment]
@albertv-devpro Please indicate which page you are referring to. Thanks

**Comment by yogkumgit** [comment]
@albertv-devpro We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
