### ISSUE TITLE
Get-DlpCompliancePolicy add -DistributionDetail

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/microsoft-365-docs#7129]
[I've just been using this and the screenshot nr 2 here https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy?view=o365-worldwide#turn-on-a-dlp-policy needs to be updated.

This line will not present the correct DistributionStatus: Get-DlpCompliancePolicy "policy" | select distributionstatus

But when adding -DistributionDetail it will

Get-DlpCompliancePolicy "policy" -DistributionDetail | select distributionstatus]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36344d-67bf-68cb-5004-9ac6f27ebf51
* Version Independent ID: 89a7d7e7-c643-eb06-d844-b97b80633b68
* Content: [Create, test, and tune a DLP policy - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-test-tune-dlp-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@ChristianJBergstrom Thank you for your feedback. Both the cmdlets work the same way. Distribution status is available even when you run get-dlpcompliancepolicy

![image](https://user-images.githubusercontent.com/45987684/146659401-68286350-903f-4983-94e6-96a21ceb3b77.png)

Hope this helps!

Thanks
Sri

**Comment by ChristianJBergstrom** [comment]
@msbemba Perhaps I wasn't clear enough. It might look as they work the same and return the same value but that's not the case. I have policies which has been enabled with status "success" for a long time, but when using the former they are still showing status "pending". The actual DistributionStatus is only presented when adding -Distributiondetail.

Ex.
![image](https://user-images.githubusercontent.com/90273807/146666740-7a55f07c-ce78-42cc-9de9-d696c9a77a31.png)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ChristianJBergstrom Thank you for your feedback. Good Catch and I was able to repro the situation.

![image](https://user-images.githubusercontent.com/45987684/146720144-4cb34966-2e66-4885-acab-e5f27f705292.png)


I have created a PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7221 to reflect these changes.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChristianJBergstrom Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
