### ISSUE TITLE
Site and group settings

### ISSUE THREAD

**Issue by alschneiter** [MicrosoftDocs/microsoft-365-docs#713]
How long does it takes until Site and group settings appears in the policy wizard? We have activated the Preview on several tenants, but there is no "Site and group settings" available when creating new labels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#if-you-used-classic-azure-ad-site-classification)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@alschneiter  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by ajeriksson** [comment]
Same here, how many hours should the activation take?

**Comment by prashant1380** [comment]
Same here, "Site and Group settings" not available

**Comment by jpawlowski** [comment]
From what I've heard, the tenant readiness (e.g. an updated version of the "Security center", I believe) is ongoing for a few more weeks. That means even though you can run the PowerShell command from this article, it does not mean that it will work for you without the admin center being updated by Microsoft as well.

I too find this a little miss-leading, e.g. successfully running the PowerShell command should only be possible when the tenant was prepared for the whole preview already. However - by knowing this, simply wait a few more days until the end of the month are totally okay ;-)

**Comment by alschneiter** [comment]
Based on that blog, Public preview starts Nov 20th, 2019.
See section "Sensitivity labels for Teams, Office 365 Groups, and SharePoint Sites":
https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/SharePoint-and-OneDrive-Security-compliance-migration-admin-and/ba-p/960871?utm_source=t.co&utm_medium=referral

**Comment by msbemba** [comment]
@alschneiter You are correct! The public preview starts on Nov 20th.

Hope this helps!

Thanks
Sri

**Comment by vinodb20** [comment]
I have activate the Preview on our tenant but I still do not see the Site & Group settings in Office 365 Compliance Center.
Will this only be published to https://security.microsoft.com or will it also be available via https://protection.office.com ?

The very first line of this article refers to https://protection.office.com, but I do not see the preview feature yet. It is 21st November, 2019 already.

Thanks,
Vinod Bhargavan

**Comment by smileythf** [comment]
Hi, is anyone seeing the preview yet?

**Comment by alschneiter** [comment]
Unfortunately not! :-(.
@MS what are we missing?

**Comment by JitMcCarthy** [comment]
Hi, I have a customer who is using the preview and he was able to update the sensitivity label on one of his site collection property, but when uploaded files after setting the label, it did not automatically update the file label sensitivity. Is this caused by a missing feature?

**Comment by smileythf** [comment]
I'm glad to day that I'm now seeing the Site and group settings in the Microsoft 365 Security center, no further action required.

**Comment by alschneiter** [comment]
@smileythf I can confirm the same behavior, also in the "old" protection.office.com portal.
Solved!

**Comment by bybytaren** [comment]
No issue to enable on a tenant where old Classification has not been enabled, and the powershell responds with class SettingValue {
                Name: EnableMIPLabels
                Value: True}
That response is not displayed when I enable on a tenant where Classification is in use, however the Security & Compliance center Labelling does show the Site and groups settings, but the option to add Sensitivity to a Team is not visible.

**Comment by vinodb20** [comment]
The feature does not work as expected:

1. I was able to set EnableMIPLabels to True. 
 - This enabled Site & Group settings while creating sensitivity labels in security & compliance center.
2. I created the labels and published the same.
3. I do not see the 'Sensitivity Field' while creating a group connected team site - SharePoint.
4. I do not see the 'Sensitivity Field' while creating a new Office 365 group - Outlook.
5. I see the 'Sensitivity Field' while creating a new Team - MS Teams.
6. The command 'Get-Label |ft Name, Guid?' shows me the list of labels that I have created, but I am not able to update the SensitivityId of an existing Office 365 Group - please see below:

Set-UnifiedGroup -Identity ABC -SensitivityLabelId "GUID"

We failed to update the unified group. Please try again later.
    + CategoryInfo          : NotSpecified: (:) [Set-UnifiedGroup], TaskException
    + FullyQualifiedErrorId : [Server=AM0PR04MB5154,RequestId=c8022509-e6ad-425e-b75c-a7eca209fb4c,TimeStamp=11/26/201
   9 8:33:08 AM] [FailureCategory=Cmdlet-TaskException] 9C9D889D,Microsoft.Exchange.Management.RecipientTasks.SetUnif
  iedGroup
    + PSComputerName        : outlook.office365.com

What am I missing here?

**Comment by bybytaren** [comment]
However when creating a new Team with a Sensitivity label i receive "You are not authorized". 
I am Global Admin and have no issue when creating a Team with label set to None.

**Comment by alschneiter** [comment]
Do you have the roles Compliance administrator and Security Administrator as well?

**Comment by vinodb20** [comment]
Same here:

![image](https://user-images.githubusercontent.com/28761066/69619807-7ed21200-103c-11ea-9182-53069531d2ff.png)

**Comment by prashant1380** [comment]
Yes, i have the situation as explained by @bybytaren i.e. I am already using Classification list in my tenant and after enabling this preview, I can see Site & Group Settings in label configuration but after applying the configuration Sensitivity does not show up in Group/SPO site/Teams creation.

**Comment by msbemba** [comment]
@prashant1380 @vinodb20 @bybytaren Thank you for your feedback. This issue is more of a support case rather than a document correction as it is not a constant issue across all tenants. @mypil Would you be able to provide the support information for O365?

Thanks
Sri

**Comment by mypil** [comment]
@prashant1380 @vinodb20 @bybytaren - You can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get this information you are discovering back into the docs.
