### ISSUE TITLE
Please mention that onboarding can be automatically done when MDE is deployed

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/microsoft-365-docs#7132]
[Enter feedback here]
If MDE is already configured, you have the option to "Turn on device onboarding" - and then the custom OMA URI is not needed, and probably this is nevery needed since we now have the "Microsoft Defender for Endpoint" configuration profile.

/Kenneth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb56734-b73f-1440-87b2-e87497269938
* Version Independent ID: ffb56734-b73f-1440-87b2-e87497269938
* Content: [Onboard Windows 10 and Windows 11 devices using Mobile Device Management tools - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-mdm?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/device-onboarding-mdm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/device-onboarding-mdm.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@kennethvs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7214

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kennethvs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
