### ISSUE TITLE
New-OMEConfiguration should inform others

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/microsoft-365-docs#7133]
[Enter feedback here]
New-OMEConfiguration -Identity "Custom branding template" does not indicate in any known documentation that an E5 subscriptions is needed.  All other commands work in this document, but New-OMEConfiguration does not.
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04de3d3-6a94-29f8-3a3d-68ed9422e058
* Version Independent ID: e50fc407-2c78-a3cc-71cd-7978ca340189
* Content: [Add your organization brand to your encrypted messages - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@fixx-er Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7215

Thanks
Sri

**Comment by yogkumgit** [comment]
@KCCross this is similar to #7092

**Comment by yogkumgit** [comment]
@fixx-er Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
