### ISSUE TITLE
For a section called "Manage email and calendars" .. *where are the calendars?*

### ISSUE THREAD

**Issue by JohnAWasco** [MicrosoftDocs/microsoft-365-docs#7134]
[Enter feedback here]

Literally the title of the section is "Manage email and calendars" but .. there's *NADA* *BUPKIS* *ZILCH* *ZIP* *ZERO* about managing calendars here.

This is .. disappointing .. as I have a user on temporary leave and need to reassign their calendars .. not "convert to office365" (already did that) or "assign another user access to their mailbox" (because managing calendars is not the same as managing email) ...

This level of "miss" in documentation should be unacceptable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@JohnAWasco Thank you for your feedback. When you assign full access to another user on a mailbox, it grants access to all folders in the mailbox (including calendar)

Mailbox permissions are used to grant access to an entire mailbox. Every folder within the mailbox, whether it be the Inbox, Calendar, or Contacts, allows the same level of access, when mailbox permissions are used. The access granted through mailbox permissions is “Full Access”, meaning that the user can read, write, edit, create, delete, and so on.

On the other hand, If you only want to grant someone calendar permissions you will need to use Mailbox Folder Permissions (https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailboxfolderpermission?view=exchange-ps)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JohnAWasco Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
