### ISSUE TITLE
Features not documented

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/microsoft-365-docs#714]
Anti-malware policies have two features that are undocumented by this page:
1. Common Attachment Types Filter
2. Malware Zero-hour Auto Purge
It's possible to find these features mentioned elsewhere in Docs, but they should be documented here in the "Use the EAC to create anti-malware policies" section, since this is a walkthrough of creating an anti-malware policy, and these features appear on-screen when creating an anti-malware policy.

To see what I'm talking about, set up a Microsoft 365 test tenant (using https://demos.microsoft.com) and try to follow the steps in "Use the EAC to create anti-malware policies." There are two sections in the dialog that are not documented on this page.

The Common Attachment Types Filter subsection should be after the Malware Detection Response section. The Malware Zero-hour Auto Purge section should be after the Common Attachment Types Filter section. 

The Notifications section (already documented on this page) should be after the Malware Zero-Hour Auto Purge section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db041b73-f7c9-db6c-070b-a7c974de640c
* Version Independent ID: dffb7045-3ba8-a014-d1be-462ca1d609b5
* Content: [Configure anti-malware policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-anti-malware-policies#feedback)
* Content Source: [microsoft-365/security/office-365-security/configure-anti-malware-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-anti-malware-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@robmacf  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@robmacf Thank you so much for the feedback. I have modified the doc accordingly via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/831

Thanks
Sri

**Comment by mypil** [comment]
@robmacf - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/9407a98db94bf61a9cf79e6d4d183df55d08cfcc. 

Thank you for your contribution to make the docs better! Much appreciated!
