### ISSUE TITLE
SIP Gateway adds UDP ports

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/microsoft-365-docs#7140]
Additional UDP ports have been added as part of the Teams SIP Gateway.
https://docs.microsoft.com/en-us/microsoftteams/sip-gateway-configure
Now mentions 49,152-53,247 vs in this document  it only starts at 50,000
This is also obvious in more than just SIP gateways as we are seeing it in some calls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Other endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by JohnGGeo** [comment]
I guess I want to add on that it'd be nice to see these ports accross additional documentation such as https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide
as the ports are mentioned in direct routing, https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-plan#port-range-applicable-to-all-environments we're also seeing a TCP port 49252 and it's not mentioned in any documentation we're seeing.

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I've confirmed that the data in these articles is out of sync. Note that the endpoints data in this article is autogenerated by the Office 365 endpoints web service and cannot be manually edited. I am informing the appropriate engineering team of this issue and requesting that they go through the process of updating their endpoints in the web service. Once they complete this process, the correct endpoints and related information should be included in future updates. -Kelley

**Comment by tiburd** [comment]
@kelleyvice-msft 
Thank you for sharing the information.
Closing this issue.

FYI: @yogkumgit
