### ISSUE TITLE
Content Search via Msg IDs

### ISSUE THREAD

**Issue by brettsec** [MicrosoftDocs/microsoft-365-docs#7143]
It would be helpful to conduct a Content Search for specific Msg IDs.

Workflow starts with an audit log search. The unique data point provided in an Audit Log is the message ID. To my knowledge, I can't use Message ID directly to search for messages within content search and / or eDiscovery.

**Comment by yogkumgit** [comment]
@brettsec Please indicate, which document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@bratsche We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
