### ISSUE TITLE
Win10/11 Multi-Session Support - Clarification required

### ISSUE THREAD

**Issue by RichardvanNuland** [MicrosoftDocs/microsoft-365-docs#7147]
Please clarify in this article the support for Windows 10/11 multi-session.

As mentioned in the below article Win10/11 multi-session should be considered a separate OS edition, so it should be made clear what scenario's are and aren't support for multi-session.

https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31e7b39-b7c3-188a-0b2a-02ff10a5be6d
* Version Independent ID: 44940a13-0a2d-e281-560b-cb4d8a5d1ccf
* Content: [Protect security settings with tamper protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@RichardvanNuland Thank you for your feedback. I have made changes via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7200

Once the Author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @RichardvanNuland Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by RichardvanNuland** [comment]
Hi,

Apologies, but I don't believe this update addresses the issue fully.

For example microsoft-365-docs/prevent-changes-to-security-settings-with-tamper-protection.md at public * MicrosoftDocs/microsoft-365-docs (github.com)<https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md#requirements-for-managing-tamper-protection-in-the-microsoft-365-defender-portal> now still shows this only applies to Win10 / Win11 without mentioning Win10/11 multi-session. That makes it still very unclear what options you have to enable Tamper Protection on Win10/11 multi-session.

This is just one example, all sections in this article should make clear if that section applies to Win10/11 multi-session.

Regards,
Richard

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@RichardvanNuland I have made some additional changes via PRhttps://github.com/MicrosoftDocs/microsoft-365-docs/pull/7248

Once the author verifies and approves, the changes will be live. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @RichardvanNuland Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
