### ISSUE TITLE
DLP Alerts retention

### ISSUE THREAD

**Issue by jorge-at123** [MicrosoftDocs/microsoft-365-docs#7152]
This document and probably others (or a FAQ page) should have information about how long DLP alerts remain available in the Portal.
This type of information is often asked by customers.

I could not find this information anywhere and needed to open a support case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e9f547-6180-2981-6e7a-895fc17b7703
* Version Independent ID: 58334631-7058-1809-0804-c107457b4470
* Content: [Configure and view alerts for data loss prevention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-configure-view-alerts-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-configure-view-alerts-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-configure-view-alerts-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@chrfox Please help us resolving this issue. Thanks. Email sent with details : 12-19-2021

**Comment by chrfox** [comment]
Hi @jorge-at123 
Thanks for your comment, I'll get the information and update the content as appropriate.

**Comment by randomat123** [comment]
Hello @chrfox!
I could not find the information in the docs. Did you update another DLP document with the Alerts retention information?
I would like to have the document to send to our customers.

Thanks!
