### ISSUE TITLE
Add the Getfile timeout details

### ISSUE THREAD

**Issue by absheh** [MicrosoftDocs/microsoft-365-docs#7157]
[Enter feedback here]
To add the details for Getfile command timeout, as the Getfile also have the same timeout of 30 minutes and while the command is running it is considered as a inactive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b2a4c2-e698-dda0-9919-80ca2d05b358
* Version Independent ID: 19b5f609-fcaa-cb5b-96b7-462285fd32e7
* Content: [Investigate entities on devices using live response in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response?view=o365-worldwide#get-a-file-from-the-device)
* Content Source: [microsoft-365/security/defender-endpoint/live-response.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/live-response.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@absheh Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7216

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @absheh Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
