### ISSUE TITLE
Preservation Hold One drive sites.

### ISSUE THREAD

**Issue by nmistry77** [MicrosoftDocs/microsoft-365-docs#7159]
[Enter feedback here]
How do you identify a one drive sites on preservation hold?
OR
What is the attribute which uniquely identifies one drive sites with preservation hold? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
I’m not aware of a site attribute you could use and as this page states, the Preservation Hold library isn’t created until needed.  However, you can use Policy lookup (https://docs.microsoft.com/en-us/microsoft-365/compliance/retention#policy-lookup) to confirm whether a OneDrive site has a retention policy assigned to it, and then check the policy configuration.  If the retention actions include retain (not just delete), the Preservation Hold library will be used to preserve files if the user delete them.

**Comment by yogkumgit** [comment]
@nmistry77 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by nmistry77** [comment]
No it did not provide me information I was looking for.

**Comment by cabailey** [comment]
@nmistry77  Can you describe what business problem are you trying to solve?

**Comment by nmistry77** [comment]
> @nmistry77 Can you describe what business problem are you trying to solve?
Working on T2T migration and customer has requested to migrate PHL OD4B data as well. MS should provide a simple p$ command to find all one drive sites which are enabled for preservation hold just like inactive mailboxes in exchange. workaround for OD4B is tedious when you have duplicates etc.

**Comment by cabailey** [comment]
@nmistry77  OK, so you don't need to know if a site has a retention policy applied, but if it has a Preservation Hold library - might not be the same thing!  Since this is more a SharePoint question than retention question, I'm making a few inquiries with SharePoint folks & will update here if I can find an answer that helps you.

**Comment by nmistry77** [comment]
> @nmistry77 OK, so you don't need to know if a site has a retention policy applied, but if it has a Preservation Hold library - might not be the same thing! Since this is more a SharePoint question than retention question, I'm making a few inquiries with SharePoint folks & will update here if I can find an answer that helps you.

Thank you so much!

**Comment by cabailey** [comment]
@nmistry77  Not forgotten - but delays with people taking time out for the holidays.  There isn't a single query that you can use, but I do have a suggested solution to share:

1. Use a script to get a list of OneDrive URLs for your tenant: https://docs.microsoft.com/en-us/onedrive/list-onedrive-urls#use-powershell-to-create-a-list-of-all-the-onedrive-urls-in-your-organization

2.  Use the output to parse each site by using another script that looks for the library title "Preservation hold library"

Unfortunately, nobody could locate a ready-made script for the second step, although they passed on the tip to use the GetByTitle method "Web.Lists.GetByTitle" and suggested looking at the following links that similarly pull details for a document library (but you'll need to modify for "Preservation hold library"):

https://www.sharepointdiary.com/2018/08/sharepoint-online-get-document-library-using-powershell.html#ixzz7Gw5X6I3k
https://www.spguides.com/get-sharepoint-document-library-size-using-powershell/
