### ISSUE TITLE
Preparation instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#716]
The instructions are not very explicit if we have used the PowerShell gallery to get the shell. this can be confusing to new powershell users. please add some information about updating the module in addition to using the control panel.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files#limitations)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@DeanGross  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by msbemba** [comment]
@DeanGross  Thank you for your feedback. We have updated the doc via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/825

Thanks
Sri

**Comment by cabailey** [comment]
@DeanGross This page is now updated to include Update-Module, which I think addresses this issue. If not let me know!
