### ISSUE TITLE
Licensing cost is not shown

### ISSUE THREAD

**Issue by matttheba** [MicrosoftDocs/microsoft-365-docs#7161]
Despite this being the licensing page, I cannot find pricing anywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998f446c-aacf-4d7c-fdc0-fc5c5073d20e
* Version Independent ID: 587f92c0-7f44-6ebf-1fac-403b84722969
* Content: [Licensing for SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/syntex-licensing)
* Content Source: [microsoft-365/contentunderstanding/syntex-licensing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/syntex-licensing.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@matttheba Thank you for your feedback. The license cost is not shown on the pages, instead, I have added the license overlink link to the document which provides more information about the cost based on the locale and/or currency.

This change can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7201

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @matttheba Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
