### ISSUE TITLE
Group Owners to add Guests - setting misbehaving or wrong description 

### ISSUE THREAD

**Issue by MarekHalfar** [MicrosoftDocs/microsoft-365-docs#7166]
Hi, this group setting 

> Let group owners add people outside your organization to groups

does not behave as described when set to "Off":
![image](https://user-images.githubusercontent.com/61430916/145972152-2944ade8-7539-4b9f-9657-769e0973bab5.png)

In my tests the Group/Team owner cannot add ANY guest, even if such already exist in directory.

Is it wrong in the Doc or can some other setting have an effect on this? For example I have set

> AllowToAddGuests              False

in Group.Unified AAD global Setting and enabling it ONLY per Group in Group.Unified.Guest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030743fd-0c22-025b-f190-f637a2772506
* Version Independent ID: fbded472-e3ea-4297-c527-810e117ea7ea
* Content: [Microsoft 365 guest sharing settings reference](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-guest-settings?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-guest-settings.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@MarekHalfar Thank you for your feedback. I'll test this and update the document if need be.

**Comment by msbemba** [comment]
@MarekHalfar Thank you for your feedback. I have made the changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7217

Thank you again for the feedback. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MarekHalfar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
