### ISSUE TITLE
Page is talking about Android instead of iOS?

### ISSUE THREAD

**Issue by Frankrebel** [MicrosoftDocs/microsoft-365-docs#7169]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb4c0c7-8f4d-df66-500d-f2d16e2fd85c
* Version Independent ID: 0031c46e-529e-f029-3509-ddf1174a220f
* Content: [Deploy Microsoft Defender for Endpoint on iOS features](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install-unmanaged?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install-unmanaged.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install-unmanaged.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @sunasing
* Microsoft Alias: **sunasing**

**Comment by msbemba** [comment]
@Frankrebel Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7202

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Frankrebel Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
