### ISSUE TITLE
Can't restore quarantined "Threat" files in Microsoft Defender Antivirus

### ISSUE THREAD

**Issue by Nicholas-Steel** [MicrosoftDocs/microsoft-365-docs#7170]
You can not restore a file from Quarantine if the file is treated as a "Threat". Restoration is only possible for Lesser issues like Unwanted Programs. Effectively once Windows Defender quarantines something as a Threat you lose the ability to restore the file and permanently lose access to the file... even if both you & Windows Defender know the file is not a threat to the health of you and your PC.

In my case the file is of a somewhat questionable nature and I don't want to disclose what it is, losing access to the file without my consent is a huge problem! I should not be having data deleted from my computer without my consent!

I'm unsure if this page pertains to Windows Defender, which is what I'm talking about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a40da1f-0038-b2f3-69c0-7d769f0f9152
* Version Independent ID: 54a1caf7-271f-df11-02c5-121c15444bb1
* Content: [Restore quarantined files in Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/restore-quarantined-files-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/restore-quarantined-files-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/restore-quarantined-files-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by Nicholas-Steel** [comment]
Turns out I just needed to type the following in to an elevated Command Prompt window to resolve my issue. This does not resolve my concern that it's needlessly difficult to restore some types of threats instead of being equally easy regardless of threat type.

"%ProgramFiles%\Windows Defender\MpCmdRun.exe" -restore -all

**Comment by msbemba** [comment]
@Nicholas-Steel Thank you for your feedback. You are correct, there is no GUI button to solve this currently. I recommend you leave the feedback directly to the Product team via https://feedbackportal.microsoft.com so you can get updates or information on when this will be available.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@Nicholas-Steel  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by Nicholas-Steel** [comment]
Interesting, so when I went back to the folder containing the file and Windows Defender again picked it up and removed the file to quarantine but... this time I was given access to the 3 Actions and was able to Allow (restore) it via the Windows Defender UI (which presumably also adds an exception for it). So that's nice.

Unsure if this is just this particular infection that can be Allowed or if it's a global change and all Threats can now be Allowed as they're encountered.

Separate issue, but I hate that the Quarantine UI doesn't tell you the originating path nor file name of the files in quarantine. It only tells you the threat type/name.

**Comment by buza-me** [comment]
> @Nicholas-Steel Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

Hah, valuable feedback xD Yeah, sure, it is only 2023. MS will definitely change the behavior any time soon. Thanks for the command @Nicholas-Steel

**Comment by TheBestPessimist** [comment]
This issue is not fixed as of the date of this comment: when i chose to restore the file, it was not restored. moreover on downloading the same file from the same url (this one https://github.com/seerge/g-helper/releases/download/v0.81/GHelper.zip), it kept putting it to quarantine.

Whitelisting/restoring still doesn't work.

**Comment by jpodpro** [comment]
agree that controls for dealing with false positives are incredibly insufficient. windows is being highly over-zealous here and should at least give users control over their files if they seek it out.
