### ISSUE TITLE
PowerShell Command missing value

### ISSUE THREAD

**Issue by chadwanderson** [MicrosoftDocs/microsoft-365-docs#7171]
[Enter feedback here]
Your command examples for Disabling Sharing is missing the value "disable" at the end.  

set-SPOSite https://dreampak.sharepoint.com -DisableCompanyWideSharingLinks disabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30458b2e-e1e3-842c-f817-53ed9fa9e05c
* Version Independent ID: 162dbe0c-8d15-8946-170c-38d44886c5be
* Content: [Limit sharing in Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-limit-sharing?view=o365-worldwide#people-in-your-organization-sharing-links)
* Content Source: [microsoft-365/solutions/microsoft-365-limit-sharing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-limit-sharing.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@chadwanderson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7203

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chadwanderson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
