### ISSUE TITLE
I see the Anti-Malware in the Policies section

### ISSUE THREAD

**Issue by linx-collin** [MicrosoftDocs/microsoft-365-docs#7174]
Hi,

The document on this page says "In the Microsoft 365 Defender portal, go to Email & collaboration > Policies & rules > Threat policies > Anti-malware in the **Rules** section.", but when I look down the page I see an "Anti-malware" in the Policies section. Is this the actual "Anti-malware" the instructions are referring to or should I see another in the Rules section?

Thanks
Collin

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf5c5df-c3ab-8448-aef0-af05977db9b9
* Version Independent ID: adade895-f42b-1029-9948-5ddb5b038257
* Content: [Quarantine policies - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide#anti-malware-policies)
* Content Source: [microsoft-365/security/office-365-security/quarantine-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@linx-collin, Anti-malware Policies is under Policies, not Rules. It was a simple copy/paste error that actually affected a bunch of other policy types in that topic, so I fixed them all.

Thanks for the feedback.

Closing
