### ISSUE TITLE
Advisor Content is out of date

### ISSUE THREAD

**Issue by ConradAT** [MicrosoftDocs/microsoft-365-docs#7175]
The section at the top that talks about signing up as an advisor is out of date. Currently only CSPs can get Delegated Admin Privileges on customer tenants. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18e861ca-29ad-feea-ff80-3750bce4005f
* Version Independent ID: 9dd4e1a3-aca7-bea2-d050-cfd02aa04a54
* Content: [Delegated administration FAQ](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/delegated-administration-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/delegated-administration-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/delegated-administration-faq.yml)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ConradAT, I fixed the offending section a few weeks ago:

<https://github.com/MicrosoftDocs/microsoft-365-docs/commit/13a98eee8f1b196c9bf9fa598c9e16b19157f0b5#diff-ca284f2338ddb52b32b1cad74ea8c9cdc058717d26778abf86b990ba39bcfb44>

Thanks for the feedback.

Closing
