### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by MicahFalde** [MicrosoftDocs/microsoft-365-docs#7176]
It would be nice if there were prerequisite roles in this blog. i.e.
"In order to do this you must have one of the following roles:
Security Reader
Security Admin
Global Admin"

And whatever other roles are applicable. 

It would also be nice to know if Defender RBAC roles affect this as well.  Do people who have been given read access to TVM in the portal have the ability to query Advanced Hunting tables from PowerBI?

**Comment by yogkumgit** [comment]
@MicahFalde Please indicate which document you are referring to for this feedback. Thanks

**Comment by yogkumgit** [comment]
@MicahFalde We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
