### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bashramath** [MicrosoftDocs/microsoft-365-docs#7179]
[Enter feedback here]The link pointing to "Start using your Office Add-in" seems to be broken.
The link pointing to "Start using your Office Add-in" seems to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61e46dd-c1ff-dfec-5e0e-9f2e7251a5c1
* Version Independent ID: 49f69fa9-33e8-373f-a7f9-26b828510fda
* Content: [Manage add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-addins-in-the-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-addins-in-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@bashramath Thank you for your feedback. The link is not a locale link (https://support.microsoft.com/office/82e665c4-6700-4b56-a3f3-ef5441996862) and it is working currently. If you are having problems with accessing the link from the document you can use the direct link posted above.

Thanks
Sri

**Comment by RAJU2529** [comment]
@yogkumgit .  According to me, bracket should be removed, so that link will link for all users.
Without removing brackets , link is working fine

**Comment by yogkumgit** [comment]
@msbemba Please comment

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @bashramath Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
