### ISSUE TITLE
auto-claim

### ISSUE THREAD

**Issue by rafi4242** [MicrosoftDocs/microsoft-365-docs#7183]
Only global admins can access the auto-claim page and view reports. even licenses admin can't view this.

Also, auto-claim gives licenses even when accessing a sharepoint site, without ever using Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57d3c7ec-df48-1f82-8b07-283b5238fda4
* Version Independent ID: 89a71654-a370-2160-8606-93d15be87e99
* Content: [Manage auto-claim policies](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/manage-auto-claim-policies?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/licenses/manage-auto-claim-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/manage-auto-claim-policies.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@rafi4242 Thank you for your feedback. I'm currently testing this feature for changes and will update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@rafi4242 Thank you for your feedback. You are correct, Only a Global admin is able to create or modify the policy. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7218

Regarding SharePoint, I do not see a roadmap item but will make changes once I receive confirmation.

Thanks
Sri
