### ISSUE TITLE
MDATP or WDATP

### ISSUE THREAD

**Issue by nb-ofs** [MicrosoftDocs/microsoft-365-docs#7184]
The instructions are inconsistent - https://security.microsoft.com/preferences2/onboarding says C:\test-WDATP-test 
however 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-detection-test?view=o365-worldwide#verify-microsoft-defender-for-endpoint-onboarding-of-a-device-using-a-powershell-detection-test says C:\test-MDATP-test

which one is right? MDATP or WDATP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d716f82-0a0f-49b8-587e-589d166e602e
* Version Independent ID: 2c91a5fb-0567-f267-29f9-4f2660742f6a
* Content: [Run a detection test on a device to verify it has been properly onboarded to Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-detection-test?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-detection-test.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-detection-test.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@nb-ofs Thank you for your feedback.  Originally launched as Windows Defender ATP, this Endpoint Detection and Response (EDR) product was renamed in 2019 as Microsoft Defender ATP. At Ignite 2020, we launched the Microsoft Defender for Cloud XDR suite and this EDR component was renamed Microsoft Defender for Endpoint.

The command at  https://security.microsoft.com/preferences2/onboarding needs to be changed to MDATP. I'll work with the author and provide feedback to the concerned team to make these changes.

Thanks
Sri

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks. Email sent with details : 20-12-2021

**Comment by mjcaparas** [comment]
I believe the documentation is accurate - C:\test-MDATP-test.

I reach out to the PM team wrt to the UI change required.
