### ISSUE TITLE
Missing a bit on checking settings

### ISSUE THREAD

**Issue by jotheman0303** [MicrosoftDocs/microsoft-365-docs#7185]
There is a step "Select the Virus & threat protection tile (or the shield icon on the left menu bar) and then the Virus & threat protection settings label:" to validate whether Cloud-delivered protection and Automatic sample submission is on. You need to click "Manage Settings" to see those options, might want to add that.

In addition it can be very unclear for people managing via GPO that the MAPS settings are "equal to" the cloud-delivered protection, it woult help to clarify that. Furthermore I don't think there is a suggestion/required setting on the Basic or Advanced setting. Some explanation on that can help as well. Thanks for updating in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcfc10-a6b2-04a9-180e-7e0ffa230c36
* Version Independent ID: 8ed5bf92-9816-fb44-ca16-8d6fd8b1e37f
* Content: [Turn on cloud protection in Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by RAJU2529** [comment]
@denisebmsft . I will look into this issue and I will made adjustments to this article

**Comment by denisebmsft** [comment]
Hello, all! It looks like this issue has been resolved with the recent content updates. Thank you again @jotheman0303 for your feedback, and thanks to those who contributed to the fixes!
