### ISSUE TITLE
Add exclusions for Microsoft Defender Antivirus in the Windows Security app steps outdated

### ISSUE THREAD

**Issue by angelazhangmsft** [MicrosoftDocs/microsoft-365-docs#7191]
The steps at https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus?view=o365-worldwide#add-exclusions-for-microsoft-defender-antivirus-in-the-windows-security-app need to be fixed. (#3 should be Under Virus & threat protection settings, select Manage settings.

![image](https://user-images.githubusercontent.com/69016571/146282423-27c22383-c75d-4f77-8237-6b9a55ca5961.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fc8e9f-ad24-1453-d0c8-85ff73910c79
* Version Independent ID: 7a6d0aae-8a3e-b6fc-cb13-e0a30b7b76df
* Content: [Microsoft Defender Antivirus in the Windows Security app](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-security-center-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@angelazhangmsft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7205

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @angelazhangmsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
