### ISSUE TITLE
The Office 365 Exchange Online API is depreciated and not visible.  Please add updated instructions, or an approved workaround if the API is not available for step 15.

### ISSUE THREAD

**Issue by richardkarras** [MicrosoftDocs/microsoft-365-docs#7193]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@richardkarras Thank you for your feedback. I tested the steps provided in the document and can locate the Exchange online API

![image](https://user-images.githubusercontent.com/45987684/146477341-cc28a349-6eab-4ae9-90a6-a95e5e691b54.png)

If you are still not able to view the API. I'd recommend you contact Microsoft support via the need help option in the admin center.

Thanks
Sri

**Comment by richardkarras** [comment]
Thanks Sri.  I wasn't able to find it, but I now believe the issue is that
I hadn't provisioned the fresh Tenant with any Exchange Online licenses
before attempting to build the migration app.  Hopefully all goes well
after that.

Happy holidays,
Richard

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @richardkarras Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
