### ISSUE TITLE
Thanks, I think we want to also work in/breadcrumb the What's New guidance/details here as well please @msbemba https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#new-deployment-channel-setting-for-custom-device-configuration-profiles-on-macos-devices

### ISSUE THREAD

**Issue by jerryabo** [MicrosoftDocs/microsoft-365-docs#7194]
Thanks, I think we want to also work in/breadcrumb the What's New guidance/details here as well please @msbemba https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#new-deployment-channel-setting-for-custom-device-configuration-profiles-on-macos-devices

_Originally posted by @jerryabo in https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7180#issuecomment-994954542_

**Comment by msbemba** [comment]
@jerryabo Thank you for your feedback. I had another PR open for the Same document and have committed changes to the same PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7180

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jerryabo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
