### ISSUE TITLE
|Needs updating

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#720]
Message expiry (delivery retry) is now 24 rather than 28 hours

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 291ffc45-3b90-c68b-7c57-0f46f57fc6f5
* Version Independent ID: cfb759bf-de5c-5ca3-3c0a-b39481021f29
* Content: [Queue alerts and Queues](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/mfi-queue-alerts-and-queues)
* Content Source: [microsoft-365/security/office-365-security/mfi-queue-alerts-and-queues.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mfi-queue-alerts-and-queues.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@aldoug  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
