### ISSUE TITLE
At the end of the retention period "do nothihg"

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/microsoft-365-docs#7210]
Question about the lack of documentation.
When configuring a retention policy you can set, [At the end of the retention period "Do Nothing"]. Isn't this the same thing as "retain items forever"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@HarrisburgUSysAdmin  No, it's actually the opposite. Retain forever means take steps to ensure the item is never permanently deleted (will always be returned in eDiscovery searches).  Whereas "do nothing" at the end of the retention period means no longer take steps to ensure the item isn't permanently deleted - in other words, the item can now be deleted by a user or system-initiated action & then won't be returned by eDiscovery searches.

**Comment by yogkumgit** [comment]
@HarrisburgUSysAdmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
