### ISSUE TITLE
Add more detail

### ISSUE THREAD

**Issue by ekfletcher** [MicrosoftDocs/microsoft-365-docs#722]
The information on this page is not detailed enough.  The report that you export for auto-forwarding seems to show you who has done any auto forwarding in the time period shown by the report.  I want to see EXACTLY who has forwarding enabled in both Outlook (rules) and OWA (Rules and Forwarding).  This needs to be a point in time report so that I can remediate accounts that are forwarding and should not be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5bb1b82-5bde-ce65-ca17-9e982b030a5c
* Version Independent ID: 704d9708-5308-4b5d-0ffa-d6b31fa7d0f3
* Content: [Auto-forwarded messages report](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report#feedback)
* Content Source: [microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mfi-auto-forwarded-messages-report.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@ekfletcher  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by ekfletcher** [comment]
Thank you!


Kevin Fletcher
AdventHealth
Sr. IT-Collaboration Eng, Enterprise Collaboration Services | AdventHealth Technology Services
O 407-805-8557

**Comment by msbemba** [comment]
@ekfletcher Thank you for the feedback. This report has information on messages that are automatically forwarded from your Office 365 organization to recipients in external domains and doesn't provide information on who has Automatic forwarding enabled. 

There are other docs that are related to Block auto-forwarding, But there is no report in o365 at the moment which can provide information on accounts that are auto-forwarding. Instead, You can follow the blog:-  https://blogs.technet.microsoft.com/timmcmic/2015/04/19/office-365-determine-accounts-that-have-forwarding-enabled/  which has PS CMdlets to gather the information that you are looking for.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@ekfletcher - From our understanding, the issue you raised has been answered by msbemba. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
