### ISSUE TITLE
False Microsoft Invoice for Windows Defender Order

### ISSUE THREAD

**Issue by CyberTech859** [MicrosoftDocs/microsoft-365-docs#7220]
I received a phishing email pretending to be from Microsoft. The email was intended to be an order confirmation / invoice for purchase of Microsoft Defender. 

The recipient name is incorrect and does not match the email address. The email was sent from a @gmail.com account which Microsoft would never do.

A text file has been added for your review.

Thank you.
[Order Confirmation.txt](https://github.com/MicrosoftDocs/microsoft-365-docs/files/7742834/Order.Confirmation.txt)

Sincerely,
Alan R. Smart
928 Aragona Blvd
Virginia Beach, VA 23455
Phone: 757-375-8432
alan.r.smart@outlook.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a21caf6-05ad-6226-59ea-5e4151d784b8
* Version Independent ID: 9cb6935a-184f-b18a-184c-7d4faf6256b6
* Content: [Report spam, non-spam, and phishing messages to Microsoft - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@CyberTech859, Just now I séen txt document, email is definitely phishing mail, suspicious mail, 

Don't response to that mail,  don't call to indicated customer care number.

**Comment by msbemba** [comment]
@CyberTech859 Thank you for your feedback. Use the Submissions portal to submit suspected spam, phish, URLs, and files to Microsoft https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide

In cases when you are unsure about the authenticity, we recommend you to contact Microsoft support via the need help link on the admin center so a support representative can help you investigate such emails.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @CyberTech859 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
