### ISSUE TITLE
Lack of word

### ISSUE THREAD

**Issue by mmangiante** [MicrosoftDocs/microsoft-365-docs#7224]
In the "Permission" section there is this period: "To access the Microsoft 365 Defender portal, users must one of the following", I think the correct version would be "To access the Microsoft 365 Defender portal, users must have one of the following".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05016400-436b-a954-3874-4a12ece08f39
* Version Independent ID: 05016400-436b-a954-3874-4a12ece08f39
* Content: [Requirements for Microsoft Defender for Business (preview)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-requirements.md)
* Product: **m365-security**
* Technology: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@mmangiante Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7242

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mmangiante Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
