### ISSUE TITLE
Exchange online Retention policies and labels isn't yet moved to M365 Compliance center

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/microsoft-365-docs#7225]
Our customer is seeing the below features as "Older" features in Exchange online MRM. 

“An archive policy for archive mailboxes to automatically move emails from a user’s primary mailbox to their archive mailbox after a specified period of time. Eg: EAC uses a default retention tag to move all emails from primary mailbox to archive after 2yrs. The same ability when using retention tags within EAC to manage individual mailbox folders (Not referring to Personal Tags). Eg: Retention Tag: Delete mail from “Deleted Items” folder after 30 days or from “Junk Email” folder.

That results in asking the below questions:

1. How do we achieve the above things through M365 Compliance center (M365 retention policies and labels)?
2. Do we have this in the roadmap if it is not currently achievable?
3. As an alternative, can we do it through Azure PowerShell?

This particular statement 'Older Features' needs to be focused.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#use-retention-policies-and-retention-labels-instead-of-older-features)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Balamurugan-dot  I'm not sure I understand the issue - the documentation lists MRM as an older technology than retention with M365 Compliance but states:

" ..if you use the following MRM features, be aware that they aren't currently supported by Microsoft 365 retention policies:

An archive policy for archive mailboxes to automatically move emails from a user's primary mailbox to their archive mailbox after a specified period of time. An archive policy (with any settings) can be used in conjunction with a Microsoft 365 retention policy that applies to a user's primary and archive mailbox."

This means at the moment you must continue to use MRM for an archive mailbox solution, but it doesn't exclude you from using M365 Compliance for retention and deletion. Yes, there are plans to move archiving to M365 Compliance, but I don't have dates to share at this time.

**Comment by Balamurugan-dot** [comment]
Thank you for you response Cabailey, 

Customer basically requested us to correct the wording **‘Older features’** because it’s a mistake on the current article that needs to be corrected now. Once we bring these features into M365 compliance center, we can then use the term ‘old’.

Thanks!

**Comment by Balamurugan-dot** [comment]
> Thank you for you response Cabailey,
> 
> Customer basically requested us to correct the wording **‘Older features’** because it’s a mistake on the current article that needs to be corrected now. Once we bring these features into M365 compliance center, we can then use the term ‘old’.
> 
> Thanks!

Thank you for you response Cabailey,

Customer basically requested us to correct the wording ‘Older features’ because it’s a mistake on the current article that needs to be corrected now. Once we bring these features into M365 compliance center, we can then use the term ‘old’.

Thanks!

**Comment by cabailey** [comment]
@Balamurugan-dot   Thank you for your clarification from your customer.  MRM is an older solution for retaining and deleting emails than Microsoft 365 retention policies and retention labels. That's not an inaccurate comparative statement. The word "older" doesn't mean it's deprecated or unsupported, however - at least, not yet. We intentionally used the word "older" to signal to customers that no current or new investments are being made in MRM (unlike Microsoft 365 retention) and if customers are looking to retain and/or delete emails, they are best served by using Microsoft 365 retention unless they need the specific MRM features listed. 

By using the newer technology, customers will benefit from newer features and ongoing investment, integration with other workloads for lower administrative overheads, and not have to worry about a migration plan if/when MRM is deprecated.  I don't have deprecation dates for MRM and it's unlikely to be before archiving is available as a Microsoft 365 Compliance offering, but customers should expect it will happen and plan accordingly.

**Comment by Balamurugan-dot** [comment]
@cabailey - Thank you very much for the detailed explanation. One last ask. 

Customer also mentioned about the below ability which is not achievable through M365 compliance center:

The same ability when using retention tags within EAC to manage individual mailbox folders (Not referring to Personal Tags)
		Eg Retention Tag: Delete mail from “Deleted Items” folder after 30 days or from “Junk Email” folder 
Or will this all move to PowerShell?

**Asks**

Do we have plan to move this behavior as well to M365 Compliance center? 
Do we have a plan to bring in any Azure PowerShell to achieve this?

Thank you very much once again for your help!

**Comment by cabailey** [comment]
@Balamurugan-dot   You are asking about the second bullet, the ability for an administrator to apply a policy for a specific folder rather than the whole mailbox?  I haven't heard whether there are plans for Microsoft 365 retention to support this in either the compliance center or PowerShell, and there could be a less compelling argument to do so if there are alternatives to achieve the same result with retention labels.  But I have no control over this decision and it would probably be dependent on customer demand.  Plans for both of these MRM features aren't yet decided so I recommend you keep an eye on the Microsoft 365 roadmap (https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=compliance).

**Comment by Balamurugan-dot** [comment]
@cabailey - Makes sense, Thank you very much for your outputs. Really appreciate your time and let us know this outcomes. Merry Christmas and Happy New Year 2022!

**Comment by cabailey** [comment]
@Balamurugan-dot   Seasons greetings to you, as well!  Closing this issue.
