### ISSUE TITLE
Offboarding Issue using local script

### ISSUE THREAD

**Issue by curiousbwoy** [MicrosoftDocs/microsoft-365-docs#7227]
[Enter feedback here]
There is no enough supporting documents & steps available for offboarding information.
Also the checklist to verify whether the offboarding was successful or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f044e756-d5d8-5db6-edbb-f042b1b22b3c
* Version Independent ID: 5d016fa2-3407-e757-1595-118728158c46
* Content: [Onboard Windows devices using a local script](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-script?view=o365-worldwide#offboard-devices-using-a-local-script)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-script.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-script.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
The running of the script is the actual offboarding. The result is that the device will no longer appear in the device inventory.
