### ISSUE TITLE
Confusing help 

### ISSUE THREAD

**Issue by telstar-dev** [MicrosoftDocs/microsoft-365-docs#7230]
[Enter feedback here]

This is not helpful. What does this even mean? That you don't know what your system will do in this case?

"If user enabled Focused Inbox at some point in the past:

Clutter settings will never appear

Otherwise,

Clutter settings will appear"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122fb260-6533-c67b-0d9c-5282a73989c0
* Version Independent ID: 33bb5e77-e3cd-976e-f333-1d80e1475caa
* Content: [Configure Clutter for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/configure-clutter?redirectSourcePath=%252fen-us%252farticle%252f832276bd-d024-47b6-a80a-a6b884907a5b&view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-clutter.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-clutter.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@telstar-dev  Thank you for your feedback. If a user has enabled  Focused inbox even once in the past, the clutter settings will never appear. If they have not enabled it both clutter as well Focused inbox options will appear.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @telstar-dev Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
