### ISSUE TITLE
Addtional step to clarify how to reach subscription details page

### ISSUE THREAD

**Issue by CarnegieJ** [MicrosoftDocs/microsoft-365-docs#7231]
[Enter feedback here]

Please update Step 2 "On the Products tab, in the Software section, select the software that you want to download."

Suggestion:

Step 2: On the Products tab, click the download target hyperlinked product name to navigate to the subscription details page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f67ebee8-4451-c7d4-2c00-720e1886ea12
* Version Independent ID: 60e9e39f-3906-150a-f455-375dbdfe119d
* Content: [Download perpetual software and product license keys bought through the Cloud Solution Provider (CSP) program - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/download-software-licenses-csp?view=o365-worldwide#download-software-and-product-license-keys)
* Content Source: [microsoft-365/admin/setup/download-software-licenses-csp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/download-software-licenses-csp.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@CarnegieJ Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7244

Thanks
Sri

**Comment by UniversalDevGit** [comment]
On Step 2: could On the Products tab, in the Software section, select the software that you want to download, actually be changed to Step 2: On the Products tab, click the download target hyperlinked product name to navigate to the subscription details page?   If you click on the check box, there is no options that come up, so the check box seems kind of pointless, you have to click on the product name.

On Step 3:  On the subscription details page, in the Downloads & keys section, choose the Product version, Language, and CPU & file type, then select Download, where is the download and keys section?  All I have is download and install software, which does not lead to what Step 4 is asking.

**Comment by rconiv** [comment]
On Step 2: could On the Products tab, in the Software section, select the software that you want to download, actually be changed to Step 2: On the Products tab, click the download target hyperlinked product name to navigate to the subscription details page?   If you click on the check box, there is no options that come up, so the check box seems kind of pointless, you have to click on the product name.

On Step 3:  On the subscription details page, in the Downloads & keys section, choose the Product version, Language, and CPU & file type, then select Download, where is the download and keys section?  All I have is download and install software, which does not lead to what Step 4 is asking.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@rconiv Thank you for your feedback. We have made changes to the existing PR. Once the author approves, the changes will be live.

Thanks
Sri

**Comment by tiburd** [comment]
Closing this PR.
Article language complies with Microsoft style guidelines.

cc: @msbemba @yogkumgit
