### ISSUE TITLE
Where do these LABELS  get set?

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/microsoft-365-docs#7232]
The MDE portal mentions you need to create an MDMManaged Device Tag in MDE portal. This documentation does not reflect that - as an MDE device tag "MDEManaged" would allow the customer to select which devices get AAD Registered. This article reads as if the device automatically gets AAD registered and then a "LABEL" (MEM/AAD uses LABELS, MDE uses TAGS).

Confusing and clear as mud.

Please clarify if the LABEL is an MDE TAG or a SYSTEMLABELS value in AAD or SYSTEMLABELS within Intune (Dynamic group filter SYSTEMFILTERS)....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e93f9bbd-5752-e28a-f32d-a01d81964c8f
* Version Independent ID: e93f9bbd-5752-e28a-f32d-a01d81964c8f
* Content: [Manage Microsoft Defender for Endpoint configuration settings on devices with Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/security-config-management?view=o365-worldwide&source=docs#create-azure-ad-groups)
* Content Source: [microsoft-365/security/defender-endpoint/security-config-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/security-config-management.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by vboyev-MSFT** [comment]
To be clear - Intune Group - would be Dynamic and the query would be either 
(device.managementType -contains "MDEJoined") this would be the group we could target MEM automatic onboarding to - I suppose
or (device.managementType -contains "MDEManaged") - apply policy to.

So it looks as if -
1. Device appears as Can Be Onboarded in MDE portal
2. Tag device with MDE-Managed in MDE portal Device Tags (regkey/portal or API)
3. Device will AAD Register
4. With a dynamic device group in Intune, you can target an Intune/MEM onboarding policy
5. With a dynamic device group in Intune - you can now target/assign AV and Firewall policies to these devices.

Did I get that right?

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Yes I believe that's outlined steps are right.
