### ISSUE TITLE
Clarification of Set-AuthServer DomainName value

### ISSUE THREAD

**Issue by wperry1** [MicrosoftDocs/microsoft-365-docs#7233]
In the Set-AuthServer cmdlet below, is the Tenant Domain the mail domain, AD domain, xxx.onmicrosoft.com domain? It is also a multi-value field. Does it need more than one of the above?

Set-AuthServer -Identity "EvoSTS - {GUID}" -DomainName "Tenant Domain" -IsDefaultAuthorizationEndpoint $true

Thank you in advance for clarifying.

WP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae987bba-faf5-916d-c3b1-74f547ff8d90
* Version Independent ID: 9f5a7979-af5a-8fbf-45f0-287bb9fa4772
* Content: [How to configure Exchange Server on-premises to use Hybrid Modern Authentication - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/configure-exchange-server-for-hybrid-modern-authentication.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@wperry1 Thank you for your feedback. The Tenant domain is xxx.onmicrosoft.com for this document and it is a multivalued property as you can add multiple domains (in case if an exchange is in hybrid with multiple tenants).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @wperry1 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by wperry1** [comment]
Thank you for the clarification.
