### ISSUE TITLE
Need example to disable self service of all products, and error on example

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/microsoft-365-docs#7234]
I believe it would be very helpful to have an example on this page where one can disable self service for all product types. 

I also ran the example script to disable products with a certain name like others, and I received the following error:

PS C:\WINDOWS\system32> $product = Get-MSCommerceProductPolicies -PolicyId AllowSelfServicePurchase | where {$_.ProductName -match 'Power Automate'}
PS C:\WINDOWS\system32> Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId $product.ProductID -Enabled $false
Update-MSCommerceProductPolicy : Cannot process argument transformation on parameter 'ProductId'. Cannot convert value
to type System.String.
At line:1 char:78
+ ... licyId AllowSelfServicePurchase -ProductId $product.ProductID -Enable ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-MSCommerceProductPolicy], ParameterBindingArgumentTransformatio
   nException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Update-MSCommerceProductPolicy

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@StuBeck32 Thank you for your feedback. The documents usually do not contain scripts and they need to be customized by the customer based on requirements.

In your case, I think the reason it fails is that there are multiple products. So I'd use for each to resolve it.

![image](https://user-images.githubusercontent.com/45987684/147201861-81590103-a6ac-4eb6-81a0-9777c970de98.png)


If this still doesn't resolve, I'd recommend contacting support via the need help section on the admin center and they should be able to help you out.

**Comment by StuBeck32** [comment]
Why can't this be added to the main document detailing how to disable this?

**Comment by msbemba** [comment]
@StuBeck32 Thank you for your feedback If there are multiple values for the product, you can run the command individually for each value as shown in the following example and that is what we recommend. Scripts are for advanced users and we do not know the number of values for product till they run it. Customer's can script every single cmdlet for custom requirements, but we refrain from adding custom scripts in docs to avoid confusion.

Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId $product[0].ProductID -Enabled $false
Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId $product[1].ProductID -Enabled $false

Thanks
Sri

**Comment by StuBeck32** [comment]
To clarify, the script in the original document does not work, which is what I reported on. You've given me a perfectly good script that does, but you can't add it to the document. 

I'm not positive why the script given in the original document can not be resolved to one that does work, or why you can't add the one you sent earlier today to the main document. There are going to be many users who want to disable self service, and that is the way to do it. Having scripts which knowingly don't work isn't very helpful for anyone.

**Comment by msbemba** [comment]
@StuBeck32  The script in the document is for one product.  We have added a line now to  the document  stating if there are multiple  values for the product, You can run the command individually (this should clear the ambiguity)

![image](https://user-images.githubusercontent.com/45987684/147262082-e2d3f873-010f-4044-ac19-c773d3c55382.png)

Thanks
Sri

**Comment by StuBeck32** [comment]
The example script which does not work is still there. It is under Example script to disable AllowSelfServicePurchase

**Comment by msbemba** [comment]
@StuBeck32 Thank you. I have made changes to that script to match a particular product instead of just power automate. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7257

Thanks
Sri

**Comment by StuBeck32** [comment]
Thank you.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @StuBeck32 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jnickell** [comment]
I do not believe the provide code is functional.  Should this be a new case? 
See snippet below:

`\> $product = Get-MSCommerceProductPolicies -PolicyId AllowSelfServicePurchase | where {$_.ProductName -match 'Power Automate per user'}
PS Scripts:\> $product
PS Scripts:\> Get-MSCommerceProductPolicies -PolicyId AllowSelfServicePurchase

PolicyValue ProductId    PolicyId                 ProductName
----------- ---------    --------                 -----------
Disabled    CFQ7TTC0LH3L AllowSelfServicePurchase Power Automate per user`

Running Powershell version 5.1.22621.1778, installed the MSCommerce module today
