### ISSUE TITLE
Information is not correct

### ISSUE THREAD

**Issue by roojs** [MicrosoftDocs/microsoft-365-docs#7237]
Tried all of this - and still getting reject messages from multiple 365 hosted domains

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Remove yourself from the blocked senders list - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@roojs Thank you for your feedback. It may take up to 24 hours or results can vary widely before restrictions are removed. If the issue still persists, I'd recommend you to contact Microsoft support via the need help link on the admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @roojs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by roojs** [comment]
"contact Microsoft support" - it's likely when this happens you may not be a Microsoft customer, and will not be able to contact MS Support. 

We are lucky that I have a relationship with someone who was a customer and they reported it, but there is a serious issue that there is no way to solve undeliverable messages at present (no support actually seems to exist)

BTW - even when we did report to MS Support - it took over a week (and I'm not actually sure it's been resolved), which is a serious problem, (and this was for a MS customer)
