### ISSUE TITLE
Documentation on Defender for Endpoint does not mention "Process Memory Indicators"

### ISSUE THREAD

**Issue by JLangthaler** [MicrosoftDocs/microsoft-365-docs#7238]
While Indicators are [well documented](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-indicators?view=o365-worldwide), there is no mention whatsoever on Process Memory Indicators in the documentation. Since this feature is available in the M365 Defender Portal, there should be documentation.
![image](https://user-images.githubusercontent.com/22906534/146902835-9b0715fa-8555-401a-8dcd-49fca11babb0.png)

**Comment by patrickboeck** [comment]
of course, more information needed how to deal with it

**Comment by graser93** [comment]
would be also interesting for me!
please provide some documentation

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Will suggest to team.

**Comment by carlokohan** [comment]
Has anyone use this feature?
