### ISSUE TITLE
There's A New Exchange Admin Center - Update Docs To Match

### ISSUE THREAD

**Issue by MHCLV** [MicrosoftDocs/microsoft-365-docs#7239]
This article is next to useless because this function has been removed from the old EAC and the document does not mention the new EAC, let alone how to actually get the tasks done.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@MHCLV This article has step-by-step instructions to enable archive mailbox in the M365 compliance center. Alternatively, you can enable archive mailboxes in the M365 admin center, the old EAC, the new EAC, and Exchange Online PowerShell. Regardless of which admin tool you use, the archive mailbox will be enabled. In the new EAC, go to Recipients > Mailboxes. Select a user. In the flyout page, under More actions, select "Manage archive mailbox."

Hope this helps.

![image](https://user-images.githubusercontent.com/36746813/146983582-d616c6eb-588a-46b9-b93e-6f8dd5735cee.png)
