### ISSUE TITLE
Great article.Please add videos 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/microsoft-365-docs#724]
This article is supprised to me, and this will eater all the office 365 users.
If the video demonstration gives more comfortable to users.
Thanks to all  authors.
If I find  suitable video demonstration, then I will create a PR 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 980399d9-b70f-fc0e-e723-81d4d6550f25
* Version Independent ID: cda440d4-dab3-a0ad-c46a-55e699e885e9
* Content: [Microsoft 365 Enterprise Test Lab Guides](https://docs.microsoft.com/en-us/microsoft-365/enterprise/m365-enterprise-test-lab-guides#feedback)
* Content Source: [microsoft-365/enterprise/m365-enterprise-test-lab-guides.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/m365-enterprise-test-lab-guides.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@RAJU2529 Thanks for your comments. I will add the videos idea to our documentation backlog.
