### ISSUE TITLE
SIEM integration no longer available

### ISSUE THREAD

**Issue by Amatziab** [MicrosoftDocs/microsoft-365-docs#7241]
[Enter feedback here]
Hi,
This option is no longer available in the admin center.
![image](https://user-images.githubusercontent.com/48100745/146935332-f057094e-6415-495f-a266-9ece4f3279f0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36bbd71-ef7b-e08f-d565-d2b1e8b9deed
* Version Independent ID: 60fad392-2d82-84ca-6b0b-671122738b38
* Content: [Enable SIEM integration in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-siem-integration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-siem-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-siem-integration.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Amatziab Thank you for your feedback. We have added an important note that the feature is not supported effectively immediately. The document will be taken down or modified closer to the date. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7252

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Amatziab Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
