### ISSUE TITLE
Don't overstate permissions needed

### ISSUE THREAD

**Issue by michaelblumenthal** [MicrosoftDocs/microsoft-365-docs#7243]
The page currently says:
"To use the MSCommerce PowerShell module, you need:
- A Windows 10 device
- PowerShell 5 or below. Currently, PowerShell 6.x/7.x isn't supported with this module.
- Administrator permission for the device
- Global or Billing Admin role for your tenant"

However, you do NOT need Administrator permission for your device.  If you run the Install-Module cmdlet with the parameter
-Scope CurrentUser, you do NOT need to be administrator on your machine.  In other words, the syntax that uses the least permissions is "Install-Module -Name MSCommerce -Scope CurrentUser"

Also, if you are a Global Reader (not Global Admin), that is enough to be able to query the Commerce Product Policies. Therefore, a better way to say this is that you need Global Admin or Billing Admin if you want to change the Commerce Product Policies but you only need Global Reader if you just want to view them.  

Finally, I suspect that this will work on a Windows 11 device, so perhaps one should say that the minimum OS version is 10?  Is there a minimum build number of Win 10 that is needed?  It works with Win 10 1909 from my experience.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@michaelblumenthal Thank you for your feedback. It works on Windows 10 or later (no minimum build needed). We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7253

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @michaelblumenthal Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
