### ISSUE TITLE
what happens when expirationTime passes?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/microsoft-365-docs#7245]
Is the indicator automatically deleted?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03d3a25-4ee0-0c3a-4fde-c6f9ef7a3773
* Version Independent ID: b08640a7-7e66-2653-bf3f-727fbb90709d
* Content: [Manage indicators](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-manage?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/indicator-manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/indicator-manage.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by anwarmahmood1** [comment]
tested: the indicator is deleted.  

please add this to the documentation

**Comment by msbemba** [comment]
@anwarmahmood1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7254

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @anwarmahmood1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
