### ISSUE TITLE
Article needs update to remove Search by ID List feature

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/microsoft-365-docs#7249]
Hi Team,

The article needs an update. The Search by ID list has been deprecated.

(Updated) Microsoft 365 Compliance Center Core eDiscovery - Search by ID list retirement
MC291088 · Published Oct 13, 2021 · Last updated Oct 13, 2021

Message Summary
Updated October 13, 2021: We have updated this message with additional details for clarity.

We will be retiring the option to Search by ID list, as it is not functioning to an adequate level and creates significant challenges for organizations who depend on consistent and repeatable results for eDiscovery workflows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edf6054e-d069-a63c-8b7a-7dbbe98f0748
* Version Independent ID: e9344a15-d168-67e2-925a-004d7e7b187d
* Content: [Search for content in a core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-content-in-core-ediscovery?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/search-for-content-in-core-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-content-in-core-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@kumaarrahul Thanks for heads up. The "Recommended Content" list at the bottom of this topic is auto-generated. I will retire/remove the search ID topic that it linked to and that should remove it from the list.
