### ISSUE TITLE
Missing operations from 'Audited Activities' section

### ISSUE THREAD

**Issue by miss-tech** [MicrosoftDocs/microsoft-365-docs#7250]
I have found that there are quite a few operations which are not included in the 'Audited Activities' section. In particular the Azure AD Application section is missing the following entries and descriptions for operations:

Consent to application.
Update service principal.
Add service principal credentials.
Add app role assignment grant to user.
Add owner to application.
Update application.
Update application – Certificates and secrets management
Add a deletion-marked app role assignment grant to user as part of link removal.

Thanks, Emily

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide&source=docs#application-administration-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@miss-tech Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
