### ISSUE TITLE
Unexplained asterisks on products

### ISSUE THREAD

**Issue by alesteravo** [MicrosoftDocs/microsoft-365-docs#7251]
Under the section "View a list of self-service purchase products and their status" where the products are listed, the Project and Visio products have asterisks beside them. These aren't explained either in that section or at the bottom of the page. They should either be removed to avoid confusion, or a footnote should be added to explain what the asterisks are intended to denote.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by RAJU2529** [comment]
Today I will try to add explanation

**Comment by RAJU2529** [comment]
@yogkumgit, Please look in this PR #7273.

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @alesteravo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
