### ISSUE TITLE
Incorrect or incomplete documentation about pre-requisites for creating new import jobs.

### ISSUE THREAD

**Issue by yvesrosius** [MicrosoftDocs/microsoft-365-docs#7256]
Incorrect or incomplete documentation about pre-requisites for creating new import jobs.

Article states under **Before you import PST files** that a global administrator can create import jobs. This is not the case. A role still needs to be applied.

https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#before-you-import-pst-files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@yvesrosius Thanks for feedback. The first bullet in the "Before you begin" section states that you need to be assigned the Mailbox Import Export role in Exchange Online. You also need to be assigned the Mail Recipients role in Exchange Online as well. 

https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#before-you-import-pst-files

The Mailbox Import Export role enables you to access the "Create import job" tool in the compliance center and to create PST import job requests. The Mail Recipients role allows the PST import service to access and write to user mailboxes on behalf of the user who creates the PST import job in the compliance center.

**Comment by yvesrosius** [comment]
@markjjo Thanks for having a look at it.

Yes, this information is correct. However, the article states you don't need them if you are a global admin in the tenant.

```
Also, to create import jobs in the Microsoft 365 compliance center, **one of the following must be true:**

You have to be assigned the Mail Recipients role in Exchange Online. By default, this role is assigned to the Organization Management and Recipient Management roles groups.

**Or**

**You have to be a global administrator in your organization.**
```

**Comment by markjjo** [comment]
@yvesrosius I'll try to make this clearer. The permissions requirement is:

Mailbox Import Export role + Mail Recipients role

OR

Mailbox Import Export role + Global admin 

A global admin is assigned the Mail Recipient role because this role is assigned to the Organization Management role group in EXO and global admins, by default, are members of the Organization Management role group in EXO.

**Comment by markjjo** [comment]
That is, I will try to make this clearer in the "Before you begin" section in article.

**Comment by yvesrosius** [comment]
Thank you Mark! That makes sense :-)
