### ISSUE TITLE
Need More Details On Setting Up Cross Tenant Access For Teams Shared Channels

### ISSUE THREAD

**Issue by imrananwar** [MicrosoftDocs/microsoft-365-docs#7260]
Need More Details On Setting Up Cross Tenant Access For Teams Shared Channels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f0db07-fbeb-7a8e-aa94-297b5f808216
* Version Independent ID: 0fec134e-c8a3-50ec-7094-31ca70cb42ba
* Content: [Microsoft 365 inter-tenant collaboration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-inter-tenant-collaboration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-inter-tenant-collaboration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-inter-tenant-collaboration.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving the issue. Thanks

**Comment by kelleyvice-msft** [comment]
In my understanding, documentation for Teams Shared Channels across tenants isn't available at this time as the feature is still in Public Preview. Additional information about Shared Channels is available here: https://docs.microsoft.com/en-us/MicrosoftTeams/shared-channels. You can check https://techcommunity.microsoft.com/t5/microsoft-teams-blog/bg-p/MicrosoftTeamsBlog or subscribe to the RSS feed from the blog for new information.
