### ISSUE TITLE
Content out of date in multiple places, 

### ISSUE THREAD

**Issue by bruceburge** [MicrosoftDocs/microsoft-365-docs#7263]
Content out of date in multiple places, the UI has significantly changed and many of the suggested paths are not accurate to the new menu.  Please review these paths and correct them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf5c5df-c3ab-8448-aef0-af05977db9b9
* Version Independent ID: adade895-f42b-1029-9948-5ddb5b038257
* Content: [Quarantine policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide#configure-global-quarantine-notification-settings-in-the-microsoft-365-defender-portal)
* Content Source: [microsoft-365/security/office-365-security/quarantine-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bruceburge, the only thing that I could find that was out-of-date was the very first step for getting to quarantine policies in 5 locations It said this:

> In the [Microsoft 365 Defender portal](https://security.microsoft.com), go to **Email & collaboration** \> **Threat policies** \> **Rules** section \> **Quarantine policies** and then select **Quarantine policies**.

It should say this:

> In the [Microsoft 365 Defender portal](https://security.microsoft.com), go to **Email & collaboration** \> **Policies & Rules** \> **Threat policies** \> **Quarantine policies** in the **Rules** section.

I fixed all 5 instances. That was all that I could find wrong.

**Comment by yogkumgit** [comment]
@bruceburge Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
