### ISSUE TITLE
Security & Compliance Center PowerShell Question

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/microsoft-365-docs#7264]
Can a link be added to an article that shows how to load the Security and Compliance Center PowerShell?

Microsoft 365 retention policies
Run the following command in Security & Compliance Center PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4119f918-a0b2-4bdc-535e-11d2c476f675
* Version Independent ID: 1520175d-398b-4df1-86db-8ba6b26260df
* Content: [How to identify the type of hold placed on an Exchange Online mailbox - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@rconiv Thanks for feedback. I added a link to help topic on connecting to SCC PowerShell in this retention policies section: https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox?view=o365-worldwide#microsoft-365-retention-policies
