### ISSUE TITLE
Required license?

### ISSUE THREAD

**Issue by CharLind87** [MicrosoftDocs/microsoft-365-docs#7268]
Does the migration require M365 Business Premium licenses as the lowest license plan or is this just the chosen license for the guide?

**Comment by denisebmsft** [comment]
Hello @CharLind87. Can you tell us to which article(s) your feedback applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by CharLind87** [comment]
Hi,
Sorry it's referring to this page: Switch from Google Workspace to Microsoft 365 for business | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/business-video/moveto-microsoft-365/move-from-google-workspace-overview?view=o365-worldwide>

**Comment by msbemba** [comment]
@CharLind87 Thank you for your feedback. This document pertains to switching from Google Workspace to Microsoft 365 for business. out of the three flavors available in M365 for business, only M365 Business premium has all the options like Security, Office install, etc. So I'd say for this guide the minimum requirement is M365 Business premium.

We also have another document - https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration which talks about the migration from Googleworkspace in general and that might be helpful.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @CharLind87 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
