### ISSUE TITLE
Audit log verification

### ISSUE THREAD

**Issue by ErNestB3** [MicrosoftDocs/microsoft-365-docs#7269]
This article is out of date regarding audit log verification. When will the update be? How can I verify the logs in the new Audit log center? https://compliance.microsoft.com/auditlogsearch 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by markjjo** [comment]
@ErNestB3 Thanks for feedback. We're working to update the article. In the mean time, you can run an audit log search and search for all activities, as per the current guidance. Then you can export those search results to a csv file, and then open in Excel. Here's how to export: https://docs.microsoft.com/en-us/microsoft-365/compliance/export-view-audit-log-records?view=o365-worldwide

Then you can filter on the Operations column to display records for Set-AccessToCustomerDataRequest and filter on the UserIds column to display activities performed by "Microsoft Operator". You can also folllow the steps in Step 2 to format the exported audit log using the Power Query Editor, which will parse the AuditData JSON object into multiple columns for better filtering and display.

Hope this helps.

**Comment by ErNestB3** [comment]
@markjjo Thanks for your comment. Viewing the log audit in a csv file is difficult. One day file is 85MB. Export of all activity results to csv file from 90 days is impossible to review. Is there another option for auditing this activity?

**Comment by markjjo** [comment]
@ErNestB3 You can try using the **Search-UnifiedAuditLog** cmdlet in Exchange Online PowerShell. 

https://docs.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog

Use the Operations parameter and specify Set-AccessToCustomerDataRequest. Something like:

Search-UnifiedAuditLog -StartDate xxx -EndDate xxx -Operations Set-AccessToCustomerDataRequest

You could also include -RecordType ExchangeAdmin to scope the search only to Exchange admin cmdlets. If you knew the alias of the admin performing the action you could also include that: -UserIds <alias>

Here is documentation for exporting  audit records for PowerShell: https://docs.microsoft.com/en-us/microsoft-365/compliance/export-view-audit-log-records?view=o365-worldwide#use-powershell-to-search-and-export-audit-log-records

We also have an article on using a PowerShell script to search the audit log: https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-search-script

The script exports the results to a csv file. For the $record variable, use ExchangeAdmin 

FYI that engineering is looking into ways to make this Customer Lockbox scenario easier to accomplish. I'll try to remember to follow up on this thread if/when that happens. Until then, I will update the Customer Lockbox article with the above strategies for searching/exporting.
