### ISSUE TITLE
german translation contains incorrect/misleading information

### ISSUE THREAD

**Issue by andreaseliasnts** [MicrosoftDocs/microsoft-365-docs#7270]
Hello,

in the german version, in the table <what happens to existing encryption when a sensitivity label is applied to that content>, the english text "New label encryption is applied" is currently translated as "Es wird keine neue Verschlüsselung mit Bezeichnung angewendet". The meaning is really the opposite of the english text, please change to something like "Neue Verschlüsselung wird angewendet".

Best regards,
Andreas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Restrict access to content using sensitivity labels to apply encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#how-to-configure-a-label-for-encryption)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@TinaMcN Please help us in resolving this issue. Thanks

**Comment by TinaMcN** [comment]
@andreaseliasnts thanks for reporting the issue, I'm working to get it fixed in the German article.

**Comment by TinaMcN** [comment]
@andreaseliasnts the translation has been fixed and changed to "Neue Verschlüsselung der Bezeichnung wird angewendet". https://docs.microsoft.com/de-de/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#how-to-configure-a-label-for-encryption   Thanks again for letting us know about this.

**Comment by andreaseliasnts** [comment]
@TinaMcN translation is now ok, thanks for the fast fix :) !
