### ISSUE TITLE
Miss leading RH versions supported

### ISSUE THREAD

**Issue by kotras** [MicrosoftDocs/microsoft-365-docs#7271]
The RH versions are not clear. Need or only to have RH 6.7 and higher, has we have for major versions. But if the purpose is to mention minor versions it should have also RH 8 and higher and RH9 and higher, since all are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@kotras Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7291

Thanks
Sri

**Comment by yogkumgit** [comment]
@kotras Reported to PG. Thanks for the feedback.
