### ISSUE TITLE
What if email is deleted?

### ISSUE THREAD

**Issue by Dburke225** [MicrosoftDocs/microsoft-365-docs#7274]
Can you explain why sometimes we are unable to preview or download an email. Whenever I'm investigating I find emails that say they were deleted from the server. How am I supposed to review these?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2a332c-34ed-49fd-519a-4df38e9f4f60
* Version Independent ID: 19968ae0-b43e-d02d-fee3-14da766c7832
* Content: [Investigate malicious email that was delivered in Microsoft 365, Find and investigate malicious email - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/investigate-malicious-email-that-was-delivered.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Dburke225 Thank you for your feedback. Threat Explorer gives your security operations team the details they need to investigate suspicious emails.  If you receive error on certain messages, We recommend you to contact Microsoft support via the need help section on the admin center,  so they can investigate and resolve it.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Dburke225 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
