### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by FMofDeath** [MicrosoftDocs/microsoft-365-docs#7275]
In the 'Before you begin' section, the "an" in the following sentence needs to be replaced with an "a".

"You must be an global admin or password administrator to perform these steps."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52c6916-7e79-9a9c-b7a6-47041ddb81e3
* Version Independent ID: 43c9b873-d354-d814-3065-1e8832361b86
* Content: [Set an individual user's password to never expire - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by denisebmsft** [comment]
There's also a link issue in the "Before you begin" section.

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @FMofDeath Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
