### ISSUE TITLE
Add Corelight NDR to Network security section

### ISSUE THREAD

**Issue by esmithcl** [MicrosoftDocs/microsoft-365-docs#7278]
I suggest adding 'Corelight Open NDR' to the 'Network security' section for completeness as the integration is already mentioned elsewhere in the MDE documentation: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/corelight-integration?view=o365-worldwide

The Corelight logo is available here: https://corelight.com/hs-fs/hubfs/raw_assets/public/Corelight_May2021/images/logo-corelight.png

The 'Corelight Open NDR' Partner name can link to this page: https://corelight.com/integrations/iot-security

Here is text that can be used for the description (from the MDE doc linked above): "Using data, sent from Corelight network appliances, Microsoft 365 Defender gains increased visibility into the network activities of unmanaged devices, including communication with other unmanaged devices or external networks."

Please let me know if I can help with sizing the logo graphic or anything else. Thank you!
edward.smith@corelight.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b6f3ea-6ff6-9b97-578a-c9a31fb38eab
* Version Independent ID: 08d35852-6da9-f663-1b8f-80d98eb24b54
* Content: [Partner applications in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/partner-applications?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/partner-applications.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/partner-applications.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Yes will work on this.
