### ISSUE TITLE
HIPAA for Windows??

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/microsoft-365-docs#728]
I was wondering why Microsoft doesn't include Windows as part of the "Microsoft in-scope cloud services" now that Windows is (or can be) subscription based?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545aa0d-ba68-3113-413b-0c0b176b08bd
* Version Independent ID: bb2ce8e1-7f40-e5ed-60c4-f8bb0912661d
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-hipaa-hitech)
* Content Source: [microsoft-365/compliance/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@AndySanchezVM  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@AndySanchezVM - thanks for the feedback, we're discussing this with our internal stakeholder teams and I'll update this thread soon. Thanks!

**Comment by AndySanchezVM** [comment]
@robmazz - Any update on this?

**Comment by robmazz** [comment]
@AndySanchezVM - yes, apologies for the delay and thanks for the reminder. Windows is an operating system for PCs and servers, and also powers Azure - but isn't included in how we define online services. Please see our online service terms on how we define Microsoft online services. - https://www.microsoft.com/en-us/licensing/product-licensing/products
