### ISSUE TITLE
Setting doesn't exist

### ISSUE THREAD

**Issue by armattt** [MicrosoftDocs/microsoft-365-docs#7280]
Settings vaguely described in section 'Allow everyone to see the Sent email (the replies)' do not exist. 

See available settings in screenshot.
![Screen Shot 2021-12-30 at 10 06 36 pm](https://user-images.githubusercontent.com/96871731/147750970-0d69eb41-9a49-4ac5-857d-a22fb1367c9a.jpg)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198eb002-1d99-5a13-05d4-34d1cbb8d9d9
* Version Independent ID: 6218b3c9-f0a2-ed0e-ef0a-c99c3c280030
* Content: [Configure shared mailbox settings - Microsoft 365 admin](https://docs.microsoft.com/en-au/microsoft-365/admin/email/configure-a-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/configure-a-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/configure-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@armattt Thank you for your feedback. I was able to test this in our lab and it works as described.

![image](https://user-images.githubusercontent.com/45987684/147912512-2bfcbf0c-d6ec-4415-828d-4dc1c6dde2fd.png)

Looks like you might be in the Exchange admin center instead of the M365 admin center(https://admin.microsoft.com/)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @armattt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
