### ISSUE TITLE
Set-CsOAuthConfiguration -Identity global -Realm "contoso.com"

### ISSUE THREAD

**Issue by Dlcowjd7252** [MicrosoftDocs/microsoft-365-docs#7283]
- [ ] Set-CsOAuthConfiguration -Identity global -Realm
#- - - [_**@![image](https://user-images.githubusercontent.com/81820055/147824916-05bc7fa5-2dfe-458b-b100-6f394a1024d0.jpeg)**_]()~~~~"contoso.com"```

```

**Comment by msbemba** [comment]
@Dlcowjd7252 Thank you for your feedback. The command Set-CsOAuthConfiguration -Identity global -Realm "contoso.com" modifies the global collection of OAuth configuration settings. The Realm property is set to "contoso.com".

The cmd is correct. If you think there is an issue with the cmdlet let us know.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Dlcowjd7252 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
