### ISSUE TITLE
 Edit billing frequency is greyed out 

### ISSUE THREAD

**Issue by PaulTippit** [MicrosoftDocs/microsoft-365-docs#7287]
[Enter feedback here]
 Edit billing frequency is greyed out 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d66f21-cff3-bb96-df38-6f67d95eb6cf
* Version Independent ID: 00256bad-f01c-02a6-9554-a0be1ce933ea
* Content: [Change your billing frequency](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-payment-frequency?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-payment-frequency.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-payment-frequency.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@PaulTippit Thank you for your feedback. I was able to test in multiple tenants and the option to edit billing frequency is not grayed out.

![image](https://user-images.githubusercontent.com/45987684/147910464-3e016402-2716-42eb-82f6-bcdcda4867cc.png)

If this is still an issue, I'd recommend you contact Microsoft support via the need help section on the M365 admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PaulTippit Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by djmrky** [comment]
This option is grayed out for me too
![image](https://user-images.githubusercontent.com/29006279/209734423-9b440423-5a6c-41f6-9f2a-4f2f2bb34a67.png)

How can I change this?
