### ISSUE TITLE
Error cause to blank page issue in Import Job Office 365 Compliance Admin Portal 

### ISSUE THREAD

**Issue by Mghannaj** [MicrosoftDocs/microsoft-365-docs#7288]
Hay Fellas,

Greetings. I just wanted to drag your attention to an issue when I use Import job wizard this "https://compliance.microsoft.com/informationgovernance?viewid=import" specifically.
I go through to step one naming the import job. Then the method of uploading the PST using Network or Ship a drive. 

When I proceed after step2 I reach blank page like the below figure. I tried all kind of browsers and the issue is everywhere only in my machine and all other pages and features are working fine with me.   

![image](https://user-images.githubusercontent.com/7113443/147862845-d4917861-a468-45a2-84f2-8a12f8818ae6.png)

**Comment by msbemba** [comment]
@Mghannaj Thank you for your feedback. I was able to test this in our lab and it works as expected.

![image](https://user-images.githubusercontent.com/45987684/147910929-96d49625-0b6f-4676-9ebd-75c42bac0590.png)


This could be a permission issue on your end. To create import jobs, you must be assigned the Mailbox Import Export role in Exchange Online. After this role is assigned, it might take up to 24 hours before you can start creating jobs.

Thanks
Sri

**Comment by Mghannaj** [comment]
> 

The same account working fine on different machine. I know the issue is only related to my machine. Can you direct me where to troubleshoot this issue? 

Thank you

**Comment by msbemba** [comment]
@Mghannaj You can contact Microsoft support for troubleshooting this issue. Please use the need help icon on your M365 Admin center to work with a Microsoft support engineer.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Mghannaj Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
