### ISSUE TITLE
Incorrect text and links - The Microsoft 365 Service Communications API has now been moved to Microsoft  Graph

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#7289]
In the section Track your message center tasks in Planner the text and the link in the following sentence is incorrect because the Microsoft 365 Service Communications API Overview has been replaced by Microsoft Graph 

If you'd like to program an alternative way to get real-time service health information and Message Center communications, please reference Microsoft 365 Service Communications API Overview.

The correct text is 'please reference service communications API in Microsoft Graph'
The correct link is https://docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f3771a-247c-4f85-992a-e671285c70bd
* Version Independent ID: f3c2890a-2470-9349-ff77-924cf8566365
* Content: [Message center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/message-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/message-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/message-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7290

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
