### ISSUE TITLE
Add Azure Active Directory?

### ISSUE THREAD

**Issue by chadhasbrook** [MicrosoftDocs/microsoft-365-docs#729]
Is it possible add Azure Active Directory as a Microsoft in-scope cloud services to make it easier to find? The answer was buried in the Overview of Microsoft Azure compliance doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b545aa0d-ba68-3113-413b-0c0b176b08bd
* Version Independent ID: bb2ce8e1-7f40-e5ed-60c4-f8bb0912661d
* Content: [Health Insurance Portability and Accountability (HIPAA) & HITECH Acts](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-hipaa-hitech?source=docs#feedback)
* Content Source: [microsoft-365/compliance/offering-HIPAA-HITECH.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-HIPAA-HITECH.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@chadhasbrook  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by robmazz** [comment]
@chadhasbrook - thanks for this feedback, we are talking through updates to the content architecture and I'll incorporate this feedback.
