### ISSUE TITLE
Markdown Link/URL malformed

### ISSUE THREAD

**Issue by SegersIan** [MicrosoftDocs/microsoft-365-docs#7294]
There is some malformed Markdown on top of the page:
```
 [What's an admin account?](Overview of the Microsoft 365 admin center](../admin-overview/admin-center-overview.md).
```
In the "Before you begin" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322ca91-2125-7486-887f-7c313f2fbcf9
* Version Independent ID: a139620d-3330-a687-709a-35bb270101e4
* Content: [Set the password expiration policy for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/set-password-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/set-password-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by gcaringal** [comment]
I submitted the same issue #7304 before seeing this one, sorry. As I wrote in my issue, however, this error exists on several pages.

**Comment by msbemba** [comment]
@SegersIan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7324

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SegersIan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
