### ISSUE TITLE
EOP quarantine notification french translation issue

### ISSUE THREAD

**Issue by SabRom** [MicrosoftDocs/microsoft-365-docs#7296]
Hello,

Two feedback that I'm not sure where to put : 

1- the link  "Feedback > This product" on https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages?view=o365-worldwide#feedback does not work anymore

2- French translation for EOP quarantine notification are awful, as shown here : https://imgur.com/a/cKd2cD9

Sentences in yellow does not respect French Grammar.

Sentence in red has just been forgotten by the translation program

It might seems trivial but, to an end user, receiving such an email does not look professional and might lead them to believe those emails are just one phishing attempt, which is a shame for a notification from EOP.

You can correct the yellow sentence with something like "1 message a été placé en quarantaine comme tentative de phishing. Examinez le avant le (datetime)".

Merci

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedcd379-0c7e-5b68-be04-e272ac53638d
* Version Independent ID: 664acd84-b4df-c943-e027-677f4340768e
* Content: [Quarantine notifications (end-user spam notifications) in Microsoft 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SabRom, you are correct in that product feedback is basically not available.

For the translation problem, your best way forward is to open a support ticket.

**Comment by yogkumgit** [comment]
@SabRom Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TinaMcN** [comment]
@SabRom an alternative way to provide translation feedback about the product is in the Microsoft Tech Community: https://techcommunity.microsoft.com/t5/localization-feedback/bd-p/LocFeecback

**Comment by SabRom** [comment]
@TinaMcN Thank you, I'll try my luck here as the support ticket is going nowhere.
