### ISSUE TITLE
Stale Content in Setup Guide

### ISSUE THREAD

**Issue by chasman157** [MicrosoftDocs/microsoft-365-docs#7297]
Content is outdated - ICON/Images outdated - Features missing

**Comment by denisebmsft** [comment]
Hello @chasman157. Can you please tell us to which article your feedback applies?

**Comment by chasman157** [comment]
So sorry, I thought the form gathered that with the "This site" question.

Here is the outdated site.  I do have direct knowledge and relationships with the Wizard CxE FastTrack Team if you need further information.

Setup guides for Microsoft 365 and Office 365 services - Microsoft 365 Enterprise | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/enterprise/setup-guides-for-microsoft-365?view=o365-worldwide>


Chuck VanDeweel
1+(469) 713-7393

**Comment by yogkumgit** [comment]
@chasman157 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by yogkumgit** [comment]
@msbemba Please resolve.

**Comment by chasman157** [comment]
I did reply:  See attached

Chuck VanDeweel
1+(469) 713-7393

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@chasman157 Thank you for your feedback. I see multiple changes to be made on this document and will be making those changes shortly.

Thanks
Sri

**Comment by chasman157** [comment]
Thank You!

Chuck VanDeweel
1+(469) 713-7393

**Comment by msbemba** [comment]
@chasman157 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7557

Once the author approves the changes will be live.

Thanks
Sri

**Comment by chasman157** [comment]
Thank you so much!!

Chuck VanDeweel
1+(469) 713-7393

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chasman157 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
