### ISSUE TITLE
Page isn't in the TOC

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/microsoft-365-docs#7299]
This orphan page isn't attached to any table of contents.
It would help if it could be grouped with other related content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f283e6d-8054-3abf-becf-65037e9c70b7
* Version Independent ID: e8dfaaad-a731-bd2e-7c7b-c5d0b80462de
* Content: [Microsoft 365 encryption chains - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-certificate-chains?view=o365-worldwide#additional-certificate-paths)
* Content Source: [microsoft-365/compliance/encryption-office-365-certificate-chains.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-certificate-chains.md)
* Service: **o365-seccomp**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Was added to the TOC
