### ISSUE TITLE
Microsoft Myanmar

### ISSUE THREAD

**Issue by breakerzoe1832** [MicrosoftDocs/microsoft-365-docs#7300]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f283e6d-8054-3abf-becf-65037e9c70b7
* Version Independent ID: e8dfaaad-a731-bd2e-7c7b-c5d0b80462de
* Content: [Microsoft 365 encryption chains - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/encryption-office-365-certificate-chains?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-office-365-certificate-chains.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-certificate-chains.md)
* Service: **o365-seccomp**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@breakerzoe1832 What is your feedback. Thanks

**Comment by yogkumgit** [comment]
@breakerzoe1832 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
