### ISSUE TITLE
Expected Behavior After Policy Days

### ISSUE THREAD

**Issue by usvjosh** [MicrosoftDocs/microsoft-365-docs#7301]
Hello,

What is the expected behavior of the exchange in place holds action item 2 after the retention policy expires? Are you able to HARD delete a item (mailbox or email) after that timeframe? 

The section i'm referring to is this:
"Understanding the format of the InPlaceHolds value for retention policies"

Action #2:
2 - Indicates that the retention policy is configured to hold items. The policy doesn't delete items after the retention period expires.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4119f918-a0b2-4bdc-535e-11d2c476f675
* Version Independent ID: 1520175d-398b-4df1-86db-8ba6b26260df
* Content: [How to identify the type of hold placed on an Exchange Online mailbox - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/identify-a-hold-on-an-exchange-online-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@usvjosh Here's info about retention policy behavior for Exchange: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-exchange. It describes what happens to items (based on whether they were deleted or not) after the retention period expires.

Also, ability to hard-delete items would assume that no other type of hold (or no other retention policy) is applied to the user mailbox. And, single-item recovery feature will also impact when a hard-deleted items is permanently removed. See https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-single-item-recovery

Hope this helps.
