### ISSUE TITLE
generateAlert parameter is missing from the list

### ISSUE THREAD

**Issue by jmmowrer** [MicrosoftDocs/microsoft-365-docs#7305]
generateAlert enum is missing in the list.  It's mentioned under the action parameter as being required for audit but it's not in the list.  

Probably can just be copied from the "all methods and properties" link:
generateAlert	Enum	True if alert generation is required, False if this indicator should not generate an alert.

text from here:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ti-indicator?view=o365-worldwide#properties 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea229ca-05ce-38c5-003e-4d811b0bed25
* Version Independent ID: 765b3d95-745c-357b-b19e-87ee0b0a1661
* Content: [Submit or Update Indicator API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/post-ti-indicator?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/post-ti-indicator.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/post-ti-indicator.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jmmowrer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7329

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jmmowrer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
