### ISSUE TITLE
Tamper Protection included in P1?

### ISSUE THREAD

**Issue by rmrosen** [MicrosoftDocs/microsoft-365-docs#7307]
Top of page only has link to P2, which implies it is not included with P1.  Tamper Protection appears to be part of P1 under Next Gen Protection.

https://microsoft.sharepoint.com/teams/windef/atp/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2Fwindef%2Fatp%2FShared%20Documents%2FLicensing%2FMicrosoft%20Defender%20for%20Endpoint%20P1%20resources%2FMicrosoft%20Defender%20for%20Endpoint%20P1%20FAQ.pdf&parent=%2Fteams%2Fwindef%2Fatp%2FShared%20Documents%2FLicensing%2FMicrosoft%20Defender%20for%20Endpoint%20P1%20resources&p=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31e7b39-b7c3-188a-0b2a-02ff10a5be6d
* Version Independent ID: 44940a13-0a2d-e281-560b-cb4d8a5d1ccf
* Content: [Protect security settings with tamper protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@rmrosen Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7328

Once the author approves, the  changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rmrosen Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
