### ISSUE TITLE
Incorrect information on page.

### ISSUE THREAD

**Issue by FreedomChris** [MicrosoftDocs/microsoft-365-docs#7310]
Hello,

This page states "eDiscovery Administrator: Can perform all case management tasks that an eDiscovery Manager can do."

This is not correct.  an eDiscovery Administrator cannot manage cases without the eDiscovery Manager entitlement.  Both are required for the eDiscovery Administrator to manage cases, data sources, collections, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb7387a-258a-6c16-1744-25b205f6de14
* Version Independent ID: 46dc7d79-21a6-f6c0-02c6-86ff9bec8e62
* Content: [Set up Advanced eDiscovery in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-advanced-ediscovery?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/get-started-with-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-with-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@FreedomChris Thanks for feedback. Technically, the statement is correct. An eDiscovery Admin is assigned all the management roles that are assigned to the eDiscovery Manager, **at least when you add a user as an eDiscovery Manager using the Permissions page in the M365 compliance center UI.** When you use the UI, two underlying Powershell cmdlets are invoked: Add-RoleGroupMember (to add the user to the eDiscoveryManager role group) and Add-eDiscoveryCaseAdmin (to assign org-wide scope). After you add the user as an eDiscovery Admin in the UI, you'll see that user is added to the eDiscoveryManager role group by running Get-RoleGroupMember eDiscoveryManager command. Likewise, if you use the UI to remove an eDiscovery Admin, they will be removed from the role group and they will be removed as eDiscovery admin. 

But an issue arises when you only use PowerShell to assign permissions or use a combination of PowerShell and the UI. If you use PowerShell to perform the equivalent of adding an eDiscovery Admin in the UI, then you have to run two commands: Add-RoleGroupMember and Add-eDiscoveryCaseAdmin. The first gives, as you say, the eDiscovery Manager entitelment. The second provides the org-wide scope. If you only run Add-eDiscoveryCaseAdmin, then the situation that you originally describe will result. But using the UI will mitigate this issue.

Hope this helps. Any suggestions for clarifying this in the AeD set up topic?

**Comment by markjjo** [comment]
@FreedomChris Sorry one correction from above: 

at least when you add a user as an **eDiscovery Admin** using the Permissions page in the M365 compliance center UI.

**Comment by yogkumgit** [comment]
@FreedomChris Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
