### ISSUE TITLE
More on Activities and Record Types

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#7311]
I am creating an audit log retention policy. During the creation three questions came up:
1) what is AeD?
2) what activities are included for each record type?
3) will this increase the searchable date range for AzureAD user sign-in logs?

I found [this](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#microsoft-365-services-that-support-auditing) referenced article. Unfortunately, that page lists more record types than are available when creating an audit log retention policy. For example, the feature "Azure Active Directory" uses these record types: AzureActiveDirectory, AzureActiveDirectoryAccountLogon, AzureActiveDirectoryStsLogon

Of the 3 listed, I only see AzureActiveDirectory as a record type when creating a retention policy.

For question 1, AeD appears to be related to eDiscovery, Ah! Advanced eDiscovery is my guess. These names need to be more friendly, or we need a place to find what the names mean!

For question 2, the only way I have found to determine what activities are included is to select one record type while creating the policy, then look at the list of activities. I tried to search the unified log and scroll through activities, but the groupings in the search page does not use the same language. 

"Azure AD Group administration activities," is that an AzureActiveDirectory Record Type? Maybe.
![image](https://user-images.githubusercontent.com/15677312/148130753-c0abbe84-1112-4df2-8833-e61d1ecaa145.png)

For question 3, I think the answer is no. But there is also Workplace Analytics (isn't that called Viva Insights now?) which has log-in/log-out activities... 

Maybe we should search the "UnifiedAuditLog user log-in activities" instead of the AzureAD User Sign-in logs.
Maybe they are the same thing and the [AzureAD User Sign-in search](https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade/SignIns) will benefit from this retention policy too! Fingers crossed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@jonwbstr Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
