### ISSUE TITLE
How do I build reputation when you send my email to SPAM from Day 1?

### ISSUE THREAD

**Issue by sambellbraze** [MicrosoftDocs/microsoft-365-docs#7313]
You explain on this support page that "IP addresses not previously used to send email typically don't have any reputation built up in our systems. As a result, emails from new IPs are more likely to experience delivery issues. Once the IP has built a reputation for not sending spam, EOP will typically allow for a better email delivery experience."

Yet, if I have a brand new IP address, how can I build a trusted reputation with Microsoft if you are delivering my emails to the SPAM folder straight away due to me not having a reputation? How am I supposed to engage with my customers via email as a new IP address when you send the email to SPAM. My customers won't be looking in SPAM for the email, and the email channel is the only way I can reach them. It's not as if I will telephone call each of my customers I send an email to and ask them to check their SPAM folder.

How do you recommend we build a positive sender reputation when you send my emails to SPAM frame Day 1?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95417878-bc32-8b18-9900-6ad4f10da2a9
* Version Independent ID: 30cd3f4e-9c51-f2fa-b6c0-036756f6b99e
* Content: [Troubleshooting mail sent to Microsoft 365 - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/troubleshooting-mail-sent-to-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/troubleshooting-mail-sent-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/troubleshooting-mail-sent-to-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@sambellbraze, you have SPF, DKIM, and DMARC DNS records configured for your domain? That might help.

**Comment by sambellbraze** [comment]
Hey @chrisda,

Thanks for the reply - do you mean that if I setup SPF, DKIM and DMARC DNS records this helps MS know I am a more trustworthy sender from Day 0 for my IP warming?

I work with a lot of customers who IP warm through a brand new IP, and we see that the vast majority of emails go to the SPAM folder straight away for MS. We set them up with a SPF and DKIM record. And then it's up to the customer as to if they setup a DMARC record. So we do pre-configure 2 of the 3 items you've mentioned. Keen to understand your recommendations a bit further please. 

Thanks,
Andrew

**Comment by chrisda** [comment]
@sambellbraze, I'm sorry, but I have nothing else to suggest. At this point, it's probably best if you open a support case to ask the question. If you learn anything that can go into the existing article to help others, please report back here.

**Comment by sambellbraze** [comment]
Hey @chrisda - no worries. Last question - does signing up prior to IP warming through MS SNDS and JMRP (junk mail reporting program) help with reputation prior to commencing IP warm?

Thanks,
Andrew

**Comment by chrisda** [comment]
@sambellbraze, I'm sorry, I don't know.

**Comment by sambellbraze** [comment]
No worries :) Will log a support ticket.
