### ISSUE TITLE
"Security Reader" is not sufficient to see MDE device inventory

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/microsoft-365-docs#7314]
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prepare-deployment

> Basic permissions management: Set permissions to either full access or read-only. In the case of basic permissions management users with Globa Administrator or Security Administrator role in Azure Active Directory have full access while the **Security reader** role has read-only access.

Nor [Security Reader](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#security-reader) or [Security Operator](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#security-operator) is sufficient for viewing device inventory in Microsoft Defender for Endpoint.

From what I've been able to see, [Security Administrator](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#security-administrator) is the least privilege built in role to even be able to view machines/ device inventory.

Please add sufficient permissions to the "Security Reader" and "Security Operator" role (preferably), or update this documentation to mention that, there are in fact some crucial things inside Microsoft Defender you can't see with mentioned roles.

For reference, this is the page I'm talking about:

* Old portal: https://securitycenter.windows.com/machines
* New portal: https://security.microsoft.com/machines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c20ab25-de01-7794-8025-43c3f859e272
* Version Independent ID: bd4264bb-cca6-7fc4-45bc-c94e519c06cc
* Content: [Prepare Microsoft Defender for Endpoint deployment](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prepare-deployment?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/prepare-deployment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prepare-deployment.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @o-l-a-v Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
