### ISSUE TITLE
The video is not updated with  Sharepoint Admin webpage

### ISSUE THREAD

**Issue by carias78** [MicrosoftDocs/microsoft-365-docs#7317]
![Invite External Users](https://user-images.githubusercontent.com/42930419/148197372-8e022367-763c-4a10-b04e-79ef3d25e05c.png)

**Comment by yogkumgit** [comment]
@carias78 Which document you are referring to. Please indicate. Thanks

**Comment by yogkumgit** [comment]
@carias78 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
