### ISSUE TITLE
The RSS feed URL in the 'Tip' section is root-relative instead of absolute

### ISSUE THREAD

**Issue by AndrewBryson** [MicrosoftDocs/microsoft-365-docs#7318]
The RSS feed URL in the 'Tip' section is root-relative instead of absolute, it's not clear what domain should be used.  Please clarify what URL should be used by providing an absolute URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f744fca0-6584-f0e9-2bbb-7894d151498e
* Version Independent ID: eb540bda-8fe0-dce3-daa8-4f2ed53f584f
* Content: [Microsoft Defender for Endpoint preview features](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/preview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/preview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@AndrewBryson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7326

The RSS feed will be `https://docs.microsoft.com/api/search/rss?search=%22In+the+navigation+pane%2C+select+Settings+%3E+Advanced+features+%3E+Preview+features.%22&locale=en-us&facet=`

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AndrewBryson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
