### ISSUE TITLE
Device group is not shown

### ISSUE THREAD

**Issue by amanmcse** [MicrosoftDocs/microsoft-365-docs#7319]
![image](https://user-images.githubusercontent.com/33834131/148235677-1a7fe1b6-1a1c-4396-af18-4290d4d913fd.png)

I have the device added to a device group but it doesn't show the device group name under either the Alerts queue or the Alerts tab under the file page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628f6627-8a79-560a-fee4-cb5a68e5a070
* Version Independent ID: f09cb963-7608-0d9c-e1fa-6a02d2af3a26
* Content: [Investigate Microsoft Defender for Endpoint files](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/investigate-files?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/investigate-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/investigate-files.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@amanmcse Please indicate which document you are referring to. Thanks

**Comment by amanmcse** [comment]
@yogkumgit Added the Doc details to the footer in the question.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@amanmcse Thank you for your feedback. I tested this and could not locate the device group as well. Later, I found that the document states  This list covers much of the same information as the Alerts queue, **except** for the device group, if any, the affected device belongs to.

Hope this helps!


Thanks
Sri

**Comment by amanmcse** [comment]
@msbemba It states other information on **Alerts queue** is same as **Alerts tab under the file page** except the device group. This indicates that the Alerts queue has device groups as an extra piece of information.

**Comment by msbemba** [comment]
@amanmcse Got it! I don't see it either. I'll work with the author internally and update the document if need be.

Thanks
Sri

**Comment by mjcaparas** [comment]
From the Alerts queue, try selecting the Choose columns, scroll down to Device group.
