### ISSUE TITLE
Exchange Online Archiving for Exchange Online license also acceptable?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/microsoft-365-docs#732]
The article says that a Exchange Online (Plan 2) license is required, however Litigation hold and other archiving features are offered with the "Exchange Online Archiving for Exchange Online" add-on. I'd like to confirm that this inactive mailbox feature/concept isn't an exception for some reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Overview of inactive mailboxes in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@Mike-Crowley - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@Mike-Crowley Correct, inactive mailboxes are no exception. For hold/archiving features, EXO Plan 2 and EXO Plan 1 + EOA are equivalent. For example: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-inactive-mailboxes

I will update overview topic.

**Comment by Mike-Crowley** [comment]
Thank you @markjjo ! As some customers require retention many years into the future, being crystal clear on their entitlements is critical. I plan on printing this page once you're done with the update, so the customer can keep it in their retention policy documents.
