### ISSUE TITLE
Word "antivirus" is missing?

### ISSUE THREAD

**Issue by AndrewBryson** [MicrosoftDocs/microsoft-365-docs#7320]
I think the word "antivirus" is missing from this sentence:

Actual:
"Microsoft Defender for Endpoint on Linux offers preventative (AV)"

Expected:
"Microsoft Defender for Endpoint on Linux offers preventative **antivirus** (AV)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e914c02a-e905-fc32-439c-feb1fafa09b8
* Version Independent ID: 1a6a15e9-717a-33c1-b90e-96925c680228
* Content: [Microsoft Defender for Endpoint for non-Windows platforms](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/non-windows?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/non-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/non-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@AndrewBryson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7360

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AndrewBryson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
