### ISSUE TITLE
Why does Dynamics 365 for Financials and Dynamics 365 for Operations include in Available self-service programs?

### ISSUE THREAD

**Issue by Tad1011** [MicrosoftDocs/microsoft-365-docs#7322]
Dynamics 365 for Financials and Dynamics 365 for Operations hasn't self-service sign-up feature. But, this docs mentions Dynamics 365 for Financials and Dynamics 365 for Operations, and it looks like self-service sign-up can be used with those services. Please let me know reason why this docs mentions Dynamics 365 for Financials and Dynamics 365 for Operations.
https://docs.microsoft.com/en-us/microsoft-365/admin/misc/self-service-sign-up?view=o365-worldwide#available-self-service-programs
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10769542-cd9f-30a1-be29-2a37627149fb
* Version Independent ID: a99e4d71-62da-563d-a1b2-97d8d0bc358c
* Content: [Using self-service sign-up in your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/self-service-sign-up?view=o365-worldwide#available-self-service-programs)
* Content Source: [microsoft-365/admin/misc/self-service-sign-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/self-service-sign-up.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Tad1011 Thank you for your feedback. Both options are available under self-service programs. We recommend you contact Microsoft support via the need help section on the admin center, so an engineer can work with you to investigate why these options don't show up.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Tad1011 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
