### ISSUE TITLE
Does the documentation needed an update ?

### ISSUE THREAD

**Issue by aravindmunna** [MicrosoftDocs/microsoft-365-docs#7323]
Heading says  "Use network upload to import your organization's PST files to Microsoft 365"

https://docs.microsoft.com/en-us/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-worldwide

However, the content still displays Office 365. Just checking to see if the documents need to be updated or if it is acceptable to use Office 365 instead of Microsoft 365.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f9f87e-6f96-9663-114a-f6bd74a7a7f4
* Version Independent ID: b3ba56e3-0c78-f286-1c01-12375bf00f62
* Content: [Overview of importing your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/importing-pst-files-to-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/importing-pst-files-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/importing-pst-files-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by RAJU2529** [comment]
@yogkumgit Created PR #7325 for this issue #7323

**Comment by markjjo** [comment]
@aravindmunna Thanks for the feedback. We will update the documentation.

**Comment by aravindmunna** [comment]
Thank you
