### ISSUE TITLE
Retention Policy APIs

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/microsoft-365-docs#733]
Is there any other way to configure retention policies other than PowerShell? For e.g. C# using REST APIs or using MS Flow. I am mainly looking for adding location (e.g. SPO site or O365 group) automatically to an existing retention policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d08974-4cd1-4fab-7a59-17e5f8517566
* Version Independent ID: 93e7f78f-6a94-1b90-1adf-70d2e266ce51
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies)
* Content Source: [microsoft-365/compliance/retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by mypil** [comment]
@prashant1380  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by LauraWi** [comment]
Hi @prashant1380 PowerShell is the method we currently document. There are some 3rd party content results that turn up for internet searches for both Flow and REST.
