### ISSUE TITLE
Turn on Safe List recommendations

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/microsoft-365-docs#7331]
Hi folks,

Can we please have some guidance or reference to best practice on the default Connection filter policy setting "Turn on safe list".

It has been made clear that this is a list managed by Microsoft, but what is not clear if it is recommended to have it enabled or disabled.

I have checked the information at the Anti-spam protection docs page, and it says the same thing - just that it's managed by Microsoft.  There is little more detail on it. 

I could assume that this is a finely tuned list of vetted trusted providers, but that is a big assumption.  There is also no indication of how these "safe lists" are treated, do they bypass all hygiene engines, spam rules, phish rules, spoof rules?

Anti-spam protection docs page:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-protection?view=o365-worldwide

Microsoft recommendations for MDO/EOP also doesn't mention it:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide

Life was so much easier when everything was in the Exchange admin center :) 

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3094559e-4d03-8f6d-a620-a3f61ec33184
* Version Independent ID: d352d9b3-3d96-402b-c20e-df677b3e9d60
* Content: [Configure the default connection filter policy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-connection-filter-policy?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-the-connection-filter-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-connection-filter-policy.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@anthonynz, the main reason that connection filtering settings are not described in [Recommended settings for EOP and Microsoft Defender for Office 365 security](https://docs.microsoft.com/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365) is the connection filtering policy is not one of the policies that's included in the Standard or Strict [preset security policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies).

In the connection filter policy, the only settings are:

- IP Allow List
- IP Block List
- Turn on/off the Safe List

Clearly, there are no default or universal entries that we can recommend or configure for the IP Allow List or the IP Block List. Using the IP Allow List is the second to last (3rd out of 4) recommended method as a [safe senders list](https://docs.microsoft.com/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365), while the IP Block List is dead last (4th out of 4) recommended method as a [block senders list](https://docs.microsoft.com/microsoft-365/security/office-365-security/create-block-sender-lists-in-office-365).

That leaves the Safe List. It's off by default, which you can easily interpret as our default recommendation. It's certainly not harmful to turn it on, but you should monitor the effects. According to the documentation:

> The safe list is a dynamic allow list in the Microsoft datacenter that requires no customer configuration. Microsoft identifies these trusted email sources from subscriptions to various third-party lists. You enable or disable the use of the safe list; you can't configure the source email servers on the safe list. Spam filtering is skipped on incoming messages from the email servers on the safe list.

The messages would still be subjected to the rest of the filtering stack, including and more importantly for phishing: spoof, domain/user impersonation (E5/MDO), Safe Links (E5/MDO), and Safe Attachments (E5/MDO).

So, if you're having a problem with spam false positives, turning on the Safe List might offer some relief.

**Comment by anthonynz** [comment]
Thanks Chris,  I appreciate this very helpful response.

I  miss the days of white papers that would have this level of explanations.


________________________________

**Comment by yogkumgit** [comment]
@anthonynz If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
