### ISSUE TITLE
MDE for Server - more details on how to license required

### ISSUE THREAD

**Issue by Saraquin** [MicrosoftDocs/microsoft-365-docs#7332]
Hi,

The second note bubble on the page pertaining to Licensing servers and the minimum requirements does not clearly define what that provides. i.e. does it allow the purchase of a server license or are they then included as part of the required licenses. if the former, details on the process to purchase would be useful.
![image](https://user-images.githubusercontent.com/1393504/148491467-41bcf7ac-58ab-45ee-8d8b-76d7c993e073.png)

I followed the link to the Product Terms site and searched for MDE for server details and was only provided information on Defender for Identity.

Having more clarity on this point would enable more MDE for server adoption by removing the hesitation around licensing.

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Saraquin Thank you for your feedback. The Note has been removed to avoid ambiguity and the added link to another document which talks about the requirements

For information licensing requirements for Microsoft Defender for Endpoint, see Microsoft Defender for Endpoint licensing information (https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-endpoint)

Hope this helps!

Thanks
Sri

**Comment by Saraquin** [comment]
Thanks, that makes it clearer from the eligibility aspect, the licensing is still confusing but that is a separate issue :)

Cheers
