### ISSUE TITLE
Zero touch (preview) does not deploy the MDE app

### ISSUE THREAD

**Issue by WolfgangSauer** [MicrosoftDocs/microsoft-365-docs#7333]
[Enter feedback here]
Docs say "Defender for Endpoint is automatically installed without the need for the user to open the app" which leads to the interpretation, that an explicit app deployment profile is not necessary. But an MDE app deployment profile is necessary. The following  activation after installation is silent as documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [App-based deployment for Microsoft Defender for Endpoint on iOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide#add-ios-store-app)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by cashxx** [comment]
Agree with WolfgangSauer.  Whole page is confusing to me.

**Comment by msbemba** [comment]
@WolfgangSauer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7391

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @WolfgangSauer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
