### ISSUE TITLE
"sc query" only returns running services

### ISSUE THREAD

**Issue by Gregor-Weertman** [MicrosoftDocs/microsoft-365-docs#7334]
"When Microsoft Defender Antivirus is running, the STATE value displays RUNNING."

the command "sc query" only returns running services
You need "sc query state= all" to view the non running too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff9a2869-614c-e077-8d71-351448810897
* Version Independent ID: 09369dc3-f8d1-9b19-0043-47fa733a3b81
* Content: [Microsoft Defender Antivirus on Windows Server](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@Gregor-Weertman Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7390

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Gregor-Weertman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
