### ISSUE TITLE
Note needs to be more specific

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/microsoft-365-docs#7335]
[Enter feedback here]
The article contains this note:
" Note

You must add at least one content location to the hold. Otherwise, the eDiscovery hold statistics will show that no items are on hold."

This needs to be reworded to match the behaviour of the Hold wizard on the web.  
The wizard will allow you to select SPO sites.  Many customer who have worked with retention will mistakenly believe this is the same as selecting all sites in retention and other policies.  They won't read the screen and see that selecting the bubble beside SPO does NOT put all sites on hold.  It actually puts None on hold.  If they cruise through the wizard and never check their results (more common than you think) they will not realize their hold failed to capture anything.

I was thinking of wording like:
Note
You cannot put All mailboxes or Sites on hold.  You must select specific mailboxes or sites for the hold.  The only object class where you can put All items on hold is Public Folders.  If you select the slider beside Exchange Mailboxes or SharePoint Sites and do nothing more then the hold will not apply to any objects.

Feel free to massage my wording as needed.  The way the note currently reads it could be interpretted as a display problem with the statistics.  I will also suggest to the eDiscovery development team that they add some sort of warning to the steps in their web based wizard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7263ba97-4e79-7144-a9d4-5138fe228fa2
* Version Independent ID: 316e242e-7f37-592e-9c8f-e754b23a29ca
* Content: [Create eDiscovery holds in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-ediscovery-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-ediscovery-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@cablechewer Thanks for the feedback. I will update the documentation as you suggest. Adding @SeunginLyu  for visibility.

**Comment by SeunginLyu** [comment]
@cablechewer @markjjo thanks for the feedback, I'll also bring this to our UX team to add the warning.

**Comment by markjjo** [comment]
@cablechewer , @SeunginLyu Article has been updated; added note in this section: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide#how-to-create-an-ediscovery-hold

Thanks again for the help.
