### ISSUE TITLE
MAPS - Send Safe Samples or Send All Samples - Which is Correct?

### ISSUE THREAD

**Issue by lccctemp** [MicrosoftDocs/microsoft-365-docs#7338]
Under "Other recommended configuration settings > Update endpoint configuration protection > Policy location: \Windows Components\Microsoft Defender Antivirus\MAPS > Send file samples when further analysis is required", the suggestion states to enable it and set it to "send safe samples". 

However, lower on the page, under "Setup Defender AV policies > Configure Cloud Deliver Protection and send samples automatically > Policy location: \Windows Components\Microsoft Defender Antivirus\MAPS > Send file samples when further analysis is required", the suggestion states to enable it and set it to "send ALL samples". 

Which setting is correct? They're both referring to the same policy.  

Thank you again for the opportunity to provide feedback! I hope you can see why this would be confusing to a new user. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523651c3-a318-2369-6892-d13e04991596
* Version Independent ID: 624c5e05-f87d-1bd4-bc87-bd55dcac1d86
* Content: [Onboard Windows devices to Microsoft Defender for Endpoint via Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-gp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@lccctemp Thank you for your feedback. Both the options are safe

The "Send File samples when further analysis is required " should be set to 1 (Send safe samples) or 3(Send all samples). Setting to 0 and 2 will not lower the protection state of the device.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lccctemp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
