### ISSUE TITLE
Secure your Windows 10 Computer is out of date

### ISSUE THREAD

**Issue by josephgruber** [MicrosoftDocs/microsoft-365-docs#7339]
This page is out of date. Specifically the Secure your Windows 10 computer section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c4e2120-1795-40bd-9f36-238273c9d5c4
* Version Independent ID: 88e4584e-c545-b74d-44bd-5fc966637513
* Content: [Secure Windows 10 computers - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/secure-win-10-pcs?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/secure-win-10-pcs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/secure-win-10-pcs.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@josephgruber Thank you for your feedback. I'm not able to locate the Secure options as well.  I will work with the author and update the document accordingly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@SKjerland Please help. Sent you an email with a query. Thanks

**Comment by SKjerland** [comment]
@yogkumgit - This article is slated to move to a new doc library owned by someone else. I assume it will be reworked and/or updated in the process. @denisebmsft, do you want to field this one? Thanks!

**Comment by denisebmsft** [comment]
The current article is located here: [https://docs.microsoft.com/microsoft-365/business-premium/m365bp-secure-windows-devices](https://docs.microsoft.com/microsoft-365/business-premium/m365bp-secure-windows-devices)

Thanks again!
