### ISSUE TITLE
It doesn't return information about folders in the user's archive mailbox.

### ISSUE THREAD

**Issue by walvisam** [MicrosoftDocs/microsoft-365-docs#734]
I already tested for archive and worked ok, only need to add -archive in the line 37 
$folderStatistics = Get-MailboxFolderStatistics -Archive $emailAddress

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136c161f-13b8-fb62-01de-53b1219b5290
* Version Independent ID: f1843c14-29da-d831-c7ce-9e3f624a01ed
* Content: [Use Content Search in Office 365 for targeted collections](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections)
* Content Source: [microsoft-365/compliance/use-content-search-for-targeted-collections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-content-search-for-targeted-collections.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@walvisam Thanks for pointing this out. However, if we add the -Archive parameter to the script, then I think that only folder Ids for folders in the archive mailbox would be returned. Folders Ids for folders in the primary mailbox would not be returned. Also, does using the folderid for an folder in archive mailbox in a search query return any results?

This info about using the Archive parameter in the script could be added to a note. Please feel free to submit a pull request with this change.

**Comment by markjjo** [comment]
FYI - https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxfolderstatistics?view=exchange-ps

**Comment by Venkat-gists** [comment]
The code on this page does not return the folderids of Archive mailbox.
https://learn.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide

But this code works correctly
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-content-search-for-targeted-collections.md
