### ISSUE TITLE
Update Request - Requirements for managing tamper protection in Intune

### ISSUE THREAD

**Issue by fabiotelesMS** [MicrosoftDocs/microsoft-365-docs#7341]
Hello,

Checking the documentation on enabling Tamper Protection on Intune, on the FAQ it states clearly that we need to have MDE enrollment to configure it using Intune at:

_I have the Windows E3 enrollment. Can I use configuring tamper protection in Intune?
Currently, configuring tamper protection in Intune is only available for customers who have Microsoft Defender for Endpoint._

I thin it would be helpful to have that information **implicit** on the requirements for Intune under: **Requirements for managing tamper protection in Intune**

This would increase the clarity, even so when this page applied to Defender for Endpoint P2, but a quick search will point out to these requirements without being explicit.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31e7b39-b7c3-188a-0b2a-02ff10a5be6d
* Version Independent ID: 44940a13-0a2d-e281-560b-cb4d8a5d1ccf
* Content: [Protect security settings with tamper protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection?view=o365-worldwide#manage-tamper-protection-for-your-organization-using-intune)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@fabiotelesMS Thank you for your feedback. We have added a statement to the requirements section of the document which states Your devices must be onboarded to Microsoft Defender for Endpoint.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @fabiotelesMS Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
