### ISSUE TITLE
Is this documentation correct?

### ISSUE THREAD

**Issue by ok2play** [MicrosoftDocs/microsoft-365-docs#7342]
I am using Microsoft Endpoint Manager to try and configure a process exclusion and per this documentation:https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-process-opened-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide

I should be able to use a path wildcard and the example given: "c:\test\sample\*"

What I want is: "%ProgramFiles%\Cisco\AMP\*\sfc.exe"  but any time I add an "*" I get a RED Exclamation point that pops up and if hover over it, it tells me "Specify a valid process"

I tried many different variations but all with a wildcard fail.

Here is what I need to whitelist. Cisco AMP now  Cisco Secure Endpoint "sfc.exe' but the problem is every time Cisco has a version update the path changes. Ex:

"%ProgramFiles%\Cisco\AMP\7.3.13\sfc.exe"
"%ProgramFiles%\Cisco\AMP\7.3.15\sfc.exe"
"%ProgramFiles%\Cisco\AMP\7.4.1.20439\sfc.exe"
"%ProgramFiles%\Cisco\AMP\7.4.3.20630\sfc.exe"
"%ProgramFiles%\Cisco\AMP\7.4.5.20701\sfc.exe"
"%ProgramFiles%\Cisco\AMP\7.5.1.20813\sfc.exe"
"%ProgramFiles%\Cisco\AMP\7.5.0.20833\sfc.exe"

Also in "Exclude files and folders:" I had C:\Program Files\Cisco\AMP\*

But this morning got Malware detected - Program:Win32/Uwamson.A!ml  
On "C:\Program Files\Cisco\AMP\clamav\0.103.2.19\temp\clamtmp\000198f7.tmp"

Let's try: %ProgramFiles%\Cisco\AMP\clamav

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52d23d2-1b6b-b0ed-dddf-6e4596adcbac
* Version Independent ID: b69c1c07-1bbc-7a18-efaa-d0d34de70cd9
* Content: [Configure exclusions for files opened by specific processes](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-process-opened-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-process-opened-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-process-opened-file-exclusions-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this Issue. Thanks

**Comment by denisebmsft** [comment]
@ok2play thank you so much for opening this issue, and thank you @yogkumgit for your help.

I have been looking into this issue and I have a suggestion. It's important to note that process exclusions don't actually apply to the processes themselves. Instead, what happens is, process exclusions mean that files that are opened by the processes listed as exclusions are not scanned. If you want to exclude a process itself, try adding the process as a file exclusion. 

Now in the case where you have variables, such as with Cisco path changes, consider using a folder exclusion with a wildcard, like this: %ProgramFiles%\Cisco\AMP\*

Please give that a try, and let me know if you still have any questions. I don't think any updates are needed to the docs at this time, so I am going to close this issue.
