### ISSUE TITLE
Intune User interface config is not present

### ISSUE THREAD

**Issue by MatthewWhiteMoJ** [MicrosoftDocs/microsoft-365-docs#7343]
Reading the updated docs page I can see that you can allow/deny hardware classes however i cannot see an option to define the level of control that can be made by the OMA-URI settings. is this a limitation of Intune or the feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7a5c17-1358-990b-968d-432a3aab2e17
* Version Independent ID: 1b4d4eff-3e22-47d7-4054-6cc9ed0217d0
* Content: [Microsoft Defender for Endpoint Device Control Removable Storage Access Control, removable storage media](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control?view=o365-worldwide#deploying-and-managing-policy-by-using-intune-user-interface)
* Content Source: [microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
I have opened work item 5731624 to be assigned to a writer.

**Comment by denisebmsft** [comment]
Hello @yogkumgit! My work item has been assigned and is in the queue for April.

**Comment by jweston-1** [comment]
@MatthewWhiteMoJ  the PM would like to known if you are asking how to “Block specific removable storage class but allow specific media”? if that is the case, he suggests "you can use ‘IncludedIdList a group through PrimaryId and ExcludedIDList a group through DeviceId/HardwareId/etc.’ "
If this is not what you are inquiring about, please provide additional details, perhaps with a basic example.

**Comment by jweston-1** [comment]
@yogkumgit Is it possible to contact the customer for additional information (posted above)? The PM needs some clarification in order to proceed with a response or revisions to the documentation.

**Comment by yogkumgit** [comment]
@MatthewWhiteMoJ Please respond to our query. Thanks

**Comment by jweston-1** [comment]
Fixed in pr 16338 Adds clarification in two topics, with cross-linking references, per PM.
To block a specific removable storage class but allow specific media, you can use ‘IncludedIdList a group through PrimaryId and ExcludedIDList a group through DeviceId/HardwareId/etc.` For additional guidance, see Deploy Removable Storage Access Control by using Intune OMA-URI. Will publish this morning 09/16.

**Comment by jweston-1** [comment]
Update to article went live about 5 minutes ago.

**Comment by yogkumgit** [comment]
@MatthewWhiteMoJ Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
