### ISSUE TITLE
Security Alerts not generating security incidents on Microsoft 365 Defender

### ISSUE THREAD

**Issue by aquiros17** [MicrosoftDocs/microsoft-365-docs#7344]
Hi,

We have multiple customers with alert policies configured in their tenants. Some of this alerts (for example "Email reported by user as malware or phish") generates an incident on Microsoft 365 Defender but there are some alerts policies (for example "Elevation of Exchange admin privilege") that is generating an alert but not an associated incident on Microsoft 365 Defender.

This is a very big problem because we have Sentinel with Microsoft 365 Defender connector and Sentinel only receives the incidents when the alert policy generates an associated incident on Microsoft 365 Defender but when the alert policy doesn't generate an incident on Microsoft 365 Defender, this is not sending to sentinel and there isn't incident on Sentinel (I assume that sentinel is a SIEM and it receives all alerts from all diferents connected sources and it seems that is not working as expected).

Please, fix ASAP.

**Comment by denisebmsft** [comment]
Hello @aquiros17. It sounds like your feedback is more product related than documentation related. Is that correct?

**Comment by aquiros17** [comment]
@denisebmsft yes, my feedback is product related. Please, could you say me anything about our problem ASAP?

**Comment by yogkumgit** [comment]
@aquiros17 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised as here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
