### ISSUE TITLE
Mixing up JSON and CSV

### ISSUE THREAD

**Issue by lkchild** [MicrosoftDocs/microsoft-365-docs#7347]
Hi,

It's ambiguous calling a JSON file a CSV file.  You should explain why the incorrect naming, or just stick with calling JSON JSON, and CSV CSV unless this is converting a CSV to JSON (which might be a nice opton)

Thanks!
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96e6e3c8-bc3b-900b-ff9a-fd56b33afab7
* Version Independent ID: f6423be1-2491-f53f-2344-b3f630e441fe
* Content: [Set up a connector to import physical badging data - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/import-physical-badging-data?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/import-physical-badging-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-physical-badging-data.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@lkchild Thanks for the feedback. The use of CSV is step 5 in this article is a copy and paste error. I will fix this so we're just calling JSON JSON.
