### ISSUE TITLE
Custom Org-Wide Signatures?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/microsoft-365-docs#7349]
Is there any way to pull from User Fields to insert that person's actual email address, phone number, etc instead of the same one for everyone?  I don't see this mentioned on the page I was looking at or the ones linked to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a984a46-1f7b-6ef1-71f3-c5df6c142c01
* Version Independent ID: 4fab7da3-c9ae-0136-c693-ae99c1090f40
* Content: [Create organization-wide signatures and disclaimers - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/create-signatures-and-disclaimers?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/create-signatures-and-disclaimers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/create-signatures-and-disclaimers.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@kelemvor33 Thank you for your feedback. I tested and looks like this is currently a limitation. To gain these and other capabilities to manage email signatures, use a third-party tool. Please do an internet search for email signature software. A number of these providers are Microsoft Gold Partners and their software provides these capabilities.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kelemvor33 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
