### ISSUE TITLE
O365 ATP mailbox intelligence; CAT:GIMP missing!

### ISSUE THREAD

**Issue by partlycloudyGE** [MicrosoftDocs/microsoft-365-docs#735]
I like to pressure updating the header information in this article as well. We already had a support case open related to his as message have been identified as being impersonated, as we saw from the ‘GIMP’ tag (“Graph-based Impersonation”, aka. “Mailbox Intelligence-based Impersonation”) in the headers &gt;  CAT:GIMP. see ticket MS support ticket 17501852

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers#feedback)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@partlycloudyGE  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by MaratMussabekov** [comment]
Hello @partlycloudyGE,
Looks like it was already added by https://github.com/MicrosoftDocs/microsoft-365-docs/commit/eac3a37c8c80be362da895927ba3d2ffc9d0d5ee#diff-09722203569ce3a5e005661b5c6d258c

**Comment by mypil** [comment]
@partlycloudyGE - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/b40406a4bf9a1f8d719f28461be5c21c09653790. If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!
