### ISSUE TITLE
Time zone location is moved to new blade

### ISSUE THREAD

**Issue by rajivmeh** [MicrosoftDocs/microsoft-365-docs#7352]
[Enter feedback here]
Location to Change the time zone is outdated in this doc. 
 
New Location - Settings > Security Cetner > Time Zone

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23a7695c-722d-22af-662c-e8680a492899
* Version Independent ID: b607ed60-729a-0dac-4464-dbc116531b40
* Content: [Microsoft 365 Defender time zone settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/time-settings?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/time-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/time-settings.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@rajivmeh Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7405

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rajivmeh Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
