### ISSUE TITLE
How to link Azure subscription to Intune Trial payment?

### ISSUE THREAD

**Issue by stchien** [MicrosoftDocs/microsoft-365-docs#7353]
Hi team,
We have the Azure subscription in Azure portal from our team, which cannot link to Intune trial payment. Do you know how? 
We tried "Replace payment method", which cannot be found in the product tab of M365 portal. 
Any suggestion is appreciated!

Azure Subscription: WER China Engineering
Resource Groups:
Resource Group Owner
WER_Hailey Steven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14e33d-0d3e-45f4-fefe-dec3ae7d351f
* Version Independent ID: aeb53e2c-d35c-73fe-26f2-4f101bfeeea7
* Content: [Manage payment methods](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-payment-methods?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/manage-payment-methods.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/manage-payment-methods.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@stchien Thank you for your feedback. This is a support request and needs to be routed to the Support team. We recommend you contact Microsoft support via the need help section on the admin center to get this resolved.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @stchien Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
