### ISSUE TITLE
Clarify that "Defender for Endpoint Lite" is the same as "Plan 1"

### ISSUE THREAD

**Issue by robwesterby** [MicrosoftDocs/microsoft-365-docs#7354]
Under [Review the requirements](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration?view=o365-worldwide#review-the-requirements) the Licensing requirements row lists "Defender for Endpoint Plan 1".

However in the Azure AD Portal > Licenses > Microsoft 365 A3 > Service plan details, the product SKU appears as "Microsoft Defender for Endpoint Lite".

It would be really helpful if the docs made it clear that you should look for "Lite" and not "Plan 1", to confirm you're correctly licensed.

As a suggetion, within the Review the requirements table, after "Defender for Endpoint Plan 1" add "Users should be assigned the Microsoft Defender for Endpoint Lite service plan."

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f58c48-23a1-29e6-4358-7733b12668c8
* Version Independent ID: 27f7f229-ae73-3cd0-287f-8592aaa3928b
* Content: [Set up and configure Microsoft Defender for Endpoint Plan 1](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mde-p1-setup-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration.md)
* Product: **m365-security**
* Technology: **mdep1**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@robwesterby Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7374

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @robwesterby Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
