### ISSUE TITLE
UserVoice link

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/microsoft-365-docs#7356]
This doc still has a link to UserVoice in the first paragraph. I'm not sure if there is an alternative new service available yet or if the link should just be removed
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4f52aa5-3876-1854-0fcc-279d694cb45d
* Version Independent ID: bfa3001d-e71a-705c-3492-5add564d131d
* Content: [Customer Lockbox Requests - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-lockbox-requests?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-lockbox-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@thommck Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7373

Updated user voice link to Feedback portal (https://feedbackportal.microsoft.com)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @thommck Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
