### ISSUE TITLE
IdentityDirectoryEvents moved, renamed or removed?

### ISSUE THREAD

**Issue by MarcErland** [MicrosoftDocs/microsoft-365-docs#7357]
Hello! Has the table "IdentityDirectoryEvents" changed name or been moved/removed? I cannot find it anywhere in our tenant. The table "Apps & Identities" in our advanced hunting schema only contains "IdentityInfo" and nothing else. It is also not possible to run a query involving "IdentityDirectoryEvents".

Regards,
M

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c69ab513-5cbb-3502-1404-f33536adaab9
* Version Independent ID: 5fbccf2d-81e9-0cb0-917b-660878638d12
* Content: [IdentityDirectoryEvents table in the advanced hunting schema](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-identitydirectoryevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-identitydirectoryevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-identitydirectoryevents-table.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@schmurky Please help us in resolving this issue. Thanks

**Comment by schmurky** [comment]
This is a permissions issue. Kindly check if you have all required permissions to access these tables.

**Comment by yogkumgit** [comment]
@MarcErland Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
