### ISSUE TITLE
Can't see bill online

### ISSUE THREAD

**Issue by TVdVelHuve** [MicrosoftDocs/microsoft-365-docs#7359]
[Enter feedback here]
Whenever I get a bill, there is a link for more details (https://admin.microsoft.com/Adminportal/Home#/billoverview/invoice-list/G007740367).
When I click on it, I get the message "Something failed at our end. Try again later.

I get this for over a month now, 

Many thanks for looking into this.

Regards,
   Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b461bf0-1269-d4d5-cf95-a774d1046b91
* Version Independent ID: 0fe88eec-af92-196d-1ee6-c35de1751fc7
* Content: [Understand your bill or invoice](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/understand-your-invoice?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/understand-your-invoice.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/understand-your-invoice.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@TVdVelHuve Thank you for your feedback. The link should ideally take you to the invoice. In your case, since it is not happening, we recommend you to contact Microsoft support via the need help section on the admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @TVdVelHuve Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
