### ISSUE TITLE
MECM 2011 Support

### ISSUE THREAD

**Issue by Phildo76** [MicrosoftDocs/microsoft-365-docs#7361]
Page states 'During preview, full Microsoft Endpoint Configuration Manager automation and integration to perform an automated upgrade will be available in the 2111 release of MECM' However I can't see how the Modern Unified Solution is configurable any differently in MECM 2111 after upgrading too it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a152af-6336-d498-60e5-1550bf457196
* Version Independent ID: c18e61ad-b9be-9a31-67a8-461705f3fdbf
* Content: [Server migration scenarios for the new version of Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/server-migration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/server-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/server-migration.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Phildo76 Thank you for your feedback. You are right, the changes were not made in the 2111 release and are expected to be available in a later release.  We have edited the document to reflect that "full Microsoft Endpoint Configuration Manager automation and integration to perform an automated upgrade will be available in a later release of MECM".

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Phildo76 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
