### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#737]
This item "Delete the message (this is the default value).", and all associated comments, needs review, as the default option is now to send malware to the administrator quarantine&gt;

https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Enhanced-Reporting-Quarantining-and-Safe-Links-Capabilities-for/ba-p/74581

"Enhanced Quarantine Capabilities
This month will also see significant feature enhancements to quarantine capabilities, extending support for EOP and providing new support in ATP for emails classified as malware. We are also enhancing the existing quarantine experience by allowing administrators to review and delete emails from quarantine. The new features will be enabled in SCC Quarantine interface which could be accessed from this link.

Now, all emails classified as malware from both EOP and ATP will be quarantined. In the event of a mail getting misclassified as malware and placed in quarantine, admins will have the ability to easily release the email to an end-user, thus preventing any unnecessary disruption to end user productivity. Administrators can understand the details of a mail from Quarantine by double click of a specific message and clicking on the “Preview message”."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b89afa39-ea8f-bfa3-d600-0bb5fda0805f
* Version Independent ID: 8b0ccaa2-9d59-1677-4cf1-1a3cacfc9239
* Content: [Anti-malware protection](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/anti-malware-protection)
* Content Source: [microsoft-365/security/office-365-security/anti-malware-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-malware-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@aldoug  Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@aldoug - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/44cd1aa2334967c417fb72b6bb60c27f62dc7f23.


Thank you for your contribution to make the docs better! Much appreciated!
