### ISSUE TITLE
Misleading content (screenshots, icons, labels)

### ISSUE THREAD

**Issue by f-casas** [MicrosoftDocs/microsoft-365-docs#7377]
Content is this document is a misleading since the screenshots, icons and labels used are in many cases for the **Microsoft Defender Security Portal** instead for the new unified **Microsoft 365 Defender portal**.
But yet according to the title the document refers to the new unified portal.

Please review it and update accordingly.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d69d8122-de1d-0d24-7b02-6efb95e0a038
* Version Independent ID: 3db2b699-3aa0-4711-e063-a249e2a1fc3e
* Content: [Microsoft Defender for Endpoint portal overview](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/portal-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/portal-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/portal-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@f-casas Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7488

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @f-casas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
