### ISSUE TITLE
Inverted description for DeviceLogonEvents RemoteIP field

### ISSUE THREAD

**Issue by JamesMasonRC** [MicrosoftDocs/microsoft-365-docs#7378]
The documentation says the field contains `IP address that was being connected to`, but the actual data returned is the IP address the connection is coming `from`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4287f831-8d71-6b0f-1221-7d2c34f86a87
* Version Independent ID: 773e0455-189d-11d4-6f8b-af7874f03ff6
* Content: [DeviceLogonEvents table in the advanced hunting schema](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-devicelogonevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-devicelogonevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-devicelogonevents-table.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JamesMasonRC Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
