### ISSUE TITLE
Define StartCalendarInterval values more clearly

### ISSUE THREAD

**Issue by ms-smithch** [MicrosoftDocs/microsoft-365-docs#7379]
Apple documentation doesn't clarify the values for StartCalendarInterval or does so behind a paywall. Suggest updating docs to include the following

Minute <Integer>
Range 0-59

Hour <Integer>
Range 0-24

Day <Integer>
Range 1-31
Note: This represents the calendar date

Weekday <Integer>
Range 0-7
Note: 0 and 7 represent Sunday

Ref: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/ScheduledJobs.html
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1c59b1-e4aa-6a18-7c34-720d0eb83c5d
* Version Independent ID: f5a3fc3c-bec2-3d7a-1d61-e23a0c1f8d4f
* Content: [How to schedule scans with Microsoft Defender for Endpoint on macOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-schedule-scan?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-schedule-scan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-schedule-scan.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ms-smithch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
