### ISSUE TITLE
Files with Digital Signatures

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#738]
Is this supposed to work with PDF files that have been digitally signed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29df28b-0065-a059-f22d-3433c1dd65a0
* Version Independent ID: 83b44475-2a39-5747-fc3c-2a92d0d958f2
* Content: [Set up Information Rights Management (IRM) in SharePoint admin center](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-irm-in-sp-admin-center)
* Content Source: [microsoft-365/compliance/set-up-irm-in-sp-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-irm-in-sp-admin-center.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by KCCross** [comment]
Reassigning to Samson.

**Comment by SanjoyanM** [comment]
@DeanGross can you please explain the question in details?

**Comment by DeanGross** [comment]
The doc states, "SharePoint Online supports encryption of the following file types:

PDF", when we try to upload a PDF that has a digital signature,we get an error. I'd like the documentation to clearly state if digitally signed PDF files are supported or not.

**Comment by MaratMussabekov** [comment]
Hello @DeanGross ,
could you please clarify, which error do you see when you upload this file?
how did you sign the file?
**The doc states, "SharePoint Online supports encryption of the following file types: PDF"** - it means encryption using Azure IRM
Thank you

**Comment by DeanGross** [comment]
my customer is getting this error. I'm not sure how it was signed.

![encryptedfileerror](https://user-images.githubusercontent.com/4058555/69537030-3556c980-0f4d-11ea-9dd7-e0cecba8c534.png)

**Comment by MaratMussabekov** [comment]
Hello @DeanGross ,
it is normal behavior, documents protected by third-party encryption (not by azure IRM) cannot be uploaded to the IRM-protected library
Thank you

**Comment by DeanGross** [comment]
Thanks for the confirmation, please add this information to the documentation to explicitly state this limitation.

**Comment by KCCross** [comment]
Thank you. This is still under investigation.

**Comment by mypil** [comment]
@KCCross - Do you have any updates on this?

Thank you.

**Comment by SanjoyanM** [comment]
What is the ask here?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by mypil** [comment]
@DeanGross - Thank you for submitting feedback.

A note was added to resolve your issue based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/8507d71371f879081087359ed391f3d6c62ca1d7. 


Thank you for your contribution to make the docs better! Much appreciated!
