### ISSUE TITLE
Both links are the same and don't think they are supposed to be.

### ISSUE THREAD

**Issue by cashxx** [MicrosoftDocs/microsoft-365-docs#7382]
Right under the heading "Complete deployment for supervised devices" in the first step is to download a file and this is the same link as later in the next section.  Are you supposed to continue to the next section, little confusing as it says Next, and acts as if you should continue on.  But seems to be the same steps further down the page.  https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide#complete-deployment-for-supervised-devices

Under this heading "Configure Supervised Mode via Intune" in step 7 is the same file that gets downloaded at the link above.  Doesn't seem right to me? https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide#configure-supervised-mode-via-intune

This article page is a little confusing.  It needs split up a little better between what you should do if device is supervised vs unsupervised with exact steps in order.  This page is all over the place it seems.  The new preview part of zero touch makes it sound like you just do that part and you're done, app gets deployed, etc. https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide#zero-touch-onboarding-of-microsoft-defender-for-endpoint-preview

Thanks!

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [App-based deployment for Microsoft Defender for Endpoint on iOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@cashxx Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7404

Once it is approved the changes will be live.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cashxx Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
