### ISSUE TITLE
"View, manage, and install add-ins in Office programs"

### ISSUE THREAD

**Issue by BrewskiBill** [MicrosoftDocs/microsoft-365-docs#7383]
How about you guys in Redmond (or whereever) actually TEST your help recommendations before you post them? I have a single user, standalone PC to which -I- am the ONLY user/adminstrator, yet Outlook is gleefully telling me that add-ins can only be disconnected by the administrator, and won't remove them. Where's the help instruction page to correspond, why isn't it directly linked to that bloody dialog box, and what in the h-e-double-hockeys ever happened to KISS (... look it up ...)? Just because you think The Cloud (which is just a mass of servers, by the way) is the wave of the future doesn't give you latitude to do whatever you want and not DOCUMENT all aspects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61e46dd-c1ff-dfec-5e0e-9f2e7251a5c1
* Version Independent ID: 49f69fa9-33e8-373f-a7f9-26b828510fda
* Content: [Manage add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-addins-in-the-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-addins-in-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@BrewskiBill Thank you for your feedback. Outlook States that you should be contacting your administrator to make changes in the O365 admin portal. The Steps to be followed on your admin center are here -https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide#delete-an-add-in

Hope this helps!

Thanks
Sri

**Comment by BrewskiBill** [comment]
Still not getting it: I AM THE ADMINISTRATOR FOR THIS SINGLE STANDALONE PC! And, oh, by the way, I have been to the Admin Center, and the add-in(s) in question DO NOT APPEAR. 

![image](https://user-images.githubusercontent.com/42098822/149535223-ded57ecf-3392-4401-8012-4063475e3b43.png)

![image](https://user-images.githubusercontent.com/42098822/149535567-33a69fe9-045a-4083-b2f6-6f701a13838d.png)

So thanks for playing, but ... Next?
