### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by AJ-Gov** [MicrosoftDocs/microsoft-365-docs#7385]
[At the top of your document approx 4 lines down, you state "Microsoft Defender for Endpoint Device Control Removable **Storage Access Control** enables you to do the following task:"....
But the title of the document is not **Storage Access Control** it shows Device Installation, so the correct title as well as in the description should match to Microsoft Defender for Endpoint Device Control Device Installation ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5df26b-9563-4810-f5b8-6997c9baa27c
* Version Independent ID: 006f5550-36b6-1de7-d3a5-63b85241df03
* Content: [Microsoft Defender for Endpoint Device Control Device Installation](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-device-control-device-installation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Lovina-Saldanha
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@AJ-Gov Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7386

Thanks
Sri

**Comment by AJ-Gov** [comment]
OFFICIAL

Hi,

I don't see the change, see yellow highlight below, still showing Removable Storage Access Control:

***@***.***


Cheers

Amjad Naseer (Contractor)
Digital Workplace Architect | Digital, Data & Technology Services | Department for Environment, Food and Rural Affairs

**Comment by msbemba** [comment]
@AJ-Gov The author will review the PR and Approve/Reject. once that is complete, you will see the document updated.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AJ-Gov Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by AJ-Gov** [comment]
OFFICIAL

Thank you for updating and have a great week

Cheers
Amjad
