### ISSUE TITLE
Sync users restrictions

### ISSUE THREAD

**Issue by v-videba** [MicrosoftDocs/microsoft-365-docs#7389]
[Enter feedback here]

When trying to add a alias or other details on synced users, its not possible and this message is shown

This user is synchronized with your local ‎Active Directory‎. Some details can be edited only through your local ‎Active Directory‎.

Would be a good idea to put this information also on this page to let know this restriction

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94754a91-ac3b-9b1c-ded9-3fdab2dd229c
* Version Independent ID: 517f9726-1861-8b1c-fe9d-6c50047e16d3
* Content: [Add another email alias for a user - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/add-another-email-alias-for-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/add-another-email-alias-for-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/add-another-email-alias-for-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by v-videba** [comment]
![imagen](https://user-images.githubusercontent.com/43179021/149361778-bcb7a70d-4d69-49b9-b855-60570228f905.png)

**Comment by msbemba** [comment]
@v-videba Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7440

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @v-videba Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
