### ISSUE TITLE
Section URL category lookup incorrect with recent changes to the M365 security portal

### ISSUE THREAD

**Issue by philtapp** [MicrosoftDocs/microsoft-365-docs#7393]
With a recent change to the M365 Security Portal with searching moving from a blade under Endpoint to the title bar you can no longer pick what you want to search for (such as URL) and the results don't include a URL section. How do you accomplish this now? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbaaa90e-6975-ee29-335a-545cb6a55986
* Version Independent ID: 75c93c17-4952-a13f-ed60-d2baefd0337e
* Content: [Web content filtering](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-content-filtering?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-content-filtering.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@philtapp Thank you for your feedback. I tested in multiple tenants and the feature to search URL  is still available

![image](https://user-images.githubusercontent.com/45987684/150217681-0b0797f6-a287-4c7a-a954-ad55cd2affe6.png)


Thanks
Sri

**Comment by philtapp** [comment]
Thanks. My portal experience has reverted back to the previous behaviour and matches what you are showing in the screenshot above. When I was having the issue the search blade was no longer present in the endpoint section and the search bar was up in the header bar with no dropdown. Let's close this and I'll open a new issue with some screenshots if it reoccurs.

**Comment by netbootdisk** [comment]
The UI on my tenant is not showing "Endpoint > Search"

But there's now a search box at the top of the window. Enter the URL in question & select "Search as URL". Then on the right-side panel; select "Open url address page".

The category will then display on the page that loads.
