### ISSUE TITLE
Option does not exist

### ISSUE THREAD

**Issue by bmansf** [MicrosoftDocs/microsoft-365-docs#7394]
[Enter feedback here]
The step "Under Sign-in and security, choose View under Sync users from your org's directory." is not accurate.  There is no option listed to "Sync users from your org's directory".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fec6b1a-892f-4717-02d4-6ceaaabf6222
* Version Independent ID: f1c8418b-8b18-5db9-3376-7f1d65633dfe
* Content: [Synchronize domain users to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/manage-domain-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/manage-domain-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/manage-domain-users.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@bmansf Thank you for your feedback. I see the options have changed. It is now under ***Add or sync users to your Microsoft account***. I have made the necessary changes in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7441

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @bmansf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
