### ISSUE TITLE
Provided Method for finding Consent to Application Activity is not reliable

### ISSUE THREAD

**Issue by BobbyFlayva** [MicrosoftDocs/microsoft-365-docs#7397]
I guess this is more an issue that's inherent to the current state of the Audit Log but the provided direction is not feasible for organizations that generate even a moderate amount of activity lots. The Audit Log only loads the first 250 entries by default which my not capture any Consent to Application activities. A user can not be expected to load the entire log set manually by scrolling infinitely through it.

Consent to Application is not an available activity filter either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66854a7-7556-9b2a-0a33-886e3d881047
* Version Independent ID: 7ce3d8d5-cece-0b6f-68d5-143e12a3fff8
* Content: [Detect and Remediate Illicit Consent Grants - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@BobbyFlayva Author replied that please open support request in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
