### ISSUE TITLE
Add Outlook to the list of client requirements

### ISSUE THREAD

**Issue by sgreenlee11** [MicrosoftDocs/microsoft-365-docs#7402]
Hello,

As Outlook for Windows can be used to open file types like EML and MSG, I think it makes sense include it in the list of client requirements. This will make it clear that Outlook for Windows will use the safe links API to check unwrapped links in these types of files when attached to messages, or when opened directly in Outlook from the file system.

> Safe Links protection for Office 365 apps has the following client requirements:
> 
> Microsoft 365 Apps or Microsoft 365 Business Premium.
> 
> **Current versions of Word, Excel, and PowerPoint on Windows, Mac, or in a web browser.**
> Office apps on iOS or Android devices.
> Visio on Windows.
> OneNote in a web browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@sgreenlee11 Thank you for your feedback. I have added outlook for windows to the requirements section via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7443

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chrisda** [comment]
Be advised that the current list was based on the UI from 2-3 years ago that went into excruciating detail about supported apps. Granted, that was a while ago.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sgreenlee11 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
