### ISSUE TITLE
Enable-OrganizationCustomization is needed on new target tenant

### ISSUE THREAD

**Issue by pgdrews** [MicrosoftDocs/microsoft-365-docs#7403]
In step 3 of the "Prepare the source (current mailbox location) tenant by accepting the migration application and configuring the organization relationship"

I found that when I did the step 3, I got the following error:

**The command you tried to run isn't currently allowed in your organization. To run this command, you first need to run the command: Enable-OrganizationCustomization.
    + CategoryInfo          : NotSpecified: (:) [New-OrganizationRelationship], InvalidOperatio...ontextException
    + FullyQualifiedErrorId : [Server=PH7PR11MB5915,RequestId=c26ef171-cb49-4086-b24e-36b130741d9a,TimeStamp=1/14/2022 2:38:19 PM] [FailureCategory=Cmdlet-InvalidOperationInDehydratedContextException] D6 
   3E7DD6,Microsoft.Exchange.Management.SystemConfigurationTasks.NewOrganizationRelationship
    + PSComputerName        : outlook.office365.com**

The first time I ran the Enable-OrganizationCustomization it took some time to run and then threw and error.  I came back later and ran it again, and it said it had already been completed. 

At that time, I was then able to complete Step 3.  So this may be some knowledge that should be put in the article if this can be reproduced and validated that it was not unique to my clients new Tenant.  

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@pgdrews Thank you for your feedback. I was able to execute the cmdlet without Running Enable-OrganizationCustomization.
In the Microsoft datacenters, certain objects are consolidated to save space, and very rarely the tenant is dehydrated, which is when you will need to run Enable-OrganizationCustomization. I think that was the case with your tenant. 

To check tenant status, you can run Get-OrganizationConfig | fl *isdehydrated*

If it is True, You need to run the cmdlet Enable-OrganizationCustomization.

Hope this helps!

Thanks
Sri

**Comment by kelleyvice-msft** [comment]
Perhaps we could add the following to the script:

# Enable customization if tenant is dehydrated
$dehy=Get-OrganizationConfig | fl isdehydrated
if ($dehy -eq $true) {Enable-OrganizationCustomization}

Sound reasonable?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@pgdrews We have added cmdlet to the script to enable customization if the tenant is dehydrated. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7504

Thank you @kelleyvice-msft 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pgdrews Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
