### ISSUE TITLE
Include new tabs in the document.

### ISSUE THREAD

**Issue by amanmcse** [MicrosoftDocs/microsoft-365-docs#7407]
Please update the document as it includes only 3 tabs - Overview, Analyst report, and Mitigations but there are a lot more tabs available now, as highlighted below:

![image](https://user-images.githubusercontent.com/33834131/149617735-83bdad16-9165-427e-aae8-c1abef45e36d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1834aed2-8822-5a3b-c5c5-ac70b86fa277
* Version Independent ID: 525f0820-aedb-8822-8518-27a5f983f68d
* Content: [Track and respond to emerging threats with Microsoft Defender for Endpoint threat analytics](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/threat-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/threat-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/threat-analytics.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@amanmcse Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7407

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit I received the feedback from the author stating the TA view between Microsoft Defender for Endpoint (MDE) and Microsoft 365 Defender (M365) is different. Hence the difference even in the mitigation tabs that a customer looking at the MDE portal will see compared to what a customer looking at the M365D portal will see.

Hope this helps!

Thanks
Sri
