### ISSUE TITLE
Need migration details

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#7408]
Please add details on how organizations should migrate from older MRM to new retention tags / policies. For example, MRM has been in use for years. How to transfer all of the items that are tagged with existing MRM tags to new retention tags from the compliance center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#related-information)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
@danmyhre   We don't have guidance or tools for this yet, but yes, it is something I would expect to see later

**Comment by danmyhre** [comment]
That is a pretty big deal / miss in functionality. Hopefully Microsoft will think through this and come up with a solution.
