### ISSUE TITLE
What happens to my Words .docx files and my Excel .xlsx files when my subscription expires?

### ISSUE THREAD

**Issue by frankbj57** [MicrosoftDocs/microsoft-365-docs#7410]
The page is very unclear, as it does not give any examples. It is all high level legal gibberish.
If I have created a Word document with a subscription version of Microsoft 365 - will it then eventually disappear or become useless if my subscription ends?
What exactly is Customer Data - is that my documents? Where are they residing? Will I loose my work?
This confusion is the biggest reason I do not want a MS 365 subscription. The next biggest reason is that it is very expensive to pay a substantial amount every year, just to have my document files available, as compared to a fixed price single version app.
Perhaps this is a big misunderstanding but you're not doing a great deal to do away with it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e656ac-5f86-6f46-55fc-5ea2cef0b51c
* Version Independent ID: 74553c8e-e34c-8f5b-c2c2-95100c357d74
* Content: [What happens to my data and access when my subscription ends?](https://docs.microsoft.com/en-gb/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires?redirectSourcePath=%252farticle%252fWhat-happens-to-my-data-and-access-when-my-Office-365-for-business-subscription-ends-4436582f-211a-45ec-b72e-33647f97d8a3&view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/what-if-my-subscription-expires.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@frankbj57 Thank you for your feedback. 

If they are located on your computer, you will still be able to open them, but will not be able to edit them or create new documents.  

If you have them saved on OneDrive, and your subscription has not yet expired, you should download them from OneDrive to your computer as I understand that you will no longer be able to access documents on the OneDrive account that is associated with your subscription, after the subscription expires.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @frankbj57 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
