### ISSUE TITLE
Advanced command -> "scan" - wrong description

### ISSUE THREAD

**Issue by ptrsny** [MicrosoftDocs/microsoft-365-docs#7412]
In the table under "Advanced commands" the command "scan" has the same description as "isolate" witch seems to be wrong.

![screenshot-22-01-17T09-04-02](https://user-images.githubusercontent.com/14097379/149730962-69452987-c570-4e08-8b34-c5dc2f2aede2.png)

![screenshot-22-01-17T09-04-09](https://user-images.githubusercontent.com/14097379/149730991-e68f9a61-9e1f-4a37-8e97-aea2a6c260ea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b2a4c2-e698-dda0-9919-80ca2d05b358
* Version Independent ID: 19b5f609-fcaa-cb5b-96b7-462285fd32e7
* Content: [Investigate entities on devices using live response in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/live-response.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/live-response.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ptrsny Thank you for your feedback. The description for Scan is - "Runs an antivirus scan to help identify and remediate malware."

The same has been updated in the document. Thank you for pointing it out.

CC : @yogkumgit This can be closed.
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ptrsny Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
