### ISSUE TITLE
Thresholds for Geo Location moves

### ISSUE THREAD

**Issue by TheBrookman** [MicrosoftDocs/microsoft-365-docs#7413]
[when starting a SharePoint geo location move I ran into a threshold limit error because the site that I was trying to move was bigger than 1 TB, I ran into a second error from a different site where the list threshold was reached not allowing me to geo locate a site with more than 1 million items in a list. Can you please document all thresholds when geo locating sites, what would be the workaround to resolve, is it possible that these sites can be geo located internally through the PG group, or how can I get around this issue?] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f8357e-400c-d29e-0394-9bfbeea5ed9c
* Version Independent ID: 0ec5d2be-13f3-19b3-1dc5-89f92e5c4816
* Content: [Move a SharePoint site to a different geo location - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/move-sharepoint-between-geo-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/move-sharepoint-between-geo-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/move-sharepoint-between-geo-locations.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@WayneEwington can you help?

**Comment by WayneEwington** [comment]
Adding @chhaya-sharma9 who should be able to assist with documenting these restrictions

**Comment by chhaya-sharma9** [comment]
Hello, the size limit of 1TB is captured as a limitation in the documentation to move a OneDrive - https://review.docs.microsoft.com/en-us/microsoft-365/enterprise/move-onedrive-between-geo-locations?view=o365-worldwide&branch=main#scheduling-onedrive-site-moves 
The limitation applies equally for SharePoint site moves as well. 
Required gaps in documentation would be bridged. 
Thanks

**Comment by yogkumgit** [comment]
@TheBrookman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TheBrookman** [comment]
understand your point but I was not looking to move one drive I was looking to move a SharePoint site, therefore it needs to be documented in the SharePoint documentation, correct, or a least linked to the documentation, anyway however you do it the thresholds need to be mentioned in that SP article.
thanks!
