### ISSUE TITLE
Defender Plan 1 vs Defender Plan 2 vs Defender Azure vs Onboarding

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#7414]
Hello,

Some time ago we have enabled the full Azure Security Center (Defender for Azure), this activated Defender ATP's old platform that is now migrated to the Microsoft 365 Defender (security.microsoft.com), then later we enabled Microsoft 365 E5 security for some users, then enabled Defender Plan 2 and we onboarded those users devices to Microsoft 365 Defender using Endpoint, now all users with Microsoft 365 E3 received Defender Plan 1, assuming that onboarding process is still same via Endpoint... 
But, because Defender for Azure and Defender Plan 2 activate other services like "vulnerability management" etc. in Microsoft 365 Defender, how can we make sure we stay compliant with the license?

Or if we onboard:

1. Azure servers via Azure Defender - this triggers extra services because servers licensed for this
2. Defender Plan 2 - this enabled all futures from Defender ATP and those devices will show all data from the full license
3. Defender Plan 1 - all those devices, if we go to the device will show us some limited information

Will it be the case?
Or because we have 1-2 enabled, the 3 will allow us to see all options possible to get from Microsoft 365 Defender? 
How can we stay license complaint, split deployment or we shouldn't care about it because it is as it is and there is no way to do so, so it is not a customer problem?

This message is to request documentation about a possible combination of licenses per single-tenant, like what if we have Plan 2 and Plan 1 or what if Azure Defender and Plan 1, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d966a60-ffac-d1b0-4a2c-34bd64edd5ce
* Version Independent ID: da866056-2041-3c18-77c9-05fdd5fa7caa
* Content: [Overview of Microsoft Defender for Endpoint Plan 1](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-plan-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1.md)
* Product: **m365-security**
* Technology: **mdep1**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
@yogkumgit I have reached out to PMs for help with this issue and will respond here soon.

**Comment by denisebmsft** [comment]
Hello @lightupdifire and thank you for posting this excellent question. We understand that this is an issue, and we are working on it at priority.
