### ISSUE TITLE
Document requirements to apply a custom detection to "All devices"

### ISSUE THREAD

**Issue by 0xThiebaut** [MicrosoftDocs/microsoft-365-docs#7415]
The "Create and manage custom detections rules"  documentation mentions the following under the "Set the rule scope" section:

> Set the scope to specify which devices are covered by the rule. The scope influences rules that check devices and doesn't affect rules that check only mailboxes and user accounts or identities.
> 
> When setting the scope, you can select:
> 
>  -  All devices
>  -  Specific device groups
> 
> Only data from devices in scope will be queried. Also, actions will be taken only on those devices.

We have however observed instances where the "All devices" option is not available. Could you document which requirements have to be met for that option to be presented?

#### Expected layout:
![image](https://user-images.githubusercontent.com/46688461/149778954-1cfafe0a-4aff-47d9-9974-2a864ecfee62.png)

#### Observed layout:
![image](https://user-images.githubusercontent.com/46688461/149778877-05be0574-26c0-4d8b-90b8-e588d3f94aa4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf510e0-742e-fce6-787e-18eb8a22f42d
* Version Independent ID: 23b77843-cf19-aacb-47af-1f51792c76a0
* Content: [Create and manage custom detection rules in Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/custom-detection-rules?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/custom-detection-rules.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/custom-detection-rules.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@0xThiebaut Thank you for your feedback. The required permissions are Security Administrator or Security operator (will need the manage security settings permission in Microsoft Defender for Endpoint if RBAC is turned on.) 

If the permissions are still intact and you still have a problem viewing all devices section, I'd recommend you to contact Microsoft support via the need help section in the M365 Admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @0xThiebaut 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
