### ISSUE TITLE
Audited Activities available in the Unified Audit log Search UI, but are not yet functional (ex: Forms activities)

### ISSUE THREAD

**Issue by jetkjh** [MicrosoftDocs/microsoft-365-docs#742]
Please add to the Audited Activities verbiage that clarifies when activities present in the S&C UI are not listed here are not yet functional.

Note: You may see some audited activities available in the Security and Compliance Center Audit log search UI that are not yet functional (such as Forms events). Until the these classifications of events are present in the above named list, they should not be expected to present functionality and should not be used in a production environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@jetkjh  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by j0rt3g4** [comment]
Hello @jetkjh 
We are a documenting team, we can't provide information or report to technical issues for that you can use other channels like technical support ticket or user's voice.
