### ISSUE TITLE
Trial for Microsoft Defender for Office 365 Plan 1

### ISSUE THREAD

**Issue by ShawnHag** [MicrosoftDocs/microsoft-365-docs#7420]
Hello, 
I have a question about the free trial of defender for office.

On this article, I saw that a free trial for defender for office plan 2 is available.

From the admin portal, I saw the "free trial" button for plan 2.
But there was no "free trial" button for the plan 1 license.

Is there any way to try the defender for office plan 1 for free?

Thank you in advace,
Shawn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d08fef08-2fa6-79c4-4adf-e1e194a33a0d
* Version Independent ID: 6c962f09-1e5d-bcac-c58f-ecaf58bc9774
* Content: [Evaluate Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-evaluation?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/office-365-evaluation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-evaluation.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ShawnHag, in the context of the admin portal and the content of the topic in question, no there's no way to do a Plan 1 trial; everything is about Plan 2.

In the greater world of Microsoft 365 at <https://www.microsoft.com/microsoft-365/>, is it possible to get a Defender for Office 365 Plan 1 trial? Maybe. But it won't be tightly integrated as described in the topic.

**Comment by ShawnHag** [comment]
@chrisda , Hello
Thank you for your reply.

I`ve seen few people (including myself) wanting to see the difference between Plan 1 and Plan 2 through an actual environment.
It`ll be great if there will be a free trial for the Plan 1 in the future.

Thanks for your time and the great products.

Best regards,

**Comment by chrisda** [comment]
Sure. In some respects, there isn't much different, but in other respects, there's a lot of details that are different.

From [this topic](https://docs.microsoft.com/microsoft-365/security/office-365-security/defender-for-office-365), the main additions from P1 to P2 are:

- [Threat Trackers](threat-trackers.md)
- [Threat Explorer](threat-explorer.md)
- [Automated investigation and response](office-365-air.md)
- [Attack simulation training](attack-simulation-training.md)
- [Campaign Views](campaigns.md)

Really, Attack simulation training and Campaign Views are discreet features. But good grief, there's a lot of differences between Real-time Detections and Threat Explorer!
