### ISSUE TITLE
Please fix the link to the Webinar. 

### ISSUE THREAD

**Issue by fussytroll** [MicrosoftDocs/microsoft-365-docs#7421]
[Enter feedback here]
Link to the Webinar is resulting in 404, Please fix the link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Records Management in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/records-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records-management.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@fussytroll   Thanks for flagging this.  The link is taken from the blog post https://techcommunity.microsoft.com/t5/security-compliance-and-identity/records-management-webinar/ba-p/1456654, and it's not working from there.  I'm trying to find out if it's moved or no longer available.

**Comment by cabailey** [comment]
@fussytroll  Unfortunately, that recording is no longer available.  I've updated the page accordingly.

**Comment by fussytroll** [comment]
Thanks @Carol Bailey

Regards
Talwar
________________________________
