### ISSUE TITLE
Text in this section has repeating words

### ISSUE THREAD

**Issue by mbrown19465** [MicrosoftDocs/microsoft-365-docs#7424]
On the Logos page, **you can you can** add your logos, and specify the URL where users will navigate to, when they select the logo.

https://docs.microsoft.com/en-us/microsoft-365/admin/setup/customize-your-organization-theme?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide#logos-specify-your-theme-logos

**Comment by msbemba** [comment]
@mbrown19465 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7447

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mbrown19465 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
