### ISSUE TITLE
"Submit and view feedback for This product"- still broken on your entire website...

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/microsoft-365-docs#7426]
Microsoft has been planning and moving, over the last couple of years, to your new Q&A site. Why are we still getting redirects to "This UserVoice instance is no longer available" when clicking on "Submit and view feedback for This product"?

Please update this link in your website templates to at least drop us in your Q&A home page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e0344cf-9692-43ff-94c3-f86f7d61e53b
* Version Independent ID: bd84da4a-c6c1-d5ae-2a68-a0093629b460
* Content: [Report false positives and false negatives in Outlook - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-false-positives-and-false-negatives?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/report-false-positives-and-false-negatives.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/report-false-positives-and-false-negatives.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@deejerydoo Thank you for your feedback. I'm working with the author to get this corrected on the documents.

Thanks
Sri

**Comment by yogkumgit** [comment]
@Dansimp

**Comment by chrisda** [comment]
Testing today 7/10/2023 reveals that clicking on **This product**

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/33166947/e17339e3-51e3-4ba9-b157-a326d5620279)

Takes you to [Provide feedback on Microsoft 365 Defender](https://learn.microsoft.com/microsoft-365/security/defender/feedback).

So, I guess time does heal all wounds.

Thanks for the feedback.

Closing.
