### ISSUE TITLE
more step needed

### ISSUE THREAD

**Issue by tamiyatxt1** [MicrosoftDocs/microsoft-365-docs#7428]
[Enter feedback here]
Within step 11, need to create a profile for this file as well.

**sysext.mobileconfig**

If this profile is not created, following bundle will not be identified.

6. Under Bundle identifier and Team identifier, set these values
Bundle identifier | Team identifier
**com.microsoft.wdav.epsext | UBF8T346G9**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1858cbcb-cbc6-850f-c291-61edbe01d195
* Version Independent ID: 1858cbcb-cbc6-850f-c291-61edbe01d195
* Content: [Onboard and offboard macOS devices into Microsoft 365 Compliance solutions using Microsoft Intune (preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-offboarding-macos-intune?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/device-onboarding-offboarding-macos-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/device-onboarding-offboarding-macos-intune.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@tamiyatxt1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7449

Thanks
Sri
