### ISSUE TITLE
feedback link dont' working

### ISSUE THREAD

**Issue by fipe-ch** [MicrosoftDocs/microsoft-365-docs#7430]
Hi

Feedback Link https://aka.ms/mdagoffice-fb don't working.

Kind Regards,

Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cc5310-e03b-d538-e741-09be5f32ab13
* Version Independent ID: 6f56df92-3eb1-56ff-efc9-a4d269efd7aa
* Content: [Application Guard for Office 365 for admins - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/install-app-guard?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/install-app-guard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/install-app-guard.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@fipe-ch Thank you for your feedback. Feedback Hub is an application and when click on the link you will see a pop up window like below to open it with the application installed on your computer

![image](https://user-images.githubusercontent.com/45987684/150532870-73eac8d0-0261-42e8-8c54-1482277f1a8d.png)

I was able to test the link on multiple computers and it seems to be working now.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @fipe-ch Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
