### ISSUE TITLE
i cant download this to my pc :(

### ISSUE THREAD

**Issue by Thisissowicandownloadgoanimate** [MicrosoftDocs/microsoft-365-docs#7432]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62dfa25-e420-38e4-ff47-05cca62d14ec
* Version Independent ID: 5ea03ce0-38b9-e005-a430-e98442e2ec83
* Content: [Deploy add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by Thisissowicandownloadgoanimate** [comment]
someoen help

**Comment by msbemba** [comment]
@Thisissowicandownloadgoanimate Thank you for your feedback. The add-ins will be automatically added to your outlook profile if the requirements are met. If they are not showing up, we recommend you contact Microsoft support via the need help Icon on the M365 Admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Thisissowicandownloadgoanimate 
Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
