### ISSUE TITLE
Configure alert notifications: what's the PowerShell way?

### ISSUE THREAD

**Issue by KhaaliTurbo** [MicrosoftDocs/microsoft-365-docs#7434]
Been looking everywhere to get the proper API endpoint in order to retrieve the [configured] email alert|vulnerability notification settings, but am unable to find this. Please advise whether this is programmatically possible. Asking for an MSSP friend.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f066b4c-ef35-cb0a-50af-8d8cfd381790
* Version Independent ID: 379396f5-064a-2048-dce7-7b2e4ff69dda
* Content: [Configure alert notifications in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-email-notifications?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-email-notifications.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-email-notifications.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Not aware of ability to do it programmatically but here are some links for notification guidance: 

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-mssp-notifications?view=o365-worldwide
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-email-notifications?view=o365-worldwide#create-rules-for-alert-notifications
