### ISSUE TITLE
Should rename the page to "Lore of Contoso"

### ISSUE THREAD

**Issue by TitleOS** [MicrosoftDocs/microsoft-365-docs#744]
I love me some lore for a fake company, can't wait for Elder Scrolls: Contoso

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd9ad252-50c2-e9d6-9e1a-ab5efde15e60
* Version Independent ID: 7d82a046-e1e2-015f-cb09-27798701b131
* Content: [Overview of the Contoso Corporation](https://docs.microsoft.com/en-us/microsoft-365/enterprise/contoso-overview#feedback)
* Content Source: [microsoft-365/enterprise/contoso-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/contoso-overview.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@TitleOS More content is on its way for you to read or print (Printer is coming...). :)
