### ISSUE TITLE
DKIM instructions no longer valid.

### ISSUE THREAD

**Issue by tommylux** [MicrosoftDocs/microsoft-365-docs#7448]
This page appears to be out of date:
on https://security.microsoft.com/dkimv2
there is no option to generate the CNAMES. Only an option to 'sign messages for this domain with DKIM signatures'. The following error message then says that the CNAME is not set up in DNS.

There doesn't appear to be a way to see what CNAME needs to be set up as depicted in this guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide#how-dkim-works-better-than-spf-alone-to-prevent-malicious-spoofing-in-office-365)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@tommylux Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7489

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tommylux Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
