### ISSUE TITLE
Any limitations on Export

### ISSUE THREAD

**Issue by bvksphub** [MicrosoftDocs/microsoft-365-docs#745]
Any limitations on Export in terms of max # of files, size similar to Core eDiscovery limits?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2fc0c55-c012-4496-b28f-7462daef5ea9
* Version Independent ID: 6abe59ff-8679-98c5-7261-525d818b0b7d
* Content: [Export case data in Advanced eDiscovery](https://docs.microsoft.com/en-us/microsoft-365/compliance/exporting-data-ediscover20?source=docs#feedback)
* Content Source: [microsoft-365/compliance/exporting-data-ediscover20.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/exporting-data-ediscover20.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@bvksphub Please see https://github.com/MicrosoftDocs/microsoft-365-docs/issues/746
