### ISSUE TITLE
Wrong words - Application setup area

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/microsoft-365-docs#7454]
Step 5
On the Register an application page, under Supported account types, Select Accounts in any organizational directly (Any Azure AD directory - Multitenant).

after organizational .... the word directly needs to be updated.

Step 13
In the Request API permissions windows, select APIs my organization users, and search for office 365 exchange online, select it.

after the word organization > users should be uses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Karr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7472

Thanks
Sri
