### ISSUE TITLE
Microsoft Endpoint link leading to 404 error

### ISSUE THREAD

**Issue by Amplify101** [MicrosoftDocs/microsoft-365-docs#7457]
[Hi @JoeDavies-MSFT, https://docs.microsoft.com/en-us/microsoft-365/security/defender/integrate-microsoft-365-defender-secops-services?view=o365-worldwide on this page, there is a list of our Defender products as links and I found the **MDE link** didn't work.  Just wanted to bring to your attention.  Thank you for everything! Great article! - Respectfully, Avani]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b92d260-ca15-0bdf-0d36-66ea6189f516
* Version Independent ID: 9c436392-f1b5-a66e-74a8-7a8b85347738
* Content: [Step 3. Plan for Microsoft 365 Defender integration with your SOC catalog of services](https://docs.microsoft.com/en-us/microsoft-365/security/defender/integrate-microsoft-365-defender-secops-services?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/integrate-microsoft-365-defender-secops-services.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/integrate-microsoft-365-defender-secops-services.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by msbemba** [comment]
@yogkumgit The PR is merged and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Amplify101 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
