### ISSUE TITLE
startssl.com

### ISSUE THREAD

**Issue by vhpang** [MicrosoftDocs/microsoft-365-docs#7458]
[Enter feedback here]

Why stiil consider *.startssl.com which ceasing operations by 2018 and with Mozilla, Google and Apple distrusting their certificates?
https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f283e6d-8054-3abf-becf-65037e9c70b7
* Version Independent ID: e8dfaaad-a731-bd2e-7c7b-c5d0b80462de
* Content: [Microsoft 365 encryption chains - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-certificate-chains?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-office-365-certificate-chains.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-certificate-chains.md)
* Service: **o365-seccomp**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. The AIA and OSCP endpoints listed in the table were mistakenly left in place when their related certificates were removed from the article. I am removing them as part of a broader update to the article. Thanks! -Kelley
