### ISSUE TITLE
Instructions do not match screen reality

### ISSUE THREAD

**Issue by sinnermark** [MicrosoftDocs/microsoft-365-docs#7459]
[Enter feedback here]
Instructions say' Step 2: Click on Create DKIM keys.'

It is not obvious that you have to click on the grey are of the domain name to open the dialogue that contains the button.  It is not intuitive.

That you are pushing users to f$%king git hub in the same windo when trying to provide feedback is a nightmare.

I pay for microsft products as I expect a seemless user friendly experience.  Not to have to go throw multiple trial and error attemps to work out what needs to be done.

If I didn't know what github was or have an account, how would I leave feedback.

Talk about not carring for paying users, not everyone wants to work as hard as developers.

Typical developer assumptions, very disappointing.  There's a reason developers build things and BA's or product managers, CX people do their job.  Because devs are a bumch of muppets who assume everyone knows the deep details they do.  FFS!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@sinnermark Thank you for your feedback. You are right, the steps have changed recently. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7489

Instead of Clicking on  Create DKIM keys, You need to toggle the button to enable DKIM. The pop-up window that appears will provide the CNMAE records that need to be added.

Sorry for the confusion.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sinnermark Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
