### ISSUE TITLE
Any limitations on Export

### ISSUE THREAD

**Issue by bvksphub** [MicrosoftDocs/microsoft-365-docs#746]
Any limitations on Export in terms of max # of files, size similar to Core eDiscovery limits?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b5b9f-5ee0-cf64-d39a-38f010315b8a
* Version Independent ID: f9bdd1e6-e8e1-eef1-f9ca-b9a2b473dc7d
* Content: [Advanced eDiscovery limits](https://docs.microsoft.com/en-us/microsoft-365/compliance/limits-ediscovery20)
* Content Source: [microsoft-365/compliance/limits-ediscovery20.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/limits-ediscovery20.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@bvksphub The backend for exporting data from core eDiscovery and Advanced eDiscovery are completely different, so the limits in core eDiscovery don't apply to AeD. Data in a review set in AeD is storage in a Azure Storage blob. In the export workflow, you're downloading data from the Azure blob, so any limits would be Azure storage blob limits. I've done a quick search and I can't find any total size or daily limits (see the link below for egress limits which relate to throughput. My assumption is that you will hit AeD case limits before you will hit Azure export limits. If you do hit an export limit, you could open a case with MS support. If you hit a limit using Azure Storage Explorer, you might try using AzCopy (though not sure if limits are different for these tools). Here are few relevant links below. We'll look into adding a statement about export in this topic.

HTHs

https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#storage-limits

https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#upload-and-download-data-limit

https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10?toc=%2fazure%2fstorage%2fblobs%2ftoc.json

**Comment by bvksphub** [comment]
Thank you. This is helpful.
