### ISSUE TITLE
Microsoft Defender Event ID: 5013 is not documented

### ISSUE THREAD

**Issue by ig-tr** [MicrosoftDocs/microsoft-365-docs#7461]
Hello, i see eventid 5013, but i not find documentation about this event.
`Tamper Protection Blocked a change to Microsoft Defender Antivirus.
 	Value: HKLM\SOFTWARE\Microsoft\Windows Defender\Real-Time Protection\DisableRealtimeMonitoring = (Current)
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102c5c34-0c04-cc14-8e9c-74ff42e1fdc2
* Version Independent ID: 6a06016e-6ac1-ab00-5a33-1d1226e2e45d
* Content: [Microsoft Defender Antivirus event IDs and error codes](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@ig-tr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7527

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ig-tr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
