### ISSUE TITLE
Monitored files should include archives (zip) 

### ISSUE THREAD

**Issue by robertofan** [MicrosoftDocs/microsoft-365-docs#7462]
Hi,
based on what's written on [this post](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/announcing-expanded-dlp-coverage-to-new-file-and-content-types/ba-p/2902869#:~:text=Protect%20sensitive%20files,inappropriate%20file%20transfer.) I believe that archives (zip, ...) should be included among the file types listed on the page in the section [Monitored files](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-learn-about?view=o365-worldwide#monitored-files)

Thanks!
Roberto

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 820cb23f-f33d-241d-5ce2-1d824bcd3747
* Version Independent ID: 36d24f60-27b6-f2c1-ccda-1b49a1d4f073
* Content: [Learn about Microsoft 365 Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-learn-about?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@robertofan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7499

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@robertofan closing as per the author's input. Thanks
