### ISSUE TITLE
Does not align with Plan 1

### ISSUE THREAD

**Issue by ConfigConfused** [MicrosoftDocs/microsoft-365-docs#7464]
Plan 1 customers do not have access to all of the features mentioned yet page states it is applicable to Plan 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96cedf2c-e6fa-bbfb-61f0-ab4bcaae1479
* Version Independent ID: 45ca9ffb-55e9-7721-3433-017a513a59be
* Content: [Use attack surface reduction rules to prevent malware infection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#attack-surface-reduction-rules?WT.mc_id=365AdminCSH_M365SecurityCenter)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@ConfigConfused Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7481

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ConfigConfused Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
