### ISSUE TITLE
Assigning Multi-Geo Licensing to Shared Mailboxes

### ISSUE THREAD

**Issue by michaeljonathanparish** [MicrosoftDocs/microsoft-365-docs#7465]
Could this page be updated with details of applying Multi-Geo licensing to Shared Mailboxes? Is it required? how is it done?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289f2440-9c44-7d93-20e3-baa9e9892cd9
* Version Independent ID: abc4e209-a071-d28a-cb01-aa72bbaee7c0
* Content: [About shared mailboxes - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/about-shared-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/about-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/about-shared-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@michaeljonathanparish Thank you for your feedback. I have added information about Multi geo to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7478

In a multi-geo environment, Shared mailboxes need to be licensed the same way a user mailbox is licensed. Note that cross-geo mailbox auditing is not supported. For example, if a user is assigned permissions to access a shared mailbox in a different geolocation, mailbox actions performed by that user are not logged in the mailbox audit log of the shared mailbox. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @michaeljonathanparish Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
