### ISSUE TITLE
Dead end on Microsoft FastTrack

### ISSUE THREAD

**Issue by lkchild** [MicrosoftDocs/microsoft-365-docs#7466]
The instructions rely on Microsoft FastTrack, but FastTrack is not available unless you have added over 150 seats.  There is no way to continue after registering with the FastTrack portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58b6670c-3ed1-97f9-b728-79bb77106206
* Version Independent ID: 50934005-9e01-e6ea-21dc-af6735e1faa7
* Content: [Set up Customer Key - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-set-up?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/customer-key-set-up.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/customer-key-set-up.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by lkchild** [comment]
I found it - you need to navigate to the "Deploy" tab.

**Comment by msbemba** [comment]
@lkchild Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7534

You are correct, it is now changed to Deploy

![image](https://user-images.githubusercontent.com/45987684/151559120-08f07ba1-2c2d-480a-9eb7-9f9aacaa38f9.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lkchild Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
