### ISSUE TITLE
the location of conversation is not located in exchange anymore its located elsewhere. 

### ISSUE THREAD

**Issue by Alfredox911** [MicrosoftDocs/microsoft-365-docs#7467]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb41d287-f954-dc84-782c-de8fa3c1ea0d
* Version Independent ID: 0081aa8b-87dd-aef2-aaeb-61caa8f20351
* Content: [Teams workflow in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by Alfredox911** [comment]
https://support.microsoft.com/en-us/office/export-or-delete-your-teams-data-1ed6ac68-5fb4-41be-9861-1a4127fecf68

Users and request the export of conversations here.. Where is the data located ?

**Comment by msbemba** [comment]
@Alfredox911 Thank you for your feedback. For channel conversations, messages are journaled to the group mailbox in Exchange Online, where they're available for eDiscovery.

Personal chats including group chats are stored in the mailboxes of the users. However, these are not accessible immediately and are in hidden folders. - https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Alfredox911 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
