### ISSUE TITLE
Does this sentence make sense?

### ISSUE THREAD

**Issue by SteveCuriously** [MicrosoftDocs/microsoft-365-docs#7468]
Dear Microsoft,

Does this sentence make sense?

"Opening the file and help the attacker compromise the target's device."

I wonder if this is a typo and the word 'and' should be replaced by a word such as 'will'?

Regards,
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c312fd69-72cd-bc86-4fe1-993b60b97bc6
* Version Independent ID: b7887ba6-4775-39f0-e368-68f140ce233d
* Content: [Simulate a phishing attack with Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@SteveCuriously Thank you for your feedvack. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7476

Thanks
Sri

**Comment by chrisda** [comment]
PR approved.

Thanks for the feedback.

Closing

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SteveCuriously Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
