### ISSUE TITLE
Typo in first bullet -- url with misspelled 'microsoft'

### ISSUE THREAD

**Issue by boelters** [MicrosoftDocs/microsoft-365-docs#7469]
"In the Microsoft 365 Defender portal at **https://security.microsofot.com**"

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-assign-standard-and-strict-preset-security-policies-to-users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f1cf3-a121-3c6e-9380-79440f4c6671
* Version Independent ID: 9b1bc5d1-8ecc-d0f9-092e-325c6acff4fe
* Content: [Preset security policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-assign-standard-and-strict-preset-security-policies-to-users)
* Content Source: [microsoft-365/security/office-365-security/preset-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/preset-security-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@boelters, Yikes! Thanks for catching that. In the future, you can make fixes like this directly (no need to open an Issue first). For instructions, see [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
