### ISSUE TITLE
Microsoft 365 compliance center

### ISSUE THREAD

**Issue by jpawlowski** [MicrosoftDocs/microsoft-365-docs#747]
Hi,

this documentation says that Sensitivity Labels are supported in Microsoft 365 compliance center. In fact, those are not there but in the Microsoft 365 _security_ center. This may be corrected.

Don't worry, mixing this up is easy to do, especially as the legacy "Office 365 security & compliance center" is also still there ;-)

Cheers,
Julian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by alschneiter** [comment]
Based on that blog, Public preview starts Nov 20th, 2019.
See section "Sensitivity labels for Teams, Office 365 Groups, and SharePoint Sites":
https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/SharePoint-and-OneDrive-Security-compliance-migration-admin-and/ba-p/960871?utm_source=t.co&utm_medium=referral

**Comment by mypil** [comment]
@jpawlowski  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by KCCross** [comment]
alschneiter pointed to the blog that answers this. Thanks!
