### ISSUE TITLE
Need more troubleshooting options

### ISSUE THREAD

**Issue by chuck-milyli** [MicrosoftDocs/microsoft-365-docs#7470]
I have an M365 E3 license associated with my account and have for days. 

I still receive the error that there is no mailbox associated with my account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00421a8e-42cf-c393-f91d-da1b7d7cc7da
* Version Independent ID: de00b816-762d-2171-eb7f-1ce6a55ec189
* Content: [Getting a mailbox not found error in Outlook on the web - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/mailbox-not-found-error?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/mailbox-not-found-error.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/mailbox-not-found-error.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@chuck-milyli Thank you for your feedback. 

M365 E3 has multiple services associated with it, there is a good chance that Exchange online plan2 is unchecked or not assigned.

Could you please Open the Microsoft 365 admin center and go to Active users under the Users section, and select your account.
In the user page that opens, go to the Licenses and Apps section, select the appropriate Location value, and assign a license that contains Exchange Online (expand the license to see its details).

If this is already assigned, there is a good chance that the mailbox is pending or stuck in provisioning. Opening a support ticket with Microsoft via the need help icon on the admin center will help you get in touch with a Microsoft support engineer who can fix this in the backend.

Hope this helps!

Thanks
SRi

**Comment by chuck-milyli** [comment]
Sorry, the GitHub forum might not have been the best place to post that.

I thought I was just responding to why the information on the help page wasn't useful to me.

We ended up opening a ticket with Microsoft.


Turns out my account and several others had orphaned, on-prem exchange email accounts associated with them from a test exchange server that had been setup and decommissioned extremely incorrectly several years previously.

We didn't realize this because we had been using Google Suite for production email until we migrated recently which brought up this issue.

MS support got us sorted out.



Cheers!





CHUCK KINNAN

Engineering & IT Manager, Founder


________________________________

**Comment by msbemba** [comment]
Thank you for the update. We are glad that the issue got sorted out.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @chuck-milyli Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
