### ISSUE TITLE
Add instructions to find machine id from defender portal.

### ISSUE THREAD

**Issue by belqesghrama** [MicrosoftDocs/microsoft-365-docs#7477]
For this http request " POST https://api.securitycenter.microsoft.com/api/machines/{id}/offboard "

Kindly add how to find the machine id as I was not able to find it anywhere until I had to ask many of my coworkers to get it, it's nearly impossible to spot it, It will be so useful and stright forward if you added how to find the machine id from device inventory page , from the URL on the top and include a screen shot of where to find it. 
Regards,
Belqes
![machine id](https://user-images.githubusercontent.com/71808990/150853285-4d9ceb3f-6ee5-44f2-baa9-4718109c3561.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05007b38-2a58-d34a-6afb-838e2ddd380e
* Version Independent ID: d0e699b6-abe7-e8f6-a093-ecec52559dec
* Content: [Offboard machine API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/offboard-machine-api?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/offboard-machine-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/offboard-machine-api.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara*
![machine id](https://user-images.githubusercontent.com/71808990/150853342-d386a4bb-2105-4a97-8b20-7c0631d8f460.png)
*

**Comment by msbemba** [comment]
@belqesghrama Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7577. 

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @belqesghrama Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
