### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#748]
Message MC192874  stated that this was rolled out in October, but I'm not seeing it yet. Has it been delayed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de70c835-f408-83a6-3cc7-885756bd7152
* Version Independent ID: 076708dd-80e4-39d7-7e23-42730c106900
* Content: [Automated investigation and response (AIR) in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/automated-investigation-response-office)
* Content Source: [microsoft-365/security/office-365-security/automated-investigation-response-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/automated-investigation-response-office.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @DeanGross! When a feature like this reaches general availability, it can still take a few weeks to reach all tenants. Assuming your subscription includes AIR, you should have these features anytime now. I'm going to close this issue for now, but please let us know if you have any other questions.
