### ISSUE TITLE
Missing description for "View-Only Case"

### ISSUE THREAD

**Issue by CharlieDiesel** [MicrosoftDocs/microsoft-365-docs#7485]
In analysing role risk for implementing an RBAC model for a government entity, I have yet to come across any documentation that decsribes what "View-Only Case". I can make assumptions of course, but a description of this role would be much appreciated.

Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions - Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@CharlieDiesel, from what I can tell, the View-Only Case role only gives access to the [Get-ComplianceCase](/powershell/module/exchange/get-compliancecase) cmdlet (and the corresponding features in the UI). Access to the UI often depends on multiple roles, so creating a custom role group with only View-Only Case assigned might not work.

According to the CaseType parameter description, the following types of cases are available:

- AdvancedEdiscovery: Advanced eDiscovery cases are used to manage legal or other types of investigations. In the Microsoft 365 compliance center, Advanced eDiscovery cases are displayed under **eDiscovery** \> **Advanced eDiscovery**.
- ComplianceClassifier: This type of case corresponds to a trainable classifier. In the Microsoft 365 compliance center, trainable classifiers are displayed under **Data classification** \> **Trainable classifiers**.
- ComplianceWorkspace: This value is reserved for internal Microsoft use.- DataInvestigation: Data investigation cases are used to investigate data spillage incidents. In the Microsoft 365 compliance center, Data investigation cases are displayed on the Data investigations page.
- DSR: Data Subject Request (DSR) cases are used to manage General Data Protection Regulation (GDPR) DSR investigations. In the Microsoft 365 compliance center, DSR cases are displayed under **Data privacy** \> **Data subject requests**.
- eDiscovery: eDiscovery (also called core eDiscovery) cases are used to manage legal or other types of investigations. In the Microsoft 365 compliance center, core eDiscovery cases are displayed under **eDiscovery** \> **eDiscovery**. This is the default value.
- InsiderRisk: Insider risk cases are used to manage insider risk management cases. In the Microsoft 365 compliance center, insider risk cases are displayed under **Insider risk management** \> **Cases**. Typically, insider risk management cases are manually created in the compliance center to further investigate activity based on a risk alert.
- InternalInvestigation: This value is reserved for internal Microsoft use.
- SupervisionPolicy: This type of case corresponds to communication compliance policy. In the Microsoft 365 Compliance center, communication compliance policies are displayed under **Communication compliance** \> **Policies**.

Additionally, according to the error message when you feed the parameter a junk value, the following values are also available, but these need to be confirmed:

- DataInvestigation
- InsiderRiskAuditSearch
- SupervisionPolicy

**Comment by CharlieDiesel** [comment]
Thank you so much for your detailed response @chrisda, it has provided that extra insight I was after but did not know how to get to myself.

**Comment by yogkumgit** [comment]
@CharlieDiesel If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
