### ISSUE TITLE
information about limitations incorrect

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/microsoft-365-docs#7487]
regarding this part of the document:
![image](https://user-images.githubusercontent.com/39616319/150938233-4520ecda-3be5-4823-b2a7-3d337cc44bd9.png)

I checked this functionality and all of those limitations are working in our environment. Could you please investigate if these limitations are still apply?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dd3497a-c02a-5fd6-12db-3a093f0fe17c
* Version Independent ID: 2ef81556-61b0-47ae-d8fc-3d9aa5240c51
* Content: [Restrict access to content using sensitivity labels to apply encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-sensitivity-labels?view=o365-worldwide#considerations-for-encrypted-content)
* Content Source: [microsoft-365/compliance/encryption-sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Checking with engineering

**Comment by cabailey** [comment]
@SRE93 Have you enabled co-authoring for your tenant?

**Comment by SRE93** [comment]
> @SRE93 Have you enabled co-authoring for your tenant?

@cabailey yes we have

**Comment by cabailey** [comment]
@SRE93  Confirmed from engineering, if you've enabled co-authoring, you get these fixes "for free" :-)   Still a problem if you haven't.  I've updated the section accordingly.  Thanks for flagging!
