### ISSUE TITLE
OCR Feature

### ISSUE THREAD

**Issue by bvksphub** [MicrosoftDocs/microsoft-365-docs#749]
I have tried to explore this feature but could not see any result. 

Does OCR gets executed only when preparing results from core for Adv analysis? i belive that in Adv eDiscovery, while adding search results to review OCR gets executed. i have tried adding lot of content from search to Adv eDiscovery after enabling OCR in settings. i pretty much see same items in Review set. i see lot of images has text inside. When i did review set search i could not get search results for those images.( i am searching keyword/text that contained in a image)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7605608e-97ad-5daa-a560-7e1e37acc55b
* Version Independent ID: 465ff1b5-5bd3-ce65-aef6-a77373bb6ce6
* Content: [Prepare search results for Office 365 Advanced eDiscovery](https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-search-results-for-advanced-ediscovery?source=docs#feedback)
* Content Source: [microsoft-365/compliance/prepare-search-results-for-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prepare-search-results-for-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by bvksphub** [comment]
I have recreated new search and added to review set. it worked. but it could not extract from all images. I ahve verified for following supported extensions

GIF
JPEG
JPG
PNG
TIFF

**Comment by mypil** [comment]
@bvksphub  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@bvksphub - I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
