### ISSUE TITLE
this page desperately needs information about DLP roles

### ISSUE THREAD

**Issue by paul-rich** [MicrosoftDocs/microsoft-365-docs#7497]
[Enter feedback here]
I find it virtually impossible to find out the specific rights that are granted to an identity as a result of being assigned the role "View-Only DLP Compliance Management". Likewise with the "DLP Compliance Management" role. It is criminal that Microsoft ships role groups and roles without documenting what permissions they grant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adedbe4e-fdfa-473e-6f55-4f0247658472
* Version Independent ID: ee52c4d5-6588-215c-ef92-035211cb302f
* Content: [Learn about data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-learn-about-dlp?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-learn-about-dlp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-learn-about-dlp.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@paul-rich Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7578

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chrfox** [comment]
this content is already live in https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy?view=o365-worldwide
