### ISSUE TITLE
Need more details on finding Duplicate files

### ISSUE THREAD

**Issue by bvksphub** [MicrosoftDocs/microsoft-365-docs#750]
We can see duplicate file count in the report which is good. But in practical scenario it will be good if we know the list of files. Is there any way that we can create query to list duplicate files in the review set. This will help users to filter out those document and focus more on relevant documents. I have tried using few filters like "representative" but its not helping completely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fb8cc9-d3a4-1e44-9ed9-93b3bbf2ef4f
* Version Independent ID: e4c7e64f-4346-bce5-d2b9-3e6af04abe75
* Content: [Analyze data in a review set in Advanced eDiscovery](https://docs.microsoft.com/en-us/microsoft-365/compliance/analyzing-data-in-review-set)
* Content Source: [microsoft-365/compliance/analyzing-data-in-review-set.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/analyzing-data-in-review-set.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@bvksphub  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@bvksphub - I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
