### ISSUE TITLE
Clarification on what blocks SMTP forwarding vs mailbox rule auto-forwarding

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/microsoft-365-docs#7506]
[Enter feedback here]

Can you please clarify this item? "Disabling automatic forwarding disables any Inbox rules (users) or mailbox forwarding (admins) that redirect messages to external addresses."  Does this apply to only to the outbound spam policy or also to mail flow rules as well?  I'm trying to understand how SMTP forwarding can be allowed while preventing mailbox rule forwarding.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding in Microsoft 365. - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Canis-Lupis Thank you for your feedback. One question we encounter frequently is, how all these techniques work together? What if auto-forward is blocked in one of the above methods but allowed in another? 

**Let’s say you have the following requirements:**

By default, automatic forwarding should be blocked.
Automatic forwarding to an external domain contoso.com should be allowed for all users.
Allow users Jack and Jill to also be able to forward to northwindtraders.com, but no one else.


**There are multiple methods to achieve this, the following is one such solution:**

Keep the new external forwarding control under Outbound spam filter policy setting to “On”.
Disable automatic forward for default * domain in remote domain setting.
Create a new remote domain for contoso.com and northwindtraders.com and allow automatic forward for these remote domains.
Create a transport rule to block auto forward from all to northwindtraders.com but put an exception for users Jack and Jill.
As transport rule will not block forwarding set using Outlook on the web (ForwardingSMTPAddress parameter) you can use RBAC rule to stop users from creating auto forward setting from OWA.

The Technet blog, here would be able to help you understand better -https://techcommunity.microsoft.com/t5/exchange-team-blog/all-you-need-to-know-about-automatic-email-forwarding-in/ba-p/2074888

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Canis-Lupis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
