### ISSUE TITLE
out of date page

### ISSUE THREAD

**Issue by joshfolcik** [MicrosoftDocs/microsoft-365-docs#7510]
This page is out of date from the very top at least. To get to the place to start this you have to go to security.microsoft.com not securitycenter.microsoft.com (it redirects you to security.microsoft.com today)
then go to settings -> endpoints -> then scroll way down to device management -> onboarding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a947a2-093c-0f4e-7053-c30112d1cee1
* Version Independent ID: 12fbc5ca-2b24-6717-ac98-331f0bba5278
* Content: [Set up the Microsoft Defender for Endpoint on macOS policies in Jamf Pro](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide#step-1-get-the-microsoft-defender-for-endpoint-onboarding-package)
* Content Source: [microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-jamfpro-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @joshfolcik Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
