### ISSUE TITLE
Partner, BDO, concern that https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mssp-list?view=o365-worldwide&WT.mc_id=email isn't working properly

### ISSUE THREAD

**Issue by morobinson** [MicrosoftDocs/microsoft-365-docs#7513]
[Enter feedback here]
Hello.  My partner, BDO, informed me that it looks as if this Microsoft webpage isn’t working consistently (mixed results on iPhone and Android phone browsers, too.  Was there an issue today with the site or is this a known problem?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56e74fd4-8ac5-98d6-1e56-a376d013756e
* Version Independent ID: e4ca4c88-c60e-5eac-1282-c0517a34a565
* Content: [Supported managed security service providers](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mssp-list?view=o365-worldwide&WT.mc_id=email)
* Content Source: [microsoft-365/security/defender-endpoint/mssp-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mssp-list.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@morobinson Thank you for your feedback. The website is working on the phone as well as the browser on desktops. This is not a known issue, Please provide us screenshots in case the issue persists.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @morobinson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
