### ISSUE TITLE
Enabling Network Protection via GPO - Must be forced, or GPO-setting enough?

### ISSUE THREAD

**Issue by jotheman0303** [MicrosoftDocs/microsoft-365-docs#7519]
The article states that to enable Network Protection via GPO you must set the "Prevent users and apps from accessing dangerous websites" to Enabled, but that you should "verify" Network Protection is enabled on the machine (by checking the registry setting). This makes it unclear what is required to enable Network Protection.
In a rollout we are using the new Unified/Preview rollout that does not enable Network Protection automatically during the onboarding. It looks like we need to force the GPO setting above _and_ force the registry setting to enable Network Protection. If that is indeed the case, please update the article to reflect this. Otherwise it might seem like Network Protection is enabled for admins, but in reality it is not.

Hope this helps to clarify!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 673970ca-2f79-a288-978c-ceb4845c5062
* Version Independent ID: 2a58449f-b0d4-bf17-1209-d7b8ec0481b6
* Content: [Turn on network protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-network-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks.

**Comment by denisebmsft** [comment]
Opened work item 5766834 to be assigned to a writer.

**Comment by denisebmsft** [comment]
Hello @jotheman0303 and @yogkumgit. Our writer updated the article and published the changes about a week ago. Please let us know if you still have any questions.
