### ISSUE TITLE
P1 vs P2 plan deployment

### ISSUE THREAD

**Issue by svinusje** [MicrosoftDocs/microsoft-365-docs#7520]
how is the difference made between a plan P1 and a P2 deployment. Assuming you want to use both plans in one tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f58c48-23a1-29e6-4358-7733b12668c8
* Version Independent ID: 27f7f229-ae73-3cd0-287f-8592aaa3928b
* Content: [Set up and configure Microsoft Defender for Endpoint Plan 1](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mde-p1-setup-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration.md)
* Product: **m365-security**
* Technology: **mdep1**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by lightupdifire** [comment]
Hello,
Same question from my side on this topic: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7414
We do have multiple licenses Plan 1 and Plan 2 and Defender Azure and now it is full mess, what is supported? how to stay license compliant? completely unclear :)

**Comment by denisebmsft** [comment]
Hello @lightupdifire @svinusje and thank you so much for posting this good question. Currently, whenever a customer has multiple subscriptions, the highest subscription takes precedence. 

For example, suppose that you're using Microsoft Defender for Business, and you start a trial or purchase Microsoft Defender for Endpoint Plan 2. Your tenant experience will now reflect Defender for Endpoint Plan 2, and you won't see the Defender for Business experience. It works the same way with Defender for Endpoint Plan 1. If you have licenses for Defender for Endpoint Plan 2, you'll see all the capabilities of Plan 2. 

That said, you're asking a very good question about how to stay license compliant, and I'll look into that.

**Comment by denisebmsft** [comment]
Hello again @lightupdifire @svinusje. I just wanted to let you know that our product team is working on this issue at priority.
