### ISSUE TITLE
AAD Portal

### ISSUE THREAD

**Issue by gvnshtn** [MicrosoftDocs/microsoft-365-docs#7521]
Under portals for other workloads it would be useful to have the aad.portal.azure.com for Azure Active Directory.
Have created an aka.ms link for this page: https://aka.ms/securityportals - please advise if ownership needs aligning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87804d7-c76b-509d-eaa0-18b91b0563bd
* Version Independent ID: 7dc288f3-939a-590b-fe8b-31a266795fa3
* Content: [Microsoft security portals and admin centers](https://docs.microsoft.com/en-us/microsoft-365/security/defender/portals?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/portals.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/portals.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@gvnshtn Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7580

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gvnshtn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
