### ISSUE TITLE
Apply Attack Surface Reduction (ASR) rules via MECM for Modern Unified Solution

### ISSUE THREAD

**Issue by Phildo76** [MicrosoftDocs/microsoft-365-docs#7522]
Query - WIll Attack Surface Reduction (ASR) rules by configurable via MECM for 2016 & 2012 R2 servers utilising the Modern Unified Solution? Or is ASRs just configurable Windows server 1803+ via MECM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Phildo76 Thank you for your feedback.  We have added it to the Known issues and limitations as not all Attack Surface Reduction rules are available on all operating systems.  The minimum Windows Server build is version is 1809 or later for ASR.

You can find more information here- https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#public-preview-supported-operating-systems

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Phildo76 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
