### ISSUE TITLE
Riduculous that there are no links to these products

### ISSUE THREAD

**Issue by techlogik** [MicrosoftDocs/microsoft-365-docs#7523]
As usual Microsoft has moved products to new locations and admin pages...but none of the docs have direct links to get to them. I know what the products do, I just need to get to them.  Endemic with MS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed2861d-860e-5d27-9259-fb9db2187f4b
* Version Independent ID: 09ef5622-3a7e-30f9-00f9-4c5578f8e1ca
* Content: [Configure spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@techlogik, I'm not sure I understand. The topic is full of general and direct links to the feature in the Microsoft 365 Defender portal:

In the "What do you need to know before you begin?" section:

> - You open the Microsoft 365 Defender portal at <https://security.microsoft.com>. To go directly to the **Anti-spam policies** page, use <https://security.microsoft.com/antispam>.

Step 1 of every procedure:

> 1. In the Microsoft 365 Defender portal at <https://security.microsoft.com>, go to **Email & Collaboration** \> **Policies & Rules** \> **Threat policies** \> **Anti-spam** in the **Policies** section. To go directly to the **Anti-spam policies** page, use <https://security.microsoft.com/antispam>.

**Comment by yogkumgit** [comment]
@techlogik Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
