### ISSUE TITLE
Create an Event without a Date

### ISSUE THREAD

**Issue by ashleyspurlin** [MicrosoftDocs/microsoft-365-docs#7525]
Detail on this page include the following: "Deleting an event doesn't cancel the retention settings that are now in effect for the content that's already labeled. To do that, create a new event with the same details, but leave the date blank."
In practice, there does not appear to be a way to create an event without specifying a date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad33cc1-dc5f-d9f9-ee8e-b103839945ef
* Version Independent ID: 1bc3101d-afe8-2056-3cda-6a86a209c460
* Content: [Start retention when an event occurs - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Investigating.  I confirm you can't do this in the UI (not sure about PowerShell) and not sure if this is a UX design issue or by design.  In the meantime, as an alternative, you could use search to find items with the relevant retention label and then remove/relabel the items.   I'll update when I hear from engineering.

**Comment by cabailey** [comment]
@ashleyspurlin  It seems PowerShell will let you create an event without a date .... but it doesn't work, even though we were previously told an event with no date was an official workaround (and the UI used to support this).  Engineering has accepted this as a future work item & in the meantime, I've updated the documentation to reflect our findings.

Thanks for flagging this!
