### ISSUE TITLE
Need updates to the Prepare Target Relationship

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/microsoft-365-docs#7530]
The section:
Prepare the target tenant by creating the Exchange Online migration endpoint and organization relationship

Step 3:
Running the Relationship script creates an error.
The command you tried to run isn't currently allowed in your organization. To run this command, you first need to run 
the command: Enable-OrganizationCustomization.

Attempting to runn the Enable-OrganizationCustomization command created a big error the first time.  I waited a little bit and then attempted again and it finished with no errors the second time.

Although, #3 powershell script is still creating errors listed above.

I read somewhere that I should wait approximately 1 hour before attempting any commands after customization is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Karr Thank you for your feedback. It ideally works right away after running the Enable-OrganizationCustomization. We have added this to Step2 so that users don't get stuck.

# Enable customization if tenant is dehydrated
  $dehydrated=Get-OrganizationConfig | fl isdehydrated
  if ($dehy -eq $true) {Enable-OrganizationCustomization}

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Karr Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
