### ISSUE TITLE
How do I know this worked - Fails

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/microsoft-365-docs#7531]
Alls steps performed and rechecked and recreated multiple times.  Nothing done finds the mailbox in the Test-MigrationServerAvailability.  No other errors with any parts or steps.  All GUID's and permissions double checked and verified.
This solution did not work.

Source Tenant was created by GoDaddy if that matters.
Destination Tenant was created by Microsoft (Non-Profit).

Thanks for trying.  Shame there is no help available as the steps were simple and easy to understand.

-Vladimir Nekic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Karr Thank you for your feedback. The steps outlined are for direct Microsoft tenant to tenant migration. I'd request you to work with the Microsoft support team(via the need help icon on the Admin center to convert the go daddy tenant to a Microsoft tenant(steps need to be done in the backend by Microsoft/go daddy support to de federate the go daddy tenant).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @Karr Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
