### ISSUE TITLE
MS Booking delete calendar incomplete

### ISSUE THREAD

**Issue by GuidanceImp** [MicrosoftDocs/microsoft-365-docs#7535]
When deleting the User Associated with the MS Bookings page this does not remove the Bookings Calendar from the system entirely.  My best guess is that the calendar will be removed from the system when the user is permanently removed from the "deleted users" hold.

This should be included in the notes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa612c0e-c089-8b3e-8e2e-dd12b6fc382c
* Version Independent ID: fa014ea6-7aa2-b2bd-d913-165c3241675f
* Content: [Delete a booking calendar](https://docs.microsoft.com/en-us/microsoft-365/bookings/delete-calendar?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/delete-calendar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/delete-calendar.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@GuidanceImp Thank you for your feedback. The Bookings calendar is a mailbox in Exchange Online so you delete the corresponding user account to delete the booking calendar. it is not required to hard delete the user from the deleted users container. 

If you have already deleted the user associated with the booking calendar and still see the booking calendar active, I'd suggest reaching out to Microsoft support via the need help section on the admin center to resolve the issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GuidanceImp Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
