### ISSUE TITLE
Dismiss reccomandations in Configuration Analyzer

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/microsoft-365-docs#7538]
I do not see any possibility to dismiss some recommendations that are not applicable to a certain organization or that may be duplicated in another policy rather than the default one. Is this planned?

Can we please mention in the docs that this is not available at the moment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbce796-0aec-3236-d505-607ae8371773
* Version Independent ID: 473cdc81-dc01-f7fd-d570-73e9a07cb972
* Content: [Configuration analyzer for security policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@teomonda, are you saying that we mention functionality in the article that isn't there? If not, I'm having a hard time wrapping my head around talking about features that are not available.

Please advise.

**Comment by teomonda** [comment]
I agree it does not make complete sense reading it that way. :)

From the usability perspective, I was comparing these recommendations to what we have in the Defender for endpoint recommendations, meaning being able to set an exception / accepted risk. Both me and the customers I was working with were looking for an option to "dismiss" a recommendation which does not seem to be there and I was after having a concrete confirmation of that, like a note saying it is not possible at the moment to do this, rather than busting my head in forums and chasing PM-s to find that out :).
I do get it if you feel that would be redundant.
Worth the shot :)

**Comment by chrisda** [comment]
@teomonda, interesting connection. I would recommend that you encourage the customers to open a support case about this. The argument that you can dismiss recommendations in other products in the Microsoft Defender is compelling.

Thanks for the feedback.

Closing
