### ISSUE TITLE
Dynamic delivery supportability status

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/microsoft-365-docs#7539]
In the portal Dynamic Delivery is still listed as PREVIEW whereas i do not see this marked in this article. Can you please highlight it here as well whether it is still in preview or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5966b7b-cbaa-eaa2-c9d6-5c6e7218df74
* Version Independent ID: cfcc8772-be5d-009a-0805-62624835ac5f
* Content: [Safe Attachments - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-attachments?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-attachments.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@teomonda, I know exactly what you are talking about, and I thought the same thing when I saw it.

In this topic:

<https://docs.microsoft.com/microsoft-365/security/office-365-security/set-up-safe-attachments-policies>

One of the selections for **Safe Attachments unknown malware response** is **Dynamic Delivery (Preview feature)**.

**(Preview feature)** is not supposed to mean Dynamic Delivery is in Preview; it's supposed to mean Dynamic Delivery is an attachment preview feature that delivers the attachments as stubs before they're scanned. I didn't review/approve that initial string text.

**Comment by yogkumgit** [comment]
@teomonda Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
