### ISSUE TITLE
Please add www.msftconnecttest.com/13.104.7.52 as 100% required

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#7542]
After a ~7-hour Severity A ticket with MS Support, we've come to find that www.msftconnecttest.com (13.107.4.52) is extremely critical for M365 Apps to be functional.

We found that this URL is not published nor is the IP, in any of the O365 URL/IP ranges publications.  I did find that this URL is mentioned in Windows 10/11 documentation:

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-21h2-endpoints#:~:text=www.msftconnecttest.com*

However, several sources have recently reported that IP address as being infected with a "WIPER" virus, and many firewalls in the wild now block connections to it.  This cause many people lots of trouble.

It would be best if this URL and that IP address were both listed in the O365 URLs and IP ranges.  Please add it, and please update this documentation as well.

There is no disputing the need for this, that connectivity is vital or M365 Apps will show "No internet connection" under File > Account (or File > Office Account in Outlook).  When the problem is in effect, Outlook won't let the primary account be connected to its Exchange server, even if that server is Exchange on-premises.

Needs to be published here, please and thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by JeremyTBradshaw** [comment]
[Case #:29468771] - Office activation connectivity issue

^^ for reference.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out, @JeremyTBradshaw. I'll discuss this with the folks responsible for the endpoints web service and get back to you with an update.

**Comment by kelleyvice-msft** [comment]
@JeremyTBradshaw - The key issue is that Network Connection Status Indicator is a Windows feature, not an Office 365 feature. While there are certainly non-O365 endpoints that are critical to its function, we can only include O365-specific endpoints in the web service. This is partly because there are so many factors outside the scope of O365 services that can affect functionality, there is no way to maintain documentation for all of them. Sorry, I know this isn't the answer you were hoping for. I'll close this issue, but you can still comment if needed.
- Kelley

**Comment by JeremyTBradshaw** [comment]
@kelleyvice-msft you have made fair points in your explanation.  In the end, I cannot dispute that logic and agree it would set an unmaintainable precedent if you went ahead and made an exception for this.

Maybe I will put in a PR that puts a purple note stating to be mindful of other network dependencies, and I could refer to Windows 10/11 endpoints Docs.

That seems like a fair middle ground since Windows 10/11 could be considered part of M365.  Agree?

**Comment by JeremyTBradshaw** [comment]
@kelleyvice-msft Except that page is not editable by non-Microsoft people....
