### ISSUE TITLE
"bulk" should not have changed "by default" to Quarantine

### ISSUE THREAD

**Issue by thavidu** [MicrosoftDocs/microsoft-365-docs#7546]
While I'm sure this change was well intentioned, its causing real problems for real businesses-- I had no idea my mail settings had changed and that this quarantine area even existed, have been using this Exchange 365 for 9+ years now. 
I only found out after calling up the support line at Brex because I could not get any verification emails from them (literally all their emails were landing in this new quarantine area under the "Bulk" rule which is way too aggressive). Theres NO reason why *bulk* messages should have been *by default* changed to Quarantine instead of the Junk Mail folder-- thats the whole point of the Junk Mail folder! Not only did I find Brex's emails, but several newsletters and  verification emails from some other sites I tried to signup/login to were already in there.
I am assuming you guys only intended to 'by default' protect against actual malicious content (phishing, malware etc) but "spam" is not malicious- theres no reason to not let it go to the junk mail folders....
This is absolutely ridiculous guys- I doubt i'm the only one affected, many others probably don't even know (I mean I only found out two months later since it seems this change happened in November..)

Note: I'm posting this under the 'page' feedback because the 'product' feedback link at the bottom of the page is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472b3a0c-7ad8-8245-9b57-29431490370b
* Version Independent ID: 8671f04a-b7b3-402c-1e65-59a52c1cdaf5
* Content: [Secure by default in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-by-default?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/secure-by-default.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-by-default.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@thavidu Thank you for your feedback. The product feedback link on the document will be fixed soon. In the meantime to make sure that your feedback gets routed to the appropriate team, please post it on the [Microsoft 365 Q&A portal](https://docs.microsoft.com/en-us/answers/products/m365).

Thanks
Sri

**Comment by FluidNets-DamianS** [comment]
Guys, what is the status of this.  Not only is my company domain affected by this, but I have mass clients with this as well.  I can understand actual bulk email "email with more than x recipients" being flagged as bulk.  However, this new algorithm now defaults "bulk" when a user sends a single email to another email.   a single email should never be flagged as "bulk".  Bulk should never be applied below 15 recipients.
