### ISSUE TITLE
If successful, the detection test will be marked as completed

### ISSUE THREAD

**Issue by rajmandalia** [MicrosoftDocs/microsoft-365-docs#7547]
the document states that "If successful, the detection test will be marked as completed". Where will I see it marked completed?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d716f82-0a0f-49b8-587e-589d166e602e
* Version Independent ID: 2c91a5fb-0567-f267-29f9-4f2660742f6a
* Content: [Run a detection test on a device to verify it has been properly onboarded to Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-detection-test?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-detection-test.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-detection-test.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@rajmandalia Thank you for your feedback. I was able to test and do not see it getting marked as completed. However, If successful, a new alert does appear in a few minutes. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7589

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rajmandalia Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
