### ISSUE TITLE
Azure AD Connect change results in Server 2012 R2 being marked as cloudfiltered=TRUE

### ISSUE THREAD

**Issue by dogborne** [MicrosoftDocs/microsoft-365-docs#7550]
I'm testing the change to the Azure AD Connect Inbound sync rule (Inbound from AD). I have copied the rule and the server is in scope for synchronisation. The cloudfiltered property is set to TRUE however meaning that the object does not sync to Azure AD. 
I'm not sure how to modify the rule further to enable to Server object to sync to AAD. Would you be able to validate that this is the correct setting? 
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d5a4a3-77a5-a7bc-61f8-e0c1e1a47e7e
* Version Independent ID: 16d5a4a3-77a5-a7bc-61f8-e0c1e1a47e7e
* Content: [Troubleshoot onboarding issues related to Security Management for Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-security-config-mgt?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-security-config-mgt.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-security-config-mgt.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Please contact support for assistance.
