### ISSUE TITLE
How retention works with OneNote content - Modified date OneNote file

### ISSUE THREAD

**Issue by LaPhi** [MicrosoftDocs/microsoft-365-docs#7552]
_
**How retention works with OneNote content**
When you apply a retention policy to a location that includes OneNote content, or a retention label to a OneNote folder, behind the scenes, the different OneNote sections are individual files that inherit the retention settings. This means that each section will be individually retained and deleted, according to the retention settings you specify._

It should be highlighted that the modified date never changes of the OneNote File (In SPO/ODFB) itself because it is used as folder for the individual OneNote sections. 
I had multiple questions from CXs about this behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft 365 Compliance](https://review.docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?branch=main&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@LaPhi  Thanks for the tip, now added.  Please note, because you are a Microsoft employee, feel free to ping me direct with customer feedback for the docs.

**Comment by Kory13** [comment]
I am looking for information on OneNote files (pages in the Notebook) that have been deleted during a retention sweep. 
Specifically, how to restore a deleted page and hopefully how to be notified that it has been deleted.

**Comment by cabailey** [comment]
@Kory13  Deletion with Microsoft 365 retention is a permanent delete for compliance, so can't be restored.  To prevent this happening in the future, I recommend supplementing your retention policy with retention labels that have a longer retention period and trigger a disposition review so they won't be permanently deleted without human review. You can learn more about disposition review here: https://learn.microsoft.com/microsoft-365/compliance/disposition

**Comment by itguysocal** [comment]
@cabailey I do not think retention labels can be applied to OneNote files https://learn.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#compare-capabilities-for-retention-policies-and-retention-labels

**Comment by cabailey** [comment]
@itguysocal Why did you conclude that from the comparison table?  OneNote uses SharePoint (why it's included on this page), which has Yes for retention labels. Although you can't manually apply retention labels to OneNote files, you can apply them to OneNote folders, and the label gets inherited by all files in that folder in the same way as label inheritance works with a folder in a standard SharePoint site.

**Comment by itguysocal** [comment]
> @itguysocal Why did you conclude that from the comparison table? 
Sorry about that, please disregard my comment. I was confused but now it makes sense to me.
