### ISSUE TITLE
Please add phone numbers to billing support from third world countries like Nepal as well. 

### ISSUE THREAD

**Issue by Geeksagar** [MicrosoftDocs/microsoft-365-docs#7554]
We need Educational tools like Microsoft 365 A1 more than anywhere in world. Please help schools in Nepal by adding support via calls. Lot of educational institutions are struggling to get support. We're not getting verified as School since 3 months and our classes are paused because of this. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00cb5342-0ced-ff9b-6fe4-9027decae429
* Version Independent ID: 3ff474de-a07d-bd6c-3621-96674a40b9ec
* Content: [Support information for Nepal - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/nepal?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/nepal.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/nepal.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Geeksagar Thank you for your feedback. Very sorry to hear about the situation. For Nepal currently, Telephone support is not available and only online support is available

We do not have access to set up phone numbers, however, I recommend you leave feedback on our main portal which is https://feedbackportal.microsoft.com, so someone can look into this request.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Geeksagar Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
