### ISSUE TITLE
Modify proxy setting example with 'do not use' warning

### ISSUE THREAD

**Issue by ghexp** [MicrosoftDocs/microsoft-365-docs#7558]
Proxy setting `"proxy": "http://proxy.server:port/"` example jsons (Sample and Full profile) should also include `<EXAMPLE DO NOT USE>` like "allowedThreats" 

as `"proxy": "<EXAMPLE DO NOT USE> http://proxy.server:port/" `warning to avoid naive copy-paste. 

Running mdatp with "http://proxy.server:port/" will 'work' but will fail to update definitions by attempting to use http://canonicalizer.ucsuri.tcs:80

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ef0d15-6735-bb94-0d86-d57ffbaa05f7
* Version Independent ID: 52e516b5-b365-4950-334a-c4797333093d
* Content: [Set preferences for Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-preferences?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-preferences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-preferences.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ghexp Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7597

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ghexp Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
