### ISSUE TITLE
Link doesnt lead anywhere

### ISSUE THREAD

**Issue by FrankGlez** [MicrosoftDocs/microsoft-365-docs#7560]
The link 
aka.ms/SecureO365M365
does not lead to any relevant resources or information, it simply redirects to Bing.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c378129-a842-aa6b-c348-c43b52dbc018
* Version Independent ID: 055ab120-9a74-0cad-0414-a504f71e62dc
* Content: [Security guide for small businesses - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-guide?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-guide.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-guide.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by yogkumgit** [comment]
@SKjerland Please help us in resolving this issue. Thanks

**Comment by SKjerland** [comment]
@FrankGlez - I can't find this link anywhere. It may have been removed by someone else. I'm going to close this issue, but if I somehow missed the link and the problem still exists, please re-open the issue and provide additional information to help us locate the link. Thanks!
