### ISSUE TITLE
ZAP reporting - non-existent other than one single spot which shows high level tally

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#7561]
I'm calling out that this FAQ entry is false:

> ## How to see if ZAP moved your message
> To determine if ZAP moved your message, you can use either the Threat Protection Status report or Threat Explorer (and real-time detections). Note that as a system action, ZAP is not logged in the Exchange mailbox audit logs.

Neither suggested place actually helps to find anything about ZAP.  In the Threat Protection Status report, the closest thing you will find about ZAP is the presence of the "ZAP not enabled" which is one of the "Detection Technology"'s.  It's pretty much always 0 and nowhere in the world has anyone explained what "ZAP not enabled" is supposed mean in that context.  In Threat Explorer - no comment - but in Real-Time Detections - you cannot see anything about ZAP at all.  In the referenced article, all the mentions of "ZAP" are in the section titled "Improvements to the threat hunting experience (upcoming)" where "upcoming" has no date or ETA.

Meanwhile in the Mailflow Status report, from https://security.microsoft.com under Reports > Email & Collaboration, if we switch that report to the "Mailflow" view, we can see a tally of how many "ZAP removed"'s there were.  No details about what messages or which mailboxes, no nothing.

So I'm a little confused where anyone is getting any info about ZAP.  It appears to be a complete hype feature, with no credibility.  It hasn't moved a single message in a large organization that has it enabled org-wide.  Is there any detail that can be added to this article which would make reviewing and/or reporting on ZAP an easier or even just possible at all beyond what I mentioned is available in the Mailflow status report?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb415a2-fc7c-5b9a-96de-f01be631bf07
* Version Independent ID: c5d4ab93-4f59-a60f-5d42-1a6a52a37f4c
* Content: [Zero-hour auto purge in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/zero-hour-auto-purge?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/zero-hour-auto-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/zero-hour-auto-purge.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Reference to TPS report removed and replaced by Mailflow status report in Issue #7556.

**Comment by chrisda** [comment]
@JeremyTBradshaw, I clarified the description in the ZAP topic:

> To determine if ZAP moved your message, you have the following options:
>
> - **Number of messages**: Use the [Mailflow view in the Mailflow status report](view-email-security-reports.md#mailflow-view-for-the-mailflow-status-report) to see the number of ZAP-affected messages for the specified date range.
> - **Message details**: Use [Threat Explorer (and real-time detections)](threat-explorer.md) to filter **All email** events by the value **ZAP** for the **Additional action** column.

OK?

**Comment by JeremyTBradshaw** [comment]
Hi @chrisda , thank you and yes that looks great to me.  Concise and accurate.  Much appreciated.

**Comment by chrisda** [comment]
Cool. Thanks. Closing.
