### ISSUE TITLE
Windows 10/11 Connection Endpoints

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#7562]
I would do a pull request but those seem to be disabled for this page.  Please add a row to the table for:

www.mstfconnecttest.com / 13.107.4.52 - Used by Windows 10 and 11 to determine if the computer is connected to the internet.  When this URL cannot be reached, Windows will deem itself "Not connected to the Internet" and M365 Apps for Enterprise will not try to verify activation status, instead will show "No internet connection" and begin reducing available features, prevent connections to Exchange, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Other endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by JeremyTBradshaw** [comment]
Referenceable links:

https://docs.microsoft.com/en-us/windows/privacy/manage-windows-11-endpoints
https://docs.microsoft.com/en-us/windows/privacy/manage-windows-21h2-endpoints

**Comment by kelleyvice-msft** [comment]
Thanks, @JeremyTBradshaw. I will check with the product group, but I don't think that will be a problem.

**Comment by kelleyvice-msft** [comment]
I've added a row as requested. Revisions should be live this afternoon. Thanks!

**Comment by JeremyTBradshaw** [comment]
@kelleyvice-msft thanks, I see the addition and appreciate the quick help you have me here and on the other page.
