### ISSUE TITLE
No error discription for: Unable to start Microsoft Defender for Endpoint Service. Error message: The service name is invalid

### ISSUE THREAD

**Issue by arethk** [MicrosoftDocs/microsoft-365-docs#7565]
There is no error description for the error: "Unable to start Microsoft Defender for Endpoint Service. Error message: The service name is invalid" on this link https://go.microsoft.com/fwlink/p/?linkid=822807

Full error from command line:
[Error Id: 15, Error Level: 1] Unable to start Microsoft Defender for Endpoint Service. Error message: The service name is invalid.
For more information, visit: https://go.microsoft.com/fwlink/p/?linkid=822807

When I run "sc query sense":
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.

This is really terrible guys. No info about this error on the web. I'm on Windows 10 and I'm trying to onboard via a local script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7326a1bb-dad2-0770-5df2-fb79d960cce0
* Version Independent ID: 44412965-a543-3e52-bfea-acf535d49ce5
* Content: [Troubleshoot Microsoft Defender for Endpoint onboarding issues](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-onboarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-onboarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-onboarding.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by arethk** [comment]
My system info:

Processor	Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz   2.20 GHz
Installed RAM	8.00 GB (7.90 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display


Edition	Windows 10 Home
Version	21H2
Installed on	‎6/‎17/‎2020
OS build	19044.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by arethk** [comment]
My fault guys, I didn't have Windows Pro isntalled. I found this link https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide

It would be nice if you added to that table a link to that min requirment page. Thanks.

**Comment by msbemba** [comment]
@arethk Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7598

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @arethk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by o-l-a-v** [comment]
Sharing this as it might help others.

I got same error, 15, saying the service does not exist.

I though running the ```WindowsDefenderATPLocalOnboardingScript.cmd``` file from a directory where also ```md4ws.msi``` was located, but that's not sufficient. The CMD does not install ```md4ws.msi```, nor does it handle dependencies like the two KBs needed (KB2999226, KB3080149).

Then found this script:

* https://github.com/microsoft/mdefordownlevelserver/blob/main/Install.ps1

Added it to the same directory, and ran it from PowerShell ISE like admin like so:

* First set location to the directory where the onboarding files are located.
  * ```Set-Location -Path ([System.IO.Directory]::GetParent($psISE.CurrentFile.FullPath).FullName)```
* Then start the install.ps1 script.
  * ```& $psISE.CurrentFile.FullPath -OnboardingScript '.\WindowsDefenderATPLocalOnboardingScript.cmd'```

Then it worked.

Summary: The CMD script does not automagically do everything. :)

**Comment by undixgalore** [comment]
I can confirm that using the script mentioned in o-l-a-v's post worked on a troublesome Windows Server 2016. I placed md4ws.msi and WindowsDefenderATPOnboardingScript.cmd in the same folder as Install.ps1, and successfully ran the following in an admin-PowerShell window:

`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12`
`.\Install.ps1 -OnboardingScript .\WindowsDefenderATPOnboardingScript.cmd`

**Comment by yowl** [comment]
would be nice if the script told you that windows home was not supported.

**Comment by audiocrush** [comment]
> would be nice if the script told you that windows home was not supported.

don't use windows home professionally
if anything goes wrong no one will forgive you or feel sympathy with you for your mistake.
Using windows home for anything serious is as bad as mistaking redundant hard drives for a backup.

**Comment by ntwrite** [comment]
I am having the same problem - still unclear on what is required here. Why is the ATP deployment for every OS, even Windows so bugged and terrible?
