### ISSUE TITLE
Safe Links on URIs

### ISSUE THREAD

**Issue by jamesn-jisc** [MicrosoftDocs/microsoft-365-docs#7566]
We have a number of users who receive emails that reference SAML entityIDs. entityIDs usually take the form of a secure URI but almost always need to be treated as a string.

These are not links to be followed, and they are not access URLs. They are entityIDs, and entityIDs are identifier strings that must not be altered during communication. Our concern is that most entityIDs have the same format as a URL, so are going to be picked up by any tool that checks links. If Safe Links alters them it will cause problems for anyone dealing with SAML connections. 

In the past when looking to implement a different URL checker, it altered entityIDs to an extent that made them unreadable and the protection had to turned off.

With this is mind can I ask:

- Assuming that Safe Links will alter links and things that look like them, what form will that alteration take?
- What will Safe Links do if the entityID it thinks is a link doesn't have anything reachable at the other end?

Many thanks,
Nick

**Comment by msbemba** [comment]
@jamesn-jisc Thank you for your feedback. Each Safe Links policy contains a Do not rewrite the following URLs list that you can use to specify URLs that are not rewritten by Safe Links scanning. Having said that,  If Safe Links scanning is unable to complete(Like the entity id, where the link doesn't have anything reachable at the other end), Safe Links protection does not trigger. In-Office desktop clients, the user will be warned before they proceed to the destination website but nothing is changed in the Link.

If you still have more questions about this, I'd recommend you open a support ticket and one of our Microsoft support engineers can help you out.


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jamesn-jisc Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
