### ISSUE TITLE
Albania org number is called VAT number

### ISSUE THREAD

**Issue by albgen** [MicrosoftDocs/microsoft-365-docs#7569]
[Enter feedback here]
Albania org number is called VAT number

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e2ac78-e08b-d7c8-5eec-baf9e9c13b62
* Version Independent ID: 66014f69-00c9-0e9b-fe0a-d0e10f2ca5eb
* Content: [About registration numbers and under review notifications](https://docs.microsoft.com/en-us/microsoft-365/commerce/about-registration-numbers?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/about-registration-numbers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/about-registration-numbers.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Please help us in resolving this issue. Thanks

**Comment by cmcatee-MSFT** [comment]
Specific country information was removed and replaced with a link to https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/
