### ISSUE TITLE
addition to powershell script for deployment of VM's

### ISSUE THREAD

**Issue by wloeven** [MicrosoftDocs/microsoft-365-docs#757]
The Standard_A1 VM no longer exists in Azure please edit the powershell script with the correct VM size or selection in script with active available VM sizes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6989d21-f7a7-043b-c91a-cd019a19c0e6
* Version Independent ID: 39e286bc-58fe-768e-ee65-2a2fedf1e544
* Content: [Simulated enterprise base configuration for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise#feedback)
* Content Source: [microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by wloeven** [comment]
Correction it still exists but doesn't deploy in west europe with a sponsorship subscription.

**Comment by JoeDavies-MSFT** [comment]
@wloeven I updated the commands for the Standard_A2_V2 VM size. Thanks so much for letting us know.
