### ISSUE TITLE
Typo - wrong product

### ISSUE THREAD

**Issue by uowdaniel** [MicrosoftDocs/microsoft-365-docs#7575]
In this para:

> Microsoft 365 Defender safeguards your organization against malicious threats posed by email messages, links (URLs), and collaboration tools. It shares signals resulting from these activities with Microsoft 365 Defender. Exchange Online Protection (EOP) is integrated to provide end-to-end protection for incoming emails and attachments.

I believe the first sentence should actually read "Microsoft Defender for Office 365 safeguards your organization against malicious threats posed by email messages..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9afb9bd-0d73-62ef-a10b-2942f16370c2
* Version Independent ID: ce228ca6-001d-24a0-7c5f-3ef183050c83
* Content: [Evaluate and pilot Microsoft 365 Defender, an XDR](https://docs.microsoft.com/en-us/microsoft-365/security/defender/eval-overview?ocid=cx-evalpilot&view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/eval-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/eval-overview.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@uowdaniel Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7599

Once the author approves, the changes will be live.

thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @uowdaniel Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
