### ISSUE TITLE
Threat Analytics?

### ISSUE THREAD

**Issue by mbigus** [MicrosoftDocs/microsoft-365-docs#7579]
The comparison chart for Plan 2 here doesn't show Threat Analytics as part of anything listed.
This: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/threat-analytics?view=o365-worldwide says threat analytics is part of plan 2.

I have to say - you need some sort of visual or master layout to more easily explain these products and sub/product fetaures. I have spent 2 days - trying to understand features rather than configuring the product - between product name changes - portal moves - and having to look thru multiple docs - it's extremely confusing for something that should be simple. A graphic or something that shows all features available in plan 1 vs 2 would be helpful. And, I know this exists - the problem is then you find stuff like Threat Analytics in the docs that isn't included. Or different categorizations, like parts and pieces under "Cloud Delivered Protection" - which then includes some things in plan 1 or plan2. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec57328d-4b17-abe6-001e-c5ecb2f00746
* Version Independent ID: be98599a-b690-a3e6-c610-8da71fd80d76
* Content: [Compare Microsoft Defender for Endpoint Plan 1 to Plan 2](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md)
* Product: **m365-security**
* Technology: **mdep1**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mbigus Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
