### ISSUE TITLE
This documentation requires powershell to be added

### ISSUE THREAD

**Issue by JohnGGeo** [MicrosoftDocs/microsoft-365-docs#758]
This is related to #632.
We still don't have the powershell cmdlet to turn off self-purchasing.
Please update the document to include this.

**Comment by JohnGGeo** [comment]
https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq

**Comment by cmcatee-MSFT** [comment]
@JohnGGeo The PowerShell module was released yesterday. The link is available here: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell)
