### ISSUE TITLE
404 Error when clicked on the poster 

### ISSUE THREAD

**Issue by andreyshihov** [MicrosoftDocs/microsoft-365-docs#7585]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f236aabf-0e00-b921-b97a-e8a0ff46a2fd
* Version Independent ID: 91933073-7e46-5a1d-23fa-7864effb6a12
* Content: [Set up your infrastructure for hybrid work with Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/solutions/empower-people-to-work-remotely?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/empower-people-to-work-remotely.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/empower-people-to-work-remotely.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
Resolved/

**Comment by yogkumgit** [comment]
@andreyshihov Thank you very much for the feedback. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by alrdwa** [comment]
Great
