### ISSUE TITLE
Correct/update the share permissions required for Defender's intelligence updates

### ISSUE THREAD

**Issue by NTPanaccio** [MicrosoftDocs/microsoft-365-docs#7592]
Can Microsoft update the share permissions required for the intelligence updates share? It only mentioned "Everyone" having read access, but "Domain Computers" definitely needs to have access to that share or it will never actually pull the updates into the image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87fa68a-a881-7ab7-97df-5da73dc56692
* Version Independent ID: 0c031441-cc26-903a-4d53-c044ea790d2d
* Content: [Microsoft Defender Antivirus Virtual Desktop Infrastructure deployment guide](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Hello @NTPanaccio, and thank you so much for posting your question here. I checked with our product team, and they are indicating that the content is correct as it is. Did you run into an issue with domain controllers not having the correct permissions? If so, let me know, and I will communicate that back to them. But they have tested the procedures this week on site with a customer and it worked as expected. I hope this helps! Thank you again for your question.
