### ISSUE TITLE
Create safe sender lists - Office 365 Recommendations and Explanations are Incorrect

### ISSUE THREAD

**Issue by DSDrewry** [MicrosoftDocs/microsoft-365-docs#7595]
The recommendations order and explanations for IP Allow List and Allowed Senders List/Allowed Domains List are reversed.  IP Allow List aka Connection Filter bypasses everything, including malware and phishing scanning.  Allowed Senders List/Allowed Domains List does not bypass malware or phishing scanning.  Please fix this page.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DSDrewry, this topic and the order it describes is several years old. The intent of the order of recommended solutions isn't about functionality or power; it's about our recommended methods for blocking messages based all criteria, like "safety" and reducing the number of false positives and false negatives.

I'm seeking clarification if the order should be changed. Also, I didn't think it was possible to bypass malware filtering due to the potential dangers to the entire service.

**Comment by DSDrewry** [comment]
@chrisda Thank you for your quick reply.  Not to sound preachy, but as a Microsoft Partner we leverage content such as this as the basis for our work as well as the guidance we provide to our customers. I had a customer question me on this article just yesterday, and I had to assure them the content required an update.  There's a very recent review date at the top, so we must take this as the latest and most accurate information.  The recommendations are ordered, and in the explanations for each, the content is incorrect regarding what functionality is included or bypassed.  You may be right that connection filtering no longer bypasses malware scans - I have heard that within the past year as well.  I'm looking forward to the updated content!  Thanks again.

**Comment by chrisda** [comment]
@DSDrewry, I received no indication that the recommended order of safe list options should be changed.

The topic currently mentions in 4 different places that malware and high confidence spam messages are no longer skipped. It was suggested that I add a link to the [Secure by default in Office 365](https://docs.microsoft.com/microsoft-365/security/office-365-security/secure-by-default), which I did, but the following explanations are already present:

Intro section:

> [!IMPORTANT]
>
> - Messages that are identified as malware or high confidence phishing are always quarantined, regardless of the safe sender list option that you use. For more information, see [Secure by default in Office 365](secure-by-default.md).

Use Outlook Safe Senders section:

> [!CAUTION]
> This method creates a high risk of attackers successfully delivering email to the Inbox that would otherwise be filtered; however, the user's Safe Senders or Safe Domains lists don't prevent malware or high confidence phishing messages from being filtered.

Use the IP Allow List

> [!CAUTION]
> Without additional verification like mail flow rules, email from sources in the IP Allow List skips spam filtering and sender authentication (SPF, DKIM, DMARC) checks. This creates a high risk of attackers successfully delivering email to the Inbox that would otherwise be filtered; however, the IP Allow List doesn't prevent malware or high confidence phishing messages from being filtered.

Use allowed sender lists or allowed domain lists section:

> [!CAUTION]
>
> - This method creates a high risk of attackers successfully delivering email to the Inbox that would otherwise be filtered; however, the allowed senders or allowed domains lists don't prevent malware or high confidence phishing messages from being filtered.

So, is there anything else that needs to be done?

**Comment by DSDrewry** [comment]
The specific page in question is:
Create safe sender lists - Office 365 | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide>

This page mentions the specific item:
The available safe sender lists are described in the following list in order from most recommended to least recommended:

Mail flow rules
Outlook Safe Senders
IP Allow List (connection filtering)
Allowed sender lists or allowed domain lists (anti-spam policies)

IP Allow List should be the least recommended method instead of allowed sender lists/allowed domain lists.

Attached is a screen clip of Microsoft Ignite content referencing the EOP pipeline, showing use of an IP allow list bypasses all other email hygiene steps, so it's the least recommended.  This has been the understanding of Exchange Admins for quite some time.

If the EOP pipeline has changed, please let me know.

Thanks

Doug

**Comment by chrisda** [comment]
@DSDrewry, how recent was that Ignite information? Secure by Default was implemented within the last year (and it could have been a rolling release) so that nothing bypasses high confidence phishing and malware anymore. I thought that anti-malware could not be bypassed under any circumstances, but I won't swear up and down to that.

I'll ask about swapping connection filtering with anti-spam filtering.

**Comment by chrisda** [comment]
Malware (including detections from Safe Attachments in Defender for Office 365) and high confidence phishing can't be bypassed. Ever. It's a 'health of the service' thing. Those messages are always quarantined.

Closing this issue as the recommended method now (as clearly stated in that article) is Allow entries in the [Tenant Allow/Block List](https://learn.microsoft.com/microsoft-365/security/office-365-security/tenant-allow-block-list-about).

Thanks for the feedback.
