### ISSUE TITLE
Dead link to https://blogs.office.com/2015/04/21/enhancing-transparency-and-control-for-office-365-customers/

### ISSUE THREAD

**Issue by stanalek** [MicrosoftDocs/microsoft-365-docs#7601]
The text 
 Enhancing transparency and control for Office 365 customers for the original announcement.)
contains a dead link:

https://blogs.office.com/2015/04/21/enhancing-transparency-and-control-for-office-365-customers/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2f2581-292d-a72b-0683-897eaac0adb0
* Version Independent ID: d10014a1-164d-1aea-635f-8c63da26b44c
* Content: [Service Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-service-encryption?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/office-365-service-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-service-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@stanalek Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7637

The correct link is https://www.microsoft.com/en-us/microsoft-365/blog/2015/04/21/enhancing-transparency-and-control-for-office-365-customers/
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @stanalek Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by vishnookumar** [comment]
> 

@msbemba This link is redirecting again. Could you please check?

**Comment by msbemba** [comment]
@vishnookumar  Looks like the link is not active anymore. We will check with the author to find if there is a replacement link.

**Comment by KCCross** [comment]
Fixed in the private repo.
