### ISSUE TITLE
Add-on stated is not on the list

### ISSUE THREAD

**Issue by ryeborja** [MicrosoftDocs/microsoft-365-docs#7604]
[Enter feedback here]
To add/increase the Sharepoint Storage of a Business Standard subscription, the organization must purchase "Office 365 Extra File Storage" as stated in this page. However, the option/item seems to be missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add more SharePoint storage to your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide#buy-the-extra-storage-add-on)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@ryeborja Thank you for your feedback. I'm able to locate the extra file storage add-on under products-->add-ons.
![image](https://user-images.githubusercontent.com/45987684/152778483-4bc3b8d5-ccf7-4d1f-b13a-2780e8fe2955.png)

Please note that this option is only available for customers who directly purchase licenses from Microsoft. If you are purchasing licenses from a CSP partner, you need to contact them for the add-on.

If you are purchasing this from Microsoft directly and still do not see the option, I'd recommend you to contact support via the need help icon on the admin center.

Hope this helps!
Thanks
Sri
