### ISSUE TITLE
Regarding "Application installation" Title

### ISSUE THREAD

**Issue by tfunatani** [MicrosoftDocs/microsoft-365-docs#7605]
[Enter feedback here]
Supportable version of Mac OS is 10.15 or higher on MDE, so I believe that "Regarding "Application installation" Title () should be changed as following.

**Before**: Application installation (macOS 10.15 and older versions)
**After**: Application installation (macOS 10.15)

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-manually?view=o365-worldwide#application-installation-macos-1015-and-older-versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f274b95e-a8b5-711b-7d7c-435510bfa22b
* Version Independent ID: b0374203-6177-686d-9814-e1192c6ec1cf
* Content: [Manual deployment for Microsoft Defender for Endpoint on macOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-manually?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-manually.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@tfunatani Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7638

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tfunatani Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
