### ISSUE TITLE
Legacy URL confirmation

### ISSUE THREAD

**Issue by hittensa** [MicrosoftDocs/microsoft-365-docs#7607]
The article highlights that there is a "requirement" to configure the following URL's on your firewall:

**ID39**
%tenant%-files.sharepoint.com   Port 80,443
%tenant%-myfiles.sharepoint.com  Port 80,443

When testing these URL's on any existing or newly provisioned tenancy they don't seem to exist. Therefore on some firewalls it's not possible to create an object that matches this URL, associated IP's and ports.

Please can Microsoft confirm if these URL's are still required? And if they are required what is their purpose. The only corresponding information I have found is their relation to the old "Open with Explorer" view done through Internet Explorer in a SharePoint document library.

Thank you.

**Comment by yogkumgit** [comment]
@hittensa Please indicate which document you are referring to. Thanks

**Comment by hittensa** [comment]
https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by hittensa** [comment]
Hi, I'm sorry I'm not sure what you need from me, could you be more specific.

Are you indicating that you've flagged the articles documentation to be updated and that there's nothing further that can be done in this thread?

**Comment by yogkumgit** [comment]
@hittensa your question is forwarded to Author of this document. No action on you. Thanks
