### ISSUE TITLE
P1 vs P2

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/microsoft-365-docs#7609]
It's not clear hear (or any other docs I've looked at) if Defender for Endpoint is needed to be at Plan 1 or Plan 2 to use the non-Windows features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e914c02a-e905-fc32-439c-feb1fafa09b8
* Version Independent ID: 1a6a15e9-717a-33c1-b90e-96925c680228
* Content: [Microsoft Defender for Endpoint for non-Windows platforms](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/non-windows?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/non-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/non-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@thommck Thank you for your feedback. 
Support for Windows (client and server) and non-Windows platforms (macOS, iOS, Android, and Linux) is available only on Defender for Endpoint Plan 2


You can find the comparison here -https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide#compare-defender-for-endpoint-plans and also in the document where we mention the applies to section

![image](https://user-images.githubusercontent.com/45987684/152780008-cd04709f-03b2-4d76-bd01-f9ca83ff7b8d.png)

Hope this helps!

Thanks
Sri

**Comment by thommck** [comment]
That link you shared says Plan 1 does support mobile.
The root reason I need this info is that we have frontline workers with
M365 F3 subscriptions. They will either use a shared android device (for
warehouse operations) or a shared windows desktop PC. I want to protect
those devices with Defender for endpoint  but it's not clear what features
in would require for those frontline worker use cases

Thanks,
Thom

**Comment by msbemba** [comment]
@thommck Thank you for your response. Since the comparison table mentions IOS and android, It sure does support it. I will make changes to https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/non-windows?view=o365-worldwide and include what Plan 1/2 supports .

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @thommck Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
