### ISSUE TITLE
Does this information refer to built-in labels or all labels

### ISSUE THREAD

**Issue by GladysRodriguez** [MicrosoftDocs/microsoft-365-docs#761]
When I read this article, it seems that it is saying that sensitive labels are only available on the versions of the OS specified.  Is this article supposed to be specifying that Built-in labels (no AIP client required) is available for those OS versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Sensitivity labels in Office apps](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#what-sensitivity-label-capabilities-are-supported-in-office-today)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@GladysRodriguez  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by KCCross** [comment]
I've sent this question over to the PMs for clarification.

**Comment by samschan-ms** [comment]
Yes, these are the minimum application version in order to utilize sensitivity labels in the app natively.  These apps work with sensitivity labels, and not the AIP labels.

**Comment by mypil** [comment]
@GladysRodriguez - From our understanding, the issue you raised has been answered by samschan-ms. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
