### ISSUE TITLE
0

### ISSUE THREAD

**Issue by xehoa13** [MicrosoftDocs/microsoft-365-docs#7612]
[Nhập phản hồi vào đây]

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 3642a091-493e-3807-7eaa-6a4c533ee49f
* Version Independent ID: 2e514a6e-2ae1-ccea-f566-324cf81dab52
* Content: [Enable block at first sight to detect malware in seconds](https://docs.microsoft.com/vi-vn/microsoft-365/security/defender-endpoint/configure-block-at-first-sight-microsoft-defender-antivirus?view=o365-worldwide#not-an-enterprise-admin-or-it-pro)
* Content Source: [microsoft-365/security/defender-endpoint/configure-block-at-first-sight-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-block-at-first-sight-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@xehoa13 Please share what is your feedback to improve this document. Thanks
