### ISSUE TITLE
Instructions on how to turn off spam filter are missing

### ISSUE THREAD

**Issue by Totentanz1980** [MicrosoftDocs/microsoft-365-docs#7615]
For some inexplicable reason, this page doesn't provide information on how to disable the spam filter for the massive amount of clients who use a different email threat protection platform.  It can't be because this capability does not exist, because that would just be madness to not allow us to turn off the spam filtering so we can do our own spam filtering.  So why the oversight in not providing instructions on how to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f095b8e3-be94-b244-850d-f7396762d0a5
* Version Independent ID: e32992cd-250a-2766-e487-edbc493def03
* Content: [Anti-spam protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-protection.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Totentanz1980, the three high-level anti-spam articles are:

- [Anti-spam protection](https://docs.microsoft.com/microsoft-365/security/office-365-security/anti-spam-protection): High-level overview about spam protection technologies. This is the topic you are referring to, and I contend is the least interesting or practical location for 'how to turn off/bypass' information.
- [Configure anti-spam policies](https://docs.microsoft.com//microsoft-365/security/office-365-security/configure-your-spam-filter-policies)
- [Anti-spam protection FAQ](https://docs.microsoft.com/microsoft-365/security/office-365-security/anti-spam-protection-faq)

I contend that a better place to talk about bypassing spam filtering is in the Configure topic and in the FAQ. So, I added a FAQ item and some information in the "What do you need to know before you begin?" section in the Config topic.

Updated content should be visible by F 2/4 ~11:00AM PST.

Thanks for the feedback.

Closing
