### ISSUE TITLE
Why was microsoft-365/enterprise/office-add-ins-wip.md removed?

### ISSUE THREAD

**Issue by AlexJerabek** [MicrosoftDocs/microsoft-365-docs#7620]
Recently, some Office Add-ins customers needed the information from an old article called "Use WIP and Intune to protect enterprise data in documents running Office Add-ins". We used to link to it from our docs, but the link broke in 2019 and someone quietly removed it. I went digging through this repo's history and found the file was removed as part of [this commit](https://github.com/MicrosoftDocs/microsoft-365-docs/commit/926aa077cf3b57a950d71eaadcad23bcc4efb4e0#diff-eaffee9ec47cd78cf0a4fd97f2f41ac43d59d49bd4046f679dc638ce0933af42) from @JoeDavies-MSFT. Before I replicate the old information, I'd love to know what the reason was for removing that file. Thanks!

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks

**Comment by KCCross** [comment]
Please contact me internally, thank you!
