### ISSUE TITLE
Organization Management is not a role

### ISSUE THREAD

**Issue by Yan-Son** [MicrosoftDocs/microsoft-365-docs#7621]
1) "Organization Management" is not a role, it is a permission or role GROUP. 
2) Global Administrator can do all Attack Simulation related things so it is better to ad this role to list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59c87455-77af-093a-6fb6-286049aad15a
* Version Independent ID: b2690e98-781d-4a27-a9bc-bd621964feb0
* Content: [Get started using Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-get-started.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Yan-Son, yes. I replaced Organization Management with Global Administrator. Only Global Administrator makes sense in the context of Azure AD roles.

Thanks for the feedback.

Closing
