### ISSUE TITLE
Info on Timer job purging PHL or moving data to Second-stage recycle bin ? 

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/microsoft-365-docs#7622]
Hello,

In chapter ''How retention works for SharePoint and OneDrive'', it says : 

_A timer job periodically runs on the Preservation Hold library. For content that has been in the Preservation Hold library for more than 30 days, this job compares the content to all queries used by the retention settings for that content. Content that is older than their configured retention period is then deleted from the Preservation Hold library, and from the original location if it is still there. This timer job **runs every seven day**s, which means that together with the minimal 30 days, it can take up to 37 days for content to be **deleted from the Preservation Hold library_**

but below, in the Note, it says that to prevent inadvertent data loss, data is permanently deleted from Recycle Bin only : 

Note: ''To help prevent inadvertent data loss, we no longer permanently delete content from the Preservation Hold library. Instead, we permanently delete content only from the Recycle Bin, so all content from the Preservation Hold library now goes through the second-stage Recycle Bin." 

This is a bit confusing, one cancels the other. Please clarify. Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@danone1985 The difference is the word "permanent", and is clearer when you look at the diagram.  It's deleted from the Preservation Hold library (you will no longer see it there) and moved to the second-stage Recycle Bin where it will be permanently deleted (no longer recoverable).

**Comment by cabailey** [comment]
Issue addressed, closing.
