### ISSUE TITLE
Doc to update : Power Apps is now available in 21vianet

### ISSUE THREAD

**Issue by Nicokirr** [MicrosoftDocs/microsoft-365-docs#7625]
As you can see here : https://docs.microsoft.com/en-us/power-platform/admin/business-applications-availability-china 
The service is now available in 21vianet, even if some limitations apply
So the table on this page should be updated on PowerApps line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec9d22a-5645-f235-2279-64b9194f87e6
* Version Independent ID: e9e0e8f0-e599-3db3-309e-e90c0e43d879
* Content: [Office 365 operated by 21Vianet - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/services-in-china/services-in-china?view=o365-21vianet)
* Content Source: [microsoft-365/admin/services-in-china/services-in-china.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/services-in-china/services-in-china.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@Nicokirr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7639

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Nicokirr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
