### ISSUE TITLE
English Number

### ISSUE THREAD

**Issue by EdwardCaulfield** [MicrosoftDocs/microsoft-365-docs#7628]
[On your page you indicate that English language technical support is available 24/7, but the numbers provided are not for English language support.  Please provide the local numbers for English language support.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c333804-3f9b-c44d-74d7-22400a3c7558
* Version Independent ID: 52e75bc7-55b9-978e-c4bf-f65813ca17de
* Content: [Support information for Switzerland - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/switzerland?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/switzerland.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/switzerland.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@EdwardCaulfield Thank you for your feedback. I'll test this and update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cmcatee-MSFT Question sent in the email. Thanks

**Comment by msbemba** [comment]
@yogkumgit I'm currently waiting for the correct phone number from the author.

**Comment by cmcatee-MSFT** [comment]
The numbers shown on the page for Switzerland are the only #s I have.
