### ISSUE TITLE
More recent videos

### ISSUE THREAD

**Issue by jgscherber** [MicrosoftDocs/microsoft-365-docs#7629]
The videos linked have more recent versions posted on YouTube (1 year ago vs. 3 months)

I think it'd be better if the more recent videos were used as they probably have updated information

More recent video: https://youtu.be/G2D9PFUulRo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43b53d9-6415-946c-2f34-3d63becdba3f
* Version Independent ID: 8e0dc394-9b9c-c312-a2ce-ed12d95515ee
* Content: [Get expert training on advanced hunting](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-expert-training?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-expert-training.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-expert-training.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@jgscherber Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7640

Once the author approves, the document will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@jgscherber Thank you for your feedback. I have got a confirmation that the video is the same even though there are two versions. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jgscherber Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
