### ISSUE TITLE
Content of page confusing

### ISSUE THREAD

**Issue by corinaf1** [MicrosoftDocs/microsoft-365-docs#7632]
I find it awkward that the title of the page is "alert grading playbooks" and then inside we go on to describe MDO & MDA?? Looks like the wrong place to be presenting products, and also why these two and not others in M365D?
Also, it is unclear that "playbooks" refers to content here in the documentation as opposed to in-product content (and pretty soon we will have these available in-product which will make the confusion even worse). How can we clarify this?
Finally, I would expect a description of the relationship btwn these playbooks and the existing in-product "alert recommended actions" in some M365D alerts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95459c64-c924-8cc7-1620-be6a1241b6b4
* Version Independent ID: 95459c64-c924-8cc7-1620-be6a1241b6b4
* Content: [Alert grading playbooks](https://docs.microsoft.com/en-us/microsoft-365/security/defender/alert-grading-playbooks?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/alert-grading-playbooks.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/alert-grading-playbooks.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by yogkumgit** [comment]
@JoeDavies-MSFT Please help us in resolving this issue. Thanks

**Comment by JoeDavies-MSFT** [comment]
These issues are being discussed internally at Microsoft. Thanks for letting us know.
