### ISSUE TITLE
dead link, broken email server

### ISSUE THREAD

**Issue by joernheissler** [MicrosoftDocs/microsoft-365-docs#7635]
Dear Microsoft,

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide contains a dead link to https://office365.uservoice.com/forums/289138-office-365-security-compliance (Submit and view feedback for ... this product).

So, here's my feedback:
I tried to send an email to one of your office365 customers through my own email server. This got rejected because you blacklisted my sender ip address for whatever reason.
When trying to unlist my address using your self-service portal, you tried sending me a confirmation email with overlong lines:
`rejected after DATA: maximum allowed line length is 998 octets, got 3172` is what my mailserver told me.

https://datatracker.ietf.org/doc/html/rfc5321#section-4.5.3.1.6 says that lines shouldn't be more than 1000 octets (including `<CRLF>`). 

Please fix your email software.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 390d461b-7fce-d4ac-1c90-97b7b81dc0c2
* Version Independent ID: 9f8c7285-627f-13c6-1c7a-88fa7e14ed86
* Content: [Remove yourself from the blocked senders list - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@joernheissler Thank you for your feedback. The product feedback link in the document is broken and this has been escalated to the concerned team. We will fix this shortly.

Meanwhile, you can product feedback directly on our Main feedback portal: https://feedbackportal.microsoft.com/

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @joernheissler Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
