### ISSUE TITLE
Please provide RSS Link to get updates

### ISSUE THREAD

**Issue by VinodSP1980** [MicrosoftDocs/microsoft-365-docs#7636]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fe9020-6803-bee8-7fcc-fae3971e6feb
* Version Independent ID: 480b994c-7d3f-d234-8847-e415360c6bf7
* Content: [What's new in the Microsoft 365 admin center? - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/whats-new-in-preview?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/whats-new-in-preview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/whats-new-in-preview.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@VinodSP1980 Thank you for your feedback. I'll work with the author and update the document with an RSS feed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @VinodSP1980 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
