### ISSUE TITLE
Clarification of Admin Assignments

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#7644]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by dkotars** [comment]
> [Enter feedback here]
Under "Admin requirements" it is stated:

"In order to deploy an add-in via Centralized Deployment, you need to be either a Global admin or an Exchange admin in the organization.

 Note

An Exchange admin can deploy an add-in only if the App Registrations property is set to true in Azure Active Directory admin center as shown in the following image:"

I believe if you add the "Application Administrator" role to the user who has "Exchange Administrator" roles, they can deploy add-ins, even if user enablement is disabled. At least from my testing. 

Can you verify and update documentation?

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7690.

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dkotars Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
