### ISSUE TITLE
doc refers to bad URL

### ISSUE THREAD

**Issue by jrhi** [MicrosoftDocs/microsoft-365-docs#7646]
[Enter feedback here]
The doc refers to the following URL which is not valid:  https://api-luna.securitycenter.windows.com/api/remediationtasks/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef23eda-5f78-cdcf-ec94-ea5db4734a84
* Version Independent ID: 8b5f28a6-e988-e992-a49e-1d99b3d3687e
* Content: [List all remediation activities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-remediation-all-activities?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-remediation-all-activities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-remediation-all-activities.md)
* Product: **m365-security**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by jweston-1** [comment]
I should be able to get to this today.

**Comment by jweston-1** [comment]
Resolve as "won't fix" 
This is an example URL, is labeled as "Example URL" and is provided to illustrate syntax. We do not provide URLs to microsoft-owned test systems.
