### ISSUE TITLE
Unable to download the "FISC Japan backgrounder"

### ISSUE THREAD

**Issue by kulpravin** [MicrosoftDocs/microsoft-365-docs#765]
Hi,

Few of our customers are looking for FISC compliance on Azure. I am unable to download "Download the FISC Japan backgrounder"

Getting below error.

/91d74f03-aa26-4d22-ab99-576fe9f88b58/fisc_compliance_backgrounder.pdf
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

Thanks Pravin

**Comment by kulpravin** [comment]
Name of the document is fisc_compliance_backgrounder.pdf.

This document is under below link : 
https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-fisc-japan

**Comment by mypil** [comment]
@kulpravin  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@robmazz - Can you please share your insights on this issue?

This is based on the below doc info.
Content: Compliance offering: [Center for Financial Industry Information Systems (FISC)](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-fisc-japan) 
Content source: [microsoft-365/compliance/offering-FISC-Japan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/edit/public/microsoft-365/compliance/offering-FISC-Japan.md)

Thank you.

**Comment by robmazz** [comment]
@kulpravin - thanks for your feedback about this link, I'm working to get an update from the author. I'll respond here when I've received the new link and updated the article.

**Comment by kulpravin** [comment]
Thanks for the update.

**Comment by robmazz** [comment]
@kulpravin - this has been fixed and the published topic has been updated. Thanks! https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-fisc-japan#download-the-offering-backgrounder.

**Comment by kulpravin** [comment]
Thanks
