### ISSUE TITLE
In the navigation pane, choose Device configuration. ???

### ISSUE THREAD

**Issue by bencorley** [MicrosoftDocs/microsoft-365-docs#7650]
Hi,

Can you elaborate about this :
**In the navigation pane, choose Device configuration.**
WHERE IS THIS on the portal there's no SUCH THING AT ALL !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a6e4ee4-97f2-9d40-5a92-4580fa0d25ac
* Version Independent ID: 7a6e4ee4-97f2-9d40-5a92-4580fa0d25ac
* Content: [Device groups in Microsoft Defender for Business](https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-create-edit-device-groups?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-create-edit-device-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-create-edit-device-groups.md)
* Product: **m365-security**
* Technology: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bencorley Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
