### ISSUE TITLE
 Microsoft Defender for Endpoint on Linux - no ZFS support?

### ISSUE THREAD

**Issue by danboid** [MicrosoftDocs/microsoft-365-docs#7651]
I am looking into our options for AV software for our Ubuntu 20.04 based LTSP server.

The /home directories on this server are stored on ZFS but ZFS isn't listed as a supported filesystem for real-time protection using Defender. Is ZFS not supported?

If ZFS is not currently supported by Defender, do you plan to add support for it? Can Defender still be used without realtime protection on all mounted filesystems?

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@danboid Thank you for your feedback. You are correct,  ZFS is currently not supported. However, you can use Defender without real-time protection on these systems. Regarding details for Support on ZFS, you can leave product feedback at https://feedbackportal.microsoft.com/ and one of our Product team members will be able to provide accurate information.

The solution currently provides real-time protection for the below file system types only

btrfs
ecryptfs
ext2
ext3
ext4
fuse
fuseblk
jfs
nfs
overlay
ramfs
reiserfs
tmpfs
udf
vfat
xfs


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @danboid Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danboid** [comment]
I opened a few tickets on the MS feedback site last night including one for adding ZFS support to Defender.
