### ISSUE TITLE
Create a DLP policy to remove guest access to highly sensitive files - Clarification

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#7652]
Wondering if you need to clarify the statement under this section that states: 

"It's important to note that this policy doesn't remove access if the guest is a member of the site or team as a whole. If you plan to have highly sensitive documents in a site or team with guest members, consider using [private channels in Teams](https://support.microsoft.com/office/de3e20b0-7494-439c-b7e5-75899ebe6a0e) and only allowing members of your organization in the private channels."

For a site, if there is DLP in place that will block files with sensitive content, the following most likely applies: https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-reference?view=o365-worldwide#actions

Primarily "For SharePoint Online and OneDrive for Business locations documents will be proactively blocked right after detection of sensitive information, irrespective of whether the document is shared or not, for all external users, while internal users will continue to have access to the document."

Tested this with a site and external guests will not see files that are blocked with DLP.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4945844-0f8f-2691-1092-0025cc19c683
* Version Independent ID: adc60afc-fb2a-dd5c-9217-6e074abc8dc0
* Content: [Create a secure guest sharing environment](https://docs.microsoft.com/en-us/microsoft-365/solutions/create-secure-guest-sharing-environment?view=o365-worldwide#create-a-dlp-policy-to-remove-guest-access-to-highly-sensitive-files)
* Content Source: [microsoft-365/solutions/create-secure-guest-sharing-environment.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/create-secure-guest-sharing-environment.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. I was able to repro as well. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7691

Once the author reviews and approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dkotars Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
