### ISSUE TITLE
Not able to run PS script

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/microsoft-365-docs#7658]
I am running it in Powershell 7. 

I created the GroupCreators.ps1 in PS ISE, and then tried to run it as admin in PS7, and all the commands fail saying unrecognized.

PS C:\powershell> Install-Module AzureADPreview
PS C:\powershell> .\groupcreators.ps1
Connect-AzureAD: C:\powershell\GroupCreators.ps1:4
Line |
   4 |  Connect-AzureAD
     |  ~~~~~~~~~~~~~~~
     | The term 'Connect-AzureAD' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

Get-AzureADDirectorySetting: C:\powershell\GroupCreators.ps1:6
Line |
   6 |  $settingsObjectID = (Get-AzureADDirectorySetting | Where-object -Prop …
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-AzureADDirectorySetting' is not recognized as a name of a cmdlet, function, script file,
     | or executable program. Check the spelling of the name, or if a path was included, verify that the path
     | is correct and try again.

Get-AzureADDirectorySettingTemplate: C:\powershell\GroupCreators.ps1:9
Line |
   9 |      $template = Get-AzureADDirectorySettingTemplate | Where-object {$ …
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-AzureADDirectorySettingTemplate' is not recognized as a name of a cmdlet, function,
     | script file, or executable program. Check the spelling of the name, or if a path was included, verify
     | that the path is correct and try again.

InvalidOperation: C:\powershell\GroupCreators.ps1:10
Line |
  10 |      $settingsCopy = $template.CreateDirectorySetting()
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

New-AzureADDirectorySetting: C:\powershell\GroupCreators.ps1:11
Line |
  11 |      New-AzureADDirectorySetting -DirectorySetting $settingsCopy
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'New-AzureADDirectorySetting' is not recognized as a name of a cmdlet, function, script file,
     | or executable program. Check the spelling of the name, or if a path was included, verify that the path
     | is correct and try again.

Get-AzureADDirectorySetting: C:\powershell\GroupCreators.ps1:12
Line |
  12 |      $settingsObjectID = (Get-AzureADDirectorySetting | Where-object - …
     |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-AzureADDirectorySetting' is not recognized as a name of a cmdlet, function, script file,
     | or executable program. Check the spelling of the name, or if a path was included, verify that the path
     | is correct and try again.

Get-AzureADDirectorySetting: C:\powershell\GroupCreators.ps1:15
Line |
  15 |  $settingsCopy = Get-AzureADDirectorySetting -Id $settingsObjectID
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-AzureADDirectorySetting' is not recognized as a name of a cmdlet, function, script file,
     | or executable program. Check the spelling of the name, or if a path was included, verify that the path
     | is correct and try again.

InvalidOperation: C:\powershell\GroupCreators.ps1:16
Line |
  16 |  $settingsCopy["EnableGroupCreation"] = $AllowGroupCreation
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.

Get-AzureADGroup: C:\powershell\GroupCreators.ps1:20
Line |
  20 |  … ttingsCopy["GroupCreationAllowedGroupId"] = (Get-AzureADGroup -Search …
     |                                                 ~~~~~~~~~~~~~~~~
     | The term 'Get-AzureADGroup' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

Set-AzureADDirectorySetting: C:\powershell\GroupCreators.ps1:24
Line |
  24 |  Set-AzureADDirectorySetting -Id $settingsObjectID -DirectorySetting $ …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Set-AzureADDirectorySetting' is not recognized as a name of a cmdlet, function, script file,
     | or executable program. Check the spelling of the name, or if a path was included, verify that the path
     | is correct and try again.

Get-AzureADDirectorySetting: C:\powershell\GroupCreators.ps1:26
Line |
  26 |  (Get-AzureADDirectorySetting -Id $settingsObjectID).Values
     |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-AzureADDirectorySetting' is not recognized as a name of a cmdlet, function, script file,
     | or executable program. Check the spelling of the name, or if a path was included, verify that the path
     | is correct and try again.

PS C:\powershell> Uninstall-Module AzureAD
Uninstall-Package: No match was found for the specified search criteria and module names 'AzureAD'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
* Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
* Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by rconiv** [comment]
As you will notice on the first line of what I sent you, I installed AzureADPreview.

I ran the install again, and it thought for a bit, and then gave me the prompt, so is up to date. 

Did you run the the script on PowerShell 5 or PS7?   Was there anything else that needed to be run, after installing the preview, and before running the script, to install any other modules, because the link to how to install the AzureADPreview mentions installing other things farther down.

![image](https://user-images.githubusercontent.com/72881999/153627690-ab9c33a0-50e8-4202-b10f-b50966eef2e7.png)

It still doesn't work for me.

**Comment by msbemba** [comment]
@rconiv Thank you for the response. Could you please try Import-Module AzureADPreview -UseWindowsPowerShell and see if the Connect-AzureAD works?

Thanks
Sri

**Comment by rconiv** [comment]
I get this when trying to install it.  I uninstalled and reinstalled the AzureADPreview.

![image](https://user-images.githubusercontent.com/72881999/153639820-03ea5a7c-9b7f-44b5-b35b-442dc40780ee.png)

**Comment by msbemba** [comment]
@rconiv Thank you for the response. I was able to test in Powershell 7 and get an error. From what I see, The Azure AD module is supported on the following Windows operating systems with the default version of Microsoft .NET Framework and Windows PowerShell:

Windows 10
Windows 8.1 Pro
Windows 8.1 Enterprise
Windows 7 SP1
Windows Server 2016 TP5
Windows Server 2012 R2
Windows Server 2008 R2 SP1

So that could be the issue. Are you able to run the script on PS 5?

Thanks
Sri

**Comment by msbemba** [comment]
@rconiv Thank you for the response. Could you please try the below steps in Powershell 5.0

Install-module Azureadpreview
Import-Module Azureadpreview
Connect-AzureAD

Thanks
Sri

**Comment by rconiv** [comment]
It did what the instructions say it should do this time.  Azureadpreview must be pretty big, it took it a minute or so to install.

![image](https://user-images.githubusercontent.com/72881999/154108830-4b29dae8-8667-451f-8f5d-622497068f13.png)

**Comment by rconiv** [comment]
Not sure what was done, but the script doesn't fail out now.

**Comment by ccs-steve** [comment]
The three modifications to the process that helped me:
## Allowed the install of AzureADPreview without any errors
>Install-Module AzureADPreview -AllowClobber

## Added to the script at the beginning of line 4 calling "Connect-AzureAD". This stopped the "The term 'Connect-AzureAD' is not recognized as a name of a cmdlet," error.
AzureADPreview\Connect-AzureAD

## If you have errors executing the scripts due to Execution Policies:
>powershell -ExecutionPolicy ByPass -File scriptname.ps1

**Comment by erik-wo** [comment]
Thx, worked perfectly.
