### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by wloeven** [MicrosoftDocs/microsoft-365-docs#766]
the . is missing in the following powershell command:
$domainName = "testlab"+$yourDomain
it should be : $domainName = "testlab."+$yourDomain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6989d21-f7a7-043b-c91a-cd019a19c0e6
* Version Independent ID: 39e286bc-58fe-768e-ee65-2a2fedf1e544
* Content: [Simulated enterprise base configuration for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise#feedback)
* Content Source: [microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by mypil** [comment]
@wloeven  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@wloeven Corrected and updated. Thanks for letting us know. Sorry for the inconvenience.
