### ISSUE TITLE
Microsoft 365 Defender prerequisites | Licensing requirements

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#7661]
Hello,

Somehow not clear, now when Defender Plan 1 is a part of Microsoft 365 E3,
Is it really needed to have any add-on like Security E5 to get Microsoft 365 Defender?

Same for the "Threat and Vulnerability management", which exactly license cover it since Defender Plan 1 is a part of Microsoft 365 E3? As we do see the Vulnerability management section in the security.microsoft.com...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e396c36f-1f7f-a92a-f425-a08b3aaf44e3
* Version Independent ID: 2f15dfb7-1695-9cf7-7560-f9a51eadd745
* Content: [Microsoft 365 Defender prerequisites](https://docs.microsoft.com/en-us/microsoft-365/security/defender/prerequisites?view=o365-worldwide#licensing-requirements)
* Content Source: [microsoft-365/security/defender/prerequisites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/prerequisites.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. You are correct, Defender for plan 1 is a part of M365 E3, However, to get the capabilities of M365 Defender (Microsoft defender for endpoint+Microsoft Defender for O365 + Microsoft Defender for identity + Microsoft defender for Cloud apps ) one would need Microsoft 365 E3 with the Microsoft 365 E5 Security add-on or Microsoft 365 E3 with the Enterprise Mobility + Security E5 add-on.

Threat and Vulnerability management is available only with [Microsoft Defender for Endpoint Plan 2](https://go.microsoft.com/fwlink/p/?linkid=2154037) -https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/next-gen-threat-and-vuln-mgt?view=o365-worldwide 

I'd recommend you raise a support ticket to check if there is a bug or an issue in the backend on your tenant.

Hope this helps!

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba 
I have another question maybe explaining more: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7414
But I don't think support can help a lot, I read a lot of Defender 365 documents and I can't find a good explanation of how to do the good compliant on-boarding if:
1. We used Azure Defender Full coverage for servers, which some time ago enables us https://securitycenter.microsoft.com, this now migrated to https://security.microsoft.com, but via old Defender ATP all services including Vulnerability were activated
2. We got MS 365 E5 Security for some users, this also enables full Defender Plan 2 including the Vulnerability module
3. MS 365 E3 added Defender Plan 1, the on-boarding steps are the same as for MS 365 E5 Security
Now we still can use the Vulnerability module because of steps 1 or 2...
And this is what I try to find in MS Docs, what if customers use Azure Defender or Defender Plan 2 via some license, then devices that are on-boarded via Defender Plan 1, will be included in the services (scan, detect, analyze, etc.) that are only for Defender Plan 2? And how to translate such setup in license compliance, how to stay compliant?

**Comment by msbemba** [comment]
@lightupdifire Thank you for your response. It is better for the author or PG to answer #https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7414 as it is for a combination of licenses. We have requested the author/PG to handle that request.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7661 can be closed.

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/7414 is assigned to the Author.

Thanks
Sri
