### ISSUE TITLE
Does this apply to "Personal" or "Family" Office365?

### ISSUE THREAD

**Issue by edrandall** [MicrosoftDocs/microsoft-365-docs#7662]
[Enter feedback here]
Combining information from this page and other sources, it remains ambiguous and unclear whether it's possible to use a domain name with the Personal or Family offerings.
Please add a clear statement as to which edition(s) this applies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.yml)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by msbemba** [comment]
@edrandall Thank you for your feedback. I have added a question to FAQ's about Family and personal offerings, this can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7692 

You can find more information here - https://support.microsoft.com/en-us/office/get-a-personalized-email-address-in-microsoft-365-75416a58-b225-4c02-8c07-8979403b427b

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @edrandall Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
