### ISSUE TITLE
No change in the CmdletParameters

### ISSUE THREAD

**Issue by ruben03mx** [MicrosoftDocs/microsoft-365-docs#7669]
I know that UAL is enabled and I reassure that it was on by running the command `Get-AdminAuditLogConfig | FL UnifiedAuditLogIngestionEnabled` and receiving the output `UnifiedAuditLogIngestionEnabled : True`.  
However I wanted to identify since when it was turned on and using the command `Search-AdminAuditLog -Cmdlets Set-AdminAuditLogConfig -Parameters UnifiedAuditLogIngestionEnabled`, I get `CmdletParameters   : {UnifiedAuditLogIngestionEnabled}` which according to the documentation means it is turn off., however the "RunDate" matches the time I know it was turned on.  
 As a test, I disabled the UAC by executing `Set-AdminAuditLogConfig -UnifiedAuditLogIngestionEnabled $false` and after almost two hours I verified it was off (got `UnifiedAuditLogIngestionEnabled : False`), however after executing the query `Search-AdminAuditLog -Cmdlets Set-AdminAuditLogConfig -Parameters UnifiedAuditLogIngestionEnabled` the date in "RunDate" did not change and the CmdLetParameters maintained the same value (in this case it matched to the documentation as it does not include "Confirm").  
Is there something I'm doing incorrectly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6aa9c0c-c1ba-a464-3724-2060b61df19b
* Version Independent ID: 1d2e74f1-d2b8-6cdf-a9ea-e5d9f67a35b0
* Content: [Turn auditing on or off - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/turn-audit-log-search-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/turn-audit-log-search-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/turn-audit-log-search-on-or-off.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@ruben03mx Thanks for question. I would suggest you open a ticket with MS Support and they can investigate. Not sure why your experience is different from the documentation.

Not sure this will help, but you could try running Get-AdminAuditLogConfig | FL *UnifiedAuditLog*, which displays the first opt-in date. I believe this date might correspond when unified audit logging was first enabled.
