### ISSUE TITLE
Enroll new devices - please update

### ISSUE THREAD

**Issue by CraigGladman** [MicrosoftDocs/microsoft-365-docs#7672]
Hi guys,

Couple of things - group name "Modern Workplace Devices--Shared Device Mode" is incorrect. Should be "Modern Workplace Devices - Shared Device Mode". Would also be good if you can include more specific information to explain how someone adds a record to this group (eg, need to add the autopilot device record to the group Intune - Groups)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 053b3738-e015-da32-958a-0871d6eb4fd5
* Version Independent ID: 053b3738-e015-da32-958a-0871d6eb4fd5
* Content: [Shared devices - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/shared-devices?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/service-description/shared-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/shared-devices.md)
* Service: **m365-md**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
Thank you @CraigGladman for bringing this to our attention. I'm working with a PM to take a look at the documentation.

**Comment by yogkumgit** [comment]
@tiaraquan Awaiting your kind response. Thanks

**Comment by tiaraquan** [comment]
@yogkumgit @CraigGladman Apologies, but I am waiting for verification from the team. Will provide an update as soon as I have one.

**Comment by tiaraquan** [comment]
Hi @CraigGladman @yogkumgit. Apologies for the delayed response to your feedback. We've updated the article with additional information about registering new devices in shared device mode as per #13461. Please see the updated article here: https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/shared-devices?view=o365-worldwide#register-new-devices-in-shared-device-mode

**Comment by tiaraquan** [comment]
#sign-off
