### ISSUE TITLE
Edge only web filtering  for windows 10 multisession

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/microsoft-365-docs#7674]
Can you add in a limitation for defender for Endpoint on Windows 10 multisession. I have found network protection for blocking on 3rd party browsers doesn't work as actually the AVD session hosts are listed as OS Configuration: member server which only supprots Edge for web filtering.

Only Microsoft Edge is supported if your device's OS configuration is Server (cmd > Systeminfo > OS Configuration). Network Protection is only supported in Inspect mode on Server devices, which is responsible for securing traffic across supported third-party browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb9a6dfb-2853-20fc-bd6c-2f636945b328
* Version Independent ID: 60586381-2d76-32bc-8e44-342ee36ada1c
* Content: [Onboard Windows multi-session devices in Azure Virtual Desktop](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@chiners68 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7776

Thanks
Sri
