### ISSUE TITLE
Steps out of sync with linked pages

### ISSUE THREAD

**Issue by JeroenOortwijn** [MicrosoftDocs/microsoft-365-docs#7675]
The steps in the [Solution: Remove a former employee](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee#solution-remove-a-former-employee) section are out of sync with the steps in the individual pages:

| [Solution: Remove a former employee](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee#solution-remove-a-former-employee) | individual pages |
| --- | --- |
| Step 1 - Prevent a former employee from logging in and block access to Microsoft 365 services | [Step 1 - Prevent a former employee from logging in and block access to Microsoft 365 services](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-1) |
| Step 2 - Save the contents of a former employee's mailbox | [Step 2 - Save the contents of a former employee's mailbox](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-2) |
| Step 3 - Forward a former employee's email to another employee or convert to a shared mailbox | [Step 3 - Wipe and block a former employee's mobile device](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-3) |
| Step 4 - Give another employee access to OneDrive and Outlook data | [Step 4 - Forward a former employee's email to another employee or convert to a shared mailbox](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-4) |
| Step 5 - Wipe and block a former employee's mobile device | [Step 5 - Give another employee access to OneDrive and Outlook data](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-5) |
| Step 6 - Remove and delete the Microsoft 365 license from a former employee | [Step 6 - Remove the Microsoft 365 license from a former employee](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-6) |
| Step 7 - Delete a former employee's user account | [Step 7 - Delete a former employee's user account](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-7) |

I'm not sure which of the step sequences is the correct one, so I haven't submitted a PR yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@JeroenOortwijn Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7676. The individual pages are in the correct order.

Thanks
Sri

**Comment by JeroenOortwijn** [comment]
Thanks, looking good now.

I just noticed that the steps in the [image](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/9f0e84835121ce6228fdc69182c24be7ad1cb20e/microsoft-365/media/delete-user-account.png) also need changing.
Do I need to open a separate issue for that?

**Comment by yogkumgit** [comment]
@JeroenOortwijn Yes, please do. Closing this one. Thanks
