### ISSUE TITLE
where is Sign in activity alert which category to look at ?

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/microsoft-365-docs#7678]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Microsoft 365 alert policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
Hi @robinpoulose1, as per my response in the other issue that you opened, you will have to create an alert policy using powershell. For the -Operations parameter, use the value "UserLoggedIn".

To create an activity alert (which I mentioned in the other issue are being deprecated), you can search for "User logged in", which is located under "Workplace Analytics activities". 

![image](https://user-images.githubusercontent.com/36746813/153974369-08b470c4-0d31-41d9-8092-f16f79887852.png)

Hope this helps.
