### ISSUE TITLE
How to disable

### ISSUE THREAD

**Issue by SteveColegrove** [MicrosoftDocs/microsoft-365-docs#768]
Okay, it's November, 19th :)  
Are the instructions for disabling this ready?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
I just updated the article with the link to the new PowerShell module.

**Comment by TheSharePointProfessional** [comment]
The article does not have a link to new PowerShell modules

**Comment by cmcatee-MSFT** [comment]
@TheSharePointProfessional, we had a small problem, but it has since been fixed and the link is once again available.
