### ISSUE TITLE
Missing OneDrive info

### ISSUE THREAD

**Issue by BwaddellProtectedTrust** [MicrosoftDocs/microsoft-365-docs#7680]
Article is missing how to access another employee's OneDrive yet the title says it will show you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca63bae-95f1-3248-ed6e-1bfbe0d7e9ff
* Version Independent ID: a56fc5c1-7ffd-0829-b5a4-9297ce2873ac
* Content: [Step 4 - Forward a former employee's email to another employee or convert to a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-4?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-4.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-4.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@BwaddellProtectedTrust The Page has been updated now. 

@yogkumgit  We can close the issue.

Thanks
Sri
