### ISSUE TITLE
Admin Consent needed twice during setup

### ISSUE THREAD

**Issue by porterkim** [MicrosoftDocs/microsoft-365-docs#7686]
When enabling Microsoft OneDrive LTI in Canvas, I had to click the Admin Consent button at the beginning of the setup per the instructions on this page.  Only a few permissions were listed to grant access to.  After completing the setup and testing in Canvas, I received an error when clicking on the Microsoft OneDrive link of a course.  Error: "You do not have sufficient permissions. Your school admin is required to give consent on the registration portal." 

I had to go back to https://onedrivelti.microsoft.com/admin and click the Admin Consent button a second time. This time there were many more permissions on the page to grant access to.  After accepting those, the OneDrive LTI in Canvas worked.

Why is the OneDrive LTI listed as unverified on the page to grant permissions?

It would be helpful if the instructions on this page included a note to click on the admin consent button after step 9 of the "Enable Microsoft OneDrive LTI in Canvas" section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fee0615-eb33-e945-c1ee-efad095ead11
* Version Independent ID: 2a7089da-e35a-8f39-3df1-98ee29710cb6
* Content: [Use Microsoft OneDrive Learning Tools Interoperability](https://docs.microsoft.com/en-us/microsoft-365/lti/onedrive-lti?view=o365-worldwide)
* Content Source: [microsoft-365/lti/onedrive-lti.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lti/onedrive-lti.md)
* Service: **o365-administration**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by msbemba** [comment]
@porterkim Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7794

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @porterkim Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
