### ISSUE TITLE
"View all and manage members" Not available in some groups 

### ISSUE THREAD

**Issue by AhmedEmam91** [MicrosoftDocs/microsoft-365-docs#7687]
we face issues as the "View all and manage members" is not available and don't appear in some groups for the user who managed this group

**Comment by yogkumgit** [comment]
@AhmedEmam91 Please indicate which document you are referring to and what is your feedback. Thanks

**Comment by yogkumgit** [comment]
@AhmedEmam91 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
