### ISSUE TITLE
The ja-jp page has a translation error.The label (ラベル) is correct, not the policy (ポリシー) .

### ISSUE THREAD

**Issue by nakamae1983** [MicrosoftDocs/microsoft-365-docs#7689]
[Enter feedback here]
The ja-jp page has a translation error.
https://docs.microsoft.com/ja-jp/microsoft-365/compliance/retention-flowchart?view=o365-worldwide

The label (ラベル) is correct, not the policy (ポリシー) .

![image](https://user-images.githubusercontent.com/65495605/153779478-27cb3a39-9c16-4195-9864-cebb0af77799.png)

![image](https://user-images.githubusercontent.com/65495605/153779547-084dd5f7-4c6e-484c-8526-17c630d85161.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58a7e8c-acc0-df60-1563-8ac667096826
* Version Independent ID: 770a3929-18b7-3655-be8d-5c3eb7462df2
* Content: [Flowchart to determine when an item will be retained or permanently deleted - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-flowchart?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/retention-flowchart.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-flowchart.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@TinaMcN Please help us in resolving this issue. Thanks

**Comment by TinaMcN** [comment]
@nakamae1983 thanks for reporting the issue.  I asked the localization vendors to fix the text in the image.

**Comment by nakamae1983** [comment]
@TinaMcN I have confirmed the fix. Thank you for your support.

**Comment by yogkumgit** [comment]
@nakamae1983 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TinaMcN** [comment]
@nakamae1983 thank you for checking the image and providing the detailed feedback.  I passed on your notes to the translators to fix it.

**Comment by TinaMcN** [comment]
Hi @nakamae1983 the art has been updated.  Can you please confirm if it looks ok now?
![image](https://user-images.githubusercontent.com/53281468/157354790-343c8171-1283-45b2-8a3c-c0c45e9c8d88.png)

**Comment by nakamae1983** [comment]
@TinaMcN 

Thanks for the fix.
It’s OK🙆‍♂️
Thank you all for your cooperation.

**Comment by TinaMcN** [comment]
@nakamae1983 thank you very much for confirming it's ok now and thanks again for sharing the feedback.
