### ISSUE TITLE
AzCopy v10

### ISSUE THREAD

**Issue by NeilColyn** [MicrosoftDocs/microsoft-365-docs#769]
Is it possible to use AzCopy v10 to upload pst files for Office 365 users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files#feedback)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by mypil** [comment]
@NeilColyn  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by markjjo** [comment]
@NeilColyn As per this topic (https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files#step-1-copy-the-sas-url-and-install-azure-azcopy) we recommend using the version that can be downloaded via the PST import UX. That version of azcopy supports the command syntax provided in this topic. v10 may work but you might have to tweak the syntax.
