### ISSUE TITLE
Windows and Office 365 deployment lab kit assistance

### ISSUE THREAD

**Issue by Realkdrummer** [MicrosoftDocs/microsoft-365-docs#7695]
Hello, 
I just extracted the Windows and Office 365 deployment lab kit in a Hyper-V environment.  I was able to log into the DC, the Config Manager and the GW1 VM machines. I cannot however log into any of the client VMs (1-4).  Should I be able to log into these VM's once  I have distributed memory to all of them? What am I missing?  I followed the set instructions but am still not able to log into these client VMs. Do you have any video tutorials dedicated to getting the Windows and Office 365 deployment lab kit up and running. Can I connect with someone at Microsoft via Zoom/WebEx, etc.?

Thanks,

Kevin

**Comment by yogkumgit** [comment]
@Realkdrummer Please indicate which document you are referring to and what is your feedback to improve it. Thanks

**Comment by Realkdrummer** [comment]
Hello,
I used the Lab Set Up Guide, and Lab Guide provided by Microsoft on the same page that the Lab Kit is downloaded from.  I could be asking for assistance from the wrong source. If so, who can I reach out to in order to get help setting up the lab kit properly? Documents are attached.

Thank you,

[Lab Kit_21H1_set up guide_v3.docx](https://github.com/MicrosoftDocs/microsoft-365-docs/files/8063000/Lab.Kit_21H1_set.up.guide_v3.docx)
[Lab Kit_21H1_lab guide_v3.docx](https://github.com/MicrosoftDocs/microsoft-365-docs/files/8063001/Lab.Kit_21H1_lab.guide_v3.docx)

**Comment by yogkumgit** [comment]
@Realkdrummer Thank you very much for visiting here.  Here, we are limited to documentation fixes and improvements only. Please open a service ticket in your tenant and follow with them for the resolution. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
