### ISSUE TITLE
Update documentation to reflect "New version"

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#7698]
Please update this article to instead describe the "new version" of threat tracker (https://security.microsoft.com/threattrackerv2). Especially describe the "Trending campaigns" how this differ from the Campaigns one (https://security.microsoft.com/campaigns).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58981cc-c653-509e-2bbf-3d2d0231b18c
* Version Independent ID: 7aa12d46-4f12-e06a-407d-7916e1748b69
* Content: [Threat Trackers - New and Noteworthy - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-trackers?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/threat-trackers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-trackers.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@JonesMikael Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7795

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JonesMikael Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
