### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by VK9198** [MicrosoftDocs/microsoft-365-docs#770]
https://outlook.office365.com/ecp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1541da6f-af9a-05d5-fa34-b1a5df61424f
* Version Independent ID: 88e111ed-67f7-41bc-d823-863ee7ea2a2e
* Content: [Set up Office 365 ATP Safe Links policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by VK9198** [comment]
https://outlook.office.com/ecp this is also not working if I am login with my tenant "Bad request" error

**Comment by mypil** [comment]
@VK9198  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
@VK9198 Thank you for your message. I have checked and confirmed that the link https://outlook.office365.com/ecp/ is properly linked and working fine. You need to login to your Office365 admin before you can access this link. 

![image](https://user-images.githubusercontent.com/47118050/69696211-d20d9880-1100-11ea-8db2-41cc2ee2cfea.png)

Thanks.
Imran.

@mypil  FYI Please.

**Comment by mypil** [comment]
@VK9198 - From our understanding, the issue you raised has been answered by joinimran. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
