### ISSUE TITLE
We Nepalese also need a phone support to solve our problem related to MS Product.

### ISSUE THREAD

**Issue by GyanwatiProject** [MicrosoftDocs/microsoft-365-docs#7700]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00cb5342-0ced-ff9b-6fe4-9027decae429
* Version Independent ID: 3ff474de-a07d-bd6c-3621-96674a40b9ec
* Content: [Support information for Nepal - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/nepal?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/nepal.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/nepal.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@GyanwatiProject Thank you for your feedback. We currently do not have a phone support option available and are working on getting one. Once there is a number available, the document will be updated.

Also note that when you request for online support via the need help icon on the admin center, the technician will be able to call you and troubleshoot.

Hope that helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GyanwatiProject Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
