### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by Philbbailey** [MicrosoftDocs/microsoft-365-docs#7701]
There's Skype for Business data in this article and no mention of Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6193dd68-287d-92d0-6c30-60afd6056d6b
* Version Independent ID: 158c97ef-4787-c4ad-3b92-7aff01feb6ba
* Content: [Network planning and performance tuning for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/network-planning-and-performance?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/network-planning-and-performance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/network-planning-and-performance.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Added link to Teams network planning article in [PR #12760](https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/12760)
