### ISSUE TITLE
Some settings are no longer applicable

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#7702]
"Settings categories" section lists Browser Start pages and Enterprise mode site list, but these do NOT apply to Edge Chromium, just legacy Edge. [MMD switched to Edge Chromium].
Suggest add a note to this effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e5e9bd-4de7-92eb-3eca-b0b5164c8374
* Version Independent ID: 80b519bc-c4d6-abfc-ceff-f7698b9501b6
* Content: [Microsoft Managed Desktop and Windows 11 - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/intro/win11-overview?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/intro/win11-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/intro/win11-overview.md)
* Service: **m365-md**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
Added a note to this page to address this issue. It is included in https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/13130
