### ISSUE TITLE
Some settings are no longer applicable

### ISSUE THREAD

**Issue by ceaton001** [MicrosoftDocs/microsoft-365-docs#7703]
This page lists settings for Browser Start pages and Enterprise mode site list, but these do NOT apply to Edge Chromium, just legacy Edge. [MMD switched to Edge Chromium]. Similarly, the Browser Policy CSP does not apply to Edge Chromium.
Suggest add a note to this effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0315d53-eecd-026d-9577-d772868a4265
* Version Independent ID: 9a24c435-e123-9498-33c9-59f91ca2265e
* Content: [Configurable settings reference for Microsoft Managed Desktop - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/working-with-managed-desktop/config-setting-ref?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/working-with-managed-desktop/config-setting-ref.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/working-with-managed-desktop/config-setting-ref.md)
* Service: **m365-md**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by tiaraquan** [comment]
@ceaton001 Thank you for your feedback. I am working with the team to address the issue.

**Comment by tiaraquan** [comment]
Added a note to this page to address this issue. It is included in https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/13130
