### ISSUE TITLE
Dead link (Verizon CDN)

### ISSUE THREAD

**Issue by tomppah** [MicrosoftDocs/microsoft-365-docs#7704]
For Azure CDN from Verizon (Edgecast) you can find an exhaustive list using [https://docs.microsoft.com/rest/api/cdn/edge-nodes/list](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/rest/api/cdn/edge-nodes/list) (click Try It ) - you will need to look specifically for the Premium_Verizon section. Note that this API shows all Edgecast IPs (origin and Anycast). Currently there isn't a mechanism for the API to distinguish between origin and Anycast.

<-- This link is dead, returns 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b783ee-9449-56db-3abd-f17dcf6b5d54
* Version Independent ID: d2146ff5-4248-12ec-a873-c951220aaa14
* Content: [Implementing VPN split tunneling for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Confirmed. I'm in the process of making significant revisions to this article and have corrected the link. Thank you.
