### ISSUE TITLE
Cannot see Preferences in Message Centre

### ISSUE THREAD

**Issue by dmmanderson** [MicrosoftDocs/microsoft-365-docs#7706]
[Enter feedback here]My Message Centre does not display Preferences as described.  How do I get this to show.

Mine shows  Add to Favorites      Archive     Mark as Read     Share
![Screenshot 2022-02-14 142539](https://user-images.githubusercontent.com/47195606/153956911-67ecf1c7-8ed3-4b6d-b3a8-c03491417559.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f3771a-247c-4f85-992a-e671285c70bd
* Version Independent ID: f3c2890a-2470-9349-ff77-924cf8566365
* Content: [Message center - Microsoft 365 admin](https://docs.microsoft.com/en-GB/microsoft-365/admin/manage/message-center?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/message-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/message-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@dmmanderson Thank you for your feedback. I'm able to view the preferences option in the Message center

![image](https://user-images.githubusercontent.com/45987684/154957620-fce53120-eccd-42ae-8b0e-91723f0fdc91.png)

If this is still an issue, I'd recommend you contact Microsoft support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dmmanderson Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
