### ISSUE TITLE
Is it Microsoft 365 F1 or Microsoft 365 F3 which is eligible for O365 Extra File Storage?

### ISSUE THREAD

**Issue by yasirmdar** [MicrosoftDocs/microsoft-365-docs#7707]
Is it Microsoft 365 F1 or Microsoft 365 F3 which is eligible for O365 Extra File Storage? The page lists M365 F1 but not M365 F3 which is a bit strange. Can we please fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add more SharePoint storage to your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@yasirmdar Thank you for your feedback. F3 also has the extra file storage option, I have added details to the document and it can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7725

Thanks
Sri

**Comment by yasirmdar** [comment]
Thanks Sri - will this be updated on the MS Docs website soon?

[Logo Microsoft GIF]
Yasir Dar (he/him)
Commercial Executive
RetailCPG | Banking&FS | SMC - Corporate
Phone: +61 2 9859 3323
Email/LinkedIn: ***@***.******@***.***> | LinkedIn<https://www.linkedin.com/in/yasirdar/>
[Teams logo]Message me on ***@***.***>
This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

**Comment by msbemba** [comment]
@yasirmdar That is correct. We are waiting for the author to approve and merge the PR. It will be live once it is approved.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @yasirmdar Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
