### ISSUE TITLE
Is this a doc bug? Content search is not available for M365 business basic or sharepoint plan 2 

### ISSUE THREAD

**Issue by EdmondZhangJian** [MicrosoftDocs/microsoft-365-docs#7709]
[Enter feedback here]
Check the available plan for Content search, M365 business basic is not inculded.

----
Content search
Microsoft 365 E1 subscription
Microsoft 365 G1 subscription
Microsoft 365 F1 or F3 subscription, or F5 Security add-on
Microsoft 365 Business Premium subscription
Office 365 Education A1 subscription
Office 365 E1 subscription
---

However, per to doc below, retention policy is available to M365 business basic.

https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-governance
---
The following licenses provide the rights for a user to benefit from a Teams retention policy:

Microsoft 365 E5/G5/A5/E3/G3/A3/F3/F1, Business Basic, Business Standard, and Business Premium
Office 365 E5/G5/A5/E3/G3/A3/F3/E1/G1
---

Enduser will not be able to search the contents without Content search, even if they can hold the contents with retention policy.
Is this a doc bug? And same thing occurs to Sharepoint Plan 2 as I noticed.

Would you please check it?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562b6b1d-b0fd-0d65-9db8-37df67bd7035
* Version Independent ID: 92c4403b-0d6b-88aa-74f4-ba3b7640ad00
* Content: [Microsoft 365 eDiscovery solutions - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide#content-search)
* Content Source: [microsoft-365/compliance/ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by fdesignworks** [comment]
Click the "Microsoft 365 Small and Medium-sized Businesses" item in the left menu of "Microsoft 365 and Office 365 service descriptions" to see the files that can be downloaded as PDF files.

Microsoft 365 and Office 365 service descriptions
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library

Microsoft 365 Small and Medium-sized Businesses
https://aka.ms/M365BusinessPlans

In the content of the title "Microsoft 365 User Subscriotion Suites for Small and Medium-sized Business", in the item of "eDiscovery and auditing> Countent Search", Microsoft 365 Business Basic is checked. 

check the available plan for Content search, M365 business basic is not inculded.

https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide#content-search

Content search

- Microsoft 365 E1 subscription
- Microsoft 365 G1 subscription
- Microsoft 365 F1 or F3 subscription, or F5 Security add-on
- Microsoft 365 Business Premium subscription
- Office 365 Education A1 subscription
- Office 365 E1 subscription

Would you please check it?

**Comment by msbemba** [comment]
@EdmondZhangJian  We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7782

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @EdmondZhangJian Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
