### ISSUE TITLE
NBSP is inserted in the URL list of [mde-urls-commercial.xlsx], please fix it.

### ISSUE THREAD

**Issue by hnakamoto** [MicrosoftDocs/microsoft-365-docs#7710]
[Enter feedback here]
In the [mde-urls-commercial.xlsx] file, the text in the [E15] cell is [login.windows.net], and two "Unicode (U+00A0) NBSP" are inserted after ".net".
The proxy setting is based on the information in this sheet, and it cannot be processed properly because of the NBSP, so please fix it.
Also, please make sure that the same problem does not occur in the future.

Also, the following URLs contain Unicode (U+0020), so please fix them as well.
*.security.microsoft.com 
*.blob.core.windows.net/networkscannerstable/* 
enterpriseregistration.windows.net 
*.dm.microsoft.com 
go.microsoft.com 
definitionupdates.microsoft.com  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide#enable-access-to-microsoft-defender-for-endpoint-service-urls-in-the-proxy-server)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Yes, the owner of the file has been informed. Should be fixed soon.
