### ISSUE TITLE
Permissions for the Mail tab

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/microsoft-365-docs#7712]
What permissions are required to view items under the Mail tab? We have tried Exchange Recipient Administrator + Help Desk Administrator, but our admins receive "You don't have permissions to view this information" error. What is the least privileged role to enable users to view user mail settings in O365 Admin Center?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a56d4e-5b63-a2b8-5225-abf9d91aaf90
* Version Independent ID: 467e8269-ef0c-ee69-0c3b-74221ab06e39
* Content: [User email settings - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/office-365-user-email-settings?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/office-365-user-email-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/office-365-user-email-settings.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@itishnitsa Thank you for your feedback. If you are looking for an Admin role, then Exchange admin will be needed in order to make changes to user email settings.

Also, you can use role groups and role assignment policies as well -https://docs.microsoft.com/en-us/exchange/permissions-exo/permissions-exo#role-groups

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @itishnitsa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
