### ISSUE TITLE
Left nav linked to wrong sections

### ISSUE THREAD

**Issue by ahlaverty** [MicrosoftDocs/microsoft-365-docs#7714]
The left nav isn't clicking to the right section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34c90550-34c3-c6de-81d4-6d85a8bc3f90
* Version Independent ID: 151fb754-7bea-f489-5115-e3551db0f303
* Content: [Step 5 - Give another employee access to OneDrive and Outlook data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-5?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-5.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-5.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ahlaverty  Thank you for your feedback. The changes have been made in the backend and the document is updated now.

@yogkumgit  This can be closed.

Thanks
Sri
