### ISSUE TITLE
Can find permission under Microsoft Graph API

### ISSUE THREAD

**Issue by meiliumeiliu** [MicrosoftDocs/microsoft-365-docs#7715]
I can't find the following permission
incident.ReadWrite.All, 
incident.Read.All 
Alert.ReadWrite.All
Alert.Read.All

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d4287b-0207-5c4f-ae5b-9b0fc33d36a9
* Version Independent ID: 53fdc584-5530-cf5e-fb2c-75591bb082bf
* Content: [Access the Microsoft Defender for Endpoint APIs](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/apis-intro?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/apis-intro.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/apis-intro.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@meiliumeiliu Thank you for your feedback. I was not able to locate the below as well

incident.ReadWrite.All,
incident.Read.All
Alert.ReadWrite.All
Alert.Read.All

I'll work with the author and get back to you.

Thanks
Sri

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Email sent. Thanks

**Comment by mjcaparas** [comment]
When you go through the app creation steps, that's where you encounter the permission settings. https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-create-app-webapp?view=o365-worldwide 

Please contact support for further assistance.
