### ISSUE TITLE
M365 Reporting and "total" - is it licensed, or assigned or enabled?

### ISSUE THREAD

**Issue by Lou240** [MicrosoftDocs/microsoft-365-docs#7717]
It should be more clear on this report is the "Total Accounts" is Licensed or Assigned/Enabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be6f5c5f-874c-05a7-e633-bd46613d908e
* Version Independent ID: e0578fe4-2b3f-7659-052f-7a2cd0910b38
* Content: [Microsoft 365 Reports in the admin center - OneDrive for Business usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/onedrive-for-business-usage-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/onedrive-for-business-usage-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/onedrive-for-business-usage-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Lou240 Thank you for your feedback. I have tested and it is the total licensed users in the tenant for that particular service. For making changes to the report, I'd recommend you leave feedback directly on the Main feedback portal - https://feedbackportal.microsoft.com/

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@Lou240 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised as here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
