### ISSUE TITLE
DLP available for Teams in GCC?

### ISSUE THREAD

**Issue by rbahne** [MicrosoftDocs/microsoft-365-docs#772]
I am not seeing Teams as a DLP location in a Government Tenant, is this feature available in Government yet?
See: https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams#overview-of-dlp-for-microsoft-teams

No Guidance found here: https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc#step-4-understand-which-capabilities-are-currently-unavailable-or-disabled-by-default

If not available any guidance as to when this will be available?

Thanks,
Ryan

**Comment by mypil** [comment]
@rbahne  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@chrfox - Can you please share your insights on this issue?

Thank you.

**Comment by chrfox** [comment]
adding Dhanas Raju dhraju@microsoft.com

**Comment by chrfox** [comment]
Hi, I have no information on this issue. Closing issue
