### ISSUE TITLE
Incorrect Path

### ISSUE THREAD

**Issue by grifft709** [MicrosoftDocs/microsoft-365-docs#7720]
[Enter feedback here]
Step 3 link points to the wrong location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e2bdb60-b559-ddf3-0eec-be4943fc94fd
* Version Independent ID: 5b176c0f-6c35-a187-2ccb-53a23e154978
* Content: [Step 3 - Wipe and block a former employee's mobile device - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-3?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-3.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-3.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@grifft709 Thank you for your feedback. We are making this change in the backend and will update you once it is complete.

Thanks
Sri

**Comment by msbemba** [comment]
@grifft709 Thank you for your feedback. The changes have been made in the backend and the document is updated now.

@yogkumgit  This can be closed.

Thanks
Sri
