### ISSUE TITLE
Custom scan is a quickscan?

### ISSUE THREAD

**Issue by ruicovelo** [MicrosoftDocs/microsoft-365-docs#7726]
This page says "A custom scan is a quick scan that runs on the files and folders you specify". However, a quick scan is quick because it looks into particular path that aren't usually crowded with data. So a customscan should be described as a full scan (or simple a scan) that runs on the files and folders specified. Those folder can contain a lot of files and data. Calling it a quick scan is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72be33f7-fd1f-3b0c-00c0-8d448a2cfdd3
* Version Independent ID: 0cf78d5c-8c46-8088-36c4-70fcdaf142ff
* Content: [Schedule regular quick and full scans with Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/schedule-antivirus-scans?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/schedule-antivirus-scans.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/schedule-antivirus-scans.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@ruicovelo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7786

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ruicovelo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
