### ISSUE TITLE
This page has next to ZERO info on actually hunting with these products. 

### ISSUE THREAD

**Issue by TheMidi** [MicrosoftDocs/microsoft-365-docs#773]
It would be helpful to have some technical info on hunting here rather than just links to other product pages that don't have info about hunting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bd75f06-75c8-c8f2-e2b4-0d48c714276f
* Version Independent ID: 621789df-ce3f-d985-9a93-77a46a18a9b8
* Content: [Hunt for malware and other threats in Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/security/mtp/hunting#feedback)
* Content Source: [microsoft-365/security/mtp/hunting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/mtp/hunting.md)
* Product: **w10**
* GitHub Login: @levinec
* Microsoft Alias: **ellevin**

**Comment by mypil** [comment]
@TheMidi - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by levinec** [comment]
The links do take you to pages with hunting queries, especially this one: https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/advanced-hunting-query-language

We are also modifying this page as new experiences are coming. Closing for now.
