### ISSUE TITLE
MS Export Bug

### ISSUE THREAD

**Issue by mckadmin** [MicrosoftDocs/microsoft-365-docs#7730]
PLEASE FIX YOUR BROKEN EXPORT.

I HAVEE DONE THIS MANY TIMES ON DIFFERENT ACCOUNTS -> YOUR SITE STOPS SENDING DATA.

IT IS LATE AT NIGHT AND NO ONE IS LOGGED ON.  OUR BANDWIDTH USAGE WENT FROM 60MBITS PER SECOND TO 120 MBS/SECOND -> BECAUSE i INCREASED THE BANDWIDTH LIMIT TO DECREASE DOWNLOAD TIME.

THEN IT WENT FROM 120 MB/S TO 180 MB/S BECAUSE I INCREASED THE BANDWIDTH LIMIT.
THEN IT WENT FROM 180 MB/S TO 380 MB/S BECAUSE I INCREASED THE BANDWIDTH LIMIT.

AND IT DOWNLOADED STEADILY (380MB/S) FOR 20 MINUTES - THEN ALL BANDWIDTH FROM MS STOPPED.
AGAIN.

IT DOESN'T MATTER WHEN I DOWNLOAD OR HOW FAST THE CONNECTION IS -> MS *STOPS* SENDING.

IT DOESN'T MATTER WHICH PC OR SERVER I USE TO DOWNLOAD - > MS *STOPS* SENDING.

FOR THE LOVE OF GOD FIX YOUR CRAP DOWNLOADS.

CONTENT EXPORT - WHICH ALSO FORCES ME TO USE EDGE 
OR INTERNET EXPLORE -> ARE YOU KIDDING?  INTERNET EXPLORER?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f612d934-0811-53ad-14b9-e4d44eca9448
* Version Independent ID: 284b8ae6-51d5-7571-3f70-7824e34f94a8
* Content: [Export Content search results - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-search-results?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/export-search-results.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-search-results.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mckadmin Please open a ticket with MS Support so they can investigate.
