### ISSUE TITLE
Need sample message that will be displayed to IE11 user.

### ISSUE THREAD

**Issue by TomonoriAbe** [MicrosoftDocs/microsoft-365-docs#7732]
[Enter feedback here]
In this page, there's option to notify IE11 users to update their browsers to Edge. However, Admin cannot imagine what message/notification will be displayed or delivered to IE11 user. The admin will use these sample to decide they will enable this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f954abb9-d978-b70d-c136-623a76317ddc
* Version Independent ID: d4a88bcd-ac54-ca82-9b9a-0e22da92b74b
* Content: [Microsoft 365 Reports in the admin center - Microsoft browser usage - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/browser-usage-report?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/browser-usage-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/browser-usage-report.md)
* Service: **o365-administration**
* GitHub Login: @sarahwxy
* Microsoft Alias: **waxiaoyu**

**Comment by msbemba** [comment]
@TomonoriAbe Thank you for your feedback. I was able to test it and below is the notification

The Internet Explorer 11 desktop application will be retired and go out of support on June 15, 2022 (for a list of what's in scope, [see the FAQ](https://aka.ms/IEModeFAQ)). The same IE11 apps and sites you use today can open in Microsoft Edge with Internet Explorer mode. [Learn more here](https://aka.ms/IEModeBlog).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @TomonoriAbe Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
