### ISSUE TITLE
Default audit log retention policy

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#7733]
Hello,

About the **Note**:

"The default audit log retention policy only applies to audit records for activity performed by users who are assigned an Office 365 or Microsoft 365 E5 license or have a Microsoft 365 E5 Compliance or E5 eDiscovery and Audit add-on license. If you have non-E5 users or guest users in your organization, their corresponding audit records are retained for 90 days."

Not really clear the coverage, as an example, I have a tenant with 2000 users, all users run MS 365 E3. Now, if I will buy a 1x license MS 365 E5 for myself, I will be able to create a retention policy for 1 year. This policy will cover all tenant users or only my account?

Asking because later there is a message in the doc:

"To retain an audit log for longer than 90 days (and up to 1 year), the user who generates the audit log (by performing an audited activity) must be assigned an Office 365 E5 or Microsoft 365 E5 license or have a Microsoft 365 E5 Compliance or E5 eDiscovery and Audit add-on license. To retain audit logs for 10 years, the user who generates the audit log must also be assigned a 10-year audit log retention add-on license in addition to an E5 license."

Reading this makes me feel that I don't need to license all users, only 1x user who will generate the audit log.
And FYI I could create a retention policy running mid-size tenants using Microsoft 365 Business Premium license.

Also could you please update the text in Note, suspecting it should be "Office 365 E5" instead of "Office 365"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@lightupdifire Thanks for question. I think the confusion may be in how we state this: "...the user who generates the audit log (by performing an audited activity)." What we mean is that to retain an audit record for 1 yr, the user who performs an activity that triggers an audit record to be created must be licensed with E5. For example, to save audit records for Exchange mailbox activities or SP file activities for 1 yr, the users who perform those activities must have E5 or add-on licenses. The admin who creates and audit log retention policy doesn't need an E5 license to create it. So in your scenario, to save audit records for 1 yr for 2000 users, those 2000 users would need E5 add-on licenses. Therefore, the answer to your question ("This policy will cover all tenant users or only my account?)" is that only the audit records that result from activities that you perform will be retained for 1yr.  

Hope this helps. I can look into making this more clear in the documentation, and will update to "Office 365 E5 or Microsoft 365 E5".
