### ISSUE TITLE
effect in other systems

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#7735]
Please provide some information about how these tags can be leveraged in other systems, specifically Microsoft Sentinel and Azure AD Conditional Access policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 299b59ef-e964-9f80-c48d-8d8014427a08
* Version Independent ID: 9122e30d-beb6-318c-610e-e879fd583a15
* Content: [Security recommendations for priority accounts in Microsoft 365, priority accounts, priority accounts in Office 365, priority accounts in Microsoft 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/security-recommendations-for-priority-accounts?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/security-recommendations-for-priority-accounts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/security-recommendations-for-priority-accounts.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
