### ISSUE TITLE
wording correction

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#7736]
Step 2 states - click Create Simulation, it should state Create automation (this is what is shown in the UI)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6be692e7-40f2-87ae-56b6-680a32f1024f
* Version Independent ID: 6be692e7-40f2-87ae-56b6-680a32f1024f
* Content: [Simulation automations for Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-simulation-automations?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-simulation-automations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-simulation-automations.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DeanGross, fixed.

In the future, you too can make updates like this yourself. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing.
