### ISSUE TITLE
Encrypt and Do Not Forward enabled in both OME and MIP

### ISSUE THREAD

**Issue by wcneumann219** [MicrosoftDocs/microsoft-365-docs#7739]
How about adding an explanation about how to use OME Do Not Forward and Encrypt along with Sensitivity Labels that include encryption and do not forward rights. OME has to be used if one wants an external recipient to read the encrypted contents because an email Sensitivity Label with encryption can only be read by users that have an Azure AD account.

I believe it's a little tricky to get this working properly. Getting both to coexists may depend on which capability gets enabled first, i.e., OME then Sensitivity Labels or the reverse.

If I'm correct you might also want to develop a new article that better explains the classic scenarios under which one may want to use OME for securing emails sent to external recipients and Sensitivity Labels and encryption when the recipients all have Azure AD accounts--and how to configure your environment to support these. Right now, it's REALLY HARD to figure that out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message Encryption FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.yml)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@wcneumann219 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
