### ISSUE TITLE
TenantID for partner use?

### ISSUE THREAD

**Issue by dyerseve** [MicrosoftDocs/microsoft-365-docs#774]
Is there any way to apply this from a partner admin account? Typically a -TenantId parameter is used. We manage many small businesses that do not do their own administration or purchasing so applying this to all the tenants manually is quite involved. It could be scripted but it's not very convenient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by michaelcurnutt** [comment]
Thank you for your feedback and comment.

At this point we don't support the -TenantID parameter, but we will consider this for future releases.

**Comment by rsoakford** [comment]
I agree with @dyerseve that this would be a helpful addition - duly suggested at https://office365.uservoice.com/forums/600781-microsoft-invoicing/suggestions/39983071-update-mscommerceproductpolicy-to-include-customer
