### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by oilerhead** [MicrosoftDocs/microsoft-365-docs#7746]
In this section:https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-learn-about?view=o365-worldwide#sensitive-information-types-are-used-in

Insider Risk Management is listed twice

![image](https://user-images.githubusercontent.com/15676809/154577942-a59297a3-64fd-4fb6-aab9-8f53c31c0693.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1edffc-5d5e-8ed8-a7d1-7467fb14b3d1
* Version Independent ID: 13a701b4-3dfa-2b1b-2ff2-445183a1f1eb
* Content: [Learn about sensitive information types - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-learn-about?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitive-information-type-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitive-information-type-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by RAJU2529** [comment]
@oilerhead   Today evening I will fix this issue.

**Comment by msbemba** [comment]
@oilerhead Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7772

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @oilerhead Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
