### ISSUE TITLE
Correct info about when a wrapper is received

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/microsoft-365-docs#7748]
[Hello, just read this _"Recipients of encrypted messages who receive encrypted or rights-protected mail sent to their Outlook.com, Gmail, and Yahoo accounts receive a wrapper mail that directs them to the OME Portal where they can easily authenticate using a Microsoft account, Gmail, or Yahoo credentials"._ and Outlook.com shouldn't be there. The experience is seamless with a Microsoft account as actually already mentioned in the article!, thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23994166-5118-02ea-c398-49099e5e03f3
* Version Independent ID: 4954d005-4bf2-246d-ac43-a7660c62add5
* Content: [Message Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@ChristianJBergstrom Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7784

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChristianJBergstrom Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
