### ISSUE TITLE
Microsoft Defender for office 365 Power Automate

### ISSUE THREAD

**Issue by robarismail97** [MicrosoftDocs/microsoft-365-docs#7749]
Hello,

Is it possible to create a flow (or with some other solution) to automatically send email notification to recipients that Mdfo365 has created an alert on. So the recipient can get an email that they have clicked on an malicious url in a email.

Name of the alert: "A potentially malicious URL click was detected"

Br,
Robar

**Comment by yogkumgit** [comment]
@robarismail97 Please indicate which document you are referring to. Thanks

**Comment by robarismail97** [comment]
> @robarismail97 Please indicate which document you are referring to. Thanks

Thank you for the comment. The document I'm refering to is this:  https://docs.microsoft.com/sv-se/microsoft-365/security/defender-endpoint/api-microsoft-flow?view=o365-worldwide

**Comment by msbemba** [comment]
@robarismail97 Thank you for your feedback. Yes, It is possible using flow, however, this is handled by the support team. You can contact Microsoft support via the need help section on the M365 admin center and a support engineer will be able to assist you with this.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @robarismail97 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
