### ISSUE TITLE
The article does not have a link to new PowerShell modules

### ISSUE THREAD

**Issue by TheSharePointProfessional** [MicrosoftDocs/microsoft-365-docs#775]
The article does not have a link to new PowerShell modules

_Originally posted by @TheSharePointProfessional in https://github.com/MicrosoftDocs/microsoft-365-docs/issues/768#issuecomment-555698276_

**Comment by mypil** [comment]
@TheSharePointProfessional - Thank you for submitting feedback.

If you mean the link for  Use AllowSelfServicePurchase for the MSCommerce PowerShell module as seen in the screen shot from the doc below, I actually checked and confirmed that it is working. 

![image](https://user-images.githubusercontent.com/47188252/69250350-7a47cc80-0bea-11ea-9d82-b72769077dc1.png)

Is this what you were referring to? Or is it something else? Kindly provide more details.

**Comment by mypil** [comment]
@TheSharePointProfessional - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
