### ISSUE TITLE
Additional Note recommended for Supervised Devices Without User Affinity

### ISSUE THREAD

**Issue by RichardGallo-MS** [MicrosoftDocs/microsoft-365-docs#7756]
Hi there! 

Working with a customer recently, we learned that zero-touch cannot be configured on iOS devices that are enrolled without user affinity. I think it would be super helpful if we could make a note of that, so a customer doesn't spend a lot of time troubleshooting a scenario that isn't supported yet.

Thanks so much!!

-Rich Gallo, Customer Engineer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [App-based deployment for Microsoft Defender for Endpoint on iOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide&source=docs#zero-touch-onboarding-of-microsoft-defender-for-endpoint-preview)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@RichardGallo-MS Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7783

Once the author approves, changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @RichardGallo-MS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
