### ISSUE TITLE
404\Not Found

### ISSUE THREAD

**Issue by Helix-DB3** [MicrosoftDocs/microsoft-365-docs#7760]
[Invalid(404)](https://github.com/sessions/verified-device) 
#
![Screenshot_20220218-060944](https://user-images.githubusercontent.com/96703991/154824728-20a37a5c-e930-4a7e-95c7-67e7392e693e.png)

 #7759

**Comment by msbemba** [comment]
@Helix-DB3 Thank you for your feedback. Could you please provide more details about the document that you are referring to? The link provided is for https://github.com/sessions/verified-device and is not managed by Microsoft.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@AlexJerabek The document https://docs.microsoft.com/en-us/legal/microsoft-365/ios-terms?view=o365-worldwide is already updated with the wordings - "Microsoft Defender for Endpoint on iOS application license terms"

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Helix-DB3 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
