### ISSUE TITLE
Translation issue for Japanease article

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/microsoft-365-docs#7762]
Hello community, 

I found a translation error in the reference to the impact of the M365 licenses removal for OneDrive for Business.
In the current description, the location  in the sentence the of "Microsoft 365 admin center" and "OneDrive for Business" are reversed.

Could you please revise the explanation as it is very important information regarding the retention of customer data?

https://docs.microsoft.com/ja-jp/microsoft-365/admin/manage/remove-licenses-from-users?view=o365-worldwide#what-happens-to-a-users-data-when-you-remove-their-license

![image](https://user-images.githubusercontent.com/13634805/154885645-4a940001-01ce-45f6-b2c8-ec000916467d.png)

Suggestion
-----------
ユーザーが Microsoft 365 管理センターや Acitive Directory 同期によって削除されない限り、OneDrive for Business に保存されたファイルは削除されません。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d850211-99b4-faf7-09fc-4621919dd74b
* Version Independent ID: 9b294f13-b1e3-291e-25a1-75f7c5755b6c
* Content: [Unassign licenses from users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/remove-licenses-from-users?view=o365-worldwide#what-happens-to-a-users-data-when-you-remove-their-license)
* Content Source: [microsoft-365/admin/manage/remove-licenses-from-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/remove-licenses-from-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@TinaMcN Please help us in resolving this issue. Thanks

**Comment by TinaMcN** [comment]
@kefujino thank you very much for reporting this issue.  It's seems to be a bug with the machine translation.   I sent the article to be translated by a human which will take 2-3 days.

**Comment by TinaMcN** [comment]
@kefujino the article has now been human translated.   Can you please confirm if the translation is ok now?
![image](https://user-images.githubusercontent.com/53281468/155760093-7e65d1d9-1e4a-4f2a-856c-43719140174f.png)

**Comment by kefujino** [comment]
@TinaMcN Thank you for your follow-up. Current traslation is very nice!
Could you close this ticket? thank you so match.

**Comment by TinaMcN** [comment]
@kefujino thank you for confirming the translation is ok now 👍 @yogkumgit can you please close the issue, I don't have access.
