### ISSUE TITLE
Order of operations is wrong - delete user should not be first

### ISSUE THREAD

**Issue by SCJDigital** [MicrosoftDocs/microsoft-365-docs#7764]
[Enter feedback here]
As the title says - following the order of events on the page is literally not possible as deleting the used prevents most of the following steps from working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@SCJDigital Thank you for your feedback. You are correct, deleting the user is in fact the last step. 

Step 1 - Prevent a former employee from logging in and block access to Microsoft 365 services
Step 2 - Save the contents of a former employee's mailbox	
Step 3 - Wipe and block a former employee's mobile device
Step 4 - Forward a former employee's email to another employee or convert it to a shared mailbox
Step 5 - Give another employee access to OneDrive and Outlook data
Step 6 - Remove and delete the Microsoft 365 license from a former employee
**Step 7 - Delete a former employee's user account**

Although we've numbered the steps in this solution and you don't have to complete the solution using the exact order, we do recommend doing the steps this way.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SCJDigital if you have any feedback or recommendation please feel free to reopen this issue . We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by SCJDigital** [comment]
Hi, thanks for the recommended order of events @msbemba. 

@yogkumgit the page https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide still has the original misleading event sequence issue: Step 1 & 2, a video and the "Before You Begin" all suggest "Delete a User" before operations that will no longer be possible after deleting a user, so I would not call this solved.

**Comment by msbemba** [comment]
@SCJDigital This document is an overview and talks about things you could do before you delete a user (video).

"When an employee leaves the company, you'll need to remove them from Microsoft 365 for business. Before doing so, you should block them from accessing company files, preserve the documents they created, and perform several other admin tasks associated with removing a user."

The steps are mentioned in the recommended order. 

Thanks
Sri

**Comment by msbemba** [comment]
@SCJDigital Thank you for your response. I have moved the delete user section to the bottom of the screen (after the steps) so that it reduces ambiguity.
This change can be tracked via PR# https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7874

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SCJDigital Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DocfunQ** [comment]
Will Step 3 work if you do step 1.   

Step 1 - Prevent a former employee from logging in and block access to Microsoft 365 services
Step 3 - Wipe and block a former employee's mobile device
