### ISSUE TITLE
Update image to reflect changes in steps

### ISSUE THREAD

**Issue by JeroenOortwijn** [MicrosoftDocs/microsoft-365-docs#7766]
This is a follow-up on issue #7675.

In PR #7676, the steps on this page got reordered.
The [image](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/9f0e84835121ce6228fdc69182c24be7ad1cb20e/microsoft-365/media/delete-user-account.png) on this page needs to be updated to reflect this new order of steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide#solution-remove-a-former-employee)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@JeroenOortwijn Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7929

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JeroenOortwijn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
