### ISSUE TITLE
egacy sharepoint admin center no longer available

### ISSUE THREAD

**Issue by andrewwoo0902** [MicrosoftDocs/microsoft-365-docs#7767]
[Enter feedback here]
Legacy sharepoint admin center no longer available

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29df28b-0065-a059-f22d-3433c1dd65a0
* Version Independent ID: 83b44475-2a39-5747-fc3c-2a92d0d958f2
* Content: [Set up Information Rights Management (IRM) in SharePoint admin center - Microsoft 365 Compliance](https://docs.microsoft.com/en-gb/microsoft-365/compliance/set-up-irm-in-sp-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-irm-in-sp-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-irm-in-sp-admin-center.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@andrewwoo0902 Thank you for your feedback. I can confirm that the legacy SharePoint admin center is no longer available. The fw link(https://go.microsoft.com/fwlink/?linkid=2185219) on the article for the SharePoint admin center has been updated to reflect the new SharePoint admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @andrewwoo0902 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
