### ISSUE TITLE
New location for this applet?

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/microsoft-365-docs#777]
Has mail-flow insights been deprecated?  We can't find it in the new Security Center or Compliance Center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ecd274-2094-7733-88b8-e422ebe95406
* Version Independent ID: e94b3b1d-da6a-469a-45e7-eba5e9694971
* Content: [Mail flow insights in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/mail-flow-insights-v2#feedback)
* Content Source: [microsoft-365/security/office-365-security/mail-flow-insights-v2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mail-flow-insights-v2.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@FC-EricWeller, they should be in the Security & Compliance Center: https://protection.office.com/

**Comment by FC-EricWeller** [comment]
Thanks Chris,
I'm sorry I may have been unclear.  I'm aware the feature is _currently_ located under Security and Compliance Center, but it is NOT located under Security Center, or Compliance Center, which are replacing it.  

In truth, I think I had intended to [post this question there.](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/microsoft-security-and-compliance)

**Comment by mypil** [comment]
@FC-EricWeller - From our understanding, the issue you raised has been answered by chrisda. If you feel it hasn't been answered, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
