### ISSUE TITLE
Typo in 'Administrative portal' concept description

### ISSUE THREAD

**Issue by LegalDrokz** [MicrosoftDocs/microsoft-365-docs#7771]
At the 'Administrative portal' Concept section, the Description says:

In addition to the Microsoft 365 Defender portal, the Defender for Identity portal _cab_ be used to monitor and respond to suspicious activity.

I assume that 'cab' here needs to be 'can'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e343a8b-3083-572d-80e1-2feb2a213395
* Version Independent ID: 491cc94c-5b38-b9ec-f4cc-97711c8621a0
* Content: [Review architecture requirements and the technical framework for Microsoft Defender for Identity](https://docs.microsoft.com/en-us/microsoft-365/security/defender/eval-defender-identity-architecture?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/eval-defender-identity-architecture.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/eval-defender-identity-architecture.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by RAJU2529** [comment]
@JoeDavies-MSFT,   please merge this #7773, if it is correct.

**Comment by yogkumgit** [comment]
@LegalDrokz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
