### ISSUE TITLE
What happens if you tag content after creating the event?

### ISSUE THREAD

**Issue by cablechewer** [MicrosoftDocs/microsoft-365-docs#7779]
[Enter feedback here]
I have had several customers create an event, and then continue tagging items after the event was created.  They expect the policy will act on those documents just like it did on the ones that were present at the time of the event's creation.  AFAIK this isn't how it acts.  A new event has to be created to trigger retention on the documents that were tagged after the event.  
For example a customer creates the policy and tags 500 items.  It has a 1 day delete.  Then on Dec 31, 2021 they create an event for that day.  3 weeks later they start applying the same label to additional documents expecting them to be deleted because Dec 31, 2021 was more than 1 day ago.

If my understanding is correct we need a note in the article explaining how those documents get handled.  I don't know who the PM is, but we might need to consult them to get the final answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad33cc1-dc5f-d9f9-ee8e-b103839945ef
* Version Independent ID: 1bc3101d-afe8-2056-3cda-6a86a209c460
* Content: [Start retention when an event occurs - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
@cablechewer  Yes, you're quite right & this is stated in this article: "After creating an event, the retention settings take effect for the content that's already labeled and indexed. If the retention label is added to new content after the event is created, you must create a new event with the same details."

No need to create a new note for something that's already covered in this article, closing this issue.

**Comment by cabailey** [comment]
@yogkumgit  The requested information is already on the page - no doc enhancement needed here.
