### ISSUE TITLE
Settings not available in new Exchange Admin center

### ISSUE THREAD

**Issue by Adamance** [MicrosoftDocs/microsoft-365-docs#7790]
The steps detailed on this page have become outdated since the rollout of the new Exchange admin center, as group email delegation settings are still only available in the Classic Exchange Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b725ac58-0fa5-9f7d-84fa-a8541477fe0e
* Version Independent ID: f2acd0d0-60b8-0744-e241-06fb753aa5d1
* Content: [Allow members to send as or send on behalf of a group](https://docs.microsoft.com/en-us/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Adamance Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7927

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Adamance Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
