### ISSUE TITLE
I cannot open the MECM Management Console

### ISSUE THREAD

**Issue by Realkdrummer** [MicrosoftDocs/microsoft-365-docs#7793]
I cannot open the MECM Management Console

Hello,

I recently downloaded and set up (supposedly) the Windows and Office 365 deployment lab kit.  I can open and log into the CMI Virtual Machine.  As the MECM server, I tried to open the Management Console with no luck. According to the setup instructions, the MECM server's FQDN is CM1.corp.contoso.com. When the console does not open, I am prompted for the name of the Site server.  I am prompted for the FQDN of the MECM server. I enter it click Connect and nothing happens. How can I resolve this since I have a short period of time to work with the environment? Is it possible that I downloaded the kit just before the expire date listed on the Windows and Office 365 deployment lab kit home page? Is there someone I can speak to directly/share my screen with them?

What is the best way to approach this?

Thank you,

Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by msbemba** [comment]
@Realkdrummer Thank you for your feedback. This request needs to be handled by our Microsoft support engineers who can work with you over phone/email. You can create a ticket using the need help section on the M365 admin center and one of the support engineers will work with you.

Hope this helps!

Thanks
Sri

**Comment by Realkdrummer** [comment]
The Windows and Office 365 deployment lab kit is free. Are you saying that
I have to download M365 or Office 2021 in order to get into the M365 Admin
center if I have questions about the free lab? If I do that, after 30 days,
I will be charged.  I already have a Microsoft account that I use to get
into the Azure portal to work on VMs to learn MECM.  I am already paying
for that.

I need clarity on the procedure.

Thank you,
*Kevin Newton*

**Comment by msbemba** [comment]
@Realkdrummer Thank you for the response. There are multiple options to contact support. 

1)  https://support.microsoft.com/oas - using a Microsoft account that you use.
2) Portal.azure.com - Create a ticket from the support section
3) M365 admin center (for this you need an account in M365)

We handle the documentation edits, for any product support or technical queries it needs to be handled by the Support team.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Realkdrummer Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
