### ISSUE TITLE
https://demo.wd.microsoft.com/ - This site will be decommissioned on 03/15/2022

### ISSUE THREAD

**Issue by iSazonov** [MicrosoftDocs/microsoft-365-docs#7800]
> Download the [Evaluation Package](https://aka.ms/mp7z2w) and extract the file cfa-events.xml to an easily accessible location on the device.

The link warn "This site will be decommissioned on 03/15/2022". Please update docs with new link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fb0d02-ceff-61d8-3041-13df9513769a
* Version Independent ID: 7c98a316-de58-520a-a6ad-06ddaf0d71b3
* Content: [Protect important folders from ransomware from encrypting your files with controlled folder access](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/controlled-folders.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@iSazonov Thank you for your feedback. You are correct, This site to download the evaluation package will be decommissioned on 03/15/2022. There is no replacement link available as of now. For feedback, please email [mdedemositefeedback@microsoft.com](mailto:mdedemositefeedback@microsoft.com) We will update the document once it is made available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @iSazonov Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
