### ISSUE TITLE
Please allow export/query of Exposure Score over Time

### ISSUE THREAD

**Issue by sebhurleyhte** [MicrosoftDocs/microsoft-365-docs#7808]
Related Feature: https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tvm-exposure-score.md

Can we have the feature to download the "Exposure Score over time" data - either directly or via KQL? This is a useful report for demonstrating at a high level the impact being made as new vulnerabilities appear.

![Screenshot 2022-02-24 093621](https://user-images.githubusercontent.com/48723852/155499945-4a5294ab-730a-496d-94f6-6de449283b7f.png)

**Comment by msbemba** [comment]
@sebhurleyhte Thank you for your feedback. Since you are requesting a new feature, I'd recommend you provide this feedback directly on our Main feedback portal - https://feedbackportal.microsoft.com/, So that someone will be able to contact you to take this forward.

Thanks
Sri

**Comment by yogkumgit** [comment]
@sebhurleyhte Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised as here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
