### ISSUE TITLE
Review attack surface reduction events in Windows Event Viewer

### ISSUE THREAD

**Issue by MatteoC5** [MicrosoftDocs/microsoft-365-docs#7810]
In the section "Review attack surface reduction events in Windows Event Viewer" controlled folder access is mentioned few times,
am I wrong or could it be that we are referring to the ASR rules?

Thank you

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@MatteoC5 Thank you for your feedback. I hope you are referring to https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide. If yes, all are related to controlled folder access.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MatteoC5 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
