### ISSUE TITLE
Instructions to install January 2017 SCEP update can't be followed

### ISSUE THREAD

**Issue by James-Noble** [MicrosoftDocs/microsoft-365-docs#7811]
In the section:
Install the [January 2017 anti-malware platform update for Endpoint Protection clients](https://support.microsoft.com/help/3209361/january-2017-anti-malware-platform-update-for-endpoint-protection-clie)

That page doesn't give a KB or any download link, it just says to get it from Microsoft Update.  I've searched Microsoft update for "January 2017", "SCEP", "Endpoint protection", "Anti-malware" and this update doesn't appear.  The only other way I could get it would be to enable it on our WSUS but it isn't clear what product is required to get it.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3985e3b-6df1-892c-be7c-8b1f079b4053
* Version Independent ID: 61fee405-9ccd-cf53-4aa1-4c5e98f09cf7
* Content: [Onboard previous versions of Windows on Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-downlevel?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-downlevel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-downlevel.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks
