### ISSUE TITLE
Nowhere does any documentation explain the correct method of setting Defender to ACTIVE mode.

### ISSUE THREAD

**Issue by rykerabel** [MicrosoftDocs/microsoft-365-docs#7813]
Nowhere does any documentation explain the correct method of setting Defender to ACTIVE mode.
This is a HUGE security vulnerability.
(don't say "delete the registry key" because we have over 30,000 computers that have this key and again, there is no Group Policy for this setting or at least no documentation lists one)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881d2840-25a7-0f80-c62c-9240680314e2
* Version Independent ID: 881d2840-25a7-0f80-c62c-9240680314e2
* Content: [Troubleshooting issues when switching to Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-mde-troubleshooting?view=o365-worldwide#microsoft-defender-antivirus-is-getting-uninstalled-on-windows-server)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-mde-troubleshooting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-mde-troubleshooting.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
Duplicate #7812 Closing
