### ISSUE TITLE
eDiscovery support for .whiteboard files?

### ISSUE THREAD

**Issue by dendave** [MicrosoftDocs/microsoft-365-docs#7819]
[Enter feedback here]
Hi,
soon MS whiteboard files will be stored on OneDrive for Business. 
Based on [this article](https://support.microsoft.com/en-us/office/microsoft-whiteboard-on-onedrive-for-business-opt-in-4cc65aa7-812a-4c7c-a50f-991274106286) Whiteboard files will get extensions .whiteboard.
Will Advanced eDiscovery also support .whiteboard files? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ade4c29-acc7-5d40-4112-bc18d6e31f40
* Version Independent ID: 05836f9b-3824-9dec-dac7-525270d66e28
* Content: [Supported file types in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/supported-filetypes-ediscovery20?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/supported-filetypes-ediscovery20.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/supported-filetypes-ediscovery20.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@dendave Initially Advanced eDiscovery won't support .whiteboard files but will support them sometime in the future. When that happens, there should be a roadmap item announcing that support.
