### ISSUE TITLE
Shared Channel Guidance Request

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#7820]
Please add some guidance about how we should include the new Shared Channels in Teams in this tiered model. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4734515e-5940-7ddd-48ac-807a1515d7f5
* Version Independent ID: 22873fc9-27f2-35b2-7441-044a7e00372c
* Content: [Configure Teams with three tiers of file sharing security](https://docs.microsoft.com/en-us/microsoft-365/solutions/configure-teams-three-tiers-protection?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/configure-teams-three-tiers-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/configure-teams-three-tiers-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@DeanGross, shared channels documentation updates will be published when shared channels is released for public preview.

**Comment by yogkumgit** [comment]
@DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
