### ISSUE TITLE
Sub-bullets under Actions/implementationType should be indented

### ISSUE THREAD

**Issue by cimares** [MicrosoftDocs/microsoft-365-docs#7822]
The sub-bullets of Operational, Technical and Documentation should be indented to show that they are values under the column implementationType. As it reads currently, they show as additional column headers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1fcab7e-6aec-21d1-707e-08bec1ec5412
* Version Independent ID: b51687ce-381a-8e5c-3188-02b0351a31e8
* Content: [Format assessment template data in Excel for Microsoft Compliance Manager - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-templates-format-excel?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-manager-templates-format-excel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-templates-format-excel.md)
* Service: **o365-seccomp**
* GitHub Login: @jmgriffee
* Microsoft Alias: **v-jgriffee**

**Comment by msbemba** [comment]
@cimares Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7875

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cimares Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
