### ISSUE TITLE
The sample file itself fails validation with "Action template not inserted correctly"

### ISSUE THREAD

**Issue by cimares** [MicrosoftDocs/microsoft-365-docs#7823]
After unsuccessfully writing my own template based on this article, I decided to change the certification field to ensure no clash, and then upload the Sample file as is.

A pop-up appears status "Action template not inserted correctly" with the following diagnostic information availabe: Diagnostic information: {Version:17.00.8006.006,Environment:WEUPROD,DeploymentId:a9d3e4c565b24eaba08f153fd4a0a947,InstanceId:WebRole_IN_9,SID:3242a124-84a6-4421-addc-86ad4f1d2116,CID:e4b5dc50-2f8a-4b30-9658-acb0073ccc03}
Time: Fri, 25 Feb 2022 18:04:15 GMT

The main screen shows "Validation could not be completed. if the issue persists please contact your administrator" ...which would be me... 8)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1fcab7e-6aec-21d1-707e-08bec1ec5412
* Version Independent ID: b51687ce-381a-8e5c-3188-02b0351a31e8
* Content: [Format assessment template data in Excel for Microsoft Compliance Manager - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-templates-format-excel?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-manager-templates-format-excel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-templates-format-excel.md)
* Service: **o365-seccomp**
* GitHub Login: @jmgriffee
* Microsoft Alias: **v-jgriffee**

**Comment by msbemba** [comment]
@cimares Thank you for your feedback. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information that’s provided at [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cimares Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
