### ISSUE TITLE
Declare the time it takes for change in categories to reflect on clients

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/microsoft-365-docs#7824]
this page does not indicate how long it will take for a change in categories to appear on a cliemt device. I have had to wait getting on for 2 hours which is ridiculous. Can you indicate how this can be speeded up? can you detail exactly how long it takes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbaaa90e-6975-ee29-335a-545cb6a55986
* Version Independent ID: 75c93c17-4952-a13f-ed60-d2baefd0337e
* Content: [Web content filtering](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-content-filtering?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-content-filtering.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@chiners68 Thank you for your feedback. We have added information to the document to state that **The policy refresh might take up to 2 hours to apply to your selected devices.**. Unfortunately this cannot be speeded up for now.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @chiners68 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
