### ISSUE TITLE
Double up on text 

### ISSUE THREAD

**Issue by pjbisset** [MicrosoftDocs/microsoft-365-docs#7828]
[Enter feedback here]
4th paragraph down from the top under "Applies to" has doubled up text.

"Admins in organizations with Microsoft Defender for Office 365 can also manage files that were **quarantined by quarantined by** ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an admin - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@pjbisset Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7835

Thanks
Sri

**Comment by chrisda** [comment]
@pjbisset, thanks for the feedback. In the future, you, too can make changes like this directly. No need to open an issue first. For instructions, see:

 <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>
