### ISSUE TITLE
Missing closing parenthesis 

### ISSUE THREAD

**Issue by irideostriches** [MicrosoftDocs/microsoft-365-docs#7829]
In the list of operators, 'like' and 'not like' both are missing the closing parenthesis for '(String Comparison)' 

https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide#:~:text=like%20(string%20comparison,notlike%20(string%20comparison

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 592d6717-d670-14a8-acbe-c648958ca208
* Version Independent ID: 9bc46fd9-50e1-1e58-4852-22068e2980ae
* Content: [Configure retention settings to automatically retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-settings?view=o365-worldwide#settings-for-retaining-and-deleting-content)
* Content Source: [microsoft-365/compliance/retention-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@irideostriches Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7836

Thanks
Sri

**Comment by yogkumgit** [comment]
closing as per author's input. Thanks
