### ISSUE TITLE
CAT:PHSH vs CAT:PHISH

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/microsoft-365-docs#783]
While I was inspecting some headers I found there was one header with CAT:PHISH opposed to the CAT:PHSH stated here in the documentation.
Are both valid or is only CAT:PHISH valid?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@Mr-Pingu  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by joinimran** [comment]
Hello, @Mr-Pingu Thank you for your query here. Please note there are many headers not listed in this document and they are internal and only used by Microsoft anti-spam team for diagnostic purposes.

This was also addressed in another same query. Please see https://github.com/MicrosoftDocs/microsoft-365-docs/issues/486#issuecomment-540828898

Thanks.

@mypil FYI Please.
