### ISSUE TITLE
Please add comment how  ADAL EOS on Jun. 30 2022 affects on Office 2013 in which MSAL is not supported

### ISSUE THREAD

**Issue by aikoitoms** [MicrosoftDocs/microsoft-365-docs#7830]
[Enter feedback here]
Please add comment how  ADAL EOS on Jun. 30 2022 affects on Office 2013 in which MSAL is not supported.  I've received an question from customer if Modern Authentication cannot be used in Office 2013 after ADAL EOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3a343-4140-e63d-5197-06cafdab4639
* Version Independent ID: 12cf7dda-2caf-0fe2-1564-a14dea00d46f
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-auth-for-office-2013-and-2016?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MSFTTracyP Please help us in resolving this issue. Thanks

**Comment by SaeedAkhter-MSFT** [comment]
> can Modern Authentication be used in Office 2013 after ADAL EOS?
The ADAL end of life announcement is in regards to support tickets and patches for security vulnerabilities.  The Azure AD endpoint is "standards-protocol complaint", and there will be no server-side change that will block an ADAL client or any other client using standards-based protocols.  This is more about expectation that there will be no new releases of ADAL even in the case of an security vulnerability.

Also, please note that ADAL end-of-life has been extended to Dec 2022:
https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-get-list-of-all-active-directory-auth-library-apps

**Comment by yogkumgit** [comment]
@aikoitoms Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
