### ISSUE TITLE
"Add Exclusions" section could be improved

### ISSUE THREAD

**Issue by SpitFire-666** [MicrosoftDocs/microsoft-365-docs#7833]
Hi, I was expecting the doc to show me how to add exclusions, it seems to only show how to tell _what would happen_ if the current detection was added as an exclusion.

In reality, you have to go to MEM admin center, Endpoint security, select your ASR Rules, Edit configuration, scroll to the bottom and add the path(s) there. 

Perhaps the article could point us in the right direction in future? cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 498a23d9-d5b0-2c98-edfa-d9871675f5ae
* Version Independent ID: 498a23d9-d5b0-2c98-edfa-d9871675f5ae
* Content: [Test attack surface reduction (ASR) rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@SpitFire-666 Thank you for your feedback. The exclusion is a part of the implement ASR rules document. 

You can exclude files and folders, by group policy,  via PowerShell, and also using MDM CSPs to exclude files and folders.

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-implement?view=o365-worldwide#customize-attack-surface-reduction-rules

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SpitFire-666 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
