### ISSUE TITLE
No Preferences on Message Center

### ISSUE THREAD

**Issue by klishb** [MicrosoftDocs/microsoft-365-docs#7837]
Docs refer to Preferences at the top of the Message Center, but there is no Preferences to select on the page.  Possibly referring to old Message Center functionality.

https://docs.microsoft.com/en-US/microsoft-365/admin/manage/message-center?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide#preferences

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f3771a-247c-4f85-992a-e671285c70bd
* Version Independent ID: f3c2890a-2470-9349-ff77-924cf8566365
* Content: [Message center - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/manage/message-center?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/message-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/message-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@klishb Thank you for your feedback. I'm able to locate the Preferences option on multiple tenants

![image](https://user-images.githubusercontent.com/45987684/156904718-2ecf6503-75a3-4d08-855a-b10d3955bcc9.png)


If this is still an issue, I'd recommend opening a ticket with support via the need help option on the admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @klishb Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
