### ISSUE TITLE
Information Barriers on Microsoft 365 A3

### ISSUE THREAD

**Issue by rodpayne** [MicrosoftDocs/microsoft-365-docs#7840]
Information Barriers is listed under apps and services for the Microsoft 365 A3 licenses on page https://admin.microsoft.com/Adminportal/Home#/licensedetailpage/18250162-5d87-4436-a834-d795c15c80f3.  The documentation page says that it would require the Compliance add-on or the Risk Management add-on, so the documentation seems to be incorrect or out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Learn about information barriers in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@rodpayne Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7923

Once the author approves, the changes will be live.

Thanks
Sri
