### ISSUE TITLE
OneDrive for business litigation hold - after license revoked

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/microsoft-365-docs#7845]
Hi Team,

What happens to existing litigation hold on OneDrive if license is revoked? 
How to manage litigation hold after license is revoked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115cfe0b-c8b5-193d-19da-a6f9c03fdfc0
* Version Independent ID: 4a90cb9e-ce2a-a3f6-4b67-32f45c975323
* Content: [Manage holds in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/managing-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/managing-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/managing-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by jaganpt** [comment]
Hi Team,
Any update on this? 
Thanks in advance!

**Comment by markjjo** [comment]
@jaganpt  Here's some info about OneDrive retention and deletion.

https://docs.microsoft.com/en-us/microsoft-365/admin/manage/remove-licenses-from-users?view=o365-worldwide#what-happens-to-a-users-data-when-you-remove-their-license

https://docs.microsoft.com/en-us/onedrive/retention-and-deletion. In this topic, there is the following note.

Retention policies always take precedence to the standard OneDrive deletion process, so content included in a policy could be deleted before 30 days or retained for longer than the OneDrive retention. For more info, see [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies). **Likewise, if a OneDrive is put on hold as part of an eDiscovery case, managers and secondary owners will be sent email about the pending deletion, but the OneDrive won't be deleted until the hold is removed.**
**The retention period for cleanup of OneDrive begins when a user account is deleted from Azure Active Directory. No other action will cause the cleanup process to occur, including blocking the user from signing in or removing the user's license.** For info about removing a user's license, see [Remove licenses from users in Microsoft 365 for business](https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/remove-licenses-from-users).

I would suggest you open a ticket with MS Support to investigate. If you are internal MSFT, I would suggest you follow up with the ODSP engineering team or the M365 data governance team.
