### ISSUE TITLE
Wrong variable in Use the Azure Active Directory PowerShell for Graph module

### ISSUE THREAD

**Issue by vazome** [MicrosoftDocs/microsoft-365-docs#7846]
The documentation mentions two variables `License` and `license`. Which leads to zero-result after execution.
It must be only `License` or `license` in all cases 
```
$license = New-Object -TypeName Microsoft.Open.AzureAD.Model.AssignedLicenses
$License.RemoveLicenses = (Get-AzureADSubscribedSku | Where-Object -Property SkuPartNumber -Value $planName -EQ).SkuID
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22d23da-eb81-b2e5-9655-748f77b25f80
* Version Independent ID: d8b557bc-d9c4-a58e-5ece-c4c6ffbadad0
* Content: [Remove Microsoft 365 licenses from user accounts with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/remove-licenses-from-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/remove-licenses-from-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/remove-licenses-from-user-accounts-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@vazome Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7924

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @vazome Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
