### ISSUE TITLE
Reopen issue on lack of documentation on X-Microsoft-Antispam-Mailbox-Delivery

### ISSUE THREAD

**Issue by adamlavery** [MicrosoftDocs/microsoft-365-docs#7857]
See this archived issue that was never addressed: https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/442

Three years later we still can get no useful information on the decisions Microsoft email filters make about **our** emails. I get that dealing with spam and malware is difficult nowadays but this cannot be at the expense of failing to deliver normal, everyday emails. Even whitelisting is no longer working to guarantee delivery of required emails. 

Microsoft must explain what the elements that make up this header record mean, so we have an idea what we can do to stop important emails being junked. Where an email address is whitelisted and blocked from being spam-scanned, then that must be honoured and not let some other black-box piece of the filter system decide to overrule our clear instruction. Other elements of the spam decisions are reasonably well documented - why not this?

Here's an example that many have reported. The email sender has been whitelisted at the organisation level yet still mails go to junk - why? This must be explained.

**X-Microsoft-Antispam-Mailbox-Delivery:
kl:1;ucf:0;jmr:0;auth:0;dest:J;OFR:SpamFilterAuthJ;ENG:(910001)(944506458)(944626604)(920097)(825001)(250001)(930097)(3100021);RF:JunkEmail;**

We can work out that dest:J means it now destined for the junk folder. But what does OFR:SpamFilterAuthJ signify and does RF:JunkEmail mean anything? All elements need explaining along with their potential values and clear guidance on what we need to do to stop Microsoft junking these mails.

**Comment by BigAndini** [comment]
Which additional information is required to be able to document the X-Microsoft-Antispam-Mailbox-Delivery header and the possible values the different fields within this header have and which action they trigger? I would be happy to provide the information needed to have this documentation online.

**Comment by matsimon** [comment]
The issue is that somebody outside of Microsoft is quite unlikely in possession of the full specification of all values of X-Microsoft-Antispam-Mailbox-Delivery. You likely need to be working for Microsoft's Exchange team or in a position pretty close to Microsoft.

It's a pretty longstanding issue and in practise it makes debugging decisions of Exchange Online spam filter difficult for customers or users.

**Comment by adamlavery** [comment]
I raised this instance with M$ Support and after several weeks of investigation they were finally able to answer why this sample got rejected. Someone accidentally blocked the address on the shared mailbox! Result of this was that M$ were going to look at making the header more informative. Of course they don't want to give away how the filters work but in this case a clear indication it was a blocking rule that was trumping the transport allow rule should have been included.

Subsequently though, I heard that Defender 365 is set to become the "source of truth" for all block/allow rules. The issue now is that there are multiple different bits of filtering that can be doing their own thing, making controlling it difficult. A single definitive block/allow list that works throughout Exchange Online and Outlook will be welcome.

**Comment by yogkumgit** [comment]
@KCCross Please comment, if the document update is required? Thanks

**Comment by adamlavery** [comment]
Document will need updating but I think best wait until the new "source of truth" is implemented then update the doc with definitive information. Bear in mind that the document must answer the question: why is genuine mail being blocked/filtered and what do we do to fix it.

**Comment by BigAndini** [comment]
Is there already a date when the new "source of truth" will be implemented?

**Comment by RichGoldthwaite** [comment]
My company is also being plagued by this issue. Emails from our domain are landing in external recipients Junk Email Folder if the recipient is behind Exchange Online Protection. Our email reputation is great; SPF, DKIM, DMARC all passing! We also see that header in those emails: 
`X-Microsoft-Antispam-Mailbox-Delivery:
	ucf:0;jmr:0;auth:0;dest:J;OFR:SpamFilterAuthJ;ENG:(910001)(944506478)(944626604)(920097)(930097)(3100021);RF:JunkEmail;`

Can someone explain this? Its maddening and trying to work with Microsoft Support has been frustrating as this seems to be an issue that engineering needs to look into.

**Comment by yogkumgit** [comment]
@KCCross Kindly comment.

**Comment by kfasick** [comment]
I won't repost the answer but it might help some to know I asked Bing chat to help and got a better summary of known or deduced X-Microsoft-Antispam-Mailbox-Delivery header values.
Prompt used was "Can you help me decode an undocumented email header: " and I included my exact header.

**Comment by adamlavery** [comment]
Nope, got nothing useful for this header - just a random collection of links, none of which are related to this specific header.

**Comment by CameronKnowlton** [comment]
> Nope, got nothing useful for this header - just a random collection of links, none of which are related to this specific header.

Try using GPT-4, much better than GPT-3 Legacy, which is itself better than the default GPT-3 Turbo. It did an amazing job of decoding my headers.

**Comment by CameronKnowlton** [comment]
Try asking GTP-4 (not just Chat-GPT 3.5). GPT-4 seems to have consumed the documentation on this, it's pretty great at decoding MS headers.

Cameron Knowlton
iGods Internet Marketing Inc.
***@***.***
P: 250.382.0226

**Comment by matsimon** [comment]
Please stop mentioning GPT-4, it doesn't provide a source of its knowledge that we could verify ourselves and therefore cannot be served as reference.

While it does provide guesses about i.e. some more details of X-Microsoft-Antispam-Mailbox-Delivery such as the part containing ```ENG:(<rule id1>)(<rule id2>)(<etc...>)``` that it cannot provide source so its knowledge that one could verify. It even honestly responded when I asked it about its source of knowledge of a specific rule ID:
```
[...] their meanings are not publicly documented. The information I provided earlier was based on
general knowledge of email headers and antispam/antivirus practices, as well as common practices
observed in email headers.
```

**Comment by CameronKnowlton** [comment]
Ok, you're on your own then. I had great success with very detailed breakdown of each field.

Cameron Knowlton
iGods Internet Marketing Inc.
***@***.***
P: 250.382.0226

**Comment by fayers90** [comment]
Heads up, I used Snapchat new bot and got the perfect answer. Just change the question to which ever field.
![Snapchat-1308677980](https://user-images.githubusercontent.com/8534314/234978604-3785a425-7e48-4730-b366-70d931a87eb2.jpg)

**Comment by fayers90** [comment]
Also you can't always use the online header analyser if you are checking IT a business email as they don't allow shared mailbox access on the Web based outlook.

**Comment by CameronKnowlton** [comment]
Yes, that's a very cool tool. I found it helped get me on track, here it is for others:
https://mha.azurewebsites.net/￼

Cameron Knowlton
iGods Internet Marketing Inc.
***@***.***
P: 250.382.0226

**Comment by CameronKnowlton** [comment]
I believe that the Snapchat bot is using v4. I have the OpenAI developer access (so I pay a trivial amount each month on top of ~$15 for ChatGPT plus), it lets me test out responses using different models.

Bing fed "a lot of new information" to GPT-4, I'm thinking it got is hands on the hidden Microsoft Documentation. I mean, if I were Microsoft, I'd analyze its massive arsenal of support docs to give to its support army.

The feedback I got from v4 was amazing.

Cameron Knowlton
iGods Internet Marketing Inc.
***@***.***
P: 250.382.0226
