### ISSUE TITLE
Finding data in Exchange mailboxes

### ISSUE THREAD

**Issue by robm82** [MicrosoftDocs/microsoft-365-docs#786]
Within this article, it states: "At this time these cannot be used to find data in Exchange mailboxes at rest."  Is this really true, as this article seems to suggest that this is possible?

https://docs.microsoft.com/en-us/microsoft-365/compliance/manage-gdpr-data-subject-requests-with-the-dsr-case-tool

Quote from the attached article: "Any user mailbox in your organization. This includes Skype for Business conversations and one-to-one chats in Microsoft Teams"

Can this be reviewed please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fae7253-e256-9879-1b3c-c8e335d73db2
* Version Independent ID: a4a671cc-95d0-bcaa-d3b5-579e5bea4e1f
* Content: [Search for and find personal data](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-find-personal-data?source=docs)
* Content Source: [microsoft-365/compliance/search-for-and-find-personal-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-and-find-personal-data.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@robm82  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@robm82 - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/9a71936.


Thank you for your contribution to make the docs better! Much appreciated!
