### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by mastood** [MicrosoftDocs/microsoft-365-docs#7860]
The link in the see also section to the guidance on Onboarding Windows 10 machines returns a 404 error.  The link should point here:

Windows 10 and 11 - https://docs.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-overview?view=o365-worldwide

macOS(Preview) - https://docs.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-macos-overview?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76da4eda-4ccf-ff34-6a48-d9c5553c2ed6
* Version Independent ID: 7e887aff-1b85-1651-2bff-63425c54ae63
* Content: [Using  Endpoint data loss prevention - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-using?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-using.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by RAJU2529** [comment]
@mastood, thanks for the report and giving the correct link, i added a correct link in this article.
@chrfox , Please merge #7873 if it is correct.

**Comment by yogkumgit** [comment]
@mastood Thank you very much for the contribution and updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
