### ISSUE TITLE
Additional URLs needed for Microsoft Managed Teams Rooms Program (MMRP) Agent Software 

### ISSUE THREAD

**Issue by davidleeolmstead** [MicrosoftDocs/microsoft-365-docs#7862]
Good job having this page be the Authoritative Source for the network resources needed to make MS Teams perform well. 
We need to ADD the additional URLs that the Managed Teams Room Program Agent software needs to do its job. 
Those URLs are documented here:
https://docs.microsoft.com/en-us/microsoftteams/rooms/security#network-security 
f you're using the Microsoft Teams Rooms managed services component of Microsoft Teams Rooms Premium, you also need to make sure that Teams Rooms can access the following URLs:

agent.rooms.microsoft.com
global.azure-devices-provisioning.net
gj3ftstorage.blob.core.windows.net
iothubsgagwt5wgvwg6.azure-devices.net
blobssgagwt5wgvwg6.blob.core.windows.net
mmrstgnoamiot.azure-devices.net
mmrstgnoamstor.blob.core.windows.net
mmrprodapaciot.azure-devices.net
mmrprodapacstor.blob.core.windows.net
mmrprodemeaiot.azure-devices.net
mmrprodemeastor.blob.core.windows.net
mmrprodnoamiot.azure-devices.net
mmrprodnoamstor.blob.core.windows.net

**Suggested Action:**
After Line ID 19, which is optional for customers who deploy Teams Conference Rooms, we should add an additional line to document the URLs above, with a back-link to the source URL above.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
@davidleeolmstead, thanks for reaching out. The list of IP addresses and URLs for Office 365 services is managed by a web service, and changes must be submitted with the Office 365 Endpoints portal at https://endpoints.office.net.

For instructions on how to submit a change and manage the IP addresses and URLs for your service, see the user guide at http://aka.ms/endpointshelp.

If you have any permissions issues with these links, please contact endfeedback@microsoft.com.

Hope this helps.
- Kelley
