### ISSUE TITLE
Why is Microsoft suggesting Godaddy ???  Its a very bad company.

### ISSUE THREAD

**Issue by Derek-Anderson** [MicrosoftDocs/microsoft-365-docs#7864]
Why is Microsoft supporting Godaddy?  I'm looking to move my business from Workspaces to O365wteams but this is very alarming.  Godaddy is a predatory company.  Don't get me wrong, they are big but many of their products are designed to take advantage of the little people or don't work at all.  

For example, I've paid for Godaddy service (and #1 in line to buy) a domain if/when it expires and is not renewed nearly 10-12 years ago.  A year ago, I checked on it and it did finial expire without renewal but somehow a subsidiary of Godaddy bought it and never offered it to me per our contract - now they are trying to sell it for $16k.  This is just one example of 10 or 20 things they do that are very questionable.

Godaddy is a shady business and I'm surprised as hell that Microsoft even suggests supporting them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb572a6e-0bd1-9609-4cbe-021deb497da7
* Version Independent ID: 7f82b19b-d569-c955-2e2d-20ec3112b3ad
* Content: [Buy a domain name - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/buy-a-domain-name?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/buy-a-domain-name.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/buy-a-domain-name.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@Derek-Anderson Thank you for your feedback. You can provide the feedback on our Main feedback portal: https://feedbackportal.microsoft.com/

This channel is only for updating the documents and we do not have the exact answer to your query.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@Derek-Anderson Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.

**Comment by amanbhk7** [comment]
godaddy is best for domain buy. i have buy more then 100$ from godaddy , if you check **[domain valuation](https://bynext.com/2019/07/21/free-domain-valuation-domain-appraisal-services/)**. i have also buy from dynadot and namecheap very bad experience .
