### ISSUE TITLE
Blocking "till the following day"

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/microsoft-365-docs#787]
Is this midnight UTC? O365 support engineers tell me it is 24 hours from being blocked.
Also is it possible for at least your support engineers to view these blocked users?  What is the reasoning behind not being able to unrestrict, or at least have visibility of restricted users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure the outbound spam policy](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@cabtilx - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature request on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by cabtilx** [comment]
So can the documentation at least be amended to clarify that "until the following day, based on UTC time." is midnight UTC? Currently it is causing confusion as it is not clear.
