### ISSUE TITLE
"PR #12838 Update Launch details" is not reflected 

### ISSUE THREAD

**Issue by hfukumotoms** [MicrosoftDocs/microsoft-365-docs#7872]
I submitted "PR #12838 Update Launch details".
But this Pull Request is not reflected.
Why is PR not reflected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c312fd69-72cd-bc86-4fe1-993b60b97bc6
* Version Independent ID: b7887ba6-4775-39f0-e368-68f140ce233d
* Content: [Simulate a phishing attack with Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hfukumotoms, that PR number is too high; current pull requests in this repo are in the 7880 range.

Did you follow the instructions [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md) and click the green button 3 times?

**Comment by hfukumotoms** [comment]
Thanks! I recreate #7897 (same change).

**Comment by yogkumgit** [comment]
@hfukumotoms Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
