### ISSUE TITLE
What is the roadmap for the modern unified solution in Microsoft Defender for Cloud?

### ISSUE THREAD

**Issue by timkmsft** [MicrosoftDocs/microsoft-365-docs#7876]
I am currently working with a customer who would like the features and benefits of what the modern unified solution offers in Microsoft Defender for Cloud - what is the roadmap currently to have alerting etc working as needed. There was a special note attached which read:

For Windows Server 2012 R2 and 2016 running the modern unified solution preview, integration with Microsoft Defender for Cloud / Microsoft Defender for servers for alerting and automated deployment is not yet available. Whilst you can manually install the new solution on these machines, no alerts will be displayed in Microsoft Defender for Cloud.

Much appreciated your guidance.
Have a great day ahead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@timkmsft Thank you for your feedback. I donot see this in the roadmap yet -https://www.microsoft.com/en-in/microsoft-365/roadmap?filters=&searchterms=Microsoft%2Cdefender%2Cfor%2Ccloud

You can raise this question in our main feedback portal - https://feedbackportal.microsoft.com/ to get answer specific to this feature from the dev /production team.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@timkmsft Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
