### ISSUE TITLE
Documentation is out of date relative to the https://security.microsoft.com/ site. 

### ISSUE THREAD

**Issue by davidfordaus** [MicrosoftDocs/microsoft-365-docs#7877]
Documentation is out of date relative to the https://security.microsoft.com/ site.  

This link on the page : https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide#download-the-onboarding-package

Indicates to do the following
1. Settings > Endpoints > Device management > Onboarding.

This is no longer accurate.  I'm still trying to find "device management" / onboarding of a device.  Please update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@davidfordaus Thank you for your feedback. I was able to download the onboarding package from security.microsoft.com

The navigation instructions are also correct in the document

![image](https://user-images.githubusercontent.com/45987684/156906382-b0525948-a4ca-4cfc-9ce0-5bb9f288ead8.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @davidfordaus Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by davidfordaus** [comment]
Clicking this link:
https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-defender?view=o365-worldwide
With this description:
![image](https://user-images.githubusercontent.com/602815/156990057-58b7079b-7ea2-4872-8e4e-7a67dbb4e47c.png)

And link: https://go.microsoft.com/fwlink/p/?linkid=2077139

Leads to (when logged-in):
https://security.microsoft.com/homepage

Clicking "Settings" on the left leads to:
https://security.microsoft.com/securitysettings
![image](https://user-images.githubusercontent.com/602815/156990163-208bba98-3ec0-485d-8466-fcfb3c7897e3.png)

Which does not (as you can see) provide the next step of the navigation.

1. Settings > Endpoints > Device management > Onboarding.
2. Endpoints is not visible on this screen

At a guess this is because the logged-in user doesn't have rights to view Endpoints, however there is no way to know this.   At this point I appreciate your time but will not be reporting any further Microsoft bugs.  This is not the best use of my time to help to resolve issues in the software.
