### ISSUE TITLE
Windows Mobile Reference can be removed as Windows Mobile is no longer a supported platform

### ISSUE THREAD

**Issue by fvanrijt** [MicrosoftDocs/microsoft-365-docs#7878]
There a quite some references towards "Windows Mobile" in the basic mobility and security documents. As Windows Mobile is no longer supported It might be good to reflect the documentation with that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a33db0b-45cf-2903-3c71-f68d56f520ea
* Version Independent ID: fd9e9be2-14ca-ee49-b634-d654bd141a8a
* Content: [Overview of Basic Mobility and Security for Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/basic-mobility-security/overview?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/admin/basic-mobility-security/overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/basic-mobility-security/overview.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@fvanrijt Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7926

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fvanrijt Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
