### ISSUE TITLE
Add URLs and IPs for Microsoft Teams Rooms Premium

### ISSUE THREAD

**Issue by DazMR2** [MicrosoftDocs/microsoft-365-docs#7879]
This page shows most of the URLs and IP addresses for Teams but is missing the URLs and IP addresses for Teams Room Premium. Can we add a section, or a hyperlink to the address ranges for Teams Room Premium, as shown here? 
https://docs.microsoft.com/en-us/microsoftteams/rooms/monitor-software-installation-guide#urls-required-for-communication

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&source=docs#skype-for-business-online-and-microsoft-teams)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
@DazMR2, the article you linked to in your post no longer exists. Is the list of URLs the one in this article? https://docs.microsoft.com/en-us/microsoftteams/rooms/security#network-security

I will investigate whether these endpoints are still missing from the web service.

Kelley

**Comment by DazMR2** [comment]
Hi Kelley,

Yes, these are the URLs for Teams Room Premium.

Thanks

Darryl

**Comment by kelleyvice-msft** [comment]
At this time, the Teams Room endpoints have not been added to the web service because they are in Azure, not Microsoft 365. My understanding is that there is an ongoing discussion about this, and it's likely that there will be updates in the future that will permit Teams Room endpoints to be added to the web service. There is currently no ETA for this, however.

Thanks for reaching out.  It's a great suggestion. -Kelley
