### ISSUE TITLE
Set-HostedOutboundSpamFilterRule

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/microsoft-365-docs#788]
We can create a policy with Set-HostedOutboundSpamFilterPolicy but is this active without a rule? Using the GUI creates a policy + rule. If there is no rule is the policy applied to everyone or not applied at all? There appears to be no documentation for the Set-HostedOutboundSpamFilterRule cmdlet at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure the outbound spam policy](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@cabtilx  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by get-itips** [comment]
Hello @cabtilx how are you?
How did you manage to use this Set- cmdlet to create a new Spam Filter Policy?
The Set- cmdlet only modifies an already created Spam Filter Policy, as the article says.
Thank you

**Comment by cabtilx** [comment]
To clarify the cmdlet is  New-HostedOutboundSpamFilterPolicy
I believe when using the GUI to create a 'policy' it effectively runs both New-HostedOutboundSpamFilterPolicy and New-HostedOutboundSpamFilterRule in the backend so there is a policy and a rule associated with the policy.
If you just use the New-HostedOutboundSpamFilterPolicy then no rule is automatically created. So the assumption is that it applies to everyone, but this isn't clear from the documentation. I don't think  the HostedOutboundSpamFilterPolicy cmdlets should be referenced in this article until the cmdlets to create rules is also documented and included.

**Comment by get-itips** [comment]
Hello @cabtilx thanks for clarifying, I'll investigate and get back to you.

**Comment by mypil** [comment]
@cabtilx - We have already reached out to the docs team and we were informed that they are updating the doc and it is already in progress. It will be published as soon as it is completed.

Thank you for sharing your feedback and for your contribution to make the docs better! Much appreciated!

cc: @chrisda @MSFTTracyP

**Comment by chrisda** [comment]
HostedOutboundSpamFilterRule cmdlet topics are alive and existing HostedOutboundSpamFilterPolicy topics have been updated:

https://docs.microsoft.com/powershell/module/exchange/antispam-antimalware/set-hostedoutboundspamfilterrule
