### ISSUE TITLE
Requirement for the 2021 unified agent is not explicit for windows server 2012 and 2016 devices

### ISSUE THREAD

**Issue by MasterBlaster4** [MicrosoftDocs/microsoft-365-docs#7884]
[Enter feedback here]
The requirements for windows server 2012 and 2016 devices are not explicit regarding the need for the new unified agent.
Live Response does not work if the onboarded devices connect to MDE through MMA, so it should appear as requirement that the 2021 unified agent is required to establish a session (it's only referred when the necessary KB is clicked on)
cheers,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b2a4c2-e698-dda0-9919-80ca2d05b358
* Version Independent ID: 19b5f609-fcaa-cb5b-96b7-462285fd32e7
* Content: [Investigate entities on devices using live response in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/live-response.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/live-response.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MasterBlaster4 Thank you for your feedback. Before you can initiate a session on a device running Windows Server 2012 R2 or Windows Server 2016, it is required to have Microsoft Defender for Endpoint update for EDR Sensor. I think it is mentioned as a requirement as the section talks about requirements based on the platform.

Let us know if there is any specific change you would like to make in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MasterBlaster4 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
