### ISSUE TITLE
Troubleshooting links?

### ISSUE THREAD

**Issue by tillasx** [MicrosoftDocs/microsoft-365-docs#7886]
Test-IRMConfiguration provides no advice nor links to advice on what to do if your testing results are **not similar** to the successful results displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe08d5e-4870-331e-b5f2-92848b5211b0
* Version Independent ID: 60ed3095-a42c-1bcb-f2fa-8325cfcd03f6
* Content: [Set up new Message Encryption capabilities - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-new-message-encryption-capabilities?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-new-message-encryption-capabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-new-message-encryption-capabilities.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@tillasx Thank you for your feedback. We have added a troubleshooting step to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7928

I'll verify with the author and once it is approved, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tillasx Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
