### ISSUE TITLE
Licensing requirements

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#789]
Please identify the license requirements. we have O365 E5 and this is not showing up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4325da2c-e262-0430-854d-cf3b869575b6
* Version Independent ID: e50c60f6-6b10-8f8a-5f45-5cf3befb6a61
* Content: [Microsoft Compliance Score](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score#what-is-compliance-score)
* Content Source: [microsoft-365/compliance/compliance-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-score.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Hello, any customer with a valid AAD can access Compliance Score. Depending on your launch point, some customers have had issues accessing it and I have made the engineering team aware. For now, it is best to use this deep link to take you directly to Compliance Score:  https://aka.ms/compliancescore. To view additional setup instructions, see https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score-setup.  Thanks.
