### ISSUE TITLE
Teams Logical Architecture

### ISSUE THREAD

**Issue by rmuhammad4** [MicrosoftDocs/microsoft-365-docs#7891]
Is this architecture still current as of today?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbbbdfb-c916-be79-2a91-5576d58a30e1
* Version Independent ID: 793f2f73-6fbc-04e5-fa8a-54908d74d860
* Content: [Microsoft 365 productivity illustrations](https://docs.microsoft.com/en-us/microsoft-365/solutions/productivity-illustrations?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/productivity-illustrations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/productivity-illustrations.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @samanro
* Microsoft Alias: **samanro**

**Comment by samanro** [comment]
@BrendaCarter for detailed response, but yes, this page has our current guidance. Do you have a specific illustration you have questions on?

**Comment by rmuhammad4** [comment]
Thank you for the quick response. I just wanted to confirm before I deliver a workshop.

**Comment by BrendaCarter** [comment]
Optionally you can now have your videos saved to SharePoint, but the illustration is accurate for the current defaults.
https://docs.microsoft.com/en-us/stream/streamnew/new-stream#stream-classic-vs-stream-on-sharepoint

**Comment by BrendaCarter** [comment]
What kind of workshop are you presenting?
