### ISSUE TITLE
Error when trying to execute the Get-AzureADUser cmd

### ISSUE THREAD

**Issue by phishlabs** [MicrosoftDocs/microsoft-365-docs#7895]
When i try to execute the command to export a list of all users whose password are set to never expire, i get an error saying that the -All parameter cannot be found. The exact error states: 

"Get-AzureADUser : A parameter cannot be found that matches parameter name 'All'."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f52c6916-7e79-9a9c-b7a6-47041ddb81e3
* Version Independent ID: 43c9b873-d354-d814-3065-1e8832361b86
* Content: [Set an individual user's password to never expire - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/set-password-to-never-expire.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/set-password-to-never-expire.md)
* Service: **o365-administration**
![error](https://user-images.githubusercontent.com/67167470/156456246-6461315c-d925-4487-b2fd-914b9671ff8d.jpg)

* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@phishlabs Thank you fr your feedback. I was able to test the command and you need to execute the -All parameter along with $true. The cmdlets in the document also reflect the same

![image](https://user-images.githubusercontent.com/45987684/156906612-0d78fcf9-ea7e-490a-a2b9-3face4371208.png)


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @phishlabs Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
