### ISSUE TITLE
Wrong info?

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/microsoft-365-docs#7896]
**Article problems:**
I ran the advanced hunt query in this article and it returned many results of System account running system processes (form System32 or SysWow64 or C:\Windows\Temp or C:\ProgramData folders) on path \Device\Harddisk0\DR0 being blocked??
svchost.exe -k netsvcs -p ** wuauserv is in the list.

Why are those being blocked?? That isn't the core folders listed in the article. 

And since I know you're going to blame my configuration, we have no additional folders being protected:
https://www.dropbox.com/s/7h27wfopiprdk63/ASR%20Screenshot%202022-03-02%20161504.png?dl=0

**Product problems:**
Why do I have to run an advanced hunt for that information instead of it appearing in the Reports > Attack Surface Reduction rules??
Why is notepad.exe being blocked from making modifications to anything? This isn't an app that can be hijacked with ransomware. 
Why is OneDrive.exe blocked from modifying files in my OneDrive folder?? 
Come on Microsoft! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fb0d02-ceff-61d8-3041-13df9513769a
* Version Independent ID: 7c98a316-de58-520a-a6ad-06ddaf0d71b3
* Content: [Protect important folders from ransomware from encrypting your files with controlled folder access](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide#review-controlled-folder-access-events-in-the-microsoft-365-defender-portal)
* Content Source: [microsoft-365/security/defender-endpoint/controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/controlled-folders.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks
