### ISSUE TITLE
Is there still a requirement for running the commands from the AzureADPreview module?

### ISSUE THREAD

**Issue by MacKender** [MicrosoftDocs/microsoft-365-docs#7900]
The doc states that
"If you haven't installed any version of the Azure AD PowerShell module before, see [Installing the Azure AD Module](https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?preserve-view=true&view=azureadps-2.0-preview) and follow the instructions to install the public preview release.

If you have the 2.0 general availability version of the Azure AD PowerShell module (AzureAD) installed, you must uninstall it by running Uninstall-Module AzureAD in your PowerShell session, and then install the preview version by running Install-Module AzureADPreview."

==> Given the maturity of the AzureAD module, is there still a need to install and run the commands form the AzureADPreview module?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e00be85-c1bd-bfd9-e09b-78fea811f864
* Version Independent ID: bdfb2aad-6aa8-76a8-46cf-1603f8255df4
* Content: [Prevent guests from being added to a specific group](https://docs.microsoft.com/en-us/microsoft-365/solutions/per-group-guest-access?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/per-group-guest-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/per-group-guest-access.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@MacKender Thank you for your feedback. Yes, from testing and conversation with the product group there is still a requirement for Azure AD preview to be installed(latest version recommended) to change the group-level guest access setting.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MacKender Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
