### ISSUE TITLE
page needs better graphics to explain

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/microsoft-365-docs#7903]
[Enter feedback here]
The images shown only show the right side of the menu.  This will not help most people.  It did not me.  It should have the current image of a menu as attached.  1)Opening up the "3-lines" menu item.  2) looking down the left side. 3) selecting the "words" "Health"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d8b9c3-7ff2-d3b7-a0ce-0310171c71d5
* Version Independent ID: 7b45c0a3-94ca-b749-50e4-7d4cbf204764
* Content: [How to check Microsoft 365 service health - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-service-health?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-service-health.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-service-health.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice*
![2022-03-03 10_28_46-Microsoft 365 admin center - Home](https://user-images.githubusercontent.com/38498263/156619162-efeaaaad-4665-4395-a1f9-98b68e3d0bf9.png)
*

**Comment by msbemba** [comment]
@fixx-er Thank you for your feedback. I have made changes to the document to add wordings in order to describe that the health option is in the navigation pane. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7993

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fixx-er Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
