### ISSUE TITLE
License Change Audit is not working

### ISSUE THREAD

**Issue by balaji-blg** [MicrosoftDocs/microsoft-365-docs#7909]
In User administration activities . it has "**Change user license.**"  action but whenever I change a license to an user in **Azure AD portal** or using **graph api** . I couldn't able to find that audit.  only "**Update user**" audit is there. is that audit action still in use ? or how to generate this action ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft 365 compliance center - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#audited-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@balaji-blg Thank you for your feedback. The "Change user license" is still available. I'd recommend you contact support and understand the reason it does not show up on your tenant. After you contact support via the need help section on the admin center, If you feel there are any specific activity/operation that needs to be changed, let us know. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @balaji-blg Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
