### ISSUE TITLE
GCC DLP Rule > Unable to select Teams as a location (not a visible option)

### ISSUE THREAD

**Issue by rbahne** [MicrosoftDocs/microsoft-365-docs#791]
I have a GCC client that is not seeing Teams as a location when setting up DLP rule. Is there any condition that might exist that would keep this from showing up as an option? They do have at least one existing Team so I would think that would be an available option. I am seeing Teams chat and conversations as an available location for them.

**Comment by mypil** [comment]
@rbahne - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@rbahne - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to open a new issue if there is a specific area of the docs that we can improve or make better. Thank you.
