### ISSUE TITLE
How to restrict use of a retention label to specific groups/users?

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/microsoft-365-docs#7910]
**How to restrict the use of a specific retention label to a specific groups/users?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Use file plan to manage retention labels throughout the content lifecycle - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/file-plan-manager?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@jaganpt  File plan is all about retention labels - and you can't configure this with labels. Depending on the workload, you might be able to do this when you configure the policy that applies the labels. For example, the Exchange email and OneDrive locations let you specify individual users, but not the SharePoint location (where you specify sites instead). 

Specifically, take a look at adaptive policy scopes that let you choose different attributes to identify the targeted users (or groups) for the policy: https://docs.microsoft.com/microsoft-365/compliance/retention-settings?view=o365-worldwide#configuration-information-for-adaptive-scopes

**Comment by yogkumgit** [comment]
@jaganpt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
