### ISSUE TITLE
No New Info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#7913]
Other security teams have published info about their changes in January and February. I am pretty sure that there have been some changes to this product also, Please update this information
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac42403c-4226-bec2-986d-2e8a67e7c66d
* Version Independent ID: e8e0b323-ee46-f8e7-fe99-cbee91697213
* Content: [What's new in Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/whats-new.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Direct product enhancement made in March.
