### ISSUE TITLE
Instructions to delete a group

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#7915]
The page states that Groups cannot be manually deleted, but does not state how they can be deleted. Please provide additional instructions for accomplishing this task
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a73489-d481-4b81-b45e-3ec475740b38
* Version Independent ID: 40f31f99-a8be-1801-8855-cd185d40176e
* Content: [Build and manage assessments in Microsoft Compliance Manager - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-assessments?view=o365-worldwide#data-protection-baseline-default-assessment)
* Content Source: [microsoft-365/compliance/compliance-manager-assessments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-assessments.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. At this time, groups cannot be deleted but can be reused. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8021

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The changes are live and the issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DeanGross Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
