### ISSUE TITLE
eDiscovery Content Search on Business Basic and Standard

### ISSUE THREAD

**Issue by TadaoMachida** [MicrosoftDocs/microsoft-365-docs#7919]
According to the document https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWR6bM, eDiscovery Content Search is available on Business Basic and Standard subscriptions. But in this document, these subscriptions are not listed in 'eDiscovery subscription comparison/Content search' section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562b6b1d-b0fd-0d65-9db8-37df67bd7035
* Version Independent ID: 92c4403b-0d6b-88aa-74f4-ba3b7640ad00
* Content: [Microsoft 365 eDiscovery solutions - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide#content-search)
* Content Source: [microsoft-365/compliance/ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@TadaoMachida Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7994

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TadaoMachida Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
