### ISSUE TITLE
Clarify statement for on-premises mailboxes

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/microsoft-365-docs#7921]
Can we clarify the statement about support for on-premises.

The way the article reads right is that on-prem mailboxes in hybrid work and are supported.  Only purely on-premises Exchange orgs (no hybrid) are supported.

Can we change this to say something like on-premises mailboxes are not supported?  That way there is less ambiguity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@r-milne Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7995

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chrisda** [comment]
PR merged so closing this issue.

Thanks for the feedback.
