### ISSUE TITLE
GoDaddy Hosted Microsoft 365 ---You cannot access https://admin.microsoft.com to obtain DNS records

### ISSUE THREAD

**Issue by VinceI** [MicrosoftDocs/microsoft-365-docs#7922]
[Enter feedback here]
If you have GoDaddy hosted Microsoft 365 you cannot access the admin center at [https://admin.microsoft.com]. to obtain the DNS records that are required by the procedure in the tutorial/guide so you cannot obtain the values that must be entered in Microsoft hosted Microsoft 365.

(https://go.microsoft.com/fwlink/p/?linkid=2024339)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0012093-49ca-c2f6-a3f3-4e4252fca609
* Version Independent ID: 22784dda-ff03-971b-4d6e-5b0152f62942
* Content: [Add a domain to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/add-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-domain.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@VinceI  Thank you for your feedback. You are correct, the option mentioned on this page is to perform steps via M365 purchased directly with Microsoft. For any issues on your Go daddy tenant, Support is provided by Go daddy. Here are the options to contact them - https://in.godaddy.com/help/microsoft-365-from-godaddy-1000005

You will need to provide details for the domain and they help add the domain in the backend. 

Hope this helps!

Thanks
Sri

**Comment by VinceI** [comment]
Hi,


We are migrating from GoDaddy to Microsoft direct subscriptions/licenses.

GoDaddy processed the outbound (GoDaddy to Microsoft)  migration on 8 March 2022.

They indicated I had 7 days from 8 March 2022 to purchase the appropriate licenses from Microsoft and assign them to my users.


I have purchased all the required licenses from Microsoft directly and assigned them to my users.

Every user now also has a license purchased directly from Microsoft.

In the Microsoft 365 Admin Center I have verified my domains (Status:  Healthy) and set the appropriate default domain.

+++++

Regarding the problem in the Subject line:  You cannot access https://admin.microsoft.com to obtain DNS records (Issue #7922)


Only after GoDaddy processes the outbound migration, does the subject problem goes away, you are then able to access https://admin.microsoft.com to obtain DNS records.





Thanks


Vince

**Comment by msbemba** [comment]
@VinceI Thank you for the response. I'm glad that you got it sorted. I was not aware of the migration piece, but you are right, that is when the tenant is moved from a go daddy-attached account to a direct Microsoft tenant. After which all these options mentioned on thisis page should be possible. 

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @VinceI Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
