### ISSUE TITLE
User, group and sender domain picker list

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/microsoft-365-docs#793]
Hello, these lists don't function correctly.
The user and group 'picker' lists don't seem to search the GAL at all, they're just free text.
The domain list shows 5 random domains and typing performs a substring search on these 5 domains but no others.  If you have more than 5 domains and want to select one that isn't listed you have to keep selecting one from the 5 shown until the one you want appears in the list, and then you have remove all of the ones you don't want from the selection box.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c27660-0f0b-3002-7183-854e4fb8716b
* Version Independent ID: 3f436862-e6b3-2a9d-70b5-f7eee02eec2e
* Content: [Configure the outbound spam policy](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy)
* Content Source: [microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@cabtilx - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by cabtilx** [comment]
Thank you. Unfortunately I've raised 2 service requests on the portal and spent 4 days on the phone to 1st line engineers but they don't comprehend the issue as they don't understand how the rules interact with the policies and each call ends with them going off to speak to their technical leads, hardly ASAP ;)
I'll keep trying but I was hoping that someone from the product team would view it as they'd understand the issue in 5minutes and be able to prevent other customers experiencing similar outages.
________________________________

**Comment by mypil** [comment]
@cabtilx - Sorry to hear that you are having issues. Please understand that this site is a product documentation site and not a support nor a feature request site.

As such, the feedback section here is intended for feedback that improves the content in the Microsoft documentation and not intended for user feedback on product features nor troubleshooting.

For user feedback on product feature requests, you can submit via **[User Voice](https://office365.uservoice.com/)**. I know the product teams are always looking for user feedback on how to make Microsoft 365 better. You might find others have made a similar request that you can add to, or you can open a new one.

For technical queries or troubleshooting, you can visit **support.microsoft.com**, **answers.microsoft.com** or open a **[support ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)**.

I hope this gets you pointed in the right direction. If you do find that it is a documentation error though, feel free to comment back and we'll gladly look into fixing it.  

Thank you.
