### ISSUE TITLE
Can not find Schedule Report

### ISSUE THREAD

**Issue by cakriwut** [MicrosoftDocs/microsoft-365-docs#7933]
Hi team,

I can not find **Create Schedule** in the main Report page. Could it be the information is already obsolete?

![image](https://user-images.githubusercontent.com/307755/156982314-3426f467-ca35-496f-a48e-8bd26a5d7282.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e7112fd-cc48-c218-6e7f-1b8f76644aaa
* Version Independent ID: e285a0da-bcdc-eae7-6bd5-54fe5dab2ef4
* Content: [View email security reports - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-email-security-reports?view=o365-worldwide#schedule-report)
* Content Source: [microsoft-365/security/office-365-security/view-email-security-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-email-security-reports.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cakriwut, I see what's going on. The phrase "On the main report page" is supposed to me the main page for the specific report that you're reading about, not the main **Reports** page in the Microsoft 365 Defender portal.

I changed everywhere to clarify.

Thanks for the feedback.

Closing.
