### ISSUE TITLE
File indicator elgibility for Defender for Endpoint Plan 1

### ISSUE THREAD

**Issue by 0fflineDocs** [MicrosoftDocs/microsoft-365-docs#7935]
[Enter feedback here]
This page is a bit misleading. At the top it states "Applies to MDE Plan 2" but to use a file indiciator is valid for P1 aswell as per this article, correct? https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1?view=o365-worldwide#manual-response-actions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04266df-a692-ddef-5f05-ea40d82a0eed
* Version Independent ID: d0ac62e7-498f-399d-c701-d7cbeb85cced
* Content: [Create indicators](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-indicators?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-indicators.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-indicators.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@0fflineDocs Thank you for your feedback. This document pertains to multiple indicators supported by Microsoft Defender for Endpoint Plan 2. However, I noticed that create an indicator for files-  https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-file?view=o365-worldwide Did not include p[lan 1. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7996

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @0fflineDocs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
