### ISSUE TITLE
Manage indicators (File) elgible for Defender for Endpoint P1 and P2 - Clarification needed

### ISSUE THREAD

**Issue by 0fflineDocs** [MicrosoftDocs/microsoft-365-docs#7936]
[Enter feedback here]
Clarification needed about licensing. This article states that the following actions are applied to MDE P2.
However, Indiciator for file for example is a setting valid for MDE P1 aswell?
This article at least states that: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1?view=o365-worldwide#manual-response-actions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04266df-a692-ddef-5f05-ea40d82a0eed
* Version Independent ID: d0ac62e7-498f-399d-c701-d7cbeb85cced
* Content: [Create indicators](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-indicators?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-indicators.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-indicators.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d35c168-4704-d96e-15ad-be38fe8f332f
* Version Independent ID: 71ef6707-4191-f1e0-677b-2a4c3515c2b5
* Content: [Take response actions on a file in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-file-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/respond-file-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/respond-file-alerts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@0fflineDocs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/7997

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @0fflineDocs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
