### ISSUE TITLE
MICROSOFT SWIFTKEY 

### ISSUE THREAD

**Issue by Bethotf** [MicrosoftDocs/microsoft-365-docs#7938]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce65739-6428-fc57-012c-a6741a051c6b
* Version Independent ID: 3341ac81-3e21-4e71-e4f7-3eff41db05b8
* Content: [About the Microsoft 365 Admin mobile app - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-mobile-app?view=o365-worldwide#what-do-i-need-to-do-to-be-able-to-use-the-app)
* Content Source: [microsoft-365/admin/admin-overview/admin-mobile-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-mobile-app.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Bethotf Thank you for your feedback.  Microsoft SwiftKey is the intelligent keyboard that learns your writing style, so you can type faster, It is available on google play - https://play.google.com/store/apps/details?id=com.touchtype.swiftkey&hl=en_IN&gl=US

As this is not related to Microsoft 365, We could not update details about this on this particular document. If you have further queries about Microsoft Swift Key - You can contact Support via https://support.microsoft.com/en-us/topic/global-customer-service-phone-numbers-c0389ade-5640-e588-8b0e-28de8afeb3f2


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Bethotf Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
