### ISSUE TITLE
Non O365 sources

### ISSUE THREAD

**Issue by bvksphub** [MicrosoftDocs/microsoft-365-docs#794]
Is there any feature available or in the roadmap where Non office 365 source can be connected and import required data and perform analysis. Such as adding Fileshares or other content sources. 

Current feature allows to upload data but it might not work for larger data sets. its very challenging to move all of that data into review sets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c47747-9dfb-c503-c3f8-6e7674d2b3ea
* Version Independent ID: 704e0ee8-9b45-ce81-3a9c-1ccc34dc25c3
* Content: [Import non-Office 365 content for Advanced eDiscovery analysis](https://docs.microsoft.com/en-us/microsoft-365/compliance/import-non-office-365-data-into-advanced-ediscovery)
* Content Source: [microsoft-365/compliance/import-non-office-365-data-into-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-non-office-365-data-into-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@bvksphub  - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@chrfox - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by markjjo** [comment]
@bvksphub Currently, there is nothing on the roadmap. You might consider migrating your data to Office 365 first, and then adding it to a review set. Here's a link to info about migrating files to SharePoint Online: https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online

**Comment by markjjo** [comment]
@bvksphub Would also suggest that you look at the[ v2 version of Advanced eDiscover](https://docs.microsoft.com/en-us/microsoft-365/compliance/overview-ediscovery-20)y and the documentation that corresponds to the v2 version of adding non-O365 data to a review set: https://docs.microsoft.com/en-us/microsoft-365/compliance/load-non-office-365-data-into-a-review-set
