### ISSUE TITLE
Communication Library missing

### ISSUE THREAD

**Issue by jwgarrett** [MicrosoftDocs/microsoft-365-docs#7940]
It looks like the communications library has moved. Please update with the new location as it isn't on this page anymore. https://compliance.microsoft.com/advancedediscovery/globalsettings?viewid=Overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13eb60d7-e3a2-5ee3-10e4-2ff609e1a635
* Version Independent ID: 13eb60d7-e3a2-5ee3-10e4-2ff609e1a635
* Content: [Manage custodian communications templates in the Communications library in Advanced eDiscovery - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-ediscovery-communications-library?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/advanced-ediscovery-communications-library.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/advanced-ediscovery-communications-library.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jwgarrett Thanks for message. The page hasn't been moved. My guess is that communication templates haven't been rolled out to your tenant yet. Accord to the M365 road map, this feature is still being rolled out: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=88813. And this according to the message center post: "Rollout will begin in late February and is expected to be complete by end of April. " Apologies that it isn't showing up for you yet. You might contact MS Support, but I'm not sure if they can accelerate the rollout to your tenant or not.
