### ISSUE TITLE
Password minimum lentgh should be 14

### ISSUE THREAD

**Issue by razvan-b** [MicrosoftDocs/microsoft-365-docs#7941]
Hello,

The minimum password length should be 14 and not 8. We have the recommendation here:  https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh994560(v=ws.11)#best-practices

Also a password who is 8 characters will be compromised quite fast as per the following study: https://digg.com/technology/link/how-long-it-takes-to-get-password-hacked-1IvDFspF6p

Thanks,
Razvan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@razvan-b Thank you for your feedback. Maintain an 8-character minimum length requirement (longer isn’t necessarily better). Longer password requirements (greater than about 10 characters) can result in choosing predictable words or characters in a password. These are the updated minimum requirements for M365. 


The document-  https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh994560(v=ws.11)#best-practices was updated in 2016 and We're no longer updating this content regularly. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @razvan-b Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by dn7** [comment]
[This document](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide) has conflicting length recommendations:

- 14 characters: https://docs.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide#password-guidelines-for-administrators
- 8 characters: https://docs.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide#requiring-long-passwords

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@dn7  Thank you for your feedback. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9115

Once the author approves, the changes will be live.

Thanks
Sri
