### ISSUE TITLE
Limitations on Data set 

### ISSUE THREAD

**Issue by bvksphub** [MicrosoftDocs/microsoft-365-docs#795]
Any specific limitations on number of containers/load sets or size of containers or # of files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c47747-9dfb-c503-c3f8-6e7674d2b3ea
* Version Independent ID: 704e0ee8-9b45-ce81-3a9c-1ccc34dc25c3
* Content: [Import non-Office 365 content for Advanced eDiscovery analysis](https://docs.microsoft.com/en-us/microsoft-365/compliance/import-non-office-365-data-into-advanced-ediscovery)
* Content Source: [microsoft-365/compliance/import-non-office-365-data-into-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-non-office-365-data-into-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@bvksphub - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by GiantCrocodile** [comment]
I think these questions should be documented properly and thus being answered in the docs. Can you add this information @mypil or at least reopen this issue?
