### ISSUE TITLE
Feedback on the diagram under 2. VPN Forced Tunnel with a small number of trusted exceptions

### ISSUE THREAD

**Issue by awfki** [MicrosoftDocs/microsoft-365-docs#7950]
That diagram is not useful.  We're talking split tunnel so either the traffic goes out the user's internet or it rides the tunnel to the Corp site and goes out the internet there.  That diagram doesn't make it clear, at all, which traffic is doing which.  Oh... I figured it out.  Yeah, it's a crappy diagram.  To fix it put the user in a little box with a connection to the internet. Show tunneled traffic going back to Corp and non-tunneled traffic going straight to MS.  Do NOT point those in opposite directions, they both go out the internet.  Remove that VPN device or rename it to "VPN Concentrator" or something.  I have users with Meraki's at home and I thought that was the VPN device.  

The main point of confusion is the line that says "internet traffic" and a separate line that goes in a different direction and says "optimize category traffic".   That's very wrong.  The optimize traffic is also "internet traffic" and it goes out the same local internet.

Maybe just change the "Internet traffic" label to say "tunneled traffic" and the "Optimize category traffic" (very awkward phrasing) to "non-tunneled traffic".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765a6748-f76a-55ab-af72-ebc85112cb3e
* Version Independent ID: 765a6748-f76a-55ab-af72-ebc85112cb3e
* Content: [Common VPN split tunneling scenarios for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-common-scenarios?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-common-scenarios.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-common-scenarios.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I agree that these diagrams can be confusing, and I'm working with the product team to improve them. -Kelley
