### ISSUE TITLE
404 link on this page

### ISSUE THREAD

**Issue by edsonsmith** [MicrosoftDocs/microsoft-365-docs#7951]
Hi.  When I click on the link "Evaluate Attack Reduction Surface", I get a 404.

I am, however, presented with a helpful "could not find -- may you meant this other thing type page" at https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-phase-2?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67455747-78b0-f9da-be02-bc47f2c77a73
* Version Independent ID: ff3914a8-363a-121b-7cf3-22711ac11763
* Content: [Evaluate Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluate-mde?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/evaluate-mde.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/evaluate-mde.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@edsonsmith Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8055

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @edsonsmith Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
