### ISSUE TITLE
Request to fix Restore file from quarantine command

### ISSUE THREAD

**Issue by MinoruHattori** [MicrosoftDocs/microsoft-365-docs#7954]
[Enter feedback here]
Would you please modify the command to "%ProgramFiles% instead of "ProgramFiles%" ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d48adda3-8f2e-b13d-fbd7-b556d295bf85
* Version Independent ID: 46daacb8-1def-6af5-ccf1-61505bcedad4
* Content: [Address false positives/negatives in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@MinoruHattori Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8056

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MinoruHattori Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
