### ISSUE TITLE
What happens if an external domain does not have an SPF record and I have configured SPF Hard Fail

### ISSUE THREAD

**Issue by dogborne** [MicrosoftDocs/microsoft-365-docs#7955]
Hello, 

Microsoft mentions that other email providers might block emails from domains without SPF records (If the custom domain does not have an SPF TXT record, some receiving servers may reject the message outright. This is because the receiving server cannot validate that the message comes from an authorized messaging server) 

But none of the articles mention what Microsoft logic follows. i.e does Microsoft reject emails if SPF Hard fail has been configured within ASF rules. 

Thanks
David.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b0319e8-f6d0-942a-f802-f035d753b670
* Version Independent ID: 7c74eb1c-30b5-6186-6775-6cd94fc8eaa4
* Content: [How Sender Policy Framework (SPF) prevents spoofing - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing?view=o365-worldwide#HowSPFWorks)
* Content Source: [microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-office-365-uses-spf-to-prevent-spoofing.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@dogborne Thank you for your feedback. The details about SPF record :Hard fail is explained in the document -https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/advanced-spam-filtering-asf-options?view=o365-worldwide

Messages sent from an IP address that isn't specified in the SPF Sender Policy Framework (SPF) record in DNS for the source email domain are marked as high confidence spam. The header X-CustomSpam: SPF Record Fail is added.

So in your situation, it will mark the email as high confidence spam.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dogborne Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GPX750** [comment]
I don't know if this has been changed recently but I have been testing today and the above does not appear to be the case.

I have SPF Hard fail configured within ASF rules. If there is an SPF record and the test fails then the message is marked as high confidence spam. But if there is no SPF record, the message is marked as not spam (SCL=1).
