### ISSUE TITLE
Payload indicators only available if email content added

### ISSUE THREAD

**Issue by chkockle** [MicrosoftDocs/microsoft-365-docs#7961]
When configuring the training landing page in a simulation with the option "Create your own landing page" it is necessary to add the Dynamic tag 
"Insert email content" before the "Payload Indicators" checkbox can be activated (it is greyed out otherwise).
Documentation is only stating that depending on the selection of the "select technique" wizard page this option is available, but not that the Dynamic tag must be added as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c312fd69-72cd-bc86-4fe1-993b60b97bc6
* Version Independent ID: b7887ba6-4775-39f0-e368-68f140ce233d
* Content: [Simulate a phishing attack with Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@chkockle, confirmed and fixed.

Thanks for the feedback.

Closing
