### ISSUE TITLE
Portal URLs for GCCH/DoD require update

### ISSUE THREAD

**Issue by Matt-Littleton** [MicrosoftDocs/microsoft-365-docs#7964]
Portal URLs for GCCH and DoD should be updated FROM https://securitycenter.microsoft.us TO https://security.microsoft.us

Old securitycenter.microsoft.us portal URL now returns an error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c97d4493-75b1-312c-83b0-ad8fe72f7c0c
* Version Independent ID: af86fff7-4158-6e20-683a-e9cc02a10f67
* Content: [Microsoft Defender for Endpoint for US Government customers](https://review.docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/gov?view=o365-worldwide&branch=main#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/gov.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/gov.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Matt-Littleton Thank you for your feedback. The document has the correct URL updated now https://security.microsoft.us/.

@yogkumgit  There are no changes needed in the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Matt-Littleton Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
