### ISSUE TITLE
It is very hard to understand what is 'Groups creation domain' under article's subdirectory

### ISSUE THREAD

**Issue by kristofftan** [MicrosoftDocs/microsoft-365-docs#7967]
It is very hard to understand what is 'Groups creation domain' as below article's subdirectory, even though it translate to Chinese, it still become very hard to understanding. 

https://docs.microsoft.com/en-us/microsoft-365/solutions/choose-domain-to-create-groups?view=o365-worldwide

![image](https://user-images.githubusercontent.com/48010214/157579788-01f3be53-0513-4021-9ee0-c84f3a69c597.png)

**Comment by msbemba** [comment]
@kristofftan Thank you for your feedback. This article helps you set up M365 groups using either your primary domain or subdomains.

For example, your domain is Contoso.com, and if you would like to have users create groups only with a subdomain like students.groups.contoso.com or faculty.groups.contoso.com that can be done. 

Let me know if there is anything specific that is hard to understand and I'll verify.

Hope this helps!

Thanks
Sri
