### ISSUE TITLE
Explicit mention to Defender for Business in this page

### ISSUE THREAD

**Issue by smedin4** [MicrosoftDocs/microsoft-365-docs#7969]
This page https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts doesn't mention MDB product in the "Applies to" section.

However, manual response actions like isolate device seem to be available in MDB according to this other article:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/compare-mdb-m365-plans?view=o365-worldwide#compare-microsoft-defender-for-business-to-microsoft-defender-for-endpoint-plans-1-and-2

In which it is mentioned:

_Endpoint detection and response (behavior-based detection and manual response actions) > MDB (YES)_

Please review and update accordingly this page.
Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb7742-1171-00f4-ab40-6bcc479078ca
* Version Independent ID: 9a79f573-5f20-0e4c-822e-8af4ebf65422
* Content: [Take response actions on a device in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/respond-machine-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/respond-machine-alerts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@smedin4 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8058

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @smedin4 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
