### ISSUE TITLE
What about Power BI

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#7971]
Please add some guidance for sharing from Power BI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f912ee6-5ce4-faa8-4d8a-fe96fddce1fa
* Version Independent ID: bb203434-4ae7-0a3a-e1cb-070b3c8b47ca
* Content: [Collaborating with people outside your organization](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-with-people-outside-your-organization?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-with-people-outside-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-with-people-outside-your-organization.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@DeanGross Thank you for your feedback. As this document is not pertaining to a service, that is why you don't see information about Power Bi. We have another document which talks about sharing with Power Bi in detail -https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DeanGross Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DeanGross** [comment]
I still think that this page should include a discussion about sharing dashboards, just like it includes info about sharing teams and sites.
