### ISSUE TITLE
"Still need help" is outdated

### ISSUE THREAD

**Issue by potatoqualitee** [MicrosoftDocs/microsoft-365-docs#7972]
This is no longer accurate. There's no Microsoft Support to select.

```
Still need help?
If you have worked through all the steps in this article and still need help, contact technical support.

Go to [Microsoft 365 Defender](https://go.microsoft.com/fwlink/p/?linkid=2077139) and sign in.

In the upper right corner, select the question mark (?), and then select Microsoft support.

In the Support Assistant window, describe your issue, and then send your message. From there, you can open a service request.
```

![image](https://user-images.githubusercontent.com/8278033/157689057-7a6022f6-0eda-4013-a452-4762a3e77872.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d48adda3-8f2e-b13d-fbd7-b556d295bf85
* Version Independent ID: 46daacb8-1def-6af5-ccf1-61505bcedad4
* Content: [Address false positives/negatives in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide#still-need-help)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by potatoqualitee** [comment]
Thank you. Don't know if it's within scope of this page but ultimately, the link I was looking for was found here: https://www.microsoft.com/en-us/wdsi/filesubmission/

**Comment by denisebmsft** [comment]
Oh thank you for that! @potatoqualitee
