### ISSUE TITLE
Microsoft Defender - Linux Proxy setting field has unexpected or bad behavior.

### ISSUE THREAD

**Issue by UberMeatShield** [MicrosoftDocs/microsoft-365-docs#7975]
There is some very odd behavior in the linux defender clients around the proxy settings.   If you use an empty proxy string it will substitute in some strange hard coded microsoft proxy.   canonicalizer.ucsuri.tcs:80

That is broken for basically all users and doesn't even resolve anymore.   The documents should probably reflect that an empty proxy config (which in almost all of linux as "No Proxy") shouldn't add in some strange MS default.   The documentation should either mention this or maybe somebody can get an issue to the Defender team to change this behavior so that an empty proxy doesn't result in a broken app.

```
    "cloudService":{
       "automaticDefinitionUpdateEnabled":true,
       "automaticSampleSubmissionConsent":"safe",
       "enabled":true,
       "proxy": ""
    }
```

**Comment by denisebmsft** [comment]
Hello @UberMeatShield. Can you please tell us to which article your feedback applies? This information will help us route the issue correctly. Thank you!

**Comment by UberMeatShield** [comment]
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-preferences?view=o365-worldwide

Under the Sample profile section you will find that "cloudeService" block.
"proxy": "<EXAMPLE DO NOT USE> http://proxy.server:port/"

You DO need to use a proxy for many networks.  But some of our hosts had transparent proxies.   A note that if you define "proxy": "" will cause very odd behavior should be noted (or more likely the current functionality is not sensible).

**Comment by msbemba** [comment]
@UberMeatShield Thank you for your feedback. This sounds more like a bug or a design change is needed. You can raise the feedback directly with our Dev team here at https://feedbackportal.microsoft.com/

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@UberMeatShield Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
