### ISSUE TITLE
Creating modern template from Word doc exceptions

### ISSUE THREAD

**Issue by oliviadudley** [MicrosoftDocs/microsoft-365-docs#7976]
As a Syntax user, I want to create a modern template with placeholders in tables so that I can use already existing Word templates and not spend time creating new ones.

Under **Create a modern template** section, at the end of number 5, please add (or a note to this effect):

>[!NOTE] You cannot add placeholders within a table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab6e35ec-e5f9-d97f-64c6-f0637f3aef09
* Version Independent ID: ab6e35ec-e5f9-d97f-64c6-f0637f3aef09
* Content: [Create documents using content assembly in Microsoft SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/content-assembly)
* Content Source: [microsoft-365/contentunderstanding/content-assembly.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/content-assembly.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
Thank you for the feedback. We are looking into it and will let you know.

**Comment by chuckedmonson** [comment]
Updated content accordingly. Thank you for your suggestion.

**Comment by oliviadudley** [comment]
Hello, 
Just for clarification, the update does not indicate that text placeholders are not allowable in tables. Please reopen.

**Comment by chuckedmonson** [comment]
@oliviadudley -- Thank you for the follow up. It says that tables aren't supported (thereby placeholders in tables are not supported. Do you think that needs to be clearer? Thank you.
