### ISSUE TITLE
Incorrect API permission specified

### ISSUE THREAD

**Issue by wadstromtech** [MicrosoftDocs/microsoft-365-docs#7977]
Hi,

The required API permissions specified (AdvancedHunting.Read.All) is incorrect , the correct permission is called AdvancedQuery.Read.All.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea8d6114-48d6-9157-0cbe-2b33440c7eb3
* Version Independent ID: 2aa1b7a5-0d0f-1a1d-2091-28360fef0363
* Content: [Microsoft 365 Defender advanced hunting API](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-advanced-hunting?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/api-advanced-hunting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/api-advanced-hunting.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@wadstromtech Thank you for your feedback. We have made changes via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8059

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @wadstromtech Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
