### ISSUE TITLE
Advanced eDiscovery limits in Step 4 seem off

### ISSUE THREAD

**Issue by mastood** [MicrosoftDocs/microsoft-365-docs#7979]
In step 4 we have the following text:

**If a custodian or end user is assigned an Office 365 E5 license, you can examine up to 10,000 search results at once using Advanced eDiscovery. If there are more than 10,000 email messages to review, you can divide the search query by date range and review each result individually as search results are sorted by date.** 

I don't believe this is a valid limit anymore, per this https://docs.microsoft.com/en-us/microsoft-365/compliance/limits-ediscovery20?view=o365-worldwide#search-limits 

**Maximum number of items from all mailboxes displayed on preview page for searches. | 1,000**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eab6813-2ac7-7ab4-50f1-454a350163ba
* Version Independent ID: f63bf91f-494a-dbb1-2262-35d44e586519
* Content: [eDiscovery solution series Data spillage scenario - Search and purge - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-spillage-scenariosearch-and-purge?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/data-spillage-scenariosearch-and-purge.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-spillage-scenariosearch-and-purge.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mastood Thanks for the heads up. I think you are correct; this may have been a previous limit for review set items in Advanced eDiscovery. Looks like new limit is 3M items. I will update this topic. Thanks again.

**Comment by mastood** [comment]
So not sure if the text in the article actually refers to a review set.  In a data spill scenario I would probably not want to copy the data to a review set as that will expand my spill.  I think the text I highlighted refers to the Preview capabilities after running a search/colllection.  AeD used to have its own experience here, now AeD/Core/Content Search all share the same experience I believe.
________________________________
