### ISSUE TITLE
PS Cmdlet incorrect

### ISSUE THREAD

**Issue by sinnamingrrl** [MicrosoftDocs/microsoft-365-docs#7980]
Get-QuarantinedMessage -RecipientAddress officeparty@contoso.com

Remove the D from "Quarantine"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6962b118-bc67-caa7-ebad-830792611a67
* Version Independent ID: 43956aab-5f2a-de67-c252-65e8fdb9c39e
* Content: [View and release quarantined messages from shared mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-and-release-quarantined-messages-from-shared-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-and-release-quarantined-messages-from-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-and-release-quarantined-messages-from-shared-mailboxes.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@sinnamingrrl, fixed. In the future, you too can make fixes like this directly without opening a GitHub issue first. For instructions, see <https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md>.

Thanks for the feedback.

Closing
