### ISSUE TITLE
Where are attachements encrypted through OME stored and how can the data be deleted?

### ISSUE THREAD

**Issue by Xentraxx** [MicrosoftDocs/microsoft-365-docs#7984]
Hello everyone,

according to https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#how-long-do-i-have-access-to-the-mail-in-the-ome-portal-
an through OME encrypted message and its attachement is accessible (stored) indefinitely in the OME Portal, if the receiving mail client does not support OME decryption.
I am missing where this information is being stored in this case. In the tenant of the sender? Does the receiver access the mail and attachements through the OME Portal directly from the senders exchange online?

In the documentation of https://docs.microsoft.com/en-us/powershell/module/exchange/set-omemessagerevocation?view=exchange-ps
I unfortunately can't find any information if the use of this command is not only revoking access but also deleting the data from the OME portal.

How can the mail and its attachement be deleted at the storage location, without using Advanced Message Encryption?
This is very relevant for GDPR compliency.

Thank you and I am looking forward to answers.

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks
