### ISSUE TITLE
Outlook requirements incomplete

### ISSUE THREAD

**Issue by rsparnaaij** [MicrosoftDocs/microsoft-365-docs#7985]
In the Outlook requirements section, it only refers to Outlook 2016/2019 and doesn't mention Outlook as part of an Office 365/Microsoft 365 subscription at all.

As far as I know, it works with all M365 Business, Enterprise and Education licenses but not with the Home or Personal licenses. So even when you are connecting to a mailbox with an E5 license assigned, the Home user will not see the Auto-Expanding Archive in Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a21b69-2f7c-d54d-d8a1-5512b810b4bf
* Version Independent ID: 19126a83-c4af-bd0c-6a20-76e27db675c9
* Content: [Learn about auto-expanding archiving - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/autoexpanding-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/autoexpanding-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@rsparnaaij Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8060

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rsparnaaij Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
