### ISSUE TITLE
Descriptions are lacking and/or inaccurate

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/microsoft-365-docs#7991]
The feedback below refers to the table listed in [Device Properties](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-removable-storage-protection?view=o365-worldwide#device-properties) section of this page.

It would be helpful if you specified where to find the property information for an attached device, for example in Device Manager. You're leaving it up to the reader to figure this out. It would also be beneficial if you listed the exact Device Manager property name that maps to these properties in the description.

### Device class
The Description's first sentence talks about Device ID, instead of Device Class, which is irrelevant to Device Class. There is also no example of how to specify the Device class property. Do you use the Class property, or the ClassGuid property?
Primary ID property - There is no example of how to specify the Primary ID property, and there is no direct reference in Device Manager for this property, so I have absolutely no idea how to define this, or what the purpose of this property is.

### Instance ID
You are leaving it to the reader to figure out what is being stated for this property and some of the other properties. For example the Instance ID description states

> A string uniquely identifies the device in the system, for example, USBSTOR\DISK&VEN_GENERIC&PROD_FLASH_DISK&REV_8.07\8735B611&0".

This would be better worded as "A string that uniquely identifies the device in the system..."

### Friendly Name
I'm not sure what I can say about the Friendly Name property. The description is horrible and where do I get it from? What property name in Device Manager is this referencing?

> A string attached to the device, for example, Generic Flash Disk USB Device

What does "A string attached to the device" even mean? What property name can I get this from in Device Manager?

### Vendor ID / Product ID
There is no example or where you get this from in Device Manager.

### Serial NumberID
There is no example or where you get this from in Device Manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ede5698-6581-bc4e-03a4-5bb49e92f1c7
* Version Independent ID: e725d98a-8889-1c09-97fb-4813cfe475cd
* Content: [Microsoft Defender for Endpoint Device Control Removable Storage Protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-removable-storage-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-control-removable-storage-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-control-removable-storage-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Hello @yogkumgit! I have opened a work item (6246506) for our team. I don't know the exact timing on this but will track it. I'll post an update here as soon as I know more.

**Comment by denisebmsft** [comment]
@yogkumgit the work item is assigned, and the writer needs some help from the PM. We're waiting on that.

**Comment by denisebmsft** [comment]
Hello @poortom1004. Thank you again for letting us know about the documentation issue. The article has been updated and republished. https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/15415
