### ISSUE TITLE
F5 licences also have access to the Content Explorer

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#7992]
You do not mention that F5 licences have access to Content Explorer. According to the Security and Compliance licencing see link) F5 licences do have access

https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection-data-classification-analytics-overview-content--activity-explorer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334e743d-c929-c74a-c996-2b8e0b68a46b
* Version Independent ID: 91c4563c-72c1-4655-72f7-d467b6098540
* Content: [Get started with content explorer - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-content-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/data-classification-content-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/data-classification-content-explorer.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. Looks like users licensed with Microsoft 365 F5 Security & Compliance or Microsoft 365 F5 compliance Add-on can benefit from Microsoft 365 data classification analytics (Content and activities explorer). I have added that information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8061

Once the author approves, the changes will be live.

Thanks
Sri
