### ISSUE TITLE
the sign in commands with MFA - they prompt for credentials 5 times (for each connect-...)

### ISSUE THREAD

**Issue by ramponnuram** [MicrosoftDocs/microsoft-365-docs#7999]
the sign in commands with MFA - they prompt for credentials 5 times (for each connect-...)

Example : My powershell script pulls data from AzureAD and Msolservice
If it has connect-azuread & connect-msolservice, I am being prompt to key in my credentials twice and MFA authentication twice.
any way to reduce that to 1 time credential entry and 1 time MFA authentication ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6adeef66-5e54-ba2f-37ac-c1898ef942c6
* Version Independent ID: f8a6eda6-b300-dc76-4392-9aeb6c532822
* Content: [Connect to all Microsoft 365 services in a single PowerShell window - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-all-microsoft-365-services-in-a-single-windows-powershell-window.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@ramponnuram Thank you for your feedback. As long as you have the credential cached in the variable ($credential) it prompts only once.

I tested it with the below script. 

$acctName="<UPN of the account, such as belindan@litwareinc.onmicrosoft.com>"
$orgName="<for example, litwareinc for litwareinc.onmicrosoft.com>"
#Azure Active Directory
Connect-MsolService
#SharePoint Online
Connect-SPOService -Url https://$orgName-admin.sharepoint.com
#Exchange Online
Import-Module ExchangeOnlineManagement
Connect-ExchangeOnline -UserPrincipalName $acctName -ShowProgress $true
#Security & Compliance Center
Connect-IPPSSession -UserPrincipalName $acctName
#Teams and Skype for Business Online
Import-Module MicrosoftTeams
Connect-MicrosoftTeams


However, I understand you are trying to connect to AAD twice in the same script Connect-AzureAD and Connect-MsolService. I'd recommend you contact support and get help from them or if this is a bug, they can escalate and get this fixed for you.

Hope this helps!

Thanks
Sri

**Comment by ramponnuram** [comment]
@msbemba Thank you for getting back.

I believe the $Credential process works only if you don't have MFA authentication. In our case we need MFA authentication. Both Connect-MSolservice and Connect-AzureAD and few others don't use -credential option when MFA is required.

**Comment by msbemba** [comment]
@ramponnuram Thank you for the response. With MFA it is supposed to prompt you every time there is a connection to a different module. Sorry, I missed the MFA part of your comment. So this is by design and it is working as expected. If you think it will be a good idea to implement a single block connection by entering MFA one time, you can propose it on our Main feedback portal - https://feedbackportal.microsoft.com/. One of our Dev or Product team members will contact you and provide information.

Hope this helps!

Thanks
Sri
