### ISSUE TITLE
 Site_ SearchableSiteProperty does not work

### ISSUE THREAD

**Issue by Allaen** [MicrosoftDocs/microsoft-365-docs#800]
The article mentions that any searchable site property can be used to limit which sites users can search Site_ SearchableSiteProperty. In SPO this only seems to work with the Site_Path property. The information given for OneDrive for Business seems to be incorrect as well, given that we have to raise a request with MS to set the Site_ComplianceAttribute to be able to limit searches for OneDrive for Business. The information given here seems to be inconsistent with the article about Compliance Boundaries in O365. https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97efdb7a-efb0-f786-b901-d64d055efd5a
* Version Independent ID: 559ce33c-b1e2-966f-62a7-55f226a97477
* Content: [Configure permissions filtering for Content Search](https://docs.microsoft.com/en-us/microsoft-365/compliance/permissions-filtering-for-content-search#feedback)
* Content Source: [microsoft-365/compliance/permissions-filtering-for-content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/permissions-filtering-for-content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@allaen The list of Azure Active Directory user attributes in the compliance boundaries topics are the only ones that you can use (and request MS Support to enable) for compliance boundaries. That doesn't mean you can't use other [searchable site properties](https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions#searchable-site-properties) for a search permissions filter. Suggest you contact MS Support if other site searchable properties aren't working.

**Comment by Allaen** [comment]
@markjjo Thank you for the clarification. I still think that information given in the article is confusing. The section below from the original article says that you can use any searchable site property. The link that you've posted suggests otherwise, namely just a small subset of searchable site properties can actually be used.

For a list of searchable site properties, see Overview of crawled and managed properties in SharePoint. Properties marked with a Yes in the Queryable column can be used to create a site or site content filter.
