### ISSUE TITLE
Lack of Updates

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#8005]
Nothing has been added in over 6 months, given the rapid pace of change in M365, I find this unusual. Is this actually true or have some updates been missed?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a000fe-4f18-dae2-ae48-1ce63336e238
* Version Independent ID: 8e6afd9c-0d67-718a-e93b-b7e57f9b5b38
* Content: [What's new in Microsoft Secure Score](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score-whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-secure-score-whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-secure-score-whats-new.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@DeanGross Thank you very much for the your feedback. Documentation team is continuously improving the documents as per the predefined schedule. Kindly keep checking. If you see a particular information is missing please feel free to open a new issue or contact support,  We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
