### ISSUE TITLE
Typo in image 

### ISSUE THREAD

**Issue by stevenjudd** [MicrosoftDocs/microsoft-365-docs#8006]
There is a typo in the [Fundamental parts of a sensitive information type image](https://docs.microsoft.com/en-us/microsoft-365/media/dc68e38e-dfa1-45b8-b204-89c8ba121f96.png?view=o365-worldwide). "Pattern" is missing an "n" in the top left text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1edffc-5d5e-8ed8-a7d1-7467fb14b3d1
* Version Independent ID: 13a701b4-3dfa-2b1b-2ff2-445183a1f1eb
* Content: [Learn about sensitive information types - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-learn-about?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/sensitive-information-type-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitive-information-type-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@stevenjudd Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8066

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @stevenjudd Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
