### ISSUE TITLE
Prevent Message deletion in groups?

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/microsoft-365-docs#8010]
"Message deletion: Unfortunately, you can't prevent people from deleting **messages** in a shared mailbox. The only way around this is to create a Microsoft 365 group instead of a shared mailbox"
Can we have a cross-reference  citing this?

**Comment by yogkumgit** [comment]
@jadesolis Please indicate the name of the document, your feedback applies to. Thanks

**Comment by jadesolis** [comment]
> Please indicate the name of the document, your feedback applies to. Thanks
I am the one requesting for for the document. The article is mentioning a Microsoft 365 group feature but no citation is provided

**Comment by msbemba** [comment]
@jadesolis Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8063

Note that When an email is deleted from the group mailbox, it is not deleted from any of the group members' personal mailboxes which is not the case with Shared mailboxes.

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The changes are live. This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jadesolis Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
