### ISSUE TITLE
High Confidence Spam

### ISSUE THREAD

**Issue by robarismail97** [MicrosoftDocs/microsoft-365-docs#8012]
Hi!

I have discovered that the action you have on the "high confidence spam" in anti spam policy is the action for the blacklist you have in Defender for Office365. Am I correct? Why is this not presented anywhere?

Br,
Robar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 372a5793-33b9-b7a4-d965-aa4237470b17
* Version Independent ID: 1242ce47-2528-3446-8d95-9a17f7022749
* Content: [Manage your blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-tenant-blocks?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/manage-tenant-blocks.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-tenant-blocks.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@RatulaC Please help in resolving this issue. Thanks

**Comment by RatulaC** [comment]
There is a note added to the Manage your blocks in the Tenant Allow/Block List article:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/81324214/172222518-b7199c57-09fc-4595-b0db-dae8af33c222.png">

**Comment by robarismail97** [comment]
When adding senders to the block list, will they get 9 SCL score or less?
