### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by badsector-82** [MicrosoftDocs/microsoft-365-docs#8014]
Hello guys,
In the section "3. Create new or edit your existing organization relationship object to your source tenant." the script starts with 
```
$sourceTenantId="[tenant id of your trusted partner, where the source mailboxes are]"
$orgrels=Get-OrganizationRelationship
$existingOrgRel = $orgrels | ?{$_.DomainNames -like $sourceTenantId}
```
But the DomainNames parameter specifies the SMTP domains of the external organization, not the tenantID.

I see it's the same with the next script "3. Create new or edit your existing organization relationship object to your target (destination) tenant from an Exchange Online Remote PowerShell window."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@badsector-82 Thank you for your feedback. I was able to test and it works and it is not a typo error. 

When you run $orgRel = Get-OrganizationRelationship | ? { $_.DomainNames -contains $targetTenantId } it does fetch the information. You can test it again by executing $orgrel and if there are issues or no results, I'd recommend you contact support via the need help icon on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @badsector-82 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
