### ISSUE TITLE
What is the limit for adding trusted senders and domains?

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/microsoft-365-docs#8016]
How many entries can we add to trusted senders and domains? Out domain has a name of a city in it, so domain impersonation triggers on hundreds of legitimate senders that have the city name in their email or display name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ea08aa-4520-8f48-93e2-0ce74cd43298
* Version Independent ID: 7be23d3d-f72b-abd3-e2c4-96ff3998a59b
* Content: [Configure anti-phishing policies in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@itishnitsa, from the conceptual companion to that procedural article you referenced:

 <https://docs.microsoft.com/icrosoft-365/security/office-365-security/set-up-anti-phishing-policies>

> [!NOTE]
>
> - In each anti-phishing policy, you can specify a maximum of 350 protected users (sender email addresses). You can't specify the same protected user in multiple policies. So, regardless of how many policies apply to a recipient, the maximum number of protected users (sender email addresses) for each individual recipient is 350. For more information about policy priority and how policy processing stops after the first policy is applied, see [Order and precedence of email protection](https://docs.microsoft.com/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined).


> [!NOTE]
> The maximum number of protected domains that you can define in all anti-phishing policies is 50.

But, I would contend that you don't want to eliminate impersonation protection because of issues with your domain name. In fact, you're sure that your domain name is causing the false positive hits as impersonation attempts? You should open a support case and see if there's anything else that can be done.

**Comment by chrisda** [comment]
From that same topic:

<https://docs.microsoft.com/icrosoft-365/security/office-365-security/set-up-anti-phishing-policies>

- **Add trusted senders and domains**:  ... The maximum limit for these lists is 1024 entries.

My same last comment about not eliminating impersonation protection applies.

**Comment by chrisda** [comment]
@itishnitsa, in looking at the article:

 <https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies>

Most of the information was already there:

> In each anti-phishing policy, you can specify a maximum of 350 protected users (sender email addresses). You can't specify the same protected user in multiple policies.

> You can have a maximum of 50 domains in all anti-phishing policies.

The only one missing was 1024 for trusted senders and domains, so I added that.

Thanks for the feedback.

Closing
