### ISSUE TITLE
Logs retention for other SKUs

### ISSUE THREAD

**Issue by LeonardoFelippine** [MicrosoftDocs/microsoft-365-docs#802]
Hello.

The document lists retention for E3 and E5 licenses. How about other licenses, such as E1, Business, etc?

Regards.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-gb/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@LeonardoFelippine If a subscription offers unified audit logging and it's not E5, then audit record retention is 90 days. See https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center
