### ISSUE TITLE
Note: Add-in is greyed out for shared/group or delegate mailbox

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/microsoft-365-docs#8020]
Please add a note that Add-in is greyed out for shared/group or delegate mailbox!

See:
https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/2607388
https://techcommunity.microsoft.com/t5/exchange/report-message-add-in-and-shared-mailboxes/m-p/1688407

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@trudolf-msft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8073

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @trudolf-msft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
