### ISSUE TITLE
AST Payload automation - instructions refer to Simulation Automation

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#8024]
This page is for 'PAYLOAD AUTOMATION'. the instructions in point 2 talk to 'Simulation Automations'

"2. On the Payload automations tab, select Create simulation icon. Create simulation."

This, *and the screen image/picture* ...  needs to be changed to "2. On the Payload automations tab, select Create AUTOMATION icon. Create AUTOMATION."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d554e47-e3cc-8c1f-b96f-5f031b04c406
* Version Independent ID: 3d554e47-e3cc-8c1f-b96f-5f031b04c406
* Content: [Payload automations for Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-payload-automations?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-payload-automations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-payload-automations.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@gbms311, fixed.

Thanks for the feedback.

Closing
