### ISSUE TITLE
Please add "View Data" to the (already predefined) Azure Global Reader & Azure Security Reader roles

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/microsoft-365-docs#8026]
So while I appreciate this is an improvement in Security - but the way this has been done means that as we (Gold MS Security Partner) try to help Customers this means we have to help the customer understand what you have done + adds more manual steps that need to be done before we can gain Read Only access to the Customer environment to help them.

This is something of a backward step - not everyone is fully aware that there are some subtleties' like this where the Roles in the M365 Consoles are *NOT* derived directly from the AAD Roles/Permissions. 

I would ask you to reconsider this & at least allow least privilege thru to the Global and Security Reader roles
Please add "View Data" to the (already predefined) Azure Global Reader & Azure Security Reader roles

Regards,
Dave Caddick
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 796818f1-67d6-9a20-9498-94baf03276d6
* Version Independent ID: a9293050-acc0-7710-52cf-5cf64689d719
* Content: [Create and manage roles for role-based access control](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/user-roles?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/user-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/user-roles.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@dcaddick Thank you for your feedback. The requested design change needs to go through our dev team. You can leave the feedback directly on our Main feedback portal: https://feedbackportal.microsoft.com/ and one of the dev/product team members will be looking into it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@dcaddick Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
