### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by madirap** [MicrosoftDocs/microsoft-365-docs#803]
Getting Cryptic Validation error for the Ruleset 
Request: /api/DlpSensitiveInformationTypeRulePackage/?rulePackId=fd098e03-1796-41a5-8ab6-198c93c66666
Status code: 500
Exception: System.InvalidOperationException
Diagnostic information: {Version:17.00.3774.006,Environment:NCUPROD,DeploymentId:18d19f7d03b848d7a3f3fb735faaefc6,InstanceId:WebRole_IN_0,SID:440b7fa5-4445-4735-9636-23fcc0fe06fa,CID:3b3549b9-0111-41cf-b764-f8070140af6d}
Time: 2019-11-20T13:00:50.4649039Z

When Attempting to test it , getting the following error.
Request: /api/DlpTestCustomClassification
Status code: 500
Exception: Microsoft.Exchange.PswsClient.PswsException
Diagnostic information: {Version:17.00.3774.006,Environment:NCUPROD,DeploymentId:18d19f7d03b848d7a3f3fb735faaefc6,InstanceId:WebRole_IN_1,SID:440b7fa5-4445-4735-9636-23fcc0fe06fa,CID:3ed547f5-ef6e-4adf-8062-a511e1434fa4}
Time: 2019-11-20T13:03:35.4057841Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2025905a-4c94-a7bd-41ca-c60be85b6a64
* Version Independent ID: a608cae7-0e3e-bc61-264a-44aef1f9da81
* Content: [Create custom sensitive information types with Exact Data Match](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification#feedback)
* Content Source: [microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@madirap - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
