### ISSUE TITLE
Clarification on Message Type properties

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#8031]
Hi There, under message type properties, we have listed:

Message type matches | condition: MessageTypeMatchesexception: ExceptIfMessageTypeMatches | MessageType | Messages of the specified type.

Wondering if we may be able to put a link in there that points to what these message types mean. Most are clear, but had a customer try to detect OME encrypted mails using message type: Encrypted, and found out that this was for S/MIME.  The right answer ended up being permission controlled (confirmed by the DLP PG). Just thinking the more clarity we can provide, it will really empower users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28be949f-8589-8f7c-8e08-c029389a1f6e
* Version Independent ID: f5928319-0360-41fa-dda0-5473b4e1a5b2
* Content: [DLP policy conditions, exceptions, and actions - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-conditions-and-exceptions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-conditions-and-exceptions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-conditions-and-exceptions.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8091

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dkotars Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
