### ISSUE TITLE
Label Propagation Times / article update request

### ISSUE THREAD

**Issue by o365eng** [MicrosoftDocs/microsoft-365-docs#8036]
Hi All,

  This is related to Bugs: 2638958, 2655903. 

Ask: Can the article be updated to reflect different verbiage other than new labels can take 1 hour to propagate. 

- Example: You can start checking propagation within the hour however please grant 24 to 48 hours to propagate throughout the services. 
------
 -Per Article: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide#publishing-and-changing-sensitivity-labels
- It states: The following changes replicate within one hour: New and deleted sensitivity labels, and sensitivity label policy settings that include which labels are in the policy.
The following changes replicate within 24 hours: Changes to sensitivity label settings for existing labels.
Because the replication delay is only one hour for new sensitivity labels, you are unlikely to run into the scenario in the example. 
---------------------
   - Per article: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide#publish-sensitivity-labels-by-creating-a-label-policy

It states: Remember to factor in timing dependencies that can sometimes delay sensitivity labels and label policies from working as expected. For example, populating a new group and group membership changes, network replication latency and bandwidth restrictions, and group membership caching by the Azure Information Protection service for labels that apply encryption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide#publishing-and-changing-sensitivity-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
After discussions with PM owners, created this new section & then for SPO new labels "at least one hour" and link back to it for details that now explain some external dependencies can take up to 48 hours: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide#when-to-expect-new-labels-and-changes-to-take-effect

**Comment by yogkumgit** [comment]
@o365eng Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
