### ISSUE TITLE
Add the description about Get-RoleGroupMember "Organization Management"

### ISSUE THREAD

**Issue by mikumeda** [MicrosoftDocs/microsoft-365-docs#8037]
One quick feedback.

![image](https://user-images.githubusercontent.com/61782095/158658936-6d00acb2-ea8e-40bb-bc58-4f169b509aa3.png)

It says that Global admins are automatically added as members of this role group, but you could not confim any account infos in Get-RoleGroupMember "Organization Management".
This might confuse the customer, so I guess we need to add the description that you can't find the account in Get-RoleGroupMember 
but it still works as a member of "Organization Management".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b34b5c8-b67e-72f2-0eba-d98b760f1d16
* Version Independent ID: adcd41fb-ffd1-f6d0-96ad-0036c0a677a7
* Content: [Permissions - Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center?view=o365-worldwide#permissions-needed-to-use-features-in-the-security--compliance-center)
* Content Source: [microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-in-the-security-and-compliance-center.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mikumeda, OK I expanded that last sentence to:

> Global admins are automatically added as members of this role group, but you won't see them in the output of the [Get-RoleGroupMember](/powershell/module/exchange/get-rolegroupmember) cmdlet in [Security & Compliance Center PowerShell](/powershell/module/exchange/get-rolegroupmember).

Thanks for the feedback.

Closing

**Comment by mikumeda** [comment]
Thanks for the quick response @chrisda! I don't see the expantion yet, but maybe I can wait a little. Thanks again.

**Comment by chrisda** [comment]
If it hasn't already published by now, it should publish tomorrow, Th 3/17 at approx 11:00 AM PDT.
