### ISSUE TITLE
Missing EnableAIPIntegration 

### ISSUE THREAD

**Issue by tollertenya** [MicrosoftDocs/microsoft-365-docs#804]
Installed 16.0.19418.12000 SharePoint Online PowerShell Module but Set-SPOTenant -EnableAIPIntegration is not possible due property is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@tollertenya - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by lightupdifire** [comment]
Hello,
The same issue ;) will check with Support team

**Comment by lightupdifire** [comment]
Hello,
An update, I could fix this by re-installing SharePoint Online from: https://go.microsoft.com/fwlink/p/?LinkId=255251

**Comment by kjwilso** [comment]
The re-install did the trick for me as well. Thanks!

**Comment by giveitaGo** [comment]
I tried the reinstall above and received an error about the install. I also couldn't uninstall SPO Mmgt Shell, so I had to use the link below to uninstall the version I had. Once uninstalled, I ran the install again, and it worked. I hope this helps someone.
https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed
