### ISSUE TITLE
Active Files v Non Active Files

### ISSUE THREAD

**Issue by gmparky** [MicrosoftDocs/microsoft-365-docs#8043]
Hi, It would be good to know what the definition is for an Active File is and the same with sites so we have a clear understanding of the metric. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a5a67cc-bf49-d25c-f89b-60dd30948f6d
* Version Independent ID: 56a98096-97f9-67d4-d2ed-befc800b6771
* Content: [Microsoft 365 admin center SharePoint site usage reports - Microsoft 365 admin](https://docs.microsoft.com/en-GB/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/sharepoint-site-usage-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@gmparky Thank you for your feedback. A file is considered active if it has been saved, synced, modified, or shared within the specified time period. I have made changes to the article via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8076

Thanks
Sri

**Comment by gmparky** [comment]
Thanks, it would be good to know what that specified time period is, my understanding is that it was actioned on that given day not say in the last 7 days for example.

**Comment by msbemba** [comment]
@gmparky Thank you for your response. The data is based on the number of days you choose, Like in the screenshot, the report is filtered for the past 30 days, in this case, the details show active files for the past 30 days.

![image](https://user-images.githubusercontent.com/45987684/159694492-3d6f1a57-9b1c-41f2-9b5c-811d9802f274.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gmparky Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
