### ISSUE TITLE
Retention Label Section

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#805]
This section needs to be redone.  Retention labels/policy should not be used for sensitivity.  Those are for file preservation and disposition.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files#office-365-retention-labels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d8b5b1-6343-5611-9b4a-2e0a1b7cab60
* Version Independent ID: dc3836a2-1176-e021-d6fc-a120bbeec7a8
* Content: [Secure SharePoint Online sites and files](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files#office-365-retention-labels)
* Content Source: [microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/secure-sharepoint-online-sites-and-files.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by joinimran** [comment]
@danmyhre Can you please share more details so that we can make corrections in the document.

Imran

**Comment by danmyhre** [comment]
This is probably something to bring to the product groups because there is confusion around which labels are for what, which systems support them, etc.  Having a recommendation in this article to use retention labels to drive sensitivity seems to be in conflict with the purpose of actual "Sensitivity Labels".  Using 2 different labeling sets for the same purpose can't be what the intended design is.

**Comment by joinimran** [comment]
@BrendaCarter Can you please share your input regarding request from danmyhre. Let me know know if there is anything that can be added in the doc so that I can create PR for the same.

Thanks.

**Comment by joinimran** [comment]
@BrendaCarter Any luck on this?

@mypil FYI Please.

**Comment by mypil** [comment]
@danmyhre - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by the author BrendaCarter so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
