### ISSUE TITLE
Callout for DKE Incompatibility with SCC DLP Policies

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#8050]
Can we confirm and note that DKE is incompatible with DLP Policies? It states some examples, but doesn't list DLP - which is common. If DKE is enabled for a Sensitivity Label, this does not allow you to configure DLP to trigger on the condition of Sensitivity Labels. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484b1a6d-dfd0-1da6-5405-7826ed4c088f
* Version Independent ID: 6e0ba9d2-aaa6-528a-daab-0e75c80f7135
* Content: [Double Key Encryption (DKE) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/double-key-encryption?view=o365-worldwide#when-your-organization-should-adopt-dke)
* Content Source: [microsoft-365/compliance/double-key-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/double-key-encryption.md)
* Service: **information-protection**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@SeanTGeoghegan Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
