### ISSUE TITLE
Add Global Admin information

### ISSUE THREAD

**Issue by ahuisentruit** [MicrosoftDocs/microsoft-365-docs#8051]
**I am the Documentation PM for Azure Subscription Management Support (ASMS).** 

We have never had documentation that outlines what a Global Admin can/cannot do as it relates to ASMS specifically.
While a Global Admin is at the tenant level, and many such requests are handled by the AAD team, ASMS gets a lot of requests from Global Admins asking us to perform certain actions. We need ASMS frontline support to be educated and unified in their response to our Global Admin customers about what requests of theirs ASMS can/cannot accommodate. 

I propose we add ALL of this info into an article:

While Global Admins, also known as Company Admins, are the first users in the tenant, and have the highest role, it does not necessarily grant them permission to perform actions at the subscription level. It only grants them visibility into the tenant, the ability to create users, remove users, reset passwords, etc., all AAD scope. 

At the subscription level, it is the Account Admin/Owner who has the right to make subscription requests. 

Additionally, Global Admins and EA Admins are different, and their permissions are different too. 
While a Global Admin may view all the subscriptions in a tenant, they do not have the rights to EA subscriptions either. 
Enterprise subscriptions fall under an EA enrollment, which has designated EA Admins. 
EA Admins manage everything about Enterprise Agreement enrollments, Account Owners, Enterprise subscriptions. 
A Global Admin is not allowed to make a subscription transfer request for EA subscriptions. 

For Enterprise subscription transfers to another EA or outside of an EA, an EA Admin must be involved and grant approval. 
The same goes for an EA enrollment transfer; that must be approved by EA Admins.
If an Enterprise subscription needs to be transferred to a different Account Owner within the same EA, an EA Admin may perform that action via self-serve via the EA portal. 

If an EA Account Owner wishes to convert their subscription from Enterprise to Enterprise Dev/Test, we may take their approval. We simply need to inform them of quota limit resets. If the subscription offer conversion request comes from a user who is not the Account Owner, then we would need EA Admin approval to convert the offer type. 

For non-EA subscriptions, we would only take Global Admin approval to perform subscription actions in an Orphaned Account Scenario.

**General Hierarchy:** Company tenant(s) > Global Admins > Accounts> Subscriptions

**EA Hierarchy:** EA enrollment environment (one or more tenants associated) > EA Admins > Account Owner > Enterprise Subscriptions

**EA subscription ownership transfers (SOT) and Scope of Support:** 
- An SOT of one or several subscriptions from one EA to another EA is supported by ASMS AP.
- An entire EA enrollment transfer is supported by EAL MCA team.
- An entire EA Account transfer is supported by EAL MCA team. 

**An SOT of some subscriptions from one EA to another EA requires ASMS AP Support Request and these details/approvals:**
- Source EA Admin approval:
- Source Account info:
- Source Account tenant:
- Source Account Country:
Subscriptions IDs to be transferred:
- Destination EA Admin approval:
- Destination Account info:
- Destination Account tenant:
- Destination Account Country:

Written acknowledgement from customer of Cross Tenant SOT consequences awareness
_It is best if an EA Admin submits this Support Request._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by dcaddick** [comment]
Hi @ahuisentruit,
I am very keen to understand this in more depth, as what you saying makes very good sense, and I'd like to get to the bottom of this for my own sanity. I'm specifically looking at this section/paragraph:
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/grant-access-to-the-security-and-compliance-center?view=o365-worldwide#what-do-you-need-to-know-before-you-begin
`Role group memberships aren't shared between Exchange Online and the Security & Compliance Center.`
Feel free to contact me on david.caddick@lab3.com.au and I'd be open to documenting this further.

Regards,
Dave C

**Comment by ahuisentruit** [comment]
Hi David,

@Liz ***@***.***> may be able to answer your question. She was working with Robert Lyon and Bill Anderson on this topic.

Thanks,
Ann Marie
ASMS Documentation PgM
Upcoming OOF: July 15-22

**Comment by tiburd** [comment]
@ahuisentruit 
Hi, Ann Marie,

I'm cc'ing you on email to the article author about this issue you submitted.

At your earliest convenience, please complete your account setup so that your GitHub and Microsoft accounts are connected:
- [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main)

Thanks!

**Comment by tiburd** [comment]
@ahuisentruit 
Hi, Ann Marie,

We're closing this issue due to age and inactivity.

If you want to add information to the article, we recommend creating a pull request in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/Office-Authoring-Guide/office-docs-authoring-overview?branch=main).

Thank you!

cc: @kwekuako @yogkumgit
