### ISSUE TITLE
Maybe we could add the Privacy dashboard? 

### ISSUE THREAD

**Issue by amcamillo** [MicrosoftDocs/microsoft-365-docs#8053]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87804d7-c76b-509d-eaa0-18b91b0563bd
* Version Independent ID: 7dc288f3-939a-590b-fe8b-31a266795fa3
* Content: [Microsoft security portals and admin centers](https://docs.microsoft.com/en-us/microsoft-365/security/defender/portals?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/portals.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/portals.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@amcamillo Thank you for your feedback. If you are referring to Smart reports and insights in the Security & Compliance Center, It is already included under portal name -Security & Compliance Center

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
