### ISSUE TITLE
Wrong Verb

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#806]
The proper verb to use would be "Set", not "Update"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by get-itips** [comment]
Hello @danmyhre 

Update- worked for me and Set- did not, am I missing something?

![image](https://user-images.githubusercontent.com/36666927/72014385-5e919780-3225-11ea-8263-c3ef14ad006b.png)

**Comment by danmyhre** [comment]
I was referring to the fact that the cmdlet is configured with the wrong verb, not that the documentation is wrong.  Update is not the proper verb based on powershell standards.

**Comment by get-itips** [comment]
Oh I see thanks for clarifying, the best way for your request to get to the product team, so they can decide to change this, is to open an user voice feedback here https://office365.uservoice.com/ as we are limited here to address issues in documentation.
Thank you 👍
