### ISSUE TITLE
Run antivirus scan - this is not shown in the UI

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/microsoft-365-docs#8064]
Hi,

i created a custom detection rule triggering an Antivirus Scan on a Server 2019.
you can see Eventid 1000,1001 but no Info in the UI during the Scan (like if you start a quick scan manually) 
maybe this is on purpose, but then the Info could help.

Further it would be nice to know which OS are supported, i couldn´t get 2016 or below to scan. But i guess that´s an OS limitation?

Kind Regards Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf510e0-742e-fce6-787e-18eb8a22f42d
* Version Independent ID: 23b77843-cf19-aacb-47af-1f51792c76a0
* Content: [Create and manage custom detection rules in Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/custom-detection-rules?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/custom-detection-rules.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/custom-detection-rules.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@schmurky Please help us in resolving this issue. Thanks

**Comment by schmurky** [comment]
Hello, this has to do with MDE logic, I suggest contacting for these two questions. [MDE support](https://docs.microsoft.com/microsoft-365/security/defender-endpoint/contact-support).
