### ISSUE TITLE
Suggestion for app-enforced restrictions section

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/microsoft-365-docs#8065]
[Hello, I've just read the brief section about app-enforced restrictions and think it should be adjusted https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/sharepoint-file-access-policies?view=o365-worldwide#use-app-enforced-restrictions-in-sharepoint

When you implement (i.e. change the SP admin setting) two conditional access policies are created automatically as enabled and set to all users. You can either use those or create your own to tell AAD what to do.

Also this sentence "This policy applies to all users, but only affects access to the sites you specify using PowerShell when you create the access controls in SharePoint." 

Not the case really, you get to decide how this will work as it can be scoped for users, groups or specific site/sites.

Thanks!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59a176eb-40a6-04de-2326-5fe8cdedcf76
* Version Independent ID: d400be85-3a13-7216-264d-92ee1f683b82
* Content: [Recommended secure document policies - Microsoft 365 for enterprise - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/sharepoint-file-access-policies?view=o365-worldwide#use-app-enforced-restrictions-in-sharepoint)
* Content Source: [microsoft-365/security/office-365-security/sharepoint-file-access-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/sharepoint-file-access-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ChristianJBergstrom Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8093

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by Dansimp** [comment]
Merged
