### ISSUE TITLE
no CIDR blocks or IP ranges

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#8067]
Hello,

Is it possible to know if in the future the CIDR blocks or IP ranges will be supported?

In the scenario we have the following:

1. Deployed basic Security Baseline policy that enabled Network Protection
2. The Engineering team (works with 3rd party devices via consoles, mostly NAT IPs used) complains that if they use Upload, the upload speed immediately starts slowing down and then stuck forever on almost 0

So we have to work with two policies to filter in one all Engineering team devices and set Network Protection to Disabled,
And all rest users devices with Network Protection to Enabled.

But it would be good if we have one single policy and then we simply whitelist NAT IPs, but because NAT is a quite large range, the IP ranges solution would be very useful :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0362931f-fb4c-ca1f-801e-b58a18613eae
* Version Independent ID: ed70b560-7c32-81b4-f138-6f58af9ef696
* Content: [Create indicators for IPs and URLs/domains](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-ip-domain?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/indicator-ip-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/indicator-ip-domain.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. I do not see this in the Roadmap items. The best way to get the design change request passed to the Dev/product team is to post the feedback in our main feedback portal - https://feedbackportal.microsoft.com/ 

This way one of the product team members will be able to analyze the request and respond to you directly. 

Hope this helps!

Thanks
Sri

**Comment by lightupdifire** [comment]
@msbemba Thanks!
