### ISSUE TITLE
current Whiteboard location?

### ISSUE THREAD

**Issue by newsgrep** [MicrosoftDocs/microsoft-365-docs#8070]
Considering that the [Whiteboard Storage is moved ](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=66767)to OneDrive for Business. 

I'm wondering why Whiteboard and "OneDrive for Business" are listed with different storage areas in many countries. 

btw: could you please write "Exchange Online Protection (EOP)" or whatever the name official Name is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
* Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
* Content: [Microsoft 365 data locations - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/o365-data-locations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/o365-data-locations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/o365-data-locations.md)
* Service: **o365-solutions**
* GitHub Login: @dmwmsft
* Microsoft Alias: **deanw**

**Comment by dmwmsft** [comment]
Whiteboard is still in an opt-in phase.  Once all defaulting is aligned we will update.

Dean

Sent from Outlook<http://aka.ms/weboutlook>
From: newsgrep ***@***.***>
Sent: Friday, March 18, 2022 11:57 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Dean Wierman ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/microsoft-365-docs] current Whiteboard location? (Issue #8070)


Considering that the Whiteboard Storage is moved <https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fmicrosoft-365%2Froadmap%3Ffilters%3D%26searchterms%3D66767&data=04%7C01%7Cdean.wierman%40microsoft.com%7Cf1e9844eb02841e3edea08da09111489%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637832266223630144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KYEnPobUxN%2F2Fum5uYb3iNSFt7aBp0d31OvKL5%2FnjM0%3D&reserved=0> to OneDrive for Business.

I'm wondering why Whiteboard and "OneDrive for Business" are listed with different storage areas in many countries.

btw: could you please write "Exchange Online Protection (EOP)" or whatever the name official Name is.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 61c6fa7b-7e9e-21a5-40da-adbd35040ec1
  *   Version Independent ID: 530df3b2-2048-8351-2f09-59e604aedf5b
  *   Content: Microsoft 365 data locations - Microsoft 365 Enterprise<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fenterprise%2Fo365-data-locations%3Fview%3Do365-worldwide&data=04%7C01%7Cdean.wierman%40microsoft.com%7Cf1e9844eb02841e3edea08da09111489%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637832266223630144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=354hwgYYk31B80xu4ovQ8tGMETcv6AVnEWX5N93M2%2F4%3D&reserved=0>
  *   Content Source: microsoft-365/enterprise/o365-data-locations.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fblob%2Fpublic%2Fmicrosoft-365%2Fenterprise%2Fo365-data-locations.md&data=04%7C01%7Cdean.wierman%40microsoft.com%7Cf1e9844eb02841e3edea08da09111489%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637832266223630144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FpCM%2BrRHsyB1IQ7G2zl2UX603mm1Lt%2FotWkfY9z5D%2B4%3D&reserved=0>
  *   Service: o365-solutions
  *   GitHub Login: @dmwmsft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdmwmsft&data=04%7C01%7Cdean.wierman%40microsoft.com%7Cf1e9844eb02841e3edea08da09111489%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637832266223630144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IaIwDBOPO%2B2r1Uy5d1URaDZWtv1s4O6RlcUoXGMmhuI%3D&reserved=0>
  *   Microsoft Alias: deanw

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fmicrosoft-365-docs%2Fissues%2F8070&data=04%7C01%7Cdean.wierman%40microsoft.com%7Cf1e9844eb02841e3edea08da09111489%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637832266223680140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=znLQtSjkwnKl59jK%2Fi%2B5aERtXG6NNTHrQbK3zKp8ugw%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOPQZVHOK37GYJA2YV3PU4LVATGXVANCNFSM5RCUY5XA&data=04%7C01%7Cdean.wierman%40microsoft.com%7Cf1e9844eb02841e3edea08da09111489%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637832266223680140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CCEddmuKGFIu9KUUuRIFq6gSlGcw72MzlsnorknLFAY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdean.wierman%40microsoft.com%7Cf1e9844eb02841e3edea08da09111489%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637832266223680140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aeiuNdELijsz7ePpGvCg4qVSVb24WCcVOA4soK%2BZ5pI%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdean.wierman%40microsoft.com%7Cf1e9844eb02841e3edea08da09111489%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637832266223680140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=36c3xXVgir94pHl0YEfG%2BItd8Pf1TsOFJJVQnoB0Fa0%3D&reserved=0>.

**Comment by yogkumgit** [comment]
@newsgrep Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
