### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#8074]
Hello,

Please explain, the subject set:

Web content filtering -> Applies to: -> Microsoft Defender for Endpoint Plan 1,Plan 1, Defender:

![image](https://user-images.githubusercontent.com/39700914/159255441-24591904-ed48-45d8-b429-5a2f1ce85a1d.png)

Where Microsoft Defender for Endpoint Plan 1 is a part of Microsoft 365 E3, then why is set:

<<<
Before trying out this feature, make sure you meet the following requirements:

Your subscription includes one of the following: Windows 10 Enterprise E5, Microsoft 365 E5, Microsoft 365 E5 Security, **Microsoft 365 E3 + Microsoft 365 E5 Security add-on**
>>>

If "Web content filtering -> Applies to: -> Microsoft Defender for Endpoint Plan 1" where Microsoft Defender for Endpoint Plan 1 is a part of Microsoft 365 E3, then why need **"+ Microsoft 365 E5 Security add-on"**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbaaa90e-6975-ee29-335a-545cb6a55986
* Version Independent ID: 75c93c17-4952-a13f-ed60-d2baefd0337e
* Content: [Web content filtering](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-content-filtering?view=o365-worldwide#prerequisites)
* Content Source: [microsoft-365/security/defender-endpoint/web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-content-filtering.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8162

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lightupdifire Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
