### ISSUE TITLE
VPN detection by other apps?

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/microsoft-365-docs#8075]
Are there any known issues with apps that might have implemented a VPN detection? Or won't such VPN detection not flag it as a VPN, as it is just a local loopback VPN?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f9dc4b7-9da6-9dc8-c240-6212010b6cf5
* Version Independent ID: 2bddc524-3c44-3684-dfba-1bbdd8799ca1
* Content: [Troubleshoot issues and find answers on FAQs related to Microsoft Defender for Endpoint on iOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-troubleshoot?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-troubleshoot.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-troubleshoot.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@sebhe Thank you for your feedback. There are no known issues related to apps that might have implemented a VPN detection. Having said that, the best to understand if this is a bug or to resolve, would be to contact support via the need help section on the M365 Admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sebhe Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
