### ISSUE TITLE
Powershell script looks fishy

### ISSUE THREAD

**Issue by ccanuel** [MicrosoftDocs/microsoft-365-docs#8077]
# Enable customization if tenant is dehydrated
  ***$dehydrated***=Get-OrganizationConfig | fl isdehydrated
  if (***$dehy*** -eq $true) {Enable-OrganizationCustomization}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@ccanuel Thank you for your feedback. I have corrected the script to reflect the correct variable. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8129

Once the author approves,  the changes will be live.

Thanks
Sri
