### ISSUE TITLE
Internal v- employee needs access to Visio. So far only view-only access. 

### ISSUE THREAD

**Issue by jenellean** [MicrosoftDocs/microsoft-365-docs#8079]
Opening or downloading a visio diagram from the team SharePoint site gives me view only access, even though the edit button is active and I select open in desktop app. 

There's a missing piece for giving internal employees access to the apps they need to do their job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffad00ee-7f49-e2a6-d01e-45b1ae7c6197
* Version Independent ID: 627f8975-213a-2cc4-53c7-2b5c03b1acee
* Content: [App requirements - Microsoft Managed Desktop](https://docs.microsoft.com/en-us/microsoft-365/managed-desktop/service-description/mmd-app-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/managed-desktop/service-description/mmd-app-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/managed-desktop/service-description/mmd-app-requirements.md)
* Service: **m365-md**
* GitHub Login: @tiaraquan
* Microsoft Alias: **tiaraquan**

**Comment by msbemba** [comment]
@jenellean Thank you for your feedback. The document is about App requirements and how we approach using Microsoft Managed Desktop. Since this query is related to Visio access, I'd recommend you contact the internal support team, to report this as a bug, if not to get the access level fixed.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jenellean Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
