### ISSUE TITLE
I can't find information in how to manage timezones for employees in Bookings.

### ISSUE THREAD

**Issue by stu6161** [MicrosoftDocs/microsoft-365-docs#8082]
I have set up a bookings page for my business.  But it doesn't seem to have a parameter anywhere to select the native time-zone for the business.

When I test setting up a booking, I see the software is using the same local timezone.  So presumably it uses the native timezone of the administrator of the site.

The problem I have now is that I have staff located in different time zones.  Do I have to convert their working hours to match the time zone of the site?  Or do I have to set up a new calendar for that specific time zone?  But even then, how do I set the native time zone for the booking site?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a11daa35-03f6-a8c6-bb10-7e7407581b87
* Version Independent ID: d033574c-fd2f-710d-1bab-20d2b4eea96f
* Content: [Employee working hours in Microsoft Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/employee-hours?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/employee-hours.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/employee-hours.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@stu6161 Thank you for your feedback. I was able to test this via Bookings-->Bookings Page-> Region and timezone settings.
This setting is explained in detailed here- https://docs.microsoft.com/en-us/microsoft-365/bookings/set-language-time-zones?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @stu6161 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
