### ISSUE TITLE
Alert notification methods

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#8083]
Please provide information about methods other than email to send out these alerts. Can we start a PowerAutomate flow or use an API, if so please provide some guidance. If not please state this explicitly 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c22bc78f-4f09-7bd5-4ee1-7cbbd4f42335
* Version Independent ID: c22bc78f-4f09-7bd5-4ee1-7cbbd4f42335
* Content: [Microsoft Compliance Manager alerts and alert policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-alert-policies?view=o365-worldAlwide)
* Content Source: [microsoft-365/compliance/compliance-manager-alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by yogkumgit** [comment]
@chvukosw Please help us in resolving this issue. Thanks

**Comment by chvukosw** [comment]
Right now, setting up alert policies are the only ways to set up alerts. I'll share your feedback with PMs, and if/when any other options are available we'll add them to documentation.
