### ISSUE TITLE
Clarify what changes would do to existing anonymous sharing links

### ISSUE THREAD

**Issue by nettyham** [MicrosoftDocs/microsoft-365-docs#8084]
From the article I cannot tell what the effect would be on already existing anonymous sharing links, and whether I should take additional steps to detect, expire or remove them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1b12dd3-e62d-a7ff-c597-9588cf6f1a23
* Version Independent ID: 231efccb-cfad-cf42-bd45-48bbcb2958d9
* Content: [Best practices for unauthenticated sharing](https://docs.microsoft.com/en-us/microsoft-365/solutions/best-practices-anonymous-sharing?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/best-practices-anonymous-sharing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/best-practices-anonymous-sharing.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@nettyham Thank you for your feedback. I'm currently testing and will update the document shortly.

Thanks
Sri

**Comment by MikePlumleyMSFT** [comment]
@nettyham, @msbemba, I checked on this and if you change the expiration time, existing links will keep their current expiration time if the new setting is longer, or be updated to the new setting if the new setting is shorter. I added this to the article.

**Comment by yogkumgit** [comment]
@nettyham Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
