### ISSUE TITLE
Missing steps on how to remove also the calendar permissions 

### ISSUE THREAD

**Issue by oliviacostisanu** [MicrosoftDocs/microsoft-365-docs#8094]
the documentation is missing also the steps to check where the user had calendar permissions and how to remove, revoke the sharing, because after an account is removed the display name will still show under calendar permissions and it needs manual cleaning 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6245943-00b8-c47b-f739-731531d5d357
* Version Independent ID: a9ec7066-ed8c-7b77-1d87-8c50bf74ec6c
* Content: [Delete a user from your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/delete-a-user?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/delete-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/delete-a-user.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@oliviacostisanu Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8164

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @oliviacostisanu Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
