### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/microsoft-365-docs#8095]
(https://go.microsoft.com/fwlink/p/?LinkId=525629)
The VS Web Essentials link is a dead link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eea369bc-1eca-8279-fd5d-8615d4b8c4f0
* Version Independent ID: 9891ab3e-82dc-4823-34b3-9c893471d24f
* Content: [Minification and bundling in SharePoint Online - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/Enterprise/minification-and-bundling-in-sharepoint-online?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/minification-and-bundling-in-sharepoint-online.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/minification-and-bundling-in-sharepoint-online.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by RAJU2529** [comment]
@yogkumgit still pr #8104 is not merged.

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @GitWesDone Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
