### ISSUE TITLE
High-Risk Delivery Pool and Outbound Spam Policy Sending Limits Relationship

### ISSUE THREAD

**Issue by dataCollegechurch** [MicrosoftDocs/microsoft-365-docs#8096]
This article states that "To prevent this, all outbound messages from Microsoft 365 datacenter servers that's determined to be spam or that exceeds the sending limits of [the service](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits-across-office-365-options) or [outbound spam policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide) are sent through the high-risk delivery pool."

Can you provide clarification on which outbound spam policy sending limits you are referencing. I was under the impression that when one of the outbound spam policy limits is exceeded the system will follow the action specified in the "Over limit action" field.
I.E the user is restricted from sending mail altogether for a certain amount of time or "no action, alert only".  If we select to restrict, via the "Over limit action" field, I don't see how the HR Delivery Pool could apply because mail is restricted. If we select "no, action, alert only" is it true that future mail sent from the individual would go through the HR Delivery Pool for a certain amount of time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2dee626-2897-aa19-46c9-8cbafa54035d
* Version Independent ID: e69c5a66-6591-d1b8-9fcc-ad303b86b415
* Content: [Outbound delivery pools - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/high-risk-delivery-pool-for-outbound-messages?view=o365-worldwide#high-risk-delivery-pool)
* Content Source: [microsoft-365/security/office-365-security/high-risk-delivery-pool-for-outbound-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/high-risk-delivery-pool-for-outbound-messages.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by yogkumgit** [comment]
@dataCollegechurch Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
