### ISSUE TITLE
Quarantines same non spam sender over and over 

### ISSUE THREAD

**Issue by mmyersak** [MicrosoftDocs/microsoft-365-docs#8097]
On the https://go.microsoft.com/fwlink/?linkid=874388   page it would be nice how to show the how to add sender to NOT spam.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd59e09-8b82-5c4e-a06f-3e468c9c3273
* Version Independent ID: 2ec32405-bc7a-60f2-782b-b527a2746b11
* Content: [Quarantined messages FAQ](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-faq.yml)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mmyersak, that go link you mentioned appears to be used in the Quarantine UI for find and release messages, and the target topic appears to be appropriate: [Find and release quarantined messages as a user in EOP](https://docs.microsoft.com/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user).

The only thing a non-admin user can do is to [add that sender to their own Safe Senders list in Outlook](https://support.microsoft.com/office/add-recipients-of-my-email-messages-to-the-safe-senders-list-be1baea0-beab-4a30-b968-9004332336ce]. They can also report the message as a false positive, which may or may not alert the admin, depending on how reporting options are configured. Of course, admins have more options to report false positives and to prevent messages from being blocked.

Not sure of the best way to proceed.

**Comment by yogkumgit** [comment]
@mmyersak Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
