### ISSUE TITLE
Update Document to include latest AzCopy version

### ISSUE THREAD

**Issue by msmerimoldi** [MicrosoftDocs/microsoft-365-docs#8099]
This document uses an older version of AzCopy which is out of support. 

Please work on updating this document and other O365 to use the latest version of AzCopy. If you need assistance from the AzCopy team, please ping me internally and I can connect you to them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4a7669-66ac-d8d6-7f9b-2b2713a845a3
* Version Independent ID: 279922bb-2dff-f8e9-96f7-ed64d5680d0a
* Content: [Error remediation when processing data - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/error-remediation-when-processing-data-in-advanced-ediscovery?view=o365-worldwide#remediating-errors-by-uploading-the-extracted-text)
* Content Source: [microsoft-365/compliance/error-remediation-when-processing-data-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/error-remediation-when-processing-data-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. Thanks

**Comment by markjjo** [comment]
@msmerimoldi Thanks for comment. As you probably know, the error remediation UX auto-generates an azcopy command using v8.1 syntax. So this is more than a documentation issue. If you are MSFT internal,  please contact the eDiscovery engineering team or open a work item for this change. If you are external, I think you could contact MS Support to log a DCR.
