### ISSUE TITLE
Missing header: EFV:NLI

### ISSUE THREAD

**Issue by MrM40** [MicrosoftDocs/microsoft-365-docs#810]
Please add description of this header :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@MrM40 - Thank you for submitting feedback.

Your request has been answered based on based on https://github.com/MicrosoftDocs/microsoft-365-docs/issues/486#issuecomment-540828898.  Hence, closing this issue.

Please feel free to open a new issue if you find any documentation error or if there is a specific area of the docs that we can improve on and we will be glad to help fix it. Thank you.

**Comment by freakynl** [comment]
It has NOT been answered.
