### ISSUE TITLE
Setup Guide Document, the first 2 images for the LINK and the LANDING PAGE are OUT OF DATE

### ISSUE THREAD

**Issue by chasman157** [MicrosoftDocs/microsoft-365-docs#8106]
On page 1 of this Setup Guide Document, the first 2 images for the LINK and the LANDING PAGE are OUT OF DATE

Excerpt from DOC:: 

**How to access setup guides in the Microsoft 365 admin center**
The setup guides are accessible from the [Setup guidance](https://aka.ms/setupguidance) page in the [Microsoft 365 admin center](https://admin.microsoft.com/). You can keep track of the status of your progress and return at any time to complete a guide. To reach the Setup guidance page:

1. In the Microsoft 365 admin center, go to the Home page.

2. Find the Training & guides card.

Training & guides card in the Microsoft 365 admin center **[THIS IMAGE IS OUT OF DATE]**

3. Select Advanced deployment guides and then select All guides.

Screenshot of the Setup guidance page in the Microsoft 365 admin center **[THIS IMAGE IS OUT OF DATE]**

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e0e0337-ad80-74c2-07df-1164a0641feb
* Version Independent ID: 7f19f87a-79cf-33b6-c64f-4449b1add0d9
* Content: [Setup guides for Microsoft 365 and Office 365 services - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/setup-guides-for-microsoft-365?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/setup-guides-for-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/setup-guides-for-microsoft-365.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by chasman157** [comment]
![image](https://user-images.githubusercontent.com/82958345/159922333-786a3a1e-8c99-4b53-ad4b-6b2a66ce3a92.png)
![image](https://user-images.githubusercontent.com/82958345/159922747-efaaaef2-9bf3-4bf8-95ae-e57e57a8b290.png)

NOTE: based on the NEW images and content, the content might be stale as well
[Setup Guide - Github Feeback - Images and Content are Out of Date #8106.docx](https://github.com/MicrosoftDocs/microsoft-365-docs/files/8341712/Setup.Guide.-.Github.Feeback.-.Images.and.Content.are.Out.of.Date.8106.docx)

**Comment by msbemba** [comment]
@chasman157 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8200

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chasman157 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
