### ISSUE TITLE
Increase threat protection page 

### ISSUE THREAD

**Issue by HJKUTR** [MicrosoftDocs/microsoft-365-docs#8108]
https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/increase-threat-protection?view=o365-worldwide

What an absolutely bizarre way to solicit feedback!!! Honestly, MS must be in a massive bubble of their own numbskullery.

Anyway, I'm doing you the favour of letting you know (and which all proper IT professionals should check) is your page is horrendously out of date. Quite how anyone can set up an information page where the videos do not match the text is utterly beyond me, and whilst some of the info is good, some of it is not even close to reality.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26120923-cfc5-e6f7-866b-9e5cbcf22363
* Version Independent ID: aaec5592-df91-ee04-9f73-081e69dd34cd
* Content: [Increase threat protection for Microsoft 365 for Business - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/increase-threat-protection?view=o365-worldwide#raise-the-level-of-protection-against-malware-in-mail)
* Content Source: [microsoft-365/admin/security-and-compliance/increase-threat-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/increase-threat-protection.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by yogkumgit** [comment]
@SKjerland Please help us in resolving this issue. Thanks

**Comment by SKjerland** [comment]
@yogkumgit This article is moving to a new doc library and @denisebmsft is the new owner. I went ahead and assigned the issue to her to investigate. Thanks!

**Comment by denisebmsft** [comment]
Hello @HJKUTR. Thank you so much for the feedback. We have retired the original article and it's now redirecting to the more up-to-date content. I appreciate your taking the time to post this issue.
