### ISSUE TITLE
Outbound Spam settings

### ISSUE THREAD

**Issue by GalloTheFourth** [MicrosoftDocs/microsoft-365-docs#811]
It looks like the threshold numbers for the Outbound Spam policy recommendations may be reversed. I would think that higher numbers should be less strict.

**Comment by mypil** [comment]
@GalloTheFourth - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@GalloTheFourth - We value any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue. 

Please feel free to open a new issue if there is a particular area of the docs that we can improve or make better and kindly link it to the specific MS doc. Thank you.
