### ISSUE TITLE
Microsoft 365 Groups guidance

### ISSUE THREAD

**Issue by NaMullins** [MicrosoftDocs/microsoft-365-docs#8111]
The current page says that you cannot put M365 groups in SharePoint groups - but you actually can and it is a feature that is much needed. Why is it on the page as something that isn't possible? I think this should be corrected or if there is a problem that arises from doing it - since it IS possible to do - that should be clearly outlined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@NaMullins Thank you for your feedback. I was able to test and M365 groups can be added to SharePoint groups. The document states, Microsoft 365 Groups can't be members of security groups and that is accurate. You cannot add an M365 group to a security group. However, You can give people permissions to the site by adding individual users, security groups, or Microsoft 365 groups to one of the three SharePoint groups (owners, members, or visitors). I have made this change to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8166

Once the author approves, the changes will be live.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @NaMullins Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
