### ISSUE TITLE
Defender for Endpoint Android troubleshooting steps needed

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/microsoft-365-docs#8113]
Some info or links for troubleshooting would be good.  I've deployed the app, the app config, and the device config, all showing success, but when I open Defender on my device, it tells me "Contact administrator" --> "Tunnel hasn't been set up for you yet. Contact your organization's admin to set up Tunnel on your device".  And I AM the org's admin.  It's my understanding the device policy, with the Connectivity option, should take care of this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60db9275-9265-ebca-a145-3a3eede2353a
* Version Independent ID: 9d19ab3c-eb32-4211-14d9-559998589eb3
* Content: [Deploy Microsoft Defender for Endpoint on Android with Microsoft Intune](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/android-intune?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/android-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/android-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@JakeMoe Thank you for your feedback. We have a document which talks about troubleshooting issues - https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/android-support-signin?view=o365-worldwide

However, I don't think your issue is covered. I'd recommend you to reach out to support via the need help section on the admin center for this instance.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @JakeMoe Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
