### ISSUE TITLE
communication to cdn.odc.officeapps.live.com may be unstable.

### ISSUE THREAD

**Issue by TomonoriAbe** [MicrosoftDocs/microsoft-365-docs#8115]
[Enter feedback here]
When the tenant use ExpressRoute with ER configuration listed this page, communication to cdn.odc.officeapps.live.com may be routed to ER even ER flag of cdn.odc.officeapps.live.com is No. Because the flag of *.officeapps.live.com is Yes.

ER flag of cdn.odc.officeapps.live.com is No
ER flag of cdn.uci.officeapps.live.com is No
ER flag of *.officeapps.live.com is Yes

This is inconsistent and may cause behavior to be unstable due to the order of evaluations.
MS need to eliminate inconsistencies or publish information that is not dependent on the order of evaluation.
Or, notification should be disclosed to be noted in the order of evaluations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by sthorley** [comment]
This exact issue caused problems for my org signing into OdfB. If you put:

> *.url.com ER=Yes

you can't also have:

>  subdomain.url.com ER=No

Without disclosing it. Why not just put a footnote in saying (specified URLs below maybe be excluded from ER)

**Comment by yogkumgit** [comment]
@kelleyvice-msft Gentle reminder.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.

**Comment by sthorley** [comment]
> Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 
> 
> 
> 
> We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.




This is a very unsatisfactory response. Why would we as paying MS customers have to escalate this via our TAM when you are employed at the same company and could escalate this issue with the team responsible for this service directly.

**Comment by zscalergithub** [comment]
[sample-data.pdf](https://github.com/MicrosoftDocs/microsoft-365-docs/files/10703183/sample-data.pdf)

**Comment by zscalergithub** [comment]
[sample-data.pdf](https://github.com/MicrosoftDocs/microsoft-365-docs/files/10703960/sample-data.pdf)
