### ISSUE TITLE
Page is missing the Import-Module AzureAD command.

### ISSUE THREAD

**Issue by 1024-Kibibytes** [MicrosoftDocs/microsoft-365-docs#8116]
The command Import-Module AzureAD must come after Install-Module AzureAD. I found the correct command via https://stackoverflow.com/questions/56543597/the-term-connect-azuread-is-not-recognized-as-the-name-of-a-cmdlet/63687332#63687332

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55574af9-0105-dcd1-7eb0-77513df4e54f
* Version Independent ID: 5fe2849b-d39a-4d75-a5ce-e8f577c9a161
* Content: [Connect to Microsoft 365 with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/connect-to-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/connect-to-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @1024-Kibibytes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
