### ISSUE TITLE
Compatibility Checker does not work with Exchange Online V2 PowerShell

### ISSUE THREAD

**Issue by forester123** [MicrosoftDocs/microsoft-365-docs#8117]
Using Global admin account to run compatibility checker, get below error when connect to Exchange Online, even though I'm using Global Admin account.

**_[outlook.office365.com] Connecting to remote server failed with the following error message: Access is
denied. For more information, see the about_Remote_Troubleshooting Help topic._**
![image](https://user-images.githubusercontent.com/13616574/160098404-f8d8ec4d-699f-476c-9df0-4c707721b61b.png)

WinRM set Basic to true, no difference.
Security defaults is not enabled, MFA not enabled either.

Checked the scripts O365CompatibilityChecker.psm1, below code is used for connecting to Exchange Online.
```
    $Session = New-PSSession -ConfigurationName Microsoft.Exchange `
        -ConnectionUri $exoPowershellUri `
        -Authentication Basic -Credential $Credential -AllowRedirection 3> $null
```

I did test this New-PSSession commands, it does not work either, get the same error.

With Exchange Online V2 PowerShell, I believe we shall use **Connect-ExchangeOnline**.

I modified O365CompatibilityChecker.psm1 to change above code to below, then run Invoke-CompatibilityCheck again, this time it works.
```
     Connect-ExchangeOnline -UserPrincipalName 
     $session = Get-PSSession
```

Please review and double check the O365CompatibilityChecker.psm1 script, if I can easily reproduce the issue, I believe customer will meet the issue as well if they use Exchange Online V2 PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#centralized-deployment-compatibility-checker)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@forester123 Thank you for your feedback. I'm currently checking with the author and will update you shortly.

Thanks
Sri

**Comment by forester123** [comment]
@msbemba  thanks.

I made some further test with the compatibility checker script, even if I can fix the access denied error. The report I get is not expected. 
![image](https://user-images.githubusercontent.com/13616574/161176065-6621f2d9-534c-4bb2-abe1-0f02c7a9a472.png)

I believe the problem is with below three functions used in the script:
**Get-OrgUsers
Get-ProductActivations
Get-MailActivity**

UPN returned from **Get-OrgUsers** is normal UPN
![image](https://user-images.githubusercontent.com/13616574/161176178-4295f11d-404c-4bf3-a8b2-ec1c155ff962.png)

But **Get-ProductActivations** and **Get-MailActivity** returns 
![image](https://user-images.githubusercontent.com/13616574/161176246-ad711042-b812-4919-9839-233ee3d6e862.png)
![image](https://user-images.githubusercontent.com/13616574/161176282-dc048515-72e1-45eb-a012-91c20a5864f1.png)

This caused the code never went into below “If”
![image](https://user-images.githubusercontent.com/13616574/161176338-02e8753a-3ccb-4860-8e33-0740a4f5186c.png)

I think the whole script might need to be revised.

**Comment by forester123** [comment]
I think this might be the cause that the UPNs returned as id, need additional settings to get the expected result. 
https://docs.microsoft.com/en-US/office365/troubleshoot/miscellaneous/reports-show-anonymous-user-name

If that's case, then please add this information in the article to avoid misunderstanding. Thanks.

**Comment by yogkumgit** [comment]
@kwekuako confirmed in email that @efrene is looking into it.

**Comment by forester123** [comment]
Hi Team, I want to update that I have found the root cause. The reason I get access denied is because Basic Auth is disabled for all protocols due to below update from Microsoft side.
https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-june-2021-update/ba-p/2454827 

I have to re-enable basic auth for Exchange Online remote PowerShell in Admin center first before running **invoke-compatibilitycheck** command
![image](https://user-images.githubusercontent.com/13616574/161482518-b820a145-1029-4370-8f46-9a35e1eb13f8.png)

Besides, the root cause why the report is due to the privacy mentioned in below KB.
https://docs.microsoft.com/en-US/office365/troubleshoot/miscellaneous/reports-show-anonymous-user-name

> Starting September 1, 2021, we're hiding user information by default for all reports as part of our ongoing commitment to help companies support their local privacy laws. 

To resolve this,  

1. Go to the [Microsoft 365 admin center](https://admin.microsoft.com/).
2. Go to Settings > Org Settings > Services.
3. Select Reports.
4. Clear Display concealed user, group, and site names in all reports, and then select Save.

Overall, I think the script has no problem, but I think it's worth to update the document a bit to mention above tips for end users in case they meet any problems.

Thanks all.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@forester123 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8467

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @forester123 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by forester123** [comment]
@msbemba @yogkumgit  thanks lot for the update. Appreciate :)
