### ISSUE TITLE
$dehy should be $dehydrated

### ISSUE THREAD

**Issue by ChrisWarrenCodux** [MicrosoftDocs/microsoft-365-docs#8118]
[Enter feedback here]
The **Create a new migration endpoint for cross-tenant mailbox moves** script should be

$dehydrated=Get-OrganizationConfig | fl isdehydrated
if ($**dehydrated** -eq $true) {Enable-OrganizationCustomization}

not

$dehydrated=Get-OrganizationConfig | fl isdehydrated
if ($**dehy** -eq $true) {Enable-OrganizationCustomization}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by RAJU2529** [comment]
@yogkumgit , created PR #8119.

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @ChrisWarrenCodux Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
