### ISSUE TITLE
I don't see the upgrade tap

### ISSUE THREAD

**Issue by edmiidz** [MicrosoftDocs/microsoft-365-docs#8123]
I am clicking around Billing and my products and I don't see the upgrade tab mentioned in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3519dc1-b7fa-cb9f-d9d7-cc5831ddbd67
* Version Independent ID: 18096313-720b-9f75-f9e0-6509b7dc8578
* Content: [Upgrade to a different business plan](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/upgrade-to-different-plan?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/upgrade-to-different-plan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/upgrade-to-different-plan.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@edmiidz Thank you for your feedback. We have made changes to the document  via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8168

Once you select the subscription, you will see the below options to choose from

![image](https://user-images.githubusercontent.com/45987684/161019825-9a7c1559-8fac-4db8-819d-4c54766ceab7.png)


Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @edmiidz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
