### ISSUE TITLE
Clarify the "Use Azure AD Conditional Access" detail

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#8132]
You mention the following:

> Once you turn on idle session timeout, it applies to your entire organization and can't be scoped to specific users, organizational units, or groups. Use Azure AD Conditional Access for policies for different users and groups.

However, can you please clarify which part of CA you mean. Do you mean **use app enforced restrictions**?
**a) If yes**, maybe we should mention this is limited to SharePoint/Exchange Online and not office.com/admin centers.
**b) if no**, clarify which CA policy setting you refer to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Version Independent ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Content: [Idle session timeout for Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/idle-session-timeout-web-apps?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/idle-session-timeout-web-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@JonesMikael Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8196

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JonesMikael Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by glenn1925** [comment]
How can we exclude users /devices? Seems like CA is not working for managed devices.
