### ISSUE TITLE
MSERT

### ISSUE THREAD

**Issue by Ridha1962** [MicrosoftDocs/microsoft-365-docs#8133]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 286c4f73-ff88-3fdc-8673-47c11edd763b
* Version Independent ID: 286c4f73-ff88-3fdc-8673-47c11edd763b
* Content: [Microsoft Safety Scanner Download](https://docs.microsoft.com/fr-fr/microsoft-365/security/intelligence/safety-scanner-download?view=o365-worldwide)
* Content Source: [microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/intelligence/safety-scanner-download.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Ridha1962  Whats the problem are you facing
