### ISSUE TITLE
Missing a word in the description

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftDocs/microsoft-365-docs#8135]
Under the section "Block bookings from outside your organization"

Missing a word in the description "organization who've signed and are authenticated can" should read "organization who've signed **in** and are authenticated can"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba164b8e-a574-0744-ce02-23bda994e505
* Version Independent ID: 05018469-d6f8-0eb5-956c-730991912f8b
* Content: [Turn Microsoft Bookings on or off](https://docs.microsoft.com/en-US/microsoft-365/bookings/turn-bookings-on-or-off?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/turn-bookings-on-or-off.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/turn-bookings-on-or-off.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jeff-bb Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
