### ISSUE TITLE
Usage of "WebRtcRespectOsRoutingTableEnabled"

### ISSUE THREAD

**Issue by WolfgangAndreas** [MicrosoftDocs/microsoft-365-docs#8138]
Hi,

this is regarding the 2nd Note Box regarding Edge v96:
If I understand the description of the "WebRtcRespectOsRoutingTableEnabled"-Setting (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#webrtcrespectosroutingtableenabled) correctly, then the setting would need to be set to "Disabled" instead of "Enabled" for the split tunnel scenario to apply. This is not the case here. Or am i wrong?

Description:
"If you disable this policy or don't configure it, WebRTC will not consider the routing table and may make peer to peer connections over any available network.
If you enable this policy, WebRTC will prefer to make peer to peer connections using the indicated network interface for the remote address as indicated in the routing table."

Thank you for your feedback :-)

Regards,
Wolfgang

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a633cab1-3c4c-0998-60d8-586cdf534380
* Version Independent ID: a633cab1-3c4c-0998-60d8-586cdf534380
* Content: [Securing Teams media traffic for VPN split tunneling - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-vpn-securing-teams?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-vpn-securing-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-vpn-securing-teams.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@WolfgangAndreas Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8173

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @WolfgangAndreas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
