### ISSUE TITLE
Clarify device entititlement

### ISSUE THREAD

**Issue by homotechsual** [MicrosoftDocs/microsoft-365-docs#8141]
Clarify 5 device limit / entitlement for MDB as mentioned here https://support.microsoft.com/en-gb/topic/installing-microsoft-defender-public-preview-ba7d17d7-464b-444d-bb47-990b7278369d

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11fc1978-8aab-0f92-18bf-08b4114e19c2
* Version Independent ID: 11fc1978-8aab-0f92-18bf-08b4114e19c2
* Content: [Overview of Microsoft Defender for Business](https://docs.microsoft.com/en-GB/microsoft-365/security/defender-business/mdb-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-overview.md)
* Product: **m365-security**
* Technology: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by homotechsual** [comment]
Can you confirm what device limits apply to Defender for Business then as this isn't confirmed in the documentation currently.

**Comment by msbemba** [comment]
@homotechsual Thank you for your feedback. There is no limit as such and this is licensed on a user basis. As mentioned in the document -https://docs.microsoft.com/en-gb/microsoft-365/security/defender-business/mdb-requirements?view=o365-worldwide 

Microsoft 365 Business Premium
--- or ---
Microsoft Defender for Business (standalone; currently in preview) is required so you can onboard devices and monitor them.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @homotechsual Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
