### ISSUE TITLE
No links and no info

### ISSUE THREAD

**Issue by jurion** [MicrosoftDocs/microsoft-365-docs#8145]
Documenation doesn't help at all. 

There is no links. "Office 365 defender" : Link ? Where and how can I find it ? 

We have a user blocked with high alert. I'm trying to trace it. This documenation is a waste of time : No direct links provided, no descriptions. And no explanation at all. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c17e50d-aa8f-bd30-66af-ef4d63f02402
* Version Independent ID: 92cbda3f-c3a9-ed20-2038-7e966f491934
* Content: [Remove blocked users from the Restricted users portal - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jurion, more information, please.

In that topic, The [What do you need to know before you begin?](https://docs.microsoft.com/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam#what-do-you-need-to-know-before-you-begin) section contains a link to the Microsoft 365 Defender portal, the click path to the Restricted users page, and a direct link to the Restricted users page.

The [Use the Microsoft 365 Defender portal to remove a user from the Restricted users list](https://docs.microsoft.com/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam#use-the-microsoft-365-defender-portal-to-remove-a-user-from-the-restricted-users-list) section contains a link to the Microsoft 365 Defender portal, the click path to the Restricted users page, and a direct link to the Restricted users page.

The [Verify the alert settings for restricted users](https://docs.microsoft.com/microsoft-365/security/office-365-security/removing-user-from-restricted-users-portal-after-spam#verify-the-alert-settings-for-restricted-users) did not have a link to the Microsoft 365 Defender portal, nor did it have a direct link to the Alert policy page, but I added it.

So what exactly is lacking links and descriptions?

**Comment by chrisda** [comment]
Closing due to lack of response.

Thanks for the feedback.
