### ISSUE TITLE
MECM cannot set "Block Adobe Reader from creating child processes" yet.

### ISSUE THREAD

**Issue by m-kikushima** [MicrosoftDocs/microsoft-365-docs#8147]
I checked new MECM and there is no "Block Adobe Reader from creating child processes" setting.
But, part of following doc says Y.
could you revise it?
[Enter feedback here]
Right:
Configuration Manager name: Not yet available
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#block-adobe-reader-from-creating-child-processes

Wrong:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#supported-configuration-management-systems
Block Adobe Reader from creating child processes
Microsoft Endpoint Configuration Manager Y
![image](https://user-images.githubusercontent.com/33505591/160754841-0540eeb0-1398-45db-9916-86fe6f178275.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Version Independent ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Content: [Attack surface reduction rules reference](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#supported-configuration-management-systems)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by RAJU2529** [comment]
@jweston-1 . Configuration name should given or. Y should be removed from the table.

**Comment by msbemba** [comment]
@m-kikushima Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8197

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by jweston-1** [comment]
Approved

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @m-kikushima Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
