### ISSUE TITLE
Should Mention that the import rarely works

### ISSUE THREAD

**Issue by Weychris** [MicrosoftDocs/microsoft-365-docs#815]
I know someone is going to tell me to open a ticket with O365 support, and I've already done so. It really seems like the import from the Azure blob to an Office 365 mailbox doesn't work at all. The upload works flawlessly, but the import performance from the blob to the mailbox stalls repeatedly, and support's only solution is to restart the import, which also stalls. You should also mention that you can't download the files from the blob locally using these instructions, so you can't even download the .PST files back to local storage and upload manually. This should frankly be disabled as an option until Microsoft can guarantee that it actually works. A complete waste of time for all involved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by Weychris** [comment]
Update - I just received this from an O365 support engineer:
Thanks for the feedback.
Glad to know the status has improved.

Regarding to your question, In our testing we have found that if there are more than 1 million items in a folder in a PST, the import fails. Because it is hard to determine number of items, an approximate assumption is PST files that are of size 10 GB. If you have files that are larger than 10 GB, please break them up into smaller files. We are actively working on supporting larger per folder limits.
Although the import process is slow, we are confident that it will work as the Exchange EWS Throttling Policy has now been increased.

**Comment by Weychris** [comment]
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_upgrade-mso_o365b/o365-import-service-for-pst-files-is-there-a/6c45a1f0-96af-4d62-a0d8-c6165d8d2b26

**Comment by markjjo** [comment]
@Weychris Thanks for the heads up. Sounds like MS support was able to help you. We'll look into adding some related info, such as the 1 million item folder limit, which is an EXO limit. I also got some feedback from support that the smaller a PST file is the less likely it is to get throttled by the Import service.
