### ISSUE TITLE
New Microsoft Root CAs - All 3 should be trusted or just DigiCert Global Root G2?

### ISSUE THREAD

**Issue by GauravES** [MicrosoftDocs/microsoft-365-docs#8150]
[Enter feedback here]

Although the article mentions that Microsoft may use one of 3 Root CAs listed below, the rest of the article only mentions that DigiCert Global Root G2 is widely used but does not mention the other 2.   Will the other 2 need to be manually added or will they be part of Windows Update (They dont currently seem to be as the 2 Microsoft ones do not appear in Windows 10 OSes after recent Windows Update.   Will they need to be manually installed?

Do we only need to ensure DigiCert Global Root G2 is trusted, or will we need to trust the other 2 as well?

<html><body>

DigiCert Global Root G2 | df3c24f9bfd666761b268073fe06d1cc8d4f82a4
-- | --
Microsoft RSA Root Certificate Authority 2017 | 73a5e64a3bff8316ff0edccc618a906e4eae4d74
Microsoft ECC Root Certificate Authority 2017 | 999a64c37ff47d9fab95f14769891460eec4c3c5

</body>
</html>[DigiCert Global Root G2](https://cacerts.digicert.com/DigiCertGlobalRootG2.crt) 	df3c24f9bfd666761b268073fe06d1cc8d4f82a4
[Microsoft RSA Root Certificate Authority 2017](https://www.microsoft.com/pkiops/certs/Microsoft%20RSA%20Root%20Certificate%20Authority%202017.crt) 	73a5e64a3bff8316ff0edccc618a906e4eae4d74
[Microsoft ECC Root Certificate Authority 2017](https://www.microsoft.com/pkiops/certs/Microsoft%20ECC%20Root%20Certificate%20Authority%202017.crt) 	999a64c37ff47d9fab95f14769891460eec4c3c5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c23df2b9-0e0e-1a54-2f42-effb9387459a
* Version Independent ID: c23df2b9-0e0e-1a54-2f42-effb9387459a
* Content: [Office TLS Certificate Changes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-office-365-tls-certificates-changes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-office-365-tls-certificates-changes.md)
* Service: **o365-seccomp**
* GitHub Login: @pshelton-skype
* Microsoft Alias: **pshelton**

**Comment by RAJU2529** [comment]
@GauravES . detailed investigation is needed in this regard.

**Comment by pshelton-skype** [comment]
Hi, @GauravES. The new Intermediate CAs are "cross-signed" and should be considered valid if any of the three Root CA certificates are trusted. We would recommend installing all three Root CAs for completeness, but expect the "DigiCert Global Root G2" Root CA to be pre-installed in a number of OSes and device types, thus creating a trusted chain without additional work.

**Comment by GauravES** [comment]
Thank you for the clarification; it would be best if Microsoft could make the other two certs part of a future Windows Update.  (DigiCert Global Root G2 can already be found on all machines and servers we have checked).
