### ISSUE TITLE
Alert configuration experience for DLP alerts - aggregated alerts

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/microsoft-365-docs#8151]
Could a bit more detail be provided around the alert configuration experience with Aggregated alerts and perhaps a couple of examples. I am referring to this section:

https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-configure-view-alerts-policies?view=o365-worldwide#alert-configuration-experience

For example:

If I expected 5 DLP alerts to be triggered within an hour, generated by 5 different users.
(e.g. 5 different users sent 5 emails externally with SIT data in that we monitor for)

If we decided to go for aggregated alerting and had this threshold to 10 activities in 60 minutes.
1) Does this mean that these alerts would not be picked up in the m365 dashboard, as it hasnt met the threshold of 10? so they are lost?
2) Or does it mean that instead of sending 5 emails out it will group into 1 and send on the 60 minutes? however in this case no email will be sent as the threshold of 10 was not met, but they will still be logged in in the iM365 alert interface

You  also start to use phrases "matched activities" but normally we talk about DLP rules. So what is a matched activity if a customer attached 2 spreadsheets with SITs in, is that 2 matched activities?.

Also whilst E5 is required for setting up aggregated alerts, is that just for the admin, the users can still be E3?

So my confusion is around alerts in the admin interface, versus email alerts and what happens if you dont meet thresholds, will you basically miss dlp incidents? Just some more clarity would really help please

regards
Bradley

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e9f547-6180-2981-6e7a-895fc17b7703
* Version Independent ID: 58334631-7058-1809-0804-c107457b4470
* Content: [Configure and view alerts for data loss prevention policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-configure-view-alerts-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-configure-view-alerts-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-configure-view-alerts-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by obhayes** [comment]
II just wondered when we can expect an update on this one please, as been approx 6 weeks, thanks

**Comment by obhayes** [comment]
any update please?
