### ISSUE TITLE
Puppet mdatp install snippet does not work for Ubuntu 20.04 when using the prod channel

### ISSUE THREAD

**Issue by akomakom** [MicrosoftDocs/microsoft-365-docs#8152]
Current snippet does not generate a working `apt` source list:

```puppet
# Puppet manifest to install Microsoft Defender for Endpoint on Linux.
# @param channel The release channel based on your environment, insider-fast or prod.
# @param distro The Linux distribution in lowercase. In case of RedHat, Oracle Linux, Amazon Linux 2, and CentOS 8, the distro variable should be 'rhel'.
# @param version The Linux distribution release number, e.g. 7.4.

class install_mdatp (
$channel = 'insiders-fast',
$distro = undef,
$version = undef
){
    case $::osfamily {
        'Debian' : {
            apt::source { 'microsoftpackages' :
                location => "https://packages.microsoft.com/config/${distro}/${version}/prod",
                release  => $channel,
                repos    => 'main',
                key      => {
                    'id'     => 'BC528686B50D79E339D3721CEB3E94ADBE1229CF',
                    'server' => 'keyserver.ubuntu.com',
                },
            }
        }
        
....
```
When using channel `prod`, this will generate a sources.list.d file as follows:
```
deb https://packages.microsoft.com/ubuntu/20.04/prod prod main
```

This will result in the following error:
```
Ign:8 https://packages.microsoft.com/ubuntu/20.04/prod prod InRelease
Err:9 https://packages.microsoft.com/ubuntu/20.04/prod prod Release   
  404  Not Found [IP: 104.42.185.173 443]                 
```

## Workaround

* Change 
`release  => $channel,` 
to
`release  => $facts['os']['distro']['codename'],`

This will result in the following working sources list:
`deb https://packages.microsoft.com/ubuntu/20.04/prod focal main`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a5df48-1f27-18fe-f668-22fa03b9a680
* Version Independent ID: a0291804-533d-803e-c41b-0b0bc7f9a308
* Content: [Deploy Microsoft Defender for Endpoint on Linux with Puppet](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-with-puppet?view=o365-worldwide#create-a-puppet-manifest)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-with-puppet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-with-puppet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@akomakom Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8198

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@Dansimp Pleas hep us in resolving this issue. Email sent. Thanks

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @akomakom Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
