### ISSUE TITLE
need more info?

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/microsoft-365-docs#8154]
[Enter feedback here]
Possibly add under "Recommended content", "Removing eDiscovery holds"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7263ba97-4e79-7144-a9d4-5138fe228fa2
* Version Independent ID: 316e242e-7f37-592e-9c8f-e754b23a29ca
* Content: [Create eDiscovery holds in a Core eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-ediscovery-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-ediscovery-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@fixx-er Thank you for your feedback. The recommended content seems to be getting picked up automatically. I'll work with the author and check how we can update this.

Thanks
Sri

**Comment by yogkumgit** [comment]
@markjjo Sent you an email with our query. Kindly reply. Thanks

**Comment by tiburd** [comment]
@fixx-er 
Hi,
Thanks for your feedback. 
The article contains a section about removing eDiscovery holds, so we're closing this issue.
