### ISSUE TITLE
Live response - macOS / Linux

### ISSUE THREAD

**Issue by ediemerson-br** [MicrosoftDocs/microsoft-365-docs#8155]
Live response feature is supported on macOS and Linux.

https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/announcing-live-response-for-macos-and-linux/ba-p/2864397

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e914c02a-e905-fc32-439c-feb1fafa09b8
* Version Independent ID: 1a6a15e9-717a-33c1-b90e-96925c680228
* Content: [Microsoft Defender for Endpoint for non-Windows platforms](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/non-windows?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/non-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/non-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@ediemerson-br Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8175

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ediemerson-br Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
