### ISSUE TITLE
Buy Domain link does not appear on the Settings/Domains page.

### ISSUE THREAD

**Issue by melissabrownblaeuer** [MicrosoftDocs/microsoft-365-docs#8156]
The buy domain option does not appear on the page mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb572a6e-0bd1-9609-4cbe-021deb497da7
* Version Independent ID: 7f82b19b-d569-c955-2e2d-20ec3112b3ad
* Content: [Buy a domain name - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/buy-a-domain-name?WT.mc_id=365AdminCSH_AdminPortalGlobalSearch%3FWT.mc_id%3D365AdminCSH_globalsearch&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/buy-a-domain-name.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/buy-a-domain-name.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@melissabrownblaeuer Thank you for your feedback. I was able to test and find the option to Buy domain under settings-->domains

![image](https://user-images.githubusercontent.com/45987684/161099916-80c88c57-a88b-4c18-b742-36de0bbbf6ac.png)


If you are still facing issues to locate the Buy domain option, Please contact Microsoft support via the need help section on the admin center.

Thanks
Sri

**Comment by msbemba** [comment]
Thank you for the update @melissabrownblaeuer . Looks like there might have been a bug at that point in time. In case you have an issue again in the future, feel free to contact support via the need help section on the admin center.

Thanks
Sri
