### ISSUE TITLE
Permissions required in the home tenant?

### ISSUE THREAD

**Issue by taikuli** [MicrosoftDocs/microsoft-365-docs#8157]
My account has Global Admin permissions (via B2B guest account) in selected customer tenants but not in my home tenant.
In my home tenant my account doesn't have any admin role at all (not necessary).
Now when I open the M365 admin center I don't see the tenant switcher as I only see the error message regarding the missing admin role.

What minimum permissions are required in the home tenant to see the tenant switcher?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b378de4-ca71-a16b-6669-369e3e3ff9d4
* Version Independent ID: 1a1a6ec6-8c04-2172-7afa-49d268191687
* Content: [Manage multiple tenants - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/multi-tenant/manage?view=o365-worldwide)
* Content Source: [microsoft-365/admin/multi-tenant/manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/multi-tenant/manage.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@taikuli Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8199

This is only available for Microsoft 365 partner admins (delegated admin access) for now.

Once the author approves, the changes will be live.


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @taikuli Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
