### ISSUE TITLE
Request for Cisco Meraki SM Support

### ISSUE THREAD

**Issue by bwireless** [MicrosoftDocs/microsoft-365-docs#8158]
Can you provide support and deployment instructions for Cisco Meraki System Manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd66a255-36e5-29dc-7610-d50ef8bca3f3
* Version Independent ID: 17375473-bc07-f8e5-a85f-d732bbba3d71
* Content: [Intune-based deployment for Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-with-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-with-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@bwireless Thank you for your feedback. This channel is used for documentation updates. If you are looking for Microsoft support on a third-party product, you will need to use the M365 admin center-->Need help. The support engineer assigned will be able to assist you.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bwireless Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
