### ISSUE TITLE
Missing command

### ISSUE THREAD

**Issue by siegardj** [MicrosoftDocs/microsoft-365-docs#816]
Either I'm blind or there's a step missing at the end of step 5 or beginning of step 6 you should have a line to get the $groups variable.

get-unifiedgroup | where {$_.classification -eq "General"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by siegardj** [comment]
That's step 5 and 6 of the Relabel Office 365 groups with new sensitivity labels section

**Comment by get-itips** [comment]
Hello @siegardj thanks for noticing and reporting.
I created a pull request to propose a correction to the article.
Thank you

**Comment by cabailey** [comment]
@siegardj  Thanks for flagging this.  The extra line has been added & you should see it live within the next 24 hours.
