### ISSUE TITLE
Update behavior when label is being recommended

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/microsoft-365-docs#8161]
[Hello, I was just reading this part "This method supports recommending a label to users, as well as automatically applying a label. But in both cases, the user decides whether to accept or reject the label, to help ensure the correct labeling of content."

If I'm not mistaken I believe you can only reject the auto-label when it's being _recommended_ with the policy tip. You would have to remove the sensitive content that triggered the label to proceed when using auto-labeling and not a recommendation.

Thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564bdaa-d66b-42ba-85bd-7c8f9989093d
* Version Independent ID: 33be52f1-d233-9c5d-abb3-140a9c6a0d74
* Content: [Automatically apply a sensitivity label to content in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-sensitivity-label-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-sensitivity-label-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-sensitivity-label-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by ChristianJBergstrom** [comment]
Hey, thanks for the reply @cabailey Too much going on. Had a closer look and I had only one published label for the user with the requirement to apply a label. The downside of testing multiple scenarios in multiple tenants. It gets messy :)

**Comment by cabailey** [comment]
@ChristianJBergstrom A lot to juggle!  Yes, a single label with mandatory label configured ... I can now see why you came to your conclusion!  Not a typical deployment :)  I'll close this issue.  Kudos for your extensive testing.
