### ISSUE TITLE
Unable to access linked documents

### ISSUE THREAD

**Issue by Nisden** [MicrosoftDocs/microsoft-365-docs#8169]
There are multiple links on this page that links to an Sharepoint that I can't access.

An example is: https://microsoft-my.sharepoint.com/personal/siosulli_microsoft_com/Documents/Security%20Posture/TVM/minimum-requirements.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d401bb34-5a2e-7f66-8fcd-28a395c62a99
* Version Independent ID: 1022827b-273c-7351-ee5d-189e6caa5fee
* Content: [Device inventory](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machines-view-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machines-view-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machines-view-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Nisden Thank you for your feedback. We have fixed the links via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8187

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Nisden Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
