### ISSUE TITLE
Unclear on permissions required / outcome is.

### ISSUE THREAD

**Issue by StarkCaptain** [MicrosoftDocs/microsoft-365-docs#817]
It is unclear from this page what the outcome when adding individuals to the case. What specifically will the user have access to when they are added to case? As an example say I add a user to the case that in the Review role, will they have full access to the Review sets ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 492b920b-f938-146c-1435-7bc7ba5c74f1
* Version Independent ID: b5f70139-4b8d-5079-5370-ad861dcc42ec
* Content: [Add or remove members from a case](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery#feedback)
* Content Source: [microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-or-remove-members-from-a-case-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@StarkCaptain Apologies for the delayed reply. Currently, to add a user as a member of a case in Advanced eDiscovery, that user has to be a member of the eDiscovery Manager role group on the Permissions page of the security and compliance center. That role group is assigned the necessary roles (permissions) that let case members manage the case. See https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions for more information.

Currently, members of the Reviewer role group can only access [Advanced eDiscovery v1 cases](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery-cases#step-1-assign-ediscovery-permissions-to-potential-case-members). They can't perform any tasks if they are added as a member of Advanced eDiscovery v2 cases. We're working on this issue.
