### ISSUE TITLE
Cvv_z86

### ISSUE THREAD

**Issue by algrn1406** [MicrosoftDocs/microsoft-365-docs#8177]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e2ac78-e08b-d7c8-5eec-baf9e9c13b62
* Version Independent ID: 66014f69-00c9-0e9b-fe0a-d0e10f2ca5eb
* Content: [About registration numbers and under review notifications](https://docs.microsoft.com/en-us/microsoft-365/commerce/about-registration-numbers?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/about-registration-numbers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/about-registration-numbers.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by denisebmsft** [comment]
Hello @algrn1406! Do you have a question or comment about one of our articles? Your feedback doesn't appear to have come through properly.

**Comment by yogkumgit** [comment]
@algrn1406 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
