### ISSUE TITLE
Allow list Entries don't have never expire option anymore

### ISSUE THREAD

**Issue by Parth459** [MicrosoftDocs/microsoft-365-docs#8182]
Allow list Entries don't have never expire option anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@RatulaC Please respond. Thanks

**Comment by yogkumgit** [comment]
@RatulaC Gentle reminder. Thanks

**Comment by chrisda** [comment]
@Parth459, massive updates to the Tenant Allow/Block List content have fixed this.

Thanks for the feedback.

Closing
