### ISSUE TITLE
Elaborate on "Settings"

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/microsoft-365-docs#8184]
Any chance of more detail in this Section?  https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection?view=o365-worldwide#what-happens-if-i-try-to-change-microsoft-defender-for-endpoint-settings-in-intune-microsoft-endpoint-configuration-manager-and-windows-management-instrumentation-when-tamper-protection-is-enabled-on-a-device

It just says "Settings", can you provide more detail on what you can and can't change when Tamper Protection is on?  The way this reads is you can't change any AV / Defender settings when its's on?  Like I can't add a file path or file Exclusion in my DefenderAV GPO or Intune Policy?  I can't add a Add-MPPreference via Powershell on a device? (i.e Add-MpPreference -ExclusionExtension ".mdf") 

It would be good to make it clearer....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31e7b39-b7c3-188a-0b2a-02ff10a5be6d
* Version Independent ID: 44940a13-0a2d-e281-560b-cb4d8a5d1ccf
* Content: [Protect security settings with tamper protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection?view=o365-worldwide#what-happens-if-i-try-to-change-microsoft-defender-for-endpoint-settings-in-intune-microsoft-endpoint-configuration-manager-and-windows-management-instrumentation-when-tamper-protection-is-enabled-on-a-device)
* Content Source: [microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/prevent-changes-to-security-settings-with-tamper-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Hello @mattsmacblog. Thank you so much for posting your question here. I can see how that section was confusing, and I have updated the article accordingly. If you're using Intune to manage tamper protection, you can make changes, such as applying tamper protection to some or all devices, or defining exclusions using Intune. What you can't do is switch back and forth between managing tamper protection with Intune and some other method like Group Policy or editing settings on the local device. I have updated the article and the changes will be live later today. I hope it's more clear. Please let me know if you have any other questions. Thanks again!
