### ISSUE TITLE
Using DisableAntispyware part was removed from the page

### ISSUE THREAD

**Issue by SauliusMy** [MicrosoftDocs/microsoft-365-docs#8185]
Hello, i've noticed that the part on how to disable Defender on servers by using GPO or creating DisableAntispyware regkey was removed from this page. Why? Is this method not supported anymore? We use a third party AV, we do not want to uninstall defender feature from servers  but we want service to be Stopped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61024433-366d-5ea3-4a3f-0cdd5cdcd900
* Version Independent ID: 348d3fc9-0937-b3a6-897e-09d1236d7019
* Content: [Microsoft Defender Antivirus compatibility with other security products](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@SauliusMy Thank you for your feedback. We received a recent update from the Product team to recommend "uninstall Microsoft Defender Antivirus to prevent conflict". In your case, if you would like to get more details on what the disadvantages are with the previous method, I'd recommend you to contact Microsoft support via need help to get more clarity around this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @SauliusMy Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
