### ISSUE TITLE
Wrong Options for AuditAllowed?

### ISSUE THREAD

**Issue by ThijsLecomte** [MicrosoftDocs/microsoft-365-docs#8188]
[Enter feedback here]
In the table explaining all the of the options, there is "when Type AuditAllowed is selected:".

This has option 2 and 3 with the same explanation.
Should option 3 exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7a5c17-1358-990b-968d-432a3aab2e17
* Version Independent ID: 1b4d4eff-3e22-47d7-4054-6cc9ed0217d0
* Content: [Microsoft Defender for Endpoint Device Control Removable Storage Access Control, removable storage media](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ThijsLecomte Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8281

Once the PR is approved, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ThijsLecomte Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
