### ISSUE TITLE
Apps not supporting Sensitivity Labels

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/microsoft-365-docs#819]
This page mentions that some of the apps and services cannot use Sensitivity labels, what does it mean in practice? Lets consider that i have enabled this preview and replaced classification value in existing groups with sensitivity labels. 
- Will planner,  yammer etc. (apps not in scope) show the sensitivity label applied to the connected existing group?
- Does it mean that I cannot classify yammer, planner group while creating it from these services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@prashant1380 - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by prashant1380** [comment]
How this can be closed? The issue is about documentation which does not explain in detail the impact of using new Sensitivity labels and I have asked about that impact. Could you please clarify my doubts?

**Comment by GiantCrocodile** [comment]
Hi @mypil! Can you reopen this issue as it's an open question about missing information in the docs? The user asked for clarification, not implementing this feature in apps which are not supporting this yet.

**Comment by prashant1380** [comment]
Can you please reopen this issue? This is really important to know how this change will impact other unsupported services? I have already one case open related to this, but as per the support engineer this is in preview and they cannot support fully
