### ISSUE TITLE
Health column 

### ISSUE THREAD

**Issue by azmat111** [MicrosoftDocs/microsoft-365-docs#8190]
[This page needs to updated with Health column ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d401bb34-5a2e-7f66-8fcd-28a395c62a99
* Version Independent ID: 1022827b-273c-7351-ee5d-189e6caa5fee
* Content: [Device inventory](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machines-view-overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machines-view-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machines-view-overview.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@azmat111 Thank you for your feedback. Are you referring to the Sensor Health state?If yes, it has been added. I do not see a health column in the Device inventory.

![image](https://user-images.githubusercontent.com/45987684/165793256-8c07ca9f-c2ab-48ce-955a-5d22a80a0738.png)

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @azmat111 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
