### ISSUE TITLE
"Enable" no longer appears in details pane.

### ISSUE THREAD

**Issue by QuickBASIC** [MicrosoftDocs/microsoft-365-docs#8191]
"In the details pane for the selected user, click Enable."

'Enable' no longer shows in details pane (screenshot is out of date). Must use checkbox and click "Enable Archive" at the top of the list.

![image](https://user-images.githubusercontent.com/7226914/161313468-16bd3ab8-2679-440d-b732-24a652025b4f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes for Microsoft 365 Compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@QuickBASIC Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8249

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @QuickBASIC Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
