### ISSUE TITLE
Regarding Incorrect Information on "Use Group Policy to schedule protection updates" column on This Page

### ISSUE THREAD

**Issue by tfunatani** [MicrosoftDocs/microsoft-365-docs#8194]
[Enter feedback here]
**- My change idea**

> Before
```
Important
By default, Microsoft Defender Antivirus will check for an update 15 minutes before the time of any scheduled scans. Enabling these settings will override that default.
```

> After
```
Important
By default, Microsoft Defender Antivirus will not schedule protection updates. Enabling these settings will override that default.
```

**- Summary**
I checked the default behaviors of schedule protection updates on Microsoft Defender Antivirus (MDAV) and confirmed that the default settings of schedule protection updates is following.
![image](https://user-images.githubusercontent.com/89067036/161456845-d09ac598-184d-4375-bd38-9faa502856e5.png)

If "SignatureScheduleDay" is set as "8", MDAV will not schedule protection updates.
So, I believe that "Use Group Policy to schedule protection updates" column on This Page should be changed as "My change idea" above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e26a44-834c-bcd3-5fec-b9aa9bb8cde1
* Version Independent ID: 1d3e40d3-8d86-147d-f509-2f59adbceee0
* Content: [Schedule Microsoft Defender Antivirus protection updates](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@tfunatani  and @yogkumgit , i believe the below line should be added 
**If "SignatureScheduleDay" is set as "8", MDAV will not schedule protection updates.**

@yogkumgit what is your opinion in this regard.

**Comment by tfunatani** [comment]
Thanks for your contacting!
Based on @RAJU2529 -san's opinion, my new change idea is below,

```
Important
By default, "SignatureScheduleDay" is set as "8" so Microsoft Defender Antivirus will not schedule protection updates. 
Enabling these settings will override that default.
```

@yogkumgit -san, please tell me your opinion.

**Comment by tfunatani** [comment]
@RAJU2529 -san, thanks for your contacting!
Based on your opinion, my new change idea is following.

```
By default, "SignatureScheduleDay" is set as "8" and "SignatureUpdateInterval" is set as "0" so Microsoft Defender Antivirus will not schedule protection updates.
Enabling these settings will override that default.
```

"SignatureScheduleDay" as well as "SignatureUpdateInterval" are related to the scheduling protection updates, so I believe it should be changed as above.

**Comment by tfunatani** [comment]
@RAJU2529 -san, @yogkumgit -san
Could you please let me know if there are any updates about this thread?

**Comment by msbemba** [comment]
@tfunatani Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8250

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by tfunatani** [comment]
@msbemba -san
Thanks for your support!!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tfunatani Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
