### ISSUE TITLE
What permissions are needed?

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#820]
Could you please update this article to include a section on the permissions needed to create, test, and deploy a custom sensitive information type through the UI? Thank you!

**Comment by mypil** [comment]
@EricaToelle - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by EricaToelle** [comment]
Sorry about that!
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type

**Comment by LauraWi** [comment]
@chrfox This is about sensitive information types.

**Comment by mypil** [comment]
@EricaToelle - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/7d12420.


Thank you for your contribution to make the docs better! Much appreciated!
