### ISSUE TITLE
Support for Windows Servers

### ISSUE THREAD

**Issue by dianagrig03** [MicrosoftDocs/microsoft-365-docs#8201]
Support for Windows (client and server) and non-Windows platforms with Defender for Endpoint Plan 2 - this is really confusing for the partners, stating that in this case they don't need to purchase separate licenses for servers. 
As there are 2 options of licensing servers with DfE: Defender for Cloud or Defender for Endpoint Server SKU (with the minimum 50 DfE other licenses needed), it is very important to make it clear if the Defender for Endpoint Plan 2 licenses are sufficient or not for servers.

**Comment by msbemba** [comment]
@dianagrig03 Thank you for your feedback. Could you please provide us with details or the URL of the document that you are referring to?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @dianagrig03 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
