### ISSUE TITLE
Microsoft 365 groups (both the group site and group mailbox in Outlook on the web) 

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/microsoft-365-docs#8204]
(https://docs.microsoft.com/en-us/microsoft-365/compliance/create-apply-retention-labels?view=o365-worldwide#manually-apply-retention-labels) in the Manually apply retention labels section it's detailed that:

If you Publish a Retention Label on a Microsoft 365 group, it will be available both on the group site and group mailbox in Outlook on the web. OWA seems to be misssing this feature and the documentation may be corrected to:

Microsoft 365 groups (on the group site)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b974f07-d9f4-38c6-39ac-5d53aeda45fc
* Version Independent ID: fab281b5-1ff8-6e71-1756-c0579770f523
* Content: [Publish retention labels and apply them in apps to retain or delete content - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-apply-retention-labels?view=o365-worldwide#manually-apply-retention-labels)
* Content Source: [microsoft-365/compliance/create-apply-retention-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-apply-retention-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@asdcristi  Yes, the information in the section for this is more up-to-date - it specifies "When you publish retention labels to the Microsoft 365 Groups location, the retention labels appear in the SharePoint teams site but aren't supported by any email client for group mailboxes" and that includes OWA.  This bullet is now updated to reflect this.
