### ISSUE TITLE
mispelling

### ISSUE THREAD

**Issue by l3ftb3hind** [MicrosoftDocs/microsoft-365-docs#8205]
just a tiny typo

[Disable activation loc](https://docs.microsoft.com/en-us/mem/intune/remote-actions/device-activation-lock-disable) (iOS only)

Disable activation loc --> lock

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbd65bdb-26f7-32ec-0e00-0cea0f1dc304
* Version Independent ID: 0ffa2937-a9ed-f59d-d1d7-33a587872003
* Content: [Choose between Basic Mobility and Security and Intune - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/basic-mobility-security/choose-between-basic-mobility-and-security-and-intune?view=o365-worldwide)
* Content Source: [microsoft-365/admin/basic-mobility-security/choose-between-basic-mobility-and-security-and-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/basic-mobility-security/choose-between-basic-mobility-and-security-and-intune.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by RAJU2529** [comment]
@e0i, verify PR #8207

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @l3ftb3hind Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
