### ISSUE TITLE
Incomplete list of examples

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#8208]
Sensitivity labels are also used in Defender for Cloud apps and conditional access policies, please add these to the list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f1edffc-5d5e-8ed8-a7d1-7467fb14b3d1
* Version Independent ID: 13a701b4-3dfa-2b1b-2ff2-445183a1f1eb
* Content: [Learn about sensitive information types - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-learn-about?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitive-information-type-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitive-information-type-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks
