### ISSUE TITLE
Integrate all of this into the message header analyzer

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#821]
All of these fields need to be added to this:
https://mha.azurewebsites.net/

The CAT and SFTY fields are critical ones that are missing from the Forefront Antispam Report Header section on the output.

It should also provide the descriptions of the values

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by joinimran** [comment]
Thank you for your feedback on this. You can forward your request using the user voice channel. 

@mypil Please guide the user how a user voice can be raised.

Thanks.

**Comment by mypil** [comment]
@danmyhre - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by danmyhre** [comment]
Added to uservoice
https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/39323803-add-details-to-message-header-analyzer
