### ISSUE TITLE
Update Run diagnostics on archive mailboxes

### ISSUE THREAD

**Issue by ValerianHts** [MicrosoftDocs/microsoft-365-docs#8214]
in the section "Run diagnostics on archive mailboxes" described procedure doesn't work as described: just this dialogue is presented:

![image](https://user-images.githubusercontent.com/9352060/161739477-79f039c7-12b6-4b09-a447-f4d16e2f0dd5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes for Microsoft 365 Compliance - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ValerianHts  Can you try again today?  After investigating, this looks to have been a temporary problem.

**Comment by ValerianHts** [comment]
> @ValerianHts Can you try again today? After investigating, this looks to have been a temporary problem.

Still the same behaviour. 
My account is global administrator - I am on "non-german-cloud" Enterprise Tenant with >1000 accounts. Exchange is hybrid joined.

**Comment by cabailey** [comment]
@ValerianHts  Sorry to hear you're still having a problem with this.  It should work & it's possible it might resolve by itself.  If you're running the diagnostics on a mailbox because it has a problem, please open a support ticket instead.
