### ISSUE TITLE
Webfiteriing - block all and make whitelist only

### ISSUE THREAD

**Issue by MilanKrocek** [MicrosoftDocs/microsoft-365-docs#8215]
[Hello,

I'm missing a feature to block all URLs and allow only specific ones. Would it be possible in future release?

Thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbaaa90e-6975-ee29-335a-545cb6a55986
* Version Independent ID: 75c93c17-4952-a13f-ed60-d2baefd0337e
* Content: [Web content filtering](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-content-filtering?view=o365-worldwide&source=docs#configure-web-content-filtering-policies)
* Content Source: [microsoft-365/security/defender-endpoint/web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-content-filtering.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@MilanKrocek Thank you for your feedback. You can request the feature directly to the product team via the main feedback portal - https://feedbackportal.microsoft.com. One of our Product or dev engineers will be able to respond with the release date(If this is in the roadmap) or more information about the feature.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@MilanKrocek Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
