### ISSUE TITLE
Where exactly in the Admin Center are these Terms?

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/microsoft-365-docs#8216]
This article is published that explains an error condition, because of a licensing option the client needs to accept some terms.
Ok, the product has a link, he clicks the link and it takes him to a page. https://www.microsoft.com/en-us/microsoft-365/business/terms-and-conditions
That is alright as well. And that matches this article, https://docs.microsoft.com/en-us/microsoft-365/admin/simplified-signup/signup-business-standard?view=o365-worldwide#terms-of-service-update-for-simplified-sign-up-mode

The issue is that either link does not lead to the terms. Please clarify exactly where in the portal are these terms, because for the client either link just takes him to the portal and not specifically to any terms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c85a3fa-6b46-d441-17a0-a5d1f249e05f
* Version Independent ID: bfa64c29-3d44-bf5c-2b21-899f2b54269f
* Content: [Sign up for a Microsoft 365 Business Standard - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/simplified-signup/signup-business-standard?view=o365-worldwide#terms-of-service-update-for-simplified-sign-up-mode)
* Content Source: [microsoft-365/admin/simplified-signup/signup-business-standard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/simplified-signup/signup-business-standard.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Jmartinez589 Thank you for your feedback. If the updates affect your subscription, you’ll be prompted with instructions to view and accept the terms after signing in. As mentioned in the document, If you previously used Simplified Sign Up mode to purchase a business subscription before October 2021 without adding a business domain you may need to accept new terms of service for uninterrupted service and usage of the Microsoft Office apps. You may be sent emails or you'll see in-app prompts when you sign in to Microsoft 365 admin Center.

If you used Simplified Sign Up mode to purchase a business subscription before October 2021 without adding a business domain and still do not get an option to accept terms and conditions, you can contact our Support team via the need help section on the admin center.

@yogkumgit  There are no changes needed in the document.

Thanks
Sri

**Comment by Jmartinez589** [comment]
If this is the case, "If you used Simplified Sign Up mode to purchase a business subscription before October 2021 without adding a business domain and still do not get an option to accept terms and conditions" then article would be much improved to know that there might be an answer when calling into support. I can tell you that it would be great to know where these Terms are in the Portal so that they can be accepted.

Or, if there were a PowerShell means to request and then accept these Terms. That too would be beneficial.

**Comment by msbemba** [comment]
@Jmartinez589 Thank you for your response. The Terms and Services are usually available only when you purchase a new subscription. However, In these cases, they are being targeted to specific tenants and cannot be found directly on the Admin portal.

Hope this helps!

Thanks
Sri

**Comment by Jmartinez589** [comment]
Sri - Thank you for that. Ok. I think that answers the question is that there much be some flag that needs to be set when the terms are presented and accepted. What I am finding is that my client was flagged. He can see it in the banner of the app. It takes him the web page, than he then clicks on and leads him to the admin center, that then offers no Terms to accept.

It's like a dead end. It would be great if the product was improved to not end in this need to call into support.

**Comment by yogkumgit** [comment]
@Jmartinez589 Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
