### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by tiagodasilva1** [MicrosoftDocs/microsoft-365-docs#8217]
[Enter feedback here]
the link: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-configure?view=o365-worldwide

Micofoft instead microsoft

Configure capabilities of the service
Onboarding devices effectively enables the endpoint detection and response **capability of Micorosft D**efender for Endpoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e4b5c5a-10ba-3e0c-af47-c51fa5a7ccc3
* Version Independent ID: 1704fddc-5cda-e55e-3190-74a748ae2e3d
* Content: [Onboard devices and configure Microsoft Defender for Endpoint capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-configure.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@tiagodasilva1 Perfect finding typo error

**Comment by RAJU2529** [comment]
@mjcaparas , Please verify and merge this  PR #8219

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @tiagodasilva1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
