### ISSUE TITLE
Add details on ARC

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#822]
Add all of the details on ARC headers to this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47e11dd-53ab-5f62-ac6c-59dbc00eed0d
* Version Independent ID: 362ad038-3b64-f342-2f8e-111635c4337d
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers)
* Content Source: [microsoft-365/security/office-365-security/anti-spam-message-headers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by joinimran** [comment]
@danmyhre :  Thank you for your query here. Please note there are many headers not listed in this document and they are internal and only used by Microsoft anti-spam team for diagnostic purposes.

This was also addressed in another same query. Please see #486 (comment)

Thanks.

@mypil FYI Please.

**Comment by danmyhre** [comment]
ARC is not internal to MSFT and that other post is talking about the X-Forefront-Antispam-Report header.

**Comment by mypil** [comment]
@danmyhre -  From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/06e4662adaa223a3d29cef1c503d6636518d5be2. 


Thank you for your contribution to make the docs better! Much appreciated!
