### ISSUE TITLE
Missing setup section

### ISSUE THREAD

**Issue by ShawnBaer** [MicrosoftDocs/microsoft-365-docs#8223]
In the Microsoft 365 admin center, select [Setup](https://go.microsoft.com/fwlink/p/?linkid=2171997), and then view the Files and content section.

- not seeing this section on the setup sections (nothing after Device Management)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 215aae2b-deef-07f9-03cf-009006b8cabb
* Version Independent ID: bb7fd949-ff1a-dc43-d454-3fa2c4d938db
* Content: [Set up SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/set-up-content-understanding)
* Content Source: [microsoft-365/contentunderstanding/set-up-content-understanding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/set-up-content-understanding.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ShawnBaer Thank you for your feedback. This sounds like a bug on the tenant. I'd recommend you contact Microsoft support via the need help section so that a tech support engineer can work with you to fix this issue as it should be available if there is at least one SharePoint Syntex license in the tenant. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ShawnBaer Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
