### ISSUE TITLE
I see network requests to IP addresses not on the published list, do I need to provide access to them?

### ISSUE THREAD

**Issue by wcneumann219** [MicrosoftDocs/microsoft-365-docs#8224]
This portion of the article says a lot, but the text lacks context. I have a client that thinks allowing traffic to pass through those IP unlisted IP addresses represents a security risk. These paragraphs just say they exist but says nothing about security implications. My belief is that they do not represent a security risk all the traffic going to M365 services is also being secured using PKI certificates and SSL secured traffic via HTTPS. Please consider updating this portion of the article to more clearly explain why allowing traffic through unpublished IP addresses does NOT represent a security risk.

Thanks in advance!
Bill

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7dc5655-eddb-360e-8906-d61b8e12f667
* Version Independent ID: c7939a12-24ce-5b98-c958-94a66b90ff1a
* Content: [Managing Office 365 endpoints - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/managing-office-365-endpoints?view=o365-worldwide#pacfiles)
* Content Source: [microsoft-365/enterprise/managing-office-365-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/managing-office-365-endpoints.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. The security implications of allowing direct connectivity to Office 365 endpoints are addressed with great detail in https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-network-connectivity-principles?view=o365-worldwide. We try to balance the density of these complex topics by providing appropriate cross-links in all of our networking articles to enable discoverability of related information. I've added a note in the PAC section linking to this article. Thanks, Kelley
