### ISSUE TITLE
When will this feature be available in europe?

### ISSUE THREAD

**Issue by KbWorks** [MicrosoftDocs/microsoft-365-docs#823]
When will this feature become available in Europe as it states only US.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0beb3664-94e2-fc84-15ee-184d34f0d947
* Version Independent ID: 64bbd0e0-8ded-c2e0-6688-5b6a51144a40
* Content: [Self-service purchase FAQ](https://docs.microsoft.com/nl-nl/microsoft-365/commerce/subscriptions/self-service-purchase-faq?source=docs#feedback)
* Content Source: [microsoft-365/commerce/subscriptions/self-service-purchase-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/self-service-purchase-faq.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@KbWorks Self-service purchase capabilities will become available for Power BI Pro in the US on 1/14 and will be made available in additional countries shortly after that.
