### ISSUE TITLE
Advanced Hunting API (M365 Defender API) Permissions

### ISSUE THREAD

**Issue by fabiotelesMS** [MicrosoftDocs/microsoft-365-docs#8232]
Hello,

I would like to suggest a correction the permissions needed for the Advanced Hunting API for M365 Defender.
To use it we need **Microsoft Threat Protection - AdvancedHunting.Read.All** to access the tables. I tested it with a new App Registration and with AdvancedQuery.Read.All only I had the **Forbidden** message with a PowerShell script.

Just to clarify this and the permissions that should be in place.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea8d6114-48d6-9157-0cbe-2b33440c7eb3
* Version Independent ID: 2aa1b7a5-0d0f-1a1d-2091-28360fef0363
* Content: [Microsoft 365 Defender advanced hunting API](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-advanced-hunting?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/api-advanced-hunting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/api-advanced-hunting.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @fabiotelesMS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
