### ISSUE TITLE
Update section superseded with latest guidance?

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#8233]
The section of this page linked here - https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-vdi?view=o365-worldwide#updating-non-persistent-virtual-desktop-infrastructure-vdi-images

relates to updating non-persistent virtual desktop infrastructure (VDI) images using offline servicing tools to patch golden/master images.

This now appears to have been superseded by the steps outlined in the following article - 
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deployment-vdi-microsoft-defender-antivirus?view=o365-worldwide

which states "You no longer need to create and seal golden images on a periodic basis, as updates are expanded into their component bits on the host server and then downloaded directly to the VM when it's turned on."

Would be good to either understand the reasoning for the discrepancy or update this article to reflect the guidance in the other article.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5b23fe-37ce-e3b0-ad76-55a416eaa865
* Version Independent ID: 26becb70-47ff-38fe-592f-99d84f6aba12
* Content: [Onboard non-persistent virtual desktop infrastructure (VDI) devices](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-vdi?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-vdi.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-vdi.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@pjrcdf Thank you for your feedback. We have modified the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8253

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pjrcdf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
