### ISSUE TITLE
URL not valid or missing feature in API

### ISSUE THREAD

**Issue by PhilippEisenmann** [MicrosoftDocs/microsoft-365-docs#8234]
The url
`  /testwdatppreview/machinegroups`
is not valid and cannot be used.

Is this still a preview feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ab3b9c-e91a-3878-d463-47313f309367
* Version Independent ID: 4052f89a-5cab-7b2d-bf67-732af647302f
* Content: [Get RBAC machine groups collection API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machinegroups-collection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-machinegroups-collection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-machinegroups-collection.md)
* Product: **w10**
* GitHub Login: @mjcaparas
* Microsoft Alias: **leonidzh**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @PhilippEisenmann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
