### ISSUE TITLE
"<tenant>-files.sharepoint.com" and "<tenant>-myfiles.sharepoint.com" still in use?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/microsoft-365-docs#8235]
According to the documentation:

* https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges

And the "Microsoft 365 Network Connectivity Test":

* https://connectivity.office.com/

"\<tenant\>-files.sharepoint.com" and "\<tenant\>-myfiles.sharepoint.com" must be accessible. But these domains doesn't even resolve to anything (tried 1.1.1.1 and 8.8.8.8), not for our tenant anyways, and I also get an error for these in the connectivity test.

* **Are these two mentioned endpoints/ domains still in use?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
These domains are still active, but in order to successfully ping them, you must prepend the name of your tenant, and you must have configured your tenant with SharePoint Online. -Kelley

**Comment by o-l-a-v** [comment]
@kelleyvice-msft 

I'm replacing <tenant> with my tenant initial domain (before .onmicrosoft.com), of course.

One of the mentioned domains can't be pinged, so please don't close this.

**Comment by kelleyvice-msft** [comment]
@o-l-a-v, which domain doesn't respond to pings? And what happens when you try to navigate to it in a browser?

**Comment by kelleyvice-msft** [comment]
@o-l-a-v, I've confirmed that these domains are pingable for several other tenants. I'm not sure why they don't exist in your tenant, but I will talk to engineering about adding a note to the article to call out that they might not be used in a given tenant. Thanks for reaching out! -Kelley

**Comment by steve-prentice** [comment]
Hey @o-l-a-v / @kelleyvice-msft, we have the same thing here. The "files" or "myfiles" URLs don't exist and appear to be spurious on three (i.e. all) of the tenants I manage.

**Comment by virtco-com** [comment]
Hi @kelleyvice-msft, I have the same thing too...

![image](https://user-images.githubusercontent.com/58813428/185393783-396b7b86-2ce6-422e-a1e7-a95680334006.png)

These resolve correctly and work (where <tenant> is replaced with my tenant prefix)
<tenant>.sharepoint.com 
<tenant>-my.sharepoint.com 
<tenant>-admin.sharepoint.com 

These do not resolve on any DNS server I've tried (1.1.1.1,1.0.0.1,8.8.8.8 and our own DNS servers):
<tenant>-files.sharepoint.com 
<tenant>-myfiles.sharepoint.com

Obviously, these are not DNS records I can control.
