### ISSUE TITLE
Any timeline on when the limitations will be fixed?

### ISSUE THREAD

**Issue by fthorild** [MicrosoftDocs/microsoft-365-docs#8236]
We have invested quite heavily in content types going on since 2014-2015

We also have a strong demand from security starting to classify docs. We are struggling with the fact that encryption and content types collides. Is there a hope for this being fixed or is the right way forward to somehow work without utilizing content types i.e. are content types a dead end?

Raising this in a context of an org with > 40 000 users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files in SharePoint and OneDrive - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
@fthorild  Can you tell me which content types you're most interested in?  Unfortunately, we can't provide timelines for future enhancements using GitHub Issues but if you give me some specific examples, I'll see what I can find out.  This might be a question better asked on the Yammer site: https://www.yammer.com/askipteam

**Comment by fthorild** [comment]
Hi @cabailey - thanks for reaching out. In our case it is custom content types. Content types has been slightly over used (provisioned in a lot of sites) and that we are moving away from. However, in one particular and fairly popular case a custom content type is in use. Agree on the forum but I figured, let's start off here. Do you think it make sense to raise a premium support ticket with the question? Will jump in and post in the yammer forum, thanks for pointing it out 👍

**Comment by cabailey** [comment]
@fthorild Since you're talking directly to Sanjoyan (the PM owner for this feature) on the Yammer site, closing this GitHub Issue that's designed to flag issues with the documentation.  I couldn't leave you in better hands :-)
