### ISSUE TITLE
More Information section update

### ISSUE THREAD

**Issue by dagroll** [MicrosoftDocs/microsoft-365-docs#8238]
Under the "More Information" section of this article, it states that " For our commercial customers of Office 365, deprecation of TLS 1.0 and 1.1 will begin October 15, 2020 and rollout will continue over the following weeks and months."   Can you update this article with the current status of the deprecation of support for TLS 1.0 and 1.1?  We are 18 months past the published October 15, 2020 start date.  Is the deprecation work for commercial Office 365 tenants complete?  Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f7e4139-a562-6b81-6584-277efc4f6103
* Version Independent ID: e812b33a-f183-8b6a-bab0-447ddab2f26f
* Content: [Preparing for TLS 1.2 in Office 365 and Office 365 GCC - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/prepare-tls-1.2-in-office-365?msclkid=8417d1d2b5ae11eca27ee01330cb9521&view=o365-worldwide)
* Content Source: [microsoft-365/compliance/prepare-tls-1.2-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prepare-tls-1.2-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **shmehta**

**Comment by msbemba** [comment]
@dagroll Thank you for your feedback. The deprecation work for commercial Office 365 tenants was completed as of Jan 31, 2022.

We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8254

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per Author's comment.
