### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/microsoft-365-docs#824]
On the [Information barriers page](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers), in the Important callout box there is a link to the compliance boundaries page. This link goes to an incorrect page. The correct URL is https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Information barriers overview](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@EricaToelle - Thank you for pointing this out.

PR #840  has been created to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
