### ISSUE TITLE
Include https://connectivity.office.com/ in section Test Your Existing Network

### ISSUE THREAD

**Issue by exactmike** [MicrosoftDocs/microsoft-365-docs#8241]
Hi, I think the section "Test Your Existing Network" should include a description of and link to https://connectivity.office.com/ since it is more directly applicable to general M365 network planning/testing than the Remote Connectivity Analyzer set of tools.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 677e2ded-11ef-1bc1-6e41-d0826bbe20c4
* Version Independent ID: 81a18ad4-22ed-e97d-949d-2e969a69c91b
* Content: [Network and migration planning for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/network-and-migration-planning?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/network-and-migration-planning.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/network-and-migration-planning.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@exactmike Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8255

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @exactmike Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
