### ISSUE TITLE
Repository Files Don't Work

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/microsoft-365-docs#8244]
To onboard, this page indicates that we need to create three Configuration Profiles for Full Disk Access, Network Filter, and Notifications. I downloaded the items from the linked GitHub Repository:
https://github.com/microsoft/mdatp-xplat/tree/master/macos/mobileconfig/profiles

When creating these configuration profiles, they all return an error when adding the repository files: "Must be a well formed XML string" and I cannot continue creating these profiles. So, how do we proceed with these three configurations??

![image](https://user-images.githubusercontent.com/92554993/162047222-eb91befe-a937-4680-b430-868d9201d7e6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd66a255-36e5-29dc-7610-d50ef8bca3f3
* Version Independent ID: 17375473-bc07-f8e5-a85f-d732bbba3d71
* Content: [Intune-based deployment for Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#onboarding-blob)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-with-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-with-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by RAJU2529** [comment]
I think backward slash is missing at the end of the each url

**Comment by DontNeedNoGit** [comment]
Negative. I also tried forward slashes, but no luck.

![image](https://user-images.githubusercontent.com/92554993/163014641-79d1d00e-8ff3-4cde-adec-1e45c0fb298c.png)

![image](https://user-images.githubusercontent.com/92554993/163014787-6cdc4c53-7711-4021-b709-b57ad4e66e60.png)

**Comment by DontNeedNoGit** [comment]
This issue is closed. For whatever reason, trying to save the mobileconfig files from GIT got me a source code for the GIT site. This doesn't make sense since it automatically offered the file name. In any case, right-clicking the links in the instructions on this page got me an XML file that worked.
