### ISSUE TITLE
What is Microsoft recommendation on automation of Advanced eDiscovery cases in Microsoft 365?

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/microsoft-365-docs#8247]
What is Microsoft recommendation on automation of Advanced eDiscovery cases in Microsoft 365?

1. Create advanced eDiscovery Cases
2. Manage advanced eDiscovery Cases
3. Export advanced eDiscovery search reports
4. Dashboard for total no. of cases, total no. of holds, total no. of SPO sites on hold, total no. of teams on hold etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b65228-2f7b-17bc-bba4-1735618208da
* Version Independent ID: ef891290-e3f0-d63b-5586-267733d45b01
* Content: [Create and manage Advanced eDiscovery cases in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-and-manage-advanced-ediscoveryv2-case?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-and-manage-advanced-ediscoveryv2-case.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-and-manage-advanced-ediscoveryv2-case.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by jaganpt** [comment]
Any update on this would be great. Thanks.

**Comment by markjjo** [comment]
@jaganpt I believe you can use Microsoft Graph APIs to automate some if not all of these tasks. Please see: https://docs.microsoft.com/en-us/graph/api/resources/ediscovery-ediscoveryapioverview?view=graph-rest-beta

For the last one about holds, we have published a PowerShell script that generates a holds report; see https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases?view=o365-worldwide

Finally, there are plans to release a new holds report functionality in Advanced eDiscovery. This report will provide info about holds in both Core and Advanced eDiscovery. See this roadmap item for a brief description: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=88540

Hope this helps.
