### ISSUE TITLE
Out of date screenshots

### ISSUE THREAD

**Issue by ElfNeedsFood** [MicrosoftDocs/microsoft-365-docs#8256]
[Enter feedback here]

Screenshots for what the user sees are out of date.  New prompt is not clear on allowing the user to opt-out, but rather encourages reversing setting preferred by the organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a29483-a070-ccc1-b064-176dfa49d5e9
* Version Independent ID: bad082c0-9ca2-0ade-6b1f-0ba5ac26017b
* Content: [Configure Focused Inbox for everyone in your organization - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/configure-focused-inbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/configure-focused-inbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/configure-focused-inbox.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ElfNeedsFood Thank you for your feedback. I'll be updating the new screenshots shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@kwekuako Email sent, please reply. Thanks

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Please comment.

**Comment by msbemba** [comment]
@ElfNeedsFood  Sorry about the delay. I have been working with the product group, Could you please provide the snip or screenshot of what the New prompt looks like to your users? As they would like to understand why the user to opt-out option is missing.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @ElfNeedsFood We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
