### ISSUE TITLE
Incorrect Instructions

### ISSUE THREAD

**Issue by jesslyn-omm** [MicrosoftDocs/microsoft-365-docs#8257]
Incorrect information.  There is no 'Office 365 Extra File Storage' option available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add more SharePoint storage to your subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by RAJU2529** [comment]
@jesslyn-omm , share the screenshots so that I will remove it .

**Comment by jesslyn-omm** [comment]
Apologies.  The instructions are not incorrect, there is a note about VL/CSP customers not being able to purchase directly from Microsoft.
