### ISSUE TITLE
Risk of ambiguous interpretation behind the meaning of "Group" in Defender for Office 365 anti-phishing policy documentation 

### ISSUE THREAD

**Issue by ComaCluster** [MicrosoftDocs/microsoft-365-docs#8258]
At the Microsoft Defender for Office 365 section that explains [how to create an anti-phishing policy](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-create-anti-phishing-policies), under item 4 there's a Groups bullet point that reads:

> Groups: The specified distribution groups, mail-enabled security groups, or Microsoft 365 Groups in your organization.

I think it would be beneficial if that line made it very clear that the policy would only apply to the _email address_ of the DL, M365 Group, or mail-enabled security group and not the members of that group. It's obvious that the policy configurations would not flow through to the members if you think about it, but when I read the word "Group" my mind will automatically connect concepts related to local security groups, AD, AAD, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ea08aa-4520-8f48-93e2-0ce74cd43298
* Version Independent ID: 7be23d3d-f72b-abd3-e2c4-96ff3998a59b
* Content: [Configure anti-phishing policies in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-create-anti-phishing-policies)
* Content Source: [microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ComaCluster, a couple of points:

- That exact same functionality (the ability to select groups that a policy applies to) and the same description text appears in ~8 other topics for the various protection features, so what we do here is what I'm going to do everywhere.
- For distribution groups and mail-enabled security groups, the policy applies to the *group members*, not to specifically/only the email address of the group. The really old UI in the Exchange admin center (EAC) for protection policies (spam, malware, phishing, etc.) was **The recipient is a member of**. I'm sure DL expansion happens to account for nested groups and to get the full membership of the group.

  The complication is M365 Groups, in which case the Group itself (which is basically a special type of mailbox) is the recipient (basically, more like an individual recipient than a group). From an email perspective, user who are "members" of that M365 Groups are really just security principals who receive access to the email contained within.

So, I need to split out the description into two different items:

> - **Groups**:
>     - Members of the specified distribution groups or mail-enabled security groups.
>     - The specified Microsoft 365 Groups.

Comments?

**Comment by chrisda** [comment]
I went ahead and merged my changes as described.

Thanks for the feedback.

Closing
