### ISSUE TITLE
Error in page

### ISSUE THREAD

**Issue by gamory** [MicrosoftDocs/microsoft-365-docs#8259]
I noticed that the example command is "RegistryEvents | limit 10", but that appears to be an invalid request.  As near as I can tell, the correct one is "DeviceRegistryEvents | limit 10".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e93614ec-1755-75cc-7672-ccdfc50d2946
* Version Independent ID: 9b867028-f6eb-fe80-ca88-2aa860a123bf
* Content: [Advanced Hunting with Python API Guide](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-sample-python?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-advanced-query-sample-python.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-advanced-query-sample-python.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@gamory Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8321

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gamory Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
