### ISSUE TITLE
Standard and strict recommendations switched around

### ISSUE THREAD

**Issue by yvesrosius** [MicrosoftDocs/microsoft-365-docs#826]
The table under heading EOP outbound spam filter policy settings seems to have values that have been switched around. Standard is more strict than strict.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp#eop-anti-phishing-policy-settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Office 365 ATP security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, etc](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp#eop-anti-phishing-policy-settings)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by webash** [comment]
Yeap this definitely seems to be wrong!

**Comment by mypil** [comment]
@yvesrosius @webash - Thank you for submitting feedback.

 From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/fae8ba40df0a7f73ea311446f061bf8697b93e70. 


Thank you for your contribution to make the docs better! Much appreciated!
