### ISSUE TITLE
hugozan9

### ISSUE THREAD

**Issue by hugozan9** [MicrosoftDocs/microsoft-365-docs#8260]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd61abe1-251f-1409-d386-145d93c8f18f
* Version Independent ID: b340c591-d6bf-ae5f-e9b1-b32be18d6bee
* Content: [Verify eligibility for Microsoft 365 Education subscriptions](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/verify-academic-eligibility?view=o365-worldwide#verify-your-schools-academic-eligibility)
* Content Source: [microsoft-365/commerce/subscriptions/verify-academic-eligibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/verify-academic-eligibility.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by RAJU2529** [comment]
@yogkumgit   There is no proper feedback so close this issue #8260,
