### ISSUE TITLE
Consistent terminology

### ISSUE THREAD

**Issue by ma261065** [MicrosoftDocs/microsoft-365-docs#8262]
The section "How long it takes for retention policies to take effect" has a diagram that uses the term "synced" The text underneath talks about "distributed". Are they the same thing?

Also, the actual portal shows the status as "Enabled (Success)", while the diagram in the doco shows a status of "Success (ON)". Are they the same thing?

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: fd61abe1-251f-1409-d386-145d93c8f18f
Version Independent ID: b340c591-d6bf-ae5f-e9b1-b32be18d6bee
Content: [Verify eligibility for Microsoft 365 Education subscriptions](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/verify-academic-eligibility?view=o365-worldwide#verify-your-schools-academic-eligibility)
Content Source: [microsoft-365/commerce/subscriptions/verify-academic-eligibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/verify-academic-eligibility.md)
Service: o365-administration
GitHub Login: @cmcatee-MSFT
Microsoft Alias: cmcatee

**Comment by msbemba** [comment]
@ma261065 Thank you for your feedback. I do not see the section "How long it takes for retention policies to take effect" in this document. Could you please provide the URL of the document you are referring to ?

Thanks
Sri

**Comment by ma261065** [comment]
Sorry, this is the document - [https://docs.microsoft.com/en-us/microsoft-365/compliance/create-retention-policies?view=o365-worldwide#how-long-it-takes-for-retention-policies-to-take-effect](url)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ma261065 Thank you for your feedback. I will fix the document shortly.

**Comment by msbemba** [comment]
@ma261065 Thank you for your feedback. We have fixed the diagram to match the portal. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8429

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing us per Author's input. Thanks
