### ISSUE TITLE
Error finding certificate '' from azure key vault

### ISSUE THREAD

**Issue by Srinivasu9900** [MicrosoftDocs/microsoft-365-docs#8263]
Run in to issues:

When I ran the following PowerShell Code, Got struck at below Error:

$AppId = "[App ID]"
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $AppId, (ConvertTo-SecureString -String "[Secure String]" -AsPlainText -Force)

New-MigrationEndpoint -RemoteServer outlook.office365.com -RemoteTenant "advantageircom.onmicrosoft.com" -Credentials $Credential -ExchangeRemoteMove:$true -Name "MEd to Ad 2" -ApplicationId $AppId 

Error:
Error finding certificate '' from azure key vault for tenant '1e6110c5-ae10-4a2a-8e7a-0c6869075010'.
    + CategoryInfo          : NotSpecified: (:) [New-MigrationEndpoint], KeyVaultFailureErrorException
    + FullyQualifiedErrorId : [Server=DM6PR08MB5866,RequestId=9bb2b39a-aec1-4cc8-b8be-dfa2eee85666,TimeStamp=4/8/2022 5:54:25 AM] [FailureCategory=Cmdlet-KeyVaultFailureErrorException] 91254D5C,Microsoft.Exchange.Manag 
   ement.Migration.MigrationService.Endpoint.NewMigrationEndpoint
    + PSComputerName        : outlook.office365.com

Can someone please help me quickly.

**Comment by yogkumgit** [comment]
@Srinivasu9900 Please indicate which document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@Srinivasu9900 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
