### ISSUE TITLE
Clarity regarding files in scope for BAFS

### ISSUE THREAD

**Issue by rucam** [MicrosoftDocs/microsoft-365-docs#8265]
The _A few things to know about block at first sight_ section says:

> Block at first sight only uses the cloud protection backend for executable files and non-portable executable files that are downloaded from the Internet, or that originate from the Internet zone.

To be clear, is this based on mark of the web?  If not, what?

Thanks!

**Comment by yogkumgit** [comment]
@rucam Please indicate which document you are referring to. Thanks

**Comment by rucam** [comment]
Hi @yogkumgit sorry, thought I was posting the issue to the article and not the entire site.

This is the doc:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-block-at-first-sight-microsoft-defender-antivirus?view=o365-worldwide

**Comment by msbemba** [comment]
@rucam Thank you for your feedback. You are right, it depends on the mark of the web to identify the zone from which the file was downloaded.

Hope this helps!

@yogkumgit  No changes are needed in the document.

Thanks
Sri
