### ISSUE TITLE
Limits of records in Explorer

### ISSUE THREAD

**Issue by ShawnHag** [MicrosoftDocs/microsoft-365-docs#8266]
Hi,
Is there a limit in how many records can be shown in the Explorer ?

I understand that theres a limit of 200,000 records when exporting the data, 
but I was wondering if records shown in the Explorer will be limited if it exceeds a certain number.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67966fc-41a2-d368-3ec9-e74768984af4
* Version Independent ID: e2b8c076-e23b-4141-dbe1-62d984e6a87a
* Content: [Threat Explorer and Real-time detections - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/threat-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/threat-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/threat-explorer.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@ShawnHag Thank you for your feedback. You are correct, the limit is only for records when exported as mentioned in the document. There are no limits as such for viewing it in the threat explorer.

Hope this helps!

@yogkumgit  No changes are needed in the document.

Thanks
Sri

**Comment by ShawnHag** [comment]
Thank you for your comment!
This information really helped
