### ISSUE TITLE
Missing https://security.microsoft.com/securitypoliciesandrules

### ISSUE THREAD

**Issue by Zvonimir-Maros** [MicrosoftDocs/microsoft-365-docs#8267]
On Microsoft 365 Defender Portal, as listed in the Policies & rules for RBAC Security Administrator it's missing Azure AD roles, it is listing only Roles and Device groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7052266e-b8f3-4d4f-4df7-bbf93780790d
* Version Independent ID: 9050a1bf-4a04-e629-eb6b-4b8277a16bfd
* Content: [Permissions in the Microsoft 365 Defender portal - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/permissions-microsoft-365-security-center?msclkid=ee788168b6f511ec8f6ba141f9c21622&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/permissions-microsoft-365-security-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/permissions-microsoft-365-security-center.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Zvonimir-Maros, I'm sorry, I don't understand. Can you please clarify?

> Security Administrator it's missing Azure AD roles, it is listing only Roles and Device groups.

**Comment by yogkumgit** [comment]
@Zvonimir-Maros We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
