### ISSUE TITLE
No mentioning of DKM

### ISSUE THREAD

**Issue by kentan112233** [MicrosoftDocs/microsoft-365-docs#8268]
Hi,

I do not see the mentioning of DKM in this page, https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-bitlocker-and-distributed-key-manager-for-encryption?view=o365-worldwide.
I would like to find out more on how DKM is applied in Exchange Online environment

**Comment by yogkumgit** [comment]
@KCCross Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@kentan112233 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
