### ISSUE TITLE
Install on Cloud Shell 

### ISSUE THREAD

**Issue by githubths** [MicrosoftDocs/microsoft-365-docs#827]
It is not possible to install the MSCommerce Module in the Azure Cloud Shell.

Error: 
PackageManagement\Install-Package : Unable to load shared library 'api-ms-win-core-sysinfo-l1-1-0.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG enviro
nment variable: libapi-ms-win-core-sysinfo-l1-1-0.dll: cannot open shared object file: No such file or directory

**Comment by mypil** [comment]
@githubths - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@githubths - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
