### ISSUE TITLE
Error in INTUNE Value.

### ISSUE THREAD

**Issue by desmphil** [MicrosoftDocs/microsoft-365-docs#8271]
[Enter feedback here]

Because of the line return in the VALUE below this create a **space** when you copy in the INTUNE string and it fails to deploy the policy
Please update this string using code (copy) RAW button like its is often done

`OMA-URI: ./Device/Vendor/MSFT/Policy/Config/Chrome~Policy~googlechrome~Extensions/ExtensionInstallForcelist
Data type: String
Value: <enabled/><data id="ExtensionInstallForcelistDesc" value="1&#xF000; echcggldkblhodogklpincgchnpgcdco;https://clients2.google.com/service/update2/crx"/>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77fbdd3c-a33c-84ef-082a-df4a483e3201
* Version Independent ID: 58d81554-45f9-192a-04a9-e0a6b92fe11f
* Content: [Get started with the Microsoft Compliance Extension - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-chrome-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-chrome-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-chrome-get-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@desmphil Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
