### ISSUE TITLE
Add an option to send email to each user's alternate email address (and via PowerShell)

### ISSUE THREAD

**Issue by ypae** [MicrosoftDocs/microsoft-365-docs#8280]
I would like to suggest to add a checkbox "send to the user's alternate email address" option so that I don't have to manually enter the email addresses manually, (separately not to share the temporary password to everyone)

Also, I would like to have an option like the following as part of password reset cmdlet so that I can send the same formated email generated by O365 Admin UI:

-NotifyViaEmail AllAdminUser
-NotifyViaEmail CurrentAdminUser
-NotifyViaEmail TargetAlternateEmail

If you have a workaround for this, please let me know.

Thanks,

Young-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1021a231-6649-4d53-4b6a-ae333b144f1e
* Version Independent ID: afea118c-fb56-8fb8-3e90-27ce2fb4a13b
* Content: [Resend a user's password - Admin Help - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/resend-user-password?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/resend-user-password.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/resend-user-password.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ypae Thank you for your feedback. Both the ideas are new and look good. Since these are new feature requests, I'd recommend you post them directly on our main feedback portal -https://feedbackportal.microsoft.com/   So that our Dev/product engineer can work on them and provide you with a response.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@ypae Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
