### ISSUE TITLE
There is no allow option in the UI

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/microsoft-365-docs#8282]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-tenant-allows?view=o365-worldwide

In this article there is a description of add to the Allow or Block, but the UI has now changed to just Block. There is no Allow option for Senders via the UI.

Senders:
Value: The sender domain or email address.
Action: The value Allow or Block.
Modified by
Last updated
Remove on
Notes

Please update the article to more accurately reflect the options in the user interface.
https://security.microsoft.com/tenantAllowBlockList?viewid=Sender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@RatulaC Please comment. Thanks

**Comment by yogkumgit** [comment]
@RatulaC Gentle reminder. Thanks

**Comment by chrisda** [comment]
@Jmartinez589, massive updates to the Tenant Allow/Block List content have fixed this.

Thanks for the feedback.

Closing
