### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by javybarron** [MicrosoftDocs/microsoft-365-docs#8285]
[Enter feedback here]
Just looking out for my Partner :)

Under the section:
Microsoft Intune Roles available in the Microsoft 365 admin center

Admin role | Who should be assigned this role?

Application manager | Assign the Application manager role to users who mangage the application lifecycle for mobile apps, configures policy-managed apps and views device info and configuration profiles.

The word "manage" is misspelled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6877a274-00b3-b013-5a94-2180edb5d353
* Version Independent ID: 2a0a912f-f11e-07cf-0b05-dbd4308b1d2f
* Content: [About Intune admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/intune-admin-roles-in-the-mac?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/intune-admin-roles-in-the-mac.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/intune-admin-roles-in-the-mac.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by RAJU2529** [comment]
@KwekuA , verity and merge PR #8286 if it correct.
