### ISSUE TITLE
"What's coming" section of Secure Score refers to December 2021 (4 months ago)

### ISSUE THREAD

**Issue by mcteufelms** [MicrosoftDocs/microsoft-365-docs#8289]
The "what's coming" section of MS Secure Score refers to December 2021 which is four months ago. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655194ea-3741-4039-ad60-cdf633fcec35
* Version Independent ID: 6b1877de-1a16-162a-d672-a5d71fb50c42
* Content: [What's coming to Microsoft Secure Score](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score-whats-coming?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-secure-score-whats-coming.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-secure-score-whats-coming.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@mcteufelms Thank you for your feedback. The author recently updated the document with the March 2022 data -https://docs.microsoft.com/en-us/microsoft-365/security/defender/whats-new?view=o365-worldwide#march-2022

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mcteufelms Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
