### ISSUE TITLE
Users seeing Sensitivity Label "Name" field rather than "Display Name" field.

### ISSUE THREAD

**Issue by smileythf** [MicrosoftDocs/microsoft-365-docs#829]
I migrated several of my labels from Azure Information Protection labels to unified sensitivity labels. [This](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels) causes the unified sensitivity label Name field to be populated with the label ID. This has not been an issue until now, because all of the other clients use the Display Name field. Unfortunately, it appears that this Public Preview incorrectly uses the Unified Label Name field instead of the Display Name field. I would just change the Name field, however this is not supported.
![image](https://user-images.githubusercontent.com/52077852/69533297-765fd580-0f6f-11ea-8e99-c1a9f16c5682.png)
![image](https://user-images.githubusercontent.com/52077852/69533309-7bbd2000-0f6f-11ea-9bff-a250bc01fc0b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?source=docs)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@smileythf - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
