### ISSUE TITLE
" use audit mode first to test the rule."

### ISSUE THREAD

**Issue by MikeSchorr** [MicrosoftDocs/microsoft-365-docs#8290]
[Enter feedback here]
The link for "[use audit mode first to test the rule](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluate-attack-surface-reduction?view=o365-worldwide)." is a dead link.  Please update to the correct URL or remove the link.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by RAJU2529** [comment]
@MikeSchorr , i too tested link, i conformed that the link is working fine

**Comment by yogkumgit** [comment]
@MikeSchorr Please confirm. Thanks

**Comment by MikeSchorr** [comment]
Looks to be working now.  Thank you, sorry about that.
