### ISSUE TITLE
Windows 11 DFE using this URL v20.events.data.microsoft.com but it's not mentioned in the spreadsheet.

### ISSUE THREAD

**Issue by luutuananh** [MicrosoftDocs/microsoft-365-docs#8292]
Windows 11 DFE using this URL v20.events.data.microsoft.com but it's not mentioned in the spreadsheet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@luutuananh Please confirm Thanks

**Comment by luutuananh** [comment]
> @luutuananh
> 
> us-v20.events.data.microsoft.com And us4-v20.events.data.microsoft.com Both are mentioned in Excel sheet

I check my proxy in my lab, it's also use both url v20.events.data.microsoft.com and us-v20.events.data.microsoft.com together.
