### ISSUE TITLE
How to migrate from Google Workspace Legacy free edition?

### ISSUE THREAD

**Issue by zorbag** [MicrosoftDocs/microsoft-365-docs#8293]
It's good that you have a page for migration, but it looks very hard. I would like to migrate from Google Workspace Legacy free edition to Microsoft 365 Family as we just use it as a family and not for any business. Is there a way to do that? Many people are looking since Google are killing the free tier and introducing a very expensive alternative.

Thanks,

Mario

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8162a6bc-d3e5-70e7-7c8b-fc641a05e64e
* Version Independent ID: 8162a6bc-d3e5-70e7-7c8b-fc641a05e64e
* Content: [Switch from Google Workspace to Microsoft 365 for business - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/moveto-microsoft-365/move-from-google-workspace-overview?view=o365-worldwide)
* Content Source: [microsoft-365/admin/moveto-microsoft-365/move-from-google-workspace-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/moveto-microsoft-365/move-from-google-workspace-overview.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@zorbag Thank you for your feedback. The document set is specifically for M365 Business and enterprise customers. However, you can contact the Support team via Microsoft 365 Family via the support option available on the portal. They will be able to guide you or refer you to a document that is available for the M365 Family edition.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @zorbag Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
