### ISSUE TITLE
email created unknowingly to my domain

### ISSUE THREAD

**Issue by ine74** [MicrosoftDocs/microsoft-365-docs#8294]
I bought my domain last year from go daddy with is revive-you.com and I couldn't buy an email to that domain in go daddy cause it says I have a Microsoft account to that domain . I never remember creating one . can you pls fix that riddle.

**Comment by yogkumgit** [comment]
@ine74 Please indicate which document you are referring to for the improvement and feedback. Thanks

**Comment by yogkumgit** [comment]
@ine74 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ine74** [comment]
It’s fine 


Sent from Yahoo Mail for iPhone


On Wednesday, April 13, 2022, 7:41 AM, Yogesh Kumar ***@***.***> wrote:




@ine74 Please indicate which document you are referring to for the improvement and feedback. Thanks
