### ISSUE TITLE
Endpoint security > Attack surface reduction > New Policy

### ISSUE THREAD

**Issue by aaronnavratil** [MicrosoftDocs/microsoft-365-docs#8296]
The page directs the creation of a new "Web protection profile" in MEM; but this profile type is not available

"
Go to the Microsoft Endpoint Manager admin center (https://endpoint.microsoft.com/), and sign in.
Choose Endpoint security > Attack surface reduction, and then choose + Create policy.
Select a platform, such as Windows 10 and later, select the Web protection profile, and then choose Create.
"

Please advise on the proper way to create a web protection profile, and update documentation.

See attached image:

<img width="1761" alt="asr" src="https://user-images.githubusercontent.com/64109888/163066423-430d9934-2b74-44cd-ba93-d8e6c939ff3f.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4489c89-f34a-b0d5-4e6d-edbe29e6d4e6
* Version Independent ID: 6587d8f8-855e-8e8d-1e8a-f34492825d54
* Content: [Protect your organization against web threats](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-threat-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/web-threat-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-threat-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@aaronnavratil Thank you for your feedback. I tested this in a couple of tenants and was not able to reproduce the issue as I see the options mentioned in the document.

![image](https://user-images.githubusercontent.com/45987684/163655174-87f9ff94-484d-44d8-8112-d2eb2898c6d4.png)


I'd recommend you to contact Microsoft support via the need help option on the admin center to file a bug or fix the problem with your M365 tenant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @aaronnavratil Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
