### ISSUE TITLE
Minimum Semi-Annual Enterprise Channel requirement not found

### ISSUE THREAD

**Issue by Freddy-Santos** [MicrosoftDocs/microsoft-365-docs#8298]
[Enter feedback here]
One of the requirements lists the minimum version of the Semi-Annual Enterprise Version shows 2202, but I do not see that as a version.  The latest I see if 2102 from March 8th as listed here:  https://docs.microsoft.com/en-us/officeupdates/semi-annual-enterprise-channel#version-2102-march-08

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed8ccbd-b955-4a11-f4dd-3a70b549a5f7
* Version Independent ID: 257024d1-afb3-954f-c848-21549cb64fac
* Content: [Enable co-authoring for documents encrypted by sensitivity labels in Microsoft 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-coauthoring?view=o365-worldwide#prerequisites)
* Content Source: [microsoft-365/compliance/sensitivity-labels-coauthoring.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-coauthoring.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Apologies - it was missing (Preview), now added.  See release notes https://docs.microsoft.com/en-us/officeupdates/semi-annual-enterprise-channel-preview#version-2202-march-08 and search for "AutoSave and coauthoring on sensitive encrypted documents"  It should be in the Semi-Annual Enterprise Version in July, but you can test it with the preview channel now.
