### ISSUE TITLE
View details for AllowSelfServicePurchase

### ISSUE THREAD

**Issue by Markus-Hanisch** [MicrosoftDocs/microsoft-365-docs#830]
I set / updated all Products to Enabled $False:
Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId CFQ7TTC0KP0P -Enabled $False #Power Apps
Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId CFQ7TTC0KP0N -Enabled $False #Power Automate
Update-MSCommerceProductPolicy -PolicyId AllowSelfServicePurchase -ProductId CFQ7TTC0L3PB -Enabled $False #Power BI Pro

Even though, I set / updated all Products to Enabled $False, the PowerShell Cmdlet "Get-MSCommercePolicy -PolicyId AllowSelfServicePurchase" still shows Enabled for property "DefaultValue".
How do I set/update the "DefaultValue" property of PolicyId "AllowSelfServicePurchase"? Is there no "Set-MSCommercePolicy -PolicyId AllowSelfServicePurchase" or "Update-MSCommercePolicy -PolicyId AllowSelfServicePurchase" PowerShell Cmdlet available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell#example-script-to-disable-allowselfservicepurchase)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by cmcatee-MSFT** [comment]
@Markus-Hanisch The default policy value for **AllowSelfServicePurchase** policy cannot be changed.

**Comment by jjacksonGithub** [comment]
Where can we petition to have this be an option? We should not be required to run Update-MSCommerceProductPolicy for every new product that MSFT releases. We should be able to disable self-service purchases for ALL products at a tenant level.
