### ISSUE TITLE
Question about the OS vulnerability management capability

### ISSUE THREAD

**Issue by ethanhou99** [MicrosoftDocs/microsoft-365-docs#8300]
[Enter feedback here]
Hi,

Our team is trying to develop a tool to monitor Azure service's security. One important check point is to verify if the Windows OS is still supported by Microsoft.

For example, we created a windows 7 virtual machine on Azure, based on the [official lifecycle doc](https://docs.microsoft.com/en-us/lifecycle/products/?terms=windows%207), the windows 7 is not supported after Jan 14 2020, however, we found that Windows update is still available recently:

![image](https://user-images.githubusercontent.com/43047951/163094688-07b61197-46a8-4451-b281-72b66d925e51.png)

Could you please tell me is this update can be seen as an OS vulnerabilities support?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1f5402-b627-d205-8e88-ca3fe609ef5f
* Version Independent ID: 0c91f8eb-368a-681a-209c-b03ff823945a
* Content: [Supported operating systems platforms and capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-supported-os?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/tvm-supported-os.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tvm-supported-os.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@ethanhou99  Microsoft malicious removal tool is common for windows 7 and higher versions. 
This update comes irrespective of OS

**Comment by ethanhou99** [comment]
> @ethanhou99 Microsoft malicious removal tool is common for windows 7 and higher versions. This update comes irrespective of OS

Gotcha, thanks!
