### ISSUE TITLE
Business Premium?

### ISSUE THREAD

**Issue by simonburbery** [MicrosoftDocs/microsoft-365-docs#8301]
Hi, I have been successfully enabling Litigation Hold for Business Premium users for the last couple of years... I am trying today and it is failing with the license error, has something changed?  If so I cannot find anything stating so, but I notice you do not mention it specifically on this page.

Appreciate your comments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff3e4302-c038-67aa-eb29-8b01c7fc4ed6
* Version Independent ID: 680317f5-19be-7268-5b40-f181ea3485da
* Content: [Create a Litigation hold - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-litigation-hold?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-litigation-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-litigation-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@simonburbery Litigation hold has always required an Exchange Online Plan 2 license (as per [this section](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-litigation-hold?view=o365-worldwide#assign-an-exchange-online-plan-2-license) in the article), but the product hasn't always enforced licensing (you needed to ensure that you have property licensing to be in compliance with the user agreement. It may be that the product is now enforcing licensing. 
You might check to see that the user who you want to place on LitHold is assigned an EXO P2 license. If they are assigned a EXO P1 license, then I believe you could assigned and Exchange Online Archiving add-on license, which supports LitHold.

I'm not sure if Business Premium include EXO P2 or not, *but* [this table](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWR6bM) shows that Business Premium supports Litigation Hold.

If you think you have the appropriate licensing but still can't place a mailbox on LitHold, I would suggest you contact MS Support.

**Comment by simonburbery** [comment]
Sorry I realised I was in PowerShell - the sku for MS Business Standard is
"O365 Business Premium" since it was called that prior to becoming
"Microsoft Business Standard"... that caught me out =)

Thanks,
Simon
