### ISSUE TITLE
Wrong URL 

### ISSUE THREAD

**Issue by StefanZGit** [MicrosoftDocs/microsoft-365-docs#8302]
The URL "www.mstfconnecttest.com" ist wrong and should be "www.msftconnecttest.com".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Other endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@StefanZGit Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8331

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @StefanZGit Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
