### ISSUE TITLE
Every (11) mention of "E5" is too vague here

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#8305]
Hello,

There are 11 occurrences of the term "E5" here.  It doesn't clarify if Office 365 E5 is the key ingredient or if EMS E5 would be enough.  It's a fair thing to wonder but it shouldn't need to be a wonder, it should be made nice and clear.

Please confirm exactly which E5 product is required.  Same goes for any mentions of the term "E3".  Since Microsoft offers several different E3 products and E5 products, it is merited to be more thorough here.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1aac99b-5c65-74d3-7610-b7ba4fcac493
* Version Independent ID: a0b2ab87-7d52-3429-630e-6b7a316b5f23
* Content: [Manage mailbox auditing - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-mailbox-auditing?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-mailbox-auditing.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-mailbox-auditing.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, I can see your point. Technically, it's the [Advanced Audit](https://docs.microsoft.com/microsoft-365/compliance/advanced-audit) feature that makes everything happen. Licenses that include Advanced Audit are described [here](https://docs.microsoft.com/microsoft-365/compliance/auditing-solutions-overview.md#advanced-audit-1).

I changed the first reference of E5 to say this:

> - By default, only mailbox audit events for users with licenses that include the [Advanced Audit](https://docs.microsoft.com/microsoft-365/compliance/advanced-audit.md) feature are available in audit log searches in the Microsoft 365 compliance center or via the Office 365 Management Activity API. These licenses are described [here](https://docs.microsoft.com/microsoft-365/compliance/auditing-solutions-overview.md#advanced-audit-1). For brevity, this article will collectively refer to licenses that include Advanced Audit as *E5/A5/G5 licenses*.

I then changed the remaining references from E5 and/or E5 Compliance add-on to E5/A5/G5.

Updates should be visible W 4/13 ~ 4:00 PDT.

OK?

**Comment by JeremyTBradshaw** [comment]
Hi @chrisda , yes that looks perfect. Thank you as always, and sorry to keep raising issues that you are the one who has to deal with them.

**Comment by chrisda** [comment]
Cool.

Thanks for the feedback.

Closing

**Comment by JonesMikael** [comment]
@chrisda It seems like the article still only reference "E5" and not specifically which E5. Was the update not pushed to docs.microsoft.com?
