### ISSUE TITLE
New Case action - Manage pseudonymize

### ISSUE THREAD

**Issue by ItaloDuarte** [MicrosoftDocs/microsoft-365-docs#8307]
There is a new case action called Manage pseudonymize and there is no information about this action.
we would like to have information about it on this page, because it is already explaining all actions here.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c1982d-931d-e5d9-6f54-8b63050932d5
* Version Independent ID: 30c21178-f013-4649-59ae-4b9f75e13ccc
* Content: [Insider risk management cases - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-cases?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@ItaloDuarte - thanks for the feedback. I closed the associated PR yesterday, I don't know that this action is confirmed, but will discuss with the PG team.
