### ISSUE TITLE
When Copying and pasting the text ensure there is a fullstop at the end of the txt parameter

### ISSUE THREAD

**Issue by Cobber57** [MicrosoftDocs/microsoft-365-docs#8308]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@Cobber57 Thank you for your feedback. Some DNS registrar expect you to add a trailing period at the end of the hostname or the record. Are you referring to the DKIm record- *._domainkey.SubDomainThatShouldntSendMail.contoso.com. TXT "v=DKIM1; p="  ?

**Comment by Cobber57** [comment]
Yes exactly, took me a while to work out the problem.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Cobber57 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
