### ISSUE TITLE
That doesn't make sense. 

### ISSUE THREAD

**Issue by Heymattman** [MicrosoftDocs/microsoft-365-docs#8309]
Delete the user to delete the Bookings calendar? That doesn't make sense.  Can't you delete a calendar without delete a user? Why is it the user can't delete their own calendar made in Bookings. 

Thanks,
Matt Hellwege

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa612c0e-c089-8b3e-8e2e-dd12b6fc382c
* Version Independent ID: fa014ea6-7aa2-b2bd-d913-165c3241675f
* Content: [Delete a booking calendar](https://docs.microsoft.com/en-us/microsoft-365/bookings/delete-calendar?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/delete-calendar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/delete-calendar.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Heymattman Thank you for your feedback. To delete a Booking calendar, generally we needn’t to delete user account. When we create a Booking calendar, for example, name it “Test ”, it creates a user in Admin center, and we can just remove that identity.

That is exactly what is explained in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Heymattman Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
