### ISSUE TITLE
Typos & Following Article

### ISSUE THREAD

**Issue by msternbergh** [MicrosoftDocs/microsoft-365-docs#8310]
In section "Prerequisites" step 2, URL in document is:
https://{your-servicenow-instance``}.service-now.com/auth_redirect.do //auth_redirect.do

But the URL in screenshot (and I believe the on the SNOW instructions) is:
https://{your-servicenow-instance``}.service-now.com/oauth_redirect.do //oauth_redirect.do

In section "Prerequisites" step 10, the "Redirect URL" in document is:
https://{service-now-instance-name``}.service-now.com/auth_redirect.do //auth_redirect.do

But the URL in screenshot is:
https://{your-servicenow-instance``}.service-now.com/oauth_redirect.do //oauth_redirect.do

In section "Prerequisites" step 15, the "Client ID/Clien Secret" step refers to Step 2. However, the "Client ID" and "Client Secret" are established in Step 3. 

In section "Prerequisites" step 15, the "Redirect URL" in document is:
https://{service-now-instance-name}.service-now.com/oauth\_redirect.do //includes a \ before _redirect.do

But the URL in screenshot is:
https://{your-servicenow-instance``}.service-now.com/oauth_redirect.do //oauth_redirect.do

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7bb990-5c3f-526c-3d52-0dd885c4b33f
* Version Independent ID: ce7bb990-5c3f-526c-3d52-0dd885c4b33f
* Content: [Configure Microsoft 365 support integration with Azure AD Auth Token - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/servicenow-aad-oauth-token?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/servicenow-aad-oauth-token.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/servicenow-aad-oauth-token.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@msternbergh Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8399

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @msternbergh Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
