### ISSUE TITLE
Turn off the built-in reporting experience disables report button

### ISSUE THREAD

**Issue by edwardverweij** [MicrosoftDocs/microsoft-365-docs#8311]
Please update document, after performing "Turn off the built-in reporting experience" by using the Powershell command Set-OwaMailboxPolicy -Identity OwaMailboxPolicy-Default -ReportJunkEmailEnabled $false the Report button is greyed out when a user wants to report a message. The command should be reverted  to:
Set-OwaMailboxPolicy -Identity OwaMailboxPolicy-Default -ReportJunkEmailEnabled $true
After performing this action the report button is available and not greyed out, when the user for example clicks report message, junk, "Report" button
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@edwardverweij Thank you for your feedback. This document pertains to "Enable the Report Message or the Report Phishing add-ins" and there is no mention on Powershell cmd to Set-OwaMailboxPolicy. If you are referring to a different document, please do let us know.

Thanks
Sri

**Comment by edwardverweij** [comment]
Hi Sri,
Thank you for your response, the latest version of the document is already updated and the Powershell command is removed. 
Best regards,
Edward
