### ISSUE TITLE
Needs testing

### ISSUE THREAD

**Issue by Degies** [MicrosoftDocs/microsoft-365-docs#8312]
[Enter feedback here]
What this page needs or perhaps the product is a page to test in what category a page is. If a web page is blocked it would be helpful to have a test to stick in the url and see as what category it is classified is so that it can be over ruled or fixed. Look at the Fortinet Fortiguard web-filter page that you can test and see what the url is classified as, request re-classification or have a bypass on.

Hope that helps

Looking good so far 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbaaa90e-6975-ee29-335a-545cb6a55986
* Version Independent ID: 75c93c17-4952-a13f-ed60-d2baefd0337e
* Content: [Web content filtering](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-content-filtering?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-content-filtering.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Degies Thank you for your feedback. I agree and that is a very good idea. Since this needs to go to the product/dev team I'd recommend you add such feedback directly on our feedback portal -https://feedbackportal.microsoft.com/ so one of our Dev/product engineers will be able to handle new feature or design requests.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@Degies Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
