### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by Azuredesk** [MicrosoftDocs/microsoft-365-docs#8314]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83719909-241b-2902-5ff1-496934da24e3
* Version Independent ID: d05e079d-f0d6-11ac-577c-f407cc49fcb7
* Content: [Add users and assign licenses - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/add-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/add-users.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by RAJU2529** [comment]
@yogkumgit , video is playing fine on windows 11 edge browser v100 and video played on android chrome browser

**Comment by yogkumgit** [comment]
@Azuredesk If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Azuredesk** [comment]
Plays now. No idea what was going on. tried many times (also W11 Edge). Had a reboot in-between. Must have made a difference. Sorry for trouble.
