### ISSUE TITLE
Tenant Isolation Link broken

### ISSUE THREAD

**Issue by crcarley** [MicrosoftDocs/microsoft-365-docs#8315]
this link (https://docs.microsoft.com/en-us/compliance/assurance/microsoft-365-isolation-controls?view=o365-worldwide) in the left navigation of the page does not work. Shows 404 error.
![image](https://user-images.githubusercontent.com/98420152/163306401-cc056617-bae1-46ec-89c3-022921d12968.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 032295e8-534c-71d5-0f9e-c7f96554a179
* Version Independent ID: f7da2f5a-09b6-59b4-15d7-b2c926748f32
* Content: [Subscriptions, licenses, accounts, and tenants for Microsoft's cloud offerings - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/subscriptions-licenses-accounts-and-tenants-for-microsoft-cloud-offerings.md)
* Service: **o365-solutions**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@crcarley Thank you for your feedback. The correct link would be https://docs.microsoft.com/en-us/compliance/assurance/assurance-microsoft-365-isolation-controls

I'll work with the author and get this fixed in the backed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@kelleyvice-msft replied that he will inform who can resolve.

**Comment by kelleyvice-msft** [comment]
Fixed with PR https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/13793. Changes may take a few hours to go live.
