### ISSUE TITLE
Missing Info howto batch-export data beyond page-limits

### ISSUE THREAD

**Issue by JJDE** [MicrosoftDocs/microsoft-365-docs#8316]
i try to export via powershell all /api/Machines  data , i'm aware of the 10.000 rows limit...
After research i would need to use the @odata.nextLink information to get all data in pages.
At least the /api/Machines endpoint seems to have BUGS here:
- If you call the odata-enpoint with a Top=X filter you will get NO @odata.nextLink
- If you call the odata-endpoint without a Top filter you get a @odata.nextlink but that seems to be wrong because with the nextlinks i get inifinive amounts of data (every response contains a nextlink) and the data is messy (Different "Id" for same "ComputerDNSName")
- Sample URLs:
1.run= https://api.securitycenter.windows.com/api/machines?$filter=onboardingstatus%20eq%20%27onboarded
2.run (nextlink from prev run)= https://api.securitycenter.windows.com/api/machines?$filter=onboardingstatus%20eq%20%27onboarded%27&$skip=10000
3.run (nextlink from prev run)= https://api.securitycenter.windows.com/api/machines?=onboardingstatus%20eq%20%27onboarded%27&=10000&$skip=10000
4.run (nextlink from prev run)= https://api.securitycenter.windows.com/api/machines?=onboardingstatus%20eq%20%27onboarded%27&=10000&=10000&$skip=10000
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72110011-1fc5-4e78-8e54-e43bc181b860
* Version Independent ID: c974e3d8-983a-02d4-d9dc-9603a3f8b510
* Content: [OData queries with Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/exposed-apis-odata-samples?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/exposed-apis-odata-samples.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/exposed-apis-odata-samples.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. thanks

**Comment by mjcaparas** [comment]
Please contact support.
