### ISSUE TITLE
Turn off built-in experience by setting ReportJunkEmailEnabled to False, renders the Report Message add-in unusable in OWA

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/microsoft-365-docs#8317]
If we run this cmdlet "Set-OwaMailboxPolicy -Identity OwaMailboxPolicy-Default -ReportJunkEmailEnabled $false", the "Report" button within the "Report Message" add-in will be grayed out in Outlook on the Web.

This means that "turning off the built-in experience" will actually affect the functionality of the "Report Message" add-in in Outlook on the Web and render it unusable since users will no longer be able to report any messages as junk or phishing or not junk to MS.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/42742435/163380820-56092752-7fd9-43a7-ac1f-f393434a53c2.png">

In a network trace, I can see this: {"@odata.context":"https://outlook.office365.com/api/beta/$metadata#Microsoft.OutlookServices.ReportMessageCommandResult","Properties":[{"Key":"RSP","Value":"{\"ERM\":false}"}]}. "ERM" stands for "Enable Report to Microsoft".

It also doesn't matter if User Submissions is turned on and configured on the Security Portal at https://security.microsoft.com/userSubmissionsReportMessage, as Outlook on the Web will still look at the value of ReportJunkEmailEnabled on the OWAMailboxPolicy that is applied on the user in question.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Alex-Catalin Thank you for your feedback. This section has been removed from the document as it is no longer relevant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Alex-Catalin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
