### ISSUE TITLE
Missing step ("Endpoints")

### ISSUE THREAD

**Issue by bodekf** [MicrosoftDocs/microsoft-365-docs#8319]
On this page, where it says:

Enable Microsoft Intune connection
To use this capability, enable your Microsoft Intune connections. In the Microsoft 365 Defender portal, navigate to Settings > General > Advanced features. 

...it should say:

Enable Microsoft Intune connection
To use this capability, enable your Microsoft Intune connections. In the Microsoft 365 Defender portal, navigate to Settings > **Endpoints** > General > Advanced features. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8dcf90-9dd2-d43f-d68c-83fe63e3ef99
* Version Independent ID: 1d1d2350-246a-c223-fd3d-bc89f2461abe
* Content: [Remediate vulnerabilities with threat and vulnerability management](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-remediation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/tvm-remediation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tvm-remediation.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@bodekf , May i get a screenshot showing **Endpoints**

**Comment by bodekf** [comment]
[cid:adc7e45c-26f2-4ca3-a161-00d6ac554770]
________________________________

**Comment by msbemba** [comment]
@bodekf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8400

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chrisda** [comment]
Update PR approved.

Closing
