### ISSUE TITLE
Hackers

### ISSUE THREAD

**Issue by erohner55** [MicrosoftDocs/microsoft-365-docs#8323]
My Office 365 account has been hacked twice in the last month. Microsoft is not a secure thing.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed9a314-00dd-bffd-69fa-8f93228044b6
* Version Independent ID: 4cece1bf-38f8-e293-5178-4ac5ee70bddc
* Content: [Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-defender?view=o365-worldwide#the-microsoft-365-defender-portal)
* Content Source: [microsoft-365/security/defender/microsoft-365-defender.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-defender.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@erohner55 Considering the nature of the issue please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
