### ISSUE TITLE
Provide clarifications

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/microsoft-365-docs#8324]
Hello,
due to new this new great feature and ongoing planned cross tenant migrations by multiple customers/projects, some things are left unclarified, even MS support ticket is unable to answer, so please check with product group and update this documentation for topics:

1. When will be destination MailUser be converted to destination Mailbox ? Is it automatic by "completing" migration batch or, manual step for conversion is needed?
2. Who / when will be source Mailbox be converted to source mailuser? is it automatic at some step or manual change is needed?
3. At which step / phase it is mandatory to have Exchange Online license assigned to destination MailUsers? can be this done after sync inside migration batch is status "synced" or after conversion from mailuser to mailbox? or is mandatory to be assigned before starting migration batch / sync process?
4. except setting destination MailUser X509 address, is it necessary to put any other proxyAddress (having only one/default to .onmicrosoft.com) fine, or we MUST have some other custom domain added to at destination tenant?

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#prepare-target-user-objects-for-migration)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I have requested clarification from the engineering team and will reply back to this issue when I have more information. -Kelley

**Comment by sgfurgi** [comment]
I was able to finish a migration and I can answer some of the question and others I will do wild guesses
1- The destination mail user is automatically converted to mailbox after migration. In my case the mail user was a synced one, but it was converted anyway, and the one in the Onprem environment I am still thinking if I disable the mail user and enable a remote mailbox. Don´t know if that process could affect in some way the mailbox in EXO
2- Also automatic
3- This is when I do a wild guess but I think this is like a regular Onprem/EXO migration. When you migrate the mailbox, will be migrated and will work for 30 days. If you don´t put a license on it, will be deleted
4- I think it´s not necessary. In our case the scenario was different from the one presented in the document. I don´t have another custom domain to put in the destination tenant, so I am migrating to the destination tenant using the onmicrosoft domain of that target tenant and then will do a switchover of the domain removing it from source domain and validating it on the target tenant.

**Comment by ropow** [comment]
When will be destination MailUser be converted to destination Mailbox ? Is it automatic by "completing" migration batch or, manual step for conversion is needed?

1 & 2. When you complete the migration the mailuser is converted to a mailbox in the target tenant. At the same time in the source tenant, the mailbox is converted to a mailuser.

3. This can be done while the user is still a mailuser, but do not assign a license prior to stamping the ExchangeGuid attribute, or a new mailbox will be created. You can also do as sgfurgi mentions, wait until after migration, as there is a 30 day grace period.

4. As far as proxy addresses, the only thing that needs to be stamped on the mail user is the LegacyExchangeDN as an X500, and any other X500 addresses that are on the source mailbox.

**Comment by hkusulja** [comment]
ok, can you please add those information / behavior on docs page.

**Comment by kelleyvice-msft** [comment]
Working on that right now.

**Comment by kelleyvice-msft** [comment]
I'm awaiting technical feedback before publishing revisions, which will hopefully happen early next week.

**Comment by kelleyvice-msft** [comment]
Updated in https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/14696.
