### ISSUE TITLE
Information partially not correct

### ISSUE THREAD

**Issue by RisticRile** [MicrosoftDocs/microsoft-365-docs#8327]
[Enter feedback here]
To disable "Manage the display of the Encrypt button in Outlook on the web":
For example, to disable the Encrypt button:
PowerShellCopy
Set-IRMConfiguration -SimplifiedClientAccessEnabled $false

That did not work! I
You have to run three commands:
Set-IRMConfiguration -SimplifiedClientAccessEncryptionDisabled $true
Set-IRMConfiguration -SimplifiedClientAccessDoNotForwardDisabled $true
Set-IRMConfiguration -SimplifiedClientAccessEnabled $false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33bb6e61-f899-955c-948d-bf17f0168fea
* Version Independent ID: be8ea691-3547-a442-d2ca-617e17225740
* Content: [Manage Office 365 Message Encryption - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/manage-office-365-message-encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/manage-office-365-message-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/manage-office-365-message-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@RisticRile Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8401

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@SRE93 Thank you. I have updated the PR with the parameter.

**Comment by yogkumgit** [comment]
@RisticRile Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
