### ISSUE TITLE
What is 'View Data' AD role

### ISSUE THREAD

**Issue by eric-jenouvrier** [MicrosoftDocs/microsoft-365-docs#8332]
Within Advanced Hunting page document a note highlight required permission a user should have to get a valid access token

But does someone known what is the **'View Data' AD role** ? 

on Azure AD such role not exist, or writter is talking about another role such Global Reader or Security Reader or a role having the right to read the Azure AD may be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea8d6114-48d6-9157-0cbe-2b33440c7eb3
* Version Independent ID: 2aa1b7a5-0d0f-1a1d-2091-28360fef0363
* Content: [Microsoft 365 Defender advanced hunting API](https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-advanced-hunting?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/api-advanced-hunting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/api-advanced-hunting.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Email sent, please reply. Thanks

**Comment by schmurky** [comment]
I am not very familiar with the API aspect of AH, but within AH, the roles required to view data are set out in [this page](https://docs.microsoft.com/microsoft-365/security/defender/custom-roles)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@schmurky Please comment. Thanks

**Comment by mjcaparas** [comment]
I think the reference to it being and AD role is incorrect. 

I think the accurate term is "View data" permissions as per: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/user-roles?view=o365-worldwide#permission-options

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
Thank you @mjcaparas. I have created a PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9173 to remove the AD part from that role.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @eric-jenouvrier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
