### ISSUE TITLE
Missing pages in PDF document

### ISSUE THREAD

**Issue by dilipdivgi** [MicrosoftDocs/microsoft-365-docs#8337]
[Pages 68 to 73 - Microsoft 365 Defender docs are blank in the PDF]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ecaaffb-60f9-e078-6229-212a818b9e53
* Version Independent ID: 1ecaaffb-60f9-e078-6229-212a818b9e53
* Content: [Microsoft 365 Zero Trust deployment plan](https://docs.microsoft.com/en-us/microsoft-365/security/microsoft-365-zero-trust?view=o365-worldwide)
* Content Source: [microsoft-365/security/Microsoft-365-zero-trust.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/Microsoft-365-zero-trust.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by RAJU2529** [comment]
Where did giu5 downloaded that pdf, where is the link in this article

**Comment by dilipdivgi** [comment]
Sorry, I should have added ithttps://docs.microsoft.com/en-us/microsoft-365/security/microsoft-365-zero-trust?view=o365-worldwide


-------- Original Message --------
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Missing pages in PDF
document (Issue #8337)
From: VARADHARAJAN K ***@***.***>
Date: Tue, April 19, 2022 6:09 am
To: MicrosoftDocs/microsoft-365-docs
***@***.***>
Cc: dilipdivgi ***@***.***>,  Author
***@***.***>

 Where did giu5 downloaded that pdf, where is the link in this article —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by yogkumgit** [comment]
@BrendaCarter Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. This appears to be an issue with our PDF build system. The engineering team has been notified and are working on resolving the issue. I'll update and close this issue when that happens. -Kelley

**Comment by dilipdivgi** [comment]
Great, glad to help out


-------- Original Message --------
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Missing pages in PDF
document (Issue #8337)
From: Kelley Vice ***@***.***>
Date: Fri, May 20, 2022 3:05 pm
To: MicrosoftDocs/microsoft-365-docs
***@***.***>
Cc: dilipdivgi ***@***.***>,  Mention
***@***.***>

 Thanks for reaching out. This appears to be an issue with our PDF build system. The engineering team has been notified and are working on resolving the issue. I'll update and close this issue when that happens. -Kelley —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by kelleyvice-msft** [comment]
The content platform engineering team is looking into this now. I'll update and close this ticket when there is a resolution.

**Comment by kelleyvice-msft** [comment]
The content engineering team has been made aware of the problem and is working on a solution. The blank pages are actually generated when there is a contentless node or YAML file in the TOC, so while there are blanks, no content is missing from the PDFs themselves. Closing this issue as it is an engineering issue, not content related. -Kelley
