### ISSUE TITLE
Question: Does recommendation id changes if there is a change in the recommendation name?

### ISSUE THREAD

**Issue by Bhavin789** [MicrosoftDocs/microsoft-365-docs#8338]
### Context: 
We have integrated recommendation API in our product which eventually shows up on our product UI as a set of some other custom controls names (that we are mapping internally)
For example, the 1x1 mapping goes like => recommendation name <> our custom control name

### Problem
Sometimes, the recommendation name changes but semantically means the same thing. This is breaking our internal 1x1 mapping as we now don't find the **exact** recommendation name but it does exist with slight modification in the vocabulary.

### Question
Not sure if this is the right place, but still want to confirm:
1.  Does the recommendation Id of the recommendation remains the same even if there are vocab changes?
2. Are the changes documented somewhere so that we can refer to what changes are brought upon and we can change our content mapping internally? 

Let me know if any more info is required from my end. Thanks!

**Comment by yogkumgit** [comment]
@Bhavin789 Here, we are limited to documentation fixes and improvements. Considering the nature of the issue, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
