### ISSUE TITLE
No mention that windows defender is weaker offline

### ISSUE THREAD

**Issue by nokite** [MicrosoftDocs/microsoft-365-docs#8339]
According to independent tests, windows defender has a much higher detection rate when online. For whatever reason. I think it would be fair to mention this here.

**Comment by msbemba** [comment]
@nokite Thank you for your feedback. Could you please provide us with the URL of the document that you are referring to?

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  There has been no response to this issue. This can be closed.

**Comment by nokite** [comment]
Closing this ticket shows that your ream does not care about this, and assigns the responsibility of following up to me. 

Who am I? Nobody really. I don't have a stake at Defender, and also no responsibility for it.
I just sent feedback and hoped someone would care to pick it up

Check this out:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/2574061/165699022-d5b07b4b-efb3-4b39-8c5c-7fe10322a9ef.png">

**Comment by nokite** [comment]
And this is not a "question", it's criticism.

**Comment by msbemba** [comment]
@nokite Thank you for your response. Sorry about the confusion. We handle modifications to Microsoft docs and Would like to understand which document needs to be fixed here. If you are requesting a new document (to fix missing information) or have general feedback, you can provide feedback to Microsoft via the main feedback portal - https://feedbackportal.microsoft.com/

Hope this helps and sorry for the confusion.

Thanks
Sri

**Comment by nokite** [comment]
@msbemba I see. Sorry for the confusion as well. 
I opened this issue via some button on your site and wrongly assumed that the article would be linked to the issue automatically.

I don't remember which page I was on, so I'll have to guess it was one of these, or similar:

https://support.microsoft.com/en-us/windows/help-protect-my-pc-with-microsoft-defender-offline-9306d528-64bf-4668-5b80-ff533f183d6c

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-offline?view=o365-worldwide
