### ISSUE TITLE
There's a limit of 10 IPs. What if the Phishing Simulation 3rd party vendor gives you more than 10 unique IPs to whitelist?

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/microsoft-365-docs#8343]
What should we do if we have more than 10 IPs? Can we raise it to 20 please? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17ce75e-79ba-0acd-066c-a0120a29d65d
* Version Independent ID: 14673b1c-8489-0abc-90a0-42f35d516424
* Content: [Configure the delivery of third-party phishing simulations to users and unfiltered messages to SecOps mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-advanced-delivery?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-advanced-delivery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-advanced-delivery.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@netaneladar, you should open a support ticket.

**Comment by yogkumgit** [comment]
@netaneladar Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
