### ISSUE TITLE
An added section telling how to generate the Email Apps Usage Report via Powershell?

### ISSUE THREAD

**Issue by NoahsMyBro** [MicrosoftDocs/microsoft-365-docs#8345]
I'm looking for a way to generate the Email apps usage report, showing all users and the apps they are using to access Office 365 email, ideally for all tenants.

So I need a way to request the report using Powershell.

Would be great if the page can have a note indicating how to generate the report from Powershell.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70e9c6c-8b88-9be4-5ce7-90338685ce95
* Version Independent ID: 755db873-a694-b50c-9478-eeb979dcf4cc
* Content: [Microsoft 365 admin center email apps usage reports - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/email-apps-usage-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/email-apps-usage-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/email-apps-usage-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@NoahsMyBro Thank you for your feedback. I understand your requirement of getting this information via Powershell. However, this document pertains only to Microsoft 365 Reports in the admin center. I'm not able to find another document that talks about getting this information via Powershell. I'd recommend you check with the support team to see if it is possible to get the Email apps usage report via Powershell.  They will be able to help you out with the document or information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @NoahsMyBro Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
