### ISSUE TITLE
Instructions are incorrect and point to options that don't exist

### ISSUE THREAD

**Issue by DMac-hmc** [MicrosoftDocs/microsoft-365-docs#8347]
Here's what you say to do:

In the admin center, go to Show all > Settings > Org settings and on the [Services tab](https://go.microsoft.com/fwlink/p/?linkid=2053743), select Microsoft 365 Groups.

There is no option for Microsoft 365 Groups. 

It does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5592e2-3fee-9034-5b33-2d1687d60ba2
* Version Independent ID: 5b8dee58-e383-9a26-570a-47f5c81121cb
* Content: [Manage guest access in Microsoft 365 groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/manage-guest-access-in-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/manage-guest-access-in-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/manage-guest-access-in-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@DMac-hmc Thank you for your feedback. I'm able to locate these options in two different tenants. 

![image](https://user-images.githubusercontent.com/45987684/165024877-430d8dc4-566d-4955-96d3-3d21b1c29402.png)


I'd recommend you contact the support team via the need help section on the admin center, so that can fix the issue on your admin center/tenant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @DMac-hmc Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by DMac-hmc** [comment]
Thanks.

I see it now, so the most likely explanation is that I was in a hurry and was looking past an option that existed.
