### ISSUE TITLE
Not able to see the images in the document and permission required to view the reports is missing. What permission is required to view firewall reports?

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#8350]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 060dad54-ac01-918a-f684-36464edf54c2
* Version Independent ID: f1a524a3-96a8-e112-3b83-adc9bb8af38f
* Content: [Host firewall reporting in Microsoft Defender for Endpoint](https://review.docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/host-firewall-reporting?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/host-firewall-reporting.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/host-firewall-reporting.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@PremMS-MDE Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8444

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  I can confirm that the images are rendered correctly after the PR merge. The issue can be closed.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PremMS-MDE Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
