### ISSUE TITLE
Global Administrator and Exchange Administrator Required for Privilege Access Approval

### ISSUE THREAD

**Issue by cworkmani21** [MicrosoftDocs/microsoft-365-docs#8354]
Hello,

After configuring admin roles in the Office 365 User Panel I found that both Global and Exchange Administrator Roles are necessary for privileged access approval. Please update the documentation to reflect this.

Thank you
Channing Workman

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf17bfc-f4df-b361-3017-0dc2e7e27efd
* Version Independent ID: be99d36e-1669-7d6f-b6d3-85133a98c879
* Content: [Learn about privileged access management - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/privileged-access-management-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/privileged-access-management-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@cworkmani21 Thank you for your feedback. You only need the Exchange Role Management role assigned to accounts that manage privileged access in Office 365. By default Global admin and exchange admin role includes this role by default and can manage privileged access. We have added this information to the document via  FAQ -https://docs.microsoft.com/en-us/microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide#do-i-need-to-be-a-global-admin-to-manage-privileged-access-in-office-365

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cworkmani21 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
