### ISSUE TITLE
X-plat options Linux,MAC,Android,IOS? 

### ISSUE THREAD

**Issue by bledMS82** [MicrosoftDocs/microsoft-365-docs#8356]
Options listed do not specify what options are available for all the OS's that MDE supports such as Linux,MAC,Android,IOS for offline/air gaped environments. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e829295-8a2c-aa1a-fed6-aca12f734931
* Version Independent ID: b3d2287e-d0fc-bfd8-54f7-4ead4c3633b2
* Content: [Onboard devices without Internet access to Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-offline-machines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-offline-machines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-offline-machines.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@bledMS82 Thank you for your feedback. We have added a note to the document stating that "The following steps are only applicable to devices running previous versions of Windows using the MMA-based solution".

Once it is available for other OS, the document will be updated.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @bledMS82 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
