### ISSUE TITLE
Content didn't meet what email support said it would

### ISSUE THREAD

**Issue by WRMussatto** [MicrosoftDocs/microsoft-365-docs#8357]
From: "Hotmail Sender Support" <[WINLV.EDFS.WW.00.EN.CVG.BGL.TS.T03.ESC.00.EM@css.one.microsoft.com](mailto:WINLV.EDFS.WW.00.EN.CVG.BGL.TS.T03.ESC.00.EM@css.one.microsoft.com?to=%22Hotmail%20Sender%20Support%22%20%3cWINLV.EDFS.WW.00.EN.CVG.BGL.TS.T03.ESC.00.EM@css.one.microsoft.com%3e)>
Recommended I go to This page to report an error with sending to Office 365 email customer.  It focuses on how a Office 386 customer can behave.  not on "we recommend you open a ticket with the Office 365 support team to assist you with the problem".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Version Independent ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Content: [Get support - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-support.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@WRMussatto Thank you for your feedback. You are correct. This document focuses on how an Office365 customer can report a problem and get support from Microsoft. I suggest you to try and get support via https://support.serviceshub.microsoft.com/supportforbusiness

You may need to create a Microsoft account (Free or paid) to be able to raise a support ticket.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @WRMussatto Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
