### ISSUE TITLE
Disabling or deleting retention policies with preservation lock

### ISSUE THREAD

**Issue by swift6** [MicrosoftDocs/microsoft-365-docs#8359]
[Enter feedback here]
"Administrators won't be able to disable or delete these policies after the preservation lock is applied."

This in my opinion is not a good design. If Administrators are not able to disable or delete these policies, then who can?
Can Microsoft disable or remove these retention policies? Who can be contacted to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3246d6-760b-89a2-01ae-835474c3105d
* Version Independent ID: cf6514fc-ec5a-188b-c5a0-0be947379be4
* Content: [Use Preservation Lock to restrict changes to retention policies - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-preservation-lock?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-preservation-lock.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-preservation-lock.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
If Preservation Lock isn't suitable for your organization, then don't use it - it's an entirely optional feature that's designed to meet the requirements of strict regulations, such as SEC 17a-4(f). It's purposely configurable only by PowerShell so admins can't accidentally enable it in the UI.  Kudos for reading and understanding the implications!
