### ISSUE TITLE
View File in Explorer

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#8363]
Hello,

Somehow in the article cannot find if using new EDGE the option "View File in Explorer" is being audited for file operation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by yogkumgit** [comment]
@markjjo Please help us in resolving this issue. thanks

**Comment by lightupdifire** [comment]
@yogkumgit @markjjo 
Thanks for the action! I have verified with MS Support, and they confirm no audit applies when View File in Explorer is used. So I would recommend updating the doc.

**Comment by yogkumgit** [comment]
@markjjo Please reply. Thanks

**Comment by yogkumgit** [comment]
@lightupdifire Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
