### ISSUE TITLE
Edit MDE URLs - Microsoft Support

### ISSUE THREAD

**Issue by adelaldabbas** [MicrosoftDocs/microsoft-365-docs#8364]
Hello team, this is Adel from Microsoft Support.

Please edit the Commercial URLs sheet to include the following for **Linux**:
•	go.microsoft.com
•	definitionupdates.microsoft.com

These are needed for engine V2 signature updates when behavior monitoring is enabled.
We're getting a lot of cases regarding this.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@adelaldabbas Thank you for your feedback. The Sheet is hosted in a different site, I will be working with the author to add the URL's to the sheet.

Thanks
Sri

**Comment by yogkumgit** [comment]
@mjcaparas Please help. Email sent. Thanks

**Comment by adelaldabbas** [comment]
Hello @msbemba ,
Just checking the status here, are you planning to implement the change?

Thank you,
Adel

**Comment by mjcaparas** [comment]
This has been added row 76 & 77 in the MDE URLs tab
