### ISSUE TITLE
eDiscovery Manager role also having admin role of Azure AD.

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/microsoft-365-docs#8365]
[Enter feedback here]

---
#### Document Details 

One of our customer is trying to assign an eDiscovery Manager role to a user so he can performs some functions as part of his Privacy and Data Protection role. They have allocated a test user to be an eDiscovery Manager, and the test user can now see and administer Azure Active Directory. This seems very odd to them, so would like some advice/guidance on why this is the case and how to stop or manage these extra permissions.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94e0469-2c5c-2063-8c3e-7722ceb53577
* Version Independent ID: e99eb8aa-b3b7-8791-aba4-998e209694b5
* Content: [Assign eDiscovery permissions in the Microsoft Purview compliance portal - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/assign-ediscovery-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/assign-ediscovery-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by msbemba** [comment]
@Balamurugan-dot Thank you for your feedback. I was able to test and I could not access anything apart from cases that I create or use eDiscovery search tools to search content locations. There are chances that there could be other permissions or roles assigned to this user. I'd recommend you contacting Microsoft support via the need help option on the admin center to have a Microsoft support engineer fix this issue.

Hope this helps!

Thanks
Sri

**Comment by Balamurugan-dot** [comment]
> @Balamurugan-dot Thank you for your feedback. I was able to test and I could not access anything apart from cases that I create or use eDiscovery search tools to search content locations. There are chances that there could be other permissions or roles assigned to this user. I'd recommend you contacting Microsoft support via the need help option on the admin center to have a Microsoft support engineer fix this issue.
> 
> Hope this helps!
> 
> Thanks Sri

Thank you very much Sri, for the inputs.
