### ISSUE TITLE
Step 1 Incorrect

### ISSUE THREAD

**Issue by PayneCeeva** [MicrosoftDocs/microsoft-365-docs#8367]
Step 1 contains the following sub-steps: 
"1. Go to https://compliance.microsoft.com/ and sign in using the credentials for an administrator account in your organization."
"2. In the left pane of the compliance portal, click Information governance > Import."

The feature was moved to Security and Compliance, Data Lifecycle Management, Import. It was then moved back to Compliance, Data Lifecycle Management, Import, although the previous location still contains a link to it. The documentation, updated as of yesterday, does not contain this change.

Really, you'd need someone monitoring the website's design and updating the documentation in realtime to keep up with the arbitrary changes being made in Office Online. It might be a good idea to consolidate the design more intuitively and just leave it alone for at least one week.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import PST files - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#step-1-copy-the-sas-url-and-download-azcopy)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by cabailey** [comment]
@PayneCeeva   Yes, when they changed the name of "Information governance" to "Data lifecycle management" there was a lot of documentation to change!  We did our best to scoop up all the references but inevitably some will be missed, some will take a bit longer, and some might be accidentally overwritten - so we appreciate your patience. This one is now fixed.

In case you missed it, this renaming is addressed in the Note at the top of the article:

Microsoft 365 compliance is now called Microsoft Purview and the solutions within the compliance area have been rebranded. For more information about Microsoft Purview, see the blog announcement (https://aka.ms/microsoftpurviewblog).

To help you keep up with changes in this fast-paced technology space, keep an eye on "What's new in Microsoft Purview" (https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new) - the entry for April has a concise list of name changes.

**Comment by PayneCeeva** [comment]
Any predictions on when the name Purview will be replaced with a different unrelated word? Or when the resources the site contains will be moved to another set of websites? I just want to keep on top of these fast-paced technology changes. Moving several email specific features out of the email server application into a reporting application was a “bold” move that I know I wouldn’t have made. It’s interesting how far various feature are from their relevant applications in the new Purview.
Nothing personal, I know you’re not the one making these changes, I’m just not a fan of using innocent marketing reps to whitewash poor design decisions.

George Payne
Ceeva, Inc. | Technical Support Specialist
***@***.******@***.***> | office - 412-690-2300 x336

[facebook2]<http://www.facebook.com/ceevainc>[twitter2]<http://twitter.com/ceevainc> [linkedin2] <http://www.linkedin.com/company/ceeva>
 www.ceeva.com<http://www.ceeva.com/>

***@***.***

This message (including any attachments and/or related materials) is confidential to, copyrighted by, and is the property of Ceeva unless otherwise noted. If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.

**Comment by cabailey** [comment]
@PayneCeeva  For your feedback about the changes to get to the right people, you can use the "This product" button in the Feedback section.  GitHub Issues that get generated when you select "This page" are designed for documentation changes that are now addressed, so closing this issue.  Feel free to open another issue for any other missed references you come across and once again, we appreciate your patience while we also adjust to this change.
