### ISSUE TITLE
The link on the page is broken

### ISSUE THREAD

**Issue by v-sashig** [MicrosoftDocs/microsoft-365-docs#8370]
https://docs.microsoft.com/en-us/security/defender-endpoint/non-windows
the above link in the below section on the page is broken, gets a 404 error.

-----------------------------
Important

The capabilities on non-Windows platforms may be different from the ones for Windows. For more information on what capabilities are available for non-Windows platforms, see [Microsoft Defender for Endpoint for non-Windows platforms](https://docs.microsoft.com/en-us/security/defender-endpoint/non-windows).
----------------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8690a332-f672-8db8-1552-5ee16e78746f
* Version Independent ID: 3df5b553-4e29-da25-c0e4-10686c5fed20
* Content: [Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @v-sashig Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
