### ISSUE TITLE
Grammar correction

### ISSUE THREAD

**Issue by Russel-Thomas** [MicrosoftDocs/microsoft-365-docs#8374]
Grammar correction:
In this article, we'll walk you through the steps of adding an existing domain **your** already own or buying a new one.
In this article, we'll walk you through the steps of adding an existing domain _**you**_ already own or buying a new one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc903dd4-94b0-1461-d9a4-5b457d5ac3b6
* Version Independent ID: 7a8eff98-2ba7-81f7-2a3d-71bdd7e1994a
* Content: [Set up Microsoft 365 Business Standard with a new or existing domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/setup-business-standard?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/setup-business-standard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/setup-business-standard.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by RAJU2529** [comment]
@Russel-Thomas , Thanks for pointout.

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @Russel-Thomas Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by Russel-Thomas** [comment]
Always a pleasure, thanks for the quality response everyone 👍
