### ISSUE TITLE
Contradicting information re: Exclusions in EDR Block Mode

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#8375]
In a section marked "Important" this page states

_Microsoft Defender Antivirus exclusions don't apply to other Microsoft Defender for Endpoint capabilities, including [**endpoint detection and response (EDR)**](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/overview-endpoint-detection-response), [attack surface reduction (ASR) rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction), and [controlled folder access](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders)._

However, on this page - https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/edr-in-block-mode?view=o365-worldwide#requirements-for-edr-in-block-mode. 

In a section marked "Important" it is stated that "EDR in block mode respects exclusions that are defined for Microsoft Defender Antivirus"

These 2 pages appear to directly contradict one another? Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87906607-83fd-8dc8-facb-89719390f824
* Version Independent ID: 92f3359d-84ac-90c3-33d5-513feffc4173
* Content: [Configure and validate exclusions based on extension, name, or location](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please update. Thanks

**Comment by denisebmsft** [comment]
Hello @pjrcdf and @yogkumgit. Thank you for the feedback. Microsoft Defender Antivirus exclusions are respected in EDR in block mode, but not across other protection capabilities in Defender for Endpoint (such as attack surface reduction rules and controlled folder access). I have updated the article and the changes should be live later today. Thank you for helping us improve our documentation.

https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/14260
