### ISSUE TITLE
Step 10, missing info

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/microsoft-365-docs#8376]
For Step 10, "The user will now be able to access the former employee's OneDrive using the OneDrive URL"
Where do we find this URL to provide to a user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34c90550-34c3-c6de-81d4-6d85a8bc3f90
* Version Independent ID: 151fb754-7bea-f489-5115-e3551db0f303
* Content: [Step 5 - Give another employee access to OneDrive and Outlook data - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-5?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee-step-5.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee-step-5.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@mntorq Thank you for your feedback. The URL of the user can be found in the one drive usage report or the URL for a user's OneDrive is usually in the following format: https://<tenant name>-my.sharepoint.com/personal/<user principal name>.  I have added information about this to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8404

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mntorq Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
