### ISSUE TITLE
WARNING: Breaking changes in the cmdlet 'New-AzVirtualNetworkSubnetConfig'

### ISSUE THREAD

**Issue by peterennis** [MicrosoftDocs/microsoft-365-docs#838]
Ref: https://github.com/MicrosoftDocs/microsoft-365-docs/issues/837

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6989d21-f7a7-043b-c91a-cd019a19c0e6
* Version Independent ID: 39e286bc-58fe-768e-ee65-2a2fedf1e544
* Content: [Simulated enterprise base configuration for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise?source=docs#feedback)
* Content Source: [microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@peterennis This has been answered in customer issue 837. Thanks.
