### ISSUE TITLE
Unable to add members when searching by last name

### ISSUE THREAD

**Issue by omegagx** [MicrosoftDocs/microsoft-365-docs#8380]
when following these steps https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-configure?view=o365-worldwide#add-users-to-an-insider-risk-management-role-group under step 5 I am unable to search for users by last name. I have to type the first name and searching just by last name when trying to add members produces no results. Documentation should mention that as only 50 users show up by default

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb98e0ff-d34c-75bc-0ade-7dc70fc7f4bd
* Version Independent ID: 5172471f-e514-bcde-16e0-d8d8090a892a
* Content: [Get started with insider risk management - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-configure?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-configure.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@omegagx Thank you for your feedback. I was able to test with the last name and it works

![image](https://user-images.githubusercontent.com/45987684/165033875-a74c25ad-78a0-4d92-9e50-108c1a049a0a.png)

If this issue continues, please click on need help on your admin center and report this issue to the Microsoft support team, so that one of the engineers can work with you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @omegagx Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by omegagx** [comment]
I opened case 30771406 and the support engineer Abayomi Fowe confirmed that we can't search by last name. Additionally, I just tried it again and I couldn't look up by last name as the screenshot shows and when using the full name, it worked.


![image](https://user-images.githubusercontent.com/19207488/165159924-4a74e11e-956d-4fed-bc57-e95ae2cc0a6a.png)


![image](https://user-images.githubusercontent.com/19207488/165159994-ea5a7e8c-fd2c-426b-ac05-d0366bc47263.png)

**Comment by omegagx** [comment]
@yogkumgit - please re-open

**Comment by msbemba** [comment]
@omegagx I can confirm that it is working when you search by the last name. I have three different screenshots below that shows it works. Sorry that you are having to go back and forth with support. You can share this information with the support and let them know it works for other tenants.

![image](https://user-images.githubusercontent.com/45987684/165804700-b588035e-4c9f-44dd-ab6c-d4cbd566d61c.png)

![image](https://user-images.githubusercontent.com/45987684/165804723-6626fbb8-031e-406b-9106-a1ebe37979fd.png)


![image](https://user-images.githubusercontent.com/45987684/165804829-35423deb-4705-4a01-a317-eaa23caf4867.png)

Hope this helps!

Thanks
Sri
