### ISSUE TITLE
The <Manage automated testing settings> has changed, docs need update

### ISSUE THREAD

**Issue by fvhemert** [MicrosoftDocs/microsoft-365-docs#8386]
The <Manage automated testing settings> has changed, for example the menu option "Select Automated testing from the left navigation." is no longer available and been replaced by "Testing source"

Please update to align with new menu structure, 

Francois
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f424cd-302d-5845-34fb-7b906bf7970c
* Version Independent ID: cfa50ebe-7ef1-de51-4456-a1212be9e7ec
* Content: [Get started with Microsoft Purview Compliance Manager - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-setup?view=o365-worldwide#set-up-automated-testing)
* Content Source: [microsoft-365/compliance/compliance-manager-setup.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-setup.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by chvukosw** [comment]
Thanks, this will be corrected today.
