### ISSUE TITLE
Unable to change settings 

### ISSUE THREAD

**Issue by dbrewer89** [MicrosoftDocs/microsoft-365-docs#8389]
[Enter feedback here]
Following the directions in the MS Doc page I get the below msg and changes are not saved.
You must use ‎Microsoft Edge‎ version 87.0 or newer to change settings for the ‎Microsoft Edge‎ new tab page.

MS Edge version installed is: Version 100.0.1185.36 (Official build) (64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92701183-1413-9e14-3109-53c2debe7d8b
* Version Independent ID: c1b54dbd-ac96-4582-b577-f09e8beba365
* Content: [Manage Industry news - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-industry-news?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-industry-news.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-industry-news.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@dbrewer89 Thank you for your feedback. I was able to test and save. This looks like a bug with the particular version or may be with your browser. I'd recommend you contact Microsoft support via the need help section so that a support engineer will be able to help you or file a bug to escalate it to the product group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @dbrewer89 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
