### ISSUE TITLE
For users appears outdated?

### ISSUE THREAD

**Issue by Jens-Lorenz** [MicrosoftDocs/microsoft-365-docs#839]
The settings &gt; options &gt; Block or allow does not exit any longer? On the Settings page, you have to navigate to View all Outlook settings and then to Junk mail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbab747e-1a43-037e-09ca-9c402deec602
* Version Independent ID: 1c6d8e28-034d-24d6-5732-b96475411d6b
* Content: [How to prevent false positives from happening in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/prevent-email-from-being-marked-as-spam#feedback)
* Content Source: [microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Jens-Lorenz, confirmed, but I don't really see why those steps/locations need to be repeated in this topic, when there's are perfectly good Outlook and Outlook on the web topics on support.office.com that talks all about it:

- https://support.office.com/article/5ae3ea8e-cf41-4fa0-b02a-3b96e21de089

- https://support.office.com/article/db786e79-54e2-40cc-904f-d89d57b7f41d

So I removed instructions and screenshot and linked to the 'one source of truth' topics for ease of future maintenance.

I also took the liberty of moving the topic out of the 'compliance' folder into the more appropriate 'security/office-365-security' folder, including link redirection.

Thanks for the feedback.
