### ISSUE TITLE
Calendar & Contacts instructions are unclear

### ISSUE THREAD

**Issue by Jaymoon85** [MicrosoftDocs/microsoft-365-docs#8392]
The final step says:

> You can repeat this for calendar items and contacts as well.

So...  How? What in this instruction page was specific to just email, if all 3 APIs are enabled in the Google Admin Console?

By following the instruction page from top to bottom, does this include migrating calendar and contacts? Or are those two separate actions I have to "repeat" later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd31a7b-580e-dc50-ed21-f1513cc44d09
* Version Independent ID: 3bd31a7b-580e-dc50-ed21-f1513cc44d09
* Content: [Migrate business email and calendar from Google Workspace - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/moveto-microsoft-365/migrate-email?view=o365-worldwide)
* Content Source: [microsoft-365/admin/moveto-microsoft-365/migrate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/moveto-microsoft-365/migrate-email.md)
* Service: **o365-administration**
* GitHub Login: @twernermsft
* Microsoft Alias: **twerner**

**Comment by msbemba** [comment]
@Jaymoon85 Thank you for your feedback. The last step is only about verification. So you can repeat the verification process to check if the calendar and contacts were successfully migrated.

When you follow the instructions on this page, it migrates emails, contacts, and calendar items.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Jaymoon85 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
