### ISSUE TITLE
Retention labels applied on Microsoft 365 Group

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/microsoft-365-docs#8393]
This is now working in OWA - documentation may be updated to reflect this. No ETA for outlook at this time.
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-apply-retention-labels?view=o365-worldwide#applying-retention-labels-using-microsoft-365-groups
![image](https://user-images.githubusercontent.com/47151300/164770172-37bb66c1-8811-4d2e-86d3-f179bbf3c619.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b974f07-d9f4-38c6-39ac-5d53aeda45fc
* Version Independent ID: fab281b5-1ff8-6e71-1756-c0579770f523
* Content: [Publish and apply retention labels - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-apply-retention-labels?view=o365-worldwide#applying-retention-labels-using-microsoft-365-groups)
* Content Source: [microsoft-365/compliance/create-apply-retention-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-apply-retention-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@asdcristi If you're a Microsoft employee, please contact me internally.

**Comment by cabailey** [comment]
Closing - continuing this discussion internally.  A report of a feature working is not the same as supported.  When retention label support for Microsoft 365 Groups using OWA is approved by engineering stakeholders, I'll update the documentation to match.
