### ISSUE TITLE
no more battery optimization in xiaomi MIUI 13

### ISSUE THREAD

**Issue by XiaoliangHuang** [MicrosoftDocs/microsoft-365-docs#8398]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3c4a1d-a030-0d30-cce5-d12337fcfdd4
* Version Independent ID: dca55864-acee-0617-218a-efd08eae46eb
* Content: [Troubleshoot issues on Microsoft Defender for Endpoint on Android](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/android-support-signin?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/android-support-signin.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/android-support-signin.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@XiaoliangHuang Thank you for your feedback. This issue occurs only on Android 11 as Xiaomi changed the battery optimization permissions in Android 11. If you still have the same issue on Xiaomi MIUI 13 I'd recommend raising a bug with the product group to resolve the issue.

The document is updated with the information stating it applies to Xiaomi with Android 11

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @XiaoliangHuang Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
