### ISSUE TITLE
A sample file no longer available for download?

### ISSUE THREAD

**Issue by Runs-info** [MicrosoftDocs/microsoft-365-docs#8402]
[Enter feedback here]
This page states that you can download the Demo file from aka.ms/ioavtest.
However, when I actually try to download it, it returns a 403 error. This has been happening for the last week.
Is the test file download site already closed? If so, please update the Docs to include an annotation stating that it cannot be downloaded.
Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1575e3-b233-ffd2-95c1-fd34fd242651
* Version Independent ID: 02b44885-5bff-1580-0974-f9050bee639c
* Content: [Configure and validate Microsoft Defender Antivirus network connections](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus?view=o365-worldwide#attempt-to-download-a-fake-malware-file-from-microsoft)
* Content Source: [microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@Runs-info Thank you for your feedback. I was able to reproduce the issue. I'm correctly working with the author and will fix this shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@denisebmsft Email sent, please reply. Thanks

**Comment by denisebmsft** [comment]
Greetings @Runs-info @yogkumgit. Our product team is working on this issue. I don't know when it will be resolved but it should be soon.
