### ISSUE TITLE
Potentially incorrect wording

### ISSUE THREAD

**Issue by blue-ken** [MicrosoftDocs/microsoft-365-docs#8405]
I think it should be made clear in the below wording that your can search for Teams chat messages if the users mailbox is on-premise.

"In an Exchange hybrid deployment, you can't use the Content search tool to search on-premises mailboxes. You can only use the tool to search cloud-based mailboxes."

see here

https://docs.microsoft.com/en-us/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e514aa-9f04-5cc9-93f6-9f5f2f614c2a
* Version Independent ID: dea1ab15-bc09-05c1-b48b-1a06c0b53b50
* Content: [Create and run a Content search in the Microsoft Purview compliance portal - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/content-search.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/content-search.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@blue-ken Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8483

once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @blue-ken Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
