### ISSUE TITLE
file size limit for "fileinfo" in MDE Live Response: 10GB or 30GB?

### ISSUE THREAD

**Issue by mcteufelms** [MicrosoftDocs/microsoft-365-docs#8406]
There are two different infos mentioned for MDE Live Response limitations on "file info": one line on the page mentions 30GB size limit, another line on the page mentions 10GB file size limit for file info:

![image](https://user-images.githubusercontent.com/89206976/165072257-d6319933-331e-41e1-aefb-15a2a68d4613.png)
![image](https://user-images.githubusercontent.com/89206976/165072331-3996ef30-81dd-45e8-a918-3757da42ddb4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b2a4c2-e698-dda0-9919-80ca2d05b358
* Version Independent ID: 19b5f609-fcaa-cb5b-96b7-462285fd32e7
* Content: [Investigate entities on devices using live response in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/live-response.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/live-response.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@mcteufelms Thank you for your feedback. The document has been updated to reflect the correct information now.

The fileinfo limit is 30 GB. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mcteufelms Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
