### ISSUE TITLE
MDATP - Privacy Preferences Policy Control won't work

### ISSUE THREAD

**Issue by ThreshTheRed** [MicrosoftDocs/microsoft-365-docs#8407]
Hey

We're in the process of testing MDATP across Apple Devices - Macs.
We follow an instruction from this page https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-sysext-policies?view=o365-worldwide

Previously, we did everything in MacOS jamf pro onboarding, step by step, but since it was just a short test I have no info about that.

Everything works fine, until one point - SystemExtensions. I know that Microsoft switched from Kernel Extensions to System Extensions. 

While approving *sext files works like a charm, granting **SystemPolicyAllFiles** privileges for Defender are not. 
I have to manually accept them in Security & Privacy.
Config is basically the same as in mentioned link.
We're deploying it via JamfPro.

I tried to find some info regarding that on JamfPro boards, but it seems that I am not the only one who's struggling with that.

Anybody has a solution or at least workaround for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62153cfc-2083-0d5c-2eb6-f5ae6c2af0b5
* Version Independent ID: d8da0e93-a3c3-82fc-0bce-f24d09db9635
* Content: [New configuration profiles for macOS Catalina and newer versions of macOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-sysext-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-sysext-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-sysext-policies.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ThreshTheRed Thank you for your feedback. This sounds more like a technical issue or a bug. I'd recommend you contact Microsoft support via the need help section on the admin center to get this resolved or escalated to the product group(in case this is a bug or a known issue).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ThreshTheRed Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
