### ISSUE TITLE
Person creating Trainable Classifier needs to be member of seed SharePoint Site.

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/microsoft-365-docs#8411]
Please can you add prerequisite / tip to advise that the admin creating a new custom trainable classifier needs to be listed as a **member** of the seed SharePoint site otherwise the site with the seed content does not get listed in the **Choose sites** flyout list.

Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3c5c98-9f47-9512-b932-2f72822796d2
* Version Independent ID: fd477cf9-4ee0-544f-10c6-f3dfccb10186
* Content: [Get started with trainable classifiers - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-get-started-with?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/classifier-get-started-with.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-get-started-with.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@quickclix75 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
