### ISSUE TITLE
Add Documentation Or Link to Documentation for Onboarding Via Arc

### ISSUE THREAD

**Issue by Wittkie** [MicrosoftDocs/microsoft-365-docs#8413]
Can the Microsoft Defender for Endpoint deployment documentation for Linux be updated to include, or link to the onboarding documentation via Azure Arc?

---
#### Document Details⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.** ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**
Microsoft Defender for Endpoint on Linux
Describes how to install and use Microsoft Defender for Endpoint on Linux.

**Comment by msbemba** [comment]
@Wittkie Thank you for your feedback. We have made changes to the document by adding related articles via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8525

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Wittkie Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
