### ISSUE TITLE
Azure Event Hub Data Receiver should be Azure Event Hubs Data Receiver

### ISSUE THREAD

**Issue by RHooijer** [MicrosoftDocs/microsoft-365-docs#8419]
The role Azure Event Hub Data Receiver should be Azure Event Hub Data Receiver, this is a typo I believe. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1302a36-d75f-2c77-0da1-333f81689805
* Version Independent ID: 8fd7095a-926c-6b12-07b4-0e50094bfba1
* Content: [Configure your Event Hub](https://docs.microsoft.com/en-us/microsoft-365/security/defender/configure-event-hub?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/configure-event-hub.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/configure-event-hub.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@RHooijer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8484

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @RHooijer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
