### ISSUE TITLE
Cant find "Use the Sensitivity feature in Office to apply and view sensitivity labels"

### ISSUE THREAD

**Issue by paisleyborg** [MicrosoftDocs/microsoft-365-docs#8423]
Hi,

This article talks about disabling the AIP add-in to use built-in labeling for Office apps:
https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-aip?view=o365-worldwide#how-to-disable-the-aip-add-in-to-use-built-in-labeling-for-office-apps

We followed this article to enable this feature: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide
- Navigate to User Configuration/Administrative Templates/Microsoft Office 2016/Security Settings.
- Set Use the Sensitivity feature in Office to apply and view sensitivity labels to 1

We can now see the AIP COM Add-in is disabled in MS Word - even though we are using Office 365 (with an E5 license).

However, where on the MS Word ribbon do we now find AIP labels?
Where is this built-in labeling option for Office apps we are supposed to be using now?
Because it looks like when we disable the AIP COM add-in, it also removes AIP from MS Word.

Also, my AIP Policy default is to auto-label every new document as "General" - and this also is no longer working.

Are we meant to enable something AIP related somewhere else?

Thank you
PB

**Comment by yogkumgit** [comment]
@paisleyborg Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by paisleyborg** [comment]
Hi @cabailey 

We are using this version of MS Office (pls see screenshot), which I believe is a supported version of Office? - but still no AIP capability based on this new built-in AIP functionality/client.

Thank you

<img width="410" alt="MSOfficeVersion" src="https://user-images.githubusercontent.com/19217163/167760020-1258b40d-a945-4095-b570-851d1f8673f7.PNG">
