### ISSUE TITLE
No "Applies To"

### ISSUE THREAD

**Issue by sarahmcm** [MicrosoftDocs/microsoft-365-docs#8425]
does not tell us what licenses are needed at a Tenant to be able to apply these settings

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Learn about sensitivity labels - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@sarahmcm  There is no blanket "Applies to" for sensitivity labels - licensing depends on the scenario, so it's a bit more complicated. At the top of this page, and all pages for sensitivity labels, there's a link to the licensing page that has the relevant details and the "Get started with sensitivity labels" page has a section specifically for licensing: https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-sensitivity-labels#subscription-and-licensing-requirements-for-sensitivity-labels

**Comment by sarahmcm** [comment]
great tx - now please go shoot the lawyers who made it so bloody complicated

ngā mihi
Sarah McM

***@***.***<http://www.gtb.co.nz/>
Sarah McMurray
Senior Tech, Director
04 297 1040 ext 704   |   027 697 1040
GTB IT Solutions<http://www.gtb.co.nz/>

Quality Work  |  Care for People  |  Ongoing improvement  | since 1999
Information where you need it, when you need it - safe and secure

Get our ebook ‘Type Macrons Easily – How to install a Māori keyboard’<https://gtb.co.nz/assets/ebooks/Type-Macrons-Easily---How-to-install-a-Maori-Keyboard---GTB.pdf>
Watch our 4 minute video to see how to spot and keep safe from dangerous emails<https://youtu.be/hTAfvuNEPKI>

**Comment by sarahmcm** [comment]
if it is not clear “how to buy” then how are people supposed to buy this service?

cheers

**Comment by cabailey** [comment]
@sarahmcm  I agree the licensing for sensitivity labels isn't simple, which is why an "Applies to" wouldn't work for this page and instead, we link to the relevant information that's owned and maintained by the team who are responsible for this area of the product. For feedback about the licensing itself, I recommend you use GitHub Issues on that licensing page itself or use the "This product" button in the Feedback section.  That way, the relevant people will see it.

Closing this documentation issue.
