### ISSUE TITLE
Use USMTGUI

### ISSUE THREAD

**Issue by samohtrelhe** [MicrosoftDocs/microsoft-365-docs#843]
Use USMT with a GUI and get both documents, desktop and browser bookmarks (Chrome, Firefox, IE) transferred.
USMTGUI even transfers profiles locally from a local/Domain profile, directly to the Azure users profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d6372f-64a9-904f-ff82-b9e1598cefd5
* Version Independent ID: d9815917-22a8-f4fd-5e10-031207d7c30e
* Content: [Step 4 - User Files and Settings Migration](https://docs.microsoft.com/en-us/microsoft-365/enterprise/step-4-user-files-and-settings-migration)
* Content Source: [microsoft-365/enterprise/step-4-user-files-and-settings-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/step-4-user-files-and-settings-migration.md)
* Service: **o365-solutions**
* GitHub Login: @JGruszczyk
* Microsoft Alias: **jogruszc**

**Comment by JGruszczyk** [comment]
thanks for the insight Samohtrelhe, we'll incorporate that into our content updates
