### ISSUE TITLE
string correction

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/microsoft-365-docs#8430]
Link under Overall Workflow reads

see [Process flow for creating **customer** trainable classifiers](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-learn-about?view=o365-worldwide#process-flow-for-creating-custom-classifiers).

should read

see [Process flow for creating **custom** trainable classifiers](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-learn-about?view=o365-worldwide#process-flow-for-creating-custom-classifiers).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3c5c98-9f47-9512-b932-2f72822796d2
* Version Independent ID: fd477cf9-4ee0-544f-10c6-f3dfccb10186
* Content: [Get started with trainable classifiers - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-get-started-with?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/classifier-get-started-with.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-get-started-with.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @quickclix75 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
