### ISSUE TITLE
remove (Preview) in Procedure 3

### ISSUE THREAD

**Issue by andrewn2000** [MicrosoftDocs/microsoft-365-docs#8431]
[Enter feedback here]
OLD
Under Procedure 3: Turn on Endpoint Security Profile settings in Microsoft Endpoint Manager, remove the (Preview) 

UPDATED
Under Endpoint Security Profile Settings, set Allow Microsoft Defender for Endpoint to enforce Endpoint Security Configurations to On

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b2ff80e-a827-c0f8-f488-6824704d8127
* Version Independent ID: 5b2ff80e-a827-c0f8-f488-6824704d8127
* Content: [Microsoft Defender for Business troubleshooting](https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-troubleshooting?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-troubleshooting.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-troubleshooting.yml)
* Product: **m365-security**
* Technology: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @andrewn2000 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
