### ISSUE TITLE
Incorrect table headers

### ISSUE THREAD

**Issue by coproyer** [MicrosoftDocs/microsoft-365-docs#8438]
The first two tables in this document include incorrect headers for the table columns, especially the second column reflecting the content of the prior paragraph rather than describing the content of the table column. The incorrect heading makes the table content difficult to understand for anyone who is not already versed in creating a mail flow rule. The first column header should read "Setting or Option" and the second "Recommended Setting" as is done for the remaining tables on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26120923-cfc5-e6f7-866b-9e5cbcf22363
* Version Independent ID: aaec5592-df91-ee04-9f73-081e69dd34cd
* Content: [Increase threat protection for Microsoft 365 for Business - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/security-and-compliance/increase-threat-protection?view=o365-worldwide#protect-your-email-from-phishing-attacks)
* Content Source: [microsoft-365/admin/security-and-compliance/increase-threat-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/increase-threat-protection.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by denisebmsft** [comment]
Hello @coproyer and thank you so much for your feedback. We have revised the content quite a bit and I think this issue is resolved. Please see the new article: https://docs.microsoft.com/en-US/microsoft-365/business-premium/m365bp-security-overview
