### ISSUE TITLE
When a person in the group replies to a message sent to the shared mailbox, the email appears to be from the shared mailbox, not from the individual user.

### ISSUE THREAD

**Issue by chenxizhang** [MicrosoftDocs/microsoft-365-docs#8440]
Hi there

How can I understand the statement in the document as below?

**"When a person in the group replies to a message sent to the shared mailbox, the email appears to be from the shared mailbox, not from the individual user."**

My experience is when I reply a message sent to one shared mailbox, I still need to choose the shared mailbox from the "From" field, it can't be automated. 

Is that correct or anything I am missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db2dbb29-38c4-afe4-bc0d-3bbc195f6288
* Version Independent ID: bcfee113-ecfe-e358-974e-6f9cd76b8d35
* Content: [Create a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@chenxizhang - That is correct. If you choose the shared mailbox in the "From" field, the email will show as coming from the shared mailbox--not from you.

**Comment by chenxizhang** [comment]
@SKjerland Thanks for the quick response. How can I reply to the email from the shared mailbox account directly instead to need me to select the account manually?

Is that possible?

**Comment by SKjerland** [comment]
@chenxizhang - Shared mailboxes aren't designed for direct logon. There's really no reason why you would need to log in to the shared mailbox directly. Here's another article that provides more info: [Open and use a shared mailbox](https://support.microsoft.com/office/d94a8e9e-21f1-4240-808b-de9c9c088afd)

**Comment by chenxizhang** [comment]
@SKjerland I don't want to logon with shared mailbox. let me describe the scenario here a little bit.

 1. I am a member of a shared mailbox.
 2. when a customer send mail to the shared mailbox, I will also receive the mail in my inbox.
 3. I click the reply button, the default setting of "From" is my personal account, not the shared mailbox account. of course, I can   select it from the list manually.
 4. I am just wondering if there is any way to automatically select the shared mailbox account, when the mail was sent to the shared mailbox, instead to my personal account directly.

is that clear?

😆

**Comment by SKjerland** [comment]
@chenxizhang - Thanks, I understand now. As far as I know, there's no way to automate which account gets populated in the From field. I would expect it to auto-populate with the shared mailbox account if you're replying to an email that was sent to the shared mailbox (and the article I gave you a link to also suggests that should be happening), but it sounds like that's not the case for you. The only thing I can suggest is talking to someone in Support. Sorry I couldn't be more help.
