### ISSUE TITLE
FileMD5 missing

### ISSUE THREAD

**Issue by JuergMeier-CH** [MicrosoftDocs/microsoft-365-docs#8441]
Even from the old day. MD5 is missing on the   List of supported hashes

**Comment by denisebmsft** [comment]
Hello @JuergMeier-CH. Can you please tell us to which article your feedback applies? This information will help us route the issue to the correct writer/team. Thanks!

**Comment by yogkumgit** [comment]
@JuergMeier-CH We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
