### ISSUE TITLE
Ownerless Group management policy

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/microsoft-365-docs#8448]
Creation of policy failed at the first attempt ( and second and third... )

![image](https://user-images.githubusercontent.com/45055386/165858255-7e910827-73c2-466a-beca-4245a014d9de.png)

There's no helpful info about troubleshooting this. I guess this is an issue with the 'product' rather than this page, but clicking that option assumes I have an issue with Admin Centre generally.

Alan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Version Independent ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Content: [Manage ownerless Microsoft 365 groups and teams - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/ownerless-groups-teams?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/ownerless-groups-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/ownerless-groups-teams.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by TobiasAT** [comment]
Same issue here

**Comment by msbemba** [comment]
@alanbmhs Thank you for your feedback. I was able to reproduce the issue as well. However, this needs to be reported to the support/product team via the need help section on the admin center as this feedback section is only for modifying documents.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @alanbmhs Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by TobiasAT** [comment]
Just to note, in my tenant the change was retracted and the option for ownerless group management is no longer available.

**Comment by alanbmhs** [comment]
As per @TobiasAT it appears to have been removed for me too now. In fact if I click on M365 Groups in Org Settings it just throws me out to the main admin page. The last response to my ticket was that the support engineer was checking if this behaviour was by design!

**Comment by VladilenK** [comment]
Hit the same just recently. 
For me it happened to be a permissions issue.
SharePoint admin, Teams admin or Group admin roles: cannot configure Ownerless Groups Policy (but it worked before).
Global admin: yes, can configure Ownerless Microsoft 365 Groups Policy.
What is the minimum role required?

**Comment by TobiasAT** [comment]
@VladilenK I would say at least a Groups Admin role should be able to modify the settings (in theory). But as I still have the configuration failure in multiple tenants (with Global Admin) nothing is a normal expectation.
