### ISSUE TITLE
PAM Roadmap

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/microsoft-365-docs#8449]
This article says :Privileged access management will be available in other Office 365 workloads soon. Visit the [Microsoft 365 Roadmap](https://www.microsoft.com/microsoft-365/roadmap) for more details
When I check roadmap - there is nothing related to PAM for other O365 workloads.....One of my customers is asking about roadmap details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf17bfc-f4df-b361-3017-0dc2e7e27efd
* Version Independent ID: be99d36e-1669-7d6f-b6d3-85133a98c879
* Content: [Learn about privileged access management - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/privileged-access-management-overview?view=o365-worldwide#frequently-asked-questions)
* Content Source: [microsoft-365/compliance/privileged-access-management-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/privileged-access-management-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@bubhat Thank you for your feedback. I could not find the details in the roadmap either. If you'd like to get more information on this from the product/dev team you can leave feedback on our main feedback portal -https://feedbackportal.microsoft.com/ and one of our product/dev team members will be able to provide you an update or exact dates if they are available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@bubhat  Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
