### ISSUE TITLE
Poor and small picture quality

### ISSUE THREAD

**Issue by kjulson** [MicrosoftDocs/microsoft-365-docs#845]
If you are going to use screenshots, make sure the screenshots are of good enough quality and size to read. Even zooming in to 150% they are very pixelated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in#get-and-enable-the-report-message-add-in-for-your-organization)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kjulson** [comment]
If you want smaller footprint, use thumbnails that you can click to expand a larger image.

**Comment by mypil** [comment]
@kjulson - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/c615aad61f52508c36a5f8bca17d16135bb00b85. 


Thank you for your contribution to make the docs better! Much appreciated!
