### ISSUE TITLE
Link wrong

### ISSUE THREAD

**Issue by Daiannec** [MicrosoftDocs/microsoft-365-docs#8450]
The link is wrong.

Ways to manage MFA settings
There are two ways to manage MFA settings.

In the Azure portal, you can:

Enable and disable security defaults
Configure Conditional Access policies
In the Microsoft 365 admin center, you can configure per-user and service **[MFA settings](https://go.microsoft.com/fwlink/p/?linkid=2169174).**
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4afb65e6-0570-8699-a725-e7f45d1da009
* Version Independent ID: 39ba6f37-5d4a-3166-4ef9-f0a3c7a52355
* Content: [Multifactor authentication for Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/multi-factor-authentication-microsoft-365?view=o365-worldwide)
* Content Source: [microsoft-365/admin/security-and-compliance/multi-factor-authentication-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/security-and-compliance/multi-factor-authentication-microsoft-365.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Daiannec Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8485

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Daiannec Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
