### ISSUE TITLE
Outdated CSP reference

### ISSUE THREAD

**Issue by danielfawcett1** [MicrosoftDocs/microsoft-365-docs#8454]
Under "Use MDM CSPs to allow specific apps" there is a reference to [./Vendor/MSFT/Policy/Config/Defender/GuardedFoldersAllowedApplications](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-guardedfoldersallowedapplications).

I believe that this should be updated to reference [./Vendor/MSFT/Policy/Config/Defender/ControlledFolderAccessAllowedApplications](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-defender#defender-controlledfolderaccessallowedapplications)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 696edac6-9f06-ca79-5969-ef1e30ad0817
* Version Independent ID: a5a5fad9-5fbb-014a-f628-610fdbfe1ddf
* Content: [Customize controlled folder access](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/customize-controlled-folders?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/customize-controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/customize-controlled-folders.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@danielfawcett1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8486

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @danielfawcett1 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
