### ISSUE TITLE
clarification - Can I open encrypted messages sent to a shared mailbox?

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#8455]
I believe we should provide clarification here that the win32 inline experience applies only to encrypted messages sent internally within the same tenant.  Delegates to a shared mailbox getting AME/OME encrypted messages sent from an external org will need to use Outlook on the web to sign in as the shared mailbox to read these messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4c75d7b-eec1-720b-bc4d-91d3dfe72889
* Version Independent ID: 0382d4b5-3fe2-f353-ce73-5d437d80b7bf
* Content: [Message encryption FAQ](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-faq.yml)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8527

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per authors comment.
