### ISSUE TITLE
DLP alert time

### ISSUE THREAD

**Issue by bethaniekendwa** [MicrosoftDocs/microsoft-365-docs#8456]
[I would like to see in this page if the time frame for the DLP alert is 30 days and we cannot move it up to 90 days for example]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9eefa14-0e47-cf04-6f00-4bab24b4b858
* Version Independent ID: ff141977-2b63-e839-6252-84c6787972ea
* Content: [Get started with the DLP Alerts dashboard - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-alerts-dashboard-get-started?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-alerts-dashboard-get-started.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-alerts-dashboard-get-started.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by chrfox** [comment]
Hi @bethaniekendwa 
Please refer to the note at this link  https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-alerts-dashboard-get-started?view=o365-worldwide#dlp-alert-configuration
