### ISSUE TITLE
Release button in notification emails

### ISSUE THREAD

**Issue by lmeekscssa** [MicrosoftDocs/microsoft-365-docs#846]
It appears that there has been a further update to the notification emails, and that they now include  Release button once again that releases the email directly rather than making the user go to the Quarantine center. I'd like to link my users to this article for questions, but don't feel comfortable doing so until this item is detailed.

**Comment by mypil** [comment]
@lmeekscssa - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by lmeekscssa** [comment]
@mypil My apologies. I've not reported issues on Microsoft documentation before. The page I'm referring to is here: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages

**Comment by mypil** [comment]
@lmeekscssa  - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/windows-itpro-docs/commit/4c21ab49b8def24df3577015133c61bda1f47883 but it may take a few days for the merged content to appear in the article. 

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@lmeekscssa - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/98e9b72a001da61b0f551109d722b3215c20bdb7. 

Thank you for your contribution to make the docs better! Much appreciated!
