### ISSUE TITLE
Programatic setup for ownerless Office 365 groups

### ISSUE THREAD

**Issue by slueders-bag** [MicrosoftDocs/microsoft-365-docs#8468]
Hey,
is there an option for programatic setup like PowerShell, Graph API, etc.?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Version Independent ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Content: [Manage ownerless Microsoft 365 groups and teams - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/ownerless-groups-teams?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/ownerless-groups-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/ownerless-groups-teams.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@slueders-bag Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
