### ISSUE TITLE
Update Needed

### ISSUE THREAD

**Issue by kjulson** [MicrosoftDocs/microsoft-365-docs#847]
The instructions are a bit out of date, are for the old admin experience, and do not mention that it takes up to 12 hours for the app to be available to the organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in#get-and-enable-the-report-message-add-in-for-your-organization)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@kjulson, I updated the topic and added a note about 12 hours.

Thanks for the feedback.

Closing
