### ISSUE TITLE
File size limit in LiveResponse Library - API vs portal upload

### ISSUE THREAD

**Issue by andersnese** [MicrosoftDocs/microsoft-365-docs#8471]
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/upload-library indicates that the maximum file size for files being added to the library is 20mb using the API. However, using the portal the limit is 250mb (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response). 

Will the file size limit using the API be increased in the near-term future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8edc25af-c904-8cc0-061f-44ac9ac52880
* Version Independent ID: 8edc25af-c904-8cc0-061f-44ac9ac52880
* Content: [Upload files to the live response library](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/upload-library?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/upload-library.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/upload-library.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@andersnese Thank you for your feedback. Since this question needs to be directed to our Dev/product group, I'd recommend you post the question on our main feedback portal - https://feedbackportal.microsoft.com/

So that one of our Dev/product engineers will be able to review the roadmap and provide you with the information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@andersnese Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
