### ISSUE TITLE
First query - too specific

### ISSUE THREAD

**Issue by TBSJordanNash** [MicrosoftDocs/microsoft-365-docs#8472]
This first tutorial query needs to be much broader, so that the learner doesn't get "No results found in the specified time frame." on their first try.

This query is a little better:
`
union DeviceProcessEvents, DeviceNetworkEvents
| where Timestamp > ago(7d)
| project Timestamp, DeviceName, InitiatingProcessFileName, InitiatingProcessCommandLine, 
FileName, ProcessCommandLine, RemoteIP, RemoteUrl, RemotePort, RemoteIPType
| top 100 by Timestamp
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc0f70e-62ba-9d2b-1f24-83e8abb513bf
* Version Independent ID: 117e04d7-f7b9-a3db-e2a2-46da46008c96
* Content: [Learn the advanced hunting query language in Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-query-language?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-query-language.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-query-language.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@TBSJordanNash Thank you for your feedback. I get what you are saying, however the reason we have specific commands and process is to understand how they are being used. 

Thank you again for your feedback.

@yogkumgit  This can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @TBSJordanNash Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
