### ISSUE TITLE
Add Amazon Linux 2 support?

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#8477]
Can we add Amazon linux 2 in Capabilities per supported operating systems (OS) and platforms? Amazon Linux 2 is supported for having MDATP for linux. Do we support TVM in Amazon linux 2? if we don't can we add an column providing the data that we don't support? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1f5402-b627-d205-8e88-ca3fe609ef5f
* Version Independent ID: 0c91f8eb-368a-681a-209c-b03ff823945a
* Content: [Supported operating systems platforms and capabilities](https://review.docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tvm-supported-os?view=o365-worldwide&branch=main&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/tvm-supported-os.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tvm-supported-os.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by PremMS-MDE** [comment]
any update on this?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@PremMS-MDE Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8634

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@PremMS-MDE Thank you for your feedback. I have confirmed with the author that this table is for supported OS and platforms. It only includes not supported information when at least 1 platform is supported.

As soon as this support is available the product team will update the author and the document will be updated.

Hope this helps!

@yogkumgit  There are no changes required in this document.

Thanks
Sri
