### ISSUE TITLE
Sharing Submissions to 3rd parties typo

### ISSUE THREAD

**Issue by LoGlenn** [MicrosoftDocs/microsoft-365-docs#8478]
Microsoft treats your feedback as your organization's permission for us to analyze all of the previously described information and to work to fine tune the message hygiene algorithms. We hold your message in our secure audited datacenters in the USA until we delete your submission no later than 30 days after you provided it to us. Personnel at Microsoft may read your submitted message and attachments, which is normally not permitted for email in Office 365. **_However, your email is still treated as confidential between you and Microsoft, and we will provide your submission to any other party to read the email or its attachments for this review process._**

I believe it should say "and we will **NOT** provide your submission to any other party to read the email or its attachments for this review process".  Can someone look into this and correct it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a21caf6-05ad-6226-59ea-5e4151d784b8
* Version Independent ID: 9cb6935a-184f-b18a-184c-7d4faf6256b6
* Content: [Report spam, non-spam, and phishing messages to Microsoft - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
Fixed.

Thanks for the feedback.

Closing
