### ISSUE TITLE
Page additions

### ISSUE THREAD

**Issue by trkrdy1** [MicrosoftDocs/microsoft-365-docs#8479]
[We need to explain why for some of these entries, why it's bad to add these as exclusions. There needs to be a shock factor. I see these all the time on DART engagements.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 864c454f-e0d9-fb1d-6090-5982eb733eb0
* Version Independent ID: ca1abacc-22e4-688d-370b-e34d827fde76
* Content: [Common mistakes to avoid when defining exclusions](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/common-exclusion-mistakes-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. thanks
