### ISSUE TITLE
There is no "Permissions" tab on the left side of the Compliance admin center

### ISSUE THREAD

**Issue by fitzgeezy** [MicrosoftDocs/microsoft-365-docs#8480]
It appears that these instructions are no longer valid? There is no Permissions tab in the Compliance admin portal. Has everything moved to AAD RBAC roles?

```
Assign eDiscovery permissions

    Go to the [compliance portal](https://go.microsoft.com/fwlink/p/?linkid=2077149) and sign in using an account that can assign permissions.

    _**In the left pane, select Permissions.**_

    On the Permissions & Roles page, under Compliance center, click Roles.

    On the Compliance center roles page, select eDiscovery Manager.

    On the eDiscovery Manager flyout page, do one of the following based on the eDiscovery permissions that you want to assign.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94e0469-2c5c-2063-8c3e-7722ceb53577
* Version Independent ID: e99eb8aa-b3b7-8791-aba4-998e209694b5
* Content: [Assign eDiscovery permissions in the Microsoft Purview compliance portal - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/assign-ediscovery-permissions?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/assign-ediscovery-permissions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/assign-ediscovery-permissions.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.
