### ISSUE TITLE
Compliance portal screenshot is outdated

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/microsoft-365-docs#8481]
The screenshot of Microsoft Purview Compliance Center is showing a very outdated image labeled "Security & Compliance"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5821435a-93ce-3ba9-312d-fb61a9dae127
* Version Independent ID: aaf49dab-bbdc-4c84-f9ef-a768da673279
* Content: [How DLP works with Security & Compliance Center & Exchange admin center - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/how-dlp-works-between-admin-centers?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/how-dlp-works-between-admin-centers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/how-dlp-works-between-admin-centers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@gbms311 Thank you for your feedback. I'll update the document with the latest screenshot.

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrfox Please help. Email sent. thanks

**Comment by yogkumgit** [comment]
@chrfox Gentle reminder.
