### ISSUE TITLE
WebApp Limitations with desktop labeled documents

### ISSUE THREAD

**Issue by MichaelRyan87** [MicrosoftDocs/microsoft-365-docs#8488]
From my testing there is a limitation with accessing label encrypted documents on a SPO site where the file has been encrypted from the desktop apps with an admin defined encryption label. Attempting to open the file will result in the following error:

![image](https://user-images.githubusercontent.com/37851228/166680864-26fb16c2-0b57-4aac-a069-5d8505f869ce.png)

Opening with a desktop app then continues as expected.

If the file is encrypted with a label through a WebApp then the file can shared and opened in the WebApp or desktop app by other parties without issue.

This limitation is causing confusion and an inconsistent experience where guests with access to files cannot use the WebApp that they are launched into when receiving a sharing link to an encrypted file. Some guest users may not have access to a local office suite and must use web apps.

The issue doesn't seem well documented, but another user has mentioned this with the same results around a year ago. 

https://answers.microsoft.com/en-us/msoffice/forum/all/unable-open-files-with-sensitive-label-in/cbf2b1ec-24e0-4d3b-adc9-b9283e795d1a

Is this a known issue not documented?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@MichaelRyan87 I'm not able to reproduce the issue. I'd recommend you contact Microsoft via the need help section on the admin center so that a support technician can assist you in fixing or filing a bug.

Hope this helps!

Thanks
Sri

**Comment by MichaelRyan87** [comment]
Thanks, Sri, I'll do that.
