### ISSUE TITLE
Defender for endpoint REST API issue

### ISSUE THREAD

**Issue by barn4k** [MicrosoftDocs/microsoft-365-docs#8489]
Hello,

when I'm trying to use [list_machines](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-machines?view=o365-worldwide) or [list_alerts](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-alerts?view=o365-worldwide) methods with **$top** property, there are no **odata.nextLink** in the results. Thus, it is impossible to page results less than 10k events

For example, Graph API is working [fine](https://docs.microsoft.com/en-us/graph/paging)

Second problem:
list_machines method has oData query **$filter** on the **onboardingStatus** property (and it works fine), but the **$select** query won't work with this property.

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Please contact support.
