### ISSUE TITLE
How do I download the XML manifest file?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [MicrosoftDocs/microsoft-365-docs#849]
My tenant doesn't have the Office store. I can only add using the XML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message add-in](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@A9G-Data-Droid - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products


If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
