### ISSUE TITLE
missing endport for Azure portal

### ISSUE THREAD

**Issue by vtwwe** [MicrosoftDocs/microsoft-365-docs#8490]
afd.hosting.portal.azure.net hosting log resources of Azure Portal is not listed (probably *.hosting.portal.azure.net).
In case proxy blocks this URL Azure Portal is unusable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
The Office 365 endpoints web service only includes endpoints specific to Office 365. The Azure portal is out of scope, which is why it is not listed.
Thanks for reaching out.
Kelley
