### ISSUE TITLE
Links for the deployment lab kit not working

### ISSUE THREAD

**Issue by enrikd13** [MicrosoftDocs/microsoft-365-docs#8494]
So the links to the  deployment lab kit seem to be down and just redirect to the main Microsoft downloads page (microsoft.com/en-us/download) constantly from different browsers and both in incognito too , so I'm guessing its not an issue with my browser.
Would really appreciate if someone could follow through and have a solution soon. 

## Update : 

It seems every https://www.microsoft.com/en-us/evalcenter link just gets redirected to the main Microsoft downloads page, so not really an issue with Microsoft Docs , but still hoping for a solution .

## Temporary solution : 

https://techcommunity.microsoft.com/t5/windows-11/accessing-trials-and-kits-for-windows-eval-center-workaround/m-p/3361125
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by boltsa** [comment]
I'm having the same issue. Please fix the links.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by RAJU2529** [comment]
@yogkumgit , PLease close this issue #8494, because new   links are added and working fine
