### ISSUE TITLE
com.microsoft.wdav.tunnelext is still described in the docs. It is probably no longer necessary.

### ISSUE THREAD

**Issue by colorenz** [MicrosoftDocs/microsoft-365-docs#8495]
Please Update the Docs. com.microsoft.wdav.tunnelext is still described in the docs. It is probably no longer necessary.

![image](https://user-images.githubusercontent.com/16665557/166812701-8ce71474-38be-4c2d-8dc3-037fb684a935.png)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680cec4a-027f-5aa8-b56a-85410d2c7819
* Version Independent ID: 691a04d1-ee6e-ff6e-b8da-4048eb3976b4
* Content: [Deployment with a different Mobile Device Management (MDM) system for Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-other-mdm?view=o365-worldwide#network-extension-policy)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-with-other-mdm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-with-other-mdm.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @maximvelichko
* Microsoft Alias: **mavel**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @colorenz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
