### ISSUE TITLE
Permission Requirements

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#8499]
Add details on the required permissions for managing services. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f1236b-050e-d7b5-ea59-3de650155607
* Version Independent ID: fc058c80-e7c4-1a26-cbc3-d33fc2282e13
* Content: [Define your Bookings service offerings](https://docs.microsoft.com/en-us/microsoft-365/bookings/define-service-offerings?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/define-service-offerings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/define-service-offerings.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@danmyhre Thank you for your feedback. I tested and there are no special permissions required. Once user gets access to bookings (https://docs.microsoft.com/en-us/microsoft-365/bookings/get-access?view=o365-worldwide) they will be able to create a calendar and define the service offerings.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @danmyhre Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by danmyhre** [comment]
@msbemba You were probably setup as the admin of the bookings mailbox though. I am saying it would be good to have a matrix of what each staff role can and can't do.  And if there is the ability to create custom roles.
