### ISSUE TITLE
For the second sentence on this page, please add the field names (from the table) in parentheses to their textual description.

### ISSUE THREAD

**Issue by sujit-msft** [MicrosoftDocs/microsoft-365-docs#850]
The table indicates the name of the metadata field, whether the field can be searched when running a query in a review set ("Searchable field name"), whether the field is present when viewing the file metadata of a selected document in a review set ("Display field name"), and whether the field is included when documents are exported ("Exported field name".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 103cace9-f60c-717a-1488-195cbff0f408
* Version Independent ID: 5116f243-4705-5661-f58f-dcd6f9cd56a2
* Content: [Document metadata fields in Advanced eDiscovery](https://docs.microsoft.com/en-us/microsoft-365/compliance/document-metadata-fields-in-advanced-ediscovery#feedback)
* Content Source: [microsoft-365/compliance/document-metadata-fields-in-Advanced-eDiscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/document-metadata-fields-in-Advanced-eDiscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@sujit-msft Done. Thanks for the heads up. Updated topic will be published later today.
