### ISSUE TITLE
Change code block from inline to a PowerShell formatted block

### ISSUE THREAD

**Issue by chadmando** [MicrosoftDocs/microsoft-365-docs#8501]
In the linked section, the configuration options are written with inline code blocks.  It doesn't allow for the easy copy/paste option or formatting like a language specific code block.  I would be happy to make this change.  

Creating the issue first in the case this was done on purpose. 

[change default setting link](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell.md#change-the-default-setting-of-microsoft-365-groups-for-outlook-to-public-or-private)

Current formatting:
 `Set-OrganizationConfig -DefaultGroupAccessType Public`

Proposed change:
```powershell
Set-OrganizationConfig -DefaultGroupAccessType Public
```

**Comment by yogkumgit** [comment]
@chadmando Please indicate which document you are referring to for this feedback. Thanks

**Comment by chadmando** [comment]
The document path is: MicrosoftDocs/microsoft-365-docs/microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell.md

Link: https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/manage-microsoft-365-groups-with-powershell.md#change-the-default-setting-of-microsoft-365-groups-for-outlook-to-public-or-private

The section of the document is:
## Change the default setting of Microsoft 365 Groups for Outlook to Public or Private

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chadmando Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
