### ISSUE TITLE
Limitations for OCR

### ISSUE THREAD

**Issue by janvonr** [MicrosoftDocs/microsoft-365-docs#8504]
In the documentation there's no information regarding the limitations of OCR and also no information regarding the Azure Cognitve Services on which the feature relies.

We have some customers requesting this information, so it would be very helpful if this information could be added to the documentation.

For the customers it is very important to understand what information they can expect to be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfddab0e-dc50-2271-33a9-92f6f4c72eeb
* Version Independent ID: 041f18aa-aa1a-0c2d-def0-0ae985258786
* Content: [Configure search and analytics settings - eDiscovery (Premium) - Microsoft Purview](https://review.docs.microsoft.com/en-us/microsoft-365/compliance/configure-search-and-analytics-settings-in-advanced-ediscovery?view=o365-worldwide&branch=main)
* Content Source: [microsoft-365/compliance/configure-search-and-analytics-settings-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/configure-search-and-analytics-settings-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@v-tophillips Please help us in resolving this issue. Thanks

**Comment by janvonr** [comment]
Hey everyone, are there any updates on this?
