### ISSUE TITLE
Add "applies to MDE P1" on this page

### ISSUE THREAD

**Issue by jackson-yang-microsoft** [MicrosoftDocs/microsoft-365-docs#8505]
It's a bit confusing while "Create indicators for files" display applies to MDE P1&P2, but this page only applies to MDE P2

![image](https://user-images.githubusercontent.com/101696604/167103969-603128a0-8413-4516-a4ce-1efcb2bb1b6e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04266df-a692-ddef-5f05-ea40d82a0eed
* Version Independent ID: d0ac62e7-498f-399d-c701-d7cbeb85cced
* Content: [Create indicators](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-indicators?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-indicators.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-indicators.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jackson-yang-microsoft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jackson-yang-microsoft** [comment]
This works perfectly! Thanks for updating!!
