### ISSUE TITLE
Block execution of potentially obfuscated scripts

### ISSUE THREAD

**Issue by MasterBlaster4** [MicrosoftDocs/microsoft-365-docs#8506]
The information provided is not accurate since the PS scripts were removed from the scope of this ASR according to the WD Response Request ID: 39392159

"The Powershell scripts have been excluded from the "Block execution of potentially obfuscated scripts" rule [5beb7efe-fd9a-4556-801d-275e5ffc04cc] due to the large scale FP issues faced in the past."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Version Independent ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Content: [Attack surface reduction rules reference](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?msclkid=c9afe3d1cd3011ec84d2411d02b0c0c2&view=o365-worldwide#block-execution-of-potentially-obfuscated-scripts)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@MasterBlaster4 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8670

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by jweston-1** [comment]
Approved. Please publish.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit  The PR is already approved.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MasterBlaster4 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
