### ISSUE TITLE
Create better description of quarantine notification settings

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/microsoft-365-docs#8507]
https://docs.microsoft.com/microsoft-365/security/office-365-security/quarantine-policies#configure-global-quarantine-notification-settings-in-the-microsoft-365-defender-portal

I read the documentation and tried to configure the quarantine notification settings but it is poorly described.

Could you please improve the description?

What does the setting "Default" for language mean?

>  You can select multiple languages by clicking Add after each one. 

This is not correct, you can only configure a maximum of three languages.

When you configure the same sender name for different languages you the message:

![image](https://user-images.githubusercontent.com/62641471/167138337-a94c1f21-ccb3-4112-aa63-f6d8808bcd5b.png)

It is labeled as a warning and uses the term "should".

However you cannot continue without changing the name.

So this is not a warning but an error and it should use the term "must" instead of should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf5c5df-c3ab-8448-aef0-af05977db9b9
* Version Independent ID: adade895-f42b-1029-9948-5ddb5b038257
* Content: [Quarantine policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide#configure-global-quarantine-notification-settings-in-the-microsoft-365-defender-portal)
* Content Source: [microsoft-365/security/office-365-security/quarantine-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@joergrenn, thanks for the feedback. It appears that the UI has changed in that Global Settings flyout of quarantine policies. I updated it to match currently reality, and clarified it based on your suggestions. See the pull request linked to this issue.

I'll notify the product team about the string change from "should" to "must" in that dialog box.

After you've verified that you like the changes (after 4:00 PM F 5/6 GMT-7), feel free to close this issue.

**Comment by yogkumgit** [comment]
@joergrenn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by joergrenn** [comment]
Hello @yogkumgit,
thanks for providing the update.
However even with the update it is still not clear what means "Default" Language.
The text now says:
> Select the language from the Choose language box. The default value is Default, which means English.

However there is the default setting and also an English setting. If default means English why are there two settings?
Also they are not the same. If I enter something in default it does not show up in the English setting:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/62641471/180957394-b1489b54-1624-482d-9bdb-3b32e11add39.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/62641471/180957578-bc159bee-391a-4930-b965-c58ce57ee38c.png">

Also I can Add English and Default together. What is the usecase for this if default means English?
<img width="698" alt="image" src="https://user-images.githubusercontent.com/62641471/180958113-e529b589-1863-4b71-9ea2-239c19fe7278.png">

best regards
Joerg

**Comment by chrisda** [comment]
@joergrenn, unless you can prove to the contrary, I still contend that English and Default are equivalent. It's just a quirk of the UI design that you can select both.

**Comment by joergrenn** [comment]
Hello @chrisda ,
its not just that you can select both, as you can see in my screenshots. The text that you can enter in Display Name and Disclaimer it stored differently.
If it were just the UI, it would still store the text in the same place an show the same in both selections.
But I also don't understand why we have to guess about it or I have to proof something.
You are a Microsoft employee and this is a Microsoft product, so it should be possible to find a developer that can look into the design documentation or even the source code and then we know how its implemented.

**Comment by chrisda** [comment]
@joergrenn, my apologies. I did not mean to imply that you need to prove anything. I just thought you might have the results of your testing that would show what's actually happening.

- According to old correspondence that I found but apparently never implemented, Default means the [default language of the Microsoft 365 organization](https://docs.microsoft.com/office365/troubleshoot/access-management/set-language-and-region). I'll update the topic accordingly.

  But, it doesn't really matter what the Default language value is, because, as you've described, you can still pick Default + two other languages, one of which might also be the Default, so why do that?

- Regarding the Warning and should vs. must, I'd swear that I either brought this up or it was shown to me about the same time I corrected the 'max 3 languages' thing.

I'll seek clarification on these issues and report my findings.

**Comment by joergrenn** [comment]
@chrisda, I am also sorry I apparently took the reply the wrong way.

> Default means the [default language of the Microsoft 365 organization](https://docs.microsoft.com/office365/troubleshoot/access-management/set-language-and-region).

That definitively makes more sense then: default equals English.
But I still don't really understand what this default setting is for, because I agree with you that it makes little sense to select default and another language which might be the same as the default.
