### ISSUE TITLE
Convert to shared mailbox steps need to be updated

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/microsoft-365-docs#8508]
At section: https://docs.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide#use-the-new-exchange-admin-center-to-convert-a-mailbox

Step 3, it indicates: _Select the user mailbox. In the Mailbox tab, under More Actions, select Convert to shared mailbox._

As of 5/6/22, this is under **Others** tab, not **Mailbox** tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b3fbbe-fde3-fd52-f9cd-d8fca56a1494
* Version Independent ID: 73d71ee8-579d-78b5-a8cd-48d7ec51ebb8
* Content: [Convert a user mailbox to a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@mntorq Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8565

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mntorq Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
