### ISSUE TITLE
change .py to .sh

### ISSUE THREAD

**Issue by samkellyd** [MicrosoftDocs/microsoft-365-docs#8509]
changed .py to .sh, recent change on downloading onboarding script.  https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-jamfpro-policies?view=o365-worldwide#step-1-get-the-microsoft-defender-for-endpoint-onboarding-package

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e6e51c-592a-ed20-2340-e921e5ebd775
* Version Independent ID: b3e6e51c-592a-ed20-2340-e921e5ebd775
* Content: [Onboard devices to Microsoft Defender for Business](https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-onboard-devices?view=o365-worldwide&tabs=WindowsClientDevices)
* Content Source: [microsoft-365/security/defender-business/mdb-onboard-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-onboard-devices.md)
* Product: **m365-security**
* Technology: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@samkellyd Thank you for your feedback. You are correct, it is python script, not bash. However, I'm unable to locate that in this document. COuld you please help with the URL of the document you are referring to?

Thanks
Sri

**Comment by samkellyd** [comment]
Step 10 under Mac, should be bash not .py

https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-onboard-devices?view=o365-worldwide&tabs=macOSdevices


Samantha Dominguez

Technical Advisor  | Defender for Endpoint | Azure Security
 • ***@***.******@***.***>

My Office Hours: Mon-Fri 8am - 5pm EST

Microsoft Premier Online: https://premier.microsoft.com<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpremier.microsoft.com%2F&data=04%7C01%7Csdominguez%40microsoft.com%7Cf9982fa8d47546b2962308d9e5d04f76%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793505122734656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BojLrHc6BWc0St0cC2cxszrcZb1vA1%2F9Qj8BtChh6UE%3D&reserved=0>

Microsoft Premier Support: (800) 936-3100<tel:+18009363100>

If you have any feedback about my work, please contact my manager Erik Wilson ***@***.******@***.***>

Set a meeting with me using Bookings<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Foutlook.office365.com%2Fowa%2Fcalendar%2FEPATZTA%40microsoft.onmicrosoft.com%2Fbookings%2F&data=04%7C01%7Csdominguez%40microsoft.com%7Cf9982fa8d47546b2962308d9e5d04f76%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637793505122734656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ExL4Ct5iNG2CUiq9qQxza7QH33C%2FS4CdQqYBgJ%2BkYag%3D&reserved=0>

________________________________

**Comment by msbemba** [comment]
@samkellyd We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8676

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @samkellyd Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
