### ISSUE TITLE
Multiple Errors on Page

### ISSUE THREAD

**Issue by PayneCeeva** [MicrosoftDocs/microsoft-365-docs#8512]
I'll list the errors I ran into before I had to stop due to issues with Azure AD "Sync," which is not in the purview of this page. 

-Step 2, Note insert: "Should be less than 20 GB" indicates more than 20 will work but is not recommended. In fact, a file larger than 20GB causes the application to crash. 
-Step 2, part 3: The command given is [azcopy.exe copy "<Source location of PST files>" "<SAS URL>"] and examples below reflect the Source Location being a folder. The azcopy executable does not support folders as indicated by the error message it generates. The path needs to include the file name. If the folder contains multiple files, the command must be run multiple times.
-Step 4, part 3, FilePath field: Makes reference to command switches from an obsolete version of azcopy.exe which no longer function. 

I recommend having one of the documentation staff go through the process of uploading a PST file to Exchange Online and rewrite the page from scratch. As I mentioned, I had to stop at this point, but I'd be surprised if those were the only errors in the instructions.

The reason I had to stop was that the client previously had an on premises Exchange server that "synchronized" with Exchange online, and since the sync is actually one-way and not a synchronization process, I can only enable email archives via the remote server. I'm not authorized to make major changes to the 365 account, so I've left the PowerShell commands to the engineer we assigned to the account. 

Honestly I'm amazed that the first company to create cross-application copy paste managed to make file transfers so complicated you need to make a multi page instruction article. That takes commitment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import PST files - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#step-1-copy-the-sas-url-and-download-azcopy)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@v-tophillips Please help us in resolving this issue. Thanks

**Comment by v-tophillips** [comment]
The statement "should be less than 20 GB" was written as: each PST file that you upload to the Azure Storage location should be **no larger** than 20 GB.
