### ISSUE TITLE
Script to restrict O365Group creation and Yammer

### ISSUE THREAD

**Issue by ReadingMo123** [MicrosoftDocs/microsoft-365-docs#8513]
Has anyone processed this script to restrict yammer community/group creations?
The article says it should work for Yammer. We ran the script successfully but I am still able to create communities in Yammer with an account that is not part of main group that can do the group creation.
It does work as described in the article for Planner
Any feedback would be appreciated. 
Thank you 

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 445c0a2e-1a22-d90f-0c73-0edf34f2b99a
Version Independent ID: d534ac69-134d-0198-fcb9-e19d1ed44d4b
Content: [Manage who can create Microsoft 365 Groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide)
Content Source: [microsoft-365/solutions/manage-creation-of-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/manage-creation-of-groups.md)
Service: o365-administration
GitHub Login: @MikePlumleyMSFT
Microsoft Alias: mikeplum

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ReadingMo123 Thank you for your feedback. I was able to test and the script does restrict users from creating groups in yammer. 

Note that the steps in this article won't prevent members of certain roles from creating Groups. If you continue to have the problem, I'd recommend you contact Microsoft support via the need help option on the admin center.

Hope this helps!

Thanks
Sri

**Comment by ReadingMo123** [comment]
Thank you Sri for taking the time to review it. 
I found out with further testing that the script will only restrict regular users (except those in the specified security group and network/global admins) from creating O365 yammer groups but it will not prevent from creating non O365 yammer groups. Everyone will still be able to create yammer groups (that is by design), It will just depend whether it is or not connected to O365. The button create communities will always show up in yammer.
I am just going to have to work around it and setup power automate to let me know when a new group is created so that I can keep an eye on it.
Thank you again for your help.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ReadingMo123 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
