### ISSUE TITLE
High Confidence Phishing not included in table

### ISSUE THREAD

**Issue by chrisp1992** [MicrosoftDocs/microsoft-365-docs#8514]
Is there a reason that High Confidence Phishing isn't listed in the non-configurable priority table? Is it just part of Phishing? It's hard to tell since High Confidence Spam is there along with Spam. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4194fdd-c5de-d424-319a-5e83774b36c2
* Version Independent ID: 83997ad4-a9bd-146e-5da0-8022458cf3ea
* Content: [Order and precedence of email protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/how-policies-and-protections-are-combined.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
The high confidence phishing verdict is part of spam. Did something new come along?

**Comment by chrisda** [comment]
Got it. Now attempting to find the answer.

**Comment by chrisp1992** [comment]
It’s part of Anti-Spam policies, yes, but it has it’s own toggle, next to phishing, spam, and high confidence spam within the Anti-Spam policy

**Comment by chrisda** [comment]
@chrisp1992, HPSH was finally (!) added to the table today in [this PR] (https://github.com/MicrosoftDocs/microsoft-365-docs/commit/954f217d2df69eaec47544569f9c4aa703ecc28e), so I'm closing this issue.

The linked issue above indicates there is still more work to do, in that GIMP (mailbox intelligence), Safe Links, and Safe Attachments are also missing from that table, which we are trying to rectify as we speak.

Thanks for the feedback.

Closing.
