### ISSUE TITLE
Typo on page... "essage Encryption"

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/microsoft-365-docs#8515]
There is a typo on this page, instead of "Message Encryption" it says "essage Encryption". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed881955-a2ba-6482-cb1b-8443909c4d52
* Version Independent ID: 57679a1a-7501-40fe-c1c4-5aff9a45c792
* Content: [Encryption in Microsoft 365 - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @MSFTEfeedback Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
