### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by tokar04** [MicrosoftDocs/microsoft-365-docs#852]
[Enter feedback here]
broken link
https://download.microsoft.com/download/3/7/7/377F1BBC-37D5-4677-AB4A-7C01D089CA67/PCI_DSS_Compliance_Backgrounder.pdf

404 - File or directory not found.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b95bd5-5663-90ab-f902-bab7887e4489
* Version Independent ID: 28d8c81c-5e29-b300-5b23-137e9692940e
* Content: [Payment Card Industry (PCI) Data Security Standard (DSS)](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-pci-dss#feedback)
* Content Source: [microsoft-365/compliance/offering-PCI-DSS.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/offering-PCI-DSS.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@tokar04 - thanks for the feedback, I'm working to correct this broken link,

**Comment by robmazz** [comment]
@tokar04 - thanks again, this link has been updated and fixed.
