### ISSUE TITLE
It's not clear whether this comes with our license or is an additional cost

### ISSUE THREAD

**Issue by waydaws** [MicrosoftDocs/microsoft-365-docs#8521]
To me, on reading this page, it looks like this is something that is not covered in our E5 license since it says "contact your account team".   After having to shell out for and E5 license, you wouldn't expect to get Nickle and Dimed for extra services.  Targeted Attack Notifications should be automatically covered, while Threat Experts only should be extra.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e312ba4d-6340-52f0-1290-7e5505f7a9c0
* Version Independent ID: f7d45e69-56d2-01c5-898c-2e039edafe04
* Content: [Microsoft Threat Experts](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-threat-experts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-threat-experts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-threat-experts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@waydaws Thank you for your feedback. I'd recommend you post this feedback on our Main feedback portal - https://feedbackportal.microsoft.com/ so one of our Product/Dev team members can help you with the details on why you are being asked to contact the account manager. 

This feedback section is for any modifications to the document. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@waydaws Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
