### ISSUE TITLE
Unnecessary whitespace on EwsAllowList modification

### ISSUE THREAD

**Issue by aryasenna** [MicrosoftDocs/microsoft-365-docs#8522]
There's an unnecessary whitespace character for this command:

`Set-OrganizationConfig - EwsAllowList @{Remove="MicrosoftOWSPersonalBookings"}`
 
Should be `-EwsAllowList` not `- EwsAllowList`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings in Outlook](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@aryasenna Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8569

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @aryasenna Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
