### ISSUE TITLE
Download links are dead

### ISSUE THREAD

**Issue by gringogreen** [MicrosoftDocs/microsoft-365-docs#8524]
Both links (to download the kit for Windows 10 & 11) are invalid. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by RAJU2529** [comment]
@yogkumgit , PLease close this issue #8524,because new   links are added and working fine

**Comment by gringogreen** [comment]
The issue is NOT resolved. Are you actually getting paid for this quality of work?
________________________________

**Comment by msbemba** [comment]
@gringogreen please test and let me know the erro message you receive.
