### ISSUE TITLE
Enforcing Policy in images

### ISSUE THREAD

**Issue by lalitm14** [MicrosoftDocs/microsoft-365-docs#853]
can DLP policies be enforced / checked for match in non text documents e.g. image, PDF etc. ?

**Comment by mypil** [comment]
@lalitm14  - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@lalitm14 - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
