### ISSUE TITLE
ASR Rule Block execution of potentially obfuscated scripts does not block PS scripts

### ISSUE THREAD

**Issue by D4m4** [MicrosoftDocs/microsoft-365-docs#8530]
It appears that at this moment the rule "Block execution of potentially obfuscated scripts" (https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?msclkid=b6b286d8cf8211ecab768e3d7d5d8c4b&view=o365-worldwide#block-execution-of-potentially-obfuscated-scripts) does not detect PS scripts due to high impacting FPs. It would be useful to add a note that this is a temporary measure and that soon the rule will re-start detecting them.

Thanks
//D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Version Independent ID: 71a17626-d89b-a06f-9cc6-308b80a84acc
* Content: [Attack surface reduction rules reference](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?msclkid=b6b286d8cf8211ecab768e3d7d5d8c4b&view=o365-worldwide#block-execution-of-potentially-obfuscated-scripts)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by denisebmsft** [comment]
I have opened a work item that will be assigned to a writer ASAP. We'll get the docs updated soon.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @D4m4 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
