### ISSUE TITLE
Question on logic

### ISSUE THREAD

**Issue by rmcgarry** [MicrosoftDocs/microsoft-365-docs#8531]
> [$(date +%d) -le 15] == Won't run unless it's equal or less than the 15th day (3rd week). Meaning it will run every 3rd Sundays(7) of the month at 6:00 a.m. Pacific (UTC -8).

While technically correct, the intent implied by this document is not going to be satisfied by the crontab entry presented.

As written, the "update command" will occur on every Sunday where the calendar day is less than or equal to 15.  This will happen at least twice in every month.  If the month begins on a Sunday, the conditions will be satisfied 3 times - on the 1st, the 8th, and the 15th.

To have the update occur **only** on the third Sunday of every month, you can use this simpler entry:

```
0 6 15-21 * sun sudo **update command**
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19248657-fdd4-e6d5-f61e-828181b38817
* Version Independent ID: 2244848d-24df-ce71-4e36-89cf067eedd5
* Content: [How to schedule an update of the Microsoft Defender for Endpoint (Linux)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-update-mde-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-update-mde-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-update-mde-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks.

**Comment by rmcgarry** [comment]
Upon further investigation, I discovered that my assumption of how cron works was incorrect  My changes will not work as I suggested it would.  (If the date (1-31) is not a wildcard, then the day of the week (0-6) becomes  a logical "OR".)

https://crontab.guru/cron-bug.html

My apologies, I would like to close this request.
