### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by alialhammad1992** [MicrosoftDocs/microsoft-365-docs#8532]
Please-support-the-application-in-Arabic IOS

**Comment by denisebmsft** [comment]
Hello @alialhammad1992. Thank you for posting your request here. Can you please tell us to which article this issue applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by alialhammad1992** [comment]
I want to support IOS application in Arabic language

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Denise Vangel-MSFT ***@***.***>
‏‏تم الإرسال: Tuesday, May 10, 2022 1:17:27 AM
إلى: MicrosoftDocs/microsoft-365-docs ***@***.***>
نسخة: alialhammad1992 ***@***.***>; Mention ***@***.***>
‏‏الموضوع: Re: [MicrosoftDocs/microsoft-365-docs] IOS (Issue #8532)


Hello @alialhammad1992<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falialhammad1992&data=05%7C01%7C%7C714395d8e33d4792f3da08da3209b367%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637877314484347902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iSXwdrV7GrHF%2FDXqabkxruxsEnDy3qTxacPSs4t3mjM%3D&reserved=0>. Thank you for posting your request here. Can you please tell us to which article this issue applies? This information will help us route the issue to the correct writer/team. Thank you!

**Comment by yogkumgit** [comment]
@tiburd Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@alialhammad1992 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
