### ISSUE TITLE
Add Instructions to Change Geo Location of a Team

### ISSUE THREAD

**Issue by BrianMcNeese** [MicrosoftDocs/microsoft-365-docs#8534]
Although admins may be able to read between the lines, it would be beneficial to add a section containing step-by-step instructions for moving a team's geo location (i.e. change the pdl of the underlying group using cmd below, then move the spo site using cmd below, etc).

Add this info either to this page, or link to a new page called "Move a team" under the "Manage" section of docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8330026f-6986-c8e2-f532-f1ae3a06e4b8
* Version Independent ID: e62c6f5a-d930-31de-dc1f-da57f0c7229f
* Content: [Multi-Geo Capabilities in Microsoft Teams - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-teams-in-microsoft-365?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/multi-geo-capabilities-in-teams-in-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/multi-geo-capabilities-in-teams-in-microsoft-365.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please help us in resolving this issue. Thanks.

**Comment by MikePlumleyMSFT** [comment]
@BrianMcNeese closing this issue as we have an internal thread on this subject.
