### ISSUE TITLE
Download Links for Deployment Lab Kit not working

### ISSUE THREAD

**Issue by MichaelBishopMN** [MicrosoftDocs/microsoft-365-docs#8536]
The links to download the Deployment Lab Kit just redirect to https://www.microsoft.com/en-us/download with no option to download the lab kit.

Windows 11 with Office 365 deployment lab kit:
https://www.microsoft.com/evalcenter/evaluate-windows-11-office-365-lab-kit

Windows 10 with Office 365 deployment lab kit:
https://www.microsoft.com/evalcenter/evaluate-lab-kit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @MichaelBishopMN Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
