### ISSUE TITLE
CmdLet name - small issue

### ISSUE THREAD

**Issue by jwu56** [MicrosoftDocs/microsoft-365-docs#8537]
The cmdlet name for getting the Organization Config is not in the right case. It should be `Get-OrganizationConfig
 ` and not `Get-Organizationconfig`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings in Outlook](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by chrisda** [comment]
PR merged. Closing
