### ISSUE TITLE
Is "ListItemViewed" event in SharePoint list available?

### ISSUE THREAD

**Issue by AiHirano** [MicrosoftDocs/microsoft-365-docs#8538]
[Enter feedback here]

This audit event for SharePoint lists was available until the on-premises days, but has long been unavailable in SharePoint Online. I checked the audit log entry for my tenant to see if this information is now available and found that this entry does not exist. Is this info correct? Or is this a new update?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#sharepoint-list-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AiHirano Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by AiHirano** [comment]
I am really sad that it isn't available on SharePoint Online.

Thanks all. @yogkumgit @msbemba
