### ISSUE TITLE
Educational Licensing and Alerts

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/microsoft-365-docs#8539]
Educational licenses are not listed for configuring alerts in the DLP Alert management Dashboard.

Please also see issue https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/668

A1 and A3 have access to Sharepoint/OneDrive and Exchange DLP
A5 has access to Teams DLP in addition to files and e-mail.

However alert configuration options do not list academic licenses in the alert configuration options.

Can this be updated please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e9f547-6180-2981-6e7a-895fc17b7703
* Version Independent ID: 58334631-7058-1809-0804-c107457b4470
* Content: [Configure and view alerts for DLP policies - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-configure-view-alerts-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-configure-view-alerts-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-configure-view-alerts-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@thewrabbit Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8674

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@thewrabbit The PR is updated with just A5 now. Once the author approves, the changes will be live.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit The PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8674 is waiting for author approval and merge

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @thewrabbit Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
