### ISSUE TITLE
Site and group settings privacy should be optional

### ISSUE THREAD

**Issue by Joachim83** [MicrosoftDocs/microsoft-365-docs#854]
I want to use Sensitivity label to disable external access, however I am also forced to also choose the privacy level.

We should be able to leave the privacy settings blank so we can disable external access to a group/Teams, but still allow group owners to change between private and public group.

And yes I know guest will be able to access a public sharepoint site without membership, but we want to block them from joining Teams.

**Comment by mypil** [comment]
@Joachim83  - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by Joachim83** [comment]
> @Joachim83 - May we know which Microsoft document link you used in reference to this issue?
> Please share it with us so we can investigate further. Thank you.

This is the document I am referring to:

https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#set-site-and-group-settings-when-you-create-sensitivity-labels

**Comment by mypil** [comment]
@Joachim83 - From our understanding, the issue has been addressed based on this merged commit https://github.com/ee61re/microsoft-365-docs/commit/1729d3c05a693fc3b30261ca435409da96ecc7a9. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
Reopening issue

**Comment by mypil** [comment]
@Joachim83 - Please feel free to submit this product feedback at https://office365.uservoice.com/forums/289138-office-365-security-compliance.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in UserVoice.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
