### ISSUE TITLE
Misleading information on the script extension on the german version. Its python script, not bash

### ISSUE THREAD

**Issue by kotras** [MicrosoftDocs/microsoft-365-docs#8541]
Please change on the German version the onboard script extension, should be MicrosoftDefenderATPOnboardingLinuxServer.py and not MicrosoftDefenderATPOnboardingLinuxServer.sh. This is in multiple places, here is one:
![image](https://user-images.githubusercontent.com/96786608/167620358-b2808945-703c-40d7-b6b1-5736b43452e2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab0b894-0199-7515-b060-a6724e2c9b9e
* Version Independent ID: 988ff83c-c4b5-d2f3-023e-2d8dd191b7ae
* Content: [Deploy Microsoft Defender for Endpoint on Linux manually](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-install-manually.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-install-manually.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@kotras Thank you for your feedback. I could not locate the german version to correct it. Would you be able to provide us the URL you are using to access the german version of the document?

Thanks
Sri

**Comment by kotras** [comment]
You can find it here https://docs.microsoft.com/de-de/microsoft-365/security/defender-endpoint/linux-install-manually?view=o365-worldwide#download-the-onboarding-package

**Comment by msbemba** [comment]
@kotras Thank you for the response. I'm working with the author to get this sorted.

Thanks
Sri

**Comment by yogkumgit** [comment]
@Dansimp Please help. Email sent.

**Comment by yogkumgit** [comment]
@Dansimp Please comment. Thanks
