### ISSUE TITLE
Typos in commands

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/microsoft-365-docs#8542]
You have typos in commands. Whereas, it won't work if you have whitespace between - and EwsAllowList. This whitespace has to be removed.

Wrong Command Example: 
Set-OrganizationConfig - EwsAllowList @{Add="MicrosoftOWSPersonalBookings"}

Correct Command Example: 
Set-OrganizationConfig -EwsAllowList @{Add="MicrosoftOWSPersonalBookings"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings in Outlook](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @ahamin01 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
