### ISSUE TITLE
Role Required to implement the policy and limitation on number of groups

### ISSUE THREAD

**Issue by inagrawalru** [MicrosoftDocs/microsoft-365-docs#8543]
Hi Team,
Please specify the role or license required to configure the policy as the information is missing from the page.

Also, please confirm (maximum) how many groups can be added if policy is configured for specific groups in the tenant.

Regards
Rupali Agrawal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Version Independent ID: 44c73a40-30f1-78f4-9130-37790d58fcda
* Content: [Manage ownerless Microsoft 365 groups and teams - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/ownerless-groups-teams?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/ownerless-groups-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/ownerless-groups-teams.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@inagrawalru Thank you for your feedback. Only global administrators can implement the policy. There are no such limitations for the number of groups. We have made changes to this document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8672 to reflect the same

Thanks
Sri
