### ISSUE TITLE
powershell cmdlet does not work

### ISSUE THREAD

**Issue by Will-Riach** [MicrosoftDocs/microsoft-365-docs#8544]
In the section "Use PowerShell as an alternative method to enable ASR rules".

The powershell cmdlet did not work for me.
`(Get-MpPreference).AttackSurfaceReductionRules_Ids | Foreach {Add-MpPreference -AttackSurfaceReductionRules_Ids $_ -AttackSurfaceReductionRules_Actions AuditMode}`

If I run `(Get-MpPreference).AttackSurfaceReductionRules_Ids` in isolation nothing is returned so nothing is being piped to Foreach. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 498a23d9-d5b0-2c98-edfa-d9871675f5ae
* Version Independent ID: 498a23d9-d5b0-2c98-edfa-d9871675f5ae
* Content: [Test attack surface reduction (ASR) rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-test.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by RAJU2529** [comment]
@Will-Riach , you have not used IDs, in the command, so nothing will happened 

example command 
### Block Adobe Reader from creating child processes
**Add-MpPreference -AttackSurfaceReductionRules_Ids 7674BA52-37EB-4A4F-A9A1-F0F9A1619A2C -AttackSurfaceReductionRules_Actions Audit**

**Comment by Will-Riach** [comment]
Apologies. 
I had misread the previous line "To enable all the **added**" implying I had manually added the ID's in the previous cmdlet.
