### ISSUE TITLE
Download links not valid

### ISSUE THREAD

**Issue by juergsteiger** [MicrosoftDocs/microsoft-365-docs#8547]
The download links are not valid anymore. Please provide the new links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greglin**

**Comment by aczechowski** [comment]
Thanks @juergsteiger for filing the feedback. We're aware of the issue. I'm investigating next steps.

**Comment by aczechowski** [comment]
See https://techcommunity.microsoft.com/t5/windows-11/accessing-trials-and-kits-for-windows-eval-center-workaround/m-p/3361125

We'll update this and other articles soon.

**Comment by aczechowski** [comment]
This article is updated
