### ISSUE TITLE
Spain support hours

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/microsoft-365-docs#8549]
According to Tech Support from Spain, they work until 6pm.

On this page it says they work until 9pm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a6210f0-1f53-aa78-7cbf-16bffbbd67f2
* Version Independent ID: 87fd841d-8f82-d5d0-a769-a99c3eb8ad6e
* Content: [Support information for Spain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/spain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/spain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/spain.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@JMCA2 Thank you for your feedback. We will check this internally and update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@JMCA2 Thank you for your feedback. I was able to reach a tech support representative after 7 PM as well. Looks like the tech support information was incorrect. 

Hope this helps!

Thanks
SRi
