### ISSUE TITLE
Command syntax is incorrect

### ISSUE THREAD

**Issue by ryanmonson** [MicrosoftDocs/microsoft-365-docs#8556]
Several of the commands on this page include '- EwsAllowList' when it should instead be '-EwsAllowList' (no space after the dash).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings in Outlook](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by RAJU2529** [comment]
@yogkumgit , PLease close this issue #8556, because the issue has been fixed by me. Please cross-check it

**Comment by msbemba** [comment]
@yogkumgit The document is up to date and the issue can be closed.

Thanks
Sri
