### ISSUE TITLE
Could be clearer

### ISSUE THREAD

**Issue by alanbmhs** [MicrosoftDocs/microsoft-365-docs#8557]
I get EwsEnabled : False for the Get-Organization command, so what do I do now?
For individual users, I get EwsEnabled : True, so how can it be False for the Org but True for individuals?

I also get blanks on this response for both the Org and individuals -
EwsApplicationAccessPolicy :
EwsAllowList               :
EwsBlockList               :

Not really sure what it means. I just want to turn this feature off.

Alan.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings in Outlook](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by eliaskaplanbromberg** [comment]
To disable 'Bookings in outlook' for all users: use the steps described in 'Turn Bookings in Outlook on or off for your organization using PowerShell', sections 1 and 2.C.
The individual settings, set with set-CASMailbox or default CASMailbox, override the organization wide settings, so EwsEnabled is true, need to add EnforceBlockList and EwsApplicationAccessPolicy  to turn off.
You can use the commands listed in

**Comment by msbemba** [comment]
@alanbmhs Thank you for your feedback. While the organization settings are disabled, you are still allowed to override it for specific users if need be. If you would like to disable this for users you can run the below PS script for individual users 

Set-CASMailbox -Identity Adam -EwsApplicationAccessPolicy EnforceBlockList -EWSBlockList @{Add="MicrosoftOWSPersonalBookings"}

This is updated in document section 2.C as mentioned by @ekaplanb .

If you have trouble and need technical advise while performing this, I'd recommend you contact support via the need help section on the admin center.

Hope this helps!


Thanks
Sri

**Comment by alanbmhs** [comment]
Thanks @ekaplanb and @msbemba for giving me the confidence to do this. I've now turned this off for the tenant.
