### ISSUE TITLE
Download quarantined files feature seems to be GAd already

### ISSUE THREAD

**Issue by morrow233** [MicrosoftDocs/microsoft-365-docs#8562]
Download quarantined files
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-file-alerts?view=o365-worldwide#download-quarantined-files

===========
Files that have been quarantined by Microsoft Defender Antivirus or your security team will be saved in a compliant way according to your [sample submission configurations](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-cloud-protection-microsoft-defender-antivirus?view=o365-worldwide). Your security team can download the files directly from the file's detail page via the "Download file" button. **This preview feature is turned 'On' by default.**
===========

The description calls "Download quarantined files" feature as "preview feature".
According to the tech community, it has already been GAd.
https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/download-quarantined-files-now-generally-available/ba-p/2581160

Please consider to update the description about "preview feature".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d35c168-4704-d96e-15ad-be38fe8f332f
* Version Independent ID: 71ef6707-4191-f1e0-677b-2a4c3515c2b5
* Content: [Take response actions on a file in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-file-alerts?view=o365-worldwide#download-or-collect-file)
* Content Source: [microsoft-365/security/defender-endpoint/respond-file-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/respond-file-alerts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@morrow233 Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8608

Once the author approves,  the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @morrow233 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
