### ISSUE TITLE
Error in step 1 for individual users

### ISSUE THREAD

**Issue by OleksiiH** [MicrosoftDocs/microsoft-365-docs#8563]
[Enter feedback here]
This step (for individual users):
1. Check individual’s EwsApplicationAccessPolicy by running the following command:
Get-CASMailbox -Identity adam@contoso.com | Format-List EwsEnabled

Should be changed to:
1. Check individual’s EWS control access by running the following command.
Get-CASMailbox -Identity adam@contoso.com | Format-List EwsEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings in Outlook](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@OleksiiH Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8609

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @OleksiiH Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
