### ISSUE TITLE
Windows and Office 365 deployment lab kit

### ISSUE THREAD

**Issue by SmuSmu** [MicrosoftDocs/microsoft-365-docs#8567]
Download Links are not working anymore

**Comment by yogkumgit** [comment]
@SmuSmu Please indicate which document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@SmuSmu We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
