### ISSUE TITLE
Error in PS Commands

### ISSUE THREAD

**Issue by angusmclean11** [MicrosoftDocs/microsoft-365-docs#8568]
I found there is an issue with two commands listed in the document where there is a space " " after the dash and before the attribute:

Invalid commands:
Set-OrganizationConfig - EwsAllowList @{Remove="MicrosoftOWSPersonalBookings"}
Set-OrganizationConfig - EwsAllowList @{Add="MicrosoftOWSPersonalBookings"}

Corrected commands:
Set-OrganizationConfig -EwsAllowList @{Remove="MicrosoftOWSPersonalBookings"}
Set-OrganizationConfig -EwsAllowList @{Add="MicrosoftOWSPersonalBookings"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings in Outlook](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by RAJU2529** [comment]
@angusmclean11 . Issue is fixed. It will be reflected within two days in published page.

**Comment by yogkumgit** [comment]
@RAJU2529

**Comment by RAJU2529** [comment]
@yogkumgit close this issue #8568, issue is fixed changes are reflected in article. Please cross it
