### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by Yarli** [MicrosoftDocs/microsoft-365-docs#8571]
The option to convert mailbox to shared doesn't exist anymore in the new exchange admin interface where it's stated.
It's now on the toolbar at the top and not on the action pane on the right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b3fbbe-fde3-fd52-f9cd-d8fca56a1494
* Version Independent ID: 73d71ee8-579d-78b5-a8cd-48d7ec51ebb8
* Content: [Convert a user mailbox to a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/convert-user-mailbox-to-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@Yarli Thank you for your feedback. I will test and update the document accordingly. 

Thanks
Sri

**Comment by msbemba** [comment]
@Yarli Thank you for your feedback. 

The options is moved as below, We have made changes to the document and it is reflecting correctly now. 

Select Recipients > Mailboxes.

Select the user mailbox. In the Others tab, select Convert to shared mailbox.

@yogkumgit  There are no changes and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Yarli Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
