### ISSUE TITLE
Remove an inactive mailbox from a specific location retention policy

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#8577]
Remove an inactive mailbox from a specific location retention policy - cmdlet is incorrect:

Explicit location policies cannot also have exceptions, you must use the following instead of what is currently documented:

_Set-RetentionCompliancePolicy -Identity <retention policy GUID without prefix or suffix> -RemoveExchangeLocation <identity of inactive mailbox>_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c129f4e-664c-971f-e438-18ae3eb87f17
* Version Independent ID: e63b5be8-3c3c-2592-72bf-3f00cca0e525
* Content: [Delete an inactive mailbox - Microsoft Purview](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-an-inactive-mailbox?view=o365-worldwide#remove-an-inactive-mailbox-from-a-specific-location-retention-policy)
* Content Source: [microsoft-365/compliance/delete-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@SeanTGeoghegan  Thank you for flagging the incorrect parameter - now fixed.
