### ISSUE TITLE
Empty machineTags array response with InvalidRequestBody

### ISSUE THREAD

**Issue by PhilippEisenmann** [MicrosoftDocs/microsoft-365-docs#8579]
From the documentation there is stated:

> If machine tags collection in body doesn't contain existing machine tags - replaces all tags with the tags provided in the request body.

IMHO this should include an empty array to remove all tags.

Request is:
`{"machineTags": []}`

But the Response states that this in not possible in a weird error:
`{
    "error": {
        "code": "InvalidRequestBody",
        "message": "Currently supporting only update of: 'tags' and 'deviceValue'",
.....
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de75f8e0-de5a-d4b2-b1ec-b720115ef6ae
* Version Independent ID: 41a298e5-65fe-8a4b-ca34-bb0390005dbd
* Content: [Update machine entity API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/update-machine-method?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/update-machine-method.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/update-machine-method.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@PhilippEisenmann Please indicate which document you are referring to. Thanks

**Comment by PhilippEisenmann** [comment]
@yogkumgit  Sorry for that, I updated the original post.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@PhilippEisenmann Thank you for your feedback. This looks like a bug. If the machine tags are empty, it should replace all tags with the tags in the request body. I'd recommend you contact Microsoft support via the need help section on the admin center, so that a support engineer can work with you and fix the bug on the tenant. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PhilippEisenmann Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
