### ISSUE TITLE
Link for personal bookings

### ISSUE THREAD

**Issue by placido-iv** [MicrosoftDocs/microsoft-365-docs#8582]
Hi,

The link to access personal bookings was removed " **https://outlook.office.com/bookwithme/me**". 

Also, I am having permission error after I enable personal bookings org wide commands. I have waited for almost 1 day and still I am having this issue.
![image](https://user-images.githubusercontent.com/105418731/168025350-3c486a0a-f1b1-4fe6-8ca2-88312525a322.png)

Any advise would help.

Thank you!

https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide#feedback

**Comment by msbemba** [comment]
@placido-iv Thank you for your feedback. This seems to be an issue either with the tenant or the associated mailbox. I'd recommend you contact Microsoft support so the support engineer can fix the issue.

You can reach out to the support team via the need help section on the M365 Admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @placido-iv Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
