### ISSUE TITLE
Zero-touch onboarding of Microsoft Defender for Endpoint

### ISSUE THREAD

**Issue by AndersMaletzki** [MicrosoftDocs/microsoft-365-docs#8583]
[Enter feedback here]
Hello

I was looking trough the documentation, and try to set up "Zero-touch onboarding of Microsoft Defender for Endpoint"
When I get to "Select Add for On Demand Rules and select I want to do the following = Establish VPN, I want to restrict to = All domains."

I don´t see "Establish VPN" in Endpoint Manager. But I see "Connect VPN" my guess is that is the same. 
But not tested yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [App-based deployment for Microsoft Defender for Endpoint on iOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide#zero-touch-onboarding-of-microsoft-defender-for-endpoint)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AndersMaletzki Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
