### ISSUE TITLE
Missing navigation step in documentation

### ISSUE THREAD

**Issue by jonasUMI** [MicrosoftDocs/microsoft-365-docs#8584]
Missing navigation step between
"2. In the navigation pane, choose Settings." and "3. In the General section, select Advanced features."  there should be _Choose endpoints_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0afc1f-2112-050d-2db6-40b14c2149b9
* Version Independent ID: 559af624-9032-7d66-670b-081ce8ac9d44
* Content: [Configure automated investigation and remediation capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jonasUMI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8610

Once the author approves, the changes will be live.

Thanks
Sri
