### ISSUE TITLE
Better licensing table

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/microsoft-365-docs#8588]
Hi, can you please make the table clear to understandard? Like move the name of features on left column and make a checkbox markers in each license suite? Thanks.

**Comment by yogkumgit** [comment]
@Kazzan Please indicate which document you are referring to for the feedback. Thanks

**Comment by Kazzan** [comment]
Hi, sorry. GitHub Mobile somehow do not create the request with all the headers as usual. It is the https://docs.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities?view=o365-worldwide page.

**Comment by msbemba** [comment]
@Kazzan Thank you for your feedback. I'll modify the table and provide you an update.

Thanks
Sri

**Comment by msbemba** [comment]
@Kazzan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8735

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Kazzan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
