### ISSUE TITLE
If we run API explorer to offboard a machine it returns code 200 for success. But the document says its 201 for success. I have checked in lab and the result is same as 200. Customers are getting confused as the article says "If the script runs successfully it will give 201 but the actual success result is 200" can we get this document updated?

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#8592]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05007b38-2a58-d34a-6afb-838e2ddd380e
* Version Independent ID: d0e699b6-abe7-e8f6-a093-ecec52559dec
* Content: [Offboard machine API](https://review.docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/offboard-machine-api?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/offboard-machine-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/offboard-machine-api.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@PremMS-MDE . If possible will you share screenshot of success status code

**Comment by RAJU2529** [comment]
@mjcaparas  Why i couldn't able to view the documentation article page, when i click that page , i received the error, you don't have access to this page.

**Comment by msbemba** [comment]
@PremMS-MDE Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8612

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PremMS-MDE Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
