### ISSUE TITLE
Prerequisites correct?

### ISSUE THREAD

**Issue by SirdiJ** [MicrosoftDocs/microsoft-365-docs#8593]
Hi,

Are the Prerequisites correct for this page ? Defender for business states you can use Web protection, but the prerequisites on this page suggest otherwise as it does not include the Microsoft 365 Business Premium SKU ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbaaa90e-6975-ee29-335a-545cb6a55986
* Version Independent ID: 75c93c17-4952-a13f-ed60-d2baefd0337e
* Content: [Web content filtering](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-content-filtering?view=o365-worldwide#prerequisites)
* Content Source: [microsoft-365/security/defender-endpoint/web-content-filtering.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-content-filtering.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@SirdiJ Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8685

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SirdiJ Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
