### ISSUE TITLE
Missing period

### ISSUE THREAD

**Issue by peterennis** [MicrosoftDocs/microsoft-365-docs#860]
Next, join the APP1 virtual machine to the TESTLAB domain with these commands -&gt; missing period
Add-Computer -DomainName ("testlab." + $yourDomain)

Next, join the CLIENT1 virtual machine to the TESTLAB domain with these commands -&gt; missing period
Add-Computer -DomainName ("testlab." + $yourDomain)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6989d21-f7a7-043b-c91a-cd019a19c0e6
* Version Independent ID: 39e286bc-58fe-768e-ee65-2a2fedf1e544
* Content: [Simulated enterprise base configuration for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise)
* Content Source: [microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/simulated-ent-base-configuration-microsoft-365-enterprise.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@peterennis This has been fixed and republished. Sorry for the inconvenience. Thanks for letting us know.
