### ISSUE TITLE
Undocumented "automated" Defender for Endpoint onboarding method and applicable products confusions

### ISSUE THREAD

**Issue by mikequ-taggysoft** [MicrosoftDocs/microsoft-365-docs#8605]
Two major confusion points after going through a recent deployment:

1.  Doc says it applies to:
Microsoft Defender for Endpoint Plan 2
Microsoft 365 Defender

First of all, what about "Microsoft Defender for Endpoint Plan 1" which is included with M365 E3? Does Plan 1 not need onboarding? I don't think that's the case because the [setup guide for Plan 1](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration?view=o365-worldwide) specifically mentions onboarding and links to this page.

Therefore I believe the "Applies To" section should include P1, and possibly should remove "Microsoft 365 Defender" because the latter is really an umbrella of the various Defender products and this page is specifically about Defender for Endpoint.

2. Doc listed the following onboarding methods for Windows:
Local script (up to 10 devices)
Group Policy
Microsoft Endpoint Manager/ Mobile Device Manager
Microsoft Endpoint Configuration Manager
VDI scripts
Integration with Microsoft Defender for Cloud

But there appears to be a new, automated, yet undocumented onboarding mechanism:

On a brand new M365 tenant I just set up, while visiting the Microsoft 365 Defender Portal at  https://security.windows.com, during the initial setup guide, it provided an option right there to onboard devices currently found in Endpoint Manager, and "automatically onboard future devices".

I wish I took a screenshot of that guide, as after the fact I could not find any doc that mentions it.

But I had it enabled, and checked some time later, and found that all my Azure AD joined + Intune Enrolled devices in Endpoint Manager have been automatically onboarded.

I did NOT have to do anything at all. Did not have to configure any Intune onboarding policy under device configuration profiles. And I cannot find any relevant setting/policy/configuration in neither Endpoint manager portal nor M365 Defender portal regarding this "automated" mechanism. 

Therefore this appears completely undocumented. It's unclear whether we still need the Intune onboarding configuration policy like we did before for future devices. It's also unclear how to view/change this setting after the initial Defender portal setup.

It would be great if the documentation can be updated to clarify all these confusions. Specifically for this "automated" onboarding mechanism,  how does it interreact with the other deployment policies if configured? What is the underlying mechanism/connector that allowed it to happen? How to disable it after the fact if necessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e4b5c5a-10ba-3e0c-af47-c51fa5a7ccc3
* Version Independent ID: 1704fddc-5cda-e55e-3190-74a748ae2e3d
* Content: [Onboard devices and configure Microsoft Defender for Endpoint capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-configure.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
It is documented here: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/security-config-management?view=o365-worldwide

**Comment by mikequ-taggysoft** [comment]
@mjcaparas The doc you posted discusses applying policies to devices via MDE  *after* a device is onboarded into MDE.

My question here is specifically about the onboarding mechanism itself.

Traditionally we had to onboard a device into MDE via one of the following methods such as Intune policy or local script etc as documented here https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-configure?view=o365-worldwide

However, I did not have to do *any* of those things. In other words, I did not take any action to onboard my devices, yet the MD portal automatically onboarded all the devices (which are AAD joined AND full Intune MDM enrolled) simply as part of the first visit, and it said it would "automatically onboard all future devices".

This is the undocumented part that needs clarification.

**Comment by mikequ-taggysoft** [comment]
So it looks like what I encountered was a newer "Microsoft Defender for Business" product that's included with Microsoft 365 Business Premium. The "automatic onboarding" is a unique offering under this sku, documented here:

https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-use-wizard?view=o365-worldwide

The confusing part was, even though our tenant does have some Business Premium licenses, we mostly use Microsoft 365 E3. So it seems when going through the MDE portal for the first time, it detected the existence of M365 Business Premium licenses, and automatically configured our MDE as "Microsoft Defender for Business".

It didn't help that none of these existing MDE docs linked to this new offering. All all these massive amount of Microsoft 365 product SKUs and renamings certainly makes is more challenging, too.

I recommend that you consult with your "Microsoft Defender for Business" doc authors and consolidate all the documentation related to Microsoft Defender under one centralized branch and make it easy to find common as well as sku-specific features.
