### ISSUE TITLE
One SKU has a SkuPartNumber with an issue

### ISSUE THREAD

**Issue by ivassallo19** [MicrosoftDocs/microsoft-365-docs#8606]
Hi, not sure where else to post this.
In our tenancy, we are using a particular SKU:
SkuPartNumber: "CPC_E_2C_8GB_128GB"
SkuId: e2aebe6c-897d-480f-9d62-fff1381581f7
Which is the "Windows 365 Enterprise 2 vCPU 8 GB 128 GB" product.

When processing this SKU in PowerShell, The SkuPartNumber has a character at the end, which causes its default Format-Table output on screen to move the PrepaidUnits value one character to the left.
It also means I cannot hard match it to a predefined string in my code.

I hope you can lookup this SKU and find and correct the SkuPartNumber value.
There may be more SKUs with the same issue, might pay to look at all CPC SKUs.
Feel free to reply here if you require more information from me.

**Comment by ivassallo19** [comment]
I tracked down the character.
It's a Unicode character 8203, which is ZERO WIDTH SPACE, or also referenced as U+200B.

**Comment by yogkumgit** [comment]
@ivassallo19  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ivassallo19** [comment]
"but we haven't had any response from you" ... when did you ask for a response? and to what?

If this should be raised somewhere else, kindly inform me of the correct team to raise this with.

**Comment by yogkumgit** [comment]
@ivassallo19 Apologies. Please indicate the which document you are referring to for this feedback. Thanks

**Comment by ivassallo19** [comment]
The command being used is Get-AzureADSubscribedSku.
The article is:
https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadsubscribedsku?view=azureadps-2.0
However the problem isn't with the article or the command, but the SKU data being returned from Microsoft's side.

**Comment by yogkumgit** [comment]
@ivassallo19 Thank you very much for the reply. Here, we are limited to documentation fixes and improvements only. Considering the nature of the issue please open a service ticket in your tenant and follow with them for the resolution. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
