### ISSUE TITLE
Exchange Online Plan 1 licence

### ISSUE THREAD

**Issue by brianreidc7** [MicrosoftDocs/microsoft-365-docs#861]
This licence reference in the first set of bullet points is very specific - what happens if I have the E3 licence suite, and therefore have Exchange Online Plan 2 licences, or just standalone Exchange Online Plan 2 licences. Does that work as well?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0bb4d7-d9fa-ae92-d3ca-246147d1434a
* Version Independent ID: 7ba20db3-55e2-3d29-2d6c-6f68a6b577a8
* Content: [Searching cloud-based mailboxes for on-premises users in Office 365](https://docs.microsoft.com/en-gb/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users#feedback)
* Content Source: [microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-cloud-based-mailboxes-for-on-premises-users.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@brianreidc7 Yes, that works. You need at least an EXO Plan 1 license. Will update topic to make that clear.
