### ISSUE TITLE
minor error in danish translation

### ISSUE THREAD

**Issue by DrLippert** [MicrosoftDocs/microsoft-365-docs#8615]
just a minor error in the Danish translation in the first paragraph it says 13:1 chats instead of 1:1 
![image](https://user-images.githubusercontent.com/29140398/168622463-6b66b12c-6c68-48e1-9dba-8b635e9bb2e4.png)

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: eb41d287-f954-dc84-782c-de8fa3c1ea0d
* Version Independent ID: 0081aa8b-87dd-aef2-aaeb-61caa8f20351
* Content: [Teams arbejdsproces i eDiscovery (Premium) - Microsoft 365 Compliance](https://docs.microsoft.com/da-dk/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by denisebmsft** [comment]
@TinaMcN Can you take a look?

**Comment by TinaMcN** [comment]
@v-tophillips logged a bug for the translation vendors to fix.  The article is currently machine translated and it's being sent now for human translation which should fix the problem.  @DrLippert thank you for reporting the issue and please let us know if you notice any translation issues in other Danish articles.

**Comment by RAJU2529** [comment]
@TinaMcN i conformed with english article , and i found 
**Teams 1:1 chats** is mentioned, but i could not able to edit danish article.

**Comment by TinaMcN** [comment]
@DrLippert The Danish article has been fixed now.  Thanks again for telling us about the problem.
![image](https://user-images.githubusercontent.com/53281468/169416898-d026e960-30dd-4974-9a66-61f286d40aaf.png)
https://docs.microsoft.com/da-dk/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery?view=o365-worldwide#where-teams-content-is-stored
Please close this issue if it looks ok for you.

**Comment by RAJU2529** [comment]
@TinaMcN . I too checked  now , issue is fixed
