### ISSUE TITLE
Step 3 Important note ambiguity

### ISSUE THREAD

**Issue by StuartHutchison** [MicrosoftDocs/microsoft-365-docs#8618]
Section "(Optional) Step 3: View a list of the PST files uploaded to Microsoft 365". The Important note regarding importing and deleting PST files doesn't make sense. 

PST files cannot be deleted by Storage Explorer, AZCopy, or both? 

Under what circumstances do PST files get deleted? Only the ones imported to the AZCopy target? All PST files in the blob container?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import PST files - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by v-tophillips** [comment]
As the note says, PST files cannot be deleted. It doesn't state anything about using a tool, it says they can't be deleted.
