### ISSUE TITLE
Permissions. Where to grant them?

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/microsoft-365-docs#862]
Do the permission need to be granted in Azure AD or Security and Compliance Center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de70c835-f408-83a6-3cc7-885756bd7152
* Version Independent ID: 076708dd-80e4-39d7-7e23-42730c106900
* Content: [Automated incident response (AIR) in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/automated-investigation-response-office)
* Content Source: [microsoft-365/security/office-365-security/automated-investigation-response-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/automated-investigation-response-office.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @pawp81 and @mypil. Thank you for raising this question. I have updated the article to include details on where the permissions can be assigned. Essentially the Global Admin, Security Admin, or Security Reader roles can be assigned in either Azure Active Directory or in the Office 365 Security & Compliance Center. The Search and Purge role, which is required to approve some tasks like soft deleting email messages, can only be assigned in the Office 365 Security & Compliance Center. I hope this helps! I am going to close this issue out now but please let us know if you have any other questions.
