### ISSUE TITLE
Questions about MRM and subfolder retention policies

### ISSUE THREAD

**Issue by cchambers-cap** [MicrosoftDocs/microsoft-365-docs#8624]
Hi and thanks for writing this document, it was very helpful!

I was wondering if you could provide details on how the inactive mailbox function works on retention policies assigned at the subfolder level in Exchange (are folder level retention policies only assignable via Exchange MRM?)

As an example, an account has a one year retention policy assigned to the entire mailbox (via Purview or MRM) but an indefinite retention policy applied to the native Archive **folder** (not an archive mailbox).

If on the departure date of the staff person, the account is deleted: 
1. Would the mailbox be converted to an Inactive Mailbox if both the mailbox and Archive folder polices were applied via MRM?
2. If the mailbox policy is applied at the Purview level, would the MRM policy applied to the Archive folder still apply and the inactive mailbox would remain in place indefinitely and after one year only contain the messages in the Archive folder?
3. Would email in the mailbox, with the exception the Archive folder, continue to be deleted per the one year retention policy and the email in the Archive remain in place indefinitely as an inactive mailbox? 
4. If the mailbox level one year retention policy is applied when the account is created, does it matter if the policy is applied via MRM or at the Purview/Data Lifecycle Management level?

Thanks so much for any clarification you can provide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b1290-00ae-8f23-1b41-5ca692e6d1c4
* Version Independent ID: ab2acdbd-a620-86de-8544-e655aa386b0a
* Content: [Learn about inactive mailboxes - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/inactive-mailboxes-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@cchambers-cap  I think you'll find the answers to your questions in the section for inactive mailboxes and MRM (https://docs.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide#inactive-mailboxes-and-exchange-mrm-retention-policies):

1. The mailbox would be converted into an active mailbox because of Purview retention. MRM doesn't result in an inactive mailbox.
2-3  The exact answers depend on the configuration of the Purview retention policy - is it configured to retain-only for 1 year, or retain and then delete after 1 year?
4. MRM doesn't result in an inactive mailbox and doesn't enforce retention (only prevent automated deletion), so our recommendation is to use Purview retention for all but 2 scenarios documented here: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#use-retention-policies-and-retention-labels-instead-of-older-features

**Comment by cchambers-cap** [comment]
In this case (and I should have been more specific) the policy deletes email after a year but doesn’t prevent people from deleting email before then. It is in effect "Delete any email older than a year except email that is in the archive folder. Any email can be deleted sooner if desired."

To restate: a Purview retention policy is configured to “only delete items when they reach a certain age” and set to one year.  An MRM retention tag is applied Archive folder that is set to “unlimited” retention period with a delete retention action (in effect anything put in the folder is set to not delete automatically but can be deleted manually).

In this case, on account deletion, would an inactive mailbox be created that would continue deleting email in the account for a year until it was empty except for the Archive folder. The inactive mailbox would remain indefinitely with the emails in the Archive folder because they are not set to delete. Is that correct or does Purview ignore the MRM policy?

The MRM section only mentions tags with a delete or MoveToArchive action, not those that have other actions (or no action as the case may be).

Craig Chambers
(Sent from my phone)
________________________________

**Comment by cabailey** [comment]
Oh, a delete-only retention policy changes everything - that configuration won't result in an inactive mailbox:

The retention settings must be configured to retain content, or retain and then delete content. If the retention action is configured to only delete content, the mailbox won't become inactive when the user account is deleted.

**Comment by cchambers-cap** [comment]
Ah, I was so close to finally having a solution that isn't manually exporting the Archive folder before we delete the account. :)

Thanks for your help and the clarifications!

Craig
________________________________

**Comment by cabailey** [comment]
Closing & we'll have a look at updating that MRM section for other actions (noted)
