### ISSUE TITLE
OMG

### ISSUE THREAD

**Issue by Korbyn72** [MicrosoftDocs/microsoft-365-docs#8625]
I wont use the expletives I want to, but you need to highlight a few things on this page:

a) Bookings is enabled by default in probably most environments, and NOTHING needs to be done.
b) IF you run the command to add MicrosoftOWSPersonalBookings to the EwsAllowList, it ALSO sets the EwsApplicationAccessPolicy to EnforceAllowList, and with it being the ONLY item in the list, other things will break, such as calendaring and presence on any 3PIP device.  I also started seeing odd behavior in my Outlook, but may have been unrelated

An executive with to much authority made the change and at least let me know.  All he read was "to enabled Bookings for an Organization, do this...."  

Perhaps indicate that if the EwsApplicationAccessPolicy is blank/null, then don't do anything.  In my lab environment I didn't even have to do anything with EwsEnabled, it's also blank/null, and Bookings worked just fine.  Only IF EwsApplicationAccessPolicy is set to EnforceAllowList of EnforceBlockList, then Add MicrosoftOWSPersonalBookings to the respective list.

This article is dated a couple years, but the "bonus : Some Common AllowList Items" section at the end gave me an idea of how bad it might have gotten if left in place for too long:
https://blog.meetingroom365.com/how-to-limit-third-party-application-access-to-exchange-office-365-services-via-ewsapplicationaccesspolicy-enforceallowlist-and-enforceblocklist/

It kind of reminds me of the Federated domains list, once you start adding Domains, it blocks everyone else...
K.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings in Outlook](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Korbyn72 Thank you for your feedback. You are right, I have added a note stating that the parameter defines which applications other than Entourage, Mac Outlook, and Outlook can access EWS.

We have also mentioned in the document that Bookings in Outlook is on by default for users with the subscription.

Thanks
Sri

**Comment by HoodedRobin** [comment]
> We have also mentioned in the document that Bookings in Outlook is on by default for users with the subscription.
> 
> Thanks

Will Personal Bookings be enabled by default for organizations that currently have EWS disabled?

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Korbyn72 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
