### ISSUE TITLE
There is no lab guides available anymore for W10

### ISSUE THREAD

**Issue by Turbo974** [MicrosoftDocs/microsoft-365-docs#8628]
Lab Guides seems to have been replaced by lab files (VM etc) when it was updated last week.

**Comment by sysadmininator** [comment]
There also seems to be two separate lab file downloads per environment (Win10 and Win11). One file with a date at the end and another without. They are different sizes as well, so without downloading both and extracting/running each, I am unable to determine which one is the refreshed lab.

**Comment by Turbo974** [comment]
I had tested for Windows 10 Lab. The Windows 10 lab environnment https://download.microsoft.com/download/3/3/a/33a3c7d7-b393-4f78-9b90-2d5eb7fd98e8/Win10_21H1_lab.zip was created in February. The Windows 10 lab Guides https://download.microsoft.com/download/2/9/9/29952cdb-b98d-4f9b-9d6e-9fb49644b0a0/Win10_21H1_Lab_05.12.zip was updated on 11/05. From my understanding, the second linked I provided should be available under the shortcut Windows lab environnment. The previously lab guides to set up the environment have been replaced by it.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Turbo974  Thank you for your feedback. I'm currently checking with the author and provide an update shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
As per https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8714 Closing
