### ISSUE TITLE
Conditional access support for shared channels

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/microsoft-365-docs#8629]
[Hey folks! I'm a bit confused about the conditional access headline here https://docs.microsoft.com/en-us/microsoft-365/solutions/plan-external-collaboration?view=o365-worldwide#conditional-access

More specifically this:

"The following types of conditional access policies are supported with shared channels:

- Policies that are scoped to all guests, external participants, and SharePoint Online cloud apps."

Would you mind elaborating with more details on what you mean in the article as I have been shared the following table from a previous shared channel session.

Thanks!

![thumbnail_IMG_1295](https://user-images.githubusercontent.com/90273807/168772105-28fb57af-5cb8-4c30-9f80-ac216e689691.jpg)

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d542a71-f937-57ad-8bfc-20124a18d8bd
* Version Independent ID: 6d542a71-f937-57ad-8bfc-20124a18d8bd
* Content: [Plan external collaboration with channel conversations, file collaboration, and shared apps](https://docs.microsoft.com/en-us/microsoft-365/solutions/plan-external-collaboration?view=o365-worldwide#conditional-access)
* Content Source: [microsoft-365/solutions/plan-external-collaboration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/plan-external-collaboration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@ChristianJBergstrom there is a typo in the article - the setting is actually called **All guests and external users**. You can find more details about conditional access for external identities in [Authentication and Conditional Access for External Identities](https://docs.microsoft.com/azure/active-directory/external-identities/authentication-conditional-access).

**Comment by ChristianJBergstrom** [comment]
> @ChristianJBergstrom there is a typo in the article - the setting is actually called **All guest and external users**. You can find more details about conditional access for external identities in [Authentication and Conditional Access for External Identities](https://docs.microsoft.com/azure/active-directory/external-identities/authentication-conditional-access).

@MikePlumleyMSFT Hey Mike, yeah I kind of understood that but thanks for confirming. My concern though is more about that particular sentence (and in the article you linked to) that you get the impression that one can use any conditional access policy with direct connect users.

_"Organizations can enforce Conditional Access policies for external B2B collaboration and B2B direct connect users in the same way that they're enabled for full-time employees and members of the organization."_

But as detailed they are limited to the cross-tenant access settings options of the "three Trusts". Trust MFA, Trust compliant device and Trust hybrid join.

**Comment by MikePlumleyMSFT** [comment]
Thanks, @ChristianJBergstrom. I made some updates to clarify that it's only the supported settings listed.

**Comment by yogkumgit** [comment]
@ChristianJBergstrom Thanks for the feedback. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
