### ISSUE TITLE
Inconsistent EDM SIT test results

### ISSUE THREAD

**Issue by amanmcse** [MicrosoftDocs/microsoft-365-docs#8630]
Test results for EDM SIT are not consistent.

1. Uploaded a file and got "No sensitive content was found in data.txt" on the Match results blade. 
2. Uploaded the same file and got the below match results:
![image](https://user-images.githubusercontent.com/33834131/168779353-ba5ccae4-d010-4c24-802b-5b0c1eb63cb8.png)
3. Uploaded the same file again, and got "No sensitive content was found in data.txt" on the Match results blade.

Please add troubleshooting steps for this issue as well. If it is a known issue with EDM SIT test option, please add a note.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30ccbb3e-2f44-1b16-2abc-1f6401ee5ce7
* Version Independent ID: 30ccbb3e-2f44-1b16-2abc-1f6401ee5ce7
* Content: [Test an exact data match sensitive information type - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sit-get-started-exact-data-match-test?view=o365-worldwide#troubleshooting-tips)
* Content Source: [microsoft-365/compliance/sit-get-started-exact-data-match-test.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sit-get-started-exact-data-match-test.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@amanmcse Thank you for your feedback. This sounds more like a bug as the results are inconsistent. This need to be reported to the product group so that they can fix the bug. I'm not sure if you have an internal channel to report it, if not you can report it via a ticket and escalate it to the product group.

Hope this helps!

Thanks
Sri
