### ISSUE TITLE
Deployment lab kit downloads appear to be incorrect

### ISSUE THREAD

**Issue by sysadmininator** [MicrosoftDocs/microsoft-365-docs#8631]
Duplicate of #8628 , but I noticed that issue is missing the required footer/linking details. 

Essentially the issue is that the download links on the page appear to be incorrect. Each pair of lab links now downloads lab files, instead of one for files and one for documents. The two lab downloads are also different sizes and one of them has a date appended to the end of the file name. Without downloading each lab zip and extracting/running, I am unable to determine which one is the refreshed kit. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @cdmm12
* Microsoft Alias: **aaroncz**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@sysadmininator Thank you for your feedback. I'm currently checking with the author and provide an update shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cdmm12 Please help us in resolving this issue.

**Comment by yogkumgit** [comment]
As per https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8714 Closing
