### ISSUE TITLE
Get-SafeLinksPolicy | Format-Table Name,IsEnabled

### ISSUE THREAD

**Issue by MWPatterson2000** [MicrosoftDocs/microsoft-365-docs#8636]
When I use the new version of the module, IsEnabled is no longer working.

PS C:\Temp\> Get-SafeLinksPolicy | Format-Table Name,IsEnabled,IsDefault

Name                                         IsEnabled IsDefault
----                                         --------- ---------
Customer_Safe_Links
Safe Links
Built-In Protection Policy
Strict Preset Security Policy1637335373227
Standard Preset Security Policy1637335358918

**Comment by msbemba** [comment]
@MWPatterson2000 Thank you for your feedback. I was able to reproduce the issue. Isenabled and isdefault are no longer available. Could you please point me to the document with this information I'll be happy to modify it.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and digging deep into it.  @MWPatterson2000 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MWPatterson2000** [comment]
Here is the document, I was away with limited to no internet access for the past 8 days
https://docs.microsoft.com/en-us/powershell/module/exchange/get-safelinkspolicy?view=exchange-ps

**Comment by msbemba** [comment]
@MWPatterson2000 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/office-docs-powershell/pull/9501

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MWPatterson2000 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
