### ISSUE TITLE
Not accessible

### ISSUE THREAD

**Issue by shanecribbs** [MicrosoftDocs/microsoft-365-docs#8637]
This article mentions going to "Evaluation Labs" but doesn't say what site/URL that can be found.  The answer is Microsoft Defender Security Center, but it doesn't appear that site is available any longer as you are immediately redirected to security.microsoft.com and I don't see the Evaluation Lab there.  The instructions to disable redirect don't work either.  Essentially, it appears this feature is now unavailable unless I'm suffering from an environmental/account issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302ee74c-812a-51b2-13e5-7b5daaa411f7
* Version Independent ID: 37fca1db-b257-588f-db65-4d5c6d7fd53f
* Content: [Microsoft Defender for Endpoint evaluation lab](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/evaluation-lab?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/evaluation-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/evaluation-lab.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@shanecribbs Thank you for your feedback. The evaluation lab is available as per the document. The issue you are facing might be related to permissions. I'd recommend you contact Microsoft support via the need help icon on the admin center, so that one of our support engineers will be able to assist you.

 
 
![image](https://user-images.githubusercontent.com/45987684/169961199-8799115a-5f36-496a-86ae-d1f76a07e94e.png)


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @shanecribbs Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
