### ISSUE TITLE
Which role is Needed to this ?

### ISSUE THREAD

**Issue by boivinx7** [MicrosoftDocs/microsoft-365-docs#8638]
I would love to give some admins the roles to manage those without them being Global admin.
But i cannot find the information anywhere.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61e46dd-c1ff-dfec-5e0e-9f2e7251a5c1
* Version Independent ID: 49f69fa9-33e8-373f-a7f9-26b828510fda
* Content: [Manage add-ins in the admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-addins-in-the-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-addins-in-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@boivinx7 and @DMoenks  for the feedback. We have added the information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8701

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @boivinx7 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
