### ISSUE TITLE
*.svc.ms shouldn't be Default

### ISSUE THREAD

**Issue by nickp85** [MicrosoftDocs/microsoft-365-docs#8639]
Based on recent changes to MS Whiteboard storing data in OneDrive and the involvement of a web socket connection from the Whiteboard over to OneDrive to access the data, the URL *.svc.ms under the SPO/ODB section of this document is should be updated. The URL is currently listed as "Default" so no special handling should be required however because of the use of web sockets, a proxy bypass is required for this new Whiteboard functionality to work.

```
<html>
<body>
<!--StartFragment-->

39 | DefaultRequired | No | *.gr.global.aa-rt.sharepoint.com, *.svc.ms, <tenant>-admin.sharepoint.com, <tenant>-files.sharepoint.com, <tenant>-myfiles.sharepoint.com | TCP: 443, 80
-- | -- | -- | -- | --


<!--EndFragment-->
</body>
</html>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. thanks

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. The endpoints data in this article is autogenerated by the Office 365 endpoints web service and cannot be manually edited. I will inform the appropriate engineering team of this issue and request that they go through the process of updating this endpoint in the web service. Once they complete this process, the endpoints should be included in future updates. -Kelley

**Comment by yogkumgit** [comment]
@nickp85 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
