### ISSUE TITLE
Applying a default retention label to all content in a SharePoint library, folder, or document set

### ISSUE THREAD

**Issue by Soulsailor** [MicrosoftDocs/microsoft-365-docs#864]
I notice in the section I reference in the title that you have very recently updated this section to include the following:  
"...(default labels are an E5 feature)..."

I do not understand this addition/change, because there is no way that an end user will know from the document library settings for example that this feature is E5 only, how do you expect to "police" this?
I appreciate that auto classification based on sensitive information types etc is E5 (although I wish it wasn't), but this basic default capability being, from what I can see, moved to E5 seriously impairs typical organisations from getting value from retention labels and ensuring an appropriate level of compliance for their content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ad620-438b-dae8-26df-258406e97152
* Version Independent ID: 6850f86a-00b4-cc5d-b1eb-ae48d5f7025a
* Content: [Overview of retention labels](https://docs.microsoft.com/en-us/microsoft-365/compliance/labels?irgwc=1&OCID=AID2000142_aff_7794_1246483&tduid=(ir__jjq639i0uokfrjlukk0sohz30v2xg6pmujmvvoiu00)(7794)(1246483)((2e469851f6baf3f03dec4038e08f1623)(266696)(1119169)(0001612359090036)())(2e469851f6baf3f03dec4038e08f1623)&irclickid=_jjq639i0uokfrjlukk0sohz30v2xg6pmujmvvoiu00#feedback)
* Content Source: [microsoft-365/compliance/labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/labels.md)
* Service: **o365-seccomp**
* GitHub Login: @LauraWi
* Microsoft Alias: **laurawi**

**Comment by GiantCrocodile** [comment]
I just saw your comment by chance @Soulsailor. Can someone tell me if this applies to the standard, system-generated GDPR policy/labels too? I talk about this feature: https://admin.microsoft.com/Adminportal/Home#/featureexplorer/privacy/Gdpr.

If this important information is provided nowhere in the admin panel (and now just at this spot in the docs) it's very unlikely to be seen by an admin and just caused a support incident raised today because it's not obvious and unexpected if it's even suggested in the basic setup guide of an Office 365 tenant.

**Comment by Soulsailor** [comment]
Anyone from Microsoft got a view on the above question?

**Comment by Soulsailor** [comment]
@giantCrocodile Yes I would have thought it would apply to that feature to as that includes aut-classification and retention disposition which are both (I believe) E5

**Comment by GiantCrocodile** [comment]
Yep and that's clearly not what the admin cp does say @Soulsailor. Quote from the admin cp at https://admin.microsoft.com/Adminportal/Home#/featureexplorer:

> Discover, learn about, and set up services, solutions, and add-ins **included** with your subscription.

I have made the relevant part bold. Beside of that, I found some other issues (either wrong docs or product issues) with labels/classification and their policies in general and thus opened either support incidents or Github issues as the involved CSP was neither able to find a solution. I hope this gets sorted out as soon as possible @Soulsailor.

If I hear back from Microsoft Premier support, I will provide this information in case of relevance to you @Soulsailor.

**Comment by mypil** [comment]
@LauraWi - Can you please share your insights on this issue?

Thank you.

**Comment by LauraWi** [comment]
@Soulsailor To clarify, the recent edit was not a change but rather a clarification to requested by engineering (@robertoyms ) to make explicit that this capability has always been part of Advanced Data Governance. E5 Compliance or the Advanced Compliance add-on would license someone for it. @GiantCrocodile The language in the UX is not always SKU specific and customers may see capabilities they do not have licensed.

**Comment by GiantCrocodile** [comment]
I see and understand this @LauraWi. We will close our service request and the ticket with our CSP now. On the other hand this is quite a big step backwards in the GDPR rating of Office 365 in our point of view. Thus our internal product rating will decrease.

**Comment by Soulsailor** [comment]
@robertoyms @LauraWi I'm sorry but I really don't see how it makes any sense for there to be end-user features in O365 that are license specific that do not have a licensing statement in the UX. Please explain to me how an end user would know this and how on earth are companies meant to police this?

**Comment by GiantCrocodile** [comment]
Do you know if this feature does work as expected if you don't have the proper license assigned to the specific user @Soulsailor? I suspect the admin features cause technical backend issues if you use them without the required license. I'm curious if this happens to the user too or if it gets applied but without any issue or effect. Then the user can't know and the admin is lost with zero feedback from user and the system.

**Comment by gireeshnair-arch** [comment]
Hi i can see this question in closed status. However would like to clarify the confusion around license. As I read here auto apply retention needs users to E5 license. However in my  E3 trial tenant, I tested autoapply retention and it worked nicely. Please note this is for SharePoint and not email, etc. Does that mean this auto apply retention is still in preview? Can someone please shed light on this?
