### ISSUE TITLE
Are there any wrong in the doucument?

### ISSUE THREAD

**Issue by ituff** [MicrosoftDocs/microsoft-365-docs#8646]
https://docs.microsoft.com/en-us/microsoft-365/compliance/auditing-solutions-overview?view=o365-worldwide#audit-standard-1
Audit (Standard)
- Microsoft Purview Business Basic subscription
- Microsoft Purview Apps for Business subscription
- Microsoft Purview Enterprise E3 subscription
- Microsoft Purview Business Premium
- Microsoft Purview Education A3 subscription
- Microsoft Purview Government G3 subscription
- Microsoft Purview Government G1 subscription
- Microsoft Purview Frontline F1 or F3 subscription, or F5 Security add-on
- Office 365 Enterprise E3 subscription
- Office 365 Enterprise E1 subscription
- Office 365 Education A1 subscription
- Office 365 Education A3 subscription

Are you sure these are standalone subscriptions, or they should be:

- Microsoft 365 Apps for Business subscription
- Microsoft 365 Enterprise E3 subscription
- Microsoft 365 Business Premium
- Microsoft 365 Education A3 subscription
- Microsoft 365 Government G3 subscription
- Microsoft 365 Government G1 subscription
- Microsoft 365 Frontline F1 or F3 subscription, or F5 Security add-on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9653a7b1-0227-95d1-6357-b54361d63321
* Version Independent ID: f33fce66-1688-01be-cf76-3a538730c5f9
* Content: [Microsoft Purview auditing solutions - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/auditing-solutions-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/auditing-solutions-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/auditing-solutions-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@ituff Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8686

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ituff Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
