### ISSUE TITLE
Auto approve ZAP actions in AIR (Threat Investigation) playbooks 

### ISSUE THREAD

**Issue by appelboom** [MicrosoftDocs/microsoft-365-docs#865]
Leaving some feedback for two enhancement requests:
1. Email notifications for pending approval actions and;
2. Ability to auto approve PhishZAP.

**Comment by mypil** [comment]
@appelboom - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.
