### ISSUE TITLE
Regarding Two Incorrect Descriptions on This Page

### ISSUE THREAD

**Issue by tfunatani** [MicrosoftDocs/microsoft-365-docs#8650]
Hi experts,
I'm CSS engineer in Japan Azure Security Team.
I found two incorrect descriptions on this page.

1. Network Protection feature is available to users without Microsoft 365 E5 license.
   However on this page, the following statement is included.
   "customers with E5 licenses"

2. "HKLM\Software\Microsoft\Windows Defender" is accessible with only system authority.
   So user cannot edit the registry key using the "reg add" command described on this page.

Based on above, I believe this page should be fixed as follows.

### Before
> ...
> 
> **Network protection troubleshooting**
> Due to the environment where network protection runs, Microsoft might not be able to detect operating system proxy settings.
> In some cases, network protection clients are unable to reach Cloud Service.
> To resolve the connectivity problem, customers with E5 licenses should configure one of the following registry keys:
> ```
> reg add "HKLM\Software\Microsoft\Windows Defender" /v ProxyServer /d "<proxy IP address: Port>" /f
> reg add "HKLM\Software\Microsoft\Windows Defender" /v ProxyPacUrl /d "<Proxy PAC url>" /f
> ```
> ...

### After
> ...
> **Network protection troubleshooting**
> Due to the environment where network protection runs, Microsoft might not be able to detect operating system proxy settings.
> In some cases, network protection clients are unable to reach Cloud Service.
> To resolve the connectivity problem, customers should [configure a static proxy for Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide#configure-a-static-proxy-for-microsoft-defender-antivirus).
> ...

Regards & Thanks,
Tomoya Funatani

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395141e8-be91-e226-24d7-dc136b8f9c5e
* Version Independent ID: 012beed4-1fdb-4f59-9cc4-53ba5e2c8ea2
* Content: [Use network protection to help prevent connections to bad sites](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by RAJU2529** [comment]
@denisebmsft .  Network protection is enabled without a Microsoft E5 license,  I enable it on windows 11 enterprise.

Also when I try to add a proxy server address, I received   access denied error
**reg add "HKLM\Software\Microsoft\Windows Defender" /v ProxyServer /d "145.124.489.155:2332" /f**

![Screenshot 2022-05-19 092738](https://user-images.githubusercontent.com/3296790/169201489-6d67fed4-1513-480e-8e92-9bc9dec563cc.jpg)

So  @tfunatan point is need to be added in this article

**Comment by denisebmsft** [comment]
Thank you @tfunatani for posting this issue. And thank you @RAJU2529 for your notes here. I have opened a work item to get the docs updated (ADO 6070481). Will update this issue as soon as I know more about doc status.

**Comment by tfunatani** [comment]
@RAJU2529-san,
Thank you very much for your support!

@denisebmsft-san,
Are there any updates?

**Comment by denisebmsft** [comment]
Hello @tfunatani @RAJU2529 @yogkumgit. Thank you @tfunatani for posting this issue here. We have updated the article, and you will see the changes rendering live a little later today (around 10:45 AM Pacific Time). I appreciate your feedback! Thank you for helping us improve our documentation!
