### ISSUE TITLE
Adjustment to advanced hunting queries

### ISSUE THREAD

**Issue by LethalRabbit** [MicrosoftDocs/microsoft-365-docs#8652]
The advanced hunting queries provided in the articles don't seem to work to detect devices going into Troubleshooting mode.

The issue is in the following line: 
`| where _tsmodeproperties.TroubleshootingStateChangeReason == "Troubleshooting mode started"`

This results in 0 detections. Detections do work when changing the line to
`| where _tsmodeproperties.TroubleshootingStateChangeReason contains "started"`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Version Independent ID: 445889fc-485e-9d24-aceb-b0c49ed44a32
* Content: [Get started with troubleshooting mode in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-gb/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-troubleshooting-mode.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@LethalRabbit Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8687

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @LethalRabbit Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
