### ISSUE TITLE
Set up device groups

### ISSUE THREAD

**Issue by cybernerd2014** [MicrosoftDocs/microsoft-365-docs#8653]
The instructions for set up device groups does not appear to be correct. 
Settings > Endpoint > Permissions does not exist in my tenant 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0afc1f-2112-050d-2db6-40b14c2149b9
* Version Independent ID: 559af624-9032-7d66-670b-081ce8ac9d44
* Content: [Configure automated investigation and remediation capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by cybernerd2014** [comment]
This is a permission issue so can be closed.

**Comment by ScottBeeson** [comment]
What permission? I am a global admin and a security admin. I have added myself to about a dozen other roles too, but I still do not see this option.

**Comment by cybernerd2014** [comment]
> What permission? I am a global admin and a security admin. I have added myself to about a dozen other roles too, but I still do not see this option.
Permission tied to licensing. Does not appear until endpoint defender plans.
