### ISSUE TITLE
Clarification needed: Maximum number of items for disposition

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#8656]
The article mentions a limit of 16,000,000 items but doesn't indicate what heppens to/with item number 16,000,001.
As the limit is approached, is anyone notified?
What is the suggested action to take as the limit approaches or is reached?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd1c8027-2370-524b-ccce-e5cca0600685
* Version Independent ID: c08eb86e-d979-fe1c-e473-61409fcadbcb
* Content: [Limits for retention policies and retention label policies - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-limits?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-limits.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-limits.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Kindly comment. Thanks

**Comment by cabailey** [comment]
Investigating with engineering - I'm not aware of any notification. @sparkitect, can you clarify why you're asking - for example, you think you're at or near this limit?

**Comment by sparkitect** [comment]
> Investigating with engineering - I'm not aware of any notification. @sparkitect, can you clarify why you're asking - for example, you think you're at or near this limit?

We simply have a customer that is worried they _might_ reach that limit someday and are wanting to know what will actually happen as the limit is neared/reached.

They are also unwilling to incur the costs of us setting up an environment to test it ourselves...

**Comment by cabailey** [comment]
@sparkitect  Thanks for the extra info - understood.  OK, I have an update from engineering:  I'm told that this 16M is based on storage limitations.  It's not exactly 16M but at this point most customers will likely hit the limit very soon. What happens is new items don't get added to the disposition queue. However, nothing is lost and when storage becomes available, they automatically go into the queue. Engineering has a work item to improve this, at which point I'll update the documentation.
