### ISSUE TITLE
Potential correction for P2 license requirement if using Defender for o365. 

### ISSUE THREAD

**Issue by TheLegacyKiwi** [MicrosoftDocs/microsoft-365-docs#8657]
So, I've been researching the MSFT documentation and from as far as I can see, the requirement for a P2 license or any exchange license to be attached to a shared mailbox has been dropped with the only exception being this page. I've also tested this in a lab Env where we used to be required to add 'any' o365 license in order to be able to apply the Defender license, and can confirm that we can now add a Defender for o365 license to a shared mailbox independently. 

Is this correct? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd8b6d7d-1a95-d263-595e-78649069275f
* Version Independent ID: bacc64b9-916b-bb3d-a885-46fe5d096826
* Content: [Remove license from shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/remove-license-from-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/remove-license-from-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/remove-license-from-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@TheLegacyKiwi Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8688

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TheLegacyKiwi Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
