### ISSUE TITLE
Page is improperly linked

### ISSUE THREAD

**Issue by mrmcpowned** [MicrosoftDocs/microsoft-365-docs#8659]
The link to the admin center overview is improperly linked

![image](https://user-images.githubusercontent.com/5028527/169202823-50e00cfa-a89b-4e43-b3d9-413320dedb8f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4f7db9-4faf-03f9-516c-7bb1f6dbac92
* Version Independent ID: 0a2f9a24-76e7-b889-3a75-3e2bbb5aba96
* Content: [Reset passwords - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/reset-passwords?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/reset-passwords.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/reset-passwords.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by RAJU2529** [comment]
@mrmcpowned I will investigate and fix if possible.

**Comment by RAJU2529** [comment]
@KwekuA, Please verify PR #8662  and merge if it is correct.

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @mrmcpowned Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
