### ISSUE TITLE
Add Quarantine Policy Type to recommended actions for strict and standard recommendations

### ISSUE THREAD

**Issue by andrewpEntag** [MicrosoftDocs/microsoft-365-docs#8661]
It is not clear what Quarantine policy Microsoft recommends for a number of email spam actions. For example:

If message is detected as an impersonated user  -----> Recommended action is Quarantine the message. It would be helpful to know what policy would be applied in security presets and what is the recommended quarantine policy. For example AdminOnlyAccessPolicy or DefaultFullAccessPolicy. 

It is also not clear if spam notifications will be turned on for security presets or if they should be turned on as a standard recommendation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@andrewpEntag, fortunately I had a very new E5 tenant, so I was able to check.

Standard and Strict preset security policies use the default quarantine tags that you would expect (AdminOnlyAcessPolicy for malware, Safe Attachments, and high confidence phishing);  DefaultFullAccessPolicy for everything else) as described in the table [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/quarantine-policies#step-2-assign-a-quarantine-policy-to-supported-features). **By definition, those built-in quarantine policies do not have notifications enabled**.

I updated the topic everywhere to talk about my findings.

I've never seen direct guidance on quarantine notifications or not. Verdicts and quarantine for pam, high-confidence spam, bulk. phishing, spoof, user impersonation, domain impersonation, and mailbox intelligence have historically allowed recipient access to those messages in quarantine, so I would see no issues with quarantine notifications for those verdicts.

But, verdicts and quarantine for high confidence phishing, malware, and Safe Attachments have historically not allowed recipient access to those messages/files in quarantine, so I wouldn't feel comfortable using quarantine notifications, unless they're really locked down where users can't hurt themselves (for example, they can only delete the message). I'm told the false positive numbers for these verdicts is super-low if any, so there isn't much benefit from exposing users to these dangerous messages.

OK?

**Comment by andrewpEntag** [comment]
Hi Chris, thanks for confirming that - I suspected that was the case. 

Some feature feedback for the preset settings would be to allow admins to turn on spam notifications for the DefaultFullAccessPolicy when applying the preset. 

Currently, I don't see a way that I could apply the security presets and turn on spam notifications for end users. For some customers it's necessary that they receive daily notifications. Please correct me if I am wrong.

**Comment by chrisda** [comment]
You are correct. You can't modify the built-in quarantine policies, and you can't modify the individual settings in preset security policies to assign a custom quarantine policy where notifications are enabled.

**Comment by yogkumgit** [comment]
@andrewpEntag Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
