### ISSUE TITLE
Typo: "trcaked" (should be "tracked")

### ISSUE THREAD

**Issue by tran-master** [MicrosoftDocs/microsoft-365-docs#8663]
Typo: "All these actions can be **_trcaked_** under the Actions & Submissions > Action center -> History tab (public preview)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: badda2b8-bdb2-0518-18e4-35940e506c9b
* Version Independent ID: b7045ea1-ca2a-5bd3-0149-f7baed6fe6cf
* Content: [Remediate malicious email that was delivered in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365?view=o365-worldwide#msdynttrid=-gV9I_r2i4AxsoAr8PRA79uP2nd0d67sWoIAVnk0ksA)
* Content Source: [microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/remediate-malicious-email-delivered-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by RAJU2529** [comment]
@MSFTTracyP , Please verify PR #8667 and merge if correct.

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @tran-master Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
