### ISSUE TITLE
Resource requirements unclear

### ISSUE THREAD

**Issue by AndrewBlumhardt** [MicrosoftDocs/microsoft-365-docs#8664]
The prerequisites for CPU and RAM are not clearly stated. Is this minimum for the server or is this minimum allocation for MDAV alone?

Cores: 2 minimum, 4 preferred

Memory: 1 GB minimum, 4 preferred  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 944b7b97-efbf-e83d-9330-a825d901819d
* Version Independent ID: 6c49c1c5-a178-0c9d-4768-fef1507b1a55
* Content: [Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@AndrewBlumhardt , i think  minimum system requirements for the Linux server OS

**Comment by msbemba** [comment]
@AndrewBlumhardt Thank you for your feedback. All the requirements mentioned in this document is added under system requirements. So this is the minimum requirement for the server to install Microsoft Defender for Endpoint on Linux.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @AndrewBlumhardt Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
