### ISSUE TITLE
Is it possible to add list of ConfigurationId and ConfigurationName? like Scid 2010 is Turn On MDAV, likewise can we add all the Scid's number and definition for it. Customers have hard time in writing their own queries.

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#8665]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4fe829d-1049-f4fc-5238-792d86f33126
* Version Independent ID: c52c503e-3fd2-9324-8fd2-ad05b91b1930
* Content: [DeviceTvmSecureConfigurationAssessment table in the advanced hunting schema](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-devicetvmsecureconfigurationassessment-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-devicetvmsecureconfigurationassessment-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-devicetvmsecureconfigurationassessment-table.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
Hello, did you try this: You can join this table with the [DeviceTvmSecureConfigurationAssessmentKB](https://docs.microsoft.com/microsoft-365/security/defender/advanced-hunting-devicetvmsecureconfigurationassessmentkb) table using ConfigurationId so you can, for example, view the text description of the configuration from the ConfigurationDescription column of the DeviceTvmSecureConfigurationAssessmentKB table, in the configuration assessment results.

**Comment by PremMS-MDE** [comment]
Hi @schmurky, I tried joining the tables and I am getting SCID's for the one's which is already detected. Customer is looking for something like - all the SCID's and their details.

**Comment by schmurky** [comment]
@tali-ash is AH built for this functionality? (list all SCIDs in the KB)

**Comment by tali-ash** [comment]
@giladmit can you please review this question?

**Comment by giladmit** [comment]
I'm not sure I fully understand the problem.

There are two tables:

1. DeviceTvmSecureConfigurationAssessment - This table contains the configuration assessment results for all SCIDs on all devices.
2. DeviceTvmSecureConfigurationAssessmentKB - This table contains the static metadata per each SCID (title, description, etc.)

The two tables can be used independently, or joined as in the following example, which returns all SCIDs that are part of the 'Security controls' category and are currently misconfigured, along with information from the metadata table like descriptions, risk description, etc.:

DeviceTvmSecureConfigurationAssessment
| where ConfigurationCategory == "Security controls"
| where IsApplicable == true and IsCompliant == false
| join kind=leftouter  (
    DeviceTvmSecureConfigurationAssessmentKB
) on ConfigurationId   
| project DeviceId, DeviceName, ConfigurationId, ConfigurationName, ConfigurationSubcategory, ConfigurationDescription, RiskDescription
