### ISSUE TITLE
Path to MSUPDATE should be included here (otherwise it wont work)

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/microsoft-365-docs#8669]
./msupdate does not work unless you follow the initial sequence:
Open the Terminal application
Enter cd /Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS

after you complete those steps, ./msupdate will work.

I believe providing the path to msupdate should be included in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 092ef512-a100-4be8-8f63-1caaeb9e9559
* Version Independent ID: 5245c257-ea7e-57b9-03d9-bf2b63b3306c
* Content: [Deploy updates for Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-updates?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-updates.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@vboyev-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8689

Once the author approves, the changes will be live.


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @vboyev-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
