### ISSUE TITLE
Check tamper protect status command is incorrect

### ISSUE THREAD

**Issue by timnottom** [MicrosoftDocs/microsoft-365-docs#8678]
The command in the Section is not correct: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tamperprotection-macos?view=o365-worldwide#troubleshooting-configuration-issues

It is now: 
`sudo grep -F '\[{tamperProtection}\]: Feature state:' /Library/Logs/Microsoftmdatpmicrosoft_defender_core.log \| tail -n 1`

It should be:
`sudo grep -F '[{tamperProtection}]: Feature state:' /Library/Logs/Microsoft/mdatp/microsoft_defender_core.log | tail -n 1 `

In the blog post the command is correct: https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/tamper-protection-is-now-available-on-macos/ba-p/3289643

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b466be31-a444-e4f0-f56e-1b514776df63
* Version Independent ID: b466be31-a444-e4f0-f56e-1b514776df63
* Content: [Protect macOS security settings with tamper protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tamperprotection-macos?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/tamperprotection-macos.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tamperprotection-macos.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@mjcaparas , I already fixed this issue in #8666.   it will be reflected within two days.  So please close this issue  #8678,.
