### ISSUE TITLE
Step 1.5

### ISSUE THREAD

**Issue by bryannso** [MicrosoftDocs/microsoft-365-docs#8680]
[Enter feedback here]
After clicking -> Solutions -> Information Protection, click on the "Labels" heading at the top.   THEN you will be presented with the message "Your organization has not turned on the ability"....

Appears content / steps in this document have not been updated for the latest "juice" offered by the Compliance Center ... oops...I mean the "Purview".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0f895e-4e0c-642b-3d74-f31512e555bc
* Version Independent ID: 2e6549c9-35d2-aa32-a03a-fb2ced91e54c
* Content: [Enable sensitivity labels for Office files - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@bryannso Thank you for your feedback. The document has been updated with the extra step to Click on the labels section.

Hope this helps!

Thanks
Sri

**Comment by cabailey** [comment]
Yes, the Overview that made selecting the Labels tab necessary rolled out gradually to tenants - not everybody got this immediately.  I think we can close this issue?

**Comment by bryannso** [comment]
I’m OK with this being closed.   Thank you.

**Comment by yogkumgit** [comment]
@bryannso If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
