### ISSUE TITLE
Menu options don't exist

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/microsoft-365-docs#8681]
I don't see any of these options when I log into my admin account.

Sign in to the [Microsoft 365 admin center](https://admin.microsoft.com/) and choose DirSync Status on the home page.
    Alternately, you can go to Users > Active users, and on the Active users page, choose More > Directory synchronization. On the Directory Synchronization pane, choose Go to DirSync management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7741b68-878f-ae8e-5d1c-07d80c6e888a
* Version Independent ID: 165a1f36-0824-3921-328e-e75ed198e689
* Content: [View directory synchronization status in Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-directory-synchronization-status?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-directory-synchronization-status.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-directory-synchronization-status.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@kelemvor33 Thank you for your feedback. One needs to click on the ellipse to be able to view the option. I have updated the information via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8702

![image](https://user-images.githubusercontent.com/45987684/169962758-3221afb9-c18c-4f31-a2a3-33796adeb9b4.png)

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kelemvor33 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
