### ISSUE TITLE
GCCH o DoD

### ISSUE THREAD

**Issue by contributor-luis** [MicrosoftDocs/microsoft-365-docs#8682]
Hey Team, can we add more information about Safe Link in Microsoft Team is available in GCCH o DoD. 

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@contributor-luis, typically we only call out if something is NOT available in a particular environment (like GCC High are DoD). So you're saying that Safe Links for Teams is (now?) in GCC High and DoD?

**Comment by contributor-luis** [comment]
What I am saying is that Safe Link in Microsoft Team is not available for GCCH and DoD at this moment so, I was working with Product Group on a case about Safe Link in Microsoft Team for GCCH and PG confirms that it is not available yet.

**Comment by chrisda** [comment]
OK. I added a note to the affected topics.

Thanks for the feedback.

Closing
