### ISSUE TITLE
Confirm Collection Age-Out Time

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#8684]
Per discussions with the engineering team, we had confirmed that the Age-Out period of the Azure Blobs that store eDiscovery Premium Collections is 1 year. Meaning any collection created a year ago may no longer be accessible. Can this be confirmed and documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b5b9f-5ee0-cf64-d39a-38f010315b8a
* Version Independent ID: f9bdd1e6-e8e1-eef1-f9ca-b9a2b473dc7d
* Content: [eDiscovery (Premium) limits - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/limits-ediscovery20?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/limits-ediscovery20.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/limits-ediscovery20.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@SeanTGeoghegan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8740

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SeanTGeoghegan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
