### ISSUE TITLE
Regex for German Passport Number wrong

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#870]
According to the docs, this text file content should match:

> reisepass
> F123CPRTV4

When I do validate this via 'Test sensitive info type' in the Security & Compliance center for the sensitive info type 'EU Passport Number' it says no sensitive information found.

A question: Is the regex testing for 'reisepasse' or 'reisepässe'? The first one is not a correct German word but 'reisepässe' would make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c16b548-1fc9-2765-3e8a-7559be41fd9d
* Version Independent ID: 7fe5f4ba-e53d-d86d-4ab9-64e872e33069
* Content: [What the sensitive information types look for](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-sensitive-information-types-look-for#feedback)
* Content Source: [microsoft-365/compliance/what-the-sensitive-information-types-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-sensitive-information-types-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @GiantCrocodile 
These patterns are coded into the service.  I am forwarding this over to the product team, they would have to verify your suggested update and then update it in the code.  The documentation represents what is in the code.

**Comment by GiantCrocodile** [comment]
I can't verify this @chrfox. I understand what you say but if the docs and the product code are equal, then this should trigger but it doesn't trigger.

**Comment by chrfox** [comment]
@GiantCrocodile 
The PG confirms that ‘reisepässe’  is not included as a keyword in the keyword list for German passports.  They have taken this as a bug into their backlog for potential future work.

**Comment by GiantCrocodile** [comment]
What about the regex part 'F123CPRTV4'? Is it a valid German passport id and thus should be detected with supporting keyword 'reisepass'? @chrfox

**Comment by GiantCrocodile** [comment]
Any news on this @chrfox @mypil?

**Comment by GiantCrocodile** [comment]
Anybody able to assist here @chrfox @mypil @robmazz? Premier support is working (unsuccessfully) on this too.

**Comment by GiantCrocodile** [comment]
Support ticket has been escalated with Microsoft Premier team.

**Comment by GiantCrocodile** [comment]
No solution found yet, beside the support being not very useful so far. Ticket is still ongoing with 2nd level engineer.
