### ISSUE TITLE
Screenshots in article

### ISSUE THREAD

**Issue by rodneymhungu** [MicrosoftDocs/microsoft-365-docs#8703]
[Enter feedback here]
To whom it may concern, are the screenshots in this article referring to the right admin portal? As far as I understand there should be screenshots indicating how to set up Teams DLP in the Microsoft Purview compliance portal.

Regards,
Rodney

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaab3f7-d1d4-c649-efe8-f24913da4f3e
* Version Independent ID: c5710ebf-0ca5-ab46-c490-64ebc308defe
* Content: [Data loss prevention and Microsoft Teams - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-microsoft-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-microsoft-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks
