### ISSUE TITLE
maybe put a link to the api explorer into the page for the api explorer

### ISSUE THREAD

**Issue by ChristianW-GKGAB** [MicrosoftDocs/microsoft-365-docs#8705]
maybe put a link to the api explorer into the page for the api explorer, that would make life way easier, I simply cannot find the link for the api explorer and it isn't on this page either, so where is it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6115adaf-b9e9-3af1-f9c4-c512aa90322e
* Version Independent ID: ad2e62f9-daaa-c536-7ec7-323a43d64c43
* Content: [API Explorer in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api-explorer?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/api-explorer.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/api-explorer.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@ChristianW-GKGAB Thank you for your feedback. I have added the information to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8760

You can access API explorer via https://security.microsoft.com/interoperability/api-explorer

Once the author approves,  the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ChristianW-GKGAB Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
