### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by jamvandermeer** [MicrosoftDocs/microsoft-365-docs#8706]
(For viewing security incidents across customer tenants)	Yes	No	No

This should be Yes Yes Yes

![image](https://user-images.githubusercontent.com/16414620/170071794-3ed2c6b1-c7e3-49bd-abe1-a677f337db7b.png)

**Comment by denisebmsft** [comment]
Hello again @jamvandermeer! I have updated the article, and you will see the changes render live a little later this morning. Thank you for helping me improve the documentation!
