### ISSUE TITLE
Incorrect Instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#8709]
The instructions tell us to go to Email & collaboration > Attack simulation training > End-user notifications, but there is not an End-User Notification page tab on the Attack Simulation training page. Please update the instructions to describe where this feature has been moved to. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62182f02-0365-ffc2-b94c-356f59cc2814
* Version Independent ID: 62182f02-0365-ffc2-b94c-356f59cc2814
* Content: [End-user notifications for Attack simulation training - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-end-user-notifications?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-end-user-notifications.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-end-user-notifications.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Yeah, I see a banner on the page that mentions the issue:

![image](https://user-images.githubusercontent.com/33166947/170123754-fa6898c3-d71e-4abe-b5db-1dec3b24f6fb.png)

I updated the affected topics where stuff moved around (see the referenced pull request).

Thanks for the feedback.

Closing
