### ISSUE TITLE
Incorrect download for the Windows 10 lab guide 

### ISSUE THREAD

**Issue by GeeJay-Tech** [MicrosoftDocs/microsoft-365-docs#8714]
I attempted to download the Win 10 lab guide but I ended up with two copies of the lab itself. Can this be amended please. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @cdmm12
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@GeeJay-Tech Thank you for your feedback. I will verify this and update the document if need be.

Thanks
Sri

**Comment by yogkumgit** [comment]
@cdmm12 Please help us in resolving this issue.

**Comment by msbemba** [comment]
@GeeJay-Tech Thank you for your feedback. The windows 10 Lab guide link is https://download.microsoft.com/download/8/5/e/85e007b0-1f3e-460c-bd0a-5a8c6ec490b5/Win10_21H2_guides.zip and the same has been updated in the document

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GeeJay-Tech Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
