### ISSUE TITLE
Microsoft Admin Access

### ISSUE THREAD

**Issue by JessicaLuma** [MicrosoftDocs/microsoft-365-docs#8715]
Hi, I'm trying to contact the Microsoft Support Eng - Data Protection eng team to give me admin access to our company business account. The previous admins are no longer with the company and we have a multitude of licenses that fall under our business subscription.

**Comment by yogkumgit** [comment]
@JessicaLuma Thank you for your message.  Considering the nature of the issue , please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
