### ISSUE TITLE
7 days or 14 days?

### ISSUE THREAD

**Issue by ma261065** [MicrosoftDocs/microsoft-365-docs#8716]
At the top of the document is states: "The search results data is deleted from the Azure Storage location two weeks after it's created."

Further down it states: "If the results of a search are older than 7 days and you submit an export report job, an error message is displayed..."

These statements seem to be contradictory. If they are talking about different things, then this should be made clearer in the documentation. If they are talking about the same thing, then please correct the incorrect value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7c6cc6-acab-cf49-5bd2-00f06e7c3bf4
* Version Independent ID: 37970b6e-c07c-f6cc-d280-dbfd086b3c33
* Content: [Export a Content search report - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/export-a-content-search-report?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/export-a-content-search-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/export-a-content-search-report.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@ma261065 Thank you for your feedback 


For more than 7 days (query start date is more than 7 days)   you need to run a report job and it talks about how to re run. 

The search results data collected is deleted from the Azure Storage location two weeks after it's created.

Hope this clarifies.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ma261065 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
