### ISSUE TITLE
Used Standard for M365 Secure Score

### ISSUE THREAD

**Issue by Bollagm** [MicrosoftDocs/microsoft-365-docs#8717]
On which standard is the Secure Score based upon? Is it possible to customize the secure score with CIS Benchmark, NIST and other like it is possible within the Purview Compliance Portal --> Compliance Manager (Assessment and Templates)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a57c0a2-0a6c-4499-f31e-18016d006549
* Version Independent ID: 5587ca01-e40f-478d-1796-b7b4dc41cbf0
* Content: [Microsoft Secure Score](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-secure-score?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender/microsoft-secure-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-secure-score.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Bollagm Thank you for your feedback. As mentioned in the document Microsoft Secure Score is a numerical summary of your security posture based on system configurations, user behavior, and other security-related measurements. It isn't an absolute measurement of how likely your system or data will be breached. Rather, it represents the extent to which you have adopted security controls in your Microsoft environment that can help offset the risk of being breached. No online service is immune from security breaches, and a secure score shouldn't be interpreted as a guarantee against security breaches in any manner.

It is not possible to customize the secure score. However, If you have any issues, let us know by posting in the [Security, Privacy & Compliance](https://techcommunity.microsoft.com/t5/Security-Privacy-Compliance/bd-p/security_privacy) community. We're monitoring the community and will provide help.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Bollagm Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
