### ISSUE TITLE
Update WVD references to AVD

### ISSUE THREAD

**Issue by ncdlloyd** [MicrosoftDocs/microsoft-365-docs#8723]
Update WVD references to AVD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb9a6dfb-2853-20fc-bd6c-2f636945b328
* Version Independent ID: 60586381-2d76-32bc-8e44-342ee36ada1c
* Content: [Onboard Windows multi-session devices in Azure Virtual Desktop](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-multi-session-device.md)
* Product: **w10**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@ncdlloyd Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8747

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ncdlloyd Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
