### ISSUE TITLE
Report Message or the Report Phishing add-ins for shared mailboxes in EXO.

### ISSUE THREAD

**Issue by riohedfield** [MicrosoftDocs/microsoft-365-docs#8724]
Hello, 

I'm reaching out for some specifications and details about how it's supposed to work between Report Message or the Report Phishing add-ins and shared mailboxes, please help me with this one and if possible to update the article as well so it's becomes clearer for the public:

The article is explicitly mentioning: "Both add-ins are not available for shared mailboxes."

- As per my testing I can report junk or phish messages using OWA with the feature "Open another mailbox"
![image](https://user-images.githubusercontent.com/59142439/170458357-5c41592c-6efd-4d89-bd80-154d27f0fb80.png)

- But nothing happens when I try using the add-ins (the add-ins are there displayed):
![image](https://user-images.githubusercontent.com/59142439/170458692-862e1dea-13b3-4c34-9f93-06adbecc5d6c.png)

- Few days ago the add-ins moved the message to junk folder only but didn't report it.

- When accessing the shared mailbox as a shared folder only this option is currently available and working, add-ins have no effect when clicking on them:
![image](https://user-images.githubusercontent.com/59142439/170462634-1622c13c-c4ed-46a0-805e-89dc3ed3b262.png)

- In Outlook the add-ins aren't even displayed when selecting a shared mailbox. For some other users the add-ins are there but have no effect.

- For a newly auto-mapped shared mailbox the add-ins are displayed for few seconds, can be used, then disappears.

1. What is the exact behavior we should be expecting with the Report Message or the Report Phishing add-ins when managing/dealing with shared mailboxes ?

2. What is the difference between "Security Options" and add-ins ?

![image](https://user-images.githubusercontent.com/59142439/170463672-e2f56310-470d-4dde-b2a2-37ab70d2a550.png)
![image](https://user-images.githubusercontent.com/59142439/170463848-5992e4d2-2e45-4447-9046-9c980719ff18.png)

BR
Ribo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 445892a6-5948-33e4-ce60-72670829d8ef
* Version Independent ID: a7407a6f-6563-9a4b-4a95-7ed908ab322b
* Content: [Enable the Report Message or the Report Phishing add-ins - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/enable-the-report-message-add-in.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/enable-the-report-message-add-in.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@riohedfield Thank you for your feedback. I was able to test all the methods and you are right, we are able to mark it is Junk and Phishing when opened as another mailbox and these are security options that will update your internal anti-spam policy Only.

The Report Message and Report Phishing add-ins for Outlook and Outlook on the web are used to report false positives (good email marked as bad) or false negatives (bad email allowed) to Microsoft and its affiliates for analysis. In other words, if you report a message as junk using the security options, You are updating just the internal policy. However, if you mark it using the Report Message add-in the email is sent to Microsoft for analysis, and your internal policies are also updated.

I could not make the add-in to work on a shared mailbox, so that statement from the document is right, However, there seems to be a bug with an auto-mapped mailbox where it lets the users use the add-in for a few minutes. 

If you find such a bug in design, you can report it to our product group via the main feedback portal - https://feedbackportal.microsoft.com/ or raise a support ticket with Microsoft via the need help section in the admin center. 

Hope this helps!

Thanks
Sri

**Comment by riohedfield** [comment]
Hi @msbemba,

Thank you so much for your detailed answer; on the other hand when you say: 
" if you report a message as junk using the security options, You are updating just the internal policy"

By internal policy you mean the MailboxJunkEmailConfiguration of the shared mailbox right ?

Also I've tested again using the Security Options then Mark as Junk/ Mark as not Junk: 

![image](https://user-images.githubusercontent.com/59142439/174569983-0015f0e9-7520-41b7-845d-e5b9f6a5e80d.png)

and I receive this pop up window:

![image](https://user-images.githubusercontent.com/59142439/174570091-13702d13-ded3-41db-8a39-cbd1a2725638.png)

I click report, and as an admin I receive a copy of the report because my address is used as the Organization's Mailbox, and I guess the Message is as well reported to Microsoft, because the User Reported Message Settings are configured this way:

![image](https://user-images.githubusercontent.com/59142439/174571215-a0b30db5-7662-48d7-9aac-9482fbd48d98.png)

I was aiming for some specifics to be added to the documentation when it comes to shared mailboxes to avoid  confusion and have a better idea how the Add-ins vs Security Options are working.

Thank you 
BR

**Comment by dhairyya** [comment]
@RatulaC and @chrisda shared/delegate reporting is not supported. we are working to fix this no ETA. So when someone reports from it - it moves the email to the folder as we normally do but there is no report to custom mailbox or Microsoft or both.

Security options vs addin should work in the same way in the future. I cannot provide an ETA as different clients are doing development work in different time.

**Comment by chrisda** [comment]
I added the following bullet to the What do you need to know before you begin? section. Feel free to modify:

> Currently, reporting messages in shared mailboxes or other mailboxes by a delegate using the add-ins is not supported. Messages are not sent to the [custom mailbox](https://learn.microsoft.com/microsoft-365/security/office-365-security/user-submission) or to Microsoft. Built-in reporting in Outlook on the web sends messages reported by a delegate to the custom mailbox and/or to Microsoft.

Thanks for the feedback.

Closing
