### ISSUE TITLE
Sensitivity label information is not correct

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/microsoft-365-docs#8725]
[Hello! This is a request to update the current information about sensitivity labels for direct connect users. The information here https://docs.microsoft.com/en-us/microsoft-365/solutions/plan-external-collaboration?view=o365-worldwide#sensitivity-labels says that an external user cannot open a protected document. They can, as long as the label has configured permissions for the direct connect users. 

Thanks!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d542a71-f937-57ad-8bfc-20124a18d8bd
* Version Independent ID: 6d542a71-f937-57ad-8bfc-20124a18d8bd
* Content: [Plan external collaboration with channel conversations, file collaboration, and shared apps](https://docs.microsoft.com/en-us/microsoft-365/solutions/plan-external-collaboration?view=o365-worldwide#sensitivity-labels)
* Content Source: [microsoft-365/solutions/plan-external-collaboration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/plan-external-collaboration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@ChristianJBergstrom Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8759

Once the author approves, the changes will be live.

Thanks
Sri
