### ISSUE TITLE
Risky user log entry from 2018 won't clear... 

### ISSUE THREAD

**Issue by GeorgeAAbraham1** [MicrosoftDocs/microsoft-365-docs#8726]
Occasionally we clear our risky users log.. We still have this one entry from 2018 that won't delete when trying to dismiss it.. it gives an error to try again in a few minutes.. I think it might be an exception that's not handled for a user that no longer exist...  I scanned old google reports and found an identical case.. the poster eventually.. said the feature developer remedied the bug and wanted confirmation from the original poster.. he never replied again.. I guess this one is still a problem. It's either an existing unhandled exception or something that had been remedied to be handled before the onset.. but then not catering for databases that already had entries post fix implementation...  It's just one entry but it would be nice to clear the log without buggy items following you around..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 599ed5bc-d5e1-b53a-ac24-0d327e3af372
* Version Independent ID: 599ed5bc-d5e1-b53a-ac24-0d327e3af372
* Content: [View and manage risky users in Microsoft 365 Lighthouse - Microsoft 365 Lighthouse](https://docs.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-view-manage-risky-users?view=o365-worldwide)
* Content Source: [microsoft-365/lighthouse/m365-lighthouse-view-manage-risky-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lighthouse/m365-lighthouse-view-manage-risky-users.md)
* Product: **microsoft-365-lighthouse**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@GeorgeAAbraham1 Thank you for your feedback. This sounds more like a bug and our support team can fix this from the backend. I'd recommend you create a support ticket via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @GeorgeAAbraham1 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by GeorgeAAbraham1** [comment]
Excellent friendly non service...

This ticket was raised as suggested before.. the technicians wanted to run fiddler on my PC and they are just not happy with whatever I send them.

There is a complete lack of direct conversation and relating to the issue that is not really that complicated to explain even to a developer.


George Abraham
Systems Engineer
Group Information and Communications Technology
Fidelity Services Group

My Helpdesk - Your first port-of-call for IT Service.
https://my-helpdesk.fidelitysecurity.co.za

Direct:          +27-11-697-7531

***@***.***

104D Mimosa Rd, Helderkruin, Roodepoort

Facebook<https://www.facebook.com/ADTsa/> | LinkedIn<http://www.linkedin.com/company/fidelity-security-group> | Twitter<https://twitter.com/fidelityadt>

**Comment by GeorgeAAbraham1** [comment]
I'll try the feedback feature on the Azure page... maybe someone will get to it.


George Abraham
Systems Engineer
Group Information and Communications Technology
Fidelity Services Group

My Helpdesk - Your first port-of-call for IT Service.
https://my-helpdesk.fidelitysecurity.co.za

Direct:          +27-11-697-7531

***@***.***

104D Mimosa Rd, Helderkruin, Roodepoort

Facebook<https://www.facebook.com/ADTsa/> | LinkedIn<http://www.linkedin.com/company/fidelity-security-group> | Twitter<https://twitter.com/fidelityadt>
