### ISSUE TITLE
Controlled Folder Access - Support OS'es - Needs updating

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#8729]
Hi, 

According to this document

https://docs.microsoft.com/en-gb/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#new-windows-server-2012-r2-and-2016-functionality-in-the-modern-unified-solution

Windows Server 2012R2 and Server 2016 now support Controlled Folder Access when onboarded to MDE using the unified solution which is now GA.

This page doesnt reflect this change as it doesnt list these additional Server OS versions as being supported.

Please update and correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fb0d02-ceff-61d8-3041-13df9513769a
* Version Independent ID: 7c98a316-de58-520a-a6ad-06ddaf0d71b3
* Content: [Protect important folders from ransomware from encrypting your files with controlled folder access](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/controlled-folders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/controlled-folders.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @pjrcdf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
