### ISSUE TITLE
Policies applied to nested groups

### ISSUE THREAD

**Issue by desmondgc** [MicrosoftDocs/microsoft-365-docs#873]
If I create an anti-phishing policy applied to members of a group, will it affect only direct members of the group or also to members of nested groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Nested groups are supported in policy scoping, meaning your top level group and its nested folders should get the policy. You should always test periodically if your nesting is extensive, and for peace of mind.
