### ISSUE TITLE
Confusing feature comparisions

### ISSUE THREAD

**Issue by stscholz914** [MicrosoftDocs/microsoft-365-docs#8730]
Under the section "Advantages of Microsoft Purview Message Encryption over legacy OME" it states, "Admins can customize branding, and create multiple branding templates." But under section "Microsoft Purview Advanced Message Encryption capabilities" that Multiple branding templates is a feature of advanced. This is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f151cf2f-052a-67be-8d89-b58b9f2a3058
* Version Independent ID: d06a9563-5a46-e8cf-2833-6fe6df3798cf
* Content: [Message encryption version comparison - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-version-comparison?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/compliance/ome-version-comparison.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-version-comparison.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@stscholz914 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8757

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@stscholz914 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
