### ISSUE TITLE
How to get to the page?

### ISSUE THREAD

**Issue by jrohrich** [MicrosoftDocs/microsoft-365-docs#8731]
This article describes the security operations dashboard but there are no instructions on how to access dashboard in question. I believe this dashboard references the old Defender for endpoint security center which now redirects me to the M365 Defender portal, where this dashboard does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52cf9eaa-c236-18f7-1a55-9707b953859c
* Version Independent ID: 59ee1886-914c-1d7d-ab5c-241efe9e2724
* Content: [Microsoft Defender Security Center Security operations dashboard](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/security-operations-dashboard?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/security-operations-dashboard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/security-operations-dashboard.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@jrohrich Thank you for your feedback. The Dashboards have been retired and there have been changes recently. You can view the changes and their details on https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-center-mde?view=o365-worldwide

I'll work with the author to retire this article.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jrohrich Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
