### ISSUE TITLE
missing information regarding "Send As" permissions and "Show in global address list" parameter

### ISSUE THREAD

**Issue by ViliusS** [MicrosoftDocs/microsoft-365-docs#8732]
This page and probably [this one](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide) is missing information on how "Send As" and "Send on Behalf" permissions work exactly.

You should add a big warning that these permissions *do not work* in *Outlook Desktop client* with "Show in global address list" parameter on the mailbox disabled, since they require that mailbox must be visible in Outlook via GAL (some nonsense right there). OWA and Outlook for Android/iOS will work just fine.

Just spent hours on your support line and debugging it myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db2dbb29-38c4-afe4-bc0d-3bbc195f6288
* Version Independent ID: bcfee113-ecfe-e358-974e-6f9cd76b8d35
* Content: [Create a shared mailbox - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/create-a-shared-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/create-a-shared-mailbox.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by msbemba** [comment]
@ViliusS Thank you for your feedback. We have added a note on both the documents via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8785 and PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8786

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ViliusS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
