### ISSUE TITLE
Incorrect/Missing information

### ISSUE THREAD

**Issue by markembry** [MicrosoftDocs/microsoft-365-docs#8733]
This page is incorrect or missing information.
The section for 'Buy the extra storage add-on'.

3.  There is no 'Next' on the products page even after selecting one of my subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31aa550-3d84-95b8-6a74-b3e7ad1cbfe9
* Version Independent ID: 795391d3-aced-e2f3-f52d-034e14fe1aee
* Content: [Add more SharePoint storage to your subscription](https://docs.microsoft.com/en-US/microsoft-365/commerce/add-storage-space?WT.mc_id=365AdminCSH_spo&view=o365-worldwide)
* Content Source: [microsoft-365/commerce/add-storage-space.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/add-storage-space.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@markembry Thank you for your feedback. I was able to test and see the next button. I'd recommend you contact the support team via the need help option on the admin center so that they can help fix this issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @markembry Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
