### ISSUE TITLE
Bookings FAQ's doesn't mention if online payments can be taken

### ISSUE THREAD

**Issue by OzmeisterO** [MicrosoftDocs/microsoft-365-docs#8736]
[Enter feedback here]
The Microsoft Bookings FAQ page is really helpful, but it doesn't mention anything about linking Bookings to online payments.  I've read a few articles suggesting this used to be an option, but isn't any more - could this be clarified in the FAQ's please (i.e. whether there's anything built-in, or if it can be linked to 3rd-part payment solutions).  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7484dd4-5d94-dd6c-0dbe-551c852677c1
* Version Independent ID: 257d60e2-9313-e08b-dccf-120cb4b30f5b
* Content: [Microsoft Bookings Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-faq?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-faq.yml)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@OzmeisterO Thank you for your feedback. I have added the information to the FAQ section via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8755

There are no built-in or third-party options available as of now. If you would like to see one, I'd recommend you provide feedback directly to our Dev team via the main feedback portal - [Bookings · Community (microsoft.com)](https://feedbackportal.microsoft.com/feedback/forum/e9c7c7d1-011c-ec11-b6e7-0022481f8472)

Hope this helps!

Thanks
Sri

**Comment by OzmeisterO** [comment]
Thanks for the confirmation Sri - much appreciated.

Oz Oscroft
Tel. 07765 668 224
________________________________

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @OzmeisterO Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
