### ISSUE TITLE
Prerequisite item, must be admin in tenant. 

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/microsoft-365-docs#8737]
Tried to do this from my partner account as is the prefered method for accountability so we can track users.
Calendar options not available under org settings.

Logged in as tenant global admin and option for calendar available. 

Sad that once again partners cannot do there job properly with the accounts and tools we have been give.

So if you could add that info to the doc that would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b3bda19-af86-20e8-92c4-ccb0caee7cd2
* Version Independent ID: cc93f793-d8bf-e508-d1c1-ddada942623d
* Content: [Share calendars with external users - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/share-calendars-with-external-users?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/share-calendars-with-external-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/share-calendars-with-external-users.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@webstaff Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8753

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @webstaff Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
