### ISSUE TITLE
Multiple regions in same security filter

### ISSUE THREAD

**Issue by cmateiescu** [MicrosoftDocs/microsoft-365-docs#8741]
Hi there,

The document mentions: "Only one "Region" security filter per user is supported, so all the regions need to be inside the same security filter."

But trying to set multiple regions in the same security filter via powershell fails with error
"The region you specified is invalid, valid values are NAM, APC, EUR, AUS, CAN, JPN, GBR, IND, LAM, FRA, DEU, CHE, ARE,
ZAF, KOR, NOR, BRA."

An example on how to set multiple regions in the same security filter would be great.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebaed282-c3c5-1814-f61c-16505f0925f3
* Version Independent ID: bb9a0fdd-e96d-584e-9298-1f42307c4d7c
* Content: [Configure Microsoft 365 Multi-Geo eDiscovery - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-ediscovery-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/multi-geo-ediscovery-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/multi-geo-ediscovery-configuration.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@cmateiescu  Thank you for your feedback. You are right. I could not add multiple regions as well. Only one region is supported. I have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8752
If it's necessary for an eDiscovery Manager to search across multiple regions, another user account will need to be created for the eDiscovery Manager which specifies the alternate location.

Once the author approves,  the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cmateiescu Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
