### ISSUE TITLE
Microsoft 365 Business Standard missing from licensing?

### ISSUE THREAD

**Issue by secshoggoth** [MicrosoftDocs/microsoft-365-docs#8744]
The licensing requirements section lists out all M365 licenses that have access to Audit Standard and Premium. However, Microsoft 365 Standard is missing from the list, even though Basic and Premium are listed. Does that mean it does not have access to Audit (Standard) or is it missing from the list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9653a7b1-0227-95d1-6357-b54361d63321
* Version Independent ID: f33fce66-1688-01be-cf76-3a538730c5f9
* Content: [Microsoft Purview auditing solutions - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/auditing-solutions-overview?view=o365-worldwide#licensing-requirements)
* Content Source: [microsoft-365/compliance/auditing-solutions-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/auditing-solutions-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@secshoggoth Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8789

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @secshoggoth Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
