### ISSUE TITLE
Windows 10 download guide is unavailable

### ISSUE THREAD

**Issue by GeeJay-Tech** [MicrosoftDocs/microsoft-365-docs#8749]
Hi team, 

Pleae can you fix the download for the Win 10 lab guide because it is the same as the Win 10 lab environment. I need to guide to be able to go through the lab. 

Hope you can fix it soon. 

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @cdmm12
* Microsoft Alias: **aaroncz**

**Comment by yogkumgit** [comment]
As per #8714 Closing
