### ISSUE TITLE
The "last activity date" seems incorrect

### ISSUE THREAD

**Issue by zippy72** [MicrosoftDocs/microsoft-365-docs#8754]
Hello,

Looking at the details for this report, it says that the "last activity date" column refers to "refers to the last time the user performed a read or send email activity". However when running the report, I'm seeing activity dates within the past month, but with no emails either sent or read.

Is there possibly another activity that can update this column that is not documented here?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be45e626-ed67-3f48-1a80-5d69f938638b
* Version Independent ID: de7bbfaa-17fb-01eb-fd74-a854d615dc23
* Content: [Microsoft 365 admin center email activity reports - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/email-activity-ww?view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/email-activity-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/email-activity-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@zippy72 Thank you for your feedback. I'll test this and update the document if need be.


Thanks
Sri

**Comment by msbemba** [comment]
@zippy72 Thank you for your feedback. I have tested it in a dev tenant and it works as described in the document. The  last activity date is matching the date user either sent or read an email.

If this continues to happen to your tenant, I'd recommend you raise a support ticket via the need help section on the admin center to work with a support engineer and file a bug with the Product group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @zippy72 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
