### ISSUE TITLE
Information not specific enough - Encryption in the Microsoft Cloud

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#876]
- What about TLS 1.3 or in general newer TLS than 1.2 (means: TLS > 1.2)? See last paragraph on the site.
- No info about encryption with AES although this article (https://docs.microsoft.com/en-us/office365/enterprise/office-365-sharepoint-online-data-deletion) states that we get more information about that in this article.
- this article (https://docs.microsoft.com/en-us/office365/enterprise/office-365-sharepoint-online-data-deletion) mentions this:

> In SharePoint Online, all content that a customer uploads is broken into chunks, encrypted (potentially with multiple AES 256-bit keys), and distributed across the datacenter.

Is it just one datacenter? I think the data is synced over multiple datacenters. What does potentially mean here? This is too vague.

I think both articles should be updated and clarified with respect to each other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 817fbe87-a720-b940-e27b-3e98b20e68e3
* Version Independent ID: f998f64e-e05a-0ce1-85cd-30bbd537b5ae
* Content: [Encryption in the Microsoft Cloud](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-encryption-in-the-microsoft-cloud-overview)
* Content Source: [microsoft-365/compliance/office-365-encryption-in-the-microsoft-cloud-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-encryption-in-the-microsoft-cloud-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by jer84-c** [comment]
It is his brothers I was trying to get him and his sis away from them she is trying to set me up like my son 5 yrs ago

**Comment by jer84-c** [comment]
She was on my Microsoft

**Comment by 211706183** [comment]
？

**Comment by dstrome** [comment]
Spam comments will be removed without notice.

**Comment by KCCross** [comment]
potentially = one or more. data synced over multiple datacenters for geo.
