### ISSUE TITLE
Very Minor Graphic Change: IP Addresses

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#8763]
The graphic is great and helps explain trusted ARC seals, thank you! 
Could we change IP addresses to contain [.] - not [:] ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f9293f-c337-7af6-e994-336531d62f35
* Version Independent ID: 36f9293f-c337-7af6-e994-336531d62f35
* Content: [Use Trusted ARC senders for legitimate devices and services between the sender and receiver - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@hudish, fixed.

Thanks for the feedback.

Closing
