### ISSUE TITLE
Add the supportability for LTSC

### ISSUE THREAD

**Issue by mmoioli** [MicrosoftDocs/microsoft-365-docs#8765]
As far as I know, Microsoft Defender for Enpoint Plan 1 is supporting also Windows 10 Long Term Servicing Channel (LTSC) and Enterprise IoT.

In this article, only a generic statement is made that the product is supporting "Windows 10, version 1709, or later"

But because the LTSC/IoT version are "special" version and that not all the software and services are supporting them, I suggest to add a specific bullet point for those version like we did in the article related with Defender for Endpoint Plan 2
Article: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide

Windows 10 Enterprise

[Windows 10 Enterprise LTSC 2016 (or later)](https://docs.microsoft.com/en-us/windows/whats-new/ltsc/)

Windows 10 Enterprise IoT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d966a60-ffac-d1b0-4a2c-34bd64edd5ce
* Version Independent ID: da866056-2041-3c18-77c9-05fdd5fa7caa
* Content: [Overview of Microsoft Defender for Endpoint Plan 1](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-plan-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1.md)
* Product: **m365-security**
* Technology: **mdep1**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@mmoioli Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8790

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mmoioli Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
