### ISSUE TITLE
Link Self Service Purchase Articles 

### ISSUE THREAD

**Issue by MartaRosaGomes** [MicrosoftDocs/microsoft-365-docs#8769]
[Hi team,

Can you please add a link for this article https://docs.microsoft.com/en-US/microsoft-365/commerce/licenses/manage-license-requests?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide to the main article about Self Service Purchase FAQs https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/self-service-purchase-faq?view=o365-worldwide ]

Thanks 
Marta 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb58b23-c232-2cd4-f79d-f37f87e41cb1
* Version Independent ID: 90b2a401-0d67-ec60-132d-8c7cc202c325
* Content: [Manage license requests](https://docs.microsoft.com/en-US/microsoft-365/commerce/licenses/manage-license-requests?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/commerce/licenses/manage-license-requests.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/manage-license-requests.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MartaRosaGomes Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
