### ISSUE TITLE
Missing Search admin and Search editor roles

### ISSUE THREAD

**Issue by msharshkum** [MicrosoftDocs/microsoft-365-docs#8774]
This page is missing details about Search Administrator and Search Editor roles.

https://docs.microsoft.com/en-US/azure/active-directory/roles/permissions-reference?WT.mc_id=365AdminCSH#search-administrator

https://docs.microsoft.com/en-US/azure/active-directory/roles/permissions-reference?WT.mc_id=365AdminCSH#search-editor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/add-users/about-admin-roles?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@msharshkum Thank you for your feedback. This document pertains to a set of admin roles that you can assign to users in your organization using the M365 admin center.

As mentioned in the document M365 admin center, it lets you manage Azure AD roles and Microsoft Intune roles. However, these roles are a subset of the roles available in the Azure AD portal and the Intune admin center.

We have added this information to the document in the Before you begin section "if you are Looking for the full list of detailed Azure AD role descriptions you can manage in the [Microsoft 365 admin center](https://go.microsoft.com/fwlink/p/?linkid=2024339)? Check out Administrator role permissions in Azure Active Directory. [Azure AD built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference)" .

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @msharshkum Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by msharshkum** [comment]
Thanks Yogesh and Sriraman!

Thanks,
Harshit

PS: My work hours may not be the same as your work hours. Please do not feel obligated to respond outside of your work hours.



From: Yogesh Kumar ***@***.***>
Date: Tuesday, June 7, 2022 at 4:40 AM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Harshit Kumar ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] Missing Search admin and Search editor roles (Issue #8774)

@msbemba<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmsbemba&data=05%7C01%7Charshkum%40microsoft.com%7Cc5d0e31b9ae947eae61308da487a91e1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637901988533311408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mA08XiPJbG%2FUmTjD6omPrNZz50oWRg1UerWhFVmpQFs%3D&reserved=0> Thank you very much for the contribution and sharing this explanation. @msharshkum<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmsharshkum&data=05%7C01%7Charshkum%40microsoft.com%7Cc5d0e31b9ae947eae61308da487a91e1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637901988533311408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yV%2B2YVm5hAWlN4TZatHa1cL59TK92UYvuynLsbxeK4I%3D&reserved=0> Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
