### ISSUE TITLE
Exchange Online Mailboxes Do Not Store Teams Content

### ISSUE THREAD

**Issue by 12Knocksinna** [MicrosoftDocs/microsoft-365-docs#8776]
[Enter feedback here]

The references made to Teams content being stored in Exchange Online mailboxes are incorrect. This fallacy has been abroad for a while, but it's just plain wrong. The TeamsMessagesData folder in Exchange Online mailboxes holds compliance records created by the substrate for chats and channel messages. These are mail items used by eDiiscovery and other services like Communications Compliance. They are imperfect copies of the actual Teams data, which remains safe and sound in Azure Cosmos DB.

One of the reasons why this is important is that people read that EXO holds the Teams data and assume that when they backup EXO mailboxes, they also backup Teams. Yes, they backup the compliance records, but there's no way to restore compliance records into chat or channel conversation threads.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb41d287-f954-dc84-782c-de8fa3c1ea0d
* Version Independent ID: 0081aa8b-87dd-aef2-aaeb-61caa8f20351
* Content: [Teams workflow in eDiscovery (Premium) - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@v-tophillips Please help us in resolving this issue. Thanks

**Comment by v-tophillips** [comment]
I have verified this with the product team and a fix is in the works, most likely to be published live next week.
