### ISSUE TITLE
Licensing info out of date

### ISSUE THREAD

**Issue by jimvernon** [MicrosoftDocs/microsoft-365-docs#8778]
Today, or sometime between this week and last week, the licensing for Bookings changed. The link on the bookings site takes you to the Bookings documentation, but there's no info about what actually changed. All I know is that I can't get into Bookings with a G1 license like I could previously, and nothing in the documentation specified what license I'd actually need to make Bookings work again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb53eb7-85a1-6aa0-dfd1-e2b54586008a
* Version Independent ID: 5532470a-a47d-e3bd-4e74-02b2c822cae1
* Content: [Microsoft Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-overview?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-overview.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jimvernon Thank you for your feedback. I have tested and Microsoft bookings are not available for the G1 License. We have added the license requirement to the Before you begin section of the document 

Microsoft Bookings is available in the following subscriptions:

Office 365 A3, A5, E1, E3, E5, F1, F3
Microsoft 365 A3, A5, E1, E3, E5, F1, F3, 
Microsoft 365 Business Basic, Business Standard, Business Premium

Hope this helps!

Thanks
Sri
