### ISSUE TITLE
"Messages in deferral remain in our queues for 2 days" > It's 1 day, now.

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#878]
"Messages in deferral remain in our queues for 2 days" &gt; It's 1 day, now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbee98-cf63-76b1-f685-b4f5911e6139
* Version Independent ID: f2e334bc-0965-18a2-80b2-1c26591b01e0
* Content: [EOP features](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/eop-features#feedback)
* Content Source: [microsoft-365/security/office-365-security/eop-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/eop-features.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hudish  OK. Done.

Thanks for the feedback.
