### ISSUE TITLE
Exclude process or process binary - which is more secure?

### ISSUE THREAD

**Issue by foss4ever** [MicrosoftDocs/microsoft-365-docs#8788]
Which is better from a security standpoint:
Excluding a process or the process binary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6bcf39-9a8c-7fa3-803a-508e7b74cc9b
* Version Independent ID: 9fd6d652-df16-7f4b-d253-6aee2362f836
* Content: [Configure and validate exclusions for Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-exclusions?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-exclusions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-exclusions.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@foss4ever Thank you for your feedback. Exclusion of process is better as it excludes the process and all files opened by it.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @foss4ever Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
