### ISSUE TITLE
How long it may take to propagate from the system after published a sensitivity label?

### ISSUE THREAD

**Issue by WayneYangsa** [MicrosoftDocs/microsoft-365-docs#879]
I tested this feature but it's hard to use as the huge time gap between publishing and working. Can you guys help to note how long it may take effective in this document? Meanwhile, can we improve our product by shorting the time it will take to be effective?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Overview of sensitivity labels](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by LauraWi** [comment]
Hi @WayneYangsa The topic specifies that it should take an hour or less: "After you create a label policy and assign sensitivity labels to users and groups, those people will see those labels available in the Office apps in an hour or less."
