### ISSUE TITLE
GPOs don't exist

### ISSUE THREAD

**Issue by BlakeMsft** [MicrosoftDocs/microsoft-365-docs#8793]
The GPO's noted in this docs page do not exist.  Neither GPMC (checked 2019 DC) nor Windows 11 (local gpedit).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f65bc58-aab1-16bb-4a4b-30a21491ca99
* Version Independent ID: ee076a7a-4abb-6664-3c78-735ffaf3fd54
* Content: [Create a custom gradual rollout process for Microsoft Defender updates](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-updates?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-updates.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@yogkumgit , i updated   WindowsDefender.adml  and  WindowsDefender.admx  in windows 11 , but 

**Select gradual Microsoft Defender daily security intelligence updates rollout channel** and  **Disable gradual rollout of Microsoft Defender updates** both are  not available in gpo 

but  Set-MpPreference -DisableGradualRelease is available in PowerShell 

but Set-MpPreference -SignaturesUpdatesChannel is  not available in powershell 
![Screenshot 2022-06-04 075618](https://user-images.githubusercontent.com/3296790/171974700-2c46955c-2073-49ac-bdb2-40a210671c7e.jpg)
![Screenshot 2022-06-04 075844](https://user-images.githubusercontent.com/3296790/171974703-1b58d093-833a-4579-9130-db243712bc0d.jpg)

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @BlakeMsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
