### ISSUE TITLE
External User Retention information needs to be updated

### ISSUE THREAD

**Issue by RogueObsidian** [MicrosoftDocs/microsoft-365-docs#8794]
[Enter feedback here]
This article has conflicting information regarding Teams chats and messages deletion by a retention policy.  

"In this scenario where the Azure chat service receives a delete command because of a retention policy, the corresponding message in the Teams client app is deleted for all users in the conversation. Some of these users might be from another organization, have a retention policy with a longer retention period, or no retention policy assigned to them. **_For these users, copies of the messages are still stored in their mailboxes and remain searchable for eDiscovery until the messages are permanently deleted by another retention policy_**."

The information above conflicts with information here:
https://support.microsoft.com/en-us/office/teams-messages-about-retention-policies-c151fa2f-1558-4cf9-8e51-854e925b483b
That article states the below which conflicts with the original on this page.  Which guidance is correct?
"When you have one-on-one or group chats with people outside your org, message expiration dates are set by the org with the shortest retention policy. Messages are deleted for all members of the conversation."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147f081a-c235-3400-23c9-8b4de7c9bbbc
* Version Independent ID: 0d8958fb-247e-c05b-999e-3cbd93e943c9
* Content: [Learn about retention for Teams - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-teams.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-teams.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@RogueObsidian  The information on this page is accurate and technically detailed for admins.  The other page is for end users and it's trying to simplify an explanation of why messages might disappear ("expire") from the Teams app as a result of another user's retention policy.  It doesn't even need to be from another org, but that seems to be where the most confusion comes in.  Even though the message disappears from the app, for an external user, the message remains in their mailbox and can be searched/found by eDiscovery - but that's not an end user operation.  Do you think an end user needs to know this?  Their experience is limited to seeing a system message in Teams that a retention policy deleted the message.

I see how the wording in the end user article can be misinterpreted.  An admin cannot control when to permanently delete Teams messages for external users, only for users in their own org. However, their retention policies can impact when messages for external users are no longer displayed in the Teams app.

**Comment by yogkumgit** [comment]
@RogueObsidian Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
