### ISSUE TITLE
log file path

### ISSUE THREAD

**Issue by CAT-hs** [MicrosoftDocs/microsoft-365-docs#8796]
In troubleshooting articles like this, I think it would be best to include the default path to log file locations when referencing a log file that should be used in this process, or a link to another article that describes the purpose and default locations for the log file when available. Many people don't know the locations of such log files when searching out troubleshooting steps, if they did they might not be searching for the troubleshooting information to begin with. 

Analyze the Microsoft Protection Log
In MPLog-xxxxxxxx-xxxxxx.log**(WHERE?)**, you can find the estimated performance impact information of running software as EstimatedImpact:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a08b6ae-6445-ab2b-d380-627df46cf3d5
* Version Independent ID: c855d3af-002e-aff2-b2d6-8c6e549850a2
* Content: [Troubleshoot performance issues](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-performance-issues?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-performance-issues.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-performance-issues.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by RAJU2529** [comment]
@CAT-hs  i wil update tomorrow , I found that log file.
