### ISSUE TITLE
Labels configured, but nothing in the UI

### ISSUE THREAD

**Issue by BombPAC** [MicrosoftDocs/microsoft-365-docs#880]
I see the "Site and group settings" option in the sensitivity label configuration UI, but the labels are not appearing in the SharePoint Admin Center or when I create a new Team/SP Site. I've contacted Microsoft Support who are saying that I just need to wait for the public preview to hit my tenant. Is this the case or can anything be "pushed" to my tenant to enable the features?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-gb/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by LauraWi** [comment]
Hi, the information from Support is correct. Thanks.

**Comment by chaitanyasandeep** [comment]
Do you have any target date for this features to be available instead of Public Preview?

**Comment by LauraWi** [comment]
The Microsoft 365 roadmap is our authoritative source for coming features. We try to avoid forecasting release dates within documentation because engineering schedules can change. https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Microsoft%20Information%20Protection
