### ISSUE TITLE
Feedback: Information about the plans and where they are included

### ISSUE THREAD

**Issue by hitem** [MicrosoftDocs/microsoft-365-docs#8800]
Feedback:

Hello, 
Great products and information. But when it comes to licensing its a jungle!
Wouldn't it be possible to get a list of what licenses Plan1 vs Plan 2 are included in ?

Example:
If i have Microsoft 365 E3 and buy Mobility+Security E5 = It includes Plan2
If i have Microsoft 365 E5 or Microsoft 365 E5 Security = It includes Plan2
X license include Plan 1
X license include Plan 1 + Plan 2
etc

When i purchased some plans and checked in Azure -> licenses, all i could see was "Defender for Endpoint" - never anything about plan level. When searching online its very hard to come by this information. It could defiantly be made easier very easily.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec57328d-4b17-abe6-001e-c5ecb2f00746
* Version Independent ID: be98599a-b690-a3e6-c610-8da71fd80d76
* Content: [Compare Microsoft Defender for Endpoint plans](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md)
* Product: **m365-security**
* Technology: **mdep1**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder. Thanks

**Comment by msbemba** [comment]
@hitem Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9138

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @hitem Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
