### ISSUE TITLE
Typo for heading

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/microsoft-365-docs#8809]
The first heading under "Recommended content" has a typo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58067ff3-737e-441e-1812-a50bdb97d832
* Version Independent ID: fa3aba35-e8d9-cff6-13c2-1c892c3f2cc4
* Content: [Bulk complaint level values - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/bulk-complaint-level-values?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/bulk-complaint-level-values.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/bulk-complaint-level-values.md)
* Product: **m365-security**
* Technology: **mdo**
![Snip20220605_6](https://user-images.githubusercontent.com/5389878/172034182-116f2c43-e5d1-422f-9278-152a41d7b217.png)

* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. I think I fixed it. The 'title:' attribute in the topic metadata was using `&apos;` instead of ' ' ' for some reason, so I fixed it.

**Comment by yogkumgit** [comment]
@gb5757870 . Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
