### ISSUE TITLE
Please add Exchange Online Plan 2/SharePoint Plan 2 under requirements for eDiscovery Core 

### ISSUE THREAD

**Issue by bozenektoja** [MicrosoftDocs/microsoft-365-docs#8812]
Hello,

Please add Exchange Online Plan 2/SharePoint Plan 2 under requirements for eDiscovery Core - licenseQ confirmed it is enough. E3 can be confusing because customers don't necessarily have to have full E3, EXO Plan 2 is sufficient for core eDiscovery to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562b6b1d-b0fd-0d65-9db8-37df67bd7035
* Version Independent ID: 92c4403b-0d6b-88aa-74f4-ba3b7640ad00
* Content: [Microsoft Purview eDiscovery solutions - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide#ediscovery-subscription-comparison)
* Content Source: [microsoft-365/compliance/ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@bozenektoja Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8855

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @bozenektoja Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bozenektoja** [comment]
thank you!

Best regards/Pozdrawiam,
Bozena Hutyra
________________________________
Od: Yogesh Kumar ***@***.***>
Wysłane: poniedziałek, 13 czerwca 2022 09:04
Do: MicrosoftDocs/microsoft-365-docs ***@***.***>
DW: bozenektoja ***@***.***>; Mention ***@***.***>
Temat: Re: [MicrosoftDocs/microsoft-365-docs] Please add Exchange Online Plan 2/SharePoint Plan 2 under requirements for eDiscovery Core (Issue #8812)


Closed #8812<https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8812> as completed.
