### ISSUE TITLE
why organization licensing is listed as required along with per-user licensing for standard ediscovery

### ISSUE THREAD

**Issue by bozenektoja** [MicrosoftDocs/microsoft-365-docs#8813]
[Enter feedback here]
Licensing for eDiscovery (Standard) requires the appropriate organization subscription and per-user licensing.
In this article [Get started with eDiscovery (Standard) cases in Microsoft Purview - Microsoft Purview (compliance) | Microsoft Docs](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-core-ediscovery?view=o365-worldwide#step-1-verify-and-assign-appropriate-licenses) it is also indicated that there needs to be two licenses (requires the appropriate organization subscription and per-user licensing. Can this be corrected as well? I understand that my company could potentially have only exo plan 2 to use edisocvery standard and no e3 is needed across the org – correct? If so, this article contains incorrect information (organization subscription and per-user licensing)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1da8786f-5fa8-8787-045b-5ca68d9749b5
* Version Independent ID: 9cf12db3-4a79-62d2-2ef3-bf565fd53a6d
* Content: [Get started with eDiscovery (Standard) cases in Microsoft Purview - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-core-ediscovery?view=o365-worldwide#step-1-verify-and-assign-appropriate-licenses)
* Content Source: [microsoft-365/compliance/get-started-core-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/get-started-core-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@bozenektoja Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8898

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by bozenektoja** [comment]
hello,

apologize, i dont see that as completed - organization licensing with minimnum e3 is still listed alongside per-user subscription:
[cid:4b02e855-c54b-4fae-ae12-d5b81787a4dd]

Best regards/Pozdrawiam,
Bozena Hutyra
________________________________
Od: Yogesh Kumar ***@***.***>
Wysłane: wtorek, 14 czerwca 2022 10:28
Do: MicrosoftDocs/microsoft-365-docs ***@***.***>
DW: bozenektoja ***@***.***>; Mention ***@***.***>
Temat: Re: [MicrosoftDocs/microsoft-365-docs] why organization licensing is listed as required along with per-user licensing for standard ediscovery (Issue #8813)


Closed #8813<https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8813> as completed.

**Comment by bozenektoja** [comment]
yes thank you, but it still says that organizational licenisng with E3 is needed besider the er user licensing.
it says "Licensing for eDiscovery (Standard) requires the appropriate organization subscription and per-user licensing."
so the company would need not only e1 with eop plan 2 and spo plan 2 but also some e3 in the organization. it clearly says "organization subscription AND per-user licensing". will this be corrected as well, please?

Best regards/Pozdrawiam,
Bozena Hutyra
________________________________
Od: Sriraman M S ***@***.***>
Wysłane: wtorek, 14 czerwca 2022 14:43
Do: MicrosoftDocs/microsoft-365-docs ***@***.***>
DW: bozenektoja ***@***.***>; Mention ***@***.***>
Temat: Re: [MicrosoftDocs/microsoft-365-docs] why organization licensing is listed as required along with per-user licensing for standard ediscovery (Issue #8813)


@bozenektoja<https://github.com/bozenektoja> We have updated the per-user licensing via PR##8912<https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8912>

Thanks
Sri

**Comment by msbemba** [comment]
@bozenektoja The per-user licensing is not updated as the PR is not merged. But yes, the document will be corrected once the PR is merged.

**Comment by msbemba** [comment]
PR is Pull request. I have made the changes via PR and once the author approves, the changes will be live.

**Comment by bozenektoja** [comment]
awesome thank you for explanation!

Best regards/Pozdrawiam,
Bozena Hutyra
________________________________
Od: Sriraman M S ***@***.***>
Wysłane: wtorek, 14 czerwca 2022 17:54
Do: MicrosoftDocs/microsoft-365-docs ***@***.***>
DW: bozenektoja ***@***.***>; Mention ***@***.***>
Temat: Re: [MicrosoftDocs/microsoft-365-docs] why organization licensing is listed as required along with per-user licensing for standard ediscovery (Issue #8813)


PR is Pull request. I have made the changes via PR and once the author approves, the changes will be live.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @bozenektoja Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by bozenektoja** [comment]
Hello,

Can you please confirm one more thing: SharePoint Online Plan 2 under organizational subscription is not enough?

Organization subscription: To access eDiscovery (Standard) in the Microsoft Purview compliance portal and use the hold and export features, your organization must have an Exchange online Plan 2 or Microsoft 365 E3 or Office 365 E3 subscription or higher. Microsoft 365 Frontline organizations must have an F5 subscription.


Best regards/Pozdrawiam,
Bozena Hutyra
________________________________
Od: Yogesh Kumar ***@***.***>
Wysłane: czwartek, 16 czerwca 2022 07:06
Do: MicrosoftDocs/microsoft-365-docs ***@***.***>
DW: bozenektoja ***@***.***>; Mention ***@***.***>
Temat: Re: [MicrosoftDocs/microsoft-365-docs] why organization licensing is listed as required along with per-user licensing for standard ediscovery (Issue #8813)


Closed #8813<https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8813> as completed.
