### ISSUE TITLE
Decommissioning Exchange should come with a warning

### ISSUE THREAD

**Issue by stryqx** [MicrosoftDocs/microsoft-365-docs#8814]
Step 8 should have the Note block from the following Section added to it, to remind system administrators that removing Exchange entirely is generally a bad move.
https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-a-staged-migration/perform-a-staged-migration#complete-post-migration-tasks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cce374e-a4bb-ae31-3754-931423541869
* Version Independent ID: 9d5e52c8-1f6a-9b86-49ac-a14022039c33
* Content: [Use PowerShell to perform a staged migration to Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/use-powershell-to-perform-a-staged-migration-to-microsoft-365?view=o365-worldwide#step-8-complete-post-migration-tasks)
* Content Source: [microsoft-365/enterprise/use-powershell-to-perform-a-staged-migration-to-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/use-powershell-to-perform-a-staged-migration-to-microsoft-365.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. Resolved in https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/14513.
