### ISSUE TITLE
Concerning change - do not retire legacy exchange PowerShell commands

### ISSUE THREAD

**Issue by TimD1999** [MicrosoftDocs/microsoft-365-docs#8817]
The retirement of Search-mailbox cmdlet is a concerning change. We use this frequently in conjunction with -deletecontent to search for and delete phishing mails that have landed in inboxes. The removal of this function without an apparent replacement to delete the content found opens our and other organizations to dangerous phishing mails that need to be removed as quickly as possible.

If I have missed the replacement feature to also allow us to quickly remove malicious email using eDiscovery my apologies, however so far I do not see a rapid way to remove malicious emails before employees might click on them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b8bac8-ffc4-8c4c-2d59-f27a96dbd414
* Version Independent ID: b78fa02e-9ae3-fa72-e23a-f70cf96d2e0f
* Content: [Legacy eDiscovery tools retired - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/legacy-ediscovery-retirement.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/legacy-ediscovery-retirement.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@TimD1999 Thank you for your feedback. I was able to perform New-ComplianceSearchAction -Purge command in Security & Compliance PowerShell to delete the message. You can use the below document to use the search and purge feature which replaced the existing search-mailbox cmdlet 

https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @TimD1999 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
