### ISSUE TITLE
Some descriptions still required

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#8824]
Feels like we could do with some clarification around the remaining detection technology in section "In the View data by Email > Phish and Chart breakdown by Detection Technology view, the following information is shown in the chart:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e7112fd-cc48-c218-6e7f-1b8f76644aaa
* Version Independent ID: e285a0da-bcdc-eae7-6bd5-54fe5dab2ef4
* Content: [View email security reports - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-email-security-reports?view=o365-worldwide#threat-protection-status-report)
* Content Source: [microsoft-365/security/office-365-security/view-email-security-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-email-security-reports.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@aldoug, I got everything from this topic:

 <https://docs.microsoft.com/office/office-365-management-api/office-365-management-activity-api-schema#detection-technologies>

Thanks for the feedback.

Closing
