### ISSUE TITLE
Need Clarification on M365 Admin Roles and Blocked One Drive Files 

### ISSUE THREAD

**Issue by jacksondcampbell** [MicrosoftDocs/microsoft-365-docs#8825]
[Hello team, I am with MDA and we need some help with this page. We get a lot of questions about this issue where a file is marked as malicious and why someone cannot unmark it. 
https://support.microsoft.com/en-us/topic/what-to-do-when-a-malicious-file-is-found-in-sharepoint-online-onedrive-or-microsoft-teams-01e902ad-a903-4e0f-b093-1e1ac0c37ad2?ui=en-us&rs=en-us&ad=us

The page I linked above leads to the admin page (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide#notify-users-from-within-the-portal) but it does not specify the admin role needed to monitor files marked as malicious. Can someone please add more information to the admin roles that directly states what role will be able to restore files that are marked as malicious in one drive. As of now it only refers to share point. please help. Or is this not how it is supposed to work? I did see there is a way to submit files as malware and non-malware to M365, is that the only way to address the issue? ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f18d8345-78f3-0b16-f585-1e53f49d138f
* Version Independent ID: 015e98be-2db5-11a3-9abc-6f89b44c3f96
* Content: [About admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/admin/add-users/about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jacksondcampbell Thank you for your feedback. These alerts would show up in  Microsoft 365 Defender The below document has details on what permission one would need to take action on the alert. https://docs.microsoft.com/en-us/microsoft-365/security/defender/investigate-alerts?view=o365-worldwide

Note that the https://support.microsoft.com/en-us/topic/what-to-do-when-a-malicious-file-is-found-in-sharepoint-online-onedrive-or-microsoft-teams-01e902ad-a903-4e0f-b093-1e1ac0c37ad2?ui=en-us&rs=en-us&ad=us is  outdated as it refers to Microsoft 365 Advanced Threat Protection which is now Microsoft defender for Office 365

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jacksondcampbell Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
