### ISSUE TITLE
Missing explanation - Endpoint Security Policy

### ISSUE THREAD

**Issue by PaulBendall** [MicrosoftDocs/microsoft-365-docs#8826]
Under the section [Endpoint Security Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide#endpoint-security-policy) the title is followed by two asterisks. The page doesn't provide an explanation for the asterisks.

It, therefore, isn't clear if the preferred, or current best practice, is to deploy ASR via Intune Device Configuration Profiles or Endpoint Security Policy 

Paul
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@PaulBendall  Thank you for your feedback. We have removed the asterisks as it was creating ambiguity in the recommended approach. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8848

To be clear all the options are available and help enable attack surface reduction rules.  So you can choose whichever works for you, either ASR via Intune Device Configuration Profiles or Endpoint Security Policy.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PaulBendall Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
