### ISSUE TITLE
Win 10 lab guides link is wrong (it is not the guide).

### ISSUE THREAD

**Issue by fmalric** [MicrosoftDocs/microsoft-365-docs#8829]
The "Win 10 lab guides" link in this page is wrong (it is not the guide).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @cdmm12
* Microsoft Alias: **aaroncz**

**Comment by yogkumgit** [comment]
As per https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8714 Closing
