### ISSUE TITLE
Change of ARC text

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#8830]
With the introduction of [Trusted ARC Sealers](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders?view=o365-worldwide), suggesting to revise this statement and remove the text that ARC is not customer-configured.

"ARC is not customer configured, but builds on DMARC to work with forwarding in mailing lists, while recording an authentication chain."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e32e2ed-5ae3-d1c6-6a5b-25b225647dbf
* Version Independent ID: 3f5d0ae5-a9b0-f755-c2f6-c38c75e3e485
* Content: [Step-by-step threat protection stack in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/protection-stack-microsoft-defender-for-office365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@hudish Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8849

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @hudish Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
