### ISSUE TITLE
Isolate device for Windows Server 2012 R2

### ISSUE THREAD

**Issue by mpalumbo7** [MicrosoftDocs/microsoft-365-docs#8831]
This page seems to indicates that Windows 2012 R2 is supported, but I do not believe this to be the case

![image](https://user-images.githubusercontent.com/20686457/172497257-3f1009a7-ef9a-41dc-b764-ae4b4c524681.png)

The following is a screenshot from a device with the following OS:

> Windows Server 2012 R2 64-bit / Version 6.3 / Build 9600

![image](https://user-images.githubusercontent.com/20686457/172497289-431361f1-d0e1-44d0-8d89-1881cb09cf46.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb7742-1171-00f4-ab40-6bcc479078ca
* Version Independent ID: 9a79f573-5f20-0e4c-822e-8af4ebf65422
* Content: [Take response actions on a device in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#isolate-devices-from-the-network)
* Content Source: [microsoft-365/security/defender-endpoint/respond-machine-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/respond-machine-alerts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@mpalumbo7 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8850

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mpalumbo7 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
