### ISSUE TITLE
Incorrect Step 6 Information

### ISSUE THREAD

**Issue by wege4rt34** [MicrosoftDocs/microsoft-365-docs#8832]
Step 6 and beyond needs to be updated for the changes that have been made when creating a search. For example, you can now select "Locations On Hold" but there's no definition article elaborating on what it means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edf6054e-d069-a63c-8b7a-7dbbe98f0748
* Version Independent ID: e9344a15-d168-67e2-925a-004d7e7b187d
* Content: [Search for content in a eDiscovery (Standard) case - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-content-in-core-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-for-content-in-core-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-content-in-core-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Please comment. thanks

**Comment by msbemba** [comment]
@wege4rt34 Thank you for your feedback. I was not able to find locations on hold in an eDiscovery standard case. however, it is available in premium and more information can be found here -https://docs.microsoft.com/en-us/microsoft-365/compliance/managing-holds?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit This can be closed.
