### ISSUE TITLE
'Authenticated telemetry' missing

### ISSUE THREAD

**Issue by rfellmann** [MicrosoftDocs/microsoft-365-docs#8833]
The MDE advanced feature 'Authenticated telemetry' is missing completely in the documentation. 

![image](https://user-images.githubusercontent.com/17169344/172561965-daaa3154-85bd-486b-abfd-ca9bbb0504df.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3c074f5-bd58-6b72-d891-3d9fe0118767
* Version Independent ID: 2eea3a11-be82-49bc-6056-f4fba30bd638
* Content: [Configure advanced features in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-features?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/advanced-features.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/advanced-features.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@rfellmann Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8851

Once the author approves, the changes will be live.

Thanks
Sri
