### ISSUE TITLE
Visibility issue

### ISSUE THREAD

**Issue by snowshed** [MicrosoftDocs/microsoft-365-docs#8837]
It appears that MS does not put Visual Accessibility very high on their priorities.   Page is hard to read due to the"dark" theme.  As is the the white text on green submit button on tis page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e0a301-df45-adc1-14f6-3c9a31661d66
* Version Independent ID: 5e970966-d442-2019-29da-daeacecd8a0e
* Content: [Microsoft Defender Antivirus in Windows](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @snowshed and thank you so much for the feedback. I'll pass this along to our team who manages GitHub for our group. As this doesn't seem to be a specific issue with the article about Microsoft Defender Antivirus, I am going to close it for now. Does the page render better for you if you don't use the dark theme? Thanks again for your feedback.
