### ISSUE TITLE
Fix broken link to Microsoft Security blog

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#8839]
Microsoft security blog link goes to Windows blog. Please link to https://www.microsoft.com/security/blog/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a146b0-2b14-817e-a6c0-fe1b94f6d169
* Version Independent ID: 70a146b0-2b14-817e-a6c0-fe1b94f6d169
* Content: [Phishing trends and techniques](https://docs.microsoft.com/en-us/microsoft-365/security/intelligence/phishing-trends?view=o365-worldwide)
* Content Source: [microsoft-365/security/intelligence/phishing-trends.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/intelligence/phishing-trends.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by denisebmsft** [comment]
Thank you so much for letting us know about this issue. I've fixed the link and you'll see the fix rendering live on the site tomorrow.

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @hudish Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
