### ISSUE TITLE
Screenshot displays the wrong option selected

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#884]
Instructions: 9. Choose Apply label to content that matches a trainable classifier.
Pictured: [selected] Apply label to content that contains sensitive info

Some readers may not notice the distinction between the instructions given and the picture shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c01c82c-a7f4-b3bb-226e-8e527d12268d
* Version Independent ID: 832c60f6-4bff-3ba6-d014-6925ac18772e
* Content: [Using a ready to use classifier (preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-using-a-ready-to-use-classifier)
* Content Source: [microsoft-365/compliance/classifier-using-a-ready-to-use-classifier.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-using-a-ready-to-use-classifier.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
fixed, published
