### ISSUE TITLE
Omission in table data?

### ISSUE THREAD

**Issue by koike-a** [MicrosoftDocs/microsoft-365-docs#8843]
[Enter feedback here]
section: Endpoint activities you can monitor and take action on
In the following table, are "Create Item" and "Rename Item" supported or not on Mac OS?

<html>
<body>

Activity | Description | Windows 10 1809 and later/ Windows 11 | macOS Catalina 10.15 | Auditable/restrictable
-- | -- | -- | -- | --
-- | -- | -- | -- | --
create an item | Detects when a user creates an item | supported |   | auditable
rename an item | Detects when a user renames an item | supported |   | auditable

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 820cb23f-f33d-241d-5ce2-1d824bcd3747
* Version Independent ID: 36d24f60-27b6-f2c1-ccda-1b49a1d4f073
* Content: [Learn about Endpoint data loss prevention - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-learn-about?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@koike-a Thank you for your feedback. macOS Catalina 10.15 detects when a user creates or renames an item. This has been updated in the document.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @koike-a Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
