### ISSUE TITLE
Some information doubled or on wrong domain.

### ISSUE THREAD

**Issue by ragecc** [MicrosoftDocs/microsoft-365-docs#8844]
Has information that looks like it belongs on microsoft.de. Also .de is missing from the onmicrosoft domain in the last section about not being able to remove it.

Here are the sections:
Why do I have an "onmicrosoft.com" domain?
Why do I have an "onmicrosoft.de" domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a11050-b442-7a48-0d37-9bce8908fc14
* Version Independent ID: 5456e564-2629-cfc2-dfc9-2b7934fcf43a
* Content: [Domains Frequently Asked Questions](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?redirectSourcePath=%252farticle%252f5481401f-7771-490e-b728-b3a81305a32e&view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/domains-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/domains-faq.yml)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@ragecc Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8853

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by efrene** [comment]
Hi Srinam,
I can follow up on the changes today. I will remove the duplicate section titled "Why do I have an "onmicrosoft.de" domain?"
Thanks,
Efren
