### ISSUE TITLE
Are response actions not available on Windows Server 2012 R2 and Windows Server 2016 where Defender for Endpoint is now enabled

### ISSUE THREAD

**Issue by tanves** [MicrosoftDocs/microsoft-365-docs#8847]
There is an Important note on the document which states as below:

"Important

These response actions are only available for devices on Windows 10, version 1703 or later, Windows 11, Windows Server 2019, and Windows Server 2022."

With the Defender for Endpoint product now generally available for Windows Server 2012 R2 and Windows Server 2016, will response actions not work on these servers where organisations/users have deployed or onboarded the servers to Defender for Endpoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb7742-1171-00f4-ab40-6bcc479078ca
* Version Independent ID: 9a79f573-5f20-0e4c-822e-8af4ebf65422
* Content: [Take response actions on a device in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/respond-machine-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/respond-machine-alerts.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@tanves Thank you for your feedback. Looks like the response action is not available in 2012 R2 and 2016.

Tested with the OS and get the below 

![image](https://user-images.githubusercontent.com/45987684/172838674-7796ea75-b99c-43c3-8960-cf39a292b7b9.png)

We will update once it is made available.

Hope this helps!

Thanks
Sri
