### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/microsoft-365-docs#885]
Early in the document, under anti-spam, anti-malware and anti-phish settings for EOP:

The default is currently 7 but we recommend that most organizations mvoe it down to at least 6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Office 365 ATP security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, etc](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp#feedback)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@gregmilligan - Thank you for pointing this out.

Created PR #889 to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!
