### ISSUE TITLE
Doesn't answer the question "How do I allow external forwarding"

### ISSUE THREAD

**Issue by ChaosFreak** [MicrosoftDocs/microsoft-365-docs#8857]
This article provides lots of background information, but doesn't answer the question "Where do I go in the Admin console to allow a user to forward externally?" It doesn't even link to this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43299e41-87fe-d6f1-20f7-83791d8ef90b
* Version Independent ID: e5e69845-7040-f5b7-b922-e2d2fd9a7d5e
* Content: [Configuring and controlling external email forwarding in Microsoft 365. - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/external-email-forwarding.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/external-email-forwarding.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by DMoenks** [comment]
The article links to [Configure outbound spam filtering in EOP](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-the-outbound-spam-policy?view=o365-worldwide) at the end of the initial section. The linked article explains the necessary steps for both the Defender portal and Exchange Online PowerShell module.

**Comment by ChaosFreak** [comment]
Yes, but the referenced article is also only a generic discussion of spam rules in general, and not specific to the question of "How to allow external forwarding."
What you really need is something like this:
[https://docs.helpscout.com/article/1424-enable-external-forwarding-in-microsoft-365](https://docs.helpscout.com/article/1424-enable-external-forwarding-in-microsoft-365)
It's a perfect, step-by-step instruction manual to doing this specific task.

**Comment by msbemba** [comment]
@ChaosFreak Thank you for your feedback. The article before this (as mentioned by @DMoenks ) talks about how to configure outbound spam policies and it talks in detail not just about forwarding but other features as well. Adding this information to https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/external-email-forwarding?view=o365-worldwide will mean that it is duplicated in two successive documents.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ChaosFreak Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
