### ISSUE TITLE
GCC Support for SMS?

### ISSUE THREAD

**Issue by spikedfuel** [MicrosoftDocs/microsoft-365-docs#8873]
[Enter feedback here]

Will you be adding GCC support for SMS reminders?
![gccsms](https://user-images.githubusercontent.com/41805678/172942870-0287dc52-8d39-4c57-a1f8-94fdf65cbead.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f1236b-050e-d7b5-ea59-3de650155607
* Version Independent ID: fc058c80-e7c4-1a26-cbc3-d33fc2282e13
* Content: [Define your Bookings service offerings](https://docs.microsoft.com/en-us/microsoft-365/bookings/define-service-offerings?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/define-service-offerings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/define-service-offerings.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@spikedfuel Thank you for your feedback. This needs to be routed to the product team to be able to answer the question. You can leave feedback on our Bookings feedback portal - [Bookings · Community (microsoft.com)](https://feedbackportal.microsoft.com/feedback/forum/e9c7c7d1-011c-ec11-b6e7-0022481f8472) and one of our Dev/Prodcut team member will be able to provide you the details.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@spikedfuel Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
