### ISSUE TITLE
This phone number is barely usable: 1 800 865 9408

### ISSUE THREAD

**Issue by cohortswitchback** [MicrosoftDocs/microsoft-365-docs#8874]
This phone number is barely usable: 1 800 865 9408
It is a purely computerized answering service, but the AI and voice recognition is legacy and the system can barely understand audible commands and doesn't allow button options as a fall back. This system should be retired or forwarded to [, or instructions should be given to call,] **1 855-270-0615** (the business sales line) and follow the prompts for existing Microsoft customers which lets you choose some different support options. At this point, a Microsoft customer advocate gets on the line and can open a support case.

Sincerely,

Ernst von Harringa
ernst@aurtech.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d32f1ee8-5c57-e0b8-2632-1e7b2a9c06ff
* Version Independent ID: 5e1fd1e7-396a-58ca-31f2-2da3beb6aff6
* Content: [Support information for United States - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/united-states?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/united-states.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/united-states.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@cohortswitchback Thank you for your feedback. I was able to connect to a tech support by dailing1 800 865 9408. Note that 1 855-270-0615 is a sales line and not just for tech support. If you still have any specific issues with 1 800 865 9408, let us know.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @cohortswitchback Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
