### ISSUE TITLE
Defender Store App URL not opening in the Google Play application, instead it open in browser.

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/microsoft-365-docs#8876]
For the Defender Store App URL: [https://play.google.com/store/apps/details?id=com.microsoft.scmx](https://play.google.com/store/apps/details?id=com.microsoft.scmx)

This will open a browser to the google play store where I can try to install Defender, however, when I tap on Install and go through the due process of attempting to install the application (authenticating with my Gmail and choosing the device to install it in), it then takes me back to the same URL page in the browser and nothing happens.

I found that the only way for this to work is if I go, in the default browser app for Android, to the arrow as seen in the screenshot (top right corner):

![image](https://user-images.githubusercontent.com/5460795/172980594-88ac17d1-1059-46e2-b947-7829ec721cdc.png)

This will open up in the actual Google Play application on my phone where I can actually download and install Defender

Is there any way that this URL can open through the Google Play app in the phone instead of the browser? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60db9275-9265-ebca-a145-3a3eede2353a
* Version Independent ID: 9d19ab3c-eb32-4211-14d9-559998589eb3
* Content: [Deploy Microsoft Defender for Endpoint on Android with Microsoft Intune](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/android-intune?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/android-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/android-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by RAJU2529** [comment]
@Rykimaruh .Just now I installed Microsoft defender through Google Play Store from india County.
