### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by kathleenlgo** [MicrosoftDocs/microsoft-365-docs#8878]
There are duplicate bullet points in the "Pre-trained classifiers" section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c01c82c-a7f4-b3bb-226e-8e527d12268d
* Version Independent ID: 832c60f6-4bff-3ba6-d014-6925ac18772e
* Content: [Learn about trainable classifiers - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-learn-about?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/classifier-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@kathleenlgo Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8895

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kathleenlgo Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
