### ISSUE TITLE
Specified menu/screens not found

### ISSUE THREAD

**Issue by ScottBeeson** [MicrosoftDocs/microsoft-365-docs#8882]
This article directs me to two items that do not exist on security.microsoft.com

1. "Automatically Resolve Alerts" setting
It says to go to Settings, Endpoints, Advanced Features and turn on "Automated Investigation" and "Automatically resolve alerts" The first toggle exists but the second does not.
2. Set up device groups
It directs me to Settings then Permissions then Device Groups. First of all, there is no "Permissions" page under settings. There is a Permissions page at the top level, but I don't see "device groups" anywhere on security.microsoft.com. 

The closest thing listed to a prerequisite is one of 3 licenses. I have trials or full licenses for all 3. (Microsoft 365 Defender, Microsoft Defender for Endpoint Plan 2 and Microsoft Defender for Business)

I cannot figure out how to configure AIR capabilities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0afc1f-2112-050d-2db6-40b14c2149b9
* Version Independent ID: 559af624-9032-7d66-670b-081ce8ac9d44
* Content: [Configure automated investigation and remediation capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation?view=o365-worldwide#set-up-device-groups)
* Content Source: [microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-automated-investigations-remediation.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@ScottBeeson  Thank you for your feedback. I will update the document with updated screenshots.

Thanks
Sri

**Comment by msbemba** [comment]
@ScottBeeson Thank you for your feedback. I was able to follow the document and navigate without any issues. The options do exist. 

![image](https://user-images.githubusercontent.com/45987684/178965806-94323f2d-0f53-4017-a08c-6732a42963d5.png)


If you are still having any issues locating these options, I recommend contacting Microsoft support via the need help section in the Admin center. That way, a support engineer can identify why the options do not exist for your tenant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ScottBeeson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
