### ISSUE TITLE
The images shown in the solution catalog are out of date

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#8886]
The images shown for the solution catalog are out of date.
For Information protection & governance. Information governance is now data lifecycle management
![image](https://user-images.githubusercontent.com/69439002/173207302-9dcd9503-7a9d-45df-96b8-20965249d51a.png)

Insider risk includes Information barriers
![image](https://user-images.githubusercontent.com/69439002/173207335-a4aee8bd-b43c-4739-b211-7481b1ae4bed.png)

Discovery and response no longer has Data Investigations
![image](https://user-images.githubusercontent.com/69439002/173207361-2801e048-de8b-499c-944e-7b0f51867678.png)

Privacy is a new section that includes privacy management
![image](https://user-images.githubusercontent.com/69439002/173207374-7f1beca6-4559-4b05-b9d6-de672dd6a888.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 556e9d3f-080a-d2e0-0c23-e35e548efccd
* Version Independent ID: 30fbaca4-b260-1dd4-8d54-97c84a247000
* Content: [Microsoft Purview solution catalog - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-solution-catalog?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/microsoft-365-solution-catalog.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/microsoft-365-solution-catalog.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8956

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by robmazz** [comment]
@nikki-c  - Thanks for the feedback, the changes are pending. The topic should be updated and published in the next few days.
