### ISSUE TITLE
cross tenant migration using the Microsoft Preview failing on test

### ISSUE THREAD

**Issue by amhiggins1962** [MicrosoftDocs/microsoft-365-docs#8888]
I am trying to do a cross tenant migration using the Microsoft Preview features and I am testing the setup by running the command Cross Tenant mailbox migrations as follows:
Test-MigrationServerAvailability -Endpoint " ORZCrossTenantMigrationRelationship]”
And I am seeing the error:
The migration endpoint 'ORZCrossTenantMigrationRelationship]' couldn't be found. Reason: The migration endpoint
'ORZCrossTenantMigrationRelationship]' couldn't be found.
    + CategoryInfo          : NotSpecified: (:) [Test-MigrationServerAvailability], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : [Server=SJ0PR10MB5765,RequestId=c3372f77-7d23-4a81-b04e-f83c75379fd8,TimeStamp=6/12/2022
    6:13:22 PM] [FailureCategory=Cmdlet-ManagementObjectNotFoundException] A9B37BF0,Microsoft.Exchange.Management.Mig
  ration.MigrationService.Endpoint.TestMigrationServerAvailability
    + PSComputerName        : outlook.office365.com
 
You say in the response to a Reddit query that:
“The documentation is incorrect for Test-MigrationServerAvailability (we are in the process of updating this), and you should be using the target email address, not the source address.”
But I don’t quite know what that means….. as I am meant to be able to simply specify the ENDPOINT in the command and it should find it.
 
When I set all of this up about a month ago, it worked and responded back with a positive response but now I come to start the migration, it’s not responding and I need to figure out why before continuing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by kelleyvice-msft** [comment]
@amhiggins1962, thanks for reaching out. This isn't strictly a content issue, and issues with PowerShell modules are outside the scope of content feedback. Having said that, I will update the content to point to the [Test-MigrationServerAvailability documentation](https://docs.microsoft.com/powershell/module/exchange/test-migrationserveravailability?view=exchange-ps) rather than explicitly suggest a usage that is evidently broken. I will also pass along this issue to the Exchange PowerShell engineering team as additional substantive evidence to support actively resolving the module bug. -Kelley

**Comment by kelleyvice-msft** [comment]
I also meant to add that you should try one of the other switches in the [Test-MigrationServerAvailability documentation](https://docs.microsoft.com/powershell/module/exchange/test-migrationserveravailability?view=exchange-ps) as a workaround to your specific problem. -Kelley

**Comment by amhiggins1962** [comment]
Hi Kelly,
  Thanks for responding – I ended up getting support directly from someone at Microsoft who explained my error, in this case… the problem was that I was using the name of the migration endpoint rather than the associated appname, which is what should be used……
Thanks for your help and I hope this can be posted to help others who might make the same error as I did…
Regards,


Andy Higgins
[signature_859793916]
++1 (512) 426-6142
www.imcollaboration.com<https://www.imcollaboration.com/>


From: Kelley Vice ***@***.***>
Date: Tuesday, June 14, 2022 at 12:59 PM
To: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Andy Higgins ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/microsoft-365-docs] cross tenant migration using the Microsoft Preview failing on test (Issue #8888)

I also meant to add that you should try one of the other switches in the Test-MigrationServerAvailability documentation<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fpowershell%2Fmodule%2Fexchange%2Ftest-migrationserveravailability%3Fview%3Dexchange-ps&data=05%7C01%7Candy%40imcollaboration.com%7C62a4a47f04ed456044c708da4e2fab31%7Ce975bfedaa7d415aaad92b6898099194%7C0%7C0%7C637908263906894580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GALJE65hpM%2BD%2BvvQODRmXdbKVJ%2FCTqATURFDegFHI7M%3D&reserved=0> as a workaround to your specific problem. -Kelley

**Comment by kelleyvice-msft** [comment]
Updated in https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/14696.

**Comment by quimguito** [comment]
> Hi Kelly, Thanks for responding – I ended up getting support directly from someone at Microsoft who explained my error, in this case… the problem was that I was using the name of the migration endpoint rather than the **associated appname**, which is what should be used…… Thanks for your help and I hope this can be posted to help others who might make the same error as I did… Regards, Andy Higgins 

Hello im stuck with same problem when you say "I was using the name of the migration endpoint rather than the associated appname" should the parameter in "Test-MigrationServerAvailability - Endpoint [**guid of appid**]"  or some other parameter?

**Comment by amhiggins1962** [comment]
Hi @quimguito - apologies for not getting back to you sooner but I got Covid and was ill... better now thanks..
The answer to your question is that you should use the name of the associated appname rather than the migration endpoint name (which is what I assumed they meant by "Endpoint" but that's not what is required)
Let me know if that works for you
