### ISSUE TITLE
Confusing chart comparing "Vuln mgmt" options. A venn diagram or an image would make this clearer.

### ISSUE THREAD

**Issue by amcamillo** [MicrosoftDocs/microsoft-365-docs#8890]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4383e31-f80e-65de-3a90-9bb53b6845d2
* Version Independent ID: d4383e31-f80e-65de-3a90-9bb53b6845d2
* Content: [Compare Microsoft Defender Vulnerability Management offerings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/defender-vulnerability-management-capabilities.md)
* Product: **m365-security**
* Technology: **mdep1**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by yogkumgit** [comment]
@siosulli please do not remove me from assignee list, it will help me in tracking. Thanks

**Comment by siosulli** [comment]
@yogkumgit no problem! apologies!

**Comment by siosulli** [comment]
@yogkumgit @amcamillo 

Thank you for your feedback! 

I have added a task to the backlog for this. I will look at updating this table in line with an upcoming release.
