### ISSUE TITLE
Inconsistency in the points

### ISSUE THREAD

**Issue by binUmmer** [MicrosoftDocs/microsoft-365-docs#8893]
[Enter feedback here]
There are two points in the article which is supposed to be different, but in fact its same statement.

**If there's a value for the ExternalDirectoryObjectId property, the mailbox retention period has expired**, and you can recover the inactive mailbox by running the New-Mailbox -InactiveMailbox command.
**If there's a value for the ExternalDirectoryObjectId property, the soft-deleted mailbox retention period hasn't expired** and you have to recover the mailbox by [restoring the user account](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/delete-a-user?view=o365-worldwide).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e8e1ab-8080-9c2f-d6af-97fc01b0a2c0
* Version Independent ID: d8debc69-c7bf-6e28-6e9f-8b7fae822dfd
* Content: [Recover an inactive mailbox - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/recover-an-inactive-mailbox?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/recover-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/recover-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@binUmmer Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8896

Once the author approves, the changes will be live.

The mailboxes with ExternalDirectoryObjectId values belong to Azure AD accounts deleted within the last 30 days and can be recovered by restoring the user account.

The mailbox without ExternalDirectoryObjectId value means the mailbox retention period has expired, and you can recover the inactive mailbox by running the New-Mailbox -InactiveMailbox command.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @binUmmer Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
