### ISSUE TITLE
"Click Customize columns to show a maximum of seven columns" 

### ISSUE THREAD

**Issue by rfellmann** [MicrosoftDocs/microsoft-365-docs#8899]
"Click Customize columns to show a maximum of seven columns"
The limit no longer applies. All columns can be showed at the same time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Manage submissions - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@RatulaC Please comment. Thanks

**Comment by chrisda** [comment]
Massive unrelated updates to this content, and the topic no longer says, "maximum seven columns".

Thanks for the feedback.

Closing
