### ISSUE TITLE
Remove redundant subsection

### ISSUE THREAD

**Issue by gideoncaringal** [MicrosoftDocs/microsoft-365-docs#890]
The subsection "Get Office 365 ATP" already provides all the necessary information. Therefore, subsection "Office 365 ATP Plan 1 and Plan 2", which comes earlier in the document, is redundant and should be deleted. 

For example, I was looking if Office 365 ATP is included in the Microsoft 365 Business subscription. This was not clear until I scrolled a lot further down.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a177ba2-5cff-b0a0-6afa-717689db2884
* Version Independent ID: 802f6c49-9a14-e76f-6cf3-67862b40f18d
* Content: [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp)
* Content Source: [microsoft-365/security/office-365-security/office-365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/office-365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
The table in the report is a concise, on-page learning resource for those who are new to ATP, or don't want to scroll the full article to click through links that lead off-page. The table serves the immediate intent of the article. It will remain. Thanks.

**Comment by gideoncaringal** [comment]
@MSFTTracyP Thank you for looking into it. I can see that commit 4d69a11 adds an informative table and right below, it now shows the information that I originally was hoping would be placed higher up.
