### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by eliebermangwm** [MicrosoftDocs/microsoft-365-docs#8900]
All of the documentation refers to an old version of Twitter's interface that no longer is available. Setting this up requires alot of guessing about proper inputs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c91b46-f547-f01a-b44b-2f0da184eed8
* Version Independent ID: e4d3f56c-0349-55f5-8c50-17b2b4b3dbf8
* Content: [Set up a connector to archive Twitter data - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/archive-twitter-data-with-sample-connector?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/archive-twitter-data-with-sample-connector.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/archive-twitter-data-with-sample-connector.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@v-tophillips Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@eliebermangwm Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
