### ISSUE TITLE
The list of required permissions section - AND or OR?

### ISSUE THREAD

**Issue by jamesrschoppe** [MicrosoftDocs/microsoft-365-docs#8904]
"You need to be assigned permissions in Exchange Online before you can do the procedures in this article:

To add and remove values from the Tenant Allow/Block List, you need to be a member of
- Organization Management or Security Administrator role group (Security admin role)
- Security Operator role group (Tenant AllowBlockList Manager).
For read-only access to the Tenant Allow/Block List, you need to be a member of
- Global Reader role group
- Security Reader role group
- View-Only Configuration role group."

In the first set, it wouldn't make sense to be AND, so I would assume in the second set OR.  Might be confusing to people troubleshooting why someone can't view the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jamesrschoppe, I agree, it's confusing as written. I cleaned it up to say:

- You need to be assigned permissions in **Exchange Online** before you can do the procedures in this article:
  - To add and remove entries from the Tenant Allow/Block List, you need to be a member of one of the following role groups:
    - **Organization Management** (the **Security admin** role).
    - **Security Administrator** (the **Security admin** role).
    - **Security Operator** (the **Tenant AllowBlockList Manager** role).

  - For read-only access to the Tenant Allow/Block List, you need to be a member of one of the following role groups:
    - **Global Reader** role group.
    - **Security Reader** role group.
    - **View-Only Configuration** role group.
 
Thanks for the feedback.

Closing

**Comment by jamesrschoppe** [comment]
Thanks!!!
