### ISSUE TITLE
Audit option does not exist

### ISSUE THREAD

**Issue by ishepherd** [MicrosoftDocs/microsoft-365-docs#8905]
> ## Step 1: Run an audit log search
> 2. In the left pane of the compliance portal, click Audit.

I don't have this option. Here are the options I see

![image](https://user-images.githubusercontent.com/3198421/173495808-d0fc2d89-0586-491c-a488-327ff1ee180d.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://docs.microsoft.com/en-gb/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@ishepherd Thank you for your feedback. I was able to locate the audit log option under solutions. If you still have a problem, I'd recommend you check your access/permissions or contact Microsoft support via the need help so that they can fix if it is a bug on this tenant.

Hope this helps!

Thanks
Sri

**Comment by ishepherd** [comment]
Hi @msbemba 

I've been told by colleagues that I don't have enough permissions on this tenant.

I was confused because I get alert emails advising me to do an audit log search. But I get the emails just by membership of a distribution list.

Nothing to see here 😄 thanks for your reply.
