### ISSUE TITLE
Filtering only works for DISPLAYED results, not FOUND results

### ISSUE THREAD

**Issue by RipRapRob** [MicrosoftDocs/microsoft-365-docs#891]
When I make a search I get "150 results found (More items available, scroll down to see more.)" 

If I then use the FILTER function, to filter on IP address or User, only the 150 results that are shown, are filtered. So i get maybe 8 results if I apply a filter BEFORE scrolling down the list.

But if I scroll down to the bottom of the list, and additional 150 results are shown, and repeat. So if I apply the filter then, more than the 8 filtered results from before, are shown.

So, in other words: The filter function only works for DISPLAYED results, not FOUND results, so I have to manually scroll down the list to make sure ALL my results in my current search are shown BEFORE I can use the filtering function in any meaningful way.

Tested in both Internet Explorer and Chrome. 

Please fix :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#step-3-filter-the-search-results)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@RipRapRob Please feel free to submit this product feedback at https://office365.uservoice.com/forums/289138-office-365-security-compliance. You could cut and paste this GitHub issue and provide the context of O365 unified audit log.

As an alternative workaround (which may not be any better) you can "download all results", parse the AuditData column (which is a JSON object) and then use Excel's (powerful) filtering functionality. See https://docs.microsoft.com/en-us/microsoft-365/compliance/export-view-audit-log-records.
