### ISSUE TITLE
How can we disable auto expanding archive? 

### ISSUE THREAD

**Issue by deepthainf** [MicrosoftDocs/microsoft-365-docs#8911]
I am trying to understand how to disable auto expanding archive. I  do not want to disable the archive just want to convert it to a normal archive, so that I can use Cross premises mailbox migration tool for migration. 

Any comment is appreciated.
TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c231a9b-07c0-b2a6-2292-17e760432ecf
* Version Independent ID: b2fbf9bf-44fb-74a3-ec31-c02263b7d755
* Content: [Enable auto-expanding archiving - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-autoexpanding-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-autoexpanding-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-autoexpanding-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@deepthainf  Unfortunately, this isn't supported.  From this section on the page: https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-autoexpanding-archiving?view=o365-worldwide#before-you-enable-auto-expanding-archiving:

After you turn on auto-expanding archiving for your organization or for a specific user, it can't be turned off.
