### ISSUE TITLE
Intune Azure Roles Do Not Exist

### ISSUE THREAD

**Issue by WELLBOREIS** [MicrosoftDocs/microsoft-365-docs#8913]
The Microsoft Intune Roles below do not exist in Azure AD:
1) "Application manager": May possibly be called "Application administrator" now?
2) "Help desk operator": May possible be called "Helpdesk administrator" now?
3) "Intune role administrator": May possibly be called "Intune administrator" now?
4) "Policy and profile manager": Can't find any role that fits this description.
5) "Read only operator": Can't find any role that fits this description.
6) "School administrator": Can't find any role that fits this description.

Intune documentation needs a MAJOR overhaul. I'm not switching from SCCM to full Intune deployement until there's better documentation and is updated when features change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6877a274-00b3-b013-5a94-2180edb5d353
* Version Independent ID: 2a0a912f-f11e-07cf-0b05-dbd4308b1d2f
* Content: [About Intune admin roles in the Microsoft 365 admin center - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/intune-admin-roles-in-the-mac?view=o365-worldwide#microsoft-intune-roles-available-in-the-microsoft-365-admin-center)
* Content Source: [microsoft-365/admin/add-users/intune-admin-roles-in-the-mac.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/intune-admin-roles-in-the-mac.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @WELLBOREIS Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
