### ISSUE TITLE
No mention of exap.um.outlook.com used for Cloud Voice Mail

### ISSUE THREAD

**Issue by robertpp** [MicrosoftDocs/microsoft-365-docs#8914]
The document makes no reference to exap.um.outlook.com endpoint, used in the configuration of [Cloud Voice Mail](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail). The endpoint is referenced in [Other endpoints not included in the Office 365 IP Address and URL Web service](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide), but with a different purpose and no indication of the IP ranges.

The suggestion is to add *.um.outlook.com to endpoint 22. Based on non-confirmed information, the corresponding IP range is 52.112.0.0/14.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please comment. Thanks
