### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by Nath9119** [MicrosoftDocs/microsoft-365-docs#8919]
[Enter feedback here]

The "Win 10 lab guides" doesn't link to the guides (Win11 lab guides links to https://download.microsoft.com/download/9/d/9/9d9e278e-a1ea-4704-85e1-cb24f3806f45/Win11_Lab_Guides_05.09.zip)

The URL for "Win 10 lab guides" is https://download.microsoft.com/download/2/9/9/29952cdb-b98d-4f9b-9d6e-9fb49644b0a0/Win10_21H1_Lab_05.12.zip

The above URL seems to be missing "_Guides_" in betwee "Lab" and "05" - although manually entering this takes you to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21195f1c-0f99-502b-c6e7-a87d35237a81
* Version Independent ID: 1848a7e1-4919-8e28-27ea-cfdbef125609
* Content: [Windows and Office 365 deployment lab kit - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-desktop-deployment-and-management-lab.md)
* Service: **o365-solutions**
* GitHub Login: @cdmm12
* Microsoft Alias: **aaroncz**

**Comment by msbemba** [comment]
@Nath9119 The windows 10 Lab guide link is https://download.microsoft.com/download/8/5/e/85e007b0-1f3e-460c-bd0a-5a8c6ec490b5/Win10_21H2_guides.zip and the same has been updated in the document

Hope this helps!

Thanks
Sri
