### ISSUE TITLE
Provide a list of all account types and a list of all accounts used by Microsoft

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#892]
Hello,

for compliance reasons it makes sense to provide:

- a list of all account types that exist (e. g. on some external, non-Microsoft sites there are resource and system account types mentioned but no documentation about this can be found in the official docs; see this as one of those sources: https://kb.wisc.edu/office365/page.php?id=32951) and what they are used for (can a customer create such an account? what's the use case behind the specific account type?)
- a list of all accounts that Microsoft does use for services and internal tasks, for example the 'app@sharepoint' user.

This information makes sense to know as it is necessary to be able to differentiate within the audit log between usual activities of an Office 365 tenant and what kind of activities are suspicious/malicious/should rise an alert.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#feedback)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@GiantCrocodile Thanks for the suggestion. Your reasons for wanting an authoritative list of service accounts are understandable. However, give the number of O365 services and the number of different tasks these services perform continuously on behalf of tenants, this is too difficult to compile and maintain an authoritative list. 

You might try exporting audit records and transforming the AuditData JSON object to view, filter, and sort additional information contained in audit records. For info, see https://docs.microsoft.com/en-us/microsoft-365/compliance/export-view-audit-log-records.

We will also update the audit topic with information about the "Search query performed" SP activity and the default app@sharepoint SPO user account (which typically performs the search on behalf of other features like auto-applying labels and retention policies).

**Comment by GiantCrocodile** [comment]
Thank you for your detailed reply @markjjo!

Are you aware of typical/common patterns in such accounts of Microsoft? Like if there are more accounts like app@sharepoint which have no fully qualified domain name as username.

What about the list of existing account types? I think that list should be quite short in relation to the list of all Microsoft's accounts.

**Comment by markjjo** [comment]
@GiantCrocodile I'm assume you are already familiar with the various [UserType enum values](https://docs.microsoft.com/office/office-365-management-api/office-365-management-activity-api-schema#enum-user-type---type-edmint32). I assume that's what you may mean by "list of existing account types." If you're asking about a common format/pattern for the UserID field (if UserType equals "service account") then I don't think there is. In researching my response to this issue, it was very instruction to export a large number audit records, parse the AuditData JSON object as I mentioned above, then filter on the UserType column (e.g. for example, UserType = 4, to display only the records that were "triggered" by system accounts). I saw that the values in the UserID column were, in terms of "typical/common patterns", pretty varied. Doing this might also help you compile a list of the different service account values, at least in your tenant.

As an aside/anecdote and probably not that interesting or important, but I discovered that the UserType for the app@SharePoint account is "Regular User" (UserType enum = 0). That surprised me. I also discovered that this account (and SHAREPOINT\system) is returned when you run Get-SPOUser against the top-level SP site in my tenant. Maybe this is why it's regular user in the audit record.

**Comment by markjjo** [comment]
Run Get-SPOUser in SPO PowerShell, that is

**Comment by GiantCrocodile** [comment]
I appreciate the information you did provide and I will look into this in detail within the next days. I do appreciate any information provided and added to the docs and I think this will bring me quite some steps forward. Thank you for taking this topic seriously!
