### ISSUE TITLE
Need additional explanations on the Recipient Filters Conditions

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/microsoft-365-docs#8922]
After working with Microsoft Premier support for an issue we had, we think that the documentation for all policy types (Anti-spam, Anti-malware, etc.), requires some clarification details about how the recipient filters conditions are working.
The "You can only use a condition or exception once" and the "the different conditions or exceptions use AND logic" should be rewritten to something more precise. We often make the confusion that the "AND" logic is like an "ADD" logic.

As an example, let's imagine, we fill in all conditions like this: recipientA AND member of groupB AND domainC. Where recipientA is not using domainC and is not members of GroupB either. At the end, there will be no match to this logic on the scope for the recipient filter and only the default policy would apply. When multiple conditions are used, we need to ensure that the "final recipient target" is present in the 3 kind of conditions and there is no precedence for domains or member "conditons type".

It needs to be precise that the "AND" is not an "ADD" and we should only use a single "conditions type" at once. Because of this behavior explained by Microsoft Support, we do not understand why it's still possible to select multiple conditions from the admin interface or even through powershell. It should be blocked.

I hope my description of the problem is clear enough to improve the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5966b7b-cbaa-eaa2-c9d6-5c6e7218df74
* Version Independent ID: cfcc8772-be5d-009a-0805-62624835ac5f
* Content: [Safe Attachments - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-attachments?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-attachments.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@RomanNG, OK. There were 11 topics total that talked about recipient conditions/exceptions to policies, and I added the following text in all of them:

  > [!IMPORTANT]
  > Multiple different conditions or exceptions are not additive; they're inclusive. The policy is applied _only_ to those recipients that match _all_ of the specified recipient filters. For example, you configure a recipient filter condition in the policy with the following values:
  >
  > - The recipient is: romain@contoso.com
  > - The recipient is a member of: Executives
  >
  > The policy is applied to romain@contoso.com _only_ if he's also a member of the Executives groups. If he's not a member of the group, then the policy is not applied to him.
  >
  > Likewise, if you use the same recipient filter as an exception to the policy, the policy is not applied to romain@contoso.com _only_ if he's also a member of the Executives groups. If he's not a member of the group, the then policy still applies to him.

Thanks for the feedback.

Closing
