### ISSUE TITLE
Please add the below NOTE in the technet 

### ISSUE THREAD

**Issue by MithunRathinam** [MicrosoftDocs/microsoft-365-docs#8927]
**Note:** Malware release is not possible for end users from quarantine regardless of whether a user release action was configured in the quarantine policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db041b73-f7c9-db6c-070b-a7c974de640c
* Version Independent ID: dffb7045-3ba8-a014-d1be-462ca1d609b5
* Content: [Configure anti-malware policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-anti-malware-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-anti-malware-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-anti-malware-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking.

**Comment by chrisda** [comment]
OK. Done.

Thanks for the feedback.

Closing

**Comment by MithunRathinam** [comment]
Thanks Chris ..

Thanks & Regards,
Mithun Rathinam
Support Escalation Engineer , Beta Engineer
***@***.******@***.***>
Working Hours: M-F 08:00AM - 05:00PM (EDT)
[Microsoft Logo]
