### ISSUE TITLE
Forgot to replace bracketed text with link?

### ISSUE THREAD

**Issue by AntoniaBlume** [MicrosoftDocs/microsoft-365-docs#8928]
In this section: https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide#admin-center-features-and-settings 
There is the following bracketed text that looks like it should be a link:
"Learn more about admin tasks in [admin help](Overview of the Microsoft 365 admin center](admin-center-overview.md)."

Although actually, that looks like a circular link that would go back to this same article? So maybe it should just be cut.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Version Independent ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Content: [Microsoft 365 admin center - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/admin-overview/admin-center-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-center-overview.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by RAJU2529** [comment]
@yogkumgit . Close this  issue #8928 . Issue is solved

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @AntoniaBlume Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
