### ISSUE TITLE
Exchange Mail flow rules (transport rules) impact on EOP + ATP

### ISSUE THREAD

**Issue by tfurstms** [MicrosoftDocs/microsoft-365-docs#893]
Thanks for creating this combined EOP + ATP document!

One ask - Please add guidance around the impact Exchange Mail flow rules (transport rules) can have on  EOP + ATP. Specifically call out the scenario where an Exchange Mail Flow rule could whitelist an email address and the impact is that EOP + ATP would allow that email through (i.e., bypass the protections). Any other comments around Exchange Mail flow rules and their relationship to the protections EOP+ATP would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Office 365 ATP security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, etc](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp#feedback)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Thanks for leaving this feedback. There's a separate article that covers information relating to ETRs. I'll be linking it into this article.
