### ISSUE TITLE
Discussion: Exported columns vs. Import columns

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#8930]
Why not make the columns of the Exported file plan .csv the same as the columns used for Import?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4465ca1-9ee2-e551-aff2-9fc8e4a5eae3
* Version Independent ID: 2cbc9375-d055-edf8-0f89-b5794f7aa7a7
* Content: [Use file plan to manage retention labels - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/file-plan-manager?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/file-plan-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/file-plan-manager.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@sparkitect  Hi Jim - this is a good question but not one that can be answered by GitHub Issues for the documentation.  If you have a business case for aligning the formats, raise this as a design change request with your Microsoft support channels, or use the "This product" button on the page's Feedback section.
