### ISSUE TITLE
Syntex models Supported file types

### ISSUE THREAD

**Issue by mcasaz** [MicrosoftDocs/microsoft-365-docs#8933]
the table on [this page](https://docs.microsoft.com/en-gb/microsoft-365/contentunderstanding/difference-between-document-understanding-and-form-processing-model) states that "supported files types" for Document Understanding model are only PDF, Office, email but on [this doc page](https://docs.microsoft.com/en-gb/microsoft-365/contentunderstanding/document-understanding-overview) the list is much bigger

Supported file types
Document understanding models support the following file types:

doc
docx
eml
heic
heif
htm
html
jpeg
jpg
markdown
md
msg
pdf
png
ppt
pptx
rtf
tif
tiff
txt
xls
xlsx

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7acbcb-25a1-2241-3738-0582ed407ad5
* Version Independent ID: d3c1802f-a8b4-3400-a350-734e9bad2b5d
* Content: [Differences between document understanding and form processing models - SharePoint Syntex](https://docs.microsoft.com/en-gb/microsoft-365/contentunderstanding/difference-between-document-understanding-and-form-processing-model)
* Content Source: [microsoft-365/contentunderstanding/difference-between-document-understanding-and-form-processing-model.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/difference-between-document-understanding-and-form-processing-model.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@mcasaz Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9031

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mcasaz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
