### ISSUE TITLE
Incorrect instruction

### ISSUE THREAD

**Issue by TheDeuceYouSay** [MicrosoftDocs/microsoft-365-docs#8935]
Under Use Group Policy to schedule protection updates - 

item 4, states:

Expand the tree to Windows components > Microsoft Defender Antivirus > Signature Intelligence Updates and configure the following settings:

This is incorrect.  Correct tree path is:

Windows components > Windows Defender Antivirus > Signature Updates

Item 4b should be Specify the interval to check for **definition** updates

Item 4c should be Specify the time to check for **definition** updates

This was viewed on Server 2019 Datacenter

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e26a44-834c-bcd3-5fec-b9aa9bb8cde1
* Version Independent ID: 1d3e40d3-8d86-147d-f509-2f59adbceee0
* Content: [Schedule Microsoft Defender Antivirus protection updates](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-protection-update-schedule-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@TheDeuceYouSay Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8985

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @TheDeuceYouSay Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
