### ISSUE TITLE
Schema sample for EDM xml file has a typo

### ISSUE THREAD

**Issue by Dhaval-Jani** [MicrosoftDocs/microsoft-365-docs#894]
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification#part-1-set-up-edm-based-classification

Line 1 in the XML sample file is :
<EdmSchema xmlns="https://schemas.microsoft.com/office/2018/edm">

It should be :
<EdmSchema xmlns="http://schemas.microsoft.com/office/2018/edm">

**Comment by mypil** [comment]
@Dhaval-Jani - Can you please share what specific changes you want to see in this doc? 
We would really appreciate it if you are able to help by providing more details as to what should be edited and/or included.

Thank you!

**Comment by mypil** [comment]
@Dhaval-Jani - I can see that you created PR #895. Is this the fix for the issue you created?

Please confirm. Thank you.

**Comment by chrfox** [comment]
@Dhaval-Jani 
I closed this PR, I am closing this issue as well
