### ISSUE TITLE
Typo in Image

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#8943]
The first image on the page has a spelling mistake in it - the blue heading text at the end of the arrow is spelt "Microsot 365 Defender Portal" and should read "Microsoft 365 Defender Portal"

I have highlighted in yellow my screenshot below

<img width="459" alt="image" src="https://user-images.githubusercontent.com/59968025/174106309-96b462dd-ba8f-4d63-95e0-4a35e27f8c7e.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c29e05f2-5a90-3457-220f-af7c4ad3c9f2
* Version Independent ID: c29e05f2-5a90-3457-220f-af7c4ad3c9f2
* Content: [Microsoft Defender for Cloud Apps in Microsoft 365 Defender (Preview)](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
Thank you for your comment. We'll investigate and get back to you.

**Comment by dcurwin** [comment]
Thanks again for your suggestion. The image will be updated.
