### ISSUE TITLE
Scenario 2 unworkable with 3rd party email gateway/security.

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/microsoft-365-docs#8944]
Update the documentation to indicate that "Scenario 2" is only available if the domain's MX records are pointing to Exchange Online. If the organization is leveraging a 3rd party email gateway, scenario 2 will not work. Please see support Case #:30772915.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54783558-94f0-24ad-0fa3-1461a608fd10
* Version Independent ID: 53ebf483-a8ef-e242-9a2c-c285bbce65da
* Content: [Choose the domain to use when creating Microsoft 365 groups](https://docs.microsoft.com/en-us/microsoft-365/solutions/choose-domain-to-create-groups?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/choose-domain-to-create-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/choose-domain-to-create-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@JLambEJG Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8988

Once the author approves, the changes will be live.

Thanks
Sri
