### ISSUE TITLE
Contradictory

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/microsoft-365-docs#8948]
The article seems to have a contradictory minimum password length. It recommends a 14 character minimum, and then it says that requiring more than 10 can be counter-productive, and recommends 8 minimum!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523758d0-17ea-7061-d9ce-8f5a31a76b4c
* Version Independent ID: 545fd950-8ef0-837b-8839-8aa21da0c6eb
* Content: [Password policy recommendations - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/password-policy-recommendations?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/password-policy-recommendations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/password-policy-recommendations.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@Air-Git Thank you for your feedback. We have made changes to the document to reflect the minimum character limit as 8. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8989

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Air-Git Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
