### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by PayneCeeva** [MicrosoftDocs/microsoft-365-docs#8957]
Too many details to go over. Just redo the page and let me know when it's correct. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import PST files - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#step-1-copy-the-sas-url-and-download-azcopy)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by PayneCeeva** [comment]
Hi Yogesh,
You may as well close the ticket if you need you clientele to write your documentation for you. I found the correct answers through a mixture of trial-and-error and going over various blogs and troubleshooting forums. At this point I use Microsoft documentation as a starting point and move on to more competent sources as the need arises.
Thanks,

***@***.***
George Payne
Technical Support Specialist

***@***.***
412-690-2300 x336<tel:412-690-2300%20x336>
***@***.***
***@***.******@***.***>
***@***.***
www.ceeva.com<https://www.ceeva.com>

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@PayneCeeva Thank you for your feedback. I was able to follow the steps in the document and import PST. If there is any step in particular that you think is incorrect, please let us know.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @PayneCeeva Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
