### ISSUE TITLE
Really enable privileged access from Microsoft 365 Admin center (Step 2)

### ISSUE THREAD

**Issue by akczcz** [MicrosoftDocs/microsoft-365-docs#896]
Hello, as I suppose, there is no possibility to do set up as mentioned in Step 2 (no matter if you have "new" or "old" Microsoft 365 admin center set up). Probably you Manage PIM for Office 365 only through Azure AD Privileged Identity Management located in Azure portal. If so, it would be good to update docs together with technical changes. Thx Adam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bf337ec-3242-44b9-328b-7ca6381a2bcf
* Version Independent ID: eda3540f-7049-ad17-a259-7952e5665983
* Content: [Configuring privileged access management in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/privileged-access-management-configuration#feedback)
* Content Source: [microsoft-365/compliance/privileged-access-management-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/privileged-access-management-configuration.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@akczcz - thanks for the feedback. For privileged access management (PAM), I've made some updates to the path instructions in the new admin center. For privileged identity management (PIM), please see this documentation - https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-configure.
