### ISSUE TITLE
Requirements for network protection, Windows 10 Education?

### ISSUE THREAD

**Issue by AdamJParker** [MicrosoftDocs/microsoft-365-docs#8960]
Wanted to see if this was a documentation error or if Education version of Windows 10 does not support Network Protection? I was under the impression that all Enterprise Security Features were also available in Edu SKU, but Microsoft Support referenced this article that Education version is not supported. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395141e8-be91-e226-24d7-dc136b8f9c5e
* Version Independent ID: 012beed4-1fdb-4f59-9cc4-53ba5e2c8ea2
* Content: [Use network protection to help prevent connections to bad sites](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@AdamJParker Thank you for your feedback. Currently, Network protection requires Windows 10 or 11 (Pro or Enterprise). Having said that you can leave feedback to our Dev/product team via the main feedback portal - https://feedbackportal.microsoft.com/ so that they can provide an update on whether this is in the roadmap or if there are plans to include it in the EDU SKU.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@AdamJParker Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
