### ISSUE TITLE
Azure Arc?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#8968]
What are the installation steps when machine is connected via Azure Arc? I believe there is no need to download and install anything from the MDE portal. Please clarify in this doc and refer to corresponding page...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77c40dd-e4d2-90f5-d70a-b0ee4b430136
* Version Independent ID: f0ec110b-7938-5e22-d39e-6ded935a9ced
* Content: [Onboard Windows servers to the Microsoft Defender for Endpoint service](https://docs.microsoft.com/en-gb/microsoft-365/security/defender-endpoint/configure-server-endpoints?view=o365-worldwide#prerequisites)
* Content Source: [microsoft-365/security/defender-endpoint/configure-server-endpoints.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-server-endpoints.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by andrePKI** [comment]
No mention of Arc?

**Comment by andrePKI** [comment]
And no change to the original doc. So how does this help?
