### ISSUE TITLE
Please add explainations for all buttons

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/microsoft-365-docs#897]
E.g. what is "Submit message" doing exactly
Maybe it also make sense to add screenshots of second page of wizard (New submission)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfc15d1-833b-3139-6bc0-1acb97d507c8
* Version Independent ID: 31e24618-c2e6-4fe4-9651-04d6007548a4
* Content: [Find and release quarantined messages as a user in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user)
* Content Source: [microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello @trudolf-msft,
are you sure you refer the correct artcle?
I can't find "submit" button and "new submission" wizard in this one.
Thank you

**Comment by trudolf-msft** [comment]
Hi Marat,

Please see this screenshot.
[cid:image001.jpg@01D5B7EF.5BD80C50]

Kind regards,
Thomas

Thomas Rudolf | Senior Premier Field Engineer | Messaging & Office 365
WW Lead - Offline Assessment Exchange Server Security
[cid:image001.gif@01CDCC11.C609BE10]

**Comment by mypil** [comment]
@trudolf-msft - We could not view the screenshot you shared. Can you please send it again as an attachment or just copy/paste it on your comment? 

Thank you.

**Comment by trudolf-msft** [comment]
Hi,

please find attached.

Kind regards,
Thomas

**Comment by mypil** [comment]
@trudolf-msft - We still could not view the attachment of the screenshot. Please refer to this article on how you can attach an image within the issue comment - https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

Hope this helps to give guidance. Thank you.

**Comment by trudolf-msft** [comment]
![Clipboard01](https://user-images.githubusercontent.com/43539433/72138783-d549a480-338d-11ea-832f-4fd580193f3d.jpg)

**Comment by MaratMussabekov** [comment]
hello, @trudolf-msft ,
the screenshot you added is the view for administrators not for users (the article is about user actions).
Users view is following:
![Screenshot2](https://user-images.githubusercontent.com/48041687/72197042-cb33ae80-343e-11ea-8c8e-36715a53710a.png)
So the submit option is not available for users. For the details about this option you can see [How to submit suspected spam, phish, URLs, and files to Microsoft for Office 365 scanning](https://docs.microsoft.com/microsoft-365/security/office-365-security/admin-submission)

Anyways, the description of other buttons should be added, I will create a PR.

Thank you

**Comment by MaratMussabekov** [comment]
Oh, sorry, I didn't see that the description of the "View message header" and "Preview message" already exist in the article.
I think the issue could be closed then, dear @trudolf-msft, what do you think?

Thank you

**Comment by mypil** [comment]
@trudolf-msft -  Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by MaratMussabekov so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mbensitel** [comment]
hey, i have all the option grilled out, is that normal??
