### ISSUE TITLE
Server OSes?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#8971]
Under requirements, only Windows 10 is mentioned, no server OSes. Where is the  Server OS documentation? (And what about Windows 11?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f58c48-23a1-29e6-4358-7733b12668c8
* Version Independent ID: 27f7f229-ae73-3cd0-287f-8592aaa3928b
* Content: [Set up and configure Microsoft Defender for Endpoint Plan 1](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration?view=o365-worldwide#review-the-requirements)
* Content Source: [microsoft-365/security/defender-endpoint/mde-p1-setup-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-p1-setup-configuration.md)
* Product: **m365-security**
* Technology: **mdep1**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @andrePKI and thank you so much for your feedback! I have updated the content to include the following information:

The standalone versions of Defender for Endpoint Plan 1 and Plan 2 do not include server licenses. To onboard servers, you will need Defender for Servers Plan 1 or Plan 2 as part of the [Defender for Cloud offering](https://docs.microsoft.com/azure/defender-for-cloud/defender-for-cloud-introduction). 

I also added Windows 11 to the list of operating systems. 

Thank you again for your feedback!
