### ISSUE TITLE
Request for linked Channel9 content to be reinstated/re-linked

### ISSUE THREAD

**Issue by kinshasha** [MicrosoftDocs/microsoft-365-docs#8972]
Hi ER team.

Re the following section of the linked docs page:
> We've also recorded a 10-part [Azure ExpressRoute for Office 365 Training](https://channel9.msdn.com/series/aer) series on Channel 9 to help explain the concepts more thoroughly.

The link to the series on Channel9 seems to have broken and can no longer be located. Can this be reviewed and updated please as this was a useful training asset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e54e547-0ef6-6a9c-5c50-61c76efe3a10
* Version Independent ID: ca3518a9-3add-256b-c15a-7b3f702445fc
* Content: [Routing with ExpressRoute for Office 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/routing-with-expressroute?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/routing-with-expressroute.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/routing-with-expressroute.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
@kinshasha, thanks for reaching out. I believe the reason this training series was removed is because we are deemphasizing ExpressRoute for Microsoft 365. I'll remove the link from the article. Thanks, Kelley
