### ISSUE TITLE
Missing \DataCollection folder from the exclusion list 

### ISSUE THREAD

**Issue by Nosferatu-Dk** [MicrosoftDocs/microsoft-365-docs#8975]
[This folder runs scripts also; they should be added I believe....
Thinking this folder is missing from the exclusion list "C:\ProgramData\Microsoft\Windows Defender Advanced Threat Protection\DataCollection"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42db2345-0d5c-45f3-6c24-d84a12775fb7
* Version Independent ID: 1634b283-c538-907c-83db-ad6bd99402bb
* Content: [Switch to Microsoft Defender for Endpoint - Setup](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-mde-phase-2?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@Nosferatu-Dk Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/8992

Once the author approves, the changes will be live.

Thanks
Sri
