### ISSUE TITLE
Fix release notes for March-2022

### ISSUE THREAD

**Issue by PiotrWadolowski** [MicrosoftDocs/microsoft-365-docs#8994]
For March-2022 update there is "No known issues" but there is March-2022*UPDATE* that points our that there is known issue with first one.  

"Customers who applied the March 2022 Microsoft Defender engine update (1.1.19100.5) might have encountered high resource utilization (CPU and/or memory). Microsoft has released an update (1.1.19200.5) that resolves the bugs introduced in the earlier version. Customers are recommended to update to this new engine build of Antivirus Engine (1.1.19200.5). To ensure any performance issues are fully fixed, it is recommended to reboot machines after applying update."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c01ab32b-6045-10f0-2a73-598961814f55
* Version Independent ID: 5bdbaa76-52aa-9330-fb23-03e90a28e32f
* Content: [Manage Microsoft Defender Antivirus updates and apply baselines](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus?view=o365-worldwide#security-intelligence-updates)
* Content Source: [microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @PiotrWadolowski and thank you for the feedback. I have updated the article, and you'll see the changes live a little later today (around 11 a.m. Pacific Time). Thank you for the suggestion!
