### ISSUE TITLE
Do you have informations about this EventID 54?

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/microsoft-365-docs#8996]
EventID 54
Source Microsoft-Windows-SENSE/Operational
Global (per-pattern) state changed. State: **0x1**, pattern: **0x9**
Global (per-pattern) state changed. State: **0x0**, pattern: **0x9**

Do you have informations about this EventID 54?
Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adae9e5b-5f3d-3bb9-e25c-25c82b4b044e
* Version Independent ID: f9b3f4ee-4037-93f2-e1c1-6e793756863a
* Content: [Review events and errors using Event Viewer](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/event-error-codes?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/event-error-codes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/event-error-codes.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@PehDeh Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9048

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PehDeh Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
