### ISSUE TITLE
permissions  - needs to be updated

### ISSUE THREAD

**Issue by phillkOCCM** [MicrosoftDocs/microsoft-365-docs#900]
search & purge is not visible as a role group, not addable to pre-existing org roles & is only provided by organizational admin (of security center) this needs to be reviewed & corrected, plz.
Also, for org's starting to use AIR, this information (regarding permissions) was hard to find, and could be indicated better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de70c835-f408-83a6-3cc7-885756bd7152
* Version Independent ID: 076708dd-80e4-39d7-7e23-42730c106900
* Content: [Automated incident response (AIR) in Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/automated-investigation-response-office#required-permissions-to-use-air-capabilities)
* Content Source: [microsoft-365/security/office-365-security/automated-investigation-response-office.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/automated-investigation-response-office.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@phillkOCCM thank you for the feedback. I have updated the article to include mention that a new role group might need to be created in the Office 365 Security & Compliance Center and that the Search and Purge role can be added to that new role. I will likely make further revisions in the coming weeks as well. I'm going to close this issue out for now, but please let me know if you have any other questions. And please keep the feedback coming--you are helping us improve the quality of our documentation. Happy Holidays!
