### ISSUE TITLE
Get-Mailbox does not work for Teams mailbox

### ISSUE THREAD

**Issue by VincentXu2021** [MicrosoftDocs/microsoft-365-docs#9002]
In Microsoft Teams, each team will have a mailbox in the format of "TeamName@fulldomain". I am unable to run Get-Mailbox command against the team mailbox. It says object is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac0819e-2ed8-d57f-35f5-cfa5210210a9
* Version Independent ID: 61bf03a8-091b-9a33-a7eb-a4a25e8452f3
* Content: [Delete items in the Recoverable Items folder - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold?view=o365-worldwide#step-3-remove-all-holds-from-the-mailbox)
* Content Source: [microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @VincentXu2021 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
