### ISSUE TITLE
Page missing directions when Edit service address is not clickable

### ISSUE THREAD

**Issue by BMORT17** [MicrosoftDocs/microsoft-365-docs#9013]
This tutorial page does not provide instructions for the user (e.g. me) how to enable the "Edit service usage address" text. See attached screenshot. I don't know how or why I can't edit this. NOTE: I am a Global Admin, or at least I believe I am.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50536931-a7c8-620a-aae0-9c4baec51f74
* Version Independent ID: 27ce5737-2b34-cb55-07b0-c8450c0e5d62
* Content: [Change your billing addresses](https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/billing-and-payments/change-your-billing-addresses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee*
[editServiceUsageAddress.pdf](https://github.com/MicrosoftDocs/microsoft-365-docs/files/8979046/editServiceUsageAddress.pdf)
*

**Comment by msbemba** [comment]
@BMORT17 Thank you for your feedback. I tested it in multiple tenants and the Edit service usage address tab appears. If it does not appear, I'd first check if you have global admin rights and if it is present I recommend you to contact Microsoft support via the need help option in the admin center as this looks more like a bug or a permissions issue on your tenant.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @BMORT17 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
