### ISSUE TITLE
The statement doesn't match my test result.

### ISSUE THREAD

**Issue by VincentXu2021** [MicrosoftDocs/microsoft-365-docs#9014]
It states: In order to create a case, the user must be in "eDiscovery Manager" role GROUP. However, this doesn't match my test result. When the user is NOT in "eDiscovery Manager" role GROUP, he can also create compliance case via Graph API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 327f05ec-cc23-3241-eb82-12d89ea0bfc8
* Version Independent ID: 327f05ec-cc23-3241-eb82-12d89ea0bfc8
* Content: [Search for and delete chat messages in Teams - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-and-delete-teams-chat-messages?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-and-delete-Teams-chat-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-and-delete-Teams-chat-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@VincentXu2021 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
