### ISSUE TITLE
REST API Auth for event based retention

### ISSUE THREAD

**Issue by stevensarginson** [MicrosoftDocs/microsoft-365-docs#9015]
Document details the use of basic auth for REST API. Mentions "complianceuser" and "compliancepassword" with no insight into where these fields are set. Are we using azure AD? What permissions need to be assigned? What about MFA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad33cc1-dc5f-d9f9-ee8e-b103839945ef
* Version Independent ID: 1bc3101d-afe8-2056-3cda-6a86a209c460
* Content: [Start retention when an event occurs - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @stevensarginson 

The authentication fields are available when you select "Show advanced options" in the connector and are the equivalent to signing into Security & Compliance PowerShell from a PowerShell session. If you have permissions to create events in the compliance portal, that's all the permissions you need but if you need a specific reference: https://docs.microsoft.com/en-us/microsoft-365/compliance/get-started-with-records-management#permissions

MFA isn't supported, and better security is one of the reasons why we're switching to Graph API. 

If you haven't yet configured this with the REST APIs, I recommend you don't but wait for the Graph APIs, as documented in the Note now added to the top of this section. In the meantime, consider using the PowerShell cmdlets if you need automation?

**Comment by yogkumgit** [comment]
@stevensarginson Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
