### ISSUE TITLE
Broken "DeployMMA.cmd" script example

### ISSUE THREAD

**Issue by MartinVokurek** [MicrosoftDocs/microsoft-365-docs#9016]
The example onboarding script does not work. It has incorrectly wrapped lines and an extra ')' at the end.

Proposed change:
 ```dos 
 @echo off  
 cd "C:" 
 IF EXIST "C:\Program Files\Microsoft Monitoring Agent\Agent\MonitoringHost.exe" (  
 exit 
 ) ELSE ( 
  
 wusa.exe C:\Windows\MMA\Windows6.1-KB3080149-x64.msu /quiet /norestart 
 wusa.exe C:\Windows\MMA\Windows6.1-KB4074598-x64.msu /quiet /norestart 
 wusa.exe C:\Windows\MMA\Windows6.1-KB3154518-x64.msu /quiet /norestart 
 wusa.exe C:\Windows\MMA\Windows8.1-KB3080149-x64.msu /quiet /norestart 
 "c:\windows\MMA\MMASetup-AMD64.exe" /c /t:"C:\Windows\MMA"
 c:\windows\MMA\setup.exe /qn NOAPM=1 ADD_OPINSIGHTS_WORKSPACE=1 OPINSIGHTS_WORKSPACE_ID="<your workspace ID>" OPINSIGHTS_WORKSPACE_KEY="<your workspace key>" AcceptEndUserLicenseAgreement=1

 ) 

 ``` 

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/ddf98f84d65428d440d1e3fabfad2e0c693c08c9/microsoft-365/security/defender-endpoint/onboard-downlevel.md?plain=1#L212-L229

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3985e3b-6df1-892c-be7c-8b1f079b4053
* Version Independent ID: 61fee405-9ccd-cf53-4aa1-4c5e98f09cf7
* Content: [Onboard previous versions of Windows on Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-downlevel?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-downlevel.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-downlevel.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@MartinVokurek Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9049

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MartinVokurek Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
