### ISSUE TITLE
Vague instructions on how to delete a bookings calendar

### ISSUE THREAD

**Issue by justinjbird** [MicrosoftDocs/microsoft-365-docs#9020]
Specifically this;

> On the Active Users page, choose the names of the users that you want to delete, and then select Delete user.

This is vague explanation of what is required. What users? Are we to assume that a bookings calendar is represented as a specific user in admin.microsoft? If so, how do we know what it is called? Assumed that this is the case, it could be more explicit explaining this...

> your calendar will be represented as a user in your organisation, find the user with the same name as your calendar (?) and delete it

...or something to that affect. How does a calendar assign itself if a user already exists with the same name? Needs better clarity on what is being deleted.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa612c0e-c089-8b3e-8e2e-dd12b6fc382c
* Version Independent ID: fa014ea6-7aa2-b2bd-d913-165c3241675f
* Content: [Delete a booking calendar](https://docs.microsoft.com/en-gb/microsoft-365/bookings/delete-calendar?redirectSourcePath=%252fen-us%252farticle%252fDelete-a-booking-calendar-8c3a913c-2247-4519-894d-b6263eeb9920&view=o365-worldwide)
* Content Source: [microsoft-365/bookings/delete-calendar.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/delete-calendar.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@justinjbird Thank you for your feedback. The Bookings calendar is a mailbox in Exchange Online so you delete the corresponding user account through the admin center to delete the booking calendar. This has been updated in the document to reduce ambiguity.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @justinjbird Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
