### ISSUE TITLE
Flo 

### ISSUE THREAD

**Issue by Francesco219** [MicrosoftDocs/microsoft-365-docs#9023]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4e2ac78-e08b-d7c8-5eec-baf9e9c13b62
* Version Independent ID: 66014f69-00c9-0e9b-fe0a-d0e10f2ca5eb
* Content: [About registration numbers and under-review notifications](https://docs.microsoft.com/en-us/microsoft-365/commerce/about-registration-numbers?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/about-registration-numbers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/about-registration-numbers.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by Francesco219** [comment]
Flo

**Comment by msbemba** [comment]
@Francesco219 Thank you for your feedback. Are you referring to Microsoft Flow? This registration is not specific to any services Flow, but for the entire Office Subscription.

Hope this helps!

Thanks
Sri
