### ISSUE TITLE
Storage Permissions tasks is missing from guide

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/microsoft-365-docs#9024]
Hi, seems that the description for tasks to grant app permissions for storage is missing from guide now. Only the image after "The app configuration policy for Defender for Endpoint autogranting the storage permission is now assigned to the selected user group.", but above does not talk about need to create this policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60db9275-9265-ebca-a145-3a3eede2353a
* Version Independent ID: 9d19ab3c-eb32-4211-14d9-559998589eb3
* Content: [Deploy Microsoft Defender for Endpoint on Android with Microsoft Intune](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/android-intune?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/android-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/android-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Kazzan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9141

Once the author reviews and approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Kazzan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
