### ISSUE TITLE
Missing closing brackets or wrong character used

### ISSUE THREAD

**Issue by gonz-kelv** [MicrosoftDocs/microsoft-365-docs#9029]
In the Section, What label policies can do, the explanation seems to miss the closing bracket or wrong character was used.

![image](https://user-images.githubusercontent.com/8866096/175832383-0c4437d7-34f8-40ce-8890-93b2815075a6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Learn about sensitivity labels - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@gonz-kelv Thanks for flagging - yes, missing ending parenthesis. Easy to do in Markdown after a link but now fixed & lined up to publish tomorrow.
