### ISSUE TITLE
Escape special characters in SAS URL for CMD.exe

### ISSUE THREAD

**Issue by aaas-jbrown** [MicrosoftDocs/microsoft-365-docs#903]
It should probably be noted somewhere in the document that while using the AzCopy tool via CMD.exe you will need some special characters in the SAS URL to be escaped.  Particularly `&` -&gt; `^&` and `%` -&gt; `%%`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files#feedback)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@aaas-jbrown Thanks for the heads up. I assume that you're enclosing the SAS value with double-quotation marks.  What is the error if you don't escape these characters? I've never run into this is PST import or other solutions that use SAS URLs (e.g. exporting Advanced eDiscovery search results).

**Comment by aaas-jbrown** [comment]
This seems to be mainly variations in how CMD process things differently when typed via the console or if run via script/batch.

When entering commands directly on the command line it takes the SAS URL UN-escaped (as long as using quotes, of course).  However, if you put the same commands into a script and then run that it will fail due to special character parsing.  Here is a simple sample of the issue with a test import:

```
c:\scripts>type x.cmd
"c:\program files (x86)\microsoft sdks\azure\azcopy\azcopy.exe" /s /y /v:"c:\scripts\azcopy.log" /source:"C:\pst" /dest:"UNESCAPED_SAS_URL"

c:\scripts>"c:\program files (x86)\microsoft sdks\azure\azcopy\azcopy.exe" /s /y /v:"c:\scripts\azcopy.log" /source:"C:\pst" /dest:"UNESCAPED_SAS_URL"
[2019-12-09 15:32:25] AzCopy is cancelling the transfer; this may take a while...
Finished 0 of total 3 file(s).
[2019-12-09 15:32:25] Transfer summary:
-----------------
Total files transferred: 3
Transfer successfully:   0
Transfer skipped:        0
Transfer failed:         3
Elapsed time:            00.00:00:04
[2019-12-09 15:32:25][WARNING] Error happened in several transferring, refer to c:\scripts\azcopy.log for detailed information.

c:\scripts>x.cmd

c:\scripts>"c:\program files (x86)\microsoft sdks\azure\azcopy\azcopy.exe" /s /y /v:"c:\scripts\azcopy.log" /source:"C:\pst" /dest:"MALFORMED_UNESCAPED_SAS_URL"
[2019-12-09 15:32:29][ERROR] The syntax of the command is incorrect. Invalid SAS token in parameter "Dest". Value of "se" is invalid in SAS token.

c:\scripts>
```

For security reasons I've redacted our actual SAS URLs, but cmd processing is stripping out the single `%` character from the URL encodings for things like `%3a`

This isn't major, but it was something that had me scratching my head for awhile the first time I ran into it.

**Comment by markjjo** [comment]
@aaas-jbrown Thanks for the reply and detailed explanation. I'll look at adding a footnote about using escape characters in the table that describes the azcopy parameters.
