### ISSUE TITLE
Microsoft 365 Groups now support nested membership

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9036]
An update is needed to the Microsoft 365 Group section as Microsoft 365 Groups now support nested membership. Reference Message center change MC394932 .

Therefore the current sentence is incorrect 

    _'Microsoft 365 Groups don't support nesting with other Microsoft 365 Groups or with distribution or security groups.
    [Enter feedback here]'_

Message center change MC394932 Create "Nested" Groups with Azure AD Dynamic Groups (preview) published 24 Jun 2022 now a
This feature will help you better manage group memberships by allowing you to build dynamic Azure AD Security Groups and Microsoft 365 groups based on other groups. For example, you can now create Dynamic-Group-A with members of Group-X and Group-Y.

The groups that define the membership of the dynamic group can be any group type represented in Azure Active Directory, such as user or device security groups, Microsoft 365 groups, and groups synced from on-premises. Unlike existing nested security groups today, memberOf dynamic groups return a flat list of members, so they can be used for licensing assignment and application assignment.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a37b2d3-f63b-a719-565b-a46f2b1f2e96
* Version Independent ID: e267656e-4bda-f03b-4d9c-d5149ec0a227
* Content: [Compare groups - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide)
* Content Source: [microsoft-365/admin/create-groups/compare-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/create-groups/compare-groups.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by DMoenks** [comment]
As much as I welcome the feature announcement, from an administrative point of view I would rather prefer to not directly have the result called **nesting** in the documentation, at least as long as the feature is still in preview. My reasons would be the following:

1. Based on the feature description, users of group X and Y would be made direct members of group A. Although the usability of membership information would match that of nested groups, the groups wouldn't be nested for real, and it would always take a dynamic membership refresh interval to work as expected.
2. As dynamic group membership provides the technical base for this feature, simply calling it **nesting** would belittle the possibilities, as group A could also consist of just members of group X and Y located in Spain, while excluding all others.
3. Real nesting would allow groups X and Y to be members of group A, which itself could be a member of group M. I really wonder how (or better: if) this would work with dynamic group memberships and the refresh interval. Would such cases also work within a single interval? Would it take _nesting levels - 1_ intervals to work?

Nesting would of course make for one good exemplary use case in the documentation, although that would probably be a part of [Dynamic group rules syntax](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-dynamic-membership).

That's just my two cents though, and I can very much understand if calling is **nesting** would help promote the feature.

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. I have made changes via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9074

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
