### ISSUE TITLE
Defender passive mode

### ISSUE THREAD

**Issue by a-gbusuioc** [MicrosoftDocs/microsoft-365-docs#9039]
Hello,

In this article it is mentioned that "You can set Microsoft Defender Antivirus to passive mode using PowerShell, Group Policy, or a registry key" on Windows Server 2012R2, 2016 and 2019. 
The policy mentioned for changing the Defender state to Passive mode is "Turn Off Microsoft Defender Antivirus" which enforces a running or disabled state based on the option choosed, but never a Passive mode state. 

Screenshots with the GPO:
![image](https://user-images.githubusercontent.com/108343453/176180614-cb4867c5-050d-4b4b-91e5-6394aaf78b58.png)

The only way to change the Defender AV state to passive on Windows Servers is with the Registry Key Method. 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61024433-366d-5ea3-4a3f-0cdd5cdcd900
* Version Independent ID: 348d3fc9-0937-b3a6-897e-09d1236d7019
* Content: [Microsoft Defender Antivirus compatibility with other security products](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide#how-to-confirm-the-state-of-microsoft-defender-antivirus)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@a-gbusuioc Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9139

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by denisebmsft** [comment]
Thank you @a-gbusuioc for posting your question here, and thank you @msbemba for the pull request. It's now merged. Please let us know if you have any other questions.
