### ISSUE TITLE
microsoft defender endpoint development machine configuration

### ISSUE THREAD

**Issue by FrederickEngelhardt** [MicrosoftDocs/microsoft-365-docs#9047]
Question: How do I configure security policies for real-time protection on development computers using a ton modern technologies.

Use case:
A Company needs to secure machines but there a 1000 plus difference processes that defender can scan that are development only.

**Is there a policy or a recommended config template that can be documented for microsoft defender endpoint security for macs?**

Why this needs to be public information:
- Companies that enact defender on development machines can potentially increase a development task's time by 1000s of times. Example running `rm -rf node_module` could take 20 minutes vs 1min.
- So far from the docs it looks like all frequently used development processes need to be manually ignored in order to avoid these bottlenecks.

**Comment by FrederickEngelhardt** [comment]
Does microsoft have recommendations regarding **process/folder exclusions related to Real-Time protection** for developers using the MacOS platform?

I see a bunch of documentation regarding android development for windows defender but microsoft defender Endpoint does not cover exclusions.

The docs would need to be gear towards security team JAMF deployment exclusions for Mac OS.

Something like the [Defender Performance article ](https://docs.microsoft.com/en-us/windows/android/defender-settings) but for microsoft defender ATP (mac)

Tutorials and recommendations for the following software development exclusions:
- nodeJS development (yarn, node, npm, node_module) folder/process exclusions
- android development
- ios development (frequently build artifacts and cache would be scanned)
- java development
- mac base environment IE commands like (rm, find, grep, tar, gzip)
- mac environment caching and base path exclusions (IE when tar unpacks to a temp directory should it be scanned 1 time during unpack or two times if it is unpacked and then later moved to a directory and then scanned)

My hope is having more recommendations would help shed some light on performance improvements and potential efficiency loss development machines can have it these performance improvements are not implemented.

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Please contact support.
