### ISSUE TITLE
Typo on line 37

### ISSUE THREAD

**Issue by GarrettLMurphy** [MicrosoftDocs/microsoft-365-docs#905]
There is a line 37 which says Sing-in rather than Sing-in rather than Sign-in

**Comment by mypil** [comment]
@GarrettLMurphy - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@GarrettLMurphy - We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.

If there is a specific area of the docs that we can improve on, please feel free to open a new issue by clicking on the Feedback section on the specific Microsoft doc which is found at the bottom of the page. Thank you.
