### ISSUE TITLE
Are these activities (create an I) Auditable\ restrictable 

### ISSUE THREAD

**Issue by koike-a** [MicrosoftDocs/microsoft-365-docs#9051]
<html>
<body>

<h2 id="activities-that-can-be-restricted-on-macos">Activities that can be restricted on macOS</h2>
<p>Once a macOS device is onboarded into Microsoft Purview solutions, you can monitor and restrict these actions with data loss prevention (DLP) policies.</p>
<p><strong>Copy to a USB removable media</strong> – when enforced, this action blocks, warns or audits the copying or moving of protected files from an endpoint device to USB removable media</p>
<p><strong>Copy to network shares</strong> – when enforced, this action blocks, warns, or audits the copying or moving of protected files from an endpoint device to any network share</p>
<p><strong>Print</strong> – when enforced, this action blocks, warns, or audits when protected files are printed from an endpoint device</p>
<p><strong>Copy to clipboard</strong> – when enforced, this action blocks, warns, or audits data in protected file that is being copied to a clipboard on an endpoint device</p>
<p><strong>Upload to cloud</strong> – this action blocks, warns, or audits when protected files are prevented from or allowed to be uploaded to cloud services based on the allow/unallowed domains list in global settings. When this action is set to warn or block, other browsers (defined on unallowed browsers list under Global settings) are blocked from accessing the file.</p>
<p><strong>Accessed by unallowed apps</strong> – when enforced, this action prevents applications that are on the unallowed apps list (as defined in Global settings) from accessing protected files on an endpoint device. Sample scenarios</p>
  | <h2 id="onboarding-devices-into-device-management">Onboarding devices into device management</h2>

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07fe1d95-0032-b21b-1bd2-735c1e0f7d76
* Version Independent ID: 07fe1d95-0032-b21b-1bd2-735c1e0f7d76
* Content: [Onboard macOS devices into Microsoft 365 overview - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-macos-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/device-onboarding-macos-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/device-onboarding-macos-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by koike-a** [comment]
Thank you for reviewing and replying to my request.
I am waiting for the changes to be reflected in the document.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @koike-a Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
