### ISSUE TITLE
Clarify Conditional Access controls

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/microsoft-365-docs#9052]
Please clarify on the Conditional Access Policy Controls. The article states 
> For this feature to not trigger on a managed device, an eligible Azure AD Premium P1 or P2 subscription, and a specific Conditional Access policy, is required. **See below for further details.**

But there are no further details below regarding "not triggering on managed devices". Instead the following paragraph is about "Idle session timeout on **unmanaged** devices".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Version Independent ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Content: [Idle session timeout for Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/idle-session-timeout-web-apps?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/idle-session-timeout-web-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@diecknet Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9132

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by blakebourgeois** [comment]
This still does not make sense with the new PR. 

The changed section still refers to "for this feature to **not trigger** on an unmanaged device...a specific Conditional Access policy is required. See below for further details."

The next section, "Idle session timeout on unmanaged devices" reads "for idle session timeout to get triggered on unmanaged devices, you'll need to add a Conditional Access policy."

So which is it? For idle session timeout on unmanaged devices, is the CA policy required for it to work at all? Or is a CA policy required to exempt specific users/situations?

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @diecknet Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
