### ISSUE TITLE
Remove 1607 Version

### ISSUE THREAD

**Issue by CL20220101** [MicrosoftDocs/microsoft-365-docs#9053]
[Enter feedback here]
1607 does not work and is already EOS. Could you correct it? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8690a332-f672-8db8-1552-5ee16e78746f
* Version Independent ID: 3df5b553-4e29-da25-c0e4-10686c5fed20
* Content: [Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-endpoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@CL20220101 Thank you for your feedback. You are right the Version is EOS. I'm not able to locate that information on this document. Could you please confirm if this is the URL for the document - https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint?view=o365-worldwide ?

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@CL20220101 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/memdocs/pull/2925

Once the author approves, the document will be updated.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit  The author is "mestew "

**Comment by CL20220101** [comment]
Thanks a lot!

Christina

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CL20220101 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by CL20220101** [comment]
Hi,

I still see it written 1607. No changes. Please check again, thanks.

https://docs.microsoft.com/zh-tw/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection
[image: image.png]

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@CL20220101 The main document is updated https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection 

The other locale files like zh-tw will get updated soon.

Thanks
Sri

**Comment by CL20220101** [comment]
Could you inform me when it has been updated? Thank you.
