### ISSUE TITLE
Needs pricing information

### ISSUE THREAD

**Issue by scotttromley** [MicrosoftDocs/microsoft-365-docs#9059]
This page is great, except there is no information about the cost of licenses once the trial expires, and no link to a page that indicates that pricing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a75292aa-c461-5df8-af9d-1876c97c15ff
* Version Independent ID: d80dc3cd-95f9-cc52-7d4d-4151c1e5617d
* Content: [About the Microsoft Defender for Office 365 trial - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/about-defender-for-office-365-trial?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/about-defender-for-office-365-trial.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/about-defender-for-office-365-trial.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@scotttromley, OK, fixed.

Thanks for the feedback.

Closing
