### ISSUE TITLE
Out of date instructions

### ISSUE THREAD

**Issue by GeoffWalsh** [MicrosoftDocs/microsoft-365-docs#9060]
Following documentation "$RMSConfig = Get-AadrmConfiguration"
Looking up Get-AadrmConfiguration it is part of the "AADRM" module which states "the AADRM module is now deprecated" and "only as an alias to its replacement in the AIPService module.".

It would be so much easier if we didn't have to follow so many different page look-ups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fe08d5e-4870-331e-b5f2-92848b5211b0
* Version Independent ID: 60ed3095-a42c-1bcb-f2fa-8325cfcd03f6
* Content: [Set up Microsoft Purview Message Encryption - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-new-message-encryption-capabilities?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-new-message-encryption-capabilities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-new-message-encryption-capabilities.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @GeoffWalsh Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
