### ISSUE TITLE
KQL for DLP have error when running in Sentinel

### ISSUE THREAD

**Issue by BenjiSec** [MicrosoftDocs/microsoft-365-docs#9063]
When you run KQL for raw data enrichment, it throws errors
https://docs.microsoft.com/en-us/microsoft-365/security/defender/investigate-dlp?view=o365-worldwide#dlp-investigation-experience-in-microsoft-sentinel

If we change it like before, it works then

let Alert = SecurityAlert
| where TimeGenerated  > ago(30d)
| where SystemAlertId == ""; // insert the systemAlertID here
CloudAppEvents 
| extend correlationId1 = parse_json(tostring(RawEventData.Data)).cid
| extend correlationId = tostring(correlationId1)
| join kind=inner Alert on $left.correlationId == $right.AlertType 
| where RawEventData.CreationTime > StartTime and RawEventData.CreationTime < EndTime

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a16886b-00ab-0632-956f-f2494e4331da
* Version Independent ID: 3a16886b-00ab-0632-956f-f2494e4331da
* Content: [Investigate data loss incidents with Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/investigate-dlp?view=o365-worldwide#dlp-investigation-experience-in-microsoft-sentinel)
* Content Source: [microsoft-365/security/defender/investigate-dlp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/investigate-dlp.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@BenjiSec Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9122

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @BenjiSec Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
