### ISSUE TITLE
Hard to read to find out how to change the global settings for the frequency

### ISSUE THREAD

**Issue by tdo365** [MicrosoftDocs/microsoft-365-docs#9064]
Because in this section things are listed as steps it is very hard to know that at the very bottom step 6 there is a way to change the frequency in days. There is also no visual to accompany this. 

I would also like the disclaimer that the global setting controls all of the quarantine settings themselves you can't change one of them.

Please also on the step 1 and step 2 include a screenshot of what the quarantine policy page looks like as it's quite new and it used to be something that was in the settings for anti-spam previously.

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide#configure-global-quarantine-notification-settings-in-the-microsoft-365-defender-portal

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @tdo365 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
