### ISSUE TITLE
"Data governance > Import" incorrect

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/microsoft-365-docs#907]
Step 1.2 "In the left pane of the Security & Compliance Center, click Data governance &gt; Import."

This should be Information Governance &gt; Import

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files#feedback)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@campbellkerr Thanks for the heads up. This is fixed and updated topic will be live later today.
