### ISSUE TITLE
Message submission format example incorrect

### ISSUE THREAD

**Issue by gunterda** [MicrosoftDocs/microsoft-365-docs#9076]
"Both of these messages are being reported as Not Junk based on Subject." is probable not correct, because the first example starts with 3| which is the number for Phish.

Cheers,
Gunter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User reported message settings - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by chrisda** [comment]
OK. Fixed.

Thanks for the feedback.

Closing
