### ISSUE TITLE
Installing Windows Defender on Server 2016

### ISSUE THREAD

**Issue by arielf-mn** [MicrosoftDocs/microsoft-365-docs#9077]
In the documentation, it states to use this command when installing via a Task Sequence:

c:\windows\**sysnative**\cmd.exe /c Dism /online /Enable-Feature /FeatureName:Windows-Defender-Features
c:\windows\**sysnative**\cmd.exe /c Dism /online /Enable-Feature /FeatureName:Windows-Defender

Should it be:

c:\windows\**System32**\cmd.exe /c Dism /online /Enable-Feature /FeatureName:Windows-Defender-Features
c:\windows\**System32**\cmd.exe /c Dism /online /Enable-Feature /FeatureName:Windows-Defender

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42db2345-0d5c-45f3-6c24-d84a12775fb7
* Version Independent ID: 1634b283-c538-907c-83db-ad6bd99402bb
* Content: [Switch to Microsoft Defender for Endpoint - Setup](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-mde-phase-2?view=o365-worldwide#re-enable-microsoft-defender-antivirus-on-windows-server-2016)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @arielf-mn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
