### ISSUE TITLE
ProcMon 3.60 no longer available

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/microsoft-365-docs#9078]
This page says to download procmon version 3.60, and provides a link to the general procmon download page.  3.60 was superseded many releases ago and is no longer available for download on the linked page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a08b6ae-6445-ab2b-d380-627df46cf3d5
* Version Independent ID: c855d3af-002e-aff2-b2d6-8c6e549850a2
* Content: [Troubleshoot performance issues](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-performance-issues?view=o365-worldwide#analyze-the-microsoft-protection-log)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-performance-issues.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-performance-issues.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @dloder0 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
