### ISSUE TITLE
Please add an applies to section to define which clouds have this capability

### ISSUE THREAD

**Issue by jongross4** [MicrosoftDocs/microsoft-365-docs#9081]
As with all features, a section should exist to say if the feature is available in government, china, germany clouds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Version Independent ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Content: [Idle session timeout for Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/idle-session-timeout-web-apps?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/idle-session-timeout-web-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@jongross4 Thank you for your feedback. Idle session timeout isn't available for Microsoft 365 operated by 21Vianet, or Microsoft 365 Germany. This has been added as an important note to the top of the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9134

Once the author approves, the  changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jongross4 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
