### ISSUE TITLE
Please consider adding the licensing level needed for this feature.

### ISSUE THREAD

**Issue by thomasjsweet** [MicrosoftDocs/microsoft-365-docs#9082]
[Enter feedback here]
Please consider adding the licensing level needed.  I have Microsoft 365 Business Premium. It has some of the Purview features, but not all.  I know this feature is new.  In some screens in the M365 portal, it shows me has having an E3 license.  I cannot access the "devices" feature listed in this article with my M365 Business Premium license - it does not show.

thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76da4eda-4ccf-ff34-6a48-d9c5553c2ed6
* Version Independent ID: 7e887aff-1b85-1651-2bff-63425c54ae63
* Content: [Using Endpoint DLP - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-using?view=o365-worldwide#dlp-settings)
* Content Source: [microsoft-365/compliance/endpoint-dlp-using.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-using.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@thomasjsweet Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9135 and would like to have the author review and approve before the changes go live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @thomasjsweet Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
