### ISSUE TITLE
Message Header Analyzer URL Outdated

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#9084]
In the linked article for the Message Header Analyzer, there are instructions which are outdated (for older clients, and do not include a working link to the Message Header Analyzer). 

Please either link to [here](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-spam-message-headers?view=o365-worldwide#:~:text=You%20can%20copy%20and%20paste%20the%20contents%20of%20a%20message%20header%20into%20the%20Message%20Header%20Analyzer%20tool.%20This%20tool%20helps%20parse%20headers%20and%20put%20them%20into%20a%20more%20readable%20format.) for the Message Header Analyzer tool part of the anti-spam headers article, _or_ please fix the linked article to include the link to the actual header analyzer tool directly at https://mha.azurewebsites.net/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f9293f-c337-7af6-e994-336531d62f35
* Version Independent ID: 36f9293f-c337-7af6-e994-336531d62f35
* Content: [Use Trusted ARC senders for legitimate devices and services between the sender and receiver - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @hudish Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
