### ISSUE TITLE
Contradictory statement

### ISSUE THREAD

**Issue by adamfowlerit** [MicrosoftDocs/microsoft-365-docs#9085]
"Group owners will only be notified via email. If the group was created via Planner, SharePoint, or any other app, the expiration notifications will always come via email. If the group was created via Teams, the group owner will receive a notification to renew through the activity section."

This paragraph contradicts itself.
This section states that group owners will only be notified by email, but then says in a scenario they will receive a notification through teams activity section. It also isn't clear if the teams notification replaces email or is in addition to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979f0a6e-be32-af1e-5724-d1104ebe3ef5
* Version Independent ID: cb9b993a-2224-5bb8-64b8-d1afa7a71c8e
* Content: [Microsoft 365 group expiration policy](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-groups-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@adamfowlerit Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9136

Once the author reviews and approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @adamfowlerit Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
