### ISSUE TITLE
Explanation pattern type was substituted by regular expressions

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/microsoft-365-docs#9086]
(https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/explanation-types-overview#phrase-list)
Patterns are named here but not possible to select them any longer. Only phrase list and regular expressions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea6e11b-2884-3ae0-9416-be51af65ecaf
* Version Independent ID: 3393bb9c-317d-4338-7048-a28fe5d34858
* Content: [Step 1. Use SharePoint Syntex to identify contract files and extract data - SharePoint Syntex](https://docs.microsoft.com/en-us/microsoft-365/contentunderstanding/solution-manage-contracts-step1)
* Content Source: [microsoft-365/contentunderstanding/solution-manage-contracts-step1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/solution-manage-contracts-step1.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by chuckedmonson** [comment]
@yogkumgit -- Thank you for pointing that out, and the article has been updated. Changes should be live shortly. Thanks again.
