### ISSUE TITLE
how to we whitelist an url?

### ISSUE THREAD

**Issue by securityprivateers** [MicrosoftDocs/microsoft-365-docs#9090]
when MS gets it wrong, how do we whitelist a URL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1541da6f-af9a-05d5-fa34-b1a5df61424f
* Version Independent ID: 88e111ed-67f7-41bc-d823-863ee7ea2a2e
* Content: [Set up Safe Links policies in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-safe-links-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-safe-links-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-safe-links-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@securityprivateers, use the Tenant Allow/Block List:

<https://docs.microsoft.com/microsoft-365/security/office-365-security/allow-block-urls>

You should also report the URL as not bad:

<https://docs.microsoft.com/microsoft-365/security/office-365-security/admin-submission>

**Comment by yogkumgit** [comment]
@securityprivateers Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
