### ISSUE TITLE
POST /groups specifying creator

### ISSUE THREAD

**Issue by KvnSearle** [MicrosoftDocs/microsoft-365-docs#9093]
Hi,

I have inherited a system to maintain whereby groups and teams are created using calls to the API at https://graph.microsoft.com/v1.0.

I need to adapt it to include a preferred data location

Looking at the information at [https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http), it states that "The value of the preferredDataLocation property is inherited from the group creator's preferred data location.".

I see examples of requests specifying owners but not creators. Is an owner the same as a creator?

If not, is it possible to specify the creator is when calling the create group end point so the group can use that to work out the preferred data location for the group and set it by default?

If not is it possible to specify the preferred location when calling the create group end point?

Thanks

**Comment by yogkumgit** [comment]
@KvnSearle Thanks for your feedback. Please indicate which document you are referring to. Thanks

**Comment by DMoenks** [comment]
On a second thought, this might better be discussed in the [Microsoft Graph](https://github.com/microsoftgraph/microsoft-graph-docs/issues) repository. Although the preferred data location "inheritance" seems to apply independent of group creation method (e.g. Azure AD, Exchange, SharePoint, etc.), the use almost exclusively refers to Graph API calls and any matching example would probably be located in the other documentation repository in the long run.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@KvnSearle Thank you for your feedback. The Owner and the creator need not be the same. However, you post it in the Microsoft Graph repository -https://github.com/microsoftgraph/microsoft-graph-docs/issues so that the author can help you out with more information.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @KvnSearle Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
