### ISSUE TITLE
Exclusion wildcard details out of date?

### ISSUE THREAD

**Issue by CAT-hs** [MicrosoftDocs/microsoft-365-docs#9100]
Is this statement still accurate? 
> Currently, Microsoft Endpoint Configuration Manager does not support wildcard characters (such as * or ?).

We migrated to Defender for AV beginning last November, managing configuration using Endpoint Protection policies in CM and the exclusions with wildcard that we copied from our previous AV appear to be working fine. CM did not give an error, and the exclusions are showing up in the output of get-mppreference on endpoints.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87906607-83fd-8dc8-facb-89719390f824
* Version Independent ID: 92f3359d-84ac-90c3-33d5-513feffc4173
* Content: [Configure and validate exclusions based on extension, name, or location](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@CAT-hs Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9123

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CAT-hs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
