### ISSUE TITLE
Change Request; May I know whether we can add the Note about what the Rule Frequency based on? 

### ISSUE THREAD

**Issue by sally-chenn** [MicrosoftDocs/microsoft-365-docs#9101]
[Enter feedback here]
As the Rule Frequency is based on the Event Timestamp, not the Ingestion Time. Is it possible to add an additional note about this information？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf510e0-742e-fce6-787e-18eb8a22f42d
* Version Independent ID: 23b77843-cf19-aacb-47af-1f51792c76a0
* Content: [Create and manage custom detection rules in Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/custom-detection-rules?view=o365-worldwide#rule-frequency)
* Content Source: [microsoft-365/security/defender/custom-detection-rules.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/custom-detection-rules.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@sally-chenn  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9124

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sally-chenn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
