### ISSUE TITLE
"Manage Settings" > "Manage Providers"

### ISSUE THREAD

**Issue by SpitFire-666** [MicrosoftDocs/microsoft-365-docs#9104]
"Under Virus & threat protection settings, choose Manage settings."

I think "Manage providers" would be a more accurate way to check what AV is running? Just a suggestion! Cheers

![image](https://user-images.githubusercontent.com/38451588/177465609-026c8500-e837-4780-88d4-00a46cb20c7d.png)

![image](https://user-images.githubusercontent.com/38451588/177465639-426f8f08-55fa-4527-aa64-63a5b10d394f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e0a301-df45-adc1-14f6-3c9a31661d66
* Version Independent ID: 5e970966-d442-2019-29da-daeacecd8a0e
* Content: [Microsoft Defender Antivirus in Windows](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SpitFire-666 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
