### ISSUE TITLE
Defender for Cloud Licensing Query

### ISSUE THREAD

**Issue by Phildo76** [MicrosoftDocs/microsoft-365-docs#9105]
I'm a little confused about the licensing requirement for this feature - Security Configuration via Endpoint Manager when integrated with Defender for Cloud. Does this feature work with server endpoints onboarded via Defender for Cloud. If so which licensing model do i need to follow

Note exception says: : _If you have access to Microsoft Defender for Endpoint as part of a Microsoft Defender for Cloud only license (formerly Azure Security Center), the Security Management for Microsoft Defender for Endpoint functionality isn't available._

Regards,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e93f9bbd-5752-e28a-f32d-a01d81964c8f
* Version Independent ID: e93f9bbd-5752-e28a-f32d-a01d81964c8f
* Content: [Manage Microsoft Defender for Endpoint configuration settings on devices with Microsoft Endpoint Manager](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/security-config-management?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/security-config-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/security-config-management.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Please contact support.
