### ISSUE TITLE
Testing steps

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#911]
Hello,
Cannot make it work.
Didn't use old sensitivity labeling,
All sensitivity labels migrated to Office 365 labeling and did try to create a new label from Security portal,
Run command "Enable this preview by using Azure PowerShell",
Run command "Set-SPOTenant -EnableAIPIntegration $true ",
Waited more than 24 hours,
Still, the "Sensitivity" drop-down menu, not appear when creating new sites.
Maybe something missing in article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by cabailey** [comment]
@lightupdifire We have recently added additional information to this page and wondered if you're still experiencing the same problem?  If you are, and the additional information doesn't help unblock you, I recommend you contact Microsoft Support.

**Comment by lightupdifire** [comment]
Hello @cabailey 
Already worked with MS support, answers were like "it is public preview just rollout" so need to wait.
