### ISSUE TITLE
AMRunningMode = EDR in Block mode | Not Running | Normal

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#9116]
I don't understand what is written about the AMRunningMode. Is it correct?
We set the registry key, and see `Not running` , but after a short while (<1 hr) MDE kicks in and  the status is changed to `EDR Block Mode`. We do have the M365 Defender for Endpoint Advanced Setting `Enable EDR in block mode` set to On 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61024433-366d-5ea3-4a3f-0cdd5cdcd900
* Version Independent ID: 348d3fc9-0937-b3a6-897e-09d1236d7019
* Content: [Microsoft Defender Antivirus compatibility with other security products](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @andrePKI and thank you for posting your question here. Is the device in question onboarded to Defender for Endpoint? And are you using a non-Microsoft antivirus product on the device? It sounds like the capabilities are working correctly. I just want to make sure I understand your question and scenario correctly.

**Comment by andrePKI** [comment]
Yes, the device is onboarded into Defender for Endpoint (through integration with MDC, using unified onboarding method - the machine is connected through Azure Arc and the rest is automatic). We are using McAfee on the device too (and for now we would like to keep it)

**Comment by andrePKI** [comment]
O, and yes we have a number of support cases (!) open too, but I would like to know whether the documentation is right and complete in this subject.

**Comment by yogkumgit** [comment]
@denisebmsft

**Comment by denisebmsft** [comment]
Hello again @andrePKI, and thank you for clarifying your question. The procedure about AMRunningMode is intended to whether Microsoft Defender Antivirus is running on an endpoint. It isn't intended to be used to stop Microsoft Defender Antivirus from running. The behavior you are seeing seems correct -- if the endpoint is onboarded to Defender for Endpoint, it will enable Microsoft Defender Antivirus on the endpoint (active mode if there's not another antivirus product installed, and passive mode if a non-Microsoft antivirus product is installed on the endpoint). I will update the documentation to make that more clear. Thanks again, and I hope you have a great day!
