### ISSUE TITLE
Hidden files

### ISSUE THREAD

**Issue by peterdiaz33** [MicrosoftDocs/microsoft-365-docs#9117]
[Enter feedback here]

Does the table in the article apply to hidden files?

Thanks a million.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 820cb23f-f33d-241d-5ce2-1d824bcd3747
* Version Independent ID: 36d24f60-27b6-f2c1-ccda-1b49a1d4f073
* Content: [Learn about Endpoint data loss prevention - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-learn-about?view=o365-worldwide#endpoint-activities-you-can-monitor-and-take-action-on)
* Content Source: [microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @peterdiaz33 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
