### ISSUE TITLE
EDLP applies to hidden files?

### ISSUE THREAD

**Issue by fcsbnuesteaua** [MicrosoftDocs/microsoft-365-docs#9118]
Hello,
I am using EDLP to prevent data leakage, we are blocking Microsoft’s built-in file types and files that contain any text.

Once we hide those files behind other allowed files like jpg, link, etc., the mechanism can not see the hidden file, so actually any file can be leaked.

How we can solve this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 820cb23f-f33d-241d-5ce2-1d824bcd3747
* Version Independent ID: 36d24f60-27b6-f2c1-ccda-1b49a1d4f073
* Content: [Learn about Endpoint data loss prevention - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-learn-about?view=o365-worldwide#endpoint-activities-you-can-monitor-and-take-action-on)
* Content Source: [microsoft-365/compliance/endpoint-dlp-learn-about.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/endpoint-dlp-learn-about.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @fcsbnuesteaua Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
