### ISSUE TITLE
Step 3 does not work

### ISSUE THREAD

**Issue by gsiler** [MicrosoftDocs/microsoft-365-docs#9120]
[Enter feedback here]

I just added some entries to the Exchange Online GAL using these instructions. Step 3 did not work. It took a while, but I figured out the solution. The command that worked was the following:

   Import-Csv .\ExternalContacts.csv|%{Set-Contact -Identity $_.Name -StreetAddress $_.StreetAddress <etc.>} 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a89d95b8-dd24-b6d8-f8c6-5e3cadea21dc
* Version Independent ID: f0d492b0-d84d-9119-21be-a12d203fad04
* Content: [Bulk import external contacts to Exchange Online - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/bulk-import-external-contacts?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/bulk-import-external-contacts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/bulk-import-external-contacts.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@gsiler Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9290

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gsiler Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
