### ISSUE TITLE
Exclusions for folder and its subfolders?

### ISSUE THREAD

**Issue by SpitFire-666** [MicrosoftDocs/microsoft-365-docs#9121]
Came across this, however it's not clear if there's a way to make an exclusion for all subfolders. 

Eg for AppLocker, you'd use C:\Windows\* to allow anything/everything in the Windows folder and its subfolders

The line below is a bit confusing to me, especially as it says to use "multiple instances of *\" but the example shows "**\". 

"`If you want to exclude more than one folder, in a path, use multiple instances of *\ to indicate multiple nested folders (for example, c:\Folder**\Test)`"

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad81808-0605-037f-364e-9d061d593078
* Version Independent ID: 62044527-8d7e-3dea-d872-83638fe7b14c
* Content: [Attack surface reduction frequently asked questions (FAQ)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq.yml)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @martyav
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@SpitFire-666 Thank you for your feedback. Sorry about that, it should be read as 

If you want to exclude more than one folder, in a path, use multiple instances of \*\ to indicate multiple nested folders (for example, c:\Folder\*\*\Test)

We will get the document updated in the backend.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@martyav Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
Per email, the article has been updated.
Closing this issue.

cc: @yogkumgit
