### ISSUE TITLE
Downloading onboarding package process is different

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/microsoft-365-docs#9129]
I tried following to download the onboarding package, but I think they may be outdated.

**_In Microsoft 365 Defender portal, go to Settings > Endpoints > Device management > Onboarding_**

When I go to settings in the Defender Portal I get the following:

![image](https://user-images.githubusercontent.com/5460795/178020518-053b7357-33cc-4717-9c8b-b15342838990.png)

I do not see Endpoint mentioned anywhere in the page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd66a255-36e5-29dc-7610-d50ef8bca3f3
* Version Independent ID: 17375473-bc07-f8e5-a85f-d732bbba3d71
* Content: [Intune-based deployment for Microsoft Defender for Endpoint on Mac](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-install-with-intune?view=o365-worldwide#download-the-onboarding-package)
* Content Source: [microsoft-365/security/defender-endpoint/mac-install-with-intune.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-install-with-intune.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@Rykimaruh Thank you for your feedback. I was able to see the endpoints section in Settings. 

![image](https://user-images.githubusercontent.com/45987684/180246402-cfcefbf0-32a8-4b70-9032-cfc327fab581.png)

If this continues to be a problem, I'd recommend you contact Microsoft support via the need help link in the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Rykimaruh Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
