### ISSUE TITLE
Information Barriers Preview Invite

### ISSUE THREAD

**Issue by camlynch** [MicrosoftDocs/microsoft-365-docs#913]
Hello,

How do we obtain an invite to the preview access of information barrier policies for SharePoint and OneDrive via Compliance Admin Center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a69504d-a89f-5545-3f8f-0573c928d67f
* Version Independent ID: 2f42eaa3-a159-31de-a9d5-19762d34bc5a
* Content: [Information barriers overview](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers#feedback)
* Content Source: [microsoft-365/compliance/information-barriers.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @camlynch  - Thanks for your interest in the Information Barriers preview.  Please contact dhraju@microsoft.com about participating.

Thanks

Chris
