### ISSUE TITLE
Need added info about quarantine

### ISSUE THREAD

**Issue by JasenHicks7** [MicrosoftDocs/microsoft-365-docs#9130]
In Message Center post MC373880 we state the following:
"Note: Any entry migrated from the Safe Links Block List to the Tenant Allow/Block List will adopt the behavior of TABL. This means that any message with the URL present will be moved to Quarantine. "

Our documentation doesn't seem to have any mention about what exactly is happening to the messages nor any reference to quarantine that I can find.  Can we get a blurb clarifying the action results of configuring this as these actions are different from the previous "Safe Links Block List.?"
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide&viewFallbackFrom=o365-worldwiden%20you%27re%20finished%2C%20click%20Add.)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JasenHicks7, I added the following note:

> [!NOTE]
> The ["Block the following URLs" list in Safe Links policies](safe-links.md#block-the-following-urls-list-for-safe-links) is in the process of being deprecated. You can now manage block URL entries in the Tenant Allow/Block List. We'll attempt to migrate existing entries from the "Block the following URLs" list to block URL entries in the Tenant Allow/Block List. Messages containing the blocked URL will be quarantined.

OK?

**Comment by yogkumgit** [comment]
@JasenHicks7 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by JasenHicks7** [comment]
Thanks for the quick turnaround Chris.  I appreciate it as I have a meeting with a customer over this today.  The only other thing we might do is ensure we are mentioning the quarantine behavior in the documentation for the TABL as well.  The section "What to expect after you add an allow or blcok entry" might be a good place to drop this in.  Currently it only says "the entry should start working immediately" but doesn't say what the expected behavior is.

Manage your allows and blocks in the Tenant Allow/Block List - Office 365 | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide#what-to-expect-after-you-add-an-allow-or-block-entry>

Thank you,

Jasen Hicks
Customer Engineer
***@***.******@***.***>
[Microsoft]

________________________________

**Comment by chrisda** [comment]
In what I thought were the appropriate places, I added a line that states blocked URLs are quarantined:

> Messages containing the blocked URLs are quarantined.
