### ISSUE TITLE
Clarifications on full DMARC enforcement & emphasing careful implementation

### ISSUE THREAD

**Issue by J-Rey** [MicrosoftDocs/microsoft-365-docs#9140]
I believe the last sentence of the blue alert in section 7 should be

> If you're going to keep an allowed domain for an extended period of time, you should tell the sender to verify that their domain is authenticated and set to DMARC reject appropriately.

This better explains the need to have DMARC at full enforcement (indicating that should reject unauthenticated messages) for almost all unless they are undergoing initial deployment or have known issues causing DMARC validation failures that have yet to be resolved.

Also, there should be a gradual transition from monitoring only to quarantine at increasing levels to reject all unauthenticated messages which needs to be done with constant monitoring so I just mentioned "appropriately" as a hint that need to investigate how to implement without making things worse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed2861d-860e-5d27-9259-fb9db2187f4b
* Version Independent ID: 09ef5622-3a7e-30f9-00f9-4c5578f8e1ca
* Content: [Configure spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-create-anti-spam-policies)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@J-Rey, OK. Fixed.

Thanks for the feedback.

Closing
