### ISSUE TITLE
Confilicting/Different information on licensing requirements

### ISSUE THREAD

**Issue by alexlushsevernunival** [MicrosoftDocs/microsoft-365-docs#9142]
The two references to licensing on this page quote different requirements (https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md#licensing) states M365 E3 but (https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md#licensing-1) states Windows E3. Is the requirement one or the other, or either. Also I think Windows E3 should read Windows Enterprise E3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5df26b-9563-4810-f5b8-6997c9baa27c
* Version Independent ID: 006f5550-36b6-1de7-d3a5-63b85241df03
* Content: [Microsoft Defender for Endpoint Device Control Device Installation](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-device-control-device-installation?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Lovina-Saldanha
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@alexlushsevernunival Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9225

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @alexlushsevernunival Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
