### ISSUE TITLE
PUA default settings

### ISSUE THREAD

**Issue by KJ2256** [MicrosoftDocs/microsoft-365-docs#9143]
[Enter feedback here]
Does this mean that the PUA setting will be enabled by default?
If there are any conditions under which the PUA setting will be enabled, please let me know.

PUA protection is supported on Windows 10, Windows 11, Windows Server 2019, Windows Server 2022, and Windows Server 2016. In Windows 10 (version 2004 and later), Microsoft Defender Antivirus blocks apps that are considered PUA for Enterprise (E5) devices by default.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277950a2-8ece-d717-b02b-29dbe579b85b
* Version Independent ID: 9efa9a6f-519c-c3ca-f2e3-a902280231d9
* Content: [Block potentially unwanted applications with Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/detect-block-potentially-unwanted-apps-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @KJ2256 and thank you for posting your question here. I can see how that section is confusing, and I have revised the article. You'll see the updates render live later today. Essentially, if an organization's subscription includes Defender for Endpoint, then PUA protection is enabled by default.
