### ISSUE TITLE
Please provide additional information for troubleshooting false positives

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/microsoft-365-docs#915]
It is very easy to open headers and see that a message has been marked SFV:SPM. Obviously if we are on this page the message was probably marked as spam. When a message has been marked SFV:SPM (or otherwise) we need followup information to investigate and be proactive. Please provide more information to assist us in troubleshooting further. Perhaps more information about the list of rules that could have been triggered? There are a lot of headers available. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbab747e-1a43-037e-09ca-9c402deec602
* Version Independent ID: 1c6d8e28-034d-24d6-5732-b96475411d6b
* Content: [How to prevent false positives from happening in Office 365](https://docs.microsoft.com/en-us/microsoft-365/compliance/prevent-email-from-being-marked-as-spam#feedback)
* Content Source: [microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/prevent-email-from-being-marked-as-spam.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by MaratMussabekov** [comment]
Hello @ckssaas,
unfortunately Microsoft doesn't provide the list of rules that marked message as spam. For troubleshooting purpose, I would recommend you to use CAT and SFTY sections of message header. More information could be found [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/anti-spam-message-headers) (this link is also presented in "Note" in the original article).
Thank you

**Comment by ckssaas** [comment]
@MaratMussabekov Thanks, but again, not very helpful. Best.
