### ISSUE TITLE
Update request for KB "https://docs.microsoft.com/en-us/microsoft-365/compliance/apply-irm-to-a-list-or-library?view=o365-worldwide#apply-irm-to-a-list-or-library"

### ISSUE THREAD

**Issue by o365tatsuyan** [MicrosoftDocs/microsoft-365-docs#9152]
Customer's Request: Customer thinks this documention should be noted that these "credentials" are for AIP and not for SharePoint Online.

Current docoment
![image](https://user-images.githubusercontent.com/33974498/178466608-6cd7c685-f8a9-4fed-9606-9e3f7b192466.png)

The following explanation should be added to this description
* These caching credentials are not SharePoint Online permissions, but Azure RMS credentials.

**Comment by msbemba** [comment]
@o365tatsuyan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9226

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @o365tatsuyan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by o365tatsuyan** [comment]
Thank you @yogkumgit for your prompt support!  Your update help our support and our customer. Perfect!
