### ISSUE TITLE
Incomplete features due to Business Premium + MDI license

### ISSUE THREAD

**Issue by brolifen** [MicrosoftDocs/microsoft-365-docs#9153]
It seems like the new defender portal is missing some features when you have a Business Premium + MDI addon license only. For instance the Assets->Identities section described in the doc is not present. Additionally when creating custom detection rules the "user action" section is also not present (which should allow you to disable users onprem with MDI), I think the new portal assumes that if you don't have a defender for cloud apps and/or AAD P2 license that these features must be hidden. But these features also make part of MDI which leaves the new portal experience broken with this license combination. And this is not highlighted at all in the current docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c29e05f2-5a90-3457-220f-af7c4ad3c9f2
* Version Independent ID: c29e05f2-5a90-3457-220f-af7c4ad3c9f2
* Content: [Microsoft Defender for Cloud Apps in Microsoft 365 Defender (Preview)](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/microsoft-365-security-center-defender-cloud-apps.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
This isn't a documentation issue and requires further investigation. The best way to get help is to open a support ticket.

**Comment by yogkumgit** [comment]
@brolifen Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
