### ISSUE TITLE
Update parameter list

### ISSUE THREAD

**Issue by sgarmon** [MicrosoftDocs/microsoft-365-docs#9157]
The parameter list includes rbacGroupNames but the default sample csv file from the MDE portal lists Scope/DeviceGroups as a parameter instead of rbacGroupNames. Please update the doc. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03d3a25-4ee0-0c3a-4fde-c6f9ef7a3773
* Version Independent ID: b08640a7-7e66-2653-bf3f-727fbb90709d
* Content: [Manage indicators](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/indicator-manage?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/indicator-manage.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/indicator-manage.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@sgarmon Thank you for your feedback. I see RbacGroups instead of Rbacgroupnames. I will update the same in the document shortly.

![image](https://user-images.githubusercontent.com/45987684/180454938-aae3d515-7a81-4bf4-8ef8-49fc40f5ded9.png)

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sgarmon Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
