### ISSUE TITLE
Do we have a roadmap to add other Operating systems in Supported area? Is there any OS in pipeline to support Network Assessment jobs?

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#9158]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afc92823-9277-c291-049c-0ac74542a403
* Version Independent ID: b6eadab9-51b1-23d4-224e-f9a59cde87a7
* Content: [Network device discovery and vulnerability management](https://review.docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-devices?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-devices.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-devices.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @levinec
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@PremMS-MDE Thank you for your feedback. I don't see them in the roadmap. You may be able to post this question directly to our Dev/PG via the main feedback portal https://feedbackportal.microsoft.com/  and they will be able to answer your query.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@PremMS-MDE Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
