### ISSUE TITLE
Get Information about license expiration date and purchase channel

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/microsoft-365-docs#9159]
Hello,
I am looking to access the information for a license when it expires, what the billing frequency is and how it was purchased via powershell.
The information is available in the admin center:
<img width="649" alt="grafik" src="https://user-images.githubusercontent.com/62641471/178705158-9991e512-1a85-4503-bdb3-f7cbc8d080ea.png">
Is it possible to access this information via powershell as well?
Best regards
Joerg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc0555a1-2410-5679-03f3-e5768a1dc9cd
* Version Independent ID: e3d2444e-22f6-f697-03a4-9edb8226b72e
* Content: [View Microsoft 365 licenses and services with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@joergrenn  Thank you for your feedback. I have tested and these options are not available in this module yet. You can provide this feedback on our main feedback portal - https://feedbackportal.microsoft.com/ So that one of the Dev/Product engineers can help you with information on when this will be available in PS.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@joergrenn Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
