### ISSUE TITLE
Please include additional status

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/microsoft-365-docs#916]
Retire Issued status is not on this list and this is a valid device state. It would be helpful to include this on this page. More information at https://docs.microsoft.com/en-us/intune/developer/reports-ref-devices#example-4.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: debddc56-36d4-e62e-68bb-5cf13b98e0dc
* Version Independent ID: ff6cbd39-7c71-088d-27b6-d83125eb6d82
* Content: [Device states](https://docs.microsoft.com/en-us/microsoft-365/business/device-states)
* Content Source: [microsoft-365/business/device-states.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/device-states.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by Sirkkuw** [comment]
@kellybos - I am not, however sure if the Devices page in the Microsoft 365 admin center repeats all the device states that can be seen in the Intune portal.

**Comment by mypil** [comment]
@kellybos - From our understanding, the issue you raised has been answered by Sirkkuw so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
