### ISSUE TITLE
PowerShell Code Error on https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-user-account-properties-with-microsoft-365-powershell?view=o365-worldwide

### ISSUE THREAD

**Issue by Phyktion** [MicrosoftDocs/microsoft-365-docs#9163]
[Enter feedback here]
I am having problems with this code: Get-AzureADUser | Set-AzureADUser -UsageLocation "FR"

The code doesn't work as-is for 2 reasons.
1.) "FR" gets input exactly as "FR", which violates the max characters. The max is 3. "FR" is 4. It should not have quotes. I have verified and tested this myself today, because it wreaked havoc on our system. We were getting this error:

Unable to update this object in Azure Active Directory, because the attribute [UsageLocation], in the local Directory exceeds the maximum allowed length. If you want to update, reduce the length in the local directory services, and then try again.
Tracking Id: 2a98435c-5b23-439e-a029-2707215fb39a
ExtraErrorDetails:
[{"Key":"ObjectId","Value":["b7964afb-1e8d-4f38-899a-0028d175554a"]},{"Key":"InvalidAttributeName","Value":["UsageLocation"]},{"Key":"MaxLength","Value":["3"]},{"Key":"MinLength","Value":["1"]}]

2.) Just running Get-AzureADUser | Set-AzureADUser -UsageLocation does not work. I tried a couple of times and the values never updated online. I had to change the code to Get-AzureADUser -All $true | Set-AzureADUser -UsageLocation US to get them to update.

Maybe modify the code to have a filter for user objects only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f4cab0-7352-388a-7a49-fbd82845d558
* Version Independent ID: 0b53e3c6-41f1-444d-4603-355e7bd4d862
* Content: [Configure Microsoft 365 user account properties with PowerShell - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/configure-user-account-properties-with-microsoft-365-powershell?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/configure-user-account-properties-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/configure-user-account-properties-with-microsoft-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@Phyktion Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9241

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Phyktion Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
