### ISSUE TITLE
Can a Yammer Group be selected to be a Power BI Pro (New) Workspace?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/microsoft-365-docs#9167]
Simple question: Can a Yammer Group be selected to be a Power BI Pro (New) Workspace?

If not, perhaps a note could be added to highlight this (similar to what's been noted for Teams and Yammer Groups).

Cheers
Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f4a6d6-56b1-7cc0-a3cd-6a2bd96b2a23
* Version Independent ID: 5db8e4ff-aff7-a9c0-d32f-27b7aba02bbd
* Content: [Groups services interactions](https://docs.microsoft.com/en-us/microsoft-365/solutions/groups-services-interactions?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/groups-services-interactions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/groups-services-interactions.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@HandyAndyOnGitHub Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9271

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @HandyAndyOnGitHub Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
