### ISSUE TITLE
Triplicate nav menu entries for Allow or block URLs using the Tenant Allow/Block List

### ISSUE THREAD

**Issue by LuxsonicAdmin** [MicrosoftDocs/microsoft-365-docs#9169]
[Enter feedback here]
Was on the page for 'Allow or block URLs using the Tenant Allow/Block List'. Noticed that in the sidebar menu, in the drop-down subsection of Tenant Allow/Block List, there are triplicate entries for the page 'Allow or block URLs using the Tenant Allow/Block List.' Right under 'Manage the Tenant Allow/Block list'. Screenshot attached!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b69171-7abf-93be-4d9a-7f7a512e62b3
* Version Independent ID: 66b69171-7abf-93be-4d9a-7f7a512e62b3
* Content: [Allow or block URLs using the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/allow-block-urls?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/office-365-security/allow-block-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/allow-block-urls.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp*
![Screenshot 2022-07-13 183217](https://user-images.githubusercontent.com/64994389/178859703-00be90d4-2248-4aeb-84fd-f5c145144812.png)
*

**Comment by DMoenks** [comment]
According to the titles and content of those three articles, each describes a very distinct use case:

- allowing/blocking email addresses and domains for email handling purposes
- allowing/blocking IP addresses, domains and URLs for link handling purposes
- allowing/blocking file hashes for file handling purposes

Each article is also quite long on its own, with descriptions and usage/configuration examples. In addition, every article matches a tab in the configuration GUI, if I remember correctly.
From my point of view, having those three distinct articles makes sense in multiple ways.

**Comment by msbemba** [comment]
@LuxsonicAdmin Thank you for your feedback. All three are different as they are for Files, URls and Emails.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LuxsonicAdmin Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by LuxsonicAdmin** [comment]
@yogkumgit apologies for the oversight and unnecessary issue creation!
