### ISSUE TITLE
Remove domein

### ISSUE THREAD

**Issue by Jcodaar** [MicrosoftDocs/microsoft-365-docs#9170]
Goodmorning,

I am trying to remove my domein with the steps. But I don't see de remove optie in my panel (settings -> domeins). I selected the domein but no button appears.

Kind regards,

Jcodaar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780db236-9235-2ce7-acbb-953fd997215b
* Version Independent ID: a5b80ea1-fb9f-d381-4fa6-7d4d8cce3f82
* Content: [Remove a domain - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/remove-a-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/remove-a-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/remove-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@Jcodaar Thank you for your feedback. There could be multiple reasons for your not being able to locate the domains.

1) Domain does not exist in the tenant.
2)You do not have Global Admin permissions to remove the domain.

If it is not the above two, it is better to reach out to Microsoft support for help. You can do that via the need help section of the Admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Jcodaar Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
