### ISSUE TITLE
Add Information about User Management (Fallback Domain)

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/microsoft-365-docs#9185]
* Make your new onmicrosoft.com domain your fallback domain
Where can I find a guide, to change all User to this new Fallback Domain?
Would it be possible to Link or Add that here?
_(User with *.onmicrosoft .comDomain as Primary E-Mail)_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a66bd91-6de1-5128-0f77-df1573b7f800
* Version Independent ID: 0a66bd91-6de1-5128-0f77-df1573b7f800
* Content: [Add and replace your onmicrosoft.com fallback domain in Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain?view=o365-worldwide)
* Content Source: [microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@weyCC81 Thank you for your feedback. Fallback domains are for the entire organization. So the document talks about changing it to a new onmicrosoft.com domain if you create one (it has steps to do that ).

Let's say you have contoso.onmicrosoft.com as your current fallback domain, you can change it to the new one contoso1.onmicrosoft.com so in case your custom domain is no longer active or has been removed all users in the organization will move to this fallback domain. No need to change it for individual users.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @weyCC81 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by weyCC81** [comment]
Hi @msbemba 

I have added one as we have a spelling error in the initial one and would like to switch sharepoint in the future.

It is still not clear to me what action could start such a fallback, and/or what do you mean with "no longer active".
I thought you can not remove them if you have added them once (up to 5 max)?

**Comment by msbemba** [comment]
@weyCC81 That is correct. You cannot remove onmicrosoft.com domain, however the custom domains like contoso.com can be removed leaving just the onmicrosoft.com.


Once you add another onmicrosoft.com domain to the tenant using https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain?view=o365-worldwide#add-a-new-onmicrosoftcom-domain

You can make that one as fallback domain using the steps mentioned here - https://docs.microsoft.com/en-us/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain?view=o365-worldwide#make-your-new-onmicrosoftcom-domain-your-fallback-domain

Once the fallback domain is changed, Sharepoint sites will start reflecting correctly now.

Hope this helps!

Thanks
Sri
