### ISSUE TITLE
Modern OA2 Authentication

### ISSUE THREAD

**Issue by IanMos** [MicrosoftDocs/microsoft-365-docs#9187]
This document says NOTHING about Office / Outlook 2021.

So, is Office / Outlook 2021 impacted by this coming update??
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd3a343-4140-e63d-5197-06cafdab4639
* Version Independent ID: 12cf7dda-2caf-0fe2-1564-a14dea00d46f
* Content: [How modern authentication works for Office 2013 and Office 2016 client apps - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/modern-auth-for-office-2013-and-2016?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/modern-auth-for-office-2013-and-2016.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/modern-auth-for-office-2013-and-2016.md)
* Service: **o365-administration**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@IanMos Thank you for your feedback. I have checked and OA2 is supported on office 2021. The impact will be on the earlier versions of office only and not on 2021.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @IanMos Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
