### ISSUE TITLE
Audit Retention Policy not Make any Effects after applied

### ISSUE THREAD

**Issue by yunuschrome** [MicrosoftDocs/microsoft-365-docs#9188]
Hi,

My company subscribed Business Premium only, the trials of PureVeiew Premium are already finished, yesterday i set the audit retention policy to 90 days at maximum, but when this morning i check the audit log for the specified record & activities from Februari are still generated.  Any one can help me on this issue? When the audit log rentention policy applies after the config submitted? 

Regards, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e1877-191e-5dbe-b805-e755c736b985
* Version Independent ID: 69df5ed6-a86f-06d7-1156-e1de211f8e83
* Content: [Manage audit log retention policies - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-retention-policies?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/audit-log-retention-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-retention-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@yunuschrome Thank you for your feedback. Ideally, this should not happen, However Since it is a technical glitch, I'd recommend you to contact Microsoft support via the need help section on the admin center, so that a Support representative can assist you with this technical issue/bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @yunuschrome Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
