### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by XXLMandalorian013** [MicrosoftDocs/microsoft-365-docs#9192]
[Enter feedback here]

I was looking for info on adding an external user a Office MS 365 business standard license, would of been nice to see a link at the bottom or details on this page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29fdeb34-ed9f-ebb9-0173-a9d3b3449221
* Version Independent ID: 4a552838-a850-b0d6-bb7c-b81412dfd087
* Content: [Invite users to Microsoft 365 Business Standard subscription - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/simplified-signup/admin-invite-business-standard?view=o365-worldwide)
* Content Source: [microsoft-365/admin/simplified-signup/admin-invite-business-standard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/simplified-signup/admin-invite-business-standard.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@XXLMandalorian013 Thank you for your feedback. With the instructions on the page I was able to send an invite to an external user

In the Microsoft 365 admin center, select Invite people to Microsoft 365.

Add the usernames and email addresses for the people you want to invite and choose Send. An invite email will be sent to all the users you selected to add their user account information to Microsoft 365.

If this continues to be a problem or if you are not able to invite users this way, I'd recommend you contact Microsoft via the need help section on the admin center.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @XXLMandalorian013 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
