### ISSUE TITLE
offline scan results location

### ISSUE THREAD

**Issue by razpopescuMS** [MicrosoftDocs/microsoft-365-docs#9194]
Feedback:
The part at the end, where it says the offline scan results will be listed in the scan history is incorrect, the offline scan results are not listed anywhere (I am from the Defender for Endpoint team)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecec1e6a-ee1c-5f8b-6251-71cf1aea1f35
* Version Independent ID: b0c925e2-5ad4-e250-ab97-6f8eb5601b26
* Content: [Microsoft Defender Offline in Windows](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-offline?view=o365-worldwide#review-scan-results)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-offline.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-offline.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@razpopescuMS Thank you for your feedback. I'm currently testing this and will update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@razpopescuMS Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9267

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @razpopescuMS Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
