### ISSUE TITLE
command used to view or managed preset security policy not available on MS article

### ISSUE THREAD

**Issue by mariammorgan** [MicrosoftDocs/microsoft-365-docs#9195]
The command used to view or manage the preset security setting is not available in any MS article,
however other public article like http://www.powershellgeek.com/2020/12/15/microsoft-365-preset-security-policies/
 So the article needs to be updated with the command Get-EOPProtectionPolicyRule

**Comment by msbemba** [comment]
@mariammorgan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9266

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by mariammorgan** [comment]
great , thank you

**Comment by chrisda** [comment]
Updates made in a separate PR that should publish F 7/29 ~11:00AM GMT-7.

Also, related cmdlet reference topics published in the PowerShell repo per [9374](https://github.com/MicrosoftDocs/office-docs-powershell/pull/9734).

Thanks for the feedback.

Closing
