### ISSUE TITLE
custom mailbox configuration

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/microsoft-365-docs#9198]
The documentation for setting a mailbox as SecOps mailbox states that Safe Attachments doesn't detonate attachments and Safe Links doesn't block or detonate the URLs (URLs are still wrapped but they aren't blocked). Are the steps for creating designated Safe Links and Safe Attachment policies to bypass processing still needed as a custom mailbox prerequisite when it's already configured as SecOps mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User reported message settings - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide#third-party-reporting-tools)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@itishnitsa Thank you for your feedback. You are right, We need to create safe links and safe attachment policies for the customer mailbox.

The section that you read about safe links and Safe attachments doesn't detonate, is specifically for third-party phishing simulations.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @itishnitsa Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
