### ISSUE TITLE
update wording to include Outlook

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/microsoft-365-docs#920]
Some new features were recently rolled out that allow text that was converted to a link to be protected.   This impacts Outlook as well as the other office products but it is not mentioned in this section:   
Office 365 ProPlus, Office for iOS and Android
When this option is selected, ATP Safe Links protection is applied to URLs in Word, Excel, and PowerPoint files on Windows or Mac OS, Office documents on iOS, or Android devices, Visio 2016 on Windows, and the web versions of Office apps (Word, PowerPoint, Excel, and OneNote), provided the user has signed into Office 365.

Can we add Outlook to the two references above that have the list of products. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1541da6f-af9a-05d5-fa34-b1a5df61424f
* Version Independent ID: 88e111ed-67f7-41bc-d823-863ee7ea2a2e
* Content: [Set up Office 365 ATP Safe Links policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies#step-4-learn-about-atp-safe-links-policy-options)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@scottsa-msft -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/af9999707f033e0c54657fdc4c0f7386e6de881d. 


Thank you for your contribution to make the docs better! Much appreciated!
