### ISSUE TITLE
Scenario example or clarification needed

### ISSUE THREAD

**Issue by shwag** [MicrosoftDocs/microsoft-365-docs#9200]
Under **Example for users to override automatic deletion**:

Scenario: By default, SharePoint items are automatically retained and then deleted after five years, but documents in specific libraries must be retained for ten years.

1. You create and configure a retention policy that automatically retains and then deletes content after five years, and apply the policy to all SharePoint and Microsoft 365 Groups instances.
2. You create and configure a retention label that automatically retains content for ten years. You publish this label to SharePoint site admins, so that they can apply it as a default label to be inherited by all items in specific document libraries.

Please provide specific info or reference for how to limit publishing of a retention label to site admins only per **You publish this label to SharePoint site admins, so that they can apply it as a default label to be inherited by all items in specific document libraries.** Or alternatively, if this is not possible, consider rewriting this statement to **You publish this label to the SharePoint site so that site members can apply it as a default label to be inherited by all items in specific document libraries.** Per my understanding a retention label is published to the site and cannot be isolated for use by site admins only. A site member or anyone with Edit permissions to the document library would therefore be able to also assign as default to the library, folder, or document set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c49609d-3a62-b9be-24bf-f8fa6948d390
* Version Independent ID: df547c86-fbc7-4f87-e893-49d07b045373
* Content: [Learn about retention policies & labels to retain or delete - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide#example-for-users-to-override-automatic-deletion)
* Content Source: [microsoft-365/compliance/retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@shwag You're quite right - you can't publish retention labels to specific users, it's location-based. I'll reword so it's clearer the SPO admin reference is the example of who might apply the exception label in this way.
