### ISSUE TITLE
'New domains being forwarded' should be 'New users forwarding'

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/microsoft-365-docs#9201]
The second paragraph starts with "The **New domains being forwarded** email insight" but should start with "The **New users forwarding** email insight".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d59f1c-25fd-4ee7-af8b-7ffef8dd3578
* Version Independent ID: eb0ca0ed-44f3-e1d6-6e6c-2f79a791d4f5
* Content: [New users forwarding email insight - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/mfi-new-users-forwarding-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/mfi-new-users-forwarding-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mfi-new-users-forwarding-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@VShrubowich Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9254

Once the author approves, the document will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @VShrubowich Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
