### ISSUE TITLE
permissive permissions "bookings with me"

### ISSUE THREAD

**Issue by Firewaters** [MicrosoftDocs/microsoft-365-docs#9202]
"bookings with me" has prerequisites for "Anonymous:CalendarSharingFreeBusyReviewer", this seems like a rather permissive permission for Anonymous. 

Microsoft support indicates that you can use any of the following with Booking with me, should the documentation be updated around what permissions are required and the impacts.
- CalendarSharingFreeBusySimple: Share free/busy hours only
- CalendarSharingFreeBusyDetail: Share free/busy hours, subject and location
- CalendarSharingFreeBusyReviewer: Share free/busy hours, subject, location and the body of the message or calendar item
- ContactsSharing: Share contacts only.

**Comment by msbemba** [comment]
@Firewaters  Thank you for your feedback. I will be testing these today and will update the document if need be.

Thanks
Sri

**Comment by msbemba** [comment]
@Firewaters  Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9270

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The changes have been made through another PR and the issue can be closed as the document is up to date.

Thanks
Sri
