### ISSUE TITLE
Disabling the policy

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/microsoft-365-docs#9206]
Hello,

It would be good if you explain what is happening when set to None (disable policy),
Because not clear what will happen with groups that are "expired today", pending for verification (expired and waiting for user action), or have the last hour of expiration as an example...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979f0a6e-be32-af1e-5724-d1104ebe3ef5
* Version Independent ID: cb9b993a-2224-5bb8-64b8-d1afa7a71c8e
* Content: [Microsoft 365 group expiration policy](https://docs.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-groups-expiration-policy?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-groups-expiration-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-groups-expiration-policy.md)
* Service: **o365-administration**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@lightupdifire Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9269

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lightupdifire Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
