### ISSUE TITLE
Add more info to the "Do not rewrite the following URLs" note

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/microsoft-365-docs#9208]
With respect to the note about the "Do not rewrite the following URLs" setting in safe-links policies, please consider adding some guidance.  The note explains what the setting does, and then says "Instead of using this list, you can now create allow URL entries in the Tenant Allow/Block List.".  It makes no recommendation as to which option we should use, nor does it offer any indication of why we might want to use one option over the other. It just basically says 'you could also do it this way'.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-links?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@NeighborGeek, the "Block the following URLs" list is definitely going away the same article:

> [!NOTE]
> You can now manage block URL entries in the [Tenant Allow/Block List](https://docs.microsoft.com/microsoft-365/security/office-365-security/allow-block-urls#create-block-url-entries-in-the-tenant-allowblock-list). The "Block the following URLs" list is in the process of being deprecated. We'll attempt to migrate existing entries from the "Block the following URLs" list to block URL entries in the Tenant Allow/Block List. Messages containing the blocked URL will be quarantined.

I haven't heard of a similar path for "Do not rewrite the following URLs". I'll see what I can find out.

**Comment by chrisda** [comment]
Topic updated on 7/20:

<https://github.com/MicrosoftDocs/microsoft-365-docs/commit/53ad182badc455fd8b0b16fb90e186a473106475>

Thanks for the feedback.

Closing
