### ISSUE TITLE
Mistype of reference to Phishing simulation in SecOps section

### ISSUE THREAD

**Issue by h3xplore** [MicrosoftDocs/microsoft-365-docs#9211]
Section: Use the Microsoft 365 Defender portal to configure SecOps mailboxes in the advanced delivery policy

Step two refers to phishing simulations. This is incorrect as its talking about SecOps as the next section goes into phishing simulations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17ce75e-79ba-0acd-066c-a0120a29d65d
* Version Independent ID: 14673b1c-8489-0abc-90a0-42f35d516424
* Content: [Configure the delivery of third-party phishing simulations to users and unfiltered messages to SecOps mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-advanced-delivery?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-advanced-delivery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-advanced-delivery.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@h3xplore, fixed. In the future, you too can make changes like this yourself. For instructions, see [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
