### ISSUE TITLE
Can you delete the current geo location while using that geo's admin center?

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/microsoft-365-docs#9214]
Document should clarify which admin center to use. The default or if any will work, including the admin center for the geo you want to delete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1747e6f1-9e14-a778-e1f2-fabd6c9ca329
* Version Independent ID: 66ac3bb7-661a-2c61-3b24-78dfd3e10a3a
* Content: [Delete a satellite location - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/delete-a-geo-location?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/delete-a-geo-location.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/delete-a-geo-location.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@Marweis Thank you for your feedback. I tested it and If you are a Geo Administrator, you can log in to only that Geo admin center and will not have an option to delete or view the geo-locations tab.

The document states, that you need to log in as a global admin and once you access Sharepoint admin center-->Geo locations-->You can delete the location that you want to delete. 

So if you are a geo administrator logged in only to that geo-location admin center, you will see an option to delete.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Marweis Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
