### ISSUE TITLE
Page information needs updating. 

### ISSUE THREAD

**Issue by ericsayles** [MicrosoftDocs/microsoft-365-docs#9215]
Needs updating. The option to download keys no longer exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f67ebee8-4451-c7d4-2c00-720e1886ea12
* Version Independent ID: 60e9e39f-3906-150a-f455-375dbdfe119d
* Content: [Download perpetual software and product license keys bought through the Cloud Solution Provider (CSP) program - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/setup/download-software-licenses-csp?view=o365-worldwide#download-software-and-product-license-keys)
* Content Source: [microsoft-365/admin/setup/download-software-licenses-csp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/setup/download-software-licenses-csp.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@ericsayles Thank you for your feedback. The option exists if you have purchased the perpetual software through the CSP program(Via Partner). If you still do not see the option to download keys, I'd recommend you to contact Microsoft support via the need help section on the admin center so they can fix it.

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ericsayles Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
