### ISSUE TITLE
Sender Block List vs AntiSpam Policy Block List

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#9218]
Please add details on recommendations of which to use as well as the net result of entries being in 1 vs the other or if entries are in both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b60171-271c-fb93-88bf-0cd9db014541
* Version Independent ID: e9cd207e-0d4c-e268-dd3a-701e1e2df658
* Content: [Manage your allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
Assigning to Ratula, who does TABL

**Comment by dhairyya** [comment]
@RatulaC the recommendation should be to use antispam block list if they want to block spam and if they want to block everything else from the sender use Domains & addresses (Sender ) block in Tenant allow/Block list.

**Comment by chrisda** [comment]
I added the following note to the domains and email addresses bullet:

> [!NOTE]
> To block only spam from a specific sender, add the email address or domain to the block list in [anti-spam policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/configure-your-spam-filter-policies). To block all email from the sender, use **Domains and email addresses** in the Tenant Allow/Block List.

Thanks for the feedback.

Closing
