### ISSUE TITLE
RSS Feed of update on this page

### ISSUE THREAD

**Issue by morrow233** [MicrosoftDocs/microsoft-365-docs#9222]
[Enter feedback here]

My customer would like to know the URL ASAP if required URL is changed, as MDAV security intelligence update is affected seriously.

The Docs for O365 URLs and IPs, there is a RSS feed function so that customer actively know the change.

Office 365 URLs and IP address ranges
https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

I know the URL for security intelligence update is not changed so often, but please consider to add RSS feed function on this page so that we keep our customer get updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1575e3-b233-ffd2-95c1-fd34fd242651
* Version Independent ID: 02b44885-5bff-1580-0974-f9050bee639c
* Content: [Configure and validate Microsoft Defender Antivirus network connections](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus?view=o365-worldwide#services-and-urls)
* Content Source: [microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-network-connections-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Hello @morrow233 and thank you so much for your suggestion. I have implemented a link for RSS feeds, and it should be live later today (around 4 p.m. Pacific Time). Please let us know if it does not work, and I'll try something else. Thank you @yogkumgit for all your help as well.
