### ISSUE TITLE
Will EWS to the 365 Third-Party-Data endpoint work after EWS end-of-life

### ISSUE THREAD

**Issue by sbacon17a4** [MicrosoftDocs/microsoft-365-docs#9224]
[Hello, Will Microsoft's third-party-data endpoint to the Azure service in Microsoft 365 work after EWS end-of-life? 

EWS end of life:  [Deprecation of Basic authentication in Exchange Online | Microsoft Docs](https://urldefense.com/v3/__https:/docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online__;!!AKgNyAfk550h-spHnEo!ZhdjKetAgwguP00Br9J6mTDC33vETmCtIC2AZVExKKYrD6TwPjmR0U1sOfjN96mMBdSeTEB5GwnAw6ikwa9xHZnf$)

The endpoint used to connect to the Azure service in Microsoft 365:

HTTP
https://office365ingestionsvc.gble1.protection.outlook.com/service/ThirdPartyIngestionService.svc
Endpoint:  https://office365ingestionsvc.gble1.protection.outlook.com/service/ThirdPartyIngestionService.svc 

Thank you, 
Sharon Bacon
17a-4, llc
sbacon@17a-4.com]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d168aa8-f335-f879-d12f-d0b198f2a339
* Version Independent ID: 049d4291-2fd8-c80b-18a8-31e5ecb5fc88
* Content: [Work with a partner to archive third-party data - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/work-with-partner-to-archive-third-party-data?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/work-with-partner-to-archive-third-party-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/work-with-partner-to-archive-third-party-data.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@sbacon17a4 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
