### ISSUE TITLE
Bad guidance

### ISSUE THREAD

**Issue by tofergus** [MicrosoftDocs/microsoft-365-docs#9228]
The correct method is here:

[https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection#bkmk_uplevel](url)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d0bace4-46dc-8b93-8731-71ad5e98e298
* Version Independent ID: 1d0bace4-46dc-8b93-8731-71ad5e98e298
* Content: [Onboard Windows 10 and Windows 11 devices using Configuration Manager - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-sccm?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/device-onboarding-sccm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/device-onboarding-sccm.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@tofergus Thank you for your feedback. I tested it using both the options and they are different because this document talks about onboarding devices using the [Microsoft Purview compliance portal](https://compliance.microsoft.com/) and the document you have provided talks about [Microsoft Defender Security Center](https://securitycenter.windows.com/) for Microsoft defender for the endpoint.

Both serve different purposes. 

Hope this helps!

Thanks
Sri

**Comment by tofergus** [comment]
Right, but step #3 at https://docs.microsoft.com/en-us/microsoft-365/compliance/device-onboarding-sccm refers to a deployment method choice label that is no longer available, now that ConfigMgr 2012 is EOL.

Also, step #5 mentions a .cmd file within the .zip that does not exist when selecting the current ConfigMgr choice, is not needed for Win10+, and confused our customer.

Then step #6 says to use a package/program for software distribution with ConfigMgr, which would be possible if indeed there were a .cmd file provided. ConfigMgr does have a dedicated policy type for MDE onboarding, which on Win10+ only requires the .onboarding file.

The link in blue on the portal's download page is better:

Instructions for onboarding devices using Microsoft Endpoint Configuration Manager<https://go.microsoft.com/fwlink/?linkid=2134368>
Although this article describes onboarding devices to Microsoft Defender for Endpoint, the instructions are the same for onboarding to the compliance center.

Though it doesn't link directly to https://docs.microsoft.com/en-us/mem/configmgr/protect/deploy-use/defender-advanced-threat-protection, but rather to an intermediary page https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-sccm, that lists tenant attach as an alternative method of onboarding, which again is not helpful.

Thanks,
-Tom

**Comment by yogkumgit** [comment]
@msbemba Please review it thoroughly. Thanks

**Comment by msbemba** [comment]
@tofergus Thank you for the detailed explanation. I'll need to check with the author to see if we can implement these changes in the document. 

We will update you shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by chrfox** [comment]
@msbemba  - The whole device onboarding content set is being evaluated/changed.  Please forward me the entire thread, it looks like there may be some good suggestions here from tofergus. Do not commit this PR.

@tofergus  - The overlap between Purview device onboarding content and MDE makes this a difficult area.  I am the writer/owner of the Purview content.  I am currently evaluating both content sets for what they have in common and where each is unique for updating.  Please forward your observations and questions to me chrfox@microsoft.com.

**Comment by tofergus** [comment]
Hi Chris,

Here's the thread with the expanded feedback (attached).

I suppose a simple approach would be to just state that the onboarding process is identical to MDE's, and refer the reader to those docs. I'm happy to discuss ConfigMgr or Intune methods anytime.

Thanks,
-Tom

**Comment by mohanra1** [comment]
This is still not changed.. Any update on the progress please. Am currently working with a customer who is relying on the steps for SCCM and this article is not good at all..

**Comment by mohanra1** [comment]
@msbemba pls look into this on priority
