### ISSUE TITLE
eDiscovery script throws errors when it gets to eDiscovery (Premium)

### ISSUE THREAD

**Issue by anton612** [MicrosoftDocs/microsoft-365-docs#9229]
The following error comes up when running this script against cases in eDiscovery Premium:

```
add-tocasereport : Missing an argument for parameter 'casestatus'. Specify a parameter of type 'System.String' and try again.
At \\path\CaseHoldsReport.ps1:94 char:37
+ add-tocasereport -casename $cc.name -casestatus -casetype $cc.casetyp ...
+                                     ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [add-tocasereport], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,add-tocasereport
```
It looks like a parameter and variable are swapped on line 94 so I'll submit a pull request (my first ever on someone else's code!) to fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 170c3a0d-4a77-211f-8ef4-21da97042c1e
* Version Independent ID: b121eb8f-2438-f0cf-41b9-0cfe3ca34925
* Content: [Use a script to create an eDiscovery holds report - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@anton612 Thank you very much for the contribution and updating the documentation with PR. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
