### ISSUE TITLE
eDiscovery Data Analyst

### ISSUE THREAD

**Issue by vutran2015** [MicrosoftDocs/microsoft-365-docs#923]
What is KQL meaning? I found it in section "Create a Search", and in Item 12...Each condition adds a clause to the KQL search query that is created and run when you start the search...." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9929a7f-94ca-ace1-8d2e-4fcf79278a34
* Version Independent ID: 4dd4c5ce-5750-1ce7-15fd-51b604317bc5
* Content: [Run a Content Search in the Security & Compliance Center](https://docs.microsoft.com/en-us/microsoft-365/compliance/run-a-content-search-in-the-security-and-compliance-center#create-a-search)
* Content Source: [microsoft-365/compliance/run-a-content-search-in-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/run-a-content-search-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@vutran2015 KQL is Keyword Query Language. It is the search query language used in queries for content search. Please see:

- https://docs.microsoft.com/microsoft-365/compliance/keyword-queries-and-search-conditions
- https://docs.microsoft.com/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference

**Comment by vutran2015** [comment]
Thank you Mark. This is helpful. It would be great if other readers can find out what KQL is on that page. Thanks again!

**Comment by markjjo** [comment]
@vutran2015 Here's a newer version of the content search topic, that has more info about KQL and building search queries. 

[https://docs.microsoft.com/en-us/microsoft-365/compliance/content-search](https://docs.microsoft.com/microsoft-365/compliance/content-search)

I'm going to redirect the older version of the topic (the one you opened the GitHub issue against) to this newer one.

**Comment by vutran2015** [comment]
Awesome. Thank you.


________________________________
