### ISSUE TITLE
Remediation exception methods and properties

### ISSUE THREAD

**Issue by atiedemann** [MicrosoftDocs/microsoft-365-docs#9232]
Good morning Microsoft Team,
I am working on a project for a client to display a dashboard around tvm information, and one goal is to show the remediation exceptions that we can configure in the portal. Unfortunately there is no API endpoint for displaying these exceptions. 
Is this correct, if so when is an API endpoint planned for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d05f44de-05db-1ca8-1116-b0c4ad8ac377
* Version Independent ID: e7a34d30-3a87-693a-27fc-265bc79231cf
* Content: [Remediation activity methods and properties](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-remediation-methods-properties?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/get-remediation-methods-properties.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-remediation-methods-properties.md)
* Product: **m365-security**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@atiedemann Thank you for your feedback. I was not able to find API endpoint for displaying these exceptions. Having said that you can provide this feedback directly to our Developers/Product group via the main feedback portal:- https://feedbackportal.microsoft.com/ and they will be able to provide more information on when this is planned(if it is planned).

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@atiedemann Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
