### ISSUE TITLE
XMDEClientAnalyzer.zip sha256 hash

### ISSUE THREAD

**Issue by txasman** [MicrosoftDocs/microsoft-365-docs#9234]
[Enter feedback here]
Hi, I think the sha256 hash of the file is no longer valid and it might be a good idea to update it.

Just downloaded the file from the link provided in this article and this is the hash calculation I get:

$ sha256sum XMDEClientAnalyzer.zip
ac086d65202d31ebcf9dc76f7ca29a5b8b355cd6f78d31bbf89289eb7aa2b67d  XMDEClientAnalyzer.zip
$ openssl sha256 XMDEClientAnalyzer.zip
SHA256(XMDEClientAnalyzer.zip)= ac086d65202d31ebcf9dc76f7ca29a5b8b355cd6f78d31bbf89289eb7aa2b67d

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95ba8ed0-8234-d514-f06e-3ce69e60bfec
* Version Independent ID: 51d6d3ae-6100-7acb-af46-e8ec6b9fe84f
* Content: [Run the client analyzer on macOS or Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by RAJU2529** [comment]
@mjcaparas , i too downloaded and verified SHA-256 , i received below 
**AC086D65202D31EBCF9DC76F7CA29A5B8B355CD6F78D31BBF89289EB7AA2B67D**

![Screenshot 2022-07-25 194452](https://user-images.githubusercontent.com/3296790/180798377-f270422a-c54c-4415-9ff1-778d843b7613.jpg)

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @txasman Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
