### ISSUE TITLE
Latest Change Log is showing empty

### ISSUE THREAD

**Issue by mcsorleym** [MicrosoftDocs/microsoft-365-docs#9236]
Latest Change Log showing empty.
https://endpoints.office.com/changes/Worldwide/2022062900?singleVersion=true&clientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7

2022062900
https://endpoints.office.com/changes/Worldwide/2022062900?singleVersion=true&clientRequestId=b10c5ed1-bad1-445f-b386-b919946339a7
2022062900 - Worldwide
Version 2022062900 includes 3 changes. IPs: 50 added and 0 removed. URLs: 35 added and 0 removed. 21 other attributes changed.
Wed, 29 Jun 2022 00:11:59 Z

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I'm talking to the endpoints web service team about this.

**Comment by kelleyvice-msft** [comment]
According to the engineering team, there were some internal-only changes that resulted in version increment. Since the changes were internal only, querying for changes returns nothing. The next update later this week will contain public changes. Thanks - Kelley

**Comment by triumfas** [comment]
2022072800 update is also empty. Is it another internal-only change?
