### ISSUE TITLE
Incomplete information

### ISSUE THREAD

**Issue by androns1983** [MicrosoftDocs/microsoft-365-docs#924]
"These justifications will be available for the admin to review."
Where? Where can admin review these justifications?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Overview of sensitivity labels](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by cabailey** [comment]
@androns1983  Thanks for your question.  I'm looking into this.

**Comment by cabailey** [comment]
@androns1983  This is now resolved and added the clarifying text:
 
Currently, the justification reason isn't sent to label analytics for the admin to review. However, the Azure Information Protection unified labeling client sends this information to Azure Information Protection analytics.
