### ISSUE TITLE
Missing serviceplans

### ISSUE THREAD

**Issue by LuisEmilioR** [MicrosoftDocs/microsoft-365-docs#9243]
We faced a similar issue to "Issue: MailUser objects with "external" primary SMTP addresses are modified / reset to "internal" company claimed domains" and it turns out that the list on the KB needs to be updated. Below is the list of serviceplans we've identified as causing this problem:

Information Protection for Office 365 - Premium
Information Protection for Office 365 - Standard
Information Barriers
RETIRED - Microsoft Communications Compliance
Graph Connectors Search with Index
Microsoft 365 Advanced Auditing
Microsoft Communications DLP
Microsoft Customer Key
Microsoft Information Governance
Microsoft Records Management
Office 365 Advanced eDiscovery
Microsoft Data Investigations
Office 365 Privileged Access Management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#known-issues)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@msbemba Please update. Thanks

**Comment by msbemba** [comment]
@LuisEmilioR Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9362

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @LuisEmilioR Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
