### ISSUE TITLE
"Let user assign permission" option for Word, PowerPoint, Excel Below image, do you know timeline for "Under review" iOS, Android and web?

### ISSUE THREAD

**Issue by abrouster** [MicrosoftDocs/microsoft-365-docs#9245]
"Let user assign permission" option for Word, PowerPoint, Excel Below image, do you know timeline for "Under review" iOS, Android and web?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Manage sensitivity labels in Office apps - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#sensitivity-label-capabilities-in-word-excel-and-powerpoint)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@abrouster Unfortunately, these don't have an immediate timeline for implementation.  The priority is parity with the AIP Add-in, which means support for organization-wide custom permissions for Windows, and Mac to follow. Also, the ability for SharePoint to process documents that have been encrypted with custom permissions (initial support won't include triggering the dialog box).  

If this is something that's important to you, I recommend you let your Microsoft account manager know, and also post it to the user forum https://feedbackportal.microsoft.com/feedback/forum/5ad50ce6-8a83-ec11-8d21-0022482fa693
