### ISSUE TITLE
Information on password protected and encrypted attachments

### ISSUE THREAD

**Issue by gh0stwalker** [MicrosoftDocs/microsoft-365-docs#9249]
There is no information here on what occurs when the attachment is password protected or encrypted and how Safe Attachments deals with those documents.. Please add this information to the document.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5966b7b-cbaa-eaa2-c9d6-5c6e7218df74
* Version Independent ID: cfcc8772-be5d-009a-0805-62624835ac5f
* Content: [Safe Attachments - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-attachments?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-attachments.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @gh0stwalker Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by JeremyTBradshaw** [comment]
Hello @msbemba, can you please also clarify if Password-Protected attachments would fall into this setting?:

> Apply the above selection if malware scanning for attachments times out or error occurs: The action specified by Safe Attachments unknown malware response is taken on messages even when Safe Attachments scanning can't complete. Always select this option if you select Enable redirect. Otherwise, messages might be lost.

Thanks in advance.
