### ISSUE TITLE
German version misses content

### ISSUE THREAD

**Issue by mosslive** [MicrosoftDocs/microsoft-365-docs#925]
The german version misses some content in Chapter "Enable this preview".
In particular, steps 3 and 4 are not visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#feedback)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by cabailey** [comment]
@mosslive Thanks for your feedback. With this feature being in preview, we've been updating this page with new information on a regular basis, so it's entirely possible that the missing information will resolve itself in a few more days. It obviously takes a little while for somebody to translate the changes and publish them in all the languages that we support. I've flagged this article for our localization team, so please check again in a few more days. In the meantime, I'll close this issue and will keep an eye on this. If the changes are still not showing in 2 weeks from today, please reopen.

**Comment by cabailey** [comment]
@mosslive  Update:  After checking with the localization team, there was a problem translating this page, now resolved.  Thank you for reporting this.
