### ISSUE TITLE
Istanbul

### ISSUE THREAD

**Issue by BassamAlHassan** [MicrosoftDocs/microsoft-365-docs#9251]
Client AppsIstanbul

GitHub Mobile, GitHub CLI, and GitHub Desktop

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Version Independent ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Content: [Get support - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-support.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by yogkumgit** [comment]
@BassamAlHassan  Can you please tell us what is your feedback Thank you!

**Comment by yogkumgit** [comment]
@BassamAlHassan We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
