### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by max-power15** [MicrosoftDocs/microsoft-365-docs#9252]
In step 4 under the following [section](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide#steps-for-finding-signs-of-this-attack). I believe it should be IsAdminConsent not IsAdminContent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66854a7-7556-9b2a-0a33-886e3d881047
* Version Independent ID: 7ce3d8d5-cece-0b6f-68d5-143e12a3fff8
* Content: [Detect and Remediate Illicit Consent Grants - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/detect-and-remediate-illicit-consent-grants.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@RAJU2529 Thank you very much for the contribution and updating the documentation with PR. @max-power15 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
