### ISSUE TITLE
Article regarding adding licenses using a product key seems to be missing context or is outdated

### ISSUE THREAD

**Issue by waded** [MicrosoftDocs/microsoft-365-docs#9258]
I was reading https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/add-licenses-using-product-key?view=o365-worldwide (actually, an article similar to it within Admin Center's support system, but then I later found this URL outside Admin Center.)

This article states that to use a product key to add licenses "On the subscription details page, in the Licenses section, select Add more licenses." but there appears to be no such section - there is a section titled "License." This section has no "Add more licenses" button, but instead "Buy licenses" and "Remove licenses" buttons, and "Buy licenses" does not offer the option to use a key, it states a cost of each license in dollars only.)

Additionally, this article states that to extend expiration date of a subscription using product key, "On the subscription details page, in the Subscription and payment settings section, select Extend end date." The "Subscription and payment" section does appear to exist, but there is no option there to "Extend end date." (Rather, there are only options like "Edit Recurring billing", "Edit payment method", "Replace payment method", "Edit billing frequency", and "Cancel subscription.")

The above observations were made with an existing Microsoft 365 Business Standard subscription (and before that trial, and before that Business Basic Month-to-Month.)

It feels like there's either some context missing for this article (does this require the selected subscription be prepaid, and if so, this can be misleading to people like myself who bought a product key in advance expecting to be able to apply it) or perhaps this article is describing features that no longer exist, or are yet to come?

I have an existing support ticket with Microsoft 365 Subscription & Billing for Business regarding this if that's helpful (that ticket also covers https://microsoft365.com/setupBusiness recognizing, but not seeming to be able to apply, a Business Standard 1-year 1-license key in this situation, either), but I'd prefer not to share ticket ID here. Let me know if you need contact info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be84d189-037d-409b-c777-9c1edaf7a758
* Version Independent ID: 7927ab5c-3bb5-e9ee-8f29-283238669f35
* Content: [Add licenses using a product key](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/add-licenses-using-product-key?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/licenses/add-licenses-using-product-key.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/add-licenses-using-product-key.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@waded Thank you for your feedback. I was able to find the Options in the Products section.

![image](https://user-images.githubusercontent.com/45987684/181780450-0cfc7088-222c-49f2-9978-5acf75a1a17f.png)


However, there are some minute changes to the navigation. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9282

If you still do not see the option to redeem the key, I'd request you to continue working with the Support team to resolve the issue.

Hope this helps!

Thanks
Sri

**Comment by waded** [comment]
@msbemba From your screenshot perhaps the nuance missing in the article is that this *requires an existing prepaid subscription*? (Your screenshot shows the existing Billing Frequency is "Prepaid" - I think if existing Billing Frequency is e.g. "Monthly" then this entire screen is quite different than the article's describing.)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder

**Comment by msbemba** [comment]
@waded Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9312

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by waded** [comment]
I learned from Subscription & Billing support that the URL to redeem a Microsoft 365 Business Standard product key when signed into Admin Center w/ an existing (commercial) subscription is https://admin.microsoft.com/commerce/productkeyredeem.aspx. I don't know how to get to that URL using Admin Center itself, but it appears to allow adding the subscription, after which point what's described in the article does seem to apply for THAT (prepaid) subscription. At that point you have both subscriptions and can reassign licenses.

Perhaps this points to some existing article about that URL, or about what additional information should be added to this article to completely anyone coming to the article with a key, but without an existing prepaid subscription.

**Comment by msbemba** [comment]
@waded Thank you for your feedback. I'll work with the author and update this shortly.

Thanks
Sri

**Comment by yogkumgit** [comment]
@waded closing as per the Author's input. Thanks

**Comment by yogkumgit** [comment]
Closing as per author's comment in the PR. Thanks
