### ISSUE TITLE
update to mssp-list.md request 

### ISSUE THREAD

**Issue by ghadirim** [MicrosoftDocs/microsoft-365-docs#9263]
microsoft-365/security/defender-endpoint/mssp-list.md please update BlueVoyant's offer to what is listed below.

![BV_Logo_216x216](https://user-images.githubusercontent.com/13265035/181131659-420d2942-5990-4119-a46c-69e3bd9c7664.png)| [BlueVoyant](https://www.bluevoyant.com/platform/mdr/mdr-for-microsoft) |  MDR services that deliver comprehensive threat data analytics and advanced technology solutions with 24x7 remote monitoring and XDR incident remediation in your environment.

**Comment by msbemba** [comment]
@ghadirim Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9283

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ghadirim Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
