### ISSUE TITLE
Permissions required

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#9265]
Please make a habit of describing the permissions/roles required to perform the actions in the article. Not everybody has the global admin role....
Specific to this page: what role or permission is required and where do you configure this (e.g. to download on- and offboarding packages)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e4b5c5a-10ba-3e0c-af47-c51fa5a7ccc3
* Version Independent ID: 1704fddc-5cda-e55e-3190-74a748ae2e3d
* Content: [Onboard devices and configure Microsoft Defender for Endpoint capabilities](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-configure?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-configure.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@andrePKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9284

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andrePKI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
