### ISSUE TITLE
Documentation Errors?

### ISSUE THREAD

**Issue by MikeCleary-SEC** [MicrosoftDocs/microsoft-365-docs#9273]
Several items unless I'm doing something wrong....

Step 4
- IsArchive default behavior for blank appears to be TRUE not FALSE
- TargetRootFolder doesn't appear to work as documented either.  Blank and  "/" create a folder at the same level as Inbox and the std folder called "user@contoso.com" (old / incoming PST file) then has several subfolders one of which is "Top of Information Store" and under that are the original mailbox folders such as Inbox, etc..  Neither option appears to "merge" the incoming data into existing folders such as Inbox, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import PST files - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide#step-1-copy-the-sas-url-and-download-azcopy)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by MikeCleary-SEC** [comment]
Just to be clear - regarding the PST mapping file, the "blank" option does work as defined - sort of, I guess (it creates the Imported folder at the top level, then a subfolder under that named as the email address of the incoming data, then under that all the standard folders)

What's not working as defined is the "/" option.  It essentially does the same thing as the blank except instead of starting with an "Imported" folder at the top level, it starts with the folder named "user@domain.name", then a series of 4-5 folders, one of which is called "Top of Information Store" and in that one you have the standard Inbox, etc.

The following text from the doc does not appear to be correct....
_If you specify /, the folders and items in the PST file are imported to the top of the folder structure in the target mailbox or archive. If a folder exists in the target mailbox (for example, default folders such as Inbox, Sent Items, and Deleted Items), the items in that folder in the PST are merged into the existing folder in the target mailbox. For example, if the PST file contains an Inbox folder, items in that folder are imported to the Inbox folder in the target mailbox. New folders are created if they don't exist in the folder structure for the target mailbox._

**Comment by yogkumgit** [comment]
@MikeCleary-SEC Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
