### ISSUE TITLE
Add Microsoft Business Basic for [User requested to release a quarantined message] Default alert

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/microsoft-365-docs#9274]
Add Microsoft Business Basic for [User requested to release a quarantined message] Default alert
The documentation only includes  following E1/F1/G1, E3/F3/G3, or E5/G5 however the alert is included in Microsoft Business Basic and works and also seems to work
===========
User requested to release a quarantined message | Generates an alert when a user requests release for a quarantined message. To request the release of quarantined messages, the Allow recipients to request a message to be released from quarantine (PermissionToRequestRelease) permission is required in the quarantine policy (for example, from the Limited access preset permissions group). For more information, see Allow recipients to request a message to be released from quarantine permission. This policy has an Informational severity setting. | Threat management | No | E1/F1/G1, E3/F3/G3, or E5/G5
https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide#default-alert-policies
==============
 [User requested to release a quarantined message] is Default alert used for quarantine notification as per engineering this is included and expected to work
Raising request to update the documentation to add Microsoft Business Basic here

<Could n't use review site to submitting at github>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Microsoft 365 alert policies - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide&source=docs#default-alert-policies)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**User requested to release a quarantined message	Generates an alert when a user requests release for a quarantined message. To request the release of quarantined messages, the Allow recipients to request a message to be released from quarantine (PermissionToRequestRelease) permission is required in the quarantine policy (for example, from the Limited access preset permissions group). For more information, see [Allow recipients to request a message to be released from quarantine permission](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide#allow-recipients-to-request-a-message-to-be-released-from-quarantine-permission). This policy has an Informational severity setting.	Threat

**Comment by msbemba** [comment]
@qaehtesh Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9291

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @qaehtesh Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
