### ISSUE TITLE
Where is the definitive place to find the latest version?

### ISSUE THREAD

**Issue by reticentnz** [MicrosoftDocs/microsoft-365-docs#9278]
I can see version 4.18.2207.2 is available on SCCM, yet there is no mention of this version on this page as being available. If it's not here, where can I see information on this version?

**Comment by yogkumgit** [comment]
@reticentnz Please indicate which document you are referring to. Thanks

**Comment by reticentnz** [comment]
Apologies, it is this page I'm referring to - [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus.md)

**Comment by msbemba** [comment]
@reticentnz Thank you for your feedback. The latest update from the catalog still shows 1.18.2205.7 

The definitive place to get the latest version is https://www.catalog.update.microsoft.com/search.aspx?q=antimalware

The author will update the document once more information is available about this.

CC :  @denisebmsft


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @reticentnz Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
