### ISSUE TITLE
Page out of Date

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/microsoft-365-docs#9279]
Hi,

After the setting Zero-hour auto purge (ZAP) for malware, this page isn't in line with the portal. It should be asking for Quarantine Policy, and there is a different notification section

Regards
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b89afa39-ea8f-bfa3-d600-0bb5fda0805f
* Version Independent ID: 8b0ccaa2-9d59-1677-4cf1-1a3cacfc9239
* Content: [Anti-malware protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-malware-protection?view=o365-worldwide#anti-malware-policies)
* Content Source: [microsoft-365/security/office-365-security/anti-malware-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-malware-protection.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Jlouden9, confirmed. The two issues were:

- Remove Recipient Notifications
- Add Quarantine Policy after ZAP and before Admin Notifications

Updates should publish F 7/20 ~4:00PM GMT-7

OK?

**Comment by yogkumgit** [comment]
@Jlouden9 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
