### ISSUE TITLE
Change a user's display name hasn't taken effect in 24 hours to Teams apps.

### ISSUE THREAD

**Issue by puppleStar77** [MicrosoftDocs/microsoft-365-docs#9280]
[Enter feedback here]
Change has taken effect to azure active directory and Office admin center, Teams admin center.
But It still not updated Teams web app and windows client app.
My office 365 business plan is 365 Business standard.
How long time does it take to the changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f42a1bfc-8920-c16d-f4c9-d29b401b7f6c
* Version Independent ID: 979b71da-fdff-238d-41fb-472f1591e51e
* Content: [Change a user name and email address - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/change-a-user-name-and-email-address?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/change-a-user-name-and-email-address.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/change-a-user-name-and-email-address.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@puppleStar77 Thank you for your feedback. These changes are usually reflected within 24 hours. If it does not reflect, I'd recommend you to contact support via the need help section on the admin center so that they can help you fix this.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @puppleStar77 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
