### ISSUE TITLE
Unclear if we can use wildcard in sending infrastructure

### ISSUE THREAD

**Issue by petersonal2** [MicrosoftDocs/microsoft-365-docs#9281]
[Enter feedback here]
At  [Tenant allow/blocklist page](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/allow-block-email-spoof?view=o365-worldwide#domain-pair-syntax-for-spoofed-sender-entries) there is a "Domain pair syntax for spoofed sender entries" topic. At Sending infrastructure the valid values are listed, but there is not mentioning wildcard characters. However, the graphical interface is accepting it. I am attaching a picture.
![image](https://user-images.githubusercontent.com/99815287/181700634-c024bb53-6533-4bb4-b3ef-87099cdd52fa.png)
It is very important to know if we can use a wildcard.

Why is a situation I want to wildcard a sending infrastructure you may ask. 
Our government has not so good IT department, and we can not ask them to fix their domain settings. Yet we must, and immediately have to receive their mails, because it have some deadlines, and some legal rights to we must respond in time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d9b787f-def1-bbc5-48ca-42180f9560d2
* Version Independent ID: 3d9b787f-def1-bbc5-48ca-42180f9560d2
* Content: [Allow or block emails using the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/allow-block-email-spoof?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/allow-block-email-spoof.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/allow-block-email-spoof.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by petersonal2** [comment]
I opened an MS ticket, a 2nd level engineer told to the 1st level who told me, it is not possible to use a wildcard. Still it should be updated in the docs.

**Comment by msbemba** [comment]
@petersonal2 Thank you for your feedback. We have added a note to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9358

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @petersonal2 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
