### ISSUE TITLE
The links on this page go to strange locations

### ISSUE THREAD

**Issue by briettaeasterlin** [MicrosoftDocs/microsoft-365-docs#9286]
[Enter feedback here]
https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-overview?view=o365-worldwide#components

These links: 

"Additional Microsoft 365 products
[Microsoft 365 Business Premium](https://docs.microsoft.com/en-us/microsoft-365/admin/?view=o365-worldwide)

Bring together the best-in-class productivity and collaboration capabilities with device management and security solutions to safeguard business data for small and midsize businesses.

[Microsoft 365 Education](https://docs.microsoft.com/en-us/education)

Empower educators to unlock creativity, promote teamwork, and provide a simple and safe experience in a single, affordable solution built for education.

[Microsoft 365 Government](https://www.microsoft.com/microsoft-365/government)

Empower United States public sector employees to work together, securely."

Do not go to pages about these products but IT Admin documentation pages. Very strange experience for a 'shopper' looking for more info on our products. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d7c22cf-ff91-7e45-37ea-dc0cd576c719
* Version Independent ID: d3e6043a-aff1-8de9-50f1-98a39253ade9
* Content: [Microsoft 365 for enterprise overview - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-overview?view=o365-worldwide#components)
* Content Source: [microsoft-365/enterprise/microsoft-365-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-overview.md)
* Service: **o365-solutions**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@briettaeasterlin  Thank you for your feedback.  We have made changes to the M365 Business premium link via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9359

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @briettaeasterlin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
