### ISSUE TITLE
Microsoft 365 DNS records for Cloudflare docs - _sipfederationtls SRV record (Skype for Business) is wrong

### ISSUE THREAD

**Issue by daniel-ayers** [MicrosoftDocs/microsoft-365-docs#9289]
[Enter feedback here]

The table shown in step 5 of the Skype for Business section of page https://docs.microsoft.com/en-gb/microsoft-365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide#add-the-two-required-srv-records is wrong.

The 2nd, 3rd and 4th columns of the second row of the table are in the wrong order.  This leads to nonsensical values being shown.

The 4th column value ("Use your domain_name; for example, contoso.com") should be in the second column and the other two columns should be shifted one place to the right.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6107c99-df0b-8a33-f291-086ea6fd5034
* Version Independent ID: 0ba87689-7a57-c3f8-af4b-3267c81b933d
* Content: [Connect your DNS records at Cloudflare to Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/dns/create-dns-records-at-cloudflare?view=o365-worldwide#add-the-two-required-srv-records)
* Content Source: [microsoft-365/admin/dns/create-dns-records-at-cloudflare.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/dns/create-dns-records-at-cloudflare.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene*
![m365-incorrect-lync-srv-records](https://user-images.githubusercontent.com/21326961/182003897-2592d96a-de04-4199-9ae1-2ae1046f2a91.png)
*

**Comment by msbemba** [comment]
@daniel-ayers Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9343

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @daniel-ayers Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
