### ISSUE TITLE
The published hash does not match

### ISSUE THREAD

**Issue by ramus82** [MicrosoftDocs/microsoft-365-docs#9294]
Hi,
the hash published on the site does not match with hash produced when the file "xmde_client_analyzer.zip" is downloaded.
Regards
M.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95ba8ed0-8234-d514-f06e-3ce69e60bfec
* Version Independent ID: 51d6d3ae-6100-7acb-af46-e8ec6b9fe84f
* Content: [Run the client analyzer on macOS or Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-analyzer-macos-linux.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@ramus82 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9360

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ramus82 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
