### ISSUE TITLE
Security Operations Center

### ISSUE THREAD

**Issue by DPIZee** [MicrosoftDocs/microsoft-365-docs#9295]
Security Operations Dashboard [no longer exists](https://docs.microsoft.com/en-us/microsoft-365/security/defender/microsoft-365-security-center-mde?view=o365-worldwide), but is documented on this and many other pages.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52cf9eaa-c236-18f7-1a55-9707b953859c
* Version Independent ID: 59ee1886-914c-1d7d-ab5c-241efe9e2724
* Content: [Microsoft Defender Security Center Security operations dashboard](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/security-operations-dashboard?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/security-operations-dashboard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/security-operations-dashboard.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Content removed.
