### ISSUE TITLE
**playbook** provided has a broken link

### ISSUE THREAD

**Issue by thiagobeier** [MicrosoftDocs/microsoft-365-docs#9296]
hi there the **playbook** provided has a broken link

https://download.microsoft.com/download/9/c/1/9c167271-8209-492e-acc2-38a39d1834c2/m365bp-cybersecurity-playbook.pdf

under **Protect All Email **section 
the link [https://aka.ms/M365BP-email](https://aka.ms/M365BP-email) goes to  [https://docs.microsoft.com/en-us/microsoft-365/business-premium/avoid-phishing-and-attacks?view=o365-worldwide](https://docs.microsoft.com/en-us/microsoft-365/business-premium/avoid-phishing-and-attacks?view=o365-worldwide) **<< broken link / page not found**

have a great day
Thiago

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd32d15-8d01-ed9e-14ab-4dbde9df87ca
* Version Independent ID: f43c036b-3408-fcec-3a68-3e74f5a04d96
* Content: [Microsoft 365 Business Premium overview - Microsoft 365 Business Premium](https://docs.microsoft.com/en-us/microsoft-365/business-premium/?view=o365-worldwide)
* Content Source: [microsoft-365/business-premium/index.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business-premium/index.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @thiagobeier! Thank you so much for letting us know about the link issue. It's fixed! I appreciate your calling this to our attention. Have a great day!
