### ISSUE TITLE
Clarify difference compared to "Report messages to Microsoft for analysis"

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#930]
If you go to protection.office.com &gt; Threat Management &gt; Review &gt; Quarantine and select a quarantined message you can "Submit message" - great! But how does this differ from "Release message" and selecting [v] Report messages to Microsoft for analysis. Why to ways and how do they differ, if at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 162f11ad-8add-952e-fd64-488e8e3f3b14
* Version Independent ID: addf14d5-f1c1-662d-9844-6888df0349bd
* Content: [Admin submissions in Office 365, O365 submissions, Office 365 spam problem, O365 false negative, submit phish in office 365, submit email for scanning, suspicious email in Office 365, scan a mail, have Microsoft scan for phish, have Microsoft scan for spam, submit e-mail, submit email, dodgy email, bad actor mail, suspicious, untrusted mail, report phish emails to Microsoft, report phish emails to Microsoft, report malicious email to Microsoft, report scam email to Microsoft, report malware in email to Microsoft, spam email in inbox office 365, virus in email office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/admin-submission#feedback)
* Content Source: [microsoft-365/security/office-365-security/admin-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/admin-submission.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MaratMussabekov** [comment]
Hello @JonesMikael,
When you choose to submit message - you send false negative and false positive spam messages to Microsoft for analysis. From this article "When you submit an email, you will get information about any policies that may have allowed the incoming email into your tenant, as well as examination of any URLs and attachments in the mail. Policies that may have allowed a mail include an individual user's safe sender list as well as tenant level policies such as ETR rules." So it helps to understand why email bypassed spam (or did not bypassed in case of false-positive).

When you release message with reporting - you send to Microsoft a message that should not been marked as spam but it did. From [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-an-administrator): "report it as a false positive (not junk) message to the Microsoft Spam Analysis Team, who will evaluate and analyze the message. Depending on the results of the analysis, the service-wide spam content filter rules may be adjusted to allow the message through."

So submitting usually means that you want to receive information back from Microsoft to improve your own configuration, while reporting - you just send info to Microsoft to allow team to improve spam analysis service.

Thank you

**Comment by mypil** [comment]
@JonesMikael - From our understanding, the issue you raised has been answered by MaratMussabekov  so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
