### ISSUE TITLE
Advanced Hunting queries are wrong (- instead of | character used). Copy/paste won't work

### ISSUE THREAD

**Issue by rfellmann** [MicrosoftDocs/microsoft-365-docs#9303]
[Enter feedback here]

In the Advanced Hunting query examples, replace '-' with the pipe character '|'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395141e8-be91-e226-24d7-dc136b8f9c5e
* Version Independent ID: 012beed4-1fdb-4f59-9cc4-53ba5e2c8ea2
* Content: [Use network protection to help prevent connections to bad sites](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection?view=o365-worldwide#advanced-hunting)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@rfellmann Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9340

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rfellmann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
