### ISSUE TITLE
The commands for New-TenantAllowBlockListItems don't work. They say Allow and ListType aren't valid

### ISSUE THREAD

**Issue by zinkco22** [MicrosoftDocs/microsoft-365-docs#9304]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17ce75e-79ba-0acd-066c-a0120a29d65d
* Version Independent ID: 14673b1c-8489-0abc-90a0-42f35d516424
* Content: [Configure the delivery of third-party phishing simulations to users and unfiltered messages to SecOps mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-advanced-delivery?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configure-advanced-delivery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-advanced-delivery.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@zinkco22, I copied the New-TenantAllowBlockListItems commands from Step 3 in an E5 nothing special test tenant as a Global admin, and it worked fine for me.

- What version of the EXO V2 PowerShell module are you using? v2.0.5 is the latest general release, and v2.0.6-Preview6 is the latest Preview release. Make sure you're up to date. If you're using v2.0.6, try using the `-UseRPPSSession` switch in the connect command as described [here](https://docs.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-206).
- Also, make sure you're [connected to Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell) before you run the command.

**Comment by zinkco22** [comment]
I’m running it with Business Premium and trying to run it in the Security and Compliance PowerShell since I want to add a set of URLs to the PhishingSimulation “Simulation URLs to allow”
For reference this is the script I’m trying to use.
New-TenantAllowBlockListItems -Allow -ListType Url -ListSubType AdvancedDelivery -Entries "*.com-token-auth.com/*","*.com-onlinebanking.com/*","*.password.land/*","*.2o2.lol/*","*.protected-forms.com/*","*.net-login.com/*","*.ancillarycheese.com/*","*.bloemlight.com/*","*.comano.us/*","*.msftemail.com/*" -NoExpiration

Cody Zink
M365CSAA
Security Implementation Engineer

worksighted | Professional Services
Need support?
phone: 616.546.2691<tel:616.546.2691> x1 | 888.978.7768<tel:888.978.7768>   
email:  ***@***.******@***.***>
 
Customer Feedback | How am I doing?
Please contact my manager: ***@***.******@***.***>

**Comment by chrisda** [comment]
@zinkco22, I updated the topic to use Exchange Online PowerShell.

Thanks for the feedback.

Closing
