### ISSUE TITLE
Needs to show api permissions required to query AlertEvidence and AlertInfo

### ISSUE THREAD

**Issue by katlim-br** [MicrosoftDocs/microsoft-365-docs#9306]
This page needs to show the Azure Active Directory/App Registration permissions needed. I can't seem to make it work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c882661-62c9-213d-efd1-23ffcf4fcc4a
* Version Independent ID: 1498f182-802c-5b87-1a83-3341b75eb48e
* Content: [AlertInfo table in the advanced hunting schema](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-alertinfo-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-alertinfo-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-alertinfo-table.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@katlim-br Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9339

Once the author approve, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @katlim-br Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
