### ISSUE TITLE
Populated custom fields not displayed for staff

### ISSUE THREAD

**Issue by simonkurtz-MSFT** [MicrosoftDocs/microsoft-365-docs#9307]
I added two required custom fields that, when booking, must be filled out before submitting the request. This works; however, on the staff side - regardless of whether I am using the new or old booking UI - I cannot see the meeting agenda and customer organization anywhere. The absence of this essentially has me guessing as to what the meeting is about and whom I am meeting with (organizationally). 

It would also be helpful to have the customer add a meeting subject and body/agenda more natively.

![image](https://user-images.githubusercontent.com/84809797/182426043-7ef35c6b-bdeb-40bb-bac4-15d1f95b296b.png)

<img width="249" alt="image" src="https://user-images.githubusercontent.com/84809797/182426378-c13e6d16-2589-43ee-bb52-353788c02a56.png">

<img width="520" alt="image" src="https://user-images.githubusercontent.com/84809797/182426504-38f47452-8558-4cb3-b587-85234092390b.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c94c3452-09eb-3ca1-0a9e-e46b3ac6b345
* Version Independent ID: 3f184821-e68d-fcae-a312-f3e3d0b4e97f
* Content: [Add custom and required questions to the booking page](https://docs.microsoft.com/en-us/microsoft-365/bookings/add-questions?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/add-questions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/add-questions.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@simonkurtz-MSFT Thank you for your feedback. We have had another customer report a similar issue and this sounds more like a bug. This needs to be handled by the product group, so I'd recommend you create a support ticket via the need help section and report the issue to the support engineer who can take this forward.

Hope this helps!

Thanks
Sri

**Comment by simonua** [comment]
Thank you, @msbemba. I just filed the bug. Let's keep this issue open here until a resolution is found, please, in case it requires changes to the documentation.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @simonua Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
