### ISSUE TITLE
ASR - Behavior Changes - Blocking under User Context Now?

### ISSUE THREAD

**Issue by brink668** [MicrosoftDocs/microsoft-365-docs#9311]
### Under the Section "How do ASR rules exclusions work?"
It states "ASR rules run under **NT AUTHORITY\SYSTEM account**, so environmental variables are limited to machine variables." 

### **Since 7-27-2022**
I have been seeing around 40 of 1800 machines in my work environment that are showing blocks under %userprofile% or usercontext for .dll blocks.  This is new behavior and is recent.

ASR Rule/Example Path - that is having this issue

- Block executable content from email client and webmail
- GUID: be9ba2d9-53ea-4cdc-84e5-9b1eeee46550
- Path: %userprofile%\AppData\Local\Assembly\tmp\*various*files*and*paths*.dll

Did this behavior change, this a preview of a new feature or is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad81808-0605-037f-364e-9d061d593078
* Version Independent ID: 62044527-8d7e-3dea-d872-83638fe7b14c
* Content: [Attack surface reduction frequently asked questions (FAQ)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq.yml)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @martyav
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@brink668 Thank you for your feedback. There have been no changes recently on ASR. This sounds more like a bug and I'd recommend you to report it to Support via the need help section on the admin center so that our product group can fix this.

Hope this helps!

Thanks
Sri

**Comment by brink668** [comment]
I have a support ticket open. Thank you for your reply.
