### ISSUE TITLE
Idle session timeout on unmanaged devices policy doesn't seem to be needed

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/microsoft-365-docs#9314]
> For idle session timeout to get triggered on unmanaged devices, you'll need to add a Conditional Access policy in the Azure AD admin center

There must be something else you intended to say there, some other condition, because I can confirm that idle session timeout triggers for unmanaged devices without the policy. I didn't even notice the part in the article about the policy until today, so accordingly the policy does not exist in my tenant. I've had idle session timeout, however, enabled and working for a month.

None of our devices are managed/compliant.

Yet idle session timeout works for Windows 10/11 at least. With Edge or Chrome (and in Chrome's case, not even using the
Windows Accounts extension). These devices are not even listed at all in Azure AD/All Devices (you can't get any more unmanaged than that). We also have some listed there as Azure AD Registered (also typically considered "unmanaged," or at least not compliant), and they work too.

So, clearly, there's something more to what you meant to say or I have a major misunderstanding about what an unmanaged device is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Version Independent ID: ccb07d88-8193-95d8-0e19-aa96f2d1668c
* Content: [Idle session timeout for Microsoft 365 - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/idle-session-timeout-web-apps?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/idle-session-timeout-web-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/idle-session-timeout-web-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@kwekuako Please help us in resolving this issue. Thanks

**Comment by rpodric** [comment]
@yogkumgit The answer is a typo in the article:

"The intent of that statement is to limit the policy trigger **only** on unmanaged devices. By default, the policy triggers for all device types (managed or unmanaged), but if you want to restrict it only to unmanaged devices, then you need to configure the CA policy as well. "

**Comment by msbemba** [comment]
@rpodric Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9480

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rpodric Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by rpodric** [comment]
@yogkumgit Yes, very good. Thanks.

**Comment by daveb10** [comment]
I think this is still unclear. The idle session timeout M365 setting controls both managed and unmanaged devices, noting the caveats. The setting overrides the SharePoint and OWA policies. How can a conditional access policy the enforces app restrictions for all users remove the M365 setting’s impact on managed devices?

**Comment by MrV8Rumble** [comment]
I found this issue wondering the same thing. I'm not sure how a CA policy that doesn't check for managed status can control this activity.

**Comment by rpodric** [comment]
@daveb10 and @MrV8Rumble Does this answer it (I don't know, I'm asking)?

https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-session#application-enforced-restrictions

"The device information allows cloud apps to know if a connection is from a compliant or domain-joined device and update the session experience. When selected, the cloud app uses the device information to provide users with a limited or full experience. Limited when the device isn't managed or compliant and full when the device is managed and compliant."
