### ISSUE TITLE
DeviceAlertEvents No Longer Provided

### ISSUE THREAD

**Issue by Wittkie** [MicrosoftDocs/microsoft-365-docs#9316]
[Enter feedback here]

As per : https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-migrate-from-mde?view=o365-worldwide

"The AlertInfo and AlertEvidence tables replace the DeviceAlertEvents table in the Microsoft Defender for Endpoint schema."

Microsoft Alias: jwittkie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9fd21fa-e367-78d4-bc86-80f2b75a64b8
* Version Independent ID: 97a42f10-ba7f-f2d4-6c5c-69e38a99f277
* Content: [DeviceAlertEvents table in the advanced hunting schema](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/advanced-hunting-devicealertevents-table.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by msbemba** [comment]
@Wittkie Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9338

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Wittkie Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
