### ISSUE TITLE
Misspelling 

### ISSUE THREAD

**Issue by NukaEv** [MicrosoftDocs/microsoft-365-docs#9318]
Before you get started, **yu** need to configure Exchange Online Protection and Defender for Office 365 so user reported messages are delivered to the user submissions mailbox without being filtered as described in the following steps:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53205b5-8850-42b6-0b0c-8a61b7ef7776
* Version Independent ID: 0a9e7903-ce3c-e877-e6b3-b45d09642308
* Content: [User-reported email settings for spam, phish, as malicious mail - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/user-submission?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/user-submission.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/user-submission.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by NukaEv** [comment]
Just happen to see it figured I would shout it out.

**Comment by chrisda** [comment]
@NukaEv, fixed. In the future, you too can make fixes like this yourself without opening an Issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
