### ISSUE TITLE
Step 3: Create a search permission filter, users sub instruction mislabel

### ISSUE THREAD

**Issue by jwgarrett** [MicrosoftDocs/microsoft-365-docs#9319]
Howdy,

If you search for this
Users: Specifies the users or groups who get this filter applied to the search actions they perform. For compliance boundaries, this parameter specifies the role groups (that you created in Step 3) in the agency that you're creating the filter for. Note this is a multi-value parameter so you can include one or more role groups, separated by commas.

It should be "Step 2" instead of Step 3

Users: Specifies the users or groups who get this filter applied to the search actions they perform. For compliance boundaries, this parameter specifies the role groups (that you created in Step 2) in the agency that you're creating the filter for. Note this is a multi-value parameter so you can include one or more role groups, separated by commas.

Keep on being awesome!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffb84a4-0c98-3fc2-8963-4c809efaa149
* Version Independent ID: 305dd7b2-382e-a0da-40b5-1457e6b625bd
* Content: [Set up compliance boundaries for eDiscovery investigations - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-compliance-boundaries.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-compliance-boundaries.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@jwgarrett Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9337

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jwgarrett Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
