### ISSUE TITLE
Information for O365 Advanced eDiscovery v1 GCC

### ISSUE THREAD

**Issue by rstraker** [MicrosoftDocs/microsoft-365-docs#932]
The documentation for O365 Advanced eDiscovery on https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-advanced-ediscovery?source=docs is only for the current v2 version of Advanced eDiscovery.  My GCC customers do not have access to this version and need the documentation for the prior version of Advanced eDiscovery for current operations training and knowledge.  @Dan Narloch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 999fd055-4d82-d9f5-cc3b-f5823714dfde
* Version Independent ID: e302eab7-ab91-0b19-c0bb-07e7138eb338
* Content: [Office 365 Advanced eDiscovery](https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-advanced-ediscovery#feedback)
* Content Source: [microsoft-365/compliance/office-365-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/office-365-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by markjjo** [comment]
@rstraker The link you cite above (https://docs.microsoft.com/en-us/microsoft-365/compliance/office-365-advanced-ediscovery) is the documentation for the v1 version of Advanced eDiscovery. 

The documentation for the v2 version of Advanced eDiscovery is here: https://docs.microsoft.com/en-us/microsoft-365/compliance/overview-ediscovery-20 

Apologies for the confusion. We tried to separate these in the table of contents, but it's still confusing.
