### ISSUE TITLE
Spelling mistake on Event ID 5013

### ISSUE THREAD

**Issue by timurengin** [MicrosoftDocs/microsoft-365-docs#9327]
The description of the event for Event ID 5013 has an _if_ instead of an **is**:

> ... any attempt to change any of Defender's settings _if_ blocked and Event ID 5013 ...

I think the _if_ should be an **is** here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102c5c34-0c04-cc14-8e9c-74ff42e1fdc2
* Version Independent ID: 6a06016e-6ac1-ab00-5a33-1d1226e2e45d
* Content: [Microsoft Defender Antivirus event IDs and error codes](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @timurengin. Thank you so much for letting us know about this issue. I've updated the doc, and the updates will render live later today.
