### ISSUE TITLE
Update addIn removal timeframe from 72 to 24 hours

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/microsoft-365-docs#9331]
Hi Team - per a recent interaction with the Centralized Deployment engineering team, it was relayed that the SLA for removing an addIn from a user should be 24 hours, not the 72 hour time frame that is documented in this article.  Please can this be updated accordingly?

https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide#how-long-does-it-take-for-add-ins-to-show-up-for-all-users-

Section "How long does it take for addIn to show up for all users".  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32aaf301-bc79-ea37-f3fd-94ae9e9ab02f
* Version Independent ID: 7482cca5-faac-3276-8481-e6323cafef31
* Content: [Centralized Deployment FAQ](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-FAQ.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-FAQ.yml)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@drdenson Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9379

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by drdenson** [comment]
Thank you!

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @drdenson Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
