### ISSUE TITLE
Video not working "Failed to download error message" 

### ISSUE THREAD

**Issue by sanketshah11** [MicrosoftDocs/microsoft-365-docs#9332]
(https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-get-started-with?view=o365-worldwide)
This link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3c5c98-9f47-9512-b932-2f72822796d2
* Version Independent ID: fd477cf9-4ee0-544f-10c6-f3dfccb10186
* Content: [Get started with trainable classifiers - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/classifier-get-started-with?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/classifier-get-started-with.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/classifier-get-started-with.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@sanketshah11 Thank you for your feedback. The video in the document is working currently. Please use an incognito window as there could be a browser issue on your end.

![image](https://user-images.githubusercontent.com/45987684/183716649-4fa84d18-30b4-4c3a-9e20-b348627726f7.png)


Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sanketshah11 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
