### ISSUE TITLE
PQMT: Lacking of the information about new endpoint *.powerautomate.com

### ISSUE THREAD

**Issue by Saki-Yufu** [MicrosoftDocs/microsoft-365-docs#9333]
[Description]
Lacking of the information about new endpoint *.powerautomate.com.

The following URL indicates that there will be a change in June-July 2022, when the domain of Power Automate portal will be moved from *.flow.microsoft.com to *.powerautomate.com.
> URL: https://app.cloudscout.one/evergreen-item/mc386412/

However, since the following page does not mention *.powerautomate.com as an Office 365 endpoint, we assume that users have no control over the URL, which would cause confusion.
> URL: https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&source=docs

By the way, the following page has the mention for *.powerautomate.com.
> URL: https://docs.microsoft.com/en-us/power-automate/ip-address-configuration

Please refer to the attached file (20220804_1.png).

[Actual result]
No mention of *.powerautomate.com on this page.
> URL: https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&source=docs

[Expected result]
Endpoint information for *.powerautomate.com is added to the following page.
> URL: https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&source=docs

[Source] 
Japan Internal Feedback

[Copied from]
https://microsoft.sharepoint.com/:li:/t/ntojapan/pqmt/ExNTaZsIif1Eo22Umo2ak-QBNufhaD2aIihvXWRtVPA19A?e=BfcJB7

![20220804_1](https://user-images.githubusercontent.com/103729056/183033069-c1302444-52c0-4a91-8c20-222360f7df8d.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by Saki-Yufu** [comment]
Hi. It does not seem to be fixed yet. 
Do you have any update for this? Thanks.

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out. I will find the appropriate engineering resource to make this change and update the issue when I have any new information. -Kelley

**Comment by kelleyvice-msft** [comment]
Thanks for reaching out to the Microsoft 365 Enterprise content team. Because all Microsoft 365 endpoints data displayed in learn.microsoft.com articles is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data. 

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.

**Comment by Saki-Yufu** [comment]
OK, I will report the problem to other databases.
Thank you for investigating!
