### ISSUE TITLE
Still shows Skype Data

### ISSUE THREAD

**Issue by RInfoSec-Alerts** [MicrosoftDocs/microsoft-365-docs#9334]
Is Skype still available? this template still shows Skype, shouldn't this be removed now?

**Comment by yogkumgit** [comment]
@RInfoSec-Alerts Please let us know which document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@RInfoSec-Alerts We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
