### ISSUE TITLE
These options need a GUI

### ISSUE THREAD

**Issue by A9G-Data-Droid** [MicrosoftDocs/microsoft-365-docs#934]
Some things work better on the command line. This is not one of those things. Being able to update text, and graphics with a live example of how the message will look is critical to success here. This article doesn't talk about verification. What's the workflow here? Run some PowerShell commands, send an e-mail, wait, look at the formatting, and then try again? That's not an efficient way to edit a visual style. The editor should be like a WYSIWYG editor. As you change the elements on the right sidebar the content in the middle changes, showing what the e-mail will look like. Then you only need to send one test e-mail at the end to verify that the actual e-mail matches what was shown in the editor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b04de3d3-6a94-29f8-3a3d-68ed9422e058
* Version Independent ID: e50fc407-2c78-a3cc-71cd-7978ca340189
* Content: [Add your organization brand to your encrypted messages](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages)
* Content Source: [microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-your-organization-brand-to-encrypted-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by LauraWi** [comment]
Thank you for this feedback on the product. Can you open an item on the O365 User Voice instance to make sure it gets routed to engineering (others can help upvote your request). Thank you! https://office365.uservoice.com/forums/289138-office-365-security-compliance
