### ISSUE TITLE
Replace English screenshots with German ones for the German docs

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#935]
Hello,

as I'm unable to report issues at Github for the German version of these docs, I report it here: The German docs should have screenshots from the German UIs to know how a message will look like in German. Right now, the screenshots of the German docs are in English.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce36344d-67bf-68cb-5004-9ac6f27ebf51
* Version Independent ID: 89a7d7e7-c643-eb06-d844-b97b80633b68
* Content: [Create, test, and tune a DLP policy - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-test-tune-dlp-policy#feedback)
* Content Source: [microsoft-365/compliance/create-test-tune-dlp-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-test-tune-dlp-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by mypil** [comment]
@GiantCrocodile - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@GiantCrocodile - Can you please share the URL of the German version of the doc you're referencing in this issue?

Thank you.

**Comment by GiantCrocodile** [comment]
@mypil https://docs.microsoft.com/de-de/microsoft-365/compliance/create-test-tune-dlp-policy#feedback

**Comment by mypil** [comment]
@tinamcN -  There appears to be a Translation/Localization issue on the screenshot/images in the German version (https://docs.microsoft.com/de-de/microsoft-365/compliance/create-test-tune-dlp-policy#feedback) of this doc. Can you please assist with this?

Thank you.

cc: @kenwith

**Comment by TinaMcN** [comment]
@GiantCrocodile thanks for the feedback.  This particular article is machine translated and we don't currently translate images in MT content.  We are working on a tool to machine translate art but it may be 6 months before it's ready.   In the meantime I switched this particular article to be human translated so we can the art translated.  @OfficeGlobal can you please advise how long it will take to get the localized art published.

**Comment by OfficeGlobal** [comment]
@TinaMcN the project is currently involved in DTT test, therefore we don't know when the article will be downloaded for an update.
Since there is a lot of images, it will take ~4 days for process once downloaded

**Comment by cabailey** [comment]
@GiantCrocodile  I see all the screenshots in German, so I think this issue can now be closed?

**Comment by GiantCrocodile** [comment]
I can confirm this @cabailey. I will close the issue.
