### ISSUE TITLE
One link still broken

### ISSUE THREAD

**Issue by Hindy-UK** [MicrosoftDocs/microsoft-365-docs#9355]
This is a follow-up to my previous issue #9293, which was closed following pull request #9341. There are still three links that are not correctly entered in the table:

- PowerShell -> Management options: Set-MpPreference and Update-MpSignature.
-  Microsoft Azure -> Reporting options: after “…SIEM tool to report on “.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af205543-b539-a7e8-a66c-f9365241fec9
* Version Independent ID: b9d4b071-f501-51a8-8565-859df13b7fa7
* Content: [Deploy, manage, and report on Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-manage-report-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/deploy-manage-report-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deploy-manage-report-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@Hindy-UK thank you for your attention to detail and for catching that we had STILL missed those three links. They're fixed now, and you will see the update render live later today. My apologies for the inconvenience. I appreciate you helping us to improve the quality of our documentation. Thank you again, and I hope you have a great weekend!
