### ISSUE TITLE
Poor Grammar

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/microsoft-365-docs#9356]
Early on this page, we read that "When these intermediary services, perform such actions, they can use ARC can be used to provide details of the original authentication before the modifications occurred, which your organization can then trust to help with authenticating the message."  Beyond being a very long sentence, it is grammatically ambiguous.  The phrase "they can use ARC can be used to provide details" specifically is bad.  They can use ARC, or ARC can be used?  Is there a difference between the two somehow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f9293f-c337-7af6-e994-336531d62f35
* Version Independent ID: 36f9293f-c337-7af6-e994-336531d62f35
* Content: [Use Trusted ARC senders for legitimate devices and services between the sender and receiver - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-arc-exceptions-to-mark-trusted-arc-senders.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@WillMartin58 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9383

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @WillMartin58 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by WillMartin58** [comment]
Thanks, this is much more understandable now.
