### ISSUE TITLE
Control score doesnt have testing status

### ISSUE THREAD

**Issue by pamvee** [MicrosoftDocs/microsoft-365-docs#9357]
There is wording under the control score saying:

"This sum is applied in its entirety to your overall compliance score when the control meets both of the following conditions:

Implementation Status equals Implemented or Alternative Implementation, and
Test Result equals Passed."

This is essentially how 'Improvement Action' score is calculated not at control level. Controls dont have testing statuses and test results. They are attributes of an IA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491e66c0-bfe6-58fa-4a1e-d79ee4ac0e2b
* Version Independent ID: 676dbe71-1ed1-e5db-2f16-f7c12c7565f7
* Content: [Compliance score calculation - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-score-calculation?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/compliance-score-calculation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-score-calculation.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by msbemba** [comment]
@pamvee Thank you for your feedback.  The control score is the sum of points earned by completing improvement actions within the control. 

So when IA is implemented and passed it adds up to the control score as it is the sum of points earned by completing IA.

Hope this helps!

CC: @chvukosw 

Thanks
Sri

**Comment by pamvee** [comment]
Hello @Christie ***@***.***>,

I agree. But the wording says "This sum is applied in its entirety to your overall compliance score when the control meets both of the following conditions:". Shouldn't that be ....when each of the Improvement Actions meets....", because both the conditions mentioned are only attributes at the IA level and not at the control level.

Regards,
Prameela Veeramachaneni (she/her)
Senior Product Manager | Microsoft Purview

**Comment by chvukosw** [comment]
Hi Prameela - thanks for bringing attention to this. I think that is correct, but let confirm that with Elliot before making the update. I'll provide an update here before closing out.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @pamvee Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by chvukosw** [comment]
@pamvee Letting you know I discussed this with Elliot and we edited the page yesterday to clarify.

**Comment by pamvee** [comment]
Cool! Thanks Christie for letting me know!

Prameela Veeramachaneni (she/her)
Senior Product Manager | Microsoft Purview
