### ISSUE TITLE
Policy tips in latest Outlook desktop client - explain that it won't show details

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#936]
Hello,

please add a statement/information that if you do use the latest Outlook desktop client for Windows the second part of the OWA privacy tip is not shown:

> 'View details about the information that appears sensitive. Learn more'

The desktop client shows less information than OWA it seems and thus it should be mentioned that the privacy tips are not the same for all supported platforms.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips#feedback)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
@GiantCrocodile 

Thank you for your feedback.

I don't know the specifics of your configuration that results in the behavior you describe. It sounds like what you are reporting is that you are seeing different policy tip behavior from the exact same policy on the exact same message, the only difference being that one version of the message is being composed in OWA and the other version of the message on Outlook 2013?  What trouble shooting steps have you taken to diagnose and reproduce this?  Have you contacted Support?

**Comment by GiantCrocodile** [comment]
@chrfox According to the docs the OWA shows a privacy tip with a 'Show details' link like shown here: https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips#policy-tips-in-outlook-on-the-web-and-outlook-2013-and-later

My Outlook (version 1911; monthly update channel; German language file) shows this:
![grafik](https://user-images.githubusercontent.com/6271057/71212620-fb5db680-22b1-11ea-8e19-4829c7d7bbf9.png)

As you can see, the desktop client has no 'Show details' link and thus I can't view details as like as in OWA.

According to our CSP's tech team the Outlook client won't show details to understand why an email did trigger a specific DLP policy. The OWA will show this information. Microsoft support hasn't been contacted about this as it seems to be expected behavior although the difference isn't documented.

**Comment by GiantCrocodile** [comment]
Problem solved; some other docs clarified the situation and it was an Outlook bug which is gone/fixed by some update now.
