### ISSUE TITLE
missing information on enabling shared channel access

### ISSUE THREAD

**Issue by MattAlberga** [MicrosoftDocs/microsoft-365-docs#9361]
For the Shared channel to work, the "M365 groups" setting needs to have "Let group owners add people from outside your organization to Microsoft  365 groups as guests." 

This setting is to be enabled for shared channels to work. 
It is missing from all documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a95f6020-2131-ca5c-6fc7-202c4ea852f6
* Version Independent ID: a95f6020-2131-ca5c-6fc7-202c4ea852f6
* Content: [Enable shared channels with all external organizations](https://docs.microsoft.com/en-us/microsoft-365/solutions/allow-direct-connect-with-all-organizations?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/allow-direct-connect-with-all-organizations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/allow-direct-connect-with-all-organizations.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@MattAlberga Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9385

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MattAlberga Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
