### ISSUE TITLE
M365 Defender event hub verification hunting query formatting not formatted correctly

### ISSUE THREAD

**Issue by davekallenborn** [MicrosoftDocs/microsoft-365-docs#9363]
On the Microsoft 365 Defender docs for configuring event hub for streaming page, there is a section for verifying the data export is flowing: https://docs.microsoft.com/en-us/microsoft-365/security/defender/configure-event-hub?view=o365-worldwide#verify-that-the-events-are-being-exported-to-the-event-hubs

There is a section to run an Advanced Hunting query for verifying the event hub.  The screenshot looks like it has the correct query, but the query text is missing spaces.  I believe it should be something like this instead:
```Kusto
EmailEvents
|join kind=fullouter EmailAttachmentInfo on NetworkMessageId
|join kind=fullouter EmailUrlInfo on NetworkMessageId
|join kind=fullouter EmailPostDeliveryEvents on NetworkMessageId
|where Timestamp > ago(1h)
|count
```

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1302a36-d75f-2c77-0da1-333f81689805
* Version Independent ID: 8fd7095a-926c-6b12-07b4-0e50094bfba1
* Content: [Configure your Event Hubs](https://docs.microsoft.com/en-us/microsoft-365/security/defender/configure-event-hub?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/configure-event-hub.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/configure-event-hub.md)
* Product: **m365-security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@davekallenborn Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9386

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @davekallenborn Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
