### ISSUE TITLE
External Users in Shared Channel Keep Getting Disconnected from SharePoint Site

### ISSUE THREAD

**Issue by atrainSaaS** [MicrosoftDocs/microsoft-365-docs#9364]
- Setup Azure B2B as per article (allowed everything for both internal and external)
- Invited first external user into shared channel
- External user can post to channel, create, upload and edit files from "Files" tab in channel
- External user can open SharePoint site from "Files" tab
- External user gets disconnected from SharePoint site after a few moments of navigating SharePoint Site ("Home", "Site Contents" and a news article)
- External user cannot view SharePoint site from Team channel (via SharePoint channel app)
- Access is temporarily restored after a refresh, however, this only lasts for a few moments
- Connected with Microsoft Support - found out that the External user could NOT be found in **Azure > Users**
- (re) invited external user via Azure
- External user accepted invite, and can now navigate SharePoint site without being disconnected.
- External user now appears in "Azure > Users"

Why did I need to invite this external user twice for this to work as expected?  Is this a bug? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c083238f-2bbc-29e7-ca45-6ccc30c501bf
* Version Independent ID: c083238f-2bbc-29e7-ca45-6ccc30c501bf
* Content: [Collaborate with external participants in a shared channel](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-teams-direct-connect?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-teams-direct-connect.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-teams-direct-connect.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@atrainSaaS Thank you for your feedback. This certainly sounds like a bug in this tenant. I'd recommend you to contact Microsoft support via need help so that a support engineer can file a bug and get this resolved.

Hope this helps!

Thanks
Sri

**Comment by atrainSaaS** [comment]
Unfortunately, this issue is not exclusive to a single tenant.

I have two test users from 'Tenant A' . One is 'Tenant B' and the other in 'Tenant C'.

Both Tenants B and C have the exact same issue with external users from Tenant A.

I have already opened a ticket with Microsoft support.  That is how we discovered that the external users were missing from Azure > Users.

I'm not sure how else to surface this issue up to the right people.


________________________________

**Comment by msbemba** [comment]
@atrainSaaS  Thank you for your response. You are on the right track. Microsoft support will be able to file a bug with the product group to take this forward. We make modifications to the document if there are any changes to the design.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @atrainSaaS Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
