### ISSUE TITLE
Insider risk - excel 

### ISSUE THREAD

**Issue by Lionhart91** [MicrosoftDocs/microsoft-365-docs#9368]
Does Microsoft insider risk management track moving Excel tabs to a new Excel sheet, or copying and pasting contents in Excel sheet to a blank Excel sheet not located in OneDrive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b230596-3cff-a5b9-e9b6-09297a52796e
* Version Independent ID: e51c4653-7d8a-6090-baa8-3558a2efca57
* Content: [Learn about insider risk management - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@robmazz Please help us in resolving this issue. Thanks

**Comment by robmazz** [comment]
@Lionhart91 - thanks for the feedback. No, not that I'm aware of - but please confirm with your Microsoft Customer Service representative. Opening a support ticket will get this question answered by the team that can confirm.
