### ISSUE TITLE
Suggestion to add a note to clarify that the HR connector is expecting UPN instead of email address

### ISSUE THREAD

**Issue by kathleenlgo** [MicrosoftDocs/microsoft-365-docs#9371]
Hi!

May I suggest please that we add a note to clarify that the HR connector is expecting the UPN instead of email address (even if the column name says Email Address)?  In most cases, the UPN is the same as the email address.  However, there are some orgs wherein the user has a different email address from the UPN.  When we tried to import HR data with email address, we get this error message:

![image](https://user-images.githubusercontent.com/22525477/183591415-cec00403-fbf4-4641-aa08-3643ff7ecda8.png)

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b68cfa-058a-8536-fb6a-b54e8fffa626
* Version Independent ID: dbcba365-2858-8cff-4f30-8a8a0068ac71
* Content: [Set up a connector to import HR data - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/import-hr-data?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/import-hr-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/import-hr-data.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by v-tophillips** [comment]
I am not persuaded that we need a separate note for each table when each description column has (UPN) as a descriptor for the email address. I agree it would be more clear if the column name was UPN instead of EmailAddress, but that would require a change to the product.
