### ISSUE TITLE
Missing links on page

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9372]
In the Additional Resources section of the page there are missing links for

- Take training for adoption specialist
- Join the adoption community
- Use the Microsoft 365 adoption tools

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1fd644-5b27-ea28-2844-7a0ee0fa95f9
* Version Independent ID: ee1fd644-5b27-ea28-2844-7a0ee0fa95f9
* Content: [Microsoft 365 Experience insights dashboard - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/experience-insights-dashboard?view=o365-worldwide&branch=pr-en-us-15039)
* Content Source: [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/experience-insights-dashboard.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9382

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
