### ISSUE TITLE
Only available for tenants with 20,000 plus seats

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9373]
This page does not mention that Experience insights is only available for organizations with 20,000 plus seats. This is information provided in the blog post https://techcommunity.microsoft.com/t5/microsoft-365-blog/introducing-preview-of-experience-insights-for-microsoft-365/ba-p/3574383

Update to say

Experience insights is optimized for organizations with higher volumes of data so is only available for organizations with 20,000 plus seats.  Microsoft are working on bringing the experience to smaller organizations in the future

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1fd644-5b27-ea28-2844-7a0ee0fa95f9
* Version Independent ID: ee1fd644-5b27-ea28-2844-7a0ee0fa95f9
* Content: [Microsoft 365 Experience insights dashboard - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/experience-insights-dashboard?view=o365-worldwide&branch=pr-en-us-15039)
* Content Source: [microsoft-365/admin/misc/experience-insights-dashboard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/experience-insights-dashboard.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9381

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
