### ISSUE TITLE
"Add custom questions to your services" does not reflect product

### ISSUE THREAD

**Issue by ab-ny** [MicrosoftDocs/microsoft-365-docs#9374]
Hi, when following the "Add custom questions to your services" step in the documentation, step 4 reads:

Choose the Custom fields section.

There is no custom fields section, however there is a "customised fields" section

This looks slightly different to the documented UI
![image](https://user-images.githubusercontent.com/105717253/183619957-05452787-e1cd-4701-8cc3-e8344e4dca2e.png)

Critically, the functionality to add a custom question is not there. There is no UI element to add a custom question.

Modifying the custom questions does work on the old UI, but is not reflected in the new UI. The custom questions do not show up on the booking page in either the new or the classic UI.

Has this feature been removed from the product? If not, can the documentation please be updated to reflect the state of the product.

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c94c3452-09eb-3ca1-0a9e-e46b3ac6b345
* Version Independent ID: 3f184821-e68d-fcae-a312-f3e3d0b4e97f
* Content: [Add custom and required questions to the booking page](https://docs.microsoft.com/en-us/microsoft-365/bookings/add-questions?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/add-questions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/add-questions.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@ab-ny Thank you for your feedback.

I have tested it in two tenants and I could see the Options say Custom Fields in both new and old Bookings experience

![image](https://user-images.githubusercontent.com/45987684/183721511-f4ed781c-5841-44ed-a6f2-9cd1eef8dcf3.png)

If the wordings are still showing up as Customised fields then there could be an issue or bug with a set of tenants. I'd recommend you to contact Microsoft via the need help section in the admin center so that a support engineer can verify and report it to the Product group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ab-ny Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
