### ISSUE TITLE
ćóntoso.com?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#9389]
Yes that is the spelling used in this page.
> An example impersonation of the domain contoso.com is ćóntoso.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide#exclusive-settings-in-anti-phishing-policies-in-microsoft-defender-for-office-365)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jonwbstr, the text looks OK to me. Isn't ćóntoso.com a sneaky way of impersonating contoso.com?

Or is it an allowed ASCII characters in email addresses thing where the example bad domain should be something like cont0s0.com?

**Comment by jonwbstr** [comment]
Apologies I neglected to read the sentence, that is a perfect example of
phishing.

On any other article it would be a typo 😉. Closing as pebcak
