### ISSUE TITLE
How to enable network protection in Windows Server 2019

### ISSUE THREAD

**Issue by KENJISHIRAKI** [MicrosoftDocs/microsoft-365-docs#9392]
[Enter feedback here]
I ran the command "Set-MpPreference -EnableNetworkProtection Enabled" on Windows Server 2019 to enable network protection.
However, when I accessed the demo site (https://smartscreentestratings2.net ) it was not blocked. all the requirements for real-time protection, cloud-delivered protection, etc. are met.

Network protection also worked on Windows Server 2019 by running the following additional commands
Set-MpPreference -AllowNetworkProtectionOnWinServer 1
Set-MpPreference -AllowNetworkProtectionDownLevel 1
Set-MpPreference -AllowDatagramProcessingOnWinServer 1
Therefore, could you please add that the following command also needs to be executed in Server OS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395141e8-be91-e226-24d7-dc136b8f9c5e
* Version Independent ID: 012beed4-1fdb-4f59-9cc4-53ba5e2c8ea2
* Content: [Use network protection to help prevent connections to bad sites](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection?view=o365-worldwide#requirements-for-network-protection)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@KENJISHIRAKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9419

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @KENJISHIRAKI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
