### ISSUE TITLE
Add consideration for Policy Tips in older versions of Outlook

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/microsoft-365-docs#9393]
Older versions of Outlook are not compatible with all types of Custom SITs - due to their MCE.dll version vs the minimum required version of custom SITs. Any custom SIT, depending on its elements, is not necessarily compatible with any Outlook version (specifically Perpetual 2019 and below). 

We would like a callout to this, either within, or replacing the following lines:

"_Please note that custom sensitive information types are also supported for DLP policy tips in addition to the above out-of-the-box sensitive information types._"

A suggestion replacement may be as such:

"_Please note that **some** custom sensitive information types are also supported for DLP policy tips in addition to the above out-of-the-box sensitive information types. 

**Note: Not all elements of custom sensitive information types are compatible with every version of Office. Entity elements for Custom SITs, such as Functions may cause incompatibility**._"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 720b0a3c-6c92-3f75-1dc7-6059166692c0
* Version Independent ID: 8c2f5c67-ce01-85c4-417a-b43fc062a332
* Content: [Data Loss Prevention policy tips reference - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-tips-reference?view=o365-worldwide#support-matrix-for-dlp-policy-tips-across-microsoft-apps)
* Content Source: [microsoft-365/compliance/dlp-policy-tips-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-policy-tips-reference.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@SeanTGeoghegan Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9420

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SeanTGeoghegan Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
