### ISSUE TITLE
"Web Protection" term is not entirely true....

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/microsoft-365-docs#9394]
[Enter feedback here]
MTD presently contextually defines Web Protection as "Anti-phishing, blocking unsafe network connections, and support for custom indicators" and then refers to the main MDE Web Protection article that has a different definition: "Web protection in Microsoft Defender for Endpoint is a capability made up of Web threat protection, Web content filtering, and Custom indicators. Web protection lets you secure your devices against web threats and helps you regulate unwanted content."

This is confusing and should have a note (like the iOS page does that WCF is not supported at this time).

Source pages:
MTD Defined "Web Protection" https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mtd?view=o365-worldwide#key-capabilities

MDE Defined "Web Protection"
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-protection-overview?view=o365-worldwide

Link to main MDE article defining what Web Protection is from MTD doc page (without explaining or referring to the difference)
https://docs.microsoft.com/en-us/mem/intune/protect/advanced-threat-protection-manage-android

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81ad3b34-c76e-b70a-6b3d-5b29f4408bef
* Version Independent ID: 15f316a5-d0f0-824d-b350-9dccebe784e5
* Content: [Configure Microsoft Defender for Endpoint on Android features](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/android-configure?view=o365-worldwide#configure-web-protection)
* Content Source: [microsoft-365/security/defender-endpoint/android-configure.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/android-configure.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@vboyev-MSFT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9423

Added a statement that WCF is not supported on mobile platforms.

Once the author approves, the changes will be live.

Thanks
Sri
