### ISSUE TITLE
Setting SelfPurchase policy to OnlyTrialsWithoutPaymentMethod not working.

### ISSUE THREAD

**Issue by kurtvanbalen** [MicrosoftDocs/microsoft-365-docs#9395]
When trying to set the policy value for SelfPurchase to OnlyTrialsWithoutPaymentMethod I encounter the following error. It is possible to set the value to either Enabled or Disabled but not to OnlyTrialsWithoutPaymentMethod. Can it be that this functionality was not yet enabled from MS their side?
![image](https://user-images.githubusercontent.com/28528957/183934321-82bbaf3e-d517-41e4-875d-0d8d293d3c30.png)

Thanks in advance!

KR,
Kurt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5082f7ed-ad40-04c1-5c6c-59e67b253257
* Version Independent ID: 3d8b109d-285c-952f-2fa4-9fa244c2a3f9
* Content: [Use AllowSelfServicePurchase for the MSCommerce PowerShell module](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide#view-or-set-the-status-for-allowselfservicepurchase)
* Content Source: [microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@kurtvanbalen Thank you for your feedback. **OnlyTrialsWithoutPaymentMethod** is currently not available and the same has been removed from the document. We will update the document once the parameter is made available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kurtvanbalen Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
