### ISSUE TITLE
Please remove text in Custom email notification for SharePoint and OneDrive 

### ISSUE THREAD

**Issue by teomondaPT** [MicrosoftDocs/microsoft-365-docs#9396]
The custom email notification that we can configure for Sharepoint / Onedrive automatically contains reference to the document link and Sensitive information types included, which makes the email very long and hard to read in some situations.
I would expect, since the docs article shows options/tokens to include when customizing email notifications, that it would not show anything else, but only what we input.
![onedrive dlp email notification](https://user-images.githubusercontent.com/110994143/183942246-69a74949-2466-4850-ad13-9f6eb1d0e547.png)

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505aba8-2455-5390-b34b-6bb0865b14db
* Version Independent ID: 401701a8-86fd-8570-8084-33622f34bb91
* Content: [Send email notifications and show policy tips for DLP policies - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-notifications-and-policy-tips?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/use-notifications-and-policy-tips.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-notifications-and-policy-tips.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@teomondaPT Thank you for your feedback. That makes sense. However, this needs to go to the dev/product team so that they can look at it and make changes. I'd request you to provide this valuable feedback on our Main feedback portal -https://feedbackportal.microsoft.com/ , So that one of our dev team members can respond back to you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@teomondaPT Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
