### ISSUE TITLE
Where are the email settings?

### ISSUE THREAD

**Issue by wdburgdorf** [MicrosoftDocs/microsoft-365-docs#9404]
"there are email settings"

I totally believe that there are settings. But WHERE are they? I cannot find them.
Can you please specify? Maybe add a screenshot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a56d4e-5b63-a2b8-5225-abf9d91aaf90
* Version Independent ID: 467e8269-ef0c-ee69-0c3b-74221ab06e39
* Content: [User email settings - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/email/office-365-user-email-settings?view=o365-worldwide)
* Content Source: [microsoft-365/admin/email/office-365-user-email-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/office-365-user-email-settings.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@wdburgdorf Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9421

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by wdburgdorf** [comment]
Wow. That's incredible. In more than 30 years of using many different
Microsoft products with many different issues, I have never had such a
quick and professional response to any question or request. Mostly it has
been either nothing or useless. Now you guys actually answered and fixed
something. Wonderful.
Thank you!

Cheers,
Ralf

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @wdburgdorf Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
