### ISSUE TITLE
Sentinel is GA

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#941]
Sentinel is not free anymore as it is not in preview, but GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 734ff6a2-959a-b862-a691-54410031cb71
* Version Independent ID: 04f70373-d24c-5c48-5c13-1dfa5e2ddd4d
* Content: [Microsoft 365 Security for Business Decision Makers (BDMs)](https://docs.microsoft.com/en-us/microsoft-365/security/microsoft-365-security-for-bdm?MC=WinServer#feedback)
* Content Source: [microsoft-365/security/Microsoft-365-security-for-bdm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/Microsoft-365-security-for-bdm.md)
* Service: **o365-seccomp**
* GitHub Login: @BrendaCarter
* Microsoft Alias: **bcarter**

**Comment by mypil** [comment]
@andrePKI - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/d3b15fde8188f5353b3b5c46448ab3bf534654bc. 


Thank you for your contribution to make the docs better! Much appreciated!
