### ISSUE TITLE
Need guidance on managing MDAV in Azure - Azure Antimalware is not MDAV

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/microsoft-365-docs#9410]
[Enter feedback here]
There is a lack of clarity and information for managing MDAV on Azure VM's as well as on ARC connected servers that are not managed via MEM/MECM or GPO.

Azure Antimalware - as I understand it is related to the IAAS Antimalware extension (https://docs.microsoft.com/en-us/azure/security/fundamentals/antimalware) and is not equivalent protection that the MDE Unified Agent provides.  On top of this, the MS Antimalware extension is only supported on legacy Windows Server OS's.

This needs to be clarified as this doc can be construed to recommend using the legacy antimalware extension, and does not address Server 2019 and above, nor a unified way to apply and enforce MDAV policies across platforms (as there may be Linux in the mix).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af205543-b539-a7e8-a66c-f9365241fec9
* Version Independent ID: b9d4b071-f501-51a8-8565-859df13b7fa7
* Content: [Deploy, manage, and report on Microsoft Defender Antivirus](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/deploy-manage-report-microsoft-defender-antivirus?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/deploy-manage-report-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/deploy-manage-report-microsoft-defender-antivirus.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
Hello @vboyev-MSFT and @yogkumgit. This article has been updated and the changes should be live within the hour. THANK YOU so much for your feedback, @vboyev-MSFT. I appreciate it very much.
