### ISSUE TITLE
What do you mean Forwarded messages may not be encrypted

### ISSUE THREAD

**Issue by slylabs13** [MicrosoftDocs/microsoft-365-docs#9412]
I think the statement that if a message is forwarded it isn't necessarily encrypted is misleading. ANY message sent via a TLS encrypted channel is encrypted, whether forwarded or not. I think you need to clarify what that means. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f032f4f-c4b0-9133-aaab-a44f28910472
* Version Independent ID: ffc3850e-1378-850b-5cd6-bde82db00f25
* Content: [How Exchange Online uses TLS to secure email connections - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/exchange-online-uses-tls-to-secure-email-connections.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by msbemba** [comment]
@slylabs13 Thank you for your feedback. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9422

The statement is now changed to - If you forward a message that was sent through a TLS-encrypted connection to a recipient organization that doesn't support TLS encryption, that message isn't necessarily encrypted. TLS doesn't encrypt the message, just the connection.

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by slylabs13** [comment]
Thank you very much. The issue came up in conversation with a well known IT support group who believed that TLS only encrypted the credentials and NOT the message. I was gobsmacked, and had to look it up to make my point that wasn't true. 

Bob S

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @slylabs13 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
