### ISSUE TITLE
Different rate limits across MS documentation

### ISSUE THREAD

**Issue by katlim-br** [MicrosoftDocs/microsoft-365-docs#9425]
Different rate limits:
https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-limits?view=o365-worldwide
vs
https://docs.microsoft.com/en-us/microsoft-365/security/defender/api-advanced-hunting?view=o365-worldwide
vs
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-api?view=o365-worldwide

Can you please change all of these pages (or make them refer to a single location) so we are sure what is the real limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53a61a50-f7f2-f09a-a008-759c3afba97b
* Version Independent ID: 872c0e23-c626-3e22-efea-d4ef4ad7f32b
* Content: [Advanced Hunting API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/run-advanced-query-api?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/run-advanced-query-api.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/run-advanced-query-api.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@katlim-br Thank you for your feedback. I have corrected the docs to reflect that the result set can have a maximum of 10,000 rows. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9478

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @katlim-br  Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
