### ISSUE TITLE
Reuqest a bit more info at the end of the page

### ISSUE THREAD

**Issue by thomasjsweet** [MicrosoftDocs/microsoft-365-docs#9426]
[Enter feedback here]
Hello,
I have looked at this for a couple of hours and there are a few things to consider adding.  I would add them if I knew the answer.  My questions start with a // TJS.  I realize a lot of hard work went into this document.

**Invite users
Guest sharing settings are now configured, so you can start adding internal users and guests to your site. Site access is controlled through the associated Microsoft 365 Group, so we'll be adding users there.

Guests can't be added from the site. You need to add them using Outlook on the web. Therefore, as a prerequisite to add and invite guests to a group, click the URL of the site in the URL column to navigate to the site-specific page.**
// TJS I really could not find that link.  I clicked on the document but I am missing something.

From this page, click the App launcher icon and select Outlook. This is the screen from which you can invite guests into a group, for which procedure is described below.

To invite guests to a group

Under Groups, click the group to which you want to invite guests.
Open the group contact card, click Members link in the upper right (the link which denotes the member count).
click Add members.
Type the email addresses of the guests that you want to invite, and then click Add.
Click Close. Note that you need to click Close only if you are not the owner of the group and as a result, you are not allowed to add the guest into the group. In such cases, the request to add the guest into the group is transferred to the group owner for approval.

// TJS - I found a way to add the user to the group through the Outlook web app. The one time password was sent, etc but the user had no access. I went round and round but figured out that when just adding the user to the "Extranet" site, the link that the user tries to log in goes to 
https://contoso.sharepoint.com/_forms/default.aspx.  If I later type in https://contoso.sharepoint.com/sites/extranet, then the guest has access to the site.  I am not sharing the main site, just the extranet.
// TJS - what I was hoping for was to send a link to a specific document. A screenshot or two might help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb311ed9-a649-8f67-51ea-3789ad914b00
* Version Independent ID: 165a9d7e-25e6-d5e5-d960-acaa675e4400
* Content: [Collaborate with guests in a site](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-in-site?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-in-site.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-in-site.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@yogkumgit fyi I submitted an update to link externally for how to add guests to the group rather than covering it here.

@thomasjsweet  you can find info on how to share a specific document in [Share SharePoint files or folders](https://support.microsoft.com/office/1fe37332-0f9a-4719-970e-d2578da4941c).

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Thank you very much for sharing this information. @thomasjsweet Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
