### ISSUE TITLE
Report incorrect link

### ISSUE THREAD

**Issue by rturner2** [MicrosoftDocs/microsoft-365-docs#9432]
How does a company or person report an incorrect link being flagged as malicious?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8112b7a9-8f21-18b3-03da-f8c02b05f239
* Version Independent ID: a441f1d1-5844-ecb9-ba44-95b94714e4e8
* Content: [Complete Safe Links overview for Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/safe-links?redirectSourcePath=%252fen-us%252farticle%252fSafe-Links-in-Office-365-dd6a1fef-ec4a-4cf4-a25a-bb591c5811e3&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-links.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-links.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rturner2, see:

<https://docs.microsoft.com/microsoft-365/security/office-365-security/report-junk-email-messages-to-microsoft>

**Comment by yogkumgit** [comment]
@rturner2 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
