### ISSUE TITLE
Digital Telephony

### ISSUE THREAD

**Issue by Chephic** [MicrosoftDocs/microsoft-365-docs#9433]
Building the Digital Twin of Our Environment.. !

**Comment by denisebmsft** [comment]
Hello @Chephic. Can you please tell us to which article your feedback applies?

**Comment by yogkumgit** [comment]
@Chephic We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Chephic** [comment]
Hi 
Apologies for the delay in response, I am new this space and still figuring out basic things
