### ISSUE TITLE
Incorrect - GPO does not work for onboarding servers in Defender

### ISSUE THREAD

**Issue by Degies** [MicrosoftDocs/microsoft-365-docs#9434]
[This page needs testing. The recommended GPO config for GPO running a scheduled task to execute the CMD onboarding file does not work, You can see the task ran on a VM, yet the machine does not onboard ? Perhaps some additional steps is needed but following the documentation provided step by step has not enrolled a single Defender agent in 24 hours. it certainly needs something in the config file to associate the onboarding with the tenant like we used to do with the MMA automated script. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523651c3-a318-2369-6892-d13e04991596
* Version Independent ID: 624c5e05-f87d-1bd4-bc87-bd55dcac1d86
* Content: [Onboard Windows devices to Microsoft Defender for Endpoint via Group Policy](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-endpoints-gp?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/security/defender-endpoint/configure-endpoints-gp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-endpoints-gp.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@Degies Thank you for your feedback. We will test and update the document if need be.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Degies Thank you for your feedback. The steps are the ones that we have received from the product group. This sounds more like a technical issue or a bug. I'd recommend you contact Microsoft support via the need help section so that a support engineer can fix or raise a bug with the product team.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Degies Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
