### ISSUE TITLE
Enable OME logs - parameter not found

### ISSUE THREAD

**Issue by ConfigConfused** [MicrosoftDocs/microsoft-365-docs#9438]
(https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-message-access-logs?view=o365-worldwide#enabling-message-access-audit-logs-in-powershell)

Section for enabling OME logging references command that does not work as ecpected.

Set-IrmConfiguration -EnablePortalTrackingLogs $true
Set-IRMConfiguration: A parameter cannot be found that matches parameter name 'EnablePortalTrackingLogs'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6e8b911-7fb5-372d-a4a9-36be28e0f076
* Version Independent ID: d6e8b911-7fb5-372d-a4a9-36be28e0f076
* Content: [Encrypted message portal activity log - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-message-access-logs?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/ome-message-access-logs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/ome-message-access-logs.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@ConfigConfused Thank you for your feedback. I was able to execute the cmdlet on the exchange online v2 module. I have made changes to reflect that via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9479

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ConfigConfused Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by ABCo27** [comment]
Is it possible this commandlet got dropped from exo v3 ? I'm getting 
Set-IrmConfiguration -EnablePortalTrackingLogs $true
Set-IRMConfiguration: A parameter cannot be found that matches parameter name 'EnablePortalTrackingLogs'.

**Comment by amaiman** [comment]
> Is it possible this commandlet got dropped from exo v3 ? 

That's what it looks like to me.  I opened https://github.com/MicrosoftDocs/office-docs-powershell/issues/11057 so hopefully they'll get the right team to fix this.

**Comment by amaiman** [comment]
They closed the new issue that I opened.  Apparently, this flag requires E5 licensing, so if you don't have the most expensive plan it won't work.
