### ISSUE TITLE
Support for RDS

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/microsoft-365-docs#944]
The Office version support apply on user installations only or also to RDS scenarios of Office installs? Like Shared Computer Activation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0836a95-d3b7-3c43-d56b-5fb4ceeb4765
* Version Independent ID: 8a0d366b-5ff7-22de-7aba-6adbe0ea94ea
* Content: [Sensitivity labels in Office apps - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps)
* Content Source: [microsoft-365/compliance/sensitivity-labels-office-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-office-apps.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by VLG17** [comment]
@Kazzan You need the AIP Client on the RDS Server for it to work:

https://docs.microsoft.com/en-us/azure/information-protection/requirements

> The Azure Information Protection clients are supported for Remote Desktop Services. If you delete user profiles when you use the Azure Information Protection clients with Remote Desktop Services, do not delete the %Appdata%\Microsoft\Protect folder.

**Comment by Kazzan** [comment]
Hi @VLG17, so the only MIP (AIP) Unified Client is supported on RDS and not the native "Sensitivity" button labeling in Office on RDS? Correct? Thanks for clarification.

**Comment by VLG17** [comment]
Correct. You need the client, either AIP or the new Unified Labeling one. As far as i know, support for the native "Sensitivity" button labeling will come in the future.

**Comment by cabailey** [comment]
@Kazzan  I checked up on this with the engineering team and was told that built-in sensitivity labels are supported with Remote Desktop Services.  So you don't need the AIP client to support this Office deployment.  Now added to the client comparison table: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-labeling-clients-for-windows-computers
