### ISSUE TITLE
How do I delete more than 10 emails using powershell in O365?

### ISSUE THREAD

**Issue by usnmt23** [MicrosoftDocs/microsoft-365-docs#9440]
The documentation states "A maximum of 10 items per mailbox can be removed at one time. Because the capability to search for and remove messages is intended to be an incident-response tool, this limit helps ensure that messages are quickly removed from mailboxes. This feature isn't intended to clean up user mailboxes."

I recently had an incident response case where some users had more than 10 items I needed to delete in their mailbox and I could not do it because of this limit. Running it again did not do the trick so does anyone have any advice?

https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide

**Comment by msbemba** [comment]
@usnmt23 Thank you for your feedback. Currently, the feature and the cmdlet are set to remove only 10 emails per mailbox (Max). You can reach out to Support via the need help section in the admin center and the support engineer will be able to advise if there is an alternate way to do it from the backend. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @usnmt23 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
