### ISSUE TITLE
Add information on default sensitivity label for Document Library

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9441]
In the section SharePoint settings add a new sub section called Configure a default sensitivity label for a SharePoint document library

When SharePoint is [enabled for sensitivity labels](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide), you can configure a default label for document libraries. Then, any new files uploaded to that library, or existing files edited in the library will have that label applied if they don't already have a sensitivity label, or they have a sensitivity label but with [lower priority](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide#label-priority-order-matters).

The Document Library called "Documents" is created as part of the Team provisioning process. This is where the channel files are stored by default. Add the sensitivity label created to this Document Library "Documents" any other Document Libraries created under this Team.

This will ensure that all new files added to the site will inherit the labels 
- In SharePoint, navigate to the document library > Settings > Library settings.
- From the Library settings flyout pane, select Default sensitivity labels, and then select a label that you created

See page for more details
https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-default-label?view=o365-worldwide
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5def8560-b22f-769a-e7e9-a88bfcc01d99
* Version Independent ID: abb6e6ba-d74d-7d13-3674-6f47ba2062d2
* Content: [Configure teams with protection for highly sensitive data](https://docs.microsoft.com/en-us/microsoft-365/solutions/configure-teams-highly-sensitive-protection?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/configure-teams-highly-sensitive-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/configure-teams-highly-sensitive-protection.md)
* Service: **o365-seccomp**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@nikki-c thanks for calling this out. I agree this is a good article in which to include this. I put it on my to-do list, but we'll likely wait until the feature is generally available and the licensing requirements have been announced.

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Thank you very much for sharing this. @nikki-c Hope this comment is helpful for you. We proceed here to close this issue. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
