### ISSUE TITLE
Several issues in the documentation

### ISSUE THREAD

**Issue by rfellmann** [MicrosoftDocs/microsoft-365-docs#9442]
Issue 1: "Download Onboarding Script and the unified solution from [Microsoft 365 Defender settings page](https://sip.security.microsoft.com/preferences2/onboarding)."
We need the WindowsDefenderATPOnboardingScript.cmd file, not the .onboarding file. The .onboarding file is used to import by SCCM and create the onboarding policy. The .cmd file can be onboarded when selecting the Group Policy option in the dropdown menu. See Issue 4 where you actually refer to the correct file. 

Issue 2: "Save all three files in a shared folder used by MECM as a Software Source."
Screenshot is wrong, analog issue 1. 

Issue 3: "On this step, copy the UNC path that your content is located. Example: \\Cm1\h$\SOFTWARE_SOURCE\UAmigrate."
Screenshot is wrong again (.onboarding file shown instead of WindowsDefenderATPOnboardingScript.cmd

Issue 4: Not really an issue but check "Additionally, set the following as the installation program:"
There the correct onboarding script is referred to (.cmd file, not the .onboarding file)

Issue 5: The detection method will be based on the registry key shown below. HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Sense\ImagePath

-> Imagepath should be in the 'Value' field. Data type: String

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db7a8efc-83e0-d8cf-7385-c323d3793327
* Version Independent ID: db7a8efc-83e0-d8cf-7385-c323d3793327
* Content: [Migrating servers from Microsoft Monitoring Agent to the unified solution](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/application-deployment-via-mecm?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/application-deployment-via-mecm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/application-deployment-via-mecm.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @alekyaj
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@alekyaj Please help us in resolving this issue. Thanks

**Comment by alekyaj** [comment]
> @alekyaj Please help us in resolving this issue. Thanks

Hi @yogkumgit, 

I have fixed the issues and updated the doc in the PR mentioned above. I am awaiting review to confirm on the updates. Thanks

**Comment by yogkumgit** [comment]
@alekyaj When changes are reflected, please add a comment here for me to proceed to close this issue. Thanks

**Comment by alekyaj** [comment]
> @alekyaj When changes are reflected, please add a comment here for me to proceed to close this issue. Thanks

Hi @yogkumgit, 
The updates have gone live. Kindly review and close this issue as needed. Thanks

**Comment by yogkumgit** [comment]
@rfellmann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
