### ISSUE TITLE
Report on Windows Defender Features, Windows Defender, Windows Defender antivirus installed

### ISSUE THREAD

**Issue by felymich** [MicrosoftDocs/microsoft-365-docs#9443]
Hello, 

I need to report on all machines having Windows Defender Features, Windows Defender, Windows Defender antivirus installed. I found report on the scan done by these products but not a report/query about the installation, if it is enabled or disabled...

Thanks,
Dom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bc22dbc-1c50-f45c-be48-887339dbcabc
* Version Independent ID: c4533eec-6b64-17b4-c5cd-b3d123f6169f
* Content: [Provide feedback on Microsoft 365 Defender](https://docs.microsoft.com/en-us/microsoft-365/security/defender/feedback?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/feedback.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/feedback.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@felymich Thank you for your feedback. You are correct, I could not find a report about installation. I'd recommend you provide this feedback on our main feedback portal - https://feedbackportal.microsoft.com/ so that a product or dev engineer will be able to provide more information on when this will be available.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@felymich Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
