### ISSUE TITLE
Why was notify.windows.com removed from the spreadsheet?

### ISSUE THREAD

**Issue by KENJISHIRAKI** [MicrosoftDocs/microsoft-365-docs#9448]
[Enter feedback here]
Why has "*.notify.windows.com" been removed from this Docs spreadsheet (mde-urls-commercial.xlsx)?
The "Change Log" sheet shows that it was removed on January 25, 2022.
However, the Live Response Docs states that notify.windows.com should be allowed. In other words, there appears to be a discrepancy between the spreadsheet and the Docs.
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-live-response?view=o365-worldwide#slow-live-response-sessions-or-delays-during-initial-connections
>1. notify.windows.com is not blocked in your environment. For more information, see, Configure device proxy and Internet connectivity settings.

-Question.
When using Live Response, do we need to allow "*.notify.windows.com" in our network?
Why was this URL removed from the spreadsheet?

The Docs and Spreadsheet are inconsistent and if there is a mistake in either, I would like to see it corrected.

Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide#enable-access-to-microsoft-defender-for-endpoint-service-urls-in-the-proxy-server)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@KENJISHIRAKI Thank you for your feedback. notify.windows.com was removed from the excel file as it was no longer needed.

We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9477

Once the author approves the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @KENJISHIRAKI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
