### ISSUE TITLE
Remove recommended settings paragraph

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/microsoft-365-docs#945]
Could we please remove "Recommended settings" part since we have published new document: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a4f6b67-85ac-ef6e-5260-6ae160cfd6d8
* Version Independent ID: b4ae42b8-dd36-9f18-092b-af0b55b3c0fb
* Content: [Best practices for configuring EOP and Office 365 ATP - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/best-practices-for-configuring-eop)
* Content Source: [microsoft-365/security/office-365-security/best-practices-for-configuring-eop.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/best-practices-for-configuring-eop.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by VLG17** [comment]
@pawp81 The [mentioned article](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/best-practices-for-configuring-eop) already points to the [newer article](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp).

![image](https://user-images.githubusercontent.com/41186174/71725621-58727400-2e3d-11ea-8325-81debac0a36d.png)

**Comment by mypil** [comment]
@pawp81 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
