### ISSUE TITLE
How does the IT administrator grant access to Bookings to me?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/microsoft-365-docs#9450]
The page states the following:

> If your IT administrator has granted you access to Bookings ...

Can you add a link to instructions for the IT Administrator to grant access to bookings?  I'm trying to help my IT administrator figure out how to give me access to bookings and I was hoping to share this page with them, but it doesn't have the information that the IT Administrator needs.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf3a8dac-35e3-9b2a-0a84-0d4191688489
* Version Independent ID: 34803248-9bfc-4f47-285a-c12fce1dc71c
* Content: [Get access to Microsoft Bookings](https://docs.microsoft.com/en-us/microsoft-365/bookings/get-access?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/get-access.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/get-access.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @MarkIannucci Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
