### ISSUE TITLE
Email spelled wrong in doc.

### ISSUE THREAD

**Issue by kzbierski** [MicrosoftDocs/microsoft-365-docs#9451]
Doc contains: "emial"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294aff59-300b-df83-8921-43912cb9f33b
* Version Independent ID: 80168797-3cd3-2cd6-ee49-535cb5e4c14b
* Content: [What's new in Microsoft Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/whats-new-in-defender-for-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@kzbierski Thank you for your feedback. I have reviewed the document and looks like the information is up to date and no changes are needed.

In case you have issues with a different document, please do let us know.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kzbierski Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
