### ISSUE TITLE
feedback on threat hunt queries - community once

### ISSUE THREAD

**Issue by hitem** [MicrosoftDocs/microsoft-365-docs#9452]
Would be great to get some pointers on how one goes about updating 'Community Queries' in the Hunt-portal. Or if this could be automated somehow? (new campaigns etc).
Thank you very much

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bf88b1-0da2-59ec-75c2-d09d715110b6
* Version Independent ID: 0d46b6a8-606f-af02-bea8-155c7a0369d0
* Content: [Use shared queries in Microsoft 365 Defender advanced hunting](https://docs.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-shared-queries?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-shared-queries.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-shared-queries.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
As per [here](https://docs.microsoft.com/microsoft-365/security/defender/advanced-hunting-shared-queries#save-modify-and-share-a-query), shared queries can be shared across the users in an organization, but [community queries](https://docs.microsoft.com/microsoft-365/security/defender/advanced-hunting-shared-queries#access-community-queries-in-the-github-repo) are vetted by Microsoft researchers. I can ask if there is a process for that, but is this the repo you meant?

**Comment by yogkumgit** [comment]
@hitem Please check the comment and reply.

**Comment by yogkumgit** [comment]
@hitem Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
