### ISSUE TITLE
Support for oAuth automating event based retention?

### ISSUE THREAD

**Issue by jhedtke** [MicrosoftDocs/microsoft-365-docs#9454]
Automating event based retention is a great concept. It would be nice to include how to accomplish this with oAuth instead of Basic Auth to help tighten security around this process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad33cc1-dc5f-d9f9-ee8e-b103839945ef
* Version Independent ID: 1bc3101d-afe8-2056-3cda-6a86a209c460
* Content: [Start retention when an event occurs - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/event-driven-retention?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/event-driven-retention.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/event-driven-retention.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@jhedtke  Yes, the reliance on basic auth is one of the reasons why we recommend you use Microsoft Graph and the REST APIs will soon be deprecated.

**Comment by jhedtke** [comment]
Thanks for the quick update! I completely missed the note mentioning the records management graph API
