### ISSUE TITLE
Linked ADMX files dont work.

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/microsoft-365-docs#9458]
Hi the ADMX files required to deploy this via GPO that are linked in this article (https://github.com/microsoft/mdatp-devicecontrol/tree/main/Removable%20Storage%20Access%20Control%20Samples) do not work.

It's noted on the readme for the repo that people have had issues with them, and the provided instructions dont work.

Other user are also having issues

https://github.com/microsoft/mdatp-devicecontrol/issues/8

This is an important feature I am using with a large client (15K+ devices) and where I am replacing Symantec Endpoint Protection with MDE but when things like this dont work, it makes the transition much harder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7a5c17-1358-990b-968d-432a3aab2e17
* Version Independent ID: 1b4d4eff-3e22-47d7-4054-6cc9ed0217d0
* Content: [Microsoft Defender for Endpoint Device Control Removable Storage Access Control, removable storage media](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-control-removable-storage-access-control.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@pjrcdf Thank you for your feedback. The information in Read me is what was provided to us by the product group. In case that doesn't fix the issue. I'd recommend you to contact Microsoft support via the need help section on the admin center so that a support engineer can help you fix or escalate this as a bug to the product group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @pjrcdf Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
