### ISSUE TITLE
/var/log/microsoft_mdatp_*.log should be /var/log/microsoft/mdatp/*.log

### ISSUE THREAD

**Issue by YongRhee-MSFT** [MicrosoftDocs/microsoft-365-docs#9461]
RE: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-privacy?view=o365-worldwide

This:
Product installation and uninstallation logs under /var/log/microsoft_mdatp_*.log

Should be:
Product installation and uninstallation logs under /var/log/microsoft/mdatp/*.log

Thx,
Yong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6e7ec33-6824-41e4-7a9c-56a46598955f
* Version Independent ID: 643d0a7f-d84b-10e7-455d-d79b4da50dba
* Content: [Privacy for Microsoft Defender for Endpoint on Linux](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-privacy?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-privacy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-privacy.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @YongRhee-MSFT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
