### ISSUE TITLE
Site Owners updating labels on SPO sites

### ISSUE THREAD

**Issue by MichaelRyan87** [MicrosoftDocs/microsoft-365-docs#9462]
Hi All,

A business we are working with has demonstrated that site owners can change the sensitivity label for SharePoint Online sites they own, without needing to utilise the SPO admin centre.

A tech community post was raised last year, stating it would be great to lock this down in teams. In the meantime we will look at raising alerts from the audit log when a change is detected which alters sharing permissions. 

I can see this is already documented for teams (https://docs.microsoft.com/en-us/microsoftteams/sensitivity-labels#set-the-privacy-level-for-teams) but it would be great to be clear in this document that owners can do so as it may be considered a risk. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Microsoft 365 Groups, and SharePoint sites - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@MichaelRyan87  Thanks for flagging this - I'll look into adding a note around this so people aren't surprised. However, we do currently link to that article.
