### ISSUE TITLE
Command for checking update channel is incorrect

### ISSUE THREAD

**Issue by timnottom** [MicrosoftDocs/microsoft-365-docs#9463]
Hi!
In the explanation for Prerequisites the command to check the release ring /update channel is shown as: `mdatp --health releaseRing` but it should be: `mdatp health --field release_ring`. The correct way of using the command is used some steps below under Manual deployment"

Hope this helps!

Tim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 415606ab-27e9-e125-d868-1e4636771d36
* Version Independent ID: 415606ab-27e9-e125-d868-1e4636771d36
* Content: [Use network protection to help prevent macOS connections to bad sites](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection-macos?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection-macos.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection-macos.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@timnottom Thank you for your feedback. I have tested and the correct command mdatp health --field release_ring is updated in the document now. 

Hope this helps!

Thanks
Sri

**Comment by timnottom** [comment]
Thanks Sri!
