### ISSUE TITLE
Adding Guests to a group should not require Outlook

### ISSUE THREAD

**Issue by MStormW** [MicrosoftDocs/microsoft-365-docs#9464]
Collaborating is becoming easier nowadays with all the great integration. Except when it comes to (existing) guest accounts. Why on earth is it required to invite guests via Outlook, instead of just adding them as a member in Sharepoint directly? This is totally unintuitive and complicated. Please tell me this is going to change soon and we will be able to add guests as members of site, on the site itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb311ed9-a649-8f67-51ea-3789ad914b00
* Version Independent ID: 165a9d7e-25e6-d5e5-d960-acaa675e4400
* Content: [Collaborate with guests in a site](https://docs.microsoft.com/en-us/microsoft-365/solutions/collaborate-in-site?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-in-site.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-in-site.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MStormW Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
