### ISSUE TITLE
Explain "Is this a test deployment" in details

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/microsoft-365-docs#9465]
What exactly does "Is this a test deployment" mean?

> Info: ‎Filter apps based on whether they were deployed as a test to a limited set of users or deployed to the entire organization.‎

Does this random select some users but not all if i choose "Entrie orgnaization"?
What does this mean if i select specific users and choose 1-2 Users?
What does this mean if i select specific groups with about 100-200 User?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7272ae3e-5901-94b5-d6b3-a3c0202c11fb
* Version Independent ID: a0e582e8-5d40-9fcf-6b98-bc247c082067
* Content: [Test and deploy Microsoft 365 Apps by partners in the Integrated apps portal - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps?view=o365-worldwide&viewFallbackFrom=o365-worldwide%C2%A0)
* Content Source: [microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@weyCC81 Thank you for your feedback. 

"Is this test deployment" is an option used to filter out apps on the integrated apps page based on whether the admin is testing with a limited set(pilot)  of users 

![image](https://user-images.githubusercontent.com/45987684/186360452-f4241c8d-618f-496a-808f-1a18d3f38ce1.png)


Does this random select some users but not all if I choose "Entrie organization"? No, it selects all users
What does this mean if i select specific users and choose 1-2 Users? It deploys only to those 1-2 users.
What does this mean if i select specific groups with about 100-200 User? It deploys to those 100-200 users who are part of that group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@weyCC81 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9537

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The document has been updated and the issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @weyCC81 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by hapklaar** [comment]
@msbemba I would also specify this setting is 'administrative only and has no techinal impact' in the flyout on the page this setting is made. At the moment it show below text and is not clear what it exactly does:

![image](https://github.com/MicrosoftDocs/microsoft-365-docs/assets/7703320/f0ddcd8d-c671-4ced-95fb-ddfe9621f4eb)

**Comment by Kofl** [comment]
+1
the context with the pop-up is not clear, you need to state that its admin only / a tag
