### ISSUE TITLE
Defender for Endpoint Server license info box

### ISSUE THREAD

**Issue by rfellmann** [MicrosoftDocs/microsoft-365-docs#9467]
Please place the license information box more prominent on this page. It looks like the license requirement only applies to Windows Server Semi-Annual Enterprise Channel and Windows Server 2019. 

There should be a separate Licensing section on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Version Independent ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Content: [Defender for Endpoint onboarding Windows Server](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-server?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-server.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@rfellmann Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9501

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by rfellmann** [comment]
Looks like this has not been published. Please check, the 'license requirement' paragraph is not visible on the published site.
