### ISSUE TITLE
Prerelease product notice

### ISSUE THREAD

**Issue by SoccerCore11** [MicrosoftDocs/microsoft-365-docs#9469]
The first content on this page references prerelease software but is not specific as to what that prerelease software is out of the entire document. This is throwing off customers and needs to be removed if inaccurate, or connected closer to the specific section that it relates to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a152af-6336-d498-60e5-1550bf457196
* Version Independent ID: c18e61ad-b9be-9a31-67a8-461705f3fdbf
* Content: [Server migration scenarios for the new version of Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/server-migration?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/server-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/server-migration.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@SoccerCore11 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9503

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @SoccerCore11 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
