### ISSUE TITLE
Safe and Blocked Lists

### ISSUE THREAD

**Issue by awsceris** [MicrosoftDocs/microsoft-365-docs#947]
We need a way to grant end-users the ability to add messages sent to them to the safe or blocked sender lists. It looks like users used to be able to do that until October 21 or so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 417169b2-983d-314d-94fe-32cec2f5fc40
* Version Independent ID: 620070c2-6311-a1fe-890d-a447a0994beb
* Content: [Safe sender and blocked sender lists in Exchange Online - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-sender-and-blocked-sender-lists-faq#feedback)
* Content Source: [microsoft-365/security/office-365-security/safe-sender-and-blocked-sender-lists-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-sender-and-blocked-sender-lists-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@awsceris - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get this information you are discovering back into the docs.
