### ISSUE TITLE
No "Microsoft Defender for Endpoint" app in iOS Store. Only "Microsoft Defender" app

### ISSUE THREAD

**Issue by zimage** [MicrosoftDocs/microsoft-365-docs#9470]
When I search the iOS App Store for the "Microsoft Defender for Endpoint" app, there is none. There's only "Microsoft Defender". Are they the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [App-based deployment for Microsoft Defender for Endpoint on iOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide#deployment-steps)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@zimage Thank you for your feedback. You are right, I was not able to find the Microsoft defender for endpoint app as well. Looks like the description for Microsoft defender talks about Microsoft defender for endpoint. So I have updated the document to reflect the same. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9505

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @zimage Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
