### ISSUE TITLE
Mail Transport Rule to Reject DMARC Failures

### ISSUE THREAD

**Issue by dataCollegechurch** [MicrosoftDocs/microsoft-365-docs#9471]
I think it would be helpful to add this note in this section "How Microsoft 365 handles inbound email that fails DMARC"
* Admins create an Exchange mail flow rule (also known as a transport rule) for all users reject emails that fail your organizations DMARC Policy. (Example policy below)

![image](https://user-images.githubusercontent.com/54962439/185714172-27109399-3247-4109-895a-73108e4e83a2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email, setup steps - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide#how-microsoft-365-handles-inbound-email-that-fails-dmarc)
* Content Source: [microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@dataCollegechurch Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9504

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by DMoenks** [comment]
From my point of view, both the initial suggestion and the proposed change would end up in being misleading. The list that would be updated is described as follows in the article, by the very last sentence of the previous section:

**If desired, users can still get these messages in their inbox through these methods...**

Adding an example to that list on how to block emails that didn't pass DMARC doesn't seem to match the list's intention.

**Comment by dataCollegechurch** [comment]
perhaps there could be add a new section/list that describes how admins can prevent dmarc fails from reaching the users inbox.

**Comment by yogkumgit** [comment]
@msbemba Please comment

**Comment by msbemba** [comment]
@DMoenks and @dataCollegechurch Thank you for your input. I'm waiting for the author to review the changes and if she thinks a new section is needed, I'll add it to the document. 

Thanks
Sri

**Comment by chrisda** [comment]
Updated #22279.

Closing
