### ISSUE TITLE
Cancel Teams subscription from my account

### ISSUE THREAD

**Issue by Yodler** [MicrosoftDocs/microsoft-365-docs#9472]
The cancel subscription leads me to an account that has no access to make any changes to the subscription.

How is that possible?  It is my account.

Please cancel the teams subscription from my accounts.  I will not pay for something I don't use.

Thank you

Roger Suhr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a91e3ae5-842c-fb3d-8c27-d8001122aee8
* Version Independent ID: ddccec72-7088-4207-60cb-986a35becb67
* Content: [Cancel your business subscription](https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/subscriptions/cancel-your-subscription.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/cancel-your-subscription.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@Yodler Thank you for your feedback. Unfortunately, we do not have access to cancel accounts. I'd suggest you contact Microsoft support via the need help section on the admin center so that an engineer can help you cancel the account.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Yodler Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
