### ISSUE TITLE
Priority of Policies

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/microsoft-365-docs#948]
Somewhere should be stated how the priority of policies is created. If it is the same as in Transport Rules, so the higher (0) apply first and others are also evaluated (1, 2, 3, ...) or they are just processes in order and the higher number win.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1541da6f-af9a-05d5-fa34-b1a5df61424f
* Version Independent ID: 88e111ed-67f7-41bc-d823-863ee7ea2a2e
* Content: [Set up Office 365 ATP Safe Links policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies)
* Content Source: [microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-atp-safe-links-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by VLG17** [comment]
@Kazzan higher priority policies will get applied first. I will create a PR and add a note with this info, that's for the heads-up.

**Comment by Kazzan** [comment]
Thanks @VLG17, also please note there if only first (higher priority) apply or processing continue and eventually all policies can be applied.

Like example. Policy Priority 0 - Dynamic Delivery Safe Links Scan for all members of contoso.com, Policy Priority 1 - Disable Safe Links for user@contoso.com. Which policy will get apply to user@contoso.com? Should user@contoso.com get excepted from Policy with Priority 0 or only Priority 1 will apply for him? There is no button "Stop processing more rules" like in Transport Rules, so this can lead to such questions.

Beside that the "Down" Button does not work now in EAC, you can only move Policy "Up".

**Comment by VLG17** [comment]
@Kazzan If a user has 2 policies applied to him, **only** the policy with higher priority will get applied. In your example, for user@contoso.com only the "Priority 1 - Disable Safe Links for user@contoso.com" will get applied to him.

For the button issue, i recommend providing this feedback via [UserVoice](https://office365.uservoice.com/forums/273493-office-365-admin) - that's the best way of getting Product Group attention and having this fixed.

**Comment by Kazzan** [comment]
@VLG17. Really? Because Priority 0 on other things really mean higher Priority from 1.

For example Antispam priority explain: "You can change the order in which your custom policies run by changing the priority of each custom policy; however, only the highest priority (i.e. number closest to 0) policy will apply if multiple policies meet the criteria set."

In Transport Rules docs explain: "Indicates the order that the rules are applied to messages. The default priority is based on when the rule is created (older rules have a higher priority than newer rules, and higher priority rules are processed before lower priority rules)."

Just asking.

**Comment by VLG17** [comment]
@Kazzan you are correct, it was my mistake with your example. Higher priority means closer to "0", thanks for poiting that out. I have created a note with this. You should see it in the article after it gets approved.

**Comment by mypil** [comment]
@Kazzan - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/06833175095339a3ab715eb0150d43ec98369349. 


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by pjrcdf** [comment]
I think having an additional note to illustrate the the highest priority is 0 would be useful. 

For a newcomer to the technology the idea that the highest priority is actually the lowest value is a little counter intuitive and confusing.
