### ISSUE TITLE
Instructions do not provide intended result.

### ISSUE THREAD

**Issue by shane-obrien** [MicrosoftDocs/microsoft-365-docs#9483]
I followed the instructions provided and keep getting a message that the "Refresh has failed". The Power BI app is not able to load my data. The instructions in the doc suggest the tennant ID should have the hyphens removed, even though the dialog box in the app that asks for the tennant ID has dashes in the example format. I have tried both ways without success. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/usage-analytics/enable-usage-analytics?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@shane-obrien Thank you for your feedback. This looks more like a technical issue as it working on multiple other tenants. I'd recommend you to contact Microsoft via the need help section so that a Support engineer will be able to assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @shane-obrien Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
