### ISSUE TITLE
Audit Logs For Service Principals

### ISSUE THREAD

**Issue by haydanbarry** [MicrosoftDocs/microsoft-365-docs#9488]
Is it possible to see audit activity for Service Principals?  I have a MS Graph service principal that performs email purges imitated from my SEG.  I can see the sign-in activity for this service principal but I would like to be able to see which emails this SP purged. If this is possible, could an example be added on this page please?  Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51490fff-e4b6-24fe-d203-cec12a0db3a2
* Version Independent ID: 83caa7b3-3a93-a0e3-7d0a-74cacee4407a
* Content: [Search the audit log to troubleshoot common scenarios - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/auditing-troubleshooting-scenarios?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/auditing-troubleshooting-scenarios.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/auditing-troubleshooting-scenarios.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@v-tophillips Please help us in resolving this issue. Thanks

**Comment by v-tophillips** [comment]
I have forwarded this to the product team.

**Comment by yogkumgit** [comment]
@haydanbarry Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
