### ISSUE TITLE
error in office online apps " we could not apply your label at this time. Please try again later

### ISSUE THREAD

**Issue by sociologixllc** [MicrosoftDocs/microsoft-365-docs#949]
please address the above error after sensitivity labels are created and published, this error shows up in office apps web version

**Comment by mypil** [comment]
@sociologixllc - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by sociologixllc** [comment]
> @sociologixllc - May we know which Microsoft document link you used in reference to this issue?
> Please share it with us so we can investigate further. Thank you.
I am following this link and the preview functionality has been enabled in my tenant using powershell as per the below link: 
https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files

**Comment by mypil** [comment]
@sociologixllc - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let me know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get this information you are discovering back into the docs.
