### ISSUE TITLE
Using M365 Groups as a target mailbox

### ISSUE THREAD

**Issue by Corina-github** [MicrosoftDocs/microsoft-365-docs#9492]
Hi, 

I received a question from a customer about importing calendars already saved in PST to M365 groups. From their experienced behavior and on my test tenant, it looks like group mailboxes are not being recognized as valid mailboxes in the context of PST import tool, as they'll give this type of error : _Please create Primary and Archive Mailbox for "unified group " and create a new job_ . 

My ask: If this is indeed a limitation, could it also be stated specifically along with the public folder mention for the Mailbox column explanations ?

Thank you, 
Corina Ionescu
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import PST files - Microsoft Purview (compliance)](https://review.docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?view=o365-worldwide&branch=main#step-4-create-the-pst-import-mapping-file)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@Corina-github Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9523

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by Corina-github** [comment]
@msbemba Thank you for looking into this and making the change!
Having it more straight forward mentioned will help with the expectations on how PST import can be used. 

Thanks, 
Corina

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Corina-github Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
