### ISSUE TITLE
Please provide logical flow for the sample code snippnet.

### ISSUE THREAD

**Issue by krishnacloud123** [MicrosoftDocs/microsoft-365-docs#9496]
[Enter feedback here]
In the script - both CurrentStart and CurrentEnd are set to the same value and i do understand there is logical reason behind this. But please document what it is. So it easy for end users to understand the code flow better.

#Start script
[DateTime]$currentStart = $start
[DateTime]$currentEnd = $start

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec0b4030-1bf8-c9ee-2710-b6fd3a38a381
* Version Independent ID: 96da3f55-b072-d222-b0a9-ebdf84a87a0f
* Content: [Use a PowerShell script to search the audit log - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/audit-log-search-script?view=o365-worldwide&source=docs)
* Content Source: [microsoft-365/compliance/audit-log-search-script.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/audit-log-search-script.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by yogkumgit** [comment]
@krishnacloud123 Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
