### ISSUE TITLE
Statement about migration is misleading

### ISSUE THREAD

**Issue by mealiffe** [MicrosoftDocs/microsoft-365-docs#950]
The statement "Importing PST files to user mailboxes is one way to migrate your organization's email to Office 365" is misleading and should be changed. Using PST import to "migrate" data to O365 is not realistic for a customer of any reasonable size for the reasons I list below. We either need to soften the statement in this doc to not use the term "migrate," or provide detailed caveats around why this isn't really equivalent to a cutover, staged, or hybrid migration.

- it isn't really a migration, it's more of a greenfield deployment to O365, followed by data backfill of mailbox data only
- it doesn't fully migrate data - e.g. any data outside of what is visible to the user as well as user configuration associated with the on-premises deployment isn't carried over
- the time required to get the data ingested into the service will be significant and would not really be considered a "migration" in the same way that our formally documented migration types (cutover, staged, hybrid) are

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f9f87e-6f96-9663-114a-f6bd74a7a7f4
* Version Independent ID: b3ba56e3-0c78-f286-1c01-12375bf00f62
* Content: [Overview of importing your organization PST files to Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/importing-pst-files-to-office-365?source=docs#feedback)
* Content Source: [microsoft-365/compliance/importing-pst-files-to-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/importing-pst-files-to-office-365.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mealiffe Thanks for the suggestion. Article is updated.
