### ISSUE TITLE
Hello-world

### ISSUE THREAD

**Issue by NoorImann** [MicrosoftDocs/microsoft-365-docs#9502]
[Masukkan maklum balas di sini]

---
#### Butiran Dokumen

⚠ *Jangan edit bahagian ini. Ia diperlukan untuk docs.microsoft.com ➟ Pemautan isu GitHub.*

* ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Version Independent ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Content: [Microsoft 365 admin center - Overview - Microsoft 365 admin](https://docs.microsoft.com/ms-my/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide#who-has-admin-permissions-in-my-business)
* Content Source: [microsoft-365/admin/admin-overview/admin-center-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-center-overview.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by yogkumgit** [comment]
@NoorImann Please share your feedback here. Thanks

**Comment by yogkumgit** [comment]
@NoorImann We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
