### ISSUE TITLE
"Blocked" wording

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#9506]
This should be updated to stop referring to this as blocking. Setting the SCL to 9 and _delivering_ to the junk folder is NOT blocking. That is treating as spam.

If a tenant admin wants to outright block a sender or domain, this doesn't accomplish that goal (unless high confidence spam is sent to quarantine).

This is also missing information on the fact that the actual action is dependent on the spam policy. That isn't even mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbb3daf4-fa28-88d9-4543-89d8ff5ead5d
* Version Independent ID: bbb3daf4-fa28-88d9-4543-89d8ff5ead5d
* Content: [Manage allows and blocks in the Tenant Allow/Block List - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-tenant-allow-block-list?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/manage-tenant-allow-block-list.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-tenant-allow-block-list.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@danmyhre, I asked that very question several days ago (about what happens to the message is based on the action for high confidence spam in anti-spam policies). This was the response I got:

> Antispam action is for taking action on mail detected as spam. TABL Domains & addresses (sender) block is for blocking the sender of the email. both are different.

So, it sounds like what happens is independent of the anti-spam policy.

**Comment by dhairyya** [comment]
Right as you correctly pointed out this is not the correct behavior. We will rectify this behavior by the end of this year.
Today, the email is marked as spam (SCL:9) and then the email gets acted on by the spam policy
Tomorrow, we are looking to move it to admin quarantine as we are doing for URL and file blocks in Tenant allow/block list.

**Comment by danmyhre** [comment]
Great - thanks for the info and getting that updated in the content @dhairyya
