### ISSUE TITLE
July Updates

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#9508]
When can we expect the July updates? it is almost the end of August.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89486ebd-f4fa-9d07-ee93-d04fd8d41027
* Version Independent ID: 667019d9-aac6-f466-1605-651a800fc212
* Content: [What's new in Microsoft Purview risk and compliance solutions - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/whats-new.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/whats-new.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by v-tophillips** [comment]
Updates have been submitted. They should go live with the morning build on Thursday.
