### ISSUE TITLE
Server 2019 - Defender Reinstallation not possible!

### ISSUE THREAD

**Issue by ggriffinorg** [MicrosoftDocs/microsoft-365-docs#9509]
Hi,
I am having an issue.
Some "software provider" decided that by removing Windows Defender completely (Payloads too....) was the best way to make sure his software works.
I came across the matter as I am onboarding server to M365 Defender and Endpoint Manager.
Your tutorial to reinstall Windows Defender using Dism /Online /Enable-Feature /FeatureName:Windows-Defender  DOES NOT WORK.
Neither using the payloads/sources from another machine or a local WIM Dism /Online /enable-feature /featurename:Windows-Defender /all /source:WIM:C:\Temp\install.wim:2 /LimitAccess
Does someone have a working workaround to reinstall Windows Defender again.
TY in advance.
BR
Greg

**Comment by ggriffinorg** [comment]
Hi,
A little update:
Checking registry settings from a "healthy" Server 2019 Standard Server, it seems to that all entries for Windows Defender have been removed from [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing] and related Subkeys.
M$ does make available a package to service (defender-update-kit-x64) Windows Defender but it cannot be used with DISM /Online
Any change to get that option working as we cannot leave a server with a non working Windows Defender AV.
TY in advance for the feedback.
BR,
Greg

[ComponentBasedServicing_DEFENDER_ISSUE.zip](https://github.com/MicrosoftDocs/microsoft-365-docs/files/9419167/ComponentBasedServicing_DEFENDER_ISSUE.zip)
[ComponentBasedServicing_WORKING.zip](https://github.com/MicrosoftDocs/microsoft-365-docs/files/9419168/ComponentBasedServicing_WORKING.zip)

**Comment by msbemba** [comment]
@ggriffinorg Thank you for your feedback. This looks more like a technical issue and needs to be handled by our support team. I'd recommend you click on the need help Icon on the admin center to create a support ticket so that a Support engineer can assist you or create a bug if it is a product bug.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @ggriffinorg Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
