### ISSUE TITLE
Spelling error on Add users and assign licenses in Microsoft Defender for Business page

### ISSUE THREAD

**Issue by gigagimp** [MicrosoftDocs/microsoft-365-docs#9512]
Spelling Error on this page:

https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-add-users?view=o365-worldwide

"On the Optional settings page, you can expand Profile info and fill in details, such as the user's jo title, department, location, and so forth. Then choose Next."

Should be "user's job title"

![image](https://user-images.githubusercontent.com/36750031/186449783-8115626a-032d-4da2-b605-d013b3326aab.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9f839f-892b-57c3-97f0-76dd0095384d
* Version Independent ID: 3e9f839f-892b-57c3-97f0-76dd0095384d
* Content: [Add users and assign licenses in Microsoft Defender for Business](https://docs.microsoft.com/en-us/microsoft-365/security/defender-business/mdb-add-users?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-business/mdb-add-users.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-business/mdb-add-users.md)
* Product: **m365-security**
* Technology: **mdb**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
Hello @gigagimp and thank you so much for catching that! My apologies! The good news is, some kind person fixed it! I've merged their pull request and the updates will be live later today. https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9514
