### ISSUE TITLE
Cross-link to corresponding video

### ISSUE THREAD

**Issue by SoccerCore11** [MicrosoftDocs/microsoft-365-docs#9515]
Recommend to cross-link to the YouTube video that corresponds to this page and links back to it.
https://youtu.be/eQanpq9N1Ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070967c0-919e-30de-b3c6-9c1ea3f41be5
* Version Independent ID: 070967c0-919e-30de-b3c6-9c1ea3f41be5
* Content: [Security Operations Guide for Defender for Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/mdo-sec-ops-guide?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/mdo-sec-ops-guide.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mdo-sec-ops-guide.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by imdebamrita** [comment]
I am interested to solve this issue but can not understand what I need to do......

**Comment by chrisda** [comment]
Link added.

Thanks for the feedback.

Closing
