### ISSUE TITLE
IB example broken

### ISSUE THREAD

**Issue by DamienPascua** [MicrosoftDocs/microsoft-365-docs#9517]
The example at the bottom of the page is incorrect and will not allow publishing the policies when following the instructions as provided. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2baec804-4a76-95ac-3595-985629448fd9
* Version Independent ID: c0a5fb9d-93be-b448-5bf2-4c3bdd787b8e
* Content: [Get started with information barriers - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/information-barriers-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/information-barriers-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@DamienPascua Thank you for your feedback. The syntax used on the example is correct- New-InformationBarrierPolicy -Name "policyname" -AssignedSegment "segment1name" -SegmentsAllowed "segment2name","segment1name"

If you have a problem with a particular example, please let us know with the errors and we can identify if it is a technical bug or documentation issue.

Hope this helps!

Thanks
Sri

**Comment by DamienPascua** [comment]
@msbemba The issue is with the specific example "Example scenario: Contoso's departments, segments, and policies" "Contoso's IB policies", the documentation instructions are incorrect. Manufacturing blocks communication with Sales and Research with Policy 3, but Policy 1 and 2 do not block communication with Manufacturing

Policy 1 and 2 need to include "Manufacturing" or else Policy 3 creates an asymmetric policy error when trying to apply the policies as stated in the example.

This is further confused by the table outlining the expectation for the example being incorrect if Policy 3 and Manufacturing "can't communicate with" section is intentional. 
If we want "Manufacturing" to block segments other than HR and Marketing, the full table should read more clearly like this:

Segment -- Can Communicate with -- Can't communicate with
HR -- HR, Sales, Marketing, Research, Manufacturing -- (no restrictions)
Sales -- HR, Sales, Marketing -- Research, Manufacturing
Marketing -- HR, Sales, Marketing, Research, Manufacturing -- (no restrictions)
Research -- HR, Marketing -- Sales, Manufacturing 
Manufacturing -- HR, Marketing -- Sales, Research

If Policy 3 and Manufacturing "can't communicate with" section is not intentional for the example, then the table needs to be updated to reflect this and Policy 3 removed.

**Comment by msbemba** [comment]
@DamienPascua Thank you for your feedback. 

The scenario is that Sales and Research can communicate with Manufacturing. 

![image](https://user-images.githubusercontent.com/45987684/188868318-71fe624a-f393-4604-8129-c42bf3d5a519.png)

So Policy 3 will allow Manufacturing to communicate only with HR and Marketing. it won't prevent Research and sales from communicating with Manufacturing as they are allowed to communicate. This policy is a one-way policy.

Hope this helps!

Thanks
Sri

**Comment by DamienPascua** [comment]
@msbemba If one-way communication policies are now supported by Information Barriers, then why does the related document state otherwise? 
https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers?view=o365-worldwide
" Important

Information barriers only supports two-way communication and collaboration restrictions. For example, a scenario where Marketing can communicate and collaborate with Day Traders, but Day Traders cannot communicate and collaborate with Marketing isn't supported."

To clarify further:
Policy 1 implies Sales allows communication to Manufacturing
Policy 2 implies Research allows communication to Manufacturing
Policy 2 implies Manufacturing blocks communication to Sales and Research, making this a one-way policy to both Sales and Research.

**Comment by msbemba** [comment]
@DamienPascua Thank you for your feedback. You are correct. I have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9699 and once the author approves, the changes will be live.

Thank you so much for your time.

Thanks
Sri

**Comment by DamienPascua** [comment]
Circling back on this, it looks like the example is still broken with the example table and policies as of today.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit We are waiting for author to merge the PR

**Comment by yogkumgit** [comment]
@DamienPascua Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
