### ISSUE TITLE
Microsoft planner limits page issue - "10 contexts"

### ISSUE THREAD

**Issue by Kath-Anne** [MicrosoftDocs/microsoft-365-docs#9519]
https://docs.microsoft.com/en-us/office365/planner/planner-limits

Apparently there is a limit of "10 contexts" per plan, but no where is it documented what a "context" is.

Please could this be clarified?

**Comment by msbemba** [comment]
@Kath-Anne Thank you for your feedback. Contexts is a property in the planner. For more information you see -  https://docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta#properties
&
https://docs.microsoft.com/en-us/graph/api/resources/plannerplancontext?view=graph-rest-beta

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Kath-Anne Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
