### ISSUE TITLE
Get details link is incorrect

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9520]
In the section Automatic testing source the link to Get details is referring to the same page. I am expecting this to go to a page that lists the improvement actions that are automatically tested and what the signal that triggers the testing e.g. Secure Score is updated or other compliance solutions.

It would be useful to be able to see the overlap with the secure score.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d398e1-0aa5-a170-5605-b58e82d8a287
* Version Independent ID: dba57058-9780-1aa4-e2ba-9952fde21620
* Content: [Working with improvement actions in Microsoft Purview Compliance Manager - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-improvement-actions?view=o365-worldwide#update-testing-source)
* Content Source: [microsoft-365/compliance/compliance-manager-improvement-actions.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/compliance-manager-improvement-actions.md)
* Service: **o365-seccomp**
* GitHub Login: @chvukosw
* Microsoft Alias: **chvukosw**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9534

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The document has been updated. The issue can be closed.

Thanks
Sri
