### ISSUE TITLE
Is the Defender Plan 1 required - "Quarantine Policies'

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/microsoft-365-docs#9525]
This article describes a lot of the functionality but it does not specifically mention that anything more that the Global Admin Permissions are required. Is the Microsoft Defender Plan 1 required?

If so, can this article include that requirement more explicitly?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf5c5df-c3ab-8448-aef0-af05977db9b9
* Version Independent ID: adade895-f42b-1029-9948-5ddb5b038257
* Content: [Quarantine policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/quarantine-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/quarantine-policies.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@Jmartinez589 Thank you for your feedback. This is available on all M365 Subscriptions that include Exchange online and there is no special requirement for Defender plan 1 . We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9536

Thanks
Sri

**Comment by chrisda** [comment]
Related PR merged.

Thanks for the feedback.

Closing
