### ISSUE TITLE
additional information request

### ISSUE THREAD

**Issue by valiantloong** [MicrosoftDocs/microsoft-365-docs#9531]
[Enter feedback here]  Can Microsoft add some advise on how to handle the repeat calander invites which this resigned user had made? Like how to remove these invites or transfer to someone else for action?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e366b9c-0d35-83c6-f509-1774dd351504
* Version Independent ID: 702f2dc1-46f8-508a-68bc-b5d033c56a9a
* Content: [Remove a former employee - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-gb/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide)
* Content Source: [microsoft-365/admin/add-users/remove-former-employee.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/remove-former-employee.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@valiantloong Thank you for your feedback. I have added another document as a related article that talks about removing calendar events. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9553

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @valiantloong Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
