### ISSUE TITLE
correct available use of a downloaded app MSERT.exe

### ISSUE THREAD

**Issue by olafbacon** [MicrosoftDocs/microsoft-365-docs#9533]
Please change the instruction that says the MSERT.exe download is available **10 days** after download, to instead, inform us that the download is available **for 10 days** after download. [Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 286c4f73-ff88-3fdc-8673-47c11edd763b
* Version Independent ID: 286c4f73-ff88-3fdc-8673-47c11edd763b
* Content: [Microsoft Safety Scanner Download](https://docs.microsoft.com/en-us/microsoft-365/security/intelligence/safety-scanner-download?view=o365-worldwide)
* Content Source: [microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/intelligence/safety-scanner-download.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@olafbacon Thank you for your feedback. The document states Safety Scanner only scans when manually triggered and is available for use 10 days after being downloaded. 

This statement sounds accurate to me.

Hope this helps!

Thanks
Sri

**Comment by olafbacon** [comment]
Dear Sriraman M S, RE: [MicrosoftDocs/microsoft-365-docs] correct available use of a downloaded app MSERT.exe (Issue #9533). The instruction is ambiguous. You do not mean that implantation is allowed after a waiting quarantine period of 10 days since the download date. You mean to say it is recommended to be implemented “for use for only a total of 10 days” beginning with the download date, after which it should be deleted and if required again, a later version re-downloaded.
Olaf Bacon ***@***.******@***.***>) 2022-08-30
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder

**Comment by msbemba** [comment]
@olafbacon We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9617

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by olafbacon** [comment]
Thank you Sriraman M S. I expect the change will mean that you no longer expect the user to put the file into lock-down quarantine for 10 days after having downloaded it, before allowing him to use the utility. That app is supposed to FIND bugs, not to be put into quarantine to let the bugs in the utility itself die from lack of use. Thank you.

Thank you for your attention in this regard,
From Olaf G E Bacon
Email: ***@***.******@***.***>

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit Waiting for Author to review and approve the PR.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @olafbacon Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
