### ISSUE TITLE
Could you please lead the overview discussion with what specific licenses must be in place in order to use said features?

### ISSUE THREAD

**Issue by KFMjr** [MicrosoftDocs/microsoft-365-docs#9538]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3910d49-7cd7-16d9-e7d6-36e244ddef80
* Version Independent ID: c7b26d95-c150-99c9-06c4-b8ade11ab50a
* Content: [Insider risk management - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-solution-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-solution-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-solution-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@KFMjr Thank you for your feedback. The Subscription and license information has been added now via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9555

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@KFMjr Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
