### ISSUE TITLE
Bulk add custodians

### ISSUE THREAD

**Issue by airdalle** [MicrosoftDocs/microsoft-365-docs#954]
Is there a way to add or remove multiple custodians at once, through powershell scripts or any other mean ?
Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aab7cc9-714d-2322-c349-5e5e4eaea227
* Version Independent ID: 1f5ebfdf-6949-9d28-d374-3338fc189eeb
* Content: [Add custodians to an Advanced eDiscovery case - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/add-custodians-to-case)
* Content Source: [microsoft-365/compliance/add-custodians-to-case.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/add-custodians-to-case.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@airdalle Currently, you can't bulk-add custodians to a case but you can bulk-release multiple custodians by selecting them on the **Custodians** tab and then clicking **Release custodians** on the **Bulk actions** flyout page. Better ways to bulk-manage custodians (e.g. add multiple custodians to a case) is on the roadmap.
