### ISSUE TITLE
2008 R2 Support

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/microsoft-365-docs#9540]
The section "Windows Server onboarding overview" lists 2008 R2 however this operating system is omitted in the "Applies to" section.  I expect to see 2008 R2 in the "Applies to" section since it is still supported for customers who have purchased the Extended Security Update SKU or when they host the VM in Azure, in both of those cases it is supported.

"Windows Server 2008 R2 and later versions are supported"
Reference: https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/server-software-support#windows-server

"Customers who use Windows Server 2008 or Windows Server 2008 R2 products and services should migrate to Microsoft Azure to take advantage of three additional years of Critical and Important security updates at no additional charge and modernize when ready." https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-server-eos-faq/end-of-support-windows-server-2008-2008r2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Version Independent ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Content: [Defender for Endpoint onboarding Windows Server](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-server?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-server.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@itguysocal Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9557

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @itguysocal Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
