### ISSUE TITLE
1.	Calendar FreeBusy Anonymous sharing must be enabled to use Bookings with me. 

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/microsoft-365-docs#9542]
In the article, we recommend: 

To enable anonymous sharing, use the following command.
PowerShellCopy
  Set-SharingPolicy "Default Sharing Policy" -Domains @{Add="Anonymous:CalendarSharingFreeBusyReviewer"}

It has been shared with me by Bookings with me team, that any anonymous sharing policy will work, so users could use Anonymous:CalendarSharingFreeBusySimple.   
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Version Independent ID: 7bad8864-5f08-90ae-a6d1-a23e58fc1843
* Content: [Bookings with me](https://docs.microsoft.com/en-us/microsoft-365/bookings/bookings-in-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/bookings-in-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/bookings-in-outlook.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@dkotars Thank you for your feedback. This has been address in PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9473

Once the author approves, the changes will be live.

Thanks
Sri
