### ISSUE TITLE
Will there ever be:  Enable-Mailbox -InactiveMailbox ?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#956]
Hello, while I know this isn't an issue, I'm taking the chance anyway.  Just wondering if there's any plan to create the -InactiveMailbox parameter and functionality for the Enable-Mailbox cmdlet.  Currently it is only there with New-Mailbox, which is great, but the use case for Enable-Mailbox is, from my own experience anyway, more common than that of New-Mailbox.

Example: if a user has been deleted from Azure AD by way of being UN-synced from local AD for more than 30 days, but later comes back into sync-scope and is still a RemoteUserMailbox, migrated as far as on-premises AD/Exchange are concerned.

At this point we have to re-UN-sync the user, then force delete their newer Azure AD account from the AAD recycle bin, then do the New-mailbox -InactiveMailbox..., and finally we can then re-sync the user, after we set the ImmutableId on the new-new Azure AD account which was created by the New-Mailbox command (which BTW, has an -ImmutableId parameter, but it doesn't seem to  populate the Azure AD account's ImmutableId property when used (maybe it's for linking AAD<-->EXO accounts, rather than anything to do with on-premises-synced accounts).

That scenario would be a lot easier if we could just do Enable-Mailbox -InactiveMailbox and specific the existing Azure AD account (which will have no mailbox in my example, thanks to its lingering RecipientType/Details, RemoteRecipientType, etc. from on-premises).

T'would be nice.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e8e1ab-8080-9c2f-d6af-97fc01b0a2c0
* Version Independent ID: d8debc69-c7bf-6e28-6e9f-8b7fae822dfd
* Content: [Recover an inactive mailbox in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/recover-an-inactive-mailbox)
* Content Source: [microsoft-365/compliance/recover-an-inactive-mailbox.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/recover-an-inactive-mailbox.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@JeremyTBradshaw Thanks for the feedback. Please provide this same feedback (you could copy and paste it) at https://office365.uservoice.com/forums/289138-office-365-security-compliance
