### ISSUE TITLE
Fix Report Link

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#9562]
Please fix the report link, since it leads to the URL Protection report incorrectly.

"Go to Threat protection status report at https://security.microsoft.com/reports/URLProtectionActionReport and filter by View data by Email > Spam."

Suggesting:

"In the Threat protection status report, select View data by Email > Spam. To go directly to the report, open one of the following URLs:

Defender for Office 365: https://security.microsoft.com/reports/TPSAggregateReportATP
EOP: https://security.microsoft.com/reports/TPSAggregateReport"

_(Source: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/view-email-security-reports?view=o365-worldwide#threat-protection-status-report)_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5942c743-89c5-43c8-330a-dafbbb2dde37
* Version Independent ID: 025fd91b-9ddf-fc72-16e4-2f19ab860ed7
* Content: [What's the difference between junk email and bulk email? - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email?view=o365-worldwide#how-to-tune-bulk-email)
* Content Source: [microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/what-s-the-difference-between-junk-email-and-bulk-email.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hudish, fixed.

In the future, you too can make changes like this directly. No need to open an Issue first. Instructions are [here](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/README.md).

Thanks for the feedback.

Closing
