### ISSUE TITLE
getting error while creating migration endpoint related to key vault

### ISSUE THREAD

**Issue by faiz7912** [MicrosoftDocs/microsoft-365-docs#9563]
[Enter feedback here]
Although , it is mentioned that it is not required key vault setup for mailbox migration as per doc. But getting error while creating migration endpoint related to key vault.

Error finding certificate '' from azure key vault for tenant '8ffc5e22-e7f6-434b-xxxxxxxxxxxxxxxxxxxxx'.
    + CategoryInfo          : NotSpecified: (:) [New-MigrationEndpoint], KeyVaultFailureErrorException
    + FullyQualifiedErrorId : [Server=SA1PR05MB8516,RequestId=03481fea-25c5-45a7-b3a5-007672f14e0a,TimeStamp=30-08-2022 15:20:31] [FailureCategory=Cmdlet-KeyVaultFailureErrorException] 287AA0D5,Micr 
   osoft.Exchange.Management.Migration.MigrationService.Endpoint.NewMigrationEndpoint
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@faiz7912 Thank you for your feedback. I was able to create one without Azure Key Vault. This sounds more like an issue with your tenant and I'd recommend you contact Microsoft support via the need help section on the admin center so that a Support engineer can fix the problem or raise it to the product group.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @faiz7912 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
