### ISSUE TITLE
last command is not  Get-CsBatchTeamsDeployment, is Get-CsBatchTeamsDeploymentStatus

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/microsoft-365-docs#9565]
last command is not  Get-CsBatchTeamsDeployment, is Get-CsBatchTeamsDeploymentStatus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe932bdb-d43e-356a-2c61-5d0f5c895695
* Version Independent ID: fe932bdb-d43e-356a-2c61-5d0f5c895695
* Content: [Deploy teams at scale for frontline workers in Microsoft Teams - Microsoft 365 for frontline workers](https://docs.microsoft.com/en-us/microsoft-365/frontline/deploy-teams-at-scale?view=o365-worldwide)
* Content Source: [microsoft-365/frontline/deploy-teams-at-scale.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/frontline/deploy-teams-at-scale.md)
* Service: **microsoft-365-frontline**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by msbemba** [comment]
@TomoharuMisawa Thank you for your feedback. I have verified that the document has the correct cmdlets now.

Get-CsBatchTeamsDeploymentStatus -OrchestrationId "OrchestrationId"

@yogkumgit  There are no changes needed to this document. 

Hope this helps!

Thanks
Sri
