### ISSUE TITLE
On the Japanese site, User.csv has the owner written, but Japanese was not available

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/microsoft-365-docs#9566]
It seems that Japanese cannot be used in the Owner or Member column of user.csv, but since it has been translated on the ja-jp site, the user was not added to the site as it was.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe932bdb-d43e-356a-2c61-5d0f5c895695
* Version Independent ID: fe932bdb-d43e-356a-2c61-5d0f5c895695
* Content: [Deploy teams at scale for frontline workers in Microsoft Teams - Microsoft 365 for frontline workers](https://docs.microsoft.com/en-us/microsoft-365/frontline/deploy-teams-at-scale?view=o365-worldwide)
* Content Source: [microsoft-365/frontline/deploy-teams-at-scale.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/frontline/deploy-teams-at-scale.md)
* Service: **microsoft-365-frontline**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by yogkumgit** [comment]
@TinaMcN Please help. Thanks

**Comment by TinaMcN** [comment]
Including @MartinOersted to help with this.

**Comment by MartinOersted** [comment]
Please open a bug as per previous requests. If you cannot maybe ask Tina Burden.

**Comment by yogkumgit** [comment]
@tiburd Please help. Thanks

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [233809](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/233809)

I'm closing this issue because the Global Services team will handle it from here.
