### ISSUE TITLE
csv file must have a title line

### ISSUE THREAD

**Issue by TomoharuMisawa** [MicrosoftDocs/microsoft-365-docs#9567]
A csv file must have a title line.
It is better to specify it somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe932bdb-d43e-356a-2c61-5d0f5c895695
* Version Independent ID: fe932bdb-d43e-356a-2c61-5d0f5c895695
* Content: [Deploy teams at scale for frontline workers in Microsoft Teams - Microsoft 365 for frontline workers](https://docs.microsoft.com/en-us/microsoft-365/frontline/deploy-teams-at-scale?view=o365-worldwide)
* Content Source: [microsoft-365/frontline/deploy-teams-at-scale.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/frontline/deploy-teams-at-scale.md)
* Service: **microsoft-365-frontline**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by yogkumgit** [comment]
@LanaChin Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@LanaChin Gentle reminder. Thanks

**Comment by samanro** [comment]
Adding in separate PR: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/18576
