### ISSUE TITLE
Safe Domains Ignored by Outlook in EXO

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/microsoft-365-docs#9568]
Based on my past commit this year, https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/14839/commits/a710fbf1b2df388eb59e5fb14c7b0bbd2ba28fa6 - there should have been a sentence in this doc that Safe Domains are ignored in EXO, when defined by end-users in Outlooks. I do not see my change in this doc.

Current text:
"By design and for increased security of Exchange Online mailboxes, only the junk email settings for safe senders and safe domains, blocked senders, and blocked domains are recognized. Safe mailing list settings are ignored."

Suggested text
**"By design and for increased security of Exchange Online mailboxes, only the junk email settings for safe senders, blocked senders, and blocked domains are recognized. Safe domains settings are ignored."**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@hudish Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9611

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by chrisda** [comment]
Issue is more subtle. It's more about 'Move to JMF' vs 'Quarantine'. Everything explained in https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/17670.

Thanks for the feedback.

Closing
