### ISSUE TITLE
DLP Teams GCC > Timeline?

### ISSUE THREAD

**Issue by rbahne** [MicrosoftDocs/microsoft-365-docs#957]
When can we expect this: https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams to be available in GCC? 

All I see is that it is not available: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

Roadmap give no guidance on GCC: https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=34246

It seems irresponsible to offer the tool without the necessary supporting features. 

Thanks,

Ryan

**Comment by mypil** [comment]
@rbahne - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by mypil** [comment]
@chrfox - Can you please share your insights on this issue?

Thank you.

**Comment by chrfox** [comment]
Hi @rbahne , 
Thank you for your question. The best place to stay informed on upcoming releases is the product roadmap, which you have already consulted, and the notification center in the Microsoft 365 admin center.
