### ISSUE TITLE
Seeing millions of requests that appear to be legit Microsoft Graph Change Notifications from (2) IPs not listed here

### ISSUE THREAD

**Issue by wdwinslow** [MicrosoftDocs/microsoft-365-docs#9573]
We are seeing substantial traffic that appears to be legitimate Microsoft Graph Change Notifications from these IPs.  Since they are not listed on this page, our load balancer firewall is currently blocking these requests.

Can you check and confirm if these IPs are legitimate sources of Microsoft Graph Change Notifications?  If so, can you update the page to include these IPs?

20.9.37.73 - 5,674,749 (earliest entry in our logs - Aug 26th)
20.9.37.76 - 863,233 (earliest entry in our logs - Aug 26th)

Note - both of these IPs are delegated to Microsoft.  
Reference: [](https://mxtoolbox.com/SuperTool.aspx?action=arin%3a20.9.37.76&run=networktools)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de1e69c-aee8-2cd4-3f69-5288253d9b2a
* Version Independent ID: 3bcee52a-c7be-6ce3-05a9-2409ec30661c
* Content: [Other endpoints not included in the Office 365 IP Address and URL Web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by DarrenRuane** [comment]
I came to say that we also observed the same as @wdwinslow; significant traffic to our Change Notification endpoints from the same two IP addresses (20.9.37.73 and 20.9.37.76) - neither of which are listed on the reference page.

Would appreciate some clarification as to whether or not these are genuine MS Graph Change Notification IP addresses so we can adjust our firewall accordingly.

Thanks.

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by wdwinslow** [comment]
I checked our logs, and this is continuing.  I've opened a support request (#33187810)‎ with Microsoft on this where I have provided additional evidence.  Currently, we have seen about 19 million requests blocked from these IPs in the last 7 days.

**Comment by wdwinslow** [comment]
It appears as of today that the page has been updated and now lists these IPs.  Closing...
