### ISSUE TITLE
How to Get QR Code as User

### ISSUE THREAD

**Issue by aaronstackpole** [MicrosoftDocs/microsoft-365-docs#9574]
It would be exceptionally useful for there to be a link to an article describing how to generate a QR code so that you can configure your iPad with this method. This article talks about how to disable or enable the feature as an administrator. It seems quite relevant to know how to use this as a user as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 749a8389-eda6-3059-b713-5d0b3755fe9c
* Version Independent ID: 53000b70-b561-ec33-0b94-f0c26650548b
* Content: [Use a QR code to sign-in to the Outlook mobile apps - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/use-qr-code-download-outlook?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/use-qr-code-download-outlook.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/use-qr-code-download-outlook.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@aaronstackpole Thank you for your feedback. We do not have a document that talks about how a user receives QR code. However, this document has been updated with information

In Outlook on the web or other desktop Outlook applications, users may see notifications informing them that they can use Outlook on their mobile devices.
 If users choose to send themselves an SMS text message to download the app on their mobile device, a QR code will appear on their computer.
They will be able to scan the QR code to log into Outlook on their phone or tablet. 

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @aaronstackpole Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
