### ISSUE TITLE
Step 7 Target License Requirement

### ISSUE THREAD

**Issue by aandrade550** [MicrosoftDocs/microsoft-365-docs#9579]
Recently followed this step by using a shared account without any license. Connector seems to be sending the data however the "My Connector" page shows an error that there is a missing license. The license is not specified and the link simply takes us to an article.

Please consider updating this page specifically step 7 with the intended recipient email license requirements to avoid this error and be able to retrieve the data being archived.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a96542-6e0f-d441-13db-6e47439c0583
* Version Independent ID: 524ca3e3-3e80-4693-206e-01a9533292f8
* Content: [Set up a connector to archive LinkedIn data - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/archive-linkedin-data?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/compliance/archive-linkedin-data.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/archive-linkedin-data.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@aandrade550 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9613 

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @aandrade550 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
