### ISSUE TITLE
we have it all set to strict but the same phishing email still bypass EOP&ATP

### ISSUE THREAD

**Issue by netaneladar** [MicrosoftDocs/microsoft-365-docs#958]
We have all the strict setting ON, INCLUDING all the advanced spam filters in EOP. (You'd be a fool to listen to this article that recommends NOT turning on the advanced setting "MarkAsSpamSpfRecordHardFail". You should at least turn that one on). I *think* Microsoft recommends not turning it on because the advanced filtering options in EOP can cause issues with the entries you have whitelisted in the connection filter. 

Anyways, on to the main point. 
We've had all the setting on for a while now (we even disabled the "Safe List" in the connection filter), but we are constantly getting phishing from other O365 tenant in the US and outside the US. EOP and ATP blindly trust other O365 tenant. 

There are also 3 easy tactics in 2019 that phishers are using to bypass EOP and ATP on a CONSISTENT basis:
1) HTML injection in the email. I.e. an email has these words in the  "click here to activate account to avoid account de-activation". But the actual phisher send some thing like this "cliTRANSPERENT TEXTck here TRANSPARENT TEXTto activate account TRANSPERENT TEXT to avoid account TRANSPERENT TEXT de-activation"
2) Link redirect - to avoid Safe Links. Many times the final hosted phishing/malware is hosed in azure websites. 
3) ATP anti-impersonation is no longer blocking Friendly Name of users like your CEO. There must have been a backend change to how ATP anti-impersonation works sometime around September 2019 or earlier. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Office 365 ATP security settings, recommendations, Sender Policy Framework, Domain-based Message Reporting and Conformance, DomainKeys Identified Mail, steps, how does it work, security baselines, baselines for EOP, baselines for ATP, setup ATP, setup EOP, configure ATP, configure EOP, security configuration - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@netaneladar - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature requests on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.


Thank you for your contribution to make the docs better! Much appreciated!
