### ISSUE TITLE
Nowhere in Admin guide does anyone say "close an account"

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/microsoft-365-docs#9580]
The usage of new terminology here is unwarranted.

"Close an account" is something we do at a bank.

Is this DISABLE an account?  Unlicense an account?  Delete an account?

PLEASE BE MORE CLEAR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eaa6e98-66e9-aad3-2d67-543c22f4ce4b
* Version Independent ID: 26bddf9e-f338-329f-76e5-302a1343f7f1
* Content: [Microsoft 365 admin center activity reports - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/activity-reports/activity-reports?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide#feedback)
* Content Source: [microsoft-365/admin/activity-reports/activity-reports.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/activity-reports.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@chrislehr Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9614

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The document has been updated. The issue can be closed.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chrislehr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
