### ISSUE TITLE
PQMT:[Express Route] "Office 365 URLs and IP address ranges" and "Routing by ExpressRoute for Office 365" have some inconsistencies in content

### ISSUE THREAD

**Issue by Sayuri-Kaseda** [MicrosoftDocs/microsoft-365-docs#9587]
![20220901](https://user-images.githubusercontent.com/103735276/187844725-9ee0d981-5c35-4fce-a381-54793003b26c.jpg)

[URL]　
https://docs.microsoft.com/en-us/microsoft-365/enterprise/routing-with-expressroute?view=o365-worldwide#deciding-which-applications-and-features-route-over-expressroute
https://docs.microsoft.com/ja-jp/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online

[Description]
"Office 365 URLs and IP address ranges" and "Routing by ExpressRoute for Office 365" have some inconsistencies in content.
There is a discrepancy in the following description of the domains.
・*.microsoftonline.com
・provisioningapi.microsoftonline.com
・adminwebservice.microsoftonline.com

"*.microsoftonline.com" is set to No in "Office 365 URLs and IP address ranges" but is set to YES in "Routing with ExpressRoute for Office 365". 

・Office 365 URLs and IP address ranges
![image](https://user-images.githubusercontent.com/103735276/187844089-b84c80a5-fabc-464b-ac93-fdd3f72cdf64.png)

・Routing by ExpressRoute for Office 365
![image](https://user-images.githubusercontent.com/103735276/187844212-45a86a0d-bfd8-4a0c-beff-266b59e3ea85.png)

"provisioningapi.microsoftonline.com" and "adminwebservice.microsoftonline.com" are set to YES in "Office 365 URLs and IP address ranges" but are set to No in "Routing with ExpressRoute for Office 365".

・Office 365 URLs and IP address ranges
![image](https://user-images.githubusercontent.com/103735276/187844288-44b4b456-68c7-47b4-81a9-7ef8693f8d35.png)

・Routing by ExpressRoute for Office 365
![image](https://user-images.githubusercontent.com/103735276/187844329-9ded83ab-37d3-45e9-bf5f-258fc993ae40.png)

Would like to see the inconsistency eliminated between the two Docs.​

[Actual result]
Inconsistencies between "Office 365 URL and IP address ranges" and "Routing with ExpressRoute for Office 365".

[Expected result]
"Office 365 URL and IP address ranges" and "Routing with ExpressRoute for Office 365" are consistent.

[Source]
Japan Internal Feedback

[Copied from]
https://microsoft.sharepoint.com/:li:/t/ntojapan/pqmt/E2pxnFXU9GpGnzR2E6Z1D4UB_ZXJzijsNzt4gGxllWNuWA?e=NdrdTU

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by Saki-Yufu** [comment]
Here, there doesn't seem to be any change in the documents, is there any update? Thanks.

**Comment by tiburd** [comment]
We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).
