### ISSUE TITLE
Outlook Safe Sender list - impact on the Tenant is missing

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/microsoft-365-docs#9589]
Hi,

The article does not mention if the Outlook Safe Sender list just allows the message to this recipient who created the entry or if the Safe Sender List from one user will affect all users within the Tenant. The other options like IP allow list or Allowed sender lists or allowed domain lists are very clear on this, that this is tenantwide.

Any chance to clarify this within the article to have a statement here which user in detail is affected if the safe sender list from Outlook is used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c900a9d1-897d-f7e9-6c58-a510edf56a9b
* Version Independent ID: bc59ac94-233b-e558-4455-a4c7166d4023
* Content: [Create safe sender lists - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dhairyya** [comment]
@chrisda it just impacts the user who is creating this.
IT is user level

**Comment by chrisda** [comment]
I added some clarification statements about the Outlook Safe Senders list (bolded for emphasis):

> 3. Outlook Safe Senders (the Safe Senders list that's stored in each mailbox **that affects only that mailbox**).

> Instead of an organizational setting, users or admins can add the sender email addresses to the Safe Senders list in the mailbox. For instructions, see [Configure junk email settings on Exchange Online mailboxes in Office 365](https://learn.microsoft.com/microsoft-365/security/office-365-security/configure-junk-email-settings-on-exo-mailboxes). **Safe Senders list entries in the mailbox affect that mailbox only**.

Thanks for the feedback.

Closing
