### ISSUE TITLE
Correction to instruction

### ISSUE THREAD

**Issue by mikalzen** [MicrosoftDocs/microsoft-365-docs#9590]
In the second list item under "Enable an archive mailbox"
"In the left pane of the compliance portal, select Data lifecycle management > Microsoft 365 > Archive."

The step "Microsoft 365 >" should be removed, as the step isn't there.

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f19511c-5a0f-9d5f-0779-79a9ad99938f
* Version Independent ID: 3b513017-641c-38ae-3938-03a9ee3a6923
* Content: [Enable archive mailboxes for Microsoft 365 - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/enable-archive-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/enable-archive-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/enable-archive-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @mikalzen  The data lifecycle management solution in the compliance portal has recently been updated and is now split into "Microsoft 365" and "Exchange (legacy") options, so all the instructions have been updated to match. If you don't see the "Microsoft 365" option in the UI yet, you will very soon.

You can read more about these two options in https://docs.microsoft.com/en-us/microsoft-365/compliance/data-lifecycle-management and the UI change will be covered in "What's new ... for August" (https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new) when it's published.
