### ISSUE TITLE
Page makes no reference as to whether server protection can be extended as a part of a core/non-specific license such as M365 E3 or Business Premium (only that it is not available as a part of standalone Defender Plan 1/2). Please include details on this as it's difficult to track down. TIA

### ISSUE THREAD

**Issue by KFMjr** [MicrosoftDocs/microsoft-365-docs#9591]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4b36b3a-e292-e035-ab94-895c56b46c76
* Version Independent ID: 2e02900f-f545-a199-8d1c-b6a7958ee1df
* Content: [Minimum requirements for Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/minimum-requirements?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/minimum-requirements.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/minimum-requirements.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@KFMjr Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9624

Whether it is standalone or when it is a part of M365 plans, it does not include servers plan 1 or 2. So you'll need Defender for Servers Plan 1 or Plan 2 as part of the [Defender for Cloud]

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @KFMjr Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
