### ISSUE TITLE
Device Group rank clarity

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/microsoft-365-docs#9592]
In the [Manage Device Group](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-groups?view=o365-worldwide#manage-device-groups) section it should clarify what highest and lowest means. E.g. a device group with a rank of 1 is the highest/lowest rank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a0f4a32-b5d6-82b6-f42a-9664d9be8f5a
* Version Independent ID: e64468af-9eda-5fad-9d39-f837e70c1123
* Content: [Create and manage device groups in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-groups?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/machine-groups.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine-groups.md)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @thommck Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
