### ISSUE TITLE
Note on old name

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/microsoft-365-docs#9594]
I came here after searching how to disable the M365 Unified Audit Log. 
I think this page (and the sub pages) would benefit from a note saying that The Microsoft Purview auditing is the new name for the unified audit log. It is implied slightly on this page but is easy to miss (and Bing sent me to the Audit (Standard) sub page).
I think people could easily get confused (like me) and think the Purview Audit log was something different to what we've had since O365 begun!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9653a7b1-0227-95d1-6357-b54361d63321
* Version Independent ID: f33fce66-1688-01be-cf76-3a538730c5f9
* Content: [Microsoft Purview auditing solutions - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/auditing-solutions-overview?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/auditing-solutions-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/auditing-solutions-overview.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@thommck Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9625

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @thommck Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
