### ISSUE TITLE
Why are so many parameters marked "reserved for internal Microsoft use"  $$$$$ 

### ISSUE THREAD

**Issue by TripleStackJack** [MicrosoftDocs/microsoft-365-docs#9596]
Oh no, another parameters marked "reserved for internal Microsoft use" again.  That parameter is what I needed to avoid 47 Search & Delete tasks.   Gosh, what will I do?

I'm getting really tired of watching micro$oft cut off administrative tools for the purpose of Charging customer more than the $1 million we already pay.  Making my job more difficult, just for micro$oft profit, is not acceptable.  It is stealing.  Nice job micro$oft, unmanaged code releases & gutting of services for profit.  What's next?  The old entrap and charge to get out management strategy from the 1990's (ala Kaspersky - Russian ransomware).   Not too bright.   

My new T-shirt campaign:  Vote NO on micro$oft in 2023!  (and all the years after.)

**_

> Vote NO on micro$oft in 2023!  
> (and all the years after.)

_**

**_

> Vote NO on micro$oft in 2023!  
> (and all the years after.)

_**

**_

> Vote NO on micro$oft in 2023!  
> (and all the years after.)

_**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e391a3b9-fc52-bedf-353a-3564752240dd
* Version Independent ID: 89376ace-9c00-7c45-3771-a9a913f81bed
* Content: [Search for and delete email messages in your organization - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@TripleStackJack Thank you for your feedback. Could you provide more information on which parameter you are referring to?

Thanks
Sri

**Comment by yogkumgit** [comment]
@TripleStackJack We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
