### ISSUE TITLE
clarification needed in step Prepare the source (current mailbox location) tenant step

### ISSUE THREAD

**Issue by quimguito** [MicrosoftDocs/microsoft-365-docs#9597]
in section [Prepare the **target** tenant ](https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?source=recommendations&view=o365-worldwide#prepare-the-target-tenant-by-creating-the-exchange-online-migration-endpoint-and-organization-relationship)  explicitly refers on setp to "1. [Connect to Exchange Online PowerShell] in the target Exchange Online tenant." 
but in the section "Prepare the **source** (current mailbox location) tenant" the step 3 "_Create a new organization relationship or edit your existing organization relationship object to your target (destination) tenant in Exchange Online PowerShell:_" the script shoud it be executed in target or source tenant ?

**Comment by msbemba** [comment]
@quimguito Thank you for your feedback. The section talks about setting up target tenant so you connect to the target exchange online tenant and create a new org relationship with the source tenant by running the below cmdlet 

$sourceTenantId="[tenant id of your trusted partner, where the source mailboxes are]"
$orgrels=Get-OrganizationRelationship
$existingOrgRel = $orgrels | ?{$_.DomainNames -like $sourceTenantId}
If ($null -ne $existingOrgRel)
{
    Set-OrganizationRelationship $existingOrgRel.Name -Enabled:$true -MailboxMoveEnabled:$true -MailboxMoveCapability Inbound
}
If ($null -eq $existingOrgRel)
{
    New-OrganizationRelationship "[name of the new organization relationship]" -Enabled:$true -MailboxMoveEnabled:$true -MailboxMoveCapability Inbound -DomainNames $sourceTenantId
}


Hope this helps!

Thanks
Sri

**Comment by quimguito** [comment]
Hello thanks on your response,
but my doubt is in preparation the source tenant, the following step (“Prepare the source (current mailbox location) tenant by accepting the migration application and configuring the organization relationship”) should I run the powershell commands in the target server or in the source server in the step mentioned above.

Melhores Cumprimentos,
Best Regards,
Joaquim Silva
Computer and Systems Engineer
Technician Department

[https://simulador.extrabite.pt/imagens/extrabite_NatalGif.gif]
[https://simulador.extrabite.pt/imagens/separador.png]
T: +351 256 830 840
M: +351 966 788 601
E: ***@***.******@***.***>
W: http://www.extrabite.pt/
[https://simulador.extrabite.pt/imagens/separador.png]
[https://simulador.extrabite.pt/imagens/EIC9002.jpg]

A: Rua Guerra Junqueiro, nº333 R/C | P: 3700-132 São João da Madeira
[https://simulador.extrabite.pt/imagens/banner_assinatura.jpg]

De: Sriraman M S
Enviada: 6 de setembro de 2022 11:35
Para: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: Joaquim Silva | EXTRABITE ***@***.***>; Mention ***@***.***>
Assunto: Re: [MicrosoftDocs/microsoft-365-docs] clarification needed in step Prepare the source (current mailbox location) tenant step (Issue #9597)


@quimguito<https://github.com/quimguito> Thank you for your feedback. The section talks about setting up target tenant so you connect to the target exchange online tenant and create a new org relationship with the source tenant by running the below cmdlet

$sourceTenantId="[tenant id of your trusted partner, where the source mailboxes are]"
$orgrels=Get-OrganizationRelationship
$existingOrgRel = $orgrels | ?{$_.DomainNames -like $sourceTenantId}
If ($null -ne $existingOrgRel)
{
Set-OrganizationRelationship $existingOrgRel.Name -Enabled:$true -MailboxMoveEnabled:$true -MailboxMoveCapability Inbound
}
If ($null -eq $existingOrgRel)
{
New-OrganizationRelationship "[name of the new organization relationship]" -Enabled:$true -MailboxMoveEnabled:$true -MailboxMoveCapability Inbound -DomainNames $sourceTenantId
}

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@quimguito That is correct. they need to connect to the source tenant in order to make that change. I have made the change to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9633

Once the author approves, the changes will be live.

Thanks
Sri
