### ISSUE TITLE
Clairification on 60 email address limit

### ISSUE THREAD

**Issue by rstraker** [MicrosoftDocs/microsoft-365-docs#960]
You can add up to 60 internal and external addresses that you want to protect from impersonation.  Is this 60 addresses per email domain or O365 Tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Set up Office 365 ATP anti-phishing policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?source=docs#feedback)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by VLG17** [comment]
@rstraker The 60 internal and external addresses is a per tenant limit. After you configure these you can also configure the domains that you want to protect.

![image](https://user-images.githubusercontent.com/41186174/71784211-94523880-2ff9-11ea-9803-02ed05d79690.png)

![image](https://user-images.githubusercontent.com/41186174/71784218-a03dfa80-2ff9-11ea-85c8-711891ee8d2a.png)

**Comment by mypil** [comment]
@rstraker - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by VLG17 so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!
