### ISSUE TITLE
Clarify about password-protected attachments (continuation of #9249)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/microsoft-365-docs#9603]
I'm questioning the total validity of this statement towards the top of the page:

> If a file attachment is encrypted or password protected, it can't be examined by Safe Attachments. **The message with the attachment will be delivered, and the recipient receives no warning that the file hasn't been scanned** by Safe Attachments.

Particularly, I'm wondering about the above behavior when the Action is set to Block/Replace/Dynamic-Delivery, and this setting is enabled:

> Apply the above selection if malware scanning for attachments times out or error occurs: The action specified by Safe Attachments unknown malware response is taken on messages even when Safe Attachments scanning can't complete.

I feel like the safe assumption is that it will Block/Replace/Dynamically-deliver(i.e., quarantine) the message/attachment rather than simply deliver it as if the Action was Off or Monitor.  Can somebody please confirm?  I would do the PR to update the page to clarify once I know for certain.

Thanks in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5966b7b-cbaa-eaa2-c9d6-5c6e7218df74
* Version Independent ID: cfcc8772-be5d-009a-0805-62624835ac5f
* Content: [Safe Attachments - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-attachments?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-attachments.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@JeremyTBradshaw, the response I got was to remove that statement about encrypted and password protected content from the article.

Apparently, **Apply the Safe Attachments detection response if scanning can't complete (timeout or errors)** setting has nothing to do with it.

**Comment by JeremyTBradshaw** [comment]
@chrisda thanks as always.  I'm going to accept that, close this issue and forget about it for now.  It leaves the question about how _does_ Safe Attachments handle encryption/password-protected unanswered, which was an issue in the past (I think this is the original Tech Community thread which led to that blurb being added in the first place - https://techcommunity.microsoft.com/t5/microsoft-defender-for-office/safe-attachments-and-encrypted-or-password-protected-attachments/m-p/3582077).  So people do wonder and may submit PR's in the future, but I'm happy to walk away at this time.  Thanks again.
