### ISSUE TITLE
Wrong Title

### ISSUE THREAD

**Issue by lenonsales** [MicrosoftDocs/microsoft-365-docs#9604]
[Hello Team! We checked that the title (Preview), is not correct for this page. Because the feature is available more thant 2 years in Microsoft.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0a0c8c3-d5e1-568a-7270-99ae9c1aa687
* Version Independent ID: a593e88e-6dbf-8273-9c1b-52b2904b2b57
* Content: [Learn about the default DLP policy in Microsoft Teams (preview) - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-teams-default-policy?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-teams-default-policy.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-teams-default-policy.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@lenonsales Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9621

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @lenonsales Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
