### ISSUE TITLE
Powershell Modules mentioned incorrectly.

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/microsoft-365-docs#9606]
Under heading 'Use PowerShell to modify phishing simulation override rules' it is mentioned to use Exchange Online Powershell to run the command: Set-PhishSimOverrideRule.

However, this cmdlet is only available in Security and Compliance Powershell.

https://docs.microsoft.com/en-us/powershell/module/exchange/set-phishsimoverriderule?view=exchange-ps

Likewise, under heading 'Use PowerShell to remove a phishing simulation override policy' it is mentioned to use Exchange Online Powershell to run the command: Remove-PhishSimOverridePolicy.

This cmdlet is also only available in Security and Compliance Powershell.

https://docs.microsoft.com/en-us/powershell/module/exchange/remove-phishsimoverridepolicy?view=exchange-ps

Please help in updating the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17ce75e-79ba-0acd-066c-a0120a29d65d
* Version Independent ID: 14673b1c-8489-0abc-90a0-42f35d516424
* Content: [Configure the delivery of third-party phishing simulations to users and unfiltered messages to SecOps mailboxes - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-advanced-delivery?view=o365-worldwide#powershell-procedures-for-third-party-phishing-simulations-in-the-advanced-delivery-policy)
* Content Source: [microsoft-365/security/office-365-security/configure-advanced-delivery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-advanced-delivery.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@kumaarrahul Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9623

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kumaarrahul Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
