### ISSUE TITLE
transfer e-mail from godaddy to microsoft business ofice 365

### ISSUE THREAD

**Issue by inside610** [MicrosoftDocs/microsoft-365-docs#9607]
I bought a $5 business assist and need someone to call me tomorrow morning to walk me through how to transition my e-mail from godaddy to microsoft 365.  The e-mail I need to transfer is keith@inside610.com.  Inside610.com domain is registered with godaddy.com and the office 365 is through them as well as they are a reseller of microsoft 365.

281-714-6310

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d32f1ee8-5c57-e0b8-2632-1e7b2a9c06ff
* Version Independent ID: 5e1fd1e7-396a-58ca-31f2-2da3beb6aff6
* Content: [Support information for United States - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/united-states?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/united-states.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/united-states.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@inside610 Thank you for your feedback. Since this is a support request, I'd recommend you open a support ticket via the need help option in the admin center so that a support engineer can work with you to resolve the problem.

If for some reason you cannot access the admin center, you can open a support ticket by contacting our tech support team on 1 800 865 9408

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @inside610 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
