### ISSUE TITLE
Not an issue, just feedback

### ISSUE THREAD

**Issue by exequielsantangelo** [MicrosoftDocs/microsoft-365-docs#9609]
[This rabbit hole was really interesting, i was wondering if was possible to implement a real user experience into an android tablet...im really impresed..]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce65739-6428-fc57-012c-a6741a051c6b
* Version Independent ID: 3341ac81-3e21-4e71-e4f7-3eff41db05b8
* Content: [About the Microsoft 365 admin mobile app - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-mobile-app?view=o365-worldwide#what-do-i-need-to-do-to-be-able-to-use-the-app)
* Content Source: [microsoft-365/admin/admin-overview/admin-mobile-app.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-mobile-app.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@exequielsantangelo Thank you for your feedback. Since this is product feedback, I'd recommend you post this on our main feedback portal - https://feedbackportal.microsoft.com/ so that a dev or a product engineer can look into it and provide more details.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@exequielsantangelo Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
