### ISSUE TITLE
Isolation through Live Response is only supported on MacOS - doc is misleading implying LR can also be used to do this on Linux

### ISSUE THREAD

**Issue by eepyaich** [MicrosoftDocs/microsoft-365-docs#9610]
The document says "Isolating devices from the network is not currently supported for devices running macOS or Linux. Use live response to run the action. For more information on live response, see [Investigate entities on devices using live response](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response?view=o365-worldwide)."

However, based on https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/live-response?view=o365-worldwide#advanced-commands, I believe isolation through Live Response is only supported on MacOS so this comment is misleading.  It should say "For MacOS, use live response to run the action."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efb7742-1171-00f4-ab40-6bcc479078ca
* Version Independent ID: 9a79f573-5f20-0e4c-822e-8af4ebf65422
* Content: [Take response actions on a device in Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/respond-machine-alerts?view=o365-worldwide#isolate-devices-from-the-network)
* Content Source: [microsoft-365/security/defender-endpoint/respond-machine-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/respond-machine-alerts.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@eepyaich Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9656

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @eepyaich Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
