### ISSUE TITLE
Last activity date (UTC) does not reflect Teams channel conversations?

### ISSUE THREAD

**Issue by TuomasPakkanen** [MicrosoftDocs/microsoft-365-docs#9612]
The documentation describes the following:
Last activity date (UTC) | The latest date a message was received by the group. - This is the latest date an activity happened in an email conversation, Yammer, or the Site.

Is it so that the last activity date field is NOT updated for example if somebody posts a channel message to the Teams workspace of that group? We are utilizing this info in our custom archival scripts and I assume there can be various Teams that only get activity in the messaging side on channels, but not at all in email/yammer (alternative communication platforms of the m365 group) or necessarily the SharePoint site (file edits?).

As general feedback, hopefully this can be improved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d43b01f-5c1e-515a-900a-7aab927c294e
* Version Independent ID: 23b1fc80-9d25-c9fb-2600-3d91b11b9063
* Content: [Microsoft 365 admin center groups reports - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/activity-reports/office-365-groups-ww?redirectSourcePath=%252fen-us%252farticle%252foffice-365-reports-in-the-admin-center-office-365-groups-a27f1a99-3557-4f85-9560-a28e3d822a40&view=o365-worldwide)
* Content Source: [microsoft-365/admin/activity-reports/office-365-groups-ww.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/activity-reports/office-365-groups-ww.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@TuomasPakkanen Thank you for your feedback. That is correct, it only captures the latest date an activity happened in an email conversation, Yammer, or the Site. I'd recommend you leave the feedback on our main feedback portal - https://feedbackportal.microsoft.com/ so that our dev/product team can review and provide the reason why this is not available or if it is in the roadmap.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@TuomasPakkanen Thank you very much for your kind feedback. Considering your valuable feedback, please log this issue as advised. Here we are limited to documentation fixes and improvements only. Concerning team will evaluate and take the appropriate action, as per their schedule. We proceed here to close it. Thanks again for taking out some time and sharing your feedback.
