### ISSUE TITLE
Clicking on 'Export results > Download all results' and nothing is happening 

### ISSUE THREAD

**Issue by oshihirii** [MicrosoftDocs/microsoft-365-docs#9618]
I have 150 results from Audit Log Search for activities of type 'when a SharePoint List column is created'.  

I click on `Export` > `Download all results` and nothing happens.  

Microsoft Edge
Version 105.0.1343.27 (Official build) (64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#audited-activities)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@oshihirii Thank you for your feedback. I was able to test and download the result to CSV, this sounds more like a technical issue in the tenant and I'd recommend you create a support ticket via the need help section on the admin center so that a support engineer can fix this issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @oshihirii Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
