### ISSUE TITLE
endpoint

### ISSUE THREAD

**Issue by keonglee1978** [MicrosoftDocs/microsoft-365-docs#9620]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd333ae2-34f6-4afd-cdb1-db72303a5736
* Version Independent ID: 5fc52fe8-dade-b8b7-7126-c4e7dd902e62
* Content: [Office 365 IP Address and URL web service - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-ip-web-service.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-ip-web-service.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@keonglee1978 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
