### ISSUE TITLE
office 

### ISSUE THREAD

**Issue by thomas656112** [MicrosoftDocs/microsoft-365-docs#9626]

**Comment by denisebmsft** [comment]
Hello @thomas656112. Do you have feedback on an article? We didn't receive any details.

**Comment by yogkumgit** [comment]
@thomas656112 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
