### ISSUE TITLE
Broken link to "Understand tenant isolation"

### ISSUE THREAD

**Issue by KenEdwardsMMIST** [MicrosoftDocs/microsoft-365-docs#9627]
The link to "[Understand tenant isolation](https://docs.microsoft.com/en-us/microsoft-365-isolation-in-microsoft-365?view=o365-worldwide&preserve-view=true)" is giving a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e68cccb-7e47-fbca-5fa1-8d84fc71929f
* Version Independent ID: 1624f271-ab0e-582d-b71c-2d0f1fcdcfef
* Content: [Tenant roadmap for Microsoft 365 - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/tenant-roadmap-microsoft-365?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/enterprise/tenant-roadmap-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/tenant-roadmap-microsoft-365.md)
* Service: **o365-solutions**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@KenEdwardsMMIST Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9657

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @KenEdwardsMMIST Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
