### ISSUE TITLE
Clarification on what happens to quarantined ODSP content

### ISSUE THREAD

**Issue by PaulRNewell** [MicrosoftDocs/microsoft-365-docs#9629]
Hi there, 
My understanding is that any content from OneDrive or SharePoint (ODSP) which is quarantined by Safe Attachments will _not_ be deleted after 30 days (like with email). The quarantined content will leave the quarantine view, but the files will remain in their blocked state in the ODSP repository. 
I think it would be helpful to add that note into the [Use the Microsoft 365 Defender portal to manage quarantined files in Defender for Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-manage-quarantined-files-in-defender-for-office-365) section of the [Manage quarantined messages and files as an admin in EOP](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide) article, and/or adding a note in the table of the [Quarantined email messages in EOP and Defender for Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/quarantine-email-messages?view=o365-worldwide) article. 

If there are any questions please contact me on corpnet - my alias is paulnew. 
Thank you for your time and assistance! 

Paul Newell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f14e1cc7-d9ef-c137-eb9d-802d13892ca8
* Version Independent ID: 7b85d938-ab88-20c5-d56a-340b34926271
* Content: [Manage quarantined messages and files as an admin - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/manage-quarantined-messages-and-files.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. Note added per referenced PR.

Thanks for the feedback.

Closing
