### ISSUE TITLE
Monitoring communication and files shares outside my organisation

### ISSUE THREAD

**Issue by stephane0smith** [MicrosoftDocs/microsoft-365-docs#963]
Good day,

Let say I want to monitor one of my business user that joined a private Teams Chat outside my organisation and they are exchanging Data. Can I monitor what my Business user is exchanging via the Supervision policies in Office 365 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46314027-e916-00f1-fe69-f41d4ad73213
* Version Independent ID: fbf037d0-a5d9-a479-137c-176547dbb4f7
* Content: [Supervision policies - Office 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/supervision-policies)
* Content Source: [microsoft-365/compliance/supervision-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/supervision-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by mypil** [comment]
@stephane0smith - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
