### ISSUE TITLE
Teams messages are never stored in Exchange Online

### ISSUE THREAD

**Issue by 12Knocksinna** [MicrosoftDocs/microsoft-365-docs#9634]
Despite what this page proclaims several times, Teams messages are never stored in Exchange Online. They are always stored in Azure Cosmos DB. Teams compliance records captured by the substrate are in Exchange Online. The compliance records are cut-down mail items designed to store metadata and content for Teams messages for use by compliance solutions, but they are not the Teams messages.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb41d287-f954-dc84-782c-de8fa3c1ea0d
* Version Independent ID: 0081aa8b-87dd-aef2-aaeb-61caa8f20351
* Content: [Teams workflow in eDiscovery (Premium) - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/teams-workflow-in-advanced-ediscovery.md)
* Service: **o365-seccomp**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by msbemba** [comment]
@12Knocksinna Thank you for your feedback. Since this discovery workflow, I have added a statement that the data available in exchange online is only for compliance purposes and the actual data is stored in Azure Cosmos DB.

This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9700

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @12Knocksinna Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
