### ISSUE TITLE
Wrong product reference

### ISSUE THREAD

**Issue by ediemerson-br** [MicrosoftDocs/microsoft-365-docs#9639]
The sentence below should reference Microsoft Defender for Cloud, not for Endpoint.

Microsoft Defender for **Endpoint** provides a comprehensive server protection solution, including endpoint detection and response (EDR) capabilities on Windows Servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881d6a41-be6c-430e-d4f3-26e08fa1bb50
* Version Independent ID: 5bb5aaaa-8d13-f3e1-52b1-3a043f7ff4fe
* Content: [Integrate Microsoft Defender for Endpoint with other Microsoft solutions](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/threat-protection-integration?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/threat-protection-integration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/threat-protection-integration.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@ediemerson-br Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9658

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @ediemerson-br Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
