### ISSUE TITLE
Priority in case of Sub-labels

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/microsoft-365-docs#964]
1. Is this priority also applicable to sub-labels?
2. Is there any limit on no. of labels to be created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb0c964d-2d1b-601a-c8a2-14378fc24fb8
* Version Independent ID: ee549bd1-0652-2167-0f23-d22a58cf895b
* Content: [Overview of sensitivity labels - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels)
* Content Source: [microsoft-365/compliance/sensitivity-labels.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@prashant1380  Yes, the priority also applies to sublabels. There is no limit to the number of sensitivity labels that you can create with one exception: If the label applies encryption, there is an upper limit of 500.  However, for ease of administration and as a best practice label design for your users, try to limit the number of labels so it's somewhere closer to just a handful.

**Comment by mypil** [comment]
@prashant1380 - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by cabailey so we will close this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by cabailey** [comment]
@prashant1380 The page is now updated for this additional information.
