### ISSUE TITLE
Internal takeover of Azure AD process broken

### ISSUE THREAD

**Issue by EthanB11** [MicrosoftDocs/microsoft-365-docs#9642]
Going to the link in Step 3 1. https://admin.microsoft.com results in being told I don't have permission to view the admin portal and now I have 2 members who are users in the unmanaged Azure Ad. The way this is architected is really stupid on Microsoft's part for creating this unmanaged tenant which is preventing me from adding my personal email account to Outlook. Great job Microsoft!!!!!

This link doesnt work either from [this page](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/domains-admin-takeover), same error, https://portal.office.com/admintakeover

```
Switch to an account that has permission
Your account (foo@bar.com) doesn’t have permission to view or manage this page in the Microsoft 365 admin center.

[Learn more about admin roles](javascript:void(window.open('https://docs.microsoft.com/en-US/microsoft-365/admin/add-users/about-admin-roles?view=o365-worldwide%27,%20%27_blank%27)))
[Sign out & switc](https://admin.microsoft.com/estslogout?ru=/adminportal/home/logout)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70907ca8-6aeb-c91e-f1c1-8f020d8fc2ac
* Version Independent ID: 367ae235-e297-225e-98af-a6198109f882
* Content: [Perform an internal admin takeover - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/misc/become-the-admin?view=o365-worldwide)
* Content Source: [microsoft-365/admin/misc/become-the-admin.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/misc/become-the-admin.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@EthanB11 Thank you for your feedback. These unmanaged tenants are created during the self-service user sign-up.  What you notice is unusual as the administrative takeover process is usually straightforward as described in the document. Suppose you still have an issue with the admin takeover process. In that case, I recommend contacting Microsoft support via the need help section on the admin center so that a support engineer can assist you with the process.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @EthanB11 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
