### ISSUE TITLE
Table columns messed up

### ISSUE THREAD

**Issue by Hindy-UK** [MicrosoftDocs/microsoft-365-docs#9643]
In the table for ‘Configure device proxy….’, the columns are messed up for the second EDR row. Minor issue too is that there is a missing ) after ‘(see System requirements’ for both macOS rows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 086801ff-9161-24ff-9cb9-17cf9219f173
* Version Independent ID: 499f382b-9a1b-b9a9-7203-5d6b46a5c164
* Content: [Switch to Microsoft Defender for Endpoint - Prepare](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-mde-phase-1?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-mde-phase-1.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-mde-phase-1.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@Hindy-UK Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9688

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Hindy-UK Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
