### ISSUE TITLE
Need clarity on DefaultSharingScope

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/microsoft-365-docs#9649]
[Enter feedback here]
Regarding How to configure settings for the default sharing link type- https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-default-sharing-link?view=o365-worldwide#how-to-configure-settings-for-the-default-sharing-link-type
What value should we add in powershell for the DefaultSharingScope when we want to select the scope as "People with existing access"? You have provided values only for following 3 options - 

- SpecificPeople: Sets the default sharing link for the site to the "Specific people" link
- Organization: Sets the default sharing link for the site to the "organization" link or company shareable link
- Anyone: Sets the default sharing link for the site to an Anonymous Access or Anyone link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a385c4-e299-39f9-cf2a-a45b4d2a07d2
* Version Independent ID: 48a385c4-e299-39f9-cf2a-a45b4d2a07d2
* Content: [Use sensitivity labels to configure the default sharing link type - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-default-sharing-link?view=o365-worldwide#how-to-configure-settings-for-the-default-sharing-link-type)
* Content Source: [microsoft-365/compliance/sensitivity-labels-default-sharing-link.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-default-sharing-link.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Investigating

**Comment by cabailey** [comment]
@bubhat  Thanks for flagging this.  This option was implemented differently, with its own advanced setting.  Docs are now updated to include this.
