### ISSUE TITLE
DLP in Teams

### ISSUE THREAD

**Issue by sgtdonny** [MicrosoftDocs/microsoft-365-docs#965]
Hi,
works good with chat but on channels only with additional location exchange. It's not mentioned in this articel.
Tested it, without exchange no DLP. After setting back to additional location exchange the new and old posts (2 minutes old before changing) are blocked.

**Comment by mypil** [comment]
@sgtdonny - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by sgtdonny** [comment]
That makes sense, https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-microsoft-teams

Cheers

Von: Joyce Y. <notifications@github.com>
Gesendet: Donnerstag, 19. Dezember 2019 19:13
An: MicrosoftDocs/microsoft-365-docs <microsoft-365-docs@noreply.github.com>
Cc: Patrick Clemens <patrick.clemens@adn.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/microsoft-365-docs] DLP in Teams (#965)


@sgtdonny<https://github.com/sgtdonny> - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by mypil** [comment]
@sgtdonny -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/7f0db2dcb7c4a478a1551dd695973e221919ff3c. 


Thank you for your contribution to make the docs better! Much appreciated!
