### ISSUE TITLE
we need guidance on the tenant migration and integration move along with power BI. can you support us through a call? or who can?

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/microsoft-365-docs#9651]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78fbba03-39f0-9d11-12b0-b57830942db8
* Version Independent ID: f14feef7-7041-5e60-c193-8eb480097511
* Content: [Microsoft 365 tenant-to-tenant migrations - Microsoft 365 Enterprise](https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/microsoft-365-tenant-to-tenant-migrations.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@jlabustro Thank you for your feedback. Since your request is for technical help, I'd suggest you contact Microsoft support via the need help section on the admin center so that a support engineer can schedule a call and work with you to provide guidance.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jlabustro Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
