### ISSUE TITLE
It would be nice if you mentioned aliases

### ISSUE THREAD

**Issue by cstirland** [MicrosoftDocs/microsoft-365-docs#9659]
[Enter feedback here]

Do I have to delete them first? Does removing the domain do that? I questions I had when I read this doc. Also maybe mention shared mailboxes and resources?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 780db236-9235-2ce7-acbb-953fd997215b
* Version Independent ID: a5b80ea1-fb9f-d381-4fa6-7d4d8cce3f82
* Content: [Remove a domain - Microsoft 365 admin](https://docs.microsoft.com/en-US/microsoft-365/admin/get-help-with-domains/remove-a-domain?WT.mc_id=365AdminCSH_inproduct&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-with-domains/remove-a-domain.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-with-domains/remove-a-domain.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@cstirland Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9692

Use the Microsoft 365 admin center to remove the domain. The Domain Manager in Microsoft 365 will help remove any dependencies that block domain removal. It includes aliases, shared mailboxes, resource mailboxes, groups, etc.

it takes more time if there are more references to the old domain.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @cstirland Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
