### ISSUE TITLE
Incorrect Statement

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/microsoft-365-docs#9660]
There's a statement toward the top of the page that reads:
"Retention settings from both retention policies and retention labels do not apply to organizing structures that include libraries, lists, and folders."

You later go on to discuss the Preservation Hold **Library**, which is specifically there to hold the items per the retention policy. So the first statement should be amended to exempt the Preservation Hold Library.

Additionally, throughout the documentation pages on SharePoint, OneDrive and other pages about data retention (including this article), you reference 30 days or 93 days. However, all of those are customizable time frames. So, you should really be specific that it is the time frame set in our tenants, and ideally include the link path to get to that setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b54827-f642-4c77-7cfe-64e8c2a1d1d9
* Version Independent ID: 67dffecf-4da7-864d-5c10-9b55740f32cd
* Content: [Learn about retention for SharePoint and OneDrive - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/retention-policies-sharepoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/retention-policies-sharepoint.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
@DontNeedNoGit Yes, the statement also applies to the Preservation Hold Library - Microsoft 365 retention settings don't retain or delete the Preservation Hold Library itself but apply to items in it.

I'm told it's not supported to change the 30/93 days for SharePoint/OneDrive, so they are not default values that can be customized per tenant. If you have a link that suggests otherwise, please share that.

**Comment by DontNeedNoGit** [comment]
Here in OneDrive:
https://TENANTNAME-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/settings/OrphanedPersonalSitesRetentionPeriod

I quickly found that one. I don't see SharePoint in there. So, maybe that can't be changed. I'd have to dig more, but ^ example shows that at a minimum, OneDrive is customizable. So, the source of your data that it cannot be changed "for SharePoint/OneDrive" is at least partially incorrect, and I would say invalidates that data point. I've got a super busy week, but I'll try to find a similar option for SharePoint if I find time.

**Comment by cabailey** [comment]
I think I see the confusion - you're referring to this scenario that supports the retention and deletion of OneDrive sites for deleted users? https://learn.microsoft.com/en-us/onedrive/retention-and-deletion 

That's a different scenario to the Microsoft 365 retention and deletion of individual items in SharePoint and OneDrive.  If you change those settings, they don't impact the 30/93 days mentioned here for individual items.  The long but helpful PowerShell parameter helps to clarify scope: "OrphanedPersonalSitesRetentionPeriod"

**Comment by cabailey** [comment]
I think we can close this now?  The numbers quoted on this page are accurate and can't be changed by configuring OneDrive settings for orphaned sites.
