### ISSUE TITLE
Two totally separate places for basically the same documentation?

### ISSUE THREAD

**Issue by IndigoHealth** [MicrosoftDocs/microsoft-365-docs#9664]
I'm using Microsoft Teams and Azure DevOps for project planning and communication. I decided to stop "stumbling around" and actually learn how to add, delete, and manage users on both platforms, so I did a Google search and found two apparently separate places where the Microsoft Teams Admin Center is documented:

[https://docs.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal](https://docs.microsoft.com/en-us/microsoftteams/manage-teams-in-modern-portal)
[https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview?view=o365-worldwide)

If these two online documents serve different purposes, then each should, at a minimum, provide an obvious link to the other document with an explanation of why I would want to read one vs. the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Version Independent ID: c4f0934a-bc5e-9516-ec42-082faed4675d
* Content: [Microsoft 365 admin center - Overview - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-center-overview?WT.mc_id=365AdminCSH_SupportCentral&view=o365-worldwide)
* Content Source: [microsoft-365/admin/admin-overview/admin-center-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/admin-overview/admin-center-overview.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@IndigoHealth Thank you for your feedback. You are right, both serve different purposes, The team's admin center is used only for managing Teams and other services within teams.

Whereas the M365 admin center is the central place to manage all services and subscriptions. 

I have added references to both via PR#https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/9312 and https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9694

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @IndigoHealth Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
