### ISSUE TITLE
This Page has one incorrect steps 

### ISSUE THREAD

**Issue by riteshm42** [MicrosoftDocs/microsoft-365-docs#9665]
[Microsoft showed 3 steps of creating 3 different tags. In the last and 3rd tag creation   of **Alpine Deleted Items 5 Years Delete and Allow Recovery** if you select "Automatically to entire default mailbox" this tag will not work is supposed to be. Instead the option "Automatically to default folders" should be selected and "delete items" folder should be selected under apply tag to this folder "]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e9c1f9-d22d-8c83-25bb-637f3121ef33
* Version Independent ID: b6c1f57d-978f-c959-ef0a-00ef1b9d9cab
* Content: [Customize an archive and deletion policy (MRM) for mailboxes - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/set-up-an-archive-and-deletion-policy-for-mailboxes.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@riteshm42 Yes, you're quite correct, not sure how this was missed before but a doc update is now in the pipeline to correct it.
