### ISSUE TITLE
New functionality to add to the Intelligent detections section

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9669]
There is some new functionality in Intelligent detections that is missing from this document. See Tech community document announcing new functionality https://techcommunity.microsoft.com/t5/security-compliance-and-identity/addressing-insider-risks-in-an-increasingly-complex-data/ba-p/3569047

**File path exclusions**
File paths here map to device indicators related to copying or moving files, such as moving files to a system folder or network share path. Activity involving these file paths will be ignored by your policies and won't generate alerts.
Example: excluding a file path on an endpoint that may be contributing towards noisy signals, which may include file paths like Filerename or Filedelete from temp folders

**Default file path exclusions**
These file paths are automatically excluded because activity in these file paths is typically expected and including them could potentially increase the volume of non-actionable alerts. If needed, you can clear these default exclusions.
Example:
![image](https://user-images.githubusercontent.com/69439002/189534052-65c73051-226d-4712-99a3-1ea831e0e542.png)

**Site exclusions**
Sites here map to indicators related to activity involving SharePoint sites (including sites associated with Team channels). Activity involving these sites will be ignored by your policies and won't generate alerts. Consider excluding sites that contain non-sensitive content that can safely be shared with internal and external stakeholders. Up to 500 sites can be added.
Example: excluding activities on a commonly used non-sensitive SharePoint, OneDrive and Teams sites from contributing to unnecessary alerts
![image](https://user-images.githubusercontent.com/69439002/189534038-97aae56a-65c6-49cc-86a8-41b189dfbe69.png)

**Keyword exclusion**
Keywords here will be ignored when detected in file names, file paths, or email subject lines. This can help reduce alerts for file and email activities that contain acceptable terms. You can exclude up to 500 keywords.
Example: excluding activities on an object that contains specific keywords such as paths that may contain “PublicMarketingMaterial”

![image](https://user-images.githubusercontent.com/69439002/189534032-73e9f5f2-8c02-47a1-90ac-774ab131d5a2.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Insider risk management settings - Microsoft Purview (compliance)](https://docs.microsoft.com/en-gb/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide#intelligent-detections)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@nikki-c - thanks for the feedback. This content was held up due to some internal processes but is now published.
