### ISSUE TITLE
Add Admin Audit Log

### ISSUE THREAD

**Issue by secabstraction** [MicrosoftDocs/microsoft-365-docs#967]
We need to add instructions for pulling configuration changes from the Admin Audit Log, because not all customers have Unified Audit Logging enabled. The Admin Audit Log is enabled by default for all customers. From reading many customer escalations regarding alerts sent to them about compromised accounts it's clear that instructions for querying these logs need to be moved further up in the documentation as attackers often set and remove their malicious configuration changes; leaving nothing to be found by investigators. This makes it appear as though we're sending false-positive alerts to customers. Traces of attacker actions still exist in the logs, so we should point customers there to identify root cause.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073882cd-36d0-b95a-77b2-aadd06fa34a5
* Version Independent ID: 463f2f77-3fb0-8078-5b49-878747f2842b
* Content: [Responding to a Compromised Email Account in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account#feedback)
* Content Source: [microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/responding-to-a-compromised-email-account.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by msbemba** [comment]
@secabstraction Thank you for the feedback. We have modified the document via PR #999 https://github.com/MicrosoftDocs/microsoft-365-docs/pull/999

Thanks
Sri

**Comment by mypil** [comment]
@secabstraction - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/a9c42f2b08c150b4d7d0444c32b6ec3e096f6e13 but it may take a few days for the merged content to appear in the doc. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!
