### ISSUE TITLE
Priority user groups is no longer in preview

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9670]
Priority user groups is no longer in preview

![image](https://user-images.githubusercontent.com/69439002/189534810-57826d1d-9f23-40b3-9054-ff44ff4807a9.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Insider risk management settings - Microsoft Purview (compliance)](https://docs.microsoft.com/en-gb/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide#intelligent-detections)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9698

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@nikki-c Closing it as per authors comment in PR. Thanks
