### ISSUE TITLE
New Risky browser usage (preview) policy type is missing on page

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9672]
Risky browser usage (preview) is now available. Message center changeMC409858. This is missing from this page

![image](https://user-images.githubusercontent.com/69439002/189538590-39b39452-17d2-4f44-bf0e-d4655be8ff5d.png)

**Risky browser usage (preview)**
This policy template allows admins to define, identify and detect high-risk browsing actions that may result in a security or compliance incident. These policies help organizations detect risky browsing actions based on specific high-risk website categories, such as malware, keylogging, and hacking websites. Insider Risk Management is built with privacy by design, users are pseudonymized by default, and role-based access controls and audit logs are in place to help ensure user-level privacy. 

Information on the Microsoft Purview extension is detailed here https://docs.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-browser-support?view=o365-worldwide
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3096e5de-0e2b-eb0e-850e-0cee9118078e
* Version Independent ID: 732f4433-84cb-43d5-131c-b21c358c7f99
* Content: [Insider risk management policies - Microsoft Purview (compliance)](https://docs.microsoft.com/en-gb/microsoft-365/compliance/insider-risk-management-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@nikki-c - thanks for the feedback. This content was held up due to some internal processes but is now published.
