### ISSUE TITLE
Request for confirming technical support hours for Other Plans

### ISSUE THREAD

**Issue by sasaito** [MicrosoftDocs/microsoft-365-docs#9674]
[Enter feedback here]
“Technical Support:” section mentions as follows:
Other Plans:
Telephone technical support is available from 9:00-17:30 on weekdays. For high severity issues, technical support is available 24 hours a day, 7 days a week.

Is it correct?
I would like to make it clear that the description “Telephone technical support is available from 9:00-17:30 on weekdays.” is still available for other plans such as  Microsoft 365 Business Basic, Standard, Premium and Microsoft 365 Apps for business.
Telephone technical support used to be available from 9:00-17:30 on weekdays for small mid plans, which was available before Microsoft 365 Business plan were released.
This article was described in Dec 09 2021 and I would like to confirm if the support hours for Other Plans have been still correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3618e4-be59-8a6f-92c8-cd915c63313d
* Version Independent ID: 9caeb339-7a2b-a2ce-4850-61896ea68825
* Content: [Support information for Japan - Microsoft 365 admin](https://docs.microsoft.com/en-us/microsoft-365/admin/support/japan?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/japan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/japan.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@sasaito Thank you for your feedback. You are correct. Technical support is available for all other plans (Excluding M365/O365 Enterprise) between 9-17:30 on weekdays. This includes M365 business basic, premium, and standard. 

For O365 and M365 enterprise plans technical support is available 24/7

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @sasaito Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
