### ISSUE TITLE
Microsoft Endpoint Configuration Manager does not support wildcards (* or ?)

### ISSUE THREAD

**Issue by jonconwayuk** [MicrosoftDocs/microsoft-365-docs#9675]
The statement/bullet in the FAQ that matches the title of this Issue is now incorrect I believe.

https://docs.microsoft.com/en-us/mem/configmgr/hotfix/2111/12896009#:~:text=The%20Configuration%20Manager%20console%20now%20allows%20wildcards%20when%20defining%20Microsoft%20Defender%20Attack%20Surface%20Reduction%20(ASR)%20rules.

Update rollup for Microsoft Endpoint Configuration Manager version 2111 appears to address this (KB12896009) (https://docs.microsoft.com/en-us/mem/configmgr/hotfix/2111/12896009#summary-of-kb12896009)

In summary, it looks as if ConfigMgr does now support wildcard entries in ASR rules.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ad81808-0605-037f-364e-9d061d593078
* Version Independent ID: 62044527-8d7e-3dea-d872-83638fe7b14c
* Content: [Attack surface reduction frequently asked questions (FAQ)](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/attack-surface-reduction-faq.yml](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/attack-surface-reduction-faq.yml)
* Product: **m365-security**
* Technology: **mde**
* GitHub Login: @martyav
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@jonconwayuk Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9696

Once the author approves,  the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jonconwayuk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
