### ISSUE TITLE
There is no Custom tab on Anti-spam settings page

### ISSUE THREAD

**Issue by ephemeraldrive** [MicrosoftDocs/microsoft-365-docs#968]
In reference to the section 'To manage senders who are spoofing your domain by using the Security & Compliance Center', item 4 insists on selecting the Custom tab on the Anti-spam settings page in the right pane. As of December 2019, the Custom tab doesn't exist. The screenshot would have to be refreshed too, I guess

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c0cbdb-062e-08e1-7c7c-cedab550f01b
* Version Independent ID: 2791a840-3284-bc0d-7b9e-026b852797e6
* Content: [Learn more about spoof intelligence - Office 365](https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/learn-about-spoof-intelligence#feedback)
* Content Source: [microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/learn-about-spoof-intelligence.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by mypil** [comment]
@ephemeraldrive -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/0f1a19d1f9a332b655284a7a4ffbf05a9925aa72. 


Thank you for your contribution to make the docs better! Much appreciated!
