### ISSUE TITLE
Variable List Correction

### ISSUE THREAD

**Issue by mtariqkhanIT** [MicrosoftDocs/microsoft-365-docs#9684]
[Enter feedback here]
The %LOCALAPPDATA%  variable on this page is redirected to C:\Windows\System32\config\systemprofile\AppData\Local but when I use this variable on my system(s) it takes me to the C:\Users\USERNAME\AppData\Local folder instead.

Please make the correction.,

Thanks
TK
-- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87906607-83fd-8dc8-facb-89719390f824
* Version Independent ID: 92f3359d-84ac-90c3-33d5-513feffc4173
* Content: [Configure and validate exclusions based on extension, name, or location](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus?view=o365-worldwide#system-environment-variables)
* Content Source: [microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-extension-file-exclusions-microsoft-defender-antivirus.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@mtariqkhanIT Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9740

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mtariqkhanIT Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
