### ISSUE TITLE
Descriptive link names

### ISSUE THREAD

**Issue by DavidApps2** [MicrosoftDocs/microsoft-365-docs#969]
Please use descriptive link names for all your content. Link names such as "here" are not descriptive for a screen reader user navigating the links on a page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4350fc6-0826-830b-bbb4-c585839570dc
* Version Independent ID: 4e3f696b-0ef3-a7ef-622b-d9c07fab1b94
* Content: [Service encryption with Customer Key for Office 365 FAQ - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/service-encryption-with-customer-key-faq#feedback)
* Content Source: [microsoft-365/compliance/service-encryption-with-customer-key-faq.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/service-encryption-with-customer-key-faq.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@DavidApps2 - Thank you for pointing this out.

PR #982 has been created by @JohanFreelancer9  to fix and close this issue once the PR is merged.

Thank you and we appreciate your contribution to make the docs better!

**Comment by mypil** [comment]
@DavidApps2 - Please see the response from the author on this https://github.com/MicrosoftDocs/microsoft-365-docs/pull/982#issuecomment-586504951.

We hope this helps to address your issue. 

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by DavidApps2** [comment]
Thank you.
