### ISSUE TITLE
Image error in italian version

### ISSUE THREAD

**Issue by grex86** [MicrosoftDocs/microsoft-365-docs#9693]
in the italian version the image has a big error: 
instead P1 the translator output is "Pi.greco" and obviously it makes no sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3369738b-f096-6c2e-22d4-ee79057997c7
* Version Independent ID: d3fce773-a1e8-193a-b4fa-7f71b9ac3ea4
* Content: [Office 365 Security including Microsoft Defender for Office 365 and Exchange Online Protection - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/overview?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/overview.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@MartinOersted Please help us here. Thanks

**Comment by tiburd** [comment]
This article has been updated recently. Currently, it does not include an image.
Closing this issue.
