### ISSUE TITLE
Security Intelligence Updates / Platform Updates

### ISSUE THREAD

**Issue by rfellmann** [MicrosoftDocs/microsoft-365-docs#9707]
"Security intelligence updates contain engine updates and are released on a monthly cadence. Security intelligence updates are also delivered multiple times a day, but this package doesn't contain an engine."

--> Shouldn't it say "Platform Updates contain engine updates and are released on a monthly cadence." ?

**Comment by denisebmsft** [comment]
Hello @rfellmann, and thank you for the feedback. Are you referring to this article: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-protection-updates-microsoft-defender-antivirus?view=o365-worldwide

**Comment by rfellmann** [comment]
Hi Denise, yes that's the one.

**Comment by msbemba** [comment]
@rfellmann Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9742

Once the author approves the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @rfellmann Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
