### ISSUE TITLE
Japanese language localization issue

### ISSUE THREAD

**Issue by morrow233** [MicrosoftDocs/microsoft-365-docs#9710]
[Enter feedback here]

There is a localization issue in Japanese.
https://docs.microsoft.com/ja-jp/microsoft-365/security/defender-endpoint/web-threat-protection?view=o365-worldwide

[Now]
Web 驚異から組織を保護する
Means "Protect your organization against amazing web"

[Should be]
Web 脅威から組織を保護する
Protect your organization against web threats

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4489c89-f34a-b0d5-4e6d-edbe29e6d4e6
* Version Independent ID: 6587d8f8-855e-8e8d-1e8a-f34492825d54
* Content: [Protect your organization against web threats](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/web-threat-protection?view=o365-worldwide&source=docs#configure-web-threat-protection)
* Content Source: [microsoft-365/security/defender-endpoint/web-threat-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/web-threat-protection.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by yogkumgit** [comment]
@MartinOersted Please help us here. Thanks

**Comment by MartinOersted** [comment]
Hi,

Can I ask you to please log a bug via the [Global Services Hub](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fglobalservices.powerappsportals.com%2FGlobal%2F&data=05%7C01%7Ctinamc%40exchange.microsoft.com%7C4f2b9fb1b0ed43511e9e08da69271700%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637937913870816942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TtVS0poPfsdVgMXcgJIDn0CCuSMvq0d9ZB2MP37gRj0%3D&reserved=0) using this [link](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2FGlobalCollaborationService%2FGlobal%2520Collaboration%2520Service%2520Project%2F_workitems%2Fcreate%2FBug&data=05%7C01%7Ctinamc%40exchange.microsoft.com%7C4f2b9fb1b0ed43511e9e08da69271700%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637937913870816942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0zVuNeIOdsddheQu5JNUSZeOBye%2BrCQY8lQv0TaLB54%3D&reserved=0)?
 
A few notes for logging Docs content bugs:
o	You can leave the Assigned To field blank. The localization suppliers are constantly triaging new bugs and will assign to the correct person to fix.
o	Please @mention me in the bug so I can monitor it.
o	Set Area = Global Collaboration Service Project\Global\Content\Support\Technical Content - IT Pro (formerly TechNet)
o	Set Iteration = Global Collaboration Service Project\Unspecified
o	Set Product Area = UA – TechCon

Kind regards
Martin

**Comment by MartinOersted** [comment]
@yogkumgit: Hi Yogesh, please see above for logging a bug about the issue
Kind regards
Martin
