### ISSUE TITLE
Possible values for onboardingstatus are not correct

### ISSUE THREAD

**Issue by WilfridBlanc** [MicrosoftDocs/microsoft-365-docs#9711]
Hi, 
The possible values provided for the `onboardingstatus` of machines seems not relevant:
- current values provided in the documentation are `onboarded` and `offboarded` 
- sample of values retrieved from the API include `CanBeOnboarded`, `Unsupported`, `InsufficientInfo`, `Onboarded`

Can you please update the document with the right possible values?

Thanks in advance!
Wilfrid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71010864-b3f8-23e1-33fe-496f136bf2b7
* Version Independent ID: e4c58cda-d42f-4445-3a03-6f4c8c1e6460
* Content: [Machine resource type](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine?view=o365-worldwide#properties)
* Content Source: [microsoft-365/security/defender-endpoint/machine.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@WilfridBlanc Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9743

Once the author approves,  the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @WilfridBlanc Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
