### ISSUE TITLE
Buy or remove licenses for your business subscription

### ISSUE THREAD

**Issue by XXLMandalorian013** [MicrosoftDocs/microsoft-365-docs#9712]
[Enter feedback here]

Hello,

I was looking into getting an Azure P2 license and I found this section a bit confusing. Currently Step 1 states,

1. In the admin center, go to the Billing > [Your products](https://go.microsoft.com/fwlink/p/?linkid=842054) page.

Maybe at one time it used to have the ability to view all current and possible software purchases to buy in the same area, but now the "your products" tab in billing just shows what you currently sub to.

I think step one should say,

1. In the MAC,  to removed a license go to ["your products"](https://admin.microsoft.com/AdminPortal/Home#/subscriptions) or to purchase a new product go to  ["Purchase services"](https://admin.microsoft.com/AdminPortal/Home#/catalog)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d944ed69-220c-cb69-5e74-8e42a300d1e1
* Version Independent ID: b2184ca8-a2be-398d-9dcb-d38ba1009845
* Content: [Buy or remove licenses](https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/buy-licenses?view=o365-worldwide&preserve-view=true)
* Content Source: [microsoft-365/commerce/licenses/buy-licenses.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/licenses/buy-licenses.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@XXLMandalorian013 Thank you for your feedback. You are correct with respect to adding a new subscription. However, this document talks about buying more licenses or reducing the number of licenses for your existing subscriptions.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba  Thank you very much for the contribution and sharing this explanation. @XXLMandalorian013 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
