### ISSUE TITLE
Capped at 10,000 records

### ISSUE THREAD

**Issue by maxst33l** [MicrosoftDocs/microsoft-365-docs#9713]
I am attempting to consume this data into splunk for compliance reporting, and it appears that although it clearly states "This method is best for small organizations with less than 100-K devices." which we are under that number, only 10,000 records are exported.  
It also states "The response is paginated, so you can use the @odata.nextLink field from the response to fetch the next results." which clearly seems inaccurate as in the response there is no odata.nextLink field available to use to get the next 10,000 records.
I need this information ASAP, what can I do?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9849a2ea-ad01-d8ab-f03a-6f8b256c22bb
* Version Independent ID: 9849a2ea-ad01-d8ab-f03a-6f8b256c22bb
* Content: [Microsoft Defender Antivirus export device antivirus health details API methods and properties](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-health-api-methods-properties?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-health-api-methods-properties.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-health-api-methods-properties.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by marysiakam9889** [comment]
Hi, the engineering team is aware of the missing @odata.nextLink field and are working to add these changes.

**Comment by maxst33l** [comment]
Is there any idea of implementation date?  This data is exactly what was missing from MDE.

**Comment by marysiakam9889** [comment]
You should be able to see the change within a week.

**Comment by maxst33l** [comment]
Fantastic news!!

**Comment by msbemba** [comment]
Thank you for your feedback @maxst33l Once our engineering team adds the @odata.nextLink field the issue should be resolved and no changes will be needed in the document.

@marysiakam9889 Let us know if you would like us to make any changes to the document.

Thanks
Sri

**Comment by yogkumgit** [comment]
@maxst33lIf you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by maxst33l** [comment]
well technically until it is fixed the documentation is incorrect.  is it really in the best interest to close this, or would it be better to wait until the fix is in.  this would allow myself and others to know that it's still not corrected.

**Comment by maxst33l** [comment]
> You should be able to see the change within a week.

@marysiakam9889 do you know if there as a KQL/adv hunting query that can also obtain the same data found in this api call?

**Comment by maxst33l** [comment]
Has there been any traction on this?

**Comment by maxst33l** [comment]
Just tried it and I see the odata next option, but are we sure it's working as expected?
https://api.securitycenter.microsoft.com/api/deviceavinfo?$skip=10000
https://api.securitycenter.microsoft.com/api/deviceavinfo?=10000&$skip=10000
https://api.securitycenter.microsoft.com/api/deviceavinfo?=10000&=10000&$skip=10000
https://api.securitycenter.microsoft.com/api/deviceavinfo?=10000&=10000&=10000&$skip=10000
