### ISSUE TITLE
Unable to find the control for warnings on Smartscreen

### ISSUE THREAD

**Issue by lkchild** [MicrosoftDocs/microsoft-365-docs#9717]
Hi,

In the smartscreen section, the following instruction "From the Microsoft 365 Defender portal, navigate to the path to the ConfigToolName." does not make sense.  Can you please highlight where to look.

Thanks,
Lauren

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395141e8-be91-e226-24d7-dc136b8f9c5e
* Version Independent ID: 012beed4-1fdb-4f59-9cc4-53ba5e2c8ea2
* Content: [Use network protection to help prevent connections to bad sites](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/network-protection?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/network-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/network-protection.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks

**Comment by denisebmsft** [comment]
@lkchild thank you so much for posting this issue. Good catch! I've updated the article and hopefully it will make more sense now. It's with an indicator that you'd unblock SmartScreen with network protection. I hope this helps! You'll see the updates live on the site later today (at around 4 p.m. Pacific Time). Thank you again for letting us know about this issue, and I hope you have a great week!
