### ISSUE TITLE
Document correction/ comment

### ISSUE THREAD

**Issue by peterjoinobits** [MicrosoftDocs/microsoft-365-docs#9719]
Hi 
 This document  which is a really great read by the way doesn’t mention the one other configuration that prevent you from opening an RMS protected document sent to from a 3rd party and that is the implementation of tenant restrictions on your on prem proxy servers….. This has tripped me up several times…

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e781ec1-a886-964d-e358-f40b034c065f
* Version Independent ID: 3e781ec1-a886-964d-e358-f40b034c065f
* Content: [Azure AD configuration for content encrypted by Microsoft Purview Information Protection - Microsoft Purview (compliance)](https://docs.microsoft.com/en-us/microsoft-365/compliance/encryption-azure-ad-configuration?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/encryption-azure-ad-configuration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/encryption-azure-ad-configuration.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @peterjoinobits  Thanks for your positive feedback!  The scope of this article is AD configurations.  Are you talking about network infrastructure requirements that we document here https://docs.microsoft.com/en-us/azure/information-protection/requirements#firewalls-and-network-infrastructure?  I'm not sure exactly what you mean by "tenant restrictions" on the proxy servers.

**Comment by peterjoinobits** [comment]
It's not strictly an AAD configuration issue but it does impact authentication and hence could cause problems

Peter Johnson | Senior Cloud Infrastructure ***@***.*** | +27 83 306 0019 | http://www.inobits.com

1.This email disclaimer applies to the original email, all attachments and any subsequent emails sent by Netsurit (Pty) Ltd (“the Company”). 2. This e-mail is intended only for the named person or entity to which it is addressed and contains valuable business information that is privileged, confidential and/or otherwise protected from disclosure. If you received this e-mail in error, any review, use, dissemination, distribution, printing or copying of this e-mail is strictly prohibited and may be unlawful and / or an infringement of copyright. Please notify us immediately of the error via e-mail to ***@***.*** and delete the e-mail from your system, retaining no copies in any media. 3. No employee or agent is authorized to conclude any binding agreement on behalf of the Company with another party or give any warranty by email without express written confirmation by an authorized representative or a director of the Company and nothing in this email shall be construed as a legally binding agreement or warranty or an offer to contract. The Company will not be responsible for any damages suffered by the recipient as a result of the recipient not taking cognisance of this principle. 4. Please note that the recipient must scan this e-mail and any attached files for viruses and the like. The Company accepts no liability of whatever nature for any loss, liability, damage or expense resulting directly or indirectly from the access of any files which are attached to this message. 5. Views and opinions are those of the sender unless clearly stated as being that of the Company's. 6. Any email addressed to the Company shall only be deemed to have been received once receipt is confirmed by the Company orally or in writing. An automated acknowledgment of receipt will not suffice as proof of receipt by the Company. 7. This email disclaimer shall be governed by the laws of South Africa.

You can view our Privacy Notice: https://netsurit.com/en-za/wp-content/uploads/sites/4/2021/08/Netsurit-Privacy-Notice.pdf
   
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cabailey** [comment]
@peterjoinobits Interesting - I haven't heard of a proxy configuration where you specify tenant GUIDs (only ports & URLs). Can you share a link for more info?

**Comment by peterjoinobits** [comment]
Hi

Here you go: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/tenant-restrictions#proxy-configuration-and-requirements

Peter Johnson | Senior Cloud Infrastructure ***@***.*** | +27 83 306 0019 | http://www.inobits.com

1.This email disclaimer applies to the original email, all attachments and any subsequent emails sent by Netsurit (Pty) Ltd (“the Company”). 2. This e-mail is intended only for the named person or entity to which it is addressed and contains valuable business information that is privileged, confidential and/or otherwise protected from disclosure. If you received this e-mail in error, any review, use, dissemination, distribution, printing or copying of this e-mail is strictly prohibited and may be unlawful and / or an infringement of copyright. Please notify us immediately of the error via e-mail to ***@***.*** and delete the e-mail from your system, retaining no copies in any media. 3. No employee or agent is authorized to conclude any binding agreement on behalf of the Company with another party or give any warranty by email without express written confirmation by an authorized representative or a director of the Company and nothing in this email shall be construed as a legally binding agreement or warranty or an offer to contract. The Company will not be responsible for any damages suffered by the recipient as a result of the recipient not taking cognisance of this principle. 4. Please note that the recipient must scan this e-mail and any attached files for viruses and the like. The Company accepts no liability of whatever nature for any loss, liability, damage or expense resulting directly or indirectly from the access of any files which are attached to this message. 5. Views and opinions are those of the sender unless clearly stated as being that of the Company's. 6. Any email addressed to the Company shall only be deemed to have been received once receipt is confirmed by the Company orally or in writing. An automated acknowledgment of receipt will not suffice as proof of receipt by the Company. 7. This email disclaimer shall be governed by the laws of South Africa.

You can view our Privacy Notice: https://netsurit.com/en-za/wp-content/uploads/sites/4/2021/08/Netsurit-Privacy-Notice.pdf
   
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cabailey** [comment]
Thanks for sharing - I'll look at adding a link to that helpful article

**Comment by peterjoinobits** [comment]
What I meant was that if you have enabled tenant restrictions on your proxy servers which is a way to control which tenants, based on the tenantid guid,  your users behind the proxy may not be able to authenticate against the sender's tenant and hence won't be able to open a protected document

Peter Johnson | Senior Cloud Infrastructure ***@***.*** | +27 83 306 0019 | http://www.inobits.com

1.This email disclaimer applies to the original email, all attachments and any subsequent emails sent by Netsurit (Pty) Ltd (“the Company”). 2. This e-mail is intended only for the named person or entity to which it is addressed and contains valuable business information that is privileged, confidential and/or otherwise protected from disclosure. If you received this e-mail in error, any review, use, dissemination, distribution, printing or copying of this e-mail is strictly prohibited and may be unlawful and / or an infringement of copyright. Please notify us immediately of the error via e-mail to ***@***.*** and delete the e-mail from your system, retaining no copies in any media. 3. No employee or agent is authorized to conclude any binding agreement on behalf of the Company with another party or give any warranty by email without express written confirmation by an authorized representative or a director of the Company and nothing in this email shall be construed as a legally binding agreement or warranty or an offer to contract. The Company will not be responsible for any damages suffered by the recipient as a result of the recipient not taking cognisance of this principle. 4. Please note that the recipient must scan this e-mail and any attached files for viruses and the like. The Company accepts no liability of whatever nature for any loss, liability, damage or expense resulting directly or indirectly from the access of any files which are attached to this message. 5. Views and opinions are those of the sender unless clearly stated as being that of the Company's. 6. Any email addressed to the Company shall only be deemed to have been received once receipt is confirmed by the Company orally or in writing. An automated acknowledgment of receipt will not suffice as proof of receipt by the Company. 7. This email disclaimer shall be governed by the laws of South Africa.

You can view our Privacy Notice: https://netsurit.com/en-za/wp-content/uploads/sites/4/2021/08/Netsurit-Privacy-Notice.pdf
   
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
