### ISSUE TITLE
Clarify when forwarding takes place

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/microsoft-365-docs#9721]
Can someone please clarify in the documentation when external forwarding of an mailbox takes place (using Set-Mailbox -FowardingSmtpAddress)? Does it take place in step 3 or in/after step 4?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8878304-7f4b-15c3-d2b6-8a5583930199
* Version Independent ID: 329f3b45-a087-6743-0664-e74dd9e0fc46
* Content: [Exchange Online Protection (EOP) overview - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/exchange-online-protection-overview?source=recommendations&view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/exchange-online-protection-overview.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/exchange-online-protection-overview.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JonesMikael, those steps are for incoming mail flow. Mailbox forwarding is by definition outgoing mail flow.

So, I don't think there's any real comparison or place to insert mailbox forwarding, since it's going in a different direction.

**Comment by JonesMikael** [comment]
@chrisda thanks for quick response. I agree with you if the email would be internal. But consider the example where you have a mailbox with e-mail address sales@contoso.com and you enable forwarding of this mailbox to an external email address, for example to a hosted CRM system at crm@hosted.com.

What I want to understand if that step 4 (Content Filtering) takes place before the email is forwarded or not.

This would make a huge different in the amount of spam that would reach crm@hosted.com.

**Comment by chrisda** [comment]
@JonesMikael, your best way forward is to open a support ticket and ask your question. If they give you something that you think would help the documentation, then report back here.

**Comment by yogkumgit** [comment]
@JonesMikael Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
