### ISSUE TITLE
Microsoft 365 Business Premium (Exchange Only) clarification

### ISSUE THREAD

**Issue by Priscilla-C** [MicrosoftDocs/microsoft-365-docs#9724]
Microsoft 365 Business Premium (Exchange Only) appears in the list of licensing for eDiscovery (Standard) on the [Microsoft 365 Guidance for Security & Compliance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-13) but does not feature on this page. It also features on the [Microsoft 365 Business Plan Comparison for SMB - 1 April 2022](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWR6bM) and [Microsoft 365 Compliance Licensing Comparison](https://docs.microsoft.com/en-us/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.xlsx) with Content Search and Advanced eDiscovery Export (download, export, add to another review set) rights under Discover & Respond which links to [Overview of Microsoft Purview eDiscovery (Premium)](https://docs.microsoft.com/en-us/microsoft-365/compliance/overview-ediscovery-20?view=o365-worldwide#exporting-data-for-review-and-presentation). Could this please be made clear?

**Comment by msbemba** [comment]
@Priscilla-C Thank you for your feedback. We have updated the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9758

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @Priscilla-C Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
