### ISSUE TITLE
Incorrect example `mdatp health` output when kernel extension is missing

### ISSUE THREAD

**Issue by JeffreyLeeExient** [MicrosoftDocs/microsoft-365-docs#9727]
The page says "You can also run `mdatp health`. It reports if real-time protection is enabled but not available. This indicates that the kernel extension isn't approved to run on your device."

And the page shows the following example output:

```
...
real_time_protection_enabled                : false
real_time_protection_available              : true
...
```

But the two values in the output have the opposite state to what the text above suggests; `_enabled` should be true and `_available` should be false (as observed on my machine when I had to authenticate the extension earlier today)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90bb27ba-56ae-0d45-e28c-0a5bab019fa3
* Version Independent ID: 0afbb2e6-7601-bbfe-3bdc-0f45f615ad16
* Content: [Troubleshoot kernel extension issues in Microsoft Defender for Endpoint on macOS](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-support-kext?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mac-support-kext.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mac-support-kext.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@JeffreyLeeExient Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9744

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JeffreyLeeExient Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
