### ISSUE TITLE
ConfigMgr cannot enable ASR rules on server OSes

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/microsoft-365-docs#9729]
Per a support case I've had recently, there is a known issue where ConfigMgr cannot set ASR rules on server OSes:
"We have analyzed the logs you provided and have determined that they match a known issue the Product Group is currently aware of and working on. This refers specifically to the applicability of Attack Surface Reduction on Server OS versions which is marked as compliant without any actual enforcement. There is currently no ETA for when this will be fixed"

This document currently makes no mention of this known issue, I think it would be worth adding this to make it clear as currently there's nothing to state that this isn't a supported and functional scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a360dd4-bb59-9f48-b182-8eaaf9e20a82
* Version Independent ID: 54c5dde8-f8f1-4dd3-5408-12d2dc480970
* Content: [Enable attack surface reduction rules](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @jweston-1
* Microsoft Alias: **v-jweston**

**Comment by msbemba** [comment]
@CaptainUnlikely Thank you for your feedback. This issue has been escalated to the Engineering team and they are working on a fix. The document talks about the design and how the product should work. So we usually do not document bugs/design issues in the document unless it is unresolvable.

Hope this helps!

Thanks
Sri

**Comment by CaptainUnlikely** [comment]
Hi Sri,
Right now there is no way for a customer such as myself to know that this functionality doesn't work other than trying it out and opening a support case when it doesn't work only to be told that this is a known issue.
I understand the docs should cover how the product is supposed to work and can't cover every possible scenario but as I'm told there is no ETA for this to be fixed, to my mind this should be documented somewhere.
It doesn't impact me any more now that I'm aware of it, just trying to help avoid other customers and Microsoft wasting time with support tickets that are unnecessary when the cause is known.

**Comment by msbemba** [comment]
@CaptainUnlikely Thank you for your response. I have made suggested changes in the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9760

Once the author verifies and approves, the changes will be live.

Thanks
Sri

**Comment by jweston-1** [comment]
Approved.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @CaptainUnlikely Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
