### ISSUE TITLE
Latent Semantic Analysis (LSA) & Concepts

### ISSUE THREAD

**Issue by stevengwost** [MicrosoftDocs/microsoft-365-docs#973]
Please state explicitly the relationship between Themes and Concepts extracted via LSA.  If they're the same, there is a host of additional information online that we could use to better understand this feature.  If they're different, are there any substantive differences that would effect user-interaction or -understanding of Themes if they're familiar with LSA Concepts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5280a394-dc23-4891-eac2-ade0dfc381e0
* Version Independent ID: 3fd6ab16-717c-938e-e50a-dc7d1a9ac6b1
* Content: [Themes - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/themes#feedback)
* Content Source: [microsoft-365/compliance/themes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/themes.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@stevengwost Yes Themes are a result of LSA. The product group suggests that you open a ticket with MS Support for more information.
