### ISSUE TITLE
Splunk Link is outdated

### ISSUE THREAD

**Issue by AlexDeryabin** [MicrosoftDocs/microsoft-365-docs#9730]
Please update the Link for the Splunk Add-On. It shows the old Splunk Add-on that is deprecated.
Old: https://splunkbase.splunk.com/app/4959/
New: https://splunkbase.splunk.com/app/6207/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ce4374-498e-3b53-2338-d6d7040a58cb
* Version Independent ID: 871ec3e4-4a20-4a81-0f24-041034d23a9e
* Content: [Integrate your SIEM tools with Microsoft Defender for Endpoint](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-siem?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-siem.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-siem.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@AlexDeryabin Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9745

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AlexDeryabin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
