### ISSUE TITLE
Malicious Software Removal Tools Do Not Support All Claimed Operating Systems

### ISSUE THREAD

**Issue by KnownByBJs** [MicrosoftDocs/microsoft-365-docs#9733]
https://www.microsoft.com/en-us/download/details.aspx?id=16&WT.mc_id=MSCOM_EN_US_DLC_MODULE_131Z4ENUS21984
claims System Requirements "     Supported Operating System

    Windows Server 2008, Windows 10, Windows 7, Windows 8.1, Windows 10 Tech Preview
        Note: This tool must be run with local administrator privileges. "
but the downloaded package will not run on Windows (Genuine) Server 2008 (32 bit), complaining the operating system is not supported
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 286c4f73-ff88-3fdc-8673-47c11edd763b
* Version Independent ID: 286c4f73-ff88-3fdc-8673-47c11edd763b
* Content: [Microsoft Safety Scanner Download](https://docs.microsoft.com/en-us/microsoft-365/security/intelligence/safety-scanner-download?view=o365-worldwide)
* Content Source: [microsoft-365/security/intelligence/safety-scanner-download.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/intelligence/safety-scanner-download.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@KnownByBJs Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9759

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @KnownByBJs Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
