### ISSUE TITLE
This document is no longer correct

### ISSUE THREAD

**Issue by ckey1** [MicrosoftDocs/microsoft-365-docs#974]
As 2 users have already pointed out, the spam notifications have changed and no longer have the options that are explained on the document. Whoever closed those issues apparently misunderstood that they were complaining about the new change, hence the suggestion to post on uservoice. But the point is that this document is not correct. Please fix this document to match the current spam notifications after the change in MC191185/Roadmap ID 55102.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedcd379-0c7e-5b68-be04-e272ac53638d
* Version Independent ID: 664acd84-b4df-c943-e027-677f4340768e
* Content: [Use user spam notifications to release and report quarantined messages in Office 365 - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages)
* Content Source: [microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@ckey1, topic updated.

Thanks for the feedback.

Closing
