### ISSUE TITLE
Schema validation error

### ISSUE THREAD

**Issue by kevinlpeterson** [MicrosoftDocs/microsoft-365-docs#975]
Attempted to import the XML schema definition sample into my tenant with no modification and received this validation error:

EDM schema failed XML schema definition validation. Error details: The document namespace 'https://schemas.microsoft.com/office/2018/edm' 
is incorrect. Expected: 'http://schemas.microsoft.com/office/2018/edm'..
+ CategoryInfo          : NotSpecified: (:) [New-DlpEdmSchema], EdmSchemaInvalidDefinitionException

The supplied URL and expected appear to match so not sure why the validation fails?

**Comment by mypil** [comment]
@kevinlpeterson - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by kevinlpeterson** [comment]
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-custom-sensitive-information-types-with-exact-data-match-based-classification#part-1-set-up-edm-based-classification

Thanks

**Comment by mypil** [comment]
@kevinlpeterson - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.

If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
