### ISSUE TITLE
four broken links

### ISSUE THREAD

**Issue by MarkChristman** [MicrosoftDocs/microsoft-365-docs#9751]
In the Microsoft 365 Defender section (lines 46-68) there are four broken links. Three can be resolved by removing the .md extension (lines 54, 60, and 66). The fourth, line 51, `/microsoft-defender-endpoint.md` should be `/defender-endpoint`

**Comment by yogkumgit** [comment]
@MarkChristman Please indicate which document you are referring to. Thanks

**Comment by MarkChristman** [comment]
/defender/index.yml that ultimately drives the links on https://learn.microsoft.com/en-us/defender/

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@yogkumgit  I'm not able to edit the file https://learn.microsoft.com/en-us/defender/ and will need to be assigned to the author.

Thanks
Sri

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Links work
