### ISSUE TITLE
feature went GA, out dated doc

### ISSUE THREAD

**Issue by samkellyd** [MicrosoftDocs/microsoft-365-docs#9752]
[Hello, this went GA and needs updating https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/tamper-protection-on-macos-is-now-generally-available/ba-p/3595422]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b466be31-a444-e4f0-f56e-1b514776df63
* Version Independent ID: b466be31-a444-e4f0-f56e-1b514776df63
* Content: [Protect macOS security settings with tamper protection](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/tamperprotection-macos?view=o365-worldwide#before-you-begin)
* Content Source: [microsoft-365/security/defender-endpoint/tamperprotection-macos.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/tamperprotection-macos.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @samkellyd Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
