### ISSUE TITLE
Please provide a link to overcome issue 'Cannot connect to catalog'

### ISSUE THREAD

**Issue by amit17051980** [MicrosoftDocs/microsoft-365-docs#9756]
Please can you provide a document to overcome "Cannot connect to catalog" issue while working on below section?

**_Double-click the add-in you deployed earlier (in this example, Citations)._**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61e46dd-c1ff-dfec-5e0e-9f2e7251a5c1
* Version Independent ID: 49f69fa9-33e8-373f-a7f9-26b828510fda
* Content: [Manage add-ins in the admin center - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/manage-addins-in-the-admin-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/manage-addins-in-the-admin-center.md)
* Service: **o365-administration**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@amit17051980 Thank you for your feedback. We have a different forum (tech community) to handle technical issues. I'd recommend you check https://techcommunity.microsoft.com/t5/word/office-add-ins-error-cannot-connect-to-catalog/m-p/2702496 or similar for solving technical issues. 

The common reason behind this is Your computer and/or Microsoft account might be issued by a school or company and policy/security settings are blocking access to Microsoft Office Store add-ins. So in that case, I'd recommend you contact Microsoft support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @amit17051980 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
