### ISSUE TITLE
Extra '' characters causing issue in localized pages.

### ISSUE THREAD

**Issue by TinaMcN** [MicrosoftDocs/microsoft-365-docs#976]
Near the bottom of the page there are a couple of '' characters that should be removed.   They are causing an issue in the machine translated versions which results in the text after them being left in English.

![image](https://user-images.githubusercontent.com/53281468/71384996-859b6880-2599-11ea-9c53-0bf8e9462a48.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4271558-62a9-db3c-078c-13b5e5fe99da
* Version Independent ID: 813d7002-20a2-b1be-2771-975a0b1cfd48
* Content: [Use network upload to import your organization's PST files - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-network-upload-to-import-pst-files?source=docs)
* Content Source: [microsoft-365/compliance/use-network-upload-to-import-pst-files.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@TinaMcN fixed; fix was to add a third tick (`) because this is text block. Revised topic will be live shortly.

**Comment by TinaMcN** [comment]
@markjjo thanks for the speedy fix!
