### ISSUE TITLE
Search and Auto expanding archive

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#9763]
The following section says "and their corresponding subfolders will be searched." What it doesn't mention is that nested subfolders are not searched. 

For example, I can search items in the folder "\Inbox\Subfolder" but not in the nested subfolder "\Inbox\Subfolder\Nested Subfolder"

> Search for auto-expanded archiving is available in Outlook for the web (OWA). Similar to Online Archive, you can search for items that were moved to an additional storage area. When archive is selected as the search scope in OWA, all archives (including auto-expanded archives) and their corresponding subfolders will be searched.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a21b69-2f7c-d54d-d8a1-5512b810b4bf
* Version Independent ID: 19126a83-c4af-bd0c-6a20-76e27db675c9
* Content: [Learn about auto-expanding archiving - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/autoexpanding-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/autoexpanding-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by jonwbstr** [comment]
A client shared a conversation with Microsoft where Microsoft support points to this article to say search only searches the "current folder". I located this commit which removed that language calling it an "update after talking to the PM"
https://github.com/MicrosoftDocs/microsoft-365-docs/commit/5f8d6ac7520b02dc884a01d678cf1c92d6fc3b35

What changed and when? I don't see any announcements about search capabilities for auto-archive changing. It would be better to note in the article when the behavior changed so anyone that finds the other articles can say, "oh, that use to be true but it says right here the behavior changed on **insert date**

Articles that talk about search:

https://robquickenden.blog/exchange-unlimited-archive
>**What about search? Can I search items in the archive?** Yep.. But the search process is a little different. You can search for items that were moved these additional storage area but only by searching the folder itself. If the archive folder contains subfolders, you have to search each subfolder separately. This is due to performance and speed since the archive folders are stored on lower tier disks within Exchange Online (well it is an archive).

https://techcommunity.microsoft.com/t5/exchange-team-blog/office-365-auto-expanding-archives-faq/bc-p/735158/highlight/true#M26977
>[Bruce Davis](https://techcommunity.microsoft.com/t5/user/viewprofilepage/user-id/52511) Senior Member
‎Jul 02 2019 01:29 PM
The major issue we have with Auto-Expanding Archive, and that is not mentioned anywhere in this article, is that it is not searchable.   **In order to search in folders that are located in the Aux Archives, the user must search each folder individually.**   That is not how search is supposed to work.   Search is supposed to search across all folders...   While I am told from multiple levels of support that "this is by design", I cannot reasonably accept that statement because I don't understand how Microsoft could stand for something being "broken by design".   "Broken by design," is not a good motto to associate with.

**Comment by jonwbstr** [comment]
Tested this on a user and confirmed "current mailbox" does search auto-expanding archive subfolders. 

Let me start over.

Hi,

Historically "Microsoft Search" (cloud search) for auto-expanding archive only supported the search scope "current folder." When did Microsoft Search for auto-expanding archive add support for the scope "current mailbox" and "subfolders"?

I see a version in the referenced [Microsoft Search](https://techcommunity.microsoft.com/t5/outlook-global-customer-service/how-outlook-for-windows-connected-to-exchange-online-utilizes/ba-p/1715045) article showing when support for "subfolders" was added, but no mention of "current mailbox"

And, I see articles that say auto-expanding autoarchive does not support search. Please add a reference to what outlook client version added support for the "current mailbox" scope so it's easy for readers to recognize older articles pre-date the addition of this feature.

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Thanks for your feedback.  We're making some updates to address this.
