### ISSUE TITLE
MDO - AST: Predicted Compromise Rate

### ISSUE THREAD

**Issue by kmacbird** [MicrosoftDocs/microsoft-365-docs#9767]
Hi Team
Could we clarify what the 'Predicted Compromise Rate' stat actually is?  This is for the product itself too..  From the portal; there is no info tip on the column heading and also cannot resize column to display the full heading title to see if this is a percentage, a number/volume/user count etc.  There is wording in the docs article that indicates this is a percentage (actual compromise rate is described as a percentage), but clarity for PCR would be great.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d7b1d53-4fd3-9bde-7c58-223525236f93
* Version Independent ID: 4700cbec-8554-6bc1-fe99-8d077e37b6bb
* Content: [Insights and reports Attack simulation training - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-insights?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/attack-simulation-training-insights.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/attack-simulation-training-insights.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@kmacbird, the description for that term in other content says:

> Historical data across Microsoft 365 that predicts the percentage of people who will get compromised by this payload.

Does this addition make it any clearer?

> Historical data across Microsoft 365 that predicts the percentage of people who will get compromised by this payload (users compromised / total number of users who received the simulation).

**Comment by kmacbird** [comment]
thanks Chris!
I think that helps clarify that its the percentage of users, thankyou!

Kate
________________________________

**Comment by yogkumgit** [comment]
@kmacbird Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
