### ISSUE TITLE
Changes to UI.

### ISSUE THREAD

**Issue by krishnacloud123** [MicrosoftDocs/microsoft-365-docs#9768]
![Advanced DLP Rules](https://user-images.githubusercontent.com/66212565/191175065-daf76fab-0192-4bf3-8115-289568fbcf50.jpg)
[Enter feedback here]

Please note the Screenshot Attached is outdated. For example, there aren't any more "Sensitive Labels" in the Condition.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c2bb05c-4f7c-58cf-6b72-22af2b0377b1
* Version Independent ID: 184b8cb5-327a-41c5-6e61-1cae40965994
* Content: [Use sensitivity labels as conditions in DLP policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-sensitivity-label-as-condition?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/dlp-sensitivity-label-as-condition.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-sensitivity-label-as-condition.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@krishnacloud123 Thank you for your feedback. I was able to test this and found that the sensitivity labels still shows up as a condition in DLP policies fr these locations

Exchange Online email messages
SharePoint Online
OneDrive for Business sites
Windows 10 devices

![image](https://user-images.githubusercontent.com/45987684/193514312-283f3778-07bb-4824-ab46-7527b2bb064f.png)

Note that Sensitivity Labels as a condition will not be available if you have selected Teams chat and channel messages as a location to apply the DLP policy.

This has been added as a note to the document.

Hope this helps!


Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @krishnacloud123 Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by krishnacloud123** [comment]
Thanks @yogkumgit  and @msbemba  -  Documentation update will be helpful - because not every will be able ware of these differences.

**Comment by msbemba** [comment]
@krishnacloud123 Thank you for the feedback. 

We have updated the document to reflect the locations 

![image](https://user-images.githubusercontent.com/45987684/194213749-94b4459d-089b-488a-b5cd-e50558dd324f.png)


Thanks
Sri
