### ISSUE TITLE
CANCELLING

### ISSUE THREAD

**Issue by LinTronic** [MicrosoftDocs/microsoft-365-docs#9769]
[Angiv feedback her]

VERY CONFUSING AND NOT AT ALL SIMPLE TO CANCEL A PRODUCT
AS ALWAYS - NOT USER FRIENDLY AT ALL.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 8adb403b-fded-7b9c-c093-915ca9bb348d
* Version Independent ID: df08fc6b-a752-084b-448a-a253db2a40d5
* Content: [Luk din konto](https://learn.microsoft.com/da-dk/microsoft-365/commerce/close-your-account?view=o365-worldwide)
* Content Source: [microsoft-365/commerce/close-your-account.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/close-your-account.md)
* Service: **o365-administration**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@LinTronic Thank you for your feedback. The steps outlined in the document are accurate and need to be followed to close your Microsoft account.


If you want to cancel your subscription, the easiest way is to [turn off recurring billing](https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/renew-your-subscription?view=o365-worldwide). When you turn off recurring billing, you can continue to use your subscription until it expires at the end of the subscription term. If you want to cancel immediately, use the information and steps in this article- https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide  to do that.

Hope this helps!

Thanks
Sri

**Comment by LinTronic** [comment]
It might be that the information is accurate, but it is VERY circumstantial and MANY steps.

Clicking CANCEL would be easy.

 

This is very complicated – as Windows always is.

 

 

Best regards / med venlig hilsen,

 

Michael Lindgaard

Phone: +45 2876 7699

 

 

Fra: Sriraman M S ***@***.***> 
Sendt: 21. september 2022 13:54
Til: MicrosoftDocs/microsoft-365-docs ***@***.***>
Cc: LinTronic ***@***.***>; Mention ***@***.***>
Emne: Re: [MicrosoftDocs/microsoft-365-docs] CANCELLING (Issue #9769)

 

@LinTronic <https://github.com/LinTronic>  Thank you for your feedback. The steps outlined in the document are accurate and need to be followed to close your Microsoft account.

If you want to cancel your subscription, the easiest way is to turn off recurring billing <https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/renew-your-subscription?view=o365-worldwide> . When you turn off recurring billing, you can continue to use your subscription until it expires at the end of the subscription term. If you want to cancel immediately, use the information and steps in this article- https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/cancel-your-subscription?view=o365-worldwide to do that.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @LinTronic If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
