### ISSUE TITLE
perpend subject

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/microsoft-365-docs#977]
this action will still result in email being delivered to junk. Doc should be amended to indicate this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed2861d-860e-5d27-9259-fb9db2187f4b
* Version Independent ID: 09ef5622-3a7e-30f9-00f9-4c5578f8e1ca
* Content: [Configure your spam filter policies - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies)
* Content Source: [microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configure-your-spam-filter-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by msbemba** [comment]
@aldoug Thank you for the feedback. We have modified the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/998

Thanks
Sri

**Comment by mypil** [comment]
@aldoug - From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/086f9c0c8b2ecdd51d4444514b9acadb449dd1fc but it may take a few days for the merged content to appear in the article. If you feel it hasn't been resolved, please re-open this issue.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by arafa-ettemlali** [comment]
hey can you explain this to me please 
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MjtHRD0yO1NDTD02 
V=1.1;us=0;l=0;a=1;D=2;GD=2;SCL=6
