### ISSUE TITLE
New Search (Preview) for the Audit log

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9770]
I now have a New Search (Preview) option in the audit log as well as the Classic search. There are no details on the page for the New Search (Preview)

![image](https://user-images.githubusercontent.com/69439002/191206038-587f7f5e-45e7-413b-8223-a3ab8bda0f45.png)

The improvements seem to be:

1. searches are now named 
2. your search is saved
3. you can run multiple search jobs at the same time. and the search jobs are queued
4. you can copy a previous search

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have added that as a separate document - https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-new-search?view=o365-worldwide

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@yogkumgit Thank you very much for the contribution and sharing this explanation. @nikki-c Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
