### ISSUE TITLE
Path needs updating for supression rules

### ISSUE THREAD

**Issue by mav147** [MicrosoftDocs/microsoft-365-docs#9771]
In this section:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-alerts?view=o365-worldwide#view-the-list-of-suppression-rules

It states:
In the navigation pane, select Settings > Alert suppression.

It should state:
... select Settings > Endpoints > Rules > Alert suppression

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e663245-4894-4edc-032f-5f21568c007a
* Version Independent ID: e294b3ad-cf6f-3e79-d694-a3669bb04ca9
* Content: [Manage Microsoft Defender for Endpoint alerts](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/manage-alerts?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/manage-alerts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/manage-alerts.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@mav147 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9790

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @mav147 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
