### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by NigelColtellaIT** [MicrosoftDocs/microsoft-365-docs#9774]
[Enter feedback here]
Link below is not valid: 

Use Exchange Online PowerShell. See this blog post for instructions: [Create Shared Mailboxes with Same Alias at Different Domains](https://www.cogmotive.com/blog/office-365-tips/create-shared-mailboxes-with-same-alias-at-different-domains-in-office-365)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0997ee60-7e26-6bca-823e-214654f64c40
* Version Independent ID: 2db201f5-5b3d-de65-8fb2-e66c6ebe19e0
* Content: [Resolve issues with shared mailboxes - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/email/resolve-issues-with-shared-mailboxes?view=o365-worldwide#error-when-creating-shared-mailboxes&preserve-view=true)
* Content Source: [microsoft-365/admin/email/resolve-issues-with-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/email/resolve-issues-with-shared-mailboxes.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by yogkumgit** [comment]
@SKjerland Please help us in resolving this issue. Thanks

**Comment by SKjerland** [comment]
@NigelColtellaIT - The link has been fixed. The updated link will go live on 9/30, at about 10:30 AM PST. Thanks for bringing it to our attention.
