### ISSUE TITLE
Get-MpComputersatus

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/microsoft-365-docs#9775]
Unfortunately one cannot tell from the **AmRunningmode** as displayed by `Get-MpComputerstatus` whether Defender is running in **Passive** or **Normal** mode when **EDR in Block mode** is enabled. Regardless of the two, when Defender is in **EDR in Block mode** _that_ is displayed and one has to check the registry key `ForceDefenderPassiveMode`. If equal to 0, than in **Normal** mode, otherwise **Passive** mode.
Could you make an addition to this document to reflect this, please?  (I believe it is a flaw in how it is displayed by `Get-MpComputerstatus`)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7e0a301-df45-adc1-14f6-3c9a31661d66
* Version Independent ID: 5e970966-d442-2019-29da-daeacecd8a0e
* Content: [Microsoft Defender Antivirus in Windows](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@andrePKI Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9866

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @andrePKI Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
