### ISSUE TITLE
Missing Script Details

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/microsoft-365-docs#978]
In this section:
https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#change-site-and-group-settings-for-a-label

It says you need to run an AAD script to update existing sites.  Which script?  What exactly is it doing and why isn't this automatic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d40ac52-6f02-b0f3-0c45-9f359473703b
* Version Independent ID: 108355a9-05a3-4d17-c417-c4d5664a4506
* Content: [Use sensitivity labels with Microsoft Teams, Office 365 groups, and SharePoint sites (public preview) - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#change-site-and-group-settings-for-a-label)
* Content Source: [microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-teams-groups-sites.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **krowley**

**Comment by MaratMussabekov** [comment]
Hello @danmyhre,
**It says you need to run an AAD script to update existing sites. Which script?** - the script depends on the changes you want to made. If you want to enable labels, you can use the one in the same article - https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#enable-this-preview
if you want to disable them, just change $setting["EnableMIPLabels"] = "True" to $setting["EnableMIPLabels"] = "False" in both sections in step 2 of the same script.

**Comment by danmyhre** [comment]
I am referring to this section:

> Change site and group settings for a label
> As a best practice, don't change settings after you've applied a label to several teams, groups, or sites. If you must make a change, you need to use an Azure AD PowerShell script to manually apply updates. This method ensures that all existing teams, sites, and groups enforce the new setting.
> 

There are no details on what type of change and what script to use.    Why couldn't you just update the settings in the SCC?

**Comment by cabailey** [comment]
@danmyhre  The "script" in question was actually the commands published here https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-teams-groups-sites#relabel-office-365-groups-with-new-sensitivity-labels and not the commands to enable the feature.

We've now updated this section to be more explicit and clarify the original text.
