### ISSUE TITLE
This feature isn't intended to clean up user mailboxes.

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#9780]
>A maximum of 10 items per mailbox can be removed at one time. Because the capability to search for and remove messages is intended to be an incident-response tool, this limit helps ensure that messages are quickly removed from mailboxes. This feature isn't intended to clean up user mailboxes.

Okay, that's fine. Can you give me a link to the preferred method/feature/tool for cleaning up user mailboxes?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e391a3b9-fc52-bedf-353a-3564752240dd
* Version Independent ID: 89376ace-9c00-7c45-3771-a9a913f81bed
* Content: [Search for and delete email messages in your organization - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@jonwbstr  Thank you for your feedback.  There is no tool created for admins to clean up mailboxes.  However, end users can clean up their mailboxes - **https://support.microsoft.com/en-us/office/clean-up-your-inbox-2fb652e5-b387-4147-9fff-25f2e32dfda9**

Hope this helps!

Thanks
Sri

**Comment by jonwbstr** [comment]
Good thing I said method/feature/tool then. I have a 100GB archive I want
to purge 9f 100GB. What are my options? Using outlook would take days

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @jonwbstr Considering the nature of the issue please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by jonwbstr** [comment]
Will do, sometimes the doc team reaches out to the PG for guidance and sometimes I'm asked to open tickets with frontline, escalate them to the PG and then report my findings. Never know which direction this type of thing will go ;).

Thanks!
