### ISSUE TITLE
Bookings with me wont consider all my calendars

### ISSUE THREAD

**Issue by noAlvaro** [MicrosoftDocs/microsoft-365-docs#9781]
My Outlook is subscribed to several personal calendars I use. Still my personal Bookings page ignores them, allowing people to book unavailable time.

_- Is there a way to fix this?_

**Comment by yogkumgit** [comment]
@noAlvaro Please indicate which document you are referring to.  What is your feedback to improve it. Thanks

**Comment by yogkumgit** [comment]
@noAlvaro We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by noAlvaro** [comment]
Hi, sorry which document are you referring to?

My issue is about Outlook calendars (subscriptions and non-Exchange accounts), and availability issues in personal "Bookings" page in Microsoft 365.

The problem is that busy time of such calendars is becoming available for people to book, which sounds incorrect.

**Comment by msbemba** [comment]
@noAlvaro Thank you for your feedback. You are correct, busy times of other calendars should block your booking calendar and users should not be able to book. If you are still facing this issue, I'd recommend contacting support via the need help option in the M365 admin center.

Hope this helps!

Thanks
Sri
