### ISSUE TITLE
Error in Defender for Endpoint on Linux Settings documentation - enableFileHashComputation

### ISSUE THREAD

**Issue by niemimak** [MicrosoftDocs/microsoft-365-docs#9784]
Possible values for enableFileHashComputation are actually boolean true/false, not enabled/disabled like suggested by the documentation. If enableFileHashComputation is set as "enabled" in mdatp_managed.json, the configuration file is not applied.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04ef0d15-6735-bb94-0d86-d57ffbaa05f7
* Version Independent ID: 52e516b5-b365-4950-334a-c4797333093d
* Content: [Set preferences for Microsoft Defender for Endpoint on Linux](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-preferences?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-preferences.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-preferences.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@niemimak Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9818

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @niemimak Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
