### ISSUE TITLE
EDR early preview

### ISSUE THREAD

**Issue by William-Francillette** [MicrosoftDocs/microsoft-365-docs#9785]
Hi
I would like to know what is the status of the EDR early preview setting?
![image](https://user-images.githubusercontent.com/79221284/191441120-1c93233d-e360-43a2-a2be-b16271bb2e67.png)
The description mentions unused - Does this means that it has no effect despite turning this option to true or false?

Thanks,
William

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f88efa4-ff30-7f9d-bc89-22ee1c94098b
* Version Independent ID: 028b68d0-f721-bafd-5a7c-4ab2303081eb
* Content: [Microsoft Defender for Endpoint on Linux resources](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-resources?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/linux-resources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/linux-resources.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@William-Francillette Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9819

Once the author approves, the changes will be live.

Note that we have removed "unused" and the option can be used to turn it true or false.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @William-Francillette Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
