### ISSUE TITLE
German months: Januar or only Jänuary?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#979]
For the German months this is stated:

- jänuar, februar, märz, April, mai, juni juli, August, September, oktober, November, dezember
- Jan./Jän. Feb. März Apr. Mai Juni Juli Aug. Sept. Okt. Nov. Dez.

I have a question about the first line: Does it recognize 'Januar' too or just 'jänuar'? The second line does mention 'jan' and 'jän' so I suspect this is a documentation mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ebaf450-d84e-c333-125c-b0e6d4662bad
* Version Independent ID: efcb8b51-f2fe-765b-221d-75890b4a2d64
* Content: [What the DLP functions look for - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/what-the-dlp-functions-look-for#feedback)
* Content Source: [microsoft-365/compliance/what-the-dlp-functions-look-for.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/what-the-dlp-functions-look-for.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by chrfox** [comment]
Hi @GiantCrocodile 
The documentation states what the product recognizes.
