### ISSUE TITLE
Update to Teams retention policies

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-docs#9795]
Can you update the following sentence 

> A single retention policy can be set to apply to Teams chat and Teams channel messages.

to

> A single retention policy can be set to apply to Teams chat and Teams channel messages (including shared channel messages).

Add a second sentence to state
Teams private channel messages must be contained in their own retention policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be4f3e5c-7dd7-ca98-8cd1-21177e7fe26d
* Version Independent ID: 083f0f2c-8c72-582d-3e13-1679684ea88c
* Content: [Compliance options for Microsoft 365 groups, Teams, and SharePoint collaboration](https://learn.microsoft.com/en-us/microsoft-365/solutions/groups-teams-compliance-governance?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/groups-teams-compliance-governance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/groups-teams-compliance-governance.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@nikki-c Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9821

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @nikki-c Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
