### ISSUE TITLE
How quickly can auto-expanding archive grow?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#9797]
This question comes up when performing migrations of a large on-prem archive to O365.

This [FAQ](https://techcommunity.microsoft.com/t5/exchange-team-blog/office-365-auto-expanding-archives-faq/ba-p/607784) from 2018 says Microsoft is working on it. 3rd party sites say the auto-expanding archive grows in 25GB or 50GB chunks depending on the article. Growth happens once every 7 days or once every 30 days depending on the source. They both suggest the managed folder assistant provisions chunk if the mailbox has reached the warning threshold.

I believe from previous conversations with Exchange support, grown is a hard 30 day limit regardless of how often the Managed folder assistant performs a full scan of the mailbox. I thought it was 10GB chunks, but that is most likely outdated information.

1) Enable auto-expanding
2) Moved data until archive is full
3) Waited 14-21 days and monitor the archive mailbox size. When the archive mailbox size drops below 90GB proceed to step 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54a21b69-2f7c-d54d-d8a1-5512b810b4bf
* Version Independent ID: 19126a83-c4af-bd0c-6a20-76e27db675c9
* Content: [Learn about auto-expanding archiving - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/autoexpanding-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/autoexpanding-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by jonwbstr** [comment]
This is the section that could go into more detail about what automatically and incrementally means.
> This archiving feature in Microsoft Purview (called auto-expanding archiving) provides up to 1.5 TB of additional storage in archive mailboxes. When the storage quota in the archive mailbox is reached, Microsoft Purview automatically (and incrementally) increases the size of the archive until the archive mailbox reaches 1.5 TB.

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by brenle** [comment]
Hi @jonwbstr - the [Tech Communities blog](https://techcommunity.microsoft.com/t5/exchange-team-blog/office-365-auto-expanding-archives-faq/ba-p/607784) that you referenced is accurate, however generally we don't expand on features that deep within the documentation.  

As per the blog, an AuxArchive is created when the archive reaches a certain threshold (90GB/100GB), or if a specific folder reaches the folder item limit (1M items).  This evaluation is done every time ELC runs, which as you know has an expected timeframe of about every 7 days.  That's the 'automatic' part.  That process repeats (new AuxArchives are created as the archive hits the thresholds) up to a maximum aggregate total of 1.5TB, which is what is is referenced as 'incremental'.

We will look into adding these details to the page.  Thanks!

**Comment by jonwbstr** [comment]
Thank you for the info, I've talked to support on this topic several times
over the past few years, and get different answers each time. Perhaps
because the behavior has changed over the years :).

I thought the growth was capped at 10gb in 30 days, guess that is not the
case any longer.

Thanks again!
-jon

**Comment by brenle** [comment]
@jonwbstr No problem. Actually the 10GB and 30 day misinterpretations/misunderstandings are also explained in the blog post!

**Comment by cabailey** [comment]
Closing
