### ISSUE TITLE
Prerequisites?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#9798]
I do not see a Baselines item in the Endpoint section of M365 Defender portal. Are there some prerequisites? if so please identify them on this page
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07635f52-8e88-c01d-0581-62527f53aa49
* Version Independent ID: 07635f52-8e88-c01d-0581-62527f53aa49
* Content: [Security baselines assessment](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/tvm-security-baselines?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/tvm-security-baselines.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/tvm-security-baselines.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
Hi @DeanGross 

Baseline assessments appear under Vulnerability management in the Microsoft 365 Defender portal.

Do you have either Microsoft Defender for Endpoint Plan 2 with the Microsoft Defender Vulnerability Management Add-on installed? or Microsoft Defender Vulnerability Management standalone? 

Thanks,
Sinead

**Comment by DeanGross** [comment]
No, I don't have those and there is nothing on the page that says they are needed.

**Comment by siosulli** [comment]
Hi @DeanGross so this content exists in the Microsoft Defender Vulnerability Management documentation library. It does have an Applies to section at the top of the page and a Note further down with a link on how to experience MDVM. 

This is pretty consistent with the way most of our docs are structured. 

Could you let me know how you came to expect to see Security Baselines in the portal if you were not aware of the MDVM product? I'm just trying to figure where the gap exists so if we need to update something it's done in the right place.

Thanks.

**Comment by DeanGross** [comment]
Thanks, I saw a demo that had Security Baseline menu item and I could not find it in my tenant. The Applies To section at the top of the page includes M365 Defender, which lead me to believe that I should have the functionality. It does not state the MDVM is a prerequisite, which is a little confusing. 
There are many pages like https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-configure, which have a License Requirements section which prevents any ambiguity. It would be great if all of the docs pages could have a License Requirements section. Licensing is tremendously complicated and anything that can be done to simplify this for customers would be greatly appreciated.

**Comment by siosulli** [comment]
Thanks @DeanGross That's a good point! I will take note of this and see if it's something we can address.

**Comment by siosulli** [comment]
I have tracked this as an item to review in our documentation so I think we can close this for now. 

@yogkumgit are you okay if I close this?
