### ISSUE TITLE
What should an admin consider before enabling auto-expanding archiving?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#9799]
In this article we learn about things to consider as it relates to Outlook and OWA. Or, what an administrator might communicate to end users before enabling the feature.

In the related article [Enable auto-expanding archiving](https://learn.microsoft.com/en-us/microsoft-365/compliance/enable-autoexpanding-archiving) we learn about challenges only administrators need to consider before enabling the feature.

It is preferable to include all the things an administrator should consider before enabling the feature in the same article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54a21b69-2f7c-d54d-d8a1-5512b810b4bf
* Version Independent ID: 19126a83-c4af-bd0c-6a20-76e27db675c9
* Content: [Learn about auto-expanding archiving - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/autoexpanding-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/autoexpanding-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Thanks for your feedback.  We're making some updates to address this & clarify the points in the list = potential impact to end users.
