### ISSUE TITLE
What about TLS 1.3?

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#980]
see title of this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14a729bb-ad0e-27bf-b119-beb99f1df9f4
* Version Independent ID: bc005f28-aa37-f52d-c328-ff547c1eb7b3
* Content: [Technical reference details about encryption in Office 365 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/technical-reference-details-about-encryption)
* Content Source: [microsoft-365/compliance/technical-reference-details-about-encryption.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/technical-reference-details-about-encryption.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by MaratMussabekov** [comment]
Hello @GiantCrocodile,
TLS 1.3 is not supported by Office 365 yet.
Thank you

**Comment by GiantCrocodile** [comment]
@MaratMussabekov This should be stated in the docs then :).
