### ISSUE TITLE
Include this in the list of things to consider in Outlook and OWA

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/microsoft-365-docs#9800]
As mentioned earlier in the article,
> Sometimes when a folder is moved, one or more subfolders are automatically created and items from the original folder are distributed to these folders to facilitate the moving process.

If I'm compiling a list of things I need to tell the end user when I enable auto-expanding archiving this should be on the list. Someone will inevitably ask why these folders appeared in their archive.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54a21b69-2f7c-d54d-d8a1-5512b810b4bf
* Version Independent ID: 19126a83-c4af-bd0c-6a20-76e27db675c9
* Content: [Learn about auto-expanding archiving - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/autoexpanding-archiving?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/autoexpanding-archiving.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/autoexpanding-archiving.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
Thanks for your feedback.  We're making some updates to address this.
