### ISSUE TITLE
I believe there is a missing audit in documentation

### ISSUE THREAD

**Issue by RaphaelUlysses** [MicrosoftDocs/microsoft-365-docs#9802]
Hello, I have seen reports of O365 customers seeing an audit named "Enable Strong Authentication" showing up in the unified auditing log when they enable MFA on a user account. I looked at official documentation and could not find any technet / KB article with this information. I might be missing it. But if not, I wanted to provide feedback as I was unable to spot it anywhere else other than through user reports. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@RaphaelUlysses - thanks for the feedback. I confirm that I don't currently see any documentation of this, I will discuss with the PG team and update the content as applicable.
