### ISSUE TITLE
3rd Party Apps not censored properly

### ISSUE THREAD

**Issue by AlexDeryabin** [MicrosoftDocs/microsoft-365-docs#9807]
The blocked applications image censors the application names and vendors, but contains the version numbers, which are mostly unique creating a 1:1 mapping to the application. E.g. Foxit, Putty, Teamviewer, Safari, iTunes, QuickTime, ...

Should it be censored correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 106571a1-b6e1-39c6-7324-77de625cc068
* Version Independent ID: 106571a1-b6e1-39c6-7324-77de625cc068
* Content: [Block vulnerable applications (beta)](https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/tvm-block-vuln-apps?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-vulnerability-management/tvm-block-vuln-apps.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-vulnerability-management/tvm-block-vuln-apps.md)
* Service: **microsoft-365-security**
* Sub-service: **mdvm**
* GitHub Login: @siosulli
* Microsoft Alias: **siosulli**

**Comment by siosulli** [comment]
I have updated these images to censor the version numbers.

This should be visible here after 10AM PST time today: 

https://learn.microsoft.com/microsoft-365/security/defender-vulnerability-management/tvm-block-vuln-apps?view=o365-worldwide

**Comment by yogkumgit** [comment]
@AlexDeryabin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
