### ISSUE TITLE
SafeDocsDemo.docx is not triggering Safe Document protection

### ISSUE THREAD

**Issue by ChristophersProfessional** [MicrosoftDocs/microsoft-365-docs#9808]
Good Afternoon,

The SafeDocsDemo.docx file is not triggering the Safe Document protection. The other two are, just this one.

Before you ask, I'm, Microsoft 365 E5 licensed, have checked I have this turned on, MDE enrolled (although don't think that's a prereq) and using Microsoft Word for 365 MSO (Version 2206 Build 16.0.15330.20306) 64-bit.

Thanks,

Christopher

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide#how-does-microsoft-handle-your-data)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ChristophersProfessional, you should open a support ticket about this.

**Comment by yogkumgit** [comment]
@ChristophersProfessional  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
