### ISSUE TITLE
List of breaches in the past

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#981]
Hello,

is there any list of breaches for Office 365 or Azure in the past? This would be useful.

Thank you!

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3afb621c-66f6-c64a-8f87-16b3f71d990e
* Version Independent ID: da149924-37eb-78a8-d8ea-7ae5c1fbf1ff
* Content: [Breach Notification - Microsoft GDPR](https://docs.microsoft.com/en-us/microsoft-365/compliance/gdpr-breach-notification#feedback)
* Content Source: [microsoft-365/compliance/gdpr-breach-notification.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/gdpr-breach-notification.md)
* Product: **microsoft-365-enterprise**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by robmazz** [comment]
@GiantCrocodile - thanks for the feedback, but breach information will be shared only with customers involved in any breaches as stated in this topic.
