### ISSUE TITLE
Did Microsoft cancel support for DKIM in Germany?

### ISSUE THREAD

**Issue by flowl** [MicrosoftDocs/microsoft-365-docs#9810]
On the linked page is the following alert about DKIM in Exchange / Defender 365:

> This feature requires a Microsoft 365 administrator account. This feature isn't available for Microsoft 365 Government, Microsoft 365 operated by 21Vianet, or Microsoft 365 Germany.

What is `Microsoft 365 Germany`?
I setup DKIM successfully in 2020 and I just found out that my messages are not getting signed anymore.
Did Microsoft stop supporting DKIM for German customers?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 249c059f-c3ce-a382-b99e-795a0c1f646a
* Version Independent ID: 5656c114-ae16-6194-cd9f-353b33f4a1e1
* Content: [How to use DKIM for email in your custom domain - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by DMoenks** [comment]
**Microsoft 365 Germany** was a distinct Microsoft infrastructure for German customers until end of October 2021, quite similar to **Microsoft 365 operated by 21Vianet** for Chinese customers, and it was merely meant to assure that all data was stored within Germany's borders to comply with government regulations.
Using **Microsoft 365 worldwide** in Germany has no special limitations, as far as I know.

**Comment by flowl** [comment]
@DMoenks thank you for the explanation!
