### ISSUE TITLE
still delayed in the environment enabled co-authoring feature.

### ISSUE THREAD

**Issue by Kaypyosh** [MicrosoftDocs/microsoft-365-docs#9811]
Hello
I would like to make sure one thing about the following sentence. It says that the delay may happen unless enabling co-authoring. 

_Unless you've [enabled co-authoring for files encrypted with sensitivity labels](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-coauthoring?view=o365-worldwide), you'll see a delay in applying the default sensitivity label for a document library when users select the File > Save as option._

I think the description intends to explain that the delay shouldn't happen in the environment enabled co-authoring. However, in my lab where co-authoring is enabled, it is still slow. 

I would like to make sure what the description means and if I did misread it, I'd appreciate it if you can tell me how I should have read it.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a96bf9a2-9de2-8366-24f5-d014b72fd380
* Version Independent ID: a96bf9a2-9de2-8366-24f5-d014b72fd380
* Content: [Configure a default sensitivity label for a SharePoint document library - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-sharepoint-default-label?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/sensitivity-labels-sharepoint-default-label.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/sensitivity-labels-sharepoint-default-label.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by msbemba** [comment]
@Kaypyosh Thank you for your feedback. The statement means you need to Enable co-authoring for files encrypted with sensitivity labels.

Without this setting enabled for your tenant, users must check out an encrypted document stored in SharePoint or OneDrive when they use Office desktop apps. As a result, they can't collaborate in real time. 

To Enable co-authoring for files encrypted with sensitivity labels - you can follow https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-coauthoring?view=o365-worldwide

Hope this helps!
Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Kaypyosh Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Kaypyosh** [comment]
Thanks for your help.

I understand what the statement means.
In fact, Co-Authoring feature is already enabled in my tenant, but it still happens. If it persists, I will open a support request.

Thanks
