### ISSUE TITLE
Availability in GCC/Gov Cloud

### ISSUE THREAD

**Issue by dbroussa** [MicrosoftDocs/microsoft-365-docs#9814]
Working with a client in the GCC they do not see this feature.  The article nor other pages mention if this is or is not available in the Government Cloud.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 411cc9ec-3de2-9aaf-00b8-d923d2b02f37
* Version Independent ID: c1a0daec-33a1-eb34-db3d-0b12b78a8aaf
* Content: [Microsoft Adoption Score - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/adoption/adoption-score?view=o365-worldwide&source=docs#feedback)
* Content Source: [microsoft-365/admin/adoption/adoption-score.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/adoption/adoption-score.md)
* Service: **o365-administration**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@dbroussa Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9867

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @dbroussa Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
