### ISSUE TITLE
Users will Full Access Permission to a shared mailbox cannot access the quarantined messages of this mailbox

### ISSUE THREAD

**Issue by Goobenator** [MicrosoftDocs/microsoft-365-docs#9815]
https://learn.microsoft.com/microsoft-365/security/office-365-security/view-and-release-quarantined-messages-from-shared-mailboxes

As described here is not functioning. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6962b118-bc67-caa7-ebad-830792611a67
* Version Independent ID: 43956aab-5f2a-de67-c252-65e8fdb9c39e
* Content: [View and release quarantined messages from shared mailboxes - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/view-and-release-quarantined-messages-from-shared-mailboxes?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/view-and-release-quarantined-messages-from-shared-mailboxes.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/view-and-release-quarantined-messages-from-shared-mailboxes.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Goobenator, can you be more specific?

**Comment by Goobenator** [comment]
Thank you @chrisda 

From the article that I cited this specific feature is not working:

"any user that has access to the quarantine notifications in the shared mailbox can click the Review button in the notification"

To clarify, several users have 'full access' and 'send as' permissions to a shared mailbox. When a quarantine notification digest message is received by the shared mailbox, they can only release the message from the notification message itself. In addition, any attempt to release or access the quarantine of the shared mailbox results in a permissions error. 

It is really strange because when they click the link to 'request release' the request is processed normally, but the end user still see's a permission error. None of these users is able to review any of the messages. I would assume that the 'block' and 'delete' button are functioning similarly but have not tested.

**Comment by chrisda** [comment]
Thanks. Checking.

**Comment by chrisda** [comment]
@Goobenator, here's what I have:

- I updated the topic to clarify that Full Access permissions are required to do anything if you click Review in a quarantine notification for the shared mailbox. Originally, it said visibility of the quarantine notification was enough:

  > If the following statements are all true:
  > - An admin has configured [quarantine policies](https://learn.microsoft.com/microsoft-365/security/office-365-security/quarantine-policies) to allow quarantine notifications (formerly known as end-user spam notifications).
  > - The user has access to quarantine notifications of the shared mailbox.
  > - The user has Full Access permissions to the shared mailbox (directly or via a security group).
  >
  > The user can click the **Review** button in the notification to go to quarantine in the Microsoft 365 Defender portal. This method only allows access to quarantined messages that were sent to the shared mailbox. Users can't manage their own quarantine messages in this context.

- I'm told you should open a support ticket about the following issues:

  > To clarify, several users have 'full access' and 'send as' permissions to a shared mailbox. When a quarantine notification digest message is received by the shared mailbox, they can only release the message from the notification message itself. In addition, any attempt to release or access the quarantine of the shared mailbox results in a permissions error.
  >
  > t is really strange because when they click the link to 'request release' the request is processed normally, but the end user still sees a permission error. None of these users is able to review any of the messages. I would assume that the 'block' and 'delete' button are functioning similarly but have not tested.

OK?

**Comment by chrisda** [comment]
Closing issue due to lack of response. There have been various updated to the shared mailbox quaratine article over the last 10 months, so any required call-outs or caveats should already be in there.
