### ISSUE TITLE
Microsoft Defender for Endpoint (Server)

### ISSUE THREAD

**Issue by joguzmsft** [MicrosoftDocs/microsoft-365-docs#9816]
Hello, I have been reviewing this article and I believe that it has missing information that can be helpful for readers. 

In the following documentation:
https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-users-to-benefit-from-the-service-1

It states that new customers can no longer purchase Microsoft Defender for Endpoint (Server). 
There is no **note** for this on this article. However, there is a note on the requirements necessary to purchase this SKU. 

Thank you. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Version Independent ID: 4166ff18-3b2f-8df5-1c9a-5746add8180b
* Content: [Defender for Endpoint onboarding Windows Server](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/onboard-windows-server?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/onboard-windows-server.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/onboard-windows-server.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@joguzmsft Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9848

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @joguzmsft Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
