### ISSUE TITLE
It needs to be updated the addon from Microsoft compliance extension to Microsoft Purview Extension.

### ISSUE THREAD

**Issue by sergioandreslq** [MicrosoftDocs/microsoft-365-docs#9822]
[Enter feedback here]
In the documentation still appear the legally name for the addon used in browser.

It is required to update the name in the article, this is generating misunderstanding for the users looking for this addon that doesn't exist anymore.

Error test:
Signals for these events are detected in Microsoft Edge using built-in browser capabilities and using the **_Microsoft Compliance Extension add-on_**. In Google Chrome, customers use the Microsoft Compliance Extension for signal detection.

regards, 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88966768-09f1-e1af-4f3e-15b97ae859b5
* Version Independent ID: 3058da4d-7392-56f1-8837-fc2f22a3ec22
* Content: [Learn about and configure insider risk management browser signal detection - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-browser-support?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/insider-risk-management-browser-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-browser-support.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@sergioandreslq Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9844

Once the author approves, the changes will be live.

Thanks
Sri
