### ISSUE TITLE
Discrepancies in text description and screenshot causing customer confusion issupervised and {{issupervised}}

### ISSUE THREAD

**Issue by AndNovian** [MicrosoftDocs/microsoft-365-docs#9824]
Discrepancies in text description and screenshot causing customer confusion

Under **Configure Supervised Mode via Intune > App configuration policy** section no 3, we could see **Configuration Value** issupervised, however from the screenshot it is showing as **{{issupervised}}**, with curly bracket. This causes confusion to customer

![image](https://user-images.githubusercontent.com/114455998/192415562-a80915d1-603c-47db-87ff-6fe2ea117fea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9d7718e-f707-9e4d-8583-4a6385b9b40c
* Version Independent ID: e5abdc8e-1b61-ca7c-d73c-b4d9d3a6de48
* Content: [App-based deployment for Microsoft Defender for Endpoint on iOS](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/ios-install?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/ios-install.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/ios-install.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@AndNovian Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9845

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @AndNovian Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by AndNovian** [comment]
Thanks team! Appreciate the quick resolution!
