### ISSUE TITLE
Missing Details for AdditionalFields 

### ISSUE THREAD

**Issue by PhilippEisenmann** [MicrosoftDocs/microsoft-365-docs#9826]
The details of the AdditionalFields values is missing. Without this information you cannot parse it using KQL:

AdditionalFields | string | Additional information about the event in JSON array format
-- | -- | --

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3896293b-ab88-1f86-6829-082d6d2e5f73
* Version Independent ID: ca04da4a-4d14-5dd4-20ee-b7bb22b64354
* Content: [DeviceInfo table in the advanced hunting schema](https://learn.microsoft.com/en-us/microsoft-365/security/defender/advanced-hunting-deviceinfo-table?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/advanced-hunting-deviceinfo-table.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/advanced-hunting-deviceinfo-table.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by yogkumgit** [comment]
@schmurky Please help us in resolving this issue. Thanks

**Comment by yogkumgit** [comment]
@schmurky Thank you very much for the contribution and sharing this explanation. @PhilippEisenmann Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
