### ISSUE TITLE
information missing

### ISSUE THREAD

**Issue by JXG2300** [MicrosoftDocs/microsoft-365-docs#9828]
The main page with all the phases lists 6 steps for phase 2. Phase 2 article here only has 5 steps listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42db2345-0d5c-45f3-6c24-d84a12775fb7
* Version Independent ID: 1634b283-c538-907c-83db-ad6bd99402bb
* Content: [Switch to Microsoft Defender for Endpoint - Setup](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/switch-to-mde-phase-2?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/switch-to-mde-phase-2.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@JXG2300 Thank you for your feedback. I have updated the main page to reflect 5 steps as this was recently updated.

This change can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9846

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @JXG2300 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
