### ISSUE TITLE
Please include release information for unified solution Installation Package(md4ws.msi).

### ISSUE THREAD

**Issue by hnakamoto** [MicrosoftDocs/microsoft-365-docs#9829]
[Enter feedback here]
The unified solution Installation Package(md4ws.msi) for Windows Server 2012 R2/ 2016  is updated on an irregular basis.
However, there is no site to check for fixed content and the latest version.
Since there is currently no way to check, could you please include a description of the new version as it is released?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c5eb6e9-4010-6077-4746-ec9f93148f9e
* Version Independent ID: 8c5eb6e9-4010-6077-4746-ec9f93148f9e
* Content: [What's new in Microsoft Defender for Endpoint](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-endpoint?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-endpoint.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/whats-new-in-microsoft-defender-endpoint.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
The whats new pages underwent recent changes which include version numbers etc,
