### ISSUE TITLE
Before your appointment

### ISSUE THREAD

**Issue by lkkliffen** [MicrosoftDocs/microsoft-365-docs#9830]
I am trying to add the Before your appointment section to my booking to be linked with Microsoft Forms but cannot find this setting anywhere, can someone please assist me?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08f1236b-050e-d7b5-ea59-3de650155607
* Version Independent ID: fc058c80-e7c4-1a26-cbc3-d33fc2282e13
* Content: [Define your Bookings service offerings](https://learn.microsoft.com/en-us/microsoft-365/bookings/define-service-offerings?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/define-service-offerings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/define-service-offerings.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@lkkliffen Thank you for your feedback. This is a technical question/issue and needs troubleshooting, I'd recommend you to contact Microsoft support via the need help section on your admin center. That way a support engineer will be able to assist you.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @lkkliffen Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
