### ISSUE TITLE
Frequency times documentary mismatch

### ISSUE THREAD

**Issue by Kuermel** [MicrosoftDocs/microsoft-365-docs#9832]
This documentation is different from the documentation in the online portal. 
```
Every 24 hours—runs every 24 hours, checking data from the past 30 days
Every 12 hours—runs every 12 hours, checking data from the past 24 hours
Every 3 hours—runs every 3 hours, checking data from the past 6 hours
Every hour—runs hourly, checking data from the past 2 hours
```

![image](https://user-images.githubusercontent.com/6574969/192729531-0d3faf3a-5131-4427-98b4-bd70a6b25294.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbf510e0-742e-fce6-787e-18eb8a22f42d
* Version Independent ID: 23b77843-cf19-aacb-47af-1f51792c76a0
* Content: [Create and manage custom detection rules in Microsoft 365 Defender](https://learn.microsoft.com/en-us/microsoft-365/security/defender/custom-detection-rules?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender/custom-detection-rules.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender/custom-detection-rules.md)
* Service: **microsoft-365-security**
* Sub-service: **m365d**
* GitHub Login: @schmurky
* Microsoft Alias: **maccruz**

**Comment by schmurky** [comment]
I will address this right away, thank you @Kuermel

**Comment by schmurky** [comment]
Update will go live at regular publishing hours: https://github.com/MicrosoftDocs/microsoft-365-docs-pr/pull/16592/files

**Comment by Kuermel** [comment]
https://github.com/MicrosoftDocs/microsoft-365-docs/commit/d569c63e91c2cf13f5415f20549c53a0735cb4d1
