### ISSUE TITLE
Calling an API endpoint for approving pending actions

### ISSUE THREAD

**Issue by kraken8585** [MicrosoftDocs/microsoft-365-docs#9838]
Hi guys,

This is related to the following documentation
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/air-review-approve-pending-completed-actions.md

and the following article
https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/automated-investigation-response-office.md

Based on my understanding, we can integrates AIR with their SIEM using the Office 365 Management Activity API but for some reason I can't seem to locate the right api endpoint to do so. Basically, I just want to pull all pending actions related to AIR and submit an approval using automation. Can you point me in the right direction or provide some guidance on how I can achieve that? Thank you.

**Comment by msbemba** [comment]
@kraken8585 Thank you for your feedback. This sounds more like a technical question and you need assistance from Microsoft support engineer. I recommend contacting Microsoft support via the need help section on the admin center.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @kraken8585 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by msbemba** [comment]
@yogkumgit This can be closed
