### ISSUE TITLE
Outdated instruction?

### ISSUE THREAD

**Issue by FranNev** [MicrosoftDocs/microsoft-365-docs#9841]
Hello, in this part: https://learn.microsoft.com/en-us/microsoft-365/frontline/flw-onboarding-wizard?view=o365-worldwide#run-the-wizard

The instruction is: "Go to the Apps and email section, and then under Get your frontline workforce up and running, select View ."

But if you look at the screenshot after the instruction, it looks like this is about playing a video. In this case, "select View" sounds a bit confusing.

Best regards,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9165fa1-7e61-250f-a442-ffe248d96e31
* Version Independent ID: f9165fa1-7e61-250f-a442-ffe248d96e31
* Content: [Use the Frontline Worker onboarding wizard to get your frontline workforce up and running - Microsoft 365 for frontline workers](https://learn.microsoft.com/en-us/microsoft-365/frontline/flw-onboarding-wizard?view=o365-worldwide)
* Content Source: [microsoft-365/frontline/flw-onboarding-wizard.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/frontline/flw-onboarding-wizard.md)
* Service: **microsoft-365-frontline**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanachin**

**Comment by msbemba** [comment]
@FranNev Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9883

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per the comment in PR. Thanks
