### ISSUE TITLE
Longer Term Event storage

### ISSUE THREAD

**Issue by AJ-Gov** [MicrosoftDocs/microsoft-365-docs#9842]
[Enter feedback here]
The limitation with Device Control is that you can only export 500 events to Excel, it would be useful to have a section on this page that explains for longer term event storage and use,  the use of Microsoft Sentinel can help with the appropriate connector ...etc
cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac8deee5-bb2d-24da-0a31-0d41ccb4492c
* Version Independent ID: 77b994cf-7b5c-f813-0a1f-a38f046a2a02
* Content: [Protect your organization's data with device control](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/device-control-report?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/device-control-report.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/device-control-report.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by yogkumgit** [comment]
@denisebmsft Please help us in resolving this issue. Thanks
