### ISSUE TITLE
Deployment reports ?

### ISSUE THREAD

**Issue by extenue** [MicrosoftDocs/microsoft-365-docs#9849]
Hi Microsoft,

We have deployed an Integrated App (custom addin for Outlook) , where can I see the stats for this deployment ? How can I know which users has received or not this addin.

I am not able at all to find any clue.

Thank you

**Comment by yogkumgit** [comment]
@extenue Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
