### ISSUE TITLE
Progress on Known limitations

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/microsoft-365-docs#985]
What's the status of the Known Limitations nowadays? According to the docs they should be resolved in July 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98bc6c1c-0814-3b42-25ea-266dfedc394b
* Version Independent ID: 95fff52e-d276-37d4-cd67-9406139f9c92
* Content: [Use Exchange Online and the Security & Compliance Center to comply with SEC Rule 17a-4 - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/use-exchange-online-to-comply-with-sec-rule-17a-4)
* Content Source: [microsoft-365/compliance/use-exchange-online-to-comply-with-sec-rule-17a-4.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/use-exchange-online-to-comply-with-sec-rule-17a-4.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mypil** [comment]
@GiantCrocodile - Thank you for submitting feedback.

I will get this issue over to the Microsoft 365 writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

**Comment by mypil** [comment]
@cabailey - Can you please share your insights on this issue?

Thank you.

cc: @kenwith

**Comment by cabailey** [comment]
@mypil and @GiantCrocodile :  Investigating … it seems an update is indeed due!  However, I will need to wait for people to come back after the holidays to get an authoritative answer.

**Comment by GiantCrocodile** [comment]
Thank you for the short update @cabailey!

**Comment by cabailey** [comment]
@GiantCrocodile  Apologies for the delay - I finally got confirmation that these limitations aren't yet resolved, but not forgotten.  I can't give you an ETA but I have updated the page to reflect the current status.  I'll update it again when these limitations are addressed.

**Comment by cabailey** [comment]
Closing issue.
