### ISSUE TITLE
Instructions to "Make a Bookings user a super user without adding them as Staff in Bookings" actually do the opposite

### ISSUE THREAD

**Issue by mossywell** [MicrosoftDocs/microsoft-365-docs#9850]
This section describes how, using PowerShell, to add a user as an Admin without making them bookable.

In fact, the instructions _do_ make them bookable just as if it has been set up via the GUI. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fcbd22b-e14b-fe97-7b7f-eb672e84d382
* Version Independent ID: f9a024d7-6600-4922-02b5-2c8ceeae13ab
* Content: [Add staff to Bookings](https://learn.microsoft.com/en-us/microsoft-365/bookings/add-staff?view=o365-worldwide#make-a-bookings-user-a-super-user-without-adding-them-as-staff-in-bookings)
* Content Source: [microsoft-365/bookings/add-staff.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/add-staff.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@mossywell Thank you for your feedback. I tested it with a new user and it works just as described. The cmdlets only assigned Mailbox permissions to the user and did not make the user bookable. Note that these steps only work if the user being added isn't already assigned a viewer role in Bookings.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mossywell Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by msbemba** [comment]
@yogkumgit This can be closed
