### ISSUE TITLE
Missing command in script

### ISSUE THREAD

**Issue by tcjoyce** [MicrosoftDocs/microsoft-365-docs#9851]
This script is missing "Write-Host" command at the start of line 77. Second line here:

else{
 "No hold policies found in case:" $cc.name -foregroundColor 'Yellow'
" "

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 170c3a0d-4a77-211f-8ef4-21da97042c1e
* Version Independent ID: b121eb8f-2438-f0cf-41b9-0cfe3ca34925
* Content: [Use a script to create an eDiscovery holds report - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-report-on-holds-in-ediscovery-cases.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@tcjoyce Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9884

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@tcjoyce Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
