### ISSUE TITLE
No option to add Microsoft 365 group as per line "Use the Choose Members section to add the Microsoft 365 group you created before to the role group.", additionally in portal thigs work like : https://learn.microsoft.com/en-us/microsoft-365/compliance/microsoft-365-compliance-center-permissions?view=o365-worldwide --> Create a custom role group, which says to choose members and not O365 group, tested with Microsoft 365 Business Standard subscription, requesting you to revalidate statement

### ISSUE THREAD

**Issue by RahulDube** [MicrosoftDocs/microsoft-365-docs#9852]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0e7f42-60d0-1f95-57e9-6a24a5d87c2b
* Version Independent ID: 0080b139-e35b-b302-b38c-07a2e2e8c1ef
* Content: [Create a DLP policy from a template - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/create-a-dlp-policy-from-a-template?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/create-a-dlp-policy-from-a-template.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/create-a-dlp-policy-from-a-template.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@RahulDube Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9885

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
Closing as per the input from author in the PR. Thanks
