### ISSUE TITLE
mistranslation in Japanese version

### ISSUE THREAD

**Issue by tamiyatxt1** [MicrosoftDocs/microsoft-365-docs#9853]
[Enter feedback here]
Feedback for Japanese machine translation version.
https://learn.microsoft.com/ja-jp/microsoft-365/compliance/insider-risk-management-activities?view=o365-worldwide#all-risk-factors

A phrase "health records" is translated into "正常性".
As Japanese people understand "正常性" as "normality", we cannot understand what "正常性" points.
English:
**Health record access: Displays activities for events associated with accessing health records.**
Japanese:
**正常性レコードへのアクセス: 正常性レコードへのアクセス に関連付けられたイベントのアクティビティを表示します。**

In IRM settings, health records indicators are categolized as "健康記録", so "health records" should be translated into "健康記録".

![image](https://user-images.githubusercontent.com/45841593/193170971-321d1bb1-1414-4cd8-a105-8b188a3dd9a7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 045ebef3-d785-0f44-9029-7efb29f422bc
* Version Independent ID: 09b97bf2-67a3-016e-874f-e7617386e920
* Content: [Investigate insider risk management activities - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-activities?view=o365-worldwide&source=docs#all-risk-factors)
* Content Source: [microsoft-365/compliance/insider-risk-management-activities.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-activities.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@MartinOersted Please help us in resolving this issue. Thanks

**Comment by MartinOersted** [comment]
@yogkumgit I have opened a bug for it. 

In the future can I ask you to follow the following:
Can I ask you to please log a bug via the [Global Services Hub](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fglobalservices.powerappsportals.com%2FGlobal%2F&data=05%7C01%7Ctinamc%40exchange.microsoft.com%7C4f2b9fb1b0ed43511e9e08da69271700%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637937913870816942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TtVS0poPfsdVgMXcgJIDn0CCuSMvq0d9ZB2MP37gRj0%3D&reserved=0) using this [link](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2FGlobalCollaborationService%2FGlobal%2520Collaboration%2520Service%2520Project%2F_workitems%2Fcreate%2FBug&data=05%7C01%7Ctinamc%40exchange.microsoft.com%7C4f2b9fb1b0ed43511e9e08da69271700%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637937913870816942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0zVuNeIOdsddheQu5JNUSZeOBye%2BrCQY8lQv0TaLB54%3D&reserved=0)
 
A few notes for logging Docs content bugs:
o	You can leave the Assigned To field blank.  The localization suppliers are constantly triaging new bugs and will assign them to the correct persons to fix.
o	Please @mention me in the bug so I can monitor it.
o	Set Area = Global Collaboration Service Project\Global\Content\Support\Technical Content - IT Pro (formerly TechNet)
o	Set Iteration = Global Collaboration Service Project\Unspecified
o	Set Product Area = UA – TechCon
