### ISSUE TITLE
"iso" is mentioned in the default file types, but it is also mentioned in "additional file types". Which one is it?

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/microsoft-365-docs#9856]
In this article "iso" is mentioned in the default file types, but it is also mentioned in "additional file types". Which one is it, or is one a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b89afa39-ea8f-bfa3-d600-0bb5fda0805f
* Version Independent ID: 8b0ccaa2-9d59-1677-4cf1-1a3cacfc9239
* Content: [Anti-malware protection - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-malware-protection?view=o365-worldwide#anti-malware-policies)
* Content Source: [microsoft-365/security/office-365-security/anti-malware-protection.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/anti-malware-protection.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dombat, iso is included in the default types that are already selected. I removed it from the additional file types list.

Thanks for the feedback.

Closing
