### ISSUE TITLE
Alerts for Configuration Analyzer

### ISSUE THREAD

**Issue by MSilcox1** [MicrosoftDocs/microsoft-365-docs#9860]
Is there not a built-in alert or supported method for generating alerts based on Configuration Analyzer? Seems like an obvious ask to be able to get alerts when Admins make changes to policies in Defender for 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbce796-0aec-3236-d505-607ae8371773
* Version Independent ID: 473cdc81-dc01-f7fd-d570-73e9a07cb972
* Content: [Configuration analyzer for security policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/configuration-analyzer-for-security-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MSilcox1, you should open a support ticket and ask for this. Modifications to any security policies will be caught in admin audit logging, so perhaps a custom alert based on those cmdlets is possible?

**Comment by MSilcox1** [comment]
Thanks for the response @chrisda. Unfortunately, I'm only able to create a custom alert on Get- cmdlets and not Set- cmdlets. For example, I can create one for Get-AntiPhishPolicy, but not for Set-AntiPhishPolicy. Not sure if I'm missing something obvious.

**Comment by chrisda** [comment]
Strange. I thought it was harder to monitor Get- cmdlets as they're mostly turned off for auditing by default. All of the security policies are in Exchange Online PowerShell, not Security & Compliance PowerShell, if that makes a difference.

- Set-MalwareFilterPolicy
- Set-HostedContentFilterPolicy
- Set-AntiPhishPolicy
- Set-SafeLinksPolicy
- Set-SafeAttachmentPolicy

Also watch for disabling policies:

- Disable-MalwareFilterRule
- Disable-HostedContentFilterRule
- Disable-AntiPhishRule
- Disable-SafeLinksRule
- Disable-SafeAttachmentRule

**Comment by chrisda** [comment]
Closing due to lack of response.
