### ISSUE TITLE
Conditions for finding Team Meeting recordings don't seem to work.

### ISSUE THREAD

**Issue by DPdlund** [MicrosoftDocs/microsoft-365-docs#9869]
When testing the conditions for finding Teams Meeting recordings:

ProgID:Media AND ProgID:Meeting

I get "Unknown property name: ProgID" when building the query.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a4716f6-31db-306c-2804-56591e3af7e6
* Version Independent ID: 8dfc13ff-3b6a-ba25-2911-db7a3dcd2e8a
* Content: [Automatically apply a retention label - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/apply-retention-labels-automatically?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/apply-retention-labels-automatically.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/apply-retention-labels-automatically.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@DPdlund Sorry to hear this isn't working for you.  Please open a support ticket for investigation.
