### ISSUE TITLE
PowerShell Script to assign licenses not working

### ISSUE THREAD

**Issue by NiteshSharma2K19** [MicrosoftDocs/microsoft-365-docs#9870]
I followed the PowerShell Script to copy licenses from one user to another user and it is not working

![image](https://user-images.githubusercontent.com/49910457/193654881-aa246358-2878-49f5-ac40-f1304f85a680.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 073b885d-191e-8c00-fa59-ad83ba79ec10
* Version Independent ID: 4bd5799d-9baf-90b6-634d-398fbea6b66f
* Content: [Assign Microsoft 365 licenses to user accounts with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@NiteshSharma2K19 Considering the nature of the issue,  please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by NiteshSharma2K19** [comment]
Hi Yogesh,

Sorry but you are mistaken. The issue is with the script mentioned on the
page not with my tenant. Please try to run the script in your test
environment.

**Comment by yogkumgit** [comment]
@NiteshSharma2K19 reopening it for further investigation. Thanks

**Comment by msbemba** [comment]
@NiteshSharma2K19 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9887

Once the author approves, the changes will be live.

Thanks
Sri
