### ISSUE TITLE
What kind of related user information will be returned? relatedUser or loggedOnUsers? 

### ISSUE THREAD

**Issue by mhuangdesign** [MicrosoftDocs/microsoft-365-docs#9871]
What kind of related user information will be returned? **relatedUser** or **loggedOnUsers**? 
One of my alerts has both relatedUser and loggedOnUsers, when I run get alert related user information API, the response is successful but the value is empty. It seems like this API is getting neither the realtedUser nor the loggedOnUsers. Then which user information will be returned?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffd2980d-966a-6871-d63d-3b3d887c1fc2
* Version Independent ID: 284d17be-0a41-ef9a-2d24-5ff7718fe129
* Content: [Get alert related user information](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-alert-related-user-info?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/get-alert-related-user-info.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/get-alert-related-user-info.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
Pls contact support.
