### ISSUE TITLE
Possible duplicate sentence

### ISSUE THREAD

**Issue by aaronsgutierrez** [MicrosoftDocs/microsoft-365-docs#9873]
Please see below ~ the first and last sentence seem to be saying the exact same thing: 
**The Defender for Endpoint sensor requires Microsoft Windows HTTP (WinHTTP) to report sensor data and communicate with the Defender for Endpoint service.** The embedded Defender for Endpoint sensor runs in system context using the LocalSystem account. **The sensor uses Microsoft Windows HTTP Services (WinHTTP) to enable communication with the Defender for Endpoint cloud service.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28a4997c-0029-be57-24a3-7aa10dadda53
* Version Independent ID: 98227b02-39e2-03f6-c947-23317abb818f
* Content: [Configure device proxy and Internet connection settings](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-proxy-internet?view=o365-worldwide#feedback)
* Content Source: [microsoft-365/security/defender-endpoint/configure-proxy-internet.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-proxy-internet.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@aaronsgutierrez Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9890

Once the author approves, the changes will be live.

Thanks
Sri
