### ISSUE TITLE
Anti-spam rule 3100021

### ISSUE THREAD

**Issue by TimothyL96** [MicrosoftDocs/microsoft-365-docs#9874]
Can anyone shed light on the rule 3100021 ?

I'm randomly getting this rule and not after switching the DNS a few times.
Whenever this rule appears, the mail goes to JUNK.

Dug out all the docs and nothing is written.

**Comment by msbemba** [comment]
@TimothyL96 Thank you for your feedback. This sounds more like a technical question that needs to be routed to Microsoft support. I recommend contacting support via the need help section on the admin center.

Hope this helps!

Thanks
Sri
