### ISSUE TITLE
F5 Security is missing

### ISSUE THREAD

**Issue by Roger-Sjostrom** [MicrosoftDocs/microsoft-365-docs#9876]
From my understanding, both this doc is missing the information that this can be enabled with F5 Security also, both in headline, in text, the screenshot and where you configure it as well, I am refering this document where it says "The F5 security SKU includes the same capabilities as the E5 security offer. " https://www.microsoft.com/en-us/licensing/news/new_f5_security_and_compliance_offer_for_frontline_workers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72ac8b1f-a7cf-3487-9a3c-8eff53e4adb5
* Version Independent ID: 63773389-8a4f-926f-8430-8c80b19ff2da
* Content: [Safe Documents in Microsoft Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/safe-docs.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/safe-docs.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Thanks for the feedback.

Closing
