### ISSUE TITLE
Failure to import module as this page shows

### ISSUE THREAD

**Issue by linx-collin** [MicrosoftDocs/microsoft-365-docs#9877]
Entering the Import-Module command as shown on this page results in the following:

Import-Module : The specified module 'O365CompatibilityChecker' was not loaded because no valid module file was found in any module
directory.
At line:1 char:1
+ Import-Module O365CompatibilityChecker
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (O365CompatibilityChecker:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66ace7ce-d26f-68d0-2206-525acc513322
* Version Independent ID: 19e8d325-8074-2878-b864-cf0802e23cb0
* Content: [Determine if Centralized Deployment of add-ins works for your organization - Microsoft 365 admin](https://learn.microsoft.com/en-gb/microsoft-365/admin/manage/centralized-deployment-of-add-ins?redirectSourcePath=%252farticle%252fB4527D49-4073-4B43-8274-31B7A3166F92&view=o365-worldwide)
* Content Source: [microsoft-365/admin/manage/centralized-deployment-of-add-ins.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/manage/centralized-deployment-of-add-ins.md)
* Service: **microsoft-365-business**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@linx-collin Thank you for your feedback. I was able to test and import the module as expected. If you continue to have problems, I'd recommend contacting support via the need help option in the M365 Admin center.

![image](https://user-images.githubusercontent.com/45987684/194212132-0caf0bb1-286c-4fd3-8e97-21b39b63d896.png)


Hope this helps!

Thanks
Sri

**Comment by linx-collin** [comment]
Apologies. The point I was making is you need to first go to the web page "https://www.microsoft.com/en-us/download/details.aspx?id=55270&WT.mc_id=rss_alldownloads_all" and install the "Centralized Deployment Compatibility Checker" before the Import command will work. I just thought it would be could to mention that.

Regards


Collin Willis
Systems Reliability Engineer
London Internet Exchange Ltd
WeWork 2 Minster Court, Floor 4, Mincing Lane, London. EC3R 7BB
Tele: +44 20 7645 3525
Mobl: +44 74 0896 3117
https://www.linx.net "Working for the good of the Internet"
Registered in England number 3137929
________________________________

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@linx-collin Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9909

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @linx-collin Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
