### ISSUE TITLE
This page doesn't mention the 10 xml file limit 

### ISSUE THREAD

**Issue by KhaldounAlmarzouk** [MicrosoftDocs/microsoft-365-docs#989]
The docs should mention the fact you can only upload 10 custom rules via powershell and once you try to upload more than 10 you get the following error "The number of sensitive information type collections 10 exceeds the limit of 10"

**Comment by mypil** [comment]
@KhaldounAlmarzouk - May we know which Microsoft document link you used in reference to this issue?

Please share it with us so we can investigate further. Thank you.

**Comment by KhaldounAlmarzouk** [comment]
Hi Joyce,

I'm referring to this page
https://docs.microsoft.com/en-us/microsoft-365/compliance/create-a-custom-sensitive-information-type-in-scc-powershell

Thanks,

**Comment by chrfox** [comment]
Hi @KhaldounAlmarzouk, thank you for your comment. I am following up with the product team on this.

**Comment by mypil** [comment]
@KhaldounAlmarzouk -  Thank you for submitting feedback.

From our understanding, the issue has been resolved based on this merged commit https://github.com/MicrosoftDocs/microsoft-365-docs/commit/b85e0505fa45ca9f661fd7de10c8e7e4ed2a3ae2. 


Thank you for your contribution to make the docs better! Much appreciated!
