### ISSUE TITLE
Overlay with desktop and other cloud service IP\URL listings within MSFT

### ISSUE THREAD

**Issue by Philbbailey** [MicrosoftDocs/microsoft-365-docs#9898]
!Idea!

Allow a customer to checkbox the services they are using
eg
Windows 10 1909
M365
Intune
etc ...

They always miss at least one as they go from page to page to gather all of the needed ranges and IPs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bd8666-3566-a901-b25b-eb6baba6264a
* Version Independent ID: e9f6310f-2207-8c81-d31a-3d5a80beb26b
* Content: [Office 365 URLs and IP address ranges - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-URLs-and-IP-address-ranges-8548a211-3fe7-47cb-abb1-355ea5aa88a2&view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/urls-and-ip-address-ranges.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/urls-and-ip-address-ranges.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by yogkumgit** [comment]
@kelleyvice-msft Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
We appreciate your feedback. This page is automatically generated from a database so we can’t manually update the page. However, if you suspect there is an error in this list of URLs and IP addresses or have questions, please contact Microsoft Support.
 
To contact Microsoft 365 Support:

- Sign in to Microsoft 365 admin center with your Microsoft 365 admin account, and select **Support** > **Help and support**, enter your question, and then select **Contact support**. 

- If you're an admin on the account, you can call 800-865-9408 (toll-free, US only).
