### ISSUE TITLE
Missing supported group types for Devices

### ISSUE THREAD

**Issue by ancmarti** [MicrosoftDocs/microsoft-365-docs#9900]
[Missing supported group types for Devices
We need to have documented what types of groups are supported for Devices so Endpoint DLP. We get a lot of questions raised from our customers and because this is not documented, they are getting redirected to support. For Devices the only thing that is mentioned is that "user or group" is supported. We need to have these types of groups clearly documented. Thank you]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77dd99ae-2687-1e3f-341e-04a8e3d4acc2
* Version Independent ID: 1948ad4b-3bc1-4f49-fded-9582a854cbbd
* Content: [Data Loss Prevention policy reference - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-reference?view=o365-worldwide#locations)
* Content Source: [microsoft-365/compliance/dlp-policy-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-policy-reference.md)
* Service: **o365-seccomp**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by yogkumgit** [comment]
@chrfox Please help us in resolving this issue. Thanks

**Comment by leoisbatman** [comment]
> [Missing supported group types for Devices We need to have documented what types of groups are supported for Devices so Endpoint DLP. We get a lot of questions raised from our customers and because this is not documented, they are getting redirected to support. For Devices the only thing that is mentioned is that "user or group" is supported. We need to have these types of groups clearly documented. Thank you]
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 77dd99ae-2687-1e3f-341e-04a8e3d4acc2
> * Version Independent ID: 1948ad4b-3bc1-4f49-fded-9582a854cbbd
> * Content: [Data Loss Prevention policy reference - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/dlp-policy-reference?view=o365-worldwide#locations)
> * Content Source: [microsoft-365/compliance/dlp-policy-reference.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/dlp-policy-reference.md)
> * Service: **o365-seccomp**
> * GitHub Login: @chrfox
> * Microsoft Alias: **chrfox**

+1 - This is a big ask for customers and need some clarification in doc on which group types are supported for devices: M365 groups, security groups, distribution groups, mail-enabled security groups. Thanks!

**Comment by chrfox** [comment]
the content follows the UI, assigning this to PG
