### ISSUE TITLE
Export of Admin Center UserList reports to CSV have broken columns/data

### ISSUE THREAD

**Issue by njmarchetti** [MicrosoftDocs/microsoft-365-docs#9902]
I have feedback from customers that using the export to CSV functionality for UserList report is creating a file with data that is not aligned in the correct columns. Is that expected behavior? What is the right channel to provide feedback on that export output issue?

**Comment by msbemba** [comment]
@njmarchetti Thank you for your feedback. This looks more like an issue with the export results. You can provide feedback via the feedback option in the admin center and that will be directed to the correct team.

![image](https://user-images.githubusercontent.com/45987684/195034715-51a65ea5-7739-423e-8441-840fc4b1b422.png)


Hope this helps!

Thanks
Sri
