### ISSUE TITLE
Verification on allowed actions for locked/unlocked records

### ISSUE THREAD

**Issue by atguilmette** [MicrosoftDocs/microsoft-365-docs#9903]
Just wanted to get a sanity check on the 'allowed actions' on records management.  It would appear that there's an error in the progression between "record/unlocked", "record/locked", and "regulatory record" when it comes to the Change/Remove label actions.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Records management for documents and emails in Microsoft 365 - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide#compare-restrictions-for-what-actions-are-allowed-or-blocked)
* Content Source: [microsoft-365/compliance/records-management.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records-management.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by yogkumgit** [comment]
@cabailey Please help us in resolving this issue. Thanks

**Comment by cabailey** [comment]
@atguilmette I have no reason to believe this is incorrect. The table was signed off by the PM owner when first published, and again recently when we released the feature to start a record unlocked. For example, you can't relabel an unlocked item that's been marked as a record in SharePoint and will see the message "This record is unlocked for edit. Please lock it first before applying any label."

If the behavior you see doesn't match the documentation, please open a support ticket for investigation.
