### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DShirk** [MicrosoftDocs/microsoft-365-docs#9904]
“sub.domain.contonos.com” should be “sub.domain.Contoso.com”

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7861a800-7643-dca5-1046-232a51d6e61e
* Version Independent ID: d78fc416-516b-15ab-4719-068f7d13ecca
* Content: [Use DMARC to validate email, setup steps - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dmarc-to-validate-email?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/use-dmarc-to-validate-email.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @DShirk Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
