### ISSUE TITLE
Some undocumented behavior of Syntex

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-docs#9905]
Last time I checked, this feature was implemented in a less than ideal manner; the document-based Content Type is added to ALL libraries in the Hub and associated sites, including Site Pages, Site Assets, Style Library and even HIDDEN libraries like Converted Forms. The Item-based content type is added to ALL lists, even the "Content type publishing error log".

Additionally, the Views that are created include hidden columns like TaxonomyCatchAll and even TaxonomyCatchAll_0 if the content type contains a Managed Metadata column.

None of these gotchas are included in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4760c99-cd14-4733-1655-786ab727fa6e
* Version Independent ID: 4ef91a24-bf3a-3d0b-da44-f153b788df10
* Content: [Push content types to a hub - SharePoint Syntex](https://learn.microsoft.com/en-us/microsoft-365/contentunderstanding/push-content-type-to-hub)
* Content Source: [microsoft-365/contentunderstanding/push-content-type-to-hub.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/contentunderstanding/push-content-type-to-hub.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Please help us in resolving this issue. thanks

**Comment by MikePlumleyMSFT** [comment]
@yogkumgit please follow up with the ms.reviewer for the article. Thanks.

**Comment by yogkumgit** [comment]
@shrganguly Please help us in resolving this issue.

**Comment by sparkitect** [comment]
![image](https://user-images.githubusercontent.com/9206808/197903493-88c8ec92-9932-4ce3-8720-4b5d8c790c3a.png)
What things wrong with this View?

**Comment by sparkitect** [comment]
Even the Content Type Gallery (List) in a hub-connected site suddenly has a 'View' named for one of the pushed content types:
![image](https://user-images.githubusercontent.com/9206808/198156094-c90d7c62-95f6-4b4a-8a44-45b02948498a.png)

**Comment by sparkitect** [comment]
Content Type Publishing Error Log (is a hidden List)

![image](https://user-images.githubusercontent.com/9206808/198158142-d9c50076-39ab-4a21-950f-0bb994c9b997.png)

**Comment by yogkumgit** [comment]
@shrganguly Gentle reminder. @MikePlumleyMSFT her name does not appear in the assignee box. Please contact her offline and let her know this issue is waiting for her inputs. Will appreciate help.

**Comment by yogkumgit** [comment]
@shrganguly Thanks for the email. As you are communicating directly with customer, if you find it suitable,  please feel free to clos this issue. Thanks

**Comment by tiburd** [comment]
This information has been passed on to the product group. I'm closing this issue because they are taking it from here.

**Comment by sparkitect** [comment]
@tiburd As best as I can tell, this is still happening and is still a terrible idea, terribly implemented. A few customers have actually used it and it's made quite a mess of their environments, a mess that is very tedious to clean up :(

**Comment by tiburd** [comment]
@sparkitect 
Hi Jim,

I'm communicating with the product team. Two issues have been identified:

- **Issue 1:** ContentTypes pushed from the hub are getting added to all types of lists, including Site Pages, Site Assets, Style Library, and even HIDDEN libraries.
- **Issue 2:** The Views that are created include hidden columns like TaxonomyCatchAll, and even TaxonomyCatchAll_0 if the content type contains a Managed Metadata column.

Which issue are you still facing?

Thank you,
--Tina

**Comment by sparkitect** [comment]
I would have to test again to be sure, but in a cusotmer environement yesterday is was Issue 2 that I noticed; specifically, the TaxonomyHiddenList on a site I was working on had the custom content types.

I turned off the setting for those content types so it doesn't happen to new sites, but the damage is already done...

**Comment by tiburd** [comment]
@sparkitect 
Hi again, Jim,

Here's a response from a product team member:

> If the hidden lists are getting the contentTypes (which are pushed from Hub site) and views created from those ContentTypes – then it is #issue1.
> 
> To conform that #issue2 is still occurring – we can ask customer if the hidden columns like Bussiness Unit_0, Taxonomy Catch All Column are still getting added to the View.
> 
> User can verify this behavior in Hidden lists like ContentTypePublishingErrorLog list or any other user created lists/libraries.

Is this helpful?

Thank you.

**Comment by sparkitect** [comment]
I thought I replied to this but maybe it got lost.

It is issue #1 that I saw in a customer tenant. Specifically the TaxonomyHiddenList list.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
