### ISSUE TITLE
Option to open Microsoft Service Request missing...

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/microsoft-365-docs#9906]
Until recently, the workflow to create a new service request worked as detailed in this page. However, it seems to have changed and, whilst we are still able to select our partner or reseller to open a case with, it seems we no longer have the option to open a case with, Microsoft, at the bottom of the pane as declared here "Alternatively, select New Microsoft service request at the bottom of the pane."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Version Independent ID: 1ed50e50-a3c1-1f3b-1ea5-40beec8ab6cd
* Content: [Get support - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?redirectSourcePath=%252fen-us%252farticle%252fContact-Office-365-for-business-support-Admin-Help-32a17ca7-6fa0-4870-8a8d-e25ba4ccfd4b&view=o365-worldwide)
* Content Source: [microsoft-365/admin/get-help-support.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/get-help-support.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@deejerydoo Thank you for your feedback. We have made changes to the document via pR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9923

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by msbemba** [comment]
@yogkumgit The change has been incorporated. This can be closed.

**Comment by deejerydoo** [comment]
Just checked and can't see any change. Is there a specific timeframe for changes to replicate across production, worldwide?

**Comment by msbemba** [comment]
@deejerydoo Looks like the change did not go through. I have asked the author to merge again.

**Comment by deejerydoo** [comment]
I'm still not seeing any changes. The documentation is still showing:
" Note
If you bought your subscription through a partner, you first see the contact information for that partner. Alternatively, select New Microsoft service request at the bottom of the pane."
Document link: https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide
There is still no option to "select New Microsoft service request at the bottom of the pane."

**Comment by Mashallkhattak** [comment]
This problem still persists, unable to see New Microsoft Service Request

![image](https://user-images.githubusercontent.com/109834408/207416690-18316854-1d33-4fbe-b071-22bcdce79cab.png)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@Mashallkhattak  @yogkumgit We are still waiting for the author to merge the PR.

Thanks
Sri

**Comment by Mashallkhattak** [comment]
Thank You @msbemba

**Comment by deejerydoo** [comment]
I can confirm the "New Microsoft service request" button is now available in production. Thanks for fixing this up. Now, can I remember why was I wanting to open a support case, in October?

**Comment by olsonnn** [comment]
> I can confirm the "New Microsoft service request" button is now available in production. Thanks for fixing this up. Now, can I remember why was I wanting to open a support case, in October?

What did you do to get the button again? Missing here as well and is driving me crazy as i need ms support.

**Comment by deejerydoo** [comment]
> What did you do to get the button again? Missing here as well and is driving me crazy as i need ms support.

If you’re still unable to see the button, I can only assume that it's an issue with the way Microsoft are rolling out the change to their production environment. I am based in Australia. They may simply have not yet rolled out the fix to your region, yet. However, this is speculation that would benefit from some input from a Microsoft rep, at this point.

**Comment by ignucius** [comment]
we have the same problem. we are not able to open service requests. is there another way to open a service request?

**Comment by yogkumgit** [comment]
closing it as per author's comment in PR,
