### ISSUE TITLE
Tenant Native Links

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/microsoft-365-docs#991]
Are there some links which ATP does not rewrite at all stated by Microsoft? Like SharePoint Home Page of tenant or not? Should someone add these or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac84f75-b6d9-9495-873a-8f87b90b8034
* Version Independent ID: 18369495-0e0f-e3e1-6945-0200790fd107
* Content: [Set up a custom do-not-rewrite URLs list using Office 365 ATP Safe Links - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp)
* Content Source: [microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-a-custom-do-not-rewrite-urls-list-with-atp.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Advice on not rewriting URLs has been stated in product specific articles like SharePoint for a while (ex. https://support.office.com/en-us/article/Supportability-of-rewrites-and-redirects-in-SharePoint-2016-2013-2010-and-2007-a74a19f2-a59a-4b39-8be4-ce63e50139fa). When your URL is on the ATP do not rewrite list, ex. contoso.com, it means that ATP will not allow rewritten URLs to be visited by users. Given the entry above, that means that anyone clicking a safe link can go to the root site (contoso.com) as it appears ('contosso.com' wouldn't work). This list interrogates other 'Do not rewrite' lists and blocked lists as well, for exceptions. Any product-specific do-not-rewrites for SharePoint should be included on these lists if you don't want users to click them in chats and navigate to changed URLs, but be careful to test your entries, as SharePoint generates dynamic URLs as a normal part of operation. Add tested do-no-rewrite entries as you need to. But be aware that goal here is that the safe link will not work when clicked if the URL is rewritten as you're making your additions. Use wildcard entries only where needed.

**Comment by Kazzan** [comment]
Hi @MSFTTracyP, thanks, but I asked, if there are automatically some URL created by Microsoft which EOP ATP will ignore for rewrite to Safe Links URL.

For example, if I will add https://www.microsoft.com/ or https://portal.office.com/ in or https://mytenant.sharepoint.com/ in e-mail, if these for example will not be rewritten, because they are marked as safe automatically or not.

For example https://practical365.com/exchange-server/advanced-threat-protection-notes-field/ mentioned that https://www.google.com/ do not get rewritten. So I just want to confirm or deny such behave.
