### ISSUE TITLE
Cross referencing to other similar content

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-docs#9911]
It would be very helpful to have a page like this for every MS Defender product and links between them to make it very easy for operational teams to get this info. It is scattered in many places and anything you can do to consolidate Ops Guidance would be appreciated. It would also be great if this could be exported as a CSV so that it could be added to other systems such as Planner or Service Now.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 070967c0-919e-30de-b3c6-9c1ea3f41be5
* Version Independent ID: 070967c0-919e-30de-b3c6-9c1ea3f41be5
* Content: [Security Operations Guide for Defender for Office 365 - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/mdo-sec-ops-guide?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/mdo-sec-ops-guide.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/mdo-sec-ops-guide.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by yogkumgit** [comment]
@chrisda Please help us in resolving this issue. Thanks

**Comment by chrisda** [comment]
Definitely a good idea, but monumental in scope and time, and not really trackable via a GitHub issue.
