### ISSUE TITLE
Need warning for Government tenants here.

### ISSUE THREAD

**Issue by allenlid** [MicrosoftDocs/microsoft-365-docs#9912]
[This page is missing an all important warning for Government or GCC cloud tenants: The Migration Manager for Google is NOT available for our tenants.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a52c60e-e617-f204-187b-25bfdb413975
* Version Independent ID: 4a52c60e-e617-f204-187b-25bfdb413975
* Content: [Migrate Google files to Microsoft 365 for business - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager?view=o365-worldwide)
* Content Source: [microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/moveto-microsoft-365/migrate-files-migration-manager.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@allenlid Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9940

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @allenlid Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
