### ISSUE TITLE
Should this feature work when Azure B2B is enabled and the two SPOTenant Commands are set to true?

### ISSUE THREAD

**Issue by thomasjsweet** [MicrosoftDocs/microsoft-365-docs#9914]
[Enter feedback here]
The video is really good, but initially I could not get the steps to work. If I choose "new and existing guests" then I get a "Your org doesn't allow sharing with these people. To continue sharing, remove the highlighted recipients."  message.  

It seems changing these two commands back to false, from the true settings used to enable Azure B2B allow this feature to work.
PS C:\Windows\system32> Set-SPOTenant -SyncAadB2BManagementPolicy $false
PS C:\Windows\system32> Set-SPOTenant -EnableAzureADB2BIntegration $false

I don't need a reply for your team -my ask if you send this over to the PMs to see if I am completely off base. I admit to maybe missing something, but I have been playing with this on and off since August.

I have empathy for the work your teams put into this, and I know it is not all that easy given the moving parts. 

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01430e56-8d2c-1223-4aa1-f465118b136e
* Version Independent ID: 1d6f936a-f244-9d1a-53da-6a514f63241d
* Content: [Collaborate with guests on a document](https://learn.microsoft.com/en-us/microsoft-365/solutions/collaborate-on-documents?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/collaborate-on-documents.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/collaborate-on-documents.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@thomasjsweet Thank you for your feedback. To be able to reach out to the PMs or PGs we will need you to either open up a support ticket via the need help option in the admin center or leave you feedback on our main feedback portal - https://feedbackportal.microsoft.com/ so that someone from the product group or dev team will be able to answer your question.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @thomasjsweet Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also
