### ISSUE TITLE
Can we add clarification how long it's going to take for a user to add into a security group to be able to do external sharing after configuring "Allow only users in specific security groups to share externally"?

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/microsoft-365-docs#9915]
regarding "Allow only users in specific security groups to share externally" option, after the customer configured this option and define a security group, they noticed that it took various time for people who added into a security to be able to share to the external users. Can we add some description/duration/SLA how long the security group member changes can get effect? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 030743fd-0c22-025b-f190-f637a2772506
* Version Independent ID: fbded472-e3ea-4297-c527-810e117ea7ea
* Content: [Microsoft 365 guest sharing settings reference](https://learn.microsoft.com/en-us/microsoft-365/solutions/microsoft-365-guest-settings?view=o365-worldwide)
* Content Source: [microsoft-365/solutions/microsoft-365-guest-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/solutions/microsoft-365-guest-settings.md)
* Service: **o365-solutions**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by msbemba** [comment]
@frankchen76 Thank you for your feedback. I tested it in a couple of test tenants and it works with immediate effect (less than 1 minute). Not sure, if all users in the tenant are facing the issue, however, I'd recommend reporting a bug to Microsoft via the need help section in case the issue continues.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @frankchen76 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also

**Comment by frankchen76** [comment]
unfortunately, this is something not very clear. from a few of my customers which has large tenant, they found out changes were not immediately populated and somehow tool longer hours which can be varied from a few minutes to 8 hours. that's why they would like to have clarification. another thing I also think about is since I heard this AAD security group sync relies on SPO User Profile service sync which we don't typically have a SLA for that, it probably makes sense to mention that this feature uses User Profile Synchronization so that people can refer back to user profile sync to standardize the communication. Thanks
