### ISSUE TITLE
Mistranslation in Japanese version

### ISSUE THREAD

**Issue by tamiyatxt1** [MicrosoftDocs/microsoft-365-docs#9917]
[Enter feedback here]
"Health record" is translated into "正常性レコード" in Japanese version.
As "正常性" means "normality", not "health" in Japanese.
In IRM settings page, we describe it as "健康記録".
This is natual for Japanese and we have to make the notation the same.

English version:
Health record access indicators (preview):
Japanese version:
正常性レコード アクセス インジケーター (プレビュー):
![image](https://user-images.githubusercontent.com/45841593/194981361-792b6988-18a5-4e68-bc69-6d86746e4562.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5147f5e8-a267-ee55-de12-d80ab29804c2
* Version Independent ID: 945fc70f-1861-d2e9-4d46-f56eafb53766
* Content: [Insider risk management settings - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/insider-risk-management-settings?view=o365-worldwide#indicators)
* Content Source: [microsoft-365/compliance/insider-risk-management-settings.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/insider-risk-management-settings.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@tiburd Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [233747](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/233747)

I'm closing this issue because the Global Services team will handle it from here.
