### ISSUE TITLE
Request for adding examples of "Other Plans"

### ISSUE THREAD

**Issue by sasaito** [MicrosoftDocs/microsoft-365-docs#9925]
[Enter feedback here]
Could you add examples of Other Plans? 
Customers using Microsoft 365 Business Basic, Standard, and Premium can find it difficult to determine that they fall under the “Other Plans”. 
Phone number
0120 628 860 (Other Plans) → 0120 628 860 (Other Plans e.g. Microsoft 365 Business Basic, Standard, Premium)
Technical Support:
Other Plans: -> Other Plans e.g. Microsoft 365 Business Basic, Standard, Premium:
Local call charges apply:
03 4332 6257 (Other Plans) → 03 4332 6257 (Other Plans e.g. Microsoft 365 Business Basic, Standard, Premium)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3618e4-be59-8a6f-92c8-cd915c63313d
* Version Independent ID: 9caeb339-7a2b-a2ce-4850-61896ea68825
* Content: [Support information for Japan - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/support/japan?view=o365-worldwide)
* Content Source: [microsoft-365/admin/support/japan.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/support/japan.md)
* Service: **microsoft-365-business**
* GitHub Login: @cmcatee-MSFT
* Microsoft Alias: **cmcatee**

**Comment by msbemba** [comment]
@sasaito Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9941

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@sasaito Closing as per author's comment. Thanks

**Comment by msbemba** [comment]
@yogkumgit This can be closed as well as the japan.md article was retired and replaced with [Find Microsoft 365 for business phone support numbers by country or region](https://learn.microsoft.com/en-us/microsoft-365/admin/support-contact-info?view=o365-worldwide)

**Comment by sasaito** [comment]
Thank you for this update.
I am looking at [Find Microsoft 365 for business phone support numbers by country or region](https://learn.microsoft.com/en-us/microsoft-365/admin/support-contact-info?view=o365-worldwide), but I can't see the examples for other plans in Japan region. Is it expected?
