### ISSUE TITLE
PowerShell code does not work as supposed

### ISSUE THREAD

**Issue by justinasval** [MicrosoftDocs/microsoft-365-docs#9926]
Hello,

I've tested out and want to let you know, that one of the PowerShell code's for licensing does not work.

**Assigning licenses to user accounts**

$userLicense = Get-MgUserLicenseDetail -UserId "belinda@fdoau.onmicrosoft.com"
$userDisabledPlans = $userLicense.ServicePlans | 
    Where ProvisioningStatus -eq "Disabled" | 
    Select -ExpandProperty ServicePlanId

$e5Sku = Get-MgSubscribedSku -All | Where SkuPartNumber -eq 'SPE_E5'
$newDisabledPlans = $e5Sku.ServicePlans | 
    Where ServicePlanName -in ("SWAY", "FORMS_PLAN_E5") | 
    Select -ExpandProperty ServicePlanId

**$disabledPlans = ($userDisabledPlans + $newDisabledPlans) | Select -Unique**

$addLicenses = @(
    @{
        SkuId = $e5Sku.SkuId
        DisabledPlans = $disabledPlans
    }
)

Set-MgUserLicense -UserId "belinda@litwareinc.onmicrosoft.com" -AddLicenses $addLicenses -RemoveLicenses @()

**Line:**  `$disabledPlans = ($userDisabledPlans + $newDisabledPlans) | Select -Unique`

If there are already some disabled plans - it will merge all the plans IDs to the one long ID (string):

**ERROR**:
_Set-MgUserLicense : Cannot convert the literal '**b76fb638-6ba6-402a-b9f9-83d28acb3d86a23b959c-7ce8-4e57-9140-b90eb88a9e97**' to the expected type 'Edm.Guid'._

Please fix it.  I have not found solution on myself yet. Tried to pass array, but it still does not work.

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 073b885d-191e-8c00-fa59-ad83ba79ec10
* Version Independent ID: 4bd5799d-9baf-90b6-634d-398fbea6b66f
* Content: [Assign Microsoft 365 licenses to user accounts with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@justinasval Thank you for your feedback. I will test this script and update the document if need be.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Gentle reminder.

**Comment by msbemba** [comment]
@yogkumgit This is still in the testing phase and I will update it shortly. 

Thanks
Sri

**Comment by msbemba** [comment]
@justinasval Thank you for your feedback. We have tested and it works well as explained in the example. This works only when there is one subscription like mentioned in the document (M365 E5)

This example updates a user with SPE_E5 (Microsoft 365 E5) and turns off the Sway and Forms service plans while leaving the user's existing disabled plans in their current state.

I have also updated the script with the correct email address as that was incorrect, this can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10061

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @justinasval Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by el-vicente** [comment]
Hi @msbemba, Has this been resolved? I think the problem here is when we merge the disabled plans. You won't see an error if there are no existing plans to add to the target plan to disable.

here is an example, the error below shows is for teams plan (existing disabled plan + yammer. I think the command expect it to be in ID then comma?

Set-MgUserLicense : Cannot convert the literal '57ff2da0-773e-42df-b2af-ffb7a23179292078e8df-cff6-4290-98cb-5408261a760a' to the expected type 'Edm.Guid'.
 
here is the output when you run the $disableplan to merge exiting disabled plan + target plan to disable

PS C:\WINDOWS\system32> $disabledPlans
57ff2da0-773e-42df-b2af-ffb7a23179292078e8df-cff6-4290-98cb-5408261a760a
