### ISSUE TITLE
Different PhishThresholdLevel recommendations

### ISSUE THREAD

**Issue by rafaelborter** [MicrosoftDocs/microsoft-365-docs#9928]
Hello all
I have a question regarding the anti-phish policy recommendation for PhishThresholdLevel:

The Microsoft recommendations / docs do not match the recommendation from the Configuration analyzer in the O365 portal. Which recommendation is valid now? As far as I can remember, the recommendation in the Configuration analyzer came later. Can you please make sure that this page matches the recommendation from the Configuration analyzer?

MS recommendations / Docs
- Advanced settings in anti-phishing policies in Microsoft Defender for Office 365
- PhishThresholdLevel
- Standard: 2 - Aggressive
- Strict: 3 - More aggressive

Configuration analyzer
- Advanced phishing thresholds
- Standard: 3
- Strict: 4

![ca](https://user-images.githubusercontent.com/75986989/195103309-7301bd53-c6e7-4288-9d44-8c6e68a254c7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c77e1cb-1509-83cc-7c2a-564d5e3e91ea
* Version Independent ID: 9f07278c-37ab-beac-a5dd-fa4f4825b3a4
* Content: [Microsoft recommendations for EOP and Defender for Office 365 security settings - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rafaelborter, OK. Fixed.

Thanks for the feedback.

Closing
