### ISSUE TITLE
In which format to attach e-mails to report as phishing?

### ISSUE THREAD

**Issue by nxtof** [MicrosoftDocs/microsoft-365-docs#993]
The page mentions that in order to submit a phishing message to microsoft, one should attach the message to the e-mail sent to phish@:

```
o submit a junk or phishing scam message to Microsoft:

    Create a blank email message.

    Address the message to the Microsoft team that reviews messages, as follows:

    For junk messages: junk@office365.microsoft.com

    For phishing scam messages: phish@office365.microsoft.com

    Copy and paste the junk or phishing scam message into the new message as an attachment.
```

Can you clarify what should be the format of the attached e-mail? Do both .msg and .eml work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b12c078-eccb-7786-dec6-ea1bdb91d088
* Version Independent ID: aa1e8002-a8db-383e-cbeb-abf92c033bd3
* Content: [Submit spam, non-spam, and phishing scam messages to Microsoft for analysis - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis)
* Content Source: [microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/submit-spam-non-spam-and-phishing-scam-messages-to-microsoft-for-analysis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by chrisda** [comment]
@nxtof, your request was addressed in PR #1011, so closing this issue.

Thanks for the feedback.
