### ISSUE TITLE
Wrong hyperlink

### ISSUE THREAD

**Issue by kohnpier** [MicrosoftDocs/microsoft-365-docs#9931]
Hi, the link "[Set app protection settings for Android or iOS devices](https://learn.microsoft.com/en-us/microsoft-365/business-premium/m365bp-app-protection-settings-for-android-and-ios?view=o365-worldwide)"  actually points to "https://learn.microsoft.com/en-us/microsoft-365/business-premium/m365bp-protect-devices?view=o365-worldwide" which is mostly Windows

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24a04db7-c32a-6120-bea9-5ec539b8e830
* Version Independent ID: ef61ea9c-fa9a-c93f-effd-d03d1a627904
* Content: [What is the difference between device and app management - Microsoft 365 Business](https://learn.microsoft.com/en-us/microsoft-365/business/ui/mam-and-mdm?view=o365-worldwide)
* Content Source: [microsoft-365/business/ui/mam-and-mdm.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/business/ui/mam-and-mdm.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@kohnpier Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9942

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kohnpier Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
