### ISSUE TITLE
اريد معرفة كيف يتم استرجاع نسخة ويندوذ من برنامج one drive 

### ISSUE THREAD

**Issue by electronic256** [MicrosoftDocs/microsoft-365-docs#9932]
اريد ممعرفة كيف استرجع  نسخة من Backup  من الويندوذ في حالة حدوث خلل فية من جهاز كمبيوتر من one drive

**Comment by yogkumgit** [comment]
@electronic256  Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
