### ISSUE TITLE
Command line intune trash

### ISSUE THREAD

**Issue by gregmahhn** [MicrosoftDocs/microsoft-365-docs#9935]
Why all the Powershell/command line trash to manage Intune/defender. It's 2022, not 1980. We paid a ton of money for this pile of DOS/AD policies pretending to be a security tool, that can't even do white listing/trusted apps, SSO for encryption, (I have a long list). We are implementing intune/defender and the blatant lack of security features is frightening. Sure it's got a million and one ways to pull reports, so executives will think it's glory. But as a tech, using MS for support and they can't even get the firewall to allow; by Policy our apps to run.... it's so disappointing. That big E5 license is not worth the money yet. MS please bring intune/defender into the present and replace all the xml and cmdlets and powershell with a GUI - like every AV company besides you has.

**Comment by yogkumgit** [comment]
@gregmahhn Please indicate which document you are referring to. Thanks

**Comment by yogkumgit** [comment]
@gregmahhn Thank you very much for the contribution and digging deep into it.  @ We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
Please feel free to re-open this issue if you see an improvement is required in the specific area of this documentation. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by gregmahhn** [comment]
sorry, was venting, nothing anyone can do. First use of github, and I did it wrong. thanks, bye
