### ISSUE TITLE
Consider adding mention of the OneNote LTI integration

### ISSUE THREAD

**Issue by sjgadsby** [MicrosoftDocs/microsoft-365-docs#9937]
If its omission wasn't intentional, a section on the OneNote LTI integration could be added to this page.
https://www.onenote.com/lti

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 699da01d-e317-390b-cdb6-67ce21b80d30
* Version Independent ID: eeb105a1-d032-fdd5-3bef-6972fb2919f6
* Content: [An overview of Microsoft LTI apps](https://learn.microsoft.com/en-us/microsoft-365/lti/?view=o365-worldwide)
* Content Source: [microsoft-365/lti/index.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/lti/index.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by msbemba** [comment]
@sjgadsby Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9966

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by DaniEASmith** [comment]
@sjgadsby & @msbemba I've merged the PR and should publish today.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @sjgadsby Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
