### ISSUE TITLE
Video is broken

### ISSUE THREAD

**Issue by PedroCSilvestre** [MicrosoftDocs/microsoft-365-docs#9939]
[Video is broken - not showing in line]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 491b4be2-0e86-118d-5d51-46a6c4a00048
* Version Independent ID: 3480ef34-54d8-6007-61d4-a0210e1853c3
* Content: [Configure and manage Microsoft Threat Experts capabilities](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-microsoft-threat-experts?wt.mc_id=SecNinja_mdeninja&view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-microsoft-threat-experts.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-microsoft-threat-experts.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @DulceMontemayor
* Microsoft Alias: **dolmont**

**Comment by msbemba** [comment]
@PedroCSilvestre Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9973

Once the author approves, the changes will be live.

Thanks
Sri
