### ISSUE TITLE
use label to classify content as a record- Not Available

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/microsoft-365-docs#994]
I understand that we are moving Security and Compliance center Retention Labels features from https://protection.office.com/retentionlabels  to https://compliance.microsoft.com/informationgovernance?viewid=labels.
But it seems that in new portal we don't have the option to select "use label to classify content as a record" while creating a new label. Is this intentional or would this feature be transitioned later to new Security and Compliance center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae5f811-9551-ea95-b113-9175a6f08d7e
* Version Independent ID: e1eb8d3d-d439-e814-4a05-aa5bbc11f33e
* Content: [Overview of records - Microsoft 365 Compliance](https://docs.microsoft.com/en-us/microsoft-365/compliance/records#feedback)
* Content Source: [microsoft-365/compliance/records.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/records.md)
* Service: **o365-seccomp**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by markjjo** [comment]
@3novsan There is a new Records management page in the M365 compliance center, where you can create a retention label that declares content as a record. That page is https://compliance.microsoft.com/recordsmanagement?viewid=fileplan

Also see  https://docs.microsoft.com/en-us/microsoft-365/compliance/records#using-retention-labels-to-declare-records
