### ISSUE TITLE
Can we re-evaluate the content under "Prevent installation of removable devices" as the note says that "To enable the Allow installation of devices using drivers that match these device setup classes, Allow installation of devices that match any of these device IDs, and Allow installation of devices that match any of these device instance IDs policy settings to supersede this policy setting for applicable devices, enable the Apply layered order of evaluation for Allow and Prevent device installation policies across all device match criteria policy setting." However it is not correct, as the allow policy won’t take precedence if the Block Removable Storage option is selected in Device Control

### ISSUE THREAD

**Issue by PremMS-MDE** [MicrosoftDocs/microsoft-365-docs#9946]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf5df26b-9563-4810-f5b8-6997c9baa27c
* Version Independent ID: 006f5550-36b6-1de7-d3a5-63b85241df03
* Content: [Microsoft Defender for Endpoint Device Control Device Installation](https://review.learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mde-device-control-device-installation?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/mde-device-control-device-installation.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by msbemba** [comment]
@PremMS-MDE Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9974

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @PremMS-MDE Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by PremMS-MDE** [comment]
Hi @msbemba the change is still not reflected in article.
