### ISSUE TITLE
Safety tip mechanism not explained

### ISSUE THREAD

**Issue by TLepingwell** [MicrosoftDocs/microsoft-365-docs#9948]
The article does not explicitly state how safety tips are implemented. The [Safety Tip section](https://learn.microsoft.com/microsoft-365/security/office-365-security/set-up-anti-phishing-policies#first-contact-safety-tip) mentions that the custom header **X-MS-Exchange-EnableFirstContactSafetyTip** is set to "Enable" by the safety tip setting. But it does not explain how the tip is rendered by the client.

It is unclear if the email client is supposed to render the safety tip based on the value of the header, or if the email server rewrites the body of the email by injecting the warning text. It turns out it operates by injecting the warning directly into the email.

I found a [third-party claim](https://petri.com/exchange-online-protection-safety-tips/) that EOP will not rewrite the bodies of S/MIME signed emails with safety tips as this would prevent the signature from being successfully verified. But I was not able to find any mention of this in official Microsoft documentation.

A detailed description of Safety Tip's implementation and how it interacts with email signing should be present in the Microsoft documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0b8f651-9d8e-a34b-8dde-2b6a9448f875
* Version Independent ID: 20e96426-627d-9973-8303-a43a114c7b61
* Content: [Anti-phishing policies - Office 365](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-anti-phishing-policies?view=o365-worldwide)
* Content Source: [microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/set-up-anti-phishing-policies.md)
* Service: **microsoft-365-security**
* Sub-service: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
Updates for article were waiting to publish, but I never pulled the trigger. I just pulled the trigger.

Thanks for the feedback.

Closing
