### ISSUE TITLE
Request to revise the feature table provided by Microsoft Defender for Endpoint P2

### ISSUE THREAD

**Issue by kahosoka** [MicrosoftDocs/microsoft-365-docs#9957]
Hi Team,

The published information below lists the features of Microsoft Defender for Endpoint P2 (MDE P2).

Compare Microsoft endpoint security plans:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide#compare-microsoft-endpoint-security-plans-1

In it, the scope of support for Windows is described as (Client and Server).
As also noted below, we understand that MDE P2 does not support Server OS.
Therefore, we would appreciate it if you could consider whether it is possible to modify Learn as follows.

Options for onboarding servers:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide#options-for-onboarding-servers

An idea：
Support for Windows (**client and server**) and non-Windows platforms (macOS, iOS, Android, and Linux)
　→ Support for Windows (**client only**) and non-Windows platforms (macOS, iOS, Android, and Linux)

Best Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec57328d-4b17-abe6-001e-c5ecb2f00746
* Version Independent ID: be98599a-b690-a3e6-c610-8da71fd80d76
* Content: [Compare Microsoft endpoint security plans](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2?view=o365-worldwide#options-for-onboarding-servers)
* Content Source: [microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/defender-endpoint-plan-1-2.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@kahosoka Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9976

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @kahosoka Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
