### ISSUE TITLE
Scheduled scan, which time zone?

### ISSUE THREAD

**Issue by jaegerschnitzel** [MicrosoftDocs/microsoft-365-docs#9958]
We configured a scheduled scan worldwide on Wednesday 10 a.m. But I'm not sure if these setting "translates" to the local time zone or if UTC is used. Can you clarify this and perhaps add this into your documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72be33f7-fd1f-3b0c-00c0-8d448a2cfdd3
* Version Independent ID: 0cf78d5c-8c46-8088-36c4-70fcdaf142ff
* Content: [Schedule regular quick and full scans with Microsoft Defender Antivirus](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/schedule-antivirus-scans?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/schedule-antivirus-scans.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/schedule-antivirus-scans.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by msbemba** [comment]
@jaegerschnitzel Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9977

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @jaegerschnitzel Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
