### ISSUE TITLE
Many fluctuations in translation in Japanese version

### ISSUE THREAD

**Issue by tamiyatxt1** [MicrosoftDocs/microsoft-365-docs#9962]
[Enter feedback here]
As attached, the sentence "non-custodial" is transrated into 4 shape in Japanese version.
If we unify the translation of "Custodian" as "カストディアン", I think "non-custodial" should be unified into "非カストディアン" to prevent confusion. Please discuss this tech writers' side.
![image](https://user-images.githubusercontent.com/45841593/195968853-77db86d7-9441-43e2-a28f-3387fdf4eca1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 400510d5-c0a9-09fa-b62f-abb54978704f
* Version Independent ID: 1860f5a7-fe42-08f3-177f-a3f3020a13cc
* Content: [Add non-custodial data sources to an eDiscovery (Premium) case - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/non-custodial-data-sources?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/non-custodial-data-sources.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/non-custodial-data-sources.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by yogkumgit** [comment]
@tiburd Please help us in resolving this issue. Thanks

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [235479](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/235479)

I'm closing this issue because the Global Services team will handle it from here.

**Comment by tiburd** [comment]
Reported as fixed.
