### ISSUE TITLE
Advanced should be changed to Premium

### ISSUE THREAD

**Issue by tamiyatxt1** [MicrosoftDocs/microsoft-365-docs#9963]
[Enter feedback here]
As "Advanced eDiscovery" was changed to "eDiscovery Premium", old name should be changed to "Premium".
There are some sentences such as "eDiscovery > Advanced" in this page, need to change "eDiscovery > Premium".
Besides, the old name "Advanced" causes mistranslation in Japanese version, I expect correcting English version can resolve mistranslation.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 115cfe0b-c8b5-193d-19da-a6f9c03fdfc0
* Version Independent ID: 4a90cb9e-ce2a-a3f6-4b67-32f45c975323
* Content: [Manage holds in eDiscovery (Premium) - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/managing-holds?view=o365-worldwide#manage-custodian-based-holds)
* Content Source: [microsoft-365/compliance/managing-holds.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/managing-holds.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@tamiyatxt1 Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9978

Once the author approves the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@tamiyatxt1 closing it as per author's comment in PR. Thanks

**Comment by msbemba** [comment]
@yogkumgit  This can be closed.

**Comment by Cee3097** [comment]
_verification requested
Can't retrieve proper documentation on GitHub site
Twitter involment unconstitutional
