### ISSUE TITLE
Minimum Lead Time - Does it Consider Business Hours? Or just Regular Hours?

### ISSUE THREAD

**Issue by RaphaelUlysses** [MicrosoftDocs/microsoft-365-docs#9964]
[Enter feedback here]

Hello! It is unclear if the minimum lead time is hours in general or if it respects business hours. I would like to know if it does respect business hours so I can make an appropriate feature request if not. It would be helpful if the KB article reflected this information. 

For example, I would want 48 hours of lead time in business hours, so a Friday afternoon booking would show next available at Wednesday, instead of Monday. Does this make sense?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93466e00-def6-6d4c-6705-04cb62a32945
* Version Independent ID: 4e862a20-81c3-991d-6d6f-343b99503408
* Content: [Set Bookings scheduling policies](https://learn.microsoft.com/en-US/microsoft-365/bookings/set-scheduling-policies?view=o365-worldwide)
* Content Source: [microsoft-365/bookings/set-scheduling-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/bookings/set-scheduling-policies.md)
* Service: **bookings**
* GitHub Login: @kwekuako
* Microsoft Alias: **kwekua**

**Comment by msbemba** [comment]
@RaphaelUlysses Thank you for your feedback. The minimum lead time considers Regular hours and not business hours. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/9979

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @RaphaelUlysses Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
