### ISSUE TITLE
Hygiene DAL error

### ISSUE THREAD

**Issue by deniz-yilmaz** [MicrosoftDocs/microsoft-365-docs#997]
Clicking "Permissions" in Office 365 Security & Compliance gives a client error of "The Hygiene DAL encountered a permanent exception." Following the instructions to do the same in powershell gives the same error.

Is there a workaround to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e7332f-6c1d-19cf-dc71-4cebaa93c1cc
* Version Independent ID: a8e4bd77-725f-af7a-63bc-95d8ea92f554
* Content: [Give users access to the Office 365 Security & Compliance Center - Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/grant-access-to-the-security-and-compliance-center#feedback)
* Content Source: [microsoft-365/security/office-365-security/grant-access-to-the-security-and-compliance-center.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/office-365-security/grant-access-to-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mypil** [comment]
@deniz-yilmaz - Thank you for submitting feedback.

I think the best way forward is if you can open a **[service ticket](https://docs.microsoft.com/office365/admin/contact-support-for-business-products)** in your tenant so this can get resolved ASAP. Based on outcome, let us know if it is something that can be called out in the docs.


If you don't mind please keep us posted here on the resolution so we can get the applicable information you are discovering back into the docs.
