### ISSUE TITLE
Defender ADMX Pack - 21H2?

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/microsoft-365-docs#9971]
Did this ever happen?  I don't see it in the revised "Windows 10 21H2 - 10 November 2021 V2" pack that got released and there's not been another...  Keen to have the Warn mode in GPO...

" Note
An updated Defender ADMX template will be published together with the 21H2 release of Windows 10. A non-localized version is available for download at https://github.com/microsoft/defender-updatecontrols. "

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f65bc58-aab1-16bb-4a4b-30a21491ca99
* Version Independent ID: ee076a7a-4abb-6664-3c78-735ffaf3fd54
* Content: [Create a custom gradual rollout process for Microsoft Defender updates](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/configure-updates?view=o365-worldwide)
* Content Source: [microsoft-365/security/defender-endpoint/configure-updates.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/configure-updates.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by msbemba** [comment]
@mattsmacblog Thank you for your feedback. The updated ADMX template is available here -https://github.com/microsoft/defender-updatecontrols/blob/main/WindowsDefender.admx

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @mattsmacblog Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mattsmacblog** [comment]
Thanks, any plans to get it rolled into the Normal ADMX packs that get distributed though?
i.e. the 22H2 pack came out 3 weeks ago but it doesn't have these github updated versions - https://www.microsoft.com/en-us/download/confirmation.aspx?id=104677
