### ISSUE TITLE
Add mention that following the "Move mailboxes back to the original source" instructions will stop migrations to destination from working.

### ISSUE THREAD

**Issue by unearthnz** [MicrosoftDocs/microsoft-365-docs#9972]
Currently the section "Move mailboxes back to the original source" mentions to run the steps the other way around to enable migrations from destination back to source.

What it fails to mention is that this will reverse the existing Organization Relationship attribute "MailboxMoveCapability" on both sides, which will prevent migrations from source to destination (MailboxMoveCapability can only be either Inbound or Outbound - not both directions).

Therefore, can I suggest the document is updated to reflect the fact migrations cannot work both ways simultaneously. To achieve this, you would need to change the MailboxMoveCapability attribute on both sides back and forward constantly which isn't feasible.

Side note: I assume there is no way to create an org relationship for each direction to allow simultaneous migrations, given you can only mention a remote domain name in a single policy at one time?

https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#move-mailboxes-back-to-the-original-source

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c61c960c-f5c3-76f7-ac18-dfeaf30230e4
* Version Independent ID: 3dc607b2-869e-976f-80da-d73cfb1210e5
* Content: [Cross-tenant mailbox migration - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#move-mailboxes-back-to-the-original-source)
* Content Source: [microsoft-365/enterprise/cross-tenant-mailbox-migration.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/cross-tenant-mailbox-migration.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by msbemba** [comment]
@unearthnz Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10005

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @unearthnz Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
