### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by neilcalgary** [MicrosoftDocs/microsoft-365-docs#9985]
[Enter feedback here]

This article (https://learn.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-alert-policies?view=o365-worldwide) reads:
"To create alert policies, you have to be assigned the Manage Alerts role or the Organization Configuration role in the compliance portal or the Defender portal."

And this article (https://learn.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-alert-policies?view=o365-worldwide) reads:
"To create or update alert policies: the Compliance administrator, Compliance data administrator, Security administrator, or Security operator role in Azure AD"

Are they different alert policies?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2879ba-e58e-cd47-f488-10d153c31418
* Version Independent ID: 391a2c05-d63d-e84e-7c7d-80c3b3518419
* Content: [Microsoft 365 alert policies - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/alert-policies.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/alert-policies.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@neilcalgary Thank you for your feedback. We have made changes to the document to reflect the correct permissions. This can be tracked via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10006

Once the author approves, the changes will be live.

Thanks
Sri
