### ISSUE TITLE
SLA info?

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/microsoft-365-docs#9988]
Seems you have removed the table with SLA data, yet the FAQ still refers to it:

> How long does it take for an auditing record to be available after an event has occurred?
> 
> Most auditing data is available within 30 minutes but it may take up to 24 hours after an event occurs for the corresponding audit log entry to be displayed in the search results. See the table in the [Before you search the audit log](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-search-the-audit-log) section of this article that shows the time it takes for events in the different services to be available.

Should we update the answer to this question?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3494b782-92ad-e365-3398-bd2d760d10c6
* Version Independent ID: fa4bca98-3975-23dd-dfac-f23049c71d01
* Content: [Search the audit log in the Microsoft Purview compliance portal - Microsoft Purview (compliance)](https://learn.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide)
* Content Source: [microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by msbemba** [comment]
@michevnew Thank you for your feedback. We have made changes to the document via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10007

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@michevnew Thanks for your feedback! New issues and pull requests for this content are closed while we update this content to support upcoming feature improvements.
