### ISSUE TITLE
SFB Online, is it supported or not

### ISSUE THREAD

**Issue by robgeach** [MicrosoftDocs/microsoft-365-docs#9992]
Why are you gumming up your own documentation for Teams DNS requirements with a product you no longer support?

https://learn.microsoft.com/en-us/microsoft-365/enterprise/external-domain-name-system-records?view=o365-worldwide#external-dns-records-required-for-teams-and-skype-for-business-online

You have lyncdiscover as a cname included twice, and one entry says teams still requires it while the other entry says it's only required for SFB Online.  Just get rid of all the unsupported product information and list the Teams DNS requirements.

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @robgeach Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
