### ISSUE TITLE
"The portal" is vague

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/microsoft-365-docs#9997]
Need a link to which portal page this is referring to, as there have been recent changes and it doesn't appear to exist anymore. Other articles discussing these changes are also using the old setup of Endpoint which is now Intune. 

The only way I found to add tags was going to Intune, select Tenent Admin, Roles, then Scope to add it. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51c29286-b601-4dad-0e65-227c8d045ee4
* Version Independent ID: 2af4acf9-4089-5dff-d628-16b8425e0a57
* Content: [Create and manage device tags](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/machine-tags?view=o365-worldwide&viewFallbackFrom=o365-worldwide.)
* Content Source: [microsoft-365/security/defender-endpoint/machine-tags.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/security/defender-endpoint/machine-tags.md)
* Service: **microsoft-365-security**
* Sub-service: **mde**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by yogkumgit** [comment]
@mjcaparas Please help us in resolving this issue. Thanks

**Comment by mjcaparas** [comment]
The portal has been unified in Microsoft 365 Defender.
