### ISSUE TITLE
Link needs updating

### ISSUE THREAD

**Issue by chriscam85** [MicrosoftDocs/microsoft-365-docs#9999]
The link found in the "Before you begin" section needs to be updated. When I click it (https://go.microsoft.com/fwlink/p/?linkid=2024339), I just land on the admin portal homepage instead (https://admin.microsoft.com/adminportal/home?#/homepage).
Maybe this is a link for the old layout? I'm using the newer version of admin (released ~1+yrs ago), but can't find the toggle to use the old version to verify.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65732911-21e9-0902-51fa-0d3ae0caaa7a
* Version Independent ID: 3682fff5-36fc-1d69-96ef-88f7f73225d5
* Content: [Enable Microsoft 365 usage analytics - Microsoft 365 admin](https://learn.microsoft.com/en-us/microsoft-365/admin/usage-analytics/enable-usage-analytics?view=o365-worldwide)
* Content Source: [microsoft-365/admin/usage-analytics/enable-usage-analytics.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/usage-analytics/enable-usage-analytics.md)
* Service: **microsoft-365-business**
* GitHub Login: @efrene
* Microsoft Alias: **efrene**

**Comment by msbemba** [comment]
@chriscam85 Thank you for your feedback. We have updated the navigation to initiate the template for usage analytics via PR#https://github.com/MicrosoftDocs/microsoft-365-docs/pull/10035

Once the author approves, the changes will be live.

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and updating the documentation with PR. @chriscam85 Hope this update is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
